### ISSUE TITLE
Discharge Upgrade Wizard - Fix the VA Form 10-5345 link

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#25124]
## Issue Description
VA Form 10-5345 link is busted. Form PDF URL was updated December of 2020. We are going to change the current URL in the app to the new URL.

See this comment => https://github.com/department-of-veterans-affairs/va.gov-team/issues/25065#issuecomment-846189635 

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] Exchange old link with working one.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I love this highly technical description: _VA Form 10-5345 link is busted_  🤣

**Comment by zacharymorel** [comment]
This should be live in 30!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel thank you! Staging, right?

**Comment by zacharymorel** [comment]
Yep

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO the fix is live on staging!
![Screen Shot 2021-05-25 at 3 47 11 PM](https://user-images.githubusercontent.com/26075258/119559368-8f1d9700-bd70-11eb-81ed-e3cca4e5aa35.png)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Thank you! Looking at it now.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO this good to close?

**Comment by MarciMcGuireGCIO** [comment]
Yup!
