### ISSUE TITLE
5490: Update FRY helper content and update date of death question

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25122]
As a developer, I need to update the 5490 application so that it is compliant with recent legislation and the applicant is able to successfully and accurately complete the application so that it can be processed in a timely manner.

## Assumptions:
1. This work is completed behind feature flag `edu_form5490_updates` #25123 
2. The form is located [here](https://staging.va.gov/education/apply-for-education-benefits/application/5490/introduction) on staging.

## Acceptance Criteria:
1. In Chapter 2, Page 1, the helper text displayed after selecting "The Fry Scholarship (Chapter 33)" when the user answered "Spouse or surviving spouse" to the question "What’s your relationship to the service member whose benefit is being transferred to you?" is:

> I understand that I am choosing to receive Fry Scholarship benefits instead of any DEA benefits for which I am currently eligible.  This includes DEA benefits based on:
> - the death of the qualifying individual listed in this application and/or the qualifying death of any others not listed, or
> - a spouse who has a permanent and total service-connected disability, or 
> - based on any other criteria as listed in 38 U.S.C. § 3501(a)(1) .

#### When the selected benefit in Chapter 2, Page 1 is: The Fry Scholarship (Chapter 33):

2. In Chapter 3, Page 1, the following question is not displayed:

> Sponsor's date of death or date listed as MIA or POW

3. In Chapter 3, Page 1, the last question on the page is:

> Do any of these situations apply to your sponsor?

4. The available answers to the question in AC3 are:
    a. Died while serving on active duty or duty other than active duty
    b. Died from a service-connected disability while a member of the Selected Reserve
    c. Listed as MIA or POW

5. The question in AC3 is not required.

6. When the user selects the answer `Died while serving on active duty or duty other than active duty`:
    a. The question `Sponsor's date of death` is conditionally displayed
    b. The question `Sponsor's date of death` is conditionally displayed is not required
    c. The question `Sponsor's date of death` accepts a date value

7. When the user selects the answer `Died from a service-connected disability while a member of the Selected Reserve`:
    a. The question `Sponsor's date of death` is conditionally displayed
    b. The question `Sponsor's date of death` is conditionally displayed is not required
    c. The question `Sponsor's date of death` accepts a date value

8. When the user selects the answer `Listed as MIA or POW`:
    a. The question `Sponsor's date listed as MIA or POW` is conditionally displayed
    b. The question `Sponsor's date listed as MIA or POW` is conditionally displayed is not required
    c. The question `Sponsor's date listed as MIA or POW` accepts a date value

9. The question in the spool file `Sponsor's date of death or date listed as MIA or POW` is removed from the spool file.

10. The user selected answer to the question "Do any of these situations apply to your sponsor?" and the corresponding date are included in the spool file.  (Ex. `Died from a service-connected disability while a member of the Selected Reserve`: MM-DD-YYYY)

#### When the selected benefit when the selected benefit in Chapter 2, Page 1 is: Survivors’ and Dependents’ Educational Assistance (DEA, Chapter 35)
11. The current:
    a. chapter layout is maintained
    b. `Sponsor's date of death or date listed as MIA or POW` question is maintained
    c. AC 2-10 are not applicable.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/SZIAGWJTXCU#/screens)

**Comment by dmccurdybah** [comment]
vets-json-schema PR - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/597

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/17405
- https://github.com/department-of-veterans-affairs/vets-api/pull/7086

**Comment by dmccurdybah** [comment]
Schema update PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/7089
- https://github.com/department-of-veterans-affairs/vets-website/pull/17439

**Comment by dmccurdybah** [comment]
[https://app.zenhub.com/files/133843125/cf75e44f-e570-4acf-899e-a555ba898bbd/download](https://app.zenhub.com/files/133843125/cf75e44f-e570-4acf-899e-a555ba898bbd/download)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1926&group_by=cases:section_id&group_order=asc in staging.
