### ISSUE TITLE
Discharge Upgrade Wizard - Change the DD 149 PDF link in App

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#25121]
## Issue Description
1. **Change the DD 149 PDF link on https://www.va.gov/discharge-upgrade-instructions/request-dd214 **BACK** to** https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf (i.e., revert what you did on  #23988 -- I'm closing this one, BTW since it's now nullified by this request)
2.  **Change the DD 149 PDF link on https://www.va.gov/discharge-upgrade-instructions/ **BACK** to** https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf (i.e., revert what you did on #21944)

**NOTE:** This details numbers 1 and 2 on the linked EPIC.

## Front end tasks
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] Links work.

**Comment by zacharymorel** [comment]
Blocked until Content gives input for the instructions needed to be added.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @johnhashva This is on staging.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel  - looks great! Thanks!  @johnhashva screen shot for reference:

![image](https://user-images.githubusercontent.com/73354907/119719321-a58e2600-be36-11eb-98a7-58a193ea885d.png)

**Comment by zacharymorel** [comment]
Can we close this one out?

**Comment by MarciMcGuireGCIO** [comment]
Indeed we can!
