### ISSUE TITLE
Insurance Workflow

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25138]
Waiting on RPCs

Insurance APIs are a necessary part of the CH-IP project - we will need to be able to manage insurance through the checkin process similar to how the kiosks currently handles it.

The goal of this research spike is to answer the following questions

1. What are we trying to achieve with insurance within the new checkin system?
2. What do kiosks currently do in regards to insurance?
3. Do we need to link this with FHIR? and if so, what RPCs do we need to support?
4. What payloads, endpoints, error messages do we need?

#### Notes
- [x] define workflow
> If you have insurance on file within vista, we re-verify that insurance every 6 months. If you don’t have any insurance on file then we will request insurance every 90 days. We treat all insurance the same. We do 90% of the verification with hipaa 270271 connection. This creates a simple 90 second process that can verify insurance. If anyone wants to collect new insurance information it needs to be shared in vista not icb.
- [x] identify where in vista data is stored
> It lays on top of vista automated billing. 
- [x] file number 
> SUBSCRIBER ID (#355.33, 90.03)
- [ ] identify RPC Remote procedure call

How might we integrate with existing API systems to validate insurance?

- there is an existing api infrastructure - can we use the Insurance Capture Buffer?
- How does FHIR handle insurance checks? Is there a value we can use?

Andy is trying to get the data from VistA, and seeing if there is a way to translate it to a FHIR spec
actual call for "should insurance be checked" is not in FHIR

**Comment by Kennon-git** [comment]
include insurance in "pre mvp" as insurance - tag on to the endpoint we're already returning.

**Comment by Kennon-git** [comment]
built RPC into small java framework. DDR call is functional. on track.

**Comment by Kennon-git** [comment]
shane to meet with the DSS team. 

Andy has DDR part essentially done, java broker. not written into vista link

**Comment by kjduensing** [comment]
DSS said we can't use their RPC. BJ & scheduling group looking at creating a soln that isn't using that RPC

**Comment by Kennon-git** [comment]
still waiting - will likely be in next sprint for scheduling group.

**Comment by Kennon-git** [comment]
BJ is writing the RPC, hopes to have it in the next few weeks.

**Comment by Kennon-git** [comment]
Ready in next release of VSE
