### ISSUE TITLE
vets-api deployments on docker

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2513]
As a step towards de-coupling the apps from infra and to support further Ruby upgrades, we need to switch the build/deployments to use docker images.  This will allow the dev team to control the ruby and runtime env at their own pace and process.

- [x] using current ruby version, rework the Dockerfile in vets-api to better use layer caching and change the entrypoint so we can start both sidekiq and puma separately from the same image
- [x] do a audit pass on BRD configs to make sure needed items/settings are moved over to image
- [x] change the deploy to build and embed the docker image in the AMI
- [x] do a pass on docs and playbooks to updte for new docker based workflows
- [x] change commands to use docker run (with mounted configs, etc..) and roll out per env
  - dev
    - [x] worker
    - [x] server
  - sandbox
    - [x] worker
    - [x] server
  - staging
    - [x] worker
    - [x] server
  - prod
    - [x] worker
    - [x] server

**Comment by johnpaulashenfelter** [comment]
Had a side conversation w/ @nathanhruby and wanted to followup here. Along with ruby, there are a few tool dependencies (poppler, clamav, pdftk, imagemagick) that are running older versions. It may be necessary to track down those older versions or spin up a side project to update those dependencies to a more modern version.

We ran into one difference between staging/prod and development in https://github.com/department-of-veterans-affairs/vets-api/pull/3311 for example.

**Comment by johnpaulashenfelter** [comment]
Also strikes me that a ruby version manager (eg rvm, rbenv) would separate out the ruby version issue from the underlying platform a bit cleaner. Not pushing it hard, just pointing it out.

**Comment by nathanhruby** [comment]
This is in relation to the epic: department-of-veterans-affairs/vets.gov-team#17869

**Comment by nathanhruby** [comment]
cc: @jholton

**Comment by nathanhruby** [comment]
see also department-of-veterans-affairs/va.gov-team#3032

**Comment by ricetj** [comment]
Added the three new to-dos in the description above.

**Comment by nathanhruby** [comment]
I launched this in dev staging and sandbox today, module a hiccup with ca-certs things work well.

Pre Launch tasks for prod
- [x] check rake tasks
- [x] Docker on dev machines check log access
  - logs need an IAM permissions to be readble
  -  then use `aws logs --region us-gov-west-1 get-log-events --log-group-name dsva-vetsgov-dev/srv/vets-api/src/log/vets-api.log --log-stream-name CONTAINER_ID`
- [ ] Making a cheat sheet for people on the changes

**Comment by jholton** [comment]
In the `aws logs` command, should the `log-group-name` be `dsva-vagov-dev/srv/vets-api/src/log/vets-api-server.log`?

**Comment by nathanhruby** [comment]
yes, but I also checked the IAM perms and there's no read role.  I'll probably write a small alias or script for this to make it easy

**Comment by nathanhruby** [comment]
department-of-veterans-affairs/vets-api#3769

**Comment by johnpaulashenfelter** [comment]
Waiting to merge https://github.com/department-of-veterans-affairs/vets-api/pull/3497 until AMI build is removed
