### ISSUE TITLE
Content Feedback - Staging review - Notice of Disagreement

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#25130]
staging link: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction

content brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/content-brief-NOD.md

## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
**Questions**

1.	Does this work include updates to static pages? And entry points? If so, are those on staging? 

2.	Per the content brief, the new style for subhead form intro page is: Official form name (VA Form ####) 
Should the NOD subhead on the introduction page reflect this? If so, please remove “Equal to” 

3. We direct users to update personal info by calling Veteran Benefits Assistance 800 number. 
We direct users to update phone/email/mailing address by going to profile. 

Are we able to direct  users to profile to update all this information? would be better UX if there weren't two paths a user had to take to update their information. 

----

**Must feedback**

1.	Supplemental Claim should be capped. 

2. Per the content brief,  the 3 subway map headers on intro page should be:
- Check to be sure you can request a Board Appeal 
- Gather your information 
- Start your request

Please update the introduction page on staging to reflect this


3. This paragraph seems to be missing a word. What should this say?

I understand that I’m opting in to the new decision review process any issues I’d like reviewed that are part of a claim VA decided before February 19, 2019.(*Required)

4. Under "Submit additional evidence" option

Please add missing word “a”

You can submit more evidence for **a** Veterans Law Judge to review, but you can’t have a hearing. The evidence submission option will take more than 1 year for the Board to complete.

5. Under "Hearing with a Veterans Law Judge" option, please delete last sentence, as it pertains to the Additional Evidence option

You can request a hearing with a Veterans Law Judge. You can also submit more evidence to be reviewed, either at the hearing or within 90 days after the hearing. Adding evidence is optional. ~The evidence submission option will take more than 1 year for the Board to complete.~

6. Please cap J in judge in this sentence: 
You’ll have the flexibility and convenience of attending your Board hearing with a Veterans Law judge and Veteran representatives from a personal computer or mobile device.

------

**Should feedback**

1. On "Issue for review" screen

We should include an indicator where users can find the box in this sentence: 
*If you’re requesting a Board Appeal on an issue in an older claim, you’ll need to opt in to the new decision review process by checking the box.* 

Suggest tweaking to: 
If you’re requesting a Board Appeal on an issue in an older claim, you’ll need to opt in to the new decision review process by checking the box below.

2. Under "in-person hearing" content
Is Central Office hearing another term for the in-person hearing? I recommend we use consistent language when referring to this hearing. Or rewrite to “These hearings….”

**Comment by Mottie** [comment]
> 1. Does this work include updates to static pages? And entry points? If so, are those on staging?

No, the static pages will be updated by the public websites team

> 2\. Per the content brief, the new style for subhead form intro page is: Official form name (VA Form ####)
>     Should the NOD subhead on the introduction page reflect this? If so, please remove “Equal to”

Will change to:
- title : "Request a Board Appeal"
- subtitle: "VA Form 10182 (Notice of Disagreement)"

**Comment by Mottie** [comment]
A lot of this content has been updated. Kevin & Beth worked on the changes and the design has been updated to reflect the new content. I just merged in the last of these changes, so it will be available in staging soon.
