### ISSUE TITLE
Document form 526 Eligibility

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#25139]
Things we know:
A veteran can be released from active duty but still part of the reserves

The most comprehensive documentation of who is eligible is in the "Compensation Claims Submitted Prior to Discharge" section ofhttps://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf

# Open Questions
* How do we know if someone is/was on active duty as part of the National Guard?

* When, specifically, do we need to provide the separation location to EVSS?

  * Does what EVSS requires in terms of service history and separation location align what is needed to process a claim?

  * Do we only need to provide a separation location if they are currently on active duty?  

  * What if the veteran has a past active duty history and future guard/reserve obligations?  Is the veteran able to submit the form?
  
* Should someone be allowed to submit form 526 if they have Guard/Reserve obligations more than 180 days in the future? 

## Acceptance criteria
- [x] Eligibility info is correct on https://www.va.gov/disability/eligibility/  (we need to make clear that it is now an option to apply for the first time on va.gov)
- [x] Form 526 Eligibility is documented in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez
- [x] Follow-up tickets created for any changes

Related tickets with additional info:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22710
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13721
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10031

**Comment by vhenry07** [comment]
* How do we know if someone is/was on active duty as part of the National Guard?

During application process on VA.gov:  answering “Yes” to initial gating question of “Are you on active duty right now”, selecting one of the “Guard” entities, and saying “Yes” to the “Are you currently activated on federal orders in the Reserves or the National Guard” question with dates.  A claims processor could also go into Veterans Information Solution to ascertain status.  Anyone can go to the SCRA website & check if SM is on “Active Duty Status” (see side two of sample attached):

![image](https://user-images.githubusercontent.com/77287545/128017774-1985f0c4-b82f-40c4-b694-bb86fe2eb50e.png)

* When, specifically, do we need to provide the separation location to EVSS?



  * Does what EVSS requires in terms of service history and separation location align what is needed to process a claim?

The separation location is not required by VBMS, but it is part of claim data in the corporate database. Barry talked to the BDD team and they would like to keep the separation location requirement.

  * Do we only need to provide a separation location if they are currently on active duty?  

No, separation location is only required if EVSS determines the claim qualifies for BDD (title10/anticipatedSeparationDate or furthest activeDutyEndDate is between 90-180 days).  

  * What if the veteran has a past active duty history and future guard/reserve obligations?  Is the veteran able to submit the form?
  
Yes, NG/Reserve can submit a 526 with any future RAD date (activeDutyEndDate or title10/anticipatedSeparationDate) if there is another period of service that ended in the past. If there is no past period of service, the future RAD date must be within 180 days. The obligationTermOfServiceToDate element is required for reservesNationalGuardService but is only appears on the 526 PDF and is not used to determine eligibility.

* Should someone be allowed to submit form 526 if they have Guard/Reserve obligations more than 180 days in the future? 
 No

**Comment by annaswims** [comment]
Ok, so we do know if someone is currently on active duty in the guard/reserves, but we don't know if they were on active duty as part of the guard/reserves in the past.

**Comment by vhenry07** [comment]
Content change complete (#28602)
