### ISSUE TITLE
Access for Patrick Sanders - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by psanders86** [department-of-veterans-affairs/va.gov-team#25148]
## Description

Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product. Access needed for: dev, staging, prod, CI environments and Jenkins.

- Please provide your Contracting Officer's Representative (COR) name.
> Mary O'Toole

- Please provide your name.
> Patrick Sanders

- Please provide your email.
> psanders@governmentcio.com

- Please provide the name of your team, your role on that team, and the name of the company you work for.
> VSA-VAMC-UPGRADE/VAMC-UPGRADE, Role: Digital Content Editor-Writer, Company: GovernmentCIO

- Requesting SSH key authorization?
> Yes

- What is your public SSH key? If you don't have a SSH Key or know how to find it click here for instructions. (Example below)
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFhlWGsU4Re6ZjGfciXIrAMloRv5UJk5dZF1IC1/LUxNtUEzPehe0vbaLcxI00q1UFYBqWbee7QKSEse2QGQleMEIha629H9ALlzmnkHUM8M8IiGNpL3G1yfZ8/BreYaYZzQfajjc1Rgur39Q+8HAh/ndbh/cAFlZ8hLuZnVqBjdwAiOvyD+pHShdL3H04UH5TKxNd3L/ZYDKR/ec0jJTa2hzpfW9bH7ecXcbuxr4J4TZpFcULnsErHrJiQZs1v05JzUzsFmmpDlUNvc1BlU5uriXEy9BKYmNXzgtYFfgCMVFNlI9/N7v0gkCHeQOsj7cz41E/b4HIPeeWiThy2b3N patricksanders@USRMonitors-MBP

- Grant AWS Console access?
> No

- What AWS services do you need access to and why?
> Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product. Access needed for: dev, staging, prod, CI environments and Jenkins.

**Comment by mleclerc00** [comment]
@psanders86 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by psanders86** [comment]
Thank you. I'm still working on getting this configured and establishing a connection. If I can't self-diagnose today I'll post a message on #vsp-platform-support tomorrow.

**Comment by psanders86** [comment]
I have access. Thank you!
