### ISSUE TITLE
Screen Reader Support | Languages | Footer

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25154]
## This PR for the footer update also includes the following:

- initialization of language code to en
- event driven updates (in the redux store) of the language code (es or tl)
- these language codes persist in redux, even when the page refreshes (important for when the user clicks on a link and the entire page reloads)
- this was done with the localStorage API

**Comment by SKasimow** [comment]
@youngfreezyVA do you need me to do anything else with this ticket?

**Comment by youngfreezyVA** [comment]
nope! it's already implemented and documented :)
