### ISSUE TITLE
Jenkins - Redeploy Nginx w/o Full Deployment

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#25152]
## The Problem
We want a way to quickly update the exposed Jenkins API endpoints w/o having to do a full Jenkins redeployment.

## Extra Context
Multiple teams are making use of the [new exposed Jenkins API endpoints for triggering jobs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21750) in an effort to try and offload some of our CI tasks to github actions. Those endpoints are defined in the nginx config deployed on the local jenkins ec2 instance. Every time we want a new endpoint exposed, we're forced to do a full Jenkins redeployment which requires some small downtime and is riskier than most other deployments.

## Work to be Done
- [ ] Create a GHA workflow or jenkins job to update the nginx config on the jenkins instance
  - [x] reload the nginx config as seamlessly as possible (minimize or eliminate any downtime)

**Comment by omgitsbillryan** [comment]
The script is merged ☝️ . The only reason I'm not closing this ticket yet is because the script has not yet been run against our real Jenkins. It's only been tested locally using Vagrant. 

Once the need arrises to use the script and the script works, we can close this ticket.

**Comment by jbritt1** [comment]
Ansible playbook was created. This was tested against live Jenkins deployment and incurred no downtime. It was also observed that the new test path was added correctly to the nginx config:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/53825ea3-c78c-4507-bc73-153d642d8c9c)
