### ISSUE TITLE
[SPIKE]  try using USWDS 2 in Formation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#25150]
Spike to try using USWDS 2 in Formation

We really should do a spike to try using USWDS 2 in Formation, then either write up some tickets for completing the work or a decision document we can point to when this comes up, explaining why we aren't moving forward to v2.

**Comment by cvalarida** [comment]
Additional context: Some folks have tried to do when USWDS v2 first came out (long before the design system team was around), and my understanding is that the effort required to do a full migration far outstripped the benefit we'd gain from migrating. We haven't actually tried this ourselves, but are assuming this conclusion is true.

This ticket is to give it a shot ourselves and either create a migration plan for the migration or a decision document explaining why we're not migrating.

**Comment by lukemarkwordtlibertyits** [comment]
In case this does not work out, USWDS has addressed their v1 vulnerabilities, so there is currently a way for formation users to use USWDS 1 without forcing resolutions.

https://github.com/uswds/uswds/releases/tag/v1.6.14
