### ISSUE TITLE
Add stylelint config in sister repos

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#25155]
## Issue Description

We are adding `stylelint` in `vets-website` to enable CSS linting enforcement (https://github.com/department-of-veterans-affairs/vets-website/pull/17305). It would be nice if we had the same configuration in the `formation` package as well as the `web-components` branch in `component-library`, since it involves CSS.

We should investigate the best way to accomplish this, but it may involve [using `extends`](https://stylelint.io/user-guide/configure#extends), which would mean that we have a dedicated repo for our `stylelint` config that gets published to `npm`

## Acceptance Criteria
- [ ] `formation` follows the same style linting rules as `vets-website`
- [ ] `web-components` branch follows the same style linting rules as `vets-website`

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by caw310** [comment]
Closing as this is no longer needed.
