### ISSUE TITLE
[COGNITION]: Links must be announced to screen readers as links. Currently being announced as "messages" or just text

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#25160]
# [508-defect-1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I need links to be announced as links, not "message" or read out as plain text.

## Details

JAWS and VoiceOver are reading out links in the VA chatbot responses as "LINK TEXT, message" or just reading out the link text and never saying "link". I was able to trace this to the four layers of `aria-roledescription` attributes that have been applied to various chatbot containers.

## Acceptance Criteria

- [ ] Links announce themselves as "LINK TEXT, link" correctly in all major screen readers

## Environment

* https://staging.va.gov/virtual-agent/

## Proposed Solution (if known)
The two options I was able to spot check briefly were:

1. Remove all of the `aria-roledescription` attributes
2. Add an `aria-roledescription="link"` attribute to the link markup (not preferred)

## WCAG or Vendor Guidance (optional)

* https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html

## Screenshots or Trace Logs

![Screen Shot 2021-05-24 at 1 56 47 PM](https://user-images.githubusercontent.com/934879/119394602-fae00100-bc97-11eb-98c2-6b85738e645d.png)

**Comment by anitadewitt-va** [comment]
We do not have control over the aria-rolesecriptions that are applied to the parent elements of each link. This would need to be addressed by the Microsoft webchat team.

**Comment by 1Copenut** [comment]
@anitadewitt-va This would be worth escalating with the MSFT chatbot team, probably as an issue ticket that you can point back to this one if that's appropriate.

**Comment by ianpsant** [comment]
Filed Microsoft ticket mentioned above.

**Comment by noahgelman** [comment]
WCAG Standard: [Success Criterion 2.4.4 Link Purpose (In Context)](https://www.w3.org/TR/WCAG21/#link-purpose-in-context)

**Comment by shiragoodman** [comment]
hey @ianpsant - it's been a while. Any update from Microsoft on this or other issues?

**Comment by ianpsant** [comment]
Microsoft addressed this issue with their PR (https://github.com/microsoft/BotFramework-WebChat/pull/4108) which added an announcement "Click to interact" with links. Also this problem may be a per browser issue on how they interact with Aria links. We implemented this on our chatbot on ticket https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/390. We will revisit this more when we move the chatbot and this goes through another accessibility review.
