### ISSUE TITLE
[KEYBOARD]: The chatbot text input must have a yellow focus halo when it receives keyboard focus

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#25161]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a user who prefers to navigate by keyboard, I need the chatbot's input to have a yellow focus halo like other form inputs so I know it has keyboard focus.

## Details

The input field must have our standard focus halo so users can easily identify when it has focus and they can type their question. Screenshot attached below.

## Acceptance Criteria

- [ ] Yellow focus halo appears on all four sides of the input when it has keyboard focus

## Environment

* https://staging.va.gov/virtual-agent/

## WCAG or Vendor Guidance (optional)

* https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html

## Screenshots or Trace Logs

![Screen Shot 2021-05-24 at 1 58 21 PM](https://user-images.githubusercontent.com/934879/119395110-ae48f580-bc98-11eb-9d39-6ba7b852cc65.png)

**Comment by ianpsant** [comment]
When we move the chatbot, we can ask during that accessibility review during Staging Review if this is something that's still necessary. Currently we are not aware of any other chatbot that has such a feature.
