### ISSUE TITLE
[Design] [New] - Update content to reflect 10MB file size

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#25165]
## User Story

Update Sign as a Representative content to reflect new size restriction (10 MB)

## Acceptance Criteria

- [x] Source of truth content doc is updated
- [x] New content passed to frontend (#25166)

**Comment by Dene-human** [comment]
[Content](https://github.com/department-of-veterans-affairs/va.gov-team/commit/cf1b82abd9ade1b0410ede73c42c01f14b56bf4d#diff-ddab1e738296858365edfc42922bf8d3a63c054469b496bc3b33fb98dfaff7cc) has been updated on the Upload your legal document page. 25mb to 10mb.

**Comment by dat-gcio** [comment]
@Dene-human This is in staging/prod if you wanted to test.
