### ISSUE TITLE
Create ROE for VFS teams engaging with VSP design

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2516]
As a VFS team, I want to know the correct way to engage with the VSP design team so that I can correctly solicit their help. 

AC: 
- [x] Write ROE
- [ ] Publish ROE
- [ ] Distribute ROE

**Comment by CrystabelReiter** [comment]
Closing this ticket. We're meeting up with Gretchen, on editing our readmes.
