### ISSUE TITLE
Facility Locator: Geolocation triggered by enter key

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25169]
## What happened?
Facility Locator is trying to locate me even when I’m not asking for it. (Reported by Leyda)

## Steps to Reproduce
1. Disable location services
2. Enter zip code
3. Select VA health (or other facility type)
4. Press "enter" on keyboard (rather than clicking on "search")
5. Observe error message modal appears 

![image](https://user-images.githubusercontent.com/55411834/119397751-d124db00-bc93-11eb-81d0-d1295105ead8.png)

## Desired behavior
Facility Locator should not attempt to locate the user unless "use my location" has been selected.
Modal should not appear unless "use my location" has been enabled for the user **and** an error has occurred.

**Comment by mpelzsherman** [comment]
Validated on Staging

**Comment by mmiddaugh** [comment]
@lildziner @mpelzsherman the modal no longer appears but is the expectation that pressing "enter" will initiate a search if all required fields are populated?

**Steps to reproduce**
Enter zip code
Select "VA health" as facility type
Hit "enter"

Because service type defaults to "all", no action is required for that field - but hitting "enter" does not fire a search. Should it?

**Comment by mpelzsherman** [comment]
Closing
