### ISSUE TITLE
[SCREENREADER]: New messages must be announced consistently across assistive technology software

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#25168]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I need to know when new content is posted to the chat log. This includes my questions, and the bot's responses.

## Details

Two screen reader combinations I tested weren't announcing new content completely:

* IE11 + JAWS didn't announce my question or the chatbot's responses
* Firefox + NVDA didn't announce my questions, but did announce the chatbot's responses

Live regions need to announce information properly. This is a key part of the experience for screen reader users; they won't know new content is available unless their AT starts reading back the new content. Focus remains on the input field, and may be problematic when the bot is offering links to action for veterans. Maybe consider a focus management state that sets focus on the user's question, then moves focus to the bot's answer when it arrives. Or if a focus management solution is not possible, see if the live regions can be announced consistently.

## Acceptance Criteria

- [ ] New content is announced to all screen readers, consistently

## Environment

* https://staging.va.gov/virtual-agent/

## WCAG or Vendor Guidance (optional)

* https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html

**Comment by ianpsant** [comment]
Requires Microsoft change. Would require assistance in filing Microsoft ticket.

**Comment by ianpsant** [comment]
Filed Microsoft bug mentioned above.

**Comment by noahgelman** [comment]
WCAG Standard: [Success Criterion 4.1.3 Status Messages](https://www.w3.org/TR/WCAG21/#change-on-request)

**Comment by ianpsant** [comment]
We've confirmed that Microsoft has fixed this in their ticket (https://github.com/microsoft/BotFramework-WebChat/issues/3936) on PR https://github.com/microsoft/BotFramework-WebChat/pull/4108 and it is documented here https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#ux-narration-of-messages
