### ISSUE TITLE
[Frontend] [New] - Update frontend for new 10MB file size

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#25166]
## User Story

Restrict POA uploads to 10MB to encourage users to only upload relevant documentation.

## Acceptance Criteria

- [x] Update frontend to accept 10MB files or smaller
- [x] Content updates (#25165)

**Comment by Dene-human** [comment]
Just fyi, [source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/commit/cf1b82abd9ade1b0410ede73c42c01f14b56bf4d#diff-ddab1e738296858365edfc42922bf8d3a63c054469b496bc3b33fb98dfaff7cc) has been updated
