### ISSUE TITLE
IA Feedback - Staging Review [Virtual Agent - Chatbot]

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#25178]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Change in approach from when we saw it for Midpoint review...notes from staging review meeting:
  - chatbot lives on a standalone page; page will only live on staging and will not be published to production; all user testing will happen on staging. 
  - Users will receive invite to tool on staging to review and test
  - Users will be directed to an Optimal workshop survey to provide feedback after they have tested tool

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- URL needs to be vetted and approved by OCTO IA, even if on staging only.   Meeting with OCTO on 5/25 in PM and will report back if a URL change is needed.

**Per 5/25/21 discussion:**
- **Change URL to staging.va.gov/virtual-agent-study/ - this more accurately follows our standard for ensuring that the URL provides clear context around the purpose of the page, and also clearly signifies that it is for research only.** 
  - An IA request will be required before the chatbot can go to production to review placement within the IA, entry points, and URL.  This URL is intended to be temporary and used for staging only. - 
- **Ensure "noindex" meta tag is implemented on page  - looks like this is already in place, but just in case!**

**Should:**
- Remove breadcrumb from page to reinforce that this page does not have a permanent home within the site, and to reduce wandering off page within the staging environment.
- Update H1 to focus on primary term "virtual agent" as used in your URL  - as a standard, keywords should be consistent across primary elements of the page (i.e. H1, URLs, etc)

**Consider:**

**Comment by mnorthuis** [comment]
@LucianaAlexanderMorais The description above is updated based on a conversation between myself and @mpeterz today in regards to URL standards, as well as other IA standards.  It does require a change to your existing URL.  

These requirements and recommendations are based on:
- Enforcing URL standards 
- Minimizing risk if the page is mistakenly deployed to production
- Minimizing navigational options for users to wander off into staging.va.gov site

Please let me know if there are any questions, thank you!

**Comment by LucianaAlexanderMorais** [comment]
Alright, thank you. We will handle the change to the URL.

**Comment by ianpsant** [comment]
Hi @mnorthuis, once the change is complete, for the required IA request you mention, is that something I can work with you to set up? Is there a ticket I need to file somewhere? Given our intention to hopefully start our study next week, I want to make sure we're following the process properly so there isn't any undue delay. Thanks!

**Comment by mnorthuis** [comment]
No IA request needed for this now, will be needed once research is complete and you are looking for where to place the chatbot on the site permanently.

**Comment by ianpsant** [comment]
We have made all requested changes on this ticket, 1. Changed the URL to staging.va.gov/virtual-agent-study/ (no-indexed and removed the old page) 2. Removed the breadcrumbs 3. Updated the H1 text.
