### ISSUE TITLE
508-defect-3 [SCREENREADER]: add more link renders above list of issues

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#25177]
Label: 24069

    - [508-defect-3]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3
Issue Title: 508 defect 3, screenreaders, add more link renders above list of issues
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
As a screen reader user, I navigate web pages in linear fashion. If an action requires consideration of material on a page, I expect the link to perform that action to render below the material being considered.
<h2>Details</h2>
At the end of step 2, the user is presented with a list of the issues they are appealing and a link to go back and add more if necessary. The link to add more renders above the list, causing the user to have to navigate up to find it. 
<h2>Acceptance Criteria</h2>
The "add more" link renders below the list of issues at the end of step 2.

<h2>Steps to Recreate</h2> 
<ul>
<li>Access

https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction

And sign in with vetsgov+test238@id.me</li>
<li>Proceed to step two and add at least one disability</li>
<li>Proceed to the review page at the end of step 2</li>
</ul>

**Comment by Mottie** [comment]
@AngelaFowler82 The "go back and add it" link is now below the list of selected issues. Please verify and close this ticket when you have time. Thanks!

**Comment by joshkimux** [comment]
<img width="682" alt="Screenshot 2023-06-05 at 10 03 33 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/b34e12ab-78b0-4e87-859c-c3fc8195af94">
Confirming add is below!
