### ISSUE TITLE
Make an on-boarding flow/ issue to make it easier for new people coming on. 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2517]
This came up in a retro meeting. 
Make onboarding issue template, ie list of things to go throw, ie flow of what to order to look into things.

idea: make a checklist for them to go through
idea: also ask for ideas from new people ie tell them to make notes where improvements can be made.

**Comment by wyattwalter** [comment]
I think this is largely covered here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/onboarding.md#oncall
