### ISSUE TITLE
Delete SM files from device when navigating away from page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25189]
## Acceptance Criteria
1. When viewing an SM attachment in the file viewer, automatically delete the file from the device upon navigating away from the page

**Comment by digitalken** [comment]
@keli13, is there going to be a way to test this on the device?  If not, please let me know. Otherwise, please explain.  Thanks!

**Comment by keli13** [comment]
@digitalken nothing really comes to mind since you dont have visibility to the filesystem used by the app. I can move this done once it gets merged if its make sense. 

@bessgreen thoughts?

**Comment by digitalken** [comment]
@keli13 that's kind of what I was thinking.  Seems like a non-testable dev task.  Works for me if it works for @bessgreen .
