### ISSUE TITLE
Document GitHub Actions usage and workflow for frontend development

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#25188]
## Description
There will be some differences in migrating from Jenkins to GitHub Actions. As such, documentation will have to be written or updated to reflect the changes to continue supporting the teams that have previously worked with Jenkins as the CI tool for frontend development.

## Acceptance criteria
- [ ] Documentation should be written for the new workflow with GitHub Actions.
- [ ] Outdated documentation about Jenkins should be removed or updated accordingly.

**Comment by U-DON** [comment]
We observed for PRs that the "Checks" tab can have multiple runs of a workflow (e.g., "Continuous Integration") if a branch based off of that PR's branch is created and pushed without any new commits. It seems to be caused by sharing the same commit hash when the push event is triggered for the workflow. Navigating to the summary of the run should indicate which branch triggered the run. It's worth documenting this edge case to reduce confusion.

**Comment by U-DON** [comment]
In progress docs: #26898

**Comment by meganhkelley** [comment]
@ndsprinkle since you're working on GHA docs I will ask your opinion — can this one be closed? This is for creating VFS user guides for GHA

**Comment by ndsprinkle** [comment]
@meganhkelley I was actually looking at this earlier and had some confusions, but I'm pretty sure it's safe to close. The confusing part is that in the PR that Eugene linked, there is [this](https://github.com/department-of-veterans-affairs/va.gov-team/blob/428dcc790cd71fc29a92f17d767f4ab458256ba9/platform/engineering/frontend/github-actions/github-actions-usage.md) created document. But even though that's in an open PR, it lives [here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1745911823/GitHub+Actions+usage+for+VA.gov+frontend+engineers) in a published developer doc. I'll run through them side by side to see if there are any differences (other than the changes I made to the doc) and then close the ticket. Does the PR still need to be merged to put document in GitHub, or is that not necessary?

**Comment by meganhkelley** [comment]
That's on me — Eugene made a PR and then I told him no it needed to go in Platform Website

I'll close this ticket if you can please close the PR! Thanks!
