### ISSUE TITLE
CT Redesign: Location Search - Map Display Solution	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25198]
Desktop prototype updated for Map display solution (on load / no results)	

- Discuss solution for map display with team 
- Consider whether map displays by default Identify solution 
- Update prototype accordingly

**Comment by amyknox** [comment]
CT Redesign: Map display when no results
	• Remove filters when no results
	• Reset map to full US View
	• Update content to start with something like "We didn’t find any institutions based on your search." (Not 'near you'  since they didn't necessarily use the "near you" component. 

CT Redesign: Disambiguation
	• Use MapBox default has a better solution.

**Comment by amyknox** [comment]
_Sidebar content_

We didn’t find any institutions based on your search.

**For better results:**
* Zoom in to view a smaller area of the map, **or**
* Move the map to a different area

Then click the “**Search this area of map**” button.

If we still haven't found any results for you, **enter a different search term** (street, city, state, or postal code)

**Comment by amyknox** [comment]
@watersemma Is [this the prototype page](https://bahdigital.invisionapp.com/d/main#/console/14222691/296060311/preview) that will have the updated no results content (above)? 

Or is it elsewhere, already complete & I'm looking in the wrong spot for it?
