### ISSUE TITLE
CT Redesign: Profile Page -  Prototype - Component Breakdown

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25193]
Profile page elements are identified as new, refine, reuse	

* Build on existing Profile Page IA 
* Identify status & type of components in each section 
* Tag as MVP, MVP-wannabe, Enhancement 
* UX team review & refine 
* Share with Xfunc team for input

**Comment by amyknox** [comment]
@JenLJ  - assigning you to this for now per your comments at stand-up.  We can expand assignees as needed.

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1607448875956/e7224924508e393f116b5faeab73952e08bf8c7b
