### ISSUE TITLE
COVID-19 mask guidance updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#25191]
## User story

As a Veteran, caregiver, or family member, I need to know the latest VA policy on masks.

### FAQs page

- [x] Add new question re: masks (https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#whats-v-as-current-policy-on-42457)

- [x] Update health care questions (https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#do-i-need-to-wear-a-mask-in-a-36879)

### Chatbot

- [ ] Section "COVID-19 prevention" > "Should I wear a mask?" : Update this Q&A to match this one: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#whats-v-as-current-policy-on-42457

- [ ] Section "COVID-19 prevention" > "What steps can I take to protect myself and others from COVID-19?": Update the answer to:

Here is advice from CDC:

- Wear a mask that covers your nose and mouth to help protect yourself and others.
- Stay 6 feet apart from others who don’t live with you.
- Get a COVID-19 vaccine when it's available to you.
- Avoid crowds and poorly ventilated indoor spaces.
- Wash your hands often with soap and water. Use hand sanitizer if soap and water aren’t available.

[Get more prevention advice on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention.html)

- [ ] Section "COVID-19 prevention" > "If I need to leave my house, how do I stay safe?": Delete this question

- [ ] Section "Health care, appointments, and prescriptions" > "Do I need to wear a mask when I go to a VA hospital or other location?": Update this Q&A to match this one: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#do-i-need-to-wear-a-mask-in-a-36879 

- [ ] Section "Health care, appointments, and prescriptions" > "Should I get a flu shot this year?": Delete this question

### Translation

- [ ] Send to translators
- [ ] Get translation back
- [ ] Update Spanish and Tagalog pages

**Comment by DanielleThierryUSDSVA** [comment]
Hi again, @lunascoop. Here are some updates we need to make to the chatbot. We're going to be making another update to the FAQs tomorrow, so I'll have another update to add here then. Thank you!

**Comment by RLHecht** [comment]
Old ticket. Closing!
