### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update - SCO Email EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25205]
STEM protototype / SCO Email has been reviewed by EDU	

* Prototype is reviewed w EDU 
* Updates to prototype / content doc are incorporated, if small; new tickets are created if necessary

**Comment by JenLJ** [comment]
Provided SCO email for EDU review on 5/24

**Comment by amyknox** [comment]
6/1 - Waiting on input from EDU

**Comment by JenLJ** [comment]
Email was updated to include "training institution" in first sentence
