### ISSUE TITLE
Ansible walk through 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2520]
To give a few hours walkthrough for people not familiar with it.

**Comment by nathanhruby** [comment]
https://github.com/nathanhruby/minitwit/blob/master/Docker-Ansible-Workshop.md

**Comment by nathanhruby** [comment]
https://zoom.us/recording/play/3WnLJAv9lRi28AHWSR3CvcTOkVNEjkx6JZIAKhXwhBJtDyVLfHaeimQI4IG1v9jH?continueMode=true
