### ISSUE TITLE
CT Sec 1005 - In-State Tuition: Content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25204]
Content for Sec 1005 indicator is drafted & shared with UX

* Content for indicator is drafted 
* Content for indicator is reviewed w UX team

**Comment by amyknox** [comment]
### **Question:** 
Do you qualify for in-state tuition? (Learn more)

### **Responses:**
Yes (default selection)
No


### **Learn more content**  (If all schools have a link for Sec 1005)

**Qualifying for in-state tuition**

If you're using GI Bill education benefits, you probably qualify for in-state tuition.   

Visit this school's website to [see any in-state tuition requirements]().



### **Learn more content**   (when only schools not allowing all in-state have links)

**Qualifying for in-state tuition**

If you're using GI Bill education benefits, you probably qualify for in-state tuition.   

Visit this school's website to [see their requirements for in-state tuition]().

**Comment by amyknox** [comment]
@JenLJ @watersemma 

Content for the "In-state tuition" update is included above. 2 options for the learn more depending on whether all schools have to provide a link (likely) or if it's just schools who have special requirements.  We're confirming that today.  

Pls review and drop comments, questions here or in slack.  

Thanks!

**Comment by amyknox** [comment]
Update based on 6/3 EDU discussion on Sec 1005 re: data transfer.


### Learn more content when public IHL has a link for Sec 1005

**Qualifying for in-state tuition**

If you're using GI Bill education benefits, you probably qualify for in-state tuition.

Visit this school's website to [see any in-state tuition requirements]().


### Learn more content when public IHL has "contact a SCO" for Sec 1005

**Qualifying for in-state tuition**

If you're using GI Bill education benefits, you probably qualify for in-state tuition.

Contact the School Certifying Official (SCO) to learn more about this school's in-state tuition requirements.
