### ISSUE TITLE
EDU Forms /5490 Update: IR-1002 Prototype - EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25207]
5490 protototype has been reviewed by EDU	

* Prototype is reviewed w EDU 
* Updates to prototype / content doc are incorporated, if small; new tickets are created if necessary

**Comment by JenLJ** [comment]
Provided June updates for 5490 to EDU on 5/24

**Comment by JenLJ** [comment]
Slight change to new question due to technical limitations
