### ISSUE TITLE
CT Sec 1005 - In-State Tuition: Discovery

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25203]
Requirements for Sec 1005 are understood and documented; a solution has been identified	

* Explore indicator requirements with internal team 
* Document indicator requirements 
* Follow-up with questions to EDU

**Comment by amyknox** [comment]
UPDATE QUESTION in Comparison Tool: 
Do you qualify for in-state tuition? 
- Incorporate language below and link to school in Learn more. 

Section 1005. Requirements for in-State tuition Removes the requirement for covered individuals to enroll in a course at a public institution of higher learning within three years of being discharged to receive in-state tuition. Also, VA will make publicly available on the VA website a database explaining any public institution’s requirements for beneficiaries to be charged in-state tuition. Effective: August 1, 2021.
