### ISSUE TITLE
[FE] Clean up Defect-3s and Shoulds

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#25208]
From the Staging Review in May 2020, here are the defect-3's and shoulds we haven't fixed et, but don't want to lose

- more conversions to action link https://github.com/department-of-veterans-affairs/va.gov-team/issues/24643

defect-3
>source: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24644
- Review page responses are right aligned, but should be left aligned. The jagged left edge makes it difficult for individuals with cognitive or reading disabilities to parse content.
- The results page has two links that are styled as buttons. They should be styled as links.
- "For example" text within the "Are there any other concerns..." is a part of the label itself instead of being separate hint text below the label. Including the "For example" bit as a part of the label and not as hint text (which uses aria-describedby) creates an overly verbose label for screen reader users.

from content (#24494)
1. The “user can’t proceed” error message in the content artifact:
I recommend removing “If you’re having trouble” from this message, as it sounds like the user can’t proceed at all from this point.

Here’s a recommended tweak:
We can’t submit your questionnaire right now
We’re sorry. Something went wrong when we tried to submit your questionnaire. The information you’ve entered so far has been saved. Please try again later.

2. On Questionnaire Step 2 screen
Should “Routine or follow-up visit” header be styled as H3? It carries same weight as "What's the reason for your visit?" head.

**Comment by julieadair1** [comment]
This can be closed per @mdewey.
