### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update - Wizard  EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25206]
STEM protototype / SCO Email has been reviewed by EDU	

* Prototype is reviewed w EDU 
* Updates to prototype / content doc are incorporated, if small; new tickets are created if necessary

**Comment by JenLJ** [comment]
Provided wizard for EDU review on 5/24

**Comment by amyknox** [comment]
6/1 - Waiting on confirmation on content from EDU

**Comment by JenLJ** [comment]
We discussed making updates to the language on "extending Post 9/11 benefits", but will not be making any additional changes at this time.
