### ISSUE TITLE
Orientation for Digital GI Bill team (Accenture Federal Services)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25210]
## Orientation User Story
DGIB team is going through orientation to work on the VSP, they need support to get up and running. This epic contains the tasks our team will perform to support them through their orientation stage.

## Goal
Get DGIB team up and running in their workflow as quickly as possible._ 

## Issues to create within this Epic

```
Create a place to store all relevant documents for the team we are supporting
Give access to GitHub repo vets.gov-write
Complete orientation meetings 
Schedule times to meet with team
```
### Team Members and Github Status:

Name | Github Status | Role | GitHub ID | Email
------------------- | ------------- |------------ | ------------- | -------------
Phil Crowder | Added | Application Architect | pcrowder101 | phillip.crowder@accenturefederal.com
Won Choi | Not in VA organization | Devops Lead | wonhchoi | Won.Choi@asmr.com
Cesar Santiago | Added | Technical Lead | cesaresantiago | cesar.santiago@accenturefederal.com
Ewaz Farhang |Added|Tester|ewaz-farhang | ewaz.farhang@accenturefederal.com
Liam  McCormick|Added |Tester |lmccormickafs | liam.mccormick@accenturefederal.com
Fernando Boza |Added |Full Stack Developer |fernandoboza | fernando.boza@accenturefederal.com
Khansa Hamammi |Added  |Full Stack Developer|khansahammami | khansa.ayari.hammami@accenturefederal.com
Audra Ayotte  |Added |Human Centered Design |audayotte |audra.ayotte@accenturefederal.com
Russell Lyons| Added| Human Centered Design Lead | rlyons89 | russell.lyons@accenturefederal.com
Leelah Holmes | Added | Human Centered Design | LeelahHolmes | 
Isabel Herrick | Added | Human Centered Design |IsabelHerrick | 
Miya Furukawa | Added  | Human Centered Design| mfurukawa99 | 
Gilbert Engle | Added | Backend Developer | gilbert-engle | gilbert.engle@accenturefederal.com
Shamik Desai | | Product Manager | | shamik.n.desai@accenturefederal.com
Rishikesh Kollipara| Added| Integration Architect | Rishikv |rishikesh.kollipara@accenturefederal.com 
Jackie Nguyen |Added| Enterprise Architect |jacquelynnguyen | jacquelyn.nguyen@accenturefederal.com
Alexander Ferzola | Added | UI Designer | alexander-ferzola | alexander.ferzola@accenturefederal.com
 

## How to configure this issue
- [ ] **Labeled with `vsp-product-support` Team**
- [ ] **Orientation is complete and new VFS team is operating in their development workflow**

**Comment by shiragoodman** [comment]
general Platform Orientation completed June 2. Team is currently blocked awaiting Slack access before Design, BE and FE orientation can occur.

CC @naomimarcussen @jeff2d2 @meganhkelley

**Comment by naomimarcussen** [comment]
Need to add 1 more designer to the list above
Alexander Ferzola alexander.ferzola@accenturefederal.com
CC @shiragoodman

**Comment by naomimarcussen** [comment]
@shiragoodman  Here's all the designers and their emails for reference:

Audra Ayotte: audra.ayotte@accenturefederal.com
Russell Lyons: russell.lyons@accenturefederal.com
Leelah Holmes: leelah.holmes@accenturefederal.com
Isabel Herrick: isabel.herrick@accenturefederal.com 
Miya Furukawa: miya.s.furukawa@accenturefederal.com 
Alexander Ferzola: alexander.ferzola@accenturefederal.com
