### ISSUE TITLE
Create Memory Usage Report for vet-website Application Build

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#25215]
## Problem Statement

The application build can use a lot of memory, especially when creating the production version. In CI, this prod version can take upwards of 8-11mins to complete, we would like to get that running faster and reduce the memory usage. To get the most telling results, this should be run with a production build so we can see all the optimizations being run.

## Goal

Measure memory footprint used to create builds of the website and identify points for improvement or bottlenecks in the process.

## Definition of Done

- [x] Produce memory report containing each application within vets-website
- [x] Identify areas of increased memory usage 
- [x] Identify potential remedies to manage and reduce memory usage during the build
- [x] Tickets have been created for potential solutions

## Resources

- [Guide: How To Inspect Memory Usage in Node.js](https://www.valentinog.com/blog/node-usage/)
- [heapdump](https://www.npmjs.com/package/heapdump)

**Comment by jhonnyoddball** [comment]
Comparing [heapdump](https://github.com/bnoordhuis/node-heapdump) vs [v8_getheapsnapshot](https://nodejs.org/dist/latest-v15.x/docs/api/v8.html#v8_v8_getheapsnapshot) (native)

Running the same function:

```
let arr = Array(1e7).fill("some string");
```

heapdump took 39.961s
v8_getheapsnapshot took 13.258s

![Screen Shot 2021-06-01 at 2 13 36 PM](https://user-images.githubusercontent.com/55560129/120371355-ab2ab680-c2e3-11eb-96d2-ff8fc8889ad9.png)

**Comment by jhonnyoddball** [comment]
## Possible solutions:

1. Use [v8_getheapsnapshot](https://nodejs.org/dist/latest-v15.x/docs/api/v8.html#v8_v8_getheapsnapshot) instead of [heapdump](https://github.com/bnoordhuis/node-heapdump). This will help auditing memory leaks in the apps.
2. Use `process.memoryUsage()` to identify and mark heap and rss info
3. Use a webpack profiler
4. Try a new tool like [clinicjs](https://clinicjs.org/)

**Comment by jhonnyoddball** [comment]
## Use of v8_getheapsnapshot

Insert the below code to be able to take snapshots

```
const fs = require('fs');
const v8 = require('v8');

function createHeapSnapshot() {
  const snapshotStream = v8.getHeapSnapshot();
  // It's important that the filename end with `.heapsnapshot`,
  // otherwise Chrome DevTools won't open it.
  const fileName = `${Date.now()}.heapsnapshot`;
  console.log(fileName);
  const fileStream = fs.createWriteStream(fileName);
  console.log(fileStream.path);
  snapshotStream.pipe(fileStream);
}

createHeapSnapshot();
```

Open the `.heapsnapshot` file using Chrome Dev Tools

![Screen Shot 2021-06-03 at 9 57 11 AM](https://user-images.githubusercontent.com/55560129/120659796-b3eeca00-c454-11eb-83d3-ee183a459613.png)

**Comment by jhonnyoddball** [comment]
## Use of  process.memoryUsage()

Returns an object describing the memory usage of the `Node.js` process measured in bytes.

**It can be run at different stages during the process**

Using:

```
function getProcess(){
  const memory = process.memoryUsage();
  for (let key in memory) {
    console.log(`${key} ${Math.round(memory[key] / 1024 / 1024 * 100) / 100} MB`);
  }
}
```

Results:
```
rss 176.92 MB
heapTotal 5.06 MB
heapUsed 3.33 MB
external 429.42 MB
arrayBuffers 428.46 MB
```

- **rss**, Resident Set Size, is the amount of space occupied in the main memory device (that is a subset of the total allocated memory) for the process, including all C++ and JavaScript objects and code.
- **heapTotal** and **heapUsed** refer to V8's memory usage.
- **external** refers to the memory usage of C++ objects bound to JavaScript objects managed by V8.
- **arrayBuffers** refers to memory allocated for ArrayBuffers and SharedArrayBuffers, including all Node.js Buffers. This is also included in the external value. When Node.js is used as an embedded library, this value may be 0 because allocations for ArrayBuffers may not be tracked in that case.

**Comment by jhonnyoddball** [comment]
Started testing [Speed Measure Plugin](https://www.npmjs.com/package/speed-measure-webpack-plugin)

![Screen Shot 2021-06-07 at 10 56 51 AM](https://user-images.githubusercontent.com/55560129/121042337-92a61a80-c781-11eb-9059-f88af35d3d68.png)

**Comment by jhonnyoddball** [comment]
More detailed testing using [Speed Measure Plugin](https://www.npmjs.com/package/speed-measure-webpack-plugin)

![Screen Shot 2021-06-07 at 2 49 58 PM](https://user-images.githubusercontent.com/55560129/121200953-217a6c00-c842-11eb-81d0-1d87f52b8c27.png)

**Comment by jhonnyoddball** [comment]
## Clinic.js

After some testing we have decided that this application will not work with our current implementation since it is mainly used for profiling on a server

**Comment by jhonnyoddball** [comment]
## Use of  webpack-bundle-analyzer

I run a comparison between a previous analysis done back in 2019 and one done this week. The purpose of comparing them is to analyze better how it has changed and how much it has grown after 2 years.

### End of 2019

`node_modules` bundle size: 2.69MB (uncompressed)
Deployed compressed bundle size: 233KB

`node_modules` bundle percentage: 90%
`src` bundle percentage: 10%

![Screen Shot 2021-06-14 at 3 18 12 PM](https://user-images.githubusercontent.com/55560129/122090588-e9d96a00-cdd5-11eb-8459-47c890e0e2b5.png)

### Middle of 2021

`node_modules` bundle size: 1.90MB (uncompressed)
Deployed compressed bundle size: 313KB

`node_modules` bundle percentage: 65%
`src` bundle percentage: 35%

![Screen Shot 2021-06-14 at 1 42 19 PM](https://user-images.githubusercontent.com/55560129/122091182-88fe6180-cdd6-11eb-8adf-6116b37f11f8.png)

![Screen Shot 2021-06-14 at 3 13 23 PM](https://user-images.githubusercontent.com/55560129/122091206-91569c80-cdd6-11eb-9e64-a549afe81735.png)

## Analysis

- After following my recommendation of removing/fixing `lodash.js` we are still at a 30% reduction from initial analysis in the `node_modules` bundle size.
- `node_modules` bundle percentage has decrease from 90% to 65%. However, the entire bundle size has increase, which means that the `src` bundle has increase a lot.
- Top 3 dependencies worth checking for improvements: 
   - `date-fns` (512KB / 1900KB)
   - `vets-jason-schema` (230KB / 1900KB)
   - `markdown-it` (204KB / 1900KB)

**Comment by jhonnyoddball** [comment]
## Recommendations

There are a lot of room for improvement, however, things that we should focus on first are"
- `css` 
- `modules with no loaders`
- `babel-loader`

Other mentions:
- Worth mentioning that `Webpack 5` should be significantly faster but it requires a fresh setup with the most recent loader in order to work correctly. More info about this can be found [here](https://github.com/webpack/webpack/issues/12102)
- Consider installing `babel-plugin-date-fns` to improve `date-fns` performance

**Comment by timwright12** [comment]
**Largest Entry Points via webpack-bundle-analyzer**

1. gi-sandbox.entry.js (1.79 MB)
2. facilities.entry.js (1.64 MB)
3. 526EZ-all-claims.entry.js (1.54 MB)
4. questionnaire.entry.js (1.31 MB)
5. hca.entry.js (1.29 MB)
6. request-debt-help-form-5655.entry.js (1.29 MB)
7. 0996-higher-level-review.entry.js (1.28 MB)
8. 0994-edu-benefits.entry.js (1.23 MB)
9. 686C-674.entry.js (1.23 MB)
10. 1990-edu-benefits.entry.js (1.19 MB)
11. 5490-edu-benefits.entry.js (1.19 MB)
12. pensions.entry.js (1.19 MB)

**Comment by timwright12** [comment]
**Sourcemaps**

Discovered that the [source map generation ](https://v4.webpack.js.org/plugins/source-map-dev-tool-plugin/)for a production build is a significant bottleneck. There was a caching option [added in Webpack 5](https://github.com/webpack/webpack/issues/4558) (doesn't help us). This is reflected in the `additional chunk assets processing` step pausing at 90% build for around 5 mins. At 91% you can see it stepping through each entrypoint generating sourcemaps.

We're currently using `SourceMapDevToolPlugin` for this, which is a feature built into webpack. Let's either replace this with a normal `devtool` option or find another way to generate sourcemaps that isn't so resource intensive.

If we find that removing SourceMapDevToolPlugin we can also specificly exclude certain files from generating a sourcemap: `exclude: ['vendor.entry.js'],`

**Comment by timwright12** [comment]
**momentJS**

There are 294 instances of `import moment from 'moment';` in vets-website. moment is a large, deprecated library. Parts of vets-website have migrated to `date-fn` and a more modular import model, we should promote this more in the system.

**Comment by timwright12** [comment]
Report document will be at: https://docs.google.com/document/d/1PYjohfc9TLYKjCMJK2Y1xwXJ5Xed4v00GQ5B0ZTL4QU/edit?usp=sharing

**Comment by timwright12** [comment]
@jhonnyoddball This is what I came up with for recommendations, let me know your thoughts: https://docs.google.com/document/d/1PYjohfc9TLYKjCMJK2Y1xwXJ5Xed4v00GQ5B0ZTL4QU/edit#heading=h.8gqepzcxd1v2

**Comment by timwright12** [comment]
Tickets created:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26622
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26621
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26620

**Comment by timwright12** [comment]
Closing this since we've already moved onto the tickets

@jhonnyoddball @meganhkelley
