### ISSUE TITLE
CT Redesign: Create service to return data for multiple institutions at once

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25219]
As a developer, I need to create a new service that returns a data set for multiple institutions in a single call so that the new compare functionality can be implemented in the comparison tool redesign sandbox.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The [Info] indicates where that information can be found on the current comparison tool profile page.
3. Some of the data points may be calculated values.

## Acceptance Criteria:
1. A service exists that accepts multiple facility codes as inputs and returns the following data set for each facility code:
    a. Accreditation [Institution Summary]
    b. GI Bill students [Header]
    c. Length of program [Header]
    d. Type of school [Header]
    e. Institution locale [Header]
    f. Size of school [Header]
    g. School mission [Used in search results - Not displayed]
    h. Tuition and fees [EYB]
    i. GI Bill pays to school [EYB]
    j. Out of pocket tuition [EYB]
    k. Housing allowance [EYB]
    l. Book stipend [EYB]
    m. Overall rating [Ratings - behind feature flag]
    n. # of veteran ratings [Ratings - behind feature flag]
    o. Overall experience Rating [Ratings - behind feature flag]
    p. Quality of classes Rating [Ratings - behind feature flag]
    q. Online instruction Rating [Ratings - behind feature flag]
    r. Job preparation Rating [Ratings - behind feature flag]
    s. GI bill support Rating [Ratings - behind feature flag]
    t. Veteran community Rating [Ratings - behind feature flag]
    u. True to expectations Rating [Ratings - behind feature flag]
    v. Caution flags [Cautionary information]
    w. Student complaints [Cautionary information]
    x. Length of VET TEC programs [VETTEC profile]
    y. Credit for military training [Additional information]
    z. Single point of contact [Additional information]
    aa. Yellow Ribbon [Veteran Programs]
    ab. Student Veteran Group [Veteran Programs]
    ac. Principle of Excellence [Veteran Programs]
    ad. 8 Keys to Veteran Success [Veteran Programs]
    ae. Military Tuition Assistance (TA) [Veteran Programs]
    af. Priority Enrollment [Veteran Programs]

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main/#/console/14222629/296059730/preview)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/826
https://github.com/department-of-veterans-affairs/vets-website/pull/17429

**Comment by sonntag-adam** [comment]
In staging. Closing story.
