### ISSUE TITLE
Create Google Analytics Dashboard & Update analytics

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#25224]
## Tasks
- [X] Create Google Analytics Dashboard to track typeahead data on a day to day basis
- [X] Update analytics tagging so that only one search results click is tagged after each typeahead search, so we can get a % of typeahead searches that are successful metric

## Related
https://github.com/department-of-veterans-affairs/vets-website/pull/17342

## Link to dashboard
https://analytics.google.com/analytics/web/#/dashboard/Iv7tzMW8QEeoyu_P6PXzXQ/a50123418w177519031p176188361/_u.date00=20210501&_u.date01=20210525/

**Comment by denisecoveyduc** [comment]
@srsuddath has established a GA report that allows us to monitor to total number of searches, the total number of searches that have suggestions, the total number of searches that selected one of the suggestions that was presented and finally how many selected a result after selecting a suggestion.
This funnel enables us to calculate overall conversion rates at each stage and provide us with the data needed to make strategic decisions as we move forward and iterate on the feature.

GA Report Link - https://analytics.google.com/analytics/web/#/dashboard/Iv7tzMW8QEeoyu_P6PXzXQ/a50123418w177519031p176188361/_u.date00=20210501&_u.date01=20210525/
