### ISSUE TITLE
Check-in Content Support

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25221]
# Sitewide Content Intake Form
## What do you need content guidance and support for?
- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
- [ ] Writing/editing to update existing unauthenticated (static) VA.gov page
- [X] Content support for an app or tool
- [ ] Something else (please add details in the next question)

## What do you need help with?
I need help with content for the check-in project. Right now, the help will center around two workflows.

1. Pre-check in (a group of tasks that the Veteran needs to complete prior to their appointment date) 
- [Draft Wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/ZOdgYzp/play)

2. Check-in (the act of letting the VA know that you have arrived for your appointment)
- [Draft Wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/kaVYLYP/play) 
  - There is one change that the wireframes haven't been updated to show. For the near term MVP, the workflow will start from a poster in the waiting rooms. The Veteran will scan a QR code, which will launch the va.gov experience.

@DanielleThierryUSDSVA and I met on May 24 to go through in detail all of the feedback that I need for these two sections. Danielle, I'll let you add in everything from your notes.

## When does this content work need to be done?
We hope to usability test in mid-June, so I would like to have the first round on content suggestions incorporated before then.

Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [X] Yes, health content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No
Note: If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

About your team
Team name: VSA Healthcare Experience Team
OCTO-DE product owner: Patrick Bateman
Product manager: Corey Parker
Designer: Kristen McConnell
FE engineer: Mark Dewey
Product/team Slack channel: check-in-experience
Links to related tickets
Please include here a link to the epic, or other relevant tickets, for this product work.

Next steps
Once you’ve submitted this ticket, please post a link to this issue in the #va-sitewide-content Slack channel and tag @RLHecht.

If you also need engineering support from the Public Websites team, fill out their intake request form.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @peggygannon @shiragoodman. Randi's out this week, so I'm tagging you for awareness. Thanks!

**Comment by kristenmcconnell** [comment]
We might need a contact/insurance information question in the UI for MVP. See the updated [wireframe prototype](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/kaVYLYP/play).

With the addition of that question with also need to account for when the Veteran selects "Yes." Selecting "Yes," would link the Veteran to [this page](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/zxQbWQa). I have the content in an alert. Should it just be an H1?

cc @mdewey

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell @peggygannon @shiragoodman 
This product now has a content brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/check-in-experience.md

**Comment by kristenmcconnell** [comment]
The content brief looks good. Thank you. Good to know your recommendation on pre-check-in, because I was writing it as pre-check in.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell. Let me know if you have any questions about any of this. Thanks!
[Check-in experience (onsite check-in only)_v1.060721](https://app.zenhub.com/files/133843125/12e98714-8dda-4bb9-b482-a81fc9bac0a3/download)

**Comment by kristenmcconnell** [comment]
No questions. The content looks great. Though, Patrick Bateman just posted in [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1623157764398200?thread_ts=1623099658.383100&cid=C022AC2STBM) that he is interested in seeing a poster that says "let us know you're here" versus the term check-in. The term check-in didn't seem to cause any confusion when utilized in the initial discovery test. Thoughts? I'm going to think through a way to test this terminology in the upcoming 
usability test.

**Comment by jparker0425** [comment]
@kristenmcconnell What phrase has been used up to this point regarding the new check-in experience with the Veterans? My only concern about having the poster say something different is lack of continuity between the language being used. It may not make a huge impact, but I know once the Veteran actually launches the URL the actual process is to click "Check-in now". Would we not want to keep the same language on the poster and leave as "check-in"?

**Comment by kristenmcconnell** [comment]
@jparker0425 Veterans seemed to have no problem with the term "check-in" during the initial discovery research. I could possibly test this as a variable during the upcoming usability test. I could show half the participants one poster saying "here" and the other half one saying "check-in." Then, we could see if there was a difference in understanding or feedback. On the other hand, we could just test the "check-in" poster with all participants and see if there is any confusion. 

I would want continuity in language (like you mentioned), so that would mean...changes to UI need to be determined. Ideally, I would want to A/B test the two UI options. Since we are testing in staging that means Mark would need to build two versions. As a result, I'm leaning towards just testing "check-in" and seeing if there is any confusion.

cc @batemapf

**Comment by jparker0425** [comment]
I agree @kristenmcconnell, especially with this being the MVP. I feel we should test using just the "check-in" terminology, solicit feedback from testing, and then potentially make changes to the UI subsequently based on that feedback.

That said, we could even explicitly call it out in the usability testing and ask if there would be a preferred terminology, or if it even makes a difference to the Veteran?

@batemapf thoughts?

**Comment by kristenmcconnell** [comment]
I can definitely add a question to the wrap-up section. 

Something like...
Now that you've seen this entire experience, what wording would you want the initial poster and webpages to use?
- let us know you're here
- check-in
- something else 
- I don't have a preference

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA I like the consistency. Can you post the "check in" suggestion for the text message in this [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1623162568403900)? The VEText team will need to know about it.

**Comment by DanielleThierryUSDSVA** [comment]
Sure! Posting now.

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Thoughts on this version of the poster with a QR code?

[https://app.zenhub.com/files/133843125/e2c3bcd5-99fa-4dfe-bf98-e19c578df0ca/download](https://app.zenhub.com/files/133843125/e2c3bcd5-99fa-4dfe-bf98-e19c578df0ca/download)

**Comment by kristenmcconnell** [comment]
@artsymartha68 Posted this comment in the check-in Sketch file that I wanted to pass onto you as well, Danielle.

On the confirmation page,

Maybe "You are now checked in" to double-confirm in big letters that they are indeed checked in? Vs the thank you. Just an idea, happy to defer to content folks.

**Comment by artsymartha68** [comment]
LOL @DanielleThierryUSDSVA I seem to be on a mission to remove all niceties from our UIs. First "please" now "thank you".  As always, you get to make the final call.

**Comment by DanielleThierryUSDSVA** [comment]
Ha, @artsymartha68! I actually went back and forth between the 2 approaches with this one. I ultimately landed on the "Thank you" version because I thought it flowed better into the "We'll let you know when we're ready..." line and still feels clear. But I'm not attached to it and can see the value in "You're now checked in" approach.

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell poster looks great!

**Comment by kristenmcconnell** [comment]
Great.

**Comment by kristenmcconnell** [comment]
@jparker0425 I'm closing this, since we have moved onto Phase 2 and have a content support ticket for that.
