### ISSUE TITLE
Add Analytics Events

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#25232]
The following analytics events need to be added to the application:

#### When:
- [ ] When a user successfully logs into the app through the webview and receives an access token. Does not include biometrics login
Event Name: vama-login-success
Event Params: none

#### When:
- [ ] When a user hits the cancel button in the login web view
- [ ] When a user receives an error in the login/code exchange actions

Event Name: vama-login-fail
Event Params: none

### When:
- [ ] After successful send of Compose Message
- [ ] After Successful send of Reply Message

Event Name: vama-sm-send-message
Event Params: none

## User Properties
###Available Services:
saves a list of services the user can access
#### When: 
- [ ] Upon log in and after profile endpoint is recieved
Property Name: vama-profile-services
Property Type: Object
```
{
  appeals: boolean
  appointments: boolean
  claims: boolean
  directDepositBenefits: boolean
  lettersAndDocuments: boolean
  militaryServiceHistory: boolean
  userProfileUpdate: boolean
  secureMessaging: boolean
}
```

### Uses Biometric:
Saves a boolean for a users decision on the biometric options
#### When:
- [ ] When a user chooses biometric log during the first log in 
- [ ] When user toggles biometric in the settings page
- [ ] If a user's device doesnt support, set to false

Property Name: vama-login-uses-biometric
Property Type: boolean

###Has Biometric Device:
Saves a boolean that indicates if the device has biometric or not. 
####When:
- [ ] At log in when the access token is saved
Property Name: vama-login-biometric-device
Property Type: boolean

###Stagin/production
Flag to indicate staging builds from production builds. This will need a new ENV for `ENVIRONMENT` that will also need to be added to the `env.sh` script
###When:
- [ ] right after User Services are set
Property Name: vama-environment
Property Value: string
`productions, staging`

**Comment by digitalken** [comment]
Closing 6/2/2021.
