### ISSUE TITLE
Analytics: User Usage Properties

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#25235]
When collecting analytics, we also want to know when a user has utilized an available service. Utilization will consist of any action beyond viewing the overview page or list of items. So downloading a letter, viewing a secure message, viewing appointment details, etc. This list will update the user property vama-uses-{service} when this happens.

### vama-uses-letters
- [ ] User downloads a letter

### vama-uses-secure-messaging
- [ ] User opens a Secure Message from any of their boxes
- [ ] User sends a Secure Message

### vama-uses-claim-and-appeals
- [ ] User looks at the details of a claim or appeal

### vama-uses-appointments
- [ ] User looks at the details of an appointment

### vama-uses-profile
- [ ] User updates any information in the profile area

### vama-uses-vcl
- [ ] User clicks any of the CTA for VCL

**Comment by ayushchak** [comment]
Hi @bessgreen, adding you to this ticket for FE, but please let us know how we can support!

**Comment by digitalken** [comment]
Closing 6/2/2021.
