### ISSUE TITLE
Find a VA Form [Discovery] - PDF "download" attribute & Content-Disposition

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25236]
## User Story

As a Veteran or Veteran's caregiver/representative, I would like to be able to download PDF forms locally without having to read or follow explicit instructions (when technically feasible) so that I can save time when downloading a form.

## Expected Behavior

HTML5 has a "download" attribute `<a href="/images/myw3schoolsimage.jpg" download>` that may be used to 'force' a PDF form to download rather than open in a browser.  https://www.w3schools.com/tags/att_a_download.asp

There is also an http header option Content-Disposition: attachment; filename="fname.ext" that can be set to force download of the PDF, but this may be something that would have to be part of the actual PDF document itself (something we cannot control).

We want to test the download attribute and confirm that it will not cause issues if implemented in conjunction with the PDF download instructions.  It is likely the attribute will not force a download in every case, but download instructions are intended to handle those scenarios.

## Acceptance Criteria
[ ] Add download attribute to PDF links on Staging
[ ] Test and document how popular browsers behave when encountering the link with the download attribute

**Comment by MarciMcGuireGCIO** [comment]
Per Zach, this is already baked into VA.gov when the form is hosted on the VA.gov domain. Closing out this discovery ticket.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO I'm sorry, I didn't relay that info correctly. 

For find-forms, the download functionality I mentioned in our chats I have written up for that tool only. 
However, if the PDF uses a different domain other than va.gov, we will need PDF right click download instructions.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel - Oh, no worries!  I understood we would need to provide instructions for domains other than va.gov.
