### ISSUE TITLE
MAINTAIN - Platform Website

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25249]
# Description

Various tasks around keeping the Platform Website neat.  In this sprint:

- [x] Amy - Update Platform Website style guide https://github.com/department-of-veterans-affairs/va.gov-team/issues/24451
- [x] Gretchen - Replace the word `VSP` with `Platform`
- [x] Gretchen - Adding the feedback snippet to existing previous pages
- [x] Amy - Removing duplicate custom template in individual spaces
- [x] Gretchen - Deployment policy update
  - Update names for off-cycle deploys
  - Update link to deploy policy from deploy process doc

# Reference info
- n/a

**Comment by lianilychee** [comment]
Weds 6/2:
- Amy - `Update Platform Website style guide #24451`
  - Primarily examples missing (will take care this week as fits), secondarily organization
- Gretchen - Replace the word VSP with Platform, Adding the feedback snippet to existing previous pages
  - populated [spreadsheet](https://docs.google.com/spreadsheets/d/1fTS_JAp7RhXbybAgIzmfunPUZ-533yaPD_j48Xyvn7I/edit#gid=1257506133)
  - updated Confluence but not Scroll Viewport yet
  - changing titles to sentence case
  - goal by tomorrow: want to be at least 75% thru editing

**Comment by gmaciolek** [comment]
- completed:
  -  replaced VSP with Platform
  - added the feedback snippet
  - changed page titles to title case for all pages
- Updated [spreadsheet](https://docs.google.com/spreadsheets/d/1fTS_JAp7RhXbybAgIzmfunPUZ-533yaPD_j48Xyvn7I/edit?usp=sharing)

**Comment by lianilychee** [comment]
Questions for Fri 6/4:
- how are we intending to use the spreadsheet (or an incarnation of it) going forward?
- can we have a time block for Friday for the style guide?

**Comment by lianilychee** [comment]
6/8 Tues:
- done!  now shelving till Gretchen returns
