### ISSUE TITLE
Showing both cancelled and occurred in the past boxes for cancelled appointments in the past

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25244]
If an appointment has a past date and was canceled, then we show two boxes:

![Screen Shot 2021-05-25 at 3.37.09 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/a91b6136-9132-4f43-9a57-41d0698ee7a6)

I imagine we just want to show the canceled box.

**Comment by jbalboni** [comment]
@outerpress Am I correct in saying this is a bug, to have both colored boxes?

**Comment by outerpress** [comment]
@jbalboni yep, the "Past" box is only for appointments that occurred in the past. The "Canceled" box is only for appointments that were canceled (so never occurred). So there shouldn't be overlap between those two states.
