### ISSUE TITLE
Analytics Implementation (Change Event Name) for eBenefits

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25246]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?

    - Jason Wolf and Micah Chiang
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    The eBenefits Team is hoping to add an event name to the CH31 feature (ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24557)) and we want to validate the event name against any standards or requested changes to the event name before implementing it
    
    - eBenefits Team , VR&E CH31 feature
    
- Provide the Domain where Google Analytics needs to be implemented
   - www.va.gov  
    
    _Identify if PII is passed in URL or title tag:_ **No**
    
    - https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - No critical dates, we would just like to track one of the skip buttons

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - This is for the first action link after the wizard on this page: https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start
    
    - *Other User Interactions*: _N/A_  
    
    - [Other user interactions here] _N/A_  

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here] _N/A_

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]  _N/A_

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]  _N/A_

- Additional Comments

    - Just need to get some feedback on  the event name for an action link on the start page for our form.  Proposing `ch31-orientation-skip` but happy to accommodate?

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jason-gcio** [comment]
cc: @micahchiang

**Comment by jason-gcio** [comment]
cc: @cohnjesse

**Comment by laurensimpson14** [comment]
@jason-gcio I'm not seeing a "skip" CTA 
![image](https://user-images.githubusercontent.com/80417436/120673432-2bc2f180-c461-11eb-9264-459b78cc1e9f.png)

Where can I find the "skip" button?

**Comment by jason-gcio** [comment]
I believe it is after the wizard, right before the Orientation content...the first text link (not highlighted) is good to go I think
![image](https://user-images.githubusercontent.com/53826255/120707157-fc73ab00-c487-11eb-855d-8722f8e79521.png)

**Comment by laurensimpson14** [comment]
Aha! I see it now. It looks like that link is already being tracked with the event `howToWizard-skip` and can be viewed in GA here: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22howToWizard-skip%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22apply-vre-form-28-1900%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath

Is tracking it what you were aiming to do, or was there a motive to renaming it?

**Comment by jason-gcio** [comment]
Oh ok, I was under the assumption we were missing that.  Is the text link above set up as well?

**Comment by laurensimpson14** [comment]
Sorry, I misunderstood your first message. So this text highlighted in green is the one being tracked with the event `howToWizard-skip`. 
![image](https://user-images.githubusercontent.com/80417436/120709987-9557f580-c48b-11eb-84da-16aa830107c8.png)

The link highlighted in yellow (which I now realize you were talking about initially) is not tracking. 
![image](https://user-images.githubusercontent.com/80417436/120710124-c33d3a00-c48b-11eb-8b4d-7c21a499ec45.png)
That link ^ is an "action link". Here's what we send in for those...
`{
     event: 'cta-action-link-click',
     'action-link-type': 'primary',
     'action-link-click-label': "Apply for Veteran Readiness and Employment with VA Form 28-1900",
     'action-link-icon-color': 'green',
}`

**Comment by jason-gcio** [comment]
Right...there is another action link when the Veteran completes the Orientation content as well, that is being tracked as well but I think what we want to pin point is this one (in yellow) as different from the others

**Comment by laurensimpson14** [comment]
It looks like the label text is different, so that should distinguish one from the other, right?
![image](https://user-images.githubusercontent.com/80417436/120725049-1373c680-c4a3-11eb-936d-c8fe19aabf70.png)

**Comment by joanneesteban** [comment]
@jason-gcio Hi! Let us know if you need to distinguish between the 2 links in the screenshots above. Thanks!

**Comment by micahchiang** [comment]
Hey @joanneesteban - Jason is OOO right now so he may not get back to you right away. Yes, I believe we do need to distinguish between the two links in the screenshot above since they semantically mean different things. 

The first one is for when a user completes the wizard but then chooses to skip the chapter 31 orientation. We currently have a GA event for that called `howToWizard-skip-orientation`. 

The second one is for when a user has completed the orientation. Looking at our code - [here](https://github.com/department-of-veterans-affairs/vets-website/blob/547f7fe2502d927c936b7c02317415725f409d8f/src/applications/vre/28-1900/orientation/StepComponent.jsx#L62-L71) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/f482361eda1e6dea3a5928472e1eed1f20355531/src/applications/vre/28-1900/containers/App.jsx#L9-L11), it doesn't look like we have a GA event for this yet. We probably need one for that 😄

**Comment by joanneesteban** [comment]
Got it! Thanks for the quick response, @micahchiang !

FYSA @bsmartin-ep @laurensimpson14

**Comment by bsmartin-ep** [comment]
@micahchiang -

Event `howToWizard-complete-orientation` works for me.

**Comment by bsmartin-ep** [comment]
@laurensimpson14 - Since you've QA'd most of this, would you mind testing the skip and complete orientation events on this GTM workspace?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000534

Thanks!

**Comment by micahchiang** [comment]
cc @jason-gcio

**Comment by laurensimpson14** [comment]
@bsmartin-ep The `howToWizard-skip-orientation` event is firing correctly in the GTM workspace: 
![image](https://user-images.githubusercontent.com/80417436/125980609-f65e91ee-f8c7-4472-8f8c-41841a87ecf8.png)

However, the `howToWizard-complete-orientation` event is not firing. It should be this button after the user gets through the 10 orientation slides - correct @micahchiang? 
![image](https://user-images.githubusercontent.com/80417436/125981219-46805736-85fb-4b0a-aba6-c68db5a81aca.png)

**Comment by micahchiang** [comment]
@laurensimpson14 - yes that's correct, it will be on that button. It isn't firing because we haven't attached it to the button just yet. 

@jason-gcio - could you please create a ticket for this? Not sure if we have one on the board for it yet.

**Comment by micahchiang** [comment]
@laurensimpson14 - GA event has been added

**Comment by micahchiang** [comment]
@laurensimpson14 - I don't think there is anything else. Thanks for the support!
