### ISSUE TITLE
Contact Center Review | Language  Assistance & Resource Pages | C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25240]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

### Launch Date
* Targeted for June 7, 2021

### Product Guide
*Please provide product guide link*

[https://app.zenhub.com/files/133843125/446eed54-be7b-4a6c-a129-ebcca8f578c2/download](https://app.zenhub.com/files/133843125/446eed54-be7b-4a6c-a129-ebcca8f578c2/download)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hi @SKasimow. Can you please link the document to this? Thanks!

**Comment by SKasimow** [comment]
@starlow00 Hi - sorry I just opened this ticket and started working on the doc. Meant to remove you guys until it is ready.  I'm doing that now...and will add you back/tag you once I have it drafted. Thanks, Sharon

**Comment by SKasimow** [comment]
@starlow00 Hi Steven - just attached my draft product guide; please have a look and lmk if you have any questions (and feel free to tweak formatting!). Thanks, Sharon

**Comment by starlow00** [comment]
Hi @SKasimow , I've attached my edits here. Looks good, just minor things. I'd say the main thing is to make sure to include captions for the figures and link them to a Table of Figures. Questions, please let me know. Once you're good with it, I can move this to VEO.

[language-assistance-resource-product-guide_ST_060121.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6580714/language-assistance-resource-product-guide_ST_060121.docx)

**Comment by SKasimow** [comment]
Hi @starlow00 - your edits look good! Thanks for putting those finishing touches on with figures and links to figures. 
Sharon

**Comment by starlow00** [comment]
Sent to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO.
[language-assistance-resource-product-guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6634566/language-assistance-resource-product-guide.docx)
