### ISSUE TITLE
Allow 3 simultaneous matrix jobs with GHA self-hosted runners in content-build

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#25257]
## Description
In content-build, in the GHA conflig `.github/workflows/continuous-integration.yml` we have:

```
strategy:
  matrix:
    buildtype: [vagovdev, vagovstaging, vagovprod]
```

This should run a job for each buildtype in parallel. However in practice only two of the jobs run in parallel. When they complete, the third job runs. It appears that only two runners are available in content-build, so the maximum number of parallel jobs is two when executing a matrix strategy.

Increasing the number of runners to 3 or more should allow all 3 builds to run in parallel. Short term this will allow us to test 3 builds in parallel with 48k nodes, and in the longer term it will save a significant amount of build time.

## Background/context/resources
From the [GitHub Support Community](https://github.community/t/do-jobs-in-self-hosted-runners-run-in-parallel/17776):

> One self-hosted runner can only run one job at a time, when no available runners are idle, the subsequent jobs will be in queueing until available runners are idle.

## Technical notes
Does each runner require its own EC2 instance? Or can we have multiple runners per instance, allowing multiple parallel jobs per instance?

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@alexandec - some additional information on this topic: 

https://github.community/t/how-to-run-multiple-self-hosted-runners-on-a-single-host/130474

Ops is looking into this functionality, but is not yet picking up this ticket at this time.

**Comment by alexandec** [comment]
Sounds good, thanks for the update Jesse!

**Comment by jhouse-solvd** [comment]
@alexandec - there are now many more than just 3 runners. you should be able to run matrix jobs pretty easily. 

please confirm and close if all is well. removing the operations label for now, but feel free to tag me or re-add if needed.

**Comment by alexandec** [comment]
I've been testing the content build with this new setup and it works fine. Closing the ticket.
