### ISSUE TITLE
FSR Tech Debt

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#25259]
##  Description
Capturing some tech debt and other issues for FSR fixes

**Comment by Tom-Davis** [comment]
Moved all remaining work to Ongoing Maintenance Epic [#72728](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72728) - closing.
