### ISSUE TITLE
Request Limit Pop Up Modal Window Won't Close

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25267]
1. Log in a Judy Morrison. Select Ambulatory Care. Select Cheyenne
2. This window displays:  You’ve reached the limit for appointment request
3. Select the "X" in upper right corner.  Expected Response:  Pop up modal window closes.  Actual Response:  Window won't close.  User has to refresh page  to close window.

Same thing happens if I pick Eye, Ophthalmology and Fort Collins.

![RequestLimitPopUpWontClose.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/0c2f69d3-1a93-40b4-ba1a-dbe8e772ab67)

**Comment by aarathi-poldass** [comment]
Completed QA Validation. Works as expected.
