### ISSUE TITLE
Add Downtime Notifications to FSR

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#25266]
### UserStory
As a Veteran I would like to know if the form application is down before I start the form so I do not waste time filling out a form I cannot submit. 

Implement downtime notifications on the FE so we can schedule downtime maintenance and give that information to the users.

### Acceptance Criteria
- [ ] Veteran are notified on entry of the FSR when downtime is scheduled

**Comment by LinnJS** [comment]
We probably need to break this down into a couple task.

First one probably being for BE to map out all possible error states

Another for design to map the possible error states to content to show the users 

Then another ticket for the FE to implement those error states.

**Comment by LindaLi123** [comment]
Duplicate ticket
