### ISSUE TITLE
Contact Center Resources - Improve Product Guides

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#25262]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/product-outlines/contact-center-tier-2-and-3-support.md)

This epic most closely ties to our tier 2/3 support product, but is primarily to improve a component (product guides) of the collaboration cycle owned by the product support team. We own the process of ensuring product guides are comprehensive and efficiently usable by contact center support agents.

## High Level User Story/ies
As a contact center support agent, I need comprehensive and intuitive product guide to reference when Veterans call so I can solve the issues they are experience while using VA.gov.

## Hypothesis or Bet
**If** _we add a clickable table of contents to product guids, update our best practices doc with that requirement, and provide a comprehensive `example product guide`_ **then** _we expect to see a reduction in time to resolution for CC support agents_.

## OKR
_TBD_

### For this epic to be done, we will complete the following things:
- Update existing product guide best practices doc with new requirements (i.e. clickable table of contents, table of figures and appropriate references when figures are used, title page required, consistent use of headers/sub-headers, etc.)
- Update CC product guide review/request guidelines
- Collab Cycle PM has been notified of changes and provide documentation
- Product Guide Review template is created and made available to VFS teams

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ATMiddleton** [comment]
In conjunction with ticket #239
