### ISSUE TITLE
Claims Integration | Request decision - Requested decision and got an error page

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#25260]
## What happened?
I made a request for a decision when there was still 1 file request pending from VA.  After making the request, I got an error page.  When I backed out to look at the claim, it appeared that the request had been made.  I went back out to the claims listing and tapped to return to the same claim, and it seemed to take a few moments to reload.  When it reloaded, I saw that there was still a file request.  I tapped to view file requests and then view details for asking for a claim decision.  This time I got a request received notification when it opened.

See screen shots below.

## Specs:
- Device: iPhone XR
- User:  arfan.a.russel1 on the DS login

## Steps to Reproduce
- Login as arfan.a.russel1
- Go to Claims
- Choose the top active claim in the listing that was submitted on January 01, 2021
- Tap into View File requests
- Go to ask for Claim decision and tap View details
- Request for claim to be made.  
- Received error page.
- Backed out to see claim and I couldn't request decision or submit file.
- Backed out to see claims listing and then returned to Claim.
- Claim took a few seconds to load and then I saw that a file request was pending.
- I tapped into the file request and then tapped into requesting a decision.
- This time I see a Request received notification.
- It looks like I'm still able to request a decision and upload a file.

## Desired behavior
User does not get an error when requesting a decision, but rather the decision requested notification.
I'm also suspecting that requesting the decision closes out the ability to interact with the claim any further in terms of uploading files?

## Acceptance Criteria
See above.

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/24756

## Screen shot(s) and additional information

1. This is the response I got when I first requested a decision be made.
![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/9d706be4-e219-4692-915b-dcf3af630638)

2. I went back out to the claims listing and then went back into the same claim.  It reloaded and then displayed this.
![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/d400dc23-63ff-4a7a-ae53-f3e00ee98c1c)

3. I went further in to look at the file request page and saw this.
![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/917c4056-3541-4d0d-819b-7a928c286161)

4. I tapped to view details on asking for a claim decision and saw this.
![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/5f734406-b626-40f6-a402-3feeacfd8fcc)

**Comment by patrickvinograd** [comment]
I believe this is caused by the issue fixed in this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/7105

**Comment by digitalken** [comment]
PASS 6/2/2021 - Submitted a request gave the expected response.  Closing.
