### ISSUE TITLE
Update zero results user message

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25264]
## Description

As a product team we would like to review the message users are receiving when no results are presented to the user

## Background/Context

![0 results image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/a9ba6db2-9781-4e24-8927-1b6f5c60fa85)

## Definition of Done

- [x] Update Messaging for no results pages: User doesn't type anything:
"We didn't find any results. Enter a keyword in the search box to try again."
- [x] No results after user types something:
"We didn't find any results for "**term**." Try using different words or checking the spelling of the words you're using."
 - [x] Tier 2 (must be validated in Socks by Design Lead)

**Comment by srsuddath** [comment]
Messages have been updated and confirmed by @mgleo & @denisecoveyduc
