### ISSUE TITLE
Updates to chatbot 5.25.21

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#25265]

**Comment by DanielleThierryUSDSVA** [comment]
### COVID-19 prevention section

1. "What steps can I take to protect myself and others from COVID-19?"

Update answer to:

If you haven't yet received your COVID-19 vaccine:

- [Find out if you can get a COVID-19 vaccine at VA](https://www.va.gov/health-care/covid-19-vaccine/)

- [Find COVID-19 vaccine locations near you with the CDC vaccine finder tool]

- (https://www.vaccines.gov/)[Get tips on how to protect yourself and others from the CDC](https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention.html)

2. "If I need to leave my house, how do I stay safe?" - Delete question

3. "Should I wear a mask?"

- Update question to: 

What's VA's current policy on masks?

- Update answer to:

We follow CDC guidelines for cloth masks. The updated guidelines state that fully vaccinated people don’t need to wear a mask in many places. The guidance doesn’t apply to health care settings.

Your safety is our top priority. Here’s our current mask policy for different VA locations:

At VA health care facilities: We require everyone who enters our hospitals, clinics, and Vet Centers to wear a mask that covers their mouth and nose. If you’re fully vaccinated, we ask that you still wear a mask when you enter the facility. Our staff will tell you when it’s safe to remove your mask.

At VA national cemeteries: If you're not  fully vaccinated, please wear a cloth mask and follow physical distancing guidelines. Some areas such as info centers, pavilions, restrooms, or chapels may be closed.

Other VA locations: Our staff will explain the specific location’s mask policy when you arrive.
Check back often for updates.

**Note:** We continue to screen all visitors to our health and other facilities for COVID-19 symptoms. We also continue to follow physical distancing and other safety guidelines.

### COVID-19 vaccines question

- Add this question after "Who else can get a COVID-19 vaccine at VA?"

Can eligible adolescents ages 12 to 17 get a COVID-19 vaccine at VA?
Yes. Eligible adolescents ages 12 to 17 can now get a Pfizer-BioNTech vaccine at VA facilities that provide this vaccine. 

Adolescents are eligible if they meet either of these requirements:

- They receive CHAMPVA benefits, **or**

- They help provide care or assistance to a Veteran

Here’s what to know:

- The Pfizer-BioNTech is the only COVID-19 vaccine authorized for use in adolescents at this time. Not all VA health facilities offer this vaccine right now. Check with your VA facility before you go to get a vaccine.
[Find your nearest VA health facility that offers COVID-19 vaccines ](www.va.gov/find-locations/?facilityType=health&serviceType=Covid19Vaccine)

- The adolescent’s parent or legal  guardian must come with them to get the vaccine. Both the adolescent and their parent or guardian must give their consent for the vaccine.

### Health care, appointments, and prescriptions section

1. "Should I get a flu shot this year?" question: Delete question

2. "Do I need to wear a mask when I go to a VA hospital or other location?"

- Change question to:

Do I need to wear a mask in a VA health facility or Vet Center?

- Change answer to:

Yes. To help us protect you, other patients, and our staff, we require everyone who enters our hospitals, clinics, and Vet Centers to wear a mask that covers their mouth and nose.

Here’s what to know:

If you’re fully vaccinated, we ask that you still wear a mask when you enter the facility. Our staff will tell you when it’s safe to remove your mask.

Please bring your own mask with you if you can. If you can’t, we’ll provide you with one.

If you wear an oxygen mask, you don’t need to wear a separate mask. We’ll work with you to keep you and others safe. We may ask you to wait in a designated space until your appointment time.
If you have concerns about wearing a mask, talk with your provider. They’ll work with you to get you the care you need and follow safety guidelines.  

[Find your VA provider’s phone number](https://www.va.gov/find-locations)

[Learn more about cloth masks on the CDC website](https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/diy-cloth-face-coverings.html)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Can you please make the updates above in the chatbot and let me know when PR is ready for review? Thanks very much!

**Comment by lunascoop** [comment]
Morning @DanielleThierryUSDSVA I made the changes and they're ready for review. I created a PR ([#389](https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/389)), but one of the checks failed. I assume it's because I changed the key words for some of the questions in the chatbot messages file, but I reached out to Shefali and Katie via Slack to confirm.

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO Would you be able to review this PR for Selina?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. I reviewed the PR, but commit seems to have an issue. I think just slack the team in the morning and ask them to take a look at it before merging. Thank you, as always, for your work on this!

**Comment by lunascoop** [comment]
Chatbot updates are live. Closing ticket.
