### ISSUE TITLE
[Discovery] Determine UX Issue on Burials and Memorials Pre-Form

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#2526]
## Goal

Determine where to guide the user if they cannot complete a pre-need application.

## Acceptance Criteria

- [ ] Understand the process of submitting a pre-need application
- [ ] Determine what steps to take if user cannot complete a pre-need form

**Comment by kevinstachura** [comment]
From Leah Bannon:

I think the main problem is that the user is trying to complete a pre-need application, and the error message is giving them the impression that they can still accomplish this task by calling a help desk. I think we may need a product/design person to weigh in on this -- what should the user be directed to do if they can't complete our pre-need form on VA.gov? Is there an alternative path? Should they just come back later?

Sounds like they believe it's an error message that pops up on one of these pages:

https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction

Or this page:

https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information

**Comment by sonntag-adam** [comment]
@ccruzgra @barron-charles

**Comment by barron-charles** [comment]
Hey @kevinstachura @leahbannon, 

It's been a while, but we have a question for you guys. Our team is working through this issue and we're wondering if the message attached is the specific message being referenced. 

@ccruzgra and I have only see this pop up at the Confirmation page, but above it's listed under the Introduction and Applicant Information pages here. If it isn't the right reference, or there are other messages being referenced, we'd appreciate some examples!

<img width="815" alt="Pre-Need Error Message Example" src="https://user-images.githubusercontent.com/95768999/228045193-3eee9512-7fb3-4ca3-a25d-292fd3590140.png">

**Comment by MichelleDieudonne** [comment]
@kevinstachura @leahbannon @CBonade We have completed this item, can you please close this ticket or give us the permission to do so?  Thank you!
