### ISSUE TITLE
Find a VA Form: Contact Jeff Grandon / Jenny Heiland-Luedtke re 10-10ez form on OPA site

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25272]
Slack message from Jen Lee 5/19/2021

https://dsva.slack.com/archives/CUB5X5MGF/p1621460599037200

https://www.va.gov/opa/choiceact/documents/1010EZ-fillable.pdf
@John Hashimoto @Marci McGuire - would you mind reaching out to Jeff Grandon/Jenny HL, and ask them to have whatever this OPA site is to take down this rogue unofficial 10-10ez form and point to the official 10-10ez form URL and/or (better yet) the modernized form detail landing page?  Don’t ask how I found it, but it is coming up in anonymized Google searches against the official 10-10ez and form landing page. Not to mention that it is pointing to a very old, 2015 outdated version of the form because it is not pulling from the official VA forms database. 

<hr>

Note from Marci:  Jenny HL = Jenny Heiland-Luedtke

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO will reach out to Jenny and Jeffrey about this today with a cc: to you.  thanks for the reminder.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @johnhashva !
