### ISSUE TITLE
Assess manual Sentry triage process & add to FE support rotation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25271]
## Details 

Sentry errors are not manually triaged. This used to be included as part of the FE support rotation responsibilities but is now listed as optional and has not been done lately. 

The list of errors is currently very long. 

## To Do 

- [ ] Assess list of current errors and consider deleting/starting from scratch
- [ ] Draft error triage process for FE support rotation to follow including details on expected time commitment 
- [ ] Review new process with FE Tools team members and implement 

Try the new process for 1 round of support (~8 weeks) and reassess with the team.

**Comment by mchelen-gov** [comment]
is this different from https://github.com/department-of-veterans-affairs/va.gov-team/issues/24144 ?

**Comment by meganhkelley** [comment]
@mchelen Nope, it certainly is not - haha! Classic case of forgetting I had already made a ticket. 

Here are the details from the other one & I'll close that now. 

Details
FE Tools is not currently triaging errors that happen on the website.

The purpose of this issue is to investigate and make a recommendation for Sentry error triaging.

Questions to answer:

Is it feasible to triage errors manually as they come in?
Could this be incorporated into the existing FE support workflow?
Is it worth looking into automated error alert triaging as a solution?
Is that something we should look into as a now solution, or something we should put in the backlog for future?
Should the error queue be reset?
What should the threshold be (# of users affected) for errors being reported? For errors requiring action?

**Comment by jhonnyoddball** [comment]
Expired. Closing
