### ISSUE TITLE
Incorporate VADIR data

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#25270]
## Issue Description
Figure out how to access VADIR data so that we can eliminate PTSD questions. Start with eMIS and move to VA Profile.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
from the [ATO document](https://github.com/department-of-veterans-affairs/vets.gov-ato/blob/master/assets/VetsGov%20ISAMOUs/Vets.gov%20VA%20VRS%20MOU%20ISA%2020170501.pdf):

![Screen Shot 2021-06-04 at 9.08.15 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/35ca94ef-13d4-4ee4-9dda-7234583901f9)
![Screen Shot 2021-06-04 at 9.01.22 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/16065838-1a62-487f-9b98-ddc69e42459f)

![Screen Shot 2021-06-04 at 9.01.49 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/e08076a5-0c7c-4f69-94bd-1b4c7e14f6b7)

**Comment by annaswims** [comment]
As we talked about in grooming, here is an overview of the data available.  @kevinstachura @chrvalla does any of this look like stuff you'd want to know more about?
