### ISSUE TITLE
Access for Megan Gayle

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#25284]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Megan Gayle
- Please Provide your email.
   >mgayle@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name: Search & Discovery
   > My Role: Senior Visual Designer/Researcher
   > Company: GovernmentCIO

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2qhIq0ComdOPNTNfOLCkPavQ+3jZOpYaoBTefY4jXMsVoF3iB6RRGyI97vjXaQ6C2alKfpoVG28tue593N78GBDAfAJt7hS9s0C3ujbyvYhMg8+a7opqZX/sMCZx0HN/QWcFAIuNheTPbgS4+XEw6QV0vEstrhV0t0hJBJg9iFk5g0bsF2xDOTxnXqVbSRqRLjDaHUOo5bO3jSfsSpTkDOc/tMyeo1rvjzZC9nReLNtKPscb68z3xhph5dl925xpSmirNnzDaAr1EL0lJi9hPno4/o6IbCtsWdG3jH9Y5SMCpSuhIoAYlw3dQkiClUf3AVsPNxNzqc1w/YowNYHFNkCnBCRWQW4IwQnU7D5nXZJ9P/YEv+1vBBcYRdIwMCYp1b9yPkkD3MoGkWkYrcUbX+KmYJGrMBbIN8oxJvSUhOjqFAkgQJXfs7rKZodm369gumHjb5U2Y+X/+1pJXo9cP/aOo9DpWy3xj4KsSiYbdKdv5oVDq/ikZ/3E7p5aR5mc= megan@Megans-MBP.fios-router.home
```

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why?

**Comment by mleclerc00** [comment]
@mgleo 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by mgleo** [comment]
@mleclerc00 Apologies, I somehow added an extra _**ssh-rsa**_ before my public key above. Just edited my original ticket, can this be updated? Thank you.
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2qhIq0ComdOPNTNfOLCkPavQ+3jZOpYaoBTefY4jXMsVoF3iB6RRGyI97vjXaQ6C2alKfpoVG28tue593N78GBDAfAJt7hS9s0C3ujbyvYhMg8+a7opqZX/sMCZx0HN/QWcFAIuNheTPbgS4+XEw6QV0vEstrhV0t0hJBJg9iFk5g0bsF2xDOTxnXqVbSRqRLjDaHUOo5bO3jSfsSpTkDOc/tMyeo1rvjzZC9nReLNtKPscb68z3xhph5dl925xpSmirNnzDaAr1EL0lJi9hPno4/o6IbCtsWdG3jH9Y5SMCpSuhIoAYlw3dQkiClUf3AVsPNxNzqc1w/YowNYHFNkCnBCRWQW4IwQnU7D5nXZJ9P/YEv+1vBBcYRdIwMCYp1b9yPkkD3MoGkWkYrcUbX+KmYJGrMBbIN8oxJvSUhOjqFAkgQJXfs7rKZodm369gumHjb5U2Y+X/+1pJXo9cP/aOo9DpWy3xj4KsSiYbdKdv5oVDq/ikZ/3E7p5aR5mc= megan@Megans-MBP.fios-router.home
```

**Comment by mleclerc00** [comment]
Whoops! Sorry about that I completely skimmed over that when doing the copy/paste.  You should be good now though.

**Comment by mgleo** [comment]
Thank you! Looks like everything's working now.
