### ISSUE TITLE
Latency with uploads to S3

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#25286]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
We generate a signed URL to services_user_content/vba_documents/ where a PUT request can be made to upload to S3. We noticed that it takes anywhere from 7 to 10 minutes in sandbox. There are also complaints in prod. But we should recreate in sandbox first. Please look at this request from an AWS instance with 5GB ethernet:

## Background/context/resources
Users of the Benefits Intake API are reporting slow upload times to S3. See: https://developer.va.gov/explore/benefits/docs/benefits?version=current

## Technical notes
Recreated with a t3.small with 2 CPU and 4GB Ram and 5GB ethernet. Tested with both Ruby code and Curl

_Notes around work that is happening, if applicable_
160.1.7.119

Start
< Date: Wed, 26 May 2021 14:31:35 GMT

https://sandbox-api.va.gov/services_user_content/vba_documents/32343df8-c4c4-4eb9-bca6-e41d63297eaf

Finish. 598 sec for three 95 MB attachments.

160.1.7.119 - - [26/May/2021:14:41:33 +0000] "PUT /services_user_content/vba_documents/32343df8-c4c4-4eb9-bca6-e41d63297eafHTTP/1.1" 200 0 "-" sandbox-api.va.gov - "Faraday v1.4.2" "160.1.7.119, 10.238.28.71"

---
## Tasks
- [ ] _What things need to happen?_
We need to investigate why a 5 gigabit connection cannot upload a 300 MB in a timely (1-2 min) manner.
## Definition of Done
- [ ] _What is the expected outcome of this issue?_
Without Kong overhead, this should happen in only a few seconds, however we understand f5 and kong overhead adds to this, but we should see closer to 1-2 minutes in sandbox.
---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
I believe that @mviterna and the team are currently troubleshooting this w/ Gateway Ops. 

[HERE](https://dsva.slack.com/archives/CBU0KDSB1/p1622052134068100) is a slack thread with additional discussion.

**Comment by jhouse-solvd** [comment]
@mviterna - Has there been any follow-up or resolution on this matter? Curious to know if there is any help needed from the Operations team at this time... And if not, if it would be okay to remove the "operations" label. We can always re-add a need is determined.

**Comment by jhouse-solvd** [comment]
As far as we are aware, this was resolved w/ Gateway Ops. if anything else is needed, we can re-visit this matter. 

Closing.
