### ISSUE TITLE
Update front-end testing guidelines to include accessibility testing

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2528]
We are required to have accessibility testing in our client-side apps, so this is a good place to add some bullet points about those expectations.

**Comment by anandbhagwat** [comment]
Hi @1Copenut  I can Work On this to add Bullet Points, Feel Free to assign it to me

**Comment by 1Copenut** [comment]
Hi @anandbhagwat. I'm adding you as an Assignee, much appreciated.

I took a first pass at it and merged a few adjustments yesterday ( https://github.com/department-of-veterans-affairs/va.gov-team/pull/2527 ) but still think we're thin on specifics. Please feel free to improve and adjust.
