### ISSUE TITLE
CT Redesign: Add interactions to compare page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25280]
As a developer, I need to add the remove and highlight interactions to the compare page so that the page is fully functional and ready for usability testing.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. On the comparison page, the user has the ability to:
    a. Highlight differences between institutions
    b. Remove an institution from the Compare page.

2. When the user enables the highlight differences functionality the following occurs when the data is not exactly the same for all institutions on the compare page:
    a. The entire data row is highlighted yellow
    b. The entire data row has a bold border
    c. The entire data row content is bold
    d. The row label has an * marker indicating there is different content

3. When the user opts to remove an institution from the compare page, they are prompted to confirm the removal:
    a. If they cancel the request, no change is made to the page
    b. If they proceed with the removal request, the institution is removed from the page and the institutions are moved left (if necessary) so that the blank column is on the right.

## Supporting Artifacts:
1. [Prototype - Highlight differences](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060326_CT_Redesign_PI10_Desktop_ComparePg_OnScroll_Highlight_Differences)

2. [Prototype - Remove institution](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060324_CT_Redesign_PI10_Desktop_ComparePg_RemoveInstitution)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17581

**Comment by delli-gatti-michael** [comment]
Changes are on Staging. Closing this issue

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/cases/view/5351)
