### ISSUE TITLE
CT Redesign: Institutions farther away than the designated distance limit are showing in search results

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#25283]
When searching by location in the new comparison tool, the user has the option to confine their search results to institutions within a specified distance of their search location. Currently, results are showing that are further away than the selected distance limit.

### Steps to reproduce
1. Access the redesigned comparison tool at https://staging.va.gov/gi-bill-comparison-tool-sandbox
2. Select "Search by location"
3. Type "charleston, sc" into the search bar
4. Select "within 75 miles" from the distance drop-down
5. Click Search
6. Scroll to the bottom of the search results

### Expected results
1. No institutions are present that are greater than 75 miles away from Charleston, SC.

### Actual results
1. Search results are present that are greater than 75 miles away from Charleston, SC.

### Screenshot
![Screen Shot 2021-05-26 at 12 18 31 PM](https://user-images.githubusercontent.com/45575003/119696908-a8305180-be1d-11eb-9e76-5a6da1acc988.png)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/827

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
This fix is on staging. Closing this issue.
