### ISSUE TITLE
Draft and publish policies around using Scroll Viewport (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25287]
# User story

As a Platform team member, I need to know how to navigate Scroll Viewport and self-publish, so that I can contribute to it (the Platform Website) without prematurely exposing others' content.

# Tasks

- [ ] Some sort of call out from within the guidelines, to share the info to contributors before they start tweaking the Platform website.

# Acceptance criteria
- To come.

# Reference info
- [Publishing workflow](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579803/Publishing%2Bworkflow)

**Comment by vbellissimo** [comment]
Cancelling/old task.
