### ISSUE TITLE
MCP Design - Veteran Copay Location 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#25291]
### Userstory
As a veteran I would like to see different contact numbers for my medical copay done at different locations, so I can contact the right person to resolve my copay. 

### Acceptance Criteria
- [ ] Veteran can enter zip code or city for their treatments relocation while they are searching for copay resolution. 
- [ ] Make ticket for front end after mockup is created

**Comment by rebeccawalsh** [comment]
@LindaLi123 I'm reviewing this now, but I need clarification:

Where is this "Veterans enter zip code" thing proposed to happen? Is this in regards to the wizard terminus (shown below)? 
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/f718cccc-3fd8-4216-a0e3-763e37bed686)

IF SO:
We're already adapting the wizard pattern past its intended use by linking to one wizard from multiple products (Debt Portal and soon MCP.) Adding in a form inside of our wizard spit out a phone number is not a reasonable pattern and I highly doubt VSP will sign off on it.
 
Once the Medical Copayment Tool and its accompanying FSR is available, this will no longer be an issue, as we will be able to match their bills to the correct facilities and CPACs by default.

**Comment by LindaLi123** [comment]
Will include this in medical copay portal tool.
