### ISSUE TITLE
MVP “critical launch criteria” for onboarding expectation-setting

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#253]
# User Story
As a VFS Team I need to know what critical things to plan for up front, so that I can prioritize that work throughout my discovery/build/launch/learn and avoid getting bottlenecked/paused/no-go'd as I get close to launch.

# Goal
Clarify our expectations for what launch criteria are / should be, so that we can later build help into our support process and documentation to help teams meet those criteria throughout their discover/build/launch/learn work.

# AC
- [ ] Criteria are written up
- [ ] Criteria are discussed w/DSVA

**Comment by rroueche** [comment]
Current format is a "checklist" but that's just for the purposes of clarifying the important 'requirements' to help ensure VFS team product launch success. Next steps will involve figuring out how to incorporate these ideas into workflows so that they doesn't get used like a pre-launch checklist being looked through just prior to launch. Then we can start talking about these things in onboarding kickoffs as well, so VFS teams have these expectations from the beginning.

Current checklist: https://docs.google.com/document/d/1j85vLAVcZFUGKJubbew2CeOC8I_bIntLQygUneJ6DgI/edit#

**Comment by gunsch** [comment]
Additional reference (in Markdown):

https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Launch%20Process/overview.md

**Comment by rroueche** [comment]
this is a duplicate of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/124
