### ISSUE TITLE
Real-time messaging & communication in VAOSR

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2530]
# Stakeholder input: 
## High Level User Story / Problem / Opportunity
As a Veteran who uses VAOSR for scheduling, I want to be able to communicate directly with my provider about my appointments in VAOSR. I also want to be able to get real-time information about my appointments (such as reminders) inside of VAOSR. 

## Goals / Outcomes
*Need to understand goals/outcomes for this*

##  Options for addressing:
- I want to be reminded of my upcoming appointments at a frequency and via a method that I determine (e.g. one week before via SMS).
- Getting better notifications about requests and appointments. Specifically, as the request turns to an appointment, and also in app notifications. 
- HMW enable Veterans to connect their appts to notifications, calendar, completing clipbards, phone, ets.
- I don't like chat but I want to talk to a person about my specific appointment I'm trying to make. HMW enable phone-facilitated use of VAOS that does not require me to describe my screen to a contact center rep?

---

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

## Issues to create within this Epic

```
- If discovery needed, create Discovery/Research Epic
- If no discovery needed, break epic into corresponding stories and tasks
```

## How to configure this issue
- [x] **Labeled with `roadmapOCC` and `VAMF` and `vaos`**
- [x] **Add Epic to VAOS-R Roadmap Project in Github - must do this in GH, not Zenhub**

**Comment by ldelacosta** [comment]
We will create a new epic for secure message in VAOS.
