### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#25306]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

Chris Dyer
chris.dyer@adhocteam.us

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
ASAP
## Product Team / External Team / VA Office
VSA Caregiver
*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Chris has been added to DOMO.  Closing.

**Comment by ala-yna** [comment]
@bsmartin-ep any chance we could add him to GA as well?

**Comment by bsmartin-ep** [comment]
Done @ala-yna.
