### ISSUE TITLE
Handle MOBILE_ANY appointments without facility id

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25300]
MOBILE_ANY appointments in staging lack a facility id, which causes some minor issues in the display of those appointments.

1. The wording on the blue cancel box on the details page references "this facility" but includes no facility information
2. The wording in the cancel modal on the current list page for this appointments says "below facility" even when there is no facility.
3. There's no timezone listed on the appointment (details page and list page, both refresh and non-refresh). We're displaying in the current browser timezone, which is probably the best we can do here.

We should fix these issues.

How to test locally:

Log in to staging with alfred.castillo@id.me and find an upcoming video at home appointment. Copy that appointment data from the network tab into our confirmed_va.json mock so that it's viewable locally.

--

## Acceptance Criteria

- [ ] CONTENT - Copy should be:

> Need to change this appointment?
> To reschedule or cancel this appointment, contact the VA facility where you scheduled it.

**Comment by jbalboni** [comment]
![Screen Shot 2021-05-26 at 3.00.47 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/39c1fdd7-6ba4-499d-bc0e-fc42541b6cc6)
![Screen Shot 2021-05-26 at 3.00.16 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/2b40d8e9-65ee-48eb-a4ca-247450221ba0)
![Screen Shot 2021-05-26 at 3.00.12 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/c3cd071f-3148-4de2-b60b-1f2847bb16a9)

**Comment by outerpress** [comment]
@peggygannon a couple of notes for your recommendations:
- The home page refresh will look like the first screenshot in Jeff's comment. The blue informational box will replace the cancel appointment button and the modal it triggers.
- The language we're looking at is in that blue box. We will not be able to show any facility info for this type of appointment.
- My first pass at the language:
     
*Need to make changes?*
Contact the VA facility where you scheduled this appointment if you need to reschedule or cancel it.

**Comment by outerpress** [comment]
@jbalboni looking at the [appt card documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md#video), is there a different version of this appointment type that shows an add'l info dropdown with the label `Prepare for video visit`? Or did we drop that at some point?

**Comment by jbalboni** [comment]
@outerpress Yeah, some video at home appointments have that dropdown, if you specified in VCM to include instructions, I think. However MOBILE_ANY appointments will never have those instructions, as far as I know.

**Comment by peggygannon** [comment]
Hi, @outerpress Here's my recommendation. Let me know if you have any questions. 

**Need to change this appointment?**
To reschedule or cancel this appointment, contact the VA facility where you scheduled it.

**Comment by outerpress** [comment]
Looks perfect to me thanks @peggygannon !

**Comment by laurenernest** [comment]
Moving to dev
