### ISSUE TITLE
Phase 2: Move content-build Cypress E2E to GHA

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25308]
# Description
The `content-build` repository does not currently have a GitHub Actions workflow that executes its minimal set of Nightwatch and Cypress test specs. We need to create a workflow or add to the existing `Continuous Integration` workflow so that the Nightwatch and Cypress E2E test specs are executed as part of the `content-build` build process conducted in GitHub Actions.

## Acceptance Criteria
- [x] The `content-build` GitHub Actions build executes Cypress E2E tests
- [x] Nightwatch and Cypress tests are executed in parallel
- [x] E2E results are reported in aggregate

**Comment by ddzz** [comment]
WIP branch: https://github.com/department-of-veterans-affairs/content-build/compare/migrate-cypress-to-gha?expand=1

**Comment by ddzz** [comment]
PR opened: https://github.com/department-of-veterans-affairs/content-build/pull/262

**Comment by pjhill** [comment]
Acceptance Criteria have been satisfied
