### ISSUE TITLE
Document feature flag usage with React hooks

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25301]
## Background

Description of issue and resolution along with follow-up action items can be found here:

- Postmortem: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-05-26-broken-links-across-website.md
- Slack thread:  https://dsva.slack.com/archives/CBU0KDSB1/p1621974644462200

## Description

In [Adding a new feature toggle (frontend)](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#a-idadd-featureadding-a-new-feature-toggle-frontenda) add note about how to guard or handle React hooks when using feature toggles.

(that section seems to focus on template rendering, but doesn't take into account side effects / other hooks associated with a feature)

reference: https://dsva.slack.com/archives/CBU0KDSB1/p1622039564026800?thread_ts=1621974644.462200&cid=CBU0KDSB1

## Acceptance Criteria

- [ ] Update [feature flag](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles) documentation with guidance for React hook usage

**Comment by mchelen-gov** [comment]
note: may also be helpful to mention that feature flag API returns multiple casings for each flag
https://dsva.slack.com/archives/CBU0KDSB1/p1622577746390700
https://dsva.slack.com/archives/CBU0KDSB1/p1622578565395200?thread_ts=1622577746.390700&cid=CBU0KDSB1
> There was an issue with ie11 and url character length, so we decided to return all toggles to avoid url params all together. As for styling though, I’d check with front end.  There was no uniformity so that’s why both formats are returned

**Comment by SKasimow** [comment]
@mchelen-gov Hi Mike - has the document been updated? Wanted to see if I can close this ticket? Thanks!
