### ISSUE TITLE
Phase 2: Implement Cypress Parallelization in GHA

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25310]
# Description
Currently, the GHA `E2E Tests` workflow does not execute Cypress test specs in parallel. We need to borrow whatever configuration we can from the Jenkins parallel Cypress execution effort and recreate that solution in GitHub Actions. This will likely have implications for the demand on self-hosted runners. Each self-hosted runner apparently only has one thread to work with, so in order to gain a performance advantage by running in parallel, the parallel test runners will need to operate on distinct self-hosted runners.

## Acceptance Criteria
- [ ] Cypress E2E tests do not take more than 10 minutes to complete
- [ ] Results from all E2E tests can be viewed in a single location. (VFS teams should not have to dig through results from 6 or more individual runners to try to find the test spec that they own that is failing.)

**Comment by ddzz** [comment]
WIP branch for Cypress test parallelization on GitHub Actions: https://github.com/department-of-veterans-affairs/vets-website/compare/parallelize-cypress-gha?expand=1

**Comment by ddzz** [comment]
PR opened: https://github.com/department-of-veterans-affairs/vets-website/pull/17515

**Comment by pjhill** [comment]
This was merged and is working as expected.
