### ISSUE TITLE
Build `/requests/{requestId}/messages` GET endpoint

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2531]
As a backend developer, I want a vets-api endpoint that will pull messages sent to the scheduler so that the front end can show the message that was sent to the scheduler in an appointment request's details.

AC:
- [ ] Mock data from staging vaos services recorded to cassette
- [ ] `/requests/{requestId}/messages` endpoint supports `GET` method with staging data
- [ ] Tests, specs, and Swagger exist in vets-api

**Comment by narin** [comment]
@saneshark I believe this is done right? If so we can close this out.

**Comment by markgreenburg** [comment]
Confirmed working in staging.
