### ISSUE TITLE
Phase 2: Improve Cypress Test Artifact Collection

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25312]
# Description
In order to provide a better experience for VFS teams that are using the GitHub Actions to troubleshoot their E2E test failures, we need to provide easy access to relevant artifacts.

## Tasks
- [x] Modify Cypress configuration to save videos only on test failure on GitHub Actions.

## Acceptance Criteria
- [x] Videos of passing Cypress tests are not saved as artifacts on GitHub Actions

**Comment by ddzz** [comment]
By default, Cypress generates videos of all tests runs. This PR modifies the Cypress config to save videos only for failing tests in order to reduce the amount of unneeded artifacts: https://github.com/department-of-veterans-affairs/vets-website/pull/17424

**Comment by pjhill** [comment]
PR Merged this is complete and functioning normally for ~1 week.
