### ISSUE TITLE
Message detail displays loading spinner after it's loaded

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25329]
## What happened?
On the message detail/thread page, certain messages display a loading spinner even after the message content has (seemingly) already loaded. 

## Specs:
- Device: iPhone 11
- User: +41

## Steps to Reproduce
1. Log in with +41
2. From the Inbox page, select the following message:
     - Ecker, Jennifer M
     - Medication: Side effects
     - 26 May 2021 @ 1259 PDT
3. When the message detail page loads, notice that the most recent message is expanded/loaded (as expected)
4. Select the oldest message in the thread add expand the accordion
     - Notice how the older message loads, but then the most recent message at the bottom of the page (which should already be loaded) displays a loading spinner

## Desired behavior
1. Message detail should not display a loading spinner if it's already loaded

## Acceptance Criteria
See desired behavior. 

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
https://images.zenhubusercontent.com/133843125/2dbc1c10-5742-4d2e-be6b-fd7a2fd21e7f/image_from_ios.mov

**Comment by digitalken** [comment]
PASS 6/17/2021 - Only get the loading spinner on the message that is opening. No spinner on the most recent message.  Closing.
