### ISSUE TITLE
Form system - upload document error message

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#25320]
As a Veteran or Caregiver,
I would like to know what I need to do when I encounter an error while uploading a document while completing the [10-10CG](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction).

## Current situation
Currently when uploading a document within the form system, when users encounter an error  they receive an error message + Delete button (see documented errors below). The problem is that it is not clear what next steps should be taken. For example: _"The file is too large, **please delete the file** and upload a file that is no larger than 10MB"_

This is in alignment with the [Style and Tone Guide](https://design.va.gov/patterns/messaging-error-messages#content-within-the-message-description)
_"If the resolution fails, what’s the next step?
The answer will inform whether or not to include a “next-step call to action” to help guide the user further should the first call to action fail to resolve the issue."_

### Documented error states
1. Internet connection error![network fail.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/4d03c108-7658-4a8d-a0f8-53006df98ffd)

2. File too large error
 ![file too large.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/fb418372-c3b0-49dc-be50-ff59918c3371)

3. Wrong file type
![image.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/567a3de2-a70c-48bf-a5af-d3dabc060bbe)

## Expected Behavior

Form system is updated with error messaging that provides user with clear next steps

## Acceptance Criteria

- [ ] Each upload document error state within the form system is updated with content that gives users appropriate guidance for next steps.
- [ ] Frontend component is updated

**Comment by ala-yna** [comment]
Hi @caw310  - we have a ticket for the design system to update the messaging in the upload component. Please take a look, and let me know if this is something your team would take on, or if it's something we should do. Thank you!

**Comment by caw310** [comment]
@ala-yna , It would be great if your team could take on this work. We are down one person with Crystabel leaving so booked up. Of course, if you have questions, we are here. Thanks!

**Comment by Dene-human** [comment]
@caw310 If we take on this work, would we approach it as something that would be implemented sitewide in the form component or would this be a specific solution for the 10-10CG?

CC: @mlighdc

**Comment by cvalarida** [comment]
Because it's not form-specific, I'd say it should be in the forms library so all forms across VA.gov benefit from the improvement.

**Comment by dat-gcio** [comment]
@cvalarida Are there any approval process we need to go through to get the go ahead to implement after we have some designs?

**Comment by Dene-human** [comment]
Hi @caw310 and @cvalarida We worked with Danielle to change the copy (see below). Are we good to move forward with implementation? 

### Internet connection error
**OLD:**  Network request failed
**New:** We're sorry. We had a connection problem. Please delete the file and try again.

### File too large error
**OLD:**  File is too large to be uploaded
**New:** We couldn't upload your file because it's too big. Please delete this file. Then upload a file that's 10MB or less.

### Wrong file type error
**OLD:**  File is not one of the allowed types
**New:** We couldn't upload your file because we can't accept this type of file. Please delete the file. Then try again with a .pdf, .jpeg, .jpg, or .png file.

**Comment by dat-gcio** [comment]
To add onto what Dene has said, the file size is dymanic.

`We couldn't upload your file because it's too big. Please delete this file. Then upload a file that's {limtSize}MB or less.`
