### ISSUE TITLE
Remove unpublished Vet Center check

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25328]
## Issue Description
During Vet Center pilot phase, we added logic to check to see if a Vet Center location added as a "Nearby" location is published to determine data source (CMS or Lighthouse). This logic was necessary so that unpublished content within CMS would not be displayed on the front end. 

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/24312 for details.

Once Vet Center pages are rolled out nationally, all locations will be published and this duplicate code will not longer be needed. 

---
## Tasks
- [ ] Prune out "published" check for Nearby Vet Centers

## Acceptance Criteria
- [ ] Cleaner code base, no unnecessary logic
---

**Comment by mpelzsherman** [comment]
> we added logic to check to see if a Vet Center location added as a "Nearby" location is published to determine data source (CMS or Lighthouse)

I don't see any such code to remove. I think we can close this.

**Comment by mmiddaugh** [comment]
Added to #37529 so this can be closed
