### ISSUE TITLE
Post-Mortem Action Items | Feature Flag Language Switcher | Analytics

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25340]
## Feature Flag Issue:

Description of issue and resolution along with follow-up action items can be found here:

- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/281/files

## Action Items Resulting from Post-Mortem

- [x] Review analytics for non-working links in the two hours that these links were broken in production.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/25327
- Slack thread: (https://dsva.slack.com/archives/CBU0KDSB1/p162197464446220

**Comment by bsmartin-ep** [comment]
@SKasimow -

Here is the Event we fire when someone clicks that button (2021-05-16 to 2021-05-27):

> [LINK](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210516&_u.date01=20210527&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:nav-header-link,analytics.eventAction:Navigation%20-%20Header%20-%20Find%20a%20VA%20Location%20-%20https:~2F~2Fwww.va.gov~2Ffind-locations)

Oddly enough - it peaks on 2021-05-25.

By hour on that day:

> [LINK](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210525&_u.date01=20210525&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.hour&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:nav-header-link,analytics.eventAction:Navigation%20-%20Header%20-%20Find%20a%20VA%20Location%20-%20https:~2F~2Fwww.va.gov~2Ffind-locations&explorer-table-dataTable.sortColumnName=analytics.hour&explorer-table-dataTable.sortDescending=false)

We fire these on link click - not when the Find Locations page loads - so it's likely we wouldn't see a drop from this issue.

Though I'm also not seeing much of a drop in pageviews compared to the previous Tuesday....

> [LINK](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210525&_u.date01=20210525&_u.date10=20210518&_u.date11=20210518&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Ffind-locations~2F)
