### ISSUE TITLE
Change upper case letter on button to lower case

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#25347]
The first page after [Introduction](https://www.va.gov/health-care/apply/application/introduction) for unauthenticated 10-10EZ.

Button should only have uppercase for first letter, correct text is: **Continue to the application** 

![Button text.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/945451b4-d7e8-404c-ac7f-f72d893a4433)

**Comment by dat-gcio** [comment]
@Dene-human Here is the [review instance](http://30752fc89e82c7e71716b5dd00830000.review.vetsgov-internal/health-care/apply/application/id-form)

**Comment by Dene-human** [comment]
Perfect!

**Comment by dat-gcio** [comment]
Validated in prod.
