### ISSUE TITLE
[Content] - Review copy for contact information updated email template

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#25344]
## Background
One of the things that fraudsters do before they hack people's direct deposit information is change a user's contact information. They do this so that any correspondence re: direct deposit then goes to the fraudster, and then the user doesn't know their information has been compromised until it's too late.

We can't stop fraudsters, but we can confirm with veterans that their contact info has been updated so that if they, the veteran, weren't the one making the update, they can get in touch with the VA and have their account locked right away.

## Use cases
- user updates, adds, or removes contact information in one section of profile
- user updates, adds, or removes contact information in multiple sections of profile

## Copy to be reviewed

Subject: Confirmation - Your contact information has been updated on VA.gov

Your contact information information changed.

We're sending this email to confirm that you updated the following contact information in your VA.gov account profile:
- [bulleted list of contact info that changed]
- [bulleted list of contact info that changed]

If you didn't make this update, please call us right away.

Call 800-827-1000 (TTY: 800-829-4833). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. We can help you take the steps you need to protect your bank account information and prevent fraud.

[Go to your VA.gov profile](https://www.va.gov/profile?utm_source=gov-delivery&utm_medium=email&utm_campaign=contact-information-update)

—
You’re getting this email because you made a change to your information on VA.gov.

Please don’t reply to this email. If you need to contact us, go to https://www.va.gov.

### Note

We're planning on including multiple updates in one email to prevent the user from getting too many VA emails based on actions that took place in one session. If that's not technically feasible for some reason, we will put the updated contact info in the sentence like so:

>We're sending this email to confirm that you updated your [contact information] in your VA.gov account profile:

**Comment by DanielleThierryUSDSVA** [comment]
cc @peggygannon @shiragoodman

**Comment by andaleliz** [comment]
Oh, should this be a VSP content review? That would make sense since this is not on the website! 🤦

**Comment by shiragoodman** [comment]
thanks @DanielleThierryUSDSVA. @andaleliz Platform no longer supports content reviews outside of the Collaboration Cycle, so you were right to open a ticket with Sitewide Content. Just curious, is this request in support of work that is going through Collab Cycle?

**Comment by andaleliz** [comment]
@shiragoodman it isn't, this is [an enhancement that's been in our backlog](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8383) for over a year.

**Comment by shiragoodman** [comment]
sounds good - thanks! I'll see myself out

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz! Let me know if you have any questions on this.
 
[subject]

Your VA.gov profile information has changed

[email]

Your VA.gov profile information has changed. We’re sending this email to confirm that you updated this information:

- Change 1
- Change 2

If you made this update, you don’t need to take any action.

**Don’t remember updating this information?**

This could mean that someone is trying to access your account.

Call us right away at <a href="tel:+18008271000" aria-label="8 0 0. 8 2 7. 1 0 0 0.">800-827-1000</a>. We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. If you have hearing loss, call <a href="tel:711" aria-label="TTY. 7 1 1.">TTY: 711</a>. We can help you protect your bank account information and prevent fraud.

[Go to your VA.gov profile](https://www.va.gov/profile?utm_source=gov-delivery&utm_medium=email&utm_campaign=contact-information-update)

**Comment by andaleliz** [comment]
Thanks @DanielleThierryUSDSVA this is great! Much better :) No questions from me.

**Comment by DanielleThierryUSDSVA** [comment]
Great question, @andaleliz. Yes, I think a more general "account" is good here. Thanks!

**Comment by andaleliz** [comment]
Sounds good, thank you @DanielleThierryUSDSVA
