### ISSUE TITLE
Discovery on understanding on the PDF XFA detector works 

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#25343]
## Issue Description
Going to look over the XFA detection script created by Lighthouse.
See if I can get it to work locally or what that entails. 

## Acceptance Criteria
- [x] Give report on findings.

**Comment by zacharymorel** [comment]
HERE is link to forms report => https://dsva.slack.com/archives/C01DWJFD45D/p1622141708154600?thread_ts=1622057252.127400&cid=C01DWJFD45D

**Comment by MarciMcGuireGCIO** [comment]
Thank you 🙏

**Comment by zacharymorel** [comment]
Closing this out after a decent discovery.
