### ISSUE TITLE
VAMC "Get updates" box is missing social links

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25357]
## What happened?
The "Get updates" box at the bottom of the VAMC page is missing social links: 
<details>
<summary> Current behavior </summary>

![image](https://user-images.githubusercontent.com/55411834/119869596-a62dc780-bedd-11eb-9639-0370e8733ef6.png)

</details>

<details>
<summary> Expected behavior </summary>

![image](https://user-images.githubusercontent.com/55411834/119869566-9d3cf600-bedd-11eb-812c-32ee810f5af9.png)

</details>

## Steps to Reproduce
1. Visit URL - such as - [Pittsburgh VA Medical Center-University Drive](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
2. Scroll to the bottom of the page to the "Get updates box"

## Desired behavior
- [ ] Get updates box contains links available in CMS
- [ ] Can be up to 4 social media links (including Instagram)
- [ ] All VAMCs are expected to have at least Facebook
- [ ] Test should look for Facebook link

**Comment by mpelzsherman** [comment]
Please re-test when the commit has been release to production, thanks! 😄

**Comment by mmiddaugh** [comment]
Viewed in Prod - looks great!
![image](https://user-images.githubusercontent.com/55411834/121751780-0f136300-cacc-11eb-90af-6e76b926054e.png)
