### ISSUE TITLE
[Content review] Modality nomenclature alignment

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25356]
## Description
For homepage refresh, we are going to surface the user-selected modality preference on the appointment request detail page.

On both the new appointment form and request detail pages:

1. How should we refer to in-person/office requests? (These are the standard VA appointments at a clinic)
2. How should we refer to the phone requests? (These are when the VA calls a Veteran)
3. How should we refer to telehealth requests? (These would include any of the different types of VVC appointments)

![modality naming.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/df2e6a13-117e-4249-be58-55c1bd1e7928)

**Comment by outerpress** [comment]
@peggygannon notes from our sync yesterday in this section on the detail page, we'll display the same text that's in the option they selected. Here's a mock just for visual reference:

![va-request_PENDING.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/c15aabe5-a692-47c0-841e-2e510bce8712)

**Comment by peggygannon** [comment]
Hi, @outerpress Ok, thanks for sharing the updated mockup! Thank you also for matching the display screen with the appointment option they selected.

**Comment by laurenernest** [comment]
Thanks! Moving to dev #25835
