### ISSUE TITLE
[Content review] - Test User Dashboard

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#25352]
## What do you need content guidance and support for?

- [x] Content strategy and writing for the VSP Test User Dashboard web application
-	[x] Writing/editing to update existing documentation
-	[x] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

The VSP Identity team is requesting a content audit on the Test User Dashboard tool (https://tud.vfs.va.gov).  Ideally, we would like a content review of the entire site which is about 4 pages.

## When does this content work need to be done?

I do not anticipate this being a high priority as this tool is non-Veteran facing and the content is relatively small.  The Test User Dashboard web application tool is already launched (behind the SOCKS proxy) but ideally within 2-3 sprints or end of June.

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VSP Identity
-	OCTO-DE product owner: 
-	Product manager: @christine-dillman 
-	Designer: @APorter-Clarity 
-	FE engineer: @AGarcia-Clarity 
-	Product/team Slack channel: #vsp-identity

## Links to related tickets

*Please include here a link to the epic, or other relevant tickets, for this product work.*

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
@AGarcia-Clarity Can I ask what the Test User Dashboard is? Is it Veteran-facing? The link isn't working for me both on my desktop and on the network. Could you give me a little more info? If it's easier to hop on a call that works too. Thanks!

**Comment by AGarcia-Clarity** [comment]
Hello @RLHecht,

The Test User Dashboard (TUD) is a standalone application to find and manage test accounts for https://staging.va.gov.  It is mostly used as an internal tool for VSP developers, content editors, accessibility experts to ensure proper quality assurance, feature development, and accessibility on VA.gov.  The website is not a Veteran facing application however the SOCKS proxy is required to view it.

The Github repo is located at https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard in case need to see just the content.  I am available to sync anytime you have bandwidth 👍

**Comment by AGarcia-Clarity** [comment]
@RLHecht, do you want me to close this ticket and open a new one with the Content/IA team?

**Comment by RLHecht** [comment]
Yep, we can close this out. Thanks, @AGarcia-Clarity
