### ISSUE TITLE
Create initial E2E test for VA.gov header

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#25362]
## Description
Changes within codebase can have unintended effects on header functionality that would be helpful to catch with E2E automated testing.

#### Acceptance Criteria
- [x] VA.gov header has initial Cypress E2E test

**Comment by kelsonic** [comment]
PR is up for mega menu e2e tests: https://github.com/department-of-veterans-affairs/vets-website/pull/17582

**Comment by kelsonic** [comment]
PR merged

**Comment by brianalloyd** [comment]
This works should be complete @mchelen can you validate VA.gov header has initial Cypress E2E test and close in support.  Thanks.

**Comment by brianalloyd** [comment]
Think this work has been completed, going to close out the ticket but can reopen if need arrises.
