### ISSUE TITLE
Remove "go back" button on detail pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25363]
## Description
On the appointment detail pages, we currently have 2 methods of navigation back to the homepage. We would like to use only the top breadcrumb for navigation.

![staging_va_gov_health-care_schedule-view-va-appointments_appointments_va_202106041545983000070700000000000000__1_.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/e8755831-dea7-4c7b-9871-4fbc3b622cda)

## Acceptance Criteria

- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag

- [ ] If any detail page, Then do not show "Go back to appointments" button

---
**Original description**

On the homepage refresh pages, when you

1. open the appointment list
2. Choose an appointment and open the details page
3. Go back to the appointment list page

You do not return to the same scroll position you were at before, or have the same list item focused. We should explore ways of handling this.

Chrome and other browsers have some automatic handling of this, which we disable on the form pages, and may be disabled on the list pages, too. React Router may also have some scroll handling built into it.

**Comment by laurenernest** [comment]
Updated the ticket. We're going to remove the button completely instead.
