### ISSUE TITLE
[Research] Notification Preferences: Conduct research/usability testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25367]
## Background
We need to validate our designs for the notification preferences feature via usability testing. 

## Tasks
- [x] conduct research sessions
- [x] debrief team on progress and findings

**Comment by andaleliz** [comment]
Final session completed today! Research folder here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research
