### ISSUE TITLE
NOD: Design to Development QA

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#25365]
## Issue Description
A final sweep to ensure that all design changes are properly reflected in staging.

#### Link to the design: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562

---
### Intro page 

- [ ] Action links need to be on this page (marking as done already since action links are on hold)
- [x] remove period in "Follow these steps to request a Board Appeal."
- [x] In the "what happens after you apply" add'l info dropdown, can you add this url (https://va.gov/decision-reviews/board-appeal/#what-are-my-board-appeal-optio) for the link titled "Read more about the 3 Board Appeal options."
- [x] Remove the "more" in that sentence, since we're assuming they've read nothing about the board appeal options
- [x] Put a space at the start of the sentence "Read more about the 3 Board Appeal options" 
- [x] Remove the period at the end of the link sentence "Read more about the 3 Board Appeal options"
- [x] Remove the last sentence in the 'start your request' step that says "Complete this Board Appeal application form. After you submit the application, you’ll get a confirmation message. You can print this for your records."

### Issues for review: system issues
- [x] There's more to the first paragraph. Add another sentence that says "If an issue is missing from this list, you can add it on the next step."

### Issues for review: Add issues
- [ ] Remove the sentence "Please add a new issue for review:"
  
### Opt-in
- [x] TYPO ALERT! 🚨 in the sentence "Our decision reveiw process is part of the Appeals Modernization Act. When you opt in, you’re likely to get a faster decision." you need to spell "review" correctly

### Board review option

- [x] "Direct review" needs to be "Request a direct review"
- [x] "Submit additional evidence" should be "Submit more evidence"
- [x] "Hearing with a Veteran's Law Judge" should be "Request a hearing"

### Additional Evidence: Would you like to add? Yes / No Page

- [x] The add'l info dropdown - last sentence that says "You can also send it by fax to 844-678-8979" should read "You can also fax it to 844-678-8979"

### Review page

- [x] Add "question" after both the homelessness and representative headings/section titles

### Submit page

- [x] "After you request an appeal" should be "After you request a decision review" since it IS a type of decision review
- [x] "Learn more about what happens after you request an appeal" link should be "Learn more about what happens after you request a review"
- [x] In the "what should I do while I wait?" Change the sentence that says "You don’t need to do anything unless VA sends you a letter asking for more information. If VA schedules any exams for you, be sure not to miss them." to use "we". Like this: "You don’t need to do anything unless we send you a letter asking for more information. If we schedule any exams for you, be sure not to miss them."
- [x] change this sentence: "If you requested an appeal and haven’t heard back from VA yet, please don’t request another appeal. Call VA at 800-827-1000." to this: "If you requested an appeal and haven’t heard back from us yet, please don’t request another review. Call us at 800-827-1000."

![counting-on-you.gif](https://images.zenhubusercontent.com/5d65638e0845ad5f24bada4a/e2343823-73b6-4c9d-a76f-fdf188bf8660)

## Acceptance Criteria
- [x] All changes listed here have been completed on staging
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
> * Action links need to be on this page

Platform will be making this change

> * Remove the sentence "Please add a new issue for review:"

That is the _only_ content I could think to add to the `<legend>` that wraps the name & date. So we need something in there. When a second card is added, the legend text is changed to "Update issue"

> * Add "question" after both the homelessness and representative headings/section titles

The design shows "Homeless question" which doesn't sound as nice as "Homelessness question"?

**Comment by kevinstachura** [comment]
>The design shows "Homeless question" which doesn't sound as nice as "Homelessness question"?

@Mottie do "Homelessness question", please! Thanks.

**Comment by Mottie** [comment]
Already done! 😸

**Comment by kevinstachura** [comment]
@Mottie Yesssssssss

**Comment by kevinstachura** [comment]
All changes have been successfully made by our wonderful FE team. 🤘
