### ISSUE TITLE
Reduce noise in GHA linting 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25378]
## Details 

On 5/26 FE Tools team replaced CircleCI with GHA. We have since gotten some feedback from VFS developers on the linting output. 

Slack links & convos pasted in comments below

## Definition of Done 

- [x] Iterate on linting output in GHA to address VFS developer feedback

**Comment by meganhkelley** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1622122786152200

Robin Garrison:no_entry: Yesterday at 9:39 AM
:heart: the use of GitHub actions! But why show me lint errors in unrelated files in a PR I open?
8 replies

Robin Garrison:no_entry:  1 day ago
Screen Shot 2021-05-27 at 8.38.54 AM.png 
Screen Shot 2021-05-27 at 8.38.54 AM.png



Jhonny Gonzalez  1 day ago
cc @eugene_doan @Oseas Moran

Robin Garrison:no_entry:  1 day ago
PR for reference: https://github.com/department-of-veterans-affairs/vets-website/pull/17385/files#diff-0c0cf08b49329ef2cfb739fcec986b81d585711fd2c06eb5a4a9c3a6e1a8dde7

Oseas Moran  1 day ago
The linting is done across vets-website not just on individual files, so when the "report" is generated, it displays files not in the commit either (edited) 

Robin Garrison:no_entry:  1 day ago
I'm just saying it's a lot of extra noise :disappointed:

Oseas Moran  1 day ago
I am hopeful that the code-owners for those files will clean up the lints. I will also notify FE tools team and bring this feedback up

Eric Boehs:camping:  1 day ago
I've ran into this issue on other projects. I solved it by fixing all lint issues, then failing the build if there were any linting issues. Then the displayed annotation will only be relevant to change code.
Other solutions if fixing all is unfeasible:
ignoring existing issues with a todo plugin
Only checking files changed
Disabling the annotations
I think the unrelated noise is annoying and code owners won't fix it timely.  (edited) 

Oseas Moran  1 day ago
Thanks for the info Eric! It does not seem like too many files, so I am going to try to get around fixing the linting issues myself sometime hopefully today

**Comment by meganhkelley** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1622145665249000

Mark Dewey Yesterday at 4:01 PM
Hey Platform! I have question about the new GHA(?). I was approving a PR and I noticed there is section on the files called Unchanged files with check annotations . I really like the extra checks and I have a few questions about them.
Can we scope them to any more? I like them, but’s extra noise when it includes other directories/files
How can we run the checks that its running them locally and/or see what all its checking for? There looks to be some helpful suggestions (Cognitive Complexity for one) That I would like to have running against all the code make
I am not sure if this is GHA or not, but I overall I like it :slightly_smiling_face:

**Comment by oseasmoran73** [comment]
Exploring what are options, these were the ones we discovered:
- We can manually fix them ourselves
  - One way is based off team/organization. FE Tools can get PR started and teams can continue off of that -- did not seem too feasible and disruptive
- Discover how to only view files committed
  - We can compare base_ref to head_ref (branch committed) and check lint that
  - initial commit sometimes flaky (test continue-on-error feature)
  - Investigated difference between base_ref/head_ref in a pull_request vs push
    - push only got difference on last commit and previous information was "lost" (file needed to be modified and recommitted -- hassle)
  - WIP: [eslint enhanced for files committed only](https://github.com/department-of-veterans-affairs/vets-website/pull/17458/files)


Pending discoveries:
- If lint moved from push to pull_request, how will that look on daily deploys?
- Suppress non-valid files

**Comment by oseasmoran73** [comment]
Closing ticket as [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17458) was recently merged
