### ISSUE TITLE
Update Calendar UI Widget to Show AM/PM bubbles for Appointment Request

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#2537]
## User Story
As a veteran, I need visual indications of my selections so I can have confidence in my appointment preferences.

Mockup coming soon.

## Acceptance Criteria
- [ ] Green bubbles with "AM" or "PM" inside should show on the date for each appointment/time  preference the user selects

**Comment by narin** [comment]
cc: @markgreenburg

**Comment by narin** [comment]
@rtwell We talked about this a while back. I've got this pretty much complete but could use a refresher on what you had in mind for the design.  Icons would be a tougher to do but text is pretty straightforward. I think you had proposed something similar to the screenshot below:

![image](https://user-images.githubusercontent.com/786704/70958715-ffc66d00-202e-11ea-9138-a32ac23cfb38.png)

**Comment by rtwell** [comment]
yo yo yo 

lookin' great!

here's where i landed—i'd focus on the buttons/interaction, although i would like the AM/PM blips to be our almost-black color instead of primary blue.
