### ISSUE TITLE
Missing events on VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25371]
## What happened?
Published events are not displayed on VAMC pages (reported for events in hub as well)

## Steps to Reproduce
Visit URL: https://www.va.gov/northern-california-health-care/events/
Observe - "no events at this time" is displayed
![image](https://user-images.githubusercontent.com/55411834/119906382-59f97c00-bf0b-11eb-9dc8-5c0568dcfea8.png)

---

View preview-prod.vfs.va.gov/preview?nodeID=20173
Observe events have been entered into CMS and published

![image](https://user-images.githubusercontent.com/55411834/119906419-6d0c4c00-bf0b-11eb-8c89-d5e6eec346f9.png)
![image](https://user-images.githubusercontent.com/55411834/119906475-89a88400-bf0b-11eb-85dd-17d83232bd6f.png)

By contrast, the Mental health conversation event for Montana health care is working as expected

## Desired behavior
Published upcoming events are expected to be available on event listing pages

**Comment by mpelzsherman** [comment]
I only see one published event in Northern California, and it is marked as a "placeholder": (https://prod.cms.va.gov/admin/content?title=event&type=event&moderation_state=editorial-published&owner=233)

![Content___VA_gov_CMS](https://user-images.githubusercontent.com/80267/120032969-f766b580-bfc8-11eb-994b-421b7485bc71.png)

**Comment by mpelzsherman** [comment]
One theory: we currently have a [limit](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/eventListingPage.graphql.js#L45) of 500 on the reverseFieldListingNode field in eventListingPage.graphql.js. I'm going to try expanding that limit and see if that helps.

**Comment by mpelzsherman** [comment]
Thanks @cmaeng. Should we close this ticket and open a new one for showing the last event on the home (system) page?

I do think the `limit` issue should be addressed, whether linked to this ticket or a new one.

**Comment by mpelzsherman** [comment]
@indytechcook has confirmed that these reverse field limits are for the max # of items on each “parent” node (e.g. max events on a given event listing page). If we’re OK leaving that at 500, I don’t think there’s anything else for me to do here. I'm closing this ticket.

**Comment by mmiddaugh** [comment]
This issue was resolved by [reverting a PW PR](https://github.com/department-of-veterans-affairs/content-build/pull/200) - see [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1622151870325900)
