### ISSUE TITLE
[Design] vaccine CTA to type of care

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25385]
## Prerequisites
Spike #24707

## Request

- [ ] Desktop, Tablet, and Mobile specs for homepage with single CTA
- [ ] Desktop, Tablet, and Mobile specs for vaccine option on type of care page without "new" label
- [ ] Desktop, Tablet, and Mobile specs for vaccine option on type of care page with "new" label

## Design specs

[Workflow](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/jgPbqgm)

[Home page overview](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/jgPbp2G)
    - [Mobile](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/QbxkMYe)
    - Tablet (TBD)
    - Desktop (TBD)

With "new" label
- [TOC overview](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/ELjlYLd)

Without "new" label
- TBD

COVID-19 start page
    - [Mobile](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/ELjlJmo)

**Comment by outerpress** [comment]
@peggygannon could you look at these and provide content feedback/recommendations?

For context, here's the [new proposed workflow](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/jgPbqgm)

These mocks show the proposed changes alongside the current state on staging:
- [Home page changes](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/jgPbp2G)
- [TOC page changes](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/ELjlYLd)
- [COVID-19 start page for reference](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/ELjlJmo) - I'm proposing we change the heading above the h1 to "NEW APPOINTMENT" throughout the flow to match other flows

**Comment by laurenernest** [comment]
Dev complete
