### ISSUE TITLE
Set up custom GitHub Action for Terraform automation 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#25384]
## Description
We want to set up custom GitHub Action for Terraform automation as a possible replacement for Atlantis. 

## Background/context/resources
This action would see a change to TF files within a PR, and then run a TF Plan, and then comment on the PR with the plan. 

---
## Tasks
- [x] Design it 
- [x] Test it 
- [x] Ship it 

## Definition of Done
If it's found that this can fully replace Atlantis, then...
- [x] Atlantis is decommissioned 

---
### Reminders
- [x] Please connect to an epic

**Comment by jbritt1** [comment]
Also created a small doc in confluence: https://vfs.atlassian.net/wiki/spaces/OT/pages/1553203214/Terraform+Automation+GitHub+Action

**Comment by jhouse-solvd** [comment]
This looks good. Please see https://github.com/department-of-veterans-affairs/va.gov-team/issues/25777 for considerations that have been captured WRT to this work. 

Closing.
