### ISSUE TITLE
Decide what QA content to move and where to move it to

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2538]
Columns:
Link to all QA content
Is it moving?
If it's moving, where to?

**Comment by peterhill-oddball** [comment]
Spreadsheet with links to old content, move/don't move, and new location created as [Google Sheet](https://docs.google.com/spreadsheets/d/1Lx8lbzFou-zuPv7cXsk_9swlnUTYFclbrqEfouC_h3I/edit?usp=sharing).

**Comment by peterhill-oddball** [comment]
Contacted Matt Johnson via Slack for review / approval on proposed migration locations.

**Comment by peterhill-oddball** [comment]
The materials have been manually moved to va.gov-team.  Now I need to run the scripts from -- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/scripts

**Comment by peterhill-oddball** [comment]
Need to come up with a strategy for executing the migration scripts with JP.
