### ISSUE TITLE
[Bug] Language Asst. & Rsrcs pages - Static/missing breadcrumbs

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#25395]
## What happened?
The **breadcrumbs** were static [on desktop] or missing [on mobile] -- no links back to homepage -- on Staging **[VA asistencia y recursos en Español](https://staging.va.gov/asistencia-y-recursos-en-espanol/)** and **[VA Tagalog wika mapagkukunan at tulong](https://staging.va.gov/tagalog-wika-mapagkukunan-at-tulong/)** pages.

## Specs:
- Devices: [**basically** device-agnostic]:
  - Static breadcrumbs on Desktop/Tablet [Win10 pc / MacBook Pro / Apple iPad]
  - Missing breadcrumbs on Mobile [Samsung Galaxy S9].
- Browsers: [**basically** browser-agnostic]:
  - Static breadcrumb in Win IE11, MacOS/Android Chrome
  - Missing breadcrumb iOS Safari

## Steps to Reproduce
- URLs:
  - https://staging.va.gov/asistencia-y-recursos-en-espanol/
  - https://staging.va.gov/tagalog-wika-mapagkukunan-at-tulong/
- Go to each page listed above.
- Observe that **Home** breadcrumb is not a clickable link.

### Screenshots:

**Mac Chrome** examples:
![image](https://user-images.githubusercontent.com/587583/120033524-84e9db80-bfb0-11eb-8e67-0184a13fe4c2.png)
![image](https://user-images.githubusercontent.com/587583/120033631-acd93f00-bfb0-11eb-9e5a-b9d1152a555f.png)

**Android Chrome** examples:
![image](https://user-images.githubusercontent.com/587583/120035076-ddba7380-bfb2-11eb-97c1-9f270988db38.png)
![image](https://user-images.githubusercontent.com/587583/120035456-8072f200-bfb3-11eb-8b09-d41b8aac07bc.png)

## Desired content/behavior
Breadcrumbs on these pages should be present, and clickable links back to **homepage**:
- [ ] [Desktop/Tablet] VA asistencia y recursos en Español (should be clickable link)
- [ ] [Desktop/Tablet] VA Tagalog wika mapagkukunan at tulong (should be clickable link)
- [ ] [Mobile] VA asistencia y recursos en Español (should be present & clickable link)
- [ ] [Mobile] VA Tagalog wika mapagkukunan at tulong (should be present & clickable link)

## Acceptance Criteria
[see **Desired content/behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by SKasimow** [comment]
Thanks @tlei123   I think this will be addressed upon @youngfreezyVA return Tuesday!

**Comment by youngfreezyVA** [comment]
i will dig deeper, but this likely has to do with the entity in drupal missing the appropriate nodes to render the breadcrumbs, will post findings here

**Comment by SKasimow** [comment]
@youngfreezyVA ok thanks!

**Comment by youngfreezyVA** [comment]
hi, just confirmed that this is due to the entity in drupal missing the appropriate breadcrumbs (on `entityUrl.breadcrumb`. in the screenshot below we can see in the english language support link, the appropriate breadcrumbs are there, but in the spanish / tagalog versions they aren't. i believe @DanielleThierryUSDSVA implemented a fix (in drupal) for breadcrumbs in non english content for the faq page as well, so i think we should do the same thing here, unless i'm missing something.

<img width="1910" alt="Screen Shot 2021-06-02 at 10 35 08 AM" src="https://user-images.githubusercontent.com/46791771/120527284-049bef80-c38f-11eb-9a23-4b71360ea728.png">
<img width="1910" alt="Screen Shot 2021-06-02 at 10 35 34 AM" src="https://user-images.githubusercontent.com/46791771/120527298-082f7680-c38f-11eb-8bcf-0b2f5501e04e.png">

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA - can you take a look. Fareez said same thing happened on FAQ pages and you were able to correct....

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow sure, i'll take a look!

**Comment by tlei123** [comment]
Fixes validated on Staging --  **Home** links successfully navigated to Homepage.

![image](https://user-images.githubusercontent.com/587583/120721769-5756d380-c483-11eb-82d3-ae13889d3af8.png)
![image](https://user-images.githubusercontent.com/587583/120721658-237bae00-c483-11eb-9121-09c9de4dfde1.png)

**Comment by SKasimow** [comment]
@tlei123 Thank you Tze!!

cc @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
Awesome. Thank you, @tlei123!
