### ISSUE TITLE
Discovery: Unit Test Failure Automated Reporting

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#25393]
We would like to find a way to automate reporting on unit test failures. This card is a discovery card, the result should be a path forward to implement some kind of automated reporting system.

Definition of Done
- [ ] Meet with several stakeholders to determine what exactly we would like this automated reporting to track
- [ ] Assemble an analysis of options for getting this done
- [ ] Provide a recommendation for a path forward

**Comment by k80bowman** [comment]
I started research on this card by speaking with Tim Wright about the expectations our team has for what automated unit test failure would accomplish. The main goal he identified was to find a way to automate alerting the appropriate team when a unit test fails in `master` on `vets-website` or `content-build`.

He also identified several other goals that we might look into including
* automating skipping the test in Mocha,
* automatically re-running the test suite when a unit test fails in `master`,
* and collecting and reporting metrics on tests that fail `master`.

I completed research on what was possible for accomplishing each goal, focusing on what we could do using Github Actions. I’ll go through each option below and then provide my recommendation for moving forward.

#### Notifying Codeowners of a Failed Unit Test in `master`
Currently, there are several steps the Frontend Tools team member on support needs to go through in order to identify a failing test on `master` and then notify the appropriate codeowner team.
1. Click through the Slack notification that a `master` build has failed to Jenkins (this will change to Github once we finish the transfer to Github Actions).
2. Check for any failed unit tests. If they have failed (and it’s not a mass test failure), identify which tests have failed and in which test files.
3. Identify the codeowner teams for each test file with a failing test
4. Go back to Slack and tag someone from each codeowner team in a thread on the failing `master` build notification.

It doesn’t take too long, and it gets easier as each Frontend Tools team member gets to know who the codeowners are and which set of codeowners is responsible for each section of code, but it would be nice to find a way of automating at least part of this process so that we can more easily get relevant information about test failures in front of the people who can fix them.

We potentially have two different ways of notifying teams of a failing unit test in `master`: using Slack or email. Each has their advantages and their challenges. For each, though, the thought was that maybe we could use our current codeowners system to identify which teams or people needed to be notified about a failing unit test in `master`. Then we could use either email or Slack for notification.

Tim thought the email notification might be better (and easier), given that is how the codeowners system already works in Github, so that is the primary avenue I explored. Unfortunately, while I did find a way through Github Actions to identify which codeowner team owns the file with the failing test, there was nothing in Github’s API (REST or GraphQL) that would allow us to trigger a codeowner notification. There was also no easy way to figure out who the members were of a codeowner team so that we could send individual emails.

The closest we could get here with a reasonable amount of work would be to add a Slack notification that includes details about the failing test and which codeowner team the test file belongs to. I imagine this could look a lot like the broken link failure notifications we have now. It could even go in the `vfs-platform-builds` channel, same as the broken link notifications.

We would need to be careful, however, to limit the number of tests for which we print details. We would probably want to limit it to five or less; in the case of a mass test failure we wouldn’t want the details for 20 or 50 tests showing up in Slack.

#### Automatically Skip Test in Mocha
If a test fails in `master`, there is a very good chance that it is a flaky test (assuming here that it had to pass the unit test suite on a PR branch in order for whatever is causing the failure to have been merged in). In order to eliminate the chance that this test continues to fail in the future, it would be useful to be able to automatically skip the test in future unit test runs, until the responsible codeowner team is able to fix it.

I investigated this and found that, while this is not 100% impossible, it’s impossible enough that I would not recommend going down this route. We would need to be able to somehow add a `.skip` to the failing test, which would involve some complicated reg-ex that would be brittle enough that I would worry about it breaking and causing more frustration than it’s worth. Also, there aren’t any good examples for editing files in Github Actions for us to follow.

#### Automatically Re-Running the Unit Test Suite After a Failure in `master`
For this one, we could set up a [Github action](https://github.com/nick-invision/retry/) to check for unit test failures and, if it finds them, re-run the unit test suite. There are a few things to consider here, though.

First, given that the most important intervention we had with this unit test improvement effort was simply paying attention to our failing unit tests, I would not be comfortable implementing this without implementing some kind of notification or tracking improvement as well. Even when the tests are re-run automatically, we should be aware of failures so that they can be fixed.

Second, we would need to find a way to persist information about test failures in Github. Currently, if the test suite is run multiple times on the same commit, only the data on the latest test run persists, any information on test failures in earlier runs becomes inaccessible.

Third, we wouldn’t want to run the unit test suite more than two or three times, I think. If the test suite fails three times in a row then there is most likely a legitimate failure that needs to be handled immediately.

Fourth, we already re-run each failing test five times in Mocha. This does not help in cases where something in the test order is causing the failure (as is often the case with flaky tests), but it is good to be aware that this is already happening.

#### Collecting and Reporting Metrics on Tests that Fail in `master`
We could export the test results from `master` runs to an s3 bucket, write some code to parse them, and then print the results to a dashboard. We could even limit the number of files in that bucket and only keep the latest so many or only keep them for a specified length of time.

Having this dashboard would allow us to see if there are tests that are continually failing and not being fixed. It would also allow us to see how often we are experiencing mass test failures, which are an indication that something deeper is happening and we’re going to need to expend some effort to get it fixed. This would be nice to have, however, it is dependent on someone going to the dashboard site to look at the results.

#### Recommendations
In order of priority, here are the actions that are possible:
1. Adding a Slack notification with information about failing tests and the responsible codeowner team.
2. Automatically Re-Running the Unit Test Suite After a Failure in `master`
3. Collecting and Reporting Metrics on Tests that Fail in `master`

If we only do one of these things, I think the Slack notifications would be the one to do. I could see this work taking anywhere from 2 to 3 sprints, depending on the experience of the person doing the work with Github Actions and whether or not any coordination with the Operations team is necessary.

The work to automatically re-run the tests could take 1-2 sprints, as there are a few challenges with Github Actions we would need to work through. Also, I would not recommend doing this unless we are going to add a Slack notification or collect and report test failure metrics.

The work to collect and report on test failure metrics could take 2-3 sprints,  and we would probably want to break it up into several pieces of work:
- uploading the test run results to S3
- parsing the test results (this would include figuring out what data we would want to show on our dashboard)
- displaying the test results on the dashboard

**Comment by timwright12** [comment]
@k80bowman @meganhkelley Based on the time estimates here, I don't think the value is present for any of these tasks. 4-6 weeks to save a support person 30 seconds doesn't seem like the return on investment is there.

**For #1**
This would just take too long, maybe we can revisit after the GHA work is complete, but I would spend more than 1 sprint on something like that, the information is just too readily available with a few clicks,

**For #2**
I agree about not rerunning the tests in master, they're already rerunning a few times, to me that feels akin to increasing a timeout, which is rarely the answer.

**For #3**
I like this one, but same deal, it's a long estimate and we can probably work with Testing tools' Domo integrations to speed this up. Might be a good opportunity to hitch onto that effort. I still wouldn't attempt until GHA work is complete just to get everyone on solid footing.

**Comment by meganhkelley** [comment]
Thanks for the writeup, Katy! I agree with Tim's comments. 

If we entertain the idea of gathering flaky test metrics manually every 6 months (or similar), is that still less work than idea 3 (over the course of, say, 3 years)? I assume yes but want to confirm. 

Other than that Q I think this ticket is good to close with no further action.

**Comment by k80bowman** [comment]
Yes, I think it would take less time to collect it manually every six months for three years (so six times) than it would to build option 3. But that depends on setting up a methodology ahead of time so that we are collecting data for the same number of builds each time. Generally when I have collected this data if I'm going through builds and adding them to a spreadsheet it takes me about a day to a day and a half to gather it all.

**Comment by meganhkelley** [comment]
Got it, thanks! Let's aim to do that very roughly every 6-8 months for the next year, and then we can reassess.

**Comment by k80bowman** [comment]
I can create a card for that and a spreadsheet template with instructions, if you think that would be useful.

**Comment by k80bowman** [comment]
Created a "[Collect Flaky Test Data](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/27112)" card.
