### ISSUE TITLE
Brown Bag Training - Unit Tests

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#25390]
Scheduled for June 17th at 3pm ET

We need to put together a presentation for this. We would like for it to cover:
- [ ] Findings from our flaky unit test analysis
- [ ] Work we have done to help stabilize/improve unit tests
  - [ ] Updated documentation
  - [ ] Resetting fetch mocks between tests
  - [ ] Cleaning up unit test output
- [ ] Recommendations for improving unit test practices
  - [ ] TDD
  - [ ] Cleaning up any mocks
  - [ ] Being careful with shared data mocks

**Comment by meganhkelley** [comment]
Scheduled for June 17 2021

**Comment by k80bowman** [comment]
Presentation slides are here: https://docs.google.com/presentation/d/1WQfl4UMiMSPsaePWpiKIAqbfaECOdNLVxB9A9tHZ03Q/edit?usp=sharing

**Comment by k80bowman** [comment]
Updated Outline:
- Intro - Katy
- Definitions - Katy
    - Unit test
    - Integration test
- Tooling
    - Mocha - Calvin
    - Chai - Calvin
    - RTL - Katy
    - Sinon - Katy
- Practices
    - TDD or BDD - Katy
        - even if you don’t use TDD to write tests, thinking about tests in this way is helpful for writing good tests that will help when functions are being refactored
    - Writing Testable Code - Calvin
        - Functional development
        - Writing smaller functions
    - Controlling for side effects
        - Mock data - Calvin
        - Mocking APIs - Katy
- Q&A

**Comment by k80bowman** [comment]
Session recording: https://www.youtube.com/watch?v=8Y0cuMUoWAw

**Comment by k80bowman** [comment]
PR to add recording to unit test documentation: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/638
