### ISSUE TITLE
Update UI for click-to-call button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25391]
## Acceptance Criteria
1. On the click-to-call component, rotate the phone button clockwise, 90 degrees
     - Ensure that this change is applied globally throughout the app, wherever the click-to-call component appears

.svg: ![phone.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8dad9f73-0815-42fe-a3d8-aaee1ffcb6e0)

## Designs
Design library: https://adhoc.invisionapp.com/console/Mobile-App-Design-Library-cknr12ik52y3q01yq037sp4nb/cknr136x63na301yss5m77mqf/play

Reference:
![Screen Shot 2021-05-28 at 11.05.53 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4ebdc61f-be4f-4c39-848f-1ba22113dc1c)

**Comment by digitalken** [comment]
PASS 6/1/2021 - New icon is in there.  Closing.
