### ISSUE TITLE
Collect Flaky Test Data to Measure Improvement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#25392]
We'd like to see if there has been any improvement in the flaky test situation with all the work we've been doing as part of this epic. In order to measure this, we are going to manually record each build for the vets-website `master` branch in [this spreadsheet](https://docs.google.com/spreadsheets/d/1vrVMNKWS1fXMADeAONHRj4qAVchfFA7EE1i3UhVvLIA/edit?usp=sharing) and track each build that shows a "flaky" test failure (a test that is failing for unknown reasons). We will collect data for the period from May 10th to June 18th (a six-week period) and then analyze the results.

Definition of Done
- [ ] [Spreadsheet](https://docs.google.com/spreadsheets/d/1ygkhUItmLr9KtNIVLutpvLznQoKqWXjFbRltnxTWeGA/edit?usp=sharing) contains record of recent and historical Jenkins `master` branch build failures.
-  [ ] Analysis of results has been added to this card.

**Comment by alex-treebeard** [comment]
Hey @k80bowman I can see how much work you have put into this so I just wanted to share a project I'm working on: [get-flakes](https://github.com/treebeardtech/get-flakes). Would appreciate your feedback on the design so we can make a useful tool!

**Comment by k80bowman** [comment]
## Intro
When we began our work analyzing and improving unit test failure rates, our goal was twofold:
1. Find the root cause(s) for the failures
2. Stabilize our unit test suite and decrease the number and frequency of failures.

We started out with a research phase, looking at intermittent (“flaky”) unit test failures over about a month and a half (February 24th to April 15th). We looked into the causes of the failing tests, identified quick fixes for several of them, and identified a platform-level fix we could implement that would help improve unit test stability.

We spoke with members of several teams about their tests, getting background information on their testing philosophies and practices and discussing the quick fixes we’d found. We also took time to improve our documentation on writing unit tests and held a Unit Test Best Practices training and discussion.

The platform fix we identified was standardizing how fetch is mocked in our tests and adding a function to our mocha setup to reset the fetch mock between tests. We had noticed that some tests were not resetting their fetch mocks and the mocks were then persisting between tests, which could cause some flakiness.

 Given all of that work, we wanted to collect some data and see if any of it had translated to real improvements in our unit test failure rates.

## Methodology
We had data on Jenkins builds with failing unit tests on the `master` branch of `vets-website` from our initial research phase. We chose to focus on failures in the `master` branch because any test failing there had to have passed its PR branch in order to be merged. Therefore, any test failing in `master` can be assumed to be “flaky”. 

What we wanted to do, then, was collect data from a point after our unit test improvement work had begun and then compare the two data sets to see if there was any measurable improvement.

I chose to collect data on Jenkins builds beginning on May 18th and running through June 21st. May 18th is the date that we finished our discussions of flaky tests and quick fixes with frontend teams and marked the end of our first bit of intervention work for this initiative.

This time period covered 385 Jenkins builds of the `master` branch of `vets-website`. I chose to then compare this data against 385 of the most recent Jenkins builds of the `master` branch from our initial research. This covered the time period from March 17th to April 15th.

## Data Analysis
The analysis shows that our work did have a significant effect on unit test failure rates. The data from before our intervention showed unit tests had failed 59 of the 385 Jenkins builds we looked at. After our intervention, only 21 of the 385 Jenkins builds we looked at had failed due to unit test failures.

It should also be noted here that seven of those 21 failures were caused by an issue we have now fixed (the fix was merged in on June 21st), so those types of failures should no longer happen and will cause our unit test failure rate to decrease even more in the future.

## Conclusions
It’s good to see that the time we spent on this initiative seems to have improved the stability of our unit tests. The only real question that remains at this point is whether there were any root causes of the problems we were having and what they were.

Looking back on this initiative, I wouldn’t associate the improvement we saw with any one particular intervention. The root cause, as I saw it, was really a lack of attention being paid to our intermittently failing unit tests. 

As I pointed out in our Unit Tests Best Practices training and discussion, paying attention to how our tests are running is the number one most important way to prevent test flakiness.  When we notice that one of our unit tests has begun to fail intermittently, we need to prioritize fixing it right away. And when we notice unit test runs where multiple tests are failing in seemingly unrelated ways, we need to prioritize finding and fixing the root cause of those failures right away.

Paying attention to our unit tests also means paying as much attention to the tests we write and review as the application code we write and review. We need to make sure that our code is being tested thoroughly and that any cleanup necessary is being completed between each test.

**Comment by k80bowman** [comment]
Received feedback on summary from @Cgfor3 and @meganhkelley. Closing now.
