### ISSUE TITLE
Small improvements to confirmation page

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#25397]
![Screen Shot 2021-05-28 at 5.36.11 PM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/e5ce0eaf-1931-4bec-aa92-90e2423d404c)

When an application is successfully submitted:

1) link should read: https://www.caregiver.va.gov/
2) go back to VA.gov should be a link not a button

**Comment by Dene-human** [comment]
Prototype is updated: https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666521/simulate/sitemap?mode=i

**Comment by Dene-human** [comment]
@dat-gcio This is ready for you. Should we create a new ticket for FE?

**Comment by dat-gcio** [comment]
@Dene-human I believe so, because all your parts are done, so this ticket is technically done.

**Comment by Dene-human** [comment]
Created Frontend ticket #[25543](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/25543)
