### ISSUE TITLE
Lighthouse UX Toolkit Kubernetes (EKS) Onboarding

### ISSUE THREAD

**Issue by anthony-kopczyk** [department-of-veterans-affairs/va.gov-team#25394]
## Description of your application
_Describe your application_
The UX Toolkit contains various tools for the UX team to increase productivity and efficiency. Currently it contains a transcription tool, where the team can upload research interviews and have them automatically transcribed in order to cut down on the manual process of transcribing by hand.

_Name_: UX Toolkit

_Functionality_:
- **Auth**: Users sign in with github OAuth, and are authorized if they belong to one of the github teams configured in the app.
-  **Transcription**: If authorized, the user can access the transcription tool. Here they can upload recordings of user interviews. These interviews are transcribed using AWS Transcribe. The user can then view the transcription in the app or download it as a word document.
-  **External Tools**: This is not yet implemented. We have designs to include some links that the user can click to go to other tools used by the UX team. These will really just be fancy looking hyperlinks.

_Language/Stack_: Ruby on Rails

_Ports/Networking needed_:
These ports could all easily be configured on our end. Currently it expects the following:
- Web Server: Standard: 80/443
- Expects the database at 5432
- Expects redis at 6379
- Needs to be able to reach https://api.github.com
- Needs to be able to reach the S3 buckets - more info under 'Other infrastructure needed'

_Other infrastructure needed e.g. Database, redis, etc_:
- Redis (port specified above)
- Postgres Database (port specified above)
- S3 buckets to store interview sources and outputs with PII - AWS Transcribe takes care of removing PII from the output. We currently have two buckets, that should delete their content after 90 days to keep with standards on PII. These were created as one-offs, and to my knowledge there's no backing terraform or IAC to back these up. In addition, it would be helpful to have some kind of development bucket we can use, and have a single bucket dedicated to production. These buckets are under dsva from, I think a previous time, when that account was shared.
  > dvpuxresearchinput
  > dvpuxresearchoutput

_Anything else we need to know?_:
We are still moving toward being production ready in the codebase. We're in the process of improving the transcription, making sure we have better testing, code linting, and improving acessibility. We wanted to get this process started ahead of time so that once we're ready we can get it deployed - or if this goes quicker, we can get some kind of staging/dev/test environment deployed for the UX teams/users to use so we can get feedback.

We are planning to expand on this tool but do not have specific plans at this time. One idea is a tool/API to retrieve the reading level of a certain block of text. I don't think this will change the needed ports or infrastructure however.

We are onboard helping with any sort of terraform or related coding if that's desired. We're willing to help out with that if it will help speed up the process and we have a devops engineer on the project that has already said he could help us out. If this doesn't work out, that's fine, but we wanted to be forward about helping if possible.

## Background/Context/Resources
_Any addition information that can be provided, Slack conversations, tickets, design documents, epics, etc._
Slack thread including jira ticket and description of app - also coordination between teams: https://dsva.slack.com/archives/CJYRZK2HH/p1620325697040900

## Technical Notes
_Any addition technical notes that can be provided_

## Checklist of Items needed for onboarding (Responsible parties in parentheses)

[ ] Your application! (Your team)
    Your application should conform to the 12 factor app methodology (https://12factor.net/)
[x] A Github Repository for your application (Operations or your team): https://github.com/department-of-veterans-affairs/lighthouse-ux-toolkit
[ ] A Dockerfile for your application (Your team, Operations can assist if needed)
[ ] Elastic Container Registry Repository for your application (Operations, PRs are welcome: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)
[ ] Automation to "Release" and "Tag" the application Github Repository with a semantic version number. (Your team, Operations can assist if needed)
[ ] Automation to push the built Docker container to the ECR Repository and tag it with the semantic version number. (Your team, Operations can assist if needed)
    Please do not use 'latest' tags
[ ] Kubernetes Application Manifest in YAML, jsonnet, or Helm Chart (Operations and your team)
    YAML and jsonnet are highly preferred, Helm charts are discouraged
[ ] Automation to update the Kubernetes Application Manifest when a new version of your application container is pushed to ECR (Operations and your team)
[ ] AWS Service account for your team or application (Operations)
[ ] Path/s in AWS SSM Parameter Store created for your team or application (Operations)
[ ] AWS IAM Permissions applied to your team members to allow read/write access to AWS SSM Parameter Store path/s for your application/team (Operations)
[ ] AWS IAM Permissions applied to the service account to allow read access to AWS SSM Parameter Store path/s for your application/team (Operations)
[ ] Secrets and Parameters needed for your application stored in AWS Systems Manager Parameter Store (Your team)

**Comment by dginther** [comment]
I have created discrete tasks and issues in the project here: https://github.com/department-of-veterans-affairs/devops/projects/16

Please feel free to drop notes in the tickets or just add a notecard in the to-do column if needed, no need to create a whole issue.

**Comment by dginther** [comment]
Demian to add lighthouse-marmoset team to a project in ArgoCD to allow team access.

**Comment by jbritt1** [comment]
@anthony-kopczyk, is lighthouse-ux-toolkit still a current initiative?

**Comment by jhouse-solvd** [comment]
Closing. If this is still needed, please open a new request using the ["Application Onboarding Template" ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=devops%2C+eks%2C+infrastructure%2C+infrastructure-request%2C+operations&template=kubernetes-onboarding-template.md&title=%5BInsert+app+name+here%5D+-+Application+onboarding+infrastructure+request)
