### ISSUE TITLE
[Backend] Submit Space Force as service branch option on 10-10EZ form

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25407]
## User Story

**As a** veteran, **I want to** select US Space Force as my service branch when I apply for healthcare using the online 10-10EZ form **in order to** correctly identify my service branch.

This is the BACKEND story

## Expected Behavior

When a veteran selects the US Space Force option and submits, the option should be correctly sent to CARMA

## Acceptance Criteria

- [ ]  Adding the new reference code to send it in the interface to ES
- [ ]  Tested in Staging prior to release

**Comment by kevinmirc** [comment]
This is blocked until we can get a confirmation of the code (integer) used by the Enrollment System to represent space force (see current service branch codes here).

We **can** merge these PRs (schema, UI, API) and send the code for "Other" (`6`), and do a followup PR when we know the code.

Will consider this blocked for now.
