### ISSUE TITLE
[Carryover][Frontend] Improve document upload error messaging

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25405]
## User Story

**As a** veteran/caregiver, **I want to** be told what I need to do whenever I encounter an error while uploading a document while completing the 10-10CG **in order to** correct the problem or try again.

## Expected Behavior

If a veteran/caregiver receives an error while uploading document, we want to provide an informative error message that gives instructions to the user on what to do next.

Currently, the system is returning generic error messages without any instructions on what the user needs to do.

Refer to:
* [Design]: Design details and customize copy and/or error messaging for the "upload" component in 10-10CG#20318
* Form system - upload document error message #25320

## Acceptance Criteria

- [ ] Each upload document error state within the form system is updated with content that gives users appropriate guidance for next steps.
- [ ] Frontend component is updated

**Comment by Dene-human** [comment]
As per the platform slack support, we are approved to implement #25320

![Screen Shot 2021-06-11 at 2.16.48 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/477835f6-ba17-4cc6-9865-fc687dfc8ff2)

**Comment by dat-gcio** [comment]
Here is the link for the [review instance](cf45fe50576b11dbb1239f527aded25f.review.vetsgov-internal). 
[Caregiver file upload](http://cf45fe50576b11dbb1239f527aded25f.review.vetsgov-internal/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/representative-document-upload)
[Disability benefits file upload](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records-upload)

**Comment by dat-gcio** [comment]
@tchrisdyer This is merged and is in Staging. Will hit prod at 3:00PM EST today.

**Comment by dat-gcio** [comment]
Validated in staging. Additional accessibility feedback to be implemented in follow up ticket with workflow changes.
