### ISSUE TITLE
[Frontend] Add Space Force as service branch option to 10-10EZ form

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25406]
## User Story

**As a** veteran, **I want to** to select US Space Force as my service branch when I apply for healthcare using the online 10-10EZ form **in order to** correctly identify my service branch.

This is the FRONT END story.

## Expected Behavior

A US Space Force option should be added to the list of service branches in the 10-10EZ form.

## Acceptance Criteria

- [ ]  Added it to the dropdown for last branch of service
- [ ]  Adding the new reference code to send it in the interface to ES
- [ ]  Tested in Staging prior to release

**Comment by dat-gcio** [comment]
@tchrisdyer Here is the [link](http://8ebdecd6ff41d9568a2fc65cedc5db79.review.vetsgov-internal/health-care/apply/application/introduction) to the review instance. Let me know if you need help running socks to get to this site.

cc: @kevinmirc

**Comment by dat-gcio** [comment]
@tchrisdyer This is ready to merge whenever you get the confirmation about the display name of `Space Force`

**Comment by dat-gcio** [comment]
@tchrisdyer I tested this in staging. Not sure if you wanted to as well before I close this ticket.
![image](https://user-images.githubusercontent.com/83595736/121736862-22bbcb00-cac6-11eb-8c0d-33a047bd86f3.png)

**Comment by dat-gcio** [comment]
@tchrisdyer closing this out. It has been tested in stage and has been sitting in prod for a couple of days now.
