### ISSUE TITLE
[BE] 10-10EZ - SIGI: Hook up new SIGI question to ES

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25415]
## User Story

**As a** veteran, **I want to** select my gender on the 10-10EZ form **in order to** reflect my self-identifying gender identity.

This does NOT need to be added for Spouse. Only for the veteran.

## Expected Behavior

The veteran's gender identity selection is sent to the Enrollment System (ES)

## Acceptance Criteria

- ~Enclosed with SIGI feature toggle~
- [ ] Schema is merged in (https://github.com/department-of-veterans-affairs/vets-json-schema/pull/655)
- [ ] Gender identity is received from Front End
- [ ] Gender identity is transformed into the payload for ES
- [ ] Gender identity is successfully sent to ES
- [ ] End-to-end testing in staging

## Value Mapping
The backend will need to convert the values sent from the front end to into values expected by Enrollment Systems:
![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/5bd903c2-f884-4c19-8a7e-95b78c1f14d8)

**Comment by tchrisdyer** [comment]
Updated to add: This does NOT need to be added for Spouse. Only for the veteran.

**Comment by kevinmirc** [comment]
Blocked: The Enrollment System is not yet ready to accept this field.

**Comment by MickinSahni** [comment]
Blocked until we know how ES will accept these changes. Pending a meeting with HEC

**Comment by MickinSahni** [comment]
Paused until we clarify how ES will accept our payload
