### ISSUE TITLE
[FE, PM][ 10-10EZ - SIGI: Add event tag to the page to track how many applicants answer the question

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25414]
## User Story

**As a** VFS Stakeholder, **I want to** monitor, and analyze the ability for veterans to select their gender on the 10-10EZ form **in order to** verify the functionality and report on it.

This does NOT need to be added for Spouse. Only for the veteran.

## Tasks
- [ ] Event tag is added to track whether a selection was made on the question
- [ ] PM confirms event is trackable in Google Analytics

## Acceptance Criteria
- The functionality is working properly and we are able to monitor and report on it.

**Comment by tchrisdyer** [comment]
Updated to add: This does NOT need to be added for Spouse. Only for the veteran.

**Comment by longmd** [comment]
@hdjustice , do we have "staging" dashboards we could check this in?

**Comment by hdjustice** [comment]
Hi @longmd - Yep, they have a staging environment.  We have to submit an Analytics ticket since I dont think one was submitted for this feature yet

**Comment by longmd** [comment]
SWEET! That works.. I'm going to make a note in #31735 to for us to submit that ticket and verify we're tracking.
