### ISSUE TITLE
[Design] Create design Self-Identifying Gender Identity on 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25412]
## User Story

As a veteran, I want to select my gender on the 10-10EZ form in order to reflect my self-identifying gender identity.

This is a DESIGN story to create the design of the new functionality.

This does NOT need to be included for Spouse; only the Veteran.

## Expected Behavior

Design is confirmed.

## Acceptance Criteria

- [x] Design is approved
- [x] Collab Cycle feedback is incorporated

**Comment by tchrisdyer** [comment]
Updated ticket to clarify that it does NOT need to be added for Spouse. Just for the veteran.

**Comment by Dene-human** [comment]
Hi @mlighdc  I created the first round [**design mockups for the updated SIGI**](https://app.zenhub.com/files/133843125/785da4aa-3a90-4700-a268-75c856383b2f/download). Please see my questions below.

**Questions**
1. Is birth sex required?
2. Is SIGI required?
3. Are we ok to implement [Style guide gender pattern](https://design.va.gov/patterns/form-templates#gender) or do we need to stick to paper form content? 
4. I updated the race, ethnicity, origin question to align with [style guide](https://design.va.gov/patterns/form-templates#race-ethnicity-or-origin), added the hint text (from paper form), and alphabetized the list. Any questions or concerns with this update?


CC: @tchrisdyer

**Comment by mlighdc** [comment]
@Dene-human
1. I would keep it as it is 
2. This would be optional
3. Yes, here is what Danielle proposed and has been agreed upon:
![image](https://user-images.githubusercontent.com/35788031/122814468-39220d80-d2a2-11eb-9905-698e7ea5f760.png)
4. Should not be a problem as long as it is mapped on the back end.

If you have any other question, please let me know. Thanks!

**Comment by Dene-human** [comment]
Thanks!

[Updated design](https://app.zenhub.com/files/133843125/ab95ef3d-606f-4f7b-82f8-ab24045c74aa/download)

Now waiting for Platform review #26355

**Comment by Dene-human** [comment]
I'm closing this as the design has been approved. We will finalize the content in #25350
