### ISSUE TITLE
🛑 [Frontend] Add Self-Identifying Gender Identity (SIGI) to 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25411]
## User Story

**As a** veteran, **I want to** select my gender on the 10-10EZ form **in order to** reflect my self-identifying gender identity.

This the FRONTEND story to allow the veteran to select the gender identity.

This does NOT need to be added for Spouse. Only for the veteran.

## Expected Behavior

The veteran is able to select the appropriate gender identity.

UX Design Ticket: #25412

## Acceptance Criteria

- [x] UX Design is confirmed
- [x] Frontend is updated based on UX design
- [ ] Functionality is tested in staging
- [ ] Critical Accessibility issues are addressed
- [x] Validated via Review Instance
- [ ] Turned off in prod (via toggle) until ES can accept!

**Comment by Dene-human** [comment]
@LinnJS Here is the [design PDF](https://app.zenhub.com/files/133843125/56bd174b-e3b1-416d-9999-b023f0679158/download)

Patrick said that it might not be possible to include "prefer not to answer" If that is true. It is ok to remove that value.


Apologies for the confusion!

**Comment by LinnJS** [comment]
@Dene-human I don't see why prefer not to answer is a big deal we can keep it :)

**Comment by Dene-human** [comment]
> @Dene-human I don't see why prefer not to answer is a big deal we can keep it :)

Ok cool! Yeah i think he was worried that maybe ES couldn't accept it. I don't know exactly thought TBH.

**Comment by MickinSahni** [comment]
PR contains sigi question (behind feature toggle) as well as splitting up of existing questions. Waiting for CI/CD to clear up with Platform

**Comment by MickinSahni** [comment]
Tests passing. @LinnJS focused getting RI up and shared

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19337) where this work is being done
