### ISSUE TITLE
[Schema] Add Self-Identifying Gender Identity (SIGI) to 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25413]
## User Story

**As a** veteran, **I want to** select my gender on the 10-10EZ form **in order to** reflect my self-identifying gender identity.

This story is to update the schema for this new functionality.

This does NOT need to be added for Spouse. Only for the veteran.

## Expected Behavior

Gender options are available and selectable.

## Acceptance Criteria
- [ ] Schema is updated: [schema #655](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/655). (Note that this is a work in progress.)
  - We're retaining birth sex values of `Female` and `Male` but moving them to a new constant: `birth_sexes`
  - Genders have been created under the constant `genders` with the new values as given in the design document
 
- ~Update API to send the selection to ES (behind feature toggle)~
- ~Test submissions to ensure application can be accepted by ES, with these changes~

[Design Document](https://github.com/department-of-veterans-affairs/va.gov-team/files/7470861/ac8e47b1-e95e-4ef8-959d-77fe293a759b.pdf)

**Comment by tchrisdyer** [comment]
Updated the story to add a note: This does NOT need to be added for Spouse. Only for the veteran.

**Comment by kevinmirc** [comment]
@tchrisdyer, @mlighdc Do we have the list of selections (labels and data values) for the new SIGI question?

**Comment by mlighdc** [comment]
@kevinmirc here are the proposed values

![image](https://user-images.githubusercontent.com/35788031/120737877-e0d6c780-c4bc-11eb-8a82-40cb04ce556a.png)

**Comment by mlighdc** [comment]
One note @kevinmirc, I am not sure what values need to be passed to the backend systems. Josh is out until Monday (6/7).

**Comment by kevinmirc** [comment]
Okay, I think we will have to block this ticket until we know what the backend values will be and we can get confirmation that Enrollment System can accept them.

Will be moving to other tickets for now until we can get confirmation from Josh.

**Comment by mlighdc** [comment]
@kevinmirc can you pull together a list of questions for Josh so if he is not available, we can still move forward? Thanks.

**Comment by kevinmirc** [comment]
Just wanted to document Josh's responses to our questions:
- The code for "space force" as a service branch for Enrollment Systems is `15`, and their backend is ready to receive it.
- ES is not yet ready to receive the SIGI field.

**Comment by kevinmirc** [comment]
This is blocked until ES can accept the SIGI field.

**Comment by MickinSahni** [comment]
Made an educated guess on what the `value` should be for each new label (e.g. TM for Transgender Male)

**Comment by MickinSahni** [comment]
Q: how do we prevent a PR from merging?
- A: 
  - Title - Include "WIP"
  - add `donotmerge` label
  - create a draft PR

**Comment by MickinSahni** [comment]
Pending sync with HEC to confirm final values associated with new labels

**Comment by LinnJS** [comment]
I took a stab at this since its been sitting for a while can update the values anytime just felt like these names made semantic sense from my side on the frontend.

https://github.com/department-of-veterans-affairs/vets-json-schema/pull/660/files#diff-ba2e40a65c66be0b39f44333042d7985d263679b0a8f59f2b4f7d9e29ebabc79R1598-R1618

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/660) where this work is being done and is integrated with frontend on this [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19337)

**Comment by Dene-human** [comment]
@LinnJS @jchilders 

Here is the [design/content PDF](https://app.zenhub.com/files/133843125/56bd174b-e3b1-416d-9999-b023f0679158/download)

Patrick said that it might not be possible to include "prefer not to answer" If that is true. It is ok to remove that value.


Apologies for the confusion!

**Comment by MickinSahni** [comment]
Verify that with https://github.com/department-of-veterans-affairs/vets-json-schema/pull/661, 10-10ez still works via RI. If it works, we'll move ahead with this schema PR (with the FE work behind toggle in #25411)

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/661) where this work is being done in order to enable this task [ticket](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/25411)
