### ISSUE TITLE
EDU Forms /5490 Update: IR-1002 Prototype - Revision

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#25421]
Prototype is updated with radio buttons & date selection

* Prototype is updated to incorporate radio & date selection
* Prototype is reviewed w Xfunc team
* Updates are incorporated, as necessary

**Comment by JenLJ** [comment]
Prototype: https://bahdigital.invisionapp.com/share/SZIAGWJTXCU
