### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by mattpointzxer0** [department-of-veterans-affairs/va.gov-team#25436]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [X] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
As soon as possible

## Product Team / External Team / VA Office
OCTO-DE, Benefits

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
Hi @mattpointzxer0 I've granted GA access to your email (matthewself.dsva@gmail.com). Please feel free to re-open this ticket if you do not see the welcome email or if you have any trouble getting logged in.

**Comment by joanneesteban** [comment]
@laurensimpson14 - sorry, I think this is missing from our team documentation. I'm adding it now. We'll need to provision access to the VA.gov email so that we're not giving access to personal gmail accounts.

**Comment by laurensimpson14** [comment]
I've removed access to the gmail account. @mattpointzxer0 what is your VA.gov email address?

**Comment by bsmartin-ep** [comment]
@mattpointzxer0 - you have been added to our GA account.
