### ISSUE TITLE
Slack request: Team members need access to #devops-deploys

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#2543]
The BAH team needs access to the #devops-deploys channel because it's the channel where gids deploy notifications are shared and we're supporting GIDS as part of our work for the GI Bill Comparison Tool. 

Team members to include: 
Desiree Turner
Matthew Roth
Devin McCurdy
Daniel Shawkey
Will McCormack 
Kenneth Santiago
Joseph Elder

**Comment by lisac-usds** [comment]
this is done!
