### ISSUE TITLE
Feature Toggle: Add Self-Identifying Gender Identity (SIGI) to 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25446]
## User Story

**As a** VFS Stakeholder, **I want to** put the new self-identifying gender identity functionality behind a feature toggle **in order to** control when and how this feature launches.

This does NOT need to be added for Spouse. Only for the veteran.

## Expected Behavior

Feature toggle created for Self Identifying Gender Identity (SIGI), Allows dialup %.

## Acceptance Criteria

- [x] Feature toggle created: `caregiver_sigi_enabled`
- [ ] Feature toggle tested.

**Comment by tchrisdyer** [comment]
Updated to add: This does NOT need to be added for Spouse. Only for the veteran.

**Comment by MickinSahni** [comment]
Validated 
![image](https://user-images.githubusercontent.com/13204473/138175948-0891fc9d-e5ef-4a2f-b6ab-2b7005c0227d.png)
