### ISSUE TITLE
Updated Design for Spell Check

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#25443]
Updated design for #19225
[Invision link](https://vsateams.invisionapp.com/console/UI-Search-Consistency---desktop-cknr2uisl2tl101ymmt48cx3z/ckoycyvys00qg01154omqe7ap/play)

**Comment by denisecoveyduc** [comment]
Thanks for creating this to capture the work. I have added it to our sprint report.
