### ISSUE TITLE
[Decision Tools - Find a VA Form search & UI enhancements] VSA-QA Test Plan

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25455]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: \https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md
- Product/Feature Epic: #21639
- Product/Feature Copy deck(s): In Design Prototypes
- Product/Feature Design prototypes: In Design Prototypes
   - Search Landing Page Desktop:  https://vsateams.invisionapp.com/console/share/SD10IE31CENR **please note that the words "search results" should NOT appear in the title after "Find a VA form"**
   - Search Landing Page Mobile: https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4/60053858  **please note that the words "search results" should NOT appear in the title after "Find a VA form"** 
   - Form Detail Page Mobile: 
   - Form Detail Page: https://www.sketch.com/s/b63a081e-fa7a-4e33-bc9a-f2614bc4f703/a/g0bY2nk
 
## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Cassandra Allen
Content/IA: 
Front-end: Zach Morel
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md

## How to configure this issue

- [X] **Product Manager** added to Assignees
- [X] Attached to a **Milestone** (when will this be completed?)
- [X] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [X] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.  
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod environment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@MarciMcGuireGCIO , I've updated my TestRail test-cases.  You can click on the **TestRail Test Case** link under each of your updated **[Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md)** to see TR test-case details.

**Comment by MarciMcGuireGCIO** [comment]
@tlei123 We are ready for you to schedule our test run.  We are targeting 7/1 for our Staging review.   Please let me know what additional information you need from me; it's been a bit since I've done this!  Thank you!

**Comment by tlei123** [comment]
Thx, @MarciMcGuireGCIO !  I'll start test-runs this afternoon; should be done by eod tomorrow.

Everything looks good right now, but if I run into problems or have further questions I'll just ping you on Slack.

**Comment by MarciMcGuireGCIO** [comment]
Awesome; thank you, @tlei123 !

**Comment by tlei123** [comment]
@MarciMcGuireGCIO , all test-runs now completed.  QA-artifact links are below, and will also be added/updated in the Staging Review ticket #26298 .

100% Passed; no defects logged.

TestRail artifacts:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1923)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1308)
- [Coverage for References (Cases) report]()
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/248)
