### ISSUE TITLE
Content Feedback - Staging review - Language Assistance and Resources 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#25454]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
Hello, content feedback for Language assistance staging review. 

**Consider**

Consider linking to the Spanish and Tagalog language assistance pages from English assistance page.

**Comment by SKasimow** [comment]
@peggygannon Thanks...I'll discuss with @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - forgot if we discussed this. Think it would be helpful to provide another placement to Spanish and Tagalog in addition to the footer.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - should we add this to our backlog and have the spanish/tag toggle appear on "Other languages" page?

cc: @adamwhitlock1

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA can this ticket be closed? I found this in searching for tickets assigned to Sharon who is no longer with the org. It's not clear to me what product this is even related to.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz! Yep, I'll close this. This is related to a team that I led to do discovery around multilingual content and begin setting up the foundation for multilingual content for VA. Sharon and Adam were both on that team with me before they moved into the auth world. Thanks for tagging me!
