### ISSUE TITLE
Contact Center Review for VA Mobile App

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#25457]
## Description
The Office of the CTO will be launching a mobile app that leverages native mobile features to allow Veterans to quickly and easily check the status of their services and complete simple, transactional tasks across health and benefits. 

### Launch Date
6/7/2021

### Version Number
V1

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/vfs-product-guides/VA.Mobile.App.Product.Guide.docx

### Product Video
Not available yet

### Product Video Transcript
Not available yet

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Sent review draft to @clantosswett via VA.gov email

**Comment by starlow00** [comment]
Sent draft to VEO for review; copied Caroline H. for New Hire training prep.

**Comment by starlow00** [comment]
Incorporated edits requested by Chante and the app team (by Ashley Matthews). Sent updated draft with explanation to Caroline Hain and VEO.

**Comment by starlow00** [comment]
No edits from VEO. 
[VA-Mobile-App-Product-Guide-Call-Center-Support-061521.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6712305/VA-Mobile-App-Product-Guide-Call-Center-Support-061521.docx)
