### ISSUE TITLE
Views Past Appts, View Details Returns Back to Upcoming Appts 

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25456]
1.  Log into VAOS
2.  In Show by Type, select Past, Select any of the date ranges
3. List displays, select to view details for an appointment.  Appointment details displays.   Select the 'go back to appointment button'.
4. Expected response: User is returned back to Past Appointments and the date range previously selected.  
5. Actual response:  User is returned back to Upcoming Appointments and has to redo their previous selections to return back to the list they were just viewing.

**Comment by laurenernest** [comment]
This is covered in #25363. Closing as dupe.
