### ISSUE TITLE
"No cached content found" when using `yarn fetch-drupal-cache`

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#25469]
## What happened?
```
yarn run fetch-drupal-cache
yarn run v1.12.3
$ node script/drupal-aws-cache.js --fetch
No cached content found for that environment and query: https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/content/vagovdev_800ac7712de91ca3d537f4de4635faa2.tar.bz2
```

## Steps to Reproduce
```
git clone https://github.com/department-of-veterans-affairs/content-build
cd content-build
yarn install
yarn run fetch-drupal-cache
```

note: also tested with `vagovprod` buildtype
```
yarn run fetch-drupal-cache --buildtype vagovprod
yarn run v1.12.3
$ node script/drupal-aws-cache.js --fetch --buildtype vagovprod
No cached content found for that environment and query: https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/content/vagovprod_800ac7712de91ca3d537f4de4635faa2.tar.bz2
```

## Desired behavior
Should pull drupal data from S3

## Acceptance Criteria
- [ ]  Successfully pulls drupal data from S3

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by timwright12** [comment]
Closing this out as it seems like it was just a hiccup in the system. [Slack Context](https://dsva.slack.com/archives/C01512KN35G/p1622638479086600)
