### ISSUE TITLE
Appointments not sequenced correctly

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25462]
## What happened?
1. In the upcoming appointments list, some appointments are not sequenced from most recent to least recent. Judy.m has upcoming appointments for September 2021 and October 2021 that are incorrectly listed **after** appointments for December 2021. 

Note: Within the month heading (i.e. September 2021), appointments appear to be sequenced correctly.

2. Some past appointments are also listed out of order.

## Specs:
- Device: iPhone 11
- Test user: judy.m

## Steps to Reproduce
1. Navigate to the Upcoming Appointments page
2. From the pagination CC, navigate to page 4 and 5. 
3. Notice how the appointments are listed in the following sequence (<*> indicates appointments that are not sequenced correctly):
     - November 2021
     - December 2021
     - September 2021*
     - October 2021*
     - December 2021
     - January 2022
     - February 2022
     - March 2022
4. Navigate to the Past Appointments page. Select "Past 3 months" as the dropdown field. 
5. View list of past appointments. Navigate across several pages. Notice how they are listed in a seemingly random order:
     - March 17 (page 1)
     - March 16 (page 1)
     - March 2 (page 1)
     - March 31 (page 2)
     - March 16 (page 2)
     - April 6 (page 3)
     - March 31 (page 3)

## Desired behavior
1. Upcoming appointments are listed from most recent date to least recent date. 
2. Past appointments are listed from most recent date to least recent date.

## Acceptance Criteria
See desired behavior above.

## Bug Severity
- 3 - Medium

## Linked to Story
#13971 - AC 3
#13994 - AC 4

#### Upcoming appointments issue
![Image from iOS (8).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/85d75af7-ec8d-4880-9d3c-63bdb7b2fa46)

#### Past appointments issue
https://images.zenhubusercontent.com/133843125/c60e0967-7d92-45cf-a5c6-951a71afb96a/image_from_ios.mp4

**Comment by digitalken** [comment]
PASS 6/18/2021 - Ordering now looks correct, not random.  Closing.
