### ISSUE TITLE
Vaccine scheduling-Staging Review Design Updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25478]
## Description
Per VSP Design feedback in #24102, update copy based on recommendations.
![25478_scope_1.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/287c5d19-e11d-41d4-8950-4188bce161c7)   ![25478_scope_2.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/c5f50935-a963-4a08-99c7-cf4f052a565a)

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] DESIGN - Plan Ahead page designs match the specs (copy is FPO)
[Mobile](https://www.sketch.com/s/fd383f03-0827-49a7-865c-e0b44f70b183/a/3OPEQLD#Inspector)
- "i" icon to bullets
- [ ] DESIGN - Contact Facility-dose received page designs match the specs (copy is FPO)
[Mobile](https://www.sketch.com/s/fd383f03-0827-49a7-865c-e0b44f70b183/a/52PWQyP#Inspector)
- Move H1

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation/screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) are updated

**Comment by jenniemc** [comment]
@laurenernest,  @outerpress, I currently have the text inside the alertbox  "If you got your first dose:" designated as `<h2>`.  Let me know if that's what you intended. Thanks.

![image](https://user-images.githubusercontent.com/54327023/120701903-70f71b80-c481-11eb-9dd6-d12f76667d6a.png)

**Comment by outerpress** [comment]
@jenniemc that wasn't the original intent but I think it makes sense to make it an h2 as you have in your screenshot. Good catch!
