### ISSUE TITLE
5490: Remove feature flag for form updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25506]
As a developer, I need to remove the 'edu_form5490_updates' feature flag toggle so that it is no longer configurable, and the new functionality is permanent. 

## Assumptions: 
1. UAT has been completed for this effort and EDU signed off as of 2021-06-14. 
2. The new functionality is live in production with no need remaining need for the toggle. 

 ## Acceptance Criteria 
1. The feature flag 'edu_form5490_updates' is removed. 
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features. 

 ## Supporting Artifacts: 
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-api/pull/7447

**Comment by sonntag-adam** [comment]
In all environments. Closing story.
