### ISSUE TITLE
Translated Medallia survey content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#25503]
## User story

As a VA.gov translation team member, I need to know how helpful our newly translated pages are for Veterans, caregivers, and family members with limited English proficiency. 

## Issue description

Get Medallia survey translated into Spanish and Tagalog

### English

**Were you able to do your task today?**
- Yes
- No

**What task were you trying to do today?**

**What is your overall satisfaction with this site?**
1, 2, 3, 4, 5

Very dissatisfied

Very satisfied

[button 1] Cancel [button 2] Submit

### Spanish

**¿Pudo realizar su tarea hoy?**
- Sí
- No

**¿Qué** tarea estaba tratando de hacer hoy?**

**¿Cuál es su satisfacción general con este sitio?**
1, 2, 3, 4, 5

Muy insatisfecho

Muy satisfecho

[button 1] Cancelar [button 2] Enviar

### Tagalog

**Nakita mo ba ang mga hinahanap mo ngayon?**

•	Opo
•	Hindi po

**Ano ang mga sinusubukan mong alamin ngayon?**

**Gaano kayo kakuntento sa pahinang ito?**
1, 2, 3, 4, 5

Hindi nasiyahan

Talagang nasiyahan

[button 1] Kanselahin  [button 2] Ipasa

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow Got Tagalog survey translation back. They also provided again in Spanish, so we should check against the previously provided Spanish translation just to check if there are any changes to consider. Thanks!

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danielle - I reviewed and there are some slight differences between the old and new Spanish translations (attaching a slide highlighting these differences).

Can we get clarification on which to use? T[https://app.zenhub.com/files/133843125/df610c97-630d-4831-8380-3b0a045bff2f/download]he original text was already sent to Medallia and I believe they've begun (or are about to) start working on it.

Thanks,

Sharon


[https://app.zenhub.com/files/133843125/8b206315-b35e-404e-b4ca-925bc1a3d443/download](https://app.zenhub.com/files/133843125/8b206315-b35e-404e-b4ca-925bc1a3d443/download)
