### ISSUE TITLE
10203: Remove feature flag for form updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25507]
As a developer, I need to remove the 'edu_form10203_updates' feature flag toggle so that it is no longer configurable, and the new functionality is permanent. 

 ## Assumptions: 
1. UAT has been completed for this effort and EDU signed off as of 2021-06-23. 
2. The new functionality is live in production with no need remaining need for the toggle. 

 ## Acceptance Criteria 
1. The feature flag 'edu_form10203_updates' is removed. 
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features. 

 ## Supporting Artifacts: 
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/7431
