### ISSUE TITLE
Use Mochawesome Report Generator to Collect E2E Data and Push it to BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25516]
# Description
Configure Cypress to use Mochawesome as a test reporter. Collect the test results, create a report, and push the report data to BigQuery.

# Tasks
- [x] Push Data to Big Query

**Comment by holdenhinkle** [comment]
PR to grab Cypress Mochawesome test results files as an artifact from each Cypress test execution running in parallel, then, once all 6 executions are complete, kick off a workflow that checks out the Testing Tools Team Dashboard Data repo, downloads the artifacts into the `mochawesome/data directory`, updates the results files, merges them, generates a Mochawesome report, then posts the results data to BigQuery - https://github.com/department-of-veterans-affairs/vets-website/pull/17625

I made good progress on this today. Testing it now. Very close to working (might be working!).

**Comment by holdenhinkle** [comment]
Soooo close getting this to work!

Convo with Demian - https://dsva.slack.com/archives/CJYRZK2HH/p1623887134208800

I'm guessing we'll be able to pump Cypress Mochawesome results into BigQuery tomorrow morning.

**Comment by holdenhinkle** [comment]
Jeremy is adding testing tools param access to frontend GHA SA.

See - https://github.com/department-of-veterans-affairs/devops/pull/9428

**Comment by holdenhinkle** [comment]
We’ve got Cypress test results data pumping into BigQuery from GitHub Actions using Darius’ Cypress parallelization:

GHA Job - https://github.com/department-of-veterans-affairs/vets-website/runs/2851625155?check_suite_focus=true

```
Create report and post results to BigQuery
Run yarn cypress-mochawesome-to-bigquery
yarn run v1.22.10
$ node src/mochawesome/
Inserted 1 row(s) into cypress_test_suite_executions.
Inserted 139 row(s) into cypress_test_results.
Done in 1.94s.
```

**Comment by holdenhinkle** [comment]
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/1fadd472-8928-475e-ad7f-fd8ca82ce4aa)

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/vets-website/pull/17625

**Comment by holdenhinkle** [comment]
The PR was merged.

**Comment by holdenhinkle** [comment]
This ticket is complete.

**Comment by pjhill** [comment]
Excellent -- great work!
