### ISSUE TITLE
[ Usability Testing for Candidate Address Validation ] 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2551]
### Scheduled for the following timeframe in Eastern Time

11/13/19 - 8:30am - 9:30am
11/13/19 - 11:30am - 12:30pm
11/13/19 - 1:30pm - 2:30pm
11/15/19 - 11:30am - 12:30 pm
11/15/19 - 1:30 pm - 2:30pm 

## Definition of Done 
- [x] Usability testing has been scheduled
- [ ] Usability testing has been completed 
- [ ] Feedback has been compiled and socialized with team

- [ ] If changes are needed, the changes have been made
- [ ] Tested and validated
- [ ] This ticket can be closed

**Comment by Samara-Strauss** [comment]
Closing in favor of #3280
