### ISSUE TITLE
Design Feedback - Design intent Decision Tools - Find a VA Form - Add Relevance, Popularity Related To & PDF Instructions 

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#25513]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- See comments below for design notes

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by rtwell** [comment]
My only feedback is for the PDF interaction—i would keep it as simple as possible (aka mimic gov.uk's simplistic approach).

**Comment by callen2563** [comment]
I have updated the Related forms H tags. I have also created a new version of the PDF download mock that I think will help address the issue of users opening PDFs in the browser and forms fields not showing up as well as giving them a tool tip for PDF help that would link to a PDF help page with instructions on how to download acrobat etc. I have placed in simplified FPO copy as a placeholder and will work with content to fine tune. I also took a look at UK.gov but wasn't seeing a PDF example that addresses all the problems our users have been facing but let me know if you have additional thoughts. Cindy has started a research plan for this as well.

![FAF - Related Forms](https://user-images.githubusercontent.com/68560244/121961252-2c973580-cd35-11eb-96f0-e5d44b954da5.png)

![Find a Form - PDF Download desktop](https://user-images.githubusercontent.com/68560244/121961710-c2cb5b80-cd35-11eb-9102-1a200bffb1ea.png)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 @rtwell @sshein @zacharymorel @johnhashva @allison0034  Noting that the **PDF download instructions** part of this original review was de-scoped and moved into its own design ticket to be further fleshed out.  Please add any new feedback on that ticket. https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050
