### ISSUE TITLE
Design Feedback - Staging Review | Language Assistance and Resources | C&L Team

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#25511]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- No design feedback, good work!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
1. too much white space between the language header and the links
2. Missing the horizontal white rules

![Screen_Shot_2021-06-03_at_11_12_59_AM.png](https://images.zenhubusercontent.com/5d93fa1ea615ef00010992b0/885bedcf-0aa5-4cac-96a9-323f19fc24b3)

![Screen_Shot_2021-06-03_at_11_12_20_AM.png](https://images.zenhubusercontent.com/5d93fa1ea615ef00010992b0/34149aad-c874-4391-9b5a-08b77965b96a)

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by SKasimow** [comment]
@youngfreezyVA Hi Fareez - here is the feedback from Design. I believe the top most arrow pointing to the existing footer is work captured in our backlog here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23541

So changes for now would be to move the Language assistance (lower case) text closer to hyperlinks, add rules/white lines and remove '|" pipe after "Other languages".

Please point this.

**Comment by SKasimow** [comment]
Hi @allison0034 @rtwell: the extra "pipe" after "Other Languages" comes from a css rule that is globally applied. We have this change captured in the backlog ticket we hope to start working on soon:

- Remove the last | from "Veterans Portrait Project" so inline lists do not end in a |
- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23541

cc @DanielleThierryUSDSVA @youngfreezyVA
