### ISSUE TITLE
[Research] HCA Address Military Base Checkbox

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#25524]
## Description ##
We are uncertain as to where the value from [the checkbox](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18394) will be going. Back end research needs to be done to determine the value of this checkbox on the frontend.

**Comment by dat-gcio** [comment]
@tchrisdyer @kevinmirc Created this backend research ticket for the initiate research.

**Comment by tchrisdyer** [comment]
Moving out of Sprint 49 to gain additional info on the requirements.

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in over a year.  If work is needed, a new ticket will be created under an initiative
