### ISSUE TITLE
Access for [Curt Bonade]

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#25529]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Curt Bonade
- Please Provide your email.
   > curt.bonade@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Testing Tools Team, Software Engineer FE, Oddball

- Requesting SSH key authorization?
   > YES
   - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAr9c9DSc+fkZQ9ejJS9JmxkfF1pw3+yJEPqovejlAAM curt.bonade@gmail.com

- Grant AWS Console access?
  > NO
  - N/A

**Comment by tskinn** [comment]
@CBonade you key has been added and you should be able to connect now. Reach out in slack if you have issues.
