### ISSUE TITLE
Establish Best Bets for all VAMC & Vet Center Locations

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25534]
##  Description
Establish a best bet for all VAMC & Vet Centers Locations to improve veteran experience when searching for these locations

## Background/Context
Required information will be collected in #25532. Once it is ready we can proceed with plan to establish Best Bets for these va locations. 

## Acceptance Criteria
- [ ] John to meet with Dave Conlon to discuss the strategy going forward. Do we do it now manually or adopt an API strategy.
- [ ] Create a best bet for each VAMC and Vet Center Location

**Comment by denisecoveyduc** [comment]
Via slack discussion it was suggested that we look at a direct connection to CMS to scale this request.

It is populated by VAST data, making it a living/sustainable automated method of getting accurate/updated facility info. Which would also provide Benefit and Cemetery locations. At face value, CMS does not create a plain English Best Bet text description.

Dave Conlon can "see value in including locations in the best bets, but I don't think that the facilities team can realistically scale to manage several thousand of these ongoing nor necessarily wrangle over 1000 stakeholders. And the 'text description' we might want to figure out something that also scales that doesn't make perfect the enemy of good. (Because whatever the field supplies will likely not be Plain English).
And manual data calls fail."

Search Team :
- can provide specific guidance on the Plain language, character limitations, etc for the Best Bet description
- Determine what, if anything would be different than the guardrails for the metatags/what's in the meta information.
- Explore a way to establish a Best Bet API - All of the information is available out of Drupal so look to potentially connect to Drupal's API for the best bet rather than something manual. 
- As a short term solution, explore a CMS export or creation of graph QL Query  or other

**Comment by davidconlon** [comment]
This issue is untenable due to conflicting facility names (e.g. Springfield, Alexandria) as well as maintaining/curating thousands of best bets.
We should lean more into ensuring that these search terms are included as part of SEO to ensure high level of return on search.gov results themselves sans best bets.
