### ISSUE TITLE
Content Feedback - Midpoint review  - Authenticated Experience, Notification Preferences

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#25544]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback key
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

*

**Comment by peggygannon** [comment]
Hello, @ajakabcin @andaleliz content feedback from Midpoint Review. Just two things to consider. Thx! 

**Consider**

1. For this Introduction line:  We’ll use the contact information from your profile to send notifications: 

Consider giving user a little more detail about what type of VA information they'll receive notification for. (For example, in-progress applications, claims status, benefit payments, appointment, etc...) 


2. Consider making the notification on/off labels more plain language.

For example: 
On: text > Text notifications: on
On: email > Email notifications: on
Off> Notifications: off

**Comment by andaleliz** [comment]
Thanks for your feedback @peggygannon. 

>Consider giving user a little more detail about what type of VA information they'll receive notification for. (For example, in-progress applications, claims status, benefit payments, appointment, etc...)

At this point, I'd like to test with it being less verbose and see how it resonates with users. In the study we're running right now for facilities, multiple people have commented that they wish there was less text under the heading, stating that it was too much to read.  The list of possible notifications could be quite long.

 >Consider making the notification on/off labels more plain language.

I've updated the mock-up labels to `Notify by text` or `Notify by email` to be consistent with the checkbox labels, and see how that tests.  https://preview.uxpin.com/5ecec4de6ec34eddc9f095677a881be3646124ce#/pages/139049744/simulate/sitemap?mode=i
