### ISSUE TITLE
Messages not loading

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#25546]
### Issue
MHV implemented a pagination fix that is preventing messages from displaying in SM folders 

### Expected Behavior
Messages should display in all SM folders

**Comment by narin** [comment]
This is related to #21454.  PR in code review here: https://github.com/department-of-veterans-affairs/vets-api/pull/7080

**Comment by narin** [comment]
This issue was in SQA (Staging) only and has been resolved by the MHV team.  Closing out.
