### ISSUE TITLE
Claims & Health care: intermittent UI flashes before loading in data

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25540]
## What happened?
1. When navigating to the Claims & Appeals page for the first time, the following happens:
     - Page briefly displays the null state UI: "You don't have any submitted claims or appeals"
     - Page displays loading screen (correct)
     - Page displays Active claims/appeals (correct)

The app should only display the null state UI on this page if the user does not have any active claims/appeals. It should not display before the loading screen.

2. When navigating to the Health care page for the first time, the following happens:
     - Health care landing page flashes
     - Page displays loading screen (correct)
     - Page displays Health care landing page (correct)

The app should not intermittently display the Health care page before a loading screen. When navigating to this page, the app should display the loading screen until the page data has loaded.  

## Specs:
- Device: iPhone 11
- User: judy

## Steps to Reproduce
1. Log in with judy
2. Navigate to the Claims page
     - Notice how the app flashes a series of screens (null state, loading spinner) before settling on the active claims
4. Navigate to the Health care page. 
     - Notice how the app flashes a series of screens (Health care landing page, loading spinner) before settling back on the Health care landing page

## Desired behavior
1. Upon navigating to a page, if the data for that page has not yet loaded, the UI should display a loading screen until the data has loaded
2. The app should not display an intermittent screen before the loading screen

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - low

## Linked Story
n/a

## Screen shot(s) and additional information
Video includes intermittent flashes on Claims/Appeals and Health care: 

https://images.zenhubusercontent.com/133843125/01b64c0e-f413-4ce6-b342-c083902137a2/rpreplay_final1622656534.mov

**Comment by digitalken** [comment]
PASS 6/18/2021 - I see no flashing on Judy.  Closing.
