### ISSUE TITLE
Subtask:  Port SideNav to Design System 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2554]
**This is a subtask for the validation of new SideNav menu for Pittsburgh:**
Port to the deisng system (Formation) (Mostly jSCSS naming conventions) 

Relates to ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/2278 Implement new sidebar navigation on Pittsburgh health care

**Comment by kelsonic** [comment]
I put this ticket back in the Icebox since I think we should wait until the SideNav has a finalized design spec so as not to do this work twice! :)

**Comment by MickinSahni** [comment]
Blocked until designs are updated based on research

**Comment by caw310** [comment]
This is over 3 yrs old so closing.
