### ISSUE TITLE
Update "Need help?" footer on 10-10CG

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#25542]
## User Story

_As a user who needs help filling out the [online 10-10CG](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction), I want to understand what offline support is available to me
so that I can successfully submit my application._

## Expected Behavior

_The content of the 2nd paragraph of the footer has been updated for plain language_

## Acceptance Criteria

- [ ] _Update "Need help?" footer in production_

**Current footer**

![Screen Shot 2021-02-03 at 9.34.55 AM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/f92f5129-ecc8-474e-a017-628efdd283d9)

**Desired design**

![Screen Shot 2021-06-02 at 1.29.13 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/389e2bcb-7af5-467b-90c6-49fa1538529a)

**Desired content**
You can also call 855-488-8440 if you have questions about completing your application, or contact your local Caregiver Support Coordinator. 

## Resources
[Prototype](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666459/simulate/sitemap?mode=i)
[Content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/10-10CG-application-copy.md#apply-for-the-program-of-comprehensive-assistance-for-family-caregivers)
Original design ticket #[19446](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/19446)

**Comment by dat-gcio** [comment]
@Dene-human Here is the [review instance](http://30752fc89e82c7e71716b5dd00830000.review.vetsgov-internal/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)

**Comment by Dene-human** [comment]
Great thanks! Full disclosure, I only checked a couple of pages, but I assume it carries through everywhere.

**Comment by dat-gcio** [comment]
Validated in prod.
