### ISSUE TITLE
Update launcher icon

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25557]
## Acceptance Criteria
1. Update the launcher icon for the VA Mobile app
     - See comments for iOS app icon set
2. Android: 
     - redo adaptive icons
     - set ic_launcher_bg color to #003E73

**Comment by lexicalninja** [comment]
App icon set for iOS
[https://app.zenhub.com/files/133843125/1e2dac92-94b2-4d7e-8f32-2a751bf15f3c/download](https://app.zenhub.com/files/133843125/1e2dac92-94b2-4d7e-8f32-2a751bf15f3c/download)

Android needs to redo the adaptive icons and set the ic_launcher_bg color to `#003E73`

**Comment by digitalken** [comment]
PASS 6/18/2021 - Seems to be OK.  Closing.
