### ISSUE TITLE
Remove backend cheetah flag

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25555]
## Description
The cheetah/vaccine scheduling flow is live and moving to sustainment.

---
## Tasks
- [ ] Remove backend va_online_scheduling_cheetah flag

## Acceptance Criteria
- [ ] No changes in experience

**Comment by LeKeve** [comment]
@cferris32 PR removing the cheetah flag on the frontend has been merged and the backend PR can be merged once completed.
