### ISSUE TITLE
CT Redesign: Update search results card content and layout

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25559]
As a developer, I need to update the search results cards format and content to match the latest designs so that they can be usability tested in the sandbox.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. Each card has the following 4 or 5 sections:
    a. Type Header
    b. Name / Location / Ratings (if available)
    c. Caution Flags (if available)
    d. Tuition and Housing Benefit
    e. Institution Details (Accreditation, GI Bill Students, Approved programs, Program length)
    f. Compare

2. The Type Header identifies the type of institution:
    a. School
    b. Employer
    c. VET TEC

3. If an institution has a special mission, the special mission is displayed in the Type Header.  Special missions include:
    a. Single-gender school (Men-only, Women-only)
    b. Religious affiliation (Religious)
    c. Historically Black College or University (HBCU)

4. The name of the institution is a link to the institution profile page.

5. The format of the ratings information is: [star visual] **(X.X of 5) by XX Veterans**

6. VET TEC institution types display the preferred provider indicator below the ratings information.

7. The Caution Flag display:
    a. Is only displayed when an institution has a caution flag
    b. Initially displays the number of caution flags the institution has
    c. The user can view the specific type of caution flags at the institution.

8. The "Housing benefit" for Employer institution types has helper content

    >* Housing rate and the amount of entitlement used decrease every 6 months as employer pay increases

9. There is a new "Institution Details" section between the "Tuition and fees" section and the "Compare" section

10. The "Institution Details" section displays the following information based on institution type:
    a. School: Accreditation, GI Bill students
    b. Employer: Accreditation, GI Bill students
    c. VET TEC: Approved programs, Program length

11. In the Institution details section:
    a. When an institution has no GI Bill students, 0 is displayed.
    b. When there are multiple program lengths, it is displayed as min - max hours
    c. When there is a single program length, it is displayed as XXX hours
    d. When there is no program length, it is displayed as TBD hours

12. The view link is not displayed in the "Compare" section

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060313_Searchbyname_Desktop_2)

2. [Prototype - Caution flag display open](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060314_Searchbyname_Desktop_3_openwarning)

**Comment by elder-joseph** [comment]
Associate PRs:
`website`: https://github.com/department-of-veterans-affairs/vets-website/pull/17552
`gids`: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/830

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1934&group_by=cases:section_id&group_order=asc
