### ISSUE TITLE
Collaboration Cycle Kickoff [Public Website, ORDMI Harassment Reporting Tool]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25567]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/README.md)
- The Office of Resolution Management, Diversity and Inclusion (ORDMI) - https://www.va.gov/ORMDI/HPP.asp
- WIP Roadmap and Proposed Architecture - [Roadmap_Architecture Deck v1 SM.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6399894/Roadmap_Architecture.Deck.v1.SM.pdf)
- Proposed System Architecture of Front End Portal and Federated System (with new and existing platforms)
[example Federated Systems.pdf](https://github.com/department-of-veterans-affairs/digital-experience-products/files/6313817/example.Federated.Systems.pdf)
- Draft Business Requirements (Last updated 5/12/2021)
[REVISED 05_12_2021 Draft Business Requirements (2).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6511091/REVISED.05_12_2021.Draft.Business.Requirements.2.xlsx)
- ORDMI PIFs: VA Cultural Health Initiative
[DIVAC Harassment_4_22_final.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6511053/DIVAC.Harassment_4_22_final.pdf)
- ORDMI PIFs: Proposed Web to Datastore Flows
[05_13_2021 Flow.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6511058/05_13_2021.Flow.pdf)
- ORDMI PIFs: Proposed Service Design

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [x] New
- [ ] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [x] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [x] Yes (Type and Level of Research has not been determined but "Landscape Survey" was our initial thought process.
- [ ] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work include content changes for: (Select all that apply)
- [ ] Tools and applications*
- [ ] Static pages
- [x] This work doesn’t involve content changes. (New Content, no changes to existing content)

*For tools and applications, take into account if any content on static page entry points will need updates.

Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.

### 6. Are you making a change to the user flow?
- [x] Yes (Build a new form, not making changes to existing user flow)
- [ ] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 7. Are you making a change to urls, navigation, or entry points?
- [x] Yes
- [ ] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 8. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [x] Yes (Not yet determined, working to get this determined)
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 9. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @brianalloyd. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is a new tool and/or application so we are recommending the following Collaboration Cycle touchpoints:

- Design Intent
- Information Architecture (IA) Request
- Research Plan Review
- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

Also - looks like a lot of the artifacts you linked above did not attach correctly.

**Comment by brianalloyd** [comment]
Thanks @shiragoodman appreciate the quick follow up and much needed collab info.  Also, I updated ticket with new artifact links and am looking forward to work this with everyone.

**Comment by brianalloyd** [comment]
closing ticket in support.
