### ISSUE TITLE
IA Request [Healthcare Experience, Check-in]

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#25561]
## What this is:
Work with Platform Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kickoff ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
 - Phase 1 (MVP) is Check-in, also known as letting the VA know that you have arrived for your medical appointment a few minutes before the appointment is set to begin.
- Link to or attach prototype or mockups ([Full user journeys and wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/DPn2PMj/play) | [MVP Phase 1 only](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/WK4jvJ2/play))
- Link to or attach user/page flows
  - Most non-happy path scenarios (if we don't have a phone number on file, etc) will result in the Veteran seeing a screen directing them to check-in with a staff member.
- Link to or attach your content source of truth, including H1s (if separate from prototype/mockup)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
It shouldn't really be discoverable on va.gov. Veterans will access it via a text message. This feature will utilize a new authentication method, LoROTA. 

**What is LoROTA?**
Low Risk One Time Authentication, or LoROTA, is a simple service that uses a unique hash passed between a user and various services to authenticate that user for certain low risk activities, like form submission.

LoROTA does two things: 
- it receives information, generates a unique encrypted hash that represents the received information, and returns the hash to the caller
- it receives a hash, verifies that the hash is authentic, and returns the encrypted information to the caller

Applications that use LoROTA do so for two reasons. First, the uniqueness of a LoROTA hash can be used to verify that the a user moving between modalities (i.e. text message to web) is the same user. Second, the ability to encrypt information in the hash itself enables application to pass around sensitive information via open means (i.e. a URL parameter) without needing to create and store copies of the sensitive information in one or more places.

@stephenBarrs is a good contact for any other details about LoROTA.

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
Check-in, Health care, VA appointments

**URL(s)** - What are your suggested URLs and why?
Open to suggestions. Need to think through LoROTA implications. [LoROTA Diagram](https://dsva.slack.com/archives/C022AC2STBM/p1622663533267400?thread_ts=1622574985.234600&cid=C022AC2STBM)

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  
Text message.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
N/A

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?
N/A

I'm particularly interested in feedback on any impacts to the va.gov header and footer due to LoROTA as well as breadcrumb suggestions. Also, keep phase 2 scope, also known as Pre-check in ([draft wireframes](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/ZOdgYzp/play)), in the back of your mind when generating suggestions. Pre-check is a set of tasks that a Veteran needs to complete prior to their appointment (the Health Questionnaires feature will become a subset of Pre-check in). It will begin via a text message sent approximately a week prior to the appointment. If a Veteran doesn't complete their Pre-check in activities prior to Check-in (letting the VA know you have arrived for your appointment just a few minutes before the appointment is set to begin) a subset of the Pre-check in tasks may be added to the Check-in workflow. 

## Definition of Done
- [x] VFS: Creates issue and provides all required information above
- [x] Platform: Completes final IA feedback/recommendation
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [x] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
@kristenmcconnell Draft IA info is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-appt-check-in.md

I'm going to review this early next week again, but feel free to take a look at and let me know if you have any questions or thoughts.  Its relatively straight forward.

**Comment by kristenmcconnell** [comment]
I'm back from vacation and reviewing this now. It looks pretty good for Phase 1 (also talked about as pre-MVP). 

I'm thinking through the URL that you recommended (www.va.gov/health-care/appointment-check-in/). We are envisioning a future where people can check-in for walk-in appointments (lab tests, etc). I guess that we can still consider that an appointment too. Just debating .../health-care/appointment-check-in versus .../health-care/check-in.

Since we ask about updates to insurance, contact, and other information, thoughts on the URL being .../update-information instead of the suggested .../insurance.

I wanted to clarify one thing that you have marked down in the meeting notes section for Phase 1. You have "If they want to do anything else they will need to log in." For Phase 1, we will actually be directing them to staff to complete anything else besides letting the VA know that they arrived.

cc @jparker0425 @mdewey @batemapf for knowledge/feedback.

**Comment by mnorthuis** [comment]
@kristenmcconnell Thanks for the responses!

- For the URL, I'm inclined to stick with including "appointment" in the URL for specificity...ultimately they are checking in for some sort of appointment. 
- I'm fine with whatever you feel is accurate for the sub-pages.  I was thinking there was a page that was only for insurance, so that is why I suggested that.  If it is combined with other information, then you can modify that to be more broad. 
- For the comment in the phase 1 notes, that was in reference to this check-in page having a full header and footer, so if they clicked on a link to go to another authenticated task, or a link was provided to view the appointment details, they would need to fully authenticate to do that.  Basically its saying that LaROTA is only identifying them for the check-in, any other tasks that they  navigate to would potentially need full auth.

**Comment by kristenmcconnell** [comment]
Sounds good to me. So, the only change is the URL being .../update-information instead of the suggested .../insurance.

**Comment by mdewey** [comment]
Hey @mnorthuis  

I have a question about the URL structure. 

We need to have a token in the URL. This token is coming from LoROTA and used to guide the current session. 

Currently, we have the token as part of the URL (for example `check-in/some-token/check-in`). 

For the new URLs, where should the token go? Should we keep it as part of the URL? Should it be a query parameter for only a few pages? 

I didn't see a reference to the token in the threads. 

Thoughts?

**Comment by mdewey** [comment]
The MUSTS have been addressed (new URLs and meta tags for restricting search) are in staging. With a sample URL being 

https://staging.va.gov/health-care/appointment-check-in/?id=46bebc0a-b99c-464f-a5c5-560bc9eae287

**Comment by mnorthuis** [comment]
IA recommendations were complete on 6/22.  You can close this ticket whenever you are ready.  Please reach out if there's anything additional you would like to discuss.  Thanks!
