### ISSUE TITLE
Build report for SSO / Non SSO login to portal

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25576]
- [x] add sync system additional field " login type" for table "login"
- [x] bi report

**Comment by kjduensing** [comment]
For the adding the login type to the login table, make sure the data is retroactive to January 2021 (Shane may be able to help do this manually)

**Comment by Kennon-git** [comment]
retroactive data is not needed - ready for work

**Comment by Kennon-git** [comment]
andy added field - justin to generate report
