### ISSUE TITLE
Content Request from Decision Tools team for Find a VA Form PDF download instructions & sort option

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25578]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[X] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?
- ~~We need to know what word(s) to add to an existing sort feature to allow the user to sort by popularity (e.g., "popularity", "most popular", "most downloaded", etc.)~~ Edit 6/8/2021 - this part is no longer needed; the popularity data is just being used behind the scenes to enhance/weight the relevance logic.
- We also need verbiage to give users information on downloading a PDF form. The design intent for the PDF download work can be found in issue #25247  
     - As more and more VA forms are created/updated using dynamic XFA, they can no longer be filled out (and sometimes cannot even be opened) in a web browser.   The VA has no plans to change their use of dynamic XFA in the foreseeable future, so we need to provide users with information telling them to download the form locally.  
     - As detailed in #25247, the process for downloading is dependent on a number of different factors.

## When does this content work need to be done?
- By June 21

*In addition to the date you need this content work to be done, please let us know the ETA for the app/tool launch.*  June 29

## Do you plan to bring this to an upcoming content office hours session? 

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [X] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET) I will attend on June 7
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Decision Tools
-	OCTO-DE product owner:  John Hashimoto
-	Product manager:  Marci McGuire
-	Designer:  Cassandra Allen
-	FE engineer:  Zach Morel
-	Product/team Slack channel: vsa-decision-tools

## Links to related tickets

*Please include here a link to the epic, or other relevant tickets, for this product work.*   

- Epic for all work in this release: #21639
- Design intent for PDF instructions: #25247
- Find a VA Form search results with sort feature & PDF links:  https://www.va.gov/find-forms/?q=
- Example Find a VA Form detail page with PDF links:  https://www.va.gov/find-forms/about-form-10-10ez/

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by MarciMcGuireGCIO** [comment]
Updated request to remove need for text to use in order to sort by popularity.

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO Do you still want to talk about content needs for this? We can set aside time this week...

**Comment by MarciMcGuireGCIO** [comment]
Hi @bethpottsVADEPO , yes, that would be great.  If you want to send me a couple of times that work for you I will schedule a meeting.  Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO - will you be at the design intent at 2:00 this afternoon?  If so, that directly relates to this request.

**Comment by RLHecht** [comment]
For awareness: @shiragoodman @peggygannon @mnorthuis

**Comment by callen2563** [comment]
@bethpotts Hi Beth, it looks like we are now pushing testing for this out a few weeks so I'm going to hold off on uploading the updated design here until it's gone through the design review/approval process. Thanks for your help!

**Comment by bethpottsVADEPO** [comment]
@callen2563 OK, let me know when you'd like my input!

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 and @bethpottsVADEPO  - looks like you both collaborated on the design ticket for this, so am I good to close this one?  Thanks!

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO I believe so. Do you have everything you need, @callen2563?

**Comment by MarciMcGuireGCIO** [comment]
Closing this since design intent review is scheduled.  If any new content needs come out of that, I'll open a new ticket.
