### ISSUE TITLE
DISCOVERY | Use of Graph QL | Translation Recommendation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25577]
Spike ticket to: investigate the feasibility of using graphql queries to return translated content from the cms when passing a lang code ( en | tl | es) to a graphql query

**Comment by youngfreezyVA** [comment]
@SKasimow you stated that this approach wouldn't work based on our requirements. Please provide those requirements in this thread, and we can also adapt/modify this ticket for the API sandbox work, once you are able to groom / gather those requirements from @Yuffster-usds.
