### ISSUE TITLE
Find a VA Form: Implement "download PDF" instructions on search results

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25571]
## User Story

As a Veteran or Veteran's caregiver/representative, I want to know that I need to download a PDF locally rather than attempt to open/view in my browser so that I don't waste time attempting to open a form not supported by a web browser

## Expected Behavior

Implement the final PDF download instruction design in search results ~and on form detailed pages~ as documented in design issue #25247 and as mocked up in issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050#issuecomment-877449047.

## Acceptance Criteria

- [ ] PDF instructions are implemented in search results based on [mockup](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050#issuecomment-877449047)
- [ ] Change is tested and promoted to Staging for user testing.

**7/12/2021 - mock-up has been modified from original. @zacharymorel - let's just implement on the Search page for user testing, and hold off adding to the detail pages until we determine if  changes are required.**

**Comment by MarciMcGuireGCIO** [comment]
This has been de-scoped from the July 6 release as we want to do some further exploration and research.

**Comment by MarciMcGuireGCIO** [comment]
Blocked pending Cassandra fleshing out the options for PDF download instructions

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel - if you have a min, can you estimate what it will require to add Cassandra's PDF instructions on the search and detail pages?

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO It is this, https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050#issuecomment-867038171, yes?

**Comment by MarciMcGuireGCIO** [comment]
> @MarciMcGuireGCIO It is this, [#26050 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050#issuecomment-867038171), yes?  
Yep!  That's the one!

> Also, I am wondering what the url is for link, **Get instructions for opening the PDF form in Acrobat Reader**.
The URL is https://www.va.gov/resources/what-if-im-having-trouble-opening-a-pdf

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I went ahead and pulled this into the sprint because you looked a little slim on points.  If there's a lot of rework from the design intent, we can grab something else from the backlog instead.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel it is not.  I will remove. Good catch!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This is the work that will be on staging only so the research can be done for it? 
See => https://github.com/department-of-veterans-affairs/va.gov-team/issues/25924

**Comment by MarciMcGuireGCIO** [comment]
> @MarciMcGuireGCIO This is the work that will be on staging only so the research can be done for it?
> See => #25924

I'm sorry, @zacharymorel  -- I must have overlooked this.  You're correct; this is the work that will be on staging only for the research study.

**Comment by MarciMcGuireGCIO** [comment]
Per Ryan's comment and our discussion in Backlog Grooming, @callen2563 is going to update the [mockup](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26050) so that it is an [informational alert](https://design.va.gov/components/alertboxes#informational-alert) in the Design System.

**Comment by zacharymorel** [comment]
@callen2563 @MarciMcGuireGCIO https://staging.va.gov/find-forms/?q=health

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel in the mockup it looks like the gray box is aligned with the rest of the page content.  For some reason when I look at it on Staging in Chrome, the gray box is flowing all the way to the edge of the page. 

![image](https://user-images.githubusercontent.com/73354907/125308409-e070ee00-e2fe-11eb-82ff-e4b5f9d10642.png)

**Comment by zacharymorel** [comment]
Ha weird, well then, I shall revisit it.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel !

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Recheck it on Chrome!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Thank you! It looks like the mock-up now.

**Comment by MarciMcGuireGCIO** [comment]
Closing this issue; will open a new one specific to adding the A/B versions per our conversation on 7/13/2021
