### ISSUE TITLE
[NOV 2021] SQL Server upgrade

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#25585]
- [ ] Andy to put in EWR request

- needs to happen before the end of the year - better earlier than later

- Need to see if we need to get our own sql server. We need access to the local file system, we need to schedule ssis packages, will cause issues if we’re on a consolidated system
- It’s the OS on the server with the upgrade of the os you’ll need to upgrade sql. 
- There will be some positive benefits but there shouldn’t be any negative effects.

**Comment by Kennon-git** [comment]
ewr request put in - meeting on friday.

**Comment by kjduensing** [comment]
plan to put sql server in sacramento rdc

**Comment by kjduensing** [comment]
have to build the server before we can do anything.
