### ISSUE TITLE
Sign Out confirmation alert persists when navigating away from Profile

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25586]
## What happened?
On the Profile page, when the confirmation alert for Sign Out is triggered, the alert persists when navigating away and back to the page.

## Specs:
- Device: Android and iOS

## Steps to Reproduce
1. Navigate to the Profile page
2. Select the Sign Out button to trigger the confirmation alert: "Are you sure you want to sign out?" 
3. From the bottom nav bar, navigate to a different page (ex: Home)
4. Navigate back to the Profile page
5. Observe now the confirmation alert still displays

## Desired behavior
The confirmation alert should be dismissed when navigating away from the page.

Note: the following parts of the app do this correctly:
- Settings: Sign Out
- Contact Info: Delete Address/Phone/Email

## Acceptance Criteria
1. Confirmation alert should be dismissed when navigating away from the page
     - When navigating back to the page, the Sign Out button should display in lieu of the alert

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information

https://images.zenhubusercontent.com/133843125/8c863b1f-2852-49f2-a4e1-18decbe1fd58/image_from_ios__2_.mp4

**Comment by digitalken** [comment]
PASS 6/17/2021 - Navigating away causes the confirmation to be gone upon returning.  Closing.
