### ISSUE TITLE
Access for Joseph Niquette

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#25587]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Joseph Niquette
- Please Provide your email.
   > joe.niquette@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Identity team within VSP. I am a Sr. Security Engineer at Oddball.

- Grant AWS Console access?
  > YES
  - Need additional access please. I would like to have access for AWS Cognito added to my permissions. I will require write permissions to be able to test out a concept for identity related ideas.
  - I will be working with @bramleyjl @bosawt @jimiray , please expect a request from them for this access as well. Once we have things operational (if we do) then we will ask for the permissions to be reduced to ensure only proper access is being used. 

Thank you for your assistance!

**Comment by tskinn** [comment]
@joeniquette can you confirm you have adequate permission now?

**Comment by joeniquette** [comment]
Yes everything is working as expected, thank you so much!!
