### ISSUE TITLE
508-defect-2 [sitewide, SCREENREADER]: On smaller screen widths and mobile, the footer's "language assistance" is not a heading

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#25594]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user, I want to be able to navigate by headings to access important sections on a page like language assistance. 

## Details

The footer's `h2`s are removed when they are converted into accordions on smaller screen widths. This creates an unequal experience for mobile screen reader users as discovering important content within the footer will be more difficult without key headings.

## Acceptance Criteria

- [ ] Footer `h2`s are not removed when converted into accordions

## Steps to Recreate

1. Shrink the page size until the footer `h2`s collapse into accordions.
2. Confirm using headingsMap that the headings disappear.

## Proposed Solution (if known)

Place the accordion button within an `h2`

## WCAG or Vendor Guidance (optional)

https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

## Screenshots or Trace Logs

<img width="1010" alt="Screen Shot 2021-06-03 at 9 40 41 AM" src="https://user-images.githubusercontent.com/14154792/120654667-e944e900-c44f-11eb-9baf-ae059d668d0c.png">
<img width="829" alt="Screen Shot 2021-06-03 at 9 41 19 AM" src="https://user-images.githubusercontent.com/14154792/120654668-e944e900-c44f-11eb-92b5-a05f9f17d2dc.png">

**Comment by laflannery** [comment]
Language Assistance accordion button is now an H2 on mobile.  Will close in 1 week unless told otherwise
