### ISSUE TITLE
VVC @Home Need to Make Changes Not Showing Facility Phone Number

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25598]
1.  Go into VCM and make an Atlas and a regular VVC appts for Judy Morrison.
2.  Log into VAOS s Judy Morrison 
3.  On upcoming appt find those two appts and view details. 
4.  Actual Response:  The 'Need to Make Changes' for Atlas shows the Facility and facility phone number. The "Need to Make Changes' for VVC at home shows the Facility.  
5. Expected Response:  VVC at home should display like Atlas and how the Facility and facility phone number.  ![VVC_AtHome_NeedToMakeChanges_NoFacilityPhone.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/44ab7923-2783-4ad1-8d77-445f21263a1c)

**Comment by beth-wodzinski** [comment]
Verified the fix.
