### ISSUE TITLE
Collaboration Cycle Kickoff : Search & Discovery - Search UI Consistency Pattern for Global Search Pages

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#25596]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts 
Search UI Consistency has already been through the collab cycle as part of a joint venture with Decision tools and public websites. This is now for the Search & Discovery team to implement the UI Design Pattern changes on the global pages. 
-  [Product outline- Search UI Consistency](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/search-ui-consistency/product-outline.md)
- [Invision Link - Showing Global Search Pages](https://vsateams.invisionapp.com/console/share/SD10IE31CENR/614352925)
- [Spreadsheet - Outlining Design Elements](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit#gid=0)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [x] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [x] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [ ] Yes
- [x] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work include content changes for: (Select all that apply)
- [ ] Tools and applications*
- [ ] Static pages
- [x] This work doesn’t involve content changes.

*For tools and applications, take into account if any content on static page entry points will need updates.

Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.

### 6. Are you making a change to the user flow?
- [ ] Yes
- [x] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 7. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 8. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [ ] Yes
- [x] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 9. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @denisecoveyduc. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: (delete Post Launch if there are no touchpoints in this area)

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

We are not recommending a Design Intent since your team was able to participate in the [Decision Tools - Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22885) on 4/20/21. Please be sure to review feedback provided in that ticket. Let us know if you have any questions.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Quality Assurance (QA)
- Accessibility
- Product


We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the Platform Collaboration Point Tracker (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by mnorthuis** [comment]
@denisecoveyduc Although an IA request is not needed for this, if you need any assistance or support in this work from a user flow, page structure and breadcrumb perspective, please reach out.  Each of the search tools on the site has been implemented in its own way over the years, and I would love to help in getting consistency in not just how they look, but also how they flow and function.  Thanks!

**Comment by denisecoveyduc** [comment]
@shiragoodman I just realized that I answered question #8 incorrectly. We do have some onsite search metrics through google analytics. Does this change the need for an analytics review?

**Comment by shiragoodman** [comment]
@denisecoveyduc are the current search metrics through GA sufficient or would you want to modify them to support this change?

**Comment by denisecoveyduc** [comment]
@shiragoodman GA is sufficient at the moment

**Comment by shiragoodman** [comment]
thanks @denisecoveyduc . With that in mind, we're no longer recommending an Analytics Request. I've updated my comment and will update the tracker.

**Comment by denisecoveyduc** [comment]
Hi @shiragoodman , Thanks for the quick sync today. Just to recap and document here is a quick recap of what we discussed. Let me know if any further clarification is needed.  

- **Midpoint review:** Is not required given that no user testing is happening, and we are near ready for launch. 

- **Contact Center Review:** Although we don’t think a full review is required for this effort. I will follow up to see if a product guide exists for onsite search and if anything is required. 

 - **Staging Review:** I will be creating the staging review request soon and I will share the review instance for the team’s review.

 - **Privacy and Security Review:** will also leverage the review instance.

**Comment by shiragoodman** [comment]
sounds good, Denise! Thanks for checking in.

**Comment by denisecoveyduc** [comment]
Hi @shiragoodman, just for tracking purposes I wanted to let you know that @jwoodman5 and I met today regarding the contact center review and at the moment there are no further actions for this initiative.
