### ISSUE TITLE
Atlas Appointments Not Displaying Provider Information

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25601]
On the  VVC at home details page, the provider information displays.  

Whereas on Atlas appointments provider name for Atlas is not displaying.  I verified that provider name is in the response body for Atlas appointments.   ![AtlasProviderInfoNotDisplayed.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/9a66f8fc-2f80-415c-89e5-933c3384490d)

**Comment by beth-wodzinski** [comment]
Verified the fix.
