### ISSUE TITLE
Extra space between sentences

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25603]
## What happened?
Running list of screens where there is >1 space between sentences in the same paragraph:

1. On the Generic Error alert, there is an extra space between the following text: "end.   Try"
2. On the SM unenrolled screen ("You're not currently enrolled to use Secure Messaging"), there is an extra space between the following text: "need.  It"
3. On the SM Terms & Conditions screen, there is an extra space between the following text: "need.  It"

## Specs:
- Device: iPhone 11
- #1 - User: +226 > claims detail
- #2 - User: +1401 > Messages
- #3 - User: +1404 > Messages

## Acceptance Criteria
1. Sentences in the same paragraph are separated by a single space 

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Image from iOS (10).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5257cda9-20c0-47e2-bb69-e9f16bf5aa94)
![Image from iOS (11).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/599a5fbc-ea0e-4c66-9e99-f783865dc6b5)
![Image from iOS (12).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/92510714-ea40-4590-b6eb-062c02c620cb)

**Comment by digitalken** [comment]
PASS 6/17/2021 - Looks good.  Closing.
