### ISSUE TITLE
Access for Michael Pritchard

### ISSUE THREAD

**Issue by thepipster** [department-of-veterans-affairs/va.gov-team#25615]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   N/A (I'm a fed, product owner on the platform leadership team)
- Please provide your name.
   Michael Pritchard
- Please Provide your email.
   michael.pritchard1@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   Platform leadership

- Requesting SSH key authorization?
   YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC26hQmoTAIbPedNzn/B3lI00Y4asvniUWAJn9oK7TJJ+VviYrnFQ9tpvTmhlCVbrrbKsGy+5LVG9OyEVDs3qqiUSzkfkDCzux6iD2QtL14IqAmkGlVEyaHw7t7Y7Ahxd6pW+0dRboi42y5sg7peAQpBA7c8l4FCX6EcJ+wCxJrfLfrjPn0S5zps3UA1LHsr5XzL9edooFFwCQFZFwe+cqIuE/PryQVrDRkxHp18vca3IJrStM7jNsofRxLal24l+Bg0V/jI/vRiaN0Q8caPnImSfskOyXThqUJl5MCe1i7hYHxO75B9Q0OU9kH3DgYhDHLgg/Iz8QLrEDBOBirpZico8AMp71ZYRr5iQ4Ci8YMMxnNRMX9Smmtk+g07M5CDb3kZRd/NMdAFAqNuy9dxvWMVdBPJQ08G/oMEHftJhpuuxOYpr9TG2yyNQH5SIsuwf2I1wfHMm85uJ7RQKzGiFjl4ER16FsqJC6mDEv7oiuzSZRohgGguxAZvE46qaG4YNdswPuXsUAAyzaCQ6gdaD5Zck62lQVXW8+ivwXoi8ii2StV4oD/a+HuXPvqcuAicVIEdNf/vWCDk1Ls7j3DcejNm3+6AgftCelUmZk0T3L87iABwNCeoGEO55gGjqEGwMmvtNzBlLPRR1d1bOZLwmXXycCcLMVDPu7rHiL2Ii3huw== mike@arsenicsoup.com
```

- Grant AWS Console access?
   NO (I already have access)

**Comment by tskinn** [comment]
@thepipster your key has been added and you should be able to connect now. Reach out in slack if you have any issues.
