### ISSUE TITLE
Validate Drupal Templates & Components Have Language Attributes Set

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25619]
This is to request a list of all frequently used Drupal templates/components that have or will be used for translated content so that Eng can check and confirm they are all set up to avail themselves to the lang attributes via Redux.

[ ] Danielle to provide list of most frequently used drip templates and components used for content and translations
[ ] Fareez to check and confirm each is able to leverage the language attribute in Redux

**Comment by youngfreezyVA** [comment]
looks good, when i was making a change earlier today, i realized that b/c i used local storage (a web store api) the lang code is available everywhere for sure

**Comment by SKasimow** [comment]
@youngfreezyVA so we won't need @DanielleThierryUSDSVA to provide a list? What/where does the "global" setting reside that tells a screenreader to read out everything in-language? Just want to be sure that if editors add stuff it auto-magically picks up the fact that it is a translated page...Thanks, Sharon

**Comment by youngfreezyVA** [comment]
that global setting resides in `localStorage` and `redux` and is currently being read by the `#content` div as well as all links on a page.

so as of right now, if an editor adds a link anywhere on the page it will automatically have the appropriate language code. the parent `content` div also has the appropriate language code. i think that covers all the places that we'd need the language code, right @joshkimux? 

but regardless a running list of templates (that we can keep updating) that we've used or are planning on using for i18 work would be super helpful.

in this case when i'm referring to templates i mean the templates here:
https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/includes 
or here:
https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/layouts

**Comment by SKasimow** [comment]
Thanks - that's helpful

cc @DanielleThierryUSDSVA

**Comment by joshkimux** [comment]
@youngfreezyVA that sounds good!

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA hi -can you provide the top templates we're likely to use so @fareez can verify there won't be any issues re lang attribute settings?

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow @youngfreezyVA Right now, I would say:

- basic_landing_page.drupal.liquid
- landing_page.drupal.liquid
- page-breadcrumbs.html
- page-react.html
- page.drupal.liquid.
- page.html
- va-form.drupal.liquid
- alerts.drupal.liquid
- benefit-hubs-links.drupal.liquid
- breadcrumbs.drupal.liquid
- breadcrumbs.html
- date.drupal.liquid
- detail-page.html
- footer.html
- metatags.drupal.liquid
- last-updated.drupal.liquid
- metatags.liquid
- related-information.drupal.liquid
- survey-tools.html *if this is for the medallia survey - not sure*
