### ISSUE TITLE
Turn off default watch behavior in vets-website for opening browser window

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25614]
## Details 

[Slack thread 1](https://dsva.slack.com/archives/CBU0KDSB1/p1622061755124700)
[Slack thread 2](https://dsva.slack.com/archives/C5HP4GN3F/p1622665753105800)

## Definition of Done 

- [x] Change default behavior of the watch command in vets-website so that it does not open a new browser window
- [x] Add documentation to our getting started page about Webpack dev server (and link to their developer docs)
- [x] Announce change in #vfs-frontend and cross post in relevant channels

**Comment by timwright12** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17490

**Comment by timwright12** [comment]
Documentation PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/633

**Comment by timwright12** [comment]
Slack announcement https://dsva.slack.com/archives/C5HP4GN3F/p1622754900119100
