### ISSUE TITLE
Tech Debt | Language Assistance Project

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25618]
## Lang Attributes Code Clean-up

[ ] Remove old code used to set languages from new pages to avoid future conflicts or confusion
[ ] Determine whether to modify existing logic used for Covid/Corona translated pages to new logic or leave as-is

**Comment by youngfreezyVA** [comment]
hi @SKasimow this looks good. i'd imagine for now i can remove just the parts that can be replaced with the new redux based approach.

I think all I need to do is take the lang setting logic out of the `content-build` repo, and move it to a hook inside the language switcher component in the `vets-website` repo. 

i'm buffering from 5 to 8 just in case this isn't as simple as above and might involve non-technical insight.
