### ISSUE TITLE
Request access to Google Analytics and/or Domo - Mike P

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#25627]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `@platform-analytics` to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo
- [x] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
June

## Product Team / External Team / VA Office
OCTODE leadership/Platform

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by JasonTheBearded** [comment]
BigQuery access set up.

**Comment by joanneesteban** [comment]
Set up with Domo.

**Comment by joanneesteban** [comment]
@bsmartin-ep can you grant Mike read-only access to GTM?

**Comment by bsmartin-ep** [comment]
GA and GTM acccess have been granted to Mike, @joanneesteban .

**Comment by joanneesteban** [comment]
Thanks, @JasonTheBearded & @bsmartin-ep ! Closing this ticket.
