### ISSUE TITLE
Schedule appointments page COVID-19 updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25624]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[x] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[ ] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

Following a pilot of vaccine scheduling in VAOS, it will be opening up to all facilities to enable online scheduling for the COVID-19 vaccine. The vaccine will be included in the VAOS sustainment flow as any other type of care so the statement on the static page will no longer be true.

![www.va.gov_health-care_schedule-view-va-appointments_covid note.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/a55ae55f-8319-4190-a341-43997358551e)

## When does this content work need to be done?

Mid-late June

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VAOS
-	OCTO-DE product owner: @lalexanderson-dsva 
-	Product manager: @laurenernest 
-	Designer: @outerpress 
-	FE engineer: @jbalboni 
-	Product/team Slack channel: #vaos-team

## Links to related tickets

VAOS vaccine epic #23506

**Comment by RLHecht** [comment]
@laurenernest Just confirming that the only ask removing that note from the page.

**Comment by laurenernest** [comment]
Correct! I don't believe there's any other vaccine content on that page. 

Also ensuring the last updated date reflects the change too.

**Comment by RLHecht** [comment]
Perfect! You mean the date that shows at the bottom of the page? Anytime we publish a revision of a page that date will change so whatever date you want us to remove it, that will be the date that shows once it's published.

**Comment by laurenernest** [comment]
Yep, that date on the bottom of the page. It didn't update automatically before so just wanted to make sure :) It might've been where the last change was made. #18500 Thanks!

**Comment by RLHecht** [comment]
Ah yeah, if the content isn't in Drupal then that updated date won't change. If you can just give me a heads up for when you want us to remove and publish it that would be great. It's an easy lift so can be done that day, but I just don't want it to get lost and forgotten about.

**Comment by RLHecht** [comment]
For awareness: @shiragoodman @peggygannon @mnorthuis

**Comment by laurenernest** [comment]
@RLHecht Good to remove the note. Thanks!

**Comment by RLHecht** [comment]
@laurenernest I removed the note and published the page. It should be live on the site within the hour as long as there are no issues with the deploy.

**Comment by laurenernest** [comment]
I see the change. Good to close ticket on my end.

**Comment by RLHecht** [comment]
work completed. Closing ticket.
