### ISSUE TITLE
KPI update schedule and drill path plan

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#25630]
## Issue Description
Domo does not handle incomplete periods well, comparing the most current incomplete week to the previous Sunday to Saturday period. Previously, the Analytics team had discussed pulling the data once a week for the standard KPI dashboards, as data was not planned to be shown in units smaller than a week. However, this does not mirror our users' experience on GA or other platforms, where they can see a dynamic "Last X Days" and could impact the usefulness of the product.

We already have a [quick fix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-creating-pop-gauges.md) for correcting the percent-change comparisons for the many multi-value gauges on the dashboard. However, we may need to brainstorm a new solution for the drill path cards for each of these gauges. These step-line charts face the same issues when Domo groups by week, but hard coding for dynamic 7-day groups isn't feasible for this time scale. If we were to update the gauges but not the drill path charts, the trends may look drastically different and undermine trust in the data.

If we plan on updating the dashboard daily, we'll need to find the best way to rethink the way data is shown on drill downs. The best way might be to show a rolling 7-day average at the day-level. However, I'm not sure whether this would be easiest to approach through Domo dataset views, a new ETL, or Beast Modes given where other fields are currently being calculated.

---
## Tasks
- [x] Decide whether to pull data daily vs. weekly and how to approach drill path charts.
(n/a) Create views for current datasets with grouping field and reconfigure gauges.
(n/a) Implement drill path data solution across all 2nd-tier charts.

## Acceptance Criteria
- [x] Date grouping applied uniformly across dashboard and explained clearly in supporting documentation (if needed).

**Comment by JasonTheBearded** [comment]
Discussed with @chloedotbrown and a weekly refresh schedule for the standardized dashboards seems the best path forward. If users want to see a day by day breakdown, then I believe we should direct them towards GA.

**Comment by joanneesteban** [comment]
All set to switch to the weekly refresh schedule!

**Comment by chloedotbrown** [comment]
Closing out this ticket, since issue was resolved over the summer.
