### ISSUE TITLE
NOD: Use mobile phone with home phone fallback

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#25643]
## Description

The Notice of Disagreement form can not be submitted without a phone number. It currently uses only the home phone from the Veteran's profile. We should instead check the mobile number first and if it doesn't exist, fall back to the home phone.

## Tasks

- [ ] Mobile phone first with home phone fallback

## Definition of done

- [ ] Either the mobile or home phone will be shown on the NOD contact page

**Comment by annaswims** [comment]
Thank you! That's one part... but if a veteran is not homeless then Lighthouse will not accept the NOD without a phone number.

**Comment by Mottie** [comment]
Not sure what to do about the homeless Veteran not having a contact number...
