### ISSUE TITLE
Find a VA Form: Remove "search results" from H1 on desktop and mobile

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25640]
## User Story

After investigation, our FE engineer has determined that having a dynamic page title where the words "search results" are added to "Find a VA Form" is currently not feasible because the title comes from the CMS and does not have any awareness of state (when the results are displayed) .   The mockups for the mobile and desktop need to be updated to remove those words so they will match in QA testing.

Sketches 
[Search tools - UI consistency mobile](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4)
[Search tools - UI consistency desktop](https://vsateams.invisionapp.com/share/SD10IE31CENR)

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by callen2563** [comment]
@Marci Let me know if this is what you meant. Thanks! :) 

![Find a Form - mobile](https://user-images.githubusercontent.com/68560244/121957653-b395df00-cd30-11eb-9609-0860b2b39c89.png)
![Find a Form - desktop](https://user-images.githubusercontent.com/68560244/121957739-ce685380-cd30-11eb-87a4-2336502f378c.png)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 yes, that is exactly it. Thanks!  Can you make the same update in the Sketch files so I can send those links to Tze?  Thx!!
