### ISSUE TITLE
Accessibility Feedback for Midpoint Review [Authenticated Experience, Preferred Facilities]

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#25642]
# Accessibility Feedback for Midpoint Review [Authenticated Experience, Preferred Facilities]

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Consider
- Split the descriptive text about the order away from the legend itself. This will help reduce verbosity for screen reader users and should make it easier to read for folks with cognitive disabilities. We could alternatively remove the order instructions entirely if they don't need to be duplicated-- but I'd be curious on how that tests with screen reader users and people with cognitive disabilities who may have memory challenges.

![image](https://user-images.githubusercontent.com/14154792/120810933-7a33c700-c519-11eb-8c50-9a40fe201ba5.png)

- Making the read-only view of facilities present as a visual list, with bullet points. We will need to add a role="list" on the UL if it stays a non-decorated list. A reviewer had some difficulty reading these as individual items, and had to really slow down and concentrate.

**Comment by andaleliz** [comment]
I don't think we'll build this section of profile, but added MHV discovery as a blocker in case we learn something that suggests we do need this. If we move forward, we'll still need this ticket.

**Comment by andaleliz** [comment]
Closing this out, per Kevin we are putting this work on ice.
