### ISSUE TITLE
CT Redesign:  Comparison Testing - Research Workshop

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#25653]
DONE: Research workshop is held & tasks are complete

TASKS:
Identify target participants
Establish goals for testing effort
Identify themes for conversations (discussion guide building blocks)

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1622144415771/0b486e7f9235eff44f637e7ec10b518f010e998e
