### ISSUE TITLE
Add support for env.api command line flag to yarn preview

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#25656]
When running the preview server locally, we often need to hit an API other than localhost:3000.

The only way to do this currently is to modify src/site/constants/environments-configs.js.

The preview server should support the env.api command line flag so we don't have to do this. 

### Current behavior

```
❯ yarn preview --env.api https://dev-api.va.gov
yarn run v1.22.4
$ node script/preview.js --env.api https://dev-api.va.gov
/Users/michaelpelz-sherman/source/content-build/node_modules/command-line-args/src/lib/argv.js:91
  throw err
  ^

UNKNOWN_OPTION: Unknown option: --env.api
    at halt (/Users/michaelpelz-sherman/source/content-build/node_modules/command-line-args/src/lib/argv.js:89:15)
    at Argv.validate (/Users/michaelpelz-sherman/source/content-build/node_modules/command-line-args/src/lib/argv.js:80:7)
    at commandLineArgs (/Users/michaelpelz-sherman/source/content-build/node_modules/command-line-args/src/lib/command-line-args.js:42:8)
    at Object.<anonymous> (/Users/michaelpelz-sherman/source/content-build/script/preview.js:71:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

### Desired behavior
Running `yarn preview --env.api https://dev-api.va.gov` points all API calls to https://dev-api.va.gov (or whatever env.api is set to).

**Comment by theodur** [comment]
@mpelzsherman Aren't the API calls dependent on the `vets-website`'s local build rather than the preview server? Which all you'd need to do is run `yarn build --api=https://dev-api.va.gov` in the `vets-website` directory before running the preview server.

**Comment by mpelzsherman** [comment]
Nope.

First, I think you mean `yarn build --env.api=https://dev-api.va.gov`.

I tried what you suggested, but when I run `yarn preview` in content-build and view `http://localhost:3002/preview?nodeId=318`, my API requests (e.g. `/feature_toggles` or `/v1/facilities...`) still go to localhost:3000.

You are correct though that vets-website code determines the API URL. If I edit `src/site/constants/environments-configs.js` and point `ENVIRONMENTS.LOCALHOST` to `dev.api.gov`, then run `yarn build`, the requests work. But that's sub-optimal for obvious reasons.

I think we need to find a way to make the `--env.api` parameter available to the vets-website code.

**Comment by theodur** [comment]
@mpelzsherman No, I meant to remove `env` from the flag. It should be how I had it, `yarn build --api=https://dev-api.va.gov`. Running what you mentioned only works for yarn watch in vets-website but not yarn build. If you run the build with the flag `--api` instead of `--env.api` it will use the dev api instead of `localhost:3000`.

`--env.api` is already available to vets-website, it's used for the `watch` command in the repo. The build command requires `--api` instead. This is because `watch` and `build` are executed differently. Try that and let me know. There should be no need to edit `environments-configs.js`.

**Comment by mpelzsherman** [comment]
Hey, you're right! I had no idea this `--api` flag existed. Is this documented anywhere?

I guess we can close this ticket, or perhaps just add some docs, but it's confusing that we have both `env.api` and `api` flags.

Thanks @theodur !

**Comment by theodur** [comment]
No problem! @mpelzsherman 

Technically, the `--api` flag that can be passed into `yarn build` gets converted to `--env.api` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.sh#L13-L14). One thing we could do is update the regex on that line to not prepend `env` to the argument if it already has `env` in it. That way, we could also use `--env.api` on the `build` command and keep consistency with Webpack's [environment variables](https://v4.webpack.js.org/guides/environment-variables/) and how we pass options to our `watch` command.

**Comment by theodur** [comment]
I'm closing this ticket in favor of a ticket for cleaning up the [build script](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.sh) in vets-website. Part of that cleanup should consist of making the format of the parameters of `yarn build` consistent with `yarn watch`. I'll post the ticket number here for general reference once I create it.

**Comment by theodur** [comment]
I created a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28041) for cleaning up the build script in `vets-website`, which should include getting the arguments for `yarn build` consistent with `yarn watch`.
