### ISSUE TITLE
Spike: Medication APIs

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25654]
Medication APIs are a necessary part of the CH-IP project - we will need to be able to manage medications through the checkin process similar to how the kiosks currently handles them.

VEText currently has some connection to medication notification systems and has done some ground work around notifying Veterans about refills, AVS also interfaces with medications, but the needs for the kiosks are an unknown, so these resources can be seen as a reference, not necessarily something we can build from.

The goal of this research spike is to answer the following questions

1. What are we trying to achieve with medications within the new checkin system?
2. What do kiosks currently do in regards to medications?
3. Do we need to link this with FHIR? and if so, what RPCs do we need to support?
4. What payloads, endpoints, error messages do we need?

**Comment by aschulhof** [comment]
Duplicate. Closing this issue - Moved to CHIP board

https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/47
