### ISSUE TITLE
Content request from Decision Tools team for Air Force-specific change on Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25655]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[X] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?
The Air Force would like for Air Force Veterans currently directed to download DD 149 to instead be directed to their Air Force Review Boards Agency portal (AFRBA) https://afrba-portal.cce.af.mil/#portal.   DD 149 and accompanying instructions are contained on this portal, so are no longer necessary in our content.

**Screen shot of page**
<img width="330" alt="US AF Discharge Upgrade Page" src="https://user-images.githubusercontent.com/63107147/114218970-15ecf080-9938-11eb-86e0-799588d2368a.png"> 

 **Link to page:** https://www.va.gov/discharge-upgrade-instructions/guidance - then answer the questions as shown in this [PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/6401425/DUW.pdf) to view content requiring changes.

- Current content on the page is highly specific to completing DD 149, and now needs to be reworked to provide a transition from the wizard to the Air Force portal, which will ask some of the same questions, and then ultimately provide instructions and a link to fill out and upload DD 149 online.
- We need to change the **Download Form 149 CTA** link to a link to the AFRBA portal.

## Expected Results
If a service member chooses Air Force while filling out the Discharge Upgrade Wizard questions, AND if their answers currently direct them to download DD Form 149, they will now be directed to the AFRBA portal located at https://afrba-portal.cce.af.mil/#portal  

## When does this content work need to be done?  

*It's an existing tool, so the timeline is largely dependent upon your team's availability.  We will need a mockup for design intent review, so Cassandra Allen will coordinate with you on the verbiage that it should include*

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [X] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET) **I will attend on Monday, June 7.**
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner:  John Hashimoto
-	Product manager:  Marci McGuire
-	Designer: Cassandra Allen
-	FE engineer:  Zach Morel
-	Product/team Slack channel: #vsa-decision-tools

## Links to related tickets

*Please include here a link to the epic, or other relevant tickets, for this product work.*

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
For awareness: @shiragoodman @peggygannon @mnorthuis

**Comment by RLHecht** [comment]
@callen2563 Could you let us know when you need this language for the design intent review? Trying to figure out a timeline for this work. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
It looks like @callen2563 and @bethpottsVADEPO collaborated on this in this ticket --> https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591.  OK to close this ticket?

**Comment by bethpottsVADEPO** [comment]
Yep, our work is covered in #23591. I'll close this ticket now.
