### ISSUE TITLE
Past events are no longer available in Prod

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25662]
## What happened?
Past events are not displayed on Prod

<details>
<summary> Screenshot from Production </summary>

![image](https://user-images.githubusercontent.com/55411834/120834488-4e680f80-c520-11eb-970c-0683d2f6709e.png)

</details>

## Steps to Reproduce
- View [Pittsburgh health care's events page](https://www.va.gov/pittsburgh-health-care/events/)
- Observe only one view of events is available (no tab for past events)

<details>
<summary> Previous experience screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/120834356-22e52500-c520-11eb-99f3-65e3a94722c7.png)

</details>

## Acceptance Criteria
Assumes discrepancies between preview and prod have been resolved. 
**The following criteria assumes events are published (not archived, in draft or in review) and apply to the event list pages, not the individual event pages.**
Past events 
- [ ] Past event page always shows the toggle
- [ ] Past events page shows past events only if there are published past events
- [ ] If there are no past events, show "There are no past events"
- [ ] If there are past events but no upcoming events, show the toggle. On the upcoming page, it should display "no events" and past events page will displays the events and the toggle 
- [ ] If there are past and upcoming events, show the toggle. Upcoming events display on the upcoming page and past event will display on the past events page. Both pages show the toggle. 
- [ ] Pagination is independent between past and upcoming events

## Dev Notes
- The `$today `variable might not be getting passed through correctly. If you look at the `pastEvents` array in the metalsmith data, it’s empty, and it should not be. 

<details>
<summary> Screenshot from Slack </summary>

![image](https://user-images.githubusercontent.com/55411834/120834871-d51cec80-c520-11eb-9d9b-10aec03cf6e8.png)

</details>

**Comment by mmiddaugh** [comment]
Related issue - Make Events page previewable #25402

**Comment by mpelzsherman** [comment]
It's worth noting that the past-events page _is_ being generated and _does_ show past events:

https://www.va.gov/pittsburgh-health-care/events/past-events/

The only bug here is the toggle is not displayed, though there is a workaround - you can click the Events breadcrumb.

![Past_Events___Events___Veterans_Affairs](https://user-images.githubusercontent.com/80267/130526651-3a476b9d-b45d-449f-9933-47efa3117935.png)

**Comment by mpelzsherman** [comment]
Closing - the past events tab is visible in production now. Fixed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/27433.
