### ISSUE TITLE
New Forms Library: Routing

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#25665]
This epic is related to routing in the new forms library. 

- [Routing] Scaffold routing components
- [Routing] Create and use Router context
- [Routing] Create form-wide layout elements
- [Routing] Review page: Chapter
- [Routing] Review page: Page
- [Routing] Review page: Field
- [Routing] Review page: Field (checkbox group)

**Comment by taylorkaren** [comment]
Transferred all issues to the VA Forms System Core repository and assigned to the Routing epic in that repository. Closing this ticket.
