### ISSUE TITLE
IA Request Debt Resolution Team, Medical Copayments Tool (MCP)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#25663]
## What this is:
Work with Platform Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kickoff ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- [Link to product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md)
- [Link to or attach prototype or mockups (usability version)](https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages//simulate/sitemap?mode=i)
- Link to or attach user/page flows
- Link to or attach your content source of truth, including H1s (if separate from prototype/mockup)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement**
In the absence of a true authenticated experience or financial hub, we agreed that this tool can be built as a stand-alone application for now, tied to other financial tools via crosslinking. In the meantime, we believe that this tool should replace the current "Pay copay bill" page, as it contains information on paying, resolving, or disputing copayment bills.

**Keywords and SEO** - 
Bill, Copays, (Medical) Copayments, health care bills, explanation of benefits

**URL(s)**
/health-care/manage-va-copay-bills because our users google "VA copay bills" and there will be more options than just the current "Pay copay bill" (i.e. ask for resolutions or dispute)

**Primary entry points** 
Email notifications and MHV (if we can include a link from there), most likely. 

**Crosslinking opportunities** 
- [Manage your VA debt](https://staging.va.gov/manage-va-debt/)
- [View Payment History](https://staging.va.gov/va-payment-history/) - users were drawn to this page due to its prevalence on the homepage, for both debts and copays
- [MyVA](https://staging.va.gov/my-va/)

**Redirects** 
- [Pay your VA copay bill](https://staging.va.gov/health-care/pay-copay-bill/)

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] Platform: Completes final IA feedback/recommendation
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
IA in progress: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-copays.md

Need to meet with sitewide content on plans for the new "financial hub" static page as well as crosslinking between tools.  

@rebeccawalsh would love your feedback on this showing the possible crosslinking opportunities. My VA is not represented in this diagram yet, need to review where they are at.

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/7d08912d-b7a6-4775-a2c1-7db15e1e83e5)

**Comment by rebeccawalsh** [comment]
@mnorthuis Nice! This represents strictly the ecosystem around the initial release of Medical Copays, right?

Feedback:
- There is also a link off to pay.gov within 'Pay copay bill'
- Another thing that has been mentioned is Travel Pay and its new(?) online tool, which one of our participants mentioned in conjunction with Medical Copays in our current study: https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

**Comment by rileyorr** [comment]
One more thing I'd like to add is that Veterans can request waivers and compromise offers for copay bills using the FSR. It's on our roadmap to expand the online form's functionality to include copay bills; but as part of the MVP it might make sense to link to the FSR's content page with adjusted content as needed. Unless the thinking is to incorporate the medical copay FSR content into the 'Request VA financial hardship assistance' page?

**Comment by mnorthuis** [comment]
@rebeccawalsh @rileyorr Thanks for the feedback!  Will try to answer all of the questions above...please let me know if I missed anything or if there is anything we need to continue to discuss. 

- Yes, this strictly represents the MVP - no actual financial "hub", just a content page and alot of crosslinking to build relationships. 
- For the pay.gov link, I assumed that link would go away with the new online tool you are building to pay copays?  Can you clarify what the pay.gov link would be for?
- For Travel Pay, we could add a link to that from the copay static page as a related item.  
- For the FSR, I did not link to the FSR or the FSR content from the copay page for right now, because the FSR content would just send the user right back to the copay pages for info and the pdf form.  When the FSR is expanded to include copay assistance, then we will definitely make that connection - I imagine this structure may change quite a bit to accommodate that, but this is the minimal changes for now.

**Comment by rebeccawalsh** [comment]
@mnorthuis 
- Great, was just confirming with the medical copay FSR not being present currently, but soon after the medical copay 'portal'
- Our tool does not support the actual *payment* of copays, it just allows users to view their copay account balances and activity, then the content or wizard will direct them to the appropriate payment or resolution pathway. So if they want to pay their bill online, they'll still have to use pay.gov to do that.
- Sure!
- Makes sense to me. We'll just adjust those supporting pages in the future when the copay FSR is live.

**Comment by mnorthuis** [comment]
Thank you for clarifying what your tool does, I had that wrong.  I will work on updating this to represent the view vs pay functionality.

**Comment by mnorthuis** [comment]
Updated crosslinking diagram that updates the tool to correctly reflect the ability to view copay bills and detail, as well as includes Travel Pay page (only crosslinked from financial landing page) and shows link to pay.gov for paying copay bills.   This does not show a link between the copay details and the online FSR since the current FSR does not yet support copays.  The copay details page will need to link back to the static pages within the health copay area (i.e. request financial hardship page). 

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/89b3c085-a29c-4a9f-ba28-393f4d70638d)

**Comment by mnorthuis** [comment]
@rebeccawalsh just checking in to see if there was feedback on the above?

Also, are you working with sitewide content to finalize headings?  I'd like to connect on that work to finalize breadcrumbs, URLs and entry point labels in the IA write up.

**Comment by rebeccawalsh** [comment]
@mnorthuis This is lining up for me -- one note is that Pay.gov will be directly linked on both the 'View copay bills' and the 'Copay details' pages, but I don't know if that needs emphasis in this diagram?

As for finalizing headings, I meet with Danielle and Beth at their office hours, but I didn't get a ton of feedback on the headings themselves. Danielle suggested that 'Current copay balances' could be more personalized to 'Your current copay balances' - but she did not mention the content page's title. I am going to work on incorporating all of Danielle's feedback before asking further about finalizing the rest of the headings.

**Comment by mnorthuis** [comment]
Thanks @rebeccawalsh, I'm going to sync with @DanielleThierryUSDSVA on this one as well to make sure all our headings, breadcrumbs and URLs are in alignment.

**Comment by LindaLi123** [comment]
@mnorthuis Hello Mikki,  would you please advise when our domain for medical copay will be available?

**Comment by mnorthuis** [comment]
@rebeccawalsh @LindaLi123 IA elements for the Auth tool to view copay balances and balance details are complete based on a conversation I had with @DanielleThierryUSDSVA .  We sync'd on the H1s of the pages, as well as the corresponding links and breadcrumbs.   I have included a page flow that shows page names and link labels for reference, but final copy will come from the sitewide content team. 

URLs and entry points are documented: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-copays.md

The IA information for the financial landing page is still in the works.  Please let me know if you have any questions or want to talk through anything.

**Comment by LindaLi123** [comment]
@mnorthuis Hello Mikki,  is there anything we need to do before we can close this ticket?

**Comment by mnorthuis** [comment]
If you and your team has all the information you need, you can close at your discretion.

**Comment by LindaLi123** [comment]
Hello @rileyorr and @rebeccawalsh would you please confirm you have all the information you need?
