### ISSUE TITLE
508-defect-2, sitewide [FOCUS]: Mobile menu loses focus when expanded and collapsed

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#25661]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh 

## User Story or Problem Statement

As a screen reader user, I expect a mobile menu to expand once I activate a collapsed menu button.
As a keyboard user, I expect focus to stay on the button I just activated. I also expect the next tab stop to be the first menu item in the expanded menu.

## Details

Focus is not managed when opening and closing the mobile menu. This means that no feedback will be given to screen reader users that the menu has been expanded e.g. "Close menu, expanded, button." It also is an annoyance for keyboard users who will need to tab an extra time to regain focus back onto the menu. 

Screen reader announcements are in the grey box.

https://user-images.githubusercontent.com/14154792/120833558-ecafa180-c52f-11eb-9516-edb561356ca2.mov

## Acceptance Criteria

- [ ] Focus remains on the menu button when opening and closing
- [ ] Screen reader users receive feedback that the mobile menu is expanded or collapsed

## Environment

On a narrow screen width where the menu is collapsed on VA.gov, turn on a screen reader.
Tab to the menu button and activate it.
Confirm no feedback is provided that it has expanded.

**Comment by brianalloyd** [comment]
Considering ripple affect that an applied fix would have on mega menu.

**Comment by joshkimux** [comment]
This has been fixed by @Rleahy22  in ticket #25659 🥳
