### ISSUE TITLE
IA Feedback - Midpoint Review [Authenticated Experience, Notification Preferences]

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#25679]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**
- What is the order of the notification groups based on?  Alpha order works best in an easily scannable list and where users understand the buckets.  This is a small list, so not a huge issue, but may be something that is reviewed as groups are added or modified.   Ordering by prevalance/importance is another option, which would lead with health care and end with the "General" bucket.   But this also depends on how the health care bucket is handled - see next bullet :-) [content hierarchy]
-  Will we know if a user does not have health care through VA?  If so, will that box be hidden or have a different display state so users do not try to change settings for a content area that does not apply to them?  If not, consider clarifying content so its clear that those notifications only apply for users with VA health care. [11, 44 messaging]

**Comment by andaleliz** [comment]
>What is the order of the notification groups based on? Alpha order works best in an easily scannable list and where users understand the buckets. This is a small list, so not a huge issue, but may be something that is reviewed as groups are added or modified. Ordering by prevalance/importance is another option, which would lead with health care and end with the "General" bucket. But this also depends on how the health care bucket is handled - see next bullet :-) [content hierarchy]

Yes, it is alphabetical order.  I think you're right that it's something we should keep an eye on as the list grows, and we'll certainly keep an ear/eye out during usability testing.  


> Will we know if a user does not have health care through VA? If so, will that box be hidden or have a different display state so users do not try to change settings for a content area that does not apply to them? If not, consider clarifying content so its clear that those notifications only apply for users with VA health care. [11, 44 messaging]

Yes, the box will be hidden if a user doesn't have health care through the VA (same logic we use to show/hide health sections in My VA).

What are the comments in brackets? I'm not sure what this means:
>[11, 44 messaging]

**Comment by mnorthuis** [comment]
Thanks @andaleliz!   You can ignore the info in brackets, that's for my reference :-).
