### ISSUE TITLE
Reserve Instances Expiration   

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2567]
Our RIs expired and we need to know how much reserve do we want for VA.gov

**Comment by ricetj** [comment]
@wyattwalter are we good with these now?

**Comment by ricetj** [comment]
@tskinn can we close this guy?

**Comment by wyattwalter** [comment]
I chatted with Boris a bit yesterday on this. He's got the list and I think we're good at this point on this ticket.
