### ISSUE TITLE
CT Redesign:  Comparison Testing - Research Plan	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25675]
Research plan is written, reviewed & updated	

Draft initial research plan Review w UX Team 
Update based on feedback

**Comment by JenLJ** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usability-testing-june2021/research-plan.md
