### ISSUE TITLE
CT Redesign:  Comparison Testing - Discussion Guide

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25676]
Discussion guide is written, reviewed & updated	

Create interview discussion guide (with streamlined tasks)  
Coordinate with prototype designer to align scenarios. 
Review with UX team 
Update based on feedback

**Comment by JenLJ** [comment]
Discussion guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usability-testing-june2021/discussion-guide.md

**Comment by amyknox** [comment]
@JenLJ - great job on the guide, as usual.  Notes below.  LMK if you have questions or concerns. 
 
This is going to be such a fun research endeavor!! 


**Intro** 
Where you have "Today we're going to talk about looking for schools on the GI Bill Comparison Tool."  Consider whether you want to specifically mention we're looking at the ability to search and compare schools in the tool. That way, they'll have a sense from the outset about our goal (and that we're not as interested in input on the profile pages).


**Warm- up questions**
Suggest this order to go from personal stuff they know to questions that queue them up for the testing tasks: 
* What is your military status (e.g. Veteran, child, spouse)?  If Veteran, which branch of service?
* Are you currently using or have you ever used your education benefits? (and follow-ons)
* _Where are you in the process of selecting a school to attend?_  (_NEW QUESTION_)
* When you first decided to go back to school, what factors were important to you in picking school options? Do you remember any of the schools you were considering? 
  * _This should be tailored based on their response to the "Where are you in the process" question_  
  * _Wondering if asking for specific names of schools may prime them to conduct a name search. 
 If you ask the "What was important to you" question, they might say "Location!" and the map search would definitely be in play._  

* Have you ever used the GI Bill Comparison Tool before?  NEW:  If yes, what do you recall about using it? 
 
**First Task: Finding schools**
* I like the time-travel framing of the task but curious what's the approach if they are currently looking for schools?  Or if they actually did use the CT for their previous school search? 
* Suggest adjusting the language just a bit:  Let's travel back in time and say you found the GI Bill Comparison Tool when you were first exploring schools.  Could you show me how you'd use the Comparison Tool to learn about schools you might be interested in attending?
* Upon task completion, reviewing the cards.  Suggest asking even if the new cards aren't there and maybe helping them focus by asking "When you're looking at these search results, what information here is helpful to you? Any information not at all important to you?"  

**Second Task: Comparing schools**
* If they were focused on just 1 school in the first task, you may need to get them talking about a couple schools they're interested in or work in a prompt to search for another school so they have a couple they're thinking about and "comparing" is top of mind.  
* Suggest adjusting the task language just a bit:  Let's say you want to get a better idea of the differences between the schools you're considering. How would you use the Comparison Tool to determine which school would be the best option for you?
* Upon task completion looking at the compare page, suggest tightening this up by asking "As you look at this page, what information here is most useful to you? Anything missing that would be particularly important to you?"  

**Third Task: Yay - Harvard!** 
* Is there a reason it's Harvard Law and not just Harvard University?  

"Harvard Law" doesn't return Harvard Law School - that tripped me up! - I thought I was supposed to see "Harvard Law School" and it isn't there which would look like a failed test.  YIKES - we don't want to start a compare task with a challenging search!  If just Harvard University, that's pretty easy to search and get an expected result.
