### ISSUE TITLE
CT Redesign: Profile Page -  Prototype,  EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#25670]
Profile page prototypes are reviewed w EDU stakeholders	

* Prototype is shared with relevant EDU team members  
* Feedback is collected 
* Prototype is tweaked, per input OR additional stories are written, as necessary

**Comment by amyknox** [comment]
Reviewed with EDU 6/17.  

Feedback: 
CINDA re: Types of degrees offered
Do they need to just display just VA-approved programs or is it all programs offered? 
> Depends on where the info comes from. 
> Doesn't seem like it could come out of WEAMS consistently. 
We'll need to discuss this internally and review what's possible. 

BRIAN re: Yellow Ribbon
Can we have links to the Yellow Ribbon tool in context so it's easy for people to get there? 

Joe P
"I like it. Very user-friendly.  A lot more modern looking than our current site.  I like the anchor links, too."
