### ISSUE TITLE
10-10EZ Form Alignment: Update Expiration Date

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25696]
## User Story

**As a** Veteran, **I want to** know the Expiration Date of the online form matches the most recent paper form, **in order to** ensure I'm filling out the correct form.

## Expected Behavior

The Expiration Date displayed on the online 10-10EZ form should be **6/30/2024**

*Note: we will need to get the expiration date when the new form is finalized*

## Acceptance Criteria

- [ ] The expiration date matches the expected value

**Comment by tchrisdyer** [comment]
Updated Expiration Date for new form:
![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/5d040a9b-f7d9-4ded-af87-af4146b9ff50)

**Comment by dat-gcio** [comment]
@tchrisdyer This is in prod. https://www.va.gov/health-care/apply/application/introduction

**Comment by tchrisdyer** [comment]
@dat-gcio looks good
