### ISSUE TITLE
Spike: Appointment API Integration

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25699]
Appointment APIs are a necessary part of the CH-IP project - we will need to be able to manage appointments through the checkin process as the kiosks currently handle them.

VEText currently has some connection to appointment management through the IMH, OSM, Direct Scheduling, etc, AVS also interfaces with appointments, but the needs for the kiosks are an unknown, so these resources can be seen as a reference, not necessarily something we can build from.

The goal of this research spike is to answer the following questions

1. What are we trying to achieve with appointments within the new checkin system?
2. What do kiosks currently do in regards to appointments?
3. What is the interplay with IMH - Are we building an analogue?
5. How are we integrating with EAS?
6. Do we need to link this with FHIR? and if so, what RPCs do we need to support?
7. What payloads, endpoints, error messages do we need?

**Comment by aschulhof** [comment]
Closing as OBE
