### ISSUE TITLE
Update the COVID HP sticky banner (July 2021)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25694]
## Issue Description
_Update COVID HP Sticky Banner to reflect: Get a COVID-19 vaccine at VA_

Screenshot: 
<img width="1046" alt="Screen Shot 2021-06-04 at 1 22 20 PM" src="https://user-images.githubusercontent.com/70410912/120852793-ea514580-c537-11eb-84fb-8a930821d0ea.png">

## Front end tasks
- Update COVID HP sticky banner with Verbiage to reflect ***Get a COVID-19 vaccine at VA**
- Validate all checks pass

## Acceptance Criteria
- [ ] Tier 2 Validation (must be validated in Socks by PM or PO)
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
Latest word from @DanielleThierryUSDSVA is to hold off on pulling down the sticky banner until some time in July 2021.  I'll place this in backlog until we get a solid timeline from Danielle or John in terms of implementation.

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA @johnhashva any update on desire to pull down COVID HP banner?

**Comment by johnhashva** [comment]
**7/14/21 Update** @brianalloyd -- Final decision on sticky banner is to _keep it in place for the time being_ -- and change the  text to: (via @DanielleThierryUSDSVA)

Get a COVID-19 vaccine at VA

**Comment by brianalloyd** [comment]
Completed, closing in support.

**Comment by johnhashva** [comment]
@kelsonic and @brianalloyd just confirming:   We did **not remove the sticky banner** (decision was to preserve it for now) -- but **we did change the text to**:

_Get a COVID-19 vaccine at VA_

I ask because I don't see it anymore.

**Comment by kelsonic** [comment]
PR merged, will go out with the daily deploy tomorrow: https://github.com/department-of-veterans-affairs/vets-website/pull/17969 sorry about that! 🙂

**Comment by brianalloyd** [comment]
Thanks @kelsonic updated the title of this ticket a few weeks back and should have noticed your PR element.  Thanks for reverting @kelsonic we'll give it a review post daily deploy.

**Comment by brianalloyd** [comment]
Validated and closing.
