### ISSUE TITLE
Re-write Education Benefits -- 0993 Test in Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25709]
* 00.0993-opt-out.e2e.spec.js

**Comment by CBonade** [comment]
This is in for review now and all checks have passed.  It's just awaiting a code owner review to be merged into master. This PR also adds a helper file and starts adding some form helpers that can be used in situations where the form tester may be overkill (or in lieu of an understanding of how to use it).

**Comment by CBonade** [comment]
This is merged to master and should be good to close out!

**Comment by pjhill** [comment]
Nice -- looks good
