### ISSUE TITLE
Access for Chris Dyer

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25702]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Chris Dyer (full name Thomas Christopher Dyer)
- Please Provide your email.
   > chris.dyer@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Caregivers Team, Sr. Product Manager, Ad Hoc LLC

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZjSzwo0x+3/x94+GX8xMb9tjkzkHl8d8mycKO4RVTrysGOhPNUuaXjtvITiBvb46u7xmi1J2Kj+vCTzWmUYv8l+lxJUC9oiaL1eeyq+pSkKOleLfBUilnRADxtcRsFyqNg4lcmYrvqq5hYZusvedQ3KraC3AGJ3E+1Shi9epp2iKFuHC09v1YRdeYTEq/16jPLKFNiOWrHBQ08ShFfeR1fY/SqQEaB21jQDKraN0Nk6v2xKzkTtno9IV5JQAUiIkUCOs93ab4smEZIPpREsRxJ3zcFJO+UKIgbhS0aN/qjzZbKG3twzqQSS49tJOAFZSmBHJkJZIJIrlw1jRMRU/3EXc/kXUar2NE2JeAbQzAU6X6DCmmyB9VCoN8G5kEQRo6FKpJhmnpxAH7AQSXDz78vzBojNL8xXTiQZ50dAJ/L6YmP5Gr4rXEWp00p46ahADPAf8ZO0NN+fRzMo+mEpqOumhETr14ug9SX5I+1UOdmApyEM4iIFxP2tRZEgfby4s= thomaschristopherdyer@Thomas-Christopher-Dyer-Macbook.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by tchrisdyer** [comment]
tagging @department-of-veterans-affairs/vsp-operations as per the instructions.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
