### ISSUE TITLE
Re-write Claims Status E2E Tests in Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25705]
src/applications/claims-status/tests/e2e --
* 00.claims-list-breadcrumb.e2e.spec.js
* 00.claims-list-empty.e2e.spec.js
* 00.claims-list.e2e.spec.js
* 01.claim-status-decision.e2e.spec.js
* 01.claim-status-est-current.e2e.spec.js
* 01.claim-status-est-past.e2e.spec.js
* 01.claim-status-est.e2e.spec.js
* 01.claim-status.e2e.spec.js
* 02.claim-files.e2e.spec.js
* 03.claim-details.e2e.spec.js
* 04.claim-ask-va.e2e.spec.js
* 05.claim-additional-evidence.e2e.spec.js
* 05.claim-document-request.e2e.spec.js
* 06-claim-estimation-breadcrumb.e2e.spec.js
* 06.claim-estimation.e2e.spec.js

**Comment by CBonade** [comment]
This has been merged into master and should be good to close!

**Comment by pjhill** [comment]
Whew, this was a big one -- awesome!
