### ISSUE TITLE
5490: Remove prod flag and set feature flag to ON for legislative form updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25700]
As a developer, I need to remove prod flags and set the 'edu_form5490_updates' feature flag toggle to ON so that the new functionality is available in production.

## Assumptions: 
1. UAT has been completed for this effort and EDU signed off as of 2021-06-14. 

 ## Acceptance Criteria 
1. The feature flag 'edu_form5490_updates' is ON. 
2. All prod flags associated with the implementation of #25122 are removed.

 ## Supporting Artifacts: 
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17593

**Comment by dmccurdybah** [comment]
Flipped flag on prod

**Comment by sonntag-adam** [comment]
Testing passes QA. Closing story.
