### ISSUE TITLE
10203: Remove prod flag and set feature flag to ON for legislative form updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25701]
As a developer, I need to remove the prod flags and set the 'edu_form10203_updates' feature flag toggle to ON so that the new functionality is available in production.

 ## Assumptions: 
1. UAT has been completed for this effort and EDU signed off as of [TBD]. 

 ## Acceptance Criteria 
1. The feature flag 'edu_form10203_updates' is ON in production. 
2. All prod flags created as part of #24612 are removed and the functionality is available in production.
3. All prod flags created as part of #25972 are removed and the functionality is available in production.

 ## Supporting Artifacts: 
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17646

**Comment by sonntag-adam** [comment]
In production. Closing story.
