### ISSUE TITLE
Re-write Caregivers E2E Test in Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25704]
* src/applications/caregivers/tests/00.caregivers.e2e.spec.js

**Comment by CBonade** [comment]
Moved this one back to in progress. There's an issue with the axeCheck blowing up due to the page not loading in vets website (returns a blank white page with 'CANNOT GET /caregivers`.  I'm going to dig further into why this is happening and how it differs from the nightwatch experience.

**Comment by CBonade** [comment]
This is now merged into master and ready to be closed.

**Comment by pjhill** [comment]
Thanks
