### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#25719]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
lli@governmentcio.com
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `@platform-analytics` to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [X] Google Analytics
- [X] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
_6.7.2021._

## Product Team / External Team / VA Office
_Debt resolution_

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
@LindaLi123 -

You should receive emails for both GA and Domo.

Some info about our various GA properties and views:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/navigating-google-analytics.md

Let me know if you have any questions.
