### ISSUE TITLE
Update color of SafeAreaView to match nav bar

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25710]
## Acceptance Criteria
1. iOS/Android: When the bottom nav bar & SM toolbar buttons display, update the hex code of the SafeAreaView (i.e. bottom-most part of the screen) so that the background color matches the color of the button: #F9F9F9
2. Android: apply this same color (#F9F9F9) to the bottom toolbar on screens that don't have the nav bar/SM toolbar buttons. 
     - Note for dev/QA: this color is currently set as #F1F1F1. Per direction from UX, we're updating this to #F9F9F9 so the app consistently uses 1 color throughout the app

## Screenshot for reference
![Screen Shot 2021-06-04 at 1.44.07 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/120c18a9-9413-446e-8635-906d88b7eed5)

**Comment by digitalken** [comment]
@jmarchi , I'm going to send this one back to you on in-progress.  As you can see the iOS looks good but the Android is still showing the difference.  Thanks.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/6fa05625-8628-4af3-88a7-8358c7ac4174)

**Comment by bessgreen** [comment]
@digitalken SafeArea view also needs to be updated for the Compose/Reply SM footer buttons on iOS + Android

**Comment by bessgreen** [comment]
@digitalken requirements in this ticket have been updated

**Comment by digitalken** [comment]
@jmarchi 6-28-2021 - Looks good on the Android but I'm getting color difference on the bottom for iOS where I don't have them on the Android, specifically for the pages in SM with "Compose a Message" and "Reply".  There are still two distinct colors at the bottom of those pages. Sending back to In Progress.

Here are those pages:

![2021-06-28_11-56-23.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/c0a386df-bb27-4921-b13f-85f23a2347fc)

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good now on both iOS and Android.  Closing.
