### ISSUE TITLE
Remove mention of named `screen` import from React Testing Library

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#25714]
# Details

During the previous iteration of updating the unit test best practices document, we included an example with a statement that imports the `screen` utility directly from react testing library (RTL). We have not properly configured our testing environment to allow for this import, so this will be misleading for developers and lead to errors.

# Acceptance Criteria
- [ ] Update unit test best practices document to show how to properly define the `screen` utility

**Comment by Cgfor3** [comment]
Updates can be found here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/
