### ISSUE TITLE
Adding Jenna Ouellet to DSVA Slack

### ISSUE THREAD

**Issue by nsmith1982** [department-of-veterans-affairs/va.gov-team#25716]
Good morning,

Please add Jenna Ouellet (Jenna@empiricalpath.com) as a Full Member of DSVA Slack with access to following channels:

# VSP-Analytics
# vfs-platform-support
# vfs-all-teams

Thank you 

@batemapf @LEHigley @LizCallaghan

**Comment by LEHigley** [comment]
done
