### ISSUE TITLE
Replace sass-lint with stylelint in GHA

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#25729]
## Description

Stylelint is now the new scss linter for vets-website. We will want to update GHA to use this new tool.

## Acceptance Criteria

[] Replace sass-lint with stylelint in GHA workflow
[] Github Actions annotations and outputs are working as expected

**Comment by U-DON** [comment]
Closing since `stylelint` has replaced `sass-lint` in GHA.
