### ISSUE TITLE
Access for [Ana Ricci]

### ISSUE THREAD

**Issue by anaricci-va** [department-of-veterans-affairs/va.gov-team#25721]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee Cecilia.Lee@va.gov
- Please provide your name.
   > Ana Ricci
- Please Provide your email.
   > ana.ricci@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name = Matsumoto
   > Company = Libertyits
   > Role =Scrum Master

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQDPQzeNXeNI+0I5rXoVQZcr3loAUOHaYFPayj89yOSQ7BaOjLVKTOK0aY9eLB67ndzQSDfGG6a7S5RRQPIUca4dT6Kl3W1Qv+I3gjM/MiiqDZGVit10ueKdYreAYGUMtH5A5OwUpTmA8cOItQDq4nEQtcjWIXGDC1YTJ///IKOCy0sq9dcv4P1aCEjh5Hcq52DLtgE9T48G+6JagnPvFZbYED/6pMT+oZKQLWoxWbh+oezpHBN7SqZWm68rERejeGhRvrPuo81sSRHsk1UfsIEtmKCyyKHSImL9xXAgR2txrlm50qzBxYGv6synf/PsWKV6eUs2sQtfbFc2Ra6lXkf0Z6it1QllA4KyW+P3lAV4CcoPIgvuNkaqFCIwbu4v/E5tcnk5J8UV7Ies1WRqhdJaxqK9v2USFvil+W8NZA23oFF7ToJuo9rrw4F40kkbj3ybDoiAAsqfWQj08DFs661FXqVOeHxiPjn/R3E4Ln3mcYOapWXR0FS2BPpBWXbpqm8= AzureAD+AnaRicci@DESKTOP-R2DUCTJ
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
  > S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house including things like CloudWatch.

**Comment by jbritt1** [comment]
### For AWS Access:

User: Ana Ricci
COR: Cecilia Lee
Approval needed: @drorva

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by drorva** [comment]
Request sent to COR

**Comment by drorva** [comment]
Approved for AWS access

**Comment by jbritt1** [comment]
Temporary credentials passed to user at this time.
