### ISSUE TITLE
Direct Scheduling:  Date selection says earliest day but it is NOT actually the earliest date

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25745]
This defect is for two three issues related to this message seen in VAOS direct scheduling flow.  

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/26849cad-c779-43b0-9fcb-f17271f78d16)

From Jeff:  the above is related to the preferred date you picked and what slots come back.

Issue #1:  Says the earliest date you can schedule is XXX but if you select previous month there are open slots.  So that is incorrect.  

Issue #2:  Message implies a date has been selected.  Instructed that if this date doesn't work pick a different date when you haven't even selected a date yet.

1. Login is Judy Morrison
2. Select Primary Care Cheyenne
3. Enter T+365 as preferred date. At least this is a date that I found where this message shows up consistently.  
4. Expected response:  Not sure what to expect.
5.  Actual response: system tells user that the earliest date that they can schedule an appt is June 1.  

It seems this message is really the earliest date you can schedule give the appointments displayed on this page.  

## Tasks
- Remove info alert message for standard of care scenario (when date preference is a future date)

### Out of Scope
The similar "urgent care" warning alert when date preference = today is out of scope and should remain.

**Comment by laurenernest** [comment]
Latest steps to repro:
Judy
Audiology
Dayton
Date input = Dec 1, 2021

**Comment by laurenernest** [comment]
Looks good! closing.
![25745 validation.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/664dc40b-f166-43d3-adcc-341f5f9b76df)
