### ISSUE TITLE
[FE] Update link on 2FA prompt under Direct Deposit section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2574]
On the VA.gov profile, the link to set up 2FA in the 2FA prompt under the direct deposit section links to /account. That was my mistake originally — it should link directly to the 2FA flow. Can we update its destination to the following?:

https://api.idmelabs.com/en/multifactor/setup/phone/new 

<img width="670" alt="Screen Shot 2019-10-18 at 12 55 23 PM" src="https://user-images.githubusercontent.com/34068740/67116013-8684d800-f1ad-11e9-9f54-4c1d38698553.png">

**Comment by erikphansen** [comment]
@Samara-Strauss this can also be validated if you can sign in with jaime.wood

**Comment by Samara-Strauss** [comment]
Will take a look at this once DS Logon is back up and running, *hopefully* by Monday.

**Comment by mshea0606** [comment]
@Samara-Strauss  - DS Log on issue

**Comment by Samara-Strauss** [comment]
Hey, I still can't get into the account for the staging user we have, but it's separate from the DS Logon issue we had a couple weeks ago. Not sure when I'll be able to get into that account to verify this.

**Comment by Samara-Strauss** [comment]
FINALLY was able to get into the test account. This is working as outlined above. Validated! Feel free to close.
