### ISSUE TITLE
Add Daniel Nalbach and kevin musiorski to DSVA Slack as Full Members

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#25748]
Please add the following two new people supporting VSA as full members to the DSVA Slack:
Daniel Nalbach: dnalbach@governmentcio.com
Kevin Musiorski: kmusiorski@governmentcio.com

Thank you!

**Comment by LEHigley** [comment]
added Kevin, but got a note that Daniel is already a member
