### ISSUE TITLE
Content Updates from VEO

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#25764]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[x] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[ ] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

Justin Hoffman, from the Veterans Experience Office is requesting updates to the "Welcome Kit" page's content.

"Can I get this new document (Food and Nutrition) posted at www.va.gov/welcome-kit under “Download our guides to VA benefits and services” for Veterans? The title of the link will be “Get started with food and nutrition services”.

Also, I have an updated document that needs to post to an existing link at the same site under “Get started with health services for women Veterans”. 

[VAWK_QSG_Food_and_Nutrition_2021_508.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6611305/VAWK_QSG_Food_and_Nutrition_2021_508.pdf)
[VAWK_QSG_Women_Veterans_Health_Services_2021_508.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6611307/VAWK_QSG_Women_Veterans_Health_Services_2021_508.pdf)

## When does this content work need to be done?

Not sure as the user wasn't specific in the email.

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Links to related tickets

*Please include here a link to the epic, or other relevant tickets, for this product work.*

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
Emailed Justin Hoffman 6/8 to ask for the PDFs to be uploaded into Drupal.

**Comment by RLHecht** [comment]
Changes made, reviewed by SMEs and published. Moving to validate. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
