### ISSUE TITLE
Content Feedback - Midpoint review - Preferred Facilities

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#25760]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
Content feedback for Preferred facilities prototype is below: 


**Should**
On Personal and contact information screen
Log in should be> sign in (per content style guide word list)

------

**Comment by andaleliz** [comment]
Hi @peggygannon confirming this is what you're referring to:
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/47832fa3-cbbe-48b7-a13d-713241266e11)

If so, the language on staging is below, which I think is correct. That copy in the mock-ups is from an early profile 2.0 design before I joined the team so it probably just didn't get updated between the design + staging review stages. I can update it now so it's accurate in all prototypes moving forward.

>Your contact email may be different than the email you use to sign in. To view or update your sign-in email, go to the website where you manage your account information.

**Comment by peggygannon** [comment]
HI, @andaleliz Yes that is the content I was referring to. Thanks for following up about this.

**Comment by andaleliz** [comment]
We are so lucky to have your eagle eyes on our team! Thanks for catching that, and I'll make sure it's resolved in future prototypes.
