### ISSUE TITLE
Pilot new VA.gov Experience Standards process at Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#25763]
## Issue Description
We have identified and documented a process for how we will write and communicate issue tickets at Collaboration Cycle Staging Reviews ( @allison0034 is documenting the process via [ticket #22310](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22310) ). Now we need to test our internal process to identify any issues and verify it will work correctly.

---
## Pre-Pilot Tasks
- [x] Create a feedback survey (optimal workshop) ( @allison0034 )
 - goal of the survey should be to gauge VFS opinion on issue based tickets vs. former approach of practice-area based tickets. Can have 5 point scale rating, but then also include space for them to provide detailed feedback.
 - survey has already been created in Collaboration Cycle folder on optimal workshop.
 - ask Naomi or Shira for login
- [ ] Schedule pre-staging Sync meeting for every Staging Review included in our pilot.
   - [ ] [Decision Tools - Find a VA Form  ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26298) scheduled for 2:00pm ET on 7/2
   - 8/19/2021: Pre-staging meetings were not scheduled and determined unnecessary by team.
- [x] Schedule Pilot Kickoff meeting with full team (Josh and Angela included) so that we can review team responsibilities and expectations for the pilot. Be sure to discuss:
   - [x] Instructions to team
   - [x] Location of Feedback template
   - [x] How face-to-face feedback will be delivered
 - Shira to move meeting from 7/1 to 6/29 to allow for more time for teams to ask questions.

## Post-Pilot Tasks
 - [x] Launch feedback surveys with teams post-Staging Review.
- [ ] In [Staging review template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md), add checkbox under "Steps to complete review" to send feedback survey to teams after the meeting. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
I am not sure how you plan to send this survey out but one suggestion would be to send it a week after a team has a staging review.

**Comment by shiragoodman** [comment]
thanks @allison0034. I will review on Thursday. 

I do like the idea of sending the survey out later so they have time to digest the new feedback format. Thanks!

**Comment by shiragoodman** [comment]
@allison0034 this looks good. I'm glad you took the time to weed out the VFS folks who have not participated in a collab cycle Staging Review before. I wouldn't have thought of that! Let's discuss in refinement later today.
