### ISSUE TITLE
Save Login Trace To DB

### ISSUE THREAD

**Issue by jimiray** [department-of-veterans-affairs/va.gov-team#25766]
Save login information including started_at, completed_at, idp, ip address, and SAML response.

**Comment by bosawt** [comment]
Notes:

### Functionality
* In `v1/sessions` controller, function `audit_login` gets called with context set to current route (`new` or `callback`)
* `LoginAudit` model is a class that serializes data for the logs
	* Validates `idp`, which is a list including `idme`, `mhv`, `dslogon`, `login_gov`, you can delete any of these and logs will stop being saved for that `idp`
	* Validates presence of `request_id` (think this is meant to be `transaction_id`
	* Serializes the rest of the response
* `AudiLoginService` is a service object that processes a single log
	* Creates a log entry for the `LoginAudits` table
		* If `response` is passed in, it attempts to find an existing entry by searching for `request_id` (`transaction_id`) and `idp` match in the `LoginAudits` table
			* If entry is found, it adds the existing `response` to this entry
* `AuditLoginJob` is a `sidekiq` job that simply makes a call to the `LoginAudit` service
* `LoginAudits` is a table that includes
	* `request_id`
	* `account_id`
	* `idp`
	* `ip_address`
	* `started_at`
	* `completed_at`
	* `success` (whether login was successful)
	* `response` (full SAML response)

**Comment by bosawt** [comment]
We discussed this, we might leverage the branch in the future, but we're going to investigate Loki first and see what the limits of its functionality are, then potentially transition to a database trace solution if it seems that's more appropriate. 

If we want to leverage the branch in the future it's here: jimiray/login_traces
