### ISSUE TITLE
Re-write Pensions E2E Test in Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25775]
* src/applications/pensions/tests/00-all-fields.e2e.spec.js

**Comment by CBonade** [comment]
This appears to have already been completed by Eugene on the FE Tools team.

**Comment by CBonade** [comment]
This has been merged into master and should be good to close!

**Comment by CBonade** [comment]
This should be good to close

**Comment by pjhill** [comment]
🎉
