### ISSUE TITLE
Subtask:  Update SideNav `expanded` logic to not rely on original data source 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2577]
**Subtask for new SideNav for Pittsurburgh Health:**
- [ ] Update Expanded Logic to not rely on original data source
- [ ] Remove new SideNav from pages other than `/pittsburgh-health-care/**`

Relates to ticket #2278:  Implement new sidebar navigation on Pittsburgh health care

**Comment by ncksllvn** [comment]
🚀
