### ISSUE TITLE
Follow up considerations from GitHub Actions replacement for Atlantis (Terraform)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#25777]
## Description
There are a couple of follow up considerations from the [work that was done to replace Atlantis w/ GHA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25384) 

## Considerations 
Do we want "applies"?
Do we want to restrict it to specific users? and if so, 
Do we want to implement some logic to query GH teams and restrict this by team membership?

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _TBD_

## Definition of Done
- [ ] _TBD_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
Do we want "applies"? 
From @dginther (Demian) - We probably do want applies, ie reply to PR and "terraform apply" which might require some extra logic in the code, but totally doable. In Atlantis, we can "terraform plan" in the thread and it runs the plan again. That would be a nice-to-have as well... 
From @omgitsbillryan - it would be nice if there was an automated apply process.
Demian points out that there can be errors with the PR, so might need an automated+manual process

Do we want to restrict it to users? and if so, 
Demian - yes, we would want the ability to restrict, and... 

Do we want to implement some logic to query GH teams and restrict this by team membership?
We can definitely use GH team membership for that. Can start with just the Ops team. Can expand later. 
---
We will continue to prioritize this and decide on when to implement but wanted to get some thoughts down.

**Comment by dginther** [comment]
Based on discussions in a grooming session
- Tracing WHO exactly applied would become difficult if we allowed GHA to terraform apply
- targeting and command line arguments would become very difficult
- we are all afraid of this

Closing this ticket.
