### ISSUE TITLE
Remove rails engine flag front-end logic

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25786]
## Issue Description
Now that the Rails engine has been enabled in Prod, the flag holding it in Staging is no longer needed. 

## Tasks
 - Remove unneeded flag logic from front end
~- Work with Lance to determine need for logic on the backend~
There is nothing that needs to change on the back end AFAIK, but we can probably remove the non-Rails-engine logic on the back end as well (separate ticket).

## Acceptance Criteria
- [ ] Unneeded logic is no longer present in code

**Comment by mpelzsherman** [comment]
Resolved by https://github.com/department-of-veterans-affairs/vets-website/pull/18879
