### ISSUE TITLE
VAOS Phone Appt Request Not Indicated as such on detail card

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25797]
Enter VAOS appt request and type = Phone. 
View detail card.  The type = VA Appointment.  

Enter a VAOS request and type = Telehealth
View detail card.  The type = VA Video Connect.  

Enter VAOS request and type = Office Visit
View detail card. The type = VA Appointment.  

Issue: If type selected = Phone.  Then shouldn't the type on the detail card indicate Phone rather than VA Appointment.  

![RequestTypePhoneDetailCard.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/c471b0a8-04ba-466d-8f9e-64b43d96c198)

**Comment by laurenernest** [comment]
Since this is a pending request, it's working as expected. We won't show the extra detail on the label until it's confirmed. 

We're working with Content on the best way to show the user's preference when it's still pending.
