### ISSUE TITLE
Dependent Verification Listing Adjustment

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#25790]
## Background
When a Veteran is presented with a modal window that displays dependents that need to be verified, that list should ONLY be those dependents that are eligible for verification (per their respective diary entry) AND are on the "on award" list.  At this point, the Veteran is not required to update the VA on dependents that are not on an award.

## Considerations

<details>
  <summary>Expand to see image of full list (both on and off award and the modal window (image cropped)</summary>

![modal-all-dependents.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/8fd7ba37-f496-4f9b-acc8-2a0aff009018)

</details>

- each dep has a unique PID, use that to group
- award effective date needs to be most current but not in the future
## Tasks
- [x] Filter the applicable dependents to only include those that are eligible for verification AND are currently on award (or use the effective date) AND filter it down to unique names.

## Acceptance Criteria
- [ ] The  list presented by the modal window only shows those dependents that are eligible for verification and on award, effectively.

**Comment by jason-gcio** [comment]
BGS data is on View Dependents but the Modal is looking at Diary Entries - so two different data sources

**Comment by jason-gcio** [comment]
Reminder to ensure filtering code is removed from frontend

**Comment by RudyOnRails** [comment]
merged...
