### ISSUE TITLE
Adding [GilbertEngle] to DSVA Slack

### ISSUE THREAD

**Issue by gilbert-engle** [department-of-veterans-affairs/va.gov-team#25798]
adding myself to DSVA Slack

**Comment by gilbert-engle** [comment]
The following individual gilbert.engle@accenturefederal.com needs be added as a full member guest to #25798

**Comment by LEHigley** [comment]
hi @gilbert-engle i'm getting a message that you're already in slack?

**Comment by gilbert-engle** [comment]
hello

Ok, great

Thanks for checking

cheers
________________________________
From: Lacey Higley ***@***.***>
Sent: Tuesday, June 8, 2021 3:31 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Engle, Gilbert [Greenbrier Government Solutions Inc.] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Adding [GilbertEngle] to DSVA Slack (#25798)


This message is from an EXTERNAL SENDER - be CAUTIOUS of links and attachments. THINK BEFORE YOU CLICK.
________________________________


hi @gilbert-engle<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgilbert-engle&data=04%7C01%7Cgilbert.engle%40accenturefederal.com%7C59e6e5fb642a412a1bc008d92acd1cef%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637587882722502679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jARYgON0E3ngHpCmCMhSRFuoEG6ggzuRdCrllHU%2Fgfg%3D&reserved=0> i'm getting a message that you're already in slack?
