### ISSUE TITLE
Statuses parameter not working on /vaos/v2/appointments GET

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25800]
There's a statuses parameter on the GET for the appointments fetch in the VAOS service, but passing it to /vaos/v2/appointments doesn't seem to have any effect on the results returned.

I verified that the vaos service parameter works, it's just the vets-api wrapper that is not handling it correctly.

Swagger: https://coderepo.mobilehealth.va.gov/projects/VAR/repos/vaos-service/browse/vaos-service/src/main/resources/swagger.json?at=refs%2Fheads%2Frelease%2F1.6#136

Request url for vaos service I used that returned items just with proposed status: https://veteran.apps-staging.va.gov/vaos/v1/patients/<judy morrison icn>/appointments?start=2020-06-08T00:00:00.000Z&end=2021-06-08T00:00:00.000Z&statuses=proposed

I tried appending `statuses`, `statuses[]` and other variations of that as a query parameter on the vets-api endpoint without any change in the number of results.

**Comment by ajmagdub** [comment]
Submitting a single status to the vaos service worked as expected. When submitting more than one status, for example `/vaos/v1/patients/redacted-icn/appointments?end=2022-07-03T04:00:00Z&pageSize=0&start=2021-05-04T04:00:00Z&statuses=cancelled,proposed`, the vaos service was returning a 400 error with a message `{"message":"statuses: invalid value"}`, per the vaos service swagger file this should be a valid request. 

Created [VAOSR-2005](https://issues.mobilehealth.va.gov/browse/VAOSR-2005)
