### ISSUE TITLE
Claims and Appeals overview display titles

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va.gov-team#25803]
The front end should consume the new displayTitle field from vets-api for claims and appeals on the overview page.

**Comment by digitalken** [comment]
Hi @jperk51, is there anything for me to test on this one?

**Comment by jperk51** [comment]
# Acceptance Criteria
Login with user +226
Navigate to claims and appeals
Scroll until you see the Supplemental Claim submitted on September 23, 2020
- [ ] Title should read: "Supplemental claim for disability compensation updated on September 23, 2020"
Then navigate to the next page
Scroll to the Higher-level review submitted on May 01, 2020
- [ ] Title should read: "Higher-level review for disability compensation updated on May 01. 2020"

**Comment by digitalken** [comment]
PASS 7/29/2021 - Looks good, as indicated.  Closing.
