### ISSUE TITLE
Discover and add new content maps for appeals events 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va.gov-team#25804]
During UAT is was discovered that some events for appeals were missing titles and content for the event timeline. This content needs to be found on web and added to the mobile front end.

**Comment by digitalken** [comment]
Hi @jperk51, is there anything for me to test on this one?

**Comment by jperk51** [comment]
Change is thoroughly tested by the unit tests. Can be considered a dev task.

**Comment by digitalken** [comment]
PASS - Closing this one as a developer task due to the complexity of trying to locate users that might satisfy verifying this task.
