### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by thepipster** [department-of-veterans-affairs/va.gov-team#25813]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
michael.j.pritchard@omb.eop.gov

## Access Requirements
Please check the analytics tools you need access to:
- [*] Google Analytics
- [*] Domo
- [*] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
ASAP 

## Product Team / External Team / VA Office
Platform team leadership

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
Dupe : https://github.com/department-of-veterans-affairs/va.gov-team/issues/25627

**Comment by joanneesteban** [comment]
@thepipster the team's provisioned GA, GTM, Domo, and BigQuery access (noted in https://github.com/department-of-veterans-affairs/va.gov-team/issues/25627), and you should receive emails from Domo & Google for this access. Please reopen this ticket if you run into any issues!
