### ISSUE TITLE
[Content] Update copy for the health reminder text message notification setting in the VA.gov profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2581]
@peggygannon per #2428 we need to modify the copy for the upcoming notification setting that will allow people to opt in to health care appointment reminders right from their VA.gov profile. Trevor says that [per this standard](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G13), the existing copy isn't friendly for people using screenreaders because it doesn't explicitly mention that you need to check the box to opt in to text messages.

Can you please update the copy for the check box below so it clarifies that checking the message will opt people in to text messages? I checked with Trevor, and he confirmed we do **not** need to also mention that people should uncheck to opt-out again.

<img width="465" alt="Screen Shot 2019-10-18 at 2 22 46 PM" src="https://user-images.githubusercontent.com/34068740/67118394-cc906a80-f1b2-11e9-8755-bf268be6b546.png">

**Comment by lkoenigsberg** [comment]
@peggygannon , after discussion with the team we are going to leave the check box's on both the profile and modal.  What we need is better copy for when/if the box is checked or unchecked.

cc @Samara-Strauss, @claricechan, @elwoodva

**Comment by Samara-Strauss** [comment]
I've updated the top message to reflect the new direction we're taking.

I'm also waiting to hear back from Trevor about whether we need to specifically mention checking AND unchecking the box, and will update the directions accordingly when I hear back.

**Comment by Samara-Strauss** [comment]
OK, got feedback from Trevor. Updated the initial directions. This ticket should be ready for copy eyes @peggygannon.

**Comment by peggygannon** [comment]
Hello, @Samara-Strauss @elwoodva @claricechan @lkoenigsberg Please see my content recommendation below. Let me know if this will work!

Please check the box if you want to receive text message (SMS) reminders for your VA health care appointments.

**Comment by Samara-Strauss** [comment]
@peggygannon sounds good to me! Will also confirm with Trevor that it looks good.

**Comment by elwoodva** [comment]
Ok, thank you!

**Comment by Samara-Strauss** [comment]
Got sign off from Trevor. Closing!

**Comment by elwoodva** [comment]
So, we are changing the text on the profile page but not inside the edit modal.  Correct?  Since the checkbox is part of a form with an Update button, I understand it to not be necessary to change the text next to the checkbox inside the edit modal, only where it appears on the profile page.

**Comment by lkoenigsberg** [comment]
@elwoodva This ticket is closed but yes, only on the profile page.

**Comment by Samara-Strauss** [comment]
Yes, we can leave the copy in the modal as-is
