### ISSUE TITLE
GIDS: Add ability to upload section 1005 tuition and fees data file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25818]
As an Education team member, I need the ability to upload a file containing data regarding an institutions compliance with Isakson and Roe section 1005 so that data can be displayed on the Comparison Tool.

## Assumptions:
1. This data file is temporary until the data can be included in the WEAMS file.
2. This data does not need to be included in the version export file.

## Acceptance Criteria:
1. The file type is "InStateTuitionPolicyUrl".
2. The user has the ability to:
    a. Import a data file
    b. Export a data file
3. Accepted import file formats for the data file are:
    a. .txt
    b. .csv
    c. .xls
    d. .xlsx
4. Valid column delimiters are:
    a. ,
    b. |
5. The accepted imported file has the columns in the following order:
    a. Facility Code
    b. In-State Tuition Information
6. The following columns are required for data to be imported:
    a. FacilityCode
    b. In-State Tuition Information
7. The "In-State Tuition Information" data is included in the institution version generation.

## Supporting Artifacts:
1. [Sample Data File](https://github.com/department-of-veterans-affairs/va.gov-team/files/6618915/PL.116-315-Section.1005-Web.Links.20210604.xlsx)

**Comment by elder-joseph** [comment]
Associated PRs:
DB Only: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/832
Full: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/834

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
testing complete
