### ISSUE TITLE
cleanup of pre-VAEC migration sentry resources

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2582]
Looks like some cleanup was missed when sentry got moved into VAEC. I see that there's at least:

- dsva-vetsgov-utility-redis-sg security group
- a "vetsgov-util" elasticache cluster
- a "dsva-vetsgov-utility-sentry-elb" ELB
- sentry-vetsgov deployment configs in ansible

There's likely others. The AWS resources should be removed from Terraform and the rest of the config removed.

**Comment by benniemosher** [comment]
Security Group may possibly have a redis instance attached to it, track that down,  may be named something like 'vetsgov-util'
