### ISSUE TITLE
SM Drafts UX  

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#25831]
Acceptance Criteria
* Users can begin a message and save the message (new message or replying to a message)
* The draft message is saved in the drafts folder
* Users can access draft messages within the app and within the web version on MHV

Note: within the existing experience, a number displays beside the draft folder representing the number of draft messages in the folder but defer to the UX expertise on how to best handle this within mobile.

**Comment by melissa-lefevre** [comment]
This is the flow of the current Mobile- Web version. ![Screen Shot 2021-06-09 at 10.14.05 AM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/a6ea5073-9c94-44f2-a928-cdd5acb5d0f6)
