### ISSUE TITLE
Socialize training session recordings (Develop guidelines)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25840]
# User story

As a Platform team member, I need to know absorb the info from the training session, so that I can contribute to it (the Platform Website) without prematurely exposing others' content.

# Tasks

- Upload recording onto YouTube:
  - [x] Trim video.
  - [x] Upload video.
  - [x] Add captioning.
- Socialize recording:
  - [x] (Amy, Fri) Compile FAQ.
  - [ ] (Liani, Mon) Draft and send message with recording, deck, and FAQ to #platform-team.

# Acceptance criteria
- A message in #platform-team has been sent out.

# Reference info
- Playlist https://www.youtube.com/playlist?list=PL0QW9C65TdUVwEEfUEsLSo6dlQPhlQlzQ
- FAQ doc http://bit.ly/contributing-to-platform-website-faq

**Comment by amygoldman** [comment]
Added questions and answers to the FAQ doc

**Comment by lianilychee** [comment]
draft message:

> good morning @ here :sunshine: 📽️ :va: **The Content team is now supporting all Platform teams in contributing to Platform documentation!*** (Objective 1: Info for all common VFS needs are findable in Platform website .) If you missed our 6/2 ~30-min training session, you can _**watch [the recording](https://www.youtube.com/playlist?list=PL0QW9C65TdUVwEEfUEsLSo6dlQPhlQlzQ)**_ and _**drop your questions in #VSP-confluence**_.
>
> _contributing to Platform documentation_ = creating new content in the Platform website, migrating GitHub content to the Platform website, and deprecating old content in GitHub
>
> _Other note:_ The recording description links to the session deck + the FAQ.  The FAQ is a living document, and we will update it as we receive more questions.
>
> cc: @ Rachael Roueche @Dror @ chelen @ Andrea Hewitt @ Carol @Christine @ James @Jason @Jeff @Jesse @Joanne @Megan @Shira

**Comment by lianilychee** [comment]
sent! https://dsva.slack.com/archives/CJRQ85PQB/p1623690980289100
