### ISSUE TITLE
Low frequency TypeErrors in Sentry

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25847]
TypeError when switching to eye care from another type of care:

http://sentry.vfs.va.gov/organizations/vsp/issues/38285/events/931d29013f814fa7a3d71db63882d9bc/?environment=production&project=4&query=is%3Aunresolved+vaos&statsPeriod=14d

This error is happening sporadically when someone chooses a type of care, then goes back and chooses eye care. I'm not sure what other conditions are required, possibly something where the EligibilityModal component displays immediately upon opening the facility page.

There are also a variety of other TypeErrors that affect one user at a time, but seem to be more common in the past couple weeks.

**Comment by jbalboni** [comment]
I'm adding some logging for one kind of TypeError

As for the type of care page one, I haven't been able to reproduce it, and it hasn't happened for a week now.

**Comment by laurenernest** [comment]
no additional validation needed. closing ticket.
