### ISSUE TITLE
IA Review for Rated Disabilities

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2584]
## Story  
As a member of the eBenefits team building with VSP, we need our IA reviewed to ensure it's aligns with VA.gov standards and best practices.

## Goal  
**IA:** To review the IA structure, URL and entry points and provide feedback.

We have thought about some of the impacts on IA for [**this and a few of our other features**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/impact-on-ia.md).

## Background/Helpful Info

**Mockup/Prototype:** 
- [**Rated Disabilities**](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/)
- Effort includes a single static page available to all users, and a dynamic tool/report page behind authentication.

**Context:** The Veteran will be coming to this page for 3 main things with a few secondary actions.  There are a few error states shown in the mockup as well.  We think the url might be ~https://www.va.gov/disability/my-rated-disabilities/~ _(see below)_

1. See their Total Rated Disabilities Calculation - this tells them how much benefit pay they can seek from the VA.  
  1a. In case there is an error or if the Veteran wants to learn more about this, there are some helpful links available.  
  1b. In case there is need for an adjustment, there is a link with info on that as well.  
2. See the breakdown of that calculation - in case there is more or less than expected, the Veteran can see what is included in the formula for the Total Rated Disabilities Calculation  
3. Track and manage any pending rated disabilities - in the event that there are other ratings that have not yet been accounted for, the Veteran can see their status.  
  3a. The Veteran can click for more details in the Pending Status table and be taken over to the Claim Status Tool  

**Design elements to consider:** There do not appear to be any unformatted sections in the mockup at this time, but we should note that we are not sure what will be shown in the left sidebar nav at this time.  

**User research:** 

**SEO Keywords:** 

## Acceptance Criteria
- [ ] Feedback has been shared with the eBenefits Team

**Comment by mnorthuis** [comment]
### IA Review and Feedback: 
If you have any questions, please let me know.  

**URL**
- Static page URL: www.va.gov/disability/check-disability-rating/
- Report/dynamic page URL: www.va.gov/disability/check-disability-rating/rating

This is a functional/dynamic page where users complete tasks, so we generally lead these pages with action words.  We try to avoid using "My" or "Your" when possible as they can be misinterpreted by different user roles. 

**Structure:**   
- Pages shown in site map here: https://app.moqups.com/Rnc4BDEKrA/view/page/ac5c05e4d
- This page will exist under the Disability hub as you have identified.  The actual tool will be nested below the static page.

**Navigation/Entry Points:** 
- Disability hub will include a link under the "Manage" spoke. This link will appear on the hub page as well as in the left nav as the 2nd option under the "Manage" spoke
- I would recommend that content and link also be added to the Disability Calculator tool that is currently being worked on so that users know they can log in to see their actual rating.  
- A link can also be added to the calculator from the Disability Ratings static page for users who may not have a rating or who are not logged in. 
- Also consider a link from within the Profile page.

**Crosslinking**
- Potential future enhancement is to add a link to this tool from any eligibility content where a specific disability rating is a term of eligibility.  We have taken a similar approach with the discharge upgrade tool

**Redirects**
- eBenefits technical team is handling all redirects from the eBenefits domain.

**Comment by jenniferlee-dsva** [comment]
RE:
I would recommend that content and link also be added to the Disability Calculator tool that is currently being worked on so that users know they can log in to see their actual rating.

@mnorthuis Yes, agree - great idea to add cross link on the calculator page.   @Karak888 can we create a ticket to do that when/after  the ^ new page goes live. 

@peggygannon For the H1 "View your disability rating" - Adding "VA" would greatly help SEO. "View your VA disability rating."

**Comment by jason-gcio** [comment]
We are extremely grateful for all the feedback you folks have given us.  I feel like we are pretty settled at this point but is there anything else we should address?
cc: @mnorthuis, @meganhkelley

**Comment by mnorthuis** [comment]
If you are good with the above feedback @jason-gcio,  you can close this issue when you're ready.

**Comment by jenniferlee-dsva** [comment]
@jason-gcio @mnorthuis - sorry to throw a wrench but Mikki and I are meeting tomorrow to go over some additional comments/consideration (for the static tool unauth page), per my convo w/ Steve Kovacs. Don't know if any of it will affect ^ recommendations, but wanted to give you a heads up, in case some things change.

**Comment by Karak888** [comment]
Thanks @jenniferlee-dsva - @jason-gcio I will relay any pertinent info to you (if you help me get my folders on GH cleanup up) ;)

**Comment by mnorthuis** [comment]
@jason-gcio I made a correction to the URLs above - we should be using the word "view" in place of the word "check".  That was my miss from a conversation that I had with Peggy earlier - we use "view" for data that tends to be established and not constantly changing, and "check" for data that is more dynamic (i.e. check status).  I updated the URLs in my original recommendations above.

**Comment by jason-gcio** [comment]
We will update the urls, thanks!

**Comment by jenstrickland** [comment]
Do we have time to revisit the `view` language? It is exclusive to those with vision issues. Perhaps `review` or `access` would be suitable.

**Comment by jason-gcio** [comment]
@mnorthuis, @peggygannon: please see @jenstrickland's comment above.  We can easily change whatever needs to be changed.  

Just so it is handy, here is a link to what we are working on: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/

If anyone wants a quick view of actual staging, please let me know and I can share that as well in case there are any other changes we need to make.

**Comment by mnorthuis** [comment]
Will let @peggygannon chime in on this, but @jenstrickland this is how we use the language on the site today across other tools.   "View" = view data that is relatively static, "Check" = view data that updates periodically (i.e. status).  Will see what Peggy says, but if we move away from this language, it will impact more than just this tool - which is totally fine if its the right change!

**Comment by jenniferlee-dsva** [comment]
@jenstrickland - given the above, let's not spin on "view" for the moment. We should look at this issue in context of other 508 needs and prioritize accordingly; AND IF this turns out to be a high priority, we should make this a ticket to update globally.

**Comment by peggygannon** [comment]
yes, @jenstrickland to echo @mnorthuis we use "View" to refer to info that is mostly static. And "Check" to refer to data that might change and would require updates or subsequent "checks" by the user.

**Comment by jenstrickland** [comment]
@peggygannon For when it is possible to review, "View" could be updated to "Review" in order to be inclusive for those who are blind, low-vision, or using other assistive technology that are not viewing the content but reviewing it. In the 508 audit, this will be documented, and since I saw it earlier hoped to avoid redoing work.

**Comment by mnorthuis** [comment]
@jason-gcio Do you have the eBenefits URLs that will eventually be redirected to this new tool?  If so, can you drop them here so I can add to the IA documentation?

**Comment by jason-gcio** [comment]
@mnorthuis I have https://www.ebenefits.va.gov/ebenefits/disabilities but will verify.

**Comment by mnorthuis** [comment]
The IA information above has been documented in GH:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-rated-disabilities.md

Closing this issue.
