### ISSUE TITLE
MAINTAIN - Platform Newsletter

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#25841]
carried from https://github.com/department-of-veterans-affairs/va.gov-team/issues/25250

# Description

Various tasks around keeping newsletter production chugging along.  In this sprint:

- [ ] Update the editorial cal aka process doc to account for soliciting different types of feedback (wording vs. content) at different types

Other tasks in maintenance rotation:
- Add the most recent examples to the style guide.

# Reference info
- n/a

**Comment by lianilychee** [comment]
6/14 Mon:
- will tackle after newsletter draft

**Comment by lianilychee** [comment]
6/21 Mon:
- Amy will work on draft of checkbox today, to review at SU tomorrow!

**Comment by andreahewitt-odd** [comment]
Newletter no longer exists -- closing
