### ISSUE TITLE
General Analytics Request for Chris Dyer, Caregivers

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25856]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Chris Dyer, Caregivers Team

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data, link to this Github issue, and tag `@platform-analytics`._
    
- What team/project is this work for?

    _this adds context for the data_
    - Caregivers Team, Health Care Application for (10-10EZ)
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)

I'm looking for a way to distinguish between submissions of the Health Care Application form by Logged-in Users vs Not-Logged-in Users over some period or time. It could even be just Logged In submissions vs ALL submissions of the form. Could be in the form of a table or line/bar graph.
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

Ideally as far back as we can go, otherwise perhaps after July 2020.

## Analytics to Track Down
> Examples
> 
> - User was logged in and event: caregivers-10-10cg--submission-successful <-- Most Important
> - User was logged in and event: caregivers-10-10cg--submission
> - User was logged in and event: caregivers-10-10cg--submission-failed
> - User was logged in and event: caregivers-10-10cg--submission-failed-client

## Which Product Questions are you trying to answer?

What percentage of submissions are by logged in veterans vs unauthenticated veterans?

## Other Helpful Questions to think through
- Who is your audience? Myself, Caregivers Team, HCA Stakeholders
- Why do you need this data?  To determine the percentage of veterans do not login to submit so we can tailor the experience.
- What are you hoping to find? If a higher number than expected do not log in, we may need better messaging.
- What is your hypothesis that you're hoping the data will support? That the vast majority of veterans login to submit the form.
- What area of the VA are you hoping to assess? Health Care application submissions
- How frequently do you need this data? Ideally on-demand.

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

I can try to figure out how to do the query if someone can just tell me how to distinguish logged in submissions.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@tchrisdyer - Hi! Are you all set/can we close out this ticket?
