### ISSUE TITLE
[Content review] - Test User Dashboard

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#25850]
### Description
The VSP Identity team is requesting a formal content review of the VSP Test User Dashboard web application.

#### Background
The VSP Test User Dashboard (TUD) is a tool that helps VSP Testing Tools team find Test User accounts more quickly instead of searching through the mountains of markdown in the sensitive repository.

#### Requested Items
Ideally, we would like a content review of the entire site. The TUD application has four pages the Find a test account page, Getting started page, Documentation page, and Issues page.  If there are any questions or concerns please do not hesitate to reach out to myself or in the `#vsp-identity` Slack channel.

### Relevant URLs 
https://tud.vfs.va.gov *(This URL is located behind the SOCKS proxy).
https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard (Test User Dashboard repository)
https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/tree/main/src/markdown (Markdown content)

**Comment by gmaciolek** [comment]
Hi Alex, I was out of the office for a few weeks and missed this ticket. My apologies! I'll take a look at this with our product manager today and get back to you by the end of the day with information on whether or not and when we could look into this for you.

**Comment by amygoldman** [comment]
Hey, I just sent you an invitation for a follow-up session to discuss the solution Gretchen came up with. Let us know if the suggested time doesn't work and we can reschedule!

**Comment by gmaciolek** [comment]
@AGarcia-Clarity Here are the links to our high-level recommendations as well as the Whimsical board where you can see a rough idea of how it might look if it were pared down to 2 pages:

- [Recommendations](https://vfs.atlassian.net/l/c/o1HhKpHr)
- [Whimsical wireframe](https://whimsical.com/test-user-dashboard-content-feedback-CPAoi2ehrK4SD2Aq8N3Kn3@VsSo8s35WwKKWNSYSUVT2F)

We'll wait to hear back from you before determining next steps. We're happy to help edit and revise the documentation once we know whether or not we can consolidate it all on to a single "Help" page.

- Gretchen

**Comment by AGarcia-Clarity** [comment]
👋  @gmaciolek After reviewing the high-level recommendations and speaking with Amanda we are going to move forward with reducing down to 2 pages as suggested.  Is there anything required on my part at this time as I work on fixing the high-level items?

**Comment by gmaciolek** [comment]
@AGarcia-Clarity Awesome! I can carve out some time next week to create a revised version of the "Help" content (consolidated on one page) and provide some real copy for the introductory sentences in the UI.

If I had something ready by Wednesday, would that timeline work for you? If so, I can schedule another check-in meeting and we can review the content together.

**Comment by AGarcia-Clarity** [comment]
@gmaciolek Yes, that would work for me.

**Comment by gmaciolek** [comment]
@AGarcia-Clarity My apologies, but I might have been a little overconfident in my estimate for when I could have the content ready. I'm in the middle of some other sprint work that I have to prioritize ahead of this today. Can I give you the content by Friday?

**Comment by AGarcia-Clarity** [comment]
@gmaciolek That is not a problem at all. I will update my team on the timeline.  Thank you for the update!

**Comment by gmaciolek** [comment]
@AGarcia-Clarity 

1. We've written updated [documentation and support content](https://docs.google.com/document/d/1Xqbj0o_3rrwuTGPP3PXKx9PCpakhgKR5cPuMK0hDWbM/edit?usp=sharing). There are a few comments in the document for your consideration. I also made [a copy of all the original text in another Google doc](https://docs.google.com/document/d/1YCEjBkzDMjlxvncz7mL3bDxNMdooryj2l1Tw0fr6Hv8/edit?usp=sharing) for comparison. You can use the doc with the original text in case you want to double-check that the new version isn't missing anything important and to see what we changed. 

2. Amy wrote new copy for the intro text on the main user dashboard page (see screenshot)
Recommended copy update:
Find test user account credentials you can use to sign in to the VA.gov staging environment. If you need help, check out our documentation for instructions and definitions of commonly used acronyms and terms. You can also report an issue. 

![Test user dashboard intro text](https://user-images.githubusercontent.com/3953849/126001505-9c070137-2ef0-4d97-8458-b29fcda3e5cd.png)

I assume that the pages are already built using the expand/collapse pattern and you don't want to mess around with changing that up, but if you're looking for guidance on how to implement and structure the text, I'm happy to offer suggestions.

If you have any questions and what to set up a quick check-in meeting next week, let us know!

CC: @amygoldman

**Comment by AGarcia-Clarity** [comment]
Hello @gmaciolek @amygoldman,

I started the work for the high-level updates already and was just waiting for this content 🥳 .  I am open to suggestions for the expand/collapse sections - I don't really care what we use, as long as it makes sense to the users.

I'm going to get started updating the content you and Amy provided and we can review next week to ensure I didn't mess it up.  Thank you again, you both are awesome 🏆

**Comment by gmaciolek** [comment]
Sounds great, thank you!

My thoughts for the sections would be to do one of the following:
1.  Leave the sections expanded and have a table of contents at the top that anchors down to the section headings
2. - Use a 2-column layout with a sidenav. Make each section a sidenav item. Similar to how the sections of the Design System are structured. Possibly helpful links: [2-column page template from design system](https://design.va.gov/layout/page-templates#two-columns-content-on-right) and [sidenav component](https://design.va.gov/components/sidenav)

If you go with option 2, we'd need to figure out what content goes on the main Help page, so it's probably more complex both from an implementation and a writing perspective, but it is a layout/format people are familiar with.

**Comment by AGarcia-Clarity** [comment]
@gmaciolek I would like to get this rolled out by this week so I'm going to opt for option 1. However, if in the next UX session users are having difficulties we can go for the 2-column layout (and I will create a separate ticket).

I also left some comments on the Google docs (revised v1) for some of the questions you asked.
