### ISSUE TITLE
[User testing] Combined Profile and Account: Create research plan

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2585]
Epic #2092

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/User%20Research.md

- [x] Create research plan

**Comment by sshein** [comment]
Hi all! good to see you're planning your first study, @tressaellen :) Just a reminder about process:

**Comment by sshein** [comment]
Also please refer to my research process doc for expectations around gathering notes during sessions, debriefs, and synthesis: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md

**Comment by Samara-Strauss** [comment]
Thanks for this @sshein! We're actually meeting in about an hour to go over things, but maybe you and Tressa want to meet briefly as well (though I'll leave that up to you all). I definitely didn't know about the pre-testing check in with VSP, so I want to make sure I don't miss anything or tell Tressa outdated info.

Thanks, as always, for your help and guidance! I really appreciate it!

**Comment by tressaellen** [comment]
@sshein thank you! I'm excited to get going on this! I'll make sure to utilize you for questions and advice as I start building things out.

**Comment by sshein** [comment]
cool, yep Tressa and I can chat at our next 1:1.  The pre-usability checkin is part of VSP's new "collab cycle" process- I think your team is going through it with them this coming Monday so things should be more clear at that point!

**Comment by Samara-Strauss** [comment]
My feedback:

**General**

- For easy tracking purposes, can you please link the plan to the first comment in this ticket?
- Do you need a note-taker? I didn't see any mention of that but I would call that out either way so it's clear to Lauren when she's filling out the recruiting request.

**Research questions**

These look good! Just a few thoughts:

- "How do users interact with the information on the profile?" What does this mean? Not sure what you are trying to evaluate here. I would make this more clear/specific, or take it out if you feel that it is adequately covered by other questions you've listed.
- "Can people find what they're looking for in the profile?" Just want to underscore that this is the most important question we're trying to evaluate. Let's bump it up on the list!
- We should also add "Do users understand how to update their information?" to this list.

**Timeline**

- Those research dates are too soon since the pre-usability review isn't happening. I would just leave this as TBD for now until we're more sure of exactly when we'll kick off recruiting and be able to conduct sessions.
- Also, you should give them 5 days of availability. They're pretty good at trying to cluster things into a couple of days, but there will definitely be no shows or people who need to reschedule. It's helpful to get them a range in advance so they can reschedule more easily.

**Team roles**

- Can you add Carey Otto (carey.otto@adhocteam.us) to the observer list? She asked me if she could sit in to observe any connected accounts-related things.

**Comment by tressaellen** [comment]
@Samara-Strauss thank you for the feedback, I'll make these changes.  Aricka has offered to take notes and I'm sure I can find a couple more once we know exactly when we're actually running sessions. Also, I've dropped the research in the first comment so we can keep track of things.
