### ISSUE TITLE
508 Defect 1, Launchblocker, screen readers and sighted keyboard users, Facility locater, map breaks tab order.

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#25857]
Label: 

    - [508-defect-1 :exclamation: Launchblocker]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1

Issue Title: 508 Defect 1, Launchblocker, screen readers and sighted keyboard users, Facility locater, map breaks tab order.
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
As a screen reader user, I expect to be able to tab between all clickable items on a page.

<h2>Details</h2>
When I search for a VA facility, on the main search page and the results page the tab order is interrupted by the map. When tabbing either up from the bottom of the page or down from the top, focus will not move past the map. 

<h2>Environment</h2>
In JAWS, focus moves to the top of the page. In NVDA it stays at the previous tab spot.

<h2>Steps to Recreate</h2>
<ul>
<li> Access

https://www.va.gov/find-locations/

</li>
<li> Place focus on the edit box labeled "City, State or Postal Code."</li>
<li> Attempt to tab past the map.</li>
</ul>

**Comment by laflannery** [comment]
I believe this is resolved.  Will close in 1 week unless told otherwise
