### ISSUE TITLE
[BE] Profile: Work needed to support contact info update email

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25865]
## Background
Per discussion in #25360 we need to send a user an email confirming that they updated a piece of their contact information. In the case of email updates this message will need to be sent to both the old email address and the new one.

## Tasks
- Use VANotify to notify user whenever their contact info changes
- Save old email address when user updates their profile email and notify both email addresses on email change

**Comment by lihanli** [comment]
@ajakabcin the pr for this issue has been merged, do you want to release to a percentage of users first or release to everyone?

**Comment by ajakabcin** [comment]
@lihanli let's release to all users - thanks!
