### ISSUE TITLE
Past Appts list does not reset correctly when navigating away from page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25875]
## What happened?
When a date range is selected from the Past Appointments picker (ex: **All of 2020**), navigating to Upcoming Appointments and then back to Past Appointments results in the following:
     - Picker resets to **Past 3 months** (correct)
     - Appointments in the list still reflect **All of 2020** (incorrect)

## Specs:
- Device: iPhone 11
- Test user: judy.m

## Steps to Reproduce
1. Go to Past Appointments and select **All of 2020**
     - Observe how the appointments in the list are all from 2020
2. From the segmented selector, navigate to Upcoming Appointments
3. Go back to Past Appointments
4. Notice that the date range picker has reset to **Past 3 months** (correct), but the appointments in the list below still reflect the list from **All of 2020** (incorrect)

## Desired behavior
1. When navigating away from the Past Appointments page, the date range picker should reset to **Past 3 months** and the appointments in the list should reflect that date range

## Acceptance Criteria
See desired behavior above.

## Bug Severity
- 3 - Medium

## Linked to Story
n/a

## Screen shot(s) and additional information
![Image from iOS (25).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/1e8c5fa7-5737-48b2-8c7f-19d4d978b4aa)

**Comment by digitalken** [comment]
PASS 6/28/2021 - Date picker resets on both iOS and Android.  Closing.
