### ISSUE TITLE
Analytics Implementation or QA Support for eBenefits (View Representative)

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#25876]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

Implimentation.

- Who is this request for?

    - Jesse Cohn
    _Provide any relevant contact information and link this issue on the DSVA Slack Channel: `#VFS-Platform-Support` and tag `@platform-analytics`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - Ebenefits Team for the View Representative project
    
- Provide the Domain where Google Analytics needs to be implemented
    
    _Identify if PII is passed in URL or title tag_
NA
    
    - VA.gov
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - As soon as possible

- Please provide website interactions to Track

 we want to track when the page loads if it loaded with a 200 response, a 400 response, or a 500 response as well as some detail about the 400 or 500 error if there was one. It will be basically the same as the implimentation we made on View Payments [here](https://github.com/department-of-veterans-affairs/vets-website/blob/b8284b4b43ce52ff543f159ba8edc3eb8aa71377/src/applications/disability-benefits/view-payments/actions/index.js#L27)

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Any test user will work

- Certain conditions/responses that need to be reviewed

    - NA

- Additional Comments

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by bsmartin-ep** [comment]
@cohnjesse -

If we follow the pattern of other API events, something like this?

```js
{
    event: 'view-representative-retrieved'
}
```

```js
{
    event: 'view-representative-failed',
    'error-key': '500 your error message'
}
```

**Comment by cohnjesse** [comment]
@bsmartin-ep That works for me. So the 400 error would look like this then, correct?

```javascript
{
    event: 'view-representative-failed',
    'error-key': '400 your error message'
}
```

**Comment by laurensimpson14** [comment]
@cohnjesse Yes! Correct.

**Comment by joanneesteban** [comment]
@cohnjesse Hello! Were you able to make the change on this? Thanks!

**Comment by jason-gcio** [comment]
@joanneesteban / @laurensimpson14 
Just to close the loop on this, here is the mockup for this feature :https://xd.adobe.com/view/e27b7e71-d920-4bcd-9e81-dc62a9665d5e-b728/

We want to see if there is anything else on this that is not standardized.

**Comment by joanneesteban** [comment]
Thanks, @jason-gcio ! We'll have @bsmartin-ep take a look when he returns next week and get back to you.

**Comment by bsmartin-ep** [comment]
@jason-gcio -

Things like the table of content links, telephone links, "more info" controls (probably) should be tracked by default.

Button clicks are usually something you need to add-in manually (no actual button component to use).

Is there a particular interaction you are interested in?
