### ISSUE TITLE
Redirect Request - Vet Center MVP pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#25885]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

When a Veteran selects a facility from the Facility Locator search results, that location's facility detail page is displayed. As the new Vet Center pages are rolled out, the existing Facility Detail pages for the specific locations will be archived and Veteran will be taken to the new page, based on Lighthouse API url logic. This redirect is intended to assist visitors who may arrive to the page via outside links. 

The first 10 Vet Center web pages are expected to roll out ~June 21. Note: Outstations and Mobile Vet Centers have their own Facility Detail pages but will be part of their respective main Vet Center's Location page. 

### Requesting team info
*Indicate what team and who the primary contact on that team is*
Facilities team
Michelle Middaugh, PM

### Implementation date
Date new URL(s) will be live: *June 21*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [x] Can happen within 1-5 business days **after** new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Vet Center | Current URL  |  Redirect Destination or New URL
---  | ---  |  ---
*For reference* | *enter current URL* | *enter new URL*
Springfield, MA | www.va.gov/find-locations/facility/vc_0103V | va.gov/springfield-ma-vet-center
Orlando, FL | www.va.gov/find-locations/facility/vc_0314V | va.gov/orlando-vet-center
Escanaba, MI | www.va.gov/find-locations/facility/vc_0434V | va.gov/escanaba-vet-center
Escanaba, MI Mobile| www.va.gov/find-locations/facility/vc_0826mvc | va.gov/escanaba-vet-center
Reno, NV | www.va.gov/find-locations/facility/vc_0506V | va.gov/reno-vet-center
Reno, NV MVC | www.va.gov/find-locations/facility/vc_0867MVC | va.gov/reno-vet-center
Colorado Springs | www.va.gov/find-locations/facility/vc_0525V | va.gov/colorado-springs-vet-center
Nashville, TN | www.va.gov/find-locations/facility/vc_0724V | va.gov/nashville-vet-center
Clarksville Outstation | www.va.gov/find-locations/facility/vc_7241OS | va.gov/nashville-vet-center
Cincinnati, OH | www.va.gov/find-locations/facility/vc_0204V | va.gov/cincinnati-vet-center

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [x] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@mmiddaugh When are you looking for the redirects to be in place?  I see the new URLs will be live by June 21, I'm assuming these do not need to go live on that day, but probably soon after?

**Comment by mmiddaugh** [comment]
Thanks @mnorthuis - you're correct -> soon after. They won't necessarily go live exactly on the 21st due to content review. That's the goal date.

**Comment by mnorthuis** [comment]
@brianalloyd This one is ready from my perspective, please see note regarding timing - not to be implemented until new URLs are live.

@mmiddaugh Please use this ticket to indicate any changes in timing, and let everyone officially know when the new URLs are/will live, so Brian and team can coordinate the publishing of the redirects. 


**Please ensure redirects accommodate both upper and lower casing of the final slug in the legacy URLs.**

**Comment by brianalloyd** [comment]
Thanks @mnorthuis for the notification, we'll scrub in.  @mmiddaugh we'll hold until you let us know once these have gone live, then we'll kickstart the publishing of the redirects as mentioned keep us updated if those dates slip or you need anything in support.

**Comment by brianalloyd** [comment]
@kelsonic holding on this until we get a green light from @mmiddaugh concerning the above deployment DTG. Once these have all gone live we can initiative the redirects.  Including the below for emphasis:

**Please ensure redirects accommodate both upper and lower casing of the final slug in the legacy URLs.**

**Comment by kelsonic** [comment]
PR is up for the redirects: https://github.com/department-of-veterans-affairs/devops/pull/9429 Will hold off merging/deploying until we get the green light from @mmiddaugh 👍

**Comment by brianalloyd** [comment]
@mmiddaugh following up on this ticket, we've got a PR on hold, let us know once you have confirmed you would like this released.  No pressure, I just don't want our team to be the blocker on this action.  Thanks.

**Comment by kelsonic** [comment]
@mmiddaugh Any update?

**Comment by kelsonic** [comment]
Moving this to blocked

**Comment by brianalloyd** [comment]
Shifting to next sprint in support.  @mmiddaugh I know you all are still working details, just let us know when sea state changes, thanks.

**Comment by brianalloyd** [comment]
@mmiddaugh checking in on this ticket, I know you're working lots of actions right now and didn't want to drop the ball on these redirects if ready.  Thanks.

**Comment by davidconlon** [comment]
@mmiddaugh @brianalloyd - 
To move this one forward a bit. We're going to remove from this issue:
- Rochester
- Rochester Mobile
- Great Falls
- Concord
And @brianalloyd will add these to a new ticket in PW backlog that will track the next batch of redirects to push forward.
@brianalloyd can you be sure to assign that issue to @mmiddaugh and tag it with both product tags.

@mmiddaugh can then progressively add the sites as we publish them to that issue and we can coordinate between teams when we think we've hit the 'sweet spot' to pull that issue into a sprint and create a new one for the backlog to collect redirect links for the next batch

**Comment by mnorthuis** [comment]
@brianalloyd can you please use the redirect template on the new ticket so I can keep documentation up to date?  You can immediately assign it to yourself and don't need to wait for me, I just want to stay informed.  Thanks!

**Comment by brianalloyd** [comment]
@mnorthuis will do, I've got you and @mmiddaugh on the new ticket [#28651](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28651) that included the 4x facilities that were not redirected and is ready to populate with sites as they are published for the next batch ISO Vet Centers MVP 1.0.

**Comment by brianalloyd** [comment]
Redirects validated, closing out ticket in support.
