### ISSUE TITLE
Add fire CMS GovDelivery callback step to content-build

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25883]
From: Adrian (CMS team)
1. Add the fire CMS GovDelivery callback step (code referenced in the first post of this thread) that lived in the vets-website build to the content-only build, so that the build will trigger govdelivery notifications once new status updates are live on VA.gov
2. Update the timestamp var in that step to use the time when the query for status updates was run, so that notifications will only get sent for status updates that are already live on VA.gov

Relevant Slack threads 
* [CMS Team requesting the work](https://dsva.slack.com/archives/CBU0KDSB1/p1623175952260500?thread_ts=1623098996.224800&cid=CBU0KDSB1)
* [Discussion with Ops about who should own the work](https://dsva.slack.com/archives/CJYRZK2HH/p1623244575146000)

CMS Team needs this completed to deliver functionality by end of month — we should keep them posted on our timeline for this.

**Comment by timwright12** [comment]
PR open to adding timing data to the build process https://github.com/department-of-veterans-affairs/content-build/pull/308

**Comment by timwright12** [comment]
@indytechcook @ElijahLynn 
Looking through the logs I see this error:

```
16:13:57  TASK [deploy-content-build : fire CMS GovDelivery callback] ********************
16:13:57  Friday 09 July 2021  20:13:57 +0000 (0:00:00.418)       0:02:16.093 *********** 
16:13:57  fatal: [localhost]: FAILED! => changed=false 
16:13:57    content: ''
16:13:57    elapsed: 0
16:13:57    msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno -2] Name or service not known>'
16:13:57    redirected: false
16:13:57    status: -1
16:13:57    url: https://internal-dsva-vagov-prod-cms-812329399.us-gov-west-1.elb.amazonaws.com/api/govdelivery_bulletins/queue?EndTime=1625860976
```

Do some permissions need to be opened up to allow the deploy to hit that URL?

**Comment by ElijahLynn** [comment]
> @indytechcook @ElijahLynn
> Looking through the logs I see this error:
> 
> ```
> 16:13:57  TASK [deploy-content-build : fire CMS GovDelivery callback] ********************
> 16:13:57  Friday 09 July 2021  20:13:57 +0000 (0:00:00.418)       0:02:16.093 *********** 
> 16:13:57  fatal: [localhost]: FAILED! => changed=false 
> 16:13:57    content: ''
> 16:13:57    elapsed: 0
> 16:13:57    msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno -2] Name or service not known>'
> 16:13:57    redirected: false
> 16:13:57    status: -1
> 16:13:57    url: https://internal-dsva-vagov-prod-cms-812329399.us-gov-west-1.elb.amazonaws.com/api/govdelivery_bulletins/queue?EndTime=1625860976
> ```
> 
> Do some permissions need to be opened up to allow the deploy to hit that URL? I can see the exact same code running in vets-website

Thanks for this Tim! I think I missed this in the bigger picture of how the job is run, and I was only looking at the content-only-build. Great to see that this Ansible Task is running, that was the part that I was missing. 

I'll look into the request failure in a bit and can figure that part out.

**Comment by ElijahLynn** [comment]
> ```
> 16:13:57    url: https://internal-dsva-vagov-prod-cms-812329399.us-gov-west-1.elb.amazonaws.com/api/govdelivery_bulletins/queue?EndTime=1625860976
> ```

K, this is because that balancer address is incorrect and doesn't exist. 

That is actually the DEV balancer ID > https://internal-dsva-vagov-dev-cms-812329399.us-gov-west-1.elb.amazonaws.com, must have been copy/pasted and updated with PROD once upon a time. Now that we have Route53, we can actually use prod.cms.va.gov. I'll make a PR to update that now.

**Comment by ElijahLynn** [comment]
> I'll make a PR to update that now.

https://github.com/department-of-veterans-affairs/devops/pull/9569

**Comment by ElijahLynn** [comment]
> > I'll make a PR to update that now.
> 
> [department-of-veterans-affairs/devops#9569](https://github.com/department-of-veterans-affairs/devops/pull/9569)

Cool, this is [tested, working and merged](https://github.com/department-of-veterans-affairs/devops/pull/9569#issuecomment-880252440)!! I think this is closeable now!

**Comment by timwright12** [comment]
@ElijahLynn awesome!! Closing out. Let me know if you discover that we need to reopen it
