### ISSUE TITLE
FSR List Loop Redesign

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#25881]
## Issue Description
When Veterans incur a debt with the VA and cannot pay the full amount, they're able to request financial help via the Financial Status Report (VA Form 5655). The Financial Status Report (FSR) collects a snapshot of a Veteran's monthly financial situation. The form asks Veterans to include a list of utilities, assets, etc. To help Veterans quickly add multiple items of the same category, we designed a list loop component. However, the component tested poorly during usability research. Additionally, the component is inaccessible to screen readers. Finally, because the list loops are customized components they're tedious to update and contain many bugs. 

## The solution
The FSR's UI has been redesigned to remove the list loop components. This redesign will use patterns and components that exist in either VA.gov's experimental or established design systems. 

[The FSR's updated designs can be accessed in this UXPin prototype.
](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/no-panels?mode=i) Please note: this is an in-progress design as of 4/29/2022. 

### The redesigned pages

- [Veteran's contact information](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/147887481/comment/no-panels?mode=i)
- [Veteran's employment history](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842695/comment/no-panels?mode=i)
- [Veteran's other income](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146220344/comment/no-panels?mode=i)
- [Spouse's employment history](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868493/comment/no-panels?mode=i)
- [Dependents](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022114/comment/no-panels?mode=i)
- [Financial assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084977/comment/no-panels?mode=i)
- [Real estate](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146385053/comment/no-panels?mode=i)
- [Vehicles](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145354965/comment/no-panels?mode=i)
- [Trailers, campers, boats](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145355886/comment/no-panels?mode=i)
- [Other assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084980/comment/no-panels?mode=i)
- [Household expenses](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022052/comment/no-panels?mode=i)
- [Utility bills](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145111152/comment/no-panels?mode=i)
- [Credit card bills](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145377491/comment/no-panels?mode=i)
- [Other debts](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482543/comment/no-panels?mode=i)
- [Other living expenses](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146358669/comment/no-panels?mode=i)

**Comment by rileyorr** [comment]
@denisecoveyduc just updated the ticket and linked to the list loop mockups! I'm happy to answer any questions or meet whenever y'all have a chance to dig into the designs and want to discuss 🚀

**Comment by denisecoveyduc** [comment]
@rileyorr That's great thank you!!! I set up touchpoint for Thursday May 5th.. let's sync up with @OptionSelect and @Dr-Pongo then as an intro call. We can level set on next steps at that time.

**Comment by rileyorr** [comment]
Cross-posting [the 21-686 form](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/introduction) so we have it to reference when we start digging into the new list loop pattern of adding pages. Test-user-1 seems to work!
