### ISSUE TITLE
Decide on protocols for auditing dependencies and addressing security vulnerabilities

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#25896]
### Automated security audits

The `security-check` job in CI currently runs on every pushed commit. When it discovers vulnerabilities in a PR's CI run for unrelated reasons, it's particularly disruptive, and PR authors are blocked from merging until Platform pushes the dependency resolution or upgrade.
- Should this job run on a schedule rather as part of CI?
- How frequently should this job run?
- Would Dependabot be adequate for dependency auditing?
    - What's the effort involved in configuring it to do what we need it to do?
    - It's third-party functionality, so doesn't require maintenance on our part.
    - It automatically creates patch PRs.

### Auditing dev dependencies

The `security-check` only checks `dependencies` and not `devDependencies`. Currently, running `yarn audit` across all dependencies will yield hundreds of high severity vulnerabilities.
- Do we want to start checking for vulnerabilities in `devDependencies` as well?
- What's the process or priority of patching those? If low, maybe not worth including them in checks.
- MIght be less of an issue when we begin upgrading dependencies again after app isolation.

### Dependency patching process

Part of our strategy for patching vulnerabilities, at least for sub-dependencies, is setting resolutions in `package.json`.
- Should we establish a procedure for removing those resolutions when we upgrade top level dependencies (the ones that we actually use)?
- If we just have Dependabot to do it automatically, this might not matter.
- Should we continue using resolutions when patching or just update `yarn.lock` (like how Dependabot usually does it)?

### Relevant Threads
- https://dsva.slack.com/archives/GLDNCMRSP/p1623161747175500
- https://dsva.slack.com/archives/CQH357ZTP/p1623165834058900

## Definition of done
- [ ] Decision is documented, and if necessary, work is planned for changing the `security-check` job in CI.
    - Run on a schedule in a separate pipeline?
    - Remove entirely in favor of Dependabot?
    - Some other alternative?
- [ ] Decision is documented, and if necessary, work is planned for including `devDependencies` in security check.
- [ ] Document either (1) a standard process for patching dependencies to address vulnerabilities or (2) decision for using any automated tools to accomplish the same goal.

**Comment by meganhkelley** [comment]
See also: #4092

**Comment by jhonnyoddball** [comment]
Expired. Closing
