### ISSUE TITLE
Support pagination in preview mode

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#25895]
The preview server does not support pagination on static pages.

To do so, we would need to change the preview server to look for a `page` query parameter and pass that into the `paginatePages` filter.

**Comment by mmiddaugh** [comment]
This issue is being returned to the icebox after a conversation with engineering about the level of complexity and value add.

**Comment by mmiddaugh** [comment]
no longer needed
