### ISSUE TITLE
Spike: Audit/Logging

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#25897]
Questions:
- What are best practices?
- Is cloudwatch an option?
- How could cloudwatch be set up for audit trail purposes?
- Do we need to worry about this for Pre-MVP?

**Comment by calquisola** [comment]
Cloudwatch is a good starting point for logging our aws lambda.  Set up is simple, we just need to choose a role to our lamdba function with cloudwatch access.

**Comment by calquisola** [comment]
For pre-MVP,  we should at least enable cloudwatch.
