### ISSUE TITLE
Phase 2: Investigate Cypress test failures on GitHub Actions and implement a fix

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#25893]
Cypress tests are failing occasionally on GitHub Actions with two different errors. Cypress is unable to load pages that are being tested, causing the failures. These failures have not occurred on Jenkins. Two different error messages appear:

```
     CypressError: The XHR server is unavailable or missing. This should never happen and likely is a bug. Open an issue if you see this message.
```

```
     CypressError: `cy.visit()` failed trying to load:

http://localhost:3001/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3001
```

This task is to determine the root cause of these failures and implement a fix.

Examples of failing builds:
* https://github.com/department-of-veterans-affairs/vets-website/runs/2785545883?check_suite_focus=true
* https://github.com/department-of-veterans-affairs/vets-website/pull/17515/checks?check_run_id=2787788541

**Comment by ddzz** [comment]
The fix for this will likely be included in the PR that parallelizes Cypress tests on GHA: https://github.com/department-of-veterans-affairs/vets-website/pull/17515

**Comment by ddzz** [comment]
The failures appear to be caused by port conflicts on self-hosted runners used for E2E tests on GitHub Actions. Port usage will be randomized in order to prevent conflicts.

**Comment by pjhill** [comment]
Port randomization solution is in place and appears to be working as intended.
