### ISSUE TITLE
Display Mochawesome E2E Test Summary in GHA Check

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25900]
# Description
* Use [Mochawesome Report Generator](https://www.npmjs.com/package/mochawesome-report-generator) to create a nicely formatted report with inline video playback for the Cypress E2E test results in GitHub Actions.
* Feed the JSON used to build the MARGE report into BigQuery
* Leverage the MARGE HTML report somehow in the QA Dashboard

## Reference Material
* [How to merge Cypress test reports on GitHub Actions](https://docs.knapsackpro.com/2020/how-to-merge-cypress-test-reports-generated-by-mochawesome-on-github-actions)

**Comment by holdenhinkle** [comment]
The following functionality required to enable the use of Mochawesome report data to be stored in BigQuery and for the Mochawesome report to be generated has been added to the  [Testing Tools Team Dashboard Data repo](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data):

See the [`/src/mochawesome` directory](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/tree/master/src/mochawesome):
- update the paths to the failed-test videos in each `json` results file
- merge all the `json` results files
- generate the mochawesome report
- write the BigQuery schema for the `cypress_test_results` and `cypress_test_suite_executions` tables
- create the row data for the `cypress_test_results` and `cypress_test_suite_executions` BigQuery tables
- insert the Report data into the tables

Additionally, I have a [draft PR for setting up Mochawesome for Cypress test results](https://github.com/department-of-veterans-affairs/vets-website/pull/16655), which includes embedding the videos of the failed tests in the Mochawesome report. More information can be found in this ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22332

I'm waiting for Cypress parallelization in GHA to be merged and for the current Cypress issues to be sorted out. Once that's complete, I'll get started on implementing this in GHA.

**Comment by holdenhinkle** [comment]
This work is done.

**Comment by pjhill** [comment]
Indeed, this work is done! Thanks Holden!
