### ISSUE TITLE
Error when fetching scheduling configurations 

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25903]
User: judy.morrison@id.me
URL tried: https://staging-api.va.gov/vaos/v2/scheduling/configurations?facility_ids=983&ccEnabled=true

`{"errors":[{"title":"Bad Request","detail":"Request scheduling/configurations missing required parameter: facilityIds","code":"VAOS_400","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/facilities/v2/scheduling/configurations?pageSize=0","vamfBody":"{\n  \"code\" : 400,\n  \"message\" : \"Request scheduling/configurations missing required parameter: facilityIds\",\n  \"traceId\" : \"34a8ae8caf2973b2\"\n}","vamfStatus":400},"status":"400"}]}`

Looks like two things going on:

1. facility_ids should be transformed into facilityIds in the vaos-service request. 
2. I don't see the ccEnabled param passed through

**Comment by ajmagdub** [comment]
The passing in the ccEnabled query param to the VAMF Mobile Facility Service does not seem to affect the results. Also placing ccEnabled first when ordering the query parameters causes the Mobile Facility Service to return a 400 error. [VAOSR-2021](https://issues.mobilehealth.va.gov/browse/VAOSR-2021) submitted.
