### ISSUE TITLE
Issue when calling /vaos/v2/facilities

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25906]
User: judy.morrison@id.me

I get the same results with both of these urls:
https://staging-api.va.gov/vaos/v2/facilities?ids=983
https://staging-api.va.gov/vaos/v2/facilities?ids=983&children=true

If that parameter is getting passed through correctly (and the vaos-service is using it correctly), I would expect to get more results in the second call, but both times I get one result back.

**Comment by grossb1** [comment]
This is currently blocked by:
https://issues.mobilehealth.va.gov/browse/VAOSR-2045

**Comment by ajmagdub** [comment]
Looks like VAOSR-2045 has been resolved and is in staging. This ticket is no longer blocked. The Vets Api can now be checked against the VAMF VAOS Service.

**Comment by jbalboni** [comment]
This looks like it's working in staging now, so I'll close it.

**Comment by cferris32** [comment]
This has been resolved with [#7407](https://github.com/department-of-veterans-affairs/vets-api/pull/7407) - our most recent spec recordings show expected results back from the facilities endpoint, with multiple facilities being passed back when children=true
