### ISSUE TITLE
Document the ExpandableOperatingStatus component

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#25905]
Add documentation on the [ExpandableOperatingStatus](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/shared/ExpandableOperatingStatus.jsx) component to the Experimental Design System.

See https://design.va.gov/documentation/contributing-to-the-design-system#5-document-and-submit

**Comment by mmiddaugh** [comment]
no longer needed
