### ISSUE TITLE
Add missing appeals statuses to app

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va.gov-team#25913]
While adding missing appeals event phase titles it was noticed that web also had a number of appeals statuses which the app currently doesn't have. Those statuses should be added to the app. 

Missing statuses:
amaRemand*
statutoryOptIn 
evidentiaryPeriod
postBvaDtaDecision
bvaDecisionEffectuation
scReceived
scDecision
scClosed
hlrReceived
hlrDecision
hlrDtaError
hlrClosed
remandReturn

*empty case on web, put in switch on web just to avoid the default case

**Comment by jperk51** [comment]
QA notes: 
User to trigger mock appeal: vets.gov.user+226@gmail.com
The current appeal has the `status.type` of `sc_received`. To trigger different statuses open `appealData.ts` and change `status.type` to whichever of the below list you want to check. 
`'ama_remand'
'statutory_opt_in'
'evidentiary_period'
'post_bva_dta_decision'
'bva_decision_effectuation'
'sc_received'
'hlr_received'
'hlr_decision'
'hlr_dta_error'
'sc_decision'
'sc_closed'
'hlr_closed'
'remand_return'`

**Comment by digitalken** [comment]
PASS 7/8/2021 - Passing on the basis of 'sc_received' as I'm unable to change anything on the devices.  Closing.
