### ISSUE TITLE
SPIKE: Establish Data Structure

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25911]
As a part of the Check In project, we need to facilitate parallelization and concurrent work on the λ. 

**We need to know**
1. What information we are saving into the database
2. What information is being passed
3. What information we're accessing
4. What information we're passing back

**Win Conditions**
A documentation of structure for future reference

**Comment by kjduensing** [comment]
For the Pre-MVP, payload to include: 

- `locationIEN`
- `sta3n`
- `facilityName`
- `a patient identifier (ICN or DFN)`

```javascript
UUID: {
  config: {
    validStart: x,
    validEnd: x,
    ttl: x,
    canRefresh: x,
    additionalValidation: ['x', 'y', 'z']
  },
  payload: {
    <just the exact JSON object they send us>
  }
}
```
