### ISSUE TITLE
Prep Tasks for Research: Find a Form PDF Downloading

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25912]
## Issue Description
_Tasks needed in support of upcoming research project_

## Preparatory tasks
- [ ] Share research plan and conversation guide with Lauren Alexanderson for approval and recruiting
- [ ] Make note-taking spreadsheet
- [ ] Schedule pilots
- [ ] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [ ] Run pilots
- [ ] Debrief pilots 
- [ ] Revise conversation guide
- [ ] Send instructions to observers
- [ ] Review recruited participant list for requirements met
- [ ] Make sure all research sessions are in my calendar
- [ ] Schedule team debrief sessions once a day
- [ ] Followup with Perigean re participant list
- [ ] Other tasks as needed 

## Acceptance Criteria (AC)
- [ ] All set to start research sessions

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO This is a Find a Form prep tasks ticket that Brian created a while ago, so you might want to take this over, plus the Research Sessions, and Synthesis and Reporting tickets from my baseline wayfinding research for Public Websites.

**Comment by cindymerrill** [comment]
@brianalloyd could probably point you to the other 2 research tickets, @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
Thank you! I will create equivalents in about an hour or so.

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill Thanks - I located them all yesterday. Just haven't had a chance to create them in our backlog.

**Comment by cindymerrill** [comment]
Closing because a new Decision Tools ticket was created for this. @MarciMcGuireGCIO @brianalloyd
