### ISSUE TITLE
Bug - Fix UI for expandable operating status icon padding on IE

### ISSUE THREAD

**Issue by brangi** [department-of-veterans-affairs/va.gov-team#25923]
Issue : https://dsva.slack.com/archives/C0FQSS30V/p1623261494083800

<img width="1104" alt="Screen Shot 2021-06-10 at 12 36 55 PM" src="https://user-images.githubusercontent.com/100468/121571651-e9f9f400-c9e8-11eb-9b5a-af4645dbc164.png">

**Comment by mmiddaugh** [comment]
@brangi the padding still looks odd in IE - I viewed it in preview: 
![image](https://user-images.githubusercontent.com/55411834/122302870-f0dca700-cebf-11eb-9cc1-784d3a8ec8b4.png)

**Comment by mmiddaugh** [comment]
Fix looks good! Thank you 
![image](https://user-images.githubusercontent.com/55411834/123454348-afbe5400-d59d-11eb-8f4f-5e0d9563f2ce.png)
