### ISSUE TITLE
Access for Cesar Santiago

### ISSUE THREAD

**Issue by cesaresantiago** [department-of-veterans-affairs/va.gov-team#25926]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Laura Ross
- Please provide your name.
   > Cesar Santiago
- Please Provide your email.
   > cesar.santiago@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > My Education Benefits Team. Company: Accenture Federal Services

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkF5WtVnSEE6b+KrUGojBuy1HvHeLrcg2D2vHCwmGqYnt6QR55lPkIPWy5OxjK9c+mTpk6WSSDA4TxI6R/Zqac9D34IVxdB6/eg2ivDeYhqyatFmBkfGo0cIJcZFnCJ9hu8jUkY6jKkpsGipFyTGc62qthmaw4joEP2e57DKa8p2Zqe0u5YbuvrMfNynM44Zi39zWxZgz9iy7H57PfwEe72sUWfzVOwD28UqTpEhUeakuLRqz7yd0nwmimM5muqRxqXIuTO5Ksjq6OQ33DJHwGcOmn3gXYFbMhn0eBgK50ytcuYH6PLwzCq04u+8Hjc66gbXR49VjzdkTTrMevpqYOGRt0kFM718xP0X6kDwI23BMVLLJYjMkxYvpqCl0u8WR1ZXmCFeMWthEjRijgCymbER4TkjXRCDwdg2gErVsz92XnwDb7Haz/JEVxj60BJsOXaPykctgms5PFirzKTKGDJnR/PcgwpwbHmiIoIOLrUZmJwFfC/8Tu32jU+nxYK0M= cesar.santiago@AFSMWSZH33VJBBW
```

- Grant AWS Console access?
  >NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
