### ISSUE TITLE
Quality Assurance Feedback - Midpoint Review - Authenticated Experience, Preferred Facilities

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25920]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- Similar to the feedback provided in a related Midpoint Review -- thanks for creating some [draft test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-preferred-medical-facility.md#preferred-medical-facility-testuse-cases--users-your-va-health-facilities)! Please consider, using [TestRail](https://dsvavsp.testrail.io/) instead of creating the test cases in markdown.
- Previously, you responded that specific test user accounts would be determined once development for the product was underway.  That makes sense, but please be sure to update the test cases to include those specific test accounts for all cases.

**Consider:**
None

**Comment by ajakabcin** [comment]
Thanks Peter! We'll update all test cases with user info when we get into development.
