### ISSUE TITLE
IA Feedback - Midpoint Review [Authenticated Experience, Preferred Facilities]

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#25921]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-  Are you planning to make the profile menu active to allow users to click it?  Understand this is not part of the flow that is being tested, but could be something users look at they link over from VAOS in an effort to understand where they are or where to go next. 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Prototype is missing the breadcrumb [18]

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by andaleliz** [comment]
Hey Mikki, sorry that it wasn't clear that the research had already happened and you spent your time on this.
