### ISSUE TITLE
Analytics not showing up

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#25928]
In GA, the custom user properties are not showing up. The user setting names are visible, but all of the settings on users are showing in GA as `not set`

We will need to review the implementations and see why the custom setting values are not passing through to GA.

**Comment by lexicalninja** [comment]
We figured it out. We need to create the custom fields in GA so that it picks everything up. Any time we add a custom user prop we need to also add it to GA. 

This ticket will go and create the custom props in GA

**Comment by travis-newby** [comment]
I created the custom dimensions for our current set of user settings.

**Comment by travis-newby** [comment]
AFAIK this one can be closed. We've created custom dimensions for all user properties in the app.

**Comment by lexicalninja** [comment]
yep!
