### ISSUE TITLE
[Research] Draft research plan & convo guide: Find a Form PDF Downloading

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25924]
## Issue Description
Research ticket to draft research plan and conversation guide to support #25247. Now new ticket: Find a VA Form: Flesh out PDF download instructions #26050

## Acceptance Criteria
- [x] Draft research plan 
- [x]  Draft conversation guide
- [x] Share both with another researcher, Marci, John, Cassandra, Josh
- [x] Incorporate all feedback 
- [x] Discuss recruiting and launch with Lauren

**Comment by cindymerrill** [comment]
Started drafting research plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-plan.md

**Comment by cindymerrill** [comment]
Revised research plan per discussion with Marci yesterday. Shared out for feedback.

**Comment by cindymerrill** [comment]
Drafted conversation guide and shared out for feedback previously (copied this comment from another ticket): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/conversation-guide.md
Need to revise more based on feedback.

**Comment by cindymerrill** [comment]
Revised research plan and convo guide today.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cindymerrill !

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 52 since the decision to conduct an A/B test will require changes to the research plan & conversation guide.

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill - capturing what we discussed in our 7/15 meeting: 

- Earlier this week Shawna suggested an A/B test and the PO and rest of the team were on board with that
- We now want to test how users respond to a version with a single alert at the top as compared to a version with alerts that appear alongside each PDF link
- The original timeline will pushed out by a couple of days, but testing both versions is feasible
- Cindy recommends testing half the users with one version and half with the other based on her experience
- Zach will start tomorrow prepping two versions for Staging
- Should be live Tue afternoon (July 20)
- Cindy will review shortly thereafter and get w/Perigean for test subjects
- Perigean needs a full week to recruit
- Cindy will conduct Pilot review later next week
- Research sessions will start on or around July 27

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO  Revised my [research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/conversation-guide.md) for Find a Form PDF Downloading to reflect the addition of an A/B test since we want to test two different designs. Feedback is welcome until end-of-day Monday July 19. 

Research sessions are currently scheduled for July 27-30 with pilot tests on July 22-23.

**Comment by cindymerrill** [comment]
Revised research plan and conversation guide based on feedback received. Asked a few followup questions via slack; when hear back tomorrow (Tue 7/20), will make final changes and then share with Perigean to launch recruiting.

**Comment by cindymerrill** [comment]
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/conversation-guide.md) are ready for today's pilot test, so closing this ticket.
