### ISSUE TITLE
[repo migration]: Analytics

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2592]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1MBhSpKXM1Vz-PAkn6_QMagWZRgWr1rusy1Yg6J_-L5Q/edit#gid=930462618

**Comment by johnpaulashenfelter** [comment]
@thatmattjohnson @meganhkelley I don't have access to this gDoc

**Comment by thatmattjohnson** [comment]
access granted

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/3494

and

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19981

**Comment by thatmattjohnson** [comment]
Approved #3494; requested updates for #19981.

**Comment by johnpaulashenfelter** [comment]
Updates to deprecation messages are complete https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19981

**Comment by thatmattjohnson** [comment]
Approved updates to #19881.

**Comment by thatmattjohnson** [comment]
UAT:

#3494: **not completed -- one file still requires migration:**
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Insights/Analytics/Get_Access/Opting-Out.md

**Comment by thatmattjohnson** [comment]
update #19881 to include this file:

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Insights/Analytics/Get_Access/Opting-Out.md

**Comment by johnpaulashenfelter** [comment]
This file was renamed after the migration:

```
6393f1a0 [3 days ago] (Nedie Recel) Rename platform/analytics/opting-out-google-analytics.md to platform/analytics/google-analytics/opting-out-google-analytics.md
28468d92 [3 days ago] (Nedie Recel) Update and rename opting-out.md to opting-out-google-analytics.md
9c4212ca [3 days ago] (Nedie Recel) Create rules-of-engagement-request-review.md
e6bacc17 [3 days ago] (John Paul Ashenfelter) Migrate analytics documentation from vets.gov-team (#3494)
```

**Comment by thatmattjohnson** [comment]
Thanks for clarifying re: #3494.

Re: #19881: link redirect in deprecation message should be the following: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics

**Comment by thatmattjohnson** [comment]
UAT completed for #19881; all looks good. closing this issue.
