### ISSUE TITLE
Access for Haidong "Alex" Ji

### ISSUE THREAD

**Issue by haidong** [department-of-veterans-affairs/va.gov-team#25936]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee cecilia.lee@va.gov
- Please provide your name.
   > Haidong "Alex" Ji
- Please Provide your email.
   > haidong.ji@gmail.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team name: Pteracuda, Lighthouse
   > Company: Liberty ITS
   > Role: Database administrator

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8gI6nn8SfF2xAbWbvVvC8kaAV3W/jtqGc+UsoGF6Lnpr4VyBmx75uA1QecjE/11nHAFn5AhQrp3uwwZfOmIfGVZeOtE5+MZgUFrsmogqnaHGUtF7U/+oyfQ1UJn5d960Tb7UfquTiIi37nWHGhj1zgK2RFYZFFIQZ4avjzqaIpaTJXwooaKrwciHrDoZm7lVptCLTSw3jZd61BFvwnbgaoa++yXZU23MGKgB6nbLSAmiboJHJV6mBzU91lPDKpuYExvbuTxQThGChDdsf8Sw+ul8XHPHTa1a9kFVViHX0e+epJarUHJDdQN79vVK4J0X3mK+82fvsVYHtfhwOrNpBG+zTMIZv9OsfuoMjS8nsEdxFBCYDvTvKdgkMncB5r7zWgIMyfHDHdeZz2qVorH+1BQYpJaL5zv5kTvas4pVQpY07/KyIIa9QQB1Qwns2jAzxFhZDPs04zIgp5APgu39Ftmhs33lyIBv4qPoSqxDVXpFiODUenWY6/12msgVtE8s= haidong@ryzenkde
```

- Grant AWS Console access?
  > YES
 - What AWS services do you need access to and why?
 > S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house including things like CloudWatch

**Comment by jbritt1** [comment]
#### For AWS Access

User: Haidong "Alex" Ji
COR: Cecilia Lee
Approval required: @drorva

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by haidong** [comment]
Thanks @jbritt1 SOCKS access confirmed!

**Comment by drorva** [comment]
AWS access approved.

**Comment by jbritt1** [comment]
Access granted and temporary credentials passed to user at this time.
