### ISSUE TITLE
Update 10-10CG upload file page to include .jpg

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#25958]
### Add .jpg within the body

NEW: You can upload a .pdf, .jpeg, .jpg, or .png file

![Screen Shot 2021-06-11 at 12.38.47 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/0bd8bed0-3803-4641-80d0-6c2822e8d7d9)

**Comment by dat-gcio** [comment]
@Dene-human Here is the review instance [link](http://a7fb8bd3aa3dfcb012541c6da2f6bdd3.review.vetsgov-internal/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/representative-document-upload).

**Comment by dat-gcio** [comment]
Validated in staging.
