### ISSUE TITLE
CT Redesign: Search Improvements - Prioritization of testing recommendations

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#25950]
Updates to CT Search based on testing have been reviewed and prioritized

* Recommendations have been reviewed for priority & ease of implementation
* Recs have been reviewed & aligned at PI Minisync (6/17)

**Comment by JenLJ** [comment]
Link: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1621873180899/9430c6401d3caf812d21462194f9252821518e08?wid=0-1623420427816
