### ISSUE TITLE
"Edit on Github" link not appearing

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#25965]
@mchelen-gov commented on [Fri Jun 11 2021](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/635)

**Describe the bug**

The "Edit this page on GitHub" link is not appearing anymore.

**To Reproduce**

1. Go to https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started
3. Scroll down to bottom of the page
4. There is no link to edit page in Github

**Expected behavior**

There is a link to edit the page in Github

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 91.0.4472.101 

**Additional context**

The link is generated by [EditLink](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/components/EditLink.jsx) component which is called from [SidebarLayout](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/layouts/SidebarLayout.jsx#L24) which is used in [VaGovTeamTemplate](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/templates/VaGovTeamTemplate.jsx#L12).

**Comment by timwright12** [comment]
Looked into this briefly and it is because the sourceUrl is coming back undefined from the pageContent object. It looks like pageContent is just returning front matter.
