### ISSUE TITLE
Best Bet Request for COVID-19 CLP

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#25969]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [X ] NEW: You would like to create a new best bet
    - [ ] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @denisecoveyduc  and @John Hashimoto

# Section 1: New Request

### Description
*Please provide a brief description of the initiative and supporting information for the creation of a best bet.*  
The VA.gov Sitewide Content team on behalf of VHA has created a Campaign Landing Page promote Vaccine awareness and help overcome vaccine hesitancy -- http://va.gov/covid-vaccine-questions.

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > Best Bet live by June 15, 2021
 
 ### Please provide the following information:

 - [ ] Specify the **Headline** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

> TBD
  
 - [ ] Specify the **Text** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

> TBD

 - [ ] Specify the  **Keywords** that would generate the Best Bet*(@DanielleThierryUSDSVA or @bethpotts)

> Examples: covid vaccine, covid vaccine availability, vaccine availability, etc._

        > enter text

 - [X] Specify the **URL** for the Best Bet 

        > https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/
       
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: These requests are handled by the Search & Discovery  Team. Reach out via Slack #va-search with any questions.*** 

#### Acceptance Criteria
- [ ] Add this request into a Zenhub Epic
- [ ] Follow-up with requester to address any lingering questions/concerns
- [ ] For new Best Bet: Setup, test and validate the Best Bet in Production via the Search.gov dashboard (@johnhashva)
- [ ] For Best Bet Changes: Alter Best Bet via the Search.gov dashboard, test and validate (@johnhashva)

#### Definition of Done

 - [ ] Request has been implementation and live on production

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva. Let me know if this works. The meta title is 52 characters so I think it's okay. But if it's too long, we could go with **Have questions about COVID-19 vaccines?** instead. 

**Have questions before you get your COVID-19 vaccine?**
https://va.gov/covid-vaccine-questions
Get advice and personal stories from trusted VA providers. And get answers to common vaccine questions.

I believe we can surface 2 best bets per keyword. If that's correct, I think we can use the same keywords as we use for our covid-19 vaccine mini-hub. Thanks!

**Comment by johnhashva** [comment]
@denisecoveyduc and @DanielleThierryUSDSVA this best bet is live with same keywords as used for mini-hub, with one additional phrase: covid-19 vaccine questions
<img width="821" alt="Screen Shot 2021-06-15 at 9 59 18 AM" src="https://user-images.githubusercontent.com/63107147/122066081-6d885c00-cdc0-11eb-9836-5ecf144826e9.png">

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much, @johnhashva!

**Comment by denisecoveyduc** [comment]
Great! Closing this out as part of S49. Thanks!
