### ISSUE TITLE
Create a spreadsheet to prioritize design system accessibility issues

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#25967]
## Description
Review the issues [logged in the design system audit](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility), and add them to a shared spreadsheet.

Links to prioritized findings are available in our sensitive repo: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/accessibility/audits/design-system.md

## Acceptance Criteria
- [x] Finish the first draft of the spreadsheet
- [x] Share spreadsheet with Testing Tools Team
- [x] Review and approve the spreadsheet

**Comment by 1Copenut** [comment]
@JoeTice I linked the spreadsheet in the issue description. I'll leave this open until our meeting with the Design System team for the final todo item.

**Comment by pjhill** [comment]
We have met with design system and they have given approval to begin working on the list of a11y issues defined in the spreadsheet.
