### ISSUE TITLE
VRRAP: Add google analytics tracking to form

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25963]
As a developer, I need to add google analytics tracking to the new stem automated denial functionality so that we can monitor usage and make adjustments as necessary.

## Assumption:
1. This work does not require a production or feature flag.

## Acceptance Criteria:
1. When the user updates the direct deposit information by clicking "Save", the following event is fired:

```
{
 event: 'cta-button-click',
'button-type': 'primary',
'button-click-label': 'Save',
'button-background-color': '#0071BB',
}
```

2. The answer to the question "I don't want to use direct deposit", fires the following event:

```
{
event: 'int-checkbox-option-click',
'checkbox-label': 'I don’t want to use direct deposit',
}
```

3. When the user answers the question "Do you know which program you'd like to enroll in?", the following event is fired:

```
{
event: 'int-radio-button-option-click',
'radio-button-label': "Do you know which program you'd like to enroll in?",
'radio-button-optionLabel': 'Yes' or 'No',
'radio-button-required': true
}
```

4. When the user answers the question "What's the name of the school or training provider?", the following event is fired:

```
{
event: 'int-text-input-blur',
'text-input-label': "What's the name of the school or training provider?",
'text-input-value': {{{value they entered}}}
}
```

5. When the user answers the question "What's the name of the program?", the following event is fired:

```
{
event: 'int-text-input-blur',
'text-input-label': "What's the name of the program?",
'text-input-value': {{{value they entered}}}
}
```

6. When the user answers the question "Which state is the program in?", the following event is fired:
```
{
event: 'int-text-input-blur',
'text-input-label': "Which state is the program in?,
'text-input-value': {{{value they entered}}}
}
```

7. When the user expands/collapses the accordion on the review application page, the following event is fired:

```
{
event: 'int-accordion-expand' OR 'int-accordion-collapse'
'accordion-header' 'VRRAP application'
}
```

8. When the user clicks the "Edit" button on the review application page, the following event is fired:

```
{
event: 'cta-button-click',
'button-type': 'primary',
'button-click-label': 'Edit',
'button-background-color': 'transparent',
}
```

9. When the user clicks the "Update page" button after editing the review application page, the following event is fired:

```
{
event: 'cta-button-click',
'button-type': 'primary',
'button-click-label': 'Update page',
'button-background-color': '#0071BB',
}
```

## Supporting artifacts:
1. Originating issue: [#23723](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23723#issuecomment-859230578)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17618

**Comment by sonntag-adam** [comment]
in staging. Closing story.
