### ISSUE TITLE
COE - Provide a way for users to view their existing COE if they have chosen to fill out the form

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#25979]
## Description
As a user who has gone through the automatic COE check and is eligible for an automatic COE, but has opted to instead fill out the 26-1880, I would like a way to access my previously generated COE. 

## Considerations
Currently, users can click on a link called `Make changes online COE with VA Form 26-1880`. This link lives on the [COE page](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139511607/simulate/sitemap) for when users successfully pass the coe check and are eligible to download one. If a user clicks this link they are sent to the form introduction page to fill out the form. Using the browser back button allows them to re-access their COE, but we should include a more explicit way return there. For example, on the Chapter 31 form introduction page, we include a link that allows users to go back and answer the wizard questions again. 

- COE check is on `/eligibility/`
- [Intro screen](https://staging.va.gov/housing-assistance/home-loans/apply-for-coe-form-26-1880/introduction) is dynamic and has a subway map on it where we would like to add a direct link back to the `/eligibility/` page (in addition to the back button, if that was part of their current path)
- Link directly to design page: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140646596

"[Click here to view your eligibility.](https://staging.va.gov/housing-assistance/home-loans/apply-for-coe-form-26-1880/introduction)" (If it exists, else, consider hiding.)

## Tasks
- [ ] add a more explicit way to return to the COE page

## Acceptance criteria
- [ ] above task is done

**Comment by jason-gcio** [comment]
Within the subway map, provide a link back to eligibility

**Comment by micahchiang** [comment]
Given that the designs for COE have changed since the creation of this ticket and include the aforementioned link back to COE, this can be closed.
