### ISSUE TITLE
10203: Update clinical training section content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25972]
As an EDU team member, I need the update content regarding the clinical training program eligibility to the 10203 form and  SCO email so that the users are provided with clear, concise and accurate information.

## Assumptions:
1. AC1 is completed behind feature flag `edu_form10203_updates` #24615 
2. AC2 is completed behind a prod flag.
3. The form can be found here: [Staging Form](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction)
4. All "sections of the SCO email are always included in the email:
    a. If the applicant is an undergraduate
    b. If the applicant is a teaching certificate candidate
    c. If the applicant is in a clinical training program for health care professionals
    
## Acceptance Criteria:
1. The "clinical training program" section content in the SCO email below includes the following "header": **If the applicant is in a clinical training program for health care professionals**
    > If the student already has a bachelor's or graduate degree and is pursuing a clinical training program, please provide the following:
    > 
    > - Has the student earned a bachelor’s or graduate degree in an approved STEM program? 
    >    ([Programs approved for the Rogers STEM Scholarship](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf))
    > - Name of STEM program of degree conferred:
    > - Is the student currently enrolled in a covered clinical training program for health care professionals? 
    >    ([Programs approved for the Rogers STEM Scholarship](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf))
    > - Total length of clinical training program (in months or years):
    > - Amount of clinical training program completed to date (in months or years):

2. The sub-bullets under the "STEM degree" on the [How to Apply](https://staging.va.gov/education/how-to-apply/) page are:

    > - You're enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), **or**
    > - You've already earned a STEM bachelor’s degree and are working toward a teaching certification, **or**
    > - You've already earned a STEM bachelor's or graduate degree and are pursuing a covered clinical training program for health care professionals.
    >    [See eligible degree and clinical training programs](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf)

## Supporting Artifacts:
1. [Email Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f225eff42c572b9786a8fd9300cdfa4457b13cee/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-email.md)

**Comment by ksantiagoBAH** [comment]
SCO Email
Feature Flag off
![Screen Shot 2021-06-18 at 12.34.55 PM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/9538459e-2d4f-464f-b70d-d7fd156e7a75)

Feature Flag on
![Screen Shot 2021-06-18 at 12.33.28 PM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/d57ace50-2872-49ad-8ba0-b4cb54300a0d)

**Comment by ksantiagoBAH** [comment]
related defect https://github.com/department-of-veterans-affairs/va.gov-team/issues/26316

**Comment by ksantiagoBAH** [comment]
Pull request FE: https://github.com/department-of-veterans-affairs/vets-website/pull/17642
Pull Request BE: https://github.com/department-of-veterans-affairs/vets-api/pull/7268

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1958&)

**Comment by delli-gatti-michael** [comment]
testing complete
