### ISSUE TITLE
CT: Add Learn more to "Are you an in-state student?" question

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25982]
As a comparison tool user, I need to be informed of institution policies regarding in state tuition, so that I can make an informed decision about where to use my benefits.

## Assumptions:
1. This work is completed behind a prod flag.
2. The data referenced in this story was loaded into GIDS via #25818

## Acceptance Criteria
1. The current "Are you an in-state student?" question in the "School costs and calendar" section of the institution profile page has a corresponding "Learn more" link.
    a. The aria-label for the "Learn more" link is: Learn more about qualifying for in-state tuition.
2. When the "In-State Tuition Information" data is a URL, the following content is displayed in the Learn more modal with the URL being the link:

> **Qualifying for in-state tuition**
> If you're using GI Bill education benefits, you probably qualify for in-state tuition.
> 
> Visit this school's website to [see any in-state tuition requirements](url).

3. When the "In-State Tuition Information" data is "Contact the School Certifying Official (SCO) for requirements" OR there is no data for the institution, the following content is displayed in the Learn more modal:

> **Qualifying for in-state tuition**
> If you're using GI Bill education benefits, you probably qualify for in-state tuition.
> 
> Contact the School Certifying Official (SCO) to learn more about this school's in-state tuition requirements.

## Supporting Artifacts:
1. 
<img width="862" alt="Section1005_URL_Display" src="https://user-images.githubusercontent.com/48260534/121741026-ee4b0d80-cacb-11eb-8c00-a40758adbac1.png">
2. [Prototype](https://bahdigital.invisionapp.com/share/KEIAH11J9NX#/screens)

**Comment by amyknox** [comment]
Aria label for learn more:  Learn more about qualifying for in-state tuition.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17657

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1964)

**Comment by delli-gatti-michael** [comment]
Testing complete
