### ISSUE TITLE
On-site search improvements

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2598]
See this issue for background information and discovery conversations: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1328 

This epic is to track tasks for improving the search.gov public website search functionality, ux, and accuracy of results. 

"As a user, I want to search for X and find what I'm looking for."

**Comment by aeltarhoni** [comment]
Per @Karak888 we can close.
