### ISSUE TITLE
Review Instances: port appearing in search URLs

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#25983]
[Slack context](https://dsva.slack.com/archives/CBU0KDSB1/p1623432808410900)

Steps to replicate

1. [Visit a review instance](https://github.com/department-of-veterans-affairs/vets-website/deployments)
2. Search for something
3. Note that the URL contains port 3001

Monitor this for a week and see if it has been fixed by Ops (see Slack thread)

**Comment by timwright12** [comment]
Checked in on this 6/5 w/RI d6e9859217133642fb482c31d06a5ddb, search is working

**Comment by timwright12** [comment]
Check in on this 6/15 w/RI 9e7c19aa8eb735af91c56a6cfa3f93b0, search is working

**Comment by timwright12** [comment]
Checked this on 6/17 w/RI 9dc5ef00263b4eb1074f29070df08237, search is working.

Going to move this to the backlog this review instance search isn't blocking anything. We should still look at it since it's a strange behavior, but it's not breaking anymore.

**Comment by meganhkelley** [comment]
Will not fix
