### ISSUE TITLE
[FE] My VA: Ensure we are sending appropriate events to the dataLayer for analytics tracking

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25984]
## Background
In order to be able to appropriately track metrics once we launch My VA 2.0 there's some additional FE work needed to ensure we're capturing and sending events appropriately. 

## Acceptance Criteria
- [ ] Ensure that for the untracked links (as identified in the table in [Brian's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23336#issuecomment-859260656)) that we are sending the appropriate events to the dataLayer:

<table>
  <tr>
    <th>Interaction</th>
    <th>Data Layer</th>
    <th>Notes</th>
  </tr>

  <tr>
    <td>Go to your profile</td>
    <td>
      <pre lang="js">
{    
event: 'dashboard-navigation',   
'dashboard-action': 'view-link',  
'dashboard-product': 'view-your-profile',
}</pre
      >
    </td>
    <td>This exists in the current My Va, but is a view-button.</td>
  </tr>
  <tr>
    <td>Manage all your claims and appeals</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Check your claim or appeal status',        
'links-list-section-header': 'Claims &amp; appeals',
}
</pre
      >
    </td>
    <td>This is the "Manage all your claims and appeals" link, correct?</td>
  </tr>
  <tr>
    <td>Schedule your appointment</td>
    <td>
      <pre lang="js">
{                
event: 'nav-linkslist',        
'links-list-header': 'Schedule and view your appointments',        
'links-list-section-header': 'Health care',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
      Schedule and manage your appointments (the "We can’t access your
      appointment information" version)
    </td>
    <td>
      This is already tracking with nav-alert-box-link-click. Just wanted to
      note this.
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
      You have _ unread messages (text changes to "Send a secure message to your
      health care team" if there are 0 unread messages, but still links to same
      place)
    </td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'You have n unread messages',        
'links-list-section-header': 'Health care',
}
</pre
      >
    </td>
    <td>
      I would use n vs the actual number to reduce the cadinality on these
      events.
    </td>
  </tr>
  <tr>
    <td>Refill and track your prescriptions</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Refill and track your prescriptions',        
'links-list-section-header': 'Health care',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Get your lab and test results</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Get your lab and test results',        
'links-list-section-header': 'Health care',
}
</pre
      >
    </td>
  </tr>
  <tr>
    <td>Get your VA medical records</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Get your VA medical records',        
'links-list-section-header': 'Health care',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>How to file a VA disability claim</td>
    <td>
      <pre lang="js">
 {    
event: 'dashboard-navigation',    
'dashboard-action': 'view-link',    
'dashboard-product': 'recommendations-disability-file-claim',
}
</pre>
    </td>
    <td></td>
  </tr>
  <tr>
    <td>Learn how to apply for VA education benefits</td>
    <td>
      <pre lang="js">
 { 
event: 'dashboard-navigation',
'dashboard-action': 'view-link', 
'dashboard-product': 'recommendations-education-apply-now',
}
</pre>
    </td>
    <td></td>
  </tr>
  <tr>
    <td>Link to view all disability ratings (ex. "40% service connected")</td>
    <td>
      You can infer this by looking at pageview for
      "/disability/view-disability-rating/rating" with a Previous Page Path of
      "/my-va/".

But let me know if you want to throw this in a      dashboard-navigation event.
    </td>
    <td>&nbsp;</td>
  </tr>

  <tr>
    <td>
      Learn how to apply for VA health care (only shown for users who do not
      have and have never applied for health care)
    </td>
    <td>
      <pre lang="js">
{    
event: 'dashboard-navigation',    
'dashboard-action': 'view-link',    
'dashboard-product': 'recommendations-health-care-apply-now',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
      Tracking for clicking into an individual claim (should carry over from
      1.0, but double check - will look like Dashboard - Navigation - View
      Button -View Claim)
    </td>
    <td>I see this in the dataLayer still, so I think we're good.</td>
    <td></td>
  </tr>
</table>

See additional instruction/guidance from the analytics team [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23336#issuecomment-859670540).

**Comment by erikphansen** [comment]
This was pretty straightforward so I downgraded it to a 2.

**Comment by erikphansen** [comment]
Just merged this in so it'll be ready to validate on staging first thing tomorrow.

**Comment by ajakabcin** [comment]
Per [Lauren's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23336#issuecomment-863311286) I think we're good to close this ticket. Thanks Erik!
