### ISSUE TITLE
COE - Update introduction page copy

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#25981]
## Description
The COE form introduction page copy needs to be updated. This includes updates to the traditional subway lists, messaging at the top of the page, and possibly the `SaveInProgressIntro` component.

## Considerations
- [Current introduction signed in page](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137652088/simulate/sitemap)
    - This mockup suggests changes to the save in progress intro component to just use an action link. Not entirely certain of the feasibility of this. Will require investigation.
    - There's a new alert box at the top that says `We need more information...`. Presumably this is for when a user doesn't pass the COE eligibility check. We may however need some copy for when they do pass, but choose to fill out the form because they are applying for restoration of entitlement, or need to make changes/corrections.
    - This page also includes copy updates to the subway list component (add a link to the eligibility page)

## Tasks
- [ ] make all copy updates

## Acceptance Criteria
- [ ] tasks have been completed

**Comment by jason-gcio** [comment]
This needs a link to eligibility included, or ask FE to implement when they update
