### ISSUE TITLE
[Research] My VA:  Determine method for testing action items work + plan research

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#25980]
## Background
As part of long-term research and continued improvements to My VA post-launch we need to do some discovery/research prep around how to better elevate action items in the dashboard ~and create sketches for that work~.

## Acceptance Criteria
- [ ] Determine method for testing
- [ ] Plan research strategy

**Comment by ajakabcin** [comment]
Moving this to next sprint

**Comment by tressaellen** [comment]
Based on discussions around how to test, we will be building one prototype and doing moderated usability tests with Veterans. I've been putting together some things to test [in this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/action-items-plan-and-questions-tressa.md) - there likely be more added as we clean up the prototype.

Closing this ticket.
