### ISSUE TITLE
Best Bet Request | Content & Localization

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#25986]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [x] NEW: You would like to create a new best bet
    - [ ] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @denisecoveyduc  and @John Hashimoto

# Section 1: New Request

### Description

The Content and Localization team recently released 3 resource pages: one for Spanish speakers, Tagalog speakers and speakers of all other languages. These pages will provide key information such as how to request an interpreter, file a discrimination complaint and provide links to existing translated content. We will continue to add content and links to these pages.

###  Completion Dates
    
 Launched May 27, 2021
 
 ### Please provide the following information:

# Request # 1 Other Languages (English)

 - [x] Specify the **Headline** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

How to get free language assistance from VA

 - [x] Specify the **Text** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

We offer free interpreters and other language assistance to Veterans and family members. Find out how to get help in other languages by phone or at a VA health facility.

 - [x] Specify the  **Keywords** that would generate the Best Bet*(@DanielleThierryUSDSVA or @bethpotts)

interpreter, language assistance, translation

 - [x] Specify the **URL** for the Best Bet (@davidconlon )

https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/

# Request # 2 Spanish

 - [x] Specify the **Headline** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

Asistencia y recursos del VA en español

 - [x] Specify the **Text** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

Obtenga un intérprete sin costo. También obtenga información que le ayude a entender su cuidado médico, beneficios y servicios del VA.

 - [x] Specify the  **Keywords** that would generate the Best Bet*(@DanielleThierryUSDSVA or @bethpotts)

spanish, español, intérprete, language assistance, interpreter, asistencia

 - [x] Specify the **URL** for the Best Bet (@davidconlon )

https://www.va.gov/asistencia-y-recursos-en-espanol/

# Request # 3 Tagalog

 - [x] Specify the **Headline** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

VA Tagalog wika mapagkukunan at tulong

 - [x] Specify the **Text** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

Kumuha ng libreng tagapagsalin at impormasyon upang matulungan kayong maintidihan ang inyong pangangalaga sa kalusugan, mga benepisyo at mga serbisyo ng VA.

 - [x] Specify the  **Keywords** that would generate the Best Bet*(@DanielleThierryUSDSVA or @bethpotts)

tagalog, tagapagsalin

 - [x] Specify the **URL** for the Best Bet (@davidconlon )

https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong/

# Section 2: Change Request

### Description
Please provide a brief description of the initiative and supporting information for the creation of a best bet.  
> ****Example:*** "The VA is working closely with the Centers for Disease Control and Prevention (CDC) and other federal partners to provide COVID-19 vaccines to Veterans and VA health care personnel. The Find a Facility tool has just added [COVID vaccine as a search category](https://www.va.gov/find-locations?facilityType=health&serviceType=Covid19Vaccine)and we want to create a Best Bet to ensure veterans seeking looking information are aware of this new tool feature."**

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > date/time
 
 ### Please provide the following information:
 - [ ] Identify the Best Bet requiring changes

        > associated best bet
- [ ] Specify the change(s) that are required.  

        > details about required change
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: These requests are handled by the Search & Discovery  Team. Reach out via Slack #va-search with any questions.*** 

#### Acceptance Criteria
- [ ] Add this request into a Zenhub Epic
- [ ] Follow-up with requester to address any lingering questions/concerns
- [ ] For new Best Bet: Setup, test and validate the Best Bet in Production via the Search.gov dashboard (@johnhashva)
- [ ] For Best Bet Changes: Alter Best Bet via the Search.gov dashboard, test and validate (@johnhashva)

#### Definition of Done

 - [ ] Request has been implementation and live on production

**Comment by johnhashva** [comment]
@SKasimow + @denisecoveyduc these Best Bets are now live -- but you should check them using the specified keywords to make sure I did not miss anything.
<img width="566" alt="Screen Shot 2021-06-28 at 4 30 15 PM" src="https://user-images.githubusercontent.com/63107147/123703924-0a241280-d833-11eb-992d-384ecb911b90.png">
<img width="576" alt="Screen Shot 2021-06-28 at 4 29 52 PM" src="https://user-images.githubusercontent.com/63107147/123703930-0c866c80-d833-11eb-97d4-3208ad7479f0.png">
<img width="536" alt="Screen Shot 2021-06-28 at 4 28 58 PM" src="https://user-images.githubusercontent.com/63107147/123703932-0e503000-d833-11eb-889c-33e680189885.png">

**Comment by SKasimow** [comment]
@johnhashva Hi John - I just finished checking the keywords and am seeing the correct info surface. Thank you so much! Can't wait to review our numbers for this week!

cc @denisecoveyduc @DanielleThierryUSDSVA

**Comment by johnhashva** [comment]
Closing this ticket based on validation.
