### ISSUE TITLE
[Design] Draft Harassment Reporting Tool wireframe/mockup build

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25991]
## Issue Description
_ORDMI PIFs have never actually produced any design mockups for the harrassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled.  We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems.  The designs will be used for both design intent review and initial FE build of the prototype_

Here's the layout: Scope is Veterans/Beneficiaries and were only build for the top three situations: 1.Sexual Assault 2. Sexual Harassment 3. Harassment (other then Sexual) as identified here:
![Screen Shot 2021-06-23 at 10 17 21 AM](https://user-images.githubusercontent.com/70410912/123134771-5e338f00-d40e-11eb-8e08-9bc4db0f00cc.png)

Artifact is Here: 
[05_13_2021 Arch_Use Cases.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6644644/05_13_2021.Arch_Use.Cases.pdf)

Example IG Harassment Reporting Tool:[ HERE ](https://www.va.gov/oig/apps/info/hotlineGeneralContactForm.aspx?cc=s)

## Design tasks
- Ensure the page is styled according to design spec. 
- Ensure any questions are pushed to PIF partners to get clarification 
- Ensure  we follow VA.gov system system recommendations to ensure a streamlined system is achieved 
- Be prepared to share design mockups for review with team and collaboration cycle checkpoints 

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Designer posts link to designs for review by PIF/PM/PO
- [ ] Designer be prepared to share designs in support of VSP collab cycle reviews
- [ ] Designs are prepared with full mockups in support of FE build requirements

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
Currently blocked as we wait for visual screenshots.

**Comment by sshein** [comment]
I mentioned this to Cassandra but might be nice to do this design work with Sketch and Sketch for Teams instead of InVision since we're moving to that tool and losing InVision in August

**Comment by sshein** [comment]
looks like Cassandra is already planning on working in Sketch for Teams, I just was confused by the title of the ticket. Thanks all :)

**Comment by brianalloyd** [comment]
Thanks @sshein I updated the ticket to keep it system agnostic, unsure why I added that from the onset.  Looking forward to kicking this off and getting mock ups for review.  Please let me know what other questions exist.

**Comment by brianalloyd** [comment]
Draft sketch files have been reviewed.  Creating a follow on ticket for feedback and refinement for Sprint 51 design elements.  

[Sketch Review](https://www.sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

**Comment by sshein** [comment]
@callen2563 whenever is appropriate, let's meet up and I can run through your design with you and point out anything that might need tweaking based on our (sometimes unwritten) standards etc. Maybe you can grab some time on my calendar? Or you can post the designs to a ticket and I can respond in the ticket whichever makes the most sense. Looking like a good start for your first form design!
