### ISSUE TITLE
Contact Center Review for [Claims & Appeals - Notice of Disagreement]

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#25998]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

### Launch Date
June 30, 2021

### Version Number
Version 1

### Product Guide
[Notice of Disagreement Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/VSA_NOTICE_DISAGREEMENT_GUIDE_DRAFT_V2_20210512.docx)

### Product Video
[NOD Video](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/NOD-2.mp4)

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hello @vhenry07 . The draft looked great! I only made minor formatting adjustments. There are a few of points marked for your review. My review draft is attached. Once you are able to approve, I can share with the VEO Contact Center for their approval.
[VSA-NOTICE-DISAGREEMENT-GUIDE-ST-061521_.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6665312/VSA-NOTICE-DISAGREEMENT-GUIDE-ST-061521_.docx)

**Comment by vhenry07** [comment]
Hi @starlow00 these edits look great to me. Approved.

**Comment by starlow00** [comment]
Sent to VEO for review.

**Comment by vhenry07** [comment]
Updated with link to product video.

**Comment by starlow00** [comment]
Thank you, @vhenry07 . Looks great! I have shared it with VEO.
