### ISSUE TITLE
Document: making a change in formation or formation-react 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#260]
Should walk through the steps for making the change, updating versions in vfs tools and vets-website.

This is mostly covered in the vfs tools readme already, but we could clean it up and get it on the site, then link back to it from the readme.

**Comment by rianfowler** [comment]
- have the CI/CD publish tagged packages

**Comment by caw310** [comment]
We need to move this link to Formation Readme. 
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/updating-formation/

**Comment by humancompanion-usds** [comment]
That doc is fairly out of date. That entire repo is replaced by the documentation at:
https://depo-platform-documentation.scrollhelp.site/

One doc that would be good to update is this one which does not talk about web-components and should:
https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-architecture#Frontendarchitecture-Designsystem

**Comment by FranECross** [comment]
Closing due to age and inactivity. More than likely obsolete. Can reopen if needed in the future, or a new ticket created.
