### ISSUE TITLE
Change name of the app

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#26003]
## Description
There are concerns about naming the app "VA Mobile" due to overlap with the VA Mobile App program and va.mobile.gov.

## Notes
6/24: In app store "VA: Health & Benefits", on phone "VA"

- Patrick Saxton to make changes to the string within the app, but needs to be told what to call it? (like in onboarding carousels and error states)
- We will leave as is on the IAM page (Jonathan to check if its an easy change)
- Go through QA to make sure its read as "Vee-Aye" and not "vah"
- Do we want to say "this app" to stay generic? or "the VA mobile app"

Older:
- Avoid the word "mobile"
- Avoid "My VA"
- Can we call the app something different in the app store than we do on someone's phone? (see Chase app for reference)
- VA: (You) Health & Benefits
- Apple won't let us call it "VA"

**Comment by bridgethapner** [comment]
Sharing a couple of thoughts: 

- It seems like the display name on a user's home screen will need to be short -- the longest one I see on my phone is 13 characters. I'm not finding a clear character limit online, I see a forum saying it depends on the width of the characters. If we want to avoid “mobile”, “VA” seems like a good option for home screen display to keep it short. 

- I’m not too bugged by the repetition of “VA” in the icon and then “VA” as the display name. I'm seeing other apps that have the name repeated in the image and display name or have text icons (like “in” for LinkedIn’s icon then “LinkedIn” written out below). Curious to hear other’s thoughts? We could look into changing the app icon to something more graphic. The seal is too detailed for the icon, so if we didn't do a typographic "VA" we could do something icon-based that doesn't say "VA" at all...but the icon feels flagship to me now & I do like it.

- I tested navigating my home screen using VoiceOver & it doesn’t read out the icon for any apps -- iOS VO will read “VA” if a user tapped on our app.

**Comment by msmanak** [comment]
I was watching a commercial last night and it was for a banking brand... "what's in your wallet?" so the suggestion of  "VA wallet"?

**Comment by travis-newby** [comment]
The store name should be VA: Health and Benefits, and the display name (the one that appears below the app) should be VA. I'll take care of the store name, and we need a dev team member (@lexicalninja) to change the display name.

**Comment by travis-newby** [comment]
Other things that need changing related to this...

1. Screenshots
2. Other random graphics (e.g. feature graphic on the play store)
3. App Store descriptions

May be a good idea to make those items more generic so we don't have to change them again when the name changes.

**Comment by bridgethapner** [comment]
Commenting w/ some updates: 

- @melissa-lefevre updated the app stores screenshots & text to make the name generic. Thanks, Melissa! 
- I opened #26583 for in-app copy changes in the front-end to sweep for "VA Mobile" and "VA Mobile App"
- Nice to have: @jjulian is reaching out to IAM to ask if we are able to change "VA Mobile" to "the VA mobile app" on the fly or if we'd need new paperwork. Thanks, Jonathan!

**Comment by jjulian** [comment]
emailed our request to the IAM team, Subject `SR-3287 VA Mobile App "User Friendly Application Name"`

**Comment by lexicalninja** [comment]
@jjulian I haven't had a chance to check in with you on this. We have a request in already with IAM that completely removes the graphics on the log in page. Please let them know this can either be rolled into that request or to just make sure they do both at some point. 

The current request removes these images
![image](https://user-images.githubusercontent.com/7376126/123445238-522a0780-d59d-11eb-899c-7b9f3a3a22a2.png)

![image](https://user-images.githubusercontent.com/7376126/123445260-581fe880-d59d-11eb-9165-bd7916d4bf2a.png)

**Comment by jjulian** [comment]
IAM team will have this change to the login flow in SQA today:
> The change is deployed in IAM INT environment. Same change will be deployed in SQA today during deployment window starting at 10:00 a.m. EST
<img src="https://user-images.githubusercontent.com/7627/123645866-b5fa3d80-d7f4-11eb-8e54-1d0f7862389b.png" alt="new sign in screen text" width="500"/>

**Comment by jjulian** [comment]
> Our goal is to deploy the change to production Thursday evening (7/1) starting at 9:00 p.m. ET window.   It will be promoted to our preprod environment on Wed.

**Comment by digitalken** [comment]
From reading through the comments and notes, I'm interpreting this ticket to be the following:

App store / Google Play name:  "VA: Health and Benefits"
App name on device:  "VA"
IAM page name:  "the VA mobile app"

As such, I'm passing this on 7/16/2021.
