### ISSUE TITLE
[Design] Add list of common PoA documents

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26002]
## User Story

**As a** Caregiver, **I want to** know what kinds of documents are allowable for Power of Attorney, **in order to** submit relevant documents with my application.

## Expected Behavior

We will display a list of common documents that are considered proof of Power of Attorney.
We will also display a list of common documents that are NOT considered proof of PoA.

## Acceptance Criteria

- [ ] Copy written that incorporates the list of common allowed and not-allowed PoA documents.
- [ ] Design updated to incorporate new copy

**Comment by mlighdc** [comment]
Here are the list of documents we received from the Caregiver Team.

![image](https://user-images.githubusercontent.com/35788031/122131723-98e26980-ce07-11eb-98f6-fbad86856dee.png)

**Comment by Dene-human** [comment]
@mlighdc @tchrisdyer Please see updates below (highlighted). 
- This is based on the content that the CG team gave us, but I made some adjustments to the copy and capitalization.
- Two words I thought we could remove, but wanted to check (crossed out).

![POA update.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/202ee9ab-19eb-47a6-875d-e9661214ccd3)

**Comment by mlighdc** [comment]
@Dene-human do you have this in a word doc to be able to make comments? I think some of the capitalization may not be needed e.g. I don't think you need to capitalize "M" in marriage licenses or "D" in drivers' licenses, etc.  Also I think we need to reword "What type of document ...?"

**Comment by Dene-human** [comment]
@mlighdc I am planning on having Danielle review it in our weekly on Friday, but just wanted to show you my proposed layout. 
[10-10CG POA-common docs_6.22.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6697283/10-10CG.POA-common.docs_6.22.21.docx)

**Comment by mlighdc** [comment]
Sounds good @Dene-human. The layout looks good. I am a little concern with the treatment and placement for this section.
![image](https://user-images.githubusercontent.com/35788031/122997052-98068600-d379-11eb-9cb1-04636ca91493.png)

It feels like you might be able to combine it with the last bullet of the previous section.

**Comment by Dene-human** [comment]
Ah ok, I was unclear if we were replacing or just getting into more specific examples. So maybe something more like this?

![Screen Shot 2021-06-22 at 5.57.16 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d0d181d1-4bbd-4a3c-806e-d164e86a80e1)

**Comment by mlighdc** [comment]
Layout of wise looks good. Lot more cleaner. Thanks.

**Comment by Dene-human** [comment]
Submitted for content review #25350

**Comment by Dene-human** [comment]
![POA-NEW.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/00289aa7-7ec6-4dcd-8f5a-9420955edd05)

@mlighdc Should I have Dat start implementing this?

**Comment by Dene-human** [comment]
**Designs updated**
[Prototype](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666490/simulate/sitemap?mode=i) (more info component) 
[Prototype](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666491/simulate/sitemap?mode=i) (upload legal document page text) 


**Content**
Approved in Ticket #25350
[Source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/10-10CG-application-copy.md) updated

Development ticket prepared #26329

**Comment by Dene-human** [comment]
@mlighdc These are ready for the program team. Thanks!

![Screen Shot 2021-06-29 at 4.11.40 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/4190e2f3-1c9b-480b-a103-a386f00cc90a)![Screen Shot 2021-06-29 at 4.12.08 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d0ec22df-e21f-4071-9411-93dfd182a4dd)

**Comment by mlighdc** [comment]
@Dene-human where can I find a PDF of the updates? I went to the UXPin but was not able to find how to get a PDF version. Thanks.

**Comment by mlighdc** [comment]
@DanielleThierryUSDSVA and @Dene-human 

Just wondering if we need to be more clear with the sentence highlighted in yellow. The VA does accept the listed documents but not as proof or support of their legal representation status. I am a little worry how folks may interpret if they skim through the previous paragraphs.
![image](https://user-images.githubusercontent.com/35788031/123897997-746fac80-d932-11eb-8bcb-470657aea9d4.png)

**Comment by DanielleThierryUSDSVA** [comment]
Great question, @mlighdc. I'm not sure if this would be confusing or not, especially it's specifically in the additional info about documents for this reason. But I don't think it hurts to be explicit. How about this?

We don't accept these documents as a way to show legal representation:

**Comment by mlighdc** [comment]
I think that is perfect! Thank you @DanielleThierryUSDSVA.
