### ISSUE TITLE
R&S Updates: How to change direct deposit information for VA benefits

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26012]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-benefits/):  

- Under related information, add [Direct deposit for your VA benefit payments](https://www.va.gov/resources/direct-deposit-for-your-va-benefit-payments/) 

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Please review and approve or edit the recommendations above so I can make the changes in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
1/ Thank you for adding this related link. Looks good.
2/ Please use this same ticket for one more task. On Direct deposit for your VA benefit payments, change the second CTA to follow our standard of telling the user where they're going if the link takes them off the site (this one isn't as straightforward as some, but I think "through VBBP" is better than what we have there now): **Set up a bank account through VBBP**

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Is there anything we're waiting on with this ticket?

**Comment by lwalsh617** [comment]
@RLHecht - Per Beth's comment ^^ and the revision described at the top of this ticket,  I made changes to the following two pages. They're ready for you to review and publish:
http://preview-prod.vfs.va.gov/preview?nodeId=8434
http://preview-prod.vfs.va.gov/preview?nodeId=8423
Thank you!

**Comment by RLHecht** [comment]
Both of these are reviewed and published.
