### ISSUE TITLE
508-defect-2: Feedback button hides content on mobile width viewports

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#26019]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Details

Users who make use of the browser's zoom functions on a smaller browser width will experience having parts of the page blocked by the floating feedback button in combination with other floating and sticky elements on the page.

<img width="618" alt="Screen Shot 2021-06-14 at 2 23 21 PM" src="https://user-images.githubusercontent.com/14154792/121940704-614ac300-cd1c-11eb-842a-29681703be9b.png">

## Steps to Recreate

1. Enter `https://www.va.gov/health-care/refill-track-prescriptions/` in browser
2. Reduce screen width
3. Zoom to 400% and scroll down the page

## Proposed Solution 

Don't make the feedback button sticky. Place it in a consistent location at the end of the main content similar to gov.uk.

**Comment by aubreyarcangel** [comment]
No longer a problem with the new feedback button below the main content on every page:
<img width="1440" alt="Screen Shot 2022-03-14 at 11 37 07 AM" src="https://user-images.githubusercontent.com/11021491/158207977-03976e77-891d-47fa-8373-47d87d5f7488.png">
