### ISSUE TITLE
508-defect-2 [COGNITION]: Feedback button style is unadjustable and difficult to read

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#26018]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Angela and Josh

## User Story or Problem Statement

As a user with reading disabilities, I expect text to not be rotated at a 90 degree angle so I can read what it says.
As a user who uses custom stylesheets, I expect text styles to be adjustable on the page and not overidden by `!important`.

## Details

The feedback button's current design is difficult to read for the following reasons:
- Some people with reading or cognitive disabilities will struggle to read rotated text, rendering this inaccessible to them
- Due to the use of `!important`, users won't be able to override the button's styles with stylesheets more comfortable to them
- Because this button's text is an _image_, it will become more blurred when magnified and more difficult to read on high contrast modes

<img width="1291" alt="Screen Shot 2021-06-14 at 2 11 27 PM" src="https://user-images.githubusercontent.com/14154792/121939846-7410c800-cd1b-11eb-8999-c404152aebba.png">

## Steps to Recreate

1. Enter `https://www.va.gov/health-care/refill-track-prescriptions/` in browser
2. Zoom to 400% and confirm it's blurry
3. Run an axe scan and confirm an error is thrown due to the use of `!important` for `line-height`

## Proposed Solution 

- Don't use `!important` unless absolutely necessary.
- Don't rotate the button
- Use actual text, (not an image) for the button's content
- Use an SVG for the speech bubble, with appropriate `aria-hidden="true" and `role="presentation"` to hide it from screen readers

**Comment by aubreyarcangel** [comment]
This is no longer an issue with the new feedback button:
<img width="1440" alt="Screen Shot 2022-03-14 at 11 37 07 AM" src="https://user-images.githubusercontent.com/11021491/158207289-6624087b-7e63-4147-8f3f-4db0da03fc06.png">
