### ISSUE TITLE
CT Redesign: Location Search - No Results Content Update

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#26010]
Done: Content in "No Results" screen is updated to a generic message that can be used whether a user is zoomed too close or too far to have actionable results.  

Content to be used is: 

We didn't find any institutions based on your search.

**For better results:**
**Zoom in or out** to view a different area of the map, **or**
**Move the map** to a different area

Then click the **“Search this area of map”** button.

If we still haven't found any facilities near you, please **enter a different search term** (street, city, state, or postal code).

**Comment by watersemma** [comment]
Search by location - no results. Updated copy to be more generic based on todays mini sync discussion. Prototype can be seen [here](https://bahdigital.invisionapp.com/share/PUIAH2F953K).
