### ISSUE TITLE
Describe "Search Start Page"  with modified screenshots

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26011]
##  Description
As a result of our Depo discussion about the Surfacing Search tools for #22500 we would like to describe the "Search Start Page" 

## Tasks
- [x] Modify screenshots fo va.gov search experience to describe the envisioned search start page. 

## Acceptance Criteria
- [x] a representation artifact that can be used to further discussions

**Comment by denisecoveyduc** [comment]
@mgleo Could you add the mockups or a link to them you created to this ticket?

**Comment by mgleo** [comment]
![search-landing-homepage.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/9ef7ce21-799a-45b1-b40d-8f6df4de43ea)![search-landing-subpage.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/b7714f8e-13e3-4e0a-b6ed-a53b8fd10bb0)
