### ISSUE TITLE
Endpoint: Get/ Retrieve Appointment Data (LoROTA)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#26029]
#### Acceptance Criteria

1. When I call the LoROTA "Get/ Retrieve Appointment Data" endpoint with the correct permission state and a payload I should receive patient data and status code 200. 
2. If I call the LoROTA "Get/ Retrieve Appointment Data" endpoint without the correct permission state I receive an error message

**Comment by calquisola** [comment]
#1.  retrieve data lambda/function code is in Github, dev branch
