### ISSUE TITLE
508-defect-1 [MOBILE SCREENREADER]: Feedback button can accidentally be activated when browsing on a mobile screen reader

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#26021]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a mobile screen reader user, I don't want to be suddenly interrupted mid-experience by the feedback modal. This issue also affects me when I zoom my desktop browser to 200% or more (assuming 1280px monitor resolution).

## Details

During a pilot test for facilities, we noticed two issues related to accidental activation of the floating/sticky feedback button:
- While swiping through a page, a finger can accidentally track onto the feedback button and activate it due to its relatively large size and center positioning on the screen
- It can overlay on top of other interactive elements and be accidentally activated 

### MOBILE
![image](https://user-images.githubusercontent.com/14154792/121945714-13d15480-cd22-11eb-9a2f-f1af3fb7c296.png)

---
### 200% at 1280px
![Screen Shot 2021-06-24 at 6 57 06 AM](https://user-images.githubusercontent.com/934879/123259187-d0ad7900-d4b9-11eb-8511-f4d35d0e4e6e.png)

---
### 250% at 1280px
![Screen Shot 2021-06-24 at 6 57 36 AM](https://user-images.githubusercontent.com/934879/123259231-db680e00-d4b9-11eb-9641-be4cb0f87ca0.png)

## Proposed Solution

Don't make the feedback button be sticky and float on top of other elements on the page. Place it in a consistent location at the end of the main content similar to gov.uk.

**Comment by pjhill** [comment]
Medallia can do a customized solution similar to what [sacksoff5th.com](https://www.saksoff5th.com/) offers in the footer.
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/8b410e6b-0091-4328-b20f-df1bb9a64db7)

**Comment by joshkimux** [comment]
@pjhill That would resolve this ticket 👍 
There's still other a11y issues related to housing it in the footer that can be addressed elsewhere.

**Comment by aubreyarcangel** [comment]
This is longer a problem with the new feedback button below the main content on every page:

<img width="514" alt="Screen Shot 2022-03-14 at 12 23 44 PM" src="https://user-images.githubusercontent.com/11021491/158216435-735ee0f7-78f5-410a-95b9-ce41e4c5c73b.png">
<img width="514" alt="Screen Shot 2022-03-14 at 12 23 32 PM" src="https://user-images.githubusercontent.com/11021491/158216436-f4ba75b6-892b-40b1-b75c-4b4db8f22478.png">
