### ISSUE TITLE
Endpoint: Store Appointment Data (LoROTA)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#26028]
#### Acceptance Criteria

1. When I call the LoROTA "Store Appointment Data" endpoint with the correct permission state and a payload I should receive a UUID and status code 201. 
2. If I call the LoROTA "Store Appointment Data" endpoint without the correct permission state with a payload I receive an error message

**Comment by calquisola** [comment]
#1. store data lambda/function code is in Github, dev branch

#2. Do we need to implement an API KEY pre MVP?

**Comment by kjduensing** [comment]
We'll create a ticket for API gateway API keys
