### ISSUE TITLE
508-defect-2 [FOCUS]: Feedback button interactions do not manage focus

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#26024]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Trevor

## User Story or Problem Statement

As a keyboard and screen reader user, I expect focus to be managed when I activate and close the feedback button modal.

## Details

Focus isn't managed when the user closes the modal (for both "Close" and "x"). After the user closes the modal, focus should return to the feedback button. It shouldn't be lost.

This issue compounds with other issues in this epic. Should a mobile screen reader user accidentally activate this modal and then close it, their focus will be lost on the page which can make them even more disorientated.

https://user-images.githubusercontent.com/14154792/121947593-31072280-cd24-11eb-8f18-4c43eed2465d.mov

## Acceptance Criteria

- [ ] Upon closing the feedback modal, focus returns to the feedback button

**Comment by aubreyarcangel** [comment]
The problem statement was written for the old feedback button. With the new feedback at the bottom of the main content on the page, once a user closes the form, the focus is set back to the button.
![focus](https://user-images.githubusercontent.com/11021491/158217135-b21dfc31-991c-4f62-94bb-8faa8248fbb3.gif)
