### ISSUE TITLE
Endpoint: Delete Appointment Data

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#26030]
#### Acceptance Criteria

1. When I call the LoROTA "Delete Appointment Data" endpoint with the correct permission state and a payload I should receive a UUID and status code 201. 
2. If I call the LoROTA "Delete Appointment Data" endpoint without the correct permission state with a payload I receive an error message

**Comment by calquisola** [comment]
#1. delete lambda/function  is in github
