### ISSUE TITLE
R&S Updates: What if I can't sign in to VA.gov because my password doesn't work

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26045]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/what-if-i-cant-sign-in-to-vagov-because-my-password-doesnt-work/).

Edit reset password text links as follows:
**Reset your password on the My HealtheVet website
Reset your password on the DS Logon website
Reset your password on the ID.me website**

### Tasks

- [x] DEPO to approve changes as described above, or edit (Beth)

- [x] SC to make changes in Drupal (Laura)

- [x] SC to QA and publish (Randi)

### Acceptance Criteria

- [x] Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 For text links where there's more space than we have for buttons, it's probably clearer to use this formula: "on the XYZ website"--so let's do that here:
Reset your password on the My HealtheVet website
Reset your password on the DS Logon website
Reset your password on the ID.me website

**Comment by lwalsh617** [comment]
@RLHecht - This page is ready for you to review and publish. Thank you! 
http://preview-prod.vfs.va.gov/preview?nodeId=8214

**Comment by RLHecht** [comment]
These changes have been published. Moving to validate and will close after live on the site.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
