### ISSUE TITLE
R&S Updates: Can I plan ahead for my burial in a VA national cemetery?

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26049]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/can-i-plan-ahead-for-my-burial-in-a-va-national-cemetery/).

Under related info, add:

Learn about military funeral honors 
https://www.va.gov/burials-memorials/what-to-expect-at-military-funeral/

Learn about memorial items
https://www.va.gov/burials-memorials/memorial-items/

### Tasks

- [x] DEPO to approve changes as described above, or edit (Beth)

- [x] SC to make changes in Drupal (Laura)

- [x] SC to QA and publish (Randi)

### Acceptance Criteria

- [x] Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 We have a military funeral honors page--let's link to ours instead of this legacy one. https://www.va.gov/burials-memorials/what-to-expect-at-military-funeral/

Would you also reach out to Mikki and find out if this legacy page should be redirected to ours? I'm not sure why it isn't already. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- FYI, I just messaged Mikki about the redirect. Corrected the link at the top of this ticket and will make edits in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
Thank you!

**Comment by lwalsh617** [comment]
Putting Mikki's Slack response here for tracking purposes. Per Slack conversations, we're keeping the legacy page, but are going ahead and linking to our modernized page instead of the legacy one. I swapped in the correct link at the top of this ticket. 
![image](https://user-images.githubusercontent.com/53535663/123145607-048d8d80-d42b-11eb-8ddf-aaead2ce8074.png)

**Comment by lwalsh617** [comment]
@RLHecht -- This page is ready for you to review and publish: http://preview-prod.vfs.va.gov/preview?nodeId=16585
Thank you!

**Comment by RLHecht** [comment]
Thanks @lwalsh617 ! I reviewed and published this page. Moving to validate and will close after the next deploy.

**Comment by RLHecht** [comment]
Changes live. Closing ticket
