### ISSUE TITLE
R&S Updates:  What if I don't have a bank account and want to use direct deposit

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26046]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/what-if-i-dont-have-a-bank-account-but-i-want-to-use-direct-deposit/).

Add the missing **related information** section:

Direct deposit for your VA benefit payments   
https://www.va.gov/resources/direct-deposit-for-your-va-benefit-payments/

How to change direct deposit information for VA benefits  
https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-benefits/

Under "**VA benefits**"

Change health care to disability and add pension

Link this existing line of text:  
"...a list of Veteran-friendly banks and credit unions..." to. 
https://veteransbenefitsbanking.org/banks/

### Tasks

- [x] DEPO to approve changes as described above, or edit (Beth)

- [x] SC to make changes in Drupal (Laura)

- [x] SC to QA and publish (Randi)

### Acceptance Criteria

- [x] Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 All these changes look good. Thank you!

**Comment by lwalsh617** [comment]
@RLHecht - This page is ready for you to edit and/or publish. Thank you! 
http://preview-prod.vfs.va.gov/preview?nodeId=8419

**Comment by RLHecht** [comment]
This page is published. Moving to validate and will close after live on the site.

**Comment by RLHecht** [comment]
live on site. closing ticket.
