### ISSUE TITLE
DISCOVERY | "Other languages" page iteration

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#26048]
## User story

As a Veteran or family member with limited English proficiency, I need instructions for how to get language assistance in my first language.

## Issue description

Iterate on our Language assistance and resources pages to make "Other pages" a page with language assistance information in the top 10 languages for Veterans and family members with limited English proficiency. We can further iterate on this page by adding information about how to resolve concerns at VAMCs and your civil rights/how to file a discrimination complaint in each language.

## More info 

- We'll need to set the language code by using a component such as anchor links (in the "on this page" component) and/or accordions.
- Example of page with content in multiple languages: https://www.pbgc.gov/about/policies/pg/pbgc-assistance-in-other-languages

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow Not sure if you want to add this to our existing Language assistance and resources pages epic or start a new epic for LARP iterations?

**Comment by SKasimow** [comment]
Hello @DanielleThierryUSDSVA - thinking we could add to existing epic but need to look into.
In the meantime, I'll grab the top 10 languages by both users and page views and send over.

@youngfreezyVA If we provide you top 10, can you start working on having this page support these? Or let us know if you need something else to work on this ticket.

Thanks,

Sharon

**Comment by youngfreezyVA** [comment]
yes I can, assuming that we're going off of this link as our mockups:

https://www.pbgc.gov/about/policies/pg/pbgc-assistance-in-other-languages

only thing I need to clarify is that in order for this to work within the existing architecture, the section of jump links at the top will need to be a React component (and not created via cms/drupal).  This section is what I'm referring to:

<img width="1261" alt="Screen Shot 2021-06-17 at 9 29 30 AM" src="https://user-images.githubusercontent.com/46791771/122437558-ac4c1c80-cf4e-11eb-9af0-3ebacea9076c.png">

**Comment by youngfreezyVA** [comment]
Actually, I take that back.

this is how the jump linking is working:

<a href="#arabic">العربية (Arabic)</a>

<h2 id="arabic"><span dir="RTL" lang="ar" xml:lang="ar">العربية<a id="arabic" name="arabic"></a></span> (Arabic)</h2>

so this can actually be done entirely in the cms, if you just give the link an href of the language code (or language), and the h2 and id of the language code (or language)... and then i just need to check all elements on the dom, if any of them have an id of a language or language code, i would set that elements language code to that id or associated language code

**Comment by youngfreezyVA** [comment]
@DanielleThierryUSDSVA any ideas as to which templates we will be / are using for this page? 

This is the first case of a page with sections of non-link content that need to know its lang code, so i don't think the existing solution will work for setting the lang code.

I think if we can give each link in the jump link section an `href` of "lang:en" or "lang:tl" (say for 10 links)
I can then loop through the 10 associated sections in order of the links, give them the same id as the associated links `href`, and also set the lang attribute on each section in the process.

**Comment by youngfreezyVA** [comment]
in terms of the content model on the CMS side, I think this would be a good approach. could model it off of the breadcrumbs:

jumplinks -> object
  links-> array of objects w link metadata
  sections -> jumplinked (to) sections

![Screen Shot 2021-06-23 at 6.28.34 AM.png](https://images.zenhubusercontent.com/5ce2db4f5fc50627da65259a/f178c90a-680d-462a-b27c-55b4ce417caf)

**Comment by SKasimow** [comment]
@youngfreezyVA @Yuffster-usds @DanielleThierryUSDSVA Hi Fareez - thanks for coming up with a new approach! Let's review on SU today :)

**Comment by youngfreezyVA** [comment]
useful context for breadcrumbs structure in the CMS: https://dsva.slack.com/archives/CDHBKAL9W/p1624646580228600?thread_ts=1624295708.189700&cid=CDHBKAL9W

**Comment by SKasimow** [comment]
@youngfreezyVA Can we close this one out?

**Comment by youngfreezyVA** [comment]
So the discovery suggestion on my end is to model the jump link section after breadcrumbs (not the front end derived breadcrumbs) model in the CMS.

More context here: 
https://dsva.slack.com/archives/CDHBKAL9W/p1624502379214500?thread_ts=1624295708.189700&cid=CDHBKAL9W

**Comment by SKasimow** [comment]
@adamwhitlock1 Hi - can you review this ticket as Fareez was able to complete the discovery work and find an approach but as a next step would be great if we can test in sandbox (I'll open a new ticket for that after we discuss). Thanks, Sharon
