### ISSUE TITLE
R&S Updates: Signing in to VA.gov

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26043]
As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/signing-in-to-vagov/).

- Text links related to resetting passwords at other websites will be labeled as follows (update  per ticket 26045, which uses the same links):
**Reset your password on My HealtheVet
Reset your password on DS Logon
Reset your password on ID.me**

### Tasks

- [x] DEPO to approve changes as described above, or edit (Beth)

- [x] SC to make changes in Drupal (Laura)

- [x] SC to QA and publish (Randi)

### Acceptance Criteria

- [x] Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Go ahead and move forward with these changes. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Per your feedback on ticket 26045, I'm going to add "on the XYZ website" to the links above. LMK if you disagree. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Yes! Thanks for updating these links with "on the XYZ website"

**Comment by lwalsh617** [comment]
@RLHecht - this page is ready for you to review. All edits are at the top of this ticket. 
http://preview-prod.vfs.va.gov/preview?nodeId=8222
Thank you!

**Comment by RLHecht** [comment]
This work was already completed in the other ticket. If you make a change to a single Q&A the change shows on any article you've added the question to. Closing ticket!
