### ISSUE TITLE
R&S Updates: How to get a Premium DS Logon account online

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26042]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to the [live page](https://www.va.gov/resources/how-to-get-a-premium-ds-logon-account-online/). 

-CTA button:  Replace **Sign into VA.gov**  with 
**Check your DEERS enrollment on DS Logon**
and link it here: 
https://myaccess.dmdc.osd.mil/identitymanagement/authenticate.do?execution=e6s1

### Tasks
- [x] DEPO to approve changes as described above, or edit (Beth)
- [x]  SC to make changes in Drupal (Laura)
- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Haven't we been using "on" rather than "at"?

**Comment by lwalsh617** [comment]
Yes, you're correct! I will adjust it. Thanks.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - This page is ready for you to edit and/or publish. Here's the Drupal link:  http://preview-prod.vfs.va.gov/preview?nodeId=8503
Thank you!

**Comment by RLHecht** [comment]
Thanks @lwalsh617 I reviewed and published. Moving to validate and will close when on live site.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
