### ISSUE TITLE
CT Redesign: Can't select checkbox on location results

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#26058]
Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location
2. Can only select compare, **need to be able to select compare and the checkbox**
##
https://user-images.githubusercontent.com/48804582/122069278-1041da00-cdc3-11eb-9aaf-f5cc9c978532.mov

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17606

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
