### ISSUE TITLE
CT Redesign: Add VETTEC program length to compare page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26051]
As a Comparison Tool user, I need to be able to VET TEC program length for institutions that I am interested in using my benefits at so I can make an informed decision about which institution to attend.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This will leverage the service #25219.

## Acceptance Criteria:
1. A "Length of VET TEC programs" data row is displayed in the "Academics" section of the compare page.
2. If an institution is not a VET TEC institution _**or**_ it is a VET TEC institution with no program data available "N/A" is displayed.
3. If all the program lengths are the same for a given institution "HHH hours" is displayed.
4. If there are a variety of program lengths for a given institution, the range from shortest to longest is displayed.  (ex. HHH - HHH hours)

## Supporting Artifacts:
1. [Prototype - Compare three schools](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060322_CT_Redesign_PI10_Desktop_ComparePg)

2. Length of VETTEC programs section:
<img width="802" alt="Screen Shot 2021-06-15 at 9 14 29 AM" src="https://user-images.githubusercontent.com/48260534/122058935-24cda480-cdba-11eb-9b3d-bcd363111d72.png">

**Comment by ksantiagoBAH** [comment]
FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17663
BE PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/836

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1966)

**Comment by delli-gatti-michael** [comment]
Testing complete
