### ISSUE TITLE
IA Request for eBenefits - Dependency Verification

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26059]
## What this is:
Work with Platform Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kickoff ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/dependency-verification/README.md)
- Link to [prototype or mockups](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/dependency-verification/research-design)
- Link to[ user/page flows](https://xd.adobe.com/view/95773c75-de5a-4e55-8c35-34a91425155d-c024/)
- Link to or attach your content source of truth, including H1s (if separate from prototype/mockup)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
Currently this modal window lives on the View Dependents page

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
Same as View Dependents, already in place

**URL(s)** - What are your suggested URLs and why?
va.gov/view-change-dependents/view

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  
va.gov/view-change-dependents/view

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
Most likely, this will expand but for now we only have it on View Dependents

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?
Doubtful

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] Platform: Completes final IA feedback/recommendation
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
@jason-gcio @sporeboy  In regards to the verification modal only,  I have a question I need help with...

What triggers this modal to display?  Will it just automatically appear on this page, or do they receive an email to this page that triggers the display?  I want to confirm that it is intended that there is no CTA on the view dependents page for a user to "Verify dependents".

**Comment by jason-gcio** [comment]
The modal procs when an authenticated Veteran arrives on the View Dependents page and their Diary Entry shows that it is older than 1 year.  We anticipate the modal being used elsewhere on VA.gov and depending on where it goes, we may want to build in an inline question on View Dependents about the verification.

As of right now, there is no CTA to cause this modal pop up.

**Comment by mnorthuis** [comment]
Thank you for confirming.  Given this is a modal that sits over one page with no entry points at this time, there's no additional IA work needed for it.   I will close this issue.  Thanks!
