### ISSUE TITLE
Access for [Kevin Musiorski]

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#26069]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Kevin Musiorski
- Please Provide your email.
   > kevin.musiorski@gcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > eBenefits Migration Team, Full Stack Developer, GovernmentCIO

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqZ5vM8tYGUFRCOi8y1eEyRogU9NpE6d4pGmEDZ1B3AWY3s/kLzBNN+a1u81UtRVlIlIe7e+iHLf7PScmhey8ULv5gfCbT/STo3JZG0OUfZ90I67iYgh/o2F4m/mG1LXgBMNVBz44E+/D6MwRc8wmqZrZKnS6SRLhO4CMvD/2xlFQJgY9+x7BNsnuCHgpdJSlezhOS91JYBrFJMgDY6pvv60l1IvBDZu5rXiqWi1XxRB+bfAMvS+KKaah5GnewrMaZdE4ti3PPo5jqDE83UccZMz8tLsSyWSQZOyJXb4wGtMQ80CnB7JABj8mlGcevIQ4KLWbiDfjg70IASm7N4RPWprje/r/bp4ZZzECyI0mrKbFRwujc/plR7+tfpFIk2kyismDJLtAo/53TqjFjrUhQILcErmNnQdyMw5mmlhVFTgb+9jG5LBb8PEfv7csLg6qq7la3/DAiLTUkTVya4QSn+clcmiOwwC41/r1vVhf+qXIyWK8H1h9dEXB0ueM1nnIQX1eW7RcZO226143Es70hmRRwYnbGOns7VlAwm+s1dEiK3Flg5Fdaa1FCHuCMvHf5qViYPSfNMoI8PJrbj9584Bf0egKaoWxHGk4g1R/f1PZ4fBuFMX/A8Iuj0DF9kjkFCYjOtdgS6d5DF0Bu4BdNuhKPSn4dacs5kkCm0lIfQQ== kmusiorski@governmentcio.com

```

- Grant AWS Console access?
  > **YES** / NO
  - What AWS services do you need access to and why?

**Comment by RudyOnRails** [comment]
EDIT: I asked my teammates and I **do** need access to Cloudwatch (for logs) and EC2 for ssh'ing into some dev/staging servers.

Thanks,
Kevin

**Comment by RudyOnRails** [comment]
Good morning,

Does this process include me getting SOCKS access?

**Comment by mydesignrocks** [comment]
Hello there, apologies for getting to this late... I am looking at the ssh key and doesnt look right. Can you please follow these steps...
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - please review for AWS access. thanks!

**Comment by RudyOnRails** [comment]
> Hello there, apologies for getting to this late... I am looking at the ssh key and doesnt look right. Can you please follow these steps...
> https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

@mydesignrocks Ah, sorry about the confusion! I assumed newer ed25519 type could be used. However, I have been on a project before where the servers were not up to date so the stronger ed25519 key was not compatible. I will generate a legacy RSA key and update it above.

**Comment by RudyOnRails** [comment]
@mydesignrocks new ssh key is updated above in the description. thanks for your help.

**Comment by mydesignrocks** [comment]
Hi @RudyOnRails - can you please check your socks access now.

**Comment by mydesignrocks** [comment]
I just realized that I havent dropped the document for socks configure:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

**Comment by RudyOnRails** [comment]
Sorry for the delay Srikanth, we are troubleshooting a local env SSO issue. I've had that page open and ready to attack. Will do it now and let you know.

**Comment by RudyOnRails** [comment]
@mydesignrocks after starting the proxy with `ssh socks -D 2001 -N` and running `$ curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov` it doesn't give me the desired `HTTP/1.1 302 FOUND`. It gives me this output:

```shell
% curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov
*   Trying 127.0.0.1...
* TCP_NODELAY set
* SOCKS5 communication to sentry.vfs.va.gov:80
* SOCKS5 read timeout
* Closing connection 0
curl: (28) SOCKS5 read timeout
```

My proxy seems to be running as well:
```
% nc -z 127.0.0.1 2001
Connection to 127.0.0.1 port 2001 [tcp/dc] succeeded!
```

**Comment by mydesignrocks** [comment]
thanks for the update! As and when we have an approval from the depot on your AWS access, I will be able to add you in to it. Will keep this access request open until then @RudyOnRails

**Comment by RudyOnRails** [comment]
Thanks @mydesignrocks

**Comment by RudyOnRails** [comment]
Thanks for the movement on the `AWS Console Access`. Looking forward to getting this checked off and using it!

**Comment by RudyOnRails** [comment]
Any update on AWS access? I am in need of it today.

Thanks,
Kevin

**Comment by drorva** [comment]
Sorry for the delay. Request sent to Kimberly.West2@va.gov, your GTL. Once replied, I'll approve.

**Comment by RudyOnRails** [comment]
> Sorry for the delay. Request sent to [Kimberly.West2@va.gov](mailto:Kimberly.West2@va.gov), your GTL. Once replied, I'll approve.

No worries and thanks for moving it along.

**Comment by RudyOnRails** [comment]
I would like to look at vets-api logs in production to help me solve a tricky problem I've been tasked with. I think I need AWS access so I can look in CloudWatch.

Is my access delayed because my background check hasn't been completed yet and/or I don't have my PIV card?

**Comment by RudyOnRails** [comment]
> I would like to look at vets-api logs in production to help me solve a tricky problem I've been tasked with. I think I need AWS access so I can look in CloudWatch.
> 
> Is my access delayed because my background check hasn't been completed yet and/or I don't have my PIV card?

Sorry for the ping - I checked with Kimberly and Platform Support, and yes we are waiting for background check and VA account first. Makes sense.

Thanks,
Kevin

**Comment by RudyOnRails** [comment]
My PIV sponsorship was approved and I am planning to get my PIV card as soon as my stomach flu clears up.

I am continuing to work on a problem that requires AWS Cloudwatch log access for troubleshooting. Is there a chance I could have AWS access soon so I may investigate the issue on my own and help resolve the problem for all involved?

Thank you,
Kevin

**Comment by mchelen-gov** [comment]
Hi @RudyOnRails, who is your vendor onboarding representative? This is the person from your company or the primary contractor who helped you onboard at VA.

**Comment by RudyOnRails** [comment]
I'm not 100% sure, but I think it's either Kimberly.West2@va.gov with GCIO (she's helped me the most), or:
> Please provide your Contracting Officer's Representative (COR) name.
Mary O'Toole

**Comment by RudyOnRails** [comment]
Good morning,

My teammate Kathleen will be on vacation next week, and I will be the only backend dev on our team. Is there a chance that I could get access to AWS in preparation for Kathleen being out next week?

Thank you,
Kevin

cc: @kathleencrawford @jason-gcio

**Comment by RudyOnRails** [comment]
Is there anyone that can help me with this?

**Comment by RudyOnRails** [comment]
@mchelen Do you need any more info? I have my PIV, and am on the VA network via CAG.

**Comment by mchelen-gov** [comment]
Ok I have sent a reminder email to Kimberly West asking for EQIP transmittal date, once we have that then the request can be approved.

**Comment by mchelen-gov** [comment]
Request approved 👍

**Comment by mleclerc00** [comment]
Account details passed on to Kevin
