### ISSUE TITLE
CT Redesign: 2nd Comparison selection, everything on the page "collapses" and is no longer visible

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#26061]
Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location
2. Select compare for one school, scroll to another and select compare.
3. Observe

https://user-images.githubusercontent.com/48804582/122071444-bb9f5e80-cdc4-11eb-9193-e82c12662d8c.mov

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17606

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
