### ISSUE TITLE
Update Disability 'how to file' page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2608]
Per Paul Shute (Disability stakeholder) and the AMO team (Lynny Thiem, Fred Somers) - general content updates related to:
- UX improvements/fixes
- Correcting inaccurate seeming information (because of the way the widget, when expanded, appears to flow into the body copy right below the REACT widget)

This page needs text updates in the REACT widget and in body copy: 
https://www.va.gov/disability/how-to-file-claim/
In Drupal: http://preview-prod.vfs.va.gov/preview?nodeId=905

See attached screenshot.
- Inside widget. Change H2 to: Can I file my claim online?
- Inside widget. Change instruction text to: It depends on your situation. Answer a few questions, and we'll guide you to the right place.
- Inside widget. Change button text to: Let's get started
- Outside widget, on body copy. Change the H3 "You can also file..." to H2 "What other ways can I file my disability claim?" And add extra spacing, so the expanded/user filled out REACT component doesn't flow right into body copy.

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/9a11719d-d0b9-48f5-b09c-e27f50da0562)

@Karak888 -This needs someone to update the REACT widget text. I've already updated the body copy (on Drupal page copy). Once the REACT widget text is made and can be previewed together with the Drupal draft updates, this can go to @peggygannon to review and publish. 

[x] Update body copy in Drupal.  (JL: done)
[ ] Update text in REACT widget.  
[ ] Review and validate both sets of changes together and publish. 

This change is part of a larger set of content changes from Lynn's AMO team (documented in [ticket 2608](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2608), but pulling this page out separately because of the REACT part of the change, in case that needs FE engineer or another team to work on it.

**Comment by Karak888** [comment]
@RLHecht this REACT component needs to be handled by FE engineer correct?

**Comment by kelsonic** [comment]
@Karak888 @RLHecht I'm happy to pick this up if needed/wanted! :)

**Comment by peggygannon** [comment]
@jenniferlee-dsva @RLHecht Yes, the react wizard needs to be updated by an engineer. I'm happy to review/preview the updates when ready.

**Comment by jenniferlee-dsva** [comment]
@kelsonic Thank you for picking this up! Appreciate you! Please let @peggygannon know when the change is ready to review.

**Comment by kelsonic** [comment]
@peggygannon the PR is ready for review! https://github.com/department-of-veterans-affairs/vets-website/pull/10927

**Comment by Karak888** [comment]
wizzard needs to be updated out of Drupal.  @kelson to find out if there is a way to merge this to see if we can view in drupal preview.  SME has additional pages so @jenniferlee-dsva will assign another iteration per those pages.

**Comment by jenniferlee-dsva** [comment]
@peggygannon - kelson says this wizard has been merged and wll go live today. can you be sure to review the drupal page copy update and publish if all looks ok?

**Comment by peggygannon** [comment]
@jenniferlee-dsva @kelsonic I've reviewed and published this page in drupal today.
