### ISSUE TITLE
Update Disability hub AMA appeals info

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2609]
**This set of changes include pages still published through GitHub only.** 

Please provide Heroku preview pages with these updates this week, Wed or Thu (to shoot for going live with Friday's daily deployment). 

Per Disability and AMO stakeholder change requests, updates include:
- Clarifying misleading or confusing info (e.g., calendar timeframes/deadlines)
- Refining minor UX - spacing, header issues
- Updating meta title (browser title) and other page copy with style guide standards (like numbers, etc.)

**Affected pages**
1/ VA decisions reviews and appeals:  https://www.va.gov/decision-reviews/ 
2/ Request a Higher-Level Review: https://www.va.gov/decision-reviews/higher-level-review/
3/ File a Supplemental Claim: https://www.va.gov/decision-reviews/supplemental-claim/
4/  After you request a decision review: https://www.va.gov/decision-reviews/after-you-request-review/
5/ Request a Board Appeal: https://www.va.gov/decision-reviews/board-appeal/

**See Word doc with screenshots and highlighted text changes.**
[Disability-AMA-appeals-VAgov-edits-AMO-100719-FSomers-jlee.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3751071/Disability-AMA-appeals-VAgov-edits-AMO-100719-FSomers-jlee.docx)  [10/21 REATTACHED WITH .DOCX ADDED TO FILE NAME]

**Checklist/acceptance criteria**
[X ] Updates made in Github.
[X] Style guide and proofread checks. 
[ ] Preview heroku links shared with Jen & Disability and AMO stakeholders. 
[ ] Updates validated/confirmed ok by stakeholders. 
[ ] Publish via Github.

@Karak888 fysa - Could you please assign Anne or Randi? I think they both can take this, as this is a GitHub only ticket. I'm not sure who has most bandwidth.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I'm getting an error message when I try to open the Word doc you attached. Can you upload again?

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I will Slack the attachment to you. Not sure what the GH issue is.

**Comment by jenniferlee-dsva** [comment]
Just tried to reattach with .docx added to filename link. Not sure it will work though. Just fyi.

**Comment by RLHecht** [comment]
@AnneHurley These pages are now ready for you to review in Github. I made all the stakeholder edits and also proofread the pages. Once you're good with it we can share the links with stakeholders. @jenniferlee-dsva @Karak888 

Heroku: https://vagov-content-pr-570.herokuapp.com/
PR: https://github.com/department-of-veterans-affairs/vagov-content/pull/570

**Comment by AnneHurley** [comment]
@RLHecht  @jenniferlee-dsva  @Karak888  I've reviewed/approved this page and it's ready for SME review.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley - just want to confirm - there are actually 5 pages. Are all 5 reviewed and ready for SME?

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  - Yes all ready assuming all the time info etc is correct.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - One teensy thing. On the Decision Review page, there's a missing colon after a bolded Note. 

Note[MISSING COLON] You can’t file a Supplemental Claim if you have a fiduciary claim or you’re one of multiple people claiming the same benefit (this is rare). 

Will send this to stakeholders with preview links now, as this is not a showstopper, but wanted to note it should be fixed before go-live.

**Comment by RLHecht** [comment]
@jenniferlee-dsva Good catch! That's been fixed now so all we need to do is enter any other stakeholder changes.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I've made updates to the GH instances of these pages. 
1/ Please review and fix any weird things and style things
2/ And please provide the heroku preview links that I can share with SME prior to publishing. 

https://vagov-content-pr-570.herokuapp.com/decision-reviews/board-appeal/
https://vagov-content-pr-570.herokuapp.com/decision-reviews/higher-level-review/ 
https://vagov-content-pr-570.herokuapp.com/decision-reviews/supplemental-claim/
https://vagov-content-pr-570.herokuapp.com/decision-reviews/after-you-request-review/ 
https://vagov-content-pr-570.herokuapp.com/decision-reviews/

And this one in Drupal was updated - steps 2 and 3:
http://preview-prod.vfs.va.gov/preview?nodeId=901 

The SME feedback is documented here - it's very messy, so I'm happy to walk through specific areas of what has changed. Also described the changes in the message logs.
[Fred-feedback-Disability-AMA-appeals-VAgov-103019.docx](https://app.zenhub.com/files/133843125/a0760007-b36e-44ce-a600-1cb75108e124/download)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've finished my review of these. There were just a few minor tweaks on each. 

Here are the links: 
https://vagov-content-pr-570.herokuapp.com/decision-reviews/board-appeal/
https://vagov-content-pr-570.herokuapp.com/decision-reviews/higher-level-review/
https://vagov-content-pr-570.herokuapp.com/decision-reviews/supplemental-claim/
https://vagov-content-pr-570.herokuapp.com/decision-reviews/after-you-request-review/
https://vagov-content-pr-570.herokuapp.com/decision-reviews/
http://preview-prod.vfs.va.gov/preview?nodeId=901

**Comment by jenniferlee-dsva** [comment]
These have been shared with SME and stakeholders for final review.

**Comment by jenniferlee-dsva** [comment]
@RLHecht  or @AnneHurley - Could one of you do a final proof read/check and publish the following pages for tomorrow's (Friday) deployment?

1/ VA decisions reviews and appeals https://vagov-content-pr-570.herokuapp.com/decision-reviews/  [updated with a couple new SME edits - see GH change log/message]

2/ After you request a decision review https://vagov-content-pr-570.herokuapp.com/decision-reviews/after-you-request-review/

3/ File a Supplemental Claim with new evidence https://vagov-content-pr-570.herokuapp.com/decision-reviews/supplemental-claim/  [updated with a couple of SME edits- see GH change log/message]

4/ Request a Higher-Level Review https://vagov-content-pr-570.herokuapp.com/decision-reviews/higher-level-review/

5/ Request a Board Appeal https://vagov-content-pr-570.herokuapp.com/decision-reviews/board-appeal/  

**DO NOT PUBLISH THE File a VA disability appeal Drupal page.**  Once the above 5 pages go live, I will close this ticket and create a new ticket to capture the new/additonal SME changes that affect the Drupal page and others from stakeholder.  The stakeholder has additional (new) changes, but has agreed to break out new scope to work on separately, so the above 5 can go live now.

**Comment by RLHecht** [comment]
@jenniferlee-dsva @AnneHurley I'll take a look at these pages now and have Anne approve the PR.

**Comment by jenniferlee-dsva** [comment]
Thank you!

**Comment by RLHecht** [comment]
@jenniferlee-dsva All of your changes look good. I've proofread the page with no more edits. Since I created the PR, I can't approve it, so Anne will have to. @AnneHurley This is ready for you! Once you approve it I think you can ask Kelson to merge it.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've validated the changes you made yesterday on the live site. You can close this ticket and pull out the info about the one Drupal page.
