### ISSUE TITLE
Access for Adam Stilton

### ISSUE THREAD

**Issue by as-va** [department-of-veterans-affairs/va.gov-team#26091]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Adam Stilton
- Please Provide your email.
   > adam.stilton@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse, Software Engineer, Liberty IT Solutions

- Requesting SSH key authorization?
   > NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
SSH access previously granted in issue 20253
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20253
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
    > Access to logs for Facilities and CCE APIs.

**Comment by omgitsbillryan** [comment]
@drorva - am I understanding correctly that we (ops) should now tag you in these tickets rather than trying to reach out to the COR directly?

**Comment by drorva** [comment]
@omgitsbillryan I replied in slack.

**Comment by omgitsbillryan** [comment]
**For AWS Access**

User: Adam Stilton
COR: Cecilia Lee
Approval required: @drorva (or @mchelen in Drors absense)

**Comment by jjennings-va** [comment]
@drorva or @mchelen can we get this access pushed through? It has been pending for a good amount of time now. Please let us know if anything needs to be done on our end.

**Comment by drorva** [comment]
Sorry for the delay.
Email sent to CORS, awaiting confirmation.

**Comment by drorva** [comment]
Approved

**Comment by jjennings-va** [comment]
Alright, now that it is approved, what are the next steps to get Adam his credentials? Anything we need to do on our end?

**Comment by golavarr-va** [comment]
Is there anything still pending with this ticket? Just wanted to doublecheck in case I can assist providing additional information. Thank you!

**Comment by drorva** [comment]
@omgitsbillryan should process it.

**Comment by mchelen-gov** [comment]
@omgitsbillryan is this complete?

**Comment by jbritt1** [comment]
@as-va have you been given any temporary credentials at this time?

**Comment by omgitsbillryan** [comment]
Attempted to coordinate a time to deliver temporary credentials to @as-va , but haven't been able to coordinate a time.
![image](https://user-images.githubusercontent.com/3077884/128546978-fe16274f-57a3-4a5a-bfc0-e21f97b279aa.png)

His account is ready to go, just need to coordinate a time to deliver credentials. 

Side note, I prefer to deliver the login credentials synchronously so that the user can quickly add their MFA device. I'm not fond of an asynchronous pattern where we have an IAM account that does not require MFA to login.

**Comment by omgitsbillryan** [comment]
The account is created in IAM but is currently disabled for GUI console login.

**Comment by jbritt1** [comment]
Can anyone provide an update on this access request?

**Comment by jsgarmon** [comment]
User has indicated he no longer requires DSVA AWS access. Closing this ticket, which can be reopened if needed.
