### ISSUE TITLE
CT Redesign: Add "Payments made to school" calculations to compare page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26096]
As a developer, I need to add the calculations that exist on the current profile page to the comparison page so that the users of the redesigned comparison tool can compare the financial aspects of institutions.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria
1. The "Payments made to school" section displays the following calculated data for each institution:
    a. Tuition and fees
    b. GI Bill pays to school
    c. Out of pocket tuition

## Supporting Artifacts
1. [Prototype - Compare three schools](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060322_CT_Redesign_PI10_Desktop_ComparePg)

2. Payments made to school section
<img width="802" alt="Screen Shot 2021-06-15 at 3 13 05 PM" src="https://user-images.githubusercontent.com/48260534/122110169-3cbe1c00-cdec-11eb-9855-a22d9acd553c.png">

3. [Documentation of how the amounts are currently calculated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/data/calculation-definitions.md)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17748

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1977&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
