### ISSUE TITLE
Rename vet360 components/modules

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#2611]
As a developer, I want the file names of components to match the actual component name to make it easier to navigate and understand the code. ie, it should be obvious when glancing at an open tab which component the file corresponds to.

For example, the Vet360EditModal component's file is named `EditModal.jsx` but should be changed to `Vet360EditModal.jsx`. Also, `InitializedID.jsx` should be renamed to `InitializeVet360ID.jsx` to match its default export.

**Comment by Justin-Pickett** [comment]
@erikphansen can you let me know the status of this ticket?

**Comment by erikphansen** [comment]
I still have a local branch with most of the work done. Got sidetracked with address validation API stuff and will try to wrap this one up by EOW!

**Comment by Justin-Pickett** [comment]
@erikphansen just wanted to touch base with you on this ticket status?
