### ISSUE TITLE
Implement Emergency mashup: New UI elements

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26173]
## Issue Description
Following design intent conversations and Veteran research, we need to implement the new Emergency care mash-up search experience

## Related work
- Query/merge and sort effort #25987 

---
### Front end

- [ ] Implement new emergency care mash-up search experience, consistent with prototyped design (designer: Nick O)
     - [Link to mobile prototype](https://preview.uxpin.com/1301b20e90a5233463e47d27e1f970738f4abf0e#/pages/139532595/simulate/no-panels?mode=i) (Click on the "Documentation" tab to view spec notes)
     - [Link to desktop prototype](https://preview.uxpin.com/1301b20e90a5233463e47d27e1f970738f4abf0e#/pages/139532581/simulate/no-panels?mode=i) (Click on the "Documentation" tab to view spec notes)
- [ ] Add screen reader announcement and focus flows

### Legacy search experience
- [ ] Searches using the legacy pathway (Facility type= `Community providers (in VA's network)` + Service type = `261QE0002X, 282N00000X, 282NC0060X, 282NR1301X and 282NW0100X`) should be mapped to the new search experience

## Acceptance Criteria

- [ ] Veterans are able to select `Emergency care` as a facility type

**When facility type = `Emergency care`**
- [ ] the "Call 911" alert is displayed at full-width, at all breakpoints
       - [Design system reference](https://design.va.gov/components/alertboxes#background-color-only)
       - ​[Storybook code reference](https://design.va.gov/storybook/?path=/docs/components-va-alert--background-only)
       - 911 is actionable within text alert
- [ ] the service type dropdown includes 
      - `All in network emergency care`
      - `VA emergency care`
      - `In-network emergency community care`
- [ ] **_and_** service type =` All in network emergency care`, the results list contains the twenty closest locations corresponding to Facility type = `VA health` + Service type = `Emergency` **and** Facility type= `Community providers (in VA's network)` + service type = `261QE0002X, 282N00000X, 282NC0060X, 282NR1301X and 282NW0100X`, regardless of facility type
- [ ] **_and_** the service type =`VA emergency care`, the results list contains the twenty closest locations corresponding to Facility type = `VA health` + Service type = `Emergency`
- [ ] **_and_** service type =`In-network emergency care`, the results list contains the twenty closest locations corresponding to Facility type= `Community providers (in VA's network)` + Service type = `261QE0002X, 282N00000X, 282NC0060X, 282NR1301X and 282NW0100X`
- [ ] Search result cards for community care facilities contain 
       - Letter corresponding to map
       - Name of facility
       - Address
       - Hyperlinked "Get Directions"
       - Actionable phone number
       - Call to confirm services and hours
       - Actionable link to emergency care benefit (`Learn about your in-network emergency care benefits`) linking to https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency_Care.asp
- [ ] Legacy search pathways for Community emergency care locations display the new 911 alert and contain links to the emergency benefit page in search result cards
      - Facility type= `Community providers (in VA's network)` + Service type = `General Acute Care Hospital`
      - Facility type= `Community providers (in VA's network)` + `General Acute Care Hospital - Critical Access`
      - Facility type= `Community providers (in VA's network)` +  `General Acute Care Hospital - Rural`
      - Facility type= `Community providers (in VA's network)` +  `General Acute Care Hospital - Women` 
      - Facility type= `Community providers (in VA's network)` +  `Clinic/Center - Emergency Care` 
- [ ] Legacy search pathways for VA Emergency facilities display the new 911 alert
      - Facility type = `VA health` + Service type = `Emergency`
- [ ] When a Veteran using a screen reader views the search results, the emergency alert is announced
- [ ] Users navigating via keyboard can tab first to the emergency alert, then to the 911 within the alert, then to the search results subhead 
- [ ] Emergency alert gains focus after "Search" button, followed by "911" link, followed by search results subhead 
- [ ] Clicks on the link to the emergency care benefit page are tracked (event: `cta-emergency-benefit-button-click`)
- [ ] Environment check is in place to hold changes in staging until validated by team and accessibility specialists

**Comment by mmiddaugh** [comment]
@joshkimux @AngelaFowler82 these changes are now available in staging. We will appreciate your review when you are able. Thank you!

**Comment by AngelaFowler82** [comment]
Looks good to me.

**Comment by mmiddaugh** [comment]
Thank you for your quick review @AngelaFowler82!
