### ISSUE TITLE
VA direct - Increase character limit in reason for appointment field

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26170]
## Description
In response to veteran feedback, we'd like to increase the character limit in the reason for appointment field. The max should be the same regardless of reason.

Currently, users can enter a max of 150 characters less predefined booking notes.
- Follow-up/Routine = 131 characters (150 - 17 booking note - 2 prefix)
- New issue = 139 characters (150 - 9 booking note - 2 prefix)
- Medication concern = 130 characters (150 - 18 booking note - 2 prefix)
- My reason isn't listed = 126 characters (150 - 22 booking note - 2 prefix)

![DS - reason for appt - default copy.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/03701eae-94de-47ee-a8f9-424c25171e43)

## Backend Dependencies
- [ ] _TBD_

## Acceptance Criteria
- [ ] If direct schedule flow, Then users can enter up to _x_ characters

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
Ask in SoS if we can increase the limit.
Spike for checking new short prefixes

**Comment by laurenernest** [comment]
We can't get the limit increased from 150. Spike ticket #26359 has been created to research how else we may be able to expand.

**Comment by ldelacosta** [comment]
Closing out this ticket. We completed the work in [58398](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/58398) and [57111](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/57111). cc: @JRRoof
