### ISSUE TITLE
[Frontend] Update 10-10EZ introduction page

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#26172]
Update 1010ez intro page per [10-10EZ Intro design and content](https://app.zenhub.com/files/133843125/d2846f8c-4784-4901-b43e-a45e7864b70e/download)

**Comment by Dene-human** [comment]
[10-10EZ Intro design and content](https://app.zenhub.com/files/133843125/d2846f8c-4784-4901-b43e-a45e7864b70e/download)

**Comment by Dene-human** [comment]
Basically all content has been changed from the title down to the footer including the "Need help?" section. I think we should make sure to work with Angela on this to make sure we do the proper heading sizes/labels.

**Comment by dat-gcio** [comment]
Note to self: this will need to be behind an environment guard so that it can be validated in staging first.

**Comment by dat-gcio** [comment]
@Dene-human The review instance [link](http://39ab6d6c70d689d104c1627702e11f45.review.vetsgov-internal/health-care/apply/application/introduction). Here is also the PR if you wanted to see screenshots https://github.com/department-of-veterans-affairs/vets-website/pull/18061

**Comment by Dene-human** [comment]
Thanks @dat-gcio I reviewed all of the screenshots and just have very minor feedback. I will review the RI after my morning meetings, just to check to the links.

1. Authenticated, not started: The green button at top has wrong capitalization
2. See screenshot below: Please check that there is a space between 7 and (TTY
![Screen Shot 2021-07-30 at 9 57 04 AM](https://user-images.githubusercontent.com/80857940/127663869-d48323c8-47c4-47eb-af86-c0d52a723257.png)

**Comment by dat-gcio** [comment]
@Dene-human Updated the green button capitalization. Also checked the spacing between TTY: and 711 and it renders for me. You can check when you do the review by highlighting the space in between.

**Comment by Dene-human** [comment]
Due to a miscommunication in content versions. I am posting this as the "final"
[Content source of truth](https://app.zenhub.com/files/133843125/c44c0377-a67b-4d9a-a4fc-ce31ca0e9870/download)

**Comment by Dene-human** [comment]
Checked and good to go into staging!

**Comment by dat-gcio** [comment]
@tchrisdyer @dnalbach Here is the link to the [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/18089). I would test it again in the review instance to make sure it all looks good still before merging.

**Comment by mdewey** [comment]
Updated to master is ready for review : https://github.com/department-of-veterans-affairs/vets-website/pull/18089

**Comment by tchrisdyer** [comment]
Verified in production. Closing
