### ISSUE TITLE
Run test scenarios to support VBMS testing (beginning Nov 4)

### ISSUE THREAD

**Issue by AZSchneider** [department-of-veterans-affairs/va.gov-team#2618]
## Purpose

As a Benefits and Memorials team member, I need support VBMS in testing their interactions with VA.gov so that I can be confident that VBMS changes have not affected VA.gov submissions of 526 forms. 

## Background and scenarios

(test user accounts are being created to support this)
See info below from the email from Jennifer Powell:

"VBMS is preparing for our 18.0 release and we are requesting your assistance with our regression testing. Please find below the preliminary VBMS test plan for VA.GOV testing for our next release.  This assumes that there are no scheduled changes for VBMS or VA.GOV functionality.  Any additional or unscheduled changes would lead to a modification of the test plan to accommodate these changes.  
 
VBMS UAT testing for our 18.0 release will begin on **Nov 4, 2019**. We would like to run through eleven (11) varying claim scenarios with various test records, including an ITFs to validate it is functioning correctly. We will be validating the claim process is correct with the National Work Queue (NWQ) functionality. We will plan on starting on Nov 4, 2019. Additionally, we will validate that VA.GOV has access to the efolder documents uploaded. If another date in that week or the next week works better, please let us know.
 
Prior to testing we request that the test accounts be cleared and have no pending claims. To test the pre-discharge scenario accurately it will need to be a test account with no prior claims.
 
If any defects related to VA.GOV claims are identified in this initial test window, once the defect is fixed (either by VA.GOV or VBMS), we will set up a time as soon as possible to re-test and validate the defect is fixed.  As soon as we are aware of the timing of the fix, we will determine the next available time that works for all parties to validate the fix.
 
On **Monday, Nov 25, 2019**, the day after we have received the final production candidate build, we will test 3 additional regression claim scenarios.  To best test this functionality with all interested parties, we can set up a coordinated meeting (Lync Online Live Meeting) for this morning.  We will use this test to validate the VA.GOV functionality is still working correctly in the final build. 
 
We will be using the final criteria to determine a successful test:
[ ] Correct EP Code is Established
[ ] ~If applicable, claim is established as a pre-discharge claim~ (can't do from current VA.gov capability)
[ ] Date of claim is correct
[ ] Claim Established is a VBMS Claim
[ ] All contentions came over exactly as they were entered
[ ] All special issues came over exactly as they were entered
[ ] Military service in VBMS matches military service in corporate
[ ] Address in VBMS matches address in Corporate
[ ] The correct number of documents are received
[ ] 25 MB documents received in correct eFolder
[ ] 25 MB documents received in an appropriate time frame
[ ] Document date of receipt in eFolder is correct
[ ] Documents are not corrupted
[ ] Document properties reflect the correct date and source
[ ] PDF in the eFolder matches the PDF submitted in VA.GOV; Validation of the FDC checkbox will also be performed during the PDF Review (In order for us to validate this item, we will need the copy of the documents submitted/generated)
[ ] Documents are labeled correctly
[ ] New mail indicator displays appropriately in the eFolder. 
[ ] Intent to File displays in VBMS UI correctly
[ ] The system shall display the correct claim source: VA.GOV
 
We will be using the final criteria to determine a successful test in relation to the NWQ
[ ] The claim is established and becomes a NWQ claim
[ ] The claim is routed accurately
[ ] The claim can be processed through the NWQ (IE it goes back and forth to 499)
[ ] Coordinated testing at every stage of working claims through the system, to make sure that all updates (as it bounces back and forth to 499) are reflected accurately in both systems, VBMS and VA.GOV.
 
The original 5 scenarios will be a mix of both SEP and eBenefits claims:
eBenefits – Predischarge claim [QuickStart]
eBenefits – Regular (non-predischarge) claim, with multiple document attachments
eBenefits – claim with address change
eBenefits – claim with contentions with special characters
eBenefits-ITF [If ready for testing by VA.gov]
 
The final 3 scenarios will be:
eBenefits – Predischarge claim [QuickStart]
eBenefits – Regular (non-predischarge) claim
eBenefits-ITF [If ready for testing by VA.gov]
 
 
If there is any additional information anyone is looking for, any feedback or modifications of the proposed test plan, or more details that you think should be included in the test plan, please let me know!  Since NWQ testing is a new component, I will be happy schedule a meeting to discuss NWQ testing."

**Comment by YanaRoy** [comment]
@SMLuthi @camerontesterman what do you need to prepare for monday's UAT support? Anything I can help with?

**Comment by AZSchneider** [comment]
Here are the test account logins to use and the high level scenarios we need to address:
1. Regular (non-pre-discharge) claim, with multiple document attachments—Existing Veteran = File number with existing claim.  
2. Claim with address change- Existing Veteran with prior claims = File number with existing prior claim (closed).
3. Claim with contentions with special characters- Existing Veteran = File number with exiting claim. (so, use a disability with an apostrophe in it)

I'll send the test user names and pw separately @SMLuthi 
If you need me to do this for you tomorrow, say the word.

**Comment by AZSchneider** [comment]
Part 1 complete:
Submitted 4 claims with the following claim ID's and test user accounts:
* User vetsgov+test209@id.me Claim # 600170949 has a large file size attachment (24.5MB)
* User vetsgov+test205@id.me Claim # 600170952 has a special character (Addison’s Disease) and 3 files attached. I also checked “VA employee” to see if it changes routing with NWQ
* User vetsgov+test206@id.me Claim # 600170953 has 3 disabilities identified (tinnitus, thumb, and back sprain) and I was able to change the address for this test user
* User vetsgov+test207@id.me Claim # 600170954 has PTSD identified as the disability, so a 781 form should be included with the submission

VBMS test team notified of the completed submissions in staging on 11/5/19.
