### ISSUE TITLE
Adjust GA Event Label: CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26183]
Adjust GA Event label to be `howToWizard-skip-orientation` not `ch31-orientation-skip` (per https://github.com/department-of-veterans-affairs/va.gov-team/issues/24557)

## Task
- [x] Switch the event label to reflect the above

## Acceptance Criteria
- [x] New event name is in place

**Comment by cohnjesse** [comment]
This original ticket had not been merged yet so I made this update there https://github.com/department-of-veterans-affairs/vets-website/pull/17421
