### ISSUE TITLE
Discovery: investigate strategies for mapping templates to pages

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#26198]
## Details

When a template or filter is modified, we need to build only the pages which use that template or filter. This incremental approach will help us keep builds fast as total node count increases. A challenge here is determining which pages to build based on a given template or filter modification. In this ticket we'll investigate the best method for ensuring we generate a complete list of pages.

See [#25773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25773) for a high-level summary of incremental build approaches.

## Definition of Done 
- [x] List the different types of templates, with an approach to finding page dependencies for each

**Comment by alexandec** [comment]
## Overview
To implement Partial Builds, we need to detect changes to templates or filters and build only the pages which use those templates or filters. A successful implementation will cover:

- Layout templates (top level)
- Partial templates (included in layout templates or in other partial templates)
- Filters (can be used in all templates)
- React app page templates
- vagov-content pages

Any of the above could be added, removed or modified. We need to detect all those actions and rebuild the appropriate pages.

On CI, change detection will examine the current branch to see what has changed. Locally, we'll watch for file changes instead. Some of this local work may be implemented in the [Revisit content-build watch command process](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/25379) ticket.

The Partial Build (PB) implementation will complement Small Batch Publishing (SBP). SBP will handle all content changes, while PB will handle all template and filter changes. The strategies described here form a key part of PB implementation.

## Template types

### Blocks
Block templates are used for alerts and promos. They are included inside certain layout templates and a paragraph template.

### Components
Component templates are partials used inside a variety of other templates. Some examples are sidebars, banners, phone numbers, and images.

### Facilities
As the name suggests, these templates are used by facility pages.

### Includes
Similar to components, these partials are used throughout the site.

### Layouts
These top-level templates are associated with page types. For example, a node with `"entityBundle": "landing_page"` would be rendered using the `content-build/src/site/layouts/landing_page.drupal.liquid` template. When a layout template is modified, we can get the entityBundle by grabbing `*.drupal.liquid` from the entityBundle value. Then we can loop through the `files` object and remove all the entries that don't have the correct entityBundle type.

### Navigation
These templates are used in sidebar navigation. 

### Paragraphs
Similar to components, these partials are used throughout the site.

### Teasers
Short partials repeated when listing events, news stories, and people.

## Filters
Detecting a changed filter and mapping it to a list of pages is challenging because the filters are almost all contained in a single file: `src/site/filters/liquid.js`. (There is also one filter in a separate file: `src/site/filters/phoneNumberArrayToObject.js`.) We can detect when the single large filter file changes. However it's difficult to determine which specific filter was modified.

Change detection would be much easier if each filter was in a separate file. The current filters/liquid.js file is about 1000 lines long, so refactoring it into separate files is a good idea for the developer experience as well.

For a complete implementation we need to detect added and removed filters, in addition to modified ones.

If we can get the name of the modified/added/removed filter, we can do something like `grep -r '| filterName' src/site/**/*.{liquid,html}` to find all the templates which use the filter. Then the problem is reduced to determining which pages to build based on that list of templates.

## Dynamic includes
Most liquid template includes are static, like this:

```
{% include "src/site/blocks/alert.drupal.liquid" with alert = alertBlock %}
```

Static includes allow us to find dependencies without actually running the code. We can just search through all the template files for a particular path. However, in some templates we use dynamic includes where the include path is calculated when the template is rendered. Here's an example in `src/site/paragraphs/alert.drupal.liquid`:

```
{% for paragraph in entity.fieldVaParagraphs %}
    {% assign bundleComponent = "src/site/paragraphs/" | append: paragraph.entity.entityBundle | append: ".drupal.liquid" %}
    {% include {{ bundleComponent }} with entity = paragraph.entity %}
{% endfor %}
```

In cases like this, we can't determine what templates might be included without running the code because the include path is formed using dynamic data from a GraphQL query. That means if one of the template partials in `src/site/paragraphs` is changed, we will be unable to compile a full list of pages to build because our dependency graph can't be properly traced back up to the top-level layout template(s).

We use dynamic includes in about 15 different templates. The above example is a common pattern. Some potential workarounds are:

- If a template in `src/site/paragraphs` is modified, search all templates for `assign bundleComponent = "src/site/paragraphs/"`. Trace any matching templates up to top-level layout templates. Rebuild all associated pages. It appears this method would cover all existing uses of dyanmic includes. If future uses were different, they would not be covered.
- Eliminate all uses of dynamic includes. This would solve the problem but it's not clear exactly how to replace existing uses with equivalent functionality. Also, can we prevent future uses of dynamic includes?
- Attempt to render the template with actual data, then read the resulting include path. This seems time-consuming and difficult to implement.

## React app pages
We can probably build these every time since they are quick to build and there aren't too many of them.

## vagov-content pages
These are remnants of an older static site build process. If they are not moved into Drupal, we'll have to handle them as a special case.

## Summary
A high-level overview of how we can handle changes:

- Top-level templates (layouts): Check which layout was modified, build only pages which use that layout.
- Lower-level templates (partials): Check which partial was modified, find which layouts use that partial, build only pages which use those layouts. (Note that multiple levels of includes may separate the partial from the layout).
- Filters: Check which filter was modified, find which partials use that filter, find which layouts use the partials, build only pages which use those layouts. (Note that layouts may also use filters directly. Also multiple layers of includes may be present.)

Some code can be shared. For example the layouts -> pages mapping will be used in every case to determine which pages to build. The partials -> layouts mapping will be used when filters are used inside partials.

**Comment by alexandec** [comment]
@theodur I've added my initial findings here in case that helps with your current work. If you have any thoughts or suggestions that's great too. I want to make this as complete and informative as possible.

**Comment by theodur** [comment]
@alexandec This is a great write-up. It covers most of what I discovered in my work on improving the `yarn watch` command as well. To add on to this from my implementation for `yarn watch` improvements, the steps in the Metalsmith build that need to be run again when only layout changes are made are:

- `Get files for rebuild` (New step that I added to filter out which files are needed for the rebuild)
- `Apply layouts` (Applies the updated layout changes)
- `Parse a virtual DOM` (There are some DOM modifications that need to happen again)
- `Create header and footer` (Without running this, the header/footer won't be present)
- `Rewrite VA domains` (Domains need to be rewritten since file content from the previous build was wiped)

Some other discoveries were the `entityUrl.breadcrumb` field in a file object kept getting the last element re-added to the array after each rebuild when using the cached Metalsmith file object. This increases the breadcrumb array with each rebuild. I'm still troubleshooting this issue though. Also, HTML templates seemed to get duplicated in the output file during each rebuild. Only HTML templates had this issue. Setting the `content` field blank before each rebuild seems to have fixed that issue.

Not all of this may be relevant as the incremental build may use a slightly different approach when building the content since I'm guessing it would be a new build with only the needed files rather than a rebuild, but hopefully it helps.

**Comment by alexandec** [comment]
@theodur Awesome, that is helpful, thanks!

My hope is we can share a bunch of code between your `yarn watch` implementation and the Partial Builds implementation. It's true that the Partial Build approach on CI would be a new build from scratch, but in reality it should be basically the same in how it operates. The main difference would be the method of determining which templates/filters have changed.

**Comment by alexandec** [comment]
@timwright12 this is ready for your review when you get a chance.

**Comment by timwright12** [comment]
@alexandec No real feedback, I think think this looks great. Thanks for putting it together!

**Comment by alexandec** [comment]
@timwright12 thanks, sure thing!
