### ISSUE TITLE
Redirect Request [JUNE 30] - VAMC - VA Wilmington health care 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26199]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
VHA Digital Media and VA Wilmington have approved moving VA Wilmington health care from dual state to full production, which includes redirecting traffic from TeamSite to new VAMC - System website. 
**Set URL redirect for June 30th, 2021**
Requesting that Current URLs be redirect for primary URLs listed below and that all remaining URLs under the root URL to be redirected to new VAMC - Website URLs.

### Requesting team info
VAMC - upgrade team - Stan Gardner - sgardner@governmencio.com
[vsa-vamc-upgrade Slack Channel](https://dsva.slack.com/archives/CPQFCQKEH) 

### Implementation date
**June 30th, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday June 30th, 2021

Please indicate when the change/redirect(s) needs to be implemented"
**June 30th, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday June 30th, 2021
- Redirect can occur at start of day so site can be validated and tested. 

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.wilmington.va.gov/ 		<br>  **NOTE:  This redirect is a catch-all for the top level of this sub-domain AND all remaining pages in the sub-domain that are not specified as a 1:1 redirect in the list below.**		| https://www.va.gov/wilmington-health-care/
**Removed by MN** <br> ~https://www.wilmington.va.gov/locations/directions.asp~ 	| ~https://www.va.gov/wilmington-health-care/locations/wilmington-va-medical-center/~
https://www.wilmington.va.gov/locations/Atlantic_County_Community_Based_Outpatient_Clinic.asp | https://www.va.gov/wilmington-health-care/locations/atlantic-county-va-clinic/
https://www.wilmington.va.gov/locations/Cape_May_County_Community_Based_Outpatient_Clinic.asp | https://www.va.gov/wilmington-health-care/locations/cape-may-county-va-clinic/
https://www.wilmington.va.gov/locations/Cumberland_County_Community_Based_Outpatient_Clinic.asp | https://www.va.gov/wilmington-health-care/locations/cumberland-county-va-clinic/
https://www.wilmington.va.gov/locations/Kent_County_Community_Based_Outpatient_Clinic.asp | https://www.va.gov/wilmington-health-care/locations/kent-county-va-clinic/
https://www.wilmington.va.gov/locations/Sussex_County_Community_Based_Outpatient_Clinic.asp | https://www.va.gov/wilmington-health-care/locations/sussex-county-va-clinic/
https://www.wilmington.va.gov/services/covid-19-vaccines.asp | ~~https://www.va.gov/wilmington-health-care/health-services/covid-19-vaccines/~~ ~New: https://www.va.gov/wilmington-health-care/covid-19-vaccines/~ <br> **UPDATED by MN** https://www.va.gov/wilmington-health-care/programs/covid-19-vaccines/

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@SgardnerPMP @mmiddaugh the new URL for the covid page is incorrect.  Redirect can't proceed until the URL is corrected.

**Comment by SgardnerPMP** [comment]
Menus have been updated.

**Comment by mnorthuis** [comment]
@SgardnerPMP FYI, corrected the COVID URL in above chart.

**Comment by mnorthuis** [comment]
@brianalloyd @kelsonic Redirects for VAMCs due on June 30. All URLs above have been reviewed and approved. @SgardnerPMP will be responsible for communicating any date changes.

Please note that this will redirect an entire sub-domain, HOWEVER, see the note on the first row. There are several URLs in that sub-domain listed for 1:1 redirects, then the root level of the sub-domain and all remaining pages will then be bulk redirected.

**Comment by brianalloyd** [comment]
Thanks @mnorthuis and @SgardnerPMP we're scrubbing into this now, will make a touch point with Stan to ensure timing and details as discussed last week are still "blue sky" and ready for implementation prior to release. @kelsonic or myself will follow up with any questions in support.

**Comment by mnorthuis** [comment]
@kelsonic Removed the 1:1 redirect for the directions page, left comment in the PR.

FYSA @SgardnerPMP

**Comment by kelsonic** [comment]
PR merged to remove directions redirects: https://github.com/department-of-veterans-affairs/vets-website/pull/17732

**Comment by kelsonic** [comment]
Updated redirect documentation for the future: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsa/teams/public-websites

**Comment by kelsonic** [comment]
Closing these redirect tickets for now since PW can't implement them: https://dsva.slack.com/archives/C52CL1PKQ/p1625759187483900?thread_ts=1625754059.481800&cid=C52CL1PKQ

We will keep a look out for how this new edge case can be implemented in our redirect process moving forward 👀
