### ISSUE TITLE
Discovery: document inner workings of metalsmith-incremental module

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#26194]
## Details

We'll need an incremental build solution in order to keep build times low even as total node count grows. The `metalsmith-incremental` module won't work for us as implemented, but it can inform our approach. In this ticket we'll document how the module performs incremental builds. The focus will be on how this approach can be adapted for our particular use case.

See [#25773](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/25773) for a high-level summary of incremental build approaches.

## Definition of Done 
- [x] Document structure and function of the `metalsmith-incremental` module
- [x] Describe which patterns we can use and how we might use them

**Comment by alexandec** [comment]
## Overview of functionality

By default metalsmith runs its build pipeline on all the files in the `files` object. This is inefficient since only a few files are usually modified. The `metalsmith-incremental` plugin offers a more efficient method. It first removes unchanged files from the `files` object so the build pipeline runs only on changed files. At the end of the pipeline, it adds the unchanged files back into the files object so metalsmith can output the full set of files. Here's an example:

```
// Remove unchanged files from the files object
metalsmith.use(incremental({ plugin: 'filter' }));

// Run metalsmith plugins on the remaining (changed) files only
metalsmith.use(plugin1);
metalsmith.use(plugin2);
metalsmith.use(plugin3);

// Restore unchanged files to the files object before writing to disk
metalsmith.use(incremental({ plugin: 'cache' }));
```

An advantage of `metalsmith-incremental` is that it's just another plugin. It can wrap the most time-intensive sequence of steps in the pipeline, while leaving other steps at the beginning and end of the pipeline to run on all files as before.

In addition to detecting file content changes, `metalsmith-incremental` can also look for template changes. To accomplish this you can pass a regex or a custom function to find the dependencies of each file. The resulting dependency graph can capture multiple levels of dependencies. If a dependency is modified, all the files using that dependency will be marked as modified as well. They'll be kept in the `files` object and built.

## Differences in our needs

### File contents vs templates
`metalsmith-incremental` looks for changes in both file contents and dependencies like templates. But in Partial Builds (PB) we only care about template changes. That's because content changes will be handled by [Small Batch Publishing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/34d977885efaff7dca6dc06c5aaeaaffe11ca967/platform/engineering/design-docs/2021-06-11-small-batch-publishing.md) (SBP).

### Change detection
`metalsmith-incremental` maintains a local cache to determine which files have been modified since the last metalsmith build. However for Partial Builds (PB) we need a solution which runs from scratch on CI, without any saved cache from previous CI runs. To solve this we can check which templates are modified in the current branch. For local development, we can implement a watch mode which checks for template file changes.

In the context of Partial Builds, "changed templates" means:

- Templates which are modified
- Templates which use filters which are modified
- Templates which include other templates which are modified (potentially multiple levels deep)

We have [another ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/26198) where we'll explore how to generate a list of pages to build based on a given template change.

### File output
When performing a Partial Build, it's not necessary to write all files to disk every time the build runs, as `metalsmith-incremental` does. Instead we'll just write changed files.

On CI we'll also need a method to sync only the changed files to the appropriate S3 bucket. Or maybe we can send SBP a list of pages to build, and it will build and deploy them for us. These deployment questions are outside the scope of the build process however.

## Useful patterns

`metalsmith-incremental` implements some patterns we might be able to use in our Partial Build implementation.

(Will list patterns here)

**Comment by alexandec** [comment]
@timwright12 @meganhkelley I think this writeup is in a good place now. There are some useful things we can use in our implementation when we get to that point. Please review when you get a chance.

**Comment by timwright12** [comment]
@alexandec I don't have many comments; overall I think this is great. I was thinking that we also need a way for the react app pages to trigger a rebuild, but I think we can probably build those every time since (I think) they're pretty lightweight. We had an instance lately where an app entrypoint name was updated, which would require a template rebuild for that app; they can also update breadcrumbs and such

**Comment by alexandec** [comment]
@timwright12 Thanks! I'll add something about the React pages to the [build strategies ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/26198) I just started working on. My plan there is to have a list of all the different template and filter types, and how we plan to handle each one.

Also good idea, I'll drop a message in the #content-release-engineering channel to get some additional feedback on this ticket.

**Comment by mchelen-gov** [comment]
@alexandec thanks for this writeup, it is super helpful in understanding how metalsmith-incremental works and what would be involved for our use case! i had a couple of clarification questions about the "Change detection" part:
> metalsmith-incremental maintains a local cache to determine which files have been modified since the last metalsmith build
this is referring to liquid template files right?
> However for Partial Builds (PB) we need a solution which runs from scratch on CI, without any saved cache from previous CI runs.
would caching data in CI help with this issue?

**Comment by alexandec** [comment]
@mchelen-gov glad it's helpful! 

The metalsmith-incremental cache contains the contents of every page (everything in the `files` object). When I tested metalsmith-incremental with our data, I found this approach to be quite slow. I think it would be fast with a much smaller site. But I guess that's the case with everything about metalsmith, haha.

I'm not sure caching in CI is worth the effort since Small Batch Publishing will handle content changes. If our Partial Build implementation can look only at template changes, change detection will be simple and fast, without requiring the extra complexity and slowness of maintaining persistent state across CI builds. That's my thinking anyway!

**Comment by alexandec** [comment]
Closing this since we have enough documented to help us in our own implementation. But the research and discussion will continue. Next up is [Discovery: investigate strategies for mapping templates to pages](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/26198).
