### ISSUE TITLE
General support

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26195]
## Issue Description
General support for Sprint 50

---
## Tasks
- Issue 1:  It looks like we have not seen a successful file upload since 6/16 at 10:34 am EST.
We see a response like [{"key"=>"File Upload", "text"=>"Unique ID: [1624286274514] Server Name: [ManagedServer006] ", "severity"=>"ERROR"}]
- Issue 2: EDIPI issue with BDD submission (via email from Paul Shute)
- 
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Issue 2 was resolved for the veteran - Apparently EVSS was not returning her claim data because she had 2 active CORP id's.  The identity team is owning follow-up on this on.e

**Comment by annaswims** [comment]
Issue 1 was solved with more details in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/26326

**Comment by annaswims** [comment]
Issue 1 was solved with more details in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/26326
