### ISSUE TITLE
[FE] Notification Prefs: Make CommunicationGroup model class

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#26193]
We need an easy way to know _which_ communication channels (ie, checkboxes) within a group have changed when a user is editing their communication preferences. One potentially clean way to do that is to make a CommunicationGroup class that would have the ability compare one instance's channel selections to another instance's channel selections. So let's make a class that will do just that.

**Comment by ajakabcin** [comment]
Rolling to sprint 51

**Comment by erikphansen** [comment]
PR is open for this so it might get closed out before EOD.

**Comment by ajakabcin** [comment]
PR was merged - closing :)
