### ISSUE TITLE
Add Logic for LoROTA config/option parameters

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#26192]
Add logic for optional LoROTA parameters.
e.g.

options: {
    validStart: '07/23/2021 10:30:00 GMT',
    validEnd: '07/23/2021 11:00:00 GMT',
    ttl: 30,  
    canRefresh: false,
    additionalValidation: [{'DOB' : '12/24/1956'}, {'last4SSN' : 1234 }]
  }

_** Still needs to be finalize with Stephen Barrs_

**Comment by kjduensing** [comment]
Discuss Post-Pre-MVP

PreMVP important fields: validStartDate, validEndDate
