### ISSUE TITLE
Remove accounts table reliance on idme_uuid

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#26190]

**Comment by nsoutouras** [comment]
Same status as 29577

**Comment by joeniquette** [comment]
waiting until after login.gov is working.

**Comment by nsoutouras** [comment]
MSI - Still waiting on Login.gov

**Comment by nsoutouras** [comment]
@bosawt Does this belong in any epics?

**Comment by bosawt** [comment]
@nsoutouras It is already in this epic: https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/5290 
Although that one's old. Do you prefer we just use recent epics?

I added it to the login.gov epic as well because it was technically necessary for that work
