### ISSUE TITLE
Conduct VHA Mobile clinic discovery interviews

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26203]
## Problem statement and background
<details>
<summary> Collapsed content </summary>

Mobile health clinics are VA health facilities that are included as locations under the relevant VAMC. These types of facilities were not part of the initial Pittsburgh pilot so the special attributes of this type of location were not foreseen. They don't fit the facility pattern established by the VAMC facility detail pages as they do not offer services at fixed locations. The information needed for these types of facilities may be different from that which is expected for brick and mortar medical clinics.

Before we reimagine the detail page experience, we want to more fully understand how mobile clinics are being used across the country so that it isn't based on our assumptions (such as: all mobile clinics have a predictable schedule of service locations)

**Questions**

- What Veteran population is served by mobile clinics?
- Why do Veterans choose mobile clinics for services?
- Are mobile clinics used differently in urban and rural areas?
- Does the mobile clinic have predictable locations/dates/times or is it determined by Veteran demand?
- What services are provided?
- Are appointments necessary? if so, how are they made?
- Is there specific eligibility criteria?
- What information does a Veteran need for these types of facilities?
- What info is meaningful for the "prepare for your visit" section?

</details>

## Tasks
- [ ] Conduct SME interviews to gain foundational understanding about these facilities

## Acceptance Criteria
- [ ]  Convo guide and documentation from SME conversations

**Comment by lildziner** [comment]
[Convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign/discovery/stakeholder-interview.md)

[Discovery Mural board
](https://docs.google.com/spreadsheets/d/11NlludP42r6DGWky0fKZEdJAET81cjdejZ5PJsCCrJc/edit?usp=sharing)

[Synthesis spreadsheet](https://docs.google.com/spreadsheets/d/11NlludP42r6DGWky0fKZEdJAET81cjdejZ5PJsCCrJc/edit?usp=sharing): 2nd Tab> Mobile Synth

Completed:
- Cheyenne, WY
- Fayetteville, NC
- Central Iowa (Des Moines)

seeking two more

**Comment by mmiddaugh** [comment]
[Mobile discovery documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign)
