### ISSUE TITLE
 Inject a default ”lang” attribute into the HTML

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#26212]
When using the Liquid Template Testing Framework to test ["fragments" of html ](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/teasers/bio.drupal.liquid)(as opposed to pages), the following error is returned when running an Axe Check:

```
'<html> element must have a lang attribute' 
```

To avoid this error, inject a default ”lang” attribute into the HTML when testing fragments of HTML.

**Comment by holdenhinkle** [comment]
Hey @mpelzsherman ... I just created the ticket. I'll try to get to this ASAP. Sorry for the delay.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/content-build/pull/296

This is complete.

**Comment by pjhill** [comment]
Thanks for knocking out this request!
