### ISSUE TITLE
Large text: links & phone numbers don't respect L/R gutter

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26222]
## What happened?
When viewing the app with large text:
1. Click-to-call numbers and some hyperlinks get cut off and don't respect the right-gutter
2. On the Appointments null screen, the **Visit VA.gov** link gets cut off on both the left and right gutters

## Specs:
- Device: iPhone 11, Galaxy S9
- User: +41

#### **For Issue #1**
1. In the device's settings, max out the text size
2. Log into the app
3. Go to the VCL page. Observe how the click-to-action buttons (phone number, text #, etc.) are cut off on the right side
     - Other pages where this issue occurs: Contact VA, Direct Deposit (not a comprehensive list) 

#### **For Issue #2**
1. In the device's settings, max out the text size
2. Go to the Appointments page (user +41 should display the null state) 
3. Observe how the **Visit VA.gov** link is cut off on both the left and right-margins: 
     - On the left, part of the arrow icon is cut off
     - On the right, part of the "v" in "gov" is cut off

## Desired behavior
All buttons and copy should be visible, without being cut off. Text should wrap to the next line if it cannot fit on a single line.

## Acceptance Criteria
1. Left and right gutter (20px each) should be maintained when viewing the app with larger text
2. Text should wrap to the next line when it hits the gutter

Design library w/ gutter specs: https://adhoc.invisionapp.com/console/Mobile-App-Design-Library-cknr12ik52y3q01yq037sp4nb/cknr136x63n9z01ys4xs75opr/play

**Note:** This appears to be working correctly for SM attachment links. See image below. 

## Bug Severity
- 3 - Medium

## Linked to Story
n/a

#### Issues 1 & 2
![Screen Shot 2021-06-16 at 12.45.16 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/66c03ddb-277a-4654-9b47-f44725d28338)

#### Desired behavior
![IMG_0306.PNG](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4159ed8e-570d-40ae-b6a9-6903ceee6d23)

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good on iOS and Android.  Closing.
