### ISSUE TITLE
Update downtime warning notifications to warning modal style

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#2622]
**User Story**:

As a UX expert, I want the downtime warning notification updated so that it clearly communicates that the platform is going down soon. 

**More context**: 

These notifications are in the form of a default modal as displayed here https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/modal/ This type of modal does not indicate visually that the platform will be down for maintenance soon. A warning modal/notification could match the styling of the warning modal. This way it will alert users more visually 

**Current style**: 
![downtime banner 1.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/8272aa2b-c17d-4956-b563-6686cc1890d6)

**Expected style**:
![warningmodal.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/ae1adf74-f5f6-4867-b19d-b0eb633ffa30)

**Acceptance criteria**:
[ ] - All warning notifications on VA.gov about downtime maintenance are updated to the new style

**Comment by mandifrances** [comment]
@meganhkelley is this something that should have the FE Tools label on it? Trying to clean up my backlog.

**Comment by jilladams** [comment]
The design system has evolved since this time, downtime notifications along with it. Closing this on assumption that future iteration for downtime notifications will come down from DST guidance.
