### ISSUE TITLE
Access for Shawna Hein

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/va.gov-team#26227]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Shawna Hein
- Please Provide your email.
   > shawna@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Design Lead, Ad Hoc (through GCIO as prime)

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? 
   > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCy4315ygTIDSNqTQiNH0U7p6TxG4UNZ8aAiG2kpN9QKzUo7im6dZ1F/zN6qXpHu/VusjDe1eLaCFX0fd3RdrrzrbCOifLYc5AFX8XXMw5yK9192a0uH+tj2IMAhQsF0yfSOMxyWnFM8ndBv+64+Cjq85mjtnwBqn/3VIYoBgxtapv80rjXYOjhq9ckbm2kRuypBYNaPmbzINTKCZoZfs8jxYE7dhzvucuSbBkA6ujcZxLNfCDZYEzu0G7VEPDBsjBsT+ePs2/e8lqUbP2BIw1poDOP34ScuNbWNEMx7WE4KpvTYNS2HSCX7wchmYDe8oPxguv6Nn4xqgpNMegiNet3YFwIPPq/TszF9Wdm5kxniGBniRrhmMWH2wiWvH8B8KxAYw3sGWHeN0BCKJGufcnvbQL52eVpBOkchqSeARiiHgEiLKn/BgOHiULg788TgaQ8X5tqglDT25zv4/Cv3pphpTYJmbDpqBfnWpl57qcD1aaOwo/DfokThktpwvuMvkU= shawnahein@ShawnaLrMacbook.routerlogin.net

- Grant AWS Console access?
  > No

**Comment by drorva** [comment]
Approved by Mary.
@mchelen FYI, this is how I do it.

**Comment by jbritt1** [comment]
It does not appear this user is requesting AWS access ![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/8cc4f8fb-f915-44e6-b1f8-0f24389bde8f)

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
