### ISSUE TITLE
Content Feedback - Staging review - VAOS homepage refresh 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#26237]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@outerpress @laurenernest Here is my feedback for the homepage: 


**Consider**

1. COVID-19 vaccine appointment is no longer an option on the homepage. I recommend adding this to the intro line (see below), so users know they can make a vaccine appointment through  VAOS.  

Primary and specialty care and COVID-19 vaccine appointments are available. 

-----

2. For this error message on the homepage, I recommend adding "online" and tightening up the language to avoid repeating "you can"  (see recommendation below)

**You don’t have any appointments**
Schedule an appointment online now, or you can [call your VA medical center] to schedule an appointment.
{link} Schedule an appointment

**Comment by laurenernest** [comment]
@peggygannon 
cc @outerpress 
> Consider 1 - Primary and specialty care and COVID-19 vaccine appointments are available.

Since vaccine supply>demand and the VA has shifted focus to the walk-in experience, VAOS is more of an "other" option so we're opting not to implement this at this time.

---

> Consider 2 - You don’t have any appointments
Schedule an appointment online now, or you can [call your VA medical center] to schedule an appointment.
{link} Schedule an appointment

Since the dropdown selection has an empty state specific to it (past/canceled/upcoming/requested), do you have a recommendation on how we might include the distinction? In the top line maybe?

**Comment by peggygannon** [comment]
@outerpress @laurenernest 

To clarify, we are able to populate the top line with the appropriate state depending on the what dropdown says?

 If so, then yes, we should make this distinction in the message as well. So: 
**You don't have any past appointments**
**You don't have any canceled appointments**
**You don't have any upcoming appointments**
**You don't have any appointment requests**

{Updated message body}
You can schedule an appointment online now, or [call your VA medical center] to schedule an appointment.
{link} Schedule an appointment

**Comment by outerpress** [comment]
Thanks @peggygannon ! Yes, we should be able to adjust the top line based on the dropdown.

**Comment by laurenernest** [comment]
Dev ticket created #27244
