### ISSUE TITLE
Synthesize VHA Mobile clinics interviews

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26238]
## Problem statement and background
<details>
<summary> Collapsed content </summary>

Mobile health clinics are VA health facilities that are included as locations under the relevant VAMC. These types of facilities were not part of the initial Pittsburgh pilot so the special attributes of this type of location were not foreseen. They don't fit the facility pattern established by the VAMC facility detail pages as they do not offer services at fixed locations. The information needed for these types of facilities may be different from that which is expected for brick and mortar medical clinics.

Before we reimagine the detail page experience, we want to more fully understand how mobile clinics are being used across the country so that it isn't based on our assumptions (such as: all mobile clinics have a predictable schedule of service locations)

**Questions**

- What Veteran population is served by mobile clinics?
- Why do Veterans choose mobile clinics for services?
- Are mobile clinics used differently in urban and rural areas?
- Does the mobile clinic have predictable locations/dates/times or is it determined by Veteran demand?
- What services are provided?
- Are appointments necessary? if so, how are they made?
- Is there specific eligibility criteria?
- What information does a Veteran need for these types of facilities?
- What info is meaningful for the "prepare for your visit" section?

</details>

This issue to synthesize the information gathered in VHA Mobile clinic discovery interviews (#26203) to inform the VHA mobile clinic detail page redesign (#24611)

## Tasks
- [x] Synthesize information gained during SME interviews 

## Acceptance Criteria
- [x]  Recommendations and findings to inform next steps for representing VHA Mobile clinics

**Comment by mmiddaugh** [comment]
Consider service blueprint as artifact

**Comment by lildziner** [comment]
[Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-vha-mobile-redesign/discovery/research-findings.md#research-findings) md file

[Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1627038564401/bdd84c5da65e1000f7d3d2f2d365d03839a1466e?wid=0-1627563024271&outline=open) with visual examples/mockups
