### ISSUE TITLE
[Backend] Create Redis store that contains the list of PCAFC facilities

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26233]
## User Story

As a Veteran, I need to select the most relevant VA Medical Facility with a Caregiver Support Coordinator so I can participate in the PCAFC.

Research ticket: #20531

## Expected Behavior

We will store the list of facility names in Redis

## Acceptance Criteria

- [ ] Add here

**Comment by mlighdc** [comment]
@tchrisdyer let chat about this user story. I think the user story should be: 

> As a Veteran, I would like to select the VA medical facility where I receive care or prefer to receive care.

It does not necessarily have to be where there is a CSC. We should route on the backend to the appropriate facility to process the application.

**Comment by tchrisdyer** [comment]
Based on current design, this story is no longer relevant as we will be calling the live API.
