### ISSUE TITLE
Add dismissible alert documentation to design system

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#2623]
**User Story** 
As a UX expert, I want to read more documentation of dismissible alerts so that I can know when to use dismissible alerts in my designs. 

**Goal**:

Add more documentation on the alerts components page https://design.va.gov/components/alertboxes on when it’s appropriate to use a dismissible alert box. 

**Acceptance criteria**:
[ ] -Add more distinct rules in the “Guidance” section of the alert boxes of when to use a dismissable alert. 
[ ] -Add the dismissable alert box to the Sketch pattern library

**Comment by mandifrances** [comment]
This ticket has been addressed in the design system audit or the appropriate changes have been made.
