### ISSUE TITLE
Unauthorized Home: issues w/ margins & scaling when larger text is enabled

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26232]
## What happened?
On the Unauthorized Home screen:
1. The ">" icon in the **Find a VA location** button does not scale with larger text sizes (iOS & Android)
2. The padding below the VA logo is not maintained: the **Sign In** button bumps against the edge of the logo (iOS)

## Specs:
- Device: iPhone 11, Samsung Galaxy S9

## Steps to Reproduce
1. On an iPhone 11, max out the text size
2. View the Unauthorized Home page
3. Observe how the ">" icon in the **Find a VA location** button does not scale, but the arrow in the VCL banner does
4. Observe how the **Sign In** button hits against the bottom edge of the VA logo. The VA logo still maintains top-padding, but not bottom-padding

## Desired behavior
1. Icon scales with font size
2. VA logo maintains equal padding above and below the image

## Acceptance Criteria
See desired behavior. 

## Bug Severity
- 4- low

## Linked to story
n/a

## Screen shot(s) and additional information
![Screen Shot 2021-06-16 at 2.11.33 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4352104b-c8b7-4bc0-8263-268968bd322c)

**Comment by digitalken** [comment]
7/2/2021 - Looks good on Android, waiting on iOS build.

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good on iOS and Android.  Closing.
