### ISSUE TITLE
Drafts Folder Displays

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26240]
## User Story
As a user, I want to be able to see my drafts folder in the Folders tab so that I can see my draft messages.

## Acceptance Criteria
1. In the Folders tab, create a new ListItem for Drafts
2. The Drafts ListItem will display under the Sent ListItem, no matter if the user has draft messages or not
3. Drafts will leverage the existing loading state so that the app loads in drafts when a user navigates to the Inbox tab for the first time
4. Draft number icon is captured in the [draft folder icon](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/26243) ticket 

## Accessibility Guidelines

Drafts ListItem:
accessibilityLabel= "Drafts"
accessibilityRole= "button"
accessibilityHint="View your draft messages"
denote sequence of this button in the list (i.e. "2 of 2")

## Design
**Draft Folder List**
![drafts folder.png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/16fc85dc-934b-483c-a208-fc4af78f49b1)

**Comment by ashley-matthews** [comment]
@melissa-lefevre @narin - can you confirm if there are any limits on how long drafts live in the drafts folder?

**Comment by melissa-lefevre** [comment]
I have not been able to find anything as far as time limits.
