### ISSUE TITLE
[FE] | 10-10CG | Implement Lighthouse Facilities API for medical center selection

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26246]
## User Story

As a Veteran, I need to select the most relevant VA Medical Facility with a Caregiver Support Coordinator so I can participate in the PCAFC.

See Research ticket for more details: #20531

## Expected Behavior
- [ ] No changes to the UI
- [ ] Same select options are displayed as before

## Acceptance Criteria

- [ ] Update facilities drop-down to use list fetched from API instead of vets-json-schema enums
- [ ] UI behaves and looks as it did before
- [ ] Errors fetching should be logged to Sentry

**Comment by dat-gcio** [comment]
note to self: check in with Josh about using `aria` usage for radio buttons.
