### ISSUE TITLE
[Backend] Create (or use) an endpoint that serves the list of PCAFC facilities

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26244]
## User Story

As a Veteran, I need to select the most relevant VA Medical Facility with a Caregiver Support Coordinator so I can participate in the PCAFC.

See Research ticket for more details: #20531

## Expected Behavior

Service endpoint for facilities

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by longmd** [comment]
Closing. API endpoint is available for use already. No new endpoint is needed.
