### ISSUE TITLE
[Backend] Change JSON schema references to use service object module constant instead (i.e. pdf generation)

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26247]
## User Story

As a Veteran, I need to select the most relevant VA Medical Facility with a Caregiver Support Coordinator so I can participate in the PCAFC.

See Research ticket for more details: #20531

## Expected Behavior

Any backend code currently referencing the vets-json-schema for station numbers and labels would instead reference a module constant of similar values hardcoded in a new backend service object. 
 

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by dnalbach** [comment]
This is the line that will change from using the current vets-json-schema as a constant to using a service object constant instead:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/va1010cg.rb#L575

```
caregiver_facilities = VetsJsonSchema::CONSTANTS['caregiverProgramFacilities'].values.flatten
```

There are no other current code references to the `caregiverProgramFacilities` constant in the VetsJsonSchema, so this is the only line that changes.

**Comment by dnalbach** [comment]
See PR for change details. Rspec testing verifies expected PDF is the same whether the feature is off and using the JSON Schema or the feature is on and using the live Facilities API to fetch Caregiver facilities.

**Comment by dnalbach** [comment]
This has been merged and released, but continues to be feature toggled off.
