### ISSUE TITLE
Update Questionnaire Manager Swagger Docs

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#26257]

**Comment by loripusey** [comment]
@dillo can you please provide some information for this ticket so that I understand its purpose?
cc: @sarahknoppA6

**Comment by dillo** [comment]
@loripusey This is a placeholder story to update the endpoint documentation for developers(swagger docs) on the Clipboard/HealthQuest project, currently on the backburner.
