### ISSUE TITLE
[Backend] Create schedule definition for delete attachment job

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26252]
## User Story

Kevin mentioned this story as something he needed to do. I believe it was to create a cron job to delete attachments.

## Expected Behavior

We want to make sure that there are no orphaned document uploads for the Caregiver (10-10cg) form. 

## Acceptance Criteria

Manual
- [ ] Docs can still be attached to forms 
- [ ] Job can be run manually and attached documents remain while orphaned docs are deleted

Automated
- [ ] Orphaned are attachments are deleted automatically
- [ ] Job runs daily at midnight

**Comment by dnalbach** [comment]
Kevin mentioned this today as a reminder for an outstanding item.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/form1010cg/delete_old_uploads_job.rb

```
# frozen_string_literal: true

module Form1010cg
  class DeleteOldUploadsJob < DeleteAttachmentJob
    ATTACHMENT_CLASSES  = [Form1010cg::Attachment.name].freeze
```
There is some file that we add the schedule for it to run, which was not previously configured.

**Comment by MickinSahni** [comment]
tested this locally and confirmed files deleted overnight and waiting for an update re:prod. next question, how to verify via the web app.

**Comment by MickinSahni** [comment]
Verified a successful upload and submission in Staging. Verified a successful upload in Prod. Closing out. 
![image](https://user-images.githubusercontent.com/13204473/138003958-c3c7eab7-c6c5-4141-a1db-49b13f7cb74f.png)
