### ISSUE TITLE
[Backend] Create Feature Toggle for Facility Names retrieval functionality

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26269]
## User Story

As a Veteran, I need to select the most relevant VA Medical Facility with a Caregiver Support Coordinator so I can participate in the PCAFC.

## Expected Behavior

Feature toggle for the functionality to retrieve facility names from the Facilities API

## Acceptance Criteria

- [ ] Ability to toggle Facility names list source on/off (API vs static list)

**Comment by dnalbach** [comment]
PR
https://github.com/department-of-veterans-affairs/vets-api/pull/7396

**Comment by dnalbach** [comment]
PR merged today.
