### ISSUE TITLE
508 defect 2, screen readers, cognitive disabilities, household information page, changing a radio button changes the page.

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#26275]
Label: 

    - [508-defect-2]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2

Issue Title:508 defect 2, screenreaders, cognative disabilities, household information page, changing a radio button changes the page.

Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
Screen reader users and users with cognative disabilities expect the page they are working on to change only when they perform an action which they know will initiate that change. 

<h2>Details</h2>
In the household information section, when the user responds "yes" to the question "do you have additional dependents," a list loop appears on the page which allows the user to add as many dependents as they need. This may be confusing for users with cognative disabilities who are distracted by the change, or for screen reader users who are familiar with the page in its original form and may skip to the "continue" button. 

<h2>Acceptance Criteria</h2>
Pressing "continue" triggers the appearance of the list loop.

<h2>Proposed Solution (if known)</h2>
The list loop should come up on a new page once the user presses "continue" after answering "yes" to "Do you have additional dependents."

**Comment by hdjustice** [comment]
**FYI - This ticket is 2 years old.**
Once the Household section is in development, we can ensure we address this issue.  We believe it may be resolved with the new design

**Comment by longmd** [comment]
Just linking this to close when Household is done. This will be completed with #52960 .
