### ISSUE TITLE
Archived services linked within system accordion

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26277]
## Issue description
 In #23470, we prevented archived services from being included in the build. However, the links to archived health services for facility pages still appear in system service accordions.

## Steps to reproduce:

1. View [the Health services page for Houston health care](https://www.va.gov/houston-health-care/health-services/) 
2. Scroll down to “Addiction and substance abuse” accordion
3. Observe the link to Beaumont VA clinic, which has an archived facility health service for Addiction and Substance abuse 
4. Confirm archived service in [Drupal](https://prod.cms.va.gov/houston-health-care/locations/beaumont-va-clinic/addiction-and-substance-abuse-care)

<details> 
<summary> Screenshot from Prod </summary> 

![image](https://user-images.githubusercontent.com/55411834/122437167-b07c3800-cf56-11eb-8680-3107f96ac458.png)

</details>

<details> 
<summary> Drupal screenshot </summary> 

![image](https://user-images.githubusercontent.com/55411834/122436777-54b1af00-cf56-11eb-8031-b26712f87a23.png)

</details>

## Expected behavior
- The Facilities listed within health service accordions have only published services. 
- When a facility archives a health service, that location no longer appears listed within system health service accordions. 
- If a facility has a health service in draft, that location is not listed within the health service accordions for the system.

**Comment by mpelzsherman** [comment]
Our top-level graphql queries do filter out archived stuff, but these filters do not “trickle down” to all of the deeply-nested relationships in the data. For cases like this we have to do the filtering on the front end.
