### ISSUE TITLE
Contribute Card Component to VA Design System

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2627]
## Story
As a team member working on VA.gov, I want to be able to use the card component to display data in a more legible format.

## Goals
Contribute a component that houses multifaceted data in the form of cards as opposed to tables, which should only be used for numerical data representations.

## Considerations
- Review protocols found in the [Contributing to Formation](https://design.va.gov/documentation/contributing-to-formation) doc
- Live example of content card can be found in rated disabilities, [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/rated-disabilities/components/RatedDisabilityListItem.jsx).
- Screenshots are attached of the card layout that gets rendered. A more universally usable design may want to be implemented. 
- Ensure 508 Compliance is captured.

## Tasks
- Create a component that can accept different endpoints normally used in cards, in the previously used style.

## Acceptance Criteria
- [ ] Submit review/propose an update through a GitHub issue to the platform team

<img width="679" alt="Screen Shot 2019-10-16 at 2 47 38 PM" src="https://user-images.githubusercontent.com/15097156/67235072-38fdaa80-f3fb-11e9-8ae4-a7d49ee78ff2.png">

<img width="419" alt="Screen Shot 2019-10-16 at 2 49 49 PM" src="https://user-images.githubusercontent.com/15097156/67235102-49ae2080-f3fb-11e9-9dea-cfeed3b0e95b.png">

**Comment by ncksllvn** [comment]
I'm not sure if it's the same "Card", but on our upcoming widget on our Find VA Forms work, we have some blue boxes that I thought I heard referred to as Cards.

![Find VA Forms screenshot](https://user-images.githubusercontent.com/1915775/69464289-e7bf3e80-0d4b-11ea-9165-9aa5535b1e42.png)

So potentially, this is another app that could leverage this Design System component.

**Comment by ncksllvn** [comment]
Oh nvm, looking at your screenshot under `Acceptance Criteria`, they look quite a bit different. Disregard 😄
