### ISSUE TITLE
June Home Page Link Requests from VA 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#26276]
## Why you're here 

VA stakeholders have requested the addition of new links to the VA.gov Home Page -- either the Top Tasks boxes or the Footer.

We need to work with the IA and Content leads to determine how to respond to each -- e.g.

- Decline - and our rationale
- Accept - our rationale and where we will put the link, how it will be named
- Delay - to spend time researching options
- Escalate - to get air cover from OCTO-DE leadership

Here are the current requests:

- [ ] From OAR (decision reviews): Carolyn Temple requested that a link to their landing page be added to the hp because a recent VSignals survey indicated that Veterans are unable to locate the information about DR.
<img width="664" alt="Screen Shot 2021-06-17 at 2 46 46 PM" src="https://user-images.githubusercontent.com/66026798/122476494-2a261d00-cf7b-11eb-9fcf-d9538109ba37.png">

---

## About your support needs
- Sitewide IA will need to help guide decisioning
- Sitewide Content will need to determine/approve precise wording of links
- FE engineering support will be needed to implement any site links to the HP Top Tasks or Footer.  

### Desired/target implementation date

- VA Trust - in June
- OAR/Decision Review - in June

---

### About your team

- Team name: Public Websites
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Cassandra Allen
- FE engineer: Kelson Adams
- Product/team Slack channel: #vsa-public-websites
-
--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by bethpottsVADEPO** [comment]
@johnhashva I added the OAR request above with a screen shot of the ask.

**Comment by johnhashva** [comment]
6/28 Update on the CLP Trust HP Link request (@bethpottsVADEPO & @jenlee):  Tim Hudak accepted our rationale for not adding links to CLPs from HP -- so that item on this list is CLOSED.  
<img width="733" alt="Trust CLP HP Link" src="https://user-images.githubusercontent.com/63107147/123705590-2d4fc180-d835-11eb-9194-81a418f5ecf2.png">

**Comment by johnhashva** [comment]
Adding fresh Home Page analytics snapshot report -- via @cindymerrill -- on HP click-throughs for top tasks during weeks of 5/19/2021-6/28/2021. 

![image (4)](https://user-images.githubusercontent.com/63107147/123960766-b1ad5c00-d97d-11eb-8266-9af6d9fde9ca.png)

**Comment by brianalloyd** [comment]
@johnhashva noticed this at the bottom of VA.gov top task panel that redirects to CLP/Trust Initiatives page.  Just curious where this falls in the link strategy identified above?  Is the CLP ask already achieved and we just need to address the OAR request above? 

![Screen Shot 2021-07-20 at 2 39 49 PM](https://user-images.githubusercontent.com/70410912/126393236-46ae73b3-3fed-4e21-bda2-f5b00eb1b8b4.png)

**Comment by johnhashva** [comment]
@brianalloyd yes, the Trust ask is fulfilled -- but we need to keep this open (or I need to create a new ticket) for the OAR ask.   Let's keep this open while I compose a Product Outline of sorts to spell out how we are going to manage these requests in a more systematic way.

**Comment by brianalloyd** [comment]
@bethpottsVADEPO was just looking over this request and updated based on OAR ask, also linking in David Colon as well.  Any status update on this?

**Comment by bethpottsVADEPO** [comment]
@brianalloyd Thanks for the ping. I will get back in touch with OAR folks to see if they want to look at a short-term partial solution of best bets / typeahead. This is what I'd recommended to the fiduciary team that also asked for placement. But long-term we still will need to put together a plan for addressing these requests. You all can decide if you want to keep this ticket open or start a new, broader one. But we do need to make sure we don't lose track of this long-term need for an assessment criteria.

**Comment by FranECross** [comment]
@bethpottsVADEPO The last comment indicates this ticket should be left open and an assessment done. Do you know if any movement happened, or if this is still needed? Thanks! cc @davidconlon

**Comment by FranECross** [comment]
@bethpotts Just circling back around on my question above. Thanks in advance!

**Comment by FranECross** [comment]
Closing this old ticket as not needed, and am assuming a new ticket will be created if this is resurrected.
