### ISSUE TITLE
Borders on Claim/Appeal step tables are larger than designs

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26284]
## What happened?
The border size on the Claim & Appeal step tables is larger than the designs. In the build, it looks like the size varies between 2px and 3px. The designs call for a weight of 1px. 

## Specs:
- Device: iPhone 11, Samsung Galaxy S9
- Users: +1 (has active claims and appeals)

## Steps to Reproduce
1. Log in with user +1
2. View the Appeals detail page and the Claims detail page
3. Compare step tables in the build against design library: https://adhoc.invisionapp.com/console/Mobile-App-Design-Library-cknr12ik52y3q01yq037sp4nb/cknr136x63na401ys0t5epa4b/play. Observe how the borders in the build are thicker than those in the design library.

## Desired behavior
Step table borders are 1px. 

## Acceptance Criteria
See desired behavior. 

## Bug Severity
- 4 - Low

## Linked to story
n/a

## Screen shot(s) and additional information
![Screen Shot 2021-06-17 at 10.15.23 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/638bdae2-5d41-4070-8024-be6001dec43b)

**Comment by digitalken** [comment]
PASS 6/25/2021 - Looks good on iOS and Android.  Closing.
