### ISSUE TITLE
Manual migration of accordions web components in content build

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#26280]
Manual migration of accordions web components in content build

@bkjohnson , please add details as necessary on this work.

**Comment by bkjohnson** [comment]
## Template changes

There are 9 template files in `content-build` which need to be migrated from using the `usa-accordion` class to using the `<va-accordion>` and `<va-accordion-item>` Web Components.

1. [collapsible_panel](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/paragraphs/collapsible_panel.drupal.liquid#L25-L60)
1. [q_a.collapsible_panel](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/paragraphs/q_a.collapsible_panel.drupal.liquid#L1-L36)
1. [facility_health_service](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/facilities/facility_health_service.drupal.liquid#L1-L50)
1. [sidebar_nav](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/navigation/sidebar_nav.drupal.liquid#L19-L73)
1. [facility_no_drupal_page_sidebar_nav](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid#L23-L85)
1. [health_care_local_facility](https://github.com/department-of-veterans-affairs/content-build/blob/e1142aa247359b68f7bc83a564280fe36be4dcbb/src/site/layouts/health_care_local_facility.drupal.liquid#L133-L157)
1. [campaign_landing_page](https://github.com/department-of-veterans-affairs/content-build/blob/e1142aa247359b68f7bc83a564280fe36be4dcbb/src/site/layouts/campaign_landing_page.drupal.liquid#L458-L474)
1. [faq_multiple_q_a](https://github.com/department-of-veterans-affairs/content-build/blob/e1142aa247359b68f7bc83a564280fe36be4dcbb/src/site/layouts/faq_multiple_q_a.drupal.liquid#L55-L74)
1. [health_service](https://github.com/department-of-veterans-affairs/content-build/blob/e1142aa247359b68f7bc83a564280fe36be4dcbb/src/site/facilities/health_service.drupal.liquid#L1-L53)

I expect that `sidebar_nav` templates won't be able to be migrated immediately - some work will need to happen to the accordion to allow the kind of styling variation that we see on those pages if we want to still call them accordions. Here is an example:

### sidebar nav accordion

![image](https://user-images.githubusercontent.com/2008881/124000050-0a81f200-d988-11eb-8661-5b86da546cb8.png)

This looks different than the [accordion defined in the design system](https://design.va.gov/components/accordions).

---

The other templates should be more straightforward.

Additionally, there is another use of `usa-accordion` which I _don't_ think should be migrated to the accordion Web Component:

https://github.com/department-of-veterans-affairs/content-build/blob/e1142aa247359b68f7bc83a564280fe36be4dcbb/src/site/includes/usa-website-header.html#L1-L2

This may be better off as an additional info component, but I think it's best to leave the "accordion" banner at the top of the page as it is for now.

## Build changes

There is a build plugin that adds `id` attributes to `h2` and `h3` elements while specifically excluding headings that are a part of an accordion. For completeness, this should remove [the use of `usa-accordion`](https://github.com/department-of-veterans-affairs/content-build/blob/e1142aa247359b68f7bc83a564280fe36be4dcbb/src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js#L71-L72) and see what additional (if any) changes need to be made. The accordion heading (`usa-accordion-button`) is inside the shadow DOM, so the build plugin may not include that automatically which would be convenient. The nodes in the light DOM (`usa-accordion-content`) might show up in the `dom` search, so a change _may_ need to be made to exclude any headings in there.

**Comment by Rleahy22** [comment]
[collapsible_panel](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/paragraphs/collapsible_panel.drupal.liquid)
[q_a.collapsible_panel](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/paragraphs/q_a.collapsible_panel.drupal.liquid)
[facility_health_service](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/facilities/facility_health_service.drupal.liquid)
[facility_no_drupal_page_sidebar_nav](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid)
[health_care_local_facility](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/layouts/health_care_local_facility.drupal.liquid)
[campaign_landing_page](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/layouts/campaign_landing_page.drupal.liquid)
[faq_multiple_q_a](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/layouts/faq_multiple_q_a.drupal.liquid)
[health_service](https://github.com/department-of-veterans-affairs/content-build/tree/master/src/site/facilities/health_service.drupal.liquid)

Have all been migrated to web components via https://github.com/department-of-veterans-affairs/content-build/pull/378

1. [sidebar_nav](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/navigation/sidebar_nav.drupal.liquid#L19-L73) was not migrated per @bkjohnson [above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26280#issuecomment-871568160)

> I expect that sidebar_nav templates won't be able to be migrated immediately - some work will need to happen to the accordion to allow the kind of styling variation that we see on those pages if we want to still call them accordions.

Should we close this ticket and open a new one to migrate [sidebar_nav](https://github.com/department-of-veterans-affairs/content-build/blob/7c8411e38ca40c312d25547cf51f237b41d65fbf/src/site/navigation/sidebar_nav.drupal.liquid#L19-L73) once it is ready?

**Comment by brianalloyd** [comment]
@Rleahy22 @bkjohnson  I'm going to close out this ticket in support and place the `sidebar_nav` into a #28922 to action in future sprint when ready and available.
