### ISSUE TITLE
Access for Chris Dyer

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26289]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   >  Chris Dyer
- Please Provide your email.
   > chris.dyer@adhocteam.us -or- Thomas.Dyer1@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Caregivers Team, Product Manager, Ad Hoc LLC

- Requesting SSH key authorization?
   > NO

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > Cloudwatch to run reporting queries on the logs for the Caregivers form submissions.

**Comment by mydesignrocks** [comment]
@drorva - can you please review this

**Comment by mydesignrocks** [comment]
@mchelen  - can you please review in Dror's absence. thanks!

**Comment by drorva** [comment]
Approved.

**Comment by mydesignrocks** [comment]
AWS access provided.

**Comment by jbritt1** [comment]
> AWS access provided.

Was this done in error? The pull request for AWS access has not yet been approved, so should not have yet been applied.

**Comment by mydesignrocks** [comment]
yes Jeremy, was an error... addressing the "email" part as we speak. thanks for catching that.

**Comment by mydesignrocks** [comment]
email updated for the user to va.gov email.
