### ISSUE TITLE
vets-api sidekiq performance tuning

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#2628]
This is a tracking ticket for sidekiq performance tuning in vets-api as a result of EVSS / https://www.va.gov/track-claims/your-claims related issues from an incident on 2019-10-21.

- [ ] Look at enabling sidekiq [swarm](https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process) to maximize thoughput on the current c5.xl instances (is only using one core now)
- [x] Look at concurrency to see if there is tweaking to be done - specifically sync up database connection pool size with sidekiq threads

**Comment by nathanhruby** [comment]
see also #2614 for puma issues from same incident

**Comment by nwalke** [comment]
Staging and prod are using c5.large, dev and sandbox are t3.mediums

**Comment by wyattwalter** [comment]
@benniemosher can you open a ticket on the sidekiq upgrade stuff you talked about in Slack before closing this? I think that was to enable sidekiq swarm? I remember there was also some mention of metrics not working, is that worth opening a ticket on to follow-up?
