### ISSUE TITLE
Medallia | Translated Survey | JS Variable to Trigger Language

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#26292]
Medallia advised that they will need a JS variable to use to trigger the language translation needed for a given page.

"We need a JS Variable within the resources of each page storing the same language key (es for Spanish on spanish URL/page, tl for tagalog on Tagalog URL/page)".

Example on: www.usps.com. Search for variable name 'medalliaSurveyLanguage' on console

**Comment by SKasimow** [comment]
Slack discussion here: https://dsva.slack.com/archives/C015PF52YFL/p1623945596006400

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - can you link the PR and point this pls :)

**Comment by youngfreezyVA** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17632
