### ISSUE TITLE
Redirect Request [JULY 15] - Find a VA Form

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26299]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

A bulk redirect of URLs was completed last year to redirect URLs from the legacy VA Forms tool to the modernized Find a VA Form tool. It was recently discovered that some URLs in the legacy experience have been altered so that they now contain a backslash (`\`) or its ASCII equivalent - `%5C`, which is thwarting the original redirect's abilty to send users to the modernized tool.  Examples: 
- https://www.va.gov/%5Cvaforms/
- https://www.va.gov/%5Cvaforms/va/pdf/VA0896a.pdf
- https://www.va.gov/%5Cvaforms/default.asp?CurrentPage=2&orderby=number

These "rogue" URLs have also been picked up by search engines.

For additional info and context, please see this ticket:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/24949

### Requesting team info
*Indicate what team and who the primary contact on that team is*
Decision Tools - Marci McGuire and John Hashimoto

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*
There are no URLs; we are just requesting a bulk redirect to the modernized experience

Please indicate when the change/redirect(s) needs to be implemented"
- [x] On the same date the new URLs launch
- [x] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing :  Tuesday, July 15, 2021 to allow us time to notify the VA stakeholders at the monthly stakeholder meeting.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed
Current URL  |  Redirect Destination or New URL
--- |  ---
 `*va.gov/%5Cvaforms/*` | `https://va.gov/find-forms/`
`*va.gov/\vaforms/*` | `https://va.gov/find-forms/`

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [x] Implementation team: Implementation team completes work 
- [x] Implementation team: Implementation pushed live and redirect is validated in production
- [x] Requesting team: Ticket is closed

**Comment by MarciMcGuireGCIO** [comment]
Please note that I am on PTO June 18-27 and will answer any questions upon my return June 28.  Thanks!

**Comment by mnorthuis** [comment]
@brianalloyd This redirect is good to go.  Please not the July 15 date, so no rush on this one.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for the update, @mnorthuis !  cc @johnhashva @zacharymorel FYSA.

**Comment by MarciMcGuireGCIO** [comment]
@mnorthuis @brianalloyd cc @johnhashva - just wanted to confirm that John shared this info out to the VA Stakeholders via email on Friday.

**Comment by brianalloyd** [comment]
Thanks @MarciMcGuireGCIO, we've slotted for action with consideration to the July 15th DTG.  @kelsonic slotted for this sprint, please reference above notes from @mnorthuis (July 15th DTG) and let me know what questions exist.  Thanks.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @brianalloyd !

**Comment by brianalloyd** [comment]
@Rleahy22 and @kelsonic How are we doing with this redirect request?

**Comment by Rleahy22** [comment]
@brianalloyd I merged this today and moved it to validate. I'm still learning our process, so are there other steps I need to take?

**Comment by Rleahy22** [comment]
@tskinn first, nice to meet you 👋! While testing the redirect I'm seeing a weird issue where va.gov/%5Cvaforms redirects correctly, but with the trailing slash included it does not: va.gov/%5Cvaforms/. The same problem does not exist for the second redirect I added, even though the code outside of the specific path is identical. Do you have any ideas why that might be?
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L1041-L1048

**Comment by brianalloyd** [comment]
@kelsonic is this something you could help @Rleahy22 resolve?

**Comment by kelsonic** [comment]
@brianalloyd It's not unfortunately, I think we need devops' insight into why the regex is not working for that specific redirect (https://va.gov/%5Cvaforms/) 🤔

**Comment by kelsonic** [comment]
Talked with @jbritt1, I don't think he has a hypothesis why this could be 🤔 it seems really odd

**Comment by brianalloyd** [comment]
Thanks @kelsonic appreciate you validating with @jbritt1, any idea on possible next steps?

**Comment by kelsonic** [comment]
I think we need to talk to that team site team to understand why they made a page with a %5C prefix anyways, seems like they are creating these duplicate pages on purpose 🤔

**Comment by MarciMcGuireGCIO** [comment]
@kelsonic - I'm fairly certain that @johnhashva reached out to them before we requested the redirect and didn't get any response.

**Comment by kelsonic** [comment]
I'm just worried that they're doing something on their side to make it impossible for us to implement a trailing slash redirect

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva - there are some challenges with redirecting URLs with a trailing slash.  Do you think it's worthwhile to reach back out to Kevin Reid (or whoever Kevin reports to) to see if they've modified something on their end that can be reversed?  Thanks!

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO -- Let me try getting help with this one more time.  Take a pause on this while I chase this down..

**Comment by brianalloyd** [comment]
Thanks @johnhashva for the support. Standing by in support.

**Comment by brianalloyd** [comment]
@johnhashva any update from VA Forms Stakeholder on this issue?  If not, no issue, shifting to next sprint in the event this comes into scope.

**Comment by johnhashva** [comment]
@brianalloyd go ahead and move to next sprint.  I have one more VA source to chase down for this and will do that now.   Fingers crossed.

**Comment by brianalloyd** [comment]
Closing out based on current sea state, would reopen a new ticket in future if needed.

**Comment by MarciMcGuireGCIO** [comment]
John contacted Kevin Reid at least twice to no avail trying to ask them to resolve on the VA side.

**Comment by jenniferlee-dsva** [comment]
Contacted KReid and others. KR implemented page level redirect on the weird URL page itself. Marci verified it's working at least for the root level. (legacy form detail pages still accessible. )
