### ISSUE TITLE
CT: Remove prod flag for 25982 update T&F URL

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26304]
As a developer, I need to remove the prod flag created for #25982  so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 2021-06-28.

## Acceptance Criteria
1. The functionality created in #25982   is available in production.

## Supporting Artifacts:
1. N/A

**Comment by delli-gatti-michael** [comment]
Changes are on Prod. Closing this issue
