### ISSUE TITLE
Design Feedback - Staging Review Search & Discovery-Search UI Consistency Pattern for Global Search Pages

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#26308]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- It is going to be nice to have consistent searches. 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Make the spacing above “Enter a…” and below the text box the same 
- ![Screen Shot 2021-06-21 at 4.41.30 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/eecb0573-a2b3-40b0-9e31-00544577d42b)
- Make the spacing between the clickable and non clickable titles.
- ![Screen Shot 2021-06-21 at 4.40.29 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/f1884e0f-f582-46f1-b596-10d8293a0c5d)

**Should:**
- Remove horizontal rule between H1 and gray box (it is not on the other searches)
- ![Screen Shot 2021-06-18 at 1.37.31 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/5a3e7512-8638-48a5-a8f8-06ee259a769b)

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by denisecoveyduc** [comment]
@brianalloyd @MarciMcGuireGCIO  This is  UI Consistency feedback we have received for both Resources and Support (horizontal rule) and Find a Form (Spacing).  Passing it to your teams but please let me know if we can help in any way.

**Comment by zacharymorel** [comment]
We can through this one our next sprint? I'll create a user story that points so we can _track the work_ on our end without using this user story that we share.

**Comment by MarciMcGuireGCIO** [comment]
This is now complete
