### ISSUE TITLE
CT: Remove prod flag for 24373 update VRRAP Indicator

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26303]
As a developer, I need to remove the prod flag created for #24373  so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 2021-06-28.

## Acceptance Criteria
1. The functionality created in #24373   is available in production.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17706

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
