### ISSUE TITLE
CT Redesign: Update profile page header content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26302]
As a developer, I need to create the new header for the profile page so that the page is in place for further development and it can be usability tested.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The section content outside of the header is outside of scope for this story.
3. The number mockup next to the Institution size in the prototype is out of scope of this story.
4. AC2E & AC2E do not currently have sections on the profile page and as a result are not displayed, they are included for technical implementation.

## Acceptance Criteria
1. The header contains:
    a. An "On this page" section that contains jump-links to each section of the page
    b. A card view of the institution details.

2. The following jump links in the "On this page" section are displayed if the institution has data for that section:
    a. Calculate your Benefits
    b. Ratings
    c. School locations
    d. Academics
    e. Student Body & Campus Life
    f. Contact Information

3. The card view of the institution details displays the following information:
    a. Institution type header with specialized mission (if applicable)
    b. Institution name
    c. Institution City and State (ex. Chicago, IL)
    d. Ratings Visual Indicator
    e. Ratings calculated amount (ex. 4.5 of 5)
    f. Ratings jump link specifying number of ratings (ex. See 50 ratings by Veterans)
    g. Number of GI Bill Students at an institution
    h. Program Length
    i. Institution Size
    j. Institution Type (ex. Private, public, etc)
    k. City Type (ex. Small, Medium, Large, etc)
    l. Accreditation Type (ex. National, Regional, etc)
    m. Institution URL
    n. The ability to add institution to compare drawer

4. If the institution has a specialized mission as specified in AC3a the following content is included in the header:
    a. Men-only OR Women-only (for Single-gender school)
    b. Specific Religion data for (Religious affiliation) (e.g. "Catholic", "Baptist")
    c. "Historically Black College or University" for HBCU data

## Technical Note:
- The header is a component, so a new component can be created to replace the existing component.

## Supporting Artifacts:
1. [Protoype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens/296060596_Profile__-_no_Caution_Flag)

**Comment by elder-joseph** [comment]
At the time of implementing this story, we do not have the updated sections `Academics` or `Student Body & Campus Life` so those links wont be able to be displayed until those sections are implemented.

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17679

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1967&group_by=cases:section_id&group_order=asc
