### ISSUE TITLE
Access for [Kevin Cranmer]

### ISSUE THREAD

**Issue by KevinCranmer** [department-of-veterans-affairs/va.gov-team#26312]
Please provide your Contracting Officer's Representative (COR) name.
Michael Lovejoy michael.lovejoy@libertyits.com

Please provide your name.
Kevin Cranmer

Please Provide your email.
kevin.cranmer@libertyits.com

Please provide the name of your team, your role on that team, and the name of the company you work for.
Team Name = Matsumoto
Company = Libertyits
Role =Ruby Developer

Requesting SSH key authorization?
YES

What is your public SSH key? If you don't have a SSH Key or know how to find it [click here]ssh-ed25519
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCq7k9zIxZvIcMjzswMnJQGEKDXOmYoiIV7/9aCu+/mHpTPXw/XnWkFNQZcS+oLK9BW6rh5Sw9ISQR4x9S6XAEHKletSEvanvJexB6TtRv4aZ7OS4wB79nKupwPHL0Qv7KmV/cPsdFqt+ngt3TBdro3TxylO6ixPIwfmrCsahfwnnynHicKkP9lHF7uh40Qm2f+9jvX2eJ/LFqLXcwmAplzxolJfLjHJS/3qAVKfYBzZI+TPNl3oWlBeYyOQ4EYTENVgrUxtrbzCseSfEZG0IseX1nA9mabou+mPlSn13xvQV/Ab+NUF4l/ufXrtIJsFwttXJctZMr6Ax6xiTjyc78C61/ylH0HDvr56skxG34t+pp+jqv5i1bgWd4BeJPbUGlpdTJYkVapa/UHQ0atZ5K67c1Dmxg18N6QaPEzynScVbLgfRkB8twsR5CfaUmlXVaLC0hVuAHPSwbSrDzvQZN30defwn4Ab30BsyTOQvap7yIjRgha7FMf7ElEZpdVwDc= AzureAD+KevinCranmer@DESKTOP-4NF76QS

Grant AWS Console access?
YES
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

**Comment by mydesignrocks** [comment]
socks access is granted. Please review this tools document and reach out if you have any questions/concerns:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - please review for AWS access.

**Comment by drorva** [comment]
Sorry for the delayed response.
The CORS should be a VA employee, so michael.lovejoy@libertyits.com is probably not your CORS.

**Comment by KevinCranmer** [comment]
> Sorry for the delayed response.
> The CORS should be a VA employee, so [michael.lovejoy@libertyits.com](mailto:michael.lovejoy@libertyits.com) is probably not your CORS.

michael.lovejoy@va.gov is his VA email. He's been serving as my CORS for my onboarding.

**Comment by drorva** [comment]
Can you please check with your PM and find out who is your CORS?

**Comment by KevinCranmer** [comment]
Oh shoot. Michael is my Point of Contact...
Actual COR: 
Cecilia Lee
Cecilia.Lee@va.gov

**Comment by KevinCranmer** [comment]
@drorva @mchelen Hoping to get this moving along as I'm getting assigned tickets that require me to have prod access. Thanks!!

**Comment by drorva** [comment]
Sent to CORS for confirmation.

**Comment by drorva** [comment]
@mydesignrocks approved

**Comment by mchelen-gov** [comment]
@mydesignrocks is this complete?

**Comment by mydesignrocks** [comment]
AWS access granted and initial password with steps to login has been communicated over DM
