### ISSUE TITLE
Access for Fernando Boza

### ISSUE THREAD

**Issue by FernandoBoza** [department-of-veterans-affairs/va.gov-team#26314]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   Laura Ross
- Please provide your name.
   Fernando Boza
- Please Provide your email.
   fernando.boza@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   My Education Benefits Team: Full-stack Developer: Accenture Federal Services

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJBtJ4wa6zwX7+XFd5G7zJj/lkmkxoOJVYYJ7tw+IcstbVXjm6Er78A9Esg4ntZJrTunSZAUNenYo2RCCjSzAmZXxpjX7+YEx4RlB9R2AnkOI331LIvrbL7sjkMgFFYB3A649sQrHwCmgpZmro6Ih/oa1VbQibXJpSSxUTURARajeq2k3WpE4+CJEhtomrs1WRxo3+wwbuqdG9C9ncUwkNpKcXSJcAe8O/wKyQToo02gd6eP7ZEN6eJiNMo8RyU8jqgfsqiNd9VuQTbKqIZb+UYZysd9BkroYWha+ODeVlaGS1RJekrFoyPFP52paHH964y0Yw4FhXqqU0jJcDvyzv7of/pp16jQe4C17KB3mfPv1+KMB1jmRf1EGHGDLpj0Hg3B6kaFCOCIJarCBYAR/c6+O1kGF2aUsO7eXoj/QI3oR94rKGK0sslfgjjZZ0y5BdifMBBILCnS9AIf0/j327mHPj+dy4S22K9zz1tmcsxuuzldvxCU24xuRdL6UitVBnZ4U= fernando.boza@AFSMWTOK79M4FIQ
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by mydesignrocks** [comment]
access is granted. Please review this tools document and reach out if you have any questions/concerns:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox
