### ISSUE TITLE
10203 Form: SCO email missing content

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#26316]
When a user who is attending school applies for the STEM scholarship, the SCO at their school is sent an email notifying them. Some of the content from that email is currently missing.

### Steps to reproduce (On Staging)
1. Add your own email to the SCO GIDS file for College of Charleston, Upload the file, and generate and publish a new version.
2. Using user 226, apply for the STEM scholarship
3. Open the SCO email once it is received

#### The highlighted content below is missing from the SCO email and should be added back:

![Screen Shot 2021-06-21 at 10.01.07 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f3e8ad32-b395-4e7f-951f-86136cca2cc5)

### Supporting artifacts
[Content document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f225eff42c572b9786a8fd9300cdfa4457b13cee/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-email.md#if-the-applicant-is-a-teaching-certificate-candidate)

**Comment by ksantiagoBAH** [comment]
related story https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25972

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
testing complete
