### ISSUE TITLE
Form 526 file upload job 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#26326]
# Problem part 1 
It looks like Form 526 file uploads aren't working.
[graphana](http://grafana.vfs.va.gov/d/000000066/form-526-disability-compensation?viewPanel=19&orgId=1&from=now-7d&to=now)
[new events in Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/40547/?project=3&query=user%3Aid%3A038fcdc15ef1417dbe9f32e22ec3ee53&statsPeriod=14d)

We're not seing successful file uploads:
<img width="1516" alt="Screen Shot 2021-06-21 at 10 21 45 AM" src="https://user-images.githubusercontent.com/19188/122786580-737bb280-d282-11eb-8730-18b871a252a7.png">

# Problem part 2

But something else is off that I think is not an EVSS problem.  Either our stats are wrong OR somehting is problematic with Sidekiq and retries. 

We're still enqueing around the same number of jobs, but it doesn't look like they're getting dequeued. At the same time, the error stats are nonexistant. 
<img width="1507" alt="Screen Shot 2021-06-21 at 11 12 35 AM" src="https://user-images.githubusercontent.com/19188/122786097-f18b8980-d281-11eb-8b01-2ce8ac5ecbf8.png">
<img width="1507" alt="Screen Shot 2021-06-21 at 11 13 06 AM" src="https://user-images.githubusercontent.com/19188/122786096-f0f2f300-d281-11eb-936f-700e432a79d9.png">

**Comment by annaswims** [comment]
I think the problem is that https://github.com/department-of-veterans-affairs/vets-api/pull/7198/files#r655514684  caused http://sentry.vfs.va.gov/organizations/vsp/issues/40527/?project=3&query=transaction%3ASidekiq&statsPeriod=14d. 

Root cause: sidekiq upgrade

**Comment by jeff2d2** [comment]
@annaswims the Sidekiq fix is merged. I'm not sure if this solves this whole ticket or not (it seemed like there may be other issues at hand).

**Comment by annaswims** [comment]
Thank you! @jeff2d2.  The next steps for me are to understand if this bug caused stats to fail or the whole job.

**Comment by jeff2d2** [comment]
BE Tools ticket for the Sidekiq bug: #26348

**Comment by annaswims** [comment]
I requeued upload jobs

```
results = []
delay = 0
batch_set = Sidekiq::BatchSet.new
batch_set.each do |status|
  begin
    submission_id = status.callbacks["success"].first["Form526Submission#workflow_complete_handler"]["submission_id"] 
    first_name = status.callbacks["success"].first["Form526Submission#workflow_complete_handler"]["first_name"] 
  rescue 
    submission_id = nil
  end
  next unless submission_id && status.created_at < "2021-06-21T19:03:22Z" && status.created_at > "2021-06-16T14:03:22Z"
  uploads = Form526Submission.find(submission_id).form['form526_uploads']
  next unless uploads.present?
  jids = status.jids
  new_batch = Sidekiq::Batch.new
  new_batch.on(
      :success,
      'Form526Submission#perform_ancillary_jobs_handler',
      'submission_id' => submission_id,
      'first_name' => first_name
  )
  new_batch.jobs do
    uploads.each do |upload|
      EVSS::DisabilityCompensationForm::SubmitUploads.perform_in(delay, submission_id, [upload])
      delay += 10.seconds
    end
  end

  old_batch = Sidekiq::Batch.new(status.bid)
  old_batch.status.delete

  results << {submission_id: submission_id, stuck_count: jids.count, upload_count: uploads.count, old_batch: status.bid, new_batch: new_batch.bid }
end
```
