### ISSUE TITLE
Attachment Copy Update

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26324]
## User Story
As a user, I want to be notified that I cannot save attachments in drafts so that I know what to expect when I save a draft. 

## Acceptance Criteria
* Copy is updated on the Attachments screen to display "Attachments are not saved in drafts."

## Design
![Select File@2x (1).png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/ea1e5bfa-e28f-4430-82fc-38862c1a3906)

**Comment by digitalken** [comment]
PASS 7/15/2021 - Looks good on iOS and Android.  Closing.
