### ISSUE TITLE
Access for Khansa Ayari Hammami

### ISSUE THREAD

**Issue by khansahammami** [department-of-veterans-affairs/va.gov-team#26328]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Laura Ross
- Please provide your name.
   > Khansa Ayari Hammami
- Please Provide your email.
   > khansa.ayari.hammami@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > this adds context

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQCbaE9tg4HJyRGynmvzKJQSolApUyObtR3hshFrm8+N/jJvhAc95N2yvMS3/P8aNYY/fdVRIuElDYmSkU/KMqnsTVaTSDosG51hLTaXafPuX4k6mdEMyEWvRiNV1TAqxeOF1qtFqYw5hlUTEYMsuhKPnQPVt+LHnhMS0v2RpAVx+RC82hFTvTYrBQnfjZ94RPOnzJVJzYOKOL6RJdqd0EvOJgevdeoQfILWYTMB9wYilvr3Hx1U8IPW/0qjwLWk/x+sQeKevWI7DzPYVjXuzStjUkfbEnl4Tw2LgjG0gS8vYx8i/PBziyytPTkgj6zWFRC5yNDZG4GtSpA1iS/Or8gYqtXXm2bqQzGlOAI0vLEcctGeP+xVDOnxrpGMVL+GQjeuNy1pKli9F/47ilPUCNNwIpSjYLH6j/S1o2hdpMWSRdEr4LS2Jo/+MJq/07n0Ubi5CwfKZP1YiC3m1zPmn/sPjPN7kWR/kTPOmYr+HmZHfnczjtJefIowCNBRlVocpFE= khansa.ayari.hammami@AFSMWDQ6N7VX2KQ
```

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why?

**Comment by mydesignrocks** [comment]
access is granted. Please review this tools document and reach out if you have any questions/concerns:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

**Comment by khansahammami** [comment]
Hi 
I am not able to connect to socks I used this ssh socks -D 2001 -N and I got an error .Unable to negotiate with  port: no matching MAC found. can you please help me ?
Thank you

**Comment by mydesignrocks** [comment]
@khansahammami 
This key will not work with a double space between ssh-rsa and AAAAB3N..
can you look at your key again and attach it here, please.

**Comment by khansahammami** [comment]
here is my public key
![Screen Shot 2021-06-22 at 12 10 30 PM](https://user-images.githubusercontent.com/84814036/122962111-13087600-d353-11eb-9108-ffce5af6cb14.png)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbaE9tg4HJyRGynmvzKJQSolApUyObtR3hshFrm8+N/jJvhAc95N2yvMS3/P8aNYY/fdVRIuElDYmSkU/KMqnsTVaTSDosG51hLTaXafPuX4k6mdEMyEWvRiNV1TAqxeOF1qtFqYw5hlUTEYMsuhKPnQPVt+LHnhMS0v2RpAVx+RC82hFTvTYrBQnfjZ94RPOnzJVJzYOKOL6RJdqd0EvOJgevdeoQfILWYTMB9wYilvr3Hx1U8IPW/0qjwLWk/x+sQeKevWI7DzPYVjXuzStjUkfbEnl4Tw2LgjG0gS8vYx8i/PBziyytPTkgj6zWFRC5yNDZG4GtSpA1iS/Or8gYqtXXm2bqQzGlOAI0vLEcctGeP+xVDOnxrpGMVL+GQjeuNy1pKli9F/47ilPUCNNwIpSjYLH6j/S1o2hdpMWSRdEr4LS2Jo/+MJq/07n0Ubi5CwfKZP1YiC3m1zPmn/sPjPN7kWR/kTPOmYr+HmZHfnczjtJefIowCNBRlVocpFE= khansa.ayari.hammami@AFSMWDQ6N7VX2KQ

**Comment by mydesignrocks** [comment]
The key provided looks better and added that now @khansahammami - can you try your access.

**Comment by khansahammami** [comment]
I got the same error

**Comment by mydesignrocks** [comment]
@khansahammami - wondering if you were able to get through "Configure the SOCKS proxy" step? 
And please reach out to me on slack to review this further...

**Comment by khansahammami** [comment]
I have done all the steps to configure Socks proxy . I will ping you on slack

**Comment by mydesignrocks** [comment]
provided the necessary troubleshooting and asked the user to reach out on slack support for further assistance. Requested keys are looking right and added, closing.
