### ISSUE TITLE
Document estimation & WIP limit

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26321]
## Tasks

- [ ] Define and [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/team/charter.md#estimation) ticket estimation technique and scale (complexity, t-shirt LOE, etc)

- [ ] Define work in progress limit for Code Review pipeline

Due by EOB 6/22

**Comment by laurenernest** [comment]
Thanks for the estimation details! Is there a WIP limit for Code Review you'd like to start with?

**Comment by jbalboni** [comment]
I'm not sure if we necessarily need one? I'm curious if @grossb1 has thoughts. I think having expectations around when a ticket gets reviewed and how long it should be in review would make more sense to me.

**Comment by laurenernest** [comment]
Makes sense!
