### ISSUE TITLE
Cancel Confirmation

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26333]
## User Story
As a user, when I tap 'Cancel' when composing/replying/editing a message, I want to see a confirmation screen to make sure I'm taking the intended action. 

## Acceptance Criteria
* When a user taps 'Cancel', the user is directed to a cancel confirmation screen
* The user has the option to 1) Save Draft or 2) Discard
* If the user selects 'Save Draft'
     * The message/edits are saved in the user's Draft folder
     * The user is directed to their drafts folder with the [success message ](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26336)
* If the user selects 'Discard' 
    * The message/edits are not saved
    * The user is directed to the screen they were on before composing/replying/editing
* H1 Headers
   * If the user is composing a new message, 'Compose' should display as the H1 header
   * If the user is replying to an existing message thread, 'Reply' should display as the H1 header
   * If the user is editing a draft message, 'Edit Draft' should display as the H1 header
* Button Treatment
   * 'Discard' is treated as the primary button and 'Save Draft' as a secondary. 

## Accessibility Guidelines
* Mark 'Save Draft?' as an H2

**Discard**
Title= "Discard"
accessibilityHint= "Cancels your message"
accessibilityRole= "Button"

**Save Draft**
Title= "Save Draft"
accessibilityHint= "Saves message to your draft folder"
accessibilityRole= "Button"
## Design
![Cancel Draft (1).png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/6ddad463-7643-436e-bd9e-9404a10a6ef6)

**Comment by ashley-matthews** [comment]
@melissa-lefevre - can you confirm the expected behavior once folks hit save or discard?

**Comment by melissa-lefevre** [comment]
Save draft: takes the user to the "success draft saved" page
Discard: takes the user back to where they were before selecting
"compose message"

**Comment by digitalken** [comment]
PASS 7/28/2021 - Looks good on Android and iOS.  Minor text bug logged.  Closing.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/28013
