### ISSUE TITLE
Research Eggplant and Add it to the Visual Testing Tools Summary Document

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#26331]
## Issue Description
Research Eggplant as a solution for Visual Regression Testing and add it to this [Visual Testing Tools Summary Document](https://docs.google.com/spreadsheets/d/1QKC0d31lARWY83vztyQXTY0pA1mZkjSqVkILQfraHl4/edit#gid=758931068).

**Comment by holdenhinkle** [comment]
Some links:

- Eggplant website - https://www.eggplantsoftware.com/
- Eggplant Digital Automated Intelligence - https://www.eggplantsoftware.com/digital-automation-intelligence
- Eggplant Artificial Intelligence - https://www.eggplantsoftware.com/artificial-intelligence
- Short Slack convo about Eggplant - https://dsva.slack.com/archives/C01CHAY3ULR/p1623874981124800

**Comment by holdenhinkle** [comment]
After reviewing Eggplant's website, watching some videos, etc., the video on this page finally gave me some understanding of how Eggplant works - http://docs.eggplantsoftware.com/ePF/gettingstarted/epf-getting-started-eggplant-functional.htm

Eggplant has a scripting language called SenseTalk. By interacting with Eggplant's 'Functional' UI and using SenseTalk, users can define interactions on a page to test. I think this can include looking for images.

---

Here's the section on working with images - http://docs.eggplantsoftware.com/ePF/using/epf-capturing-images.htm

---

Visual regression docs search results - http://docs.eggplantsoftware.com/en-us/search/results.htm#stq=visual%20regression&stp=1&facets%5Bpage%5D%5B%5D=category_name

No mention of visual regression.

---

The is the only relevant search result for 'eggplant visual regression' on Google - https://blog.eggplantsoftware.com/topic/visual-regression-testing

It's an Eggplant blog post titled "Automated Visual Testing: An Essential Component of Modern Testing". It doesn't mention "visual regression testing", only "visual testing", and it give very little information about how Eggplant performs "visual testing".

**Comment by holdenhinkle** [comment]
Peter and I reviewed Eggplant together. It's clear from our research that Eggplant isn't a Visual Regression Tool that can easily be implemented like Percy is. It's not even clear if Eggplant is good at detecting differences between images.

We don't recommend using Eggplant as a visual regression tool.

**Comment by pjhill** [comment]
Agreed -- Eggplant doesn't seem like the way to go at this point. It would be very disruptive to implement Eggplant on the Platform as it seems to be an entire ecosystem of test tooling and processes.
