### ISSUE TITLE
NoMethodError when calling id_theft_flag when validating mobile users

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#26341]
For a small percentage of user validation attempts the user object is nil.

http://sentry.vfs.va.gov/organizations/vsp/issues/40520/?environment=staging&project=3&query=is%3Aunresolved

**Comment by patrickvinograd** [comment]
Saw your PR for this...I suppose it's also possible that IAMSessionManager is building a non-nil user, but the User.find in the worker is not finding it...because it's not getting saved, or something? More data will tell I guess.

**Comment by patrickvinograd** [comment]
I know there were issues where the user entry in redis would time out for various jobs when those jobs were being retried over sidekiq's default retry interval...but we don't have that issue with the claims and appts jobs which don't retry.

Now that there is logging of the uuid when session is established, it could be fruitful to do a check for User.find == nil in the workers, and log the UUID there to match things up time-wise.
