### ISSUE TITLE
CT Redesign: Usability updates for search functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26343]
As a developer, I need to update the search mechanisms in the comparison tool redesign sandbox based on the usability test session feedback, so that the users of the new tool have a more intuitive and user friendly experience.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. AC4 uses the same style and layout as the current comparison tool error message.

## Acceptance Criteria:
1. Pagination is displayed with the "Search by name" results:
    a. When the number of total results is > 10.
    b. Using the DEPO component in SA1.
    c. The component is centered underneath the location "cards".
    d. The page size is 10.

2. The default "Search by location" radius is 25 miles.

3. The "Search by location" distance dropdown menu includes an option of "within 15 miles".

4. When there is a technical error that would cause an infinite loading search results spinner for name search:
    a. The "Update tuition and housing estimates" component is not displayed.
    b. The "Refine your search" component is not displayed.
    c. The error message below is displayed beneath the search control:
  
    > **The GI Bill Comparison Tool isn’t working right now**
    > We're sorry. Something went wrong on our end. Please refresh this page or try searching again. 

    d. The error message is cleared from the name search view on execution of a new name search.

5. When there is a technical error that would cause an infinite loading search results spinner for location search:
    a. The "Update tuition and housing estimates" component is not displayed.
    b. The "Refine your search" component is not displayed.
    c. The map component is not displayed.
    d. The error message below is displayed beneath the search control:
  
    > **The GI Bill Comparison Tool isn’t working right now**
    > We're sorry. Something went wrong on our end. Please refresh this page or try searching again. 

    e. The error message is cleared from the location search view on execution of a new location search.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222691/296060312/preview)
2. [Pagination Component](https://design.va.gov/components/pagination)
3. Warning Alert Style for AC4 https://design.va.gov/components/alertboxes#warning-alert
4. Mockup of error message for AC4/AC5
<img width="894" alt="Screen Shot 2021-06-29 at 10 22 45 AM" src="https://user-images.githubusercontent.com/48260534/123814805-fd9bca80-d8c3-11eb-9ca9-d6dfb4f87b3a.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17720

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail Test run](https://dsvavsp.testrail.io/index.php?/runs/view/1969)
