### ISSUE TITLE
Content Feedback - Midpoint review - Health Care Experience  Check-in MVP

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#26344]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

**Comment by peggygannon** [comment]
sitewide content support tix: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25221#issuecomment-848041375

**Comment by peggygannon** [comment]
@kristenmcconnell  Platform content feedback for Check in MVP. Please let me know if you have any questions. Thx. 

**Consider**

1. If a user clicks "Yes" to updating info, the next screen says “Check in with a staff member"  
Consider adding an explanation or some content explaining why they can’t check in online. (b/c they need to update  their info), so this doesn’t confuse users who think they're checking in online. 


2. It took me little bit to understand that the headers above the blue rule on each screen relate to the content below the rule. (This could be because I’m used to seeing *Need help?* information in this location.) But maybe something to watch for in testing if this is also unclear to users.

**Comment by kristenmcconnell** [comment]
**For the consider items:**
1. We incorporated this feedback into our changes for MVP. Here is what we landed on: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/dlbYq5L
2. The team discussed this (I also reviewed with Danielle) and we decided to keep this as is, because it is a standard component. It tested well with users. No confusion about that section.

**Comment by kristenmcconnell** [comment]
@jparker0425 I commented back and closed out this story. Don't know how you want to count it in the sprint report, etc.
