### ISSUE TITLE
DISCOVERY | CMS Sandbox | Translation Recommendations 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#26358]
## User Story

As a product manager on the C&L Team,  I would like to stand-up a CMS sandbox that can be used to test technical solutions that will help us  support multi-language content on the VA.gov website and automate translation workflows. 

## CMS Sandbox Info:

- CMS URL: https://localization-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/
- Web: https://web-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/
- Tugboat page for refreshing with the latest content: https://tugboat.vfs.va.gov/60d1020d4fa3231be8d58007
- Documentation in the CMS help center with a Tugboat training video and some common how-tos: https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments

## Acceptance Criteria

- [ ] CMS sandbox set up with links to builds that generate a new front-end whenever edits are made
- [ ] Video and documentation of process attached to this ticket

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - lmk if this reads ok and point when you have a better idea of time needed to set this up :)

Thanks,

Sharon

**Comment by youngfreezyVA** [comment]
hi, the piece about "able to support integration testing with an API" doesn't really mean anything at this point, and i don't recall us discussing those specifics in standup.  i suggest removing that piece from the AC and creating a new ticket for different API integrations.

**Comment by SKasimow** [comment]
@Yuffster-usds Hi Michelle - please review and provide any additional req's or comments. Thanks!

**Comment by SKasimow** [comment]
@youngfreezyVA Can we close this one out now?

**Comment by youngfreezyVA** [comment]
setup is pretty self explanatory.

CMS URL: https://localization-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/
Web: https://web-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/
Tugboat page for refreshing with the latest content: https://tugboat.vfs.va.gov/60d1020d4fa3231be8d58007
Tugboat docs: https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments (I doubt you'll need them)

once you have the proper access, to test, go to: 


-

1.  find the coronavirus FAQ page.
2.  click the edit tab
3.  make test edits, then save as "Published"
4. In tugboat: actions -> refresh to fetch the latest content. you may also need to build from the master branch (at  https://cms-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/admin/content/deploy)
5. navigate to: https://web-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/coronavirus-veteran-frequently-asked-questions/


You will see the build status of the page on the far right in the demo CMS, as well as at:

 https://cms-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/admin/content/deploy (choose master branch)

**Comment by youngfreezyVA** [comment]
Slack thread here, re: leveraging sandbox for Other languages discovery ticket: 
https://dsva.slack.com/archives/CDHBKAL9W/p1624646580228600?thread_ts=1624295708.189700&cid=CDHBKAL9W
