### ISSUE TITLE
Publish Cypress Mochawesome report with failed videos

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#26366]
## Description
Publish Cypress Mochawesome report HTML reports with video playback.

Ideally, publish the reports in GHA for easy reference.

## Tasks
- [x] Publish Cypress Mochawesome HTML Reports with Video Playback in GitHub Actions

**Comment by pjhill** [comment]
This effort was duplicated under the GHA pipeline efforts. Closing this!
