### ISSUE TITLE
Create Presentation About Testing Tools Team Dashboard for VSP Demo

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#26369]
Notes - https://docs.google.com/document/d/1W5CWrNC5_P-RFG5PygNk2QdIgqnP9cKnCXzOPMNtUg0/edit?usp=sharing

Slideshow - https://docs.google.com/presentation/d/1OUa1Rk6-O_cFU57iJvjHaW_wnyGD9RFBGgGN3eyDPHY/edit?usp=sharing

**Comment by holdenhinkle** [comment]
This is done.

**Comment by pjhill** [comment]
Hooray -- good job!
