### ISSUE TITLE
Refactor code that parses Direct Deposit save errors

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#2636]
As described here https://github.com/department-of-veterans-affairs/vets-website/pull/10930#discussion_r337240086

I also noticed that the code needs to be more precise. It needs to make sure that the searched-for key and text are part of the _same_ error message; as it stands it only checks to see if there's a message that has a given key and a message that contains a given text string. Hypothetically it could throw a false positive.

Will also need to put in plenty of test coverage as well.

**Comment by Justin-Pickett** [comment]
@bradl3yC can we move this ticket to validate?

**Comment by erikphansen** [comment]
@Justin-Pickett the PR hasn't been merged yet

**Comment by Justin-Pickett** [comment]
@erikphansen okay thanks.

**Comment by Justin-Pickett** [comment]
Ticket can be closed.
