### ISSUE TITLE
[Bug Research] My VA:  Get your lab and test results

### ISSUE THREAD

**Issue by tmitchellgcio** [department-of-veterans-affairs/va.gov-team#26365]
On my profile, I don't believe I should have VA Healthcare as I don't qualify for it. Anyways, Health care is showing up and when you click on `Get your lab and test results` it errors out and gives you the message shown in the screenshot below. It also happens with `Download my data`

![8FC308CC-711E-4D08-96E7-486D9215FCB7_1_201_a](https://user-images.githubusercontent.com/84803567/122817280-b56a2000-d2a5-11eb-9ac3-c1443ea42eda.jpeg)

**Comment by ajakabcin** [comment]
Closing this issue - further investigation and any action we need to take will be tracked in #26603
