### ISSUE TITLE
Recheck Info Alert

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26363]
## User Story
As a user, I want to see an alert nudging me to complete required fields if they are not filled so that I can save a draft message. 

## Acceptance Criteria
* When a user taps 'Save', but does not have all the required fields filled, an error message displays at the top of the form. 

## Accessibiltiy Guidelines
* indicate 'Recheck Information' as an H2

## Design
![Recheck info alert.png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/1c00a6c1-0208-4c5a-b67c-5200ac979839)

**Comment by digitalken** [comment]
PASS 7/16/2021 - Looks good on both iOS and Android.  Closing.
