### ISSUE TITLE
Review Instances / Environemtns - Ability to issue SSL certificates for *vfs.va.gov

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26373]
## Description
To support review environments, and other developers tools and resources, we need the ability to issue certs for *.vfs.va.gov. For example, this would enable us to protect Jenkins, Grafana, and Review instances with an SSL cert, among others. 

## Background/context/resources
CMS has done this before, so we can reach out to Eric Oliver to understand the process. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] Follow through with process to be granted this ability from the VA 

## Definition of Done
- [ ] We will be able to issue certs for <subdomain>.vfs.va.gov

**Comment by jhouse-solvd** [comment]
@olivereri - Can you share any notes or docs regarding the process for ability to issue certs for *.vfs.va.gov. (see description for add'l details)

**Comment by olivereri** [comment]
Certainly! @ElijahLynn created these documents;

Gaining Access to Venafi self-service certificate portal:
https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates

Creating certificates in Venafi self-service certificate portal:
https://vfs.atlassian.net/wiki/spaces/OT/pages/1787953328/Venafi+Create+and+download+TLS+certificates

**Comment by dginther** [comment]
Verified that Jeremy Britt has this ability. Others on the team can follow the documentation as well.
