### ISSUE TITLE
Update FOIA + Privacy footer links

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2637]
## What happened?

1/ On this page, called **Privacy, policies, and legal information** https://www.va.gov/privacy-policy/  
- The  Freedom of Information Act (FOIA) link on the page is currently pointing to a 404. It should point to their new URL: https://www.va.gov/foia

Screenshot:
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/d60a195c-9460-4322-9a9d-5863ac6d6cee)

## Specs:
N/A

## Acceptance Criteria
- [x] Links point to the correct URLs. See above in Description. 

@Karak888 - Sorry; I think this bug originated with me mixing up FOIA with privacy office back in September. 

The footer may have gotten migrated into Drupal, but I"m not 100 sure. CCing Randi here in case it needs  Drupal access.

**Comment by jenniferlee-dsva** [comment]
WAIT - please hold.

**Comment by jenniferlee-dsva** [comment]
Okay, updated. @Karak888 @RLHecht

**Comment by RLHecht** [comment]
Link updated in Drupal. @peggygannon Can you please review and then publish?

**Comment by Karak888** [comment]
oh wow didn't know footer was in Drupal yet, cool!  So @peggygannon please just let me know when you have reviewed and updated so I can close out on my end.  Thanks!!

**Comment by RLHecht** [comment]
@Karak888 This change was not in the footer. It was just linked to on the page, so I put in the new URL that was listed above. I think that's all that needed to be done, @jenniferlee-dsva ?

**Comment by Karak888** [comment]
you are correct @RLHecht, thanks I was jumping the gun!

**Comment by jenniferlee-dsva** [comment]
>I think that's all that needed to be done, @jenniferlee-dsva ?

Yes, thank you, Randi!

**Comment by RLHecht** [comment]
@jenniferlee-dsva I saved as a draft and it needs to be published. I asked Peggy in a comment above but if you want to set to publish that would be great and it will be in for tomorrow's deploy.

**Comment by RLHecht** [comment]
@Karak888 Jen reviewed and published this last night. I'll validate this afternoon after the Drupal deploy.

**Comment by Karak888** [comment]
Thank you Randi!!

**Comment by RLHecht** [comment]
@Karak888 this has been validated on the live site. Closing this issue.
