### ISSUE TITLE
Add E2E test for images on VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26370]
## Issue description
The build will break if required images are missing

## Tasks
Add E2E to confirm required images are displayed properly on VAMC system home page
confirm the image is loaded (check width/height)

## Acceptance Criteria
- [ ] Tests are in place to confirm the presence of required images

**Comment by mpelzsherman** [comment]
The best way to do this that I'm aware of is documented [here](https://stackoverflow.com/questions/51246606/test-loading-of-image-in-cypress):

```js
    cy.get('...')
      .should('be.visible')
      .and($img => {
        // "naturalWidth" and "naturalHeight" are set when the image loads
        expect($img[0].naturalWidth).to.be.greaterThan(0);
      });
```
