### ISSUE TITLE
CT Redesign: Location Tab  - Update from Testing	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26394]
Location Tab interactivity is designed & included in prototype	

* Refine the UI for the "Search by location" tab so it's clear that the tab is clickable when it's not active 
* Ensure this is in prototype so behavior is clear

**Comment by amyknox** [comment]
@watersemma 
- when you get a chance could you add the improvement you made in the location search screens to the Name search screens? 

https://bahdigital.invisionapp.com/share/EJIAH5RM6ZY

If that update is in and I'm missing it, share here & tag me.  TIA!
