### ISSUE TITLE
CT Redesign: Profile Testing - Research Plan	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26405]
Research plan is written, reviewed & updated	

Draft initial research plan Review w UX Team Update based on feedback

**Comment by JenLJ** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usabilitytesting-july2021/research-plan.md
