### ISSUE TITLE
CT Redesign: Profile Testing - Discussion Guide	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26406]
Discussion guide is written, reviewed & updated	

Create interview discussion guide (with streamlined tasks)  
Coordinate with prototype designer to align scenarios. 
Review with UX team 
Update based on feedback

**Comment by JenLJ** [comment]
Discussion guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usabilitytesting-july2021/discussion-guide.md
