### ISSUE TITLE
CT: Make VRRAP Indicator a Learn More Link

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26407]
As a comparison tool user, I need the ability to learn more about the VRRAP program when viewing an institution profile page so that I can familiarize myself with it and it's benefits if I am not aware of the program.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. The "Veteran Rapid Retraining Assistance Program (VRRAP):" in the "Institution summary" area of the "Additional information" section is a link.
2. When the user clicks the link the following content is displayed:

    > **Veteran Rapid Retraining Assistance Program (VRRAP)**
    > The Veteran Rapid Retraining Assistance Program (VRRAP) offers education and training for high-demand jobs to Veterans who are unemployed because of the COVID-19 pandemic.
    > 
    > To learn more about this benefit and see eligibility requirements, [visit the VRRAP page](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/).

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17666

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1965&group_by=cases:section_id&group_order=asc
