### ISSUE TITLE
[vaos service appointments] Fetch booked VA appointments from VAOS service on detail pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#26409]
We should fetch booked VA appointments from the VAOS service, when the VAOS service appointments toggle is on, on the appointment detail pages.

Tasks
- Update VA appointment details page to use the VAOS service appointments fetch for a single appointment
- Create new transformer or adapt existing transformer to transform VAOS service data into Appointment structure
- Verify all data for different appointment types (in person and video) is displayed on detail pages
- Add some tests to cover the new appointment fetch

AC
- [ ] Appointment details page for VA appointments shows appropriate data fetched from VAOS service

**Comment by laurenernest** [comment]
Validation blocked by Jacqueline test user set up downstream. Closing ticket.
