### ISSUE TITLE
Create Conversation Guide (Rated Disabilities and View Dependents)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2641]
### Story  
As a design researcher, I want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users I will be communicating with.

### Task
- Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery-conversation-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
### Acceptance Criteria
- [ ] Conversation Guide has been sent to Shawna for review

**Comment by sporeboy** [comment]
The initial draft on the conversation guide is here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md

May not be able to get Shawna's OK before end-of-sprint; she is away in Toronto.

**Comment by jason-gcio** [comment]
It was sent though, correct?
