### ISSUE TITLE
Prep Tasks: Search Design Concepts Research

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#26425]
## Description
- Research ticket to draft research plan and conversation guide to support Search design research. 

##  Associated Research Study 
- Search & Discovery: Design concept research for surfacing more search tools and search landing page
- [Research Materials Folder Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search/research/user-research/2021-Aug-research-study)

## Acceptance Criteria
- [x] Draft research plan 
- [x]  Draft conversation guide
- [x] Share both with Lauryl, Denise, Megan
- [x] Incorporate all feedback 
- [x] Schedule pilots
- [x] Run pilots
- [x] Debrief pilots 
- [x] Make note-taking spreadsheet
- [x] Share research plan and conversation guide with Lauren Alexanderson for approval to launch recruiting
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Revise conversation guide
- [x] Send instructions to observers
- [x] Review recruited participant list for requirements met
- [x] Followup with Perigean re participant list
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief session(s)
- [x] Other tasks as needed

**Comment by cindymerrill** [comment]
Drafted [research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-plan.md)today and shared with Lauryl, Shawna, and the Search & Discovery team for feedback. Plan to discuss with the Search team tomorrow morning.

**Comment by cindymerrill** [comment]
Discussed research plan with the Search team and made revisions. Also drafted a screen flow diagram for the prototype to discuss with Megan hopefully tomorrow.

**Comment by denisecoveyduc** [comment]
As discussed via Slack we are shifting this over to search and discovery team for tracking purposes.  @cindymerrill let us know how we can continue to tweak the process to make it work well for you ;)

**Comment by cindymerrill** [comment]
Revised goals and tasks in the research plan, per meetings today with Denise, Megan, and John. Revised research plan can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-plan.md

Also posted to #va-sitewide-content to confirm that the wording of one task is OK, and got revised copy from Beth Potts.

**Comment by cindymerrill** [comment]
Revised research plan and started conversation guide but didn't get too far.

**Comment by cindymerrill** [comment]
Waiting to sync on search concepts to usability test in a few weeks. @denisecoveyduc

**Comment by cindymerrill** [comment]
Updated research plan per design sync meeting this week.

**Comment by denisecoveyduc** [comment]
As per meeting with @cindymerrill we will bump the completion of the conversation guide to Sprint 55 as she is synthesizing the decision tool research and then running into PTO. We will schedule the completion in Sprint 55.

**Comment by cindymerrill** [comment]
Conversation guide has been drafted and revised with feedback from Denise: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/conversation-guide.md

**Comment by cindymerrill** [comment]
Revised the newly added new prep tasks a bit, and ready to start working on them.

**Comment by cindymerrill** [comment]
Reached out via slack and email to find pilot participants.

**Comment by cindymerrill** [comment]
Ran first pilot test, debriefed with team, and decided with the team to make a few changes to the conversation guide and prototypes. Then launched recruiting with Perigean; hope to hear from Lauren tomorrow. Looking for another Veteran volunteer for pilot test #2 tomorrow or next Thursday.

**Comment by cindymerrill** [comment]
Recruiting launched with Perigean today. Will look for a second pilot participant for next Thu (Sept 9) when back from PTO on Wed Sept 8. Real sessions will start on Fri Sept 10 and run through Sept 17.

**Comment by cindymerrill** [comment]
Completed second pilot test today, as well as the rest of the prep tasks for research. The only thing I wasn't able to do was to schedule daily debrief meetings because the only available time I have is after all the sessions of the day, which is unfortunately after Eastern working hours. So I scheduled one debrief meeting for after the last research session. If we have any no-shows (as we undoubtedly will), perhaps we can use that time for a bit of team debriefing.
