### ISSUE TITLE
Past Appt Filters Not Working for Select Patients

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#26435]
1.  Log in to VAOS as John Morrison.  
2.  Select Past Appointments
Past 3 mos - works
Jan - March - works
Oct - Dec - error displays, no error in dev tools
July- Sep - error displays, no error in dev tools
All of 2021 - works
All of 2020 - error displays, no error in dev tools

1.  Log in as Ruben Moreno
2. Select Past Appts, 
Past 3 mos - error displays, no error in dev tools

Note, I tried other patients and did not have any errors;  Judy Morrision, kidys.b.quankep@id.me, kidys.b.quankep@id.me, cecil.morgan@id.me are working just fine and no errors.

**Comment by jbalboni** [comment]
Related to https://issues.mobilehealth.va.gov/browse/VAOSR-2058

On the FE, we can partially fix this by using the vvsAppointments id when the top level id doesn't exist. But this will still cause a problem when we try to fetch this appointment if someone refreshes the detail page.

**Comment by laurenernest** [comment]
@vbahinwillit @jbalboni Can we roll out the partial fix with this ticket and do a followup once https://issues.mobilehealth.va.gov/browse/VAOSR-2058 is done?
