### ISSUE TITLE
Analytics Bug | Language Assistance Pages | C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#26434]
## User Story

Opening a new ticket to look into the issue Analytics team found with 2 items on new Language and Assistance Pages (Spanish, Tagalog, Other Languages).

The 2 issues are in the table below 1) Accordion Clicks and 2) Satisfaction Score

(More details here in original ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/24408 ) 

| Interaction | Screenshot | Status |
| :------- | :-------: | :-------:|
|PDF Downloads - | ![image](https://user-images.githubusercontent.com/80417436/122802491-67e4b780-d293-11eb-84af-4cb582bb9b04.png) | 🟢 Tracking Correctly|
| Outbound Link Clicks | ![image](https://user-images.githubusercontent.com/80417436/122802775-c14ce680-d293-11eb-8c2b-44295926bfec.png) | 🟢 Tracking Correctly|
| Footer Language Assistance Links | ![image](https://user-images.githubusercontent.com/80417436/122802850-e17ca580-d293-11eb-8d4c-ac6fdf61df78.png)| 🟢 Tracking Correctly|
|`Find helpful VA phone numbers` CTA | ![image](https://user-images.githubusercontent.com/80417436/122803006-1a1c7f00-d294-11eb-8f4b-cc6b68d5bbf2.png)| 🟢 Tracking Correctly|
|Navigation List Links| ![image](https://user-images.githubusercontent.com/80417436/122803116-34eef380-d294-11eb-9bb6-32dce059f1ee.png)| 🟢 Tracking Correctly|
|Accordion clicks |![image](https://user-images.githubusercontent.com/80417436/122803283-6667bf00-d294-11eb-927e-396c6d5c815d.png)| 🟡  Accordion clicks are coming in as not set. @youngfreezyVA can you please pass nav-accordion-embedded-link-click? (GA report w/those events for reference [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=embedded/))|
|Jump Links | ![image](https://user-images.githubusercontent.com/80417436/122803370-84352400-d294-11eb-9ae2-de11a99553e3.png)| 🟢 Tracking Correctly|
|Pageviews|![image](https://user-images.githubusercontent.com/80417436/122803427-9911b780-d294-11eb-8c4b-5c5673f58c76.png)| 🟢 Tracking Correctly|
|Scroll Depth| ![image](https://user-images.githubusercontent.com/80417436/122803492-af1f7800-d294-11eb-804e-855c54014dcb.png)| 🟢 Tracking Correctly|
|Click to Call| ![image](https://user-images.githubusercontent.com/80417436/122803589-cb231980-d294-11eb-8472-241e12f73688.png)| 🟢 Tracking Correctly|
|Satisfaction Score (Good/Bad Buttons)| ![image](https://user-images.githubusercontent.com/80417436/122816305-8c955b00-d2a4-11eb-8733-479f3299de52.png)| 🟡 the `not set` portion of the interaction label should be `good` or `bad` depending on the selection, not `not-set` @youngfreezyVA do you know why this is happening? (link to page [here](https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/))|
|Search Bar| ![image](https://user-images.githubusercontent.com/80417436/122816988-6328ff00-d2a5-11eb-95df-0b0e1252448d.png)| 🟢 Tracking Correctly|

## Expected Behavior

[ ] Accordion clicks come in as set
[ ] Not set portion of label should  be Good or Bad

## Acceptance Criteria

- [ ] Analytics confirms above 2 items are set correctly for tracking

**Comment by SKasimow** [comment]
@youngfreezyVA Hi -can you take a look and point this (not urgent, can pick up when ready). Thanks!

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - were these fixed? If not, could you take a look and see if they are quick fixes you can do?

**Comment by youngfreezyVA** [comment]
Hello, can I get a screenshot of which `nav-accordion-embedded-link-click` is being referred to? Looks like i don't have access to GA at the moment.

Based on this site wide platform function, they should be coming in. perhaps it is a staging-specific issue? 

<img width="744" alt="Screen Shot 2021-06-30 at 10 06 26 AM" src="https://user-images.githubusercontent.com/46791771/124002630-d6f49700-d98a-11eb-950a-7a32f264d388.png">

**Comment by youngfreezyVA** [comment]
I'm not sure about the Satisfaction Score row... @kelsonic worked on this, maybe he can provide more context? :) 

<img width="758" alt="Screen Shot 2021-06-30 at 10 07 57 AM" src="https://user-images.githubusercontent.com/46791771/124002809-0e634380-d98b-11eb-9e37-fda5d334653b.png">

**Comment by kelsonic** [comment]
Hey @youngfreezyVA! Sorry just catching up 🙂 Is the problem that `radio-button-optionLabel` is coming in as `not set` on [this page](https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/)?

**Comment by youngfreezyVA** [comment]
yup! that is my understanding of the issue

**Comment by kelsonic** [comment]
ah ha! reproduced, thanks! 
![image](https://user-images.githubusercontent.com/12773166/124004888-b1b95600-d995-11eb-82b8-7b662cd3137d.png)

I will send up a PR for this shortly CC @brianalloyd

**Comment by kelsonic** [comment]
PR is open: https://github.com/department-of-veterans-affairs/content-build/pull/307

**Comment by kelsonic** [comment]
PR merged, the option label will be fixed following today's daily deploy (eta 30 min?) 🙂

**Comment by laurensimpson14** [comment]
The radio button is now working correctly and passing in `good` and `bad` as the value - Thanks @kelsonic!
| Interaction | Screenshot | Status |
| :------- | :-------: | :-------:|
|Satisfaction Score (Good/Bad Buttons)| ![image](https://user-images.githubusercontent.com/80417436/124311703-c0d60a80-db33-11eb-895c-a9440dafdd1b.png)| 🟢 Tracking Correctly|

@youngfreezyVA The accordion buttons referenced can be found at the bottom of both the [Spanish ](https://www.va.gov/asistencia-y-recursos-en-espanol)and [Tagalog ](https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong)language assistance pages. It is when a user clicks to expand any of these options: 
![image](https://user-images.githubusercontent.com/80417436/124311902-127e9500-db34-11eb-9d53-ec231b74dcae.png)

Right now on both staging and prod the interaction's label is coming in as `(not set)`:
![image](https://user-images.githubusercontent.com/80417436/124311956-2924ec00-db34-11eb-9c82-de2e677d1b02.png)

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - this is a bit of a long thread but short story is that in Lauren's comment above, the accordion buttons are coming in as (not set).I think we just need to pass nav-accordion-embedded-link-click. (GA report w/those events for reference [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=embedded/))|

**Comment by adamwhitlock1** [comment]
I spoke to @kelsonic about this issue and he has a similar ticket to update the `qa_collapsible_panel.drupal.liquid` and other drupal templates that are using the accordion component in general. https://github.com/department-of-veterans-affairs/va.gov-team/issues/27200

In looking at the english page analytics events, they also are missing the appropriate information as well for the accordions, so it looks like this is a larger issue not just pertaining to the translated pages.

**Comment by SKasimow** [comment]
Ah...thanks for the looking into this. Should we just link to this to the refactor ticket?

**Comment by SKasimow** [comment]
@adamwhitlock1 Analytics complete. Closing as implementation needs to be done holistically by PW team.
