### ISSUE TITLE
5490: Update form for legislative changes effective 8/1

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26436]
As an EDU team member, I need digital Form 22-5490 on VA.gov to be updated to include legislative changes that effective 8/1 so that the form is compliant with the changes.

## Assumptions:
1. This work is completed behind a prod flag.
2. AC 1 is **_NOT_** validation.

## Acceptance Criteria
1. On chapter 1, page 1, when the applicant has answers the "Your date of birth" question with a birthdate that reveals the applicant is under the age of 18 the following content is conditionally displayed using the blue information box pattern:

    > Applicants under the age of 18 cannot legally make a benefits election.  Based on your date of birth, please have a parent, guardian or custodian review the information on this application and click the “Submit application” button at the end of this form.   

    a. The content has: aria-live=“polite”

2. On chapter 1, page 1, the question "What’s your relationship to the service member whose benefit is being transferred to you?" answer "Spouse or surviving spouse" has a "Learn more" link that:
    a. Opens the following page in a new tab: http://www.va.gov/opa/marriage/
    b. Has the aria-label: "Learn more about VA requirements for marriage certification"

3. In chapter 2, page 1, the "Select the benefit that is the best match for you:" question answer has a `aria-describedby="[Informational Content UNIQUE ID]"`
    a. The 'Informational Content Unique Id' corresponds to the conditional content that is displayed after selecting an answer.

4. In chapter 2, page 2, question "Before this application, have you ever applied for or received any of the following VA benefits?":
    a. Does not have a "None" option as an answer choice.
    b. The "Other benefit" option has a checkbox
    c. The free text input corresponding with the "Other benefit" option is hidden and content is cleared when the checkbox (AC4b) is unchecked.
    d. The free text input corresponding with the "Other benefit" option is displayed when the checkbox (AC4b) is checked.
    e. When The "Other benefit" option is checked; the question, all available answers, and conditional free text input are displayed with the blue bar pattern.

~~5. In chapter 3, page 1, when FRY has been selected as the benefit type each answer to the "Do any of these situations apply to your sponsor?" question answer has a `aria-describedby="[DATE LABEL UNIQUE ID]"`.~~

6. In chapter 6, page 1, the question "Type of education or training" is not required.

7. In chapter 8, page 1, the following I Certify content is displayed after the section accordions:
    a. If the applicant answered the "Your date of birth" with a birthdate that shows that they are under 18 years of age and answered "Have you ever served on active duty in the armed services?" with "No":

    > **By submitting this form** you certify that:
    > 
    > - You are the parent, guardian, or custodian of the applicant
    > 
    > - All statements in this application are true and correct to the best of your knowledge and belief

    b. If the applicant answered the "Your date of birth" with a birthdate that shows that they are under 18 years of age and answered "Have you ever served on active duty in the armed services?" with "Yes" and **_any_** service period "Service end date" is blank:

    > **By submitting this form** you certify that:
    > 
    > - You are the parent, guardian, or custodian of the applicant
    > 
    > - All statements in this application are true and correct to the best of your knowledge and belief
    > 
    > - Since the applicant is an active-duty service member, he or she has consulted with an Education Service Officer (ESO) regarding their education program

    c. If the applicant is over 18 years of age and answered "Have you ever served on active duty in the armed services?" with "No":

    > **By submitting this form** you certify that all statements in this application are true and correct to the best of your knowledge and belief.

    d. If the applicant is over 18 years of age and answered "Have you ever served on active duty in the armed services?" with "Yes" and and **_any_** service period "Service end date" is blank:

    > **By submitting this form** you certify that:
    > 
    > - All statements in this application are true and correct to the best of your knowledge and belief
    > 
    > - As an active-duty service member, you have consulted with an Education Service Officer (ESO) regarding your education program

    e. If the applicant answered the "Your date of birth" with a birthdate that shows that they are under 18 years of age and answered "Have you ever served on active duty in the armed services?" with "Yes" and all service period "Service end date" values are **_not_** blank:

    > **By submitting this form** you certify that:
    > 
    > - You are the parent, guardian, or custodian of the applicant
    > 
    > - All statements in this application are true and correct to the best of your knowledge and belief

    f. If the applicant is over 18 years of age and answered "Have you ever served on active duty in the armed services?" with "Yes" and all service period "Service end date" values are **_not_** blank:

    > **By submitting this form** you certify that all statements in this application are true and correct to the best of your knowledge and belief.

~~8. In chapter 8, page 1, the "Submit application" button has a `aria-describedby="[By submitting this form content UNIQUE ID]"`~~

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/SZIAGWJTXCU)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/20ea2f105c74528bb1f1f35eec90e41d5cc0a428/products/education-careers/application/5490/content/5490-content.md)
3. [Aria Accessibility AC origination](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26936)

**Comment by dneel-bah** [comment]
AC 5 & 8 have been removed from this story due to platform level implications.  I have struck through them here so the referenced numbers are not removed and cause confusiong.

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17846

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2013)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
