### ISSUE TITLE
CT Redesign: Format of the ratings information is incorrect

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#26430]
## Steps to reproduce:

1. Navigate to 

https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=name&name=College%20of%20charleston&location=

And

https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location&name=&location=college%20of%20charleston

2. Look at College of Charleston
3. The format of the ratings information should be [star visual] (X.X of 5) by XX Veterans
4. "by XX Veterans" is missing

![Screen Shot 2021-06-22 at 1.14.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/52179a6d-8c59-43a0-8f19-e87d8ba59c4e)

![Screen Shot 2021-06-22 at 1.14.23 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d548ec69-cdee-4f81-a2e2-89852094569c)

## Expected Results:

**Remove Rated By: XX** should only have this below
![Screen Shot 2021-06-23 at 8.52.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7b0d04d6-e1f3-4dcc-b171-f6d24eba3401)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17665

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
