### ISSUE TITLE
Whole Platform - clarify what to do when you might accidentally publish someone else's changes (proactive)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26440]
# Description

To come.

**Slack URL:** https://dsva.slack.com/archives/C01AS05BQ79/p1624308462067400

# Reference info

**Dates:** Date asked to come, Date resolved to come.

- Notes to come.

**Comment by lianilychee** [comment]
this reminder can probably go out next week (the week of June 28)

Amy provisionally willing to send a reminder message

**Comment by lianilychee** [comment]
goal:
- inform platform teams what to do when they encounter someone else's changes (eliminate confusion)

talking points:
- acknowledge that we left a grey area: call out what we said in the training vid was vague, so we have more info
- for... 
  - whole pages: change privacy settings
  - partial pages: roll-back changes to prev version
- emphasize: it doesn't matter who was the one who accidentally published
- re-emphasize: plz keep all communications about Platform website in #VSP-confluence

**Comment by amygoldman** [comment]
_WIP draft_

In our training video about contributing to the Platform website, we weren't very clear about what you should if either a. you accidentally publish someone else's changes or pages before they're ready for publication or b. someone else accidentally publishes your pages or changes before they're ready for publication. 

Regardless of how the changes were published, here's how you can manage the situation:

- For whole pages that were published prematurely, you can change the privacy settings to make the page private. Once you're confident that the page is ready for publication, you can change the privacy setting back to public.

- For just parts of pages that were published too soon, you can roll back the changes to the previous version.
 
Just a reminder: please keep all communications about the Platform website to the #VSP-confluence channel on Slack.

**Comment by amygoldman** [comment]
Update: sent!

**Comment by amygoldman** [comment]
Closed by: Amy on 6/29/21
