### ISSUE TITLE
Drafts Null State

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26443]
## User Story
As a user, I want to see a null state in the drafts folder when I have no draft messages so that I know drafts exist.

## Acceptance Criteria
- When there are 0 messages in the draft folder, a null state displays. 

## Accessibility Guideline
* Indicate "You don’t have any drafts in your Drafts folder" as an H2

**Go to Inbox button**
Title= "Go to Inbox"
accessibilityHint= "Return to your inbox"
accessibilityRole= "Button"

## Design
![Draft - No messages.png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/f5a0656f-83a8-4f32-b47b-53bc093ab645)

**Comment by digitalken** [comment]
PASS 7/28/2021 - Looks good on iOS and Android.  FAIL on accessibility hint (and bug logged.). Since bug is logged and it was minor, I'm closing this story.

Bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/28053
