### ISSUE TITLE
CMS Test Implementation |"Other languages" page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#26444]
## User story

As a Veteran or family member with limited English proficiency, I need instructions for how to get language assistance in my native language.

## Issue description

Discover an approach and test to make Language assistance and resources pages to make "Other pages" a page with language assistance information in the top 10 languages for Veterans and family members with limited English proficiency. We can further iterate on this page by adding information about how to resolve concerns at VAMCs and your civil rights/how to file a discrimination complaint in each language.

## More info 

- Research ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/26048 

## Acceptance criteria:

[ ] Content is available in 10 languages 
[ ] Screenreader recognize and apply appropriate language for each section
[ ] Analytics fires correctly for each section of the page

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danielle - could we possibly get one additional language translated to add onto this page so we can confirm @youngfreezyVA approach works before he transitions?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. We can't do that, as we'll have to build a whole new page for this. The current link goes to a Resources & Support article. We're not going to use that page for this, but rather build a new one.

We have the sandbox environment now though. Could we build a node with multiple languages in the sandbox and test there? As long as it's not going to production, we can use Google translate content for testing the approach.

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - can you comment on Danielle's suggestion above for using the sandbox to test support of additional languages?

cc @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@adamwhitlock1 Hi Adam - I neglected to groom this ticket with you yesterday but please take a look at the Research ticket (link above in "More Info") and we can touch on when we meet with Michelle on Monday. Thanks!

**Comment by adamwhitlock1** [comment]
We have the ability to set the language attribute on any 'Rich Text' main content block, so I think that we could just use that to provide a page with 10+ language sections with essentially the same content in each section.

A sample implementation of this with 3 languages and some filler text content is available on a sandbox here:

https://web-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/health-care/language-test

Example of rich text block with 'source' view toggled on to show language tag attribute:

![Screen Shot 2021-07-26 at 8.14.38 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/b0de4377-4659-4f05-b36c-70626b127764)
