### ISSUE TITLE
Update link to point to 2019-2020 Yellow Ribbon schools 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#2645]
## User Story or Problem Statement
As a Veteran, I need the most up-to-date list of schools so I can see if my school offers the Yellow Ribbon Program. The program page currently links to the 2018-2019 school year list of schools. 

## Goal
In Drupal, update the link to the 2019-2020 list of Yellow Ribbon participating schools on the [Yellow Ribbon Program](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/) page.
New link to use: https://www.benefits.va.gov/GIBILL/yellow_ribbon/yrp_list_2019.asp

## Acceptance Criteria
- [x] Link updated to the 2019-2020 list of Yellow Ribbon schools

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of? [Epic Website content maintenance#2607](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2607)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
@RLHecht Updated link looks good. Page is set to publish.

**Comment by RLHecht** [comment]
@Karak888 I'll validate later today once Drupal deploy happens in afternoon.

**Comment by Karak888** [comment]
doh! Thank you!

**Comment by RLHecht** [comment]
Validated on live site. @Karak888 I'm closing this issue.
