### ISSUE TITLE
Onboarding New BE Engineer

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26467]
## Issue Description
Initial onboarding tasks for Michel McDonald

---
## Tasks
- Introduction to development environment
- Identify and assign initial tasks

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by annaswims** [comment]
Michel and  I have been chatting regularly about our products.  He expects to have his development environment set up today
