### ISSUE TITLE
5490: Remove prod flag for 8/1 legislative updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26460]
As a developer, I need to remove the prod flag created for #26436 so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 2021-07-22.

## Acceptance Criteria
1. The functionality created in #26436 is available in production.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/17992

**Comment by delli-gatti-michael** [comment]
Changes are live in production. Closing this issue
