### ISSUE TITLE
Check image gets cut off in landscape mode

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26472]
## What happened?
On the Direct Deposit edit page, the check image gets cut off when the device is in landscape mode. 

## Specs:
- Device: iPhone 11

## Steps to Reproduce
- On an iPhone 11, view the app in landscape mode
- On the Direct Deposit edit page, expand the dropdown to view the check image
- Observe how the right side of the image gets cut off and isn't fully in view

## Desired behavior
When in landscape mode, the image resizes to fit within the boundaries of the white box behind it

## Acceptance Criteria
See desired behavior above.

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Image from iOS (25).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c86302f3-f143-4d5d-909b-c7ad6f16350a)

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good on iOS and Android.  Closing.
