### ISSUE TITLE
Create research readout for COE usability testing

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#26489]
## Background
Certificate of Eligibility (COE) usability testing sessions are complete.

## Considerations
- [Top line summary for context](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-topline-summary.md)
- [CH31/6 synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-synthesis.md)
- [Session notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/session-notes)
- [Latest template version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/research-findings-template.md)

## Tasks
- [ ] Create research readout for COE usability testing

## Acceptance criteria
- [ ] Research readout for COE usability testing available for team review

**Comment by jason-gcio** [comment]
@candy-gcio is there an artifact for this?

**Comment by candy-gcio** [comment]
Yep. It's here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-readout.md
