### ISSUE TITLE
Draft Messages Display in Draft Folder 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26495]
## User Story
As a user, I want to be able to see my draft messages in my draft folder so that I can edit a message. 

## Acceptance Criteria
1. When a user opens the draft folder, draft messages display. 
2. Selecting the Drafts ListItem routes to a new page, called "Folders" (H1)
3. Pull in loading screen component as the app works to load the Drafts page
     - Copy: "We're loading your messages"
4. Pull in loading screen component as the app works to load the Drafts page
     - Copy: "We're loading your messages"
5. On the Drafts page, create section header called "Drafts" (H2)
6. Draft messages are listed by date/time, with the most recent message at the top of the list
7. Each draft message ListItem should include: 
     - Header: [Draft -] + [Recipient] (ex: Draft - MHClinic)
     - Line 2: Subject: subject line
     - Line 3: Date @ time. Format: "01 Mar 2021 @ 1345 ET"
     - Optional: attachment icon if there is a file attached to the message
     - Should not display: READ receipt, unread indicator
8. Display pagination component on the Drafts page when there are >10 draft messages 

## Accessibility Guidelines

* Mark "Folders" as H1
* Mark "Drafts" as H2 

**Draft list**
For each field:
accessibilityLabel= contents of ListItem
accessibilityHint= "view this draft message"
accessibilityRole= "button"
accessibilityValue= let the user know the element in the list which is currently being focused and its place in the list

## Design
**Draft Folder List**
![drafts folder.png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/16fc85dc-934b-483c-a208-fc4af78f49b1)

## Tech Notes
7. Update any failing unit tests
     - Add test that checks that the Drafts folder is displaying, has no indicators, and is prefixed with "Drafts. -"

**Comment by digitalken** [comment]
PASS 7/15/2021 - Although I logged two fairly minor bugs on this one, I've chosen to pass/close it since the minor bugs are being tracked in zenhub.  Other than the bugs, it looks good on iOS and Android in functionality and accessibility.  Bugs listed below.  Closing.

Draft Messages - Draft count on Folders page doesn't increment like the total of drafts in the pagination for the draft folder does #27453

Draft with attachment is not displaying attachment icon in listing #27457
