### ISSUE TITLE
Deduplicate content on "Request access to tools" page

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#26491]
### Description
There is content which has been added to Platform website page https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html but has not been removed or linked from `va.gov-team` page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md

### Relevant URLs 
For example the "Request Access" section:
 - https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html
 - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md
 - https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools

**Comment by amygoldman** [comment]
Hi @mchelen-gov! Defining ownership of docs is currently in our backlog. 

As a short-term solution, we added a deprecation message to the [GitHub version of the doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md) and ensured [the Platform Website version](https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools) is up-to-date. 

If any updates need to be made to this doc, please update the Platform Website version only by following our [guidelines for updating documentation](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+page#Step-4%3A-Update-the-Platform-website). 

This doc is part of a broader set of docs that are going to be updated and migrated. We appreciate that this isn’t a perfect solution, and it’s currently a work in progress. Thanks for bearing with us!

**Comment by jbritt1** [comment]
Removed the duplication in the newer version / source of truth https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=969605215&selectedPageVersions=4&selectedPageVersions=3

**Comment by jbritt1** [comment]
Not quite sure how to make the change show up on https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html still though 😕

**Comment by jbritt1** [comment]
Looks like the published version is now reflecting the change of dropping the desired note: https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Requestaccess

**Comment by lianilychee** [comment]
closing this ticket, as the issue (duped content) appears to be resolved.

hey @jbritt1 !  In the future, if you have any Platform website questions -- ie, your q about making the change show up https://github.com/department-of-veterans-affairs/va.gov-team/issues/26491#issuecomment-872213178 -- you can best reach the Content/IA team through [#vsp-confluence](https://dsva.slack.com/archives/C01AS05BQ79) in Slack.

^^ You might already know this since I'm commenting months after the fact 😆
