### ISSUE TITLE
[repo migration]: Healthcare

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2650]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [ ] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [ ] Run migration script on linked migration plan file
- [ ] PR for va.gov-team
- [ ] PR for vets.gov-team
- [ ] Merge va.gov-team PR
- [ ] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1EJadI7Guty7ptWRI8tjBD0tmi7SI7HbnK2bV1BQ07NA/edit#gid=1283217997

**Comment by thatmattjohnson** [comment]
#3955: all discrepancies reviewed and resolved in migration plan; need to rerun script

#20070: reviewed/approved

#24: reviewed/approved

**Comment by billfienberg** [comment]
WIP PRs for files migrated from `vets.gov-team` to `va.gov-team`
• `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20062
• `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3955 (still resolving discrepancies)

WIP PRs for files migrated from `vets.gov-team` to `va.gov-team-sensitive`
• `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20070
• `va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/24

**Comment by thatmattjohnson** [comment]
#20062 reviewed/approved.

**Comment by thatmattjohnson** [comment]
all PRs reviewed/approved.  UAT revealed some broken deprecation links; resolved manually.  All else looks good; closing this issue.
