### ISSUE TITLE
Incorrect a11yHint on Folders buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26505]
## What happened?
On the Folders page, the accessibilityHints for the Sent & Custom Folders ListItems are announced as: "view this message thread". 

This accessibilityHint does not make sense, as the corresponding pages are not message threads.

## Specs:
- Device: iPhone 11

## Steps to Reproduce
1. Turn VoiceOver on
2. Log in with +41
3. Navigate to the Folders tab
4. Select the following ListItems: "Sent", "Custom Folder 2", and "Test". Observe how the accessibilityHint is the same for each of these ListItems: "view this message thread"

## Desired behavior
1. accessibilityHint for Sent ListItem: "view your sent messages"
2. accessibilityHint for any custom folder ListItems: "view messages in this folder"

## Acceptance Criteria
See desired behavior above.

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
n/a

**Comment by digitalken** [comment]
PASS 6/25/2021 - No announces folder instead of thread.  Closing.
