### ISSUE TITLE
Setup BE for scheduled downtime notifications

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#26509]
## Technical Task

We need to show scheduled downtime messages on FE so users do not visit a down application and are told when to com e back. Setup FSR `vets-api` to get downtime windows from Pager Duty so they can be passed to the FE.

## Expected Behavior

Scheduled downtime windows are able to be retrieved by the FE

## Acceptance Criteria

- [ ] When downtime is scheduled in pager duty it is sent to FE
- [ ] Downtime console error is removed

**Comment by denisecoveyduc** [comment]
In #49728 we will investigate which external services have downtimes that are applicable for this work.

**Comment by HeatherRienks** [comment]
@OptionSelect  to investigate if this needs to be closed

**Comment by HeatherRienks** [comment]
@ScottyRJames and @kjsuarez and @OptionSelect to huddle re this ticket on 10/24

**Comment by OptionSelect** [comment]
Have not huddled with BE team yet, ticket will roll however it is first priority for next sprint.

**Comment by OptionSelect** [comment]
Rolling due to issues with validation slowing me down, now picking up. Scheduling meeting with BE team.

**Comment by OptionSelect** [comment]
This ticket is also serving to remind us to investigate a Downtime console error!

**Comment by OptionSelect** [comment]
Confirmed working per window with back end team. <img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODg3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3316ea5c2af2e18a0877cd50def3dd07719c7b9/image.png" alt="image.png" />

Continuing console error investigation.
