### ISSUE TITLE
Security (Authentication) - Investigate pomerium as a viable source of Github SSO

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#26519]
Research pomerium and find out what it is capable of. If it can serve as an auth proxy, setup a prototype with github SSO enabled.

AC: 

- [ ] Quick explainer in Confluence 
- [x] Validate with other teams

**Comment by tskinn** [comment]
Interesting note on adding oauth apps to dvsva github org https://github.com/department-of-veterans-affairs/github-user-requests/issues/7676

**Comment by jhouse-solvd** [comment]
@tskinn - there's a task above "Quick explainer in Confluence". If we can get that done and linked up to this ticket, that would be helpful.

**Comment by jhouse-solvd** [comment]
This is done for now. Please see linked PRs. 
If we decide to move forward w/ Pomerium, we'll determine what documentation may be necessary. 

Closing.
