### ISSUE TITLE
Research NLB -> ALB forwarding and provide NLB static IP to CMS team, assuming it is possible to do this

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#26518]
Lighthouse is making this vital work by July 1

Boris says we'd need to make a lambda to update it when the NLB changes. some technical work to be done

https://dsva.slack.com/archives/CJYRZK2HH/p1623435716154800

- [ ] Give static IP that forwards to TBD

**Comment by jhouse-solvd** [comment]
@dginther - can you help us draft what's needed here

**Comment by dginther** [comment]
https://aws.amazon.com/blogs/networking-and-content-delivery/using-static-ip-addresses-for-application-load-balancers/

This AWS article outlines the steps to make this work.

**Comment by jhouse-solvd** [comment]
@dginther - Do you know if this was done and can be closed?

**Comment by dginther** [comment]
Done.
