### ISSUE TITLE
OCTO-DE - how to deprecate, who owns Platform-wide docs in the interim (reactive)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26526]
# Description

**Question:** how to deprecate?  what if there's an existing doc that needs updating?  who owns while the ownership is fuzzy?

**Slack URL:** https://dsva.slack.com/archives/CJRQ85PQB/p1624469279366700 this whole thread

# Reference info

**Dates:** 6/23 asked, 6/30 resolved

**Days to resolution:** 6 biz days

**Comment by lianilychee** [comment]
6/29 tues:
- let's NOT take action on this today (tues) bc Amy and Gretchen will need to read the thread to get full context
- thoughts:
  - perhaps Dror (and/or Fleet) if it's an eng thing?
  - interim solution: quick conversation with leadership, and we can revisit when we pick up this initiative in earnest

**Comment by amygoldman** [comment]
Closed by Amy on 6/29/21
