### ISSUE TITLE
[FE] My VA: (UAT Bug) 'View lab results' and 'View medical records' behave differently - one opens in another tab, another opens in the same tab

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26528]
## Background

During UAT we found that 'View lab results' and 'View medical records' behave differently - one opens in another tab, another opens in the same tab. They should both open new tabs.

## Task

- [ ] Fix this so both links open in new tabs

**Comment by erikphansen** [comment]
Addressed by https://github.com/department-of-veterans-affairs/vets-website/issues/17670

Ready to be validated in staging.

**Comment by ajakabcin** [comment]
Confirmed on staging
