### ISSUE TITLE
Access for Saad Ahmed

### ISSUE THREAD

**Issue by saad-va** [department-of-veterans-affairs/va.gov-team#26527]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Saad Ahmed
- Please Provide your email.
   > saad.ahmed@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I work on Leeroy Jenkles with the Lighthouse project. I work for Libtertyits

- Requesting SSH key authorization?
   > YES 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDwfb0uhhXhqnGWx0HnJYt/Fb+DOhHhoZo6TyWbsT7Ylr85unkXCDB9/2rxt22Hk71PU6BKFjNRDSNSmylAOle4DGK0yEKlE+4jG120indAMnCDkzbE44HCYoWjavi8mz72QxxFsdw8Ij0o5SM36A/xwvZPf+a4kbqR5drnkkVEKOwntz8BmWwWmQf0I5UEv58/zy2A44tEJxElk/0LooHUeTDpnafqGVMdQUKPhNMNBov3+sKHBJp3MhDLNCZzyylVwwv6j/dncOl5Ocqn14w4+a8gKIp18kO+CtbjBsYyPYi3l80KjofrOqQBvhktJsaD3UNOWlzxFRkK14eW9F3dUigtVRS+WCTVylrPEiLai/C1Mn/N97+zp59Hhjnm/6ctITsxy1Ou4UxxAI0cBN2TZEGe/zcCVwaUE7G/RpZVzgFo2gcTE3X6vlAnfRc1lif8oAt556SvHP7BE7C4jFT2vljj62KG6PJo9wNQ/aV6r5CitnehZID4fy1ugyeGj4c= Saad@WIN-PQB8E9L0BVU
```

- Grant AWS Console access?
  > YES
I am on the DevOps team and will need console access for managing Lighthouse components that still reside in DSVA

**Comment by mydesignrocks** [comment]
your socks access has been through and please follow these steps:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - please review AWS access for this user.

**Comment by drorva** [comment]
Email sent to CORS, awaiting confirmation.

**Comment by drorva** [comment]
approved

**Comment by mydesignrocks** [comment]
AWS access provided and sent the directions to login. closing now... if there are issues, please reachout using /support in slack vfs-platform-support channel.
