### ISSUE TITLE
Discovery: Investigate gracefully killing Sidekiq workers during deploys

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#26520]
Sidekiq workers should be gracefully killed during deploys. We're not sure what's happening right now or how we should be doing it.

## AC
- [ ] Enqueue a long running job via `rails console` just before a deploy to see what happens (e.g. Does it get killed? Does it get added back to the queue?).
- [ ] Determine the proper way to kill Sidekiq workers
- [ ] Decide if it's valuable to do the work now or when we migrate to k8s

From Eric: I doubt they are as USR1 signals are no longer supported since 5.0.

**Comment by LindseySaari** [comment]
Some links for Sidekiq autoscaling from a [conversation](https://dsva.slack.com/archives/CJYRZK2HH/p1635803175251800) with Demian

1. https://www.cuelogic.com/blog/how-to-autoscale-instances-depending-upon-sidekiq-queue-size
2. https://www.pablocantero.com/blog/2013/05/04/auto-scale-sidekiq-workers-on-amazon-ec2/

**Comment by RudyOnRails** [comment]
Not sure if this helps or if I'm poking my nose where it shouldn't be (just tell me), but at a company I used to work at we used Capistrano for deploys and the sidekiq plugin used to "quiet" the workers. Quiet causes workers to stop grabbing jobs from the queue. Looks like after Sidekiq 5, they suggest using `TSTP` in the beginning of the deploy and `TERM` at the end: https://github.com/mperham/sidekiq/wiki/Signals#tstp

**Comment by ericboehs** [comment]
Thanks @RudyOnRails.

As we're moving to K8s, this is something we'll want to consider.

I did observe long running jobs are re-enqueued across deploys (using our current BRD process) so they aren't getting killed and forgot about.

That doesn't mean we're exiting properly but at least jobs aren't completely dropped before they can do their work.

**Comment by ericboehs** [comment]
We verified that long running jobs will get properly restarted after a deploy.
