### ISSUE TITLE
Focus goes to "skip to content"

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26532]
##  Description

defect-2 When searching from global header, focus goes to "skip to content", not the actual search results
Focus should go to "Showing 1-10 of..." so users know that the search has been activated and that results exist. "Showing 1-10 of..." should also be a h2, and not a p with aria-live to be consistent with the other search experiences.

## Background/Context
GH [#26416](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26416)

## Acceptance Criteria
- [x] Issue has been resolved

**Comment by srsuddath** [comment]
I believe this ticket has been resolved as a part of #26534
