### ISSUE TITLE
Duplicate Appointment Slots

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#26539]
1. Log in to VAOS as Judy Morrison
2. Select any type of care configured for direct scheduling.  
3. For desired date enter a date in July.  Calendar displays.  Randomly select a couple days to see the slots.
4. Select the <-previous button to go back to June. Randomly select a day to see slot and double slots display

As far as I can tell this only happens on the month of June.  If you start in August and go back to July it is not happening.  It only happens if you go back to June.

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/0f9bd5df-813a-4205-b716-2abfc86f9ee9)

**Comment by jbalboni** [comment]
I believe this is related to https://issues.mobilehealth.va.gov/browse/VAOSR-2055.

When we fetch slots the start date we pass is ignored, which means that we start getting duplicate slots in our list when we make the call to get the next set of slots. I think this is also resulting in an error when you try to go too far in the future.

**Comment by laurenernest** [comment]
Fix for blocker is slated for var-resources 4.30.1

**Comment by jbalboni** [comment]
Looks like this should be fixed now

**Comment by laurenernest** [comment]
No longer seeing issue. closing ticket.
