### ISSUE TITLE
Focus is not providing feedback to users when there are no results

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26533]
##  Description

Defect-2 No feedback is provided when there are no results
Focus is not managed post search when no feedback emerges. Focus should go to the error message that no results were found.

## Background/Context
GH [#26416](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26416)

## Acceptance Criteria
- [x] Tier 3 (No Socks validation necessary)

**Comment by srsuddath** [comment]
This ticket is ready for validation as part of the staging review
