### ISSUE TITLE
Dynamically generate robots.txt entries

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26547]
## Issue description
Each time the VAMC team brings up a new System into Dual-State, a disallow line (Disallow: /(name)-health-care/) has to be manually added to the robots.txt file to prevent crawlers from accessing the new site in dual state.  

Similarly, when the site moves from dual state to live, the line must manually be removed from the list so crawlers and external browsers can find the new URL.

This manual effort isn't entirely scalable and a dynamic solution would be more efficient. 

## Tasks
- Determine a solution to dynamically generate the robots.txt entries

**Comment by mpelzsherman** [comment]
Discussed w/Dave & the team... we don't think there's enough benefit since we will be done migrating sites by December.
