### ISSUE TITLE
Redirect Request [TBD]- VAMC - VA Erie health care health care

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26545]
Redirect Request - VAMC - VA Erie health care health care 

### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
VHA Digital Media and VA Erie health care have approved moving VA Erie health care from dual state to full production.  Set for July 7th, 2021 

### Requesting team info
VAMC - upgrade team - Stan Gardner - sgardner@governmencio.com
[vsa-vamc-upgrade Slack Channel](https://dsva.slack.com/archives/CPQFCQKEH) 

### Implementation date
**July 7th, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday **July 7th, 2021**

Please indicate when the change/redirect(s) needs to be implemented"
**July 7th, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday **July 7th, 2021**
- Redirect can occur at start of day so site can be validated and tested. 

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.erie.va.gov/ 				| https://www.va.gov/erie-health-care/
**Removed by MN** <br> ~https://www.erie.va.gov/locations/directions.asp~ 	| ~https://www.va.gov/erie-health-care/locations/erie-va-medical-center/~
https://www.erie.va.gov/locations/ashtabula.asp | https://www.va.gov/erie-health-care/locations/ashtabula-county-va-clinic/
https://www.erie.va.gov/locations/crawford.asp  | https://www.va.gov/erie-health-care/locations/crawford-county-va-clinic/
https://www.erie.va.gov/locations/mckean.asp    | https://www.va.gov/erie-health-care/locations/mckean-county-va-clinic/
https://www.erie.va.gov/locations/venango.asp   | **Modified by MN** <br> ~https://www.va.gov/erie-health-care/locations/warren-county-va-clinic/~ <br> https://www.va.gov/erie-health-care/locations/venango-county-va-clinic/
**Removed by MN** <br> ~https://www.va.gov/erie-health-care/locations/venango-county-va-clinic/~ | ~https://www.va.gov/wilmington-health-care/locations/sussex-county-va-clinic/~
**Added by MN**<br> https://www.erie.va.gov/locations/warren.asp | https://www.va.gov/erie-health-care/locations/warren-county-va-clinic/
**Removed by MN** *(Page isn't fully live, don't need to redirect)*  <br> ~https://www.erie.va.gov/services/covid-19-vaccines.asp~ | ~https://www.va.gov/erie-health-care/programs/covid-19-vaccines/~
**Added by MN** <br> https://www.erie.va.gov/services/covid-19-vaccines.asp | https://www.va.gov/erie-health-care/programs/covid-19-vaccines/

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [ ] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [ ] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@SgardnerPMP Made a number of updates to the list above.  Can you please take a look and let me know if there are any issues?

**Comment by SgardnerPMP** [comment]
@mnorthuis, Please be advised that Erie has pulled out of Full Production for next week.  Their PAO has left and is being replaced by an alternate. They will be reassigned for July Full production, but for now they will be moved to Backlog until the new PAO is fully updated and has reviewed all of the pages.

**Comment by mnorthuis** [comment]
Redirect will be handled by a Service Now request.
