### ISSUE TITLE
[repo migration]: Identity

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2655]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [ ] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [ ] Merge va.gov-team PR
- [ ] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1GEn63xS9MWUkXzKBAtomBIey5NXA7PFlUE0ayaY6aqI/edit?ts=5defe2b4#gid=1914583772

**Comment by billfienberg** [comment]
PRs:
* `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20089
* `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/4411

**Comment by thatmattjohnson** [comment]
PR review/UAT completed; all looks good. Closing this issue.
