### ISSUE TITLE
Do not display addresses for mobile Vet Centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26557]
## Issue Description
We recently removed the address display for mobile clinics on VAMC Location pages due to the likelihood of inaccuracy and because they are _mobile_  by definition. Vet Center Location pages still display addresses for Mobile Vet Centers. For consistency and accuracy, we should consider hiding the address. 

## Tasks
- [ ] Remove/hide addresses for Mobile Vet Centers on Vet Center Location pages

## Acceptance Criteria
- [ ] When a Mobile Vet Center is included on the Location page, it contains only the name, photo (if present) and phone number.

**Comment by mpelzsherman** [comment]
Already done
