### ISSUE TITLE
Search Landing Page (404) Mockups 

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#26558]
Continuation of [#26558](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26558)

**Comment by mgleo** [comment]
![404-search-landing.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/71ccd8e7-d11d-4d27-afe3-ffcf5e2264c8)

**Comment by denisecoveyduc** [comment]
@mgleo This looks great! Let's keep in mind as we determine  next steps for the search "start" page. I am excited to see your vision for that page.
