### ISSUE TITLE
va-alert font size is too big

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#26566]
## Issue Description
The `font-size` on the `<va-alert>` web component is `2rem` when it should be `1.6rem` to match the rest of VA.gov.

I think the solution here is to remove the `font-size` declarations altogether. I think it's fine if that's controlled by the globally-scoped stylesheet. (Or whatever it's called. The thing outside the CSS encapsulation that we get with web components.) This allows for greater flexibility and use outside of VA.gov if desired.

![image](https://user-images.githubusercontent.com/12970166/123295181-520d0780-d4ca-11eb-8987-307fa105a9bf.png)

---
## Acceptance Criteria
- [ ] The font sizes match the parent styles

**Comment by bkjohnson** [comment]
(We still need to release that version & update `vets-website`)

**Comment by bkjohnson** [comment]
[Release](https://github.com/department-of-veterans-affairs/component-library/releases/tag/wc-v0.7.1) has been tagged & made available in `vets-website`.
