### ISSUE TITLE
Duplicate women's health accordion on Jersey City

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26570]
## What happened?
There are duplicate Women Veteran Care service accordions on [Jersey City VA Clinic](https://www.va.gov/new-jersey-health-care/locations/jersey-city-va-clinic/).  Content in the two accordions is different. 

This duplication causes an accessibility defect in the build due to duplicate IDs

<details>
<summary> Screenshots from prod </summary>

 ![image](https://user-images.githubusercontent.com/55411834/123298153-73272580-d4d5-11eb-9dd9-08f5d8d52fca.png)

https://files.slack.com/files-pri/T03FECE8V-F026107JZQV/screen_shot_2021-06-24_at_1.01.40_pm.png

</details>

Drupal contains only one Women Veteran Care service accordion: prod.cms.va.gov/new-jersey-health-care/locations/jersey-city-va-clinic/, which was created yesterday and has a published state
Node: prod.cms.va.gov/node/23601

This is not occurring on other facility pages or for other health services on this page. 

## Acceptance Criteria
- [ ] Health services are displayed based on Drupal data in published states

**Comment by mmiddaugh** [comment]
Update - this is behaving as expected on Staging

**Comment by gescobardev** [comment]
@mmiddaugh Update on where this issue stands-
It was discovered from the metalsmith data and graphql data that there is a difference between these 2 "Women Veteran care". The difference is seen in `fieldServiceLocation`, one is empty and one is not.

![Jersey_City_VA_Clinic_____Veterans_Affairs (1)](https://user-images.githubusercontent.com/84030819/123474693-54ee2200-d5c8-11eb-86dc-26955bc49031.png)

<img width="607" alt="Jersey_City_VA_Clinic_____Veterans_Affairs" src="https://user-images.githubusercontent.com/84030819/123474327-cc6f8180-d5c7-11eb-8eb5-5d4555306348.png">

It was concluded that this is a CMS data issue. I have added the slack thread below for reference.
https://dsva.slack.com/archives/C0FQSS30V/p1624637989407200
