### ISSUE TITLE
Design Feedback - Staging Review - Claims & Appeals - 526 Wizard updates

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#26578]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change this green button to a [green action link](https://design.va.gov/experimental-design/action_links)
- ![Screen Shot 2021-07-01 at 8.32.30 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/aaa8f819-4b28-45f6-bb30-d93ac175f1f2)

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by Mottie** [comment]
The collapsed "Let's get started" button (not link) that is visible on the form info (not intro) page is located within the `applications/static-pages/wizard`, which I believe is owned by the public websites team.

**Comment by Mottie** [comment]
So to clarify:
- In staging, this `<button>` (static-pages wizard) redirects users to the `/start` page since it's behind a feature flag 
- In production, this same button expands the wizard on the same page

**Comment by Mottie** [comment]
Closing this... the wizard has been moved to https://www.va.gov/disability/file-disability-claim-form-21-526ez/start & there is now an action link on the [eligibility page](https://www.va.gov/disability/eligibility/).

<img width="674" alt="Screen Shot 2021-12-06 at 1 27 49 PM" src="https://user-images.githubusercontent.com/136959/144909680-550d3b70-af1e-4590-b1bd-3fe83743c888.png">
