### ISSUE TITLE
App-wide copy change for name of app 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#26583]
# Context for this ticket
We want to change how we refer to ourselves in the app for 2 reasons:

1. We have changed our name to "VA: Health and Benefits" but it might change again, so we want to keep app copy generic 
2. We want to be less self-referential overall   

# Acceptance criteria
1. Sweep app to remove "VA Mobile" and "VA Mobile App"

# Places to change text
Locations include but may not be limited to: 

- [x] Biometric opt-in screen: Change "_Do you want to allow VA Mobile to use [biometric option]?_" to "_Do you want to allow us to use [biometric option] for sign in_?" 

- [x] Onboarding screen 1: "_Change Welcome to the official VA Mobile app, [name]_" to "_Welcome, [name]_"
 
- [x] Error states: Don't be self-referential by name. Change current copy to remove app name where it exists and to read: "_The app isn't working right now..._" or "_We're having trouble loading your..._"

**Comment by digitalken** [comment]
PASS 7/20/2021 - I was not able to find the incorrect app name in the app but I did find it in the IAM authorization screen. Simply to keep track, I created a bug on that but I'm passing/closing this story.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/27603
