### ISSUE TITLE
A/I - couple of questions about SVP vs Conf (reactive)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#26586]
# Description

**Question or description:** 

is there a way to grab a Platform Website page link before it gets pushed to production?
- Context: we want to build links in our dashboard to this content page, but aren’t ready to push the page to production until next week.
- (Maybe answering my own question here:) would it just be adding it to the Platform Website space, but not pushing Update site? My fear with this is that we add it & someone else pushes it with their update.
(less urgent question): could we use the children's display that y’all use for the documentation homepage for the Analytics & insights homepage?

**Slack URL:** https://dsva.slack.com/archives/C01AS05BQ79/p1624560091075800?thread_ts=1624377737.072200&cid=C01AS05BQ79

# Reference info

**Date we were asked:** received 6/24 thurs.

**Date we resolved:** Date we received confirmation of resolution to come.

**Days to resolution:** To come.

**Comment by lianilychee** [comment]
notes:
- is it that they want to know the link before the page is live?  then the answer is NO
- what is the use case?
  - to VFS folks, NO
  - but if you just wanna share amongst ppl in the platform, then you can grab the confluence link

**Comment by amygoldman** [comment]
Hi Joanne!

It depends on the reason why you want to get the link for a Platform Website page before publication.

- If you want to know the live Scroll Viewpoint-powered PW link before the page as it'll be seen by VFS folks, you'll have to publish the page first.
- If you want to share the draft of the page in Confluence with other Platform users, you can just grab the Confluence link and share it. 

Hope this clears things up!

**Comment by lianilychee** [comment]
gretchen found how svp generates urls https://help-cloud.k15t.com/scroll-viewport/How-Does-Scroll-Viewport-Construct-URLs%3F.843515335.html

**Comment by amygoldman** [comment]
Closed by Amy on 6/29/21
