### ISSUE TITLE
Onboarding screen #1 displays {firstName}} instead of user's first name

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26597]
## What happened?
Onboarding screen #1 displays `{firstName}}` instead of the user's first name (i.e. "Judy"). 

## Specs:
- iPhone 11, Samsung Galaxy S9
- TF build: 1.0.0 (14)
- Users: judy, +41

## Steps to Reproduce
1. Reset first time log in
2. Log in with any user and view Onboarding Screen #1

## Desired behavior
1. App displays the value of the `firstName` field
     - E.g. "Welcome, Judy" instead of "Welcome, [firstName}}"

## Acceptance Criteria
See desired behavior

## Bug Severity
- 3 - Medium

## Screen shot(s) and additional information
![Image from iOS (30).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/dd2f6240-4e02-4294-bebf-aec6b6d8a4c1)

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good on iOS and Android - seeing the name.  Closing.
