### ISSUE TITLE
Contact Center Review for VAOS-Community Care Provider Selection

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26591]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description

Product: VAOS - VA online scheduling (VAOS) is a Veteran-facing healthcare appointment online scheduling tool on VA.gov.

Context of changes: 
- Community Care Provider Selection MVP
- Updating vaccine scheduling intro to sustainment entry point

(I uploaded the version with the tracked changes so you can see the diff)

### Launch Date
Already launched

### Version Number
6/24/21

### Product Guide
[vaos-product-guide-20210624DRAFT.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6711685/vaos-product-guide-20210624DRAFT.docx)

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Thank you, @laurenernest. Changes look good. I have shared with VEO.
[vaos-product-guide-update-06242021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6718565/vaos-product-guide-update-06242021.docx)
