### ISSUE TITLE
[Research] My VA: Create conversation guide for research on elevating action items

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26599]
## Background
As part of long-term research and continued improvements to My VA post-launch we need to create write the conversation guide that goes along with the research plan for how to better elevate action items in the dashboard.

## Tasks

- [ ] Write conversation guide.
- [ ] Review with team/AJ/Kevin

**Comment by tressaellen** [comment]
Here is the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/research/alerts-discovery-conversation-guide.md) for elevating action items.
