### ISSUE TITLE
[Research] My VA: Create research plan for elevating action items

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26598]
## Background
As part of long-term research and continued improvements to My VA post-launch we need to create a research plan for how to better elevate action items in the dashboard.

## Tasks
- [x] Write research plan.
- [ ] Review with team/AJ/Kevin.

**Comment by tressaellen** [comment]
Here is the [research plan for action items](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/research/alerts-discovery-research-plan.md). It's currently getting reviewed by a few internal people, but I'll close this ticket when all the updates are made.
