### ISSUE TITLE
Discrepancies in urgent care search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26593]
## Issue Description
Community urgent care search results for Anchorage don't appear to be included in the "All urgent care" results. I tested this in Indianapolis and Washington, DC and those searches behaved as expected

## Steps to reproduce
1. enter Anchorage, AK for location
2. Select Facility type = "Urgent care"
3. Select Service type= "All urgent care" 
4. Observe no search results are returned (Screenshot 1)
5. Change Service type to "Community urgent care"
6. Observe results are returned (Screenshot 2)

## Screenshots

<details>
<summary> Screenshot 1: "All urgent care" results </summary>

![image](https://user-images.githubusercontent.com/55411834/123326067-040df900-d4f6-11eb-9ead-74649d8da3d1.png)

</details>

<details>
<summary> Screenshot 2: "Community urgent care" results </summary>
![image](https://user-images.githubusercontent.com/55411834/123325965-e5a7fd80-d4f5-11eb-972d-21d94b9b8a91.png)

</details>

## Expected behavior
- Results for "All urgent care" searches should contain the closest VA and community urgent care results. 
- If "Community urgent care" searches return results, then "All urgent care" search should not return 0 results.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

---

**Comment by mmiddaugh** [comment]
Issue resolved itself and was believed to be related to caching. 
@darkbushido to discuss with Michael Fleet

**Comment by darkbushido** [comment]
The query to the rails api that isn't giving any results is

`https://api.va.gov/facilities_api/v1/ccp/urgent_care?address=632+West+6th+Avenue%2C+Anchorage%2C+Alaska+99501%2C+United+States&bbox%5B%5D=-150.6449&bbox%5B%5D=60.4663&bbox%5B%5D=-149.1449&bbox%5B%5D=61.9663&latitude=61.2163&longitude=-149.8949&page=1&per_page=40&radius=665`

changing the `per_page` param by one we were able to get 18 results

`https://api.va.gov/facilities_api/v1/ccp/urgent_care?address=632+West+6th+Avenue%2C+Anchorage%2C+Alaska+99501%2C+United+States&bbox%5B%5D=-150.6449&bbox%5B%5D=60.4663&bbox%5B%5D=-149.1449&bbox%5B%5D=61.9663&latitude=61.2163&longitude=-149.8949&page=1&per_page=39&radius=665` is giving results

this may be a caching issue and I have mentioned it in the #SRE channel
