### ISSUE TITLE
Links on null screens are left-aligned when they should be centered

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26596]
## What happened?
The app contains some null/unauthorized screens where the content (all copy and links) should be center aligned. In the latest build, the copy is still center-aligned, but the links are now left-aligned. 

This includes (but may not be limited to) the following screens:
- Appointments > null state
- Letters > unauthorized screen

## Specs:
- iPhone 11, Samsung Galaxy S9
- TF build: 1.0.0 (14)
- User: +366

## Steps to Reproduce
1. Log in with +366
2. View the Appointments page, and the Letters list page. 

## Desired behavior
1. Links should be center-aligned to match the copy

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Image from iOS (29).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/dccab6c7-d025-42f0-9eb5-1e3fa3238468)
![Image from iOS (28).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6875dd76-e318-4cf2-88a0-8a505c531581)
![Image from iOS (27).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/daff0d93-6f7e-4b2e-ac6d-6746a4971893)

**Comment by lexicalninja** [comment]
looks like the change in #26222 pushed everything over. I am going to revert those changes and reopen that ticket for fixing. 

@kxiao133 FYSA, since that was your ticket. Not sure if you want to try again or just leave it in the backlog, its your preference.

**Comment by digitalken** [comment]
7/2/2021 - Looks good on Android, waiting on iOS build.

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good on iOS and Android.  Closing.
