### ISSUE TITLE
Cancel Button Action w/ No Message Content

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26594]
## User Story
As a user, when I hit cancel on a compose/reply screen that is empty, I want to be redirected to my previous screen rather than seeing a confirmation alert because there is no message content to save. 

## Acceptance Criteria
* If all form fields are empty, send users back to the previous page when they hit "Cancel" without a confirmation alert

Note: on edit screens, hitting cancel should take the user to a cancel confirmation screen. 

## Accessibility Guidelines
* Accessibility requirements should match existing Cancel state 
    * Title: Cancel
    * accessibilityRole: Button
    * accessibilityHint: "Cancels changes and navigates to the previous page"

**Comment by digitalken** [comment]
PASS 7/15/2021 - Looks good on iOS and Android.  Closing.
