### ISSUE TITLE
Make sure Terms & Conditions check for MHV works for appointments

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#26595]
### User Story
As a user I need to have accepted terms and conditions to access Secure Messaging and Appointments, and if not be directed on how to do that.

This is currently hooked up to work with SM but MHV has indicated that it should also work for Appointments. Since both of those live in the health section it should display when a user goes to the Health page in the app ([reference to unhappy paths mapping](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614017071435/8061f2093dc4679b4b1da3ab3f20423c8f1c8f66)).

### Acceptance Criteria

1. Display an error for the Health page when a user has not yet accepted the MHV terms & conditions. In SM this was triggered by the following API error: `SM135: # 'User is not eligible because they have not accepted terms and conditions or opted-in' `
2. Create UX/UI based on the below design
- Header 2: "You're required to accept the current terms and conditions"
- Content is hard-coded "To accept the current terms and conditions, please go to the My HealtheVet website:  "
3. Hyperlink: "Go to My HealtheVet"
- Selecting this button opens the following link, out-of-app, in the device's browser: https://www.myhealth.va.gov/mhv-portal-web/user-login?redirect=/mhv-portal-web/web/myhealthevet/secure-messaging
4. Mock this out with user +1414

### Design:
<img src="https://images.zenhubusercontent.com/602e6bbb345265c801d416d8/7c01bce4-1d6a-4539-88df-d1a49b0611f9" alt="Design of terms and conditions screen" width="350">

### Accessibility Implementation Guidelines

- Mark "You're required to accept the current terms and conditions" as Header 2

**"Go to My HealtheVet" link**
- Title= go to myhealthevet (note for dev: please adjust as needed so that it is pronounced like "my healthy vet")
- accessibilityRole= “link”
- acessibilityHint= "accept the current terms and conditions. this page will open in your device's browser"

**Comment by drjecker** [comment]
@ashley-matthews W will need to confirm the MHV URL is ok or if we should use something else as this is no longer a SM only error.

**Comment by narin** [comment]
I'm pretty sure that not signing the T&C for MHV wouldn't block a user from accessing the appointments APIs.  @kreek do you happen to know?

**Comment by kreek** [comment]
@narin only requirement for appointments is LOA3, so if not signing the T&C doesn't take away that status then they'd still have access.

**Comment by narin** [comment]
Thanks @kreek.

@drjecker @ashley-matthews We can probably close this out as MHV's T&C status shouldn't affect appointments.

**Comment by drjecker** [comment]
Great! Closing.
