### ISSUE TITLE
[Research] My VA Action Items: Research synthesis 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26602]
## Background
As part of long-term research and continued improvements to My VA post-launch, and once research is complete for how to better elevate action items in the dashboard, we need to complete a synthesis of our findings.

## Tasks
- [x] Sort and synthesize research

**Comment by tressaellen** [comment]
All synthesis is in this [Mural board.](https://app.mural.co/t/vsa8243/m/vsa8243/1629486960158/8b6f559f0cc35a20d98bf6c5f462ca5f1a022840?sender=tressafurner7646)

Session notes are in [this spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/research/participant-notes/Action%20Items%20Research%20Notes.xlsx), and [github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/action-items-discovery/research/participant-notes).
