### ISSUE TITLE
Address verification screen omits submitted fields and displays placeholder for non-submitted fields

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26604]
## What happened?
**Issue #1**
When attempting to save an "invalid" address (i.e. all required are fields are completed but the address cannot be verified), the "Confirm your address" page excludes the following fields from the "You entered" tile:
    - APO/FPO/DPO selection (when the address is U.S. military)
    - Country (should display as a 3rd line)

**Issue #2**
When attempting to save an "invalid" international address, where only the required fields are filled out, the "Confirm your address" page includes an extra space/comma between the city and international post code. It looks like the app is including this placeholder where the "State" field (which is optional) would be.

## Specs:
- iPhone 11
- TF build: 1.0.0 (14)
- User: +1

## Steps to Reproduce
**Issue #1**

1. On the Mailing Address edit form, enter a seemingly random military address, ensuring that all of the required fields are completed. Example:
     - Check the military base box
     - Country: **United States**
     - Street address line 1: **22 Main St**
     - APO/FPO/DPO: **APO**
     - State: **AA**
     - Zip code: **94129**
2. Save the address. This should trigger the "Confirm your address" screen
4. In the  "You entered" section, notice how the address is played back as: 
     **22 Main St
     , AA, 94129**

Notice how **APO** and **United States** do not display, even though both fields were entered in the form.

**Issue #2**

1. On the Mailing Address edit form, enter a seemingly random international address, ensuring that only the required fields are completed. Example:
     - Country: **Armenia**
     - Street address line 1: **15 Main**
     - City: **Yerevan**
     - International post code: **0054**
2. Save the address. This should trigger the "Confirm your address" screen
4. In the  "You entered" section, notice how the address is played back as: 
     **15 Main
     Yerevan, , 0054**
 
The address summary displays an extra " ," between the city and zip code, even though the State field was null. Additionally, **Armenia** is excluded from the address summary (See Issue #1).
    
## Desired behavior
The "You entered" section should display all fields that were submitted in the form. This section should not include placeholders, ie: ` ,`, for fields that are not submitted.

## Acceptance Criteria
1. The "You entered" section should display all fields that were submitted in the form.
     - Any optional fields that were omitted in the form (such as "State" for an international address) should be excluded from the address summary
2. A submitted military address should display in the following format: 
     - [Street Address line 1]
     - [APO/DPO/FPO], [State], [Zip code]
     - [Country]

## Bug Severity
- 4 - low

## Linked to Story
n/a

## Screen shot(s) and additional information
**Issue #1**
![Image from iOS (32).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/25c753b2-9a62-46bc-b360-ec37066ea2a0)
![Image from iOS (33).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d2ebdb28-f7fb-4351-be9a-c54170f6b5b8)

**Issue #1**
![Image from iOS (34).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b838a18d-e329-4e1b-a1bc-0ff4ce0fdef9)
![Image from iOS (35).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9403f23c-1a95-49e8-ac78-b8c147f0a1d8)

**Comment by digitalken** [comment]
PASS 7/8/2021 - Looks good now.  Closing.
