### ISSUE TITLE
[Research] My VA Action Items: Kick off recruiting for research on elevating action items

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26600]
## Background
As part of long-term research and continued improvements to My VA post-launch we need to kick off recruiting for the research  on how to better elevate action items in the dashboard.

## Tasks
- [x] Submit to Perigean
- [ ] Coordinate scheduling/recruiting as needed

**Comment by tressaellen** [comment]
I sent everything to Lauren - we're looking to start testing Aug 19-26.
