### ISSUE TITLE
Create readme for Testing Tools Team Dashboard Data repo

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#26613]
Create a readme for the [Testing Tools Team Dashboard Data repo](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data).

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/37

**Comment by holdenhinkle** [comment]
All done!

**Comment by pjhill** [comment]
Fantastic -- thanks for getting this done!
