### ISSUE TITLE
Monitor Side-by-side Execution of Test Specs Migrated from Nightwatch to Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26616]
# Description
Now that all refactored Nightwatch test specs have been merged, we need to monitor the execution of the Cypress version of these specs for 10 business days in order to ensure that the Cypress spec versions continue to pass without issue.

# Tasks
- [ ] Monitor Cypress version of these specs for failures or unexpected behavior for 10 business days
- [ ] If we go 10 business days without any issue with these specs, then we remove the redundant Nightwatch version of these test specs from the repo

**Comment by CBonade** [comment]
These tests do not seem to be failing on builds and nothing has been reported otherwise.

**Comment by CBonade** [comment]
This monitoring process has been completed and the specs have been removed pending a merge into master.  As there is a separate ticket that exists to actually remove the specs, this ticket should be good to close.

**Comment by pjhill** [comment]
Thanks for monitoring this!
