### ISSUE TITLE
[repo migration]: Careers/Education

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2661]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1PEh6fdd0j8Oq4zzvYZ4ZypxfomgnkHztmqS-hFgWaCk/edit#gid=1851789287

**Comment by billfienberg** [comment]
`vets.gov-team` PR: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20015
`va.gov-team` PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3655

The spreadsheet had 1,089 URLs listed, but the `va.gov-team` PR only has 1,034 files. I'm currently investigating that discrepancy. I suspect that it's possible some of the files in the spreadsheet have been deleted/renamed since the repo snapshot was taken.

Additionally, there were 6 LFS files that were causing errors. I omitted those files from the above `va.gov-team` PR so the review can start sooner rather later.

Reference: https://dsva.slack.com/archives/GQBPKKYQ2/p1574363319032900

**Comment by billfienberg** [comment]
I think this is the same file, but one of them has an extra `Ratings` directory. 
`https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Ratings/Source%20Files/Ratings%20vectors%20-%20Mortar%20Boards.ai`

`https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Source%20Files/Ratings%20vectors%20-%20Mortar%20Boards.ai`

**Comment by billfienberg** [comment]
I think the `Ratings vectors - Mortar Boards.ai` file currently exists in three different directors in `vets.gov-team`. 

1. https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Ratings/Source%20Files/Ratings%20vectors%20-%20Mortar%20Boards.ai
2. https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Source%20Files/Ratings%20vectors%20-%20Mortar%20Boards.ai
3. https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Ratings%20vectors%20-%20Mortar%20Boards.ai

I think `Ratings vectors - Stars.ai` file currently exists in three different directors in `vets.gov-team`. 

1. https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Ratings/Source%20Files/Ratings%20vectors%20-%20Stars.ai
2. https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Source%20Files/Ratings%20vectors%20-%20Stars.ai
3. https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Education/GIBCT/Visual%20Design/Ratings/Ratings%20vectors%20-%20Stars.ai

**Comment by thatmattjohnson** [comment]
It appears that the differential file counts between the migration plan and the migration PR is indeed largely attributable to duplicate files in the migration plan.  Those plus the 6 problematic LFS files total 44; that's not quite the same as the observed difference in count (n = 56) but it's close enough that I don't think it warrants further investigation. I'm going to go ahead and approve both PRs as is; if we encounter any unhandled leftovers we can deal them with post-migration.

**Comment by thatmattjohnson** [comment]
UAT completed for #3655 and #20015; all looks good. Closing this issue.
