### ISSUE TITLE
Send Mental Health Text Messages

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#26610]
The National Suicide Prevention Office ask that facilities provide a monthly mailing to Veterans at high risk for suicide.  Text messaging could be viewed an expansion of the national office requirements. Augusta VAMC was seeking approval to pilot at the facility level. 

The requested message was:

_We just wanted to let you know that you matter. 

If you are currently experiencing a crisis, please text the Veterans Crisis Line at 838255._

OVAC approved the use case and form is attached.

The initial message campaign was sent on 6/4/21. Augusta VAMC will reach out if/when additional messages will be sent.
[https://app.zenhub.com/files/133843125/88977956-fee8-41ca-8e27-9f0ee9134148/download](https://app.zenhub.com/files/133843125/88977956-fee8-41ca-8e27-9f0ee9134148/download)

**Comment by jwowk** [comment]
6/24/21 - Shane referred Aimee Johnson to speak with Dr Cary West on how they could combine efforts on their pilot.

We work for the VACO Suicide Prevention Program within the Office of Mental Health and Suicide Prevention (under Dr.’s Matt Miller & Lisa Kearney).

I met with some of your team members about a year ago to inquire about the possibility of using VEText to outreach prior VHA Veterans who have dropped out of care but are showing as having increased suicide risk per our predictive modeling known as REACH-VET. I believe at the time there was a potential use-case under Primary Care that would allow us to text Veterans and provide them with a phone number they could call to schedule an appointment. 

My colleagues are helping me to reach back to you and find out- is there a cost to a potential series of monthly text messages to Veterans, what is the cost, and what would we need to do paperwork wise or otherwise to try and move forward in this outreach. Then, we can summarize for our leadership to decide if we can move out on this during this FY or next.

Aimee C. Johnson, LCSW 
Program Analyst, VHA Office of Mental Health and Suicide Prevention 
Office: 503-220-8262 ext. 58540  Mobile: 971-998-3543  Email: Aimee.Johnson@va.gov
U.S. Department of Veterans Affairs

**Comment by jwowk** [comment]
7/9 - July messages were sent (24): "The world is a better place because you are in it."

**Comment by kjduensing** [comment]
went through video for another group (telehealth). Will record a new video to use going forward.

**Comment by Kennon-git** [comment]
Justin requesting new templates, reviewing new use cases & current use cases

**Comment by Kennon-git** [comment]
haven't heard about august - will set them up with self service when they do.

**Comment by jwowk** [comment]
Pilot continues on a monthly basis. Closing card.
