### ISSUE TITLE
IA Feedback - Midpoint Review [Healthcare Experience, Check-in MVP]

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#26624]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- We've discussed adding a "< Back" link in the breadcrumb space to allow users to go back in the process. This wouldn't apply to all pages in the flow, likely just the "See staff" page and "your appointment" page.  Once they have checked in, they probably shouldn't be able to go back.  If you plan to implement this in your experience, it must be included in user testing. If you are not planning to pursue, then disregard.  (17)

**Should:**
- There is a disconnect going from an action link that says "Check-in now" (in text message), then landing on a screen with a heading that asks about insurance info.  A consistent indicator that they are in a check-in flow would help connect the steps.  One option is to add a secondary heading to indicate they are in an "Appointment check-in" process. (19)
- If they choose to update insurance info, the heading and content doesn't reinforce what they need to do or that they are not checked in.  Something like "Please see a staff member to complete your check-in.   A staff member will help you update your insurance information and check you in for your appointment." (43)
- ~On the Your Appointment page - are instructions/option needed if that is not the right appointment?  Maybe they had an old link, maybe they showed up at the wrong time or day? Something like "Not the right appointment?  See a staff member to confirm your appointment and complete the check-in process." (12, 110)~ This was discussed during collab cycle meeting, based on LoROTA functionality, the links have a short life span, clicking on old links will give them a error message.  

**Consider:**
- Consider showing the appointment information on the success page as part of the confirmation.

**Comment by mnorthuis** [comment]
Updated above feedback based on conversations in collab cycle meeting.

**Comment by kristenmcconnell** [comment]
@mnorthuis 
- We have worked with Danielle on the back button, which you can see in this wireframe: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/ELj2Yad. You'll also be able to see the implementation soon in our staging review.
- About the disconnect from text to VA.gov, I worked with Danielle on that too. We changed around the landing page as a result: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/GmyvWLY
- We updated the "check in with a staff member" page as well with your suggestion. We are providing more content now on why they need to see a staff member: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/dlbYq5L


- Lastly, about your "consider" item, we asked Veterans what they really wanted to see on the confirmation page. They are more interested in next steps, such as "have a seat and a nurse will come find you" or additional directions. They aren't so interested in appointment information at that point.
