### ISSUE TITLE
Create recommendation for managing non-loader module performance in vets-website

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#26621]
[Source document](https://docs.google.com/document/d/1PYjohfc9TLYKjCMJK2Y1xwXJ5Xed4v00GQ5B0ZTL4QU/edit#)

## Description

The audit turned up a large number of “non-loader modules” occupying the majority of the build time. This is in reference to npm packages being included in applications. The largest offenders are: mapbox, momentJS, and vets-json-schema (wontfix).

### Mapbox

Mapbox is the main culprit for the weight of the facilities locator, which makes that application the second largest in vets-website. The application itself imports mapbox in its entirety.

### MomentJS

There are 294 instances of import moment from 'moment'; in vets-website. moment is a large, deprecated library. Parts of vets-website have migrated to date-fn and a more modular import model, we should promote this more in the system and communicate it to application teams with recommendations on migration.

## Recommendation

The output of this effort should be a recommendation in the form of a document and brown bag session for app teams to optionally follow. While we can’t force them to update their code we can guide them through it to offer advice on improving performance of their applications.

### Mapbox
 
Investigate the mapbox usage to see if any enhancements can be made. If so a report should be delivered to the Facilities team.

### MomentJS

Produce a document and recommendation for migrating from momentJS to date-fn. This one is probably the best suited to pair with a brown bag.

## Definition of Done

- [ ] Mapbox implementation for facilities locator is analyze
- [ ] If any mapbox updates can be made to reduce the bundle size, they are documented and delivered to the facilities team
- [ ] A momentJS->date-fn migration guide is created for and delivered to app teams
- [ ] A brownbag on momentJS findings and date-fn migration is delivered to app teams

**Comment by jhonnyoddball** [comment]
Expired. Closing
