### ISSUE TITLE
Improve Sass Loader Performance in vets-website

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#26620]
[Source document](https://docs.google.com/document/d/1PYjohfc9TLYKjCMJK2Y1xwXJ5Xed4v00GQ5B0ZTL4QU/edit#)

## Description

Sass loader is one of the slower processes uncovered in the audit. Adding Cache Loader cleaned up some build time, but nothing that really moved the needle in a meaningful way (about 15-30 second savings). It also only helps if the cache is set, which is unlikely for a CI build, but helpful for a local build. Because this is pretty minor we should implement it and confirm there are no functional issues introduced.

## Recommendation

Implement [Cache Loader](https://v4.webpack.js.org/loaders/cache-loader/) and verify that there are no ill effects to the applications with that update.

## Definition of Done

- [ ] Cache Loader is implemented and the vets-website output is verified to not have been negatively affected

**Comment by jhonnyoddball** [comment]
`cache-loader` was implemented in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17827). All the results of the improvements are in the PR
