### ISSUE TITLE
Resolving Headers Accessibility Defect

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26628]
##  Description
As part of the staging review for UI Consistency for Global Pages an Accessibility defect was identified which will require the headers to be handled differently. This issues is to resolve on the global search pages. 

## Background/Context
#26335
![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/cc0c4d51-4b7d-49bd-b0e7-27b58ea3009f)

## Acceptance Criteria
- [x] Resolve Header Structure
- [x] Add SR-only tags to comply with 508 requirements

**Comment by srsuddath** [comment]
Changes for this test have been pushed to the review instance, they should be live in another hour or so!
