### ISSUE TITLE
Improve source map generation performance in vets-website

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#26622]
[Source document](https://docs.google.com/document/d/1PYjohfc9TLYKjCMJK2Y1xwXJ5Xed4v00GQ5B0ZTL4QU/edit#)

## Description

Discovered that the [source map generation](https://v4.webpack.js.org/plugins/source-map-dev-tool-plugin/) for a production build is a significant bottleneck. There was a [caching option added in Webpack 5](https://github.com/webpack/webpack/issues/4558) (doesn't help us). This is reflected in the additional chunk assets processing step pausing at 90% build for around 5 mins. At 91% you can see it stepping through each entrypoint generating sourcemaps.

We're currently using SourceMapDevToolPlugin for this, which is a feature built into webpack.

## Recommendation

Replace sourcemap generation with a normal devtool option or find another way to generate sourcemaps that aren't so resource intensive.

If we find that removing SourceMapDevToolPlugin we can also specifically exclude certain files from generating a sourcemap: exclude: ['vendor.entry.js'],

## Definition of Done

- [ ] One of the sourcemap generation methods outline above is implemented and we have verified that there are no side effects to the va.gov output

**Comment by jhonnyoddball** [comment]
After trying different options for [SourceMapDevToolPlugin](https://v4.webpack.js.org/plugins/source-map-dev-tool-plugin/), none of them helped improving the speed nor the performance of the source maps.

Tried removing [SourceMapDevToolPlugin](https://v4.webpack.js.org/plugins/source-map-dev-tool-plugin/) and it reduced the building time, however, we lose some extra features like moving the source maps to the `/generated/` folder.

I think there is nothing that can be improved here
