### ISSUE TITLE
AWS Console Access for [Nichole Harris]

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#26639]
# Description

**In [this prior user request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19690) I received SOCKS Proxy Access and I'm working productively in some tools (e.g. Kibana). However, I believe I still need AWS Console access.  ** 

- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea
- Please provide your name.
   > Nichole Harris
- Please Provide your email.
   > nichole.harris@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >Team Name = Matsumoto
  >Company = Libertyits
  >Role =Product Manager

- Requesting SSH key authorization?
   > ?  (Already have Socks access, still need AWS Console) 

- What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQCbdoJAXJXEOTkbx8+kBY7GlTjacUoQnxjPe1lvROUmsY2F9+J6UgVXjroXk3YxPw3SqdPUh84HEHP/xlSovXCOudLldQPYlvYCt1E5rNgo/YVSRQjLbkWO2iAVinKRwEc1PLe3zaxNwr5sObqNTcohFvqven711D68ZDuDUAiSP70op45rC685H6XO0cD2yG6gB2s8uDja5ZD/z2YwVNT8zQkmWWbq8b0CMwRrBjhvHSTdP8ysd8PajihNmztbka/bWlF9gjG59f3NgSegiCc7fTXcUxb6NrxGQH2g7yPIYRKi+dVE9PBRXOa4Rur57xLXg89svC72ZkXcLPt4XPjt+pzNDUApbTTCR+rZjjYnOLn7EJjbnuXq8edq/TnCRjZ/PeQ/2bL/7IaffWTq5ZfnMBykkrBl7ZxOi4JW4HUIeGKosk/R3PodgtiRXbTFkWWCxVsHtp85pjrEjhSXLiYUM1JjQIT/xBEYrDo16efWFy1yarGWUcoAM7FdPlZY1C0= AzureAD+NicholeHarris@WIN-JO913FR0J10

- Grant AWS Console access?
  > YES 

- What AWS services do you need access to and why? 

 > Once AWS Console access is set up, I'll be submitting a separate ticket request related to accessing Google Analytics information about the VA.gov pages that are related to Forms/Forms Search (which uses my team's API). Soon we will be implementing improvements to drive down the refinement rate for forms search and will need to monitor the refinement rate over time. 
 > Also, as per the original request linked above, our team typically requests access to "S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house" for the purpose of ongoing support of the Benefits-Intake and Forms APIs.

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - can you please review this AWS access request.

**Comment by jhouse-solvd** [comment]
@drorva / @mchelen - pinging again for awareness

**Comment by drorva** [comment]
Approved

**Comment by mydesignrocks** [comment]
AWS access provided and sent the directions to login. closing now... if there are issues, please reachout using /support in slack vfs-platform-support channel.
