### ISSUE TITLE
VETExt: Sending the wrong reminder. 

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#26635]
Can you assist? Puzzled to why a telephone template would have kicked out for a F2F clinic. Everything that I see is set up correctly. 
Veteran phone number is 3202323826.

From: LaFleur, Melissa D. 
Sent: Friday, June 25, 2021 11:25 AM
To: Schmitz, Kayla L. <Kayla.Schmitz@va.gov>
Cc: Kunkel, Tanya M. <Tanya.Kunkel@va.gov>
Subject: RE: VETEXT

 

I will have to look into this because you are correct it kicked out the wrong template, but not sure why. The only clinic tied to the telephone template  is the tele clinic, not the face to face.
 
The F2F clinic is set for our default F2F template. So no idea what caused this. I will send to the developers to see if they can find something that may have caused the problem.
 

From: Schmitz, Kayla L. <Kayla.Schmitz@va.gov> 
Sent: Friday, June 25, 2021 10:28 AM
To: LaFleur, Melissa D. <Melissa.LaFleur@va.gov>
Cc: Kunkel, Tanya M. <Tanya.Kunkel@va.gov>
Subject: RE: VETEXT

Hi Melissa,

Can you take a look at the below patient.

He was scheduled for an in person appointment and got a TCP Notification. 
The Clinic he was scheduled in was “STC AMPUTEE CLINIC”

 

Thank you! 
Kayla

From: Kunkel, Tanya M. <Tanya.Kunkel@va.gov> 
Sent: Friday, June 25, 2021 9:43 AM
To: Schmitz, Kayla L. <Kayla.Schmitz@va.gov>
Cc: Kunkel, Tanya M. <Tanya.Kunkel@va.gov>
Subject: VETEXT

Thanks for checking on this.

Tanya![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/5a9a9186-0421-4ec4-ad13-d33417230e2a)

**Comment by kjduensing** [comment]
at face value, looks like person got the wrong message. Tough to debug - sporadic, one-off.

perhaps someone temporarily changed the template? Only happened 1 day.

Shane has 2nd example - will attach to this ticket.

**Comment by Kennon-git** [comment]
wrong template may have been used - have not had more reports of the same issue.
