### ISSUE TITLE
Create a solution to keep messages from sending past a specific time. 

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#26634]
Thank you Bill! This was helpful. After further review It appears there was an isolated issue on 6/15 delaying VEText appointment reminders. The result was messages being sent late into the night and early the following morning (6/16). This issue has been resolved and since then, messages should be going on time. If you encounter any further issues, please don’t hesitate to reach back out. 

From: Bellis, William P. <William.Bellis@va.gov> 
Sent: Friday, June 25, 2021 11:01 AM
To: Wowk, Justin ( Government CIO) <Justin.Wowk@va.gov>
Subject: RE: Messages Received at Inappropriate Hours.

5025481615

This is her number…she is an employee here.

We have seen some PT responses that made comments about why Texting me at this hour?

NEWLAND,THOMAS JUDSON      9985      5026140391       603198265              1016132702       ROBLEY REX VAMC         C-1c (03/02/2021 07:22)                                           Please watch the time you send messages. It is too late to send messages at 2300.   Jun 15,2021 22:57           No

This is what I have for now.

Need me to try and find others?

From: Wowk, Justin ( Government CIO) <Justin.Wowk@va.gov> 
Sent: Friday, June 25, 2021 10:42 AM
To: Bellis, William P. <William.Bellis@va.gov>; VEText <VEText@va.gov>
Cc: Stefano, Jennifer J. <Jennifer.Stefano@va.gov>
Subject: RE: Messages Received at Inappropriate Hours.

Hello William,

Can you provide the cell number of this patient so we can look into this further? Is it more than one patient this has occurred with?

Thank you,

Justin Wowk
VEText Project Manager
Email:   Justin.Wowk@va.gov
Email:   Justin@docme360.com
Phone:  (240) 367-9626

From: Bellis, William P. <William.Bellis@va.gov> 
Sent: Friday, June 25, 2021 9:45 AM
To: VEText <VEText@va.gov>
Cc: Stefano, Jennifer J. <Jennifer.Stefano@va.gov>
Subject: Messages Received at Inappropriate Hours.

Morning,

We have received some complaints via PT responses that we are sending messages at 0300 hours.

I have checked our settings at none of our clinics are set up for 0300

I was given an example this morning, and the clinic that the message is for is not in my enabled clinics.

Here is the message:

 

As you can see, this message was sent at 0351 am.  This is not sitting well with our Veterans’.  Can someone look into this please?

Thanks,
Bill

**Comment by kjduensing** [comment]
Problem: was a one off issue. had been migrating apps over to rhel 7, 1 was memcached server, host redirected to poitn to new server on rhel 7. Old server taken down prior to domain being pointed to new membached server. VEText trying to hit old server - trying for 30s, then timeout, retry, etc. Introducing delays. Once domain transferred, all was well. Only a problem for a few hours, but appt reminders slowed to crawl. appt reminders didn't finish til late.

fix has been put in place: if fails, doesn't take so much time.
