### ISSUE TITLE
New BE dev orientation

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#26638]
Please reach out and schedule BE dev orientation with `@Kevin Musiorski` and `@Daniel Nalbach`. Kevin reached out, but said "_There is one more GCIO backend dev that started around the same time who also needs this orientation too. His name is Daniel Nalbach. Wasn't sure if you wanted to knock out two at the same time._"

Reference: [New Team Member Platform Orientation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26427)

**Comment by thilton-oddball** [comment]
Orientation set for Friday July 2nd at 2:30 ET

**Comment by jeff2d2** [comment]
@thilton-oddball How did the orientation go? Can we consider this closed?
