### ISSUE TITLE
Send Blood Pressure Check-up Reminder Messages

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#26647]
James J Peters VAMC is requesting the following:

Outreach effort via VETEXT to Hypertensive patients to supplement our "Know Your Numbers Campaign". Encouraging patients to come see their primary care providers to get their blood pressure checked.  We hope to have patients come in to provide education, counseling, & management  of care.  We hope to send messages twice a week , weekly for 2 month duration starting 7/1/2021 to 8/30/2021.

Request to OVAC is pending submission.

**Comment by Kennon-git** [comment]
pending response from OVAC

**Comment by jwowk** [comment]
7/14 - OVAC approved sending of messages. Approved form is attached. Shawn Kingston will reach out when ready to send.

[https://app.zenhub.com/files/133843125/d08d4948-b75c-419e-b878-3674284c218b/download](https://app.zenhub.com/files/133843125/d08d4948-b75c-419e-b878-3674284c218b/download)

**Comment by jwowk** [comment]
Capability exists but site never actually sent messages. If they wish to send in future they can contact VEText support.
