### ISSUE TITLE
[FE] My VA: Enhance My VA tracking to allow distinction between My VA 1.0 and My VA 2.0

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26649]
## Background
We have GA tracking implemented on My VA but we realized in going through UAT we don't have a way of making a distinction between activity on My VA 1.0 which exists fully in production and My VA 2.0 which we were testing in production behind a feature toggle and is on track to begin a phased roll out next week. We need to enhance our tracking to be able to make a distinction between the two.

## Tasks
- [ ] Pass the following event into GA so the activity can be segmented 
```
{
      event: 'phased-roll-out-enabled',
      'product-description': 'My VA v2',
}

```

See this [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1624630427304400) for reference

**Comment by erikphansen** [comment]
@bsmartin-ep We are now sending the following event to GA when users first land on the new My VA dashboard.

```
{
      event: 'phased-roll-out-enabled',
      'product-description': 'My VA v2',
}
```

Is there any validation you can do to confirm it works? If not, we can just call this done and close it.

**Comment by bsmartin-ep** [comment]
I don't see any events in GA yet @erikphansen.  Was this just added today (Jun 29)?

**Comment by erikphansen** [comment]
@bsmartin-ep Are you looking in prod or can you see if this is working in staging? It won't be on prod until later today.

**Comment by erikphansen** [comment]
@bsmartin-ep the additional tracking should be in prod now. A couple of us have access to the feature in prod and just did some clicking around (~4ET on Tuesday, June 29, 2021). So data should show up in GA soon enough.

@ajakabcin do you have what you need to dig into GA and see My VA 2.0 activity compared to My VA 1.0 activity?

**Comment by bsmartin-ep** [comment]
Ah yes @erikphansen. I'm seeing data in both [production](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210629&_u.date01=20210629&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=My%20VA%20v2/) and [non-prod](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20210629&_u.date01=20210629&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=My%20VA%20v2).  

Not sure if this will link correctly, but I [added 2 segments to the All view](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20210629&_u.date01=20210629&_.useg=userhvR59z78SaeiIWkAtY2xIw,userM7_Smm-yRfKfrS43Bf0BZA/) to differentiate sessions with and without the event.

- Sessions with "My VA v2"
- Sessions without "My VA v2"

**Comment by erikphansen** [comment]
Thanks @bsmartin-ep!
