### ISSUE TITLE
New Team Onboarding

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2664]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist

- [x] PM: Attend intro meeting with product support PM
- [ ] Attend general onboarding meeting
- [x] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [ ] Review the [Product Development Checklist] (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/Product%20Development%20Checklist.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf)
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation
- [ ] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [x] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [x] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [x] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [ ] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [ ] Designers: Attend breakout session with @CrystabelReiter @emilywaggoner 
- [ ] Engineers: Attend breakout session with John Paul/ Dan shank
- [ ] Front-end Engineers: Attend deep-dive session with Dan shank
- [ ] Back-end Engineers: Attend deep-dive session with John Paul 
- [ ] PM, Designers and Content Writer(s): Request content and IA intro @meganhkelley 
- [ ] PM and Front-End Engineers: Request analytics intro @joanneesteban 
- [ ] Full team: Request KPI workshop with analytics team @joanneesteban (Once scope is defined)
- [ ] PM Request 508 intro @1Copenut 
- [ ] PM and Engineers: Request load testing @peterhill-oddball 

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by rebeccawalsh** [comment]
@wygonikGCIO It looks like we're missing a Research Onboarding session Lauren Alexanderson. @rileyorr mentioned that it goes over the high level process for research on the team, and she thinks it will be beneficial.

**Comment by emilywaggoner** [comment]
🤔  I think that research deep dive with Lauren was a special one-off -- we've incorporated that content into the UX onboarding deck. Let us (me and @CrystabelReiter) know if you have specific questions we can answer!

**Comment by rebeccawalsh** [comment]
@emilywaggoner Oh gotcha. I don't remember what I learned from where anymore!
