### ISSUE TITLE
[NEW] 10-10 EZ Update Medicaid/ Medicare page 

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#26656]
## User Story

**As a** Veteran, **I want to** accurately answer whether I'm eligible for Medicaid, **in order to** complete the Insurance section of the 10-10EZ form.

### Medicaid/Medicare questions:

[1010EZ_Medicaid_6.28](https://app.zenhub.com/files/133843125/2edb865f-76a9-4c0a-a7b6-bd5bb9138f36/download)

 - [ ] Break Medicaid and Medicare into multiple pages
 - [ ] Remove more information components
 - [ ] Update text on Medicaid question 

Please note the last question of this flow "What is your Medicare Part A effective date?" is dependent on a **Yes answer** to the second question "Are you enrolled in Medicare Part A (hospital insurance)?" if no, skip this question.

**Comment by dat-gcio** [comment]
@Dene-human Here is the review instance [link](http://bee83717a9ddd6c81e58213b7b105c69.review.vetsgov-internal/health-care/apply/application/introduction)

**Comment by Dene-human** [comment]
Looks great! Just one question: Would it be possible to make the "required" on the Medicare question not an orphan? 
![Screen Shot 2021-07-07 at 10 33 29 AM](https://user-images.githubusercontent.com/80857940/124778671-23058580-df0f-11eb-9aa4-15327ff6cb88.png)

**Comment by dat-gcio** [comment]
@Dene-human Unforunately, it is how the form system wraps it, so that it is mobile friendly. On desktop, if the line was shorter, it wouldnt wrap. (deleted some characters from the word insurance)
![image](https://user-images.githubusercontent.com/83595736/124781156-30bc0a80-df11-11eb-9c86-f091d8c46d45.png)

**Comment by Dene-human** [comment]
Yeah I figured. How do you feel about artificial breaks (bumping "insurance" to the next line?) It's probably not good for responsiveness/ consistency, right?

Anyway it's fine. I'm mostly asking out of curiosity.

**Comment by dat-gcio** [comment]
Having arbitrary break points is not a good idea for responsiveness.

**Comment by dat-gcio** [comment]
Validated in staging.
