### ISSUE TITLE
Update homepage copy

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26657]
## Description
Per Content and IA feedback, update appointment list copy when requests are selected in the dropdown.
- Dropdown field label
- Request selection description
- Page title
![26657 scope updated.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1abe4124-2c11-4f11-b1ee-347bb2c359a1)

---

## Acceptance Criteria

Background: the `va_online_scheduling_homepage_refresh` feature toggle is on

Given the user is on the homepage
When they view any of the four appointment lists
Then the call to action and type dropdown copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#homepage-refresh-toggle) 

Given the user is on the homepage
When they view their requested appointments
Then the call to action and type dropdown copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#homepage-refresh-toggle) 
    And the page title is "Requested | VA online scheduling | Veterans affairs"
    And the page design matches the [design spec](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/MylpA97#Inspector)

### Design Assets
**Specs**
All spec copy is FPO. Use copy in the copy doc.
- [Mobile spec](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/MylpA97#Inspector)

## Definition of Done
- All acceptance criteria are met

**Comment by laurenernest** [comment]
Needs further review. Appointments in "request" list also include canceled requests so "open" is not accurate.

**Comment by jenniemc** [comment]
@laurenernest Looking at the [doc copy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#homepage-refresh-toggle), the `requested` dropdown selection is the only one that's missing the modifier "appointment" in the H2 . Currently with the dropdown {Upcoming, Past, Canceled}, the respective H2 reads:
    

> Your appointment
>     Past appointment
>     Canceled appointment

Would it make sense to stay consistent such that the `request` dropdown would have the H2 display: 

> Requested appointment

And the same for the document title to read,  "Requested appointment | VA online scheduling | Veterans affairs"

**Comment by jenniemc** [comment]
Proceeding to complete this ticket per original AC. @laurenernest will create a new ticket with new AC once she hears back from Content.

**Comment by laurenernest** [comment]
Changes validated. closing ticket.

![26657 validation.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/b2bfe6de-d7da-4c37-a325-f8735f032107)
