### ISSUE TITLE
Remove icon bot warning

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#26651]
Whenever a commit contains an icon, the va-vfs-bot adds a comment to our PR's:

```
Icon found
Icons can be decorative, but sometimes they are used to convey meaning. If there are any semantics associated with an icon, those semantics should also be conveyed to a screen reader.

What you can do
Review the markup and see if the icon provides information that isn't represented textually, or wait for a VSP review.
```

This triggers a need for VSP review, which slows down product teams.

If we can't remove these warnings, can we at least disable them while a PR is in draft mode?

**Comment by timwright12** [comment]
@mpelzsherman I've seen enough of these alerts come through that require HTML updates that I'm not comfortable turning this alert off.

I'll look into some options in GitHub actions to see if we can stop it from triggering on Draft PRs.

**Comment by mpelzsherman** [comment]
OK, thanks!

**Comment by timwright12** [comment]
@mpelzsherman  Opened [PR](https://github.com/department-of-veterans-affairs/content-build/pull/365) to update manual checks to run on:

```
  pull_request:
      types: [review_requested, ready_for_review]
```

**Comment by timwright12** [comment]
vets-website PR as well https://github.com/department-of-veterans-affairs/vets-website/pull/17860

**Comment by timwright12** [comment]
This is updated in both [vets-website](https://github.com/department-of-veterans-affairs/vets-website/commit/5295b8322ddaa562b647aebaf6e8e1dd4cfc63b4) and [content-build](https://github.com/department-of-veterans-affairs/content-build/commit/7af48e893fd0efabdf946b53c94f55af0d657a94). Closing out.
