### ISSUE TITLE
Improve reporting of Daily A11y scan in Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26654]
# Description
Once the accessibility scan has been rewritten in Cypress, use the Mochawesome Report Generator that we are using with other Cypress test suites to gather data and report on the state of the Daily Accessibility Scan in the QA Dashboard.

## Tasks
- [ ] Use the [mochawesome ingestion mechanism](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/tree/master/src/mochawesome) we already have to ingest the data from the a11y scan
- [x] Adjust the workflow for the daily accessibility scan to use the Mochawesome report to report results in GHA

**Comment by ddzz** [comment]
PR: https://github.com/department-of-veterans-affairs/content-build/pull/499

**Comment by pjhill** [comment]
The first AC from this ticket --
`Use the mochawesome ingestion mechanism we already have to ingest the data from the a11y scan`
-- was not completed. This may be worked under a different ticket in the future.
