### ISSUE TITLE
Manual Functional Test Dash - Improve test format

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#26661]
## Issue Description
Improve formatting of # of defects by team card -- https://va-gov.domo.com/page/947844944/kpis/details/1602020533

For example, when no defects are logged for a week in TestRail, a placeholder 0 is used in order to maintain calculation integrity. However, the placeholder 0 shows up in the visualization and causes display issues.

For example --
![image](https://user-images.githubusercontent.com/52456633/123650401-9107c980-d7f8-11eb-96ea-fd687dfecd00.png)

---
## Tasks
- [ ] Change card formatting

## Acceptance Criteria
- [ ] Review w/ team leadership

**Comment by holdenhinkle** [comment]
After talking with Jason in Analytics and going over my attempts at fixing this and my findings with Peter, this is the best I can do:

![image](https://user-images.githubusercontent.com/9326247/123688821-7f3a1c80-d820-11eb-9bba-abdc146d2d67.png)

I changed the empty value for 'name' to 'Please Ignore' using an ETL.

Peter found that this is currently a short-coming in DOMO - https://dojo.domo.com/discussion/27281/graph-empty-time-periods

**Comment by pjhill** [comment]
Until a better solution presents itself, we will work with the current state of things.
