### ISSUE TITLE
Beta alert on resources and support landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#26670]
## Beta alert on resources and support landing page

On this page: https://www.va.gov/resources/ 

Can we consider removing the "beta" alert message?  It has been 8+ months and there seems to be enough content that it's no longer technically beta. And the search and sort logic have been successfully improved. (We also don't label other site pages with 'beta' when it's just transitions into 'add more content' mode, since that's the norm on our site.)

**Comment by RLHecht** [comment]
I'll defer to @bethpottsVADEPO and @DanielleThierryUSDSVA if they are good with removing the beta testing alert but I agree that it's been live for a while and we have a fair amount of articles up. Just let me know and I'll remove it and republish the page.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva @RLHecht I was just going to open a ticket for this actually. I do think we can bring that alert down now. I know @johnhashva has expressed this as well, so let's do it. Thanks @RLHecht!

**Comment by RLHecht** [comment]
Done! Moving to validate and will close after after the next deployment.

**Comment by RLHecht** [comment]
Alert no longer on live site. Closing ticket.
