### ISSUE TITLE
CT Redesign: Adjust map search behavior based on zoom level

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26671]
As a developer, I need to update the map based location search functionality to only allow for searching under a specified radius, so that errors do not occur with the search and the map and pins are presented in a user friendly manner.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This work is specific to the location search map functionality.

## Acceptance Criteria:
1. The "Search this area of the map" button is displayed when the map radius <= 150 miles.
2. A "Zoom in to search" button is displayed when the map radius > 150 miles.
    a. The button takes no action when clicked.

## Supporting Artifacts:
1. [Facility Locator](https://www.va.gov/find-locations)
2. Mapbox [documentation](https://docs.mapbox.com/help/glossary/zoom-level/#zoom-levels-and-geographical-distance)
3. Example of Zoom button:
<img width="706" alt="Screen Shot 2021-06-28 at 10 52 19 AM" src="https://user-images.githubusercontent.com/48260534/123657620-f52d8c00-d7fe-11eb-97b3-1766ecaabc23.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17756

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1972&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
