### ISSUE TITLE
Meta title tag format on resources and support should follow style guide formatting

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#26679]
## Meta title tag format on resources and support should follow style guide formatting

The meta title on public website pages should use the [VA.gov content style guide formatting](https://design.va.gov/content-style-guide/seo#title-tags): 

`Use The H1 And Put It In Initial Caps For The Meta` | Veterans Affairs

In the example below, there appears to be an extra pipe | and the meta title tag isn't using Initial Caps (Each Word Is Capitalized For Meta Title Formatting). 

AC:
- [ ] Extra | is removed on the RS meta title format. (Leave this for VAMC pages, which have an exception.) 
- [ ] The H1 text before the |  is formatted in the FE with Initial Caps. 

### Screenshot example: 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/107995a0-39b2-494a-981a-5e668e042a08)

**Comment by brianalloyd** [comment]
Scrubbing into this issue, aligning to Sprint 51.

**Comment by kelsonic** [comment]
Related tickets:
#26679
#23082
#24383

**Comment by brianalloyd** [comment]
@kelsonic as discussed, the fix in place should fix all issues sitewide, is that correct?

**Comment by kelsonic** [comment]
Almost 99% of cases, yes, EXCEPT some of the VAMC pages modify their title tags with javascript at some point during the build and I have no idea 1) why those edge cases are in the code and 2) where those edge cases live in the code, so I'm not sure how to tackle them, we can do it by a case by case basis if it pops up in the future I think

**Comment by brianalloyd** [comment]
Concur, thanks @kelsonic.  I've reviewed and am closing this out in support.
