### ISSUE TITLE
Access for Nick Osmanski

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#26687]
# Description

- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product. Access needed for: dev, staging, prod, CI environments and Jenkins.

- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Nicholas Everett Osmanski
- Please Provide your email.
   > nick.osmanski@amida.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA-VAMC-UPGRADE / VAMC-UPGRADE
   > Role: UI/UX Designer
   > Company: GovernmentCIO

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAyPXEYJZdHeFGdoQ/OIe+O5K2EUe33XEw/iLQkWQ14/WJqu5pfW1VihsRXVXsXcLQqH4wl8meS85hkG/QWAH34LPJFf2Q0O1U9i6Gfw32WHq4/Elxhb9/EkXf4b1RN5xwqC8yeKFf1CeLG9kj5PspwDIKUi2BKoZALs4oh5SeLVGH/HSEs47VA4SfWdx0/PVT6A/DRSqm/tV98tKYQH6b0HCHQQX/UdgoI6SkByzOMG4di82vT1wJRdg0jVN4nP3FnfDw8G1GgmE4PsHlNJJQ8m2kSz0NPazzIw3m9pKIul4lmXry3Frz1XUYJHVa0Qc1d9TCazG+BhujIJiN4MrVTpta1bd48dPfNwTdMlXb66+RRkEijHVI/l0niDhb+Ys3u6RHH0g3qnFF50+gQDiYUQWHDFQ8bXzmmgxZTFMMAarfWrs178nvslhPLmV1Yt99DmDI60L7RszWLrXoVMdbln5ZDeFQ/Mg1YawDlV7bh8KFVkbMQakKzZ7xEW6QM8M= nick@Amidas-MacBook-Pro.local
```

- Grant AWS Console access?
  > NO

**Comment by mleclerc00** [comment]
@nicko-amida 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by nicko-amida** [comment]
@mleclerc00 Alright thanks!
