### ISSUE TITLE
Access for Nathaniel Buck

### ISSUE THREAD

**Issue by nathanielbuck** [department-of-veterans-affairs/va.gov-team#26696]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Nathaniel Buck
- Please provide your name.
   > Nathaniel Buck
- Please Provide your email.
   > nathaniel.buck@gmail.com / nathaniel.buck@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > My Education Benefits Team, Front-End Developer, Accenture Federal

- Requesting SSH key authorization?
   > **Yes**
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEtO0ycgWpq9/MxbVbghFetcFtlZxqFqUnUmr0zaEd6Jc6EZVOCg7QIIy1PS8cT1/RJqqNHaJNDFhAI9OHXld2urOhGLr/131UATmLgP0BfdR7kZhRzBKMBEPUtgOXtyfLDzDsFimjvEwKRt60OeiqctsW45RzibR/4ucCKh8vs6p91rvg7RbU/Te/czB5NO7t5+DXdGdzVWF7bqlL5qoyeb113Zxrk6dCO4SSPMtIoyRxIeC3KgD1nVQ3cryQ7xIThUUodO/T7VAE/dzUOXKQH/iEuGnBVdyxZOGsI4RSi4Bn+OLrVzsNZzdHcPp/ZfVHIc1xNMcGgLsnfgh8sR3lG0tFTLEpixrXxUtKZYOSFg83x+Q9hKQqrFnPBVZWAHu3C8UuQnIwip6FIuOV49wtVM6xS/rh9NpqjXfzg2t41r+WMryGVeh8RkU22Mavk7RGKYTnIdu3QQT6ScbrszANUVzV1dmAxr81G1V5A0QvQVWON/ru5Wj38+z5Qcv8Yo8= nathaniel.buck@AFSMWS9LPGG76DE
```

- Grant AWS Console access?
  > **No**
  - What AWS services do you need access to and why?
  > **N/A**

**Comment by mleclerc00** [comment]
@nathanielbuck 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
