### ISSUE TITLE
Edit Draft Compose

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26699]
## User Story
As a user, I want to edit a draft reply message so that I can make updates before sending it.

## Acceptance Criteria
* In the Drafts folder, when a user taps on a message that was a response to an existing message thread, it opens the compose edit screen. 
* Data from the original reply message displays in the Message field
* 'Edit Draft' displays as an H1

Not included in this story:
[Save Integration](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26508)
[Save Success](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26336)/[Cancel Confirmation ](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26333)
## Accessibility Guidelines
* 'Edit Draft' is marked as H1
* Assuming all of the accessibility requirements from the original [Compose a Message form] (https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/20426) and the new [Save button](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26239) criteria 

## Design
![Edit Draft (2).png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/a20ea136-cc7c-497c-b684-ddec4b0cbfc5)

**Comment by digitalken** [comment]
PASS 7/28/2021 - Looks good on Android and iOS.  Closing.
