### ISSUE TITLE
Find alternative solution for sending email from Sentry

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#26694]
## Description

With the migration of Sentry to kubernetes complete, we will need to find a new workflow for sending emails from this service.  The ec2 instance didn't have any special configurations and was sending email requests directly to the internet.  This does not work for the kubernetes instance because the requests are being sent through the TIC and getting blocked at some point along the way.  The difference being that the ec2 instance of sentry was hosted in vetsgov utility (requests not getting blocked from here) and our kubernetes instance in vagov utility.

For example

looking at the ec2 config this will direct the email requests to the container 'sentry_onpremise_smtp_1' which is just a exim4 deployment (https://ubuntu.com/server/docs/mail-exim4)

```
###############
# Mail Server #
###############

# mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp'
# mail.port: 25
```

Since most people are using gmail accounts it will reach out to the internet and find a gmail relay server as seen in the logs

```
xxxx@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.google.com [74.125.142.27]
```

I had set up both postfix and exim4 servers to test in kubernetes as a sanity check but ultimately both fail because any requests sent to any variation of google smtp relay servers is dropped and this can be observed by running a traceroute.

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [x] Configure sentry to use VA SMTP server

## Definition of Done
- [x] Email is being routed from Sentry through VA SMTP server

---

**Comment by mleclerc00** [comment]
Email has been pointed to smtp.va.gov for the time being which seems to work.  But it has been mentioned that this relay server is somewhat unreliable.  Not sure if we wan't to further pursue another route such as using AWS SES.

Boris has directed us to talk to Filip Fafara about VA Notify and the implementation of SES that they use if we feel the need to go this route.

**Comment by jhouse-solvd** [comment]
This has been done. 

Closing.
