### ISSUE TITLE
VAOS Scheduling Flow - 508 Findings

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2670]
This epic will be where we file any 508 findings for the general VAOS scheduling workflow and views.

#Zenhub link
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2670

**Comment by lenaecb** [comment]
@1Copenut - now that we have another 508 happening for VAOS should we close this epic out? Seems like this was earlier in the year when the app wasn't in the state it's in today.

**Comment by 1Copenut** [comment]
@lenaecb Let's close this one, because all of the findings are completed. I'd like to keep the Calendar widget epic open, and I'll roll that into the wider audit epic I create tomorrow when I start work.

**Comment by lenaecb** [comment]
Sounds good. Closing this out.
