### ISSUE TITLE
HLR validation error

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#26715]
Triage HLR Validtion erros

[sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/241/events/468250fb56d647b29fa7a8910b5fe10b/?project=4&statsPeriod=14d)

The first few I looked at looked like this - Seems like we're not forcing people to pick a time.
````JSON
{
argument: time1, 
message: requires property "time1", 
name: required, 
property: instance.informalConferenceTimes, 
schema: {
properties: {}, 
required: [], 
type: object
}, 
stack: instance.informalConferenceTimes requires property "time1"
}
````

**Comment by annaswims** [comment]
id's so that I can look up in-progress forms tomorrow
 id:7c937871-5122-40fe-acea-09a74a127f7f
id:5c3c7269-d05b-4bf1-a263-3f51dcf36c63
id:af064f77-fd72-42fe-b01e-f656e9415e87

**Comment by Mottie** [comment]
Opened a PR with a "possible" fix and a lot more tests. Will verify once I get some save-in-progress data, or if Sentry starts working again.

**Comment by annaswims** [comment]
oof.  This is the entirety of one of the "in progress forms" that attempted to submit.  I didn't redact anything.

````JSON
{
    "informal_conference": "me",
    "informal_conference_rep": {
        "view:contact_representative_info": {}
    },
    "informal_conference_times": {
        "time1": "time1000to1230",
        "time2": "time1230to1400"
    },
    "privacy_agreement_accepted": true,
    "same_office": true,
    "view:disabilities_explanation": {},
    "view:same_office_info": {}
}`

**Comment by Mottie** [comment]
I have no idea how an HLR form would be submitted without any issues, Veteran info or zip code, unless they attempted to reload the review & submit page (maybe)?

We're going to need to push this issue into our next sprint for further investigation.

**Comment by Mottie** [comment]
Still not able to duplicate this issue. Will move to the back log for now.

**Comment by vhenry07** [comment]
Closing. OBE v2.
