### ISSUE TITLE
Audit of Original Claims - 526

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26718]
## Issue Description
Audit of 526 to make sure it is all up to date and synced up with the Design systems

---
## Tasks
- [x] Initial design review 

## Acceptance Criteria
- [x] Documented results.
---

**Comment by kevinstachura** [comment]
Christian and I chatted and the documents are located here: 

Mural: https://app.mural.co/t/vsa8243/m/vsa8243/1625248359834/f8b955857cc277bb4c01ba1f3fb1497964bec4e7?sender=cvalla7693

Google doc / readout: https://docs.google.com/presentation/d/1HS2daQh1efO69WM0LkGTwFjHcjWsg1LxjMBGaWYcH9U/edit?usp=sharing
