### ISSUE TITLE
[FE] Profile: Update DD4CNP "please add your bank info" state

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#26710]
![Screen Shot 2021-06-28 at 3.24.35 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/666ddbcd-dd20-46c1-87eb-965cb3e7c39b)

We should not make a button look like a text link.

Instead this "no data" state should look like the "no data" state when there is missing contact info:

![Screen Shot 2021-06-28 at 3.26.53 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/3a24f85f-77d9-4932-bfa7-41e096685425)

A similar change was made to how we handle the "no data" state for missing contact info in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17668)

**Comment by ajakabcin** [comment]
Confirmed on staging (tested with user 204)
