### ISSUE TITLE
CT Redesign: Create "Calculate your benefits" component for institution profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26725]
As a developer, I need to create a "Calculate your benefits" component so that it can be used in the new CT Redesign institution profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.
3. The indicators specified in the "Additional information regarding your benefits" section are data elements on the current profile page under the "Veteran programs" or "Additional information" sections.

## Acceptance Criteria:
1. The component header is "Calculate your benefits".
2. The component has two sections:
    a. Benefits estimator calculator
    b. Additional benefits
3. The Benefits estimator calculator section includes the current controls and calculations of the "Estimate your benefits" section of the current profile page for non-vettec institutions.
4. The Additional benefits section has the header: "Additional information regarding your benefits"
5. The "Additional information regarding your benefits" section displays the following data:
    a. "Veterans tuition policy"
    b. "Protection against late VA payments"
    c. "Yellow Ribbon Program"
    d. "Veteran Rapid Retraining Assistance Program (VRRAP)"

6. The "Veterans tuition policy":
    a. Displays "No" when there is no policy URL available.
    b. Displays "Yes" when there is a policy URL available.
    c. Displays a "View policy" link that links to the policy URL when there is a policy URL available.

7. The "Protection against late VA payments":
    a. Displays "No", "Yes", or "Contact the School Certifying Official (SCO) for requirements" based on implementation specified in SA3
    d. Has a Learn more link
    e. Displays the following content when the Learn more link is clicked:

    > **Protection against late VA payments**
    > If VA is late making a tuition payment to a GI Bill school, the school can’t prevent a GI Bill student from attending classes or accessing school facilities.
    > 
    > Schools may require students to provide proof of their GI Bill eligibility in the form of:
    > 
    > - Certificate of Eligibility (COE) **or**
    > - Certificate of Eligibility (COE) and additional criteria like an award letter or other documents the school specifies
    > 
    > **In addition, schools can't charge late fees or otherwise penalize GI Bill students if VA is late making a tuition and/or fees payment.** This restriction on penalties doesn't apply if the student owes additional fees to the school beyond the tuition and fees that VA pays. Students are protected from these penalties for up to 90 days from the beginning of the term.
    > 
    > Contact the School Certifying Official (SCO) to learn more about the school’s policy. [Read our policy on protecting students from late VA payments](https://benefits.va.gov/gibill/fgib/transition_act.asp).

8. The "Yellow Ribbon Program":
    a. Displays "No" when the institution does not participate in the Yellow Ribbon Program.
    b. Displays "Yes" when the institution participates in the Yellow Ribbon Program.
    c. Has a Learn more link.
    d. Displays the following content when the Learn more link is clicked:

    > **Yellow Ribbon Program**
    > The Yellow Ribbon Program can help you pay for out-of-state, private school, or graduate school tuition that the Post-9/11 GI Bill doesn’t cover. Schools that choose to participate in the Yellow Ribbon program will contribute a certain amount toward the extra tuition. VA will match the participating school’s contribution, up to the total cost of the tuition and fees.
    > 
    > Veterans and Fry Scholarship and Purple Heart recipients, or their dependents using transferred benefits, are eligible for the maximum benefit rate. Active-duty service members and their spouses aren’t eligible for this program. (An active-duty service member’s dependent child using transferred benefits may be eligible if the service member is qualified at the 100% rate.)
    > 
    > Learn more about [the Yellow Ribbon Program](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/).
    > 
    > Visit the [Yellow Ribbon tool](https://www.va.gov/education/yellow-ribbon-participating-schools/) to find schools that participate in this program.

9. The "Veteran Rapid Retraining Assistance Program (VRRAP)":
    a. Is not displayed when the institution does not have participation data available.
    b. Displays "No" when the institution does not participate in the VRRAP program.
    c. Displays "Yes" when the institution participates in the VRRAP program.
    d. Has a Learn more link.
    e. Displays the following content when the Learn more link is clicked:

    > **Veteran Rapid Retraining Assistance Program (VRRAP)**
    > The Veteran Rapid Retraining Assistance Program (VRRAP) offers education and training for high-demand jobs to     Veterans who are unemployed because of the COVID-19 pandemic.
    > 
    > To learn more about this benefit and see eligibility requirements, [visit the VRRAP page](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/?_ga=2.64501932.269488545.1624886313-1403569758.1603827284).

10. The "Calculate your Benefits" jump link in the header
    a. is replaced with "Calculate your benefits"
    b. scrolls the page to where the header of the "Calculate your benefits" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b4423daa6b9fe67f4bf212e1255422a4b25fb766/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#calculate-your-benefits)
3. AC3 question grouping original implementation: #8404
4. AC7 Original implementation stories: 
    a. #7843
    b. #8095
5. AC9 original implementation stories:
    a. #24373 
    b. #26407

**Comment by dmccurdybah** [comment]
PR:  https://github.com/department-of-veterans-affairs/vets-website/pull/17807

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1981&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging.
