### ISSUE TITLE
Access for Ewaz Farhang

### ISSUE THREAD

**Issue by ewaz-farhang** [department-of-veterans-affairs/va.gov-team#26724]
# Instructions
1. Fill out **Description**
2. Add the label used by your team : DGI33
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Laura Smallwood Ross
- Please provide your name.
   > Mohammad Ewaz Farhang 
- Please Provide your email.
   > ewez.farhang@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: MyEducation Benefit
   > My Role: Tester 
   > Name of Company: Accenture Federal Services 

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here]

```
ssh-rsa  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDW17jkPByT+MD0ejt3aOo9cJFghodbm1JEQqBulC2EwZyMj08y60xMcADsi0vdJWO33XIG0x9Slx/b6nnGDo0r1QNT9mOlpiM0MDD8ci90yvbMhnrNKd4qkvdAMGlBHUgMCmT1SzqbSEcoVrFGRLD6m85Tpr4L2hOPM5cCQxFFLEsnP/Q0sMuEAVM6iE2O57G1sytsaM1CMXJWiXF+B6RoQEFATW3q5GQfRrqR3MkHSf9NobsBxWdz4UXekvAQgAnHaWmiSp52gyx2DEfBDVuoWsOjNITEYjufT0iLMT0WChRfXqqyKFOoXFBqEAjcawLtOryX2rb9FfqdWMofowWlyCDJ3Mq8iVcYqjobMoOLYMGNdjmD+L60AG/DsBKWjysa/6NT7dDhnZUAFU7tZcH/te1zOK/dKwXduFI2MkcaUs399+7993ArJqISlULuECoYCZdKRN/uMGFEOKOAsVDCAk9tfnkyrWizSHjb89HAsqBqQT1PeZiDHU4acKxk7GM= ewaz.farhang@AFSMWYB5TE1WGYX + ewaz.farhang@accenturefederal.com
```

- Grant AWS Console access?
  > No

**Comment by mleclerc00** [comment]
@ewaz-farhang 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
