### ISSUE TITLE
Request accessibility/508 review for VA Online Scheduling (VAOS)

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2672]
## Instructions

1. Click or press the gear icon next to the "Labels" heading on the right. Search for your team in the labels list. If your team is not listed in the Labels menu, please leave a comment after you have created this issue. The Product Support team will create a new label for your team.
2. Text inside `<-- comment -->` blocks will not appear in your issue ticket. These comments offer guidance on what information you should provide for each section.

## Team Name
VAOS / VA Online Scheduling

## Product Description

VAOS is a tool that allows veterans to book, view, and manage VA Healthcare appointments. The tool is built mostly with the form-wizard concept and guides veterans through the appointment booking process, constraining their future options based on their previous answers.

The gist of all the functionality is:
- Directly schedule a VA healthcare appointment
- Request that a VA healthcare appointment be booked for you around a preferred date / time
- Request that a Community Care appointment be booked for you around a preferred date / time
- View your confirmed and requested appointments
- Cancel confirmed and requested appointments

Veterans must be enrolled in VA healthcare (and have used VA healthcare previously) to use the VAOS tool.

## Staging URL and Credentials

The tool is not currently gated in staging. The full flow is not live in staging yet. Whatever is up in staging is available at staging.va.gov/vaos (this is a temporary home).

## Test Plan
Most of the application uses existing design patterns (and specifically patterns related to the form system).

Areas of Specific Concern
- Calendar UI (not in staging): this is a new pattern that is core both 'request' and 'direct schedule' new appointment flows. Existing 508 work on this component is being tracked in #2569 

- Appointment List (https://staging.va.gov/vaos/appointments): not super concerning, but there will be changes to this appointments view interface, mixing several different appointment types into one list. We would like to ensure that the list items make obvious sense to anyone using screen readers, specifically. The changes to the existing Staging UX is being tracked in #2306 .

## Known Issues
Just the calendar so far - see #2569 .

[508 Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=508%2FAccessibility&template=508-issue.md&title=)

**Comment by 1Copenut** [comment]
@markgreenburg I've finished the audit and written all tickets. They're in the VAOS Schedule Flow and VAOS Calendar Widget epics, respectively. I'm moving this ticket for the original audit to close. LMK if you want to schedule another closer to launch or to discuss any questions. Thank you.
