### ISSUE TITLE
Connect Cypress tests to Test Rail to fulfill automated test requirement

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#26728]
##  Description
 We need to connect our existing automated tests to test rail in order to meet the automated testing requirement

## Background/Context

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/20841#issuecomment-854285971
-  #25364

## Acceptance Criteria
- [x] Cypress Tested have been connected to test rail

**Comment by srsuddath** [comment]
The following command is used to sync our cypress tests with our test rail account!

TR_USER="dcoveyduc@governmentcio.com" TR_API_KEY="8v.fL9bwBFD46Li53Li3-ypYC26AgLPTnRU4WL91u" TR_PROJECTID="31" TR_SUITEID="150" TR_RUN_NAME="Typeahead test run 1" TR_INCLUDE_ALL="TRUE" TR_GROUPID="642" TR_FILTER="" yarn cy:testrail-run --spec src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js

**Comment by tlei123** [comment]
Sorry, @srsuddath !  Please re-generate your team's TR **API Key** and **save the new one ONLY within TR** [not here in GH] -- I've just added a label for that in your TR-Project edit-screen [here](https://dsvavsp.testrail.io/index.php?/admin/projects/edit/31/1).

Once done, feel free to Close this ticket.

Thx much for getting this integration done!  :)

**Comment by srsuddath** [comment]
@tlei123 I generated a new API key, but am having a hard time getting to the edit-screen you are mentioning. The link you provided seems to get blocked with a login and then not redirecting me to the desired page.

Can you give me directions for how to get to the edit screen?

**Comment by tlei123** [comment]
@srsuddath , sorry about that!  You can just log in the regular way, then...

1. Copy your API key.
2. Go to your team's Project: https://dsvavsp.testrail.io/index.php?/projects/overview/31
3. Just below the Project Overview page-header, at the top-right of the main panel/column, click the **Edit** button to access the project's edit-screen.
4. In the project edit-screen's **Announcement** text-area, paste your API key.  [You should see the placeholder label I added there yesterday.]

**NOTE**: This **Announcement** is hidden by default, so other teams don't see this on the Dashboard page.  You can just cilck **Edit** again whenever you need to retrieve the API key or Project/Suite ID.

Hope this helps!  Ping me on Slack if you need further info/help.  :)

**Comment by srsuddath** [comment]
![Screen Shot 2021-07-09 at 3 09 03 PM](https://user-images.githubusercontent.com/47081947/125125442-9b16ab80-e0c7-11eb-9fe5-a3db66832d97.png)

@tlei123 Pardon my eyesight, but I am not seeing the option to edit. Is this something that is hidden to some users?

**Comment by tlei123** [comment]
@srsuddath , so sorry!  I just found out from Peter that only Admins can edit TR Projects.  Please just save the key in a plain-text file on your machine for now.  Once I figure out a better place to store it, I'll let you know.

**Comment by srsuddath** [comment]
@tlei123 I am going to close this ticket as we have everything accomplished until we find a better spot to store that API key?
