### ISSUE TITLE
Explore ways to reduce Typeahead suggestions lag

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26721]
##  Description
Work with Platform team to discuss ways to reduce lag

## Acceptance Criteria
- [x] Sam will reach out to platform team to investigate what options we have to address this 
- [ ] Meet with Dror, Mike Chellen, other platform team members to discuss ways to reduce time it takes for typeahead suggestions to be generated and shown to users

**Comment by srsuddath** [comment]
we have opened a ticket to address this issue with the OPS team, https://github.com/department-of-veterans-affairs/va.gov-team/issues/28024
