### ISSUE TITLE
CT Redesign: Create "Getting started with benefits" component for profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26735]
As a developer, I need to create a "Getting started with benefits" component so that it can be used in the new CT Redesign institution profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.

## Acceptance Criteria
1. The section header is "Getting started with benefits".

2. The section has the following sub-sections:
    a. How do I prepare before starting my application?
    b. What documents and information do I need to apply?
    c. A decision with consequences

3. The content of the "How do I prepare before starting my application?" sub-section is:

    > **How do I prepare before starting my application?**
    > ****
    > - [Find out if you're eligible for VA education benefits](https://www.va.gov/education/eligibility/)
    > - Gather the documents and information listed below that you'll need to apply for education benefits
    > 
    > **Note:** To apply for Veteran Readiness and Employment (Chapter 31) or educational and career counseling through Personalized Career Planning and Guidance (Chapter 36), you'll need to use a different application.
    > 
    > [Find out how to apply for Veteran Readiness and Employment (Chapter 31) ](https://staging.va.gov/careers-employment/vocational-rehabilitation/how-to-apply)
    > [Find out how to apply for educational and career counseling (Chapter 36)](https://www.va.gov/careers-employment/education-and-career-counseling/)

4. The content of the "What documents and information do I need to apply?" sub-section is:

    > **What documents and information do I need to apply?**
    > ****
    > 
    > - Social Security number
    > - Bank account direct deposit information
    > - Education and military history
    > - Basic information about the school or training facility you want to attend or are attending now

5. The content of the "A decision with consequences" sub-section is:

    > **A decision with consequences**
    > ****
    > Your decision to apply for a certain educational benefit could impact your eligibility for other benefits. Here are a few factors to keep in mind:
    > 
    > - If you're eligible for more than one education benefit, such as the Post-9/11 GI Bill and the Montgomery GI Bill, you must choose which benefit to receive, **a decision that's final and cannot be changed.**
    > - If you're eligible for the Post-9/11 GI Bill and two or more additional education benefits, you must give up one of the additional education benefits. However, you may remain eligible for the benefit or benefits you did not give up.
    > 
    > [Apply for education benefits](https://www.va.gov/education/how-to-apply/)

6. The "Getting started with benefits" jump link in the header scrolls the page to where the header of the "Getting started with benefits" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/2e85d2f27d0ef2662eaf057733f19ffbeb734bc9/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#getting-started-with-benefits)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17794

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1983)

**Comment by delli-gatti-michael** [comment]
Testing complete

![Screen Shot 2021-07-12 at 3.37.35 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/7976984a-2cfa-4a8e-9f02-742ff0174a7a)
