### ISSUE TITLE
CT Redesign: Update "School Ratings" component of the profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26736]
As a developer, I need to update the "School Ratings" component so that it is consistent with other new components of the profile page on in the CT Redesign sandbox.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.

## Acceptance Criteria:
1. The name of the component is "Veteran ratings".
2. "About ratings" has a horizontal rule between it and the content that follows.
3. The header has a border.
4. The component has a border.
5. The "Ratings" jump link in the header:
    a. is replaced with "Veteran ratings"
    b. scrolls the page to where the header of the "Veteran ratings" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b4423daa6b9fe67f4bf212e1255422a4b25fb766/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#veteran-ratings)

**Comment by ksantiagoBAH** [comment]
pr: https://github.com/department-of-veterans-affairs/vets-website/pull/17843

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1999&group_by=cases:section_id&group_order=asc


In staging.
