### ISSUE TITLE
General Analytics Request for Patrick Bateman

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#26737]
# Metrics Reporting Request

## What this form is for

Use this template to request support for anlaytics that need interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?
Patrick Bateman    

- What team/project is this work for?
COVID-19 Screener / VA CTO Health Team
VA Durham Health Care System
    
- What type of analytics support are you looking for?
Extraction of data from Big Query to support COVID-19 research

## Timeframe for Analytics Requested

What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
June 1, 2020 - present.

## Analytics to Track Down

The dimensions, metrics, and filters from this custom report:

https://analytics.google.com/analytics/web/template?uid=vCx-58-qQ_eExf04o4Csug

## Which Product Questions are you trying to answer?

Not necessarily product questions. A researcher at Durham HCS is interesting in comparing data from our COVID-19 screener with infection rates over time and geography to see if anything interesting pops up.

## Other Helpful Questions to think through
- Who is your audience?
N/A
- Why do you need this data?
See above.
- What are you hoping to find?
See above.
- What is your hypothesis that you're hoping the data will support?
N/A
- What area of the VA are you hoping to assess?
N/A
- How frequently do you need this data?
Ideally just once.

## Link to Metrics
https://analytics.google.com/analytics/web/template?uid=vCx-58-qQ_eExf04o4Csug

## Additional Comments
[Slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1624448747095500)

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@batemapf - link was Slacked to you.  Let me know if I should upload it somewhere off Google.

2020-05-01 an OK start dtae?

For reference in case we need to adjust and re-run...

```sql
SELECT
  PARSE_DATE("%Y%m%d", date) AS date,
  hits.eventInfo.eventAction AS event_action,
  geoNetwork.city AS city,
  geoNetwork.region AS region,
  device.operatingSystem AS operatingSystem,
  COUNT(1) total_events,
  COUNT(DISTINCT CONCAT(CAST(fullvisitorid AS string), CAST(visitstarttime AS string))) AS unique_events,
FROM
  `vsp-analytics-and-insights.176188361.ga_sessions_*` AS ga,
  UNNEST(ga.hits) AS hits
WHERE
  _TABLE_SUFFIX BETWEEN "20200501" AND FORMAT_DATE( '%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) )
  AND hits.type = 'EVENT'
  AND hits.eventInfo.eventLabel = 'covid-screening-tool-result-displayed'
GROUP BY
  1,
  2,
  3,
  4,
  5
ORDER BY
  1 ASC,
  6 DESC
  ```

**Comment by bsmartin-ep** [comment]
Sounds good @batemapf .  OK to close this?

**Comment by batemapf** [comment]
First data pull was so good, I'm back for more! @bsmartin-ep would you be able to run a similar query, but include the fields marked with an X in this sheet, without any aggregation (i.e. line level data / each event on its own line)?

[Google Host Schema.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6778681/Google.Host.Schema.xlsx)

**Comment by bsmartin-ep** [comment]
@batemapf -

I'll Slack you the link to the export.

Not news to you, but...

Standard disclaimer we're mixing session level metrics like `totals.hits` with hit level events.  So avoid directly aggregating these columns.  We will usually CONCAT together a session id with other fields and COUNT DISTINCT that to get our totals and unique totals.

Updated query...

```sql
SELECT DISTINCT
  PARSE_DATE("%Y%m%d", date) as date,
  fullvisitorid,
  visitNumber,
  visitStartTime,
  hits.eventInfo.eventAction as event_action,
  hits.hitNumber as hitNumber,
  totals.hits as totals_hits,
  totals.newVisits as totals_newVisits,
  totals.sessionQualityDim as totals_sessionQualityDim,
  totals.timeOnScreen as totals_timeOnScreen,
  totals.timeOnSite as totals_timeOnSite,
  geoNetwork.region as region,
  geoNetwork.metro as metro,
  geoNetwork.city as city,
  geoNetwork.cityId as cityId,
  geoNetwork.latitude as latitude,
  geoNetwork.longitude as longitude,
  device.mobileDeviceInfo as mobileDeviceInfo,
  device.operatingSystem as operatingSystem,
  device.deviceCategory as deviceCategory,
FROM
  `vsp-analytics-and-insights.176188361.ga_sessions_*` AS ga,
  UNNEST(ga.hits) as hits
WHERE
  _TABLE_SUFFIX BETWEEN "20200501" AND FORMAT_DATE( '%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) )
  AND hits.type = 'EVENT'
  AND hits.eventInfo.eventLabel = 'covid-screening-tool-result-displayed'
GROUP BY
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
ORDER BY
  1 ASC,
  6 DESC
```

**Comment by bsmartin-ep** [comment]
OK to close this @batemapf?

**Comment by bsmartin-ep** [comment]
Confirmed with Patrick we're OK to close.
