### ISSUE TITLE
Notice of Disagreement Opt-in

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26730]
## Issue Description
Updated opt-in language per Board request

---
## Tasks
- [x] Work with Beth to adjust opt-in language

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---

**Comment by sshein** [comment]
Did we get any updates to the questions in this thread? https://dsva.slack.com/archives/CSKKUL36K/p1625081458129100

**Comment by vhenry07** [comment]
Sent email yesterday as mentioned in thread. No response so far. Will update thread when I do,

**Comment by sshein** [comment]
Thanks!

**Comment by vhenry07** [comment]
Blocked until we receive updated language. Sent reminders 7/9.

**Comment by kevinstachura** [comment]
Still no indication of new language for opt-in from the Board. 7/26

**Comment by kevinstachura** [comment]
The changes for opt-in are complete and the design can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28480

**Comment by kevinstachura** [comment]
All change discussions happened on this ticket, and they have been implemented:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28262
