### ISSUE TITLE
Redirect Request - Authenticated Experience, Find VA Benefits redirect request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26747]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
Because the Find VA Benefits feature is not moving over to My VA 2.0, there would have been issues if someone went to the Find VA Benefits selection page and tried to save new settings if they already had My VA 2.0 turned on. We agreed the easiest approach was to kill this feature on My VA 1.0 just prior to My VA 2.0 launch in order to avoid any wonkiness. 

Additional discussion in #25149 and #25071

### Requesting team info
Authenticated Experience
- DEPO Product Lead: @Samara-Strauss (interim, @KevinMHoffmanUSDS )
- Product Manager: @ajakabcin 
- Frontend engineer: @erikphansen 

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : 
        Per discussion in [25071](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25071#issuecomment-847219551), this redirect work can be done any time once our phased launch is complete (roughly mid-July)

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
*/my-va/find-benefits* | */my-va*

### Definition of done
- [ ] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [ ] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [ ] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [ ] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
Hi @ajakabcin,   I'm attaching some analytics for the month of June for the Find VA Benefits tool.  

After reviewing a few stats for this page, one key piece of data is the percent of page views that are entrances.  This tells us how many users are getting to the page from external sources.  The higher that % the more a redirect is needed so users do not get a 404. We can control internal traffic and update or remove links, but we can't control external links.
- Only .73% of the page views are entrances from external sources, which is extremely low.  Over 99% of the page views are users coming from another page on the site (pretty much all coming from My VA).

Based on this, I don't feel that a redirect for this page is necessary.  The content can be taken down and the links to it can be removed with minimal to no impact to users.  Please let me know your thoughts.

**Comment by erikphansen** [comment]
@mnorthuis that matches my expectations as well. If you don't feel the need to set up a redirect, that's good enough for me!

**Comment by ajakabcin** [comment]
Thanks @mnorthuis ! Ditto to what Erik said above - thank you for pulling this info together for us. 

Do we just close this ticket then?
