### ISSUE TITLE
Find a VA Form - Form VA10101, 8824i not in search results

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26755]
## What happened?
Form VA10101 is not found when searching for `10101` on Production or Staging, VA8824i or is found when searching for `8824i` on production – but not when searching for `8824i` on Staging

## Specs:
- Device: Windows, Macintosh
- Browser: Edge, Chrome
- Test User: N/A; unauthenticated

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
Form VA10101 should be listed as the top result when searching for `10101` and VA8824i should be the top result when searching for `8824i`

## Acceptance Criteria
- [ ] Form VA10101 is listed as the top result when searching for `10101` and VA8824i is the top result when searching for `88241i`.  Other forms names that start with VA should follow the same pattern.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by NCHLiberty** [comment]
testing

**Comment by mviterna** [comment]
@MarciMcGuireGCIO My socks access just died today, not sure what happened. I think I see the issue VA88241i and will have a fix in tomorrow for it. On the 10101, can @zacharymorel  confirm that is even in CMS (since my SOCKS is broke)?

**Comment by zacharymorel** [comment]
@mviterna it appears to in the cms. I double checked to make sure it is also published. 

![Screen Shot 2021-06-30 at 9 19 13 AM](https://user-images.githubusercontent.com/26075258/123967374-4024dc00-d984-11eb-934e-92d3bbbd8fc8.png)

**Comment by mviterna** [comment]
@zacharymorel The front end is adding a dash because it looks like a 10-10 form to the code. So it searches for VA10-101

**Comment by zacharymorel** [comment]
Oh weird it shouldn't be doing that; otherwise it would be effecting all the other searches. 
@MarciMcGuireGCIO what env are you testing?

**Comment by zacharymorel** [comment]
Staging isn't currently adding any dashes. 
![Screen Shot 2021-06-30 at 9 33 31 AM](https://user-images.githubusercontent.com/26075258/123969537-52077e80-d986-11eb-96ed-9f0c6c565a9f.png)

**Comment by mviterna** [comment]
@zacharymorel Prod is adding a dash

**Comment by zacharymorel** [comment]
Yeah that's an undesired behavior on prod. Not sure if it is worth it to try to come up with a solution since we are so close to launch.

**Comment by mviterna** [comment]
@zacharymorel Yeah, nothing I can do with the old code on prod. If the new code was on prod, we could have put a temporary tag on the search string to point it to the right one. But yeah, I'd say we just hold off.

**Comment by mviterna** [comment]
@zacharymorel 8824 is interesting....when I call the staging API route directly it comes back fine. no issues. but when I go through the revproxy, it can't find it. I'm still looking into this one

**Comment by MarciMcGuireGCIO** [comment]
> Yeah that's an undesired behavior on prod. Not sure if it is worth it to try to come up with a solution since we are so close to launch.

@zacharymorel -- no need to try to fix this in prod with a deployment coming so soon.  I brought it up to Mark because the same behavior occurs in Staging, and thought it could be remediated via the API.

**Comment by MarciMcGuireGCIO** [comment]
@mviterna worst case, I suppose we can add VAxxxx as a keyword for those forms?

**Comment by mviterna** [comment]
@MarciMcGuireGCIO Once the code goes live in prod, we can fix the 10101 easily with the keyword. I thought I had 8824 figured out, but still looking into it

**Comment by MarciMcGuireGCIO** [comment]
Thanks, Mark!

**Comment by MarciMcGuireGCIO** [comment]
Corrected title and description.  Correct form is 8824i and VA8824i; there is no 1 in that form name.
