### ISSUE TITLE
[Design] Choose preferred method of contact for notifications

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26758]
## User Story

As an authenticated veteran, I want to choose my preferred method of contact, in order to ensure I receive notifications.

The purpose of this story is to design how we might ask for a preferred contact method. We should also find out what, if any, functionality already exists in other forms or in VANotify.

## Acceptance Criteria

- [x] Design for Choosing Preferred Contact Method

**Comment by Dene-human** [comment]
Design system [reference](https://design.va.gov/patterns/form-templates#method-of-contact)


![preferred contact.jpg](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/29a44900-db06-4cbe-ae2f-22d521726820)

**Comment by Dene-human** [comment]
Sketch [files are here](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/yg05Jwy)

The copy will be updated once we know more about the why/how/when applicant will be contacted.

**Questions for the future:**
1. What methods and in what order does the application processors use when trying to reach an applicant for X scenario?
2. What contact fields must be collected? EG. Do we still need to collect mailing/home address if user selects Home phone as preferred contact method? 
3. Would it be useful for the applicant to be able to select more than one contact method? Should we still ask for email, etc. If applicant chooses a different method aka will this be useful to the application processor?

**Comment by mlighdc** [comment]
@Dene-human where are you thinking this would fall within the application flow?

**Comment by Dene-human** [comment]
Good question @mlighdc! It would depend on the above questions:

1. _IF_ HEC team uses all methods of communication and would still like to ask for them (even though not required) this question would go after all contact input fields -After Mobile telephone in current flow
2. _If_ HEC team only needs one contact method, this question would go before all contact info is asked and then only show the input field for the preferred method (making that one required).
3. _If_ HEC team needs address, but only needs home telephone OR mobile telephone OR Email, then this question would go after address and only populate the corresponding preferred contact method after. If user selects mail then we need to decide if we show phone/email input at all.
