### ISSUE TITLE
Speed up cache-busting step of build

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#2675]
In our website build, we have a step to prevent application code and style from being cached after a new version has been deployed. However, that step takes about 45 seconds. We should speed that up so that our deployments are quicker.

**Comment by bkjohnson** [comment]
PR for this: https://github.com/department-of-veterans-affairs/vets-website/pull/10935
Follow-up: https://github.com/department-of-veterans-affairs/vets-website/pull/10948
