### ISSUE TITLE
[Design] 10-10EZ Confirmation Notification

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26756]
## User Story

As an authenticated veteran, I want to receive a confirmation notification when I submit my form, in order to ensure that my submission was received.

The purpose of this story is to determine the design for the confirmation notification for email or text. This would be similar to the existing confirmation screen, but could be sent as either an email or text. 

## Expected Behavior

If an authenticated veteran specifies a preferred method of contact and successfully submits the 10-10EZ form, we will send a confirmation notification using the preference.

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by markfallows** [comment]
Duplicate ticket.  Closing.
