### ISSUE TITLE
[FE] My VA: stop using client-side routing for My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26752]
## Background
Since My VA 2.0 is a single page with no sub-routes we should stop using client-side routing

## Tasks
- [x] Remove this code referenced [here](https://github.com/department-of-veterans-affairs/devops/blob/408d805717fd2f90d26c78bba6eef562046f41e3/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml#L73-L74):

```
path: /my-va
protected: no
```

**Comment by erikphansen** [comment]
Just waiting for this change to propagate to prod. But it looks good in staging.

**Comment by erikphansen** [comment]
looks good on prod.
