### ISSUE TITLE
Evaluate and Analyze Existing Research on Modify Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2676]
## Story
As a member of the eBenefits Team, I want to synthesize the research previously done on the rainbows team as well as our own baseline research.

## Tasks
- Evaluate research, establish completeness
- Pull out baseline research and consolidate it

## Acceptance Criteria
- [ ] Document analysis in an .md file

**Comment by sporeboy** [comment]
Analysis nearly finished for initial round. There is a WIP list here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/research/rainbows-team-686-analysis

A more finished presentation document is available here:

https://xd.adobe.com/view/519b9e01-ef85-4713-6eb7-a4a8b29a2117-27aa/

**Comment by jason-gcio** [comment]
Very well done, thanks Jim.
