### ISSUE TITLE
[Research] Pre-populate fields on 10-10CG for authenticated users

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26762]
## User Story

**As an** authenticated veteran, **I want to** have more information pre-populated into the online 10-10EZ form, **in order to make** the process more streamlined and accurate.

The goal of this story is to:

1. Confirm what information is current pre-populated in the 10-10EZ form
2. Determine what additional items may be added to be pre-populated on the 10-10EZ form
3. Focus on items, such as Service Rated Disability Rating, which could be used in the future to auto-qualify the applicant or to skip other questions.

Examples:

- Service-related Disability Rating (auto qualifier)
- Service History dates, etc.

According to Alayna Abel, the following information _may_ be pre-populated, but we need to confirm:

- Name
- Date of birth
- SSN
- Gender
- Mailing and/or home address

## Acceptance Criteria

- [ ] List values that are current pre-populated in the 10-10EZ form
- [ ] List values that may be added to be pre-populated in the 10-10EZ form
- [ ] Determine which, if any of these pre-popluated values may be used to skip questions or auto-qualify users.

**Comment by dat-gcio** [comment]
Info about disability rating in vets-api:
modules/veteran_verification/VETERAN_VERIFICATION.yml
modules/veteran_verification/app/models/veteran_verification/disability_rating.rb
spec/support/schemas_camelized/disability_rating_response.json

public api looks like this:
{
  "data": {
    "id": "0",
    "type": "disability_ratings",
    "attributes": {
      "combined_disability_rating": 30,
      "combined_effective_date": "2015-02-01T00:00:00+00:00",
      "legal_effective_date": "2015-01-01T00:00:00+00:00",
      "individual_ratings": [
        {
          "decision": "Service Connected",
          "effective_date": "2015-01-01T00:00:00.000+00:00",
          "rating_percentage": 30
        }
      ]
    }
  }
}

**Comment by dat-gcio** [comment]
**Current fields that 1010ez prefill for:**
veteran_full_name: 
gender: 
veteranDateOfBirth: 
veteranSocialSecurityNumber: 
homePhone: 
veteranAddress: 
email: 
lastServiceBranch: 
lastEntryDate: 
postNov111998Combat: 
lastDischargeDate: 
discharge_type: 
swAsiaCombat: 
vaCompensationType:

**Comment by dat-gcio** [comment]
### Fields not prepopulated:

Possible? Needs further research by backend engineer.
Possible spouse info:
app/models/form_profiles/va_21686c.rb
//maritalStatus
//spouseGrossIncome
//spouseNetIncome
//spouseOtherIncome
//spouseFullName
//spouseSocialSecurityNumber
//spouseDateOfBirth
//dateOfMarriage
//sameAddress
//cohabitedLastYear
//provideSupportLastYear
//spouseAddress
//spousePhone

//mothersMaidenName
//cityOfBirth
//stateOfBirth
//isEssentialAcaCoverage
//vaMedicalFacility
//isSpanishHispanicLatino
//isAmericanIndianOrAlaskanNative
//isBlackOrAfricanAmerican
//isNativeHawaiianOrOtherPacificIslander
//isAsian
//isWhite
//mobilePhone
//discloseFinancialInformation
//dependents
//veteranGrossIncome
//veteranNetIncome
//veteranOtherIncome
//deductibleMedicalExpenses
//deductibleFuneralExpenses
//deductibleEducationExpenses
//isCoveredByHealthInsurance
//providers
//isMedicaidEligible
//isEnrolledMedicarePartA
//medicarePartAEffectiveDate
//purpleHeartRecipient
//isFormerPow
//disabledInLineOfDuty
//vietnamService
//exposedToRadiation
//radiumTreatments
//campLejeune

Should not autofill
???wantsInitialVaContact
???privacyAgreementAccepted
???veteranHomeAddress // The mailing address is already prefilled

**Comment by dat-gcio** [comment]
Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/27279 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/27278

**Comment by mlighdc** [comment]
@dat-gcio I couldn't tell from your notes if you were able to see what other data fields might be available via VA Profile (which is different from profile on va.gov). Thanks.
