### ISSUE TITLE
[Research] Using VANotify to send confirmation and reminder notifications

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26760]
## User Story

**As an** authenticated veteran, **I want to** receive reminder or confirmation notifications on my application, **in order to** complete or confirm that I have completed my application.

The purpose of this story is to research how we might configure and use VANotify for he following:
- Setting a preferred format for notifications (eg. Email or Text)
- Triggering a notification (eg. on Confirmation of submission)
- Scheduling a notification (eg. Reminder to complete and submit the application)
- Determine any opt-out rules that might apply to these use cases

Notes from [VANotify Lunch & Learn](https://docs.google.com/presentation/d/1l2sHoFhQ3or73xO7Z_Ia0Vj_NhbEUMWRJbuFkeo0X2I/edit?usp=sharing) session.

## Acceptance Criteria

- [X] Have enough information and understanding of the VANotify system to begin designs for how we may us VA Notify for Confirmation Notifications.
- [X] Have enough information and understanding of the VANotify system to begin designs for how we may us VA Notify for Reminder Notifications, or a decision about whether reminders can be included in the initial feature.
- [X] List of question for further research (if necessary), or understanding of contacts and documentation available to gather answers to future questions.

**Comment by tchrisdyer** [comment]
Adding a link to my notes from the April 9th [VANotify Lunch and Learn](https://docs.google.com/presentation/d/1l2sHoFhQ3or73xO7Z_Ia0Vj_NhbEUMWRJbuFkeo0X2I/edit?usp=sharing) session.

**Comment by dnalbach** [comment]
VANotify is a service created by forking a GovUK project and creating custom infrastructure for it to make a US VA version, branded as VANotify. 

- https://github.com/alphagov/notifications-ruby-client
- https://docs.notifications.service.gov.uk/ruby.html#ruby-client-documentation

### Official VANotify docs and repos

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify
- https://github.com/department-of-veterans-affairs/notification-api
- https://github.com/department-of-veterans-affairs/notification-utils

The templates used by the VANotify system are written in Jinja and are stored in a separate repo here:
https://github.com/department-of-veterans-affairs/notification-utils/tree/master/notifications_utils/jinja_templates

### VETS-API

The `vets-api` already has a working example of the VANotify system. Here are various pieces of it:

The forked ruby gem:
https://github.com/department-of-veterans-affairs/vets-api/blob/987e2e43934c71f3bca70b5a573f43f4798ced68/Gemfile#L99

The settings placeholder (overwritten by environment)
https://github.com/department-of-veterans-affairs/vets-api/blob/987e2e43934c71f3bca70b5a573f43f4798ced68/config/settings.yml#L902

The betamocks config (inside vets-api)
https://github.com/department-of-veterans-affairs/vets-api/blob/987e2e43934c71f3bca70b5a573f43f4798ced68/config/betamocks/services_config.yml#L564

The lib folder where the service is declared and the ruby client internals are overwritten to allow different options:
https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/va_notify
https://github.com/department-of-veterans-affairs/vets-api/blob/987e2e43934c71f3bca70b5a573f43f4798ced68/lib/va_notify/service.rb#L34

An example controller endpoint queuing up an email job in sidekiq:
https://github.com/department-of-veterans-affairs/vets-api/blob/987e2e43934c71f3bca70b5a573f43f4798ced68/app/controllers/v0/ppiu_controller.rb#L52

The email job definition:
https://github.com/department-of-veterans-affairs/vets-api/blob/987e2e43934c71f3bca70b5a573f43f4798ced68/app/workers/va_notify_dd_email_job.rb

**Comment by dnalbach** [comment]
We have learned a lot about the VANotify service and are meeting with that team later this week. We now know enough to close this research ticket and open a Design ticket to plan out the work needed to implement our own version of it.

**Comment by tchrisdyer** [comment]
We met today with the VANotify Team (Beverly Nelson - VA PO, Maria Becker - PM, Filip Fafara - Tech Lead). Some of the key takeaways were:


* **Confirmation Notifications**
  * The VANotify Team does NOT recommend sending Text confirmations.
  * The confirmation email is transactional so it does not require any additional opt-in
  * We would simply need to draft the confirmation email, define the dynamic elements, and get it approved
  * To trigger it, we would send email address and Profile ID (not ICN)
    * Note: we would want to make sure the submission is a success before sending.
  * [VANotify Intake Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=bevnobev%2C+miabecker&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D) can be created -- although there may already be one created.
* **Reminder Notifications**
  * Existing [VANotify Ticket](https://app.zenhub.com/workspaces/vanotify-business-intake-board-606cc5c49392c900162c3971/issues/department-of-veterans-affairs/vanotify-team/23) for Reminder Notifications.
  * Existing [Caregivers Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23609) for Reminder Notifications.
  * Kevin had already discussed a potential design in the ticket above.
  * The VANotify team feels this might be a better use case for texts and emails.
  * Texts need an opt-in
     * May be covered under VHA privacy policy
  * The costs are much higher for Texts. The LOB would have to budget for that.
  * VANotify team is working on Preferred Method of Contact working with VA Profile. It will be very granular.
* **Priorities**
  * Ming would like to focus on the Reminder Notifications over the Confirmation Notifications since the reminders would likely increase submissions.

**Comment by dnalbach** [comment]
After the meeting, we discovered that the 1010EZ is currently queuing up a Sidekiq job for submission of the form if the user provided an email address. The job will attempt to submit several times, and if successful, nothing visible happens to the user. If it fails repeatedly and exceeds the retry limit, then the user will be sent a failure email to the address provided. This is done via an ActionMailer template that directly sends through Granicus. It does not use the newer, preferred VANotify system. If the user did not provide an email address, the EZ form submission occurs immediately rather than through a Sidekiq job, and there are no retry attempts. The front-end client always receives a success response from the vets-api regardless of the success/error response from the Enrollment System upon submission.

**Comment by bevnobev** [comment]
tagging @megansiddle, @nathanbwright, @Dene-human  and @SKasimow for visibility
