### ISSUE TITLE
Harassment Reporting Tool [Form Mockup]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#26765]
## Issue Description
_ORDMI PIFs have never actually produced any design mockups for the harassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled.  We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems.  The designs will be used for both design intent review and initial FE build of the prototype_

Here's the layout: Scope is Veterans/Beneficiaries and were only build for the top three situations: 1.Sexual Assault 2. Sexual Harassment 3. Harassment (other then Sexual) as identified here:
![Screen Shot 2021-06-23 at 10 17 21 AM](https://user-images.githubusercontent.com/70410912/123134771-5e338f00-d40e-11eb-8e08-9bc4db0f00cc.png)

Artifact is Here: 
[05_13_2021 Arch_Use Cases.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6644644/05_13_2021.Arch_Use.Cases.pdf)

Example IG Harassment Reporting Tool:[ HERE ](https://www.va.gov/oig/apps/info/hotlineGeneralContactForm.aspx?cc=s)

[Draft Design Sketch Review](https://www.sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

## Design tasks
- Ensure the page is styled according to design spec. 
- Ensure any questions are pushed to PIF partners to get clarification 
- Document feedback on ticket for follow up and review purposes 
- Ensure we follow VA.gov system system recommendations to ensure a streamlined system is achieved 
- Be prepared to share design mockups for review with team and collaboration cycle checkpoints 

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling 
- [x] Designer posts link to designs for review by PIF/PM/PO
- [x] Feedback is documented on ticket for follow up and review 
- [ ] Designer be prepared to share designs in support of VSP collab cycle reviews
- [ ] Designs are prepared with full mockups in support of FE build requirements

**Comment by cindymerrill** [comment]
Gave Cassandra a lot of feedback on use cases and form mockup.

**Comment by callen2563** [comment]
Both mobile and desktop first drafts have been mocked up but will be continuing edits during collaboration with content.

[HRT mobile and desktop designs](https://sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

**Comment by brianalloyd** [comment]
This work is completed, shifting 2nd draft to new ticket in support.  Validated and closing.
