### ISSUE TITLE
VAMC options for Veterans to communicate with the VA

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26770]
## Problems to be solved
There are a growing number of ways for Veterans to connect with clinicians for health related needs. It may be confusing for Veterans to find the right one for their needs and/or differentiate between the tools. 

New options for contacting the VA are becoming available and need to be added to the VAMC pages. Before we can determine the right experience for Veterans, we need to understand both the individual options and the landscape

## Background

The following options are in addition to 

- Phone numbers
- Crisis Line 
- Mental health phone numbers 

Both the crisis line and the display of mental health phone numbers are legislatively mandated and need to remain on the site. (The location of the numbers might be adjusted if recommended.)

**VA health chat** (Discovery effort in #27686)
- SME: Kathleen Frisbee (Kathleen.Frisbee@va.gov), manages VA Health Chat
- Wilmington is one of the pilot sites
- National experience (open in browser or in app)
- **Chat live** with a clinician for issues such as
   - Medical advice for a minor injury or illness
   - Medication questions
   - Lab/imaging test results
- [VA health chat](https://mobile.va.gov/app/va-health-chat)

Link to [health chat discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md)

---

**Secure messaging** (Discovery effort in #27687)
- SME: Patrica Henry - Product Owner (Patricia.Henry@va.gov)
- SME: Tracey Martin (Tracey.Martin@va.gov), My HealtheVet coordinator
- **async service** for non-urgent, non-emergency health-related questions, such as 
  - Providing updates on one's condition
  - Requesting VA referrals, test results, and prescription renewals
  - Managing appointments
  - Asking routine administrative questions 
- Response time ~24 hours
- [Secure messaging](https://www.va.gov/health-care/secure-messaging/)

Link to [secure messaging discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/secure-messaging-discovery.md)

---

**VA health connect** (Discovery effort in #27688)
- SME: Rick Fox
- Clinical contact center
- 24 hours live by phone
- Regional phone numbers (mapped to health system)
- slow roll-out, will be available nationwide 

## Potential considerations for options for displaying on VAMC
- Present at facility or system level?
- Include with phone number for location?
- Present within accordions?
- Program page (like care coordinator?)
- What information should be displayed to help Veterans understand when to use option/what to expect?
- How to handle locations without the service

## Questions 
- What is the right experience for Veterans?
- What do they need to know about each service?
- How is it different than the other options?
- Where does each option fit within the Veteran journey?
- What is the situation the Veteran is in when he/she uses the service?

**Comment by mmiddaugh** [comment]
See also
- [VSA UX Transition document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/product-transition-doc/vsa-ux-transition-doc.md) | March 2022 
- [VA health connect communications feature doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/product-transition-doc/feature-docs/va-health-connect-communications.md) | March 2022

**Comment by davidmpickett** [comment]
Closing as all tickets are colmplete
