### ISSUE TITLE
Surface VVC Group appointments to vets-website

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26771]
## Description
With [VAOSR-1274](https://issues.mobilehealth.va.gov/browse/VAOSR-1274), the groupAppointment flag from VVS should be passed through MAS. We would like to show Group VVC appointment details in the frontend.

---

## Acceptance Criteria
- [ ] FE can identify group VVC appointments

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ajmagdub** [comment]
the groupAppointment flag is currently being passed through MAS and Vets API to the Vets Website. The field name is group_appointment in the VVSAppointment object.
