### ISSUE TITLE
[WIP] VVC Group appointment details page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#26772]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] CONTENT - Content matches the [copy doc](#) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 

### Designs
- Mobile
- Tablet
- Desktop

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
@jbalboni Could you drop in a screenshot of what a group appointment looks like currently in homepage refresh?

**Comment by jbalboni** [comment]
@laurenernest As far as I can tell, group appointments are only differentiated by the groupAppointment flag and having more items in the patients list. We ignore those, so a group appointment would look like any other video appointment from VVC (at home or I think even ATLAS).

![Screen Shot 2021-07-14 at 4 58 44 PM](https://user-images.githubusercontent.com/634932/125691993-fb39becb-6c5b-4829-8829-07dfc3454cdc.png)

**Comment by ldelacosta** [comment]
Ticket is old. We will open a new ticket to update VVC details. Closing out the ticket. cc: @JRRoof
