### ISSUE TITLE
Investigate Form Builder Capabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2679]
## Story
As a frontend engineer I need to fully understand what is available in the form scaffolding and what possible extensions so that I can better implement newly form functionality.

[Link](https://react-jsonschema-form.readthedocs.io/en/latest/) to original form docs

## Problem Statement
- The 686 has many workflows, not all of them required. It would be nice to build a 'form of forms' where sections are toggled in/out based on user input. The form config currently accepts a `depends` property that has the ability to toggle entire pages. Would this suffice or would it need to be extended to support a 'form of forms' pattern? 

## Considerations 
Here is a [markdown file](https://github.com/usds/us-forms-system/blob/master/docs/README.md) that has some documentation

## Tasks
- Explore extending form builder functionality
- Investigate unused functions in the form builder:
  - Are there any functions that we want that are not readily available (like toggling sections using `depends`)
  - What is on the wishlist that is not being done in the 686 form? (should we make a quick test form that addresses all the different types of functions we anticipate being in the form?)

## Acceptance Criteria
- [ ] Document potential functions that were previously unknown.

**Next steps**
- This could generate other tickets

**Comment by micahchiang** [comment]
Documentation on the forked version of the form builder USDS has: https://github.com/usds/us-forms-system/blob/master/docs/README.md
