### ISSUE TITLE
CT Redesign: Create "Cautionary information" component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26794]
As a developer, I need to create a new "Cautionary information" component so that it can include the consolidated information  and match the design of the other new components of the profile page on in the CT Redesign sandbox.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.

## Acceptance Criteria:
1. The name of the component is "Cautionary information".
2. The component has two sub-sections:
    a. "Alerts from VA and other federal agencies"
    b. "Student feedback"

3. The sub-section "Alerts from VA and other federal agencies":
    a. Has the header "Alerts from VA and other federal agencies"
    b. Displays the caution flags
    c. Displays the content:

    > Before enrolling in a program at this institution, VA recommends that potential students consider these cautionary warnings.  Caution flags indicate that VA or other federal agencies like the Department of Defense (DoD) or Department of Education (EDU) have applied increased regulatory or legal scrutiny to this program.
    > 
    > To learn more about Caution Flags, [visit the About this Tool page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/c9a6c5bdb23e59223f8e25c379a1e4d94e1bac07/products/education-careers/school-comparison-tool/redesign/design).

4. The "Student feedback" sub-section:
    a. Has the header "Student feedback"
    b. Displays the number of student complaints: "X student complains in the last 24 months".
    c. The number of student complaints has a Learn more link.
    d. When clicked, the Learn more link displays the following content:

    > **Student complaints**
    > 
    > This is the number of closed, Principles of Excellence-related, complaints submitted to VA through the GI Bill Feedback system for this school.
    > 
    > To learn more visit the [VA GI Bill Feedback Tool](https://www.benefits.va.gov/GIBILL/Feedback.asp).

    e. A table displays a summary of the total number of student complaints.

    f. A table displays a summary of the complaints by type.

5. The table that displays a summary of the total number of student complaints has a header with the following columns: 
    a. [blank]
    b. "**This campus**"
    c. "**All campuses**"
  
6. The table that displays a summary of the total number of student complaints has a single data row with the following:
    a. "All student complaints"
    b. # of complaints at this campus
    c. # of complaints at all campuses

7. The table that displays a summary of the complaints by type has a header with the following columns: 
    a. "**Complaints by type** (Each complaint can have multiple types)"
    b. "**This campus**"
    c. "**All campuses**"
    d. This table only appears when there is 1 or more complaints. 

8. The table that displays a summary of the complaints by type has a data row with the following if the complaint type exists:
    a. A complaint reason type:
    > Financial Issues (e.g., Tuition/Fee charges)
    > Quality of Education
    > Refund Issues
    > Recruiting/Marketing Practices
    > Accreditation
    > Change in degree plan/requirements
    > Student Loans
    > Grade Policy
    > Transfer of Credits
    > Post-Graduation Job Opportunities
    > Release of Transcripts
    > Other

    b. # of complaints at this campus for the specific reason
    c. # of complaints at all campuses for the specific reason

9. The "All campuses" table header in both tables is a link that displays the following content when clicked:

    > **VA Complaints (all campuses):**
    > 
    > The number of closed, Principles of Excellence-related, complaints for schools with the same six-digit OPEID code.

10. After the data tables, there is a link to the feedback tool:

    > [Submit a complaint through our Feedback System](https://www.va.gov/education/submit-school-feedback/introduction)

11. The "Cautionary information" jump link in the header scrolls the page to where the header of the "Cautionary information" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b4423daa6b9fe67f4bf212e1255422a4b25fb766/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#cautionary-information)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17833

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2003)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
