### ISSUE TITLE
[Research] Create conversation guide for the Education Dashboard MVP usability study

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#268]
## Goal
Create a conversation guide for the Education Dashboard MVP usability study.

## Acceptance Criteria
- [x]  Create a conversation guide
- [x]  Review with the team

## Definition of Done
- [x]  Approved by team
- [x]  Linked to the Education Dashboard MVP Research Plan

---
View [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/Education-Analytics-Research-Plan.md).

cc: @amycesal @joanneesteban

**Comment by smoonpeyes** [comment]
@joanneesteban @amycesal @emilywaggoner 

A draft of the conversation guide is here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/conversation-guide.md

Please review and let me know if I've missed anything. Thank you!

**Comment by joanneesteban** [comment]
This looks great! I think you covered most of it. The only thing I can think of is perhaps asking if they would want a reminder email or ping that the dashboard is ready.
