### ISSUE TITLE
Remove type ahead phased roll out event

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#26808]
As we're now at 100% usage, please remove the Type Ahead phased roll our event.

```js
{
          event: 'phased-roll-out-enabled',
          'product-description': 'Type Ahead',
}
```

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/components/SearchMenu.jsx#L62

Thanks!

**Comment by srsuddath** [comment]
ticket has been merged and event has been removed
