### ISSUE TITLE
[Backend] Send MCP team data contract for how we will filter data by user

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#26805]
**Description**
We will be fetching a user's statement information from the VBS API. The VBS API's DynamoDB does not have data partitioned by user identity. It is instead partitioned by either `edipi` or a `DFN` number (which is a unique identifier combining a user and a facility).

We will need to provide the VBS API a list of identifiers to filter the data down.

**A/C**
- [ ] Design the data contract / parameters for how we will provide the identifiers
- [ ] Provide the design to the VBS team.

**Comment by LindaLi123** [comment]
Wait for verification for DFN parsing.

**Comment by kevinmirc** [comment]
Closing. LibertyIT team updated the swagger docs to include an endpoint to query by both edipi and vista account number:
```
POST /vbsapi/GetStatementsByEDIPIAndVistaAccountNumber
{
  edipi: string,
  vista_account_numbers: number[]
}
```
