### ISSUE TITLE
Access for Liam McCormick

### ISSUE THREAD

**Issue by lmccormickafs** [department-of-veterans-affairs/va.gov-team#26817]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Setting up local dev environment for MyEducationBenefits team
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Liam McCormick
- Please Provide your email.
   > Liam.mccormick@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > MyEducationBenefits, Tester, Accenture Federal Services

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOUqcyECraomI5xbYuJxtgHUuF8mw2H+LCdqDxryISAWXl6QqVlNtbcC6QMF5exMp2+M3+sgeVbtC+IMIGy4aAL4sSj15g/4z5HF2soVr7Gsh66BDw4bWgNZJBO+qzi+zAHiaAG2LPtunxryDTqvldKiRyNy0v8CgCrKVPp+rKHbzpEs6VaEMrnox2Kx8Rz/ONqKLLfTud9xFmiyl9+i9mYLb28pEYNP8yElrEQg9cWCC8oAx6DDWUHGQ5w9dpTLdRircwOdcC7MWSBaeRE8BfWaOli6w+lwKqfERfHp/4WoFaCsHYWZBnXksyVJC0StephCJOQo/QXKq3jcbyvmGG9dmh4z0qcBEQU6afsxopl/j/bWOMB/UKL+sLmhALxtcg8CG5v+s9KshMepKOE5agxDJwqdlyg1I9kGBnIBy7k4K+c9yL/mck62NPIq4alHN4o0f8Rl8jvwabB9ZM9MPtWsZi4KuNRHt0WpjZnBzhfTB5Lx6SaeFL91D9NyBPGXs= liam.mccormick@AFSMW8KPW1ZMQON
```

- Grant AWS Console access?
  > NO

@department-of-veterans-affairs/vsp-operations

**Comment by mleclerc00** [comment]
@lmccormickafs 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
