### ISSUE TITLE
CT Redesign: Create "Academics" component for profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26820]
As a developer, I need to create a Academics component for the Comparison Tool profile page so that the information can be organized in an effective way and be displayed on the sandbox profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.
3. The data elements specified in the "Education opportunities" AC is currently found under the Additional Information Institution summary section or the Veteran programs section of the current profile page.
4. The "Types of degrees offered" section of the prototype data is not currently available via GIDS and will be added in a future story.

## Acceptance Criteria:
1. The component header is: "Academics"
2. The component has two sub-sections:
    a. Education details
    b. Get started with CareerScope

3. The "Education details" subsection displays the following information:
    a. Accreditation
    b. Credit for military training
    c. Independent study
    d. Priority Enrollment

4. Accreditation includes the following:
    a. Accreditation type available: Regional or Hybrid or National or None
    b. If a URL is available, a see accreditors link that links to the corresponding profile page on the College Navigator
    c. A Learn more link with aria label: "Learn more about the different accreditation types and why it matters"
    d. When the learn more link is clicked the following content is displayed:

    > **Accreditation and why it matters**
    > 
    > The goal of accreditation is to ensure the education provided by institutions of higher learning meets acceptable levels of quality. Accreditation matters if you plan to start school at one institution and transfer to another to complete your degree. Be sure to ask any potential school about their credit transfer policy.
    > 
    > Schools are accredited regionally or nationally by private educational associations. While the Department of Education (ED) doesn't say whether regional or national accreditation is better, a recent ED study revealed that, “Nearly 90 percent of all student credit transfer opportunities occurred between institutions that were regionally, rather than nationally, accredited.” [Read the ED report on credit transferability](http://nces.ed.gov/pubs2014/2014163.pdf)
    > 
    > To learn more about the accreditation process and types of accreditation, visit the "[About this Tool](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#accreditation_type)" page.

5. Credit for military training includes the following:
    a. Credit for military training available: Yes or No
    b. A Learn more link with aria label: "Learn more about credit for military training"
    c. When the learn more link is clicked the following content is displayed:

    > **Credit for military training**
    > 
    > Does the school offer postsecondary credit for experiences and military training?

6. Independent study includes the following:
    a. Independent study available: Yes or No
    b. A Learn more link with aria label: "Learn more about Independent study"
    c. When the learn more link is clicked the following content is displayed:

    > **Independent study**
    > 
    > Beneficiaries may use educational assistance to access online learning (accredited independent study) at schools that aren’t Institutions of Higher Learning (IHLs). These schools must be postsecondary vocational institutions or area career and technical education schools that provide postsecondary level education. Note: This doesn’t apply to Dependents’ Educational Assistance program beneficiaries.

7. Priority Enrollment includes the following:
    a. Priority enrollment available: Yes or No
    b. A Learn more link with aria label: "Learn more about priority enrollment"
    c. When the learn more link is clicked the following content is displayed:

    > **Priority enrollment**
    > 
    > If an Institution of Higher Learning (a college or university) has a system for priority enrollment that allows certain student Veterans to enroll in courses earlier than other students (not necessarily earlier than all students), we’ll note that with the school’s information here.

8. The Get started with CareerScope sub-section displays the following content:

    > **Get started with CareerScope**
    > ****
    > CareerScope(R) take career and educational planning to a new level. The proven career assessment and reporting system from the Vocational Research Institute is a powerful, yet easy-to-use program.
    > 
    > [Get started with CareerScope](https://va.careerscope.net/gibill)

9. The "Academics" jump link in the header scrolls the page to where the header of the "Academics" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#academics)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17803/files

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1985&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Testing passes Qa.
