### ISSUE TITLE
Find a VA Form: PROMOTE Add Relevance, Popularity, Related Forms & UI consistency to Prod

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26826]
Promote changes for Epic #21639 to Production 

[x] Complete peer reviews
[x] Lighthouse team promotes code changes to Prod
[x] Move FE to Prod with feature flags in place on Tue 7/6/2021
[x] Remove feature flags from FE on Wed 7/7/2021
[x] Smoke test on Prod

**Comment by NCHLiberty** [comment]
watching
