### ISSUE TITLE
CT Redesign: Create "Veteran programs and support" component for profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26834]
As a developer, I need to create a Academics component for the Comparison Tool profile page so that the information can be organized in an effective way and be displayed on the sandbox profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.
3. The data referenced in this story can be found on the current profile page in the Veteran Programs section or Additional information Historical Information section.

## Acceptance Criteria
1. The component header is: "Veteran programs and support"
2. The content has two columns:
    a. Veteran programs
    b. Historical information

3. The following information is displayed under the "Veteran Programs" column when the institution participates in the program:
    a. 8 Keys to Veteran Success
    b. Military Tuition Assistance (TA)
    c. Principles of Excellence
    d. Student Veteran Group
    e. VetSuccess on Campus

4. The following content is displayed under the "Veteran Programs" column when the institution does not participate in any of the programs:

    > Please contact the school or their military office directly for information on the Veteran programs they offer.

5. The Student Veteran Group:
    a. Has a "Visit the site" link to the provided URL for the institution.
    b. Has a learn more link.
    c. Displays the following content when the learn more link is clicked:

    > **Student Veterans group**
    > Does this school have a student-led Veterans group on campus?
    > 
    > If a school has a student Veterans group that’s not represented here, please email [224A.VBAVACO@va.gov](email). We make quarterly updates to this tool.
    > 
    > Please note this email address is only for Comparison Tool-related issues. For questions about your GI Bill benefits, please check this "[Ask a Question](https://gibill.custhelp.va.gov/app/utils/login_form/redirect/ask)" page.

6. The Military Tuition Assistance:
    a. Has a learn more link.
    b. Displays the following content when the learn more link is clicked:

    > **Military Tuition Assistance (TA)**
    > 
    > Are you receiving any military tuition assistance this year? If so, how much? The Post-9/11 GI Bill pays the net-cost of your education after scholarships or financial aid amounts are applied. This includes amounts already paid by military tuition assistance.

7. The Principles of Excellence:
    a. Has a learn more link.
    b. Displays the following content when the learn more link is clicked:

    > **Principles of Excellence**
    > 
    > The [Principles of Excellence](https://www.govinfo.gov/content/pkg/FR-2012-05-02/pdf/2012-10715.pdf) are guidelines for educational institutions receiving federal funding. Schools that agree to participate will:
    > 
    > - End fraudulent and aggressive recruiting techniques and misrepresentation.
    > - Provide students with a personalized form covering the total cost of an education program.
    > - Provide educational plans for all military and Veteran education beneficiaries.
    > - Provide accommodations for service members and Reservists absent due to service requirements.
    > - Assign a point of contact for academic and financial advising.
    > - Make sure all new programs are accredited before they enroll students.
    > - Align institutional refund policies with those under Title IV.
    > 
    > Foreign schools, high schools, on-the-job training and apprenticeship programs, residency and internship programs, and those who don’t charge tuition and fees aren’t asked to comply with the Principles of Excellence.
    > 
    > We try to make sure this information is accurate, but prospective students should only use this as a planning tool. Principles of Excellence schools are updated quarterly.

8. The 8 Keys to Veteran Success:
    a. Has a learn more link.
    b. Displays the following content when the learn more link is clicked:

    > **8 Keys to Veteran Success**
    > 
    > The “8 Keys to Veterans’ Success” are steps that postsecondary institutions can take to assist Veterans and service members in transitioning to higher education, completing their college programs, and obtaining career-ready skills.
    > 
    > Postsecondary institutions listed here have stated their support for the 8 Keys. However, this isn’t an assurance by the U.S. Department of Education that an institution has actually implemented the 8 Keys. It also doesn’t mean that these institutions are endorsed by the U.S. Department of Education.
    > 
    > To learn more about accreditation, visit the U.S. Department of Education’s [8 Keys to Veterans’ Success](http://www.ed.gov/veterans-and-military-families/8-keys-success-sites) page.

9. The VetSuccess on Campus:
    a. Displays the email contact provided for the institution.
    b. Has a learn more link.
    c. Displays the following content when the learn more link is clicked:

    > **VetSuccess on Campus (VSOC)**
    > 
    > This program supports service members, Veterans, and qualified dependents through on-campus counseling and help overcoming barriers—like accommodating disabilities or getting referrals to health services. It's designed to help you succeed at school and get ready to enter the job market in a promising career field.
    > 
    > [Download the VSOC fact sheet](http://www.benefits.va.gov/vocrehab/vsocfactsheet.asp)
    > 
    > [Learn more about the VSOC program](https://www.benefits.va.gov/vocrehab/vsoc.asp)

10. The historical information column displays a table with the following data columns:
    a. Benefit
    b. Recipients
    c. Total paid (FYXXXX) where XXXX is the calculator constant FISCALYEAR.

11. The data rows in the historical information table are:
    a. Post-9/11 GI Bill
    b. Yellow Ribbon

12. The "Veteran programs and support" jump link in the header scrolls the page to where the header of the "Veteran programs and support" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/GAIAH35MWDR#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b4423daa6b9fe67f4bf212e1255422a4b25fb766/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#veterans-programs-and-support)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17819

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1984)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are on staging. Closing this issue

https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/11513535#veteran-programs-and-support
![Screen Shot 2021-07-14 at 12.26.47 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d30c36a4-dfc1-477a-9c47-d83e5dd72bb6)
