### ISSUE TITLE
[FE] Notification Preferences: Create feature flag for notification preferences feature

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#26837]
## Background
In order to support testing an eventual phased rollout of the Notification Preferences feature we'll need to have a feature flag in place to control access.

## Tasks
- [ ] Create feature flag
- [ ] ...
- [ ] ...?

**Comment by erikphansen** [comment]
Both FE and BE PRs were merged so I'm closing this.
