### ISSUE TITLE
CT Redesign: Create "Contact Information" component for profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26835]
As a developer, I need to create a Academics component for the Comparison Tool profile page so that the information can be organized in an effective way and be displayed on the sandbox profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for non-vettec institution types.
3. The data referenced in this story can be found on the current profile page in the Contact Details section or Additional information section.

## Acceptance Criteria:
1. The component header is: "Contact Information"
2. The content has foursub-sections:
    a. Address information
    b. Single point of contact for veterans
    c. School certifying officials
    d. Institution codes

3. The address section displays:
    a. The physical address of the institution.
    b. The mailing address of the institution.

4. The Single point of contact for veterans section:
    a. Has the header "Single point of contact for veterans.
    b. Displays whether the institution has a single point of contact with: Yes or No
    c. Has a learn more link
    d. Displays the following content when the learn more link is clicked:

    > **Single point of contact for Veterans**
    > 
    > Does the school have a dedicated point of contact for support services for Veterans military service members, and their families?

5. The School certifying officials section displays the following information for all primary SCOs:
    a. Name
    b. Title

6. The Institution codes section displays the following information:
    a. VA facility code
    b. ED IPEDS code
    c. ED OPE code

7. VA facility code:
    a. Has a learn more link
    b. Displays the following content when the learn more link is clicked:

    > **VA facility code**
    > 
    > Unique identifier for VA-approved facilities.

8. ED IPEDS code:
    a. Has a learn more link
    b. Displays the following content when the learn more link is clicked:

    > **ED IPEDS code**
    > 
    > Unique identification number assigned to postsecondary institutions surveyed through the Integrated Postsecondary Education Data System (IPEDS). Also referred to as UNITID or IPEDS ID.

9. ED OPE code:
    a. Has a learn more link
    b. Displays the following content when the learn more link is clicked:

    > **ED OPE code**
    > 
    > Identification number used by the U.S. Department of Education’s Office of Postsecondary Education (OPE) to identify schools that have Program Participation Agreements (PPA) so that its students are eligible to participate in Federal Student Financial Assistance programs under Title IV regulations.

10. The "Contact Information" jump link in the header scrolls the page to where the header of the "Contact Information" section is at the top of the viewport.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b4423daa6b9fe67f4bf212e1255422a4b25fb766/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#contact-information)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17834

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1986&group_by=cases:section_id&group_order=asc
