### ISSUE TITLE
[Discovery] Determine approach for a Front End

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#2684]
## User Story or Problem Statement
The current solution that we are using to display the data in the VA.gov product directory is through a shared Google Sheet.  Not all members working on VA.gov have easy access to Google Sheets, and it is very cumbersome to use with the vast amounts of data.

## Goal
Determine an approach to create a user friendly UI that is powered by a single source that allows members working on VA.gov to easily find all available information on specific products.

## Objectives or Key Results this is meant to further
- Determine what type of front end solution to connect to the data source
- Create a mock of what the front end should look like

## Acceptance Criteria
- [ ] A mock up of a potential front end is completed

**Comment by omgitsbillryan** [comment]
@alexpappasoddball , mind linking to the mockup you showed me in this ticket? Either directly or using screenshots.

This seems like a "solved problem", so I'm not sure we should be reinventing the wheel on a first iteration. A custom solution would require a lot of extra stuff like:

- tests
- deployment scripts
- CI environment
- possibly a new GH repo
- design work

☝️becomes a very big undertaking.

I did a bit of searching based on that mockup you showed me, and I think the standard Github Wiki section meets a lot of the needs:

- easily searchable
- single source of truth
- access for everyone to view and edit

For the `va.gov-team` repo, the wiki would contain a page for each of our "products". Each page would describe what the product does and who is responsible / could answer questions. What do you think?

**Comment by alexpappasoddball** [comment]
@omgitsbillryan That sure does sound like a viable solution to look into.  I know one of the teams is going to stand up a document center that is powered by GitHub.  The only question we have about using GitHub is it is public and we have a lot of PII in this (business owners, product owners, etc) that we don't want to expose.

Here is the link to a prototype of a way to expose the data that is visually superior to Google Sheets.
https://www.fluidui.com/editor/live/preview/cF9jQ2ZlNnd6VEtoSjBUejFyV1FnUm9sdk00dDJFN0hESg==
