### ISSUE TITLE
[Frontend] Enhance a11y for file upload component error

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#26843]
## User Story

**As a** screen reader user, **I want to** have the error message for the file upload component to be read before the filename **in order to make** the error more apparent.

## Acceptance Criteria

- [ ] Update file upload error message to be read before the file name

**Comment by dat-gcio** [comment]
@AngelaFowler82 Creating this ticket so that it can be documented in a ticket. Can you confirm that this change is recommended.

CC: @tchrisdyer

**Comment by AngelaFowler82** [comment]
Essentially, this is what we're looking for. See this WCAG success criteria for more specific guidance. There are several ways we can do this.
https://www.w3.org/WAI/WCAG21/Understanding/error-identification.html

**Comment by dat-gcio** [comment]
Closing this out. Further enhancements to the focus will be handled in future ticket.
