### ISSUE TITLE
Define Previewable page scope

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#26853]
## Issue Description
A gap exists in the front end experience between the preview server and the production environment, making troubleshooting difficult and inefficient for engineers and hard for field staff to view/trust their changes before publishing. This impacts Vet Centers and VAMC

---
## Tasks
- [ ] Document the scope of work for making Vet Center and VAMC pages "previewable", including the following considerations:
       - Audit existing Facilitiies pages to make sure they are all previewable.
       - Pages with greatest difference between preview and prod, such as entire pages and or areas of missing content (i..e images, alerts)
       - Document pain point for engineers - troubleshooting bugs, etc (most will be the same)
       - Value to content editors and business stakeholders - ability to preview content before publishing
       - Pages at highest risk for bugs/high volume changes by field 
       - Known differences in Preview mode that we want to keep

## Acceptance Criteria
- [ ] Scope of initiative is documented and time boxed to pages with greatest value to engineers and users

**Comment by mpelzsherman** [comment]
All pages under pittsburgh-health-care:

| path     | entity id | previewable? | diffs  |   |
|----------|-----------|--------------|---|---|
| about-us | 775       | yes          | none  |   |
|billing-and-insurance   |   197        |       yes       | none  |   |
| chaplain-services-and-interfaith-chapels         |   779        |    yes  | none  |   |

contact-us
dav-vans-transportation-for-veterans
events
health-services
legionella-water-testing
locations
make-an-appointment
medical-records-office
news-releases
operating-status
pharmacy
policies
programs
register-for-care
research
shuttle-schedule
staff-profiles
status
stories
water-quality-monitoring-and-reports
work-with-us
```

**Comment by mpelzsherman** [comment]
Known differences in Preview mode that we want to keep:

1. "Edit this page in the CMS" link
2. AXE checks (may yield false positives)

**Comment by mpelzsherman** [comment]
Closing as objectives have been met.
