### ISSUE TITLE
[Design] 10-10EZ Automatic Qualifiers flow

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26850]
## User Story

As a Veteran applying for health care, I would like to expedite the HC application so I can complete it faster, remove blockers, and have less confusion.

## Expected Behavior

If an applicant's disability rating is 50% or higher, they can skip some parts of the application. We need to define that experience so that it is clear and transparent. 

## Acceptance Criteria

- [x] Define specifications
- [x] Define flow for authenticated user with pre-populated disability rating of 50% or higher
- [x] Define flow for authenticated user with self-reported disability rating of 50% or higher
- [x] Define flow for unauthenticated user with self-reported disability rating of 50% or higher
- [x] Define flow for user **without** disability rating of 50% or higher
- [x] Create a design for authenticated user with pre-populated disability rating of 50% or higher
- [x] Create a design for user with self-reported disability rating of 50% or higher
- [x] Update design intent ticket

**Comment by sshein** [comment]
also watching this one :)

**Comment by Dene-human** [comment]
Current specs:

1. Authenticated user with disability rating of 50% or higher (confirmed through pre-fill or by self answering Disability compensation question) will skip Military Service, Household information and (maybe) Medicaid/Medicare questions.
     - Question: Will the unauthenticated user also be able to skip? -probably yes

2. Required questions: Veteran information section, other insurance info, facility selector. Need to confirm how Medicaid/Medicare questions are used to understand if we can skip these.

3. VA Benefits question will move up in the flow to be placed before Military Service section (it will be hidden for applicants who pre-fill shows has 50% or higher disability rating).
       - Authenticated user with 50% or higher will be shown an alert at the beginning that provides them with the information and gives them the option to say this is not correct (in the outlier case)

4. The experience must provide those with 50% or higher a clear understanding that they are able to skip some questions and why.

**Comment by Dene-human** [comment]
These designs and flows were specifically created around the service-related disability rating of ≥50%, but when we want to also incorporate Combat status it can follow a similar pattern.

[Working designs](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/4EEB69A5-43C1-45B3-B5B6-58D7DA435BD1)
[Flows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/A71F1C96-FF98-42A2-9ADD-6D4B7A1DDB20)

**Comment by Dene-human** [comment]
I created a new page for confirmation instead of the pop-up as discussed in design intent. I'm closing this ticket. We will obviously iterate as we go through research/discussions with SMEs.
