### ISSUE TITLE
Wizard Move from Claims & Appeals

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26864]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[x] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?
Content page and entry point changes for Form 526 Wizard updates. 
From: https://staging.va.gov/disability/how-to-file-claim/
To: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/start

## When does this content work need to be done?
07/12/21

*In addition to the date you need this content work to be done, please let us know the ETA for the app/tool launch.*
7/15/21

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Ronnie Henry
-	Designer: Kevin Stachura
-	FE engineer: Robin Garrison, Asha Gross
-	Product/team Slack channel: vsa-claims-appeals

## Links to related tickets

*Please include here a link to the epic, or other relevant tickets, for this product work.*
Ticket for this work [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16517). 

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
@shiragoodman @peggygannon @mnorthuis for awareness

**Comment by RLHecht** [comment]
@vhenry07 For this work, are we taking off the wizard and replacing it with a CTA button similar to the other how to apply pages on other benefit hubs? So instead of what is there now, we would have something like "How do I file my disability claim online?" and then the green button that links to va.gov/disability/file-disability-claim-form-21-526ez/start? Just making sure I'm clear on the work being done. FYSA @bethpottsVADEPO

**Comment by mnorthuis** [comment]
There are quite a few entry points that need to be modified/added as part of this work, info is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/wizard-disability.md

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's my suggestion for the teaser text for the disability hub page:

File a claim online (VA Form 21-526EZ)
Start your application for disability compensation online now.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I like what you have, let's just get rid of the second instance of "online"--keep it in the link label, but delete it from the teaser. Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht For the green button on the how to file a claim page, would you check with accessibility about the label we talked about to make sure there aren't any concerns?: Find out if you can file a claim online

**Comment by RLHecht** [comment]
@joshkimux See Beth's comment directly above. We are going to change the text on green CTA button on the disability claims landing page from "Let's get started" to read "Find out if you can file a claim online" and it will go to the [start page](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/start) where users will need to answer the questions in the wizard. We wanted to confirm this text is OK from an accessibility standpoint and that it gives screen readers enough information when clicking through the page. Adding in "disability compensation" puts us over the character count.

**Comment by joshkimux** [comment]
@RLHecht we can include specifics like "disability compensation" in an `aria-label` as we do elsewhere at VA.gov 😄

**Comment by RLHecht** [comment]
@joshkimux I'm not sure we can do that in Drupal. I know that it often strips out aria labels for certain things. The only thing we usually have them for is phone numbers.

**Comment by joshkimux** [comment]
Got it-- three follow up questions just so I can get a little bit more context before making a recommendation:

1. How many links of this type will exist on the page? If this is the only "Find out if you can file a claim online" and the `h1` already suggests it's around disability compensation, we may not need to include it.
2. If there are many types of this link on this page, could we use `sr-only` css class to hide text visually from sighted folks?
3. Is this styled as a link or styled as a button? Also, is this a `a` element or `button` element? If this is a link, it should use the action link styling. https://design.va.gov/experimental-design/action_links

**Comment by RLHecht** [comment]
@joshkimux Thanks for thinking this through with me! 
1. This is the only link like this on the page. The page it's on has the H1 "[How to file a disability claim](https://www.va.gov/disability/how-to-file-claim/)" so it does mention disability already.
3. This will be styled as a button. The CMS does not allow for the action link yet so we are still using the green CTA button. If you scroll down on the page it's under the H2 Can I file my claim online? Instead of this being a wizard it will now be a button linking to the start page.

**Comment by joshkimux** [comment]
@RLHecht Of course, glad to help! 🤜 🤛 

1. If this is the only link, "Find out if you can file a claim online" works 👍 
2. I'd recommend writing up an issue ticket to backlog for updating the green CTA button to an action link; this is an ongoing effort across VA.gov we'd like to keep tabs on 🙏

**Comment by RLHecht** [comment]
@joshkimux Great, thank you! The CMS team does have the action link in their backlog already so I think we are OK on that front.

**Comment by RLHecht** [comment]
Update: The CTA button text and hub page teaser link will be "File a disability compensation claim online"

For nav entry points we can say "File a claim online"

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made the updates to the disability page, adding the CTA button and removing the widget. I reworked the text above the CTA and the button text slightly so that it aligned with what we have on other how to apply pages I did the same with the H2 underneath about other ways to file. Can you take a look and let me know if all looks OK?

**Comment by RLHecht** [comment]
@mnorthuis For the CTA button on disability are we linking to the /start page or the /introduction page? In your entry points doc you have /introduction. If the wizard is on the /start page is that an issue?

**Comment by mnorthuis** [comment]
@RLHecht Good question!  We actually shouldn't be linking to either /start or /introduction, our links (for any form) should go to the primary form URL (www.va.gov/disability/file-disability-claim-form-21-526ez/)  and the FE code will resolve to the appropriate URL.   This ensures all scenarios are handled (sometimes the wizard is skipped) and that if the wizard should ever be removed, all the entry links do not need to be updated, nor are redirects needed...the FE code just resolves to the appropriate first page of the flow.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Two things...
1/ I see that the CTA on disability/how-to-apply that's currently "Let's get started" changed recently to an action link. Is there any update on when drupal will have this capability? With the work you have queued up that action link will change back to a button, right?
2/ Would you please change the CTA label on the eligibility page as well to match how-to-apply? (You may already have this in place, but I wanted to double check.) Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht Your changes to the green button label and surrounding text look good. I'd like to align with the HC how to apply page for the text below this... "other ways to file." This is an accessibility recommendation:

H3: You can also file a claim in any of these 3 ways _(right now this is an H2, but it should be an H3)_

H4: Option 1: Apply by mail _(these are all H3s, and should be changed to H4s)_
H4: Option 2: Apply in person
H4: Option 3: Apply with the help of a trained professional

Would you make those edits? Go ahead and break my lock. Thanks!

**Comment by RLHecht** [comment]
The CTA widget and updated disability hub page have been published and all the entry points have been added and updated. FYSA @mnorthuis. Will close after I validate them all online.

**Comment by RLHecht** [comment]
These changes are all live. Closing ticket. FYSA @vhenry07
