### ISSUE TITLE
Research Which Synthetic Monitors to Create for the Platform

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26881]
# Description
The Platform is looking to expand the suite of synthetic monitors. We need to gather feedback from stakeholders for the Platform to determine which areas of the Platform we need to create synthetic monitors for.

## Tasks
- [x] Schedule interviews with stakeholders
- [x] Synthesize feedback from various stakeholders into a single cohesive list of synthetic monitors

## Definition of Done
We have a list of synthetic monitors to create that will alert Platform support personnel of production issues with essential aspects of our Platform.

**Comment by rjohnson2011** [comment]
Reaching out to @platform-team to get list of desired requirements for latest iteration of synthetic tests.

**Comment by JoeTice** [comment]
We have conducted this informally via Slack and have gotten input from stakeholders

**Comment by pjhill** [comment]
Stakeholder input has been collected and used to define synthetic monitor tickets.
