### ISSUE TITLE
Troubleshoot the `SIGILL` Error Occurring in the GHA-Hosted Cypress Suite

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26893]
Chase down a root cause for the issue being discussed here --

https://dsva.slack.com/archives/C01V94K0QNS/p1625075402187300

**Comment by pjhill** [comment]
Error being logged out -- 

> The Test Runner unexpectedly exited via a exit event with signal SIGILL

**Comment by pjhill** [comment]
Self-hosted runner is logging out this error message when the Cypress suite fails --

> kernel: [867685.753454] traps: Cypress[1484892] trap invalid opcode ip:563286b30ee3 sp:7fffe1dfde40 error:0 in Cypress (deleted)[5632822e7000+639b000]

**Comment by ddzz** [comment]
PR with an attempt at a fix: https://github.com/department-of-veterans-affairs/vets-website/pull/17759

**Comment by pjhill** [comment]
'SIGILL' has not popped up since this PR was merged -- marking as resolved.
