### ISSUE TITLE
Access for Michel McDonald

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#26897]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Michel McDonald
- Please Provide your email.
   > michel.mcdonald@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Claims and Appeals, backend software engineer, AdHoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDmP007EH+vqd+INB9IrSLsEzZi1he8v5dKSW2E9bTFKuq6oTJigBO47Y0t5EW1sznJrwGcToStg+O5jNjwtttce4iGbR0ZTOA8koVihs6vgORK2+04e6HXqKhgRLf50ADxw+lZv2ELwR8KxwfnOFnT7N5qWqKcjlHykdT6cWChlvKaSfoMXOAMsEVQFXrH3o4CZ79ZggT/EOo2kv3FOTttCXjidQvgFQ2djNlOre1J0A9tIcx5LPKMCRxScqMLuIa3jyEIgLlDF0mH9qXgcm0dSAeklYu/F9i/MEpSi4v//Hn3uyizyN+HJ8YracVkC2mUGOk+B58LWuFFTSyz4n9xrK/yOGmyeFSnH/52vRcqYl8Lyiwy2QoAb+yTxc71IO/Yzo1q0nRRHsisIeyMGaE1QDiwxa5tq+Ar0/fDNA5BkEDSO5LLwLD0ofKiLs4ECDyo3te2Px9t7fTJs8iNLy4hnuF2F1HfSOBbIvdTJkJ557n55/Yu8n/c0g6CKQPROT0= michel.mcdonald@adhocteam.us
```

- Grant AWS Console access?
  > Yes
  - What AWS services do you need access to and why? 
  > I need aws access to run a rake task related to error monitoring for form526

**Comment by mleclerc00** [comment]
@mchelen-gov 

Requesting AWS access

Thanks!

**Comment by mchelen-gov** [comment]
Hi @michelpmcdonald , who is your vendor onboarding representative? This is the person from your company or the primary contractor who helped you onboard at VA.

**Comment by michelpmcdonald** [comment]
Hi @mchelen-gov,

Kimberly West

**Comment by mchelen-gov** [comment]
Request approved 👍

**Comment by mleclerc00** [comment]
@michelpmcdonald 

Do you happen to have a teammate I can reference in order to make sure you have the correct permissions to resources you need?

**Comment by michelpmcdonald** [comment]
> @michelpmcdonald
> 
> Do you happen to have a teammate I can reference in order to make sure you have the correct permissions to resources needed?

@annaswims

**Comment by mleclerc00** [comment]
Account created and passed along needed information
