### ISSUE TITLE
Content plain language and style review of Q&As for Your VA payments from eBen team

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#26891]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[x] Content support for an app or tool (auth page)
-	[ ] Something else (please add details in the next question)

## What do you need help with?

Please review the rewritten content in the 3 Q&As on the Your VA payments main page. https://www.sketch.com/s/2cbfbba2-b8c6-490a-8f25-240877a7786b/v/p4b1bp/

This is the original page that's being reworked, just for context:
https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/4fd4ae07-0f81-46d2-957b-80737ec69b6a/

## When does this content work need to be done?

Second week of July.

## Do you plan to bring this to an upcoming content office hours session?

- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: Jason Wolf
-	Designer: Jim Adam, Candy Clark
-	FE engineer: Jesse Cohn
-	Product/team Slack channel: vsa-eben-migration

## Links to related tickets
#

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by bethpottsVADEPO** [comment]
@candy-gcio Here you go! Did a little editing and plain language work. Two questions: 
1/ Does the Veteran really have to mail a missing check they've found back to Treasury? If so, we should put that address here or say something like "...you must return it to the U.S. Department of the Treasury. Send it to the address listed on the check." (I'm assuming there's a Treasury address there, but you'll need to check of course.)
2/ I'm not sure what the text link or tab or button says in the VA.gov profile for direct deposit. Can you double check that what I bolded in the last of the 3 Q&As here is accurate (with capitalization style too)? Maybe put a screen shot here and I can rework the text accordingly!

**What if I'm missing a payment?**
If you didn't receive your payment on the date it should have arrived, please wait 3 business days before you contact us. We can't track payments before then. 

**Note:** We don't list direct-deposit payments that are less than $1 or check payments that are less than $5 in your online payment history.

To report a missing payment, contact us at <a href="tel:+18008271000" aria-label="8 0 0. 8 2 7. 1 0 0 0.">800-827-1000</a>. Please be ready to give us your address and social security number or VA claim number. If you receive payments through direct deposit, you'll also need your bank account information.

**What if I find a check that I reported missing?**
If you find a check that you reported missing, please don't deposit it. Return it to the U.S. Department of the Treasury and wait for your replacement check. If you deposit both the original and the replacement check, you'll owe us for the additional payment. U.S. Debt Management Center will contact you about collection. 

**How can I change my direct deposit information?**
To change your bank information, go to your profile and click on **direct deposit**. Any changes you make in your VA.gov profile will update across these benefits: disability compensation, pension, claims and appeals, Veteran Readiness and Employment (VR&E), and VA health care.

**Comment by candy-gcio** [comment]
Thanks, @bethpotts ! I've updated the language in the sketch. I'm checking into the address to return payments.

Here's the screenshot of the profile. So, looks like we'd have "Direct deposit information".
![image](https://user-images.githubusercontent.com/84141672/126354282-7f8154c7-ec15-482d-b450-7fb16f6e5713.png)
![image](https://user-images.githubusercontent.com/84141672/126354342-8d0ea1ee-9c9c-41fa-b5c5-717e9bb4ebb8.png)

**Comment by bethpottsVADEPO** [comment]
@candy-gcio Thanks! I updated the text above that I originally provided. It now says, "Direct deposit information." And it's correct, fyi, for it to be bolded. That's our way of representing text that a user would need to click on.

**Comment by bethpottsVADEPO** [comment]
@candy-gcio Following up with a revised version of this Q&A to account for including a phone number to call to find out how to return the payment (if there's space, you'll see that I'd like the answer to be split into 2 paragraphs):

**What if I find a check that I reported missing?**
If you find a check that you reported missing, please don't deposit it. Return it to the U.S. Department of the Treasury and wait for your replacement check. Call this number to find out how to return the original check: XXX-XXX-XXXX. 

If you deposit both the original and the replacement check, you'll owe us for the additional payment. U.S. Debt Management Center will contact you about collection.

**Comment by RLHecht** [comment]
@candy-gcio Is there anything else you need or should we close this ticket?

**Comment by candy-gcio** [comment]
We are done with this one. Thank you!
