### ISSUE TITLE
[Research] Recruit participants for the Education Dashboard MVP usability study.

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#269]
## Goal
Recruit participants for the Education Dashboard MVP usability study.

## Definition of Done
- [x]  3-6 product owners are scheduled for the usability study

---
View [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/Education-Analytics-Research-Plan.md).

cc: @amycesal @joanneesteban

**Comment by joanneesteban** [comment]
Participants have been identified and scheduled. Closing this issue.
