### ISSUE TITLE
[Overall user experience] Design component or pattern in use isn't considered a best practice.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26903]
#### VFS team name
Decision Tools

#### VFS product name
Find a VA Form, Add Relevance, Popularity, Related to 

#### Point of Contact/Reviewers
Allison Christman

---

### Platform Issue
Design component or pattern in use isn't considered a best practice.

### Issue Details
Spacing above and below search box content is not equal

Spacing between form name and clickable and non clickable titles is inconsistent 

### Link, screenshot or steps to recreate
![image](https://user-images.githubusercontent.com/71330581/124292337-764c9200-db23-11eb-9058-b70b8b47a5ba.png)
![image](https://user-images.githubusercontent.com/71330581/124291952-1b1a9f80-db23-11eb-8431-22f5f9f2883c.png)

### Supporting Guidance
Category 01, Issue 01 (this section will eventually link to the VA.gov Experience Standards on Platform Website, however it's not live yet)

### Other References

---

### Platform Recommendation
Make the spacing above “Enter a…” and below the text box are the same 

Make the spacing between the clickable and non clickable titles consistent.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by shiragoodman** [comment]
adding labels so ticket is consistent with post-pilot process

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO => https://staging.va.gov/find-forms/?q=10-10ez

![Screen Shot 2021-09-03 at 10 27 28 AM](https://user-images.githubusercontent.com/26075258/132021957-9f5ae8ad-a045-4405-a61e-66210b654bab.png)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel do you have a sec to do a screen share?  I have Prod and Staging up side by side and they look identical to me.  I must be missing something.

**Comment by MarciMcGuireGCIO** [comment]
Thanks for clarifying that.   This looks good.  Thanks!
