### ISSUE TITLE
[Link and button labels] Button and link language isn't descriptive and/or their purpose isn't clear.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26907]
#### VFS team name
Decision Tools

#### VFS product name
Find a VA Form, Add Relevance, Popularity, Related to 

#### Point of Contact/Reviewers
Angela Fowler

---

### Platform Issue
Button and link language isn't descriptive and/or their purpose isn't clear.

### Issue Details
On the form detail page About VA Form 10-10EZ, the text of the link to access the online form simply says "Go to the online tool." Since there are other forms listed on the page, this may cause confusion as to which online tool the user is going to.

### Supporting Guidance
Category 08, Issue 03(this section will eventually link to the VA.gov Experience Standards on Platform Website, however it's not live yet)

### Other References
WCAG SC 2.4.4_A

---

### Platform Recommendation
Ensure the test of the "Go to online tool" link on form detail pages include the form title.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by zacharymorel** [comment]
Ref with screenshots for the future for solving the issue => https://github.com/department-of-veterans-affairs/va.gov-team/issues/26068

**Comment by MarciMcGuireGCIO** [comment]
Noting that we whatever language is decided on, we will also need a Spanish translation for it.

**Comment by zacharymorel** [comment]
Oh could this be a blocker for the launch blocker?

**Comment by MarciMcGuireGCIO** [comment]
It might be best to just get the desired button label text written, and then translated before we update.  Two birds with one stone.

**Comment by MarciMcGuireGCIO** [comment]
Blocked - need Content to provide recommendation

**Comment by shiragoodman** [comment]
adding labels so ticket is consistent with post-pilot process

**Comment by MarciMcGuireGCIO** [comment]
This issue has been resolved.
