### ISSUE TITLE
Edit Cards do not open when they hit error state

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#26900]
## User Story

As a Veteran it is confusing when I press the continue button and it does not let me navigate at the same time of not receiving any validation feedback. 
Update the edit card UI to go into edit mode it error exist under neath.
So when there is an error the Veteran knows what to fix and does not need to press the edit button to see the error underneath.

I## Expected Behavior

Veterans can see error when blocked by continue button

## Acceptance Criteria

- [ ] Edit cards open into edit mode when there is an error underneath.

Video:
https://images.zenhubusercontent.com/133843125/55145ad0-2c6d-40c1-94e4-44ba674aa942/edit_cards_no_error.mp4

**Comment by craigwheeler** [comment]
validation added to list loop component verified issue no longer exists closing ticket
