### ISSUE TITLE
[Color, typography and visual elements] Your content or feature uses color as the only method to provide information.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26905]
#### VFS team name
Decision Tools

#### VFS product name
Find a VA Form, Add Relevance, Popularity, Related to 

#### Point of Contact/Reviewers
Josh Kim

---

### Platform Issue
Your content or feature uses color as the only method to provide information.

### Issue Details
Helpful links, more information links, and manage your VA benefits links should not rely on color. This is a common issue that can be resolved by referencing past tickets like [#18442](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18442)

### Supporting Guidance
Category 06, Issue 01
(this section will eventually link to the VA.gov Experience Standards on Platform Website, however it's not live yet)

### Other References
WCAG SC 1.4.1_A

---

### Platform Recommendation
Consistently underline and style links.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by 1Copenut** [comment]
@joshkimux If you have an example of the links that are relying solely on color, would you mind attaching a screenshot? I think it'd be a helpful addition.

**Comment by zacharymorel** [comment]
Ref with screenshots for the future for solving the issue => https://github.com/department-of-veterans-affairs/va.gov-team/issues/26068

**Comment by zacharymorel** [comment]
Hey @joshkimux , is the links in the "Helpful Links" section suppose to have an underline OR just not turn grey on hover state?

![Screen Shot 2021-09-02 at 10 31 33 AM](https://user-images.githubusercontent.com/26075258/131862533-4b41f08e-37e4-49c7-9049-c657220bb7ec.png)

**Comment by joshkimux** [comment]
@zacharymorel Just have an underline! 😄

**Comment by shiragoodman** [comment]
adding labels so ticket is consistent with post-pilot process

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This now can be viewed on staging.

**Comment by zacharymorel** [comment]
@joshkimux This can be viewed on staging or prod.

**Comment by joshkimux** [comment]
![image](https://user-images.githubusercontent.com/14154792/132373006-6ddec5c3-c33e-4c79-9811-627811082dc2.png)

Wonderful! Closing this out 🥳

**Comment by MarciMcGuireGCIO** [comment]
Great job as always @zacharymorel !  Thanks @joshkimux for the review!

**Comment by 1Copenut** [comment]
Thanks y'all! This is a big win for usability.
