### ISSUE TITLE
[Link and button labels] Your content doesn't use correct and consistent labels across links, entry points, navigation components, and H1s.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#26906]
#### VFS team name
Decision Tools

#### VFS product name
Find a VA Form, Add Relevance, Popularity, Related to 

#### Point of Contact/Reviewers
Peggy Gannon
Mikki Northuis

---

### Platform Issue
Your content doesn't use correct and consistent labels across links, entry points, navigation components, and H1s.

### Issue Details
The link "Schedule and view your VA appointments" should match and align with the H1 of the page where it's sending users  

### Supporting Guidance
Category 08, Issue 02 (this section will eventually link to the VA.gov Experience Standards on Platform Website, however it's not live yet)

### Other References
WCAG SC 2.4.6_AA

---

### Platform Recommendation
Update link language to "Schedule and manage health appointments" to align with the H1 on the page we’re sending users

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by zacharymorel** [comment]
Ref with screenshots for the future for solving the issue => https://github.com/department-of-veterans-affairs/va.gov-team/issues/26068

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Something I just ran in to during my development. 
See this ticket under **Platform Recommendation** ? 

The Update language "Schedule and manage health appointments" that should match with header is actually controlled on the Drupal side.
It here's the link we need to change:
![Screen Shot 2021-08-06 at 12 18 36 PM](https://user-images.githubusercontent.com/26075258/128541079-1d3219a1-9e36-40f8-b525-b0f9de0e351f.png)
Here's what it needs to be:
![Screen Shot 2021-08-06 at 12 17 40 PM](https://user-images.githubusercontent.com/26075258/128540973-0ee4bad5-9582-4e07-ac10-f31c297181da.png)

The Drupal should be close to "Va Form Link Teaser" within the CMS.

**Comment by MarciMcGuireGCIO** [comment]
Ok.  We'll just need to keep that in the backlog until we have someone employed by the VA who can make that change for us.

**Comment by zacharymorel** [comment]
> Ok. We'll just need to keep that in the backlog until we have someone employed by the VA who can make that change for us.

Can we make a separate follow up ticket to the engineering work of this ticket can be finished?

**Comment by MarciMcGuireGCIO** [comment]
Yes, we can do that.

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO does anyone on your team manage the content in the gray box shown [in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26906#issuecomment-894369868) above?   We need someone with authority to update CMS content to make this change.  Thanks!

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO Yes, @RLHecht can make that update. Thanks for passing this along!

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @bethpottsVADEPO !

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO I made this change and just published.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @Randi ***@***.***>! I really appreciate it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zacharymorel** [comment]
@joshkimux Work to update the headings is now live on staging!

**Comment by joshkimux** [comment]
<img width="705" alt="Screen Shot 2021-08-10 at 8 44 45 AM" src="https://user-images.githubusercontent.com/14154792/128868936-8ae2fbc9-0e6f-4c68-914b-ebf58b0c1bf6.png">
<img width="602" alt="Screen Shot 2021-08-10 at 8 44 48 AM" src="https://user-images.githubusercontent.com/14154792/128868938-e319baf3-c7ba-49d5-828b-39b8632b5da0.png">

Brilliant as always @zacharymorel 🥳

**Comment by MarciMcGuireGCIO** [comment]
Great job, @zacharymorel! Thank you @joshkimux !

**Comment by shiragoodman** [comment]
adding labels so ticket is consistent with post-pilot process
