### ISSUE TITLE
On-Site Search: Research and Documentation 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2690]
Now that we have reviewed the feedback from search.gov, this ticket will be for research and documentation. @Karak888 to fill in

**Comment by Karak888** [comment]
closing this issue as will be creating sub tasks for documented items.

**Comment by andaleliz** [comment]
@Karak888 the description for this issue starts with "now that we have reviewed the feedback from search.gov"

Does "the feedback" reference the information here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1328

Or is there another place? Trying to follow all the links throughout the various issues around this and want to make sure I'm not missing something.
