### ISSUE TITLE
Design for Master Detail Landing Page 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2691]
- [x] Create draft layouts for each pattern
- [x] Review proposed design with design system experts
- [x] Deliver final layout for 4 templates/patterns

**Comment by artsymartha68** [comment]
Uploading what I have so far thanks to @lwalsh617 's in-depth analysis of the top 25 forms. 
[LP-Patterns.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3764334/LP-Patterns.docx)

**Comment by artsymartha68** [comment]
Updated link to the word doc in the above comment - I located a more complex 10-10EZ example.

**Comment by artsymartha68** [comment]
Uploading latest draft pattern documentation.

[LP-Patterns-v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3795320/LP-Patterns-v2.docx)

**Comment by Karak888** [comment]
@lwalsh617  is working on taking feedback and creating word docs instead of excel spreadsheet.  @artsymartha68 is still working on feedback from Jen on 11/5
ensure each of the pages have page meta info at top to fill out later- may be a new URL

**Comment by artsymartha68** [comment]
Uploading v3 of the "patterns". I am also including some styling suggestions for the content in the last two examples. 
[LP-Patterns-v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3825623/LP-Patterns-v3.docx)

**Comment by Karak888** [comment]
@jenniferlee-dsva have you reviewed @artsymartha68 's file or can one of you kindly let me know next steps?  Thanks!!

**Comment by jenniferlee-dsva** [comment]
@artsymartha68 - Per our chat, please see comments in edited doc. Please add FPO type of indicator on visual examples; please insert specs and mocks in the outline/frame I've provided -- just to help ppl quickly grok the variation between "template" vs. "custom."  

[LP-Patterns-v3-jl.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3838064/LP-Patterns-v3-jl.docx)

Regarding breadcrumb/IA - this is TBD also pending Mikki's review, so it's fine for now and we'll provide for final content info in @lwalsh617 copydeck pages. FYSA only @mnorthuis

**Comment by artsymartha68** [comment]
Uploading final version of the design spec for all the patterns after review by @1Copenut and @jenniferlee-dsva 

[LP-Patterns-v4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3842810/LP-Patterns-v4.docx)

**Comment by Karak888** [comment]
Thank you @artsymartha68!!

**Comment by artsymartha68** [comment]
Happy to help, @Karak888! I left this issue open just in case more changes come in.

**Comment by Karak888** [comment]
Thanks @artsymartha68 !  I am going to move to close this one and we can create new tickets for anything else that may arise!
