### ISSUE TITLE
Redirect Request - VAMC - VA Coatesville health care health care 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#26926]
Redirect Request - VAMC - VA Coatesville health care health care 

### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
VHA Digital Media and VA Coatesville have approved moving VA Coatesville health care from dual state to full production.  Set for July 21st, 2021.  

### Requesting team info
VAMC - upgrade team - Stan Gardner - sgardner@governmencio.com
[vsa-vamc-upgrade Slack Channel](https://dsva.slack.com/archives/CPQFCQKEH) 

### Implementation date
**July 21st, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday **July 21st, 2021**

Please indicate when the change/redirect(s) needs to be implemented"
**July 21st, 2021**
- New URLS are already implemented in Dual State
- Redirect needs to be implemented on Wednesday **July 21st, 2021**
- Redirect can occur at start of day so site can be validated and tested. 

### Redirects needed
**NOTE:  Per Web Operations process, we are changing our redirect to All to one. All TeamSite pages will redirect to new Root/landing page.

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.coatesville.va.gov	| https://www.va.gov/coatesville-health-care/

**All remaining Pages are to be redirected to system page:| https://www.va.gov/coatesville-health-care/

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [ ] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [ ] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
Redirect will be handled by a Service Now request.
