### ISSUE TITLE
[Design] Notification Prefs: Consult with IA on the order of notification groups

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#26921]
Consult with IA on the order of notification groups.
We received some [IA feedback in our midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25679) to consider ordering groups by prevalence.  Our study suggests that would be more helpful to Veterans, so we should discuss this earlier recommendation with IA to get their thoughts on how to best implement this.

Tasks
- [x] Meet with IA to discuss order of notification groups
- [x] Share any recommendations with VA Profile team to discuss feasibility (ordering of groups comes from API and it's ideal that they update it on their end, rather than manipulating it on the front end)
- [ ] Update designs to reflect any updates
- [ ] Update FE docs to reflect any updates

**Comment by andaleliz** [comment]
Spoke to Mikki and we decided to order the groups as follows:

- Your Health Care
- Applications, claims....
- Benefit payment and debts
- General VA...

The thinking behind this is a combination of frequency and prevalence; it also generally follows the IA of the home page and mega menu on the site.  It has the added benefit of still following a logical, alphabetical order for people who don't have health care, and for those that do, it surfaces the thing they will likely engage with the most frequently first.

@ajakabcin we should set some KPIs around this so we can track usage as the feature matures. We can re-order later as needed.  I'd love the teams input on what we might track. The one I can think of is:
- frequency of updating the settings for a notification (e.g. a high percentage of turning notifications on would be indicative of people being very interested in a notification; off would be people are less interested)

We can also use metrics from VA Profile and/or VA Notify (not sure who they'd come from) around frequency of communication, and keep an eye on the size of notification groups.  We might want to think about putting groups with more notifications first, or those with the most frequent notifications first.

ccing @erikphansen and @lihanli for awareness. I know we'd need to go to VA Profile and ask them to put the groups in this order through the API, ideally. Do you have any concerns/thoughts around this proposed ordering?

**Comment by lihanli** [comment]
ordering by the frequency of turning on the notification sounds good to me

**Comment by erikphansen** [comment]
This sounds fine. I was gonna say the order shouldn't change all that frequently because it could be confusing. On the other hand, this won't be something anyone is visiting and using on a regular basis so if the order changes between visits they likely won't even notice.

**Comment by andaleliz** [comment]
cool, glad we are all aligned. I don't want the order to change frequently either, and I don't think it will.  @erikphansen your point is also valid that this isn't a place people are going to be going regularly.

I'll bring this up in our VA Profile meeting today.

**Comment by andaleliz** [comment]
Brought this up in VA Profile; it's best if we handle the ordering if groups for now.  We can submit a request to them to add ordering logic in the future if we have a use/business case that warrants that. 

I've updated the [spec doc content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/README.md#content) section to reflect this. I'll update the designs with the work in #25985.
