### ISSUE TITLE
IA Request [VANotify, Terms & Conditions Page]

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/va.gov-team#26923]
## When to use this 
After you've received a response to your Collaboration Cycle kickoff ticket that indicates an Information Architect Request is needed. 

## Steps to complete an IA request

- [X] VFS Product Manager: Create this issue and provide all required information below.
- [X] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support. 
- [ ] Platform: Completes final IA feedback/recommendation.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886).
- [ ] VFS: Close issue once all IA feedback/recommendations are implemented.

## Artifacts
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify
- Link to or attach prototype or mockups
- Link to or attach user/page flows
- Link to or attach your content source of truth, including H1s (if separate from prototype/mockup)

[Digital.Notifications.Ecosystem.TCs.Additions.Draft_6_9_21_For.Intake.docx.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6755548/Digital.Notifications.Ecosystem.TCs.Additions.Draft_6_9_21_For.Intake.docx.pdf)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26807

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
Hi! We are looking for your help to create a new Digital Notifications Terms & Conditions page on VA.gov so we can display the relevant terms and conditions specific to notifications. We received some guidance from VACO that this potentially could be a separate new page vs. editing an existing one. However we would love it if it could be integrated into the existing policies given that we are under the same ATO as VA.gov etc We are also open to feedback or your ideas.

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
Digital Notifications
Terms & Conditions
Legal Information

**URL(s)** - What are your suggested URLs and why?

Unsure but this is just an idate

https://www.va.gov/digital-notifications-terms-conditions

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  

https://www.va.gov/privacy-policy/

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?

**Comment by miabecker** [comment]
@shiragoodman let me know what we need to do next here. Thank you!

**Comment by miabecker** [comment]
@shiragoodman checking in here to see if there was an update? And I will schedule a midpoint review! Thanks.

**Comment by mnorthuis** [comment]
@miabecker I need to work with sitewide content and IA on this one to determine how it relates with the overall site policies.  I'm hoping to connect with them this week and will get back to you soon.

**Comment by mnorthuis** [comment]
Content request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26807

Planned topic for next sitewide content and IA sync.

**Comment by miabecker** [comment]
Thank you @mnorthuis know you all are super busy. Bev and I had a meeting with Danielle T and John Hashimoto a few weeks ago to discuss. Let me know if you need any help from our side.

**Comment by mnorthuis** [comment]
Here is final IA information after discussing this with Danielle and sitewide content crew.  

This page should be placed as a child under the "Privacy, policies, and legal information" page.  

![image](https://user-images.githubusercontent.com/20994159/126817709-7c08cf53-0bea-424b-9a8b-7312045a568e.png)


**URL:** www.va.gov/privacy-policy/digital-notifications-terms-and-conditions

**Breadcrumb:**  Home > Privacy, policies, and legal information > [H1 of page]

**Entry point links should include**
- Privacy, policies, and legal information page: https://www.va.gov/privacy-policy/
- Profile Notifications page: www.va.gov/profile/notifications  (I don't believe this has launched yet, work with auth exp team to be added.)

**Comment by shiragoodman** [comment]
@mnorthuis can we move this to Done?

**Comment by mnorthuis** [comment]
@shiragoodman I moved it on the VFT board but not the product support board.  I'll remove the VSP label so it's off your radar. 

@miabecker You can close this issue if you don't have any questions and you have the information you need.

**Comment by miabecker** [comment]
Closing this ticket as we have what we need!
