### ISSUE TITLE
CT Redesign: Sandbox Profile Framework Story

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26920]
## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This is for non-vettec institution types.

## Acceptance Criteria:
1. Create dummy sections for each possible section
2. Each dummy section has correct CSS  (i.e borders and header css) and spacing between sections
3. Each dummy section can be scrolled to by jump links in the currently built header
4. No conditional logic for hiding/showing section+jumplink is in this story
5. No content in each section, just headers with empty content area

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b4423daa6b9fe67f4bf212e1255422a4b25fb766/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17766

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1968&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
