### ISSUE TITLE
Content Feedback - Midpoint review - EDU benefits - VA Form 22-5490, 22-0994, 22-1990E

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#26932]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
Content feedback for Education applications updates:


**Should feedback**

5490

1. Please use contractions in content
Cannot> can’t 
You are> You’re

2. I recommend sentence-casing and bolding this for emphasis, not using all caps. 
IMPORTANT: > **Important:**

3. Fry Scholarship alert
Please capitalize the first letter of each bullet point

-----

0994 

There are two versions of the certify statement on the Review screen (one with bullets and one without). Which version is correct?

**Comment by JenLJ** [comment]
@peggygannon The certification statement on the Review screen changes depending on the user's inputs.  In the Military service section, applicants state whether they are on full-time duty in the Armed services or not - and this determines which version of the Review screen they see.  Individuals on active duty have two statements to certify and therefore see the version with the bullets.  Those who aren't on active duty see the one without bullets.

**Comment by dneel-bah** [comment]
### 5490
**Must feedback**
None

**Should feedback**
1. Please use contractions in content
    - Cannot> can’t 
    - You are> You’re

> Captured in story #29806.

2. I recommend sentence-casing and bolding this for emphasis, not using all caps. 
    - IMPORTANT: > **Important:**

> Captured in story #29806.

3. Fry Scholarship alert
    - Please capitalize the first letter of each bullet point

> Captured in story #29806.

**Consider feedback**
None

**Comment by dneel-bah** [comment]
No must feedback to incorporate.  Remaining feedback has been captured in a story and added to the backlog.  See comment above for story.

Closing this issue.
