### ISSUE TITLE
Vista based upcoming CC appts when canceled display “Add to Calendar” in VAOS appointment detail card

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#26931]
## What happened?
Login to VAOS with a Test user and then all the upcoming appointments will be displayed on the landing page. Click on the Arrow sign to expand more details on the appointment for a canceled CC appt. The "Add to Calendar" link should not display in the card details page

## Steps to Reproduce
1) Create a CC appt in Vista for a future date - 30 days later or so (Ex -grethel.g.petryniec@id.me)
2) Cancel the CC appt in Vista
3) Log in VAOS with the test user (Ex:-Judy.morrison@id.me)
4) The user is directed to the VAOS landing page 
5) Validate the your CC appointment is displayed and then click on the card details link

Actual Results: The system displays the details of cc appt and Add to calendar option displays
Expected Results: The system displays the details of cc appt and Add to calendar should NOT display

![image](https://user-images.githubusercontent.com/69315717/124306040-e06d3300-db33-11eb-8e9e-a02e4e6251a0.png)

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ldelacosta** [comment]
Aarathi - this is ready for testing.

**Comment by ldelacosta** [comment]
Marcy - ready for testing. Thanks.

**Comment by laurenernest** [comment]
Retesting still pending, but closing this ticket. We can reopen if necessary.

**Comment by laurenernest** [comment]
Note from Aarathi

> We can't test the defect as the CC display flag is set to false, veteran won't receive any appointment for a clinic name matching the CC_CLINIC_REGEX pattern
