### ISSUE TITLE
Vista based upcoming CC appts when canceled does not display "Canceled by Clinic" or "Canceled by Patient" message in VAOS appointment detail card

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#26934]
## What happened?
Login to VAOS with a Test user and then all the upcoming appointments will be displayed on the landing page. Click on the Arrow sign to expand more details on the appointment for a canceled CC appt. The "Canceled by Clinic" or "Canceled by Patient" message is not displayed in the card details page

## Steps to Reproduce
1) Create a CC appt in Vista for a future date - 30 days later or so (Ex -grethel.g.petryniec@id.me)
2) Cancel the CC appt in Vista
3) Log in VAOS with the test user (Ex:-Judy.morrison@id.me)
4) The user is directed to the VAOS landing page 
5) Validate the your CC appointment is displayed and then click on the card details link

Actual Results:  "Canceled by Clinic" or "Canceled by Patient" message is not displayed.
Expected Results: The system displays the  "Canceled by Clinic" or "Canceled by Patient" message

![image](https://user-images.githubusercontent.com/69315717/124307270-984f1000-db35-11eb-9bb6-14e9deb8d0cd.png)

display## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ldelacosta** [comment]
Aarathi - this is ready for testing.

**Comment by ldelacosta** [comment]
Marcy - ready for testing. Thanks!

**Comment by aarathi-poldass** [comment]
This ticket cannot be test at this time as the CC console flag in staging is set to false. This ticket is related to VistA based CC appointments and VAOS FE won't display the appointments for clinic that matches regex. Closing the ticket @ldelacosta @jbalboni @laurenernest @marcynadeau
