### ISSUE TITLE
CT Redesign: Search Solution - Mobile prototype Internal Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26937]
Mobile prototype for landing page & search results has been reviewed with Xfunc team	

* Mobile prototype has been reviewed with Xfunc team 
* Any items needing additional, extensive  prototyping may require new ticket

**Comment by amyknox** [comment]
@watersemma Quick review at roundtable & share in slack.  Comments by EOD (7/9)
