### ISSUE TITLE
CT Redesign: Profile Page - OJT Content Doc

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26942]
Create content doc that maps to OJT Profile page	

* Draft content doc to align with prototype
* Include update to OJT benefits that mentions pro-rating of entitlement

**Comment by JenLJ** [comment]
Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/design/content-OJT.md
