### ISSUE TITLE
CT Redesign: VET TEC Profile page Internal Review, Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#26941]
Update VET TEC prototype after  internal review with Xfunc team	

* Adjustments & tweaks to mobile prototype after Xfunc review have been made  
* Signficant updates may require new ticket

**Comment by amyknox** [comment]
@watersemma to confirm with Xfunc team that all looks good & no add'l updates are needed. 

If they are, work happens on this ticket.
