### ISSUE TITLE
[Design] Notification Prefs + AI discovery: Regroup on notifications + action items

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#26949]
Now that we’ve learned more about Veterans experience and expectations around notifications, we will regroup to see where there is overlap (if any) between notifications and action items.  We'll also consider larger implications for AE IA.

Tasks
- [x] Liz and Tressa touch base (scheduled for 7/6)
- [x] Liz, Tressa, AJ, and Kevin touch base (scheduled for 7/7)
- [x] Capture any next steps (AJ)

**Comment by andaleliz** [comment]
We touched base; capturing a few points for consideration (@tressaellen lmk if I missed anything) :
- Not all alerts will have associated notification items (but some will)
- Alert MVP will likely be kind of a news feed
- It may be helpful to include a way to manage related notifications within the alert
- People will probably conflate/confuse alerts and notifications (it's already happening internally).  We need to carefully consider language and labeling around this.
   - Helpful distinction: alerts can't be opted into or out of and take place in VA.gov; notifications can be elected and are received outside of VA.gov

Future To/Dos (may need to capture in a separate ticket)
- [ ] Look how sites label alerts and notifications differently

**Comment by ajakabcin** [comment]
Next steps are to dive into the technical conversations for backend specifically around the requirement to have a toggle for general updates that indicates whether a notification goes to My VA action items or not. We plan to start this conversation in grooming today (7/7) and go from there.

**Comment by ajakabcin** [comment]
@andaleliz and @tressaellen anything else from your perspectives' at this point on this ticket?

**Comment by andaleliz** [comment]
@ajakabcin as long as we have things documented somewhere else I think we can close this :) LMK if there is a doc I should move my notes into from the comment above.

**Comment by andaleliz** [comment]
Closing this - @tressaellen feel free to reopen if there are outstanding concerns
