### ISSUE TITLE
Access for Adam Whitlock

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#26947]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`) - **can't change labels as I haven't been added to github org yet**
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Adam Whitlock
- Please Provide your email.
   > adam.whitlock@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA - Content Localization, FE Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDA0gA7xHfflIlakhM24u7RjQRVqA6y69zlzpbMSjwnsMCA96h08ie3WNKe719YmOiCjVQFh11GNo7lwtYbhOmktH9dLDNBp7ijerkKxJeM521iOl02YQI9B8gU0SrVniHOrRBRMFDnIDw+dr2e8UeInlk3zw718LndSv3S25aamVcd+dMnhpxPH4J9goJ8bmJS2dCGp5dtJr32W7j5ztF1WbUUUZTf6obeo14Y7x8Sx7G7eGxKX5lDPAebUXBjriV+04iBxmfcBYrRAMv5hSIOW/Svs+VUmIfVqtEGLWt3lb3nhi+7FhbDPyiJ2cUoZ1aSEOnN93aCZWJDmgjVHpJhbNKxFLsdYgt4veCZ/Rkqog2VtxmRVEWUn5XROCfrodOPe6D2jSj++kNXWg9q/SBs88Gne07ex1Gtok4OlFmqStG7Xdcl2++2+qSFztoryma1evI+Q26RQWRYMZtpLkQSD128FjsUTM6EYUqc3UBDUAhAKxyygHMeRXhl/y//Uk= adamwhitlock@Adam-Whitlock-Macbook.local
```

- Grant AWS Console access?
  > NO

**Comment by mleclerc00** [comment]
@adamwhitlock1

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
