### ISSUE TITLE
Remove Google Optimize tags from GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#26957]
We have Google Optimize tags in GTM that can be removed:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/tags/293

There have not been any Optimize experiments for a few years and implementation is now done outside of GTM.

**Comment by laurensimpson14** [comment]
Google Optimize tag has been deleted in [this container](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000552).

**Comment by bsmartin-ep** [comment]
LGTM.

**Comment by bsmartin-ep** [comment]
Published to production.  Closing.
