### ISSUE TITLE
Investigate and remove paused tags in GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#26959]
We have a number of tags in GTM that are paused and therefore not collecting data in GA.   These should be removed unless they were mistakenly paused.

Tag | Link
-- | --
TEST STAGING ONLY - Profile Form Submit | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/356)
TEST STAGING ONLY - Profile Saved - API Calls | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/tags/355)
Header - Link Click | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/tags/350)
cHTML - COVID FAQ Jumplinks | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/000497/tags/835)
Header - Link Click | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/tags/350)
cHTML - Onload Event Push | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/tags/1372)
cHTML - Medallia - With Datalayer | [link](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000497/tags/1422)

----

### Checklist
- [ ] Are these debug / test tags?
- [ ] Have these been replaced with another implementation (usually scraping replaced by dataLayer)?
- [ ] Can we determine why these were paused?

**Comment by jennaouellet** [comment]
QA is complete and changes have been published
