### ISSUE TITLE
[Design] - Profile: Revisit how we present information about login vs contact email address

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#26950]
Veterans got very confused when looking at the Contact Email Address section of personal and contact information in our notification settings study ([read finding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/notifications-research-findings.md#5-of-9-participants-experienced-concerns-and-confusion-about-their-sign-in-vs-contact-email-address)).  Let's see how we can improve the design and/or content around this to reduce confusion when people need to add/edit their contact email address.

**Current**
<img src="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/images/notification-settings-contact-post-email-addition.png" width="50%" />

**Possible solution**
<img src="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/images/profile-email-mock-up.png" width="50%" />

Tasks

- [x] Learn about constraints related to the ID.me sign-in email address. Do we have access to it through VA Profile? Are we allowed to display this (fully or partially) on VA.gov?
- [x] Create mock-ups
- [x] Review with content team
- [x] Create FE documentation
- [x] Alert FE team to updates

**Comment by andaleliz** [comment]
- Got a great run through on Slack about ID.me constraints
- Put together a mock-up and shared with Danielle to review content. She's on board, but wanted one last look to review before we call it "official". Captured in GH issue #27422

Will update when I get confirmation from her.

**Comment by andaleliz** [comment]
Danielle asked a great question while reviewing this content:
>If someone signed in with a DS Logon or My HealtheVet account, would they still go to ID.me to edit their sign-in email? 

Trying to hunt down the answer [in Slack](https://dsva.slack.com/archives/CSFV4QTKN/p1627396339300400).

**Comment by andaleliz** [comment]
@ajakabcin I'm moving this into the next sprint and increasing the estimate.  There is some ambiguity and confusion around DS Logon, MHV, and ID.me that we need to sort out as part of this work.

**Comment by andaleliz** [comment]
Created doc, which will update with final copy once I hear back from Danielle: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/clarify-email-addresses-specs.md

**Comment by andaleliz** [comment]
Created #27979 to better separate the work, reverted estimate back to original LOE of 5

**Comment by andaleliz** [comment]
Heard back from Danielle! @ajakabcin, @erikphansen and @tmitchellgcio this improvement is ready for FE implementation.  The [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/clarify-email-addresses-specs.md) includes mock-ups and copy.

We'll address the MHV / DS Logon confusion separately.

**Comment by andaleliz** [comment]
@ajakabcin is there a FE ticket for this created? I don't want to lose track of this work.

**Comment by ajakabcin** [comment]
There is now! Good catch - thank you! #28425
