### ISSUE TITLE
Design Feedback - Midpoint Review: Booz Allen / Education Benefits - VA Form 22-5490, 22-0994, 22-1990E

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#26973]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Put the “Applicants under the age…” in an alert style. You can use either the [background only](https://design.va.gov/components/alertboxes#background-color-only) with icon or the [standard alert](https://design.va.gov/components/alertboxes) styles.
- ![Screen Shot 2021-07-06 at 10.14.58 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/1d46e1c0-eb79-4bf6-82a3-ed2aef121853)
- Remove blue circle from the step number in the progress bar. See Sketch/Styles/Feedback for styling
- ![Screen Shot 2021-07-06 at 10.19.10 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/071de192-6969-424e-bbf8-5c5b1486982f)

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by amyknox** [comment]
@JenLJ 2 could you address these updates in the prototype Wednesday am?  TIA!

**Comment by JenLJ** [comment]
Thanks @allison0034! We've changed the underage 5490 message to a background only alert with an icon.  Do we need to use the conditional blue bar with the alert - or is that unnecessary?
![Screen Shot 2021-07-07 at 9 48 11 AM](https://user-images.githubusercontent.com/36964225/124772587-2a766000-df0a-11eb-92c4-55fcf37ae2e3.png)

**Comment by allison0034** [comment]
@JenLJ thank you. You do not. Since this is immediate feedback you can use the background only alert.

**Comment by JenLJ** [comment]
@allison0034 Finally getting back to this - all Must criteria has been incorporated :)

**Comment by dneel-bah** [comment]
@allison0034 

We have incorporated both pieces of **Must** feedback.  See below for screenshots from staging.  Are we OK to close out this issue?

### 5490 - Must 1
<img width="745" alt="Screen Shot 2021-08-31 at 2 13 32 PM" src="https://user-images.githubusercontent.com/48260534/131554854-9943325e-65d3-4097-8b53-7e12ecaae2ec.png">

### 0994 - Must 2
<img width="931" alt="Screen Shot 2021-08-31 at 2 12 16 PM" src="https://user-images.githubusercontent.com/48260534/131554838-bccec460-9340-4f91-b32d-1cf0b375428b.png">

**Comment by allison0034** [comment]
@dneel-bah thank you! You can close this ticket.

**Comment by dneel-bah** [comment]
Closing issue as completed.
