### ISSUE TITLE
New BE dev orientation

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#26977]
Please reach out and schedule BE dev orientation with:
- `@Manish Shah`
- `@Gina Ronat (ERRonat0609)`
- `@Abe Blanco`
- `@Morgan Whaley`
- `@Bradley Bergeron`

[Slack thread where orientation was requested](https://dsva.slack.com/archives/CBU0KDSB1/p1625585495203400)

**Comment by thilton-oddball** [comment]
Added following people to list:

- Fernando Boza: Boza: fernando.boza@accenturefederal.com

- Khansa Hammami: khansa.ayari.hammami@accenturefederal.com

- Nathaniel Buck: nathaniel.buck@accenturefederal.com

- Cesar: cesar.santiago@accenturefederal.com
