### ISSUE TITLE
Find a VA Form - Smoke Test - Add Relevance, Popularity, Related Forms links

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#26970]
## User Story

Issue for conducting Production smoke test July 6, 2021

## Expected Behavior

Team will test Find a VA Form on the Staging environment at https://staging.va.gov/find-forms/

## Acceptance Criteria

- [x] Designer confirms that updated UI on Find a Form search page matches mockups https://staging.va.gov/find-forms/
- [x] Designer confirms that updated UI Find a Form search results matches mockups  https://staging.va.gov/find-forms/?q=10-10ez
- [x] Designer confirms that updated UI Find a Form detail pages match mockups  https://staging.va.gov/find-forms/about-form-10-10ez/
~~- [ ] Designer confirms that PDF download instructions on search results page match mockups **(final design TBD)** ~~ DESCOPED FROM THIS RELEASE 6/14/2021
~~- [ ] Designer confirms that PDF download instructions on form detail pages match mockups  **(final design TBD)**~~ DESCOPED FROM THIS RELEASE 6/14/2021
- [x] Team verifies that searches produce desired results according to the test cases.  [Search terms below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25812#issuecomment-857774181).

### Note - copy and paste below table into your own comment for testing.  
**Icons for Change Direction:**
- 💚 Positive - New results are better than original results
- 🔴 Negative - New results are worse the original results
- ❓ Mixed - Some positive, some negative aspects
- :minus: Neutral - Results are comparable

| Search term                                                    | Prod (Post-Launch) | Staging | Prod (Pre-Launch) | Change Direction | Comments                               |
|----------------------------------------------------------------|--------------------|---------|-------------------|------------------|----------------------------------------|
| 88241i                                                       |    TBD                |   VA8824i not found        |    VA8824i found              |               |     Adding after John reporting bug on Staging last week                                   | 
| 10101                                                          |     TBD               |   VA10101 not found       |    VA10101 not found                |                 | Adding after VA reported bug last week |
| assign a representive                                          |                    | 3       | 468               |                  |                                        |
| assign a representative                                        |                    | 3       | 468               |                  |                                        |
| va representative for appeals                                  |                    | 10      | 223               |                  |                                        |
| how do I get a representative for va assistance                |                    | 10      | 477               |                  |                                        |
| 1010                                                           |                    | 188     | 26                |                  |                                        |
| 1010ez                                                         |                    | 4       | 3                 |                  |                                        |
| 21P1775                                                        |                    | 1       | 1                 |                  |                                        |
| 210304                                                         |                    | 2       | 1                 |                  |                                        |
| va form 21-526                                                 |                    | 1       | 1                 |                  |                                        |
| represenative                                                  |                    | 4       | 0                 |                  |                                        |
| representive                                                   |                    | 4       | 0                 |                  |                                        |
| travel                                                         |                    | 3       | 3                 |                  |                                        |
| nurse                                                          |                    | 2       | 2                 |                  |                                        |
| direct deposit                                                 |                    | 9       | 9                 |                  |                                        |
| release of information                                         |                    | 40      | 170               |                  |                                        |
| travel pay                                                     |                    | 12      | 12                |                  |                                        |
| dbq                                                            |                    | 0       | 0                 |                  |                                        |
| aid and attendance                                             |                    | 6       | 110               |                  |                                        |
| va form 21-526                                                 |                    | 1       | 1                 |                  |                                        |
| certificate of eligibility                                     |                    | 63      | 178               |                  |                                        |
| appeal                                                         |                    | 6       | 6                 |                  |                                        |
| notification of personnel action                               |                    | 4       | 170               |                  |                                        |
| intent to file                                                 |                    | 3       | 87                |                  |                                        |
| burial                                                         |                    | 4       | 4                 |                  |                                        |
| report of contact                                              |                    | 44      | 195               |                  |                                        |
| sf-50/ notification of personnel action                        |                    | 4       | 170               |                  |                                        |
| clothing allowance                                             |                    | 5       | 5                 |                  |                                        |
| ptsd                                                           |                    | 2       | 2                 |                  |                                        |
| disability                                                     |                    | 15      | 9                 |                  |                                        |
| coe                                                            |                    | 0       | 0                 |                  |                                        |
| medical records                                                |                    | 32      | 24                |                  |                                        |
| fmla                                                           |                    | 0       | 0                 |                  |                                        |
| power of attorney                                              |                    | 2       | 162               |                  |                                        |
| travel reimbursement                                           |                    | 9       | 8                 |                  |                                        |
| pension                                                        |                    | 29      | 29                |                  |                                        |
| va form 10-2850c application for associated health occupations |                    | 121     | 249               |                  |                                        |
| authorization                                                  |                    | 20      | 17                |                  |                                        |
| rfs                                                            |                    | 0       | 0                 |                  |                                        |
| notice of disagreement                                         |                    | 12      | 162               |                  |                                        |
| request for service                                            |                    | 87      | 240               |                  |                                        |
| statement in support of claim                                  |                    | 69      | 325               |                  |                                        |
| caregiver                                                      |                    | 1       | 1                 |                  |                                        |
| change of address                                              |                    | 9       | 165               |                  |                                        |
| burial benefits                                                |                    | 29      | 26                |                  |                                        |
| application for associated health occupations                  |                    | 121     | 249               |                  |                                        |
| home loan                                                      |                    | 50      | 50                |                  |                                        |
| advance directive                                              |                    | 7       | 3                 |                  |                                        |
| award letter                                                   |                    | 13      | 13                |                  |                                        |
| supplemental claim                                             |                    | 42      | 42                |                  |                                        |
| chapter 35                                                     |                    | 6       | 12                |                  |                                        |
| prior authorization                                            |                    | 24      | 21                |                  |                                        |
| statement of service                                           |                    | 61      | 199               |                  |                                        |
| application for nurses                                         |                    | 90      | 233               |                  |                                        |
| agent orange                                                   |                    | 2       | 2                 |                  |                                        |
| nurse application                                              |                    | 90      | 87                |                  |                                        |
| request for services                                           |                    | 86      | 232               |                  |                                        |
| name change                                                    |                    | 9       | 15                |                  |                                        |
| application for pension                                        |                    | 107     | 255               |                  |                                        |
| third party                                                    |                    | 8       | 4                 |                  |                                        |
| death benefits                                                 |                    | 31      | 28                |                  |                                        |

**Comment by MarciMcGuireGCIO** [comment]
- @zacharymorel it appears that the detail pages are not displaying the new PDF and online tool icons.

**Icons for Change Direction:**
- 💚 Positive - New results are better than original results
- 🔴 Negative - New results are worse the original results
- ❓ Mixed - Some positive, some negative aspects
- :minus: Neutral - Results are comparable

| Search term                                                    | Prod (Post-Launch) | Staging | Prod (Pre-Launch) | Change Direction | Comments                               |
|----------------------------------------------------------------|--------------------|---------|-------------------|------------------|----------------------------------------|
| 88241i                                                       |    TBD                |   VA8824i not found        |    VA8824i found              |               |     Adding after John reporting bug on Staging last week                                   | 
| 10101                                                          |     TBD               |   VA10101 not found       |    VA10101 not found                |                 | Adding after VA reported bug last week |
| assign a representive                                          |                    | 3       | 468               |                  |                                        |
| assign a representative                                        |                    | 3       | 468               |                  |                                        |
| va representative for appeals                                  |                    | 10      | 223               |                  |                                        |
| how do I get a representative for va assistance                |                    | 10      | 477               |                  |                                        |
| 1010                                                           |                    | 188     | 26                |                  |                                        |
| 1010ez                                                         |                    | 4       | 3                 |                  |                                        |
| 21P1775                                                        |                    | 1       | 1                 |                  |                                        |
| 210304                                                         |                    | 2       | 1                 |                  |                                        |
| va form 21-526                                                 |                    | 1       | 1                 |                  |                                        |
| represenative                                                  |                    | 4       | 0                 |                  |                                        |
| representive                                                   |                    | 4       | 0                 |                  |                                        |
| travel                                                         |                    | 3       | 3                 |                  |                                        |
| nurse                                                          |                    | 2       | 2                 |                  |                                        |
| direct deposit                                                 |                    | 9       | 9                 |                  |                                        |
| release of information                                         |                    | 40      | 170               |                  |                                        |
| travel pay                                                     |                    | 12      | 12                |                  |                                        |
| dbq                                                            |                    | 0       | 0                 |                  |                                        |
| aid and attendance                                             |                    | 6       | 110               |                  |                                        |
| va form 21-526                                                 |                    | 1       | 1                 |                  |                                        |
| certificate of eligibility                                     |                    | 63      | 178               |                  |                                        |
| appeal                                                         |                    | 6       | 6                 |                  |                                        |
| notification of personnel action                               |                    | 4       | 170               |                  |                                        |
| intent to file                                                 |                    | 3       | 87                |                  |                                        |
| burial                                                         |                    | 4       | 4                 |                  |                                        |
| report of contact                                              |                    | 44      | 195               |                  |                                        |
| sf-50/ notification of personnel action                        |                    | 4       | 170               |                  |                                        |
| clothing allowance                                             |                    | 5       | 5                 |                  |                                        |
| ptsd                                                           |                    | 2       | 2                 |                  |                                        |
| disability                                                     |                    | 15      | 9                 |                  |                                        |
| coe                                                            |                    | 0       | 0                 |                  |                                        |
| medical records                                                |                    | 32      | 24                |                  |                                        |
| fmla                                                           |                    | 0       | 0                 |                  |                                        |
| power of attorney                                              |                    | 2       | 162               |                  |                                        |
| travel reimbursement                                           |                    | 9       | 8                 |                  |                                        |
| pension                                                        |                    | 29      | 29                |                  |                                        |
| va form 10-2850c application for associated health occupations |                    | 121     | 249               |                  |                                        |
| authorization                                                  |                    | 20      | 17                |                  |                                        |
| rfs                                                            |                    | 0       | 0                 |                  |                                        |
| notice of disagreement                                         |                    | 12      | 162               |                  |                                        |
| request for service                                            |                    | 87      | 240               |                  |                                        |
| statement in support of claim                                  |                    | 69      | 325               |                  |                                        |
| caregiver                                                      |                    | 1       | 1                 |                  |                                        |
| change of address                                              |                    | 9       | 165               |                  |                                        |
| burial benefits                                                |                    | 29      | 26                |                  |                                        |
| application for associated health occupations                  |                    | 121     | 249               |                  |                                        |
| home loan                                                      |                    | 50      | 50                |                  |                                        |
| advance directive                                              |                    | 7       | 3                 |                  |                                        |
| award letter                                                   |                    | 13      | 13                |                  |                                        |
| supplemental claim                                             |                    | 42      | 42                |                  |                                        |
| chapter 35                                                     |                    | 6       | 12                |                  |                                        |
| prior authorization                                            |                    | 24      | 21                |                  |                                        |
| statement of service                                           |                    | 61      | 199               |                  |                                        |
| application for nurses                                         |                    | 90      | 233               |                  |                                        |
| agent orange                                                   |                    | 2       | 2                 |                  |                                        |
| nurse application                                              |                    | 90      | 87                |                  |                                        |
| request for services                                           |                    | 86      | 232               |                  |                                        |
| name change                                                    |                    | 9       | 15                |                  |                                        |
| application for pension                                        |                    | 107     | 255               |                  |                                        |
| third party                                                    |                    | 8       | 4                 |                  |                                        |
| death benefits                                                 |                    | 31      | 28                |                  |                                        |

**Comment by johnhashva** [comment]
Great job of reviewing @MarciMcGuireGCIO!  My smoke test -- while not nearly as thorough -- bears the same results.   All in all, as expected based on what we saw in Staging.   Agree, next level analysis should be focused on "relevance" (as opposed to how many results) -- and we could use Google search results as one of the benchmarks (along with our own expert knowledge, of course).  So, for "burial" -- VA Form 21P-530 is the top result form wise -- and that's FaF top result as well (score: 100!).

**Comment by MarciMcGuireGCIO** [comment]
Thank you @johnhashva! Great work, @zacharymorel @callen2563 @markviterna!

**Comment by johnhashva** [comment]
This is such a huge stop forward.  Outstanding work @MarciMcGuireGCIO @zacharymorel @callen2563 -- and Lighthouse Team! (will post in Slack to make sure Mark and Nichole get the Kudos they richly deserve).  Looking forward to the UX consistency release later today @zacharymorel
