### ISSUE TITLE
Transform tome-sync objects to fit the appropriate content model

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2698]
## Problem Statement
The content model that the templates require is somewhat different than the model that's saved from tome-sync. We need to transform the data from tome-sync to what's expected in the templates.

This includes, but is not limited to:
- Changing case (snake to camel)
- Changing property name
- Modifying the raw data
  - Unsure if this is something the GraphQL query is doing now

The work of actually doing the transformations will happen in separate tickets (e.g. https://github.com/department-of-veterans-affairs/va.gov-team/issues/2824), so this is to set up the scaffolding to get the transformations working properly and transform the fields for `page` as an example. (Also because the tickets outlining the rest of the content models don't include `page`.)

## Goal
Mimic the GraphQL query to send the same data in the same model to the templates.

## Acceptance Criteria
- [ ] The templates don't need to be modified
- [ ] Set up a scaffolding so each content model type has its own transformations
- [ ] Transform the properties for the `page` content model

## Implementation note
The transformation step will have to happen _after_ all the entity references have been replaced with the entities themselves because some transformations will require properties of the sub-entities.

**Comment by cvalarida** [comment]
@kelsonic is doing some great work listing the differences in https://github.com/department-of-veterans-affairs/vets-website/pull/10939

**Comment by bkjohnson** [comment]
Closed by https://github.com/department-of-veterans-affairs/vets-website/pull/10973
