### ISSUE TITLE
HLR v2 - add email

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#26984]
Lighthouse says they're going to accept longer email addresses for HLR v2 . Currently the email address must be 44 characters or less and is optional so we don't send it.  But, it might be worth sending for v2.  

No action is required now but adding this as a reminder for later.

https://dsva.slack.com/archives/CSKKUL36K/p1625589750145500?thread_ts=1625238891.135200&cid=CSKKUL36K

**Comment by vhenry07** [comment]
This is part of the schema change so closing as unneded.
