### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#26985]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the `department-of-veterans-affairs/vets.gov-write` org. Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: @annaswims, @michelpmcdonald 
- Reason access is required: We work on Form 526, application for Disability, which uses a series of workers to submit the main form and its related form and uploads.  Our upstream service, EVSS is rather flaky and having sidekiq admin pannel will allow us to better triage and retry failed jobs.

**Comment by jeff2d2** [comment]
Added on 7/6/21
