### ISSUE TITLE
EDU Forms: Update spacing on SSN fields in forms

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26996]
As a developer, I need to update the spacing of the 'Social Security number' and the 'I don't have a Social Security number' inputs so that the applicant can easily focus on either input on a mobile device without experiencing any difficulties.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. TBD - I don't have a social security number should be spaced farther away from the input. Need to define spacing / layout.

## Supporting Artifacts:
1. Originating Issue: #26936
2. Screenshot of issue
<img width="515" alt="Screen Shot 2021-07-06 at 3 10 46 PM" src="https://user-images.githubusercontent.com/48260534/124657366-6b219b00-de70-11eb-8dca-f1bbe8567d03.png">

**Comment by noahgelman** [comment]
@af-manish This is not an an accessibility issue. The spacing should be whatever the spacing is between similar fields elsewhere on VA.

**Comment by af-manish** [comment]
@noahgelman <cc @ERRonat0609 @mrblanco1 > Gentle nudge

**Comment by ERRonat0609** [comment]
@noahgelman  @af-manish @mrblanco1    - Just as an FYI, this issue was originally brought up as Accessibility Feedback which was part of a Mid-point Review, and was included in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26936.  

In that ticket it was also noted by our predecessors (on Jul 6) that: "This is a part of a platform definition, and similar behavior is contained in other forms."

**Comment by noahgelman** [comment]
@af-manish I told you this isn't an accessibility issue. Ask design.
@ERRonat0609 Ty for the heads up. I would ask design

**Comment by ERRonat0609** [comment]
@rtwell This defect, originally from Trevor Pierce, recommended to add "more" space but we need something less ambiguous than that. This is the field from form 5490, which is for eligible dependents to apply for education benefits. 
![image](https://user-images.githubusercontent.com/85580424/144670023-82cb82b1-146a-4578-8633-7310bff0ed38.png)

I brought this to Collab Cycle office hours, and the recommendation was to make the space between the SSN entry box and the checkbox the same as the space above it. Can you please verify if this spacing would be adequate, and if not, what should the spacing be?

**Comment by noahgelman** [comment]
@ERRonat0609 @rtwell Originally there was no Required property on the field. If there is no Required property checkbox doesn't need to exist. If there is (like in the pic above) The checkbox should be above the field. We should not require a user to enter a SSN and then put a checkbox after to say they don't have one. Those on screen readers with no SSN would be confused.

**Comment by ERRonat0609** [comment]
@noahgelman Yes, after this was brought up during office hours a couple days ago, that is why I checked in the form. The screen grab I posted this afternoon is directly from that form and it is required. And my understanding is that the checkbox  there because it is on the paper form. 

@rtwell So if that is the case, and we need to move the checkbox above the field, we will still need to know what the spacing should be. Or if there is something else that we need to consider, please let me know. Thanks!

**Comment by rtwell** [comment]
@noahgelman correct me if I'm wrong—but all form fields must have labels, yes? If so, is it OK to separate the form label from its form field? for example, it would read:

`Form label`   Social Security Number (*Required)
`Checkbox`    [ ] I don't have a Social Security Number
`Form field`    [_________]

Here's a quick couple mocks:

![image](https://user-images.githubusercontent.com/12564977/144904217-8683c61e-91aa-44ae-a8a0-7ac2b3dfbe5f.png)


Or, would we like to repeat it like so:
![image](https://user-images.githubusercontent.com/12564977/144903646-8b9cb6be-94bd-44a1-8bb3-f9ab33d88467.png)

**Comment by noahgelman** [comment]
@rtwell It looks like the same picture twice?

They should not be separated. It would make error messages complicated. The checkbox and label should be moved above the Social Security Number field entirely

**Comment by rtwell** [comment]
it's not the sea picture twice. one has a label directly about the form field, the other does not—this might be easier to read:

![image](https://user-images.githubusercontent.com/12564977/144908907-0d94bb7b-a993-4eb2-9de1-1faf177e9d6b.png)

**Comment by noahgelman** [comment]
@rtwell Ah, I see. Both are wrong. The checkbox should be above the Social Security Number (*Required) label. Social Security Number shouldn't be repeated twice nor should the checkbox be between the label and text field

**Comment by noahgelman** [comment]
@rtwell That's it 👍

**Comment by ERRonat0609** [comment]
@rtwell  OK, so now that we have that straight, :-)  what do we need the spacing to be between the checkbox and the SSN field label?

**Comment by rtwell** [comment]
exactly what I have there ☝️ 

from element to element it looks like 3 spacing units, but I'm not familiar with the default spacing built into the elements themselves.

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2771&group_by=cases:title&group_order=asc
Test case: https://afs365.sharepoint.com/:x:/r/sites/DGIBillServicesProject/Shared%20Documents/Legacy%20AO/Team%203/QA/Test%20Results/AFS-Sprint%205/EDU%20Forms-%20Update%20spacing%20on%20SSN%20fields%20in%20forms.xlsx?d=w65b1a5a3f73b4321a978cc9d24d8d3ad&csf=1&web=1&e=LkJAkk
