### ISSUE TITLE
Fetch the tome-sync data for content builds

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2699]
## Problem Statement
We need to fetch the tome-sync content in the build process.

## Acceptance Criteria
- [ ] This feature doesn't disrupt the current content build process (yet)
- [ ] The cms export content is fetched and untarred
- [ ] The cms export tarball is cached when `drupal-aws-cache.js` is called with `--use-cms-export`
- [ ] The cached cms export is fetched with `drupal-aws-cache.js --use-cms-export --fetch`
  - [ ] The tarball is untarred at the location `--cms-export-dir` specifies

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
Unticketed dependency: The CMS export (tome-sync export) is saved somewhere (S3) where we can fetch the latest version.

**Comment by ncksllvn** [comment]
@ElijahLynn Can you link to your CMS PR so that we can see when this becomes actionable for us?

**Comment by ncksllvn** [comment]
Actually, it looks like the Tome-Sync Drupal implementation is tracked here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/2988, although it just references an Atlassian issue.
