### ISSUE TITLE
Refine Existing Home Page Canary Based on Stakeholder Feedback

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26997]
# Description
Per the this [thread ](https://dsva.slack.com/archives/CJRQ85PQB/p1624307675346800)of discussion regarding image loading and other issues on the VA.gov homepage, we need to make changes to the canary in order to accommodate new feedback. Ideas pulled from that thread include --

## New Acceptance Criteria
- [x] Refactor Canary to distinguish between `console.log()` and errors (console vs. pagerror seems to solve this: https://stackoverflow.com/questions/47539043/how-to-get-all-console-messages-with-puppeteer-including-errors-csp-violations)
- [x] Also scan for these errors in [DataDog](https://dsva.slack.com/archives/CJRQ85PQB/p1624988174464500?thread_ts=1624307675.346800&cid=CJRQ85PQB)?
- [x] [Blacklist ignored errors](https://dsva.slack.com/archives/CJRQ85PQB/p1625167109487100?thread_ts=1624307675.346800&cid=CJRQ85PQB) (this doesn't seem to be part of a change to the canary)

**Comment by rjohnson2011** [comment]
Created a PR to refactor the page event listeners on the `build-error-check` canary. 
https://github.com/department-of-veterans-affairs/devops/pull/9606

@pjhill If scanning for errors in DataDog remains a priority, it makes sense to separate those concerns into its own `datadog` ticket & standalone canary check. Does that sound good?
