### ISSUE TITLE
0994: Add aria-describedby to form submit button

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#26995]
As a developer, I need to add a describedby aria attribute to the form submission button so that users with accessibility issue can have the confirmation content reconfirmed on form submission.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria
1. The "Submit application" button has a aria-describedby="[By submitting this form content UNIQUE ID]"

## Supporting Artifacts:
1. Originating Issue: #26936

**Comment by AdamFreemer** [comment]
Need clarification and confirmation on which button this card references. There are many submit buttons on the form, but my best guess is this is the one in question (see screenshot). Need confirmation from client. It seems other folks working on this card were BAH and are no longer here. 

![Screen Shot 2021-11-02 at 2.16.33 PM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/e14bce3f-46f4-4aea-babb-f46f5bffdd53)

**Comment by AdamFreemer** [comment]
Clarification on issue noted below.

![Screen Shot 2021-11-03 at 12.08.34 PM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/b9d8e499-855d-466f-8ae5-020493098eaf)

**Comment by AdamFreemer** [comment]
Deployed QA / Review container: http://06e5fd8762a1f1d1442d4f47eff8f1b0.review.vetsgov-internal/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/review-and-submit

**Comment by dbarnes-VA** [comment]
Test Run: https://dsvavsp.testrail.io/index.php?/runs/view/2573

**Comment by dbarnes-VA** [comment]
Test Script: [https://app.zenhub.com/files/133843125/38152470-ac17-46f4-b0ac-96a47727cabd/download](https://app.zenhub.com/files/133843125/38152470-ac17-46f4-b0ac-96a47727cabd/download)

**Comment by dbarnes-VA** [comment]
Validated in Staging, Submit button now has the aria-describedby attribute. See highlighted element line.
 ![26995.png](https://images.zenhubusercontent.com/612faf5311d1aa63424e2351/d4802b9e-d544-4aa6-a191-0b3cac577bbc)

**Comment by mrblanco1** [comment]
Waiting for Katie approval (OCTO).

**Comment by dbarnes-VA** [comment]
Test Run: https://dsvavsp.testrail.io/index.php?/runs/view/2583
**Performed on Prod server.**

**Comment by dbarnes-VA** [comment]
Test Script: 
[0994- Add aria-describedby to form submit button(prod).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7563813/0994-.Add.aria-describedby.to.form.submit.button.prod.xlsx)

**Comment by dbarnes-VA** [comment]
Validated in production (va.gov) for testing the following assumption: "This work does not require a prod or feature flag."
<img width="1278" alt="26995(prod)" src="https://user-images.githubusercontent.com/88742213/142442750-d0bcd694-fee4-454c-a599-e26113a609ac.png">
