### ISSUE TITLE
Strategize for summer edition (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27003]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [x] Alert Joanne and Carol that we are -not- publishing a July newsletter
- [ ] Determine when the summer edition should be released

Strat:
- Schedule the pair writing sessions
- Revise the draft 

# Acceptance criteria

- We have a modified schedule for the summer edition

# Reference info

- [Operational docs - Products and services space](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1582891050/Platform+Newsletter)

**Comment by lianilychee** [comment]
Weds 7/7:
- Amy drafting strat tomorrow, and will share in SU on Thurs

**Comment by lianilychee** [comment]
Thurs 7/8:
- will send over slack today!

**Comment by amygoldman** [comment]
July:
- Schedule PW sessions with Carol and Joanne & their subject matter experts for next week (week of 7/12)
- Prepare for PW sessions by doing a preliminary revision of Carol and Joanne’s newsletter submissions and determine which questions from the PW script are relevant for their sessions by EOD Tuesday 7/13 
- Revise blurbs based on feedback from PW sessions by EOD 7/16 & share with Carol, Joanne, Rachael, and subject matter experts for review 
- Revise blurbs based on feedback ... between now and August

August:
- call for August submissions on Wednesday (7/21 or 7/28?)
- Schedule PW sessions with PMs who submit blurbs in August & their subject matter experts for the week of 8/9
- Revise August submissions based on feedback from PW sessions for the first round of review by EOD Friday 8/13 
- Request feedback by EOD Tuesday 8/17
- Follow up with Carol and Joanne by Friday 8/13 to ensure their newsletter blurbs are still up-to-date 
- Share with PMs, subject matter experts, and Rachael for review by Friday 8/20
- Share MailChimp version with Rachael by Friday 8/27 
- Publish July/August edition of newsletter on Monday 8/30 or Tuesday 8/31

**Comment by lianilychee** [comment]
7/9:
- Amy seeking feedback!
- could schedule pair writing sessions

**Comment by lianilychee** [comment]
decision: end of august tentatively but ask joanne and carol if there is urgency behind their submissions

**Comment by lianilychee** [comment]
7/12 monday:
- amy will let joanne know that, change of plans and we're not publishing a july issue
