### ISSUE TITLE
R&S updates: Life insurance if you have preexisting conditions

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#27000]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/life-insurance-if-you-have-preexisting-conditions/):  

- Intro: Replace the current last sentence of intro with the following:
**Keep reading this page to learn about preexisting conditions and what to do right now to get insurance.** 

- Under related information:  We have "Life insurance dividend payment options" Because there are dividend rumors we're trying to combat, balance this link by also adding a link to the legacy special dividend rumors page: 
**Special dividend rumor**
https://www.benefits.va.gov/insurance/dividends_special.asp

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make these changes in Drupal. 
Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Both of the above edits/additions you're recommending look good. Just minus "this page."

**Comment by lwalsh617** [comment]
@RLHecht - I made the edits per Beth's comment ^ and the top of the ticket. One thing, when I added the link under related info, Linkit wouldn't find it. Maybe because it's a legacy page? I dropped it in as is. Let me know if there's a different way to handle legacy page links. Thanks!

**Comment by RLHecht** [comment]
@lwalsh617 Thanks, Laura! Yes, Linkit only recognizes it if it's a Drupal page. If it's not, you have to just enter in the full URL rather than search for the node.

Reviewed and published this page.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
