### ISSUE TITLE
R&S Updates:  Life insurance dividend payment options

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#27001]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/life-insurance-dividend-payment-options/):  

- Intro: Replace last line of intro with the following:
Keep reading this page to learn about your options for receiving or using your dividend.

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make the change above in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
Keep reading ~this page~ to learn about your options for receiving or using your dividend.

Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - I made the edit to the intro per Beth's comment ^ and the top of this ticket. Ready for you to edit and publish. Thanks!

**Comment by RLHecht** [comment]
These page is reviewed and published. Moving to validate and will close after it's live on the site.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
