### ISSUE TITLE
Host office hours for Eng teams' audits

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27005]
# User story

As a Platform Eng team member, I want to understand Content's audit guidance, so that I can prioritize what/how to transform my team's documentation.

# Tasks

- [ ] Remind people that there are office hours
- [ ] Host office hours

# Acceptance criteria
- To come.

# Reference info
- n/a

**Comment by gmaciolek** [comment]
Looking at the name of this ticket, I just realized that we might not be aligned on the purpose of office hours. I don't think we should limit the focus of office hours to a specific topic. I want people to show up and ask questions about anything Platform content-related. I don't even care if it's about how to write a better operational doc. 😄  I see this an opportunity to develop partnerships with people on the Platform and improve overall awareness of content best practices. Platform website audits are a specific subset of that.
