### ISSUE TITLE
R&S updates: How to find out if you should get a higher TSGLI payment

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#27002]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/):  

- Under related information, add [TSGLI Loss Standards](https://www.benefits.va.gov/insurance/tsgli_schedule_Schedule.asp)

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make the change described above in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Yes, go ahead and add this related link if you've assessed it and it makes sense based on this R&S article topic.

**Comment by lwalsh617** [comment]
@RLHecht - I made the change at the top of this ticket. It's ready for you to review and publish. Thanks!
http://preview-prod.vfs.va.gov/preview?nodeId=15172

**Comment by RLHecht** [comment]
This page has been reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
changes are live
