### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#27013]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the `department-of-veterans-affairs/vets.gov-write` org. Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: kreek
- Reason access is required: The mobile api makes use of a couple Sidekiq jobs that may require monitoring and debugging during app beta testing (going on now) and after launch (in a couple of weeks).

**Comment by jeff2d2** [comment]
Added on 7/6/21
