### ISSUE TITLE
CT Redesign: Can't search by name

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#27014]
## Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=name
2. Search on a school
3. Observe error

![Screen Shot 2021-07-07 at 7.48.52 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d2acebde-e985-418c-890d-5a1a4f804512)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/841

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/9539

**Comment by sonntag-adam** [comment]
Fixed in staging.
