### ISSUE TITLE
R&S Updates: What if I don't want a fiduciary anymore?

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#27012]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/what-if-i-dont-want-a-fiduciary-anymore/):  

- 2nd CTA button:
Change label to make it clearer: 
**Appeal a fiduciary claim decision**

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Let's do this: Learn about your decision review options

Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - I made the edit per Beth's comment ^. Ready for you to review and publish:
http://preview-prod.vfs.va.gov/preview?nodeId=8540
Thank you!

**Comment by RLHecht** [comment]
This has been reviewed and published. Will close after live on the site.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
