### ISSUE TITLE
Search results discrepancy between map and list

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2701]
**As a user, I expect the list of search results to be consistent with those displayed on the map so that I can use either presentation to find my location.**

**Steps to reproduce:**
- On the Facility Locator page, enter "Spokane, Washington" in first search box and VA Health in the facility type box.
- Observe 4 results appear in list.
- Observe 3 locations marked on the map. 

**Acceptance criteria:** pending product and design decisions

**Comment by mmiddaugh** [comment]
@davidconlon, @arickalewis1 and @mmiddaugh will determine expected behavior for identical lat/long results based on industry handling for maps, etc.

**Comment by davidconlon** [comment]
This issue may be usurped by the desire for the industry standard "search this area"

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/7d02cb54-058a-4a1b-8bc9-cbfff937eae9)

**Comment by mmiddaugh** [comment]
Keep an eye on with Mapbox/redesign

**Comment by mmiddaugh** [comment]
Closing this issue as this has been added as acceptance criteria for [#4324].
