### ISSUE TITLE
R&S updates: How to set up direct deposit for VA travel pay reimbursement

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#27011]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/):  

- Intro:
Add "keep reading"  language so user knows not to hit CTA buttons:
**Keep reading this page to find out how to set up direct deposit so we can deposit your reimbursement directly into your bank account.** 

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make this change in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Keep reading ~this page~ to find out how to set up direct deposit so we can deposit your reimbursement directly into your bank account.

Note: Danielle and I are going to wait to insert "this page" until we're able to do some testing. I know we all had talked about it on a call. Let's hold off for now.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Can we move forward with this?

**Comment by lwalsh617** [comment]
@RLHecht - I made the change per Beth's comment ^^. It's ready for you to review and publish. Thank you!

**Comment by RLHecht** [comment]
Reviewed and published. Will close after next deploy.
