### ISSUE TITLE
Access for Brooks Johnson

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#2702]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Brooks Johnson
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Tools & Improvements - Frontend Engineer - Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf20tQxnbq2ACQo5VlvIJDBIbTFDcvRiHWOdxz    RCHCi3U7G5MGpEE7fxgca8N2mhmUGWHatLpvKsatnNKCYugG+LqCnLKa401snk4rxr0+CMJTACag    8W6pC/qXWjjBXrljhLLKs7Iq9HqZO6Jo5UfOIgLChhj23sZ4VfPtUMOPt52+8LuyMDlHo2e0ugV7    /EOo617KvCp25murkaSwggimppwaCJsK7xAQWmcfsE9qIrAjezkXOLg/VCKt2rF4ubAeI6hDsueR    V7xEHxFAlGVjgZCeC4CsGiM85ayL1RLyfv3Jg/laI2rkWSl+PPFsT8L1Mlz0Tzk9I5kY0aQmFyn1     brooks@adhocteam.us

- [Grant AWS Console access?]
  > NO

**Comment by bkjohnson** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter
COR: Yourself
User: Brooks Johnson

**Comment by Jeff-Hayter** [comment]
@ricetj Confirmed, please grant access.

**Comment by tskinn** [comment]
@bkjohnson your key has been added. Contact us in slack if you have issues connecting.
