### ISSUE TITLE
State level Search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2703]
**As a user, when I search by state, I expect .... (TBD)

**Current functionality:**
State level searches result in different experiences, depending on the state. 

- **a single location (often in the center of the state)**
- Example: Search Washington (state) and VA Health: Observe the list returns 1 result. 
![image](https://user-images.githubusercontent.com/55411834/68710706-e83a2700-054c-11ea-8d7f-2439d73312d0.png)

- **a list of facilities, extending beyond the state itself**
- Example: Search Massachusetts (state) and VA Health: Observe the list returns 18 results, including locations in Massachusetts, Rhode Island, New Hampshire and Connecticut. 
![image](https://user-images.githubusercontent.com/55411834/68711684-fe48e700-054e-11ea-9285-8b4ba1b66d00.png)

- **more than a single location, but restricted to those within the state**
- Examples: Search Kansas (state) and VA Health: Observe the list returns 2 results. Search Florida (state) and VA Health. Observe the list contains 14 results.

![image](https://user-images.githubusercontent.com/55411834/68711955-934be000-054f-11ea-978f-a62bff5048f2.png)
![image](https://user-images.githubusercontent.com/55411834/68712144-f3428680-054f-11ea-9c68-1227c1c31108.png)

**Expected results**

1. Should the search using "Washington" return all locations in the state, which should be **at least** 11, based on these separate searches? (In reality, the list in Washington is significantly longer.)

2. What logic causes only one to be returned and how is the one selected?

**Comment by mmiddaugh** [comment]
@jellis-gcio as part of our Discovery sprint, please use this and https://github.com/department-of-veterans-affairs/va.gov-team/issues/2405 to help you investigate our data quality issues and document the following:
1- What is the json output for the API *currently* called by our Facility Locator? (For each facility type: VA Health, Benefits, Vet Centers and Cemetery)
2- What is the json output for the Facilities API? (For each facility type: VA Health, Benefits, Vet Centers and Cemetery)
3- What is the json output for the API which is called for urgent care and community care facilities?
4- What are the differences in output between the two pathways?
5- For community care, where does the duplication in service and description originate?

@jellis-gcio, please work with @brangi to understand how the backend is being translated and displayed in the UI

**Comment by jellis-gcio** [comment]
uploaded to drive and GitHub (commit: b512a9edbb8861b67400f43ec7245bcba386cde0)

**Comment by mmiddaugh** [comment]
Reopening this as the awkward search result issue has not been resolved.  

Found the following in a closed legacy ticket [11436] (https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11436): 

>The facility locator on Vets.gov is based on proximity from a search term. If you enter a zip code or an address, you get results within a bounding box (I believe it's 25 miles X 25 miles) around a point that represents your search term. Problem is that if you search for a state users expect to see all results in that state but the current behavior is that the third party mapping software returns a point for the search term (probably somewhere within that state) and we display results within a box around that point.

**Comment by jellis-gcio** [comment]
@mmiddaugh my research concluded it’s based on what the front-end is requesting. There’s also an issue where searching by state pulls up two different result sets when initially searching, and when reloading the page (and the state is searched via auto fill).

**Comment by mmiddaugh** [comment]
@davidconlon @arickalewis1 we need to discuss expectations for search experience here

**Comment by mmiddaugh** [comment]
This should be resolved by recent query changes and upcoming updates to the user-map interaction.
