### ISSUE TITLE
Content review - Warning modal triggered when someone removes contact information from profile.

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#27037]
We heard in a [recent research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/notifications-research-findings.md#all-participants-easily-understood-how-to-remove-contact-information-but-some-wanted-more-information-about-the-impacts-of-doing-so) that Veterans want clearer information about the impacts of deleting their contact information.  We're proposing to update the content in the warning modal from what we showed Veterans in our prototype (click remove to trigger modal), to content similar to what we're using on our [resources and support page](https://staging.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-online-in-).

Submitting copy for review below.  Our [specs for this work](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md) include mock-ups if you'd like to reference what we're working on, or you can see it in action by clicking `remove` in contact email section of[ this prototype](https://preview.uxpin.com/5ecec4de6ec34eddc9f095677a881be3646124ce#/pages/139109680/simulate/sitemap?mode=i).

If possible, we'd love to have feedback by 7/13 EOD so we our FE team can work on this in the sprint starting 7/14.

**Heading**
Are you sure?

**Body**
Your [contact information] will be removed across these VA benefits and services:

- [If user has health care] VA health care (including prescriptions, appointment reminders, lab and test results, and communications from your VA medical center)
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)
- [If user is removing contact email or mobile number, and has opted into notifications] You will no longer get [email or text] notifications you signed up for.

[If user is removing contact email] You will still be able to login to VA.gov.

You can always come back to your profile later if you want to add your [contact information] again.

**Buttons**
Primary
Yes, remove my information

Secondary
Cancel

**Notes:** 
- I'm purposely keeping the label on the primary button generic (information vs "contact email address") to prevent the button wrapping into two lines on mobile with longer labels. I like having the `Yes,` affirmation on the label.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. Was able to work this in today. Just a few tweaks:
- Making lead-in to bullets active voice
- Making the notifications bullet parallel in structure so it works with the lead-in and tweaking wording
- Bringing the last 2 sentences together so they flow a little more, and tweaking wording a bit

Feel free to slack me with any questions or additional thoughts on this!

Heading
**Are you sure?**

Body

This will remove your [contact information] across these VA benefits and services:
- [If user has health care] VA health care (including prescriptions, appointment reminders, lab and test results, and communications from your VA medical center)
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)
- [If user is removing contact email or mobile number, and has opted into notifications] VA notifications. This means you'll stop getting any VA [email or text] notifications you signed up for.

You can always come back to your profile later if you want to add your [contact information] again. [If user is removing contact email] And you can still sign in to VA.gov even after you remove your contact email address.

Buttons
Primary
Yes, remove my information

Secondary
Cancel

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA Thanks for taking care of this so quickly! I appreciate the feedback and have updated our specs accordingly.
