### ISSUE TITLE
Change URL in sitemap for R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27034]
## Issue Description
Sitewide Content is changing the H1 and URL for the R&S article [What if I'm having trouble opening a PDF?](https://www.va.gov/resources/what-if-im-having-trouble-opening-a-pdf/what-if-im-having-trouble-opening-a-pdf/) and we need to change this on the sitemap. 

When published the new H1 will be **How to download and open a VA.gov PDF form** so the new URL will be: 

https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form

More info to follow in ticket #26704

---
## Tasks
- [x] Update URL in sitemap

## Acceptance Criteria
- [x] New URL is now in sitemap

**Comment by RLHecht** [comment]
@brianalloyd @johnhashva Wasn't sure who to tag in this one but let me know if you have questions about the info above. We should be publishing the page with the new URL this week.

**Comment by bethpottsVADEPO** [comment]
@brianalloyd and @johnhashva Do you have a sense of when this work could be done so I can time it with publishing our R&S article changes?

**Comment by johnhashva** [comment]
@bethpotts brian is out on vacay thru next Monday -- can @brianalloyd get back to you then?

**Comment by bethpottsVADEPO** [comment]
@johnhashva  Sure--no problem. @brianalloyd want to check in with me about timing when you're back?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you work with @brianalloyd on the timing of this?
