### ISSUE TITLE
CMS Sandbox Access

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27049]
## High Level Story

Get new engineer set up with access to CMS sandbox and a local build so he can start working on testing and demoing some programmatic approaches in support of in-language content. 

# CMS Sandbox Info:

- CMS URL: https://localization-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/
- Web: https://web-nwlghnqkwe3ftxcgy830jkfejcxjswak.demo.cms.va.gov/
- Tugboat page for refreshing with the latest content: https://tugboat.vfs.va.gov/60d1020d4fa3231be8d58007 
- Documentation in the CMS help center with a Tugboat training video and some common how-tos: https://prod.cms.va.gov/help/how-to-access-and-manage-demo-environments

**Comment by adamwhitlock1** [comment]
I now have access to tugboat, our cms sandboxes, and can create new sandboxes as need.
