### ISSUE TITLE
Invalid Date in Message List

### ISSUE THREAD

**Issue by Teesh** [department-of-veterans-affairs/va.gov-team#27044]
## What happened?
The first message in each Draft message thread in the iOS simulator showed an Invalid Date
![Screen Shot 2021-07-07 at 12.57.58 PM.png](https://images.zenhubusercontent.com/608716c8425a91126d5ff063/9e1fd64d-22e7-4190-90d9-a1ea38250aae)

## Specs:
- Device: Xcode iOS simulator (iPhone 12 Pro Max)
- Test User: Melvin Freeman (261 or 41)

## Steps to Reproduce
Log in with user
Go to Health > Messages > Drafts and select one of the draft messages to open the thread

## Desired behavior
The Invalid Date should be replaced with a valid parsed date

## Acceptance Criteria
- [ ] No dates in the drafts messages should show up as invalid

## How to configure this issue
- [ ] **Attached to Epic** (`Drafts`)
- [ ] **Labeled with Team** (`secure-messaging`)
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with `Bug`**

**Comment by narin** [comment]
Closing this out, since tapping on a draft within the drafts list will take them to the Edit Draft form, not the message thread.
