### ISSUE TITLE
"Compose a Message" button requires tapping twice to compose message and remains in tapped state upon return

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#27052]
## What happened?
When I tap the "Compose a Message" button, it remains in the dark blue "tapped" state.
I must tap the button again to get an action.
Upon returning to the screen from the compose screen, the button is still in the "tapped" dark blue state.

Happens with iOS and Android.

## Specs:
- Device: Android Galaxy Note 9, iPhone XR

## Steps to Reproduce
- Go to messages
- Tap Compose a Message button (notice it turns blue but does nothing else.)
- Tap Compose a Message button again (this time it goes to the compose screen.)
- Cancel and return to inbox (notice Compose a Message button is still dark blue in the "tapped" state.)

## Desired behavior
Tapping Compose a Message button takes use to the compose screen with one tap and is not in the tapped state upon return to the inbox.

## Acceptance Criteria
- See Desired behavior.

## Bug Severity
- 3 - Medium

## Linked to Story
n/a

## Screen shot(s) and additional information

https://images.zenhubusercontent.com/133843125/d8cd1ac3-b81a-4399-b3e2-9bf340278568/composebutton.mp4

**Comment by rarroyo23** [comment]
Cannot reproduce the bug following the steps provided.
Tested On: Latest develop branch
OS: Android and IOS 

IOS test: (Physical)

https://user-images.githubusercontent.com/34731551/125340401-6e110580-e320-11eb-9b8e-95b0f0eda026.MP4

Android Test: (Emulator)

https://user-images.githubusercontent.com/34731551/125342702-33f53300-e323-11eb-8e56-0c5b7d4fde3c.mov

**Comment by digitalken** [comment]
PASS 7/14/2021 - Now I'm no longer able to reproduce the bug, either.  Closing.
