### ISSUE TITLE
Use CMS export in content build

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2706]
## Problem Statement
We need a way to get the CMS export (tome-sync data) into the build pipeline.

## Acceptance Criteria
- [ ] This feature doesn't disrupt the current content build process (yet)
  - This includes the GraphQL query for the normal, still-relevant build until we can make the switch
- [ ] A flag can be passed to the build script which tells it to use the CMS export process instead of GraphQL for fetching the nodes
  - We'll still want to keep all the sidebar nav queries for now, but we can remove the largest chunk of the query (or at least the result)
- [ ] The hub queries for sidebar navigation menus still use GraphQL
  - We're only pulling out the query for nodes

**Comment by cvalarida** [comment]
I originally marked this as blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/2699, but we can still manage to run the CMS export data through the build process without fetching and un`tar`ing the data first if we temporarily require a directory sibling to `vets-website` with the CMS export data.

**Comment by cvalarida** [comment]
Unmarking https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835 as a dependency since we can use a small subset of these entities. I wrote [this script](https://github.com/department-of-veterans-affairs/vets-website/pull/11250) to copy over a single node (page) to a new directory with all its required descendant entities for just this purpose.

**Comment by bkjohnson** [comment]
Here is confirmation that the build using tome-sync content will load in the browser as was requested [here](https://dsva.slack.com/archives/CQH357ZTP/p1578336893053800).

First, I modified one of the node-files in the content directory by adding `TESTING` to the title:

![image](https://user-images.githubusercontent.com/2008881/71916636-3d507e80-3133-11ea-85bb-101550c11c18.png)

(This is in `node.410f20c7-e49b-4289-8759-ee34d8b6432a.json`)

Next, I ran `npm run watch -- --use-cms-export --cms-export-dir ~/Projects/test-tome-sync-output/content`

Here is what the content directory looks like:
![image](https://user-images.githubusercontent.com/2008881/71916791-902a3600-3133-11ea-8341-b96a4b61e851.png)


After the build finishes and I navigate to `/change-address` I can see that the change I made is in effect:

![image](https://user-images.githubusercontent.com/2008881/71916500-ed71b780-3132-11ea-90bf-73e042d79fcc.png)
