### ISSUE TITLE
EVSS Form526 Validation 

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27069]
## Issue Description
EVSS has provided [list of validations](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/support).

---
## Tasks
- [ ] Review validation list and determine updates we need to make on frontend.

## Acceptance Criteria
- [ ] Documented findings.
---

**Comment by kevinstachura** [comment]
We might make this an epic. @vhenry07 please help us

**Comment by vhenry07** [comment]
Tabling this work due to Lighthouse migration.
