### ISSUE TITLE
EVSS fix - get data

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27075]
## Issue Description
Get a list of veterans affected by the EVSS service date bug.  (starting april 1, 2021).  
exclude veterans who have submitted a claim after they experienced the error.

As with previous error communication get
Name, Email, EDIPI

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
😢 The EVSS "fix" was reverted because it had a bug.

**Comment by annaswims** [comment]
once the error is fixed, this will do the trick:
````ruby
# frozen_string_literal: true

ids = Form526JobStatus.where(updated_at: [(DateTime.new(2021, 4, 1))..Time.zone.now]).where.not(status: 'success').where("error_message like '%180%'").pluck(:form526_submission_id).uniq

incomplete_submissions = Form526Submission.where(id: ids, submitted_claim_id: nil)

@edipis = []
CSV.open('tmp/service_dates.csv', 'wb') do |csv|
  csv << %w[form526_submission_id form526_submission_date first_name last_name edipi SSN email_address later_completed_dates_and_claim_ids disabilities]
  incomplete_submissions.each do |fs|
    form_json = JSON.parse(fs.form_json).dig('form526', 'form526')
    disabilities = form_json.dig('disabilities').collect { |d| "#{d['disabilityActionType']}:  #{d['name']}" }
    later_completed_dates = Form526Submission.where.not(submitted_claim_id: nil).where(user_uuid: fs.user_uuid).where('created_at > ?', fs.created_at).pluck(:created_at, :submitted_claim_id).join(',')
    email_address = form_json.dig('veteran', 'emailAddress')
    @edipis << fs.auth_headers['va_eauth_dodedipnid']
    csv << [fs.id, fs.created_at, fs.auth_headers['va_eauth_firstName'], fs.auth_headers['va_eauth_lastName'], fs.auth_headers['va_eauth_dodedipnid'], fs.auth_headers['va_eauth_pnid'], email_address, later_completed_dates, disabilities]
  end
end
````

**Comment by annaswims** [comment]
I have a CSV with 
`form526_submission_id,form526_submission_date,first_name,last_name,edipi,SSN,email_address,later_completed_dates_and_claim_ids,disabilities`

 4,057 veterans faced the error and have not submitted a claim on va.gov after that.
