### ISSUE TITLE
[FE] Profile: Long email addresses break Profile layout

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27072]
## Background
As reported in [slack](https://dsva.slack.com/archives/C909ZG2BB/p1625699754078400), long email addresses break the Profile layout:

<img width="741" alt="Screen Shot 2021-07-07 at 4 15 09 PM" src="https://user-images.githubusercontent.com/45603961/124935269-81943780-dfd3-11eb-9f4f-3ef0ce57b157.png">

## Task
- [x] Consult with @andaleliz as needed for how best to handle this
- [x] Implement the fix

**Comment by erikphansen** [comment]
@ajakabcin I don't think we really need Liz to weigh in on this. I _think_ we could make the email address break/wrap at symbols (`@`, `-`, `.`) first (by adding in hidden spaces) and also potentially have it force-wrap (by using `word-break: break-all;` or `overflow-wrap: break-word;`) even if wrapping at symbols does not accomplish what we need. Example: if an email address was something like `thisisbyfarthelongestemailaddressihaveeverseeninmylife@gmail.com`

**Comment by ajakabcin** [comment]
Confirmed on staging
