### ISSUE TITLE
Contact Center Review for [Caregivers, Improve File Upload Error Messaging]

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27070]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The online 10-10CG form (Program of Comprehensive Assistance for Family Caregivers) launched in October 2020. In May, 2021 an enhancement was launched that allowed caregivers to upload Power of Attorney documents and sign as a representative on behalf of the veteran. 

We have noticed intermittent errors occurring when the user attempts to upload a file. (Note: this issues appears to affect many forms on Va.gov). The default errors messaging was not very helpful to the user. Therefore, the purpose of this new enhancement is to do 2 things:

1. Replace the default generic error messaging with better error messaging that instructs the user on how to address the error.
2. Replace the default "Delete File" button that would appear with the error message with a better set of buttons, such as "Try Again" and "Cancel".

_Note these messages only appear when a file upload error has occurred and not during the normal course of the flow._

### Launch Date
*Please provide the launch or rollout date and details.*
Target: July 23 (or sooner). Will rollout matched with the current dial-up percentage of the Sign as a Representative functionality, which is currently at 50%. Would then go to 75% and then 100% based on observed usage.

### Version Number
*Please provide the version number of the guide and/or video.* Version 1.1.1

### Product Guide
[Link to Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/Online-10-10CG-Product-Guide.docx)

_Note: Main changes are on pages 39 and 40_

### Product Video
Given the change is just an improvement to an existing error message, which is an edge case, I'm not planning on updating the video.

### Product Video Transcript
See note above.

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by tchrisdyer** [comment]
Note the primary change in this enhancement is changing the error messaging the is displayed when a file upload error occurs due to an unknown network error.

Original messaging:
![image](https://user-images.githubusercontent.com/48114189/124936784-d7b5aa80-dfd4-11eb-84de-6b48b331bcff.png)

New Messaging
![image](https://user-images.githubusercontent.com/48114189/124936360-755caa00-dfd4-11eb-9799-24ed8202f08e.png)

We did add separate messaging for several other scenarios:
1. File too big
2. File too small
3. Wrong file type

**Comment by Kimberley2019** [comment]
@tchrisdyer is this ready for a CC review?

**Comment by tchrisdyer** [comment]
@Kimberley2019 The change is in staging. I still need to update the Product Guide which I will attach shortly. I'm hoping the change is small enough that I won't need to update the Product Video or Transcript.

**Comment by tchrisdyer** [comment]
@starlow00 @jwoodman5 @Kimberley2019 I've updated the Product Guide with the new error messages. Please let me know if there is any feedback.

**Comment by starlow00** [comment]
Hi @tchrisdyer. The product guide looks great with the change/additions. I'll make sure VEO has the updated copy. While I don't think the original video/transcript needs to be changed, I would advise at least recording an addendum at some point with the 3 additional error messages covered.

**Comment by starlow00** [comment]
Provided updated guide to VEO, awaiting review/comment.

**Comment by starlow00** [comment]
No changes from VEO. Will attach copy shortly.

**Comment by starlow00** [comment]
[Online-10-10CG-Product-Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6857369/Online-10-10CG-Product-Guide.docx)
