### ISSUE TITLE
Access for Alexander Garcia

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#27073]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Alexander Garcia
- Please Provide your email.
   > agarcia@clarityinnovates.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Identity team within VSP. I am the Frontend Engineer for Oddball.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

- Grant AWS Console access?
  > YES
  - Requires additional access.  I need access to AWS Cognito added to my permissions.  I will require write permissions to be help prototype concepts for identity related ideas.
  - *Note I think my AWS password has expired because I am unable to login 😓 
Thank you again!

**Comment by AGarcia-Clarity** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
Cognito power user access granted in the referenced pull request [#9538](https://github.com/department-of-veterans-affairs/devops/pull/9538).

**Comment by jbritt1** [comment]
Please reopen if any issues are observed or if we need to adjust permissions further.
