### ISSUE TITLE
General Analytics Request for Contact Center Support Team

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#27087]
# General Analytics Request

## What this form is for

Use this template to request support for analytics that need interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description

Chante Lantos-Swett - OCTODE lead for the contact center support team - chante.lantosswett@va.gov

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data, link to this Github issue, and tag `@platform-analytics`._
    
- What team/project is this work for?

   contact center support team - AVA 
    
- What type of analytics support are you looking for?
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze: ASAP

## Analytics to Track Down
> Examples
> 
> - [ ] numbers of authenticated vs unauthenticated visitors to VA.gov for the past 30 days
> - [ ] breakdown of VA.gov authenticated accounts by LOA. 
> - [ ] Metric 3

## Other Helpful Questions to think through
- Who is your audience? VA Stakeholders
- Why do you need this data? For a meeting to discuss some implementation questions as it relates to a new support system being built
- What are you hoping to find? 
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data? One time. 

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
one off report for the above requested metrics. 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jennaouellet** [comment]
Hi @clantosswett 
You can use a Segment to differentiate between authenticated users vs. unauthenticated users with the Segment name "VA.gov - Session - Authenticated - LOA Present". 

Here is an example:
https://analytics.google.com/analytics/web/?authuser=1#/report/visitors-overview/a50123418w177519031p176188361/_.useg=useri0ZvPaPpQKyUHGrYCFPigw,userXZpoGov_R4K1a1Biwj2YNg
 
 This segment counts users at any LOA level. 
 
 
 To only segment authenticated users with a LOA level 3, I've created a filter on that segment here:
 
 https://analytics.google.com/analytics/web/?authuser=1#/report/visitors-overview/a50123418w177519031p176188361/_.useg=useri0ZvPaPpQKyUHGrYCFPigw,userXZpoGov_R4K1a1Biwj2YNg
 
 
 Please let me know if there are any additional items you'd like to track or if you have any questions. Thanks!

**Comment by joanneesteban** [comment]
Hi @clantosswett - does that report work for you, or do you need anything else from us? Thanks!

**Comment by clantosswett** [comment]
This was perfect and helped with some of the discussions I was having with VA stakeholders so thank you very much!

**Comment by joanneesteban** [comment]
Thanks, @clantosswett ! And thanks, @jennaouellet for your work and help here! Closing this ticket.
