### ISSUE TITLE
Possible bug in Letters app

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#2708]
Possible bug in Letters app at https://staging.va.gov/records/download-va-letters/letters/confirm-address route.

- sign in with user 228
- go to https://staging.va.gov/records/download-va-letters/ and click the green button to Get Your VA Benefit Letters.
- this directs you to https://staging.va.gov/records/download-va-letters/letters/confirm-address. the spinner eventually resolves to a blank page. console reports:
```
breadcrumbs.js:58 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at z (helpers.jsx:571)
    at t.value (AddressSection.jsx:22)
    at ji (react-dom.production.min.js:173)
    at Pi (react-dom.production.min.js:172)
    at Li (react-dom.production.min.js:180)
    at Ka (react-dom.production.min.js:232)
    at Ga (react-dom.production.min.js:233)
    at ju (react-dom.production.min.js:249)
    at Cu (react-dom.production.min.js:248)
    at Eu (react-dom.production.min.js:245)
    at Za (react-dom.production.min.js:243)
    at Object.enqueueSetState (react-dom.production.min.js:130)
    at u.w.setState (react.production.min.js:13)
    at u.l.onStateChange (connectAdvanced.js:205)
    at Object.notify (Subscription.js:23)
    at e.t.notifyNestedSubs (Subscription.js:62)
    at u.l.onStateChange (connectAdvanced.js:202)
    at Object.y [as dispatch] (redux.js:220)
    at e (<anonymous>:1:40553)
    at analytics-middleware.js:24
    at index.js:14
    at dispatch (redux.js:636)
    at letters.js:51
```

This might just have to do with user 228's data being funky, but it seems to indicate some fragile code somewhere in the redux chain.

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/17779fd7-2204-4f0e-a0d0-5ae81d8f2c29)

**Comment by erikphansen** [comment]
@ndsprinkle I'm afraid this might actually affect any Vet who has not been initialized in Vet360 (now known as VA Profile). If the `vet360ContactInformation` that comes back from the `GET user` endpoint is populated with null values:

![image](https://user-images.githubusercontent.com/20728956/69298748-a56af580-0bc3-11ea-8f96-1079470b3339.png)

the `user.profile.vet360` Redux data will also be null:

![image](https://user-images.githubusercontent.com/20728956/69298758-abf96d00-0bc3-11ea-91d0-746dc3394b7c.png)

which I think will lead to this error. I'm guessing the `MailingAddress` component (https://github.com/department-of-veterans-affairs/vets-website/blob/830f1b56c0e10b192b2cdd1fece1bad7a7237b39/src/applications/letters/containers/AddressSection.jsx#L28) will need to be wrapped in the `Vet360InitializeID` component like it is in the ProfileApp (https://github.com/department-of-veterans-affairs/vets-website/blob/dad806e2937c19b04e0a767d749492488963836f/src/applications/personalization/profile360/components/ContactInformation.jsx#L28-L54).

**Comment by erikphansen** [comment]
I mentioned above:

>  I'm guessing the MailingAddress component (https://github.com/department-of-veterans-affairs/vets-website/blob/830f1b56c0e10b192b2cdd1fece1bad7a7237b39/src/applications/letters/containers/AddressSection.jsx#L28) will need to be wrapped in the Vet360InitializeID component like it is in the ProfileApp (https://github.com/department-of-veterans-affairs/vets-website/blob/dad806e2937c19b04e0a767d749492488963836f/src/applications/personalization/profile360/components/ContactInformation.jsx#L28-L54).

_That is definitely the case_.

Not only to hopefully resolve the bug that I opened this issue for. But also because the behavior of editing addresses will change with this PR https://github.com/department-of-veterans-affairs/vets-website/pull/11091. When that PR is merged, address changes will no longer be submitted directly to  VA Profile (formerly Vet360) save/update endpoint. Instead the user-entered address will first hit a new address validation/suggestion API. And it's possible that that will trigger a new modal that will prompt the user to fix the address they entered or pick from a list of suggested addresses. _And that will break unless the MailingAddress component is wrapped in the Vet360InitializeID component._

Tagging @bradl3yC so he's aware of this issue, just in case the VSA Benefits team needs to reach out to the Authenticated Experience for any guidance since I'll be OOO the week of Nov 25.

**Comment by ndsprinkle** [comment]
Hey @erikphansen thanks for bringing this and #3664 to my attention. Sorry for the delay in response, I will bring this to the team's attention.

**Comment by Samara-Strauss** [comment]
Why have I been assigned to this ticket? Can I help with something?

**Comment by YanaRoy** [comment]
@Samara-Strauss no clue - you were on it originally, then i removed you accidentally, and then added back. And here we are.

**Comment by Samara-Strauss** [comment]
@YanaRoy I'll go ahead and remove myself. There's nothing actionable for me on this ticket AFAIK.

**Comment by ndsprinkle** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11362
