### ISSUE TITLE
Remove Circle CI logic from content-build repo tests

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#27085]

**Comment by CBonade** [comment]
There were two specs here that have been updated.  That said, it looks like CI builds have been failing so I can't get it to pass it's checks.  Both Nightwatch and Cypress tests look to be being skipped in content-build currently, but I've removed the logic just in case.

**Comment by CBonade** [comment]
Builds seem to be back on track today, so PR is open and checks are running.

**Comment by CBonade** [comment]
This is merged to master and approved to close.

**Comment by pjhill** [comment]
Excellent!
