### ISSUE TITLE
Create daily job to clean up erroneous TestRail data pushed to BigQuery. Only push seemingly accurate GitHub issues to BigQuery.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#27088]
Create a daily job to clean up erroneous TestRail data pushed to BigQuery. Set a condition for pushing new GitHub issues data to BigQuery.

Add a script to the Testing Tools Team Dashboard Data repo that:
- [x] Deletes erroneous data from `testrail_metrics` table
- [x] Call the script in a new GitHib Actions scheduled event workflow
- [x] Only push the updated/new GitHub issues to BigQuery if the number of issues seems correct

**Comment by holdenhinkle** [comment]
Draft PR for removing unwanted records from the BigQuery `testrail_metrics` table daily - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/44

It grabs the `created_at` values for records created the previous day. `created_at` is unique to each record and is a natural key.

If the result is only one `created_at` value, the scripts stops execution; there's nothing to delete.

If the result has more than one `created_at` value, we remove the most recent value (we want to keep that record) and we delete the other records.

I'll write the GitHub Actions workflow file now...

**Comment by holdenhinkle** [comment]
PR is merged - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/44

I'll add conditions for pushing Cypress results and GitHub issues to BigQuery first thing tomorrow.

**Comment by holdenhinkle** [comment]
https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/runs/3027953868?check_suite_focus=true

The job ran this morning:

```
Run yarn clean-bigquery-testrail-metrics-table
yarn run v1.22.10
$ node src/testrail/cleanMetrics.js
1 record removed
Done in 3.28s.
```

Yay!

**Comment by holdenhinkle** [comment]
PR for conditionally inserting GitHub and Cypress data into BigQuery - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/48

**Comment by holdenhinkle** [comment]
The Cypress test results data that has been pushed to BigQuery is highly variable. Here's a spreadsheet that lists some high-level numbers from the last 100 Cypress runs - https://docs.google.com/spreadsheets/d/1ahMVMfXkkLabJsTcTcR9muepJyCsl8GrSqY3cgSjYaU/edit#gid=0

I talked to Darius about this and he said that the Cypress tests are very unstable right now, for various reasons. He suggest that we not conditionally set what Cypress data can be pushed to BigQuery until the tests are stabilized.

I'll circle back to the Cypress part of this ticket later, once the tests are more stable, and open a different ticket for that.

This is done.

**Comment by pjhill** [comment]
This method seems solid. If an issue with noisy data seeping into BigQuery pops up again then we can work that under a new ticket.
