### ISSUE TITLE
React Widget addition from vfs-ebn-migration team

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#27099]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[x] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[x] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

The `/view-change-dependents` static page includes a react widget for the 686:
<details><summary>Widget and corresponding code</summary>

![Screen Shot 2021-07-08 at 12 30 05 PM](https://user-images.githubusercontent.com/15097156/124966003-5cf68a80-dfe8-11eb-8526-d99b06d1ce15.png)
![Screen Shot 2021-07-08 at 12 30 25 PM](https://user-images.githubusercontent.com/15097156/124966005-5cf68a80-dfe8-11eb-8f03-f265f52ea3ef.png)

</details>

This exact widget also needs to be added to `/disability/add-remove-dependent` by replacing the corresponding p tag that currently exists on that page:
<details><summary>P tag and link that needs to be replaced</summary>

![Screen Shot 2021-07-08 at 12 34 09 PM](https://user-images.githubusercontent.com/15097156/124966327-ce363d80-dfe8-11eb-9475-74fa7df2126e.png)
![Screen Shot 2021-07-08 at 12 34 30 PM](https://user-images.githubusercontent.com/15097156/124966370-daba9600-dfe8-11eb-98ff-0ad18e378e87.png)

</details>

## When does this content work need to be done?
Our team is already in a phased rollout, so we would prefer this to be done as soon as possible. Preferable date would be by Monday July 12th 2021 😬 

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Jason Wolf
-	Designer: Jim Adams & Candy Clark
-	FE engineer: Micah Chiang & Jesse Cohn
-	Product/team Slack channel: vfs-ebn-migration

## Links to related tickets
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26330

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
@micahchiang is the react code to put into Drupal **form-686-CTA**?

**Comment by micahchiang** [comment]
@RLHecht - yes that's correct.

**Comment by RLHecht** [comment]
@micahchiang Before I set the page to publish can you confirm this is correct?

![Screen Shot 2021-07-12 at 12.56.55 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b35421ce-3674-42be-ad18-32bb4c9906d2)

**Comment by micahchiang** [comment]
@RLHecht - yup that looks correct for when the feature toggle is turned off 👍 cc @jason-gcio

**Comment by RLHecht** [comment]
@micahchiang The page is published. Let me know if you all need anything else!

**Comment by RLHecht** [comment]
New widget live on site. Closing ticket.
