### ISSUE TITLE
Offboarding of Desiree Turner

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#27091]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Desiree Turner
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Team: VSA-education (BAH)
   > Role: Scrum Master 
   > Last day: 07/16/2021
   > Company: Booz Allen Hamilton
- Please provide any type of access they may have and their GitHub username. 
  > Access type
   - GitHub, @desireeturner 
   - Slack, Desiree Turner
   - Google analytics, desiree.turner@va.gov
  
 
## AC
 - [ ] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [ ] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [ ] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [ ] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [ ] Pagerduty access removed (if applicable) 
 - [ ] Datadog account disabled (if applicable)
 - [ ] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jennaouellet** [comment]
Google Analytics access removed, Domo not applicable

**Comment by desireeturner** [comment]
This request should not be effective until 07/16 (next Friday)

**Comment by desireeturner** [comment]
Closing this request because I think I submitted it a little early! Please don't remove any additional access
