### ISSUE TITLE
508 defect 2, screen readers, cognition, VA home page main navigation confusing and redundant

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#27098]
Label: 

    - [508-defect-2]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2

Issue Title: 508 defect 2, screen readers, cognition, VA home page main navigation confusing and redundant
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
Screen reader users expect a consistant and predictable experience when navigating a web page.
Users with cognative disabilities are often confused by redundant links.
<h2>Details</h2>
There are three items in the main navigation region, an accordian labeled "VA benefits and health care," an accordian labeled "about VA" and a link to the facility locator. This in itself is an inconsistant and potentially confusing presentation of the web site's main navigation.
The accordians within VA benefits and health care expand consistently but do not collaps consistently, causing confusion for screen reader users and those with cognative disabilities.
The links within VA benefits and health care are repeated further down on the page.
Links in VA benefits and health care are not in the same order as thise in the headings below, leading to a potentially disorienting experience for some users.

<h2>Proposed Solution (if known)</h2>
The ideal solution would be to replace the accordians with a list of navigation links which are not contained within the below headings.

**Comment by FranECross** [comment]
Closing as obsolete. The header/footer will be changing in the near future and another a11y review done at that time.
