### ISSUE TITLE
Adding Shelby Kavades to DSVA Slack

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#27094]
Shelby Kavades [kavades_shelby@bah.com, Shelby.nelson2@va.gov] needs be added as a full member guest to the following channels: 
- general
- gids-prod
- random
- vfs-all-teams
- vfs-platform-support
- vfs-test-accounts
- victories
- vsa-education
- devops-deploys

**Comment by mchelen-gov** [comment]
please use https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose "New Team VSP Orientation Epic Template"  for onboarding new team members
