### ISSUE TITLE
Clean up Sentry backlog

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#271]
## User Story
As a VSP team member, I need to be able to identify priority issues on the platform so that I can escalate or resolve them in a timely manner.

## Goal
Issues in Sentry are easily identifiable
Issues in Sentry are more easily prioritized
Issues in Sentry backlog are higher fidelity i.e. they are linked with GH issues if necessary, they are marked as resolved if they are indeed resolved, they are appropriately labeled, etc

## Acceptance Criteria
- [ ] Every issue in the Sentry backlog is a known issue with relevant information
- [ ] Every issue in the Sentry backlog is appropriately tagged 
- [ ] Every issue in the Sentry backlog is linked with GH issue if necessary
- [ ] No issue in the Sentry backlog is older than 6 months (will go down to 3 months if we're too busy)
- [ ] Every issue in the Sentry backlog has an assignee if necessary

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
For the `vets-website` project, we have this setting enabled:
![image](https://user-images.githubusercontent.com/12970166/59726002-b9f62c80-91e4-11e9-8f6a-7f4e20ee9fb2.png)
So if an issue doesn't have a new event within that timeframe (30 days, in this case), it's automatically resolved. That said, the fourth AC should be fulfilled by default for `vets-website`.

**Comment by kfrz** [comment]
This data is collected by [querying Sentry production-api-platform](http://sentry.vetsgov-internal/vets-gov/platform-api-production/?query=is%3Aunresolved+timesSeen%3A%3E10000+lastSeen%3A-30d&sort=freq&statsPeriod=30d) for:

- unresolved issues 
- seen in the past 30 days.
- seen over 10k times in total

I sorted by frequency, then gathered details on the top 10 issues:

| Summary                                                                       	| Events 	| User Impact 	| Sentry URL                                                                   	| VFT Issue                                                                                                                     	|
|-------------------------------------------------------------------------------	|--------	|-------------	|------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------------------	|
| MhvAccountTypeService: could not fetch eligible data classes                  	| 422k   	| 31k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/36560 	|                                                                                                                               	|
| Could not parse XML/HTML response from MHV                                    	| 176k   	| 66k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/8810  	| https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16998                                                  	|
| SM901 Database errors returned from MHV                                       	| 110k   	| 59k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/59513 	|                                                                                                                               	|
| Appeals data for a veteran with that SSN was not found,                       	| 109k   	| 43k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/59511 	| https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15063                                                  	|
| Unmapped 50x level error in V0::PrescriptionsController#index                 	| 106k   	| 54k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/63222 	|                                                                                                                               	|
| MHV provided unparsable error response, check logs for original request body. 	| 105k   	| 54k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/56842 	|                                                                                                                               	|
| MVI find_profile error: SOAP service returned internal server error           	| 67k    	| 6.5k        	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/31482 	| https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?repos=31788863&showPipelineDescriptions=false&search=mvi 	|
| Outage detected on MVI beginning at 1560739221                                	| 66k    	| 6.3k        	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/46783 	|                                                                                                                               	|
| Unmapped 503, handling an HTML return body                                    	| 41k    	| 15k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/1067  	|                                                                                                                               	|
| spider crawling it seems, we can probably ignore these client types?          	| 37.k   	| 6           	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/41959 	|                                                                                                                               	|


--- 

This is the same collection of issues, but [sorted by priority](http://sentry.vetsgov-internal/vets-gov/platform-api-production/?query=is%3Aunresolved+timesSeen%3A%3E10000+lastSeen%3A-30d&sort=priority&statsPeriod=14d). There is some crossover, but between these two tables I think we have the most impactful issues to start with.

| Summary                                                                           	| Events 	| User Impact 	| Sentry URL                                                                    	| VFT Issue                                                                    	|
|-----------------------------------------------------------------------------------	|--------	|-------------	|-------------------------------------------------------------------------------	|------------------------------------------------------------------------------	|
| SM901 Database errors returned from MHV                                           	| 110k   	| 59k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/59513  	|                                                                              	|
| Appeals data for a veteran with that SSN was not found,                           	| 109k   	| 43k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/59511  	| https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15063 	|
| LettersController#index Undefined Method dig                                      	| 28k    	| 16k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/56813  	| https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18719 	|
| Common::Exceptions::RecordNotFound: Record not found                              	| 16k    	| 8           	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/61609  	|                                                                              	|
| MhvAccountTypeService: could not fetch eligible data classes                      	| 422k   	| 31k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/36560  	|                                                                              	|
| 404 in connected_applications okta_redis/profile.rb                               	| 11k    	| 9.9k        	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/57861  	|                                                                              	|
| Appeals 504                                                                       	| 18k    	| 13k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/61606  	|                                                                              	|
| EVSS502 Common::Client::Errors::ClientError: the server responded with status 500 	| 22k    	| 10.5k       	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/56811/ 	|                                                                              	|
| V0::Facilities::VaController undefined method `[]' for nil:NilClass               	| 22k    	| 11k         	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/59689/ 	|                                                                              	|
| spider crawling it seems, we can probably ignore these client types?              	| 37.k   	| 6           	| http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/41959  	|                                                                              	|

**Comment by omgitsbillryan** [comment]
I think another viable option for cleanup is to suppress issues. For example, the login `NotOnOrAfter` error happens ~200 times/day but is actually a product of people clicking back on their login attempt. However, if this were to spike over, say 1k / day, it could indicate clock drift either on ours or ID.me's server; a serious issue that would need to be fixed.

![image](https://user-images.githubusercontent.com/3077884/59777293-69cda780-9282-11e9-9a76-3d17496488b3.png)

**Comment by kfrz** [comment]
I agree - we should follow something of a rubric. 

If it's a critical error - assigned and properly escalated 
If it's a minor error - ignore based on specific rules as Bill outlines above
If it's irrelevant - delete and discard so we aren't looking at noise again
