### ISSUE TITLE
CT: Update profile learn more modal content regarding covid in person allowance

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27107]
As an EDU team member, I need the covid in person allowance date to be updated to Dec 21, 2021 so that the information provided to the users of the tool is accurate.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The date in the following content, in the current Comparison Tool, of the Learn more modal of the "Will you be taking any classes in person?" question on the profile page is "Dec. 21, 2021".

    > Through Dec. 21, 2020, current and new students can receive in-person allowance rates if their school’s approved program changed from in-person to online learning due to COVID-19.

2. The date in the following content, in the Comparison Tool Sandbox, of the Learn more modal of the "Will you be taking any classes in person?" question on the profile page is "Dec. 21, 2021".

    > Through Dec. 21, 2020, current and new students can receive in-person allowance rates if their school’s approved program changed from in-person to online learning due to COVID-19.

## Supporting Artifact:
1. Screenshot of location of learn more:
<img width="415" alt="Screen Shot 2021-07-08 at 10 55 37 AM" src="https://user-images.githubusercontent.com/48260534/124978494-dbaaf200-dfff-11eb-9f89-9296c4aa8e1b.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17807

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1982&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging.
