### ISSUE TITLE
Investigate using Redux middleware to abstract out action creator complexities

### ISSUE THREAD

**Issue by jcosta-gcio** [department-of-veterans-affairs/va.gov-team#2710]
## High Level User Story
Currently, the pattern on `vets-website` seems to be to dispatch side-effect actions or other side-effects (e.g. API calls, etc.) within action creators. This can create complexity within action creators and, as a result, a developer may overlook side-effects that a certain action creator has. The solution to this typically is to use Redux middleware. We should:

## Goals
1) Decide if it makes sense to introduce Redux middleware
2) If it does, identify the benefits/drawbacks of the various open-source Redux middleware libraries.
3) Write up an RFC that documents ^^

**Comment by kelsonic** [comment]
Going to move this to closed. Most teams are using Redux middleware, and the chosen library for that thus far is [redux-thunk](https://github.com/reduxjs/redux-thunk). An example of this being used in `vets-website` is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/find-va-forms/actions/index.js#L40).
