### ISSUE TITLE
[LISA] Follow Up on VR&E Request for Statistical Data

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#27108]
The following question was posed: “Are there any statistics regarding the responses to the question on the new application in VA.gov on whether the applicant wants to opt into telecounseling?”

Is the question  above something that the VA.gov team would be able to provide a response to via google analytics or another method?

`check with Lisa`
Add column with application results

**Comment by jason-gcio** [comment]
- Google Events might be unreliable
- This might require a fair amount of time to create a custom widget and then it might not be reliable
- Tracking results in submissions might be tough as well
- Can this be tracked in Sentry? Other tools?

Need some more info before finding a path forward

**Comment by jason-gcio** [comment]
Next steps: double check with GA if there is a an event around this and if there is, what does it look like?
How often do they need to know this? One for a one-time decision, or weekly/monthly?

**Comment by jason-gcio** [comment]
Consider the summary email as well
