### ISSUE TITLE
508 defect 3, screen readers, VA home page no header to indicate footer links

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#27101]
Label: 

    - [508-defect-3]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3

Issue Title:508 defect 3, screen readers, VA home page no header to indicate footer links
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
As a screen reader user, I expect major sections of a web page to be indicated by a header. According to the most recent web aim survey, 70% of screen reader users use headers to navigate a web page.
<h2>Details</h2>
The last heading on the VA home page is "Language assist." If the user presses the quick navigation key H to go to the next heading, they are wrapped back to the top of the page. This could cause them to completely miss the footer links not related to language assist which render below it.

<h2>Proposed Solution (if known)</h2>
Insert a level two header "footer," or "footer links" immediately below language assist.

**Comment by laflannery** [comment]
I redid the markup in the new footer Codepen Prototype to make this clearer using landmarks. This could perhaps change if we get feedback from Phase 2 research but this has been addressed with the new Federal Footer and this is can be closed.
