### ISSUE TITLE
Capture Wait Time

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2711]
## Story
As the VA, I want to track veterans' appointment wait times when they schedule directly so that we can better understand the quality of care we are providing.

## AC
- [ ] New page exists for 'when would you like to be seen'
- [ ] New page comes after clinic selection in direct schedule flow
- [ ] New page comes before calendar / datepicker in direct schedule flow
- [ ] New page does not show in request flow

**Comment by peggygannon** [comment]
@goldenmeanie @rtwell  I think it would be best if I write content once the mocks are ready. Seeing how this is going to be depicted on the page will help me craft the content.

**Comment by goldenmeanie** [comment]
> We use this date to try to offer you the earliest dates we can, that make sense for your situation. For example, if you need an appointment for a check-up in 6 months, we can find available times without making you scroll through months of slots that aren't relevant to you.
> 
> It also helps us measure what kind of wait times people experience to be seen.

**Comment by narin** [comment]
@rtwell Just want to confirm that those are meant to be text inputs and not drop downs?

**Comment by rtwell** [comment]
@goldenmeanie ☝️ i'm guessing inputs but i default to however we do this in applications elsewhere. I think the important note here is that we dont want this to feel like the calendar input because they are _really_ different dates—so, the more this can feel like a diff interaction than the calendar, the better.
