### ISSUE TITLE
[UNPLANNED] Update Ch31 Daily Report Email

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#27114]
When #24945 was implemented, a regression was introduced. The object was changed from an `ActiveRecord::Relation` object to an `Array` object and `#find_each` is raising an exception, so we need to switch to `.each`.

**Comment by RudyOnRails** [comment]
opened https://github.com/department-of-veterans-affairs/vets-api/pull/7393

**Comment by RudyOnRails** [comment]
@jason-gcio I was about to submit the platform support request and boom it got merged.

I'll leave it to you to take to Close City.
