### ISSUE TITLE
Change Background Color of Profile Banner

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27117]
## Acceptance Criteria
* Change the background color of the Common Component of Profile Banner to #0071bb - Primary Blue.

This component appears in Profile. 

## Design reference
![Profile Header.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/6829b357-28e7-49d7-8495-41c27418849d)

## Context
This change takes a step towards matching the design of the mobile app profile banner with VA.gov (reference screenshot below)
![Screen Shot 2021-07-08 at 3.45.45 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/29b3dedf-080b-454f-9e86-21ef4e004ab2)

**Comment by lexicalninja** [comment]
@bridgethapner @ashley-matthews what is the color name of #0071bb?

**Comment by bridgethapner** [comment]
@lexicalninja Primary Blue - updated the ticket.

**Comment by lexicalninja** [comment]
Thank you!

**Comment by digitalken** [comment]
PASS 7/15/2021 - Looks good on iOS and Android.  Closing.
