### ISSUE TITLE
SCO: Add PDF to SCO page to make available for download

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27128]
As an EDU team member, I need a VRRAP Training Material PDF to be made available for download on the SCO resources page so that the SCOs have information available to help veterans who are interested in the VRRAP program.

## Assumptions:
1. These updates are made on the SCO page found here: https://www.va.gov/school-administrators/

## Acceptance Criteria:
1. The PDF in SA1 can be downloaded from the “Key Resources for SCOs” section of the SCO page using a link "VRRAP Training Material"

## Supporting Artifacts:
1. PDF to make available:
[VRRAP EI Training_07-01-2021-Finalv4.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6791307/VRRAP.EI.Training_07-01-2021-Finalv4.pdf)

**Comment by shawkey-daniel** [comment]
[PR 777](https://github.com/department-of-veterans-affairs/vagov-content/pull/777)
[PR 779](https://github.com/department-of-veterans-affairs/vagov-content/pull/779)

**Comment by shawkey-daniel** [comment]
[PR 780](https://github.com/department-of-veterans-affairs/vagov-content/pull/780)

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2020)
