### ISSUE TITLE
Conditional Alerts for Wait Time

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2712]
## Story
As a veteran, I want to know what my best scheduling options are so that I can get an appointment as close to my preferred date as possible.

## Calendar Alert Mocks Needed
- [ ] **Care needed urgently:** When preferred date is today *and* requests are available
- [ ] **Care needed urgently, request flow not viable:** When preferred date is today *and* requests are **NOT** available
- [ ] **VA not meeting standard of care, request flow viable:** Preferred date >5 days away, *and* next avail appointment is >20 (mental health) or 28 (other ToCs) days away from the preferred date, *and* requests are `enabled` for the selected facility
- [ ] **VA not meeting standard of care, request flow not viable:** Preferred date >5 days away, *and* next avail appointment is >20 (mental health) or 28 (other ToCs) days away from the preferred date, *and* requests are `disabled` for the selected facility

## AC
- [ ] Alert variants show on calendar page per conditions above
- [ ] Alerts don't show on calendar page otherwise

**Comment by peggygannon** [comment]
@goldenmeanie @rtwell Hello, I think it would be best if I write content once the mocks are ready. Seeing how this is going to be depicted on the page will help me craft the content.

**Comment by narin** [comment]
@markgreenburg I think recall you showing me mocks for this.  If so, can you please link them here? Might be able to start work on it later today.

cc: @rtwell

**Comment by rtwell** [comment]
ignoring the calendar design:
![image](https://user-images.githubusercontent.com/12564977/68153495-958cb980-ff13-11e9-97ec-5d15710b64f6.png)
![image](https://user-images.githubusercontent.com/12564977/68153506-9aea0400-ff13-11e9-9d28-3f777af94c24.png)

**Comment by narin** [comment]
Hi @peggygannon. When you get a chance, can you please review the language for these alerts?  Not depicted in the mockups is the 3rd scenario where requests are not available and the only option is for a user to call: 

**VA not meeting standard of care, request flow not viable:** Preferred date >5 days away, *and* next avail appointment is >20 (mental health) or 28 (other ToCs) days away from the preferred date, *and* requests are `disabled` for the selected facility

Thanks!

**Comment by peggygannon** [comment]
@narin @rtwell @goldenmeanie 
See below for content recommendations for the two scenario mocked up above. I'm still working on the 3rd and 4th scenarios. There's a lot of info we're trying to convey here, so I'm suggesting a bullet list so users can clearly see their options. I also added a page header/title, for accessibility purposes



{page title} **Appointment calendar**
{alert}
**This is the earliest date we can schedule your appointment**
The earliest we can schedule your appointment is November 1, 2019 at 10:00 a.m. ET. 
If this date doesn’t work, you can: 
-Submit a request for an earlier date, **or**
-Pick a date from the calendar below, **or**
-Call your local VA medical center

If you have an urgent medical need, please: 
Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
Go to your nearest emergency room or VA medical center. [Find your nearest VA medical center](va.gov/find-locations/)

{button} Request an earlier appointment    {link}[Call your local VA medical center](phone number)

{end alert}

-------

{page title} **Appointment calendar**
{alert}
**This is the earliest date we can schedule your appointment**
The earliest we can schedule your appointment is November 1, 2019 at 10:00 a.m. ET. 
If this date doesn’t work, you can: 
-Submit a request for an earlier date, **or**
-Pick a date from the calendar below, **or**
-Call your local VA medical center

{button} Request an earlier appointment    {link} [Call your local VA medical center](phone number)

**Comment by peggygannon** [comment]
Messages for 3rd and 4th scenarios. Please let m know if these recommendations will work? 


3rd scenario where requests are not available and the only option is for a user to call:


{page title} **Appointment calendar**
**We’re sorry. We can’t find a date for your appointment**
This medical facility doesn’t accept online appointment requests. Please call them directly to schedule your appointment. 
{link} [Call your local VA medical center](phone number)

------

4th scenario:
Care needed urgently: When preferred date is today and requests are not available

{page title} **Appointment calendar**
**We’re sorry. We can’t schedule your appointment**
If this is an emergency or you have an urgent medical need, please: 
-	Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
-	Go to your nearest emergency room or VA medical center. Find your nearest VA medical center

If this isn’t an emergency, please call your local VA medical center to schedule your appointment. 
{link}[Call your local VA medical center](phone number)

**Comment by narin** [comment]
Thank you @peggygannon.  One issue right now for the first scenario is that we don't have the local medical center number readily available.  However we can provide a link to the facility contact details in facility locator for now.  Let me know if that's suitable for the interim and I'll update in a new PR.  Thanks!

**Comment by peggygannon** [comment]
@narin OK, thanks for the update. In this instance, we can tweak the copy to say: 

[Contact your local VA medical center](va.gov/find-locations/*TK link to that facility*)

**Comment by markgreenburg** [comment]
@peggygannon @narin the attached PR looks to have been merged a few days ago - can we offload this content update to a new one? Happy to proceed however is easiest for you both.

**Comment by narin** [comment]
@markgreenburg Created new ticket #3414 to cover copy updates and closing this one out.
