### ISSUE TITLE
Access for Morgan Whaley

### ISSUE THREAD

**Issue by mraewhaley** [department-of-veterans-affairs/va.gov-team#27123]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Morgan Whaley
- Please Provide your email.
   > morgan.whaley@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team 3, lead React developer, Accenture Federal Services/Gray Digital

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDq8gfOd/qS+IJQbDvfgObkvifAGP8Xnfan/RRVRr+X5pDY0QkzIK3vsHc9MiA9QP/pnuiZkaN8avptrpWPqRqcZFiqRp1iQ0aooLr+SvdDCD15xtux6Y0U0mdNbQdtV48Yy8Upo52npfN39a1ufQLo2eJJueI+hGPdlBmRkbJTkobF1q9bj7Rt0cuYJS/xR5zO2QAcdeSivH58W9Fwg1K1fg+EkBSiCKQ5515dTR5mydEPqRX1p4h75Jkip4oQ5Nmlw7o+yeLmsadJd8ucpNOL1TlUUyB7Ts/ckocpuBnPebIE0p7KODZfA73wL02SgGzk6u5nqsMEJGd9x1jNwSz0ljRRqZ/m/LMZP64U/5tbzY7tbrFH2hRaVn/W59XXScBMmrc7OSgAJ+OY/+jpW9LGCLlK4j37hwyal3NWykNm5TPTBGsc47ERWg6hQ/ZffFid3K9HezQ/lXlXw1IH3yKl0dkQyiD4sITj04oDNgrQVnEJqAYSXwYEiB5NU3NpO8= morgan.whaley@AFSMWH8L5XI6XUD
```

- Grant AWS Console access?
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
