### ISSUE TITLE
Remove or fix unused secure message events in GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#27124]
We have many events in GTM for secure messaging...

- SM Additional Subject
- SM Attach File
- SM Create Folder
- SM Delete Message
- SM Move Message
- SM Notification Settings
- SM Save Draft
- SM Search
- SM Send Message
- SM Sort

...but [I only see data in GA](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20170101&_u.date01=20210707&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22%5E(SM%7CSecure%20Messa)%22,0%5D%5D/) for `SM Send Message` since 2017.

- [ ] Should these additional interactions / API call be tracked?
- [x] If not, we should remove these tags from GTM

**Comment by laurensimpson14** [comment]
If no one has asked for the data in 4 years then I think we should delete... 

I deleted the 9 tags that weren't collecting data + the 1 that was (`SM Send Message`).

**Comment by bsmartin-ep** [comment]
Published to production.  Closing.
