### ISSUE TITLE
CT Redesign: Update Navigation controls on the profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27129]
As a developer, I need to add a way for the users to quickly navigate back to the top or to various sections of the comparison tool profile page so that the amount of scrolling when viewing sections of the page is reduced.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. These changes are applicable to all institution type profile pages (school, OJT, VET TEC).

## Acceptance Criteria
1. Once the header card is out of view, the back to top button is available in the bottom right of the viewport.
    a. Clicking the back to top button returns the view to the top of the profile page.
2. Clicking a jump-link in the header moves the page to the corresponding section on the profile page without modifying the URL.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222703/296062933/preview)
2. VA.gov back to top [documentation](https://design.va.gov/storybook/?path=/docs/components-back-to-top--default-story)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17930

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2018)

**Comment by delli-gatti-michael** [comment]
Local testing complete
