### ISSUE TITLE
Delete unused code for preneeds burials

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#27122]
From our [graphana dashboard,](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fpreneeds%2Fburial_forms&var-backend_controller=v0%2Fpreneeds%2Fcemeteries&var-backend_controller=v0%2Fpreneeds%2Fpreneed_attachments&var-frontend_app=All&from=now-30d&to=now) it looks like the only api endpoints that start with ` /v0/preneeds` that are actually used are :

> v0/preneeds/cemeteries#index
> v0/preneeds/burial_forms#create 
> v0/preneeds/preneed_attachments#create 
> 

So, we should remove the unused endpoints and their associated code after confirming with the front end that they're not used. 

- [x] GET    /v0/preneeds/states https://github.com/department-of-veterans-affairs/vets-api/pull/7401
- [x] GET    /v0/preneeds/attachment_types   https://github.com/department-of-veterans-affairs/vets-api/pull/7390
- [x] GET    /v0/preneeds/discharge_types https://github.com/department-of-veterans-affairs/vets-api/pull/7409
- [x] GET    /v0/preneeds/military_ranks https://github.com/department-of-veterans-affairs/vets-api/pull/7413
- [x] GET    /v0/preneeds/branches_of_service https://github.com/department-of-veterans-affairs/vets-api/pull/7391
- [x] GET    /v0/preneeds/burial_forms/new (remove from routes) https://github.com/department-of-veterans-affairs/vets-api/pull/7427
- [x] Remove Branches of Service Model https://github.com/department-of-veterans-affairs/vets-api/pull/7471 (In code Review)

**Comment by annaswims** [comment]
I'm thinking we'll be able to delete many of the models in https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/models/preneeds but I'll need to be more sure before we do.

**Comment by michelpmcdonald** [comment]
> I'm thinking we'll be able to delete many of the models in https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/models/preneeds but I'll need to be more sure before we do.

I was able to remove the models corresponding to the endpoints
