### ISSUE TITLE
CT Redesign: Add compare drawer functionality to profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27136]
As a developer, I need to add the compare drawer to the profile page so that the user can add an institution to the drawer from the profile page and then navigate to the compare page if they choose to do so.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The compare drawer is a shared component that can be reused.

## Acceptance Criteria:
1. The profile page includes the compare drawer as a sticky component at the bottom of the viewport.
2. The user can add the institution to the compare drawer from the profile page header.
3. The user can remove the institution from the compare drawer:
    a. from the profile page header.
    b. from within the compare drawer.
4. The compare drawer is available for all institution type profile pages:
    a. Schools
    b. OJT/Apprenticeship
    c. VETTEC

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/projects/prototypes/14222703?scrollOffset=159)
    a. Note: the prototype does not show the bar as sticky, but it should be just like it is on the search results.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17892

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2016)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
testing complete
