### ISSUE TITLE
Access for Bradley Bergeron

### ISSUE THREAD

**Issue by bradbergeron-us** [department-of-veterans-affairs/va.gov-team#27138]
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Bradley Bergeron
- Please Provide your email.
- 
   > bradley.bergeron@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >  Team 3, Ruby on Rails and React Developer, Accenture Federal Services/Knowledge Vortex

- Requesting SSH key authorization?
   > YES
- What is your **public** SSH key? 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIRhawHWj6j9fHcuiLBI2XLSh3T/JkOWPP/UpKNtZsAeDY3//QTEXq7QJIiYYYQYkuRP5uu8KwQ2AdZqYN7M+yym3OU3SEHa50DsFJuLRJjaHBCsAO6VpXtEd8YcPBQihTmqUu1CIEjYzeOfk2iNYssW9lxlGoyVcHnohdOvw27KIUjTIoyUfIRW4NqDuN107VBYlhXb+NTf5BWHBJ5ewqMh4EkjDqg5MXOPUEfdwgwpSZIgAZCnNtM8hR88K61UPSg5dnYglIuAx00rA1IszvRuljPNoY4Vjr/zIvHTnNN0+u+l6LU4V9PBrKXwJrZNj7+fxMi0UY3ObeqpWSq+WnPRHE3IwWdYUCSWxgUNxCDbTTT7iyX6m3CfpNR2XtiaHJxhegmiu7+zr3UVnl/sRdzp6o3DpUUy8bznSNxfSrcQYslWvmIT4WEUhm/EazXu4HqMy02hAqAg+6gUVLJPW5XkmLLZujvhQJ2n2JaFJ2pRM2dfCYmRH3+rCsTpc+bg8= bradley.bergeron@AFSMWL9CZWUW5N4
```

- Grant AWS Console access?
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
