### ISSUE TITLE
NOD - 'Area of Disagreement' Content

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#27133]
## Issue Description

Currently, on the 'area of disagreement' page(s), we are instructing veterans to tell us **why** they disagree with their issue. After chatting with the Board, they are mostly interested in just knowing '**what**' is being disagreed with - and that is categorized into the 4 checkboxes that the user can select. 

In usability testing and in UAT, we found that veterans wanted to give reasons for why they disagreed with the evaluation of their issue. We intend on pursuing changes to give veterans that option post-launch, but for time concerns, we want the MVP to just collect the 'what' aspect they disagree with.

In doing so, we will need to change the copy to instruct them to simply choose which area(s) of disagreement pertain to their issues.  

Area of disagreement page: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292867

---
## Tasks
- Work with Beth to modify language
- If possible, change the language to reflect that it's not the 'why' the board is looking for, but a general 'what' they are disagreeing with

## Acceptance Criteria
- [x] Design has been updated with the above changes
- [x] Content changes have been shared with FE development
---

**Comment by bethpottsVADEPO** [comment]
@kevinstachura Could we say this? (edits are bolded):

Tell us **what** you disagree with. You can choose more than one.
I disagree with **this**:

**Comment by kevinstachura** [comment]
This has been updated and can be found here:

https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/v8KZbx1
