### ISSUE TITLE
BDD content changes - Lay Statment

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27145]
## Issue Description
Update BDD content per stakeholder request

---
## Tasks
- [x]  Step 3 of 5 page; recommend revising "Supporting (lay) statements or other evidence" to read: "Additional VA Forms, medical records, separation documents (DD Form 214), supporting (lay) statements, or other evidence"

## Acceptance Criteria
- [x] Updated content
---

**Comment by kevinstachura** [comment]
Here is a visual of the updated content:

<img width="592" alt="Screen Shot 2021-08-16 at 9 19 02 AM" src="https://user-images.githubusercontent.com/54544300/129570167-ebef49b6-9f9d-4875-ab10-d66496f307fb.png">

@vhenry07 It's worth noting that we should talk to both Kevin Hillegas and Beth Potts about the (now updated checkbox) 'lay statements and other evidence' content under the "which evidence type should I choose?" dropdown:

<img width="627" alt="Screen Shot 2021-08-16 at 9 17 41 AM" src="https://user-images.githubusercontent.com/54544300/129570344-6def133c-47da-456a-82d3-4154994f69fc.png">

Tagging @Mottie for awareness on this, though I'm sure it will become an FE ticket soon.
