### ISSUE TITLE
Access for Patrick Arthur @department-of-veterans-affairs/vsp-operation

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#27149]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Janet Doe
- Please provide your name.
   > Patrick Arthur
- Please Provide your email.
   > Patrick.Arthur1@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > GI Bill of Rights legacy team 3

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIdk4plaWHUxlUphS2JCpbXQfn5Lputer8IPjVk72r4oJG33oH5+jBBO6bz8JW9Uz/YffEMdCAx7R1zH+f7No7+sCRVc3Vjp5U+EKOeJas/q+4hUcExmjN+GZODc2cTdwVq5Cp8EK/bGV610bQ1qgRrbfljDtUm1OMII/j0V5Wwq8sAS9IMNhZjSLZB5CUBY0l9TVBATKL+UBV13fslnsf4NBW1bzAKgBqvGmvuJTRiKPN+vamGJ06gq2du7BYt31qjfsXCj2N0S/e6Vxvg4Z4VcNa8MaTzJonksXjlfICPUY41iIiXUW/+hWXNufe9J40m2+nY4FiQHqcGF6lr8kX9tT1jBcww4fOnoOJHwVU03PquzpHXlwO9y1OPPrPjgmGW8HYFM+vwRFdjkjoEwYUQH7Wrnr/yci5AZPKVFaNEdAj4ccA1PaZx8G5ZKScvRxVu1H51HlTZ4W3IYvi1ycnds3WMFstccOo6YWA+XaoU/o4WdQccXG1hZk1OAw9f+s= patrick.arthur@AFSMWFR8MB5TPA3

```

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by PJart** [comment]
I don't have access to this link https://github.com/department-of-veterans-affairs/devops/raw/master/ssh/config

**Comment by jbritt1** [comment]
> I don't have access to this link https://github.com/department-of-veterans-affairs/devops/raw/master/ssh/config

DM'd via Slack
