### ISSUE TITLE
Bypass schema + uiSchema in the schema-based forms library

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#27148]
## Issue Description
Currently, the only way to get content on a page within a form in the schema-based forms library is to pass the `schema` and `uiSchema` properties to the page in the `formConfig`.

This poses a problem for pages with content that we don't want to come from the schema, such as a modal-based profile update flow.

Additionally, when rendering the `schema` + `uiSchema` to fields, they're always nested in a `<form>` element, which is a problem when we want to render a `<Modal>`.

Lastly, the migration path to update forms to use the new forms library will be to allow teams to replace single pages at a time in the `formConfig` with the Formulate version of the page, so this work will be a stepping stone for migration.

## Acceptance Criteria
- [ ] `schema` and `uiSchema` are optional properties of a page in the `formConfig`
- [ ] If `schema` and `uiSchema` are absent, `pageComponent` and `reviewComponent` are required and are rendered instead of assembling the fields from the `schema` and `uiSchema` on the normal page and review page respectively
- [ ] `pageComponent` accepts a React component which receives the following props
    - `index` The index of the array the page is in (if applicable)
    - `initialData` The state of all the form data when the page is entered
    - `setData` The function to set the data for the entire form
    - Any other form state (such as metadata or profile data) may be obtained by connecting the component to the Redux store
- [ ] `reviewComponent` accepts a React component which receives the following props
    - `index` The index of the array the page is in (if applicable)
    - `formData` The state of all the form data
    - `edit` The function which enters edit mode

**Comment by Mottie** [comment]
Our use-case for Form 10182 (NOD) and in the future Form 0996 (HLR) will show the Veteran their contact information and allow them to edit required information.

Currently, we show them an alert message with a link to the profile page along with a refresh button. Once the user updates their profile information in the new tab, they return to the form and click to refresh the contact info page. This isn't good UX as it interrupts the form flow and may not be ideal in the mobile environment.

We want to allow in-line profile contact information updates. The `platform/user/profile/vap-svc` components allow for this editing, but the edit form opens in a modal. This causes a problem where the modal's `<form>` is nested within the `<form>` of the application. The outer form cannot be removed as the form "Back" and "Continue" buttons rely on it, and moving the modal contents to _after_ the form element breaks the React bindings causing an error once the edits have been submitted, and the modal close button stops working.

I think defining a `pageComponent` and `reviewComponent` instead of a `schema` & `uiSchema` sounds like a reasonable solution to this issue, as long as the form navigation buttons work.

**Comment by cvalarida** [comment]
Just spent some time pondering on this. My notes for posterity:

---
# Things it needs to do
- [ ] Render the custom component in the `FormPage` instead of `SchemaForm`
- [ ] Render the review component in the `ReviewPage` instead of...the current content
- [ ] Allow custom components to update the form data in the Redux store 
- [ ] Allow custom components to dispatch the SiP save action
    - Alternatively, this could be automatic, but...that doesn't excite me...
        - ...unless this is already happening automagically...🤔
- [ ] Prevents navigating forward if there are validation errors
    - What does this look like
    - I need to know more about how this works right now so I can hook into that
    - Looks like we render the `ProgressButton`s as children of `SchemaForm`, so potentially it's up to the custom component to render them
        - The function we then provide that component is the function to actually do the navigation if there are no validation errors


# SchemaForm Props
- `name`: The `pageKey` in the `formConfig`
- `title`: The title to display
- `data`: The entire form data...unless `showPagePerItem` is true
    - We'll need to change this to return the entire form data if there's a custom component
- `appStateData`: An arbitrary collection of data gathered from the redux store
    - I'm going to not include this because folks can just connect their custom component to the redux store without this layer of indirection
- `schema`: The schema
- `uiSchema`: The uiSchema
- `pagePerItemIndex`: The index of the array page
- `formContext`: The...form context...to overuse that term
    - Object containing
        - `isLoggedIn`
        - `prefilled`
        - `onReviewPage`
    - I'll just spread these as props on the custom component—no need to bury them one more layer deep
- `trackingPrefix`: String to prefix the GA events with
- `uploadFile`: Function to use to upload a file
- `onChange`: Function to call when data is changed
    - This is what calls the redux action
    - This _also_ calls the `route.pageConfig.updateFormData()` function, which I'm going to ignore because it can be defined in the `onChange` handler for that page directly with this new model
- `onSubmit`: Function to call to move to the next page
    - Interesting!
    - How does this interface with the `ProgressButton` callback for continuing?
        - `callonContinue` just calls `route.pageConfig.onContinue(data)`, so......a form-specific thing I'm not going to worry about

# Ordered tasks
- [ ] Write test to render the component instead of `SchemaForm`
- [ ] Render the component instead of `SchemaForm`
- [ ] Pass that component
    - `name`
    - `title`
    - `data`
        - Make sure it's the entire form data
    - `pagePerItemIndex`
    - `isLoggedIn`
    - `prefilled`
    - `onReviewPage`
    - `trackingPrefix`
    - `uploadFile`
    - `onChange`
    - `onSubmit`
- [ ] Write a test to render the custom review component on the review page
- [ ] Render that on the review page
    - [ ] Including `showPagePerItem` pages with custom components
- [ ] Make sure toggling between edit and review state works seamlessly
- [ ] Make sure editing on the review page works
- [ ] Throw an error if there's a custom component without a corresponding review page component
- [ ] Write documentation on how to use all of this
    - [ ] Document all the props passed to the custom component (types and descriptions)
    - [ ] Example of how to bypass the `SchemaForm`
    - [ ] Call out easy pitfalls
        - [ ] Need to wire up navigation
            - [ ] Potentially including _not_ navigating if there are validation errors
        - [ ] Maybe need to wire up SiP
