### ISSUE TITLE
[Discovery] Determine Discharge Upgrade Wizard impact to user flow

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27143]
## Overview 
We were recently asked via email to make several content changes to the Discharge Upgrade Wizard tool.  The content of those requests is captured in the attached PDFs.

[update_1.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6793185/update_1.pdf)
[update_2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6793186/update_2.pdf)

One change in particular will impact the user flow.  That request is as follows:

**"For Discharge Review Board applications, consider adding a separate initial question that
asks if the Veteran was a victim of Intimate Partner Violence/Domestic Assault which
resulted in misconduct that led to discharge, then include the appropriate Kurta Factor
instructions, per the PTSD/OBH/TBI/MST instructions."** 

## Scope
This discovery item is to:

- Map out the current flow in a flowchart
- Determine where in that flow these content changes will fit (likely multiple places) 
- Estimate the effort to implement those changes

@zacharymorel specifically noting that this question only applies to paths that result in referrals to a given military branch's  Discharge Review Board (DRB)

## Acceptance Criteria
- [X] Create a narrative describing where along the user flow each of the requested changes will be inserted

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel @callen2563 here is a Discovery task for Sprint 52.  Please have a look and add your estimates  before we do our Sprint Planning on Wed.  Thank you!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @callen2563 At least a 3 for my part.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @zacharymorel !

**Comment by zacharymorel** [comment]
Markdown bare bones flow of the decision tree.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/dw-content.md

**Comment by callen2563** [comment]
Yes, 3 as well

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @callen2563 Understanding this logic tree isn't the easiest haha.

**Comment by zacharymorel** [comment]
I'm going to try to document it here so it is easier to follow that the markdown link above.

**Comment by MarciMcGuireGCIO** [comment]
Yikes! Ok, sounds good.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @callen2563 
So in regards to the request to add this content below: 

**"For Discharge Review Board applications, consider adding a separate initial question that
asks if the Veteran was a victim of Intimate Partner Violence/Domestic Assault which
resulted in misconduct that led to discharge, then include the appropriate Kurta Factor
instructions, per the PTSD/OBH/TBI/MST instructions."**

They're two places to add the content needed here.
1.  We will need to add to the bullet list of PTSD/OBH/TBI/MST seen here in the screen shot 
**Note:** these categories are shown on the "root" of the application. va.gov/discharge-upgrade-instructions/
![Screen Shot 2021-07-26 at 11 48 39 AM](https://user-images.githubusercontent.com/26075258/127033072-69798711-5d98-4677-8e73-ef3607ca7f2c.png)
2. Well will need to add an option for **"victim of Intimate Partner Violence/Domestic Assault which
resulted in misconduct that led to discharge"** to the following question.
![Screen Shot 2021-07-26 at 1 41 50 PM](https://user-images.githubusercontent.com/26075258/127034196-fec849dc-960a-4f68-b361-4a48150084a0.png)
The process of submitting remains unchanged, however, a vet needs to know they can qualify of a DBR review.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @zacharymorel !

**Comment by MarciMcGuireGCIO** [comment]
This exercise was more involved than anticipated.  For that reason I am splitting out the Mural board AC into a new ticket #28002
