### ISSUE TITLE
BDD Content Changes - Evidence

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27144]
## Issue Description
Update BDD 

---
## Tasks
- [x] Step 3 of 5 page; recommend revising "What type of evidence do you want us to review as part of your claim?" to "What type of evidence do you want to submit as part of your claim?"

## Acceptance Criteria
- [x] Completed content updates
---

**Comment by kevinstachura** [comment]
This design change has been made:

![BDD-evidence-type](https://user-images.githubusercontent.com/54544300/133093753-b9fb6c26-868c-4f62-91ea-449b614d42f0.jpg)

Can now send to @Mottie for changes. Let me know if you have any questions - thanks!
