### ISSUE TITLE
BDD Content Change - Supporting Language

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27142]
## Issue Description
Revise BDD content
---
## Tasks
- Step 3 of 5 page; recommend revising "Step 3 of 5: Supporting evidence" to read "Step 3 of 5: Submitting supporting evidence, such as additional VA Forms, medical records, separation documents (DD Form 214) etc. 

## Acceptance Criteria
- [ ] Revised content
---

**Comment by kevinstachura** [comment]
This has been completed on the last checkbox as suggested:

![BDD-evidence-type](https://user-images.githubusercontent.com/54544300/133098173-4817a6bc-815c-47ec-a7fd-455434d26c1b.jpg)

If this refers to the heading, we try to keep those short in general to avoid cognitive overload, and the context should be there as part of the interaction model (the checkboxes below state these things). Closing as complete.
