### ISSUE TITLE
CT Redesign: Compare is broke

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#27152]
Compare is broke
![Screen Shot 2021-07-09 at 3.13.08 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/188f7533-8c84-4d8c-9f20-204048038a77)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17816

**Comment by sonntag-adam** [comment]
Compare is no longer broke. Closing bug.
