### ISSUE TITLE
Access for David Rowley

### ISSUE THREAD

**Issue by dsrr47** [department-of-veterans-affairs/va.gov-team#27154]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > David Rowley
- Please Provide your email.
   > dsrr47@gmail.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Legacy AO team 3  Role: React Developer Company: m9 solutions, contracted to Accenture Federal

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvBDj1mNOt8lp7dNUVis7h9dwN6MbAYUA+X8XKT9nrCMUMhWoH2nrvX3ofaLpFi1Zt8gEqFZySIj7lrM1rj0eVTEHGmd7zhNXJM1FxldZW+2/Hdo7r/0SFh6BMP9bfbM24P4zn/Ql+qPXVer2PR4aTTX8vsViqEN/GVRdkdt8RdJom4XMW0WtiDwyxlQMFSXFNqdH/LZkJaFHjp2d20VOT3iYKVIvcTIZYi4IZhQv0JPGzQONodb9YWAz+oZ4kcOfoTSx+3x7U4twRY8F+wEnY1+PUTMsHIdAR6SjtrU6LK1lE5VV/h8kiVjzl1U0PpQRFPygOrQRBpZx7k6yYHUFfyfxt/5evqH2cE0E9Cei8Fjc+9JTVMywp3lGQ/47BRutN7zzkZdZroDczbJRJxsV9Zno8Bpw0Ls/lwP6FGw3+JwDUenejOYPdNPidndiVpttePYTED/9DlRcQ/iNT3Rt3V0Kg4OiJfCakJIagLpR887BzYpsFCy7yPFiRPdSitZc= david.rowley@AFSMW0RAOVVJWMQ

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
@dsrr47, please include a work email rather than a personal one.

**Comment by dsrr47** [comment]
Work Email: david.rowley@accenturefederal.com

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
