### ISSUE TITLE
Access for Manish Shah

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#27157]
# Instructions
1. Fill out - need access to SOCKS proxy
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Manish Shah
- Please Provide your email.
   > m.c.shah@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team 3 for VA website

- Requesting SSH key authorization?
   > **YES** / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJ8DfV38BlO7LDZnH2nuRXob996zPbqqGwXkNENUPiFmBdUB681ftTO5flp27JtSKnQmplSldvWV0VxwZLKIc6kTuY9BVuxA/IFZS90XRTWonGNSGoRWc8Mh2pa00yIxL7vq2F6o03yZ4peuiwROQ8AnNu1dSxdYTRMPvf1sUVP0MpRJpYWpMD/svOgIloBiXfdIXDrbZkLDAz/luTYV20BH0foc4Z8DDuM9OpEwHOQHcz2WyX2N96X9WudFhcvwHLnnWV150SddUisjU5pJC6qTolAjlJqexrA+RAxSm74JJtEoMRTkcBWq1ISswC4bTZf+pjlbeoTSa21azBuQSJsA5b+67uLogLamuxLp2udrXGKgr1kcJXQg3y2nncM6hHdPLz8L4nGz+ga4NdsI96HrVamk8IeaUilU34MHdSUazQVh3c7X75DU9QeyGFw7x8GTONWRXc/xmjQu+F54BOF/WL1xApfP9qbW51PbMfYzVHs/FgGycIrBEVNI4eehc= m.c.shah@AFSMW8KI3ILMIKX
```

- Grant AWS Console access?
  > YES / **NO**
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
