### ISSUE TITLE
Access for Jacob Finnern

### ISSUE THREAD

**Issue by jfinnern** [department-of-veterans-affairs/va.gov-team#27153]
@department-of-veterans-affairs/vsp-operations 
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Jacob Finnern
- Please Provide your email.
   > jacob.finnern@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Comparison/Feedback Tool - QA Test Engineer; Accenture Federal Services

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC230c14aopiKSyyW/ilu+ZoTvmU/wIxKH6AnR9qM0qYrkt9RjGIdH9Xkbo47s0dQSEgxMM+jQVe3ThNYEwSbwfDNUDe3XFSt0XHo9XX8j6AJ1nSEig8AUs9vdnbgM+h4sRKyXXm1ECGP3VtO+rq2rGgmnT/wGIBgnXeaRAJ51lX2ZqYuM26MddnOmJRh/4Ar7XoY5SnnaSmzoJGocxn0UrGxwTMFOb45q0EekPOzIKmzH0qSkSSbnQZ/2Q0TRQYBIKM5gpf0T/gn9fmw2JoAqMTaCHgZHDK7ZaezbxypUi4a3Dlfj+WCQcxHzkMG0PoAK8OI+q5BXb3MtyrNx4rHVMRZFHUm+XDIBbWmjy1Nh3so1OQ5fvFHLjc5un19aQYOMw6vUpUVZMHOnETmJAfyrMWA8Idq7Zd+4vrKsc8SPmurwK5FgNJ6IUUM+7qQWP29YttjPhP8FLeElSmcewg0S/O7MNB6cDO3O/svYf8SaIQzfnBTmDUEwzR5TKxVA6j1s= jacob.finnern@AFSMWFY7K9LA36J
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
