### ISSUE TITLE
CT Redesign: Update visual elements of the search page based on UX feedback

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27150]
As a developer, I need to update visual components of the comparison tool sandbox search so that it is in line with the redesign styling.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria
1. The "Search by name" of the search component has a border.
2. The "Search by location" of the search component has a border.
3. The active "tab" in the search component:
    a. has a blue border on the top.
    b. has a white background with gray-dark (`#323A45`) text
4. The inactive "tab" in the search component has a grey background (`#EEEEEE`) with grey (`#757575`) text.
5. The "Refine your search" accordion header is replaced with "Filter your results":
    a. on "Search by name"
    b. on "Search by location"
5. When the "Update tuition and housing estimates" accordion is expanded, there is 16px of space between it and the "Refine your search" component.
6. On "Search by name" the top of the cards in the first row of results aligns with the top of the "Update tuition and housing estimates" accordion.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222692/296060318/preview)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17844

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1988)

**Comment by delli-gatti-michael** [comment]
Testing complete
