### ISSUE TITLE
CT Redesign: Update text content on compare page based on UX feedback

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27155]
As a developer, I need to update text content on the compare page so that the content is consistent with OCTO content standards and practices.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. In the "Summary" section, "Gi Bill students" is replaced with "GI Bill students".
2. In the "Your estimated benefits" section "Payments made to school" sub-section, "Gi Bill pays to school" is replaced with "GI Bill pays to school".
3. In the "School ratings" section:
    a. "# of veteran ratings" is replaced with: "# of Veteran ratings"
    b.  The word "Rating" is not included in any of the table row headings (e.g. Online instruction ~Rating~, GI Bill support ~Rating~)
4. The "School ratings" section is not displayed if none of the schools selected for comparison have ratings data.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222692/296060322/preview)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17845
