### ISSUE TITLE
Access for Hocine Halli 

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#27158]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Hocine Halli
- Please Provide your email.
   > hocine.halli@va.gov
   > hocine.halli@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Legacy AO team 3
   > Role: QA test engineer
   > Company name: Accenture Federal Services

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQCsEedyrBXa/MaAs4WKS/lJ85fu2NGWboABwLI+a657hzyJGDg3gHiGgRTiFUG97GvmwE7tdjRwa4TDDfNiMH9VMkOoIvEdUGys/PNWRT1f4lv1vdIeMK3LZ1HsuEiSZszd90A9/UhZ2VHzR+j2fAz8e1TwsiGEmh6Z3nIzPySQy9pTuj2xwTBMs2sxuzGXvFBJyianlK2BM3i1Mxtv7B8iG06IYcnAl2S9FGBK1KZEwAuI/2Gyvsb/3vXy8+fcq5MoUQ5/CdtZIj9y6+35+O9PkTuNjqPMlUOaMZfrCZpRmwDN0wkY5kTPxqBbRgTPcjf5V1qInBS0dQPCP1XcNW6rSKDjG7dZehVmncJf8+kdaT/pR3ZjyZxTK7lkOF1x3hjMGfm0jcr1IXRfYCpCYMN+pTrZC+ED9x+xCTAM/wMQdC28Q9L37PhCpGf6sGxuTxpl9tdsxYLUhict9FALEOxxn4wvJ6T+tIRGMaay3nirwuDLWny+k89tpFA1BxMDx5E= hocine.halli@AFSMW9G67259G58
```

- Grant AWS Console access?
  > YES / NO
  - What AWS services do you need access to and why? SOCKS proxy to access Jenkins

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
