### ISSUE TITLE
Update the header styling and meta description for home loans best bet

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27166]
## Issue Description
When searching for "veteran home loans" on VA.gov, the top result that comes up is for our VA-backed Veteran home loans page but the title and meta description seem to be pulling from the legacy page. Service members should be lowercased and two words, for example. The meta description in Drupal is different from what is showing in the Best Bet.

https://www.va.gov/search/?query=veteran%20home%20loans&t=false 

We should replace what's in the search with the meta title and description for our modernized page.

## Tasks
- [ ] Update best bet

## Acceptance Criteria
- [ ] Best bet is live with current meta description

**Comment by RLHecht** [comment]
@johnhashva I just found this issue with the best bets when doing the forms work. I wonder if this page was redirected and it's pulling that information instead of what we have?

**Comment by johnhashva** [comment]
@RLHecht does this look right now?

<img width="783" alt="Screen Shot 2021-07-12 at 11 11 11 AM" src="https://user-images.githubusercontent.com/63107147/125311988-e0262200-e301-11eb-95b5-cdc5293b1eba.png">

**Comment by RLHecht** [comment]
Yep, that's perfect. Thanks @johnhashva !

**Comment by johnhashva** [comment]
With @RLHecht 's validation, closing this issue.
