### ISSUE TITLE
[FE] My VA: Send appropriate events to GA for enhanced tracking on Claims & appeals

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27167]
## Background
The Claims & appeals section of My VA 2.0 frequently times out. As requested in [26703](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26703) we want to implement some enhanced tracking, specifically the following events:

1. a call to the claims API succeeds
2. a call to the claims API fails
3. a call to the claims API has timed out (when we stopped calling it because it was taking too long)

## Tasks
- [ ] Implement the global `api_call` events as outlined in [Brian's comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26703#issuecomment-876037933) (also outlined below)
- [ ] Ask analytics team via [26703](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26703) to test/confirm

1. a call to the claims API succeeds
```
{
     event: 'api_call',
     api_name: 'GET claims',
     api_status: 'successful',
     api_latency_ms: 20000
}
```

2. a call to the claims API fails
```
{
     event: 'api_call',
     api_name: 'GET claims',
     api_status: 'failed',
    'error-key': '500 Your error message'
}
```

3. a call to the claims API has timed out (when we stopped calling it because it was taking too long)
```
{
     event: 'api_call',
     api_name: 'GET claims',
     api_status: 'failed',
    'error-key': '500 timeout message'
}
```

4. Recommendation from Brian: _You may also want to fire an event when the request begins to get a completion rate:_ But we are **not** going to implement this since a single view of the My VA Dashboard can result in `GET claims` being called 6 times in a row (once every five seconds)
```
{
     event: 'api_call',
     api_name: 'View Claims and Appeals',
     api_status: 'started'
}
```

**Comment by erikphansen** [comment]
@bsmartin-ep Starting with today's daily deploy around 3PM ET we should start seeing data some data for the `GET claims` API in Google Analytics. Could you point me to a URL in GA where I could find this data? Thanks!
