### ISSUE TITLE
Cognito Tech Presentation

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#27170]

**Comment by joeniquette** [comment]
- [ ] video of logging in
- [ ]  prototype of UI
- [ ] architecture diagram
- [ ] cost breakdown
- [ ] how does cognito work
- [ ] integration with login.gov explained(creation of test app timing)
- [ ] integration with id.me explained (creation of test app timing)
- [ ] va.gov backend integration (how this uses existing session object
- [ ] no support for SSO)
- [ ] DNS UI breakdown
- [ ] next steps
- [ ] reason we are doing this
- [ ] login flow diagram

**Comment by christine-dillman** [comment]
Wednesday 7/21 12:00 EST - Tentative 1st Demo for Oddball Leadership & Cory/Kevin

**Comment by joeniquette** [comment]
draft completed on 7/16
