### ISSUE TITLE
CT Redesign: Update search result cards UI & content based on UX feedback

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27177]
As a developer, I need to update UI and text content of the search results cards so that the the cards meet the designs as laid out by the UX team.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. For both name and location search
    a. The "Housing Benefit:" label is replaced with "Housing benefit:".
    b. The " / Month" with the housing benefit amount is replaced with "/mo".
    c. The "compare section of the card is the same width as the rest of the card.
    d. The "Employer" heading on applicable cards is replaced with "On-the-job training / Apprenticeship".

2. For the name search:
    a. the left edge of the "Update tuition and housing estimates" component aligns with the left edge of the search component
    b. the left edge of the "Filter your results" component aligns with the left edge of the search component
    c. the right edge of the institution cards align with the right edge of the search component
    d. the width of all components below the search component is the same (about 312px)
    e. the vertical space between all of the components (ex between the accordions and the cards) below the search component is the same (about 32px)

## Supporting Artifacts:
1. [Search Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222691/296060315/preview)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17864

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2015&group_by=cases:section_id&group_order=asc
