### ISSUE TITLE
Update teaser text for Apply for a Veterans Pension on pension hub page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27179]
## Issue Description
As we add more online tools we want to keep the teaser text consistent across the hubs. Therefore we should remove the word "online" from the teaser text for Apply for a Veterans Pension online (VA Form 21P-527EZ) on the [Pension hub landing page](https://www.va.gov/pension/).

Text should now read:

Complete your application now.

---
## Tasks
- [x] Remove the word "online" from teaser (Selina)
- [x] Review (Randi)
- [x] Publish (Selina)

## Acceptance Criteria
- [x] New teaser is live on site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

VA pension benefits: http://preview-prod.vfs.va.gov/preview?nodeId=73

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published.

**Comment by RLHecht** [comment]
Live on site. Closing ticket.
