### ISSUE TITLE
E2E testing speed is too slow on GHA

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#27175]
The current E2E suite runs on GHA are taking anywhere form 18 to 35 minutes.  On Jenkins, they averaged 10-12 minutes.  We need to get the GHA speed down closer to what we had with Jenkins.

**Comment by CBonade** [comment]
An update on this yesterday:

After trying everything I could think of to rework our pipeline steps, I came up empty.  The thing that stuck out to me, was that removing everything related to Cypress, even the webpack compile times were just about double what they were on Jenkins by comparing side by side.  This to me sounded like a hardware issue.

After chatting with ops, it was determined that GHA runners were running on 2xlarges while Jenkins had been running on 4xlarges.  The Github runners have been bumped up to 4xlarges, however, they have to be manually swapped out on each of the 10 runners and that has to be done while no other processes are running, so it's being worked on as possible.

Will continue to monitor the testing suite speed after it's been confirmed this has been updated.

**Comment by CBonade** [comment]
After updating the speed of the runners, the build times have drastically improved on the testing front and I believe are below our target goal of 15 minutes. Process index 1 has the highest time, as it contains our largest spec.  We might be able to trim this down by breaking that spec apart into separate tests, but outside of that, there's not a lot more optimization that I see opportunity for here.

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/c87f2f73-6c02-45b2-8444-f29e08117842)

I think we're ready to close this one out.

**Comment by CBonade** [comment]
While we are seeing a large quantity of timeouts currently, I think those fall under the failures ticket and can be kept separate from this.  When the tests do succeed currently, they're doing so in an acceptable timeframe.

**Comment by pjhill** [comment]
Thanks for working this with Ops. I guess when you hear hooves think horses and not unicorns!
