### ISSUE TITLE
Replace 'View'

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27189]
## Background
In the current state of the app, the word 'view' is leveraged many times but it not friendly to users with accessibility needs. 

## UX Actions

- [ ] Determine what word could be used in place of 'view'

- [ ]  Review app content to make sure the new word makes sense in the place of 'view'

**Comment by msmanak** [comment]
## Pages that show "View"

**"View your medical appointments"** 
Change this to "_open_ your medical appointments"
Change this to "_Access_ your medical appointments"
Change this to "Review your medical appointments"

**"To view more details about your appeal, visit VA.gov: ",**
Change this to "To open more details about your appeal, visit va.gov"
Change this to "to _Open_ more details about your appeal, visit va.gov"
Change this to "To _access_ more details about your appeal, visit va.gov"
Change this to "To _review_ more details about your appeal, visit va.gov"

**"view what you will need to verify your identity"**
Change this to "_Open_ what you will need to verify your identity"
Change this to "_Access_ what you will need to verify your identity"
Change this to "_Review_ what you will need to verify your identity"

**"View your appointments and send messages",**
Change this to "_Open_ your appointments and send messages",
Change this to "_Access_ your appointments and send messages",
Change this to "_Review_ your appointments and send messages",
