### ISSUE TITLE
Cutover statsd reporting from statsd_exporter to datadog

### ISSUE THREAD

**Issue by cbtkc** [department-of-veterans-affairs/va.gov-team#27183]
StatsD messages will need to be cutover to use the new datadog agent that is installed on the machines, as prometheus and statsd_exporter are going to be deprecated.

AC:
- [ ] `STATSD_HOST`, `STATSD_PORT`, & `STATSD_ADDRESS` pointed at datadog-agent
- [ ] Add matchers in `datadog.yaml` for all custom metrics
- [ ] Add/migrate alerts

**Comment by cbtkc** [comment]
[DevOps PR](https://github.com/department-of-veterans-affairs/devops/pull/9601) added to cutover sbx and dev envs to start reporting into datadog.

**Comment by cbtkc** [comment]
vets-api statsd in the dev environment is now reporting into datadog, but is reporting an integration issue that @mydesignrocks is researching.

**Comment by cbtkc** [comment]
Started a [thread](https://dsva.slack.com/archives/CQHBJ5U06/p1630594637012600) in the vsp-tools-be channel to discuss this ticket.

I will post updates on this ticket as well as I make progress.

**Comment by jeff2d2** [comment]
Is this considered unblocked now @cbtkc ? Just want to remove that label if indeed it is.

**Comment by cbtkc** [comment]
@ericboehs Can we call this ticket done? vets-api StatsD messages are now reporting into Datadog.
