### ISSUE TITLE
Subtask:  (PPMS) Resolving Data Blocker Discrepency

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2718]
Test Findings and Scenarios for Veteran Needing Network Information

**TESTING RESULTS**
We have attached the spreadsheet that was shared at our meeting this afternoon. We compared five different locations (Washington DC, Houston TX, Ann Arbor MI, Portland OR, and Decatur AL) for two services (Walk-in Retail Health Clinic (POS 17) and Urgent Care Facility (POS 20)) in PPMS, VA.gov’s Facility Locator and the TriWest Locator. On the first tab, we listed the top 5 search results. In the subsequent tabs, we attached screenshots for each search in each location.

In the TriWest Locator, we searched by ZIP code.
In PPMS, we used the search criteria: ZIP code, Place of Service Code (POS 17 and 20), Provider Network (TriWest -PC3, TriWest - Choice).
In VA.gov’s Facility Locator, we searched by ZIP code

**A few notes to keep in mind:**
VA.gov does not make a distinction between POS 17 and 20, which is why the results for each data set are the same.
We needed to use the ‘zoom out’ feature in Decatur, AL to get sufficient results to finish the chart, as the baseline view only provided 4 results.
There are nationwide results for ‘American Current Care of Arizona PA,’ however it appears that these may be mis-named Concentra facilities.

[PPMS Results Testing_092319_.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3768924/PPMS.Results.Testing_092319_.xlsx)

**Comment by mmiddaugh** [comment]
Closing as a duplicate to [3051](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3051)
