### ISSUE TITLE
Access for Sebastian Cooper [KVortex Contractor of AFS]

### ISSUE THREAD

**Issue by SebVortex** [department-of-veterans-affairs/va.gov-team#27180]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > Sebastian Cooper
- Please Provide your email.
   > sebastian.cooper@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team 3 React developer. Accenture Federal Services/Knowledge Vortex

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChTAAepPIHrxTRAKqe72jp1EmINpMApvXJPxuKnGlftwNnBCQYfJx687L7xOROPqC1G7f4m1MM4NvwWvbhNa75kYViL7+VDItR9izqEfo03iHwVKgtgggjU+suOd+iLWlxmSdYImPeoNqlUawPvNfW1bXgNN6cbFnCK4utk2bFp35glJYyVLAtO+j+R9gpZVRz4eu4cXNHFjQ5tCzQCXS0gqioXUM94R471FJSoeB8yiK5SMeixFUlt5uyTBSHWV2hFFOfQW6Xc3YTkhTBoUcyWoUYF+AO73lwSH3GSBy1MsBr+a3tnVz9PscfqyEJWnKlfoF/99l6fAFlScnQRJF4jeR+cRn9zQuWz4OtI99bIN5DBkHfb5M5r8RPmdDqivtcl2X4xW7NQ1rsNtZuI5GD+O1rYp4+zmmp62C2dQ0qcs+mrQW6e9ic++FxDZivws302rO/7KCMe92OU/PqICR3W7MhEBvGR2X5bVVxUs9dLQz6pQSdRQ0g5dwTcK0F6SE= sebastian.cooper@AFSMWDX5KYL79P4
```

- Grant AWS Console access?
  > NO

**Comment by tskinn** [comment]
@SebVortex your key has been added and you should be able to connect now. Reach out in slack in the vfs-support channel if you have any issues.
