### ISSUE TITLE
Access for LeRoy Michaelson

### ISSUE THREAD

**Issue by LeRoyMichaelson** [department-of-veterans-affairs/va.gov-team#27190]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your name.
   > LeRoy Michaelson
- Please Provide your email.
   > leroy.michaelson@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team 3 - Comparison & Feedback Tool
   > Tech Lead
   > Accenture Federal Services
- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBcRoFFHrjZKdc15E3/jYUu/+/mD/wCEr1/6sO0ApNnEwuwYSp+utH9lD7yvhtG72ig0qwTwz55ylWf5FPLXxlZeI\
7+bwRwNj4sPKRAZDhGpmAW7FXsKkYR1HJJc0ydE4aeCmsaNvf1x/3r4FI1BL80/Pe1j7cFKFjsUjtJsSVxr/GW67KkQlEiRZud5CEjALacy/X+/mWlU29bJ2rq8nubU\
dMdQF3rdRPCcN7sSlgJfw2oL7OeASHb8usz+QvGjf6DBCVNwNfCYOxLQUB726KOP/RYxfFmDjLi3/qgvG9u9gjLpneUiBQveMamW7b8Stc4URUpVpiennBHQuILSsYO\
SZ5LulaaJRaOAndhrkLkEtTziSNsiMm0phxxXu5Sq1MmXVzPn/r52OSgjrlHVcBPGqilOGvWb4Hs9J+72a18SqaxtwNEE5hF67+fOXcDO8BsCGv2lzvpcomFahX5hwD\
iQ/2BLlaR1I37Ad2thlSQptz0vP1u7AOug1GAr/O2l0= leroy.michaelson@AFSMWB3IV3UF2GN
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by tskinn** [comment]
Hey @LeRoyMichaelson your key has been added to the proxy. You should be able to connect now. Reach out in slack if you have any issues.
