### ISSUE TITLE
Access for Stan Gardner, sgardner@governmentcio.com - SOCKS

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27194]
# Description
- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins.

- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Stan _Gardner_
- Please Provide your email.
   > sgardner@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   VSA-VAMC-UPGRADE / VAMC-UPGRADE,  Role:Product Manager, Company: GovernmentCIO

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDiWiN6cCcq/EwDrO1R+wtuFiqdR2mowJ0/zAuvKZJWLWL8RzWYkvi18oQP8pytOZMzdWxOEYgGqxS5YV//ej+wtZztZCwf/x538uKG0SqzzzOzquaOHByoPJp+rrzC/ygqVZsR9xc1UdEzHZU8hnoKFCbIzUAT7dwvbjvk8hEajmhVT56vTBmNnHmoXIdNwaEBVPbA0x53L4Rt3PVzeZBZLlxR7wcstCnfYGKdjn96MpxmeVdObf6/0Sj+Xh82Fc3Wa6CWDZDFy6+nBOyBJFh2LTqFvyfugpNDuKFhE6tw5SNT/u5cyqw5XaPnyog2wakf1kaKvTiqOgjlpcdNLL71mjlkLBCTc/OFQZHjLBNVqB7KLzCLIB3UH9h/oE0o6fgonT89045Z0ruNYYjPoUzHxDDtugzLq5+ruae/v6SDPg/mBTjejOLPOXNvnjzVm8mc3dJH+2gaomXFoczblp8LXfsL5dSNpxjFSCnTz70vRVcC7HhcnpLQrJBBCgtmZSc= SGardner BJQ4PV2@Sgardner-BJQ4PV2

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by tskinn** [comment]
@SgardnerPMP it looks like you already have socks proxy access. Do you just need us to update your public key?

**Comment by SgardnerPMP** [comment]
@tskinn I am swapping out computers.  Once this new SOCS proxy is active, and I confirm it is working,  Please drop the other.   I'm currently using it until this SOCKs connection is up and running.   Unless there is no way to have two at the same time, I understand, so we can just update and I will get this one up and running.   Thank you.

**Comment by tskinn** [comment]
@SgardnerPMP you new key has been added. Can you verify that you can connect?

**Comment by SgardnerPMP** [comment]
Getting this error, and confused as my file name is id_rsa, not id_rsa_vagov.   "Warning: Identity file /c/Users/SGardner BJQ4PV2/.ssh/id_rsa_vagov not accessible: No such file or directory."

**Comment by tskinn** [comment]
Your ssh config expects `id_rsa_vagov`. But I think you should be able to update your ssh config to `id_rsa` without issue. This is where you would change it https://github.com/department-of-veterans-affairs/devops/blob/master/ssh/config#L25

**Comment by SgardnerPMP** [comment]
Working this now.

**Comment by SgardnerPMP** [comment]
updated config line 25 and I am in.  Please remove previous SOCKS connection I will be sending that laptop back.  Thank you for your help.  You can close this issue.
