### ISSUE TITLE
Collaboration Cycle Kickoff - Decision Tools - Discharge Upgrade Wizard July 2021 Content Updates 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27197]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] VFS: Attach any available artifacts.  

- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
- Link to wireframes, mockups, or prototypes
- Any other artifacts you have so far
  -   [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/post-mvp/2021-content-updates/initiative-brief.md)
  - [update_request_1.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6804191/update_1.pdf)
  - [update_request_2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6804192/update_2.pdf)
  - [Kurta memo referenced in requests](https://github.com/department-of-veterans-affairs/va.gov-team/files/6804193/kurta_memo.pdf)
## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [X] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [X] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [ ] Yes
- [X] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work involve changes to: (select all that apply)

- [X] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 6. Will your work include:  

- [X] New content
- [X] Changes to existing content

### 7. Are you making a change to the user flow?
- [ ] Yes
- [ ] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 8. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [X] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 9. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [ ] Yes
- [X] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 10. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

### 11. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [X] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @MarciMcGuireGCIO. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Design Intent
- Analytics Request
- Midpoint Review
- Contact Center Review (you may not need a full review, however please check to see if your Product Guide needs updating)
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process: (select all that apply)

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman would you mind attaching this to Epic #27212 for me?  I don't see to have the authority on this ticket.

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO looks like it's already link to the epic.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman Thanks!   Hmmm...  there seems to be a new bug in ZenHub.  When I initially load some issues, there are several fields - like Epic - that sometimes aren't visible (estimate is another), but when I refresh (sometimes more than once), they magically appear.  So far cannot identify a pattern. Strange.

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO hahaha i noticed the same thing this morning! refreshing the page worked for me. It was in github too, not just Zenhub

**Comment by MarciMcGuireGCIO** [comment]
Doh!
