### ISSUE TITLE
[Design] Distinguish in person vs. at home video appointments

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#27193]
### Problem
Veterans report that the [VA Video Connect at a VA location](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointments-cards/confirmed-va-video-clinic.png) label is misleading, as they expect  to be able to join VA Video Connect appointments from anywhere. 

### Assumptions

- It's most important for a Veteran to know where they need to be for an appointment first, and then the method of the appointment
- A Veteran scanning their appointment information could easily miss "at a location" in the type label

### Hypothesis

If we distinguish that a Veteran needs to go to a specific location for certain types of appointments, there will be less confusion and fewer complaints about this the VAOS home page.

### Questions
- Aside from VAVC, what other methods are there for joining appointments?
- Do we need to distinguish VAVC appointments (vs. just calling them video appointments)?
- See screenshot for open questions about different video appt types

![Screen Shot 2021-07-14 at 8.32.38 AM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/2b57060d-9093-4e4a-ab08-0156f69458f3) 

### Research/analytics
- This came up through facility feedback, who reported on behalf of Veterans. 
- There aren't many appointments of this type, but we could prove out potential solutions through UAT.

### Related tickets
* [Design - "At ATLAS site" (Ad Hoce - ATLAS & Mobile_Any - ATLAS)](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13053)
* [Design - Account for VVC Store_Forward appts#15294] (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15294)
* ["At VA Facility" VVC appts (Clinic-Based)#13055]
(https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13055)

### Design assets
Design will provide:

- [ ] Sketch file showing content changes in context for:
* Current home page
* Home page refresh

**Comment by ldelacosta** [comment]
Adding this to the Appointment List feature. We will test the appointment modality when we go live. cc: @outerpress

**Comment by outerpress** [comment]
Work on the new home page addresses this, closing
