### ISSUE TITLE
Access for Ryan Leahy

### ISSUE THREAD

**Issue by Rleahy22** [department-of-veterans-affairs/va.gov-team#27205]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Ryan Leahy
- Please Provide your email.
   > ryan.leahy@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Public Websites

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICVgtIvd4OoqQ0yVk0Fd35b0Vp+30hXcxyKBtQewP7M/ ryanleahy90@gmail.com
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by tskinn** [comment]
@Rleahy22 you key has been added and you should be able to connect now. Reach out in slack in the vfs-support channel if you have issues.
