### ISSUE TITLE
Accordion variants refactor to web component

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#27200]
# Description

There exist a number of accordion variants across va.gov, specifically:

```
src/site/navigation/sidebar_nav.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid
src/site/layouts/campaign_landing_page.drupal.liquid
src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
src/site/paragraphs/collapsible_panel.drupal.liquid
src/site/facilities/health_service.drupal.liquid
src/site/includes/usa-website-header.html
src/site/facilities/facility_health_service.drupal.liquid
```

These accordions should all be updated to use the web component, e.g.
```html
<va-accordion multi>
```

https://design.va.gov/storybook/?path=/docs/components-va-accordion--default

## Acceptance Criteria

- [ ] src/site/navigation/sidebar_nav.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/layouts/faq_multiple_q_a.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/layouts/health_care_local_facility.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/layouts/campaign_landing_page.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js updated to use `<va-accordion>` web component.
- [ ] src/site/paragraphs/q_a.collapsible_panel.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/paragraphs/collapsible_panel.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/facilities/health_service.drupal.liquid updated to use `<va-accordion>` web component.
- [ ] src/site/includes/usa-website-header.html updated to use `<va-accordion>` web component.
- [ ] src/site/facilities/facility_health_service.drupal.liquid updated to use `<va-accordion>` web component.

**Comment by mpelzsherman** [comment]
Please make sure to review the requirements around Google Analytics for the accordions, and be sure not to break them.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/21555

**Comment by Rleahy22** [comment]
It looks like we'll want to hold off on `src/site/navigation/sidebar_nav.drupal.liquid` until another time: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26280#issuecomment-871568160

**Comment by Rleahy22** [comment]
Do we want to replace the accordion in `src/site/includes/usa-website-header.html` right now? I don't know that we will be able to match the UI with `va-accordion` at this time.
<img width="997" alt="Screen Shot 2021-07-16 at 4 05 08 PM" src="https://user-images.githubusercontent.com/3144003/126003024-07b208aa-55cb-4089-ae87-3e291082595c.png">

**Comment by Rleahy22** [comment]
One thing to note for validation is that the event properties are named differently in the web component version but the new names are preferred, see: https://github.com/department-of-veterans-affairs/content-build/pull/378#issuecomment-884218894 and https://github.com/department-of-veterans-affairs/content-build/pull/378#issuecomment-885077339

**Comment by brianalloyd** [comment]
Validated and closing.
