### ISSUE TITLE
Diagnose and remove duplicate output from E2E testing suite

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#27211]
The test results for each assertion are showing double in the Cypress test output. This uses extra resources and may be confusing to someone unfamiliar with the bug.  This should be reworked to only show once, as we are only running each test once.

**Comment by CBonade** [comment]
After numerous attempts, the problem here ended up being doubling up the default "spec" reporter with other reporters such as the JUnit reporter and Mochawesome.  Removing "spec" did not lose us any information output, however it removed the duplicate line on each spec as desired. This PR is open and awaiting passing it's checks and reviews.

**Comment by CBonade** [comment]
This is merged and ready to close!

**Comment by pjhill** [comment]
This [PR ](https://github.com/department-of-veterans-affairs/vets-website/pull/17840)has resolved the issue.
