### ISSUE TITLE
CT: Display institutions that have a suspended state

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27210]
As an education team member, I need institutions that are suspended to be displayed within the comparison tool, because they have 60 days to address any issues before being changed to a withdrawn status and removed from the comparison tool.

## Assumptions:
1. This work is entirely in GIDS, so does not need a prod/feature flag and will just need a production deployment.

## Acceptance Criteria:
1. Institutions with a WEAMS poo status of "SUSP" are included in GIDS version generation.
2. Institutions with a status of "SUSP" are assigned a caution flag.
3. Suspended institutions are displayed within the Comparison Tool with the suspended caution flag text:

    > Title: School may not be able to accept new GI Bill students 
    > 
    > Description: This school currently doesn't meet the approval criteria for receiving GI Bill funds and has been suspended. The suspension doesn't impact current students. 

### Technical note:
1. The suspended caution flag is developed as a back-end configuration.

## Supporting Artifacts:
1. Profile mockup with suspended caution flag: https://bahdigital.invisionapp.com/share/XUIAHBLZY4F#/screens

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/850

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2094&group_by=cases:section_id&group_order=asc
