### ISSUE TITLE
Sleep Medicine / CPAP choice content

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2722]
As a veteran, I want help understanding which 'sleep medicine' follow-up type of care I actually need so that I can make the right decision.

AC
- [ ] Help content for this page attached to this ticket
- [ ] Peggy has reviewed content
- [ ] Content shows on the sleep medicine follow up page in the app

Adding @lalexanderson-dsva because I think she had a first draft of content already going.

Page that needs content:
<img width="817" alt="Screen Shot 2019-10-24 at 1 57 29 PM" src="https://user-images.githubusercontent.com/24251447/67516618-89c50b80-f666-11e9-98df-b85e534d3fec.png">

**Comment by lalexanderson-dsva** [comment]
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2396

**Comment by markgreenburg** [comment]
#dupe of #2396
