### ISSUE TITLE
CT Redesign: Update profile for OJT/Apprenticeship institution types

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27230]
As a developer, I need to update the OJT/Apprenticeship profile page so that the appropriate information is displayed in a consistent manner with other institution profile page types.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria
1. The "Veteran programs and support":
    a. jump-link is not displayed in the "On this page" header section
    b. section is not displayed on the OJT/Apprenticeship profile page.

2. The following content is displayed under the grey "Your estimated benefits" box in the "Calculate your benefits" section:

    > Note: Housing rate and the amount of entitlement used decrease every 6 months as training progresses

3. The content on the search results card

    > "Housing rate and the amount of entitlement used decrease every 6 months as employer pay increases"

    is replaced with:

    > "Housing rate and the amount of entitlement used decrease every 6 months as training progresses"

4. The "Book stipend:" in the "Your estimated benefits" section of the grey panel has a "Learn more" with the following content:

    > You may be eligible for money to cover books and supplies, up to $83 per month.

5. The "Book Stipend" data (with the monthly breakdown) under the "Estimated benefits per month" section of the grey panel is not displayed.

6. The "Housing allowance" Learn more in the "Estimated benefits per month" section of the grey box displays the following content:

    > **Your housing allowance is determined by where you take training**
    > 
    > Under the GI Bill you’re eligible to receive a monthly housing allowance. We calculate this monthly housing allowance based on where you take training.
    > 
    > [View the current housing allowance payment rates](https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376)
    > 
    > For on-the-job training and apprenticeships, housing allowance decreases every 6 months as employer pay increases.  
    > [Learn more about how the housing rate decreases over time.](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/)

7. The "Calculate your benefits" section "Additional information regarding your benefits" sub-section and related content below is not displayed:
    a. Veterans tuition policy
    b. Protection against late VA payments
    c. Yellow Ribbon Program
    d. Veteran Rapid Retraining Assistance Program

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens/296063148)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/907b86789afadfe4b3db36a092fa66bc69cc9e5d/products/education-careers/school-comparison-tool/redesign/design/content-OJT.md)
3. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/907b86789afadfe4b3db36a092fa66bc69cc9e5d/products/education-careers/school-comparison-tool/redesign/design/content-OJT.md#your-estimated-benefits) section reference for AC 4, 5, and 6.

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18062

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2049&group_by=cases:section_id&group_order=asc
