### ISSUE TITLE
FSR 75b debt alert review from the Debt Resolution team 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27233]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[x] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?
Veterans are mistakenly receiving notifications about owing 75b debts (represented as 'Chapter 33 Tuition, Fees, Yellow Ribbon – School Liable' in the DMC's deduction code spreadsheet). While the DMC troubleshoots why Veterans are receiving these notifications, our stakeholders requested we put up an alert in the debt portal with the following content: 

> If you are a student who received a letter regarding a 75B tuition debt:
>
> Please note that a 75B deduction code identifies a debt assigned to your educational institution. Please communicate with your educational institution prior to making payment on their behalf in order to avoid potential duplicate billing.

Prior to putting this content on the site, we wanted to get it reviewed to ensure we're following plain language guidelines. 

### The alert's design 

![Screen Shot 2021-07-13 at 12.18.22 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/944dc5a6-45a9-4d0f-bb07-8ed8ddd83aa3)

[View the UXPin prototype to see the alert in context of the entire page. ](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/140309044/simulate/no-panels?mode=i)

Our proposal is to use the experimental design system's minimalist alert due to the existing Coronavirus alert and that this is a use case that doesn't impact all users. 

## When does this content work need to be done?

As soon as possible to try to mitigate the contact center call volume 

## Do you plan to bring this to an upcoming content office hours session?

- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Self
-	Product manager: Linda Li
-	Designer: Riley Orr, Rebecca Walsh
-	FE engineer: Craig Wheeler, Justin Linn 
-	Product/team Slack channel: vsa-debt

## Links to related tickets

- [Original ticket that sparked this work](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26838)

**Comment by LindaLi123** [comment]
@rileyorr Hey Riley, when can this be live?

**Comment by rileyorr** [comment]
@LindaLi123 I'm going to our suite's content office hours in 17 minutes to chat about this! Will have an update for ya afterwards

**Comment by rileyorr** [comment]
@LindaLi123 just chatted with @bethpotts & @DanielleThierryUSDSVA and they are currently revising the alert and will update this ticket soon! 🚀

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rebeccawalsh and @rileyorr. Here's content based on our conversation. Definitely need to check the accuracy with SMEs, as it was a bit hard to really get all the nuances of the meaning from the original. Just let me know if you need more help with this. Thanks!

**If you got a letter about Chapter 33 tuition debt with code 75B**
This is a debt assigned to your school. You won’t find it listed here. Before you make a payment on this debt, check with your school. They may have already paid.

**Comment by rileyorr** [comment]
@LindaLi123 I've updated the UXPin prototype ([view here](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/140309044/simulate/no-panels?mode=i)) with the proposed content. I've also attached a screenshot of the alert below. Per Danielle's comment, we should check the accuracy with Jill. Do you want to send it over to her since you've been communicating with her about this work?  

![updated-75b-content](https://user-images.githubusercontent.com/46329147/125956281-bd180258-80bf-4e62-92ed-afbba99f42bc.png)

**Comment by LindaLi123** [comment]
@rileyorr  Yes i will check with Jill and confirm as soon as i hear back.  Thank you so much!

**Comment by LindaLi123** [comment]
@rileyorr Hello Riley, would you please confirm if It is only the 75B letters that are showing in the portal and not the 75B debt balances?   If so then the message is approved.

**Comment by rebeccawalsh** [comment]
@LindaLi123 We wrote and collaborated on the content and information Jill sent to you. As far as I know, neither balances nor letter downloads should be available for 75B debts in the tool, but this is a bug so we're not sure what the actual behavior of the bug is. If there is something technically wrong with the messaging, we'd have to know what it is from either Jill or an engineer who is familiar with the exact bug behavior.

**Comment by rileyorr** [comment]
@LindaLi123 per the meeting we just had, I updated the alert to say 'email' instead of 'letter' since we just learned they're email notifications instead of letters. [The UXPin has been updated and can be viewed here.](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/140437273/simulate/sitemap?mode=i) I'll write up a frontend ticket and edit this comment with a link in a moment!

<img width="972" alt="Screen Shot 2021-07-20 at 1 05 30 PM" src="https://user-images.githubusercontent.com/46329147/126366932-23270335-0f2a-4eaf-9195-69b8cbc70fa4.png">
