### ISSUE TITLE
CT Redesign: Create VETTEC profile page framework

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27234]
As a developer, I need to create the framework for the VET TEC profile page so that multiple developers can work on the page at once implementing the various sections.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This is for VET TEC institution types.
3. The "contact information" component can use the same component that is used for the non-vettec profile page.
4. The "Cautionary information" component can use the same component that is used for the non-vettec profile page.

## Acceptance Criteria:
1. The header card displays the "* Preferred provider" indicator and corresponding learn more under the city, state of the provider.
2. The preferred provider learn more displays the following content when clicked:

    > **Preferred training providers**
    > 
    > A provider is “preferred” if the training facility agrees to refund tuition and fees to VA if the student completes the program and doesn’t find meaningful employment within 180 days.

3. The following data elements are not displayed in the header:
    a. Certificate program
    b. Institution type (ex. For profit school)
    c. Institution size

4. The following data elements are displayed in the header:
    a. Phone number
    b. Location type (ex. City locale)
    c. URL

5. To the right of the header card is the "On this page" section with the following jump-links
    a. Calculate your benefits
    b. Approved programs
    c. Getting started with VET TEC
    d. Cautionary information
    e. Veteran programs
    f. Get started with CareerScope
    g. Contact information

6. A placeholder section for each jump-link in the "On this page" section of the header exists.
    a. Each section has correct CSS  (i.e borders and header css) and spacing between sections.
    b. Each section can be scrolled to via jump links in the "On this page" section of the header.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens/296062934)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17865

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2004)

**Comment by delli-gatti-michael** [comment]
testing complete
