### ISSUE TITLE
HP Alert Banner Updates

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#27240]
# Public Websites Banner Intake Request Form

## Description

- OPIA (Josh Tuscher) has signed off on adding the "dismissable X" on the HP Banner Alert (COVID) -- as long as the banner reappears if new content is added to it.

<img width="779" alt="Screen Shot 2021-07-13 at 2 19 26 PM" src="https://user-images.githubusercontent.com/63107147/125504788-c90ec0f2-1fa4-472c-bf33-78d65493e208.png">

- We can remove the "Sign up COVID vaccine at VA" sticky banner on the HP.

<img width="1142" alt="Screen Shot 2021-07-13 at 2 14 35 PM" src="https://user-images.githubusercontent.com/63107147/125504509-251430c7-62fa-4ece-89a9-fe7f27b7be45.png">

## Stakeholders

Who specifically should we communicate with when building + deploying the banner?  Please provide relevant contact details and desired slack details for forward communication.

- John Hashimoto (I'll communicate the change to OPIA/Josh Tuscher when deployed)

**Comment by johnhashva** [comment]
@brianalloyd working to confirm removal of the sticky banner via Lauren and Danielle.  Will update the ticket when I get word.

**Comment by johnhashva** [comment]
Update @brianalloyd: Danielle says the sticky banner should remain up as there is new emphasis on urging the vaccine given the implications of the Delta variant (and continued slow uptake).   However, she would like us to change the sticky banner text to: _Get a COVID-19 vaccine at VA_

**Comment by johnhashva** [comment]
@brianalloyd final decision on sticky banner text change from @DanielleThierryUSDSVA --

Get a COVID-19 vaccine at VA

Let us know if any questions about this one.

**Comment by brianalloyd** [comment]
Thanks @johnhashva I'm shifting this over to our Stick Banner ticket [25694](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25694) feel free add additional details on that ticket as they come up.  Thanks.

**Comment by brianalloyd** [comment]
Worked like a charm.  @kelsonic how do we test for the use case of "when a new update is applied, it will reappear of users browser"?

**Comment by kelsonic** [comment]
If you dismiss the homepage banner on https://www.va.gov right now, the next time there is a homepage banner update we can see if it reappears. Desired behavior is that the homepage banner does reappear when updated (due to the copy change) even if we previously dismissed it.

**Comment by johnhashva** [comment]
@brianalloyd and @kelsonic -- Josh is planning to update the text of the COVID alert on Monday morning so we can test it then.

**Comment by brianalloyd** [comment]
Thanks @johnhashva that's great, we'll keep an eye out for the update in support of validation.

**Comment by brianalloyd** [comment]
Validated, closing ticket in support.
