### ISSUE TITLE
Collaboration Cycle Kickoff [10-10EZ Short-form using Auto-qualifiers]

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27242]
## Steps to complete Collaboration Cycle Kickoff
- [X] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [X] VFS: Answer the questions below.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Collaboration Cycle touchpoints:

- [x] Design Intent (#27617)
- [x] Information Architecture (IA) Request
- [ ] Research Plan Review
- [x] Analytics Request (#27724) 
- [x] Midpoint Review
- [ ] Contact Center Review
- [ ] Staging Review
- [x] Privacy and Security Review
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
- Link to wireframes, mockups, or prototypes
- Any other artifacts you have so far (see **Project Overview** below)

### Project Overview

In order to improve the submissions and user experience for Veterans applying for health care using the online 10-10EZ application, we are looking to implement the ability to recognize automatic qualifiers and use those to skip portions of the online form. The primary example of this is using the user's combined service-related disability rating to skip sections of the form containing information that is no longer relevant, such as the household and financial information.

The proposed flow would be something like this:

1. The Veteran begins the 10-10EZ online form
2. If they have logged in, when we retrieve their account information we will also retrieve their combined service rated disability.
3. The Veteran will fill out any remaining or blank personal information (address, phone #, etc.)
4. If the combined service related disability meets the qualifications, we will inform the Veteran they may skip other sections and then take them to a later point in the form (likely Insurance information or Review).

Designs and flows are still being finalized but from a general perspective the work includes:
1. Retrieving new profile information (combined disability rating)
2. Dynamically altering the flow to skip chapters and sections
3. For any information we skip, we may need to send certain default values to the backend system
4. There may be new a new screen or messaging to discuss the fact that the veteran can skip sections.

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [X] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [X] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [X] Yes
- [ ] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work involve changes to: (select all that apply)

- [X] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 6. Will your work include:  

- [ ] New content
- [X] Changes to existing content

### 7. Are you making a change to the user flow?
- [X] Yes
- [ ] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 8. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [X] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 9. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [X] Yes
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 10. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

### 11. Who is the VA business owner for this body of work?

- [X] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @PM-handle. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Design Intent
- Information Architecture (IA) Request
- Research Plan Review
- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process: 
- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the Platform Collaboration Point Tracker. Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by SKasimow** [comment]
@Dene-human Hi Dene - can you provide the relevant tickets/links for research so I can include above? Thx!

**Comment by Dene-human** [comment]
@SKasimow 
Here is a link to the short form [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/10-10EZ/Short%20form%20flow%20research) which includes:
- [Research Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/topline%20summary-%20research%20findings.md)
- [Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/Research%20findings.md)
- [Research Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/Research%20Readout_%2010-10EZ%20Short%20form%20usability%20.pdf)


Here are the completed research tickets:
- #29089 
- #29738 
- #29683 
- #29684

**Comment by markfallows** [comment]
@hdjustice What are the rules on closing out Collab Cycle tickets?  Are we able to close this one?

**Comment by hdjustice** [comment]
Yes, we can close this now that we have launched to production

**Comment by shiragoodman** [comment]
@hdjustice @markfallows  - general rule of thumb - any Collab Cycle ticket you open, you're free to close. The only time we may reopen is if Platform hasn't completed all our tasks, but we usually get those done within a day or 2 of the review. Platform will never close any of the Collab Cycle tickets opened by VFS teams.
