### ISSUE TITLE
CT Redesign: Create VETTEC "Getting started with VETTEC" component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27258]
As a developer, I need to create a "Getting started with VETTEC" component so that it can be used in the new CT Redesign VET TEC profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for VETTEC institution types.

## Acceptance Criteria
1. The section has the following sub-sections:
    a. What types of training does VET TEC cover?
    b. What benefits can I get through this program?
    c. How do I apply for VET TEC?

2. The content of the "What types of training does VET TEC cover?" sub-section is:

    > **What types of training does VET TEC cover?**
    > ****
    > You can get training in one of these high-demand training areas:
    > 
    > - Computer software
    > - Computer programming
    > - Data processing
    > - Information science
    > - Media applications

3. The content of the "What benefits can I get through this program?" sub-section is:

    > **What types of training does VET TEC cover?**
    > ****
    > With VET TEC, you can get:
    > 
    > - Tuition for a full-time high-tech training program
    > - Money for housing during your training
    > **Note:** If you're on active duty, you're not eligible to receive a housing allowance.
    > 
    > **If you attend your training program in person,** your housing stipend will be equal to the monthly military Basic Allowance for Housing (BAH) for an E-5 with dependents. This is based on the zip code where you attend your training.
    > 
    > **If you participate in an online program,** your stipend will be half of the BAH national average for an E-5 with dependents.
    > 
    > **Note:** If you don’t attend a training for a full month, we’ll prorate your housing payment for the days you train.

4. The content of the "How do I apply for VET TEC?" sub-section is:

    > **How do I apply for VET TEC?**
    > ****
    > **To apply for the VET TEC program, you'll need to:**
    > 
    > 1. Fill out an Application for Veteran Employment Through Technology Education Courses (VA Form 22-0994). If we approve your application, you’ll get a Certificate of Eligibility (COE) in the mail.
    > 
    >     (Chevron Icon) [Apply for VET TEC (VA Form 22-0994)](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction)
    > 
    > 2. After you’ve been approved for VET TEC, you can then apply to the VA-approved training program you’d like to attend.
    > 
    > To learn more about these approved programs, visit the training provider's website.
    > 
    > **What if I have questions about the VET TEC program?**
    > 
    > - Call us at 888-GIBILL-1 (888-442-4551). We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET. If you have hearing loss, call [711](), or
    > - Email us at [VETTEC.VBABUF@va.gov]()

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens/296062934)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/19b896f6c02f38b4e00cb14eb8c4f2d24a778fb0/products/education-careers/school-comparison-tool/redesign/design/content-VETTEC.md#getting-started-with-vet-tec)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17895

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2024&group_by=cases:section_id&group_order=asc
