### ISSUE TITLE
Calendar Updates

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#2725]
## Description
Based on discussion, the calendar needs the following updates:
- Currently, if a user has a datetime selected and they click on another day, their selection is cleared, even before they've selected a time or am/pm.  The selection should remain until the user chooses a time or am/pm.
- The first month displayed should be the same month that the user selects for their preferred date (wait time)
- Min/max dates should be set
  - Direct schedule:
    - No same day scheduling
    - Max day is 395 days out
  - Requests
    - No requests within 5 days
    - Max day is 395 days out

## Acceptance Criteria
- [ ] Calendar updates implemented

**Comment by markgreenburg** [comment]
@narin let's chat about the 5-day thing for requests, want to understand where that came from.
