### ISSUE TITLE
CT Redesign: Create VETTEC "Calculate your benefits" and "Approved programs" components

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27256]
As a developer, I need to create a "Calculate your benefits" component so that it can be used in the new CT Redesign VETTEC profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for VETTEC institution types.

#### For "Calculate your benefits"
1. The Benefits estimator calculator section includes the current controls and calculations of the "Estimate your benefits" section of the current profile page for VETTEC institutions.
2. The first program in the radio button list is selected by default and populates the "Your estimated benefits" calculations accordingly.

#### For "Approved programs"
3. Displays the following content with a table of approved programs:

    > The following training programs are approved for VET TEC:

4. The table of approved programs has the following columns:
    a. Program name
    b. Length
    c. Tuition & fees

5. The program selected in the "Calculate your benefits" section:
    a. is bold in the approved programs table
    b. has the following text appended to the program name: "(Selected program)"

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens/296062934)
2. [Content Doc - Calculate your benefits](https://github.com/department-of-veterans-affairs/va.gov-team/blob/19b896f6c02f38b4e00cb14eb8c4f2d24a778fb0/products/education-careers/school-comparison-tool/redesign/design/content-VETTEC.md#calculate-your-benefits)
3. [Content Doc - Approved programs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/19b896f6c02f38b4e00cb14eb8c4f2d24a778fb0/products/education-careers/school-comparison-tool/redesign/design/content-VETTEC.md#approved-programs)

**Comment by ksantiagoBAH** [comment]
pr: https://github.com/department-of-veterans-affairs/vets-website/pull/17957

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2025&group_by=cases:section_id&group_order=asc&group_id=46
