### ISSUE TITLE
Update Attachment Limit Copy 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27265]
## User Story
As a user, I want to know attachment requirements so I can successfully send a message with an attachment to my provider. 

## Acceptance Criteria 
* When a user clicks on 'How to attach a file' link on the compose or reply forms, the copy referring to attachment file sizes is updated to reflect the new limits:

"The file size for a single attachment cannot exceed 6 MB and the total size of the attachments cannot exceed 10 MB." 

## Reference Image
![IMG_81CD9D7B96D9-1.jpeg](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/3c097dbe-9b00-4ecd-9213-d462e2037c89)
**Old attachment copy** 
![IMG_B420B5E0C75C-1.jpeg](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/95b37071-7d45-414c-9895-d8341556de7d)

**Comment by digitalken** [comment]
PASS 7/28/2021 - Looks good.  Closing.
