### ISSUE TITLE
CT Suspension Update: Discovery

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#27266]
DONE: Team understands Suspension flag update and has identified a path forward

* Questions about suspension flag have been collected & answered by EDU
* Areas in CT to deploy solution have been identified

**Comment by amyknox** [comment]
Per Education Service: 

1. We don’t want to go in a direction that posts anything about referring users to their state approving agency.

2. Language along the lines of a caution flag that notes “This schools is currently suspended for not currently meeting approval requirements” will suffice for this request.  This would mitigate the need for a suspense reason or any further detail.  

Further info...

There's no brief guide or document that outlines all possible suspension reasons. 

Any approval criteria called into question after the initial approval has the potential to result in suspension if the school can’t or won’t show evidence of compliance.  It can apply to single programs or the entire school.  These issues would be handled by the SAA or VA when serving as SAA (in the case of federal programs or when no SAA agreement is in place).

VA can also suspend programs or schools for failure to correct reporting errors (that result in payment issues) or if the SAA fails to correct approval criteria deficiencies.  This is very common when the 85/15 ratio is exceeded (re vet population relative to overall student population).

**Comment by JenLJ** [comment]
From Louise:
Small edit of phrasing.

“This school is currently suspended for not currently meeting approval requirements” will suffice for this request.
 
The word should be “school” not plural “schools”

**Comment by amyknox** [comment]
From Joe P on suspensions

2.21 SUSPENSIONS OR DISCONTINUANCES OF PAYMENTS BY VA
 
           a. VA Rationale. VA may suspend or discontinue payments of education benefits when a school or job training establishment fails to correct reporting requirement errors or if the SAA fails to correct approval criteria deficiencies.
           b. Committee on Educational Allowances. VA may suspend or discontinue payments of education benefits through the Committee on Educational Allowances. See part I, chapter 8 for details.
