### ISSUE TITLE
Update SM Attachment File Size Limits

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27262]
## User Story
As a user, I want to have the same attachment limits for secure messaging within the app and on the website so my experience is consistent. 

## Acceptance Criteria 
* Update attachment file size requirements to support 6mb per individual attachment, and a total of 10mb per message (max number of 4 attachments remains)
* When attaching an attachment to a new/existing message, users can upload attachments with the new limits. 

## Background
MHV increased the attachment file size limits for secure messaging on 7/12/2021

**Comment by narin** [comment]
This work was completed by @jperk51 at some point.  Possibly in a duplicate ticket.
