### ISSUE TITLE
CT Suspension Update: Draft content

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#27267]
DONE: Content for suspension flag update has been drafted 

* Draft content for solution
* Review w UX team 
* Review w Xfunc team

**Comment by amyknox** [comment]
Per Education Service: 

1. We don’t want to go in a direction that posts anything about referring users to their state approving agency.

2. Language along the lines of a caution flag that notes “This schools is currently suspended for not currently meeting approval requirements” will suffice for this request.  This would mitigate the need for a suspense reason or any further detail.  

Further info...

There's no brief guide or document that outlines all possible suspension reasons. 

Any approval criteria called into question after the initial approval has the potential to result in suspension if the school can’t or won’t show evidence of compliance.  It can apply to single programs or the entire school.  These issues would be handled by the SAA or VA when serving as SAA (in the case of federal programs or when no SAA agreement is in place).

VA can also suspend programs or schools for failure to correct reporting errors (that result in payment issues) or if the SAA fails to correct approval criteria deficiencies.  This is very common when the 85/15 ratio is exceeded (re vet population relative to overall student population).

**Comment by amyknox** [comment]
Draft per @JenLJ 

Title: School is suspended
Description: This school does not currently meet the approval criteria for receiving GI Bill funds. The school has 60 days to provide proof of compliance to regain approved status.

**Comment by JenLJ** [comment]
Latest content revision:

Proposed Title: School may not be able to accept new GI Bill students

Proposed Description: This school does not currently meet the approval criteria for receiving GI Bill funds and has been suspended by the VA. The suspension does not impact current students.
