### ISSUE TITLE
[Phase 2] [Research][Backend] Pass disability rating to frontend on 10-10EZ

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#27279]
## User Story

**As an** authenticated veteran, **I want to** have an expedited experience if I qualify, **in order to make** the process more streamlined.

## Acceptance Criteria
- [x] Determine best pattern for 1010ez front end to receive veteran's disability rating.
- [ ] Document in this ticket what data source will be used to check an authenticated Veteran's disability rating

## Notes from front end research:
Info about disability rating in vets-api:
modules/veteran_verification/VETERAN_VERIFICATION.yml
modules/veteran_verification/app/models/veteran_verification/disability_rating.rb
spec/support/schemas_camelized/disability_rating_response.json
lib/evss/common_service.rb

public api looks like this:
```
{
  "data": {
    "id": "0",
    "type": "disability_ratings",
    "attributes": {
      "combined_disability_rating": 30,
      "combined_effective_date": "2015-02-01T00:00:00+00:00",
      "legal_effective_date": "2015-01-01T00:00:00+00:00",
      "individual_ratings": [
        {
          "decision": "Service Connected",
          "effective_date": "2015-01-01T00:00:00.000+00:00",
          "rating_percentage": 30
        }
      ]
    }
  }
}
```

**Comment by dnalbach** [comment]
More notes and information about how to expand the `in_progress_forms` model for the `1010ez` are in this ticket:
https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/27278

The 526 uses a disability rating that is a little different than the files and response structure that Dat mentions in the description of this ticket. It is using the EVSS Form526 RatedDisabilities API which is different than the BGS Veteran Verification service. 

Both have similar types of data, though there are differences in the data structure and fields. The combined rating fields are exclusively in the BGS Veteran Verification service, which is not currently used with any of the `in_progress_forms`.

**Comment by SKasimow** [comment]
@jchilders - to complete this ticket, can you provide what source will be used to check for a Veteran's disability rating? I'll then use that to open a ticket to do the actual work (in another sprint).

**Comment by SKasimow** [comment]
@jchilders - need your comments on what work was done to day and why incomplete.

**Comment by SKasimow** [comment]
rolling over to sprint 67

**Comment by SKasimow** [comment]
Hi @lihanli - we need to determine where we can pull in a Veterans disability rating. It sounds like we can get this thru VETS- api (public API) but can you review this (and related ticket in comments above) and let me know if that is correct or if there is another source we should use for this? We're working on a "Short-forms" init and disability rating will be key to bypassing portion of the application form.

Thanks,

-S

**Comment by SKasimow** [comment]
@lihanli Just saw a doc with info below; could you tell me what the difference is between what you provided in comment above vs info below? Thanks!

EVSS
View my rated disabilities
o	Static landing page: https://www.va.gov/disability/view-disability-rating/
o	View disability rating: https://www.va.gov/disability/view-disability-rating/rating
