### ISSUE TITLE
[Variant Test] missing no address alert

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27276]
## Summary
When a user chooses to sort by home address, but doesn't have an address on file, facilities are sorted alphabetically. There is no message to indicate this (similar to blocked location).
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/a3796a3d-057a-4bfe-a8e4-e0997412f317)

## Specs
- Device: Mac
- Browser: Chrome Version 91.0.4472.114

## Steps to Reproduce
**Test User:** Judy, or any user that doesn't have home address in profile

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Click Start scheduling
3. Select primary care
4. From Sort Facilities dropdown, choose By your home address

### Actual Result
No message indicating list is sorted alphabetically

### Desired Result
- If user does not have address on file, Then default sort alphabetically
- If user selects sort by address AND doesn't have an address on file, Then display message

**_If there isn't an existing pattern for this kind of message and copy is needed, let Product know._**

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made

**Comment by laurenernest** [comment]
@outerpress The "by home address" option is no longer in the dropdown for this scenario. Can you confirm that's the latest intended experience?

![Screen Shot 2021-07-20 at 1.19.46 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8a1d4217-7c2a-4ec5-aa84-dcc9ec08db4f)

**Comment by outerpress** [comment]
@laurenernest yep, that's the intended experience.

Context if needed: we don't have a great way of adding the "missing address" messaging within the dropdown itself, so I just went with not showing it as an option. Another path would be leaving the "Home address" option in and showing an alert when it was selected; that would be more likely to grab their attention, but not as easy to scan, and potentially a bit frustrating.

**Comment by laurenernest** [comment]
Sounds good! Thanks for confirming!
