### ISSUE TITLE
[Research] [Backend] Additional fields to prefill on 10-10EZ

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#27278]
## User Story

**As an** authenticated veteran, **I want to** have more information pre-populated into the online 10-10EZ form, **in order to make** the process more streamlined and accurate.

## Issue Description
Branching off of front-end research into 1010ez prefill data, investigate if additional fields can be prefilled.

### Possible spouse info, needs further research by backend engineer:
app/models/form_profiles/va_21686c.rb
maritalStatus
spouseGrossIncome
spouseNetIncome
spouseOtherIncome
spouseFullName
spouseSocialSecurityNumber
spouseDateOfBirth
dateOfMarriage
sameAddress
cohabitedLastYear
provideSupportLastYear
spouseAddress
spousePhone

### Other fields I couldn't track down:
mothersMaidenName
cityOfBirth
stateOfBirth
sEssentialAcaCoverage
vaMedicalFacility
isSpanishHispanicLatino
isAmericanIndianOrAlaskanNative
isBlackOrAfricanAmerican
isNativeHawaiianOrOtherPacificIslander
isAsian
isWhite
mobilePhone
discloseFinancialInformation
dependents
veteranGrossIncome
veteranNetIncome
veteranOtherIncome
deductibleMedicalExpenses
deductibleFuneralExpenses
deductibleEducationExpenses
isCoveredByHealthInsurance
providers
isMedicaidEligible
isEnrolledMedicarePartA
medicarePartAEffectiveDate
purpleHeartRecipient
isFormerPow
disabledInLineOfDuty
vietnamService
exposedToRadiation
radiumTreatments
campLejeune

### UI Fields, dont need to prefill:
wantsInitialVaContact
privacyAgreementAccepted
veteranHomeAddress // The mailing address is already prefilled

**Comment by dnalbach** [comment]
Upon starting the form for the first time or resuming it, an API call is made to:
```
https://<server>/v0/in_progress_forms/1010ez
```

The payload of this response has two main fields: `formData` and `metadata`.

The `formData` object contains a nested set of basic veteran profile fields, which are different per form type. The `metadata` fields are limited and generally the same across all form types.

The `formData` field differences appear to be determined by the `FormProfile` models. For example, the `VA1010ez` model is empty except for metadata, and therefore contains only the basic veteran profile fields. However, when looking at a more complex form model like the `VA526ez`, we see a variety of other fields being added to the model via Virtus models populated by EVSS calls.

Early experiments show that it is possible to add those same data fields into the `VA1010ez` model by adding similar Virtus model classes. By using the 526 as an example, I was able to add the same disability fields it had to the 1010EZ.

It is important to note that adding attributes to the form class does require adding mapping entries to the form's YAML file in the `config/form_profile_mappings/<form_id>.yml` file. Otherwise the data will have been gathered but not exposed in the return payload.

**Comment by dnalbach** [comment]
While spiking integration of different data sources to the 1010EZ form model today, the EVSS/PCIUAddress reported back a 503 status with an outage message. 

This is a good reminder that the more services we integrate, the higher the chance that one of them is broken or down at any given time. We may need to have a plan for how to handle outages, especially for just one service or object out of many.

**Comment by dnalbach** [comment]
The real question I have now is what fields are available from which services, and how many of the possible fields in our schema we will potentially have available from these services. It will take some time and digging to compare the two.

**Comment by dnalbach** [comment]
This is a sample data payload from betamocks with all fake data utilizing five of the existing, available, data services for the in-progress-form: 

- contactInformation
- identityInformation
- militaryInformation
- ratedDisabilitiesInformation
- veteranContactInformation


```
{
    "formData": {
        "contactInformation": {
            "homePhone": "14445551212",
            "usPhone": "4445551212",
            "email": "test2@test1.net"
        },
        "identityInformation": {
            "fullName": {
                "first": "XXXX",
                "middle": "Y",
                "last": "ZZZZZZZZZZ"
            },
            "dateOfBirth": "XXXX-YY-ZZ",
            "gender": "M",
            "ssn": "XXXYYZZZZ"
        },
        "militaryInformation": {
            "lastServiceBranch": "Air Force",
            "hcaLastServiceBranch": "air force",
            "lastEntryDate": "2001-03-21",
            "lastDischargeDate": "2014-07-21",
            "dischargeType": "honorable",
            "postNov111998Combat": true,
            "compensableVAServiceConnected": true,
            "toursOfDuty": [
                {
                    "serviceBranch": "Air Force",
                    "dateRange": {
                        "from": "2001-03-21",
                        "to": "2014-07-21"
                    }
                }
            ],
            "vaCompensationType": "lowDisability",
            "serviceBranches": [
                "F"
            ],
            "servicePeriods": [
                {
                    "serviceBranch": "Air Force",
                    "dateRange": {
                        "from": "2001-03-21",
                        "to": "2014-07-21"
                    }
                }
            ],
            "guardReserveServiceHistory": [
                {
                    "from": "2007-05-22",
                    "to": "2008-06-05"
                }
            ],
            "latestGuardReserveServicePeriod": {
                "from": "2007-05-22",
                "to": "2008-06-05"
            }
        },
        "ratedDisabiltiesInformation": {
            "ratedDisabilities": [
                {
                    "name": "Diabetes mellitus0",
                    "ratedDisabilityId": "0",
                    "ratingDecisionId": "63655",
                    "diagnosticCode": 5238,
                    "decisionCode": "SVCCONNCTED",
                    "decisionText": "Service Connected",
                    "ratingPercentage": 100
                },
                {
                    "name": "Diabetes mellitus1",
                    "ratedDisabilityId": "1",
                    "ratingDecisionId": "63655",
                    "diagnosticCode": 5238,
                    "decisionCode": "SVCCONNCTED",
                    "decisionText": "Service Connected",
                    "ratingPercentage": 100
                }
            ]
        },
        "veteranContactInformation": {
            "veteran": {
                "mailingAddress": {
                    "country": "USA",
                    "city": "APO",
                    "state": "AE",
                    "zipCode": "00000",
                    "addressLine1": "123 MAIN ST",
                    "addressLine2": "BEN FRANKLIN VILLAGE"
                },
                "primaryPhone": "4445551212",
                "emailAddress": "test2@test1.net"
            }
        }
    },
    "metadata": {
        "version": 0,
        "prefill": true,
        "returnUrl": "/veteran-information/personal-information"
    }
}
```
Additional data may be available through other VA services that are not currently coded to be part of the in-progress-form system. Adding additional services would involve more effort and testing.
