### ISSUE TITLE
[Variant Test] dropdown selection incorrect when default alpha

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27275]
## Summary
When a user doesn't have an address on file and the default facilities sorting is alphabetical, the selection in the Sort facilities dropdown is by your home address.

## Specs
- Device: Mac
- Browser: Chrome Version 91.0.4472.114

## Steps to Reproduce
**Test User:** Judy, or any user that doesn't have home address in profile

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Click Start scheduling
3. Select primary care

### Actual Result
Facilities are sorted alphabetically, but dropdown says "by your home address"
![27275 example.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f9dbbd57-d314-4274-90b9-148f1d42e7fd)

### Desired Result
- Facilities are sorted alphabetically and dropdown says "Alphabetically"
- Dropdown label matches the list sort

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made

**Comment by jbalboni** [comment]
Fixed with #26106

**Comment by laurenernest** [comment]
confirmed the dropdown label matches the default sort. closing ticket.
