### ISSUE TITLE
[VAMC-Scaffolds] Return and Clone Leadership pages for VISN-20 and VISN-9 Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#27285]
## Story
As a Web editor, the new leadership page has to be cloned and scaffold, so I can validate the correct leadership profiles for our system.

## TASK
- [x] Return to Systems in VISN without Leadership page and clone pages from SOT.

## Acceptance Criteria
- [x] All VISN-20 and VISN-9 already cloned now have leadership pages with correct information (Leadership profiles)

**Comment by ltrombley** [comment]
Updated for VISN-20 & VISN-9 which are the VISNs we held off on cloning the Leadership pages

**Comment by ltrombley** [comment]
Task #27285 - Return and Clone Leadership pages for VISN-20 and VISN-9 Systems [BA] - is Complete and moved to Validate
