### ISSUE TITLE
Photos on VAMC Stories appear grainy

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-team#27280]
[transferred from va.gov-cms repo]

**Describe the defect**
After a user uploads their photo to a node and publishes the node it loses resolution.  

**To Reproduce**
Visit  https://www.va.gov/eastern-colorado-health-care/stories/new-telerehab-program-empowers-veterans-at-home/

The resolution is worse than Teamsite found here https://www.denver.va.gov/DENVER/features/New_Telerehab_program_empowers_Veterans_at_home.asp

**Expected behavior**

Images are not pixelated on VA.gov

**Additional context**
From Kevin's comment: 
 The FE should be using 2_1_large not 2_1_medium_thumbnail
https://prod.cms.va.gov/sites/default/files/styles/2_1_large/public/2021-06/MaggieJeanBaptiste.jpg not
https://prod.cms.va.gov/sites/default/files/styles/2_1_medium_thumbnail/public/2021-06/MaggieJeanBaptiste.jpg?h=315a0b06

## Dev Notes
Limited to photos on stories

**Comment by kevwalsh** [comment]
@mmiddaugh  

This is a FE issue, i've transferred it to va.gov-team. The FE should be using `2_1_large` not `2_1_medium_thumbnail`
https://prod.cms.va.gov/sites/default/files/styles/2_1_large/public/2021-06/MaggieJeanBaptiste.jpg not
 https://prod.cms.va.gov/sites/default/files/styles/2_1_medium_thumbnail/public/2021-06/MaggieJeanBaptiste.jpg?h=315a0b06

**Comment by mmiddaugh** [comment]
@kevwalsh @swirtSJW Is this the right way to get the image path with GraphQL?  
`derivative(style: LARGE) {`

from https://github.com/department-of-veterans-affairs/content-build/blob/3a7ce87224240b28d8b4fa58fc15cb55c1dd764b/src/site/stages/build/drupal/graphql/file-fragments/outreachAssets.graphql.js#L40

**Comment by mpelzsherman** [comment]
Use this tugboat environment to validate: https://web-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/eastern-colorado-health-care/stories/

**Comment by mpelzsherman** [comment]
The medium thumbnail crops the images to a 2:1 ratio.

If the image is too small, it will be grainy. That's a CMS user issue.

So we're blocked on this unless we want to relax the cropping requirement.

**Comment by mpelzsherman** [comment]
Large, cropped thumbnails are in prod. Closing.
