### ISSUE TITLE
Support "query flags" in the tome-sync page builder

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2729]
## Problem Statement
We currently query the CMS for "query flags" which we then use to build the GraphQL query. When we switch away from the GraphQL approach, we need to still accommodate these flags.

## Possible implementation
This can probably be done in the filter and transformation functions for each content model.

## Acceptance Criteria
- [ ] Each "query flag" still returned from Drupal is used appropriately in the tome-sync page builder process
- [ ] Building the content from tome-sync has a 1:1 feature parity with the current GraphQL approach

**Comment by ElijahLynn** [comment]
The query flags at https://prod.cms.va.gov/flags_list will still be active and that process should remain the same. This is all in the FE code right @cvalarida? I don't think I need to be assigned this, unless I am missing something.
