### ISSUE TITLE
Establish process for surfacing Sentry issues

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#273]
## User Story
As a VSP team member, I need to know about Sentry issues in a timely manner so that I can address them in a timely manner.

## Goal
When there is a Sentry issue, it is surfaced to the VSP team as quickly as possible.

## Acceptance Criteria
- [ ] Solution for disseminating Sentry issues to team is decided
- [ ] Solution is documented in GH
- [ ] Solution is implemented

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Related: #305
