### ISSUE TITLE
CT Redesign: Create VETTEC "Get started with CareerScope" component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27304]
As a developer, I need to create a "Get started with CareerScope" component for the Comparison Tool VET TEC profile page so that the information can be organized in an effective way and be displayed on the sandbox profile page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is for VET TEC institution types.

## Acceptance Criteria
1. The following content is displayed within the component:

    > CareerScope(R) take career and educational planning to a new level. The proven career assessment and reporting system from the Vocational Research Insitute is a powerful, yet easy-to-use program.
    > 
    > (Chevron Icon) [Get started with CareerScope](https://va.careerscope.net/gibill)

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DJIAGZFF2TW#/screens/296062934)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/19b896f6c02f38b4e00cb14eb8c4f2d24a778fb0/products/education-careers/school-comparison-tool/redesign/design/content-VETTEC.md#get-started-with-careerscope)

**Comment by ksantiagoBAH** [comment]
This story will be covered in the VET TEC frame work story https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27234
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17865

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2017)

**Comment by delli-gatti-michael** [comment]
testing complete
