### ISSUE TITLE
Exploration - Screenreader pronunciation 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27307]
##  Description
The accessibility team identified a level 3 defect that requires some exploration in order to determine what is required to resolve

## Background 

- 408-defect-3 [SCREENREADERS]: Word "veteran" in search suggestions mispronounced and search suggestions are spoken twice #24784

## Steps
- Acquire screen reader
- attempt to replicate 
- investigate screenreader issues on firefox
- discern possible solution (if any)

## Acceptance Criteria
- [x] Understand what is required or how to respond to a11y feedback

**Comment by srsuddath** [comment]
I am sizing this issue as a 5 due to needing to acquire a screen reader in order to even begin testing / replicating this issue

**Comment by srsuddath** [comment]
After doing my research, it is my understanding that we will be unable to fix this issue using the Downshift component, as we will need more granular control of the aria tags and list options.

When we implement our own version of this component we should explore this issue further
