### ISSUE TITLE
CT: Accept "In-State Tuition URL" column in WEAMS file and incorporate into version generation.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27306]
As an Education Team Member, I need the In-State Tuition URL to be loaded from the WEAMS data file so that the update of the information can be automated in place of the current manual process.

## Assumptions:
1. This work is completed in GIDS and does not require a prod / feature flag.
2. This story is to replace the data file InStateTuitionPolicyUrl.

## Acceptance Criteria:
1. A WEAMS file with the new column "In-State Tuition URL" can be uploaded to GIDS without error.
2. The data in the WEAMS file column "In-State Tuition URL" populates the column "in state tuition information" during version generation for the corresponding facility code.

## Supporting Artifacts:
1. [WEAMS file](https://github.com/department-of-veterans-affairs/va.gov-team/files/6816304/WEAMS_School_Data_07122021.csv) with new column

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/845
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/844
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/846

This can be tested on https://github.com/department-of-veterans-affairs/gibct-data-service/pull/846, which contains the changes in the other two.

**Comment by sonntag-adam** [comment]
in staging.
