### ISSUE TITLE
One Pager/ FAQ Documentation: Zenhub, Heroku and Github

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#2731]
Research and gather team feedback to create one pager/FAQ documentation for the Zenhub, Heroku and Github platforms. This documentation will better assist team members in understanding and leveraging these platforms in their work.

- [x] Research platforms and create questionnaire to send to team members for input on what should be included in documentation.
- [x] Draft Zenhub one pager
- [x] Draft Heroku one pager
~~- [ ] Draft Github one pager~~ (previously created; will not duplicate efforts

**Comment by Karak888** [comment]
Hi @lunascoop - here is the PDF that Peggy was pointing you to...
[GitHub_content_process.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3789415/GitHub_content_process.pdf)

**Comment by lunascoop** [comment]
[Heroku FAQ.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3811637/Heroku.FAQ.docx)
@RLHecht Here is the Heroku one pager (well two-pager) for review. Let me know what else should be added.

**Comment by lunascoop** [comment]
[ZenHub FAQ.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3814600/ZenHub.FAQ.docx)

**Comment by RLHecht** [comment]
@lunascoop Here are my edits for the Heroku one-pager. It looks good! I would also have Nick read it over to make sure we have the process correct. That's how I always have gotten to it but it's possible that there's more to it and its purpose.
[Heroku.FAQ-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3814811/Heroku.FAQ-RH-edit.docx)

**Comment by RLHecht** [comment]
@lunascoop Here are my edits for the ZenHub one-pager. Since @Karak888 is the ZenHub guru it might be good to have her read it over as well to see if anything is missing. 
[ZenHub.FAQ-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3814850/ZenHub.FAQ-RH-edit.docx)

**Comment by Karak888** [comment]
oh @RLHecht you gots to be kidding me! Thanks and I will look at it @lunascoop !

**Comment by Karak888** [comment]
looks great @lunascoop !
