### ISSUE TITLE
attr_encrypted key rotation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#27317]
## Issue Description
Our database attrs are encrypted via the attr_encrypted gem. The key used to encrypt the attribute needs to be rotated (probably on a monthly basis, similar to the session key rotation) in an effort to decrease brute force and malicious user based vulnerabilities 

If a malicious actor obtains the value of our db encryption key, they will then have full access to decrypt all the PII and sensitive data that we store in Postgres. 

## Notes:
- It doesn’t appear that we use the same encryption keys for our session encryption vs our database encryption.
- DB Attributes are encrypted via the [db_encryption_key](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L57) found in the settings.yml
- See some of the solutions [here](https://github.com/attr-encrypted/attr_encrypted/issues/109#issuecomment-241950897) for how to migrate and rotate the encryption key

---
## Acceptance Criteria
- [x] Determine how to rotate our keys
- [x] Create docs around rotating key
- [ ] Alerting mechanism that our key is needing rotation (at the ~1 month mark)
- [ ] Determine benchmarking for our PG data in staging

**Comment by LindseySaari** [comment]
There are currently 39 attributes that use attr_encrypted to encrypt. It appears that we can possibly use a rake task or a migration to toggle the keys

**Comment by LindseySaari** [comment]
All instances of attributes except one  utilizing the attr_encrypted gem are database fields. The only instance that is not a database field is [this field](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/covid_research/app/services/covid_research/volunteer/form_crypto_service.rb#L7) on the FormCryptoService. It was introduced in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4745) to add security for the submission/form data arguments when the job is pushed to the Redis queue. 

My only concern is that there could potentially be a brief moment when a job is in the Redis queue, we rotate the encryption keys and when the submission gets decrypted [here](https://github.com/department-of-veterans-affairs/vets-api/blob/e6483de9c146596e5daf49c648ff6936d5bd4023/modules/covid_research/app/workers/covid_research/volunteer/genisis_delivery_job.rb#L18) there will be a decryption error because it was encrypted with the old key. It doesn’t appear that this job runs often, but we may want to be aware of any jobs that are in the queue to be run when rotating the keys. This logic will probably be wrapped into the rake task

**Comment by ericboehs** [comment]
Lindsey is on support rotation so @cbtkc has volunteered to take this to the finish line.

**Comment by LindseySaari** [comment]
@cbtkc I just noticed in the oncall channel that there's an [RDS maintenance window](https://dsva.slack.com/archives/C30LCU8S3/p1628521228027300) that we could piggy back off of possibly if we feel that we need to

**Comment by cbtkc** [comment]
Since this needs to happen on a per-month basis, we could create a "rotate db keys" job that would handle the steps outlined in the documentation, removing the chance for human error.

The job would need to do the following:

- Verify no `GenesisDeliveryJobs` are in queue
- Generate new `db_encryption_key`
- Update parameter store with the new `db_encryption_key`
- Run deployment
- Run database rotation rake task post deploy

**Comment by cbtkc** [comment]
Current `TODOs`

- [ ] Benchmark against staging. Gather how many records are in staging vs prod
- [ ] Define the threat model. It's basically already defined (see comment in the PR) but maybe there's something else i'm not thinking of
- [ ] Test in staging
- [ ] Figure out a prod deploy plan

**Comment by cbtkc** [comment]
Collecting # of records that have encrypted attributes by running the following in the console:

`
ApplicationRecord.descendants.each do |model|
  if !model.encrypted_attributes.empty?
    puts "#{model.name} row count: #{model.all.count}"
  end
end
`

Was going to add this as a rake task, but rake tasks by default do not eager load models, so no descendants will return, (except for the very first one, for whatever reason.)

I will put the totals in another comment.

**Comment by cbtkc** [comment]
**STAGING**

InProgressForm row count: 402
SavedClaim row count: 6229
CentralMailClaim row count: 66
SavedClaim::Burial row count: 33
SavedClaim::DependencyVerificationClaim row count: 7
SavedClaim::EducationCareerCounselingClaim row count: 1
SavedClaim::Pension row count: 25
SavedClaim::EducationBenefits row count: 3692
SavedClaim::EducationBenefits::VA5495 row count: 13
SavedClaim::EducationBenefits::VA0993 row count: 28
SavedClaim::EducationBenefits::VA1990s row count: 2
SavedClaim::EducationBenefits::VA0994 row count: 3370
SavedClaim::EducationBenefits::VA1990n row count: 14
SavedClaim::EducationBenefits::VA1990e row count: 10
SavedClaim::EducationBenefits::VA10203 row count: 145
SavedClaim::EducationBenefits::VA5490 row count: 19
SavedClaim::EducationBenefits::VA1990 row count: 36
SavedClaim::EducationBenefits::VA1995 row count: 55
SavedClaim::CaregiversAssistanceClaim row count: 0
SavedClaim::Ask row count: 0
SavedClaim::DisabilityCompensation row count: 715
SavedClaim::DisabilityCompensation::Form526AllClaim row count: 715
SavedClaim::DependencyClaim row count: 220
SavedClaim::VeteranReadinessEmploymentClaim row count: 1377
Form526Submission row count: 751
FormAttachment row count: 44936
HCAAttachment row count: 98
SupportingEvidenceAttachment row count: 4421
DecisionReviewEvidenceAttachment row count: 38
Form1010cg::Attachment row count: 269
VIC::SupportingDocumentationAttachment row count: 0
VIC::ProfilePhotoAttachment row count: 0
Preneeds::PreneedAttachment row count: 15
AppealSubmission row count: 48
EducationStemAutomatedDecision row count: 35
PersistentAttachment row count: 232
PersistentAttachments::PensionBurial row count: 177
PersistentAttachments::DependencyClaim row count: 55
GibsNotFoundUser row count: 12
AsyncTransaction::Base row count: 3745
AsyncTransaction::Vet360::Base row count: 2847
AsyncTransaction::Vet360::PermissionTransaction row count: 0
AsyncTransaction::Vet360::EmailTransaction row count: 1195
AsyncTransaction::Vet360::TelephoneTransaction row count: 794
AsyncTransaction::Vet360::AddressTransaction row count: 636
AsyncTransaction::Vet360::InitializePersonTransaction row count: 222
AsyncTransaction::VAProfile::Base row count: 892
AsyncTransaction::VAProfile::PermissionTransaction row count: 0
AsyncTransaction::VAProfile::EmailTransaction row count: 133
AsyncTransaction::VAProfile::TelephoneTransaction row count: 344
AsyncTransaction::VAProfile::AddressTransaction row count: 311
AsyncTransaction::VAProfile::InitializePersonTransaction row count: 104
HealthQuest::QuestionnaireResponse row count: 58
ClaimsApi::PowerOfAttorney row count: 9
ClaimsApi::SupportingDocument row count: 0
ClaimsApi::AutoEstablishedClaim row count: 427
AppealsApi::NoticeOfDisagreement row count: 0
AppealsApi::HigherLevelReview row count: 8
Veteran::Service::Representative row count: 16830
CovidVaccine::V0::ExpandedRegistrationSubmission row count: 29
CovidVaccine::V0::RegistrationSubmission row count: 976207

**TOTAL: 1073052**

**PRODUCTION**

InProgressForm row count: 197225
SavedClaim row count: 1084939
CentralMailClaim row count: 6048
SavedClaim::Burial row count: 2386
SavedClaim::DependencyVerificationClaim row count: 0
SavedClaim::EducationCareerCounselingClaim row count: 1487
SavedClaim::Pension row count: 2175
SavedClaim::EducationBenefits row count: 214309
SavedClaim::EducationBenefits::VA5495 row count: 11720
SavedClaim::EducationBenefits::VA0993 row count: 0
SavedClaim::EducationBenefits::VA1990s row count: 3998
SavedClaim::EducationBenefits::VA0994 row count: 4021
SavedClaim::EducationBenefits::VA1990n row count: 572
SavedClaim::EducationBenefits::VA1990e row count: 20444
SavedClaim::EducationBenefits::VA10203 row count: 8171
SavedClaim::EducationBenefits::VA5490 row count: 30191
SavedClaim::EducationBenefits::VA1990 row count: 72586
SavedClaim::EducationBenefits::VA1995 row count: 62606
SavedClaim::CaregiversAssistanceClaim row count: 0
SavedClaim::Ask row count: 0
SavedClaim::DisabilityCompensation row count: 825663
SavedClaim::DisabilityCompensation::Form526AllClaim row count: 825663
SavedClaim::DependencyClaim row count: 385
SavedClaim::VeteranReadinessEmploymentClaim row count: 26919
Form526Submission row count: 799630
FormAttachment row count: 1311712
HCAAttachment row count: 51052
SupportingEvidenceAttachment row count: 1240302
DecisionReviewEvidenceAttachment row count: 2
Form1010cg::Attachment row count: 263
VIC::SupportingDocumentationAttachment row count: 0
VIC::ProfilePhotoAttachment row count: 0
Preneeds::PreneedAttachment row count: 3041
AppealSubmission row count: 16404
EducationStemAutomatedDecision row count: 3345
PersistentAttachment row count: 20643
PersistentAttachments::PensionBurial row count: 20614
PersistentAttachments::DependencyClaim row count: 29
GibsNotFoundUser row count: 4972
AsyncTransaction::Base row count: 215712
AsyncTransaction::Vet360::Base row count: 15659
AsyncTransaction::Vet360::PermissionTransaction row count: 0
AsyncTransaction::Vet360::EmailTransaction row count: 1525
AsyncTransaction::Vet360::TelephoneTransaction row count: 4399
AsyncTransaction::Vet360::AddressTransaction row count: 1469
AsyncTransaction::Vet360::InitializePersonTransaction row count: 8266
AsyncTransaction::VAProfile::Base row count: 200053
AsyncTransaction::VAProfile::PermissionTransaction row count: 0
AsyncTransaction::VAProfile::EmailTransaction row count: 17843
AsyncTransaction::VAProfile::TelephoneTransaction row count: 54305
AsyncTransaction::VAProfile::AddressTransaction row count: 104569
AsyncTransaction::VAProfile::InitializePersonTransaction row count: 23336
HealthQuest::QuestionnaireResponse row count: 2
ClaimsApi::PowerOfAttorney row count: 3
ClaimsApi::SupportingDocument row count: 0
ClaimsApi::AutoEstablishedClaim row count: 129743
AppealsApi::NoticeOfDisagreement row count: 8
AppealsApi::HigherLevelReview row count: 18103
Veteran::Service::Representative row count: 16977
CovidVaccine::V0::ExpandedRegistrationSubmission row count: 54708
CovidVaccine::V0::RegistrationSubmission row count: 1006836

**TOTAL: 8747035**

**Comment by LindseySaari** [comment]
# Progress as of 8/20

On 8/19, the rake task to re-encrypt new records was deployed via git ref to vets-api. As an oversight, the rake task wasn’t wrapped in a transaction and failed mid run. This caused an encryption key mismatch as some attrs were saved with the new encryption key, while others were still encrypted with the old key. 

TLDR; The encryption key mismatch was taken care of manually on a dev instance. With help from Ops, I was able to detach an instance from the ASG and use this to get all the data on the same encryption key. 

The above scenario WILL not happen again because the rake task is now wrapped in a transaction. If one piece fails, it all fails and any ActiveRecord updates will be rolled back. 

Another piece to point out was that while running the rake task, the CPU spiked on the dev ec2 instance, causing the instance to drop.  Dev instances are significantly smaller, so this may only be the case in dev. We will want to think about what this process entails for the future. 

We also may want to think about detaching an instance when re-running this process because if you deploy via git ref, but another change gets merged into master shortly after, the new change will be deployed and your deploy by git ref change will be overwritten by the new deploy


### More issues
**Single Table Inheritance and records that existed before we implemented Inflections**:

We have a model HCAAttachment that inherits from FormAttachment. It used to be called HcaAttachment (lowercase) before we implemented inflections for Zeitwerk mode. I found that there were records in the db BEFORE we implemented the inflection (so the type = HcaAttachment…lowercase). This caused the rake task to throw an error. 

There could be other instances of records that have the same issue, so we will most likely want to create a separate rake task to migrate the data as well come across it. 

## Next steps: Test in Staging
1. SSM into a staging instance and run [this code](https://hackmd.io/wtCQXBBWSqKUadmqjkIASw) to point out any errors
2. If #2 is ok continue, otherwise address the errors
3. Merge in[ this change](https://github.com/department-of-veterans-affairs/devops/pull/9798)
4. Immediately deploy [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7552/files) via [git ref](https://github.com/department-of-veterans-affairs/vets-api/pull/7552/commits http://jenkins.vfs.va.gov/job/build-deploy-vets-api-by-ref/ ) ref: bfe5c7878af8b94dea3ce053d44eb27933fa1fa8
5.  Run the `attr_encrypted:rotate_keys` rake task (either manually or in Jenkins) once the changes are deployed (Pay attention to server and worker in Jenkins)
6. Test a few encrypted records to be sure that the rotation was successful

**Comment by LindseySaari** [comment]
Currently running into a few `ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass` errors for the SavedClaim records

**Comment by LindseySaari** [comment]
This ticket will most likely be closed in favor of migrating to lockbox instead. [Ticket here](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/29612). Keeping this open until we are certain

**Comment by LindseySaari** [comment]
Closing in favor of #29612

**Comment by LindseySaari** [comment]
Closing in favor of #29612
