### ISSUE TITLE
Refactor provider selection field

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#27320]
The ProviderSelectionField component is pretty large and complicated. It would be good to refactor it by breaking it into multiple components and making the different visual states more obvious and scannable.

**Comment by LeKeve** [comment]
Initial refactor merged into master. Second [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28276) created to address larger changes from PR.
