### ISSUE TITLE
[FE] My VA: Clean up My VA 1.0 code post 2.0 launch to 100%

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27326]
## Background
Once we launch My VA 2.0 to 100% of users we need to go back and clean up all code from My VA 1.0. We should proceed this work about a week or so after we go to 100% once we're confident that there isn't a reason we'll need to roll back 2.0.

## Tasks
- [x] Erik and Taylor to discuss what needs to be done here
- [x] Taylor to execute

**Comment by tmitchellgcio** [comment]
ready to be validated possibly by Erik or another person

**Comment by ajakabcin** [comment]
We received a thumbs up from Kevin on proceeding with this, just once we have validation from another dev that the code has been removed we can proceed with this.
