### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#27334]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the `department-of-veterans-affairs/vets.gov-write` org. Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: RudyOnRails
- Reason access is required: A nightly job that sends an email report erred last week and now that the bug is fixed there was a small burst of retries succeeding. In order to communicate to the end user what to expect, I need to view retries and possibly kill some, as they are causing some confusion.

**Comment by jeff2d2** [comment]
Added on 7/14/21
