### ISSUE TITLE
Mobile Appointments NoMethodError

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#27339]
Looks like some production facilities do not have phone numbers and the regex match is returning nil which then later causes a NoMethodError. Sentry event is [here](http://sentry.vfs.va.gov/organizations/vsp/issues/6142/?environment=production&project=3&query=Mobile&statsPeriod=14d).

```NoMethodError: undefined method `[]' for nil:NilClass
  from mobile/v0/adapters/va_facilities.rb:43:in `phone_from_facility'
  from mobile/v0/adapters/va_facilities.rb:17:in `block in map_appointments_to_facilities'
  from mobile/v0/adapters/va_facilities.rb:10:in `map'
  from mobile/v0/adapters/va_facilities.rb:10:in `map_appointments_to_facilities'
  from mobile/v0/appointments/proxy.rb:77:in `get_appointment_facilities'
  from mobile/v0/appointments/proxy.rb:70:in `va_appointments_with_facilities'
  from mobile/v0/appointments/proxy.rb:24:in `get_appointments'```

**Comment by jperk51** [comment]
Saw the same error popping up on this line: https://github.com/department-of-veterans-affairs/vets-api/blob/b41af48b827a1412ccfa3b1c1304ce71a09b55fa/modules/mobile/app/models/mobile/v0/adapters/va_facilities.rb#L15
