### ISSUE TITLE
Create High Fidelity Mockups for prototype

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27342]
##  Description
Create high fidelity designs for usability testing

## Acceptance Criteria
- [x] High Fidelity Designs have been created for all 3 pages (Search Landing Page, Home Page and Search Results Page
- [x] Design Exploration for Search Landing Page as discussed during platform design office hours

**Comment by mgleo** [comment]
Updating with progress (tagging @sshein for awareness)

Homepage with updated search button in header and text below 4 boxes:
![search-homepage.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/bef9e65f-f524-49df-84e5-d4025e2dbcac)

Search landing page with buttons
![search-landing-btn.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/68734dae-a72b-4a4a-82e2-28eee0151e3a)

Search landing page with boxes
![search-landing-boxes.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/a45e8491-ba03-4318-8dbe-c2dc03a295ca)

Search results with buttons
![search-results-btn.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/96cd9a38-d2af-458a-90d2-6800d7932d5a)
Search results with boxes
![search-results-boxes.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/e8544786-2231-416e-8608-4475880c7fae)

**Comment by sshein** [comment]
thanks Megan! looking good. Very interested to see how all this tests

**Comment by denisecoveyduc** [comment]
@mgleo These look great!! Let's plan do discuss them with the team today and I will look for some time with Cindy as well in the future.
