### ISSUE TITLE
Discovery: review libraries/dependencies and recommend upgrades

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#27348]
## Details 

The purpose of this ticket is to investigate what software dependencies should be upgraded in frontend repos. 

This should be done in vets-website, content-build, and vets-json-schema if applicable.

### To Do: 

- [x] Inventory the package.json files in [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json) and [content-build](https://github.com/department-of-veterans-affairs/content-build/blob/master/package.json)
- [x] Document in a spreadsheet what version we are using and what is the latest version
- [x] Verify that the dependency is being used
- [ ] Upgrade one package to the latest version and run the commands associated with that package; document whether the command passes or fails 

### Next steps (will be separate tickets) 

* Based on this info, decide what to upgrade and upgrade

**Comment by jhonnyoddball** [comment]
Tools to be used:

- `npm list`
- `npm ls --production`
- `npm ls --development`
- `npm outdated`
- `yarn why [dependency]`
- `yarn list --depth=0`

**Comment by jhonnyoddball** [comment]
## Inventory the package.json files in vets-website and content-build

The audit can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1x3Qn3N0asy4vSZc-l7XragAPW_Ucdb-CeOYiajlU5fk/edit#gid=2053754634)

**Comment by jhonnyoddball** [comment]
## Possible unused dependencies

Generate a report using [depcheck](https://github.com/depcheck/depcheck)


## vets-website
Running: `depcheck vets-website --ignores='eslint'`

### Unused dependencies
* blob-polyfill
* dotenv
* leaflet-control-geocoder
* react-dropzone
### Unused devDependencies
* @department-of-veterans-affairs/generator-vets-website
* babel-core
* babel-jest
* babel-plugin-react-transform
* cache-loader
* choma
* concurrently
* css-loader
* cypress-multi-reporters
* cypress-testrail-reporter
* docdash
* enhanced-resolve
* extract-text-webpack-plugin
* file-loader
* json2csv
* mocha-junit-reporter
* mocha-snapshots
* null-loader
* polyfill-function-prototype-bind
* postcss-loader
* quick_check
* react-test-renderer
* recursive-uncache
* sass-lint
* sass-loader
* selenium-server
* start-server-and-test
* style-loader
* stylelint-order
* stylelint-scss
* svg-url-loader
* text-loader
* uglify-js
* url-loader
* webpack-cli
* webpack-dev-server
* yeoman-generator

## content-build
Running: `depcheck content-build --ignores='eslint'`

### Unused dependencies
* blob-polyfill
* deep-diff
* dotenv
* jsonschema
* tar-fs
### Unused devDependencies
* ajv
* babel-core
* babel-jest
* babel-loader
* babel-plugin-react-transform
* choma
* cypress-multi-reporters
* eslint-plugin-deprecate
* fuzzy
* inquirer-autocomplete-prompt
* jsonschema
* mocha-junit-reporter
* mocha-snapshots
* nyc
* puppeteer
* sass-lint
* webpack
* webpack-dev-server
* yeoman-generator

**Comment by jhonnyoddball** [comment]
[npm-check](https://www.npmjs.com/package/npm-check) can also be used to find unused dependencies as well as its current versions.

![Screen Shot 2021-07-26 at 1 41 10 PM](https://user-images.githubusercontent.com/55560129/127034319-dbfb5e0f-426e-4c45-a7b6-5994233dcd41.png)

**Comment by jhonnyoddball** [comment]
# Recommendations

Now that the [audit](https://docs.google.com/spreadsheets/d/1x3Qn3N0asy4vSZc-l7XragAPW_Ucdb-CeOYiajlU5fk/edit?usp=sharing) is complete, we can take in consideration the following actions:

## Remove unused dependencies.

The audit contains a column called `USED?`. the `?` represents that the dependency was not found. Those dependencies need to be verified and removed.

## Minor upgrades

These upgrades usually don't affect the existing code and should be prioritized over the major upgrades.

## Major upgrades

These should be the latest since they are the hardest, specially if jumping several versions up.

**Comment by jhonnyoddball** [comment]
After auditing our current dependencies, we will be removing the following unused dependencies:

## vets-website

- [ ] babel-core
- [ ] babel-plugin-react-transform
- [ ] concurrently
- [ ] enhanced-resolve
- [ ] extract-text-webpack-plugin
- [ ] json2csv
- [ ] leaflet-control-geocoder
- [ ] polyfill-function-prototype-bind
- [ ] quick_check
- [ ] react-dropzone
- [ ] react-test-renderer
- [ ] recursive-uncache
- [ ] style-loader
- [ ] text-loader
- [ ] uglify-js


## content-build

- [ ] babel-core
- [ ] babel-loader
- [ ] babel-plugin-react-transform
- [ ] deep-diff
- [ ] fuzzy
- [ ] inquirer-autocomplete-prompt
- [ ] jsonschema
- [ ] puppeteer
- [ ] react-dom
- [ ] yeoman-generator

**Comment by jhonnyoddball** [comment]
## Based on the recommendations above, these are the final decisions:

- **Remove unused dependencies**
All unused dependencies have been removed. Please see above for the [work done](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27348#issuecomment-892902993).

- **Minor upgrades**
A new ticket ([28952](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28952)) was created to keep track of the upgrades

- **Major upgrades**
A new ticket will be create to keep track of the upgrades
