### ISSUE TITLE
Access for Taylor Mitchell

### ISSUE THREAD

**Issue by tmitchellgcio** [department-of-veterans-affairs/va.gov-team#27341]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Taylor Mitchell
- Please Provide your email.
   > taylor.mitchell@gcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > company: Government CIO
      team name: Authenticated Experience

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtzNXcNJPqZW+Zm3hBwRA9DPnCpmqPa0YAbIUjaxphQecI0sNUth8kRHgwWx9At4xpnpwjyjXrwkyLZ+ioZewhVzIr2bQuXSIm/mvUW41v0Cok1ECEQ8UVW205IxUKhYguj7p+kW5Bzr/xlbXH9ShxTrD3SyvRQkjrF1DV4dee3JPbJpsOe1iGzJk1KaHKzAeYX9/qMkb4wv7B5u91pwhUknZNv61k9gshqdZKVy4FLKARweyS1+rcPHKQ1jm64VFcuCwUuGjQyWRcb8za01GofzN3XutQHRk8F3h6Q3FS3y4gJb49deRvRs1aAYyTb4MmX7/vQlTnhcYHA84QxGAF1Z8pqxfmMTXkZQTh9uN8gifJ6OEqr9N6p0k8HzW9ygBJlZXzCefYhwHAKXtfPLb7REdDSTYDaNpLpeqZOYbmffCKXb8TLZfaO+YKJWrW5HGLEh7p55ba+am12/Rk3zLzTf6AcS2XOid7KRfT03n1DslYPoudYxBiXCX6d3SECBM= Taylor@DESKTOP-0CF2BG8
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? I don't think I need this. I haven't heard if I do yet.

**Comment by tskinn** [comment]
@tmitchellgcio your key has been added and you should be able to connect now. Reach out in slack if you have any issues.
