### ISSUE TITLE
Scaffold MCP Wizard

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27346]
## Technical Task

Make file structure outline in [mocks](https://preview.uxpin.com/18073b171729031ac0af64822d31a7427b012d66#/pages/139873794/simulate/sitemap?mode=i) with cards. Expect to update content and URLs in the future.

## Expected Behavior

- Wizard looks like the mocks with base options and routing

## Acceptance Criteria

- [ ] Looks like mocks supplied
- [ ] Routing is set up for display cards
- [ ] Content boxes are assessable to aria-ids to appended boxes

**Comment by LindaLi123** [comment]
Closing this ticket because we wont be creating wizard for MCP. We will be using existing wizard.
