### ISSUE TITLE
CT Redesign: Update search page display on mobile viewports

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27340]
As a developer, I need to update the search page UI of the comparison tool redesign sandbox so that it displays in a user friendly manner on mobile devices.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The "Update tuition and housing estimates" is hidden until a search is executed.
3. The "Filter your results" is hidden until a search is executed.
4. Filter changes in the prototype are out of scope of this story

## Acceptance Criteria:
1. The breakpoint for mobile display is 481px ($small-screen).
2. The search component tabs are displayed as accordions.
3. Only one of the accordions can be expanded at a time.

#### Search by name
4. The contents of the search by name tab are:
    a. displayed when the search by name accordion is expanded.
    b. hidden when the search by name accordion is collapsed.
5. The contents of the search by name tab are stacked vertically in this order:
    a. Free text field
    b. Search button

#### Search by location
6. The contents of the search by location tab are:
    a. displayed when the search by location accordion is expanded.
    b. hidden when the search by location accordion is collapsed.
7. The contents of the search by location tab are stacked vertically in this order:
    a. Use my current location
    b. Free text field
    c. Distance dropdown
    d. Search button

#### Filters
8. The "Update tuition and housing estimates" accordion is displayed as a button.
9. On click of the "Update tuition and housing estimates" button, the component is expanded to take the entire viewport.
10. When the user clicks "Update results", the "Update tuition and housing estimates" component is closed.

11. The "Filter your results" accordion is displayed as a button.
12. On click of the "Filter your results" button, the component is expanded to take the entire viewport.
13. When the user clicks "Update results", the "Filter your results" component is closed.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#)
2. [Breakpoints documentation](https://design.va.gov/design/breakpoints#names-and-values)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17989

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2026)

**Comment by delli-gatti-michael** [comment]
Testing complete
