### ISSUE TITLE
CT Redesign: Add conditional display logic to the ratings functionality.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27359]
As a developer, I need to put the ratings functionality in the sandbox behind the ratings feature flag so that it is not enabled in production when the updated CT is rolled out if the ratings functionality data is not available.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. Ratings information is only displayed in the CT Sandbox in the following locations if an institution has five or more ratings available.
    a. Search results cards
    b. Profile page header
    c. Profile page ratings section

2. On the compare page, if an institution that has 5 or less ratings is compared with an institution that has 5 or more ratings the institution with 5 or less ratings is displayed as if it has no ratings.

3. Ratings information in the CT Sandbox in the following locations is behind the feature flag "gibct_school_ratings".
    a. Search results cards
    b. Compare page
    c. Profile page header
    d. Profile page ratings section

4. When the feature flag is off, the ratings content is not displayed.
5. When the feature flag is on, the ratings content is displayed.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17909

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2019&group_by=cases:section_id&group_order=asc
