### ISSUE TITLE
Establish engineering requirements for typeahead drop down component

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27353]
This ticket is to capture our proposed list of features / implementation decisions for the search and discovery typeahead dropdown component.

## Implementation Decisions
- We have decided to implement this feature as a component within the search application. This will allow us to tailopr this component to meet our specific needs, rather than to prematurely focus on generalizing and over-emphasizing reuse. Our intention is to create a component that another team would be able to leverage as a 90% solution.

## Functionality
- The dropdown menu shall not display any "suggestions" when a user has not entered any input
- the dropdown menu shall display suggestions after a user has finished typing a potential query (debounce the "fetch suggestions" call 200ms after a user finishes typing)
- The dropdown menu shall accept a prop function to call to fetch suggestions. This function shall:
     - have a single parameter (the user's query)
     - return an array of strings (the list of items for the dropdown menu)
- The dropdown menu shall be keyboard navigable with with following functionality:
     - pressing the up and down arrow keys will navigate through the suggestions
     - pressing the down key on the last suggestion will wrap to the top suggestion, and pressing the up key on the top suggestion will wrap to the last suggestion
     - pressing the enter key while focusing a suggestion will populate the input field with it
     - pressing the enter key while focusing the input field will initiate its submit functionality
     - pressing the enter key or space key while focusing the fields "button" will initiate its submit functionality
- the dropdown menu shall accept an onSubmit function as a prop. This function shall:
     - accept a single parameter (the user's query)
     - this function should be defined in the component so as to leverage any relevant state data - suggestions lists - pathname, etc

**Comment by srsuddath** [comment]
The following patterns have been provided by accessibility, which will help us meet our goals moving forward:

The first is a editable combobox that has been specifically tested for accessibility uses (and could be leveraged for our custom component)
https://github.com/microsoft/sonder-ui/tree/master/src/components/combobox

and the second is a powerpoint detailing accessibility's thoughts on typeahead
https://docs.google.com/presentation/d/1JSN9Bd7-4yOl8hVZS3zEhHuDxI3DMAYzZLCXYz9fMfs/edit?usp=sharing
