### ISSUE TITLE
General Analytics Request for Public Websites Team 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27364]
# General Analytics Request

## What this form is for

Use this template to request support for analytics that need interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Public Website Team - Campaign Landing Pages 
- I'm looking to pull recent dashboard data for all three campaign landing pages that have launched in an effort to share with details with stakeholders.  
- Looking to replicate the below [CLP/Trust dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/J-aJKanqTnmCDZh5UP9UlA/a50123418w177519031p176188361/_u.date00=20210601&_u.date01=20210713/) for all CLP pages.

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data, link to this Github issue, and tag `@platform-analytics`._
    
- Public Website Team - Product is Campaign Landing Pages (CLP)

    
- What type of analytics support are you looking for?
  - [X] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [X] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
- Would ideally be soon as possible but would ideally like it by Friday, July 16, 2021?

## Analytics to Track Down
Looking to replicate dashboard and details: [CLP/Trust dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/J-aJKanqTnmCDZh5UP9UlA/a50123418w177519031p176188361/_u.date00=20210601&_u.date01=20210713/) for all CLP pages.

Here are the URLs for the needed CLP Datasets: 

CLP/Vaccine
Redirect URL: http://va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine |  
-- | --
Vanity URL: http://va.gov/covid-vaccine-questions

CLP/Pride
Redirect URL | Redirect Destination
-- | --
https://www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month/ | http://va.gov/pride-month

## Other Helpful Questions to think through
- Who is your audience? Stakeholders / Related Products 
- Why do you need this data? Impact Measuring 
- What are you hoping to find? Traffic Data associated with Product

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks for opening this ticket, @brianalloyd ! Would you be able to attend our office hours tomorrow, 7/15 12:30-1pm ET? We can coach you how to set up your GA dashboards there. Thanks!

**Comment by brianalloyd** [comment]
@joanneesteban unfortunately not, I have a team retro during that time.  Any chance you have office hours on Friday that I could join?

**Comment by bsmartin-ep** [comment]
@brianalloyd -

Is this dashboard set to "Shared"?

https://analytics.google.com/analytics/web/?authuser=0#/dashboard/J-aJKanqTnmCDZh5UP9UlA/a50123418w177519031p176188361/_u.date00=20210601&_u.date01=20210713/

I'm getting a permissions error.    To share...

![image](https://user-images.githubusercontent.com/62304138/125720807-4e5ca63b-3053-44be-8d00-38af75b4bd53.png)

**Comment by brianalloyd** [comment]
@bsmartin-ep I believe so, think you our John W. might have created for us initially.  Here's a share link: https://analytics.google.com/analytics/web/template?uid=7upyOw24TmibU2eGiVk87A

**Comment by bsmartin-ep** [comment]
@brianalloyd - 

Do you want a separate dashboard for each CLP or use one dashboard for all of them?

If the former...

GA doesn't have a direct way to copy a dashboard.  But you can use that template link to re-import the dashboard under a different name.  Then just change the filtering on each widget to the new URL...

![image](https://user-images.githubusercontent.com/62304138/125883082-9cb66d09-0a11-485f-8d92-aa884c78c5d1.png)

And if you want these to be available to anyone on the view (vs private), you can use the share link I screenshotted above.

**Comment by brianalloyd** [comment]
@bsmartin-ep thanks for the follow up, would like them separate if possible and yes they can be available to anyone to view.

**Comment by bsmartin-ep** [comment]
Content KPI dashboard now has CLP pages.  Confirmed with Brian this is OK to close.
