### ISSUE TITLE
DISCOVERY | CMS Sandbox | Content Relationship in Drupal for Lang Attribute

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27365]
## Story

Per our meeting with CMS on 6/16, there was an agreement that any content relationships should live in Drupal. Since that isn't currently feasible, we'd like to explore the creation of a programmatic workaround that can  be used in the near-term. Ideally, this would make it easier for us to migrate to i18n in the future. 

Some of the options noted include: 

- meta data tags
- naming conventions
- pathways (changing the alias of the page and letting that be the connector for the short term)
- UU IDs

This ticket is for the discovery work necessary to explore each of these possible approaches (and any others not noted above) and identify best path forward.

**Comment by mchelen-gov** [comment]
is it possible to use node reference fields?

**Comment by SKasimow** [comment]
Hi Mike - so funny that you commented on this! I was just pinging you to see if we can grab a few minutes with you tomo as Adam (our new FE) and I have some questions on testing translations in the CMS sandbox. We're meeting with Neil H but not until he is back from PTO on Monday and wanted to start some work before then.

**Comment by SKasimow** [comment]
Closing. Dupe to https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27409
