### ISSUE TITLE
[FE] Profile: Implement table styling for screens >768px

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27377]
## Background
As part of the revisions to the "remove" functionality, we need to implement different table styling for when screens are >768 px. This needs to be done before [27169](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27169).

Full documentation for remove functionality [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md).

## Tasks
- [ ] Implement table styling for desktop as outlined in specs [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/remove-info-specs.md#design)

![tables.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/3188aeef-8a93-4fd4-9c80-86b07e46620e)

**Comment by erikphansen** [comment]
@ajakabcin I think I can knock this out super fast so I'll just do it.
