### ISSUE TITLE
Submission failures on 10-10EZ without an email address look like a successful submission

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27378]
## User Story

**As a** veteran, **I want to** know that my submission has failed on the 10-10EZ, **in order to** retry and successfully submit my health care application.

### Background

During research on notifications, we discovered that the 10-10EZ is currently queuing up a Sidekiq job for submission of the form if the user provided an email address. The job will attempt to submit several times, and if successful, nothing visible happens to the user. If it fails repeatedly and exceeds the retry limit, then the user will be sent a failure email to the address provided. This is done via an ActionMailer template that directly sends through Granicus. It does not use the newer, preferred VANotify system. 

However, if the user did not provide an email address, the EZ form submission occurs immediately rather than through a Sidekiq job, and there are no retry attempts. The front-end client always receives a success response from the vets-api regardless of the success/error response from the Enrollment System upon submission.

The net result is that veterans that did not provide an email address will be shown a Confirmation screen even though their submission failed. They will believe their submission was successful even though it was never received.

### Potential Fixes
For the long-term, we may need to re-evaluate this logic and also change the mechanism for sending the Error Email to use a method preferred by the VANotify team.

## Expected Behavior

Veterans need to be notified of submission failures.

**Comment by dnalbach** [comment]
The 1010EZ controller calls a process action on the HealthCareApplication model that performs an immediate synchronous submit of the application to the Enrollment System using the `HCA::Service` client calling its `.submit_form` method if the user did not provide an email address. The HCA service client appears to be hardcoded to return success as seen in this `submit_form` method:

```
    # lib/hca/service.rb
    def submit_form(form)
      formatted = HCA::EnrollmentSystem.veteran_to_save_submit_form(form, @user_identifier)
      content = Gyoku.xml(formatted)
      submission = soap.build_request(:save_submit_form, message: content)
      response = perform(:post, '', submission.body)
      root = response.body.locate('S:Envelope/S:Body/submitFormResponse').first
      {
        success: true,
        formSubmissionId: root.locate('formSubmissionId').first.text.to_i,
        timestamp: root.locate('timeStamp').first&.text || Time.now.getlocal.to_s
      }
    end
```

Note how the `success: true` line of the final response hash is hardcoded and is not conditional or pulled from the response body. I also checked and the `perform` method of the base client does not appear to have any retry logic in it, rather it looks like a single, one-time send operation. Therefore I can only conclude that this `submit_form` method **appears to always return a successful response object** back up the invocation chain to the controller, where this object is provided to the endpoint caller (front-end client) as the JSON payload for the form submission.

This could be changed to show conditional success or failure based on the actual ES response. We must be aware however that this is a shared library service client, and any changes to it will impact all consumers of the service client. Quick research appears to only show the HCA Sidekiq jobs sharing the HCA service client, but a more thorough investigation would be advised. Any service client changes would also require verification of the Sidekiq job behavior.

**Comment by dat-gcio** [comment]
@tchrisdyer Regarding tickets to make the email field required:
1) vets-website (front-end) (3 points to make required, and make sure previous in progress forms still function)
2) vets-json-schema change (2 points)
3) vets-api (backend) (Whatever point @dnalbach  deems)
4) add feature toggle (2 points)

If you wanted to add this under a feature toggle for 50%, then we do not need to do 2 and 3, until we go to 100%.
If you just want to make it required then we only need to do 1, 2 and 3.

**Comment by SKasimow** [comment]
Discussed adding "Preferred Contact Method" info and how and why we need contact info.

**Comment by markfallows** [comment]
Lihan will need to investigate when we are ready to take up the work.
