### ISSUE TITLE
[FE] My VA: Remove feature flag code for My VA 2.0

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#27379]
## Background
As part of the code cleanup of My VA (#27326) post launch to 100%, we need to remove the feature flag code since it's available to all users.

We should do this mid-sprint after My VA 2.0 has been live to all users for a few days so that we can make sure there isn't a reason to roll back.

## Tasks
- [x] Remove feature flag code
- [x] Test

**Comment by tmitchellgcio** [comment]
ready to be validated possibly by Erik or another person

**Comment by ajakabcin** [comment]
We received a thumbs up from Kevin on proceeding with this, just once we have validation from another dev that the code has been removed we can proceed with this.

**Comment by ajakabcin** [comment]
Confirmed and merged
