### ISSUE TITLE
EVSS - Veteran must have DOB

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#27374]
What we know: 
 EVSS  requires that we send the veteran's date of birth in a header for form 526 submissions. There's no point in a veteran starting an application only for EVSS to reject it on submission.  We have the birthday for most but not all identity-verified veterans.

# back end:
the [access_form526?](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/evss_policy.rb) method should check for veteran's Date of Birth. `user.birth_date`
# Front end: 
Is this still the appropriate message for someone who is missing a birthday?

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/containers/MissingServices.jsx#L26

# open questions
In the validation doc there’s a VAAFI header requirements section. Are these header requirements the same for all EVSS services VA.gov calls?  I’m asking in this case because va_eauth_birthdate Cannot be Null isn’t something we’re checking for.  We have birth date nearly all the time but not 100%. [asked in evss channel](https://dsva.slack.com/archives/C1VBAHWQL/p1626464170052700)

**Comment by annaswims** [comment]
@michelpmcdonald - depending what EVSS answers, we may also want to add a check for user.birth_date in all of the `EVSSPolicy` checks

**Comment by annaswims** [comment]
DOB is not required for letter generator, claim status, and reference data. All other EVSS APIs need DOB.

**Comment by Mottie** [comment]
> Is this still the appropriate message for someone who is missing a birthday?

I don't see DOB as one of the "downtime" services - https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/DowntimeNotification/config/externalServices.js

Maybe we need to add a specific error message asking for their DOB, but I think the only way you can "officially" update it to tell the Veteran to call their regional office (ref: profile page). Maybe we need to include a DOB input if it's missing and indicate that it will only apply to their current form?

**Comment by Mottie** [comment]
Fix merged in with placeholder content

**Comment by annaswims** [comment]
complete
