### ISSUE TITLE
STEM AD: Add GA to "View Details" action link

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27376]
As a developer, I need to add google analytics tracking to the view details action link so that we can understand how users are interacting with the information.

## Assumptions:
1. The link where the automated denial cards are displayed: https://staging.va.gov/track-claims/your-claims

## Acceptance Criteria:
1. The card "View detail" link fires the following event:

The links in the more resources section are tracked using:

```
'event': 'cta-action-link-click', 
'action-link-type': 'primary', // or 'secondary', 'reverse' --- i.e click class of 'vads-c-action-link--blue' = 'secondary' ... based on name of action link button used from css class
'action-link-click-label': //click label for action link, 'View details'
'action-link-icon-color': //name of color from class, i.e 'blue'
'claim-type': //'Dependency', 'STEM Scholarship'
'claim-last-updated-date': //date claim was last updated on
'claim-submitted-date': //date claim was submitted on
'claim-status': //i.e 'Denied', 'Claim received'
```

## Supporting Artifacts:
1. [Originating story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21747#issuecomment-828577740)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18195
