### ISSUE TITLE
[Research] Prototype out caregiver facility search

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#27375]
### Description

Initial research and prototyping of the caregiver support coordinator facilities search and selector.

**Comment by Dene-human** [comment]
Design and most current text: [PDF](https://app.zenhub.com/files/133843125/9bb45a1e-7cc3-4880-9fe5-fbfe7537e994/download)



**Specs**
- When user lands on page, results should be automatically generated based on Veteran's home address input in form

- Hint text below input should appear until user inputs something different in field and presses Search button

- Reference for search interaction: [https://staging.va.gov/find-locations](https://staging.va.gov/find-locations)

- I need to work with you on the "miles filter" to define the mile breakdowns and dropdown design
     - We also need to understand how this will work with longer text aka if user searches city + state
     - We need to define this on mobile

- List should be ordered by miles away- displaying closest first

- "Get directions" open new tab to Google maps

- Pagination to load more results should use [VAOS as reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request_flow.md)

- More info component should appear before user clicks on "+X more locations" 
     - Text: Caregiver Support Program Staff are only located at certain VA health facilities. The list includes only these 
                  facilities.

- After user clicks on "+X more locations" the "Why isn't my VA facility listed?" text should appear at bottom. _See PDF page 2_


Note: This likely won't affect the 10-10CG, but when implementing the 10-10EZ, we may need to define how many results are shown at a time (pagination) if the number is large.

**Comment by Dene-human** [comment]
@dat-gcio Please note that i updated the above with a V2 design based on A11y feedback that i received from Josh and Angela. I think it is likely that we will use something similar to this version.

**Comment by dat-gcio** [comment]
Getting facilities looks something like so:
v1/facilities/va?bbox[]=-83.2084&bbox[]=27.1978&bbox[]=-81.7084&bbox[]=28.6978&type=health&services[]=CaregiverSupport&page=1&per_page=20&radius=35&latitude=27.9478&longitude=-82.4584

Or:
facilities_api/v1/va?bbox[]=-83.2084&bbox[]=27.1978&bbox[]=-81.7084&bbox[]=28.6978&type=health&services[]=CaregiverSupport&page=1&per_page=20&radius=35&latitude=27.9478&longitude=-82.4584

Getting the coordinates (taken from vaos):
const mapboxToken = ‘xxxxxxxxxxxxxxxxxxxxxx;
const mapboxClient = new MapboxClient({ accessToken: mapboxToken });
const mbxClient = mbxGeo(mapboxClient);
mbxClient
      .forwardGeocode({
        types: location.match(/^\s*\d{5}\s*$/) ? ['postcode'] : TypeList,
        autocomplete: true,
        query: location,
        limit: 6,
      })
      .send()
      .then(({ body: { features } }) => {
        dispatch({ type: LOCATION_AUTOCOMPLETE_SUCCEEDED, payload: features });
      })
      .catch(err => {
        dispatch({
          type: AUTOCOMPLETE_FAILED,
          payload: err.message,
        });
      });

**Comment by dat-gcio** [comment]
@tchrisdyer Tested the facility api endpoint and I can get locations from Florida to California, so we can definitely go up to 500 mile radius.

**Comment by dat-gcio** [comment]
Closing this out. The rest of the work to be completed in the implementation ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/26246
