### ISSUE TITLE
EVSS headers - veteran first and last name

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#27394]
As part of the epic[ reviewing validators for form 526 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27069
)we learned that not all names are accepted by EVSS or its upstream partners.  In addition to the validation rules provided by EVSS,[ we learned that accented characters are not accepted](
https://dsva.slack.com/archives/C1VBAHWQL/p1626290118045600). 

## Validation rules from EVSS:
[va_eauth_firstName](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/auth_headers.rb#L23) & va_eauth_lastName
  Cannot be Null
  Must have <= 30 characters, no quotes (single or double)

## Questions to answer:

- How many veterans had applications rejected, due to their name?
- How might we remedy improperly rejected applications?
- How do we move forward?  Ideally, all VA systems would accept any veteran's name. Can we affect that sort of change?  If not then what?
  - If a veteran named `José O'Groß 2nd` files an application is there a way that we could modify the name so that could be accepted by BGS/VBMS? Would would `Jose OGross nd` work? (`é `-> `e`, `ß`-> `ss`,  remove apostrophe and number).
- Do we have the same standards any time we send a name in a header to EVSS, or does it differ depending on which services EVSS calls?
- Aside from form 526, what other apps might be affected?

**Comment by annaswims** [comment]
> EVSS uses the first/middle/last name in the request headers from VA.gov to populate the VBMS establishClaim request. We don't alter the name, so if it contains a single quote we pass that on to VBMS where it causes an error. To confirm this, I just submitted a claim for Miriam O'Richardson in the lowers. The EVSS response contained this error message: Claim not established. System error with BGS.
> The VBMS response has some additional information: An error occurred while establishing the claim: Unable to establish claim: insertBenefitClaim: LastName has invalid character(s)

**Comment by annaswims** [comment]
will fix the error in https://github.com/department-of-veterans-affairs/va.gov-team/issues/9903

**Comment by annaswims** [comment]
**How many veterans had applications rejected, due to their name?**

3347 veterans have has their applications rejected with `form526.submit.establishClaim.serviceErrorClaim not established. System error with BGS.` of those, 62 had a character in their name that we now know is not allowed.

some names like `Florez` and `Jose`  that typically/frequently have accents were on that list.   So, perhaps even the mismatch is causing problems.

**Comment by annaswims** [comment]
Michael Harlow says:
> I think VA.gov should continue to pass special characters to EVSS so the name appears correctly on the generated 526 PDF. Then EVSS could strip/replace special characters from VBMS requests to comply with corp rules.
and I agree

**Comment by annaswims** [comment]
Closing this, not because it's complete, but because it should be addressed but upstream systems.

**Comment by annaswims** [comment]
https://dsva.slack.com/archives/CSFV4QTKN/p1626385071279100?thread_ts=1626380593.274700&cid=CSFV4QTKN Identity team may follow up with Corpdb.

**Comment by annaswims** [comment]
I'm going to re-open for tracking purposes.  We really need someone to fix this.

**Comment by annaswims** [comment]
even if we strip characters that aren't accepted by VBMS the claim will still be rejected if the character is in VBMS.

**Comment by drorva** [comment]
Just to be clear. Here's the pipeline and capabilities:
* va.gov -- accepts special characters
* EVSS -- does
* VBMS -- does not
* corpdb -- does
How does the PDF fit in with the above?

**Comment by annaswims** [comment]
VA.gov sends form526 data to EVSS. Evss fills a pdf and puts it in the VBMS e-folder, but also makes other API calls to VBMS.  I think something about the API call fails.   Just curious, where did you learn that corpdb does accept special characters? I thought we didn't know if corpdb accepts special characters.

I found this comment in slack from a couple months ago, so maybe it's on EVSS' plate soon
https://dsva.slack.com/archives/C1VBAHWQL/p1626701554053600?thread_ts=1626290118.045600&cid=C1VBAHWQL
> Thanks all. EVSS is tracking this now in Jira as EVSS-9625. Will discuss with Melissa Rebstock and then reach out to VBMS and BGS to explore how we can improve the situation.

The names aren't even that unusual. Got a support request form someone this week whose name had `Jr.` in it so it was rejected because of the `.`

**Comment by drorva** [comment]
I probably misunderstood one of the conversations that corpdb accepts special characters. 
Who owns this problem at this point, and do we have an idea of how many vets are affected?

**Comment by annaswims** [comment]
It's hard to put a number on it because EVSS gives us a vague error message back that could mean one of many things. `Claim not established. System error with BGS. GUID: d1c7b0c8-93f1-41fa-9f52-36b9ae94b528` they get a detailed message from BGS but don't pass on the details. 
We've seen that error message 274 times in the last year but only 5 times in the last month.  We know that it's still a problem because we had a veteran reach our for support last week.

**Comment by annaswims** [comment]
Names are also an issue for lighthouse who strips characters from names before sending to central mail.  At least in that case we know that the fuzzy match algorithm helps.

**Comment by drorva** [comment]
The numbers are helpful to understand the magnitude. 
Just to double check, if va.gov converted the special characters, would that solve some of the problem? In other words changing Mathéo to Matheo would it make it work? I understand that there are different cases like you mentioned "Jr." (I guess we can strip the '.' too.

**Comment by annaswims** [comment]
In this case, I don't think removing the unapproved characters would help.  We send first & last name to EVSS, but this vet had a  `suffixName = JR.` in corpdb and VA.gov isn't even sending suffixName.

https://dsva.slack.com/archives/C8R3JS8BU/p1631721611018300?thread_ts=1629926344.025600&cid=C8R3JS8BU 

Though there are cases where we do transliterate characters (NOD & HLR) because central mail doesn't accept those characters either and does fuzzy matching.
