### ISSUE TITLE
Detail screen for disability ratings

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#27396]
# User Story
As a user of the app, I want to see my combined disability rating and my individual ratings.

**Note:** Reference staging.va.gov to see ratings (test user +224 has several disability ratings)

# Acceptance Criteria

- [x] Screen should include combined & individual disability ratings
- [x] Each rating should include what the disability rating is for, if it is service-connected (yes or no), and the effective date. 
- [x] Screen could include "Learn about VA disability ratings" and "Need help?" sections (see VA.gov website)

**Comment by melissa-lefevre** [comment]
When the user selects the disability rating link in the profile banner, they will be taken to this screen. 

![disabilityrating.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/9003f834-71d8-4aa3-8238-aaf8b01ec17a)

Copy: 
Combined disability rating
100% 
This rating doesn’t include any disabilities for your claims that are still in process. You can check the status of your disability claims or appeals with the Claim Status tool.
Check your claims or appeals

Individual ratings

40%
diabetes
Service-connected disability? Yes
Effective date: 01/06/2005

0%
hearing loss
Service-connected disability? Yes
Effective date:18/03/2014

30%
PTSD
Service-connected disability? Yes
Effective date:18/11/2013

20%
cervical strain
Service-connected disability? Yes
Effective date:01/07/2018

Learn about VA disability ratings

To learn how we determined your VA combined disability rating, use our disability rating calculator and ratings table.

About VA disability ratings

Need help?
Call our VA benefits hotline. We're here Monday through Friday, 8:00 a.m to 9:00 p.m. ET.
