### ISSUE TITLE
Make street, city, state or Zip required field for Facility Locator search

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2739]
@NatalieEMoore commented on [Tue Jul 24 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11684)

@U-DON can you let me know how this is working on FE but right now there is no change to the messaging if a user types the wrong word or no words and we were hoping to get more specific on the messaging. 

cc: @jstanek 

![Screen Shot 2018-07-24 at 12.32.14 PM.png](https://images.zenhubusercontent.com/59c004f6b0222d5de4782892/4135c9fa-2c31-492f-8da2-de7535f7aebd)

---

@jstanek commented on [Tue Jul 24 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11684#issuecomment-407583245)

@NatalieEMoore Beth suggested we could move this message closer to the location search box to serve as helper copy,

**Note:** Be sure to enter a street name, city, state, or zip to find services and facilities.

---

@NatalieEMoore commented on [Wed Jul 25 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11684#issuecomment-407779975)

that could work too

---

@mmiddaugh commented on [Tue Oct 22 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11684#issuecomment-545139352)

@brangi , here is one to evaluate for level of effort and usability impact. 
Two things here: 
1- The first field (street/city/state/zip) probably should be marked required. That might resolve the absence of results in most cases. 
2- If there are truly no results, then the language becomes relevant. We should look across the website and see how other areas handle searches that do not return results

This may require @arickalewis1 design input

**Comment by mmiddaugh** [comment]
Make city, state, zip field required 
Confirm links from other pages which pre-populate facility type still function correctly
Search cannot be activated without first field value

**Comment by mmiddaugh** [comment]
This is a short term solution to provide user value/resolve pain point

**Comment by mmiddaugh** [comment]
@jenstrickland are there any other particular considerations for this?

**Comment by jenstrickland** [comment]
<img width="1040" alt="Screen Shot 2019-11-01 at 4 23 54 PM" src="https://user-images.githubusercontent.com/57469/68054148-0b024b00-fcc4-11e9-8eac-08bde0e1a0ea.png">

@mmiddaugh At this time, there is no error message indicating that I haven't entered anything in the City, State, or Zip input. The form just hangs with the Search button focused.  The acceptance criteria asked that the Search button not be active until the requirements are met, but in absence of that we should at least provide error messages that say which required fields need information.

**Comment by jenstrickland** [comment]
The Search button should not be disabled. Rather, error messages should be provided to indicate the missing information for the required fields.

**Comment by brangi** [comment]
@mmiddaugh @jenstrickland , is the error message necessary when there is already a message warning the required fields ?

<img width="1162" alt="Screen Shot 2019-11-05 at 2 02 55 PM" src="https://user-images.githubusercontent.com/100468/68241853-0fd14280-ffd5-11e9-831a-9fbc1fc71eee.png">

**Comment by jenstrickland** [comment]
@brangi — That HTML5 required attribute behavior isn't rendering when I view the screen. I included a screen recording in this ppt file, since mov files aren't accepted.  If those required dialogs are included, that ought to be an acceptable interim fix.

[FacilityLocator.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3811034/FacilityLocator.pptx)

**Comment by mmiddaugh** [comment]
@brangi please review [16732](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16732) regarding search functionality for address

**Comment by brangi** [comment]
@mmiddaugh @jenstrickland the fix has been merged to prod

**Comment by mmiddaugh** [comment]
@brangi can this be closed?

**Comment by brangi** [comment]
@mmiddaugh yes, fix has been merged
