### ISSUE TITLE
Add Disability Rating to Profile Banner

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#27395]
# User story
As a user of the VA mobile app, I want to view my disability rating.

**Note:** Reference staging.va.gov to see ratings (test user +224 has several disability ratings)

### Research support
User research supports that many users would find it valuable to view their disability rating. 
> "I would add a breakdown of disabilities: current disabilities, current rating, service-connected percentage amount, and permanence." 

> "It's very informative to tell me if the disability rating goes up then I can qualify for a certain percentage of taxes to be taken off from my house."

This feature has also recently been added to VA.gov's Profile.

# Acceptance Criteria

- [x] Include combined service-connected disability rating into the Profile Banner (note: this AC assumes we are copying VA.gov's UI, if that doesn't feel right in design change this AC)

**Comment by melissa-lefevre** [comment]
Here is the Disability rating added to the profile banner:

Copy:
Your disability rating: 
100% service connected

![Profile.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/7812ee6a-30a1-4c30-9ecc-0509b62c8777)

I went off of the current design on staging.va here is a screenshot for reference:![Screen Shot 2021-07-21 at 9.45.38 AM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/29ab364b-127f-4548-939c-85dd16113071)
