### ISSUE TITLE
Remove Sign Up alert from Spanish and Tagalog pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27392]
## Issue Description
An alert that used to be on the [English vaccine page](https://www.va.gov/health-care/covid-19-vaccine/) is now showing up on the [Spanish](https://www.va.gov/health-care/covid-19-vaccine-esp/) and [Tagalog](https://www.va.gov/health-care/covid-19-vaccine-tag/) pages. We want it removed from all three pages.

The page was created in drupal but the alert was created separately in the FE. 

![Screen Shot 2021-07-14 at 5.36.51 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d74a8e3a-161d-41c5-8934-c4da14a7564d)

## Tasks
- [ ] Remove alert from Tagalog and Spanish pages

## Acceptance Criteria
- [ ] Alert no longer showing on any of the vaccine pages.

**Comment by stephenBarrs** [comment]
@RLHecht the CTA widgets have been removed from ES and TAG pages in Staging and Prod.  Thanks for bringing this to our attention!

**Comment by RLHecht** [comment]
Thanks @stephenBarrs. Just validated on prod.You can close the ticket.
