### ISSUE TITLE
CT Redesign: Update location search results display on mobile viewports

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27408]
As a developer, I need to update the location search results UI of the comparison tool redesign sandbox so that it displays in a user friendly manner on mobile devices.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. After clicking the search button, the "Showing XX results..." content is the first thing displayed beneath the following content:
    a.  Search by name accordion
    b. Search by location accordion
    c. "Update tuition and housing estimates" component
    d. "Filter your results" component
2. After clicking the search button, tab options "View List" and "View Map"  are displayed beneath the following content:
    a.  Search by name accordion
    b. Search by location accordion
    c. "Update tuition and housing estimates" component
    d. "Filter your results" component
    e. "Showing XX results..." content
4. The width of the tab content is equal to the with of the search accordions (about 288px).
5. The "View List" tab displays the search results cards are vertically one at a time.
6. The "View Map" tab displays the map
7. Clicking on a map pin in the "View Map" view switches to the "View List" view with the institution card for the corresponding pin displayed from the list.
8. The user is not able to search using the map control.
9. The map retains it's most recent display state when switching between tabs.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222698/296060491/preview#project_console)
2. [Breakpoints documentation](https://design.va.gov/design/breakpoints#names-and-values)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17984

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2043)

**Comment by delli-gatti-michael** [comment]
Testing complete
