### ISSUE TITLE
Remove unused debug event in GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#27403]
We have an event called `Debug Event` and a related trigger called `CE - debug` with no recorded data in production....

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20200801&_u.date01=20210713&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=debug-/

I suggest we remove these if they aren't being used.

**Comment by laurensimpson14** [comment]
Removed the Debug Event and associated Trigger.

**Comment by bsmartin-ep** [comment]
LGTM.

**Comment by bsmartin-ep** [comment]
Published to production.  Closing.
