### ISSUE TITLE
Redesign Letters empty state UI 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#27402]
# User Story
As a user, if the VA app can't find letters for me, I want to see a screen that says that and is clearly designed.

# Background 
This error message got long over time and is a lot of text center-aligned on a screen -- it feels hard to read. Let's apply the Empty UI style we're using for Claims and Secure messaging here to increase readability. 

# Screenshot reference of the build now
![IMG_0057.PNG](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/9fc8b726-85f6-409a-b752-61cf462cfefa)

# Reference of left-aligned Empty UI design
![Screen Shot 2021-07-14 at 5.52.12 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/84e70e6c-ffa4-469e-9048-76524a6dae90)

**Comment by melissa-lefevre** [comment]
I changed the Letters empty state to look like the Claims empty state. Other than changing the copy, everything else is the same as the claims empty state, font, padding etc. 

Copy:
We couldn’t find any letters for you.
We’re sorry, we can’t find any letters for you. If you think this is an error, please call the VA benefits hotline.

![Info screen.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/a035c024-e026-4759-9a49-9e9eb63f57d8)

**Comment by bridgethapner** [comment]
@melissa-lefevre Next week, can you open a FE ticket for this? Thank you! :)

**Comment by melissa-lefevre** [comment]
Link to FE ticket: 
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/27587
