### ISSUE TITLE
CT Redesign: Update name search results display on mobile viewports

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27407]
As a developer, I need to update the name search results UI of the comparison tool redesign sandbox so that it displays in a user friendly manner on mobile devices.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. After clicking the search button, the "Showing XX results..." content is the first thing displayed beneath the following content:
    a.  Search by name accordion
    b. Search by location accordion
    c. "Update tuition and housing estimates" component
    d. "Filter your results" component
2. After clicking the search button, the search results card content is displayed beneath the following content:
    a.  Search by name accordion
    b. Search by location accordion
    c. "Update tuition and housing estimates" component
    d. "Filter your results" component
    e. "Showing XX results..." content
3. The search results cards are displayed vertically one at a time.
4. The width of the search results cards is equal to the with of the search accordions (about 288px)

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#)
2. [Breakpoints documentation](https://design.va.gov/design/breakpoints#names-and-values)

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/17951

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2042&group_by=cases:section_id&group_order=asc
