### ISSUE TITLE
Remove unused "Crisis Modal" tag from GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#27404]
We have tagging for a homelessness crisis modal on https://www.va.gov/health-care/ that is no longer in use.  It's now an `additionalInfo` component and [can be tracked here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20210101&_u.date01=20210713&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:nav-additionalInfo-expand,analytics.eventAction:Navigation%20-%20Additional%20Info%20-%20Expand%20-%20How%20do%20I%20get%20help%20if%20I'm%20homeless%20or%20at%20risk%20of%20becoming%20homeless%3F%20-%20We%20may%20be%20able%20to%20help/
).

We can remove tag `Crisis Modal Clicks` and triggers `Crisis Expander Link on Health Care` and `Crisis Homelessness Modal Clicked`.

**Comment by laurensimpson14** [comment]
I made these changes in the GTM container `GTM Cleanup` [here](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000552). I also deleted the Trigger `Crisis Expander Link` that was being used as an exemption to the `Outbound Links` Tag.

**Comment by bsmartin-ep** [comment]
LGTM.

**Comment by bsmartin-ep** [comment]
Published to production.  Closing.
