### ISSUE TITLE
CT Redesign: Update typeahead menu and pin selection behavior

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27416]
As a developer, I need to update the typeahead and pin behavior so that the experience is good on both mobile and desktop experiences.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. On mobile, the typeahead for name search pushes the rest of the controls below the free text field down so that they are still visible if within view.
2. On mobile, the typeahead for location search pushes the rest of the controls below the free text field down so that they are still visible if within view.
3. When clicking a pin on the map view, the corresponding card is highlighted in the gold focus box pattern on mobile.
4. When clicking a pin on the map view, the corresponding card is highlighted in the gold focus box pattern on desktop.
5. The map pin letter identifier is replaced with a number identifier starting with the number 1 and incrementing by 1.
    a. The identifier on the search result card listing is replaced with the corresponding number identifier.

## Supporting Artifacts:
1. [Desktop prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P)
2. [Mobile prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18079

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2048)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
