### ISSUE TITLE
[FE] Add Search Results for Resources and Support Copy

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27417]
## Issue Description
_As part of the search UI consistency effort, working with IA, Design and Accessibility to create a more consistent design for search tools. PW team needs to add "Search results for resources and support:" copy to the staging environment for review and approval by Design Leads_

Desktop:
<img width="602" alt="Screen Shot 2021-07-15 at 9 05 04 AM" src="https://user-images.githubusercontent.com/70410912/125811091-85393dab-7842-448b-93a3-05fab49e6b19.png">

Mobile:
<img width="275" alt="Screen Shot 2021-07-15 at 9 05 19 AM" src="https://user-images.githubusercontent.com/70410912/125811121-8426c4ca-4d38-4e56-a645-fa9973afd82c.png">

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling **(Cassandra Allen)**
- [ ] Ensure change is ONLY in Staging and not pushed to Production Environment
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/125829261-7d795433-fad5-44ad-8f33-85822bf9a71c.png)

We want an additional header despite already having `Search resources and support articles or all of VA.gov`? I'm confused by this request

**Comment by brianalloyd** [comment]
@kelsonic let's circle back on this tomorrow during SU as @callen2563 has context on this and agree this might not be needed based on what we already have in support.

**Comment by brianalloyd** [comment]
Awaiting response from @callen2563 in terms of decision from the Design Council on decision point.  Team feedback is that this is redundant and likely not need for R&S Search elements.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563

**Comment by callen2563** [comment]
We can disregard that "search results" copy addition it looks like it was decided that we remove it. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/21513

**Comment by kelsonic** [comment]
Awesome, thanks @callen2563! Closing the ticket since there aren't any action items here anymore 🙂 Feel free to reopen if anything changes!
