### ISSUE TITLE
Analytics Feature Request/Bug Report

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27423]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

  - Sharon Kasimow -Product Manager, C&L team, Translation Recommendations project

- Is this a feature request or a bug?

  - [x] Feature request
  - [ ] Bug report

## Request/Report Description

For a new feature request:

Requesting the addition of language query in Domo so that we can compile reports by language segments and run against metrics such as PVs and UVs. 

This ability can not be easily supported in GA through the creation of standard reports or custom reports (limit of 4  segments that can be used and you can not assign a segment to just one reporting tab).

This data is being used for upcoming report to Congress on our Translation Recommendations.

Ideally I would like to be able to start gathering this data by 7/23.

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by SKasimow** [comment]
@laurensimpson14 Hi Lauren - please take a look at the write-up and feel free to edit/clarify any of it! Thanks, Sharon

**Comment by andaleliz** [comment]
I'm auditing old tickets Sharon created and it looks like this went no where and many of the folks on the ticket aren't around. I'm going to close this but feel free to reopen if needed.
