### ISSUE TITLE
Improve handling of invalid locations in Facility Locator

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#27432]
# Description

As a Veteran, I get a helpful response if I enter an invalid location into the Facility Locator

# Current Behavior

After entering an invalid location and clicking "Search", the user sees the following message:

![Find_VA_Locations___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/40c67f8f-f580-48cd-8ea3-2467e078349c)

# Desired Behavior

After entering an invalid location and clicking "Search", the user is notified that their location is invalid, and prompted to try entering a different location.

(Needs design input!)

**Comment by mmiddaugh** [comment]
Closing as duplicate for Better support for "no results found" on Facility Locator #36955
