### ISSUE TITLE
Pre-need: Update or remove respondent burden text

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27430]
## Description

At the bottom of the [pre-need introduction page](https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction) is a "Respondent Burden" paragraph.

![Screen Shot 2021-07-15 at 12 43 34 PM](https://user-images.githubusercontent.com/136959/125833392-42a20e0a-4faf-49ae-804d-4a9d54b3e950.png)

It is difficult to read and includes content that is also included in the privacy act statement modal (click the "Privacy Act Statement" link), but the modal content varies between staging & production - see screenshots - [this problem was reported to for followup determination](https://dsva.slack.com/archives/C5AGLBNRK/p1626367361329700).

<details><summary>Privacy Act Statement modal (staging & production)</summary>

**Modal seen on staging**

![Screen Shot 2021-07-15 at 11 35 57 AM](https://user-images.githubusercontent.com/136959/125833706-c0ebea9b-3354-4e1b-b9c4-6519f18dc7bf.png)

**Modal seen in production**

![Screen Shot 2021-07-15 at 11 35 43 AM](https://user-images.githubusercontent.com/136959/125833716-df0266c5-6822-47a6-be30-cb48da8ea85c.png)</details>

## Tasks

- [ ] Review respondent burden content outside of modal & determine if it needs to be updated or removed

## Acceptance criteria

- [ ] Tasks completed
- [ ] Relay & document findings

**Comment by AlexanderSherrow** [comment]
@Mottie did we ever get any final thoughts on whether to remove this text block or not?

**Comment by Mottie** [comment]
The text block should instead show up within the modal that opens when the "Privacy Act statement" link is clicked, and not show as stray text under the OMB block. I'm not sure what the content of the modal should be - it's different for a few apps. And lastly, it should use the new [`va-omb` web component](https://design.va.gov/storybook/?path=/docs/components-va-omb-info--default) which replaces the link with a more material-honest button that opens the modal.

**Comment by ccruzgra** [comment]
@joshkimux is there anything concluded for which version of the Privacy Act Statement modal is correct, staging v. production? The thread in Slack is from two years ago.

**Comment by joshkimux** [comment]
@ccruzgra I don't know unfortunately, as I don't have too much context behind this ticket/conversation. Danielle or CAIA may be able to support.

**Comment by ccruzgra** [comment]
This is the related issue logged for the differences in the Privacy Act Statement modal in staging v. prod: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27577

**Comment by ccruzgra** [comment]
@joshkimux based on the feedback from Danielle and Matt Self, it seems the staging modal was probably never updated as the text is really generic and the production modal is reflecting content specific to education, which is a known issue in several forms. The modal overall needs to reflect the privacy act statement specific to the pre-need form.

**Comment by sonntag-adam** [comment]
@Mottie the fix is in staging.

**Comment by MichelleDieudonne** [comment]
@Mottie Will you be closing this GitHub items since the fix is in Staging?

**Comment by Mottie** [comment]
You are more than welcome to close these tickets 😺
