### ISSUE TITLE
[Spike] Track contact info page interactions

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27455]
## Description
Currently, we have a separate page in the scheduling flow for users to input contact information. If a user has this information in their profile, we pre-populate the fields and allow them to edit for the one appointment. All fields are required to continue through the flow.
- Requests: phone number, best times to call, email address
- Direct: phone number, email address

Goal:
- Reduce the amount of time it takes a user to get through the scheduling flow
- Avoid collecting unnecessary information, or information the VA doesn't use

![Screen Shot 2021-07-21 at 10.05.34 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/fa6fd5db-3b09-48d6-97aa-9e53a1ac98fe)

## Questions
- How often is the phone number field pre-populated vs not?
- If the phone number is pre-populated, how often does a user change the value before continuing?
- How often is the email field pre-populated vs not?
- If the email is pre-populated, how often does a user change the value before continuing?
- What are the most common combinations of best times to call?
- In the direct scheduling flow, if a user has a phone number and email in their profile, are there any performance or technical concerns if they skip the contact info page and go directly to review?

## Tasks

- [ ] Identify ways we can track interactions for further analysis, and provide technical recommendation

- [ ] Answer questions above

## Time Box
3 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by jbalboni** [comment]
Events:

vaos-contact-info-email-populated
vaos-contact-info-email-not-populated

vaos-contact-info-phone-populated
vaos-contact-info-phone-not-populated

vaos-contact-info-phone-changed
vaos-contact-info-phone-not-changed

vaos-contact-info-email-changed
vaos-contact-info-email-not-changed

I also added `vaos-preferred-combination` as an attribute on the submit event. It may take some work by the analytics team to handle that.

**Comment by jbalboni** [comment]
And to answer the last question, I did a quick prototype of the changes, I don't see any issues with skipping the contact info page if we have that info from the profile. Everything seems to work fine.

**Comment by laurenernest** [comment]
@jbalboni I'll submit the request to Analytics to add the attribute in GTM. Is it on both `vaos-request-submission` and `vaos-community-care-submission` or just request?

**Comment by laurenernest** [comment]
> And to answer the last question, I did a quick prototype of the changes, I don't see any issues with skipping the contact info page if we have that info from the profile. Everything seems to work fine.

Good to know! cc @outerpress

**Comment by jbalboni** [comment]
@laurenernest Should be on both

**Comment by bsmartin-ep** [comment]
@laurenernest - 

I will add this as a custom dimension to GA today.  What is the dataLayer parameter name?

**Comment by laurenernest** [comment]
@bsmartin-ep since we've already implemented it with that naming convention, can we use it or will that break something? i'm assuming the data will backfill for visualizations from the time we implemented it so hoping it'll reduce the amount of time we need to track this

**Comment by JRRoof** [comment]
Totals by Event Label for Jan 01 - Jun 30, 2022
