### ISSUE TITLE
[Discovery] Yellow Ribbon - Determine feasibility of search by abbreviation

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27464]
Follow-on Discovery issue to this one: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26829

Now that the data sources have been identified, determine if there is a way we can provide users with a way to search by common institution abbreviations such as NYU, UCLA

**Comment by zacharymorel** [comment]
Something of note, after talking with the BAZ engineers and then querying the data for myself, I have confirmed that the alias data is very "junky", many common schools are missing and some are full on sentences.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel yikes.  That is disappointing.  Thank you for the update!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I am filling out the sprint report for sprint 55 and just realized there is no estimate on this task.  Do you recall how long it took?  Thx!

**Comment by zacharymorel** [comment]
Yeah, a two was fine. It was not _too complex_ to figure out.
