### ISSUE TITLE
Monitor Cypress failures and address accordingly

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#27460]
We have had an extreme number of failures being reported in our `gha-test-status`  channel.  Some of these are due to failed tests, while others present other complications that are not related to a test failing. We need to start smoothing out these issues to ensure GHA has a non-frustrating launch for users.  

1) Any test failures should be run in a loop locally to try and reproduce. If possible, optimizations should be made to test specs to avoid these errors in the future.
2) Any non-test failures should be investigated thoroughly and solved to the best of our ability.

**Comment by CBonade** [comment]
Yesterday, I noticed that the spec `src/applications/search/tests/e2e/00-required.cypress.spec.js` was involved in roughly 20-30% of our failures in the `gha-test-status` channel.  A number of improvements have been made to this spec:

- Updated Cypress server and route commands to the newer intercept
- Changed the custom axe function being declared in this spec to use the globally set up ones (accomplishing the same objective)
- Added assertions to get statements to stop Cypress from getting ahead of itself.
- Added an assertion to ensure that the input field on the search is not disabled before attempting to type into it (this was causing multiple failures, specifically)

After these changes, I pushed this to CI with the loop code still implemented, so it would run 20x in CI.  It passed all 20 runs in CI, so the loop was removed.  This PR is open and just waiting for the appropriate teams to review.

**Comment by CBonade** [comment]
Updates today:

Lots of trial and error, with little moving the needle.  Most of our errors are currently coming from two places:  Dependency Installation and Build/Testing timeouts.  On the build front, Eugene threw some extra error logging into the build that was timing out and while without the extra logging it had seemed the build was hanging entirely, however it appears that it actually made it to 92% before blowing up.  This seems to imply the resources are stretched too thin and it's running super slow. I've taken two steps here:

1) in the interim, I've asked Demian/ops to consider either bumping up the power of the runners or cutting down the limit on how many jobs they can take simultaneously, to see if freeing up more resources will stop the timeouts.

2) While that may be in progress, I've doubled the timeouts on my branch and am running it attempting to see a build that goes over the old timeout, but finishes before the new timeout.  My thoughts here are, if it times out still at double timeout, the process is likely hanging entirely.  If it finishes over the old timeout but within the new timeout, then it's just running slow.  Hopefully, knowing this for sure will give ops the information they need to adjust the runners accordingly.

**Comment by CBonade** [comment]
Current status here:

Regarding ops and hardware: Demian is going to try turning down the number of runners per instance, and bumping up the number of instances - to avoid runners fighting over limited resources and hopefully, helping avoid timeout issues.

Regarding the timeouts:  I doubled the timeouts, however unfortunately, on my last run of doing that 3 processes still timed out at 2 hours each.  Two of these processes were only one test in when they timed out. This seems to imply that the processes are not just running slow, but they are hanging entirely at a point and never resuming. Darius has enabled more logging from Cypress and we are going to explore further.

**Comment by CBonade** [comment]
Updates today: 

Ran some more testing here with the build runners switched over to github-hosted to match Darius' efforts of switching the Cypress ones over.  The build overall feels way more stable, albeit WAY slower, and we both agree we feel the problem lies in how the runner is handling/isolating the processes (it's not isolating them at all).  Darius started a conversation with Demian to toss around some ideas about how the runners could be reconfigured to solve these problems.  We both felt confident saying that the problem is on the runner side at this point.

https://dsva.slack.com/archives/C01V94K0QNS/p1626876793349300 Conversation starts here

**Comment by CBonade** [comment]
We had a mob session today to start the process of dockerizing these cypress runs.  The last run of said build ended up with failures trying to install Chromedriver.


https://github.com/department-of-veterans-affairs/vets-website/runs/3138086811?check_suite_focus=true

**Comment by CBonade** [comment]
Yesterday:

Darius added an extra two parallel processes for Cypress. I re-added dependency caching.  Results?  Very reduced times across the board!

Today: 

Darius and I have opened PRs for many flaky test spec fixes, many of which have been merged already into master.  WIP.

**Comment by CBonade** [comment]
Continued to notate failures of specs and dependency installation failures on the slack notifications today.  No timeout failures today.

**Comment by CBonade** [comment]
Merged in an attempted band-aid to stop some of our test-reporting failures that were being caused by another workflow pushing after your workflow had checked out the repository already.

**Comment by ddzz** [comment]
`docker pull` rate limit errors have appeared on GitHub Actions. This PR should address the error: https://github.com/department-of-veterans-affairs/vets-website/pull/18097

**Comment by CBonade** [comment]
I've opened a PR today to address the issues we have been having with the `Testing Reports` step failing.  The action that handles commit and push prior had it's default branch as `master` if one was not set. While their docs have not updated, it appears that they at some point changed their default to `main`, which is why this started having conflicts (we were checking out master, but pushing to main which was outdated).  I've explicitly declared "master" as the branch on the push and it seems to be working on my PR here:

https://github.com/department-of-veterans-affairs/vets-website/pull/18145

**Comment by CBonade** [comment]
While efforts will continue to refine tests that look like they may be regularly flaky, I think we may be stable enough to close the primary efforts of this ticket out. We've been a few days now of no failures that are not valid failures for normal reasons.

**Comment by CBonade** [comment]
Some new failures popped up today with flaky profile personalization tests on a few different branches.  The url check seems to be timing out waiting for the loading circle to go away.  Will be attempting to fix this with either a longer timeout, an extra assertion, or both if necessary.
