### ISSUE TITLE
Dashes in appointment ids may not be parsed properly by vets-api

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#27463]
This call received a 404 in production: https://api.va.gov/vaos/v0/appointments/va/202107130000000000000000000000000000UdimCKR5gTn-Weqtpq9PgPg 

Are `-`'s allowed in the appointment ids in the Rails url parsing? This seems similar to the period issue.

http://sentry.vfs.va.gov/organizations/vsp/issues/42458/?environment=production&project=4&query=is%3Aunresolved+vaos&statsPeriod=14d

**Comment by jbalboni** [comment]
@grossb1 Can you look into this and see if dashes are the culprit here?

**Comment by laurenernest** [comment]
@jbalboni assigning to you for validation and closure.

**Comment by jbalboni** [comment]
Looks good to me, no dashes in 404 errors recently
