### ISSUE TITLE
Find a VA Form - Translation request for updated "Go to online tool" verbiage.  

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27467]
The Decision Tools team needs the text for two action links translated into Spanish so that we can display it on our search page for forms that are in Spanish. 

The first action link reads **Fill out VA Form [`form name`] Online.**

The second link reads **Download VA Form [`form name`] (PDF).**

![image](https://user-images.githubusercontent.com/73354907/128397901-4ce03a5a-f5a4-4773-9409-727083727a02.png)

**Comment by MarciMcGuireGCIO** [comment]
@SKasimow - I am just creating this as a placeholder and will update/tag you once we have new CTA text to translate.

**Comment by MarciMcGuireGCIO** [comment]
@SKasimow Please let me know if you have questions about this request or need more info!  Thank you! 😄

**Comment by SKasimow** [comment]
@RLHecht Hi Randi - can you please get the 2 action links described in ticket ^ translated to Spanish? Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @SKasimow and @RLHecht !

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO I sent these out for translation and will post here when he sends them back.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @RLHecht!

**Comment by MarciMcGuireGCIO** [comment]
Great!  Thanks, @RLHecht !
