### ISSUE TITLE
CT Redesign: Create search / search results framework for mobile displays

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27466]
As a developer, I need to create the framework for the mobile search / search results page so that multiple developers can work on the page at once implementing the various sections.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The contents and stylings of the accordions are out of scope of this story.

## Acceptance Criteria:
1. The breakpoint for mobile display is 481px ($small-screen).
2. The "Search by name" tab is styled as an accordion.
3. The "Search by location" tab is styled as an accordion.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#)
2. [Breakpoints documentation](https://design.va.gov/design/breakpoints#names-and-values)

**Comment by dmccurdybah** [comment]
PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27466

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2021)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
![6FAB200D-17C8-435C-8CB9-34A92115CDF6.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/81fad714-f15c-42b5-bcd6-9d09e6ab3a85)Testing complete
