### ISSUE TITLE
5th specialty code doesn't return results

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27465]
## Summary
In #23895, a 5th Podiatry specialty code (213ES0103X - Podiatrist - Foot & Ankle Surgery) was added to our query of Community Care providers for the provider list. 

**Technical Notes**
From initial investigation in original ticket ([see comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23895#issuecomment-881507299)), "...the facilities endpoint is hardcoded to only look at the first 4 specialty codes. [This method](https://github.com/department-of-veterans-affairs/vets-api/blob/fcb8cb4e960d14b0dbe3f6a165c9ec4c2fc6455a/lib/facilities/ppms/v1/client.rb#L161) in vets-api needs to be updated by the facilities team in order for us to query the 5th podiatry code."

**Product Notes**
The Facilities work should already be complete so this will require coordination with the Facility Locator team to resolve.

## Steps to Reproduce
**Test User:** Jacob Reid

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Click Start scheduling
3. Select Podiatry
4. Select a calendar preference
5. Select provider preference

### Actual Result
Foot & Ankle Surgery providers do not display in the list
![23895 validation missing provider.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1cdcbd72-9fa6-471c-9b5a-bebdb6e5f729)

### Desired Result
Foot & Ankle Surgery providers display among other specialty code providers if within distance or max providers returned in list

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by LeKeve** [comment]
@laurenernest We received a new endpoint to use from the facilities api team. Will be updating this request to use the new url.

**Comment by laurenernest** [comment]
Looks good! closing ticket.
![27465 validation.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/30c45ed7-963a-4149-aab6-706accf5c7f1)
