### ISSUE TITLE
Access for [won choi]

### ISSUE THREAD

**Issue by wonhchoi** [department-of-veterans-affairs/va.gov-team#27476]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Laura Ross
- Please provide your name.
   > Won Choi
- Please Provide your email.
   > won.choi@asmr.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Digital GI Bill: DevSecOps: Accenture Federal Services

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnd7scRhYCyGqgWAd9WoMVJ/l5jei3qCZGx5b21qSosr4EUwppqiqV2TVA3c6xiPeavbiXW2dhD0ANUUWNHCPe4Fq4zLd2MC5iTFEadKW80GvdZp4gwzbx/AwkxhV09y93AZM3purg0+E364cUV/ga1TqUwKzcRiYZCsi0NpTip+BKJLIAcLWzSCrsEqs0RDJ/Ku6hEf54s7Cxf98A0jwXAXBnM0K7m7js64JxYlYVS9oAZdRXnVly/ogK7rdIf8wUupZ3eGF1ZyH5gzDCpU56/QOHQsEZ5j4ufP1IL7ovjGG+e2Fjwr+81nsqEJjyRB/i3xzOOlklh+2EdmoDn2hZ7ryYpBpJPC0MgKS3sKFSk4n8W76riGBBQdIjPGICtbDkV5t8EOZwZ52liWu5bpQyOxj1zjomNO3ARajfm6JVkoICow78I4TrP7GR2qNFUo00Tf8lFtLW7PLBJQcnL7KDNzxzWbRRtee5e8Ldb+lZGnau0Mj7vlvWm0Y0hGnqiJOfQB+O2hVx3TSMVv5MMXYZw79+BrKCCAkzPKk7n8c73JjTwFdDlLahhOteOTJ50/2kzDl8dkRAoOBdhwzsHF46R1n49V3pdSITlAyoH8dDG8FusW5EcX1m2OWtDA3nMBGXF29xvPqAFS3mPpAyfVgdnIN9PqdIyLGhri8PrLw2SQ== won.choi@asmr.com
```

- Grant AWS Console access?
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
