### ISSUE TITLE
Replace straight quotes with curly quotes in content (not code)

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#27473]
# Description

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1626451577121800

Currently, it is up to the content editor to use curly quotes over straight quotes:

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/5655e325-5f52-4182-bb0c-4846cdd016a2)

This is not sustainable as many content editors' keyboards default to straight quotes. We should look into frontend solutions that can format the content from the CMS to exclusively use curly quotes for content and straight quotes for code (html).

## Example page

URL: https://www.va.gov/resources/what-if-i-cant-sign-in-to-vagov-because-my-password-doesnt-work/

Curly apostrophes VS straight apostrophes

![image](https://user-images.githubusercontent.com/12773166/125980238-f479c10d-ee7e-4f43-87df-0feaa75fc39f.png)

![image](https://user-images.githubusercontent.com/12773166/125980267-d43d2369-b3f2-4238-9afa-ed4d1df36657.png)

**Comment by brianalloyd** [comment]
CMS is handling this issue, closing ticket in support.
