### ISSUE TITLE
Change va-accordion-item internal ID to "va-accordion-item-content"

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#27472]
## Issue Description
Having a generic ID like `content` (what it is now) has a greater chance to inherit conflicting styles.

This may be a non-issue if we can encapsulate the web component styles to not inherit anything, but I'm not sure if that's what we want to do.

---
## Tasks
- [ ] Change the `content` id to `va-accordion-item-content`

**Comment by bkjohnson** [comment]
This is currently a non-issue due to the shadow DOM. However, that may change as a result of [discovery on using USWDS3 resources](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1035)
