### ISSUE TITLE
Prep Tasks for Research: Find a VA Form PDF Download Information

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27475]
## Issue Description
_Tasks needed in support of upcoming research project_

## Preparatory tasks
- [x] Review both versions of prototype on Staging
- [x] Share research plan and conversation guide with Lauren Alexanderson for approval and recruiting
- [x] Make note-taking spreadsheet
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilots
- [x] Debrief pilots 
- [x] Revise conversation guide
- [x] Send instructions to observers
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day
- [x] Followup with Perigean re participant list
- [x] Other tasks as needed 

## Acceptance Criteria (AC)
- [ ] All set to start research sessions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO Added task at top: **Review both versions of prototype on Staging**

**Comment by MarciMcGuireGCIO** [comment]
@cindymerrill Thank you!

**Comment by cindymerrill** [comment]
Recruiting launched to Perigean yesterday, and communications started with emails and Slack today. First pilot is this afternoon, and I'll be scheduling a second pilot for tomorrow.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cindymerrill!

**Comment by cindymerrill** [comment]
Conducted first pilot, which went well. Scheduled second pilot for tomorrow (Friday July 23). Sent instructions to observers. Started a notetaking spreadsheet.

**Comment by cindymerrill** [comment]
Conducted second pilot and debrief afterwards. Revised conversation guide and notetaking documents.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @cindymerrill .  This is shaping up to be a very informative and powerful study!

**Comment by cindymerrill** [comment]
Received participant roster from Perigean with 12 of 15 sessions scheduled, and most required and good-to-have characteristics have been met. 4 sessions with screen reader users have been scheduled, and Josh and/or Angela plan to attend them to provide technical support if needed. Looking forward to sessions starting tomorrow!

**Comment by cindymerrill** [comment]
Done prepping, and so closing.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @cindymerrill !
