### ISSUE TITLE
Login.gov Mock Up Content Review

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#27485]
## Issue Description

Identity team needs editing support for mockup screen to be viewed/tested with Veteran users. 

The goal of the text is to inform Veterans that changes will be made to current (sign in) providers.

Also to see which choice the Veteran would make between providers (Login.gov, ID.Me, Or continue with their current provider). 

[https://app.zenhub.com/files/133843125/5107103d-e085-43e1-8525-acb59a9f28c8/download](https://app.zenhub.com/files/133843125/5107103d-e085-43e1-8525-acb59a9f28c8/download)

**Comment by peggygannon** [comment]
HI, @APorter-Clarity I have a couple of questions about this update: 

1. Is the intent to let users know they in the future there will only be 2 options to sign in to VA.gov (Id.me and Login.gov)? is this modal eventually going to replace the current VA.gov sign in modal? 
2. Is Login.gov replacing DS Logon altogether?  
3. Will users no longer have the option to sign in to VA.gov with their MyHealtheVet account? (MHV is a sign-in option on the current modal)
4. For users who need to create an account, will they need still go through the identity verification process through ID.me first? or will Login.gov allow users to verify their identity?

**Comment by APorter-Clarity** [comment]
Hi @peggygannon 

**1. Is the intent to let users know that in the future there will only be 2 options to sign in to VA.gov (Id.me and Login.gov)? is this modal eventually going to replace the current VA.gov sign in modal?**
- No, we do not intend to let the user know there will only 2 be in options in the future because we do not know when that future will be. Eventually we’re moving in that direction, but the timeline is still in the works. 
- The screen in the pdf will not replace the modal it will be the next screen users see if they select DsLogon or MHV.

**2. Is the Login.gov account replacing DS Logon as an option altogether?**
- In the future, if the user chooses to upgrade their account to Login.gov or ID.Me, this account would ultimately replace DsLogon but this isn't happening for a long time. There will be 4 options on the sign in modal (which include Login.gov and DsLogon)

**3. Will users no longer have the option to sign in to VA.gov with their MyHealtheVet account? (MHV is a sign-in option on the current modal)**
- Eventually, but not for a while. The pdf you have doesn't show the screen but all the providers plus Login.gov will live on the modal for a while before that change is made.

**4. For users who need to create an account, will they need still go through the identity verification process through ID.me first? or will Login.gov allow users to verify their identity?**
-  Not unless they are moving to an account that requires a higher LOA then yes, they would have to go through the identity verification process. 
- Login.gov- yes but still trying to figure out which account. Looking to make the process as seamless as possible.

**Comment by peggygannon** [comment]
ok, thank you. This is helpful information. So users will only see the modal in the mockup if they choose to sign in with DSLogon or MHV. The mockup modal doesn't make mention of MHV, so what is the user's experience if  they choose MHV on the current modal to sign in, but then they don't see MHV mentioned on this 2nd modal? 

It seems that we would some messaging/content around MHV in addition to DSLogon on the new modal.

**Comment by APorter-Clarity** [comment]
[https://app.zenhub.com/files/133843125/aec80bad-8a9b-439f-ab78-fdedbadc5f99/download](https://app.zenhub.com/files/133843125/aec80bad-8a9b-439f-ab78-fdedbadc5f99/download)

**Comment by peggygannon** [comment]
Hi, @APorter-Clarity Ok, thank you for follow up and the revised mockup.
