### ISSUE TITLE
Add active state for list item rows

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#27500]
# User Story
As a user of the app, whenever I press a button that is a row item, I want feedback that the button is active and the app is responding to me. 

# Acceptance Criteria
- [x] Define active UI style for: 
- Simple List rows
- Default List rows
- Claim Step Table rows
- Secure Messaging list rows

**Comment by melissa-lefevre** [comment]
Using primary-alt-lightest for the active state. 

![Screen Shot 2021-07-22 at 4.10.33 PM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/28aab1db-8e9f-47ae-9263-bc0131b83dd7)

This is the same as the picker we have in the design system. @drjecker  If this looks good, I can change the entire design system to have an active/ inactive state for each type of row.

**Comment by drjecker** [comment]
Looks good to me! Bridget put a handy list where it would apply above.

**Comment by melissa-lefevre** [comment]
In the design library, I added an active and inactive state to each of these symbols:

Simple List rows
Default List rows
Claim Step Table rows
Secure Messaging list rows

There was a "filled" state for the simple list row and I changed it to active/ inactive to be consistent.

**Comment by melissa-lefevre** [comment]
I created a FE ticket for making this change:
https://app.zenhub.com/workspaces/va-mobile-app---current-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/27867
