### ISSUE TITLE
Refresh-Incorrect H1 on VA request confirmation page 

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27502]
## Summary
When a VA request submission is successful, the Heading 1 on the confirmation page should display the type of care and indicate pending.

## Specs
- Device: Mac
- Browser: Chrome Version 91.0.4472.114

## Steps to Reproduce
**Test User:** Cecil

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Click Start Scheduling
3. Choose Nutrition
4. Choose Fort Collins VA Clinic
5. Select calendar preferences
6. Select This is a routine or follow-up visit and enter text in the additional details field
7. Choose Office visit
8. Continue through flow and submit request

Original confirmation URL: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/requests/8a488d9b7a6f1d73017ab1c045f10003?confirmMsg=true

### Actual Result
Heading 1 says "Pending not required appointment"
![Screen Shot 2021-07-16 at 5.06.20 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/5f611216-9bb6-4a42-bf44-b1e00e767623)

### Desired Result
Heading says "Pending nutrition and food appointment" or respective type of care

Design spec: https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/jgkdPMG

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by jbalboni** [comment]
This is a bug/new behavior in var-resources, so I believe it's due to the new release in staging. Checking with backend team to see what their intent here is.

Might be worth it for us to just go ahead and switch to using the type of care id instead of the text appointmentType field, which would make this backend change irrelevant.

**Comment by jbalboni** [comment]
Backend ticket: https://issues.mobilehealth.va.gov/browse/VAOSR-2158

**Comment by laurenernest** [comment]
Would this also result in the request not showing up in the appointments list on the homepage?
![Screen Shot 2021-07-19 at 12.10.34 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/7f414d3e-14d7-4249-ba83-c1f1d2f19591)

**Comment by jbalboni** [comment]
Not this specific problem, but I believe the requests not showing up is also related to ARS issues in staging. We've had this same problem with the VAOS service for a while, and it uses ARS underneath.

**Comment by laurenernest** [comment]
> Might be worth it for us to just go ahead and switch to using the type of care id instead of the text appointmentType field, which would make this backend change irrelevant.

In the long run, is it better for us to use the type of care id, or is that suggestion mainly to remove the dependency?

**Comment by jbalboni** [comment]
@laurenernest It's better for us to switch to type of care, we have to that anyway for the vaos service.

**Comment by laurenernest** [comment]
Sounds good. Moving back to ready.

**Comment by laurenernest** [comment]
Fix validated. Closing ticket.
![Screen Shot 2021-07-29 at 4.39.01 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/d7f60e50-176f-4d85-bc83-a69b5b0bd34f)
