### ISSUE TITLE
Refresh-preference details don't display on VA request confirmation

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27503]
## Summary
In the VA request flow, a user is required to indicate a modality preference and reason for appointment information. This information is not displaying on the VA pending request confirmation page.

## Specs
- Device: Mac
- Browser: Chrome Version 91.0.4472.114

## Steps to Reproduce
**Test User:** Cecil

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Click Start Scheduling
3. Choose Nutrition
4. Choose Fort Collins VA Clinic
5. Select calendar preferences
6. Select This is a routine or follow-up visit and enter text in the additional details field
7. Choose Office visit
8. Continue through flow and submit request

Original confirmation URL: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/requests/8a488d9b7a6f1d73017ab1c045f10003?confirmMsg=true

### Actual Result
- Modality preference doesn't display
  - Work to add was done in #25835
- Booking note doesn't display after reason for appointment
![Screen Shot 2021-07-16 at 5.01.28 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/2fedcd95-7cfb-41fc-8d0a-72c46632fa76)

### Desired Result
- Modality preference displays
- Reason for appointment and booking note displays

Design spec: https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/jgkdPMG

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by jenniemc** [comment]
The expected display under "You shared these detail about your concern" should show [Reason]: [Booking note]

It appears to be working in the local environment.  The error may be coming from the BE side in staging. Jeff created a ticket https://issues.mobilehealth.va.gov/browse/VAOSR-2161

**Comment by laurenernest** [comment]
Noted on the booking note.

Modality preference looks good! closing ticket.
![27503 validation.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/7fa701de-c9ed-40e5-a522-40acaabda80c)
