### ISSUE TITLE
7/19 HP Banner Alert COVID Content Update from OPIA

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#27506]
# Public Websites Banner Intake Request Form

## Description

Josh Tuscher from OPIA will update the COVID text on the HP current banner alert on Monday 7/19 to the following:

**Coronavirus FAQs: What Veterans need to know | Veterans Affairs**

**Coronavirus information:** To get the latest COVID-19 vaccine and Delta variant updates, and find out how to get your vaccine at VA, go to our vaccine information page. For questions about how COVID-19 may affect your VA health care and benefit services, visit our coronavirus FAQs or read VA’s public health response.

He may also delete the inclement weather portion of the alert.

## What do you need?

Choose one of the following and make sure you fill out at least the required details for it.

- [X] Homepage banner
  **Required Details:**
  - `startsAt`: Monday 7/19 (Time TBD)
  - `expiresAt`: No expiration date at this time
  - `title`: **Coronavirus FAQs: What Veterans need to know | Veterans Affairs**
  - `content`: To get the latest COVID-19 vaccine and Delta variant updates, and find out how to get your vaccine at VA, go to our vaccine information page. For questions about how COVID-19 may affect your VA health care and benefit services, visit our coronavirus FAQs or read VA’s public health response.
 
Visual Example:
![image](https://user-images.githubusercontent.com/70410912/119869662-be054b80-bedd-11eb-98dc-11ec71032670.png)

## Stakeholders

Who specifically should we communicate with when building + deploying the banner?  Please provide relevant contact details and desired slack details for forward communication.

- John Hashimoto - Public Websites PO
- Josh Tuscher - OPIA

**Comment by brianalloyd** [comment]
This was implemented, closing ticket in support.
