### ISSUE TITLE
STEM AD: Google analytics clicks within "More resources about VA benefits" is incorrect

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#27516]
## Expected Results:

Example: https://staging.va.gov/?next=%2Ftrack-claims%2Fyour-stem-claims%2F8468%2Fstatus

We will want to correct links-list-section-header to be 'More resources about VA benefits'

https://github.com/department-of-veterans-affairs/va.gov-team/issues/21747#issuecomment-828560986

![Screen Shot 2021-07-19 at 10.04.51 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/582fcc18-f5b8-4263-9e17-63863fa780ec)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18195
