### ISSUE TITLE
Fix GitHub Actions Errors in Testing Tools Team Data Dashboard Repo

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#27510]
There were 2 errors this weekend which I just addressed:
- https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/runs/3091516326?check_suite_focus=true
  - The response from TestRail is missing a status code sometimes. Trying to handle that...
- https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/runs/3096829197?check_suite_focus=true
  - Because the previous job failed (bullet 1) there were zero testrail metrics so this failed. I handled this edge case...

**Comment by holdenhinkle** [comment]
Here's the PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/49

**Comment by pjhill** [comment]
LGTM!
