### ISSUE TITLE
Redirect Request - 10-10EZR PDF Form

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27512]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)
- [X] A VA Forms Manager changed the name of a form PDF and Google has indexed the wrong URL

### Implementation date
When does this request need to be live: 

### Redirects 
Current URL  |  Redirect Destination or New URL
------  |  -----
https://www.va.gov/vaforms/medical/pdf/vha-10-10ezrfill.pdf | https://www.va.gov/vaforms/medical/pdf/vha-10-10EZR-fill.pdf

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [x] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
Hi @MarciMcGuireGCIO, I'm not sure we can implement a redirect on a file that lives in a directory we do not own. 

@kelsonic Can you take a look at this one and let us know if this is a possibility?

cc @brianalloyd

**Comment by MarciMcGuireGCIO** [comment]
@mnorthuis - thanks!  Please let us know what you find out.

**Comment by kelsonic** [comment]
@mnorthuis this seems definitely feasible! I'll send up a PR for it right now and see if I we can test it out on dev/staging to confirm. When does this redirect need to go out?

**Comment by MarciMcGuireGCIO** [comment]
Thanks @kelsonic!  It can go out as soon as feasible.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9598

**Comment by kelsonic** [comment]
Staging deployed, redirect seems to work as intended, deploying to production: https://github.com/department-of-veterans-affairs/devops/pull/9598

**Comment by MarciMcGuireGCIO** [comment]
🥳 Excellent!

**Comment by brianalloyd** [comment]
Nice work @kelsonic thanks for actioning and testing this for deployment.  @MarciMcGuireGCIO keep an eye on this and let us know if the redirect is preforming as intended once deployed to prod.  Thanks.

**Comment by MarciMcGuireGCIO** [comment]
Will do! Thank you!

**Comment by kelsonic** [comment]
Redirect is in prod: https://www.va.gov/vaforms/medical/pdf/vha-10-10ezrfill.pdf

**Comment by brianalloyd** [comment]
Hi @MarciMcGuireGCIO this should be completed, can you review and close once validated?  TIA.

**Comment by MarciMcGuireGCIO** [comment]
Hi @Brian! Looks great! Thank you!
