### ISSUE TITLE
Automate QA Builds

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#27521]
# Issue
As an engineer, I want to automate the building of the QA builds in order to get a regular distribution to our QA and development team. 

#ACs

- [x] update gradle files for Android to make naming and updating build numbers easier
- [x] add fastlane to android and ios directories and set up `qa` lanes for each
- [x] add global fastfiles for slack notifications
- [x] create a workflow that builds a QA for each operating system from circle CI every Wednesday and Friday at 5AM UTC.

**Comment by digitalken** [comment]
PASS 8/2/2021 - Seems to be working.  Closing.
