### ISSUE TITLE
Design Feedback - Midpoint Review [Caregivers, HCA-Self-Identifying Gender Identity]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#27558]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
The light gray text is something we currently do not use. Use an information callout box or bold the text instead for ALL light gray text. See Sketch/cards/feedback for example
- ![Screen Shot 2021-07-19 at 12.59.06 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/9eb7cce3-e715-40d7-91e2-cfb4c11a6c1b)
- ![Screen Shot 2021-07-19 at 12.21.15 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ef4af56e-359e-482e-88d7-0ed2ab5ec4da)

- Update the progress bar styling

- ![Screen Shot 2021-07-19 at 12.22.34 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/90d4ec6c-81da-46a7-bd1c-dc0229bdf04f)

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by Dene-human** [comment]
Thanks @allison0034 ! I would like to clarify the feedback.

1. The progress bar is consistent with the rest of the 10-10EZ form, we are just updating a couple of pages. Are you saying we need to update the whole application? If so, I think this may need to be a separate project.

2. In regards to the gray text, I've been working with @sshein and Danielle on ways to implement this additional information and we thought this might be a good chance to try out the hint text in the [Experimental design system](https://design.va.gov/experimental-design/hint-text). Can you please provide additional guidance around this? Thank you!

**Comment by allison0034** [comment]
@Dene-human 

1. It would need to be updated everywhere, so yes, a separate project would be fine to make that change.
2. Great! Can you follow the directions on [add an experimental design component](https://design.va.gov/experimental-design/#how-do-i-add-an-experimental-component-here)?

For tracking purposes, you do not need to implement the 2 must items I listed given these comments. Thank you!

**Comment by sshein** [comment]
isn't what's currently on the 1010ez our updated progress bar styling?
![Screen Shot 2021-07-19 at 11 56 21 AM](https://user-images.githubusercontent.com/3856611/126212531-4594833b-f6cd-4cd8-821f-ff9b2081daba.png)

**Comment by allison0034** [comment]
@sshein yep, that is it. So @Dene-human it looks as tho your prototype has the old one (blue circle), please update it to look like the current version

**Comment by sshein** [comment]
@Dene-human let us know if you were using a sketch template that needs an updated progress bar design

**Comment by Dene-human** [comment]
Oh! Apologies for the confusion. Birth sex and gender are up-to-date and marital status and race will also be updated in this scope. I know the sketch link has other designs that we are not working on in the workspace. The pdf is correct though. Attaching here for reference.
[10-10EZ SIGI update_7.16.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6843285/10-10EZ.SIGI.update_7.16.pdf)
