### ISSUE TITLE
CT Redesign: Update compare drawer styling on mobile

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27557]
As a developer, I need to update the compare drawer styling on mobile so that the component has good user experience and usability on mobile devices.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The breakpoint for mobile display is 481px ($small-screen).

## Acceptance Criteria:
1. The width of the compare drawer:
    a. Is the width of the institution cards in the name search results
    b. Is the same on name and location search
2. The elements in the compare drawer are stacked vertically in the following order:
    a. "You can compare 2 to 3 institutions" content
    b. Placeholder indicator / institution names
    c. Compare button
3. The height of the placeholder indicator is 40px.

## Supporting Artifacts:
1. [Mobile prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#/screens/296063401_Comparison_Drawer_0)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18036

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2097&group_by=cases:section_id&group_order=asc
