### ISSUE TITLE
Back to top z-index bug

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#27562]
## Issue Description
When the screen is sufficiently large and the back to top button is present, the button hides behind some components such as the footer (this is maybe intentional). It appears to always hide behind (some?) accordions (I believe this is not intentional) and potentially other components regardless of viewport width.

## Screenshot
![image](https://user-images.githubusercontent.com/12970166/126208091-da6b9698-3bf0-40ed-b931-46288fc29ad7.png)

**Comment by sshein** [comment]
validate that this is still true, it might not be true anymore.

**Comment by sshein** [comment]
@Mottie checked on this and it is no longer a thing we should close it

**Comment by Mottie** [comment]
Tested on https://staging.va.gov/decision-reviews/higher-level-review/

![Back to top button is above the accordion](https://user-images.githubusercontent.com/136959/183486057-04454498-9438-4eab-b8f8-859a5f3bdd2e.png)

**Comment by bkjohnson** [comment]
Before closing this I think it would be good to confirm that the `<va-back-to-top>` component doesn't have this problem [in the `gi` app](https://dsva.slack.com/archives/C0NGDDXME/p1626801341280500?thread_ts=1626701433.264600&cid=C0NGDDXME). If [this custom app component](https://github.com/department-of-veterans-affairs/vets-website/blob/2f066ac9927cdf9a82f3378805515966cd87daf8/src/applications/gi/components/BackToTop.jsx) can be removed and replaced with `<va-back-to-top>` without any issue then I think this would be good to close.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. f there is still an issue file a new bug.
