### ISSUE TITLE
[Epic] Pre-need improvements

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27578]
## Product Outline
[Pre-need](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/burials-memorials/pre-need)

## High Level User Story/ies

As a Veteran, I would like an error free experience on va.gov so I can submit my pre-need form 40-10007 online.

## Hypothesis or Bet

If we find & fix bugs, then we can reduce errors & increase customer satisfaction

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by MichelleDieudonne** [comment]
@Mottie We are a new team taking over PreNeed.  Are we able to request that you close this item?  We are already completing most of this work.  cc @ksantiagoBAH

**Comment by Mottie** [comment]
Oh, I knew that, but our team is still listed as a code owner; and, I didn't know if any one else would review this PR. If you would please remove our team from CODEOWNERS, I'd appreciate it. Thanks!

**Comment by MichelleDieudonne** [comment]
@Mottie thank you for closing this!  I just want to confirm I have the right team, we should be removing the team vsa-claims-appeals from CODEOWNERS, is that correct?

**Comment by Mottie** [comment]
Oh, I meant this line should change:

https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS#L55

Our team is `@department-of-veterans-affairs/benefits-team-1-frontend`
