### ISSUE TITLE
Create group emails for collaboration cycle meetings

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#27575]
## Issue Description
Create group email lists for design intent, midpoint and staging review to help when scheduling meetings for those touch points.

Edit 7/30/2021: Michael Fleet and Joe Niquette would like to explore Calendly, a scheduling application, for scheduling Privacy and Security Reviews. Platform Product Support will also research Calendly to see if it is a good option. This ticket may be unnecessary dependent on the outcomes of that research.

---
######  Design intent email group includes (design.intent@oddball.io):
  - [ ] Platform Collaboration Meeting
  - [ ] Shira 
  - [ ] Allison
  - [ ] Peggy
  - [ ] Ryan Thurlwell 
  - [ ] Randi Hecht
- People we will tag in the GH ticket with the Calendly link
   - Josh Kim (if VSA)
  - Angela Fowler (if VSA)
  - Other attendees listed in GH ticket
- We will post the Calendly link in the vsp-collaboration-cycle for
  - Beth Potts
  - Danielle Thierry
  - All others

######  Midpoint review email group includes (midpoint.review@oddball.io):
  - [ ] Platform Collaboration Meeting
  - [ ] Shira 
  - [ ] Allison
  - [ ] Peggy
  - [ ] Ryan Thurlwell 
  - [ ] Noah
  - [ ] Jim
  - [ ] Peter
  - [ ] Dariusz
- People we will tag in the GH ticket with the Calendly link
   - Josh Kim (if VSA)
  - Angela Fowler (if VSA)
  - Other attendees listed in GH ticket
- We will post the Calendly link in the vsp-collaboration-cycle for
  - Rachael 
  - Martha Wilkes 
  - All others

######  Staging review email group includes (staging.review@oddball.io):
  - [ ] Platform Collaboration Meeting
  - [ ] Shira 
  - [ ] Allison
  - [ ] Peggy
  - [ ] Ryan Thurlwell 
  - [ ] Noah
  - [ ] Jim
  - [ ] Peter
  - [ ] Dariusz
- People we will tag in the GH ticket with the Calendly link
   - Josh Kim (if VSA)
  - Angela Fowler (if VSA)
  - Other attendees listed in GH ticket
- We will post the Calendly link in the vsp-collaboration-cycle for
  - Rachael 
  - Martha Wilkes 
  - Joanne 
  - Lauren Simpson
  - All others

## Acceptance Criteria
- [ ] There is a group email list for design intent, midpoint and staging review
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
add content people to Design intent

add Josh, Angela and Tze possibly? Shawna too?

**Comment by shiragoodman** [comment]
VSA email group?

**Comment by shiragoodman** [comment]
Naomi? Beth? Danielle? Meg?

**Comment by allison0034** [comment]
@shiragoodman these group emails will need to have the oddball.io domain. Is that ok? I was thinking the following...

design.intent@oddball.io
midpoint.review@oddball.io
staging.review@oddball.io

**Comment by shiragoodman** [comment]
i think that would be fine. @andreahewitt-odd do we need to get special approval for creating an email group?

**Comment by allison0034** [comment]
@andreahewitt-odd I don't have access. Do you know who does?

**Comment by andreahewitt-odd** [comment]
@shiragoodman I also don't but I know @f1337 does

**Comment by allison0034** [comment]
@f1337 below are the emails and people we need:
### Design Intent email (design.intent@oddball.io):
 Platform Collaboration Meeting
shira.goodman@oddball.io
allison.christman@oddball.io
peggy@thesocompany.com
ryan.thurlwell@va.gov
rhecht@governmentcio.com

### Midpoint review email (midpoint.review@oddball.io):
 Platform Collaboration Meeting
 shira.goodman@oddball.io
allison.christman@oddball.io
peggy@thesocompany.com
ryan.thurlwell@va.gov
 noah.gelman@adhocteam.us
peter.hill@oddball.io
 darius.dzien@adhocteam.us

### Staging  review email (staging.review@oddball.io):
 Platform Collaboration Meeting
 shira.goodman@oddball.io
allison.christman@oddball.io
peggy@thesocompany.com
ryan.thurlwell@va.gov
 noah.gelman@adhocteam.us
peter.hill@oddball.io
 darius.dzien@adhocteam.us

**Comment by shiragoodman** [comment]
@allison0034 the midpoint and staging are the same people. Do we anticipate this changing? if not, do you think we could just have 1 group for both midpoint and staging?

**Comment by allison0034** [comment]
@shiragoodman I noticed that too but I thought having different emails would make this more flexible in the future.

**Comment by shiragoodman** [comment]
that's fair. Unless @f1337 has a reason why we can't or shouldn't do this, I am ok with a Staging and Midpoint group.

**Comment by f1337** [comment]
Are these groups intended to be used solely for Collaboration Cycle scheduling?

**Comment by allison0034** [comment]
@f1337 yes. I am trying to think if we would use them for anything else and I dont think so.

**Comment by allison0034** [comment]
@f1337 I added Jim.Ryan@adhocteam.us to the midpoint and staging emails. Please let me know when this is complete.

**Comment by allison0034** [comment]
@f1337 do you know when this will be complete?

**Comment by f1337** [comment]
My sincere apologies for the delay. Done. Please note the email format isn't *precisely* what was requested. We need to prefix Oddball group emails with some kind of context:

va.gov-design-intent@oddball.io
va.gov-midpoint-review@oddball.io
va.gov-staging-review@oddball.io
