### ISSUE TITLE
Create FE Tools Documentation Plan

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#27588]
## Narrative
Create a documentation plan for FE developer docs that detail where each type of documentation should live and why

## In Scope
Documentation the FE Tools team is responsible for maintaining

## Out of Scope
Documentation the FE Tools team is not responsible for maintaining

## Technical Notes
From Tim: “A micro vs macro documentation distinction could be helpful as well”

## Acceptance Criteria
- [ ] This plan should be either be added to this card as a comment or as a link to a google doc
- [ ] It should be clear from this plan where current documentation should live in the future
- [ ] This plan should be developed in consultation with the Content & IA team
- [ ] This plan should be reviewed and approved by the FE Tools PM and/or TL

**Comment by k80bowman** [comment]
@timwright12 @meganhkelley 

I've put together a draft plan for where different types of documentation should live. Would you mind taking a look at this draft diagram and let me know what you think? I'm trying to keep things as simple as possible. Once this diagram is finalized I'd like to add it to the FE Tools internal Confluence documentation.

![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/024f8645-0dd5-4f93-8760-f25336c8c6e0)

**Comment by k80bowman** [comment]
I was going back through the inventory and made a couple of edits.

![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/0109233e-7d7e-4725-828c-8e7f91a16840)

**Comment by meganhkelley** [comment]
This looks great so far! I agree that we will want to leave some documentation in vets-website and content-build, and as needed we can link to those resources from Confluence docs. 

Only other note is that I might make a case for moving decision docs -> operational docs sooner than later, but that is a wider Platform convo to have and we can proceed on our team without that decision (the decision about decision docs).

**Comment by k80bowman** [comment]
The priority is definitely going to be the Platform docs, so we have some time for any decisions we need to make around where the decision docs should live.
