### ISSUE TITLE
Access for [Ana Ricci]

### ISSUE THREAD

**Issue by anaricci** [department-of-veterans-affairs/va.gov-team#27582]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee Cecilia.Lee@va.gov
- Please provide your name.
   > Ana Ricci
- Please Provide your email.
   > ana.ricci@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name = Matsumoto
   > Company = Libertyits
   > Role =Product Manager

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyDxIGG7Oi3Jzrn3a8tCCpRiL5N+BNCGQ4j88dIS4Osef/7O0RyRI03M20xF78TnPIiUOYJGZkeTRMSLr5ecDSzhO4FG+QLLrYSMZOVY6Ymbnyr+3LPg3QYEnGcc5axNtvO1TAfJYr2Nr43vzJiBuchZwVLNtQNMsYTUZ4WBg8JvruqXu3LIY7BlDOxvFwgiYO/g80mA6NYHe7mNzFh8W9Lgc8gNIsvVj/5OTO6pjkFUyBMJzsvzaePpW8wPRZv/kLS4cz0cp6XR6CjUiMNhxI0JRNhWkRbPRU8azqR0MhywLtvqJT7BCkFTiBD4z3GmhCecrHu5bsLpeBIHPG/RSlutPVs157aMs2oOGwkGZ2mjVS1C0fGMg0fRKAZE4tXemFdzzfxDuhjVsRByTEgkZgFEY5zcI17UOwnRGaWmMo2qLxQenv9PvQ87wDNFsv6f8Ad81KUI7vIJ1RagiDjo/NSadGHo55jlzdNvnElYSuA5GZbLJYd6dPaqPii602Hac= AzureAD+AnaRicci@DESKTOP-R2DUCTJ
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
  > S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

**Comment by omgitsbillryan** [comment]
It looks like you were already given access https://github.com/department-of-veterans-affairs/va.gov-team/issues/25721

I'm a bit confused why you've opened another ticket using different GitHub account (`anaricci` V.S. `anaricci-va`)

**Comment by mchelen-gov** [comment]
this appears to be a duplicate, @anaricci @anaricci-va please reopen if needed
