### ISSUE TITLE
Outline Platform Site Documentation

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#27589]
## Narrative
Create an outline of the frontend developer documentation we would like to have on the Platform site.

## In Scope
Documentation the FE Tools team is responsible for maintaining

## Out of Scope
Documentation the FE Tools team is not responsible for maintaining

## Technical Notes
* This should include documentation we have and documentation that needs to be created

## References
Documentation requests to keep in mind:
* https://dsva.slack.com/archives/CQH357ZTP/p1617204274087700?thread_ts=1617203585.085900&cid=CQH357ZTP

* https://dsva.slack.com/archives/G01M8VD9USC/p1617205239110300?thread_ts=1617131713.102700&cid=G01M8VD9USC

## Acceptance Criteria
- [ ] Outline should be added to this card as a comment or a link to a Google doc
- [ ] Outline should be reviewed by the FE Tools PM and/or TL

**Comment by k80bowman** [comment]
@meganhkelley in the process of creating the plan for moving the documents and going through your notes in the spreadsheet, I've created a new outline diagram. I wanted to flatten things out more (have fewer subcategories). Thoughts?

![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/1486fea5-b713-4457-9def-9ecf914395a1)

**Comment by meganhkelley** [comment]
This looks good! The only one that stands out to me as causing minor confusion (for me) is the "Standards" bucket, but that might just be re: Row 37 in the spreadsheet which I know we want to check in about anyway. 

Let's do it!

**Comment by k80bowman** [comment]
Yes, I have a few I items in the spreadsheet I need to ask folks about. Thank you for reviewing!
