### ISSUE TITLE
IA Feedback - Midpoint review - Debt resolution, Medical copays

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#27586]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- On the copay bill details page, which CTA is the primary?  Based on link styles, it appears as those requesting help is the primary option and paying is secondary. 
- 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- The H1 of the existing static landing page for Pay your VA copay bills is different in the prototype than on the live site - the prototype has it labeled "Manage your VA copay bills".   This change needs to be confirmed with Sitewide content prior to implementation as it impacts the breadcrumb, URL and all existing entry points of the page that is already live. 
- The breadcrumb for the static landing page is incorrect, the page lives within Health care. The correct mobile version of the breadcrumb is " < Health care". 
- Align on terminology used and be consistent in headings and CTA labels - "copay bills" versus "copay balances".   Content refers to the ability to "view your copay bills" but primary CTA and the H1 of the tool is labeled as "copay balances".   
- Use consistent CTA label for "Request help with copay bills".  On the "copay balances" page, it is labeled as "Resolve copay bills"; on the copay details page the link label is "Request help...".  The link label must be consistent and should use the same language as the landing page. 
- The breadcrumb on the copay details page should match the H1 of the parent page.  Currently the H1 of the parent page is "Current copay balances".   This H1 needs to be finalized, then ensure consistent labels are used in the breadcrumb as well as link labels.  This will also feed the final URL. 

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by LindaLi123** [comment]
@mnorthuis Hello Mikki,  would you please confirm this feedback is for IA or for mid point review?  I know we are waiting for both at the moment.

**Comment by mnorthuis** [comment]
Hi @LindaLi123 This feedback is based on the review of the prototype provided for the midpoint review.  

IA recommendations are being worked on as part of this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25663

**Comment by rebeccawalsh** [comment]
@mnorthuis 
- **Drupal h1:** ✅ I've changed the prototype(s) back to 'Pay your VA copay bill' until we've decided whether or not to make it more similar to the debt portal's title.
- **Mismatched breadcrumbs:** ✅ I think I managed to get all of these straight - we just kept changing H1s, so it got a little mismatched :)
-**Bills vs Balance in CTAs:**   ✅ I believe these are resolved with the suggested content changes we got - balances can have multiple bills attached, so we primarily go with balance as an analogy for account.
- **CTA consistency:** ✅
- **Mismatched breadcrumbs 2.0:** ✅

**Comment by mnorthuis** [comment]
@rebeccawalsh Danielle and I met and worked through H1/breadcrumb labeling, it will be reflected in her content and my IA work.  All of these items will be resolved with that, so I'm going to close this issue.
