### ISSUE TITLE
CT Redesign: Add GIDS preview functionality to redesign sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27592]
As a developer, I need to add the ability to preview a new version to the redesign sandbox so that it maintains the same level of functionality as the current comparison tool

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The GIDS manager has the ability to preview the version of data in the redesign sandbox using a "Show redesign" action button.
    a. The URL of the sandbox preview is: https://staging.va.gov/gi-bill-comparison-tool-sandbox?version=xxxxx
2. The sandbox preview has all of the same functionality as a published version of the data.
3. The sandbox preview has an informational header (SA#1) informing the user that they are viewing a preview version.

## Supporting Artifacts:
1. Preview header:
<img width="1439" alt="Screen Shot 2021-07-20 at 11 10 38 AM" src="https://user-images.githubusercontent.com/48260534/126349029-a6515e02-7f9d-435e-a3c6-7d59fe58d2e5.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/849

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18110

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/9711

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2075)

**Comment by delli-gatti-michael** [comment]
Testing complete
