### ISSUE TITLE
Auto assign errors to relevant product team in Sentry

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#276]
## User Story

As a VSP engineer, I want Sentry to auto-assign issues to the relevant product team so I do not have to manually monitor and assign issues.

## Goal

When an error comes into Sentry, it is automatically assigned to the team that owns the product for which there is an error.

## Acceptance Criteria

- [ ] Each product has a routing rule defined in Sentry configuration
- [ ] All errors for a given product are collected with a tag reflective of the owner of each of those products
- [ ] Unmapped errors are handled appropriately
- [ ] Documentation of these changes are made in GitHub 

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
This _might_ require the new Sentry client to actually set a custom `application` tag, I'm not sure. I kind of doubt it, but it's worth mentioning.

**Comment by cvalarida** [comment]
Looks like the only options to auto-assign issue owners are `path` and `url`. `path` looks like it's the path to the file where the issue was triggered, so that may make the most sense. It's not perfect, since an app may call some code in `src/platform/` that may not trigger the `path` condition, but it's better than nothing.

**Comment by kfrz** [comment]
We have enabled assignment based on rules, however, Sentry 9 does not auto-assign. It simply suggests an owner based on rules. Auto-assignment is expected to work when Sentry 10 is deployed. 

Marking this issue as blocked in the meantime.

**Comment by erluti** [comment]
Sentry 10 deploy covers this issue
