### ISSUE TITLE
[MCP] Information Architecture

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27604]
## User Story

We need to setup configuration for breadcrumbs and URL entry point which will require us to add the shape to our application as well as the `content-build` repo and these PRs will need to be coordinated with each other as well as VSP. Since this will create a "chicken or egg" scenario  VSP will need to do a merge overwrite. 

## Expected Behavior

Bread crumbs and URL entry point are corrected and propagated across vets-website and `content-build`

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by craigwheeler** [comment]
IA tickets:

[IA Request Debt Resolution Team, Medical Copayments Tool (MCP)
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25663)

[IA Design and Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-copays.md)

**Comment by craigwheeler** [comment]
Sign in widget created and merged by PW https://github.com/department-of-veterans-affairs/va.gov-team/issues/32117 need to get with a member of the content team to implement the widget

**Comment by craigwheeler** [comment]
Verified the sign in widget has been implemented however there are still some updates from the content team to remove the info alert that is currently showing on staging

![Pay Your VA Copay Bill  Veterans Affairs 2021-11-19 14-57-51.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/a7cdd4f1-250a-4daa-8b10-3eebd028e3dc)
