### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#27609]
# Request Google Analytics

## User Email Address
**Please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `Analytics` in the "I need help from" dropdown, and add this issue's link and _add your email(s)_ in the "Summary of request."**
joe.niquette@oddball.io

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [ x] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

I am requesting access to google analytics for Identity/SSO purposes.

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
No hard date.

## Product Team / External Team / VA Office
VSP Identity

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@joeniquette You now have Google Analytics access! Please feel free to re-open this ticket if you have any problems getting logged in.
