### ISSUE TITLE
Authorize SSH keys for Barry Melton

### ISSUE THREAD

**Issue by barry-melton** [department-of-veterans-affairs/va.gov-team#27618]
# Instructions
1. Request for SSH keys be authorized
2. Barry Melton
3. DE-PMO
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Salvatore Granata
- Please provide your name.
   > Barry Melton
- Please Provide your email.
   > barry.melton@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Digital Experience (DE) PMO Support Team; Technical writer/analyst/admin support; FavorTech Consulting (FTC)

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCvVTZVkwcI5CGZ7QF9G3v+8uFRMmMe6MBnSW3K+thQLkuTyBEjZUT7Aw8bZM8YbsjbAB8S88mXa0+6iu/TfHRf6eaHjDS1AvhepytkoNJgDvTD4v23SzUzCL1IupdM577m2Bt7palFBcnudTAZSdSUXiMTXvDjZOGKgEw9YzEYDxAOoU9WpwRJM/qiMYg0eraDzMUk22wtmJwFljVCM+I1phwVPfxcP6pmjCkR0Q8YkPTwq2rTb48id0PDLNGW9WJCuRvWJF3Yg4oXB49R+eiHeaXuhHiBUiBm5/PngNWXaIcJaqtHayyBIbv3CX8W4Xa/YcnmdKt/WTfd4zYSYBD3smUdGE8WR70TKNQKWN42VFWfXXYRWiJt3+15wbmuZMD0SAiATLvMfpuhU87LPlKnAFFe6nirCZ1Wkmk3P4rqTPCQES0RWpxQQ+hqDZYlziaSrdr2lLhDdiFuwFf0PcrDLWHwYAXWY0OeZfiRfPngNtKGG018v0awTyLsv+57FM= OITNFLMeltoB@NFL-LT162094

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by barry-melton** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by omgitsbillryan** [comment]
I'm not seeing @barry-melton as part of the `department-of-veterans-affairs` GitHub organization. Going to hold off on providing SOCKS access until that happens.

**Comment by omgitsbillryan** [comment]
Relevant doc for being invited: https://github.com/department-of-veterans-affairs/github-user-requests/wiki/JOIN

**Comment by barry-melton** [comment]
When I click the link, I get a 404 message. Has this URL been updated? Thanks.

**Comment by omgitsbillryan** [comment]
Barry, do you have a work email? The email listed in the OP looks to be a personal one `barry.melton@gmail.com`

**Comment by barry-melton** [comment]
barry.melton@va.gov -- That's odd to because in my GH profile, I have my va.gov email as my primary.

**Comment by barry-melton** [comment]
***@***.*** -- That's odd to because in my GH profile, I have my va.gov email as my primary

Barry Melton (Contractor)
Technical Writer, FTC
Office of Information and Technology (OIT), Development, Security, and Operations (DevSecOps)
Enterprise Program Management Division (EPMO)
Benefits and Memorial Services Portfolio (BAM)
(904) 228-2940

From: Bill Ryan ***@***.***>
Sent: Tuesday, July 27, 2021 12:45 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Melton, Barry R. (Favor TechConsulting) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Authorize SSH keys for Barry Melton (#27618)


Barry, do you have a work email? The email listed in the OP looks to be a personal one ***@***.******@***.***>

-

**Comment by barry-melton** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCvVTZVkwcI5CGZ7QF9G3v+8uFRMmMe6MBnSW3K+thQLkuTyBEjZUT7Aw8bZM8YbsjbAB8S88mXa0+6iu/TfHRf6eaHjDS1AvhepytkoNJgDvTD4v23SzUzCL1IupdM577m2Bt7palFBcnudTAZSdSUXiMTXvDjZOGKgEw9YzEYDxAOoU9WpwRJM/qiMYg0eraDzMUk22wtmJwFljVCM+I1phwVPfxcP6pmjCkR0Q8YkPTwq2rTb48id0PDLNGW9WJCuRvWJF3Yg4oXB49R+eiHeaXuhHiBUiBm5/PngNWXaIcJaqtHayyBIbv3CX8W4Xa/YcnmdKt/WTfd4zYSYBD3smUdGE8WR70TKNQKWN42VFWfXXYRWiJt3+15wbmuZMD0SAiATLvMfpuhU87LPlKnAFFe6nirCZ1Wkmk3P4rqTPCQES0RWpxQQ+hqDZYlziaSrdr2lLhDdiFuwFf0PcrDLWHwYAXWY0OeZfiRfPngNtKGG018v0awTyLsv+57FM= OITNFLMeltoB@NFL-LT162094

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by barry-melton** [comment]
Hi Jeremy - When I open the link to the guide<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fblob%2Fmaster%2Fplatform%2Fengineering%2Finternal-tools.md%23configure-the-socks-proxy&data=04%7C01%7C%7Ca99ca5d788334a5ca08408d95298fc6e%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637631639302304786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C%2Bc80bAVIJdRaZG9P3SHR4ojQSMyL6PG9oREylE5%2Bmg%3D&reserved=0> and I click this link<https://github.com/department-of-veterans-affairs/devops/raw/master/ssh/config> in step one, I get a 404 code. I'm logged into GH and have access to the VA GH org. Am I doing something wrong?

V/R,

Barry Melton (Contractor)
Technical Writer, FTC
Office of Information and Technology (OIT), Development, Security, and Operations (DevSecOps)
Enterprise Program Management Division (EPMO)
Benefits and Memorial Services Portfolio (BAM)
(904) 228-2940

From: Jeremy Britt ***@***.***>
Sent: Thursday, July 29, 2021 9:59 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Melton, Barry R. (Favor TechConsulting) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Authorize SSH keys for Barry Melton (#27618)


SOCKS access granted. Please continue with the guide<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fblob%2Fmaster%2Fplatform%2Fengineering%2Finternal-tools.md%23configure-the-socks-proxy&data=04%7C01%7C%7Ca99ca5d788334a5ca08408d95298fc6e%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637631639302304786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C%2Bc80bAVIJdRaZG9P3SHR4ojQSMyL6PG9oREylE5%2Bmg%3D&reserved=0> to establish a connection to SOCKS proxy.

-

**Comment by jbritt1** [comment]
Nope, likely just a permissions issue. Let me dig a little further.

**Comment by jbritt1** [comment]
Since I don't know the ins and outs of your role I am hesitant to just go adding access to things. Mind if I email a copy of the guide and necessary SSH config to your VA email?

**Comment by barry-melton** [comment]
That's fine, thanks. The reason I need SOCKS access is to access Prometheus and Grafana for monthly Product Scorecard (PSC) reporting for products within the Digital Experience (DE) product line (VA.gov, BTSSS, MyHealthyVet, etc.

Barry Melton (Contractor)
Technical Writer, FTC
Office of Information and Technology (OIT), Development, Security, and Operations (DevSecOps)
Enterprise Program Management Division (EPMO)
Benefits and Memorial Services Portfolio (BAM)
(904) 228-2940

From: Jeremy Britt ***@***.***>
Sent: Thursday, July 29, 2021 10:47 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Melton, Barry R. (Favor TechConsulting) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Authorize SSH keys for Barry Melton (#27618)


Since I don't know the ins and outs of your role I am hesitant to just go adding access to things. Mind if I email a copy of the guide and necessary SSH config to your VA email?

-
