### ISSUE TITLE
Connect Redux to Detail Page Table

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27614]
## Technical Task
For the "Your charges and payments" section of the debt detail page we need to render copay balance data. The columns should be sortable by `Charge date` and `Description` with 1 additional un-sortable column for `Amount`. Refer to [mocks](https://preview.uxpin.com/18073b171729031ac0af64822d31a7427b012d66#/pages/139873793/simulate/sitemap?mode=i)

## Expected Behavior
Table renders correct data for copy details and has pagination with 6 items per page. Transaction Date and type are sortable ASC and DEC.

## Acceptance Criteria
- [ ] Table matches [mocks](https://preview.uxpin.com/18073b171729031ac0af64822d31a7427b012d66#/pages/139873793/simulate/sitemap?mode=i)
- [ ] Table is populated with copay detail data

**Comment by LinnJS** [comment]
This could almost be 3 task, make the table, make the table sort, then add pagination. Honestly this ticket might be a 13 not sure what tooling we have for this here. Feels very react-table-y.

**Comment by craigwheeler** [comment]
splitting into 2 tasks, 1 to implement the table component and another to wire up the data

**Comment by craigwheeler** [comment]
Table has been removed from MVP closing ticket
