### ISSUE TITLE
Quality Assurance Feedback - Midpoint Review - [Deb Resolution, Medical Copays]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#27626]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Please develop a draft test plan as early in the process as you are able to once the feature becomes well-defined and testable. Obviously the agile process is designed to accommodate small changes and stakeholder feedback all along, but a formal test plan helps to define what the team needs to verify is working before release. Please refer to this [list of artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md) that Platform requests for the QA area of the Collaboration Cycle.
- Are there any changes that need to be made to the relevant end-to-end test specs? We recommend planning out that change at this time.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
None

**Consider:**
None

**Comment by LindaLi123** [comment]
@pjhill Hello Phil, we haven't started building the application,  is there anything we need to do at the moment?

**Comment by pjhill** [comment]
> @pjhill Hello Phil, we haven't started building the application, is there anything we need to do at the moment?

Understood -- hopefully, you're at the point in your SDLC where you have defined discrete units of work (stories, acceptance criteria, requirements). Once there are acceptance criteria available for the change you are going to be integrating into the platform, you should be able to begin creating a test plan.

For example, do you have any prototypes that you have tested with users? I assume that at this point one of those prototypes has risen to the top of the stack as a candidate for the UI. It should be possible to begin to outline test scenarios that drive those prototypes from a user perspective. That could be the beginnings of your test cases. As your QA starts to work through those scenarios, it can also help the team understand and clarify acceptance criteria for those flows.

**Comment by leahkeeler** [comment]
@pjhill I am confused by above - Are you talking about usability testing or functional test cases? If it is usability, we can point you to that. If you mean functional use cases, we can provide you with test users that will be used and the associated stories such as A Veteran has co-pay debt,  A Veteran has no co-pay debt etc. I do not understand what purpose this will serve at this point of sdlc, as they will be the natural outcome of epic acceptance criteria a development is under way . Can you please elaborate?  Thanks

**Comment by pjhill** [comment]
> @pjhill I am confused by above - Are you talking about usability testing or functional test cases? If it is usability, we can point you to that. If you mean functional use cases, we can provide you with test users that will be used and the associated stories such as A Veteran has co-pay debt, A Veteran has no co-pay debt etc. I do not understand what purpose this will serve at this point of sdlc, as they will be the natural outcome of epic acceptance criteria a development is under way . Can you please elaborate? Thanks

@leahkeeler -- Sorry for the confusion, I am referring to functional / quality assurance testing. General information about QA on the platform is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance). Specific information about the artifacts requested as part of the QA process and when they are requested is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md).

A test plan and the test cases that make up that test plan help independently verify that the acceptance criteria defined by the user story / epic have been completed. At mid-point it is still quite early in the SDLC as you indicated! However, a test plan consisting of drafts or stubs of test cases that include some or all of the following types of tests is prudent -- functional tests, negative tests, acceptance tests, regression tests.

Additionally, planning out the modification or creation of an E2E test spec in Cypress that incorporates the changes you are proposing to the product can begin at this point in the SDLC.

At this point we only expect drafts or stubs of a test plan / test cases with the understanding that the agile SDLC prescribes small easy to integrate changes that incorporate stakeholder feedback throughout the lifecycle. We expect that test cases may require modification as the product evolves and responds to stakeholder feedback. However, at some point the product reaches a stable set of acceptance criteria that define the nature by which you plan to fulfill the business needs and interests of stakeholders.

The Platform requests a test plan and draft test cases at this point because we believe that it sets up the product team for success moving forward. If you and your team believe that you do not need a QA test plan at this point in the SDLC then that is your prerogative.

**Comment by LindaLi123** [comment]
Hello @pjhill I have a use case draft ready, please see attached. Is this what you are looking for? [https://app.zenhub.com/files/133843125/3d6b0506-4b24-40d4-8534-64099279d808/download](https://app.zenhub.com/files/133843125/3d6b0506-4b24-40d4-8534-64099279d808/download)

**Comment by LindaLi123** [comment]
Hello @pjhill did you get a chance to review my draft test users and use cases?  Pls let me know your comments

**Comment by pjhill** [comment]
> Hello @pjhill I have a use case draft ready, please see attached. Is this what you are looking for? https://app.zenhub.com/files/133843125/3d6b0506-4b24-40d4-8534-64099279d808/download

@LindaLi123 This looks like a great source document from which to generate some. Since this feedback was generated for a midpoint review, it seems like these use cases would translate almost 1 to 1 to some stubbed out test cases. Have you had a chance to log into our [TestRail instance](https://dsvavsp.testrail.io/)?

**Comment by LindaLi123** [comment]
@pjhill not yet, i just recently got access to testrail but not have used it yet,  please let me know what do i need to do.

**Comment by pjhill** [comment]
> @pjhill not yet, i just recently got access to testrail but not have used it yet, please let me know what do i need to do.

General guidance for TestRail and some examples are available on the Platform Website [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-use-TestRail.1600684126.html).
