### ISSUE TITLE
CT Redesign: Configure "Filter your results" component to work with search via the map

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27623]
As a developer, I need to configure the "Filter your results" component to work with the search via the map control so that an error is not encountered.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. When a search is executed via the map, the "Filter your results" are included when conducting the search.

#### Technical Note:
If you zoom in and search from the map with nothing in the search textbox, then try to refine your search it blows up. Refine your search only applies to searches from the search textbox for now. We need to add logic to track where the latest search was initiated and apply the filters accordingly.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18090

**Comment by delli-gatti-michael** [comment]
Adding functional label

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2050)

**Comment by delli-gatti-michael** [comment]
testing complete
