### ISSUE TITLE
[FSR] Payroll deduction list loop error handling bug

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#27638]
## Issue Description
There isn't error handling in the payroll deduction list loops. I can save payroll deductions:
- Without including a payroll deduction type and amount
- Adding a payroll deduction type but no amount
- Without including a payroll deduction type, but including an amount

### Screenshot of the payroll deduction list loop on test-user-1

![fsr-payroll-deduction-list-loop-bug.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/c8aa76d0-a6c7-4985-b21a-82bf94162b4f)

---
## Tasks
- [ ] _Add the error handling that's present on the other list loops_
Please reach out to Riley or Becca if you have questions about the error handling! 

## Acceptance Criteria
- [ ] _Error handling has been added to the payroll deduction list loops_

**Comment by denisecoveyduc** [comment]
Hey @rileyorr could you confirm, is this still an issue?

**Comment by josephrlee** [comment]
Closing this ticket as it's no longer relevant since this is from the deprecated list loop pattern.

cc: @mgleo , @denisecoveyduc , @Tom-Davis , @dhill802 , @charlottecesana
