### ISSUE TITLE
CT: Do not display unapproved schools in "School locations" section of profile pages

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27657]
As a developer, I need to remove the display of non-approved institutions from the "School locations" section of the profile pages so that institutions that are not approved for display are not shown in the comparison tool.

## Assumptions:
1. This work is to be completed in both the current comparison tool and sandbox.

## Acceptance Criteria
1. Only institutions with the following WEAMS poo status are displayed in the "School locations" section of the profile page:
    a. APRVD
    b. SUSP

## Supporting Artifacts:
1. Institution that displays a non-approved location: https://staging.va.gov/gi-bill-comparison-tool/profile/21015023
    a. Unapproved location: DEVRY UNIV- ST LOUIS PARK

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2126)
