### ISSUE TITLE
Document questions to populate Platform Website/ Collaboration Cycle/ FAQ page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#27653]
## Issue Description
VFS teams have many questions about the Collaboration Cycle and have DM'd Shira on several occasions to get direct responses. 

- How can I find out if an initiative needs to go through Collaboration Cycle?
- Can I skip a Collaboration Cycle touchpoint that was recommended during Kickoff?
- Do discovery efforts need to go through Collaboration Cycle?
- Do I need to have a Midpoint Review before usability testing?
- What if I don't have all the artifacts requested in the touchpoint template?
- Can I schedule a Collaboration Cycle meeting outside of the available timeslots?
- My team is doing more than 1 round of usability testing. When should I schedule Midpoint Review?
- Can I schedule multiple instances of the same Collaboration Cycle touchpoint?
- Does my team have to fix the issues identified at Staging Review?
- A launch-blocking issue was identified at Staging Review, but my team doesn't think it should be launch-blocking. Can I challenge the severity of the issue?

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
Recent questions --

> Hi @Peter Hill - How's it going? I have a couple of questions for you, I hope you don't mind.
> Would you happen to know if there some group / someone that could restrict permissions in ZenHub? i.e. Only Read permissions
> Could you or Joe Tice show us how automation for Comparison Tool is executed in Cypress? How many scripts execute? Repo? etc....  We would like to understand from a functional side how Booz Allan writes and executes their scripts.  Unfortunately last time we met with them they could not demo anything around functional automation and we would like to learn more.  Not sure if you are the right person.  Any help will be appreciate it!  Thanks!

**Comment by pjhill** [comment]
Another one --

> Hi Peter, I have question about QA testing on staging.va.gov - our QA says he is trying to log into GIDS, where he says the test data is located, using his PIV card and its not letting him in, he gets an certificate authentication error. Is there additional access that the testers need to get to the test data? Or should they actually be logging is with a test ID or some other way?

**Comment by 1Copenut** [comment]
* How do we handle accessibility issues that are design system or third-party dependencies?
* Why do we have to do foundational accessibility testing?
* How should I prioritize fixing accessibility issues?

**Comment by allison0034** [comment]
@shiragoodman should I add the question by Peter and Trevor? I am not sure Peter's are related to the Collab Cycle.

**Comment by shiragoodman** [comment]
yes to Trevor. No to Peter. @pjhill if you disagree, let me know. I agree with @allison0034 and I'm not sure if they're Collaboration Cycle specific. These might be questions for TTT, not us.

**Comment by allison0034** [comment]
[FAQ page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/FAQ's.1864073263.html)
