### ISSUE TITLE
Analytics Implementation or CMS Knowledge Base search keywords

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#27652]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

Implementation

- Who is this request for?

    - @kevwalsh , Product Manager CMS Product Support Team
   
     
- What team/project is this work for?
    
    - CMS team
    
- Provide the Domain where Google Analytics needs to be implemented
    
   prod.cms.va.gov_
    
    
- Please provide any upcoming deadlines or important milestones
    
   we'd like to launch the Knowledge Base search in the coming days, but next couple weeks would be fine, it's a soft launch

- Please provide website interactions to Track

   we want to track search keywords. 

![Search_CMS_Knowledge_Base___Veterans_Affairs](https://user-images.githubusercontent.com/643678/126413379-0b5eb797-474d-430e-b48d-c3ffbcc42633.png)

search at prod.cms.va.gov/help/search , which has just one parameter right now, which is `keyword`. eg `prod.cms.va.gov/help/search?keyword=video`

![Analytics_360](https://user-images.githubusercontent.com/643678/126413345-ee904cf8-19f4-4c6b-a330-9067dbecb144.png)

    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
in the future we may want to add additional parameters than just `keyword`, such as `product`. 

- Additional Comments

  I'm not too concerned about testing this extensively on staging first, but we can do that too, after PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5914 has been merged. 

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by kevwalsh** [comment]
CMS issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5920

**Comment by laurensimpson14** [comment]
Hi @kevwalsh I've enabled site search tracking for the CMS Prod view!
![image](https://user-images.githubusercontent.com/80417436/126518046-ae7fc09e-c75e-4336-bf94-f1ff2f26ade9.png)

However, I'm unable to QA since I get this screen when I visit prod.cms.va.gov or cms.va.gov: 
![image](https://user-images.githubusercontent.com/80417436/126518154-19f18770-bd4e-4497-9d5e-18a8adfdd05e.png)

Do you know how I can reach the site?

**Comment by kevwalsh** [comment]
@laurensimpson14 
Wow, that was fast, thank you!
You'll need to be on the VA network to access prod.cms.va.gov. But this won't even be testable until we deploy some code to CMSs, which may be tomorrow EOD, but may be as late as next week.

i'm happy to do the QA on this, and/or schedule some time with you that we can do it together if that makes sense. But consider the ball in my court for now?

**Comment by joanneesteban** [comment]
@kevwalsh hello! Analytics is going to close this ticket. Please feel free to reopen if you need additional support from us!
