### ISSUE TITLE
Fix typo in meta description in disability housing grants best bet

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#27658]
## Issue Description
The meta description for disability housing grants for Veterans has "service members" 1 word and capped instead of 2 words and lowercase in the top search result. This should be fixed. 

![Screen Shot 2021-07-21 at 9.35.26 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/631c0e66-6536-4a37-9af6-1a782475a7a2)

## Tasks
- [x] Update text to service members

## Acceptance Criteria
- [x] Service members is now lowercase and 2 words in best bet meta description

**Comment by johnhashva** [comment]
@RLHecht howdy -- this one is "fixed" and live.  Please validate and close ticket if a-o-k.

<img width="720" alt="Screen Shot 2021-07-21 at 10 34 31 AM" src="https://user-images.githubusercontent.com/63107147/126506911-4b444fe6-8e38-4f6d-9bcc-623b5800c58a.png">

**Comment by RLHecht** [comment]
Looks good! Thanks @johnhashva
