### ISSUE TITLE
(Due 7/23) Document instances of 911

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27668]
We have a priority need to review all placements and copy of our references to 911.

## Tasks
- [ ] Identify scenarios, pages, flows, etc when 911 is mentioned
- [ ] Screenshot messaging that includes 911

**Comment by jbalboni** [comment]
Found two instances:

When direct scheduling using today as your preferred date:

![Screen Shot 2021-07-30 at 2.57.35 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/f7433625-2613-4b59-9739-0dd79418750c)

Reason for appointment page in VA request and direct schedule flow
![Screen Shot 2021-07-30 at 2.56.58 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/a155ad54-e6e3-4d70-9a6d-a9427018c8f2)
