### ISSUE TITLE
Add MCP services to DevOps Downtime Config

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27662]
## Technical Task

We need to be able to schedule downtime for a particular service. But before we can use these services we need to add them to the DevOps config so we can use them on the FE as dependancies.

[DevOps Config](https://github.com/department-of-veterans-affairs/devops/tree/a4b5432061ae60a4f77952bbe5f668a1355ee007/ansible/deployment/config)

## Expected Behavior

All service dependancies for Financial Status Report are int he DevOps Config

## Acceptance Criteria

- [ ] MCP endpoint Dependency is added to DevOps Config

**Comment by denisecoveyduc** [comment]
This will roll over into Sprint 63 due to higher priority MCP fixes.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19766) where this work is being done

**Comment by LinnJS** [comment]
PR was merged
