### ISSUE TITLE
Add react-router VS react-router-dom imports to FE docs

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27666]
## Technical Task

When working on [Debt Letters Details Refresh bug#26974](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26974) I spent quite a bit of time trying to wrap our app in a BrowserRouter so we had routing memory to persist IDs across routes. But there was some tribal knowledge that was required and is undocumented as noted in this [slack thread](https://dsva.slack.com/archives/C5HP4GN3F/p1626789649382300).

We need to add this to the FE documentation so others in the future with this issue do not waste time on something that should really be documented.

## Expected Behavior

Documentation explaining how to use `react-router` VS `react-router-dom`

## Acceptance Criteria

- [ ] Documentation explaining how to use `react-router` VS `react-router-dom` in platform code

**Comment by craigwheeler** [comment]
doesnt appear to be an issue closing ticket
