### ISSUE TITLE
ScoreCard/Performance Dashboard - Iterate dashboard based on new user feedback

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2767]
## High Level User Story
As a VFS storyteller, I need easy to read VA.gov data in one place so I can deliver accurate stories to stakeholders to champion our work on VA.gov.

How might we iterate on the Thoughtworks discovery sprint dashboard?

## Hypothesis/(es)
**If** _we focus on storyteller-focused data_ **then** _we expect an easier way for VA.gov to be championed_.

## Assumptions
- We will have validated the Product Success Tool for VFS audiences
- Historical and offline data is available for our team to aggregate and leverage
- We will be able to identify and connect with stakeholders for other sources of VA data
- We will be able to get buy-in from other VA offices to report accurate data on a consistent cadence
- Storyteller audiences will use the Product Success Tool as a source of truth for VA.gov data

## Goals
Iterate on a veteran-facing dashboard based on our findings from the Product Success Tool.

### Links
[PST User & Discover Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/research/product-health-prototype)
[Thoughtworks Github Folder](https://github.com/department-of-veterans-affairs/vets.gov-status)
[Thoughtworks Google Drive Folder](https://drive.google.com/drive/folders/1P5P_-wZ68sDbvfhrJNsNfYhyy2bQF5Vv)

## Product Outline
[Product Success Tool Product Outline](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#)
[Product Success Tool Product Brief](https://docs.google.com/presentation/d/1sI32UbQRqpKqOhBT8lkUuOHgfD4UUkV2cd5Pzw1fP9w/edit#slide=id.g5ce1b6f7f4_0_19)

### Areas for Discovery
Who are the storyteller audiences and how will we provision access to them? What types of data are they looking for and what is the best format to deliver that data?

### VSP Objectives
`O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.`

### Key Results
- KR1: Increase in customer NPS				

## KPIs
- Number of recurring users
- Customer feedback

## Definition of Done
- [ ] Storyteller data has been iterated on based on PST findings & VA leadership feedback

**Comment by johnny-jesensky-adhoc** [comment]
VA.gov veteran-facing [Performance Dashboard](https://www.va.gov/performance-dashboard/) was created and being iterated on by the IIR Team. Closing this as part of backlog.
