### ISSUE TITLE
Limit concurrency when writing debug information

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#27670]
Discussed in [#25859](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/25859).

## Details
Currently we allow very high concurrency when adding debug information to Drupal pages. The only limit is the maximum number of open files allowed by the OS. Limiting concurrency to a lower number (10 files or so) speeds up this step significantly at 48k nodes. See the ticket linked above for more information.

## Definition of Done 
- [x] Concurrency is limited when writing debug information
 - [x] Before and after benchmarks are recorded here

**Comment by alexandec** [comment]
### Benchmarks

I tested the build at 48k nodes to check the elapsed time to add debug information. With the existing approach (unlimited concurrency), I added timing logic so I could get precise timing for the debug information step only. With the new approach I also added timing information. Then I performed multiple runs on GitHub Actions with each approach. Here are the average results:

**Without concurrency limit (existing approach)**
Average debug info time: 12m 38s
Average total content build time: 61 mins

**With concurrency limit (new approach)**
Average debug info time: 5 min 43s
Average total content build time: 54 mins

So the new approach saves about **7 minutes** of build time at 48k nodes on GHA.

I also extended the existing manual garbage collection so it runs during the debug info step. During my tests I found this kept total memory use (RSS) in check. With garbage collection turned off, additional memory use was significant on some runs.

**Comment by alexandec** [comment]
PR is here: https://github.com/department-of-veterans-affairs/content-build/pull/403

**Comment by theodur** [comment]
Nice work on this! I'm glad to see time being saved on that step. Did you have to do a lot of testing with different file numbers, or was 10 the obvious sweet spot?

Also, do you know if using streams vs using `writeFileSync` and `readFileSync` made a big difference in timing? I'm guessing it wouldn't since we're limiting to 10 files at a time.

**Comment by alexandec** [comment]
Thanks Theo! I tested with a few different concurrency settings both below and above 10, and 10 performed best. My assumption is that lower concurrency doesn't fully utilize the available disk performance, and higher concurrency overloads the disk. The optimal setting might even vary depending on the type of EC2 instance, but I don't know for sure.

I didn't test this implementation with streams, but yeah, I think performance and memory use would be similar with 10 concurrent files.

**Comment by alexandec** [comment]
PR is merged and this is looking good. Closing.
