### ISSUE TITLE
IA Feedback - Midpoint Review [Caregivers, Facilities Search on 10-10CG)

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#27674]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Breadcrumb does not accurately reflect location of the form.  The 10-10CG lives under family member benefits. The breadcrumb should be: Home > Family member benefits  > Apply for the Program of Comprehensive Assistance for Family Caregivers 
- Error handling is not currently included in description of functionality, ensure that all potential error scenarios are handled.  If you are planning user research, including a common error scenario may be helpful.  Examples of potential errors:
  - What if user clicks/taps "Search" button if the search field is null?
  - What if there are no results for the value entered in the search field?
  - What if there are no results within the distance selected?
  - User clicks/taps "Continue" without first selecting an item from the list

**Should:**

**Consider:**

**Comment by hdjustice** [comment]
Closing ticket - The team has decided on a different design, and will be going through a new Midpoint review.
