### ISSUE TITLE
[DISCOVERY] VA health chat

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27686]
## Problem to be solved
There are a growing number of ways for Veterans to connect with clinicians for health related needs. It may be confusing for Veterans to find the right one for their needs and/or differentiate between the tools. 

New options for contacting the VA are becoming available and need to be added to the VAMC pages. Before we can determine the right experience for Veterans, we need to understand both the individual options and the landscape

This issue is for the discovery effort for the **VA health chat** option

## VA health chat background
- SME: 
- Wilmington is one of the pilot sites
- National experience (open in browser or in app)
- **Live chat** with a clinician for issues such as
   - Medical advice for a minor injury or illness
   - Medication questions
   - Lab/imaging test results
- [VA health chat](https://mobile.va.gov/app/va-health-chat)

## Goal
Get clarity on which should be used when (from VA perspective) so that we can determine the best method for researching Veteran expectations about  their communication options and begin considering the best way to present the information that Veterans need 

## Questions 
- What is the right experience for Veterans?
- What do they need to know about each service?
- How is it different than the other options?
- Where does each option fit within the Veteran journey?
- What is the situation the Veteran is in when he/she uses the service?

## Tasks
1. Make contact with SME
2. Conduct informational interview
3. Document findings

## Acceptance criteria
- [x] Ready for joint synthesis (reflecting the other options listed in #26770)

Link to [health chat discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md) - Nick O

**Comment by nicko-amida** [comment]
@mmiddaugh In progress health chat discovery is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/health-chat-discovery.md)!
