### ISSUE TITLE
Dependencies from npm disrupted by TIC in GHA implementation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#27681]
## Details 

Network issues are preventing us from downloading npm packages in CI using GitHub Actions

Idea: use a private npm registry (?) — this sounds like a lot of work, how could we validate that it would actually work before we do it? And/or other ideas? Proxy the install request?

## Acceptance Criteria

- [x] No network issues while installing dependencies in CI in vets-website
- [x] No network issues while installing dependencies in CI in content-build

**Comment by oseasmoran73** [comment]
Adding link to slack convo https://dsva.slack.com/archives/C01U8EYHSEM/p1626879282038600

**Comment by oseasmoran73** [comment]
CAG/GFE is required to move forward with the next step.

The next step will be try pointing package.json at the nexus instance from CAG/GFE

https://dsva.slack.com/archives/C01U8EYHSEM/p1628618487000400?thread_ts=1626879282.038600&cid=C01U8EYHSEM

**Comment by oseasmoran73** [comment]
PR has been recently merged, will be observing

**Comment by oseasmoran73** [comment]
Stability seems to be present for `vets-website` and `content-build`. Trying a different registry with no caching on NEXUS side, due to FE Tools caching `node_modules` within GHA. In observation still.

**Comment by oseasmoran73** [comment]
After monitoring with new registry, it seems there is stability on install along with the retries should an error be encountered.
