### ISSUE TITLE
Fix error with moving the Medallia button container

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#27693]
Slack conversation - https://dsva.slack.com/archives/CBU0KDSB1/p1626874663336400

Error:

```
helpers.js:88 Uncaught TypeError: Cannot read property 'remove' of null
    at medallia-feedback-button.js:13
    at i (helpers.js:72)
```

Turns out the script I wrote executes before the Medallia script adds the feedback button container to the DOM.

PR to fix this - https://github.com/department-of-veterans-affairs/vets-website/pull/17949

Now it listens for the button container to be added to the DOM, then it moves it.

**Comment by pjhill** [comment]
PR merged -- things are looking good
