### ISSUE TITLE
CT Redesign: Set bottom limit on compare drawer and back to top controls

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27699]
As a developer, I need to set a bottom limit on the compare drawer and back to top controls so that they do not enter the area covered by the footer of the page.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The compare drawer does not enter the blue footer on the following pages of the comparison tool:
    a. Search Page
    b. VET TEC Profile Page
    c. IHL/OJT Profile Page
2. When closed, the compare drawer does not enter the disclaimer footer area on the search results page of the comparison tool.
3. When open, the compare drawer covers the disclaimer footer area on the search results page of the comparison tool.
4. When closed, the compare drawer does not enter the disclaimer footer area on the profile page of the comparison tool.
5. When open, the compare drawer covers the disclaimer footer area on the profile page of the comparison tool.
6. When the compare drawer is closed, the back to top button stops above the disclaimer footer area on the profile page of the comparison tool.

## Supporting Artifacts:
1. https://bahdigital.invisionapp.com/d/main#/console/14222703/296062587/preview
2. 
![image](https://user-images.githubusercontent.com/1094999/128414457-88882820-5def-4193-b14b-034586de52d7.png)

**Comment by dneel-bah** [comment]
Adding dependency on disclaimer footer story based on discussions with UX about the drawer stopping above the disclaimer footer instead of the va.gov footer.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18142

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2095)
