### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#27692]
# Request Google Analytics and/or Domo access

## User Email Address
zach.morel@gcio.com

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
ASAP

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
Hi @zacharymorel which tool(s) do you need access to (Google Analytics, Domo, BQ)?

**Comment by zacharymorel** [comment]
I am unsure what BQ stands for? 
CC: @MarciMcGuireGCIO 

However, I do need access to Analytics and Domo!

**Comment by laurensimpson14** [comment]
It stands for BigQuery - however I don't think you'll need access to that. I've given you Domo access - let me know if you have any issues getting logged in. To add an email to Google Analytics the email address needs to be linked to a Google account. I'm getting an error message that the email you provided is not linked. You can link it here: https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en

Once it's linked please let me know, and I can get you access to Google Analytics!

**Comment by zacharymorel** [comment]
> It stands for BigQuery - however I don't think you'll need access to that. I've given you Domo access - let me know if you have any issues getting logged in. To add an email to Google Analytics the email address needs to be linked to a Google account. I'm getting an error message that the email you provided is not linked. You can link it here: https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en
> 
> Once it's linked please let me know, and I can get you access to Google Analytics!

I've links zach.morel@gcio.com with a google account!

**Comment by laurensimpson14** [comment]
You should now have access. Please feel free to re-open this ticket if you have any trouble getting logged in.
