### ISSUE TITLE
Remove welcome modal

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#27694]
Originally worked on in #9677. We still show a welcome modal for new VAOS users:

![Screen Shot 2021-07-21 at 2.26.27 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/e176f173-ef46-465c-889b-9d469904544e)

We can go ahead and remove this modal.

## Acceptance Criteria

- [ ] Given fresh VAOS session, When user signs in, The welcome modal doesn't display

**Comment by laurenernest** [comment]
Confirmed welcome modal no longer appears in Staging. Closing ticket.
