### ISSUE TITLE
Resocialize style guide

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27696]
# User story

To come.

# Tasks

To come.

# Acceptance criteria

To come.

# Reference info

To come.

**Comment by lianilychee** [comment]
amy's super rough draft

---

Hi everyone! We've gotten a few questions recently about publishing your changes on the live Platform website. There are a couple of extra steps you need to take on the Scroll Viewport admin dashboard to make that happen. Here's our guidance about publishing your Platform website contributions.

**Comment by lianilychee** [comment]
thurs 7/22:
- Amy: 
  - focusing on this today and tmr; already have the list section
  - goal: finish by end of day Monday

**Comment by gmaciolek** [comment]
Goal: post announcement in Slack on Thursday

Task status:
- announcement copy ✅ 
- tweaks to the style guide to make for a better user experience (breaking up the Formatting and organization page into multiple pages, adjusting sections that we link to in the announcement to make sure they are clear and concise) = in progress

**Comment by gmaciolek** [comment]
3rd announcement was posted in #vsp-confluence channel with links to updated Style Guide
