### ISSUE TITLE
July 14th QA build crashes on initial login after onboarding screens on Android

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#27698]
## What happened?
I noticed that I'm able to repeat an issue with Androids crashing on the first run of the app just after the onboarding screens complete and the home screen displays.  I've repeated with a couple of different users, so it doesn't seem to be user specific.  I can log right back in (even just using biometrics) and all is fine.  
Seems to be Android only, not iOS.

See video clip of it happening below.

## Specs:
- Device: Tested on Motorola, LG, and Samsung Galaxy Note 9 (happened on every android I tried it on.)
NOTE:  Did not happen on iOS.

## Steps to Reproduce
- Initial run after installing on device.
- Log in and go through the onboarding screens.
- After landing on the home screen the first time, the app crashes.
- User is immediately able to log back in (even using biometrics) and all is fine on that run and those after.

## Desired behavior
App does not crash.

## Acceptance Criteria
App does not crash on initial run on device.

## Bug Severity
- 1 - Critical

## Linked to Story
n/a

## Screen shot(s) and additional information

https://images.zenhubusercontent.com/133843125/fcb1b061-232a-4c1b-946a-d6bc2112fe18/androidcrash.mp4

**Comment by lexicalninja** [comment]
likely connected to this
https://console.firebase.google.com/project/va-mobile-app/crashlytics/app/android:gov.va.mobileapp/issues/ae9411de0db6575a893d287f37b803c6?time=last-seven-days&sessionEventKey=60F8529502A50001695B43E203546EE6_1565871832502118244

**Comment by digitalken** [comment]
PASS 7/29/2021 - No longer able to reproduce.  Closing.
