### ISSUE TITLE
Organize Sentry projects to reflect VSP reality

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#277]
## Background

In Sentry, we have [19 projects](http://sentry.vetsgov-internal/settings/vets-gov/projects/). It looks like we're (VSP) really only using 6 of them—three environments for both website and API. (There's _some_ activity on the others, but I don't know if anybody is looking at them or doing anything with that information.)

In Sentry, we have three projects for each vets-api and vets-website. 

Sentry supports sending a specific environment context tag, so we don't need to have separate projects.

Here's an example [development event](http://sentry.vetsgov-internal/vets-gov/platform-api-development/issues/66406/?environment=development).

## Questions 
- How would this change the developer experience (DX)?
- What impact would this have on sampling rate (i.e. do we have per-project rates set?)
- How would this change be implemented on the front end?
  - ... on the backend?
- Are the rest of the projects being used by anybody?
- If not, should we remove them?
  - We're using Sentry self-hosted, so we don't have to worry about quotas, right?

## Acceptance Criteria
- [ ] Projects are identified to be used by a given team/members
- [ ] Projects properly implement environment switching (at least api/website)
- [ ] Teams are notified of any changes
- [ ] Changes are codified as infrastructure-as-code

**Comment by cvalarida** [comment]
It doesn't look like they're doing any _harm_ just hanging out there, but I want to make sure we're being deliberate about what we're keeping in there.

**Comment by kfrz** [comment]
I wouldn't mind striking any projects that aren't being actively used. Cleaner is better!

**Comment by alexpappasoddball** [comment]
7/1/19 Notes:
Who all is using these projects and are they worthwhile?
- No longer a discussion, what does it take to clean up the projects.

**Comment by kfrz** [comment]
OBE. Closing as we will re-configure projects in #12118
