### ISSUE TITLE
CT: Make tuition and fees learn more url open in a new browser tab

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27722]
As a developer, I need to make the link to an institutions tuition and fees informational page open in a new broswer tab so that the user can easily return to the comparison tool to resume their search.

## Assumptions:
1. Sandbox location: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The link in the "Qualifying for in-state tuition" modal opens in a new browser tab for the current comparison tool.
2. The link in the "Qualifying for in-state tuition" modal opens in a new browser tab for the sandbox comparison tool.

## Supporting Artifacts:
1. URL
<img width="799" alt="Screen Shot 2021-07-22 at 9 04 56 AM" src="https://user-images.githubusercontent.com/48260534/126643675-c7dbbe2e-8490-4748-b13a-0699f849a421.png">

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18201

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2106&group_by=cases:section_id&group_order=asc
