### ISSUE TITLE
Offboarding of Jonathan Nelson

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#27729]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Jonathan Nelson
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > jonathan.nelson@adhocteam.us; VSA; no longer on the program; AdHoc
- Please provide any type of access they may have and their GitHub username. 
  > ex: SOCKS, Pagerduty, Google analytics, ect.
  
 
## AC
 - [ ] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [ ] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [ ] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [ ] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [ ] Pagerduty access removed (if applicable) 
 - [ ] Datadog account disabled (if applicable)
 - [ ] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by joanneesteban** [comment]
@laurensimpson14 - no action for Platform Analytics (Google Analytics/Domo) necessary. Jonathan is currently on the Platform Crew.

**Comment by shiragoodman** [comment]
@jonathanjnelson FYI - may want to make sure your access to necessary Platform tools isn't revoked

**Comment by jbritt1** [comment]
Thanks to the team we were able to decide this one isn't really need to go further on the access removal as Jonathan is on the Platform Team and needs what remaining access he currently possesses. Thread for tracking/transparency: https://dsva.slack.com/archives/C03FECE9K/p1627568588059200
