### ISSUE TITLE
Analytics specs to track Short Form implementation in 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#27724]
## High Level User Story
As a Veteran applying for health care, I would like to expedite the HC application so I can complete it faster, remove blockers, and have less confusion.

## Goals
Once we rollout the "auto-qualify" feature we need to track changes in drop-off and submission rates.

## Acceptance Criteria
-[ ] Submit new page for Auth users to Analytics to add tracking
-[ ]  Submit new page for confirmation for the Unauth users
-[ ] Tracking confirmed to be in place for above items

**Comment by SKasimow** [comment]
@lzapson Hi Lisa - I think you mentioned you had the URLs for the new pages; can you point me to them? thx!
