### ISSUE TITLE
Update Privacy Policy on 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#27732]
## User Story

**As a** Veteran, **I want to** have accurate information on the Respondent burden and Privacy act.

## Acceptance Criteria

 - [ ] Update Privacy act statement with the content in the 10-10EZ paper form
 - [ ] Create FE ticket
 - _In the future_ write in plain language

**Please note:** This is the Privacy Act Statement located at the bottom of the[ Introduction page](https://www.va.gov/health-care/apply/application/introduction). The check box on the review page, "I have read and accept the privacy policy" links to the main [www.va.gov/privacy-policy/](https://www.va.gov/privacy-policy/) which is correct.

**Comment by Dene-human** [comment]
**OLD/current privacy statement** - has references to education benefits/ is not for HCA
![OLD/current privacy statement](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/f0c53c58-d39c-48d4-a1d6-c0f5c01c65eb)

**Comment by Dene-human** [comment]
@mlighdc I just spoke with Danielle and this is what we identified. I think you also mentioned something about "Terms & Service" - is this something separate or is the above what you were referencing?

CC: @tchrisdyer

**Comment by Dene-human** [comment]
@mlighdc @DanielleThierryUSDSVA @tchrisdyer


I just realized that the Privacy Act Statement for the 10-10EZ is different in staging and prod. [Prod](https://www.va.gov/health-care/apply/application/introduction) has the wrong education one, but [Staging](https://staging.va.gov/health-care/apply/application/introduction) has one that is broken down into sections.

Maybe we should use the staging one- it seems even better than the paper one. Thoughts?

**Comment by Dene-human** [comment]
### Paperwork Reduction Act and Privacy Act Information

**The Paperwork Reduction Act** of 1995 requires us to notify you that this information collection is in accordance with the clearance requirements of Section 3507 of the Paperwork Reduction Act of 1995. We may not conduct or sponsor, and you are not required to respond to, a collection of information unless it displays a valid OMB number. We anticipate that the time expended by all individuals who must complete this form will average 30 minutes. This includes the time it will take to read instructions, gather the necessary facts and fill out the form.

**Privacy Act information:** VA is asking you to provide the information on this form under 38 U.S.C. Sections 1705,1710, 1712, and 1722 in order for VA to determine your eligibility for medical benefits. Information you supply may be verified from initial submission forward through a computer-matching program. VA may disclose the information that you put on the form as permitted by law. VA may make a "routine use" disclosure of the information as outlined in the Privacy Act systems of records notices and in accordance with the VHA Notice of Privacy Practices. Providing the requested information is voluntary, but if any or all of the requested information is not provided, it may delay or result in denial of your request for health care benefits. Failure to furnish the information will not have any effect on any other benefits to which you may be entitled. If you provide VA your Social Security Number, VA will use it to administer your VA benefits. VA may also use this information to identify Veterans and persons claiming or receiving VA benefits and their records, and for other purposes authorized or required by law.

**Comment by Dene-human** [comment]
Danielle and I discussed that first step is updating it to be aligned with the paper form (above text). In the future she will work with the Privacy office to update to plain language.

**Comment by dat-gcio** [comment]
@Dene-human This one is ready too. Review instance [link](http://8970fb5a6bcdf782df9768c303e36f5f.review.vetsgov-internal/)

**Comment by Dene-human** [comment]
Also good!

**Comment by tchrisdyer** [comment]
Hi @mdewey sorry I was partially mistaken on this ticket. We had two separate tickets to update the content in Privacy Act modals which appears from links on the Intro pages for both the 10-10EZ and 10-10CG. The update for the 10-10CG is in production already, but this update for the 10-10EZ is still only in Staging. So that is another thing we need to push into Production with your help.

**Comment by mdewey** [comment]
This looks to be in the PR https://github.com/department-of-veterans-affairs/vets-website/pull/18089
