### ISSUE TITLE
Update Privacy policy on 10-10CG

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#27733]
## User Story

**As a** Veteran, **I want to** have accurate information on the Respondent burden and Privacy act.

## Acceptance Criteria

 - [ ] Update Privacy act statement with the content in the 10-10CG paper form
 - [ ] Create FE ticket
 - _In the future_ write in plain language

**Please note:** This is the Privacy Act Statement located at the bottom of the[ Introduction page](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction). On the review page, "I have read and accept the privacy policy" links to the main [www.va.gov/privacy-policy/](https://www.va.gov/privacy-policy/) which is correct.

**Comment by Dene-human** [comment]
Same problem on the 10-10CG as EZ ticket #27732 @mlighdc @tchrisdyer

**Comment by Dene-human** [comment]
### Privacy Act Statement

**The Paperwork Reduction Act:** This information collection is in accordance with the clearance requirements of section 3507 of the Paperwork Reduction Act of 1995. Public reporting burden for this collection of information is estimated to average 15 minutes per response, including the time to read instructions, gather necessary data, and fill out the form. Respondents should be aware that notwithstanding any other provision of law, no person shall be subject to any penalty for failing to comply with a collection of information if it does not display a currently valid OMB control number. Completion of this form is mandatory for individuals who wish to participate in the Program of Comprehensive Assistance for Family Caregivers.

**Privacy Act information:** VA is asking you to provide the information on this form under 38 U.S.C. Sections 101, 5303A, 1705, 1710, 1720B, 1720G, 1725 and 1781 in order for VA to determine your eligibility for medical benefits. Information you supply may be verified through a computer-matching program. VA may disclose the information that you put on the form as permitted by law. VA may make a "routine use" disclosure of the information as outlined in the Privacy Act systems of records, “Patient Medical Records --VA” (24VA10P2), “Enrollment and Eligibility Records --VA” (147VA10NF1), and “Veterans and Beneficiaries Purchased Care Community Health Care Claims, Correspondence, Eligibility, Inquiry and Payment Files - VA” (54VA10NB3) and in accordance with the VHA Notice of Privacy Practices. Providing the requested information, including Social Security Number, is voluntary, but if any or all of the requested information is not provided, it may delay or result in denial of your request for health care benefits. Failure to furnish the information will not have any effect on any other benefits to which you may be entitled. If you provide VA your Social Security Number, VA will use it to administer your VA benefits. VA may also use this information to identify Veterans and persons claiming or receiving VA benefits, and their records, and for other purposes authorized or required by law.

**Comment by dat-gcio** [comment]
@Dene-human Here is the review instance [link](http://8970fb5a6bcdf782df9768c303e36f5f.review.vetsgov-internal/)

**Comment by Dene-human** [comment]
Looks good to me!
