### ISSUE TITLE
Infrastructure Monitoring w/ Datadog - "one-sheet" style documentation with pertinent info needed access the service

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#27749]
## Description 

We want to provide a simple "one-sheet" style document that contains the key/pertinent information that developers need to access Datadog for Infrastructure Monitoring. We do not need to recreate all of the "how-to" information which is already provided by Datadog, but we want to make sure that people can easily find links to access the service and understand what capabilities to expect. 

The audience at this moment is platform crew developers.

Think of it as, If a platform engineer said: "How do I access Datadog?", we can say "GO HERE"

## Document should contain  
- [x] Summary of what it does
- [x] Quick overview of what is being monitored (ie all instances, containers, environments) 
- [x] Link to access the Datadog SaaS
- [x] "For the more technical types" - this is where it actually gets configured (TF / other repo)
- [x] Invite flow/expectations aka how to onboard (needs clarification) - We think this should be: 
  - [x] Make Team Leads (TLs) an admin (double-check that admins can't cause any disruption of service)
  - [x] Allow TLs to invite their team members
  - [x] Tell team member individual contributors (ICs) to request invite from TLs
- [x] **Background / resources section**
  - [x] Link to [product outline](https://vfs.atlassian.net/l/c/533ozNwF) 
  - [x] Link to existing Datadog how-tos 

## To discuss 
What do we want the invite/onboarding flow to look like? 
For context: **We are still figuring out the rollout plan**, so the goal is just to complete the documentation for now, and then roll out with this doc and additional comms. I think the plan will be a) platform crews first, then b) vfs developers, but need to shore up our messaging around the alerting functionality to expect as well as the fact that we are not porting over dashboards. Jesse to help with the clarification of the rollout plan. 

## AC 
- [x] Document published in Confluence

**Comment by jbritt1** [comment]
How do we want to link to this new documentation for the masses to easily locate?

**Comment by jbritt1** [comment]
Where does this "best fit" in our Confluence documentation hierarchy? My current thought is a doc titled "Get Acquainted with Datadog" under the "How do I..." section. Could be persuaded otherwise though.

**Comment by jbritt1** [comment]
Who do we want to own the responsibility of inviting new members? Operations team with formal access request template for Datadog? Or team leads with admin roles to invite their own team members?

**Comment by jbritt1** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/1775435805/Get+Acquainted+with+Datadog

**Comment by jhouse-solvd** [comment]
Let's figure out if we need to link that up here, or create a new one in Confluence? 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/f4026d31bca3bec71d4b60ad6be96f441ad48878/platform/engineering/internal-tools.md

**Comment by jbritt1** [comment]
Ready for review / feedback: https://vfs.atlassian.net/wiki/spaces/OT/pages/1775435805/Get+Acquainted+with+Datadog

**Comment by jhouse-solvd** [comment]
I think this is good to go. I think we can open a new ticket if we decide to do a round of improvements. 

Closing.
