### ISSUE TITLE
Links to unpublished staff profiles

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27755]
## What happened?

An unpublished staff profile for David Brimmer was linked to from `new-jersey-health-care/programs/communications-and-outreach` which caused a broken link.  The profile has since been published, resolving the broken link

<details>
<summary> Screenshots</summary>

![image](https://user-images.githubusercontent.com/55411834/126678529-958c48ea-4bbb-4b36-a9f8-e25903a57d5a.png)

![image](https://user-images.githubusercontent.com/55411834/126679933-cf5bc2fe-c137-44d4-9b86-a5dfda8f8ec6.png)

</details>

## Additional information
- Drupal node 27395
- This issue was previously addressed in Staff list showing unpublished content #24708

## Acceptance Criteria
- [ ] Do not include information from unpublished staff profiles (withhold all from front end)
- [ ] ~Null entries for fieldLeadership produce no html.~
- [ ] Anchors are not built if no href is present.

## Testing Plan
Use tugboat. Unpublish a staff profile, release content from `vamc-unpublished-staff-profiles-27755 `branch, confirm unpublished profile does not render.

**Comment by mpelzsherman** [comment]
Confirmed by using tugboat to publish off master with an archived staff profile on new-jersey-health-care/programs/communications-and-outreach. Closing.
