### ISSUE TITLE
List of medical facilities for HCA and other forms needs update

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2775]
@patrickvinograd commented on [Fri Jul 28 2017](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4119)

HCA builds a list of possible VA medical facilities from a list in vets-json-schema. This list was provided by a contact in VHA from a list of then-currently-active facilities, but has not been updated in a while. 

Other forms will need a similar list.

We happen to have a regularly-updated list of VHA facilities in the form of the data that feeds facility locator. VHA updates their canonical VAST database quarterly and these updates are supposed to get pushed to ArcGIS and from there to facility locator on the same frequency. 

At minimum we can update vets-json-schema on a more regular basis. Alternatively we could build a inter-app-oriented API into facility locator that would let all forms get the lastest data programmatically. 

Before doing the above we should confirm with business owners that the same filter that was used originally is effectively the same as what is getting put into facility locator. Certainly facility locator is only supposed to show active facilities. But we should make sure there weren't any other conditions that apply here, e.g. there may be some VHA facility types in FL that don't work for HCA.

Note this won't be a cure-all - sometimes facility locator data is stale or incorrect - but it will make it so we only have to fix data problems in one place. 

---

@patrickvinograd commented on [Fri Jul 28 2017](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4119#issuecomment-318770098)

https://dsva.slack.com/archives/C0ETYFY31/p1501271186926657

---

@NatalieEMoore commented on [Thu Dec 07 2017](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4119#issuecomment-350081710)

@patrickvinograd any update on this?  is this for kudos or rainbows? cc @BBarone1 

---

@NatalieEMoore commented on [Tue Aug 07 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4119#issuecomment-411247144)

@rtluu can you look into this one?

**Comment by mmiddaugh** [comment]
@jellis-gcio can you please review this and see if this still still relevant and/or has any role in the data discrepancies you're investigating? Thanks!

**Comment by davidconlon** [comment]
@mmiddaugh Did we ever determine if this was still relevant? I'm not sure if this is ours or for lighthouse.

**Comment by mmiddaugh** [comment]
I think we still need to learn more to determine where this belongs, @davidconlon
