### ISSUE TITLE
27739: Update access to Google Analytics for the VSA Debt Team

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#27751]
# Update access to Google Analytics for VSA Debt Team

## What this form is for
Users are currently still given access to GA using the old format and should be updated to use the new first.last@gcio.com email format

## User Email Address
**Please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `Analytics` in the "I need help from" dropdown, and add this issue's link and _add your email(s)_ in the "Summary of request."**

The following VSA Debt Team members should be updated to use the new first.last@gcio.com email format:

- cwheeler@governmentcio.com -> craig.wheeler@gcio.com
- jlinn@governmentcio.com -> justin.linn@gcio.com
- lkeeler@governmentcio.com -> leah.keeler@gcio.com
- triser@governmentcio.com -> troy.riser@gcio.com
- kmircovich@governmentcio.com -> kevin.mircovich@gcio.com
- lli@governmentcio.com -> linda.li@gcio.com

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
_Please share the date you require access._

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@craigwheeler I got you added, but I was not able to add the following email addresses since they are not linked to a Google account: 
- justin.linn@gcio.com
- leah.keeler@gcio.com
- troy.riser@gcio.com
- kevin.mircovich@gcio.com
-  linda.li@gcio.com

Those emails can be linked by following the instructions here: https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en
Once linked please let me know, and I can get them access to Google Analytics!

**Comment by craigwheeler** [comment]
Hi @laurensimpson14 👋  ... i've been advised that everyone on the list has now linked their google accounts and should be good to go lemme know if you run into any issues... thanks!

**Comment by laurensimpson14** [comment]
@craigwheeler Wonderful! Everyone now has access to both Google Analytics and Domo through their gcio.com email addresses. I'll be removing access for everyone from their old email addresses. Please feel free to re-open this ticket if anyone has trouble getting logged in.
