### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#27769]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
**Please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `Analytics` in the "I need help from" dropdown, and add this issue's link and _add your email(s)_ in the "Summary of request."**
nichole.harris@libertyits.com
mark.viterna@libertyits.com

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [X] Google Analytics
- [X] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._
N/A

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
No specific date needed. Whenever it is comfortable to provide we will be thankful. :) We want to monitor how improvements implemented in the Forms API are improving the refinement rate for Forms Searches on VA.Gov, and try to identify additional opportunities over time. 

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._
Lighthouse Program - Matsumoto Team supporting the Forms API and the Benefits Intake API

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
Hi @NCHLiberty I've given you Domo access - let me know if you have any issues getting logged in.

To add an email to Google Analytics the email address needs to be linked to a Google account. I'm getting an error message that your VA email is not linked. You can link it here: https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en

Once it's linked please let me know, and I can get you access to Google Analytics!

**Comment by NCHLiberty** [comment]
hi Lauren. The corporate email account that is linked to a google account is Nichole.Harris@Libertyits.com. I believe this same email is what was used when request/setup was done for socks, aws console etc. It says[ in these instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/analytics-request-guide.md#requesting-access-to-google-analytics) "corporate or va email" so I figured i was on the right track. Let me know if this is off track. Thanks!

**Comment by NCHLiberty** [comment]
Also, fyi this request is for two people. Just wanted to make sure you saw Mark's email as well.

**Comment by laurensimpson14** [comment]
Thank you for clarifying @NCHLiberty! 🙂 I've now added both you and Mark to Domo and Google Analytics. You should receive a welcome email from both. Please feel free to re-open this ticket if either of you have any trouble getting logged in!

**Comment by NCHLiberty** [comment]
Thanks!
