### ISSUE TITLE
526 Notify user when missing DOB

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#27760]
EVSS  requires a DOB for 526 submissions: [EVSS - Veteran must have DOB #27374](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27374)

Date of birth has always been required, but it's new information to va.gov. 

When attempting to create a new 526 claim, users with a missing DOB will get the following error message:

![image](https://user-images.githubusercontent.com/865014/126690230-ad9afe4a-5fa9-4cd7-8bd7-8e5a7c4d4a17.png)

Should we consider modifying the above notification to inform the user that there is an issue with their DOB:
~"Please Call......Tell the representative that you may be missing your DOB"

We already have specific text around a missing id(I was able to trigger by signing in with staging user vets.gov.user+0@gmail.com):

![image](https://user-images.githubusercontent.com/865014/126691807-c2b9644a-d092-428f-a459-4c6c50054aed.png)

In the API, 526 requires: user.edipi AND user.ssn AND user.birls_id AND user.participant_id AND user.birth_date, might want to consider a gui with a more info accordian and have messaging around each missing required field.

**Comment by kevinstachura** [comment]
We have collaborated with Beth to create this copy for the error message:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/27986#issuecomment-891260505

A PR related to this ticket is already out 🤘
