### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#27763]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
**Please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `Analytics` in the "I need help from" dropdown, and add this issue's link and _add your email(s)_ in the "Summary of request."**

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [X] Google Analytics
- [X] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
July 23, 20201
 
## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

Education Benefits Application / Booz Allen / VA Education Service & OIT

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@amyknox your bah.com email address already has access to both GA and Domo - do you need access through a different email address?

**Comment by amyknox** [comment]
Hi @laurensimpson14 

Need it for someone else: Bill Spruce.  I was waiting until I heard back from him that he had linked his VA email to a google account before officially submitting this in the /support wizard on slack.

**Comment by laurensimpson14** [comment]
@amyknox Bill now has access to both Google Analytics and Domo! He should receive a welcome email. Please feel free to re-open this ticket if he has any trouble getting logged on.
