### ISSUE TITLE
Triage top 5 FE Sentry errors and recommend remediation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#27767]
## Details 

There's a lot of noise in [Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/). Also, Sentry has been hiccuping lately — [recent comms](https://dsva.slack.com/archives/CE4304QPK/p1626367481318500)

How might we clear out some of the most common errors in Sentry to decrease the load on the system and also decrease the noise that humans need to filter out?

## To Do

- [x] Identify top 5 FE Sentry errors 
- [x] Investigate each one
- [x] Recommend solution — could entail... 
   - [x] Triage to another team
   - [x] FE Tools fix (new ticket)
   - [x] Stop the reporting by changing the threshold or similar

**Comment by timwright12** [comment]
Top 5 Sentry Errors:

- [Validation issue not displayed](http://sentry.vfs.va.gov/organizations/vsp/issues/241/?project=4&query=is%3Aunresolved&sort=user&statsPeriod=14d) Users: 3.9k, Events: 65k
- [TypeError: Failed to fetch](http://sentry.vfs.va.gov/organizations/vsp/issues/41984/?project=4&query=is%3Aunresolved&sort=freq&statsPeriod=14d) Users: 121 , Events 939k
- [Blocked 'script' from 'resource.digital.voice.va.gov ](http://sentry.vfs.va.gov/organizations/vsp/issues/29641/?project=4&query=is%3Aunresolved&sort=freq&statsPeriod=14d) Users: 154k, Events: 497k
- [Origin https://www.veteranshealthlibrary.va.gov is not allowed...](http://sentry.vfs.va.gov/organizations/vsp/issues/84/?project=4&query=is%3Aunresolved&sort=freq&statsPeriod=14d) Users: 47k, Events: 421k
- [TypeError: Network request failed](http://sentry.vfs.va.gov/organizations/vsp/issues/463/?project=4&query=is%3Aunresolved&sort=freq&statsPeriod=14d) Users: 4.5k, Events: 101k

**Comment by timwright12** [comment]
## Validation issue not displayed 

### Issue URL

http://sentry.vfs.va.gov/organizations/vsp/issues/241/?project=4&query=is%3Aunresolved&sort=user&statsPeriod=14d

### Report URL: 

https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit

### Events 

65k

### Users 

3.9k

### Investigation

This issue seems to show up later in the submission process on the review step. I can't get there reliably on staging. Reached out to Design System for proper routing of this issue to see if is a forms issue or app issue. Recommended to push it over the to app team.

### Action

Assigned to va-benefits-memorials-1 via Sentry

**Comment by timwright12** [comment]
## Blocked 'script' from 'resource.digital.voice.va.gov 

**Issue URL**
http://sentry.vfs.va.gov/organizations/vsp/issues/29641/?project=4&query=is%3Aunresolved&statsPeriod=14d

**Report URL**
https://www.va.gov/claim-or-appeal-status/

**Events**
497k

**Users**
154k

**Investigation**
Found the template that is loading the resource. I wasn't able to replicate the error but can see how it would be blocked for some users. From there I found the CSP in devops and made the update.

**Action**
Opened PR to update CSP and add the blocked URL https://github.com/department-of-veterans-affairs/devops/pull/9645 - will mark as "resolved in next release"

**Comment by timwright12** [comment]
## Blocked 'connect' from 'events.mapbox.com'

**Issue URL**
http://sentry.vfs.va.gov/organizations/vsp/issues/6460/?project=4&query=is%3Aunresolved+is%3Aunassigned&sort=freq&statsPeriod=14d

**Report URL**
https://www.va.gov/find-locations

**Events**
19k ( after Sentry clear-out issue)

**Users**
13

**Investigation**
Discovered the offending resource and added to CSP

**Action**
Opened PR to update CSP and add the blocked URL https://github.com/department-of-veterans-affairs/devops/pull/9645 - will mark as "resolved in next release"

**Comment by timwright12** [comment]
## TypeError: Cannot call method "addEventListener" of null 

**Issue**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27903 

**Report URL**
http://vhl.staywellsolutionsonline.com/Resources/VideoLibrary/?e=0#landing

**Investigation**
The Sentry issue was lost in the data dump EKS bug, but the reported URL was still active so we debugged it and found where the error needed to be corrected https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/home.html#L119

**Action**
Kelson Adams submitted a PR to fix
PR: https://github.com/department-of-veterans-affairs/content-build/pull/399

**Comment by timwright12** [comment]
## Origin https://www.veteranshealthlibrary.va.gov is not allowed... 

**Issue URL**
http://sentry.vfs.va.gov/organizations/vsp/issues/84/?project=4&query=is%3Aunresolved&sort=freq&statsPeriod=14d

**Report URL**
https://www.veteranshealthlibrary.va.gov/

**Events**
421k

**Users**
47k

**Investigation**
Looked around in the devops repo for where the teamsites are set to be allowed and updated the list.

**Action**
Updated allowed origins list in devops https://github.com/department-of-veterans-affairs/devops/pull/9647

**Comment by timwright12** [comment]
# - [Blocked 'frame-src' from 'www.youtube.com'](http://sentry.vfs.va.gov/organizations/vsp/issues/5227/?project=4) 

**Issue URL**
http://sentry.vfs.va.gov/organizations/vsp/issues/84/?project=4&query=is%3Aunresolved&sort=freq&statsPeriod=14d

**Report URL**
https://www.veteranshealthlibrary.va.gov/

**Events**
17k

**Users**
19

**Investigation**
Just another CSP issue

**Action**
Updated CSP rules: https://github.com/department-of-veterans-affairs/devops/pull/9648/files

**Comment by timwright12** [comment]
Cleared ~30 misc. CSP issues including:
https://github.com/department-of-veterans-affairs/content-build/pull/402
