### ISSUE TITLE
Create a post-migration guidance message on migration script transformers

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#27785]
Create a post-migration guidance message on migration script transformers when there isn’t an easy way to automate migrating some edge cases.

This is a follow up from retro.

**Comment by bkjohnson** [comment]
@k80bowman do we want to close this now that we're going in the linting direction instead of a separate script?

**Comment by k80bowman** [comment]
Yep, closing now. Thanks.
