### ISSUE TITLE
Refactor DebtDetails by fetchingDebtById

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#27789]
## Technical Task

When working on [Debt Letters Details Refresh bug#26974](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26974) I had to create a workaround where I stored a derived debtId by concatenating fileNumber and  deductionCode from the debt.

We had to do this since debt does not have a unique Id and then we have to add the ID to every debt then filter on that derived id. We did it this way because we did not have an endpoint to just get one debt at a time by a BE provided id.

Once the BE is creating unique ids and is providing an endpoint to fetch one debt at a time we need to refactor this work since it's not performant to do so on the FE.

*Might need to refactor the entire app including the `<DebtWrapper />` component* not sure if that is the best and most performant way to be fetching this data. 

## Expected Behavior

On the debt details page we are fetching a single debt from the backend and persisting it via URL state.

## Acceptance Criteria

- [ ] Debt letters fetches single debt at a time
- [ ] Debt is persisted on refresh

**Comment by HeatherRienks** [comment]
FYI - per @denisecoveyduc - this is an old ticket. We are NO longer displaying debt letters on the portal.

**Comment by HeatherRienks** [comment]
Per Backlog Refinement on 5/1/24, we will close this ticket and create a new ticket for this effort.
