### ISSUE TITLE
BDD - Dependency Prompt

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27781]
## Issue Description
Create prompt to complete form 686

---
## Tasks
- [ ] Develop language to direct Veteran to complete dependents form after BDD submission

## Acceptance Criteria
- [ ] Documented language
---

**Comment by kevinstachura** [comment]
Reached out to Kevin Hillegas on 8/19 to see if there was any particular copy he'd like to see on there - still waiting on a response. I have something preliminary but would rather run it by the SME first, before sending over to content team / Beth.

**Comment by kevinstachura** [comment]
Kevin H. responded back today with some suggested copy, which has been put into a mockup:

<img width="441" alt="Screen Shot 2021-08-24 at 4 14 56 PM" src="https://user-images.githubusercontent.com/54544300/130683696-97d43ca3-81b9-48de-8816-cde3533b42bd.png">

When I clean up this massive BDD Sketch file, I will also upload it to Sketch for Teams so we have it there.

At this point the only thing left is running copy past Beth so she can refine. That will be a content request ticket. Closing this as all acceptance criteria has been met.
