### ISSUE TITLE
CT Redesign: Compare length of school overlapping 

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#27795]
## Steps to reproduce: 

Compare these 3 schools

![Screen Shot 2021-07-23 at 1.40.29 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b05e2141-3828-4bb0-8542-ae8f2928814d)

## Expected behavior:

Does not overlap

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18000

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
