### ISSUE TITLE
General Analytics Request for Platform Content/IA

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27792]
# General Analytics Request

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- n/a Analytics to Track Down
- n/a Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Liani Lye
    
- Platform Content/IA team; Platform website KPIs
    
- What type of analytics support are you looking for?
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    
## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

Before EOS 57, aka before 8/3

## Other Helpful Questions to think through
n/a

## Link to Metrics
n/a

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

Hello - I have some questions about specific metrics in y'all's [Data dictionary: VA.gov Content KPIs](https://vfs.atlassian.net/wiki/spaces/APM/pages/1651867793/Data+dictionary+VA.gov+Content+KPIs):

- _I'll be formatting my questions as: Category > Metric: Question_
- **Finding the page > top sources:** What does "previous page" show when the content page is accessed via a bookmark?
- **Anchor links > total anchor link clicks:** Does this show _which_ anchor link is clicked?
- **Anchor links > total anchor link clicks:**  Let's say Page X and Page Y have anchor links X1 X2 X3 and Y1 Y2 Y3 respectively. Situation 1: We're on Page X and click on X1.  Situation 2: We're on Page X and navigate to Y1.  Would situations 1 and 2 be reported in aggregate, or is a situation excluded?

Thanks in advance!

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@lianilychee are you able to attend one of [our office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport) to discuss this?

**Comment by lianilychee** [comment]
@joanneesteban yes, I'll move my cal around - thanks for the reminder!

**Comment by joanneesteban** [comment]
@lianilychee - hello! Do you need anything additional from our team for this?

**Comment by lianilychee** [comment]
@joanneesteban - nope!  Chloe answered my q, so I am good.  I will close this ticket.
