### ISSUE TITLE
CT Redesign: Update display of compare page for mobile displays

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27797]
As a developer, I need to update the display of the compare page so that it displays in a usable manner for users of the tool on mobile devices.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The breakpoint for mobile display is 481px ($small-screen).

## Acceptance Criteria:
1. The initial content displayed on the page, after the breadcrumb, is:

    > **GI Bill® Comparison Tool**
    > 
    > Use the GI Bill Comparison Tool to see how VA education benefits can pay for your education.
    > 
    > **School Comparison**
    > 
    > View school information side by side to compare schools
    >
    > [ ] Highlight Differences

2. The cards with the institution name and location are horizontally scrollable.

3. All of the content below the cards and arrow controls is displayed as rows.
    a. The section headers
    b. Table row labels
    c. Table row institution data

4. When the user horizontally scrolls:
    a. The section header rows do not move (ex. Summary, Your estimated benefits, etc.)
    b. The table row labels do not move (ex. Accreditation, GI Bill students, etc)
    c. The table row institution data moves in unison with the institution card header
    d. When an institution card header is fully in view, the dot indicator is updated to indicate that is the card being viewed.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222763/296063829/preview)
2. Home Depot Mobile Webpage - Refrigerator Comparison is a good example of desired behavior.
    a. https://www.homedepot.com/compare?item1=308743988&item2=311411352&item3=305712398

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18207

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2110)

**Comment by delli-gatti-michael** [comment]
Testing Complete
