### ISSUE TITLE
Hide Support R&S article listing paginated pages from SERPS

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#27793]
# Description

There are certain paginated pages that end with `/2`, `/3/`, `/4`, etc. that need to not be indexed by search engines. These pages for the moment look to only be coming from [this template](https://github.com/department-of-veterans-affairs/content-build/blob/0350ee4ded912677c92aeff94867ca1c6c438b78/src/site/layouts/support_resources_article_listing.drupal.liquid).

## Affected pages

https://www.va.gov/resources/other-topics-and-questions/2/
https://www.va.gov/resources/other-topics-and-questions/3/
https://www.va.gov/resources/va-account-and-profile/2/
https://www.va.gov/resources/education-and-training/2/
https://www.va.gov/resources/tag/all-veterans/2/
https://www.va.gov/resources/tag/all-veterans/3/
https://www.va.gov/resources/tag/all-veterans/4/
https://www.va.gov/resources/tag/all-veterans/5/
https://www.va.gov/resources/tag/all-veterans/6/
https://www.va.gov/resources/tag/payments-and-debt/2/

## Acceptance Criteria

- [x] Add `<meta name="robots" content="noindex">` to the support_resources_article_listing.drupal.liquid template when on pages 2 or more.

**Comment by srsuddath** [comment]
I believe this is the current list of affected pages

https://www.va.gov/resources/other-topics-and-questions/2/
https://www.va.gov/resources/other-topics-and-questions/3/
https://www.va.gov/resources/va-account-and-profile/2/
https://www.va.gov/resources/education-and-training/2/
https://www.va.gov/resources/tag/all-veterans/2/
https://www.va.gov/resources/tag/all-veterans/3/
https://www.va.gov/resources/tag/all-veterans/4/
https://www.va.gov/resources/tag/all-veterans/5/
https://www.va.gov/resources/tag/all-veterans/6/
https://www.va.gov/resources/tag/payments-and-debt/2/

**Comment by kelsonic** [comment]
Updated the ticket, thanks @srsuddath! 🙂

**Comment by kelsonic** [comment]
PR merged, will go out with the daily deploy today. You won't see it removed from the sitemap, but those pages won't be indexed by search engines due to the noindex metatag.

**Comment by brianalloyd** [comment]
Thanks @kelsonic for the update.

**Comment by brianalloyd** [comment]
LGTM, closing out in support.
