### ISSUE TITLE
Rework 10-10EZ intro for user who arrives on intro already signed in. (to complete after auto-qualify flow is set)

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#27791]

**Comment by Dene-human** [comment]
[Current logged in intro ](https://app.zenhub.com/files/133843125/af6dcf97-b55d-476a-81db-43106b205095/download)


This also shows when user logs in from non-signed in Intro page. I think we need to remove that from the flow if possible.

**Comment by markfallows** [comment]
@hdjustice and @markfallows to investigate and add any additional detail/information as needed.

**Comment by markfallows** [comment]
I don't think I fully understand the purpose of this ticket, but I believe there are two problems that we can address along this vane:
1. If we want to do more to ensure that the users read all of the instructions before starting, it might be a good idea to remove the first **Start the health care application >>** button that's presented prior to the instructions.
![start_hc_app](https://user-images.githubusercontent.com/65271356/194614640-720b6bc4-784a-4f40-9859-69d0beb8279a.png)

2. When a user that *is not signed in* arrives on the front page, they are presented with an option to  sign in and start the application.  If they sign in, they're redirected to the same page that a logged in user receives when they first arrive on the introduction page (shown above).  We should probably just check to see if there are any existing applications for this person
![sign_in_to_start](https://user-images.githubusercontent.com/65271356/194615074-93ddf8ea-b0ab-4a92-aee7-460619684ad4.png)
 and, if not, place them directly into the first appropriate page of the application itself.

**Comment by hdjustice** [comment]
Not enough information in this ticket and outdated with recent updates.
