### ISSUE TITLE
Document Button Loading/Downloading Indicator

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#27807]
Add documentation to the design system for Button Loading/Downloading Indicator

Document the two use cases for 
- Static files
- Generative uploading and downloading will behave this way. 

Work to be done when DST gets a new designer. 
See this ticket for additional information. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/432

**Comment by GnatalieH** [comment]
This request should be handled in the guidance I left in #[432](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/432). I also added guidance to the Accessibility considerations in Button component documentation on design.va.gov to indicate the following:

- Button labels should never change dynamically or be used to communicate a status.

It's not a good practice for a11y reasons to change the text label on a button or use it to indicate an activity status. Our [Loading indicator](https://design.va.gov/components/loading-indicator) should be used for indeterminate activities and the [Progress bar - Activity](https://design.va.gov/components/progress-bar/) should be used when the wait time is known.

**Comment by GnatalieH** [comment]
Closing this ticket per Matt's suggestion. We'll handle uploading/downloading patterns in #[1121](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1121) and #[1122](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/1122).
