### ISSUE TITLE
Adding Josh Scanish to DSVA Slack

### ISSUE THREAD

**Issue by nsmith1982** [department-of-veterans-affairs/va.gov-team#27815]
Good evening,

Would you please add Josh Scanish (Josh.Scanish@oddball.io) as a Full Member to DSVA Slack with access to the following channels?

# vfs-platform-support
# vfs-all-teams
# vsp-identity

Thank you!

**Comment by nsmith1982** [comment]
@LEHigley @LizCallaghan just making sure someone sees this.

**Comment by LizCallaghan** [comment]
done!
