### ISSUE TITLE
CT Redesign: Update behavior of compare page header and cards

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27831]
As a developer, I need to set a stop-point on the compare page header stickiness so that it does not go into the footer and lose the value of it's context.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The header cards become vertically sticky once the card hits the top of the viewport.
    a. The cards stop being vertically sticky once the top of the blue footer meets the bottom of the viewport.
2. The "Highlight differences" includes checkbox includes the same asterisks that is displayed when the functionality is enabled.
3. On desktop, the name of the institution header is a link to the institutions profile page.
4. On mobile, the name of the institution header is static text.
5. The institution card does not display the "city, state" of the institution.
6. The institution "city, state" is displayed as the "Location" row in the "Summary" section of the compare page.
7. The header card includes the color institution type indicator and corresponding text:
    a. School [Blue]
    b. OJT / Apprenticeship [Green]
    c. VET TEC [Red]

## Supporting artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222692/296060325/preview)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18207

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18265

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18308

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2120&group_by=cases:section_id&group_order=asc&group_id=46
