### ISSUE TITLE
Search Results not showing same results

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#2784]
### Status

UNRESOLVED

### Severity Analysis

*Estimate of how critical this bug is*

- `sev 3` 

### User Impact 

- Users of the VA.gov site
- Search results vary depending on how the user types in information

### Description

The search results for "10-10EZ" result in the correct documenting being presented to the user at the top of the search results.  However, the search for "10-10 EZ" does not return the correct results at all.

### Steps to Reproduce

Searching for "10-10EZ" Displays the correct results at the top of the list as shown below:
![Screen Shot 2019-10-25 at 11.32.15 AM.png](https://images.zenhubusercontent.com/5d0d04b74cffae4475d77c10/6cb49b71-32d5-43fc-b27d-ffc12bf87532)

Searching for "10-10 EZ" has a different set of results as shown below (and none of the results are the "Apply for VA Health Care Online (VA Form 10-10EZ"):
![Screen Shot 2019-10-25 at 11.34.13 AM.png](https://images.zenhubusercontent.com/5d0d04b74cffae4475d77c10/fa02b18a-4c89-4f91-ab1d-8436e6367031)

#### Expected Results

The search results for "10-10EZ" and "10-10 EZ" should display the same results and both should result in showing the "Apply for VA Health Care Online (VA Form 10-10EZ" link  at the top.

#### Actual Results

See Above

### Proposed Solution

- *Summary of solution*
- *Link to related tickets*

**Comment by alexpappasoddball** [comment]
@Karak888 Sending your way for visibility.  I know you are working on revamping the search functionality so this is more for visibility than anything.

**Comment by FranECross** [comment]
Confirmed today that the correct search results are being returned when 10-10 EZ is used. Closing.
