### ISSUE TITLE
Research Canary PagerDuty Notification Procedures

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#27846]
## User Story

- [x] Discuss PagerDuty alerting thresholds with Ops team. How can we configure these? What options for limiting noisy notifications are there?
- [x] Come up with a playbook for dealing with Canary failures. Consult Ops for their input.

## Acceptance Criteria

- [x] Create a Confluence document for the Canary Alerting best practices vis a vis PagerDuty
- [x] Create a Confluence document for the Canary Triage Playbook

**Comment by rjohnson2011** [comment]
Synced with Ops regarding AWS CloudWatch / Canary alerting procedures. In process of writing up Confluence doc for best practices.

**Comment by rjohnson2011** [comment]
Confluence doc is up on https://vfs.atlassian.net/wiki/spaces/TTT/pages/1801617441/Canary+Alerting+Best+Practices

Sent to Ops to review and awaiting any potential feedback.

**Comment by rjohnson2011** [comment]
Ops has approved the Confluence doc best practices. https://dsva.slack.com/archives/CBU0KDSB1/p1628191166163600?thread_ts=1628005178.061000&cid=CBU0KDSB1
