### ISSUE TITLE
[Design] 10-10CG - Improve Facilities Selection: Create mobile design for facility selector

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#27841]
Once an updated design is decided on, we need to create a mobile view that reflects the updated functionality.

More information to be added as the non-mobile design is finalized and implemented.

**Comment by longmd** [comment]
@jessicastump , these are what I mentioned this morning that I took a peek at.

**Comment by hdjustice** [comment]
Closed - duplicate ticket.  We already have one for design on this feature, and will include mobile with that effort
