### ISSUE TITLE
CHIP - Determine & document most important traits for monitoring

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27855]
We need to set up an "Information radiator" to allow for easy tracking of CHIP performance. This will likely take the tangible form of a dashboard.

We need to make sure to monitor a high water mark for requests. 

Task is done when:
We have 
- [x] a list of traits to monitor 
- [x] approved by consensus

**Comment by kjduensing** [comment]
* [**VEText**] Number of patients that send the word checkin to shortcode
* [**LoROTA**] POST/GET/DELETE information
* [**LoROTA**] Read/write capacity units
* [**CHIP**] Number of messages sent back
* [**CHIP**] Number response with url for checkin
* [**CHIP**] Number of messages with too many appts
* [**CHIP**] Number of unknown #s.
* [**CHIP**] Number of successful checkins.
* [**CHIP/VistA Service**] Number of checkin api calls.
* [**Frontend/CHIP**] Number of clicks on check in button
