### ISSUE TITLE
CHIP - Research available monitoring / alert tools

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27859]
We need to set up an "Information radiator" to allow for easy tracking of CHIP performance. This will likely take the tangible form of a dashboard.

It will take some time to gather data.

We have datadog as an option - other teams are using it. 
Cloudwatch is also an option.
There are also existing AWS tools we can use (X-RAY) that need to be considered. 

**Task is done when:**
We have 
- [ ] chosen a tool 
- [ ] approved by consensus

**Comment by kjduensing** [comment]
Going with cloudwatch (at least for now because:

1. Shane was concerned about who can access the dashboard, but is ok with it because Patrick can access the dashboard.
2. It's easy and accessible.
