### ISSUE TITLE
LoROTA - Determine & document most important traits for monitoring

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27856]
We need to set up an "Information radiator" to allow for easy tracking of LoROTA performance. This will likely take the tangible form of a dashboard.

We need to make sure to monitor a high water mark for requests. 

Task is done when:
We have 
- [x] a list of traits to monitor 
- [x] approved by consensus

**Comment by calquisola** [comment]
Here are some of the metrics Kevin and I discussed yesterday for LoRota

[LoROTA] POST/GET/DELETE information
[LoROTA] Read/write capacity units
