### ISSUE TITLE
Analytics Feature Request/Bug Report

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27863]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- Lauren Ernest, Product Manager

  _this adds research context for any data or features being requested_

  - VAOS

- Is this a feature request or a bug?

  - [ ] Feature request
  - [ ] Bug report

Neither? Support request follow up.

## Request/Report Description

Follow up from platform support discussion in Slack https://dsva.slack.com/archives/CBU0KDSB1/p1626985095424900

We are doing a test with a control and one variation version of the Choose VA location v2 page. In addition to other metrics, we are trying to measure if the time users spend on that page is affected and compare the time of the control and variant during the testing period.

https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361/edit/Z4cFM5gyQhy65K3s4tymQw

We would like to run this test and capture the data for about 1 week, starting Tue 7/27 or Wed 7/28

For a new feature request:

- Description of desired feature
- Why the feature is needed

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by joanneesteban** [comment]
@laurenernest Hello! Are you able to attend [one of our office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport) to discuss this?

**Comment by laurenernest** [comment]
@joanneesteban I might be able to make it next Wed or Thu. I'll make a note for myseslf.

**Comment by joanneesteban** [comment]
Thanks, Lauren!

**Comment by laurenernest** [comment]
I got the segments set up for both with and without the event in the funnel and was able to use them to create a report for the average time. Thanks for the help! Closing ticket

https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361/edit/Z4cFM5gyQhy65K3s4tymQw

https://analytics.google.com/analytics/web/template?uid=wJNRUJodTRW30Z7w567VZg
