### ISSUE TITLE
[FE] Notification Prefs: Notification settings display bug after removing email address and mobile phone

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#27864]
1. As a staging user with at least a mobile phone or email address on file, view the Notification Settings page at https://staging.va.gov/profile/notifications
2. Delete the mobile phone and email address from https://staging.va.gov/profile/personal-information
3. Return to https://staging.va.gov/profile/notifications

You'll see the blue alert telling you that you don't have an email address or mobile phone on file. That's good.

But you also still see all of the notification groups and items, which is incorrect.

**Comment by ajakabcin** [comment]
Oh yes you're right! I moved it out of the sprint epic but forgot to move the milestone. Thanks for flagging!

**Comment by erikphansen** [comment]
Fixed
