### ISSUE TITLE
LoROTA - Determine & document alerts and alert thresholds

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27869]
We need to set up an "Information radiator" to allow for easy tracking of LoROTA performance. This will likely take the tangible form of a dashboard.

We may need to do some extra research around

- provision capacity
- cold starts. 

Task is done when:
- [x] list is made
- [ ] list is approved

**Comment by calquisola** [comment]
here's a list of traits that Lorota should have alerts on:

1. Consumed RCU within 80% of provisioned RCU
2. Consumed WCU within 80% of provisioned WCU
3.  500 errors reach a certain number within an hour
4. lambda memory consumption with 80% of the provisioned memory

**Comment by kjduensing** [comment]
@calquisola Looks like a good start
