### ISSUE TITLE
LoROTA - Research available monitoring / alert tools

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27860]
We need to set up an "Information radiator" to allow for easy tracking of LoROTA performance. This will likely take the tangible form of a dashboard.

It will take some time to gather data.
Datadog is an option
Cloudwatch is another option
There are also existing AWS tools we can use (X-RAY) that need to be considered. 

**Task is done when:**
We have 
- [ ] chosen a tool 
- [ ] approved by consensus

**Comment by calquisola** [comment]
tools to consider: 

AWS XRay  
 - Built into AWS no integration needed
 - great for trouble shooting
 - performance metrics
 - XRay needs to be added to code and SAM template
 - adds more cost

Cloudwatch Lamba Insights
 - easily configurable in the console
 - need to research if can be through the SAM template
 - simplifies collection and aggregation of metrics from AWS
 - adds more cost

Data Dog integration
 - Will need AWS Xray added to our code
 - No AWS SAM integration (recommends Serverless Framework instead.)
 - Needs IAM credentials to be integrated
