### ISSUE TITLE
CHIP - Set up monitoring for important traits with tool

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27866]
We need to set up an "Information radiator" to allow for easy tracking of CHIP performance. This will likely take the tangible form of a dashboard.

Task is done when:
We can view the monitoring tool (likely a dashboard)

**Comment by kjduensing** [comment]
- [ ] Number of checkins initiated
- [ ] Number of messages sent back
- [ ] Number of "too early" messages
- [ ] Number of "too late" messages
- [ ] Number response with url for checkin
- [ ] Number of messages with too many appts
- [ ] Number of unknown #s.
- [ ] Number of successful checkins (ie good responses from CHIP).
- [ ] Number of patients checked into VistA (regardless of how CHIP responds)
- [ ] Number of checkin api calls.
- [ ] Number of clicks on check in button
