### ISSUE TITLE
LoROTA - Set up monitoring for important traits with tool

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27868]
We need to set up an "Information radiator" to allow for easy tracking of LoROTA performance. This will likely take the tangible form of a dashboard.

Task is done when:
We can view the monitoring tool (likely a dashboard)

**Comment by calquisola** [comment]
Dashboards for dev and prod were created. 

 [dev link](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#dashboards:name=LoROTA
)

[prod link ](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#dashboards:name=LoROTAProd)
