### ISSUE TITLE
CHIP - Set up and publish monitoring dashboard 

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27876]
We need to set up an "Information radiator" to allow for easy tracking of CHIP performance. This will likely take the tangible form of a dashboard.

**Task is done when:**
Dashboard is available to view in
- [x] Dev
- [x] New Dev
- [x] Staging
- [x] Prod

**Comment by kjduensing** [comment]
Dev is set up - need to set up a prod dashboard

**Comment by kjduensing** [comment]
For prod testing - need a full test to enable check in metrics
