### ISSUE TITLE
CHIP - Determine & document alerts and alert thresholds

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27871]
We need to set up an "Information radiator" to allow for easy tracking of CHIP performance. This will likely take the tangible form of a dashboard.

Task is done when:
- [x] list is made
- [x] list is approved by consensus

**Comment by kjduensing** [comment]
* gte 3 5XXs per minute for
  * `/token`
  * `/initiate`
  * `/checkin`
  * `/getAppointments` (temp)
* gte 3 4XXs per minute for `/token`
* vista checkin count != chip checkin count
