### ISSUE TITLE
[Discovery] Document possible error states from Facilities search on the 10-10CG

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27889]
## User Story

**As a** Veteran, **I need to** select the most relevant VA Medical Facility with a Caregiver Support Coordinator **so I can** participate in the PCAFC.

The purpose of this story is to document the possible error responses from the Facility search and discuss how to handle them.

## Expected Behavior

Main errors we main experience:
* No facilities found in the current search
* No response from Facilities service
* Error response from Facilities service

## Acceptance Criteria

- [ ] Error states documented so that UX can be defined

**Comment by dat-gcio** [comment]
@Dene-human 
When the user searches, one of the following can happen:

-	over 0 results return based on the search (user able to select)
-	0 results return based on the search
-	An error of any kind occurs (which yields no result)

In essence, we have to handle the case that the user cannot make a selection based on those two possible scenarios.

**Comment by Dene-human** [comment]
Thanks! For the "An error of any kind occurs (which yields no result)". Any guidance on messaging or what the next step for the user should be?

**Comment by dat-gcio** [comment]
I would think something to the effect of `we are sorry, something went wrong`. How to proceed, I am not too sure. If this service is down, submission is probably down as well. We would probably tell them to come back later, or do it manually?
