### ISSUE TITLE
CT Redesign: Add standard links / footer disclaimer to sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27888]
As a developer, I need to add two links and a disclaimer footer to all pages of the sandbox so that current functionality of the comparison tool is not lost.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The search page contains:
    a. An "About this Tool" link (https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp)
    b. A "Download Data on All Schools (Excel)" link (https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx)
    c. The following disclaimer content:

    > Please note: Content on this Web page is for informational purposes only. It is not intended to provide legal advice or to be a comprehensive statement or analysis of applicable statutes, regulations, and case law governing this topic. Rather, it’s a plain-language summary. If you are seeking claims assistance, your local VA regional office, a VA-recognized Veterans Service Organization, or a VA-accredited attorney or agent can help. [Search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives](https://www.va.gov/ogc/apps/accreditation/index.asp?_ga=2.11643697.460336236.1627307157-1403569758.1603827284).

2. The compare page contains:
    a. An "About this Tool" link (https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp)
    b. A "Download Data on All Schools (Excel)" link (https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx)
    c. The following disclaimer content:

    > Please note: Content on this Web page is for informational purposes only. It is not intended to provide legal advice or to be a comprehensive statement or analysis of applicable statutes, regulations, and case law governing this topic. Rather, it’s a plain-language summary. If you are seeking claims assistance, your local VA regional office, a VA-recognized Veterans Service Organization, or a VA-accredited attorney or agent can help. [Search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives](https://www.va.gov/ogc/apps/accreditation/index.asp?_ga=2.11643697.460336236.1627307157-1403569758.1603827284).

3. The non-vettec profile page contains:
    a. An "About this Tool" link (https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp)
    b. A "Download Data on All Schools (Excel)" link (https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx)
    c. The following disclaimer content:

    > Please note: Content on this Web page is for informational purposes only. It is not intended to provide legal advice or to be a comprehensive statement or analysis of applicable statutes, regulations, and case law governing this topic. Rather, it’s a plain-language summary. If you are seeking claims assistance, your local VA regional office, a VA-recognized Veterans Service Organization, or a VA-accredited attorney or agent can help. [Search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives](https://www.va.gov/ogc/apps/accreditation/index.asp?_ga=2.11643697.460336236.1627307157-1403569758.1603827284).

4. The vettec profile page contains:
    a. An "About this Tool" link (https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp)
    b. A "Download Data on All Schools (Excel)" link (https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx)
    c. The following disclaimer content:

    > Please note: Content on this Web page is for informational purposes only. It is not intended to provide legal advice or to be a comprehensive statement or analysis of applicable statutes, regulations, and case law governing this topic. Rather, it’s a plain-language summary. If you are seeking claims assistance, your local VA regional office, a VA-recognized Veterans Service Organization, or a VA-accredited attorney or agent can help. [Search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives](https://www.va.gov/ogc/apps/accreditation/index.asp?_ga=2.11643697.460336236.1627307157-1403569758.1603827284).

## Supporting Artifacts:
1. Screenshot of current CT:
<img width="1105" alt="Screen Shot 2021-07-26 at 10 44 53 AM" src="https://user-images.githubusercontent.com/48260534/127051573-8e502508-9c97-4b13-a31a-3ba8bbadfcf5.png">
2. Prototype of disclaimer footer on profile page: https://bahdigital.invisionapp.com/d/main#/console/14222703/296062587/preview

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18121

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/2076)

**Comment by delli-gatti-michael** [comment]
testing complete
