### ISSUE TITLE
Access for [Robert Williams]

### ISSUE THREAD

**Issue by rwilliams-oddball** [department-of-veterans-affairs/va.gov-team#27887]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team 
    > Operations
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Nancy Smith
- Please provide your name.
   > Robert Williams
- Please Provide your email.
   > robert.williams@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Ops

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDhIqF/brsC7ZXMjmZPGl6jhqFLFUArSocwWU3UN7LVU1l2meQ4YmZjmEPqSAhChNZdD4mhVrxJS6qggwkzFI25+F4mZydRp4cTjwf9epw+0bG0VaH42pAAqFa8KcnHH8djUnpyg+5IY9lylxgYsj/2MHEbO4KiPnNhmKWhU19aUAhmtY8mMHORXic2hewvBgyBH2/ziYaWBkRmwhHlK/0NLrQrlczE+htj4RXHcRtH5tQIUzWMmzG8Esqxi/tLnMZxw11FqaiLo0EoXztLwnJwBl3CB3hLjAYhs/KAW/HtGkMf/fpSVFPJS2u/v5JjJP1qiHsuBCY0lXvTnQQ1LTt368SYYtaNvmsHDgPqW0ScpJr8ug4Ib3pquvs8IFTHijrO+0JyWUOA/pGSJPZM2PAaJCVVs6TAKh38spCCV7uWfkJp4I6Kps5VF0AIAcwWPw0AsxtL5r8Ks64Qsny4M6bN0bv8e5ulOvM4l74y/9rRD2NFwjLCmgqLNzxqOn8hlVc= rwilliams@roberts-air.lan```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why?

**Comment by mydesignrocks** [comment]
Hi @rwilliams-oddball your socks is now granted.
Please follow this document in enabling: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#chrome--firefox

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - please review for AWS access.

**Comment by jbritt1** [comment]
Expedited approval for AWS access requested: https://dsva.slack.com/archives/CJYRZK2HH/p1627567226313100

**Comment by drorva** [comment]
Approved

**Comment by jbritt1** [comment]
Temporary credentials provided to user, confirmed access and password reset.
