### ISSUE TITLE
Refactor LanguageSupport and I18Select for Redux/execution issues.

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#27885]
## Issue Description
_The LanguageSupport component triggers various dom manipulations that could be considered overreaching, and the Redux action 'LANGUAGE_SELECTED' fires multiple times on every page render. This should be refactored to be more modular and less intrusive to prevent potential issues._

This ticket arrises from the exploration done to resolve this accessibility ticket:
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/27619](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27619)

**Issues:**

- Hook for `adaptLinksWithLangCode` is running on every page load, and not just on pages that have language translations.
    - This hook gets all document.links, and the lang tag is injected into each link based on some hook logic.
    - The hook is running 4 times on page load, and this results in a Redux action
    - The Footer.jsx is where this hook is called, and therefore is basically global as long as the Redux language_support key is true.
- Only links with a url structure in the href that indicates that is goes to another translated page have the correct lang attribute, all others basically have a `lang="en"` set

**Fix:**

- The hook should probably only fire on pages that it deems necessary and not on every page load. That means splitting the hook into sub hooks and only one sub-hook for conditional execution on page loads and will stop propagation of any lang based dom manipulations.
    - The secondary sub-hook fires off the dom changes and updates the dom via a series of selectors based on rules and criteria set in the hook.
        - Selectors for manipulation include `#va-detailpage-sidebar` (sidebar where translated links appear as of now), `article.usa-content` (main content of article), and lastly numerical characters in the dom, as they will be dictated in the wrong language via screen readers.
- Parse every link in the `article.usa-content` element to be the correct language attribute. This fix will potentially change english links in any embedded react app that renders inside that article element though and should be considered. The other drawback is that spanish links in the sidebar would not be correct, so a second parsing of that element and other areas may still need to be done.
- A separate function for correcting 'other' link types should run to the correct language code so numbers are translated to desired language on those edge case li (phone numbers, and maybe other types of links?)
- The component naming is incorrect and should probably be changed to I18nSelect 🥴

## Acceptance Criteria
- [x] Redux action is only fired when needed (when language selection changes)
- [x] Dom manipulations to links only happen on specified translated pages and don't occur on homepage etc.
- [x] Configuration for languages and translated pages is centralized into a config/constants file.
- [x] Evaluation of effectiveness of refactor and possible edge cases are documented.
- [x] Unit testing supports refactor and maintains coverage.

**Comment by SKasimow** [comment]
@adamwhitlock1 I'll move this one over too. thx
