### ISSUE TITLE
[Backend] Short Form: Mapping available data to desired fields in 10-10EZ form

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27884]
## User Story

**As an** authenticated veteran, **I want to** have more information pre-populated into the online 10-10EZ form, **in order** to make the process more streamlined and accurate.

## Expected Behavior

This is a follow on to research done in ticket #27278 to map those finding to fields we would like to populate in the 10-10EZ, assuming they are not already.

## Acceptance Criteria

- [ ] mapping for available data to 10-10EZ fields

**Comment by MickinSahni** [comment]
10/1 Standup: gonna get ready for sprint 58 starting next Wed

**Comment by tchrisdyer** [comment]
Closing this ticket as I believe it has too much overlap with #27886
