### ISSUE TITLE
Expand unit testing for LanguageSupport and I18Select components

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#27882]
## Issue Description
_There are not many unit tests available for these components and we need to get increased coverage and edge cases covered._

## Acceptance Criteria
- [x] Increase coverage of unit tests for the two main components
- [x] Unit test helper functions / hooks that are in use
- [x] Consider edge cases, error prevention and any other testing that is needed
- [x] Verify footer links use correct URLs and lang attributes
- [x] Redux and language attributes after links clicked
- [x] Check "On Other Pages" text is translated and screenreader is correctly engaged

**Comment by SKasimow** [comment]
@adamwhitlock1 Looks good Adam - thanks for catching. I'll leave it in the backlog for now and you can move it to Ready column when you are ready to start working it.
