### ISSUE TITLE
[Phase 2] [Backend] Short Form: Populating new profile data into payload for eventual prepopulation in 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27886]
## User Story

As a veteran who has logged in, I would like as much data prepopulated from my profile, in order to make my 10-10EZ application process faster and more accurate.

We already populate a lot of data today, just want to make sure we're pulling as much as we can AND bring in the Disability Ratings

## Expected Behavior

Based on mapping made in ticket #27884, the purpose of this story is to add the desired data into the payload so that it may be used to pre-populate the 10-10EZ.

## Acceptance Criteria

- [ ] Selected data fields added to payload

**Comment by tchrisdyer** [comment]
The goal of this story was to make sure the 10-10EZ is prepopulating as much info as it can from the profile. The main NEW thing we are after here is the disability rating(s) which we don't retrieve or use today, but will use for the Short Form in the future.

If any disability rating is 50% or greater, we can use that skip some questions.

**Comment by RudyOnRails** [comment]
@SKasimow would it be ok if we didn't assign tickets until it was time to work on them? It most likely won't be just me all by lonesome so having unassigned allows filters and queries to happen so other devs can pick things up.

**Comment by SKasimow** [comment]
@RudyOnRails Sure - I was doing some organizing but we can use the label "back-end" to find these tickets. Feel free to remove your name from any other tickets I assigned prematurely.
-S
