### ISSUE TITLE
Redirect Request (Vet Centers live as of 7/23- legacy directory location and key staff pages)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#27890]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

As the new Vet Center pages are rolled out, the legacy Directory location and key staff pages need to direct Veterans to the new web presence. These requests will be made in bulk for the locations which have gone live in the previous two weeks. 

Note: Outstations have their own Directory location and key staff pages but will be part of the new respective main Vet Center's Location page.

### Implementation date
No specific date - at your earliest convenience 

### Redirects

Location Directory url | Key staff directory url | New URL
-- | -- | --
--- | --- | ---
https://www.va.gov/directory/guide/facility.asp?ID=506 | https://www.va.gov/directory/guide/keystaff.cfm?id=506 | https://www.va.gov/colorado-springs-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5508 | https://www.va.gov/directory/guide/keystaff.cfm?id=5508 | https://www.va.gov/escanaba-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6494 | https://www.va.gov/directory/guide/keystaff.cfm?ID=6494 | https://www.va.gov/nashville-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5446 | https://www.va.gov/directory/guide/keystaff.cfm?ID=5446 | https://www.va.gov/nashville-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=553 | https://www.va.gov/directory/guide/keystaff.cfm?id=553 | https://www.va.gov/orlando-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=493 | https://www.va.gov/directory/guide/keystaff.cfm?id=493 | https://www.va.gov/reno-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=633 | https://www.va.gov/directory/guide/keystaff.cfm?id=633 | https://www.va.gov/springfield-ma-vet-center/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@brianalloyd This one is ready to be worked on, will let you assign as appropriate on your team. 

Please note:  these are parameter based URLs.  The parameter included is the key parameter, but these pages can be shown with other parameters, AND its possible that the parameters may be shown in a different order.   Please let me know if that creates any concern.   

Example, these URLs should all be redirected the same way based on the ID=5446:   https://www.va.gov/directory/guide/facility.asp?ID=5446
https://www.va.gov/directory/guide/facility.asp?ID=5446&dnum=All
https://www.va.gov/directory/guide/facility.asp?dnum=All&ID=5446

**Comment by brianalloyd** [comment]
Thanks @mnorthuis we'll scrub into this issue and might follow up if we need clarity on any of the above.  Appreciate it.

**Comment by kelsonic** [comment]
Quick question -- do both the `Location Directory url` and the `Key staff directory url` redirect to the `New URL`? @mnorthuis @brianalloyd Also I am very not confident that the devops redirects is going to support these query params in varying positions on the URL, I'm going to send up a PR now to test and see if we can figure it out 😬

**Comment by kelsonic** [comment]
Also (in the future), it's much easier if the redirects are formatted in the table the following way to avoid any confusion when we implement them:

Current URL  |  Redirect Destination or New URL
------  |  -----
https://www.va.gov/vaforms/medical/pdf/vha-10-10ezrfill.pdf | https://www.va.gov/vaforms/medical/pdf/vha-10-10EZR-fill.pdf

**Comment by brianalloyd** [comment]
Thanks @kelsonic I'll default to @mnorthuis on the question above.  Keep us posted on how PR reacts in support, thanks for scrubbing into this so quickly.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9675

**Comment by kelsonic** [comment]
Downgraded to a 3, should be feasible with current devops infrastructure, will bump to 5 if we run into hurdles that bring to light the need for more infrastructure in that repo

**Comment by kelsonic** [comment]
Yay! Everything worked flawlessly 🎉 Are these redirects good to merge/deploy to prod right now?

**Comment by mnorthuis** [comment]
Yes, both the location and key staff URL should redirect to the same new URL.  I was thinking about reformatting the table for you, but didn't want to mess up their data!  Next time I will get them laid out so its easier to read and manage.   Thank you for picking up on this so quickly!

**Comment by kelsonic** [comment]
No worries! Thank you @mnorthuis 🙂 This is ready to be validated btw! https://github.com/department-of-veterans-affairs/devops/pull/9675

https://www.va.gov/directory/guide/keystaff.cfm?id=506
https://www.va.gov/directory/guide/facility.asp?ID=506
https://www.va.gov/directory/guide/keystaff.cfm?id=5508
https://www.va.gov/directory/guide/facility.asp?ID=5508
https://www.va.gov/directory/guide/keystaff.cfm?ID=6494
https://www.va.gov/directory/guide/facility.asp?ID=6494
https://www.va.gov/directory/guide/keystaff.cfm?ID=5446
https://www.va.gov/directory/guide/facility.asp?ID=5446
https://www.va.gov/directory/guide/keystaff.cfm?id=553
https://www.va.gov/directory/guide/facility.asp?ID=553
https://www.va.gov/directory/guide/keystaff.cfm?id=493
https://www.va.gov/directory/guide/facility.asp?ID=493
https://www.va.gov/directory/guide/keystaff.cfm?id=633
https://www.va.gov/directory/guide/facility.asp?ID=633

**Comment by mnorthuis** [comment]
@mmiddaugh I have spot checked a couple and they look good, you/your team can review and close this issue if everything looks good.  Thank you!

**Comment by mmiddaugh** [comment]
Looks good to me! Thank you!
