### ISSUE TITLE
[Design] 10-10CG - Facility page: Handle errors on Facility Selection page

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27891]
## User Story

**As a** Veteran, **I need to** select the most relevant VA Medical Facility with a Caregiver Support Coordinator **so I can** participate in the PCAFC.

The goal of this story is create the UX design on how we will handle each error state.

## Expected Behavior

This is a followup for discovery ticket #27889 which documented possible error states that could occur when performing a facility API search. 

## Acceptance Criteria

- [ ] Designs for error states

**Comment by hdjustice** [comment]
Keeping this ticket in case we determine error states when calling Facilities API

**Comment by hdjustice** [comment]
no longer needed
