### ISSUE TITLE
[Design] Handle errors on Facility Search on 10-10CG

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#27892]
## User Story

**As a** Veteran, **I need to** select the most relevant VA Medical Facility with a Caregiver Support Coordinator **so I can** participate in the PCAFC.

The goal of this story is create the UX design on how we will handle each error state.

## Expected Behavior

This is a followup for discovery ticket #27889 which documented possible error states that could occur when performing a facility API search. 

## Acceptance Criteria

- [x] Designs for error states

**Comment by Dene-human** [comment]
**_Work in progress:_** [Errors and loading states designs](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/p/2D75EEBD-40EB-4F19-A2F7-1EB7CCF35952)
