### ISSUE TITLE
Break apart large test spec that runs too slow over time

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#27906]
The primary disability benefits `all-claims.cypress.spec.js` is extremely large.  Unfortunately, Cypress slows down the longer it's running a single spec.  This test should be divided into multiple specs to try and speed up Cypress some.

**Comment by CBonade** [comment]
Took a pass at this today.  The first run after splitting this up seemed to be an improvement but subsequent runs did not show the same time savings.  Going to reevaluate the need for this after we see what the suite run times look like between the additional parallelization Darius added today and the caching PR I merged in today.

**Comment by CBonade** [comment]
On further evaluating this test spec with breaking apart the data sets in different ways, there does not appear to be the savings here that we were hoping for. The good news, is the updates from yesterday seem to have dropped our times immensely. I've closed this PR and this ticket can head to closed status I believe.

**Comment by pjhill** [comment]
Sometimes the answer is "no can do" -- thanks for looking into this!
