### ISSUE TITLE
Access for Curt Bonade

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#27901]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Curt Bonade
- Please Provide your email.
   > curt.bonade@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Testing Tools Team, Front End Engineer, Oddball

- Requesting SSH key authorization?
   >  NO (already authorized)

- Grant AWS Console access?
  > YES
  - S3. Need to be able to upload html/video files to an S3 bucket for the VSP Testing Tools Team to host testing reports for users on vets-website.

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - please review for AWS access. thanks!

**Comment by drorva** [comment]
Request sent to Nancy Smith the GTL.

**Comment by drorva** [comment]
Approved

**Comment by mchelen-gov** [comment]
@mydesignrocks is this resolved?

**Comment by mydesignrocks** [comment]
AWS access granted and initial password with steps to login has been communicated over DM
