### ISSUE TITLE
External Domain Runtime Error

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27903]
## Description

Tim Wright just discovered a runtime error that was occurring on an external domain from our code.  This will need to be fixed in support of future builds. 

## Acceptance Criteria

- [x] Determine fix for runtime error and apply fix 
- [x] Ensure component is working as intended 
- [x] Content build is working with no runtime error reflected

**Comment by brianalloyd** [comment]
Connected PR for the work: https://github.com/department-of-veterans-affairs/content-build/pull/399

**Comment by kelsonic** [comment]
PR merged, we should be able to validate in the next couple of days here by not seeing a runtime error anymore: http://vhl.staywellsolutionsonline.com/Resources/VideoLibrary/?e=0#landing

**Comment by brianalloyd** [comment]
Thanks @kelsonic going to close out in support, but can reopen next sprint if issue remains.
