### ISSUE TITLE
James Adams access request to Google Analytics/Domo

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#27900]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
GCIO email: james.adams@gcio.com
VA email: james.adams2@va.gov

Google account created and linked to the email addresses above.

**Please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add `Analytics` in the "I need help from" dropdown, and add this issue's link and _add your email(s)_ in the "Summary of request."**

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo
- [ ] (Platform Teams only) BigQuery

## Date Required
As soon as is convenient.

## Product Team / External Team / VA Office
I am on the VSA eBenefits team.

*Please leave the following blank*

---

### Definition of Done
- [x] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jennaouellet** [comment]
@sporeboy I've given you GA and DOMO access to your gcio email address. Can you confirm you have gotten emails and are able to login? Thanks!

**Comment by joanneesteban** [comment]
@sporeboy - please let us know if you need anything else from Analytics. Feel free to reopen this ticket if you have any other access questions.
