### ISSUE TITLE
[Campaign Landing Page] - Archive and Redirect Pride CLP

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#27904]
## The What

As part of our governance model for Campaign Landing pages, all CLPs will archived (e.g. unpublished) with a redirect put in place to point to a related program page.  For those CLPs which are "seasonal" (e.g. Flu Season), there will be an option to re-surface those for re-use and content updates each year.

For the [Pride Month CLP](https://www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month/), we have been given stakeholder approval to:

- Archive (e.g., unpublish) the CLP now (Pride Month was observed in June 2021) but preserve the page for re-use in June 2022.
- Redirect the page traffic (the root and vanity URL) to this page: https://www.patientcare.va.gov/lgbt/

## Acceptance Criteria

- [ ] CLP is now long available on VA.gov and a redirect is in place that points to https://www.patientcare.va.gov/lgbt/

**Comment by brianalloyd** [comment]
@johnhashva are we okay to close this one out based on our roundtable review with decision to keep page active as in forward?  Any word back from Stakeholder in terms of preference or issues with the approach forward?

**Comment by johnhashva** [comment]
@brianalloyd  -- yes, we can close this as Kayla Williams at OPIA is up-to-date and in agreement with our strategy to keep this seasonal/recurring CLP live for next year's update.

**Comment by brianalloyd** [comment]
Thanks John, closing now in support.
