### ISSUE TITLE
IA Request [Public Websites, Harassment Reporting Tool (HRT)]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27911]
## When to use this 
After you've received a response to your Collaboration Cycle kickoff ticket that indicates an Information Architect Request is needed. 

## Steps to complete an IA request

- [x] VFS Product Manager: Create this issue and provide all required information below.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support. 
- [ ] Platform: Completes final IA feedback/recommendation.
- [ ] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886).
- [ ] VFS: Close issue once all IA feedback/recommendations are implemented.

## Artifacts
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/product-outline.md)
- [Mural Link - Flow ](https://app.mural.co/t/vsa8243/m/vsa8243/1626971557496/936e375b82d0af58a76ef2b36da3ecf4585bb118?sender=u7ad68f2a3a694c00d8a38130)
- [Sketch Files WIP](https://www.sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
- Still determining, Public Websites team plans to host several roundtables with IA to determine best path and placement for the reporting tool.  

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
- TBD

**URL(s)** - What are your suggested URLs and why?
- TBD

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  
- TBD

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
- TBD

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?
- No, no redirects are required for the HRT.

**Comment by mnorthuis** [comment]
Content ticket #26477 (content page) and #27438 (form).

**Comment by mnorthuis** [comment]
Content ticket #26477 (content page) and #27438 (form).

Notes from discussion with Danielle:
- static page to include CTA for crisis, when to report via tool versus police, how to report, possibly faqs
- discussed how to handle differentiating types of harassment through "when to file" content (i.e. did this incident involve physical touch? If yes, file police report)

Open questions
- Can they report harassment by non-VA employees? If in a VA location?
- Does this tool also ask if the harassment involved a denial of service or inability to use services provided by VA (i.e. discrimination)? What if it does related to discrimination claim?
- Can they "report only"? As in no investigation/follow-up?
- Reporter may be therapist/social worker, someone who has no affiliation with VA, but still needs to create an account to do so?
- Save in progress?

**Comment by brianalloyd** [comment]
@mnorthuis thanks for including the additional details, I'm passing the above questions to our Stakeholder for review and reply.  I'll follow up in this ticket with known details once received from the stakeholder.

**Comment by mnorthuis** [comment]
A quick update on IA recommendations, here's what I'm looking at.  @DanielleThierryUSDSVA discussed these today and we can provide more detail and context when we meet. 

- Content page and report form that will sit at the root level of the site - i.e. www.va.gov/[name of page]
- The main entry points being considered are within the sub-footer (very bottom section) and the contact us page

I have thoughts on a URL, but that will be finalized as we work through the content and H1s of the static page and the form.  We will also need to look at the sub-footer for placement, as it is already a very packed section.  I will work on pulling some analytics to help that conversation.

**Comment by mnorthuis** [comment]
IA information is documented here: <br> 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-harassment.md

I just want to confirm the H1 of the online form and then this is all final.   Here's the highlights:

URLs:
- Static content page:   /report-harassment/
- Online form:   /report-harassment/file-report-online/   (I am waiting to see final copy on the form before I finalize this URL)

Entry points:
- An issue has been created for the addition of an entry point in the footer:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/29528
- An entry point on the Contact us page - An issue has not been created for this yet.  
- An entry point to the online form from the static page - This cannot be done  until the form is ready to launch.

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis I created [an issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/30413) for you, Beth, Randi, and I to work on around this (and the larger question of how to best incorporate info on how to contact VA re: complaints and other issues). I think you mentioned that this doesn't have to be a primary entry point at launch for the HRT landing page. Is that correct? Thanks!

**Comment by mnorthuis** [comment]
Thanks @DanielleThierryUSDSVA!  As long as there is one entry point to the page we are good - I think that will be the footer, so the contact us page work can follow up after.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome - thanks, @mnorthuis! Agree, I think the footer is the primary entry point and that should go live with launch for sure.
