### ISSUE TITLE
[FE] Notifications Settings: 'Add email address' link is wrong

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#27915]
The link to "add email address" from Notification settings should link a user directly to the email address section of their profile, with the focus on the Edit button.

It currently links to `personal-information#edit-email-address` but it should link to `personal-information#edit-contact-email-address`

<img width="682" alt="Screen Shot 2021-07-27 at 9 40 45 AM" src="https://user-images.githubusercontent.com/20728956/127193764-2d2ea624-7320-450b-aa7d-3c5fa12381c5.png">

**Comment by erikphansen** [comment]
@ajakabcin this is a super small ticket that can done at any time

**Comment by ajakabcin** [comment]
resolved via https://github.com/department-of-veterans-affairs/vets-website/pull/18202
