### ISSUE TITLE
Pre-MVP CHIP Wrap-up

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#27925]
### CHIP
- [x] Time Zone issues - mapping station numbers, send to LoROTA in UTC - for valid start / end date for session. Date from VEText is coming from facility location time zone. 
- [x] Create a prod version of CHIP
- [x] Environment Variables, including Account IDs, Credentials, etc for PROD
- [x] Need to get prod routes & creds from other systems to be fully ready for PROD
  - [x] LoROTA prod URL
  - [x] LoROTA prod creds
  - [x] va.gov checkin prod url
  - [x] VistA prod URL
  - [x] VistA prod creds 
- [x] Create prod credentials for VEText and vets-api
- [x] securely provide prod creds to integration clients
- [x] Update error messages to reflect flow chart

### LoROTA
- [x] Create a prod version of LoROTA
- [x] Environment Variables, including Account IDs, Credentials, etc
- [x] Point to Prod DB

### VistA
- [x] Create a prod version of VistA API
- [x] Environment Variables, including Account IDs, Credentials, etc

### Blockers
- [x] Need RPCs to do end to end testing in prod
- [x] Methodology for end to end testing in Prod
- [x] Point production keywords on shortcode to CHIP

End to End Testing

### Nice-to-haves
- [ ] ~OpenAPI spec for distribution (nice to have)~

### Notes
Can currently do end to end testing in dev environments

**Comment by kjduensing** [comment]
Rob is out this week (8/2 - 8/6)

**Comment by kjduensing** [comment]
Cannot provide creds to VEText or vets-api today as both Dillo and Rob are out.

**Comment by kjduensing** [comment]
Creds are provided to and received from all integration clients.

I'm not sure the port given with the new prod (and test) vista APIs will work. It's 9080, and I believe the VPCs only allow port 80 and 443 through without a firewall change request.
