### ISSUE TITLE
STEM AD: Remove unused EVSS service calls and improve performance

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#27920]
As a developer, I need to remove the unused POA EVSS call and leverage previously loaded data so that unnecessary service calls are no longer made and the performance of the automated denial process can be improved.

## Assumptions:
1. This work is completed using feature flag: 'stem_automated_decision' (#13829).  Note, any pre-existing usage of this feature flag will need to be removed.

## Acceptance Criteria:
1. EVSS service calls to retrieve POA information are removed.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/7559
