### ISSUE TITLE
va-checkbox space before required 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#27932]
## Description

The `<va-checkbox>` web component adds "(Required)" to the end of the label without a space when the `required` prop is included.

<img width="428" alt="Screen Shot 2021-07-27 at 2 02 12 PM" src="https://user-images.githubusercontent.com/136959/127212962-18c514e4-55ef-4755-9538-db360a5d97f4.png">

## Tasks

- [ ] Add a space

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by cvalarida** [comment]
Need to add a non-breaking space at the beginning of the `<span>` I think. :+1:

**Comment by pdavies88** [comment]
Fixed via https://github.com/department-of-veterans-affairs/va.gov-team/issues/33114
* https://github.com/department-of-veterans-affairs/component-library/pull/236/files#diff-145f5316c3d2374f93e2878ed545fa936a041fc43e5d417e1641f0d3792a8c3d
* Accessibility Check for usage of `Required` within label done here: https://github.com/department-of-veterans-affairs/component-library/pull/234#issuecomment-1018910243

![Screen Shot 2022-01-24 at 1.58.12 PM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/69e5685f-83bf-4896-81ee-5534d552368b)
