### ISSUE TITLE
Facility Locator - at narrow viewport width the search form layout is broken

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#2793]
<img width="570" alt="facility-locator-form-bug" src="https://user-images.githubusercontent.com/57469/67605369-35945700-f74c-11e9-8aa8-8228d645eb40.png">

## What happened?

While testing the form I narrowed my browser window to look at something else and noticed that the search form controls reflowed and were not aligned.

## Specs:
- Device: MacBook
- Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/?zoomLevel=4&page=1&address=&facilityType=all&serviceType&location=40.212440718286466%2C-99.228515625&context=20004
- Test User _(if applicable)_: N/A
- Make your browser window narrower, approximately less than 600px wide

## Desired behavior

Form controls should align according to design.va.gov specs

## Acceptance Criteria
- [ ] When the window narrows, the form controls should align according to the design.va.gov specs

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [Ongoing Maintenance] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [product support] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [frontend] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [Bug] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This issue has been resolved
