### ISSUE TITLE
Sandbox: minor issues fixes

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#27930]
## What happened?

- issue with Location Search Results displaying "no results with no filters" text on load
  - should only display intro text
- issue with Compare Page not being at top on load if previous screen was scrolled down
  - should be at top of page on load
- issue with Compare Drawer not staying open when switching between Search and Profile page
  - should stay open/close when switching between Search and Profile pages
- issue when using breadcrumbs with URL not retaining params
  - should retain search string and filters when using breadcrumbs
- issue when loading Profile page the "Back to top" is showing on load
  - should not show until header is out of view
- Scrolling and double clicking behavior on map should zoom on mouse pointer 

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18018

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are live on Staging. Closing this issue
