### ISSUE TITLE
Analytics Feature Request/Bug Report

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#27946]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [x] Ticket Description
- [x] Request/Report Description
- [x] Additional Comments

## Ticket Description

Who is this request for? 

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports) 

  _this adds research context for any data or features being requested_

  - PM for the Claims & Appeals team, project- form 526ez

- Is this a feature request or a bug?

  - [ ] Feature request
  - [x] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature
- Why the feature is needed

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

Requesting existing BDD domo board based on [this spreadsheet](https://docs.google.com/spreadsheets/d/1LdH2iAHa6_lGeDnRrhHe8jIVjowU6vzLrJa4cQ6oUSk/edit#gid=85525268) be renamed to 21-526EZ and the funnel modified to match this [updated spreadsheet:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/KPI%20Dashboard%20Template%20-%20Original%20Claims%20526.xlsx) 

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

After discussion with my engineering team, consensus is that it doesn’t make sense (and is likely impossible) to separate the BDD funnel from 526, so, I’d like to just modify my existing domo board and replace with an overarching 526 domo board. 

> Please leave the following blank

## Acceptance Criteria

- [x] Relabel the issue where appropriate
- [x] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [x] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by chloedotbrown** [comment]
Thanks for submitting this, @vhenry07! To give you an update on our plan, we'll remove the current BDD-only version and replace it with this new funnel. Once the new data has loaded, we'll still need to QA it again, so consider your dashboard temporarily "offline" until it's passed its tests even though you may see new data in there.

Will update you on this ticket once it's officially good to go!

**Comment by chloedotbrown** [comment]
@vhenry07 We're still working on the QA of your data, but wanted to reach out and see if there were any adjustments you'd like to make to your [funnel](https://docs.google.com/spreadsheets/d/1BXJcV2C1aNtxuOim2uaFd3Q2gWrKN6Q2WQE5Qq_2_u0/edit?usp=sharing) based on this initial funnel table. 

- **Steps 1 & 2**: Despite the fact that these steps have different URLs, user counts between step 1 and step 2 are always identical (whether counting users by month, week, or day). Would you like to combine these into a single step? Or is this something you'd like to keep as-is and monitor moving forward?
- **Steps 4 & 5**: These two steps _actually_ have the same URL, and so these user counts will always be identical in your funnel. If one of these links needs to be updated or you'd like to consolidate them under a single step, let me know!

<img width="674" alt="21-526EZ New Funnel" src="https://user-images.githubusercontent.com/45518242/127721407-db3d22da-eaa4-4e3d-bb72-bd9ad0f26a68.png">

**Comment by vhenry07** [comment]
Hi! Let's combine 1&2 into a single step, and remove step 4.

**Comment by chloedotbrown** [comment]
Hi @vhenry07 - your funnel has been updated and the data has been QA'ed. Your revised [dashboard](https://va-gov.domo.com/page/447193050) is now good to go! 

Closing out this ticket, but feel free to reach out with any other questions in the future.
