### ISSUE TITLE
Add text and PDF link to Navy/Coast Guard ships page (Disability hub)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2794]
Per Agent Orange > Blue Water Navy various changes, we need to ADD BACK a link to this updated ships list. Desired ETA - Monday, 10/28 daily deploy.

SME revoking previous request to remove: "Per Laurine Carson’s  guidance, 'Until further notice, the ships list must be maintained and the policies for its use are still effective.  There are several factors that must be considered before this list is permanently discontinued.' ”

Add the PDF link to this Navy or Coast Guards ships page: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/

I recommend using a "More information" component at the bottom of the page and adding a link and teaser text there - but open to guidance. See suggested text below.

Attached is updated ships list document (with new ships; and contextual blurb & link at the top for ppl getting to the raw PDF from organic search).

[https://app.zenhub.com/files/133843125/39471112-597a-4bd5-b97c-036337f91cac/download](https://app.zenhub.com/files/133843125/39471112-597a-4bd5-b97c-036337f91cac/download)

Link text: 
Get more information [H2]
Ships that had contact with Agent Orange
Find out if the ship you were on had contact with Agent Orange. Download the list of ships (PDF)

@RLHecht:  Instead of hosting this PDF  in GitHub as we had before, I recommend moving this into Drupal. (So in future, VBA/Misty's team can upload updated ship list themselves.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I uploaded the PDF to Drupal and added this teaser text to the Agent Orange page, but I Slacked Kevin to help me figure out the URL to use for the PDF. As soon as I get that URL in, the page will be ready to go for Monday's deploy.

**Comment by RLHecht** [comment]
@jenniferlee-dsva This page is now ready for you to review and publish in Drupal. I changed the ships list PDF info to a related link now that it is pulling from Github and not Drupal for the time being.

**Comment by RLHecht** [comment]
This page is published. Moving to validate and will check after today's deploy. @Karak888

**Comment by Karak888** [comment]
Thanks @RLHecht!  @kelsonic would you mind being on standby for this to review as well to ensure it got into today's deploy?

**Comment by kelsonic** [comment]
Of course! @RLHecht Could you give me steps to validate?

**Comment by RLHecht** [comment]
@kelsonic Jen Lee published in Drupal earlier so it should be good in today's Deploy. The link at the bottom of the page pointing to the Ships LIst PDF should go to a new one that's now in the assets folder, which has yesterday's date at the top. It looks like this. If that all works then it's validated!
<img width="720" alt="Screen Shot 2019-10-29 at 1 15 27 PM" src="https://user-images.githubusercontent.com/48728214/67796413-64654280-fa56-11e9-905c-2ca6bc60a699.png">

**Comment by kelsonic** [comment]
[Validated here](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/) successfully! Looks great! :)

**Comment by Karak888** [comment]
Thanks!!!!

**Comment by RLHecht** [comment]
@kelsonic This looks like it's still showing how it was set up in yesterday's deploy. We reworked it today. Originally we had the file pulling from Drupal but now we had to put it back in the assets folder in Github so it should open the PDF and not automatically download.

**Comment by RLHecht** [comment]
@kelsonic and @Karak888 I just refreshed the page and it's now all good. Closing this issue!
