### ISSUE TITLE
Access for Kha Huynh

### ISSUE THREAD

**Issue by khathuynh-tw** [department-of-veterans-affairs/va.gov-team#27951]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > N/A
- Please provide your name.
   > Kha Huynh
- Please Provide your email.
   > kha.huynh@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Orchid (Virtual agent (chatbot) for VA.gov), developer, Thoughtworks

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCYpKCpAHHn3w3CFdDYbeFkbxqTOJf4PBo+Ha427In8q2ME9waJcZFDq92ZbM5n1twDqD5f8hgNspFcPWALlMe0DJhfZ+cbytpwCLT0wZF0gmnSp8xTvNXUiOd6yWjzdVw/9OIbR8uUHYcsEQ8DZr4FNKWuoPbPj9NVPZVUYWM2M4bjsYQfiaDwTs6G4JBoSKRo6s6jdOoE7MXWLCjzjlyIXaFIOv/6SbhKQxAEGAfYG+jI9O/G6NucO6aPt1AZmJ9153nKAvJzgjYZHbk58Tiwa54DAenk+mJURZyxwNLVBjkmSfoy2NWZ0a8dMvdQsmLPpaz+qQtYA9k+Ja7RAlTskJ8H+7M+Q7nbNmJUyssWaetlNHgf6lOfwJ0WMbyBoCQj7unlnwQAgJQ3nuS/ufcomb98TJdxIroZ8FJQIAUeuesXXlr2gNIIDiVqD/Kb5mfs2ToTrekJFFwl+RR9LLTodCOI30SFGxYZ3ts1wz6iPmz+T1Cl0dbkLAzF0vHmdp8= khahuynh
```

- Grant AWS Console access?
  > NO

**Comment by khathuynh-tw** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by khathuynh-tw** [comment]
COR is Cecilia Lee, cecilia.lee@va.gov.

**Comment by mydesignrocks** [comment]
Hello @khathuynh-tw - your socks access has been granted. Please follow these instructions as next steps: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md
If you need support, please reach out to #vfs-platform-support slack channel with a /support request.

**Comment by khathuynh-tw** [comment]
As a developer on the Virtual Agent Chatbot team, I would like AWS Console Access so that I can manage secrets for our applications that live in the AWS store.

**Comment by mydesignrocks** [comment]
@mchelen-gov please review for aws access.

**Comment by mchelen-gov** [comment]
@mydesignrocks EQIP transmittal date confirmed, access approved 👍
