### ISSUE TITLE
Create AWS group for the FE Tools team

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#27950]
## Description
Inside AWS, we would like to have an FE Tools group for members of the FE Tools team with permissions that allow us to at least view the following buckets:
- apps.dev.va.gov
- staging-va-gov-assets
- prod-va-gov-assets

## Background/context/resources
I [requested permissions](https://dsva.slack.com/archives/CBU0KDSB1/p1627396663022100) to view the contents of these buckets as a support request and @mydesignrocks suggested that we create a group with all the right permissions that we can then add myself and others on the FE Tools team to so Ops doesn't have to manage these permissions individually. 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@k80bowman - It looks like @mydesignrocks may have added the necessary permissions. Can you please check when you have the chance? Thank you.

**Comment by k80bowman** [comment]
@jhouse-solvd - I checked yesterday and I do not have the necessary permissions yet. I spoke with @theodur, however, and it seems he does have the correct permissions. So maybe his account could be an example.

**Comment by k80bowman** [comment]
@theodur did a little more digging and we found that [he has been assigned to the "dsva-vfs-all" group](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf#L1726) while @oseasmoran73 and I have not. Could that be why he can see the contents of these S3 buckets and we cannot?

**Comment by jhouse-solvd** [comment]
@jbritt1 - As time allows, could you take a peek at this and see if there's a quick resolution for the FE Tools team on this one?

**Comment by k80bowman** [comment]
I'm now able to see the content on those buckets! Thank you all very much.

**Comment by jbritt1** [comment]
> I'm now able to see the content on those buckets! Thank you all very much.

Thank you for confirming. Closing, please reopen if any issues arise.
