### ISSUE TITLE
Modularize the Webpack config

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2796]
## Problem Statement
The Webpack config is getting unwieldy and—worse—hard to understand. There are ways we can simplify it. See https://survivejs.com/webpack/developing/composing-configuration/ for inspiration.

## Goal
Engineers can look at the configuration and easily understand what it's doing.

## Acceptance Criteria
- [ ] A configuration file is made for each build type
- [ ] The common parts are modularized and shared between the configuration files
- [ ] All the current functionality is preserved

**Comment by timwright12** [comment]
After initial investigation, small architecture changes aren't going to solve this, better to focus on the upcoming Webpack 5 upgrade than to spend time reworking the current system.

Closing out.
