### ISSUE TITLE
Remove temporary fix for double bars

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27978]
##  Description
CMS has completed the fix mentioned on #27061. Search & Discover now needs to remove the temporary fix that was implemented

## Background 
GH #27061
[Slack comment from CMS](https://dsva.slack.com/archives/C52CL1PKQ/p1627320136238500?thread_ts=1626870601.166400&cid=C52CL1PKQ) 

## Acceptance Criteria
- [ ] Confirm CMS fix has gone live
- [ ] Remove temporary fix
- [ ] Validate that the text after the double bars does not appear in the search results
- [ ] Tier 3 (No Socks validation necessary)

**Comment by srsuddath** [comment]
We are not able to implement this ticket currently, there are more cms changes needed
