### ISSUE TITLE
Updates designs post midpoint review

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27994]
##  Description
Anticipating feedback from midpoint review will highlight the need to refine the designs before we create the prototype for usability testing. 

## Background 
midpoint review is scheduled for August 3, 2021 @3:30pm EST

## Acceptance Criteria
- [x] Update the designs (desktop and mobile) with new descriptions and any feedback comments from midpoint review/’design intent’ meeting 
- [x] Create descriptions for search landing page
- [x] Create design using gray boxes and descriptions in place of the original three example links.
- [x] Connect with Beth to approve the descriptions and link titles on the search landing page design

**Comment by mgleo** [comment]
Designs to incorporate into prototype. (tagging @sshein for awareness)

![d-homepage.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/960e0274-de5b-44e1-a001-17497d467358)
![d-landing.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/f3454d49-0928-49ef-b431-ebf0e203fc44)
![d-results.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/209d0b40-dd94-4146-8736-c420ee80b61f)
![m-homepage.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/6a684ebb-36bd-4b72-80a7-f5ee199088a3)
![m-landing.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/58b656b4-d055-43f7-8fe8-9b9423ec3869)
![m-results.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/dc039953-8f1a-4d11-bbd8-092c463cd629)

**Comment by denisecoveyduc** [comment]
@mgleo These look great! Nice work!!

I know this work was increased because of the many changes, do you think we should bump up the estimate larger than 5 to reflect that or had you accounted for that when you added the sizing?
