### ISSUE TITLE
Exploration: Review video results when all sources area added

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#27999]
##  Description
Review video results after the additional channels have been added to search.gov
Additonal channels to add:
[VHA: Veterans Health Administration](https://www.youtube.com/user/VeteransHealthAdmin)
[NCC: National Cemetery Administration](https://www.youtube.com/channel/UCL9c-s2Jgr_viIRccUeby1w/featured)

## Background 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27047

## Acceptance Criteria
- [x] Megan to review video results and assess user experience.

**Comment by mgleo** [comment]
The following bugs were found on the Search.gov preview in regards to video:

- One video result shown on "Everything" results does not always match first video result on "Videos" tab.
- One video result not always showing on "Everything" results tab even when there are video results.
- Some search terms pull up video results from random YouTube channels not listed on search.gov's admin.

Search term: "**form**"
![form-text.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/7eac85e1-17ae-47db-a9e2-14be583efb9c)
![form-video.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/d8652b0d-719d-4a6b-8b38-41e56cef08ca)

Search term: "**travel pay**"
![travel-pay-text.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/50fece02-1415-4491-9909-bfa06b54a72d)
![travel-pay-video.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/d02503d8-a06d-494b-b6c0-9d1f07bd8e81)


Search term: "**garden**"
![garden-text.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/b63be29e-f2fe-4bd0-9035-02af2481a675)
![garden-video.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/d7686aec-bcb2-41fa-a52a-59f8f6131a39)

**Comment by denisecoveyduc** [comment]
Great work @mgleo ! Let's pull this into an email to send over to search.gov to further the discussions. Drafting now and will add the final [send copy for our records](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/meeting-notes/search.gov/search-gov-meeting-notes.md).
