### ISSUE TITLE
VA.gov - mobile view bug in footer, Contact Us accordion does not open and crisis line info is missing

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#2799]
<img width="501" alt="va-gov-contactus-bug" src="https://user-images.githubusercontent.com/57469/67681024-e3794e80-f962-11e9-9143-1d84a6bc1de9.png">

## What happened?

Viewing VA.gov on a mobile screen width, and then also on my mobile device, I attempted to click Contact Us, but nothing happened. Expanded my screen on desktop, and the info is displayed not in an accordion. The other accordion options beneath Contact us open fine.

## Specs:
- Device: MacBook, iPhone
- Browser: Chrome on MacBook, Safari on iOS
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL:  VA.gov
- Test User _(if applicable)_: N/A

## Desired behavior

The Contact Us accordion option should open and reveal contact information when a person taps or clicks or selects Contact Us in the viewports beneath ~600px. 

## Acceptance Criteria

The Contact Us accordion option should open and reveal contact information when a person taps or clicks or selects Contact Us in the viewports beneath ~600px. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** product support
- [x] **Labeled with Practice Area** frontend
- [x] **Labeled with `Bug`**

**Comment by lizlantz** [comment]
The Crisis information is also missing on mobile view.   

Quick peek under the hood, maybe a clue: looking at the mark-up and ID names, it looks like the Contact Us content is in the `#veteran-criss` div. Not sure if the original intent was for the crisis info to be it's own accordion, and the contact info is mistakenly a child of `#veteran-crisis`, or if the id should actually be `#contact-us` and the crisis info would also appear under Contact...

![image](https://user-images.githubusercontent.com/6371287/67708513-a927a580-f992-11e9-83ee-9d3b336f74c4.png)

**Comment by Karak888** [comment]
@lizlantz I am going to pull this into the backlog to be groomed. Great detective work (will need FE engineer I suppose at some point)

**Comment by Mottie** [comment]
The Crisis Line still shows up as a red banner at the top of the page. Clicking on it opens a modal with information. Maybe that's why it was omitted in the mobile footer?

The accordion is not working because of an inline `onClick` handler for analytics tracking.

```diff
          <button
-           onClick={recordEvent({ event: 'nav-jumplink-click' })}
+           onClick={() => recordEvent({ event: 'nav-jumplink-click' })}
            className="usa-button-unstyled usa-accordion-button va-footer-button"
            aria-controls="veteran-contact"
            itemProp="name"
            aria-expanded="false"
          >
            Contact us
          </button>
```

It was working before ([this above change](https://github.com/department-of-veterans-affairs/vets-website/pull/10879/files#diff-012c01408a39e1e5893dab912297e60fR15)); but then the `recordEvent` wasn't working.

Even an empty `onClick` function breaks the button click.

One possible fix would be to move the `onClick` to the the `<li>` above the element, but then you'll get this accessibility error - `jsx-a11y/no-noninteractive-element-interactions` - but I'm sure if that matters in this case.

**Comment by jenstrickland** [comment]
@Mottie What do you think of moving the onclick event to the individual Contact Us items? Is there a way to track which of the contact us items gets clicked, instead of the accordion? It seems that could be more informative as far as metrics go.

**Comment by Karak888** [comment]
@jenniferlee-dsva just a reminder we will need to get a FE Engineer to help us work on this as @ndsprinkle is unavailable to work on this.  thanks!

**Comment by Mottie** [comment]
> What do you think of moving the onclick event to the individual Contact Us items?

That should be possible, but I don't know what metrics are important and who determines what needs to be tracked.

**Comment by nedierecel** [comment]
@Mottie @jenstrickland For the individual items under Contact Us, these should fire `nav-footer-contact` events so we can track interactions. 

The intent for the `nav-jumplink-click` event was for jumplink interactions like the ones on Pittsburgh Health (here in screenshot):

![image](https://user-images.githubusercontent.com/24525739/67959965-f04eaa00-fbcf-11e9-9505-b8e86bd71fd2.png)

Next Steps for Analytics-Insights:
1. @jonwehausen - Confirming the implementation with you: should the Contact Us accordion use a `nav-accordion-expand` in lieu of the `nav-jumplink-click`? 
2. @Karak888 - We'll be back in touch on what to do with the Contact Us event.

**Comment by nedierecel** [comment]
@jenstrickland - Threading a quick update from the Slack in VSA-Public channel. Let's remove the problematic `nav-jumplink-click` to make sure our users can access the menu. We will make a recommendation at a later date on the accordion tracking.

**Comment by jonwehausen** [comment]
> @Mottie @jenstrickland For the individual items under Contact Us, these should fire `nav-footer-contact` events so we can track interactions.
> 
> The intent for the `nav-jumplink-click` event was for jumplink interactions like the ones on Pittsburgh Health (here in screenshot):
> 
> ![image](https://user-images.githubusercontent.com/24525739/67959965-f04eaa00-fbcf-11e9-9505-b8e86bd71fd2.png)
> 
> Next Steps for Analytics-Insights:
> 
> 1. @jonwehausen - Confirming the implementation with you: should the Contact Us accordion use a `nav-accordion-expand` in lieu of the `nav-jumplink-click`?
> 2. @Karak888 - We'll be back in touch on what to do with the Contact Us event.
 
Correct Nedie

**Comment by Mottie** [comment]
This issue has been fixed, but it is not yet available in production. Do we need to keep this issue open to track the analytics changes, or is that described in another issue?

**Comment by andaleliz** [comment]
The analytics changes aren't described elsewhere, as far as I know.  

Does the crisis info appear in the footer, now that the accordion is working, @Mottie ?

**Comment by Mottie** [comment]
> Does the crisis info appear in the footer, now that the accordion is working

No it does not

![Screen Shot 2019-10-31 at 2 20 06 PM](https://user-images.githubusercontent.com/136959/67979090-96f37480-fbe9-11e9-8c82-d304c9d516d0.png)

**Comment by andaleliz** [comment]
@andrewlewandowski The Crisis Line Info content in the footer disappears on mobile. Do you know if this is intentional or a bug?

**Comment by andrewlewandowski** [comment]
@andaleliz - The crisis line goes away in the footer on mobile. This is intentional.

**Comment by andaleliz** [comment]
@andrewlewandowski Thanks for clarifying! @jenstrickland and I were thinking it's a bug, and feel that it should display - will open a separate issue as an improvement suggestion if that's the case.

**Comment by andrewlewandowski** [comment]
Cool! I would recommend folding in the "In crisis? Get help now" heading and Veterans Crisis Line link under the "Contact us" heading/column. That way, there's no mobile-adaptive changes (other than putting the "Contact us" column in the first spot on mobile).

**Comment by Karak888** [comment]
moving to close this ticket - If caregivers are having a hard time finding that info we can create a ticket to do an actual design.
