### ISSUE TITLE
Use custom application Sentry event tag

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#280]
## User Story
As a VSP or VFS engineer, I need to easily find all the Sentry issues for the application I'm working on or assigned to so I can triage problems properly.

## Goal
Every event sent to Sentry from within an application gets an `application` tag that's unique to the app.
The tag is set automagically, requiring no extra setup from engineers.

## Assumptions
- Once we set the scope, it'll persist for each event caught without having to set it for each individual event
- After we have the tag in the captured event, we'll be able to search for it in Sentry
  - From what I can tell, this shouldn't be a problem

## Acceptance Criteria
- [ ] A system is set up that uses the application name as a custom Sentry tag for all Sentry events caught
- [ ] Documentation is written (somewhere) that explains how to find all the errors for a given front end app

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
This may depend on #275. We can possibly do something like `Sentry.setScope` with the Raven client, but I'm not sure yet.

**Comment by cvalarida** [comment]
Good news! This is actually already a thing. We use the `source` tag to track this. That just leaves documentation (assuming that's not also done already). It's probably worth investigating whether this is behaving as expected.

**Comment by minafarzad** [comment]
OBE because it's already a thing that jeff already did, thanks jeff!
