### ISSUE TITLE
CT Redesign: "Skip to your estimated benefits" link should be hidden

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#28005]
As a user tabs through the various fields in the "Calculate your benefits" section of a profile page in the CT, they will eventually tab to a "Skip to your estimated benefits" link. This link should be hidden until the user tabs to it. The  "Skip to your estimated benefits" should show under the "Update benefits" button for each of the four accordions under "Calculate your benefits". Currently, the link displays in various positions around the profile page header on screen 1200px wide and smaller.

### Steps to reproduce
1. Access https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/11929140 and reduce screen size to 1200px wide or smaller

### Expected behavior
"Skip to your estimated benefits" link is only visible in the correct location when the user tabs to it.
![Screen Shot 2021-07-28 at 11.28.52 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/16aede94-7d18-4eff-afd7-31715ac64554)

### Actual behavior
"Skip to your estimated benefits" link is displayed near the top of the page

https://user-images.githubusercontent.com/45575003/127362294-997f94df-c1ae-43b9-8f4b-94c47eb6f4f0.mov

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18045
