### ISSUE TITLE
Updates for Blue Water Navy Vietnam Veterans Act of 2019- (effective oct. 27, 2019)

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2800]
**Overview:**
To support the Blue Water Navy Vietnam Veterans Act of 2019, the following updates need to be made to VA.gov by October 28th, 2019: 
- [x] Update and replace current PDF 
- [x] Add second PDF of expanded Frequently Asked Questions

This is the link to update: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/

This is the section, and the last sentence is the one to be edited:
What if I’m a Blue Water Navy Veteran, and VA denied my claim in the past?
If we denied your claim because we determined that your disability wasn’t caused—or made worse—by your active-duty service, you can file a new claim based on the change in law.

In certain cases, if we approve your claim, we’ll pay you back to the date when you submitted your original claim. We refer to this as retroactive payment. 

Find out how to file a claim for disability compensation

If you have more questions about this change in law, please read our fact sheet on Blue Water Navy Veterans and Agent Orange (PDF).

**Comment by AnneHurley** [comment]
@RLHecht  Here is the new sentence with the suggested two new links. Updated PDF is attached for more information/fact sheet, and 2nd doc is a word doc that presumably we can turn into a PDF, for the expanded frequently asked questions.

New text:

If you have more questions about this change in law, please see these helpful documents:

The fact sheet on Blue Water Navy Veterans and Agent Orange (PDF)
A list of frequently asked questions (FAQ) about the benefits (PDF)

@RLHecht  The above two links can replace the current single one. @Karak888 for visibility

**Comment by RLHecht** [comment]
@AnneHurley @jenniferlee-dsva @Karak888 These PDFs are now uploaded to Github and the links have been changed in Drupal with the new text from Anne above. Kelson added the PDFs to the assets repo, which won't merge until tomorrow's deploy. Therefore when you preview the page in Drupal, the PDFs don't show up. This is the same method we used for the ships list PDF so they should be good once both deploys happen. I pinged Kevin to confirm that I put in the correct URLs and am waiting to hear back. Once I do, Jen can review and publish.

**Comment by AnneHurley** [comment]
@RLHecht @jenniferlee-dsva @Karak888  Thanks so much, this sounds great. Question - Renee asked that these changes be live no later than 1 p.m. tomorrow, Oct. 30 - will we make that deadline waiting for tomorrow's deploy?

**Comment by RLHecht** [comment]
@AnneHurley @jenniferlee-dsva @Karak888 I'm so sorry I didn't think about the fact that the daily deploy happens later than when they want it live. Jen, do you think we should do a daily deploy? If so, it would need to be both Github and Drupal since the PDFs are in Github and that PR needs to merge where we uploaded them to the assets repo in order for the links to work on the page.

**Comment by Karak888** [comment]
good call @AnneHurley and thanks for bringing it up this morning @RLHecht .

**Comment by jenniferlee-dsva** [comment]
If it didn't go live with yesterday's afternoon deployment, then yes, you'll need to request a special content-only deploy from FE engineer - and make sure it's for both Drupal page in question + GitHub PR with the new PDFs.  I would reach out to Nick Sprinkles in Kelson/Nick's absence.

**Comment by RLHecht** [comment]
Thanks. @jenniferlee-dsva Can you review and publish the Drupal page? Then we can have Nick Sprinkle do the content-only deploy. Kara, who should reach out to him?

**Comment by jenniferlee-dsva** [comment]
sure, what is the drupal page link?

**Comment by Karak888** [comment]
I'll reach out to Kelson not leaving this to someone who doesn't know our process.

**Comment by RLHecht** [comment]
Node ID 876 Agent Orange Exposure on Navy or Coast Guard ships

**Comment by jenniferlee-dsva** [comment]
Also - I removed duplicate links: 

![image](https://user-images.githubusercontent.com/43381063/67864477-0db24400-fafc-11e9-905c-d39b220eb10f.png)

**Comment by AnneHurley** [comment]
@Karak888  @jenniferlee-dsva  Can we close this ticket? We may still want a ticket to address the search results, but I think this work is done ^ yes?
