### ISSUE TITLE
Discharge Upgrade Wizard: Create Mural Board of Content Changes

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#28002]
## Issue Description
Based on the changes described in #27143 generate a Mural board illustrating where the new content changes will be inserted relative to the existing user flow/logic.    

---
## Acceptance Criteria
- [x]  A Mural flow chart showing the current user flow is created and linked here.
- [x]  Places where content changes will occur are denoted on the flowchart
- [x]  Places where the wizard logic will be altered are denoted on the flowchart
- [ ]  When ready, ask Marci to schedule a work breakdown meeting so we can create relevant stories for completing the work
- [ ]  Each story is estimated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by callen2563** [comment]
@MarciMcGuireGCIO Zac and I met and discussed the Mural flow and we determined that we need to set up a meeting with content to walk them through the flow in order for me to mock up the two pages with correct verbiage.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 Thanks!  Wow - that is quite a flowchart.  Would you like me to schedule that meeting with Content?

**Comment by callen2563** [comment]
@MarciMcGuireGCIO Yes it is! Thanks to @zacharymorel for that chart! Just to be ultra clear here are the two places we determined that the domestic assault questions need to be added. If you could set up a meeting with content so we can go over the flow and pages that would be great! 

<img width="706" alt="Screen Shot 2021-08-03 at 4 24 59 PM" src="https://user-images.githubusercontent.com/68560244/128081490-72f368ca-c6d0-448a-96c6-398497b9def3.png">
<img width="794" alt="Screen Shot 2021-08-03 at 4 24 43 PM" src="https://user-images.githubusercontent.com/68560244/128081500-0c745ef8-dfc7-49fa-88a7-2d74c5a19987.png">
