### ISSUE TITLE
[MCP] Replace new login experience with established pattern

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#28010]
## Issue Description
After the design council meeting, it was determined that the redesign of the login experience from the content page would be reevaluated by another team. We have to use the current established pattern instead. 

---
## Tasks
- [x] Switch out the pattern for the existing one

## Acceptance Criteria
- [x] Pattern replaced and uploaded to UXPin

**Comment by rileyorr** [comment]
I'm playing around with how we could draw attention to the tool's features before users log in using the existing sign-in widget and I have three options:
- [Bullet points within the sign in alert](https://preview.uxpin.com/aaa18573afb5e4a4b9967a35be14696a20490811#/pages/140666253/simulate/no-panels?mode=i)
This is most similar to how we laid out the information in the online tool card.
- [Full sentences within the sign in alert](https://preview.uxpin.com/aaa18573afb5e4a4b9967a35be14696a20490811#/pages/140666252/simulate/no-panels?mode=i)
I based this format off the sign-in alert component in the VA design system Sketch library - I couldn't find a similar example on staging
- [Additional section below the sign-in alert highlighting what can be accomplished within the tool](https://preview.uxpin.com/aaa18573afb5e4a4b9967a35be14696a20490811#/pages/140666251/simulate/no-panels?mode=i)
I've seen a lot of examples of this on the site including [the Claim Status Tool](https://staging.va.gov/claim-or-appeal-status/) and [VA lab and test results tool](https://staging.va.gov/health-care/view-test-and-lab-results/). 

I'm going to be attending today's content office hours to chat about the different options and deduce the option we want to go with.

**Comment by rileyorr** [comment]
Met with Danielle & Beth and incorporated their feedback. I've send the adjusted alert over for content review. This work is being tracked in the MCP content ticket ([view here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27780)).

**Comment by rileyorr** [comment]
@LindaLi123 due to the amount of content we've changed this sprint, I requested a full content review of the entire prototype. I think we're good to close this out. I'll just open another ticket when Danielle's review is complete so we can incorporate her updates!
