### ISSUE TITLE
[Forward Proxy] Investigate obfuscating secret key when connecting to Search.gov

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#28024]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Here is the following platform-support threat that spawned this ticket : https://dsva.slack.com/archives/CBU0KDSB1/p1627485560058900

## Background/context/resources
Here are the requirements that we need to meet
Currently we are hitting a search.gov API and need to obfuscate the secret key. to accomplish this we have a custom vets-api endpoint that takes a request, tacks on the api key, and then hits search.gov's api.

Making requests this way is slow and introduces a LOT of lag into the user experience, which can have some very negative effects on some of our pages. We would like to investigate ways to move this secret key obfuscation out of vets-api and into a proxy layer, so that we can have a quicker response time with these requests

- Operations notes:
We could add this as an endpoint on the fwdproxy, essentially a new TCP port that would get routed to search.gov, and would add a header to the outgoing traffic including the authentication header.
  - Needs:
    - New secret added to parameter store for key (or re-use existing)
    - new fwdproxy pass-through added for search.gov that is configured to add the header to the request

  - Notes: Determine what is causing the latency in the request... It may be an extra round trip through the TIC because the request is likely going out to the internet. If this is the case, doing the above may not help the latency, as we would only be moving the request to the fwdproxy, and not alleviating the extra round trip.
  - Experimentation with making this request from inside the VA network needs to be performed to see if the fwdproxy method would give any latency reduction

## Tasks
- [ ] Determine a more time-efficient manner to both hide api keys and provide a "pass-through" endpoint to reach search.gov's endpoints (multiple)

## Definition of Done
- [ ] We have a method to improve the responsiveness of these endpoints

**Comment by jhouse-solvd** [comment]
@srsuddath - Is there anything that you need from the Platform Operations team? I noticed that it was tagged with the "operations" label, but wasn't clear from the body of the ticket what might be needed.

**Comment by srsuddath** [comment]
@jhouse-solvd sorry for the late reply, the notification got lost in my feed.

This ticket is actually entirely for the Operations team, If you look at the original conversation linked in the body, @dginther suggested I open this ops ticket so you all could investigate a more efficient manner to hit one of our service provider endpoints without having to go all the way through Vets-API

**Comment by ph-One** [comment]
There is no need for this at this time.
