### ISSUE TITLE
Vet Center alert content update - Facilities team

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#28026]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[x] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[ ] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

- Looking for input on the "Non-traditional hours" phrase associated with the Vet Center alert
     - Is there a more easily understandable phrase that would work here?
     - Any other examples of similar wording we can reuse?

- Also looking for input on alert content itself
     - Calling the Vet Center main number (407-857-2800 below), during "non-traditional" hours automatically forwards to the Vet Center call center (877-927-8387 in alert below). We may not need the number in the alert, in which case the wording should inform Vets of the auto-forwarding.

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/84a6d773-0e04-4de6-8930-2818cb7a058f)

## When does this content work need to be done?

End of the week (7/30) if possible.

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Facilities
-	OCTO-DE product owner: @davidconlon 
-	Product manager: @mmiddaugh 
-	Designer: @nicko-amida 
-	FE engineer: 
-	Product/team Slack channel:

## Links to related tickets

[Revisit Vet Center alert #25625](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25625)

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
@mnorthuis @shiragoodman @peggygannon for awareness

**Comment by peggygannon** [comment]
Thanks, @RLHecht  

also, fyi, I'm sharing a link to the [Platform content feedback](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/24857) I gave the team in May when they brought this through the Collaboration Cycle.

**Comment by bethpottsVADEPO** [comment]
@peggygannon thanks for the further context.
@nicko-amida here's some text that I hope gets at what you're trying to achieve. Once it's incorporated into mockups, would you tag me so I can see how it looks/works? Thanks!

**Current:**
**Non-traditional hours are also available. Call 407-857-2800 to find out more.**

**New:** (It might be best not to bold this so it doesn't compete in prominence with the alert text)
Option 1 (longer version): We're also open additional hours. We don't list them here because they can change to meet current needs. Call us at 407-857-2800 to find out what our additional hours are right now.
Option 2 (shorter version): We're also open additional hours not listed here. Call us at 407-867-2800 to find out what our additional hours are right now. 

**Current:**
**How do I talk to someone right now?**
The Vet Center call center is available 24/7:
877-927-8387

**New:**
**How do I talk to someone right now?**
You can call the Vet Center at 877-927-8387. We're here 24/7.

**Comment by nicko-amida** [comment]
@peggygannon @bethpotts Thank you both!

**Comment by nicko-amida** [comment]
Hi @bethpotts I'm back in the office - I have some [updates to show you](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/140708775/simulate/sitemap?mode=i), based on your previous suggestions. I can submit a new ticket if needs be.

**Comment by bethpottsVADEPO** [comment]
@nicko-amida Want to see if this works. It may be too long. Can you try it and see how it looks? Option 2 is shorter (I added "anytime" before the phone number and removed the last sentence "we're here 24/7")

OPTION 1 
**You can call us after hours too**
If our local office is closed, we'll transfer you to the main Vet Center. Or you can call our main number directly at 877-927-8387. We're here 24/7.

OPTION 2 
**You can call us after hours too**
If our local office is closed, we'll transfer you to the main Vet Center. Or you can call our main number directly anytime at 877-927-8387.

**Comment by nicko-amida** [comment]
@bethpotts Ok thanks, I'll send an update using these examples.

**Comment by nicko-amida** [comment]
@bethpotts Here's an update with your recent suggestions: 
![image](https://user-images.githubusercontent.com/81988788/129384774-4ce64853-c848-4e16-935c-d87fdeb16546.png)
I don't think it's too long, actually. I like the "anytime" version  better.

**Comment by bethpottsVADEPO** [comment]
@nicko-amida If there's no need to include the 24/7 language, then I agree with going with the "anytime" version on the right. There are 2 small tweaks I'll call out:
1/ Remove the period in the header.
2/ Remove the colon before the phone number. 

I think this works great!

**Comment by nicko-amida** [comment]
@bethpotts Closing out this issue. Thanks for the help!
![image](https://user-images.githubusercontent.com/81988788/129572508-562b6014-7d12-4d6d-b3c3-a0e879152bcd.png)
