### ISSUE TITLE
AWS Access for Oseas Moran

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#28048]
I already have access to SOCKS, but need access to AWS

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Oseas Moran
- Please Provide your email.
   > oseas.moran@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Front End Tools, Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > NO

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
    - S3 and SSM for Github Actions initiative being worked on
    - [SSM ticket opened](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27495)

**Comment by mydesignrocks** [comment]
@drorva or @mchelen - can you please review for AWS access. thanks!

**Comment by drorva** [comment]
Request sent to Nancy Smith the GTL.

**Comment by drorva** [comment]
Approved

**Comment by mchelen-gov** [comment]
@mydesignrocks looks like this is resolved?

**Comment by mydesignrocks** [comment]
AWS access granted and initial password with steps to login has been communicated over DM
