### ISSUE TITLE
Analytics Implementation or QA Support for [eBenefits - Certificate of Eligibility]

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#28040]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics Implimentation

- Who is this request for?
Jason Wolf and Jesse Cohn

    
- What team/project is this work for?
    _this adds context for the data_
    
    - eBenefits
    
- Provide the Domain where Google Analytics needs to be implemented

    - www.staging.va.gov/housing-assistance/home-loans/apply-for-coe-form-26-1880
    
   
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - NA

- Please provide website interactions to Track
We will only be using the standard events that come with the form system, but we need to know what label to use

    _Design System components are automatically tracked. [Read more here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md#other-important-things) to see which Design System components are opt in or opt out. You do not need to specify on this ticket which components you are tracking unless you are opting in._

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - www.staging.va.gov/housing-assistance/home-loans/apply-for-coe-form-26-1880
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - NA

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by joanneesteban** [comment]
Hi @cohnjesse & @jason-gcio ! Do you have a launch date for the Certificate of Eligibility?

**Comment by jason-gcio** [comment]
Not at this time, we are working on getting into staging

**Comment by laurensimpson14** [comment]
Hi @jason-gcio 👋 Below is a QA chart of everything that is currently tracked on http://www.staging.va.gov/housing-assistance/home-loans/apply-for-coe-form-26-1880.

| Interaction | Screenshot of Interaction | QA Screenshot | Status |
| -- | -- | -- | -- |
| Pageviews | N/A | ![image](https://user-images.githubusercontent.com/80417436/132704659-4f19aeff-af12-42fe-8191-13a72337c83d.png) | 🟢 Tracking Correctly |
| Clicks to `Eligibility requirements for VA home loan programs` | ![image](https://user-images.githubusercontent.com/80417436/132704883-c65014d6-6402-42a1-9bf1-2ae97f6c6f50.png) | 🟡 This link does not currently lead to another page, will it in the future? |
| Accordion Expands | ![image](https://user-images.githubusercontent.com/80417436/132705139-dc575b41-5b1f-468c-877f-46477a5c5705.png) | ![image](https://user-images.githubusercontent.com/80417436/132705176-cbf790eb-4a44-43ef-86bd-994fcd202998.png) | 🟢 Tracking Correctly |
| Clicks to `Privacy Act Statement` | ![image](https://user-images.githubusercontent.com/80417436/132705428-e7708cde-c594-481f-8847-14cf7ea242d3.png) | ![image](https://user-images.githubusercontent.com/80417436/132705350-95295c2c-111c-4cba-b41f-77cfc6bc5a7c.png) | 🟢 Tracking Correctly |
| Phone Clicks | ![image](https://user-images.githubusercontent.com/80417436/132705526-473d0d9b-f886-4d1f-a307-ac6b646ecadf.png) | ![image](https://user-images.githubusercontent.com/80417436/132705560-82a6d1d2-fdc2-43f0-a00c-697e48bbba4b.png) | 🟢 Tracking Correctly |
| Clicks to `Apply for a Certificate of Eligibility` | ![image](https://user-images.githubusercontent.com/80417436/132705768-6560e79d-8eca-44aa-a6a0-24365cfdb85d.png) | N/A | 🟢 Tracking Correctly - Tracked using `previous page path` metric in GA |

Here is a list of the [Form Events](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Form-Events.1840808051.html). We'll need you to add a prefix of `ebenefits-26-1880-`. Once the prefix is added please let me know, and I can QA the Form Events.

**Comment by joanneesteban** [comment]
@jason-gcio let us know when the prefix is added, and we can continue QA!

**Comment by joanneesteban** [comment]
@jason-gcio - following up with this. We can QA on our end when y'all are ready!

**Comment by laurensimpson14** [comment]
Closing this ticket since. Please feel free to re-open if anything additional is needed or if you have any questions!
