### ISSUE TITLE
Cleanup Build Script in vets-website 

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#28041]
## Details 

Now that the content build is removed from the `vets-website` repo, the [build script](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.sh) can be updated. We may be able to preferably remove `build.sh` entirely and directly use `yarn build:webpack` for builds.

Some things to note:
- `build.sh` is [copying](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.sh#L68) the vendor entry to the shared modules entry. Figure out if this is still needed, or if a better approach can be taken
- Figure out if `jenkins/build.sh` is still needed. We will be migrating to GitHub Actions soon, so this may be irrelevant when that happens
- Verify that once complete, the build command accepts arguments similarly to the `watch` command. Currently, `yarn watch` accepts arguments in the form of `--env.api` while `yarn build` accepts arguments in the form of `--api`. This adds confusion for VFS developers. More context [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25656).

**Comment by CBonade** [comment]
Closing as stale. Believe this has already been addressed.
