### ISSUE TITLE
Access for Jesse Cohn

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#28045]
I am using a loaner laptop while my laptop gets fixed and I need to get Socks access on the loaner laptop.

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Jesse Cohn
- Please Provide your email.
   > jesse.cohn@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > eBenefits team, front end engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+D7B+rcrmTd/RGFcZIR9S54gePgEW4YB9y9Kko7huBJqHgdf/CkMW7PVdZ2/DZupjSXreaOzYShg9Gi8AC49WTNk8F15+ojXDfD4FjDoqLK++11fF5ACiScgdzxijU7bpwniAVxOvInOe7eTDEibndMzAtcu65meA/UPebT65K+xrctjvFeON2hfG/Q3qZAzg/xAKbEGHvEgqNxUiwl3h2Ae3JCEGWi8Pno5lxIXE1C2TDvVQ0RMfhy+cYXdlI4H1blgYVXEjw1QkpFOjzKDQShVd56i9sjGNizv3aWBtZ2Eg05hqrxrDqYRXMMbQa22zG4RG4NotSyl+AaqiiHknXDzagc/EyN5BQ3JJEBXDQIwSmS7Bf1L3NzCMTjyR2wvSvgPCOOVowiN2PcODr88NYsBtoU8t1PqplS02Qa6Kg9A0up0tivUMGBsSHviNQw+cvPOCUKoR88BY8nWbxJ96C0mvIqAmyAKwgS+ZycoaBaQtwvOrNhy8e6+qxjcMhqs= loaner@ahtmbploaner2.lan

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by cohnjesse** [comment]
@department-of-veterans-affairs/vsp-operations commenting for visibility per instructions

**Comment by mydesignrocks** [comment]
Hi @cohnjesse - your socks access for the loaner has been granted.
