### ISSUE TITLE
[Development] End Date on Temporary Address Failing

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2804]
## Problem Statement
- Currently when an End Date is added to Temporary Change of Address, an error is produced. EVSS is looking at why these errors are happening. More info to be added.
- Met with BGS 

## Goal
_Form needs to load fully without errors_

## Tasks
- [ ] _Identify problem with EVSS_
- [ ] _Omit the field in data translation for 526 (or all) submission

**Comment by Mottie** [comment]
Update: Not sure of the status on EVSS fixing the problem with forwarding (temporary) addresses, but this can not be done until it's fixed on the backend.

Related issues: #3283 & #4557

**Comment by luke-gcio** [comment]
Let's follow up with EVSS on this.  I looked for some follow-up convos with EVSS but was not able to see anything.

**Comment by luke-gcio** [comment]
![image.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/39a354ab-992a-4baf-b22f-584cb7ec2be5)

**Comment by Mottie** [comment]
This ticket still appears to bel blocked; [no action to take at this time](https://dsva.slack.com/archives/C5AGLBNRK/p1585922289120100?thread_ts=1585922059.117300&cid=C5AGLBNRK).

**Comment by luke-gcio** [comment]
Closing since this is OBE for now.  If this changes, we can reopen.
