### ISSUE TITLE
Investigate "Network is unreachable" deployment error

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#28058]
[Slack conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1627506129088400)

The deploy periodically fails because of an unreachable network when we're trying to grab the new BUILD.txt file. @alexandec suggested we might add a retry to https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-speedy-s3-assets/tasks/main.yml#L24

Let's investigate this a bit and see what we can do without sinking a lot of effort into it.

**Definition of Done**

- [ ] Root cause (or set of potential causes) has been identified
- [ ] Remediation recommendation has been made
- [ ] If remediation is under 1 week of effort, please implement

**Comment by oseasmoran73** [comment]
@timwright12 @alexandec I have not seen this occur in a good while. If we do see this again, can we add the URL so we can keep track of the log?
