### ISSUE TITLE
AWS Access for Nick Sprinkle

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#28057]
I have had SOCKS access for awhile and previously had AWS access, but now I need AWS access again.

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Nick Sprinkle
- Please Provide your email.
   > nick.sprinkle@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Front End Tools, Software Engineer, Oddball

- Requesting SSH key authorization?
   > NO

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
    - S3 and SSM for Github Actions initiative being worked on
    - [SSM ticket opened](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27495)

**Comment by mydesignrocks** [comment]
Hi @ndsprinkle - can you please provide the name of your government team lead (GTL).
cc: @drorva and @mchelen for awareness/review.

**Comment by mchelen-gov** [comment]
i think vendor onboarding rep for oddball is Amber Malcolm

**Comment by mchelen-gov** [comment]
Hi @ndsprinkle , who is your vendor onboarding representative? This is the person from your company or the primary contractor who helped you onboard at VA.

**Comment by mchelen-gov** [comment]
found them, access approved 👍

**Comment by mydesignrocks** [comment]
Nick now has aws access, closing.
