### ISSUE TITLE
Reply draft doesn't always open as it should with the To and Subject fields being non-editable

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#28050]
## What happened?
I found that a few times the reply draft didn't open to a screen with non-editable To and Subject fields, as the requirements dictate, but sometimes to a screen that looks like the original edit screen.  I have screen shots attached that show the two states I see the screen in and also screen shots of a video that shows the transition and what is happening.  The screen originally animates when the user taps on a draft with the original looking screen.  It slides over and then flashes and becomes the correct layout.  I think I was getting it a few times without it fully loading correctly.

## Specs:
- Device: iPhone XR, Samsung Galaxy Note 9
(I've actually only seen it happen on the iPhone.  I included the Samsung because I created an original draft using it, but have created draft and seen the bug with the iPhone alone.)

## Steps to Reproduce
- Before I took the video and took screen shots, I found that the first time I went to edit the DRAFT it would happen. Not every time, but more than once.  I was able to get it to happen the second I opened the same draft.

## Desired behavior
Reply screen opens with non-editable To and Subject fields, follows requirements in story.

## Acceptance Criteria
Reply screen opens with non-editable To and Subject fields, follows requirements in story.

## Bug Severity
3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app---current-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26357

## Screen shot(s) and additional information
I think that sometimes the correct screen doesn't render after the animation.  See the shots showing the animation how it starts with the wrong screen but ends up with the correct screen.

![2021-07-28_12-41-08.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/87b79ee5-464f-4119-88bd-b47dbc69e4b1)

![2021-07-28_13-25-59.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/e0abcd72-346c-4465-b3df-999a7c109e5d)

**Comment by narin** [comment]
I don't think it made it in the QA build but this should be resolved with this PR: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/977.  Will follow up after next QA build.

**Comment by digitalken** [comment]
PASS 7/30/2021 - This doesn't seem to be happening anymore.  Closing.
