### ISSUE TITLE
Update Community Care preferences flow

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2805]
## Story
As a veteran, I find the existing community care preference options confusing; I would like to have less confusing community care options so that I can fill out the appointment request clearly.

## AC
- [ ] Update mocks to match flow outlined in figma node: https://www.figma.com/file/KGChcQHMrTReo7T7cML418/VAOS-Flow?node-id=118%3A217

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67981800-c9a46980-fbf7-11e9-826a-ca6179623708.png)

![image](https://user-images.githubusercontent.com/12564977/67981808-ce691d80-fbf7-11e9-9c43-01b9f2c85a10.png)

**Comment by jbalboni** [comment]
Here's the legacy preferences fields, for reference:

![Screen Shot 2019-11-04 at 11.40.34 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/f8f95a46-9aae-48da-8952-fc70ca9969cc)
![Screen Shot 2019-11-04 at 11.40.40 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/eb2b0dde-7840-4ffb-a083-2a903338a75e)

There are a few things that seem to be missing or are unclear how to map:

1. Preferred city/state (this is not the VAMC choice, which happens earlier)
2. Office hours
3. Provider preferences
4. Distance choice (seems like we've decided to default this to a number, though)

**Comment by rtwell** [comment]
cc @lalexanderson-dsva 

1. the city / state is captured at the top of our page and is only necessary if a user is registered at more than 1 VA healthcare system AND they have selected a type of care that both systems offer AND is Community Care eligible. For all other use cases, we should default to there residential addy, behind the scenes. 
2. Office hours are unnecessary b/c users have already indicated their preferred date/time
3. Provider preferences—I assume you're referring to the ope text field? that should be captured by the "Additional details" field in the "Why are you making an appt" page
4. Usability testing revealed that Veterans always want the closest location

**Comment by jbalboni** [comment]
@rtwell That's all fine, but I want to confirm that we all understand that the preferred city and state on the legacy app is separate from both the VAMC city/state and the preferred provider city and state. We can default it to the residential address, but that field is completely independent of what health care systems you're associated with, and given that it's required, looks to me like the primary piece of information schedulers would use to figure out where to book an appointment.
