### ISSUE TITLE
Request access to Google Analytics - GCIO

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28065]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## Information
This ticket is to track the GCIO email transition.  Each GCIO team member should get access to Google Analytics with their new emails. Platform Analytics & Insights and GCIO has access to a Google Spreadsheet (not linked here due to privacy) with the transition checklist.

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

Once you receive access, you should receive a confirmation email directly from Google or Domo.

## Date Required
_Please share the date you require access._

ASAP

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

GCIO

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jennaouellet** [comment]
Users that have emails tied to google have been given GA access. As others link accounts they will be added to GA.

**Comment by chloedotbrown** [comment]
Updated emails in Domo and on the VFS roster sheet. Tracked on spreadsheet [here](https://docs.google.com/spreadsheets/d/1cY9KDi3JafJIgNAqHPh7n4GFeRqtzHCqLI8ijbDWJ5M/edit?usp=sharing).
