### ISSUE TITLE
Document steps for reassigning a CC Staging Review issue ticket to a different team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28061]
## Issue Description
In the CC Staging Review process, issue tickets are created for the VFS team being reviewed, and their github team label is added to the ticket. On occasion, after review by the VFS team and further investigation by Platform, the issue could be reassigned to a different VFS team or to a Platform team.

We also need to document how to handle invalid tickets (for example a duplicate ticket or a ticket that was created by mistake). In this case, we should close the issue ticket and also remove the VFS team label.

We need to document the necessary steps for when this occurs so that the same process is applied across the board.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
Link to review https://vfs.atlassian.net/wiki/spaces/PPST/pages/1862139961/Reassigning+invalid+or+duplicate+GitHub+issue+tickets

**Comment by shiragoodman** [comment]
@allison0034 looks good to me. Thanks!
