### ISSUE TITLE
Use CMS export in preview server

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2807]
## Problem Statement
When we make the switch to use the CMS export in the content-only build, the preview server needs to be updated to reflect this same process instead of relying on the GraphQL request.

## Acceptance Criteria
In the build script:
- [ ] The latest CMS export is fetched
- [ ] The `uuid` is used instead of `nodeId` to build the page data
- [ ] The content build process the preview server uses mirrors the normal build

**Comment by timwright12** [comment]
Closing because we migrated away from CMS Export as a project.
