### ISSUE TITLE
GI Bill School Feedback Tool form submission not working

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#28078]
## What happened?
- [Daniel Shawkey raised](https://dsva.slack.com/archives/CBU0KDSB1/p1627478540056000) an issue with GI Bill School Feedback Tool not submitting.
	- Travis found an [RSAError in Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/43467/).
	- Looking into it further, GIBillFeedbackSubmissionJob is [calling `Gibft::Service`](https://github.com/department-of-veterans-affairs/vets-api/blob/cf7f453b11e87819f51f65a38a02fe5ad7593c48/app/workers/gi_bill_feedback_submission_job.rb#L14), which is [calling `Salesforce:Service.private_key`](https://github.com/department-of-veterans-affairs/vets-api/blob/cf7f453b11e87819f51f65a38a02fe5ad7593c48/lib/salesforce/service.rb#L30). The `SIGNING_KEY_PATH` is [set in `Gibft:Service`](https://github.com/department-of-veterans-affairs/vets-api/blob/cf7f453b11e87819f51f65a38a02fe5ad7593c48/lib/gibft/service.rb#L11).
	- `SIGNING_KEY_PATH` is set to `"/srv/vets-api/secret/gibft-sfdc-signing.key"` which is [generated in vets-api-server-vagov-prod.yml](https://github.com/department-of-veterans-affairs/devops/blob/e4ea76ccd791414e1fe10a290bb7391f8736ae5f/ansible/deployment/config/vets-api-server-vagov-prod.yml#L174-L175) from parameter store. This cert was updated 8 days ago.
	- **First root cause**: when the key was updated, a cert was put into param store rather than the RSA key which causing Ruby to fail to parse the key.
	- [Demian updated](https://dsva.slack.com/archives/CJYRZK2HH/p1627494327279300?thread_ts=1627489516.269400&cid=CJYRZK2HH) the key in param store and tweaked the config in https://github.com/department-of-veterans-affairs/devops/pull/9662.
	- This solved the RSAError when trying to read/parse the file in Ruby but we're still seeing an error when following the repro steps. **Further investigation required**.

## Steps to Reproduce
1. Go to [GI Bill School Feedback Tool](https://www.va.gov/education/submit-school-feedback/introduction) and click 'Start your application without signing in'.
2. Click 'Start your application without signing in' (if you're not signed in).
3. Select 'I want to submit my feedback anonymously' and click Continue.
3. Check Post-9/11 GI Bill box and click Continue.
4. Click 'Search Schools' and select the first one then click Continue.
5. Check the first box, enter text into the two fields, then click Continue.
6. Check the privacy policy box and click 'Submit application'.

## Desired behavior
The form should submit properly but instead displays a message that says 'We’re sorry. We can’t submit your application right now.'

**Comment by WillMcCormack** [comment]
Good afternoon, any updates on this ticket? We have another check-in with stakeholders on Monday so would like to provide them a status.

**Comment by cbtkc** [comment]
@WillMcCormack It's being actively researched right now. As soon as I have a better understanding of what is causing the problem, I will let update this issue.

**Comment by cbtkc** [comment]
I think I've found the culprit - seems to be because of an invalid auth header. And the reason that is happening is because when the get_auth_token method in the Salesforce::Service class is called, it is returning nil so the submissions aren't authorized.

This lines up with the only submission errors I am seeing in Sentry, which are Restforce::Unauthorized errors.

**Comment by cbtkc** [comment]
[This line will need to be looked at.](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/salesforce/service.rb#L34)

**Comment by WillMcCormack** [comment]
Great, thank you for the update. Have a nice weekend!

**Comment by ericboehs** [comment]
I'm pretty certain this is because the remote server hasn't updated the cert that was rotated last week. The errors correlate with the time the key expired/was rotated. Shirley Edwards (GIBCT, I believe) is working with Salesforce to get this updated.

**Comment by WillMcCormack** [comment]
Thanks Eric, we will be on standby to test once Salesforce gets the cert updated on their end.

**Comment by WillMcCormack** [comment]
Good morning, any movement on this?

**Comment by WillMcCormack** [comment]
Just tested and it looks like I was able to submit:

![image](https://user-images.githubusercontent.com/25459380/128370430-7f965275-6fd6-4bd9-9be4-012236948d8f.png)
