### ISSUE TITLE
CT Redesign: Location Search result cards are the incorrect size

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#28074]
The location search result cards in the redesigned comparison tool are about half the width they should be (see below screenshot)

### Steps to Reproduce
1. Execute any location search that returns results at https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location

### Expected Behavior
Search result cards adhere to the design standards shown in the [prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/screens/296060309)
![Screen Shot 2021-07-29 at 12.21.33 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4d457283-f8c0-4c7c-b31b-65d32cad9b39)

### Actual Behavior
![Screen Shot 2021-07-29 at 12.16.56 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/28968362-5b51-4143-b824-5a27c730fefe)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18077

**Comment by sonntag-adam** [comment]
reopening. When testing
 https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27557, size of location institution is not the same width as name.
Location:
![Screen Shot 2021-08-04 at 10.05.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ca857a51-c1d8-4a6c-afd1-2b0f106d43a9)
##
Name:
![Screen Shot 2021-08-04 at 10.05.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/658a465e-8e2b-4d82-8687-56be28229141)

**Comment by sonntag-adam** [comment]
Prototype for reference https://bahdigital.invisionapp.com/share/QDIAGYESX4T#/screens/296060497

**Comment by sonntag-adam** [comment]
was implemented here https://github.com/department-of-veterans-affairs/vets-website/pull/18135

**Comment by delli-gatti-michael** [comment]
This issue is still occurring when using the "Search this area of the map" button

Can be reproduced by:
1. Navigate to the "Search by location" tab
2. Position the map so that the center is approximately halfway between Charlotte, NC and Columbia, SC (see attached clip for reference)
3. Click the "Search this area of the map" button
4. Scroll through the results

Example institutions include:
1. W L BONNER COLLEGE
2. CONVERSE COLLEGE
3. WOFFORD COLLEGE


https://user-images.githubusercontent.com/45575003/129589183-2034a6fc-33f6-42e8-9186-9f8874ceb1d2.mov

![Screen Shot 2021-08-16 at 11 30 50 AM](https://user-images.githubusercontent.com/45575003/129589297-21f48fc6-f435-4253-afcf-cee90e7f7192.png)

---

![Screen Shot 2021-08-16 at 11 31 02 AM](https://user-images.githubusercontent.com/45575003/129589307-0b58d4af-1c3b-4da6-983b-81cfff1d46e8.png)

---

![Screen Shot 2021-08-16 at 11 31 13 AM](https://user-images.githubusercontent.com/45575003/129589324-38ab933d-47da-4b06-a6af-864bf5f5bb7e.png)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18267

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
