### ISSUE TITLE
CT Redesign: Update display of School/OJT profile page on mobile.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28080]
As a developer, I need to update the display of the School/OJT profile page so that it displays well on mobile devices and provides the user with a good user experience.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The breakpoint for mobile display is 481px ($small-screen).
3. "Types of degrees offered" in the "Academics" section of the prototype is out of scope of this story.

## Acceptance Criteria:
1. The content of the profile page is displayed in the following order:
    a. Header card
    b. On this page navigation control
    c. Institution applicable sections in the same order as desktop

2. All data in the profile header card is displayed vertically in the following order for schools:
    a. Name
    b. City, State
    c. Star rating visual | X.X of 5 
    d. (See XXX ratings by veterans) link
    e. XXX GI Bill students (Learn more)
    f. Caution flag control (if applicable)
    g. Program Type
    h. Institution Type
    i. Accreditation (Learn more)
    j. Institution size
    k. Institution locale
    l. Institution URL
    m. compare

3. All data in the profile header card is displayed vertically in the following order for OJT/Apprenticeships:
    a. Name
    b. City, State
    c. Caution flag control (if applicable)
    d. Institution Type
    e. compare

3. The "Calculate your benefits" section displays the content in the following order:
    a. The content "The 4 sections below include questions that will refine your benefits estimate. Use the fields in each section to make your updates."
    b. "Your military details" accordion
    c. "School costs and calendar" accordion
    d. "Learning format and location" accordion
    e. "Scholarships and other VA funding" accordion
    f. Estimate your benefits grey box
    g. "Additional information regarding your benefits" sub-section content

4. The "Veteran ratings" section displays the content in the following order:
    a. # of veteran ratings
    b. Overall calculated rating
    c. "Education Ratings" group
    d. "Veteran Friendliness" ratings group
    e. "About ratings" sub-section content

5. The "Cautionary Information" section displays the content in the following order:
    a. Student Feedback
    b. X student complaints in the last 24 months (learn more)
    c. The "Complaints by type (Each complaint can have multiple types)" table data

6. The "Complaints by type (Each complaint can have multiple types)" table data is displayed in the following rows
    a. "This campus" header
    b. "This campus" complaint type and count
    c. "All campuses" header
    d. "All campuses" complaint type and count
    e. The "All campuses" header is static text with a "Learn more" that opens the "VA Complaints (all campuses):" modal.

7. The "Academics" section displays the content in the following order:
    a. Education details
    b. Get started with CareerScope

8. The "Veteran programs and support" section displays the content in the following order:
    a. Veteran programs
    b. Historical information

9. The "Contact information" section displays the content in the following order:
    a. Physical Address
    b. Mailing Address
    c. Single point of contact for veterans
    d. School certifying officials
    e. Institution codes

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222781/296063965/preview)
2. Profile showing current complaint table behavior: https://www.va.gov/gi-bill-comparison-tool/profile/21376032
3. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/afe9ac6562950cfb18e702765469f84d4c1e4ff1/products/education-careers/school-comparison-tool/redesign/design/content-IHL.md#student-complaints)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18126

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2112&group_by=cases:section_id&group_order=asc
