### ISSUE TITLE
Lat/long for non-VAST locations (CAPs, mobile, etc)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28088]
## Issue Description
As a Veteran, I want to see satellite locations where VA services are offered so that I can visit the location closest/most convenient to me.

### Background
Drupal is the source of truth for non-VAST locations such as Mobile health clinics and Vet Center Community Access Points (CAPs). 
- Mobile health clinics exist in VAST only as the parking location for the unit - not as service delivery locations throughout  the community. 
- Vet Center CAPs are not available in VAST as they exist in rental/shared space within community locations (church, YMCA, health department, mall) rather than in VA owned/operated physical facilities. There are 300 Vet Centers nationwide and as such, some Veterans may live at a distance to the closest Vet Center or outstation. However, there could be a CAP nearby. 

### Problems to solve

- Identify a method for determining lat/long (based on newly added/edited locations)
- Method for storing the data 
- Make non-VAST locations available to Lighthouse (so they can be searched in Facility Locator)

**Comment by kevwalsh** [comment]
Closing this in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8683
