### ISSUE TITLE
Assess Vet Center pages for alignment with new standards

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28096]
## Issue Description
The Platform Product Support team will use new VA.gov Experience Standards to assess VFS products for design, IA, content, and accessibility as teams bring their work through the Collaboration Cycle. These standards incorporate WCAG 2.1 guidance, which will also now be applied in Collaboration Cycle reviews.  

We need to review our products to check for alignment with these standards

---
## Tasks
Review the Vet Center pages, checking for alignment with 

- [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

**Supporting references**
- [New success criteria in WCAG 2.1](https://depo-platform-documentation.scrollhelp.site/test-release/1777893393/VSP%20WCAG2.1_%20New%20Success%20Criteria.pptx?inst-v=6d1b52e3-861c-4053-bd78-89093868c388)
- [Foundational testing for WCAG 2.1](https://depo-platform-documentation.scrollhelp.site/test-release/1777893393/VSP%20WCAG2.1_%20Foundational%20Testing%20Redux.pptx?inst-v=6d1b52e3-861c-4053-bd78-89093868c388)

## Acceptance Criteria
- [ ] Issues have been created to address any identified gaps.

**Comment by laflannery** [comment]
@mmiddaugh What would your thoughts be on my adding this to my list to actually do? I actually don't anticipate major issues coming out of this besides what we already know but I think it might be good to have a complete audit done and make sure all issues are documented? CC: @xiongjaneg

**Comment by laflannery** [comment]
Closing this in favor of [a new ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17371)
