### ISSUE TITLE
[KEYBOARD] VA.gov Direct Deposit - Tab order is not correct

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#2809]
## Description

[KEYBOARD] VA.gov Direct Deposit - Tab order is not correct

**Focus Order** –  When Selecting the the "Direct deposit information" link to jump to the direct deposit section, the next tab stop is the “Contact information” link above the “direct deposit information” link.  ***(I can still get to the information by continuing to tab however this would confuse a user). When I have JAWs on it flows properly with the arrow keys.***

## Point of Contact

Jennifer

## Acceptance Criteria

As a keyboard user, I want to open the direct deposit interface and be able to tab through the information in a logical order.

## Steps to Recreate

1. Log into staging.va.gov with user 150
2. Click on the person menu in the top right corner
3. Click "Profile" from that menu. Your profile view will load.
4. Click the "Direct deposit information" link to jump to the direct deposit section
5. Click any of the three buttons styled as links underneath Bank name, Account number, or Account type to open the DD modal.
6. Tab through the form

**Comment by Justin-Pickett** [comment]
@jenstrickland okay great!  Thanks for the update!
