### ISSUE TITLE
CT Redesign: Update display of VET TEC profile page on mobile.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28091]
As a developer, I need to update the display of the VET TEC profile page so that it displays well on mobile devices and provides the user with a good user experience.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The breakpoint for mobile display is 481px ($small-screen).

## Acceptance Criteria:
1. The content of the profile page is displayed in the following order:
    a. Header card
    b. On this page navigation control
    c. Institution applicable sections in the same order as desktop

2. All data in the profile header card is displayed vertically in the following order for VET TEC providers:
    a. Name
    b. City, State
    c. Caution flag control (if applicable)
    d. Compare

3. The "Calculate your benefits" section displays the content in the following order:
    a. Calculator label and field content
    b. Estimate your benefits grey box

4. The "Approved programs" section is displayed with the same stylings as the current comparison tool.

5. The "Cautionary Information" section displays the content in the following order:
    a. Student Feedback
    b. X student complaints in the last 24 months (learn more)
    c. The "Complaints by type (Each complaint can have multiple types)" table data

6. The "Complaints by type (Each complaint can have multiple types)" table data is displayed in the following rows
    a. "This campus" header
    b. "This campus" complaint type and count
    c. "All campuses" header
    d. "All campuses" complaint type and count

7. The "Contact information" section displays the content in the following order:
    a. Physical Address
    b. Mailing Address
    c. School certifying officials
    d. Institution codes

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222781/296064088/preview)
2. Profile showing current complaint table behavior: https://www.va.gov/gi-bill-comparison-tool/profile/21376032

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/18266

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2114&group_by=cases:section_id&group_order=asc
