### ISSUE TITLE
Ignore CSP violations we won't do anything about

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#281]
## User Story
As a VSP or VFS engineer, I need to see only the errors that are meaningful to me so I can focus on them.

(Okay, bad user story, I know. Sorry. :grimacing: )

We _can_ filter for `logger:javascript`, but we shouldn't expect engineers to always do this. Currently, a search for `is:unresolved logger:csp` gives 997 separate issues with millions of events.

## Goal
The number of CSP violations logged to Sentry because of browser extensions and the like is reduced
- Ideally to zero, but I'm not sure if that's realistic
We still see CSP violations that we _can_ do something about
- Like for Google tag manager and the like—things that we do actually want to go through

## Acceptance Criteria
- [ ] CSP violations from browser extensions are not displayed in Sentry
  - Either we filter them out once they reach Sentry or on the client side; I don't know what's possible here yet

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
Where does the CSP logger even come from, and why is it separate from the JavaScript logger?

**Comment by cvalarida** [comment]
I found a toggle at http://sentry.vetsgov-internal/settings/vets-gov/projects/website-production/filters/data-filters/ which filters out errors known to be caused by browser extensions.

I'll close this one out for now. If after a while we still see these kinds of errors crop up, we can deal with them individually in another ticket.

**Comment by annaswims** [comment]
This has been bugging me for a while so I figured I'd just take 30 min to fix it. I added good urls for services that we actually use to the whitelist https://github.com/department-of-veterans-affairs/devops/pull/5021

We can also add "known bad" urls here to be filtered. http://sentry.vetsgov-internal/settings/vets-gov/projects/website-production/security-headers/csp/
