### ISSUE TITLE
CT Redesign: Add covid banner to sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28106]
As a developer, I need to add the COVID banner displayed on the landing page of the current comparison tool to the search page of the sandbox so that current functionality is not lost.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The comparison tool sandbox displays the covid banner in SA1 on the search page.

## Supporting Artifacts:
1. Current covid banner:
<img width="1013" alt="Screen Shot 2021-07-30 at 8 11 15 AM" src="https://user-images.githubusercontent.com/48260534/127651134-cf429429-fc14-480f-b8e2-06d101b23dca.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18155

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2093)
