### ISSUE TITLE
Accessibility Feedback for Midpoint Review [Search & Discovery, Surfacing Search Tools]

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#28107]
# Accessibility Feedback for Midpoint Review [Search & Discovery, Surfacing Search Tools]

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Angela and Josh

## Must
- Use lin 

## Should
- Style links as links, not as buttons. An action link version of the first "button" style could be a compromise between the two.
- Logically order headings. Either make all the additional search headings `h2`s or add a buffer `h2` called "Additional search tools" _and then_ make the additional search tool headings `h3`s

### Analyze assumptions

> Findings from user research are representative of Veterans across the Veteran journey.

[Plot the previous research sessions onto the new VA recruitment checker](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit?usp=sharing) or reference recruitment documentation (below) to better examine this assumption for the [risks section of the initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/surfacing%20other%20search%20tools/initiative-%20brief.md).

<img width="582" alt="Screen Shot 2021-07-30 at 9 06 41 AM" src="https://user-images.githubusercontent.com/14154792/127657197-cff23909-bea2-4f1a-95d6-cf4f9028f63f.png">

<img width="395" alt="Screen Shot 2021-07-30 at 9 09 01 AM" src="https://user-images.githubusercontent.com/14154792/127657478-134c0531-dc8f-4be3-b806-395c71f91451.png">

For example, if only one low vision, desktop screen reader user was included in this research, research will unlikely cover the needs of other types of assistive technology such as:
- Mobile Screen Reader (SR)
- Magnification/Zoom
- Voice AT like Siri/Dragon Naturally Speaking
- Hearing Aids
- Sighted keyboard
- Captions
- Switch Device
- Braille Reader

Doing so may guide future research to prioritize testing with AT or request analysis from an accessibility specialist.

### Think of AT specific KPIs

Quantitative:
- Improved sentiment score -- as measure by Medallia -- for search products/tools

Note: The thoughts of AT users will likely be absent in feedback due to the inaccessibility of Medallia's feedback button (currently in the process of being redesigned). What other means of collecting feedback from AT users can be used to rate this?

Qualitative:
- User testing **(on mobile, desktop, and with assistive technologies)** shows the other search tools are more findable

## Consider

Not hiding the search within a collapsible menu in favor of an immediately visible and operable search box on the landing page.
- Screen reader users often rely on landmarks to quickly find important sections of a page. [Providing a "search" landmark is very helpful](https://www.w3.org/TR/wai-aria-practices-1.1/examples/landmarks/search.html), especially on a landing page, to help screen reader users quickly discover and use an accessibility-friendly tool. However, that landmark will _not_ emerge to screen reader users if it is hidden beneath an expandable menu. 
- For everyone else, and particularly folks with cognitive disabilities, surfacing search immediately without having it buried beneath a menu can be incredibly valuable.

<img width="1319" alt="Screen Shot 2021-07-30 at 9 19 01 AM" src="https://user-images.githubusercontent.com/14154792/127658716-692e3831-e2fd-4724-b0be-f3614ae19fe0.png">

For example, gov.uk's search is a part of the landmarks on the page.

<img width="1319" alt="Screen Shot 2021-07-30 at 9 19 33 AM" src="https://user-images.githubusercontent.com/14154792/127658786-2d5c7dde-a426-446d-8424-2b8e9ab51d9c.png">

This is a contrast to VA.gov. Even if we were to add a role="search" to the `form` element hidden beneath the collapsed menu, it would not present itself to screen reader users until that collapsed search menu expands. Placing the role="search" onto the `button` that expands the search menu would not be an alternative as it would override the `button`'s semantics.

**Comment by laflannery** [comment]
I think this might be resolved? I know there was a separate issue that handled the heading structure of search results.  I also know that the global search will be surfaced with the new redesigned homepage.  Will close in 1 week unless told otherwise

**Comment by joshkimux** [comment]
@laflannery agree! These should all be covered in the new homepage design
