### ISSUE TITLE
[FE] Notification Prefs: Adjust existing RadioButton component

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#28114]
Assuming we move forward with using radio buttons for the new Notification Settings designs, we'll need to expand the [RadioButton component that lives in the React component library](https://design.va.gov/storybook/?path=/docs/components-radiobuttons) so that it supports additional states beyond normal and ["error" states](https://design.va.gov/storybook/?path=/docs/components-radiobuttons--error).

As of Friday, July 30, 2021, [the designs call for two additional status levels](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140669494/simulate/sitemap), similar to the existing "error" status, but with different colors. We'll need a new "warning" state and "success" state. I'm using those terms because they match what is used by the [AlertBox](https://design.va.gov/storybook/?path=/docs/components-alertbox-deprecated--success)

[As Liz mentioned below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28114#issuecomment-890004042), we will also need to reset the radio buttons in the following scenario:
1. User has never opted in or out, so no radio button is selected and the radio buttons have the yellow "Warning" appearance
2. User clicks a radio button, trigging an API call to save their selection
3. The API fails, so we need to reset the radio buttons to the "no selection" state and give the radio buttons the red "Error" appearance

<img width="321" alt="Screen Shot 2021-07-30 at 8 30 19 AM" src="https://user-images.githubusercontent.com/20728956/127676190-6e24146c-5f0c-4f7e-b184-bd9f58dbd302.png">

**Comment by erikphansen** [comment]
@ajakabcin @andaleliz tagging you for awareness. Assuming Liz continues with the radio button designs, this dev work will need to be done. This is something that could potentially be handled by @tmitchellgcio while I am out next week, depending on what's on his plate.

**Comment by andaleliz** [comment]
Does the current error status reset the radio buttons to null? I think we should follow this pattern for the error state as well, but our current "please try again" guidance in the error message means we would need to reset it null so the person can actually try again (without clicking the option they _don't_ want and then going back to the other option.

**Comment by erikphansen** [comment]
We'd have to programmatically reset/unselect the radio buttons in the case of an error. But we should make sure that can be easily done with the existing component. I'll add that to the original ticket.

**Comment by erikphansen** [comment]
validation not needed for this.
