### ISSUE TITLE
Explore/research Calendly as an option for scheduling Collab Cycle Reviews.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28115]
## Issue Description
Scheduling Collaboration Cycle reviews is time consuming and involves many steps. On occasion, necessary team members may be excluded from the invitation. Platform Product Support would like to explore using Calendly as a tool to assist in scheduling Collab Cycle Reviews. 

---
## Questions to answer:
- [x] How does Calendly work?
We would use Calendly to set up links so VFS and other people can schedule their own meeting time for collab cycle meetings.
- [x] How much does Calendly cost?
$8/month for the [Premium membership](https://calendly.com/pricing)
- [x] Would implementing use of Calendly be less time consuming that the current Collab Cycle scheduling process?
Yes!
- [x] How many people can use Calendly?
Unlimited
- [x] what happens if a meeting need to be rescheduled?
We would need to reschedule via Google calendar and then make sure to comment in the GH ticket and tag any attendees.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
[Link to mural](https://app.mural.co/t/oddball9501/m/oddball9501/1628778288960/d63d8684b531f9b8a0dc60a64e05604e20395d66?sender=u045df875f30f7e9f34339908)

**Comment by shiragoodman** [comment]
Notes from 8/16 meeting with Allison: 

- Still need to determine cost.
- Write up pros/cons of migrating to Calendly
- Write up dependencies (ie group emails) and document new process
- potentially research other Calendar tools

**Comment by allison0034** [comment]
Cost
$8/month for the Premium membership

Pros
Less time to schedule meetings
VFS teams can choose their own time instead of going back and forth
Others (OCTO) can add the meeting to their calendar without having to reach out to us

Cons
We will have to reschedule meetings thru Google calendar, not Calendly
Individuals may not click the link to add the meeting to their calendar

Dependencies
Create group emails
Document new process

I looked at Google appointments but it only works with Google calendar
