### ISSUE TITLE
General Analytics Request for Search & Discovery

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28123]
# General Analytics Request

## What this form is for

Use this template to request support for analytics that need interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Search & Discovery

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data, link to this Github issue, and tag `@platform-analytics`._
    
- What team/project is this work for?

 - We are exploring adding the videos to the search results page and wondering how many users are clicking on the You tube channel link in the footer. Can you point us to this information in GA? 
    
- What type of analytics support are you looking for?
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

We are in the exploration phase and would love to have this data by August 6th if possible.  

## Analytics to Track Down

> - [ ] Click data on youtube channel in the footer for 2020 and 2021
![Screen Shot 2021-07-30 at 1.43.07 PM.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/ec11c1f6-3d8e-4b29-aa34-97b2f6dc5e70)

## Other Helpful Questions to think through
- Who is your audience? All VA.gov users
- Why do you need this data? Want to get a sense of how many people are looking for videos on VA.gov
- What are you hoping to find? A sense of who is looking for videos and has found the youtube link in the footer
- What is your hypothesis that you're hoping the data will support? Since this link is in the header we assume it isn't used very frequently.
- What area of the VA are you hoping to assess? Video usage
- How frequently do you need this data? Just once

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jennaouellet** [comment]
Hi @denisecoveyduc! The YouTube clicks can be found using the Events report in GA. I've narrowed down to the event actions that contain "youtube". The specific link in the footer is https://www.youtube.com/user/DeptVetAffairs which is found in this report.

**Comment by denisecoveyduc** [comment]
Thanks @jennaouellet This is exactly what I was looking for. Appreciate it!
