### ISSUE TITLE
CT Redesign: Add arrow navigation controls to mobile compare page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28124]
As a developer, I need to update add arrow controls to the compare page on mobile so that users who have difficulty scrolling the page have buttons that can be used to move the information to the left and right.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The breakpoint for mobile display is 481px ($small-screen).

## Acceptance Criteria:
1. Below the institution cards and highlight differences is a control that:
    a. has a dot visual indicator for the number of cards being displayed
    b. allows the user to tap an arrow indicator to scroll the cards to the left or right

2. When the user scrolls using the arrow indicators:
    a. the card and data content moves in unison.
    b. the card and corresponding institution data is snapped to a left aligned position with the card and data fully in view.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/3GIAHDEDJKM#/screens)

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2109)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
