### ISSUE TITLE
[FE] Feedback from UX when reviewing staging

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#28140]
# Description
What I found when reviewing staging.

1. A period is missing at the end of the check-in text message URL. (@Kennon-git, since this is VeText and not VA.gov)
![IMG_6164.PNG](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/3381e7e6-b391-4a90-a208-ac62e528b357)
2. The "Back to last screen" buttons weren't functioning for me on either page that they are located on.
3. Can the clinic name be Title Case, instead of UPPERCASE on both the confirmation page and the "Your appointments" page?
![IMG_6166.PNG](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/2ae4181d-2845-4171-b70b-a7a7eecab2c0)
4. Question: where did we land on displaying timezones? I'm thinking about the "Your appointment" page.

Besides the back button functionality, I wouldn't rank any of the other items as high or even medium priority.

cc @jparker0425

**Comment by jparker0425** [comment]
@kristenmcconnell agreed, the back button functionality was brought up by a test user for the Staging Review testing as well and that needs to be the top priority right now. I am not concerned at this time about getting timezone as part of the MVP unless it is very minimal to implement. That can be addressed in Phase 2 with multiple appointments. 

My thoughts:

MVP:
* Add the period to end up initial text - @Kennon-git 
* Title Case @mdewey 
* Fix back button 

Phase 2: 
* Timezones

Thoughts??

**Comment by mdewey** [comment]
Sounds like a plan to me @jparker0425. I have created a ticket to track my two items and marked it as unplanned work.

**Comment by mdewey** [comment]
Created PR : https://github.com/department-of-veterans-affairs/vets-website/pull/18092

**Comment by mdewey** [comment]
@kristenmcconnell  and @jparker0425  The back button fix is in staging. I will let QA know as well
