### ISSUE TITLE
Draft August newsletter edition

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#28146]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [x] Solicit content for the August issue.
- [ ] Conduct pair-writing sessions.

# Acceptance criteria

- To come.

# Reference info

- [July/Aug newsletter draft](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1657667585/July+August+2021+draft?focusedCommentId=1823998024&atlOrigin=eyJpIjoiYTUwY2M1MjcwMzllNDY4NzlkZDNkYTg3NGRlYTE1NzEiLCJwIjoiYyJ9)

**Comment by gmaciolek** [comment]
August newsletter editorial plan:
https://vfs.atlassian.net/l/c/fCqdEzUB

**Comment by gmaciolek** [comment]
Amy pulled together draft and scheduled pair writing sessions.
Gretchen to pick up the plan where Amy leaves off next week.

**Comment by lianilychee** [comment]
Fri 8/13:
- Gretchen prepared for the three consecutive sessions
- she found some of the q's in the script were repetitive and have new, deeper questions

**Comment by lianilychee** [comment]
8/17 Tues:
- Amy to read through Gretchen's work, and see if:
  - we have actually addressed the "why is the update helpful to you"
  - conduct final review and polish for sending out to customers on Mnoday
