### ISSUE TITLE
CT Redesign: Beta Testing Research Workshop, Part II

### ISSUE THREAD

**Issue by ShelbyStarr** [department-of-veterans-affairs/va.gov-team#28162]
As a developer, I need to identify and prioritize learning objectives during testing, so that I can determine the appropriate way to learn each identified and prioritized objective. 

Assumptions:

N/A

Acceptance Criteria:

1. Discuss testing objectives with UX & xfunc teams; identify research questions, prioritize desired outcomes and tactics for soliciting that information; prioritize segments
2. Review with Xfunc team for awareness & alignment

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1626186692995/bb151c3b31f30af9704e40005b6253768f482029?sender=jonesjennifer26349
