### ISSUE TITLE
CT Redesign: Beta Testing Research Plan

### ISSUE THREAD

**Issue by ShelbyStarr** [department-of-veterans-affairs/va.gov-team#28163]
As a developer, I need to draft a research plan for beta testing, so that the research plan can be reviewed with the UX team and updated based on provided input. 

Assumptions:

N/A

Acceptance Criteria:

1. Draft research plan
2. Review w UX Team
3. Update based on feedback

**Comment by JenLJ** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/beta-testing/research-plan.md
