### ISSUE TITLE
Security review informal suggestions

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#28171]
- [ ] Remove ports 22 & 80 from security groups
  - [ ] Nonprod
  - [ ] Preprod
  - [ ] Prod
- [ ] Research and lock down the IP range to something smaller (10.0.0.0/16? or better?)
  - [ ] 10.0.0.0/8 is pretty wide open. Even 10.0.0.0/16 is better
  - [ ] Look into VPC -> VPC comms for vets-api traffic, perhaps
- [ ] Make sure there's not PHI & PII in logs
- [ ] Look into Sentry & Loki, perhaps even Splunk (SaaS, not on-prem)

**Comment by aschulhof** [comment]
Outdated
