### ISSUE TITLE
Cancelled Appts Not Displaying Correctly.

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#28186]
From: Durkin, Robert M. <Robert.Durkin@va.gov> 
Sent: Monday, August 2, 2021 5:39 AM
To: Bleyer, Edward M. <Edward.Bleyer@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Ed, this has not been fixed yet.  We apologize for the delay.  This will be fixed by next week.

Rob

From: Bleyer, Edward M. <Edward.Bleyer@va.gov> 
Sent: Monday, August 2, 2021 8:28 AM
To: Durkin, Robert M. <Robert.Durkin@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Good morning!

Has anyone had a chance to take a look at the issue we came across (see below).

R/Ed

From: Bleyer, Edward M. <Edward.Bleyer@va.gov> 
Sent: Friday, July 16, 2021 2:01 PM
To: VEText <VEText@va.gov>
Subject: Cancellation Testing

Good afternoon VEText Team!

Our staff were testing the cancellation process and ran across the following. Just wanted to see if it is a known issue or just a delay in updating.

Thanks!

Ed

… the appointment still showed “scheduled” on the actual VEText website. I tried refreshing it and it was still there. Although, I’m not sure that’s a critical problem. But, it showed the new appointment in there too.

Screenshot of the cancelled appointment that still shows scheduled (it actually changed from “outside” status to “scheduled” when it cancelled)
 
Screenshot of the new appointment for the same patient:
 
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/6f0e9ebf-1a3b-4461-89a0-644e176666e3)

 
 

From: Bleyer, Edward M. 
Sent: Tuesday, July 27, 2021 3:50 PM
To: Durkin, Robert M. <Robert.Durkin@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Hi Rob!

Have you had a chance to troubleshoot the issue below?

Ed

From: Bleyer, Edward M. 
Sent: Friday, July 16, 2021 4:05 PM
To: Durkin, Robert M. <Robert.Durkin@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Thanks Rob!

From: Durkin, Robert M. <Robert.Durkin@va.gov> 
Sent: Friday, July 16, 2021 3:42 PM
To: Bleyer, Edward M. <Edward.Bleyer@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Thanks, Ed.  I will look into this and get back to you.

From: Bleyer, Edward M. <Edward.Bleyer@va.gov> 
Sent: Friday, July 16, 2021 2:07 PM
To: Durkin, Robert M. <Robert.Durkin@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Correct, the lead did verify.

From: Durkin, Robert M. <Robert.Durkin@va.gov> 
Sent: Friday, July 16, 2021 2:03 PM
To: Bleyer, Edward M. <Edward.Bleyer@va.gov>; VEText <VEText@va.gov>
Subject: RE: Cancellation Testing

Ed,

Thanks for the feedback.

In these cases, you verified that the appointments were indeed cancelled in VistA?

Rob

From: Bleyer, Edward M. <Edward.Bleyer@va.gov> 
Sent: Friday, July 16, 2021 2:01 PM
To: VEText <VEText@va.gov>
Subject: Cancellation Testing

Good afternoon VEText Team!

Our staff were testing the cancellation process and ran across the following. Just wanted to see if it is a known issue or just a delay in updating.

Thanks!

Ed

… the appointment still showed “scheduled” on the actual VEText website. I tried refreshing it and it was still there. Although, I’m not sure that’s a critical problem. But, it showed the new appointment in there too.

Screenshot of the cancelled appointment that still shows scheduled (it actually changed from “outside” status to “scheduled” when it cancelled)
 
Screenshot of the new appointment for the same patient:

**Comment by Kennon-git** [comment]
waiting for retest by original requester.
