### ISSUE TITLE
Review language/guidance in Collab Cycle touchpoint docs and templates

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28196]
## Issue Description
The language in the Collab cycle touchpoint documentation and template is lengthy and wordy. We believe that because of this, the VFS teams are not reading and are just skimming over the content. This can lead to artifacts missing from reviews, and /or VFS teams not being aware of artifacts and/or expectations of the review. While we cannot fix the behavior of VFS teams skimming over the content, we'd like to rewrite the content so that it is more direct and easily understood. 

Documents to be updated:

- [Staging Review gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) 
   - Please see link in the comments below. Josh Kim and Angela Fowler put together a sample Staging Review template that can be used as reference or baseline for the redesign. Be sure to view code too as many instructions are written as comments that do not show up in published mode.
- Artifacts section ONLY of [Staging Review touchpoint page ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform Website
   - this section should mirror what is in the Staging Review gh template
- [Midpoint Review gh template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D)
- Artifacts section ONLY of [Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform Website
- [Design Intent gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D)
- Artifacts section ONLY of [Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform Website
- [Full Accessibility & 508 Office gh template
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman%2C+noahgelman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)
   - this should be very similar to the Staging template. Review differences before making edits.
- Artifacts section ONLY of[ Full accessibility & 508 Office audit](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html) touchpoint page on Platform Website

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
split out Gretchen's work into it's own separate ticket. 

the other work is mostly with regards to the "what artifacts do I provide?" question. Rachael does not want us to have 20 bullets under this heading.

**Comment by shiragoodman** [comment]
@joshkimux and @AngelaFowler82 created some example templates of what a revised Staging Review github template could look like. They are linked here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28392.

**Comment by peggygannon** [comment]
Hii, @shiragoodman and @allison0034 I'm sharing a WIP updated staging review template. This template includes some of the recommendations from Josh and Angela, and some new recommendations from me. 

Let me know your thoughts. Or we can review together in an upcoming meeting. Thx!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/WIP%20staging%20review%20template.md

**Comment by joshkimux** [comment]
@peggygannon I made a pull request to propose some minor accessibility changes around headings and links 😄

**Comment by shiragoodman** [comment]
@joshkimux could you link your PR to this ticket? Thanks!

**Comment by joshkimux** [comment]
@shiragoodman [Here's my PR to this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/29902)

**Comment by allison0034** [comment]
@peggygannon dont Josh and Angela only attend if its a VSA team?

**Comment by peggygannon** [comment]
@shiragoodman PR for the template updates, for your review

https://github.com/department-of-veterans-affairs/va.gov-team/pull/29946

**Comment by peggygannon** [comment]
Hi, @shiragoodman @allison0034 here are links to the CC touchpoint docs with updated artifact lists (to match the updates we made to the templates)

1. Full accessibility audit: https://vfs.atlassian.net/wiki/spaces/PPST/pages/1872199873/Changes+to+full+accessibility+and+508+office+audit

2. Staging doc: https://vfs.atlassian.net/wiki/spaces/PPST/pages/1872461916/Change+to+staging+review

3. Midpoint review doc: https://vfs.atlassian.net/wiki/spaces/PPST/pages/1872822368/Change+to+midpoint+review

4. Design Intent doc: https://vfs.atlassian.net/wiki/spaces/PPST/pages/1871380627/Changes+to+Design+Intent

**Comment by shiragoodman** [comment]
@peggygannon i provided some comments on the staging and 508 links. Otherwise it looks good! Feel free to push to prod when my comments are addressed.

**Comment by shiragoodman** [comment]
@peggygannon looks like all comments are resolved except on the 508 Audit page. Can you push to Platform Website? And please archive all of the pages in Documentation Drafts.

**Comment by peggygannon** [comment]
Updated touchpoint documents are now live on Platform Website.

**Comment by peggygannon** [comment]
Updated touchpoint documents are now live on Platform Website.
