### ISSUE TITLE
GIBCT Caution Flags: Missing spaces in the section 702 Description

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#28191]
Institutions that are not approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits receive a caution flag in the Comparison Tool. On the institution profile page, a user can see a more detailed description of the warning. Currently, there are spaces missing from the description. 

### Steps to Reproduce
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11900238
2. Scroll to the Cautionary information section

### Expected Result
The Description for the Section 702 caution flag reads as follows:

```
This school isn't approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits because it doesn't comply with Section 702. This law requires public universities to offer recent Veterans and other covered individuals in-state tuition, regardless of their state residency.
```

### Actual Result
Several spaces are missing
![Screen Shot 2021-08-02 at 12.38.05 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6dcc20cd-ab8d-4f47-b441-9b6473e15047)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/850

**Comment by sonntag-adam** [comment]
fixed. Testing passes QA.
