### ISSUE TITLE
Access for Melinda Bernardo Cuerda, Will Kim 

### ISSUE THREAD

**Issue by mlvidart** [department-of-veterans-affairs/va.gov-team#28192]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee 
- Please provide your name.
   > Melinda Bernardo Cuerda 
   > Will Kim
   > Maria Vidart-Delgado (requesting access on behalf of team)  
- Please Provide your email.
   > melinda.cuerda@adhocteam.us
   > william.kim@adhocteam.us
   > maria@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > We are all members of the UX team at VA Lighthouse APIs, and we're a combination of researchers and designers. We all work for Ad Hoc LLC.

- Requesting SSH key authorization?
   > NO. 
   > We don’t need socks proxy, just a limited AWS account with S3 and Transcribe access in iAM. Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1603395713414900
 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > We need to access the transcription service to transcribe interviews that we conduct with non-Veteran users, and also to S3 buckets dvpuxresearchinput and dvpuxresearchoutput

**Comment by mleclerc00** [comment]
Maria Vidart-Delgado already has a AWS account

AWS Access
User: Will Kim, Melinda Bernardo Cuerda
COR: Cecilia Lee
Approval Needed: @drorva, @mchelen, @thepipster

**Comment by drorva** [comment]
Request sent to CORS

**Comment by drorva** [comment]
Approved

**Comment by mleclerc00** [comment]
@mlvidart 

Just to confirm, do the permissions you have assigned to you in AWS currently provide you access to everything you need or do we need to make changes there as well?  The thread you linked to was from quite a while ago so I am assuming that this ticket is more directed at providing your teammates access as well.

**Comment by mlvidart** [comment]
@mleclerc00 

Correct, the permissions I have are right and I need the same permissions for the members of my team. These permissions are: 

- S3 buckets: dvpuxresearchinput and dvpuxresearchoutput
- Transcription service. 

Thanks!

**Comment by mleclerc00** [comment]
I created accounts for both Melinda and Will and passed along the information needed to login via private messages.  If there are any questions or problems feel free to drop a message in #vfs-platform-support.
