### ISSUE TITLE
Establish guidelines for Sentry issue severity

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#282]
## User Story
As a Triage team member, I need know what issues in Sentry are less severe so I can properly prioritize fixing the things that are more broken.

## Goal
We know when to use the different severity levels for Sentry issues.

## Acceptance Criteria
- [ ] Documentation is written describing the various severity levels and when to use them
  - Document is store with our other sentry standards [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Platform/Teams/Triage)

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by minafarzad** [comment]
perhaps a rubric!

**Comment by cvalarida** [comment]
The other day, I posted this in slack, but it makes sense to have in here too:

I think the most important factor for the front end with regards to the error level is the user impact. The worse the impact, the higher the level.

- **Fatal:** The application is completely unusable and the front end is unable to recover by displaying messaging to the user
  - Will we ever _not_ be able to display a message but _still_ be able to manually log a `fatal` issue?
- **Error:** An error occurred rendering the application unusable and we were able to display a message to the user, but there is no path forward; it'll always be broken until we fix it
- **Warning:** An error occurred that has a minor impact on the user; there's a path forward for the user
  - I think this includes known issues like unexpected vendor downtime where we handle it by rendering a message to the user; the path forward in that case is to wait until it's resolved
- **Info:** An unexpected event occurred that the front end is handling gracefully with no user impact
  - If in doubt, it's not needed
- **Debug:** An expected event occurred, but we need insight into what happens in production; no user impact
  - If in doubt, it's not needed

Uncaught exceptions should be logged as `error`, but when we manually log an event to Sentry, the default should be `warning`; if everything is high priority, nothing is.

I'm not 100% on those level descriptions, but I think they should be a factor of:
- How usable the app is
- What the Veteran can do about it
- What we can do about it

**Comment by alexpappasoddball** [comment]
7/1/19 - Need feedback from the comments and go into github.
