### ISSUE TITLE
Update Eligibility Requirements Form 526

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28214]
## Issue Description
Claims webpage does not have current eligibility information. 
---
## Tasks
- [ ] Update [this page](https://www.va.gov/disability/eligibility/ ) to reflect current eligibility requirements as outlined on the [Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/21-526ez.md). 
- [ ] Ensure we make it clear that it is now an option to apply for the first time on va.gov

## Acceptance Criteria
- [ ] Updated webpage
---

**Comment by annaswims** [comment]
Complete.  The page no longer says that the veteran must have a rated disability to apply.
