### ISSUE TITLE
Analytics Feature Request for New Mobile Header

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#28225]
## Ticket Description

Who is this request for?

- Public Websites and Sitewide Crew

- Is this a feature request or a bug?

  - [X] Feature request
  - [ ] Bug report

## Request/Report Description

Since the launch of VA.gov in late 2018, the site has featured one responsive Global header element that was not optimized for Mobile view. As a result, for our growing base of Mobile users, issues with the current header include:

- It consumes too much space, pushing down the most important element on the page (based on usage): the top tasks links.
- Some of the exposed navigational elements cause user confusion -- e.g. the Crisis Line logo was mistaken for a hamburger menu on mobile per user research
- Too many chevrons in the top right corner with all acting differently, causing confusion

The problem to be solved: How might we make the Mobile version of VA.gov easier to scan and use, while preserving important links in an intuitive way?

The proposed solution: A mobile-only optimized header that streamlines the size of the header by utilizing the "hamburger menu."  More details in this [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md).

We need Analytics to determine baseline performance of the current VA.gov Mobile header, including % of mobile users that click on: 

- Search (the little mganification icon) 
- Menu 
- Veteran Crisis Line 
- Contact us 
- Sign in 
- Back to home (VA logo/Home menu item in the current nav)

- (Data) What timeframes are you looking to analyze 
   - One year of performance
   - It would be good to include Desktop performance of the header elements during same period (for posterity)

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by brianalloyd** [comment]
@joanneesteban could you advise on when this might come into scope for your team?  This is a blocker for our implementation efforts for the VA.gov mobile header as we're looking to create a baseline in order to determine success metrics in support.  Let me know if you need anything from our team in support and I'll get it to you soonest in support.  Also planning to attend office hours this week to discuss but have some competition requirements. Let me know if you would like to schedule a quick zoom sync on this as well.  CC @rtwell @davidconlon

**Comment by bsmartin-ep** [comment]
Your requested metrics @brianalloyd.  Definitely a few gaps in our tracking of the header menu on mobile devices.  Our next office hours is 12:30 EST on Thursday if you want to discuss this.

## 2020-08-23 to 2021-08-23


## Total users by device category

[GA report](https://analytics.google.com/analytics/web/#/report/visitors-mobile-overview/a50123418w177519031p176188361/_u.date00=20200823&_u.date01=20210823)


<table>
  <tr>
   <td><strong>Device Category</strong>
   </td>
   <td><p style="text-align: right">
<strong>Users</strong></p>

   </td>
   <td><p style="text-align: right">
<strong>New Users</strong></p>

   </td>
   <td><p style="text-align: right">
<strong>Sessions</strong></p>

   </td>
  </tr>
  <tr>
   <td>desktop
   </td>
   <td><p style="text-align: right">
62,299,493</p>

   </td>
   <td><p style="text-align: right">
60,660,768</p>

   </td>
   <td><p style="text-align: right">
167,225,384</p>

   </td>
  </tr>
  <tr>
   <td>mobile
   </td>
   <td><p style="text-align: right">
46,514,817</p>

   </td>
   <td><p style="text-align: right">
45,562,890</p>

   </td>
   <td><p style="text-align: right">
125,214,357</p>

   </td>
  </tr>
  <tr>
   <td>tablet
   </td>
   <td><p style="text-align: right">
3,964,380</p>

   </td>
   <td><p style="text-align: right">
3,811,410</p>

   </td>
   <td><p style="text-align: right">
11,341,625</p>

   </td>
  </tr>
</table>



## Search (the little magnification icon)

We don't have direct tracking on the icon, but we can look at the _view_search_results_ events going back to December 2020.

[GA Custom Report template](https://analytics.google.com/analytics/web/template?uid=ralbK1-NQyuKxBUu7oiing)


<table>
  <tr>
   <td><strong><em>Device Category</em></strong>
   </td>
   <td><p style="text-align: right">
<strong><em>Users</em></strong></p>

   </td>
   <td><p style="text-align: right">
<strong><em>Percent  of Total</em></strong></p>

   </td>
  </tr>
  <tr>
   <td>desktop
   </td>
   <td><p style="text-align: right">
1,262,131</p>

   </td>
   <td><p style="text-align: right">
2.0259089%</p>

   </td>
  </tr>
  <tr>
   <td>mobile
   </td>
   <td><p style="text-align: right">
509,364</p>

   </td>
   <td><p style="text-align: right">
1.0950575%</p>

   </td>
  </tr>
  <tr>
   <td>tablet
   </td>
   <td><p style="text-align: right">
69,673</p>

   </td>
   <td><p style="text-align: right">
1.7574753%</p>

   </td>
  </tr>
</table>


If you want data before that, I can pull site search data.


## Menu

Unfortunately I see no tracking on the MENU button.


## Veteran Crisis Line

Event action = _Navigation - Crisis Modal Clicked - Header_

[GA Custom Report template](https://analytics.google.com/analytics/web/template?uid=zU1NWl2QRLiL_RVVtusQjQ)


<table>
  <tr>
   <td><strong><em>Device Category</em></strong>
   </td>
   <td><p style="text-align: right">
<strong><em>Users</em></strong></p>

   </td>
   <td><p style="text-align: right">
<strong><em>Percent of Total</em></strong></p>

   </td>
  </tr>
  <tr>
   <td><em>mobile</em>
   </td>
   <td><p style="text-align: right">
<em>128,076</em></p>

   </td>
   <td><p style="text-align: right">
<em>0.2753445%</em></p>

   </td>
  </tr>
  <tr>
   <td><em>desktop</em>
   </td>
   <td><p style="text-align: right">
<em>88,937</em></p>

   </td>
   <td><p style="text-align: right">
<em>1.4275558%</em></p>

   </td>
  </tr>
  <tr>
   <td><em>tablet</em>
   </td>
   <td><p style="text-align: right">
<em>7,709</em></p>

   </td>
   <td><p style="text-align: right">
<em>0.1944566%</em></p>

   </td>
  </tr>
</table>



## Contact us

Event action = _Navigation - Jumplink Click - Contact us_

[GA Custom Report template](https://analytics.google.com/analytics/web/template?uid=6262qu4cTC-inTH97ZUkAg)


<table>
  <tr>
   <td><strong>Device Category</strong>
   </td>
   <td><p style="text-align: right">
<strong>Users</strong></p>

   </td>
   <td><p style="text-align: right">
<strong>Percent of Total</strong></p>

   </td>
  </tr>
  <tr>
   <td>desktop
   </td>
   <td><p style="text-align: right">
332,050</p>

   </td>
   <td><p style="text-align: right">
0.5329899%</p>

   </td>
  </tr>
  <tr>
   <td>mobile
   </td>
   <td><p style="text-align: right">
205,467</p>

   </td>
   <td><p style="text-align: right">
0.4417238%</p>

   </td>
  </tr>
  <tr>
   <td>tablet
   </td>
   <td><p style="text-align: right">
14,230</p>

   </td>
   <td><p style="text-align: right">
0.3589464%</p>

   </td>
  </tr>
</table>



## Sign in

Event label = _login-link-clicked-header_

[GA Custom Report template](https://analytics.google.com/analytics/web/template?uid=Y7UHXbS0TPCDdKfcq4TgMA)


<table>
  <tr>
   <td><strong><em>Device Category</em></strong>
   </td>
   <td><p style="text-align: right">
<strong><em>Users</em></strong></p>

   </td>
   <td><p style="text-align: right">
<strong><em>Percent of Total</em></strong></p>

   </td>
  </tr>
  <tr>
   <td><em>desktop</em>
   </td>
   <td><p style="text-align: right">
<em>3,524,695</em></p>

   </td>
   <td><p style="text-align: right">
<em>5.6576624</em></p>

   </td>
  </tr>
  <tr>
   <td><em>mobile</em>
   </td>
   <td><p style="text-align: right">
<em>1,994,226</em></p>

   </td>
   <td><p style="text-align: right">
<em>4.2872919</em></p>

   </td>
  </tr>
  <tr>
   <td><em>tablet</em>
   </td>
   <td><p style="text-align: right">
<em>193,620</em></p>

   </td>
   <td><p style="text-align: right">
<em>4.8839919</em></p>

   </td>
  </tr>
</table>



## Back to home (VA logo/Home menu item in the current nav)

Unfortunately I see no tracking on the logo or HOME menu item.

**Comment by brianalloyd** [comment]
Insights received now we just need to complete Analytic requests to fill in the gaps on tracking from above.  I'm going to closing ticket in support and work independent tickets for the associated gaps identified.
