### ISSUE TITLE
Access for Jeff Dunn

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#28234]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Jeff Dunn
- Please Provide your email.
   > jeff.dunn@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Backend Tools Team, Product Manager, Oddball

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKBggDpcYlUK21Zq5SC+hvbOUStbmU/1B/5RGGkCn1/TrlJS3fJIiX9vVX61BpdPIj+QhiYZRolY9AOmSiyaZ/y7kkcwKzab/gFbDi4hLl3VTe8cSxNDaCjWKlvxIVLPcg9CE1QIKbcRSWgnfwZGVJwQY2Ff7jU0CSZuYFA2nZ24qARyPrUyG0e7Jf3W4cten3ES4xcBrGEeVNJ9ziWrOHMsVNdd35agJjhSZMpOrPynY8afdnT8HlQt9vqXukpBlfWRf9MUKDOa9Wvm+Es0W5J21zyH4wPvuY8QBaRoevdQ55SH8JlpvPoZDd9M7/pS94Brt7W1YvPeBW2P7MG5SSXccGgL9/k7fqsyqrsZrtvnJJYpxarVxv7iP5QYFp3NmCL5Zvh/WHlvn2j8G/iJ6xdSZpDWDPOXcGKb0k1S8hnrnR0DuJN5vorAz9ai9zG0a6GC3vMMgbWPStYWa2wTpC5JbHXNWw1c/wVmKVQ4E9QS6Z6FmZjMW7JS/KzDa8ZNs= jeffdunn@jeffs-mbp.lan

```

- Grant AWS Console access?
  > NO

**Comment by mleclerc00** [comment]
@jeff2d2 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
