### ISSUE TITLE
Upload Broken Link Report to S3

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#28233]
When broken links happen in CI, upload the resulting file to https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/broken-link-reports/

files should be prefixed with the environment:
vagovprod-broken-links.json
vagovstaging-broken-links.json
vagovdev-broken-links.json

Upload should happen at the same time at the slack alert.
Reach out to @indytechcook to figure out a way to ping the CMS when this happens

**Comment by swirtSJW** [comment]
For context, this is the next step in needing the CMS to be able to provide timely feedback to editors that my have created the broken link.

**Comment by alexandec** [comment]
@timwright12 Question about what to put in the S3 bucket if there had previously been broken links, but now there are no broken links. Should we:

1. Do nothing, leaving the existing broken links file untouched
2. Delete the existing broken links file
3. Replace the existing broken links file with an empty file

I assume we would only notify Drupal about the broken links when there are in fact broken links, so I would think any of those options would work. Is there any benefit to updating/removing the file when all the broken links are fixed? If there's no benefit, it's simplest to just leave the file as is.

**Comment by timwright12** [comment]
@alexandec I think we're good to just leave the existing file untouched, but I would probably just do the path of least resistance for that part. If it's easier to upload an empty file, that's fine too (we just wouldn't alert the CMS in that case)

**Comment by acrollet** [comment]
I see a benefit to removing the file, since it's possible that we would parse the file and show any detected broken links any time an editor is viewing a page that is reported.

**Comment by timwright12** [comment]
@acrollet I don't think this file would update with enough frequency for an editor to check it while viewing a page. This only gets populated when the build runs. So it's possible that a link is in the list, but has also been fixed.

**Comment by alexandec** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/content-build/pull/453). This handles file upload only. We can implement the Drupal ping in the future when there's an endpoint available.

**Comment by alexandec** [comment]
PR merged, and this is working in production.
