### ISSUE TITLE
Business intake form for VA health API - PeriOptimization Surgical Appointment Reminders

### ISSUE THREAD

**Issue by santy78** [department-of-veterans-affairs/va.gov-team#28231]
## Requestor Name 
Switchlane Technologies on behalf of Lebanon VAMC

## Business Line 
PeriOptimization(Surgical scheduling software)

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
Want to use VA notify app in a VA health API enabled web application. 

## What is an overview of the notification use case? (required 3-5 sentences) 
Use the email/sms notification feature.

Notify patients on the status of a procedure. 
To make everything COVID reminder - no information.

1) Surgical Appointment Reminder

The appointment is scheduled through the PeriOptimization. 

2) While at the surgery: 

Pre-Op Holding Area
Operating Room 
Recovery Room
Ready to go home

3) Other / Follow Up appointment reminders

Texts go to the Veteran and designated person. 
When they come in at the text - they tell the clerks and they put it in the PerioOptimization system. Not connected to VISTA at this time. The PeriOptimization system has the driver and that respective cell phone provider. The language includes consent from the Veteran but not consent from owner of the number. 

 

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
Its a reduction in phone call and reduction in missed appointment. 

Its a regular case where an appointment will be scheduled and a notification will be sent for it. For that notification we want to use VA notify. 

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No, Sending through twilo, which is not supported. Identified as blocker. 

## What kind of notification would this be? (required Email, Text, Not sure)
Text, Email

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
Yes and is approved. 

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
From a custom application(PeriOptimization/Surgical scheduling software) which is integrated to va health api

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
yes

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
Yes 
## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
Yes

## What is your estimated volume of notifications per day, week, month? (optional - open space)
2500/- per month, pretty much the same M-F with small variations day to day. 

## When does this notification need to be in production? (optional - open space)
October 4th 2021.

**Comment by santy78** [comment]
I have generated the client id, secret using the developer registration in va.gov but need to test out. Need some sample apart from the postman collection.

**Comment by miabecker** [comment]
@Santy78 What is the VA health API enabled web application you are interested in using VANotify for? Thank you!

**Comment by miabecker** [comment]
Wonderful can you share the name of the app, please?

**Comment by santy78** [comment]
The name is perioptimization. But it is still at initial integration and
discussion phase with the VA team.

**Comment by santy78** [comment]
The business sponsor is Robert Villare. ***@***.*** is my
official id.

**Comment by santy78** [comment]
> Cool! @santy78 thanks for sharing! And who is your VA business sponsor and or product owner?

The product owner name is Deborah Mentzer. Product name is PeriOptimization or PRO
Lebanon VAMC is the Facility

**Comment by bevnobev** [comment]
Adding their website for more info - https://www.perioptimization.com/

**Comment by miabecker** [comment]
Thanks for the update Santosh! Will get back to you with next steps tomorrow.

**Comment by santy78** [comment]
Thanks Maria. The earlier the better.

**Comment by miabecker** [comment]
@Santy78 thanks for your intake and additional information. We would like to coordinate a call next week to discuss your needs and technical architecture. Can you provide some times that would work for you and your team?

**Comment by santy78** [comment]
Hi Maria,

We can meet on Tuesday/Wednesday 12:00 PM EST.

Regards
Santosh

**Comment by bevnobev** [comment]
Hi @santy78 Maria is out of the office tomorrow and Wednesday of this week.  Are there any other dates/times that work for you?

**Comment by santy78** [comment]
We can meet on Thursday or Friday as well 30 min earlier.

**Comment by miabecker** [comment]
@santy78 what times work for you early next week for a 30 minute call? It looks like our team might have time Monday at noon, Tuesday at 11 or between 2-3:30, Wednesday 4:00pm. Let me know if any of these times work, who to invite and we'll send an invite.

**Comment by santy78** [comment]
Hi Maria,

We can meet on Monday. If possible make it earlier in the day rather than
late noon.
+ @Robert Villare ***@***.***> @Vanitha Yoganand
***@***.***> @Shankara Subramanian ***@***.***>
Regards
Santosh

**Comment by miabecker** [comment]
@santy78 I can't see the emails can you send them to me maria.becker@thoughtworks.com?

**Comment by santy78** [comment]
Below are the email id's

***@***.***
***@***.***
***@***.***

**Comment by miabecker** [comment]
I wasn't able to see your email address @Santy57 but here is the invite I sent out:

Maria Becker (she/they) is inviting you to a scheduled Zoom meeting.

Topic: VANotify x PeriOptimization Surgical Appointment Reminders
Time: Aug 16, 2021 12:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://thoughtworks.zoom.us/j/91475037503

Meeting ID: 914 7503 7503
One tap mobile
+13017158592,,91475037503# US (Washington DC)
+13126266799,,91475037503# US (Chicago)

**Comment by santy78** [comment]
+Vanitha Yoganand ***@***.***>  +Robert Villare
***@***.***> --Meeting with the VA Notify team today.

**Comment by miabecker** [comment]
Santosh@switchlane.com

**Comment by miabecker** [comment]
Primary code is on .net 4 - Send test code

**Comment by miabecker** [comment]
@Santy78 what area code would you want for production? For staging, we are thinking of giving you a not-specific number.

**Comment by santy78** [comment]
Hi Maria,

Area code is 717.

We have not yet got the api key, sample client code and access for sandbox
api testing as we discussed last day. Can you please look into it.

Regards
Santosh

**Comment by santy78** [comment]
Please ask Maria to include me in her emails. Then I can assure the project
moves forward.
She can email me directly at work: ***@***.***
Thanks.



Robert C Villare, M.D., MPA
302-545-0787
The information in this email and any attachments hereto, is
private, confidential and privileged material and may contain information
that is legally PRIVATE, PRIVILEGED AND CONFIDENTIAL and intended only for
the personal and confidential use of the named sender and recipient. This
missive may be to or from an attorney and thereby protected by
attorney/client privilege. This information is further protected under *the
Privacy Act of 1974, and/or *Federal HIPAA Laws and/or State Healthcare
Privacy Laws. Any opinions are protected by the Freedom of Speech of the
U.S. Constitution. If you are not the intended recipient, *you are hereby
notified that you have received this document in error , *you are strictly
prohibited from any review, printing, copying, saving, disseminating or
otherwise using this information. If employed you may not share this email
with your boss, supervisor or employer, and must delete all copies of the
message, and notify anyone who may have a copy or control of your computer
documents to do the same; including removal from your "trash bin and
recycle bin". Please notify the sender immediately.

**Comment by miabecker** [comment]
As mentioned over email we will revert back with the api key, sample client code, and access for sandbox
api testing once we've worked through some things internally on our side.

**Comment by santy78** [comment]
Thanks Maria

**Comment by santy78** [comment]
+Robert Villare ***@***.***> , +Vanitha Yoganand
***@***.***> -- please help with the  content of SMS or email
here and volume estimate(this was already shared in our last call I guess).

**Comment by santy78** [comment]
We have the rover video that demonstrates all of our messages. Pannetta can help you copy those exact messages and send it to them. I have already done this but there appears to be a barrier in everyone getting the information that I send.

Again, we estimate approximately 25,000 messages per year. Perhaps a maximum of 28,000 messages or a minimum of 23,000 messages. Those are total numbers intermixed with some that will be emails. Some veterans will receive emails because they do not use cell phones.
I hope this helps.

**Comment by miabecker** [comment]
Awaiting update on ATO (ETA next 2-3 weeks) as well as content from the business line.

**Comment by santy78** [comment]
+Robert Villare ***@***.***> , +Vanitha Yoganand
***@***.***>
