### ISSUE TITLE
"On this page" has no jump links

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28249]
## Issue Description

The [Surgery service program page on Pittsburgh](https://www.va.gov/pittsburgh-health-care/health-services/surgery-service/) has an "on this page" section but no jump links are displayed

![image](https://user-images.githubusercontent.com/55411834/128078547-26de73fb-9e09-45e4-80c4-5135421c6ece.png)

Typically, jump links refer to H2 titles. In this case, there are no H2 titles - Contact info is an H3

Content editor can select checkbox to include table of contents. 

## Dev notes
**Options**
- upgrade to web component (selectively or across the board) and address the bug 
   - cleaner code and can be selective/contained change
   - if we use web component, we'll need to consider if it is being used anywhere else and regression test
- address the bug in the current metalsmith [plugin](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js) (which will impact all pages with jump links)

**Decision** 
- migrate to web component and fix the bug (will be separate PRs)

---
## Expected behavior
- [ ] If the editor checks the box for the table of contents **_and_** there are H2 headings, the "On this page" table of contents should render 
- [ ] If there are no H2 headings, the "On this page" component should not be present, even if the editor has checked the box

**Comment by mpelzsherman** [comment]
The current implementation is in src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js.

Currently the “On this page” headers are hard-coded in the template. We would have to either modify the plugin to remove them, or remove them from all of the templates and modify the plugin to add them.

Instead I suggest we convert to use the new Web Component: https://github.com/department-of-veterans-affairs/component-library/blob/web-components/src/components/va-on-this-page/va-on-this-page.tsx, and fix the issue there.

**Comment by mpelzsherman** [comment]
We may not need to fix the web component [issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/530) if the design system team fixes it first.

**Comment by mpelzsherman** [comment]
@bkjohnson [observes](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/530) that the fact that Contact Info is an h3 is an a11y violation. The heading levels should not skip from h1 to h3. If we fix the heading levels in Drupal on this page, the issue should go away, with no need for any code changes.

**Comment by mpelzsherman** [comment]
Per @mmiddaugh, our product owner has asked us to fix this in our metalsmith plugin for now in order to unblock the ticket.

**Comment by bkjohnson** [comment]
I've written an issue (linked above) for making the a11y tests stricter - someone from @department-of-veterans-affairs/vsp-testing may be able to help out.

Also, I'm curious about an earlier comment of yours @mpelzsherman:

> We will not be able to migrate to the Web Component unless/until that bug is fixed.

The Web Component isn't in use now - the current behavior is coming from [this part of the content build](https://github.com/department-of-veterans-affairs/content-build/blob/f89ea0493ef4de92fee3344ba427cbdaf9b1cb2a/src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js#L84-L106). The end result is the same however - only `<h2>` nodes get added as list items under "On this page". My question is:  How is this blocking migration since the current behavior would be the same as the behavior after migration?

**Comment by mpelzsherman** [comment]
The current behavior of the metalsmith plugin has a bug, as defined by the product owner. 
It should not render a "table-of-contents" element if there are no jump links present in the content.
The PR linked above fixes that bug.
If we want to migrate to `va-on-this-page`, we will have to fix the bug there first.

**Comment by mpelzsherman** [comment]
Verified in prod. 

The "Heading levels should only increase by one" Axe error is still present on the page, but there is no extraneous empty table of contents now.

**Comment by kevwalsh** [comment]
We just rehashed this entire issue in [this slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1656350905472109?thread_ts=1656338299.814849&cid=C01DBGX4P45) (i hadn't seen this issue).
