### ISSUE TITLE
Upcoming events and the listing toggle on VAMC event listing pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28252]
## Issue description
In #27433, we resolved the discrepancy between preview and prod event listing pages
#25662 focuses on restoring the display of past events on VAMC event listing pages

**This issue is focused on the availability of the past/upcoming events toggle as it relates to upcoming event listing pages**

![image](https://user-images.githubusercontent.com/55411834/120834356-22e52500-c520-11eb-99f3-65e3a94722c7.png)

</details>

## Acceptance Criteria

**The following criteria assumes events are published (not archived, in draft or in review) and apply to the event list pages, not the individual event pages.**
- [x] If there are upcoming events, they are displayed on the upcoming events listing page. 
- [x] If there are no upcoming events, "There are no upcoming events" displays on the listing page.
- [x] If past events are available, the toggle is displayed on the upcoming and past event listing pages. 
- [x] If past events are not available, the toggle is not displayed. 
- [x] Pagination is independent between past and upcoming events (full build only)

**Comment by mpelzsherman** [comment]
@mmiddaugh The currrent message when there are no upcoming events is "No events at this time."
