### ISSUE TITLE
Access for Tony Valdez

### ISSUE THREAD

**Issue by tony-valdez-accenture** [department-of-veterans-affairs/va.gov-team#28264]
Instructions

Fill out Description
Add the label used by your team (eg: BAH-526)
Do not remove operations label; this will notify the VSP Operations team of your request
When the issue is closed you will be notified and can continue with on-boarding setup

Description

- Please provide your Contracting Officer's Representative (COR) name.
Laura Ross

- Please provide your name.
Tony Valdez

- Please Provide your email.
tony.valdez@accenturefederal.com

- Please provide the name of your team, your role on that team, and the name of the company you work for.
My Education Benefits Team: UI Developer: Accenture Federal Services

- Requesting SSH key authorization?
YES

- What is your public SSH key?
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnCxArq4tQc5c6F3MitXdULDgM4ZeGrnTbYtDQAlI0DErprcQBumz81Em6k0mnueqJp/WOYJwF8uyz8W53Ysphtg2fJKh9LQSUqCE7ZKm4asXWpsd/kaTZHS4xcMKwQuT8eEy/cmwJc6kcO+hnG/PMb1WgScRT+5jDZHtG6aYBH0Rrjf4/WLe35dbNDluetv9WTC+I2rd2bzVoe+sGpQTfL01DgK25aJAuMCMgq/ny+L+4anyWvnQKC9NWf1L5dOEkq8sV3V+F1i+Q3Irb+RpDkT6ufoYMZb2WnN0QIEZmvx2Oc8g8faQefSTpOZMS5My7PeXsVzsscV9FOeh0vND4vcA6c2sWNeAwNXvXUIPhtheYIqDvSUV8R1H1oIMVg+OPjzbXILdDZxB2zlntU+EvUk0UcH7S9Fp5HqKQ0dnMfC5vS04FWmAm1g4OYGauwUvaFZLRBpvJ7LB5VSBbzxkFa9j5PU/xHSnVjzk1h2jcN31urkOQjva0LRj579C9sqM= tony.valdez@AFSMWTY9N4RF0PL

```

- Grant AWS Console access?
NO

**Comment by mleclerc00** [comment]
@tony-valdez-accenture

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
