### ISSUE TITLE
[Discovery] Technical Analysis for New Mobile Header

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28288]
## Issue Description
Since the launch of VA.gov in late 2018, the site has featured one responsive Global header element that was not optimized for Mobile view. As a result, for our growing base of Mobile users, issues with the current header include:

It consumes too much space, pushing down the most important element on the page (based on usage): the top tasks links.
Some of the exposed navigational elements cause user confusion -- e.g. the Crisis Line logo was mistaken for a hamburger menu on mobile per user research
Too many chevrons in the top right corner with all acting differently, causing confusion
The problem to be solved: How might we make the Mobile version of VA.gov easier to scan and use, while preserving important links in an intuitive way?

The proposed solution: A mobile-only optimized header that streamlines the size of the header by utilizing the "hamburger menu." More details in this [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md).

## Front end tasks
- Review product outline and provide a technical analysis on implementation
- Provide best recommendations for optimized UX/UI
- Include risks and ideas to mitigate risks for implementation 
- Add questions for PO/PM/Lead Designer for follow up and determination during future planning and grooming sessions

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Rleahy22** [comment]
- Review product outline and provide a technical analysis on implementation
  - Many of the changes in the product outline are cosmetic including:
    - Updating the "Official..." banner to consume less space
    - Removing the "crisis line" logo
    - Use a simplified version of the VA logo
    - Add th hamburger icon to the Menu button
    - Remove the Home page item in the menu"
    - "Contact us" moves to the bottom spot on the expanded menu
    - Wrap "Close menu" with the expanded menu
    - Authenticated user drop down menu moves to the top
  - All of these changes can be done by removing/updating assets and elements with minimal risk
  - Some changes will involve relocating existing components 
    - Sign in stays persistent in the header
    - Search is now usable in the expanded menu
    - Currently these are part of the [SearchHelpSignIn component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx), but would need to be broken up into individual components so we can relocate the individual UI pieces
- Provide best recommendations for optimized UX/UI
  - Earlier comments mentioned building out 2-4 components 1 for each combination of Unauth/Auth + Desktop/Mobile, but it looks as though the distinction between unauth and auth at the component level is already done for us [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx#L36-L66), so we can mostly copy the [MegaMenu](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/mega-menu/components/MegaMenu.jsx) to a `MobileMegaMenu` component that can be combined with the [MobileMenuButton](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/mobile-menu-button/containers/Main.jsx)
  - We should consider moving the mobile mega menu out of `content-build` entirely and having it render by react so it can sit below the menu button within the dom, making it easier to have connect the background/border of the menu and button
- Include risks and ideas to mitigate risks for implementation
  - The biggest risk is in breaking functionality, especially anything tied to the redux state when we break out the components in the [SearchHelpSignIn component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/components/SearchHelpSignIn.jsx), but we can mitigate this risk with E2E testing
- Add questions for PO/PM/Lead Designer for follow up and determination during future planning and grooming sessions
  - None at this time

**Comment by Rleahy22** [comment]
@kelsonic @brianalloyd let me know your thoughts on the technical analysis above, please.

**Comment by kelsonic** [comment]
will read this asap, sorry for the delay! 🙂

**Comment by brianalloyd** [comment]
Great work on this @kelsonic and @Rleahy22, great technical walk through that will help me build out the Product assumptions now, thank you so much for the support.  Closing out ticket in support.
