### ISSUE TITLE
Create AWS group for the Testing Tools team

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#28285]
Description
Inside AWS, we would like to have a Testing Tools group for members of the Testing Tools team with permissions that allow us to at least view and manage object expiration on the following buckets:

testing-tools-testing-reports

Background/context/resources
Our S3 bucket `testing-tools-testing-reports` was created to store our test reports.  Now we need our team to be able to view files in this bucket as well as have the ability to manage object expiration to ensure that the bucket stays clean.

**Comment by jhouse-solvd** [comment]
@CBonade - Can you see if this was done based on @mydesignrocks merged PR above? Sri is out right now but wanted to check on the status.

**Comment by dginther** [comment]
Verified that this is complete. Curt has a request in to add some permissions to the front-end user which is separate from this request.
