### ISSUE TITLE
Understand magnitude of forms' refactor

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#28294]
Go through the entire code base, find all the forms, and determine the difficulty of refactoring their business logic into Ruby classes.

Answers for:
- [x] How many forms are there?
  - Check out config/form_profile_mappings. If they're using the forms' system they'll be in there. If they're non-conforming they won't. The yaml files are how the data gets mapped.
- [x] How much work is there?

**Comment by jeff2d2** [comment]
@ericboehs @rileyanderson Can we get some notes in here on progress?

**Comment by ericboehs** [comment]
Migrating synchronous forms' business logic to an asynchronous-like process appears to be lower complexity than initially thought (assuming no changes to vets-website). For complete asynchronicity, collaboration with the front end team will be necessary but implementation complexity is primarily on the front end in this regard.

There are [44 forms defined in vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema/tree/master/src/schemas). These forms are processed through the [FormsController](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/forms_controller.rb). There we can extract calls to all or individual forms' business logic via Sidekiq classes. For initial compatibility, these classes would be called synchronously (via `perform_now`) and after full integration (with collaboration from front end) would be called asynchronously (via `perform_later`).

Any form that falls outside the `FormsController` pattern would need to be migrated or evaluated for independent migration.

**Comment by drorva** [comment]
@ericboehs great to hear that the complexity is lower than expected.
Did we figure out a way to tell which services each form depends on?
