### ISSUE TITLE
Analytics Feature Request Report

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28296]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [X] Ticket Description
- [X] Request/Report Description
- [X] Additional Comments

## Ticket Description

Who is this request for?

Public Websites Team - Unauth Crew 

- Is this a feature request or a bug?

  - [X] Feature request
  - [ ] Bug report

## Request/Report Description

The PW team recently received approval from OPIA stakeholder to make the Homepage Alert Banner dismissible for users with some use cases that the banner reappears if new content is added to it. As a component we need to track how many times this banner is dismissible via users in order to track effectiveness. This will also provide some historical analytics to share with OPIA and other stakeholders in order to make more informed decisions concerning banner alerts forward.

For a new feature request:

- Looking to track how many times the Homepage Alert Banner is dismissed via users. 
- Effectiveness of dismissible banners going forward.  This will also provide some historical analytics to share with OPIA and other stakeholders in order to make more informed decisions concerning banner alerts forward.

- (Data) What timeframes are you looking to analyze: **08/01/2021 forward.**

## Additional Comments

_Please reach out if Public Website PM/PO with any questions concerning this request.  PW Internal ticket to track details can also be found [#28295](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28295)_

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks for opening this, @brianalloyd ! To clarify, are y'all requesting new Google Tag Manager tags for the historical alert banner? Or are you looking for a feature request to have that data visualized as a report?

**Comment by brianalloyd** [comment]
Thanks @joanneesteban appreciate the follow up, we're looking for a new feature request to have the data visualized as a report.  Looking to see how many users dismiss the alert banner to help inform decisions.

**Comment by joanneesteban** [comment]
Thanks, @brianalloyd , for the clarification! We'll add this to our feature request backlog. If you're able to, we can also help guide you in creating a Google Analytics report for this during one of [our office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguide-5.AdditionalAnalyticsSupport).

**Comment by brianalloyd** [comment]
I'll plan to attend next office hours session.  Thanks @joanneesteban for the support and assistance.

**Comment by bsmartin-ep** [comment]
Oh it will definitely get you where you need to go.  A `recordEvent` or direct push to the dataLayer will get your events into GA.  But Brooks and Chris V asked us to slightly abstract this [with this function](https://github.com/department-of-veterans-affairs/component-library/search?q=dispatchAnalyticsEvent).  The argument being it doesn't tightly couple the components with a particular event structure and makes things like our future GA4 expansion (which would be a totally different `event`) a bit easier to implement.

**Comment by bsmartin-ep** [comment]
Apologies @brianalloyd - it doesn't appear tagging on this was completed on our end.  We have event data, but without the headline in the Event action.  

I fixed the tagging, so we should start seeing [correct data here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20211024&_u.date01=20211031&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:int-alert-box-close/) in the very near future.

**Comment by brianalloyd** [comment]
@bsmartin-ep thanks for the efforts on this, reviewed and have a question as to what "unknown" is tracking?  
![Screen Shot 2021-11-04 at 3 20 02 PM](https://user-images.githubusercontent.com/70410912/140421952-f2bbe12b-69fe-4ddb-a024-74ec042cb119.png)

**Comment by brianalloyd** [comment]
@bsmartin-ep circling back on this, can you help determine what "unknown" is tracking?

**Comment by bsmartin-ep** [comment]
@brianalloyd - I believe our tagging wasn't live before this event was being entered into GA so the Event Action defaulted to "Unknown".  You can see how it [drops off around 2021-11-01](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20211001&_u.date01=20211130&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5B%22Unknown%22%5D%5D&_r.drilldown=analytics.eventLabel:int-alert-box-close/).

![image](https://user-images.githubusercontent.com/62304138/144322179-05e5dbe8-244a-416d-8799-bb60d9f6f040.png)

**Comment by bsmartin-ep** [comment]
How are we on this @brianalloyd?  Anything outstanding or OK to close?

**Comment by michelle-dooley** [comment]
Hi @brianalloyd - looks like you have everything you need for this one so I'm planning to close.  Please let me know if you have any questions.  If you need any more assistance please open a new ticket for tracking in the new year.  Thanks, Michelle.
