### ISSUE TITLE
Clean up non-actionable Sentry issues

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#283]
## User Story
As a VSP or VFS engineer, I need to know that every error-level issue deliberately sent Sentry is actionable so I can focus on fixing the right things.

## Goal
Non-actionable issues [like this](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/letters/containers/AddressSection.jsx#L76) are not sent to sentry.
- Alternatively, if the information is still useful to collect for monitoring third-party data or whatever, use the `info` or `warning` severity
- Only actionable events from vets-api or vets-website are in sentry.

## Acceptance Criteria
- [ ] Definition of actionable is documented
- [ ] All uses of `Raven.captureMessage` and `Raven.capture_message` are audited
- [ ] Instances where the message describes a valid state are removed or the severity is set to `info` or `warning`

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by omgitsbillryan** [comment]
We may be able to create StatsD metrics in place of some of the BE sentry `log_message_to_sentry` places.
