### ISSUE TITLE
Stretch: visualize our 'new' customer support guide

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28305]
## Issue Description
Visualize the process for standardized dashboards instead of custom dashboards. Point the VFS teams towards standardized dashboards instead of custom dashboards. Other ideas:

- Visualization of dashboard eligibility navigation
- "Why Standardized dashboards" campaign
- Lunch & Learn syllabus + training

---
## Tasks
- [ ] Create an artifact that points VFS teams to standardized dashboards instead of custom dashboards.

## Acceptance Criteria
- [ ] Fewer VFS teams request custom dashboards or custom dashboard iterations. More VFS teams request standardized dashboards.

**Comment by chloedotbrown** [comment]
Completed as part of #36294 .
