### ISSUE TITLE
Surgery Notification Patient Selection Truncated

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#28316]
The surgery notification patient selection drop-down truncates choices around 45 choices.

**Comment by jwowk** [comment]
Recommended the site add first few letters of first name as well to narrow selection. This worked so maybe it should be a training procedure vs. programmatic change which could cause performance issues with more choices.

**Comment by shanemelliott** [comment]
@jwowk  can you expand a little more? I am not sure I understand this.

**Comment by jwowk** [comment]
“Station 520 cannot add certain patient names to Surgery Notifications, we type in the last name, and the list of patients does not go far enough to pick out patient. Example, we have a pt with first name Henry, and the list only goes to Harry. Can someone help with this issue?”

The resolution was to type LASTNAME,FIRSTNAME to see the exact patient. I added this ticket as a possible usability issue that could be resolved with instructions to enter more characters to narrow the selections down.

**Comment by jwowk** [comment]
Update UI so default name prompt says "Enter LastName,FirstName or  LastName+LastFourSSN"

**Comment by jwowk** [comment]
Update UI so default name prompt says "Enter LastName,FirstName or  LastName+LastFourSSN"
