### ISSUE TITLE
AWS Staging: Optometry Direct Scheduling 

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#28319]
John Morrison should be able to direct schedule Optometry but instead of direct scheduling flow, the request flow is displayed.

1. VATS:  Cheyenne Direct Schedule  - Optometry = Yes Any Veteran. Request = Yes Any Veteran. 
2. Patient (John Morrison) has past appointment in Optometry clinic ( Chy Opt Var1 05/11/2021@09:15 No Action Taken and Chy Visual Field  04/30/2021@09:10 No Action Taken )        
3. Log into VAOS, select Eye are, select Optometry and select Cheyenne.  
4. **Expected Response:**  User is able to direct schedule Optometry or cans elect a different clinic and gets dropped to Request flow
5. **Actual Response:**  User is dropped into Request flow. 

Console shows the following
Eligibility checks for location 983 and type of care 408
     User not eligible for direct scheduling:
      The FE could not find any of the clinics returned by var-resources in the past 24 months of appointments

User passed checks for requests

**Comment by jbalboni** [comment]
At the moment, following these steps results in a failed past visits check on the backend. The front end is correctly reflecting the result of the backend logic.

@marcynadeau If you think this should currently be working, I can open a JIRA ticket.

**Comment by marcynadeau** [comment]
@jbalboni @laurenernest. Please close this issue. This has been resolved.

**Comment by aarathi-poldass** [comment]
@laurenernest  The issue has been resolved.
