### ISSUE TITLE
Build out drop down component part 1

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28320]
##  Description
This ticket is to build the initial drop down component to replace the existing typeahead component. Once this component is created, there will be additional tickets to add in all the analytics tagging and ensure that all accessibility requirements are met

## Background 
The following ticket contains relevant requirements and details
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27353

## Acceptance Criteria
- [x] dropdown component framework is in place and baseline functionality is established.

**Comment by srsuddath** [comment]
Work is currently in progress, and coming along nicely, you can see the component in progress here:
https://github.com/department-of-veterans-affairs/vets-website/tree/srsuddath-28320-search-dropdown

**Comment by srsuddath** [comment]
due to unexpected leave (death in the family) I am splitting this ticket into two parts and lowering the effort related to each. I will complete part 1 in sprint 54 and part 2 in sprint 55

**Comment by srsuddath** [comment]
Closing this part 1 ticket, as most of the functionality of the drop down component is in place. part 2 will complete the component in sprint 55
