### ISSUE TITLE
Verify drop down component meets 508 standards

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28322]
##  Description
Ensure that the new drop down component meets WAI-ARIA_1.2 guidance and meets all accessibility guidelines

## Background 
- this ticket contains all of the resources necessary
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27353

## Acceptance Criteria
- [x] dropdown component is capable of passing an accessibility audit.
- [x] Check for screenreader pronunciation errors
- [x] @denisecoveyduc to schedule quick demo with Angela to demo screen readers - may help us resolve #24779

**Comment by srsuddath** [comment]
I have made a number of changes to the component and have done a pre-lim accessibility audit. 

Once we implement Megans design changes we will be good to go for a review!
