### ISSUE TITLE
AWS Staging: Alert Message Needs to be Updated to include number of months

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#28323]
## Summary
When a user doesn't meet the past visit check, the alert messaging should indicate the amount of time checked.
![28323 scope.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/a84ac49b-e11d-4b6e-acf6-682a5883e764)
![28323 scope 2.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/70e18021-37d4-4e2e-8b2c-9db24b5d91be)

## Acceptance Criteria

- [ ] Given user doesn't meet past visit check, When type of care is Primary Care or Mental Health, Then alert description copy should say "...past {number of months} months..."
- [ ] Given user doesn't meet past visit check, When type of care is **not** Primary Care or Mental Health, Then alert description copy should say "...past {number of months} months..." AND {number of months} should not exceed 24

---

**Original description**
VATS will have new last seen within limit. It was 24 months and now it is 36 months.  

This Alert message in VAOS will need to be updated to say within past 12-36 months.  

1. In VATS for DAYTSHR. Set Optometry direct scheduling = Last seen within 36 mos.  
2. Login as a veteran that does not have any past checked in or Checked out appointments in the last 12 months.  (vaostest,patienttwo: marcy.nadeau@va.gov Password 1234!)
3. Select Eye Care, Optometry as Type of Care. Select Dayton VAMC.  Message displays.  

  

Alert:	
We couldn’t find a recent appointment at this location
You need to have visited this facility within the past 12-**24** months for optometry to request an appointment for this type of care.

Please call the facility to schedule your appointment or search for another facility.

**Comment by laurenernest** [comment]
@jbalboni Shouldn't the months dynamically update?

We shouldn't show a range so if that's the case, I'll switch this ticket to fix that.

**Comment by jbalboni** [comment]
Yeah, I think this is a bug where it's not displaying the correct month setting.

**Comment by laurenernest** [comment]
Updated the ACs and moving back to ready. For types of care other than PC and MH, we would still have to show no more than 24 months in the copy due to the FE check.

**Comment by jbalboni** [comment]
@laurenernest I think we're correctly handling that scenario, unless you're saying you saw it not working in staging.

When there are no matching clinics, we show the no clinics message, rather than a past months message.

**Comment by laurenernest** [comment]
This test result with the Optometry & 36 months is what stood out to me, but if the clinic wouldn't even show up then that makes more sense. 
> To schedule an appointment online at this location, you need to have had an optometry appointment at this facility within the last 36 months. Please call this facility to schedule your appointment or search for another VA facility.
