### ISSUE TITLE
CT: Remove link to PDF from 702 caution flag.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28325]
As an EDU team member, I need the PDF link removed from the 702 caution flag so that the user is not taken to a 404 page because the PDF is no longer available for review.

## Assumptions:
1. The flag content is shared between the CT Classic & Sandbox.

## Acceptance Criteria:
1. The "Learn more about Section 702 requirements" link is not displayed.

## Supporting Artifacts:
1. Link to remove:
<img width="1078" alt="702_Caution_Flag" src="https://user-images.githubusercontent.com/48260534/128370309-34f37b1b-0827-43ea-a3c7-b0f8117f9a46.png">

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/853

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
