### ISSUE TITLE
Add analytics event logging to component

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28321]
##  Description
This ticket is to implement the analytics tagging for the dropdown component

## Events that need to be added
- [x] When a user clicks on or presses enter while a drop down item is selected
- [x] When a user tabs and presses enter focusing the search button
- [x] when a user presses enter focusing the input field
- [x] Reach out to analytics and make a plan to add a "location" field to allow data to be filtered based off which input field is being used

**Comment by denisecoveyduc** [comment]
@srsuddath Just in case you need this when we are ready we can request the Analytics Review touchpoint for the collab cycle. Here is the info you would need if you want to proceed before my return. 

**[Analytics Request Information](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)** which includes the link to the **GH ticket template** you would need to create. Just ensure you add the search & discovery label and maybe share the link in slack so I can snag it when I get back.

**Comment by srsuddath** [comment]
all relevant analytics tagging is in place
