### ISSUE TITLE
508-defect-3 [SCREENREADER, COGNITION]: Link text "download them online" should include target and purpose

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#28348]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user who navigates by means of a links list, I expect links to include a clear target and purpose so I know what they will do and where they will lead me.

## Details

The link text "download them online" on the "Your VA Debt" page is not specific enough to help screen reader users take action. Rewriting the content below the heading "By Mail" can help.

## Acceptance Criteria

- [ ] "download them online" is rewritten to include a target and purpose

## Steps to Recreate

1. Log in to user 1 and go to `https://staging.va.gov/manage-va-debt/your-debt/`
2. Confirm the link text below the heading "By Mail" is written as "download them online"

## Proposed Solution

Consider rewriting the content to accommodate a link text that contains a target and purpose:
You can [download instructions on how to pay by mail online](https://staging.va.gov/manage-va-debt/your-debt/debt-letters) or in the demand letter sent to your address.

## WCAG or Vendor Guidance 

[Accessibility Oz - Links and accessibility](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)

## Screenshots or Trace Logs

<img width="756" alt="Screen Shot 2021-08-05 at 1 22 06 PM" src="https://user-images.githubusercontent.com/14154792/128393892-ff5c3b1f-80cd-44c9-a7dd-443fdca2c7d0.png">

**Comment by denisecoveyduc** [comment]
We no longer offer Veterans the ability to download letters from VBMS on the debt portal and therefore this link has been removed from the experience and this issue is no longer applicable.
