### ISSUE TITLE
CT Redesign: Update Book stipend (Learn more)

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#28344]
## Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/10000008
2. Select "learn more" on Book stipend (Learn more)
3. Modal displays "The book stipend is paid as a lump sum at the beginning of the school year (if starting in the Fall) or at the beginning of the semester. The book stipend is $1,000 per year or $83 per month at 100% benefit. The book stipend is pro-rated based on your enrollment."

## Expected results:
Modal should say:
"You may be eligible for money to cover books and supplies, up to $83 per month."

**Comment by dneel-bah** [comment]
Closing this as OBE as it will be covered in #28618.
