### ISSUE TITLE
Analytics KPI dashboard request for Content & Localization

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#28340]
# Request a Standard KPI Dashboard

## What this form is for

Use this template to request a KPI dashboard on Domo for your product. 

We are currently only supporting standardized dashboards for Forms, Content, & Search products. If you have another VA.gov product, please reach out to the Platform Analytics & Insights team on #vfs-platform-support. Please note that these dashboards will require additional data and design discovery, and will take additional time to deliver.

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 

- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).

### Expected delivery timelines

Your KPI dashboard request will be added to the Platform Analytics & Insights team's customer support queue, and we expect tickets at the top of the queue to be pulled in every Platform Sprint Planning & Refinement (every Wednesday). We appreciate your patience.

- Once your ticket has been pulled into the Platform sprint, we expect to deliver your completed dashboard within the next 4 business days. Please use this ticket for any follow up questions.

## Instructions for the VFS team

- [ ] **Please fill out [this template](https://docs.google.com/spreadsheets/d/1dIh-MVmVYCc2mZ_b_8y-cPVZB5-8RIShuOP_ng9uqAA/edit#gid=0) ([attached Excel sheet](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo) if you do not have Google access) & link it below to help define your product/feature's information.** The Analytics team will ***not*** be able to pull this ticket into the queue until this is provided & linked.
- [ ] Add your team label to follow progress
- [ ] If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

## VFS-provided information

[Funnel Information](Add your product/feature's funnel information here) - Add your product/feature's funnel information here

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Build (See [internal process document](https://vfs.atlassian.net/wiki/spaces/AT/pages/1464598569/New+KPI+Dashboard+Request+Process) & [how to](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/WIP%2B-%2BHow%2Bto%2Bcreate%2Bstandardized%2Bdashboards%2Bin%2BDomo))

- [ ] Add the `VSP Analytics & Insights` Group as the dashboard owner
- [ ] Structure funnel data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Document any blocked/unavailable metrics in the Analytics team space
- [ ] Update the dashboard header, including Google Analytics links
- [ ] If any, add [implementation issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) for additional necessary implementation

2. Q&A

- [ ] Please see & complete the [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

3. Share

- [ ] Add VFS group & default group to the dashboard

  *For new VFS customers only:* 

- [ ] Schedule onboarding meeting

- [ ] Host the meeting to explain how the dashboard works

## Definition of Done

- [ ] Acceptance Criteria has been completed
  - [ ] KPI Dashboard full QA checklist completed
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
Hi @SKasimow ! Which product are you looking to get a KPI dashboard on?

**Comment by SKasimow** [comment]
@joanneesteban Hi - I think I started this to add tracking for the additional pages we launched after the Covid and Corona pages. In addition to Tagalog versions for these 2 we also have 3 new pages I'd like to have included in dashboard. Is this the right ticket to request this?

**Comment by joanneesteban** [comment]
Hi @SKasimow - thanks for the quick response! Yes, this is the right ticket ✅  Would you be able to fill out the template in the instructions section? Once it's filled out, we can move this into refinement and look into adding it into sprint.

**Comment by joanneesteban** [comment]
Hi @SKasimow - let us know once you have the template filled out! We can pull adding the Spanish Covid/Corona pages to the Content KPI dashboard into our sprint.

**Comment by SKasimow** [comment]
Hi @joanneesteban - I just realized that I actually completed the template for this last month and included all of the translated pages we built that we wanted to be included in our dashboard:   https://docs.google.com/spreadsheets/d/1pdKJTz9fuFGR64UXXbTe3Bu_tENFmh0MAmMBt9k-A3s/edit?usp=sharing   

Is there anything else you need from me?

**Comment by chloedotbrown** [comment]
Thanks, @SKasimow! This should be all we need. I'll assign myself to the ticket and reach out if there are any questions.

**Comment by SKasimow** [comment]
Thanks @chloedotbrown!

**Comment by chloedotbrown** [comment]
Hi @SKasimow - your new urls have been added to the [Content KPI Dashboard](https://va-gov.domo.com/page/426422632)! I'll close this ticket at the end of today, though feel free to follow up if you have other questions.

One quick note: I did notice that you'd added a  `page_name` field in your request template – this isn't a field we currently collect for this dataset, but I _do_ think that it could be a useful [Feature Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+enhancement&template=analytics-feature-request-bug-report.md&title=Analytics+Feature+Request%2FBug+Report) for us in the the future, since it's easier to read than `product_url` or `page_title` filters. We'd need to reach out to teams with products currently on the dashboard to get that info and then backfill the data, so it's outside the scope of this ticket – but for now, I did go ahead and add the `page_name` field just for your new urls since we had them. 

If you wanted to be able to use this as a filter for your new pages, you could create custom dashboard view that's easy to access and that would only be visible to you. I'm including a GIF here to walk you through the process. Feel free to drop by Collaboration Cycle tomorrow or our office hours on Thursday if it's easier to demo!

![Create a custom view](https://user-images.githubusercontent.com/45518242/130669210-44e609b1-4b1f-4504-bfa7-badccec11755.gif)

**Comment by chloedotbrown** [comment]
Closing ticket.
