### ISSUE TITLE
508-defect-2 [SCREENREADER, COGNITION]: There can be multiple duplicate "Go to debt details" labels for links without specific targets

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#28352]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

- As a screen reader user, I expect links to include a target and a purpose
- As a voice AT user, I expect links that go to different pages to be uniquely labelled so I can accurately interact with the link I want to select
- As a screen reader user, I expect links that go to different pages to be uniquely labelled so I don't confuse them within a links list as going to the same destination

## Details

There can be multiple "Go to debt details" links on the page which can cause confusion or issues for screen reader and voice AT users as listed in the user stories above. There may be better alternatives to designing the links to be more actionable and specific. I'd recommend working with a designer to discover an alternative solution.

## Acceptance Criteria

- [ ] Links contain target and purpose
- [ ] Links that go to different pages do not share the same accessible label

## Steps to Recreate

1. Log in as user 1 and go to `https://staging.va.gov/manage-va-debt/your-debt/#currentDebts`
2. Run an axe scan
3. Confirm the error "links with the same name have similar purpose" emerges

## Proposed Solution

If the links are just meant to send the user to a generic details page, it may be better to link the headings and provide more actionable guidance below. For example:

<img width="783" alt="Screen Shot 2021-08-05 at 1 49 15 PM" src="https://user-images.githubusercontent.com/14154792/128397243-b3561548-258f-4eaf-854d-caa33b1d7e16.png">

The first debt has no immediate action, so no action link is provided. The second debt has a payment that's required, so a link to where the user can pay is provided _along_ with a specific label just in case there are multiple on the page.

## WCAG or Vendor Guidance (optional)

[Ensure that links with the same accessible name serve a similar purpose](https://dequeuniversity.com/rules/axe/4.2/identical-links-same-purpose?application=coconut)

## Screenshots or Trace Logs

<img width="1792" alt="Screen Shot 2021-08-05 at 1 45 32 PM" src="https://user-images.githubusercontent.com/14154792/128397380-de8d6905-36cb-4c85-a6db-06cc62ebad61.png">

**Comment by denisecoveyduc** [comment]
These were updated with combined debt portal
