### ISSUE TITLE
Discovery: Require minimum testing coverage for component-library PRs

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#28358]
## Issue Description
`<obvious-statement>`To ensure we have adequate testing coverage, we need to require PRs to include tests.`</obvious-statement>`

While test coverage doesn't mean the tests are _good_ or _complete,_ it's not nothing. :man_shrugging: 

## Considerations (8/2023)
- Validate prior research done below is still relevant given it's over a year old

## Acceptance Criteria
- [ ] Propose a method to add e2e coverage to minimum test coverage report

**Comment by bkjohnson** [comment]
We can easily work Jest coverage (unit tests) into our testing with this:

![image](https://user-images.githubusercontent.com/2008881/160471774-2b8afc63-3be6-4483-a7ff-abf5b37061b8.png)

But it doesn't include puppeteer (E2E) coverage:

![image](https://user-images.githubusercontent.com/2008881/160491267-8a51b2ef-652f-4b3c-8e96-a8ce7cc696a0.png)

This has [been a problem for a while](https://stackoverflow.com/a/51688048), and it's unclear what a good solution would be. There has also been [some mention](https://stencil-worldwide.slack.com/archives/CG0TNT3EH/p1633707895017900?thread_ts=1633706057.014700&cid=CG0TNT3EH) of the problem in the Stencil slack, and the Stencil team [decided not to support this feature in 2020](https://github.com/ionic-team/stencil/issues/1219#issuecomment-570102811).

**Comment by k80bowman** [comment]
We discussed this during the engineering weekly discussion. Due to the fact that most of our tests are e2e tests and there doesn't seem to be an easy way to integrate coverage information from those tests with the coverage information from our jest unit tests. Closing this ticket for now, we'll create a new ticket for discovery on this to be worked on in the future.

**Comment by caw310** [comment]
Reopening so we can start up work so we can track automated test coverage of component library.

**Comment by powellkerry** [comment]
On researching this it appears that, when running `stencil test --spec --e2e --coverage`, coverage continues to only be reported for unit tests and not E2E tests (majority of tests on component library). This causes the coverage report to look like the screenshot, where every component that does not have unit tests results in 0% coverage. Continuing to look into solutions

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVZ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19fe11b5b5508f74e29a6ed887eb538b175a2d0b/Screenshot%202023-09-05%20at%203.49.14%20PM.png)

**Comment by powellkerry** [comment]
On researching this it appears that, when running `stencil test --spec --e2e --coverage`, coverage continues to only be reported for unit tests and not E2E tests (majority of tests on component library). This causes the coverage report to look like the screenshot, where every component that does not have unit tests results in 0% coverage. Continuing to look into solutions

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVZ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19fe11b5b5508f74e29a6ed887eb538b175a2d0b/Screenshot%202023-09-05%20at%203.49.14%20PM.png)

**Comment by powellkerry** [comment]
Further investigation:
Puppeteer, which is how stencil runs E2E tests, does have methods to start and stop coverage. However it would take a major re-factor of all of our tests. Currently our E2E tests instantiate a new "page" for each test ("it"), the coverage methods are part of the page, ie `page.coverage.startJSCoverage()`. We would need to refactor our tests to use a single page, per component, on which we could call these methods.

See: https://pptr.dev/api/puppeteer.coverage

**Comment by powellkerry** [comment]
Closing for now. There is not an active effort to include E2E/puppeteer tests in coverage calculations by the Stencil team. As mentioned above we could possibly achieve getting some coverage totals by refactoring our tests so that each component only instantiates the page once, but this seems like a huge effort.
