### ISSUE TITLE
Require minimum testing coverage for formulate PRs

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#28357]
## Issue Description
`<obvious-statement>`To ensure we have adequate testing coverage, we need to require PRs to include tests.`</obvious-statement>`

While test coverage doesn't mean the tests are _good_ or _complete,_ it's not nothing. :man_shrugging: 

## Acceptance Criteria
- [ ] PRs which don't include 80% test coverage of new code are rejected by CI

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new bug.
