### ISSUE TITLE
General Analytics Request for Debt resolution - Veteran user Journey to FSR

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#28356]
# General Analytics Request

## What this form is for

Use this template to request support for analytics that need interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- [Linda Li]

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data, link to this Github issue, and tag `@platform-analytics`._
    
- What team/project is this work for?

    _this adds context for the data_
    - Debt Portal
    
- What type of analytics support are you looking for?

  - [ ] analytics discussion (I would like to track when veterans receive emails notifying them they have pending debt and a link to debt portal to take action,  how many veterans went to the debt portal from link provided in email, reviewed their debt, and clicked "get help for your debt" to FSR verses how many veterans bounced around outside the fennel and came back to FSR) 
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

## Analytics to Track Down
> Examples
> 
> - [ ] Metric 1
> - [ ] Metric 2
> - [ ] Metric 3

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks for opening this ticket, @LindaLi123 !

Following up from [our Slack conversation with VA Notify](https://dsva.slack.com/archives/C010R6AUPHT/p1628105158007200), Platform Analytics & Insights is in between data engineers right now to fully support this work. 

However, our team will be doing some technical discovery to determine if we have the sufficient internal infrastructure to support this data pull until then. We'll be in touch as we learn more!

CC: @bsmartin-ep @bevnobev

**Comment by bsmartin-ep** [comment]
Hi @LindaLi123 -

Pardon me if these question have been answered already, but I'm just joining this ticket.

First, I do want to acknowledge that we do have some sort of VANotify events being tracked in GA:

![image](https://user-images.githubusercontent.com/62304138/129271028-abe87ba0-d345-4018-8b7a-3612471d9c7b.png)

[:bar_chart:  LINK TO THESE EVENTS](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:email/)

If you filter events with a category of "email", you will see these.  It looks like the Event action can be _open_, _completed_ or _failed_.  The Event label looks to be the campaign name.  Based on the data I'm seeing, I am guessing these are originating from the VANotify system - and not via GTM on www.va.gov.

----------------------------

Second, if we want to get VANotify data in BigQuery (and then into Domo), we would need...

1. The ability for the system to export the data to a Google Cloud Storage bucket.  (This is our preferred choice but we may be able to work around other export options).
2. The data would need to be CSV (our preference), newline JSON, or AVRO.

If we can get both of these to happen, it's pretty straightforward to code a function to ingest the data in BigQuery.

Let me know if you have any questions.

**Comment by bsmartin-ep** [comment]
Apologies @bevnobev - I think these questions are for you...
 
> Pardon me if these question have been answered already, but I'm just joining this ticket.
> 
> First, I do want to acknowledge that we do have some sort of VANotify events being tracked in GA:
> 
> ![image](https://user-images.githubusercontent.com/62304138/129271028-abe87ba0-d345-4018-8b7a-3612471d9c7b.png)
> 
> [:bar_chart:  LINK TO THESE EVENTS](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:email/)
> 
> If you filter events with a category of "email", you will see these. It looks like the Event action can be _open_, _completed_ or _failed_. The Event label looks to be the campaign name. Based on the data I'm seeing, I am guessing these are originating from the VANotify system - and not via GTM on [www.va.gov](http://www.va.gov).
> 
> Second, if we want to get VANotify data in BigQuery (and then into Domo), we would need...
> 
> 1. The ability for the system to export the data to a Google Cloud Storage bucket.  (This is our preferred choice but we may be able to work around other export options).
> 2. The data would need to be CSV (our preference), newline JSON, or AVRO.
> 
> If we can get both of these to happen, it's pretty straightforward to code a function to ingest the data in BigQuery.
> 
> Let me know if you have any questions.

**Comment by bevnobev** [comment]
Tagging my team @miabecker @ffafara-tw @philherbert

**Comment by joanneesteban** [comment]
@bevnobev Hello! The Platform Analytics team would like to follow up on the Notify data. Let us know if there's been any movement, and we can get started with pulling the data into BigQuery & Domo.

CC: @bsmartin-ep @crystalio587

**Comment by bevnobev** [comment]
Hi @joanneesteban.  We have a spike story for it that is slated for late October.  Will let you know if anything changes.

cc: @miabecker

**Comment by miabecker** [comment]
: @bsmartin-ep @crystalio587 can you help us understand how to get our data into big query from google analytics?

**Comment by bsmartin-ep** [comment]
Hey @miabecker.  You're looking to find Google Analytics events and pageviews in BigQuery?  Or setup a process to get VANotify data into BigQuery?

(cc @crystalio587)

**Comment by miabecker** [comment]
Hi Brian - looking to do the later - setup a process to get VANotify data into Big Query so that our business line folks can view it in DOMO. Thanks for the support

**Comment by miabecker** [comment]
@bsmartin-ep just checking in here do you have any instructions? I put in a ticket and they directed me back to this ticket?.

**Comment by bsmartin-ep** [comment]
Hey @miabecker -

Our normal process is to provide a Google Cloud Storage bucket to your team.  When you upload a data file (usually a CSV), we would then validate and ingest that into BigQuery.

Would that work?

(cc @crystalio587)

**Comment by LindaLi123** [comment]
CC @denisecoveyduc

**Comment by miabecker** [comment]
We are also looking for help with building a report of open email events with unique Client Ids irrespective of sessions so that the stats are more accurate.

**Comment by miabecker** [comment]
@bsmartin-ep We are working on what our tables might look like but wanted to verify that are you already pulling all of Google Analytics into Big Query? For example, we have events for Email Opens and Click Throughs in there so wondering if that is already available for the DMC Team in DOMO.

**Comment by bsmartin-ep** [comment]
@miabecker -

> We are working on what our tables might look like but wanted to verify that are you already pulling all of Google Analytics into Big Query? 

Sorry for the delay, but - yes - all data from the Production - All view is streaming unsampled into BigQuery.

**Comment by miabecker** [comment]
@bsmartin-ep how do we direct users to build reports if they want to view their data? A ticket to you? Some of the data that the DMC wants to see is already in Google Analytics.

**Comment by miabecker** [comment]
@bsmartin-ep making sure you see @ffafara-tw's questions above! Thanks!

**Comment by bsmartin-ep** [comment]
@ffafara-tw -

> Can we get some test credentials so that we can evaluate connectivity and do some spikes/exploration to see if our team would prefer that option.

Are you looking for personal credentials or a service account to insert data via the API?

> stats for each day would be replaced for 3 consecutive days (since that stats will change due to delayed delivery statuses of notifications)

Once a newer "version" of a day's stats is inserted, you would completely disregard the old stats?  What about adding a `_ROW_CREATED` or `_ROW_UPDATED` timestamp and pulling the `MAX` timestamp for each day?  Or do you need to know which "version" you are displaying?

**Comment by ffafara-tw** [comment]
Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/32755 for getting personal credentials and service account

**Comment by miabecker** [comment]
Adding data fields 
[VA Notify Data.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/7824120/VA.Notify.Data.pdf)

**Comment by denisecoveyduc** [comment]
Closing this one out all FSR analytics are being captured.
