### ISSUE TITLE
IA Request Omnichannel Enterprise, Chat link on Claims and Appeals Page

### ISSUE THREAD

**Issue by stephenjames1** [department-of-veterans-affairs/va.gov-team#28360]
## When to use this 
Once you've kicked off your work and are starting on early designs. 

## Steps to complete an IA request

- [ ] VFS Product Manager: Create this issue and provide all required information below.
- [ ] VFS IA: Completes final IA feedback/recommendation.
- [ ] VFS Product Manager: Closes issue once all IA recommendations are implemented.

## Artifacts
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
- Link to or attach prototype or mockups
- Link to or attach user/page flows
- Link to Sitewide content intake ticket 

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?

The link to the Omnichannel chat on the https://www.va.gov/claim-or-appeal-status/ page will open a pop up window to the OMC chat service, which is stored outside of VA.GOV
![Omnichannel MVP](https://user-images.githubusercontent.com/83350540/128407771-df6269b1-1a06-4556-b2eb-c796808e0137.png)

https://www.va.gov/claim-or-appeal-status/ as requested by the VEO requirements team

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?

n/a

**URL(s)** - What are your suggested URLs and why?

n/a

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  

Authenticated users should see the link to chat only on the https://www.va.gov/claim-or-appeal-status/ page

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

n/a

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?

n/a

**Comment by mnorthuis** [comment]
@stephenjames1 Thank you for submitting this, and I apologize that I was not at the design intent meeting the other day.  I did watch the recording to get up to speed and have a few bits of information for you and responses to some of the questions that came up in the meeting. Please reach out with any questions. 

**IA work**
- Given the code and experience for this lives off VA.gov and displays in a pop-up, there isn't work needed around placement within VA.gov IA (i.e. no URL needed), and there are no global navigation changes needed for this at this time. 
- The focus of the work revolves around the requested entry points, to which I have responses on below. 
- Beyond the few requested entry points (which will all be inline with content), there is no additional IA collab needed, but please feel free to reach out with any questions or let me know if things change.  

**Header link**
- I am in agreement with the feedback given regarding the header not being an option for an entry point at this time.  Given this is essentially an early MVP/beta, not visible to all users, and only intended for very few pages, we would not pursue a global header change for it at this time.  I think it will be interesting to see how this chat performs, and how it integrates with other contact options and tools on the site over time.  As it find a more permanent place in those contact options, we can, and should, revisit whether a global/omnipresent entry point is appropriate.  

**Claims and appeals status page** 
- The requested page [https://www.va.gov/claim-or-appeal-status/](https://www.va.gov/claim-or-appeal-status/) is not visible to users who are authenticated.  If a user is logged in and attempts to go to that page, they are immediately directed to the actual Claim and appeal status tool.  I have attached a screen shot of that tool below so you can get a sense of what that looks like. 
- The claims and appeals team "owns" that tool from a product standpoint, and if that is still the location for placement that your stakeholder wants, you can work with that team to determine best placement within the page content - my guess is likely within the "Need help?" section.    You can reach that team in slack channel #vsa-claims-appeals.  The PM for that team is Veronica Henry (@vhenry07), and I will make a connection for you in that channel to start discussion.  

Non-modernized page links
- In addition the page above, there were other non-modernized pages that were identified for links.  I'm not sure if that is still the plan, but I did want to provide some information regarding authentication and non-modernized pages on va.gov. 
- Those legacy pages have a copy of our header injected into their code, and  that header doesn't fully function like it does within our modernized experience.  The biggest difference, is that header does not recognize that a user is signed in or not.  I don't believe you will be able to put a link within a Team Site page that only appears for authenticated users.

**Comment by mnorthuis** [comment]
@vhenry07 I just realized that @stephenjames1 is not in Slack, so this is the only means I have to connect the 2 of you.

**Comment by vhenry07** [comment]
The "need help" section, right-hand sidebar elements are actually controlled by the sitewide content team. Tagging @RLHecht for confirmation.

**Comment by RLHecht** [comment]
@vhenry07 Since this is an authenticated page, we don't control that right rail. We would be able to access it on the static page, but there isn't one on /claim-or-appeal-status

**Comment by Mottie** [comment]
My apologies, I incorrectly told @vhenry07 that we don't own the right side-bar. We do. @mnorthuis Please let us know what needs to be added.

**Comment by vhenry07** [comment]
@mnorthuis We can make the change but do you think this needs to go through a staging review first?

**Comment by mnorthuis** [comment]
@vhenry07 @Mottie Please work with directly with @stephenjames1 on this work to define placement and link label for this.  I'm going to close this ticket since there isn't any additional IA work that needs to be done.  @stephenjames1 please reach out to me if you have any questions or determine there are additional areas that you want to create an entry point to the chat.  Thank you!
