### ISSUE TITLE
[Design] Notification Prefs: Share revised designs with partners

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28369]
Share revised designs with VA Profile and VA Notify teams 

**Tasks**
- [ ] Share with VA Profile 
- [x] Share with VA Notify

**Comment by andaleliz** [comment]
Shared mock-ups with [VA Notify](https://dsva.slack.com/archives/C010R6AUPHT/p1629209392036000) via Slack, and emailed Michael Richard link to new mock-ups.
