### ISSUE TITLE
[Design] Notification Prefs: Update FE documentation per new designs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28370]
## Backstory
With the changes in design, we need to make sure our [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/README.md) is up to date.

## Tasks
- [ ] Update FE documentation

**Comment by andaleliz** [comment]
@erikphansen and @tmitchellgcio  - would it be helpful/necessary for me to put together documentation like this, since it's a new variation?
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/2fd2df27-4cff-4fd7-889d-160afbdf9bff)

If so, what level of detail is most helpful?

**Comment by tmitchellgcio** [comment]
I think it would be helpful in my opinion. The level of detail here is good for me I believe

**Comment by andaleliz** [comment]
I've updated the docs but will wait to see the outcome of our meeting on 8/13 before I let FE know they are officially ready to rock.

**Comment by erikphansen** [comment]
@andaleliz Taylor was already plowing away last week and there is actually a PR up that gets us about 80% there. But I'll hold off on actually switching the notification settings page to use the new radio buttons in place of the checkboxes until Friday.

**Comment by andaleliz** [comment]
@tmitchellgcio and @erikphansen [the FE docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/README.md) are good to go!
