### ISSUE TITLE
Patient Cell Number Changes - Unable to Opt-Out

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#28371]
Station 657A4 cannot opt-out a patient. Searching for the patient by name in the patient lookup tool, the patient's phone number shows an incorrect cell number and already opted out, however, sometimes it will show the correct number and opted-in. I have sent an examples in an email due to PHI. Andy looked up the incorrect cell number that displays and could not find it in the database.

**Comment by Kennon-git** [comment]
enable patients to opt out by patient icn.
