### ISSUE TITLE
Community care provider selection sort dropdown

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#28373]
## Description
Update provider list sort toggle from address/location links to dropdown.

---

## Acceptance Criteria
Background: the `va_online_scheduling_cc_iterations` toggle is on

Given user is in CC flow
And there is no provider selected
When the user opens the provider preference page
Then the provider question content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-provider-preference.md#iterations-toggle)
And the provider question design matches the design spec and templates

Given a user is in the CC flow
And the user has a home address on file
And the user is on the provider preference page
When user selects Choose a provider
Then the list sort options are home address and current location
And the default sort is home address
And the copy and design match the copy and design docs

Given a user is in the CC flow
And the user is on the provider preference page
And the provider list is expanded
When the user changes the sort method
Then order of providers in list is updated to the new sort method

Given a user is in the CC flow
And the user is on the provider preference page
And the provider list is expanded
And the user changed the sort method to current location
When the browser fails to get the current location
Then show location blocked and retry message

### Design Assets
All spec copy is FPO. Use copy in copy doc.
- [Overview - dropdown](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/EL98PER#Inspector)
- [Dropdown sorting selector states](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/QbrLaqY)
- [Mobile spec](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/Kvwjd8g#Inspector)
- [Tablet spec](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/v/akdEVZ/a/wLMWGYq/r/ovlW73#Inspector)
- [Desktop spec](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/v/akdEVZ/a/qe5Wzy2/r/ovlW73#Inspector)

### Out of Scope
Copy changes on the language preference page are out of scope for this ticket and will be handled separately.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md) is updated

**Comment by laurenernest** [comment]
@LeKeve What's the parent site reference address used when calculating the distance of the providers? I can't tell if it's a Staging data issue, but Aurora is actually ~100 miles from Cheyenne.

I used Judy & Optometry to get that result.

![Screen Shot 2021-09-03 at 12.16.24 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/9a2dc7c7-fadb-4306-8175-40e0afa4bad3)

**Comment by LeKeve** [comment]
@laurenernest I think this is an issue with the lat/long coordinates in our mock data.

The coordinates for Cheyenne VA Medical Center in our mocks are currently set to the following, lat: 39.744507, long: -104.830956 which is Aurora, CO. I'll update those coordinates in our mocks.

Dayton, OH coordinates look good though, so it should show the correct providers closest to that facility.

**Comment by aarathi-poldass** [comment]
Steps to reproduce:
Scenario 1: If user has home address in profile, then sort options include: home address, current location, parent site city/state
1)	Login to VAOS as cecil.morgan@id.me
2)	Select Primary care and follow steps to enter a cc request 
3)	Validate the sort options include 
i)	Your home address 
ii)	Your current location 
iii)	Parent site city/state
4)	Your home address is set as default 
Scenario 2: If user has no home address in profile, then sort options include: current location, parent site city/state
1)	Login to VAOS as grethel.g.petryniec@id.me
2)	Select Eye care (Optometry) and follow steps to enter a cc request 
3)	Validate the sort options include 
i)	Parent site city/state
ii)	Your current location 
4)	Parent site city/state is set as default and the profile get original manual preference version

Validated and everything is working as expected.
