### ISSUE TITLE
Upgrade jsonschema-form to v7

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#28374]
## Details
We are currently using v4.5 of `ajv` in the `vets-json-schema` repo. Some teams are having issues using v4 with the version that Lighthouse is using, which is v7. We'll want to upgrade to v7 to resolve any conflicts with Lighthouse.

More context: https://dsva.slack.com/archives/CBU0KDSB1/p1628188296150700

**Comment by timwright12** [comment]
Noting that there are errors in yarn test with any major upgrade to this package. Tested with 5.5.2, 6.12.5, 7.2.4, and latest 8.6.2.

With this in mind, we should probably just bring it all the way up to current/latest: https://www.npmjs.com/package/ajv

**Comment by CBonade** [comment]
Closing as stale.
