### ISSUE TITLE
[Design] CC prefs - breakout question and update language

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#28379]

**Comment by outerpress** [comment]
## Goals
Clarify the cc provider preferences questions

## Background
The CC provider selection page is getting more complex. This work breaks the "closest city/state" question off of that page to help Veterans focus on one question at a time.

It also adjusts the language on each of the preferences pages to clarify the intent of each of those questions.

## Design assets
- [ ] [Workflow/Overview](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/g057rRM#Inspector)

Specs (TBA)
- [ ] Mobile
- [ ] Tablet
- [ ] Desktop

**Comment by peggygannon** [comment]
Hi, @outerpress Here is my content recommendation for these screens. 

I have a question: For screen 1, will the list of options always be a city? If so, I recommend condensing the H1 to just say "city", as I don't think "state" is needed here. Let me know your thoughts! 

screen 1
**What's the closest city to you?** (Required)
{city, state radio button options}


screen 2
**Request a [type of care] provider** (Optional)
We'll call you to confirm your provider choice or to help you choose a provider if you skip this step. 

screen 3
**Choose a preferred language**(Required)

Select your language preference for your community care provider.

**Comment by outerpress** [comment]
Thanks @peggygannon ! Updated the sketch file with these recs so we could take a look. Just a couple of notes:

Screen 1
* Removing the word state makes sense! I'll confirm, but I think you're right that the options are always a city. I also removed it from the text below the header (see my next bullet)
* Are you recommending removing the text below the header? I would love to do this but we need  to put something there as the form system requires some kind of label over the question and we can't use the page header (yet..)

General
* Are you recommending we remove the asterisk from the (Required) notation? If so, we should do this across VAOS to be consistent, as a separate effort.

**Comment by peggygannon** [comment]
@outerpress Hello! Here is a line of content for screen 1

Also, regarding the * for required and optional. I would like to remove them too, as the asterisks don't refer to anything. I believe  this is part of a design system component. I think this would need to be reviewed/addressed as design system council before removing. 

**What's the closest city to you?**
Choose a city that is near you. This ensures that we send your community care request to your closest VA health system. (*Required)

**Comment by outerpress** [comment]
Thanks! Looks great, I updated the mocks.

We'll save tweaks for the required marks for another day. 

@laurenernest these should be gtg, I added m/t/d specs for the three pages to this ticket.

**Comment by laurenernest** [comment]
Moving to Product to update copy docs and dev ticket

**Comment by laurenernest** [comment]
Updated tickets and copy docs:

[Closest city](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-closest-city.md)
[Request provider](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-provider-preference.md)
[Language preference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-preferred-language.md)

**Comment by outerpress** [comment]
Design work done, closing
