### ISSUE TITLE
Update Lighthouse Report with Metrics from Analytics Data

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#28383]
The current implementation of collecting daily lighthouse data is just using the default mobile options:

**Device**: Emulated Moto G4
**Network throttling**: 150 ms TCP RTT, 1,638.4 Kbps throughput (Simulated)
**CPU throttling**: 4x slowdown (Simulated)

Connect with the analytics team about which browser/device/viewport size metric we should use to capture the largest audience possible. Also get the top 5 pages on the site. If mobile is our top device, use that, if it's desktop, use that.

Current lighthouse report: https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/lighthouse/homepage.html

**Definition of Done:**
- [] Add the rest of the top 5 sites into the test suite and publish the reports to the S3 bucket (JSON and HTML)
- [] Ligthhouse reports are updated with new metrics

**Comment by jhonnyoddball** [comment]
Expired. Closing
