### ISSUE TITLE
[Ongoing Service] - Assist teams with QA effort

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2838]
## User Story

As a team without a dedicated QA resource, I want someone I can turn to to do QA on our features so that they don't go to production without being fully tested.

## VSP Objective (Q1 & Q2 2020)
O1- delightful, self-service, end-to-end

## Measuring Success (KRs/KPIs)

% customers meeeting QA standards
Customer NPS

## Details and Notes

During onboarding we will identify teams without a QA resource and have them use Peter Hill to perform their QA needs and make sure it is up to VSP’s QA standards. 

### Goal(s)

Engage with teams and perform their QA needs when that team does not have a dedicated resource. 

### Assumptions and Hypotheses

We **hypothesize** that  **if** If we offer a QA service where a QA person can step in and test a new feature for a team without a dedicated QA person **then** we will have better code going to production and more stabil features.

**Comment by shiragoodman** [comment]
@andreahewitt-odd @pjhill is this epic still in use? Can we close it?
