### ISSUE TITLE
Update lighthouse scan to include all applications

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#28386]
The current lighthouse implementation only scans a subset of the pages and applications. Let's see if we can use the application registry to generate a report for each application. If we can't use the registry, what can we use?

We can use this data down the line to assemble an app-specific dashboard.

**Definition of Done**
- [] Published reports cover all applications in vets-website (as well as the top 5 pages, if they aren't apps)

**Comment by timwright12** [comment]
Resource for later: https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/server.md

**Comment by oseasmoran73** [comment]
Closing ticket as PR has been recently merged

**Comment by oseasmoran73** [comment]
Reopening ticket to address so flakiness if possible

**Comment by oseasmoran73** [comment]
Upon investigating, there is not much within the CI that can be done to reduce the flakiness. May need to be via another action. Closing ticket
