### ISSUE TITLE
Create a lighthouse performance budget recommendation for Static Pages

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#28388]
Static pages are all kind of the same so we can create a single performance budget.

**Information on creating performance budgets in lighthouse**

- [Performance Budgets](https://github.com/GoogleChrome/lighthouse/blob/master/docs/performance-budgets.md)
- [Use Lighthouse for Performance Budgets](https://web.dev/use-lighthouse-for-performance-budgets)
- [Performance Budgets with Lighthouse](https://www.afasterweb.com/2020/01/28/performance-budgets-with-lighthouse)

**Definition of Done:**
- [ ] Create a general performance budget for the top 5 static pages on the site
- [ ] Install the performance budget into lighthouse for only the static page runs (if we need a different workflow just for static pages, that's fine)
- [ ] Confirm lighthouse runs against the budget and reports any pages violating the budget into slack (with the offending data)

**Comment by jhonnyoddball** [comment]
Expired. Closing
