### ISSUE TITLE
Move Lighthouse reporting to new public repository

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#28384]
The Lighthouse Github actions are currently housed within vets-website. There's no real reason for them to be there since we're running tests against the live website. The code it just bloating the repo.

Create a new repo for "Lighthouse reporting", reach out to OCTODE to submit a request to make the repo public. Migrate lighthouse work into that repo and confirm that it all still works.

**Definition of Done**
- [] New public rep created
- [] Workflow removed from vets-website
- [] Workflow added to the new repo
- [] Reports publishing to the same S3 location

**Comment by jhonnyoddball** [comment]
Expired. Closing
