### ISSUE TITLE
Remove all references to VHA PDF from VA.gov Playbook

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#28387]
**Background:** 
This old old old site from Vets.gov days still exists: https://www.va.gov/playbook/. A very future topic for the Platform to consider will be whether we cut, transform, or keep the site. But right now, a Stakeholder in the Health space noticed that the site links to an old PDF (https://www.va.gov/playbook/downloads/VHA_Style_Guide_508.pdf) which is a VHA style guide that was retired back in 2016. For goodwill building reasons, we need to prioritize taking care of that. I'm hoping it won't be more than a few hours of work at most to hunt down the source code, and find and remove all references to that doc.

**Task:**
- Remove https://www.va.gov/playbook/downloads/VHA_Style_Guide_508.pdf and any links or references to it from the va.gov/playbook site.
- Communicate in this ticket (and ping Rachael if you need an OCTO-DE decision) if there are questions around what "removal" looks like. I'm not sure if it'll, for example, leave a sentence hanging to just delete the linked text, or something like that (which would actually be fine, since this is not a site we're actively trying to maintain.)
- Let Rachael Roueche know in Slack if it's taking more than a few hours to complete, so we can re-evaluate whether to continue doing this.
- Once complete, let Rachael Roueche know in Slack so she can communicate to the appropriate Stakeholders

Thanks!

**Comment by f1337** [comment]
I suspect it’s not in the code, but in the  CMS. I searched our entire org on GitHub, and the only results are two outdated docs, one of which has been updated, the other is just a top 50 URLs report from long ago:

https://github.com/search?q=org%3Adepartment-of-veterans-affairs+VHA_Style_Guide_508&type=code

**Comment by f1337** [comment]
Also, Google is coming up empty, even when searching *all* of va.gov: https://www.google.com/search?q=site%3Awww.va.gov+VHA_Style_Guide&hl=en&biw=1600&bih=911&ei=fkENYc2iJ9m6tAaR2rwQ&oq=site%3Awww.va.gov+VHA_Style_Guide&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVDBMFjPVmDrWGgCcAB4AIABa4gBuQiSAQQxOC4xmAEAoAEBwAEB&sclient=gws-wiz-serp&ved=0ahUKEwjN2fqkyJzyAhVZHc0KHREtDwIQ4dUDCA0&uact=5

**Comment by rroueche** [comment]
@f1337 could it be this repo? https://github.com/department-of-veterans-affairs/playbook

**Comment by f1337** [comment]
I think they've already been scrubbed: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+VHA_Style_Guide&type=commits

**Comment by indytechcook** [comment]
Data most likely comes from https://github.com/department-of-veterans-affairs/vagov-content/tree/master/pages/playbook

**Comment by indytechcook** [comment]
The PDF files for the playbook are here: https://github.com/department-of-veterans-affairs/vagov-content/tree/master/assets/playbook/downloads including the PDF: https://github.com/department-of-veterans-affairs/vagov-content/blob/master/assets/playbook/downloads/VHA_Style_Guide_508.pdf

**Comment by rroueche** [comment]
Thanks @indytechcook ! Do you have access to remove? And do you know where on the public-facing site the file appears to end-users?

**Comment by indytechcook** [comment]
@rroueche I can remove it.  I'll have to look into where it's used. An initial scan of the build files on my local doesn't show any usage but I can dig deeper.

**Comment by indytechcook** [comment]
PR to remove file: https://github.com/department-of-veterans-affairs/vagov-content/pull/789

**Comment by indytechcook** [comment]
I haven't found any links to the file, I'm asking other engineers to looks also.

**Comment by indytechcook** [comment]
PR has been merged and the PDF file is no longer live.  There are no none links to this file:

```
find . -type f -print0 | xargs -0 grep "VHA_Style_Guide_508.pdf"
```

return no results from within the HTML of the content-build.

**Comment by rroueche** [comment]
Stakeholders have been notified of the update, and have confirmed they're no longer seeing the PDF. Thanks for the great work everyone!
