### ISSUE TITLE
Appointment time on Review page does not match selected time from Calendar Page 

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#28393]
## Summary
When VAOS service appointments feature toggle is on, the appointment time selected for direct schedule on calendar page does not match the appointment time displayed on the Review page

## Specs
- Device: Mac OS
- Browser: Chrome

## Steps to Reproduce
**Test User:** 

1. VAOS service appointments feature toggle is turned on
2. Make a direct schedule for Primary care at Cheyanne VA Medical Center, Green Team Clinic 1
3. Select September 1st 9:15am on the Calendar page
4. Continue with the direct schedule flow until the Review page

### Actual Result
Appointment time on Review page does not match selected time from Calendar Page 

![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/db923ec0-f886-454c-a0b4-adf1dcc3006f)

![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/b03d299c-9f5a-4298-be49-0e6053c975aa)

### Desired Result
Appointment time on Review page matches selected time from Calendar Page

## Definition of Done
- [ ] Appointment time on Review page matches selected time from Calendar Page
- [ ] Correct Time zone to be displayed

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by laurenernest** [comment]
unable to validate in staging
