### ISSUE TITLE
Campaign landing page template - 1st Round content & design

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2839]
## Create a campaign landing page template for VA content authors to help  better communicate relevant and helpful information on the web. 

**Generic use cases:**
Primary business use will be to drive traffic to a CLP via email/social media or other public affairs ("engagement") type of communications. In some cases, the audience will be Veterans/benefit users. In other cases, the audience may be non-Veterans (members of the media, Congress, etc.). 

**Content design goals:**
- Help create guardrails in the content design, so that the page content is findable on organic search; directs traffic to benefit hubs or tools; and doesn't duplicate benefit hub tier 1 content. 
- Enable content authors to curate existing VA content on a page and link people to relevant existing content on VA.gov. 
- Ensure that CLP content drives traffic to relevant tier 1 benefit information or tools, AND does not dilute, distract, and clutter Veteran-facing benefit product UX (benefit hubs). 

**Content & design requirements:**
A consistent 'rigid' location for primary CTA button/s to  benefit hub page or tool 
Default analytics - click events, downloads, plays, etc.
Follows semantic order of H1-2-3s.
Follows/reuses existing components already in Drupal
Allows:
- Text
- Text links
- Videos
- Image files
- PDFs
- Email sign-ups
- Social media sharing

**Super rough sketch of example attached - for discussion and not to be taken literally:**

![campaign-lp-whiteboard](https://user-images.githubusercontent.com/43381063/67781786-4390f300-fa3e-11e9-9553-81f4df780d69.png)

**Comment by andaleliz** [comment]
Hello @kevwalsh!  As part of the work Laura and I are working on this issue, it'd be really helpful to get a list of content components users have available to them in Drupal.  For example, the options a user is presented with in the modal if the user is on a Benefits Detail Page, and clicks `Add Content Block` under the **Main Content** section.  We understand you work with Drupal and are wondering if that's something you can help with?  

It seems that those options might change based on the template the user picks - we're interested to know what the options are across templates.   Thanks in advance for any help you can provide.

**Comment by andaleliz** [comment]
Attaching Q&A matrix from meetings w/ Jen last week. 
[Questions for issue #2839 (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3806023/Questions.for.issue.2839.1.xlsx)

**Comment by kevwalsh** [comment]
Sorry I missed that ping on that issue! I'm ooo today but happy to hop on a call tomorrow if you like. The benefits hub detail pages are indeed the best place to get a sense of the menu of content  components available to editors. Particularly the Main Content section

**Comment by kevwalsh** [comment]
There are other components you should know about though...

**Comment by kevwalsh** [comment]
And unfortunately not all of them have made their way back into the design system

**Comment by andaleliz** [comment]
@kevwalsh It looked like the options under main content were plentiful, but as you mentioned, we were told there are other components out there and not all in the design system.  Hence the ask for a comprehensive list...is there a db query or something we can run to even get a list as a starting point?

**Comment by Karak888** [comment]
@andaleliz I think we should just move forward just getting out intitial wireframe and we can circle back on Drupal.  Main thing is to get the MVP moving forward.... @jenniferlee-dsva please let us know your thoughts here.  Thanks!

**Comment by andaleliz** [comment]
@Karak888 This isn't blocking Laura or me.  But we will need this information as we go further down the road, so would like to continue to try to get it as we go along.

**Comment by andaleliz** [comment]
@Karak888  Here's the link to wireframes you requested - very much a work in progress and will evolve today: https://vsateams.invisionapp.com/share/PHUPD25QV9J

@jenniferlee-dsva Laura and I should be at a point to go over these with you before the week is through. Will send a message on Slack to coordinate a time for the three of us to review.

**Comment by Karak888** [comment]
Thanks @andaleliz!

**Comment by Karak888** [comment]
@lwalsh617 @andaleliz @jenniferlee-dsva to schedule time to chat with all 3 and go over revisions.

**Comment by Karak888** [comment]
@andaleliz  @lwalsh617 - I know Liz and I discussed breaking this ticket down into tasks that can be created over a 2 week sprint, but from your conversations with @jenniferlee-dsva, if either of you have any ideas or tasks that emerged, I would love to get a start on breaking this down into trackable pieces.  Thanks!

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @andaleliz Here's what I heard on our call and what next steps I'm taking. Please give a shout with any clarifications. Thanks!!
[Campaign LP next steps.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3859796/Campaign.LP.next.steps.docx)

**Comment by andaleliz** [comment]
@lwalsh617 The only additions I can think of are the video guidelines from Jen:

> Let's use a rigid  TOPIC SUPERHEAD for videos too because many video titles will be either super crazy long or super non-sensical.
> I think we also need to allow a short blurb to go with videos, to give context to users. I'd love it if we could also indicate length of video -- like Watch [name of video] 1:03 mins -- or something

I updated the prototype w/ my best interpretation but def needs some content finessing

**Comment by Karak888** [comment]
@lwalsh617 @andaleliz I just renamed the title of this in order to track work done on this and shown in sprint demo.  Will create second ticket for remaining work.

**Comment by jenniferlee-dsva** [comment]
Thank you @lwalsh617 and @andaleliz  for this amazing MVP 1.0! 

@Karak888 -- we'll do a DEPO/DSVA on this to turbo charge it to the finish line.

**Comment by lwalsh617** [comment]
Posting content deck. 
[Campaign LP Template_Placeholder copy v3_11-20-19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3870128/Campaign.LP.Template_Placeholder.copy.v3_11-20-19.docx)
