### ISSUE TITLE
[Build] Programmatically Populate the Google Analytics fields in the Education Analytics MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#284]
## User Story
As a Product Owner, I need proactive/automatic, regular, and easy to consume updates on my data so I can use data regularly as part of my workflow.

## Goal
Product owners and teams should receive weekly/monthly analytics dashboards without a heavy weekly lift by the analytics team.

## Acceptance Criteria
- [x] Google Analytics (Goal Conversion and Event Tracking) automatically pulls to Product Health Prototype
- [x] Data reviewed by and shared with team

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with `analytics-insights`**
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Resources
https://github.com/department-of-veterans-affairs/va.gov-team/issues/185
[Product Health Prototype](https://docs.google.com/spreadsheets/d/1go-gIeGXb_W-XdJzW3xLT__UUspXX5hwfY2K0ovqkTo/edit#gid=1824671595)
[Data Gathering Example](https://docs.google.com/spreadsheets/d/1mbEF0ksGPz_0pwG7L38cjo_v1YeeMoF_Tg64ht2LFm0/edit#gid=0)
[Vets/VA Metrics Automation example](https://script.google.com/a/adhocteam.us/d/19O_-27JeC1Syna9fLLfoXNP37zLednwufJH8iu15tmO9EkqGi4zylWSP/edit?usp=sharing_eip&ts=5cc87b28)
[Vets/VA Metrics Automation Prod example](https://script.google.com/a/adhocteam.us/d/1QD0jK62NXaa9Cj0hqSP8CLvlg-iUdW_uns0_ra6Rem1XVeNRW381vEui/edit?usp=sharing_eip&ts=5ccb4891)

**Comment by joanneesteban** [comment]
2 Potential Methods:
- Google Sheets API - Plugin (Pulls directly from GA)
- Copy Script around how the vets/va.gov metrics sheet pulls

**Comment by joanneesteban** [comment]
@nedierecel will discover what is effective to pull on Google Sheets API - Plugin.

@jonwehausen will discover if he can use Google Script (resources in User Story) to pull Google Analytics data points into most recent [MVP Iteration](https://docs.google.com/spreadsheets/d/18CeQzeOxTwZ7Q1007ZUHgV12EtrjHawmgiVbsUtL8wY/edit#gid=786826286). Jon, please make a copy while you are in discovery.

**Comment by jonwehausen** [comment]
[Here](https://docs.google.com/spreadsheets/d/1dN8U-argfp_fG_zR_G0uU4Tkb-Y-nRT6UA7cMqs_tRk/edit?usp=sharing) you guys can find my working copy of the Product Health MVP. 

**Latest Status:**

- Most fields are leveraging their GA datapoint where possible. 
- The 'Funnel Conversion' column is not exposed thru the API so I am manually calculating using the formula
`Goal Completions / Goal Starts`
That said, the percentage calculated is slightly off from what's displayed at the bottom of GA [here](https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184624291/_u.date00=20190601&_u.date01=20190630&_.goalOption=6/). Potential solution is to setup a calculated metric within GA and pull in via the API.

**Comment by nedierecel** [comment]
@jonwehausen From our discussion:
1) Funnel completion rate - I believe the timeframe is different in GA 
2) Data Source - Because we ran into a goal limitation on the `WBC View`, the remaining goals can be taken from the `Education Modernized View`(View ID `184334251`). Moving forward, we can pull from their respective product views.

**Comment by joanneesteban** [comment]
@jonwehausen we will need multiple tabs (so we have week by week data). Will schedule a discussion for 7/19/19.

**Comment by joanneesteban** [comment]
Jon successfully tested and ran the data for the Education MVP.
