### ISSUE TITLE
[BUG] Yellow Ribbon - Words "Search Criteria" appear twice after searching

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#28403]
## What happened?

After searching the words "search criteria" appears twice in the left rail.

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/7add36d2-ea53-480b-94da-fabcff564f33)_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zacharymorel** [comment]
This can be closed: 

![Screen Shot 2021-08-17 at 3 43 17 PM](https://user-images.githubusercontent.com/26075258/129790181-8f449de0-d36d-4815-9b73-3027568c8b45.png)
