### ISSUE TITLE
Identify pilot or test for integrating emoji's into experimental design tickets

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#28409]
This request originated from the DSC meeting on 8/6. Shawna had raised the question "Ddo we want to add a feature to allow Up Voting?"

The DSC has asked the DST to identify how we might integrate emojis into responses or comments for experimental designs. 

This idea should be tested or a pilot to see if it is successful. If it is, then we should add to issues. 

Reassign to Natalie Hill once she is onboard.

**Comment by caw310** [comment]
Write up instructions for upvoting to experimental designs in GitHub issue or comment.

**Comment by humancompanion-usds** [comment]
@sshein - Two bits of progress on this as we try to push this idea forward this sprint:

1. We created a board for tracking requests that come to DSC and requests for new components & patterns: https://github.com/orgs/department-of-veterans-affairs/projects/730/views/2
2. I did discover github allows you to sort by reaction:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-desc

Unfortunately, you cannot view the reactions on a board or even in the results returned by that issues query. You have to click thru to each issue. Also, it's all reactions, not just up votes. I think there are a few potential paths forward here:

A. We encourage folks to up-vote issues they care about and periodically the DST will sort the repo and look for the issues with the most reactions and take that into account as we prioritize sprint planning.
B. We periodically invite teams to a session where the DST preps a short-list of new, or update, pattern and component proposals and drops them with links into Mural (I'm thinking no more than 10 at a time). We give folks time to read through the issues, discuss them, then vote in Mural. We use that to prioritize the [Proposals (New or updates) column in the board](https://github.com/orgs/department-of-veterans-affairs/projects/730/views/1).
C. We continue to prioritize this new board in DSC meetings and rely on the Council members to know the current temperature of what is desired by teams (with perhaps some warning of when we're going to do this so they can check-in with folks).

C is kinda the status quo though we have recently resurrected the Governance Kanban Board and plan to maintain it. It's the least work for the DST but is not direct feedback from Teams. That said, we kinda have enough prioritize work with DSC requests and other initiatives to keep us quite busy for quite some time. 

B is a reasonable amount of effort for the DST to take on but "periodically" here might be only once a quarter. A is also doable but the most nebulous in that we don't communicate directly with either Teams nor the DSC.

Any preference? Other ideas?

**Comment by sshein** [comment]
cool thanks Matt. I think I prefer Option B - but where we also leave space for teams to bring up new things and file tickets because I bet a bunch of people have thoughts that they haven't bothered to capture in tickets because they don't know about the process or just don't bother. I think using a Monday meeting once a quarter seems about right? And we could accompany it with an async way for folks to add things in the #design channel, maybe just a simple slack thread.

**Comment by humancompanion-usds** [comment]
Workshop scheduled for Monday 8/8/2022.
