### ISSUE TITLE
[FE] Profile: Implement revised design for clarifying contact email vs sign-in email

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28425]
## Background
As outlined in #26950 Veterans were confused by the contact email address section of profile during the notifications settings study. We have a revised design and copy to help reduce this confusion, which can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/clarify-email-addresses-specs.md)

## Tasks
- [x] Implement updated design and copy as outlined in the documentation linked above.

**Comment by tmitchellgcio** [comment]
@ajakabcin ready for validation.

**Comment by ajakabcin** [comment]
Confirmed on staging thanks @tmitchellgcio! Closing
