### ISSUE TITLE
Remove 'nutrition' from CC eligible care types; remove 'podiatry' from VAOS

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2842]
Nutrition and Podiatry should not be eligible for Community Care at this time. Additionally, 'podiatry' is not supported for online scheduling at the VA at all. We need to remove them from the respective lists so that they don't trigger the VA / CC Choice page or let veterans pick an option that isn't available.

AC
- [ ] Clicking on nutrition does not give veteran CC option
- [ ] VAOS does not include a podiatry option in the type of care list

**Comment by lalexanderson-dsva** [comment]
To be clear, nutrition should still show in the type of care list, because it can be booked for VA appointments, but it will not be eligible for cc drive time eligibility.

**Comment by markgreenburg** [comment]
@vbahinwillit after multiple meetings with stakeholders, we will want to hold off on this change. Sorry this has gone back-and-forth so much. The new logic is:
- Podiatry should only be available for Community Care (in another ticket, we will add content to the podiatry option on the type of care page to make it more obvious that it should only be selected when a veteran suspects they are CC eligible).
- Nutrition is back to being available for CC as well as VA care.

In a separate ticket, we will add a follow-up page for veterans who selected podiatry but are not eligible for CC - nothing to worry about in this ticket.
