### ISSUE TITLE
Complete UXPin Prototype

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28421]
##  Description
Create prototype to be used during usability study. This includes 6 prototypes in total both mobile and desktop versions for 3 different tasks aligned to the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-plan.md).

## Background 
- [Research Plan: Search Design Concepts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-plan.md)
-  #26814

## Acceptance Criteria
- [x] Continue working on prototypes to finalize ahead of team QA
- [x] Create GH pages to host task links (one for mobile, one for desktop)
- [x] Create bit.ly link shortcuts (one for mobile, one for desktop)

**Comment by denisecoveyduc** [comment]
@mgleo can you add an estimate to this one and ensure that the description reflects the work remaining for the prototype? Thank you!

**Comment by mgleo** [comment]
Link to Desktop prototypes: https://bit.ly/tasks-d
Link to Mobile prototypes: https://bit.ly/tasks-m

Task one - Find a Form
Task two - Find a VA location
Task three - Resources and support
