### ISSUE TITLE
HCE Phase 2 Checkin - Last4/LastName & Multiple Appointments 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#28429]
This super-epic will contain all items related to the first iteration post-MVP. The following two enhancements are being added:

* Adding Last 4 SSN and Last Name for identity verification. 
* Ability to show multiple appointments.

**Comment by julieadair1** [comment]
It looks like all stories in this epic have been closed so I'm closing this epic. 
cc: @jparker0425
