### ISSUE TITLE
Facility address is merged into appointment list request in vets-api

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#28432]
Currently when vets-website displays an appointment list it must make an additional call to retrieve the facility address. 

As part of the implementation of the new VAOS service, vets-api will be taking over that additional call on the back-end and merging the facility address into the response object returned to vets-website, allowing vets-website to make a single call to retrieve the necessary appointment list data.

The facility address is present for each appointment returned to vets-website when booked appointments are requested
The facility address is present for each appointment returned to vets-website when past appointments are requested
This feature can be toggled via the include query parameter, please see https://www.hl7.org/fhir/search.html#include for reference.

**Comment by laurenernest** [comment]
@LeKeve Can you confirm if any other FE changes are needed to use the address from this updated response instead of the additional call, or was that work done first?

**Comment by LeKeve** [comment]
We still make that second call to fetch facility data so FE changes are needed. I can create a ticket for our end of the work.

@grossb1 Am I correct in understanding that the work done in vets-api will add the facility address to each appointment object returned from `/vaos/v2/appointments/`? We don't need to add an extra query param to our call?

**Comment by laurenernest** [comment]
@LeKeve Thanks for confirming. Please write up the FE ticket and we can groom next week.
