### ISSUE TITLE
Harassment Reporting Tool [Mobile Screens Mockup]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28434]
## Issue Description
_ORDMI PIFs have never actually produced any design mockups for the harassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled.  We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems.  The designs will be used for both design intent review and initial FE build of the prototype_

[Draft Design Sketch Review](https://www.sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

[Link to Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26765) 
## Design tasks
- Create MOBILE design mockups (in support of user research)
- Validate designs are in sync with desktop look and feel

## Acceptance Criteria
- [ ] Designer comments on this issue to approve mobile designs
- [ ] Designer posts link to Prototype for review by PIF/PM/PO
- [ ] Feedback is documented on ticket for follow up and review

**Comment by callen2563** [comment]
Mobile first drafts have been mocked up but will be continuing edits during collaboration with content.

[HRT mobile and desktop designs](https://sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

**Comment by brianalloyd** [comment]
Mobile designs are completed, closing ticket in support.
