### ISSUE TITLE
Intake: Disaster Response

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#28441]
Hello Dr. Hubert, 

Approved – Ready for VEText Development Backlog

 

From: Williams, Erica <Erica.Williams@va.gov> 
Sent: Thursday, July 29, 2021 8:03 AM
To: Lowe, Jeffrey T. <Jeffrey.Lowe2@va.gov>
Cc: Jenkins, Florence A. <Florence.Jenkins@va.gov>; Wilt, Angie R. <Angela.Wilt@va.gov>
Subject: FW: VEText Capability Requirements for Vulnerable Patients

Good Morning, 

This request is to send Emergency Notification VEText messages to a select cohort of patients as deemed necessary.

.  

From: Hubert, Terrence L. <Terrence.Hubert@va.gov> 
Sent: Thursday, July 29, 2021 7:47 AM
To: Williams, Erica <Erica.Williams@va.gov>
Cc: Elliott, Shane M <shane.elliott@va.gov>; VHA 15HOC Healthcare Ops Ctr Monitoring and Evaluation Team <VHA15HOCHealthcareOpsCtrME@va.gov>; Brewster, Peter <Peter.Brewster2@va.gov>; Holmes, Chad E. <Chad.Holmes@va.gov>; Dingman, Scot C. VHAREN <Scot.Dingman@va.gov>
Subject: VEText Capability Requirements for Vulnerable Patients

Erica,  please see attached.  Happy to discuss further as needed.

Thank you,

Terry

Terrence Hubert, Ph.D.

Heathcare Operations Center (15HOC)
Veterans Health Administration
Office 412-215-2282
terrence.hubert@va.gov

From: Elliott, Shane M <shane.elliott@va.gov> 
Sent: Tuesday, July 27, 2021 6:28 PM
To: Hubert, Terrence L. <Terrence.Hubert@va.gov>
Subject: RE: VEText Capability Requirements for Vulnerable Patients - NEW TIME

Looks good.  You would need to forward to Williams, Erica <Erica.Williams@va.gov>

Shane

From: Hubert, Terrence L. <Terrence.Hubert@va.gov> 
Sent: Tuesday, July 27, 2021 4:02 AM
To: Elliott, Shane M <shane.elliott@va.gov>
Cc: Holmes, Chad E. <Chad.Holmes@va.gov>; Brewster, Peter <Peter.Brewster2@va.gov>
Subject: RE: VEText Capability Requirements for Vulnerable Patients - NEW TIME

Attached correct version this time

From: Hubert, Terrence L. 
Sent: Tuesday, July 27, 2021 6:57 AM
To: Elliott, Shane M <shane.elliott@va.gov>
Cc: Holmes, Chad E. <Chad.Holmes@va.gov>; Brewster, Peter <Peter.Brewster2@va.gov>
Subject: RE: VEText Capability Requirements for Vulnerable Patients - NEW TIME

Hi Shane,

Please see the attached form for the vetext request for the vulnerable patient outreach project.  Please advise of next steps when appropriate.

Thanks,

Terry

-----Original Appointment-----
From: Brewster, Peter <Peter.Brewster2@va.gov> 
Sent: Friday, July 16, 2021 12:20 PM
To: Brewster, Peter; Hubert, Terrence L.; Elliott, Shane M; Phillips, Paul R (V20); Rutan, Mary Kay; Ramos, Victor L.; Henrickson, Michael L. (Columbia); Barker, Tony; Stokes-Sumrall, Sonya L.(VHAV16); Cook, William C; Dingman, Scot C. VHAREN; Kennedy, Michael W.
Cc: Holmes, Chad E.; Tyler, Andrew; Miller, Shella M.
Subject: VEText Capability Requirements for Vulnerable Patients - NEW TIME
When: Thursday, July 22, 2021 1:30 PM-2:00 PM (UTC-05:00) Eastern Time (US & Canada).
Where: Microsoft Teams Meeting

The purpose of this meeting is to finalize design requirements for VEText for use in outreach efforts to vulnerable patients.
________________________________________________________________________________ 
Microsoft Teams meeting 
Join on your computer or mobile app 
Click here to join the meeting 
Or call in (audio only) 
+1 872-701-0185,,662812449#   United States, Chicago 
Phone Conference ID: 662 812 449# 
Find a local number | Reset PIN 
 
Learn More | Meeting options 
________________________________________________________________________________ 

[https://app.zenhub.com/files/133843125/35cd5e0b-a394-4e96-b10e-2901be074618/download](https://app.zenhub.com/files/133843125/35cd5e0b-a394-4e96-b10e-2901be074618/download)

**Comment by jwowk** [comment]
VEText Emergency Management notifications went live in Fall 2022.
