### ISSUE TITLE
[COGNITION]: VAOS Scheduler - Edit links would benefit from aria-labels

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2845]
## Description

A number of pages have `Edit` links that do not provide full context for assistive tech. Users must listen to nearby text/headings to understand what they are editing. We can improve this by adding `aria-labels` to each edit link. 

I've bundled this as a single issue ticket because it's more expedient to fix all instances than have several tickets that are closely related, but could drift if fixed at different times.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I want to hear explicit labels like "Edit phone number" when `Edit` buttons have keyboard or virtual cursor focus.
* As a screen reader user, I want to hear these longer labels read aloud when I queue them up in my Links menu (available in all major screen readers)
* As a visual user, I do not want to see any difference in the page layout

## Environment
Listing all page URLs affected:
* ~~/vaos/new-appointment/community-care-provider~~
* /vaos/new-appointment/review
* ~~/vaos/appointments/confirmed~~
* ~~/vaos/appointments/pending~~

## Possible Fixes (optional)
I've specced an aria-label for a pending appointment. This is the format to add an `aria-label` regardless of button or link.

```html
<a
  aria-label="View details of Audiology (hearing support)
  class="vads-u-font-weight--bold vads-u-text-decoration--none" 
  href="/vaos/appointments/pending/8a48dea06c84a667016c867b1ac00011"
>
  View details
  <i aria-hidden="true" class="fas fa-angle-right"></i>
</a>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2019-10-29 at 9 22 39 AM](https://user-images.githubusercontent.com/934879/67777229-7089d980-fa2f-11e9-917d-d867a8dee665.png)

---
![Screen Shot 2019-10-29 at 9 24 46 AM](https://user-images.githubusercontent.com/934879/67777256-78e21480-fa2f-11e9-951c-ce125f77c3ed.png)

---
![Screen Shot 2019-10-29 at 9 31 41 AM](https://user-images.githubusercontent.com/934879/67777293-85666d00-fa2f-11e9-9907-3b966937ad10.png)

**Comment by jbalboni** [comment]
Based on some design changes, I think we only have this issue on the review page now.
