### ISSUE TITLE
Remove triggers with no tags in GTM

### ISSUE THREAD

**Issue by laurensimpson14** [department-of-veterans-affairs/va.gov-team#28455]
The following triggers are not associated with any tags. Can they be removed? 

- [x] CE - phone-number-link-click
- [x] CE - directions-link-click
- [x] CE - onsite-search-results-click - yellow ribbon
- [x] HC - Search Page
- [x] Window Loaded - /Search Page
- [x] CE - view_search_results -type ahead enabled -customhtml
- [x] CL - COVID FAQ
- [x] Logo home click
- [x] PV - Window Loaded - Has Video
- [x] Temp - Exception - Nav Jump Link
- [x] PDF Downloads
- [x] DOM Ready
- [x] Education Opt-Out Modal
- [x] Feedback Event
- [x] GIBCT - Viewed Profile - HistoryChange

**Comment by laurensimpson14** [comment]
@jennaouellet I deleted all triggers without any associated tags. I also deleted all variables that had no references and were 1+ years old. 

Could you please QA? Is there any reason that you think we should keep these? [Link to workspace here](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000595).

**Comment by jennaouellet** [comment]
@laurensimpson14 I didn't see any issues with the workspace or any dependencies on the deleted triggers/varables. I think it's good to publish!

**Comment by laurensimpson14** [comment]
Published! Closing this ticket.
