### ISSUE TITLE
Adding Thomas Delrue to DSVA Slack

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#28451]
Please add Thomas.Delrue@omb.eop.gov as a full member, with access to the following channels:

- platform-crew-octo-de
- platform-team
- platform-crew-leadership
- vsp-security

Thanks!

**Comment by LizCallaghan** [comment]
@rroueche I could only find the last channel to add him, but his account is set up!

**Comment by rroueche** [comment]
awesome, thanks!
