### ISSUE TITLE
Support multiple appointments between CHIP / LoROTA

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28454]
To support multiple appointments for check in, CHIP and LoROTA need to be able to return an array of appointments instead of just one in a call. 
 
- [ ] Remove (one appointment) check
- [ ] ~Determine invalid appointment types~
- [ ] ~Filter invalid appointments (already checked in, cancelled, etc)~ FE currently wants all appointments for the day
- [ ] Make a data structure - good way to organize multiple appointments in a single array (sorting etc)

Task is done when: a call to CHIP with >1  appointment returns an array

For Future
Send the Appointment ID / Appointment IEN in the array for VA.gov

**Comment by kjduensing** [comment]
call VistA API to get appointments

**Comment by kjduensing** [comment]
add stories for VETExt tweak and vista api endpoint.

**Comment by aschulhof** [comment]
Captured in https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/19
