### ISSUE TITLE
Collaboration Cycle Kickoff [Healthcare Experience, Check-in Initiative 2]

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#28457]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] VFS: Attach any available artifacts.
- [x] Platform: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md).
    - [Initiative Brief]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/Last4LastName.md) for this iteration.
        -  To be updated
- [Poster](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/check-in-collateral-usabilityTest.pdf) used to initiate check-in experience.
-  [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=ae54280c-fc00-486e-83f3-faffbbdaff96) board including user flow.

- ## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [x] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [x] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [ ] Static pages
- [x] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 6. Will your work include:  

- [x] New content
- [x] Changes to existing content

### 7. Are you making a change to the user flow?
- [x] Yes
- [ ] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 8. Are you making a change to urls, navigation, or entry points?
- [x] Yes
- [ ] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 9. Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?
- [ ] Yes
- [x] No

### 10. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [x] Yes
- [ ] No

### 11. Who is the VA business owner for this body of work?

- [x ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @jparker0425. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 
- Design Intent
- Research Plan Review
- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: 
- Full Accessibility and 508 Office Audit
- Post-launch Check-in

We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience.

Please reach out to Dave Conlon and John Hashimoto to let them know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 

Design
Content
Quality Assurance (QA)
Accessibility
Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the Platform Collaboration Point Tracker. Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by jparker0425** [comment]
@shiragoodman , I have a quick question for you. Our Design Lead has already taken the Phase 2 iteration to office hours and received feedback for both design and content which are being incorporated currently (minimal feedback). We have also already completed the Research Plan Review. The team mainly needs to get with Accessibility at this point.  

That being said, are we allowed to move forward _without the Design Intent meeting_ and just meet with Accessibility directly, prior to our usability testing which is set to begin end of next week. At that point we would incorporate that feedback and schedule Midpoint. 

Just wanted to get your thoughts. Thank you.

**Comment by shiragoodman** [comment]
Hey @jparker0425. That's great that you've already gotten content and design feedback. As for skipping Design Intent, I would default to Ryan Thurlwell (@rtwell) since he likes to use Design Intent as an opportunity to provide feedback on the user experience. 

Whatever Ryan decides, I highly recommend you schedule a Midpoint Review prior to doing usability testing. This is when we can give you accessibility feedback . If you plan on doing multiple usability testing sessions, let me know and we can work something out. 

Could you also be sure to update your Initiative Brief linked above? I'm uncertain what the scope of this iteration is.

**Comment by jparker0425** [comment]
Thank you @shiragoodman for the quick feedback. @rtwell  Please let me know your thoughts and if you have any questions. 

Our usability testing will consist of several sessions starting next week spanning from 8/18 - 8/24.  Perigean has started the recruiting process. 

I will also be updating the initiative brief this week to include the details of this iteration.

**Comment by rtwell** [comment]
I'm fine skipping design intent as we spent quite a while discussing it last week—I would like to see this before it is tested (the midpoint review). thank you!

**Comment by jparker0425** [comment]
Great, appreciate the feedback @rtwell! 

@shiragoodman out usability tests have been scheduled as of this morning, first one starting 9am ET 8/18. There are three scheduled for that day. Would you like for me to put in a Midpoint review ticket for next Thursday (8/19) or is there a way to sync prior to testing?

**Comment by shiragoodman** [comment]
@jparker0425 So it's slightly under the 2 day mark, but we can have a Midpoint Review on Tuesday at 11 or 11:30. Let me know if that works with you/your team. If not, Friday is the earliest we can get you in (we try and reserve Thursday for Staging Review's only)

**Comment by jparker0425** [comment]
@shiragoodman I think we can make Tuesday happen. We have not coded, but have the mockups/working prototypes built out already and I will be adding the artifacts prior to next week. It will be similar to what we had for the [MVP](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26281) product Midpoint.

**Comment by jparker0425** [comment]
Closing this ticket as we continue to address feedback. Next will be scheduling staging review.
