### ISSUE TITLE
Add app logging for Session Timeout errors

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28464]
## User Story

As as VA.gov Staff Member, I would like to view accurate data on session timeout errors with our other application messages, in order to better monitor session timeouts.

## Expected Behavior

Today, session timeout errors are recorded in Sentry. Since data in sentry is short-lived and since it is separate from the rest of our application log data, we would like to also add a message into our application logs indicated the session timeout error for submissions.

## Acceptance Criteria

- [ ] Update existing service to log session timeout errors to our server log in addition to Sentry
- [ ] Validate that the log entry is present in the server log

**Comment by SKasimow** [comment]
@lihanli - do we have session time-out errors in Datadog? If not, should we add?

**Comment by lihanli** [comment]
@SKasimow what do you mean by session timeout?

**Comment by markfallows** [comment]
Closing as unnecessary.  Will open again if needed in the future.
