### ISSUE TITLE
Add app logging for File Upload errors

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28465]
## User Story

As as VA.gov Staff Member, I would like to view accurate data on file upload errors with our other application messages, in order to better monitor session timeouts.

## Expected Behavior

Today, file upload errors are recorded in Sentry. Since data in sentry is short-lived and since it is separate from the rest of our application log data, we would like to also add a message into our application logs indicated the file upload error for submissions.

## Acceptance Criteria

- [ ] Update existing service to log file upload errors to our server log in addition to Sentry
- [ ] Validate that the log entry is present in the server log

**Comment by SKasimow** [comment]
fyi... @lihanli

**Comment by lihanli** [comment]
this doesn't seem like a high priority issue. sentry is already recording these errors and sentry logs are not short lived, i see errors from a year ago on there
