### ISSUE TITLE
HCE Checkin Phase 2 - DESIGN 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#28475]
Design for post-MVP initiative regarding Last 4 / LastName and multiple appointments in the checkin product.

**Comment by julieadair1** [comment]
@jparker0425 looks like all issues in this epic have been completed.  I'm going to go ahead and close it out. 
cc: @kristenmcconnell

**Comment by kristenmcconnell** [comment]
Makes sense to me.
