### ISSUE TITLE
LoROTA generates an access token for full scope 

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28497]
A common theme for the next stage of CHIP and LoROTA is needing the ability to grant access to "full" scope of information.

Validating against information (aka Last 4 and Last name) will grant the requester access. 

- When a requester sends a claims token signed with a private key to LoROTA. 
- LoROTA will use the public key to verify the claims token. 
- Once the request is validated LoROTA generates an access token with claims to which the caller has requested. 

Blocked from testing until **Scoped Authentication Flow** is complete.
 
**Task is done when:**
1. Hit the auth endpoint with a "full" claims token and verify we get a token back with the claims we requested. 
2. We hit the auth without a claims token and get an error

**Comment by calquisola** [comment]
new version of Lorota deployed.
