### ISSUE TITLE
CT Redesign: Mobile location compare drawer flickering

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#28492]
## Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location on mobile view
2. Scroll down and search by location
3. Search on a location
4. Compare 3 schools
5. Expand compare tray
6. Observe

https://user-images.githubusercontent.com/48804582/128885027-6da52087-ded9-47ba-b91f-d97721bc8712.mov

## Expected Results:

Should not flicker

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18308

**Comment by sonntag-adam** [comment]
This is fixed
