### ISSUE TITLE
Housekeeping: Switch Instances

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28509]
For CHIP and LoROTA we're pointed to instances that are not under CI/CD / Infrastructure as code. goal is to put everything under that umbrella.

**Task is done when:**
Deploy new dev instances
Point everyone to new staging instances
Delete old instances

**Comment by calquisola** [comment]
no more blockers. Let's do this after Martinsburg Pilot.

**Comment by kjduensing** [comment]
Talk to Dillo about when we can do this.
