### ISSUE TITLE
Directions for attending orientation

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#28508]
### Description
In the [Getting Repo Access](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-GettingRepoAccess) section it says to "attend Orientation with the Product Support team" however there is no information included on how to do this.

**Comment by lianilychee** [comment]
@shiragoodman , since this is Governance related, we're reassigning to you to close (or whatever else you see fit).  It's a pretty old ticket.

**Comment by shiragoodman** [comment]
thanks, @lianilychee . I put our team's label on it. 

@mchelen-gov this problem still exists, however the solution for getting repo access now falls on the Infrastructure team. See [this ticket for reference. ](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/35154) If you'd like, maybe we can put forth an interim/short term solution for updating Platform Website until Infrastructure has come up with a long term plan for onboarding teams.

**Comment by shiragoodman** [comment]
issue resolved with ticket #39321
