### ISSUE TITLE
Generate a public and private keypair for CHIP

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28510]
A [keypair](https://www.preveil.com/blog/public-and-private-key/) are two files that match, one public and one private, that can verify encrypted information

- Generate a RSA keypair using openSSL
- Give public key to LoROTA
- LoROTA will store it somewhere very safe
- CHIP will store private key

**Task is done when**
- Public key is stored in LoROTA
- Private key is stored where only CHIP can access it
- Two files are generated when open SSL command invoked

**Comment by kjduensing** [comment]
Considering using KMS to facilitate creating/verifying/signing .

**Comment by kjduensing** [comment]
@calquisola  the keypair is created. As discussed, leaving it up to you to decide if you want to store the public key separately or just use the kms api to verify future claims tokens from CHIP.

It might be good to keep in mind that you'll need to repeat this process for other integrations, so it might be more convenient to store the public keys in the secrets manager (or somewhere) so you have a common place to access them. This will come in handy for future integrations as well.
