### ISSUE TITLE
Explore Search.gov video behavior and access to API for VA

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28519]
##  Description
As part of the exploration work we have been doing around adding videos to VA.gov search results page we have identified a few odd behaviors and potential bugs that need further discussion and exploration with Search.gov

## Background 
-  Results Research #27999 

## Acceptance Criteria
- [x] Send evidence of potential behavior errors/bugs to the Search.gov team for review
- [x] Work with Search.gov as needed to explore/resolve
- [x] Collect further evidence to support or refute the potential integration of videos on the VA.gov site.

**Comment by denisecoveyduc** [comment]
@srsuddath @mgleo Here is the response from search.gov that I mentioned on SU today. It would be great @srsuddath if you can check out these endpoints this sprint so we can summarize our findings in #28631.

> Hi Denise,
> 
> Thank you for the examples - investigating now. Wanted to pass you the Videos API information though ahead of time, this will reflect the same set of videos you see in the "videos" vertical.
> 
> Instructions are here: https://search.usa.gov/sites/7378/api_instructions with one caveat - 
> 
> The instructions list this as the endpoint:
> https://search.usa.gov/api/v2/search/video?affiliate=va&access_key={{YOUR_ACCESS_KEY}}=&query={YOUR_SEARCH_TERM}
> 
> While that will work, the below is the preferred endpoint:
> https://api.gsa.gov/technology/searchgov/v2/results/video?affiliate=va&access_key={{YOUR_ACCESS_KEY}}=&query={YOUR_SEARCH_TERM}
> 
> Let me know if you have questions as you test the API as well. We'll investigate the video issues on our end and follow up. 
> 
> Best,
> Amani

**Comment by mgleo** [comment]
Response from Amani: 

> Hi Denise and team,
> 
> Appreciate your patience while we investigated this!
> 
> Difference in Results on First Page vs. Tab: We'll show the most relevant video in the first page of results, while the videos tab itself shows results sorted by recency. It also looks like we require a keyword match in the video title to show on the first page, rather than only a match in the description. However, if you use the Videos API endpoint, you'll retrieve all videos (that would be listed in the tab), not just the singular one we feature on the hosted results page. 
> 
> Videos from other channels appearing in results: We index all playlists for any given youtube channel, so that's where those additional videos are coming from. You can see the VA playlists here: https://www.youtube.com/c/VeteransHealthAdmin/playlists and an example of a playlist with non-VA content here: https://www.youtube.com/watch?v=zahV4QKqaUw&list=PL3AQ_JVoBEyyy1-hWbMe2MWPWL3aben9I  
> 
> As always, let us know with additional questions!
> 
> Best,
> Amani
