### ISSUE TITLE
[Bug] Fix for missing facility in the PDF sent to CARMA

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28523]
CSP staff brought an issue to the CARMA team’s attention that was reported to the VSA Caregiver product team. The 10-10CG PDF that generates after some Veterans and caregivers submit an online application is missing the typed name of the VAMC or clinic where the Veteran receives or plans to receive health care services. The problem has been occurring for all PDFs since July 21 at around 1:50 PM Eastern.

Kevin and Daniel found the issue.

The functionality to create the PDF exists in two places:
1. Download
2. Send to CARMA

It's working in Download but on in the job that sends to CARMA.

According to Kevin:

> We need to make sure the deliver attachment job also generates a label and sends it. We should also ensure we have a default value (whatever was provided in the payload)
> 
> The download PDF doesn’t use a background job. It’s an API req/res in process. When a submission is done, it triggers a job to send attachments. And in that job the PDF is generated. So it’s generated in two places
> 
> The PDF generation for the user has the label passed as an option. The PDF generation that goes to CARMA doesn’t have a label passed to it.

**Comment by dnalbach** [comment]
I am placing the code for this in a work-in-process commit to a feature branch by this ticket name:
https://github.com/department-of-veterans-affairs/vets-api/tree/28523_new_fix

Code is working to provide the facility label with either toggle state, on or off. Resolves correctly to JSON schema or live API call in local testing.

Some tests are still failing and need to be fixed. Work interrupted, code is in branch above.

**Comment by tchrisdyer** [comment]
The original change that caused this issue was backed out of production on August 11th. Daniel worked an update to that code which would work correctly but needs further testing as the change to incorporate the PDF generation for CARMA was substantial. Daniel's code is located at https://github.com/department-of-veterans-affairs/vets-api/tree/28523_new_fix
