### ISSUE TITLE
Evaluate github extensions for performance budget enforcement 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2856]
# Overview 

vets-website has no performance monitoring or enforcement. Evaluate GitHub extensions for monitoring / enforcing a performance budget 

# Tasks 

- Evaluate lighthouse: https://github.com/GoogleChrome/lighthouse and https://github.com/GoogleChromeLabs/lighthousebot

**Comment by timwright12** [comment]
With the recent switch to Github Actions, we're going to use lighthouse for this.

**Comment by timwright12** [comment]
PR for foundational reporting https://github.com/department-of-veterans-affairs/vets-website/pull/18144

**Comment by timwright12** [comment]
**Follow up tickets**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28384
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28386
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28383
