### ISSUE TITLE
CT Redesign: Replace school with institution in compare page content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28566]
As a comparison tool redesign user, I need the language on the compare page to be generic so that when I am comparing institutions of different types I am not confused by them all being referred to as schools.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The learn more links and content are outside the scope of this story.

## Acceptance Criteria
1. The content in the header:

    > **School comparison:** 
    > View school information side by side to compare schools

    is replaced with:

    > **Institution comparison:**
    > Compare schools, employers and VET TEC providers side-by-side

2. In the "Summary" section, the "Type of school" row label is replaced with "Type of institution".
    a. The type displayed for VET TEC institutions is "VET TEC"
    b. The type displayed for OJT/Apprenticeship institutions is "Employer"
    c. The type displayed for School institutions is "[Type] school" (ex. Private school, For profit school, Public school)

3. In the "Summary" section, the "Size of school" row label is replaced with "Size of institution".

4. In the "Your estimated benefits" section, the "Payments made to school" sub-header is replaced with "Payments made to institution".

5. In the "Your estimated benefits" section, the "GI Bill pays to school" row label is replaced with "GI Bill pays to institution".

6. The "School Ratings" section header is replaced with "Veteran ratings".

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/screens/296064394_CT_Redesign_PI11_Desktop_ComparePg_Learnmore)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/85d4a210182b4c54bfac656ba6cea011432bbd7c/products/education-careers/school-comparison-tool/redesign/design/content-compare-pare.md)

**Comment by elder-joseph** [comment]
Associated PR: Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/18266

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18266

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2128&group_by=cases:section_id&group_order=asc
