### ISSUE TITLE
Spec out frontend work for Facility Search on 10-10CG

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28569]
## User Story

**As a** Veteran/Caregiver, **I want to** search for a facility **in order to** choose the most appropriate facility.

The purpose of this ticket is to spec out and create a rough working prototype of facility search.

[UX Designs](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/p/D741171D-81BD-4CEF-A7A2-69A548C8D346) ( refer to Vet Medical Center v2.2 for example of proposed layout)

## Expected Behavior

- GIVEN a Veteran or Caregiver is filing out the only 10-10CG form
- WHEN the Veteran or Caregiver arrives at the Facility Selection screen (see UX design above)
- AND enters their [city and state] or [zipcode]
- AND specified a search radius
- AND submits the search
- THEN call the facility service to retrieve a list of VA Health facilities (option to limit to facilities with Caregiver suport service type)
- AND display the facility names, addresses and distances in a Radio button list

## Acceptance Criteria

- [ ] High-level spec for how this should work
- [ ] Working prototype of a simple search and display of facility list (could just use zip code and hard coded area)

**Comment by hdjustice** [comment]
Closing ticket, added another ticket for FE technical discovery
