### ISSUE TITLE
Access for Dany Han dany.han@libertyits.com MATSUMOTO

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#28564]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
Cecilia Lee Cecilia.Lee@va.gov
- Please provide your name.
Dany Han
- Please Provide your email.
Dany.Han@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
Matsumoto, Rails Engineer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES / NO 
YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC63wx35ugwoTJ13PQ5kUtxQ40w0QLV/55fRKZTYWzhZvhIWYu4mbDUjkkwFQWgTvf240xgxDrJGgQKYJV4keBg2bllKn1Ha5vl4cDjDjY4m1MlrgRJU5Y1zIKXMBZeQ9ZqRzMhua/tEZJjduXtUn29u15M/2SIf/FkW42RRrB9kb5tPvXHwwKumBUDhMgnw/SYWkt6c+uBOzI79NtZT3jzypSTGDqgQkYLZlu4HKXCTAyK3J7SjKhrAxfAWx1XzDXZLqM86HJZowgLrM5HG3dqz02VaMpKbp9ZOWRBdovbxch1k9mdsq17G+JFl9nOk7m5Iv8Uomh14wJ5JfE+dFJWyO/qM3oAhxYYzd2UDItYb12KFnXOqiC/rb7wE8XKNVCTKZw9bu2S50Wh3JNSBFp4jD+dsQHt+tTzv3WoUgte+PEfdb1U3pocsKIPJPZpJQbcT1mBd1s1rM3dZAc0E+drCDnSnks9DGVqcGA9U41pDz4m1I/QNjWimdE2O4GPclk= danyhan@devs-MBP-2.lan
```

- Grant AWS Console access?
  > YES / NO
  - What AWS services do you need access to and why? 
No

**Comment by tskinn** [comment]
Does Dany have a github account? Is he part of the department-of-veterans-affairs github org?

**Comment by jbritt1** [comment]
@mviterna, we need Dany's GitHub handle as time allows please.

**Comment by mviterna** [comment]
@jbritt1 @tskinn It doesn't look like it. Oh man, I must have missed an onboarding step, how do I put in that request?

**Comment by jbritt1** [comment]
> @jbritt1 @tskinn It doesn't look like it. Oh man, I must have missed an onboarding step, how do I put in that request?

https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D

**Comment by mviterna** [comment]
@jbritt1 sorry about the delay, I've opened a new ticket to get him added to VA GH. https://github.com/department-of-veterans-affairs/github-user-requests/issues/8218  his username will be danielliberty

**Comment by mviterna** [comment]
@jbritt1 Ok, I think he is in GH now

**Comment by jbritt1** [comment]
Verified membership of the DSVA GH Org

**Comment by jbritt1** [comment]
SOCKS access granted @danielliberty. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
