### ISSUE TITLE
[MCP] Document data to include on the medical copay portal to inform technical discovery

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#28579]
## Issue Description
_There's certain data we're not currently receiving in the Liberty's API that we'd like to include in the medical copay tool. We need to document the data we want to include in a most-MVP iteration_

---
## Tasks
- [x] _Document a list the data we want for MCP_

## Acceptance Criteria
- [x] _Link the document in this ticket and post in the public debt resolution Slack channel_

**Comment by rileyorr** [comment]
Writing this here for my reference:

We need to be able to show Veterans the status of their balances similar to the statuses in the VBA debt portal. We've had conversations with SME's where we've learned that there's a feature in VISTA that allows a charge to be suspended and potentially shows a dropdown of the reason, but we don't know what all the reasons are. 
Some potential statuses could result from: 
- Veteran being on a payment plan for their charges
- Waiver request being reviewed
- Additional suspension reasons

**Comment by rileyorr** [comment]
Update to the above:

We just learned that we don't have access to any data attributes outlined above. For example, if a Veteran submits an FSR for a waiver there is no 'suspended for waiver request review' status; there's the ability to add a text comment to their file stating that information. 

We learned that individual charges can be in a suspended or active state. Some of these suspension statuses include:
- Closed
- Collected

This appears to be something we won't have access to in this iteration of the Liberty API, but we can add it to the list of data we can request access to

**Comment by rileyorr** [comment]
More things to consider when I make this doc:
- We may need to remove the $0 balance cards from MVP, will need to expose that data in a future iteration
- Identify if a copay bill is related to third party copays

**Comment by rebeccawalsh** [comment]
Progress is being made on this work in a [sharepoint document here](https://governmentcio.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B5166B975-8860-4909-8ECB-11BEBDB85018%7D&file=Document.docx&action=default&mobileredirect=true&cid=c85c3031-b43a-43e5-a6a3-4a415bb7662e).

**Comment by rileyorr** [comment]
We've finalized the list & posted it in our slack channel for any feedback!
