### ISSUE TITLE
Set Status: E-CHECK-IN STARTED in VistA API

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28570]
In order to alert VSE staff that a veteran has begun the E-Checkin process we need to expose endpoints in the VistA API for CHIP to consume. 
 
- [x] Call an RPC (already created) to set the value and get / set the local VistA datetime
- [x] Expose endpoints to CHIP

**Comment by wamccarty** [comment]
PUT:    base_url/checkin-status-set/{stationNo}/{sdecApptIen}/{statusIen}

response:
success:
{
  "success": true,
  "severity": "",
  "responseStatus": 200,
  "message": null,
  "path": "/vista-api/api/v1/sdec/checkin-status-set/500/221/6",
  "payload": {
    "ApptCheckInSteps": {
      "FilingSuccess": 1
    }
  }
}

error:
{
  "success": false,
  "severity": "",
  "responseStatus": 200,
  "message": "Duplicate status entry.",
  "path": "/vista-api/api/v1/sdec/checkin-status-set/500/221/5",
  "payload": null
}

**Comment by wamccarty** [comment]
1="PRE-CHECK-IN STARTED"
2="PRE-CHECK-IN COMPLETE"
3="CHECK-IN STARTED"
4="CHECK-IN COMPLETE"
5="E-CHECK-IN STARTED"
6="E-CHECK-IN COMPLETE"
7="Much Test"
