### ISSUE TITLE
Create endpoint: GET E-Checkin Status

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#28577]
Make an Endpoint - Appointment E Checkin Status will return all possible values associated with E Checkin Array

- [ ] Expose an endpoint
- [ ] Call RPC given an appointment IEN
- [ ] Return all set values

**Definition of done:**
When it can be called and returns all set values

**Comment by kjduensing** [comment]
From Andy:

```
get status of specific statusIen
{{base_url}}/checkin-status-get/{stationNo}/{sdecApptIen}/{statusIen}
     will return   success=false   if statusIen not found/set
get all set statuses
{{base_url}}/checkin-status-get-all/{stationNo}/{sdecApptIen}
     will return success=false if no statuses are found/set
```
