### ISSUE TITLE
CT Redesign: Bring awareness to compare drawer when add/removing institutions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28587]
As a comparison tool redesign user, I need to be made aware of the compare drawer so that I am not confused when I check the compare box on a search result card.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This behavior apply to both desktop and mobile.
3. The interactions in this story do not override the user interactions with the compare drawer itself.

## Acceptance Criteria:
1. When the first institution is added to the comparison drawer; it is updated in the following steps:
    a. The drawer opens.
    b. The institution is added to the drawer and the count is updated
    c. The drawer closes.
2. When a second or third institution is added to the comparison drawer:
    a. the drawer opens, and remains open, if closed.
    b. the drawer takes no action if open.
3. If after removing an institution, the compare drawer is empty, it closes.
4. If a user tries to add more than 3 institutions for comparison the following content is displayed:

    > **You've reached the comparison limit**
    > 
    > You can compare up to 3 schools or employers. You'll have to remove one of your selections before you can add another to the comparison.

## Supporting Artifacts:
1. [Modal Prototype](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/screens/296062817_Searchbyname_Desktop_MaximumReached)

2. Mobile timing breakdown:
<img width="643" alt="drawer_animation_breakdown" src="https://user-images.githubusercontent.com/48260534/129376236-572227a6-c276-4b77-96b6-f6d2d1e17f55.png">
- 0.3s to open
- 0.5s delay
- 0.3s to close

3. Mobile animation breakdown:
![Gif_walkthrough.png](https://images.zenhubusercontent.com/5c814a7219e31d676cd7e33a/e5886e76-a1c2-4565-80ab-44b264fa6120)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18361

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
testing complete
