### ISSUE TITLE
Sort by parent sites for community care provider selection

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#28580]
## Description
The community care provider list can be sorted by home address or current location. Include option to sort by their registered parent site locations.

---

## Acceptance Criteria
Background: the `va_online_scheduling_cc_iterations` toggle is on

Given a user is in the CC flow
And the user has a home address on file
And the user is on the provider preference page
When user selects Choose a provider
Then the list sort options are home address, an alphabetical list of parent sites, and current location
And the default sort is home address
And the copy and design match the copy and design docs

### Design Assets
- [Dropdown sorting selector states](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/QbrLaqY)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md) is updated

**Comment by jbalboni** [comment]
Closing this, since the work is being done in the dropdown selector ticket.
