### ISSUE TITLE
Establish governance process for performance monitoring 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2858]
# Overview 

vets-website has no governance over its performance. Document process for monitoring and improving performance 

# Tasks 
- Categorize user behavior 
  - determine the highest traffic landing pages 
  - determine the major navigation avenues through the site 
- Choose which user path to optimize and evaluate a baseline 
  - Focus on FCP for each page
  - Focus on revisit / caching behavior 
- Determine what improvements to make 
- Establish a review process (e.g. pre/post performance evaluation, a/b testing performance improvements) 
- Determine how to scale optimization and improvements
  - auditing tasks that can be standardized 
  - monitoring / messaging that can be automated 
- Present findings to stakeholders

**Comment by KevinMHoffmanUSDS** [comment]
A thought -  how might we frame this as a service we provide?

**Comment by rmessina1010** [comment]
Expired. Closing.
