### ISSUE TITLE
AWS Staging: VAOS Direct Scheduling clinic Availability Calendar >Next button not enabled

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#28597]
1.  Log in as Cecil. 
2. Select Primary Care. Select Cheyenne. 
3. Enter April 1, 2022 for 'when do you want to schedule this appointment'.  Select continue.
4. Expected response:   The month of April displays and I can advance to the next month (using the >Next button).  
5. Actual Response:   The month of April displays and I CAN NOT advance to the next month (using the >Next button).   I have to go back and change the date to May 1, 2022 if I want to see May availability. 
6. I can use < Previous just fine. It is the >Next that is all in grey. 

april 1 selected call:  https://staging-api.va.gov/vaos/v0/facilities/983/available_appointments?type_of_care_[…]&clinic_ids[]=455&start_date=2022-04-01&end_date=2022-05-31

may 2 selected call:  https://staging-api.va.gov/vaos/v0/facilities/983/available_appointments?type_of_care_[…]&clinic_ids[]=455&start_date=2022-05-01&end_date=2022-06-30 (edited) 

Max future days to the clinic is 450 days.  So that is not the issue.

**Comment by laurenernest** [comment]
Appears to be fixed now. @marcynadeau feel free to validate on your end as well
