### ISSUE TITLE
Design Bug: Pagination

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#28601]
##  Description
Spacing issues around pagination and Powered by Search.gov" on Search Results page. Fixes may rely on updates to the pagination code and not the Search Results page.

Pagination and Search.gov text do not line up on desktop
![desktop-uneven](https://user-images.githubusercontent.com/5553542/129089432-940c4352-37b4-4315-af32-702ec725d671.png)

Uneven padding on the sides depending on page number on desktop
![mobile-pagination-uneven](https://user-images.githubusercontent.com/5553542/129089962-cd18984a-a2d3-4106-a465-56262f262caf.png)

Uneven padding on the sides depending on page number on mobile
![desktop-pagination-uneven](https://user-images.githubusercontent.com/5553542/129089572-0d9ae809-5688-405b-b048-19eb25dd7290.png)

Increase padding between Search.gov text and More VA search tools 
![mobile-spacing](https://user-images.githubusercontent.com/5553542/129090011-31bdcf7b-d195-4412-8240-4ed7dfa1b695.png)

**Comment by srsuddath** [comment]
PR has been merged and issue fixed, ticket can now be closed
