### ISSUE TITLE
CT Redesign: Add Learn more modals to compare page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28618]
As a comparison tool redesign user, I need to be able to get more context around the differences of institutions when using the compare page so that I do not have questions about what the data in a row represents.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. AC1, AC7, AC11, AC12, AC15, AC22 content includes updates to the shared content.

## Acceptance Criteria:
1. The "Accreditation" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about the different accreditation types and why it matters"
    b. Displays the following content (note: this content is shared with the profile page academics section accreditation learn more):

    > **Accreditation and why it matters**
    > 
    > The goal of accreditation is to ensure the education provided by institutions of higher learning meets acceptable levels of quality. Accreditation matters if you plan to start school at one institution and transfer to another to complete your degree. Be sure to ask any potential school about their credit transfer policy.
    > 
    > Schools are accredited regionally or nationally by private educational associations. While the Department of Education (ED) doesn't say whether regional or national accreditation is better, a recent ED study revealed that, “Nearly 90 percent of all student credit transfer opportunities occurred between institutions that were regionally, rather than nationally, accredited.” [Read the ED report on credit transferability](http://nces.ed.gov/pubs2014/2014163.pdf).  
    > 
    > To learn more about the accreditation process and types of accreditation, visit the [About this Tool] (https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#accreditation_type) page.

2. The "GI Bill students" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about how we calculate the number of GI Bill students"
    b. Displays the following content (note: this content is shared with the profile page header gi bill students learn more):

    > **GI Bill students**
    > 
    > The number of Veterans, service members and family members using their GI Bill benefits attending this school in the last calendar year. This includes all chapters of the GI Bill program (e.g., Post-9/11, Montgomery GI Bill, Reserve Education Assistance Program, and Veteran Readiness and Employment). Keep in mind that differences in attendee numbers don’t necessarily mean one school is more military friendly than another. This information will be updated annually.

3. The "Size of institution" row label has a "Learn more" that:
    a. Has an aria label: “Learn more about institution size”
    b. Displays the following content:

    > **Size of institution**
    > 
    > The size of institutions is based on calculation of full-time equivalent students (FTEs) which considers both full-time and part-time students. Two-year colleges are classified using a different scale than four-year and higher institutions. 
    > 
    > Two-year college sizes
    > • Very small  -- fewer than 500 FTEs attend this institution
    > • Small  -- at least 500 but fewer than 2,000 FTEs attend
    > • Medium -- at least 2000 but fewer than 5,000 FTEs  
    > • Large -- at least 5,000 but fewer than 10,000 FTEs attend  
    > • Very large -- 10,000 or more FTEs attend  
    > 
    > Four-year college sizes
    > • Very small -- fewer than 1,000 FTEs attend this four-year institution
    > • Small -- at least 1,000 but fewer than 3,000 FTEs attend
    > • Medium -- at least 3,000 but fewer than 10,000 FTEs attend
    > • Large -- more than 10,000 FTEs attend

4. The "Specialized mission" row label has a "Learn more" that:
    a. Has an aria label: “Learn more about specialized mission”
    b. Displays the following content:

    > **Specialized mission** 
    > 
    > Is the school single-gender, a Historically Black College or University, or does it have a religious affiliation?

5. The "Tuition and fees" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about tuition and fees"
    b. Displays the following content (note: this content is shared with the profile page calculate your benefits t&f learn more):

    > We display the average tuition and fees for an undergraduate student that is reported by the school to the Department of Education. These values might not be the same for all students at an institution. 
    > 
    > [Learn more about the tuition and fees displayed in the GI Bill Comparison Tool](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#tuition_fees_input)

6. The "Housing allowance" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about how housing allowance is determined"
    b. Displays the following content (note: this content is shared with the profile page calculate your benefits housing allowance learn more):

    > **Your housing allowance is determined by where you take classes**
    > 
    > Under the GI Bill you’re eligible to receive a monthly housing allowance. We calculate this monthly housing allowance based on where you take classes.
    > 
    > [View the current housing allowance payment rates](https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp)

7. The "Book stipend" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about the book stipend"
    b. Displays the following content (note: this content is shared with the profile page calculate your benefits book stipend learn more):

    >     You may be eligible for money to cover books and supplies, up to $83 per month.

8. The "Caution flags" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about why caution flags might appear on an institution profile"
    b. Displays the following content:

    > Caution flags indicate that VA or other federal agencies like the Department of Defense (DoD) or Department of Education (ED) have applied increased regulatory or legal scrutiny to this program.

9. The "Student complaints" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about student complaints"
    b. Displays the following content (note: this content is shared with the profile page cautionary information student feedback learn more):

    > **Student complaints**
    > 
    > This is the number of closed, Principles of Excellence-related, complaints submitted to VA through the GI Bill Feedback system for this school.
    > 
    > To learn more [visit the VA GI Bill Feedback Tool](https://www.benefits.va.gov/GIBILL/Feedback.asp).

10. The "Credit for military training" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about credit for military training"
    b. Displays the following content (note: this content is shared with the profile page academics education details learn more):

    > **Credit for military training**
    > 
    > Does the school offer postsecondary credit for experiences and military training?

11. The "Yellow ribbon" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about what is covered by the Yellow Ribbon program and who can use it"
    b. Displays the following content (note: this content is shared with the profile page calculate your benefits section learn more):

    > **Yellow Ribbon Program**
    > 
    > The Yellow Ribbon Program can help you pay for out-of-state, private school, or graduate school tuition that the Post-9/11 GI Bill doesn’t cover. Schools that choose to participate in the Yellow Ribbon program will contribute a certain amount toward the extra tuition. VA will match the participating school’s contribution, up to the total cost of the tuition and fees.
    > 
    > [Learn more about the Yellow Ribbon Program.](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/)
    > 
    > [Visit the Yellow Ribbon tool](https://www.va.gov/education/yellow-ribbon-participating-schools/) to find schools that participate in this program.

12. The "Student Veteran Group" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about Student Veteran Groups"
    b. Displays the following content (note: this content is shared with the profile page veteran programs and support section learn more):

    > **Student Veteran group**
    > 
    > Does this school have a student-led Veteran group on campus?
    > 
    > If a school has a student Veterans group that’s not represented here, please notify us by email at [224A.VBAVACO@va.gov]. We update this information in the Comparison Tool quarterly.
    > 
    > Please note this email address is only for Comparison Tool-related issues. For questions about your GI Bill benefits, [please check this "Ask a Question" page](https://gibill.custhelp.va.gov/app/utils/login_form/redirect/ask).

13. The "Principles of Excellence" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about Principles of Excellence"
    b. Displays the following content (note: this content is shared with the profile page veteran programs and support section learn more):

    > **Principles of Excellence**
    > 
    > The [Principles of Excellence](https://www.govinfo.gov/content/pkg/FR-2012-05-02/pdf/2012-10715.pdf) are guidelines for educational institutions receiving federal funding. Schools that agree to participate will:
    > 
    > • End fraudulent and aggressive recruiting techniques and misrepresentation.
    > • Provide students with a personalized form covering the total cost of an education program.
    > • Provide educational plans for all military and Veteran education beneficiaries.
    > • Provide accommodations for service members and Reservists absent due to service requirements.
    > • Assign a point of contact for academic and financial advising.
    > • Make sure all new programs are accredited before they enroll students.
    > • Align institutional refund policies with those under Title IV.
    > 
    > Foreign schools, high schools, on-the-job training and apprenticeship programs, residency and internship programs, and those who don’t charge tuition and fees aren’t asked to comply with the Principles of Excellence.
    > 
    > We try to make sure this information is accurate, but prospective students should only use this as a planning tool. Principles of Excellence schools are updated quarterly.

14. The "8 Keys to Veteran Success" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about 8 Keys to Veteran Success"
    b. Displays the following content (note: this content is shared with the profile page veteran programs and support section learn more):

    > **8 Keys to Veteran Success**
    > 
    > The “8 Keys to Veterans’ Success” are steps that postsecondary institutions can take to assist Veterans and service members in transitioning to higher education, completing their college programs, and obtaining career-ready skills.
    > 
    > Postsecondary institutions listed here have stated their support for the 8 Keys. However, this isn’t an assurance by the U.S. Department of Education that an institution has actually implemented the 8 Keys. It also doesn’t mean that these institutions are endorsed by the U.S. Department of Education.
    > 
    > To learn more about accreditation, visit the U.S. Department of Education’s [8 Keys to Veterans’ Success page](Link to http://www.ed.gov/veterans-and-military-families/8-keys-success-sites).

15. The "Military Tuition Assistance (TA)" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about Military Tuition Assistance"
    b. Displays the following content (note: this content is shared with the profile page veteran programs and support section learn more):

    > **Military Tuition Assistance (TA)** 
    > 
    > Military Tuition Assistance is a benefit paid to eligible members of the Army, Navy, Marines, Air Force, and Coast Guard. Each service has its own criteria for eligibility and application process. This money is usually paid directly to the institution by the individual service.

22. The "Priority Enrollment" row label has a "Learn more" that:
    a. Has an aria label: "Learn more about priority enrollment"
    b. Displays the following content (note: this content is shared with the profile page academics section learn more):

    > **Priority enrollment**
    > 
    > If a college or university has a system for priority enrollment that allows certain student Veterans to enroll in courses earlier than other students (not necessarily earlier than all students), we’ll note that with the school’s information here.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222692/296064394/preview)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/bfc512315a9b1d6ffe43b1e643994c806b062cf0/products/education-careers/school-comparison-tool/redesign/design/content-compare-pare.md)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18300

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2144)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by dneel-bah** [comment]
Functionality has been verified on staging.  Closing story as completed.
