### ISSUE TITLE
Homepage Banner Migration - Update isBannerVisible liquid filter to support trailing * and ! regex

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28614]
## Description
_PW Team partnered with CMS team is looking to transition "Banner Alerts" to CMS functionality in order to make it more accessible and streamlined for OPIA stakeholders when looking to publish immediate alerts across VA.gov website._

## Reference 
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1628544653122200

## Tasks
- [x] PW team will update isBannerVisible liquid filter to support trailing * and ! regex

## Testing done
Locally, added unit test.

## Acceptance criteria
- [x]  Update isBannerVisible liquid filter to support trailing * and ! regex

**Comment by swirtSJW** [comment]
## Cases:
### no wildcard *
`/education/` or   `/education` - If a path ends with just a slash. it should cause the banner to appear on just that page.  In this case the banner should only appear on `/education/index.html' but not on any other pages.

### trailing *  - wildcard
`/education/*`  - If a path ends with a slash and *. it should cause the banner to appear on every page within that path.
`/education/index.html', `/education/loans/index.html', `/education/proof/index.html' ...    EXCEPT for any path specified as a blocked path.

### leading ! - blocked path
``!/education/loan-calculator/'` - If a banner should not a appear on a page, it will be prefixed with `!`.   Example:  `!/education/loan-calculator/'  would have no banner, even if `/education/*` had also been set.  In this case, anything on the /education/ path would have a banner except the loan-calculator page.


Those three cases would give us a lot of flexibility.

There are two "_stretch possibilities_" that do not have to get solved with this ticket or any time soon... but should guide the approach so as to allow them to be achieved in the future without lots of re-working.

1. Multiple path blocking - the combination of the blocking path and wildcard.
`!/education/foundations/*`  This would allow an entire subpath set to be excluded.
2. Mid path wildcard - allows for a specific targeting across multiple similar sections (like VAMC systems)
`/*-health-care/contact-us/` would allow a banner to appear on every contact-us page across all systems.


Architectural suggestions.... errr really just random thoughts.  :)
1.  Separate paths into two arrays immediately: blocked paths (those that had ! - strip the ! on the way in), and allowed paths.
2. A matcher method that can be used to determine a match to either array.
3. Look for block, only if you get an allowed path match.

**Comment by brianalloyd** [comment]
Validate and closing.
