### ISSUE TITLE
CT Redesign: Profile page "compare" checkbox cannot be clicked

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#28610]
The checkbox on the institution profile to add an institution to the compare tray cannot be clicked.

![Screen Shot 2021-08-11 at 2.34.09 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/bd0b9b11-5204-4827-a1f6-7208d795523b)

### Steps to reproduce
1. Navigate to any institution profile (ex. https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/14800005) 
2. Click the "Compare" checkbox

### Expected Behavior
Checkbox can be checked

### Actual Behavior
Checkbox cannot be clicked

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18209

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
testing complete
