### ISSUE TITLE
[FE] Notification Preferences: Add loading state to radio buttons

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28619]
## Background
As part of the revised designs for the Notification Preferences feature we need to add a loading state to the radio buttons when the user makes a selection

## Tasks
- [ ] Implement loading state functionality
- [ ] Test

**Comment by erikphansen** [comment]
This work was done as part of https://github.com/department-of-veterans-affairs/vets-website/pull/18331
