### ISSUE TITLE
Front End Service Account auth for s3 bucket uploads

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#28629]
## Description
The front end service account needs to be authorized to upload to the `testing-tools-testing-reports`  s3 bucket, so we can upload files to it from the `vets-website` workflow in GHA.

## Background/context 
The S3 bucket `testing-tools-testing-reports` was created to store and host our Mochawesome reports and videos to be viewed by users from their workflows.  We now need the workflow to be able to upload to this bucket.

---
## Tasks
- [x] Edit the front end GHA service account permissions (not the roles) to be able to upload items to this bucket.

## Acceptance Criteria 
- [x] The workflow that vets-website uses to upload testing results to the bucket works without error

**Comment by mydesignrocks** [comment]
@CBonade validated his need
