### ISSUE TITLE
Internal Server errors in vets-api

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#28630]
There are a few recent 500 errors in vets-api:

http://sentry.vfs.va.gov/organizations/vsp/issues/44408/?environment=production&project=3&query=is%3Aunresolved+vaos&statsPeriod=14d

500 errors are a vets-api issue that we should be able to address, rather than VAMF issues.

**Comment by grossb1** [comment]
I was able to find the set of corresponding cloudwatch records, here is one to seems relevant:
```
18:29:00 web.1       | {
    "host": "eb96852ff88d",
    "application": "vets-api-server",
    "environment": "production",
    "timestamp": "2021-08-02T18:29:00.256393Z",
    "level": "info",
    "level_index": 2,
    "pid": 29,
    "thread": "puma threadpool 008",
    "duration_ms": 0.853973892,
    "duration": "0.854ms",
    "named_tags": {
        "request_id": "e2da248a-0e1d-4968-bb05-91b2e4e62bda",
        "remote_ip": "2607:fb90:ae5f:2ebf:3940:a21:0:4cf",
        "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1",
        "ref": "46b340cd1b7ba972e2f5a7b77abdfd391cf5e2e3",
        "csrf_token": "p8waicDh+0DAJeEnlAq3ZKJesiR7PHUf0CsXFHNOL7FPTkUWWP8v29r9UpLT/vNafkd5U29sF6U0M2HWKQRboQ=="
    },
    "name": "Rails",
    "message": "VAOS service call succeeded!",
    "payload": {
        "jti": "84e4a93f-6514-423b-8509-d64d9695ec00",
        "status": 204,
        "url": "(GET) https://internal-dsva-vagov-prod-fwdproxy-2075821597.us-gov-west-1.elb.amazonaws.com:4463/appointments/v1/patients/1016743798V090124/appointments/202107301930521001066900000000000000"
    }
}
```

**Comment by ajmagdub** [comment]
When VAMF would return an http status of 204, no content, the body returned was an empty string. The Vets API code would try to initialize an OpenStruct with that empty string which would cause an initialization error. Added code to catch that case and return an http status of 204 to the Vets Website.

@jbalboni would this cause any problems for VAOS web?

**Comment by ajmagdub** [comment]
Changed returned http status to Vets Website from 204, no content, to 404, not found.
