### ISSUE TITLE
Double Check diaryEntry Dates 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28632]
1 or 8 years ahead?

Reached out to Molly Gatty in Teams on 8/11 to ask

**Comment by kathleencrawford** [comment]
I can check that these dates were updated ...just need to confirm that this was done in staging/linktest?

**Comment by kathleencrawford** [comment]
As of 08/17 the dates have not been updated in linktest/staging.
