### ISSUE TITLE
Create notification for build failures in vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#28635]
While builds have seemed to be stable, nobody has really been monitoring closely. The assumption that silence means there's no problem is probably not enough confidence to launch on, so we should create a Slack notification/channel for when builds fail. There may be failures that are being wiped away by users rerunning jobs and there is no record a failure initially took place.

**Comment by CBonade** [comment]
This is merged into master!  Channel link is here: https://dsva.slack.com/archives/C02AG8UF95M

**Comment by pjhill** [comment]
Hooray notifications!
