### ISSUE TITLE
Update the DOMO 'End-To-End Testing' page with test selection data

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#28645]
Now that Cypress Test Selection is in place, we can report data regarding Cypress tests run on push (selected tests) and Cypress tests run on merge to master (all tests).

Create additional versions of the following graphs for 1) tests run on push, and 2) test run on merge to master:
- Number of Test Suite Executions
- Average Number of Individual Tests Passing, Pending, and Failing
- Average Test Suite Execution Time in Minutes

**Comment by holdenhinkle** [comment]
I ran the following query to clean up data on 8/12/2021:

```SQL
UPDATE `vsp-analytics-and-insights.vsp_testing_tools.cypress_test_suite_executions`
SET isMasterBuild=NULL, numContainers=NULL
WHERE DATE(start)='2021-08-12';
```

Setting `isMasterBuild` and `numContainers` was not completed until EOD on 8/12/21 so most of the data for those columns that date is wrong/`NULL`.

**Comment by holdenhinkle** [comment]
I created the following additional graphs:
- Number of Test Suite Executions: Master Build (commit to master), Branch Build (on push)
- Average Number of Individual Tests Passing, Pending, and Failing: Master Build (commit to master), Branch Build (on push)
- Average Test Suite Execution Time in Minutes: Master Build (commit to master), Branch Build (on push)
- Number of Containers Needed: All Builds, Master Build (commit to master), Branch Build (on push)

I also updated the query that generates the data for the 'Total Spec Files and Tests, Last 28 Days' graph so it only graphs data for tests run against the master brach:

```SQL
SELECT
    DATE(start) AS date,
    MAX(suites) AS num_specs,
    MAX(tests) AS num_tests
FROM `vsp-analytics-and-insights.vsp_testing_tools.cypress_test_suite_executions`
WHERE DATE(start)<='2021-08-21' OR isMasterBuild=true
GROUP BY date
ORDER BY date DESC;
```

**Comment by pjhill** [comment]
Looking good -- thanks!
