### ISSUE TITLE
Create json schema for FSR submission payload

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#28646]
## Issue Description
_When an invalid request is made to FSR, we do not receive a response explaining which properties of the payload were invalid.
Create a JSON schema that matches the DMC’s API documentation so we can later (next ticket) validate the requests and render useful error messages (for debugging and testing)._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@ScottyRJames can you validate this one?

**Comment by ScottyRJames** [comment]
JSON schema has already been created within the `vets-json-schema` repo [here](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/5655-schema.json)

This is already being used to validate requests that are sent from the FE but created a new ticket [#35719](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35719) to capture validating DMC requests from the API
