### ISSUE TITLE
Add is_master_build and num_containers columns to cypress_test_suite_executions BigQuery table

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#28644]
Add `is_master_build` and `num_containers` columns to `cypress_test_suite_executions` BigQuery table.

This will allow us to report data regarding Cypress tests run on push (selected tests) and Cypress tests run on merge to master (all tests) and the average of the two in DOMO.

**Comment by holdenhinkle** [comment]
PR for `vets-website` part - https://github.com/department-of-veterans-affairs/vets-website/pull/18219

PR for `testing-tools-team-dashboard-data` part - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/51

**Comment by holdenhinkle** [comment]
Added columns to `cypress_test_suite_executions` BigQuery table.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/c7f50610-0eb9-4e9f-9e59-168222f63ea5)

**Comment by holdenhinkle** [comment]
I approved and merged the PR in `testing-tools-team-dashboard-data`.

Circle back and delete the following, which is for debugging this when it's checked out in the `testing-reports` job in GHA.

```
// to be deleted
const MASTER_BUILD = process.env.MASTER_BUILD;
const NUM_CONTAINERS = process.env.NUM_CONTAINERS;
console.log('MASTER_BUILD: ', MASTER_BUILD);
console.log('NUM_CONTAINERS: ', NUM_CONTAINERS);
```

**Comment by holdenhinkle** [comment]
It's working. See the `Testing Reports`,  job, `Create report and post results to BigQuery` step:
https://github.com/department-of-veterans-affairs/vets-website/actions/runs/1124423064

Pic of values being logged by testing-tools-team-dashboard-data in GHA:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/544f8ea4-0c52-4f25-a614-4fb66c7760ea)

Pic of test results data pushed to BQ:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/7abc3be1-edb4-4b94-8b31-3f6539d6b2d8)

**Comment by holdenhinkle** [comment]
PR is in review - https://github.com/department-of-veterans-affairs/vets-website/pull/18219

Done :-)

**Comment by pjhill** [comment]
Nice -- detailed metric collection on a new workflow!
