### ISSUE TITLE
[User flows and navigating] Static content pages and entry points (including CTAs) aren't updated to support a tool or feature launch. (03.07.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28655]
#### VFS team name
Claims & Appeals

#### VFS product name
Higher Level Review

#### Point of Contact/Reviewers
Mikki Northuis

---

### Platform Issue
Static content pages and entry points (including CTAs) aren't updated to support a tool or feature launch.

### Issue Details
Incorrect URL.   The destination URL (https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction) for the left nav link for "Request a  Higher-Level Review" is incorrect. Incoming links should use the canonical form URL , and not link to a specific path/page within the form flow.  The form flow should resolve the canonical URL to the proper start page. 

### Supporting Guidance
[03.07.1](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

---

### Platform Recommendation
Update the destination URL to the canonical URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/

### VFS Team Tasks to Complete

- [x] Comment on the ticket if there are questions or concerns
- [x] VFS team closes the ticket when the issue has been resolved

**Comment by Mottie** [comment]
I believe this ticket will need to be directed to the public websites team. I will notify them in Slack

**Comment by Mottie** [comment]
This ticket is regarding the start button here, I think - https://staging.va.gov/decision-reviews/higher-level-review/#how-do-i-request-a-higher-leve

Ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/28656 - may be regarding the side nav on the same page?

**Comment by shiragoodman** [comment]
@Mottie @brianalloyd let us know if this is actually Public Websites work. We need to ensure the labels get updated appropriately.

**Comment by brianalloyd** [comment]
@shiragoodman PW team is scrubbing in on this, I'll add our label in support.

**Comment by brianalloyd** [comment]
This work was completed via ticket #28687.  Closing the ticket in support but please advise if any questions exist.

**Comment by shiragoodman** [comment]
adding labels so ticket is consistent with post-pilot process

**Comment by shiragoodman** [comment]
removed the Claims & Appeals team label so CC-Dashboard is correct
