### ISSUE TITLE
serviceType is getting dropped when GETing appointment requests

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#28652]
When I look at https://veteran.apps-staging.va.gov/vaos/v1/patients/1012846043V576341/appointments/42458 (jacqueline.morgan@id.me), I see a `serviceType` field populated, but when I look at that same request in vets-api, that field is null.

![Screen Shot 2021-08-12 at 11.10.23 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/da1867b0-31b4-4772-810d-dd8c4d44828d)

![Screen Shot 2021-08-12 at 11.14.36 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/f148f660-eb32-4c3e-a611-17368cf145cc)

**Comment by ajmagdub** [comment]
On re-checking appointment 42458 on the VAOS test page, the ServiceType field was not longer there (the reason field was also absent). Checked another appointment, 33052, that was verified to have a ServiceType field and the field did come through vets-api, which implies vets-api is mapping ServiceType. Assume that the appointment changed between checking it on the VAOS test page and viewing it through vets-api. 

A JIRA ticket was open to address the changing data, which makes our test difficult.

Below is a screen capture of appointment 42458 showing the changed appointment data (missing ServiceType, and reason):

![serviceType.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/c6a41781-ef25-4f00-b5b5-0b9ad5cedbc5)
