### ISSUE TITLE
Create Tilt.dev Walkthrough Confluence Document

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#28665]
## Issue Description
We need tweaked walkthrough documents to show the tools selected for the development of the Kubernetes spike in action.

---
## Tasks
- [x] Create a walkthrough document in Confluence for Tilt.dev

## Acceptance Criteria
- [x] Walkthrough document exists [WIP](https://vfs.atlassian.net/wiki/spaces/OT/pages/1828814849/WIP+Tilt+Walkthrough)

**Comment by jhouse-solvd** [comment]
We decided to revisit this after we get some feedback from developers. 

Closing.
