### ISSUE TITLE
[Parameter Store] Update documentation for creating parameters

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#28666]
## Description
Update the Confluence documentation on how to create new values in parameter store and what to do if they previously existed in credstash.  Also to reach out to the OPS team if they dont have proper permissions to the path where their parameter needs to live.

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/19849

---
## Tasks
- [x] update documentation explaining how to create parameters

## Acceptance Criteria 
- [x] people understand the process of creating new parameters and what needs to happen if they previously existed in credstash

**Comment by jhouse-solvd** [comment]
The doc is looking good. 

Closing.
