### ISSUE TITLE
Consider removing VA home loan help option from Facility Locator

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#28662]
## Description

As a Veteran, I can find a VA home loan facility using the Facility Locator, OR I am not given the option to search for a home loan facility.

## Details

There are only 7 centers that offer help for VA Home Loans. They are listed on https://www.benefits.va.gov/HOMELOANS/contact_rlc_info.asp:

Atlanta
Cleveland
Denver
Houston
Phoenix
Roanoke
St. Paul
St. Petersburg

Since our Facility Locator search is limited to 500 mile radius, it is often hard if not impossible for veterans to find  a VA home loan facility with this tool. 

See Slack [thread](https://dsva.slack.com/archives/C0FQSS30V/p1628784374252500) for more details.

## Options:

1. Allow VA home loan search to cover a wider radius
2. Remove the VA home loan option from the faciliity locator
3. Redirect veterans who choose this option to a static page with home loan info

**Comment by mmiddaugh** [comment]
This will be vetted as part of [Region Offices initiative](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices)
