### ISSUE TITLE
Create DevSpace.sh Walkthrough Confluence Document

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#28664]
## Issue Description
We need tweaked walkthrough documents to show the tools selected for the development of the Kubernetes spike in action.

---
## Tasks
- [x] Create a walkthrough document in Confluence for DevSpace.sh

## Acceptance Criteria
- [x] Walkthrough document exists

**Comment by jbritt1** [comment]
Confluence doc: https://vfs.atlassian.net/wiki/spaces/OT/pages/1815150766/DevSpace+Walkthrough

**Comment by jhouse-solvd** [comment]
This is good to go! 

Closing.
