### ISSUE TITLE
Create Garden.io Walkthrough Confluence Document

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#28663]
## Issue Description
We need tweaked walkthrough documents to show the tools selected for the development of the Kubernetes spike in action.

---
## Tasks
- [x] Create a walkthrough document in Confluence for Garden.io

## Acceptance Criteria
- [x] Walkthrough document exists

**Comment by jbritt1** [comment]
Confluence doc: https://vfs.atlassian.net/wiki/spaces/OT/pages/1814528001/Garden+Walkthrough

**Comment by jhouse-solvd** [comment]
This is good to go! 

Closing.
