### ISSUE TITLE
Access for Bradley Conley (@bradl3yC)

### ISSUE THREAD

**Issue by bradl3yC** [department-of-veterans-affairs/va.gov-team#2866]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.

**Mary O'Toole**

- Please provide your name.

**Bradley Conley**

- Please provide the name of your team, your role on that team, and the name of the company you work for.

**`vsa-public-websites`, Senior Frontend Engineer, GovernmentCIO**

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDxwnUhsEwzVi3cfoTUlnf3hIB2sujSIR6b/VcgHdolovBnfCn6AGiVInGY5t0Sne+liocjzRfpZofj4aeO8dQn5zlClhay045g3KNYzYF8yBDnF2Sv5NzQda1r4/o1WHz/m3KQekiDYiqhfC/sJAfca4IjyVjrg/dh7WfPP5N0u6KC6kH8E6Zp0L6rSUWI2HZMczJBlP2oVvxqSPljQbRu1ox0vg/SPO/+DgHMtdhhzkYQEeAblZwWsZue7EnTLd0BzXnJoP5PTTmnnWoBXXDKCKKa4ZvcGy88Oq7/vbjd/PM1CT1pkzdErfERE8LEO+/s3q6R+6eyEftQNXUOyybX6yZmLwUYoYvwqMI+4WU0/UCqtlPy7wI07tRBIyTwaWsOF9KlETdL4CP3yQUYPc3SjOw9wWipU924dPgexnGLsWEcdjN0xTHiOsewW52yPcNaGX6r+rZ6LKjIIvwT8ZBwjp0C/X9i2+PUqd0VznBkel2JCMrLBQMrKRkGnJTq3ayPtSLKhuvg1hZA6P8tFGstzxtkYNTzmf4ogp02SEHgO9+B0bVUbA+aFO0uSvPIf4e06Igb1mNXHaTbEk6T76q6advBFS+ZdSIhU9jazqZ9OJDps+uFsCXoYwc1Vq95OjCpFm8u6aNflPCp7qP8WabVpIjAOfOohCvy0k3ogsT7iw== brad.conl3y@gmail.com

```

- [Grant AWS Console access?]

**YES**

**Comment by bradl3yC** [comment]
@department-of-veterans-affairs/vsp-operations happy to provide additional information if necessary :)

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Bradley Conley

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for both SOCKS and AWS.

**Comment by jbritt1** [comment]
First time login credentials provided to user via Slack.
