### ISSUE TITLE
Omit "Introduction" from left nav link and page button (Request for Higher Level Review)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28687]
## Issue Description
_The claims an appeals team had a staging review for our Higher-Level Review form. This ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/28655 - indicates that the "Request a Higher-Level Review" button on this page - https://staging.va.gov/decision-reviews/higher-level-review/#how-do-i-request-a-higher-leve - should not include /introduction in the URL._

Reference Slack Convo: https://dsva.slack.com/archives/C52CL1PKQ/p1628800592195100 

Reference Staging Review Tickets:
[#28655](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28655)

[#28656](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28656)

## Front end tasks
- Remove "Introduction" from both the left nav link and the on page button.

## Acceptance Criteria
- [x] Introduction is removed from both left nav link and page button as described on the above tickets. 
- [x] Link PR to above tickets to indicate work is being complete 
- [x] Once this ticket is closed, PM will link in Claims & Appeals team into desired outcome and completion of work. 

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Rleahy22** [comment]
@brianalloyd We base the `href` on the path that is provided: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/navigation/sidebar_nav.drupal.liquid#L60. Should this change occur in the cms for that specific link?

**Comment by brianalloyd** [comment]
@Rleahy22 good question. Looping in @kevwalsh and @RLHecht in support.

**Comment by RLHecht** [comment]
I can remove that on the Drupal side @Rleahy22

**Comment by RLHecht** [comment]
The /introduction has been removed from both the left nav and the CTA button on the HIgher-Level Reviews page.

**Comment by Rleahy22** [comment]
This looks good on the staging urls mentioned in the description as of 8/16.

**Comment by brianalloyd** [comment]
Thanks for the assistance on this effort @RLHecht and @Rleahy22.  Looping in @vhenry07 and closing ticket in support.
