### ISSUE TITLE
GIDS: Add feature flag support

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28695]
As a developer, I need to add feature flag support to GIDS so that new functionality that is going through UAT in staging is not available in production.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The "SchoolRating" file type on the GIDS dashboard leverages the "gibct_school_ratings" feature flag.
    a. When the feature flag is on, the "SchoolRating" file type is displayed.
    b. When the feature flag is off, the "SchoolRating" file type is not displayed.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/852

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/852

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2115&group_by=cases:section_id&group_order=asc
