### ISSUE TITLE
EBS volume storage is being absorbed at an alarming rate

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#28694]
## Issue Description
EBS volume storage is being absorbed at an alarming rate. Please see the Slack thread for more details: https://dsva.slack.com/archives/CJYRZK2HH/p1628858568265500

---
## Tasks
- [x] Need to figure out what we can do to adjust before hitting out 80TB service limit for EBS volumes

## Acceptance Criteria
- [x] Adjustments made to prevent us reaching our EBS volume storage limit via automated solution(s).

**Comment by jbritt1** [comment]
Deleted ~200 available state gha-on-demand-runner volumes manually for now, but this is just a bandaid until we get a more permanent solution in place.

**Comment by jhouse-solvd** [comment]
@jbritt1 - Any estimate on how long (time) that gives us?

**Comment by jbritt1** [comment]
> @jbritt1 - Any estimate on how long (time) that gives us?

In conjunction with @mleclerc00's [work to reduce the EKS node size](https://dsva.slack.com/archives/CJYRZK2HH/p1628870079277600) it buys us some time. However, we should not neglect this for too long as once the limit is hit it will break all future deploys until resolved. This included production.

**Comment by jhouse-solvd** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28707

**Comment by jhouse-solvd** [comment]
@dginther to validate and close out

**Comment by dginther** [comment]
I updated the AMI creation for GHA runners to change 'destroy_on_termination' to true for future GHA runners. This was a major cause of the escalation.
