### ISSUE TITLE
[MCP] VSA-QA Test Plan

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#28690]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md
- Product/Feature Epic: \[https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26309]
\[https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26311]
- Product/Feature Copy deck(s): \[https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140826057/simulate/sitemap?mode=i]
- Product/Feature Design prototypes: \[https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140826057/simulate/sitemap?mode=i]

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: 
Content/IA: 
Front-end: 
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \[https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B024225EB-16E9-4A99-9D9E-078AD5935E07%7D&file=MCP%20Use%20Cases.xlsx&action=default&mobileredirect=true&cid=206e3a34-9f6d-4c8f-8154-be1067c6ba03]

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@LindaLi123 , re. the [Use-Cases spreadsheet](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B024225EB-16E9-4A99-9D9E-078AD5935E07%7D&file=MCP%20Use%20Cases.xlsx&action=default&mobileredirect=true&cid=206e3a34-9f6d-4c8f-8154-be1067c6ba03%5D)...

Beyond row 11's "[reasons TBD]", is everything else final?  I see a couple Comments [on rows 2 & 3] that seem to indicate otherwise.

Pls. let me know.  Thx much!

**Comment by tlei123** [comment]
@LinnJS @craigwheeler , once you have automated tests\*, pls. tag me here in case I have bandwidth to get them integrated w/ TestRail.

Thx much!  :)

\* I'm assuming they'd be inside \src\applications\medical-copays, but if they already exist elsewhere just let me know.

**Comment by tlei123** [comment]
@LinnJS @craigwheeler , I checked Staging over the weekend but ran into some anomalies that suggested there might still be some work-in-progress.

Here are some questions before i start actual test-runs...

- (1) Re. **Active-bill** [test-user 81] **Detail** page:
  - (1a) will we have destinations for the **Learn how** & **Request help** cta-links?
  - (1b) has the **Your charges** table been dropped?
- (2) Will the currently-displayed **404-error** alerts be fixed [replaced w/ the expected alerts?
  - (2a) **No-history** [test-user 81] - expected No-history alert
  - (2b) **Not-enrolled-in-health-care** [test-user 87] - expected Not-enrolled alert
- (3) Do we have a correct test-user for **Deceased** test-case?  Neither test-user 228 nor 90 is displaying deceased alert.

Please let me know.  Thanks much!

cc @rileyorr [in case you have some insight into the above]

**Comment by rileyorr** [comment]
Hi @tlei123! Hope you had a great weekend 😄 I do have some insight into a couple of your questions:

> will we have destinations for the Learn how & Request help cta-links?

For the tool's MVP release, the 'Learn how' & 'Request help' CTA links should be anchor tags directing towards the 'How do I pay my VA copay bill?' and 'How do I get financial help for my copays?'. Once we release the combined FSR, the 'Request help' link will lead to the online FSR form. 

> has the Your charges table been dropped?

Correct! The charges table is no longer part of the MVP.

**Comment by craigwheeler** [comment]
hi @tlei123 👋 ..  FE is waiting for some BE changes from @LinnJS and @ScottyRJames to get the user data inline with the use cases that have been outlined after which ill be working on implementing the alerts for each case which should be completed during this sprint

**Comment by tlei123** [comment]
@denisecoveyduc , one test-case's runs now completed.  Here are interim QA-artifacts below [and in Staging Review ticket #32081's main description].  I'll run the rest of the cases once they're ready on Staging.

Defects logged so far: #33843, #33844, & #33846

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/2111)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_id=2939&group_order=asc&display_deleted_cases=0)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/284)
- [Partial Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/285)

cc @LinnJS @craigwheeler @ScottyRJames

**Comment by tlei123** [comment]
@denisecoveyduc , final test-runs [for Not enrolled in health care case] now completed.  Report-link below will also be in [Staging Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32081).

No-enrolled-in-health-care case runs all Passed.  Defects remain the same &mdash; all from other cases' test-runs.

- [Complete Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/286)
