### ISSUE TITLE
CT Redesign: #cautionary-information appended to url

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#28693]
## Steps to reproduce:
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/1000814
2. Select "View details below"
![Screen Shot 2021-08-13 at 7.25.05 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a97c4f89-b21e-4128-8686-b1bf2d40c4ca)
3. #cautionary-information gets added to the URL
![Screen Shot 2021-08-13 at 7.27.35 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cbc2b979-714b-4958-8572-cc115952cef5)

## Expected Results:

#cautionary-information should not be added to the URL and it should stay as https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/1000814

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18248
