### ISSUE TITLE
STEM AD: Store remaining entitlement on 10203 submission for use in automated denial job

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28697]
As a developer, I need to store the remaining entitlement on the submission of the 10203 application so that when the automated denial job processes, it does not need to make an EVSS call requesting that information once again.

## Assumptions:
1. This work is completed using feature flag: 'stem_automated_decision' (STEM AD: Create automated decision feature flag #13829).

## Acceptance Criteria:
1. On submission of the 10203 application, the remaining entitlement is persisted.
2. On execution of the STEM automated denial job, the remaining entitlement is used in place of the EVSS service.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7700
