### ISSUE TITLE
CT Redesign: Hide back to top button on mobile devices.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28702]
As a developer, I need to hide the profile page back to top button on mobile devices so that it does not take up extra screen real estate.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The breakpoint for mobile display is 481px ($small-screen).

## Acceptance Criteria
1. The back to top button is not displayed on all pages when the compare drawer is open.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18292

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/2119)

**Comment by delli-gatti-michael** [comment]
Testing complete
