### ISSUE TITLE
Task: Investigate setting up alerts to monitor for submission failures

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28700]
We need to find a way to setup alerts to monitor for submission failures. Perhaps a threshold or a percentage of a period of time could trigger an alert. Need to figure out the best platform to use for this alerting (Grafana/Prometheus, DataDog, etc.)

This is a followup task from the postmortem for the caregiver submission failure issue that occurred from Aug 10-12, 2021.

**Comment by tchrisdyer** [comment]
Based on a conversation with Demian Ginther and Jesse House on August 18, 2021, it sounds like the best course of action is:

* Near-term: Use our existing metrics in Promethes/Grafana to have Grafana send Slack Alerts
* Long-term: Log metrics to DataDog and use it to send Slack Alerts

**Comment by drorva** [comment]
@tchrisdyer do you have resources on your team to create the Grafana alerts and send them to slack?

**Comment by tchrisdyer** [comment]
@drorva at the moment we do not. We are currently without a frontend or backend developer on the team. Perhaps, I can figure out how to configure it. I believe we already have some metrics going into Prometheus.

**Comment by drorva** [comment]
I can try and help with that.
Do you know what's the endpoint that gets called when the form is submitted?

**Comment by tchrisdyer** [comment]
Hi @drorva , our end point is `/v0/caregivers_assistance_claims`

We also do have a dashboard in Grafana which reports on client failures, server failures and total failures. I'm trying to figure out a way to trigger off that (probably total failures). I assume client failures are failure between the front end and the vets API where as server failures are between the vets api and the CARMA or MPI systems but not quite sure. Our most recent issue was a failure between the client vets API (view in the dashboard back to last week to see the spike).
![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/d2389180-3e58-4b65-be83-c093de2f4325)

**Comment by drorva** [comment]
Yeah, I just noticed this dashboard.
If you change the time frame to 30 days, you will very clearly see the outage in there.
So, yes, the next steps are:
* `Figure out where to send notifications in slack
*  Set up notifications and test

**Comment by tchrisdyer** [comment]
Hi @drorva I've been looking at the Grafana dashboard for the 10-10cg and I think there are some issues with the numbers I'm seeing. The Submission successes and attempts don't seem to match what I see in Cloudwatch or in Google Analytics.

For example, on August 17, the data from each platform was:

| Platform | Attempts | Success  | Note |
|---|---|---|---|
|Google Analytics | 193 | 188| Not UTC time |
|Cloudwatch | 216 | 207 | UTC time |
|Grafana | 17 | 95 | UTC time |

It looks like we're going to have to figure out if it is an issue with the dashboard setup or an issue with the metrics logging.

**Comment by drorva** [comment]
yeah, these number don't add up, but at this point, I'm just trying to get the alerting to work correctly. 
Even just looking at the numbers in grafana, how can success be larger than attempts?

**Comment by tchrisdyer** [comment]
It looks like there is a working prototype in ticket #29154.

**Comment by tchrisdyer** [comment]
Will close this ticket as a research ticket and create a new one to adapt the prototype.

**Comment by SKasimow** [comment]
@dillo I came across this while looking for background on error alerts; thought it would be one of the items we can talk thru Fri :)
