### ISSUE TITLE
Task: When reintroducing the 10-10CG checkbox fix, create better testing and validation on the submission for the FE to ensure that the structure is not broken

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28703]
When reintroducing the 10-10CG checkbox fix, create better testing and validation on the submission for the FE to ensure that the structure is not broken

## Expected Behavior
In #28237, we fixed a bug to require the checkbox to be checked before submission. But, there are variety of scenarios that require different combinations of boxes to checked before the submission can be completed. (See table below)

## Acceptance Criteria
- [ ] Confirm whether there's adequate FE validation to enforce checkbox requirements
- [ ] Add additional validation as needed to cover the different scenarios
- [ ] Test in local and staging before promoting to production

**Comment by tchrisdyer** [comment]
Hi @mdewey one thing to note on the 10-10CG form is that there can be up to four signature check boxes in a variety of combinations:

| Scenario | Veteran | Primary CG | Secondary CG 1 | Secondary CG 2 |
| --- | --- | --- | --- | --- |
| 1 | X | X | |
| 2 | X | X | X | |
| 3 | X | X | X | X |
| 4 | X | | X | |
| 5 | X | | X | X |

You can check out the screen flow on this [mural board for the 10-10CG](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1624656038538/fd2365daff7d967cc30d9b8c923238b3bd9848a2?sender=u940e2a1fd182724d6c379496) to see what it looks like.

**Comment by tchrisdyer** [comment]
Adding @charCodelet to the ticket. Lihan is still working on getting the lower environments to work so that we can test submissions to full test this before pushing to production.

**Comment by MickinSahni** [comment]
10/4 Standup: dealing with Id.me access issues. Coming back to this ticket after.

**Comment by hdjustice** [comment]
Closing ticket - Test cases/use cases can take these validation scenarios into account in our next QA session for 10-10CG.
