### ISSUE TITLE
List of conditions - 526

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#28712]
## Issue Description
During usability testing, users were confused by list of conditions. More research into how many conditions are typical.

We would like at least 1,000 users sampled to see how many conditions they have per submission.

Within that, it would be good to know:
- How many are BDD vs. 526?
- Are there any commonalities in the conditions entered? (i.e. are there a high level of one type of condition entered?)
- Can we determine if these are OG claims vs. secondary claims?
---
## Tasks
- [x] Take a sample (maybe 1000) and see how many conditions were put in for each submission and perhaps we'll find an average

## Acceptance Criteria
- [x] Document list of of conditions. 
---

**Comment by annaswims** [comment]
Here's what I used to get the data.  There's no PII (just disability names) but I'm sharing it privately to be on the conservative side.
````ruby
qq = Form526Submission.where(workflow_complete: true, created_at: [1.week.ago..Time.now]).limit(1000)
CSV.open('tmp/disabilities.csv', 'wb') do |csv|
  csv<<  %w[total_disabilities, new_count, bdd, disabilities]
    qq.find_each do |fs|
    disabilities = fs.form.dig('form526', 'form526', 'disabilities')
    new_count = disabilities.reject {|dis| dis['disabilityActionType'] == 'INCREASE' }.count
    dis = disabilities.collect {|dis| [dis['disabilityActionType'], dis['name']] }
    csv << [disabilities.count, new_count, fs.bdd?, dis] 
  end
end
````

**Comment by chrvalla** [comment]
Quantitative analysis of 1000 users filing for BDD or original 526 claims. 
Link to findings in Github below. Ticket closed.

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/Sept-2021
