### ISSUE TITLE
Publish iterated standardized GTM tags documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28736]
## Product Outline
[Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics+-+WIP)

## High Level User Story/ies
As a VFS product manager, I want to Determine how to track the metrics so that I can Test & improve how Veterans can use my product.

As a Platform Analytics team member, I need to know how to share with VFS teams which metrics can be tracked.

## Hypothesis or Bet
If we update, iterate, & migrate Google Tag Manager documentation on which tags come out of the box to the Platform Website, then VFS teams will be able to create tagging requests easier and faster.

## OKR
OBJECTIVE 1: Info for all common VFS needs are findable in Platform Website
KR: 50% of VFS's analytics questions on Slack & Github are redirected to the Platform Website.
KR: Decrease Platform Analytics time spent on support questions by 50%.
KR: Increase engagement with Analytics documentation.

### What must be true in order for you to consider this epic complete? 
- [ ] Update, QA, and migrate general analytics operational documentation in Confluence
- [ ] Update, QA, and migrate general analytics VFS-facing documentation to the Platform Website

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by johnny-jesensky-adhoc** [comment]
This was an epic from 2021. There are no specific tasks or cards attached to this. After some review, the Platform Website has fairly robust documentation on tagging, and [GTM tags](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager).

Our team will be reviewing any needed updates to documentation on Google Analytics and Tracking as part of [this separate epic](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/53417).

Closing this out as part of backlog clean-up.

FYI [@davidconlon](https://github.com/davidconlon)
