### ISSUE TITLE
CT: Only display "approved" schools in the school locations section.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28731]
As a developer, I need to update the query for the display of suspended schools so that the institution are appropriately displayed in the comparison tool.

## Assumptions:
1. "approved" is a back-end calculated value based on the following:
```
    a. poo status (weams column n) is: APRVD _**or**_ SUSP
    b. applicable law code (weams column o) is:
        - not 'educational institution is not approved'
        - not 'educational institution is approved for chapter 31 only'
        - not blank
    c. One of the following must have a true value:
        - institution of higher learning indicator (weams column p)
        - ojt indicator (weams column q)
        - correspondence indicator (weams column r)
        - flight indicator (weams column s)
        - non college degree indicator (weams column t)
```

## Acceptance Criteria
1. Only institutions that are "approved" (Assumption 1) are displayed within the profile page school locations section.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/856

**Comment by delli-gatti-michael** [comment]
Testing complete
