### ISSUE TITLE
Access for Sonia Lee

### ISSUE THREAD

**Issue by soneslee** [department-of-veterans-affairs/va.gov-team#28733]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Sonia Lee
- Please Provide your email.
   > sonia.lee@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am part of the VA API UX team, currently assisting in transcript work for the Benefits & Appeals API team.

- Requesting SSH key authorization?
   > No, we don’t need socks proxy, just a limited AWS account with S3 and Transcribe access in iAM. Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1603395713414900

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > We need to access the transcription service to transcribe interviews that we conduct with non-Veteran users, and also to S3 buckets dvpuxresearchinput and dvpuxresearchoutput

**Comment by jbritt1** [comment]
### For AWS Access:

User: Sonia Lee
COR: Cecilia Lee
Approval needed: @mchelen-gov

**Comment by omgitsbillryan** [comment]
Is this access still needed? @jbritt1 is on PTO until 9/6. If any further assistance is needed, I can help.

**Comment by soneslee** [comment]
Hi @omgitsbillryan -- this request is not urgent, but I will be needing access for transcript work in the future. Thank you :)

**Comment by mchelen-gov** [comment]
access approved 👍

**Comment by omgitsbillryan** [comment]
AWS Access Granted.
