### ISSUE TITLE
Publish iterated GTM implementation & QA guide

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28737]
## Product Outline
[Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics+-+WIP)

## High Level User Story/ies
As a VFS FE dev, I need to Implement new metrics collection so that I can Accurately track the progress and results of my experiment

As a Platform Analytics team member, I need to know how to help VFS teams implement new metrics with Google Tag Manager.

## Hypothesis or Bet
If we update, iterate, & migrate GTM implementation and QA documenation to the Platform Website, then VFS teams can find, access, and understand how to build and QA tags on their products.

Make [this Github document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md) more robust and easier to read.

## OKR
OBJECTIVE 1: Info for all common VFS needs are findable in Platform Website
KR: 50% of VFS's analytics questions on Slack & Github are redirected to the Platform Website.
KR: Decrease Platform Analytics time spent on support questions by 50%.
KR: Increase engagement with Analytics documentation.

### What must be true in order for you to consider this epic complete? 
- [ ] Update, QA, and migrate general analytics operational documentation in Confluence
- [ ] Update, QA, and migrate general analytics VFS-facing documentation to the Platform Website

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by johnny-jesensky-adhoc** [comment]
All assigned issues to this are completed, marking this epic as _Done_.
