### ISSUE TITLE
Publish iterated Google Analytics training documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#28738]
## Product Outline
[Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics+-+WIP)

## High Level User Story/ies
As a VFS team member, I need to Explore out of box analytics - user interactions so that I can Report on previous success/failure with the product.

As a Platform Analytics team member, I need to know how to help VFS teams understand and access user interactions in Google Analytics.

## Hypothesis or Bet
If we update, iterate, & migrate GA training documentation to the Platform Website, then VFS teams can find, access, and understand how to navigate and read Google Analytics for their products.

## OKR
OBJECTIVE 1: Info for all common VFS needs are findable in Platform Website
KR: 50% of VFS's analytics questions on Slack & Github are redirected to the Platform Website.
KR: Decrease Platform Analytics time spent on support questions by 50%.
KR: Increase engagement with Analytics documentation.

### What must be true in order for you to consider this epic complete? 
- [ ] Update, QA, and migrate general analytics operational documentation in Confluence
- [ ] Update, QA, and migrate general analytics VFS-facing documentation to the Platform Website

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by johnny-jesensky-adhoc** [comment]
This was another epic from 2021. There are no specific tasks or cards attached to this. A major part of the GA4 migration will involve updating these documents on Google Analytics, however, that will be performed as part of [this separate epic](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/53417), thus making this a duplicate.

Closing this out as part of backlog clean-up.

FYI [@davidconlon](https://github.com/davidconlon)
