### ISSUE TITLE
AWS Staging Alert Message Still Says 12-24 - VATS is now 36 months

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#28752]
1. In VATS for Fort Collins Amputation set VATS to Direct Scheduling to Yes Any and Request = Yes 36 months.
2. Login as John Morrison
3. Select Amputation, select Fort Collins. Select 'I need a different clinic'
4. Veteran is able to direct schedule Amputation because VATS is set to Yes any veteran. and he has past appointments in an Amputation Clinic within last 24 mos.
5. The alert message when veteran selects 'I need a different clinic' is wrong. The message says veteran hasn't visited in last 12-24 months.  
6. Alert message says:  We couldn’t find a recent appointment at this location.   You need to have visited this facility within the past 12-24 months for amputation care to request an appointment for this type of care.

The veteran has several past appointments, it just that all of them are outside the 36 direct scheduling criteria.    
Ftc Amputation 04/27/2020@09:00  Cancelled By Patient
Ftc Amputation            08/13/2018@08:00      Act Req/Checked Out   14:29
Ftc Amputation            08/14/2018@08:00      Act Req/Checked Out   14:32
Ftc Amputation            08/20/2018@08:00     No Action Taken

**Comment by jbalboni** [comment]
I think I noted this as a bug in one of the other tickets, but it looks like it got retested and closed. There's one spot where the app still uses "12-24" and it should never show that.

**Comment by laurenernest** [comment]
@marcynadeau ready for you to retest

**Comment by beth-wodzinski** [comment]
The message now says 36 months in this scenario. Thumbs up.
