### ISSUE TITLE
AWS Staging:  Select Current Date for Appt Date, Earliest We Can Schedule Message is Wrong

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#28753]
1.  in VATS set up Optometry (actually any type of care where veteran has had past appointments).  Direct Scheduling = Yes
2.  Log in as Judy Morrison or John Morrison
3. Select Eye, Select Optometry, Select Cheyenne VAMC
4.  For "Choose a Date and Time for you Appointment enter the current date. Select continue.
5.  Message displays above the calendar that says:  The earliest we can schedule your appointment is current date at XXX (time zone).  
The problem is that VAOS won't allow veteran to schedule on the current date and time as indicated above.  
6.  In the screen shot below the current date is 8/126/2021.![EarliestDate.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/21f57863-9ecc-4931-ab68-7405a0cc86b2)

**Comment by jbalboni** [comment]
It looks like we removed the bad display logic for this alert, but we didn't remove the incorrect date when the alert is shown in order to tell the user about urgent care

**Comment by laurenernest** [comment]
@marcynadeau @beth-wodzinski ready for retesting

**Comment by beth-wodzinski** [comment]
Today's date no longer appears as a valid selection, even if there are slots available today at the selected clinic. I tried this with a few different clinics and patients and this looks like it has been fixed.
