### ISSUE TITLE
Access for Cody Reinold

### ISSUE THREAD

**Issue by codyreinold-usds** [department-of-veterans-affairs/va.gov-team#28758]
# Description
- Please provide your name.
   > Cody Reinold
- Please Provide your email.
   > cody.reinold@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Federal Employee (VA / EOP); Identity Team Lead; Background Check Adjudicated

- Requesting SSH key authorization?
   > No 

- Grant AWS Console access?
  > YES
  - CloudWatch (log / alert review); Cognito

**Comment by jbritt1** [comment]
### For AWS Access:

User: Cody Reinold
COR: No COR or GTL provided (I assume due to being a federal employee?)
Approval needed: @mchelen-gov

**Comment by jbritt1** [comment]
Access granted and temporary credentials provided to user at this time.
