### ISSUE TITLE
[repo migration]: Research

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2877]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] UAT, remediation on documentation post-migration
- [x] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [ ] Merge va.gov-team PR
- [ ] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1TN_HVYQUo0T7qIA9VGMR8PxWgi7iJ2tMbbDwpmBggXw/edit#gid=0

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/2975

and

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19883

**Comment by thatmattjohnson** [comment]
PRs reviewed, comments submitted, both good to go.

I will need to perform manual remediation post migration for the following file that is not listed on the PR: https://github.com/department-of-veterans-affairs/va.gov-team/platform/research/discovery-sprints/USDS_Working_Backwards_Document_Template%5B1%5D.pdf

**Comment by thatmattjohnson** [comment]
UAT, remediation, and content SME notification completed 11/4/2019.  Holding open for final review to ensure all flagged documents were captured.
