### ISSUE TITLE
[COGNITION]: VAOS Scheduler - Can we consider marking up the cards as definition lists?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2878]
## Description

Looking at the cards on the review appointment and confirmed/pending appointments, I think these would benefit from being marked up as definition lists. It shouldn't affect the visual design, but would be more meaningful for assistive technology. Screenshots and code snippet attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Environment
* /vaos/new-appointment/review
* /vaos/appointments/confirmed
* /vaos/appointments/pending

## Possible Fixes (optional)

```html
<div>
  <h1 class="vads-u-font-size--h2" tabindex="-1" id="first-list-id">Review your appointment</h1>
  <dl aria-labelledby="first-list-id">
    <dt class="vaos-appts__block-label vads-u-margin-top--2">Type of care</dt>
    <dd>
      <span class="vads-u-padding-right--1">Mental health</span>
      <a href="/vaos/new-appointment">Edit</a>
    </dd>
    <dt class="vaos-appts__block-label vads-u-margin-top--2">Where</dt>
    <dd>
      <span class="vads-u-padding-right--1">CHYSHR-Cheyenne VA Medical Center</span>
      <a href="/vaos/new-appointment/va-facility">Edit</a>
  	  Cheyenne, WY
    </dd>
    <dt class="vaos-appts__block-label vads-u-margin-top--2">Purpose</dt>
    <dd>
      <span class="vads-u-padding-right--1">Routine/follow-up</span>
      <a href="/vaos/new-appointment/reason-appointment">Edit</a>
    </dd>
    <dt class="vaos-appts__block-label vads-u-margin-top--2">Type</dt>
    <dd>
      <span class="vads-u-padding-right--1">Phone call</span>
      <a href="/vaos/new-appointment/choose-visit-type">Edit</a>
    </dd>
  </dl>
</div>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2019-10-29 at 1 13 01 PM](https://user-images.githubusercontent.com/934879/67797183-62e44c00-fa4f-11e9-9cac-501955d5b6b0.png)

---
![Screen Shot 2019-10-29 at 1 19 32 PM](https://user-images.githubusercontent.com/934879/67797197-6972c380-fa4f-11e9-9242-f84a545400f5.png)

**Comment by jbalboni** [comment]
@1Copenut I marked these up this way based on some feedback from you saying that sub-headings worked better "since we have some 1:1 and some 1:many relationships." Is that no longer a good reason for making them headings? 

It's easy enough to change them, I don't any problem changing these to definition lists, I'm just hoping to get a better sense of when to use what markup, since I struggled with this when building a lot of these pages.

**Comment by jbalboni** [comment]
This was done as a part of other tickets. Closing.
