### ISSUE TITLE
Pundit gem update - research breaking change

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#28786]
## Issue Description
Pundit 2.1.1 may have introduced a [breaking change](https://github.com/varvet/pundit/blob/master/CHANGELOG.md#211-2021-08-13). The gem was [updated, but rolled back](https://github.com/department-of-veterans-affairs/vets-api/pull/7653) due to a possible breaking changes in the 2.1.1 release. There were quite a few pundit unauthorized errors found in Sentry for vets-api on 8/16, but this may have been a coincidence related to a [fraud issue](https://github.com/department-of-veterans-affairs/vets-api/pull/7646) with the direct deposit team.  

Although we do have test coverage, we should investigate if the breaking change applies to vets-api. We mostly use [headless policies](https://github.com/varvet/pundit#headless-policies) in vets-api 

---
## Tasks
- [x] Research breaking change
- [x] Verify is change is applicable to vets-api

**Comment by thilton-oddball** [comment]
From what I can tell, the update should not have had any effect on vets-api. It seems that any Sentry errors related to Pundit were happening before the update. They all appear to be instances of a user trying to access something they are unauthorized to access based on the Pundit policies in place (not LOA3, EDIPI not present, etc.).
