### ISSUE TITLE
Bypass Fast JSON API serializer for all V2 appointment endpoints

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#28797]
To minimize thrash, a temporary pass-through will be created that allows vets-api appointment endpoints to bypass the standard serialization logic used with Fast JSON API.  Once upstream VAMF dependencies have stabilized, the original serializer will be reinstated in the response flow.
In order to implement this, the response object will be manually created to match the existing Fast JSON API response object schema

- All V2 appointment end-points no longer use the Fast JSON API serializer.
- The response schema for all appointment end-points is the same as if it were serialized by Fast JSON API.

See #28798 for follow-up work.

**Comment by laurenernest** [comment]
@jbalboni any other validation you want to do for this one?

**Comment by jbalboni** [comment]
I validated it on a review instance, so I'm good.
