### ISSUE TITLE
[GHA On-demand self-hosted runners] Set up automated maintenance to make sure instances and resources are cleaned up properly

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28805]
## Description
Sometimes on-demand runners don't get destroyed at the end of a workflow. This means that we must clean them up manually to avoid unnecessary consumption of resources. 

---
## Tasks
- [x] Create a GHA workflow that terminates runners older than 1 day

## Acceptance Criteria 
- [x] On Demand runners older than a day are terminated automatically

**Comment by dginther** [comment]
Successful run! https://github.com/department-of-veterans-affairs/devops/runs/3383131478?check_suite_focus=true

**Comment by jhouse-solvd** [comment]
It looks like this is good to go. Please see the example linked in the previous comment. 

Closing.
