### ISSUE TITLE
[Alerting] Document alert routing flow from Datadog to Slack and PagerDuty 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#28804]
## Description
Currently, there are multiple methods of sending alerts. Let's document how we plan to consolidate these into a single path.  
---
## Tasks
- [X] Documentation needs to be written

## Acceptance Criteria 
- [x] Documentation of intended Alert flow is documented in Confluence

**Comment by dginther** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting

**Comment by jhouse-solvd** [comment]
Great work, Demian. 

This is now a living document. Please direct comments or questions to the document itself. 

Closing.
