### ISSUE TITLE
[repo-migration]: Comms/Product/Platform

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2880]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] UAT, remediation on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/16rNpkpd5n1-8aaczdde8nyzvaSvWqbikkUXb15pVRvE/edit#gid=686560927

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/2966

and

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19882

**Comment by thatmattjohnson** [comment]
PR review complete, ready to merge

**Comment by thatmattjohnson** [comment]
UAT complete, holding open pending notification to content SME
