### ISSUE TITLE
CHIP - Only allow e-check-ins from a list of pre-approved facilities + clinics

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#28824]
In order to prevent a Veteran from attempting to check in at a facility + clinic where e-check-in is not supported, CHIP must deny e-check-in requests to a f+c not on a pre-approved list.

For now, we're thinking this is a hard coded, yet update-able whitelist.

We'll know we're done when:
1. A user attempts to check in to a f+c where e-check-in is supported and receives a text with the link to check in
2. A user attempts to check in to a f+c where e-check-in is NOT supported and receives a text with a message telling them the feature is not supported.

**Comment by kjduensing** [comment]
Hi @snyderje. Was there any discussion around the wording for the "e-check-in is not supported at this location" text message?

**Comment by snyderje** [comment]
"We're sorry, mobile check-in is not yet available for this appointment. Please see the front desk to continue checking in."

**Comment by kjduensing** [comment]
This story was deemed high priority since it looks like we're set to go live on 8/26 and I'll be out from 8/18 - 8/23
