### ISSUE TITLE
Breaker diagnosis/troubleshooting

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#28822]
## Issue Description
A bug from a Microsoft API change was uncaught in Facility Locator, bubbled up to Sentry + Faraday and led to Faraday breakers kicking in. This interrupted service for community care searches. The breaker kicked in sooner than expected and needs to be evaluated for changes. 

Post Mortem[ here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-08-16-facility-locator-possible-DOS.md)

---
## Tasks
- [x] Troubleshoot breaker functionality
- [x] Identify and recommend optimal settings

**Comment by darkbushido** [comment]
We store a month of minutes in Redis, we only use the last 2 minutes to identify an "Outage"
The logic for how outages are identified and handled isn't Thread-Safe and a Slow request that is an error can re-trip the breaker even if it would be under the threshold.
I recommend replacing it with https://github.com/yammer/circuitbox
