### ISSUE TITLE
[SCREENREADER]: VAOS Scheduler - Consider updating the heading text for new Community Care appointments

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2882]
## Description

Screen readers are reading out the "1/2" on Community Care appointments as "one slash two". I'm proposing an improvement where we could keep that visual representation and offer screen readers a more clear understanding. Code snippet below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I should hear "one of two" instead of "one slash two" read aloud
* As a user, I should not see any visual change

## Environment
* /vaos/new-appointment/community-care-provider

## Possible Fixes (optional)

```html
<h1 class="vads-u-font-size--h2" tabindex="-1">
  Share your community care provider preferences
  <span aria-hidden="true">(1/2)</span>
  <span class="vads-u-visibility--screen-reader">one of two</span>
</h1>
```

## WCAG or Vendor Guidance (optional)

![Screen Shot 2019-10-29 at 1 31 31 PM](https://user-images.githubusercontent.com/934879/67797820-7ba13180-fa50-11e9-8cd5-db4491a380f9.png)

**Comment by jbalboni** [comment]
This texted is removed with some CC preferences design changes, will close when that work is merged.
