### ISSUE TITLE
CHIP - Remove clinic from the pre-approved list

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#28830]
In order to allow a team member to easily remove a clinic from the pre-approved list, CHIP must provide a `DELETE` endpoint which will remove a single clinic from the list

We'll know it's done when:
1. A user can call `DELETE /clinics/clinicIEN123`, then call `GET /clinics` and see that the clinicIEN passed to the delete calls is no longer in the whitelist

**Comment by aschulhof** [comment]
Duplicate of https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/58
