### ISSUE TITLE
[FE] Remove the Add functionality for DD

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2883]
## FE work

We need to remove the "Add" functionality in the direct deposit section. Users should only be able to "edit" their existing information. 

![Profile with direct deposit_Fields blank](https://user-images.githubusercontent.com/34068740/67804597-a2b62e00-fa65-11e9-8499-07ba029286da.png)

## Definition of Done

- [x] Add functionality has been removed 
- [ ] Team member has been assigned by developer to validate and test this feature.
- [ ] This ticket can be closed.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss please add any more information to this ticket that may be critical to know for the FE engineer to be able complete this work. 


@erikphansen please size this work appropriately for the work that is needed.

**Comment by erikphansen** [comment]
switched from a 1 to 2 since there is a small bit of unknown here. but it should be pretty straightforward

**Comment by Justin-Pickett** [comment]
@erikphansen okay thanks for the clarification.

**Comment by Samara-Strauss** [comment]
I added a screenshot to the top comment to clarify what we're talking about, but I don't think any other context is needed. Let me know if you have questions, @erikphansen.

**Comment by Samara-Strauss** [comment]
@erikphansen Idk that we really need to account for this use case at all since people should be set up for direct deposit when they complete their 526, and since they need to otherwise switch forms of compensation via paper. I think we can feel OK about removing this capability without compromising the user experience.

**Comment by lkoenigsberg** [comment]
Any update on the progress of this work and the likelihood we will complete it within the scope of sprint 7, ending tomorrow (11/5)?

**Comment by Justin-Pickett** [comment]
@lkoenigsberg this is completed by @erikphansen but we are waiting for the PR to be approved.
