### ISSUE TITLE
[KEYBOARD]: VAOS Scheduler - Can we manage focus better when users add another Community Care provider?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2884]
## Description

I'd like to improve the focus management when users add two or more Community Care providers. This may be a forms issue, but opening it here for a first pass. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* Focus should follow the screenshot attached below when users add or remove additional Community Care Providers.

## WCAG or Vendor Guidance (optional)

* [Focus Order: Understanding SC 2.4.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html)

## Screenshots or Trace Logs

![Screen Shot 2019-10-29 at 1 33 03 PM](https://user-images.githubusercontent.com/934879/67798307-421cf600-fa51-11e9-9fc5-782c8776124f.png)

**Comment by jbalboni** [comment]
I'm going to close this, because we removed the multiple provider UI in favor of just one provider.
