### ISSUE TITLE
Midpoint Review [Healthcare Experience, Check-in Phase 2]

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#28859]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Using the Slack Workflow ([User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)), notify Collaboration Cycle team of this Github ticket in #vfs-platform-support.
- [x] Platform: Schedule meeting with Collaboration Cycle reviewers and VFS team attendees (listed below).
- [x] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure Collaboration Cycle reviewers have appropriate access to secured applications.
- [x] Platform: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [x] VFS: Respond to feedback tickets.
- [x] Platform: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [x] VFS: Close this ticket when the review is complete.

#### Has your team met with the Sitewide Content team for content support? 
- [ ] Yes*
- [x] No

\*If yes, please be sure to include any relevant content artifacts.

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Prototype and Mockups](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/DP9D30k/play)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/Phase%202.md)
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/research-plan.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review

## Scheduling
Would you like this review to be asynchronous? Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No
 
### Midpoint Reviews can only be scheduled on Monday, Tuesday, or Friday.

Please select your preferred time slot per the [Platform Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)<br>

**Date/time**
8/20/2021 2:00PM ET
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [REVIEW BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [REVIEW BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Meeting attendees from requesting team*
\*Only required for synchronous meetings.
- Product Manager (required): Corey Parker
- OCTO-DE Product lead (recommended): Patrick Bateman
- OCTO-DE Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Kristen McConnell, Mark Dewey, Dillo Raju, Stephen Barrs
- VFS Content, IA, accessibility, and QA specialists (if applicable): name(s)

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jparker0425** [comment]
@shiragoodman wanted to get this on the calendar to async review on Friday. We plan to be at office hours tomorrow as well. Will be adding artifacts to the ticket.

**Comment by shiragoodman** [comment]
@jparker0425 the async review has been scheduled for 8/20/21, meaning you will receive feedback by EOD. No meeting will be held. looking forward to seeing your updates at office hours!

**Comment by mnorthuis** [comment]
Hi @jparker0425!  I missed the design office hours and do have a couple of things I'm curious about - maybe you already have rationale, or maybe you plan to gather info in research, but wanted to put this out there.  

1) On the appointment list page, I'll be curious, in a scenario like this, how users respond to the order of the appointments listed and how easily they can find the one they need to check in to.  I wonder if the level of information and weight given to each appointment on the page needs to be the same if they can't interact with them (past appt, future appt).  Really just interested in how easily they can find the immediate appointment.  

2) I am curious about the link on this page once you have checked in for your appointment.  For those users that have multiple appointments in a day,  how often do users need to check in for another appointment versus how often do they just want to go back to see the other appointments?  I'm just wondering if a more generic link label to "go back to today's appointments" versus "go back to check in to another appointment"?  In addition, would it be helpful to have the link to go back if there is multiple appointments even if they can't interact with any of them currently. 

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/f30294ab-a519-4b86-84a6-0ae08654920b)

**Comment by jparker0425** [comment]
Hey @mnorthuis ! Thanks for the feedback, and great questions. I have provided answers below. Please let me know your thoughts. 

1. We have had a few usability session this week, and the response from most (if not all) have been that they really like seeing the list of appointments for the day consolidated to one screen.

Also, great point about the weight of how it is presented and how easily the immediate appointments can be found. One of the characteristics of available appointment(s) that can be checked into is that the "Check in now" button stand out more boldly to alert that it is in the appropriate time slot to check in. If an appointment on that list is outside of that time frame (> 30m before or >10m after the appointment start time), the "check in now" button will not show so there is no confusion.  It will note that in the details of the appointment. 

img width="296" alt="Screen Shot 2021-08-20 at 2 57 19 PM" src="https://user-images.githubusercontent.com/84734317/130281042-8d0d828f-fa09-4fae-aedb-b380d09604f8.png">


2. I do like the call out on the link to specify "today's" appointments. This may be something we can discuss post-usability because we have been getting feedback about and discussing how to handle if a large time-gap takes place between appointments (say a few hours). 

cc: @kristenmcconnell

**Comment by jparker0425** [comment]
Feedback from @joshkimux 

Feedback:
- If “Go to another appointment” is a link, it should be styled as a link instead of a secondary button
- For “Your Appointments” page cards, would the time and clinic be needed in combination to specify a unique appointment? If so, I would recommend annotating your wires or communicating to your developer that the time and clinic should be contained within one heading element instead of what their visual styling looks like ( h2 followed by a h3. )
- If a user can check in to two different appointments at any given time, we need to make sure that each “Check in now” button has a unique label. Your developer can handle that using an aria-label that contains  “Check in now” + “Title of the appointment” e.g. “Check in now to Clinic: Cardiology Specialty Red Clinic #4"
For the “Not sure who to check in with” section-- can a TTY (Telecommunications Relay Services for Deaf users) link be provided?

Questions:
- To confirm-- is “Check in now” submitting something to the system? In which case writing and styling it as a button is correct!

Minor recommendations:
- If y’all haven’t already, I’d recommend running this by Danielle for a content review. For example, on the first page, I wonder if more specific reasons can be provided to the user as to why their social security number is needed instead of simply “We need some information to check you in.”

**Comment by jparker0425** [comment]
Response from @kristenmcconnell to @joshkimux feedback above:
Feedback:
- Buttons versus links!!!! I guess that this instance is just navigation. The statuses on the resulting page will change when they get to it, but it isn't a direct result of clicking the "Go to another appointment" button. Would you say this is one of our "action links" or a regular old link?
- Time and clinic are probably needed in combination to truly know what you are checking in for. I will make a note for engineering.
- The user can only select "Check in now" for one appointment at a time, but you are correct that more than one button can appear on the "Your appointments" page at a time. Appointments are 15 minutes in length and the "Check in now" button will appear 30 minutes before and 10 minutes after. Depending upon a Veteran's schedule, more than one appointment could be eligible for check in. I will add a comment for engineering.
- I will take that as a note. We are discussing removing all phone numbers and just directing people to staff.

Questions:
- Yes, "Check in now" is submitting something. The status in Vista changes, so billing starts. The check-in status in the staff-facing app changes as well.

Minor recommendations:
- I have been talking to Danielle. We are verifying their identity off of that information. We have debated actually saying that or not.

**Comment by joshkimux** [comment]
For the first bullet on buttons vs. links-- I’d say that this would be a regular old link since it’s not starting a journey or flow! :smile:

**Comment by jparker0425** [comment]
@mdewey Above is the accessibility feedback from Josh (along with the responses Kristen replied with) and also feedback from @mnorthuis . 

Based on recommendations I would make changes to the following:
- Update the "Go to another appointment" link text to say "Back to today's appointments"
- @kristenmcconnell it looks like the wireframes have the time and clinic in a single heading already for each appointment card, @mdewey just need to confirm that is replicated on the FE. 
- Under the "Not sure who to check in with" section, I would remove the phone number and direct to staff member. I think this is going to be more clear and streamlined for a Veteran, especially if we do not know what phone number may actually be populating.

Let me know your thoughts and @kristenmcconnell please add any notes you may have as well! Thanks all.

**Comment by kristenmcconnell** [comment]
@jparker0425 - I agree about changing the link to "Back to today's appointments" I will update that in the wireframes when I incorporate the usability feedback. Also, we removed the phone number for the usability test and most participants didn't notice. I do want to go back and review the research results; a few participant did talk about phone numbers in certain instances. However, I think keeping it removed makes sense. 

@joshkimux On button vs. link, made it a link already for the usability test.

@mdewey 
- There were actually two items for you based on the accessibility feedback (the one mentioned above and another). In the design, time is an H2 and clinic is an H3. Attached is a screenshot of the Sketch page detailing everything.
<img width="933" alt="Screen Shot 2021-08-25 at 11 33 33 AM" src="https://user-images.githubusercontent.com/66287082/130820520-8e07c2dc-8373-4efc-bbd9-363726e61ec9.png">

**Comment by shiragoodman** [comment]
tracker is updated. thanks for the reminder @jparker0425

**Comment by jparker0425** [comment]
Thank you @shiragoodman !
