### ISSUE TITLE
CT Redesign: Ratings not displaying for CSU

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#28853]
Ratings are not displaying for the below

https://github.com/department-of-veterans-affairs/va.gov-team/issues/27359
AC 1: Ratings information is only displayed in the CT Sandbox in the following locations if an institution has five or more ratings available.
a. Search results cards
b. Profile page header
c. Profile page ratings section

## Steps to reproduce: 
1.  Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Search on Charleston Southern University
3. No ratings are displaying on search results card
4. Select school
5. Profile page displays, ratings don't show in the header or the ratings section

## Expected results:
Ratings should display

**Comment by dneel-bah** [comment]
Redesign profile matches CT classic profile.  Doing more research to identify compare page discrepancy.  Closing this as OBE.
