### ISSUE TITLE
[repo migration]: Design

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2885]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [ ] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1SEb5_9XTOiVz3D0niGxvDXQTQZmGvUnD3jqNLPKe42Y/edit#gid=1453189445

**Comment by billfienberg** [comment]
PRs to migrate file from `vets.gov-team` to `va.gov-team-sensitive`
`vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20048/files
`va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/21

PRs to migrate files from `vets.gov-team` to `va.gov-team`
`vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20049
`va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3837

**Comment by billfienberg** [comment]
I found four conflicting .md files in the migration plan.

The following two files are both competing to be readme.md in the platform/design/example-design-project folder.
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Design/Example%20Design%20Project/design/readme.md
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Design/Example%20Design%20Project/design/wireframes/readme.md

The following two files are both competing to be conversation-guide.md in the products/platform/documentation-site folder:
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Platform Support/research/documentation-research-round-2/conversation-guide.md
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Platform Support/research/documentation-research/conversation-guide.md

The following two files are both competing to be research-plan.md in the products/platform/documentation-site folder:
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Platform Support/research/documentation-research-round-2/research-plan.md
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Platform Support/research/documentation-research/research-plan.md

The following two files are both competing to be results-summary.md in the products/platform/documentation-site folder:
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Platform Support/research/documentation-research-round-2/results-summary.md
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Platform Support/research/documentation-research/results-summary.md

**Comment by thatmattjohnson** [comment]
Conflicts resolved in migration plan document.  Please advise whether script needs to be re-run prior to PR reviews.

**Comment by billfienberg** [comment]
One of the files included in the original `va.gov-team` PR was actually sensitive. I deleted the file, opened a new PR, closed the original PR, and deleted the original branch.

New `va.gov-team` PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3879

Since the sensitive file was a `.pdf` file, there were no changes to that file in the original `vets.gov-team` PR, and therefore, the original `vets.gov-team` PR doesn't need to be updated/replaced.

https://dsva.slack.com/archives/GQBPKKYQ2/p1575330445005000

**Comment by thatmattjohnson** [comment]
reviewed/merged sensitive PRs (#21, #20048). UAT completed for #21, #20048, #3879, #20049; all looks good. Closing this issue.
