### ISSUE TITLE
[repo migration]: Engineering

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2886]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1JUdlm9U3MWMOrXOvwRnK85MRUOjbIwRUC5f7EYWtwF0/edit?ts=5dced5b2#gid=1645070064

**Comment by billfienberg** [comment]
The following two PRs are ready for review. 

* `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20077
* `va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/28/

**Comment by thatmattjohnson** [comment]
both PRs reviewed/approved

**Comment by billfienberg** [comment]
PRs have been merged

**Comment by thatmattjohnson** [comment]
UAT completed; all looks good. Closing this issue.
