### ISSUE TITLE
Post-pilot enhancement: Create blank template for Staging Review issues

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#28867]
## Issue Description
In the [Staging Review pilot ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25763), Product Support identified a [series of enhancements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25762) that should be fixed prior to going live with the new process. This ticket will be for creating a blank github issue template that matches the format of the tickets created from the bulk upload process. If a collab cycle reviewer doesn't get their review in on time, or if a last minute issue is found, using the DraftingTemplate to then bulk upload would be inefficient. This is when the blank github template would be useful.

*Please refer to ticket #28861 as the template layout will be changing.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 can you link the new template here? feel free to close out once linked.

**Comment by allison0034** [comment]
[Collab cycle feedback staging template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md)
