### ISSUE TITLE
[repo migration]: Claims/Appeals

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2887]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/11MTTtgLStBsQZw0jEyXTcArQEq2hkTtusCytXCafJAI/edit#gid=960932556

**Comment by billfienberg** [comment]
PRs to migrate files from `vets.gov-team` to `va.gov-team`
* vets.gov-team: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20059
* va.gov-team: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3908

**Comment by thatmattjohnson** [comment]
PRs 3908 and 20059 reviewed/approved.

**Comment by thatmattjohnson** [comment]
UAT completed for merged PRs; all looks good. Closing this issue.
