### ISSUE TITLE
Extra spaces in input field invalidate search

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#28887]
## What happened?

Adding an extra space to the input field under "Community providers (in VA's network)" invalidates an otherwise valid entry.

![image](https://user-images.githubusercontent.com/81988788/129789316-0a2f5734-72f3-4703-ab8b-0de088d99135.png)

...and then either clicking, or tabbing to and tapping enter, on search:

![image](https://user-images.githubusercontent.com/81988788/129789360-f50dddf3-fdb2-4bf0-b8a6-66b44f2ccbb4.png)

## Steps to Reproduce
- URL: [Facility locator](http://2492c839193eaddc466a22129454f9f2.review.vetsgov-internal/find-locations)
- Test User: @nicko-amida 

New info surfaced during grooming discussion 12/13/21
- we determined the worst scenario is resolved - search can be initiated using keyboard (tab and enter commands). 
- **issue:** after making a selection from the dropdown/successful search, if the input field loses focus, then regains focus, the text in the field is no longer treated as a valid list selection
- this is caused by the logic we added previously to stop new searches from being initiated before an existing search process has completed. Need to add logic to ensure the delivery of search results is recognized as a successful search 

## Desired behavior

Adding an extra space at the end should not invalidate the search. Users should still be able to execute a search even if there is an extra space in the input field.

## Acceptance Criteria
- [ ] Search executes when there is a valid entry in the input field, regardless of extra spaces

**Comment by nicko-amida** [comment]
@gescobardev Here's the issue created from my comment on #26852. Here's what I think is going on really: after making a selection from the dropdown, if the input field loses focus, then regains focus, the text in the field is no longer treated as a valid list selection, just more generic input text - regardless of whether there's extra spaces.

**Comment by mmiddaugh** [comment]
Just validated this in product - screenshot doesn't show that there is a space in front of the "d" and "dentist" is not present as a valid search option
![image](https://user-images.githubusercontent.com/55411834/184225505-0f516ad2-3e02-45fe-9149-bc916abe0271.png)
 
Second screenshot with extra space removed 
![image](https://user-images.githubusercontent.com/55411834/184225589-909107ec-a7cd-46d0-b390-dc2ca44c05a8.png)

**Comment by laflannery** [comment]
Closing this ticket in favor of a more recent issue for the new iteration of the FL
