### ISSUE TITLE
[repo migration]: BAM, Disability, EVSS

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2888]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/14Z992z7FnqZv0PhJ4hEPG6rnxO77pGm3fSAZVEN-2t4/edit#gid=1968995813

**Comment by billfienberg** [comment]
The following files don't have file extensions, but seem to be using Markdown formatting. Is it same to add the `.md` file extension to all of these files?

* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Burials%20and%20memorials/Pre-Needs-Burial/Discovery/user-research-session-3
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Burials%20and%20memorials/Pre-Needs-Burial/Discovery/user-research-session-4
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Records/VA%20Documents%20and%20Letters/research/synthesis/debrief_letters_071417
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Records/Veteran%20Identification%20Card%20v2/Meetings/adhoc_mtg_12072107
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Records/Veteran%20Identification%20Card%20v2/Requirements/Alex_Questions

**Comment by billfienberg** [comment]
WIP PRs:
- `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20071
- `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/4053

**Comment by billfienberg** [comment]
Slack thread: https://dsva.slack.com/archives/GQBPKKYQ2/p1575906738000700

**Comment by thatmattjohnson** [comment]
#4053: all discrepancies reviewed and resolved in migration plan

**Comment by billfienberg** [comment]
This migration is two files away from being ready for review. I just need some guidance on how to resolve the two files that overwrote pre-existing files.

https://github.com/department-of-veterans-affairs/va.gov-team/pull/4053#issuecomment-563292475

**Comment by thatmattjohnson** [comment]
For the two files above: va.gov-team readmes for pre-need and pension are blank templates and should be overwritten by corresponding vets.gov-team files.

**Comment by billfienberg** [comment]
The following PRs have been updated, and are ready for review:
* https://github.com/department-of-veterans-affairs/va.gov-team/pull/4053
* https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20071

**Comment by thatmattjohnson** [comment]
both PRs reviewed/approved

**Comment by billfienberg** [comment]
PRs have been merged

**Comment by thatmattjohnson** [comment]
UAT completed for both PRs; all looks good. Closing this issue.
