### ISSUE TITLE
[Analytics] Validate and update all LGBT Care Coordinators to LGBTQ+ Care Coordinator Staff profiles [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#28889]
## Story
As a LGBTQ+ Coordinator I need my title and position to reflect the newest approved title representing LGBTQ+.

## GOAL
Update all know LGBTQ+ Coordinator staff profiles.

## TASK
Review and update all staff profiles for LGBTQ+ to the new acronym.
- [x] Review all VISN/Systems for LGBTQ+ staff profiles and update the titles as appropriate.

## Acceptance Criteria
- [x] All systems have been reviewed for LGBTQ+ coordinator staff profiles and they have been updated with new title.

**Comment by bcastoe** [comment]
I have reviewed all VISN(s) regarding LGBT staff profiles. (1) The completed finished VISN(s) are as follows: 1, 6, 8, 9, 10, 16, 19, 20, 21, and 22.  (2) VISN 12 will need to be re-visited/circle back as currently there are no LGBTQ+ pages. (3) VISN 5 will need to be re-visited/circle back as this visn is currently being cloned/scaffold. (4) there are some questions for the following VISNs 2, 4, 7, 12, 14, and 19 of which I have listed and provided in the channel. (5) moved to BLOCK as I will be on PTO.
