### ISSUE TITLE
CT Redesign: Search page content doc

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#28898]
As developer I need to create a content doc for the search page & search cards so the specifics of the page and cards are documented for posterity

* create content doc for search page (heading, tabs, filters)
* create content doc for search results cards (IHLs, OJT, VET TEC)

**Comment by amyknox** [comment]
@JenLJ 

Where needed, update Military Status / Spouse conditionals to improve the experience for individuals whose spouse died in the line of duty.

What’s your military status, update the conditional question that appears when spouse is selected to: Is your spouse currently on active duty?

**Comment by JenLJ** [comment]
Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/design/search-content-doc.md
