### ISSUE TITLE
[repo migration]: Comms/Programs Research

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2889]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1Kub8mStrLwlfl8ezUAh5sMQmveGtX2ySiN6UJ7gRMuo/edit#gid=1298625508

**Comment by billfienberg** [comment]
There are two files competing to be `https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/design/design-resources/background-from-va-partners/ve-products/surveys/contact-center-employee/readme.md`:
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Communications/Background info from VA partners/VE_products/surveys/contact-center-employee/readme.md
* https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Communications/Background info from VA partners/VE_products/surveys/contact-center-veteran/readme.md

**Comment by billfienberg** [comment]
PRs:
* `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20086
* `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/4407

**Comment by thatmattjohnson** [comment]
PR review/UAT completed; all looks good.  Closing this issue.
