### ISSUE TITLE
GIDS: Update logic for including ratings during version generation

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28902]
As a developer, I need to update the ratings data retrieval to only retrieve valid ratings so that the display of ratings information and the calculations accurately reflect the aggregate ratings.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Only GIDS "SchoolRating" data rows that contains a rating in at least one of the following categories are included during version generation:
    a. overall experience
    b. quality of classes
    c. online instruction
    d. job preparation
    e. gi bill support
    f. veteran community
    g. marketing practices

2. On the CT Redesign search results page:
    a. If the institution has the minimum number of ratings, the composite average is displayed on the card.
    b. If the institution does not have the minimum number of ratings, "Not yet rated by Veterans" is displayed (replacing current content "School rating: Not yet rated")

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG#/screens/296064743_Searchbyname_Desktop_4_refineopen)

**Comment by elder-joseph** [comment]
Associated PRs:

GIDS: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/859

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2165&group_by=cases:section_id&group_order=asc
