### ISSUE TITLE
[repo migration]: Declare Dependent

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2890]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [ ] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan here: https://docs.google.com/spreadsheets/d/10FeuMh03YsL0HoE4OqNQ1mJc6wuSb6Thv2A1fWfvSbY/edit#gid=1182547973

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/3495

and

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19982

**Comment by thatmattjohnson** [comment]
Reviewed and requested changes for #3495 and #19982.

**Comment by thatmattjohnson** [comment]
UAT:

#3495: completed, looks good.

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19982 is updated with the correct deprecation

**Comment by thatmattjohnson** [comment]
approved #19982

**Comment by thatmattjohnson** [comment]
UAT completed for #19982; all looks good.  Closing this issue.
