### ISSUE TITLE
Create accounts table stats

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#28911]
Several requests have been coming in around how many users we have for va.gov. The only way we can get this information within a reasonable amount of time is to query the accounts table. This can be accessed today through the rails console. We need a few reports to be generated and regularly posted somewhere. The first set of stats should be:

- How many total users does VA.gov know of
- How many DSlogon user accounts
- How many MHV user accounts
- How many id.me user accounts
- How many "other" user accounts

Depending on what data we store, it may also be optimal to be able to say "there are the numbers of each type of accounts that have logged in within the past year."

**Comment by joeniquette** [comment]
One suggestion of "where to send the reports" was to drop them in domo. I know nothing about how to get an integration with domo but its something we should look into.

**Comment by jscanish** [comment]
Talked with @joeniquette , @bosawt , and @bramleyjl . We all agreed that we don't currently have the stats we would need to generate this kind of report right now.

To that end, our first step will be collecting information. The plan right now is to create a new table for account login activity. The table will have some kind of foreign key linking it to the accounts table, as well as columns containing a datetime that would represent the last time a user logged in using id.me, dslogon, and mhv. Rows will be created/updated when a user successfully logs on, so an account can have exactly one corresponding login record.

**Comment by nsoutouras** [comment]
Job to generate stats was run today.  Need to set up dashboard.
