### ISSUE TITLE
Manual migration of accordions web components in content build - Sidebar Nav

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28922]
## Template changes

There are 9 template files in `content-build` that we're migrated from using the `usa-accordion` class to using the `<va-accordion>` and `<va-accordion-item>` Web Components in ticket #26280 with the exception of `Sidebar_Nav` which will need to be migrated when ready. 

Context: We expect that `sidebar_nav` templates won't be able to be migrated immediately - some work will need to happen to the accordion to allow the kind of styling variation that we see on those pages if we want to still call them accordions. Here is an example:

### sidebar nav accordion

![image](https://user-images.githubusercontent.com/2008881/124000050-0a81f200-d988-11eb-8661-5b86da546cb8.png)

This looks different than the [accordion defined in the design system](https://design.va.gov/components/accordions).

---

I expect that sidebar_nav templates won't be able to be migrated immediately - some work will need to happen to the accordion to allow the kind of styling variation that we see on those pages if we want to still call them accordions. Here is an example:

sidebar nav accordion
image

**Comment by Rleahy22** [comment]
From discussion in the linked PR, I think this implementation is good as it is, and should not move to `va-accordion`
