### ISSUE TITLE
[Design] Notification Preferences: Document concepts for A/B testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28927]
## Background
We had a few ideas for A/B testing within the design of the Notification Preferences feature. Our two main ideas are:

1. Use of warning icon on the Notification Preferences page and testing whether the presence of icons on every notification item would increase engagement vs not having the warning icons on each notification item (potential to release as part of mvp)
2. Use of modal or on-page alert to drive engagement with notification preferences (post-mvp)

This ticket is to capture the work to do a brief write up of the two proposed experiments, why we want to do them, what we would do, and how we would track the experiment via analytics, as well as links to mock-ups when/if available.

## Tasks
- [ ] Complete [GH page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/AB-testing-concepts.md) with A/B experiment outline

**Comment by andaleliz** [comment]
Per @ajakabcin we won't pursue A/B testing for this product.
