### ISSUE TITLE
[repo migration]: Teamsite

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2893]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [x] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/185olv0TwpVvqGPCRHGogqhGfjRfXJLarfIMbIq5ksW8/edit#gid=0

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/3348

It looks like there was already a file here for products/global/README.md -- this replaced it. Might need to be combined @thatmattjohnson ?

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19960

**Comment by thatmattjohnson** [comment]
I've updated the migration plan with the inclusion of a /teamsite subdirectory to avoid the conflict you pointed out. Both PRs will need to be updated accordingly.

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/3491

and

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19980

**Comment by thatmattjohnson** [comment]
#3491 approved; #19980 needs update to link but otherwise okay.

**Comment by johnpaulashenfelter** [comment]
@thatmattjohnson updated. looked like the file content also got clobbered.

**Comment by thatmattjohnson** [comment]
UAT:

#19980: **not completed -- no deprecation messaging appended to the following files:**
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Global/Teamsite/Teamsite.md
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Global/Teamsite/Readme.md

#3491: completed, looks good.

I don't see where file content has been corrupted post-migration -- could you point me to any issues you're seeing?

**Comment by johnpaulashenfelter** [comment]
The missing content was in the PR -- and now fixed in the PR. UAT happens *after* its merged -- hoping you can take a look _before_ its merged.

**Comment by johnpaulashenfelter** [comment]
In any case, the last commit updated the content I saw that was missing and all of the deprecation messages are in place. You can merge and UAT at will

**Comment by thatmattjohnson** [comment]
approved #19980

**Comment by thatmattjohnson** [comment]
UAT completed for #19980; looks good.

Closing this issue.
