### ISSUE TITLE
Tech debt: Update `data-homepage` and `EmergencyBanner` with better naming

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#28933]
# Description

For our `banners` template and the homepage, we are currently using the `EmergencyBanner` component. It's interface requires that we use data properties like `data-homepage-banner-content`. However, given that these banners are not exclusive to the homepage, this naming should be modified.

In fact, it'd be a good time to modify the entire name of `EmergencyBanner` to just `Banner`, too.

```liquid
    <div
      aria-label="{{ banner.title | escape }}"
      data-template="components/banners.drupal.liquid"
      data-homepage-banner-content="{{ banner.body.processed | escape }}"
      data-homepage-banner-title="{{ banner.title | escape }}"
      data-homepage-banner-type="{{ banner.fieldAlertType | formatAlertType }}"
      data-homepage-banner-visible="{{ isVisible }}"
      data-widget-type="banners"
      role="region"
    ></div>
```

https://github.com/department-of-veterans-affairs/content-build/pull/441/files#diff-6095e4530cba0140e29cf8c0af2eae7c1ec4057c97629446f1e0ba42471e5fd8R10

## Acceptance Criteria

- [x] Update data-homepage attributes to data-banner (or a better name).
- [x] Update `EmergencyBanner` to `Banner`.

**Comment by brianalloyd** [comment]
Completed, closing in support.
