### ISSUE TITLE
[repo migration]: Facilities Locator

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2894]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1ZaFspRIijqrZ11D1wyM91Xu6H8StQAcfRDNlU3_QZjc/edit#gid=45210262

**Comment by johnpaulashenfelter** [comment]
@thatmattjohnson none of the rows in the CSV have the target filenames. 

I can rewrite the script to handle that but when we talked about automatically handling file renames, I understood that you had been in favor of manual renaming instead.

**Comment by thatmattjohnson** [comment]
Agreed during meeting on 11/7/2019 that automatically handing file names is preferred path. Able to proceed with edits to the script followed by PR generation.

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/3363

most of the names transferred ok. i can rename any that slipped through.

https://github.com/department-of-veterans-affairs/vets.gov-team/pull/19961

**Comment by thatmattjohnson** [comment]
reviewed and approved both PRs

**Comment by thatmattjohnson** [comment]
Initial UAT completed for the Facilities Locator PR merges.  For 22 files copied, 16 have subfolder names and file names concatenated and hence ended up in the incorrect va.gov-team location.  I was able to edit locations for the 9 affected Markdown files, but the 7 document uploads (highlighted in red in the migration plan doc, link below) will need to be rerun so that they live within LFS. Deprecation messaging/linking in vets.gov-team is consistent, links are sufficiently high-level so they don't need to be repointed.

**Comment by thatmattjohnson** [comment]
Screenshots of 7 uploaded files requiring manual moves below:

![Screenshot 2019-11-14 at 3.47.05 PM - Edited.png](https://images.zenhubusercontent.com/5d23974854489141ee75fa25/691d9b2a-3426-4ff3-9aae-23168edb9ef0)

![Screenshot 2019-11-14 at 3.47.45 PM - Edited.png](https://images.zenhubusercontent.com/5d23974854489141ee75fa25/9269c2bb-cd55-47ff-b6ae-4ad382380614)

**Comment by johnpaulashenfelter** [comment]
Thanks @thatmattjohnson . Here's the PR that fixes it: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3493

**Comment by thatmattjohnson** [comment]
Approved #3493.

**Comment by thatmattjohnson** [comment]
UAT completed on #3493; all looks good.
