### ISSUE TITLE
bug - form 526 submission when PPIU is disabled

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#28946]
17k form 526 submissions failed because [direct deposit functionality was disabled](https://github.com/department-of-veterans-affairs/vets-api/pull/7646) and raises a permissions error. 

It's far better to submit without direct deposit info 

<img width="1529" alt="Screen Shot 2021-08-18 at 5 21 34 PM" src="https://user-images.githubusercontent.com/19188/129990433-f15dfbcf-f95c-4206-8f32-e210384967e3.png">

**Comment by vhenry07** [comment]
Closing complete
