### ISSUE TITLE
Capture Comm Preference

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#28959]
...and record in the summary email

![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/4f8905d9-a9dc-40a3-972f-c331e6b43712)

**Comment by RudyOnRails** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/29552
