### ISSUE TITLE
[repo migration]: VA.gov Relaunch 2018

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2896]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1o5bAFuPf1vTLDljN6zPVVRoF522E2jLsN57jwPMB_R8/edit#gid=1776009537

**Comment by billfienberg** [comment]
PRs
* `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20087
* `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/4408

**Comment by thatmattjohnson** [comment]
PR review/UAT completed; all looks good. Closing this issue.
