### ISSUE TITLE
Internal GitHub Actions documentation for Platform FE Tools

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#28969]
## Details 

We have written a "how to use GHA" guide for VFS developers [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/GitHub-Actions-usage-for-VA.gov-frontend-engineers.1745911823.html)

We still need to write documentation for our end: 
* Daily deploys
* Content releases
* Troubleshooting build failures ([previous Jenkins version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/frontend/troubleshooting-build-failures.md))

Check with Megan and/or Katy about where the new docs should be located

**Comment by ndsprinkle** [comment]
Update on the current status of documentation:

Daily Deploy and Content Release documentation has been successfully updated - https://vfs.atlassian.net/wiki/spaces/FTT/pages/1844641889/Deployments

This excludes updates to explanations of how to deploy a specific commit (mainly for rollback purposes) as this functionality has not yet been implemented in GitHub Actions. See ticket for implementation - https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/29578

It's possible that this documentation could be updated prior to the ticket's completion if a definitive plan is made for how this will function from a user's perspective.

Also, Troubleshooting Build Failures has been migrated and formatted without changes from Jenkins to GitHub Actions - https://vfs.atlassian.net/wiki/spaces/FTT/pages/1861812285/Troubleshooting+build+failures

However, much of this documentation will be removed and the remainder will be refactored/reworded into the already existing GitHub Actions Usage documentation - https://vfs.atlassian.net/wiki/spaces/pilot/pages/1745911823/GitHub+Actions+usage+for+VA.gov+frontend+engineers

This page already features a section on troubleshooting, which is the section that will have pieces added from the migrated documentation.

**Comment by ndsprinkle** [comment]
Created two follow up tickets for the remaining documentation changes:
[29726](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/29726)
[29727](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/29727)
