### ISSUE TITLE
AWS Staging: Direct Scheduling Clinics Not Displaying as Expected

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#28960]
1. Configure VATS Cheyenne Optometry Direct Schedule Yes = 36 months
2. brienne.b.ferrara@id.me has a past optometry appt:    Chy Opt Var1   08/02/2019@08:00  Act Req/Checked In, meets the criteria for optometry direct scheduling.     
3. Log into VAOS.  Select Eye, Select Optometry, Select Cheyenne. 
4. Expected response:  CHY OPT VAR1  and Visual field both display as both are configured for Direct Scheduling in Mock CDW.
5. Actual response:  See attached screen shot.  Only Visual Field is available for direct scheduling. 

MOCK CDW Clinic Data:
{"etag":"e84cc2540fe9ff221c3ae780cf975b62bdfb90d416664b6dd2595fadc68e0ec6","locationSID":1400078777,"locationIEN":"408","facilityId":"983","locationType":"CLINIC",**"locationName":"CHY OPT VAR1"**,"primaryStopCode":408,"primaryStopCodeName":"OPTOMETRY","secondaryStopCodeName":"*Missing*","institutionSID":1400039290,"institutionIEN":"442","institutionName":"CHYSHR-CHEYENNE VAMC","institutionCode":"983","medicalService":"SURGERY","appointmentLength":30,"directSchedulingPatient":true,"displayAppointment":true,"sta6aid":"983","vaStationName":"CHYSHR-Cheyenne VA Medical Center","futureBookingMaximumDays":30,"nationalChar4":"*Missing*"}

{"etag":"48a9ed14ac34e2f571537d16a0eb5bb1e13749eb8f952b75ee08fcfa2221d8ed","locationSID":1400078806,"locationIEN":"437","facilityId":"983","locationType":"CLINIC","locationName":"CHY VISUAL FIELD","primaryStopCode":408,"primaryStopCodeName":"OPTOMETRY","secondaryStopCodeName":"*Missing*","institutionSID":1400039290,"institutionIEN":"442","institutionName":"CHYSHR-CHEYENNE VAMC","institutionCode":"983","patientFriendlyLocationName":"**VISUAL FIELD",**"medicalService":"SURGERY","appointmentLength":30,"directSchedulingPatient":true,"displayAppointment":true,"sta6aid":"983","vaStationName":"CHYSHR-Cheyenne VA Medical Center","futureBookingMaximumDays":365,"nationalChar4":"*Missing*"}

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/06c771b8-309b-4059-bba0-437459b817ea)

**Comment by jbalboni** [comment]
The bug here is that the two clinics names are mismatched. Only Visual Field should be available for scheduling, based on the VATS settings and matching clinics check.

I've opened an issue around the conflict between the 24 month matching clinics check and 36 month past visit check: #28970

**Comment by laurenernest** [comment]
@marcynadeau @beth-wodzinski the matching names part is ready for retesting. per jeff's comment above, the clinic availability is captured in another ticket.

**Comment by aarathi-poldass** [comment]
@laurenernest @marcynadeau @beth-wodzinski - Validated above steps and now see that the clinic names are matching (clinic name mentioned in the text below the main header, and then another clinic name mentioned in legend for the radio button group) and only Visual Field is available for direct scheduling.

**Comment by laurenernest** [comment]
Closing ticket per QA validation.
