### ISSUE TITLE
[Design] Create design for new Indian question on 10-10EZ (Phase 1)

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#28975]
## User Story

As a Native American, I would like to specify that fact during enrollment on the 10-10EZ, in order to _____

## Expected Behavior

The purpose of this story is to create the initial UX design for the a new Indian question that is being added to the 10-10EZ. Here is an example of how the question may appear on the 10-10EZ paper form:

![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/fc98da0a-19c0-498f-9803-c2bd9447b688)

We will address this question online in 2 phases:
* Phase 1: Add the new question. Any required documents will be provided through an offline process after submission.
* Phase 2: Add the ability to upload required documents with this question.

For this specific Ticket, the focus is on the design for Phase 1. This means we will add a new Yes/No answer question to the 10-10CG. 

In Phase 1, the design should incorporate the following elements:

* **Question**: Are you a member of an Indian tribe? _Note: this is just a placeholder copy for now_
* **Answers**: Yes / No
* **Definition of "Indian"**: For now use the copy listed below
* **Required documents**: We will need copy that states the user will be contacted to provide required documents. For now use the list below

### Definition of "Indian"

> INDIAN:  The term “Indians” or “Indian”, unless otherwise designated, means any person who is a member of an Indian tribe, as defined in subsection 25 U.S.C. 1603(d) except that, for the purpose of sections 1612 and 1613 of this title, such terms shall mean any individual who (A) irrespective of whether he or she lives on or near a reservation, is a member of a tribe, band, or other organized group of Indians, including those tribes, bands, or groups terminated since 1940 and those recognized now or in the future by the State in which they reside, or who is a descendant, in the first or second degree, of any such member, or
> (B)is an Eskimo or Aleut or other Alaska Native, or (C) is considered by the Secretary of the Interior to be an Indian for any purpose, or (D)is determined to be an Indian under regulations promulgated by the Secretary.

### Required documents

1. **Tribal Entities.**
       a.     Tribal Enrollment or Membership ID card (Documentation establishing membership in a tribe or lineage including a tribal enrollment or membership identification card)
       b.    Letter – Tribal Affiliation or Enrollment (a letter from tribal executive staff verifying tribal affiliation or enrollment)
       c.     Letter – Descendancy (a letter of descendancy)
       d.    Tribal Certificate (a tribal certificate)
      e.    Tribal Census Document (a tribal census document)
        f.    Certificate of Indian Blood or Kinship Report (a Certificate of Indian Blood or a kinship report)
       g.     ANCSA Shareholder document (a shareholder document from an Alaska Native Claims Settlement Act (ANCSA) Corporation)
2. **Federal Government. Documentation from**
      a.      U.S. Health and Human Services
      b.     U.S. Department of Homeland Security (DHS)
      c.      U.S. Department of the Interior (DOI) (including a letter on Agency letterhead)
      d.     Bureau of Indian Affairs or Indian Health Service (a copy of records from the Bureau of Indian Affairs or Indian Health Service,
      e.     Enhanced Tribal ID card
3. **State Government.**
      a.      Driver’s License

_Note: In Phase 1, the Veteran will not need to upload these documents during submission._

## Acceptance Criteria

- [ ] New design/wireframe is created for feedback from the Healthcare Eligibility team

**Comment by tchrisdyer** [comment]
@Dene-human 
1. See attachment [https://app.zenhub.com/files/133843125/8616faa7-ee90-4811-803e-c20b78618c7f/download](https://app.zenhub.com/files/133843125/8616faa7-ee90-4811-803e-c20b78618c7f/download)
2. Not sure. Let's assume yes but ask them to be sure.
3. Let's assume one for now and ask them during the meeting.
4. Not sure. We can ask. I can't remember where I copied that from.
5. No, we should ask

**Comment by Dene-human** [comment]
[Design is here](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/pavlY1R)

I will talk about this with Danielle on Friday. I believe it needs to be in plain language.

**Comment by Dene-human** [comment]
Confirmed with Danielle that this will require more context, and will need to be rewritten in accordance with our style guide and plain language standards.
