### ISSUE TITLE
Matching clinics and VATS past visit mismatch

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#28970]
In VATS, you can set a facility to require a past visit within the past 36 months to direct schedule for a particular type of care.

In VAOS, for non MH and PC types of care, we require you to have clinics available that have been interacted with in the past 24 months in order to direct schedule.

These two things conflict, making it ineffective to set the past visits range to 36 months for direct scheduling on types other than MH and PC.

There are two solutions for this:
1. Update the matching clinics check to pull 36 months of appointment history. This has a negative impact in performance on all users of VAOS, as it is additional wait time to verify what flow you're in
2. We can remove the matching clinics check for non MH and PC types of care.

**Comment by marcynadeau** [comment]
@laurenernest Does this mean in VATS Mental Health for a site to Yes Last Seen within Last 36 months, and veteran has past appointments  in MH clinic >24 mos that the veteran will not be able to direct schedule in MH despite VATS being set to 36 mos?

**Comment by laurenernest** [comment]
@marcynadeau This applies to types of care that are _not_ primary care or mental health.

We removed the check for PC and MH in #28269

**Comment by marcynadeau** [comment]
Okay, thanks.  So given a veteran meets direct scheduling criteria, then those clinics that have been interacted with in the last 36 months will display to the user for direct scheduling,  correct?

**Comment by ldelacosta** [comment]
We have addressed this fix in #39950
