### ISSUE TITLE
**DISCOVERY** | Localization for Non-Latin Languages 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#28981]
## High Level User Story/ies

As a product owner creating translated VA.gov content for LEP Veterans, family members and/or caregivers, I need to provide Covid-19, benefit info, form applications, and other important information to a given population in their native language (Chinese is likely to be next language we begin to support).

As our next step, we'd like to gain an understanding of the potential impacts and obstacles that will need to be understood and addressed before we can begin expanding our translated content to non-Latin languages. Some potential areas to vet include:

1. Understanding whether our most commonly used templates,  page.drupal.liquid, will support translated content and if not, what the problematic areas are.

Validate types of differences we will likely encounter such as:

- increased character count 
- vertical placement
- different font sizes (based on language) and need for flexible line heights

Some background info here: https://www.w3.org/International/articles/article-text-size:

> Chinese, Korean, or Japanese will usually contract, although the percentages may fluctuate significantly. And, even while these languages typically contract, they use characters that are more complex than those in Latin alphabets and therefore require more space in between characters. This can result in vertical expansion if the space between the lines needs to increase to fit the characters.

Typically there is a 15%-20% space increase when translating English to French or Spanish. German and Dutch can be up to 35%. Also, it is very common for non-Latin text to have much taller characters than Latin text. Additionally, as mentioned above, these scripts often require more vertical space between lines than does Latin-based text.

  
## Acceptance Criteria

- [x] Demonstrate how the Covid-19 page would render in Chinese (use Google translate for sample translation)
- [x] Document any impediments noted with rendering and review with team
- [x] Include recommendations to investigate how to resolve for future sprint work
- [x] Add write-up of findings to Github Product folder

**Comment by SKasimow** [comment]
@adamwhitlock1 This is the placeholder ticket I thought we could review at our backlog meeting next week for Sprint 58 work.

**Comment by adamwhitlock1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/non-latin-character-content-discovery.md
