### ISSUE TITLE
Content review for Authenticated Experience: Direct deposit messaging

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#28986]
We're blocking online direct deposit access for users who log in with MHV and DS Logon (essentially unverified accounts that don't have 2FA) due to a recent security issue.  We need to let these users know they can call the contact center or set up a verified ID.me account to edit info online.

### Heading
> You’ll need to verify your account to edit direct deposit information online.

### Body
>We require this to help protect your bank account information and prevent fraud.
> [h3] What you can do
> If you have questions or concerns about your direct deposit, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. 
> You can also [create a verified account through ID.me](link), and then use it to log into VA.gov and update your direct deposit information.

## Screenshot
![image](https://user-images.githubusercontent.com/55992116/130158874-caffe07d-d151-4abd-990b-554c996c53da.png)

## Notes
- I think the heading should specify this is about completing the task _online_. It feels safe to assume the user came to this page with the intention of doing this online. They can still do this through the call center without setting up an ID.me account
- We don't have contact center support for the ID.me process. So if someone struggles with that, they're kind of on their own. Not ideal, but for that reason, I'm putting the call center info first.

**Comment by bethpottsVADEPO** [comment]
@andaleliz Is the assumption that if someone signs in with MHV or DS Logon, they don't have an account on VA.gov through ID.me? I'm wondering if we need to add language to that last sentence you have that would account for people who already have an ID.me account and just need to sign in that way rather than through MHV or DS Logon. Maybe this is an edge case? Wanted to see what you know.

**Comment by andaleliz** [comment]
Hi Beth- let’s go ahead and add copy to account for that use case. Thanks
for catching that! --
Liz Lantz
Senior UX Designer, Ad Hoc
adhoc.team
<https://www.google.com/url?q=https%3A%2F%2Fadhoc.team%2F&sa=D&sntz=1&usg=AFQjCNE4MGCYSFhDl_lZwwTif1R0KYNm0w>
|
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>
@adhocteam
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>

**Comment by bethpottsVADEPO** [comment]
@andaleliz I'm not sure how calling helps the user, so I don't know if "Get help verifying your identity" is the right messaging. If they call, can someone help them update their DD information? What's the purpose of including the phone number? Should it be more like this?: **Get help updating your direct deposit information**

Let me know if you think this works or if we need to tweak the language a bit more:

**Heading** (no period at the end)
**You’ll need to verify your identity to update any of your direct deposit information online**

**Body**
We require this to protect your bank account information and prevent fraud.

**Use ID.me to verify your identity online.** You can create an ID.me account now or sign in using your existing ID.me account.  Then you'll be able to update your direct deposit information online. [Create an ID.me account or sign in now]

**Get help verifying your identity.** You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by andaleliz** [comment]
@bethpotts Thanks for your help!  **Get help updating your direct deposit information** is the way to go. We're including the phone number so someone can get help with direct deposit. We don't have a way for someone to help them verify their identity over the phone, which is why I put the call center info before the CTA to use ID.me.   Here's what I think would work best:

-----

**Heading**
You’ll need to verify your identity to update any of your direct deposit information online

**Body**
We require this to protect your bank account information and prevent fraud.

**Get help updating your direct deposit information.** You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Use ID.me to verify your identity online.** You can [create a verified ID.me account] or sign in using your existing verified ID.me account. Then you'll be able to update your direct deposit information online.

-----

My thinking in prioritizing the call center over creating an account is that it's more likely that a person came to this page to update direct deposit info, vs create an ID.me account.  

And I've emphasized that a _verified_ ID.me account is necessary in the last section, because it is possible that someone is signed in with an ID.me account but it's not verified. 

Let me know if you're good with that, or if there are any further edits. Thanks again for your help!

**Comment by bethpottsVADEPO** [comment]
I think we need to label the text link as I did in my last message so people who just need to sign in to an existing ID.me account have a CTA. So:

_I want to note the bolding of the first sentence for each scenario for the dev. (Get help updating... / Use ID.me to verify...)_
Heading
You’ll need to verify your identity to update any of your direct deposit information online

Body
We require this to protect your bank account information and prevent fraud.

**Get help updating your direct deposit information.** You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Use ID.me to verify your identity online.** You can create a verified ID.me account or sign in using your existing verified ID.me account. Then you'll be able to update your direct deposit information online. [Create a verified ID.me account or sign in now]

One more question I have: Will all users see this message? Even ones who are already verified? If that's the case, we'll need to add some language like this to follow that first line of text under the header: "If you're already signed in through ID.me with 2-factor authentication, you can update your direct deposit information online right now."

**Comment by erikphansen** [comment]
@bethpotts this message will be shown to all users who signed in with DSLogon or MHV. If you signed in with a verified ID.me account, you will not see this message.

**Comment by andaleliz** [comment]
@bethpotts I don't think we can have a CTA that says both "create an account" or "sign in now".  If the user is signed in with MHV, but they also have a verified ID.me account, they would need to log out of VA.gov and then sign back in with ID.me. I think the only link we could give them is a link to sign out.

@erikphansen wouldn't you see this message if you signed in with a non-verified ID.me account?  Also, can you confirm that my statement about signing out and then back in is correct?

**Comment by erikphansen** [comment]
1. Yes, a MHV user would need to sign out and then log back in using their ID.me account
2. Technically, yes. The FE does have logic to show this message to non-verified ID.me accounts. But apparently it's not possible to have an LOA3 ID.me account that doesn't have 2FA set up. So it seems likely ID.me users will never see this alert; If an ID.me user is LOA1, they only have access to the Account Security section where they are told they need to verify their ID. And (I have been told) part of verifying their ID includes setting up 2FA. At that point they will have access to Direct Deposit.

**Comment by andaleliz** [comment]
Oh, okay. That's good to know. I think we will still need the language we have though, because if they still need to sign in with a _verified_ account.

**Comment by bethpottsVADEPO** [comment]
@andaleliz @ajakabcin Here's a mash up of what Liz and I talked about:

Heading
**You’ll need to verify your identity to update any of your direct deposit information online**

Body
We require this to protect your bank account information and prevent fraud.

**Get help updating your direct deposit information.** You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Sign in with a verified ID.me account.** You can [create a verified account on ID.me]. Or, if you already have one, please sign out and sign back in using your existing verified ID.me account. Then you'll be able to update your direct deposit information online.

**Comment by erikphansen** [comment]
Sorry I'm way late with this comment. But this heading feels misleading to me: `You’ll need to verify your identity to update any of your direct deposit information online`. MHV and DSLogon users who _have_ verified their identity are going to see this message. MHV and DSLogon users who _haven't_ yet verified their ID aren't going to be able to get this far.

**Comment by andaleliz** [comment]
@erikphansen That's a good point. I don't know enough about the MHV and DSLogon processes.

If we add, ID.me, does that feel more accurate? 

"You’ll need to verify your identity with ID.me to update any of your direct deposit information online"

**Comment by erikphansen** [comment]
Yeah. That seems a lot better and more accurate. Technically they need to verify their ID _and_ set up 2FA with ID.me, but they _have to_ set up 2FA as part of verifying their ID, so your messaging is solid.

**Comment by andaleliz** [comment]
I can't imagine Beth will argue with that - and I know she has many demands for her attention. Let's go with that, and close this out. 

Beth, please re-open if you have any edits. Thanks for your help!

**Comment by erikphansen** [comment]
[PR to update the content is here](https://github.com/department-of-veterans-affairs/vets-website/pull/18368)
