### ISSUE TITLE
Create SEO Best Practices Document

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2898]
Bring over, update and broaden the SEO standards started previously.

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Content/Content%20Strategy/SEO%20Writing.md

**Comment by mnorthuis** [comment]
@peggygannon I have created a draft guidelines doc for you to review.  I haven't put a ton of info in on sections that primarily relate to your work, so we can talk through those and start to build them out.  

https://docs.google.com/document/d/1-tQsIknkkHqF4nT_XJ44CeYZJ5Flct0KqMV0RA93Zsk/edit?usp=sharing

**Comment by meganhkelley** [comment]
@mnorthuis and @peggygannon I added some comments in the google doc, including a couple notes at the end about what's missing here as compared to the last iteration of the SEO doc. Looks great so far!

**Comment by peggygannon** [comment]
@mnorthuis @meganhkelley I've added some info under the content areas of this doc. Let me know if you have any questions. I need do a little more research on keywords and will drop that in by tomorrow (Tues). 

https://docs.google.com/document/d/1-tQsIknkkHqF4nT_XJ44CeYZJ5Flct0KqMV0RA93Zsk/edit

**Comment by mnorthuis** [comment]
Documentation posted in GH: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/seo-best-practices.md

Closing issue.
