### ISSUE TITLE
(WIP) [Design] Vaccine 3rd dose/booster

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#28984]
## Request
D/T/M specs for vaccine flow to factor in 2nd and 3rd (booster) dose scheduling options.

## Background
VAOS currently supports self-scheduling for the first dose of a COVID-19 vaccine.

## Requirements
- Vaccine appointments are self-scheduling only (no schedule requests)
- Vaccine type the Veteran received is included in submission (currently no programmatic way of getting this info)
- Veterans who received J&J vaccine are not eligible for another dose/booster (direct to vaccine info page for softer dead end?)
- Veteran cannot schedule 3rd dose/booster less than 8 months after they received their 2nd dose
- Show clinics with CHAR4=CDQC

## Open questions
- If Veteran mixed and matched their 2 doses, can they get a 3rd dose?
  - If yes, can they get it if their 1st dose was Moderna and 2nd Pfizer?
  - If yes, can they get it if their 1st dose was Pfizer and 2nd Moderna?

## Scenarios
- Veteran has not received any vaccine dose
- Veteran received one dose of Moderna or Pfizer
- Veteran received one dose of J&J
- Veteran received two doses of the same series Moderna or Pfizer
- Veteran received two doses of a combination of Moderna and Pfizer
- Veteran received one or more doses of another vaccine (e.g. AstraZeneca)

## Design assets
- [Mobile](#)
- [Tablet](#)
- [Desktop](#)

**Comment by ldelacosta** [comment]
We do not need this ticket. If we do decide to work on updating the vaccine workflow, a new epic/feature will be created. cc: @JRRoof
