### ISSUE TITLE
Update all remaining docs to reflect Jenkins -> GHA CI change

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#28990]
## Details 

Various docs have been created and updated for GitHub Actions migration as part of tickets #25188 and #28969

This is a catchall ticket to update any remaining docs that refer to Jenkins as a frontend CI tool 

Links TBD, effort may be dependent on migration to Platform Website #13756

**Comment by ndsprinkle** [comment]
Locations where Jenkins is referenced on the new platform site: https://depo-platform-documentation.scrollhelp.site/search.html?q=jenkins&max=10&s=developer-docs&start=0

**Comment by oseasmoran73** [comment]
Have identified the following documents need to be updated:

- [Frontend workflow](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-workflow.1846083611.html)
- [Cypress Upgrade Guide](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1869742109/Cypress+Upgrade+Guide) -- Have reached out to Peter via [slack](https://dsva.slack.com/archives/C01CHAY3ULR/p1635881816055300)
- [Deployment Process](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployment-process.590970953.html)
- [Unit Tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/Unit-tests.1836187655.html)

**Comment by oseasmoran73** [comment]
@ndsprinkle There were a couple of features recently added to `Manual dev/stage Deploy`. Can you provide the URL link for it?

**Comment by ndsprinkle** [comment]
@oseasmoran73 Right here: https://vfs.atlassian.net/wiki/spaces/FTT/pages/1847820373/Manual+deployments#Manual-deployment-of-vets-website-to-staging-or-dev

That stuff is still living in the TEMP directory

**Comment by meganhkelley** [comment]
To Do: 

- [ ] Update the "Deployment Process" doc to reflect that vets-website and content-build now use GHA 
- [ ] Move deployment docs from temp directory to a "Deployments" directory in the frontend dev docs on Platform Website 
- [ ] Confirm that everything [on this page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy) is reflected on the Platform Website (in Confluence) — if not, add the info to Confluence
   - [ ] Confirm that there are links to the deploy jobs in Confluence 
- [ ] Add deprecation message, as shown [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/overview) to the [Deploy](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy) page.
- [ ] Confirm that everything [on this page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/build-deploy-flows/) is reflected on the Platform Website — if not, add it
   - [ ] Add deprecation message here
- [ ] Last task: publish Platform Website

**Comment by oseasmoran73** [comment]
Adding [Excel](https://www.npmjs.com/package/@department-of-veterans-affairs/component-library) that was given by Katy B

**Comment by oseasmoran73** [comment]
> The use of hotfixes is discouraged, but may be useful in an emergency situation when masterhas significantly deviated from the release and a fix to the failed production release is critical. To create a hotfix, create a branch from the last stable release tag, make changes necessary (with review), create a new release tag following the correct naming scheme, and trigger a deploy in Jenkins with the release name as a parameter. This documentation is above, in the "Creating a Release" section.

@meganhkelley This section is under rollback which we don't have in our new documentation. I have not researched/investigated this snippet. Is this something we want to pursue?

**Comment by timwright12** [comment]
@oseasmoran73 No, I think this was more important when the pipeline took forever, but now with it faster folks can just follow the normal process
