### ISSUE TITLE
[TIER 3] Disability Claim Application Issues with Application ID number (3597784)

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#28999]
## Issue Description
_Disability Claim Application Issues with Application ID number_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Initials: W.L.

Issue:  Cannot submit disability Claim application

ID: 3597784

Link for more information:

**Comment by annaswims** [comment]
Note to self: user:"id:9a2171dd800642eeb6a21a62a727cc1a"

**Comment by annaswims** [comment]
@Kimberley2019 Did the vet describe what they are seeing at all?

**Comment by Kimberley2019** [comment]
![WL screenshot](https://user-images.githubusercontent.com/52981726/130691424-bd6e4d32-6669-4e21-b824-aa6d936b7574.jpg)

**Comment by Mottie** [comment]
> is there any reason that this data would make it into the in-progress form

Yes, the in-progress form saves error states. So this Veteran couldn't submit the form from the last page, or did they have a problem with uploading a file? Did they try again? Can they delete the entry that has an error?

**Comment by annaswims** [comment]
This screenshot is quite helpful! We can see that the vet had a weaker wifi connection and the error message says it's a connection problem. Perhaps the vet can try going closer to the wifi router or using cellular data and retry.  If that fails, the vet can submit the application without the file and add it later on the claim status page https://www.va.gov/claim-or-appeal-status/ .  There's also the option to print and mail or fax the document.
<img width="1016" alt="Screen Shot 2021-08-25 at 9 07 56 AM" src="https://user-images.githubusercontent.com/19188/130796175-df4647ca-d1cd-49f7-bec0-8bd1680b82a1.png">

**Comment by Kimberley2019** [comment]
Reached out to veteran with information above.

From: VA Technical Support 
Sent: Thursday, September 2, 2021 2:38 PM
To: 'W Layne' 
Subject: RE: [EXTERNAL] Re: Disability Claim Application Issue

Good Afternoon Mr. Layne,

Thank you for your service.

The screenshot that you provided was very helpful to the technical team.  They were able to see that there was a weaker wifi connection and the error stated that there was a connection problem.  Perhaps you can try going closer to the wifi router or use cellular data and retry.  If that fails, you can submit the application without the file and add it later on in the claim status page https://www.va.gov/claim-or-appeal-status/ .

There is also the option to print and mail or fax the document.

 


Please feel free to reply to this message if you have tried the steps above and are still unable to submit.  Once we receive the information we can relay it to the appropriate team and proceed accordingly.



Kind Regards,

The VA.gov Technical Support Team

**Comment by annaswims** [comment]
I checked up on this one - the vet has not yet submitted

**Comment by Kimberley2019** [comment]
I followed up with veteran again.

From: VA Technical Support 
Sent: Thursday, September 16, 2021 6:02 PM
To: 
Subject: RE: [EXTERNAL] Re: Disability Claim Application Issue

Good Afternoon Mr.,

We are following up to see if you were able to submit your claim online or if you chose another option.

We look forward to hearing back from you.



Kind Regards,

The VA.gov Technical Support Team

**Comment by annaswims** [comment]
@Kimberley2019 can we close this one if the vet doesn't respond?

**Comment by alsleaders** [comment]
I am closing this ticket because we have not heard back from the veteran.
