### ISSUE TITLE
EDU: Update content of GI Bill status when no delimiting date

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#28991]
As a developer, I need to update the content of the GI Bill status tool when the user does not have a delimiting date so that it displays a meaningful message.

## Assumptions:
1. This work is done in this tool: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status

## Acceptance Criteria
1. When a user has benefits remaining, but does not have a delimiting date the text

> You have until **Invalid date** to use these benefits.

is replaced with:

> There's no time limit to use these education benefits.

### Technical Notes
The Post 9/11 GI Bill Statement of Benefits page displays information comprising the Certificate of Eligibility for EDU benefits. This page exists in the post-911-gib-status application in the vets-website repo. The StatusPage.jsx renders the UserInfoSection.jsx. The UserInfoSection.jsx uses a helper function to display the benefit end date explanation. This function is expecting a valid benefit end date or delimiting date. The function attempts to parse the date string and format it to a valid date display format. Since the value is not a valid date string, the formatter returns "invalid date" instead of the formatted date string. The fix would be to account for the possibility of an invalid date and display a more meaningful message accordingly.

## Supporting Artifacts:
1. Screenshot:
<img width="439" alt="Screen Shot 2021-08-20 at 10 13 18 AM" src="https://user-images.githubusercontent.com/48260534/130246740-8a19638b-30d4-4d06-9cf2-54060db508b4.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18337

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2155&group_by=cases:section_id&group_order=asc
