### ISSUE TITLE
Implement sentry triage rotation for vets-website

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2900]
# Overview 

We don't review sentry errors frequently enough and we don't have a clear process for documenting bugs. By designating someone responsible for triaging bugs, we improve our operations readiness and foster process improvement to our error triaging. 

# Goals 

- Create a rotation and a daily review process (e.g. weekly rotation, daily triaging of sentry issues) 
- Determine how to give apps team ownership over their own triaging 
- Create and improve error capture / reporting guidelines

**Comment by kfrz** [comment]
Closing this as we are intending to address [by auto-routing errors](https://github.com/department-of-veterans-affairs/va.gov-team/issues/276) based on tags and component and directly assigning with Sentry rules to the product teams.
