### ISSUE TITLE
Support Request - Intent to File Date dispute

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29008]
## Issue Description
This veteran (Sensitive 7) contends that she submitted a complete application on 3/20/20 (documented in VBMS). AFTER submitting the complete application, she reports initiating another claim in eBenefits. She states that she continued to work on this pending application until she was ready to submit it. She states that she received an error message during the claim submission process and that this deleted her ITF of 3/20/20.

There is no information in the ITF screen or VBMS notes to support the contention that a claim was initiated/ITF on 3/20/20. There is also no screenshot documenting the “red banner error.” However, it seems as though this VA employee veteran did understand how to initiate/complete an eBenefits claim because she had done it previously.

Current Claim ID:           84794031
---
## Tasks
- [ ] Please review to determine if there is a record of this veteran initiating an eBenefits claim/ITF on 3/20/20. I’ve been told that the veteran’s claims were submitted via va.gov so you may be able to provide assistance. Thank you.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by annaswims** [comment]
this says `eBenefits claim` do we think it happened on Va.gov?

**Comment by annaswims** [comment]
What the veteran describes in entirely possible.  

VA.gov finds or creates the veteran's intent to file from EVSS and caches it for a day when a veteran begins or resumes a form 526. 

 When a veteran submits a form 526, we run a variety of jobs, in an ideal scenario they all succeed within 5 minutes and the final `SubmitForm526Cleanup` job removes the intent to file from our cache.  However, in a non-ideal scenario we would retry those jobs for around 36 hours and that original intent to file could still be present as we retry the submission.

**Comment by vhenry07** [comment]
Can we determine if there is a record of this veteran initiating a claim/ITF on 3/20/20. I’ve been told that the veteran’s claims were submitted via va.gov so you may be able to provide assistance. Thank you.

**Comment by annaswims** [comment]
I think the text of the request is correct - the claim was filed in ebenefits, not va.gov. we have no record of a claim  with a claim id of 84794031 in va.gov.  At that point eBenefits would've still been accepting benefit claims.

**Comment by cnemeth** [comment]
Closing ticket:
- there is no log trail to investigate
- there is no record of a claim with a `claim_id: 84794031` in `va.gov`
