### ISSUE TITLE
Access for Ryan Johnson (Laptop)

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#29000]
Already have approval in past, but need access for my laptop.

# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Nancy Smith
- Please provide your name.
   > Ryan Johnson
- Please Provide your email.
   > ryan.johnson@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Testing Tools Team - Software Engineer - Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDy5jNwPAZdw4f456f8EyZ8iK7TyAHLrH3fmP1nEys0q5NNMcV7JOKp+wRTc4f09s8rcSMXYvoTTqixx73XY/ZN4uLmzZGhJcuDTTm/8PhM0jgPZAewUhtymyVseRmnGAaKq/TODbZfvNCEP870Mm6lN0Ni3oqMKK3LWNZpl1MuJP9xiLBArB34yQfznAFkf7eZpOI03RtmG5EQp6MTJCI0y3pNUP6+ErCW4m25IYztajcW+sca+ywLimaPF073T6/sThsFt7hLwELib0T+GE5MFBu8m5h60XbLV2gMbvTuUYPoAy/VUTWeMHgRouhyndreERGTy4dtHHACZy8k9OyCWpWUmK07g/vDA9QGUTvqsChuWvems8Ajr3+VMaNB1MlOFOaajRJYBzfFrL4t6ViE/CMAJltpcNc0aDAJzvHMqs3Wgj9uGOhREpVuL2WluympBJAOePuR8M3lIvzfKRea/96CK/eZUKaZ4c9TkSQ0bsycut9bG6kMHlaQGjafneE= ryanjohnson@Ryans-MacBook-Air.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
Authorized keys file for user being updated now. Should be able to access in about 5-10 minutes. Please reopen if any issues are observed.
