### ISSUE TITLE
[Call Center] Review and update call center guide for direct deposit based on recent updates

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2901]
We are slightly changing how direct deposit functionality will work on VA.gov. Currently, people can add direct deposit info for the first time. They can also edit existing information.

We have learned that in reality, people adding direct deposit info for the first time have to do this via paper form (use case: someone is switching from paper checks to DD) and that they can not do this via VA.gov. So, we need to remove the ability to add direct deposit info for the first time.

**People will still be able to edit existing direct deposit info**. 

In terms of other changes, we may want to add some documentation on what users should do if they can't change their DD info because of address-related issues. I don't think we anticipate any additional changes beyond that, but something small might come up. 

### Definition of done

- [ ] Remove content on adding direct deposit info from call center guide
- [ ] Add information on what users should do if they get a DD error related to their address.

**Comment by Samara-Strauss** [comment]
cc/ @clantosswett for awareness

**Comment by Samara-Strauss** [comment]
@lkoenigsberg @clantosswett I updated the call center guide to reflect the mailing address and phone number errors we're seeing, and to mention how people can update whether they get paper checks or direct deposit. Those updates start on page 15. Can you read through them and let me know if you have feedback? Thanks!

[Direct Deposit Call Center Guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3795736/Direct.Deposit.Call.Center.Guide.pdf)

**Comment by clantosswett** [comment]
Thanks Samara. It looks good and clear to me. I just have a few points of feedback that are relatively small. First, on page 15 in the third paragraph and on page 17 in the last paragraph, the text references the "above error messages". I don't think the error messages are shown above (from what I can tell). I think we should just say the below error messages because in both cases the user flow is shown, including the error message in question.

The only other question I had was about updating phone numbers. You said it won't be likely they will need to update both numbers to fix the error. Do you know if there will be a scenario where they might need to do that and if so, would that be shown in the error message. It's not a huge deal but just curious. Call centers do best when they have answers to even the smallest edge cases. 

Thanks!

**Comment by Samara-Strauss** [comment]
> First, on page 15 in the third paragraph and on page 17 in the last paragraph, the text references the "above error messages". I don't think the error messages are shown above (from what I can tell). I think we should just say the below error messages because in both cases the user flow is shown, including the error message in question.

Good catch. Changed to "If someone sees this error..."

> Do you know if there will be a scenario where they might need to do that and if so, would that be shown in the error message. It's not a huge deal but just curious. 

I do not know for sure that someone would never need to update both phone numbers. I think it's unlikely, but I can't say for sure. I'll clarify that this is possible but unlikely, and it is possible that someone goes back to update direct deposit and gets a different error related to updating their mailing address or phone number.

**Comment by Samara-Strauss** [comment]
I've got updates ready and wanted to post screenshots/the new guide but file upload isn't working on Github right now. So, here is the copy I added below to clarify that someone might get an additional error. I'll post the updated guide when file upload is working again. Let me know if you have any feedback:

Page 15:

> If someone sees this error, then they should update their mailing address in the VA.gov profile, and then try to update their direct deposit again. Once they are successfully able to save a new and valid mailing address, then their direct deposit information should be able to be saved unless there are issues with their phone numbers on file (see the next section for more information on phone number errors). 

Page 17:

> **Note**: This is unlikely, but it is possible that someone will get another error related to changing their phone number after they’ve fixed their mailing address (see the next section below for more information). This is unlikely but it is possible. Once they fix their phone number(s), they should be all set to update their direct deposit information.

Page 18:

> Once they are successfully able to save a new home or work phone number, then their direct deposit information should be able to be saved unless there are issues with their mailing address on file (see the previous section for more information on mailing address errors) or there are issues with a different phone number (eg. they had to fix their home number and then got a different error that they need to fix their work phone number). 

Page 20:

> **Note**: This is unlikely, but it is possible that someone will get another error related to changing a different phone number or to changing their mailing address (see Mailing Address section above) after they’ve fixed their phone number. This is unlikely but it is possible. Once they fix their phone number(s) and/or mailing address, they should be able to update their direct deposit information.

**Comment by Samara-Strauss** [comment]
@clantosswett here is the Call Center Guide with the updates we discussed on Friday. Unless there is other feedback, this is done. I am going to close this, but please feel free to re-open it if you have additional feedback.

[Direct Deposit Call Center Guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3806203/Direct.Deposit.Call.Center.Guide.pdf)
