### ISSUE TITLE
Update timeframes for Burials 

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#2902]
NCA has a quick update request to make on https://www.va.gov/burials-memorials/plan-a-burial/ 

FROM: If you can’t find these documents, please ask for our help when you call. It may take us 48 hours or more to check eligibility if you don’t have discharge documents.

TO: If you can’t find these documents, please ask for our help when you call. It may take us several days to check eligibility if you don’t have discharge documents.

**Comment by RLHecht** [comment]
@AnneHurley This change has been made and saved as a draft. @peggygannon Can you please review and publish in Drupal? It is node ID 861 Schedule a burial for a Veteran or family member. @Karak888 for awareness.

**Comment by peggygannon** [comment]
@RLHecht @AnneHurley Page has been reviewed and published in drupal.

**Comment by AnneHurley** [comment]
This is live.
