### ISSUE TITLE
TUD - fix user availability

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#29022]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Currently the user availability attribute is not properly updating when a test user is in use.

---
## Tasks
- [ ] Determine why a test user's availability isn't updating and fix it.

## Acceptance Criteria
- [ ] The availability feature will work again.

**Comment by nsoutouras** [comment]
Transitioned to TTT
