### ISSUE TITLE
Update cancel appointment route and remove required reason parameter

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#29033]
Two changes:

1. Instead of the cancel endpoint being `PUT /vaos/v2/appointments/cancel/:id`, do `PUT /vaos/v2/appointments/:id`
2. Remove `reason` as a required field in the body of the PUT

Status should remain a required field in the body.

**Comment by laurenernest** [comment]
@jbalboni do you need to do any validation on this one?

**Comment by jbalboni** [comment]
@laurenernest I just did, looks good to me.
