### ISSUE TITLE
Access for David Rowley

### ISSUE THREAD

**Issue by dsrr47** [department-of-veterans-affairs/va.gov-team#29030]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Amy Kollar
- Please provide your name.
   > David Rowley
- Please Provide your email.
   > david.rowley@va.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Legacy AO Team 3, frontend developer, Accenture Federal

- Requesting SSH key authorization?
   >  NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  - My team is assuming maintenance/support for Comparison Tool, Feedback tool, etc. from the current team. Please add me to the newly created group “afs-vfs-developers” and provide the same access as the group “bah-vfs-developers” so that we can continue to maintain the same level of support for Education Services.

**Comment by omgitsbillryan** [comment]
**For AWS Access:**
User: David Rowley
COR: Riley Ross
Approval needed: @mchelen-gov

I verified that this GH user is part of the department-of-veterans-affairs GH org.

**Comment by mchelen-gov** [comment]
request approved 👍

**Comment by rwilliams-oddball** [comment]
Shoot me an IM for your AWS temp password.

**Comment by rwilliams-oddball** [comment]
Verified login to AWS.
