### ISSUE TITLE
[FE] My VA: 508-defect-3 [FOCUS]: Focus should go to the `h1` Verify your identity when the LOA user uses the "Verify your identity" link

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#29046]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user, I expect focus to go to the h1 of the "Verify your identity" page when I use the action link "Verify your identity" so that I know where I am immediately.

## Details

When a screen reader users the "Verify your identity" action link on their My VA page, focus goes to the "Skip to content" link.
Placing focus on the `h1` would be more preferable as it clearly announces that they have arrived on the Verify your identity page.

## Acceptance Criteria

- [ ] Upon using the "Verify your identity" action link, focus goes to the `h1`"Verify your identity" on the new page

## Steps to Recreate

1. Log in as LOA 1 user B 
2. Turn on your screen reader of choice
2. Tab to "Verify your identity" link and activate it with `enter`
3. Confirm that focus goes to "Skip to content" 

## Proposed Solution (if known)

Use a `tabindex="-1"` to send the focus to the `h1`.

## Screenshots or Trace Logs

<img width="1066" alt="Screen Shot 2021-08-23 at 12 20 43 PM" src="https://user-images.githubusercontent.com/14154792/130483262-4b20d04d-7b22-4fcc-9d94-d5986de7765c.png">

**Comment by tmitchellgcio** [comment]
ready for validation. There is a passing test for this as well @ajakabcin

**Comment by ajakabcin** [comment]
Hi @joshkimux! Another one for your or Angela's review please when you have a moment :) thank you!

**Comment by joshkimux** [comment]
<img width="1089" alt="Screen Shot 2021-10-04 at 5 01 51 PM" src="https://user-images.githubusercontent.com/14154792/135924419-fcf0ebaf-2121-4c72-bdf5-8fd18ffe5e22.png">

Fantastic! 👏
