### ISSUE TITLE
[GIDS] [EKS] GIDS in dev redirects to the internal DNS record

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29041]
## Description
https://dev.va.gov/gids is saying service not found

Not sure exactly what needs to be done here.

## Background/context 
https://dsva.slack.com/archives/CG6N59X40/p1629141492002400?thread_ts=1627933224.001000&cid=CG6N59X40

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Think this works now since https://dev.va.gov/gids resolves. Not sure _what_ was done, but seems to be working at this time. Closing, but open to reopening if we see the need to.
