### ISSUE TITLE
Fix CC request practitioner submission and viewing

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#29056]
Two bugs related to CC practitioners in the vaos service

1. When we POST a CC request to the /v2/appointments, the `system` in `practitionerIds` should be set to `http://hl7.org/fhir/sid/us-npi`
2. When `practitioners` are returned when GETing a community care request (from /v2/appointments), instead of an `id` object, they have an `identifier` object now.

**Comment by laurenernest** [comment]
@jbalboni Any additional validation for this?

**Comment by jbalboni** [comment]
@laurenernest Looks good to me on staging
