### ISSUE TITLE
Access for Sebastian Cooper to AWS

### ISSUE THREAD

**Issue by SebVortex** [department-of-veterans-affairs/va.gov-team#29052]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
COR: Riley Ross
Vendor Onboarding Rep: Amy Kollar
Name: Sebastian S.A. Cooper
Email: Sebastian.Cooper@va.gov
Name of team: AFS-Education
Role & Company: React Developer from Accenture Federal Services.

- Requesting SSH key authorization?
   NO

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```

- Grant AWS Console access?
  > YES
- What AWS services do you need access to and why? 
  My team is assuming maintenance/support for Comparison Tool, Feedback tool, etc. from the current team. Please add me to the newly created group “afs-vfs-developers” and provide the same access as the group “bah-vfs-developers” so that we can continue to maintain the same level of support for Education Services.

**Comment by omgitsbillryan** [comment]
**For AWS Access:**
User: Sebastian Cooper
COR: Riley Ross
Approval needed: @mchelen-gov

I verified that this GH user is part of the department-of-veterans-affairs GH org.

**Comment by mchelen-gov** [comment]
request approved 👍

**Comment by jbritt1** [comment]
Temporary credentials provided to user at this time.
