### ISSUE TITLE
[DESIGN] My VA, Profile: 508 Banner Issue

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#29068]
## Background

This is a defect-4. 

From Josh:

While conducting the 508 office-- I noticed that for the Cerner user the blue banner at the top only has their name and not their status or disability. Visually, that’s no problem, but for folks with screen readers we come into a bit of a tricky situation.

Earlier, we worked with Erik to have the region read out as “My disability and status region” to separate it from the rest of the content on the page. That makes sense when it indeed does contain disability and status information, but it becomes a bit confusing in this context where they are absent.
Here’s my immediate thoughts:

- For a user who doesn’t have their disability or status loaded, is there a use case/purpose to show their name in the blue banner when it already appears in the header when they log in?
- If not, could we not show the blue banner?
- If yes, what could we rename the region so that it makes sense when disability and status are absent?

Would love your thoughts here!!
![Screen Shot 2021-08-23 at 11.58.50 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/5a372486-8f76-4dc5-9f66-4453baa927b3)

## Tasks
 - [ ] Discuss with team to answer these questions:
- For a user who doesn’t have their disability or status loaded, is there a use case/purpose to show their name in the blue banner when it already appears in the header when they log in?
- If not, could we not show the blue banner?
- If yes, what could we rename the region so that it makes sense when disability and status are absent?
- [ ] Create FE ticket

**Comment by andaleliz** [comment]
@joshkimux can you share a little more context about what a screenreader person will hear exactly when this is read out to them? Does the screenreader read out "My disability and status region, [all the content in the region]" or is it something different?

**Comment by joshkimux** [comment]
If they tab into it, they'll hear the object they've tabbed to followed by "My disability and status region"
If they read it in flow, they'll hear "My disability and status region" as a standalone announcement _before_ intentionally moving into the content of the region. It will not read all of its contents automatically.

**Comment by tressaellen** [comment]
The team decided the best direction to go in is "My information region". @ajakabcin will create a ticket for the FE work.

**Comment by ajakabcin** [comment]
Created #30202 as a frontend implementation ticket to change the banner name.

closing this - thanks Tressa!
