### ISSUE TITLE
Change naming of EmergencyBanner to just Banner

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#29069]
# Description

Currently the `<EmergencyBanner>` component is being used not as an emergency banner but rather a generic banner. The name should then be changed to `<Banner>` for simplicity + clarity.

## Acceptance Criteria

- [x] Change instances of [`<EmergencyBanner>`](https://github.com/department-of-veterans-affairs/component-library/tree/master/src/components/EmergencyBanner) to `<Banner>`.

**Comment by brianalloyd** [comment]
Completed, closing in support.
