### ISSUE TITLE
Onsite Search data for recurring reports

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#29063]
## Issue Description
Investigate whether data source for Onsite Search can be created/repurposed to include older data than the Standard Search source. This is related to Chris Johnston's request for a new monthly recurring report with 24-months of data for each KPI.

#### Related existing datasets
- [Standard Search](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/overview)
- [Generic All Site Searched by Day](https://va-gov.domo.com/datasources/e94aa216-38f5-483e-9eef-01421bc2ee37/details/overview)
---
## Tasks
- [ ] Discovery for creating search data set that includes older data, relevant fields.

## Acceptance Criteria
- [ ] Datasource in Domo for Onsite Search totals has at least 24 months of historical data – or we've confirmed that data that far back can't be tracked with facility searches excluded.

**Comment by bsmartin-ep** [comment]
@chloedotbrown -

We wouldn't get things like total search results, position clicked _etc_, but I don't see why we couldn't tie `page_path` in _Generic All Site Searched by Day_ to our standard search scope.  Looks like we only have site search and find forms in there, but that's definitely most searches on the site.

![image](https://user-images.githubusercontent.com/62304138/146617832-047c73c1-af1a-4eb1-a18b-09dd22632276.png)
