### ISSUE TITLE
Request access to Google Analytics for Abelardo Blanco

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#29065]
# Request Google Analytics access for Abelardo Blanco

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [X] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [x] Provide access to user
- [x] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Access has been granted.
