### ISSUE TITLE
Access for Adam Freemer

### ISSUE THREAD

**Issue by AdamFreemer** [department-of-veterans-affairs/va.gov-team#29061]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Amy Kollar
- Please provide your name.
   > Adam Freemer
- Please Provide your email.
   > adam.freemer@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > AFS-Education, Ruby Developer from Accenture Federal Services.

- Requesting SSH key authorization?
   > Yes 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUTfPbXOHgiIaOLZUfLfEG4ViSl0WZE4M1iADCRIdPwYAoEiQfiVS2LqJZ6+vzywqLrP5d5vGUh/vF9KqB8EZct+0As15QlKhXJHvQUUG/yjUC9IonUhkAhpm9fo+CCOvGwoVL+5yn9jAKqMJvIWNgrvW9k3K0gy+/eILp12zBDLP3obRmzM5EuVCtrPhrHjJTTekvS5y6CCHmrPbG3th5ElvhQV2lTpYnXp45EX5TO5JIz0blIjzU5yLm6LXwbkK+0/aYVpXyWuiKVSUV5lxKiuhY+hCWG/eoH2459jPRak7y1dtCj7Bi5A4bfN0Vd8rNMrClJYLJE5VvLg17dNN8FQ9xLip8sXm1T3QQGzv4Hnu3dMag+4SU2Jeam36WS1VSI0lzMHwEDA+YeGEmc6t9OoiIu1oIdxgf7XeBXqRWHRHUCUE5ukD6shcWIuvNKJffFXBhYkl8i+WB7guuc1SxLXXb4tnU45HeFD0UDlsqu1aPe5tMgSUOaIoic0789kE= adam.freemer@AFSMWX9K3EV6YHQ
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > My team is assuming maintenance/support for Comparison Tool, Feedback tool, etc. from the current team. Please add me to the newly created group “afs-vfs-developers” and provide the same access as the group “bah-vfs-developers” so that we can continue to maintain the same level of support for Education Services.

**Comment by omgitsbillryan** [comment]
**For AWS Access:**
User: Adam Freemer
COR: Riley Ross
Approval needed: @mchelen-gov

I verified that this GH user is part of the department-of-veterans-affairs GH org.

**Comment by AdamFreemer** [comment]
@omgitsbillryan - my computer had to be re-imaged so I have new keys I need for the SOCKS setup. This is the updated key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEgKKrgZOlGfpGjQD7hdycOZktFCeqTqsH2FpOQdzCh3ytbUybynfdyo6GjVBvEBQz/xdY0FHjIqasxaBkIMKkDLTopzxnMyXwKEgermV3zNDDBQdOrGuVfDDYUXD6svOzDZ0JPU5Jwddi/5UHYcT8a+JDQaEs8ZPfFnLaHssFnzmX3M9DAzsRla7E3Ll5mGNxPBv1nnCLaOPEtM1EMN4qYSc4zaeqmr7jWC/DDq38h6Fgj7HSybtc7Vs5ti6MrGrIPgEZrgWhxWOOK3zxaN0kxmsA+CbqFJDpIUC9NqrRP1p8J473LDqFO5JDIN9i5m0f7ik1R6fTDV65w+ueCT1FWizUFMn38s+1Wm5VJ4nNVVGCLfUTTREbUJqL0jPaTkt8VXbfNujjcs2V9uWhuKE9iJEC316y9Zz+HQgXmJ/ViLo6wdAhAg8ovzuAY2MfkqtyJwbWc+d6ZUc+pZ8xnP+qM1wTRvblZITHuu/+HArlFP/G4B2sMy+ORjyAToafs9U= adam.freemer@AFSMWX9K3EV6YHQ
```

**Comment by jbritt1** [comment]
Temporary credentials provided to user at this time.

**Comment by omgitsbillryan** [comment]
Temporarily re-opening. It looks like the socks key update that @AdamFreemer requested, never happened.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/29061#issuecomment-915556830
- https://dsva.slack.com/archives/CBU0KDSB1/p1632160195323200

**Comment by omgitsbillryan** [comment]
Socks was granted - closing again.
