### ISSUE TITLE
Adding Jonah Czerwinski to DSVA Slack

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#29072]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Jonah Czerwinski works in business development for Thoughtworks and is helping to structure the engagement with Thoughtworks and the digital health platform team.

## Sample Descriptions 
- Please add jonah.czerwinski@thoughtworks.com as a multi-channel guest to #digital-health-platform and #health-care-products-all-teams

**Comment by LizCallaghan** [comment]
done!
