### ISSUE TITLE
Add support for multiple banner types to `<Banner>`

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#29071]
# Description

The `<EmergencyBanner>` in the component library needs to support 5 types of banner type designs, but it currently only supports 2. You can see the currently supported types [here](https://github.com/department-of-veterans-affairs/component-library/blob/master/src/components/EmergencyBanner/EmergencyBanner.jsx#L89).

The banner type designs that need to be supported:

```js
{
  INFO: 'info', // Blue border, black circled 'i'
  ERROR: 'error', // Red border, red circled exclamation
  SUCCESS: 'success', // Green border, green checkmark
  WARNING: 'warning', // Yellow border, black triangle exclamation
  CONTINUE: 'continue', // Green border, green lock
}
```

## Acceptance Criteria

- [x] Add banner type designs to the Banner component

**Comment by brianalloyd** [comment]
Completed, closing in support.
