### ISSUE TITLE
Adding Chris Grenz to DSVA Slack

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#29073]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Chris Grenz is a technical principal at Thoughtworks who will be joining the team working on digital health platform.

- Please add christopher.grenz@thoughtworks.com as a full member, and add to these channels: #digital-health-platform, health-care-products-all-teams.

**Comment by LizCallaghan** [comment]
done!
