### ISSUE TITLE
[FE] My VA: 508-defect-2 [COGNITION, SCREENREADER]: Disability rating description in disability and status region must be remediated

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#29070]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a voice input user, I expect the visible link text to be included within the accessible link text so I can accurately select a link.

As a screen reader user, I expect to be able to hear my service connected rating if sighted folks can see it.

As a screen reader user, I expect description details to not repeat the description title (Your disability rating is repeated twice).

## Details

Two issues exist within the your disability rating description in the blue banner:
- The link "XY% service connected" has an `aria-label` that does not include the visible link text. This can create problems for voice input and screen reader users (see user stories).
- "Your disability rating" is repeated twice: once by `sr-only` text and another time in visible `dd` text

## Acceptance Criteria

- [ ] Accessible link text (`aria-label`) includes the visible link text "80% service connected"
- [ ] "Your disability rating" isn't announced twice

## Steps to Recreate

1. Log in as user 15 and go to My VA
2. Start screenreading device 
3. Navigate to the disability and status region
4. Confirm that "your disability rating" is announced twice
4. Tab to 80% service connected
5. Confirm "view your disability rating" is announced without mentioning "80% service connected"

### Duplicate disability rating string
- Was it intentional to have "Your disability rating" be visible?
  - If yes, remove the `sr-only` class from the `dt` "Your disability rating" and then delete the string "Your disability rating" from the `dd`
  - If no, delete the string "Your disability rating" from the `dd`

### Visible vs accessible link text
 "View your disability rating" provides purpose and target, but not the visible label.

A small change to the `aria-label` can include the visible label. For example:
`aria-label="80% service connected disability rating"` 

## Screenshots or Trace Logs

<img width="1030" alt="Screen Shot 2021-08-23 at 1 48 39 PM" src="https://user-images.githubusercontent.com/14154792/130495964-4fc096ce-25ae-4b15-b087-34076b546784.png">
<img width="1792" alt="Screen Shot 2021-08-23 at 1 47 11 PM" src="https://user-images.githubusercontent.com/14154792/130495986-78cbf98f-97ab-4e98-b7c9-4dbe7a7efa35.png">

**Comment by tmitchellgcio** [comment]
@ajakabcin ready for validation

**Comment by ajakabcin** [comment]
@joshkimux can you give this a look when you have a moment? thank you!

**Comment by joshkimux** [comment]
<img width="363" alt="Screen Shot 2021-10-01 at 11 27 00 AM" src="https://user-images.githubusercontent.com/14154792/135646555-7b73fccf-3157-4982-a487-5608060ffe5c.png">

Just a couple more small changes to make this parse better 🙇 

### Before
```html
<dl class="vads-u-margin-y--0">
  <dt class="sr-only">Name: </dt> <!-- Description Title -->
  <dd>Wesley Watson Ford</dd> <!-- Description-->
  <dd> <!-- Describing name? -->
    <dfn class="sr-only">Branch of service: </dfn> <!-- Unnecessary definition element -->
    United States Air Force
  </dd>
  <dt class="sr-only"> <!-- Empty description title --></dt>
  <dd>Your disability rating: <!-- Description to empty title -->
    <a href="/disability/view-disability-rating/rating" aria-label="View your 100% service connected disability rating">
      <strong>100% service connected </strong>
    <i aria-hidden="true" role="img" class="fas fa-chevron-right vads-u-padding-left--0p5"></i>
    </a>
  </dd>
</dl>
```

### After
```html
<dl class="vads-u-margin-y--0">
  <!-- First dt dd pairing, name -->
  <dt class="sr-only">Name: </dt> <!-- Description Title -->
  <dd>Wesley Watson Ford</dd> <!-- Description-->

  <!-- Second dt dd pairing, branch of service -->
  <dt class="sr-only">Branch of service: </dt> <!-- Delete dfn and replace with dt element -->
  <dd>United States Air Force</dd> <!-- Wrap description "United States Air Force" inside dd -->

  <!-- Third dt dd pairing, disability rating -->
  <dt>Your disability rating: </dt> <!-- Remove sr only from dt and place "Your disability rating" inside it
  <dd>
    <a href="/disability/view-disability-rating/rating" aria-label="View your 100% service connected disability rating">
      <strong>100% service connected </strong>
      <i aria-hidden="true" role="img" class="fas fa-chevron-right vads-u-padding-left--0p5"></i>
    </a>
  </dd>

</dl>
```

**Comment by AngelaFowler82** [comment]
I can confirm that the rating percentage is reflected in the link text which is accessible to screen readers, and that "Your disability rating" is only announced once.

**Comment by joshkimux** [comment]
This reads excellently. Well done team! 👏
