### ISSUE TITLE
Access for Dan Hinze for AWS Console

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#2908]
Hi, @department-of-veterans-affairs/vsp-operations , requesting AWS access and SSH access for VA APIS (my SSH key was previously added to the `authorized_keys` dir)

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Michael Domanski (VIEWS contract)
- Please provide your name.
   > Dan Hinze
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA Startup Team (about to sub on some work for the Authenticated Experience Team), Software Engineer, Ad Hoc

- [Grant AWS Console access?]
  > YES
  >  Moving into backend API work (previously only frontend) and I need AWS access so I can SSH into dev/staging VA APIs

**Comment by ricetj** [comment]
@Jeff-Hayter
COR: N/A (currently in contractual limbo on the VA Startup Team)
User: Dan Hinze

**Comment by Jeff-Hayter** [comment]
@hinzed1127 Unfortunately I can't check anything without the name of the COR.  Are you heading to the VSA contract?

**Comment by hinzed1127** [comment]
@Jeff-Hayter that makes sense. Yes, this would be for work under VSA.

**Comment by hinzed1127** [comment]
Hey @Jeff-Hayter, some updates for you that should clear the way for access:
**Contract**: VIEWS
**COR**: Michael Domanski
Let me know if there's anything else you need

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.  Waiting on eQIP confirmation for AWS.

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for AWS.

**Comment by hinzed1127** [comment]
@department-of-veterans-affairs/vsp-operations / @Jeff-Hayter 

There was a [sweep of IAM AWS users](https://dsva.slack.com/archives/C03FECE9K/p1586522678034600) in April to maintain ATO compliance. I didn't think I would need future access at the time, but once again I do. Details in the description here remain the same.

**Comment by drorva** [comment]
@hinzed1127 do you have access at this point?
If not, I'm approving this request.

**Comment by hinzed1127** [comment]
@drorva I'm able to log in, but I'm still seeing a lack of permissions in most places. I'm specifically looking for jobs in ECR and Codebuild and everything is showing various not authorized errors.
