### ISSUE TITLE
[Alerting/Documentation] Update Platform Operations alerting page to include Sentry

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29087]
## Description
Update https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting to include Sentry and its alerting possibilities.  Also link to documentation defining how to do so.

## Background/context 
- https://dsva.slack.com/archives/CBU0KDSB1/p1629736131288400?thread_ts=1629734512.272600&cid=CBU0KDSB1 

---
## Tasks
- [x] Update confluence to include information about sentry

## Acceptance Criteria 
- [x] Everyone has the information needed to alert from sentry

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball - Please check off tasks and acceptance criteria (you can re-write for accuracy if needed).

**Comment by jhouse-solvd** [comment]
This has been done. Please see the linked documentation above. 

If more is needed, please create a new issue with specifics. 

Closing.
