### ISSUE TITLE
[Research] Conduct research on Short Form (10-10EZ)

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#29089]
## User Story

_As a user I would like to have this feature because it would help me with this pain point_

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by Dene-human** [comment]
[Research notes](https://docs.google.com/spreadsheets/d/1vuYPB8Q3kzm1y3eCLAa_ncc6zvdmSCvRssR_PsJNyhc/edit#gid=161699097)

**Comment by Dene-human** [comment]
Research is complete. 
- [Session notes ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/Session%20notes)
