### ISSUE TITLE
[Research] Create prototype for Short Form (10-10EZ)

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#29088]
## User Story

_As a user I would like to have this feature because it would help me with this pain point_

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by Dene-human** [comment]
[Immediate short form](https://preview.uxpin.com/acda277e33e9629a7ab817f6c93c251b4a60ac56#/pages/141488399/simulate/no-panels?mode=i)
[Self-reported short form](https://preview.uxpin.com/19ee97072a3233029149e8865f986abfda4c1aef#/pages/141488374/simulate/no-panels?mode=i)
