### ISSUE TITLE
Feedback Tool: Incorrect OMB date 

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#29085]
## What happened?
The Feedback Tool is showing an incorrect expiration date at the bottom of the main page.  This date appears in both staging and production.

**Prod:** 
![image.png](https://images.zenhubusercontent.com/60bfb0a65b600c166b5779ed/1eab1588-bdd1-4971-9aa3-4f05f27b85e0)

**Staging:**

![image.png](https://images.zenhubusercontent.com/60bfb0a65b600c166b5779ed/178e4469-3ad6-4819-a670-4e0828180fb0)

## Steps to Reproduce
For Staging:
1. Navigate to https://staging.va.gov/education/submit-school-feedback/introduction
2. Scroll to the bottom to see the date.

For Prod:
1. Navigate to https://www.va.gov/education/submit-school-feedback/introduction
2. Scroll to the bottom to see the date

## Desired behavior
The correct date of **01/31/2022** is displayed

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mrblanco1** [comment]
Dev found the OMB date is hard-coded in this jsx file:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/feedback-tool/containers/IntroductionPage.jsx

Once the update is made and validated locally, Dev will deploy to Staging /where QA will conduct their final validation.  ETA at this point for this fix to be released to prod is tomorrow 8/24/2021 with the 2pm auto-deployment.

**Comment by SebVortex** [comment]
Associated PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/18366

**Comment by jfinnern** [comment]
![Screen Shot 2021-08-24 at 1.12.37 PM.png](https://images.zenhubusercontent.com/60e85c574d27f28c9ab35457/9666361e-63ae-4519-86a4-48a1a965138e)

**Comment by jfinnern** [comment]
Validated in staging the "Expiration date:" field has been updated
https://dsvavsp.testrail.io/index.php?/runs/view/2146&group_by=cases:section_id&group_order=asc

**Comment by SebVortex** [comment]
Branch "29085-Incorrect-date-2" in vets-website has been changed to show the correct date no matter the environment.

**Comment by SebVortex** [comment]
Draft Pull Request has been made.
https://github.com/department-of-veterans-affairs/vets-website/pull/18375

Review from vfs-platform-support should come soon.

**Comment by SebVortex** [comment]
Squashed and merged. Moving to closed.
This was a nice practical exercise for the workflow.
