### ISSUE TITLE
[Design] 10-10EZ Intro: Update wording of the Healthcare Eligibility Center

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#29094]
## User Story

As a Veteran applying for healthcare, I need to know who to contact if I have questions.

Purpose: Update wording on the **Need Help** section of the 10-10EZ Intro page:

![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/1cf9fc1e-3922-4c2c-a40c-589bcfc36842)

The purpose of this story is to update the Content Source of Truth for this change.

## Expected Behavior

Change "Health Resource Center" to "Health Eligibility Center"

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by Dene-human** [comment]
This was already completed in ticket #29090
