### ISSUE TITLE
Add react-axe to dev watch task on vets-website

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2909]
This will check react components for axe errors during the development process and show an error in chrome console 

- https://github.com/dequelabs/react-axe
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/43ffd6bf579559543369c16b3e250c0f838136e2/packages/accessible-react-app/src/index.js#L8

**Comment by timwright12** [comment]
Update: new package for this: https://www.npmjs.com/package/@axe-core/react

**Comment by timwright12** [comment]
This was completed with https://github.com/department-of-veterans-affairs/vets-website/commit/ef120b111a325be65158ef94a6ccc40de8105094

Closing out.
