### ISSUE TITLE
Contact Center prepare for launch of Epic #756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2911]
Contact Center prepare for launch of Epic #756 Texting for Medical Appointments

This item follows the steps outlined in the following document:
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-contact-center-review.md#request-a-contact-center-review.

Basically there are two things needed to resolve this issue.
1- Update of the Existing Product Guide-Clarice
2- Preparation of the Video and Transcript for the Contact Center-Bylight

**Comment by lichellebain** [comment]
@claricechan and @clantosswett I have attached the transcript below, however I am unable to attach the video--the file type is unsupported.  What is the best way to get you the video to review?

[https://app.zenhub.com/files/133843125/e53d85f3-d37b-40ff-82d7-2b8ab0be7ee8/download](https://app.zenhub.com/files/133843125/e53d85f3-d37b-40ff-82d7-2b8ab0be7ee8/download)

**Comment by clantosswett** [comment]
Hi @lichellebain I can't download the product guide from the link in your comment. As for the video, we are trying to set up a process for uploading demo videos to the VA.gov youtube site in an unlisted format. It might be some time until that is available so for the time being, is it possible to upload the video to google drive and share that link here? Alternatively, I've had teams reduce the file quality significantly and zip the file and email it to me. 

Finally, do we have a go-live date for this?

**Comment by lichellebain** [comment]
@clantosswett The file is small enough to email.  What is your email address?

Release date is Nov 15--last I heard.

**Comment by lichellebain** [comment]
Video and Transcript were emailed to Chante on 10/30/19 for her review.

**Comment by lkoenigsberg** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/2901

**Comment by lichellebain** [comment]
Screen shots were sent to Clarice on Tuesday afternoon (11/5/19) for the Product guide.

**Comment by claricechan** [comment]
Attached are **PDF** and **Word** versions of the final **Product Guide**. 

[Feature Guide VA.gov SMS Notification Preferences.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3822095/Feature.Guide.VA.gov.SMS.Notification.Preferences.docx)

[Feature Guide VA.gov SMS Notification Preferences L.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3822094/Feature.Guide.VA.gov.SMS.Notification.Preferences.L.pdf)
