### ISSUE TITLE
[Tier 3] Disability Claim Application Issue wit Application ID number (3589519)

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#29115]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Initials: J.C.

Issue:  Cannot submit disability Claim application

ID: 3589519

Link for more information:

**Comment by annaswims** [comment]
There is no form currently in progress with the id. Perhaps this means the veteran succeeded or perhaps it means they started over with a new form. Either way it's hard to tie back to any veteran activity.

**Comment by Kimberley2019** [comment]
Reached out to veteran to determine if he was able to submit.

From: VA Technical Support 
Sent: Thursday, September 2, 2021 2:21 PM
To: 'J Catamisan' 
Subject: RE: [EXTERNAL] Re: Disability Claim Application Issue

Good Afternoon Mr. Catamisan,

Thank you for your service.

I wanted to reach out and inquire if you were able to successfully submit your claim.  The technical team as indicated that there is no form in progress which means either you were able to submit or you have started over with a new form.

Can you please advise if either of those options are correct?  If you are still experiencing issues with submitting your claim, please send over the required information so that the technical team can review again.



Kind Regards,

The VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
@annaswims @vhenry07 
Please see response from veteran below:

From: J Catamisan 
Sent: Thursday, September 2, 2021 3:13 PM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: RE: [EXTERNAL] Re: Disability Claim Application Issue

Good Afternoon,

I am showing a status of a new claim to see if by starting over it would work. It didn't work and it shows the same thing click here to finish the application dated 24 Aug 21. So it is there and still not working. Not on my end as I have tried a myriad of times.

v/r
J Catamisan

**Comment by annaswims** [comment]
@Kimberley2019 Could you get the new form id from him?  the id reset when it started over.  It's clearly something related to his personal data, but we'll need to find his data to track it down.

**Comment by annaswims** [comment]
@Kimberley2019  can we close this one?

**Comment by Kimberley2019** [comment]
From: Reinold, Cody <Cody.Reinold@va.gov> 
Sent: Tuesday, September 14, 2021 4:58 PM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: RE: My VA411 Follow Up - Two Factor Authentication Issue

This is a new one for all of us…very unique. Forwarded it on to the guy who works with this system, specifically. Will keep you posted.

Cody

Cody Reinold
U.S. Digital Service
Office of the Chief Technology Officer
Department of Veterans Affairs

From: VA Technical Support <VATechnicalSupport@va.gov> 
Sent: Tuesday, September 14, 2021 4:14 PM
To: Reinold, Cody <Cody.Reinold@va.gov>
Subject: FW: My VA411 Follow Up - Two Factor Authentication Issue

Hey Cody,

Here is the issue I was discussing below.  As you can see, this is all he provided, but have no issue reaching out if you need additional information, let me know.

Would it be beneficial for me to open a ticket in ZH for you/your team?



Kind Regards,

Kimberley
