### ISSUE TITLE
Back to top component is not bottom right aligned on desktop

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#29126]
## What happened?
On hub pages, the back to top component is not bottom right aligned on screens > 768px

## Specs:
- Device: Macbook 
- Browser: Chrome

## Steps to Reproduce
- URL: I saw it on https://www.va.gov/decision-reviews/supplemental-claim/ and https://www.va.gov/health-care/covid-19-vaccine/; I suspect it's on all the hub pages.
![Screen Shot 2021-08-24 at 10 50 25 AM](https://user-images.githubusercontent.com/55992116/130639522-794be1b3-5e1f-4b7a-a7df-425bdd3eadfe.png)

## Desired behavior
Back to top component should be bottom right aligned with main content area.

## Acceptance Criteria
- [ ] Back to top component is bottom right aligned with main content area.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Rleahy22** [comment]
This fix should got out with the Tues (9/14 deployment)

**Comment by brianalloyd** [comment]
Great work, thanks Ryan.  Validated and closing.
