### ISSUE TITLE
Enable changed application builds for dev in PR CI

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29137]
## Description

The current dev build build the entire application suite. This update should build only the changed applications for dev.

We should be able to get a list of the changed files and deduce which application or applications they are from. This work should happen in CI for a Pull Request. Follow up tickets will handle `master` and deployments.

## Definition of Done

- [ ] The dev build in CI only creates files for the changed application
- [ ] The dev build can detect and run builds for multiple changed applications
- [ ] tar file artifact is still created and uploaded to S3

**Comment by alexandec** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/19335), going to close this one.
