### ISSUE TITLE
[ZOOM]: VAOS Scheduler - Add another Community Care provider layout gets unstable above 250% zoom at 1280px

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2914]
## Description

The Add Another Community Care provider layout becomes unstable when I set my browser width to 1280px and zoom above 250%. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a user who zooms my layout, I want to be able to view the add a community care and edit community care providers at up to 400% normal layout to satisfy WCAG 2.1 guidance.

## Environment
* /vaos/new-appointment/community-care-provider

## WCAG or Vendor Guidance (optional)

* [Success Criterion 1.4.10 Reflow](https://www.w3.org/TR/WCAG21/#reflow)

## Screenshots or Trace Logs

![Screen Shot 2019-10-29 at 4 52 41 PM](https://user-images.githubusercontent.com/934879/67813062-a306f700-fa6e-11e9-8b7f-b78a572c1991.png)

**Comment by narin** [comment]
@markgreenburg @1Copenut  This ticket was created a while back and I don't believe this page exists in the flow anymore.  Currently, the user is only able to add 1 CC provider on the CC preferences page, and the closest thing to being able to edit it is on the review page which looks okay at 200% zoom (screenshot below). 

Should we close this ticket, or keep it open and have @1Copenut adjust it to any new issues with CC providers he finds?

![image](https://user-images.githubusercontent.com/786704/73089530-48bddc80-3e8b-11ea-9c20-5669d168062f.png)

**Comment by markgreenburg** [comment]
@narin I'm going to close this one out since the main issue noted here is for a piece of UI that no longer exists. @1Copenut lemme know if you have any objections.
