### ISSUE TITLE
Enable changed application builds for staging in PR CI

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29141]
## Description

The current staging build builds the entire application suite. This update should build only the changed applications for staging.

We should be able to get a list of the changed files and deduce which application or applications they are from. This work should happen in CI for a Pull Request. Follow up tickets will handle `master` and deployments.

## Definition of Done

- [ ] The staging build in CI only creates files for the changed application
- [ ] The staging build can detect and run builds for multiple changed applications
- [ ] tar file artifact is still created and uploaded to S3

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19458) for this has been merged, and confirmed to be working ✅

[GHA run](https://github.com/department-of-veterans-affairs/vets-website/runs/4292274392?check_suite_focus=true) ([vagovstaging.tar.bz2](https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/c1ac734eaa93d23e1108790f5b53ae85bb9b68a3/vagovstaging.tar.bz2))
