### ISSUE TITLE
[ZOOM]: VAOS Scheduler - The Back link competes with breadcrumb back-by-one at mobile sizes

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2915]
## Description

The < Back links compete with our back-by-one breadcrumb link at mobile sizes. This isn't a defect per se, but could be an opportunity to improve the user experience. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a user who zooms my layout, I want to be able to view one link that will let me step back to my appointments or the VAOS landing page.

## Environment
* /vaos/appointments/confirmed
* /vaos/appointments/confirmed/<UNIQUE_ID>
* /vaos/appointments/pending
* /vaos/appointments/pending/<UNIQUE_ID>

## Screenshots or Trace Logs

<img width="1262" alt="Screen Shot 2019-10-29 at 4 54 06 PM" src="https://user-images.githubusercontent.com/934879/67813397-6ee00600-fa6f-11e9-9778-dce753dbb1c9.png">

**Comment by rtwell** [comment]
This back link wont exist as this page / list feature has been redesigned, see #2306

**Comment by 1Copenut** [comment]
@rtwell Cool, I'm looking at #2306 now, moving this one to close. Thank you for confirming.
