### ISSUE TITLE
Move 10-10CG Grafana Alert Out of #devops-alerts & Route to Caregiver Team

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#29154]
## The Problem
Grafana is alerting to #devops-alerts slack channel. The devops team has no way to meaningfully respond to this alert so it has become noise.
![image](https://user-images.githubusercontent.com/3077884/130659845-662d7049-e2af-448d-929c-ec11fa37ffe1.png)

## Extra Context
- Link to Slack alert - [link](https://dsva.slack.com/archives/C24RH0W11/p1629818424085100)
- Slack thread where @mchelen indicates that this should be owned by Caregivers team - [link](https://dsva.slack.com/archives/C24RH0W11/p1629820804087800?thread_ts=1629818424.085100&cid=C24RH0W11)

## Work to be Done
- [x] Make this alert stop reporting to #devops-alerts slack channel
- [ ] Route to caregivers
  - [ ] Identify appropriate slack channel
  - [ ] Alert routes to ☝️ slack channel

**Comment by mchelen-gov** [comment]
grafana panel: http://grafana.vfs.va.gov/d/0beXyL7nz/dror-test-2?editPanel=4&tab=alert&viewPanel=4&orgId=1

**Comment by drorva** [comment]
Oops, my bad. So that's where my alert went. I thought setting the channel in the config would override the default.
I own this pilot and am documenting it in https://vfs.atlassian.net/wiki/spaces/~722865800/pages/edit-v2/1839759431
@omgitsbillryan  How/where I get an API URL to alert from Grafana to Slack?

**Comment by omgitsbillryan** [comment]
I think you can use a Slack App or an "Incoming Webhook" custom integration - both of which are configured in the dsva slack workspace
- https://dsva.slack.com/apps/A0F7XDUAZ-incoming-webhooks?tab=more_info
- https://app.slack.com/apps-manage/T03FECE8V/

I've only ever configured the former, so I know that the slack channel (among other things) gets configured there. There's no overriding the slack channel AFAIK.

Looking at the existing slack alert, [it's currently using `VFS Grafana Monitoring` slack app](https://dsva.slack.com/apps/A011F3UKTEG-vfs-grafana-monitoring?settings=1). I think this app could receive additional config to post to more slack channels but @boris-ning-usds owns it. Short of him specifically, I think you may find someone to help in `#slack-workspace-admins`

**Comment by SKasimow** [comment]
@lihanli - can we do something similar to what's referenced in this ticket and have the Datadog alerts go into our Slack channel?

**Comment by lihanli** [comment]
@SKasimow the datadog alerts are already setup to send messages to the `vsa-1010-apm` slack channel

**Comment by hdjustice** [comment]
This ticket has been completed, the alert stopped publishing in the Devops slack channel in August 2021
