### ISSUE TITLE
EDU: Remove BAH as Codeowners in gibct-data-service and vets-website

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29159]
As a repo manager, I need to remove BAH team members from being code-owners on the repositories so that they no longer have access because they no longer support this project.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The BAH team is no longer a code owner for the gibct-data-service repo.
2. The BAH team is no longer a code owner for the vets-website repo.

## Supporting Artifacts:
1. https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/CODEOWNERS#L92
2. https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/.github/CODEOWNERS

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/861
https://github.com/department-of-veterans-affairs/vets-website/pull/18690

**Comment by shawkey-daniel** [comment]
Both PRs are merged into master. Closing this issue.
