### ISSUE TITLE
Access for change Patrick Arthur, give AWS access

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#29152]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Riley Ross
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Amy Kollar
- Please provide your name.
   > Patrick Arthur
- Please Provide your email.
   > Patrick.Arthur1@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > AFS-Education from Accenture Federal Services

- Requesting SSH key authorization?
   >  NO 
- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? - My team is assuming maintenance/support for Comparison Tool, Feedback tool, etc. from the current team. Please add me to the newly created group “afs-vfs-developers” and provide the same access as the group “bah-vfs-developers” so that we can continue to maintain the same level of support for Education Services

**Comment by omgitsbillryan** [comment]
For AWS Access:
User: Patrick Arthur
COR: Riley Ross
Approval needed: @mchelen-gov

I verified that this GH user is part of the department-of-veterans-affairs GH org.

**Comment by mchelen-gov** [comment]
request approved 👍

**Comment by jbritt1** [comment]
Temporary credentials provided to user at this time.
