### ISSUE TITLE
Analytics KPI dashboard request for [Facilities]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29160]
# Request a Standard KPI Dashboard

## What this form is for

Use this template to request a KPI dashboard on Domo for your product. 

We are currently only supporting standardized dashboards for Forms, Content, & Search products. If you have another VA.gov product, please reach out to the Platform Analytics & Insights team on #vfs-platform-support. Please note that these dashboards will require additional data and design discovery, and will take additional time to deliver.

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 

- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).

### Expected delivery timelines

Your KPI dashboard request will be added to the Platform Analytics & Insights team's customer support queue, and we expect tickets at the top of the queue to be pulled in every Platform Sprint Planning & Refinement (every Wednesday). We appreciate your patience.

- Once your ticket has been pulled into the Platform sprint, we expect to deliver your completed dashboard within the next 4 business days. Please use this ticket for any follow up questions.

## Instructions for the VFS team

- [x] **Please fill out [this template](https://docs.google.com/spreadsheets/d/1dIh-MVmVYCc2mZ_b_8y-cPVZB5-8RIShuOP_ng9uqAA/edit#gid=0) ([attached Excel sheet](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo) if you do not have Google access) & link it below to help define your product/feature's information.** The Analytics team will ***not*** be able to pull this ticket into the queue until this is provided & linked. 
    - [Link to request template](https://docs.google.com/spreadsheets/d/1N6KWvbMeV3W51WKNLsn5_kYEa69r-Eo4-AWxA4ZWD3Y/edit?usp=sharing)
    - [Vet Center KPI Dashboard request.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7041456/Vet.Center.KPI.Dashboard.request.xlsx)
- [x] Add your team label to follow progress
- [x] If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).
     - Already have access 

## VFS-provided information

[Funnel Information](Add your product/feature's funnel information here) - Add your product/feature's funnel information here
- Veterans may arrive directly or by clicking the name of the Vet Center in search results on the [Facility Locator](https://www.va.gov/find-locations) (when facility type = Vet Centers)
- FYI, for Vet Centers which are not live, clicking the name will send them to a detail page within Facility Locator. For example, [a search for Vet Centers in Colorado Springs](https://www.va.gov/find-locations/?address=colorado%20springs%2C%20co&bounds%5B%5D%5B%5D=-105.5753&bounds%5B%5D%5B%5D=38.084&bounds%5B%5D%5B%5D=-104.0753&bounds%5B%5D%5B%5D=39.584&context=Colorado%20Springs%2C%20Colorado%2C%20United%20States&facilityType=vet_center&latitude=38.834&longitude=-104.8253&page=1&radius=58&serviceType&bounds%5B%5D=-105.5753&bounds%5B%5D=38.084&bounds%5B%5D=-104.0753&bounds%5B%5D=39.584) yields two results: 
  - Colorado Springs Vet Center, which is live and goes to the new [web page](https://www.va.gov/colorado-springs-vet-center/)
  - Pueblo Vet Center, which is not live and uses the [legacy detail page](https://www.va.gov/find-locations/facility/vc_0542V). these urls are updated as pages go live. 

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Build (See [internal process document](https://vfs.atlassian.net/wiki/spaces/AT/pages/1464598569/New+KPI+Dashboard+Request+Process) & [how to](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/WIP%2B-%2BHow%2Bto%2Bcreate%2Bstandardized%2Bdashboards%2Bin%2BDomo))

- [ ] Add the `VSP Analytics & Insights` Group as the dashboard owner
- [ ] Structure funnel data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Document any blocked/unavailable metrics in the Analytics team space
- [ ] Update the dashboard header, including Google Analytics links
- [ ] If any, add [implementation issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) for additional necessary implementation

2. Q&A

- [ ] Please see & complete the [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

3. Share

- [ ] Add VFS group & default group to the dashboard

  *For new VFS customers only:* 

- [ ] Schedule onboarding meeting

- [ ] Host the meeting to explain how the dashboard works

## Definition of Done

- [ ] Acceptance Criteria has been completed
  - [ ] KPI Dashboard full QA checklist completed
- [ ] Dashboard has been shared back with the VFS team

**Comment by laurensimpson14** [comment]
## QA


**regex:**
`www.va.gov/[^/]+-vet-center`

### Highlights

Chart title | Assets | Pass / Fail
-- | -- | --
Usage trends |  Unique Engagements: [custom report](https://analytics.google.com/analytics/web/template?uid=3OW7IOZGT2iqDQYkRElziQ)<br>Unique Sessions: [custom segment](https://analytics.google.com/analytics/web/template?uid=hZ6CPl-eRM2KGjxyc8jDQQ)   |  :green_circle: PASS
Unique users |   |  :green_circle: PASS
Unique pageviews |  Filtered report:  [report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210822&_u.date01=20210828&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22www.va.gov~2F%5B%5E~2F%5D+-vet-center%22,0%5D%5D&explorer-table.plotKeys=%5B%5D/) |  :green_circle: PASS
Avg. seconds to click |  (BigQuery only metric)  |  :green_circle: PASS
Avg. star ratings |  n/a  |  n/a 
Total clicks by device | Custom report: [report](https://analytics.google.com/analytics/web/template?uid=3_J0_ILpSTmqIA6E6kCXMg)  |   :green_circle: PASS

### Links

Chart title | Assets | Pass / Fail
-- | -- | --
Link engagement rate | | :green_circle: PASS
Avg. link clicks per session | | :green_circle: PASS
Total link clicks | (use Link Engagement CR) | :green_circle: PASS
Links with highest engagement | (use Link Engagement CR page 2)| :green_circle: PASS

### Buttons and action links

Chart title | Assets | Pass / Fail
-- | -- | --
Buttons with highest engagement |  | :green_circle: N/A
Button engagement rate |  | :green_circle: N/A
Avg. button clicks per session | | :green_circle: N/A
Total button clicks |  | :green_circle: N/A

### Anchor Links

Chart title | Assets | Pass / Fail
-- | -- | --
Anchor link engagement rate | Custom segment: [segment](https://analytics.google.com/analytics/web/template?uid=F-tVwGyoSXmrnZ-C3hTFUA) |  :green_circle: PASS
Avg. anchor link clicks per session | | :green_circle: PASS
Total anchor link clicks | Custom report: [report](https://analytics.google.com/analytics/web/template?uid=sH84G69hSKaW7Nfg8sgGCw) | :green_circle: PASS
Anchor links with highest engagement | Custom report (page 2) | :green_circle: PASS

### Accordions

Chart title | Assets | Pass / Fail
-- | -- | --
Accordions with highest engagement | Custom report (Page 2): [report](https://analytics.google.com/analytics/web/template?uid=BFrfxlPLSe2pZKBzoay5pQ)  | :green_circle: PASS
Accordion engagement rate | |  :green_circle: PASS
Avg. accordion opens per session | | :green_circle: PASS
Total accordion opens | Custom report (page 1) | :green_circle: PASS

### Misc
Chart title | Assets | Pass / Fail
-- | -- | --
Avg. scroll depth | Custom report: [report](https://analytics.google.com/analytics/web/template?uid=oMkXpzdUQ-iRsH6380gD3Q) | :green_circle: PASS
Top pages previously viewed |  Custom report: [report](https://analytics.google.com/analytics/web/template?uid=wzjrlGcmQyaDzC65kFmfgg) |  :green_circle: PASS
Devices used to access the page |  Custom report: [report](https://analytics.google.com/analytics/web/template?uid=8Ph8wqsZROWv6ntGJDX-aQ) |  :green_circle: PASS

**Comment by laurensimpson14** [comment]
@mmiddaugh QA has been completed and Vet Center content is now on the [Content KPI Dashboard](https://va-gov.domo.com/page/426422632?userId=1292731753)! You can view your data by filtering the product at the top of the dashboard to be `Vet Center pages`. 

I'll close this ticket, though feel free to follow up if you have any questions.
