### ISSUE TITLE
Review Top task content model murals before 9/1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29175]
## Issue Description
The Facilities team will soon be implementing FE changes for top task pages which were recently hardened by CMS. Prior to a meeting with CMS about this work, we need to review the content model information and confirm that we have everything we need to do this work. 

---
## Tasks
- [x] Review the following content model murals for understanding
      - [Register for care](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1594821112000/9932af464534c2676a2656992de3cf809cfad97b)
      - [Medical records](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595862359396/4d517fc3ffe0e6e9ec9fb81ff4325a4d7d1946d4)
      - [Billing and insurance](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595854648224/23c83ef3ccbbd06cd4d5afd59db5ddfa5688a8e1)

## Acceptance Criteria
- [x] Document questions/missing details for discussion during CMS/Facilities sync on 9/1

**Comment by mpelzsherman** [comment]
This mural currently contains a mockup of the new pages with a bunch of notes. In order to proceed with implementation, we need to know the bundle_type(s) and field names in the content model.

RE: this comment:
> We need to figure out a way to "Tokenize" the Facility or health system name

I’m imagining we could implement this as a liquid filter function, passing in an object mapping token strings to their corresponding values, e.g.

```js
{
  "SYSTEM_NAME": "{{ fieldOffice.entity.entityLabel }}"
}
```

**Comment by mpelzsherman** [comment]
Murals need to spell out which content is coming from CMS vs. hard coded, and supply field names and full graphql paths for all CMS content.

I can't think of any other questions at this time.

**Comment by mmiddaugh** [comment]
Replacing this with individual issues
