### ISSUE TITLE
[Bug] SOCKS `va-socks` EC2 instances not pushing logs to CloudWatch

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#29180]
## The Problem
Cloudwatch stopped receiving logs from `va-socks` instances as of `2021-08-20 13:15:47 (UTC-04:00)`.
![image](https://user-images.githubusercontent.com/3077884/130682804-89879953-f530-43b3-ad5f-8ee313957551.png)

Seems like an IAM permissions issue - found this in `/var/log/awslogs.log` on the EC2 inststance:
```
ClientError: An error occurred (AccessDeniedException) when calling the PutLogEvents operation: User: arn:aws-us-gov:sts::XXXXXXXXX:assumed-role/dsva-vetsgov-utility-va-socks-role/i-0f0fXXXXXXXX is not authorized to perform: logs:PutLogEvents on resource: arn:aws-us-gov:logs:us-gov-west-1:XXXXXXXXX:assumed:log-group:dsva-vetsgov-utility/var/log/secure:log-stream:deployment-utility-va-socks-20210823-175728-172.31.2.253
```

## Extra Context
This was discovered as part of a separate outage regarding CMS DNS - [slack link](https://dsva.slack.com/archives/CBU0KDSB1/p1629741457298900?thread_ts=1629739487.292900&cid=CBU0KDSB1)

☝️ That outage was root caused as an IAM problem that prevented deployments from copying files from an S3 bucket. Various IAM SSM permissions were modified as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/23969. I believe this cloudwatch logs issue is related.

## Work to be Done
- [x] Restore `va-socks` cloudwatch logs functionality

**Comment by omgitsbillryan** [comment]
CloudWatch logs are back in business 
![image](https://user-images.githubusercontent.com/3077884/130714823-62649742-e605-46e8-b9c1-f36e44d813dc.png)


Closing.

**Comment by jhouse-solvd** [comment]
It looks like this is good to go. Please see the previous comment. 

Closing.
