### ISSUE TITLE
VSA Benefits & Memorials 2 KPI Workshop

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2919]
## User Story
As a VFS team, I need to set my KPIs so I can see what my data-driven product goals are before I begin building my veteran facing product.

## Goal
Hold KPI workshop with the VSA Benefits & Memorials 2 team and set KPI tracking expectations.

## Objective
Workshop KPI setting with VSA Benefits & Memorials 2 and VSA Caregiver so that they can set data-centered goals for their product before they begin to build.

## Acceptance Criteria
- [ ] Schedule KPI setting workshop with the team
- [ ] Send out pre-workshop work
- [ ] Host KPI setting workshop
- [ ] Send KPI workshop excel sheet to the team
- [ ] Follow up with team PM on KPI check ins

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
Reached out to Nick on 12/19 for new times

**Comment by nedierecel** [comment]
@joanneesteban I sent a calendar invitation for 1/7 for a 90-minute session. Two follow-ups please:

- [ ] May I grab your Zoom?
- [ ] I have not followed up with pre-work if you can please distribute.

**Comment by joanneesteban** [comment]
@nedierecel 
Following up here (also from our Slack convo)
- The Google event won't allow me to edit, so we can use the same Zoom info from the Caregiver workshop:

>https://zoom.us/j/764375299
>
> Join Zoom Meeting
> https://zoom.us/j/764375299
> 
> Meeting ID: 764 375 299
> 
> One tap mobile
> +16468769923,,764375299# US (New York)
> +16699006833,,764375299# US (San Jose)
> 
> Dial by your location
>        +1 646 876 9923 US (New York)
>        +1 669 900 6833 US (San Jose)
>        +1 408 638 0968 US (San Jose)
> Meeting ID: 764 375 299
> Find your local number: https://zoom.us/u/aCaXFMG5m

- Nick has the pre-work from our initial conversations with him earlier in the Fall, but I'll remind him of that portion on Slack

**Comment by joanneesteban** [comment]
Workshop was scheduled for 1/7/20, but has been rescheduled so that we can include the product owner, Matt. Will be pushing back Sprint 17.

**Comment by joanneesteban** [comment]
Status Update on 1/15/20: Waiting on the B&M 2 team to provide us with times that both their PM and PO can attend.

**Comment by joanneesteban** [comment]
Adding a blocked label since we have not heard back from the team about availability. Switching tactics and adding Matt directly to the conversations.

**Comment by nedierecel** [comment]
Resources for Today's BAM2 Workshop:

- [KPI Prework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/KPI.md)
- [KPI Google Sheet](https://docs.google.com/spreadsheets/d/17VZ3hvvi1WSY0aHiDFtc7fmJTvL_1De8L20g6CQYJ8c/edit#gid=1554481611)
- [Optimal Workshop Post-KPI Workshop Survey](https://adhoc.optimalworkshop.com/questions/3g071kfh)

**Comment by nedierecel** [comment]
@wygonikGCIO Thank you so much for a really active discussion on Friday. I wanted to leave you with a few resources from our call:

- [KPI Worksheet](https://docs.google.com/spreadsheets/d/17VZ3hvvi1WSY0aHiDFtc7fmJTvL_1De8L20g6CQYJ8c/edit#gid=1554481611)
- [Zoom Recording](https://zoom.us/rec/share/5vJWBrHXx21JfM-d4W36B7w7QpXXT6a8gyIe-vNYyR45dBMnXkV5aeWtlvYqaGli)

Next steps:
- We encourage you to complete the remaining columns for the metrics you outlined.
- Review again with the team to determine priority of these metrics as it relates to your OKRs. 
- Please reach out to us in #vfs-analytics if you need anything!
