### ISSUE TITLE
Update Contact Us component to allow content from an external source (Drupal)

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#292]
We need to have the contact us menu content that exists in the header and footer be sourced from Drupal. We also need our application code to be independent of Drupal content changes.

This means we need to externalize that content in some way. For the mega menu, we have an external json structure with link content, that is written to the page for va.gov sites and fetched client side on Teamsite pages.

The Drupal content is not ready for this, but we could start thinking about solutions.

**Comment by timwright12** [comment]
Closing because the "contact us" menu doesn't exist anymore
