### ISSUE TITLE
Support sessionStorage for Banner dismissible functionality

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#29209]
# Description

The CMS sends us 3 states for banners' dismissible functionality:

1. Don't show dismissible button.
2. Show the dismissible button and store it on sessionStorage.
2. Show the dismissible button and store it on sessionStorage.

## Acceptance Criteria

- [x] Support sessionStorage for Banner dismissible functionality.

**Comment by brianalloyd** [comment]
Completed, closing in support.
