### ISSUE TITLE
[Research] My VA Action Items: Research Summary

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29226]
## Background
As part of long-term research and continued improvements to My VA post-launch, and once research synthesis and topline summary are complete, we'll need to produce a full summary.

## Tasks
- [ ] Write Research Summary

**Comment by tressaellen** [comment]
Here is the [research summary.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/action-items-discovery/research/alerts-discovery-research-summary.md)
