### ISSUE TITLE
Links should be styled as links on the "Other languages" page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#29238]
## Issue Description
_Links should be styled as links on the "Other languages" page_

<img width="1078" alt="Screen Shot 2021-06-03 at 10 14 45 AM" src="https://user-images.githubusercontent.com/14154792/120659708-9c174600-c454-11eb-9290-239c3c87a5a3.png">

Reference Ticket: #25592 

## Designer tasks
- Help determine what styling this link should be in support of the image above. 

## Front end tasks
- Work with designer on link styling 
- build and replace with appropriate component 
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling 
- [x] Impilment update in appropriate location 
- [x] Ensure component is tested 
- [x] Ensure a11y and WCAG 2.1 considerations are applied
- [x] Move pipeline to Validate for PM/PO review 
## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joshkimux** [comment]
@kelsonic sorry for the late response-- yes, but it depends. Does "Find helpful VA phone numbers" take the user to a page where they can find helpful VA phone numbers immediately? Or does it start like a form flow/wizard? If it's the former, removing the button class styling will do the trick. If it's the latter, an action link may be preferred.

**Comment by Rleahy22** [comment]
@joshkimux it takes the user directly to the page https://www.va.gov/resources/helpful-va-phone-numbers/  We will remove the button class styling then.

**Comment by brianalloyd** [comment]
@joshkimux can you validate, work should be complete on this and wanted to make sure it meets intent before closing. TIA.

**Comment by joshkimux** [comment]
@Rleahy22 This has been fixed! If there's a little more time, I'd recommend nesting the link within the intro text `div` which will make it easier to read and a less awkward transition from large to small text.

<img width="806" alt="Screen Shot 2021-09-03 at 12 51 38 PM" src="https://user-images.githubusercontent.com/14154792/132041385-9e4df2a7-7f95-4127-9735-ab1cb535a21b.png">
<img width="1056" alt="Screen Shot 2021-09-03 at 12 52 43 PM" src="https://user-images.githubusercontent.com/14154792/132041387-26342ab6-7a27-4e5f-ad35-017379129e43.png">

**Comment by brianalloyd** [comment]
Validated, closing in support.
