### ISSUE TITLE
MCP - Update DevOps repo Config

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#29247]
## Issue Description
 Update configuration information into dev-op repo staging

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
Not 100% sure what this ticket actually needs to be done to be accomplished. We updated some configs in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7786) but they are not in the [DevOps](https://github.com/department-of-veterans-affairs/devops) repo and not sure what configurations exactly need to be updated.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/10073) where this working is being done
