### ISSUE TITLE
FSR - Product Guide Final review

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#29243]
Finalize FSR Product Guide

**Comment by troyriser** [comment]
@tarlow00 @LindaLi123 Steven, received & acknowledged. I'll get on it right away, & thanks for such a speedy turnaround.

**Comment by tarlow00** [comment]
Hi @troyriser. Have you had the chance to look over the edits I sent for this product guide? I'd like to send a clean draft to VEO this week if possible. Thanks!

**Comment by troyriser** [comment]
@tarlow00 Steven, all of your corrections have been accepted or addressed. The 'clean' review version without markup or comments is filename **VSA-Form-5655-Product-Guide_090221.docx,** while the marked-up, redlined version is filename **VSA-Form-5655-Product-Guide-SRT-redline_090221.docx**. Track Changes is turned OFF in both documents.

[VSA-Form-5655-Product-Guide_090221.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7101472/VSA-Form-5655-Product-Guide_090221.docx)
[VSA-Form-5655-Product-Guide-SRT-redline_090221.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7101473/VSA-Form-5655-Product-Guide-SRT-redline_090221.docx)

**Comment by tarlow00** [comment]
Great, thanks @troyriser!

**Comment by troyriser** [comment]
@tarlow00 Your timing was impeccable. I was setting them up for upload when I saw your message come up.

**Comment by tarlow00** [comment]
Sent draft to VEO for review.

**Comment by LindaLi123** [comment]
Hello @starlow00 is the draft approved?

**Comment by tarlow00** [comment]
No changes from VEO.
[VSA-Form-5655-Product-Guide-v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7130764/VSA-Form-5655-Product-Guide-v3.docx)
