### ISSUE TITLE
CT Redesign Search: Type of institution Filter checkboxes are not grouped

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#29255]
When conducting a search in the redesigned Comparison Tool, the user has the ability to filter the search results. When tabbing through the page with a screen reader running, the screen reader will read the text associated with the checkbox (ex. "School") without the additional context that it is a filter for the institution type. This can cause a confusing experience for sight-impaired users.

### Steps to Reproduce
1. With a screen reader running, navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Execute any search which returns multiple results (ex. "university" name search)
3. In the "Filter your results" section, tab to each of the "Type of institution" checkboxes

![Screen Shot 2021-08-25 at 3 34 41 PM](https://user-images.githubusercontent.com/45575003/130854273-010b6f33-7a2f-4197-b5fe-3b1b73d9eda3.png)

### Expected Result
The screen reader reads a group name as well as the checkbox name (ex. "Type of institution: School") similar to the functionality of the "Exclude these school types:" checkboxes in the same section

### Actual result
The screen reader only reads the text associated with the checkbox

**Comment by shawkey-daniel** [comment]
This issue is being closed due to duplication by [29353](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/29353).

**Comment by zurbergram** [comment]
Reopening as not a duplicate of [29353](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/29353) each issue is for a separate set of checkboxes

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18537

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
testing complete
