### ISSUE TITLE
QA new monthly report iteration

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#29268]
## Issue Description
Review of [WIP - Monthly VA.gov Summary](https://va-gov.domo.com/page/1314425343), the new monthly KPI report requested by Chris Johnston (see [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24740)). This report will replace the DMC report currently Slacked to Chris Johnston and Liz Callaghan [each month](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/insights-analytics/monthly-reports-how-to.md), though we will keep the current version as a backup.

#### Report requirements:
- Provide all available data, but filter for most recent 24 months at the dashboard-level.
- Use bar charts only (not stacked or grouped).
- Cards sorted in specific order (written up in ticket above, reflected in dashboard).
 
#### Data notes:
- **Letters downloaded:** Only data from Aug 2020 available – this is not a data quality issue, but when tag was added. This is noted in card description that appears when user hovers over title.
- **On-site searches:** Only data from Jan 2021 available – this is not a data quality issue, but when new `view_search_results` tag for top search bar was added. @bsmartin-ep is looking into whether historical info for top bar searches could be pulled another way, but this is not a blocker. In the meantime, this is noted in card description that appears when user hovers over title.
- **System Availability:** Data is not currently in Domo, and I don't have access to view the Grafana dashboard. @bsmartin-ep is seeing if past data could be exported (manually or automated). Currently using manually updated text card, copied from [OMB report](https://va-gov.domo.com/page/1587068891).
---
## Tasks
While "System Availability" data is still pending, all other cards on [WIP - Monthly VA.gov Summary](https://va-gov.domo.com/page/1314425343) can be reviewed as of now:
- [ ] QA for data and design

## Acceptance Criteria
- [ ] Card totals and dashboard design have been vetted by Analytics team members and dashboard can be shared with Chris Johnston on Domo.

**Comment by bsmartin-ep** [comment]
## QA

### Benefits

Card | Notes | Pass / Fail
----|----|------
  |  |  |

### Web Interactions

### Authenticated Experience

### User Surveys

### Performance

**Comment by bsmartin-ep** [comment]
Should we be tracking all `edu-` successful submission events?

![Screenshot from 2021-08-27 22-26-09](https://user-images.githubusercontent.com/62304138/131203366-02c0436e-849d-4705-ad7b-af915fe135b4.png)

**Comment by bsmartin-ep** [comment]
For the  "Unique Visitors" card, should we be counting users from the _All_ view and not _WBC_?  It seems most other metrics - use the _All_ view.

![Screenshot from 2021-08-27 22-50-45](https://user-images.githubusercontent.com/62304138/131203980-a4b8b2bd-b7a7-4343-b7b3-5bf5bd0debdf.png)

**Comment by chloedotbrown** [comment]
@bsmartin-ep Yes! That unique visitors question was the same one I brought up a few stand-ups ago (though a screenshot at the time may have been more helpful). It's the only card with those view settings, even among others using that datasource on the other reports. Seems like it would make more sense to be consistent and change to "All VA/Vets Site Data" across them all?

Education seems like it would make sense to track them all – unless there's some historical reason we don't need to see these others anymore? But this looks to me like someone manually clicked what were all the ed success tags at that point in time and new ones have since appeared. If there's no reason anyone knows about for why these specific tags are selected, I can write a regex Beast mode and update across all 4 reports.

**Comment by bsmartin-ep** [comment]
@chloedotbrown -

> Seems like it would make more sense to be consistent and change to "All VA/Vets Site Data" across them all?

:heavy_plus_sign: - it would give parity between pageviews and users, so I say go for it.

> If there's no reason anyone knows about for why these specific tags are selected, I can write a regex Beast mode and update across all 4 reports.

:heavy_plus_sign: - I think by definition all `edu` forms are a 'benefit'.  I only noticed because I was comparing this to `edu-.*submission-successful` events in GA.

I'll get the rest QA'd today.

**Comment by chloedotbrown** [comment]
Confirming these are now corrected across all 4 recurring reports if they appear – unique visitors are counted across both VA/Vets production views and a new regex beast mode for education benefits submissions (excludes "not set" labels and submissions for the feedback tool).

**Comment by chloedotbrown** [comment]
FYI Grafana monthly data now added. Unfortunately, it's manual update to a [Google Sheet](https://docs.google.com/spreadsheets/d/1i_cW1hKqgw4VZu1kVTB5ZjXEiMo_kSsjeR9ZNPDSdxU/edit?usp=sharing) for now – would be great to automate the process at some point in the future, but at least for now, it's no heavier of a lift than the existing changes to the text card on the OMB monthly report.

Know QA is still going on for the last few cards, but I'm going to go ahead and give Chris a status update on the external-facing ticket and share on Domo so that he can weigh in with any edits before I'm out.

**Comment by bsmartin-ep** [comment]
@chloedotbrown - QA is complete.  LGTM!

**Comment by chloedotbrown** [comment]
Awesome - thanks so much!

**Comment by joanneesteban** [comment]
Hello! Thank y'all for working on this! Question: did y'all get the uptime hours directly from the Grafana report? We may have to refill the historical data. The current data doesn't match the numbers from previous reports, and our Grafana instance infamously doesn't accurately keep historical data past 14 days.

**Comment by chloedotbrown** [comment]
Closing, since this issue was resolved on other ticket and historical backfill corrected on spreadsheet.
