### ISSUE TITLE
COVID-19 vaccine mini-hub reorganization

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#29269]
# User story

As a Veteran, spouse, caregiver, or CHAMPVA recipient, I need quick and easy access to information about:
- If I can get a COVID-19 vaccine at VA
- How I can get my a vaccine at VA
- Which vaccine I can get at VA
- If and when I can get an additional or booster dose
- What to expect when I get a vaccine at VA (including how VA will record and share my information)
- How to access and share my vaccine record & how to share information about vaccine doses I may have gotten outside of VA with VA
- General vaccine information (efficacy, safety, etc.) (can be info provided by VA or by linking to CDC or FDA sites)

## What we need to do

We need to:
- Audit existing content to determine what we might remove and/or replace with links to CDC or FDA
- Create new content around boosters and records
- Determine evolving IA for this information that's flexible enough to allow us to consider creating a broader covid hub in the near future. We want to work to bring all of our covid content together to make it easier to find and navigate over the long term. But this work will need to start with a focus on vaccines due to the fast pace of evolving vaccine communications.

**Comment by RLHecht** [comment]
Work completed in other tickets. Closing
