### ISSUE TITLE
[SOCKS] Automate the validation of public SSH Keys

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#29277]
## The Problem
When a user requests SOCKS access, they generate their own ssh keypair. They then paste the public key into their GH issue requesting access. It's not uncommon for an extra line break, space, or hidden character to accidentally get pasted as well. This causes their SOCKS access to not work and requires additional troubleshooting.

## Work to be Done
- [x] Add automation that validates that the added public SSH key is valid

**Comment by jhouse-solvd** [comment]
https://app.zenhub.com/workspaces/platform-operations-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/27159 <-- see here

**Comment by jhouse-solvd** [comment]
This is good to go. 

Closing.
