### ISSUE TITLE
Decide Next Steps for Grey Sky Build

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2927]
## User Story or Problem Statement
How might we determine what the user's minimum needs are to use the product health tool?

## Goal
Determine the next build steps for Grey Sky and build to the point where we can send the product out the door for Education stakeholders to use and test.

## Objectives or Key Results this is meant to further
- Implement second iteration of Product Health tool

## Acceptance Criteria
- [x] (Amy/Joanne) Insights runs through a [User Journey Map](https://miro.com/app/board/o9J_kwNObPU=/) to determine how to set product targets
- [x] (Amy) Insights validates Education products, forms, and POCs (persons of contact) so we are creating the right Education products for the right people
- [x] (Amy) Education Stakeholders have baselines & template so they can set targets
- [x] (Nicola) Insights discovers a way to add targets to the Front End Solution so we can rapidly add Education targets when we receive them from teams
- [x] (Nicola) Insights adds links to the current Google Analytics data on the Front End Solution so users can dive deeper into the data if they want to investigate further
- [x] (Nicola/Amy) Insights adjusts the Front End Solution to reflect the Veteran Affairs Service Design standards so users can trust the solution
- [x] (Nicola/Amy) Insights adds placeholder charts for metrics that we don't have so that we know where we're missing data due to data warehousing or missing sources

## Definition of Done
- [x] Education stakeholders have Google Analytics baselines so they can set targets on the front end solution
- [x] The front end solution can link to the original data and reflects the VA designs
- [x] Insights has research started on how to add real targets to the front end solution

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@amycesal @deweydell Could you update your progress on the comments here? Thank you!

**Comment by deweydell** [comment]
- Implemented google oauth in a react app
- Added VA design system
- Working on adding the table w/ targets, and other blank charts due to lack of data
- Planning to deploy to gh-pages next Tuesday

<img width="1117" alt="Screen Shot 2019-11-08 at 3 08 02 PM" src="https://user-images.githubusercontent.com/11186572/68507399-d0eff680-0239-11ea-85d7-5d0c7806e7c9.png">

**Comment by amycesal** [comment]
**Education products spreadsheet with owners:** https://docs.google.com/spreadsheets/d/1kXX2I971mtShe2EVwAn1-eFK3GheUNnls76sb3bf2r4/edit#gid=680304574

**Target setting template spreadsheet:** 
https://docs.google.com/spreadsheets/d/1QyYEl0ApqsIVComoCBaf6ULrJZ94KWHayrqmUikRcBg/edit?usp=sharing
