### ISSUE TITLE
Atlantis interacting with Terraform

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2928]
We want to use Atlantis for interacting with Terraform so we can keep the workflow inside GitHub.

## Goal
- [x] Non-Ops folks can collaborate
Better changelog of the infrastructure as it’s applied (and not just the configuration)

Terraform automation project phase 1 AC:
- [x] Atlantis runs a plan on all environments when a change in /terraform/modules or in a *.tf file is proposed in a PR
- environments dsva-pagerduty, dsva-vetsgov-ssl not accounted for
- [x] Atlantis does not have the ability to apply, and responds with a comment stating that when someone attempts an apply
- [x] Terraform version is set by Atlantis config
- [x] instances get replaced on a schedule to pick up security updates

**Comment by jbritt1** [comment]
[x] Atlantis does not have the ability to apply, and responds with a comment stating that when someone attempts an apply (custom apply functionality: https://github.com/department-of-veterans-affairs/devops/blob/master/atlantis.yaml#L20)

[x] Terraform version is set by Atlantis config (specified Terraform version: https://github.com/department-of-veterans-affairs/devops/blob/master/atlantis.yaml#L7)

The above two are covered by https://github.com/department-of-veterans-affairs/devops/pull/5868 in the `atlantis.yaml`.

I also think we encompass `Atlantis runs a plan on all environments when a change in /terraform/modules or in a *.tf file is proposed in a PR` with Atlantis runs a plan on all environments when a change in /terraform/modules or in a *.tf file is proposed in a PR.
