### ISSUE TITLE
Document in GitHub `Submission Function` Within Rainbows Work

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2929]
## Story
As a frontend engineer, I want to check and see what the schema and validation errors are saying so that I can have a better understanding of where the data is going.

## Tasks
- Pull apart the function
- Trace the data

## Considerations
- This ticket may create other tickets

## Acceptance Criteria
- [x] Validation errors are either assessed or known to eventually be resolved within the submission function
- [x] Document findings [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents)

**Comment by micahchiang** [comment]
Leaving some things I've found here:
1. the warning thrown in the console regarding `Invalid prop formData supplied to StringField` is something that occurs across other forms on the site.
