### ISSUE TITLE
Document in GitHub the Business Logic in the 686 Form

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2930]
## Story
As an engineer and/or designer, I want to investigate the different functions of the 686 as they relate to the business needs of the 686 form to better capture the varying intents.

## Tasks
- Perform a gap analysis of what is currently in place for the Update Dependents work (form, current compared to rainbows work) as it relates to form functions.
  - Map of 686 functions compared to what the rainbows team is attempting to do in staging.
- Understand and document the lower level business logic that will end up in valid workflows.
- Results may inform future iterations of the Dependents work flow.

## Acceptance Criteria
- [ ] Document variances in form functions [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)

**Comment by sporeboy** [comment]
Posting WIP link to form flows: https://xd.adobe.com/view/380c70df-eb96-4008-79af-c210c9c795c1-4e3d/

**Comment by sporeboy** [comment]
Paper form workflows mapped-out by field. 21-674 form workflow added.

**Comment by sporeboy** [comment]
PDF added to Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-business-logic/686_Business_Flows_W1.pdf

Preliminary gap analysis shown in matrix on page 2. Further analysis required.

**Comment by sporeboy** [comment]
There are still holes in the current eBenefits and Rainbows 686 workflows, but these can be filled-in over the course of subsequent discovery. There were a few technical barriers to viewing all steps in these: accounts with no data, occasional login outages, etc.
