### ISSUE TITLE
[Markup and meta data] Visual labels aren't included in the accessible label. (09.05.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29345]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Trevor Pierce (Accessibility)

---

### Platform Issue
Visual labels aren't included in the accessible label.

### Issue Details
Compare checkboxes do not provide additional cues for assistive technology to understand "Compare which school?'

### Link, screenshot or steps to recreate
![Screen Shot 2021-08-26 at 5 12 49 PM](https://user-images.githubusercontent.com/934879/131042978-f20562c9-61b5-4cc4-a9d1-bd9b4f56f8e5.png)

### VA.gov Experience Standard
[Cateogy Number 09, Issue Number 05](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 2.5.3_A

---

### Platform Recommendation
Add an aria-label or SR-only text to the Compare checkbox labels so screen readers announce "Compare Florida State, checkbox not checked."

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18565
