### ISSUE TITLE
Discovery/Introduction Meetings with VSP/VSA Teams

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#2935]
## User Story or Problem Statement
As a Call Center Lead, I need to meet with VSP/VSA teams so I can effectively provide resolutions/information to external Call Centers and customers directly.

## Goal
_What outcome(s) do we want to see?
   - Effective communication between Call Center and VSA/VSP teams.
   - Timely responses to issues.
   - Discovering if there are work-arounds.
   - Schedule discussions with VFS teams on Call Center onboarding.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [x] _Discussions scheduled with appropriate VFS team POCS

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Ticket below has been closed/deleted due to similarity with this ticket.

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4132

**Comment by Kimberley2019** [comment]
On 12/20/2019, I reached out to Andrea Hewitt for an org chart in order to have a list of individuals to reach out to in order to complete this task.

She stated that she could pose this question to the PM team on VSP and get their feedback and get back to me.  The preferred method is to have the meetings first since to my knowledge, we have not connected with the appropriate teams for the introduction.

The outcome was that Andrea can work us into the onboarding process for all new VFS teams where the Call Center team could talk about the process and expectations.  She also stated that she can also help connect us with all the current teams.

Once the Holidays are over, we will have a better chance to fulfill this task.  A meeting will be scheduled by @clantosswett and I in early January.

**Comment by joanneesteban** [comment]
@Kimberley2019 @clantosswett As we set up the process, one thing we can do is add the Call Center process to the [Analytics & Insights onboarding](https://docs.google.com/presentation/d/1TKYK88pHqNAJ0HrGtXIjnDYPQT-ccBQcOTy64kd0cd4/edit#slide=id.g5f29ec5fc2_4_71) that we do for each onboarding VFS team so we can reduce the amount of meetings/bloat for VFS teams. The onboarding sessions are scheduled for 30 minutes and we have generally used ~20 with time at the end for questions, so we should be able to add Call Centers with the Insights process.

(CC: @andreahewitt-odd )

**Comment by Kimberley2019** [comment]
Slack messages were sent to Justin Pickett (authenticated experience), Kara Kemahli (public websites), and Matt Self (education) to verify that they are still the accurate POCs for these teams.  The product org chart may be outdated since the product team point for education was originally listed as Dan Ziober, but his account has been deactivated.
Once we receive confirmation we will schedule meetings with each team for the contact center introduction.

**Comment by Kimberley2019** [comment]
Meeting with Public Websites is scheduled for 1/16/2020 at 1:00PM EST.

**Comment by Kimberley2019** [comment]
Meeting with Education is scheduled for 1/13/2020 at 1:00PM EST.

**Comment by Kimberley2019** [comment]
Both meetings were held on 1/16/2020.  

Public Websites and Education had no issues that needed to be reviewed, however both are extremely interested in the issues that may come about in the future.

Matt Self with Education inquired about the priority setting of our issues.  He asked how we would be able to set a priority for him/his team if we are unaware of their current workload.  We explained that the priorities that are set are those of the Call Center and while a resolution would be great within the 48 business hour time frame; that will not always occur.  

We informed him that communication for resolution/research is the primary goal understanding that the teams we work with have their own prioritization of workloads.  

As issues come about for each team, adjustments will be made accordingly to ensure that work is reported, researched, and resolved in a timely manner.

**Comment by Kimberley2019** [comment]
Meeting with Luke (new PM) from Benefits and Memorials is scheduled for 1/22/2020 at 1:00.

**Comment by joanneesteban** [comment]
### Grooming Follow Up

@Kimberley2019 confirming that you and @clantosswett met with everyone?

**Comment by Kimberley2019** [comment]
@clantosswett 
Can you provide a brief recap of the meeting with Luke?

@joanneesteban I believe that there are other teams that we need to meet with.  Once Chante and I meet, the next round will be notated.  Once the recap is entered, we can close this ticket and open additional ticket(s) when second round of meetings are ready to go.

**Comment by joanneesteban** [comment]
@Kimberley2019 

Anything still need to be done with this?

**Comment by Kimberley2019** [comment]
@joanneesteban the only portion that is outstanding is the recap from the meeting that was held with Luke.  However, it has been so long ago, the ticket can simply be closed now.
