### ISSUE TITLE
Profile Service Authentication

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#29381]
Authenticate profile service via VAMF STS Token / Jwt Service.  [https://app.zenhub.com/files/133843125/7f433cdb-6dc2-4e3d-9b20-f0c1daadf9db/download](https://app.zenhub.com/files/133843125/7f433cdb-6dc2-4e3d-9b20-f0c1daadf9db/download)[https://app.zenhub.com/files/133843125/ba704173-64fe-4c76-8492-bbc4b6e4c63e/download](https://app.zenhub.com/files/133843125/ba704173-64fe-4c76-8492-bbc4b6e4c63e/download)[https://app.zenhub.com/files/133843125/99a3cda2-3756-4429-9756-d53002887357/download](https://app.zenhub.com/files/133843125/99a3cda2-3756-4429-9756-d53002887357/download)

From: Michael Ramirez <michael@apothesource.com> 
Sent: Thursday, August 26, 2021 8:30 AM
To: Elliott, Shane M <shane.elliott@va.gov>
Cc: Thompson, Robert J. <Robert.Thompson7@va.gov>; Jenna Gaze <jenna@apothesource.com>
Subject: [EXTERNAL] VA Mobile - SSOi STS Design and Example JWT

Hi Shane, 

Attached are three documents: 

•	20210826-MobileJWTClaims.pdf - Summary of the base claims available in our Mobile JWTs- Should address questions regarding specific JWT claims
•	20210826-SSOI-STS-SRVDD.pdf - Design document for our SSOi STS service that exchanges an IAM SSOi WS-Trust Token with a VA Mobile JWT
•	20210826-SSOi-STS-OpenAPI.json - OpenAPI specification for our SSOi STS

I don't expect that you'll need the SSOi design/API docs immediately since you'd only be consuming the issued JWTs but including them here for background and awareness in case they're helpful in the future.

Most of our services use the Nimbus library for JWT validation (https://connect2id.com/products/nimbus-jose-jwt) but any JWT JOSE-compliant library should work. Our only expectation for JWT-protected consumers is that they validate the JWT constraints + signature. I didn't include any specifics regarding JWT signatures since it's spec compliant. The only additional insight that might be helpful here is that we sign the tokens using RS512 (RSA + SHA-512)- we provide the RSA public key to JWT consumers though a separate endpoint which I can provide separately assuming you move forward with adoption. 

Please let me know if you have any questions!

-Michael

**Comment by aschulhof** [comment]
Closing as duplicate - captured in https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/35
