### ISSUE TITLE
CT Redesign Comparison Tray: tabbing to the bottom of the page unhides the tray

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#29380]
After conducting a search in the redesigned Comparison Tool, there is a tray at the bottom of the screen to which schools can be added so that they can be compared. By default, this tray is collapsed. Using the Tab key to navigate to the bottom of the page causes the tray to become unhidden despite still being "collapsed".

### Steps to Reproduce
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Execute a name search using a search term that will return multiple results (ex. "College")
3. Press the tab key until the browser scrolls to the bottom of the page and the blue footer is visible

### Expected Result
Compare tray remains collapsed until it is expanded by the user.

### Actual result
The compare tray is partially exposed

### Screen Captures
![Screen Shot 2021-08-26 at 11 50 02 AM](https://user-images.githubusercontent.com/45575003/130994804-0fe60d9d-83f7-483a-a36c-a7bee840a46f.png)

https://user-images.githubusercontent.com/45575003/130994829-9b1d0279-264f-4fdf-b414-925acdb95936.mov

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18628
