### ISSUE TITLE
Access for Clarence Maeng

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#29392]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Anthony Arashiro
- Please provide your name.
   > Clarence Maeng
- Please Provide your email.
   > clarence.maeng@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS

- Requesting SSH key authorization?
   > Yes
   - What is your **public** SSH key?

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoJEcaWcHVdQHzXVted8OcjuqjFBR/FTvfefdAL2St5WQoVr7MRjJUT48Mfs+rZuS2pxcMxcfmFA6BsbkdBToQG/q2jGfohmD5ZW25yjKjNPDuXcjgx5zvefUCZCi5JQUlDePziOJTebHOLyrsPbTnXddwCgnY5k0JKq5LBk8VBXVIfm4ShHeioDi1lP+/W9JGRjDK0iNOlGwtw9hnYJf9DT3GQbqKFIXKNAARIMeJWfr/3LfCVj7JNMqF0WThGDw5WRbNuQvmZ3DoRYtsGFAojrcGnD6I2hrl4kX3S5xcc0/dZBoLorvhFE9kYG/ANs3FyFSpGNjnGlD/VOKHnPHH+HDlUcI+d10ATHJl5Af/ddcwaonPilg3XzYOiPFb6pM0wutQvOxdMc4iLz6fnQrZOLhNWsLxu9owxF1JkJIiHL7DjczfRLn3vU3GvpbMpbDMPfqMFxhlHDmqY2g+Zql/cqr1tRiRVCD5k1iTkq0NG6mCGtynT8qG3btogsIMcXE= Clarence.Maeng@Agile6-A53

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? 

- Note: I had SOCKS set up previously on another machine through [#7143](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7143) but replaced that computer so redoing.

**Comment by omgitsbillryan** [comment]
J/w - why the update? Have you lost access to the private key?

**Comment by cmaeng** [comment]
@omgitsbillryan basically yes, i recently fried my machine and replaced it with a new one. i didn't have the private key stored anywhere so lost it.

**Comment by jbritt1** [comment]
@cmaeng, will you confirm the update has you up and running again as time allows so we may close this ticket please?

**Comment by cmaeng** [comment]
@jbritt1 not able to connect yet. i'm getting a 400. i'll keep trying throughout the day:

![image](https://user-images.githubusercontent.com/60702623/132541361-52dce1ad-081d-4fd1-a10d-7097064dd9ca.png)

**Comment by jbritt1** [comment]
> @jbritt1 not able to connect yet. i'm getting a 400. i'll keep trying throughout the day:
> 
> ![image](https://user-images.githubusercontent.com/60702623/132541361-52dce1ad-081d-4fd1-a10d-7097064dd9ca.png)

I assume this was due to not having needed permissions on the devops repository. I have added the vfs-cms-team as a `write` role now so maybe it will work the next time you try it.

**Comment by cmaeng** [comment]
@jbritt1 still no luck. anything else i can try? thanks.

**Comment by jbritt1** [comment]
> @jbritt1 still no luck. anything else i can try? thanks.

Are you authenticated with GitHub?

**Comment by cmaeng** [comment]
yup, i can reach out on #vfs-platform-support to see if anyone can assist there.

**Comment by omgitsbillryan** [comment]
Your new socks ssh key has been deployed and there's been 14 days of inactivity - I'm going to close this ticket.

If you still require further assistance, I think the most appropriate place for that is a support request in #vfs-platform-support slack channel.

**Comment by cmaeng** [comment]
@omgitsbillryan my apologies, but @ElijahLynn is making me do this. the key got regenerated and we're looking to have the following deployed.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbqBPVcHK4ifuAB+gyT1nblqVpK2qeGICcXynjr5TP2bqPrxq8th9EIzQ9jXkaevaEbj4XnwZ1d9nYf573O+K6fSmWYHxt8pi0+7hEFO2dIGmj2TxBg4kJYk6hsQNmcsqLjODcWmhB038yt9fIxmPzZfryZHQlt4yOQdr1EooI8iwd7isznJLgjElmi7SuzIAuPeAdZJ5fT6roKE4G4A+3rYHXKGbUV6+yHcQFLzVRm0r+Y9PeXs86WhiFUhyE+KZSVmmodCdDzMunPDLjOEeoZNxssf8DJnR9BC6jurLH3j5NBHZ+3AZKWYloGoRfqTJKZxsrPVRAt2aI9cuGi+1OSmUbXq/Gai9PseSLiFyCi5AW2n3NmkpIocLp59hTDp8iMylkvJW70b8Qny9HiOXQpQWjjugs7un1NLnMUJJQcqg4+X837r77HIuRULM6ZmVxN9lOQ/+iPamIBG3yqSkZtSi8J8Xg5WTE1MtwB+qIZXEXjp/uRr89fkvl9Z2RxMc= clarence.maeng@agile6.com
```

**Comment by omgitsbillryan** [comment]
Closing again.
