### ISSUE TITLE
Consider accessibility tests for Staging (vagovstaging) builds

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#294]
By enabling accessibility tests for Staging builds, we may be able to catch CMS errors before causing Prod builds to break. We should see if enabling this affects our build times.

**Comment by timwright12** [comment]
Closing this out because we have some form of a11y testing in the pipeline already and official scan have been moved to a scheduled job as they take over and hour to complete.
