### ISSUE TITLE
[Sentry/EKS] Replace docker hub images with ECR

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29400]
## Description
We need to add the Sentry docker images to ECR and deploy from those images since we are hitting the docker hub rate limit which is preventing pods from being created.

![image](https://user-images.githubusercontent.com/76792875/131030537-a93d10fc-3c81-4046-957e-73d40e331e6c.png)

---
## Tasks
- [x] replace image references in Sentry values files

## Acceptance Criteria 
- [x] Sentry Kubernetes deploys referenced images from ECR repositories

**Comment by jhouse-solvd** [comment]
Confirmed that Sentry is using the DSVA ECR. 

Closing.
