### ISSUE TITLE
Use patientInstruction field to get instruction title for video appointments

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#29408]
The vaos service is now returning `patientInstruction` in the appointment data. This will have the instruction title we use to determine what instructions to show on video appointments, which we currently do by checking `instructionTitle` in the video appointment data from MAS.

Note: The patientInstruction field starts with the instruction title and also contains the full VCM instructions, which we don't use. So you may need to do some work to remove that extra instruction text in the transformer.

AC
- Incorporate `patientInstruction` into comment field for video appointments
- Verify that instruction titles passed in through `patientInstruction` result in correct instructions show on details page

**Comment by laurenernest** [comment]
@jenniemc I'm not seeing the instructions and the text above the CTA is different between 2 of the same types of video appointments. Can you verify if this is a staging/test data issue or something else?

![Screen Shot 2021-09-10 at 11.56.30 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/799ea464-521c-4dd0-a3f4-c347828a439b)

**Comment by jenniemc** [comment]
The patientInstruction field must have either `Medication Review` or `Video Visit Preparation` in order to display the link which expands to show video appointment instruction. Currently the 2 at home video appointment on staging does NOT have anything in the patientInstruction field.
