### ISSUE TITLE
Vanity URL Request: Assess the use of a shortened URL for VRRAP program on materials and videos

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29414]
## Issue Description
Stakeholder Ricardo Da Silva asked if we can create a shortened url for the VRRAP page for materials such as videos. 

The current url:https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
www.va.gov/vrrap | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@bethpottsVADEPO @RLHecht We can use `www.va.gov/vrrap` as the vanity URL for this. 

Do you need to run this by anyone before we implement?  If not, I can send this along for implementation.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Thanks! Please move forward with implementing.

**Comment by mnorthuis** [comment]
@brianalloyd this vanity url request is approved and can be implemented at any time.  Thank you!

**Comment by brianalloyd** [comment]
Thanks @mnorthuis we'll scrub into this request and begin implementation this sprint.  We'll follow up if any questions or clarity exist.  Thanks.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9915 Will try and have this go out today

**Comment by kelsonic** [comment]
https://www.va.gov/vrrap and https://www.va.gov/vrrap/ redirects out on production! 🙂

**Comment by brianalloyd** [comment]
Thanks @kelsonic
