### ISSUE TITLE
Add timestamp footer to rated disabilities

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#2941]
## Story
As a user, I want to know when the page I am currently on was last updated, so I am certain the information on it is being actively kept up to date. 

## Considerations
- Similar to the breadcrumbs component, there may be an existing component for adding the timestamp footer to a page, as it's used elsewhere on VA.gov.
- Mockup here: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/4255c799-245e-4df0-90bb-7cec66dfc218/RD-Screen-Tool-3?fullscreen

## Acceptance Criteria
- [ ] Add timestamp footer to the bottom of rated disabilities
- [ ] Validate with an e2e test

**Comment by jason-gcio** [comment]
Given that this is not a Drupal page, this might get wiped.  We are not in a position to invent this at this time.  Spend a little time to investigate, then close as needed.
