### ISSUE TITLE
Access for Justin Trieu

### ISSUE THREAD

**Issue by justin-trieu** [department-of-veterans-affairs/va.gov-team#29419]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Scott Mason
- Please provide your name.
   > Justin Trieu
- Please Provide your email.
   > justin.trieu@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Orchid, Developer, ThoughtWorks

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8QwBD5ujVGqIGCAeHL7g3T0zc2mcipHObAEPQhx3D7Xyeeer2kjhvrdGxS73cjtx3iUPJHm0C9ZpyL2DqPtXfzmv5PiBD3ipNmGhL3f/15988oo6YGEaTtAEsa5X2rl3WKeawrYGzTSyGXd5H//iGm1PnafPIFrbumzBZrk2Fnv4+mTRsEnkl7O63aHg+N0C36Ipn0JmAEX968pxNHapa2PNWDdrHpvynQYroh2odPmb9Wa//Yl/RzxMRoMF66RsBh7iJBDyLsEsMN57s68HwUlKDDyEuZyaIpVugDREYpid+rH8WtlV4Lpc1eSW6nBAucbTi1eDRbivFIwhjBTzVUXr+K/ZGL+AGh2KA6PX9xLwpTeIDdlzm7VAhW6FgeqF9/JLyc4pwc7sJHCLH/cTwQT8OGN0lCy9AX8bNtoYitLAreA9AVzerZMEfhM1YVTRYmN3SzZIIl6LHICXXqM1Fg/FYCiLWVOnaGk79Ril+gJdC1PNjnYZfjbCBcqwRB4c= justintrieu@justins-mbp.lan

```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by justin-trieu** [comment]
As a developer on the Virtual Agent Chatbot team, I would like AWS Console Access so that I can manage secrets for our applications that live in the AWS store.

**Comment by jbritt1** [comment]
New approval group: @department-of-veterans-affairs/operations-aws-approvers

**Comment by td-usds** [comment]
eQIP transmittal date confirmed, approved

**Comment by jbritt1** [comment]
Temporary credentials provided to user at this time.
