### ISSUE TITLE
Replace Select components with VaSelect web components

### ISSUE THREAD

**Issue by LeKeve** [department-of-veterans-affairs/va.gov-team#29418]
The Select component is deprecated and should be replaced by their web component counterpart VaSelect.

The `web-components` package now comes with react bindings that allow us to add event handlers to VA web components. The event handlers should be named in the following manner `onVAEventName`. The remaining props should work just like the `va-select` web component documented [here](https://design.va.gov/storybook/?path=/docs/components-va-select--default).

```
import { VaSelect } from 'web-components/react-bindings';
<VaSelect onVaSelect={onSelectEventHandler} />
```

AC:
[ ] Replace Select React components with VaSelect web components
[ ] selects work as intended

**Comment by pdavies88** [comment]
The `<va-select>` web component is available to use and its implementation can be found here: https://design.va.gov/storybook/?path=/docs/components-va-select--default
If additional styling or updates are needed please open another ticket with the requested changes to be made

**Comment by laurenernest** [comment]
Reopening for VAOS dev team to implement

**Comment by laurenernest** [comment]
Seeing the new web component in some spots, but not others. The font of the selected value looks different, but appears to be part of the design system. @outerpress can you take a look and determine if we should use as is or override? we can handle in another ticket if changes need to be made.

✅  facility selection, CC provider selection
![Screen Shot 2021-12-27 at 9.17.17 AM (2).jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f1d69e02-be16-4318-b8bf-3e0bc0b128bb)

⚠️ homepage status
![Screen Shot 2021-12-27 at 9.12.52 AM (2).jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/10cf0bfd-6ae8-43da-918e-63559d863b33)

⚠️ CC preferred language
![Screen Shot 2021-12-27 at 9.26.27 AM (2).jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/e80a890c-b8bc-4d43-a60d-e90b5d2231ab)

**Comment by ptouchton** [comment]
This ticket replaced the deprecated select component with the new VaSelect from component-library. It was discovered that VAOS has a select component based off of the React component. It was decided to complete this ticket addressing the deprecated component and create a new ticket to address the VAOS component. This new ticket can be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34515

**Comment by laurenernest** [comment]
Thanks! closing this ticket
