### ISSUE TITLE
GHA Lambda Error: `The instance i-0598XXXX is not in InService or EnteringStandby or Standby.`

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#29427]
## The Problem
The gha-runner lambda script encountered some errors causing a PD alert to go off:
https://dsva.slack.com/archives/C30LCU8S3/p1630079187009500

[Grafana](http://grafana.vfs.va.gov/d/tAxjiwG7z/github-runners?orgId=1&from=now-6h&to=now&var-app=content-build)
![image](https://user-images.githubusercontent.com/3077884/131168207-9ac3c3ef-3e13-474a-b668-3d0b4cd7ff8c.png)

## Extra Context
Looking at the CW logs:
```
  "errorMessage": "The instance i-0598XXXX is not in InService or EnteringStandby or Standby.",
  "errorType": "Function<Aws::AutoScaling::Errors::ValidationError>",
  "stackTrace": [
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.117.0/lib/seahorse/client/request.rb:72:in `send_request'",
    "/var/runtime/gems/aws-sdk-autoscaling-1.64.0/lib/aws-sdk-autoscaling/client.rb:5362:in `set_instance_protection'",
    "/var/task/lambda_function.rb:125:in `block in lambda_handler'",
    "/var/task/lambda_function.rb:29:in `each'",
    "/var/task/lambda_function.rb:29:in `lambda_handler'"
  ]
}

```

## Work to be Done
- [x] Fix bug so failure does not occur in the future

**Comment by omgitsbillryan** [comment]
PR tested & merged. This is done.

**Comment by jhouse-solvd** [comment]
Closing per Bill's comment above.

**Comment by rmtolmach** [comment]
We hit this again. `GithubRunnersLambdaFailing` kept alerting and resolving for about half an hour. https://dsva.slack.com/archives/C30LCU8S3/p1660246886794949

Realized that Bill's changes didn't make it into the lambda_function [in aws](https://console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions/gha-runner-cleanup?tab=code). I think changes have to be manually added to the lambda functions, i.e. we don't have any way of keeping https://github.com/department-of-veterans-affairs/devops/blob/master/scripts/github-runner-cleaup/lambda_function.rb parody with the lambda function in AWS. 

I updated the file in AWS.
