### ISSUE TITLE
Access for Aditya Sharma 

### ISSUE THREAD

**Issue by TW-Addy** [department-of-veterans-affairs/va.gov-team#29422]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Scott Mason
- Please provide your name.
   > Aditya Sharma
- Please Provide your email.
   > Aditya.sharma@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Orchid, QA, Thoughtworks

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB0lM2ITiyURJLHkKysrRYaWvxELYghwLrZ4f2h1lsRD4UJaIv3Ninc4/GVx2+Vr826+5vI491WK5I56Dd1WFmmMeBx+2Nn1Qpaow5NJLj/CCy/FfQj30O6BWRQIHPvgNKOVgjoyJBA190mIBfzRbYKqa84HaLyfnxsaR2SSEu5nUMUYtU1kcw9JBissc2mt10X7h8hIvbdh/9RYYZz0JJB8/fsU6guwEH5jb1DORjR87kv+zbNX0omQdI05/9xklwgZ1bQzloXkITRgcg6L1AC1My7fIM5HSv61jbggzHk/F+wHCCH6ATQkCgJXUKg1AzN/XTJ75Pv4PLD22cPqOweszM8HCWTfR/I+GSNvN1NMWMYAVb7sWiD7fxsDW9ThmLWdXZZt66+eO9er7ek2PyoZQUb8p9zMJQmo6srwjWfTA1KS6SJRD8mXQDUEKU+j5AVks7QuZzAugdomxPoQ9FrtaoywUVrloK2Hby0UkShWpFGGRfAk3u7AGzTLTGi2U= adityasharma@Adityas-MacBook-Pro.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
### For AWS ACCESS
User: <user's first and last name>
COR: Cecilia Lee
GTL: Scott Mason
Approval needed: @mchelen-gov
