### ISSUE TITLE
QA Feedback - Staging Review - Add spacing to "Additional information regarding your benefits" section labels

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29429]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Darius Dzien (QA)

---

## What happened?
On the `School Details` page, there are spaces missing before some parentheses. Spaces must be added to be consistent with the rest of the page.

<img width="981" alt="Screen Shot 2021-08-25 at 2 28 52 PM" src="https://user-images.githubusercontent.com/3535749/130856603-edb416c3-ef13-4e4e-a51d-929a91ef2412.png">

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/31005740

## Desired behavior
There is spacing between the label text and the (Learn more)

## Acceptance Criteria
In the "Additional information regarding your benefits" section:
1. There is a space between the label "Protection against late VA payments" and the "(Learn more):".
2. There is a space between the label "Yellow Ribbon Program" and the "(Learn more):".
3. There is a space between the label "Veteran Rapid Retraining Assistance Program (VRRAP)" and the "(Learn more):"

**Comment by zurbergram** [comment]
Change is at the bottom of the "Calculate your benefits" section
https://github.com/department-of-veterans-affairs/vets-website/pull/18454

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2021-09-01 at 11.03.21 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6c14dfd9-c860-4c93-9992-0626e5d0e7be)

**Comment by delli-gatti-michael** [comment]
Changes are on staging

**Comment by mattpointzxer0** [comment]
We now have properly spaced parentheticals; nice! ✊
