### ISSUE TITLE
Upgrade `vets-api` to Ruby version 2.6

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#2943]
Upgrade `vets-api` to Ruby version 2.6.5

## Acceptance criteria
- [x] Make changes to `vets-api` repo to use Ruby 2.6.5
- [ ] co-ordinate with the devops team to formulate a strategy for upgrading Ruby in our deployed environments.

**Comment by alexpappasoddball** [comment]
Are there any breaking changes in 2.6?  Bill and Keifer have a *feeling* but aren't certain.

**Comment by alexpappasoddball** [comment]
@jholton any updates on this one yet?  I believe it has rolled out to production.  If so we are good to close this.

**Comment by jholton** [comment]
You are correct.
PR was merged 2/18/2020.
The upgrade rolled out to production on 2/19/2020 at 3 PM EST.
