### ISSUE TITLE
QA Feedback - Staging Review - The spacing of profile page card titles does not have room for certain name lengths

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29434]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Darius Dzien (QA)

---

## What happened?
- On the `School Details` page, CSS might need to be modified so that long school names do not come as close to the edge of the `School` box.
<img width="762" alt="Screen Shot 2021-08-25 at 2 40 39 PM" src="https://user-images.githubusercontent.com/3535749/130856931-69696e07-f4f6-4a23-944c-771079070a96.png">

<img width="762" alt="Screen Shot 2021-08-27 at 3 37 47 PM" src="https://user-images.githubusercontent.com/48260534/131180406-fc25a161-eea8-46da-97f3-ceeb599231d1.png">

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/25026309

## Desired behavior
The display of the institution name in the card has more spacing near the edge of the card.

## Acceptance Criteria
1. The card title has 16px of right margin.

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18591
