### ISSUE TITLE
QA Feedback - Staging Review - Hide auto-complete menu when search field is empty

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29433]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Darius Dzien (QA)

---

## What happened?
- The search autocomplete options do not disappear after clearing the search box. Determine if this is acceptable behavior.

https://user-images.githubusercontent.com/3535749/130856822-bc6500f0-6fac-4c89-a6fb-c11767f7448a.mov

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox
1. Type a search term in
2. Backspace the search term out; the auto-complete dropdown remains displayed

## Desired behavior
The auto-complete dropdown disappears when the search field is empty

## Acceptance Criteria
1. The auto-complete dropdown disappears when the search field is empty

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18593
