### ISSUE TITLE
QA Feedback - Staging Review - Make compare page header transition to "stickiness" smoothly so it doesn't "jump"

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29431]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Darius Dzien (QA)

---

## What happened?
- Scrolling of the school comparison table is not smooth. This should be fixed for a better user experience.

https://user-images.githubusercontent.com/3535749/131012565-a0de7377-cb86-4227-b503-7bdf8e1f9f3e.mov

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/compare/?facilities=15060213%2C31005740%2C10610240

1. Navigate to the url
2. Begin scrolling down the page and notice that when the header becomes "sticky" that it "jumps" covering the data at the top of the table.

## Desired behavior
1. When the user is scrolling, it seamlessly transitions the sticky header without causing a jump covering data.

## Acceptance Criteria
1. When the user is scrolling, it seamlessly transitions the sticky header without causing a jump covering data.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18457

**Comment by mattpointzxer0** [comment]
Still seeing the noted behaviour; when scrolling down the page, just after the table header becomes sticky, the table "jumps" downward, obscuring

https://user-images.githubusercontent.com/35348636/132370419-e2e68c21-4b6b-4f17-83a5-cb5975fb1f60.mov

 the top 2-3 rows from view.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18573

**Comment by zurbergram** [comment]
This might resolve https://github.com/department-of-veterans-affairs/va.gov-team/issues/29376 as well

**Comment by mattpointzxer0** [comment]
Seems to be resolved...Awesome!
