### ISSUE TITLE
Access for Chloe Brown

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#29430]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Janet Doe
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Nancy Smith, Oddball
- Please provide your name.
   > Chloe Brown
- Please Provide your email.
   > chloe.brown@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Platform Analytics & Insights team, Data Analyst, Ad Hoc LLC

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4qkRsyww5BjoCGZE9r9rzr3WewM8eNWK74zS5CVoQLuf12P4iNvlmXJJjmyk2ZtXAw/odWMcALIp47iHBb2izNCyZpVjr6ikFhIbAmqDahqbGrgZkykHf6fuJkRA2dpBCq1yGEa310Jv0bXfRfq/4hYeRlvbRBmhfr4WCR8CWBrc7yEcekk08JtWGTAqmSnjsMBdqsOang/XrJiNHheRmuJp8jTpXahG5BNyMPrAlUoybguer5zWxUw0SjzDL1pHECnpeUg0Mtm5qPC6Cp4ABWRsVMUv92lcgutXZ07tH2/EczOENBw66qvb0lcC2/H8tyfQ7msZS7koUevfwXtAdIt0Ic3YxIcv7Y9S8RdgUuXT3USOniaaJGhNDVS0xm/+Hn+vYfwhrU/lBpSQBgswAZhlufdSIscpFMjPvVC3ATC9J5Q+saL8PEKt13JoBys2rdRp50sh9aDdMxveQHTpFYIt7Bm62aNNdCems6kGuqi8WULeErWSK4Vr23E08PDs= chloebrown@Chloe-Brown-Macbook.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
