### ISSUE TITLE
[Design] Update Pre-Checkin Wireframes to Reflect Day-of Demographic Info 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#29454]
As a Veteran, I want to be able and review demographic information so that I can see if anything needs to be updated to inform staff. 

### Background

Current Phase 3 (pre-checkin/reg) wireframes need to be updated to reflect decision to  show read-only demographic info screen in the day-of checkin experience. 

### Acceptance Criteria  
- [X] Create Pre-checkin [Wireframes ](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/eKDzGwz

**Comment by kristenmcconnell** [comment]
These wireframes were reviewed with staff at Martinsburg. A Veteran usability test should be planned.
