### ISSUE TITLE
[Design] Update Pre-Checkin Research Plan 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#29453]
As a Veteran, I want to be able and review demographic information so that I can see if anything needs to be updated to inform staff. 

### Background

Current Phase 3 (pre-checkin/reg) research plan needs to be updated to reflect decision to  show read-only demographic info screen in the day-of checkin experience. 

### Acceptance Criteria  
- [ ] Update Pre-checkin [Research Plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-plan.md)

**Comment by kristenmcconnell** [comment]
The read-only demographic info screen in the day-of checkin experience will be tested after implementation during a visit to the Martinsburg's pilot site. This ticket is no longer needed.
