### ISSUE TITLE
Subdomains' header does not look correct

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#29458]
# Description

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1630339496089000

A recent change to the header that is used on subdomains resulted in the following UI look:

![image (3).png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/16862487-dfff-43cf-a510-dfa603af4308)

Instead, the header should look like:

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/2dab9cdb-93ad-418d-8e21-8f7ba292b904)

## Acceptance Criteria

- [x] Fix the header on subdomains like https://benefits.va.gov/benefits/ and https://www.va.gov/homeless

**Comment by brianalloyd** [comment]
Closing.
