### ISSUE TITLE
Business intake form for LGY #2

### ISSUE THREAD

**Issue by john-thomashill** [department-of-veterans-affairs/va.gov-team#29464]
## Requestor Name

John-Thomas Hill

## Business Line

LGY

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 

When Veterans have requested their Certificate of Eligibility (COE) and are required to fill out an online application, we would like to have notifications sent if they forget to begin the process or abandon the process. This is necessary to avoid having the Veteran contact the Regional Loan Center when confused about the status of their COE application if it has not been formally submitted.

## What is an overview of the notification use case? (required 3-5 sentences) 

We would like to send Veterans reminder notifications to begin and complete their online COE application when a Veteran is not automatically approved, and has not began their online application.

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 

Veterans looking for their eligibility for their VA Home Loan benefits will visit VA.gov to apply for their COE. Once on VA.gov, they will click to sign in and find out how to apply for their COE, click to apply for their COE, receive a preliminary decision that they are automatically approved or that an online application is required. If an online application is required, then the reminder notifications would be sent when the criteria in the use case is met. The desired behavior change is to remind the Veteran to start and/or complete their COE application in lieu of contacting an RLC for status.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 

No

## What kind of notification would this be? (required Email, Text, Not sure)

Email

## If you have a draft of the content you’d like to send - please upload here. Please note we collaborate with all of our users on their content to ensure it meets standards. (optional - blank) 

Dear [Veteran Name]

You recently requested an automatic Certificate of Eligibility (COE) on www.va.gov but did not complete the online application. Unfortunately, we were unable to issue your COE without additional information. If you would like to request a determination of your eligibility for the VA home loan benefit, please return to www.va.gov to complete and submit your application. 
Applications are saved in our system for 60 days.

Once submitted, VA processes most requests within 5 business days.

If you have any questions about completing the application, please reach out to a VA Loan Specialist at 1-877-827-3702 option 1, between 9am-6pm EST.

Sincerely, 

Loan Guaranty Service

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 

No

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 

VA.gov is the platform that the Veteran will use to request their COE and to complete their online COE application.

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 

When the Veteran is required to submit an online application through VA.gov (VA Form 26-1880), they have not submitted the application, and it’s been 24 hours since they requested their COE, it would trigger the one-time notification.

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)

Yes

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)

Not sure

## When does this notification need to be in production? (optional - open space)

November

**Comment by miabecker** [comment]
@John-thomashill we have received your intake and get back to you soon!

**Comment by bevnobev** [comment]
@miabecker I messaged @John-thomashill and he confirmed that the content for LGY #1 and LGY #2 are the same. I mentioned that we would create one template since the content is the same, and he is in agreement with that.

**Comment by miabecker** [comment]
Deleting duplicate issue.
