### ISSUE TITLE
[FE] Figure out Review Instances

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29468]
## Description

Figure out a way to test a branch before getting merged into master. 

## Questions to Answer

> these are the targeted questions that need to be answered in this spike

- [ ] What needs to be done with Review Instances?
- [ ] Could we use code spaces

## Acceptance Criteria

- [ ] Relevant documentation has been created
- [ ] Findings shared with the appropriate team members
- [ ] Ensure web UI is available to business partners
- [ ] Ensure that the codespace may be set up with a branch of `vets-api`

**Comment by julieadair1** [comment]
@jparker0425 - what epic should this ticket be attached to?

**Comment by sarahknoppA6** [comment]
This ticket is to be closed since validation is done in staging right now. We will reopen later if needed.
