### ISSUE TITLE
IA Feedback - Staging Review - Update display of location search results count 

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29474]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

## What happened?
When on search by location, the "Showing 46 search results for 'minnesota'" info should be displayed above the filters and results list the same as it is in the search by name experience - this info should be in a consistent and prominent place as it is the primary feedback on what is being displayed.

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location&name=charleston&location=charleston

## Desired behavior
The position of the number of results found is consistent across search types.

## Acceptance Criteria
1. On search by location, the results count the `Showing **XX search results** for '**location**'` is displayed above the "Update tuition and housing estimates" component instead of with the search results cards (like the search by name location).

#### Note
- #29365 is related and consider fixing at the same time if possible.

## Supporting Artifacts
1. [Desktop prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296065251_Searchbylocation_Desktop_results_-1-)
2. [Mobile prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#/296060491_CT_Searchbyname_mobile_1)

**Comment by amyknox** [comment]
@dneel-bah 

[Desktop prototype here](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296065251_Searchbylocation_Desktop_results_-1-)

This update also addresses #29365 (The text "Showing 8 search results for 'UNIVERSITY...' was updated to be consistent with current VA search styling. This styling update is needed on both Name and Location search results)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18506

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
This is on staging.

**Comment by mattpointzxer0** [comment]
Lookin good! 🙇
