### ISSUE TITLE
IA Feedback - Staging Review - Update accordion component buttons to accurately describe behavior

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29471]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
The "Update results" buttons only update the results based on selections within their corresponding filter set - if these are meant to update independently, the labels of those buttons should be distinct in what they are updating. For example, the top button is "Update tuition and housing estimates" (it doesn't seem to impact search results at all) versus the bottom button would be "Update results"

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Desired behavior
The buttons in the "Update tuition and housing estimates" and the "Filter your results" components accurately describe what the button is doing.

## Acceptance Criteria
1. In all locations where it appears, the button label in the "Update tuition and housing benefits" accordion should say "Update estimates"

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18502

**Comment by mattpointzxer0** [comment]
✊ ✊ ✊
