### ISSUE TITLE
IA Feedback - Staging Review - Update estimates button on location search must make user aware of changes

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29476]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
On the search by location, the "Update tuition and housing estimates" impacts data in the search results, not the map - users have no indication that changes are happening in the data. Users must have an indicator of how changes are impacting their search results.

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location&name=charleston&location=charleston

## Desired behavior
The user is made aware of the impact to the search results when the "Update tuition and housing estimates" button is clicked.

## Acceptance Criteria
1. The following note is displayed above the "Update estimates" button of the "Update tuition and housing estimates" component:

    > **Note:** Changing these settings modifies the tuition and housing benefits shown on the search cards.

2. The "Update estimates" button has an aria-describedby with the following content: 

    > **Note:** Changing these settings modifies the tuition and housing benefits shown on the search cards.

## Supporting Artifacts:
1. [Desktop prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060313_Searchbyname_Desktop_2)
2. [Mobile prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#/296060494_Mobile_Update_Tuition_And_Housing_Estimates_)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18508

**Comment by mattpointzxer0** [comment]
gtg, thx!
