### ISSUE TITLE
IA Feedback - Staging Review - Update profile page breadcrumb to be more accurate for different profile types

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29478]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
Breadcrumb for detail page should use a term other than "School detail" since not all facilities shown are schools - i.e. "Facility detail". Consider using the facility name in the breadcrumb for the detail page in place of "School detail" or "Facility detail" for the best experience.

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/21000140

## Desired behavior
The breadcrumbs on the profile page should more accurately describe page for all profile page types.

## Acceptance Criteria
1. The static breadcrumb of all profile pages (School, OJT, VETTEC) is "Institution details".

#### Example
The profile page: https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/31005740 breadcrumb would be:
[Home](https://staging.va.gov/) > [Education and training](https://staging.va.gov/education/) > [GI Bill® Comparison Tool](https://staging.va.gov/gi-bill-comparison-tool-sandbox/) > **Institution details**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18507

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
On staging

**Comment by mattpointzxer0** [comment]
gtg!
