### ISSUE TITLE
IA Feedback - Staging Review - Update Comparison Tool header content to more accurately reflect the tool

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29470]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
The H1 and intro content do not accurately reflect the actual functionality of the tool - which is comparing benefits by school. The H1 and intro content must include accurate keywords and descriptors for users and SEO.

<img width="1032" alt="Screen Shot 2021-08-30 at 3 06 42 PM" src="https://user-images.githubusercontent.com/48260534/131391612-bfa3bf7d-6a2f-44c8-a3b4-d223bcacffd4.png">

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Desired behavior
The H1 and intro content accurately reflect the functionality of the tool

## Acceptance Criteria
1. The header content

    > "Use the GI Bill Comparison Tool to see how VA education benefits can pay for your education."

    is replaced with

    > "Learn about and compare your GI Bill benefits at approved schools, employers, and VET TEC providers."

#### Note
- #29362 is related and consider fixing at the same time if possible.

## Supporting Artifacts:
1. [Desktop prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296062999_Searchbyname_Desktop_4)
2. [Mobile prototype](https://bahdigital.invisionapp.com/share/QDIAGYESX4T#/296060491_CT_Searchbyname_mobile_1)

**Comment by amyknox** [comment]
@mnorthuis - this ticket is based on the h1 / intro content launch-blocker which you shared for the Comparison Tool staging review.  Please let us know if these solutions work on your end.  Thanks! 

**H1: GI Bill Comparison Tool** - We would like to keep the name of the tool as the h1 for the landing page.  
* It has brand recognition - during TAPS, service members are trained on how to use the "GI Bill Comparison Tool." Veterans who are aware of the tool share it by that name with their "buddies" and the name also is reinforced throughout VA.gov
* We researched many typical searches (VA education benefits, GI Bill Comparison, Compare GI Bill benefits, etc) and found the GI Bill Comparison Tool consistently returns as the top results - showing established SEO for the tool.


**Landing page intro content** - We propose the following update to add clarity and a few more keywords into this content: 

_Learn about and compare your GI Bill benefits at approved schools, employers, and VET TEC providers._

**Comment by mnorthuis** [comment]
New intro copy looks good - it includes reference to the function of the tool (i.e. compare) and what is in the tool (i.e. the types of institutions).  Thanks @amyknox!

**Comment by amyknox** [comment]
@dneel-bah 

[Desktop prototype here](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296062999_Searchbyname_Desktop_4). 

The prototype update also addresses 29362 (H1 should be left-aligned, not centered on the page)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18504

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
on staging

**Comment by mattpointzxer0** [comment]
Ser gut! Danke shon 🙇
