### ISSUE TITLE
IA Feedback - Staging Review - Update URL of profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29479]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
URL for detail page - use a term other than "/school-detail" since not all facilities shown are schools (i.e. gi-bill-comparison-tool/facility-detail/).

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/21000140

## Desired behavior
URL for detail page - use a term other than "/school-detail" since not all facilities shown are schools (i.e. gi-bill-comparison-tool/facility-detail/).

## Acceptance Criteria
1. The URL of the profile page is: https://staging.va.gov/gi-bill-comparison-tool-sandbox/institution/{facility code id}

**Comment by dneel-bah** [comment]
Copying comments from originating location for reference:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28682#issuecomment-907449563
* URL for detail page - use a term other than "/school-detail" since not all facilities shown are schools (i.e. gi-bill-comparison-tool/facility-detail/).

For the URL, unfortunately, we can't use the institution name and have to use the facility number due to technical constraints.  The current syntax is .../profile/[facilitynumber]
**Given that, would the following syntax be an acceptable approach:  .../institution-detail/[facilitynumber]?** 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28682#issuecomment-907889015
Hi @amyknox, responses to the above questions

Regarding the breadcrumb and URL feedback
- for the URL, I figured there might be technical constraints for using the name, so thank you for confirming that.  In that case I'm fine with using "institution" in the URL as well, followed by the facility ID.

**Comment by zurbergram** [comment]
Tested below as all of these were affected by changing url value, this is includes using a preview version:
- direct url http://localhost:3001/gi-bill-comparison-tool-sandbox/institution/31005740, http://localhost:3001/gi-bill-comparison-tool-sandbox/institution/2V000406/HACK%20REACTOR%20SOFTWARE%20ENGINEERING
- clicking link in a Search Result Card
- clicking link in Compare Page
- inspecting Institution Details breadcrumb and observing that href link has institution in it
- When on a profile page the Compare Drawer is always displayed

https://github.com/department-of-veterans-affairs/vets-website/pull/18511

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
On staging

**Comment by mattpointzxer0** [comment]
Validated on staging. Thx!
