### ISSUE TITLE
IA Feedback - Staging Review - Consider using a different delimiter in the URL in place of a space to prevent encoding

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29483]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
Consider using a different character as a delimiter for the URL parameters on the compare page rather than a space which must be encoded.

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=name&name=charleston&excludedSchoolTypes%5B%5D=FOR%20PROFIT&excludedSchoolTypes%5B%5D=PUBLIC

## Desired behavior
Consider using a different character as a delimiter for the URL parameters on the compare page rather than a space which must be encoded.

## Acceptance Criteria
1. TBD

**Comment by zurbergram** [comment]
@mnorthuis The values like "FOR PROFIT" are being passed across to match the values in the database so that [app/models/institution.rb#L536](https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution.rb#L536) can be done

**Comment by mnorthuis** [comment]
@zurbergram I'm not referring to the characters within the actual values, instead the delimiter that is used when there are multiple values passed.  The compare page is where I see this happening: 
https://staging.va.gov/gi-bill-comparison-tool-sandbox/compare/?facilities=10242703%2C24943503

In this URL, there are 2 facilities being compared, so 2 values passed separated by a space which is encoded.   This is not a blocking issue, more of a suggested practice to ensure that values being passed are human readable.

**Comment by zurbergram** [comment]
@mnorthuis [%2C is a comma](https://ascii.cl/)

Would you rather the url look like https://staging.va.gov/gi-bill-comparison-tool-sandbox/compare/?facilities%5B%5D=10242703&facilities%5B%5D=24943503

**Comment by mnorthuis** [comment]
First, my bad, I read %2C and saw %20.  I would have suggested a comma, so that is good.  I don't totally understand why the comma is encoded, but beyond my technical knowledge, and wouldn't suggest the brackets, which just adds more encoding to the URL.  My goal would be to have a readable URL ex: https://www.bestbuy.com/site/compare?skus=6362515,6412317

**Comment by zurbergram** [comment]
By default commas are encoded when using https://www.npmjs.com/package/append-query

PR to disable encoding for compare page url
https://github.com/department-of-veterans-affairs/vets-website/pull/18600

**Comment by mnorthuis** [comment]
Thanks @zurbergram.  If that solution works, that is awesome, but if it ends up creating any technical issues, then I want to make sure this does not create churn.  Its a nice to have.  Thank you!
