### ISSUE TITLE
IA Feedback - Staging Review - Consider updating the spacing of the search component to increase visibility or search and results

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29480]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
The search entry box occupies quite a bit of vertical space, it is barely noticeable that results are on the page when you are scrolled all the way to the top of the page

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Desired behavior
The search entry box occupies quite a bit of vertical space, it is barely noticeable that results are on the page when you are scrolled all the way to the top of the page

## Acceptance Criteria
1. TBD

**Comment by JenLJ** [comment]
UX reviewed the search page design and looked into reducing a couple margins, but didn't see many opportunities.  To mitigate the above, the page automatically scrolls down to the results once a search has been run so the user sees what their query found.
