### ISSUE TITLE
IA Feedback - Staging Review - Consider improving compare page highlight differences content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29485]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

## What happened?
The "*Highlight differences" option label should be a bit more descriptive and the use of the asterisk in the label of the input is confusing. Consider a more descriptive label for the selection, then show the asterisk with text next to the content "An * indicates the information is different between the schools shown."

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/compare/?facilities=31005740%2C10610240

## Desired behavior
Consider a more descriptive label for the selection, then show the asterisk with text next to the content "An * indicates the information is different between the schools shown."

## Acceptance Criteria
1. TBD

## Issue Source:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28682#issuecomment-906746031

**Comment by amyknox** [comment]
@dneel-bah This issue duplicates a portion of #29356 

Our solution is as follows:

Using the recommendation for "*Highlight differences" checkbox subtext as an aria label on the checkbox but not including it in the visual. 

Our testing indicates that users do not have any trouble understanding the difference between institution categories when the asterisk + color are used. We're also concerned that adding the extra text will crowd the control and causing users to overlook it.

**Comment by dneel-bah** [comment]
Closing this issue as a duplicate of #29356.

Fix is outlined in comment https://github.com/department-of-veterans-affairs/va.gov-team/issues/29356#issuecomment-920108507.
