### ISSUE TITLE
'Notice of rights and responsibilities' content assistance from the debt resolution team 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#29489]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
During a round of design feedback with our SME's, we received feedback to provide a way for Veterans to access their Notice of Rights and Responsibilities within the tool. I've since incorporated that content into a modal that opens up if the Veteran clicks on the link, 'Notice of rights and responsibilities' on the balance's details page (UXPin attached below). However, I noticed that most of the content can be found elsewhere in our tool. 

I'm looking for help on how the 'notice of rights and responsibilities' transition from paper format to the site has been handled in the past. It seems like we could display a condensed version containing the content not found elsewhere in our tool, but I don't know how this topic has been approached with stakeholders for other projects. 

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: 
- Link to or attach user flows:
- Link to prototype or mockups: 
   - [Details page](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/140772652/simulate/sitemap?mode=i)
   - [Full content ](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141491504/simulate/sitemap?mode=i)
   - [Shortened content](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141491503/simulate/sitemap?mode=i)
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: End of September
- Estimated staging review date: TBD
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by rileyorr** [comment]
Update on this work: I talked through the work and presented the designs in @bethpottsVADEPO's office hours and she said she would sync up with Danielle about what we chatted about

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rileyorr! @bethpottsVADEPO gave me an update on this. 

This does feel like a lot of content for a modal. I can't say that I've seen how other products handle notices of rights and responsibilities, specifically, but I know that some teams have versions of the privacy act statement modal in staging with longer content (click the privacy act link on this page in staging as an example: https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction).

Beth and I agree that we wouldn't recommend cutting out information based solely on the fact that it's found elsewhere in the tool (unless you're going to position it as something like "_Other_ information about your rights and responsibilities you need to know" to indicate that this is supplemental info).

This is a legal notice meant to cover all the key points of someone's rights and responsibilities. So we don't want to just cut parts of it assuming that Veterans will know that info is located in other places (and that probably wouldn't align with legal requirements). That said, there may be a way of condensing this information and it would also be good to do a plain language pass at some point. 

This might be a case of needing to go with the full notice, as is, for launch, and creating a ticket in the backlog to condense/plain language it in the future. Thoughts?

**Comment by rileyorr** [comment]
@DanielleThierryUSDSVA that works, thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Moving this to backlog since we decided this is something we'll need to come back to later.

**Comment by denisecoveyduc** [comment]
@DanielleThierryUSDSVA wondering if this still applies? Happy to keep it on the books if so.
