### ISSUE TITLE
[Support] Google Tag Manager for Drupal CMS (Internal Usage)

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#295]
As a CMS team member, I want to see how often users are interacting with the backend. This activity will be measured in a separate internal-only Google Analytics property.

Acceptance criteria:
- [x] GTM code provided to Agile6
- [ ] GA tag created for internal GA property
- [ ] Publish tag

**Comment by nedierecel** [comment]
@jefflbrauer This was an older request to measure Drupal usage. Should we leave here?

**Comment by jefflbrauer** [comment]
@nedierecel Let's leave this and prioritize for 2020 :)

**Comment by nedierecel** [comment]
@joanneesteban This is an older issue requested in 2019. This is now covered in #5673 outlined by the work @jonwehausen has in progress.
