### ISSUE TITLE
DGIB: Transition EDU Form 22-0994 (VET TEC)

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29504]
## Description:
This is a placeholder epic that contains backlog work related to Form 22-0994 that is being transitioned to the Digital GI Bill project.

## Note:
This form was implemented prior to the current collaboration checkpoint system and as a result does not have most of the corresponding artifacts.

## Resources:
[Form Documentation in repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/application/vettec-0994)

**Comment by mrblanco1** [comment]
This epic was competed. There are no pending items to be done.
