### ISSUE TITLE
DGIB: Transition EDU Form 22-1990S (VRRAP)

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29520]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md)

## Description:
This is a placeholder epic that contains backlog work related to Form 22-1990S that is being transitioned to the Digital GI Bill project.

## Resources:
[Form Documentation in repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/application/VRRAP)

**Comment by mrblanco1** [comment]
This epic was completed. There are no pending items to be resolved.
