### ISSUE TITLE
Access for Joseph Hall

### ISSUE THREAD

**Issue by joehall-tw** [department-of-veterans-affairs/va.gov-team#29526]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Scott Mason
- Please provide your name.
   > Joseph Hall
- Please Provide your email.
   > joe.hall@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Orchid, Developer, Thoughtworks

- Requesting SSH key authorization?
   > ALREADY DONE. 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDikRYTQQVptNV+k/bpaowLOCBn+WtYXeGhWxMY5FS9BesjAs3dpch8vNGxjpeXuyNqmmQQnoDxg80dFN1IgxprLS0UtkmBXJ7MPv6H+lXwdAavGhUcr5P0Dhh46x2m9MHvWJx4ATILiwz2gSPu0Ko8NPdYRBFidLfK4tl7WrQp+Dnuj5sheYD9DOLbjqGLpsc9j3mVowR505Q2x4Y2X46COoALh86ApyO3ll4QU1UGaYIHsKhhrbulK+AYklSMp2QTAjayg75ye/VbU1wVIH0c/R3qCgpbv6+Vb1J02UGz72aciVi5KM5jXWBCztinAOL0LdOHh320fcVUoZfCbhFaSZpL3OE3KpytOvmxN6HGkbNgzrJFChXpld0bZy5RiBRefBOjsYdTVrIJFJBz9bJidIx+UVWUG6SKlnVxgdoW4mxAYvZdhKllSk7Xaj5XI3ONhyyhmpfBMUfF/9ITWIVKQi5TjdrGAk5tthmZECJiVLg11vXrp8L5rAeNGUHa5AM= groundh0g@josephs-mbp.lan
```

- Grant AWS Console access?
  > YES
  - I need access to the AWS secret manager so I can add pipeline secrets for the va-virtual-agent team to AWS.

**Comment by mydesignrocks** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by joehall-tw** [comment]
I edited the text to reflect new requirement for AWS. Adding this comment to reopen. If you need a new ticket, please let me know. Thanks.

**Comment by omgitsbillryan** [comment]
Please close this ticket and open a new one. It helps w/ our internal tooling & auditing, and will ultimately result in a more timely approval for you.

**Comment by joehall-tw** [comment]
Will do. Thanks.
