### ISSUE TITLE
QA Audit Public Websites (Formerly Global UX)

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2952]
Contact: Kara Kemahli

AC: 
- [x] Talk with team about what features they are working on
- [x] Note any places the team needs help with QA
- [x] Note any QA resources already working on that team
- [x] Create tickets for work needed to assist the team

**Comment by peterhill-oddball** [comment]
Start with contacting Kara Kemali.

**Comment by peterhill-oddball** [comment]
Per Kara, their current efforts are related to content and design work.  They are making no functional changes to their product.

Mikki and Peggy are responsible for deploying their mostly Drupal changes.
