### ISSUE TITLE
Footer Changers from IA

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#29528]
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [x] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [x] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * < description > 
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [x] **Other -  Updates to the  global footer**

**These updates can be done at any time**
1. Move the "VA performance dashboard" link out of the sub-footer (2 rows at very bottom) up to the main footer under the "Get VA updates" column.  Place this option as the last option in the column.  
2. Add a "Civil Rights" link (destination https://www.va.gov/resources/your-civil-rights-and-how-to-file-a-discrimination-complaint/) to the sub-footer.  Place it after the "Accessibility" option.  
3. Move the "Freedom of Information Act (FOIA)" to be after the new "Civil Rights" link so it is in proper alpha order with the other links in those 2 lines. 

**This change is waiting confirmation before implementation**
4. Remove the "Veterans portrait project" link from the sub-footer 

**This can be done once the new harassment static page is live**
5.  Add a "Harassment" link (destination www.va.gov/report-harassment/) to the sub-footer.  Place it after the FOIA link so it is in proper alpha order in that list. 
    - IA info: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27911

      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* see above

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: IA
- DEPO product owner: Dave Conlon
- Product manager:  n/a
- Designer: n/a
- FE engineer: n/a
- Product/team Slack channel: 

--- 
#### Acceptance Criteria
- [x] Convert this request into a Zenhub epic
- [x] Follow-up with requestor to address any lingering questions/concerns
- [x] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by mnorthuis** [comment]
Sub-footer links and order, for reference:

![image](https://user-images.githubusercontent.com/20994159/131571678-50ca33f8-952f-4b63-aa3e-e1f71ddb97cd.png)

**Comment by mnorthuis** [comment]
FYSA @davidconlon @DanielleThierryUSDSVA

**Comment by kelsonic** [comment]
1. Move the "VA performance dashboard" link out of the sub-footer (2 rows at very bottom) up to the main footer under the "Get VA updates" column. Place this option as the last option in the column.
2. Add a "Civil Rights" link (destination https://www.va.gov/resources/your-civil-rights-and-how-to-file-a-discrimination-complaint/) to the sub-footer. Place it after the "Accessibility" option.
3. Move the "Freedom of Information Act (FOIA)" to be after the new "Civil Rights" link so it is in proper alpha order with the other links in those 2 lines.
4. Remove the "Veterans portrait project" link from the sub-footer
5. Add a "Harassment" link (destination www.va.gov/report-harassment/) to the sub-footer. Place it after the FOIA link so it is in proper alpha order in that list.

Just confirming these are all ready to be implemented? @mnorthuis Do we want to move 4 + 5 into a separate ticket if they aren't ready yet?

**Comment by mnorthuis** [comment]
4 and 5 are not ready, you can move into a separate ticket if you want

**Comment by brianalloyd** [comment]
@kelsonic I'll break out 4 & 5 into a connected ticket for tracking and timing.  I have this slotted for the upcoming sprint for the items that ready, pending items will wait until ready.

**Comment by kelsonic** [comment]
Thanks @brianalloyd! 🔥

**Comment by brianalloyd** [comment]
@mnorthuis wanted to reach out and see if you were taking the lead in coordinating efforts in support of `4. Remove the "Veterans portrait project" link from the sub-footer` or was this something @davidconlon was closing the loop on in support?

**Comment by kelsonic** [comment]
1-3 are now merged, will go out with daily deploy tomorrow 🙂

**Comment by mnorthuis** [comment]
@brianalloyd - Dave is digging into it, and I will let you know as soon as we have info.

**Comment by brianalloyd** [comment]
@mnorthuis work is complete for 1-3 on this ticket, I've moved 4-5 to separate tickets based on timing.  I'm going to close out this ticket in support and will keep it connected to the follow on tickets for items 4 & 5 as discussed.
