### ISSUE TITLE
QA Audit Benefits and Memorials 

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2953]
Contact: Yana Roy

AC: 
- [x] Talk with team about what features they are working on
- [x] Note any QA resources already working on that team
- [x] Note any places the team needs help with QA
- [x] Create tickets for work needed to assist the team

**Comment by peterhill-oddball** [comment]
Start with contacting Yana Roy.

**Comment by peterhill-oddball** [comment]
## Upcoming features :
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/b119a267-1166-41aa-9a8b-d250cea55c9f)

## QA resources:
Tze is assigned to this team.

## Help:
No help requested at this time

## Work assigned:
N/A
