### ISSUE TITLE
Access for Stefanie Gray

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-team#29549]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Anthony Arashiro
- Please provide your name.
   > Stefanie Gray
- Please Provide your email.
   > stefanie.gray@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA++IT4YhfZS1oVkeYTHxPUtXUyY0y8TvHRgxCecfHUzgH5GIvcmfOTPdwV7AkdV64XNeYbstAZ5fJgCqysFe2fY/QaZdYV2jvj68hR10ZrRLyLwoO7dNHjoy9OKhSjGM/3LaynxASBoyaE93oVNSNU2s/R9b4ua9cfxiNtEmQy0FYZVUhKB0qgnlAsM1D5bbJP2sQLPNiGKBLU2vPVKEzKXijnrfYqjUE2Dz3MdK1nxzpq7oTk8C5hSX62vsb9BNbBn6x2LSCWBT2wnv0x41IQChzVPiWSwfZI46FgVQmop233QN+dfImQ08ZUNe/X24+FkMDcKKQeDvXqnZuVS5+eckm5q7Fwuq1NX0u7ODqOO/jQLTwJnECoFrw+TKmU4vEfLpevTqu+EKv3LYM0fGd0WTJzERRc9KRlZ1vkJYW+AxezCdPqshzKnBinMeIZHvBLDhW7Jp7OkXa6NhRCZgLYjYNi9jG3IZByhsAZdokFNKxk9oU8TfgqeWQo4kRa1U= stefanie.gray-a@MacBook-Pro
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by stefaniefgray** [comment]
This was supposed to be auto-generated when running the VTK tool in Terminal, but it was not

Here is the error message from when this Github issue should've been created by the script:
```
An SSH key has been created. Would you like to copy the key to your clipboard and open the access request issue in GitHub now? Yes
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2561, NSUnderlyingError=0x7fa3fb60dd90 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7fa3fb60e450 {Error Domain=OSLaunchdErrorDomain Code=125 "Domain does not support specified action" UserInfo={NSLocalizedFailureReason=Domain does not support specified action}}}}}
```

Special thanks to Eric O. @ Agile 6 for all of his help!

**Comment by mydesignrocks** [comment]
access has been granted and verified. closing as there is no further access requests
