### ISSUE TITLE
QA Audit Authenticated Experience

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2954]
Contact: Justin Pickett

AC: 
- [x] Talk with team about what features they are working on
- [x] Note any QA resources already working on that team
- [x] Note any places the team needs help with QA
- [ ] Create tickets for work needed to assist the team

**Comment by peterhill-oddball** [comment]
Start with Justin Pickett.

**Comment by peterhill-oddball** [comment]
In contact with Justin Pickett, the following input was provided regarding upcoming QA efforts --

>1. Do you have a roadmap?  What features / user stories are you working on currently?
1. Do you have QA personnel on your team?
1. Do you have an internal QA process on your team?
1. Do you need assistance with QA from the platform team?

1. We do have a road map...its a little in flux at the moment.
2. We do not have a dedicated QA team member on our team. Currently we utilized a shared resource "Tze" for our QA efforts when needed.
3. We don't have a set QA process for things that are developed daily as they are moved into validation but we have a more formal process for coordinating with Tze on bigger feature releases.
4. Yeah I think any assistance with QA from the platform team would always be helpful.

**Comment by peterhill-oddball** [comment]
Created a ticket to query Tze regarding details of the test effort for this one.
