### ISSUE TITLE
[FE] Profile, Notification Prefs: Implement solution for redirecting users back to notification prefs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29542]
## Background
The MVP for notification prefs allows the user to easily navigate to the contact info section of profile to make updates to phone and email when needed. Liz came up with a light solution that helps redirect the user back to the task of completing their notification preferences once they have updated their contact information, which they will often have to do in order to set their notification preferences.

See designs in #28636 

## Acceptance Criteria
- [ ] User can click link on notification prefs page to add/update their mobile phone
- [ ] Link deep links them to the mobile phone section of the contact info section of profile
- [ ] Once mobile number is added/updated, a link appears to prompt the user to go back to notification preferences to finish setting their prefs
- [ ] Clicking the link takes the user back to notification prefs
- [ ] If a user removes their mobile phone number, they are not prompted to manage notification settings
- [ ] If a user navigates to add a mobile number via a means other than a CTA on the notification settings page, they are not prompted to manage notification settings.

**Comment by andaleliz** [comment]
FYI I updated the AC above to include the points below. I realized we should check for these things in UAT to confirm it works in all the correct ways, and figured I should add these points here as well.  

> If a user removes their mobile phone number, they are not prompted to manage notification settings
> If a user navigates to add a mobile number via a means other than a CTA on the notification settings page, they are not prompted to manage notification settings.

**Comment by erikphansen** [comment]
@andaleliz @ajakabcin was just about to say that this is ready to validate on staging. And it is, but I do need to address a couple issues for this point of AC:
> If a user removes their mobile phone number, they are not prompted to manage notification settings

**Comment by erikphansen** [comment]
This _is_ ready to validate if you ignore this point of AC:

> If a user removes their mobile phone number, they are not prompted to manage notification settings

I have https://github.com/department-of-veterans-affairs/vets-website/pull/18898 up to fix that particular case.

**Comment by erikphansen** [comment]
@andaleliz @ajakabcin Okay this should be _done_ done now. The fix for that last remaining bit of functionality is on staging.

**Comment by andaleliz** [comment]
This looks great @erikphansen! Thanks for your attention to detail.  Closing this out.
