### ISSUE TITLE
Remove Un-Used Non-Prod Specific Events

### ISSUE THREAD

**Issue by laurensimpson14** [department-of-veterans-affairs/va.gov-team#29550]
There is a variable called `Staging Only - Base Configuration`, and it's tied to 3 events that aren't in use: 
1. `Debug Event`: This is set to fire on the custom event `^debug.*`, however in GA it hasn't fired since last November (and even then it only fired twice)
2. `TEST STAGING ONLY - Profile Form Submit`: The trigger for this is paused, and I don't see any data from this event in GA for the past 5+ years
3. `TEST STAGING ONLY - Profile Saved - API Calls`: The trigger for this is also paused, and I don't see any data from this event in GA for the past 5+ years

I'm thinking that we can likely retire the variable, the three events, and the three associated triggers. @bsmartin-ep are you aware of any reason we may still need these?

**Comment by johnny-jesensky-adhoc** [comment]
Closing -- no longer need.
