### ISSUE TITLE
Add options for larger max-old-space-size in yarn commands

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29556]
Slack context: https://dsva.slack.com/archives/C5HP4GN3F/p1630441590019500

**Comment by cvalarida** [comment]
I said this in the thread, but I'll mention it again here for posterity: I recommend using an environment variable with a default value.
```sh
NODE_OPTIONS=--max-old-space-size=${VA_BUILD_MEMORY_LIMIT:-4096} webpack-dev-server ...
```
This lets us set a relatively sane default while allowing folks to override it either for a single command or whenever they run the dev server.

**Comment by Rleahy22** [comment]
Is this available for anyone to pick up or just the tools team?

**Comment by timwright12** [comment]
Update: need to rework this command a bit, the way we're calling it doesn't appear to allow us to put a bash variable in there like normal
