### ISSUE TITLE
Content Request (R&S Article) Auth Profile Team for Notification Settings

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#29557]
We're adding a notification settings section to the VA.gov profile; our MVP will be launching in fall of 2021. 
Creating this ticket to:

- [ ] Evaluate whether or not it is appropriate to create an R&S page for this new feature
- [ ] If so, complete the necessary steps to get that page created.

If we do create an R&S page, it would be great if the timing was not too far off after we launch our MVP.  We don't have a hard launch date for our MVP so we certainly have flexibility with the timing on this.

IMO, I think it makes sense to create this page to help Veterans understand a few things:
- where they can manage notifications on VA.gov
- where they can manage VA notifications they are receiving that are _not_ managed on VA.gov (e.g. health care email notifications must be managed on MHV)
- why they can only get some notifications by text, and some by email
- why they may be getting notifications that can't be managed anywhere (default things they're opted into).

cc @ajakabcin for awareness and tracking

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA I'd love to discuss this during office hours next week. Can we plan on that?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks for bringing this to office hours yesterday, @andaleliz!   

**Capturing notes from our discussion here:**

- A Resources and Support article to help Veterans understand their notification options and how to manage them is probably a good idea, yes. The content team can look at SEO, contact center questions, etc. and craft and article.
- We'll also want to take into account the new notifications Terms and Conditions page ([issue #25887](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25887)) and a recent request to migrate and rewrite VETtext FAQs into Resources and Support ([ticket #28245](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/28245)).
- The sitewide content team will need to put this in our backlog and prioritize against other work. We'll reach out when we're ready to begin the work.

cc @bethpottsVADEPO @RLHecht

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht I moved this from In Progress to Backlog for now. This is important, but not something we have the capacity for right now, so just moving it for transparency. Thanks!

**Comment by SKasimow** [comment]
@andaleliz @cgednalske - is timing right to re-visit this work now?

**Comment by andaleliz** [comment]
This is in the content team's court, I believe.

**Comment by mtcA6** [comment]
@andaleliz since the content team seems busy, would it make sense for us to create something like an overview for the profile while we wait for an R&S page? 

Today we land users on the first thing in the profile. They then have to click on each section to know what is available within that section. 

We could create something like what's in the images below (examples from banking and shopping websites) where they give users clues on what to find w/in each section of the profile w/out having to open each 

eg. chase bank
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/5367b9ef-887a-4de5-9330-d9b6fd9f0378)

eg. amazon
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/8efb7c4c-616c-4723-a089-3b0798551b9a)

**Comment by andaleliz** [comment]
@mtcA6 definitely something worth further discussion. The team has talked about this "hubless spoke" problem in the past - that phrase means that there isn't a landing page for all the profile spokes. 

There's an [open, related ticket,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40593) which I _think_ is on your radar given the recent CAIA ticket that was opened.

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Could you add this ticket to an upcoming grooming meeting to go over with the team and talk about capacity?

**Comment by mtcA6** [comment]
> @mtcA6 definitely something worth further discussion, though I think that's a separate thing from this resources and support page. The team has talked about this "hubless spoke" problem in the past - that phrase means that there isn't a landing page for all the profile spokes.
> 
> There's an [open, related ticket,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40593) which I _think_ is on your radar given the recent CAIA ticket that was opened.

@andaleliz I didn't recognize this ticket as related to the linked item. Are you suggesting creating a landing page like this for the profile would potentially operate as a solution to help with #40593?

**Comment by andaleliz** [comment]
@mtcA6, you're totally right, this particular ticket isn't related to the linked item.  The resources and support page is a separate thing from any changes we'd make to profile.

Your suggestion to create a landing page is related to the linked item.  I'm not personally suggesting anything at this point, just calling out that it's been discussed in the past, and we should take that into consideration as our team discusses your idea.
