### ISSUE TITLE
Find a VA Form: Full Test Coverage for Form Detail Template

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29553]
## Issue Description
 Story for adding full test coverage to the template that the Form Detail pages are created from

---
## Tasks
- [ ] Full test coverage for form detail page template

## Acceptance Criteria
- [ ] Full test coverage for form detail page template

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO I think this is at a good point to close up for us!
