### ISSUE TITLE
Update moment.js to pass date format

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#29568]
moment.js currently parses date strings by using the default JavaScript Date constructor and will be deprecated so we need to the input date format before sending it to moment.

`moment("09-02-2021", "MM-DD-YYYY");
`

Details about this issue can be found here: http://momentjs.com/guides/#/warnings/js-date/ 
Supporting documentation: https://momentjs.com/docs/#/parsing/string/

Warning received for www.va.gov/manage-va-debt/your-debt

`instrument.js:109 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.`

![Your VA Debt  Veterans Affairs 2021-09-02 09-22-52.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/9830042f-a94e-4aed-8b5c-b6bbdb188953)

**Comment by craigwheeler** [comment]
usage of moment has been updated and the warning has been suppressed will continue to monitor this issue

**Comment by drorva** [comment]
Has this been merged into master? I just checked with the user and they're still having problems getting an exception with the date.
