### ISSUE TITLE
Adding Amy Lai to DSVA Slack

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#29560]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- What channel(s) do they need to be added to?
#appeals, #appeals-announcements, #appeals-wisdom-wed

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Amy Lai is a new Caseflow Product Manager.  Her email address is: amylai@navapbc.com

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add amylai@navapbc.com as a full member.

**Comment by LizCallaghan** [comment]
done!
