### ISSUE TITLE
va-alert padding is too big

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#29576]
## Issue Description
The `va-alert` padding takes up more space than it should (compared to the old component).
![image](https://user-images.githubusercontent.com/12970166/131754494-ae107ff9-7c40-47c3-9ee3-c6095446e0b5.png)

## Acceptance Criteria
- [ ] The padding is uniform and reasonably sized (matches the legacy component)

**Comment by bkjohnson** [comment]
Fixed in https://github.com/department-of-veterans-affairs/component-library/pull/212
