### ISSUE TITLE
[S3] Permissions needed to manage "testing-tools-testing-reports" bucket

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#29571]
## Description
Now that uploads are working from GHA to the bucket `testing-tools-testing-reports`, I need a bit more help making sure we can manage our bucket appropriately.

1) I need to be able to set object expiration for our files in our bucket `testing-tools-testing-reports`.  We'd ideally like all reports and videos to fall off every 30 days, to keep it from ballooning in size too much over time.
2) It'd be nice to additionally be able to delete files from the bucket `testing-tools-testing-reports` (I uploaded a few in the wrong directory structure and I'd like to clean it up).

---
## Tasks
- [x] Add S3 permissions to testing-tools team group in IAM

## Acceptance Criteria 
- [x] Testing tools team can make changes to files/folders in the S3 bucket 'testing-tools-testing-reports'

**Comment by mydesignrocks** [comment]
worked with curt and provided the required access to the s3.

**Comment by CBonade** [comment]
All works great for me, thanks for this!

**Comment by pjhill** [comment]
Thanks for addressing this ticket, Ops! All work related to this ticket is complete.
