### ISSUE TITLE
QA Audit API Team

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2957]
Contact: Kelly Lein 

AC: 
- [x] Talk with team about what features they are working on
- [ ] Note any places the team needs help with QA
- [ ] Note any QA resources already working on that team
- [ ] Create tickets for work needed to assist the team

**Comment by peterhill-oddball** [comment]
Start with Kelly Lein.

**Comment by peterhill-oddball** [comment]
Initial communication with Kelly Lein and Kendra Skeene indicate that they are not formally a part of the VSP.  Whether or not the VSP product support team needs to get involved probably depends on their membership on the platform.

**Comment by peterhill-oddball** [comment]
VSP processes do not apply to this team.
