### ISSUE TITLE
Add Rollback Support to GitHub Action Workflow

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#29578]
## Details
Currently, if a production deployment has an issue and needs to be rolled back to a previous commit, this is possible through Jenkins. This is done by triggering a new deploy job in Jenkins and passing in a previous release tag. More details on this process are described here: https://vfs.atlassian.net/wiki/spaces/FTT/pages/1844641889/Deployments#Rollbacks

This functionality should be available in GitHub Actions. The process should be as similar as possible to the Jenkins process.

## Tasks
- [x] Add rollback functionality to `vets-website`
- [x]  Add rollback functionality to `content-build`

**Comment by meganhkelley** [comment]
Solution may depend on what we end up doing for #29873 — check in there before starting this

**Comment by oseasmoran73** [comment]
@timwright12 @ndsprinkle Depending on how #29873 and the direction that it is going in, we may not go the route of separate workflow. If that is the case, I propose the following:

Currently in GHA, for manual deploy the options to enter `time to deploy` (default to 5). See screenshot below.

![image](https://user-images.githubusercontent.com/10648480/133515917-933ea056-9d22-49c5-a838-c4877678f515.png)

What we can do is conditionally check if a commit is passed. Default will be null (this is specifically for manual deploy, `cron` will be `github.sha` default) and if a commit is passed, skip all steps (validate-build, notify-start, build [only in content-build], create-release) and go directly to `deploy` 

Thoughts?

**Comment by oseasmoran73** [comment]
Closing ticket as it has been merged `content-build` and `vets-website`
