### ISSUE TITLE
QA Audit VA Online Scheduling

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2958]
Contact: Mark Greenberg (they have a hard deadline coming up on veterans day)

AC: 
- [x] Talk with team about what features they are working on
- [x] Note any places the team needs help with QA
- [x] Note any QA resources already working on that team
- [x] Create tickets for work needed to assist the team

**Comment by peterhill-oddball** [comment]
Start with Mark Greenberg.

**Comment by peterhill-oddball** [comment]
Created ticket #3397 to track future Product Support QA activities with this team.
