### ISSUE TITLE
[Content] Notification Settings - Update content to reflect notification settings

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#29582]
We need to track down any pages on VA.gov that 

- reference email notifications for health care and claims/appeals and update accordingly to reflect the new notification settings section on the site.
- have content where it would make sense to tell Veterans that now they can manage related settings in their profile (e.g. appeal status information)

[Here's the list of MVP notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/communications-permissions-mvp-configuration.md) we're launching with (3 in total)

Pages
- [ ] https://www.va.gov/claim-or-appeal-status/index.html is an unauth page that might be a reasonable place to put information about being able to opt into text appeal hearing reminders
- [ ] https://www.va.gov/health-care/refill-track-prescriptions/ references email notifications under `How can VA’s prescription tool help me manage my health care?`.  Now text notifications are also available, but in a different way than email since MHV still handles email notifications

<img src="https://user-images.githubusercontent.com/55992116/131865575-72a7f896-d2d7-4710-8fbb-6cc4103c6980.png" width="50%" />

- [ ] Would the appeals hearing reminder be relevant to Veterans in the context of other other unauth content about appeals hearings, such as https://va.gov/decision-reviews/board-appeal/ ?

**Comment by andaleliz** [comment]
@ajakabcin created this ticket since I came across the instance in the description. I can add more pages as I come across them.  It'd be great if you could add any you think of too. We'll have to work with Danielle + team on the content, and they may be able to help us track more down.

RE this piece:
> We also need consider whether or not we want content added to MHV and/or eBenefits to let people know about these new settings.

Is that something you can take the lead on? From a UX perspective I think it makes sense to do so, but I think your product strategy expertise would be helpful here.

**Comment by andaleliz** [comment]
Danielle works all the time with MHV content strategy manager, he is very supportive of alignment and promoting meaningful tips/tools for Veterans.  She has offered to help us meet with him to figure out the best way to align if we decide to want to put something on MHV.

**Comment by ajakabcin** [comment]
> I can add more pages as I come across them. It'd be great if you could add any you think of too. We'll have to work with Danielle + team on the content, and they may be able to help us track more down.

Could probably put out an APB in platform, with the other VFS pm's, and/or at next week's ToTs for folks to flag instances they know of in their products as well

**Comment by andaleliz** [comment]
That makes sense to me! I'll remove the MHV reference from the description of this one.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA, I'm following up on our discussion last Thursday - I believe you said your team would help identifying content where it would make sense to update or add info about our new notification settings. Can you confirm?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. Yes! We can help with this. @RLHecht can you add this as a discussion point for our next content check-in meeting? Thank you!

**Comment by RLHecht** [comment]
@andaleliz Here's the list of our pages I found. @DanielleThierryUSDSVA Let me know if you think I'm missing any or if some of these don't make sense.

https://www.va.gov/health-care/refill-track-prescriptions/
https://www.va.gov/health-care/secure-messaging/
https://www.va.gov/health-care/schedule-view-va-appointments/
https://www.va.gov/health-care/view-test-and-lab-results/
https://www.va.gov/health-care/get-medical-records/
https://www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/
https://www.va.gov/health-care/order-prosthetic-socks/
https://www.va.gov/claim-or-appeal-status/
https://www.va.gov/decision-reviews/board-appeal/
https://www.va.gov/decision-reviews/supplemental-claim/
https://www.va.gov/decision-reviews/higher-level-review/
https://www.va.gov/decision-reviews/contested-claims/
https://www.va.gov/decision-reviews/insurance-claims/
https://www.va.gov/decision-reviews/fiduciary-claims/
https://www.va.gov/disability/how-to-file-claim/

**Comment by andaleliz** [comment]
@RLHecht thanks for this list! I lost track of this ticket since it's not in our sprint - will review these and get back to you asap.

**Comment by andaleliz** [comment]
@RLHecht so sorry for the delay.  I've taken a look and there are definitely some relevant pages here. 
- It makes sense to me to include content about managing appointment reminder notifications on https://www.va.gov/health-care/schedule-view-va-appointments/.   However, this page mentions the VAOS tool, and managing notifications will be done outside of that tool.
- Content about managing BVA appeal hearing reminders makes sense to me on the following pages, though I'm not quite sure how to incorporate it.
  - https://www.va.gov/claim-or-appeal-status/
  - https://www.va.gov/decision-reviews/board-appeal/
  - https://www.va.gov/decision-reviews/contested-claims/

- I realized that it might not make sense to update anything on the prescription page yet.  The prescription shipment/tracking notification is in beta at only 2 VAMCs, so it won't apply to the majority of users. I think we should update that page once it's fully rolled out.

- The rest of these claims related pages mention BVA hearings, but it feels a little premature in the process to start telling Veterans about reminders for their scheduled hearing.  What do you think?
 - https://www.va.gov/decision-reviews/supplemental-claim/
 - https://www.va.gov/decision-reviews/higher-level-review/
 - https://www.va.gov/decision-reviews/insurance-claims/
 - https://www.va.gov/decision-reviews/fiduciary-claims/
 - https://www.va.gov/disability/how-to-file-claim/


- We don't have any notifications related to records, lab results, hearing aids, or prosthetic socks so I don't think we need to update anything on those pages just yet.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA and @RLHecht , I updated the label since we're not launching until Nov. This is def work we'd want to do post-MVP launch. December would prob be fine too.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA and @RLHecht our team would like to check in with you regarding this work. Any thoughts on [my response](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29582#issuecomment-938681764) to the pages Randi shared?

Would it be possible to move these updates forward in the next 2 weeks? I If not, what is a reasonable timeline for your team?

Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @andaleliz! @RLHecht, let's add this to our agenda for our next content team check in and then get back to Liz on timing.

**Comment by DanielleThierryUSDSVA** [comment]
Notes from 11.18.21 office hours:

- We can add a question at the bottom of relevant pages that speaks to "Can I get X reminders?" and explains the different ways to get reminders/notifications.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA by any chance do you have an ETA from your team? I know you were going to check with Randy in your team check in and try to figure out a date. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Good morning, @andaleliz! Hope you had a great holiday. The team is aiming to add this to this next upcoming sprint along with some other work on tool pages. Thanks! cc @RLHecht

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA awesome, thank you! I'll move this into our next sprint then. I hope you had a great holiday too.

**Comment by andaleliz** [comment]
FYI @MarciMcGuireGCIO I moved this into Sprint 62 for our team.

**Comment by DanielleThierryUSDSVA** [comment]
Connecting this issue to the content work for this ([#33349]([url](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/33349))). Thanks!

**Comment by andaleliz** [comment]
Hi! Do we still need to keep this open now that we have #33349?

**Comment by Samara-Strauss** [comment]
Not sure on my end. @DanielleThierryUSDSVA is the best person to make this determination.

**Comment by RLHecht** [comment]
I can close this as we're tracking the work in the ticket listed above.
