### ISSUE TITLE
[Design] 10-10EZ Intro: remove the word "full" in content source of truth

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#29585]
## User Story
As a Veteran, I need to understand that there is no partial enrollment status for the 10-10EZ.

The purpose of this story is to update the content source of truth.

## Expected Behavior

We need to remove the word "full" from the first sentence under the **Check your eligibility" section on the 10-10EZ.
![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/07d28ff8-3a80-430f-8c23-a5daa457e3bc)

## Acceptance Criteria

- [x] Remove the word "full" in content source of truth

**Comment by Dene-human** [comment]
Done: [Source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/commit/0d3144cb47fa4247a32d0ca40450e1def2521361#diff-dca6278f1e951f3986ffa644f72b0187b2f2c32b32edf894d20032101d87c74e)
![Screen Shot 2021-09-03 at 1 22 27 PM](https://user-images.githubusercontent.com/80857940/132044120-65416bfc-11c5-44bd-862d-447e79750bdc.png)
