### ISSUE TITLE
QA Audit Notification MVP (bylight) 

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2959]
Contact: Lichelle Bain? 

AC: 
- [x] Talk with team about what features they are working on
- [x] Note any places the team needs help with QA
- [x] Note any QA resources already working on that team
- [x] Create tickets for work needed to assist the team

**Comment by peterhill-oddball** [comment]
Start with Lichelle Bain.

**Comment by peterhill-oddball** [comment]
Lichelle provided various artifacts from her test efforts for the most recent release.

**Comment by peterhill-oddball** [comment]
Feedback sent to Lichelle.  No further support is needed for By Light at this time.
