### ISSUE TITLE
Offboarding of Jennifer Nguy

### ISSUE THREAD

**Issue by mramirez-va** [department-of-veterans-affairs/va.gov-team#29599]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Jennifer Nguy
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Lighthouse Software Developer, Liberty IT Solutions (BAH)
- Please provide any type of access they may have and their GitHub username. 
  > SOCKS, AWS, Slack
  
 
## AC
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @drorva, @mchelen-gov

**Comment by laurensimpson14** [comment]
Jennifer didn't have Google Analytics access or Domo access, so no action is needed.

**Comment by jbritt1** [comment]
@mramirez-va, it appears when you tried to request removal of this user the action failed due to permissions of your user on the GitHub repository ([failed action](https://github.com/department-of-veterans-affairs/va.gov-team/actions/runs/1194858454). I will post it again here to get the request fired off since it didn't go through and the admins were not notified and will also try to figure out why your / your team's perms are not allowed to use the action.

**Comment by jbritt1** [comment]
@mramirez-va, I have now added the `dvp-infrastructure` GitHub team with `Write` permissions on this repository. Hopefully it will work next time you or your teammates attempt to use the `/request` action.

**Comment by LizCallaghan** [comment]
removed from slack!

**Comment by jbritt1** [comment]
No PagerDuty, Datadog, Sentry access on the VSP side

**Comment by jbritt1** [comment]
User still requires access to GitHub: https://github.com/department-of-veterans-affairs/github-user-requests/issues/8069#issuecomment-914607312
