### ISSUE TITLE
No locations returned for COVID 19 vaccination

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#29601]
## What happened?
In VAOS, when trying to book a covid vaccine appointment, I get "We couldn't find a VA facility where you receive care that accepts online appointments for COVID-19 vaccines." instead of the patient's locations. CHYSHR and Ft Collins are set to Yes, Any in VATS but are not returned in VAOS. 

Without locations being returned, I cannot book a vaccine. 

## Steps to Reproduce
1. In Vaos, click Start Scheduling.
2. Click Covid 19 and click Continue.
3. Click Continue on the Covid Info page. 
4. Click No on the Have You Had A Vaccine page
Expected result: the location page displays Cheyenne and Fort Collins, the two locations where Covid is set to Yes in Vats. 
Actual result: The Location page says "We couldn't find a VA facility where you receive care that accepts online appointments for COVID-19 vaccines." 

This happened with Judy Morrison and all other test patients. 

## Desired behavior
Display Covid locations. 

## Acceptance Criteria
Covid locations display and I can book a vaccination appointment. 

Jira ticket: https://issues.mobilehealth.va.gov/browse/VAOSR-2385

Jeff Balboni  29 minutes ago
This isn’t a production issue, it’s related to the feature flag the front end has turned on in staging for MFS v2 testing: https://dsva.slack.com/archives/CMNQT72LX/p1630430086014100 (edited) 
It looks like a front end bug to me, can you enter it in Github?

**Comment by laurenernest** [comment]
@beth-wodzinski Ready for retesting

**Comment by beth-wodzinski** [comment]
Looks good! I'm able to schedule vaccine appointments now.
