### ISSUE TITLE
[Content/Communications]  - Determine whether or not we need to link from MHV or eBenefits to notification settings

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#29610]
**Since MHV has the email version of our health care text notifications, does it make sense to put a CTA or link back to notification settings there?**  

- Unsure exactly what the messaging would be since Veterans _already_ get the text messages and we're now giving them a way to manage it online (vs this being a brand new thing they can get)
- What would that look like as more health care notifications are added?

**Same questions for eBenefits w/ the appeals hearing reminder text notification**. 
- I believe Veterans already receive this text too
- not sure if they get opted in by filing an appeal, or if they get opted in only once a hearing is scheduled.

**Comment by andaleliz** [comment]
Danielle works all the time with MHV content strategy manager, he is very supportive of alignment and promoting meaningful tips/tools for Veterans. She has offered to help us meet with him to figure out the best way to align if we decide to it makes sense to put something on MHV.

**Comment by Samara-Strauss** [comment]
Going to close this since MHV and eBenefits notifications will eventually move over to VA.gov.
