### ISSUE TITLE
Deprecate Nightwatch in content-build

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#29611]
With the Cypress a11y scan taking over the Nightwatch scan, we should start the process of deprecating Nightwatch in content build. The steps needed to take are as follows:

**Ensure approval to start each step of this process with some form of management before merging**

- [x] Identify any existing Nightwatch specs that do not have a Cypress counterpart and convert these tests.
- [x] Ensure that Cypress is dockerized in GHA to avoid port conflicts and other Cypress issues.
- [x] Allow any new Cypress tests to run in CI for a minimum of 5 days to catch any test flakiness.
- [x] After the waiting period has passed, remove any unused Nightwatch specs and/or helpers. Attempt to separate these PRs by codeowner.
- [x] Remove Nightwatch as a dependency and all related configs and global helpers, once all specs and spec helper files are gone.

Specs that need to be rewritten:
src/platform/site-wide/tests/accessible-modal.e2e.spec
src/site/tests/home/00-required.e2e.spec

**Comment by CBonade** [comment]
The work for the entirety of this is done. At this point, we are just awaiting PR approvals and giving the tests time to test for stability before pushing the merge button.

https://github.com/department-of-veterans-affairs/content-build/pull/610

**Comment by CBonade** [comment]
This was merged in today and should be complete.

**Comment by pjhill** [comment]
We're doing it!
