### ISSUE TITLE
Offboarding of Thomas Apodaca

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#29627]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Thomas Apodaca
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Caseflow, Software Engineer, 9/3/21, NAVA
- Please provide any type of access they may have and their GitHub username. 
  > Slack and GIthub username: tomas-nava
  
 
## AC
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @drorva, @mchelen-gov

**Comment by laurensimpson14** [comment]
Thomas did not have GA or Domo access, so no action needed there.

**Comment by KCollinsBrown** [comment]
Please remove from DSVA Slack and AWS.

**Comment by jbritt1** [comment]
AWS access removal requested through the infrastructure team that manages Caseflow/Appeals users: https://dsva.slack.com/archives/CAM9FJ85P/p1631033978089100

**Comment by jbritt1** [comment]
No PagerDuty, Datadog, Sentry access on the VSP side

**Comment by jbritt1** [comment]
No signs of SOCKS access on the VSP side.

**Comment by jbritt1** [comment]
Additional pull requests for tracking: 
- https://github.com/department-of-veterans-affairs/appeals-deployment/pull/3454
- https://github.com/department-of-veterans-affairs/appeals-terraform/pull/410

**Comment by KCollinsBrown** [comment]
Hi @jbritt1 can you please remove Thomas Apodaca from Slack?  His user name is Tomas Apodaca.  Thanks.

**Comment by jbritt1** [comment]
> Hi @jbritt1 can you please remove Thomas Apodaca from Slack? His user name is Tomas Apodaca. Thanks.

We do not have the ability to remove, we can only make requests to the slack admins. I will fire off another though.

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/C01S729LX6X/p1631284588008400

**Comment by LizCallaghan** [comment]
removed from slack
