### ISSUE TITLE
Test Selection - Always regenerate the Cross-App Import Graph

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#29621]
Running `git diff` in GHA sometimes produces unexpected errors, which causes the `check-app-dependency-graph` to fail. When that happens the `cypress-tests-prep` job doesn't run, because it needs the `check-app-dependency-graph` job, and then the `cypress-tests` job doesn't run, because it needs the `cypress-tests-prep`. And ultimately, the diff for the commits in that push aren't evaluated to see if the graph needs to be rebuild. And if it does need to be rebuilt, it isn't.

Solution: Always regenerate the graph and try to push it. It will only push the commit to the branch if the graph is updated and is different than the one that already exists.

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/vets-website/pull/18533

**Comment by holdenhinkle** [comment]
We no longer save the graph. It's generated on each push and the graph object is used in test selection. This allowed me to delete some files and a CI workflow job, and it simplifies the dev experience.

**Comment by pjhill** [comment]
This has been completed and test selection is operating without issue for several weeks now.
