### ISSUE TITLE
Index BVA Decisions with Search.gov

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#29624]
##  Description

Goal is to index all BVA Decisions into search.gov but exclude those decisions from the general search results on www.va.gov

## Background 
- The existing search page at https://www.index.va.gov/search/va/bva.jsp will be shut down soon and the intent of getting the decisions indexed by search.gov is to stand up a search interface on search.gov that is restricted to BVA Decisions. Eventually, we might consider using their API to show results on a BVA site at va.gov but for now we just want to make the content available on search.gov.
- leveraging search.gov's existing service will eliminate the need to develop a new custom search feature with va.gov. 
- Kevin Reid has spoken with Dawn at search.gov who has indicated they can support my request but they want to make sure that indexing this content will not interfere with va.gov search as it works now.
- There are about 1.4M text documents in BVA Decision Search
- For the current legacy engine, Kevin Reid has BVA Decisions isolated to avoid conflicting with the main search engine. 
- Dawn, at search.gov, indicated that a filter to avoid use of those decisions could be added by VA Search teams. 
- All BVA Decisions are under www.va.gov/vetappXX where XX is 92 to 21 and represents years 1992-2021. 
- A filter to exclude BVA Decisions like *va.gov/vetapp*, or maybe *va.gov/vetapp9?,*va.gov/vetapp0?,*va.gov/vetapp1?,*va.gov/vetapp2?, would work.”

## Acceptance Criteria
- [ ] BVA decisions have been indexed by search.gov
- [ ] BVA decisions are not appearing on the search results page of va.gov
- [ ] Kevin Reid has what he needs to deprecate the existing search page at https://www.index.va.gov/search/va/bva.jsp

**Comment by nicole-leonard** [comment]
@denisecoveyduc @srsuddath Can someone tell me what soon is? In the first paragraph it states that url will be shut down soon.

**Comment by denisecoveyduc** [comment]
@nicole-leonard I'd recommend you reach out to Kevin Reid. I have a feeling "soon" may have already happened but he would know for sure.

**Comment by nicole-leonard** [comment]
Per Dave this is complete.
