### ISSUE TITLE
Adding several VHA team members to DSVA Slack

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#29623]
# Description

Please add the following VA employees as full members of the DSVA slack:

Ghosh, Roshni   Roshni.Ghosh@va.gov
Henderson, Blake   Blake.Henderson@va.gov
Purnell, Amanda L.   Amanda.Purnell@va.gov
Vega, Ryan J    Ryan.Vega@va.gov
Ripley, Beth Ann   Beth.Ripley2@va.gov

Please add them to #digital-health-platform channel as well.

These are all leads in the VHA innovation space.

**Comment by LizCallaghan** [comment]
done!
