### ISSUE TITLE
Unit test intermittently failing 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2963]
Unit test with description "successfully submits when at least one condition is selected" is intermittently failing. This is a unit test for the disability benefits / 996 form.

To reproduce run the following:

```
CHOMA_SEED=8xt28bNKFV yarn test:unit
```

Attempted fixes: 
- add a `done()` callback to the `setTimeout()`
- increase the timeout length to 1500 ms

Unit test link: https://github.com/department-of-veterans-affairs/vets-website/blob/30afad1a13ba81240827ca72b08bfda344dd5e15/src/applications/disability-benefits/996/tests/components/contestedIssues.unit.spec.jsx#L30-L55

**Comment by Mottie** [comment]
I've updated, and hopefully improved, the troublesome unit tests for the Higher-Level Review form in https://github.com/department-of-veterans-affairs/vets-website/pull/10984.

I did see there were more `setTimeout`s used in other unit tests, but they didn't appear to be an issue? If needed, maybe we can turn this issue into an epic and address these other tests?

**Comment by rianfowler** [comment]
Thanks @Mottie - `setTimeout` should be fine as long as we're using `done()`. I filed a bug because adding that didn't resolve the issue and it wasn't obvious to me how to fix the unit test.
