### ISSUE TITLE
SSH Keys Jenkins Job is not Running When New SSH Keys Are Committed to Github

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#29637]
## The Problem
SSH keys are not getting automatically deployed when they are committed to `master` in the devops repo.

[The Jenkins job for deploying SSH keys](http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/) may still be manually triggered as a workaround.

## Extra Context
The job is configured to be triggered on commits to the devops repo under:
```
ansible/global/config.yml
ansible/roles/dsva-config/files/authorized_keys/.*
```
[Build #840](http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/840/) is the last known job that was properly triggered. All subsequent job had to be manually triggered.

## Work to be Done
- [ ] Root cause why the job is not being triggered by commits to authorized keys
- [ ] Restore said build trigger functionality

**Comment by jbritt1** [comment]
Seems to have been a temporary blip as builds have been running successfully from what is currently observed in the job list:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/c0f671db-3793-4101-870d-4fad983c7760)

Verification that these were triggered by GitHub pushes and not manual intervention: 

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/f7d9d1ef-9a45-43c1-9059-faf8baba1970)
