### ISSUE TITLE
[App Hosting & Deployment] Service design: VFS interaction w/ the platform's new delivery infrastructure (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#29631]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/context 
Conversation w/ @mchelen-gov: 
Mike: 
"I'd love to see more definition of how Operations and VFSes interact. do we have them submit requests to us? is there a template that we provide? where does responsibility for application stability exist?"
Jesse: 
"that's a great q. my opinion on the vision would be that we try to provide them as many tools as needed to make sure that the app functions as expected, and it's up to them to monitor stability. Underlying infra should be a level of abstraction and concern that is "behind a wall" for the developer.
If the developers' tools show that some part of the underlying infra is to blame for stability, they can submit a support request and we can fix & improve it, or say... it looks like your code is broken.
Scalability is abstracted away as much as possible so that it scales as a function of demand."

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jbritt1** [comment]
No longer relevant, closing.
