### ISSUE TITLE
VSA Onboarding - Patrick Ryll

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#29636]
## Welcome to the VSA Program

Welcome! This issue will be used to track your onboarding to the VSA Program.

---

## Pre-Onboarding

**Operation Lead Tasks**

- [x] Send Welcome email to New Hire (request GitHub Username)

*Send Notifications with New Hire details (name, position, start date) to:*

- [x] Admin Analyst
- [x] VA Leadership
- [x] VA PO
- [x] Practice Lead
- [ ] VSP Onboarding

**Access, Paperwork and Program File Updates**

- [x] Access to [VSA Team SharePoint](https://governmentcio.sharepoint.com/sites/VSATeam)
- [x] Access to VSA PTO Calendar
- [x] Request [Access to VA Organization in GitHub](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19&labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D)
- [x] Access to [VSA GitHub Repositories](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-vsa/members)
- [x] Access to GCIO/AdHoc Slack Workspace
- [x] Request access to DSVA Slack Workspace
- [x] Request Hardware/Software (GCIO Only)
- [x] Request New Hire to Complete VA Onboarding Paperwork (GCIO Admin Analyst)
- [x] Schedule Program Overview Meeting

---

## Onboarding

**New Hire Tasks**

*Day 1*
- [ ] [Watch Chris Johnston va.gov Backgrounder recording](https://governmentcio.sharepoint.com/:v:/s/VSATeam/EeqymtQQGcFKo0i7GwsgF3YBfSfR7VtvJ1D30hhxSTTF5A?e=kjQtvm)
- [ ] Review [VSA Onboarding Doc](https://governmentcio.sharepoint.com/:w:/s/VSATeam/EZZcIzaCedxGuHYy58rD0F0B_xSODMW4MMEl8yJAThZjGQ?e=uRlTnl)
- [ ] Attend VSA Program Overview Meeting
- [ ] Share calendar visibility with team members
- [ ] Complete VA Onboarding paperwork (sent by VSA Admin Analyst)

*Month 1*
- [ ] Request SOCKS Access, after SAC Adjudication
- [ ] Complete VSP Orientation (Invite sent by VSP team)

**Operation Lead Tasks**

- [x] Inform Practice Lead, Product Manager to trigger communication
- [x] Conduct VSA Program Overview Meeting
- [x] Update Org Chart and Share with New Hire
- [x] Add New Hire to #va-vsa
- [x] Send out org announcement on #va-vsa
- [ ] Add New Hire to Program-wide Meetings

**Practice Lead Tasks**

- [ ] Send Intro Comms to New Hire
- [ ] Conduct Practice-specific Onboarding Meeting with New Hire
- [ ] Add New Hire to Practice-specific meetings
- [x] Schedule Accessibility Orientation meeting with New Hire and VSA Accessibility Specialists 

**Product Manager Tasks**

- [x] Send Intro Comms to New Hire
- [x] Conduct Intro Meeting with New Hire
- [x] Add New Hire to Product team meetings

**Program Manager Task**

- [ ] Check in with New Hire

**Comment by shiragoodman** [comment]
Patrick - invited you to VA.gov Platform - General Orientation at 4pm on 9/22
