### ISSUE TITLE
Access for Trevor Bosaw

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#29645]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Trevor Bosaw
- Please Provide your email.
   > trevor.bosaw@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Identity team, VSP 
   > Backend Developer
   > Oddball

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
  > Already have AWS access generally, but I am requesting additional access for Cognito. My team is working on an integration with va.gov and Cognito

**Comment by jbritt1** [comment]
@bosawt, are you part of the SSO team? Wanted to verify with you because we can either assign you to that IAM group (if you belong to it) or attach the additional permissions directly to your user. We like group memberships for most situations, but either way we can get this adjusted for you.

**Comment by bosawt** [comment]
I'm with the Identity team in VSP, so not the existing SSO/IAM team, but we're investigating Cognito as a scheme to bring SSO fully within VSP. It is likely the entire team will basically request similar permissions, so it might be worth creating a group membership for us, or changing an existing one that we're part of.

**Comment by jbritt1** [comment]
> I'm with the Identity team in VSP, so not the existing SSO/IAM team, but we're investigating Cognito as a scheme to bring SSO fully within VSP. It is likely the entire team will basically request similar permissions, so it might be worth creating a group membership for us, or changing an existing one that we're part of.

I _think_ [this pull request](https://github.com/department-of-veterans-affairs/devops/pull/9896) will be a good way forward. It re-purposes an older group and includes a name change (to make it more broad) and the addition of you to said group. Will post back here once that PR has been approved, applied, and merged.

**Comment by jbritt1** [comment]
@bosawt, you should be good to go at this time. You may have to log out of the console and back in / initiate new authenticated sessions for the permission changes to take effect. Please reopen or post here if any issues are observed.
