### ISSUE TITLE
[Spike] Direct scheduling potential

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#29647]
## Background
In Aug 2021, 8% of submissions were direct schedule and 90% of submissions were VA requests.

### Goal
Understand the relationship of direct schedule submissions to the total possible direct scheduling options. Did a user have the option to direct schedule for their type of care, but submitted a request instead?

---

## Tasks
- Answer the following questions:
  - If a user is in the direct scheduling flow, how might we know if they left that flow and went through the request flow instead?
  - How might we know if a facility has clinics that support direct scheduling (that could be surfaced to user)?
  - What events are we currently tracking on the Clinic Selection page?
  - What are the technical recommendations for implementing this tracking?

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations (including additional research needed) are documented in this ticket

**Comment by jbalboni** [comment]
1. Any time a user goes from the clinics page to the requested date page, they chose to drop out of the direct flow. We could also add an event when this happens, if that's easier to track. It's pretty straightforward
2. We have an event called vaos-eligibility-direct-available-clinics-failed that tracks when no VistA clinics are returned. It's by far the number one reason users drop out of the direct flow. It happend 3000+ times last week.
3. I don't see any custom events on the clinic page
4. It's a very small amount of effort to add tracking for users opting out of the direct flow on the clinic page, but we might be able to get a number from existing GA funnel tracking

It seems pretty clear from our current analytics that the main reason users aren't completing the direct flow are:

1. No VistA clinics to choose from
2. VistA clinics prohibited access issues

For 1, there are several things going on:
- Some number of users may not have a PACT and therefore no primary care clinics
- Some sites may have turned off DS by turning off their clinics, but not VATS
- Some sites may have intended to turn on DS, but haven't configured clinics correctly

**Comment by laurenernest** [comment]
Here's the funnel between Clinics and Request Calendar pages https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361/edit/RPx76RRFQkK4J99Ff3rNgg
