### ISSUE TITLE
Burials & memorials rewriting: Burial at sea

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2964]
@DanielleSoCompany commented on [Tue Jun 11 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18930)

## User story
As the family member of a deceased Navy Veteran, I need to know how to arrange for a burial at sea.

### IA details
- **URL:** /burial-at-sea/
- **Spoke:** More resources
- **Order:** 6

### Content details
- **Source page:** https://www.cem.va.gov/cem/burial_benefits/burial_at_sea.asp
- **SEO keywords:** burial at sea, navy burial at sea
- **What's needed:** 
  
- [x] Create new page in VA.gov style (including meta description) 
- [x] Add a link/label for this page on the burials and memorials hub page (after the Veteran grave locator) 
- [x] Find content on this topic in other page(s). Remove it and, instead, add a related link to this page. 

## Steps to completion
- [x] Draft page and build in Github @lillianjwarner 
- [ ] Review/edit pages @bethpotts  
- [ ] 2nd review/edit if needed @DanielleSoCompany 
- [ ] Package rewriting instructions and send to SMEs @DanielleSoCompany 

---

@DanielleSoCompany commented on [Tue Jun 11 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18930#issuecomment-501028467)

@Karak888 for awareness - we're starting on the burials & memorials rewriting. This is first issue of several that we'll start on this/next week. Thanks! 

---

@lillianjwarner commented on [Wed Jun 26 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18930#issuecomment-501060169)

@DanielleSoCompany Ready for review. 

https://vagov-content-pr-463.herokuapp.com/burials-memorials/burial-at-sea/

- Is there a preference between linking to [this page](https://www.navy.mil/navydata/questions/burial.html) and [this page](https://www.navy.mil/navydata/nav_legacy.asp?id=204)? We linked to the latter on another VA.gov page, but the former has larger text and doesn't say legacy in the URL (not sure if those things matter, though).
- The only page I added a Burial at Sea related link (and deleted burial at sea content in body text) to was /burials-memorials/plan-a-burial/. I searched "burial at sea" on VA.gov and this was the only va.gov page that came up. Let me know if I'm missing any pages.

---

@bethpotts commented on [Tue Jul 16 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18930#issuecomment-511672606)

Update: 7/15

I did a very high-level first edit. This should be considered a first pass. It needs to be reworked for organization with a second, more thorough edit, and it also needs a copyedit.

**Comment by Karak888** [comment]
@AnneHurley @mnorthuis I have moved this issue from vets.gov repo over to VA.gov repo.

**Comment by AnneHurley** [comment]
@RLHecht  This Heroku looks good to me and is ready for your copyedit. Let me know if you see anything I may have missed.

**Comment by RLHecht** [comment]
@AnneHurley This page is now built in Drupal: preview-prod.vfs.va.gov/preview?nodeId=2347

**Comment by Karak888** [comment]
@AnneHurley to pick back up

**Comment by Karak888** [comment]
@AnneHurley to bundle up ones she is finished.

**Comment by AnneHurley** [comment]
@RLHecht  This is ready to go live when content freeze is lifted; no longer waiting to push all Burials content live together.

**Comment by RLHecht** [comment]
This has been published. Moving to validate and will close when on live site. @Karak888

**Comment by RLHecht** [comment]
@mnorthuis Confirming that the IA for this page is the same as originally listed in this ticket. The sixth page under More Resources in Burials.

**Comment by mnorthuis** [comment]
No, this is not correct. Burial in a Private Cemetery and Burial at Sea are both children of Eligibility. Looks like that note was missed in this ticket.  We moved both of them from Resources to Eligibility.

**Comment by RLHecht** [comment]
Thanks @mnorthuis. This has now been moved to eligibility and I put it below the Burial in a Private Cemetery. If this one should come first in the order, just let me know.

**Comment by mnorthuis** [comment]
That is the correct order.  Thank you!

**Comment by RLHecht** [comment]
This page is live. Closing ticket. FYI @AnneHurley @Karak888
