### ISSUE TITLE
Access for Tony Valdez

### ISSUE THREAD

**Issue by tony-valdez-accenture** [department-of-veterans-affairs/va.gov-team#29642]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Laura Ross
- Please provide your Vendor Onboaring Representative name. This is the person from the contracting company responsible for your onboarding process.
   > cesar.santiago@accenturefederal.com
- Please provide your name.
   > Tony Valdez
- Please Provide your email.
   > tony.valdez@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > My Education Benefits Team, Company - Accenture Federal Services

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcGg62En6eSxR/KB740leXH6HFc0zTsXjhYrRhO4W3qbQMTsC3ITWZB5x8NZ6XLGfMRPa+HCYKVkEBlINg7H1FXKYSSCYSzz+tNP4ZhU+oyEJQyA0It5xT7rigc0Vz7XWE3o3nF5b1a4rNJgLSGNA9UpBqI9QgdPdvs0AVTifnELKdM43eN6wFccDhKZi2eYEIxdtxNrxPK8WhGhSBP4U4s7eqbsoS6l9/9sD5JcTgC08cQUnPH0ZQXjHZVXSdyDnI/Me3rgTKO+zoCw+IrzHl04eKPshvkTQi4d9DJbkSTZr5Cbbqzr18ZcS9IAMFkUwpaauo89lw17LVR2/urUTfVqm3MMZj4hmkzXNpuQHstUPVtTeRSjy3GivPPZT3w5TGqJ9X8qhErLd/6ZEoKPF9/sRkxyvQqYKSAVAM2ojkEbzgCjCeSwdFO9cQFZR2fjbynPst8qPR4tw7cmwNJsWAPgHLx6RrjITMtCs+pEG/ilqibdM+d4d7DPsQmePt96M= tony.valdez@AFSMWTY9N4RF0PL
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
@tony-valdez-accenture, it appears you were granted SOCKS back on August 4: https://github.com/department-of-veterans-affairs/devops/pull/9713

Is this key an update? Did you perhaps lose access to the old SSH key? We can get you squared away either way, just wanted to see if there was some additional info we could track here.

**Comment by tony-valdez-accenture** [comment]
This is a SOCKS update. I have created new keys.

Thanks.

-Tony

From: Jeremy Britt ***@***.***>
Reply-To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Date: Tuesday, September 7, 2021 at 6:53 AM
To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Cc: "Valdez, Tony [Dynavet Solutions, LLC]" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Access for Tony Valdez (#29642)


This message is from an EXTERNAL SENDER - be CAUTIOUS of links and attachments. THINK BEFORE YOU CLICK.
________________________________


@tony-valdez-accenture<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftony-valdez-accenture&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cd2fd0b3b23a0469afde508d971fe865b%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666160260372470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=clSFgY15lbx12XgrF7h4vbvZNeSjMXzbEnHTDMErglA%3D&reserved=0>, it appears you were granted SOCKS back on August 4: department-of-veterans-affairs/devops#9713<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fdevops%2Fpull%2F9713&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cd2fd0b3b23a0469afde508d971fe865b%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666160260372470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U%2BEg%2BUaQtcG4DpH%2BVuQUOLmZWB%2FiNuEEBwlRmn28gfI%3D&reserved=0>

Is this key an update? Did you perhaps lose access to the old SSH key? We can get you squared away either way, just wanted to see if there was some additional info we could track here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F29642%23issuecomment-914281339&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cd2fd0b3b23a0469afde508d971fe865b%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666160260382463%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jf8Z3R1b39uJ81kOihzsCKUaWxADyoTs5wXJIRdSTpA%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU7ZQRPNAGKUIGS4WK4K523UAYDNPANCNFSM5DMM2GSQ&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cd2fd0b3b23a0469afde508d971fe865b%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666160260382463%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zIZ7d0nVs%2FH8cnJJI0YfASZ1jik%2FsNxwx3HVKtCqoOU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cd2fd0b3b23a0469afde508d971fe865b%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666160260392461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VMSR0N8YevIfQOo2woB78FrXjteNfK9ZjYv8uPC9aFI%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cd2fd0b3b23a0469afde508d971fe865b%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666160260402456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8SzARP0uP%2B2Fj45PYNX%2BICwoKpC1QIF4IBqZ3moMv%2Fw%3D&reserved=0>.

**Comment by jbritt1** [comment]
Roger that @tony-valdez-accenture, I will get your key updated shortly.

**Comment by jbritt1** [comment]
Update going out now @tony-valdez-accenture, changes should be live in about 5-10 minutes. Please reopen the ticket or comment here if any issues are observed.

**Comment by tony-valdez-accenture** [comment]
I am getting the following error when starting socks…

Please advise.

Thanks.

-Tony

***@***.***

From: Jeremy Britt ***@***.***>
Date: Tuesday, September 7, 2021 at 8:20 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Valdez, Tony [Dynavet Solutions, LLC] ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Access for Tony Valdez (#29642)

This message is from an EXTERNAL SENDER - be CAUTIOUS of links and attachments. THINK BEFORE YOU CLICK.
________________________________


Update going out now @tony-valdez-accenture<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftony-valdez-accenture&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227425191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rqr2kAtoySR3Qk1m3TwesBhgstcvycwd9xF64RfmG5c%3D&reserved=0>, changes should be live in about 5-10 minutes. Please reopen the ticket or comment here if any issues are observed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F29642%23issuecomment-914347576&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227425191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P%2BcvuqgCj3XvdDV3%2Fdkdl5MQ0%2F%2F1tncnqscGox2jK0c%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU7ZQRM3QR5YM2IKRNHNONDUAYNSJANCNFSM5DMM2GSQ&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227435181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bz757TngQKoqNuXJufEPow03Pg66NwSOxi0BQA3Y%2BPk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227435181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AEy9VgnAQlNuucgAckjrOaEjz5LYTc5cfeQeYxJS3ys%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227445182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GKB8FDzW4jR6CowmAv66wdx0V1tqMtHRZny8tjyMlQk%3D&reserved=0>.

**Comment by jbritt1** [comment]
> I am getting the following error when starting socks… Please advise. Thanks.
> […](#)
> -Tony ***@***.*** From: Jeremy Britt ***@***.***> Date: Tuesday, September 7, 2021 at 8:20 AM To: department-of-veterans-affairs/va.gov-team ***@***.***> Cc: Valdez, Tony [Dynavet Solutions, LLC] ***@***.***>, Mention ***@***.***> Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Access for Tony Valdez (#29642) This message is from an EXTERNAL SENDER - be CAUTIOUS of links and attachments. THINK BEFORE YOU CLICK.
> ________________________________ Update going out now @tony-valdez-accenture<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftony-valdez-accenture&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227425191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rqr2kAtoySR3Qk1m3TwesBhgstcvycwd9xF64RfmG5c%3D&reserved=0>, changes should be live in about 5-10 minutes. Please reopen the ticket or comment here if any issues are observed. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F29642%23issuecomment-914347576&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227425191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P%2BcvuqgCj3XvdDV3%2Fdkdl5MQ0%2F%2F1tncnqscGox2jK0c%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU7ZQRM3QR5YM2IKRNHNONDUAYNSJANCNFSM5DMM2GSQ&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227435181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bz757TngQKoqNuXJufEPow03Pg66NwSOxi0BQA3Y%2BPk%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227435181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AEy9VgnAQlNuucgAckjrOaEjz5LYTc5cfeQeYxJS3ys%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctony.valdez%40accenturefederal.com%7Cdb80d91cdf964199b0e408d9720aa034%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637666212227445182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GKB8FDzW4jR6CowmAv66wdx0V1tqMtHRZny8tjyMlQk%3D&reserved=0>.

Reach out in #vfs-platform-support on the DSVA Slack workspace
