### ISSUE TITLE
Disable "unfurl URL" on Slack removal request bot

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#29658]
The Github issue links sent by https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/slackRemovalRequest.yml are being unfurled (there is a preview shown) which creates too much clutter in the channel.

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29659 created in lieu of this issue. Closing.
