### ISSUE TITLE
Spike: How to set ECHECKIN STARTED for multiple appointments

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#29656]
What does VSE GUI display? Will it be confusing for the staff if we set E-CHECKIN-STARTED for every appointment that day?

**Comment by kjduensing** [comment]
Remember to bring this up in the Tiger Team meeting 9/13. @wamccarty @calquisola @kjduensing

**Comment by kjduensing** [comment]
Last landed on setting e-checkin-started for all appointments.

**Comment by aschulhof** [comment]
Closed as duplicate to https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/52
