### ISSUE TITLE
Investigate form 526 Submission errors - Error calling external service 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#29651]
we learned in this[ veteran support ticket ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/318) that at least one reason that veterans see this error message is they have an incorrect birls id.  In this case, the BIRLS id and SSN were one digit different.  

form526.submit.establishClaim.serviceError: Error calling external service to establish the claim during Submit

Review `Form526JobStatus` data and see if this may provide a fix for more veterans.

**Comment by annaswims** [comment]
js = Form526JobStatus.where.not(status: "success").where(updated_at:[1.year.ago..Time.now]).where("error_message like '%Error calling external service to establish the claim during Submit%'")

js.collect do |j|
  dd = j.form526_submission.auth_headers
  [dd["va_eauth_dodedipnid"], dd["va_eauth_birlsfilenumber"], dd["va_eauth_pnid"], dd["va_eauth_birlsfilenumber"].to_i - dd["va_eauth_pnid"].to_i  ]
end

**Comment by annaswims** [comment]
Found 10 people that have similar but not exact SSN and BIRLS id's. will pass on their info to IAM.

**Comment by annaswims** [comment]
I passed on to @joeniquette a list of 277 veterans who have been blocked from submitting a form 526 submission in the last year and had similar but not matching SSN's and BIRLS ids. I can't say with certainty that this is the one and only cause of their problems but it seems highly likely that it will help.

**Comment by annaswims** [comment]
once https://github.com/department-of-veterans-affairs/vets-api/pull/7989 is merged we shoudl be able to run `rake form526:birls_errors`. @Kimberley2019 and @joeniquette have a contact who can fix these issues manually.

**Comment by joeniquette** [comment]
work is submitted to proper team for completion.
