### ISSUE TITLE
CHIP - set start and end times to make sure they are valid

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#29655]
Because multiple appointments can span an entire day, CHIP must set the valid start and valid end times  in LoROTA appropriately so that patients can access appointments all day.

**Comment by kjduensing** [comment]
Do dynamic time calc

**Comment by aschulhof** [comment]
duplicate of https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/21
