### ISSUE TITLE
Remove dashboard page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2965]
As a veteran, I want to click as few buttons as possible to start making a new appointment and to view my existing appointments.

## AC:
- [ ] Current dashboard page does not exist in the app.
- [ ] staging.va.gov/vaos goes to the appointment list.
- [ ] 'schedule an appointment' button is updated per mocks below.

**Comment by markgreenburg** [comment]
@rtwell please let me know if this ticket is accurate and let's move to dev if so.

**Comment by rtwell** [comment]
aight, so to dodge the stupid million API call problem, we could shift to this approach. cc @goldenmeanie @lalexanderson-dsva @jbalboni @narin 

## on page load, the top banner is there before API call madness

![image](https://user-images.githubusercontent.com/12564977/67981431-091e8600-fbf7-11e9-84b7-d9a8af873e4e.png)

## then, if there are appts for this user, the cards load below it:

![image](https://user-images.githubusercontent.com/12564977/67981581-5ac71080-fbf7-11e9-8526-4c0c071a4229.png)

**Comment by jbalboni** [comment]
That seems fine, it's pretty similar to the landing page for claim status, which has to fetch claims and appeals, and the claims api is very slow.
