### ISSUE TITLE
Adding Matthew Gardner to DSVA Slack

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#29665]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member

- What channel(s) do they need to be added to? 
- 
- Appeals, Appeals-Announcements, Appeals-Wisdom-Wednesday (we will add more, but at this time just starting with these 3).

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Matthew is a new Engineer starting on Caseflow today 9/7/21.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add mattgardner@navapbc.com as a full member with (to start) access to these channels: Appeals, Appeals-Announcements, Appeals-Wisdom-Wednesday.

**Comment by LEHigley** [comment]
done
