### ISSUE TITLE
SPIKE: Pre-registration/Demographics/VA Profile

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#29668]

**Comment by kjduensing** [comment]
Remember to bring up at Tiger Team 9/13, @wamccarty @calquisola @kjduensing

**Comment by shanemelliott** [comment]
@Durkin, Robert M. per our conversation yesterday, below you will find the link to the different VA Profile Swaggers.  At the bottom of the SharePoint page, you find v2.0:
https://dvagov.sharepoint.com/sites/OITEPMOEPMDES/Projects/Vet360/OnBoarding%20with%20Vet360/Home.aspx

Let me know if you need anything else from my end.

Thanks,
Paras

Paras C. Shah, MHA
Office of the VA CTO (OCTO)
Advisor, VA Digital Notifications (VANotify and VEText)
(e) paras.shah3@va.gov
(o) 703.386.7822

**Comment by shanemelliott** [comment]
https://dev.vaprofile.va.gov:7005/profile-service/swagger-ui/index.html?configUrl=/profile-service/v3/api-docs/swagger-config&urls.primaryName=Profile-v2

**Comment by shanemelliott** [comment]
https://dsva.slack.com/archives/C022AC2STBM/p1631635848277000?thread_ts=1628879449.231200&cid=C022AC2STBM

**Comment by pcshah1026** [comment]
plan is to use VEText's existing integration -- use VEText cert for authorization

**Comment by pcshah1026** [comment]
**3 paths to pull demographics, etc.:**

VA Profile (via VEText)
Lighthouse
via VETS API

**Comment by pcshah1026** [comment]
Shane confirmed with Patrick that its read-only demographic.  Veterans need to only verify demographics once -- multiple appts in one day.

**Comment by shanemelliott** [comment]
Can we modify Date Updated.

**Comment by pcshah1026** [comment]
@pcshah1026  follow-up on whether data updated in VistA is updated in real-time with VA profile.

**Comment by shanemelliott** [comment]
`{
    "txAuditId": "8858af54-36ae-4c23-b15a-efb57d059747",
    "status": "COMPLETED_SUCCESS",
    "bios": [
        {
            "telephoneId": "183317258",
            "phoneType": "HOME",
            "phoneNumber": "5551212",
            "areaCode": "909",
            "textMessagePermInd": false,
            "internationalIndicator": false,
            "countryCode": "1",
            "sourceSystem": "VHAES",
            "sourceDate": "2009-05-07T13:31:57Z",
            "originatingSourceSystem": "VAMC",
            "sourceSystemUser": "VAMC-605",
            "textMessageCapableInd": false,
            "voiceMailAcceptableInd": false,
            "ttyInd": false,
            "createDate": "2018-05-14T23:57:35Z",
            "updateDate": "2018-05-14T23:57:35Z",
            "effectiveStartDate": "2009-07-10T12:02:49Z",
            "vet360Id": "21433808",
            "txAuditId": "DATA SEEDING"
        }
    ]
}`

**Comment by shanemelliott** [comment]
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/56733793-9263-4fb0-ae95-b658d5464c71)

**Comment by shanemelliott** [comment]
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/cef73648-6bde-4b5a-ab53-21efcc4c8ab8)

**Comment by shanemelliott** [comment]
Successful test VA.gov => Profile
`{
    "txAuditId": "ca7f0261-772f-408c-8428-8921a9d48470",
    "status": "COMPLETED_SUCCESS",
    "bios": [
        {
            "telephoneId": "183317258",
            "phoneType": "HOME",
            "phoneNumber": "8675309",
            "areaCode": "909",
            "internationalIndicator": false,
            "countryCode": "1",
            "sourceSystem": "VETSGOV",
            "sourceDate": "2021-09-20T23:10:05Z",
            "originatingSourceSystem": "VETSGOV",
            "sourceSystemUser": "1011568236V299349",
            "createDate": "2018-05-14T23:57:35Z",
            "updateDate": "2021-09-20T23:10:05Z",
            "effectiveStartDate": "2021-09-20T23:10:05Z",
            "vet360Id": "21433808",
            "txAuditId": "264000d6-23f0-4eb0-9f17-23d225aa5b63"
        }
    ]
}`

**Comment by shanemelliott** [comment]
VistA RPC for Get Demopgraphics.
`{
  "context" : "SDECRPC",
  "rpc" : "SDEC GETREGA",
  "jsonResult" : "false",
  "parameters" : ["237"]
 
}`

**Comment by shanemelliott** [comment]
`var jsonData = JSON.parse(responseBody);
var resp = jsonData.payload
var respArr = resp.split(String.fromCharCode(30));
var header = respArr[0].split("^");
var data = respArr[1].split("^");
header = header.map(element=>element.substr(6))
var object = {}
header.forEach(function(k,i){
  object[k]=data[i]
})
console.log(object)`

**Comment by shanemelliott** [comment]
Final Decision is to use VistA for now.

**Comment by shanemelliott** [comment]
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/d32a5152-558d-4b9e-b0f7-c65df5c87017)

**Comment by shanemelliott** [comment]
PRe-Registration Log:
https://vivian.worldvista.org/dox/Global_XkRHUyg0MS40MQ==.html

write to log:
https://vivian.worldvista.org/dox/Routine_DGPREP1_source.html

**Comment by shanemelliott** [comment]
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/23d2697e-5d93-448f-9920-20c5531f135c)

**Comment by shanemelliott** [comment]
PreReg RPC:

https://vivian.worldvista.org/vivian-data/8994/8994-3249.html
