### ISSUE TITLE
Offboarding of Tim Radle

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/va.gov-team#29661]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Tim Radle
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VANotify
   > company: thoughtworks
   > last day: 8/31/2021
- Please provide any type of access they may have and their GitHub username. 
  > Google Analytics, Slack
  
 
## AC
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @drorva, @mchelen-gov

**Comment by jennaouellet** [comment]
User does not have GA or Domo access

**Comment by mleclerc00** [comment]
No socks
No aws
Couldn't find tradle51 as part of the Org
https://github.com/department-of-veterans-affairs/github-user-requests/issues/6218
No pagerduty
No Datadog
No Sentry

**Comment by ffafara-tw** [comment]
I can still see Tim still in Slack.
I found the GH action that messaged #vsp-slack-user-management on slack: 
https://github.com/department-of-veterans-affairs/va.gov-team/runs/3536604133?check_suite_focus=true

Not sure if admins just haven't gotten to it yet or sth failed somewhere.

**Comment by mleclerc00** [comment]
They probably havent gotten to it yet since I just made the request yesterday
