### ISSUE TITLE
HLR Form Refresh Testing

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29674]
## Issue Description
HLR form refresh testing

---
## Tasks
- [ ] Test frontend with backend in preparation for collab cycle kickoff. Related to this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28112). 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by Mottie** [comment]
Successful test in staging.
