### ISSUE TITLE
Add Natural Disaster Messaging to Debt landing page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#29679]
# Public Websites Banner Intake Request Form

## Description

DMC Has Requested a natural disaster message be added to debt landing page 

![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/ae4ed677-5713-4e79-bc06-34439de03257)## What do you need?

URL: https://www.va.gov/manage-va-debt/

Timing: ASAP 

## Stakeholders

@leahkeeler Jill Anderson

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I reworked the alert into plain language. Let me know what you think: [https://app.zenhub.com/files/133843125/96aaa03c-eed2-4eff-9612-33e64c8edc45/download](https://app.zenhub.com/files/133843125/96aaa03c-eed2-4eff-9612-33e64c8edc45/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. We can add an alert to this page. But this far too much content for an alert and much of it is already on the page. I'm working on a simpler, plain language alert and will share with you when ready. Thanks.

**Comment by leahkeeler** [comment]
@DanielleThierryUSDSVA I thought as much - I will let DMC know that you are rewriting and it will be up when completed. Thanks for your help - Leah

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht, could you take a look at the alert at http://preview-prod.vfs.va.gov/preview?nodeId=6521 and do a copy edit/numbers check?

@leahkeeler Let me know if you'd like us to go ahead and publish this. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @leahkeeler! I'm looking at this again and I'm thinking we should make it an expand/collapse alert. This will help us avoid pushing the sign-in component down as far on the page. I'll make that change now. cc @RLHecht

**Comment by DanielleThierryUSDSVA** [comment]
Okay, alert updated in this preview: http://preview-prod.vfs.va.gov/preview?nodeId=6521 @leahkeeler @RLHecht

**Comment by RLHecht** [comment]
I reviewed this and made a few copy tweaks. @leahkeeler Let me know when this is good to publish.

**Comment by RLHecht** [comment]
The alert has been published. Moving this to validate and will close once it's live.

**Comment by RLHecht** [comment]
This alert is now live. Closing ticket. FYSA @leahkeeler
