### ISSUE TITLE
Support POSTing to `/appointments` endpoint

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2968]
As a developer, I want to allow POSTing to `appointments` so that the VAOS front end can support direct scheduling mental health and primary care appointments.
AC:
- [ ] Mock data from staging vaos services recorded to cassette (not sure if possible)
- [ ] `appointments` endpoint supports `POST` method with staging data
- [ ] Tests, specs, and Swagger exist in vets-api

**Comment by saneshark** [comment]
I've gone ahead and done some of the boiler plate for this in a draft PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/3756/files

But could use a bit of a guidance on what a successful POST in legacy gets sent, and what it receives back. Is the POST request basically similar to cancel or is there additional data that can be added? Do we know what is required / optional based on validations in varWeb?
