### ISSUE TITLE
Develop helpers for Cypress-TestRail Reporter

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#29691]
Develop tools for facilitating cypress-testrail-reporter usage.  Make it easier to:

- Gather TestRail variables
- Save TestRail variables
- Run the Cypress spec(s)

None of the team's Front-End Engineers have implemented cypress-testrail-reporter runs.  This may well be due to the current process' tediousness and lack of custom-tooling.

**Comment by tlei123** [comment]
Added a Custom UI script to TestRail to display a Test Case's Group, Suite, & Project IDs.  This should make it much easier to gather many of the required TestRail variables.

**Comment by tlei123** [comment]
Now trying do develop a Node-CLI app in vets-website to save all TestRail variables.  This should eliminate the need to export the variables as environment-variables, except for Username & API Key.

**Comment by tlei123** [comment]
The **current** process doesn't seem to be working!  Need to do some troubleshooting.

**Comment by tlei123** [comment]
Crap!  It looks like cypress-testrail-reporter 1.3.2's got an error with a dependency deasync (introduced in 1.2.4).

The current process worked after rolling-back to 1.2.3 in my feature-branch.

@pjhill @ddzz , should I open a PR in a separate branch to roll cypress-testrail-reporter back to 1.2.3?

**Comment by tlei123** [comment]
Per Darius, 1.3.2 upgrade was required for security reasons.  Not sure how to proceed from here.

Will wait for his further findings in #28390.

**Comment by ddzz** [comment]
@tlei123 @pjhill I'm not sure how `cypress-testrail-reporter` is being used right now. Does this still need to be addressed, or are we fine with the errors? If a fix is needed I'll need a failing scenario that I can recreate.

**Comment by pjhill** [comment]
> @tlei123 @pjhill I'm not sure how `cypress-testrail-reporter` is being used right now. Does this still need to be addressed, or are we fine with the errors? If a fix is needed I'll need a failing scenario that I can recreate.

It's fairly rarely used AFAIK. Tze is attempting to fix that by making some enhancements to it that make it easier to use. In order to test it out this [document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1738047581/Cypress+to+TestRail+Reporter+Plugin+Configuration) is still up-to-date.

**Comment by tlei123** [comment]
@ddzz , to test the current process, you can run VSA Healthcare Experience team's Check-In (CI) [test-cases-group 1373](https://dsvavsp.testrail.io/index.php?/suites/view/35&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1373) -- in the left-panel's list, next to **C5684**, click the green **Info** button to display the Case's Group, Suite, & Project IDs.

For your script-call's `--spec` override, the corresponding spec-file path is `src/applications/check-in/tests/e2e/phase-1-pre-mvp/back-button/back.button.check.in.cypress.spec.js`

**Comment by tlei123** [comment]
^ PR merged!  Thx much, @ddzz !

cc @pjhill

**Comment by tlei123** [comment]
With Darius' cypress-testrail-reporter fix, my WIP Node-CLI helper-app's working fine.

So far, the helper-app's successfully prompting and saving all TestRail variables, elminating the need to export them as environment variables.

Next step is to exec/spawn a child process to actually trigger the Cypress run.

**Comment by tlei123** [comment]
Child-process exec code added.  Now cypress-testrail-helper (CTH) app automatically runs the Cypress spec after gathering user-inputs for TestRail-info and spec-path.

Will need help testing this to determine whether machine-specific NVM/Node paths might impact the child-process code.

**Comment by tlei123** [comment]
cy-tr-helper merged.
