### ISSUE TITLE
Document mega menu config 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#297]
Problem
- mega menu behavior is not clear from the source code 
- mega menu content requires dev intervention to update 

Goal 
- provide enough context on how the mega menu / header content is loaded by the build process to support CMS effort to move content management of mega menu into drupal 

Tasks 
- Document how the mega menu content is populated
- Document how the build processes uses the mega menu config

**Comment by accbjt** [comment]
@rianfowler Should this be a separate document from the gatsby doc? Specifically for vets-website and how it is configured in there.

**Comment by rianfowler** [comment]
@accbjt I think that works- it could be a readme in here: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/site-wide/mega-menu
