### ISSUE TITLE
Adding Justin Bosse to DSVA Slack

### ISSUE THREAD

**Issue by nsmith1982** [department-of-veterans-affairs/va.gov-team#29703]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Good morning,

Please add Justin Bosse (jbosse@clarityinnovates.com) as a Full Member of DSVA Slack.  Justin is a new SRE starting on the CEDAR TEVI contract.  Please give Justin access to the following channels:

# vfs-all-teams
# vfs-platform-support
# vsp-service-design

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
