### ISSUE TITLE
[Discovery] Find a VA Form: Add new PDF alert to each link on Detail pages

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29707]
## Issue Description
Discovery issue to determine how to display a modal widget in a detail page

**Comment by zacharymorel** [comment]
**NOTE TO SELF**: 
_Modal_ => https://design.va.gov/storybook/?path=/docs/components-modal--default

_Creating a widget to be used on a static page_ => https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/static-pages-entry.js#L151

_Widget Constants_ => https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/widgetTypes.js#L24

_Container on content repo_ => https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/va_form.drupal.liquid#L158

**Comment by MarciMcGuireGCIO** [comment]
Strong work @zacharymorel, as always!! 👏
