### ISSUE TITLE
Access for Jennica Stiehl

### ISSUE THREAD

**Issue by stiehlrod** [department-of-veterans-affairs/va.gov-team#29711]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Cecilia Lee
- Please provide your name.
   > Jennica Stiehl
- Please Provide your email.
   > jennica.stiehl@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Koala on Lighthouse, Software Developer, Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0FGTM1a8z0my0hFbtesZoW/m2g0JIYsXHCGB7kQXSvDqiFE0D01KMEr1G+R2I+jPix3ZjLgiMp+0FLuCc29qVPYQyY4h9ran7fYJU+61Mah4mbROI8iGX7nBl6MwZ6jAoiDukef+Cd+/ZzGAaZ3+BTT1MiD6dgsCeSLwnI4AGI5aYR19z0qRxPMnE1T4kH73MX0uBqsLbK/K2pitePSzGIuaVLRiPbrAck9wP28fyodMHxikvsF/fP/wkViP5q4QClDEqbk83r/+LbHI4UlgrnzfevIiWfvs2yHS1pDqTyLMjEbYjcvA6Map9OdfnwiGtRVFe94ekOyNXwsz1amZCFquC3MM/sDAUIrvMAKu2deasktWu5d0ab/+0oZJpNwDBGqEuO1PvcrIv9WwynN7FtleEMpqJ99q0FulnQsMUS6DyBvi+TfJtOAT9mUBBDW7ln9QFokrhHSUpLOY+jlZ6ADMQh7/z4Wb/LQZeZohpWh8eJfz2Xkzar5Rc78lnFCc= jennicastiehl@Jennicas-MBP.hsd1.co.comcast.net


```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
lighthouse developers IAM

**Comment by mleclerc00** [comment]
For AWS Access:
User: Jennica Stiehl
COR: Cecilia Lee
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @stiehlrod 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by stiehlrod** [comment]
Matt,
Socks is set up on my machine and I can access the Garfana login page.
Thank you,
Jennica

**Comment by stiehlrod** [comment]
@jbritt1  and @mleclerc00 ,
I am curious why this is still waiting approval and who needs to approve it? In addition, I edited the token since I have a new laptop. Thanks so much!

**Comment by jhouse-solvd** [comment]
@stiehlrod - Hi Jessica! Product Manager for the Ops team here. 

In the case of AWS access, there is an approval process involving contacting your organization's Contract Officer Representative (COR) to ensure that necessary paperwork (EQIP) has been submitted and is in process. 

Also, when you mentioned that you "edited the token", are you possibly referring to the SSH Key? Are you still able to access Grafana? _If not, it's possible that the new SSH Key will need to be re-applied..._

**Comment by stiehlrod** [comment]
@jhouse-solvd - Jesse, Who needs to contact my COR? My eQIP has been completed.

Since my ticket is waiting approval, I edited my ticket to include the token generated by my new laptop. When you say 'does the SSH key need to be re-applied', who would re-apply it?

Basically, I am trying to understand what I need to do, if anything?

Thank you,
Jennica

**Comment by mleclerc00** [comment]
Hi @stiehlrod , I apologize for missing this message.  Usually pretty good about these things but this one slipped past.  If you do end up in this scenario again, feel free to to drop a /support request in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

Going to ping @mchelen-gov here again for the AWS access.

**Comment by stiehlrod** [comment]
Thank you Matt! :)

**Comment by mchelen-gov** [comment]
@mleclerc00 EQIP transmission date confirmed, request approved.

**Comment by mleclerc00** [comment]
AWS account information has been passed along to Jennica.  Closing this ticket.
