### ISSUE TITLE
Change VA.gov VPCs to use TGW (Transit Gateway)

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2971]
VAEC now has access to AWS' Transit Gateway and is switching projects over to it. This'll give us more reliable and lower latency access to other services in AWS, along with a few VAEC features.

The ordering is roughly:
- create a new TGW attachment
- give VAEC team TGW Attachment ID and the Name and ConnectionID tags
- once VAEC team tells us we are good to go, we disable route propagation from the VGW, remove any manual routes, simultaneously add new routes to the TGW, and then disconnect VGW from the VPC (Traffic will be interrupted for ~30 seconds while BGP reconverges.)
- Traffic will be interrupted for ~30 seconds while BGP reconverges.

They have some instructions here: https://github.ec.va.gov/AWS/vaec-network/blob/master/tgw/plan/cutover-spoke-vpc-vgw-tgw.md

**Comment by wyattwalter** [comment]
PR is set, I believe, for the first phase. Once we get that created I can reach back out to COMS/VAEC folks.

**Comment by wyattwalter** [comment]
Attachments are created, doing some back-and-forth with COMS to make sure we're all setup for a cutover.

**Comment by wyattwalter** [comment]
We're now cutover and routing traffic through the TGW. Cleanup tasks that need to be finished before closing:

- [ ] Change route53 endpoints to point at VAEC DNS across the board (sounds like dev and prod already do this)
- [ ] ticket exploring reducing route tables to 1 for each environment
- [ ] remove old VGW’s
- [ ] remove VPC peering with transit gateway VPC and cleanup any extra routes that may exist

**Comment by wyattwalter** [comment]
Ticket for route table cleanup: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3674

**Comment by wyattwalter** [comment]
Old VGW's are gone, I believe everything is torn down at this point. The customer gateways were left up as Appeals still uses them and they were shared between projects.
