### ISSUE TITLE
Build /community-care/supported-sites GET endpoint

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2972]
## Story
As a backend developer, I want to be able to call a service to get a list of veterans' sites that support CC scheduling, so that the front end can check whether a veteran should see the community care option and whether they need to choose between multiple CC-enabled sites.

## AC
- [ ] Staging data recorded to cassettes
- [ ] `/community-care/supported-sites` `GET` endpoints exist in vets-api
- [ ] Tests, specs, and swaggers exists for both endpoints

**Comment by sjbrush** [comment]
I am trying to figure out how this functionality works in current vaos.  if someone knows what that actual service call is and could post it here, that would be great.

**Comment by sjbrush** [comment]
"/facility-service/supported-facilities/#{siteCodes}"  this is handled by var-resources.  Apparently a VAR supported facility is a CC supported facility.  in other words, if they are able to use VAR, they are able to use CC assuming the user is eligible.

**Comment by sjbrush** [comment]
For the call to https://veteran.apps-staging.va.gov/var/VeteranAppointmentRequestService/v4/rest/facility-service/supported-facilities?siteCodes=983%2C984&_=1576697126602 I got:

    {
    "sitesSupportingVAR" : [ {
      "id" : "983",
      "name" : "CHYSHR-Cheyenne VA Medical Center",
      "timezone" : "US/EST",
      "objectType" : "SiteSupportingVAR",
      "link" : [ ]
      } ]
    }
