### ISSUE TITLE
Claim Status Tool Messaging - Phase II

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29736]
## Issue Description
Continue work to understand statuses and events within the CST.

---
## Tasks
- [x] [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29084) Work with backend to document all event statuses in CST

## Acceptance Criteria
- [x] Events documented in GitHub.
---

**Comment by kevinstachura** [comment]
All statuses and events have been documented on this Mural board:

https://app.mural.co/t/vsa8243/m/vsa8243/1631731095728/a545d8695af30185db129969ec7c48b9055b37a3?sender=kstachura1551
