### ISSUE TITLE
Bug - Letters Address

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29730]
## Issue Description
Reported by Mobile app team. Letter displaying home address instead of mailing address. This [ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1375#issuecomment-902798174) outlines issue. 

![image.png](https://images.zenhubusercontent.com/5ffca1cc8ef760e3db881927/e8e1b196-674d-4477-9cde-1d371ddf8ea2)

---
## Tasks
- [x] Determine if tool is working correctly as-is or if it should display mailing address (instead of home address) on letter. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by Mottie** [comment]
We were planning on switching to show the "Home address" on the front-end to quickly resolve this, but it bears further investigation since the back-end does use the "Mailing address".

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1375#issuecomment-915474330

**Comment by vhenry07** [comment]
Closing ticket as issue was reported to the appropriate team.
