### ISSUE TITLE
[FE] Profile: Stop stripping address line 2 and line 3

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#29744]
https://user-images.githubusercontent.com/20728956/132557040-1db25caa-57de-4272-8236-97efa2d420f1.mp4

Supporting text, like "care of..." lines, are removed from user-entered addresses.

This is because the address validation layer all addresses goes through strips the supporting text. In the case above, we get a single confirmed suggestion with a confidence score of 100% from the validation layer, and that's what is actually saved by VA Profile.

To get around this, we'd need to force address validation in cases where a user has entered info on line 2 or line 3.

Is this worth doing? I think it is. If my disabled-Veteran-father-in-law is living with me but the mailman thinks only "Hansen" is at my address, my father-in-law's medication might not get delivered. But if "care of Erik Hansen" was printed on the mail, it would likely be delivered.

**Comment by erikphansen** [comment]
I can think of a few ways around this:
1. Always show the address validation screen which would allow the user to always override the suggestion. This is a bad idea  since it would annoy almost all Veterans who enter an address, but I wanted to raise it as a possibility.
2. Always show the address validation screen _if_ the user entered text in line 2 or line 3. Would be annoying to those who entered a valid unit number on line 2.
3. Show the address validation screen _if_ the one confirmed, high-confidence suggestion did not contain the text entered on line 2. This might alleviate some of the annoyance that'd come from approach 2.

**Comment by erikphansen** [comment]
@ajakabcin this can be validated on staging. Enter an address with info in line 2 and/or line 3 and you will then have the option to pick the address you entered on the validation screen.

**Comment by ajakabcin** [comment]
confirmed - looks great, thanks @erikphansen !
