### ISSUE TITLE
Publish deployment docs and deprecate originals

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#29769]
## Narrative
We will need to migrate the Deployment documents inside of the TEMP section to the [Frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) section of the new documentation site.

Info about this process can be found in the [Content migration guidelines](https://vfs.atlassian.net/wiki/spaces/AP/pages/1375666200/Content+migration+guidelines).

We also need to deprecate the original deployment docs, which can be found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1vDQlI_lk9GTQuqw4eMmDe8CAHvNjVmjW3CGRDp0I9iU/edit?usp=sharing).

[This page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1397194753/Deprecate+a+page+in+GitHub) contains instructions on deprecating pages in Github.

**Comment by timwright12** [comment]
closing out as this work is complete
