### ISSUE TITLE
Letters Timezone Issue

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29762]
## Issue Description
[(Jayson Perkins Slack thread)](https://dsva.slack.com/archives/C5AGLBNRK/p1631116531093900)We noticed an issue in our app for the benefit summary letter where the date a user would see when deciding what the letter should display would be one day off from what actually shows up in the letter. After some debugging this seems to be an issue where the timezone of the user doesn't match the timezone of the server generating the letter. We also checked va.gov and noticed the same issue, so I'm reaching out to see if you all are aware of this issue and what your thoughts on it are before we considering trying to fix it on our end.

---
## Tasks
- [ ] Investigate issue and resolve.

## Acceptance Criteria
- [ ] Timezone issue resolved
---

**Comment by annaswims** [comment]
EVSS generates the letter and they use central time. Vets-api uses UTC.

**Comment by annaswims** [comment]
the api response from https://staging-api.va.gov/v0/letters/beneficiary is:
````
{
    "data": {
        "attributes": {
            "benefitInformation": {
                "awardEffectiveDate": "2017-12-01T06:00:00.000+00:00",
                "hasAdaptedHousing": false,
                "hasChapter35Eligibility": true,
                "hasIndividualUnemployabilityGranted": false,
                "hasNonServiceConnectedPension": false,
                "hasServiceConnectedDisabilities": true,
                "hasSpecialMonthlyCompensation": true,
                "monthlyAwardAmount": 3261.1,
                "serviceConnectedPercentage": 100
            },
            "militaryService": [
                {
                    "branch": "Army",
                    "characterOfService": "HONORABLE",
                    "enteredDate": "1965-01-01T06:00:00.000+00:00",
                    "releasedDate": "1972-10-01T05:00:00.000+00:00"
                }
            ]
        },
        "id": "",
        "type": "evss_letters_beneficiary_responses"
    }
````

**Comment by michelpmcdonald** [comment]
This sounds like something the vets-api might be able to help with, but I'm unsure, just some notes:

This looks like a date mismatch between the date that is on the PDF letter and the date we show in the GUI, investigate what the letters GUI looks like, do we display the "awardEffectiveDate" field from the json Anna posted above.  Where do we get this date ?(perhaps from EVSS ?, or is the date from one of vets-api own models-tables ?)

If we do display the awardEffectiveDate on the letters GUI, is that the date that is incorrect ?  If it is, could we simply take the  awardEffectiveDate json, parse it as a date, convert it to central time, and then put the converted date back in the json we provide to the front end ?  I'm somewhat doubtful that I understand the problem and it's that easy to correct, I think if it were Anna might have mentioned that as a possible solution....but it's worth investigating.

**Comment by Mottie** [comment]
I believe the problem is that we're getting an ISO 8601 formatted date with a time offset, but no timezone offset. I've created a fix that strips off the time component and when our time library parses it, the date doesn't change.
