### ISSUE TITLE
AWS Staging:  Ruben Moreno Requests Not Displaying

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#29763]
I need someone to look into this and let me know if this is a backend issue.  This is ONLY happening on Ruben Moreno.  

This only is happening with Ruben Moreno.  I tried three other patients and none of them have this error.  
Log in and select Requested Queue.  Expected Response: request display.  Actual response Alert displays we're sorry.  We've run into a problem.
Select other queues and no issue.  all other queues are working.

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/fc1648f4-e4e0-451e-8dab-771cd33e1bbc)

**Comment by laurenernest** [comment]
@marcynadeau are we good to take a look at this now or are you still seeing the flakiness?

**Comment by ajmagdub** [comment]
The requested appointment list is now showing up for Ruben Moreno. Closing ticket as this is now resolved.
