### ISSUE TITLE
Add two new columns to the TestRail cases and tests tables in BigQuery. Clean up TestRail metrics table.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#29768]
Add `custom_automation_status` and `custom_device_platform` to the BigQuery `testrail_tests` and `testrail_cases` tables.

Clean up the data in the `testrail_metrics` table which is causing issues in DOMO.

**Comment by holdenhinkle** [comment]
PRs:
- https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/67
- https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/68

**Comment by pjhill** [comment]
This was the result of a support request to add some custom fields to a specific project in TestRail. Thanks for knocking this out!
