### ISSUE TITLE
Access for Branden Bartlett

### ISSUE THREAD

**Issue by bbartlett26** [department-of-veterans-affairs/va.gov-team#29766]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Laura Ross
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Janet Doe
- Please provide your name.
   > Jane Doe
- Please Provide your email.
   > branden.bartlett@accenturefederal.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > My Education Benefits Team: Full-stack Developer: Accenture Federal Services

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDO7TzRsJ6/nlwjEeom62JCO+/dt6mZ3qZikI76sdr0bshWPUk8AOKEvelM8Y1FkQYDNyDyF8Y7TdgBNDFbX2EiIDNS09ZQPRgEJQht3y8dscuUYKKpB1PR1VWI2OF3I4Yp3JbVLvNzj19izZNjbgkVFyap3BsDwifC4eKsJld6x8wfVkXeqgVe+qPz5ZjlY8JgQ1IhPJOGKgUsQVZZNFfa2DnBdsJOP1dtLiHGzQoEpqU3usrmu64UVsiFLCnO73piFGVgMNtN7Uf5972Mvrt7NwRXBgsLF2ocbr0vvM6LNe5q9ofcvDr7rRxW56Yd6s/DCCVJvKi2Azw5Sbeg9E08zPEUzJ5UBsv5ANyK/1QoJKGrjBxEVHTGimr2s4hYisExSrqJKDWEe1opk8yzUy2M0uO2pv88A23fdj6Y+zPvuDhp22Km80TU5p5dSqjQLqjNEuk8tm8kRLSKXblEd89s145TIwXbcJBL1arVNdBKy7vZ5xViVNu0IO+kTQ8as48= branden.bartlett@AFSMW3ZWTMVQN1B+ branden.bartlett@accenturefederal.com
```

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why?

**Comment by mleclerc00** [comment]
Hi @bbartlett26 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
