### ISSUE TITLE
Non-reusable alert content blocks do not render unless there is a heading

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29771]
## Issue Description
(reported and verified by Jane)
On a VAMC Detail Page, the  Non-reusable Alert content block doesn't show when published on Veteran-facing site if the Alert Heading field is empty.

According to the design system, this component cannot be used without a headline. 
- [Alert boxes](https://design.va.gov/components/alertboxes)
- [Background content only](https://design.va.gov/components/alertboxes#background-color-only)

See https://staging.cms.va.gov/node/34352

<details>
<summary> Screenshot of CMS editorial side </summary>

![image](https://user-images.githubusercontent.com/55411834/132579215-148d110f-3cd2-48b2-9663-7dceafe034f3.png)

</details>

---

<details>
<summary> Screenshot of FE when title has been entered </summary>

![image](https://user-images.githubusercontent.com/55411834/132579241-ca660086-d7da-4b0d-946c-f04e5cbaa809.png)

</details>

---
<details>
<summary> Screenshot of FE when title has **_not_** been entered </summary>

![image](https://user-images.githubusercontent.com/55411834/132579271-ed63b098-6056-40c8-98de-103b5cf9fc11.png)

</details>

## Steps to reproduce

1. Add a Non-reusable alert content block to a VAMC detail page. 
2. Populate the rich text content
3. Leave the alert heading field empty
3. Observe that the content does not
4. Edit the content block by adding an alert heading
5. Observe that the content now displays

## Acceptance Criteria
- [ ] When a non-reusable alert content block is added to a VAMC detail page, the content renders, even without a heading

**Comment by mmiddaugh** [comment]
closing as duplicate to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6266

**Comment by mmiddaugh** [comment]
According to the design system, this component cannot be used without a headline. 
- [Alert boxes](https://design.va.gov/components/alertboxes)
- [Background content only](https://design.va.gov/components/alertboxes#background-color-only)

This is a content management change for CMS - headline should be required.

**Comment by jilladams** [comment]
@omahane @swirtSJW to repro and see if this is real

**Comment by jilladams** [comment]
nonreusable alerts don't exist on VAMC Detail Pages anymore
