### ISSUE TITLE
Add Component to Search Results Page

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#29784]
##  Description
Add the new Search DropDown Component to the search results page, so that it functions and allows us to test analytics, accessibility, and other usability features.

## Acceptance Criteria
- [ ] Search Drop Down Component has been added to the results page, replacing the old search bar

**Comment by denisecoveyduc** [comment]
@srsuddath This is the issue we created during planning. Could you please update the description accordingly and create (or let me know) of any additional tasks required. Thanks!

**Comment by srsuddath** [comment]
Component has been successfully added to the search results page
