### ISSUE TITLE
Access for Marc Heusser

### ISSUE THREAD

**Issue by mheusgit** [department-of-veterans-affairs/va.gov-team#29799]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Cecilia.Lee@va.gov
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Michael Lovejoy
- Please provide your name.
   > Marc Heusser
- Please Provide your email.
   > marc.heusser@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse Team Quokka - Senior Software Engineer

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8aEVtx/2McbSByDbjduz1dUugRi4QUCz/7XZOcczPTp2QTDnj9Li45KLMHMkwEsMFbzgFTilB4N3nAg6Dhx7CPdGNBq3m1pS6repWKxCFq94LH07DgA86S26Y5jWBm4BnZYAEUOgr0TervPKTGasNatZk7Y0LvqsjnezC1a8dLWiDu14igoWUXTTEjtgsc36Gd7nBXNw75JIINfSLGASwk1cnwDQYnpk/nROmMY8ps1Fns0bTkFzf6EedcJByFwht5B1XEizJgoRzZ635F5g/kTvOPA8QMiEJLNUmgBzqx1U67uttTzMpq02dsmsllA9o/sFDbmX73IT3wTQmvNyb mheus@Marc-Heusser-HP
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  - AWS Console access for developing and maintaining the Lighthouse dev portal

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Marc Heusser
COR: Cecelia Lee
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @mheusgit 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by mheusgit** [comment]
Hi @mleclerc00, any update on AWS access approval?

**Comment by mleclerc00** [comment]
This is out of ops hands at this point and will require that your COR confirms with mike chelen that your eqip is under way

**Comment by mheusgit** [comment]
Hi @mleclerc00 & @mchelen-gov, an email was send to my COR last week concerning this access.  Have either one of you received the proper confirmation?

**Comment by mheusgit** [comment]
Hi @mchelen-gov, have you received confirmation yet concerning my eqip status?  I am hoping to get the ticket closed.
