### ISSUE TITLE
**DISCOVERY** |  XLIFF to Manage Translated Content Workflow

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#29797]
##  XLIFF Overview and Benefits

XLIFF is an XML-based format used to standardize the data transfers between systems. Also, it's one of the most common formats used for the localization process and by CAT Tools. This special format enables translators to concentrate on the text to be translated, without worrying about text layout. XLIFF format specifies the elements, attributes as well as target translations that are used to store content that has been extracted from other sources.

> XLIFF files are bilingual documents that hold the content to be localized. In addition, all corresponding translations, and additional data to improve localization efficiency. With XLIFF files, both source and target language data remain in sync as the localization process takes place.

- The acronym XLIFF stands for **XML Localization Interchange File Format**.  XLIFF is an XML-based file format for the exchange of translation and localization data. "XML-based" means that XLIFF is an XML application and is based on the rules of XML. 

- XLIFF is file format-independent, and layout-independent of text to be translated. As a general rule, the exchange can take place between all tools and systems that support XLIFF. 

- Often, translation data is exchanged between translation management systems (TMS). However, they can also be exchanged between TMS and other systems in which language resources are entered or managed, such as a CMS used for creating and maintaining websites.

- File format-independent" means that XLIFF serves as a kind of meta file format, i.e. the data are not provided in a specific file format such as Word, PowerPoint, HTML but merely in a single format: XLIFF.

- To generate XLIFF files, the data to be translated are first extracted from the source files. Subsequently, the data to be translated are formatted according to the XLIFF standard and stored in an XLIFF file. 

- After the translation, the translated XLIFF file is converted back to the original format.

 - Apart from the segments to be translated, **XLIFF files often also contain matches and terminology entries as well as all context information**. The file format is also very useful for creating a single file from multiple source files.

- Java (.properties, .json)is one of the most common file formats for software and can be leveraged with XLIFF.

- We'll need to capture the original text and format the translation so that it retains the original layout and HTML code. Compare this to using a regular text editor where common issues encountered include:

    - Missing text because it was hidden and thus not copied
    - Uneditable text
    - Color or font changes
    - Broken links
    - Uneven or incorrect formatting
    - Messed up page layouts
  
## Story

I want to receive structured files like .xlf that I can use with translation solutions other than Drupal

As a writer working with a translator to translate a piece of content, I'd like to be able to extract the text from Drupal and save as an XLIFF file to send via email to my translator
AND
My translator can then complete the translation in an XLIFF-enabled translation editor
THEN
The translated XLIFF file can be sent back to me to import back to Drupal (which is then used to generate translated content)

**FUTURE**
The new translations are saved to the Translation Memory to enable future translations to be done faster and easier.

## Acceptance Criteria

- [ ] TBD

**Comment by adamwhitlock1** [comment]
Findings on XLIFF exporting and Translation Management in Drupal

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/XLIFF-to-Manage-Translated-Content.md

My recommendation would be to use the built in Drupal tools, and to make it a priority to support translation tooling during the Accelerated Publishing initiative work to enable this.

There are a couple alternative options that could be investigated further, but are not translation focused and are more catered to exporting general Drupal content in CSV or XML. If one of these modules was used, then custom conversion to XLIFF would need to be done to the files before sharing with translators.
