### ISSUE TITLE
Integrate important details from Canary playbook into the Incident Response Playbook

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#29813]
# Description
- [x] Distill the essence of the expanded Canary playbook into the consolidated [Incident Response Playbook](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Incident%20Response%20Playbook.md) for on-call engineers.
- [x] Link to the full Canary playbook from the Incident Response Playbook
- [x] Determine whether we should move the Canary playbook to the sensitive repo. Is there some `sensitive` area of Confluence we should be using?

**Comment by rjohnson2011** [comment]
PR Created: https://github.com/department-of-veterans-affairs/devops/pull/10204

Any page in Confluence may be made Private/Sensitive by the `Restrictions` lock icon (next to the blue Share button in the top right) by a team member with Admin permissions.

**Comment by rjohnson2011** [comment]
PR approved & merged.
