### ISSUE TITLE
Mobile App Store Content Tweaks from VA Mobile team

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#29817]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [X] Something else (please add details in the next question)

## What do you need help with?
*Use this space to describe your content need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*
The VA Mobile app would like to update a few pieces of language on the Apple and Google Play stores. We'd love some quick eyes on this content, as it is veteran-facing. The doc is here: https://docs.google.com/document/d/1C_dLb5vUVnIHK-3c8SZxX1yeSeFieET436vX1pq95tQ/edit
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: 9/28
- Estimated staging review date: N/A
- Content and IA work needed by: 9/15/21

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VA Mobile App
-	OCTO-DE product owner: Leanna Miller; Travis Newby
-	Product manager: Ambika Roos
-	Designer: Jen Ecker
-	FE engineer: Patrick Saxto
-	Product/team Slack channel: #va-mobile-app

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by DanielleThierryUSDSVA** [comment]
Hi there. Just a quick note that I've started looking at this and will add the rest of my comments by tomorrow. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht, I did a quick pass through this. Could you give it a look as well for anything else? Thanks!

**Comment by RLHecht** [comment]
I took a look at this as well and made a few minor copy edits. @ambikaroos this should be ready for you now. Let us know if you need anything else. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht!

**Comment by RLHecht** [comment]
@ambikaroos Can this ticket be closed or is there more work from us needed?

**Comment by ambikaroos** [comment]
We're all set! Thank you!
