### ISSUE TITLE
Remove asterisk from required note

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#29819]
## Description
The asterisk in our required form fields don't reference any definition. Per Design System note in #26619, we can remove these asterisks throughout our tool.

_TBD - PR for component library changes to be done by Auth Exp team_

**Examples of current uses**
 ![staging_va_gov_health-care_schedule-view-va-appointments_appointments_new-appointment_iPhone_5_SE___2_.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/fbcda18c-60db-40c7-b4f6-9601359a5ef4)     ![staging_va_gov_health-care_schedule-view-va-appointments_appointments_new-appointment_iPhone_5_SE___4_.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/d31110aa-f4fb-46e4-ac7c-d949d343c82d)  

---

## Acceptance Criteria
Given any VAOS page form field or text
When user input is required
Then fields/text are labeled as `(Required)` (no asterisk)
Once initial change is made, evaluate how many tests are broken
* If more than reasonable to update, send back to Design System team

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
Note from grooming - This might cause a bunch of broken tests in other team’s projects, in which case we’ll likely have to pass back to Design System team

**Comment by ldelacosta** [comment]
I have created a [new FE ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63316)for this work. Closing out the ticket today. cc: @JRRoof
