### ISSUE TITLE
[FE] Notification Prefs: Revisit hit areas for radio buttons

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29814]
## Background
As part of #29473 Erik noticed that the hit areas around the radio buttons are not quite centered/aligned properly. See second portion of comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29473#issuecomment-915534829).

Current state as implemented on staging:
<img width="677" alt="132578065-a0234760-2ac7-4998-8f47-d2cd4dad3f27" src="https://user-images.githubusercontent.com/45603961/132760809-86f582cd-d086-4426-9678-1237da4217e7.png">

## Acceptance Criteria
- [ ] Hit areas around the radio buttons are centered

**Comment by erikphansen** [comment]
This is being addressed by https://github.com/department-of-veterans-affairs/vets-website/pull/18674

**Comment by erikphansen** [comment]
The radio button hit areas, and radio button spacing, have been adjusted and can be validated on staging, @andaleliz

**Comment by andaleliz** [comment]
YAS! Looks great. Thanks @erikphansen
