### ISSUE TITLE
[Design] Notification Prefs: Content ticket to review hint text for Rx tracking notification item

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29810]
## Background
Due to some data limitations around VA facilities and the Rx shipment tracking notification item, we need to include some hint text with the notification item to inform users that only specific facilities have this capability.

## Tasks
- [x] Draft language
- [x] Discuss/get approval from content
- [x] Add to ticket #28982

**Comment by andaleliz** [comment]
@ajakabcin I'm closing this since you and Erik have closed out #28982.

**Comment by andaleliz** [comment]
@ajakabcin The final text is in [Erik's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28982#issuecomment-918418951):

>"Only available at some VA health facilities. Check with your VA pharmacy first."

**Comment by ajakabcin** [comment]
Thanks @andaleliz! Would it be possible to show the hint text in the mock-ups? If you need a new ticket for that let me know!

**Comment by andaleliz** [comment]
Sure, it's [here](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/142049300/simulate/sitemap).
