### ISSUE TITLE
Setup a dedicated Jenkins Worker for va.gov content deploys (VFS)

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2981]
Dedicated Jenkins Worker for va.gov content deploys (VFS)
- c5.2xlarge 8vCPU @ 3.4Ghz) 
- io1 volume @ 3,000 IOPS OR NVMe SSD (c5d.2xlarge)
- placement group to achieve 10Gbps link

**Comment by brandonrapp** [comment]
Hey @ricetj - We will need to setup some time to talk through this with @nathanhruby. Right now this is not a hard requirement but we a discussion would still be helpful.

**Comment by ElijahLynn** [comment]
Per our Zoom discussion just now. This is a _Nice to Have_ and not a blocker for MVP. THe main goal of this dedicated Jenkins worker is to not have any blocks waiting for other works that are maxed out. Also in play is the need to have this job be as fast as possible. 

If there are other ways to achieve the goals above then that is fine I suppose, but this seemed easiest.

**Comment by jbritt1** [comment]
I believe our Jenkins capabilities and structure has long achieved what we needed out of this work and this can likely be closed. Agreed, @ElijahLynn? CC @jhouse-solvd

**Comment by ElijahLynn** [comment]
Yup, we won't be needing this Jenkins worker.

**Comment by jbritt1** [comment]
> Yup, we won't be needing this Jenkins worker.

Thanks Elijah!
