### ISSUE TITLE
Setup a Dedicated File Server (VSP DevOps)

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2982]
Dedicated File Server (VSP DevOps)
- c5.2xlarge 8vCPU @ 3.4Ghz) 
- io1 volume @ 3,000 IOPS OR NVMe SSD (c5d.2xlarge)
- placement group to achieve 10Gbps link

**Comment by KevinMHoffmanUSDS** [comment]
Discuss closing it, will re-open or recreate when neccessary
