### ISSUE TITLE
[BUG] Promo Banner dismissing when hyperlink clicked 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#29824]
## What happened?
_When I clicked the link on the promo banner, it also dismissed the banner. When investigating additionally I didn't need to click the "X" to dismiss it, but when you click the hyperlink it automatically dismisses the promo banner._

## Specs:
- Device: All Devices 
- Browser: ALL
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: Code is maintained in: @department-of-veterans-affairs/component-library/PromoBanner
- Test User _(if applicable)_:

## Desired behavior
_Banner shouldn't dismiss when clicking the hyperlink_

## Acceptance Criteria
- [ ] _Fix banner behavior so dismissal is working properly._

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by Rleahy22** [comment]
This should go out with the deployment Wed (9/15)

**Comment by brianalloyd** [comment]
Validated and closing in support.

**Comment by brianalloyd** [comment]
Validate and closing in support.
