### ISSUE TITLE
Facility operating status is not displayed on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29828]
## What happened?
Facility operating status alert for `Limited services and hours` is not displayed on Facility Locator. 

## Steps to Reproduce

- View [Colorado Springs Vet Center's Location page](https://www.va.gov/colorado-springs-vet-center/locations/)
- Observe "Limited services and hours" is displayed for the location
- View the [same location on the Facility Locator](https://www.va.gov/find-locations/?page=1&address=colorado%20springs%2C%20%20co&facilityType=vet_center&serviceType&latitude=38.834&longitude=-104.8253&radius=58&bounds%5B%5D=-105.5753&bounds%5B%5D=38.084&bounds%5B%5D=-104.0753&bounds%5B%5D=39.584&context=Colorado%20Springs%2C%20Colorado%2C%20United%20States)
- Observe the absence of operating status alert for Colorado Springs Vet Center

Facility Closed status can be tested with [Baton Rouge VA Clinic page](https://www.va.gov/southeast-louisiana-health-care/operating-status/) and [Facility Locator](https://www.va.gov/find-locations/?address=baton%20rouge%2C%20la&bounds%5B%5D%5B%5D=-77.53653&bounds%5B%5D%5B%5D=38.3976763&bounds%5B%5D%5B%5D=-76.53653&bounds%5B%5D%5B%5D=39.3976763&facilityType=health&latitude=30.4507&longitude=-91.1546&page=1&serviceType&radius=32&bounds%5B%5D=-91.9046&bounds%5B%5D=29.7007&bounds%5B%5D=-90.4046&bounds%5B%5D=31.2007&context=Baton%20Rouge%2C%20Louisiana%2C%20United%20States)

Facility Notice status can be tested with [Sioux Falls in Drupal](prod.cms.va.gov/vba-facilities/locations/sioux-falls-regional-office) and on [Facility Locator](https://www.va.gov/find-locations/?address=sioux%20falls&bounds%5B%5D%5B%5D=-77.53653&bounds%5B%5D%5B%5D=38.3976763&bounds%5B%5D%5B%5D=-76.53653&bounds%5B%5D%5B%5D=39.3976763&facilityType=benefits&latitude=43.55&longitude=-96.7003&page=1&serviceType&radius=27&bounds%5B%5D=-97.4503&bounds%5B%5D=42.8&bounds%5B%5D=-95.9503&bounds%5B%5D=44.3&context=Sioux%20Falls%2C%20South%20Dakota%2C%20United%20States)

<details>
<summary> Relevant screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/132875828-ce416866-c685-4789-adaa-19a5bd5dc937.png)

![image](https://user-images.githubusercontent.com/55411834/132876091-a2152504-aee8-4ae0-aac3-6d939c83812f.png)

</details>

## Desired behavior
If the operating status for a facility is `Limited services and hours`, `Facility notice` or `Closed` in Drupal, the appropriate alert should be displayed on the that facility's search result card in the Facility Locator.

**Comment by darkbushido** [comment]
Colorado Springs Vet Center's Location page API call
https://api.va.gov/v1/facilities/va?ids=vc_0542V,vc_0504V

Facility Locator
https://api.va.gov/v1/facilities/va?bbox[]=-105.5753&bbox[]=38.084&bbox[]=-104.0753&bbox[]=39.584&type=vet_center&page=1&per_page=20&mobile=false&radius=58&latitude=38.834&longitude=-104.8253

Both are returning 
```
        "operatingStatus": {
          "code": "NORMAL"
        },
```

Is there anything else that the FE would call for the operating status?

**Comment by mmiddaugh** [comment]
This was caused by a bug in the Facilities API. Lighthouse deployed an update this morning ~10:15am ET which caused the API to only emit default values for both operating_status and detailed_services. After we reported it to Lighthouse, Adam Stilton went in and corrected the error, resolving the issue on FL.
