### ISSUE TITLE
Platform support slack bot: Reformat support requests

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29825]
## Description

Reformat support request confirmation posts so Summary is at the top to make them easier to scan. ([Slack conversation further context](https://dsva.slack.com/archives/CBU0KDSB1/p1623090513206500)).

## Documentation

- [README](https://github.com/department-of-veterans-affairs/platform-support-slackbot/blob/master/README.md)
- [Project overview](https://docs.google.com/document/d/1loKKQCD1gqlvIdxucsYAjDbd_tSCnqvxs-W-nVxzwGM/edit#heading=h.o1b49rfssykx)
- [Repository](https://github.com/department-of-veterans-affairs/platform-support-slackbot) 
- [Feature request summary document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1548943522/Slack+Workflow+Post-Launch+Issue+Tracker)

**Comment by k80bowman** [comment]
I was looking through the slack thread cited above and it seems that the problem isn't so much that the summary needs to be at the top as it is that the way the messages are currently formatted they take up too much space. So I decided to play around a little in Slacks Block Kit playground to see if I could reformat the message to be more compact and make sure it's highlighting the important information.

I can talk with James and Rebekah about this at our meeting on Monday, but I wonder if something like this would be better?
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/cd4fee4b-5a89-4a99-9b0e-68a61f391f56)

**Comment by k80bowman** [comment]
Just to note, this is the design we settled on.
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/1c1f2353-9d5e-48c2-a8ae-805df7a9e757)
