### ISSUE TITLE
Error message content recommendation from VSA Claims & Appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29829]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
*Use this space to describe your content need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We are adding a new validation error message to form 526. When a Veteran is activated (title 10) from the Reserves or National Guard, their activation date must be after a Reserve or National Guard start date. If not, this error message will be shown

![Screen Shot 2021-09-10 at 9 46 50 AM](https://user-images.githubusercontent.com/136959/132872432-c6e8a073-8d7f-40e3-888c-a71cf0e14e2a.png)

The previous page asks for obligation service dates, but the validation is not based on the service period dates that only include Reserve or National Guard periods. See https://dsva.slack.com/archives/C8R3JS8BU/p1629381358016100

<details><summary>Obligation dates page (dates not used when validating)</summary>

![Screen Shot 2021-09-10 at 9 49 09 AM](https://user-images.githubusercontent.com/136959/132873576-427d9862-4288-4bcc-92d2-12aa15fbeaec.png)</details>

<details><summary>Service history page</summary>

![Screen Shot 2021-09-10 at 9 49 28 AM](https://user-images.githubusercontent.com/136959/132873656-0706c686-f9df-49d3-acbb-eda02b638ac3.png)</details>

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/526%20Benefits%20Delivery%20at%20Discharge%20-%20Product%20Guide.docx
- Link to or attach user flows: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/workflow-diagram.png
- Link to prototype or mockups: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/federal-orders
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28962

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: 
- Estimated staging review date:
- Content and IA work needed by: No timeline 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Claims & appeals
-	OCTO-DE product owner: Matt Self
-	Product manager: @vhenry07
-	Designer: @kevinstachura 
-	FE engineer: @Mottie
-	Product/team Slack channel: #vsa-claims-appeals

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@Mottie So sorry for the delay on this. We're very backed up. 

My only change would be to add "the" before both "Reserves" and "National Guard":
Your activation date must be before your earliest service start date for the Reserves or the National Guard.

**Comment by RLHecht** [comment]
@bethpottsVADEPO We should change it to "Reserve" (no s) per the style guide

**Comment by Mottie** [comment]
Thanks @RLHecht!

**Comment by Mottie** [comment]
Result

![](https://user-images.githubusercontent.com/136959/134243445-3589cd48-a533-4345-8379-c73c15a49a15.png)

**Comment by bethpottsVADEPO** [comment]
@Mottie @RLHecht Thanks so much, looks great!
