### ISSUE TITLE
Upgrade CMS Server (VSP DevOps)

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2983]
CMS Server (VFS)
- Upgrade from gp2 @ 100 IOPS > io1 @ 3,000 IOPS OR NVMe SSD (c5d.2xlarge)
- placement group to achieve 10Gbps link

**Comment by jbritt1** [comment]
@ElijahLynn, with the work that was done some time ago to allow the io1 option.. is this one good to close at this time?

**Comment by ElijahLynn** [comment]
I think so for now. The CMS server is still on GP2 but bursts to 3,000 IOPS, I verified. It only does 3Gbps though. But if we need a faster transfer time eventually we can use a placement group. 

+1 for closing.
