### ISSUE TITLE
Create proposal for database schema to allow for login.gov->cognito  integration and sharing user preferences/forms/etc between log in types

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#29833]
This schema should provide:
- Ability for a login.gov user to log initially with IAL2, prove they've been verified, and later log in with IAL1
- Mapping from login_gov_uuid to icn
- Ability for an ID.me user to utilize this schema (perhaps with the same IAL1 working with previously verified IAL2 plan)
- Correlation between user information from a login_gov log in and an id.me log in
- At least some initial consideration for future IDPs if relevant

**Comment by bosawt** [comment]
### Proposal

#### Prerequisite
	* Every credential provider uses a different unique identifier (idme_uuid, login_gov_uuid, mhv_correlation_id, edipi, etc)
	* If we receive an identifier from a credential provider, this identifier is assumed to be the new ground truth (any conflicts will be resolved in favor of incoming identifier)
	
#### Schema
[image:6FFA647A-9895-4C01-BE58-EE44B6183E41-1351-000046E4A5D22D6C/Screen Shot 2021-09-14 at 5.00.46 PM.png]

[image:BE7C79B5-8265-4C72-A62A-FC2437AF7109-1351-000046E8AC818948/Screen Shot 2021-09-14 at 5.01.05 PM.png]

#### Actions
* User logs in with IAL1, and we receive identifier `<cred_prov_uuid>`, and type `<cred_prov_type>`
	*  We query `user_verifications` table with `<cred_prov_uuid>` and `<cred_prov_type>`
		* If record is found in `user_verifications`, and `verified_at` is defined
			* We query `user_accounts` with `user_account_uuid`
				* Query MPI with `user_account.icn`
					* If `user_account.icn` != `<mpi_response>.icn`
						* `user_account.icn` -> `<mpi_response>.icn`
		* If record is found in `user_verifications`, and `verified_at` is not defined
			* IAL2 call is made, then:
				* We update existing entry in `user_verifications`, overwriting:
					* `<cred_prov_type>` -> `type` column
					* `<cred_prod_uuid>` -> `<type>_uuid` column
					* `verified_at` -> `Time.now`
				* We create an entry in `user_accounts` (or overwrite existing entry), and `user_verification.user_account_uuid` -> `user_account.uuid`
				* We query MPI with identifiable information from IAL2 response:
					* `user_account.icn` -> `<mpi_response>.icn`
		* If record is not found in `user_verifications`
			* IAL2 call is made, then:
				* We create an entry in `user_verifications`
					* `<cred_prov_type>` -> `type` column
					* `<cred_prod_uuid>` -> `<type>_uuid` column
					* `verified_at` -> `Time.now`
				* We query MPI with identifiable information from IAL2 response, returning `<mpi_response>`
				* We query `user_accounts` for `<mpi_response>.icn`
					* If found:
						* `user_verification.user_account_uuid` -> `<query_response_user_account>.uuid`
					* If not found:
						* Create `user_accounts` entry
						* `user_verification.user_account_uuid` -> `<created_user_account>.uuid`
						* `<created_user_account>.icn` -> `<mpi_response>.icn`

**Comment by nsoutouras** [comment]
**Closes with 61** - should be superseded by (https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/vets-api/7961)
