### ISSUE TITLE
Discovery: margin/padding for checkboxes and radio buttons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#29835]
Follow up from DSC meeting on 9/10 when issue around Margin/padding discrepancy between checkboxes and radio buttons was discussed. 

Action items for DST

- [ ] Determine level of effort to make this change. Look at code for these components and see how they’re structurally formed. 
- [ ] Identify any down stream effects if we change padding to get margins and spacing equal. 

Original issue
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/534

**Comment by k80bowman** [comment]
Closing, this has been resolved
![image](https://user-images.githubusercontent.com/12739849/178556748-4d8a18c6-baed-4c12-9459-21ba708f789f.png)
![image](https://user-images.githubusercontent.com/12739849/178556768-5af760ef-a904-4dca-9a41-fb27ddf103f7.png)
