### ISSUE TITLE
Compare Checkbox error message placement and then make announcement

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#29834]
Follow up from DSC meeting on 9/10 when issue with checkbox error message placement was discussed. Issue where error message was showing up below for one checkbox vs. error message appears above for multiple checkboxes has been resolved. 

- [ ] DST to compare existing Forms library component with DS component to make sure they’re the same. 

- [ ] Make announcement that checkbox component has been updated. Put out comms in Monday meeting and in slack that this is an error that has been corrected and to please check applications if you haven’t received this code.

Original ticket
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/535

**Comment by caw310** [comment]
@bkjohnson , assigned this to you since you were at the DSC meeting. Let me know when you have time to get this done.

**Comment by bkjohnson** [comment]
Closing as this is a stale issue.
