### ISSUE TITLE
File upload error form 526

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#29846]
Troubleshoot the error

EVSS_15006We were unable to complete your upload because the uploaded file is corrupted and cannot be uploaded. Please verify that the file is valid. If you still have problems, call the VA  at 1-800-827-1000 (711, if you use a TDD) for assistance. When you call, provide the following error code: EVSS_15006.

**Comment by michelpmcdonald** [comment]
Locked PDFs are supposed to be unlocked prior to saving them in s3 before the files are upload to evss.

I was unable to reproduce the issue.  PDFK is used to unlock the original PDF and saved an unlocked copy of the PDF before uploading the PDF to S3.

The password the vet provides to unlock the PDF is not stored, so at this point, I can't test unlocking this particular file.

Suggest the vets who hit this try uploading their files using CST.
