### ISSUE TITLE
Need BRD change to specify the volume type and IOPS specification (VSP DevOps)

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2984]
## Problem
Need BRD change to specify the volume type (gp2/io1) and IOPS specification (may not be as urgent if we use c5d instance types that come with an NVMe SSD. Still would be useful to add.) (VFS)

## Goal
_Allow the IO1 EBS Vol type to be specified in a deployment_

## Acceptance Criteria
- [ ] _CMS team can use IO1 EBS Vol_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
For this task, would we want to see the option as a parameter within Jenkins that could be selected during the deploy? Or an environment variable with Ansible inside the DevOps repository?

**Comment by brandonrapp** [comment]
@ElijahLynn can you provide some context to the question above?

**Comment by ElijahLynn** [comment]
Sure, for example: https://github.com/department-of-veterans-affairs/devops/blob/119768e018516ca88b1e9860a3f59bfd8567842f/ansible/deployment/config/cms-vagov-dev.yml#L45

deployment_volume_size: 16 (current)
deployment_volume_type: io1 (proposed, default is gp2, need io1 as an option too)

**Comment by jbritt1** [comment]
Perfect, that is kinda what I thought but wanted to be sure. Working on an option for being able to change from the default (gp2) and select io1 as well as an amount of provisioned iops. Should have a PR up Monday.

**Comment by ElijahLynn** [comment]
> Perfect, that is kinda what I thought but wanted to be sure. Working on an option for being able to change from the default (gp2) and select io1 as well as an amount of provisioned iops. Should have a PR up Monday.

Ahh yes, the provisioned IOPS is key here too, thank you!

**Comment by jbritt1** [comment]
No problem

**Comment by jbritt1** [comment]
The options are there now in latest master. Also included instructions on use in the `deployment_options.md` doc.
