### ISSUE TITLE
RESEARCH | Page & Word Counts for VA.gov

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#29848]
## User Story

As a product manager, I would like to have a count of the # of pages in the Benefit Hubs and the associated word count for each page, so that I can begin to estimate our translation  budget and secure adequate funding.

Benefit Hubs: 
- Disability
- Health Care
- Education
- Records
- Housing Assistance
- Pension 
- Careers & Employment
- Burials & Memorials
- Family Member Benefits
- Life Insurance
- Service member Benefits

## Acceptance Criteria

- [ ] Number of pages within the Benefits hub (by hub is a nice-to-have)
- [ ] Number of words for each page within the Benefit hubs

(Note: once we secure this info I will open up another ticket to do the same for Resources and Support but wanted to note it here if it is easier to do in one fell swoop).

**Comment by adamwhitlock1** [comment]
Some findings on page word counts and the process I used:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/Page-and-Word-Counts-for-Benefit-Hubs.md

CSV of all analyzed urls and word counts
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/va_page_word_counts.csv
