### ISSUE TITLE
Investigations ways to document design system patterns

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#29856]
##  Description
In order to document the search design pattern on the design system it has been suggested that we use Storyboard. This issue is to investigate what is required.

## Background 
- Search UI Consistency: Document Search Design Pattern for Design System #24597
- Slack message: https://dsva.slack.com/archives/C01Q9PDPLE9/p1630514356000600

## Acceptance Criteria
- [x] Determine if storyboard is a good solution to document the design pattern in the design system
- [x] Identify Next Steps

**Comment by mgleo** [comment]
Skipping Storybook for now. Design system team will develop guidelines for visual portion of documentation. Experimental design system pattern does not need to be as thoroughly documented as other design system patterns.
Follow [Pattern Template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=&template=documentation_template.md) and [Copy Deep Link Example](https://design.va.gov/experimental-design/copy-deep-link).
