### ISSUE TITLE
Jenkins Job Modifications (VSP Devops/Elijah)

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2985]
- Single Jenkins job for Content Deploy
  -  SSH Connection Reuse - keep a warm connection too aka `ControlPersist` setup
  - No virtualenv setup, or reuse existing one
  - No docker image building
  - Don’t git clone, just git pull
  - npm cache reuse
  - Use new build script
  - Skip GitHub Release API
  - More are possible (if needed)
- Cleanup old jobs (4 of them)

**Comment by jbritt1** [comment]
Is this work still relevant / necessary? CC @jhouse-solvd

**Comment by jhouse-solvd** [comment]
Please see #2719 for more current iterations of this effort.
