### ISSUE TITLE
Analytics Bug Report - Facilities monthly report data update

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#29854]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

Internal Analytics report

- Is this a feature request or a bug?

  - [ ] Feature request
  - [x] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature
- Why the feature is needed

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

The [Facilities data in the new VA.gov monthly reports](https://va-gov.domo.com/page/1314425343) are not updating correctly. The data is not set to retry on failure. This resulted in data loss when originally scheduled for reporting deploy on 9/7, but the data was updated. We would like to look into this issue to fix data updates for future monthly reports. 

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
This is a systemic issue we will address in another ticket.  But for this ticket, this particular dataset has been fixed, backfilled, and rescheduled.

Closing.
