### ISSUE TITLE
Improve error messages in Liquid Template Testing Framework

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#29866]
Fork `tinyliquid` (it hasn't been updated in ~5 years) or add `try/catch` block to `renderHMTL` to improve error handling.

See Slack thread https://dsva.slack.com/archives/C01CHAY3ULR/p1631540367135800

**Comment by holdenhinkle** [comment]
@mpelzsherman @zacharymorel So you can follow this...

**Comment by zacharymorel** [comment]
Hey, thank you @holdenhinkle.

**Comment by mpelzsherman** [comment]
If we don't want to fork tinyliquid, we could simply add a try/catch in our `renderHTML` function that says something like “An error occurred while rendering the template. Check to make sure all required values are populated.”

**Comment by ddzz** [comment]
All Liquid template tests in `content-build` have been deleted, so we may have to look into removing any remaining code used for those tests.

**Comment by JoeTice** [comment]
Liquid template tests have been removed at this point, so this ticket is no longer valid as is
