### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#29872]
There was an intermittent failing test in vets-api/modules/vaos. It has been disabled it so it doesn’t affect deploys. Please fix at your convenience.
#7870 Skip intermittent failing JWT wrapper spec
• This test was off by a second. We should use TimeCop here so we can avoid issues where time advances between when logic is run and comparison happens.
• VAOS will be notified so the spec can be fixed.
Failures:

  1) VAOS::JwtWrapper#token with a decoded payload includes a exp(iration) timestamp
     Failure/Error: expect(decoded_payload['exp']).to eq(Time.now.utc.to_i + 900)
       Expected 1631218483 to eq 1631218484.
     # ./modules/vaos/spec/services/jwt_wrapper_spec.rb:57:in `block (4 levels) in <top (required)>

https://github.com/department-of-veterans-affairs/vets-api/pull/7870

**Comment by ajmagdub** [comment]
added timecop to jwt_wrapper_spec.rb.
