### ISSUE TITLE
Adding [individual] to DSVA Slack

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/va.gov-team#29883]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Andrew Gray is part of the business sponsor for the supplemental claims work on Lighthouse. 

Are you requesting to add an individual as a:

- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add Andrew.Gray@va.gov as a multi-channel guest to these channels: [appeals-api].

I've asked for making him a multichannel guest as he may need to be on more channels as we continue to work together.

**Comment by LizCallaghan** [comment]
already has a guest account and is in the channel
