### ISSUE TITLE
Publish event needs to tar files and content

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2989]
Publish event needs to tar files and content
- come up with filenaming structure, use timestamps?
- how does downstream consume? 
  - /content.tar (always latest)
  - /files.tar (always latest)

Image Content Required
- Need all the crop sizes

Acceptance Criteria
- [ ] Publish Event in CMS triggers action to tar files and content
- [ ] Images are included

**Comment by ElijahLynn** [comment]
Update on this: For now we are going with a solution that will tar it every minute instead of do this on publish event. We will work towards doing this on publish event but want to put a more reliable background worker system in place and don't want that to hold up "good" from getting shipped.

**Comment by ElijahLynn** [comment]
> Update on this: For now we are going with a solution that will tar it every minute instead of do this on publish event. We will work towards doing this on publish event but want to put a more reliable background worker system in place and don't want that to hold up "good" from getting shipped.

We ended up tarring this on each request and the request takes less than 1 second for content and less than 5 seconds for all the files. Details are here > https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-export.md

Closing.
