### ISSUE TITLE
Adding Gino Perlangeli  to DSVA Slack

### ISSUE THREAD

**Issue by nsmith1982** [department-of-veterans-affairs/va.gov-team#29904]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Good morning, please add Gino Perlangeli (gperlangeli@clarityinnovates.com) to DSVA Slack as a Full Member.  Gino is a new Site Reliability Engineer (SRE) working on VSP.  Please give him access to the following channels:

# vfs-platform-support
# vfs-all-teams
# vsp-service-design

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
