### ISSUE TITLE
Parameter store write permissions for vets-api service account

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#29905]
## Issue Description
In order to automate the db key rotation, the vets-api service account needs write permissions to parameter store (it currently only has read). The vets-api account will need write perms for the lockbox.master_key and lockbox.previous_master_key across all envs in order to use Github Actions to update values in parameter store. We can most likely use something like [this](https://github.com/marketplace/actions/aws-parameter-store-injector) to update values. 

---
## Tasks
- [ ] Figure out exactly which values we will need to update in the GH Action
- [ ] Ask Ops member to update permissions for the vets-api service account (for the keys in previous step ^^)

**Comment by LindseySaari** [comment]
Need to investigate this more, but most likely this will be irrelevant if we move to KMS. From a security perspective, we also need to consider if GHA was compromised. If this were the case, encryption keys would then be available to the bad actor.

**Comment by ericboehs** [comment]
I'm scared to do this in GHA and we're moving to KMS (soon™).

@rileyanderson suggested we do this in a cron on a VA instance. Maybe good idea?
