### ISSUE TITLE
Incorrect PDF form name on VA Survivors Pension page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29906]
## What happened?
When reviewing analytics for VA form PDF downloads, I found metrics for a form that doesn't exist (21-534EZ) and traced it to https://www.va.gov/pension/survivors-pension/.   The URL to the form is correct, but the text should be changed to 21**P**-534EZ.   Screen shot below.

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/c318c5d5-4378-44dc-8549-9e98e22b5d5f)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO @brianalloyd - I am not certain if this is PW or related to another team.  If it's not PW, please let me know and I will re-assign.  Thanks!

**Comment by RLHecht** [comment]
@brianalloyd @MarciMcGuireGCIO We can fix this. I'll let you know when the change is live.

**Comment by brianalloyd** [comment]
Thanks @RLHecht appreciate it.

**Comment by RLHecht** [comment]
This change is now live. FYSA @MarciMcGuireGCIO @brianalloyd. Going to close the ticket.

**Comment by brianalloyd** [comment]
Thanks @RLHecht for the lift on this ticket.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @RLHecht and @brianalloyd !
