### ISSUE TITLE
Access to devops Repo for Nick Sprinkle

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#29912]
## Description
I am requesting access to the devops repository for work I am doing on the FE Tools team.

---
## Acceptance Criteria 
- [x] Nick Sprinkle has access to the devops repository

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Added `vsp-tools-frontend` with `write` permissions to the `devops` repository

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
Confirmed access is now allowed: https://dsva.slack.com/archives/CJYRZK2HH/p1631630667409000
