### ISSUE TITLE
Access for Patrick Ryll

### ISSUE THREAD

**Issue by charCodelet** [department-of-veterans-affairs/va.gov-team#29918]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Michael Wilson
- Please provide your name.
   > Patrick Ryll
- Please Provide your email.
   > patrick.ryll@gcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Caregivers, Front End Engineer, GovernmentCIO

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDx/WdvBXWzaTZOBv6Qj7dKI5AQpWzhRaLO/vUCZLemlcdBroiMqF7jzLGfV/DN/VmdokgYjVbdwhIcvvXirP1w/+CF3aBLyZDvSV32DjAjBK72F0ckDnkJTt52xFxtzpu/bLAvxR+IvMI+wENYqX49k7MhF/buD/1iVnqlHLGcWxU2n4/lzUxBUVg7OdOBD5SRDU9RuwGVjh67olAXpLoAIlaJjuZVPYEl+Cn9wag/lqhyWjR46x0GjbMTErrzhF8Rhe7Cnj9JZXatOH6vKaud03jdsx1bJ0kVuF6ZEHUtzHTtbmST2KH2eIC0TScd3pzWzXz7vvEPu2EgaoeUYkHa/Ag7SU0jrm8vqVPVktDOR5SgKEG+odL9HXNz9lXEpQ6QBL3zbgWL5IkPMorFP1jOWGRUuvtw+EuySenp2WivksyPBcTEsIDaW2jqBsV2bWV1JNba8Unz3E2SVk2jZbbpvIc1jstDDQ+USbIEa3i1sna3FCvQ23vUpbZd+NJH4g8= patrickryll@pryll-C02ZJAHDLVDL.home
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
