### ISSUE TITLE
Change feature toggle flag names from camelCase to snake_case

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#29917]
Tim Wright of VSP FE Tools Group requested to update all VAOS feature flag names from camelCase to snake_case  in `FeatureFlagNames.js` file so the values match those in `features.yml`

The spreadsheet with the 15 VAOS flags that require changes are: https://docs.google.com/spreadsheets/d/1N0GJMa-PpLDMP-585Wd3KEC6QIHljueGRCgC6Qq3LXc/edit#gid=0

Examples of feature toggle flag names in `FeatureFlagNames.js` should  be:
vaOnlineSchedulingVariantTesting: 'va_online_scheduling_variant_testing',
vaOnlineSchedulingCCIterations: 'va_online_scheduling_cc_iterations',

**Comment by laurenernest** [comment]
@jenniemc this has already been reviewed and approved by VSP, right?

**Comment by jenniemc** [comment]
@laurenernest Yup, reviewed and approved by the VSP Front End Review Group, https://github.com/department-of-veterans-affairs/vets-website/pull/18727
