### ISSUE TITLE
Adding Beth Culp to DSVA Slack

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#29928]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add bethculp@navapbc.com as a full member.  Beth Culp is a new Designer joining Caseflow 9/20/21

**Comment by LizCallaghan** [comment]
done!
