### ISSUE TITLE
Adding Meko Hong to DSVA Slack

### ISSUE THREAD

**Issue by cgreim** [department-of-veterans-affairs/va.gov-team#29926]
Please add Meko Hong (meko.hong@adhocteam.us) as a full member. Meko is a new Product Manager on the VA Mobile App team with Ad Hoc.

**Comment by cgreim** [comment]
@LEHigley @KevinMHoffmanUSDS @LizCallaghan Hi all! Checking in - do you need additional information to approve Meko's slack access? @leanna-usds is our Product Owner if needed. Thanks!

**Comment by LizCallaghan** [comment]
does Meko have a VA.gov email address?

**Comment by ambikaroos** [comment]
Hi Liz - Meko is still doing her VA onboarding so she does not have a VA.gov email address yet. Hoping this is not a blocker to adding her to DSVA slack. She is now part of the VA Github Org, if that helps at all.

**Comment by LizCallaghan** [comment]
done!
