### ISSUE TITLE
Optionally hide the form title on the confirmation page

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#29929]
## Issue Description
On the confirmation page, some forms may want to disable displaying the form title. This should be configurable.

### Links
- [Original request in Slack.](https://dsva.slack.com/archives/CBU0KDSB1/p1631561301028600)
- [PR to an application to override the title](https://github.com/department-of-veterans-affairs/vets-website/pull/18702)

## Acceptance Criteria
- [ ] The confirmation page may optionally hide the form title
- [ ] Existing forms are unaffected by the change

## Possible implementations
- Add a `hideTitle` property to the `ConfirmationPage` component
  - The forms library then checks to see if that property exists (and is truthy) on the component before rendering the title
  - Pro: Doesn't add yet another yet another `formConfig` option
  - Con: Seems kind of awkward
  - Con: Breaks from the existing pattern of adding yet more options to the `formConfig` object
- Make the `confirmationPage` property on `formConfig` accept either a React component _or_ an object with the shape:
    ```ts
    confirmationPage: {
      component: JSX.Element,
      hideTitle: boolean,
    }
    ```

**Comment by rtwell** [comment]
This is a deviation from the pattern we use on all other forms and is unnecessary. Please revert, tyvm!
