### ISSUE TITLE
Unit Testing: Automate test coverage report

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#29938]
# Description
We are currently updating the Frontend Support Dashboard Unit Test Coverage Report manually once a month or so. We would like to have this happen automatically instead.

# Details
Most of the work for this has already been done (and then undone). This [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17848/files#diff-c6ff63d9fe07d20f6be6c10743321f1b97d35be902486ac2479cbc18a18f60a9R69) shows a daily upload version that saves the coverage report data to the vetsgov-website-s3-builds bucket. We can probably do this as part of the unit tests on master instead of a separate daily GHA job, as shown in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17970/files).

The one blocker here is that we need to submit a support ticket with Ops to add a CORS policy to the S3 bucket so that we can download the data and display it on the Frontend Support Dashboard.

**Comment by theodur** [comment]
@laineymajor This ticket should be good to close. This was completed by @timwright12 in this PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/787

**Comment by timwright12** [comment]
LOL, I forgot that was me
