### ISSUE TITLE
Unit Testing: Remove coverage report from logs and add failing test details

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#29937]
# Description
Since we have the coverage report details by application readily available in [two](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report) [other](https://github.com/department-of-veterans-affairs/vets-website/runs/3603031146?check_suite_focus=true) places, we no longer need it to display at the end of our unit test logs. It would also be nice to have some information at the end of our unit test logs about the tests that have failed.

# Details
Removing the test coverage table should be relatively straightforward.

The difficulty will be in figuring out why there is no information on passing or failing tests printing at the end of the log. The Mocha reporter we are using (unless another reporter is specified) is [Progress](https://github.com/department-of-veterans-affairs/vets-website/runs/3603031146?check_suite_focus=true), which should print at least the numbers of tests passed and failed at the end of the test run. This is currently not happening. We don't necessarily want to change the reporter, but we would like to have this information in the logs.

**Comment by timwright12** [comment]
Failing test details have been added to CI, but the coverage report is still there

**Comment by jhonnyoddball** [comment]
Expired. Closing
