### ISSUE TITLE
React pages should also have banners

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#29943]
# Description

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1631650897339000?thread_ts=1631633582.318600&cid=C52CL1PKQ

Notice how on [this page](https://www.va.gov/education/survivor-dependent-benefits/) the banner appears (it's not a React page, it's just a normal statically generated page). However, on [this page](https://www.va.gov/education/yellow-ribbon-participating-schools/) the banners do not appear (in fact, no metalsmith debug output is logged to the console for that page).

React pages should also render banners if there is one designated for its page or subpages.

## Hypothesis

We may want to compare these 2 files and see if we're missing the `banners` data from Drupal when we are constructing the react pages:

https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/plugins/create-react-pages.js#L17

https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/page.js#L305

It could be that we just aren't funneling drupal data to the react pages (and it might be as simple as including them in that react-pages file above).

**Comment by Rleahy22** [comment]
This should go out with Wednesday's (9/22) deploy. This page should have a banner: https://www.va.gov/education/yellow-ribbon-participating-schools/
