### ISSUE TITLE
[Tier 3] Disability Claim Issue with ref number 

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#29948]
## Issue Description
_Veteran experiencing issue when attempting to upload claim application._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Initials: A.C.

Issue: Cannot submit disability Claim application

ID: Not provided
reference number:  25b9d12f6eb44c2707e90a53

User Story: I've tried this for months and it is the same outcome. From what i was told my account was flagged and that is why i could not file anything and to call technical support to help me remove that flagged issue.

**Comment by annaswims** [comment]
user uuid: 4ab1b83a24c3473d90301d9931008633

we're getting an error from evss - we'll have to ask them why
ransaction_id	
vagov-b1833bc8-cb4d-4844-95ad-2deab09d0fcb
http://sentry.vfs.va.gov/organizations/vsp/issues/137/events/f70fc4bb16504329bb69b93b8a36724f/?environment=production&project=3&statsPeriod=14d

{"messages"=>[{"key"=>"form526.submit.establishClaim.serviceError", "severity"=>"FATAL", "text"=>"Claim not established. System error with BGS. GUID: 3817aff0-8a76-41bb-ab51-26e7432a6e78"}]}

**Comment by annaswims** [comment]
It seems that this was flagged for fraud.  Not sure where to go from here yet.  We don't have any contacts at VBMS (yet)
> The VBMS error is due to potential fraud. VBMS says: Please contact the System Administrator. Error is: GUIE50041&amp;FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!!  FILE: FABTInterfaceCreator.cpp  LINE: 350This update is being elevated for additional review due to an Incident Flash associated with this Beneficiary

**Comment by annaswims** [comment]
Possibly but not certainly the ebenefits contact center could help?

> Technical Issues, such as password changes or error codes
> 1-800-983-0937
> 
> Monday - Friday, 8:00 am - 8:00 pm ET

**Comment by annaswims** [comment]
asked EVSS for suggested next steps: https://dsva.slack.com/archives/C8R3JS8BU/p1631729177018900?thread_ts=1631719114.016700&cid=C8R3JS8BU

**Comment by Kimberley2019** [comment]
Thanks Anna, I'll find where this needs to go and report back to you any POCs for fraud.

**Comment by Kimberley2019** [comment]
Reached out to POCs with fraud department to see if they could assist.

**Comment by Kimberley2019** [comment]
@annaswims Not sure if this helps at all but this is what I was able to find out.

From: VAVBAWAS/CO/FRAUDINCIDENTTEAM <FRAUDINCIDENTTEAM.VBACO@va.gov> 
Sent: Friday, September 17, 2021 2:44 PM
To: Daniels,  VAVBAWAS/CO/FRAUDINCIDENTTEAM <FRAUDINCIDENTTEAM.VBACO@va.gov>
Cc: Johnson, 
Subject: RE: Flagged account preventing online submission

September 17, 2021

Good afternoon.

The Veteran should contact the Department of VA call center at 1-800-827-1000 and request his eBenefits account to be unlocked. The Veteran will need to complete advanced ID protocol. The call center will forward the request to BDP&R (our team) for processing.


Respectfully,

Kim Adams
Operations/Remediation Specialist
Benefits Delivery Protection & Remediation
Office of Financial Management
FRAUDINCIDENTTEAM.VBACO@va.gov

**Comment by annaswims** [comment]
That looks like good advice to me! Thanks!

**Comment by Kimberley2019** [comment]
Never heard back from veteran.
