### ISSUE TITLE
[BUG] - Broken PDF form link on Fry Scholarship content page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29961]
## What happened?
Broken link to PDF form on https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/4849fe00-ae5b-45e9-9143-a632e07687f9)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/
- Test User: N/A
- Scroll under Apply For Benefits heading and then to the fourth bullet.  That bullet references form 22-1999c, which results in a 404 error.

## Desired behavior
The correct form should be determined, and the copy & URL updated to reflect the right form.

## Acceptance Criteria
- [ ] Link is no longer broken, copy and Google Analytics tag contains correct PDF name.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MarciMcGuireGCIO** [comment]
@brianalloyd @bethpottsVADEPO please let me know if this needs to be assigned elsewhere.  Thanks!

**Comment by brianalloyd** [comment]
@lunascoop @RLHecht Can you all advise on what can be done if VBA owns this PDF.  Link:https://www.vba.va.gov/pubs/forms/vba-22-1999-are.pdf?_ga=2.18213945.1206357025.1555902018-524815269.1555902018

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO @brianalloyd After talking with folks at VBA we removed the link to the form and updated the language to explain where certifying officials can find it. I just published the page and will close the ticket when it's live on prod.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @RLHecht! We really appreciate it! 😁

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.

**Comment by brianalloyd** [comment]
Thanks @RLHecht appreciate the lift on this ticket.
