### ISSUE TITLE
Tweak Dashboard Dataset to Reflect Recent CC Process Change

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#29967]
# Description
We need to narrow the dataset we are displaying for the Collaboration Cycle Dashboard. Detailed information is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25770).

1. Change dataset to only involve these labels:
```sql
SELECT number, state, labels
FROM `vsp-analytics-and-insights.vsp_testing_tools.github_issues`,
    UNNEST(labels) as collab_cycle_feedback,
    UNNEST(labels) as practice_area,
    UNNEST(labels) as experience_standard,
    UNNEST(labels) as touchpoint
WHERE collab_cycle_feedback = 'collab-cycle-feedback'
    and practice_area in ('QA', 'IA', 'Content', 'Design', '508/Accessibility')
    and experience_standard like 'CCIssue%'
    and touchpoint in ('Staging','Midpoint')
```
2. Remove the `Open / Closed Issues by Team` card in favor of the alt view
3. Display a single donut card with open launch blocker, open non-launch blocker, and closed tickets

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/8bbfd3f3-97df-47ad-9492-66b733744b55)

**Comment by rjohnson2011** [comment]
Synced with Shira & Peter to discuss modifications. Desired outcome is 2 charts - 
1. Bar with Open Non-Launch Blocking, Open Launch-Blocking, and Closed
2. Donut with totals for Open Non-Launch Blocking, Open Launch-Blocking, and Closed

In the process of rewriting the queries and generating the new CC Domo page.

**Comment by rjohnson2011** [comment]
Here is the [CC Domo page](https://va-gov.domo.com/page/1340527018) with the above changes.

These stats are pulled from the dataset at the top of the ticket, which at the time of this writing is 130 records.

**Comment by shiragoodman** [comment]
hey @rjohnson2011 I have some feedback:

- Can we have the colors match from one graph to the next? Right now Closed is green in the first graph and blue in the second.
- I think you may have mixed up the labels. In the first graph (bar), there's 21 open/launch-blocking issues for Caregivers, but then in the 2nd graph (donut) there's only 3 open/launch-blocking issues total. Can you double check please?

**Comment by rjohnson2011** [comment]
@shiragoodman Nice catch regarding the labels! There was an issue counting multiples. I modified the SQL query and the numbers are now in line with [the data set](https://gist.github.com/rjohnson2011/dcf8f7b570cdfb1d6902c0d21e1cc6e6). Went through a few of the heavy-hitters like Education & eBenefits to verify accuracy. I modified the colors to be coordinated by status across both charts. [The latest.](https://va-gov.domo.com/page/1340527018)

**Comment by pjhill** [comment]
Waiting on a review from @shiragoodman before we close this out.

**Comment by shiragoodman** [comment]
thank you @rjohnson2011 and @pjhill ! This is looking great. I am planning to review the current dashboard with @rroueche at our 1:1 later this week. I think for now, the dashboard is satisfying our basic needs. Any changes to the dashboard will be captured in a different ticket, so I think it is safe to close this. Thank you again for all your hard work!

**Comment by pjhill** [comment]
Awesome, thanks for the feedback. As you say, we will work additional changes under a new post-MVP ticket.
