### ISSUE TITLE
[10/07] Insurance Check 

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#29984]

**Comment by wamccarty** [comment]
/v1/sdec/insurance-verify/{stationNo}/{dfn}:
    get:
      summary: determine if a patient's insurance need to be verified
      operationId: getInsuranceVerify
      parameters:
      - name: stationNo
        in: path
        description: sta3n of VistA system; should match stationNo in bearer token
        required: true
        schema:
          type: string
        example: 600
      - name: dfn
        in: path
        description: vista identifier of patient from patient file (#2)
        required: true
        schema:
          type: string
        example: 123456
      responses:
        default:
          description: default response
          content:
            application/json: {}

example payload   /v1/sdec/insurance-verify/500/221
{
  "success": true,
  "severity": "",
  "responseStatus": 200,
  "message": null,
  "path": "/vista-api/api/v1/sdec/insurance-verify/500/221",
  "payload": {
    "NeedInsuranceVerification": {
      "YesNo": 1
    }
  }
}

**Comment by katieroach** [comment]
@wamccarty - is this in staging?  will this go to production?

**Comment by aschulhof** [comment]
Moved to https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/59
