### ISSUE TITLE
VAEC Network Egress Enhancement

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#2999]
## Background
We've noted that egress to the internet from behind the TIC causes trouble for a few use cases:

- For docker container builds, having to add the CA certs at build is a hassle since OS'es in the container can vary and in many cases, we only want to use what the vendor provides and not build a new container
- For builds of software, transit thought the TIC can be unreliable or slow when fetching dependencies which can slow down an already slow process even more and add brittleness

The proposed solution is to deploy a caching forward proxy service that would handle ssl on-loading for TIC traffic with the VA CA's and cache data so repeated builds would not have to egress at all.

Config on clients would be with standard HTTP_PROXY headers.

## AC 
- [ ] Deploy a caching forward proxy 
- [ ] Handle ssl on-loading for TIC traffic with the VA CA's
- [ ] Min used by Jenkins, max used by all systems reaching out to the internet

**Comment by dginther** [comment]
No longer necessary, with new infrastructure.
