### ISSUE TITLE
Analytics Feature Request/Bug Report

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#29990]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - I am the Product Analyst on the AFS-Education team. We received the request from EDU

- Is this a feature request or a bug?

  - [X] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature

Looking for some metrics regarding Education form 22-1990 (Ch33 applications):

1. Number of CH33 applications submitted through current online form (https://www.va.gov/education/how-to-apply/) 
2. Number of users completing CH33 application in authenticated view versus unauthenticated (https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction) 
3. Time to complete CH33 applications through manual online form (https://www.va.gov/education/how-to-apply/) 
   --Broken out by authenticated & non-authenticated submissions
4. Number of login sessions to complete CH33 application through manual online form (https://www.va.gov/education/how-to-apply/) 
    --Assuming this can only be tracked via authenticated users
5. Number of users that start application in current authenticated experience, but do not complete (https://www.va.gov/education/how-to-apply/)
    --Assuming this can only be tracked via authenticated users
    --Is there a way to see at which page they don’t return / stop?

- Why the feature is needed

This is a request directly from our EDU partners, who are doing some work with the AFS chatbot development team and they have asked for these specific data points. 

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
The request is for data from the past 12 months, so starting in October 2020 through current.

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Thanks @ERRonat0609.

We'll start looking into these.  In the meantime, can you make a copy of this spreadsheet and fill out the "Forms" sheet for all the forms you want to track in the Domo forms dashboard?

https://docs.google.com/spreadsheets/d/1dIh-MVmVYCc2mZ_b_8y-cPVZB5-8RIShuOP_ng9uqAA/edit?usp=sharing

Let me know if you have any questions.

**Comment by ERRonat0609** [comment]
ok, @bsmartin-ep I just got approval from EDU to do that but it might take awhile to get that back to you - there are quite a few forms that we maintain...

**Comment by bsmartin-ep** [comment]
Hi @ERRonat0609 -

Some initial metrics I've culled from BigQuery.

------

> Number of CH33 applications submitted through current online form (https://www.va.gov/education/how-to-apply/)

COUNT 'edu--submission-successful' events over 2020-10-01 and 2021-09-23

224,350

------

> Number of users completing CH33 application in authenticated view versus unauthenticated (https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction)


COUNT sessions with 'edu--submission-successful' preceded in session by 'login-success' event over 2020-10-01 and 2021-09-23:


152,331 / 224,350 = 67.9%

------

> Time to complete CH33 applications through manual online form (https://www.va.gov/education/how-to-apply/)
--Broken out by authenticated & non-authenticated submissions

**AVG with preceding login:**
1790.796847619 seconds

**AVG with no preceding login:**
1516.991762887 seconds

------

> Number of login sessions to complete CH33 application through manual online form (https://www.va.gov/education/how-to-apply/)
> --Assuming this can only be tracked via authenticated users

So we would want to count the number of sessions between the initial visit to the introduction page and the eventual successful submission of the form?


--------

> Number of users that start application in current authenticated experience, but do not complete (https://www.va.gov/education/how-to-apply/)
> --Assuming this can only be tracked via authenticated users
> --Is there a way to see at which page they don’t return / stop?

Do you have a list of form URLs I can drop into a GA funnel?  Or are their no variations / alternate paths and I could just walk through the app on staging?

**Comment by ERRonat0609** [comment]
@bsmartin-ep 
Thanks for these. I am following up on your questions, and will respond ASAP.

**Comment by ERRonat0609** [comment]
@bsmartin-ep 
Regarding the list of form URLs - you should be able to walk through it in staging. To my knowledge there are no alternate paths, but here is a list of URLs that I went through this morning.

https://staging.va.gov/education/apply-for-education-benefits/application/1990/introduction
https://staging.va.gov/education/apply-for-education-benefits/application/1990/benefits-eligibility/benefits-selection
https://staging.va.gov/education/apply-for-education-benefits/application/1990/benefits-eligibility/benefits-relinquishment
https://staging.va.gov/education/apply-for-education-benefits/application/1990/military-history/service-periods
https://staging.va.gov/education/apply-for-education-benefits/application/1990/military-history/service-periods
https://staging.va.gov/education/apply-for-education-benefits/application/1990/military-history/military-service
https://staging.va.gov/education/apply-for-education-benefits/application/1990/military-history/rotc-history
https://staging.va.gov/education/apply-for-education-benefits/application/1990/military-history/contributions
https://staging.va.gov/education/apply-for-education-benefits/application/1990/education-history/education-information
https://staging.va.gov/education/apply-for-education-benefits/application/1990/employment-history/employment-information
https://staging.va.gov/education/apply-for-education-benefits/application/1990/school-selection/school-information
https://staging.va.gov/education/apply-for-education-benefits/application/1990/personal-information/contact-information
https://staging.va.gov/education/apply-for-education-benefits/application/1990/personal-information/secondary-contact
https://staging.va.gov/education/apply-for-education-benefits/application/1990/review-and-submit

**Comment by ERRonat0609** [comment]
@bsmartin-ep 
> So we would want to count the number of sessions between the initial visit to the introduction page and the eventual successful submission of the form?

I have verified that yes, this is what they are looking for, Thanks!

**Comment by bsmartin-ep** [comment]
@ERRonat0609 -

> Regarding the list of form URLs - you should be able to walk through it in staging. To my knowledge there are no alternate paths, but here is a list of URLs that I went through this morning.

I dropped your pages into a funnel in GA:

https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361
(Click _Form 1990 Funnels_)

We can only do 10 steps per funnel so I split it up into 2 separate funnels.  

--------------------------
I noticed you added this step twice:

> `1990/military-history/service-periods`

-------------------

If you want to make changes - such as changing the time frame, adding segments, _etc_ - you can make a copy from the link above.  If you have more questions, we have Office Hours Tuesday 3:30 – 4:00 ET.

![image](https://user-images.githubusercontent.com/62304138/134752323-ae5f6d60-32a2-4f48-a446-91ab28b3f73c.png)

**Comment by bsmartin-ep** [comment]
> > So we would want to count the number of sessions between the initial visit to the introduction page and the eventual successful submission of the form?
> 
> I have verified that yes, this is what they are looking for, Thanks!

We _do_ get a `-form-loaded` event when someone restarts a form:

[:bar_chart: GA Report of these events](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=500&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22-form-loaded%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22application~2F1990%22,0%5D%5D/)

Would that work?
