### ISSUE TITLE
[FE] Notification Prefs: Refactoring frontend filtering

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29993]
## Background
Due to the various adjustments we've had to make to the notification prefs feature throughout the built, there's a bit of refactoring that needs to be done on the frontend related to filtering.

## Acceptance Criteria
- [ ] Remove duplicated logic re: notification group and item filtering; handle all filtering at the Redux reducer level and remove it from the complex Redux selectors.
- [ ] All existing Cypress tests still pass, ensuring nothing changed as far as the user is concerned: health care group should only be shown the patients and be the first group, the Rx-tracking item should be shown only to those who should see it, and the CTA to make a selection for "null" radio buttons should still work.

**Comment by erikphansen** [comment]
Merged. Nothing to really validate since this was just a refactor with no functional changes.
