### ISSUE TITLE
[FE] Profile: Modal is delayed in closing after remove contact info is confirmed

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29992]
## Background
As noted in [Liz's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27169#issuecomment-919634916) in 27169, there seems to be a delay on the modal closing after confirming removal. The modal shows the loading button, and then the `yes, remove my information` button re-appears and the modal stays open for several seconds before it closes.

https://user-images.githubusercontent.com/45603961/133499108-d1a6bcd0-cc86-44bb-b9dd-6e4dad83329e.mov

You can replicate this with test user 36.

## Acceptance Criteria
- [ ] Modal should close once loading state is complete on the button the user selected

**Comment by ajakabcin** [comment]
@tmitchellgcio Hmm I'm still seeing a delay in the modal closing after selecting "yes, remove my information". I get a thinking/spinning dial while the info is removed and then the buttons both reappear and the modal stays open for ~5 seconds. cc @andaleliz

**Comment by tmitchellgcio** [comment]
Sorry It's likely not deployed yet

**Comment by ajakabcin** [comment]
@tmitchellgcio do we have the PR number? then I can follow it in the [frontend support dashboard](https://frontend-support-dashboard.vercel.app/) to know when it's ready to look at. Thanks!

**Comment by tmitchellgcio** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/18734
sorry this one is not ready for validation. I made a mistake. The other PR is though, but not sure when it gets deployed

**Comment by ajakabcin** [comment]
Confirmed on staging - thanks @tmitchellgcio !
