### ISSUE TITLE
Test less used Promo modals to ensure functionality (NOT announcement promo)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30000]
## Issue Description
_Over the course of using promo banners several created modals have been less utilized and we want to test these modals to ensure they are still functional and relevant to promo offering as a step to migrate promo banners to CMS Drupal_

## Front end tasks
- Test all promo modals with the exception of "announcement promos"

## Acceptance Criteria
- [x] Provide an analysis on functionality and modal purpose 
- [x] Advise on any risk iso future migration to CMS Drupal

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
## VAPlusVetsModal

![image](https://user-images.githubusercontent.com/12773166/135104624-93ed4f69-3e68-40f5-a12c-680b58af98e4.png)

## Explore VA

![image](https://user-images.githubusercontent.com/12773166/135104917-aacb610f-04f4-4630-88dd-e7cfab6abdc9.png)

## SingleSignOnInfoModal

I couldn't get this one to render 🤔 This is its content:

```jsx
    <Modal visible onClose={dismiss} id="modal-announcement">
      <h1 className="vads-u-font-size--h3 vads-u-margin-top--2">
        Sign in once to access the VA sites you use most
      </h1>
      <p>
        {`Now when you sign into VA.gov, we’ll also sign you into MyHealtheVet${
          useSSOeEbenefitsLinks ? ', eBenefits,' : ''
        } and
        other VA sites.`}
      </p>
      <p>
        <strong>With a single sign on, you can:</strong>
      </p>
      <ul>
        <li>
          {`Track and manage your VA ${
            useSSOeEbenefitsLinks ? 'benefits and ' : ''
          }services with just one username
          and password`}
        </li>
        <li>
          Access the VA sites you use most without having to sign in each time
        </li>
        <li>Sign out of VA.gov and be signed out of other VA sites</li>
      </ul>
      <button type="button" onClick={dismiss}>
        Continue to VA.gov
      </button>
    </Modal>
```

**Comment by kelsonic** [comment]
CC @davidconlon @brianalloyd when you have time could you review the above comment and determine if we can remove these modals?

**Comment by kelsonic** [comment]
PR is up to remove the modal: https://github.com/department-of-veterans-affairs/vets-website/pull/18949

**Comment by kelsonic** [comment]
PR merged, will go out with daily today and then we can close if there's no bugs

**Comment by brianalloyd** [comment]
Completed work, closing ticket in support.
