### ISSUE TITLE
[CMS Preview Server] Sanitize all response values from the accessibility check 

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#3002]
It looks like HTML tags might exist in pretty much any value from the Axe Check. We should sanitize every property so that it renders properly.

### Example

http://preview-dev.vfs.va.gov/preview?nodeId=1013

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/3be48662-bf
50-4f2d-9fa8-4af347da12e8)

**Comment by ncksllvn** [comment]
will be resolved by https://github.com/department-of-veterans-affairs/vets-website/pull/11285

**Comment by 1Copenut** [comment]
Moving this to close. The fix in PR 11285 just shipped and has been tested on localhost with Chrome, Firefox, and Safari on MacOS.
