### ISSUE TITLE
[MCP] Create standard 404 error messaging content and design

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#30033]
## Issue Description
We need to create a 404 alert for MCP to show when something has gone wrong.

---
## Tasks
- [x] Create the content and design then upload to UXPin

## Acceptance Criteria
- [x] New 404 message uploaded to UXPin and linked in this ticket

**Comment by rileyorr** [comment]
The 404 message can be viewed on UXPin [here](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/142029940/simulate/sitemap?mode=i).
