### ISSUE TITLE
Promo Banner reset for all users (Dismissible)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30048]
## Issue Description
_Now that we've updated the Promo banner recently we need to ensure that it reappears for all users as some users may have already likely dismissed the banner and not cleared local storage. This will reset the experience for all users and allow them to re-dismiss the banner if desired.  This is not urgent and can go out tomorrow or Monday during the daily deploy._

## Front end tasks
- Ensure Promo banner appears for all users (despite having dismissed previously)
- Test to ensure Promo banner is working properly 

## Acceptance Criteria
- [x] Promo banner is reset for all users and have a new opportunity to view and dismiss as desired 
- [x] Not urgent and can go out with the next programmed daily deployment

**Comment by Rleahy22** [comment]
This should got out with today's deployment

**Comment by brianalloyd** [comment]
Validate and closing in support.  Thanks for working this so quickly Ryan.
