### ISSUE TITLE
[Platform Arch WG]: VA.gov Network Architecture

### ISSUE THREAD

**Issue by boris-ning-usds** [department-of-veterans-affairs/va.gov-team#30042]
### Topic

Network architecture of the TIC

### Summary

Network paths, how traffic flows, what are common blockers, etc.

### Status

Not Ready

### Points of Contact

@boris-ning-usds , @mchelen 

### Topic

- [ ] Frontend application
- [ ] Backend application
- [X] Network
- [ ] Other

**Comment by mchelen-gov** [comment]
Meeting notes 2022-01-12
va background
vamc list: https://www.va.gov/directory/guide/allstate.asp
facility list: https://www.va.gov/directory/guide/rpt_fac_list.cfm 
More History on VistA - https://worldvista.org/AboutVistA/VistA_History 

TIC references
https://www.cisa.gov/trusted-internet-connections
https://www.whitehouse.gov/wp-content/uploads/2019/09/M-19-26.pdf
https://www.doi.gov/sites/doi.gov/files/uploads/tic_ref_arch_v2-0_2013.pdf
https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/memoranda_fy2009/m09-32.pdf
https://csrc.nist.gov/CSRC/media/Events/ISPAB-JULY-2009-MEETING/documents/ispab_july09-donelan_tic-external-connections.pdf
