### ISSUE TITLE
[FE] - Profile: update direct deposit edit button style

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#30051]
Since the edit button is the primary action on this page, I think it should have the primary instead of secondary button style
![image](https://user-images.githubusercontent.com/55992116/133678368-591a49b0-6e1e-4b4e-b06d-01d729687824.png). That would also align with the pattern we have on other parts of profile

**Acceptance criteria**

- [x] Button has primary (blue) styling instead of secondary (white w/ blue outline)

**Comment by andaleliz** [comment]
@ajakabcin FYI just created this quick fix ticket, not sure which of our devs would tackle, and when. This isn't anything urgent.

**Comment by andaleliz** [comment]
@SKasimow this is an old ticket I found that wasn't assigned to anyone.

**Comment by SKasimow** [comment]
@andaleliz - thanks.

**Comment by SKasimow** [comment]
@andaleliz - is #30051 the related ticket you wanted to have linked here?

**Comment by jcatergovy** [comment]
@SKasimow ready for review in staging

**Comment by SKasimow** [comment]
@jcatergovy - validated with user #107 - thanks!
