### ISSUE TITLE
[repo migration]: Content

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#3005]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] UAT, remediation on documentation post-migration
- [x] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] ~PR for vets.gov-team~
- [x] Merge va.gov-team PR
- [x] ~Merge vets.gov-team PR~

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/13ObZdVhPMmF5775khXdbPciyymdJD9LvsCunkBaB-jE/edit#gid=0

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/3208

There is no deprecation PR in vets.gov-team since this is not a Markdown file.

**Comment by thatmattjohnson** [comment]
above PR reviewed and approved to merge

**Comment by johnpaulashenfelter** [comment]
@thatmattjohnson ready for UAT/SME

**Comment by thatmattjohnson** [comment]
UAT complete, no remediation required, content SME notified, closing issue
