### ISSUE TITLE
[FE] Profile: Remove SMS checkbox on Profile in production ahead of notification prefs launch

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30053]
## Background
The SMS checkbox on Profile that associated with mobile phone, giving Veterans' the ability to sign up for appointment reminders was going to be removed when we launched the notification preferences feature. However, to avoid issues with VA Profile's data migration of the backend, we need to remove that checkbox ahead of time. Otherwise Veterans could be checking that box in production and then once we are live with notification prefs on the frontend, their preference would not have been migrated over to the new feature.

This checkbox has already been removed on staging, however it needs to be deployed separately and _ahead_ of our frontend release/feature launch to take place in a few weeks.

<img width="764" alt="Screen Shot 2021-09-16 at 4 12 30 PM" src="https://user-images.githubusercontent.com/45603961/133679609-00f7b25d-97c7-4348-9675-ba7141f1adce.png">

## Tasks
- [ ] ...

## Acceptance Criteria
- [ ] the checkbox to "send me text message (SMS) reminders for my VA health care appointments" is no longer visible on production

**Comment by erikphansen** [comment]
This should be done right before VA Profile performs the settings migration.

**Comment by erikphansen** [comment]
I can't think of a way to validate this on prod unless we know of a Vet who has health care who used to see this checkbox. @ajakabcin feel free to close if you want.

**Comment by ajakabcin** [comment]
Roger - thanks @erikphansen !
