### ISSUE TITLE
Adding Nikola Savic to DSVA Slack

### ISSUE THREAD

**Issue by haivi** [department-of-veterans-affairs/va.gov-team#30062]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Request Descriptions 
- Please add nikolasavic@thoughtworks.com as a full member.

**Comment by LEHigley** [comment]
done
