### ISSUE TITLE
Limit number times vets-website will poll API for job status update, throw error to Sentry

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#3006]
## Background 

This issue was raised as an action item from this [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/edit/vets-api-latency-pm/Postmortems/2019-10-21-vets-api-latency.md). 

We should limit the amount of polling that the frontend client does when requesting job status. This will help to prevent client timing out on polling, and breaking the user experience. It will also allow operations to more precisely identify when there might be a frontend service degradation. 

##

**Comment by rianfowler** [comment]
Duplicate #2644
