### ISSUE TITLE
Adding David Johnston to DSVA Slack

### ISSUE THREAD

**Issue by haivi** [department-of-veterans-affairs/va.gov-team#30063]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- What channel(s) do they need to be added to? #long-covid

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add dajohnst@thoughtworks.com as a full member.

**Comment by LizCallaghan** [comment]
already in Slack

**Comment by zinalpatel09** [comment]
@LizCallaghan he used to be in slack about a year, but we need to re-enable his account.  Can you do that so he gets an email invite to join the DVSA slack?

**Comment by LizCallaghan** [comment]
done!
