### ISSUE TITLE
Lower polling time again on vets-website for retrieving claims status 

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#3009]
## Background

[Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/vets-api-latency-pm/Postmortems/2019-10-21-vets-api-latency.md) response actions included increasing the polling time for vets-website, and now we should revert those changes.

**Comment by alexpappasoddball** [comment]
@kfrz Can we close this one?
