### ISSUE TITLE
Adding Zinal Patel to DSVA Slack

### ISSUE THREAD

**Issue by zinalpatel09** [department-of-veterans-affairs/va.gov-team#30096]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

This request is to add Zinal Patel (zinal.patel@thoughtworks.com) as a Full member

Description:  Zinal Patel is a project manager for the Long Covid project. In order to do her job efficiently, she needs slack to help her keep up to date on any communication and activities for the project.

**Comment by LizCallaghan** [comment]
done!
