### ISSUE TITLE
Content Team Input for VSA Facilities Team

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#30092]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

### Background
VA Domiciliary (ex: [Tampa](https://www.va.gov/tampa-health-care/locations/tampa-va-domiciliary/)) and Community Living Centers (ex: [Miles City](https://www.va.gov/montana-health-care/locations/miles-city-va-community-living-center/)) currently exist as Facility pages. Both are being redesigned as program pages, using existing program page design patterns (ex: [Pittsburgh pain rehab program](https://www.va.gov/pittsburgh-health-care/programs/interdisciplinary-pain-rehabilitation-program/)).

### What we need help with
The prototype (see link to UXPin in Supporting Artifacts) for dom/clc program pages has a number of areas that need content input:

#### Intro paragraph
- Domiciliaries and Community Living Center pages will each have their own standardized intro paragraph. It's intended to be a brief general description of that the program is, and who it is for.

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/0b3e218c-e30a-43a6-aade-1f8133f763c2)

#### Admissions header and descriptive paragraph
- We need help with the title of this section, as well as the descriptive paragraph. Doms and CLCs have similar admissions processes, so the basic description can be standardized. Individual locations can add to it as needed later.

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/a3ebeaf4-57a8-4f36-89d0-dc7c1b004513)

#### Hours of operation description
- Doms and CLCs offer 24/7 health care, but hours for visitors, regular business stuff, are not necessarily 24/7. We need some descriptive sentence that conveys this.

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/09093221-a67a-44b4-9ecf-562cae7e1f8d)

#### Labels
- Need some input on labels for:
     - phone numbers
     - hours of operation (ie. "regular hours" and "health services hours")

Other text on the pages will be provided by the locations themselves, so we're seeking Content team input for things that will be standard across Dom and CLC pages.

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups: 
     - [UXPin mockup - mobile](https://preview.uxpin.com/a2b38a92d039129e71f5589e314742891dcfbb08#/pages/141558738/simulate/sitemap?mode=i)
     - [UXPin mockup - desktop](https://preview.uxpin.com/a2b38a92d039129e71f5589e314742891dcfbb08#/pages/141566020/simulate/sitemap?mode=i)
- Link to any epics/issues that may be helpful: [Wireframe iterations for Doms & CLCs - #28462](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28462)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Q4 pilot program page (not sure)
- Estimated staging review date:
- Content and IA work needed by: **9/24/21**

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VSA Facilities
-	OCTO-DE product owner: Dave Conlon (david.conlon@va.gov)
-	Product manager: Michelle Middaugh (michelle.middaugh@adhocteam.us / Suzanne.Middaugh@va.gov)
-	Designer: Nick Osmanski (nicholas.osmanski@va.gov)
-	Product/team Slack channel: [#vsa-facilities](https://dsva.slack.com/archives/C0FQSS30V)

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by nicko-amida** [comment]
@mmiddaugh Here's the issue for the Content team - will update with any feedback/changes from conversations we have this coming week.

**Comment by bethpottsVADEPO** [comment]
@mmiddaugh @nicko-amida First, I can't believe the name of this program hasn't been updated since the late 1860s. It's as far from plain language as you can get. 

I have some questions: 
1/ What does "enter a consult" mean? Is this an assessment of some sort that the Veteran is in need of housing? What form does it take? And where does the health care provider or social worker submit ("enter") it? Online or mailing paperwork somewhere?
2/ I can't tell from the content here if it's the health care provider or social worker who can also call directly or if we're saying that the Veteran can do this.
3/ Is it the same phone number for residents and non-residents to call--for health services and any other help that a non-resident would call about? So the line is open 24/7, but if you're a non-resident, whoever answers will ask you to call back during regular business hours?

Thanks! I can probably wrap up my feedback/edits pretty quickly after I get these answers from you.

**Comment by nicko-amida** [comment]
@bethpotts Thanks Beth! 
1) "enter a consult" means to officially request clinical services on behalf of a VA patient. Like if a health care provider or social worker requests medical services to be included as part of a patient's treatment. This [CONSULT PROCESSES AND PROCEDURES pdf file](https://www.va.gov/vhapublications/ViewPublication.asp?pub_ID=3230) has the definition under section 3g, along with other kinds of consults.
2) Sort of all of the above: health care providers, social workers, and Veterans can all call the line to start the admissions process, but obviously only health care and social workers can officially enter a consult.
3) There's a main domiciliary number ("Domiciliary phone" in the mockup), that both residents and non-residents can call - but, it's not available 24/7, only during regular business hours. The health care services themselves are available to residents 24/7, in-person, but the number is just a regularly accessible business hours number.

If you want to video chat to clarify anything else, just let me know.

**Comment by bethpottsVADEPO** [comment]
@nicko-amida Here are my suggestions--let me know if there's anything you want to touch base about. I'm including edits to the bullet points and the intro (wasn't sure if you were asking for intro edits, but I tweaked the language a bit). Do we have a SME who will verify the accuracy of this information before it goes live? Note that we've started to use the terminology "experiencing homelessness." ​

**Intro**
The Residential Rehabilitation Program offers residential and other health services for Veterans who are experiencing homelessness or at risk of becoming homeless. On this page, you’ll find contact information, learn about the health services this program offers, and find out how to get started with the admissions process.

**Eligibility and the admissions process**

To be a part of this program, you must meet all of these requirements:

- You’re registered for VA health care, **and**
- You’re experiencing homelessness, or at risk of becoming homeless, and want to work toward living independently, **and**
- You’re able to live independently and take your medications as prescribed, **and**
- You’re able to live safely with others in a residential setting

  If you’re eligible, your VA primary health care provider or VA social worker can contact us in either of these ways to start the screening and admissions process:

- Submit a request online (this is called a consult), **or**
- Call us directly to speak with an admissions coordinator

**Note:** As a Veteran, you can also call us directly to start the admissions process.

Be ready to share relevant medical and financial documents as part of the admissions process.

**Referrals**
This program doesn’t require a referral.

OPTION 1
**Hours of operation**
Monday through Friday, 8:00 a.m. – 4:30 p.m.

**Note:** If you’re a resident, you have 24/7 access to health care services at the domiciliary. 

OPTION 2
**Hours of operation**
Monday through Friday, 8:00 a.m. – 4:30 p.m.

**Health care services for residents only:** 24/7

**Comment by nicko-amida** [comment]
Closing this one, and moving forward with the new request [#30546 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30546)
