### ISSUE TITLE
COE - Wire API call for My COE page document upload and provide visual feedback

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#30093]
``` diff
- Needs API work first
```

## Description
As a user, I want visual confirmation that my documents have been successfully uploaded to LGY, or, I want to be notified that the upload failed and I need to retry.

## Considerations

1.  Though the UI for the document upload feature is complete as of [this pr](https://github.com/department-of-veterans-affairs/vets-website/pull/18558), work to connect to `vets-api` still needs to be completed. This needs to include making an API call to an endpoint in `vets-api` that can accept a list of documents.
1. Existing endpoints (`/v0/claims_attachements` and I think one other?) may not work because they rely on an existing claim ID to associate documents with.
1.  [Current mockups](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/141541271/simulate/sitemap) need to be updated to include visual feedback for when a user clicks `Submit uploaded documents`. Similar to form submission feedback. In another ticket.
1.  This can probably be divided into three tickets - Design, FE, and BE, since it's a task that encompasses all three disciplines. 

## Tasks
- [ ]

## Acceptance Criteria 
- [ ]

**Comment by jason-gcio** [comment]
this can probably be closed

**Comment by jason-gcio** [comment]
see if this may have been for the standalone uploader

**Comment by jason-gcio** [comment]
sprint 68? due by march 3

**Comment by jason-gcio** [comment]
dupe 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37810
