### ISSUE TITLE
Define and implement revproxy based url for external Sentry integration

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#301]
## User Story
As a triage team member, I need to access Sentry externally (not from within the internal network) so I can integrate GitHub issue tracking.

## Goal
We want to have publically facing urls so that we can integrate GitHub according to [Sentry docs](https://docs.sentry.io/server/integrations/github/).

It is possible to expose this, theoretically, according to @wyattwalter  / @wunderhund 

We should determine what risks or challenges are associated with this approach.

## Acceptance Criteria
- [ ] Identify any risks associated with this approach
- [ ] Public-facing URL is available (if determined to be viable)

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Do we want the Sentry UI exposed publicly, or the ability to receive webhooks?

**Comment by kfrz** [comment]
@wyattwalter  No need to expose the UI publicly at this time, we just need the ability to receive webhooks.

**Comment by kfrz** [comment]
This URL can be arbitrary in name - maybe something like `va.gov/sentry-hooks`
