### ISSUE TITLE
Update VA appointments content 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3010]
Page in question:
https://www.va.gov/health-care/schedule-view-va-appointments/

This ticket/task is associated with the ticket: [update static Appointments page for VAOS launch #2525](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2525)

There need to be updates in stages: 
1/Updates for now  - this ticket covers updates to be done now. [Jen]
2/Updates for around launch [Peggy]
3/Updates for after full roll out (around Jan 2020) [Peggy]

Per convo with Lauren Alexander and Peggy Gannon, we will make the relevant changes needed that came via Shawn Adams. 

Will include more details here - just getting ticket started. @Karak888  @lalexanderson-dsva @peggygannon fysa

**Comment by Karak888** [comment]
preview links to stakeholders and FYSA:  @RLHecht @peggygannon

**Comment by Karak888** [comment]
@peggygannon  for awareness.   @RLHecht: Please review and copy edit as needed, but please don't put in publish state until we hear go-ahead from stakeholders. 

Attached is the clean Word doc logging the changes, and also the messy original doc from Shawn Adams. Note: we are not making every change Shawn submitted, per my discussions and vetting with @lalexanderson-dsva . 

[Change log: VAOS-pre-launch-changes-110619.docx](https://app.zenhub.com/files/133843125/ae6060ea-f20f-4414-9c45-ed5b5700ea95/download)

[Shawn Adam's change request doc](https://app.zenhub.com/files/133843125/1dd9bd40-6279-4c31-b0bd-10fd84deb18a/download)

**Comment by RLHecht** [comment]
@jenniferlee-dsva @peggygannon I copyedited the Drupal preview page and everything looks good. I just made one change: I made the link about getting care from non-VA providers be the full sentence and deleted the punctuation at the end.
![2019-11-05_14-10-44](https://user-images.githubusercontent.com/48728214/68335104-d61e3b80-00a9-11ea-877b-96b7aabea32d.png)

**Comment by jenniferlee-dsva** [comment]
@RLHecht - This page can go into today's deployment queue.

**Comment by RLHecht** [comment]
@jenniferlee-dsva Page is now set to publish.

**Comment by Karak888** [comment]
This is closed as part of first iteration.  New changes in new ticket.
