### ISSUE TITLE
Change R&S top + bottom links to action links

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#30119]
# Description

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1631218372242100

We need to change the top and bottom links for the following R&S templates to use blue action links:

1. `basic_landing_page`
1. `checklist`
1. `faq_multiple_q_a`
1. `media_list_images`
1. `media_list_videos`
1. `q_a`
1. `step_by_step`
1. `support_resources_detail_page`

Currently we use a template called `button.drupal.liquid`, this should be renamed to `action_link.drupal.liquid` or something similar.

**Comment by kelsonic** [comment]
PR merged: https://github.com/department-of-veterans-affairs/content-build/pull/560

**Comment by brianalloyd** [comment]
Validated and closing, great work Kelson.  Thanks for jumping on this so quickly.
