### ISSUE TITLE
Slack notification channel

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#30111]
## Details

Placeholder to discuss whether it makes sense for notification to continue being sent to #devops_deploys or create a new channel for Github Actions

**Comment by timwright12** [comment]
Cataloging the standard alerts we're dealing with as the Release Tools Team:

- Daily production deploy, vets-website
- Daily production deploy, content-build
- master branch CI run, vets-website
- master branch CI run, content-build

**Out of scope alerts**
- content-release (CMS team)
- daily accessibility scan (QA team)
- vets-api-* (Console Services team)
- fwdproxy
- cms
- *-cluster
- unbound

**status-vets-website**

- Stand by, production deploy for vets-website coming up in...
- Successfully deployed vets-website to production... (does not exist)
- Production deploy for vets-website has failed!...
- vets-website master branch CI failed!

**status-content-build**

- "Stand by, production deploy for content-build coming up in..."
- Successfully deployed content-build to production... (does not exist)
- Production deploy for content-build has failed!
- content-build master branch CI failed!

**Comment by timwright12** [comment]
PR for vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/19943
PR for content-build: https://github.com/department-of-veterans-affairs/content-build/pull/919

**Comment by indytechcook** [comment]
Follow up to update content_release and broken links: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7664

**Comment by timwright12** [comment]
PR to add success message into vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/19955
PR to add success message into content-build: https://github.com/department-of-veterans-affairs/content-build/pull/921
