### ISSUE TITLE
Access for Giang Nguyen

### ISSUE THREAD

**Issue by giangnguyen2** [department-of-veterans-affairs/va.gov-team#30121]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Michael Lovejoy
- Please provide your name.
   > Giang Nguyen
- Please Provide your email.
   > giang.nguyen@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >Lighthouse API, Java Developer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMdz3U5jqbI6DYssLt5VKL4EH7hKAojweBasxFsvr0mc giang.nguyen@libertyits.com
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
