### ISSUE TITLE
Analytics Implementation or QA Support for [Authenticated Experience - Notification Preferences]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30128]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
GA Implementation

- Who is this request for?
     - DEPO Product Lead: @KevinMHoffmanUSDS and @Samara-Strauss 
     - Product Manager: @ajakabcin
     - Designer: @tressaellen
     - Frontend engineer: @erikphansen
     - Backend engineer: @lihanli

    
- What team/project is this work for?    
    Authenticated Experience, [Notification Preferences](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
    
- Provide the Domain where Google Analytics needs to be implemented
    va.gov/profile/notifications
    
- Please provide any upcoming deadlines or important milestones
    Targeting phased launch rollout in early Q4 (October)
    

- Please provide website interactions to Track
   [Notification Preferences Measuring Success](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md#measuring-success)

    _Design System components are automatically tracked. [Read more here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md#other-important-things) to see which Design System components are opt in or opt out. You do not need to specify on this ticket which components you are tracking unless you are opting in._

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Notification Preferences use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/notification-preferences-QA-use-cases.md)

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Notification Preferences use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/notification-preferences-QA-use-cases.md)

> Please leave the following blank

## Acceptance criteria
- [x] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of done
- [x] All appropriate issue tagging is completed
- [x] All AC completed
- [x] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by ajakabcin** [comment]
Hi @joanneesteban I just wanted to check in to see if there was any additional info you needed from us on this. Is it in flight or waiting in the queue? I see that this ticket says it's in the Icebox, but on your customer support board it says in progress. Thanks in advance for your help!

cc @Samara-Strauss

**Comment by joanneesteban** [comment]
Hi @ajakabcin - @laurensimpson14 is working on this/it should be in flight!

**Comment by laurensimpson14** [comment]
Hi @ajakabcin I want to confirm that I understand what you'd like tracked! You're looking for:
- How many accounts have a phone number saved
- How many accounts have the below highlighted sections _showing_
- What radio button is selected as the preference for each highlighted section when that section is showing

![image](https://user-images.githubusercontent.com/80417436/136030237-fd265d16-71b4-44d1-ae09-e02ec6d61746.png)

Is that everything? Is there anything that I'm missing?

**Comment by ajakabcin** [comment]
Hi @laurensimpson14! I believe we also need to track how many accounts have made at least one selection and/or no selections at all. That will help us track key result 3 here - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md#measuring-success

@Samara-Strauss  does that track with your thinking?

**Comment by Samara-Strauss** [comment]
@laurensimpson14 reviewing our [KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md#measuring-success), we are looking to track the following:

- How many profiles have a mobile phone number saved
- How many profiles have an email address saved
- How many profiles have made any kind of selection on the notification preferences page (so selected at least one of the radio buttons in the screenshot above)
- Percentage of successful saves from the notification preferences page (note: save happens upon selection of a radio button option, not upon clicking a "Save" button, so this may impact how you are able to track this metric)
- Percentage of successful retrievals of notification preference data from the backend

Please let me know if you have any questions about this. cc/ @ajakabcin

**Comment by laurensimpson14** [comment]
I checked with Brian and the way to track that is with an API call event (the same way it's done for direct deposit). Below is the code that needs to be implemented, and it can also be found [here in Confluence](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/API-Call-Events.1840808140.html). 

Started call: 
```
     event: 'api_call',
     api-name: 'View Claims and Appeals',
     api-status: 'started',
     api-latency-ms: 20000,
     api-request-id: "55d07138-4056-405f-b361-e03ef56a386e"
```

Successful call: 
```
     event: 'api_call',
     api-name: 'View Claims and Appeals',
     api-status: 'successful'
     api-latency-ms: 20000,
     api-request-id: "55d07138-4056-405f-b361-e03ef56a386e"
```

Failed call: 
```
     event: 'api_call',
     api-name: 'View Claims and Appeals',
     api-status: 'failed',
    'error-key': '500 timeout message'
     api-latency-ms: 20000,
     api-request-id: "55d07138-4056-405f-b361-e03ef56a386e"
```

**Comment by ajakabcin** [comment]
Thank you @laurensimpson14 ! We don't have access to confluence but I'll check with Erik - I imagine this is sufficient. If not we'll reach out for further guidance.

Thank you!

**Comment by michelle-dooley** [comment]
Completed all required tasks.  Brian mentioned he worked with team on remaining items regarding phone/email address (PII) feel free to re-open if needed.
