### ISSUE TITLE
Build additional info web component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#30136]
- [ ]  Build an additional info web component
- [ ] Identify existing additional info REACT  components that need to be migrated
- [ ] Announce the new additional info web component to all teams

**Comment by bkjohnson** [comment]
There's some initial discovery-based work done on this branch: https://github.com/department-of-veterans-affairs/component-library/tree/additional-info-bkj

This is copied over from a previous `web-components` based branch where I was exploring if the additional info component could be created without one of the React dependencies that `<AdditionalInfo>` has.

**Comment by caw310** [comment]
Staging review will be Dec 2.
