### ISSUE TITLE
Offboarding of [Jeff Barrett]

### ISSUE THREAD

**Issue by eunicegar** [department-of-veterans-affairs/va.gov-team#30134]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Jeff Barrett
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > operations and his last day was 9/17
- Please provide any type of access they may have and their GitHub username. 
  > ex: SOCKS, Pagerduty, Google analytics, etc.
  
 
## AC
 - [x] Remove from Slack
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @mchelen-gov

**Comment by bsmartin-ep** [comment]
No GA access.  Domo account archived.

**Comment by jbritt1** [comment]
Not found in VFS Team Roster

**Comment by jbritt1** [comment]
Not found in VA GitHub Org

**Comment by jbritt1** [comment]
No SOCKS, PagerDuty, Datadog, Sentry
