### ISSUE TITLE
Build modal web component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#30138]
## Description
Build a web component version of the React Modal component.

The React modal component uses `react-focus-on` to trap focus, disable scrolling outside of the modal and to hide all content outside of the modal to screen readers. 

This functionality can be implemented using:
https://github.com/theKashey/focus-lock to limit focus to modal
https://github.com/willmcpo/body-scroll-lock to limit scrolling to modal
https://www.npmjs.com/package/aria-hidden to hide everything outside of the modal to screen readers

## Acceptance Criteria
- [ ] Build a modal web component
- [ ] Add modal web component to Storybook
- [ ] Add tests
- [ ] submit component for [Staging Review](https://vfs.atlassian.net/wiki/spaces/DST/pages/1998192674/Staging+Review+process)

**Comment by k80bowman** [comment]
Closing in favor of #35255
