### ISSUE TITLE
Offboarding of Timothy Akampa

### ISSUE THREAD

**Issue by timothyakampa** [department-of-veterans-affairs/va.gov-team#30132]
# Description
Offboarding for **Timothy Akampa**

GitHub Username: **timothyakampa**
Team: **Covid Patient Manager**
Expected Last Day: **09/17/2021**
Company: **ThoughtWorks**

Has access to:
- Circle CI via GitHub
- Pagerduty (email: akampati@thoughtworks.com)
- Datadog (email: akampati@thoughtworks.com)
- Google Analytics (email: akampati@thoughtworks.com)
 
## AC
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multiple accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @mchelen-gov

**Comment by bsmartin-ep** [comment]
No GA or Domo access.

**Comment by jbritt1** [comment]
Not found in VFS Team Roster

**Comment by jbritt1** [comment]
No SOCKS, AWS, PagerDuty, Datadog, Sentry
