### ISSUE TITLE
Access for Matthew McCollum

### ISSUE THREAD

**Issue by mmccollum-va** [department-of-veterans-affairs/va.gov-team#30130]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Michael Lovejoy
- Please provide your name.
   > Matthew McCollum
- Please Provide your email.
   > matthew.mccollum@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse Team Axolotl, Senior Software Engineer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjmq+ijU0i5Sa9Ikw0INl8K1IxQj036gulUtRUBonEaS4zB5HESrV+9E6BDXAJ8D69fe3IxAht4k4bECiHdhP1i/svcEVU7js16jL4si3RAoDA7mm5ua17L3y7vqGnHt0U2JEZ23GrgGtZlSQw6ZFfbuqEaR4D90OmBRzFQJVTkLnkE6wHHeOvDgl1cKp243AmtIR8X46K4u1qFqQWYr8vKwV0Sx2Dy+wbB2sj/XlDPNjGXEKDEqbF7CqKkFte3MlLBudqXo+TGaztj2CBIaADhvhQ128h5fTOm81umDheo6obVy5armODHqByPnNCCTyGmxwhzNAoFwhmVR7Azy463V/aL/nR2MJzroko9vctrdYDeKs0c0fy/z8qPvMjFq5dS7ObAM2A0bY+qwRRGN3z+SBLqYtYGfMAh3qYB20hczJ/TFyy5Kxb7K2skosFNw4PyA3f0qpuXuYO8iBZY8VXIbGxSFeG5CqWLrYwQgVxU6ySfpzXfkvGtiTRqJ8sU+c= mmccollum-va@DESKTOP-3JTP0ML
```

- Grant AWS Console access?
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
