### ISSUE TITLE
VBMS Down for Maintenance

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30141]
## Issue Description
Receiving errors in Sentry for calls to the debt letters endpoint `https://api.va.gov/v0/debt_letters` stating VBMS is down for maintenance

VBMS::DownForMaintenance V0::DebtLettersController#index

Sentry: http://sentry.vfs.va.gov/organizations/vsp/issues/20789/?project=3&query=is%3Aunresolved+source%3Ayour-debt&statsPeriod=14d

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Adding future work to capture more detailed exception on Sentry 

https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/35935
