### ISSUE TITLE
[Monitoring and Alerting] Documentation for Adding PagerDuty Integration in Datadog

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30152]
## Description
As a user of the Datadog documentation published by the Operations team, I need to know the steps for adding a new PagerDuty integration in Datadog.

## Background/context 
https://dsva.slack.com/archives/CJYRZK2HH/p1631889183033900 

---
## Tasks
- [x] Add steps for adding PagerDuty integration in Datadog to [existing doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting)

## Acceptance Criteria 
- [x] Steps documented in referenced doc explaining the final step to adding the PagerDuty integration to Datadog

**Comment by jhouse-solvd** [comment]
[This] (https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting#PagerDuty-and-DataDog-Integration) is looking good! 

Closing
