### ISSUE TITLE
Create design spec for typeahead drop down component

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#30197]
##  Description
Design to establish design specs for new typeahead drop down component

## Background 
- [Typeahead improvements made on header](https://docs.google.com/presentation/d/1re7s91M3Yi-qdXMXyvmMBiTIWbFczn6bZAM_zDN4CgA/edit?usp=sharing)

## Acceptance Criteria
- [x] Establish design specs to for front end to ensure that drop down component follows designs consistent with the typeahead implemented in header
- [x] Work with accessibility team and make changes to improve typeahead for low vision users

**Comment by mgleo** [comment]
Designs for typeahead on search results page.  @srsuddath 
Accessibility updates: Typeahead selection background will change from light blue to primary blue (#0071bb) for users with low vision.

![typeahead-search-results-desktop.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/5561eb2f-aa79-4697-ba3f-45802e180cac)![typeahead-search-results-mobile.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/39ba7bc7-9b7c-4451-bdd0-0bca1e91ff46)
