### ISSUE TITLE
Burials rewriting: Veteran burial in a private cemetery

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3019]
@DanielleSoCompany commented on [Tue Jun 11 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18931)

## User story

As the family member of a Veteran whose burial will take place in a private cemetery, I need to know what burial honors, memorials, and benefits are available and how to apply.

### IA details
- **URL:** /burial-in-private-cemetery/
- **Spoke:** More resources
- **Order:** 5
- **Left nav label:** Burial in a private cemetery

### Content details
- **Source pages:**
  - https://www.cem.va.gov/cem/burial_benefits/private_cemetery.asp
  - https://vagov-content-pr-137.herokuapp.com/burials-memorials/memorial-items/headstones-markers-medallions/ (see the subsection titled "What do I need to know about burial in a private cemetery?") 
  - https://www.cem.va.gov/cem/hmm/order_instructions.asp
  - https://www.cem.va.gov/cem/hmm/apply_by_fax.asp
- **SEO keywords:** private cemetery
- **What's needed:** 

- [x] Create a new page in the VA.gov voice/style about benefits related to burial in a private cemetery. 

- [x] Include on this page information about applying for headstones/markers/medallions for a private cemetery, and create appropriate crosslinks between this and the main headstones/markers/medallions page.

- [x] Add a link/label to this page on the burials and memorials hub page.

- [x] Write page meta description.

**Note:** We do not need to link to [VA-NCA-IS-1 Interments in VA National Cemeteries](https://www.cem.va.gov/CEM/pdf/IS1_Jan_2011.pdf) as featured on the legacy page.

## Steps to completion

- [x] Draft page and build in Github @lillianjwarner 
- [ ] Review/edit page @bethpotts  
- [ ] 2nd review/edit if needed @DanielleSoCompany 
- [ ] Package rewriting instructions and send to SMEs @DanielleSoCompany 

---

@lillianjwarner commented on [Wed Jun 12 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18931#issuecomment-501472486)

@DanielleSoCompany  - Ready for your review :) 

---

@DanielleSoCompany commented on [Fri Jun 14 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18931#issuecomment-502109952)

Hi @lillianjwarner. Thanks so much for this!

Here's some feedback/additional direction stemming from evolving IA and coordination of this piece of the work with the parity work. Just let me know if you have any questions. Thanks!

### IA

We're moving this page under Eligibility now. So the url will be:
/burials-memorials/eligibility/burial-in-private-cemetery/

### Content

Would like to reorganize the questions a bit under relevant h2s, as below, just to help the user quickly get to exactly what they need. Additional, specific notes on a few questions also below.

[h2] **Memorial items**

[h3] Is a Veteran buried in a private cemetery eligible for memorial items?

**Note:** Because the information about applying is the same as on the main Headstones, Markers, Medallions page, with parity work, let's pull that detail out here and just link over to the HHM page.

[h3] Is a family member buried in a private cemetery eligible for memorial items?

[h2] **Costs**

[h3] How much does a burial in a private cemetery cost?

[h3] Can VA help with the cost of a Veteran's burial in a private cemetery?

**Note:** Revised question to speak to the need of getting help with the cost of burial, since the user may not know to call this a "burial allowance." Then we can introduce the idea of the allowance and link over to that page for details (as you have the link there).

[h2] **More information about burial in a private cemetery**

[h3] What questions should I ask to prepare for a private cemetery burial?

[h3]  What should I do if I applied for a memorial item for a Veteran buried in a private cemetery, but the grave is still unmarked?

[h3] What can I do if I have a complaint about a private cemetery?

 

---

@lillianjwarner commented on [Tue Jun 18 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18931#issuecomment-502216549)

@DanielleSoCompany noted! these changes have been made. Only have one question:

- I think I captured this note: 

"[h3] Is a Veteran buried in a private cemetery eligible for memorial items?

Note: Because the information about applying is the same as on the main Headstones, Markers, Medallions page, with parity work, let's pull that detail out here and just link over to the HHM page." 

--but wasn't sure exactly which detail to pull. 

**Note for SMEs:** re: non-Veterans--can you have a spouse's info engraved if it isn't at government expense but it's a VA-purchased headstone...? (see question "Is a family member buried in a private cemetery eligible for memorial items?")

---

@bethpotts commented on [Tue Jul 16 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18931#issuecomment-511681193)

Update: I performed a high-level edit on this, but it needs a more thorough edit before it goes to copyedit and then to stakeholders.

**Comment by RLHecht** [comment]
@AnneHurley This page is now built in Drupal for when it's approved from SMEs.
preview-prod.vfs.va.gov/preview?nodeId=2346

**Comment by AnneHurley** [comment]
@RLHecht  This is the page that the SMEs have asked for some rewriting since the processes have changed a bit. Will upload rewritten copy by EOD Wed.

**Comment by AnneHurley** [comment]
[Burials rewrites - SME feedback on Burial in a private cemetery](https://app.zenhub.com/files/133843125/e432d57f-e086-4cc3-81a4-25451808b074/download)
@RLHecht  These are pretty simple tweaks - sorry I couldn't just do them in Drupal myself. if you could also just check that that one link works, that would be great.

**Comment by RLHecht** [comment]
@AnneHurley I made the changes to this page in Drupal. The link is also now working. It won't work in the preview because the page isn't published yet but I checked that it is connecting to that records page with all the forms.

**Comment by AnneHurley** [comment]
@RLHecht  This is ready to publish when freeze is lifted.

**Comment by RLHecht** [comment]
This page has been published. I'm moving to validate and will close ticket when live on site. @Karak888 @AnneHurley

**Comment by RLHecht** [comment]
@mnorthuis Confirming that the IA for this page is still the same as originally listed above. The fifth item under More Resources in Burials. This page was pushed live so making sure it's in the right spot in the left nav.

**Comment by mnorthuis** [comment]
No, that is not correct, note Danielle's comment on June 14th, we moved this page to be a child under Eligibility and the corrected URL is noted.  It should be listed as a child under eligiblity on the left nav with Burial at Sea as another child

**Comment by RLHecht** [comment]
@mnorthuis Thanks for the info! This has now been moved under eligibility and I disabled the legacy page in the menu so that both pages wouldn't show up in the left nav.

**Comment by RLHecht** [comment]
This page is live. Closing ticket. FYI @Karak888 @AnneHurley
