### ISSUE TITLE
Documentation & Diagram | Entity Reference Fields

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#30194]
## Story

Provide updated summary write-up/bullets and diagram for use of Entity reference fields in Drupal.
- Include flow diagram depicting the systems affected and how they interact.
- Add footnote for screenreader
- Remove option 3 depicting with Drupal/TMS

**Comment by adamwhitlock1** [comment]
Docs and Diagrams here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content-localization/translation-recommendation-project/translation-report-artifacts
