### ISSUE TITLE
Create a new GitHub application for integration with Sentry

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#302]
## User Story
As a triage team member, I need a new GitHub application so I can install it in our Sentry operation.

See [docs](https://docs.sentry.io/server/integrations/github/).

## Goal
We should have a new GitHub application in the DSVA repo so we can add it to Sentry.

@lisac-usds can help with this. 

New app details:

GitHub app name: `dsva-sentry`
Homepage URL: `TBD`
User auth callback URL: `TBD`
Webhook URL: `TBD`

## Acceptance Criteria
- [x] New GitHub application created [here](https://github.com/settings/apps/new)

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lisac-usds** [comment]
details of the GitHub app we created yesterday:
- name: `VFS Sentry (WIP)`
- homepage url: http://sentry.vetsgov-internal/
- user authorization callback url: http://sentry.vetsgov-internal/extensions/github/setup/
- webhook url: https://dev.va.gov/_vfs/sentry/extensions/github/webhook/

**Comment by omgitsbillryan** [comment]
The GH App called `VFSSentryWebhook` was created here: https://github.com/organizations/department-of-veterans-affairs/settings/apps/vfssentrywebhook .  You must be an `department-of-veterans-affairs` admin or a "collaborator" on the app to view & edit the app's settings.

The webhook URL of `VFSSentryWebhook` is configured to send requests to `https://dev.va.gov/_vfs/sentry/extensions/github/webhook/`

**Comment by omgitsbillryan** [comment]
You may contact 
- @lisac-usds (`department-of-veterans-affairs` admin)
- @omgitsbillryan @kfrz (app collaborators)

With for admin permissions of the `VFSSentryWebhook` GH app.
