### ISSUE TITLE
Access for Suzanne Gray

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-team#30204]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Scott Mason
- Please provide your name.
   > Suzanne Gray
- Please Provide your email.
   > suzanne.gray@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >VA.gov CMS
   >Content Designer
   >CivicActions

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGauXFGnJWguR7f29OzuMnmDgW7t4U55yZ7me2SzErRZSGPL4qj8ZwO1WLIJlJzvuxrFIWFz5ohXuTQUYO8TY8xbglmzr9K+HkzSqIcHe8Cqvk+ylnYqe6Umfo77rIDcSDjffR0LsJ4qJde7i1PNPr9N2N763LXgpkDNL6vV0q7D7NcOXzGay/4TQfQFfwskJ2EPYIckHsd03WhXaN8FyQ2smkqljKAdBcezlxDuw0V9zRRHzMlxuM6RwLVJ/f7A/ZPz31puSXCkla0vhO7pn3o5f67iTyHTUzM0ju+ce+y4c4KULUGVbTO3VV4vrccp7UV9puWJwVBfmsF4N6sPy6oZlhFuZU9sgqt1CRPQLDe7Eay+MIEy7hjmqbdNwk0ZzIAGq/m2cki10+1SO9EqklW4wdRyoMDkSTC4rPzhsDVMUg5AHdRJ9OqZITBVKHxymk7r5rqaY+HCNEBdnNJTewl5Iw1sD7qMYZhZ9Yn9Fhd8DORzDj/8MIsdgXuURIp10= suzanne@Suzannes-MacBook-Pro.local

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by mleclerc00** [comment]
Hi @suzanne-gray 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
