### ISSUE TITLE
Burials rewriting: Find a Veterans cemetery

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3021]
@DanielleSoCompany commented on [Wed Jun 12 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18954)

![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/dace9cf3-c5c7-447d-840a-5b620a7d2158)![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/15818575-33d6-4ad2-92ef-2955bea485e1)## User

As a Veteran, service member, or other family member planning a burial or looking to visit a grave, I need to be able to quickly find a VA national cemetery, state cemetery, or other related cemetery.

### IA details
- **URL:** /find-a-cemetery/
- **Spoke:** Plan a burial
- **Order:** 3
- **Left nav label:** Find a cemetery

### Content details
- **Source pages:**
  - https://www.cem.va.gov/cem/cems/index.asp
  - https://www.cem.va.gov/cem/cems/doi.asp

- **What's needed:** 

- [x] Create a new page in the VA.gov voice/style that directs the user to information about the type of cemetery they're looking to find.

- [x] VA national cemeteries should be the feature. And for VA national cemeteries as well as state, territory, and tribal government cemeteries, we should now link to our VA.gov facilitator locator with cemeteries as default search. (_Note:_ We are confirming this w/ SMEs, but proceed for now).

- [x] The other external cemetery links can stay as external links.

- [x] Pull in the info on https://www.cem.va.gov/cem/cems/doi.asp as a subsection on this page.

- [x] Update the existing link/label on the hub page to link to this new page.

- [x] Write page meta description.

## Steps to completion

- [x] Draft page and build in Github @lillianjwarner 
- [ ] Review/edit page @bethpotts  
- [ ] 2nd review/edit if needed @DanielleSoCompany 
- [ ] Package rewriting instructions and send to SMEs @DanielleSoCompany 

---

@lillianjwarner commented on [Thu Jun 13 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18954#issuecomment-501897898)

@DanielleSoCompany --this is ready for review.

Questions:

- is keyword listed in original ticket correct? 
- didn't see any mention of tribal cemeteries in source text, but did see mention of this in hub link to "find a cemetery." is there another source page i should incorporate into this page?

**Comment by RLHecht** [comment]
This page is now built in Drupal: preview-prod.vfs.va.gov/preview?

**Comment by AnneHurley** [comment]
@Karak888  @jenniferlee-dsva  This is temporarily blocked while SME's have sent it to Andy to fix the location finder. Propose we do this in 2 phases. phase 1, take out the location finder tool and publish with a link to the list of cemeteries by state, and the 2, later, when locator tool is fixed, add that back to the page.

**Comment by MickinSahni** [comment]
PW Grooming: 
Closing this out as it'll be covered by FL team.
