### ISSUE TITLE
Offboarding of Amy Knox

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#30214]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Amy Knox
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Education Benefits Applications, UX Lead.  Last day: 9/20/2021 
- Please provide any type of access they may have and their GitHub username. 
  > ex: Google Analytics, Domo, Github (un: amyknox)
  
 
## AC
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multiple accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @mchelen-gov

**Comment by bsmartin-ep** [comment]
GA access removed.  Domo access archived.

**Comment by mleclerc00** [comment]
no socks
no pagerduty
no sentry
no datadog
no aws

https://github.com/department-of-veterans-affairs/github-user-requests/issues/8272

**Comment by mleclerc00** [comment]
Unable to edit VFS team roster since I don't have permissions to do so.  I have sent out a request for write permissions.

**Comment by jbritt1** [comment]
> Unable to edit VFS team roster since I don't have permissions to do so. I have sent out a request for write permissions.

Knocked this one out for you in the meantime while you await access to the roster.
