### ISSUE TITLE
Typeahead 2.0 Unit and Cypress tests

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#30224]
##  Description
Add unit tests to test the drop down component in all of its forms and functions

1. Component is keyboard navigable
- up arrow key
- down arrow key
- tab key
- enter key
- escape key
- home key
- end key

2. Component is click navigable
- click on a suggestion
- click on search button 

3. Component dropdown menu hides when no longer the focus
4. Component dropdown menu appears when the down key is pressed

## Acceptance Criteria
- [ ] Unit tests exist to test the components functionality, and they all pass (non-flaky)

**Comment by LindaLi123** [comment]
Blocked by Accessibility

**Comment by srsuddath** [comment]
Unit and Cypress tests have been created and updated
