### ISSUE TITLE
Access for Gaurav Gupta

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#30220]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Jeff Brauer
- Please provide your name.
   > Gaurav Gupta
- Please Provide your email.
   > ggupta@kindsys.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Check-in Experience, Software Engineer, Agile6/KindSys

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRONZVUZmu5+5qwYJt+KWq2bG4I9ITnbrPE/d1m2UXUxfTtBQ70MkHnKaCrnTaIxU8z9UH63GdRHM244lKV1u8p/4HCmZTAwQKucHpasjuyb3XqYnYFrL5tHi3GFgiUC8lkzNRWOVoYrE5RIOxH/joYmYYrNmdPkotyNWX7LT+JRacTNatwK0DzoKb7mJK7CJf95DvaYDW4t5eI6OrnwITcKt8uBGCJxGVAiPeB5uqpE/nWKHWTWC3CK9Z7raDqM5KlC6GLGbGJGqJyyRKr518jILY4IwG4uNEQ0qgFqLfogbCvrFSjw1K6oXpqNTgNjDzekQMZ6qQ6IR0Z4i6kpnU0miq0j/00knE0UJP1BfP+tAK4VGgGZBgPvqriTs6t4EZ2zFGnZJLmfPMfZ85UvzyLcURqiS0ONcCqEaIIpa3xw4UlsWpXv8+g8+jOY5wgeX7vHn0OBVP/IaKBb/lzeB1uJ43QYIOIVrDREzGALHNlDc0SBxuVMBPWr1GaoAfRsk= ggupta@Gauravs-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why?

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Gaurav Gupta
COR: Mary O'Toole
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @randomsync 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by mchelen-gov** [comment]
approved for AWS access 👍
