### ISSUE TITLE
Burials/Records rewriting: Veterans military discharge documents

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3022]
@DanielleSoCompany commented on [Tue Jun 18 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18997)

Legacy page: https://www.cem.va.gov/hmm/discharge_documents.asp

**New url:** /records/discharge-documents/
**What's needed:** Create this page as a page within the Records hub. Make more general, but with info about these documents being accepted for burial eligibility still worked in. Find a way to incorporate footnotes without having footnotes (ie, as discussed, there are multiple documents with the same footnote - consider grouping those under the note).

**Work in this PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/463

## Steps to completion

- [x] Draft page and build in Github @lillianjwarner 
- [ ] Review/edit page @bethpotts  
- [ ] 2nd review/edit if needed @DanielleSoCompany 
- [ ] Package rewriting instructions and send to SMEs @DanielleSoCompany 

---

@lillianjwarner commented on [Tue Jun 18 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18997#issuecomment-503336250)

@DanielleSoCompany ready for your review!

**Comment by AnneHurley** [comment]
@Karak888 @mnorthuis  Do I need to do anything more with this other than send the screen shots of the page, with its new URL, to the stakeholders? Heroku is https://vagov-content-pr-463.herokuapp.com/records/discharge-documents/

**Comment by AnneHurley** [comment]
@RLHecht  @jenniferlee-dsva  I did a copyedit pass on this page ^ and don't see any edits that are necessary. It's essentially a super large/long table. I would say it's good to go. I will add the Heroku link to my list of Drupal Prod/Preview links to send to SMEs. Sound ok?

**Comment by RLHecht** [comment]
@AnneHurley I just made a few minor copyediting tweaks. (hyphenated "active-duty" and lowercased "federal." I can build this page in Drupal and will send you the preview link when it's done.

**Comment by RLHecht** [comment]
@AnneHurley This page is now built in Drupal as well: preview-prod.vfs.va.gov/preview?nodeId=2354

**Comment by AnneHurley** [comment]
Sent preview link to SMEs 12/9/19

**Comment by AnneHurley** [comment]
@RLHecht  Ready to go live when freeze is lifted.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close once it's live on the site. @AnneHurley @Karak888

**Comment by RLHecht** [comment]
@mnorthuis I am confirming that the IA for this page is the same as what was originally put in the ticket as this was pushed live. I want to make sure it is in the right place in the left nav: records/discharge-documents

**Comment by mnorthuis** [comment]
That is correct, it should be the last item in the left nav and on the Records hub page.   Redirect request is tracked here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2216.

**Comment by RLHecht** [comment]
Thanks @mnorthuis . This has been added to the left nav under Records.

**Comment by RLHecht** [comment]
This page is now live on the site. Closing ticket. @AnneHurley @Karak888
