### ISSUE TITLE
[Research] Phase 1 SME Coordination for HRT Research Scheduling 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30231]
## Issue Description
Research ticket to work phase 1 of the proposed research [phased plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/usability/research-phases.md).  

## Acceptance Criteria
- [x] Coordinate with SMEs to determine research scheduling  
- [x] Solicit introductions to SMEs from team members, other SMEs

**Comment by cindymerrill** [comment]
Soni sent email introductions to SMEs, and 3 replied to me. Scheduled 3 SME interviews for next week.

**Comment by cindymerrill** [comment]
Drafted a conversation guide for the SME interviews, which start tomorrow morning.

**Comment by cindymerrill** [comment]
Conducted 2 interviews with SMEs today. Tomorrow I have #3. Hoping to hear back from other SMEs that I've been introduced to...

**Comment by brianalloyd** [comment]
@cindymerrill closing this ticket based on the scheduled and conducted SME interviews.

**Comment by cindymerrill** [comment]
I'm not done with Phase 1 SME interviews! I have another one today, and I may have more this week. Could this ticket stay open? Or do you want another version for this new sprint?

**Comment by brianalloyd** [comment]
@cindymerrill spinning up a new ticket to get after the remaining work during next sprint.
