### ISSUE TITLE
526 - empty ratedDisabilities array

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#30236]
When a veteran submits a for 526 with no rated disabilities but an empty rated disabilities array 
`"ratedDisabilities":[]` there is a  validation error. ratedDisabilities is not required to be present, but when it is it must have between 1-100 elements in the array.

[sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/6408/events/a8779314ca6e4362ab679ed979ad21d8/?project=3&query=user%3A%22id%3A72783af1aef0463893a118966c303a1a%22+&statsPeriod=14d)

````
[{code: 100, detail: form - The property '#/ratedDisabilities' did not contain a minimum number of items 1 in schema 6f2b7799-fa7f-5efd-816c-ba22ca9d7290#, href: None, id: None, links: [], meta: None, source: {pointer: data/attributes/form}, status: 422, title: Form The property '#/ratedDisabilities' did not contain a minimum number of items 1 in schema 6f2b7799-fa7f-5efd-816c-ba22ca9d7290#}]
--
````

**Comment by Mottie** [comment]
Fix merged... leaving this open for validation

**Comment by annaswims** [comment]
This should fix https://github.com/department-of-veterans-affairs/va.gov-team/issues/30221

**Comment by annaswims** [comment]
Wow! no validation errors in 2 days!
