### ISSUE TITLE
Send email alerts when "alert" content is published

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#3024]
## User Story or Problem Statement
As a content editor, I need an email alert to be triggered in under 10 minutes so others can know that emergency content has gone out.

## Goal
Stakeholders should be notified anytime emergency content gets published

## Acceptance Criteria
- [ ] GovDelivery's Bulletin API triggers an email when emergency content is published/deployed

**Comment by swirtSJW** [comment]
Stumbled upon this while looking for documentation.   This has already been implemented on both the CMS side and the front end build side.

This issue can likely be closed.
