### ISSUE TITLE
Adding Leah De La Costa to DSVA Slack

### ISSUE THREAD

**Issue by anerbovig** [department-of-veterans-affairs/va.gov-team#30256]
Good morning! We have a new Associate Product Manager starting this week with the VAOS team, Leah De La Costa. Please add her as a full member, and also auto-add her to the following channel:
- vaos-team

Thank you! If I'm missing any needed information to get her set up, please let me know.

**Comment by LEHigley** [comment]
@anerbovig what's the email address? thanks!

**Comment by anerbovig** [comment]
Oops, thanks Lacey! Her email address is leah.delacosta@adhocteam.us .

**Comment by LizCallaghan** [comment]
done!
