### ISSUE TITLE
[Content] - Review proposed alert content for profile

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#30265]
I audited our profile and found opportunities to improve our content.  [This mural board ](https://app.mural.co/t/vsa8243/m/vsa8243/1631668096417/8acd03935adaad54b1fae3483d057fcd3b044985?sender=lizlantz1528)contains screenshots and additional context/UX guidance for the alerts.

Danielle and I reviewed the alert styles and overall approach on 9/21/21.  In this ticket, I'd like to get content review for specific alerts.  The list below links to the doc where I'm outlining the change and proposed copy

- [Adding a confirmation alert when contact info or direct deposit info is updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#1-successfully-updated-contact-information-in-profile)
- [Identify verification alert](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#2-identity-verification) (for non-LOA3 users)
- [User is editing a section and attempts to edit another section without saving ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#8-user-is-editing-a-section-and-attempts-to-edit-another-section-without-saving)

**The edits to connected app alerts are more complicated:**
The UX for this currently displays a confirmation modal prior to displaying the success message. I brought copy from the existing success alert into the proposed modal (below) to make the success message more succinct.  For reference, here is the [existing confirmation modal](https://app.mural.co/t/vsa8243/m/vsa8243/1631668096417/8acd03935adaad54b1fae3483d057fcd3b044985?wid=0-1631669552076) and the [existing success alert.](https://app.mural.co/t/vsa8243/m/vsa8243/1631668096417/8acd03935adaad54b1fae3483d057fcd3b044985?wid=0-1631669463939)
- [User indicates they want to connect an app](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#9-confirmation-user-wants-to-disconnect-app)(proposed)
- [Successfully disconnected an app](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#5-successfully-disconnected-an-app) (proposed)

Danielle and I reviewed content for another alert related to fiduciaries; I created a separate issue to cover that (#30477)

**Comment by andaleliz** [comment]
@ajakabcin I saw your slack message - is there a timeline for this work? I had originally told Danielle it was "as you have time" since we pulled it from our backlog.

If this is time sensitive, can you note it here? Otherwise I think you could create your FE tickets and designate this issue as a blocker. Then once this is closed, we'll know we can move forward with FE.

**Comment by ajakabcin** [comment]
Thanks @andaleliz!  Not urgent at all. I just wanted to get the corresponding FE tickets created and fully fleshed out in the backlog before I go on leave which is still a bit out (mid-November). I'll move our "create implementation tickets" task out to a later sprint to allow time. However, I imagine content will need a bit of time to go through everything you've recommended since there's a lot of content there, so I don't want to wait too long for that. Maybe next sprint or the sprint after as a rough timeline to get a thumbs up on the content?

**Comment by andaleliz** [comment]
[The doc I created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md) will have the updated content once we hear back, so you don't need to put the exact content in the tickets themselves. Could you create the implementation tickets and just use the doc link?

If not, could you provide dates instead of sprints in case that's helpful to the content folks?  I'm not certain the content team is on the same sprint cadence as us.

**Comment by ajakabcin** [comment]
OH yes - good call I can def do that re the tickets.

And yes, sorry about that - how about a rough deadline of end of October to have the content ironed out?

**Comment by Samara-Strauss** [comment]
@andaleliz did Danielle have a chance to review? Wondering if we can move forward with work related to this ticket.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz @Samara-Strauss. I did get a chance to take a first pass through this, yes. My edits are in the GH file. I'll try to go back through tomorrow and give it a final look. Feel free to send any questions about edits to date!

**Comment by Samara-Strauss** [comment]
Thanks, @DanielleThierryUSDSVA! @andaleliz what are next steps on this?

**Comment by andaleliz** [comment]
As long as the edits are in the GH file, we can move forward with FE implementation @Samara-Strauss. Closing this out.

**Comment by Samara-Strauss** [comment]
Great! @andaleliz have FE tickets been created for this work? Just making sure there isn't anything else we need to do at this point.

**Comment by andaleliz** [comment]
@Samara-Strauss yes - [the doc I created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md) has the associated ticket numbers for each alert.

**Comment by Samara-Strauss** [comment]
Great! Thanks for closing the loop on this.
