### ISSUE TITLE
Access for Scott James

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#30264]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Malissa Lecrone
- Please provide your name.
   > Scott James
- Please Provide your email.
   > Scott.James@gcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Debt forgiveness, Sr Back-End Developer, GovernmentCIO
   

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHjmc5E6rruE2hJjKbZu246dXiIAAmLLAn961CdQ3NWE scott.james@gcio.com

```

- Grant AWS Console access?
  > YES
  - S3 for attachments and CloudFront for logs

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Scott James
COR: Mary O'Toole
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @ScottyRJames 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by jbritt1** [comment]
New SSH key: `ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDM8/RGeYwscRw04vivjZJ0HIhxWfFsmpKtMz6xTQs8jjzUzdR+oZo/Kp+mdXVRRyBhr/6In6qKtZwbTeOcHsSu/KN4UEgzwwxN+4pS2mRuPSzmH3T6B4PeL0Hs4EYkUTMMqxVkqlBY6F54nLW6B2E8b4F2BNLWPaCHs9cOLWlH9lojVgsA0wToAWmk3LtBjh28gesKp790Otwx4S7+wdG/7ZZ/lWOAS0xqThLsAn6Ocf98ER56Q4AjnpU1qMLOl/6ZRRUKsRGtTwtMnjgmFhDHi+45YkrLyBdyHY2+7AwoXRqpcFjPh+sEQkWcHIcKZ3UCBoxojZegrerCq6+ArnVWEsU6dLkVq1u59DPKahfSZ7wkS+TMTWPX72Obh2ccqgtB3E6+xLFO+WLCbs9q+xiUtKsPgNT/8ChkAtZOFVwykMBfnWfFkoMLHcdNjgyyVRaxckyf2GVkZ73mcGM/ary4Dot08Nmx97Mm7S+6PAuolhNzHp/7m1Svtn047KNNY1E= macbook@Macbooks-MBP-2`

**Comment by jbritt1** [comment]
Key updated

**Comment by jsgarmon** [comment]
new approval group: @department-of-veterans-affairs/operations-aws-approvers

User claims to have finished EQIP and retrieved PIV card already.

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by td-usds** [comment]
@jsgarmon and @jbritt1 AWS approved

**Comment by td-usds** [comment]
eQIP submission scheduled for 2022-JAN-11; holding approval until then

**Comment by td-usds** [comment]
Internationalization mistake, eQIP was submitted on 2021-NOV-01; approved

**Comment by jbritt1** [comment]
Temporary credentials passed to user at this time.
