### ISSUE TITLE
Harassment Reporting Tool - Ongoing content strategy and content design work

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30266]
_The Office of Resolution Management, Diversity and Inclusion (ORDMI) is the office in-charge VA Wide for processing complaints from Veterans and Employees for alleged Civil Rights Violations as well as for Harassment, Reasonable Accommodations, and other inappropriate behaviors while on a VA Site._

_In response to Section 5303 of the Deborah Sampson Act which is part of the Megabus Bill that was passed in January, and new congressional demands for action, a team of Presidential Innovation Fellows (PIFs) is scoping the feasibility of creating a secure, online reporting tool on VA.gov that would enable Veterans and VA employees to report alleged incidents about violations from Veterans and VA employees which occur while on a VA Site._

This is for Content needs for the long path to include, V2 Landing Page (with form mention), Intro Page and HRT Form Flow. Connected Discover ticket for more details can be found [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27438)

Tasks:
- [ ] Collaborate with Content team on Content needs for the HRT initiative 
- [ ] Content for Updated (Version 2) Static Landing Page with Form Mention 
- [ ] Content for Intro Page for form 
- [ ] Content for Form Flow design

**Comment by cindymerrill** [comment]
When will @callen2563 be on PTO and @sporeboy be filling in? Would it be helpful if I talked with Jim about the changes needed to the prototype?

**Comment by brianalloyd** [comment]
@callen2563 I'm going to remove this from Milestone and place in ready for when content is ready we can update and shelve appropriately.  TIA.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Is this ticket still viable? It's the only outstanding ticket on an old epic. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @FranECross! Oh my goodness, this is **old**! You can go ahead and close this. This ended up being a Drupal page and it's published and live on the site. Thanks!

**Comment by cindymerrill** [comment]
I remember working on this long ago, @DanielleThierryUSDSVA. What is the URL of the live page? Does it include an interactive tool? Or are you talking about [this page](https://www.va.gov/report-harassment/) that we worked on?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, @cindymerrill, I'm referring to the Drupal page. There has been no movement toward an interactive tool since the pause in 2021. @FranECross If you or Dave would prefer to put this in the icebox, definitely feel free to do that. But I'm definitely not tracking this ticket from 2021 at this point and have no issue with closing.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Thanks so much for the quick response! I'm going to close, and we can always open a new ticket if there's any movement in the future.
