### ISSUE TITLE
Content request from CTO Identity

### ISSUE THREAD

**Issue by jrahaghi1** [department-of-veterans-affairs/va.gov-team#30279]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
*OCTO is going to roll out Login.gov as a new credential option, so that users have a choice between Login.gov (public option) and ID.me (private option).
We'd like to develop and test plain language for our UI/UX as well as communications and outreach to users. We've begun user/usability research (initial session results below) and are planning more. Specific requests are below*

[Identity Authentication Discovery 9_2 (1).pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7206979/Identity.Authentication.Discovery.9_2.1.pptx)

## Supporting Artifacts
*1. Help and informational pages for Login.gov, similar to what exists for ID.me. Example:*

<img width="799" alt="How do I sign in to VA gov" src="https://user-images.githubusercontent.com/74215939/134265579-d48da80e-22ad-4442-9cf6-3039cb49744a.png">

<img width="957" alt="va govresourcesverifying-your-identity-on-vagov" src="https://user-images.githubusercontent.com/74215939/134265587-95cb610b-2e95-42ab-9596-9e8bf05abbe1.png">

*2. Updated language on right side of sign on modal. We'll test something similar to this in our upcoming session, but will drop the "which option is right for me"*

![VA VA gov Home Veterans Affairs](https://user-images.githubusercontent.com/74215939/134265661-63c1d383-fbb1-4fcc-9351-d32c34d53c5f.png)

*3. Language for deciding between credentials. This is what we have drafted right now to address what we've heard users would want to know"*

Login.gov (“The public’s one account for government.”) 
Government created and maintained credential 
Fully secure and compliant with latest Federal guidelines 
Allows access to all benefits, services, and information at the VA
 In use by other government agencies / one account to access many government agencies

ID.me ("Simplifying how individuals prove and share their identity online.") 
Private sector created and maintained credential 
Fully secure and compliant with latest Federal guidelines 
Allows access to all benefits, services, and information at the VA
 In use by other government agencies / one account to access many government agencies

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: First week in October for the modal language. We'll be testing that next

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: John Rahaghi @codyreinold-usds 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @shiragoodman @peggygannon. Saw that part of this work just came in for a midpoint review so making sure you're tagged on the related content ticket.

@rtwell looks like you might be doing a quick design intent sync on this. Beth and I are working on content. Do you want to sync up to make sure we're aligned on design before we provide content recommendations?

**Comment by shiragoodman** [comment]
thanks @DanielleThierryUSDSVA ! Design Intent is planned for Thursday 10/7. Invite should go out by end of day. @RLHecht will be invited by default, but if you'd like an invite too, please let us know.

**Comment by DanielleThierryUSDSVA** [comment]
Oh, perfect, thanks @shiragoodman! Yes, please add me and I'll try to attend if I can. If I can't make it, I'll follow up with Randi after.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @codyreinold-usds @jrahaghi1. Attached are drafts for updating the 2 relevant, currently live Resources and Support articles in support of Login.gov: [Signing in to VA.gov](https://www.va.gov/resources/signing-in-to-vagov/) and [Verifying your identity on VA.gov](https://www.va.gov/resources/verifying-your-identity-on-vagov/).

Documents:

- [Signing in to VA.gov_Adding Login.gov and MFA_draft_11.07.21](https://app.zenhub.com/files/133843125/9ad60ab1-f4f3-4c96-906c-15e24b278300/download)
- [Verifying your identity on VA.gov_Adding Login.gov and MFA_draft_11.07.21](https://app.zenhub.com/files/133843125/881587a4-2d51-44bd-afb5-a02957c0ec3c/download)

Updates related to Login.gov are highlighted. I've also worked in the multifactor authentication in here, based on the video content we partnered on (and linking to the video). 

You'll see that I've pulled in one specific question on Login.gov identity verification issues from the Login.gov help center. Could you review and let me know if there are other issues we should address here? And any other thoughts on this content?

Once you've reviewed, I'll ask @RLHecht to do a final copy edit and we can share with our strategic communications partners. Thanks!

**Comment by andaleliz** [comment]
Hi @DanielleThierryUSDSVA ! We have an FAQ on our Account Security page that essentially duplicates the content in the [Resources and Support Verifying Your Identity article](va.gov/resources/verifying-your-identity-on-vagov/). I'd like to link to it instead of duplicating content. Any ETA on when login.gov will be reflected on that page? I think that would be the 2nd bullet point above.

We're targeting to have our page updated next week so if it won't be done by then, I'll update the FAQ content to reflect what's in that 2nd bullet.  Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks for checking in, @andaleliz! 

Hi @jrahaghi1 @codyreinold-usds. Can you confirm when Login.gov will officially launch for VA.gov? We'll coordinate timing of publishing the updated resources & support articles with launch.

For next steps on those: I believe all of our conversations in the document comments are now resolved. I'll ask the content team to flow the changes into the Drupal articles and do a final copy edit. Who would you like us to share these with in terms of other Login.gov partners? I believe IT Strategic Comms, so I can share with Leslie. Anyone else?

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA John and Cody will definitely have the latest info, but FYI last I heard the launch date is 12/8.

**Comment by codyreinold-usds** [comment]
We are going to hold the release of Login.gov and it will not be launching on 12/8. IAM needs to resolve an issue and has yet to provide us with an updated timeline. Once we know more, we'll communicate the date.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much for the update, @codyreinold-usds.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Launch is on hold, but the articles are ready for copy editing and then flowing into the Drupal articles. Links to articles above.

**Comment by johnheirloom** [comment]
@DanielleThierryUSDSVA we met with Login.gov today, and we are good from our end on content. The actual release of Login.gov won't be until sometime in January at this point, more to come on a more definite timeframe.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome! Thanks so much, @johnheirloom! We'll be ready to publish whenever the launch is ready. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @jrahaghi1! @RLHecht Let me know when the updated draft content is all ready in Drupal and I'll review so that we're ready for the launch. Thanks!

**Comment by RLHecht** [comment]
No problem @DanielleThierryUSDSVA We have this slated for this sprint so Selina is going to input the copy and I'll copyedit it and check it against the original. We'll let you know when it's ready.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA In looking at the files in Sharepoint and the Drupal pages, we're trying to figure out what the source of truth is. You updated the Drupal content after the Word docs and there are some differences between the 2. Should we go with what's in Drupal? FYSA @psanders86

**Comment by DanielleThierryUSDSVA** [comment]
Hmm. Thank you for flagging, @RLHecht! I'll take a look and get back to you.

**Comment by jrahaghi1** [comment]
Hi All, Login.gov is still on track for launch on March 14, and available for all partners on March 18. Is there an update on these info pages?

**Comment by jrahaghi1** [comment]
Hi @DanielleThierryUSDSVA, thanks for the update. Let's plan for the first content release of the day on the 14th. Login.gov should be live by 9am. If anything changes we'll let you know. Thanks!

**Comment by codyreinold-usds** [comment]
@DanielleThierryUSDSVA Can we preview the content, just to do a final check / ensure nothing has changed since this was originally produced?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @codyreinold-usds. It's a little tricky to preview each individual Q&A because the changes won't show up in the broader content pages until we publish each individual Q&A. 

I think the best way to make sure there's nothing new we need to add/change in the content is to look at the Word docs:

[Signing in to VA.gov_Adding Login.gov and MFA_draft_11.07.21](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EXiX7F1R4btAqfCQ2TlRGzYBreO7pfUm2Mu0C1fd3JqO2Q?e=qdYyia)

[Verifying your identity on VA.gov_Adding Login.gov and MFA_draft_11.07.21](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/ETlNuOWO-ExDncyJS1YELRsBdrmXQ9SrV26MkGzGRZED-Q?e=d50ftW)

These are what the team is using to update/check the content.

**Comment by RLHecht** [comment]
Thanks, @lunascoop I reviewed all these pages and they are ready to go live on 3/14.

**Comment by RLHecht** [comment]
These pages are all published. Moving ticket to validate.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @codyreinold-usds @jrahaghi1! Just confirming that these pages are live. I also double checked the links to these pages from the sign-in screen and all is good. Thanks, and exciting to see Login.gov as an option there now!

https://www.va.gov/resources/signing-in-to-vagov/
https://www.va.gov/resources/verifying-your-identity-on-vagov/
