### ISSUE TITLE
Return to Clinic (RTC) Spreadsheet & SharePoint Site

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#30292]

**Comment by pcshah1026** [comment]
Shane to provide Paras with additional data for the spreadsheeets.

**Comment by lindsay-insco** [comment]
@Cmjones233 Please connect with @pcshah1026 to continue this card

**Comment by Cmjones233** [comment]
researching power apps consolidation to link to power bi

**Comment by Cmjones233** [comment]
currently consolidating all the completed files into a master for Justin to connect to.

**Comment by lindsay-insco** [comment]
@Cmjones233 email Shane spreadsheet

**Comment by Cmjones233** [comment]
Dashboard complete. waiting for feedback/review from team

**Comment by jwowk** [comment]
Here is the link to the new report:
https://app.powerbigov.us/groups/011812a5-f044-4bd7-a84b-2d736ea18ef5/reports/8e3172e7-5788-431c-813a-259abbe8b524/ReportSection?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf

Updates:
•	Merged all completed Excel files into a single shared file (restricted internally) and configured as dataset for report.
•	Removed duplicate entries and saved to a new file for reference (56 total).
•	Updated KPIs to be based on live dataset and filterable.
•	Grouped “Appointment Status” entries that did not respond correctly as “Other” and blank entries as “Unknown”.
•	Added “Additional Comments” column to “All” table.
•	7 stations data files are not shared. Working with POCs to grant access.
o	VISN 1 - 608
o	VISN 2 - 632, 561
o	VISN 7 - 534
o	VISN 17 – 740
o	VISN 22 - 678
o	VISN 23 – 636 (636A was unlocked and is currently in dataset)


RTC SUMMARY – 12/30/21
Stations Complete	105 / 111
Patients Reviewed	3327 / 3518
Adverse Events	7
Disclosures Required	5

**Comment by lindsay-insco** [comment]
3 sites left to give access

**Comment by lindsay-insco** [comment]
Data unlocked -final review by Justin

**Comment by Cmjones233** [comment]
waiting for additional info on unknown

**Comment by lindsay-insco** [comment]
Follow up with Dawn Smith @jwowk

**Comment by jwowk** [comment]
Dawn Smith completed her analysis and provided instructions for updating "Other" appointment status. Updates were made and Power BI report was refreshed. She is now contemplating sending remaining RTC orders with a status of "Unknown" or "In Process" for an update. Should have answer by 1/20/22.

**Comment by jwowk** [comment]
VEText RTC data efforts complete.
