### ISSUE TITLE
Remove imports dependent on the claims-status app

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#30306]
## Details
The claims-status app currently has other apps that import utility functions from it. We want to remove these imports so that the claims-status app can be built in a single app build without needing to build and run tests of the other apps.

The files that import from `claims-status` are listed in the [cross app import audit](https://docs.google.com/spreadsheets/d/1K2QtE9qQXS1uFnlKXzAIsGr9Grin5k5RzLsSreQosCU/edit#gid=0) as a note in the `Dependents` column.

## To Do 

- [ ] Remove external imports from the claims-status app.
- [ ] Verify that the claims-status app can be built in a single app build. See the `Testing single app builds in GHA` section in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29742#issuecomment-917303902) for instructions

**Comment by alexandec** [comment]
These components are part of a dashboard that displays claims info inside the personalization app:
- [src/applications/personalization/dashboard/components/ClaimsListItem.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/components/ClaimsListItem.jsx#L7): Imports helper functions
- [src/applications/personalization/dashboard/components/claims-and-appeals/Appeal.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/components/claims-and-appeals/Appeal.jsx#L4): Imports helper functions and constants
- [src/applications/personalization/dashboard/components/claims-and-appeals/Claim.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/components/claims-and-appeals/Claim.jsx#L5): Imports helper functions and constants
- [src/applications/personalization/dashboard/components/claims-and-appeals/ClaimsAndAppeals.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/components/claims-and-appeals/ClaimsAndAppeals.jsx#L18): Imports helper functions, constants, and actions
- [src/applications/personalization/dashboard/components/claims-and-appeals/HighlightedClaimAppeal.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/components/claims-and-appeals/HighlightedClaimAppeal.jsx#L3): Imports a constant
- [src/applications/personalization/dashboard/containers/ClaimsAppealsWidget.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/containers/ClaimsAppealsWidget.jsx#L8): Imports helper functions, constants, actions, and components
- [src/applications/personalization/dashboard/reducers/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/reducers/index.js#L1): Imports reducers

It probably doesn't make sense to pull the helper functions/constants/actions/reducers/components out of the claims-status app and into platform, just for this dashboard usage.

I don't see any imports from `claims-status` here, though it's listed in the spreadsheet:
- src/applications/caregivers/containers/ConfirmationPage.jsx

**Comment by alexandec** [comment]
@theodur Thanks! Since testing-tools took care of that last one, I'll consider this ticket complete.
