### ISSUE TITLE
Investigate adding logging levels / logging for troubleshooting 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#3031]
# Overview 

Application logging can assist with production / staging bug investigation. Use the HCA app as a test to demonstrate

- best practices for logging 
- logging tooling 
- how logging fits into a troubleshooting guide 
- how to use logging for anomaly detection 

# Potential tasks 

- do some research on application logging approaches (maybe timebox to a day)
  - https://www.scalyr.com/blog/application-logging-practices-adopt/
  - https://about.gitlab.com/blog/2019/07/23/anomaly-detection-using-prometheus/
- research logging tools 
  - https://www.npmjs.com/package/debug

**Comment by laineymajor** [comment]
closing as this has not been touched since 2019
