### ISSUE TITLE
Access for [Kanchanadevi Suriyamoorthy]

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#30328]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Jeff Brauer
- Please provide your name.
   > Kanchanadevi Suriyamoorthy
- Please Provide your email.
   > ksuriyamoorthy@kindsys.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Check-in Experience, Software Engineer, Agile6/KindSys

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDSMMfHTajntyImUENDMPW5dEZsiMyiSRXSM9MKtlXqge6y13w7ylrQ0v6/Q0YLwUOtTHliMx9+FTL3ByPaUXJMjxmyD9flqCSeVW1oLk1jXHaYKrkGCzBDyOukT3z4F03usgBut5dO1vshsiGjAKNA0RNjG5y6jS9K0WRepxKL3mhl+QIU0uxe5F7OuT5p9F3Saw0WRRac3C2FQ3Q3HxONkZFWB/iAUsbneDt/R9zU6N5dVsaecYODVNr3xcTX/LEC9MmkVLud0n64D1XQhJ9UqVFSaTKOpmh24PZgix4IjdCCY/O+iw5lyNEH/lxH3ymiULgZmxpgl1MNGTHFpvlHkxPyK3gtJNOxmf1JCyBp6nn0dlIQEBnx4+nhsbSq7RMKuKjn3iK5K67mVSFjnLd2XTMUMJOUvFwpD+MVwsRMIAbcxmg8g5CWdf5TwL9On/z57WgJa2ri57mW8Um8P7374pJQBXjSr6mv1lSW2GuWJft2WmwwbMZ1WkW9RmOAMFU= skanchana@Kanchanas-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES / NO
  - What AWS services do you need access to and why?

**Comment by omgitsbillryan** [comment]
**For AWS Access**:
User: Kanchanadevi Suriyamoorthy
COR: Mary O'Toole
Approval needed: @mchelen-gov

This GH user is part of the department-of-veterans-affairs GH org ✅

**Comment by omgitsbillryan** [comment]
Please update your issue with a valid ssh key. The current ssh key listed is not valid (it's the default value in the issue template).

**Comment by kanchanasuriya** [comment]
Sorry about that.  Pls find ssh key updated in the ticket

**Comment by mchelen-gov** [comment]
approved for AWS access 👍

**Comment by omgitsbillryan** [comment]
Access granted to socks and AWS
