### ISSUE TITLE
evaluate replacing pdftk

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#3032]
pdftk looks unmaintained and is built using a compiler technology that was EOL’ed in ~2009.
Evaluate the feasibility of alternatives.

https://dsva.slack.com/archives/CK1A20ZCK/p1572619122099900

**Comment by nathanhruby** [comment]
I opened  jkraemer/pdf-forms#75 as well in hopes that there is an easy answer.
