### ISSUE TITLE
🛑  [FE] Split the Birth Sex, Marital Status, and Race questions into separate pages on the 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30338]
## User Story

As a Veteran, I need to clearly answer the questions of Birth Sex, Marital Status, and Racial Category, in order to complete my application for VA Health Care.

Currently, Birth Sex, Marital Status, and Racial Category questions are all displayed on the same screen. In preparation for the upcoming new question of self-identifying gender identity and to align with our long-term goals of having 1 question per page, we want to split these existing questions into separate pages.

There will likely be a followup to improve the design of each question individually such as, for example, changing the Birth Sex question from a dropdown list to radio buttons and adding addition explanatory copy.

## Expected Behavior

- Birth Sex will have it's own page within the same chapter
- Marital Status will have it's own page within the same chapter
- Racial Category will have it's own page within the same chapter

## Acceptance Criteria

- [ ] Birth Sex successfully split into a separate page in the same chapter
  - [ ] Confirm no breaking changes due to schema mods. See: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/655/files#r746012525
- [ ] Marital Status successfully split into a separate page in the same chapter
- [ ] Racial Category successfully split into a separate page in the same chapter
- [ ] The data for the form submission remains consistent with original design
- [ ] Form data is successfully sent to the backend (and to the Enrollment System)
- [ ] Designer checks off via Review Instance before promoting to Staging/Prod

**Comment by Dene-human** [comment]
Please use the below for both content and design reference

- Birth sex (accordion [open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/pa70avR) and [closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rboLPk7))
- Gender (accordion [open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/VrVyr37) and [closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nRwYPad))
- Race, ethnicity, origin ([design/content](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/xr58PYJ))

**Comment by MickinSahni** [comment]
Patrick to sync with Mark re: promoting this work + feature flagging

**Comment by Dene-human** [comment]
Updating ticket to keep feedback in one place.

As per slack:
- Review instances received on 10/29 (Friday afternoon) for Birth sex, marital status, and race questions.
- Feedback given 11/1 (Monday)

**1. Order of the questions is incorrect**
- The correct order should be (birth sex, marital status, race)

**2. Race, ethnicity, origin (2 feedbacks)**
- There should be a period after “only” in "Information is gathered for statistical purposes only."
- The order of the answers should be in alphabetical order (see design)

**3. Marital status is a required question**

**Comment by MickinSahni** [comment]
@charCodelet to add in the PR for this work

**Comment by MickinSahni** [comment]
### Prod (unauth):
<details>
<summary>Birth Sex</summary>
- ![image](https://user-images.githubusercontent.com/13204473/142286489-5bfdcbdb-a8f4-417e-9699-567d3669e968.png)
</details>

<details>
<summary>Marital status</summary>
- ![image](https://user-images.githubusercontent.com/13204473/142286618-ab0017a9-0e86-413b-a4bd-bca99e2cbaea.png)
</details>

<details>
<summary>Ethnicity</summary>
- ![image](https://user-images.githubusercontent.com/13204473/142286680-40f170a7-64a1-44e4-8e3f-cb1fba1a5410.png)
</details>
