### ISSUE TITLE
Access for Dan Goodwin

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#30336]
# Instructions
1. Fill out **Description**
2. Change the **Title** to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your Vendor Onboarding Representative name. This is the person from the contracting company responsible for your onboarding process.
   > Jeff Brauer
- Please provide your name.
   > Dan Goodwin
- Please Provide your email.
   > dan.goodwin@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Check-in Experience, Software Engineer, Agile6/CivicActions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFljkDgPcjZgcHRX+9whZcTPhkTs/oG2z3qDO8GBkr6LDliZCcDdqUg7mk1sggK2HApepZ/XDfSSJJZeatay/8mElJzARDAvujjgcE0wWmcOtRHlQgx6qcUaioqLEuQY7CTb1wAmT1BfbivtdC3YqPDA0iKNPm6eTsQ94jrqddo6+pwbP4jjE9vZw56d8BkizoHZMBZrG1RdC0mz5wAZ/jqTVyrQpSQka2b/j3sXRbW7IJ4SR6fvAO5IwpPwfyTZN1CmX1UdnBJgVni76wcl0sin/pcsyfGtxg4LvMQ+XSyQg8Bf04GsSJgQ6kN6wMjPuadR1oJUnVfU88hqNPmTmZMrTeF9RE0WP0ISutWSrbrDtEhE8TKy+6PkWgt+4O4pd2A7UxVWTtaAD5SEbTdPBJpkzNsKo7I0yDJP3nzgQWvV/z/D7MVmqDvYpAp/Mgu/bJk/j7/mbMxyWt5KwX9xDsZuxTmhgpdhLoSbmMThofAN9eylNBeIFf9NesY3DmrME= dgoodwin@daniels-mbp.lan

```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why?

**Comment by sarahknoppA6** [comment]
@dcgoodwin2112 is this ticket still in progress/needed?

**Comment by mchelen-gov** [comment]
Closing as stale, please reopen if needed.
