### ISSUE TITLE
HLR v2 - Mockups

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#30339]
## Issue Description
In preparation for Design Intent Collaboration cycle touchpoint, update HLR mockups

---
## Tasks
- [x] Update mockups to reflect v2 changes outlined in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28113)

## Acceptance Criteria
- [x] Mockups updated, link provided to Ronnie
---

**Comment by kevinstachura** [comment]
All of the V2 changes (besides some items still pending based on recent conversations) have been put into a design:

https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6
