### ISSUE TITLE
[Design] Improve usability of Current Compensation question on 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30335]
## User Story

As a veteran, I want to clearly understand the information that I need to provide in the Current Compensation section of the online 10-10EZ form, in order to appropriately complete my application for VA Health Care.

Both our metrics and research have shown a lot of confusion and bailout on the Current Compensation section of the 10-10EZ. The purpose of this story is to find a way to improve the usability/understandability of this section of the form for those that must complete it.

## Acceptance Criteria

- [ ] New Design/Content adjustments

**Comment by Dene-human** [comment]
Hey @charCodelet did you accidentally close this ticket? I'm not done with it.

**Comment by Dene-human** [comment]
This question will be split into two questions:

- VA disability compensation ([design](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/Gmb5Gnb))
- VA pension ([design](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/OmZ5kWk)). This question is dependent on the VA disability question and will only be shown IF "no" is the response on the VA disability question.

The content is correct in the design. I will update the content source of truth when we are closer to development to avoid confusion.

**Comment by MickinSahni** [comment]
Standup 10/1: Finalized after meet with Danielle! Dene created FE tickets as well in Sprint 58

**Comment by Dene-human** [comment]
FE ticket #30794
