### ISSUE TITLE
Analytics Reporting Request for BAH-Team

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3034]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?
Request for Booz Allen team working with EDU on GI Bill Comparison Tool

Requested by Amy Knox

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._

- What team/project is this work for?
Request for Booz Allen team working with EDU on GI Bill Comparison Tool
    

## Timeframe for Analytics Requested
Ideal to have information back by 11/6

## Analytics to Track Down
Per Slack discussion with Nedie Recel, we'd like to learn more about authenticated v. unauthenticated user behavior within the GI Bill Comparison Tool 

Since this is our first request on this type of investigation, it would be ideal if we could get top-line findings this round.  Then, once we understand what's available and what the general info looks like, we'd submit a subsequent request. 

## Which Product Questions are you trying to answer?

How does behavior between authenticated and unauthenticated users vary in the GI Bill Comparison Tool, if at all. 

## Additional Comments
 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@amyknox Please see the link to the segment. The logic is to look for any sessions where a LOA 1 or 3 is present.  To apply this to your Google Analytics view, here are the steps:

1. [Click on this link in your browser](https://analytics.google.com/analytics/web/template?uid=Wtfhv9rIRImi0gQcSLiaTA)
2. It will open a screen, where you should input "Education Modernized" to find the right view:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/15ecfc05-d560-41e8-8bc4-c82c587a05a3)

3. Select the Production version and save.

4. Navigate to a report. At the top of a report, select "Choose segment from list":
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/44dadf69-5f59-4f95-a370-cad9b09908bc)

5. From here, you can navigate to different reports to see how authenticated vs. all users are utilizing the site. 

--
You can repeat this for the [Unauthenticated Sessions segment](https://analytics.google.com/analytics/web/template?uid=8O1iriHhTpyQZL1bUa3LWA)
