### ISSUE TITLE
[Design] Content and Copy for new Indian question on 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30349]
## User Story

As an Indian Veteran, I want to be able to indicate that I meet the definition of an Indian on the 10-10EZ, in order to apply for VA Health Care.

The purpose of this story is to update the initial draft design (ticket #28973) with user-friendly content.

## Acceptance Criteria

- [ ] New design/content

**Comment by Dene-human** [comment]
[Design with proposed content](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/xyJvv0/a/ygbAeZz/r/0xj2Me). Will need to wait for HEC approval.

**Comment by Dene-human** [comment]
[Design and content](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ygbAeZz)

Presented to HEC team on 9/29. Waiting for feedback.
