### ISSUE TITLE
Update COE Mockups to Account for New Doc Visuals

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#30355]
## Description
As a user, I want visual confirmation that my documents have been successfully uploaded to LGY, or, I want to be notified that the upload failed and I need to retry.

## Considerations
- Though the UI for the document upload feature is complete as of [this pr](https://github.com/department-of-veterans-affairs/vets-website/pull/18558), work to connect to vets-api still needs to be completed. This needs to include making an API call to an endpoint in vets-api that can accept a list of documents.
- Existing endpoints (`/v0/claims_attachements` and I think one other?) may not work because they rely on an existing claim ID to associate documents with.
- [Current mockups](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/141541271/simulate/sitemap) need to be updated to include visual feedback for when a user clicks `Submit uploaded documents`. Similar to form submission feedback, like direct deposit, with success/failure banners
- This can probably be divided into three tickets - Design, FE, and BE, since it's a task that encompasses all three disciplines. 

## Tasks
- [x] Update existing mockups

## Acceptance Criteria 
- [x] Mockups have been updated and shared with Team

**Comment by sporeboy** [comment]
View COE document uploader success screen: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/142354839

View COE document uploader error alert: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/142356339

Inline uploader alert messaging referenced here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26354

**Comment by sporeboy** [comment]
Potential error states:
- Connection error/We're sorry. We had a connection problem. Please try again.
- File too large/We couldn't upload your file because it's too big. Please make sure your file is smaller than 10MB and try again.
- Wrong file type/We couldn't upload your file because we can't accept this file type. Please make sure your file is a (Add acceptable file types) .pdf, .jpg, .jpeg, or .png and try again.
