### ISSUE TITLE
Migrate forms library to use alert web component

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#30361]
### Description

The forms library has one use of the `<AlertBox>` React component:

https://github.com/department-of-veterans-affairs/vets-website/blob/391fb283bd30fd5c859df4bf813b19aee27ae7f4/src/platform/forms/save-in-progress/DowntimeMessage.jsx#L14-L35

It would be good to replace that with a `<va-alert>` Web Component.

### Additional details/notes/links

This may be very straightforward depending on what kind of custom styling the `schemaform-downtime-after-steps` class brings.

### Acceptance criteria

- [ ] No `AlertBox` is used in the forms library

### What type of issue is this? 
- [x] Request update to existing feature

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by humancompanion-usds** [comment]
This has been done as part of the deprecation of React components:
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/save-in-progress/DowntimeMessage.jsx
