### ISSUE TITLE
Modify jenkins to trigger email alerts

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#3036]
Create a post-deployment step that runs a script if the deploy was successful. The script will be to trigger email alerts to be sent through Granicus. 

https://dsva.slack.com/archives/CPAKQN6DN/p1575393096032900

**Comment by nathanhruby** [comment]
See also #3024 and #2780

**Comment by nathanhruby** [comment]
I talked to @swirtSJW about this, the goal here is to be able to send notification emails *after* a vets-website deploys is done, where the email points at just deployed content. Use cases here are things like emergency notifications about VHA sites, updates, etc... 

CMS will handle interfacing with the email sending, etc..  but they need a "deploy complete" event generated via callback with a date of the contained CMS content so they can process the queue of pending events before that date.  XXX: ask about concurrency 

Basically we need to mod the jenkinsfiles for vets-website to fire a callback to a endpoint in cms, the process should look like:

- record the unix timestamp at, or very slightly before, the graphql query to CMS is made during the vets-website build process. (this may be racy, we may want to subtract a few seconds from this value, be sure to check/test this)
- persist that value across the various jenkins steps to the deploy step (ether via adding to BUILD.txt or by adding a jenkins parameter for it
- at the end of a successful vets-website deploy, do a HTTP GET request to `http://ENV.cms.va.gov/api/govdelivery_bulletins/queue`  with query parameter `EndTime` and the value we persisted in step 1.  For example, a dev url would be: 
```
http://dev.cms.va.gov/api/govdelivery_bulletins/queue?EndTime=1575478406
```
- on a non-successful build do not fire the endpoint
- if the api call fails, that should be noted (fail the job and maybe send a slack message?)
- it's ok to to hit the api endpoint on the every deploy, the CMS will dequeue jobs once sent

**Comment by nathanhruby** [comment]
so after some kerfluffle with getting basic auth enabled and url routing from non-vagov vpc's I think this should work now.

Process is
- vets-website adds the timestamp to BUILD.txt
- the `deploy-vets-website` role will build BUILD.txt after deploy
- the role will hit the http endpoint as the api user using basic auth and the GET query param

For now, we are ignoring errors on the api callback action, once we see this work in dev, stage and prod, we can either make that fail the deploy as well, keep ignoring it, or fire an additional notification someplace

**Comment by nathanhruby** [comment]
Prod shipped along with  department-of-veterans-affairs/devops#6129
