### ISSUE TITLE
List should pull facility operating status from system

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30395]
## Issue description
Currently, facilities listed on each [VAMC operating status page](https://www.va.gov/pittsburgh-health-care/operating-status/) must be added manually by an editor. Instead, they should be listed based on their `field_office`, which has a value that is shared with each Operating Status page, and should automatically be connected and not editable. This will ensure the list remains accurate without human intervention. 

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/134420455-43f80dde-cc05-4d2a-a7ef-d9f828b035e7.png)

</details>

**Exclude mobiles from this work due to pending changes for mobile clinics. Do not filter them intentionally** 

## Task
- Find out where data comes from (may be similar to query used to identify associated facilities for Locations page)
- Refactor operating status pages to pull facility status from system, rather than facilities hand-listed on Operating Status page
- Add tests

## Acceptance Criteria

- All Operating Status pages are pre-populated with the facilities that are associated with the VAMC system specified in `field_office`
- Main locations will appear first, followed by an alpha list of the other locations
- Removing a published facility from a VAMC system removes it from the associated Operating Status page
- New facilities associated with a VAMC system appear on the Operating status page
- Mobile facilities may or may not appear in this list

**Comment by mpelzsherman** [comment]
Validated in production:

https://www.va.gov/pittsburgh-health-care/operating-status/
https://www.va.gov/erie-health-care/operating-status/
