### ISSUE TITLE
[DISCOVERY] Yellow Ribbon - Work with Search engineer on how to implement typeahead/auto-complete

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#30394]
## User Story

As a FE engineer, I want to work with a Search engineer on how to implement typeahead/auto-complete so that I have some ideas on how we might implement that in the Yellow Ribbon search tool.

## Expected Behavior

- Spend up to 3 story points getting some guidance and technical info from a FE engineer on the Search team 
- Document your findings in the Yellow Ribbon product GH

## Acceptance Criteria

- [ ] Set up time to work with engineer on the Search team
- [ ] Document information learned during your collaboration session in the [discovery doc within the Yellow Ribbon product folder on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-yellow-ribbon-school/post-mvp-enhancements/typeahead/discovery.md).

**Comment by zacharymorel** [comment]
Met with Sam. 

Plug n Play, fully abstracted, will be done in a few months. 
As now, after the current component passes Collab Cycle, it will ready @ 90% for me to take and make some changes so we can use it.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel That is awesome!!
