### ISSUE TITLE
CC UC3: User Guide

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#30397]

**Comment by jwowk** [comment]
Create a user guide for Community Care Use Case #3 - Post appointment reminders

General admin settings guide is attached for reference. Focus on "Message Templates" and "Enabled Clinics" for how sites add/edit templates and then configure its use with a site. I have also attached the Community Care guide which is where these instructions will ultimately be added. The appointment reminder section is a good overview of how to configure the reminders as well. Post-Appointment reminders will be configured the same way.

[https://app.zenhub.com/files/133843125/984d2fb4-6a65-48f5-91d7-ec39c57dc081/download](https://app.zenhub.com/files/133843125/984d2fb4-6a65-48f5-91d7-ec39c57dc081/download)[https://app.zenhub.com/files/133843125/61f876d2-28e1-48ff-a673-2aaaa5b6001e/download](https://app.zenhub.com/files/133843125/61f876d2-28e1-48ff-a673-2aaaa5b6001e/download)

**Comment by vlivshin** [comment]
@jwowk, I've started working on the draft.

**Comment by vlivshin** [comment]
@jwowk, 1st draft is ready for your review.
[https://app.zenhub.com/files/133843125/64aade6e-39f0-44d5-96c9-8c1c3d8f2d48/download](https://app.zenhub.com/files/133843125/64aade6e-39f0-44d5-96c9-8c1c3d8f2d48/download)
