### ISSUE TITLE
Log direct schedule submission errors

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#30405]
## Description
As Product, I would like to see the types of errors that result in a submission failure so that I can communicate trends to stakeholders and take action to reduce them.

August had ~ 85% success rate on direct schedule submissions
![Screen Shot 2021-09-22 at 3.05.15 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/5d7ef6a5-204b-4812-bab8-a25aab2e5047)

---

## Acceptance Criteria

Given a direct scheduling flow (VA direct or Vaccine)
When user attempts a submission
And submission fails
Then error details are tracked

- Error name
- Error message/reason
- Clinic name
- Site ID

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by jbalboni** [comment]
Here's a query in Sentry for the appointments POST errors: http://sentry.vfs.va.gov/organizations/vsp/discover/results/?id=6&project=3&statsPeriod=90d

I think we'd want to see what variations there are in the message field in the VAMF body (or maybe their error code). I believe we mostly see some variation of "Access to {clinic name} is prohibited!" in the message text, but it's not clear if that's always one error code.
