### ISSUE TITLE
Create a visual of Search Design Pattern

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#30400]
##  Description
Establish a visual to accompany the description of search design pattern ([example](https://design.va.gov/experimental-design/copy-deep-link)) to be added to the experimental design system. 

## Acceptance Criteria
- [ ] Visual has been created to share with Natalie

**Comment by mgleo** [comment]
![search-input-ds.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/03791387-75c1-4235-8588-05422c16614b)
**1. Search instructions
2. Input field
3. Search button**



![search-results-ds.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/1162ceb4-8a9c-48ae-9cde-7472b3fdd494)
**1. Search results summary
2. Sort filter (optional)
3. Header link
4. Description**
