### ISSUE TITLE
List of in-progress forms that are 'orphaned' for a user (perhaps from VA Profile page

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#30409]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
There is an assumption that this likely will not be a function with the frontend before login.gov is rolled out. We will have to make some assumptions `some team` will need to have figure out how to obtain this list. There is also a question that needs to be answered about what are we going to expect from the frontend when it comes to in progress forms for verified login.gov and other verified CSPs.

**Comment by joeniquette** [comment]
Trevor completed this with his accounts table work.
