### ISSUE TITLE
Analytics Implementation or QA Support for Find a VA Form:  PDF Modal actions

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#30416]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google analytics implementation

- Who is this request for?
    - Dave Conlon (PO)
    - Marci McGuire (PM)
    - Zachary Morel (FE)
   
    _Provide any relevant contact information and link this issue on the DSVA Slack Channel: `#VFS-Platform-Support` and tag `@platform-analytics`._
    
- What team/project is this work for?
    Decision Tools - Adding modals to existing Find a VA Form tool search page and form detail pages
    
    - [Insert team and project]
    
- Provide the Domain where Google Analytics needs to be implemented
    www.staging.va.gov and www.va.gov
    
    _Identify if PII is passed in URL or title tag_
    No PII collected or passed

- Please provide any upcoming deadlines or important milestones
     - Launch anticipated within the next 2-4 weeks

- Please provide website interactions to Track
    
 1. Clicks on the X to close the modal
 2.  Clicks on the links to the Resources and Support article related to PDFs
 3.  Clicks on the outbound links to Adobe's Reader download page
 4.  (Conversion) PDF download clicks **from within the modal** and the ability to distinguish them from the parent search and detail page PDF clicks already being tracked.
 5. Clicks on the Close/Cancel button within the main body of the modal (language TBD)
    
    Draft mockup below:
![image](https://user-images.githubusercontent.com/73354907/134510344-1c270108-3ef6-4c82-a36d-825334a945d6.png)

    _Design System components are automatically tracked. [Read more here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md#other-important-things) to see which Design System components are opt in or opt out. You do not need to specify on this ticket which components you are tracking unless you are opting in._

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    Each distinct PDF click is considered a conversion.  Each PDF has a unique label and URL.  PDFs that we provide links to are hosted on various servers including: 
        - **va.gov**; ex: https://www.va.gov/find-forms/?q=10-10ez
        - **fiscal.treasury.gov**; ex:  https://www.va.gov/find-forms/?q=sf1199a
        - **gsa.gov**; ex:   https://www.va.gov/find-forms/?q=SF39
        - **opm.gov**; ex: https://www.va.gov/find-forms/?q=of306
        - **vba.va.gov**; ex: https://www.va.gov/find-forms/?q=29-4364.PDF
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - N/A

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - This is an unauthenticated tool
   
- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Certain conditions/responses that need to be reviewed

    - N/A

- Additional Comments

    - This modal will be added to our search page and to our form detail page template so that it appears on every form's detail page.   Search page URL is https://www.va.gov/find-forms/ and detail page URLs look like this: https://www.va.gov/find-forms/about-form-10-10ez/

> Please leave the following blank

## Acceptance criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by bsmartin-ep** [comment]
Hi @MarciMcGuireGCIO -

This would be in the [standard modal component](https://design.va.gov/storybook/?path=/docs/components-modal--default), correct?

**Comment by zacharymorel** [comment]
> Hi @MarciMcGuireGCIO -
> 
> This would be in the [standard modal component](https://design.va.gov/storybook/?path=/docs/components-modal--default), correct?

Correct!

**Comment by bsmartin-ep** [comment]
@zacharymorel -

Sorry for the delay in getting back to you.

Want me to take the lead on getting the _link click_ and _close_ events into the component?

**Comment by MarciMcGuireGCIO** [comment]
Morning!  Wanted to get a quick status on this.  We got the final copy for the modal yesterday and are ready to proceed with building it out.  @zacharymorel are you going to handle the events or is @bsmartin-ep?  Thx!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel can I close this ticket out now?  THx!

**Comment by zacharymorel** [comment]
Yes

**Comment by MarciMcGuireGCIO** [comment]
Woot!
