### ISSUE TITLE
Analytics Reporting Request for BAH Team

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3043]
# Metrics Reporting Request

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

Booz Allen UX Team: Amy Knox, Theresa McMurdo & Cindy Cruz

We're working on the Learn & Improve plan for GI Bill Comparison Tool, VET TEC Integration
    

## Timeframe for Analytics Requested
Would like to review process for finding VET TEC data in our Sprint 33 timeline. Sp33 ends 11/8/19

## Analytics to Track Down

- [x] \# / % of GIBCT users who select “VET TEC training providers” on GIBCT landing page
- [ ] \# of Providers viewed per user
- [x] Do users engage with the "Learn more" links in the tool? 
- [x] Where users go from Provider profile page?  Do they... 
   - Click “Apply to VA Form 22-0994” (VA.gov link)
   - Click “Apply for VET TEC” (VA.gov link)
   - Click “Learn more about VET TEC programs” (VA.gov link)
   - Click Provider URL (external link, various)
   - Click “Apply for program” (external link, various) 

## Which Product Questions are you trying to answer?
Generally, how do we access data on VET TEC in the Comparison Tool? 
How are users engaging with VET TEC data in the Comparision Tool now? 
Does it appear users are having any challenges with the tool? 

## Additional Comments
Attaching original GIBCT 116 analytics request to provide detail on what we'd originally proposed tracking.   
[CT116-StarterAnalytics.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3798682/CT116-StarterAnalytics.docx)

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@amyknox From our meeting, one of the new items we wanted to begin tracking was search refinements after someone selected VET TEC from the GIBCT landing page.

One thing I noticed recently on staging is that when someone selects `VET TEC` as the provider, that the URL goes to https://staging.va.gov/gi-bill-comparison-tool/program-search. On production, the user is taken to https://www.va.gov/gi-bill-comparison-tool/search?vetTecProvider=true

So we can test the search refinements for VET TEC selections, do you know if the URL is going to change to what we see on staging? If so, this might impact our ability to help you capture refinements on VET TEC searches.

**Comment by amyknox** [comment]
@nedierecel - the URL for VET TEC results on production will be https://www.va.gov/gi-bill-comparison-tool/program-search

**Comment by nedierecel** [comment]
Thanks @amyknox - I'll spin that off into a separate request, but the dashboard is under our final review. I'll be able to share the link early next week.

For the VET TEC profiles viewed per session, we can calculate that number, but I am running into an issue in best displaying it within the dashboard. I'm working with @jonwehausen to resolve. Thanks!

**Comment by nedierecel** [comment]
@amyknox Please see the new [VET TEC dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/TT52avPURam05B0aRxyz5g/a50123418w177519031p184334251/) for Team BAH. 

Two follow-ups:
1. Search refinements for VET TEC results: I will add a table for VET TECH search refinements based on the work BAH and @jonwehausen is doing in #3048. 
2. Profile Views per Session: This request was calculated outside of the dashboard. I reviewed data from 8/1/2019-11/18/2019. Based on views of all VET TEC profiles, users are viewing an average of 1.08 profiles viewed per session. 

[https://app.zenhub.com/files/133843125/a62a33ae-3484-4417-8a2e-6c758054fd1c/download](https://app.zenhub.com/files/133843125/a62a33ae-3484-4417-8a2e-6c758054fd1c/download)

Next Steps:
1. I'll keep this issue open until the new search refinements tracking is in place.
2. Please review and provide any feedback on the initial dashboard.

**Comment by nedierecel** [comment]
@jonwehausen For your review, may you please copy and paste this beta funnel into your Custom Reports: https://analytics.google.com/analytics/web/template?uid=z2FHa7DBRrO32jWLrdBiPw

This funnel is based on this request from the report mockup:![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/9f1172cd-703f-4b26-8a73-82dd68cf1767) 

**Modifications:**
1. First step in this funnel is selection of the radio button on the landing page.
1. "Decided to view a Provider Site" is similar but broadened to any outbound click on a VET TEC profile (which may include clicks to phone)

**Funnel Logic:**
1. All actions must be completed within the same session

**Comment by nedierecel** [comment]
@amyknox @ccruzgra and Theresa - Thank you for the time today. Please see the list of resources from our call: 

#### Resources

- [Zoom Recording Link](https://zoom.us/rec/share/xNV0K-_R7F1Je6P000XUa6I-FYvueaa81CMa8vMLzkkmALAVXVqywaWegB8iw8Fv)
- [Existing VET TEC GIBCT Dashboard with Updated Trendline Visuals](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/TT52avPURam05B0aRxyz5g/a50123418w177519031p184334251/) - Data to analyze trends in overall VET TEC usage across the GIBCT, VET TEC provider pages, and VET TEC form submissions
- [Form 1995 Goal Flow Report](https://analytics.google.com/analytics/web/?authuser=0#/report/goal-flow/a50123418w177519031p184334251/_.goalOption=11&_.useg=builtin1,user3vA2ZF6LSgG3JrTYkPya7w&_r.dimension=analytics.landingPagePath&_r.goalIndex=4&_r.activeSegmentId=builtin1/) - Data to understand the flow from various landing pages into Form 22-1995. I will send additional instructions to show how to add the segment to this form.
- [Successful Submissions of Form 22-1995 with Breakdown of STEM responses](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension49&_r.drilldown=analytics.eventLabel:edu-1995--submission-successful/) - See Unique Events column to see distinct submissions breaking out how the applicant responded to the STEM question.

**Comment by nedierecel** [comment]
@amyknox @ccruzgra Additional Resource from our call on Monday:

**[Google Analytics Segment to see "Yes" responses to scholarship question in form 1995](https://analytics.google.com/analytics/web/template?uid=DClLMf2eSR6pBrNi5iymYg)**

1. Please click on the link in your browser. Once there, you will reach a screen like this: 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/0d74d582-cb1e-4fcb-85ed-1dd961b69fd2)

From here, select the "Education Modernized View" and hit Create.

2. In the [Goal Flow report](https://analytics.google.com/analytics/web/?authuser=0#/report/goal-flow/a50123418w177519031p184334251/_.goalOption=11&_.useg=builtin1,user3vA2ZF6LSgG3JrTYkPya7w&_r.dimension=analytics.landingPagePath&_r.goalIndex=4&_r.activeSegmentId=builtin1/), apply the segment then take the steps in the screenshot:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/c4d0c6e9-a13b-455e-8a11-00f0e5711a79)

3. By enabling this segment, this will allow you to look at user behavior based on applicants that selected the scholarship in their form submission.

CC: @jonwehausen

**Comment by nedierecel** [comment]
Hi @amyknox - Did you have an opportunity to review the data above? If so, can we shift this to close and open a new request for follow-up?

**Comment by amyknox** [comment]
@nedierecel - I want to review this tomorrow mornign and then we can close.  I'll ping you when it's ready.

**Comment by amyknox** [comment]
@nedierecel - one last item... the Zoom link from Jan 6 has video but no audio. https://zoom.us/rec/share/xNV0K-_R7F1Je6P000XUa6I-FYvueaa81CMa8vMLzkkmALAVXVqywaWegB8iw8Fv

Cindy mentioned that zoom audio can be a separate file. Do you have access to that?  Or a video / audio combo?

**Comment by nedierecel** [comment]
Good morning @amyknox - I was able to open the Zoom file with audio. If this is still problematic, does downloading the recordings work with audio?

**Comment by amyknox** [comment]
@nedierecel -  I have no idea what was happening last time but I have absolutely no issues with the audio today.  Listening now.

**Comment by nedierecel** [comment]
Thanks @amyknox - Please let me know if there is anything else I can help provide here.
