### ISSUE TITLE
[Components and pattern standards]The components of the navigation system (i.e. URL, breadcrumb, left nav) within your content or feature don't accurately and/or consistently represent the location of the page within the IA. (04.01.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#30432]
#### VFS team name
Public Websites

#### VFS product name
ORDMI Harassment Reporting Tool - Landing Page

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

### Platform Issue
The components of the navigation system (i.e. URL, breadcrumb, left nav) within your content or feature don't accurately and/or consistently represent the location of the page within the IA.

### Issue Details
Unable to verify the actual URL of the page from a preview link.  However, based on the breadcrumb, I am assuming the URL is incorrect.  The URL for this page should be: www.va.gov/report-harassment.  

### VA.gov Experience Standard
04.01.1

### Other References

---

### Platform Recommendation
Ensure the URL is accurate per IA guidance found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27911

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by shiragoodman** [comment]
@mnorthuis could you please rename the title of this ticket to reflect the issue found? Please leave "(00.00.1)" in the title. thanks!

**Comment by mnorthuis** [comment]
Can't validate this until page is published, will review at that time and close.  Not launch blocking.

**Comment by allison0034** [comment]
This ticket has been reassigned from CCIssue00.00 "No VA.gov Experience Standard for the issue found" to CCIssue04.01 "Components and pattern standards ". No VFS action is needed.

**Comment by DanielleThierryUSDSVA** [comment]
Verifying that the URL does show in preview (at the top of the page in the blue box) and is correct for this page.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/1e4dcb97-4ed7-4235-85c2-a6940aee5722)
