### ISSUE TITLE
[Other] URL is incorrect (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#30437]
#### VFS team name
VANotify

#### VFS product name
Digital Notifications Terms & Conditions page on VA.gov

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
Unable to verify the actual URL of the page from a preview link.  However, based on the breadcrumb, I am assuming the URL is incorrect.  The URL for this page should be: www.va.gov/privacy-policy/digital-notifications-terms-and-conditions.  Note that it should live under the Privacy Policy page. 

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
Ensure the URL is accurate per IA guidance found here https://github.com/department-of-veterans-affairs/va.gov-team/issues/26923

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by shiragoodman** [comment]
@mnorthuis please update the title of this issue ticket. thanks!

**Comment by mnorthuis** [comment]
This cannot be validated until the page is published.  Removed launch-blocking lable, will validate once live.

**Comment by mnorthuis** [comment]
@brianalloyd @RLHecht @DanielleThierryUSDSVA The published page has an incorrect URL.  See the description above. 

Since this just launched, if the URL can be corrected quickly, and the link on the privacy page updated, no redirect will be needed.

**Comment by RLHecht** [comment]
@mnorthuis I can update this now in Drupal.

**Comment by RLHecht** [comment]
This page is now live with the correct URL: https://www.va.gov/privacy-policy/digital-notifications-terms-and-conditions/

**Comment by allison0034** [comment]
This ticket has been reassigned from CCIssue00.00 "No VA.gov Experience Standard for the issue found" to CCIssue04.01 "Components and pattern standards ". No VFS action is needed.
