### ISSUE TITLE
Customer Support Tracking by VFS Team and Product

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#30433]
**User Story 1**
As a platform crew member, I want to be able to track the volume and type of support requests by customer team, so I can compare that data to other team-related data and draw insights around the impact of our customer-facing initiatives.

**User Story 2**
As a platform crew member, I want to be able to track the volume and type of support requests by VA.gov product, so I can compare that data to other VA.gov product-related data and draw insights around the impact of our VA.gov product quality initiatives.

**Comment by Khyatinp18** [comment]
Closing this issue since SD team handed off Customer Support tracking to SRE team
