### ISSUE TITLE
Adding Joseph Justice to DSVA Slack

### ISSUE THREAD

**Issue by Kathy0767** [department-of-veterans-affairs/va.gov-team#30448]
# Joseph Justice is the new APM on Axoloti team and will need access to DSVA Slack channel

Are you requesting to add an individual as a:

- Multi-channel

- What channel(s) do they need to be added to?
- #cms-lighthouse
#vsa-facilities

- Please add joseph.justice@va.gov as a multi-channel guest to these channels: #cms-lighthouse and
#vsa-facilities

Joseph Justice is the new APM on Axoloti team and will need access to DSVA Slack channel to support the LightHouse Facilities API

## Sample Descriptions 

- Please add joseph.justice@va.gov as a multi-channel guest to these channels: #cms-lighthouse and
#vsa-facilities

**Comment by LizCallaghan** [comment]
done!
