### ISSUE TITLE
Make Paul Saindon a full member of the DSVA Slack

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/va.gov-team#30449]
Paul Saindon is an attorney at the Board and a key member of the Board Advisory Council. Mr Saindon is currently a multi-channel guest of the Slack and we would like to make his account (email address: paul.saindon@va.gov, member ID: UD4UET3EC) into a full member of the Slack to eliminate the need to request Paul be added to each channel individually.

**Comment by LizCallaghan** [comment]
done!
