### ISSUE TITLE
Adding [eric@coforma.io] to DSVA Slack

### ISSUE THREAD

**Issue by kaeliwyuen** [department-of-veterans-affairs/va.gov-team#30443]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Multi-channel

- What channel(s) do they need to be added to?
- cpm-public
- lcs-public
- cds-team
- health-care-products-all-teams

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
Please add eric@coforma.io to the channels above. He is a contractor with Coforma who will be working on clinical decision support.

**Comment by LizCallaghan** [comment]
sorry, I don't have access to the channels, but I did add the person to Slack.
