### ISSUE TITLE
Handle entities with no `target_id` in `assembleEntityTree`

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#3044]
# Description
This issue originates from [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10978#issuecomment-548593424). With the current tome-sync CMS export, when running the script `yarn build:content:test` there appears to be [`target_id`s that are undefined](https://github.com/department-of-veterans-affairs/vets-website/pull/10978/files#diff-2c00f1303870433026268a99ce3672abR18), which can be seen in the [output of that script](https://github.com/department-of-veterans-affairs/vets-website/pull/10978#issuecomment-548568073).

We should discuss and investigate what needs to be done when we run into an entity without a `target_id` (e.g. `taxonomy_term`s do not have `target_id`s.)

**Comment by cvalarida** [comment]
I think with the re-working of `readEntity` to pass in the `baseType` and the subsequent cascading changes, [my PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10982) accidentally fixes this. :smile:
