### ISSUE TITLE
Remove "onclick" events in content files used to capture analytics

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#3046]
@ncksllvn commented on [Fri Oct 05 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14016)

To reduce generated `<script/>` elements from the Nonce plugin, and to centralize our analytics, we should instead use data-attributes to capture events, similar to our popup implementation - https://github.com/department-of-veterans-affairs/vets-website/pull/8667.

**Comment by FranECross** [comment]
Closing due to age and inactivity. More than likely obsolete. Can reopen if needed in the future, or a new ticket created.
