### ISSUE TITLE
Request Pre-launch ATO review

### ISSUE THREAD

**Issue by shawkey-daniel** [department-of-veterans-affairs/va.gov-team#3047]
What data are you collecting? N/A static content
What data are you using?
  GI Bill Comparison Tool
  
![image](https://user-images.githubusercontent.com/48804574/68041865-e7c9a280-fca7-11e9-9300-dcfec41c21d3.png)

  institution_programs

![image](https://user-images.githubusercontent.com/48804574/68041902-016aea00-fca8-11e9-967c-941c567745bb.png)

Where does the data come from?
  vets-api API endpoint
  /v0/gi/institution_programs/search

  gibct-data-service API endpoint
  /v0/institution_programs

**Comment by andreahewitt-odd** [comment]
We don't have a formal ATO review process yet. Closing this issue.
