### ISSUE TITLE
TTT Dashboard Data repo - install eslint, run eslint in GHA CI workflow, fix eslint errors and warnings

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#30484]
Add ESLint to the Testing Tools Team Dashboard Data repo.

Install eslint, run eslint in GHA CI workflow, fix eslint errors and warnings.

**Comment by holdenhinkle** [comment]
Created new CI GHA workflow for running ESLint.

Example run - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/actions/runs/1270280037

PR is merged - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/72

**Comment by pjhill** [comment]
We have graduated to CI! Thanks for paying down this tech debt.
