### ISSUE TITLE
Staging: No Open Appt Slots & Selected Current Date;  Alert message to user is a messed up.  

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#30480]
## Summary
No handling for urgent care alert date when no slots are returned.

## Steps to Reproduce
**Test User:** Judy

1. In VistA for CHY AUDIOLOGY (Friendly Name Audiology) configure clinic to meet for the next four weeks but have all slots booked, so there are no open slots.
2. Log into VAOS as Judy Morrison. Select to schedule, Audiology and Cheyenne. System displays the two clinic available for direct scheduling: Friendly Name Audiology and Wheatland Audiology.
3. Select Friendly Name Audiology. For Scheduled date enter the current date/today and select continue

### Actual Result
Message displays that the earliest an appointment can be scheduled is the current date and time

### Desired Result
Alert copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar.md#alert---urgent-care---no-slot)

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#urgent-care-alert) is updated

---

**ORIGINAL DESCRIPTION**
1. In VistA for CHY AUDIOLOGY (Friendly Name Audiology) configure clinic to meet for the next four weeks but have all slots booked, so there are no open slots.
2. Log into VAOS as Judy Morrison. Select to schedule, Audiology and Cheyenne. System displays the two clinic available for direct scheduling: Friendly Name Audiology and Wheatland Audiology.
3. Select Friendly Name Audiology. For Scheduled date enter the current date (9/24/2021) and select continue
4. Expected Response: User is informed there are no available appointment slots
5. Actual Response: Message displays that the earliest an appointment can be scheduled is the current date and time (9/24/2021 @7:13 AM)

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/e1613a03-342f-4a64-b27e-8c4d48027ca4)

.

**Comment by laurenernest** [comment]
Slot query looks at 2 months (2 at a time). Potential changes:
1. Keep slot query as is, update date copy
2. Query another 2 months to check for next available slot, update copy if still no slots.

Moving to backlog to review analytics on this error and update next steps.

**Comment by ldelacosta** [comment]
@marcynadeau - Please validate. Thanks

**Comment by beth-wodzinski** [comment]
Validated.

**Comment by ldelacosta** [comment]
QA validated the issue. Closing out the ticket.
