### ISSUE TITLE
Analytics Implementation or QA Support for VET TEC in the Comparison Tool

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3048]
# Analytics Implementation or QA Request

> _Please see the following information for implementation timeline:_
> 
> All other [not New] teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics Implementation

- Who is this request for?

Amy Knox / BAH Team
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    
    - BAH TEAM, GI Bill Comparison Tool 116 (VET TEC) Post-MVP Solution
    
- Provide the Domain where Google Analytics needs to be implemented
Location on staging:  https://staging.va.gov/gi-bill-comparison-tool/
Location when launched: https://www.va.gov/gi-bill-comparison-tool/

    _No PII is passed in URL or title tag_

- Please provide any upcoming deadlines or important milestones
   Target launch date: Nov. 22
 

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required - NA

- Test Users to replicate the event - NA

- Certain conditions/responses that need to be reviewed

- Additional Comments

 Word doc attached shows initial requested implementation.  NEW items to track are highlighted and marked NEW. [https://app.zenhub.com/files/133843125/ebfdd2a3-4714-4a8c-b62e-dc8976a77343/download](https://app.zenhub.com/files/133843125/ebfdd2a3-4714-4a8c-b62e-dc8976a77343/download)

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@amyknox - @jonwehausen will take the lead on implementing the items marked as `New` within the ticket.

**Comment by jonwehausen** [comment]
Hi Amy, 

Ditto to @nedierecel's above point. 

With a quick audit of the search and individual facility pages, as it stands, here is the status of your tracking items identified as `New`: 

## Items Already Tracked with previous analytics future-fitting
```diff
+ Any email link click
+ Any telephone link click 
+ Any click on a outbound website away from va.gov (will include provider sites)
+ Learn more modal pop-ups
```

#### Country, State, and "City, VET TEC program or provider" we can handle completely in GTM without any dataLayer code. 


## Items Needing dataLayer Code for Tracking
```diff
- Accordions expands/collapses
- Filter usage
```
------------------
## Here is the DL we will need for each of the items above: 

- **For EACH accordion EXPAND click** 
```javascript
dataLayer.push({
  'event': 'nav-accordion-expand',
});
```

- **For EACH accordion COLLAPSE click** 
```javascript
dataLayer.push({
  'event': 'nav-accordion-collapse',
});
```

- **For EACH individual filter listed in "Filter by provider" section**
```javascript
dataLayer.push({
  'event': 'gibct-form-change',
  'gibct-form-field': '<dynamically_populate_with_provider_name>', //example: 'CLAIM ACADEMY'
  'gibct-form-value': true|false //TRUE when toggled on or FALSE when toggled off
});
```

@amyknox Please let us know if there's anything here we haven't called out you need.

**Comment by ksantiagomorgan6** [comment]
Pull request for this story 

https://github.com/department-of-veterans-affairs/vets-website/pull/11111

**Comment by sonntag-adam** [comment]
Filters
![Screen Shot 2019-11-15 at 2.36.42 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/70a18e5f-6c6e-4f9e-ae9f-58e64119c3e7)
##
Accordions expanded and collapsed
![Screen Shot 2019-11-15 at 2.38.20 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/54774526-a0f8-4cab-a2bf-6dcefceecca1)
![Screen Shot 2019-11-15 at 2.38.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/334647c3-3e65-499a-990b-a1e533840164)

**Comment by desireeturner** [comment]
@nedierecel @jonwehausen our changes for for this work are in and should be available on staging now. Please let me know if you have any questions or need us to make any additional changes. Thank you! 

cc: @amyknox

**Comment by jonwehausen** [comment]
Hi @desireeturner and @sonntag-adam,

Thanks to you both for getting this in quickly. 

Per your screenshot, I noticed for the accordion expands, I see your screenshot has ```nav-accordion-expanded``` rather than ```nav-accordion-expand```.


### SIDE NOTES: 

- **Regarding the accordion** -- I actually saw the push correct [here in staging](https://staging.va.gov/school-administrators/) in my most recent test, but wanted to make sure the -ed version wasn't still floating somewhere.
- **Regarding the providers filter** -- On the [search results page in staging](https://staging.va.gov/gi-bill-comparison-tool/program-search): There currently aren't any examples of the providers filter. If possible, I'd like to request that to verify. Thanks. 

CC: @amyknox @nedierecel

**Comment by ksantiagomorgan6** [comment]
Pull request for text change https://github.com/department-of-veterans-affairs/vets-website/pull/11153

**Comment by amyknox** [comment]
@jonwehausen re the provider filters
The provider filters were removed pending resolution of the defects.  They will be re-deployed post launch.

**Comment by sonntag-adam** [comment]
Filters
![Screen Shot 2019-11-21 at 7.22.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1fac060c-4513-4a37-beb1-032023871b54)
##
Accordions expanded and collapsed
![Screen Shot 2019-11-21 at 7.26.33 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4d88d45f-8a2a-4917-a170-eba7f368c701)
![Screen Shot 2019-11-21 at 7.26.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d02efd4f-5a05-4a38-bc08-452005931765)

**Comment by jonwehausen** [comment]
Hi @sonntag-adam, 

Thanks again for your corrections here, this looks great. 

Per @amyknox and I's conversation, our team can stage the tag based on these screenshots that will be used for the Provider Filters, but we would like to refrain from pushing that piece to production until we can confirm live in staging with a legitimate filter -- which @amyknox mentioned may not be until December.

**Comment by amyknox** [comment]
@jonwehausen  - confirming 
1. we're good to go for the GA datalaye code for accordions and 
2. we'll revisit the GA datalayer code for Provider filters prior to that functionality going live.

**Comment by jonwehausen** [comment]
Yes correct - we would like to keep the DL code for the provider filters in staging until we have a live provider filter we can test with in staging.

**Comment by amyknox** [comment]
@jonwehausen - 
Do you prefer this story stays open in the backlog until Provider Filters are re-deployed OR we close this and create a new story when provider filters are ready to to roll?

**Comment by jonwehausen** [comment]
Hi @amyknox,

I'm okay with us closing this one and creating a new one when the provider filters are ready.

**Comment by jonwehausen** [comment]
This functionality has been published and is live. 

Will close this story now -- @amyknox if you could create a new one when the provider filters are ready we would greatly appreciate it.

**Comment by desireeturner** [comment]
@amyknox the Provider Filter updates, including GA datalayer updates, are going to be covered in the following issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19992
