### ISSUE TITLE
Access for [Justin Bosse]

### ISSUE THREAD

**Issue by jmbosse19** [department-of-veterans-affairs/va.gov-team#30491]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Justin Bosse

### Your Email

jbosse@clarityinnovates.com

### Name of Your Team

Platform Support

### Service(s) You Want Access To

SOCKS (Requires public ssh key)

### Public SSH Key

```shell
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC67Xoq2xQHphYxdDDVjWX+eirDCGtqYNWo6eHCYQaPZDo/Q+yR/fY0HcaGmY/FAWVQ6BhMwKVe9pFtSOsNCMTrWdtuKHpMkc++ZhfJctfTepBN/Hw6G+cSHV4yBDhKcQdhEEXA5cRIx20GywuX9oZJHLPGMLZKb8pEQi0fwMdj7TvrzD5L5nBAPd6zaXWX0pebypw2Z6je9qmst7+iZzsgEoBwbuEB6h9M4+av4mrucQw5zEyChILPfQ1sEwDNzW5wyOpqJaUGj4UcEW1W6vSA00wC3yP+9WWe7/hDpaX0s2mgfUTd9Xh1Ew4MeJJFhGwo6yW8Nm1Q4L2zUDtd8VHjYLVfYpuEyOy4QdAoLMohYekdU4YwpMGgHLZKU/1+D4GVqG1lL6hdLDdzHEOEALu7Kb02KG4jUUSTXtKAsBIpRqnE/zEtSaGqqwZqxmhHQnxsPfn60ju2w4AktG76BQnQt9FQpqBdFMyupd0QSHnm5LJhRVXXYgcGtzSj4N26UC0= jbosse@jbosse
```

**Comment by omgitsbillryan** [comment]
Kindly update the title of the Issue with your name.

**Comment by jmbosse19** [comment]
> Kindly update the title of the Issue with your name.

Updated, sorry about that! Thank you

**Comment by rwilliams-oddball** [comment]
Added Access, please let me know if you have any issues.
