### ISSUE TITLE
TTT Dashboard Data repo - install, configure and run prettier

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#30495]
In the Testing Tools Team Dashboard Data repo, 
- Install `prettier`
- Add `.prettierrc` to configure prettier
- Create `format` script to run prettier
- Run `yarn format` to correct any formatting errors

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/73

**Comment by pjhill** [comment]
So pretty!
