### ISSUE TITLE
Enable search button only when required fields have been populated for Community Care searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3050]
**For consistency of user experience, to maximize performance and to increase user success, the search button within Facility Locator should not be enabled until the mandatory service type field have been populated for Community Care searches within Facility Locator.**

**Current functionality:**
Although the service type search field is marked as required in the UI and the search will not initiate unless it is populated, the search button itself appears to be available for users even when all required fields have not been completed.  
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/7acc7706-3b53-43a3-a609-a9ab56d305be)

**Expected functionality:**
The search button is not enabled unless and until all required fields have been populated. 
Note: A separate issue [2739](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2739) will address the address/city/state/zip field requirement.

**Comment by mmiddaugh** [comment]
@jenstrickland are there any other particular considerations for this?

**Comment by jenstrickland** [comment]
@mmiddaugh — I just messaged the design channel to confirm, but it is my understanding we do not disable buttons until required fields are complete. Rather, we would provide error messages to indicate the required fields that need to be completed. If I hear otherwise, I'll update.

**Comment by jenstrickland** [comment]
@mmiddaugh Rather than disabling the Search button, error messages are needed for incomplete required fields so users know what is missing.

**Comment by mmiddaugh** [comment]
Closing this issue as the error messages will be addressed in [489](https://github.com/department-of-veterans-affairs/va.gov-team/issues/489)
