### ISSUE TITLE
Staging:  Type Error Cannot read property 'serviceName' of undefined

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#30502]
Network tab is not showing any error.  Consoles shows this:
https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/clinics

I am testing the VATS limits with Judy because I configured her to have past appointments in all Specialties. So I will select one type of care, verify clinics display.  The move on to the next type of care.

1.  Login as Judy Morrison. Select Audiology, Select Dayton.  Validate clinics display.  Hit back button to get back to the type of care selection
2. Select Food, Select Springfield.  Validate clinics display.  Hit back button to get back to the type of care selection
3. Select Move, Select Dayton.  Expected response:  Validate Clinics display.  Actual Response: Error Displays.

 ![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/3e64b84d-7c38-44bf-9b68-a0dede0e2bc0)

Another Example:
1.  Login as Judy Morrison. Select Move, Select Dayton.  Validate clinics display.  Hit back button to get back to the type of care selection
2. Select Eye Optometry, Select Dayton.  Expected response:  Validate Clinics display.  Actual Response: Error Displays.
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/5cc13177-d0ef-4980-af92-8e25305d347f)

**Comment by laurenernest** [comment]
@marcynadeau Ready for retesting

**Comment by marcynadeau** [comment]
I was late in testing this. I have verified this is no longer an issue is Staging and all is working as expected.
