### ISSUE TITLE
Update link in request limit alert

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#30510]
## Description
As a user who has reached a request limit at a facility, I want to view my open requests so that I can make adjustments as needed.

---

## Acceptance Criteria

Given user has reached the request limit
When user clicks "your appointment request" in the request limit alert modal
Then load the appointment request list (`/health-care/schedule-view-va-appointments/appointments/requested`)

## Definition of Done
- [x] All acceptance criteria are met

---

**ORIGINAL DESCRIPTION**

When the request limit has been reached, shouldn't the link go to the request queue?  Your appointment list should be Your request list.  

You’ve reached the limit for appointment requests at this location
Our records show that you have an open appointment request at this location. We can’t schedule any more appointments at this facility until your open requests are scheduled or canceled. To schedule or cancel your open appointments:

**Go to your appointment list and cancel open requests,** or
Call your medical facility:
Fort Collins VA Clinic
2509 Research Boulevard
Fort Collins, ColoradoCO 80526-8108
Main phone: 970-224-1550
TTY: 711

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/7b173bab-4d1b-4e05-8512-01a159ef6acb)

**Comment by laurenernest** [comment]
Thanks for calling this out. It's not incorrect to still direct to the homepage/appointment list, but I'll look at the analytics and see if we want to update.

**Comment by laurenernest** [comment]
The appointment list pageviews from the Facility Selection page are <1% of all views. We'll make the change (pending any conflicts with the request research findings), but this is a low priority.

**Comment by laurenernest** [comment]
Verified link has been updated. closing ticket.

![Screen Shot 2022-01-11 at 10.37.32 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/05a081a1-9031-4b36-a8fa-0eee4cd8c53e)
