### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#30520]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics
- [x] Domo
- [x] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 

Edit access would be useful.

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Domo access granted.

Following up re: BigQuery.

**Comment by bsmartin-ep** [comment]
BigQuery access granted.  Closing.
