### ISSUE TITLE
[Discovery] Determine how and why veterans choose a particular AMA / Decision Review Lane

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#3052]
## Goal

Determine how and why veterans choose a particular AMA lane for their appeal.

Provide solid examples of circumstances - what paths are better for X,Y,Z scenario
- Give clarity to each path by creating examples (is this for me?)
- What are the implications of each path? (time, effort, etc)
- Meet w/ Steve about this 

## Acceptance Criteria

- [ ] Determine and gather quantitative metrics for each appeals lane (how many are in each lane / how many in new appeals lane vs. legacy appeals, process / flow for lane choice, etc)
- [ ] Determine qualitative methods for researching veteran lane choice (user testing vs. other research methods?)

**Comment by YanaRoy** [comment]
@YanaRoy expand on ticket

**Comment by YanaRoy** [comment]
Epic created for this ticket - #3140
