### ISSUE TITLE
[DNS] Setup entries for CHIP API

### ISSUE THREAD

**Issue by charleystran** [department-of-veterans-affairs/va.gov-team#30524]
## Description
We are looking to have some DNS entries for CHIP (Check-in experience integration point) APIs so that vets-API (and the clinician app also using CHIP) can have a cleaner interface to the API vs the current VPC URLs. 

## Technical notes
We are looking to setup 
dev-chip.vfs.va.gov
int-chip.vfs.va.gov
staging-chip.vfs.va.gov
chip.vfs.va.gov

I can Keybase over the mappings to VPC URLs to whoever would grab the ticket

## Acceptance Criteria 
- [x] dev-chip.vfs.va.gov is setup and pointing to the dev CHIP server
- [ ] int-chip.vfs.va.gov is setup and pointing to the int CHIP server
- [x] staging-chip.vfs.va.gov is setup and pointing to the staging CHIP server
- [x] chip.vfs.va.gov is setup and pointing to the prod CHIP server

**Comment by omgitsbillryan** [comment]
DNS lookup works. 
```
$ dig +noall +answer dev-chip.vfs.va.gov
dev-chip.vfs.va.gov.  60  IN  CNAME https://vpce-063XXXXXXXX.vpce.amazonaws.com.
$ dig +noall +answer staging-chip.vfs.va.gov
staging-chip.vfs.va.gov. 60 IN  CNAME https://vpce-026XXXXXXXX.vpce.amazonaws.com.
$ dig +noall +answer chip.vfs.va.gov
chip.vfs.va.gov.  60  IN  CNAME https://vpce-04XXXXXXXX.vpce.amazonaws.com.
```

I don't know how to functionally test the API. I leave that to @charleystran

**Comment by omgitsbillryan** [comment]
One note - I didn't setup "int" - I don't know where `int-chip.vfs.va.gov` is supposed to point to.

I was able to find the other mappings by looking at the various ENV settings.yml files.

**Comment by omgitsbillryan** [comment]
I'm going to close - @charleystran feel free to re-open if the requirement has not been satisfied.
