### ISSUE TITLE
Inbound Initiated (without previous sign-on from VA.gov)

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#30532]
Create tests for all inbound scenarios that start without previous sign-on from va.gov

The intent is to document the user scenarios, test the login scenarios, record the outcomes (to include what the accounts table looks like).

**Comment by joeniquette** [comment]
sprint 63

**Comment by joeniquette** [comment]
Trevor, lets try and close this out during a meeting next week.

**Comment by nsoutouras** [comment]
MSI - Not done yet.  Waiting for Login.gov to get to staging.

**Comment by joeniquette** [comment]
This doesnt need to be done this sprint, moving to next sprint.

**Comment by joeniquette** [comment]
This task has one component left and thats to create a document which explains how to get a test account reset when this type of test is required. The issue is that once an account logs into va.gov successfully the only way to reproduce the intent of this ticket, which is to ensure accounts that have never logged into va.gov before operate as expected. Documenting this expectation as well as how to request the accounts to be reset in both the accounts table (va.gov api) and in MPI (IAM team) is whats left here.

**Comment by nsoutouras** [comment]
Nick: This is just documentation

**Comment by joeniquette** [comment]
The process of requesting a login.gov account to be reset within staging and below is as follows:
- identity BE engineer can remove the entry for the uuid in the accounts table
- contact IAM (Damien) to reset the account with the login.gov uuid

Once that is done then you can test this type of interaction. In regards to what the user looks like in the accounts table that is documented in a different ticket here:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/User%20Accounts/Data%20Consistency/user_accounts_data_consistency.md
