### ISSUE TITLE
[ 01/24/22] VEText 2.0: Content Guide

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#30539]
Write a content guide that outlines best practices for updating the VEText user guides

**Comment by vlivshin** [comment]
Write a content guide that outlines best practices for updating the VEText user guides.

**Comment by lindsay-insco** [comment]
On hold for user research

**Comment by vlivshin** [comment]
@lindsay-insco, I'm working on initial edits to user guides which provides ideas for what to include in the guide. Will  move into in progress once initial edits are complete and I'm ready to draft the guide.

**Comment by vlivshin** [comment]
Content Guide is ready for review: https://docs.google.com/document/d/1T878_sJBAwy-l6pHhoIK1rLPfzQQ0hotaZJisUYWa00/edit#

**Comment by lindsay-insco** [comment]
Reviewed by @jwowk
