### ISSUE TITLE
Design intent [Public Websites - New VA.gov Mobile Header]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30549]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [x] Respond to Platform feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [X] Yes (Ryan designed this element)
- [ ] No

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)
 

--> 
 
- [x] Whiteboard[ sketch](https://www.sketch.com/s/63193c20-04fc-4d4f-8b54-abf698c48636/a/Vr8Zzrw) or other lo-fi prototypes or wireframes 
- [ ] User flow
- [ ] Any other artifacts you have so far

### Required
- Product Manager: Brian Lloyd
- OCTO-DE Product lead: David Conlon
- OCTO-DE Design lead: Ryan Thurlwell

### VFS Attendees

- Content and IA: 
- Accessibility: 

## Scheduling

**[October 1, 2021]** **[2:00 - 2:30PM]**

## Additional information
For the Design Intent, you'll receive feedback from design and IA only. You won't receive feedback from accessibility, content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@brianalloyd this has been scheduled for October 1 at 2:00 ET.

**Comment by brianalloyd** [comment]
Thanks you @allison0034

**Comment by brianalloyd** [comment]
Completed Design Intent review, no tickets from discussion and am closing ticket in support.
