### ISSUE TITLE
Adding Bo Davis to DSVA Slack

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#30543]
# Description
- Please add bo.davis@adhocteam.us as a full member.
Bo Davis is the program manager for the Platform Spike Teams.
Please add to private channels #platform-team & #spike-planning

**Comment by LizCallaghan** [comment]
I have created the account but I don't have access to the Platform Spike Team channels.

**Comment by jjulian** [comment]
Thank you @LizCallaghan! I was able to add Bo to those private channels.

**Comment by LizCallaghan** [comment]
Great, thanks!
