### ISSUE TITLE
Urgent Care Wireframe #1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3054]
**As a Veteran, I need to quickly and accurately search for facilities with urgent care or emergency services available nearby so that I can address my medical needs**

## Background:
- User feedback suggests that the work done to consolidate the urgent/emergency/pharmacy/Community Care facility locators into Facility Finder has resulted in a confusing and frustrating search process related to community care and facilities providing urgent and emergency care services. 
- Links to the legacy Triwest locator have removed from the Facility Locator page but the changes are available only in staging, pending the resolution of data quality issues ([3051](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3051))
- An additional contractor (Optum) to the urgent care/emergency network of providers is pending and is expected to increase the urgency for removing the TriWest links. 
- Initial user research regarding Veteran understanding and mental models for Community Care/urgent care is available [here](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/ead0fe129bfee6b8e7eaae59d7f4f681a37dec15/Products/Global/Facilities_Locator/community_care/1_discovery) and in the context of scheduling [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ced1f174122a326350ec34dde19bafca087b4619/products/health-care/appointments/research/sept19-usability-testing-new-ux/request_usability/convo-guide-VAOS-cc-and-request-flows.md)
- Recent discovery research revealed usability concerns regarding iconography (link TBD)
- [Design input](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/design/facility-locator-2.0-2019-10-07%20(1).pdf) is available from Andy

## Goal:
- Begin to redesign the experience for Veterans searching for an urgent/emergency care facility.  

## Acceptance criteria
- Incorporate community and urgent care research into Facility Locator discovery research
- A first draft wireframe for incorporating Urgent Care into FL tool

**Comment by mmiddaugh** [comment]
including @jenstrickland for awareness

**Comment by mmiddaugh** [comment]
the work done in [3051](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3051) to understand the feasability of separating types of facilities may also inform this work.

**Comment by mmiddaugh** [comment]
@arickalewis1 posting these links here, in case they help with background, prompt any questions for further research or ideas for UX: 
https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent_Care.asp
https://www.va.gov/COMMUNITYCARE/programs/veterans/Emergency_Care.asp

**Comment by mmiddaugh** [comment]
@arickalewis1 moving this information from another issue so it can be incorporated into Wireframe when appropriate
**Stakeholder request:** Replace "service type" label with "Category of Care" for searches with "Community care" as the facility type.

**Comment by mmiddaugh** [comment]
@arickalewis1 @davidconlon I found this info on the [Community Care/Urgent Care website](https://www.va.gov/COMMUNITYCARE/programs/veterans/Urgent_Care.asp)

![image](https://user-images.githubusercontent.com/55411834/68984215-ab2b9a00-07c3-11ea-8f15-94161abe24d8.png)

Might be something to confirm with Andy....would this phone number/info help the Veteran  prepare for the urgent care visit?

**Comment by mmiddaugh** [comment]
@arickalewis1 please add a link to the wireframe v1 when available and close this issue.

**Comment by arickalewis1** [comment]
[FL-wire-ideation-v1.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/3866237/FL-wire-ideation-v1.zip)
Version 1 wireframes/ideation
