### ISSUE TITLE
Analytics Implementation for Resources for Schools [SCO Migration]

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3055]
# Analytics Implementation or QA Request

> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

Request for Google Analytics implementation

- Who is this request for?

Amy Knox, Booz Allen Team

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?

Booz Allen team is working on migrating content for School Certifying Officials from benefits.va.gov to va.gov
    

- Provide the Domain where Google Analytics needs to be implemented

Current location on staging:   https://staging.va.gov/education/school-resources/
When added to production:   https://www.va.gov/school-administrators/

- Please provide any upcoming deadlines or important milestones

Target Launch date: Nov. 22

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:*   Experience is a single page, not a flow.
    
    - *Other User Interactions*:  
    
   - Users engaging with jump links
   - Users engaging with accordions (open / close toggle) 
   - Users engaging with sidebar content

- Sample Users when authentication is required - NA

- Test Users to replicate the event - NA

- Additional Comments

Page will have va.gov design style but will be hosted as a GitHub page until it - and other Tier 2 content - is migrated to Drupal. 

Success Metrics include
 * Increasing # of users visiting page
 * On-site usage of SCO Handbook (PDF file)
   - Increasing page views of SCO Handbook PDF 
   - Increasing time on page
 * Increasing completion of required training before annual deadline
 * Increasing participation in VA-hosted webinars
 * Anecdotal reports of user satisfaction
   - Ease of use
   - Content freshness
   - Content relevance

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@amyknox This is picked up in the Analytics-Insights team current sprint. For the completion of required training and webinars, can you provide wireframes of what that will look like when shfited from benefits.va.gov? When clicking on the links now in staging, they still go to ebenefits.va.gov.

**Comment by jonwehausen** [comment]
Hi Amy, 

Ditto to @nedierecel's above point. 

With a quick audit of the page, as it stands, here is the status of your tracking items: 

## Items Already Tracked with previous analytics future-fitting
```diff
+ Accordion Expands/Collapses
+ File downloads
+ Right sidebar expands/collapses
+ Right sidebar links inside
+ Outbound link clicks
```

## Items Needing DL Code for Tracking
```diff
- Jumplinks
- Featured content links in 'Latest Announcement from VA' section 
- Link list for 'Other Resources to support your students' section
```
------------------
## Here is the DL we will need for each of the items above: 

- **For EACH individual jumplink** 
```javascript
dataLayer.push({
   'event': 'nav-jumplink-click'
});
```

- **For EACH individual link in 'Latest Announcement from VA' section** 
```javascript
dataLayer.push({
  'event': 'nav-featured-content-link-click',
  'featured-content-header': 'Latest announcement from VA' 
});
```

- **For EACH individual link in 'Other Resources to support your students' section**
```javascript
dataLayer.push({
  dataLayer.push({
  'event': 'nav-linkslist',
  'links-list-header': 'Other resources to support your students' 
});
});
```

@amyknox Please let us know if there's anything here we haven't called out you need.

**Comment by amyknox** [comment]
> For the completion of required training and webinars, can you provide wireframes of what that will look like when shfited from benefits.va.gov? When clicking on the links now in staging, they still go to ebenefits.va.gov.

@nedierecel - all links are directing where they should once the page is deployed

The updated link for the SCO page on production will be:   https://www.va.gov/school-administrators/

**Comment by jonwehausen** [comment]
Hi @Karak888, We're helping the BAH team with this landing page, and we wanted to see if the Public Websites team needs to implement analytics or would the BAH team need to tackle.

**Comment by zurbergram** [comment]
For jumplinks
https://github.com/department-of-veterans-affairs/vagov-content/pull/596

For announcements and "Other resources..."
https://github.com/department-of-veterans-affairs/vets-website/pull/11127

**Comment by jonwehausen** [comment]
Thanks so much for your work @zurbergram 

Staging QA: 

### ✅ Jumplinks - "On this page" bullets 
![image](https://user-images.githubusercontent.com/48527022/69245083-2bf7e680-0b74-11ea-9185-84f73833ad8b.png)

### ✅ Featured Content - Light Blue Box Clicks -  "Latest announcements from VA"
![image](https://user-images.githubusercontent.com/48527022/69245227-724d4580-0b74-11ea-8aaf-95fcaacc81ed.png)

### ✅ Links List - Grey box at bottom -  "Other resources to support your students"
![image](https://user-images.githubusercontent.com/48527022/69247155-f654fc80-0b77-11ea-9d06-06bbe8dffa43.png)

@amyknox - To look you in for a brief note, I just want to set the expectation of what's on the page that we DO NOT have tracking for... These are things I didn't explicitly see in the requirements, I just wanted to make sure there in fact wasn't any need to track these interactions so we don't miss them in case: 

- **Key resources for SCOs**: some are PDFs, so we have tracking for those (_SCO, VA-ONCE Quick Reference Guide_), but ones that are links we do not. 
- **Upcoming event clicks**
- **Links inside of accordions**  (_GI Bill benefits and programs for example_)

CC: @nedierecel

**Comment by amyknox** [comment]
@jonwehausen thanks for the setting expectations.  

Key Resources, a general question... those items are all links that appear elsewhere on the page.  If we track them (whatever the format), would it show which of the links on the page the user engaged with?  And, if we wanted to say "these are the most frequently used resources" would we be able to look at a report of "next pages" or something similar? 

Upcoming event clicks... these events will rotate through and all direct to a single page so I feel OK about not tracking them individually. 

Links inside accordions... Interesting note.  Some items are PDFs but per your comment on Key Resources, the items that aren't won't be tracked. Thinkint the real value of tracking each item would be the ability to know what the most frequently accessed items on the page are.

**Comment by jonwehausen** [comment]
@amyknox Thanks for your input and confirmations here. 

## Here's a summary of the remaining action items: 

1) **To record the links associated with links embedded within accordions, this is the DL code we'll need**: 
```javascript
dataLayer.push({
   'event': 'nav-accordion-embedded-link-click'
});
```
**We will need this on EACH of the links inside accordions on the page, see screenshot for the "Essentials for SCO's example**

![image](https://user-images.githubusercontent.com/48527022/69373322-8b87ec00-0c71-11ea-9b28-28379e274ac8.png)

2) Our team will setup a 1-off tag for the "Key Resources" section, no DL code required.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vagov-content/pull/601 for https://github.com/department-of-veterans-affairs/va.gov-team/issues/3055#issuecomment-557254189

**Comment by jonwehausen** [comment]
Hi @amyknox,

After further looking at the HTML structure on this page and chatting with @nedierecel for the **Key Resources link tracking**, we think it's best to do this within the DL as well. 

For **EACH** link in the key resources list, we'll need the following DL code: 

```javascript
dataLayer.push({
  'event': 'nav-pipe-delimited-list-click',
  'pipe-delimited-list-header': 'Key resources for SCOs'
});
```
CC: @zurbergram 
![image](https://user-images.githubusercontent.com/48527022/69377149-a78f8b80-0c79-11ea-9402-026287c66b5f.png)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vagov-content/pull/601 for https://github.com/department-of-veterans-affairs/va.gov-team/issues/3055#issuecomment-557275130

**Comment by delli-gatti-michael** [comment]
Just confirmed that this is all live in Staging

**Comment by jonwehausen** [comment]
Confirming dataLayer code looks good here for the accordion embedded links and the "Key Resources" list. 👍

**Comment by amyknox** [comment]
@nedierecel & @jonwehausen - what's the status of this story?  Is the QA just about wrapped up?

**Comment by nedierecel** [comment]
@jonwehausen These are the items I see:

- Jumplinks: Passed; I also see the exception to block these from triggering additional pageviews
- Key Resources: Passed; Expected that it will trigger a `nav-pipe-delimited-list-click` AND File Downloaded
- Nav Expands and Collapses: Passed
- Embedded links under the accordion: Passed using `nav-accordion-embedded-link-click`
- Featured content links in 'Latest Announcement from VA' section: Passed; Triggers `nav-featured-content-link-click`
- Link list for 'Other Resources to support your students' section: Passed; in cases where there is an accompanying PDF or other file, it correctly triggers both `nav-linkslist` and File downloaded event.

Intentionally not tracked based on Amy's comments:
- Upcoming Events: Links not tracked per comment above

Follow-up:
- Should the link below Policies & Procedures be tracked? 
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/8824fc5b-1e09-4383-90ff-d7af0c426a23)

**Comment by jonwehausen** [comment]
@nedierecel Thanks for your QA 👍 . 

Regarding the Policies & Procedures link, this wouldn't as of today fall under an existing design system strategy so doesn't have a DL push dedicated to it. 

This looks to be a standalone link and the only one of it's kind on the page so I'll let @amyknox make the call on need.

**Comment by amyknox** [comment]
@nedierecel & @jonwehausen - Would be great to have the "VA education forms, brochures, and fact sheets >" link tracked. Let's do it!

**Comment by jonwehausen** [comment]
Hi @amyknox, 

Thanks for being patient with us.  

After discussion with the team, we would like to track the **"VA education forms, brochures, and fact sheets"** and **"Required 2019 Training for SCO's"** links as part of our link list convention. 

If we could have the following event code put on those two links we can wrap up 👍

```javascript
dataLayer.push{(
  'event': 'nav-linkslist',
  'links-list-header': 'Training and Guidelines' //or Policies and Procedures, put the header text here
)};
```

**Comment by jonwehausen** [comment]
Tested functionality described in @nedierecel's post above has also been published and is now live.

**Comment by amyknox** [comment]
> Hi @amyknox,
> 
> Thanks for being patient with us.
> 
> After discussion with the team, we would like to track the **"VA education forms, brochures, and fact sheets"** and **"Required 2019 Training for SCO's"** links as part of our link list convention.
> 
> If we could have the following event code put on those two links we can wrap up 👍
> 
> ```js
> dataLayer.push{(
>   'event': 'nav-linkslist',
>   'links-list-header': 'Training and Guidelines' //or Policies and Procedures, put the header text here
> )};
> ```

@desireeturner  ^^ Need dev support on this final push for SCO page analytics.

**Comment by zurbergram** [comment]
For https://github.com/department-of-veterans-affairs/va.gov-team/issues/3055#issuecomment-562310196
see https://github.com/department-of-veterans-affairs/vagov-content/pull/606

**Comment by jonwehausen** [comment]
@zurbergram Keep me posted on when this becomes available in staging. Thanks for your assistance.

**Comment by jonwehausen** [comment]
Confirmed this looks good in staging. Closing. 

![image](https://user-images.githubusercontent.com/48527022/70632952-b83e7c00-1bfd-11ea-85c9-5a5fec2d442b.png)
