### ISSUE TITLE
[Design] Create Mockups for HLR Address Flow

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#3056]
## User Story
As a claimant, I want to provide my current address on the Higher Level Review form so that the VA is aware of my latest mailing address. 

## Goal

Visualize how the user will navigate the address update flow on the HLR form process.

## Acceptance Criteria

- [x] Understand the data implications of the technical option chosen (Lighthouse API takes in an Address, does no validation at all, uses the Address to build the PDF)
- [x] Determine the flow of address update via the HLR form process
- [ ] Create Mockups of the HLR address flow (if needed)

**Comment by carolynwill** [comment]
Discovery work needed. Reach out to Arthur on Authenticated Experience.

**Comment by YanaRoy** [comment]
Mock ups not needed since the form will maintain the same design following the decision made during discovery - Lighthouse API takes in an Address, does no validation at all, uses the Address to build the PDF.
