### ISSUE TITLE
Access for Jay Darnell

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-team#30561]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Jay Darnell

### Your Email

jay.darnell@civicactions.com

### Name of Your Team

VFS-CMS - CivicActions (Agile Six)

### Service(s) You Want Access To

SOCKS (Requires public ssh key)

### Public SSH Key

```shell
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDW1cdMYtBT4ZrcUD3JF+kxikRlACkricD8VtmtibfQgzMGtPGfqgGxZOi9j5UYUcDWvn5xHGk9yLVuyUxjxxNCU4HFtt0Ybyndnajc6BbBnWERICAGC9OrOf3KxIYD/J6omfKx8RcZ/egsV4BS+Chztmlrp8k9sRVwvSLgbRpMwIHhzBzPw7rgpAr61CZbzOAIcdj1ZK9hUY7X+v52/jNnyjol6HO6JPv+4ecXvMR5ObBZpvZmhuQSbVG3K0bBO9v34Z6TTr0f752EpCTOf9jYrLacWTU5Zeha8nsVR+5gHA2HkS2KcBkrCc/wMQO8n5TvgHWp5QfRBgjz8HN2OA3sPQkgogkrHbYeP3xEeR9soGa0b1mb/7rJtleT52dXOHaxqxRo0n8EVHD2PP6uieF5b42oegmew+mWxpodNCtwXU6HYJRrF0BwO04abC3j3WgVgET6tk5FqL3sqv75C/eUUHNfZPQ5PJHbEyTu/UCP3Vbf4n/t/8WnKtJBFtVuKc8= jaydarnell@Jays-MacBook-Pro.local
```

### Desired AWS Services

No

**Comment by rwilliams-oddball** [comment]
Added Access, please let me know if you have any issues.

**Comment by JayDarnell** [comment]
Thank you kindly Robert. I believe I'm good to go.
