### ISSUE TITLE
Address Bugs in Rated Disabilities on Staging

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3058]
## Story
As a Veteran looking at the Rated Disabilities Tool page, I want to view it without any display issues so that I don't get confused.

## Considerations
- It seems like disabilities which are non-service related return `null` for `effectiveDate` and `ratingPercentage`. If this is the case, this needs to be handled gracefully in the UI for the rated disability content card / list.
- Disabilities may be returned with no associated data in their `specialIssues` array. This means the `Related To` field must be hidden as it would display a blank value. Code needs to be updated to address this scenario.
- [Mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/)
## Tasks
- **Address Empty Data Fields:** For individual ratings that return no percentage because there is no value, there should be nothing displayed.  Right now, when this occurs, there is a lone percentage sign.

## Acceptance Criteria
- [x] [When testing with a test account](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/README.md#how-to-access-and-test) that has non-Service-Connected cards in it, the card will still display its information but the card will not have a rating  or percentage in the upper right corner of the card.

**Comment by micahchiang** [comment]
Sample data response from a user with non-service related disabilities:

```{
  "fetchRatedDisabilities": "fn()",
  "ratedDisabilities": {
    "ratedDisabilities": [
      {
        "decisionCode": "NOTSVCCON",
        "decisionText": "Not Service Connected",
        "diagnosticCode": 6260,
        "name": "Tinnitus",
        "effectiveDate": null,
        "ratedDisabilityId": "1046370",
        "ratingDecisionId": "134241",
        "ratingPercentage": null,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "SVCCONNCTED",
        "decisionText": "Service Connected",
        "diagnosticCode": 5260,
        "name": "Allergies due to Hearing Loss",
        "effectiveDate": "2012-05-01T05:00:00.000+00:00",
        "ratedDisabilityId": "1072414",
        "ratingDecisionId": "134242",
        "ratingPercentage": 10,
        "relatedDisabilityDate": "2018-12-22T02:12:08.000+00:00",
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "NOTSVCCON",
        "decisionText": "Not Service Connected",
        "diagnosticCode": 7913,
        "name": "Diabetes",
        "effectiveDate": null,
        "ratedDisabilityId": "1090859",
        "ratingDecisionId": "134243",
        "ratingPercentage": null,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "SVCCONNCTED",
        "decisionText": "Service Connected",
        "diagnosticCode": 6100,
        "name": "Hearing Loss",
        "effectiveDate": "2005-01-01T06:00:00.000+00:00",
        "ratedDisabilityId": "1128271",
        "ratingDecisionId": "134244",
        "ratingPercentage": 100,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "SVCCONNCTED",
        "decisionText": "Service Connected",
        "diagnosticCode": 8540,
        "name": "Sarcoma Soft-Tissue",
        "effectiveDate": "2018-08-01T05:00:00.000+00:00",
        "ratedDisabilityId": "1124345",
        "ratingDecisionId": "134245",
        "ratingPercentage": 0,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[1]"
      }
    ]
  },
  "user": {
    "login": "Object",
    "profile": "Object"
  },
  "totalDisabilityRating": 80,
  "loading": false,
  "error": false
`}```

**Comment by micahchiang** [comment]
UI bugs:
<img width="596" alt="Screen Shot 2019-11-01 at 12 47 49 PM" src="https://user-images.githubusercontent.com/15097156/68053498-4e9b8b80-fca9-11e9-84ff-aa66937f7dbb.png">

**Comment by micahchiang** [comment]
@sporeboy - Saw that you self-assigned. Are you planning on coming up with a new mockup for disabilities that are not service related?

**Comment by micahchiang** [comment]
Confirmed with Silvio, who confirmed on the EVSS sustainment call that `ratingPercentage` and `effectiveDate` will **always** come back as `null` for for non-service-connected disabilities.

**Comment by micahchiang** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/11075
