### ISSUE TITLE
Research and Implement Synthetic Monitoring Dashboard MVP

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30595]
## Product Outline
TBD

## High Level User Story/ies
As a Platform stakeholder who depends on synthetic monitors to alert on production issues, I need metric data so I can understand the effectiveness of synthetic monitors and identify improvements.

## Hypothesis or Bet
**If** we create a dashboard of synthetic monitor metrics **then** we expect to be able to identify areas for improvement in existing monitors, identify opportunities for new monitors, and understand the effectiveness of our suite of synthetic monitors.

## OKR
O4 -- Best practice testing process and tools

## Definition of done

* Identify metrics
* Ingest data from synthetic monitors into long term storage
* Design a query to select relevant data from long term storage for use in Visualizations
* Create cards in DOMO for top 3 metrics

**Comment by JoeTice** [comment]
This work has been deprioritized by Rachael, based on our recommendation that further development into this was not worth the effort at the current time.

**Comment by pjhill** [comment]
OBE
