### ISSUE TITLE
[Design] Notifications: Implement section design considerations  

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30607]
## Background
...

## Tasks
- [ ] Implement designs to differentiate between sections of alerts (e.g. health care vs. covid reminder)
- [ ] Outline what each section is and what it includes

**Comment by ajakabcin** [comment]
Consider for post-MVP

**Comment by hdjustice** [comment]
Unassigning and closing ticket - Due to the MVP revisit, we are no longer pursuing the Notification Center design at this time.  This scope change renders this ticket unnecessary.
