### ISSUE TITLE
508-defect-2 [Focus]: Focus bugs with nested accordions in mobile menu

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#30603]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Details

Angela and I came across several bugs when testing the mobile navigation menu the other day. Here's a list of steps on how to recreate the issues along with the issue descriptions:

1. Open a browser window with a narrow width that activates the mobile menu
2. Using your keyboard, open the mobile menu with `enter`
3. Tab to VA benefits and healthcare and expand it with `enter`
4. Tab to healthcare and expand it with `enter`
5. **Confirm focus is lost**, a second `tab` is necessary to set focus back on "Back to menu"
6. Tab back to "back to menu" and return up a level with `enter`
7. **Confirm focus is lost** (or focus halo isn't visible), a second `tab` is necessary for the focus halo to return
8. Tab to disability and expand it with `enter`
9. **Confirm focus is lost**, a second `tab` is necessary to set focus back on "Back to menu"
10. Tab back to "Close X" and collapse the menu with `enter`
11. Reopen the menu with `enter`
12. **Confirm focus is locked on the menu button** and `tab` does not move the focus to the menu's contents

https://user-images.githubusercontent.com/14154792/135116313-a33e9b61-eb17-4a10-8865-4174ec2417e4.mov

## Acceptance Criteria

- [ ] Focus is not lost when expanding and closing sub accordions in the mobile menu
- [ ] Focus does not lock onto the menu button after navigating through the sub accordions

**Comment by laflannery** [comment]
This is no longer occurring, closing
