### ISSUE TITLE
Diagram VAOS auth flow

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#30604]
We would like to diagram the VAOS authentication flow with additional details for benefit of the backend team. Some of these details would include interactions with the user service, and how user profiles are generated with MPI. This work would be to step through and create the relevant visualization for this process.

Related auth diagrams: https://github.com/department-of-veterans-affairs/va.gov-team/blob/mobile-ssoe-design-doc/platform/engineering/design-docs/2020-08-12-mobile-ssoe-auth-design-doc.md

AC
- [ ] Flow diagram is created for VAOS authentication

**Comment by ajmagdub** [comment]
Added VAOS Auth flow documentation to:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/architecture/vets-api-user-creation-session-validation.md

**Comment by laurenernest** [comment]
@grossb1 @cferris32 anything you need to review before we close this one?
