### ISSUE TITLE
VADIR data - Follow-up

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#30602]
## Issue Description
We would like to be able to automatically incorporate medals data

---
## Tasks
- [x] Follow up with VA Profile team and see if their work is complete. Gather contacts and information needed to implement feature on our end. Reference this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26066). 

## Acceptance Criteria
- [x] Data availability determined. Documentation/contacts noted.
---

**Comment by chrvalla** [comment]
This is no longer necessary. Working with Paul Shute on an alternative way to remove PTSD questions from Form 526. Close ticket.
