### ISSUE TITLE
Adding Natasha Jimenez to DSVA Slack

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/va.gov-team#30639]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

**Please add natasha.jimenez@thoughtworks.com as a Full Member.**

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

**Natasha Jimenez is a designer joining the VANotify Team. She will need access to collaborate with the team.**

We aim to complete slack requests within 24hrs.

**Comment by LizCallaghan** [comment]
done!
