### ISSUE TITLE
Adding Jessica Sexton to DSVA Slack

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#30645]
# Description
Please add Jessica.Sexton@libertyits.com as a full member guest to DS@VA Slack space and the following channels: 
- #vfs-evss-service-migration                           
- #va-forms                   
- #vfs-all-teams
- #vfs-benefits
- #victories
- #oncall                                
- #general                       
- #random    
- #slack-workspace-admin
- #vfs-platform-builds          
- #vfs-platform-support
- #vsa-claims-appeals
- #vsa-ebn-migration

Jessica is an Associate Product Manager in the Lighthouse Program supporting me on the Matsumoto Team which maintains the Forms API, the Benefits Intake API, and is working to modernize some EVSS backend services and bring them into the lighthouse program as modern microservices.

**Comment by LizCallaghan** [comment]
Just a FYI, she was already in a lot of these channels. Not sure why they were listed as her needing access, but I went through each one individually to verify.

**Comment by jlsexton** [comment]
Thank you, I am able to access all channels and now have the Digital Service @ VA workspace added.

**Comment by NCHLiberty** [comment]
Thank you @LizCallaghan. Everything seems to be good now. Just as an FYI something strange happened with her...she was in there a few weeks ago and in many of those channels, and then disappeared. Thanks for your help. :)
