### ISSUE TITLE
[FE] Profile: Issues with delete contact info confirmation modal

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#30652]
There are some issues with the delete contact info confirmation modal.

- The "cancel" button does not work
  - Related: we probably want to be able to tap `escape` to close the modal
- When the browser width is greater than mobile width, but the modal will not scroll which is a problem if the window is short. The modal _does_ scroll if the window is narrow enough. **This is the most critical issue.**

https://user-images.githubusercontent.com/20728956/135282145-27c934f7-f46f-4102-9c63-bba8871aa44c.mp4

**Comment by erikphansen** [comment]
@ajakabcin @tmitchellgcio for your awareness.

**Comment by tmitchellgcio** [comment]
Oh wow. Thank you for finding this out. Assign this to me @ajakabcin. Should this be done immediately or next sprint?

**Comment by erikphansen** [comment]
This seems pretty important. I'm guessing the non-scrolling issue affects phones in landscape, among other things. I'd do it ASAP. But it's AJ's call.

**Comment by tmitchellgcio** [comment]
That's what I was thinking

**Comment by tmitchellgcio** [comment]
@ajakabcin ready for validation once deployed

**Comment by erikphansen** [comment]
@tmitchellgcio The cancel button works now, but it still will not scroll vertically when simulating a phone in landscape mode.

**Comment by tmitchellgcio** [comment]
@erikphansen the latest update should fix that now

**Comment by ajakabcin** [comment]
Confirmed on staging - thanks @tmitchellgcio !
