### ISSUE TITLE
form 526 special issues 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#30651]
## history
In 2018, there was code that included special issues for disability compensation.  However, [special issues prefills](https://github.com/department-of-veterans-affairs/vets-api/pull/2243) were removed because EVSS returned an error.  

In January 2020, we learned that EVSS [fixed a bug related to special issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18924).  At that time we verified that we weren't using special issues (other than POW) and carried on.  BUT [original research ](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13989) suggests that special issues will benefit routing in the national work queue and should be used (if EVSS accepts them).

Lighthouse has done some recent work with special issues that looks like it might be reusable. they
[send special issues to BGS](https://github.com/department-of-veterans-affairs/vets-api/blob/e934b2a4ec7b0025027d5124ca3337d5032fea2e/modules/claims_api/app/workers/claims_api/claim_establisher.rb#L40) @SlakrHakr would probably be a great resource

## How special issues work 
When a veteran files for increase of a disability we get "special issues" as part of the rated disability.  When the veteran selects that disability for increase we can preserve that attribute from EVSS and return it, so that the claim is properly processed through the national work queue.  

## tasks
- [x] #31082
- [x] #31086
- [ ]  FE if the FE receives a rated disability with a special issue, that data should be preserved/included on submit (front end already does this, so no specific work needs to be done here)

## Open questions
EVSS only accepts the following special issue codes `[ ALS, HEPC, POW, PTSD_1, PTSD_2, PTSD_4, PTSD_3 ]` Should the BE or the FE be the one to filter that list?  note: evss documentation used to have slashes instead of underscores like `PTSD/1` that never worked -  _At this point, leave the front end agnostic as far as special issues, have the BE filter them because this seems more like a back end logic issue, SEs are not visible on the front end, they are just an attribute on the claim that is not displayed._ 

The previous implementation of the issues code was done when veterans could only apply for increase on va.gov (I think). How should we handle when a veteran enters new disabilities?

Lighthouse has a longer list of special issues that gets sent to evss than [EVSS documentation](https://www.ebenefits.va.gov/wss-form526-services-web-v2/swagger-ui/index.html?url=https://www.ebenefits.va.gov/wss-form526-services-web-v2/rest/swagger.yaml#/form526/submit) - why? https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/lib/claims_api/special_issue_mappers/evss.rb
Maybe hints in:
https://github.com/department-of-veterans-affairs/vets-api/pull/5504 

EVSS only accepts a subset of special issues do we send issues to EVSS or just BGS.

**Comment by vhenry07** [comment]
This work is being done by the Benefits RRD Health Evidence team.
