### ISSUE TITLE
B:[03/18/22] Build out a Template Library for Text Messages

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#30661]

**Comment by jwowk** [comment]
The message template library was started at this link:
https://dvagov.sharepoint.com/sites/vhavetext/Lists/MessageTemplates/AllItems.aspx

This only includes the default message templates. The goal is to have a list of generic/approved verbiage for various message types or use cases. These can be curated from existing templates in use by other sites and/or allow submission from other sites for addition to the catalog. Sites frequently ask if we have examples and this would be a way to proactively provide recommended templates for common message types.

**Comment by lindsay-insco** [comment]
Ongoing updates with template message cutdown

**Comment by lindsay-insco** [comment]
Template library compiled with most common message language
