### ISSUE TITLE
Feature Toggle: Add Indian question to the 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30671]
## User Story
As a Native American, I want to be able to specify that fact during enrollment on the 10-10EZ, in order to receive appropriate VA Health Care.

## Expected Behavior

The purpose of this story is to add a feature toggle to be able to turn this question on/off. We may launch this functionality into production before the Enrollment System is ready to receive the value. Therefore we need to be able to have it turned of in production.

## Acceptance Criteria

- [x] When the feature toggle is off, the Indian question should not be displayed on the 10-10EZ

Note: this question will be launched separate from the SIGI question

**Comment by LinnJS** [comment]
Naming toggle `hcaAmericanIndianEnabled` on frontend and `hca_american_indian_enabled` on backend

**Comment by LinnJS** [comment]
BE [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/8403) for feature toggle
FE [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19340) for feature toggle
