### ISSUE TITLE
Content request from Decision Tools team

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#30675]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
Suggestions on how to tighten up the content in a modal.   It needs to convey that Adobe Reader for Mac or Windows is necessary to fill out the forms electronically, but forms _can_ still be printed & filled out manually.   

We also could use a recommendation on what to say instead of the Adobe link on mobile devices since Adobe Reader on mobile  devices does not allow users to fill out 99% of our forms (it displays the form then tells them to download Reader for Mac or Windows).
  
## Supporting Artifacts
- User story for modal mockup: #29704
- Most up-to-date mockup: 
![image](https://user-images.githubusercontent.com/73354907/135308903-262c840a-724b-40b1-90b4-fb262c492902.png)

- Link to product outline:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md
- Link to or attach user flows:
- Link to prototype or mockups:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/29704#issuecomment-925136298
- Link to any epics/issues that may be helpful:  

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:  Find a Form tool is already live; this is an enhancement to resolve an issue we observed in user testing.
- Estimated staging review date:  mid-October
- Content and IA work needed by: as your workload allows

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed
- [X] I shared the mock-up at office hours on 9/29/2021

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner:   Dave Conlon
-	Product manager:  Marci McGuire
-	Designer:  Cassandra Allen
-	FE engineer: Zach Morel
-	Product/team Slack channel: #vsa-decision-tools

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO I'm looking at this now. Does the user specifically need Adobe Acrobat DC? In the R&S article, we say, "Adobe Acrobat Reader." Do you know which is accurate?

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO Adobe Acrobat Reader DC for Windows or Mac is what the error message says is required when a PDF won't load on a mobile device.

That's also the one available on Adobe's site right now.

![image](https://user-images.githubusercontent.com/73354907/135506286-6dd267a9-4e0b-4e7a-8f75-bb4d522df445.jpeg)

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO Also, if a user wants to print out the form (i.e., they don't need Acrobat Reader), are you saying we want to convey that they can just print the form from their browser? Is that right?

**Comment by MarciMcGuireGCIO** [comment]
That's correct.  If they don't need to fill it out electronically, and it will load in the browser or other PDF viewer, they can print it.

**Comment by bethpottsVADEPO** [comment]
OK, I'm still futzing a little bit with this today, but want to see if you think I'm heading in the right direction. Does this cover the issues we wanted to clarify that came up in research sessions?

<img width="966" alt="Screen Shot 2021-10-01 at 2 18 58 PM" src="https://user-images.githubusercontent.com/66026798/135670570-09c56046-99a0-412f-887b-3edb1762a447.png">

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO OK, I'll finish refining it and then will upload a final version. Just wanted to make sure I had the substance of it covered. I know there's a separate ticket for me to make updates to the R&S article too! I'll be able to get to that next week.

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO - Zach and I will be finishing out this task after all.  @RLHecht did express some concern at office hours last week that there was too much copy (that was prior to your changes).  Would it be possible for you two to put your heads together?  Thanks!  cc @zacharymorel
