### ISSUE TITLE
[Backend] Add Indian question and submit on 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30674]
## User Story
As a Native American, I want to be able to specify that during enrollment on the 10-10EZ, in order to receive appropriate VA Health Care.

## Expected Behavior

The purpose of this story is to receive the value of the new indian question (Y/N) from the Front End, add it to the payload, and submit the value to the Enrollment system (ES) with form submission.

## Acceptance Criteria

  - [x] Value received from front end
  - [x] Value prepped and sent to ES in appropriate format
  - [x] Update specs

**Comment by jchilders** [comment]
Validated locally by examining inbound request traffic (web -> API), then examining the generated SOAP data. Everything looks good as far as I can tell.
