### ISSUE TITLE
[FE] Add Indian question to the 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30672]
## User Story

As a Native American, I want to be able to specify that during enrollment on the 10-10EZ, in order to receive appropriate VA Health Care.

## Expected Behavior

The purpose of this story is to add the new Indian question to the 10-10EZ. The new question is a yes/no question.

UX Design Ticket: #28975
UX Content Ticket: #30349
[Design and content PDF](https://app.zenhub.com/files/133843125/fadd9963-61bb-4b54-9590-61c240a9fc26/download)

## Acceptance Criteria

- [x] Question behind feature toggle
- [x] New question and content added to the 10-10EZ (following the race, ethnicity, origin checkbox question)
- [x] Designer checks off in RI (SOCKS)
- [x] Value submitted to the vets api backend
- [x] Successfully tested end to end

**Comment by Dene-human** [comment]
[Design and content PDF](https://app.zenhub.com/files/133843125/f07bcf36-34fd-4d98-93b7-ef2510de2c42/download)

**Comment by Dene-human** [comment]
During the last HEC meeting (10/27) they requested that the question be changed back to "Are you an Indian?"

George and Danielle are following up with the Office of Tribal Government Relations to better understand the process and language.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19341) where this work is being done.

**Comment by MickinSahni** [comment]
@LinnJS @charCodelet to sync on who's wrapping this up

**Comment by MickinSahni** [comment]
CI/CD failing due to other tests. Need to sync with Platform to resolve those

**Comment by MickinSahni** [comment]
Built and @LinnJS to share RI
