### ISSUE TITLE
[FE] Update content for Birth Sex question based on SIGI changes on the 10-10EZ

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30670]
## User Story

**As a** Veteran, **I want to** specify my Birth Sex **in order** to submit my application for VA health care.

## Expected Behavior

The purpose of this story is to update and expand the content on the Birth SEx question on the 10-10EZ. With the SIGI update, we will be adding a new question to allow the Veteran to specify the self-identified gender identity. Therefore, we need to update the existing Gender question to clarify that it is asking for the Veteran's birth sex. The design for this question has been updated as part of the new design for SIGI.

We had previously split Birth Sex into its own page, therefore we should have plenty of space for the new content.

Design Ticket: #25412

## Acceptance Criteria

- [ ] Designer signs off on content, design, and UX via Review Instance
- [ ] Confirm no breaking changes via schema modifications
  - See https://github.com/department-of-veterans-affairs/vets-json-schema/pull/655/files#r746012525
- [ ] Content on the Birth Sex screen is updated
- [ ] Successfully tested end to end

**Comment by Dene-human** [comment]
Updating ticket to keep feedback in one place.

As per slack:
- Review instances received on 10/29 (Friday afternoon) for Birth sex, marital status, and race questions.
- Feedback given 11/1 (Monday)

Feedback: Please check the URL and ensure proper treatment of birth sex in lieu of additional SIGI question.

**Comment by MickinSahni** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/19337

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19337) where this work is being done

**Comment by MickinSahni** [comment]
## Prod (unauth)

<details>

![image](https://user-images.githubusercontent.com/13204473/142287386-ea2f6bbb-70cc-4842-a309-bbff417877b6.png)

</details>
