### ISSUE TITLE
Request access to Google Analytics 

### ISSUE THREAD

**Issue by aryeh-usds** [department-of-veterans-affairs/va.gov-team#30688]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [x] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [x] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jennaouellet** [comment]
Access has been granted to jessica.robertson2@va.gov

**Comment by aryeh-usds** [comment]
Thank you!

From: jennaouellet ***@***.***>
Sent: Wednesday, September 29, 2021 2:56 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Jacobsohn, Aryeh ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics (#30688)


Access has been granted to ***@***.******@***.***>

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F30688%23issuecomment-930455752&data=04%7C01%7C%7C5e74d11a674043f7416808d9837adec8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637685386022482587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BcDqYQJvuYQmgrJuoI3Tz16DTMKZMkF3VVZaBTysihI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASA6R2PWHJ5P7ELYEY7PAP3UENONJANCNFSM5FANHMWQ&data=04%7C01%7C%7C5e74d11a674043f7416808d9837adec8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637685386022492543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kH8RcXU9dIFeZvGhdeqivTb5QIiLVrGclhkc3muTE5g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5e74d11a674043f7416808d9837adec8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637685386022502494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O9ZNRp5nAcr%2FpReGRkyUyw%2FZYtDU6V0%2BfNXK82eNq%2BQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5e74d11a674043f7416808d9837adec8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637685386022502494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SJRsoUfyP53EB7B5xX%2BffoFRY6rKFwzJzfdLsxL9e5Y%3D&reserved=0>.
