### ISSUE TITLE
VA.gov Testing Tools - Define solution approach to solve VA.gov testing / demo'ing / QA'ing challenges

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#3070]
## Product Outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/preview/product-outline.md

## Problem Statement
We have had trouble moving forward on efforts to be able to better test VA.gov because there are a lot of large systemic blockers to any robust solution we may want to undertake. But in order to scale builds safely, we must figure out a way to drive past those blockers and enable Call Centers, VFS Teams, and VSP Triage personnel to demo apps, QA all product path scenarios, and replicate user problems easily. What solution might we recommend for delivering a solid solution to these testing challenges, and what dependencies do we have on groups across VA in order to do so?

## Objectives
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## KPIs
- Reduction in the number of test account support requests
- Reduction in time to find a test account to QA a new test case.
- Reduced abandonment of test cases because people cannot find the right test account or staging is down.
- Increase in demos being done on staging.
- Increase in job satisfaction from call center reps.

## Hypothesis/(es)
If we run a 5-day cross-functional discovery sprint on this problem space, we'll be able to recommend a holistic solution to this problem space for teams to begin implementing.

## Goals
- Validate and expand upon the problem statement by identifying specific examples of where the current way of doing things is breaking down
- Understand the solution that best balances user needs with technical opportunities and political landscape
- Understand which groups across VA will need to also take on work in order for us to, together, provide a meaningful solution
- Empower Charles and Chris with the value statements and clarity they need to shop this idea with other groups and get it prioritized on their roadmaps
- Hand off for implementation

## Definition of done
- Discovery brief presented to VSP Clients + Leadership, Chris Johnston, Jeff Barnes, and Charles Worthington
- Product Outline updated (incl w/KPIs)
- Epic(s) and top priority user stories are in ZH, ready to be further groomed and picked up by implementation team(s)

**Comment by rroueche** [comment]
Comments / additional notes:
- We need to be able to reproduce issues that users are seeing. Don’t limit ourselves to Staging.
- There are some useful comments from users in the [parent super-epic](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/1326) to consider as a part of discovery
- Will be great to see what kind of positive impact this can have on UAT, so we can QA more ourselves and reserve UAT for what it's meant to be for: usability, discoverability, more nuance. We we save a lot of our time/resources/Veteran time if we’re able to take that scenario testing on ourselves instead of relying on UAT for it.
- Sprint should include: James, Naomi, JP, Keifer, anyone else?
- Need to involve Leah / Patrick in appropriate way, we'll need their help and CTO help driving convos across VA to get buy-in for dependent system updates.
- Another thing we want to evaluate w/this effort is, could this be a good model for discovery (i.e. Service Design team leading deep dive / solutioning sprints like this outside of their normal cadence of work)? Or is it not quite the right fit?
- Leah and JP are in the process of collecting user and technical context for the sprint team to have going into it.
- Here's the [VSP Discovery Kit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/discovery-sprints/discovery-project-brief.md) to use for planning the sprint

**Comment by rroueche** [comment]
- Discovery sprint planned for Sprint 13
- Thurs/Fri (11/14, 11/15) finalize discovery sprint plan
- Sprint for 5 days starting: 11/18

**Comment by jchasia-adhoc** [comment]
Recommendations and readout from the discovery and design sprint: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/product-discovery/testing-discovery-readout-v2.pdf

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this since it's no longer a priority.
