### ISSUE TITLE
[Monitoring and Alerting] Set up new workflow for Ops-managed services

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30718]
## Product Outline
[Infrastructure Monitoring using DataDog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593917/Infrastructure+Monitoring+using+DataDog)
[Alerting using Prometheus and PagerDuty](https://vfs.atlassian.net/wiki/spaces/OT/pages/1548386403)

## High Level User Story/ies
As a platform operations devops engineer, I need monitoring set up for the services that I manage so that I can keep them running smoothly. 
As a platform operations devops engineer, I need alerting set up for the services that I manage so that I can keep be alerted to any issues that arise. 
As a platform operations devops engineer, I need alerts for services to be actionable/useful so that I am not spammed with unnecessary information. 

## Hypothesis or Bet
If we set up monitoring and alerting according to our new alerting guidance, platform operations devops engineers will be able to respond with grace and confidence to any issues that arise with services that they manage. 

## OKR
O3: Platform security and stability approach is comprehensive, on par with industry leaders

### New monitoring and alerting workflow has been set up for the following services: 
- [x] Grafana
- [x] Loki (done in previous initiative)
- [x] Traefik

### Playbook describes how to set up a monitoring and alerting for new services

**Comment by mchelen-gov** [comment]
i think "new workflow" refers to https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting#Preferred-Alerting-Workflow%3A ?

**Comment by jhouse-solvd** [comment]
We'll be creating issues to iterate on alerting for specific services as the need arises. 

For example: 
- #43859
- #45683

This issue can be closed.
