### ISSUE TITLE
Discovery: Medical Form 2346 (Hearing aids and prosthetic sock order device) schematic diagram 

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3071]
#User Story
--
As a Frondend Dev, I needed to have a global understanding of the process.

#Discovery Questions
--
What data is needed so that the user can complete the process?
Where is the database the information is stored on?
Identify the service or stack that may house the endpoints?
Define those endpoints and discuss with other team members?

#Constraints/Assumptions
--
TBD. This is a first dive into better understanding how Vet order hearing aids and prosthetic sock

#Accepts Criteria
--
- [x] A diagram of the process with database and endpoints mapped out_

#Next Steps
--
Validate diagram with VA and Stakeholder

#Blocker
--
DLC Stakeholder Meeting.

**Comment by mojaray2k** [comment]
@wygonikGCIO The current acceptance criteria is what we need @jobro I am adding you to this thread also.
