### ISSUE TITLE
[Monitoring and Alerting] Set up new workflow for Traefik

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30717]
## Description
Apply the new workflow developed during the PagerDuty redesign (lessons learned from Loki monitoring tasks) to other Ops-managed services

- Things we need to alert on re: Traefik
  - Pods are not running (separate from the generic monitors that we have currently configured, but maybe use those as a template for this)
  - 

## Background/context 
Alerting guidance documentation [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting)

## Technical notes
- Traefik metrics are already going into DataDog
- There is a dashboard for Traefik already: https://app.datadoghq.com/dashboard/bcv-vf4-qpp/traefik-eks-network?from_ts=1634312819969&to_ts=1634316419969&live=true

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jbritt1** [comment]
Couple notes for me later:

- What is our current process for alerting (prom, datadog, pagerduty, etc.)?
- Are metrics going to Datadog?
- Do we have the necessary dashboard(s) and monitors in place?
  - Are they clear, concise, and actionable?
- If this service was migrated, should we leverage older / existing alerting rules? Can they be translated to Datadog monitors?

Solid reference: Loki-canary

**Comment by jbritt1** [comment]
Synthetic checks are live and looking good ![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/c3ebfeed-9260-426d-98b6-2a635f3c2062)

**Comment by jbritt1** [comment]
In my opinion, this is closable at this time.
