### ISSUE TITLE
[PM] 10-10EZ - SIGI: Update Domo/Analytics for new page

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30728]
## User Story

As VA.gov user, I want to be able to report on the 10-10EZ after the SIGI update, in order to have accurate metrics.

## Expected Behavior

As part of the self-identified Gender Identity (SIGI) question that is being added to the 10-10EZ on its own page, this will have an impact on our Domo dashboards for the purposes of funnel analysis/exit rates.

## Acceptance Criteria

- [ ] [Submit a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D) to the Analytics team, requesting an update to our current Dashboard

**Comment by markfallows** [comment]
Should this still be in the Icebox?

**Comment by markfallows** [comment]
Ticket is very out of date.

Is a reminder for us to submit a ticket to the Analytics team for the introduction of the SIGI question.

**Comment by hdjustice** [comment]
Closing all SIGI tickets - There has been no further movement or discussion on this topic
