### ISSUE TITLE
Notification Settings: Add `name` attributes to each radio button

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#30734]
Tabbing through the page treats all of the radio buttons as if they are one group. https://github.com/department-of-veterans-affairs/va.gov-team/issues/30341#issuecomment-929468178

**Comment by erikphansen** [comment]
@andaleliz Tabbing now properly moves from one radio button group to the next without skipping any. Do you want to validate that on staging?

**Comment by andaleliz** [comment]
Yep, looks good on staging! Thanks!
