### ISSUE TITLE
Discovery: Demo the Medical device tool "Form 2346"

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3073]
#User Story
--
As a Frontend Dev, I need to walk though the current medical ordering device tool in order to better understand the current medical devices pros and cons and how they may impact the Users

#Discovery Questions
--
TBD

#Constraints/Assumptions
--
Gaining access to the tool. May have constraints about getting dev environment set up. 
This is a first dive into better understanding how Vet order hearing aids and prosthetic sock

#Acceptance Criteria
--
- [ ] _Complete walk through from authenticating user to submitting purchase_ 
- [ ] _An artifact documenting comments and inputs from the Front-end Dev_

#Next Steps
--

- [ ] Create a Content inventory list.
- [ ] Create a Mock up of the tool

#Blocker
--
- [ ] Gaining access to the test environment.
- [x] Requires meeting with the DLC to gain access to the tool

**Comment by mojaray2k** [comment]
@wygonikGCIO Can you provide a link to this tool?

**Comment by mojaray2k** [comment]
@wygonikGCIO I added one more goal to the acceptance criteria. And I am adding @jobro to this feed.

**Comment by MRosari0** [comment]
@wygonikGCIO Adding more points to the acceptance criteria.

**Comment by MRosari0** [comment]
@wygonikGCIO Making a note about meeting with DLC to avoid confusion with #3614

**Comment by mr0sari0** [comment]
Satisfied all requirements.
