### ISSUE TITLE
COVID-19 Vaccine Message Templates

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#30733]
Need a template for the following COVID-19 Vaccine templates:

- [ ] Rename message type to "Additional Dose/Booster" 
- [ ] Add button/checkbox to select appropriate template (default to additional dose)
- [ ] Assign template based on button/checkbox

**Comment by shanemelliott** [comment]
Direct
Appointments for a booster of the Pfizer-BioNTech COVID-19 vaccine are now available at %FACILITY_NAME% for eligible Veterans.
To schedule, reply with a DATE & TIME you're available from %START_DATE% to %END_DATE%
If you're not interested in getting a Pfizer booster, reply PASS.
If you've already received a Pfizer booster, reply VAX.
More info about COVID-19 vaccines: https://go.usa.gov/xASD8
One Way
Appointments for a booster of the Pfizer COVID-19 vaccine are now available at %FACILITY_NAME% for eligible Veterans.
To schedule an appointment, call %FACILITY_PHONE%.
If you're not interested in getting a Pfizer booster, reply PASS.
If you've already received a Pfizer booster, reply VAX.
More info about COVID-19 vaccines: https://go.usa.gov/xASD8

**Comment by shanemelliott** [comment]
@robertdurkin I added the templates here.
