### ISSUE TITLE
Run 508 onboarding meeting with VAMC team

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3075]
Tentatively scheduling for Monday, November 4th.

**Comment by SgardnerPMP** [comment]
New issue items will be created to include download and install of "AXE" add on for chrome and firefox, understanding of 508 compliance categories and review of existing and new pages.  Consider items for next sprint.  Additionally, PdM will create standard cadence for 508 compliance testing after each sprint and then load capacity/buffer for changes determined by these tests.
