### ISSUE TITLE
CMS Onboarding KT Zoom for K8s DEV environment

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#30758]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Need to get access to push/deploy to K8s DEV for @ndouglas, @olivereri, @cweagans, @indytechcook and myself. 

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

https://dsva.slack.com/archives/CJYRZK2HH/p1633026297217900

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by olivereri** [comment]
@ElijahLynn We already have this open:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30196

**Comment by ElijahLynn** [comment]
> @ElijahLynn We already have this open:
> #30196

Thanks, this ticket was mostly just to have a Zoom chat with Matt. Closing.
