### ISSUE TITLE
Adding Haneen Abudayyeh to DSVA Slack

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#30750]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting to add haneen.abudayyeh@va.gov as a full member to DSVA Slack. She will be working as a Project Manager on the Digital Health Platform.

Please add to #digital-health-platform channel

**Comment by LizCallaghan** [comment]
done!
