### ISSUE TITLE
Discovery: interview VFS teams about static pages app

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#30756]
## Details 

Jeff, Rian, MPS, ??

Get a sense of their understanding of what the static pages app is 

What do they think it should be 

Get some ideas of their thoughts for questions below

Exploratory conversations

**Comment by k80bowman** [comment]
In general, what I heard from people is that we need to think about the static pages app not as one thing, but as a collection of separate applications. They have different purposes and may belong in different locations.
- Michael Pelz-Sherman and Ryan Leahy both said that it would be easier if their widgets lived in the content-build repo. Right now working with the static pages widgets means coordinating PRs and deploys between two repos.
- Michael Chiang, Kelson Adams, and Jesse Cohn all said that working with the static pages app was confusing.
    - The process is not intuitive, and while it may be well-documented, that documentation is disconnected from the app and not easily found. 
    - The existence of a separate process for creating page widgets means that we have multiple ways of creating React apps within the VA application.
    - It’s confusing to have widgets that are connected to other React apps but that live in a location separate from those apps.
- Jesse Cohn also suggested a couple of changes that are worth noting:
    - Break the static-pages app up, figuring out which location makes sense for each widget, including finding a way to move some standard widgets to the design system.
    - Find a way to automate a lot of the standardized infrastructure and set up that are currently required.

If we decide to split it up and move things around, though, we will need to be careful about a couple of different things:
- Many of the apps need access to feature toggles and, for now, that access is limited to Redux in vets-website. Could we get access to feature toggles in content-build?
- Whatever we do, we need to make sure we document any changes and clearly document how widgets should be created and used as we move forward.
