### ISSUE TITLE
Update Breadcrumbs Component documentation

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/va.gov-team#30752]
# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## This update is for:

- [ ] Content style guide
- [x] Component
- [ ] Pattern
- [ ] Utility
- [ ] Other

## What is the name

Breadcrumbs component

## What is the nature of this update?

- [ ] How to build this component/pattern
- [x] When to use this component/pattern 
- [ ] When to use something else
- [x] Usability guidance
- [x] Accessibility
- [x] Implementation
- [ ] Research insights
- [ ] Package information

## Additional Context

The Breadcrumbs component has little to no documentation on design.va.gov and should be fleshed out to include usage, IA and accessibility guidelines.

**Comment by caw310** [comment]
@GnatalieH , is this still needed or were these items addressed when we made updates in Q2 to improve consistency?

**Comment by GnatalieH** [comment]
@caw310 we can close this ticket as all the items were addressed.
