### ISSUE TITLE
Synthetic Monitors: Identify Metrics

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30761]
# Description
Let's consult stakeholders about what kind of metrics would be useful for analyzing Synthetic Monitors.

## Some Ideas for metrics
Number of times a canary fails per day
Number of times a canary alerts per day
Heat map for the time of day that the canary alerts
Number of times action is taken by oncall engineer to resolve canary
Number of times canary self-resolves

**Comment by JoeTice** [comment]
This work has been deprioritized by Rachael, based on our recommendation that further development into this was not worth the effort at the current time.

**Comment by pjhill** [comment]
OBE
