### ISSUE TITLE
Synthetic Monitors: Create Visualizations for Top 3 Metrics

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30764]
# Description
As an MVP for the synthetic monitor dashboard, we need to identify the top 3 metrics that Platform wants to visualize and implement them in the chosen dashboard.

## Acceptance Criteria
- [ ] Visualizations for the top 3 identified metrics are complete
- [ ] Visualizations have been previewed by stakeholders and their feedback has been collected

**Comment by JoeTice** [comment]
This work has been deprioritized by Rachael, based on our recommendation that further development into this was not worth the effort at the current time.

**Comment by pjhill** [comment]
OBE
