### ISSUE TITLE
Synthetic Monitors: Ingest Data from AWS into Dashboard Tool

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30762]
# Description
We need to ingest data from sources relevant from synthetic monitors.

## Data Sources
* AWS Cloudwatch
* PagerDuty

**Comment by JoeTice** [comment]
This work has been deprioritized by Rachael, based on our recommendation that further development into this was not worth the effort at the current time.

**Comment by pjhill** [comment]
OBE
