### ISSUE TITLE
Access for Erika Washburn

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-team#30777]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Erika Washburn

### Your Email

erika@cityfriends.tech

### Name of Your Team

PTEMS VA.gov Modernization, Content Strategist, Friends From The City

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDI4X3ffkl1i5o/zl2YHwDVYbKkB6RSXuCr1E7gH38nN9LKUkmjA4celz1Y7JFAbnMmq4PglkdcvZxtM6/bbRNh75ObbdrwO4/h+dIlrZNqAph4A26lVGxkBmW7cADulqQpAXl0CH4FgTNR+q46qIU5kuCDDcgSLLZF+9489ai28PFa1tml9TpgELOeo+yn3kuQmQW9vYHnDcOWgFYC18uwM+QVI0f6PMpW9q+bi/fPO618eonCSQdivPnHEDlt6mlkMHFABLvsbQhOHzo34nn2ohEeSMbqmI6/sVUMFnLB2Lrs6XRqhrbvVAPr3IOAFdZcaHMu6LRwLExD/Y8EF4UjltO8jer8JwexobK2pM3nh2e2dtTU4+zFwSQN5ZlQt4yxCZtq8Q65TtmErPWjgFB4/6fL3CpiiggC2mBZLnlWx9oGjJtShkKTKPm0tCAgoJ2m8n38egjoqxeO6KYlU7wT/azQGqV6EB/nhfAvXagFQtxhCr2olNDacp+CKJbciAE= erika@cityfriends.tech

**Comment by rwilliams-oddball** [comment]
Completed by automation.

**Comment by EWashb** [comment]
@rwilliams-oddball if I am having issues with my access, do I ask questions here or should I reach out to my platform support channels?

**Comment by EWashb** [comment]
My apologies. I deleted the previous key and need to have it re-deployed. I spoke with Elijah Lynn and he helped me to get my key set up.  The following is correct
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOGcMexP0dwvLAvjPAnBRP2zs/YFygD+mgo1m+TA2kASacvRl5j26EEz8Pwkk0EcB8bYVewdE+s32sR2ZgdYOmNT4t2SUIt1BXGQ4GUHIG5cDosf1GJuVvXhqJmDBdkitB0Op9qP+Wi4QYKE42i9HrE+G3nQTo3rzTCdz1TAmi/n87YfArJQqeApm4HnM7WhqP9b1njWaL1Te45mjZxi8we4T1TJi4C/dZHKvD97zshe72V8uWgMo6fFFs4Z9pAT+1NwLY0gzN/HezViEH1GM9/Op4AewyjMWHRSbvgupeRoy1YmMKuQsNOQtU3DKAsUTGAj+OFVUreY479KawfXLSoCnenBDKokr9nTUo1hCqeox7zc+tdgeBMh6ZENuL7QJvVIzdXKV9wRYTeBgcEmFWBdn57f/mV39xgGxDuBGWtZrnxD0Xrjj0AS2l5UpsKssMIIC7oo3abAMx7iAbizI/E094VHGy3jcQzV56BRZFLL9/FK+6aWgcSfPbj1Gl/xs= erika@cityfriends.tech
```

**Comment by mydesignrocks** [comment]
Hello @EWashb replaced with the new key provided. Please verify.

**Comment by EWashb** [comment]
> Hello @EWashb replaced with the new key provided. Please verify.

Hello! It works. Thank you very much.

**Comment by mydesignrocks** [comment]
sure, closing this now.
