### ISSUE TITLE
Complete 2 Housing pages w/legal feedback

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3077]
There are 2 pages that are open for legal review and will create a new ticket to track just those 2 pages. Peggy has already been coordinating this with SMEs. 

These 2 pages are blocking Housing hub going fully live via Drupal. 

-Eligibility requirements for VA home loan
-VA help to avoid mortgage foreclosure

SMEs: Sniegon, Paul, VBAVACO <paul.sniegon@va.gov>; Drumm, Elysium, VBAVACO <elysium.drumm@va.gov>

**Comment by peggygannon** [comment]
Document with the legal feedback and edits: 

[https://app.zenhub.com/files/133843125/d072c6f5-51ab-42f5-9641-ee222bed34e3/download](https://app.zenhub.com/files/133843125/d072c6f5-51ab-42f5-9641-ee222bed34e3/download)

**Comment by peggygannon** [comment]
@jenniferlee-dsva @RLHecht I've input legal review feedback into the following two housing pages: 

prod.cms.va.gov/housing-assistance/home-loans/eligibility/
prod.cms.va.gov/housing-assistance/home-loans/trouble-making-payments/

@RLHecht 
Can you check/proof my inputs? If all looks good, we can then send these pages back to the SME for final signoff.

Document with the legal feedback and edits is here:
https://app.zenhub.com/files/133843125/d072c6f5-51ab-42f5-9641-ee222bed34e3/download

**Comment by RLHecht** [comment]
@peggygannon I copyedited both these pages. on the Eligibility page "apply" in the green button "Go to eBenefits to Apply" needs to be lowercased. I think this is something Nick has done for me in the past and you could send to the SMEs without if it can't be done right away. Also the text in the Word doc for the tables doesn't exactly match what is on the preview page (there is more detail there) but I am assuming you reworked it with their edits. 

On the Trouble Making Payments page I lowercased loan technician throughout per our style guide.

**Comment by peggygannon** [comment]
thanks, @RLHecht for giving these pages a proof!

**Comment by peggygannon** [comment]
**11/7/19 update** Preview links and screenshots of the 2 updated  housing pages sent to SMEs for final review and approval

[https://app.zenhub.com/files/133843125/84476549-16a1-492e-9455-361b77b31438/download](https://app.zenhub.com/files/133843125/84476549-16a1-492e-9455-361b77b31438/download)

**Comment by Karak888** [comment]
@peggy to follow up again this week, pending final feedback.

**Comment by peggygannon** [comment]
**11/20/19 update** Followup email sent to VA stakeholders, requesting final approval by Friday 11/22. We want to publish this hub by Monday 11/25.

**Comment by jenniferlee-dsva** [comment]
These 2 housing pages are now complete, and the entire housing assistance hub is now live via Drupal -- as of 11/25. 
@mnorthuis - please add these two pages for vetting for redirects.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva all housing redirects are documented in issues #2170 and #2214.  If all the parity and rewriting work is done I can release those tickets or break them down if some are ready to go, but just need to know which pages exactly are ready. The parity and rewriting tickets (linked in the redirect issues) don't show the work as done.

**Comment by Karak888** [comment]
these pages are complete and done and can be redirected.

**Comment by Karak888** [comment]
@Karak888 to fill out redirect request for Mikki.  Closing this issue but will refer to it for URLs to be redirected.
