### ISSUE TITLE
Testing Tools Team Dashboard Data repo: clean up old tests, write new tests, run tests in CI

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#30789]
All the old tests fail when run because the app changed significantly since the tests were written.

Clean up old tests and fixtures, write new tests, run tests on push in GHA CI.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/75

**Comment by pjhill** [comment]
Heck yes, this is awesome!
