### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#30786]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the `department-of-veterans-affairs/vets.gov-write` org. Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: timwright12
- Reason access is required: pagerDuty alerts requesting that the queue be cleared

**Comment by jeff2d2** [comment]
Added on 10/1/21
