### ISSUE TITLE
IA request from DGIB team for secure inbox/messaging

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#30790]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [X] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
*Use this space to describe your content need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

- Location for the app within va.gov. We think somewhere global, similar to profile, would make sense. Potentially under a contact us / support / help section, but that doesn't really exist today. 
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/secure-inbox/Product%20Outline.md
- Link to or attach user flows:
- Link to prototype or mockups: https://github.com/department-of-veterans-affairs/va.gov-team/issues/29842#issuecomment-922013798
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD, but likely in 2022
- Estimated staging review date: TBD
- Content and IA work needed by: 10/31

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Shamik Desai
-	Designer: Leelah Holmes, Russell Lyons
-	FE engineer: Cesar Santiago
-	Product/team Slack channel: https://app.slack.com/client/T03FECE8V/C02825JJJRW

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Hi @rlyons89!

For the purposes of your upcoming user research, here are my suggestions for representing IA in the prototype while we finalize the specifics. Hopefully this is enough info to get you through testing. 
- Remove reference to "My VA" from the breadcrumb.  I think we will need to work on the H1s a bit, but based on what you have, the breadcrumb paths would then look something like this:
  - Home > My inbox
  - Home > My inbox > Create a new message
  - Home > My inbox >  Inbox  
  - Home > My inbox >  All documents
- I'm not sure how you plan to handle the CTA below the side nav in mobile. This is not a typical placement for a CTA for our site.  For mobile, our side nav is collapsed in a section menu.  
- Question: right now you have a number after the group headings (Messages and Documents), is that intended to represent unread, new or both?  Or is that something you are still trying to determine? We don't typically show dynamic content in the left nav or breadcrumb, so this is something we will want to work with accessibility on as well. 
- I would strongly recommend you ask participants where they would expect to find a feature like this on VA.gov prior to them seeing the My VA page, so we can determine where our primary entry points will be.

**Comment by rlyons89** [comment]
Thanks @mnorthuis! We started on some design updates that went in this direction, the new mockups are here: https://share.goabstract.com/7cd80de9-ef96-4214-80c8-af79fad198d5. Are you okay with us using 'Secure messaging' instead of 'My inbox' in the breadcrumb? We are fine either way, but it seemed strange to have the parent item 'my inbox' with a label so similar to one of the children 'inbox'.

- We have moved the CTA from the side nav section
- We have removed the counts in the nav and breadcrumb components
- We will definitely include a task in our testing to investigate where users would expect to find the feature

**Comment by mnorthuis** [comment]
@rlyons89 Yeah, that's why I wanted to at some point work with you and sitewide content on the naming and H1s of this.  We will also need to be careful how this coexists with the health care secure messaging, as we should not have 2 tools with the same name. 

In regards to the breadcrumb...
- Where does "Secure messaging" in the breadcrumb you have link the user?  If it links to the Inbox, then it isn't a valid step in the path for a hierarchical breadcrumb.  
- For the message detail page, I would recommend that your H1 is the title of the message, and that is what will appear in the breadcrumb.  Breadcrumb segments must match the H1s of the page. 
- Your breadcrumb would be more like this:
  - Home > Inbox
  - Home > Inbox  >  Questions about our GI Bill application
  - Home > Sent 
  - Home > New message
- For Profile, there wasn't really a landing page, they were all equal level pages similar to this.  So, we added "Profile:" in front of each top level page name.  You could do the same here by adding "Securing messaging:" to the front of the page names - e.g. "Secure messaging: Inbox".


There are still some things to work through with the breadcrumb, that really can't be finalized until we determine where this will be living and what the final product functions like.  Its possible that we may take a different approach for the breadcrumb for this particular feature depending on how the design works out and how helpful we deem a breadcrumb to be. The H1s, title tags, breadcrumb and left menu all need to work in sync.  For now, I would keep it simple and use the suggestions I gave above.

**Comment by mnorthuis** [comment]
Hi @rlyons89! Once your user research is synthesized and you have ideas on any refinements, let me know and we can loop back around and finalize IA. 

Also, for reference, we have made the decision to remove the breadcrumb from My VA and Profile because they are such flat experiences, and the only clickable link in them is the home page.  Depending on what your designs end up like, this is likely a possible direction for this tool as well.

**Comment by rlyons89** [comment]
@mnorthuis we should have our findings ready sometime end of this week or early next week

**Comment by mnorthuis** [comment]
@rlyons89 Can you provide an update on where you are at with this work so we can determine next steps for content and IA?  Thank you!

**Comment by rlyons89** [comment]
@mnorthuis sorry for not getting back to you sooner. We have a tentative plan for an Education focused Secure Inbox that we will work on in the short term as an MVP, with the plan for it to be flexible enough to evolve into a more global feature that other benefit lines such as health care can plug into down the road. For the MVP, through discussion with Samara and Kevin the direction that was recommended was to locate the MVP version of the feature within the Education & Training section and when other benefit lines are added in the future it can be relocated to a more global location in the navigation. We can share over MVP designs when they are completed and ready for content review/feedback.

**Comment by mnorthuis** [comment]
@rlyons89 @alexander-ferzola Checking in on this work.  I believe you had a midpoint review last week, so wondering if we can finish this work?  In looking at the prototype that was attached to the midpoint review, I have a few questions.    

Also, is there a ticket for working with Sitewide content?  I looked but wasn't able to find one, and their work influences final entry point links and URLs.

**Comment by bethpottsVADEPO** [comment]
@rlyons89 I'd like to give you some edits ahead of your next collab cycle review. Where are you in the process at this point? Has midpoint review happened?

You and I haven't had much contact yet, so I wanted to explain that the sitewide content team provides support throughout the development of new products in more of a fluid way, separate from the collab cycle checkpoints. You can engage with us and we can engage with you at any point that makes sense (to get help reworking stakeholder feedback for instance or to address issues raised in research). I saw that your request in this ticket didn't ask for content support (just IA/placement assistance), so I'm reaching out to let you know there are some screens in the mockup where you'll need to align with our style guide. 

@mnorthuis for awareness

**Comment by alexander-ferzola** [comment]
@mnorthuis @bethpottsVADEPO Thank you both for your replies. Please see Russell's response Jan 26th:

"@mnorthuis sorry for not getting back to you sooner. We have a tentative plan for an Education focused Secure Inbox that we will work on in the short term as an MVP, with the plan for it to be flexible enough to evolve into a more global feature that other benefit lines such as health care can plug into down the road. For the MVP, through discussion with Samara and Kevin the direction that was recommended was to locate the MVP version of the feature within the Education & Training section and when other benefit lines are added in the future it can be relocated to a more global location in the navigation. We can share over MVP designs when they are completed and ready for content review/feedback."

The "VA education inbox" of which we submitted a content review for Friday, (https://github.com/department-of-veterans-affairs/va.gov-team/issues/37492) is the MVP iteration Russell spoke about. We do not have any updates to the original mockup/prototypes you are referencing. Please let us know if you have any questions!

**Comment by mnorthuis** [comment]
@alexander-ferzola I have a couple IA specific questions to help me understand background/conversations to led to the updated prototype provided in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37492. 

1) Is their COE the only thing they can access in the inbox? If so, is there a reason to call this an inbox versus labeling it more specificly to what they can access, i.e. Download your COE?
2) Your prototype represents this new feature as the top item in the left nav under "Manage benefits".  The left nav is roughly in order of importance/frequency of use.  Viewing payments and checking benefit statements are pretty highly accessed tools, are you stating you feel this tool will be the most frequently used tool in Education?  I would also anticipate that "Verify enrollments" will move up in the menu with the roll-out of that new functionality.

**Comment by alexander-ferzola** [comment]
> 

Hi @mnorthuis , thank you for your questions. I'll do my best to answer:

1. For our MVP iteration, the decision letters will be what users are able to access from this feature. We opted on titling it to 'VA education inbox' because with future releases, we are hoping to upgrade functionality and expand capabilities to other edu notices/messages (e.g. confirmation of an enrollment). 

2. The link from the left nav under "Manage benefits" was a placeholder to display the entry point from there. The ordering is not set. Your feedback for this would be much appreciated!

3.  Decision letters are not able to be populated in the 'Download VA letters' section for the updated My Edu Benefits 1990 form. I know the backend developers have worked hard with the Va.gov coding team to troubleshoot that issue, but at the time, it does not seem feasible. As we would like users the opportunity to access their letters from VA.gov, the VA education inbox serves as an alternative place for accessing those letters.

**Comment by mnorthuis** [comment]
Thanks @alexander-ferzola!   

For the MVP, how long will this feature just be used to access and download notices and documents?  From an IA standpoint, the existing title/label for this feature doesn't match it's capabilities.  This will create issues for SEO, wayfinding and cognitive load.  

If this will not be an actual functioning "inbox" where they can receive messages from someone for quite awhile, then we could consider calling it something more appropriate to ensure Veterans understand what it is, what it can do, and how to find it.  We can then come back around and re-name it in the future when more true messaging features are added.   

cc @bethpottsVADEPO

**Comment by alexander-ferzola** [comment]
> 

Happy Monday! We're looking into the timelines for you. In the meantime, do you have any recommendations as alternative names for this feature? Would the switch in titling be confusing for a user, in the future?

**Comment by alexander-ferzola** [comment]
> I see at a bit differently than a name switch. If the focus of the current tool is to access specific documents, we will label it according to that task so users can find it more easily - that includes the page title, the nav labels and the URL. If a year from now, a messaging feature is added, we can approach it (from a user labeling perspective) as a new product/feature. It would have an appropriate title, nav label and URL to match the new functionality. We can then redirect all the content/URLs of the old feature to the new one, or retain some content to help in the transition and direct Veterans to the new feature.
> 
> Essentially we would put together a strategy for handling that change so it wouldn't be a hard switch.

Understood. Think our team is OK with updating title nomenclature, corresponding nav labels, and URLs. Do you have any recommended language? Think we'd want to avoid any confusing language with the existing "Download VA Letters" section.

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola I agree with @mnorthuis about the H1 and am following your convo about that. I'll hold my content feedback until we know timelines for rolling out other education letters available for download since that will affect the focus and messaging across all the screens, but especially the tool landing page where the entry point/sign in is.

**Comment by alexander-ferzola** [comment]
@bethpottsVADEPO to clarify, did you have any content feedback on the screens that we submitted? Based on Mikki's feedback, we'll look to adjust the entry point copy, the H1 header, and URL.

**Comment by alexander-ferzola** [comment]
@mnorthuis  Linking the flow from our zoom call today: https://accenturefederal.invisionapp.com/freehand/VA-Edu-Inbox-User-Flow-fqQ0RWoGi?dsid_h=e5b492d65176309d085580b3f6ddc2d082df7e748ca09b5e4f36513d16196e3d&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01 should be the same as the screens you were reviewing but wanted to drop it here as well.

**Comment by mnorthuis** [comment]
Hi @alexander-ferzola!  Thank you for meeting with us yesterday to work through some questions.  Based on the discussion, here's the final IA for this phase of work on this product.   The IA includes, the URLs, breadcrumbs and primary entry points.   Please let me know if you have any questions. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-inbox-p1.md

**Comment by alexander-ferzola** [comment]
Following up on our conversation from earlier this week - thank you for providing IA feedback. Do you have a target date we can expect content feedback? One of our current stories is currently pending this review, and we'll need to replan and mitigate additional rework as appropriate

cc @bethpottsVADEPO  @mnorthuis

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola my content feedback is in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37492

Let me know if you have questions!
