### ISSUE TITLE
Update Insurance question and Insurance detail question copy and design (part 1) 

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#30792]
## User Story

As a Veteran, I need to clearly and accurately answer the questions about my Insurance, in order to complete my application for VA Health Care.

Currently, the research shows that this question causes confusion, and people are having to guess what information to input. This can result in inaccurate information being submitted.

## Acceptance Criteria
- [x] Split "Are you covered by health insurance?" and "Name of provider" into separate pages
- [x] Verify wording and validation on Insurance page as per design
- [x] Insurance page is displayed properly in review page
- [x] Verify Unit test passing
- [x] Verify end-to-end test passing

Design (ticket #30337) 
- Insurance question [design](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/agv5eAD)
- Insurance detail design ([closed accordion](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/v8qmr3Q) + [open accordion](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4aGLkPm)) 

Content is correct in the design, and I will update our content source of truth when we get closer to development to avoid confusion.

**Comment by Dene-human** [comment]
Updating ticket to keep feedback in one place.

As per slack:
- Review instances received on 11/1 (Monday) for Insurance general and Insurance detail
- Feedback given 11/1 (Monday)

**1. Other RIs were sent in the same batch**
- Feedback: Please confirm that _ONLY_ Insurance and insurance detail were touched. Medicare, medicare detail, medicaid, and VA facility that were sent in this batch of RIs **should not** be changed.

**2. General insurance question**
- Move the red “required” down after the question “Do you have health insurance coverage? (*Required)” 

**3. Insurance detail question**
- Can we adjust the spacing below the more info components? Note: Maybe this is ok, I just want to make sure it is the standard treatment.
- The “or” between Policy number and Group number is missing

**Comment by MickinSahni** [comment]
@charCodelet incorporating feedback

**Comment by MickinSahni** [comment]
@charCodelet syncing with Mark today about these changes and failing tests

**Comment by Dene-human** [comment]
Feedback for RI (received afternoon 11/15): http://a8c05ee0f61101537dc0457c5d7e1e19.review.vetsgov-internal/health-care/apply/application/insurance-information/general


**General insurance question**
- looks good now


**Insurance detail question**
- Update “or” between Policy number and Group number to H4 (same as step numbers)-_if easy_
- Check current prod for "add another" UX & ensure this is given the same treatment
- Error should be triggered if policy number **or** group number (both blank) isn't provided
     - turn "or" red on error- _If easy_

**Comment by Dene-human** [comment]
Feedback for RI (received afternoon 11/16):  http://a8c05ee0f61101537dc0457c5d7e1e19.review.vetsgov-internal/health-care/apply/application/insurance-information/general

1. Change Add another button to " Add another insurance policy" (Make sure only first letter is capitalized)

2. I am not getting consistent error treatment:
![Screen Shot 1.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/69c5244f-cf47-4226-bdf4-91db1b9f38b7)

![Screen Shot 2.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/4e9f53be-5a12-45eb-840f-d27468dfccfa)

![Screen Shot 3.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/8f50a4bb-f22e-4afc-b426-5aec4f673ff3)

3. I really don’t think we should have “required” text on both policy number and group number. This is my design suggestion:
![error.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/b3fe1f73-c414-4569-85a7-fe7b54155ace)

Talked to Patrick- seems like some of these are going to be a heavy lift due to global components - will need to discuss with other developers and then make a decision. 

CC: @MickinSahni @JSorensen55

**Comment by MickinSahni** [comment]
Patrick working with other engineers about latitude wrt global vs. local design

**Comment by Dene-human** [comment]
@lzapson Here is the PDF. 

[Insurance PDF](https://app.zenhub.com/files/133843125/4e45a9f0-2011-4881-b914-3338f4a3d90d/download)
