### ISSUE TITLE
Discovery: Workflow for medical form 2346 (Batteries)

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3079]
## User Story or Problem Statement
As a UX designer, I need to document the work flow for VA form 2346 (batteries) so I can pinpoint how the user orders batteries from each channel (VAH, Healthcare provider, eBenefits, automated and live agent phone calls, mail, and email ) and discover gaps in the flow.

## Goal
_We would like to document the workflow and confirm it with stakeholders to influence the new ordering feature's design._

## Objectives or Key Results this is meant to further
- Communicate to both BAM2 and DSVA teams about current landscape of problem space.
- Determine the following:
  - What does the Vet do, per channel.
  - What does the DLC do, per channel.

## Acceptance Criteria
- [x] Create workflows in a program that the VA stakeholder(s) can access
- [x] Present/Confirm workflows to VA stakeholder(s)
- [x] If necessary, make adjustments to workflows

## Next Steps
- Find new areas for investigation in the various workflows

## Blockers
- Pending meeting coordination with DLC

**Comment by rebeccawalsh** [comment]
![batteries-workflow.jpg](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/5cc43b53-cf04-4fa8-a292-77e828a5bd97)

Find it on GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/workflows.md
