### ISSUE TITLE
Split current compensation question into two questions and update design and copy

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#30794]
## User Story

As a Veteran, I need to clearly and accurately answer questions about the compensation that I currently receive from the VA.

Research shows that applicants are confused when answering the Current compensation question. Many believe that they receive both compensation related to a disability and VA pension-which is not possible. 

We need to split this question into two questions.

## Expected Behavior

- Service-connected disability pay will have it's own page within the same chapter
- VA Pension will have it's own page within the same chapter
- VA Pension will be dependent on a "no" answer from the Service-connected disability pay question. (this question will only be shown IF applicant answers "no" on the service-connected disability pay question)

## Acceptance Criteria

- [x] Service-connected pay is successfully split into a separate page in the same chapter
- [x] Service-connected pay copy and design is updated
- [x] VA Pension is successfully split into a separate page in the same chapter
- [x] VA Pension copy and design is updated
- [x] VA Pension is dependent (only shown) IF applicant answers "no" to  VA disability pay question
- [x] **Designer signs-off via Review Instance in SOCKS before it goes to staging/prod**
- [x] The data for the form submission remains consistent with original design
- [x] Form data is successfully sent to the backend (and to the Enrollment System)

Design & content (ticket #30335)
Disability pay- [Design PDF](https://app.zenhub.com/files/133843125/0f2f92e2-730e-4845-b174-0c6c0c7c13c5/download)
VA Pension- [Design PDF](https://app.zenhub.com/files/133843125/dad080ac-0bec-4432-b735-3b9d3bdd0e2f/download) 

- VA disability compensation 
- VA pension question is dependent on the VA disability pay question and will only be shown IF "no" is the response on the VA disability pay question.

The content is correct in the design.

**Comment by MickinSahni** [comment]
In staging

**Comment by MickinSahni** [comment]
@jchilders to verify backend is functioning correctly

**Comment by MickinSahni** [comment]
@LinnJS provided some context re: the last Acceptance Criteria—wanted to make sure we're not using mock data and/or stubbing endpoints.

**Comment by MickinSahni** [comment]
Verified and closing out
