### ISSUE TITLE
Page & Word Counts for VA.gov | Resources + Support Pages

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#30801]
## User Story

As a product manager, I would like to have a count of the # of pages in the Resources and Support section of VA.gov and the associated word count for each page, so that I can estimate our translation  budget and secure adequate funding.

https://www.va.gov/resources/

## Acceptance Criteria

- [x] Number of pages within Resources + Support
- [x] Number of words for each page within ^

**Comment by adamwhitlock1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/Page-and-Word-Counts-for-Benefit-Hubs.md

I have added the stats for the resource pages in the main table, as well as breaking down all of the categories into their own table of urls and word counts.
