### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#30800]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the `department-of-veterans-affairs/vets.gov-write` org. Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: k80bowman
- Reason access is required: Member of the FE Tools team.

**Comment by jeff2d2** [comment]
Added on 10/1/21
