### ISSUE TITLE
[DESIGN] Finalize visual/layout of check-in poster 

### ISSUE THREAD

**Issue by niradatta1** [department-of-veterans-affairs/va.gov-team#30811]
The poster is the first touchpoint in the check-in experience. Based upon research findings, and [Phase 2 Usability study,](https://app.mural.co/t/vsa8243/mural-password/vsa8243/1629923298341/3f6e350a2b322a4c77a92b30ae0dac25e42439d5) we need to make it clearer that the veteran needs to wait for a text after texting 'check-in'. In addition, it can offer clearer guidance on how to send a text.

The content design has been finalized [(link to wireframe).](https://whimsical.com/check-in-poster-content-design-concept-s-UWsas6z574Ca8MsjT6ZSep) Using this content, we need to create a final visual design of the poster to prepare for upcoming usability testing:  

- [ ] Explore new visuals to coincide with the[ new content design ,](https://whimsical.com/check-in-poster-content-design-concept-s-UWsas6z574Ca8MsjT6ZSep) 
- [ ] Create final version in Illustrator for the following size posters: 8.5X11, 11x17, 24x36

### Acceptance Criteria

- [ ] Post to [GitHUb.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral) Don't override the original version as we'll need to include both versions for usability testing.

**Comment by kristenmcconnell** [comment]
The original Illustrator file is available on GitHub, which is linked in the story.

**Comment by sarahknoppA6** [comment]
Team agreed to change the scope of the ticket so that this only encompasses the 24x36 draft of the poster. Corey to create a new ticket with finalizing the remaining sizes and completing the poster optimization. This ticket can be marked complete after that.

**Comment by jparker0425** [comment]
@zach-park @niradatta1 @kristenmcconnell this item is completed, correct? It was the poster that was created and taken to Martinsburg.

**Comment by jparker0425** [comment]
Thanks @zach-park . Closing and will create additional item for revisions.
