### ISSUE TITLE
Access for Christopher Bratti

### ISSUE THREAD

**Issue by ChrisBratti-VA** [department-of-veterans-affairs/va.gov-team#30819]
### COR Name

Other

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Christopher Bratti

### Your Email

christopher.bratti@libertyits.com

### Name of Your Team

Axolotl

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOE5ShKoNDWbfF1ge58+ed7OgJuI59xA9/HIb2ESPD0q christopher.bratti@liberyits.com

### Desired AWS Services

I need access to Kibana for CCE API metrics

**Comment by rwilliams-oddball** [comment]
Completed by automation.
