### ISSUE TITLE
[FE] Notification Prefs: Launch Notification Prefs to all users

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30810]
## Background
Following successful completion of #30809  we'll continue with the phased launch of the Notification Preferences feature, moving to all users.

## Task
- [x] Turn notification preferences feature on for all users
- [x] Monitor analytics post-launch

**Comment by erikphansen** [comment]
1. Sign into va.gov with your LOA3/2FA ID.me account
2. Go to https://api.va.gov/flipper/features/profile_notification_settings
3. Update the "percentage of logged in users" value

<img width="868" alt="Screen Shot 2021-10-29 at 12 32 11 PM" src="https://user-images.githubusercontent.com/20728956/139492754-e18c11e0-9bbe-4d19-b26e-4f1c55cabde4.png">

**Comment by Samara-Strauss** [comment]
This was actually done today! Closing!
