### ISSUE TITLE
Offboarding of Gabby Molinolo

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#30822]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Gabby Molinolo
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Caseflow, DSVA, Product, 9/30, Tista
- Please provide any type of access they may have and their GitHub username. 
  > Slack and Github Username: (GabbyTISTA)
  
 
## AC
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
   > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
   > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @mchelen-gov

**Comment by jennaouellet** [comment]
GA and Domo not applicable

**Comment by rwilliams-oddball** [comment]
No VFS
Access to Socks does not exist for the following emails "gmolinolo@tistatech.com"
and "gabriela.molinolo@va.gov".

**Comment by mchelen-gov** [comment]
@KCollinsBrown ty for reporting this! the Slack user has now been deactivated. i have created a followup ticket to improve Github action: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31187

**Comment by jbritt1** [comment]
A couple of notes here @mchelen-gov, @KCollinsBrown, @rwilliams-oddball:

The action not running when @KCollinsBrown did the `/request` command is by design as it will only work, by default, for users who have `write` permissions against this repo which @KCollinsBrown nor any of the 5 teams she is part of gives [doc](https://github.com/xt0rted/slash-command-action).

We on Operations should be the one inputting the comment to trigger this action.
