### ISSUE TITLE
Fix broken PDF link on Pay your VA copay bill page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#3084]
## Problem statement

There is a broken link to a PDF on the Pay your VA copay bill page.
URL: https://www.va.gov/health-care/pay-copay-bill/

![2019-11-04_10-02-11.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d2ea87c7-38bc-4e57-9e42-25e164a9e41a)
## Goal
Fix broken link. 

Link to put in: https://www.va.gov/HEALTHBENEFITS/resources/publications/IB10-691-understanding_your_VA_patient_statement.pdf

## Acceptance Criteria
- [x] _New link added to Drupal page

**Comment by RLHecht** [comment]
@peggygannon This PDF link was updated in Drupal. Can you please set the page to publish for today's deploy if possible:

Drupal info: preview-prod.vfs.va.gov/preview?nodeId=704 Pay your VA copay bill

@jenniferlee-dsva and @Karak888 for awareness.

**Comment by peggygannon** [comment]
@RLHecht this has been reviewed and published.

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket. FYI @Karak888
