### ISSUE TITLE
Removal of ID.me Certificate

### ISSUE THREAD

**Issue by codyreinold-usds** [department-of-veterans-affairs/va.gov-team#30848]
The VA.gov <> ID.me certificate is expiring. ID.me reached out to confirm if we needed to renew this certificate, or if we could deprecate, as all ID.me sign ins are now routing through ISAM.

**Comment by codyreinold-usds** [comment]
@joeniquette indicated that @bosawt was working on this. Transitioning to Trevor for resolution. Let me know when this is resolved so I can get back to ID.me; preferably in the near future.

**Comment by nsoutouras** [comment]
Believe this is a duplcate of #29421

**Comment by bosawt** [comment]
@codyreinold-usds It's safe to deprecate the cert now, the PR that removes references in the code has already been merged. It's still technically set during deploys but that PR is up now and just waiting for review (should be merged by EOD): https://github.com/department-of-veterans-affairs/devops/pull/10052
