### ISSUE TITLE
Notifications  from <Authenticated Experience>

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#30866]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
*The Auth Exp team is adding a new feature that will live on My VA as well as have a page of its own. This feature aims to elevate action items for Veterans. This could be anything from a very time sensitive appt reminder to a simple Covid-19 update.  We also would like to make sure to sync with the mobile team, as they will be launching a push notifications feature in the future and our features will have quite a bit of overlap. 

We don't know what to call this feature, and we'd love your help! In the prototype we called it 'Alerts' and this tested really well with Veterans. Users also mentioned wanting this to be called 'Notifications'.  

The Auth Exp team and the Mobile App team joined office hours last week and briefly discussed this, but we decided it would be better in a ticket with further discussion.  *

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications
- Link to prototype or mockups: https://preview.uxpin.com/aeb04fa2c4989723cf9b60e6d47e311ae3a4cd78#/pages/140666348/simulate/no-panels

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD
- Estimated staging review date: TBD
- Content and IA work needed by: ASAP

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Authenticated Experience + Mobile App
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Ana Jakabcin
-	Designer: Tressa Furner
-	FE engineer: Erik Hansen and Taylor Mitchell 
-	Product/team Slack channel: #vsa-authd-exp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by ajakabcin** [comment]
meeting scheduled for 10/7 at 2pm et to discuss
