### ISSUE TITLE
[Content] Calendar - no slots near future alert

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#30869]
## Request
Request review and recommendation for the alert on the direct schedule calendar page.
- If no slots in the next 2 months
- If no slots in the next 4 months

## Background
When a user inputs today's date in the preferred date, an "urgent care" alert appears above the calendar. The app queries for 2 months worth of slots. If there's a slot the alert copy is populated with the earliest available date. If there are no open slots, then the copy currently shows today's date (bug/no handling #30480)

## Screenshot

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/e1613a03-342f-4a64-b27e-8c4d48027ca4)

**Comment by peggygannon** [comment]
Hi, @laurenernest Can you tell me if this works? 

**We couldn't find an appointment for your selected date**

 To schedule this appointment, you can:  
- Call your VA medical center, **or**
- Submit a request for another date

**Comment by laurenernest** [comment]
That should work. I'll let you know if anything comes back from grooming.

**Comment by laurenernest** [comment]
no additional work needed. closing ticket.
