### ISSUE TITLE
[FE - Mobile header] Create header V2 react widget

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30875]
## Issue Description
_Since the launch of VA.gov in late 2018, the site has featured one responsive Global header element that was not optimized for Mobile view. As a result, for our growing base of Mobile users._

[Sketch Files](https://www.sketch.com/s/63193c20-04fc-4d4f-8b54-abf698c48636/a/Vr8Zzrw)

_The proposed solution: A mobile-only optimized header that streamlines the size of the header by utilizing the "hamburger menu." More details in this [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)._

## Front end tasks
- Create header v2 (show_header_v2) react widget 
- Ensure this change is for MOBILE ONLY 
- Ensure this change is on STAGING ONLY
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
Current progress:

https://user-images.githubusercontent.com/12773166/140537018-8cb872f0-9d37-4ac8-babe-39655984a003.mov

1. ✅ Official government banner 
1. ✅ VCL banner
1. ✅ Logo row
1. ✅ Sign in button
1. ✅ Menu button
1. ✅ Menu
1. ✅ Search
1. ✅ Menu items level 1, 2, and 3
1. ✅ Back to menu button
1. ✅ Unit tests for everything

Pending items:
1. I haven't tried testing it when logged in, but functionality should work as in the design spec (albeit maybe some styling issues)
1. I haven't written an e2e test for it yet
1. Accessibility feedback on implementation (I imagine this will happen when the work is on staging to test it)

**Comment by kelsonic** [comment]
PR merged! Will go out with daily deploy Monday (behind feature flag)

**Comment by brianalloyd** [comment]
@joshkimux also wanted to loop you into this as well, if you have some white space to review and provide any a11y feedback on the new mobile header that would be great.

**Comment by joshkimux** [comment]
https://user-images.githubusercontent.com/14154792/140815469-e6e83e57-f228-475e-a85b-7c9e0dc3b5f2.mov

I can't seem to activate the talk to the Veterans Crisis Line modal both in devtools and on my iphone

**Comment by kelsonic** [comment]
Yupp same here, I'm actively working on a solution for it, sorry @joshkimux!

**Comment by joshkimux** [comment]
Quick a11y feedback (I'll update this as I move along). Feel free to check these off as you fix them!:
- [ ] Menu button should indicate if it is collapsed or expanded (using `aria-expanded`)
- [ ] Buttons should respond to the `space` key to collapse/expand
- [ ] Focus should be managed within the menu (e.g. activating "Health Care" should send focus to < Back to menu and vice versa)

**Comment by rtwell** [comment]
Health care is always spelled with a lowercase `c` Health care not Health Care — I noticed it on the expanded menu, first item. 

![image](https://user-images.githubusercontent.com/12564977/140965147-74f6dc79-d034-4a2d-8ff9-e12d9ca47953.png)

**Comment by rtwell** [comment]
it also looks like the `+` on the expanded menu items are also not quite vertically centered.

**Comment by kelsonic** [comment]
Thank you both for the feedback! We will implement the changes asap 🙂 

> Health care is always spelled with a lowercase c Health care not Health Care — I noticed it on the expanded menu, first item.

This one will need to be updated in the CMS as that's where the megamenu data comes from ^ CC @RLHecht

**Comment by RLHecht** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA Is it purposeful that the megamenu uses title casing instead of sentence casing for **VA Benefits and Health Care**. Also for **Find a VA Location**. Should this be changed or kept as is?
<img width="580" alt="Screen Shot 2021-11-09 at 11 59 24 AM" src="https://user-images.githubusercontent.com/48728214/140969800-da5f368c-78f9-4b95-ad97-e05dd22bad9e.png">

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks for raising that. We shouldn't be using title case capitalization. Sentence case is our style across the board. I have no idea why it isn't that way now in this one spot! Probably some hold-over from before we switched to AP style. Are you able to make this update yourself? We may need @kelsonic to update the injected header.

VA benefits and health care
Find a VA location

cc for awareness: @rtwell @KevinMHoffmanUSDS @DanielleThierryUSDSVA @mnorthuis

**Comment by kelsonic** [comment]
oh wow you're right it is frontend, I can update that 🙂

**Comment by brianalloyd** [comment]
@kelsonic I created the below tickets in support.  I placed the immediate "Sentence Case Style" issue in sprint for action.  The second ticket "Migrating megamenu items to Drupal" is in our backlog for future grooming.  
1. #32680 
2. #32681

**Comment by kelsonic** [comment]
PR is up for @joshkimux and @rtwell's edits: https://github.com/department-of-veterans-affairs/vets-website/pull/19357

**Comment by brianalloyd** [comment]
@kelsonic closing ticket based on completion of work, if more updates are need we'll manage those in separate/individual tickets.
