### ISSUE TITLE
Remove sentence on alert box used in disability wizard

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3087]
On this page: https://www.va.gov/disability/how-to-file-claim/

In the supplemental claim alert (after answering questions in the 'can I file online' wizard:
![image](https://user-images.githubusercontent.com/43381063/68137398-e9d47100-fef4-11e9-80b8-b52e78a57e48.png)

Remove the sentence:  saying “You shouldn’t file a disability claim.”

Fred Somers, SME, says supplemental claims are a type of disability claim.

**Comment by Karak888** [comment]
hi @Mottie! this looks validated to me, but please let me know if we can close this out for this sprint.  Thanks!

**Comment by Mottie** [comment]
I think it can be closed. I just checked va.gov and the sentence is still there, but it is gone on staging.va.gov.

**Comment by Karak888** [comment]
closing per comment above.
