### ISSUE TITLE
Access for Gibran Rodriguez (@brangi)

### ISSUE THREAD

**Issue by brangi** [department-of-veterans-affairs/va.gov-team#3088]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.

**Mary O'Toole**

- Please provide your name.

**Gibran Rodriguez Luna**

- Please provide the name of your team, your role on that team, and the name of the company you work for.

**`vsa-public-websites`, Senior Backend Engineer, GovernmentCIO**

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCTb0vZSkoQQl2nvsfjulZi0hD1465Khata7Pq+p2t4TjPdxJyjAOwhlU8BtvU1ITH3BWH4HL6mtCDxIiis8+UxeJt9SnhLqDF6D+FEzpePuoO+I1PhaXMUSb7K8xmfspuhb2kTPuZXsm7m1OIbeJCaYZEebjM7UM7VEbFCTmvZ60CSPmRHpa4gQuuSnRQqvAIkEu5fds8ohnR0ABEFywGBXiA0DYCD89jnWCxq+HyCw3P/ND6kFwIil8btOYlZC8YqSX7jIVWJV+1DjHNC8RW6ERyywwYf6rzjkvIPIDViJuzmm5AdT/+tMQXRb4m1VQ0hFxt6y+oddPrNrEPFuJ/ gribranrodriguez@USRMonitorsMBP2.attlocal.net
```

- [Grant AWS Console access?]

**YES**

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Gibran Rodriguez Luna

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS access.

**Comment by brangi** [comment]
My pub has changed 

```ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNhT+mbgmwLReRWb1BLakhAVw0JJFZpkUMkBfylcQ5f gcio```

**Comment by jbritt1** [comment]
Has Gibran's E-QIP been submitted? Four months seems a bit longer than normal for this process. Any info is appreciated.

**Comment by Jeff-Hayter** [comment]
@jbritt1 I don't have any updates on my end.  I have not seen a transmittal or COI.

**Comment by jbritt1** [comment]
Roger, thank you for the update @Jeff-Hayter !

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by tskinn** [comment]
@brangi has told me he doesn't need AWS access at this time.
