### ISSUE TITLE
Replace ProgressButton with version from component-library

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#30908]
### User story(ies)

As an engineer, I want to not have to maintain two duplicate versions of the same component, so that consumers of the component will always be using the same component with the same features/enhancements.

### Additional details/notes/links

- Making enhancements to button in `component-library`:
https://github.com/department-of-veterans-affairs/component-library/pull/193#pullrequestreview-770539193
- File to be removed: https://github.com/department-of-veterans-affairs/vets-website/blob/958eb42c1c5220004685600fbb686e81950b24ba/src/platform/forms-system/src/js/components/ProgressButton.jsx#L9

### Acceptance criteria

- [ ] Single version of `ProgressButton` across `vets-website`

### What type of issue is this? 
- [ ] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [x] Other (please describe)

Dealing with tech debt

**Comment by bkjohnson** [comment]
Now that we have [`<va-button-pair>`](https://design.va.gov/components/button/button-pair) we should aim to use that web component as the Back/Continue variant instead of using the React `<ProgressButton>`.

**Comment by humancompanion-usds** [comment]
@caw310 and @micahchiang - I'm betting we can close this. Can you confirm (and close)? Thanks.
