### ISSUE TITLE
Access for Jessica Alexander

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-team#30914]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Jessica Alexander

### Your Email

jess.alexander@agile6.com

### Name of Your Team

VFS-CMS, Product Manager, Agile Six

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD37080FlhRL07W2fYV8nb+B3YEgAGQYeasP9iGLMs0yDTzHBEHdcoB5i2IiaSqHiftEaNP3lOYfPREYkHjZ3fUYC61mhB4KcifMwCG9CyO+0ytgoDNDfmiI0hrAD7pux04GHMBMmKY1oTRe+5u4Ao4ZU9ZMl6KCBNz44Ty7TxyyZ7YriWhPMhGpyF+LUuyeOci4xfDZOf2rnji0iuqL2uxqsCzRnpdBd+ZM4GVweLwTnbxAeRfVWl895Y8FkRp7lVpiIBzUvWesRsIKueQKSJTL33I4A9gD00iezhl52rOgt8fMt64yqzGcyi0bVktXC8wDbc/UNfuqkGGszwWYRcbU/PV1wcPwuaiJG4yVJksTxNqYMoKGyePN0m9m1T5h+hUfbM/fih9Mdj6Gmx7JCx0Fbp9dUGZ4pXfPE5c4QwrcFRH/Yps1rMQJ76+TQVONzjhCwc8I19gsW6GKCNVar8mDteIu1IQm3trcJaunZDRt1yw/Yp2CBZ2U0JtWLI2FsU= jess.alexander@agile6.com

**Comment by mleclerc00** [comment]
Hi @jkalexander7 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
