### ISSUE TITLE
fixup terminology used in PagerDuty services for criticality/urgency

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3092]
## Background 
We sort of break down our alerts into Critical/Warning and High/Low Urgency between Prometheus and PagerDuty. The urgency piece is decided upon by which service you send to in PagerDuty currently. We should either implement rules that parse the tags created by Prometheus to just keep one service together, or update the wording on PagerDuty. Right now both are "Critical" and "NonCritical" but the criticality on the PagerDuty side really reflects urgency.

**Comment by ricetj** [comment]
People that are in the Pagerduty group and/or Prometheus to help define this.

**Comment by ricetj** [comment]
Need to make sure we are moving forward with these tools or not.
