### ISSUE TITLE
Update note on appointments tool page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#30941]
# Update note on appointments tool page

We need to update the note on the [appointments tool page](https://www.va.gov/health-care/schedule-view-va-appointments/) to remove reference to calling being faster. This is no longer true, and is creating a circular situation of Veterans calling > being sent to the online tool > reading that they should call > calling again.

Please update the note in this image:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/14b6e77a-8111-4f16-a911-c5e042a58a14)

Update the note to this content:

**Note:** If you can’t keep an existing appointment, please contact the facility as soon as you can to reschedule or cancel.
[Find your health facility’s phone number](https://www.va.gov/find-locations/?zoomLevel=4&page=1&facilityType=health)

**Comment by kelsonic** [comment]
On it 💯

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much for the quick action on this, @kelsonic and @brianalloyd! I appreciate it.

**Comment by kelsonic** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19020
