### ISSUE TITLE
Adding Giang Nguyen to DSVA Slack

### ISSUE THREAD

**Issue by aparcel-va** [department-of-veterans-affairs/va.gov-team#30949]
# Description

Please add giang.nguyen@libertyits.com as a full member.  Giang is a member of the Lighthouse team, supporting APIs such as the Facilities API. At a minimum, Giang would need access to the following channels:

- #cms-support
- #vaos-team
- #vcm-telehealth
- #vfs-platform-support
- #vsa-facilities

**Comment by LizCallaghan** [comment]
done!
