### ISSUE TITLE
Analytics Reporting Request for BAH Team

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3094]
# Metrics Reporting Request

## Description
Booz Allen Team - working with EDU Services

Amy Knox, Dan Shawkey & Darrell Neel (among others)

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._

- What team/project is this work for?
Work for Booz Allen SCO Migration.  
SCO Migration is a new page using VA.gov styles and GitHub as a backend.  We want to add Google Analytics to the page (filing a separate story for that) but need to know how GA can be implemented on GitHub content. 

Per Peggy Gannon, all tier 1 benefits hubs (except housing) and the home page are now in drupal.
Tools, applications and tier 2 content are still powered by Github.
    

## Timeframe for Analytics Requested
Need the SCO Migration analytics implemented in a 2-sprint window - before 11/22/19, preferably.

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@amyknox We can shift this over to close, as @jonwehausen and I see Google Analytics and Google Tag Manager firing on the staging page you provided in #3055. Any granular tracking requirements will be provided in that issue.
