### ISSUE TITLE
Organization of Community Care service types

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3095]
**As a user, I need to be able to search for a community care facility according to service type using my natural language so that I can find facilities near me.**

## Background:
- Searching for Community care facilities currently requires veterans to specify a service type using type ahead functionality. 
- PPMS (Provider Profile Management System) is the "source of truth" and originator system, currently  accessed via Vets.gov and (soon to be) Facilities API. 

## Tasks
- Determine what fields relevant to Community Care/PPMS is being surfaced via VetsAPI.
- Document the list of service types possible for Community care search and the hierarchy of the options with the goal of simplifying the structure. For example, search using the word 'cardio' and observe the list of options that are given. Given the current data structure, could it make sense to nestle all of the relevant locations under the general heading of 'cardiology' rather than all of the specific versions? 
- Is "category of care" available within PPMS/API and what is are the available choices within it?
- What are the performance implications of using category of care?

## Acceptance Criteria
- Documentation of service types currently available for community care searches and their hierarchy/organization 
- Recommendation for method of flattening/simplifying hierarchy

**Comment by davidconlon** [comment]
Need to confirm with business but I believe we are replacing "service" API field with the "category of care" API field.

**Comment by mmiddaugh** [comment]
This needs additional research to map to Veteran mental model of searching for community care (provider service).

**Comment by mmiddaugh** [comment]
@davidconlon I am moving this back to Backlog as it needs reprioritized and/or research
