### ISSUE TITLE
[TEST] Request development review for VSA / VSP test

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3097]
## Template adjustment suggestions

* I'd suggest re-wording the second Checkpoint Stage description. This feels more like a spot check or feature check than a before pre-launch.
* The third item could say "If your project is code stable in Staging, [request a pre-launch 508 review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md)

💯

**Comment by jenstrickland** [comment]
- [X]  Edits incorporated

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/request_dev_review_vsa.md
