### ISSUE TITLE
Update User Guide Development Workflow

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#30980]
Now that the team is growing, determine a workflow for making updates to user documentation. Some things to go consider:

- version control
- what is right review process for the team?
-

**Comment by lindsay-insco** [comment]
Once content guide is completed - build plan to maintain

**Comment by vlivshin** [comment]
@lindsay-insco, @jwowk and I settled on making edits in  onedrive. Have a couple of other details to sort out. Let's schedule a quick meeting to discuss and document and then this ticket can be closed out.

**Comment by vlivshin** [comment]
@jwowk, per our discussion, here's the workflow: https://dvagov.sharepoint.com/:w:/r/sites/vhavetext/_layouts/15/Doc.aspx?sourcedoc=%7B679C491A-74AC-4B8F-9EA4-D84189FD3472%7D&file=Documentation%20Workflow.docx&action=default&mobileredirect=true

**Comment by jwowk** [comment]
I have reviewed and approve of the workflow.
