### ISSUE TITLE
Production Readiness / Infrastructure Review

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3098]
## Story
As a product manager building VA Online Scheduling for VA.gov, I want to get the infrastructure of my product reviewed so that I know it's OK to launch on VA.gov.

## AC
- [x] New VAOS tool is reviewed and its infrastructure is accepted as OK by the VSP team

Note: I am opening this ticket due to the prod / infra review noted in the [product dev checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/Product%20Development%20Checklist.md), however, there aren't many details there. So I'm hoping we can get the VSP team to review the tool and sign off on our infrastructure & anything else that needs to happen in this review. Please reach out to @markgreenburg or @saneshark with any questions or documentation requests that would aid in such a review.

**Comment by 1Copenut** [comment]
@ricetj I wasn't 💯whom to assign to this ticket, so took the wide net approach. Let me know how the product support team can assist.

**Comment by ricetj** [comment]
Looks good for now, we had the first meeting. I would check back in with the Tools team to touch base, but for now, things seem good for the first part of the slow rollout.
