### ISSUE TITLE
Request QA Review for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3099]
## Story  
As an engineer, I want to request a review for Security and Load Testing with the QA Team to ensure that my feature meets the requirements for publication so that my pages will safely perform as expected under heavy loads typically found in the VA.gov environment.

## Task
- Select the Milestone sprint, or otherwise provide due-date for testing results.
- Provide the following info to support testing (via links if documented elsewhere):
  - Staging URL of product/feature:
    - Static page URL: **www.va.gov/disability/view-disability-rating/**
    - Report/dynamic page URL: **www.va.gov/disability/view-disability-rating/rating**
  - [UX Design wireframes/comps](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/)
  - Copy decks
    - None at this time
  - Test-accounts `(usual staging password)`
    - User: vets.gov.user+228@gmail.com (has 5 ratings, 3 are SC)
    - User: vets.gov.user+10@gmail.com (has no ratings)
    - User: vets.gov.user+123@gmail.com (has 1 rating, SC)
    - User: vets.gov.user+38@gmail.com (has 3 rating, 2 are SC)
    - User: vets.gov.user+45@gmail.com (has 1 rating, SC)
    - User: vets.gov.user+232@gmail.com (error)
  
## Acceptance Criteria
- [ ] Review has been scheduled or reviewed by [Tze-chiu Lei](https://dsva.slack.com/team/UHB9W74TA) ([tze@adhocteam.us](mailto:tze@adhocteam.us)) or [Peter Hill](https://dsva.slack.com/team/UL0FKGBDY) ([peter.hill@oddball.io](mailto:peter.hill@oddball.io))

**Comment by micahchiang** [comment]
This ticket is blocked until https://github.com/department-of-veterans-affairs/va.gov-team/issues/1889 is resolved.

**Comment by tlei123** [comment]
@jason-gcio , here's a question\* from my VSA-DevOps team-lead @jcosta-gcio:

“If they do a UI for that call can we test the UI do we have a software for load testing ?”

Pls. let me know.  Thx much!

\*I'm currently only able to perform manual UI testing.

**Comment by tlei123** [comment]
@jason-gcio , beyond the design comps provided, are there any clickable wireframes (like in InVision?) that clearly delineate the user stories/scenarios?

For starters, I was looking at the first two design comps, and couldn't figure out how the User navigates from the initial landing page to the following page.

Please let me know.  Thanks much!  :)

**Comment by jason-gcio** [comment]
@tlei123, we don't have the unauthenticated page in place yet as Public Websites is creating that.  Presumably, once Authenticated Experience determines the best home for where this page gets linked from we will know more about how this page gets accessed.  As you can see in the mockup, the initial landing page, if already logged in, would take the user directly to the tool page.  If not, they should be presented with a login and get redirected after authentication.

With respect to Joe's question, I am not sure what he is asking...should we have a quick call to discuss further?

**Comment by tlei123** [comment]
@jason-gcio, re. @jcosta-gcio’s load-testing question, I'm just trying to see if I can actually take on the security & load testing you mentioned in the Description...

I am not aware of any UI available to QA for validating security or load performance, but Joe wants to make sure.  These 2 types of testing are usually conducted without QA involvement.

That said, even if no UI exists for me to actually conduct testing, I would still like to see if I can validate/document the security-/load-test results.

Hope this clarifies the question for you.

Please let me know.  Thanks much!

**Comment by micahchiang** [comment]
Hey @tlei123 - We have #2951 which I am currently starting work on. I was just planning on following the steps you've laid out in [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/auth-session-loadtest.md), and the document it links through to. 

Is this ticket something different when it comes to load performance? I'm a little confused 😅

**Comment by tlei123** [comment]
@jason-gcio, per @micahchiang’s comment above re. that separate load-testing ticket #2951, do you think we can remove load-testing from this ticket here?

Not sure if the two tickets are talking about the same load-testing requirement, so I thought I would double-check with you.

Please let us know.  Thanks much!

**Comment by micahchiang** [comment]
@jason-gcio, @tlei123 - I think load testing can be removed from this ticket, as I have completed it in #2951. So, if that ticket takes care of load testing, I'm wondering what testing is left for this ticket. Is this purely a visual QA test of rated disabilities?

**Comment by tlei123** [comment]
@jason-gcio & @micahchiang, would you happen to know how to UI-test the **no-rating** and **API-/backend-error** messages on Staging?

Here are the message comps:
- [No rating](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/4255c799-245e-4df0-90bb-7cec66dfc218/RD-Screen-Tool-3)
- [Combined-rating error](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/5973de59-34ae-46ce-8aca-e41d8f73f3d6/RD-Screen-Tool-4)
- [Individual-ratings error](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/06fe86e9-9efe-44b3-89ea-2bac9f433e10/RD-Screen-Tool-5)

I am figuring the no-rating message is probably a test-account-specific scenario, so I just need the Staging no-rating test-account, but I do not know how to test the two error-messages on Staging.

Please let me know.  Thanks much!

**Comment by tlei123** [comment]
@jason-gcio , please confirm that for no-ratings scenario \[vets.gov.user+10@gmail.com] the dynamic ratings page should be blank \[see screenshot below].

I wasn't sure whether I should open a Bug for this:
<img width="1466" alt="rated-disabilities-no-ratings" src="https://user-images.githubusercontent.com/587583/70494382-55979400-1ac8-11ea-9ca2-42ed2044f117.png">

**Comment by tlei123** [comment]
Progress update:
- Test-cases have been finalized
- Mac Chrome test-run completed\* - opened bug #4082 

Will continue test-runs for other browsers tomorrow (Tuesday).

*NOTE: Another bug may be opened pending @jason-gcio ’s answer to my question in previous Comment.

**Comment by tlei123** [comment]
@jason-gcio , although I may ultimately attach a Testing Matrix spreadsheet w/ results once all test-runs are done, I’m sharing here a PDF preview of an interim Test-Case Report from the new TestRail test case management system (TCMS) that @peterhill-oddball & I are piloting right now...

Please check it out as time allows, and let me know what you think.  Thanks much!

[testrail-report-7.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3943130/testrail-report-7.pdf)

**Comment by tlei123** [comment]
##Update progress:
Although browser-/device-agnostic design/content changes are still upcoming, browser-/device-specific testing is well underway \[for already-testable aspects like dynamic data-display and links to other resources].
- Added a Content/Layout Test Run and moved the browser-/device-agnostic issue #4082 into that Run.  Now the browser-/device-specific Test Runs don't show Fails for this issue.
- Browser-/device-specific Test Runs completed so far \[they now all show Passed since I moved the browser-/device-agnostic #4082 out of them]:
    - Mac Chrome
    - Mac Firefox
    - Mac Safari
    - Win Chrome
    - Win Firefox
    - Win Edge
    - Win IE11
    - iPhone 11
    - iPad 6thGen
    - Galaxy S9
    - iPhone 6
    - iPad Air 2
    - Galaxy S8+
- Content/Layout Test Run is in-progress; completion pending final content-review #4104.  This is the Test Run now housing the Fail that generated #4082.

**Comment by jason-gcio** [comment]
> @jason-gcio , please confirm that for no-ratings scenario [[vets.gov.user+10@gmail.com](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=vets.gov.user+10@gmail.com)] the dynamic ratings page should be blank [see screenshot below].
> 
> I wasn't sure whether I should open a Bug for this:
> <img alt="rated-disabilities-no-ratings" width="1466" src="https://user-images.githubusercontent.com/587583/70494382-55979400-1ac8-11ea-9ca2-42ed2044f117.png">

@tlei123 
For user #10, that seems to be an isolated case...other users that have no rating render correctly and we think the data for #10 is bad or weird.  @micahchiang is looking deeper into it but it looks isolated at this time.

**Comment by micahchiang** [comment]
Hey @tlei123 - I did some more digging around, and with the help of another engineer, was able to determine the potential root of this issue. It seems like users who aren't in MVI don't get handled properly on our Rated Disabilities page, and that causes the page to break. 

@jason-gcio - I've created https://github.com/department-of-veterans-affairs/va.gov-team/issues/4222 to address the work of adding MVI error handling to rated disabilities.

**Comment by micahchiang** [comment]
@tlei123 - For example, if you log in with test user 10 and checkout the network call for `user`, you'll see that it comes back with errors relating to MVI. Logging in with user 17, the same network call comes back without any errors.

**Comment by jason-gcio** [comment]
Hey @tlei123!
I think we are ready to pick this back up.  Please let me know if you would like to chat further!

**Comment by tlei123** [comment]
Modified test cases after bugfix #4222 closed.  Started a new test-run -- planning to complete new run by end of tomorrow (Tuesday).

New defect(s) logged so far:
 * Copy: #4462.

**Comment by jason-gcio** [comment]
@tlei123 since those changes related to #4462 are already in place waiting for a PR, I am going to move this to Validate for now and we can close it once the PR comes in.

**Comment by tlei123** [comment]
All test-runs except Win IE11\* are now complete.

@jason-gcio , here a link to the Test Plan Summary report on our TestRail.com test case mgmt sytem (TCMS): https://dsvavsp.testrail.io/index.php?/reports/view/24
[VSA shared-account credentials emailed to you separately]

I'll walk though this report in our upcoming online chat/mtg.  There's a truckload of available reports available on TestRail, so I'd love to get your feedback.

\* Re. Win IE11, it just plain froze at the ID.me sign-in popup.  I'll be chatting w/ my VSA Engineering and DevOps Lead @jcosta-gcio about this, and I'll keep you posted on this front.

**Comment by jason-gcio** [comment]
@tlei123:
#4300 is all set so once it gets through its next build it should be ready for those last two checks to be run.  Keeping this in Icebox for now.
cc: @micahchiang

**Comment by tlei123** [comment]
Blocked/untested/failed Test-Runs now all Passed, after PR merged for bugfix #4300 ...

@jason-gcio , [Test Plan 2.1 Summary Report](https://dsvavsp.testrail.io/index.php?/reports/view/26) is now available on TestRail -- [PDF export](https://github.com/department-of-veterans-affairs/va.gov-team/files/4020475/rated-disabilities-test-plan-2.1-summary-report.pdf) is attached.

Feel free to Close this ticket.  :)

**Comment by jason-gcio** [comment]
Awesome, thanks @tlei123!
