### ISSUE TITLE
Site messaging: shutdowns, outages, etc

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#31]

**Comment by jenniferlee-dsva** [comment]
Existing info on emergency banner messages - gov't shutdowns, natural disasters, etc.

https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Banners

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Banners/VA.gov-homepage-banner-texts-preapproved-v5-020919.pdf

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Banners/homepage-emergency-banners-preapproved-020919.md

**Comment by rtwell** [comment]
covering this in #52 closing!
