### ISSUE TITLE
Request Pre-launch ATO review for VA Online Scheduling (VAOS)

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3100]
## What data are you collecting? For example, what data are you requesting from users?
In general, VAOS is an application that allows veterans to request & self-schedule healthcare appointments online. In support of this mission, VAOS asks for:
- Type of care requested (primary care, mental health, nutrition, etc.)
- Contact information (email, phone number)
- Availability (dates, times)
- Free text descriptions of medical conditions / reasons for wanting an appointment.
- Information about preferred medical providers
- Information about preferred locations & healthcare systems for treatments
- Information asking veterans to choose clinics from a list of clinics they've been to in the past

## What data are you using? For example, what data are you requesting from some VA service?
- Veteran's healthcare enrollment status
- Veteran's registration status within individual VA healthcare systems
- Veterans past and future appointment history for healthcare appointments, requested healthcare appointments, and canceled healthcare appointments
- List of past clinics that the veteran has been seen at within a healthcare facility
- Veteran's Community Care eligibility status
- Limits on the requests that the veteran has submitted & how long ago they were seen at a given facility

## Where does that data come from? For example, what API endpoint are you getting the data from?
For a complete overview of the data fetched by the application or the data written back to VA services, please consult the [example data yaml file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/engineering/api-contract.yml).

**Comment by andreahewitt-odd** [comment]
We don't have a formal ATO review process right now so I'm going to close this ticket. Consider it checked off your list.
