### ISSUE TITLE
Facility Locator Showing Duplicated Services for Community Care Providers

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#3101]
## What happened?
_Community Care Provider Services are duplicated on both the Facility Locator and Facility Locator Detail Page_

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/d4a1bf0c-3662-44fb-babf-c8e8bd1439ca)

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/14ba5dcd-fc9b-4079-820c-d94c99de63dc)

## Specs:
- Device: All
- Browser: All

## Steps to Reproduce
- URL: https://www.va.gov/find-locations
_1. Input Zip Code (e.g. 21211), select "Community Care (Non-VA Health)" from middle drop down, and submit a specialty (e.g. Podiatrist). and click "Search"_
Results: Note the duplication of "Podiatrist" multiple times under "Services" in the left pane next to map. 
_2. Click on the first entry to see the Facility Detail Page._
Results: Note the duplication of the service type definition multiple times on the page.

## Desired behavior
_A service should appear once and only once for each Provider_

## Acceptance Criteria
- [ ] Regardless of the duplication in specialty/service for a single provider in PPMS, each specialty/service is displayed only once to the user. 

## Use Cases
- [ ] A provider is listed in PPMS with only one specialty in only one network: the provider's specialty should display once. 
- [ ] A provider is listed in PPMS with only one specialty in multiple networks: the provider's specialty should display once.
- [ ] A provider has multiple specialties in only one network in PPMS: each of the provider's specialties should display once.
- [ ] A provider has multiple specialties in multiple networks in PPMS: each of the provider's specialties should display once.

**Comment by mmiddaugh** [comment]
Per community Care stakeholders, the duplication of services is legitimate on the data side since providers can be listed in more than one network or region. We just need to determine how to block that duplication from being displayed to the user.

**Comment by mmiddaugh** [comment]
From the OCC/Microsoft Forum: 

> Hi David, a while back there was a request to re-map the specialties for this function to point towards each Specialty associated with the active related Provider Services for the Provider. So what you are seeing here is a Provider who performs the same specialty in many different locations. If you expand on the Provider Services instead like this: https://dws.ppms.va.gov/v1.0/Providers%281184611063%29?$expand=ProviderServices , you will be able to see each unique location that the specialty is associated with. Hope that helps!

**Comment by mmiddaugh** [comment]
Based on PPMS call today, our team will need to deal with duplication by adding "is distinct" logic

**Comment by mmiddaugh** [comment]
Need to discuss pagination impact

**Comment by mmiddaugh** [comment]
de-duplication of error will need to be done on our side (PPMS will not handle this)

**Comment by mmiddaugh** [comment]
@darkbushido This duplicated services situation is also impacting the "number of results found". As seen below, each mention of the service is being counted as an individual result. 

![image (9)](https://user-images.githubusercontent.com/55411834/73400133-63ce8900-429d-11ea-9a55-7a9a7d90f5d9.png)
