### ISSUE TITLE
Mid-December:  Update pension phone number

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#3103]
From Angie Smith:
Please update current pension phone number in right rail of https://www.va.gov/pension/  New number is effective Dec. 1 but stakeholder wants to update now. 
 
Current number to be deleted: 877-294-6380.

New number: 800-827-1000

Note: There's a training component to this update, so that's reflected in the sizing of this work. Adrianne Hooten of Veterans Benefits Administration, Office of Strategic Engagement, wants to learn how to make this update in Drupal. 

Target go live - Dec 31st [EDITED NEW GO LIVE DATE, PER ANGIE SMITH]

![image.png](https://images.zenhubusercontent.com/5c6313e20f871b64caae9909/289fdea5-3cf8-4500-ab04-b028fc712723)

**Comment by Karak888** [comment]
practice run to help VBA making updates in Drupal but using our whole editorial workflow.

**Comment by Karak888** [comment]
@AnneHurley @RLHecht @jenniferlee-dsva - I am going to move this to the ready column with note that the date will be around mid-december.

**Comment by jenniferlee-dsva** [comment]
@Karak888 - per Angie Smith - this ph# update can't go live before Dec 31st, so I think we can ice box this until Dec....

**Comment by Karak888** [comment]
per @jenniferlee-dsva moving to icebox.  Thanks

**Comment by jenniferlee-dsva** [comment]
@RLHecht for Monday go live: please copy check and publish this change per thread: https://dsva.slack.com/archives/CDHBKAL9W/p1576271578006600
 - remove the old pension ph # in the right rail component on the hub landing page. 

Also, please check other pension detail pages to see if this old pension ph#  appears and change to: 800-827-1000. If there's a label in the copy, this number should be referred to as "VA benefits hotline," as it is in the right rail.

**Comment by RLHecht** [comment]
I checked the deletion on this page and set it to publish. There were no other instances of the number on other Pension pages. Moving to validate.

**Comment by RLHecht** [comment]
This is now live on the site. Closing issue. @Karak888

**Comment by jenniferlee-dsva** [comment]
@RLHecht - could you please let Angie Smith  know via email and CC myself and Misty's team? (If you haven't already - I may be behind emails.)
