### ISSUE TITLE
[Design] Pre- check-in - Identify and document Happy Path and test plans

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31067]
This ticket is to identify and document happy paths and test plans in preparation for the usability tests.
- Refine content
- discuss UI patterns
- discuss edit function, introduction page, task list
- Only includes Sketch files

Acceptance Criteria
- Communicate the whole workflow with appropriate teammates
- Completed sketch files

**Comment by julieadair1** [comment]
@kristenmcconnell - this is supposed to be assigned to Ya-ching but she does not seem to be in the repo yet so I was unable to assign it to her.

**Comment by kristenmcconnell** [comment]
We finalized the designs for the usability test within this ticket. The final UX Pin prototypes are[ linked to here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/conversation-guide.md).
