### ISSUE TITLE
[Design] Create wireframe/prototype options for test (telemedicine)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31071]
As a Veteran, I want to view telehealth visits that are scheduled so that I can see all appointments available in the mobile checkin experience. 

**Acceptance Criteria**
- [ ] Wireframes have been create in Sketch to show telehealth appointments on the appointments page
- [ ] discussed UX Team
- [ ] Discussed with Product

**Comment by zach-park** [comment]
Update the verbiage saying "the user needs to refresh".
