### ISSUE TITLE
Analytic review (telemedicine)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31070]
As a Veteran, I want to be able and view if I have a telehealth visit scheduled while in the mobile check-in experience. 

**Tasks:**
- Identifying the data that we want to look at
- Getting that data
- Reviewing the data and making a decision about telemedicine priority

**Acceptance Criteria:**
- [ ] Analytic data has been reviewed once received from VAOS
- [ ] Discussed with Product to determine priority on work.

**Comment by julieadair1** [comment]
**Description**
We need to pull general numbers around telemedicine use.  Specifically we'd like to know if a veteran could have a telemed visit as one of many appointments in a single day.

**Comment by julieadair1** [comment]
![image.png](https://images.zenhubusercontent.com/613f9871fe0319b49ed998be/ddabd24b-9185-4e00-929f-8d6452a74ac4)

**Comment by julieadair1** [comment]
![image.png](https://images.zenhubusercontent.com/613f9871fe0319b49ed998be/864883be-ea0d-498c-ab7a-9b98a2418d4a)

**Comment by julieadair1** [comment]
![image.png](https://images.zenhubusercontent.com/613f9871fe0319b49ed998be/908a7b0c-4475-419f-b9d2-53ced644b0e1)

**Comment by kristenmcconnell** [comment]
Work will continue in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34217
