### ISSUE TITLE
Implement Proposed OAuth Solution for TUD

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31083]
## User Story
- [ ] @holdenhinkle -- Update the description of this story with the new version of the implementation details.

As a TUD user I would like to be able to authenticate to the tool using my GitHub identity because it would help me to readily access the tool without the need for creating a separate account maintained through basic authentication for just TUD.

## Expected Behavior

GitHub verifies the identity of the user and authenticates the user to TUD.

## Acceptance Criteria

- [x] The solution proposed in the [research ticket](https://app.zenhub.com/workspaces/testing-tools-team-sprint-board-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/20612) has been implemented
- [x] The authentication process has been tested among other team members
- [ ] The authentication process has been piloted with one VFS team

**Comment by holdenhinkle** [comment]
I have the api side working with `warden-github`. 

It's seems I'm not a part of the Department of Veterans Affairs org and I had to request access. Strange:

![Pasted Graphic.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/9478304a-03e8-4d7c-a45f-10ff8012fcbc)

I'm not sure if `warden-github` will work. After logging in, it renders the response to the path assigned to the redirect_uri:

> redirect_uri: Defaults to the current path. Note that paths will be expanded to a valid URL using the request url's host.

So the URL is the API URL - http://localhost:3000/test_user_dashboard/oauth

I can redirect to a given URL (to the react app) and provide the user's code as a URL parameter but I'm unclear how to persist the authentication and send the TUD users payload to the React app.

**Comment by holdenhinkle** [comment]
Yay, it's working!

**Comment by holdenhinkle** [comment]
I just submitted an issue to transfer the Test User Dashboard GitHub OAuth App to the department-of-veterans-affairs org - https://github.com/department-of-veterans-affairs/github-support/issues/64

**Comment by holdenhinkle** [comment]
I submitted a support request to Ops, asking them how to remove Basic Auth from the TUD app - https://dsva.slack.com/archives/CBU0KDSB1/p1634253752478700

**Comment by holdenhinkle** [comment]
DRAFT PR to remove Basic Auth from TUD - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/200

# THIS IS NOT READY TO BE REVIEWED AND MERGED. NOT UNTIL THE OAUTH PART IS MERGED.

**Comment by holdenhinkle** [comment]
I followed up on the OAuth App transfer - https://github.com/department-of-veterans-affairs/github-support/issues/64#issuecomment-946977275

**Comment by holdenhinkle** [comment]
I paired with Darius for a couple of hours writing RSpec tests. Almost there:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/3199e6a0-8bfd-48d1-a59a-135563052740)

**Comment by holdenhinkle** [comment]
`vets-api` PR submitted - https://github.com/department-of-veterans-affairs/vets-api/pull/8128

**Comment by holdenhinkle** [comment]
PRs to revert TUD OAuth for now:
- `vets-api` - https://github.com/department-of-veterans-affairs/vets-api/pull/8370 (AWAITING APPROVAL FROM THE IDENTITY TEAM)
- `tud` - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/92 (APPROVED AND READY TO BE MERGED)

My implementation of GitHub OAuth for TUD requires the `api_session` cookie to be passed back and forth between `staging-api.va.gov` and `tud.vfs.va.gov`.

This is the file in `vets-api` that configures session cookies - `config/initializers/session_store.rb`. It implicitly configures the cookie’s `domain` attribute to the exact name of the request host. For example, in staging it's set to `staging-api.va.gov`, so the cookie can’t be passed between other subdomains.

We’re looking for a workaround or an alternative approach.

Here’s a PR I created where we can noodle on ideas - https://github.com/department-of-veterans-affairs/vets-api/pull/8377

**Comment by holdenhinkle** [comment]
Both of the 'revert github oauth' PRs were just merged.

I scheduled a meeting with Joe Niquette and Peter Hill this coming Monday at 2pm to discuss TUD/OAuth.

**Comment by holdenhinkle** [comment]
Fleet and I had a mob session today where we spent some time trying to override the domain attribute for the `api-session` cookie. After the session I noodled with the code quite a bit and realized it's not possible to override it using the approach we were investigating which lead me to doing a bunch of research.

Where the session cookie is configured:
config/application.rb

```
    config.middleware.insert_after ActionDispatch::Cookies,
                                   ActionDispatch::Session::CookieStore,
                                   key: 'api_session',
                                   secure: Settings.session_cookie.secure,
                                   http_only: true
```

Post about it:
https://stackoverflow.com/a/29610937

List of options:
https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L195 

- - - 

Rack middlewhere sets the session cookies
https://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack

`ActionDispatch::Cookies`
* Sets cookies for the request.
`ActionDispatch::Session::CookieStore`
* Responsible for storing the session in cookies.

- - - 

Override Rack Middleware
Set the domain on the session cookie dynamically.
https://stackoverflow.com/questions/4060333/what-does-rails-3-session-store-domain-all-really-do

- - - 

@app.call(env) -  calls the next middleware in the chain
https://stackoverflow.com/questions/46436376/what-does-app-callenv-really-do 

- - - 

Adding rack middleware
https://blog.engineyard.com/understanding-rack-apps-and-middleware

- - - 

Question about dynamically setting session cookie with some interesting code (not sure it works though) - https://stackoverflow.com/questions/52392428/how-to-dynamically-change-the-session-cookie-name-in-rails

**Comment by f1337** [comment]
Per the pairing session w/ @holdenhinkle & I had last week, we can probably side-step the cookie-juggling approach by adding a revproxy entry for TUD. So that TUD is available at `dev.vets.gov/tud` or similar. I think doing so is more secure than mangling cookies, but I'm open to being wrong.

**Comment by holdenhinkle** [comment]
This is complete.

**Comment by pjhill** [comment]
Thank you so much, Holden, for sticking to this and working through the odd requirements and changing landscape!
