### ISSUE TITLE
Improve Slack UX

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#3109]
From contract: improving the information architecture and processes of the shared VA.gov Slack organization to enhance scalability, cross-team and cross-functional collaboration, and information dissemination.

**Comment by rroueche** [comment]
- This shouldn't be a leadership initiative, ideally is prioritized by one of the team's (service design? product support?)

**Comment by meganhkelley** [comment]
Added content-ia-team label to this, as I'm assuming this will involve some IA work.

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this issue since it's no longer needed.
