### ISSUE TITLE
Create allowlist of eligible apps for single app builds

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#31122]
## Details
As of now, not all apps can be built in isolation due to other applications importing from them (primarily static-pages and personalization apps). We need an allowlist of apps that are eligible for single app builds so that only these apps are allowed to be built in isolation in GitHub Actions.

## To Do
- [x] Generate a list of apps that are eligible for single app builds
- [x] Determine which apps are good candidates for a beta release of single app builds
- [x] Determine where to locate the allowlist within the vets-website repo

**Comment by alexandec** [comment]
I looked through the spreadsheet and the completed tickets to find apps that can currently be built in isolation. I then checked each one by deleting it and running `yarn lint` to see if there were any import errors. Here are the apps that remained after all my checks:

- appeals
- ask-a-question
- auth
- beta-enrollment
- caregivers
- check-in
- coronavirus-research
- coronavirus-screener
- coronavirus-vaccination-expansion
- discharge-wizard
- e-folders
- health-care-questionnaire (group)
- letters
- lgy/coe
- medical-copays
- messages
- proxy-rewrite
- public-outreach-materials
- terms-and-conditions
- vaos
- verify
- veteran-id-card
- veteran-representative
- virtual-agent
- yellow-ribbon

So our initial choice(s) for the allow list should be limited to apps in this list.

**Comment by alexandec** [comment]
@timwright12 @theodur do we want to narrow the list down further in this ticket? If so, what's the best method to pick just one or two apps?

**Comment by alexandec** [comment]
@timwright12 that makes sense. Each team has control over their own manifest.json, so if they want to override our centralized allowlist, they can do so. Hopefully they love the feature and don't have any issues, so they won't want to disable it 😄

**Comment by alexandec** [comment]
PR is merged so we're all set with this ticket.
