### ISSUE TITLE
Document Editing - Launch realtime collaboration tool

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#3113]
### User Story

As a team member building on or in support of VA.gov, I need to be able to collaborate with my colleagues on documents in realtime, so that I am working from the most up to date version and single source of truth document. 

### Problem Statement

How might we align on an approach to realtime collaboration that works in the VA ecosystem?

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov. 

## Measuring Success (KRs/KPIs)

TBD

## Details and Notes

A lot of our cross-team documentation requires people to be able to continuously and simultaneously update files in realtime. Since google sheets and docs are the simplest/best means of collaboration and continuous updating (short of building a proprietary application), today we use those tools as the source files but since VA GFE are blocked from all Google applications, we have to export to Excel, PDF, Word, etc for those w/o access. It's frustrating when clients need to review documentation, and they can't review the source files without doing some "questionable dancing."

### Links

- [VA Technical Reference Model](https://www.oit.va.gov/Services/TRM/SearchPage.aspx)

### Assumptions and Hypotheses

- We **assume** that people need to be able to collaborate on a single document both on and off the VA network. 

## Areas for Discovery

- What collaborative tools are already accessible within the VA network? 
- Google Drive is prohibited within the VA network, but we also hear that some folks might be using it — how can we get clarity here on the status of Google Drive? 
- If collaborative tools are approved by the VA, will that mean they are only accessible _on_ the VA network?

**Comment by rroueche** [comment]
Feedback from Kevin Hoffman:

- Legacy documentation for future VA teams, e.g. a link from a Github issue to a sheets doc will be a non-issue

- Direct collaboration with DEPO/VA folks - it puts us in the position of (as I understand it) violating workplace policies, and/or using personal equipment which may also violate policy

- Normalization of tools can be guided by different principles - quality of tools and user experience, or universal access. It's lame that they are in conflict here.

**Comment by meganhkelley** [comment]
This is duplicative of a super epic (placeholder) content & IA has. Closing ours, adding our label here, and moving to "future".

**Comment by vbellissimo** [comment]
Cancelling/old task.
