### ISSUE TITLE
[Design] Explore Improvements to Household information section of the 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#31146]
## Background

This ticket is for initial design ideas and research into the data we have from previous feedback sessions.  

## Tasks
- [x] Research materials provided to look into pain points and potential opportunities to improve the flow and content of the Household section
- [ ] Present to the team for discussion and feedback

## Acceptance Criteria
- Potential design ideas are presented and discussed with the team
- Collab Cycle can begin after the team agrees on the initial approach

**Comment by Dene-human** [comment]
@nicko-amida Here’s the[ Discovery research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/april-may-2021/end-user-discovery/10-10EZ%20Discovery%20Research%20readout.pdf)>Section Specific Findings>**Household Information section**

This should be useful as you start to tackle this

**Comment by Dene-human** [comment]
Hey @nicko-amida FYI for when you tack this:

Mark looked on the paper form and for the "amount you or your spouse paid in non-reimbursable...." It should actually be "and/or" - or something that captures that it's a combined. 

Another consideration is that we shouldn't include "spouse" if they said they don't have one


![Screen Shot 2022-05-13 at 11.27.42 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/c0e95d3c-888f-442b-8382-276640cfec23)

**Comment by nicko-amida** [comment]
@Dene-human @hdjustice Here's the [household design discovery pdf](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/Household%20info%20design%20discovery.pdf) we'll be going over during our team discussion on this section.

**Comment by Dene-human** [comment]
Good stuff! I look forward to our chat later! Another couple of "problem statements" that you might want to consider adding to your Discovery list is: 
1. Where do Veterans get their mental model of where to find this financial information? - understanding natural instinct for "where to look first" - for indication on where our path starts
     a. I'm also curious how they go about deciphering what we currently have up.
3. What similar or different services are asking for this information in a way that makes /it's very clear what they're requesting? (maybe conduct a mini website audit)


I really like how you did the setup here:
![nice](https://user-images.githubusercontent.com/80857940/171420252-6a1e04c5-cbd2-443b-9eb1-488dc0529fd7.png)

**Comment by Dene-human** [comment]
Your initial design idea for adding dependents reminded me that we have a "faq pattern" ([example](https://www.va.gov/health-care/covid-19-vaccine/)) that might be useful for that application, but might also be helpful for some of those content heavy explanations around the financials.
