### ISSUE TITLE
[Design] Improve Military  information section of the 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#31147]

**Comment by markfallows** [comment]
@hdjustice Given that we have other plans for this page, do you want to close this ticket out?

**Comment by hdjustice** [comment]
We can close this since there is no information as to what improvements were in question.  While we are still not sure how we will address the military information section (removal, revision/reorganization, etc), we will created tickets specifically for that effort.
