### ISSUE TITLE
Prep Tasks for Research: Harassment Landing Page & Poster (HRT)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31148]
## Issue Description
_Tasks needed in support of upcoming research project for Harassment Reporting Tool (HRT) initiative_

## Preparatory tasks
- [x] Share research plan and conversation guide with Shane & Kevin for approval and recruiting
- [x] Followup with SMEs re recruiting volunteer clinicians, if needed
- [x] Email volunteer clinicians to sign up to observe sessions
- [x] Slack team members to sign up to observe sessions
- [x] If any open team member observer slots, invite others interested (Melinda)
- [x] Make note-taking spreadsheet
- [x] Schedule pilots--be sure to mention that the study is about harassment
- [x] Test Zoom login and change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilots
- [x] Debrief pilots 
- [x] Send thank you notes to pilot participants
- [x] Revise conversation guide from pilots
- [x] Send instructions to observers of the pilot
- [x] Send instructions to observers of sessions (anyone who didn't observe a pilot)--Chaka, Melinda, Karen
- [x] Invite observers to attend debrief session on the day of their observing
- [x] Email clinicians if there are still open slots left
- [x] If still open clinician slots, ask Martha if she could be an extra observer
- [x] Send instructions to clinical observers of sessions
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day

## Acceptance Criteria (AC)
- [ ] All set to start research sessions

**Comment by cindymerrill** [comment]
Found one pilot tester but haven't scheduled pilot test yet.

**Comment by cindymerrill** [comment]
This ticket should perhaps move into Backlog since I'm not going to work on it for a while. @brianalloyd

**Comment by cindymerrill** [comment]
Should we change the name on this ticket so it applies to the Static Landing Page research instead of the online reporting tool, @brianalloyd ?

**Comment by cindymerrill** [comment]
I'm going to go ahead and rename this ticket so it applies to the current research study I'm planning (on the landing page and poster) instead of the previous one that I didn't do (online reporting tool) so I can use it now. @brianalloyd

**Comment by cindymerrill** [comment]
I emailed the 6 social workers who had volunteered last fall, and I heard back from 4 of them. 3 are still interested and available, but one is on leave during the testing days (if our timeline slips, I'll reach out to her). Still waiting to hear from 2 more...

**Comment by cindymerrill** [comment]
Emailed someone to potentially be a second pilot participant, which I'd like to be a Veteran. I already have one pilot participant who's not a Veteran.

Launched recruiting today by sharing research plan and conversation guide with Shane for review. 

Reviewed Martha's poster after she revised it with Danielle's suggestions.

Have one more social worker potentially interested in observing sessions, if any fit into her schedule. Emailed a VHA person about potentially recruiting additional volunteer social workers.

**Comment by cindymerrill** [comment]
I still have only 3 social workers who are interested and potentially available to observe research sessions, and I haven't heard back from the SME contact about sending out another recruiting email. I just emailed my other two SME contacts to ask for recruiting help.

**Comment by cindymerrill** [comment]
Haven't heard back from the potential pilot participant I already emailed, so I reached out to someone else.

**Comment by cindymerrill** [comment]
Updates:

- Still have only 3 volunteer clinicians so far, but one of the SMEs I emailed yesterday sent out my recruiting email to 12 clinicians. I'll check my VA email tomorrow to see if any volunteered.
- Perigean has scheduled most of the sessions for March 14-18. I'll put them into a spreadsheet to share with clinicians to sign up.
- I need to schedule 2 pilots. Who wants to be there to observe? Brian? Trent? If so, when are you available on Mon and Tue?

**Comment by cindymerrill** [comment]
- Scheduled 1 pilot for Tue and trying to schedule another for Mon but can't find anyone. And also worried that the landing page won't be ready for Mon, so maybe just pilot on Tue?
- Perigean has scheduled all 15 sessions, and they did create a registration survey with my additional screening questions. They recruited for all of my must-have's and many of my good-to-have's. I created an online signup sheet for observing sessions and sent it to my 3 volunteer clinicians (no new volunteers) plus Dave, Danielle, and Martha to sign up.
- Reached out to Martha for the latest poster, and Danielle re anything from VCL team.

**Comment by cindymerrill** [comment]
- Did research prep tasks for research pilots. Have 9 of 15 regular sessions covered by volunteer clinicians.
- Emailed pilot observers instructions
- Tested Perigean's Zoom login, updated settings
- Made notetaking spreadsheet
- Printed conversation guide for the first pilot
- Scheduled debrief sessions after pilots and regular sessions.

**Comment by brianalloyd** [comment]
Closing out this ticket @cindymerrill

**Comment by cindymerrill** [comment]
This ticket isn't done! Who checked off some of the tasks I haven't done?! Need to keep it open. @brianalloyd

**Comment by cindymerrill** [comment]
Invited more people to observe sessions

**Comment by cindymerrill** [comment]
Finished all tasks, and research sessions started today
