### ISSUE TITLE
[DISCOVERY] Research how to leverage SQS and SNS on the VA systems

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#31144]
## Technical Task

We need to use SQS and SNS to make sure the `va-notify` scales with large batches of request. Make sure we know how to integrate these systems together so we know what the complexity is and how to implement it. 

We also need to make sure we have access to these services via AWS

## Acceptance Criteria
- [ ] We should have documentation on how to integrate `va-notify` into SQS
- [ ] We should have documentation on how to integrate `va-notify` into SNS

**Comment by rileyorr** [comment]
Discussed in backlog grooming that we aren't going the SQS and SNS route based on not having real time MCP data
cc @ScottyRJames
