### ISSUE TITLE
[BE] Build Grafana dashboards for 10-10cg stats

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#31176]
## User Story

As a VA.gov Staff Member, I want to view reporting data for errors in Grafana, so that I may visually monitor these situations.

## Expected Behavior
In #28460 and #28461, we converted Cloudwatch queries to Loki for: 
* Additional Stats
  * Number of Secondary-caregiver-only applications
  * Number of dropped attachments
* Submission Stats - Errors

We want to visualize these Loki queries in Grafana. 

## Acceptance Criteria

- [ ] Grafana dashboards built for the respective Loki queries: "Additional Stats" and "Submission Stats - Errors"
- [ ] Link to Grafana dashboards shared in this ticket
- [ ] Screenshot of dashboard shared here

**Comment by SKasimow** [comment]
For grooming: can we automate a dashboard in Grafana that depicts:

- How many attempted submissions
- How many went through to CARMA (successful)
- How many were blocked by MPI (failed MPI)
- How many were blocked by other types of errors (failed-other)

**Comment by SKasimow** [comment]
@jchilders - can you provide an estimate for this and lmk if we can add to current sprint (sprint 66 ending Feb 8)?

**Comment by SKasimow** [comment]
Adding to sprint 66 pending no act'l MS issues that have to be addressed.

**Comment by SKasimow** [comment]
Closing this ticket; replaced with [36424](https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/36424)
