### ISSUE TITLE
**DISCOVERY** | Automated Workflow | Translated Content 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#31175]
## Story

As a product owner for translated VA.gov content, I would like to find a viable, near-term alternative to Xliff that would facilitate content file exchanges between writers and translators. 

Essentially, we're looking for a solution that enables the receipt and exchange of structured files to be used with translation solutions other than Drupal.

## Acceptance Criteria

- [x] Document any alternative options to Xliff including pros and cons and post in Github product folder

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31175?planning-poker) with ZenHub @adamwhitlock1

**Comment by adamwhitlock1** [comment]
I updated the bottom section of this doc with my findings from exploring the 3 alternatives that I found for exporting content. At this point there really doesn't seem to be any options that would actually work aside from the Translation Management Tools Module.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/XLIFF-to-Manage-Translated-Content.md
