### ISSUE TITLE
Access for Azeez Salu

### ISSUE THREAD

**Issue by azeez-salu** [department-of-veterans-affairs/va.gov-team#31179]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Azeez Salu

### Your Email

azeez.salu@oddball.io

### Name of Your Team

platform, devops engineer, oddball

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBKewALgeYO3gkxzNpGAwxFRYrZHUSz8gCdd9yAJms07oxxZ5P5EzgduylhmyPj64+uFsJzMvy4t1nbPMmvIcBLq0uzhAicukoRL4HpM0gqHwFLdVWhrMlhIk0m3YEi2BVOPyKgNaQ//J5a11c2GwkC9y63WjWXpBD8dj5jZuDonJXA8qVRNUdH1zZWojXsWkeQx88wQr/TBqlmFb6EbRoFm3Cy+xZ/EqIfB5ewGblfaqbE0Ix1xGL9djDf0E3I3NJNLfOLhgt9nQeCyc09usyOl9AmKisyqaF7wzVaQ5AJ6YJR5fT+jItVPgM0W2Uk2ROx6tfZvJlEIl0KOg9aPGSHsk2f1efJ9jOcLgC1bscuG2rrYlpui+o2TS99GG2SJPs87I/F3EINuTNrZezjshRMbNt8LwrasdP4YtsHViJILG4ogB+n+hzohGEdHuvqBOtQbihCCz3DqzEewsmiH40Kfxbed++QkdgZTa1FUQIzUcjwVaD9FmU86n0HknHv6c= azeez@Azeezs-MacBook-Pro.local

**Comment by mydesignrocks** [comment]
@mchelen - please review for AWS access. Azeez is a new addition to the ops team.

**Comment by mchelen-gov** [comment]
@mydesignrocks EQIP transmittal date confirmed, request approved 👍

**Comment by jbritt1** [comment]
First time login credentials for AWS provided to user at this time.
