### ISSUE TITLE
AFS CT Form Update: Update Expiration form - 1995

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#31173]
The expiration form for 1995 needs to be updated from 10/31/2021 to 8/31/2024.

NOTE: This needs to be completed prior to the expiration date of 10/31/2021

https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction

![image](https://user-images.githubusercontent.com/85580424/136305970-e8b8fa45-bb99-4ff0-a8de-baf5a77be190.png)

**Comment by hallihocine** [comment]
Test script/steps: 
[AFS CT Form Update- Update Expiration form - 1995.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7340938/AFS.CT.Form.Update-.Update.Expiration.form.-.1995.xlsx)
