### ISSUE TITLE
Which vets-api apis call which upstream services?

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#31183]
In https://github.com/department-of-veterans-affairs/vets-api/pull/8037 @annaswims added a tag to Statsd (Grafana/Datadog) 

- [x] Document how source app header works
- [x] create graph/report in DataDog and/or Grafana that surfaces the data in the tag
- [x] continue the work of https://github.com/department-of-veterans-affairs/vets-api/pull/8037 , which only works within the scope of the request.  Make the tags work within a background job. 
- [x] Notify @drorva of any updated data. He's interested in learning more about which apps/teams depend on EVSS.

**Comment by annaswims** [comment]
I've updated the "Breakers metrics?" column in this table https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services

This is a good representation of where we might be missing metrics. BGS is the only servie that jumps out at me as something we should add.  Some of the services may not have metrics but we may not make api calls directly to theml.

**Comment by annaswims** [comment]
all in all, the data looks like 90% complete.  There are some gaps but my guess is that the tags don't carry through when a request creates a background job (sidkeiq) that then creates another background job. 

the most comon missing tag is  `-> EVSS/Common (/VONAPP2/wss-common-services-web-11.6/rest/persistentPropertiesService/11.6/createUserAccount)` and we can tell with a quick search it comes from `EVSS::CreateUserAccountJob`



<br class="Apple-interchange-newline">
<img width="744" alt="Screen Shot 2021-11-04 at 2 22 12 PM" src="https://user-images.githubusercontent.com/19188/140397568-0829f80e-1449-4ccd-9687-fa2e2474e49c.png">
.

**Comment by wyattwalter** [comment]
Looks like the tasks here are all complete. I'm going to close this one off.
