### ISSUE TITLE
[EPIC] Profile: Personal Information Revision

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31180]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran, I need the ability to change the personal information in my profile so I can be addressed in the way that I would prefer when I visit VA facilities or communicate with a VA representative.

## Hypothesis or Bet
**If** we add personal information fields to the Profile and provide a way for the Veteran to update them **then** we expect to be in compliance with an executive order that mandates that Veterans have the ability to specify how they wish to be addressed.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by Samara-Strauss** [comment]
Work completed June 2022.
