### ISSUE TITLE
Add icon option to background only alert

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#31192]
## What
I'm proposing an official update to our background color only pattern: adding a [feedback icon](https://design.va.gov/design/icons#feedback) option.

## Why
Our background only alert is already used across many services and products across VA. Adding an icon re-enforces the meaning we're conveying with color, which is beneficial to users who are colorblind, have low vision, or cognitive considerations. 

We are already using this pattern on va.gov on form applications (example below; pretty sure this is consistent across all of our online forms); it's just not formally captured on design.va.gov, or available as an option in Storybook. It used to be part of the Sketch library, but was recently removed.

![image](https://user-images.githubusercontent.com/55992116/133847797-337bf614-ffd5-43e9-8fa3-b017fb8bd4c2.png)

Currently, our developers have to customize each time an icon is added to a background only alert. Making it an option in the existing component would improve maintainability and increase efficiency for devs.

Another option could be making a non-expandable version of the [mobile-friendly alert](https://design.va.gov/experimental-design/expandable-alert) available. That would also work for the same use cases a background-only alert with an icon.

## Next steps
I'm requesting an asynchronous approval for this update. 

**Question**
Would I still add this to experimental design, given that it's a new option to an existing component?

**Comment by andaleliz** [comment]
@caw310 what is the status of this being added to the design system? Maybe @GnatalieH knows too.

cc @zacharymorel and @MarciMcGuireGCIO per our discussion today

**Comment by caw310** [comment]
@andaleliz this is in progress. @GnatalieH is currently working on this. 

Please keep in mind that the DST is small. Thanks!

**Comment by andaleliz** [comment]
Oh great! Thank you for the quick reply.

Yes, I'm aware of the small (but MIGHTY 💪 ) DST team.  My intention was only to get a status update as I was getting a new team up to speed on pending issues. Definitely not trying to put pressure to get this work done immediately.

We'll look forward to having this available whenever it is completed.

**Comment by GnatalieH** [comment]
> Oh great! Thank you for the quick reply.
> 
> Yes, I'm aware of the small (but MIGHTY 💪 ) DST team. My intention was only to get a status update as I was getting a new team up to speed on pending issues. Definitely not trying to put pressure to get this work done immediately.
> 
> We'll look forward to having this available whenever it is completed.

Hi @andaleliz! There is progress happening on this work. First, @bkjohnson is fixing the padding on the web component so it's not as extreme (that was an error, not the intended design). It will align with the style of the react component. And, I'm focusing on this design work over this sprint. I'll definitely be asking for your feedback when I get some designs more fleshed out. I want to explore a larger icon now that we can minimize the padding. Thanks!

**Comment by andaleliz** [comment]
Those examples aren't something we implemented, and they use the bulkier padding that was recently fixed.  This is what we implemented in the contact section:
![image](https://user-images.githubusercontent.com/55992116/140565945-d36ef687-4c0e-44c7-bd9d-af2da947db97.png)

Also, you can see a similar one at the bottom of any application above the back and continue buttons.
