### ISSUE TITLE
Collaboration Cycle Kickoff: Auth Profile, Profile Personal Information Revision

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31194]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/preferred-name-pronouns-gender-sexual-orientation/README.md)
- Wireframes, mockups, or prototypes 
   - https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565
   - 
- Any other artifacts you have so far
   - Content request #31186
## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [X] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: Authenticated Profile

### 4. Are you making changes to the visual design?
- [X] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [X] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [X] New content
- [ ] Changes to existing content

### 8. Are you making a change to the user flow?
- [X] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [x] Yes
- [ ] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [X] Yes
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

### 12. Does your team have a Github label for this product?

- [ ] No. 
- [x] Yes. Please specify: `Profile`

### 13. Who is the VA business owner for this body of work?

- [X] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [X] Other. Please specify: initial request came through VHA, but VEO is also an owner of this work, as we believe the VA Profile backend falls under their leadership (and the VA Profile backend will be supporting the personal information updates via an integration with MPI)

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.

**Comment by Samara-Strauss** [comment]
Reopening because I spotted a couple mistakes in the original intake that might change @shiragoodman's initial recommendations:

> Are you doing research with VA.gov users?

This was marked as no, but we will eventually do usability testing with users.

> Are you making a change to urls, navigation, or entry points?

This was marked as no, but we will be updating URLs because we are splitting the current Personal & Contact Information page in the profile into two pages -- one for just personal information, and one for just contact information. This will result in an updated URL for the personal information section and a new URL for the contact information section.

> Does your team have a Github label for this product?

This was marked as a no, but it's sort of both yes and no. All profile work uses the Profile label in Github, but we haven't yet created a project-specific label. We probably should, though, @MarciMcGuireGCIO. Let's figure out what it should be.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @Samara-Strauss !  I will update my answers to reflect that information.  @shiragoodman - for visibility.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - perfect!  I'll create that now.

**Comment by shiragoodman** [comment]
to clarify, we'll still review IA in the collaboration Cycle, but the IA recommendations will come from the Sitewide content team... ie Mikki.
