### ISSUE TITLE
Access for Cameron Eagans

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-team#31199]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Cameron Eagans

### Your Email

cameron.eagans@agile6.com

### Name of Your Team

PTEMS VA.gov Modernization, Application Engineer/DevOps, Agile6

### Service(s) You Want Access To

AWS

### Desired AWS Services

I'm working on devops on the Platform CMS team. It looks like I need the `adhoc-vetsgov-devops` and `force-MFA` roles similar to Neil Hastings (https://github.com/department-of-veterans-affairs/devops/blob/290d35b928437546ea9d9703ce065460fb930bd6/terraform/environments/global/iam_users.tf#L1479-L1488) and Elijah Lynn (https://github.com/department-of-veterans-affairs/devops/blob/290d35b928437546ea9d9703ce065460fb930bd6/terraform/environments/global/iam_users.tf#L608-L617).

**Comment by mydesignrocks** [comment]
@mchelen - please review for AWS access. thanks.

**Comment by mchelen-gov** [comment]
@mydesignrocks EQIP transmittal date confirmed, request approved 👍

**Comment by mydesignrocks** [comment]
Complete and provided the login details.

**Comment by cweagans** [comment]
Hello, I was able to get this set up, but it appears that I've been assigned to different groups than the rest of my team. I am concerned that this different level of access will impact my ability to contribute to team efforts. I now have `dsva-vfs-developers` and `dsva-vfs-all`, rather than `adhoc-vetsgov-devops` or similar. Can this be adjusted as part of this ticket or should that be a new one?

**Comment by rbeckwith-oddball** [comment]
I have removed you from the dsva-vfs-all and dsva-vfs-developers groups and added you to the adhoc-vetsgov-devops group.

**Comment by mchelen-gov** [comment]
@cweagans is approved for addition to `adhoc-vetsgov-devops` IAM role
