### ISSUE TITLE
Request Content review: Eligibility page for the Higher-Level Review application

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3120]
**User story**
As a member of Benefits and Memorials team building on VSP, I need my content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2026)
- [InVision Design](https://vsateams.invisionapp.com/share/5RUP8V2TSHD)
 ![02-request-higher-level-review copy](https://user-images.githubusercontent.com/10746807/68208963-5ce6f180-ffa0-11e9-8481-08f57a94c70e.png)

**Acceptance criteria**
- [x] Content reviewed 
- [x] Required content updates/changes provided to Benefits and Memorials team

**Comment by peggygannon** [comment]
Hi, @YanaRoy What is your deadline for me providing feedback on the content review? I'll be able to start work on this on Friday. Please let me know if that works.

**Comment by peggygannon** [comment]
@YanaRoy @carolynwill hello, I've reviewed the Invision mockup for the HLR Eligibility page. Please see the mockup for my content recommendation. 

Have you sync'd with Mikki  Northuis on the IA for this page? I've made some notes about the left nav and the breadcrumbs that are in this mockup. Mikki should weigh in on these elements too. 

cc'ing @mnorthuis

https://vsateams.invisionapp.com/share/5RUP8V2TSHD#/screens/392020153/comments

**Comment by carolynwill** [comment]
Content edits have been made. @peggygannon 

A look over by @mnorthuis on IA is needed.

**Comment by mnorthuis** [comment]
The above image does not have accurate breadcrumb or left nav, this content does not live in the Disability hub, it lives in its own area at the root level.  

Since this is a ticket for a content review of just one page, can you please create a separate ticket for the IA review where I can look over all pages of the experience? Then I can provide a full review, or I am happy to talk through it in a call as well.  Thanks!

**Comment by kevinstachura** [comment]
@mnorthuis absolutely! Until we look at how the full Decision Reviews section of the website is structured, we can't really move forward to say the left nav is necessarily accurate' Depends on how we decide to structure the content/pages within, of course. I'm going to open a new ticket to determine the structure so we can ensure the accuracy of the left nav and the breadcrumbs as well (root level makes sense if Decision Reviews handles different types of claims).

**Comment by mnorthuis** [comment]
Thanks @kevinstachura.  Since the Decision Reviews content is all live, there technically is a structure and URLs are already in place - therefore the left nav and breadcrumbs are currently set. If you plan to reorganize that content, we will need to shift pages/links and implement redirects.

**Comment by peggygannon** [comment]
@carolynwill I've reviewed the updated mockup and all looks good. I made two more content recommendations. thanks.

**Comment by YanaRoy** [comment]
@rileyorr

**Comment by rileyorr** [comment]
@YanaRoy @kevinstachura I don't think I have access to update this screen. Do you know what Invision workspace this mockup exists in? It seems like an older version exists in the Invision workspace all the other HLR screens live in.

**Comment by Mottie** [comment]
@rileyorr https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/392996930

**Comment by rileyorr** [comment]
@carolynwill & @peggygannon I have updated everything except for two comments. I tagged you both in comment #5 because I am confused where it's supposed to be pointing to. Additionally, I didn't resolved #2 because I am unsure if the left nav is correct.

**Comment by YanaRoy** [comment]
@rileyorr can this ticket be closed or are is the question above still unanswered?

**Comment by rileyorr** [comment]
@YanaRoy I haven't received a response for comment 5

**Comment by YanaRoy** [comment]
@peggygannon if you have time today, could you please provide a response to @rileyorr 's question for comment 5 above? thank you!!

**Comment by peggygannon** [comment]
@rileyorr @YanaRoy sorry i missed this one. I just commented on #5. Riley, let me know if you have any further questions.

**Comment by rileyorr** [comment]
Hi @peggygannon! Thanks for taking a look at the mockups!! I don't see a response for [this comment](https://vsateams.invisionapp.com/share/5RUP8V2TSHD#/screens/392020153/comments/123947645).

**Comment by rileyorr** [comment]
@YanaRoy Peggy responded to the comment and no updates need to be made. This ticket is good to be closed
