### ISSUE TITLE
QA Feedback - Staging Review - [Design System Team- Back to top]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31211]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- What kind of testing have you done on the component?
- I pulled these three behaviors form the documentation --
  1. As the user scrolls down the page, the Back to top component reveals as a sticky button in the lower right edge of the main content area.
  2. The Back to top component stays fixed in the lower right edge of the main content area when the user reaches the bottom of the page.  
  3. Clicking the Back to top button takes the user to the top of the page.

These desired behaviors are a great target for acceptance tests or functional testing recorded in TestRail. I was able to verify these behaviors using the [Storybook example](https://60f9b557105290003b387cd5-lsofcanvcu.chromatic.com/?path=/docs/components-va-back-to-top--default).

On the other hand, AFAIK design system components have not previously gone through the Collaboration Cycle, so I'm not sure what kind of testing is really called for in this scenario.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
None

**Consider:**
- While I was playing with the component in [Storybook](https://60f9b557105290003b387cd5-lsofcanvcu.chromatic.com/?path=/docs/components-va-back-to-top--default), I noticed that the "Back to top" component appears to retain focus after the use interacts with it and it disappears. If the user then scrolls down again, after clicking "Back to top" the button is still highlighted. Then if the user presses space, the button is interacted with again. I'm not sure whether this is desired behavior or not. It's just something that I noticed.

- Consider adding aXe checks to unit tests for the component.

**Comment by bkjohnson** [comment]
- The focus issue is [just a problem with storybook](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30709#issuecomment-937366333) - the focus behavior works elsewhere.
- [Axe check tests are in place](https://github.com/department-of-veterans-affairs/component-library/pull/170/files#diff-af724900bd221298ab127bbd8794dbd750b2fe4ebf2945e5043b6f18c5712e12R122-R153)
