### ISSUE TITLE
review instances need to cleanup workspace

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3121]
Review instances fail when re-running the jenkins job for a PR after a failure.  This is because the git checkout (at least for vets-api) refuses to checkout into a non-empty dir, which is left behind by the previous failed run.

Fix the anisble git command to checkout into the dir, or change the job to cleanup workspaces and start fresh.

## AC
- [x] when replaying a Jenkins intense the job does not fail. 
   - go here and try replaying a successful job to test if the AC is true. http://jenkins.vfs.va.gov/job/deploys/job/vets-review-instance-deploy/

**Comment by ricetj** [comment]
@wyattwalter to groom and assign.

**Comment by wyattwalter** [comment]
This doesn't break anymore. I've been watching deploys go and tested it over and over without being able to reproduce this.
