### ISSUE TITLE
COE - Accessibility - Update confirmation page header progression

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#31226]
## Description
Headers should progress in linear order, H1, H2, H3, etc. After #31223 has been completed to update the application H1, the confirmation page will need to have its header progression updated. 

## Tasks
- [update this to a h2](https://github.com/department-of-veterans-affairs/vets-website/blob/39972a9efa1c729ebbfc5d7059cd367e1d4e9f8b/src/applications/lgy/coe/containers/ConfirmationPage.jsx#L21)
- [update this to a h2](https://github.com/department-of-veterans-affairs/vets-website/blob/39972a9efa1c729ebbfc5d7059cd367e1d4e9f8b/src/applications/lgy/coe/containers/ConfirmationPage.jsx#L31-L34)

## Acceptance Criteria
- [ ] Confirmation page header progression has been updated
- [ ] PR has been merged

**Comment by jason-gcio** [comment]
Duped
