### ISSUE TITLE
[FE] Profile: Remove breadcrumbs in Profile

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31229]
## Background
Per conversation with design and IA we determined it's unnecessary to have the breadcrumbs on Profile.

Slack [thread](https://dsva.slack.com/archives/C909ZG2BB/p1633545045475500) for context

## Task
- [ ] Remove breadcrumbs at the top of Profile and all child pages

<img width="881" alt="Screen Shot 2021-10-07 at 3 53 41 PM" src="https://user-images.githubusercontent.com/45603961/136453241-6ec3311b-c97c-466b-9f76-737d84d381a8.png">

## Acceptance Criteria
- [ ] Breadcrumbs no longer appear on Profile or any child pages

**Comment by MarciMcGuireGCIO** [comment]
I'll manage this ticket going forward.

**Comment by erikphansen** [comment]
Ready to validate. I think that @andaleliz and @tressaellen should review both the Profile and My VA to make sure things look good across both applications now that the breadcrumbs are no longer shown. We need to confirm that the vertical spacing looks good where the breadcrumbs used to be.

**Comment by andaleliz** [comment]
Both look good to me across screensizes. Thanks @erikphansen!

**Comment by tressaellen** [comment]
They both look great to me as well. Great work @erikphansen !

**Comment by MarciMcGuireGCIO** [comment]
Marking this closed.  Thanks all!
