### ISSUE TITLE
[FE] My VA: Remove breadcrumbs in My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31231]
## Background
Per conversation with design and IA we determined it's unnecessary to have the breadcrumbs on My VA.

## Task
- [x] Remove breadcrumbs at the top of My VA
<img width="918" alt="Screen Shot 2021-10-07 at 3 54 17 PM" src="https://user-images.githubusercontent.com/45603961/136453453-ba347203-e52b-4e34-b256-844c77b2370c.png">

## Acceptance Criteria
- [x] Breadcrumbs no longer appear on My VA

**Comment by ajakabcin** [comment]
@hdjustice fyi this is the breadcrumb ticket mentioned in the call earlier this afternoon. Slotted for sprint 61 🙂

**Comment by erikphansen** [comment]
Ready to validate. I think that @andaleliz and @tressaellen should review both the Profile and My VA to make sure things look good across both applications now that the breadcrumbs are no longer shown. We need to confirm that the vertical spacing looks good where the breadcrumbs used to be.

**Comment by hdjustice** [comment]
@tressaellen - Have you had a chance to check this ticket out yet?

**Comment by tressaellen** [comment]
@hdjustice - yes! Sorry, I commented in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31229#issuecomment-976776519). I didn't realized there was a second one for My VA. But we should be good to close this.

**Comment by hdjustice** [comment]
As validated by Tressa, there are no issues or concerns with the My VA page after removing breadcrumbs.  Closing ticket.

**Comment by hdjustice** [comment]
@tressaellen Closed, thanks so much!
