### ISSUE TITLE
Prepare Mockups for Usability Testing of Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3123]
## Story
As a designer, I want to prepare my mockups for the usability study so that I am prepared to fully explore the pages with the user accurately.

## Tasks
- Reworking mockups according to a script as a variation (new link)

## Acceptance Criteria
- [x] The new mockups are complete and ready for the usability study

**Comment by sporeboy** [comment]
Working on mapping-out screens to the script. WIP link: https://xd.adobe.com/view/2b040c88-19d3-47dc-4eba-d18d0636ae4e-5d35/

**Comment by sporeboy** [comment]
Links added for additional pages and error states. Ready to go!
