### ISSUE TITLE
Request Content review: Time Periods rule

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3124]
**User story**
As a member of Benefits and Memorials team building on VSP, I need my content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1920)
- [InVision Design](https://vsateams.invisionapp.com/share/8JUSQKTUM76#/screens/388976560)
![](https://user-images.githubusercontent.com/136959/67985326-9d3c1d80-fbf6-11e9-9c49-b319926d41ae.png)

**Acceptance criteria**
- [x] Content reviewed 
- [x] Required content updates/changes provided to Benefits and Memorials team

**Comment by peggygannon** [comment]
Hi, @carolynwill I'm unable to get into the Invision mockup (it says the link is invalid). So I'm listing my 2 content changes here: 

1. Please update this sentence to: 
We'll contact you directly to schedule an informal conference with the reviewer assigned to your issue. 

2 Please update the alert message to: 

**We'll try to call you twice**
A senior reviewer will call you by phone two times. If no one answers, they'll leave a voicemail. If the senior reviewer is unable to leave a message or get in touch with you after 2 attempts, they’ll proceed with their review and issue a decision.

**Comment by Mottie** [comment]
What about if the representative is selected?

* We'll contact your representative...
* A senior reviewer will call your representative... or get in touch with your representative after...

**Comment by YanaRoy** [comment]
@peggygannon could you please provide content for the scenario when the representative is selected to be contacted.

**Comment by peggygannon** [comment]
@YanaRoy @Mottie 

for the representative call: 

Please update sentences to: 

1. We'll contact your representative directly to schedule an informal conference with the reviewer assigned to your issue.

2. Please choose up to two time periods your representative is available to receive a phone call: 

3. Please update the alert message to:

**We'll try to call your representative twice*
A senior reviewer will call your representative by phone two times. If no one answers, they'll leave a voicemail. If the senior reviewer is unable to leave a message or get in touch with your representative after 2 attempts, they’ll proceed with their review and issue a decision.

**Comment by Mottie** [comment]
Merging this issue with #3532 - I will update the content and associate it with that issue.
