### ISSUE TITLE
Request Design QA

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3125]
#### Context
The GI Bill Comparison Tool offers users an opportunity to see employers, schools and training facilities where they can use GI Bill benefits. Previously, the CT 116 work allowed users to search by VET TEC Provider.  Our work on this iteration focused on integrating VET TEC programs into the Comparison Tool.  Throughout our testing efforts, we heard resoundingly that users were more interested in the programs that are available - and this update will provide that information for them.

#### URL 
- Prototype https://bahdigital.invisionapp.com/share/APIAC31SV63#/screens (updated link!)
- Staging https://staging.va.gov/gi-bill-comparison-tool/program-search

#### New Design Patterns
Length in weeks label: This component is derivative of the design for the yellow Caution Flags used throughout the Comparison Tool, which are not yet captured in the VA.gov design system. By using a similar design as the Caution Flags, this will enhance cohesiveness for the different data elements found within the cards on the search results page. The closest element to that that exists in the design system is the labels component found here: https://design.va.gov/components/labels.

####  Design Challenges

_Approved programs_
We use a standard tabular pattern in Approved Programs to allow for users to see relevant program details at a glance. Using a tablular layout here helps organize available program data and makes it easier for users to see related elements grouped together. This will be especially useful as more programs are approved and more programs appear on Provider Profiles. 

When users click through on a specific, program-based search result card, that program will be selected on the Provider Profile page.  Users can interact with other programs the provider offers using the radio buttons to the left of the program names. The selected radio button updates estimated benefits in the "Estimate your benefits" calculator area. This allows Veterans to see key information about their education benefits, such as tuition, out of pocket costs, and housing rates. 

It was essential that we provide Veterans the option to customize their estimated benefits. They can do that by choosing a program in the table. We observed during testing that selecting options from the table and seeing the changes below in the benefits estimator came naturally to users.

_Preferred provider filter_
On the search results page, we initially placed the “Preferred providers” filter within the “Filter by provider” option, but based on user response to this filter element during testing, and due to the need to increase the visibility of these preferred training providers, we decided to place the filter by itself. Doing so made it easier for users to notice this filter.  

_Contact details_
This section comprises contact information for both providers and School Certifying Officials. It was a priority to clearly delineate the different types of data for the school and to make the data fields more scannable using appropriate labels for each of them, especially if a user utilizes screen readers. For smaller displays, the layout will be especially helpful as it can easily collapse. We have seen schools with up to 20 School Certifying Officials, and as such, put together a design that would easily accommodate many contacts. We group each individual’s details together in a format that remains flexible for smaller displays.

**Comment by amyknox** [comment]
We'd like to request that DSVA start the design review on the inVision prototype and finish on staging.  Our target launch date for this work is 11/22 and we'd like to do what we can to keep UX work moving forward while dev is underway.  

A 2-part design review would allow UX to address any "early" issues and then save the more granular, pixel-almost-perfect reviews for the last part of the process.  Below you'll find our thoughts on which Design Review Tasks could be reviewed on the prototype and which would need to be on staging.  

We've discussed this approach with our DSVA contacts ( @KevinMHoffmanUSDS  and @mattpointzxer0 ), who felt the approach was workable.  Appreciate your attention and happy to respond to any questions you may have.  

To review in PROTOTYPE:
*  New design patterns have been vetted by DSVA and documented
*  Correct use of design patterns in context
      *  Form chapters in place
      *  Privacy policy is present
      *  Address form follows pattern if applicable
      *  Name form follows pattern if applicable
*  Correct use of typography
*  Padding and spacing has been applied appropriately
*  Form components used correctly in context
*  Consistent use of iconography
*  Primary and secondary CTA buttons used correctly in context

To review on STAGING:
*  Correct use of typography
*  Padding and spacing has been applied appropriately
*  Consistent use of iconography
*  Colors use are consistent with color palette
*  :hover and :focus states have been accounted for and are consistent with design patterns
*  Alert messages have been used appropriately
*  Error states have been accounted for and used appropriately
*  Loading indicators have been used where appropriate

**Comment by amyknox** [comment]
@emilywaggoner in the event you're looking at the VET TEC 116 Prototype this morning (11/8), hold up a bit.  There are some unexpected updates in the works that we'll likely need to address in the UI.

**Comment by amyknox** [comment]
@emilywaggoner We're ready to start DSVA Design of the GI Bill Comparison Tool, 116 Post-MVP solution on prototype.  Please reach out to me with any questions or comments.

**Comment by amyknox** [comment]
@emilywaggoner We're ready to start DSVA Design of the GI Bill Comparison Tool, 116 Post-MVP solution on staging. Please reach out to me with any questions or comments.

**Comment by amyknox** [comment]
@CrystabelReiter & @emilywaggoner - Please conduct this review on staging. https://staging.va.gov/gi-bill-comparison-tool/program-search

This is the list of known issues.  The team is currently working on Critical and High issues. 
 [https://app.zenhub.com/files/133843125/a48b5d7c-ea22-4ac0-9305-6d6dcca0defe/download](https://app.zenhub.com/files/133843125/a48b5d7c-ea22-4ac0-9305-6d6dcca0defe/download)

**Comment by CrystabelReiter** [comment]
Hi @amyknox, here is the feedback. I've discussed and went over items with @emilywaggoner and @1Copenut 

New design patterns have been vetted by DSVA and documented 🌀
The length in weeks label:
Recommendation: I tested this for color contrast and it failed the contrast test. I’d match to the original design in the prototype where the text color was dark. Change label to #D6D7D9 and font to #323A45 (this is already noted in the spreadsheet) 

Mobile, tablet, and desktop breakpoints have been accounted for ✅(please make changes already in spreadsheet) 
Correct use of design patterns in context
Form chapters in place ✅
Privacy policy is present ✅
Address form follows pattern if applicable ✅
Consistent use of iconography 🌀
Is there a reason the icon for location is present when you click on the card but not on the card in the search results page?
Name form follows pattern if applicable ✅

Correct use of typography 🌀
   Question: is there a reason why the line underneath “GI Bill Comparison” is blue? When I see text in blue I think that it’s a link but the line doesn’t take me anywhere 
Recommendation: Changing the font to standard H3 style and the color to #323a45

Padding and spacing has been applied appropriately ✅-issues with spacing is noted in the spreadsheet 

Form components used correctly in context 🌀
The Learn more links to modals pattern is currently being tested if it’s the most effective way for veterans to gain information. Depending on our studies, the modal pattern could change in the future site wide on VA.gov

Benefits calculator:
Trevor, Emily, and I suggest to add a submit button to the benefits calculator rather than let the form change for screenreader purposes of hearing when their results get updated. Please refer to this issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3536


Colors use are consistent with color palette ✅
 Primary and secondary CTA buttons used correctly in context ✅
 :hover and :focus states have been accounted for and are consistent with design patterns ✅
 Alert messages have been used appropriately ✅
 Error states have been accounted for and used appropriately ✅
 Loading indicators have been used where appropriate ✅

**Comment by amyknox** [comment]
@CrystabelReiter , @emilywaggoner & @1Copenut - thanks for the review & input.  Here are notes on the storm warnings you shared.  

New design patterns have been vetted by DSVA and documented 🌀
The length in weeks label:
Recommendation: Change label to #D6D7D9 and font to #323A45 (this is already noted in the spreadsheet)

*Update in progress*

Consistent use of iconography 🌀
Is there a reason the icon for location is present when you click on the card but not on the card in the search results page?

*This layout and application of the location icon is consistent with the existing pattern for institutes of higher learning & employer search results and their profile pages in the GI Bill Comparison Tool.*

*Example Search results: https://www.va.gov/gi-bill-comparison-tool/search?category=school&name=baltimore&vetTecProvider=false*

*Profile page: https://www.va.gov/gi-bill-comparison-tool/profile/14904420*

Correct use of typography 🌀
Recommendation: Changing the font [of the page title sub-heading on the landing page] to standard H3 style and the color to #323a45

*The content “Learn about education programs and compare benefits by school.”  is existing content / style on the GIBCT. * 

*This is an enhancement outside the scope of 116. We can make this update post-launch.*


Padding and spacing has been applied appropriately 🌀-issues with spacing is noted in the spreadsheet
Recommendation: All dollar values in the benefits calculator should reach the right edge to match with the total

*I'm not completely clear which dollar amounts you're referring to specifically.  If the section in the "Your estimated benefits" panel, where there's the breakdown 25/25/50 - we intentionally indented these dollar amounts due to input during testing.  When dollar amonts were all aligned right, participants were very confused about the calculations what was included in the calculation of "Total out of pocket tuition."  The numerical alignment on staging tested very well.* 

*If you're referring to the alignment of another set of numbers, let me know and we will review.*

Form components used correctly in context 🌀
The Learn more links to modals pattern is currently being tested if it’s the most effective way for veterans to gain information.

*Ok.  Good to know.  We’ll be happy to work with you if these need to be updated in the future.*

**Comment by CrystabelReiter** [comment]
@amyknox Thanks for updating me and answering my question about the location icon. This is fine as is.

The spacing of the dollar values are fine and thanks for alluding to testing results that helped make your decision. 

Please let us know when the things that we agreed upon and discussed are updated in the future.
