### ISSUE TITLE
[Content] HLR: Higher Level Review Content Updates

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3127]
## High Level User Story
As a member of Benefits and Memorials team building the Higher Level Review form on VSP, I need my content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

## Hypothesis/(es)
**If** _the content aligns with all of the VA needs_ **then** _the designs and development can be updated_.

## Goals
_Content team to provide content review to all Higher Level Review pages_ 
_Content team to make notes in InVision to document changes that need to be make to the content._

## Definition of Done
- [ ] Review and update all content
- [x] Provide changes to be incorporated into design mock ups

**Comment by luke-gcio** [comment]
We will no longer use this Epic.  Let's create a new HLR epic for phase 2.
