### ISSUE TITLE
AFS CT: Search engine and map location by state or city display global results

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#31279]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
When a user use GIBCT search, the results include all global affiliated schools instead of just displaying a list of schools by city or state.  This also causes the map to condense all results within the desired state when it should only display those schools located within the desired state.

Steps to reproduce:

1. Go to https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=name&name=Webster%20Groves%2C%20MO&location=Webster%20Groves%2C%20Missouri%2C%20United%20States
2. Select **Search by Name**
3. Type Webster Groves, MO and click **Search**

Actual: Results display schools from other states and countries around the world
Expected: Only schools in Webster Groves, MO should display

Map
1. Click on **Search by Location**
2. Type Webster Groves, MO, select "Webster Groves, Missouri, United States" and click **Search**
Actual: Results display schools from other states and countries around the world in both, the list on the left and the map
Expected: Only schools in Webster Groves, MO should display

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/eb14afb2-da2b-435f-84e0-ca95043eb0d5)

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/6e92983e-848a-4d31-b2e3-0ae022cd03ac)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mrblanco1** [comment]
Blocked until Brian G. replied to Adam.  Brian is OoO until 11/08.

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2814&group_by=cases:title&group_order=asc
Test case: https://afs365.sharepoint.com/:x:/r/sites/DGIBillServicesProject/Shared%20Documents/Legacy%20AO/Team%203/QA/Test%20Results/AFS-Sprint%206/Remove%20LatitudeLongitude%20Issues%20section%20from%20GIDS.xlsx?d=w8d4769e3ca8b4bceb7790d7cd8f30c71&csf=1&web=1&e=ApDUW7

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2838&group_by=cases:title&group_order=asc

**Comment by mrblanco1** [comment]
This issue was fixed and deployed to production on 1/19/2022.
This release required three parts to be completed:
1. GIDS code change to prevent GIDS dashboard from over-writing already fixed data in production
2. Execution of a script in GIDS to correct Geocodes
3. Execution of a second script to correct incorrect country values

Prod validation passed and EDU was informed this fix was in production.

**Comment by af-manish** [comment]
The two scripts that ran are:

lib/tasks/fix_coord_mismatch.rake
lib/tasks/fix_phys_country_coord.rake

They are checked in github here: https://github.com/department-of-veterans-affairs/gibct-data-service/tree/master/lib/tasks

**Comment by mrblanco1** [comment]
This work has been completed. Through the analysis of this issue, Dev discovered major differences between Staging nd Production environments, making it very hard for the team since testing would pass in staging but when solutions were deployed to production issues would be discovered.
Another factor that impacted Dev was that GIDS and it job processes were overwriting data. Through many attempts to try correct this issue, Dev found that GIDS' jobs were built one on top of another, in layers. This also caused the Dev team having to conduct a lot of analysis and testing.
AFS's recommendation is to work with OCTO/Matt Self and OIT and analyze GIDS, how is structured and architected, find a better solution, plan and execute to be able to remove all unnecessary obstacles the team encountered.
