### ISSUE TITLE
Add 2 new PDF quick start guide links on the VA welcome kit page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3128]
On this page - in Drupal: http://preview-prod.vfs.va.gov/prevdew?nodeId=716

@RLHecht - please review the 2 placeholder text for the new QSG's from Tim Hudak in VE, and edit as needed per our style standards; and also add the file links for these 2 new PDFs. 

@Karak888 & @kelsonic - I believe this needs a merge, so the PDF file links are available for Randi to add to the Drupal content. 

- [urgent care qsg](https://app.zenhub.com/files/133843125/73a75482-00da-49eb-81ce-0727d2a8f0a5/download)
- [community care qsg](https://app.zenhub.com/files/133843125/66c2cfdd-21d2-41ac-bb69-7e70befa7861/download)

This should be fine to go live Friday.

**Comment by kelsonic** [comment]
@RLHecht Do you have a preference for the file naming for the above files? Do we need these PDFs in [this directory](https://github.com/department-of-veterans-affairs/vagov-content/tree/master/assets)? :)

**Comment by RLHecht** [comment]
@kelsonic Yes, these should go into the assets folder. @jenniferlee-dsva Are the file names you have above OK to use?

**Comment by kelsonic** [comment]
@RLHecht @jenniferlee-dsva Going to name the files as `/urgent-care-quick-start-guide.pdf` and `/community-care-quick-start-guide.pdf` :)

**Comment by kelsonic** [comment]
PR merged -- @RLHecht could you validate this following deployment later today?

**Comment by RLHecht** [comment]
@kelsonic I validated these PDFS are now in the assets folder. Thank you!

@jenniferlee-dsva I've added the links in Drupal and copyedited the text with no changes. Please review and set to publish.

**Comment by jenniferlee-dsva** [comment]
Done. Thank you both! In the future, I'm fine with you validating and publishing @RLHecht  - you're our Drupal genie.

**Comment by Karak888** [comment]
@RLHecht once validated please just let me know!  thanks so much

**Comment by RLHecht** [comment]
This looks good on live page. Closing ticket. @Karak888 FYI
