### ISSUE TITLE
Clean up Dockerfile and docker-compose yml files

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#31292]
Clean up dockerfile, getting it “k8s ready”. Refactor docker-compose setup so it doesn’t suck.

## AC
- [ ] Dockerfile is K8s Ready (we may need two Dockerfiles)
- [ ] Development doesn't require rebuilding docker image when files change
- [ ] Dockerfile is compatible with GitHub Actions
- [ ] [Sidekiq workers TSTP cleanly](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26520)

Less is more.

**Comment by ericboehs** [comment]
Over the past two sprints, we've made a lot of progress on this.

Jeremy was able to take our re-worked Docker image and deploy it to EKS.

**Next steps**
- Continue to clean up what [we've developed](https://github.com/department-of-veterans-affairs/vets-api/compare/eb-doc-gin).
- Work with Ops to get certs/pki stuff working in EKS

Currently, we're testing a caching strategy for our bundler gems via an S3 bucket.
