### ISSUE TITLE
ECR setup for Jenkins to build and publish images

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#313]
## Description

We have a need to be pushing and pulling images to and from ECR for multiple projects. We should be able to adapt the IAM role that Jenkins uses pretty easily, but I believe there's some additional Jenkins setup needed before it can natively publish to the registry.

## AC

- [ ] example job that can build a local Docker image and push it to ECR
- [x] Docker registry (ECR) authentication configuration is done via Jenkins bootstrap script / IAM roles
- [x] model for managing repositories in ECR (likely via Terraform)

**Comment by b00klegger** [comment]
Jenkins will need this plugin for ECR auth handling: https://plugins.jenkins.io/amazon-ecr

**Comment by b00klegger** [comment]
>  Docker registry (ECR) authentication configuration is done via Jenkins bootstrap script / IAM roles

Existence of `~/.aws/credentials` file populated with `credstash -> jenkins.aws_access_key_id` credentials will override the instance profile set. Looking at the options in the various plugins now.

As an aside, we currently have a dual strategy for AWS credentials:
- We use the credential store for some
- We use the filesystem `credentials` file for others

Filesystem credentials are for an AWS IAM `jenkins` user which seems to have maxed out their policy attachments (and has somewhat permissive rights also).

**Comment by wyattwalter** [comment]
Doh, that's confusing. We should cleanup the duplicate permissions there.

**Comment by b00klegger** [comment]
Task list:
- [ ] Sort Jenkins instance role vs user permissions
Rebuild permissions around instance profile
- [ ] Retire Jenkins user
- [ ] TF for role management
- [ ] One unified role (both swarm and master)
- [ ] Jenkins bootstrap setup for instance credentials
- [ ] TF setup / management of ECR repos (within namespace)

**Comment by b00klegger** [comment]
Looking into the matter further I have closed an initial PR which tried to recreate all the permissions via the role. The goal was to eventually remove the `jenkins` user altogether and use only an instance role for all permissions.
