### ISSUE TITLE
Prepare for and Transition 10-10CG from direct-to-SF to MuleSoft-to-SF

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#31307]
## High Level User Story (from Caregiver Program)
> As a va.gov user I would like to know when my on-line 10-10CG has been successful so I do not resubmit duplicates.

## Goals
Seamless implementation of Mulesoft by the CARMA team with minimal/no interruption to the VA.gov experience.

## Dependencies
From Caregiver team:
> Per discussion with the va.gov team we will investigate creating the "shell" CCD first and giving them a "success" at that point while we asynchronously create the CCRs/Contacts/Addresses/CCP/etc. and change ownership to alleviate the timeout issues we see.

## Discovery questions
- What do we consider a duplicate 10-10cg submission? 
  - The 10-10cg submission can timeout and the user may attempt a resubmit resulting in dupe applications. 
- How do we come across these duplicate submissions? 
- What volume of duplicate submissions are we seeing? What happens to them?
- What authentication changes do we anticipate with the introduction to Mulesoft?
- What does an exhaustive/adequate regression testing look like?
- Security
  - We're comfortable with `client_id`/`client_secret` (vs. current oauth approach with SalesForce)
  - Data we're passing along to MuleSoft is secure

## Issues to create within this Epic
- Engineering Discovery ticket - @jchilders 
  - Topics:
    - Investigate/Review CARMA Interface Document 
    - Document VA.gov implementation needs (re: switching over, testing)
    - Testing/promotion plan (between environments)
    - Necessary to tech debt to tackle before do any switching e.g. Logging/monitoring
      - Might need to elevate Grafana/Loki work
    - Switch over approach i.e. feature toggle or not, env variable, % percentage increase
  - Acceptance Criteria
    - Document our approach to above topics 
    - Create any eng implementation tickets
- TBD 

Not in scope:
- Engineering Discovery - Investigate separate environments (w/ Platform) (out of scope for this effort)

## Next Steps
- [x] Acknowledge receipt to Caregiver team
- [x] Prioritize with internal team

### Environment Mapping

| vets-api           | mulesoft          | salesforce |
|--------------------|-------------------|------------|
| n/a                | https://dev.vapi.va.gov   | dev        |
| dev-api.va.gov     | https://test.vapi.va.gov  | QA         |
| staging-api.va.gov | https://stage.vapi.va.gov | stage      |
| api.va.gov         | https://vapi.va.gov       | prod       |

[VA.GOV-1010CG.postman_collection.json.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/7557794/VA.GOV-1010CG.postman_collection.json.zip) - Postman collection for testing MuleSoft 10-10CG endpoints. Endpoints are currently static.

**Comment by MickinSahni** [comment]
**2021-10-29 Caregiver team sync**

Mulesoft Planning

o    API Call will create a shell case to see if there are any errors.

o    Using middleware will insulate VA.gov from going into Salesforce. The middleware can also do the heavy-lifting on storing the request.

o    This will be an iterative approach: Build something and keep adding to it.

o    Detecting duplicates would be a major change.

o    Changing the structure of the API calls would not immediately provide a benefit, but would very likely reduce timeouts.

o    Goal is for Mulesoft to be in by the end of Sprint 14.

o    They can build mock services for testing integration while they are still integrating.

o    CARMA likely not to make any API changes until Mulesoft is more in-place.

o    CARMA needs to see Mulesoft's testing dates too.

**Comment by MickinSahni** [comment]
2021-11-12 Caregiver team sync

- [VA.Org Interface 1010CG Definition_vDRAFT_Nov11.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/7529349/VA.Org.Interface.1010CG.Definition_vDRAFT_Nov11.pdf)
-

**Comment by SKasimow** [comment]
Devops ticket to fix staging issues: https://github.com/department-of-veterans-affairs/devops/pull/10588

**Comment by SKasimow** [comment]
Dillo's summary of upload issue in staging: https://dsva.slack.com/archives/CMJ2V70UV/p1642790109026800

**Comment by SKasimow** [comment]
Submission failure in staging slack thread: https://dsva.slack.com/archives/CMJ2V70UV/p1642790129027300
