### ISSUE TITLE
Bug: first search result sometimes lingers after changing search params

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#31308]
## Steps to reproduce:

1. Search for zip code 27606, Community provider / Dentist
2. Change to Emergency care / All
3. Note that the first search result (Lane and Associates) remains in the results list

Screen shot:
<details>
![Find_VA_Locations___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/91641ff2-bbfc-4e6a-b072-d0bf299f040e)
</details>

No errors reported from the API.

This does not happen with "new york" or "washington dc".

**Comment by mmiddaugh** [comment]
can not replicate
