### ISSUE TITLE
multiple live deploys in staging

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3131]
Staging right now is a single lane gateway to prod, which works well when there are no blockers and traffic flows smoothly.   But sometimes we need to have multiple deploys live in staging in order to take advantage of live data sources where review instances are not sufficient (eg, in order to record data for mocking, to interface with new services, etc..).  

In these cases we need to manually fiddle with staging, or halt deploys while we redeploy a branch to staging manually.  When this happens it makes it really difficult for everyone to get their work done -- trending to impossible as we onboard more teams and services.

Recommendation: Make it so we can deploy branches of application under a separate name so that multiple staging tests can occur at the same time without affecting the release flow.

ref: https://dsva.slack.com/archives/C7S6EA0ES/p1572988617372800

**Comment by nathanhruby** [comment]
@annaswims you probably have a way better idea about how this should work (or if it is even a good idea).  I would welcome your thoughts and feedback here.

**Comment by nathanhruby** [comment]
See also this slack thread from @saneshark https://dsva.slack.com/archives/C7S6EA0ES/p1573163762406100

**Comment by ricetj** [comment]
@alexpappasoddball this is something that the BE tools team may want to do. assigning you so you have eyes.

**Comment by johnpaulashenfelter** [comment]
Closing since we now have review instances
