### ISSUE TITLE
Design Feedback - Design intent Claims & Appeals - Higher Level Review v2 Form Refresh

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#31318]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- This is going to be a nice improvement!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change all green buttons to an action link
- Remove the modals for editing phone number and address
  - Use inline like healthcare and education or list and loop (list/loop has some problems)
  - If you want to use a new pattern you will need to go through the experimental process
  - ![Screen Shot 2021-10-12 at 1.53.06 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/76466500-a485-40cf-bc89-0b8712cab874)
- Edit text links should be buttons
- Add space above the “Need help?”
- Add space above “Date of decision”
  - ![Screen Shot 2021-10-12 at 10.29.18 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/727f1b6c-b552-4817-8500-3e35119de62f)
- Would you like to add any more issues for review?
  - If they select yes, after they have added the issue, they should go back to the screen with issues in blue boxes 
  - Make sure the missing issue is added and selected (Eg. left ankle arthritis)
  - When they click next they should get Would you like to add any more issues for review?
  - This should happen until they answer No to that question
- Follow the [content guide for times](https://design.va.gov/content-style-guide/dates-and-numbers) (change 12 to noon)
- Remove the ability to uncheck the issues on the review screen. This should be enabled when a user clicks edit
  - ![Screen Shot 2021-10-12 at 10.43.27 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/0f2845fa-9c0b-4d97-b2dd-5d2d4e28b348)
- Removing the extra “review” of issues before the final review page. There is no need for this

**Should:**
- Remove the wizard completely
  - You could move all the information “claim other than disability compensation” below the “Request a Higher level review
  - ![Screen Shot 2021-10-12 at 10.05.39 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/a609e498-4864-4dc9-a132-da6986056fc1)

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by rtwell** [comment]
Must
• Adding user-generated issues must be a page-by-page interaction (not modals)
• User must be able to edit what they can (be it user- or system-generated issues)

**Comment by vhenry07** [comment]
Hi @rtwell , per meeting yesterday, please provide detailed Design comments here.

**Comment by rtwell** [comment]
my recommendation would be a one-by-one design solution, where users can only fill out one HLR at a time. I know Matt is getting some numbers together that might help with that decision (from where we are now)

**Comment by vhenry07** [comment]
Thanks for the recommendation. In discussions with Matt, determined we'll add this to our backlog for further exploration on the next product iteration.

**Comment by kevinstachura** [comment]
Feedback and has been incorporated per the ticket and ensuing discussions - designs can be found here:

https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6
