### ISSUE TITLE
Access for Adrian Garcia Basmadji

### ISSUE THREAD

**Issue by that-guy-is-it** [department-of-veterans-affairs/va.gov-team#31361]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Adrian A. Garcia Basmadji

### Your Email

adrian.garcia@libertyits.com

### Name of Your Team

Team Pteracuda from Liberty IT Solutions. I am a Software Developer

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDqT2gbXIKXjwIHUq1J127tU4qp3K+f1uHiekt7yXxJ3q5bldcSM9RerXc82faHJDu2Bj0EX69zMADMyzJzZSFn/nuBkPqkXS617lCyzjkZzQH41m9kjnjGsWYYFsV07NeJYj3P6jfOQGABoITd5fkt9V2tn3CV4omyOzJS9b0zkvbG9ZQsGLGeEDEZTahjG1UdgWThXpGMyXu8sw1uveBLBYHPBuZ7vTJkz3ihGg4ENa5s2rtuBW6TjQGOP7cGgll4Z5AnfHGjn71vpRC7GOxA3M51pYzrt+6Zk8EkeGHzzyXm2lwSyCBEyelqF+1BWotII97lt0rUk1mE/9dUintI5nqNTZRm2BByIXkEThNZDPqzCIBnRwJ8ngJyXmYZpGzNJM6ICaZMQmsrrERw56huRgX9caqF1q0Tw5J8NcLH8Ma6gp6D4mWe4XjUbP3sjaxE3niJWfsJJ1mHMS5DWSI89rxWScaBlee7IOdatnLLNRfCRV1lNROyh7luljmyz0= adriangarcia@Adrians-MacBook-Pro.local

**Comment by mleclerc00** [comment]
Hi @that-guy-is-it 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
