### ISSUE TITLE
Midpoint Review [Public Websites, Harassment Reporting Tool (HRT)]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31382]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [ ]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [ ] Schedule meeting with Collaboration Cycle reviewers and VFS team attendees listed in the ticket. 
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [X] Yes* (Constant content support as this feature is content heavy)
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/README.md)
 
- [ ] [Finalized design prototype or mockup](https://preview.uxpin.com/2421e73be8eba75acea37ad3fbdd09bfc147940f#/pages/141512978/comment/sitemap?mode=vhd)
- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/usability/research-plan.md)

 
- [ ] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/usability/conversation-guide.md)

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [UXPin Prototypes](https://preview.uxpin.com/2421e73be8eba75acea37ad3fbdd09bfc147940f#/pages/141512978/comment/sitemap?mode=vhd)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

### Required* 
\*Only required for synchronous meetings.
Requesting a asynchronous review if possible. 

### Team Members

- Cassandra Allen - Designer
- Cindy Merrill - Researcher 

### VFS Attendees

Just building a prototype, FE work with be handed off to Stakeholder team. 

## Scheduling
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [X] Yes
- [ ] No

**[Insert date here]** **[Insert time here]**

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Sounds good @brianalloyd . The review has been scheduled for Tuesday 10/19. You'll receive feedback by EOD. No meeting will take place since this is asynch. Thank you!

**Comment by brianalloyd** [comment]
@shiragoodman this project will be "pausing" as we wait for stakeholder validation.  Think we can cancel this requested Mid-Point based on the new guidance.  Thanks, Brian.

**Comment by FranECross** [comment]
Added to 2/20 Prod Sync with Dave

**Comment by jilladams** [comment]
This was created so long ago, Dave is leaving, no one talks about this tool anymore, and if it ever comes back it'llneed to be modernized adn start the collab cycle from the ground up. I'm closing this, and we can always reopen if I'm wrong.
