### ISSUE TITLE
Audit existing VT messages - Content strategy for existing VT messages

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#31386]
Whole spectrum of texts

**Comment by lindsay-insco** [comment]
Quantify by character count/length in excel - target sites with long messages and assist in cleaning up messages long-term 

Look at criteria - too many links for example, "ridiculousness" 

Focus on high impact first - what stands out most

**Comment by vlivshin** [comment]
Summary of audit: https://docs.google.com/document/d/1bMPHOGgoHchaXbkVq8cGWYJmXidL_NDj-nGr-HEcGno/edit?pli=1

**Comment by vlivshin** [comment]
@lindsay-insco @shanemelliott. I've attached the Message Template Audit Summary: [https://app.zenhub.com/files/133843125/4f79514c-c70d-43cd-8ba7-76ee789d3449/download](https://app.zenhub.com/files/133843125/4f79514c-c70d-43cd-8ba7-76ee789d3449/download)

**Comment by lindsay-insco** [comment]
Final message guideline updates. Update sites of concern to helpdesk

**Comment by lindsay-insco** [comment]
Audit completed
