### ISSUE TITLE
Get Damien DeAntonio access to VA Github

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#31401]

**Comment by codyreinold-usds** [comment]
@joeniquette was able to confirm access here. Should be all set.

**Comment by joeniquette** [comment]
First attempt to add Damien failed due to an unknown constraint. If the github handle has been created under github.ec.va.gov then it cannot be added to any public github orgs such as the one we use for the Department of Veterans Affairs. We ended up needing to use Damiens public github account in order for him to be added successfully.
