### ISSUE TITLE
[FE] Profile: Update alert for successfully disconnecting an app

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31406]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user successfully disconnects an app from their profile.

See also #31407 and #31411

This ticket is for [**Updates to alerts item 5**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#5-successfully-disconnected-an-app-31406) in the supporting documentation.

## Tasks
- [ ] Update the alert that appears when a user successfully disconnects an app from their profile per the copy and specs in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#5-successfully-disconnected-an-app-31406)
- [ ] Test

## Acceptance Criteria
- [ ] The alert that appears when a user successfully disconnects an app from their profile is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#5-successfully-disconnected-an-app-31406)

**Comment by tmitchellgcio** [comment]
This feels like a small downgrade to what currently exists as the current one gives details on what it can access and information on how the app stores information as well as a privacy policy. I just want to be sure this change is fully intended to replace this in it's entirety

![Screen Shot 2021-11-30 at 3.08.15 PM.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/68384101-857b-404b-aa5c-32b89ae6df5f)

**Comment by hdjustice** [comment]
@tmitchellgcio @andaleliz Taylor - Can you include a screenshot of the modal here so we can make sure it hasn't changed since last we reviewed this?  The modal and that tile from your screenshot was duplicative and the suggestion is to remove the tile, however we want to be sure the verbiage hasn't changed.  Thanks!

**Comment by tmitchellgcio** [comment]
I didn't see a modal honestly. I was assuming it was a modal as well, but this is what I saw. I will do some more research on this to see if there is anything.

**Comment by tmitchellgcio** [comment]
https://images.zenhubusercontent.com/133843125/f7698095-b699-4742-81a2-e448a2fa2392/2021_11_30_16_11_15.mp4

**Comment by hdjustice** [comment]
@tmitchellgcio This is great!  Ok, so it does seem there is some redundancy in the popup modal and the tile that shows after the app is disconnected.  So it seems to me that we want to pare down the information to a more simple readout - "We disconnected this app from your VA.gov profile: [app name]. To delete information stored in the app, contact the app's support center."  @andaleliz can you please take a look at Taylor's video and confirm the thought here?

**Comment by tmitchellgcio** [comment]
@hdjustice Do we still want the privacy information bit?

**Comment by hdjustice** [comment]
Good Point @tmitchellgcio  That wasn't in the original screenshot.  Does that take you to the actual Apple site?  
The only concern i can think of is if the URL changes (for whatever reason) and we end up with a dead link. I wonder what the thoughts were behind including it here in the first place..

**Comment by tmitchellgcio** [comment]
That, I believe, gets populated from the app. It's not hardcoded

**Comment by andaleliz** [comment]
Thanks @tmitchellgcio and @hdjustice! This is helpful. Definitely some more work to be done here. Taylor, can you let me know what is hardcoded and confirm what, if any content, is populated from the app or some other service? I don't want to make a suggestion that won't make sense across all apps.  E.g. what happens if you click disconnect on the Test App in your screenshot? 

I think some copy like this could work, but not sure if it applies across all use cases and apps:
>>We disconnected this app from your VA.gov profile: [app name]. Some apps may store information about you that you've already shared To learn how your data is stored and what steps may be available to you, review the [app] privacy policy "

**Comment by andaleliz** [comment]
I reviewed this with Danielle and have some updates, which can be seen in [this mock-up](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/4a894g3).  

Copy should read:

We disconnected [app name] from your VA.gov profile. If you have questions about data the app has already collected, review the app's privacy policy or contact customer support.    

[Review the [app name] privacy policy] (link to privacy policy) 

The [alert documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md) has been updated as well.

**Comment by hdjustice** [comment]
@tmitchellgcio Liz updated the documentation and copy for this one.  Please let us know if there is anything else unclear.  
cc: @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio is this ready to be validated on Staging?  Thx!

**Comment by andaleliz** [comment]
Taylor confirmed via Slack this is ready to validate, but I'm wondering if there are specific users I should use to test with? 

I hesitate to disconnect apps from our test user accounts since  I'm not sure how to add them back. When I try to go through the process of adding a browser based app to a test user account, it leads me through a production flow, not a staging one.

**Comment by Samara-Strauss** [comment]
> Taylor confirmed via Slack this is ready to validate, but I'm wondering if there are specific users I should use to test with?

This is a question for the lighthouse team since they manage the connected apps tool.

**Comment by MarciMcGuireGCIO** [comment]
If I haven't said it today, you guys rock.

**Comment by MarciMcGuireGCIO** [comment]
So far it's crickets on the [connected_apps Slack thread](https://dsva.slack.com/archives/C0136FJV5R9/p1638893019002200) where Liz & Samara requested a staging account that can be used to test disconnecting an app.   I'm going to also ping Joe Tice his team is working on a Test User Dashboard.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - Still haven't seen a reply to Liz's or your posts in #connected-apps; Joe Tice also doesn't have any leads on a user for testing disconnecting/connecting apps.   Do you have any other contacts I could reach out to?  Thx!

**Comment by Samara-Strauss** [comment]
@MarciMcGuireGCIO I don't, actually. I'll see what I can track down.

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by Samara-Strauss** [comment]
I've asked in vfs-all-teams. I'm hoping one of the the almost 1000 people in that channel can help.

**Comment by MarciMcGuireGCIO** [comment]
I also DM'd Cary Otto and TJ Rice

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio cc @Samara-Strauss - tried to test this morning per TJ Rice's instructions, but when I attempt to connect apps to show up in a test user's profile, the OAuth login lands me on a page saying  "VA Tools Not Working".   I posted in the same thread where TJ provided info, and will update when I have new info.

**Comment by MarciMcGuireGCIO** [comment]
Update - user ID provided in Slack by Sophia Tareen does not go through the consent flow to add connected apps.  This is the same issue blocking #31407

**Comment by MarciMcGuireGCIO** [comment]
I was able to successfully test this on staging and it correctly reflects the changes described.

![image](https://user-images.githubusercontent.com/73354907/145855580-9394c019-d785-4ee8-871c-1cfb61755ebf.png)

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz if you have a few min, can you take a look at the screen shot I took above and confirm it meets the AC for this ticket?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio I validated this yesterday, so it should be ready to deploy whenever you are ready.  Thx!
