### ISSUE TITLE
[FE] Profile: Update alert for identify verification

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31403]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears for identity verification.

This ticket is for [**Updates to alerts item 2**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#2-identity-verification-31403) in the supporting documentation.

## Tasks
- [ ] Update the alert that appears for identify verification per the copy and specs below:
- [ ] Test

### Identity verification ([#31403](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31403))

- **Impacted sections:** account security (rest are hidden when this alert shows)

- **What's changing:** alert state

- **Placement:** Under h1

- **Alert (pattern, state):** Full width alert, [sign-in or tool prompt](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-or-tool-prompt)

- **Include heading:** Yes

- **Copy:** 
9/12/22 - See [mock-up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/DPDQDwq) for up-to-date content and lay-out.

~[heading] **Verify your identity to access your complete profile**~

 ~[body] First, we need to make sure you’re you—and not someone pretending to be you. Then, we can give~
~you access to your personal and health information. We do this to help keep your information safe from fraud and~
~identity theft.~
  
  > ~**This one-time process takes about 5 to 10 minutes**.~
  
~[action link] Verify your identity~

## Acceptance Criteria
- [ ] The alert that appears for identify verification is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#2-identity-verification-31403)

**Comment by adamwhitlock1** [comment]
I can take this ticket. The only thing that I was unsure about was that the original documentation says:

> Alert (patter, state): Full width alert, **continue state**

The "continue state" is a link that takes me to storybook but there is no corresponding component story for that. I think I can get it figured out, but was just wondering if anyone knew what that link was supposed to show me.

**Comment by andaleliz** [comment]
Hi @adamwhitlock1 thanks for taking a look at this. I think they have renamed that to the [Sign in or Tool prompt](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-or-tool-prompt#sign-in-or-tool-prompt).  However, I am 99% sure that alert shows a deprecated button and now the preference is an action link.

[Here's the mock-up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/DPDQDwq) I made, but now that guidance has changed since this ticket was opened, I want to confirm the mock-up is accurate. [I posted a question in Slack](https://dsva.slack.com/archives/C0NGDDXME/p1656535607555349?thread_ts=1655474477.229769&cid=C0NGDDXME) and will follow up with you here when I learn more.

**Comment by andaleliz** [comment]
@adamwhitlock1 and @SKasimow - this still needs to be worked on and I moved the specs to the issue description for clarity

**Comment by andaleliz** [comment]
@SKasimow and @adamwhitlock1 coming back around to this since it came up in Slack yesterday. I have confirmed that the mock-up is correct and we should be using the action link the alert.

**Comment by SKasimow** [comment]
@andaleliz - I'm hoping to schedule this for Sprint 83 and wanted to confirm that we should follow your mock-up here: [mock-up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/DPDQDwq) and **not** the text that is currently in the ticket itself.

**Comment by andaleliz** [comment]
Yes, that's correct @SKasimow

**Comment by adamwhitlock1** [comment]
The update to the verify identity alert is live in staging

![Screen Shot 2022-10-17 at 11.41.16 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/81d57bee-1f3e-4003-ac5d-abf0daf2ce25)

I validated this by just setting up a regular account with one of my personal emails and bv default was at LOA1 and could see the alert.

**Comment by adamwhitlock1** [comment]
@SKasimow you can validate this as well now if you would like.

**Comment by SKasimow** [comment]
@adamwhitlock1 - I also have an LOA1 account and validated that I am seeing same message you posted above :)
