### ISSUE TITLE
[FE] Profile: Update alert for failure to disconnect an app

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31407]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user is attempting to disconnect an app from their profile but fails to do so. 

See also #31406 and #31411

This ticket is for [**Updates to alerts item 6**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#6-failure-to-disconnect-an-app-31407) in the supporting documentation.

## Tasks
- [ ] Update the alert that appears when a user is attempting to disconnect an app from their profile but fails to do so per the copy and specs in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#6-failure-to-disconnect-an-app-31407)
- [ ] Test

## Acceptance Criteria
- [ ] The alert that appears when a user is attempting to disconnect an app from their profile but fails to do so is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#6-failure-to-disconnect-an-app-31407)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel can handle making this update

**Comment by andaleliz** [comment]
I reviewed this with Danielle and have some updates, which can be see in [this mock-up](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/4a894g3).  

Copy should read:

We disconnected [app name] from your VA.gov profile. If you have questions about data the app has already collected, review the app's privacy policy or contact customer support.    

[Review the [app name] privacy policy] (link to privacy policy) 

The [alert documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md) has been updated as well.

**Comment by tmitchellgcio** [comment]
@andaleliz That should be for this ticket right? https://github.com/department-of-veterans-affairs/va.gov-team/issues/31406 

This ticket is for failure to disconnect

**Comment by andaleliz** [comment]
Ugh, yes thank you @tmitchellgcio I had too many tabs open. I'll copy that comment over there and delete it from this thread.

**Comment by tmitchellgcio** [comment]
Ready for validation @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @tmitchellgcio.  I'll take a look now, and also will also Liz to review when she's available.

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio do you happen to have some documentation on how to test this?  I logged into Profile and disconnected my wifi before attempting to disconnect the app, but I didn't see the update alert.  The warning that shows up when you first click Disconnect just reloaded again, as if nothing happened.   Thanks!

**Comment by tmitchellgcio** [comment]
So I had a hard time triggering this. I wrote a test for it which for some reason I missed adding into the commit. It seems to only trigger when the server gives back an error in the response after a bad status. If you just turn off the wifi it won't trigger. I do wonder if we should be showing this on just a server error status even if it doesn't have a error response

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio given my unfamiliarity with this, I'm going to defer to @andaleliz when she returns Monday since she did the research on these messages.

**Comment by tmitchellgcio** [comment]
![Screenshot 2021-12-03 113549.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/bf5a3685-d73a-4dca-a588-b83ba42eb792)

**Comment by tmitchellgcio** [comment]
That's what it currently looks like. I think we should talk about it triggering if it gets any kind of error from the server so we can definitely put this on hold until Monday

**Comment by MarciMcGuireGCIO** [comment]
Noting for standup that this is awaiting validation; Liz was tied up today on her own tickets.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @andaleliz !

**Comment by tmitchellgcio** [comment]
@andaleliz Well since you say it should display anytime we can't disconnect the app then I will make those changes and it will be way easier to validate as you can just open dev tools and set it to offline to test it. I will put this back in progress and make those changes after my current task

**Comment by andaleliz** [comment]
@tmitchellgcio isn't there already logic in place for when this error message should show? We shouldn't be changing the logic, just the appearance of the alert.

**Comment by MarciMcGuireGCIO** [comment]
Making a note that we may encounter the same issue trying to validate this as we are hitting trying to validate successfully disconnecting. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/31406#issuecomment-988326206

**Comment by MarciMcGuireGCIO** [comment]
Info on testing connected apps: https://dsva.slack.com/archives/C0136FJV5R9/p1638983640013300

**Comment by tmitchellgcio** [comment]
@andaleliz sorry for the late reply, yesterday was busy. The logic currently is only when the server gives a specific response back, however if it can't reach the service because it is offline then it will do what @MarciMcGuireGCIO stated and do nothing. No alert, nothing else. If this is what it should do then I will leave it alone, but I would believe this might be a bug and would need a new ticket to adjust.

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio I think for now we should promote this change, then create a new ticket to update the logic for other secnarios.

**Comment by andaleliz** [comment]
I agree with @MarciMcGuireGCIO's last comment. In other parts of profile, we show an error message when the service is offline and someone tries to make an edit (e.g. in Contact info). We should be consistent with error messages across all parts of profile.

**Comment by tmitchellgcio** [comment]
I agree. I have a new PR for this. 
![Screenshot 2021-12-09 113828.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/c8cab16e-fef7-409f-9328-f35d98694a56)

![Screenshot 2021-12-09 113756.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/2503ef14-51df-4462-a5c2-aedadd270f6b)

**Comment by MarciMcGuireGCIO** [comment]
Awesome; thanks @tmitchellgcio !

**Comment by MarciMcGuireGCIO** [comment]
Update - user ID provided in Slack by Sophia Tareen does not go through the consent flow to add connected apps.  This is the same issue blocking #31406

**Comment by MarciMcGuireGCIO** [comment]
This is ready to go based on Taylor's screen shot.  We can't reproduce on Staging by taking it offline due to the logic used to display the error.  I'll create a new ticket for displaying the error when it's offline.
