### ISSUE TITLE
[FE] Profile: Update alert for failure to update contact info in profile

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31405]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user is attempting to make updates to their contact info in profile but fails to do so.

This ticket is for [**Updates to alerts item 4**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#4-failure-to-update-contact-information-in-profile-31405) in the supporting documentation.

## Tasks
- [ ] Update the alert that appears when a user is attempting to make updates to their contact info in profile but fails to do so per the copy and specs in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#4-failure-to-update-contact-information-in-profile-31405)
- [ ] Test

## Acceptance Criteria
- [ ] The alert that appears when a user is attempting to make updates to their contact info in profile but fails to do so is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#4-failure-to-update-contact-information-in-profile-31405)

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This is now ready for review, however, it can't or shouldn't be seen. 
We have form validation in place to prevent this error from being seen. 

Here picture in my local env where I can by pass the form validation to see the error returned from the API.

![Screen Shot 2021-12-02 at 10 34 20 AM](https://user-images.githubusercontent.com/26075258/145051203-37ed8144-71e4-482b-9353-618e369acff3.png)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel, @andaleliz - I took a screen shot from Prod to compare to Staging, but I don't see any difference (I tested by logging into my ID.me account, disconnecting Wi-Fi and then attempting to update)
![image](https://user-images.githubusercontent.com/73354907/145055771-2e84b5a3-e944-42f4-849e-3cd7594af7b8.png)

**Comment by andaleliz** [comment]
Everything I see on staging aligns with what came out of the alert audit, looks good to me! We had a couple of flavors of this error message previously:
![image](https://user-images.githubusercontent.com/55992116/145061435-78f2532a-2f82-47fb-8709-6db3b5389abf.png)

This looks good to go.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel you can go ahead and prep this to deploy to Prod.  Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel not sure if you saw that this is approved and ready to go.  Thank you!

**Comment by adamwhitlock1** [comment]
> @adamwhitlock1 - I don't know if the feature flag was removed from this so it would be visible in Prod. If not, would you be able to do that? Thanks!!!

Zach mentioned that it is not not behind a feature flag, and so it should be visible on Prod

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 thank you!  Yep, I was able to invoke on Prod by logging into my own ID.me account, setting developer tools offline and attempting to update my address.  
![image](https://user-images.githubusercontent.com/73354907/145860739-696096a0-2fd5-4cdd-aebb-3a4cf551f854.png)
