### ISSUE TITLE
[FE] Profile: Update alert confirming a user wants to disconnect app

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31411]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the confirmation alert that appears when a user wants to disconnect an app from their profile.

See also #31406 and #31407 

This ticket is for [**Updates to alerts item 9**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#9-confirmation-user-wants-to-disconnect-app-31411) in the supporting documentation.

## Tasks
- [x] Update the confirmation alert that appears when a user wants to disconnect an app from their profile per the copy and specs below.
- [x] Test

9. Confirmation user wants to disconnect app
- **Impacted sections:** connected apps

- **What's changing**: copy, button order

- **Placement:** In modal component

- **Alert (pattern, state):** Full width, warning state

- **Include heading:** Yes

- **Button usage:**

  - First button contains the confirming action and has the primary button style
  - Second button (if applicable) contains the cancel action and has the secondary button style

- **Copy:**

  >  [heading] Are you sure?
  >
  > [body] After you disconnect this app, the app won’t have access to new information from your VA.gov profile. This may affect how useful the app is to you.
  >
  > Some apps might store information you’ve already shared after you disconnect. If you want your stored information deleted from the app, contact the app’s customer support. 
  >
  > [button] Disconnect
  >
  > [button] Cancel

## Acceptance Criteria
- [ ] The confirmation alert that appears when a user wants to disconnect an app from their profile is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#9-confirmation-user-wants-to-disconnect-app-31411)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel can handle making this update

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO / @hdjustice this can be considered a sibling update of #31407; this addresses the modal that displays prior to the user seeing the alert that 31407 addresses.  Looks like Zach has been unassigned, maybe @tmitchellgcio can work on this too.

**Comment by MarciMcGuireGCIO** [comment]
Thanks @andaleliz.  Yes, I unassigned this from @zacharymorel because his last day is next Fri and he's got a full plate with the Personal Info update.   If @tmitchellgcio  has capacity after working with Erik to make the Login.gov changes, and there isn't anything higher priority, then that might be a good use of his time.  cc @hdjustice

**Comment by andaleliz** [comment]
@adamwhitlock1 and @SKasimow this still needs to be done. I'm moving the guidance to this ticket from the doc that was previously linked.

**Comment by tmitchellgcio** [comment]
@MarciMcGuire this is ready for validation

**Comment by SKasimow** [comment]
I'll take a look as @MarciMcGuireGCIO is no longer on Profile team

**Comment by SKasimow** [comment]
@tmitchellgcio - I tested in staging and believe I am seeing the old message:

![Screen Shot 2022-08-11 at 12 22 51 PM](https://user-images.githubusercontent.com/74627978/184182322-6817b788-6b79-49eb-96ed-4fc2cccb66f1.png)
:

**Comment by tmitchellgcio** [comment]
@SKasimow That likely wasn't fully deployed to staging by that time. Sorry didn't expect anyone to validate that quickly. It should be up there now

**Comment by adamwhitlock1** [comment]
> @SKasimow That likely wasn't fully deployed to staging by that time. Sorry didn't expect anyone to validate that quickly. It should be up there now

Seems like CI / staging deployment might be lagging, doesnt appear to have made it into staging yet...

![Screen Shot 2022-08-11 at 12.22.16 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/46233480-0028-4298-9fbc-e4e64a6478da)

**Comment by tmitchellgcio** [comment]
I see it as deployed on my end now

**Comment by andaleliz** [comment]
FYI this is another one where the buttons don't match the rest of VA.gov and need to be updated (see description)

**Comment by SKasimow** [comment]
@andaleliz - this is what I see now in staging and seems to match the mock; can you confirm:

![Screen Shot 2022-08-15 at 3 07 15 PM](https://user-images.githubusercontent.com/74627978/184700801-f0894007-83e6-4a4a-b15c-ada4fd7857fb.png)

**Comment by andaleliz** [comment]
Yep! That's the correct button order.

**Comment by SKasimow** [comment]
@andaleliz - thanks. Think it is helpful to have a link in the ticket or comments (preferably ticket) to the specific mock; thinks why this one is correct and the other one you re-opened wasn't (or if it was there I totally missed it).
