### ISSUE TITLE
Access for Christopher Bratti

### ISSUE THREAD

**Issue by ChrisBratti-VA** [department-of-veterans-affairs/va.gov-team#31423]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Christopher Bratti

### Your Email

christopher.bratti@libertyits.com

### Name of Your Team

Axolotl

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrzZaWdx363ZBmQcj79qFyVldBa74ylWWgilVNwKOSyOgAcjxy04AVAm1JttsWvk8I9L3B13MnN2nRtQEXtDO+fLOqvnLSDJhYmXaFbvoSANl8Ouefo8JBx7xtGlcSbCqsEr+DXZmmptU7gX3/M5LOCcLU6Yw4Du+rDsLh+Be/IeBGc1o2BWXN9mrW2RBG3L49k6bGgtQuR9YmC5u9DnKMzJhvOC6d0ILa4bdgL1qTZnn/aaVimwS+eXTLwF1wn+fdIXIlrdIHjrntpkIUDj42zr6lETX8K/u1vQ5Jz5gzW0Ye9CMXBqHbxWwc3ICztSAZbmJIdtXiFQhGVDTNK67PP3oblaMhkMiZqfRep7Fvo8O8QVxtsqR4n5qOV0/HpaOInoUK7W/Ed2HJHS5uPZj3xnLrSOOPY8JWJEfDr0+xI8Dd8uszTLG0ZINwFV9sIVOF6/zGCEV/PP2DzyLch/FmZZN7Ifzn6949eoCcZ/6BbuDQPURY2+EEZvNrR0qdrek= cb_va@DESKTOP-296HFKA

### Desired AWS Services

I need access to Kibana for CCE API metrics

**Comment by mchelen-gov** [comment]
@mleclerc00 EQIP transmission date confirmed, however I'm not sure what "Kibana for CCE API metrics" means?

**Comment by mleclerc00** [comment]
Hi @ChrisBratti-VA 

Are you able to access Kibana with socks alone or is there more action that needs to be taken for AWS?

**Comment by mleclerc00** [comment]
closing this issue, please reopen if needed
