### ISSUE TITLE
Request IA support - SCO Migration Redirects

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3145]
Redirect legacy pages on benefits.va.gov to new School Resources location 

NEW URL
www.va.gov/school-administrators

PAGES TO REDIRECT
School Resources | https://www.benefits.va.gov/gibill/school_resources.asp
School Training Resources | https://www.benefits.va.gov/gibill/school_training_resources.asp
School Certifying Officials | https://www.benefits.va.gov/gibill/resources/education_resources/school_certifying_officials/sco_info.asp

**Comment by mnorthuis** [comment]
@amyknox Process for handling this redirect is in place.  Can you confirm the launch date of the new page and when you would like the redirect in place?  Thank you!

**Comment by amyknox** [comment]
We're targeting 11/21 or 11/22. 

How involved is the EDU team in this effort?  Specifically wondering how the info about the redirects is being communicated to the folks we're working with there.

**Comment by mnorthuis** [comment]
@amyknox You will need to communicate with the stakeholders regarding the redirects and let us know when you need them implemented - as in on the same day as the page launches or can the redirect follow after.

**Comment by amyknox** [comment]
[SCO-NavigationUpdates-Redirects-20191112.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3838474/SCO-NavigationUpdates-Redirects-20191112.docx)
Email sent to client re: navigation updates and redirect process.  Sharing here for posterity

**Comment by mnorthuis** [comment]
@Karak888 This redirect request has been vetted and can be assigned to your front-end team.  The redirect should be handled via a client-side redirect. 

Please note launch date for new content page is planned for 11/21 or 11/22.  You will need to coordinate with the BAH team on the implementation of this redirect.

**Comment by amyknox** [comment]
@Karak888 - our client wants to delay the redirect for a couple days so we'll launch the new page then implement the redirect.  Will let you know when we have a target for the redirects to go live.

**Comment by amyknox** [comment]
@Karak888 - Could you give me an idea of how much time will be needed for your team to turn the redirect request around once we have the target date?

**Comment by Karak888** [comment]
@amyknox I am sorry not sure what this was about.  @jenniferlee-dsva can you please let me know about this when you have a moment.  Thanks

**Comment by amyknox** [comment]
@Karak888 - we're launching a new page on va.gov and need to redirect 3 links from benefits.va.gov to the new va.gov page.  My understanding is that you're on the Public Websites team and will be handling - managing? - the redirect process.  I'd like to confirm the plan, date, etc. with you to make sure the launch & redirect plans are aligned.

**Comment by Karak888** [comment]
@ncksllvn @jenniferlee-dsva - Are we managing all redirects outside of legacy and rewrites?  I wasn't aware that we were handling all of these, but please correct me if I am wrong so as not to hold up @amyknox any further.  Thanks

**Comment by ncksllvn** [comment]
Good question...I was under that impression because it seems to fall into the realm of "public websites" and I don't know what other team the work would land with. Then again, if another team has been handling this work up to this point, it seems like it should stay with them. I have to defer to @jenniferlee-dsva 🙂

**Comment by ncksllvn** [comment]
@Karak888 these are all client-side redirects (the only option we have, due to the domain being benefits.va.gov instead of www), so it'll be our team implementing them

**Comment by amyknox** [comment]
@ncksllvn , @jenniferlee-dsva  & @Karak888 -  Can you give me some idea of how you approach the redirect process?  I'd like to confirm the plan, date, etc. with you to make sure the launch & redirect plans are aligned.

**Comment by ncksllvn** [comment]
Hey @amyknox, it's pretty simple. In our front-end project, we have a static file in the form of [JSON](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/proxy-rewrite/redirects/disabilityRedirects.json), we're we'll just add the redirect source and destination. This redirect will be deployed during our daily deployments. If there's front-end work that your team is planning to merge for your launch day, it would make sense for the redirected to be included in that merge.

**Comment by amyknox** [comment]
Thanks @ncksllvn. If I'm understanding the process correctly, we give you the redirects & targets (listed in the initial story description above) and tell you when we want them implemented.  Sounds like you need about a day to implement the redirects.

**Comment by ncksllvn** [comment]
It'll only take a sec - I can open a PR to implement the redirects, assign your team for review, and then your team members can merge the work when ready?

**Comment by ncksllvn** [comment]
Or I can open the PR, leave it until [data of launch], then I'll wait til that day to merge unless you tell us to hold off.

**Comment by jenniferlee-dsva** [comment]
@Karak888 please work with Nick  to size this, and put it in the website team's backlog. 

•	Note: Amy has a request-by date; if our sprint is full and we cannot meet her request-by date for implementation, please let her know what sprint we’ll add it. 
@amyknox - is your new page's launch blocked if the redirect is implemented later than your launch date? 
3/ RE SME and stakeholder communication – Amy please let your stakeholders know, since we only manage comms for tier 1 benefit parity/legacy content work..

4/ @mnorthuis we won't capture this redirect info in the log Selina is keeping for benefit hub work. Just FYSA, in case you may want to for platform IA documentation.

**Comment by ncksllvn** [comment]
I created this ticket to track our implementation - https://github.com/department-of-veterans-affairs/va.gov-team/issues/3611.

I marked it as due by 11/22, meaning that the redirects will be put in place on that date at approximately 3 PM ET. However, this isn't difficult, so if 11/21 is preferred, we can do that. Either way, it's on our team's radar - please let us know!

**Comment by amyknox** [comment]
@ncksllvn Great to know the turn around is so quick!  I'll confirm the date with our client on the EDU side.  Please don't redirect until we have a final answer from them. 

@jenniferlee-dsva -We are not blocked if the redirect is implemented later than launch date.

**Comment by ncksllvn** [comment]
Gotcha - I marked the ticket as on-hold, so we are awaiting your confirmation for the date!

**Comment by Karak888** [comment]
Thanks @ncksllvn but for future reference @amyknox we will require more time in advance (you got lucky that a.) you had @ncksllvn and b.) you got this in as we were defining our redirecting process).  
thanks for your patience.

**Comment by ncksllvn** [comment]
Haha, we also just had sprint planning today, so good timing 😄

**Comment by amyknox** [comment]
Folks - our client in EDU mentioned that they "have people in Philly" who can help with the redirects on their side.  Curious if you've worked with Philip Spillaine (?) in Philly?  Maybe he's on your team and we're duplicating efforts. 

In the event he's not on your team, is there an issue with him handling the redirects for the EDU pages?  If yes, could someone on this thread be available for a call tomorrow morning to discuss?

**Comment by ncksllvn** [comment]
@amyknox 😮Hm I haven't worked with Philip, but that makes me think that he can implement a server-side redirect from benefits.va.gov to www.va.gov. Is that correct? If so, that would be super useful for us on some related work.

**Comment by ncksllvn** [comment]
I don't see an issue with that at all, sounds very promising. But if it is the case that Philip can implement a server-side redirect on benefits.va.gov, I would for our team to get in touch with him for some related work.

**Comment by amyknox** [comment]
@ncksllvn - Phil in Philly can do *client* side redirects.  That was the solution for our page all along. At this point, I'm not sure who has right of way WRT this redirect process.  The EDU team is happy to handle it but I've been under the impression DSVA had to.

**Comment by ncksllvn** [comment]
If Phil was able to do a server-side redirect, then I would be all-in and have our team w/DSVA get in touch with him. But since it's also client-side, and we already maintain a list of client-side redirects for benefits.va.gov, it might be better to do it on our side

**Comment by amyknox** [comment]
@ncksllvn - sounds like it will be better for your team to handle it.  Just chatted with Kevin Hoffman & he's on board with this plan as well. We have a call with the client at 3pm and will brief them then.  

LATE BREAKING UPDATE...
We need to update a link on the va.gov/education page to direct to the new page.  

In the Not a veteran? sidebar widget, the link text "school administrators" should be updated to direct to http://www.va.gov/school-administrators/

**Comment by ncksllvn** [comment]
> LATE BREAKING UPDATE...
We need to update a link on the va.gov/education page to direct to the new page.

> In the Not a veteran? sidebar widget, the link text "school administrators" should be updated to direct to http://www.va.gov/school-administrators/

Hm, so this is a Drupal task, not a redirect. Does this need to go tomorrow as well? As in, is it a launch-stopper?

**Comment by ncksllvn** [comment]
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/5dd30cf7-b617-4a1e-8d13-c742445c3981)

The good news is that the link points to https://www.benefits.va.gov/gibill/school_resources.asp, which we'll be redirecting anyway, so if the link isn't updated the user will just be redirected.

**Comment by ncksllvn** [comment]
@amyknox Can you confirm that you want the redirects in place this afternoon? I'm ready to merge the work to do so.

**Comment by amyknox** [comment]
@ncksllvn - YES, redirects please!

I am _just_ seeing the note you made about the Not a Veteran / School Administrators link.  Good point about it not being a redirect... We do need it updated though.  Is that something your team handles?

**Comment by ncksllvn** [comment]
@amyknox Merged! They'll go live with the rest of our FE code, at 3 PM ET.

Not sure about that link... @jenniferlee-dsva what do you think?

**Comment by ncksllvn** [comment]
These have been implemented! @Karak888

**Comment by Karak888** [comment]
thank you @ncksllvn ! @amyknox can you verify that everything is working as expected?  Thanks

**Comment by amyknox** [comment]
@Karak888 - links are redirecting as expected.  Thank you!
