### ISSUE TITLE
Get user feedback on the Call Center MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3146]
## User Story or Problem Statement
How might we determine the best format for reporting current Call Center data?

## Goal
Test the first iteration of the Call Center MVP with real users.

## Objectives or Key Results this is meant to further
- Get better quality data for tracking VFS outcomes

## Acceptance Criteria
- [ ] Work with Amy to organize feedback mechanism 
- [ ] Release the Call Center MVP on #VFS-analytics on Slack
- [ ] Announce the release in ToT & present it on VSP demo day
- [ ] Document user sentiment and feedback for iteration

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@amycesal sent @clantosswett ideas for survey questions 11/19/19.

**Comment by joanneesteban** [comment]
@amycesal can you document the suggestions on this issue?

**Comment by clantosswett** [comment]
Did you find this report helpful?
◯ Yes
◯ Somewhat
◯ No

What are you going to do with this information?
[open ended box]

Is there feedback you would like to provide to improve this report? 
[open ended box]

Thank you for your feedback, if you want to chat directly please talk to Chante.
