### ISSUE TITLE
Support Request - Claim Status Tool

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#31461]
## Issue Description
Veterans unable to see claim status

---
## Tasks
- [ ] Reference issues outlined in this [slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1634230806363900).

Determine the following:

- Are there certain claims that are not viewable online?
- Are there any work arounds for vets who cannot see their claims?
- Are there any questions that need to be asked that would be helpful for your team to investigate on the backend? 

## Acceptance Criteria
- [ ] Response to contact center
---

**Comment by michelpmcdonald** [comment]
I think we have answered the original questions in the above comments, closing this out since I don't think it is tied to a specific users's claim
