### ISSUE TITLE
[FE] Discuss current app structure to combine the apps into one application

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31475]
### Goal
- Figure out approach and tasking for combination 

### Requirements to Consider
- maintainability 
- reusablilty 
- testability 

## Tasks
- How does we combine the apps into 1 app

## Time Box
- A mob programming session

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mdewey** [comment]
Created tickets of remaining work. Closing this spike.
