### ISSUE TITLE
Render alerts based on status codes

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#31472]
## Technical Task
After BE completes the documentation of all the possible error codes, we need to make a hierarchy of default alerts with more specific alerts for custom error codes. In previous products I have setup default alerts for 4XX (users end) alerts and another for 5XX (BE end) alerts then making custom alerts for more specific use cases down the line.

![MCP Desktop - UXPin Preview 2021-10-14 14-36-46.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/9b73b5de-2898-47ad-bdd0-c1ea3e80052a)

## Expected Behavior
We have default catch all alerts for 5XX and 4XX with more specific alerts for custom error messages

## Acceptance Criteria
- [ ] We have catch all alert for 5XX
- [ ] We have catch all alert for 4XX
- [ ] We have alerts for more specific custom errors

### Design Reference
https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/142712286/simulate/sitemap?mode=i

**Comment by ScottyRJames** [comment]
From discovery task (#31468)

> 403 - Not enrolled in VA Healthcare
> 5xx - 404 error screen
> 400 - VBS endpoint is down
> 
> Don't believe we will need custom error messages based on my findings.
>
> Finding whether a veteran is deceased has found to come from many different services and possibly not even able to login if it comes from MPI.

**Comment by ScottyRJames** [comment]
If user has deceased notification the following status code will be returned 

Response: `{ status: 200, body: { status: 403, message: 'Deceased' } }`

**Comment by denisecoveyduc** [comment]
This will roll over into Sprint 63 due to higher priority MCP fixes.

**Comment by craigwheeler** [comment]
It has been determined that the authorization for deceased veterans will be revoked if a date of death has been recorded so there is no longer a need to handle this use case on MCP so the alert will be removed

https://dsva.slack.com/archives/CSFV4QTKN/p1629234493082000
https://dsva.slack.com/archives/CBU0KDSB1/p1639506216012600
