### ISSUE TITLE
[Design] Mock up of Decision Review entry points flow

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3148]
## User Story or Problem Statement
As a designer, I need to create visual representation of the Decision Review entry point flow so I can test the proposed solution during Veteran sessions

## Goal
_What outcome(s) do we want to see?_
We want to get a visualization of how the user will navigate to the Decision Review 'vertical' of the website (a section of content related to Decision Reviews and contains all pages for decision review lanes).

## Objectives or Key Results this is meant to further
- _This will allow the veteran a clearer and simpler means of navigating to the Decision Review section of the website with the intent to funnel them to the proper content, assisting them in understanding which Decision Review lane is appropriate for their needs._

## Acceptance Criteria
- [ ] Flow diagram that shows the points of entry that a user will navigate to the decision reviews section of the website (va.gov/decision-reviews)

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Closing due to conversation with public websites/IA team in 2019.
