### ISSUE TITLE
[DESIGN] Meet with Crisis Center for pre check-in flow

### ISSUE THREAD

**Issue by niradatta1** [department-of-veterans-affairs/va.gov-team#31486]
The UX team has questions about  how to address veterans experiencing a mental health crisis as part of the pre check-in user flow. 

- [ ] Schedule a call with the Crisis Center to share the pre check-in flow and discuss how to consider the needs of a veteran experiencing a mental health crisis (if at all)

- [ ] Decide if we need to modify the pre check-in user flow based on the conversation

### Acceptance Criteria
Discussion with Crisis Center completed and next steps/actions captured and shared via check-in slack channel.

**Comment by julieadair1** [comment]
This ticket is no longer needed.
