### ISSUE TITLE
[BE] Update Readme file

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31505]
## Description
We need to update the Readme file. 

## Value
1. Provides updated diagrams(architecture/sequence) and setup guides for any developer working on the BE or FE.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by dillo** [comment]
Merged into master. Closing.
