### ISSUE TITLE
[BE] Add swagger documentation

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31503]
## Description
We need to add Swagger documentation to _______ @dillo - where does this documentation need to live?

## Value
1. Provides service and routes documentation that informs developers on the current team on how to integrate with the Check-in module.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by randomsync** [comment]
Duplicate and can be closed, swagger documentation was implemented already.
