### ISSUE TITLE
Words to generalize content on Medical Records page from Facilities team

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31509]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?

- We are hardening the top task VAMC pages. In order to centralize much of the content, we need to remove the specific facility name from the content, which will require some wordsmithing. 
- This issue is focused on the changes needed for the [Medical records office page](https://www.va.gov/pittsburgh-health-care/medical-records-office/).  
- For example, instead of "Get copies of your VA medical records online, by mail or fax, or in person at _our VA Pittsburgh health care_ Release of Information office."  should it be something like "Get copies of your VA medical records online, by mail or fax, or in person at the Release of Information office _at your local VA facility_"? 

## Areas of content needing input: 

1. Get copies of your VA medical records online, by mail or fax, or in person at _our VA Pittsburgh health care_ Release of Information office. (For example, should it be something like 
2. We can help you get copies of your VA medical records. We can also help you update your records. Call or come to the Release of Information office at _our University Drive or Heinz campus_.

A screenshot of the page with the areas called out is available below for information on the context of the surrounding content.

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*
<details>
<summary> Screenshot </summary>

![screencapture-va-gov-pittsburgh-health-care-medical-records-office-2021-10-15-09_00_22](https://user-images.githubusercontent.com/55411834/137509588-83b0549b-c309-4daf-a305-bccca17b8252.png)
</details>

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: _as soon as you are able_

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Facilities
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Michelle Middaugh

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by DanielleThierryUSDSVA** [comment]
@mmiddaugh Here's what I'm thinking. But I want to confirm that these pages are at the system level and there will always be more than 1 location, correct?

1. Get copies of your VA medical records online, by mail or fax, or in person at one of our release of information offices.
2. Call or visit one of our release of information offices. We can help you get copies of your VA medical records. We can also help you update your records. 

Note that I think the form link is broken. It should go to: https://www.va.gov/find-forms/about-form-10-5345a/

**Comment by mmiddaugh** [comment]
Thank you @DanielleThierryUSDSVA - and for the heads up on the form link - I'll create a separate issue to have that addressed
