### ISSUE TITLE
[FE] Update messaging of Marital status question and move to the Household information section

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#31507]
## User Story

As a health care applicant, I want to be able to provide accurate marital status information and understand how it impacts my 10-10EZ application, in order to receive appropriate VA Health Care.

## Expected Behavior

The purpose of this story is to edit the messaging of the marital status question and move it to the Household Information section. The dropdown selection list doesn't change.

UX Design Ticket: ##31134
[Design and content PDF](https://app.zenhub.com/files/133843125/5980fb0e-958a-4145-952b-4014f6be5187/download)

## Acceptance Criteria

- [ ] Content and design updated on the 10-10EZ
- [ ] Question moved to the first question of the Household information section (immediately before the yes/no Financial disclosure question)
- [ ] Design sign-off in socks and Staging
- [ ] Value submitted to the vets api backend
- [ ] Successfully tested end to end

**Comment by markfallows** [comment]
Work has already been completed; closing as already done.
