### ISSUE TITLE
Words to generalize content on Billing and Insurance page from Facilities team

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31513]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?

- We are hardening the top task VAMC pages. In order to centralize much of the content, we need to remove the specific facility name from the content, which will require some wordsmithing. 
- This issue is focused on the changes needed for the [Billing and Insurance page](https://www.va.gov/pittsburgh-health-care/billing-and-insurance/).  
- For example, instead of "You can pay your _VA Pittsburgh_ health care bill online, by phone, mail, or in person." should it be something like "You can pay your _VA_ health care bill online, by phone, mail, or in person."

## Areas of content needing input: 

1. You can pay your _VA Pittsburgh health care_ bill online, by phone, mail, or in person.
2. If you have questions about the copay balance on your _VA Pittsburgh health care bill_, call us toll free at 800-983-0932. We're here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.
3. To pay your copay bill in person, visit the agent cashier's office _at our Heinz or University Drive campus._

## Supporting Artifacts
*Please provide supporting artifacts as available.*
<details>
<summary> Screenshot </summary>

![screencapture-va-gov-pittsburgh-health-care-billing-and-insurance-2021-10-15-09_24_12](https://user-images.githubusercontent.com/55411834/137513093-efe11d73-9d2e-4427-b16a-72a9e3359a11.png)

</details>

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: _as soon as you are able_

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Facilities
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Michelle Middaugh

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mmiddaugh. Here's content for the 3 requested areas:

1. You can pay your VA copay bill online, by phone or mail, or in person.
2. If you have questions about the copay balance on your bill, call us at 800-983-0932. We're here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.
3. To pay your bill in person, visit the agent cashier's office at your nearest VA medical center.
