### ISSUE TITLE
[MCP] Outstanding wizard terminals 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#31516]
## Issue Description
As part of the MCP release, we want to update the FSR's wizard to guide Veterans towards the next step most applicable to their situation. We've previously outlined the terminals we expect to show in the updated wizard, however a couple terminals remain unclear in validity and accuracy of content ([view to the wizard content here](https://governmentcio.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/VHA%20Debt%20Letters%20Improvement/MCP%20Wizard%20Mapping.docx?d=w7a11b7a85cc3410f84134bdb15f0cf40&csf=1&web=1&e=b5p4wf)).

**The outstanding terminals:** 
![Screen Shot 2021-10-15 at 12.02.19 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/10312574-439e-47db-bb5f-b6b9c20c0155)

---
## Tasks
- [ ] Review the outstanding terminals and determine next steps for these terminals

## Acceptance Criteria
- [ ] The terminals have either been updated with proper content or removed pending the VHA team's feedback

**Comment by HeatherRienks** [comment]
Closing this ticket, per @denisecoveyduc
