### ISSUE TITLE
[Campaign Landing Page Production Launch]- Annual Influenza Vaccination Campaign (VHA)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31510]
## Description 
(Per Jessi Austin-Ashley/VHA) The flu campaign team is looking to build a seasonal CLP that can be used to help spread awareness and information for Veterans, caregivers, VA employees and their families concerning the annual influenza vaccination offered through the VA. 

### What we want to do on this page:

To provide relevant information in a way that encourages Veterans, employees, VA Stakeholders and their families to get influenza shot. 

## Key Info

**CMS Clone URL/Node**
_https://prod.cms.va.gov/initiatives/flu_
- [ ] (Place Holder)

**Who is Requesting**

- Requestor name: Michelle Spivak 
- VA organization: VHA Communications 
- Email address: michelle.spivakmelinger@VA.gov

**About the Campaign**

- Name or focus of Campaign
   -  Annual Influenza Vaccination Campaign 
   
- Target audience(s) [up to 3]:
   - Veterans, Caregivers, Families, Survivors, VA Employees
   
- Goals of the Campaign: To encourage Veterans and their families, employees and families, and VA's stakeholders to get vaccinated for influenza. 

- Campaign start and end dates: 
   - 10/30 - 03/01, 2022
   
- Campaign page target launch date: 
  -  Not Specified 
  
- Preferred URLs: 
   - Root: va.gov/Initiatives/flu
   - Vanity URL: va.gov/flu
   
- What will you to drive awareness of this Campaign and this page? 
   - Email campaigns to employees, Speaking engagements, VSO outreach, GovDelivery, Annie App, Messaging on Telehealth Screens, Youtube Video, Social Media Posts 
   
- What metrics will you want to know to measure success of the Campaign landing page? 
   - Site visits, Click Through rate.

**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Not at all **(Will require training materials)**
  
- Who will build the campaign landing page in the VA.gov CMS?
  - The flu campaign communications team will draft the copy. VHA will build the campaign.
  
- Who will review and give approval to publish the page? 
  - Michelle Spivak for VHA Comms
  
- Who will update/maintain the landing page during the campaign?
  - Flu campaign communications team
  
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - Desire is to keep it indefinitely and continue to update throughout the year. 

## What Needs to Be Done

- [x] CMS: Set up the CLP clone page in CMS for the build template 
- [ ] Product & IA: Validate that the requested vanity URL is workable/optimal 
- [ ] Product: Get the Analytics dashboard set-up and set-up VA stakeholder to create their UTM URLs

**Comment by xiongjaneg** [comment]
cloned [new CLP node](https://prod.cms.va.gov/initiatives/flu) for editing

**Comment by brianalloyd** [comment]
Vanity URL suggestion has been approved by the Stakeholder.  Just waiting on content publish for implementation .

**Comment by kelsonic** [comment]
Redirect live

**Comment by brianalloyd** [comment]
Closing ticket in support.
