### ISSUE TITLE
Words to generalize content on Register for care page from Facilities team

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31512]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?

- We are hardening the top task VAMC pages. In order to centralize much of the content, we need to remove the specific facility name from the content, which will require some wordsmithing. 
- This issue is focused on the changes needed for the [Register for care page](https://www.va.gov/pittsburgh-health-care/register-for-care/).  
- For example, instead of "Register to get care at one of _our VA Pittsburgh health care facilities._ Not yet enrolled in VA health care? We can help you apply in person or get started online."  should it be something like "Register to get care at _one of your local VA health care facilities._ Not yet enrolled in VA health care? We can help you apply in person or get started online."? 

## Areas of content needing input: 

1. Register to get care at one of _our VA Pittsburgh health care facilities._ Not yet enrolled in VA health care? We can help you apply in person or get started online.
2. Whether you moved and need to change your medical center or need a primary care provider in the area, we can help get you registered _at VA Pittsburgh health care._ Call us or come by one of our offices.
3. You need to be enrolled in VA health care before you can make appointments and receive care at a _VA Pittsburgh health care facility._ 
4. Fill out an Application for Health Care Benefits (VA Form 10-10EZ) and bring it with you to our patient registration office at the _University Drive or Heinz campus._

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*
<details>
<summary> Screenshot </summary>

![screencapture-va-gov-pittsburgh-health-care-register-for-care-2021-10-15-09_12_28](https://user-images.githubusercontent.com/55411834/137511973-ebf6cdba-f699-443b-839c-243cfe02ce8e.png)
</details>

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: _as soon as you are able_

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Facilities
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Michelle Middaugh

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by DanielleThierryUSDSVA** [comment]
@mmiddaugh Same question here re: making sure it's okay to say "at one of our offices."

1. Register to get care with us. If you're not yet enrolled in VA health care, we can help you apply in person or online.
2. Whether you moved and need to change your medical center or need a primary care provider in the area, we can help. Call us or visit one of our patient registration offices to get started.
3 . You need to be enrolled in VA health care before you can make appointments and receive care with us. 
4. Fill out an Application for Health Care Benefits (VA Form 10-10EZ). Bring your completed application to one of our patient registration offices.

**Comment by mmiddaugh** [comment]
Thanks @DanielleThierryUSDSVA
