### ISSUE TITLE
IA Review - VA Online Scheduling (VAOS)

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3152]
As a product manager, I want the IA team to review my tool's architecture and functionality so that the tool we're building is easy to find on VA.gov and flows logically for veterans.

AC
- [ ] VAOS reviewed for adherence to IA guidelines
- [ ] Entry URLs and all tool URLs identified and recommendations made on needed changes.

**Comment by andreahewitt-odd** [comment]
@markgreenburg Product support is the label we use for the product support team's work and this is content and IA so I'm going to remove it.

**Comment by mnorthuis** [comment]
### IA Review and Feedback: 
If you have any questions, please let me know.  

**Structure & URL**
- Existing static page will be used as entry point to new tool, no IA or URL changes will be made to the page at this time:  https://www.va.gov/health-care/schedule-view-va-appointments/
- New tool will live as a child to the existing static page - initial URL: https://www.va.gov/health-care/schedule-view-va-appointments/appointments/
*Subsequent pages will add on to the above URL using short and simple labels, i.e. /introduction/*

**Navigation/Entry Points:** 
- No changes to existing entry points

**Additional Considerations**
- Work with content/writing team to determine how to best represent "schedule" versus "request" functionality - need to determine whether these labels have an impact on user expectations.  
- If the team chooses to change the static page URL (i.e. change "schedule" to "request"), a redirect will need to be implemented from old to new URL.

**Comment by mnorthuis** [comment]
Following up on the "schedule" versus "request" language.  For the URL, "schedule" can continue to be used and the content of the page can clarify any nuances.  No URL changes or redirects needed. 

@markgreenburg You can close this issue if there are no further questions and you have everything you need.  Thanks!
