### ISSUE TITLE
Address validation API sometimes not returning an error when it should

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3153]
When calling `POST https://staging-api.va.gov/v0/profile/address_validation` with the following address we get the following response:

```
// POST body:
{
  "address": {
    "address_line1": "36311 coronado dr",
    "address_line2": "",
    "address_line3": "",
    "city": "",
    "international_postal_code": "",
    "province": "",
    "state_code": "ca",
    "zip_code": "94536",
    "zip_code_suffix": ""
  }
}

// RESPONSE:
{
    "addresses": [
        {
            "address": {
                "address_line1": "36311 Coronado Dr",
                "address_type": "DOMESTIC",
                "city": "Fremont",
                "country_name": "USA",
                "country_code_iso3": "USA",
                "county_code": "06001",
                "county_name": "Alameda",
                "state_code": "CA",
                "zip_code": "94536",
                "zip_code_suffix": "5536"
            },
            "address_meta_data": {
                "confidence_score": 93.0,
                "address_type": "Domestic",
                "delivery_point_validation": "UNDELIVERABLE"
            }
        }
    ],
    "validation_key": -747207952
}
```

Note that we get the following metadata: `"delivery_point_validation": "UNDELIVERABLE"`. And sure enough if you try to save that address to a user's profile, even with the validation key, it fails:

```
{
    "data": {
        "id": "",
        "type": "async_transaction_vet360_address_transactions",
        "attributes": {
            "transaction_id": "e893506e-9dc3-46ea-8774-6402c963ff28",
            "transaction_status": "COMPLETED_FAILURE",
            "type": "AsyncTransaction::Vet360::AddressTransaction",
            "metadata": [
                {
                    "code": "ADDR305",
                    "key": "addressBio.deliveryPointNotConfirmed",
                    "retryable": null,
                    "severity": "ERROR",
                    "text": "Vet360 Validation Failed: Delivery Point is Not Confirmed for Domestic Residence"
                },
                {
                    "code": "ADDR312",
                    "key": "addressBio.failAddressOverrideCriteria",
                    "retryable": null,
                    "severity": "ERROR",
                    "text": "The address override criteria has not been met, please attempt validation again"
                }
            ]
        }
    }
}
```

So I _think_ that `POST https://staging-api.va.gov/v0/profile/address_validation` should be returning an error when passed that 36311 Coronado Drive address.

## Definition of Done 
- Making sure the correct error is being populated as expected. 
- Socialize this with the team in the slack channel when completed.

**Comment by erikphansen** [comment]
Here is another address that gets back an undeliverable address from the API:

```
{
  "address": {
    "address_line1": "37 N 1st St",
    "address_line2": "",
    "address_line3": "",
    "city": "",
    "international_postal_code": "",
    "province": "",
    "state_code": "",
    "zip_code": "11249",
    "zip_code_suffix": ""
  }
}
```

And, as documented here (https://github.com/department-of-veterans-affairs/va.gov-team/issues/2532#issuecomment-546206491) if you use the following address, the API returns two suggestions, but one of them is undeliverable.

```
{
  "address": {
    "address_line1": "37 1st St",
    "address_line2": "",
    "address_line3": "",
    "city": "",
    "international_postal_code": "",
    "province": "",
    "state_code": "",
    "zip_code": "11249",
    "zip_code_suffix": ""
  }
}
```

**Comment by erikphansen** [comment]
Perhaps this one should be for a different ticket, but this is another address that seems to pass the validation API (ie, it doesn't return errors), but the address can't actually be saved to vet360.

`POST https://staging-api.va.gov/v0/profile/address_validation`:
```
// request body:
{
  "address": {
    "address_line1": "1411 SE 30th Ave",
    "address_line2": "",
    "address_line3": "",
    "city": "portland",
    "international_postal_code": "",
    "province": "",
    "state_code": "or",
    "zip_code": "97214",
    "zip_code_suffix": ""
  }
}
// response:
{
    "addresses": [
        {
            "address": {
                "address_line1": "1411 SE 30th Ave",
                "address_type": "DOMESTIC",
                "city": "Portland",
                "country_name": "USA",
                "country_code_iso3": "USA",
                "county_code": "41051",
                "county_name": "Multnomah",
                "state_code": "OR",
                "zip_code": "97214",
                "zip_code_suffix": "4100"
            },
            "address_meta_data": {
                "confidence_score": 98.0,
                "address_type": "Domestic",
                "delivery_point_validation": "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER",
                "residential_delivery_indicator": "RESIDENTIAL"
            }
        }
    ],
    "validation_key": -1125711228
}
```

and this is the failure when trying to save the address:
```
{
    "data": {
        "id": "",
        "type": "async_transaction_vet360_address_transactions",
        "attributes": {
            "transaction_id": "472a00d2-9c5a-4eec-9e1f-73fff2558c4f",
            "transaction_status": "COMPLETED_FAILURE",
            "type": "AsyncTransaction::Vet360::AddressTransaction",
            "metadata": [
                {
                    "code": "ADDR305",
                    "key": "addressBio.deliveryPointNotConfirmed",
                    "retryable": null,
                    "severity": "ERROR",
                    "text": "Vet360 Validation Failed: Delivery Point is Not Confirmed for Domestic Residence"
                }
            ]
        }
    }
}
```

**Comment by erikphansen** [comment]
In summary: if the suggestion API is going to return "invalid" addresses, that's fine, but the FE will need to filter them out so we don't present them as options to the user.

So far I've seen these examples of addresses that come back from the suggestion API but that can't actually be saved to a user's profile as their address:

- when `address_meta_data.delivery_point_validation === "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER"`
- when `address_meta_data.delivery_point_validation === "UNDELIVERABLE"`

**Comment by erikphansen** [comment]
I think I need to revise this ticket. _If_ a user is actually able to override validation and use the validation key to force through an address that's marked as "UNDELIVERABLE" then we don't need to change the API to return an error in this case. This all really hinges on if we can get the validation key to work as we expect it to. Then in cases where we get address suggestions that are flagged as "UNDELIVERABLE" or "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER" we need to inform the user that we think their address is incorrect or incomplete and they should edit it, but also give them the option to force it through as entered.

**Comment by Justin-Pickett** [comment]
@erikphansen and @hinzed1127 working on this to get an understanding of the validation keys.  Also Dan is currently awaiting SSH access...Will follow up early next week (11/13) on this item.

**Comment by lihanli** [comment]
`"delivery_point_validation": "UNDELIVERABLE"` addresses should be overrideable. the errors you were seeing were due to a bug with the vet360 api, they updated their api yesterday and i tried the "36311 coronado dr" address in console just now and it worked, but i had to capitalize `"state_code": "CA"`, it doesn't allow lowercase state codes.

**Comment by Justin-Pickett** [comment]
@lihanli can this ticket be closed? do we need to open a new ticket for any other work regarding the lowercase state codes not being allowed?

**Comment by lihanli** [comment]
@Justin-Pickett i'll let erik retest and see if he still gets errors, don't think we need a ticket for lower case state codes because the dropdown isn't sending lower case state codes

**Comment by Justin-Pickett** [comment]
@erikphansen can you test this so we can close this out for Sprint 9 if possible.
