### ISSUE TITLE
Create Message Templates Content Guide

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#31538]
A content guide will cover requirements for the messaging, such as required content (e.g., include facility name), voice, tone, length, etc. This could help standardize the process as we'll circulate the guide out to all facilities and decrease the amount of differences we’re seeing across the incoming message requests.

Points to cover:

-  messages should have some type of action, whether its call, visit a web link, or a list of times/locations
- messages should be as short as possible
- include VA facility name
- consistent capitalization and spelling, such as "Flu" or "flu".

**Comment by lindsay-insco** [comment]
Completed
