### ISSUE TITLE
[Campaign Landing Page Production Launch]- Emergency Room or Urgent Care

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31537]
## Description 
(Per Jessi Austin-Ashley/VHA) Looking to kick off a Campaign focused on influencing Veterans to choose appropriate modalities of care during a health scare by informing them about injuries and ailments appropriately treated by different modalities. Not every serious injury or illness is best suited for emergency care. Many less-than life threatening injuries or ailments are better suited for urgent care or other modalities.  Choosing the appropriately level of care can have a faster response time and a lower cost of service. 

### Goal: 
To encourage Veterans to choose appropriate modalities of care during a health scare by informing them about injuries and ailments appropriately treated by different modalities. 

### What we want to do on this page:

To provide relevant information in a way that encourages Veterans, employees, VA Stakeholders and their families to get influenza shot. 

## Key Info

**CMS Clone URL/Node**
_https://prod.cms.va.gov/initiatives/emergency-room-or-urgent-care_ 

**Who is Requesting**

- Requestor name: Chris Cox (Jessica Austin-Ashley) 
- VA organization: Office of Community Care via VHA Communications 
- Email address: chris.cox@va.gov

**About the Campaign**

- Name or focus of Campaign
   -  Care Optimization in the Emergency Department 
   
- Target audience(s) [up to 3]:
   - Veterans, Caregivers, Families
   
- Goals of the Campaign: To encourage Veterans to choose appropriate modalities of care during a health scare by informing them about injuries and ailments appropriately treated by different modalities.  

- Campaign start and end dates: 
   - Undetermined (Need to validate with Stakeholder based on "Evergreen" content in request).
   
- Campaign page target launch date: 
  -  ASAP (Requested)
  
- Preferred URLs: 
   - Root: va.gov/initiatives/emergency-room-or-urgent-care
   - Vanity URL: va.gov/choosingtherightVAcare _(Open to suggestions and shortening if possible)_
   
- What will you to drive awareness of this Campaign and this page? 
   - Social media, blogs, VSO briefings, YouTube Videos.  
   
- What metrics will you want to know to measure success of the Campaign landing page? 
   - Site visits, Page Views, Click throughs to existing reference materials (CTAs), measured reduction in unnecessary Veteran emergency care visit numbers. 

**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Not at all **(Will require training materials)**
  
- Who will build the campaign landing page in the VA.gov CMS?
  - VHA digital comms team will build the campaign.
  
- Who will review and give approval to publish the page? 
  - Jessi Austin-Ashley will publish from VHA Comms
  
- Who will update/maintain the landing page during the campaign?
  - Jessi Austin-Ashley will publish from VHA Comms
  
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - Desire is to keep it indefinitely, will need to determine content "fold-in" strategy based on evergreen content.  Possible COPE or R&S content libraries as an option. 

## What Needs to Be Done

- [x] CMS: Set up the CLP clone page in CMS for the build template 
- [ ] Product & IA: Validate that the requested vanity URL is workable/optimal 
- [ ] Product: Get the Analytics dashboard set-up and set-up VA stakeholder to create their UTM URLs

**Comment by brianalloyd** [comment]
@mnorthuis might need some help on the requested URLs for this CLP:
```
Root: va.gov/initiatives/emergency-room-or-urgent-care
Vanity URL: va.gov/choosingtherightVAcare (Open to suggestions and shortening if possible)
```

**Comment by mnorthuis** [comment]
@brianalloyd Yes, yes indeed :-)   I'm going to work on this one a bit as well.

**Comment by brianalloyd** [comment]
URLs have been approved by VA stakeholders: 

Vanity URL: www.va.gov/emergency-or-urgent-care
Root URL: www.va.gov/initiatives/emergency-or-urgent-care

**Comment by mnorthuis** [comment]
Excellent!   Just to clarify, the canonical URL will be based on the actual H1 of the page, so if the H1 is "Emergency room or urgent care", URL would be /initiatives/emergency-room-or-urgent-care.  The canonical URL and the vanity URL won't necessarily match.  I just want to make sure no one is prescribing their H1 and no one is overriding that URL.

**Comment by brianalloyd** [comment]
@mnorthuis thanks for highlighting this, sorry for the confusion.  I've updated my comment above to avoid any implementation issues or confusion.  Greatly appreciated.

**Comment by brianalloyd** [comment]
@kelsonic this CLP has been published and is ready for URL redirects.

**Comment by brianalloyd** [comment]
This CLP is live. Thanks all, closing ticket in support.
