### ISSUE TITLE
Clarify appointment requests

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#31540]
# Problem
We've heard in previous research and from user feedback that appointment requests are confusing. This becomes more problematic with some facilities turning direct scheduling back on.

# Goal
Clarify appointment requests in all flows and appointment information.

---

## Product
There are 2 key areas where users interact with the concept of a "request": scheduling flows and the appointment lists.

**Priority for updates:**
1. Appointment list
- Requests and Upcoming lists
- Impact to Past & Cancelled
2. Scheduling flows
- VA Request flow
- VA Direct flow
- CC Request

### Supporting Data
- Requested List [pageviews](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fhealth-care~2Fschedule-view-va-appointments~2Fappointments~2Frequested~2F&explorer-graphOptions.selected=analytics.nthWeek/)
- Request Detail [pageviews](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22~2Fappointments~2Frequests%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22confirmMsg=true%22,1%5D%5D/) (without confirmation page counts)
- Booked Detail [pageviews](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22~2Fappointments~2Fva%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22confirmMsg=true%22,1%5D%5D/) (includes upcoming, past, cancelled booked)

**Comment by ldelacosta** [comment]
Closing out the epic. We have completed the feature and decided we are not going to bring back the Canceled list. cc: @JRRoof
