### ISSUE TITLE
Analytics Implementation or QA Support for CPM - Creation of New GA Property for Internal Tool

### ISSUE THREAD

**Issue by rnair-tw** [department-of-veterans-affairs/va.gov-team#31546]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Brian Martin
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - Refer to comments
    
- **When is the launch date?**
    - N/A

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - Refer to comments

### Optional

**Additional comments below**

- How many environments? 4 environments
_3 non-prod (dev, staging, test), 1 prod_

- What are the URL patterns for the apps?
_No custom metrics or dimensions
https://cds.med.va.gov/cpm/index.html_

- Any views / sub-properties needed other than the standard All (filtered), Unfiltered, and maybe one for your app?
_The different environments is a view we have now_

- We usually implement a GTM function to aggressively remove any email addresses in the URLs.  Is that enough?  Any other regexes we should throw in there?
_That should be enough. We will confirm internally on the PII data and if this will affect our functionality._

- What interactions like logins, form actions, button clicks, link clicks etc do you anticipate tracking? (We can always add more later.)
1)_“Copy to clipboard” click event
--4 variable metrics that can appear_
2)_“Accordion open” click event:
--“Help”
--“About this tool”_

- Any suggestions on what we should name these properties?  I'm thinking they will (at least eventually) host multiple internal apps.
_Yes, each of the apps should be self-titled:
COVID-19 Patient Manager etc._
 
> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by bsmartin-ep** [comment]
@rnair-tw -

Are we OK to close this issue?

**Comment by rnair-tw** [comment]
yes, we can close it. thank you!
