### ISSUE TITLE
[Content] Review appointment requests research prototype

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#31541]
**Assets**
- [Prototype for content review](https://va-scheduling.invisionapp.com/overview/Request-clarification---content-review-ckuspnfbr00z90151bjq20cdg/screens?sortBy=1&sortOrder=1&viewLayout=1)
- [Research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2021-request-clarification/research-plan.md)

**Notes** 
Not all screens are modified from the current flow. I labeled screens that need review with an ![Review blob.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/eeb23767-9e2e-4e7d-8793-ee1894f21011) in the upper right corner (near the breadcrumb) along with notes specific to that screen.

Along with content feedback, any questions that you would like answers to during this research would be helpful!

**Comment by outerpress** [comment]
> Screen 4: Update intro to: Evanston VA Clinic doesn’t offer online direct scheduling for primary care appointments.

Will do. Also, during PI planning it was suggested we start using the phrase "self scheduling" since direct scheduling means something else in different contexts. Any objections to testing out that language here?

> Screen 7 QUESTION: where does this link take users? I can provide some language letting users know link will take them out of form..

Good question! I'd say assume it goes to [MyHealtheVet secure messaging](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/secure-messaging-spotlight). I'm mainly interested to find out if they expect to take add'l steps, or to directly send a message from within VAOS.

> Screen 8 QUESTION: Why are users seeing the calendar screen/selecting a preferred date? 

Good catch. The first option leads into the request flow. After they select that, any information they enter will be sent to a scheduler, who will review it and call back the Veteran to schedule/finalize the appointment.

Any recommendations on how to improve this transition, either by rewording the first radio, the calendar page, or both?

I'll get the prototype updated with the rest of your notes. Thank you @peggygannon !

**Comment by peggygannon** [comment]
Hi, @outerpress Thanks for your responses! 
No objections from me with the term "self scheduling"

**Comment by outerpress** [comment]
> No objections from me with the term "self scheduling"

Perfect, updated the screens with that, and the rest of your feedback. I tried tweaking the calendar page language a bit to make it clearer. 

Let me know if you have any other feedback, otherwise I'll close this one out and I'll report back after the research.

**Comment by peggygannon** [comment]
Hi, @outerpress Thanks. No other feedback at this time!
