### ISSUE TITLE
[LoROTA] Request for new GET endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#31554]
**User Story:**
As a veteran, I want to be notified with an appropriate error message when I refresh my old appointments page the next day.

**Description:**
During Phase 4 Multiple appointment product launch for veterans to view the list of appointments in a day, vets-api(Veteran Facing Service) implemented refresh functionality to enable veterans to view up-to-date appointment information anytime during the appointment day.

This caused an edge case issue of veterans keeping the page idle overnight and seeing failure while refreshing the page the next day.  

To fix the issue, vets-api team decided to enquire about the status of a UUID in LoROTA to confirm eligibility before calling CHIP/refreshAppointments. (More details in [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/vets-api/docs/page_refresh_failure/Overnight%20Appointment%20Page%20Refresh%20Failure.md))

Requesting LoROTA team to create new GET endpoint that can be called without JWT token in LoROTA to just enquire UUID validity.  Endpoint can provide HTTP response with status code listed below,

HTTP Status Code 200 (Successful) for appointment data within/outside check-in time threshold for current date
HTTP StatusCode 404 (Not Found) for UUID not available in LoROTA
HTTP StatusCode 401 (Unauthorized) for valid UUID with invalid token
HTTP Status Code 403 (Forbidden) for appointment data inaccessible with current time
HTTP Status Code 410 (Gone) for expired data
HTTP Status Code 500 for UnKnown error

**Clarifications:**
We also would like to get help from LoROTA team on clarifying below questions,

1. Is JWT token still valid even after appointment data associated with UUID gets deleted by cleanup automated task in LoROTA? Can vets-api use previously fetched JWT token for querying LoROTA for checking UUID validity?
2. In what scenario request to LoROTA reaches the [code path](https://github.com/department-of-veterans-affairs/lorota/blob/ebcee0dc731c4251bd3c3b159af92405fa8f086f/src/lambdas/project-LoROTA-get/index.js#L32-L36) and responds "data is inaccessible right now due to a time constraint"?

**Acceptance Criteria:**
LoROTA GET endpoint available in Staging and Prod environment with above HTTP Status Codes

**Comment by julieadair1** [comment]
@kanchanasuriya - is this related to pre-check-in work?
