### ISSUE TITLE
[Design] Add "preferred name" to 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#31552]
## User Story

As a Veteran I would like to be able to provide my preferred name when I apply for health care.

## Expected Behavior

- This is intended to be released with new SIGI question
- This question should appear after Suffix

## Clarifications needed
- Is this question mandatory?
- Guidance copy (eg. why we ask it? is it just first name?)

## Acceptance Criteria

- [x] New design
- [x] Content approved
- [x] FE ticket made  #32824

**Comment by MickinSahni** [comment]
Pending sync with HEC today

**Comment by Dene-human** [comment]
- HEC team has not confirmed if this is a required question or not.

- **Authenticated** (after MPI lock update) this question should appear first
- **Unauthenticated** this question should appear on the name page

[Design PDF](https://app.zenhub.com/files/133843125/25aa40d0-929a-4918-b96c-e8fa34632df3/download)
