### ISSUE TITLE
Spike: Explore Datadog capabilities

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#31555]
VSP has launched Datadog, which is another metrics/monitoring tool. It appears that it can replace Prometheus and Grafana, and doesn't require SOCKS access.

We should explore what it offers and if we think we should prioritize moving to it.

Some more context in thread: https://dsva.slack.com/archives/CE4304QPK/p1634309504219900

Timebox: 8 hours

**Comment by ldelacosta** [comment]
@cferris32 @ajmagdub - Do we need to explore Datadog capabilities in the near future?

**Comment by ajmagdub** [comment]
Added Datadog findings to va.gov-team repository, [Datadog monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/application-monitoring/datadog.md)

**Comment by ldelacosta** [comment]
Currently Datadog is collecting data from all Vets API modules (including VAOS). VAOS BE team will create Datadog dashboards and alerts once the Platform releases features to the VFS teams. A new ticket will be created for this work. Closing out the spike.
