### ISSUE TITLE
CIE - Cerner Integration

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31567]
## Product Outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/Cerner/integration_discovery.md

## Description
VA is transitioning to a new electronic health record (EHR) system (Cerner Millenium) over a 10-year period scheduled to end in 2028. In order to support self-service patient check-in at all VA Medical Facilities, the check-in app must interoperate with Cerner to retrieve appointment records and update appointment statuses.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jparker0425** [comment]
@julieadair1 going to close this out until Cerner work is prioritized, if/whenever that is. If Cerner work comes back up, we can create a new epic specific to that work.
