### ISSUE TITLE
[Development] Navigation Pane on Decision Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3156]
## User Story or Problem Statement
As a Veteran, I need to be able to access the Higher-Level Review page so I can understand how to move forward in the process.

## Goal
_The user is able to navigate to the Higher Level Review page using the left navigation pane._

## Acceptance Criteria
- [ ] _GIVEN a user is interested in completing a Decision Review_
- [ ] _WHEN the user accesses the Decision Review page_
- [ ] _THEN the system will display a navigation pane, allowing the user to navigate to other sections of the Decision Review options_

## Design Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/2026

**Comment by Mottie** [comment]
This content can only be modified through Drupal ([ref](https://dsva.slack.com/archives/CLXEU7Z17/p1573163124023800?thread_ts=1573062080.021400&cid=CLXEU7Z17)).

> Nick Sullivan (in Slack)
> you just need credentials to log in to Drupal. Before you can get credentials, you need a va.gov email address

> that would be all Drupal, and that's a standard side nav
> ... I don't think we need an engineer to do anything for that page

**Comment by peggygannon** [comment]
Hi, @Mottie We need to create a new ticket for the content updates to the Higher-Level Review landing page. I'm happy to create this ticket and assign it to the public websites team and myself. 

We'll coordinate with your team on when this page is ready to update in drupal. The mockup is still in content and I/A reviews. 

cc @YanaRoy

**Comment by luke-gcio** [comment]
Luke to go chase down whether this was ever closed/done/needs more work on the Drupal side.

**Comment by luke-gcio** [comment]
Talked to @peggygannon and we will add another content review as part of the HLR launch. Which means we can close this ticket for now.  Also, there is a ticket #4139 that should cover part of the above.
