### ISSUE TITLE
VANotify Form Submission Email Content Review from Debt Resolution Team (FSR)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#31580]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
We wrote a draft of the submission email for Financial Status Report using the example provided in VANotify's documentation, however, we had some extra content that was added, so I wanted to get this reviewed. This is the email that will be sent to a Veteran once their request has been submitted online.

  
## Supporting Artifacts

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/Notifications/FSR-Submission-Email.md 
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: UNKNOWN
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Denise Coveyduc
-	Designer: Rebecca Walsh, Riley Orr
-	FE engineer: Craig Wheeler, Justin Lin
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by DanielleThierryUSDSVA** [comment]
Good morning, @rebeccawalsh! I started a new branch with my edits here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/FSR-Submission-Email-dt-edits/products/Debt%20Resolution/Financial-Status-Report/Notifications/FSR-Submission-Email.md

Some thoughts related to my edits:
- I revised the language about making payments to make it clear that you should make "any payments due." Let me know what you think.
- I added the phone number for people who may need help. I think we want to make sure someone who has questions has a quick way to follow up.
- I removed the "Thank you for your service, VA.gov." It feels weird to have a website sign an email. Also seems a little random/insincere to throw that in a confirmation email (and especially one about debt). I don't think we need a sign off on a confirmation email. Thoughts?

**Comment by rebeccawalsh** [comment]
@DanielleThierryUSDSVA Thanks! 

- Cool!
- Good shout
- I'm good with that - I just included it since it was part of the template provided by VANotify :)

**Comment by denisecoveyduc** [comment]
@rebeccawalsh @DanielleThierryUSDSVA Sounds like this is all set to move forward with then? Just checking, I'd like to sync up with the VANotify team to move this forward.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @denisecoveyduc. I realized that Becca hadn't answered before she left. I think this is good to move forward, yes. Thanks!

**Comment by denisecoveyduc** [comment]
@DanielleThierryUSDSVA Thanks for reaching out.. We shared this notification with VHA who had a few comments that @rileyorr has been integrating. We do plan to move this forward the first week in January and iron it any current wrinkles ahead of a Jan 7th meeting with the VA Notify team. We will post the latest content - I don't believe it is that different from the one you had reviewed previously.

**Comment by DanielleThierryUSDSVA** [comment]
Perfect - thanks @denisecoveyduc!

**Comment by RLHecht** [comment]
@denisecoveyduc is this work that's complete or still in progress? It's currently in our blocked column and I'm trying to figure out if it can be closed or it's just stalled. Thanks!

**Comment by denisecoveyduc** [comment]
Hi @RLHecht Funny you mention this I just followed up with our stakeholders again yesterday. We are waiting on the VBA privacy officers to approve the copy for the notification that Veteran's will receive when they submit an FSR on the portal. It has been in their hands for quite a while you can classify it as stalled. That said, Jill is going to reach out today (Mar 24) to see if she can get it back on track. We all want to wrap this up! I will keep you posted but currently there is no work for the content team to do. Hope that helps.

**Comment by RLHecht** [comment]
@denisecoveyduc Great minds think alike! I'll leave this in blocked for now then. Hopefully it gets wrapped up soon!

**Comment by denisecoveyduc** [comment]
@RLHecht I just heard back from Jill and sounds like the privacy officers are accepting of the proposed changes so I think we are safe to close this one out. We are moving forward with the development work to set up this notification for Veterans.
