### ISSUE TITLE
Higher Level Review Design Mockups Content Updates

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3158]
## User Story or Problem Statement
As a designer, I need incorporate all of the content updates provided by the content team to the mockups so that FrontEnd engineers can incorporate those changes into their designs.

## Goal
_All design screens to be updated with final content provided by the content team_

## Acceptance Criteria
- [x] _Individual design screens have been updated with content provided in InVision notes_

**Comment by carolynwill** [comment]
https://vsateams.invisionapp.com/share/QWUSO15RBN9
Content edits updated and mobile screen removed for easier tracking.
