### ISSUE TITLE
[BE] Data Serializer from LoRota

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31601]
## Description
Update the serializer to include `Next of Kin` data 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- Modify the existing serializer for Next of Kin data
- Modify serializer rspec for Next of Kin data

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by kanchanasuriya** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31601?planning-poker) with ZenHub @randomsync @dillo
