### ISSUE TITLE
[Research] My VA 2.0 enhancements: Determine edu section triggers/parameters

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31609]
## Background
As part of the exercise to scope the MVP for adding an education section to My VA we need to determine what triggers this section to appear for users. Consider this: _If we can only tee off of the education direct deposit, that means we can only show this section to people who already receive edu benefits, which means we only want to elevate the edu tasks that matter to that group._

## Tasks
- [ ] Discuss with DGIB group (may need to include Lihan, and an FE dev on this convo): _are they aware of APIs we can tap into besides the one that tells us if someone receives edu payments?_
- [ ] Use discussion with DGIB team to document parameters that would trigger this section to appear for users on My VA

**Comment by Samara-Strauss** [comment]
Since we are pivoting, I think we can close this ticket.

**Comment by tressaellen** [comment]
Works for me!

**Comment by ajakabcin** [comment]
removing from sprint/milestone as work was cancelled
