### ISSUE TITLE
[Research] Edu on My VA: Discovery with DGIB around edu user needs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31604]
## Background
We need to talk with the DGIB team about what they know to be important to edu users to understand a useful baseline and establish an MVP.  For reference, [here is the education section of the website](https://www.va.gov/education/) to give you an idea of what people might need to do.

## Tasks
- [ ] Meet with DGIB researchers, designers and pm's to discuss edu users' needs
- [ ] Add findings to our documentation to help define scope of MVP

**Comment by tressaellen** [comment]
Everything will be in [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/education/discovery-and-research/edu-benefits-discovery.md). I need to add a couple more notes tonight/tomorrow - but this ticket is done.
