### ISSUE TITLE
[BE] Swagger documentation - Next of Kin

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31603]
## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by dillo** [comment]
Swagger docs for Next-of-Kin have already been added. This is a duplicate. Closing.
