### ISSUE TITLE
[Research] User Roles Research: Reach out to SMEs to set up interviews

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31618]
## Background
As part of our user roles discovery we need to coordinate time with the SMEs across the various administrations we'll be interacting with.

## Tasks
- [x] Set up interviews with each admin (VBA, NCA, VHA)

**Comment by andaleliz** [comment]
Interviews have been scheduled with all the folks Samara emailed with, and [are being tracked here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/user-roles/discovery/sme-interviews/README.md).

**Comment by Samara-Strauss** [comment]
Thank you, Liz!!

**Comment by andaleliz** [comment]
Interviews are scheduled with all SMEs now that we're holding off on talking to anyone at NCA.
