### ISSUE TITLE
[Research] User Roles Research: Create conversation guide(s)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31617]
## Background
As part of our discovery work around non-veteran user roles, we need to create a conversation guide (or guides, where appropriate). 

## Tasks
- [x] Create convo guide for VHA
- [x] Create convo guide for VBA

**Comment by andaleliz** [comment]
All guides are stored [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/user-roles/discovery/sme-interviews/conversation-guides)
