### ISSUE TITLE
Research plan for VAMC non-clinical taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31626]
## Issue Description
In #30839 we audited the VHA taxonomy to identify areas of possible misalignment which needs to be informed by Veteran research.

Goals
- Gain understanding about Veteran mental models for the organization/classification of non-clinical VHA services

---
## Tasks
- [ ] Identify the appropriate method for seeking Veteran input on non-clinical taxonomy classification and organization.

## Acceptance Criteria
- [ ] Approved research plan and conversation guide ready for recruitment

**Comment by nicko-amida** [comment]
Here's my [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/services-taxonomy/services-taxonomy-research-plan.md) for the taxonomy study. Aiming for final feedback and approval next week, with research starting on November 17th.
