### ISSUE TITLE
[FE] Auth Profile: Changing the Side Nav of the profile.

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#31662]
## Issue Description
Split off Personal and Contact information links within the Side Nav and create two separate links. 

![Screen Shot 2021-10-19 at 1.07.42 PM.png](https://images.zenhubusercontent.com/5f9095454fbba3b0c3d10cff/088b9a1b-4bf3-422a-ae82-37c08e5e5969)

## Acceptance Criteria
- [ ] The Navigation works as intended
- [ ] Personal and Contact Information navigation are separated and behind a feature flag.. 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
This update is on Staging
