### ISSUE TITLE
[FE] Auth Profile: Adding/ Adjusting content in new Contact Information section after migration.

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#31681]
## Issue Description
As the title says! Adjusting any content as needed that is specified by content or other stakeholders.  

Note that the mockup below is meant only to convey the fields that will be moved to the Content page.  Please follow the design pattern that already exists in production.

![Screen Shot 2021-10-19 at 1.59.02 PM.png](https://images.zenhubusercontent.com/5f9095454fbba3b0c3d10cff/29451fbb-223e-43fa-8430-65a2d9b6de0f)

## Acceptance Criteria
- [ ] Design pattern matches what is currently in Production
- [ ] Content of Fields matches that is approved from stakeholders/ content
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
Closing this ticket since it is redundant
