### ISSUE TITLE
[FE] Auth Profile: Updating existing Profile tests 

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#31688]
## Issue Description
Tests need to be updated, added for the profile enhancements.

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass

**Comment by SKasimow** [comment]
@adamwhitlock1 - assume this needs to be done along with the FE work for Profile revisions in sprint 72? LMK if I need to add to the Sprint 72 epic.

**Comment by SKasimow** [comment]
Closing...

**Comment by SKasimow** [comment]
Closing...
