### ISSUE TITLE
Collaboration Cycle - Implement scheduling tool: Release Plan

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31702]
## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: 3 Design Intent meetings
- Desired number of users: 3 VFS teams
- The group(s) from which you'll recruit test users: VFS
- How you'll recruit test users: when they submit Design Intent request tickets
- How you'll give test users access to the product: pilot will be live in github templates
- What "Success" criteria will you look at before launch? [refer to the desired outcomes and KPIs in your product outline]: Reduction in tasks performed by Platform. Currently, Platform is responsible for the following tasks:
1. Verify the date/time is available*
2. Verify the date/time is within the appropriate window*
3. Create the meeting invite*
4. Invite VFS team members*
5. Invite Platform team members
6. Include the github link in the invite*
7. Include Zoom information in the invite
8. Ensure that the Platform Collaboration Calendar timeslot is reserved*
The 6 tasks with asterisks are tasks that VFS and/or Calendly will be responsible for in the pilot. 
- How you'll measure your "Success" criteria? Success will be measured by 85% completion rate of the out of the 6 tasks listed above per VFS teams. 15/18 tasks overall.

### Results:

- Number of users: 3	

- Results per your "Success" criteria:

#### Pilot 1

1. Verify the date/time is available* - Pass
2. Verify the date/time is within the appropriate window* - Pass 
3. Create the meeting invite* - Pass 
4. Invite VFS team members* - Pass 
5. Include the github link in the invite* - Pass 
6. Ensure that the Platform Collaboration Calendar time slot is reserved* - Pass 

#### Pilot 2

1. Verify the date/time is available* - Pass
2. Verify the date/time is within the appropriate window* - Pass 
3. Create the meeting invite* - Pass 
4. Invite VFS team members* - Pass 
5. Include the github link in the invite* - Pass 
6. Ensure that the Platform Collaboration Calendar time slot is reserved* - Pass 

#### Pilot 3

1. Verify the date/time is available* - Pass
2. Verify the date/time is within the appropriate window* - Pass 
3. Create the meeting invite* - Pass 
4. Invite VFS team members* - Pass 
5. Include the github link in the invite* - Pass 
6. Ensure that the Platform Collaboration Calendar time slot is reserved* - Pass 

- Number of bugs identified / fixed: 0/0

- Any UX changes necessary based on the logs, user feedback, or VA challenges? Yes
1. Some confusion over adding VFS attendees. We changed the text and moved some around in the GH ticket and did not have a problem with the 2 and 3 pilots.
2. Product support has to search the calendar to add their attendees. We should ask the VFS PM to add the scheduled date and time in the Slack notification. See comment for Pilot #3.

### Planning:

- Desired launch date: 12/2/2021
- Post-launch KPI 1:
- Post-launch KPI 2:
- Post-launch KPI 3: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"? Since launching, VFS team and/or Calendly have consistently handled at minimum 4 at maximum 6 of the 6 tasks specified.
2. What qualitative feedback have you gathered from users or other stakeholders, if any? None.
3. Which of the assumptions you listed in your product outline were/were not validated? We did not list any assumptions.
4. How might your product evolve now or in the future based on these results? Ideally, it would be wonderful if Calendly could include Platform attendees on the invite opposed to us having to add them after the meeting is scheduled, however Calendly does not currently have that functionality.
5. Did anyone have the invite go into their spam folder? Not that we're aware of.

**Comment by allison0034** [comment]
Pilot # 2: [#32275](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32275)

Observation: Natasha did not check off that she had scheduled the meeting in the GH ticket, although she did schedule it. She tagged support in the Slack channel "I need help from the collaboration cycle team for this design intent meeting ticket". Her designer commented on the ticket that she had decline the meeting and requested it be moved to another day.

**Comment by allison0034** [comment]
Pilot #3: [#32658](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32658)

Observation: Russel had no issues scheduling the meeting. He commented in the Slack channel that he had scheduled it and I asked for the day and time. I wonder if we should ask them to post that in Slack so we do not have to search the calendar to add our attendees?

**Comment by shiragoodman** [comment]
@allison0034 this is looking great! Do you want to set up time (Friday maybe?) to walk thru the User Research readout?
