### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#31709]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the `department-of-veterans-affairs/vets.gov-write` org. Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: jchilders
- Reason access is required: developer access to verify code changes in higher (non-local) environments

**Comment by f1337** [comment]
Done!
