### ISSUE TITLE
outcome metrics  - Customer Support Volume  

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#31716]
one of our suggested KIPs for the integration experience team is Customer Support Volume.  
Document how we might access that metric.

Over the past 6  months how many support requests were about upstream services each month?

The raw data is is linked here https://dsva.slack.com/archives/CJRQ85PQB/p1634588085042700?thread_ts=1634585396.039900&cid=CJRQ85PQB

**Comment by annaswims** [comment]
Oh, more context... there's a #vfs-platform-support slack channel  that has a slack app so the support request ends up in both slack and the google spreadsheet. 

I'm interested in how many of the support requests were about upstream services/apis

**Comment by considerable** [comment]
<img src="https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/4d80365d-7005-48f0-a80d-92e8422383f8" alt="vfs-platform-support-submitters.png" width="400"/>

<img src="https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/3b74f51d-5db7-43f3-8edd-086e6ebeaa8a" alt="vfs-platform-support-teams.png" width="400"/>

The above is beast I can make out of the existing data: about 110 users submitted 1 or 2 issues each and 6 teams were responding it.
As no "upstream" team is in the tags or in the comments, I can not speculate how many issues were upstream-related.
