### ISSUE TITLE
Midpoint Review [Public Websites, New VA.gov Mobile Header]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31712]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Schedule meeting with Collaboration Cycle reviewers and VFS team attendees listed in the ticket. 
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [x] Respond to feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [ ] Yes*
- [X] No 

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)
- [ ] [Initiatives Briefing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Initiative%20Briefing.md)
 
- [ ] [Finalized design prototype or mockup](https://www.sketch.com/s/63193c20-04fc-4d4f-8b54-abf698c48636/a/Vr8Zzrw)

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

### Required* 
\*Only required for synchronous meetings.
- Product Manager: Brian Lloyd
- OCTO-DE Product lead: David Conlon
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Kelson Adams 
- Trent McDole

### VFS Attendees

- Content and IA: 
- Accessibility: 
- QA specialists: 

## Scheduling
Would you like this review to be asynchronous? Yes

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [X] Yes
- [ ] No

**[11/5/2021]** **[2PM]**

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by joshkimux** [comment]
No feedback from accessibility at this time from myself and @AngelaFowler82  👍 
@noahgelman please add on if there's anything we're missing.

We recommend the following future considerations (which we understand are out of scope for this effort)
- Schedule a research study on search for assistive technology users to determine performance of hiding search within the menu
- Add a non-collapsed search component to the va.gov homepage above the fold (*when search is improved) and possibly a non-collapsed search component to the footer (so it can be universally reached by screen reader shortcut keys)

**Comment by brianalloyd** [comment]
@shiragoodman would it possible to push this review to early next week?  We're run into a delay with search implementation based on the new designs and hope to have that resolved by COB tomorrow.

**Comment by allison0034** [comment]
No design feedback... thank you!

**Comment by peggygannon** [comment]
Hello, I have no content feedback. Thanks!

**Comment by jimuhh** [comment]
Hi. I have no IA feedback. Have a nice weekend!

**Comment by pjhill** [comment]
Hello, I have a few questions with regards to the missing QA artifacts for this product --
* Have you all engaged with a QA Engineer in order to develop test cases and a test plan for this effort?
* Are there any applicable existing test cases for the mobile header that you may want to re-use?
* Are there any functional requirements that you'll be carrying forward from the existing header?

**Comment by brianalloyd** [comment]
@pjhill all great questions, let me see if I can provide some insights here:  PW team is in the process now of building out the test cases for this effort, and plan to update via the [QA ticket #32505 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32505) for this product. I don't believe test cases exist for the mobile header as this will be the first refresh since the release of the modern VA.gov.  I'll circle back early next week once we've completed the test cases in support.  Please let me know if any questions remain.  Thanks.
