### ISSUE TITLE
[BE] SPIKE - Integration tests for vets-api

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#31721]
## Description
Currently we don't have any e2e tests for CheckIn module which results in additional manual effort to gain confidence before deploying. As part of this spike, we'd like to explore different options available to add e2e tests that run automatically as part of CI.

Some options to consider:
1. Using external js frameworks like Cypress
2. Explore other options

The goal is to be able to mock calls to external services (LoROTA/CHIP) by specifying canned responses (for positive as well as negative scenarios), and run these tests in an automated manner locally or in CI.

## Acceptance Criteria

- [ ] Small working demo using selected tool
- [ ] Recommendation on next steps

**Comment by randomsync** [comment]
This has been done using betamocks for local testing, and VCR for integration tests in CI. Should this be closed @dillo @kanchanasuriya ?

**Comment by dillo** [comment]
I'm fine with closing it @randomsync
