### ISSUE TITLE
Find a VA Form: PDF Download Instructions VSA-QA Test Plan

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31725]
## Product/Feature summary
The Find a VA Form search results and form detail pages will now have a dismissible modal that appears whenever a user clicks a link to download a PDF form the search results or the form detail page.  This modal will set a cookie that allows us to display the modal to a given user only once every 24 hours.

- Product/Feature Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md
- Product/Feature Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26816
- Product/Feature Copy deck(s): In design prototypes
- Product/Feature Design prototypes: In design prototypes

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research:  Cassandra Allen / Cindy Merrill
Content/IA: Beth Potts, Randi Hecht
Front-end: Zach Morel
Back-end: N/A
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md
 - Use Cases [S-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-f), [S-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-g), [D-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-f) and [D-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-g) have been added

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod environment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by MarciMcGuireGCIO** [comment]
@tlei123 Hi! Quick update - I've updated our use cases and added links to prototypes,   Zach is currently getting one of the modals on Staging for midpoint review.   I'll ping you again when this is ready for Test Rail test cases.  I'm hoping that will be some time next week.  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@tlei123 this is all up on staging now and we are ready to rumble when you are!

**Comment by MarciMcGuireGCIO** [comment]
@tlei123 I'm going to start adding the new test cases to TestRail so hopefully all you'll need to do is run them.

**Comment by tlei123** [comment]
@MarciMcGuireGCIO , QA test-runs now done.  QA-artifact links are below, and updated in Staging Review ticket #33134.

100% passed; no defects logged.  CONGRATS!!  

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/2612)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=3025)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/282)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/283)

cc @zacharymorel
