### ISSUE TITLE
User Survey Request for Debt Resolution Team (Medical Copay Tool)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#31728]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
Medical Copay Tool is a dashboard where Veterans can view current copay balances at each of their facilities. The tool consists of a summary page with cards for each facility that list balance and status, and detail pages for each facility with more in-depth information like statement downloads, contact, and payment information.

In reviewing the available questions and documentation, we modified one of the recommended combos found ever so slightly [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md):
1. What task were you trying to do today? [Free text]
2. Were you able to do your task today? [Yes/No]
3. How do you rate your experience on this page? [1-5 stars]

### Launch Date
- ~November (TBD)

### Staging URLs
- https://staging.va.gov/health-care/pay-copay-bill/your-current-balances 

### Production URLs
*Please provide Production URLs*

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by jwoodman5** [comment]
This was previously added on staging and prod. Closing.
