### ISSUE TITLE
[FE] research: determine how to call the validation API instead of the update/save endpoint from the address edit modal

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3172]
## Goal 

determine how to call the validation API instead of the update/save endpoint from the address edit modal

## Definition of Done

- [ ] Determined by FE as finished

**Comment by bradl3yC** [comment]
Currently, the createTransaction thunk is being called from :

src/platform/user/profile/vet360/containers/ProfileField.jsx

and that thunk lives in src/platform/user/profile/vet360/actions/transactions.js

A new thunk will need to be created that will take the place of the direct call in ProfileField where the Address Validation API response will be evaluated and based on that response we will either push directly to the thunk listed above or save the suggested addresses in state and display the modal with that data shown

**Comment by Justin-Pickett** [comment]
@bradl3yC do we need to create a ticket for the information that was  discovered as noted in the above comment?
