### ISSUE TITLE
[FE] 10-10EZ - American Indian question: Turn American Indian question on in Prod

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#31734]
Enrollment System (ES) to consume beginning August 8th, 2022

## User Story
As a Native American, I want to be able to specify that during enrollment on the 10-10EZ, in order to receive appropriate VA Health Care.

## Expected Behavior
Feature toggle for American Indian question turned on in **Prod**

## Acceptance Criteria
- [ ] Add/Confirm any relevant events/tags for analytics tracking
- [ ] Feature toggle turned on
- [ ] Verify question available in **Prod**

**Comment by hdjustice** [comment]
@lihanli - Do you know if there is any special work needed to ensure the American Indian question is included in the data sent downstream for EZ form?

**Comment by lihanli** [comment]
> @lihanli - Do you know if there is any special work needed to ensure the American Indian question is included in the data sent downstream for EZ form?

looks like the backend code for this was already done

**Comment by hdjustice** [comment]
Ok great, thank you for checking!

**Comment by markfallows** [comment]
Added an additional task to this ticket to check that any necessary events/flags for analytics have already been added, or to add them prior to activating this in prod.

**Comment by longmd** [comment]
@markfallows , do we need to go ahead and close this one, since there are tickets for the phased rollout of this?

**Comment by markfallows** [comment]
Closing since we're moving to a phased rollout and the tickets have been created for that.
