### ISSUE TITLE
[FE] 10-10EZ - SIGI: Launch SIGI to Production at 25%

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#31736]
Enrollment System (ES) to consume this data in November

## User Story
As a Veteran, I want to select my gender on the 10-10EZ form in order to reflect my self-identifying gender identity.

## Expected Behavior
Feature toggle for SIGI question turned on in **Prod**

## Acceptance Criteria
- [ ] Feature toggle turned on
- [ ] Verify question available in Prod
- [ ] Test submission successful

**Comment by hdjustice** [comment]
Closing all SIGI tickets - There has been no further movement or discussion on this topic
