### ISSUE TITLE
[BE] Refactor controllers/services to use LoROTA and Redis Clients

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#31755]
## Description
As part of #31210, clients for LoROTA and Redis were added. This ticket is to refactor the code in controllers and services to use these clients. The code should be added with a feature flag so these changes can be tested and rolled back as needed.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by jparker0425** [comment]
@randomsync @dillo What is the blocker reason again for this item ?
