### ISSUE TITLE
[FE] 10-10EZ - Breadcrumb update: Incorrect casing in breadcrumb

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#31767]
## What happened?
The breadcrumb on the 10-10ez form (https://www.va.gov/health-care/apply/application/introduction) has incorrect casing for the "Health care" segment.   It currently reads "Health Care", but should have a lower case "c" on "care". 

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/2869462f-52ca-4919-9c6b-31d96b69e0e4)

## Specs:
- Device: (e.g. iPhone 8, Macbook) all
- Browser: (e.g. Firefox, IE 11) all
- Test User _(if applicable)_: any

## Steps to Reproduce
- URL:  https://www.va.gov/health-care/apply/application/introduction
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by hdjustice** [comment]
Our team does not control how Breadcrumbs are displayed.  Closing this ticket.
I will find out who does have control over them

**Comment by longmd** [comment]
@hdjustice , its been found where we can programmatically override the breadcrumbs.

**Comment by hdjustice** [comment]
Can we document this somewhere within the [Engineering folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/engineering) for future reference?

**Comment by longmd** [comment]
@hdjustice , I added to the FE engineer document.

**Comment by hdjustice** [comment]
![image](https://user-images.githubusercontent.com/92328831/216096025-f95d2afb-4249-4cfc-8982-5ea11bf21f07.png)

Screenshot showing "Health care" with lower case 'c', as advised
