### ISSUE TITLE
[FE] 10-10EZ - Improvement: Update the form URL to meet VA.gov standards

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#31768]
**RISK** - There are many references across VA.gov and other sites that point to our current URL.  We will need to consider redirect efforts along with this change

## User Story

As a user I would like to have a readable and accurate URL to help me find content I want, understand what the content is about, and identify where in the site the content is. 

Reference [URL Standards in the Content Style Guide](https://design.va.gov/content-style-guide/url-standards)
- [URLs must be structurally accurate](https://design.va.gov/content-style-guide/url-standards#urls-must-be-structurally-accurate)

## Expected Behavior

URL for all modernized pages/forms follow the URL standards. 
The 10-10ez URL should be:  www.va.gov/health-care/apply-for-health-care-form-10-10ez

## Acceptance Criteria

- [x] URL is updated to meet standards.

**Comment by hdjustice** [comment]
If we do have to make this change, We will need to submit a redirect request to Public Websites to update any links to our page(s)

**Comment by longmd** [comment]
With additional entry added, confirmation of application rendering _LOCALLY_ at both URLs has been confirmed. 

| Current URL | New URL |
| -------- | ------- |
| <img width="1904" alt="Screenshot 2024-04-08 at 12 50 11" src="https://github.com/department-of-veterans-affairs/content-build/assets/6738544/cc9cc19e-3c1d-4a5f-87a9-02ec5805216e">  | <img width="1904" alt="Screenshot 2024-04-08 at 10 45 59" src="https://github.com/department-of-veterans-affairs/content-build/assets/6738544/912ce03b-0995-4f0b-af89-936284e686a8"> |

**Comment by mnorthuis** [comment]
Whew!  This is an oldie but goodie!  So glad you are making this change!   Please note that you will need to coordinate a redirect ticket with CAIA and Public Websites before the new URL goes live so we do not have old links resolving to a 404.

**Comment by longmd** [comment]
Thanks, @mnorthuis . This is on the list to have done as an (almost) final step of the process. Definitely an oldie, but finally got some guidance on how to do it all without downtime from another VFS team that just went through the same update.

**Comment by hdjustice** [comment]
CAIA ticket opened #80756 for redirect request

**Comment by longmd** [comment]
@hdjustice , the URL update has been completed and has gone to production! 🎉

**Comment by longmd** [comment]
@luis-simauchi , just a heads up that the root URL for the Health Care App has gone to prod.
