### ISSUE TITLE
Diagram relationships between teams and external services

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#31775]
using info from the [External Service / Front end source](http://grafana.vfs.va.gov/d/XYv1D0D7k/external-service-front-end-source?orgId=1) stats and [the FE app ownership](https://docs.google.com/spreadsheets/d/1V2cRi4vHLAYDvST8y9nYegtW_gD23NS7ZIhXfF5p5xU/edit#gid=1999626981 )
 make a diagram that show the relationship between teams, apps and upstream services.
consider using a diagramming tool like [mermaid](https://mermaid-js.github.io/mermaid/#/) that lets us convert text/code into a diagram.

 mermaid.live

**Comment by ewilson-adhoc** [comment]
This issue appears to be completed, closing to clean up our backlog. Reopen if there is additional work that needs to be done.
