### ISSUE TITLE
Discovery Mapbox

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3178]
**Task**
- Discover the differences between the current Mapbox version and the new one to understand the complexities of upgrading
- As part of this work, will need to collaborate with the Mapbox support team

**Comment by mmiddaugh** [comment]
@brangi The Mapbox account manager suggested this [tutorial](https://docs.mapbox.com/help/troubleshooting/transition-from-mapbox-js-to-mapbox-gl-js/). Did you find this during your research? If it doesn't supply the info you need, please let me know and I will follow up with Sim. Thanks!

**Comment by brangi** [comment]
https://github.com/mapbox/mapbox-sdk-js (we are using this one)

The tutorial refers:
https://github.com/mapbox/mapbox.js  to https://github.com/mapbox/mapbox-gl-js  (the one in development)

**Comment by mmiddaugh** [comment]
Replied to Sim at Mapbox to clarify the nature of our question. 
This issue is still blocked pending more information.
