### ISSUE TITLE
[SCREENREADER]: Review sections with no header cause aria-label errors

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#318]
## Issue
Some of the Review Application accordions do not have headings. This causes the Edit buttons to read out `Edit undefined` for screen readers. Screenshot attached below.

## Acceptance Criteria
* As a screen reader user, I want to hear clear messages to help me understand what I'm going to edit if I press the focused button

## Prior Versions of this Issue:
* https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16755
* https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16088

## Environment
* MacOS Mojave
* Safari
* VoiceOver

## Affected Pages
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/review-and-submit

## WCAG or Vendor Guidance (optional)
* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

---
![screen shot 2019-02-05 at 3 07 37 pm](https://user-images.githubusercontent.com/934879/52305177-24a37b80-295a-11e9-824f-55f11ba2fbf6.png)

**Comment by peterhill-oddball** [comment]
Migrated to va.gov issue [1075](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1075)

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
