### ISSUE TITLE
[BE] Investigate LoROTA New Endpoint Payload for Browser Refresh Issue 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#31806]
## Description
Investigate payload for the new endpoint from LoROTA before refreshing appointments using CHIP

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Payload sorted out for integration with vets-api

**Comment by dillo** [comment]
This is a duplicate. Closing.
