### ISSUE TITLE
[FE] Determine possible test scenarios 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3180]
## Goal 

- need to determine all possible test scenarios that could happen . 

## Test Scenarios

Question from Erik - Do we want to prompt users that the system is changing their address input when the confidence level is 80% or higher according to what was entered and what is validated by the system?
We may not need to write this functionality, need to further explore this. 

## Definition of Done

- [ ] Review with Team on slack
- [ ] Approved by Team
- [ ] Close Ticket

**Comment by erikphansen** [comment]
I'm closing this ticket. The purpose of this ticket was to define _how_ the address comparison function would work. In my research of how the
