### ISSUE TITLE
Deliver FSR Training Video

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#31802]
## Issue Description
 An FSR Training Video was created as part of #29758 which now needs to be delivered into the right hands. 

## Acceptance Criteria
- [ ] Deliver FSR Training video via YouTube channel.  
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by rileyorr** [comment]
@denisecoveyduc we reviewed this in backlog grooming and weren't sure whether or not to close this since Troy is unfortunately not on our team anymore :'(

**Comment by denisecoveyduc** [comment]
@rileyorr Let me take this one and do a bit of follow up.. thanks for highlighting!
