### ISSUE TITLE
Update dev and staging certs

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#31803]
Why: The dev and staging certs here(https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/vets-api) expire on 10/25 at ~0716 AM EST.

- [x] request permission to access venafi. [Instructions](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)
- [x] Obtain certs from venafi for dev and staging sso saml signing certs. [Instructions](https://vfs.atlassian.net/wiki/spaces/OT/pages/1787953328/Venafi+Create+and+download+TLS+certificates)
- [x] Add private keys to SSM for dev and staging sso saml signing certs
- [x] Update this file to use the new certs: https://github.com/department-of-veterans-affairs/devops/blob/1b5b31ae544c75d2b047bdf9eaae92fb0f5afbcf/ansible/deployment/config/vets-api-server-vagov-staging.yml#L127 and dev equivalent
- [x] add public certs to https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/vets-api
- [x] add path to new private key (from SSM) here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-server-vagov-dev.yml and staging equivalent 
- [x] deploy changes to dev and pull down new metadata file, share with IAM team
- [x] deploy changes to staging and pull down new metadata file, share with IAM team
- [x] On the 25th of October remove pointers to "new", replace and rename with standard name, redeploy changes to dev and staging.
- [x] document how to do this in the future

Old dev meta file: 
`
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="_598c8041-7af0-4397-9bc3-9790c35bb48a" entityID="https://ssoe-sp-dev.va.gov">
    <md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIFODCCBCCgAwIBAgIHPQAAAEQQMTANBgkqhkiG9w0BAQsFADBKMRMwEQYKCZImiZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHzAdBgNVBAMTFlZBLUludGVybmFsLVMyLUlDQTEtdjEwHhcNMTkwODA3MTExNjAyWhcNMjExMDI1MTExNjAyWjCBqzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkRDMRMwEQYDVQQHEwpXYXNoaW5ndG9uMSgwJgYDVQQKEx9EZXBhcnRtZW50IG9mIFZldGVyYW5zJyBBZmZhaXJzMRAwDgYDVQQLEwdWQUNPIElUMRswGQYDVQQDExJzc29lLXNwLWRldi52YS5nb3YxITAfBgkqhkiG9w0BCQEWEnZhZ292ZGV2b3BzQHZhLmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMOXx9D4fzBqBH0f0sK91wJCwWaeMNmglSlQ4eWmZwkAoLLa2eDAUFbv2YuU4M4nws29m0tjgW881GFel+Es/TwG7WtFNx3OIRoGTWYxsgpY5TDBwo28kl5mf63QqXoXDbJQmIKs8GLM+MsLwEhmNUwD5cJ+yByv4Ckd9ef+O2Vjy0+Q16lOpdxOa3qKTL41lMCHheM0a9xql6X0kmoYLsVJzkHJPC+T66VSUXq4JaqvsoCmYIX3pEBReEfEcDY4js6aBDFylUv1Lw1GbWEtqDqp5f7oG9aL6abO7pIxgu/h61bomdlpSUSGPCTjPztySQ5qWCzGInynpE31LfSVUXkCAwEAAaOCAb8wggG7MB0GA1UdDgQWBBSN7ODPbrCRgzCtwS0i19IdfPzBZzAfBgNVHSMEGDAWgBQbbd/rPeXiDe8WsdDeX1gaVsvk7DBJBgNVHR8EQjBAMD6gPKA6hjhodHRwOi8vY3JsLnBraS52YS5nb3YvcGtpL2NybC9WQS1JbnRlcm5hbC1TMi1JQ0ExLXYxLmNybDB7BggrBgEFBQcBAQRvMG0wRwYIKwYBBQUHMAKGO2h0dHA6Ly9haWEucGtpLnZhLmdvdi9wa2kvYWlhL3ZhL1ZBLUludGVybmFsLVMyLUlDQTEtdjEuY2VyMCIGCCsGAQUFBzABhhZodHRwOi8vb2NzcC5wa2kudmEuZ292MAsGA1UdDwQEAwIFoDA9BgkrBgEEAYI3FQcEMDAuBiYrBgEEAYI3FQiByMMzgfnwBoGlnw2E4IEIhcKqSwaDgp9ggeCLUgIBZAIBGjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAjAKBggrBgEFBQcDATAdBgNVHREEFjAUghJzc29lLXNwLWRldi52YS5nb3YwDQYJKoZIhvcNAQELBQADggEBAEw5nLHnywPqwBT2x+Fy7Vyvu9U4MZQbkdq8b6fO4yl8HRYkSQOvBZ2Lp4cPMVNOt3oiBUVlmYHPMRVsK4TMvZX3IX49/vu+0LT8f6daby0QvNOWrnmNJwpfV8/EBxUj2F2k/9vBJH+lR4ZaKMtDnWYiZemgC2IuMTqT7AyqY6YGzIr3BvSb+46AId6j7klwA9exulpp+ICh+LZHhr4ekWTmywFowQag9wNDsOtSaJYMNY2WY1i3C2+VxN2PvaJAG1fJjQ7P7M6TtB7HgjyV6TXCCz5zMqAfjDc9IuOn8CE7CJR+OvLxD/O1c/qepnsJ0cAr517I85uanmwnsQ7tJ+c=</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:KeyDescriptor use="encryption">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIFODCCBCCgAwIBAgIHPQAAAEQQMTANBgkqhkiG9w0BAQsFADBKMRMwEQYKCZImiZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHzAdBgNVBAMTFlZBLUludGVybmFsLVMyLUlDQTEtdjEwHhcNMTkwODA3MTExNjAyWhcNMjExMDI1MTExNjAyWjCBqzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkRDMRMwEQYDVQQHEwpXYXNoaW5ndG9uMSgwJgYDVQQKEx9EZXBhcnRtZW50IG9mIFZldGVyYW5zJyBBZmZhaXJzMRAwDgYDVQQLEwdWQUNPIElUMRswGQYDVQQDExJzc29lLXNwLWRldi52YS5nb3YxITAfBgkqhkiG9w0BCQEWEnZhZ292ZGV2b3BzQHZhLmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMOXx9D4fzBqBH0f0sK91wJCwWaeMNmglSlQ4eWmZwkAoLLa2eDAUFbv2YuU4M4nws29m0tjgW881GFel+Es/TwG7WtFNx3OIRoGTWYxsgpY5TDBwo28kl5mf63QqXoXDbJQmIKs8GLM+MsLwEhmNUwD5cJ+yByv4Ckd9ef+O2Vjy0+Q16lOpdxOa3qKTL41lMCHheM0a9xql6X0kmoYLsVJzkHJPC+T66VSUXq4JaqvsoCmYIX3pEBReEfEcDY4js6aBDFylUv1Lw1GbWEtqDqp5f7oG9aL6abO7pIxgu/h61bomdlpSUSGPCTjPztySQ5qWCzGInynpE31LfSVUXkCAwEAAaOCAb8wggG7MB0GA1UdDgQWBBSN7ODPbrCRgzCtwS0i19IdfPzBZzAfBgNVHSMEGDAWgBQbbd/rPeXiDe8WsdDeX1gaVsvk7DBJBgNVHR8EQjBAMD6gPKA6hjhodHRwOi8vY3JsLnBraS52YS5nb3YvcGtpL2NybC9WQS1JbnRlcm5hbC1TMi1JQ0ExLXYxLmNybDB7BggrBgEFBQcBAQRvMG0wRwYIKwYBBQUHMAKGO2h0dHA6Ly9haWEucGtpLnZhLmdvdi9wa2kvYWlhL3ZhL1ZBLUludGVybmFsLVMyLUlDQTEtdjEuY2VyMCIGCCsGAQUFBzABhhZodHRwOi8vb2NzcC5wa2kudmEuZ292MAsGA1UdDwQEAwIFoDA9BgkrBgEEAYI3FQcEMDAuBiYrBgEEAYI3FQiByMMzgfnwBoGlnw2E4IEIhcKqSwaDgp9ggeCLUgIBZAIBGjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAjAKBggrBgEFBQcDATAdBgNVHREEFjAUghJzc29lLXNwLWRldi52YS5nb3YwDQYJKoZIhvcNAQELBQADggEBAEw5nLHnywPqwBT2x+Fy7Vyvu9U4MZQbkdq8b6fO4yl8HRYkSQOvBZ2Lp4cPMVNOt3oiBUVlmYHPMRVsK4TMvZX3IX49/vu+0LT8f6daby0QvNOWrnmNJwpfV8/EBxUj2F2k/9vBJH+lR4ZaKMtDnWYiZemgC2IuMTqT7AyqY6YGzIr3BvSb+46AId6j7klwA9exulpp+ICh+LZHhr4ekWTmywFowQag9wNDsOtSaJYMNY2WY1i3C2+VxN2PvaJAG1fJjQ7P7M6TtB7HgjyV6TXCCz5zMqAfjDc9IuOn8CE7CJR+OvLxD/O1c/qepnsJ0cAr517I85uanmwnsQ7tJ+c=</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
        <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://dev-api.va.gov/v1/sessions/callback" index="0" isDefault="true"/>
    </md:SPSSODescriptor>
</md:EntityDescriptor>
`

Old Staging metadata file:
`<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="_7736f867-3f85-4f92-9459-63c5bff117e5" entityID="https://ssoe-sp-staging.va.gov">
    <md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIFQDCCBCigAwIBAgIHPQAAAEQQWTANBgkqhkiG9w0BAQsFADBKMRMwEQYKCZImiZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHzAdBgNVBAMTFlZBLUludGVybmFsLVMyLUlDQTEtdjEwHhcNMTkwODA3MTEyNzUyWhcNMjExMDI1MTEyNzUyWjCBrzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkRDMRMwEQYDVQQHEwpXYXNoaW5ndG9uMSgwJgYDVQQKEx9EZXBhcnRtZW50IG9mIFZldGVyYW5zJyBBZmZhaXJzMRAwDgYDVQQLEwdWQUNPIElUMR8wHQYDVQQDExZzc29lLXNwLXN0YWdpbmcudmEuZ292MSEwHwYJKoZIhvcNAQkBFhJ2YWdvdmRldm9wc0B2YS5nb3YwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCrtjIbfaYTiNLNt5Kh0b54ypvQAEoUZhna+U6LUMXm7SWA2NuMYYTmq5ZjztaCvzuIX5GqLY7lkFZokKcyLLlH77VvhvaGlQA8uB81Cwt18IK1bMBpPfSSAIMFBAFCVc5+SIjPoxV51aG/eN4DAMaCA2E5W9uWQ1KFZCuwuaSkx1yUGIJQi73J4PwfejP8Id6zkogqqBr4iTK3a7nd8l/aHl00lh2HTHhVdBuy3rfq9YXHH7+FQgiLEr2HQqmhDIFzKZDbYU4ZaskzlEAZN7qE5MfY00HHZZr/BUTdYxkktKjdlq1h+9z8DpOBeiXUKETftAmvDtON25KePYaIZ5Q9AgMBAAGjggHDMIIBvzAdBgNVHQ4EFgQUUmBx1LrTLV9uoBDNaRM8mZqUzLUwHwYDVR0jBBgwFoAUG23f6z3l4g3vFrHQ3l9YGlbL5OwwSQYDVR0fBEIwQDA+oDygOoY4aHR0cDovL2NybC5wa2kudmEuZ292L3BraS9jcmwvVkEtSW50ZXJuYWwtUzItSUNBMS12MS5jcmwwewYIKwYBBQUHAQEEbzBtMEcGCCsGAQUFBzAChjtodHRwOi8vYWlhLnBraS52YS5nb3YvcGtpL2FpYS92YS9WQS1JbnRlcm5hbC1TMi1JQ0ExLXYxLmNlcjAiBggrBgEFBQcwAYYWaHR0cDovL29jc3AucGtpLnZhLmdvdjALBgNVHQ8EBAMCBaAwPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIgcjDM4H58AaBpZ8NhOCBCIXCqksGg4KfYIHgi1ICAWQCARowHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwEwIQYDVR0RBBowGIIWc3NvZS1zcC1zdGFnaW5nLnZhLmdvdjANBgkqhkiG9w0BAQsFAAOCAQEAdhEBHIs7lB4BY110S2KqjLW/m58uzujCbDcLrXJurvoLQjnmGHR4ZwvE70ypT5+ja3WFFKrjJ3++TvzgKZfekMBQpFNoUCwpaUZD4uJXr37IHXIsNX5fNkhRSH37RApORe/hys2VLzs+3Zp3Zm7z7/el25Pl53JIBOXMiBputURrrNjiG6M+9uOZwY2VrKOYuqy90xzJ/iKhVhwqlsBcDYuqzfduPtZjpHeVdYrNiHnGUqaQWjzDmDqM6d1CzT+vbL4RTLRRGEdNJyYivvuBz2/uwt5FiXgS0QhPKvA3kGVzBe2lkeATih2drsROl3BPBlgL5J69zNvQSS/MkBqcEg==</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:KeyDescriptor use="encryption">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIFQDCCBCigAwIBAgIHPQAAAEQQWTANBgkqhkiG9w0BAQsFADBKMRMwEQYKCZImiZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHzAdBgNVBAMTFlZBLUludGVybmFsLVMyLUlDQTEtdjEwHhcNMTkwODA3MTEyNzUyWhcNMjExMDI1MTEyNzUyWjCBrzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkRDMRMwEQYDVQQHEwpXYXNoaW5ndG9uMSgwJgYDVQQKEx9EZXBhcnRtZW50IG9mIFZldGVyYW5zJyBBZmZhaXJzMRAwDgYDVQQLEwdWQUNPIElUMR8wHQYDVQQDExZzc29lLXNwLXN0YWdpbmcudmEuZ292MSEwHwYJKoZIhvcNAQkBFhJ2YWdvdmRldm9wc0B2YS5nb3YwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCrtjIbfaYTiNLNt5Kh0b54ypvQAEoUZhna+U6LUMXm7SWA2NuMYYTmq5ZjztaCvzuIX5GqLY7lkFZokKcyLLlH77VvhvaGlQA8uB81Cwt18IK1bMBpPfSSAIMFBAFCVc5+SIjPoxV51aG/eN4DAMaCA2E5W9uWQ1KFZCuwuaSkx1yUGIJQi73J4PwfejP8Id6zkogqqBr4iTK3a7nd8l/aHl00lh2HTHhVdBuy3rfq9YXHH7+FQgiLEr2HQqmhDIFzKZDbYU4ZaskzlEAZN7qE5MfY00HHZZr/BUTdYxkktKjdlq1h+9z8DpOBeiXUKETftAmvDtON25KePYaIZ5Q9AgMBAAGjggHDMIIBvzAdBgNVHQ4EFgQUUmBx1LrTLV9uoBDNaRM8mZqUzLUwHwYDVR0jBBgwFoAUG23f6z3l4g3vFrHQ3l9YGlbL5OwwSQYDVR0fBEIwQDA+oDygOoY4aHR0cDovL2NybC5wa2kudmEuZ292L3BraS9jcmwvVkEtSW50ZXJuYWwtUzItSUNBMS12MS5jcmwwewYIKwYBBQUHAQEEbzBtMEcGCCsGAQUFBzAChjtodHRwOi8vYWlhLnBraS52YS5nb3YvcGtpL2FpYS92YS9WQS1JbnRlcm5hbC1TMi1JQ0ExLXYxLmNlcjAiBggrBgEFBQcwAYYWaHR0cDovL29jc3AucGtpLnZhLmdvdjALBgNVHQ8EBAMCBaAwPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIgcjDM4H58AaBpZ8NhOCBCIXCqksGg4KfYIHgi1ICAWQCARowHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwEwIQYDVR0RBBowGIIWc3NvZS1zcC1zdGFnaW5nLnZhLmdvdjANBgkqhkiG9w0BAQsFAAOCAQEAdhEBHIs7lB4BY110S2KqjLW/m58uzujCbDcLrXJurvoLQjnmGHR4ZwvE70ypT5+ja3WFFKrjJ3++TvzgKZfekMBQpFNoUCwpaUZD4uJXr37IHXIsNX5fNkhRSH37RApORe/hys2VLzs+3Zp3Zm7z7/el25Pl53JIBOXMiBputURrrNjiG6M+9uOZwY2VrKOYuqy90xzJ/iKhVhwqlsBcDYuqzfduPtZjpHeVdYrNiHnGUqaQWjzDmDqM6d1CzT+vbL4RTLRRGEdNJyYivvuBz2/uwt5FiXgS0QhPKvA3kGVzBe2lkeATih2drsROl3BPBlgL5J69zNvQSS/MkBqcEg==</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
        <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://staging-api.va.gov/v1/sessions/callback" index="0" isDefault="true"/>
    </md:SPSSODescriptor>
</md:EntityDescriptor>`

**Comment by nsoutouras** [comment]
@nsoutouras Split documentation to its own ticket

**Comment by joeniquette** [comment]
Completed documentation here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/How-To/Security/Rotate_certs.md
