### ISSUE TITLE
Veteran Crisis Line (VCL) Analytics Research

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31851]
## Issue Description
_Analytics research needed to determine user engagement for the Veteran Crisis Line (VCL) link on VA.gov pages_

## Research tasks
- [x] Request Analytics for VCL web component 
- [x] Assess user behavior interactions to include link clicks for each of the contact elements in the modal
- [x] Document findings in an easy to read summary readout in support of product decisions 
- [x] Present findings to PO/PM and PW team collectively

**Comment by cindymerrill** [comment]
Heard back today from Brian Martin from the Analytics team. He shared links to analytics, and I replied with some questions. I spent some time looking at analytics for VCL clicks and subsequent clicks from the landing page. All links are instrumented except for the SMS/text link, which Brian said that he could write a ticket for. I'll work on writing up what I've learned so far and hope to hear back from Brian soon.

**Comment by cindymerrill** [comment]
Started writing up research questions and findings. Requested additional analytics on veteranscrisisline.net from the Analytics team. Still waiting to hear back from the Analytics team on my followup questions in the previous Analytics ticket.

**Comment by cindymerrill** [comment]
Heard back from Brian Martin about GA data from veteranscrisisline.net...There is GA instrumentation, but our Analytics team didn't create it nor has access to it. 

If we know who owns this site, maybe I could reach out to ask for the GA data. I can write up what I want to know and why, and then we can discuss and maybe ask Dave for a contact. @brianalloyd

**Comment by cindymerrill** [comment]
Finished drafting report and shared it with another researcher for feedback. When I'm ready to share (hopefully tomorrow = Friday), do you (@brianalloyd ) want to take a look before I share on slack and @mention Dave?

**Comment by cindymerrill** [comment]
Shared draft report with @brianalloyd for review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/VCL-analytics-findings.md

**Comment by cindymerrill** [comment]
Revised report per @brianalloyd 's feedback, and then shared on public-websites slack @mention Dave

**Comment by cindymerrill** [comment]
Not sure if Dave will have questions. I'm guessing that he won't want a readout.

**Comment by brianalloyd** [comment]
Concur, think we can close out this ticket based on work completed.  Thanks @cindymerrill
