### ISSUE TITLE
HRT Clinician Recruitment 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31850]
## Issue Description
_Tasks needed in support of research project for Harassment Reporting Tool (HRT) initiative. This initiative has been paused; however, this ticket will be used to consolidate clinician recruitment contact efforts._

## Preparatory tasks
- [x] Email followup with social workers and clinicians who want to participate
- [x] Collect contact information and place in reference documentation for future reference
- [x] Close ticket

## Appendix
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
@cindymerrill closing this ticket based as I believe you've completed your work with clinician recruitment.

**Comment by cindymerrill** [comment]
@brianalloyd I'm still checking for emails from clinicians, but there haven't been any in a while. I'll need to reach back out to them when we resume the project, but that can be part of the research prep ticket later.
