### ISSUE TITLE
[Technical Discovery] Investigate unused KV pairs for react widgets in Drupal

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31865]
### User Story or Problem Statement

There are dozens of react widgets placed on detail pages across the CMS, primarily in Benefits Hubs pages and VAMC detail pages. The current implementation supports the `widgetTypes` defined [here in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/cta-widget/helpers.js)

The current experience for adding and editing these in the CMS is sub-optimal, prone to user error. [See relevant slack thread](https://dsva.slack.com/archives/C01H29ERVJ7/p1621270321259200)

<details><summary>Screenshots 
</summary>

![VA_Pittsburgh_Health_Care___Medical_Records_Office___Veterans_Affairs.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f79c98b3-bc3e-4ab5-9072-7e5982eeab66)

![Edit_Detail_Page_Medical_records_office___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/10637535-907a-4098-b57f-350c125e3700)

</details>

### Affected users and stakeholders

* Product teams who design and manage react widgets
* Editors who place react widgets into content

## Front end tasks
- [ ] Define what fields does CMS needs to support?
- [ ] Investigate unused kv pairs for react widgets in Drupal
- [ ] Sync with a content editor (Sitewide content Team)
- [ ] Investigate whether certain fields are used or can be deprecated

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
@tmac9494 you'll be primary on this ticket.  Just looking for tech discovery on this in support.

**Comment by brianalloyd** [comment]
@tmac9494 can you provide a narrative on this ticket to capture work done.  Also advise on status?

**Comment by brianalloyd** [comment]
@tmac9494 Update?

**Comment by tmac9494** [comment]
I started by trying to use basic searches to dig through the vets-website and content-build  repositories and looking for any instances that seem to be only getting registered and mark them as not found, also recorded the apps paths in the apps that appear to be active, the initial results are below.






------------------------
Apps Not Found:
------------------------

CHAPTER_31_WIZARD : chapter-31-Wizard
 - no matching search results found in content-build or vets-website repos


CORONAVIRUS_CHATBOT : va-covid-vaccine-updates-cta
 - no matching search results found in content-build or vets-website repos


DISABILITY_APP_STATUS: 'disability-app-status'
 - no matching search results found in content-build or vets-website repos


EDUCATION_APP_STATUS: 'education-app-status'
 - no matching search results found in content-build or vets-website repos
 - ! two instances in vw/applications/registry.scaffold.js


FORM_686_CTA : 'form-686-CTA'
 - no matching search results found in content-build or vets-website repos


HIGHER_LEVEL_REVIEW_APP_STATUS : 'higher-level-review-status'
 - no matching search results found in content-build or vets-website repos


HOMEPAGE_BANNER : 'homepage-banner'
 - no matching search results found in content-build or vets-website repos


MANAGE_VA_DEBT_CTA : 'manage-va-debt-cta'
 - no matching search results found in content-build or vets-website repos


OPT_OUT_APP_STATUS : 'opt-out-app-status'
 - no matching search results found in content-build or vets-website repos


POST_911_GI_BILL_STATUS_WIDGET : 'post-9-11-gi-bill-status'
 - no matching search results found in content-build or vets-website repos


VIEW_DEPENDENTS_CTA : 'view-dependents-CTA'
 - no matching search results found in content-build or vets-website repos




------------------------
Apps Found: 
------------------------



BURIALS_APP_STATUS : burials-app-status
 - vets-website\src\applications\registry.scaffold.json


CHAPTER_31_CTA : chapter-31-cta
 - vw/applications/static-pages/coe-access/createCOEAccess.js
 - vw/applications/static-pages/vre-chapter31/createChapter31CTA.js


CHAPTER_36_CTA : chapter-36-cta
 - vw/applications/static-pages/vre-chapter36/createChapter36CTA.js
 - vets-website\src\applications\static-pages\static-pages-entry.js


COE_ACCESS: coe_access
 - vets-website\src\platform\utilities\feature-toggles\featureFlagNames.js
 - vets-website\src\applications\coronavirus-chatbot\tests\config\data\chatbotResponse.json
 - vets-website\src\applications\static-pages\static-pages-entry.js


DEPENDENCY_VERIFICATION : dependency-verification
 - vets-website\src\applications\static-pages\dependency-verification\


DISABILITY_RATING_CALCULATOR : 'disability-rating-calculator'
 - vets-website\src\applications\disability-benefits\disability-rating-calculator\tests\00-all-fields.cypress.spec.js
 - vets-website\src\applications\disability-benefits\disability-rating-calculator\createCalculator.js


FACILITY_APPOINTMENT_WAIT_TIMES_WIDGET : 'facility-appointment-wait-times-widget'
 - content-build\src\site\facilities\facility_health_service.drupal.liquid
 - content-build\src\site\filters\liquid.js
 - ! should maybe be in not found list


FACILITY_DETAIL : 'facility-detail'
 -! should maybe be in not found list


FACILITY_LOCATIONS_LIST : 'facility-locations-list'
 - vets-website\src\applications\static-pages\facilities\facilityList.js


FACILITY_MAP : 'facility-map'
 - content-build\src\site\includes\image_and_static_map.liquid
 - vets-website\src\applications\static-pages\facilities\createFacilityPage.js


FACILITY_PATIENT_SATISFACTION_SCORES : 'facility-patient-satisfaction-scores'
 - content-build\src\site\layouts\health_care_local_facility.drupal.liquid
 - vets-website\src\applications\static-pages\facilities\createFacilityPage.js


FIND_VA_FORMS : 'find-va-forms'
 - content-build\src\site\layouts\va_form.drupal.liquid
 - vets-website\src\applications\find-forms\createFindVaForms.js
 - vets-website\src\applications\static-pages\static-pages-entry.js


FIND_VA_FORMS_INVALID_PDF_ALERT : 'find-va-forms-pdf-download-helper'
 - content-build\src\site\layouts\va_form.drupal.liquid
 - ! should maybe be in not found list


GET_MEDICAL_RECORDS_PAGE : 'get-medical-records-page'
 - vets-website\src\applications\static-pages\health-care-manage-benefits\get-medical-records-page\index.js


HEALTH_CARE_APP_STATUS : 'health-care-app-status'
 - content-build\src\site\paragraphs\react_widget.drupal.liquid
 - ! two instances in vw/applications/registry.scaffold.js
 - ! should maybe be in not found list


I_18_SELECT : 'i18-select'
 - vets-website\src\applications\static-pages\static-pages-entry.js
 - ! should maybe be in not found list


MAINTENANCE_BANNER : 'maintenance-banner'
 - content-build\src\site\components\banners.drupal.liquid
 - vets-website\src\platform\site-wide\banners\index.js


MEDICAL_COPAYS_CTA : 'medical-copays-cta'
 - vets-website\src\applications\static-pages\medical-copays-cta\index.js
 - ! should maybe be in not found list


OTHER_FACILITY_LOCATIONS_LIST : 'other-facility-locations-list'
 - content-build\src\site\layouts\locations_listing.drupal.liquid
 - vets-website\src\applications\static-pages\facilities\otherFacilityList.js


PENSION_APP_STATUS : 'pension-app-status'
 - content-build\src\site\tests\static-pages\static-page-widgets.unit.spec.js
 - ! two instances in vw/applications/registry.scaffold.js


REFILL_TRACK_PRESCRIPTIONS_PAGE : 'refill-track-prescriptions-page'
 - vets-website\src\applications\static-pages\health-care-manage-benefits\refill-track-prescriptions-page\index.js


RESOURCES_AND_SUPPORT_SEARCH : 'resources-and-support-search'
 - content-build\src\site\includes\support_resources_search_bar.drupal.liquid
 - vets-website\src\applications\static-pages\widget-creators\resources-and-support-search.js


SCHEDULE_VIEW_VA_APPOINTMENTS_PAGE : 'schedule-view-va-appointments-page'
 - vets-website\src\applications\static-pages\health-care-manage-benefits\schedule-view-va-appointments-page\index.js


SCO_ANNOUNCEMENTS : 'sco-announcements'
 - vets-website\src\applications\static-pages\school-resources\SchoolResources.jsx


SCO_EVENTS : 'sco-events'
vets-website\src\applications\static-pages\school-resources\SchoolResources.jsx
 - ! should maybe be in not found list


SECURE_MESSAGING_PAGE : secure-messaging-page
 - vets-website\src\applications\static-pages\health-care-manage-benefits\secure-messaging-page\index.js


SIDE_NAV : 'side-nav'
 - content-build\src\site\navigation\facility_sidebar_nav.drupal.liquid
 - vets-website\src\applications\registry.scaffold.json
 - vets-website\src\platform\site-wide\side-nav\index.js


THIRD_PARTY_APP_DIRECTORY : 'third-party-app-directory'
 - vets-website\src\applications\third-party-app-directory\constants\index.js
 - vets-website\src\applications\third-party-app-directory\createThirdPartyApps.js


VET_CENTER_HOURS : 'vet-center-hours'
 - content-build\src\site\includes\vet_centers\hours.liquid
 - vets-website\src\applications\static-pages\facilities\createVetCentersHours.jsx


VET_CENTER_NEARBY : 'vet-center-nearby'
 - content-build\src\site\includes\vet_centers\nearby.liquid
 - vets-website\src\applications\static-pages\facilities\vet-center\createNearByVetCenters.jsx


VIEW_PAYMENT_HISTORY : 'view-payment-history'
 - vets-website\src\applications\static-pages\cta-widget\ctaWidgets.js
 - vets-website\src\applications\static-pages\view-payment-history\createViewPaymentHistoryCTA.js
 - vets-website\src\applications\static-pages\view-payment-history\ViewPaymentHistoryCTA.js


VIEW_TEST_AND_LAB_RESULTS_PAGE: 'view-test-and-lab-results-page'
 - vets-website\src\applications\static-pages\health-care-manage-benefits\view-test-and-lab-results-page\index.js
 - ! should maybe be in not found list



------------------------------------
Not unique enough for simple search
------------------------------------

CTA : cta
EVENTS: events

@brianalloyd @kelsonic

**Comment by brianalloyd** [comment]
Thanks for the technical discovery on this, I'm going to close out this ticket and connect to a new ticket for implementation which I would like to review in grooming in order to weigh risk factors.
