### ISSUE TITLE
[Typeahead 2.0] VSA-QA Test Plan

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#31863]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/product-outline.md) [Typeahead 2.0 initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/typeahead/initiatives/typeahead_2.0/initiative_brief.md)
- Product/Feature Epic: \[provide link]
- Product/Feature Copy deck(s): \[provide link, or type "In Design prototypes"]
- Product/Feature Design prototypes: [Design Prototypes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30197#issuecomment-934673872)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Megan Gayle
Content/IA: 
Front-end: Sam Suddath
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \[provide link]

[Staging link](https://staging.va.gov)

## How to configure this issue

- [ ] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@LindaLi123 , QA test-runs are now completed.  QA-artfiacts links are below and also updated in Staging Review ticket #31868.

96% Passed - 1 defect logged: #32485

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/2536)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/150&group_by=cases:section_id&group_id=612&group_order=asc&display_deleted_cases=0)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/278)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/279)

**Comment by srsuddath** [comment]
@tlei123 can we close this ticket now that the defect was remedied?

**Comment by tlei123** [comment]
Bugfix validated.  Closing this now.  Sorry, @srsuddath !  Been heads-down on other stuff.
