### ISSUE TITLE
Audit of current use of Statuses on cards

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#31862]
Audit of current use of Statuses on cards as part of effort to create a pattern to add the DS. 

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/387

Natalie - add any tasks for this issue as you see fit.

**Comment by GnatalieH** [comment]
Mural board of audit is [at this link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1635796660299/abfd719db54ed49269dbf8d4690e05ad774c6e35?sender=u851998f98038e0f1e2da4592).
