### ISSUE TITLE
[Design] [Discovery] Should we move profile editing from inline to editing on new page?

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31876]
## Issue Description
Design exploration around whether we should move profile editing from in-line editing to editing on a new page? This would be a big design effort, so if we pursue it, it'll likely turn into an epic at some point.  For context: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31237#issuecomment-947856877

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Noting that there is a pattern that has been introduced to the Experimental Design System - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/619

**Comment by SKasimow** [comment]
@andaleliz - should this be closed out given current research to answer this question?

**Comment by andaleliz** [comment]
Yes this is now a duplicate of the research we're doing.
