### ISSUE TITLE
Business intake form for Digital GI Bill

### ISSUE THREAD

**Issue by RileyRPM** [department-of-veterans-affairs/va.gov-team#31896]

**Comment by miabecker** [comment]
Hi Filip,

 

Here are the environment and attached is the list of emails we need to get setup for our testing. Please let me know if you have any questions. Thanks

 

# DEV (Test Account)

AFS001

AFS002

AFS003

 

# STAGE

IVV001

IVV002

UAT001

UAT002

 

# PROD (Standard Prod Account)

PROD

 

 

Sincerely,

 

-Umer Hashimi

**Comment by miabecker** [comment]
Hi Umer,

I've created services for you:
env	service name	service id
AFS001	VBA Education - AFS001	da5fbe25-468c-4226-b26d-7bcaf72f642d
AFS002	VBA Education - AFS002	f87f7493-ceb8-43de-a838-0b36ac29b7b9
AFS003	VBA Education - AFS003	a3330dc2-7f40-417e-97b2-9550ca379166
IVV001	VBA Education - IVV001	113bba63-90c4-419b-a77a-60aa18b55ad5
IVV002	VBA Education - IVV002	a190be7f-2dcb-48ee-9b68-54d8b3924e45
UAT001	VBA Education - UAT001	09ae062e-773c-4531-9067-eff0b129e8a7
UAT002	VBA Education - UAT002	254cacf7-515a-4fe4-916c-5cb4a571172b

They all have the requested whitelist and your user has permissions to manage these services in the UI.

You can also manage the whitelist and callbacks yourself by sending API requests.
I can demonstrate how you can do that on a quick video call.

I'll send over API keys for these services over encrypted email.

Regards,
Filip Fafara

**Comment by RileyRPM** [comment]
Hey @miabecker ... I was talking with Umer and our demo and testing are looking good. Our customers in EDU are super happy with the product. Question to your team: Could we get our production environment credentials so that we can set up our templates and callbacks there?

**Comment by miabecker** [comment]
@RileyRPM we are working on this afternoon and will let you know when we are done!

**Comment by RileyRPM** [comment]
Very cool! Thanks @miabecker

**Comment by philherbert** [comment]
Hi @RileyRPM - here is the Service ID for VBA Education in Prod - `4266121d-f301-434b-a97f-8ec1597143e9`

We'll send the API key to your team in a secure email - in the meantime, please let Umer and Won know that they should log into our Prod environment at https://notifications.va.gov. They won't see anything initially, but once they've logged in, I can assign them to the new service.

**Comment by RileyRPM** [comment]
Thanks @philherbert ... I'll pass that along!

**Comment by miabecker** [comment]
@RileyRPM just checking here - any updates on a go live date?

**Comment by RileyRPM** [comment]
Hey @miabecker ! Sorry. I was out for the holidays. Yeah. We're going live next weekend.

**Comment by miabecker** [comment]
@RileyRPM just wanted to check in you know that the VA is closed for MLK day, Monday January 17th so just wanted to check in. Also, we typically don't like to go live on the weekends as that requires our team to be on call on the weekend – which we avoid. Let me know if a call would be helpful.

**Comment by RileyRPM** [comment]
I think a call could be helpful just so that we can know what level of effort y'all would need. 
We HAVE to go live on weekends because of the claims processing piece - that needs to be done during off-hours. Our code updates should take a ton of time BUT we then have a couple jobs to run that are expected to take about 40 hours. We'll start those jobs on Saturday with the expectation that they could run clear into Monday so the MLK holiday actually gives us the opportunity to run our jobs in production while VA is closed  and not processing claims. I don't expect that we'll need to send a VANotify message until Tuesday if that helps. Either way... I totally support a call to set expectations. You want me to set it up?

**Comment by miabecker** [comment]
A call would be great - what works for you this / early next week?

**Comment by RileyRPM** [comment]
We could do tomorrow at 8:30 Eastern to 10:30 Eastern. Can also do Monday from 9 to 12:00 or from 2:00 to 3:30

I also have a Deployment tabletop scheduled for 10:30 on Tuesday if you want to attend that. We do that with all of our external stakeholders on our big releases.

**Comment by miabecker** [comment]
I think the table top will be perfect. Thank you! Also if you can send over any estimates of volume you think you might have for Tuesday/next week that would be great!
