### ISSUE TITLE
Implement new Lighthouse v1 services endpoint (CMS -> Lighthouse -> Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31901]
## Issue description 
The Lighthouse Facilities API is being redesigned to incorporate new features, including health services data from CMS. The Facilities team will need to keep pace with the changes to the existing V0 API and plan for the transition to V1 so that we can maintain functionality and leverage the new available data.

[Facilities API v1 Endpoint Design.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7400665/Facilities.API.v1.Endpoint.Design.docx)

## Tasks

Prepare for the following API changes, as necessary (details may be found in the attached design doc)

### Data Formats
- Deprecation of the application/geo+json data format 

### Endpoints

- Opening up the /facilities search endpoint which will allow combining search terms or providing no terms at all.
- Removal of the dedicated /all endpoint. 
- Modification of the the /nearby endpoint to no longer utilize the Bing Maps API  for address to geolocation conversion. .
 - Loss of the ability to search by full Street Address 
- Facility type additions  The full list will now be:
   - Health (vha)
    - Benefits (vba)
    - Vet_Center (vc)
    - Cemetery
       - National (nca)
       - State/Local/Tribal (nca_s)
   - Community Access Point (cap)

### Detailed Services
- 
Removal of the detailed_services structure in the Facilities API responses. Data will be available in the new /service endpoints.

### Other Minor Changes
- Consistency of display for “hours” 
- The operationalHoursSpecialInstructions field will now be a list of individual note strings. 
- Field names are now camelCased instead of snake_case. 
- The “active_status” field will be removed from the Facility results. T
- Wait times will be moved out of the Facility responses and into the new  Service response for the relevant service types.
- The list of services in the Facilities response will now be a list of objects instead of a list of strings.

**Comment by davidmpickett** [comment]
Duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12921
