### ISSUE TITLE
Analytics Implementation or QA Support for Testing Tools Team - Domo Dashboarding

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#31907]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - VSP Testing Tools Team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - N/A
    
- **When is the launch date?**
    - N/A

- **What interactions need to be tracked?** 
Good afternoon, Analytics Team! Looking for some answers and possibly some access to some data for our Domo Dashboarding effort. There's a number of metrics we're looking to track:
1) Average page render speed per application (and possibly just an overall average for the whole va.gov site)
2) Most often used viewport sizes both for the platform as a whole and each individual application
3) How many unique visitors each application gets per day
4) Number of events that have been triggered by application interaction, per application
5) Average time a user spends on each application before navigating away
6) % of users reaching the "finish line" of each application's story

Given these metrics, my questions would be:
1) Are we tracking these data points already? If so, are they being stored anywhere in BigQuery as well already?
2) If they are being stored in BigQuery, is there any way we can gain access to it on our end? I believe our BigQuery access now is currently limited to just the testing tools team data (at least my account is).
3) If all of the above are possible, would we need to do anything additional as far as creating a data connection to these BigQuery tables in Domo, or is our existing connection to BQ good enough as long as our account has access to the new data?
4) If the answer is no to any of the above, is there any way we could go about getting this data?

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - N/A

- **Any additional comments**

    - After looking through Domo, we've noticed that many of the data points we are looking to get ahold of, are already on the analytics KPI dashboards in Domo. We are open to the idea for making everyone's life easier of piggy-backing off the existing cards and making duplicates to our dashboards (we would use `Save As` to disconnect the cards) but they would just share the existing data set, if that's something you all are comfortable with. 

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by bsmartin-ep** [comment]
Hey @CBonade - I've granted read-only rights to your team's service account. You should be able to create Domo data sources that select into our primary GA session tables.

I'll put together some basic queries selecting the metrics you need and then we can fine tune the frequency, dimensions, metrics, and structure (pre-aggregated vs hit-level data).

> Average time a user spends on each application before navigating away

Would this be time on page(s) for users who don't finish the form successfully?  Or everyone?

> % of users reaching the "finish line" of each application's story

Any preferred scope for this?  In one GA session?  Over the lifetime of the user data?  Or some `n` amount of days?

**Comment by CBonade** [comment]
@bsmartin-ep Hey there, thanks for the followup! Talked to the team this morning:

> Would this be time on page(s) for users who don't finish the form successfully? Or everyone?

Would it be possible for us to do both, in separate queries so we can chart them separately?

> Any preferred scope for this? In one GA session? Over the lifetime of the user data? Or some n amount of days?

Lifetime of user data, please.

Thanks so much for all the help with this!

**Comment by bsmartin-ep** [comment]
Hey @CBonade - did you need any further assistance with this ticket or the queries we sent over?

**Comment by CBonade** [comment]
We're all good here for now. Once we start getting feedback on our dashboard there may be additional requests, but for all intents and purposes, this issue is resolved. Thank you!
