### ISSUE TITLE
Facilities support for Cerner roll-out

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31900]
## Issue Description
As a Veteran registered for care at a VA Medical system implementing the Cerner portal, I need a seamless experience. 

This epic to collect work needed to support the Cerner implementation as it relates to the Facilities suite of products

**Comment by davidconlon** [comment]
We have an opportunity to create a SSOT based on the content in drupal as part of this epic that would facilitate the migration of VAMC product, React widgets, and possibly some stuff in the Authenticated experience that will make this all easier. This effort is mostly on the CMS team (I think) but involves cross-team collab.
