### ISSUE TITLE
Pharmacy Training

### ISSUE THREAD

**Issue by BensonWD** [department-of-veterans-affairs/va.gov-team#31914]

**Comment by BensonWD** [comment]
Pharmacy Powerpoint briefing slides are ready, but need a date for delivery. As mentioned previously, desired attendee list is needed to ensure presentation goes well. **Determination needs to be made if this will be held via the VEText Teams channel or via ad hoc chat.**

**Comment by BensonWD** [comment]
Pharmacy Presentation. Presenter, **if using Dev Env**, should ensure that date ranges reflect current data set for reports portion of demo, and that sample patient selected has actual prescription. Not a problem if using production env.[https://app.zenhub.com/files/133843125/e922be78-28e3-4289-a10a-20c3f4aa1ca7/download](https://app.zenhub.com/files/133843125/e922be78-28e3-4289-a10a-20c3f4aa1ca7/download)

**Comment by BensonWD** [comment]
[https://app.zenhub.com/files/133843125/20e59e7b-96d6-4285-8312-3b6b5ad0abfc/download](https://app.zenhub.com/files/133843125/20e59e7b-96d6-4285-8312-3b6b5ad0abfc/download)

**Comment by lindsay-insco** [comment]
Materials sent to Shane for final review - live portal demo included but complete
