### ISSUE TITLE
[PM] Onboarding: Heather Justice

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31921]
## Background

Welcome, Heather! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks (internal mtgs can come from Ad Hoc account/be on Google meet):

- [ ] Erik Hansen (Out of the office until 11/17, have agreed to meet when he returns)
- [x] Taylor Mitchell
- [x] Lihan Li
- [x] Tressa Furner
- [x] Liz Lantz

Shared support team members:
- [x] Tze-chiu Lei (QA) (sched 11/3)
- [x] Josh Kim (a11y) (sched 11/4)
- [x] Angela Fowler (a11y) (sched 11/2)

### Meetings with Samara & AJ

- [ ] Project overview call (we can have more than one of these if necessary)
- [ ] PO/PM roles and responsibilities call 

### Onboarding to ceremonies

- [x] Observe standup and be ready to run once AJ goes on leave (be able to fill in for AJ as needed until then)
- [ ] Observe sprint planning and then be ready to manage once AJ goes on leave
- [x] Observe grooming and then be ready to manage once AJ goes on leave
- [x] Observe Team of Teams and then be ready to give the update once AJ goes on leave

### Products/Projects

You'll talk about these more formally in your meeting(s) with Samara and AJ, but here are some helpful resources to review in the meantime:

#### Current/Active work
**Notification Preferences**
_Status: phased launch began in sprint 60, will be handed off to Marci once we get past full launch_
- [Product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences)
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences#communications-permissions-notification-preferences-product-outline)
- [Project epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18071)

**My VA 2.0 Enhancements**
_Status: in progress, scoping MVP + discovery_
- [Product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/education)
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/education#project-outline-add-education-to-the-my-va-dashboard)
- [Project epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31611) 

**On-site Notifications**
_Status: in progress, scoping MVP + discovery_
- [Product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications)
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/README.md#alerts--notifications-on-vagov-on-site-notifications)
- [Product epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30611)

**User Role Research**
_Status: in progress, research/discovery only at this point_
- [Product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/user-roles)
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/user-roles/discovery#project-outline-user-roles-and-permissions-discovery-research)
- [Product epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30894)

#### Previous work

**My VA 2.0 Redesign**
_Status: live! launched July 2021_
- [Product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#product-outline-my-va)
- [Product epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6326)

**Comment by hdjustice** [comment]
Completed most tasks, split into a new ticket for the next sprint #32946 .  Closing this ticket.
