### ISSUE TITLE
SMS Content for Veteran Insurance Check

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#31946]
As a veteran, I want to know if I need to update insurance so that I can speak with staff to update accordingly for my scheduled appointment prior to checkin. 

**Background**
We need to speak with Content team about the appropriate verbiage to use when notifying a veteran they must update insurance prior to checking in.

A insurance check is taking place on the backend that will let CHIP know if the veteran is flagged in Vista and needs insurance verifications. We need to make sure we deliver the appropriate SMS response when a veteran tries to checkin to make sure they see staff prior to completing checkin. 

**Acceptance Criteria**
- [x] Take to Content team
- [x] Provide recommendations to Product and team in the following thread :
https://dsva.slack.com/archives/C022AC2STBM/p1634646403028500

**Comment by julieadair1** [comment]
https://github.com/department-of-veterans-affairs/chip/issues/150#issuecomment-956419464

^CHIP ticket

**Comment by kristenmcconnell** [comment]
Final wireframe: 
https://www.sketch.com/s/61f31b11-e47d-4706-82d0-981602c66f33/a/PGvWabv
