### ISSUE TITLE
Access for BJ McCotter

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va.gov-team#31942]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

BJ McCotter

### Your Email

bj.mccotter@adhocteam.us

### Name of Your Team

PST - Platform Spike Team 3

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEKy4w9ZrYjpFII0bxhkPwjhDJ86t7VNo+sVDplrcYc+s4W8nXGk5E3GcTvS9n7OpHzA27ZZH3ROF3iYqw6jfeL5mAFR8F/rmyCG6mttK+bYfbByeMf8r5MVlCzpyas8+GUQMsiAdl+rtQc938/NXNOmTDMtQPo4qYXy/dO9nbMDIBfxaz+xGspWXDzZpgn3JREzG3Q5mYV5fRrxSpGaWN7d49TrB5OGFBgKca7fqYHy5Iw/gqMOpYTLuwkjam0faA01U0zKcrHE/YBPf6cJ2QGcd7joYJJ4cH+a6nPBSbmjxrResnh1pEv3RPRtQlVmtC6oWMxnc1CV128Dwowj+25gIEF7mfuIl6QeGv9WFmY9bgI04EqLQ9f84fQ6+hVzDxZRg36vLj4d2aZs7G9L4HDtyKXX641R2+5EeYHnR5KyqnXdL07kVLgwHktPiYxzBNMcSTHp97j09v1KOoVikgrqtn5ZA3UqlZle0HmC1OQhzMNbtwKiQ8WyLR0qKS3sE= bjmccotter@BJ-McCotter-MBP

### Desired AWS Services

AWS Services Needed

1. EKS - To access the kubernetes cluster for deployments
2. ECR - Access the existing containers and be able to deploy new containers to registry
3. IAM - For permissions into and around the clusters
4. Cloudwatch - To access current monitoring and add addition for new services

**Comment by mchelen-gov** [comment]
@omgitsbillryan EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by jsgarmon** [comment]
@bjmccotter7192 : since you're the first member of the FLT spike team we're settings up AWS permissions for, can you say more about what specific permissions you'll need to what specific resources? For example, in ECR, what repos do you need to push new images to, or do you need to be able to create new repos?

**Comment by bjmccotter7192** [comment]
@jsgarmon So I originally request access while waiting for the team to finalize so at this moment I don't have a specific repo but would probably like to create containers and push to the registry eventually. This all depends on the business needs of updating the current forms system. Most of our work on this team has been in vets-website and formulate so I can see us having access to see those repos to start.

**Comment by jsgarmon** [comment]
AWS access granted and temporary login credentials sent. Changes to AWS permissions can be requested through the  #vfs-platform-support Slack channel.
