### ISSUE TITLE
[Design] Update UX Prototypes for NOK - Phone Numbers 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#31949]
As a Veteran, I want to review my next-of-kin information so that I can ensure the information listed is correct, specifically phone numbers. 

**Background**
Current prototypes show mobile phone for NOK< however the payload we get from CHIP only has "Phone" and "Work Phone" listed for NOK. 

We need to update the UI prototypes to remove the mobile phone and add the two we receive from CHIP. 

**Acceptance Criteria**
- [ ] Remove Mobile from prototypes for NOK
- [ ] Add "Phone" for NOK
- [ ] Add "Work Phone" for NOK
- [ ] Review with team (UX, Product)

**Comment by ytsaoca** [comment]
Link to the prototype: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/bgdyx7j
