### ISSUE TITLE
Create app name lookup and data assignment logic

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#31952]
# Description
In order to standardize data in our dashboard, we'll need a way to attach the names of applications to the data so it can all be associated properly. This will need a way to look up applications based on directory structure and then add the app names directly to the row data. A potential solution is to have a master JSON file that associates human-readable apps with slugs in our dashboard repo, aside from any logic that actually looks it up and adds it.

## Acceptance Criteria
- [ ] Automatically generated product / application list is updated in BigQuery upon each CI workflow execution in `vets-website`
- [ ] Verify that the product names automatically generated by this mechanism match expectations of a human brain

**Comment by pjhill** [comment]
Hooray manifests! Are there any post-MVP tasks for this that would increase the integrity of the data being extracted from the manifests? Should we document anything on Platform Website with regards to what we expect the contents of `manifest.json` to be?

**Comment by CBonade** [comment]
That's a great point. I think some addition to our best practices documentation about what a manifest should be/contain would be great. Do we think at some point, maybe a little further into the dashboard coming together, we can preview it to teams and recommend that they create a manifest if they'd like their application to have data included in our dashboard?

I think completeness of manifests for both parent applications and sub-applications is the biggest post-mvp step I'd like us to take - whether that's getting teams to create them or us creating a minimal manifest just to get the data complete.

**Comment by pjhill** [comment]
We can pursue a solution for mapping QA data to products in a future iteration.
