### ISSUE TITLE
Update Vaccine - Choose Facility Alert Message

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#31959]
## Description
Update the choose facility page to latest guidance on vaccine content.

**Current Alert Message:**
<img width="679" alt="Screen Shot 2021-10-22 at 3 28 09 PM" src="https://user-images.githubusercontent.com/90797205/138787327-ab0ad1b0-f6d5-4c49-81ee-5ca56ef34535.png">

## Acceptance Criteria
Given the COVID-19 new appointment workflow, 
When user enters Choose the facility page, 
Then page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-choose-facility.md)

Given the new appointment workflow,
When a user enters the Choose the location page, 
Then page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-choose-facility.md)

### Design Assets
Page structure guide for [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/content) section reference. 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by jenniemc** [comment]
Hi @ldelacosta, you put a call to attention around the informational text box. Did you want to update the info content box "Some COVID-19 vaccines require 2 doses" or delete it? The [vaccine facility copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-choose-facility.md) does not reference anything pertaining to "Some COVID-19 vaccines require 2 doses" or anything similar.   
cc: @vbahinwillit

**Comment by ldelacosta** [comment]
Hi @jenniemc - we would like to remove the blue box from the page. The copy doc should not have the specifications. Thanks!

**Comment by jenniemc** [comment]
Hi @vbahinwillit, look like the blue box will be removed. See Leah's message.

**Comment by ldelacosta** [comment]
Validated the copy doc changes in staging site. 

**_New appointment Covid-19 vaccine workflow:_** 
![Screen Shot 2021-12-08 at 8.59.58 AM 1.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c1a704b0-428e-4808-998c-1ee9dc40540c)

**_New appointment workflow:_** 
![Screen Shot 2021-12-08 at 8.59.58 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/db243985-e1c6-473b-9b0f-9e4eae864e26)
