### ISSUE TITLE
Google Analytics: Create GA Derived User Activity Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31967]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will display the number of events triggered over a period of time by my application. This would give a good indication of how easily interactable our applications are and if users are finding their way around it easy enough. It also could indicate struggles to use an application if a simple application has more events than anticipated._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects the number of events triggered, broken down by application, over a selected time period
    * This data requires the prior Google Analytics data task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting the number of events triggered, over a period of time, broken down by application on va.gov_

**Comment by CBonade** [comment]
This card has to be placed on hold awaiting access being granted to the forms table for our service account. I've filed a support request for this access.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1818697362

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/ae36b852-aae0-4dab-b535-cc2f1237d2c9)

All good here!

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1622437265

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/78fa740e-4e32-40dd-b0ac-e4a8cf1d8365)

All good here!

**Comment by pjhill** [comment]
For now this visualization is limited to form activity, right? Did we develop a plan to expand the scope of user activity beyond forms hosted on VA.gov?

**Comment by CBonade** [comment]
There's no current plan that we have in place to solve for this. That's not to say that we can't figure something out, however, currently analytics only tracks the activity from the forms and not every application on the site.

**Comment by pjhill** [comment]
Fair -- MVP done
