### ISSUE TITLE
Google Analytics: Create GA Derived Render Speed Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31966]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will display the average page render speed over a period of time for my application. This metric is the number one cause of losing users on a site, and therefore is extremely important for us to have tracking to be able to quickly address any pages that are taking too long to load._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects average page render times broken down by application, over a selected time period
    * This data requires the prior Google Analytics data task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting the average page render times for each application on va.gov_

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/897851565

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/6ce09241-bf14-4624-816f-21f338e5a187)

All good here!

**Comment by pjhill** [comment]
Now with more accurate numbers! This is definitely one of the more immediately accessible visuals on the dashboard.
