### ISSUE TITLE
Google Analytics: Create GA Derived User Journey Completion Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31973]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show how many users (in the form of a percentage) are reaching the end of our application. This will ensure that our application is easy to use, engaging, and runs smoothly._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects a percentage of users that reach the end of the application workflow.
    * This data requires the prior Google Analytics data task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting the percentage of users that reach the end of applications across va.gov_

**Comment by CBonade** [comment]
This card has to be placed on hold awaiting access being granted to the `forms` table for our service account.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1818697362

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/ae36b852-aae0-4dab-b535-cc2f1237d2c9)

All good here!

**Comment by pjhill** [comment]
Ditto the other GA visual -- this is for forms only based on the dataset available from GA. Do we have a plan to grab data for products other than forms?

**Comment by pjhill** [comment]
Fair points, I think we can close this out in its MVP state. Iterations will involve some research about the gold-plated end state.
