### ISSUE TITLE
BE Unit: Create Back-end Unit Test Top 5 Most Failing Tests Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31988]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show how what the top 5 tests that are failing regularly are. This should give us some insight into our biggest areas of opportunity to improve VA.gov._

## Tasks
- [x] Create a Domo Dashboard Card that reflects what the top 5 failing tests are in our back-end unit testing suite.
    * This data requires the prior `Ingest Back-end Unit Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [x] _A dashboard card exists reflecting what the top 5 failing tests are in our back-end unit testing suite provides_

**Comment by ddzz** [comment]
Dashboard has been updated: https://va-gov.domo.com/page/2049645635

**Comment by pjhill** [comment]
Nice, how is this being evaluated? Over what period of time are these failures? The descriptions of the tests are pretty good, but being able to drill into them for more details would be sweet.

**Comment by pjhill** [comment]
The top five failures card is a pretty good visual. The names of the tests are a bit... long. We may want to trim them somehow in a future version of the visual, but this is good for a first pass.
