### ISSUE TITLE
[Design] MPI "bio" info to non-editable fields for authenticated users on 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#31989]
## High Level User Story
As a Veteran, I need to avoid inappropriate modifications to MPI so that my data remains accurate.

>If the user is authenticated, we pre-populate some of the fields for them, based on the values in the Master Person Index (MPI). However, these fields are editable, and may be changed by the user.

## Goals
- Prevent unintended/inappropriate modifications to MPI when filling out the 10-10ez.
- Provide user with guidance for next step if info is wrong

## Acceptance Criteria

- [x] Create design 
- [ ] Submit for design intent _(If necessary)_
- [x] Write tech specs for FE #32137
- [ ] Work with PM to monitor analytics for changes after implemented

**Comment by MickinSahni** [comment]
Standup thoughts:
- closing this out (with understanding of future HEC changes in a sep ticket)
- given priority, will likely move forward on normalizing with all other forms that already do this (i.e. no collab cycle right now)
