### ISSUE TITLE
BE Unit: Create Back-end Unit Test Code Coverage Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31987]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show how what percentage of our code is currently being covered by our back-end unit testing suite._

## Tasks
- [x] Create a Domo Dashboard Card that reflects what percentage of our code is covered by our back-end unit testing suite.
    * This data requires the prior `Ingest Back-end Unit Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting the percentage of code coverage that our back-end unit testing suite provides_

**Comment by pjhill** [comment]
Consider recommending that we block <90% coverage in BE unit tests.

**Comment by pjhill** [comment]
Default SimpleCov report breaks up tests into the below --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/f3c6fc21-5c75-44ac-954b-9b5691a43c4d)

**Comment by pjhill** [comment]
Yesterday: SimpleCov wrangling -- 60MB HTML file (ew)
Today: continuing to wrangle the simplecov report

**Comment by pjhill** [comment]
Yesterday: Data pushed to BQ from hugemongous HTML (60MB)
Today: Play with visualizing all ~30 groups in a card. If it's too ugly then perhaps we simplify the grouping.

**Comment by ddzz** [comment]
Dashboard has been created: https://va-gov.domo.com/page/2049645635

PR: https://github.com/department-of-veterans-affairs/vets-api/pull/8864

**Comment by pjhill** [comment]
Looks good! Joe might have some visual feedback tweaks, but this ticket is done. Future tweaks to visualizations can be worked under a separate ticket.
