### ISSUE TITLE
E2E: Create E2E Flakiness Coverage Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31993]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show a percentage of our E2E testing suite that exhibits flakiness. Flakiness is defined by Cypress dashboard as tests that may fail at first in a workflow but then pass on a retry in the same workflow. Retries on failure are a built-in feature of Cypress, so we should be able to enable this and then must figure out a way to track these incidents._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what percentage of tests are exhibiting flakiness on average in our E2E testing suite.
    * This data requires the prior `Evaluate Ingestion of End to End Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what percentage of tests are exhibiting flakiness on average in our E2E testing suite._

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1521020182

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/cb498e96-44b7-4958-9c80-af9452e736f7)
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/5aa70c92-b903-449b-9e61-cc993d52be95)
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/199a1a0d-f229-46cd-be6c-5f49ac39baa6)

This card sources off a brand new table in BQ regarding test retries and flakiness. The chart here drills down to 3 different levels. It starts at the app level, drills to the spec (where the vertical bar will show which tests are responsible for the retries) and then the specs drill down into individual tests. 

What's currently displaying here is my test data. This will exist in this state until we have some actual flaky data come in, as after I cleared the table following my testing, Domo will not allow an update of a data set to an empty set when it prior had data. Once we have real flaky data, it should replace this automatically. Full disclaimer: I only had one bar, one spec worth of data to test this with. We may need to adjust this chart some once there's some real data here to work with.
