### ISSUE TITLE
E2E: Create E2E Suite Execution Time Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31996]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show average execution times for my product's E2E test suite. This will help determine if there are elements of our application that occasionally suffer delays while being used, or if our tests are inefficient in any way._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what the average E2E test suite execution time is.
    * This data requires the prior `Evaluate Ingestion of End to End Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what the average E2E testing suite execution time is._

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/3ebd7994-dde4-4c14-a32b-8fd97ce7022d)

https://va-gov.domo.com/page/1950369682/kpis/details/389820473

Should be good here - the data looks right to me based on what we actually run in CI.
