### ISSUE TITLE
Discovery: Research & document publicly-available info for current ordering process

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#3199]
## User Story or Problem Statement
As a UX designer, I need to investigate and document the current processes for ordering prosthetic socks and hearing aid batteries, so I can understand the problem space and identify user/stakeholder groups for further investigation.

## Goal
- We would like to be able to proliferate knowledge and understanding of the problem space to the BAM2 team and the project sponsors
- We would like to be able to identify groups to be stakeholders

## Objectives or Key Results
- Communicate to both BaM2 and DSVA teams about current landscape of problem space.

## Acceptance Criteria
- [ ] Research publicly available information about current ordering process(es)
- [ ] Create a document containing all research that was publicly available
- [ ] Share documentation with BAM2 team 

## Next Steps
- Identify whether additional research needs to be conducted 
- Identify & meet with stakeholders to confirm and expand upon findings
- Create initial user flow for processes for both forms 2345 and 2346

**Comment by wygonikGCIO** [comment]
21 estimation.  Maybe this should be an epic we breakup.

**Comment by rileyorr** [comment]
@wygonikGCIO This ticket was completed before the start of this sprint, so we were creating it for documentation and to close it. It should have been separate tickets, but they weren't created prior to Becca researching/creating the document.

**Comment by rebeccawalsh** [comment]
@wygonikGCIO  @rileyorr The documentation for this ticket can be found as a PDF on github [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/MDO_Preliminary_Research%20Notes_11-5.pdf). For future editability, I will probably convert this document to markdown as time permits in the same folder [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/preliminary-research-notes.md).
