### ISSUE TITLE
Contract: Create Contract Failure Rate Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31999]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show average execution times for my product's E2E test suite. This will help determine if there are elements of our application that occasionally suffer delays while being used, or if our tests are inefficient in any way._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what the average E2E test suite execution time is.
    * This data requires the prior `Evaluate Ingestion of Contract Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what the average E2E testing suite execution time is._

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/930d9403-c962-409b-8025-8ece9779f337)

https://va-gov.domo.com/page/1950369682/kpis/details/1699218273

This is done but....well...we've had zero historical failures! So, right now it's completely empty. My usual disclaimer in these situations is we may want to tweak some display properties of the graph if/when it gets more populated, but for right now we're all set.

**Comment by pjhill** [comment]
There isn't too much to take in with this visualization atm, but we are setup for the future!
