### ISSUE TITLE
E2E: Create E2E Spec Execution Time Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31994]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show average execution times for my product's E2E test specs. This will help determine if there are elements of our application that occasionally suffer delays while being used, or if our tests are inefficient in any way._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what the average spec execution time is in our E2E testing suite.
    * This data requires the prior `Evaluate Ingestion of End to End Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what the average spec execution time is in our E2E testing suite._

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/e3a712af-2106-48e8-9ba0-b7ad2e42f96c)

This card should be good to go. Two conditions for this card's data set:

1) Execution time cannot be 0. If it's 0, it's excluded from the chart as it would just be taking up space.
2) AppName cannot be null. As apps fill in manifests that are missing them, they will populate the chart.

**Comment by CBonade** [comment]
Found a potential inconsistency with this data - un-readying this one and reevaluating

**Comment by CBonade** [comment]
Comparing this with the suite execution time chart resulted in a lot of duplicated data once this inconsistency was rectified. In chatting with Peter about this, it was decided that there's not a lot of value in trying to separate this from the suite execution graph and we are going to forego this one for the time being. We may replace it down the line with a different chart.
