### ISSUE TITLE
Hub and spoke navigation 

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#32]
"The hub"

**Comment by jenniferlee-dsva** [comment]
Just providing some existing documentation, some old, some up-to-date in GH:
https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Banners

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Banners/VA.gov-homepage-banner-texts-preapproved-v5-020919.pdf
