### ISSUE TITLE
Accessibility: Create A11y Running Total Issue Count Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32003]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show a running total of a11y issues that have been filed against my product. This card should chart the total daily, whether it goes up due to new issues or down due to issues being solved. This will give us an accurate picture of the current functional state of our application._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what the running daily total of a11y issues filed against our application is.
    * This data requires the prior `Evaluate Ingestion of GitHub A11y Issue Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what the running total of a11y issues existing in an application._

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/371124421

All set here

**Comment by pjhill** [comment]
This looks great!
