### ISSUE TITLE
Contract: Create Contract Test Endpoint Coverage Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32000]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show what percentage of endpoints used in my product are being evaluated in our Contract testing suite._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what percentage of our application's endpoints are being tested with Contract tests.
    * This data requires the prior `Evaluate Ingestion of Contract Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what percentage of our application's endpoints are being tested with Contract tests._

**Comment by CBonade** [comment]
Not sure at all where or how to get this data. Going to put this on hold for now and remove it from the dashboard for the sake of our first pass until I have some more information.

**Comment by CBonade** [comment]
Closing due to no plans to implement this currently.
