### ISSUE TITLE
Contract: Create Contract Spec Execution Time Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32001]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show average execution times for my product's Contract test specs. This will help determine if there are elements of our application that occasionally suffer delays while being used, or if our tests are inefficient in any way._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what the average Contract test spec execution time is, per spec.
    * This data requires the prior `Evaluate Ingestion of Contract Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what the average Contract test spec execution time is, per spec._

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1751017624

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/0377fd2b-abf7-4370-bf3f-6004a2eb2580)

All good here!
