### ISSUE TITLE
Accessibility: Create A11y Issue Launch-blocking Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32005]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show how many of our a11y issues are regularly launch-blocking. This data should update daily._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects a comparison of launch blocking vs. non-launch blocking a11y issues filed against a product.
    * This data requires the prior `Evaluate Ingestion of Contract Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting a comparison of launch blocking vs. non-launch blocking a11y issues filed against a product._

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1955845169

This is as far as we can go with this until we get our table up and running that will allow us to assign products to any of these issues.

**Comment by pjhill** [comment]
This card disappeared. Did it morph into this one?
https://va-gov.domo.com/page/1950369682/kpis/details/721967848

**Comment by CBonade** [comment]
yes it did!

**Comment by pjhill** [comment]
Done and dusted!
