### ISSUE TITLE
[Research] Draft Conversation Guide: Outreach & Events Filtering/Recurring Events MVP

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32038]
## Issue Description
_Produce a Draft copy of a Conversation Guide in support of future research project_

Link Here: 

## Acceptance Criteria
- [x] Draft conversation guide
- [x] Share with someone from UX team, Brian, Dave, Cassandra, and incorporate their feedback

**Comment by cindymerrill** [comment]
Started a new blank conversation guide but waiting for screens walkthrough from Cassandra before writing out user tasks.

**Comment by cindymerrill** [comment]
Drafted user tasks and questions. Would like to discuss with Cassandra.

**Comment by cindymerrill** [comment]
Revised conversation guide a bit. Waiting on decision about date filter dropdown options, and then can finalize.

**Comment by cindymerrill** [comment]
Working on this today to update date filter options and add new user tasks and questions

**Comment by cindymerrill** [comment]
Revised conversation guide per today's design decisions, shared with Brian, incorporated his feedback, and shared with Dave for feedback and approval prior to launching recruiting next week.

**Comment by cindymerrill** [comment]
Conversation guide approved by Dave last Friday.
