### ISSUE TITLE
IA Request from Profile team

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32031]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
We are splitting up the user current user Profile into two separate pages: 
1. Contact information (address, phone number, fax number, email)
2. Personal information (preferred name, date of birth, birth sex, gender identity, pronouns, sexual orientation)

We have already submitted a content request, but need IA guidance on the placement of the "How do I update my date of birth or gender"  component at the top of the page in relation to two non-editable fields (date of birth and gender) on the new Personal information page.    Should we change the order of the fields?  
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md
- Link to or attach user flows: 
- Link to prototype or mockups:
   - [Personal information - blank states](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2) (new page)
   - [Personal information - edit states](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw) (new page)
   - [Contact information] https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/bg4kVKJ) (update to an existing page; two fields were moved to Personal information page)
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:  Q4 2021
- Estimated staging review date:  TBD
- Content and IA work needed by: 11/2

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Marci McGuire
-	Designer: Kevin Hoffman (temporarily)
-	FE engineer: Zach Morel
-	Product/team Slack channel: #vsa-authd-exp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
@MarciMcGuireGCIO  Have you received accessibility and design feedback on this question?

From my perspective I would prefer to see the information attached to the field rather than separated.  One option would be to place the text under each field in the place where the Edit button would be.  This would repeat the information more than once, but it would connect the the info to the field and create consistency in order of info for each field (i.e. field name, field value, CTA).  

Also, I am assuming the URL for the new page will be www.va.gov/profile/contact-information/.   If you plan to use something else, please let me know.

**Comment by MarciMcGuireGCIO** [comment]
@mnorthuis I had not yet, and thank you for those recommendations!  Do you have any suggestions on the ordering of the fields given that some are editable and some are not?

**Comment by mnorthuis** [comment]
Oops!  I failed to answer that!  Sorry!

I would not group them based on editable/not editable. I would ensure fields are grouped based on how they relate to one another - for example, keeping the gender questions (birth gender and gender identity) together.   I would lean towards ordering these by how likely they are to provide the info AND how important it is to VA.   It seems as though birth date, preferred name and pronouns would be the most important for purposes of communication, while the gender identity and sexual orientation fields are very sensitive, less likely to be provided, and not as critical to VA to have.   PLEASE correct me on that if VA feels differently.   That would create an order such as this:

Date of birth
Preferred name
Pronouns
Birth certificate gender
Gender identity
Sexual orientation

I did briefly run this by Danielle as well, and she agreed, however we were both unsure about the order of birth gender versus gender identity.  Those may need to be swapped, as who we identify as, is more important that what was assigned to us - on the flip side, birth gender is more likely to be provided by more people. This is where IA needs input from inclusivity experts and users!  Martha may have some insight on this as well.

**Comment by MarciMcGuireGCIO** [comment]
Thank you!!!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel @Samara-Strauss @cgednalske - please @mnorthuis two comments above for  IA feedback.  [Her first recommendation ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32031#issuecomment-958051757) will entail moving the "How do I update my..." verbiage into the sections with the Date of Birth and Birth sex info.  Also noting that Mikki lists "Birth certificate gender", but I believe MPI refers to that as "Birth sex". 

The second recommendation swaps the order of the fields around a bit.  

@Samara-Strauss can you confirm the new URL for contact info will be http://www.va.gov/profile/contact-information/ ? If so I will put in a request for that.

**Comment by Samara-Strauss** [comment]
>  Her first recommendation will entail moving the "How do I update my..." verbiage into the sections with the Date of Birth and Birth sex info. 

I get this recommendation, but we don't have a pattern for this in the profile right now. FAQs show above entire sections at this point in time. You can log into staging and look at the FAQ near the personal information section we have now.

> Also noting that Mikki lists "Birth certificate gender", but I believe MPI refers to that as "Birth sex".

Please use "Birth sex", as this is more accurate. I also believe this is what Danielle recommended, and she's our content person.

> @Samara-Strauss can you confirm the new URL for contact info will be http://www.va.gov/profile/contact-information/ ? If so I will put in a request for that.

Yes, that is the correct URL.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @Samara-Strauss . 

@cgednalske and @zacharymorel, I'll update the frontend documentation to reflect the changes, but I won't touch the FAQ link until you talk to Liz, @cgednalske. 

If you two decide on something different than what's already mocked up, I'll open a new ticket for that since you won't have a chance to talk until next week.

**Comment by MarciMcGuireGCIO** [comment]
> Also, I am assuming the URL for the new page will be [www.va.gov/profile/contact-information/](http://www.va.gov/profile/contact-information/). If you plan to use something else, please let me know.

@mnorthuis do I need to create an IA request for this URL?  This is our first time adding a new page.

**Comment by mnorthuis** [comment]
@MarciMcGuireGCIO Nope!  Your devs can implement that as part of their build.

**Comment by MarciMcGuireGCIO** [comment]
Great! Thank you @mnorthuis!
