### ISSUE TITLE
Updates/corrections for product directory

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#32032]
A list of updates for https://depo-platform-documentation.scrollhelp.site/getting-started/VA.gov-product-directory.1898676225.html

- Appeals modernization - this was an "act" not a product, but you could consider the launch of the Decision Reviews content area part of this.  This launched in 3/2019. Parent product=decision reviews or content hub, hub=global or decision reviews, team = Claims and appeals, url www.va.gov/decsion-reviews
- Appeals status - hub=global
- Burial benefits application - hub=Burials and memorials, team=Sitewide content and IA, lead = Beth Potts
- Burials and memorial hub - hub=Burials and memorials, team = Sitewide content and IA, lead = Beth Potts
- Claims and appeals status - hub=global
- Comparison tool updates - parent product = GI Bill comparison tool, hub = Education
- Dependent benefits application (686) - parent product = View/manage dependents, hub = global
- Disability hub - team = Sitewide content and IA, lead = Beth Potts
- Education hub - team = Sitewide content and IA, lead = Beth Potts
- Family member hub - hub= family benefits, team=Sitewide content and IA, lead = Danielle Thierry
- GI Bill feedback tool - remove the line that references Debt resolution
- Header/footer - hub= global, team = Public Websites, lead = Dave Conlon
- Health care - hub=health care
- Health care hub - hub = health care, team = Sitewide content and IA, lead = Danielle Thierry
- Higher level review - hub=decision reviews
- Home page - team=Public Websites, lead = Dave Conlon
- Left navigation - parent product = ?, hub = global, team = Sitewide content & IA, lead = Dave Conlon
- LIfe insurance - hub=life insurance, team = Sitewide content and IA, lead = Beth Potts
- Pension benefits app (527) - hub = Pension
- Pension hub - hub=Pension, team=Sitewide content and IA, lead = Beth Potts
- PCPG (ch 36) - hub=careers
- Post 9/11 info - hub=education
- Pre-need burial app - hub=burials and memorials
- Privacy policy - team=Sitewide content and IA, lead = Danielle Thierry
- Records hub - hub=records, team=Sitewide content and IA, lead = Danielle Thierry
- Resources and support - parent prod=resources and support, hub=resources and support, team=Sitewide content and IA, lead = Beth Potts/Danielle Thierry
- Save in progress - parent prod is not dashboard/My VA...maybe Forms Library?
- Search - hub=global, team=search and discovery team, lead=Dave Conlon
- Service member hub - hub=service member, team=Sitewide content and IA, lead = Danielle Thierry
- VAMC Modernized pages - parent product=facility sitess, hub=global, team=facilities
- Vet center pages - parent product=faciltity sites, hub=global, team=facilities
- Veteran ID Card - hub=records

**Comment by shiragoodman** [comment]
changes made
