### ISSUE TITLE
Prep Tasks for Research: Outreach & Events Filtering/Recurring Events MVP

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32037]
## Issue Description
_Tasks needed in support of upcoming research project scheduled for Outreach & Events - Filtering & Recurring Events MVP._

## Preparatory tasks
- [x] Share research plan and conversation guide with Lauren Alexanderson for approval and recruiting
- [x] Make note-taking spreadsheet
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilots
- [x] Debrief pilots 
- [x] Revise conversation guide
- [x] Send instructions to observers
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day
- [x] Followup with Perigean re participant list
- [ ] Other tasks as needed 

## Acceptance Criteria (AC)
- [ ] All set to start research sessions with Veterans

**Comment by cindymerrill** [comment]
Scheduled a pilot test for 11:30 PT on Tue Nov 30, which is too late for Jim Adams (in ET) to have time to make a lot of prototype revisions before real sessions start the next day. So, I'm going to look for someone else (I usually run 2 pilots anyway) who is available on Mon Nov 29 or earlier on Tue.

**Comment by cindymerrill** [comment]
Scheduled a second pilot test for next Mon. 

Hoping to sync with Jim tomorrow about user interactions needed from the prototype and when they're needed for pilots next Mon and Tue (and actual research sessions on Wed).

**Comment by cindymerrill** [comment]
Made notetaking spreadsheet.

**Comment by cindymerrill** [comment]
Launched recruiting with Lauren but haven't heard anything back yet.

**Comment by cindymerrill** [comment]
All 10 participants recruited and scheduled by Perigean. Ran pilot #1 today, debriefed with team, made tweaks to prototype (Jim) and conversation guide (me). Ready for pilot #2 tomorrow. Will continue working on other prep tasks above.

**Comment by cindymerrill** [comment]
Ran second pilot test today and finished up rest of tasks in this ticket. Only pending item is a couple bug fixes in the prototype, which Jim will be working on tonight.

**Comment by cindymerrill** [comment]
Sent thank you notes to pilot participants, which I added as a task to this ticket (so it can be copied for future research tickets). @brianalloyd
