### ISSUE TITLE
Push TUD Account Checkin and Checkout Events to BigQuery

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#32041]
Each time a TUD account is checked in or checked out, push data regarding that event to BigQuery for DOMO dashboarding purposes.

**Comment by holdenhinkle** [comment]
I manually tested this and demoed it to Peter. It's working nicely.

This is complete, all issues have been resolved, and all checks are green on GH. Just waiting for a final approval.

**Comment by holdenhinkle** [comment]
Lindsey approved it. Waiting for Identity to approve it.

**Comment by holdenhinkle** [comment]
This was merged 2 days ago.

**Comment by pjhill** [comment]
Done and dusted
