### ISSUE TITLE
Connect redux code for document uploader on COE eligibility app

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#32047]
` need to wait for an endpoint`

## User Story
As a Veteran I want the documents I upload on the eligibility app to actually be submitted to the correct place at the VA

## Background
Now that we have added the document uploader on the eligibility app for the `pending-downloads` state we need to connect it to redux so that we will be able to make an api call to actually upload the documents to the VA.

## Tasks
1. Connect Redux `actions` code for document uploader
2. Connect Redux `reducer` code for document uploader

## Acceptance criteria
- [x] The above redux code has been added to the COE eligibility app
- [ ] A PR has been submitted for review

**Comment by alsleaders** [comment]
This has work has been completed - I just tested with user 14, 38, and 128, and I can upload a supporting document as part of the COE form on staging.  
@jason-gcio can we close this?
