### ISSUE TITLE
Add reusable document list components to COE eligibility app

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#32045]
# User Story
As a Veteran I want to be able to view the documents that I have sent to and received from the VA regarding my Certificate Of Eligibility within the eligibility app so that I have them all in one central location.

# Background
Now that the designs for the COE app have been updated we need to update the code to reflect those changes. This ticket is to add the reusable front end components for listing the documents the user has sent to or received from the VA regarding their COE and then adding those components to the different states on the eligibility app. We also need to make a small text change to one of the states.

## Tasks
1. Create reusable components to list documents that the veteran has sent or recieved (Static for now but add all components needed)
2.  Add document list component to `eligible` state per [mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139512694/simulate/sitemap)
3.  Add document list component to `pending-upload` state per [mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140680778/simulate/sitemap)
4.  Add document list component to `denied` state per [mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140537807/simulate/sitemap)
5.  Change text on action link on `unable-to-determine-eligibility` state to match [mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140811192/simulate/sitemap)

## Acceptance Criteria
- [x] Changes above have been made per mockups
- [x] A PR has been submitted for review

**Comment by jason-gcio** [comment]
Some additional questions around where these files are going to be coming from... S3 would be nice
