### ISSUE TITLE
[Research] Draft Research Plan: Outreach & Events Filtering/Recurring Events MVP

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32040]
## Issue Description
_Produce a Draft copy of a Research Plan in support of future research project_

Link Here: 

## Acceptance Criteria
- [x] Draft Research Plan
- [x] Share with another researcher, Brian, Dave, Cassandra, and incorporate their feedback
- [x] Resolve with team what kind of prototype will be used
- [ ] If testing on Staging, share with Josh & Angela, and incorporate their feedback -- N/A
- [x] Add testing dates after hear when UXPin prototype will be ready

**Comment by cindymerrill** [comment]
Finished drafting the research plan and shared it with another researcher for feedback.

**Comment by cindymerrill** [comment]
Revised research plan per feedback from another researcher, and now ready to share with team. It's preliminary since it's missing dates and prototype details since we don't yet know whether we'll be able to build a "live" prototype on Staging. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/research-plan.md

**Comment by cindymerrill** [comment]
If/when it's been confirmed that we can build on Staging so we can test with screen reader users, I'd like to show this research plan to Josh and Angela for feedback.

**Comment by cindymerrill** [comment]
Updated Acceptance Criteria above to more clearly account for what's been done and what is blocking @brianalloyd

**Comment by cindymerrill** [comment]
Note: Have received no feedback from anyone on Public Websites yet

**Comment by brianalloyd** [comment]
Thanks @cindymerrill a review is on my to-do list for today.

**Comment by cindymerrill** [comment]
I just updated my research plan to reflect today’s decision to prototype in UXPin instead of on Staging

**Comment by cindymerrill** [comment]
Updated research plan re today's decision that the prototype will be mobile and tentative timing: research sessions Nov 29-Dec 3 and pilot tests Nov 19 and 22.

**Comment by cindymerrill** [comment]
Updated research plan per today's design decisions, and also decreased the number of participants to be recruited, per direction from Lauren Alexanderson. 

I'll share out the research plan for review again once I'm done with the conversation guide revisions per today's design decisions.
