### ISSUE TITLE
[QA] HLR: Request Design QA for Higher Level Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3205]
* **Context:** Provide context for your team's project.
        * e.g., ```Functionality adds a new dataset to the Facility Locator so users can search for and view non-VA health providers on the map, as well as in list and detail views.```
      * **URL:** ```link to your project on staging```
      * **New Design Patterns (if any):** Note the places where you've created and used new design patterns (if any)
      * **Design Challenges (if any):** Note any unusual or tricky design problems you needed to solve in this work
      * TODO - provide an example here.

**Comment by CrystabelReiter** [comment]
@YanaRoy Hi! Could you please add context to what we are to review? it helps to add what we're going to review and a URL to staging or a prototype if you guys have one. @emilywaggoner and I will schedule an in-person review with you and anyone else you'd like to join from your team.

**Comment by YanaRoy** [comment]
@CrystabelReiter I started this shell and will make sure to update - when we're ready for the review, I will comment here. Should be sometime in the next 2-3 weeks. Thanks!

**Comment by luke-gcio** [comment]
This is a pre-collab cycle ticket and this work is now done as part of a review process. OBE.
