### ISSUE TITLE
Feature Request - Add ignore list to content-build broken link checker

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#32057]
## Instructions 

If you have a request for a feature you believe the VA Platform should implement, complete the information below. The more information Platform has, the faster we can process the request.

## Describe the problem 

- *Describe the problem, and how solving this problem will make things better for VFS Teams, OCTO-DE, VA, or Content Editors.*
- *How widespread is the problem, i.e. who do you believe would benefit from the Platform solving this problem?*

When a content editor adds this link to a page:

<a href="/jobs/">Find VA careers and support</a>
The broken link checker in the content build detects it as a broken link. That's because the jobs section of the site is not part of the build process at all. It's a collection of ASP pages hosted on a completely different server. The link checker looks for jobs/index.html in its list of pages and doesn't find it, so it thinks the link is broken.

## Describe your idea 

*Describe your Platform feature or service idea, in other words describe how you think the Platform should solve this.*
To solve this, we can add an ignore list to the link checker. Any link in the list will be ignored and not checked. Initially the list will only contain jobs/index.html, but it could be expanded in the future.

Acceptance criteria:
- [ ]  Broken link checker ignores links that are in ignore list
- [ ]  Unit test is added to ensure that ignore list works correctly

*Provide the evidence that you have on the need for this enhancement.*
See the above problem description.

*Indicate which of the parts of our Platform mission the enhancement would drive (select all that apply):*
  - [ ] Keeps these products and services available, stable, and secure.
  - [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach. 
  - [x] Provides shared tools, software, support, and technical infrastructure to accelerate their development. 
  - [ ] N/A

**Comment by timwright12** [comment]
Closing out as this doesn't appear to be an issue anymore
