### ISSUE TITLE
Adding [erik.pollack@coforma.io] to DSVA Slack

### ISSUE THREAD

**Issue by jlang10761** [department-of-veterans-affairs/va.gov-team#32060]
Please add erik.pollack@coforma.io to the channels below. He is with Coforma and will be providing general project support.
new user requests:

Are you requesting to add an individual as a: Multi-channel
What channel(s) do they need to be added to?
• cpm-public
• lcs-public
• cds-team
• Cds-tools-leads
• Cds-tools-team
• Cpm-onboarding

**Comment by LizCallaghan** [comment]
done!
