### ISSUE TITLE
[BUG] Orphaned glyph on banner element

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32078]
## Issue Description
_Issue was identified of an orphaned glyph in a banner as show below.  This will need to be resolved to improve the user experience and ensure users are not following this orphaned glyph to a 404 page element_

## Screenshot 
<img width="268" alt="Screen Shot 2021-10-27 at 10 18 47 AM" src="https://user-images.githubusercontent.com/70410912/139106481-e2962a29-a613-475e-a924-e8381cad93e2.png">

## Possible Technical Solution 
Assuming that content doesn't come from the CMS, you can likely prevent it the same way we did here. use a span with whiteSpace: 'nowrap' around the last word and the icon https://github.com/department-of-veterans-affairs/vets-website/blob/8736710ac1de0b5c7a780487bba9c5ca4216b470/src/applications/personalization/dashboard/components/IconCTALink.jsx#L43-L51
IconCTALink.jsx

[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1635343562149000)

## Acceptance Criteria
- [ ] Ensure orphaned glyph is resolved on banner element
- [ ] Ensure Unit tests pass
- [ ] Page is rendering as intended 

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
@tmac9494 can you provide an update on this ticket concerning this work?

**Comment by tmac9494** [comment]
@brianalloyd After updating main branches in my local environment, I cant seem to get the banner to render again. After consulting Kelson and checking the updates it seems like no change has been made to the banners. Currently doing a fresh install of the repos and see if that fixes it

**Comment by tmac9494** [comment]
Testing solution locally in component library before upload,  had to format text prop in PromoBanner component to split out the last word and wrap it with a <span style={{whiteSpace: 'nowrap'}}>{lastword} <icon></span>

**Comment by tmac9494** [comment]
PR: https://github.com/department-of-veterans-affairs/component-library/pull/215

**Comment by brianalloyd** [comment]
Completed, closing ticket in support.  Thanks.
