### ISSUE TITLE
Cognito Discovery

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#32089]
Cognito looks like a good option as an identity broker, we need to do further discovery. 

Task is done when: 
we have answered the following questions and added the answers to a doc in our confluence space. 
- How would we use it?
- How it could work with PIV cards?
- What are its limitations?
- What would a prototype look like?

**Comment by calquisola** [comment]
I created a doc in confluence. 
https://vfs.atlassian.net/wiki/spaces/AMT/pages/1974501377/Amazon+Cognito
