### ISSUE TITLE
List of Tools & Services from Platform Ops team

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#32082]
### Overview
Much of the access management for the Platform is managed through the Platform Ops team. Understanding what their team is doing will help the Access Management Spike Team identify processes that would be most useful to automate first.

This information will be gathered on [this spreadsheet](https://docs.google.com/spreadsheets/d/1ONpU-N6vJVl7A6ebh5QaM2p8F7dPB2KlFl1vPp-8UTo/edit?usp=sharing). 

Task is done when: the spreadsheet lists tools and services that the Ops team manages

**Comment by calquisola** [comment]
tools were added in the spreadsheet.
