### ISSUE TITLE
Document Lifecycle of Platform Ops-Managed Tools and Services

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#32083]
### Overview
Much of the access management for the Platform is managed through the Platform Ops team. Understanding what their team is doing will help the Access Management Spike Team identify processes that would be most useful to automate first.

This information will be gathered on [this spreadsheet](https://docs.google.com/spreadsheets/d/1ONpU-N6vJVl7A6ebh5QaM2p8F7dPB2KlFl1vPp-8UTo/edit?usp=sharing). 

Task is done when: We have the following questions answered in the above spreadsheet

- Who uses it?
- Who Requests?
- How?
- How often do these requests happen?
- What info is needed to request?
- How is ops notified?
- How do they fulfill the request?
- How can we automate it?

**Comment by calquisola** [comment]
Added a confluence page for this. 
https://vfs.atlassian.net/wiki/spaces/AMT/pages/edit-v2/1959526423
