### ISSUE TITLE
Backstage Plugin Prototype

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#32093]
To test out backstage, we can start with building a plugin. We can do this after #32092 is completed. 

Tasks:
- [ ] Use the builtin Github plugin
- [ ] After a successful login in Github show a page that displays and info regarding the repo
- [ ] Create a plugin for AWS Cognito
- [ ] Test out if we can use AWS Cognito instead of Github

**Comment by harshil1793** [comment]
Only basic Backstage config was done as part of the story. This story was closed as we decided to take a pause on backstage.
