### ISSUE TITLE
Access for Elizabeth Neal

### ISSUE THREAD

**Issue by ENeal49** [department-of-veterans-affairs/va.gov-team#32096]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Frances Elizabeth Neal

### Your Email

elizabeth.neal@agile6.com

### Name of Your Team

PTEMS VA.gov Modernization, Delivery Manager, Agile 6

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMI4siK+aa/PekllMh5wkL2vc77FYST11esEf8zz/7Z8tyLUDP6cD8S7/dKf20sqe2EGUJQjlouU8HH+SokhmoJSx1hfQmnA/9otayksZeFKxSea9JS7pUZRJUOXf21TTOQXyH8G9u4iql5zVwCa9UwKu30exEZhNcNntwyfsYnUBP+8eHXtOcJinj1zO+obWSEtBEGkhNlUqoDAqZpVtzldfRaQ1ImIlvYvQOzlvJuqNmFEpIEsvAa4fLWlUHHXFuwOdRlm/5ZFIJfCV0CxblbluYce68vjSulWyFrLDRD0OknPI4mTQTJhZnBSinOHvbmdpAtW6Q2Co/AOvrhkHTShjK/7a9oRAzcGEVBwjd+fmAtjdK/jcfywq+Ngt9G2q+OJNoRzb6/uVQbHB9ecUfmM6OCICEqktcsavwDcbrmpbXhvWURj0Ls0s7SQjAh+ihSuZHy64yGVBNBNTaMCnAXet3XJfSRevSQmFMymE6HBdRruDh0ER6XXWxAqfW4V8= Elizabeth.Neal@Agile6-A72

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any further trouble.
