### ISSUE TITLE
Put in place build/deploy Slack notifications related to the cms

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#321]
## User Story
As a cms team or VSP support team member, I need notifications about the status of cms related deploys so I can see issues when they happen and troubleshoot accordingly.

## Goal
The important events around building and deploying should be defined and implemented and sent to the appropriate place in Slack

## Acceptance Criteria
- [ ] Defined notifications are sent to Slack
- [ ] Notifications are sent to the appropriate channels

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbalboni** [comment]
I think these are the situations that a cms team member or VSP person supporting the cms would be interested in:

- The vets-website master build uses the cache for a build (notification exists)
- The vets-website master build failed (notification exists)
- A staging content deploy finished
- A dev content deploy finished
- The preview server is finished deploying (notification exists)

It also could be useful to put these in one channel, like cms-notifications.

**Comment by rianfowler** [comment]
TODO: send these notifications to #cms-notifications 
- The preview server is finished deploying (notification exists)
- The vets-website master build failed (notification exists)
