### ISSUE TITLE
NEWSLETTER PIVOT: Finalize methodology

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32107]
- gretchen needs probs a day to round up thoughts
- if we set up an example and showed it to researcher(s)

**Comment by lianilychee** [comment]
11/1 Fri:
- blocked: to resolve with SD during sync today - synchronous or asynchronous?
  - also blocked by liani (but will be resolved by SD sync today)

**Comment by andreahewitt-odd** [comment]
Newletter no longer exists -- closing
