### ISSUE TITLE
NEWSLETTER PIVOT: Configure testing mechanism

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32108]
Async highlighter study, titled `The Platform | Communications research - YOUR NAME HERE`: https://docs.google.com/document/d/1dQZVXZda8Y3h-DqUZQNfTH0lcJDXnmQcc_zXgq9fOz8/edit

**Comment by lianilychee** [comment]
Pending SD sync on Thurs 11/4

**Comment by andreahewitt-odd** [comment]
Newletter no longer exists -- closing
