### ISSUE TITLE
Sign-in Widget from VSA Debt Team

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#32117]
## Why you're here

We’re looking to add the sign in widget to the content page `/health-care/pay-copay-bill/` with the flexibility for us to toggle the widget using the `show_medical_copays` feature toggle

### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [ ] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Medical Copays MVP is the next product to meet the goal of unifying Veteran VA debt into a modern, consolidated and Veteran friendly experience similar to what a consumer may experience with Quicken Loans or Chase portals. The goal of unifying all Veteran debt into a single portal is to make it simple for the Veteran to understand, pay or settle any and all debts they may have with VA without having to distinguish between different agencies and processes.
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md
   * https://github.com/department-of-veterans-affairs/va.gov-team/issues/25663
   * https://dsva.slack.com/archives/CPE4AJ6Q0/p1635365781060200

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [x] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - show_medical_copays
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* <Desired/target implementation date>

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: VSA Debt Team
- DEPO product owner: Matt Self
- Product manager: Denise Coveyduc
- Designer: Riley Orr / Rebecca Walsh
- FE engineer: Craig Wheeler / Justin Linn
- Product/team Slack channel: vsa-debt

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by brianalloyd** [comment]
@tmac9494 you'll be primary on this ticket.

**Comment by brianalloyd** [comment]
@tmac9494 can you work this ticket next.  Need to knock this out this sprint in support.

**Comment by kelsonic** [comment]
Design link: https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages/140027243/simulate/sitemap?mode=i

When not signed in:
![image](https://user-images.githubusercontent.com/12773166/140799178-56bb39ea-92b3-456c-a9c6-7d82905496ea.png)

When signed in:
![image](https://user-images.githubusercontent.com/12773166/140799148-39821e30-2452-4ba0-8a9f-4563bc7eee2b.png)

Where does the link `View your current copay balances` go to? Are there any other requirements other than just being authenticated? e.g. LOA/etc. CC @craigwheeler

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19338

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy today, will need a content editor to add the react widget `medical-copays-cta` to the pages you'd like it placed on 🙂 CC @craigwheeler @rileyorr @RLHecht

**Comment by brianalloyd** [comment]
@craigwheeler checking in on this effort, please advise on if this meets your teams intent so we can close once work is completed.  Thanks.

**Comment by craigwheeler** [comment]
hey @brianalloyd everything looks great 👍  ... you should be good to close this ticket thanks!

**Comment by brianalloyd** [comment]
Thanks @craigwheeler closing ticket in support.
