### ISSUE TITLE
Onboarding: Intro interviews with technical teams

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32115]

**Comment by lianilychee** [comment]
11/1 Mon:
- Today: J and S gonna sync this afternoon to review intro and go over q's
- wondering:
  - calendly for scheduling?
  - divide and conquer for the four teams?

**Comment by lianilychee** [comment]
11/02 Tues:
- ready to go!  RSVPs coming in

**Comment by andreahewitt-odd** [comment]
Closing -- they are now onboarded
