### ISSUE TITLE
[FE] [Bug]  Profile contact info success banner should fill parent container

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32138]
## What happened?
- [Related Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1635358954139700)
- [Info about not switching it from `Alert Box` to `va-alert`](https://dsva.slack.com/archives/C909ZG2BB/p1635433780172900?thread_ts=1635358954.139700&cid=C909ZG2BB)

Currently the success banner does not stretch to fill its parent container.  
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/e562c82e-be37-4e1c-ac32-96804711d55b)

## Specs:
- Device: Any
- Browser: Any
- Test User: I reproduced with user vets.gov.user+36@gmail.com

## Steps to Reproduce
- URL: https://staging.va.gov/profile/personal-information
- Test User _(if applicable)_: vets.gov.user+36@gmail.com
- Log into VA.gov via ID.me
- Update the email value slightly with a validly-formatted email address and save
- The success banner is displayed, but does not fill the parent container.

## Desired behavior
When a user updates a value in their contact information with a valid value and saves, the success banner should be displayed and should fill the parent container.

[Screen shots of how it is supposed to look](https://dsva.slack.com/archives/C909ZG2BB/p1635604448259800?thread_ts=1635358954.139700&cid=C909ZG2BB)

## Acceptance Criteria
- [ ] Success banner fills parent container when Profile contact info is updated, saved, and the banner is displayed

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MarciMcGuireGCIO** [comment]
Under "Desired behavior" added link to screen shots in Slack showing how it's supposed to look

**Comment by SKasimow** [comment]
Closing...tested and was fixed:

![Screen Shot 2022-08-24 at 4.52.08 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/1c75215f-60cc-4a53-9624-5d1fdccb4f79)
