### ISSUE TITLE
Document recommendation for CSS in vets-website

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#32144]
**Write an artifact that details** 
* What needs to go to design system
* What needs to be deleted 
* What needs to go to content-build 
* Where does the design system need to be utilized (what is duplicative)? 
* Effort level associated with this work (/each of these pieces of work) 

Artifact doesn’t need to list specific classes, can just reference the audit 

Should include background info

Katy’s [recommendation](https://vfs.atlassian.net/wiki/spaces/FTT/pages/1937014880) is a helpful template but this may not need as much detail

**Review/approval** 
* 2 FE Tools team members
* Design System Team 
* Send to VFS teams for awareness

**Comment by rmessina1010** [comment]
Closing.
