### ISSUE TITLE
TUD: Number of TUD Testers

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32157]
## User Story
_As a TUD stakeholder, I would like to have a dashboard card that will display the number of unique TUD users by day._

## Tasks
- [x] Create a Domo Dashboard Card that visually presents the frequency .
    * This data requires the prior `Evaluate TUD Data Ingestion` task to be completed first.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.
- [x] The scope and estimate for this ticket includes refactor work for GA code.

**Comment by holdenhinkle** [comment]
I had a meeting with Brian and Lauren today from Analytics. He said that we can track unique visitors by hashing a user attribute, like the user's GitHub ID, or something like that, so that user data remains anonymous (if I understood that correctly).

I think he might had some notes about our meeting today [to this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32617#issuecomment-974294948).

**Comment by holdenhinkle** [comment]
Push `user_id` config value. This should be hashed. See https://support.google.com/analytics/answer/9213390?hl=en#implement-user-id&zippy=%2Cin-this-article

**Comment by holdenhinkle** [comment]
Working off this same branch (`add_google_analytics_tracking`) - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/100

**Comment by holdenhinkle** [comment]
When a user is logged in, I'm grabbing their GitHub ID, hashing it, and passing it to GA as the `user_id` (a built-in property/feature in GA) and the `hashed_github_id` (which is a custom dimension I created that we can use to run reports off of).

See the following for more information - https://developers.google.com/analytics/devguides/collection/ga4/user-id?technology=gtagjs

> `user_id` is a reserved property name, so you can't directly access it in reports and explorations. To access the identifier in reports and explorations, use another parameter (such as `crm_id`) and then store the parameter as a custom dimension.

Once these values are set, they're associated with all other events sent to GA, which is handy.

`user_id`:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/deb2fc4c-3ec4-4ee1-a7eb-1864223b44f2)

`github_user_id`:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/e18d6226-b5fd-4f00-9071-8feadc75dadc)

**Comment by holdenhinkle** [comment]
The `login` event is now being recorded:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/bf64f18b-62e7-43ed-9d13-f6085a454fc8)

**Comment by holdenhinkle** [comment]
Strange, GA doesn't have a 'logout' event. See:
- https://developers.google.com/analytics/devguides/collection/gtagjs/events
- https://developers.google.com/tag-platform/gtagjs/reference/events

I created a custom one:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/f55b9ce9-bd09-4bd4-b125-6a0ea0a2600d)

**Comment by pjhill** [comment]
The scope and estimate for this ticket includes refactor work for GA code.

**Comment by pjhill** [comment]
Looking good!
