### ISSUE TITLE
Dashboard - TUD: Number of Searches Per TUD Tester Per Day

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32159]
## User Story
_As a TUD stakeholder, I would like to have a dashboard card that will display how frequently the search function is used.

## Tasks
- [x] Create a Domo Dashboard Card that visually presents the frequency .
    * This data requires the prior `Evaluate TUD Data Ingestion` task to be completed first.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria
- [ ] _A dashboard card exists reflecting the most searched for TUD Account attributes._

**Comment by holdenhinkle** [comment]
Working off this same branch (`add_google_analytics_tracking`) - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/100

**Comment by holdenhinkle** [comment]
We're recording search events:

My search...
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/f4e13b23-2d9b-4d6a-9ad0-d6cafb37a83f)

Was recorded in GA...
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/5b39a65a-938e-4fee-9b53-a10afa6d073f)

**Comment by holdenhinkle** [comment]
This is done:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/d5a10019-2296-40af-90c6-91bdf0d17214)

**Comment by pjhill** [comment]
Yay -- nice work!
