### ISSUE TITLE
TUD: Number of TUD Accounts Checked In from staging.va.gov Logout

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32160]

**Comment by holdenhinkle** [comment]
Done:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/d0fd7bea-0594-4a6a-8beb-5bec3ba71e0e)

**Comment by pjhill** [comment]
This looks good as implemented!
