### ISSUE TITLE
TUD: Number of TUD Accounts Checked In By TUD Maintenance Job

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32161]
## User Story
_As a TUD stakeholder, I would like to have a dashboard card that displays information about the number of TUD accounts that have been checked back in by the daily maintenance job._

## Tasks
- [x] Create a Domo Dashboard Card that visually presents the frequency .
    * This data requires the prior `Evaluate TUD Data Ingestion` task and potentially a ticket that creates a daily maintenance job to check users back in that were not checked back in by user actions.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria
- [ ] _A dashboard card exists reflecting the most searched for TUD Account attributes._

**Comment by holdenhinkle** [comment]
Done:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/6590ed34-b41f-420b-8043-f636d455fc84)

**Comment by pjhill** [comment]
Looks good!
