### ISSUE TITLE
TUD: Number of TUD Accounts Available

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32164]
## User Story

_As a TUD stakeholder, I would like to have a dashboard card that will show how many TUD Accounts are available in the tool._

## Tasks
- [x] Create a Domo Dashboard Card that visually represents the total number of test accounts available in TUD.
    * This data requires the prior `Evaluate TUD Data Ingestion` task to be completed first.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria
- [x] _A dashboard card exists reflecting the total number of TUD account available._

**Comment by holdenhinkle** [comment]
Done:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/10b961e1-56c3-4eb0-887b-1468a9269bef)

**Comment by pjhill** [comment]
I think we said we may want to change the default date range for this card or the entire dashboard in general. At any rate, this looks good and we can iterate based on feedback later.
