### ISSUE TITLE
Refactor Dashboard Data repository to account for multiple data streams

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#32169]
Our `testing-tools-dashboard-data` repository initially was only designed to expect one set of tests and one set of results. As we move into a complex dashboarding initiative with many, many data streams, we need to build out our structure to account for different formats of data needing different handling methods.

- [ ] Refactor repository using Javascript classes and subclasses for organization.
- [ ] Test everything in CI multiple times to ensure stability

**Comment by CBonade** [comment]
Got Cypress tests with the refactored structure to work this morning.

Spent most of the day trying to beat up contract tests to do the same. Finally at the end of the day I have it behaving the way we need it to. Will do some cleanup and call contract tests done.

Before I call this refactor initiative done, we have one bug that has reared it's head in the Testing Reports Prep stage where a BQ table will be deleted, created and then when we go to insert the data the table says it doesn't exist. This is not a new issue, and is supposed to retry when this happens (we have code to account for this) but for some reason does not run in that step only. Once that's figured out, this ticket will be ready to move to review.

So close!

**Comment by CBonade** [comment]
All set here! 

PR covering the refactored code: https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/86

Both `vets-website` and `content-build` workflows have been moved over to utilizing this new structure so it can be seen in action on any CI workflow.

**Comment by pjhill** [comment]
🎉
