### ISSUE TITLE
Contact Center Review for Authenticated Experience  - Notification Settings

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32171]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Notifications settings feature with the Authenticated Experience Profile product. The feature allows users to proactively establish the way in which the VA communicates with them. Our MVP offers up to three notification items all via text message.

[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md#communications-permissions-notification-preferences-product-outline) for reference as well.

### Launch Date
Phased launch to begin week of 11/1 (tentative)

### Version Number
Version 4 of the Profile product guide. While this is an update to the Profile product guide, we are only making updates at this time to include the Notification settings feature.

### Product Guide
[VA.Profile.-.Product.Guide.v4_102021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7438195/VA.Profile.-.Product.Guide.v4_102021.docx)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @ajakabcin. Attached is the draft of the v4 product guide. I've reviewed the Notifications setting feature section and it looks good, only tiny edits. Please note that I did add a title page and a revision history page to the beginning of the document. If there are issues there, please let me know.

If this draft looks good to you, I will share with VEO. Thanks! 
[VA.Profile.-.Product.Guide.v4_102021_srt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7444600/VA.Profile.-.Product.Guide.v4_102021_srt.docx)

**Comment by ajakabcin** [comment]
Thank you @starlow00 !!!

**Comment by ajakabcin** [comment]
@starlow00 edits looks great - good to send to VEO. Thank you for the quick feedback on these updates!
