### ISSUE TITLE
[UX] Mockup for add BTSSS link to See Clerk screens

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#32175]
## Description
We need a mock up that shows  a link to BTSSS on all of the 'see clerk...' screens so that even when a veteran must see an MSA to check in, they will still be able to access BTSSS during the check in process so that they can file a claim for travel reimbursement.

## User Story
As a veteran, I would like to be able to easily access BTSSS via my mobile device during the check in process, even when I am directed to see an MSA to complete check in. 

## Acceptance Criteria
1. A mock up of the 'see clerk...' screens that includes the link to BTSSS.

Link: https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

**Approved wireframe:** 
NoK: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/oLz5w3/a/v8J0rP1/r/9xa0w0
Contact info: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/eb5nvj/a/rbjyPzA/r/rwv4qD

**Comment by kristenmcconnell** [comment]
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e

**Comment by zach-park** [comment]
Hi team, here are the draft of 'See clerks UIs' with BTSSS link verbiage ready for feedback:
**Mockup 1**: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/eb5nvj/a/rbjyPzA/r/MGRDKb/
**Mockup 2**: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v//a/v8J0rP1/r/MGRDKb
@DanielleThierryUSDSVA @kristenmcconnell @jparker0425 @julieadair1

**Comment by kristenmcconnell** [comment]
Not everyone is eligible for travel pay (even if they do travel to their appointment). This is the verbiage used on the travel pay webpage..."Find out if you’re eligible, and how to request reimbursement." Maybe our wording should be close to that.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @zach-park! I would recommend addressing eligibility in a brief set-up sentence that also gives just a brief explanation of what travel pay reimbursement is for those who may not be familiar, and then use "Find out how to request..." language for the CTA link.
 
You may be eligible to get paid back for approved health care travel expenses. 
[Find out how to request travel pay reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/)
