### ISSUE TITLE
SOCKS Proxy Discovery

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#32186]
There are internal apps that lives behind the VA firewall and need a socks proxy to be accessed if you don't have a GFE.
These applications to my knowledge are: 

- Grafana
- Sentry
- Jenkins
- Prometheus

Platform leadership and Security Team wants to move away from SOCKS as it poses a security Risk.  

Task: 
Our main task is to find a more secure alternative to SOCKS but also give the user a better experience.  Our worst case situation  according to Thomas would be, the user logs in using AWS the open an EC2 instance and login view the applications from there.

**Comment by Kennon-git** [comment]
**Task is Done When:**

- [ ] We know why socks is being used - what are upsides?
- [ ] We have a list of alternatives in confluence with pros / cons

**Comment by calquisola** [comment]
From the ops office hours yesterday. 

"Something we’re looking at doing soon to open up some access to specific services over the internet instead of via SOCKS proxy — https://app.zenhub.com/workspaces/platform-operations-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/21026"

**Comment by Kennon-git** [comment]
"If something cannot be exposed, (we) want it to justify why that is, not the other way around. (i.e. one should have to justify why it cannot be exposed, rather than why it should be exposed). 
[Thread](https://dsva.slack.com/archives/C02GQ27HXQW/p1636036579058400)
