### ISSUE TITLE
Update URL for VAOS root

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3218]
Currently, vaos sits at `/vaos`, which isn't great because it should follow VA.gov IA guidelines for organization - and the name also doesn't make sense to veterans.

AC
- [ ] 'dashboard' / appointments list of VAOS available at `/health-care/schedule-view-va-appointments/appointments`.

**Comment by jbalboni** [comment]
There are two parts to this, updating in the app and updating the devops config. @narin has the app path updated in a PR for another issue and I will update the devops config.
