### ISSUE TITLE
Update Vaccine Contact Information Copy

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#32194]
## Description
Update the contact information copy page to the latest vaccine content. 

<img width="640" alt="Screen Shot 2021-10-29 at 11 15 12 AM" src="https://user-images.githubusercontent.com/90797205/139469130-5b45108e-d21a-45b3-985a-8a8529b67b0c.png">

## Acceptance Criteria
Given the COVID-19 new appointment workflow, 
When the user enters the Confirm your contact information page,
Then the page description matches the [copy doc ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/contact-information.md)

Given the new appointment workflow, 
When the user enters the Confirm your contact information page,
Then the page description matches the [copy doc ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/contact-information.md)

#### Design Assets
Page structure guide for [copy doc ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/content)section reference

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
PR changes pending approval from Tony when he returns from PTO

**Comment by ldelacosta** [comment]
@ptouchton - the latest changes are not in staging site. Could you please double check? 

Staging site results as of 1/10 - 
**New COVID-19 appointment workflow:** 
![Screen Shot 2022-01-10 at 11.30.48 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3b470196-2307-4e5d-ab45-466a61f8912d)

**New appointment workflow:**
![Screen Shot 2022-01-10 at 11.28.41 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/a65c3594-68ff-440a-9380-2d2812624e24)

**Comment by ldelacosta** [comment]
Validated in staging and the changes have been implemented: 

**COVID-19 new appointment workflow:** 
![image.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/bebd0735-aae6-440c-ab77-0f69f1e629c4)

**Non COVID-19 new appointment workflow**
Request: 
![Screen Shot 2022-01-10 at 12.27.30 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/9f722b07-f150-4ada-b8da-4a746d91e6f7)

Direct: 
![Screen Shot 2022-01-10 at 3.09.11 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/1661e186-a1a0-49c0-ba46-7437615e8b84)
