### ISSUE TITLE
[FE] See Staff Bug Fix

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#32196]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack Thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1635520545156300)

## Description
Fix the bug in the thread

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Create test
- [ ] Fix bug

**Comment by julieadair1** [comment]
@mdewey - what epic is this related to?  pre-check-in?
