### ISSUE TITLE
Update Vaccine Confirmation Copy 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#32198]
## Description
Update the vaccine confirmation page to the latest vaccine content. 

<img width="632" alt="Screen Shot 2021-10-29 at 11 17 34 AM" src="https://user-images.githubusercontent.com/90797205/139473844-eff4f7e3-f364-44e4-b119-af592b530e81.png">

## Acceptance Criteria
Given the COVID-19 new appointment workflow, 
When the user enters the vaccine confirmation page,
Then the page description matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-confirmation.md) 

Given the new appointment workflow, 
When the user enters the confirmation page,
Then the page description matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-confirmation.md) 

## Design Assets 
Page structure guide for [copy doc ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/content)section reference

**Comment by jenniemc** [comment]
@cferris32 , looks like this branch was merged with master. Can we move this ticket out of code review into validation?

**Comment by ldelacosta** [comment]
@cferris32 - Hi Corey. The validation looks good for vaccine confirmed appointment, but the non-vaccine workflow is still showing the old text. See validation results below. 
Please let me know if you have any questions. Thanks! 

Vaccine Confirmed Appointment:
![Screen Shot 2022-01-03 at 4.13.18 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/6c9635f7-4649-4b02-b464-5312094591a7)

Non-vaccine Confirmed Appointment:
![Screen Shot 2022-01-03 at 4.17.19 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/37936c85-f485-4790-9459-92110a5185eb)

**Comment by ldelacosta** [comment]
Validated the changes in staging. 

COVID-19 appointment workflow booked: 
![Screen Shot 2022-01-10 at 3.16.11 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/37d763cb-0af8-4919-a0ef-326f29ef76ba)

Non COVID-19 appointment workflow booked: 
![Screen Shot 2022-01-10 at 3.18.14 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/701f9415-ad26-4483-a6cb-b4b3559868f0)
