### ISSUE TITLE
Discovery: Disability Research

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3220]
## User Story or Problem Statement
As a UX designer, I need to research the battery and prosthetic products the VA sells so I can be prepared when conducting user interviews about the products.

## Goal
_Gain an understanding of the battery and prosthetic products being sold including terminology, usage, frequency of replacement, etc._

## Objectives or Key Results this is meant to further
- _Furthers preliminary discovery research and guide Veteran interview conversation guide development_

## Acceptance Criteria
- [x] _Research hearing aids, hearing aid batteries, prosthetic socks, prosthetic accessories, products sold by VA, how products are used, terminology, etc._
- [x] _Document findings_
- [x] _Add findings to the discovery research presentation for team/stakeholder(s)_

## Next Steps
Add gathered research to Sprint 1 presentation deliverable (#3221)

**Comment by rileyorr** [comment]
@wygonikGCIO & @rebeccawalsh 
I have been collecting data about hearing aids/batteries this afternoon and created a living doc that can be found [here](https://docs.google.com/document/d/1wgI2BIUIogVtdqjQRUP5FuBEK7XUY9xPuDM8PV7tpt4/edit#)!
Please feel free to add comments/thoughts to the doc as you read through it!

**Comment by rebeccawalsh** [comment]
Here are the links for [Prosthetic Socks Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/prosthetic-socks-research.md) (RW) and [Hearing Aids Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/hearing-aids-research.md) (RO)

**Comment by rileyorr** [comment]
@wygonikGCIO The research has been added to our presentation. Moving to Validate
