### ISSUE TITLE
Business intake form for Lighthouse Appeals - Supplemental Claim digital submission

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va.gov-team#32210]
## Requestor Name 
Kelly Lein

## Business Line 
Decision Reviews

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
We would like to send a notification email when the Supplemental Claim has been received by VA.  This will give the Veteran confidence in the submission and prevent duplicate submissions.

## What is an overview of the notification use case? (required 3-5 sentences) 
This notification will work exactly like the recent one implemented for Higher Level Review but with a Supplemental Claim template.

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
A Veteran will submit a Supplemental Claim on VA.gov.  Once the submission have been accepted by the Central Mail Portal, we will send the Veteran an email saying we have received the submission.  This will give Veterans the confidence that they do not need to resubmit.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No.  Digital submission of Supplemental Claims will be new functionality.

## What kind of notification would this be? (required Email, Text, Not sure)
Email

## If you have a draft of the content you’d like to send - please upload here. Please note we collaborate with all of our users on their content to ensure it meets standards. (optional - blank) 

Dear Jane,

Thank you for filing a Supplemental Claim.

To check your Decision Review status, go to https:///www.va.gov/claim-or-appeal-status/ to sign in to our claim status tool. Please allow 24 hours for your Supplemental Claim to show up there.

Your Decision Review details are below:
Supplemental Claim

Date Submitted
June 29, 2021

If we have questions or need more information, we may contact you. We’ll notify you by mail once we have processed your Decision Review.

Thank you for your service,
VA

You are receiving this email because you filed a Supplemental Claim with VA. Please do not reply to this email. If you need to contact us please visit https://va.gov or by phone: 1-800-827-1000.

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
Not yet.

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
vets-api

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes.

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
Yes.

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
not sure exactly how it will work yet but we have discussed it with our stakeholders. (Alejandro Mendiolaflores, Andrew Gray)

## What is your estimated volume of notifications per day, week, month? (optional - open space)
A complete estimate but could be ~8000 emails a month.

## When does this notification need to be in production? (optional - open space)
No hard deadline yet but hopefully by the end of the year?

**Comment by bevnobev** [comment]
@kellylein Here is your template ID in staging - 1c0a49e1-f6d8-4c38-ba6d-1a5484db028a

![image.png](https://images.zenhubusercontent.com/5fc80e211b246885156b8b66/ba118458-30bd-4ff8-beac-1b29496662f9)

Let us know if you want to make any changes.

**Comment by miabecker** [comment]
@kellylein just checking here - any updates on a go live date?

**Comment by kellylein** [comment]
We have built all of the notification functionality into our API. This functionality will go live with our Supplemental Claim MVP, so the timing is dependent on when VA.gov can build the front-end.  We won't have the final go-live timing for a while yet.  I will let you know once I know when it will be, but for now we are all set!  Thank you!

**Comment by kellylein** [comment]
@miabecker  As one caveat to my above statement, we are indeed ready for the Production template ID.  Let me know if you need anything else from us to generate that for us.  Thank you!

**Comment by miabecker** [comment]
Hi Kelly! Lovely to hear from you here is a production template ID let me know if you need anything else: b68de57f-c753-42c7-8ddd-82ca91ab8462

**Comment by bevnobev** [comment]
Hi @kellylein.  Just checking in to see when you plan on going live with the notification.  I see an email was sent in prod last week, so I'm curios.  Thanks!

**Comment by kellylein** [comment]
We still do not have a timeline for this functionality going live in Production, but we did a test last week from our end to make sure everything was flowing through, so all is good there.  I will let you know once we have a timeline, but it will likely still be months away as we need to get on the VA.gov team's roadmap.

**Comment by bevnobev** [comment]
Hi @kellylein. Checking to see if you have a timeline for going live in Production.  Is it still months away?  cc: @mjones-oddball

**Comment by kellylein** [comment]
Hi @bevnobev , Yes, unfortunately due to the VFS team contract change, the timing of this work has been pushed back. It is still likely months away.
