### ISSUE TITLE
Discovery: Research Findings Presentation

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3221]
## User Story or Problem Statement
As a UX designer, I need to compile gathered information into a PDF presentation so I can present research data to stakeholders.

## Goal
_Combine preliminary research findings into a PDF presentation to share with stakeholders at the end of Sprint 1_

## Objectives or Key Results this is meant to further
- _Gains an understanding amongst team and stakeholders about the product we're building and direction the team proposes for product development_

## Acceptance Criteria
- [x] _Create presentation document (Google Slides) - Done by design team_
- [x] _Review presentation document with PM_
- [ ] _Make edits if necessary_

## Next Steps
Direction will be determined by stakeholders and team

**Comment by rebeccawalsh** [comment]
Find the research presentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/preliminary-findings-presentation.pdf)
