### ISSUE TITLE
Make accordion web component "header" api match others

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32229]
## Description

Our accordion web component has an API where you set the header text (and level) based on props, like so:

```html
<va-accordion-item level={4} header="My header text">
  <div>Content</div>
</va-accordion-item>
```

However, as we have developed more recent components, we have been using a named slot pattern that allows a more idiomatic use of HTML:

```html
<va-alert>
  <h4 slot="headline">The alert header text</h4>
  <div>Content</div>
</va-alert>
```

The accordion component should use this newer pattern for consistency. In addition, we cannot remove the old pattern until it is no longer in use in `vets-website` and `content-build`

## Tasks

- [ ] Allow new named slot header pattern in `<va-accordion-item>`
- [ ] Ensure that the older `header` and `level` props still work

**Comment by pdavies88** [comment]
* Need to have conversation with accessibility specialist about the ability to put heading tags within button tags. 
* Issue at hand is that level and heading props are being used to create a heading tag with a button tag and then text nested inside of it, however slot tags are used to inject a full element. 
* If a full element will not pass accessibility standards then this issue will require the deconstruction of the slot element and manipulation of that element into the same format as described above.

**Comment by pdavies88** [comment]
Invalid HTML to put h tag inside of button
![Screen Shot 2021-11-22 at 9.00.46 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/0d8d17b4-732a-4c82-a122-c11174283a40)
Solution will be to deconstruct the slot element to separate out the h tag from the text and then inject a button tag in between

**Comment by pdavies88** [comment]
Merged PR: https://github.com/department-of-veterans-affairs/component-library/pull/226
