### ISSUE TITLE
Discovery: Competitor Research

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3222]
## User Story or Problem Statement
As a UX designer, I need to conduct competitive research in the e-commerce space so I can gather inspiration and follow standard design patterns our users will be familiar with.

## Goal
_Gather research about e-commerce design patterns and document them in a Mural board for future reference during prototyping stage._

## Objectives or Key Results this is meant to further
- _This issue furthers the design process by creating a streamlined design solution when creating the ordering experience._

## Acceptance Criteria
- [ ] _Research/document e-commerce design patterns in Mural_
- [ ] _Share with PM_

## Next Steps
Identify common patterns and patterns that can be used in our design. Incorporate patterns into the design.

**Comment by leahkeeler** [comment]
done
