### ISSUE TITLE
[UX] Add Content to Appointment Confirmation Wireframe for "Insurance Update Needed" 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32224]
## User Story
As a Veteran, I want to know if my insurance is current so that I can update my information with a staff member for my appointment if needed. 

## Description 
We need to add static content on the appointment confirmation page notifying a Veteran if they need to update their insurance information for their appointment. 

CHIP has a true/false boolean that checks for insurance updates. Once this check is passed to us on the BE, we will need to surface the content to the veteran. 

## Acceptance Criteria 
- [ ] Determine content for messaging 
- [ ] Update wireframes for appointment confirmation page to include content 
- [ ] Sync with appropriate team members on updates (Product, FE, etc.)

**Comment by kristenmcconnell** [comment]
@jparker0425 Are we changing to let the Veteran through the check-in process even if they need their insurance reviewed? Here is the [ticket where UX worked on wording ](https://github.com/department-of-veterans-affairs/chip/issues/150#issuecomment-954947671)for an SMS error message if the user needed to have insurance reviewed.

**Comment by kristenmcconnell** [comment]
@jparker0425 Are you doing this and changing the logic?

**Comment by julieadair1** [comment]
@jparker0425 - do we need to look at this ticket for next sprint?

**Comment by jparker0425** [comment]
@julieadair1 and @kristenmcconnell I am closing this item since it is being handled by VeText and SMS. If we revisit insurance on the FE again in the future, we can create a new item.
