### ISSUE TITLE
Phase 1 - Technical Research into how to skip sections of 526 Claim Form

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#32237]
## Issue Description
Veterans would like to be able to skip sections of the form that they find triggering. We need to investigate whether or not this can be done.

---
## Tasks
- [ ] Phase 1 technical discovery into how we can allow skipping - can we allow submission without the entire form being completed?

## Acceptance Criteria
- [ ] Technical considerations and approaches documented in GitHub
---

**Comment by chrvalla** [comment]
We did the research on PTSD to remove many off the triggering questions. We gave results and recommendations to Paul Shute, that was 100% onboard, and he was shut down by a person higher up..

Will continue to push this forward.
