### ISSUE TITLE
Adding Mobile Link to Letters  App

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#32235]
## Issue Description
As a Veteran, I would like to be able to reference the VA.gov mobile app from the Letters application. Similar to [work in Claim Status Tool,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30252) Mobile team would like to add link to Letters App. Reference [Slack conversation](https://dsva.slack.com/archives/C5AGLBNRK/p1635175502014200) with Ambika Roos

Kevin's proposed implementation:
![image.png](https://images.zenhubusercontent.com/5ffca1cc8ef760e3db881927/b991e3c6-bb9b-4ab9-84e4-49cc749aa0ce)

---
## Tasks
- [ ] Implement link addition on Letters App in same place as CST

## Acceptance Criteria
- [ ] Link added to application website
---

**Comment by Mottie** [comment]
As per [our discussion in Slack](https://dsva.slack.com/archives/C5AGLBNRK/p1635888231114800?thread_ts=1635879573.103100&cid=C5AGLBNRK), this work may not be implemented within the letters app. The info page leading into the app is better suited for this mobile alert, and that page is managed by the content team.
