### ISSUE TITLE
TUD: Daily Maintenance Job

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32240]
# Description
Create a daily maintenance job to:
1. Checkin accounts that weren't properly checked in (by logging a test user out of staging)
2. Effectively mirror the TUD accounts table (minus each account `id` and `password`) in BigQuery for Dashboarding purposes.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/8340

**Comment by holdenhinkle** [comment]
I've got it all coded up, sans tests.

I'm still waiting for my other PR to get reviewed and approved. So I branched this off of my `push_tud_account_checkin_and_checkout_events_to_bigquery` branch.

My local `vets-api` is being flaky again. I'm getting that same error I was getting before saying that it can't find the `google-cloud-bigquery` gem. Yes, I've run and rerun `bundle`.

```
2.7.4 :001 > TestUserDashboard::BigQuery.new
Traceback (most recent call last):
        1: from (irb):1
LoadError (cannot load such file -- google/cloud/bigquery)
```

**Comment by holdenhinkle** [comment]
PR  submitted.

The job runs each day at midnight.

## Testing
The BigQuery `tud_accounts` is dropped, then created successfully:

Schema:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/1f3a37c7-381d-4be0-86ec-3bba67ac6231)

Query results:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/0d20974a-8f05-4334-be08-0bc1be7a982d)

**Comment by holdenhinkle** [comment]
This is waiting for a review from Identity.

**Comment by holdenhinkle** [comment]
This was just merged.

**Comment by pjhill** [comment]
This has been functioning as designed for a couple weeks now.
