### ISSUE TITLE
Access for Tanner Heffner

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-team#32245]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Tanner Heffner

### Your Email

tanner.heffner@agile6.com

### Name of Your Team

CMS Sitewide Team, Senior FE Developer, Agile6

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZ/Vf8JuCHdud3Z06POy5bb2kh5kvd4WtxiV+liwYN2fbIg3qrqXG9oujYrajKuPTVbNZzcsnLK/2X5x9I91q6rFU4PAjOUsy33HsqFVmoDGgvqf15o38/J2Czp5T1hAkI/owAf198EmP3o81pcjO2kpWewSECAq4YHCgVTZX0gHDcKTXk4pzIAEk9RBbUM82Pk2nLRbjIlSrv4ZiB2GUBD+9ZR+SJPMc9VBBYRZ5nwgwh7Ms+t9X2eBkfHUwWMeFLggT0kxy3UV8Ux7SL5YCCEAzwULSRVT3UtP4P/9OMpbyUI1ySfmArhRY1DXrnpYeFOV8GIuV/5boKqU9MjEEM3HSrieXpJerRb2OWJjbusMOPSq2W8xTpCpJZxCbV/o3KIRu+WcH+9yHY1/XhivX6isdW8Qg8VPII5XrMY/1idVs15sOqHvWwzRmImJ4Mc0KjSLxQaPHYGn4QQ2EUIjjKS2fj32oD0iH1v4uNkqIttfcPk+3gIQkYKx/MP18B/bc= heffner@MacBook-Pro

**Comment by tjheffner** [comment]
I previously requested access here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32086

but I think the ssh key was for the wrong user account on my computer.... when I re-run `vtk socks setup` it asks me if I want to create/copy this new key and open an issue... so here I am :)

**Comment by jsgarmon** [comment]
Key updated. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any further trouble.
