### ISSUE TITLE
 Requesting Medallia for Vet Center pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32244]
## Issue Description

**Description** 
- Requesting Medallia implementation for new Vet Center pages

**Launch Date** 

- There are 300 Vet Centers nationally. 56 have been published to date. They are rolling out by district with publication to Production occurring when they've completed all content, been reviewed and approved by RCS leadership. 

**Staging URLs** 
- n/a 

**Production URLs** 
- URLs containing `-vet-center/ ` and `-vet-center/locations/`

** Requesting team info
- Facilities team
- PO: Dave Conlon
- PM: Michelle Middaugh
- #vsa-facilities

**Comment by jwoodman5** [comment]
@mmiddaugh Is the URL path `va.gov/vet-center/` or is there something between `va.gov/` and `/vet-center/`? Thanks.

**Comment by mmiddaugh** [comment]
Hi @jwoodman5 
The name of the Vet Center is between va.gov/ and /vet-center. For example, https://www.va.gov/reno-vet-center/
We are rolling out new webpages by district for a total of 300 Vet Centers. I can let you know which are published to date but the list will evolve from week to week. Does that make sense? What is the best way to handle this implementation?

**Comment by jwoodman5** [comment]
@mmiddaugh Yeah, another case for the regex idea you had. Our Medallia folks did some testing with this, but have not been able to make it work yet. However, they are still working on figuring it out and I will keep these threads updated when I get some solid information. Of course, we could handle manually but the regex route seems to be best if we can make it work.

**Comment by jwoodman5** [comment]
@mmiddaugh The Medallia team is still working with this idea. I do not have anything positive to share yet, but they are trying to figure out how to make this work dynamically.

**Comment by jwoodman5** [comment]
@mmiddaugh The Medallia team was unable to make a regex URL pattern work for adding surveys to new Vet Center pages. For now, we will need to aggregate a list of current pages to add the survey to and identify/add new pages as they go live. Hopefully, we will have a more efficient solution in the future. Happy to chat about it if you wish. In the meantime, I will work on getting surveys added as soon as I have an initial list from you. Thanks.

**Comment by mmiddaugh** [comment]
closing as feedback now opt-out
