### ISSUE TITLE
Access for Valerie Runde

### ISSUE THREAD

**Issue by valerierunde** [department-of-veterans-affairs/va.gov-team#32247]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Valerie Runde

### Your Email

valerie.runde@civicactions.com

### Name of Your Team

Sitewide CMS, Content Strategist, CivicActions

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlP8Id//SxPHi7Sozf8jlOwZBM8ImBJImzU6PYzfKm2Wul2fIKA5mrikbwlwkiSkj4lnedY+DhRf13XEIQpO6aJxVE06m4OMYFA7do2XBn+CzUsmTFCHkmLHHaSOeQSb6mOwW84RnZakp8rzjzyEVfdc3hCf62MHHeKsFzKY6cjCx7m9TVE12XvuaG6PY1q6cmnikvrmBPWcPtr5KI6pYGZHXUvHKweTaLDBiJq/66JiVqU2MzU4RN/P3+xuH9+GHgDBUPBHQyctvANyf7n9wqCp9NX02O+ArRD7JwTEQpQSfzTYPxY818n1zwOn/VTPACdifOXzTyAkyO3G5/keDdtfWVEHQxRcak6yTfN9wZiUn7QxT+ULQX5Hg/Dt2u7JMEbQc4BzOUXOKIuGY4N3JTcf5EL2b9bXc8aHONNMvY5qASrR9bKtTxgi5tFwJFsWW0jhH63QbVvGqo96knGt4RtWFFFvQ3IGJ8uJIPCOWyeBP7ICzmFCLijBL89/TZSt8= valerierunde@Valeries-MacBook-Air.local

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any further trouble.
