### ISSUE TITLE
Access for Susanna Kline

### ISSUE THREAD

**Issue by sdk-irl** [department-of-veterans-affairs/va.gov-team#32243]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Susanna Kline

### Your Email

susanna.kline@adhocteam.us

### Name of Your Team

VA Platform Spike Team, Software Engineer III, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkY9JUHPs9bI4kPZmJ/oqfetEXzE9TxhR3gNz0k3BM0eJJVMNd2wTiHDdP/vCEkZBg8oUc3BUKyV0IN6FRKbr8FQctNvSNmTvSv6nlq6Xt8MGbWfZeAW8OFeRXe26qN7K73nhODAEpO5h6f6iS0YOu24KGCczL8GJM1T5pEpuWG1thJoA4SLJ0urXruXnm6IY0E2Ye4P4Lv2jTWdQsdoQlx2+IH98m4HmOO9+xitmpYOofeP5TR1DyTRyRBlEiOyQmQzuLhFkMdAwfv+l0B/yqP3iz0rFqDVzev5Ouwh9C4tzLxRh/SR8DiU8lbkFQ4CCmau3wTT+zmDb9sN6LKtGVUU5YtG/DWAL3hA/glXuLvNacbKKiPLViLJBHkvGXPhDNpxH49f7zA4Ej7sevcwXAP0wbOYgt4TJ+PGVR1daghbMwUrab9DjEWt81zsgoFSZouk38vsxPCXVnAYnNJoWYH9mPV8v+mvWvdUOUdTj7DpFE6rrI2FFCGgfRrxtahPs= susannakline@sdk-personal.overcautio.us

**Comment by sdk-irl** [comment]
Rep: Liberty IT Services, Sabrina Ammon

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any further trouble.
