### ISSUE TITLE
[Design] HLR Step 4 - Submit Application

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3224]
## User Story 
As a claimant, I need to review and submit my HLR form so I can ensure all of the information I provided is accurate and submit my form.

## Goal
_Create a user friendly view of information to be reviewed and submitted_

## Acceptance Criteria
Scenario: System user wants to review and submit their HLR form
- GIVEN the HLR review form has been completed by a user_
- WHEN the user reviews their provided form responses_
*and* confirms their responses are accurate
*and* selects to submit their application
- THEN the system submits their HLR form

## Definition of Done
- [x] _Submit Application page mocked up_
- [x] _Content Review Requested
- [x] _FE Ticket created #1931
- [x] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
Link TBD by @carolynwill

**Comment by carolynwill** [comment]
![Review application - expanded](https://user-images.githubusercontent.com/10746807/68685116-9d61e480-0537-11ea-9082-e82fa7832bc8.png)

Link to InVision for easier review.
https://vsateams.invisionapp.com/share/54USSB4RMA2#/393030462_Review_Application_-_Expanded
