### ISSUE TITLE
Schedule a Mob Session for Working Through Synthetics

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32248]
# Description
Given the fact that the data source we wanted to use in DataDog was not readily available, we need to revisit the effort to retrieve this information. Perhaps a mob session would allow us to break through any blockers more quickly!

## Acceptance Criteria
- [ ] Invite the newly onboarded Data Engineer for the platform

**Comment by JoeTice** [comment]
This ticket is no longer valid/necessary
