### ISSUE TITLE
[Design] HLR: Submitted page (confirmation step) 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3225]
## User Story or Problem Statement
As a claimant, I need a confirmation that my HLR form has been submitted so I can verify that I have completed the process on my end.

## Goal
_Design a confirmation page_

## Acceptance Criteria
Scenario: System user wants to confirm their HLR form has been submitted
- GIVEN the HLR form has been completed by a user_
- WHEN the user submits the form_
*and* all errors have been resolved
- THEN the system provides a confirmation stating that the HLR form has been submitted

## Definition of Done
- [x] _Confirmation/submitted page designed_
- [x] _Content review requested_
- [x] _FE ticket created_ #1932
- [x] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots

**Comment by carolynwill** [comment]
![HLR - Submission](https://user-images.githubusercontent.com/10746807/68691575-f898d480-0541-11ea-8c1c-5d148af03477.png)

Link to InVision for easier review.
https://vsateams.invisionapp.com/share/94USUZWV7MY#/393047724_HLR_-_Submission
