### ISSUE TITLE
Request access to Google Analytics and BigQuery for Noah Gelman

### ISSUE THREAD

**Issue by noahgelman** [department-of-veterans-affairs/va.gov-team#32254]
# Request Google Analytics and BigQuery access

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics
- [ ] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 

**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@noahgelman I've granted you access to both GA and Domo via your adhockteam.us email. You'll receive welcome emails from each platform with instructions on how to log in. Feel free to re-open this ticket if you have any issues!

We recommend new GA users get started by [reading this documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/New-Users-to-Google-Analytics.1877704964.html) 👍

**Comment by bsmartin-ep** [comment]
@noahgelman - do you need a service account with write access or just read-only for Domo?  Both?

**Comment by noahgelman** [comment]
@bsmartin-ep I believe I answered this in slack. Write access for both.

**Comment by noahgelman** [comment]
@bsmartin-ep @laurensimpson14 I still need access to BigQuery

**Comment by noahgelman** [comment]
@bsmartin-ep Closing This. I have access. Thank you
