### ISSUE TITLE
Platform View: A11y vets-website Score

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32264]
## User Story

_As a Platform stakeholder, I would like to have a dashboard card that will show the lighthouse accessibility score for each product on the platform._

## Tasks
- [ ] Create a DOMO card that displays the lighthouse a11y score for each product on the platform.
    * This data requires the prior a11y data task to be completed first. The data source for this should already exist in DOMO.

## Acceptance Criteria

- [ ] _A dashboard card exists on the Platform View QA Dashboard that visualizes the lighthouse accessibility score for each product on the platform._

**Comment by CBonade** [comment]
This was rolled into an entire lighthouse section and is currently displaying metrics for the homepage. Further drill downs will come with FE Tools continued work on the Lighthouse scan improvements

**Comment by pjhill** [comment]
OBE
