### ISSUE TITLE
Move PPMS single provider fetch to new facilities api space

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#32279]
We currently fetch community care provider info from `/v1/facilities/ccp/{id}`, which is the va.gov facility team's passthrough for PPMS data.

However, the facilities team has created a new space for their passthrough API, which is `/facilities_api/v1/ccp/provider`. This new space does not include the GET by provider id, just the GET for searching and returning a list of providers.

We need to migrate over the code for `/v1/facilities/ccp/{id}` to `/facilities_api/v1/ccp/provider/{id}`. We have permission to do this from the facilities team, but we'll need to maintain this endpoint.

Once this work is done, the FE will need to move over to it.

**Comment by grossb1** [comment]
After chatting with Lance Sanchez the facilities_api 'show' endpoint won't guarantee that the CC provider's address that was selected during the request flow (when we list providers via the `index` endpoint) will be the same when want to display the address for a single provider (via the `show` call).  This is die to the fact that providers can have multiple locations within PPMS.

**Comment by ldelacosta** [comment]
Per @grossb1, we do not need this ticket. Closing out the ticket
