### ISSUE TITLE
[Design] Onboarding: Christina Gednalski

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#32277]
## Background

Welcome, Christina! We can use this ticket to track onboarding to the new profile team.

### Chats

- [x] Meet with Liz (My VA team) to talk about design & the profile
- [ ] Meet with Samara

### Team docs

- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md)
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/product-outline.md)

### Onboarding to the LGBTQ data work

- [x] [Adding preferred name, pronouns, gender identity, and sexual orientation to the VA.gov profile](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md)

### Onboarding to existing Profile features

**Staging**

- [x] Log into staging to explore the profile ([List of staging users for each feature](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users))

**Profile overview**

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [Profile folder and list of products](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)
- [x] [Profile roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/profile-roadmap.md)

**Contact information**

- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information)

**Direct deposit**

- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [x] [Direct deposit for comp & pen folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit)
- [x] [Direct deposit for edu project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)

**Communications preferences** (aka Notification preferences)

- [x] [Communications preferences project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)

**Comment by Samara-Strauss** [comment]
@MarciMcGuireGCIO assigning this to you temporarily since Christina isn't in GIthub yet. We can assign to her/remove you once she's on.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - this wasn't estimated since you had not yet started when we did Sprint planning.  How many days would you estimate you spent on this?
