### ISSUE TITLE
[Campaign Landing Page Production Launch]- Getting Results in Transition (GRIT)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32286]
## Description 
(Per Anthony DiMaria) This campaign will be for Getting Results In Transition (GRIT) mobile application set to release on November 18th and was hoping to create a va.gov/GRIT page we could direct users to in support of the app launch.

### What we want to do on this page:
To support service members entering the military-to-civilian transition and all other Veterans with tools for identifying employment, increasing social connection and managing stress.

## Key Info

**CMS Clone URL/Node**
(Need a clone URL)
- [ ] (Place Holder)

**Who is Requesting**

- Requestor name: Anthony DiMaria
- VA organization: Office of Business Integration 
- Email address: Anthony.DiMaria@VA.gov

**About the Campaign**

- Name or focus of Campaign
   -  Getting Results in Transition (GRIT)
   
- Target audience(s) [up to 3]:
   - Veterans, Caregivers, Families, VSOs
   
- Goals of the Campaign: To support service members entering the military-to-civilian transition and all other Veterans with tools for identifying employment, increasing social connection and managing stress.

- Campaign start and end dates: 
   - 11/18/2021 - Ongoing/Longer Duration 
   
- Campaign page target launch date: 
  -  11/18/2021
  
- Preferred URLs: 
   - Root: va.gov/Initiatives/GRIT
   - Vanity URL: va.gov/GRIT
   
- What will you to drive awareness of this Campaign and this page? 
   - Email campaigns, Social Media Posts, live events 
   
- What metrics will you want to know to measure success of the Campaign landing page? 
   - Site visits, Click Through rate, page visits, bounce rate.

**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Not at all, but have a planned walkthrough with Tim Hudak **(Will require training materials)**
  
- Who will build the campaign landing page in the VA.gov CMS?
  - Anthony DiMaria
  
- Who will review and give approval to publish the page? 
  - Valerie Hase
  
- Who will update/maintain the landing page during the campaign?
  - Anthony DiMaria
  
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - Team is requesting to maintain the page for the foreseeable future. If an end date is required then please preserve the page so we can reuse it as updates and enhancements are made to the application. 

## What Needs to Be Done

- [ ] CMS: Set up the CLP clone page in CMS for the build template 
- [ ] Product & IA: Validate that the requested vanity URL is workable/optimal 
- [ ] Product: Get the Analytics dashboard set-up and set-up VA stakeholder to create their UTM URLs

**Comment by brianalloyd** [comment]
@xiongjaneg could you create a clone for this CLP? I'll communicate back to the Stakeholder in terms of next steps in support.

**Comment by mnorthuis** [comment]
@brianalloyd A couple things that would help me in finalizing the URLs:

- Access to draft content and/or potential H1 (in any format to help with determining potential options)
- Date when team plans to have draft content in CLP (this gives me a date to review the content and finalize URLs)

**Comment by brianalloyd** [comment]
@mnorthuis this is great, going to add this to the form so we can pull in this data at the request phase.  I'll send an email to gain insights on the questions in the interim and close the loop.

**Comment by mnorthuis** [comment]
@brianalloyd Just following up on this one to see if there is a cloned CLP or draft content available to review?

**Comment by brianalloyd** [comment]
@mnorthuis this has been paused for now.  I'll follow up with updates once received.

**Comment by brianalloyd** [comment]
closing, will reopen if this resurfaces as a desired CLP in the future.
