### ISSUE TITLE
508-defect-2: The sticky footer alert is inaccessible to screen reader users and a negative experience for keyboard and mobile users

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#32285]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

- As a keyboard user, I don't want to have to tab all the way to the bottom of the page to access the sticky footer alert
- As a screen reader user, I expect important announcements to be easily accessible at the top of the DOM so I don't miss it completely
- As a mobile user, I want an uncluttered interface so I can focus and easily read content

## Details

**The main issue that needs to be addressed is that it floats at the bottom of the page.** Floating elements can:
- hide keyboard focus for keyboard users
- cause clutter with other floating elements (like the feedback button and mobile menu)
- accidentally trigger unintended clicks and disorient users (especially since this is a full width touch target)
- create an unpredictable tabbing experience
- force keyboard users to tab to the very bottom of the page before they can access important announcement links

https://user-images.githubusercontent.com/14154792/137928290-5c0acb34-ec61-4203-95e6-8a7fc083d70c.mov

<img width="371" alt="Screen Shot 2021-10-19 at 10 34 06 AM" src="https://user-images.githubusercontent.com/14154792/137932162-6368a391-8703-410a-8540-5e963d69358d.png">

## Acceptance Criteria
- [x] Important announcements/alerts are in an easily accessible location for keyboard and screen reader users
- [x] No sticky elements cover large portions of the page

AC largely depends on how we choose to solve this problem.

## Steps to Recreate

1. Go to va.gov home page
2. Tab to the footer sticky alert (confirm it takes a while to get there)

## Potential Solution

- The promo banner and the alerts must be editable by [the appropriate owners]
- Must meet accessibility standards
- Must meet responsive mobile standards
- Must deliver some form of "reasonable" UX (e.g., shouldn't be able to have a full page of Alerts)
- Should probably have some default rules around what is dismissible, what is temporarily vs. permanently dismissible, etc.

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/776

**Comment by tmac9494** [comment]
PR above addresses the screen reader issue for the sticky footer, the other requests in this ticket require some design re-work which may be outside the scope of our team

**Comment by brianalloyd** [comment]
Thanks @tmac9494 for the work here. @joshkimux we fixed the sticky footer issues.  Can you review and confirm.  Thanks.

**Comment by joshkimux** [comment]
@brianalloyd and @tmac9494 I've left a [comment for review on a way forward](https://github.com/department-of-veterans-affairs/content-build/pull/776#issuecomment-981898974)

**Comment by brianalloyd** [comment]
No issue, thanks @joshkimux appreciate it.

**Comment by brianalloyd** [comment]
@tmac9494 have you reviewed the comment? Can you provide a status update on process here in support, thanks.
