### ISSUE TITLE
[Feature Request [Feature-Name]: Improve build time

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#32280]
### Describe the problem

Please fix this 

### Who will benefit

Helo 

### Describe your idea

I had to fill out all of this 

### Provide evidence

document 

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [ ] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [X] Other

**Comment by jchasia-adhoc** [comment]
@jonathanjnelson - moving your request to review.

**Comment by jonathanjnelson** [comment]
Yes

**Comment by jchasia-adhoc** [comment]
Closing this test ticket.
