### ISSUE TITLE
[FE] My VA - Payment information: Begin technical discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32288]
## Background
Once the MVP is scoped we should begin technical discovery for development of the feature.
[Design document](https://app.mural.co/t/vsa8243/m/vsa8243/1638500075560/0e849f61e282ebe2d8e7119eea504e4c05b0bbe4?sender=tressafurner7646)
[Discovery Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/payment-discovery-synthesis.md)
[Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history/discovery-and-research)
[Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history)
Per Tressa via Slack: 
- Developer for ebenefits (payment history) - Kathleen Crawford. 
- If you need help with anything from the payment history side you can post in #vsa-ebn-migration, 
- For anything for debt you can post in #vsa-debt 

## Tasks
- [ ] Answer technical questions outlined below and document findings in [GH Project Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history)
- [ ] Review with the team

**Open questions**

1. Will Tressa's proposal for when this section will show (or not show) work?
2. How will you retrieve the payment information we tend to show?
3. How will you show the debt information we need to show?
4. Any other technical details that we should define before moving into implementation?
     - Confirmed 31 days for most recent payment to be shown.  This has been documented in [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history) (solution summary - In Scope section.)  **Excerpt Below:**

> **In Scope - MVP**
Please see the [Payment/Financial Discovery Synthesis and MVP doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/payment-discovery-synthesis.md) for detailed documentation on the MVP requirements.
>
>    - Most recent payment (31 days out - Confirmed via [this Slack message](https://dsva.slack.com/archives/C909ZG2BB/p1640031990019000), anything older will result in the payment block not showing on My VA., Section & links will remain) 
>  - Dynamic debt link ('You've got 2 outstanding debt payments)
>  - Manage Direct deposit [link]
>  - View all payments [link]

**Comment by ajakabcin** [comment]
@tmitchellgcio we're pivoting with some of this work so I'm moving this out of the current sprint. Thanks!

**Comment by hdjustice** [comment]
@tmitchellgcio This ticket was estimated at a 1 about a month or so ago.  Would you please review and re-estimate if needed?  Let me know if you feel more information is needed, additional tasks need added, or anything else.  I want this to be clear for you, and it will help me understand what is needed in tickets to be more helpful and informative.

**Comment by tmitchellgcio** [comment]
On it

**Comment by tmitchellgcio** [comment]
@hdjustice, @tressaellen this does say we pivoted from this in a previous sprint. Do you know if anything is changed or if it's still the same? Just want to be sure I have all of the information

**Comment by hdjustice** [comment]
Hi @tmitchellgcio, the pivot was actually on the [**On-Site Notifications feature,**](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30611) which is related to the new Payment Information section addition, but is not the same.  This feature is new for us to work on.

**Comment by tmitchellgcio** [comment]
ah ok thanks

**Comment by tmitchellgcio** [comment]
I see payment history and that's fairly straightforward, but I'm not sure how I find things they owe and haven't paid. I don't know how to retrieve the api for that at the moment or if there is one. @tressaellen @hdjustice do you know who I would talk to in order to figure that one out? Also if we are showing a notification for recent payments the question I have is, how many days is it considered recent to show the notification for or are we keeping track of which payments they have seen in order to dismiss the notification?

**Comment by hdjustice** [comment]
@tmitchellgcio Hi Taylor.  I am not sure if @tressaellen has an idea on where to obtain the debt info, she did suggest posting in #vsa-debt slack channel.  They are aware we are working on this and the Onsite notification effort.
I have a quick meeting with Denise Coveyduc (PM for Debt Resolution team) today, so I will see if she can give us some people to talk with on her team.

**Comment by tressaellen** [comment]
Hey @tmitchellgcio - sorry I've been in meetings all day! 

> Also if we are showing a notification for recent payments the question I have is, how many days is it considered recent to show the notification for or are we keeping track of which payments they have seen in order to dismiss the notification?

We won't be showing notifications for recent payments on My VA in this design. We'll only show the most recent payment in that grey card. My guess is that should stay around for 30-60 days, but that's something we'll ask in testing. Sorry that's not a direct answer!

**Comment by tmitchellgcio** [comment]
Payments url - `/v0/profile/payment_history` example `src/applications/disability-benefits/view-payments/tests/fixtures/test-payments-response.json`
Debt url - `/v0/debts` example `src/applications/debt-letters/tests/e2e/fixtures/mocks/debts.json`

**Comment by hdjustice** [comment]
@tmitchellgcio @tressaellen Documented above in this ticket as well as in the Product Outline that we are looking at 30-31 days (actual days to be confirmed) as the limit on when to show the payment information section.
