### ISSUE TITLE
[Design] My VA Enhancements - Payments information: Design work

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32289]
## Background
After reviewing research findings with the PMs and PO and determining scope of the MVP, we should start working on preliminary designs.

## Tasks
- [ ] Begin design work
- [ ] Review with PMs and Samara

**Comment by Samara-Strauss** [comment]
Since we are pivoting, we can either close this ticket or take it out of this sprint and hold onto it for later.

**Comment by tressaellen** [comment]
Hello @hdjustice and @Samara-Strauss - sorry for the delay on this, my computer dying set me back a bit. I just wanted to give an update, I just posted the latest design [in this Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1638500075560/0e849f61e282ebe2d8e7119eea504e4c05b0bbe4?sender=tressafurner7646). I'd love your feedback and comments, feel free to leave them on the mural board.

I'm working on all of the use cases and putting together a document with all of the rules on the use cases as well, but I'd like to get the design nailed down asap. Thank you thank you!

**Comment by Samara-Strauss** [comment]
This is great! I actually don't have much in the way of feedback. This is exactly what we talked about, and it feels super intuitive to me.

> I'm working on all of the use cases and putting together a document with all of the rules on the use cases as well, but I'd like to get the design nailed down asap. Thank you thank you!

Great. One thing re: the health care section. If there are no unread messages, the prompt to send a message should still show in the list with the other links. It should only not show in this list if there are unread messages.

Thank you for the great work on this!!

**Comment by tressaellen** [comment]
re: no unread messages- Yep, I agree! I'll drop all of that documentation into this ticket when it's wrapped up. :)

**Comment by hdjustice** [comment]
@tressaellen This looks great!  I am definitely curious on the uses cases and how we think the page will look for the various scenarios.  Thanks so much!
