### ISSUE TITLE
[Design] Onsite Notifications: Design feedback - design intent - Authenticated Experience, Notifications

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#32297]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Thank you for all your research
- All alerts are notifications but not all notifications are alerts, group the important ones together
- Think about the dates and what you can strip out of the notification, make it as simple as possible

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- The icon in the alert should be a circle
- Yellow is for a warning or negative consequences 
- Keep character count per line 66% of page, not full width
- The icon in view all notifications represents topic in other areas, use a different icon

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by ajakabcin** [comment]
Closing this as team is pivoting on this work at the moment. If we need to revisit with a new approach we'll open a new request. Thank you!
