### ISSUE TITLE
CC language preference page is skipped

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#32294]
## Summary
Language preference page is skipped in CC flow.

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** [Patient997](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Start scheduling
3. Choose primary care
4. Choose community care
5. Go through CC flow
6. From the provider preference page (`/community-care-preferences), select Continue

### Actual Result
The next page after provider preferences is the reason for appointment page

### Desired Result
The next page should be the language preference page (`/community-care-language)

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by vbahinwillit** [comment]
This may be working as designed. The next page in the flow is language preference when the user has a residential address. This test user doesn't have an address.

**Comment by laurenernest** [comment]
@vbahinwillit The desired result documented is the expectation. All users going through the CC flow should see the language page; it shouldn't be influenced by the address. Any of the address logic should end at the provider list preference page.

**Comment by laurenernest** [comment]
Validated fix works for both users with and without an address on file. Closing ticket.
