### ISSUE TITLE
Update VAMC breadcrumb

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32303]
## Current experience
VAMC pages ([Pittsburgh health services](https://www.va.gov/pittsburgh-health-care/health-services/), for example) use the system as the "home" breadcrumb: `VA Pittsburgh health care > Health services `
Vet Center pages ([Nashville Vet Center](https://www.va.gov/nashville-vet-center/), for example) use VA.gov for the home breadcrumb: `VA.gov home > Nashville vet center `

## Expected behavior
VAMC pages use `VA.gov (hyperlinked) > VA system name (hyperlinked) > page` pattern

**Hypothesis: Veterans are not confused by this breadcrumb pattern and are able to use it for navigation.** 
- Will confirm with analytics

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
THis was updated on VAMCs in the last couple of months as the Design System overhauled breadcrumbs in general, e.g. https://www.va.gov/pittsburgh-health-care/health-services/

![Image](https://github.com/user-attachments/assets/30b7ef2e-d303-46da-a821-8a1ae8a4742a)

Closing.
