### ISSUE TITLE
Analytics Discovery - [My VA custom report request]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32317]
We need assistance being able to track the number of users who click on My VA from an unauth state. Per our [KPI's](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/README.md#what-we-can-do-in-the-next--1--2-quarters-100-foot-view-q2--q3-2021): _we want to see if adding a My VA link to the unauth nav impacts traffic to the page. So, as part of evaluating this KR, we want to add tracking to the new My VA link to the unauth nav._ 
  
## Acceptance Criteria
A custom report (or reports if needed) that's shareable and allows me to see:
- [ ] the number of users who click on my va from the unauth state
- [ ] the number of users click on my va from the unauth state and then proceed to log in and actually visit my va
    

## How to configure this issue
- Labeled with team-name

**Comment by bsmartin-ep** [comment]
Sorry for the delay @ajakabcin.  To measure this sort of sequence, we have to create two session-based segments:

1. All sessions where someone clicks the My VA link
2. All sessions where someone logs in THEN clicks the My VA link

If we're looking for hit-scoped numbers - that is how many individual clicks (and not sessions) are preceded by a login - we would have to extract those from BigQuery.

Your two segments:

1. Sessions with My-VA click
2. Sessions with Login then My VA click

Standard Audiences report with both applied....
https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_.useg=userj0nyUJ8mSaSz549jUUaaoA,userwrJFROClRI-LiXtkCfYHlg/

**Comment by Samara-Strauss** [comment]
> All sessions where someone logs in THEN clicks the My VA link

Hey @bsmartin-ep -- what we want to see is actually the opposite of what you described. We want to see how many people click My VA from the unauth nav and THEN login. When people do this, they'll automatically be redirected to My VA post-login.

Also, when I clicked into that report, I just saw a standard audience report. It's fine -- I know how to apply segments -- but just letting you know in case we're seeing two different things when clicking that link.

**Comment by bsmartin-ep** [comment]
Segment updated @Samara-Strauss.

https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_.useg=userj0nyUJ8mSaSz549jUUaaoA,userwrJFROClRI-LiXtkCfYHlg/

Does this one load for you?  :crossed_fingers:

**Comment by Samara-Strauss** [comment]
Yes!! This works!! Thank you!

**Comment by bsmartin-ep** [comment]
Great!  I'm OOO next week, but feel free to ping `/support` if you need anything else for this.
