### ISSUE TITLE
Multiple IENs block on va.gov

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32310]
### Description 
If a user has multiple MHV Identifiers, they are unable to log into VA.gov.  This resolves the issue such that users with multiple (valid) MHV identifiers will be able to log in.

### Requirements
- [ ] When an MHV user logs into va.gov with multiple MHV IENs they must be able to login successfully if each of the MHV IENs is marked with <=1 `200MHS^USVHA^A` after the MHV IEN within the SAML Response. All other MHV IENs must be ignored.

- [ ] When an DSLogon user logs into va.gov with multiple MHV IENs they must be able to login successfully if each of the MHV IENs is marked with <=1 `200MHS^USVHA^A` after the MHV IEN within the SAML Response. All other MHV IENs must be ignored.

- [ ] When an IDme user logs into va.gov with multiple MHV IENs they must be able to login successfully if each of the MHV IENs is marked with <=1 `200MHS^USVHA^A` after the MHV IEN within the SAML Response. All other MHV IENs must be ignored.

- [ ] When an MHV, DSLogon, or IDme user logs into va.gov with mutiple MHV IENs they **must not** be allowed to login if the user has >=2 MHV IENs AND the `200MHS^USVHA^A` after the IEN is not present on <=1 of the IENs.

### Note
- Request came from Jason Boire at MHV (requirement owner) and the engineer contact is Cheruvu, Haritha (By Light) <Haritha.Cheruvu@va.gov>. Haritha is on teams if we want to iterate on testing but also responds quickly via email.

### **Staging user account information:**
Below is the account information that should be used to verify that you are getting the proper `200MHS^USVHA^A` marker as part of the gcids for the MHV IEN. Another account will need to be designated for testing the multiple `200MHS^USVHA^A` markers (likely use the `mhvcss03` account for multiple `200MHS^USVHA^A` markers within the multiple IENs.
As of 11/4/21 0900:
User: ID.me credentials: saba.mhvtp@idme.com
MHV IEN: `va_eauth_mhvien: 10202354,FAKEMHVT ` 
Response from `sqa.eauth.va.gov/IAM`:
va_eauth_gcids:
``` 
1012664638V565172^NI^200M^USVHA^P|5
52151046^PI^989^USVHA^A|
10202354^PI^200MHS^USVHA^A|
e8e77e2a7bb54cf481facc1a2b4cf51f^PN^200VIDM^USDVA^A|
1012664638^PN^200PROV^USDVA^A|
FAKEMHVT^PI^200MHS^USVHA^H
```
In the GCIDs above, we can see FAKEMHVT (which is one of the IENs for this account) is marked with an `H` instead of an `A` after the `200MHS^USVHA^`. This account meets the requirement of only have one `A` which stands for active, and other markers indicate that the IEN can be ignored for our purposes.

**Comment by nsoutouras** [comment]
Nick note: From a user perspective, user cannot log into VA.gov if they have multiple MHV identifiers.  After this is fixed, user with multiple MHV iders (valid) will be able to log in to va.gov

**Comment by joeniquette** [comment]
Waiting on MHV to give us a test account that can be used for validation. Emails have been going back and forth between myself, MHV, and IAM to get this completed. Until we have an account this is blocked.

**Comment by bosawt** [comment]
We've tested this and confirmed with a staging account that this works as expected
