### ISSUE TITLE
Feedback on Request military records page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32325]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
This issue is merely to submit feedback which was received from Vet Center staff during an office hours meeting this week. Context: the following is standard language included in the "What to bring" accordion within the "Prepare for your visit" section of the new Vet Center pages which are in the process of being rolled out. Example page: [Reno Vet Center](https://www.va.gov/reno-vet-center/)

> You do not need to be registered for care at VA, rated for a service connected disability, or receiving any other form of VA benefits. On your first visit, we will look for one or more of the following:
> - Discharge documents (such as a DD214)
> - Receipt of certain awards
> - Deployment orders
> - Other document that show qualifying military service
> 
> [Request your military service records online](https://www.va.gov/records/get-military-service-records/)
> 
> If you don’t have these documents on-hand, come in and we can work with you to establish your eligibility and also answer any questions you might have. 

During our initial roll-out with the MVP group of 10 Vet Centers, we noticed some Vet Centers were linking to the[ Veterans' Service Records page on archives. gov](https://www.archives.gov/veterans/military-service-records). To standardize the content and direction, we have been directing Vet Centers to use the [Request your military service records page on VA.gov](https://www.va.gov/records/get-military-service-records/). During office hours this week, a few Vet Center field staff indicated a preference for the archives.gov page because they believe it offers a smoother Veteran experience for requesting the DD214. 

**Considerations**

- The "Go to milConnect" CTA at the top of the [Request your military service records page on VA.gov](https://www.va.gov/records/get-military-service-records/).  links to the main landing page of milConnect. There is no obvious way to request records on this landing page.  We understand milConnect is not within our ecosystem but possibly a deeper link to login or more direct route from the CTA could be helpful. The [Request your military service records page on VA.gov](https://www.va.gov/records/get-military-service-records/) gives steps for requesting records through milConnect which seems to be a heavy cognitive load to switch between tabs remembering steps. Most Vet Center clients initiate contact with a Vet Center at a time of struggle, mental health need or recent transition from active service. Our users will benefit from anything we can do to simplify this process. 
- By comparison, the archives.gov link has a pretty clear path to initiate a records request on the home page (with the option to mail a form listed immediately beneath). 
- I just noticed this informational warning at the top of milConnect's landing page: _DPRIS is not processing requests at this time. We are working to resolve the issue and apologize for any inconvenience._ (this could be a temporary notice?)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Michelle Middaugh
-	Product/team Slack channel: #vsa-facilities

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA Not sure if this is a page we want to look at reworking sometime in the future.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I think yes, anything we can do to simplify the path to getting records for folks is great. Let's put this in our backlog and talk in planning about when we can dig into it further. Thanks!

**Comment by bethpottsVADEPO** [comment]
I got some info from Paul Shute on this topic that will help us figure out how to make this page more effective:

The MilConnect option seems like a good one and very comparable to what I’m seeing on archives.gov. I suspect one records custodian has DD214s for some cohorts of Veterans, while the other has the DD214 for the remaining cohorts.

We may want to add an additional option to direct the Veteran to the archives.gov option. From what I found, this seems to be the way to utilize that option: NARA | e-Vetrecs . (archives.gov).

From the service record migration tree that VBA uses to request records, older records are available at the National Personnel Records Center (NPRC), while newer records are available through DPRIS. That may allow us to direct the Veteran to which option is best suited for their needs, but we’d probably need to validate these assumptions with both NPRC (NARA | e-Vetrecs . (archives.gov)) and DPRIS (milConnect (osd.mil)).

**Comment by mmiddaugh** [comment]
Nothing for the Facilities team to act on yet.
The [Request your military service records page on VA.gov](https://www.va.gov/records/get-military-service-records/) could be considered for rewriting to simplify the path at some point. 
The "What to bring" content for Vet Centers could also be hardened at some point.
