### ISSUE TITLE
Content and IA Request from Auth Profile Team

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32327]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [X] IA support
  
## Issue Description
In the [design intent review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31237) for Profile Personal Information Revision, concerns were raised about why the VA would need some of the more sensitive information. To that end, we want at least one FAQ to address why we ask for this information.  We need help determining if we need one FAQ or more than one FAQ.

## Supporting Artifacts

- Link to product outline: [Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/preferred-name-pronouns-gender-sexual-orientation/README.md)
- Link to or attach user flows:
- Link to prototype or mockups: [Sketch files of pages ](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)-- note that the design will be updated to reflect current production patterns.
- Link to any epics/issues that may be helpful:  

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:  Late Q4 2021/early Q1 2022
- Estimated staging review date: TBD; research will be done first.
- Content and IA work needed by: 11/16/2021

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed - please also include our new designer/researcher Christina Gednalske in any messages

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Samara Strauss
-	Product manager:  Marci McGuire
-	Designer:  Christina Gednalske (started 11/1/2021)
-	FE engineer: Zach Morel
-	Product/team Slack channel: vsa-authd-exp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by MarciMcGuireGCIO** [comment]
We have incorporated this feedback into our documentation.   Closing ticket.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske this is something we'll need to work with Danielle on so that we know  where the link to this FAQ should appear and what the FAQs will say.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MarciMcGuireGCIO @cgednalske. Definitely agree with telling Veterans why we're asking for this information. 

Building on my comments in [issue #31186](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31186), I think it might be best to use just one additional info component for the personal information section. Want to work this into the mockup and then we can review together and determine if it works?

> **Why we ask for this information**
> 
> Some of the information in this section tells us how you want to be addressed as a person. For example, our staff will know your pronouns and the name you'd like us to use when you call or come in to VA.
> 
> If you get health care through VA, information in this section helps your care team better assess your health needs and risks. For example, gender identity and sexual orientation are some of the factors that can affect a person’s health, well-being, and quality of life. We call these factors “social determinants of health.”
> 
> We also collect this information to better understand our Veteran community. This helps us make sure that we’re serving the needs of all Veterans.

We could also consider including some info within or as notes below field labels. Here's an example of what we're doing with the "preferred name" field on the 10-10EZ:

> **Your preferred name (like your chosen name, nickname, or name-in use)**
> The name you would like your VA health care team to use when you come in for care. We don't use preferred names in cases where the legal name is required.

**Comment by cgednalske** [comment]
Hi @DanielleThierryUSDSVA - here is the current FAQ dropdown information for "How do I update my name, date of birth, or birth sex?" (which Kevin mentioned requires presenting documentation) that we discussed in office hours today! Let me know if you need any additional information from the current mockups. 

**If you’re enrolled in the VA health care program**
Please contact your nearest VA medical center to update your personal information.
(Link) Find your nearest VA medical center

**If you receive VA benefits, but aren’t enrolled in VA health care**
Please contact your nearest VA regional office to update your personal information.
(Link) Find your nearest VA regional office

**Comment by MarciMcGuireGCIO** [comment]
Noting that changes to the language about updating the name, DOB and birth sex are being addressed in a separate ticket:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/33065#issuecomment-975764776

**Comment by MarciMcGuireGCIO** [comment]
Noting that changes to the language about updating the name, DOB and birth sex are being addressed in a separate ticket:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/33007

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - for visibility re: info component(s) on personal info page

**Comment by MarciMcGuireGCIO** [comment]
Closing this ticket since the original copy Danielle provided above has been incorporated into the Prototype and FE specs.  If we decide to modify the Prototype to add info to each section per her second option, that will fall under #33209

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MarciMcGuireGCIO. Just checking in on the FAQ about changing information. I think linking out to Resources and Support for that is what likely makes the most sense. Our content team is working on updating articles accordingly. I can send link language over once we've determined if everything should live in 1 article or not. Thanks!

**Comment by Samara-Strauss** [comment]
@DanielleThierryUSDSVA are you all planning on adding information re: changing sex assigned at birth and birth date to that resources & support article? If so, yes, I agree we should link over to that page.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @Danielle!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss. We're assessing whether we can  work that into the 1 article or whether we might want to consider another article. But we'll definitely address those other issues in R&S, yes.

**Comment by Samara-Strauss** [comment]
@DanielleThierryUSDSVA thank you! Just confirming that we can plan to point to the R&S section for that FAQ in its entirety so we're not pointing to R&S for the "name" portion and then answering the assigned sex at birth/birth date issue within the profile itself.
