### ISSUE TITLE
Adding Michael Chaffee to DSVA Slack

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#32326]
**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting to add mchaffee@thoughtworks.com as a full member to DSVA Slack. He will be working as a Developer on the Digital Health Platform.

Please add to the channels
 #digital-health-platform-public
 #digital-health-platform-team

**Comment by LizCallaghan** [comment]
done!
