### ISSUE TITLE
[Bug] HLR - v2 - Issues Review - Missing selected issue-card

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#32333]
## What happened?
On **[Staging Higher Level Review](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/)** form, **Issues review** page, only added issue was listed.

**Screenshot**:

![hlr-bug-issues-review](https://user-images.githubusercontent.com/587583/139993169-06b2bc93-ad6b-43a7-a2ad-15dd3879bfd6.png)

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test237@id.me` (Leah) [creds [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md) (in private repo)]

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Issues** form-page, completed any pages on the way.
- On **Issues** form-page, select a listed **Issue**-card, then click **Continue**.
- On **Add issue - Yes/no** form-page, click **Yes**, then **Continue**.
- On **Add issue - Info** form-page, complete **required fields**, then **Save**.
- On **Issues review** form-page, observe that only your added issue-card's listed.

## Desired content & behavior
- [ ] All issues [both selected and added] should be displayed.

**Mockup screenshot**: https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/1KmVwx8

![hlr-spec-issues-review](https://user-images.githubusercontent.com/587583/139993247-100620a4-b6ec-4f99-a500-b028fa6db161.png)

## Acceptance Criteria
[See **Desired behavior** above

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
Hi @tlei123!

Would you please hold off on analysis of these eligible issue pages as we're reworking it into a new list loop pattern. The mock up is now a WIP with a single issues page and clicking on "add another issue" will take the Veteran to a new form page. It will then return to the eligible issues page with a new entry.

**Comment by Mottie** [comment]
@tlei123 This page should now match the mock up. It's ready for you to review.

**Comment by Mottie** [comment]
Oh, and I've enabled the `hlrV2` feature flag for all users in staging.

**Comment by tlei123** [comment]
Will validate once Staging login issue's resolved.

**Comment by tlei123** [comment]
Closing -- validated on Staging.
