### ISSUE TITLE
[Bug] HLR - v2 - Add-Issue Info missing required-field error-messages

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#32332]
## What happened?
On **[Staging Higher Level Review](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/)** form, **Add issue > Info** page, clicking **Continue** without completing required fields didn't display any error-messages.

**Video capture**:

https://user-images.githubusercontent.com/587583/139977645-ceb79c3b-afd1-4fe7-9ed2-4bd146d48363.mp4

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test237@id.me` (Leah) [creds [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md) (in private repo)]

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Add issues - Yes/no** form-page, completed any pages on the way.
- On **Add issue - Yes/no** form-page, click **Yes**, then **Continue**.
- On **Add issue - Info** form-page, WITHOUT selecting an option, click **Save** or **Continue**.
- Observe that browser doesn't display an error-messages for the empty required fields.

## Desired behavior
-  [ ] Clicking **Continue** without completing any required fields should display error-messages for the empty required fields.

## Acceptance Criteria
[See Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
@tlei123!

As mentioned in #32333, this page will end up being the "add another issue" page and "edit" page once the new flow has been implemented. Sorry for the trouble, but our recent review requested these changes after we thought everything was complete.

**Comment by Mottie** [comment]
The new HLR v2 flow is now available in staging. This page now only allows adding one issue, it will then return you to the issue list page upon update/cancel.

**Comment by tlei123** [comment]
Closing this bug due to new UI updates.
