### ISSUE TITLE
[Bug] HLR - v2 - Add-Issue Yes/No Continue without error-message

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#32331]
## What happened?
On **[Staging Higher Level Review](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/)** form, **Add issue > Yes/no** page, clicking **Continue** without selecting an option didn't display any error message, and advanced to next form-page.

**Video capture**:

https://user-images.githubusercontent.com/587583/139971327-579a3083-d170-4e74-b4e2-e26b5ede3890.mp4

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test237@id.me` (Leah) [creds [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md) (in private repo)]

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Issues** form-page, completed any pages on the way.
- On **Issues** form-page, select a listed **Issue**-card, then click **Continue**.
- On **Add issue - Yes/no** form-page, WITHOUT selecting an option, click **Continue**.
- Observe that browser doesn't display an error-message, but instead just advances to the next form-page.
- Go **Back** to **Add issue - Yes/no** form-page.
- Observe that now **Yes** option's auto-selected.

## Desired behavior
- [ ] Clicking **Continue** without selecting any option should display an error-message on same page, not advance to next page.

## Acceptance Criteria
[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
@tlei123 This page has been removed within the new v2 flow

**Comment by tlei123** [comment]
Closing this bug due to new UI updates.
