### ISSUE TITLE
[Bug] HLR - v2 - Veteran info - Contact content anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#32344]
## What happened?
On **[Staging Higher Level Review](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/)** form, **Veteran info - Contact** page, content is missing note re. updates being reflected in profile.

**Screenshot**:

![hlr-bug-vet-info-contact-missing-profile-note](https://user-images.githubusercontent.com/587583/140008134-69f7b89b-f288-4dee-83a6-68bc969c66af.png)

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test237@id.me` (Leah) [creds [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md) (in private repo)]
- Advance to **Veteran info - Contact** page, completing any interim pages on the way.
- Observe that content does not include Note about updates being reflected in profile.

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Veteran info - Contact** form-page, completed any pages on the way.
- Observe that content is missing note about updates being reflected in profile.

## Desired content
- [ ] Content should include note about updates being reflected in profile.

**Mockup screenshot**: https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/dlGVvnn

![hlr-spec-vet-info-contact-profile-note](https://user-images.githubusercontent.com/587583/140008568-ddd25cb7-b226-44af-906a-d11e59122ef4.png)

## Acceptance Criteria
[See **Desired content** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
This paragraph has been added.

**Comment by tlei123** [comment]
Will validate once Staging login issue's resolved.

**Comment by tlei123** [comment]
Closing -- validated on Staging.
