### ISSUE TITLE
Add timezone and day of week to appointment view

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3235]
## Story
As a veteran, I want to see all of the necessary information I need to grasp specifically when my appointment is.

### Timezones:
We need to use the facility timezone for the times on the appointment list page, which come back to us in UTC and are converted to the user's current timezone, currently.

We get timezones for all the VA systems in the public/facility/timezone endpoint. This isn't one we've mapped to vets-api, and it's static data, so I believe we can include it as a json file in vets-website and reference it as static data.

One note: we have timezones for systems, not individual facilities, so we'll need to just use the 3 digit code from the appointment data we have.

### Day of week:
Pretty self-explanatory from the mocks. We need to display the day of the week in the datetime line to give people a better understanding of when their appointment is.

## AC
- [ ] Day of week displays in the date line for confirmed appointments
- [ ] Facility timezone of appointment displays for confirmed appointments

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/68494698-d8ed6d80-021c-11ea-8b26-8c9e57981e07.png)
