### ISSUE TITLE
Add front end review group as CODEOWNERS of content security policy  

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#3236]
# Overview 

Because the FE review group triages the CSP logger, it should be notified when changes are made to the CSP config. 

# Suggested approach  

See [this](https://github.com/department-of-veterans-affairs/devops/pull/5826/files#r342665339) for info on how to implement CODEOWNERS file

- add codeowners file with the configuration mentioned in the comment above
- considering adding front end as the code owner of the react routes https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml
- give the front end review group has write access to the devops repo

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/devops/pull/9677) for this has been merged ✅.

FE Tools is now a CODEOWNER of:
- [ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-dev.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-dev.yml)
- [ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-prod.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-prod.yml)
- [ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-sandbox.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-sandbox.yml)
- [ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-staging.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/content_security_policy_vagov-staging.yml)
- [ansible/deployment/config/revproxy-vagov/vars/react_routes.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml)
