### ISSUE TITLE
Write Cypress test for direct schedule flow using VAOS service endpoints

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#32369]
We have Cypress tests written for the request and community care flow that run with the VAOS service and MFSv2 feature toggles turned on. We should do the same with the direct schedule flow.

Request flow test: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/tests/e2e/va-request.cypress.spec.js#L175

Community care flow test: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/tests/e2e/community-care.cypress.spec.js#L462

It should work to start from a copy of the request flow test and set up the mocks to put the user in the direct schedule flow, and mock the new calls made due to that path (mainly clinics and slots).

**Comment by ldelacosta** [comment]
@vbahinwillit - Tony, Brad G. wanted me to check with you to see if we need to get this done before V2 goes live. Please let me know if this is something we need to put in the Ready queue.

**Comment by vbahinwillit** [comment]
I would say yes.

**Comment by ldelacosta** [comment]
The five end to end test tickets that are a part of this ticket is listed below: 

1) [ appointment-list.cypress.spec.js](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39938)
2) [community-care.cypress.spec.js](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39939)
3) [covid19-vaccine.cypress.spec.js](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39940)
4) [va-appointment.cypress.spec.js](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39941)
5) [ va-request.cypress.spec.js](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39943)
