### ISSUE TITLE
Access for Ryan Koch

### ISSUE THREAD

**Issue by RyGuy0213** [department-of-veterans-affairs/va.gov-team#32375]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Ryan Koch

### Your Email

ryan.koch@agile6.com

### Name of Your Team

Sitewide CMS | Software Engineer | Agile Six

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDswnhoa932h8M5TB97omJuZ9yq0KYXtz43WxfOyUdEhYQGnyW9Y0WVd6RjEzUd9Ih9HB8pRUNPgOc68JW3OlmYbudJWAGe0E4j2yvwbcWUCGzlHPkZ4yp/ixHnaNxQFnxYtCWgLMUaZpSZtAYwQh8/8ZjGqosbz9rwn3MLOjO3MWw15mMv2pjZCWMfuqZdUvp+ugvSPk7f2E2Lmlhk+ayx1/fzZtvSSKIXFALnKTHCZjMlaO7Isd5m95DuI2h5cIdctQuhHUbs9FbQ1V0usjj5Zc1jtbADvhnxrB1NQSsAh2J1f/7sY1wDpu6zbcOu1MXmDyhNa917qIf2xxVZomk3zVFlk6LlnTV/E/Vsn81W+5QMlhkEfCWgvgcbC7qSEIaDfoAD0xznWBMUblSu0cMXae8RxBupq/4iEKS3Ow021JfjhSLl7vnYvDC9JKD562TcfbbeBWCCbfn33njxk57fPNw/bOD67IVEqIrOidXv8sge1hQw2UF8vMGpX6wQZU= rkoch@Agile6-A75

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any further trouble.
