### ISSUE TITLE
Discovery: Vets API to MPI Communication

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#32374]
## User Story

As a Veteran, I need to avoid inappropriate modifications to MPI so that my data remains accurate:
- name (first, last)
- SSN
- DOB

If the user is **authenticated**, we pre-populate some of the fields for them, based on the values in the Master Person Index (MPI). However, these fields are editable, and may be changed by the user.

## Expected Behavior

This is to track work done around researching how Vets API 10-10 EZ/CG submits data to MPI

### Discovery questions
- What data fields are pre-populated/sent along w/ submission?
- How do we carve out the locked-down fields (i.e. make them uneditable) vs. everything else that pre-populates 10-10ez now?

## Acceptance Criteria
- [ ] Verifying no changes made to MPI by the 10-10ez for authenticated users: First Name, Last Name, SSN, DOB
- [ ] Create any follow-up backend tickets as needed

**Comment by MickinSahni** [comment]
Update: got to the point of submission, now need to understand what happens within Sidekiq

**Comment by MickinSahni** [comment]
@jchilders this may help: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26762

**Comment by MickinSahni** [comment]
May be useful to check with another form that locks down bio data e.g. the 526 team

**Comment by jchilders** [comment]
Verified with ES team that this is happening. Per Joshua Faulkner, this is due to the unique identifier for that user being included in the payload that is received by them. This is happening when a user logs in, but fills out the 10-10CG form for another user. (For example, when a logged in user fills out the form for a technically inexperienced friend.)

Current recommended fix:

1. Prevent first name, last name, date of birth, and Social Security Number ("the fields") from being modified on the front end.
2. A change to the back-end is also recommended, although optional. Specifically, after the user submits the form, but before their data is submitted to CARMA, the fields should be verified to contain data unmodified from what was originally received from MPI.

Because step (1) will prevent modification of the data in the fields, and step (2) will verify that this data has in fact not been modified, and that there are no known vectors for the data in the fields to be changed, step (2) can be considered optional, although desirable. Given these factors, as well as the roadmap, this item can be prioritized accordingly.

**Comment by MickinSahni** [comment]
Thanks, @jchilders! Closing this out with #32137 as the front-end ticket (i.e. 1. on your list) cc @JSorensen55
