### ISSUE TITLE
[UX] Next-of-Kin: Add Details to NOK Page for Purpose of Information 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32373]
## User Story
As a Veteran, I want to see details on the NOK page so that I have an understanding of why this information is being presented/confirmed. 

## Description
During usability, there was feedback from veterans (a smaller percentage) voicing concern/interest in why NOK is needing to be confirmed and/or updated. This seemed to cause worry for some veterans, so we want to add a brief blurb on the NOK screen with details as to why this info is collected in the importance of having it up to date. 

## Acceptance Criteria
- [ ] Review work done in pre-check-in and add it to the day of check-in experience. Determine is any changes need to be made for the day of experience.
- [ ] Review attached [document] (https://app.zenhub.com/files/133843125/f60b530f-db93-4623-821a-74c7314a1343/download) for the NOK purpose and definition.
- [ ] Determine content to be added to the NOK page.
- [ ] Mockup wireframes
- [ ] Review with appropriate team(s) (Product, Content, etc.)

**Comment by julieadair1** [comment]
This effort has already been completed as part of MVP.  Closing this ticket.
