### ISSUE TITLE
[PM] Complete Privacy and Security Review Request

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32378]
Complete questions in Privacy and Security Review request - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/346

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel when you have a chance, can you go to our Privacy and Security Review request for the PDF Modal -- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/346 and answer the FE questions and any BE questions you are able?  Thanks!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO , a question. I think we should amend this bit because of the analytics we are adding? 

<img width="758" alt="Screen Shot 2021-11-03 at 12 46 02 PM" src="https://user-images.githubusercontent.com/26075258/140105030-d6a380c6-ea3d-4836-a83e-05840eae8972.png">

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel good catch.  Yes, please change that.  Thank you!!

**Comment by zacharymorel** [comment]
Done now for my part I think

**Comment by MarciMcGuireGCIO** [comment]
Whoo hoo!  Thanks!
