### ISSUE TITLE
Offboarding of Snehal(Neil) Desai

### ISSUE THREAD

**Issue by jlang10761** [department-of-veterans-affairs/va.gov-team#32388]
Name: Snehal(Neil) Desai
Github Account: hazelvision
Company: Coforma
Team/Role: Account Manager for CEDAR
Last Day: 10/29/2021
Reason for Offboarding: Contract ended and resource rolled off the project.

Resource's VA account was removed via another request. Requesting GitHub removal.

**Comment by jsgarmon** [comment]
@jlang10761 : to be clear, this is _only_ for GitHub removal? Is there anything else under [general acceptance criteria](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=vsp-product-support%2C+operations%2C+Offboarding%2C+analytics-insights&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D) that the user might have access to?

**Comment by jlang10761** [comment]
> @jlang10761 : to be clear, this is _only_ for GitHub removal? Is there anything else under [general acceptance criteria](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=vsp-product-support%2C+operations%2C+Offboarding%2C+analytics-insights&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D) that the user might have access to?

@jsgarmon Correct, users va email and slack were removed with other tickets(before we became aware of this template). User did not have access to AWS or any other of the items in the description. Github should be all that we require for this ticket.

**Comment by jsgarmon** [comment]
User removed from GitHub org
