### ISSUE TITLE
Conduct UAT for Dep Ver

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32384]
8 session but they will be short

**Comment by candy-gcio** [comment]
Perigean has scheduled 5 more participants for us for late next week (next sprint). Here are the [session notes](https://governmentcio-my.sharepoint.com/:x:/g/personal/candy_clark_gcio_com/ETECGnNSxJNIs7yLhv40P6AB_a5ifp2nvlrbY0Yr2tN_qA?e=AzqMnI) for the ones we have seen so far.
