### ISSUE TITLE
Scaffold out the SAHG Mockup

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32385]
wire frame is fine
use cases
some IA suggestions
kick off (Jason)
this is really to prep for design intent

**Comment by candy-gcio** [comment]
These are [initial wireframes](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a) for the happy path. I have several questions for our contacts that will fill out details, particularly on the intro and confirmation pages.
