### ISSUE TITLE
Create Outbound Integration tests in smoke tests repo

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32381]
The task requires capybara tests be created for outbound integration testing at its most basic level. The intent is that we will iterate on creating more tests for a more robust integration suite over the next 6 months. The table below lists the initial requirements for this specific task. Future iterations are in the [alerting and monitoring epic](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/31428).

- [x] Create outbound use case checklist for capybara tests (Joe)
- [ ] Add all outbound tests to smoketest repo (capybara) (Josh)
- [x] Modify buildspec in AWS (change to 5.0 image) once permissions allow (Alex)
- [x] document how often we are going to run the tests
- [x] document how we are going to report on the results
- [x] Follow up with Chelin regarding the possibility of using datadog for live monitoring of all environments
- [ ] All Documentation for this effort should go (here)[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/identity/Identity_Integration_Tests.md]

| Status                     | ID              | Inbound Scenarios                           | CSP     | Login From               | End                      | Level of Authority | CSP Designation | Can they login to va.gov successfully? | Questions | Answers | Notes       | Test account to be used for this validation |                                          |
| -------------------------- | --------------- | ------------------------------------------- | ------- | ------------------------ | ------------------------ | ------------------ | --------------- | -------------------------------------- | --------- | ------- | ----------- | ------------------------------------------- | ---------------------------------------- |
| Done                       | Outbound-4      | standard (mfa)                              | dslogon | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | LOA2               |                 | yes                                    |           |         |             | ace.a.mcghee1                               |                                          |
| Done                       | Outbound-10     | standard (mfa)                              | idme    | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | LOA1               |                 | yes                                    |           |         |             | joe.niquette+loa1idmstaging@oddball.io      |                                          |
| Done                       | Outbound-11     | standard (mfa)                              | idme    | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | LOA3               |                 | yes                                    |           |         |             | vets.gov.user+24@gmail.com                  |                                          |
| Done                       |                 | standard (mfa)                              | idme    | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | LOA3               |                 | yes                                    |           |         | Cerner user | ssoissoetesting+SPO1@gmail.com              |                                          |
|                            | Outbound-20     | standard (mfa)                              | Lgov    | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | IAL1               |                 | yes                                    |           |         |             | joe.niquette+lgovial1@oddball.io            |                                          |
|                            | Outbound-21     | standard (mfa)                              | Lgov    | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | IAL2               |                 | yes                                    |           |         |             | joe.niquette+lgovial2@oddball.io            |                                          |
| Done (confirmation needed) | Outbound-31     | return to location login was initiated from | mhv     | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | LOA1               |                 | yes                                    |           |         |             | dskevin1                                    | will only work with unified sign-in page |
| Done (confirmation needed) | Outbound-32     | return to location login was initiated from | mhv     | [va.gov](http://va.gov/) | [va.gov](http://va.gov/) | LOA2               |                 | yes                                    |           |         |             | vets250                                     | will only work with unified sign-in page |
| Done (confirmation needed) | Unified\_MHV-4  | standard (mfa)                              | dslogon | MHV                      | [va.gov](http://va.gov/) | LOA2               |                 | yes                                    |           |         |             | ace.a.mcghee1                               |                                          |
| Done (confirmation needed) | Unified\_MHV-11 | standard (mfa)                              | idme    | MHV                      | [va.gov](http://va.gov/) | LOA3               |                 | yes                                    |           |         |             | vets.gov.user+24@gmail.com                  |

**Comment by joeniquette** [comment]
Permissions for to modify the codebuild policy, which will allow us to change the container version for our integration tests has been opened. The group in charge of the ticket stated they are looking into resolving a problem where they have too many policies which are targeted at the very one we need access to. We hope to have this resolved by the EOD 11/8. Until then we can continue on the documentation side but cannot continue to test the builds until the permissions issue is resovled.

**Comment by joeniquette** [comment]
Permissions is validated to be all set. We are getting a new error in the build phase: `[Container] 2021/11/08 18:34:14 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION). Reason: exit status 252`

I was able to verify that we can use datadog to access the VA network testing resources, the issue was that we had to turn off cert errors (TIC was causing cert issues). Once the codebuild components are locked in then we can pivot to the datadog monitoring tests (This is a ticket John already has).

**Comment by joeniquette** [comment]
Tests will be run at least once daily at 1600 ET. All major releases for the Identity team will run on-demand. The test coverage will be for staging only (for now).

**Comment by joeniquette** [comment]
Test results will be reported through the codebuild reporting dashboard. All results will be published via slack. If a test fails, this would be considered a P2 until it is determined if the test fail is true (and not a change to the frontend that caused the test to not complete correctly).

**Comment by nsoutouras** [comment]
MSI - Still wrestling with codebuild.  Should finish this sprint.

**Comment by joeniquette** [comment]
documentation will be part of tech debt, not a release blocker. The outbound capybara tests are a must complete prior to release.

**Comment by nsoutouras** [comment]
Nick: Engineer - Adds the ability to have more confidence in making changes to our infrastructure.

**Comment by joeniquette** [comment]
Until further notice the use of capybara is being paused and being put into tech debt for the BE team to revisit in the future.

**Comment by AGarcia-Clarity** [comment]
This might be able to be closed in favor of DataDog Synthetic testing.
