### ISSUE TITLE
create rspec tests for all use cases with saml response

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32383]
### User Story
**As an** Engineer
**I want** to be able to run tests mimicking external dependency authentication
**So that** I have a higher degree of confidence in infrastructure changes

Tests will be added to `vets-api`

**Comment by nsoutouras** [comment]
Nick: As an engineer, I should be able to run tests that mimic external dependency authentication, in order to have more confidence in changes made to infrastructure.

**Comment by joeniquette** [comment]
this will be done before putting down login.gov blockers resolved
