### ISSUE TITLE
Change Facebook link in right rail of Burials hub landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#3239]
## User Story or Problem Statement
Link to the Facebook page on the right rail of the Burials and Memorials hub landing page needs to be updated. It currently links to the VeteransBenefits Facebook page and instead should go to NationalCemeteries. 

![Screen Shot 2019-11-08 at 1.34.50 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/3917d455-fe9d-41be-9c1c-8abbaa61b8ae)

New link to be updated: https://www.facebook.com/NationalCemeteries on this page:
https://www.va.gov/burials-memorials/

**Comment by RLHecht** [comment]
@jenniferlee-dsva This page is now updated with the correct Facebook link. Here's the preview link if you want to send to SMEs:  preview-prod.vfs.va.gov/preview?nodeId=78

Moving this to validate. 

@Karak888 for awareness.

**Comment by RLHecht** [comment]
Validated on live site. Closing issue. @Karak888 and @jenniferlee-dsva for awareness.

**Comment by Karak888** [comment]
Thanks @RLHecht a.k.a. superwoman!
