### ISSUE TITLE
Access for Denise Eisner

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-team#32398]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Denise Eisner

### Your Email

denise.eisner@civicactions.com

### Name of Your Team

VA.gov, Content Strategist, CivicActions

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjzelnXVS9LDzhncUefSyLJlJnjMr7N7TJOks1mNF0uXKJdlkH2UdJsaefsFSDlQ0qc7eRAVAFrd2TnhVv38rKw/TipY2ke+JLqVl7N7XaaARGZjUTkl6xIO2uSM8yPYFw0qdwktZw/Y8GmuG8yamD7NjYCkb5SSbSWWvIpO6VOJTIV3/08m8OdRKZ/pTAK5HqiWqqDdRguAfPzLma9gwQufulNUYRwYJhqwAf/801AsG/MFKFpUwMSSpH9B1EU0tyioCFp62lNTrERCzEqA3VlPq2RF6RGtdpqnUNpx2OjygMUq7cCwS2WLCh7EcIpMU7HFlT7YO5r1ulmpfeRD7zP32uPdEIL5ridoWMmsflrJ3vwrkHyKA7Zg1wTcOInsFh03FLtEGqHimgiWjXkK3HOfuqX13iC9b0mJw3NvkuEO2lIInFAuOSqCE9CXnetkSa2fQU+TVkmqYAa1jqoMTIQ2vhqO1e/85XFdRU1MOJlJZj/V1sX+MevLiTcYqoYtM= deniseeisner@Denises-MacBook-Air.local

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any further trouble.
