### ISSUE TITLE
[Research] User Roles Research: SME interview synthesis

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#32405]
Create a document outlining the key findings from the SME interviews conducted in #32292 

**Tasks**

- [x] Draft findings
- [x] Review with team
- [x ] Publish final doc

**Comment by andaleliz** [comment]
[Draft of synthesis started here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/user-roles/discovery/sme-interviews/user-roles-sme-interview-findings.md)

**Comment by andaleliz** [comment]
Update - I have a solid draft posted on GH; waiting for 2 more interviews to complete this week before I can close this out.  Moving to next sprint.

**Comment by andaleliz** [comment]
Sharing [folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/user-roles/discovery/sme-interviews/session-notes) with session notes.

**Comment by andaleliz** [comment]
@Samara-Strauss I have a draft of my findings ready for your review - I'm excited to hear your thoughts! I received some feedback that the report could benefit from some visualization to clarify where roles do/don't overlap, so I added a simple Venn diagram with some examples. I'm particularly interested to know if you think this is helpful to the doc.

**Comment by Samara-Strauss** [comment]
Awesome! I'll review on Friday :D

**Comment by Samara-Strauss** [comment]
This is great!! Thoughts and questions below:

> We initially planned to learn about NCA user roles as well, but decided to hold off for the time being since NCA does not have digital products that intersect with VA.gov.

Totally a suggestion, but might be helpful to mention this was per OCTO leadership given that we don't currently have tools relevant to NCA on VA.gov.

> A dependent is someone who has a legal relationship with the Veteran, and is financially dependent on the Veteran.

Is it worth mentioning here something like, "Dependents may or may not also be beneficiaries."?

> A delegate role exists in VHA to refer to people who have been assigned delegate authority per the request of a Veteran through the VA online health delegation program.

Does VBA have the concept of a delegate? If not, I would call that out specifically.

> Power of Attorney (POA) refers to a person who the Veteran has given power of attorney to act on their behalf at the VA.

How is this different from a delegate? One sentence explaining the overlap or lack thereof might be helpful.

> A person can have multiple connections to the VA.

I would clarify that you mean a person could fall into multiple categories that you listed.

> Findings details

Suggestion: for each section, include a recommendation. So for 1. Dependents, the recommendation would be that this user type does not need a user role on VA.gov if they are not also a beneficiary. Just a thought, and totally up to you to implement this suggestion or not.

> 2. A beneficiary is...

Question -- do you have a sense of whether this user type would need to interact with a veteran through VA.gov? Let's assume they are *not* a caregiver; I know a beneficiary who is also a caregiver would need to manage a veteran's account. I'm more talking about someone who is not a caregiver or veteran and receives benefits from the VA. Do they need sign-off from a veteran on anything to apply for or manage their benefits? It's OK if you aren't sure. Let me know either way.

> 3. A Veteran's caregiver... 

I have the same question for all of the caregiver categories you listed. What determines whether a caregiver should be allowed to access a veteran's information?

> VHA doesn't use the term "delegate", but VA Form 21-0845 gives a 3rd party access to information for a Veteran.

Is this supposed to say VBA?

> As a starting point, explore two primary non-Veteran user groups for VA.gov: Veteran advocates (people who do work on behalf of the veterans - caregivers, VSO representatives, claim agents, attorneys, and fiduciaries).

From reading the more detailed findings, it sounds like there are already systems for VSOs, claim agents, and attorneys and one for fiduciaries. Is your recommendation that we prioritize these users on VA.gov along with caregivers and delegates?

**Comment by andaleliz** [comment]
Thanks @Samara-Strauss! You always give such good feedback - I feel like working with you has made me a better writer and leveled up my UX work.

>Totally a suggestion, but might be helpful to mention this was per OCTO leadership given that we don't currently have tools relevant to NCA on VA.gov.

Suggestion taken - thank you.

 > How is this different from a delegate? One sentence explaining the overlap or lack thereof might be helpful.

I updated all of the key findings accordingly, except this one. It's not easy to explain this in one sentence, but I'll add some elaboration in the finding details.

> I'm more talking about someone who is not a caregiver or veteran and receives benefits from the VA. Do they need sign-off from a veteran on anything to apply for or manage their benefits? It's OK if you aren't sure. Let me know either way.

That's an interesting question, and I don't know. I didn't dig into the journey of an existing beneficiary who wants to apply to receive additional benefits, or even the initial application process. I focused on the role once they already have benefits.

>What determines whether a caregiver should be allowed to access a veteran's information?

There aren't any rules around this specifically, but a major consideration would be the Veteran's need. I can think of a couple of use cases where it's clearer than others (below), but generally speaking, it's on a case-by-case basis.
- If a Veteran requests their caregiver serve as their online health delegate, or grants access via VA Form 21-0845
- if the VA determines a Veteran is unable to care for themselves through the disability rating process. I'm 99% sure the Caregiver would not be granted access without the Veteran signing off on something though. However, I'm not sure what would be done in the case of a Veteran who is simply unable to do that. 

I think for VA.gov purposes, there'll have to be a few different caregiver roles, or a combination of caregiver + access type.  E.g. Caregiver - Full access (all benefits and actions, Caregiver - Health, Caregiver - other benefits, etc. I can update the recommendations to include this. 

Would it be helpful for me to dig in further to answer the things I'm not sure about above?

>Is your recommendation that we prioritize these users on VA.gov along with caregivers and delegates?

My recommendation would be that those users be prioritized after caregivers and delegates. They already have systems in place to serve them.

**Comment by Samara-Strauss** [comment]
> I updated all of the key findings accordingly, except this one. It's not easy to explain this in one sentence, but I'll add some elaboration in the finding details.

I'm not seeing updates. Did you do this in a branch and not merge?

> That's an interesting question, and I don't know. I didn't dig into the journey of an existing beneficiary who wants to apply to receive additional benefits, or even the initial application process. I focused on the role once they already have benefits.

Got it, and totally fine. I think this is something people will want to know, BUT that doesn't mean you need to figure it out right now. Perhaps just make a recommendation that we should explore the beneficiary <> veteran relationship further as far as online interaction goes.

> I think for VA.gov purposes, there'll have to be a few different caregiver roles, or a combination of caregiver + access type. E.g. Caregiver - Full access (all benefits and actions, Caregiver - Health, Caregiver - other benefits, etc. I can update the recommendations to include this.

Great! Definitely include this in your recommendations.

> Would it be helpful for me to dig in further to answer the things I'm not sure about above?

I don't think you need to do this right now. More specific technical needs should be assessed in future research.

> My recommendation would be that those users be prioritized after caregivers and delegates. They already have systems in place to serve them.

Got it. This was not clear to me with how things were worded in the recommendations section (it was clear earlier in the doc). It would be helpful to more explicitly make this distinction.

**Comment by andaleliz** [comment]
>I'm not seeing updates. Did you do this in a branch and not merge?

Nope, I had made all the updates locally and was waiting for your reply before updating so I could include it all at once.  It's all published now! Let me know if you have any additional edits.

I'm thinking as a final step, I'll set up some time with John and Cody (including you) to walk them through this. How does that sound to you? Anyone else I should include?

**Comment by Samara-Strauss** [comment]
Awesome! Most of the changes look good, though I did notice that your venn diagram isn't loading, so I'm not sure if something broke there.

> Veteran advocates (people who do work on behalf of the veterans - caregivers, VSO representatives, claim agents, attorneys, and fiduciaries).

By listing out VSO representatives, claim agents, attorneys, and fiduciaries, it sounds like you are implying these people should be part of the veteran advocate role. While they may be, given that there is much higher priority for caregivers and delegates, I would remove them from this list and explain below that we do not recommend addressing those roles immediately since there are already VA systems to support them.

> I'm thinking as a final step, I'll set up some time with John and Cody (including you) to walk them through this. How does that sound to you? Anyone else I should include?

Nope! John and Cody should be it.

**Comment by andaleliz** [comment]
Ah, thanks for catching that broken link! Didn't have the GH link in my local file.

>By listing out VSO representatives, claim agents, attorneys, and fiduciaries, it sounds like you are implying these people should be part of the veteran advocate role. While they may be, given that there is much higher priority for caregivers and delegates, I would remove them from this list and explain below that we do not recommend addressing those roles immediately since there are already VA systems to support them.

I can see how that's confusing. I updated the recommendation section to clarify that I don't think we should focus on those now, and explicitly named beneficiaries and delegates rather than lumping everyone into one broad "Veteran advocate" group. There's so much nuance among those roles and it's not necessary (or helpful) to put them in one bucket for these purposes.

Here's the final version; I'll set up a meeting with everyone ASAP pending availability and holiday PTO.

**Comment by Samara-Strauss** [comment]
> Here's the final version; I'll set up a meeting with everyone ASAP pending availability and holiday PTO.

Great! Looking forward to it.

> I can see how that's confusing. I updated the recommendation section to clarify that I don't think we should focus on those now, and explicitly named beneficiaries and delegates rather than lumping everyone into one broad "Veteran advocate" group. There's so much nuance among those roles and it's not necessary (or helpful) to put them in one bucket for these purposes.

Did you push these updates from your local version? I am still seeing the language "Veteran advocates (people who do work on behalf of the veterans - caregivers, VSO representatives, claim agents, attorneys, and fiduciaries)"

**Comment by andaleliz** [comment]
I did pushed the updates - just did again. Let me know if you don't see it.

**Comment by Samara-Strauss** [comment]
Thank you! This is SO much clearer!! Great job :D
