### ISSUE TITLE
Adding Becca Vasil to DSVA Slack

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/va.gov-team#32400]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Are you requesting to add an individual as a:

- Full member ✅ 

- What channel(s) do they need to be added to?
  - #va-notify-automatic-alerts
  - #va-notify-public
  - #va-notify-team

Becca Vasil is a Thoughtworks developer joining the VANotify team.

Her email is: rebecca.vasil@thoughtworks.com

**Comment by LizCallaghan** [comment]
added to slack and two channels, but can't find #va-notify-automatic-alerts

**Comment by ffafara-tw** [comment]
Thanks. I can see Becca in all our channels.
