### ISSUE TITLE
[FE] Find a VA Form PDF Modal - Add analytics to detail page and search results page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32404]
## Issue Description
Add analytics tags in Sprint 61

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by zacharymorel** [comment]
Analytics should be live now!

**Comment by MarciMcGuireGCIO** [comment]
You are kicking butt!

**Comment by MarciMcGuireGCIO** [comment]
Awesome! Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel is this something that needs to be validated by the analytics team?  Thx!
