### ISSUE TITLE
Make New Use Case Spreadsheet 

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#32401]
## Technical Task

We have use cases and we have accounts that satisfy them but the account to use case is mismatched. Make new spreadsheet that has account to use cases documented correctly for QA testing.

## Expected Behavior

The spreadsheet allows QA to know which use case data is satisfied by what test user

## Acceptance Criteria

- [ ] Make spreadsheet that maps use cases to accounts

**Comment by denisecoveyduc** [comment]
@LinnJS just wanted to ensure you saw this as well. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Docs/MCP-Use-Cases.md ;)

**Comment by LinnJS** [comment]
[Spreadsheet](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B4740A2A0-0BD1-4332-B7CC-DFB39981A4A1%7D&file=MCP%20Clarified%20Use%20Cases.xlsx&action=default&mobileredirect=true) that was created as a result of this ticket.
