### ISSUE TITLE
[FE] Profile: Update alert that appears when a user has been flagged as incompetent

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32416]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user has been flagged as incompetent and therefore not authorized to access their financial information.

See also #31406 and #31407 

This ticket is for [**Updates to alerts item 10**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#10-user-has-been-flagged-as-incompetent-so-they-cant-access-their-financial-information) in the supporting documentation.

## Tasks
- [ ] Update the alert that appears when a user has been flagged as incompetent and therefore not authorized to access their financial information per the copy and specs in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#10-user-has-been-flagged-as-incompetent-so-they-cant-access-their-financial-information)
- [ ] Test

## Acceptance Criteria
- [ ] The confirmation alert that appears when a user has been flagged as incompetent and therefore not authorized to access their financial information is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#10-user-has-been-flagged-as-incompetent-so-they-cant-access-their-financial-information)

**Comment by andaleliz** [comment]
Closing, will address in #40722
