### ISSUE TITLE
Access for Joseph Niquette, Trevor Bosaw, John Bramley, Alex Garcia, Josh Scanish to AWS Codebuild

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32422]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Joseph Niquette

### Your Email

joe.niquette@oddball.io

### Name of Your Team

Identity

### Service(s) You Want Access To

AWS

### Desired AWS Services

The folks listed within the title need write access specifically to the codebuild project `sso-smoketests-ci`. We are planning to use codebuild to run monitoring of our external dependencies and validation testing for our changes. Due to the nature of the external CSPs and IAM being outside of vets-api, we need a more robust automated testing mechanism. Using codebuild in AWS is the first phase of building out these mechanisms. 

All of us already have extensive AWS access, I am respectfully requesting that write access to codebuild be added to the vsp-identity team within AWS, at minimum for the project `sso-smoketests-ci`.

**Comment by jsgarmon** [comment]
Members of the vsp-identity team (currently the five people listed here) have been granted access to this CodeBuild project.

**Comment by joeniquette** [comment]
@jsgarmon Sorry but there is one set of permissions that wasnt set that certainly wasnt known to me to be required prior. I am getting an error:
`User: arn:aws-us-gov:iam::008577686731:user/Joseph.Niquette is not authorized to perform: iam:CreatePolicyVersion on resource: policy CodeBuildBasePolicy-sso-smoketests-ci-us-gov-west-1` When trying to update the environment image for our project. The current image is `aws/codebuild/standard:2.0` which apparently is no longer supported so we cannot use it. We need to change it to 4 or 5.0 but in order to do that we need the `CreatePolicyVersion` added to our permissions within my team. Again I really only need it for our project, no other permissions required. Is this something you can help with as part of this ticket or should I create a new one?

**Comment by jsgarmon** [comment]
Hi @joeniquette : I'm looking into this. The `codebuild-service-role` needs to be able to create and modify CodeBuild policies, and it's already at it's policy limit of 10. I'm looking into ways around this.

**Comment by jsgarmon** [comment]
I have updated the environment to `aws/codebuild/standard:5.0`. It's using a different service role, and I've given your team permission to pass this role to the CodeBuild service. I've also given your team  `CreatePolicyVersion` permission for the new policy so you can make updates directly.

I'll keep this issue open until you verify that everything is working as expected.

**Comment by joeniquette** [comment]
thank you..I will verify soon.

**Comment by joeniquette** [comment]
Sorry forgot to update you on this. I was able to change the build environment and continue with out effort. Thank you for updating our permissions, we should be all set to close this ticket now.

Thanks @jsgarmon !

**Comment by andreahewitt-odd** [comment]
Trevor Bosaw eqip confirmed 11/15/23
