### ISSUE TITLE
[UX] Poster Updates Tabloid (24x36 for Low-vision first)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#32438]
## Description
We need to make some updates to the poster based on feedback and specific needs for the prosthetic clinic expansion. 
1.  We need some verbiage that indicates this is for veterans that are there for the prosthetic clinic (only 1 in 3 vets in this waiting area will have a prosthetics appointment).
2.  We need to account for low vision patients.
3. We need to resize to tabloid.

## Tasks
- [x] Create PDF

## Acceptance Criteria
- [x] Post to GitHub (need to add link)
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md

*Note - @jparker0425 and @julieadair1 to confirm projected go live date for this clinic

**Comment by julieadair1** [comment]
@kristenmcconnell , @jparker0425 - do we have an epic to attach this to?

**Comment by kristenmcconnell** [comment]
@julieadair1 Do we have an epic for our accessibility explorations? This could be added there.

**Comment by julieadair1** [comment]
@kristenmcconnell I just created one.  I'll attach this to it.
