### ISSUE TITLE
SD - GA dashboard investigation on R&S action links tag

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#32430]
## Issue Description
_Investigate if action links are being correctly tagged and tracked since it was converted from action buttons._

---
## Tasks
- [x] _Collaborate with analytics team to learn how action links are tagged if they are tracked the same as they were buttons_

## Acceptance Criteria
- [x] _Confirm if there is or not a tagging/tracking discrepancy between action links and action buttons._

**Comment by LindaLi123** [comment]
Investigation findings: when links and action links were created,  they were being tracked at a different place than the buttons and the report we looked at had a big decrease was the tracking for buttons.  When we see the report that's actually tracking action links there isn't a decrease in click rate.

**Comment by mgleo** [comment]
[CTAs started tracking as 'action links' on Sept 17 and need a separate GA URL](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31783#issuecomment-962172458)
