### ISSUE TITLE
Identify which forms patterns are missing documentation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#32437]
Would like a list of forms patterns that are not documented. 

Here is an example of the list that Crystabel did when we were working on an initiative to document forms patters. 
https://docs.google.com/spreadsheets/d/1_ml9wTnqhQHcrmS728AsGeZ34OdR67Gp0dJn1Wh3-FA/edit?usp=sharing

- [ ] Create a list of forms patterns that do not have any documentation

**Comment by humancompanion-usds** [comment]
We have a prioritized list of patterns we are working on. https://github.com/orgs/department-of-veterans-affairs/projects/779/views/2
