### ISSUE TITLE
Prometheus is Unreachable from Within VA Network

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#32440]
## The Problem
Prometheus can't be reached in the browser from within the VA network.
![image](https://user-images.githubusercontent.com/3077884/140401003-01363983-c022-4cc3-91d4-5fead02ab67b.png)

## Extra Context
- Grafana and Jenkins are both accessible
- DNS is resolving properly
![image](https://user-images.githubusercontent.com/3077884/140401646-d363e77b-f2b4-47a6-b1eb-3b2d7ce5ffaf.png)

## Work to be Done
- [ ] Restore connectivity from VA to prometheus

**Comment by jhouse-solvd** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team-sensitive #422](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/422) via [**ZenHub**](https://www.zenhub.com/)
