### ISSUE TITLE
upgrade credstash to 1.16.1

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3246]
We need to intentionally upgrade credstash as the next version (1.16) makes a change to how version numbers are set automatically [1].  This requires a migration script to be run to fix versions in the data-store so coordination will be required.  We should also test backup / restore before we do this.

1 -https://github.com/fugue/credstash#special-note-for-those-using-credstash-auto-versioning-before-december-2015

## AC
- [x] Tested and a backed is available 
- [x] Credstash is upgraded successfully

**Comment by benniemosher** [comment]
We can not upgrade to v1.17.x until we upgrade to Python v3.
