### ISSUE TITLE
VA Profile zip code input field should require 5 digits

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3248]
currently the Zip Code field on the address edit modals show an error if the user has entered more than 5 characters. The field validation should be updated to:

- require exactly 5 characters
- only allow numbers

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/853769b8-2090-40f6-9aee-42484e96bd37)

**Comment by Justin-Pickett** [comment]
@erikphansen can this be closed?

**Comment by Justin-Pickett** [comment]
PR #11225 Merged and Closed. Closing this ticket.
