### ISSUE TITLE
[Bug] Search Type Ahead - v2 - IE11 styling anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#32485]
## What happened?
In **Internet Explorer 11**, on **[Staging homepage](https://staging.va.gov/)**, page-header **Search > Type Ahead dropdown** was not aligned with text-field above.

**Screenshot**:

![ta-bug-ie11-header-dropdown](https://user-images.githubusercontent.com/587583/140434904-645f8e95-5779-467b-b06e-42d94acc2b6a.png)

## Specs:
- Device: Windows 10 desktop
- Browser: IE11

## Steps to Reproduce
- URL: https://staging.va.gov/
- In **page-header**, click **Search**, then in **text-field** input **ebe**.
- Observe that type-ahead dropdown is not aligned with text-field above, but rather misplaced to the right.

## Desired styling
- [x] Type Ahead dropdown should align with text-field above.

**Mockup screenshot** [disregard highlight-color which should now be primary-blue]:
![ta-spec-header-dropdown](https://user-images.githubusercontent.com/587583/140435304-4287721b-5bc1-41ae-86d6-763d26b04e94.png)

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by srsuddath** [comment]
Hey @tlei123 can you tell me what browser you were using when you got the above misalignment? I am trying to replicate it but am unable to

**Comment by srsuddath** [comment]
sorry I just saw your comment , its IE11, I will see what I can do to fix it

**Comment by srsuddath** [comment]
This issue has been fixed and is live on staging!
![image](https://user-images.githubusercontent.com/47081947/142086429-dc7b9fb0-c76d-4207-900d-fea99e1c16c1.png)
