### ISSUE TITLE
[SPIKE] Scope/story writing for eng work 

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#32504]
- Ticket about NoK verbiage on page to indicate it is a routine update/not to alarm users- Corey to create ticket
- Ticket about emergency contact updates- put in Icebox
- Ticket about surface app status + logs to a developer dashboard of app health
- Ticket to research the authorization/login step and pass the user back to where they left off in the flow
- Ticket to research/confirm assumptions around how Demographics and NoK confirmations show up when the user has multiple appointments (it is thought this is already handled w/the existing functionality rather than giving the user multiple alerts to confirm/update these things)
- Epic? Needed indicating the requirements for “Pre-Check In”:
  *Intro page
  *Demographics confirmation page
  *Login/authorization
  *Edit page for Demographics
  *Next of Kin
  *Either an editing page or way to flag NoK needs updates
  *Review page
  *Confirmation Page
  *URL Content/Messaging (not sure what this is?)
- Add ticket for post-MVP feature- provide user some option via email to update their info if they’d prefer to proceed that way
- Per Stephen, suggest having one front-end engineer coordinate closely with CHIP/LoROTA team and work off of their board to help with the pre check in stuff on their side. Need to coordinate w/that team, and create a card on our board that links to what they’re working on for tracking.
- Add icebox ticket for health questionnaires (?)

**Comment by jparker0425** [comment]
@sarahknoppA6 closing this item out. Looks like it was used for tracking some discussion items for Pre-Check-in when we were still scoping. PCI is out now so will open specific tickets for anything moving forward for post-MVP.
