### ISSUE TITLE
Scan Remediation - BigFix (SCCD) FY21 ATO

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#32501]

**Comment by jwowk** [comment]
Remediate findings from BigFix (SCCD) scan. Need to identify what Rob and Andy can handle and what requires the platform teams assistance.

https://dvagov.sharepoint.com/:f:/r/sites/vhavetext/TeamShare/ATO_2021/Scans?csf=1&web=1&e=DvadFt

**Comment by lindsay-insco** [comment]
Due January 2022

**Comment by jwowk** [comment]
Platforms team in progress with re-baseline of VEText Linux servers.
