### ISSUE TITLE
Compile data on buttons vs action links to identify conversion rate

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#32515]
Look at 10 URLs of buttons vs. action links and capture change in conversion rate for uniques. This is the kind of documentation Kevin expects to move this pattern to the official design system

- [ ] Identify 5-10 URLs with buttons and action links
- [ ] Compile conversion rate for each of the URLs for buttons 
- [ ] Compile conversion rate for each of the URLs for action links
- [ ] Show conversion rate for each of the  URLs between buttons and action  links

**Comment by caw310** [comment]
@GnatalieH @k80bowman , let's work together on this.

**Comment by caw310** [comment]
For reference here are notes to the DSC meeting where this request came up. 
https://docs.google.com/document/d/19S91ebu98NLVE_JyJDydHBzcqou3zwXBku1HkuyHKrE/edit?usp=sharing

**Comment by k80bowman** [comment]
Do we know, did we only transition from buttons to action links? Or are there places were we transitioned from regular links to action links?

**Comment by caw310** [comment]
I don't know. We will need to check with Shawna, possibly or Liz on this.

**Comment by caw310** [comment]
@KevinMHoffmanUSDS , a few of us have had discussion on how to evaluate action links. Here is the thinking based on those discussions with Katy, Allison, Natalie and myself. We think we should change what data we're going to gather. Our proposal is to do A/B test with action links versus text links to find out click through / conversion rate. Are you okay with this? Do you want to bring this back up to DSC? 

Here are the tasks we will need to do: 
1. Identify application(s) for research 
-  identify where action links are used
 - reach out to teams using action links about participating in research 
2. Develop a research plan (work with Naomi) for measuring /testing 
3. Work with team to run tests
4. Analyze and compile test results
5. Present test results to DSC

**Comment by k80bowman** [comment]
URLs where buttons have been updated to action links:
1. https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg
    - Updated from button to action link on [May 13](https://github.com/department-of-veterans-affairs/vets-website/pull/17175/files)
2. https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction
    - Updated from button to action link on [August 19th](https://github.com/department-of-veterans-affairs/vets-website/pull/18326/files)
    - To see the action link, you have to move through the form a little:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/033ce38c-f5a3-499d-99f5-950cb72d971b)
3. https://www.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs/
    - Updated from button to action link on [September 17th](https://github.com/department-of-veterans-affairs/content-build/pull/560)
4. https://www.va.gov/resources/are-service-dogs-allowed-in-va-facilities/
    - Updated from button to action link on [September 17th](https://github.com/department-of-veterans-affairs/content-build/pull/560)
5. https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/
    - Updated from button to action link on [September 17th](https://github.com/department-of-veterans-affairs/content-build/pull/560)
6. https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start
    - Updated from button to action link on [June 1st](https://github.com/department-of-veterans-affairs/vets-website/pull/17412/files)
    - To see the action link you need to move through the form a little:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/8dc55559-c521-4be7-bc75-419cdad28ff8)

**Comment by GnatalieH** [comment]
@k80bowman thank you so much!

**Comment by GnatalieH** [comment]
FYI I've submitted a support request with Analytics to help find the historical data for these URLs, so we can compare 30 days before and 30 days after a Button changed to an Action link.

**Comment by GnatalieH** [comment]
Here are the GA reports I found from Megan in the DSC notes. I added the secondary dimension of "page" for the Action links report so we can compare URLs:

[Buttons](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20211001&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22www.va.gov~2Fresources%22,0%5D%5D&_r.drilldown=analytics.eventLabel:cta-button-click/)

[Action links](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20211001&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventLabel:cta-action-link-click&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D/)

The following 5 URLs can be compared, but I'm unsure when the Button changed to an Action link on each page, so I don't know the date ranges to check:

www.va.gov/resources/signing-in-to-vagov/
www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/
www.va.gov/resources/verifying-your-identity-on-vagov/
www.va.gov/resources/change-your-address-on-file-with-va/
www.va.gov/resources/how-to-change-direct-deposit-information-for-va-education-benefits/

@k80bowman or @caw310 do you have any suggestions on how to compare the date ranges for each of these 5 URLs? This is where I'm stuck. Thanks.

**Comment by GnatalieH** [comment]
[Here is a link](https://dsva.slack.com/archives/CBU0KDSB1/p1639100454212600?thread_ts=1638893701.026100&cid=CBU0KDSB1) to the Slack conversation between me and Brian Marten from Analytics. It contains several resources including a link to a custom report. Just wanted to make sure it was attached to this ticket.

**Comment by k80bowman** [comment]
@GnatalieH I should be able to find the date that the change from button to action link was made for those pages.

**Comment by GnatalieH** [comment]
Buttons date range: August 16-September 16
Action links date range: September 18-October 18

https://www.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs/ (View your payment history)

- [Button](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210816&_u.date01=20210916&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:cta-button-click,analytics.eventAction:Primary%20Button%20CTA%20-%20View%20your%20VA%20payment%20history%20-%20rgb(0%25252C%20111%25252C%20184)/) (August 16-September 16): 344
- [Action link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210918&_u.date01=20211018&_r.drilldown=analytics.eventLabel:cta-action-link-click,analytics.eventAction:Secondary%20Action%20Link%20CTA%20-%20View%20your%20VA%20payment%20history%20-%20blue&explorer-table.plotKeys=%5B%5D/) (September 18-October 18): 1,491

https://www.va.gov/resources/can-i-plan-ahead-for-my-burial-in-a-va-national-cemetery/ (Learn about pre-eligibility)

- [Button](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210816&_u.date01=20210916&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:cta-button-click,analytics.eventAction:Primary%20Button%20CTA%20-%20Learn%20about%20pre-need%20eligibility%20-%20rgb(0%25252C%20112%25252C%20185)/): 65
- [Action link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210918&_u.date01=20211018&_r.drilldown=analytics.eventLabel:cta-action-link-click,analytics.eventAction:Secondary%20Action%20Link%20CTA%20-%20Learn%20about%20pre-need%20eligibility%20-%20blue&explorer-table.plotKeys=%5B%5D/): 1,670

https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/

- [Button](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210816&_u.date01=20210916&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:cta-button-click,analytics.eventAction:Primary%20Button%20CTA%20-%20Get%20Arlington%20National%20Cemetery%20details%20-%20rgb(0%25252C%20111%25252C%20184)/): 31
- [Action link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210918&_u.date01=20211018&_r.drilldown=analytics.eventLabel:cta-action-link-click,analytics.eventAction:Secondary%20Action%20Link%20CTA%20-%20Get%20Arlington%20National%20Cemetery%20details%20-%20blue&explorer-table.plotKeys=%5B%5D/): 707

**Comment by caw310** [comment]
@GnatalieH , please share findings with Kevin.
