### ISSUE TITLE
idea: see if we can run clamd as a network service for vets-api

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3251]
clamd is a glut (lots of install deps, big memory footprint, big disk footprint). See if we can centralize it and run it as a network service:

- run clamd as a network service for STREAM requests
- see if we can make vets-api use this (seems like we probably can)

If this works, make it prod.

**Comment by ricetj** [comment]
We would need to do this before we docker all the things.

**Comment by jhouse-solvd** [comment]
@ericboehs - this is an old ticket, and not sure if it's of any utility / relevance at this point. would you have any ideas here?

**Comment by jhouse-solvd** [comment]
@jeff2d2 - Can you give this a peek and possibly raise it with your team to see if it's something of interest or fits into any of your upcoming work? It's quite old and I'm trying to determine if it's still relevant.

**Comment by ericboehs** [comment]
@cbtkc I think this is related to Tiger team work

**Comment by jhouse-solvd** [comment]
@cbtkc @ericboehs - I added it to that epic so that we can discuss in one of our sessions.

**Comment by jhouse-solvd** [comment]
In speaking w/ the team, we wouldn't see this as part of Tiger Team work. We do think that it's something worth doing, but the priority and sense of urgency is very low.

**Comment by dginther** [comment]
The Tiger team separated clamd out to it's own container as part of their work, so this may not be necessary/useful anymore.
