### ISSUE TITLE
Content Review -Outreach & Events Enhancements from Public Websites Team

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32518]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [X] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
- [Link to product Initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts/Initiative%20Briefing.md)
- [Whiteboard sketch or other lo-fi prototypes or wireframes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/design)
- [User flow Outreach & Events MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/o%26e-calendar-feature-baseline.md)
- [COA Use Case Workflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/COE_Usecase_Workflows_1.png)
- [Updated Wireframes](https://sketch.com/s/ceaa48f6-88f4-48d1-9578-7f6751a8ab74)

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Dec 18, 2021
- Estimated staging review date: Dec 16, 2021
- Content and IA work needed by: Looking for a content copy review on the verbiage used in the highlighted focus areas for our new design elements.  **See Screenshots below:**

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [X] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: David Conlon
-	Product manager: Brian Lloyd
-	Designer: Cassandra Allen
-	FE engineer: Kelson Adams
-	Product/team Slack channel: #public-websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by callen2563** [comment]
@RLHecht Here is the [Sketch file](https://www.sketch.com/s/ceaa48f6-88f4-48d1-9578-7f6751a8ab74) for your review

Title and intro copy are not changing for this MVP effort but these are the areas we need help with:

- Wording like "**+12 more occurrences**" this wording is for an event that might repeat and might have more than one date or time.
- Also, can you take a look at the date formatting
- Button copy like "view more"

<img width="340" alt="Screen Shot 2021-11-05 at 4 56 56 PM" src="https://user-images.githubusercontent.com/68560244/140577754-3cf5c89d-f227-42ce-8f55-37160b09c3da.png">
s
<img width="350" alt="Screen Shot 2021-11-05 at 4 57 04 PM" src="https://user-images.githubusercontent.com/68560244/140577786-41fb7ae2-3932-488b-bb56-649bab4f091d.png">
<img width="475" alt="Screen Shot 2021-11-05 at 4 57 38 PM" src="https://user-images.githubusercontent.com/68560244/140577808-d7e29711-87c5-46af-a84e-760da57f4e0e.png">

**Comment by cindymerrill** [comment]
To provide more useful information, @callen2563 and I would like to change `+ 12 more occurrences` in the Event List to a more descriptive phrase like `Repeats every 2 weeks` or `Repeats daily`.

Perhaps this should also change in the accordion `View 12 more occurrences`?

**Comment by cindymerrill** [comment]
We also propose simplifying the dropdown options to the mutually exclusive `Upcoming events` and `Past events' to address the UX problem uncovered in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32436#issuecomment-965858942). @callen2563

**Comment by cindymerrill** [comment]
I am proposing changing the date filter dropdown options to 
![image](https://user-images.githubusercontent.com/69914583/141600597-3dc5e266-5789-4cfa-b5fc-d4a8dd544e66.png)

**Comment by RLHecht** [comment]
@callen2563 @cindymerrill Here are our edits. Some of these changes are for text that was only in the Sketch file not in the screenshots above. Let me know if any are unclear:

**Date and time:** Per [our style guide](https://design.va.gov/content-style-guide/dates-and-numbers), we should have a period at the end of abbreviated months and a comma after the year. Time zone is abbreviated as ET (PT, MT, CT).

Take out the @ before the time. Use an en dash (not a shorter hyphen) instead of using "from" and "to." Like this:

When: Thursday, Oct. 28, 2021, 3:00 p.m. – 5:00 p.m. ET.

**Location:** Instead of just "Online event" change it to "This is an online event."

**Cost:** Don't use all caps for "FREE"

**For the accordion:** We don't want to use sighted language and "occurrences" is not very plain language. Our suggestion is: Find other times for this event

**Button:** Change from "View more" to "Check other times" to avoid sighted language.

**Link:** "See more events" link at very bottom should change to "Find more events" also to avoid sighted language. 

Also note that "Add to Calendar" should be sentence cased. "Add to calendar"

Happy to answer any questions!

**Comment by callen2563** [comment]
@RLHecht Thank you! 
@cindymerrill No need to update the spreadsheet it's easier if I just use the list above to make the edits.

**Comment by RLHecht** [comment]
@callen2563 Just confirming we can close out this ticket as there's no more work needed from us.

**Comment by cindymerrill** [comment]
I think it's done. Do you agree, @callen2563 ?

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
