### ISSUE TITLE
Build onboarding process and tools

### ISSUE THREAD

**Issue by nprimak** [department-of-veterans-affairs/va.gov-team#32521]
## Issue Description
Create onboarding experience that addresses CEDAR IDIQ paint points.

## Acceptance Criteria
- [x] MO leadership engaged for download on company onboarding.
- [ ] Other OCTO prime contractors engaged for download on OCTO onboarding.
- [x] Team members engaged to uncover pain points in onboarding.
- [ ] Current onboarding guides for Apartment reviewed.
- [x] Onboarding materials developed.
- [ ] Agenda for Project Onboarding meeting created.
- [ ] Project Onboarding agenda socialized with Team MOVE leaders.
- [ ] Agenda and tools iterated based on feedback and develop Rev 1 of materials to address pain points and create seamless experience considering MO FTE, CEDAR partner, OCTO FTE.

**Comment by SKasimow** [comment]
Hi - was this meant to be on the 10-10 Team Board?

**Comment by SKasimow** [comment]
@tameracorson Hi - was this meant to be on vsa-10-10 board?

**Comment by tameracorson** [comment]
@SKasimow It 28 days ago. Looks like Michelle-dooley moved it?  Feel free to close or delete.  This was on health-apartment board... we turned that project in to the VA January 11th.  The VA plans to reopen after they settle on where / how it fits on MyVA.  Either way .... all icebox, etc... will be redone at that time.
