### ISSUE TITLE
Figure out where the data is coming from/going

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#32527]
This ticket is to figure out where to get data for Pre-Check In.

- Figure out data sync for demographics + NoK
- Should the data be coming from VA Profile or VistA? (do we care about VA Profile for MVP?)
- Action to ask the VA Profile team about demographics and NoK data (Julie and Corey?)
- Look at Cerner for MVP
- Who is using the reconciled data/where does this get consumed downstream?

here is some info about VA Profile:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md

**Comment by julieadair1** [comment]
@jparker0425 - which epic does this belong with?

**Comment by loripusey** [comment]
@sarahknoppA6 do we still need this ticket?

**Comment by sarahknoppA6** [comment]
@loripusey no, it can be closed. I think there's still some confusion around the usage of VA profile for editing capabilities (as you've heard yesterday in our meetings) but this is addressed in other tickets at this point, and it seems like we're trying to use VA profile in the near future.
