### ISSUE TITLE
Analytics Discovery - [Va.gov Mobile Header V2/Public Websites Team/5% Prod Release]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32528]
## Context and Conclusions
What trend/measurable changes have you observed with your products?
_I'm looking for some help in determining best way to track analytics for our new Va.gov Mobile header release to 5% of users in production._  

Talked with @bsmartin-ep with [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1636127829344700) who suggested using this ticket format to capture thoughts and ideas in support. 

## Solutioning Ideas
Initial thoughts: Building a custom GA event you can use to segment sessions where a user gets the new header.
```
{
 event: 'phased-roll-out-enabled',
 'product-description': 'Some description',
}
```
We would just need to know if you are setting this per user or per session when we help build a GA segment to analyze the results.

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)
- [ ] [Initiatives Briefing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Initiative%20Briefing.md)
  
## Acceptance Criteria
- [ ] Documentation: [Linked Above] 
- [ ] Follow-on implementation/discovery tickets created 

## How to configure this issue
- Labeled with team-name

**Comment by brianalloyd** [comment]
@kelsonic looping. you into this ticket as well, as we lean toward releasing this to 5% of the user based, we'll need to follow the above recommendations from Insights team. Let's discuss approach during SU.

**Comment by kelsonic** [comment]
5% of auth users when we're ready, sounds good!

**Comment by bsmartin-ep** [comment]
@brianalloyd / @kelsonic -

Do you need anything from us on this one?

**Comment by kelsonic** [comment]
Hey @bsmartin-ep! 👋 Yes! We need analytic events to fire off for the following behaviors:

1. Toggling expanded/collapsed state for official govt website accordion
![image](https://user-images.githubusercontent.com/12773166/142263100-8a47fd0a-9454-463b-89db-11c448692753.png)

1. Clicking VCL
![image](https://user-images.githubusercontent.com/12773166/142263258-b43d9be7-8b40-4c6f-8683-77ed513b9c35.png)

1. Clicking Logo
![image](https://user-images.githubusercontent.com/12773166/142263340-8bcf56b4-11cd-4126-89c6-6e55c4e49cdd.png)

1. Clicking `Sign in`
![image](https://user-images.githubusercontent.com/12773166/142263499-e66f11b9-1993-4061-8fce-1bd18e67e684.png)

1. Expanding/collapsing `Menu`
![image](https://user-images.githubusercontent.com/12773166/142263562-c2147907-724c-4d12-9f65-473ef00c955c.png)
![image](https://user-images.githubusercontent.com/12773166/142263834-23696088-ae3f-49d8-a548-1c85a15d68f5.png)

1. Expanding/collapsing menu item level 1s
![image](https://user-images.githubusercontent.com/12773166/142264034-e687234f-c56f-4cb0-8624-6a76809b632a.png)
![image](https://user-images.githubusercontent.com/12773166/142264095-9296cf60-996a-4a8d-bf28-08a66a2e636d.png)

1. Clicking menu item level 2s
![image](https://user-images.githubusercontent.com/12773166/142264208-c871cc27-456f-4b73-ae59-215a8aeb9d75.png)

1. Clicking `Back to menu` button
![image](https://user-images.githubusercontent.com/12773166/142264303-b27db792-4e16-4300-b582-2f38dc4ad8c5.png)

Sorry for the long comment, but we need analytic events to fire off for the above behaviors ^ Thank you!! 🙏

**Comment by bsmartin-ep** [comment]
@kelsonic -

Looks like we have tagging on a good chunk of these.  If you need tagging for the remaining 3, can you  send us an implementation request using the "[Analytics Implementation and QA Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=laurensimpson14&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)"?

I'm out 11/22 to 11/26, but @laurensimpson14 and @jennaouellet can triage this in the meantime.  

(Note for you two - we may have legacy events for some of these like the `^nav-header-logo` I see in `Navigation Action - Lookup Table`.  And maybe `^nav-header-link$` for the Back to menu button.)

-----

Interaction|Is it currently tracked?
----|-----
Toggling expanded/collapsed state for official govt website accordion|**el:** int-accordion-expand<br>**ea:** Accordion - Expand - (not set) - Here’s how you know - (not set) - (not set)
Clicking VCL|**el:** nav-crisis-header<br>**ea:** Navigation - Crisis Modal Clicked - Header
Clicking Logo|None (no tracking on non-mobile either)
Clicking Sign in|**el:** int-modal-show<br>**ea:** Modal - Click - (not set) - (not set) - (not set) - (not set) - Sign in 
Expanding/collapsing Menu|None/None
Expanding/collapsing menu item level 1s| **el:** nav-header-top-level<br>**ea:** Navigation - Header - Open Top Level - <text>
Clicking menu item level 2s| **el:** nav-header-second-level<br>**ea:** Navigation - Header - Open Second Level - Health care
Clicking Back to menu button|None

**Comment by brianalloyd** [comment]
@bsmartin-ep @laurensimpson14 @jennaouellet I created ticket [33145](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33145) as requested.  Please let me know what questions remain and appreciate the support.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19498

**Comment by brianalloyd** [comment]
Closing this ticket, will pick up analytics work for Header V2 in implementation ticket.
