### ISSUE TITLE
VAOS breakers metrics not being exported

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3254]
During chats with VAOS in prep for launch, we discovered that the backend is not sending metrics through via the breakers library. They believe that it was setup with breakers, and would like some help diagnosing why metrics aren't being exposed. This seems like a decent opportunity for VSP to introduce some testing or automation to make sure this is being done and doesn't get missed.

**Comment by annaswims** [comment]
updated the example at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/tutorials/endpoint-punch-list-presentation/supporting_code/service-object-implementation.md

**Comment by saneshark** [comment]
I'm removing the VAOS tag, as the changes have now been merged to support metrics properly. Thanks for catching this. I'll leave the issue open though for you all since it also explores the possibility of automating verification of this type of thing.

**Comment by annaswims** [comment]
Added another PR to remove ICN from tag.
