### ISSUE TITLE
VEText User High-Level User Research

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#32541]
Plan for, gather, track, and analyze user data about VAMC personnels’ thoughts on VEText resources.

Living document: https://docs.google.com/document/d/1KYtzFvFbW1QtfSklOleaJzgRvqfqmCz11hUJTRNDanQ/edit#

**Comment by vlivshin** [comment]
@pcshah1026 @aschulhof, I'd love your feedback on this doc: https://docs.google.com/document/d/1KYtzFvFbW1QtfSklOleaJzgRvqfqmCz11hUJTRNDanQ/edit#

**Comment by pcshah1026** [comment]
Great job @vlivshin !  I included a couple of comments/notes.

**Comment by vlivshin** [comment]
Shane approved the research. Next step is wrapping up the survey questions by COB Monday, 11/15.

**Comment by vlivshin** [comment]
@aschulhof @lindsay-insco @pcshah1026, here are the [questions ](https://docs.google.com/document/d/1jA3FVWpn9icJNv80Yin_ut8uDjvi6m1Tk4KetG8xtKs/edit). I added in the objectives and survey script for context. Note that I wrote a lot of questions. Ideally, we should shorten the list so that more people are inclined to submit.

**Comment by vlivshin** [comment]
@aschulhof @lindsay-insco @pcshah1026, here's the survey in Forms! https://forms.office.com/Pages/ResponsePage.aspx?id=Ixtf6a-r7kWCHberJRqzv-zEFcNuAmpMgdaonOL8ZThUOUFCVVg2WDU1UTBHTVpVR05PWDdPNk5VQy4u 

I made a total of  3-4 questions mandatory.

**Comment by aschulhof** [comment]
I think you still need to add logic to only show the specific support deep dive questions if they check the box on question 10 @vlivshin

**Comment by vlivshin** [comment]
Rollout date: dec 1st. 
On dec 1st, announce the survey during office hours and in the teams channel

**Comment by vlivshin** [comment]
@lindsay-insco @shanemelliott, I've attached the VEText Support Resources Survey Analysis document: [https://app.zenhub.com/files/133843125/847a5ff9-ab22-4d71-9439-427842bf9a1a/download](https://app.zenhub.com/files/133843125/847a5ff9-ab22-4d71-9439-427842bf9a1a/download)

**Comment by vlivshin** [comment]
Survey is closed out now. Updated analysis: https://docs.google.com/document/d/1SuLoLf5Me3U9H8jG_5dQe3kRMqS3rp8EhxEQaHQQZCE/edit

**Comment by lindsay-insco** [comment]
Survey closed
