### ISSUE TITLE
[Design] - Profile: Create updated Sketch file for Direct Deposit

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#32555]
## Background
Our Profile 2.0 Sketch file has become unwieldy and out of date, so we need to split it out so that it's more maintainable.  This ticket covers the work needed to create a Sketch file that contains all the states of the direct deposit section of profile.

The original direct deposit mock-ups have been brought over into a new Sketch file called `Profile - Direct deposit`, [available in our SFT instance](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131).

One thing to note - in July 2021, we had a security incident and needed to block access to DD. I had to create an alert for that, so there is one artboard in this file that's already up to date.

## Known updates
- [x] Replace global profile elements (header with nametag, side navigation, section headings) with the symbols from the Profile pattern library
- [x] Replace footers with the symbols from the VA.gov pattern library
- [x] Make sure any buttons that look like links are replaced with the secondary button symbol from the VA.gov pattern library
- [ ] Align margins/padding of containers with what is on staging 
- [ ] Alerts should be updated to reflect changes in [this document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#3-successfully-updated-direct-deposit-information-in-profile-31404)(don't hesitate to ask Liz, this is complicated)
- [x] Additional info components should match what is on [design.va.gov documentation](https://design.va.gov/components/additional-info) (gray chevron w/ dotted line underneath)

## Updates you'll probably need to make but I'm not totally sure about:
In March 2021, education benefits were added to direct deposit and I'm not sure if the Sketch file was updated. @sporeboy (Jim Adams) worked on those updates, and he typically works in XD. You can chat with him about that, or log into staging and manually compare what you see in Sketch to what's out there.

[Staging user log information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md)

I would recommend logging into staging regardless to check for differences in copy, how headings display etc (especially on mobile).

## Acceptance criteria

- [ ] Direct deposit sketch file appropriately matches what we have on staging.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO FYI I spoke to @Samara-Strauss and she agreed that Christina can help me out with #32074 by taking on the direct deposit section. I think this will be a great way to help her start familiarizing herself with profile, this specific feature, Sketch, and how our design files are set-up.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz Sounds like a great plan! Thank you for letting me know!

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske can you please pop an estimate on this task when you have a few min?  Thx!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO just finishing this up now, so will be done shortly! (just added an estimate of 1)

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske when you have a minute, can you please drop the link to the updated Sketch file in here?  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO the updates were made to the existing files so the link included already is correct!

**Comment by MarciMcGuireGCIO** [comment]
Thanks! Hm I wonder if the link has to be published in a different way? I get a message saying it's a private page.

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO does it work now? I changed the sharing access to View. I think it was set to No Access before.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske Yep! You did it! Thank you!
