### ISSUE TITLE
Update appointment list sorting & filtering

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3256]
Currently, we filter the appointment list by date only - so a veteran could in theory see past appointments that happened earlier on today's date. We should decide if we want to continue employing this filtering strategy or switch to filtering on date and time (which in theory could get tricky with timezones).

AC
- [ ] Confirmed & cancelled upcoming appointments are sorted to the top of the unified list, with the soonest appointment sorted to the top of the confirmed appointments stack
- [ ] Requests and cancelled requests are sorted to below the confirmed appointments stack, in alphabetical order by Type Of Care.
- [ ] Past appointments are filtered out by both date and time - i.e., appointments that ENDED earlier today are not visible.

**Comment by rtwell** [comment]
Here's the logic:

1. confirmed "upcoming" appointments are sorted by date, with the soonest appointment first.
2. "past appointments" should be invisible—that is, until we create our "previous appointments" tab. So if there is a 10am and a 1pm, but the current time is 12pm (all of this in the time zone of the facility), the 10am appt would disappear/move to the "previous appointment list". Yes, there _might_ be the case where that isn't ideal, but i believe that is a _very_ edge case. 

If we can somehow know the time zone of the user, and we could be smart enough to show/hide given that time zone, that would be great, but for MVP, let's be rigid.

**Comment by jbalboni** [comment]
@rtwell This doesn't match the way VAOS works now, where it appears to leave appointments visible all day, and they drop off the next day. Which is not a blocker, just wanted to mention it. We're currently matching what legacy does.

Presumably we'd want to leave appts up until they end, not remove them once they start. That would cause problems for video appts, if you were a minute behind and no longer had access to the link. CC appts don't have a duration, so we'd have to make one up for them.

**Comment by rtwell** [comment]
gotcha. sounds like we have a path forward?

**Comment by jbalboni** [comment]
@rtwell One other thing I'm concerned about is that legacy VAOS leaves video links live for 4 hours. If we hide these appointments after 20 or 30 minutes or whatever, are we going to cause problems for people? Maybe they're left active for 4 hours to account for appointments running late?
