### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#32560]
As a VA patient, I would like to receive the check in experience in a language that I can read. 

This ticket is to provide translation support for multiple languages.

**Comment by julieadair1** [comment]
@kristenmcconnell this one feels like it needs some UX research first.  Thoughts?

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA is a good resource on translation, so I would start with her to gain an understanding of what is going on across va.gov with regard to translation.

Danielle - there is a team now working in this space. Who besides you should we talk to about this?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell. I'd be happy to talk with you all to bring you up to speed on translation planning. Feel free to put some time on our calendars. Please also invite Sharon Kasimow and Adam Whitlock as required, and Eunice Garcia and Michelle Steigerwalt as optional.

**Comment by kristenmcconnell** [comment]
Thanks, @DanielleThierryUSDSVA for the contact names.

**Comment by loripusey** [comment]
Move to this [epic](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38257)
