### ISSUE TITLE
[UX] Email Link for Check-in

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#32565]
This is a placeholder for some thoughts we had for the product post-MVP. Some users expressed a desire during usability testing to receive an email to update their information or continue it on their PC so they don't have to rely on the text and mobile interface.

**Comment by jparker0425** [comment]
Closing this item out. We have UX tickets created for this initiative and discussions are taking place around how to handle this.
