### ISSUE TITLE
AWS Staging: Select Request Than Change to Direct Schedule - Ends up as A Request

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#32579]
Steps to Recreate:

1. In VATS configure a type of care DS = Yes and Req = Yes.  I did this for  Amputation (Fort Collins) but type of care does not really matter.  I also tested with Cheyenne and Primary Care, same results.
2. Log in as Judy. Select Amputation. Select Fort Collins.  
3. Select a I need a different clinic.  Select continue.  Calendar displays. Select back button.
4. Select a clinic, select continue.   Enter a date for  appointment, select continue. Calendar displays with all the appointment date/times.  Select a specific  date/time from calendar for the appointment, select continue.  
5.  **Expected response:** Direct scheduling flow displays.  **Actual response:**  The Request flow screens display which are Select a reason and enter comments, select continue.  Select a type of appointment, select continue.  Enter contact information, best times to call and email.   
6.  **Expected response:** Confirmation screen for direct scheduling displays.  **Actual response:** Confirmation screen for request displays.  ![ReqFlowNotDSFlow.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/f1fc5455-af77-44e7-865a-cc23fe395abe)

**Comment by ldelacosta** [comment]
@marcynadeau - this is ready to be tested. Thanks!

**Comment by beth-wodzinski** [comment]
Validated.

**Comment by ldelacosta** [comment]
This has been validated by @beth-wodzinski. Closing out the ticket.
