### ISSUE TITLE
Update the page content doc for confirmed telephone appointments on appointment details page 

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#32580]
## Description
As a veteran, I should see phone appointment instructions on the appointment details screen. Update the page content doc for booked phone appointments on the appointment details page.

<img width="535" alt="telephone details" src="https://user-images.githubusercontent.com/90797205/140837639-d8e96639-8fd3-478d-a7a9-67bc8c4cc9e6.png">

---
## Acceptance Criteria

Given confirmed appointment details page
When user has a telephone appointment scheduled
Then user will see the phone appointment instructions 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md) 
And page design matches the design spec [desktop,](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/jgQeA2m) [mobile,](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/g0Y250k) and [tablet](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/ZOjpQ2x)

### Design Assets
Page structure guide for [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md) section reference

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
**QA Notes 11/8/21**
AWS Staging Telephone Appointments - Needs Instructions for Veteran
Create a pending appointment in VistA in Sid Nurse for a test patient (Ruben Moreno).
Log into VAOS and view upcoming appointments
Select to view appts for 1/01/2022 @0800 in Sid Nurse
VAOS shows as telephone only appt. 

Expected response:  I think we need to add some instructions for the veteran.  Should the veteran call the number provided or will the clinic be calling the veteran?

Actual response:  No instructions or information provided to the veteran on the telephone only appointment.  

Note, this ![VAOSPhoneOnly.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/ba3d095a-aeb8-466c-be69-8b6783666ef9)was recently fixed in MAS 1.28.0 to indicate that the appointment is telephone. So once MAS 1.28.0 goes to prod, I think there should be some instructions.

**Comment by ldelacosta** [comment]
There was a fix in VAOSPhoneOnly.pngwas in MAS 1.28.0 to indicate that the appointment is telephone. This is planned to go out into production sometime next week (Mon/Tues). Once it goes out into production, we will re-validate if the issue still exists.

**Comment by ldelacosta** [comment]
@ marcynadeau - This is ready to be tested. Thanks!

**Comment by marcynadeau** [comment]
Tested and passed. See screenshot of past and upcoming telephone appt.  ![TelephoneClinic.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/88023816-9acf-4781-afdf-1dfc385a9b34)
