### ISSUE TITLE
Implement expiration dates into PromoBanner

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#3258]
We want to take our current PromoBanner (the Veterans Day Proclamation) down at a scheduled time that is off-cycle to our deployments. So, we either need someone on-call to do a manual deployment, or implement an expiration date for PromoBanners to automatically unpublish them.

**Comment by Karak888** [comment]
Thanks @ncksllvn - I'm closing this puppy out now!
