### ISSUE TITLE
[BUG] Google Analytics opt-out component

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32587]
## Issue Description
_Following the instructions to opt out of Google Analytics.  Everything appeared to work (blue button turned to a gray, disabled button, and the text changed to indicate that I had opted out).  This was done in multiple browsers and problem was replicated._

_Bug is identified when refreshing the page, the button return to its initial, blue state.  It was expected that the cookie would be read and the button state/text would indicate that opted out was already selected._

[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1636148793398100)

## Possible Solution: 
-Ticket to address this page, we should probably audit all pages in our legacy cms: https://github.com/department-of-veterans-affairs/vagov-content/tree/master/pages

- Link to where HTML lives: https://github.com/department-of-veterans-affairs/vagov-content/blob/master/pages/analytics-opt-out.md

- Link to Live page: https://www.staging.va.gov/analytics-opt-out.html

## Acceptance Criteria
- [x] Legacy code is supporting GA opt-out component 
- [x] Opt-out element is working as desired 
- [x] Bug is resolved, tested and validated 
- [ ] Ticket is closed with work is complete.

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tmac9494** [comment]
@brianalloyd I currently have a solution hacked together that sets a new custom cookie that tracks through the render but Im worried this only solves the issue visually. Upon further investigation I have found that there is no new cookie or window variable being added. Im reaching out now to other parts of the team to see if there is another location where this state lives or if there is a problem with the 'analytics-opt-out' event.

As @kelsonic mentioned in the slack thread; this event doesn't seem to have been iterated on for some time so Im thinking we may be using an outdated method to opt out of the service. According to google docs there is a new window variable that should be set and it's not present here.

**Comment by tmac9494** [comment]
After a couple of iterations we landed on adding a new react component to handle the opt-out functionality, I added functionality according to the google analytics documentation. The vets-website PR needs to be merged before we merge vagov-content branch to ensure there is not a blank page in the meantime at va.gov/analytics-opt-out.

https://github.com/department-of-veterans-affairs/vets-website/pull/19855 - react app pr
https://github.com/department-of-veterans-affairs/vagov-content/tree/issue-32587-analytics-opt-out - vagov-content updated branch

**Comment by brianalloyd** [comment]
Closing ticket in support.
