### ISSUE TITLE
Re-geocode in gibct

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#32584]
In production CT, we need to regeocode locations in comparison tool. Here are notes we have received from BAH:

It is recommended that the location data supporting the CT Redesign Location Search is reviewed prior to production release. Several institutions are missing or have incorrect latitude and longitude values. The Census Location Batch Address Tool can provide much of the missing data. There are links and instructions in GIDS for populating the missing data in batches of 10,000. The data can be exported, submitted to the Census tool and uploaded back into GIDS. Some of the incorrect data would have to be reviewed manually. This includes some institutions where the address of the main institution is used in branches located in completely different locations. These could cause issues for the end users of the location search.

**Comment by mrblanco1** [comment]
Currently working on Staging.  Will need to be merged to Sandbox when ready.
