### ISSUE TITLE
508-defect-4 [MOTION]: Consider a less intrusive animation for users with vestibular disorders

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#32583]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Noah

## User Story or Problem Statement

As a Veteran with a vestibular disorder, I don't want to see a relatively large looping animation which could trigger headaches or sickness.

## Details

I've listed this as a defect level 4 as loading screens typically don't require the user to look at the page itself to be operable (because it's loading). That being said, it still may be worth exploring more calm alternatives to the current loading animation. For example:
- Using a smaller, less frequently looped animation
- Providing messages every couple of seconds to provide textual, instead of animated, feedback e.g. (Loading --> Still loading --> Something might be wrong because of [x])

A note-- we shouldn't use a css reduced motion query here as the animation itself is providing feedback that something is still loading. Pausing the animation may create the appearance that it is frozen.

**Comment by bkjohnson** [comment]
Solved in the linked PR
