### ISSUE TITLE
Put feature flag in front of redesigned CT

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#32585]
Currently the redesigned CT lives in a sandbox location, different from the current CT.

We need to put a feature flag on the current CT URL where:

If the flag is active, it goes to the redesigned CT
If the flag is inactive, it goes to the current CT

**Comment by jfinnern** [comment]
Error in staging env when attempting to enable flag to On status:
![Screen Shot 2021-11-19 at 12.32.54 PM.png](https://images.zenhubusercontent.com/60e85c574d27f28c9ab35457/662ee266-6f58-4e23-bba0-586aa1a9b238)

**Comment by SebVortex** [comment]
PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/19540

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2636&group_by=cases:title&group_order=asc
Test case: 
[Put feature flag in front of redesigned CT.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7634807/Put.feature.flag.in.front.of.redesigned.CT.xlsx)
<img width="1442" alt="Screen Shot 2021-12-01 at 8 19 39 AM" src="https://user-images.githubusercontent.com/86262877/144255635-1c574533-85f4-428c-a77d-8dff8d3bf2f9.png">
