### ISSUE TITLE
Help Desk / ServiceNow Configuration

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#32592]
Awaiting followup with VA/general IT request Idea manager to continue discovery on ServiceNow access and configuration requests
- Contacting WW today

**Comment by chancetheoriginal** [comment]
Progress on hold pending followup with WW.

**Comment by chancetheoriginal** [comment]
Still no update from WW. Reached out to another OIT / SNow contact, Matthew Ganesy, says he will also take a look and report back early this week (11/15).

**Comment by chancetheoriginal** [comment]
Received response from OIT-SMO with a questionnaire to be filled out.
- Filled out questionnaire and returned.

Awaiting response.

**Comment by chancetheoriginal** [comment]
Met with OIT SMO for ServiceNow AG creation and Power Apps/ServiceNow connector.
- Requests submitted, awaiting followup.

**Comment by jwowk** [comment]
OIT will not allow at this time
