### ISSUE TITLE
Display the Clinic Location information to the user on the appointment details page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#32593]
## Description
On the appointment details page, the veteran does not currently see the clinic location only clinic name. 
After the veteran books an appointment, the veteran will see the clinic location on the appointment details page. 
Update the page content on the appointment details page with the clinic location information.

**Current Appointment Details Page after booking a new appointment:** 
![Screen Shot 2021-12-13 at 2.49.37 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/333bf661-06f3-43a3-a43f-688d2b9ee5d0)

**Current Appointment Details Page when viewing an upcoming appointment:** 
![Screen Shot 2021-12-15 at 9.56.44 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/dbdaa1a1-b2a4-4ab0-845c-eadabbf03370)

## Acceptance Criteria

Acceptance Criteria 1 
Given the user books a new appointment, 
When the user is confirmed with the appointment, 
Then user will be able to see the clinic location on the confirmation details page, 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/dlQRdz3), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/dlQRdz3), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/Qb5EyKY) 

Acceptance Criteria 2
When the user views their upcoming appointment details, 
Then user will be able to see the clinic location on the confirmation details page, 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/dlQRdz3), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/dlQRdz3), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/Qb5EyKY) 

Mobile Design Spec (Example): 
![Screen Shot 2021-12-13 at 10.48.04 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/b43ddd33-8cdf-421a-a9f3-2d18f165ddd6) 

### Design Assets
[Design File](https://www.figma.com/file/8gMPlMTBrvSSQ9PFoFdajP/Add-clinic-location-%2332593?node-id=0%3A1)
Page structure guide for [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
In today's Backlog Refinement meeting, the team will need to look at the VETS-API to see if we are pulling the correct field for clinic location. Reference ticket that worked on pulling the clinic location info: #32594

**Comment by jenniemc** [comment]
@grossb1 @laurenernest @ldelacosta , When making a foodAndNutrition clinic call to the vaos service api, the `physicalLocation` returns inconsistent data. One clinic returns "1-128", while another returns "PSYCH SERVICE". Whereas at Fort Collins VAMC, the clinic returns physicalLocation as "FORT COLLINS, CO".  Another concern is would exposing any data that displays "PSYCH SERVICE" violate PHI?

For example, making the network call to Cheyenne VAMC
`https://staging-api.va.gov/vaos/v2/locations/983/clinics?clinical_service=foodAndNutrition`
 it will return two clinics with following attributes
{
        "id": "336",
        "type": "clinics",
        "attributes": {
            "vistaSite": 983,
            "id": "336",
            "serviceName": "CHY NUTRITION",
            **"physicalLocation": "1-128",**
            "phoneNumber": null,
            "stationId": "983",
            "stationName": "CHYSHR-Cheyenne VA Medical Center",
            "primaryStopCode": 123,
            "primaryStopCodeName": "NUTRITION/DIETETICS-INDIVIDUAL",
            "secondaryStopCode": null,
            "secondaryStopCodeName": "*Missing*",
            "patientDirectScheduling": true,
            "patientDisplay": true,
            "char4": null
        }
    },
    {
        "id": "707",
        "type": "clinics",
        "attributes": {
            "vistaSite": 983,
            "id": "707",
            "serviceName": "CHY NUTRITION/SATP",
            **"physicalLocation": "PSYCH SERVICE"**,
            "phoneNumber": null,
            "stationId": "983",
            "stationName": "CHYSHR-Cheyenne VA Medical Center",
            "primaryStopCode": 124,
            "primaryStopCodeName": "NUTRITION/DIETETICS-GROUP",
            "secondaryStopCode": 513,
            "secondaryStopCodeName": "SUBSTANCE USE DISORDER IND",
            "patientDirectScheduling": true,
            "patientDisplay": true,
            "char4": null
        }
    } 



When making a network call to Fort Collins to foodAndNutrition clinic
`https://staging-api.va.gov/vaos/v2/locations/983GC/clinics?clinical_service=foodAndNutrition`
it will return
{
    "vistaSite": 983,
    "id": "674",
    "serviceName": "FTC NUTRITION",
    **"physicalLocation": "FORT COLLINS, CO",**
    "phoneNumber": null,
    "stationId": "983GC",
    "stationName": "CHYSHR-Fort Collins VA Clinic",
    "primaryStopCode": 123,
    "primaryStopCodeName": "NUTRITION/DIETETICS-INDIVIDUAL",
    "secondaryStopCode": null,
    "secondaryStopCodeName": "*Missing*",
    "patientDirectScheduling": true,
    "patientDisplay": true,
    "char4": null
}

**Comment by laurenernest** [comment]
@jenniemc this change should be for v0, not vaos service. we can make a separate ticket for that. i also don't trust the data in staging to represent what's in production. do you have production examples? cc @grossb1 

@Cieramaddox what should it look like if we don't have the physical location

**Comment by jenniemc** [comment]
@laurenernest, v0 does not contain clinic location detail only v2 does. I do not have examples pulled from production, but I understand staging pulls data from CDW, Central Data Warehouse. cc @grossb1

**Comment by laurenernest** [comment]
which toggle will it be behind so we can document in the ticket? cc @ldelacosta

**Comment by laurenernest** [comment]
Moving this to Product backlog. We were notified that there might be a bigger effort time the display of this data. cc @JRRoof

**Comment by outerpress** [comment]
@ldelacosta work on this is done from a design perspective, moving to Product backlog

**Comment by ldelacosta** [comment]
We will not focus on this work for 3Q2022. We will revisit the requirements during the next PI planning (ETA October 2022).

**Comment by ldelacosta** [comment]
Moving to the block queue. Need to re-review with the team.

**Comment by JRRoof** [comment]
Replaced by Github issue [#69444](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69444)
