### ISSUE TITLE
Passing through the Clinic location information to the front end UI 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#32594]
## Description
Backend will pass through the clinic location to the front end UI. 

---

## Acceptance Criteria
When a request is made to the vets-api collecting the facility information, backend will pass through the clinic location.  

Current state to fetch the facility information: 
`{"vistaSite":983,"id":"570","serviceName":"CHY C&P AUDIO","stationId":"983","stationName":"CHYSHR-Cheyenne
        VA Medical Center","primaryStopCode":203,"primaryStopCodeName":"AUDIOLOGY","secondaryStopCode":450,"secondaryStopCodeName":"COMP
        & PENS (C&P) EXAMS","patientDirectScheduling":false,"patientDisplay":true}`

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by laurenernest** [comment]
Here's the link to the Slack conversation https://dsva.slack.com/archives/CMNQT72LX/p1635981661044200

**Comment by grossb1** [comment]
Not all the clinics have the physicalLocation field populated.

**Comment by laurenernest** [comment]
@grossb1 which vaos service toggle is this work behind?
