### ISSUE TITLE
Credentials to Transfer Report from S3 Bucket into BigQuery

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#32595]
## Description
My team is seeking to complete [this ticket](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/31980) by ingesting the report from `s3://apps.dev.va.gov/coverage/test-coverage-report.json` into BigQuery using the [BigQuery Data Transfer Service](https://cloud.google.com/bigquery-transfer/docs/s3-transfer#console). 

To fulfill this request, an Access Key ID & Secret Access Key are needed.

## Background/context 
Screenshot of Access key ID & Secret Access key needed 
![image](https://user-images.githubusercontent.com/72466113/140786631-300fa7e4-a715-4748-96d7-83c33822dd42.png)

---
## Tasks
- [x] _Generate Access Key ID & Secret Access Key for report at the following path `s3://apps.dev.va.gov/coverage/test-coverage-report.json`_
- [ ] _Credentials successfully pull report_

**Comment by jsgarmon** [comment]
@rjohnson2011 : a key has been created for this service. Credentials are in parameter store, which you should be able to access via the AWS console.
`/dsva-vagov/testing-team/bigquery_aws_api_key_id`
`/dsva-vagov/testing-team/bigquery_aws_api_key_secret`

Please close this issue when you've verified the service is working as expected.
