### ISSUE TITLE
Refactor 'verify' auth path

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#32605]
post-Login.gov using "minimum" authn_context_comparison headers we should be able to refactor our upcerting logic & remove complexity. Our Login.gov implementation is already using "minimum" headers - as soon as Login.gov updates their service to automatically upcert users with "minimum" headers the feature should be enabled and we will be able to remove upcerting functionality from the 'verify' path.

**Comment by bramleyjl** [comment]
post-Login.gov using "minimum" authn_context_comparison headers we should be able to refactor our upcerting logic & remove complexity.

**Comment by AGarcia-Clarity** [comment]
I believe this can. be closed @nsoutouras
