### ISSUE TITLE
Makefile CI V.S Local Development Refactor

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#3260]
### The Problem
In our vets-api `Makefile`, we have targets that use:

- `COMPOSE_DEV` or `COMPOSE_TEST`
- `BASH_DEV` or `BASH_TEST`

Each target uses either `DEV` or `TEST` which leads to target duplication, e.g. `make test` & `make ci-test`. This model is unsustainable and not readable.

### Additional Context
The `makefile` was designed this way to support use in CI (`COMPOSE_TEST` & `BASH_TEST`) as well as local developer use (`BASH_DEV` & `BASH_TEST`).

### Work to be Done
- [ ] Allow for the environment to be specified one the command line inline with the makefile call
- [ ] Consolidate the make targets in our `makefile` to have one target per task

**Comment by LindseySaari** [comment]
Working on this as time permits
