### ISSUE TITLE
[Administrative] CAG & Venafi access for John Stevens-Garmon

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#32621]
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices.

### Tasks
Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG and Venafi

### Acceptance Criteria
The team member will be able to do the following:

  - [x] Access CAG
  - [x] Access [Venafi](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)
  - [ ] Request SSL certificates

**Comment by jhouse-solvd** [comment]
@jsgarmon - Please share the current status as time allows, please.

**Comment by jbritt1** [comment]
This done?

**Comment by jsgarmon** [comment]
Waiting on ticket completion:
![image.png](https://images.zenhubusercontent.com/614de3ab25470e8cb6e1d4bb/ef496faa-dbf5-4f1f-94bd-9ba4d6cdd22e)

[Link on ticket](https://yourit.va.gov/nav_to.do?uri=u%5Fwork%5Ftask%2Edo%3Fsys_id=75b7922f1b3bb85018da5316624bcb5a&view=sp&id=form&table=u_work_task) just takes me to the main yourit.va.gov page (I'm guessing I don't have permission to see the ticket itself)

**Comment by jsgarmon** [comment]
I'm in the Venafi portal. What is meant by "Request SSL certificates" @jhouse-solvd?

**Comment by jhouse-solvd** [comment]
@jsgarmon - I think just that you have access to the portal and know how to use it for managing certs
