### ISSUE TITLE
[Administrative] CAG & Venafi access for Ryan Beckwith

### ISSUE THREAD

**Issue by rbeckwith-oddball** [department-of-veterans-affairs/va.gov-team#32620]
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices.

### **Tasks**
 

- [x] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG and Venafi

### **Acceptance Criteria**
 The team member will be able to do the following:

- [x]  Access CAG

- [x]  Access Venafi

- [ ]  Request SSL certificates

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball - - Please share the current status as time allows, please. If you have the ability to request SSL certs, then this can likely be closed.

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball has left the team, and this access is no longer required. We can revisit the issue if needed. 

Closing.
