### ISSUE TITLE
Replace 'messages' mock data with API call

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3262]
Messages are not currently retrieved from the `messages` vets-api endpoint, because it has not yet been available. Once available, we want to retrieve actual 'message to scheduler' data to show in the appointments list.

**Comment by markgreenburg** [comment]
Possibly a dupe of #3162

**Comment by narin** [comment]
Yes, this work is covered in #3162.  Closing out.
