### ISSUE TITLE
Eligibility timing out (Frontend Test VAOSR-2565) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#32636]
The fix for the following VAOSR ticked that was released 
This fix needs to be validated via an end to end testing on the frontend.

[Reference VAOSR-2565](https://issues.mobilehealth.va.gov/browse/VAOSR-2565)

**Comment by grossb1** [comment]
The back-end has validated that this is no longer an issue.  Front-end need to validate through the UI.

**Comment by cferris32** [comment]
Backend testing has verified this fix in vets-api
