### ISSUE TITLE
Adding Gloria Scott to DSVA Slack

### ISSUE THREAD

**Issue by pamlo412** [department-of-veterans-affairs/va.gov-team#32632]
The following individual gloria.scott@adhocteam.us needs be added as a full member guest to the following channels:

design
feedback-backchannel
general
product
random
status
vetsgov-accessibility
vfs-all-teams
victories
vsa-ebn-migration

Glo is a new Product Manager on VA API (Lighthouse). She is on the Bandicoot team, which is working to implement Backstage as an internal developer portal for all VA developers, not just Lighthouse developers. 

Initially, she is most likely to have reason to post and read in the victories, design, product, and feedback-backchannel channels. The others I've included because they are what we all get by default on Lighthouse and have potential uses for us, depending on our particular work.

**Comment by LizCallaghan** [comment]
done!
