### ISSUE TITLE
Rebalance Cypress parallelization in GitHub Actions

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#32647]
This task is to rebalance Cypress test selection on GitHub Actions by always running selected tests in eight containers regardless of the number of tests that need to be run in order to reduce CI times.

**Comment by pjhill** [comment]
We have a few days worth of data now.

1. Is there any analysis that we can do to understand how much time is being saved by this change?
2. Can we take any other measurements to understand the impact of this optimization?
3. Are there any further optimizations to make? A PR with 5 relevant specs probably doesn't need 8 containers for example.

**Comment by ddzz** [comment]
> We have a few days worth of data now.
> 
> 1. Is there any analysis that we can do to understand how much time is being saved by this change?
> 2. Can we take any other measurements to understand the impact of this optimization?
> 3. Are there any further optimizations to make? A PR with 5 relevant specs probably doesn't need 8 containers for example.

We have a few days of data in Domo, which is showing a downward trend in test times on CI. I think we need another week or so of data to have a better understanding of the impact here due to the day-to-day variation in which tests are being run, and because some older branches haven't picked up these parallelization changes.

I can't think of any other data we can use. The dashboard in Domo is tracking test times and number of containers being used, which seems like all we need.

We could further optimize the workflow to use fewer containers. Right now if there are less than eight tests the container still starts up, but Cypress does not run in it, so those parallel steps finish pretty quickly. On average, though, we've been using 5+ containers on branches, so it seems like builds with less than eight tests are relatively uncommon.
