### ISSUE TITLE
Create Clinic Cancellation Reports

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#32642]

**Comment by jwowk** [comment]
Create reports in VEText portal or Power BI for Clinic Cancellations. Sites have requested a report to see which Veterans were sent cancellation messages, what the message sent was, and any responses.

**Comment by lindsay-insco** [comment]
Awaiting Data - @wamccarty

**Comment by lindsay-insco** [comment]
@robertdurkin look at LF email

**Comment by jwowk** [comment]
User requested following two reports:
1.	Identify which Veteran’s did not receive message due to being opted-out
2.	Have a report for the Clinic Cancellations that shows the Other Comment field from VistA: Other  #COO# PID 10/14/2021 F/U, PVR 12/3/2021 (see below)
This information is very important for schedulers when rescheduling the cancelled appointments.

**Comment by lindsay-insco** [comment]
@shanemelliott awaiting data
