### ISSUE TITLE
Adding Paul Touchton to DSVA Slack

### ISSUE THREAD

**Issue by anerbovig** [department-of-veterans-affairs/va.gov-team#32648]
Good morning! We have a new front-end engineer, Paul Touchton, joining the VA Online Scheduling team this week. He will be working with Brad Gross to get onboarded to the engineering team.

Please add paul.touchton@b3groupinc.com as a full member. Thank you!

**Comment by anerbovig** [comment]
Hi there, just checking in on this one! Paul's been added to the VA.gov Github organization, let me know if there's anything else that's needed here to have him as a full member on Slack. Thanks!

**Comment by LizCallaghan** [comment]
sorry about that, done!

**Comment by anerbovig** [comment]
Thank you, Liz!
