### ISSUE TITLE
Staging Review [Public Websites Team - New VA.gov Mobile Header]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32646]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [X] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [X]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [X]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [x] Respond to Platform feedback tickets.
- [x] Update ticket with the product’s launch date after it has gone live.
- [x] Close ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information: http://staging.va.gov 

- [x] [Product outline- New Mobile Header](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md) 
 
  

- [x] [Release Plan - New Mobile Header](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Release%20Plan%20Mobile%20Header.md)

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=2941)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/2552)
- [x] [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/280)
- [x] [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/281)
- [x] [QA Test Plan ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32821)
 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

-  Menu button should indicate if it is collapsed or expanded (using aria-expanded)
-  Buttons should respond to the space key to collapse/expand
-  Focus should be managed within the menu (e.g. activating "Health Care" should send focus to < Back to menu and vice versa)
- The menu button and its expanded children should all be nested under a nav element (more on placement in this article by Heydon Pickering)

### Required
- Product Manager: [Brian Lloyd]
- OCTO-DE Product lead: [David Conlon]
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- [Kelson Adams]

### VFS Attendees

- Content and IA: 
- Accessibility: 
- QA specialists: 

## Scheduling

**[Thursday, Nov 18, 2021]** **[2PM]**

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@brianalloyd staging review has been scheduled for 11/18 at 2:00pm ET

**Comment by tlei123** [comment]
@pjhill @ddzz , QA test-runs now completed, and QA-artifact links updated/added in main description above.

cc @brianalloyd @shiragoodman

**Comment by peggygannon** [comment]
Hi, @brianalloyd are these test user logins we need in order to see this new mobile header?

**Comment by brianalloyd** [comment]
@peggygannon no you should be able to view via http://staging.va.gov.

**Comment by pjhill** [comment]
Thanks for attaching all those QA artifacts, and having everything in place ahead of this review! Given that the only defect discovered during QA has been [resolved](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32821), I have no feedback for you all.  Thanks!

**Comment by shiragoodman** [comment]
No feedback from IA, content, design or accessibility. Great work, team!
