### ISSUE TITLE
Vanity URL Request - Hazardous exposure PSA - JAN 3, 2022

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#32655]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [x] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live:  **JANUARY 3, 2022**

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
www.va.gov/military-exposures | https://www.va.gov/disability/eligibility/hazardous-materials-exposure/

VBA request via email

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by brianalloyd** [comment]
Thanks @mnorthuis I'll place in our backlog and plan to action in Sprint 63 in support of the January 3rd timeline.

**Comment by mnorthuis** [comment]
FYI, there was an update to the requested vanity URL.  Top request info reflects the update.

**Comment by brianalloyd** [comment]
@mnorthuis slotting this for this sprint and just wanted to validate we are cleared to implement?

**Comment by mnorthuis** [comment]
Yep, this is good to go!

**Comment by kelsonic** [comment]
PR merged, redirect deployed, moving to validate 🎉 https://github.com/department-of-veterans-affairs/devops/pull/10505
