### ISSUE TITLE
Design intent [DGIB - Chatbot (for education benefits)]

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#32658]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [X]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [X] Schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [ ] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No

## Artifacts

Provide links or documents for the following: 

- [ ] Product outline
 
 
 
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [ ] User flow
- [ ] Any other artifacts you have so far

### Required
- Product Manager: Shamik Desai
- OCTO-DE Product lead: Matt Self
- OCTO-DE Design lead: Ryan Thurlwell

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
This is scheduled for 11/19 at 2 pm ET

**Comment by shiragoodman** [comment]
hi @rlyons89 and team. Apologies, but we need to cancel this meeting. OCTO has informed us that the VA needs to align on strategic guidance for your team, given the desire to have a global VA.gov chatbot, opposed to silo'd chatbot experiences across the site. If you have any questions about this decision, please contact Platform lead @rroueche.
