### ISSUE TITLE
Disable log out timer in Dev

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32662]
A request from another engineer is to provide a flipper mechanism which allows an engineer to have the logout timer turned off (currently set to 30 minutes).

We dont want to allow this type of thing to be the norm as we want all code across all environments to be the same.
Thread here for context: https://dsva.slack.com/archives/CSFV4QTKN/p1636483959137900

**Comment by asg5704** [comment]
Closing in support of Mocked Authentication.  We can talk about longer token times at that time.
