### ISSUE TITLE
Create a (mininal) wireframe for the frontend

### ISSUE THREAD

**Issue by CosmicSyntax** [department-of-veterans-affairs/va.gov-team#32666]
We will need a very minimal wireframe to aid the frontend develoment.

AC: A wireframe that lays out the basic structure for:

1. Section for developers already integrated into the platform
      a. use githubstatus.com as aid
      b. status of the (5) api endpoints
      c. drill down of each endpoint with more details if the data is imcomplete
2. Section for new developers in the process of integrating into the platform
      a. A search mechanism where keywords will yield a list of endpoints

**Comment by CosmicSyntax** [comment]
Here is the first wireframe: https://wireframe.cc/xtBCjx
<img width="1029" alt="Screen Shot 2021-11-10 at 2 06 25 PM" src="https://user-images.githubusercontent.com/14236737/141177192-cacffad1-da94-49da-8e44-db2fbda06c28.png">

This is more of a placeholder for now: https://wireframe.cc/cm7E5w
<img width="1027" alt="Screen Shot 2021-11-10 at 2 13 02 PM" src="https://user-images.githubusercontent.com/14236737/141178073-94482cfb-1c9d-48f8-9a6b-7f22cd688f67.png">

**Comment by CosmicSyntax** [comment]
@Rleahy22

**Comment by wyattwalter** [comment]
Do we want a time element to this as well where it can show status over the past, say, 24 hours?

**Comment by CosmicSyntax** [comment]
Yes! This would mean we need some database (perhaps postgres or redis). We can talk about creating a ticket and working on it this sprint. If not, the next...?

**Comment by kkomes** [comment]
Here are the screens that I discussed with Dan earlier.
<img width="1011" alt="Screen Shot 2021-11-11 at 12 03 19 PM" src="https://user-images.githubusercontent.com/92583333/141362377-69df15d8-c975-46eb-a09a-a1dc4231aa36.png">
<img width="1011" alt="Screen Shot 2021-11-11 at 12 02 35 PM" src="https://user-images.githubusercontent.com/92583333/141362423-6a8c820c-f711-4973-a8e0-94985d5c5d13.png">

**Comment by Rleahy22** [comment]
Nice, should I run with @kkomes's mocks?

**Comment by CosmicSyntax** [comment]
Yes! Komes's mock is muchhhh better.

**Comment by CosmicSyntax** [comment]
Except for "check status," it just has the status shown as seen in the second picture.
