### ISSUE TITLE
Create Makefile

### ISSUE THREAD

**Issue by CosmicSyntax** [department-of-veterans-affairs/va.gov-team#32667]
Create a Makefile to easily build and launch the application.

Should include:

1. Make test
     a. Builds all dependencies and will run tests: linter, unit-test, etc
2. Make pitstop
     b. Build both the frontend and backend and runs the application

**Comment by considerable** [comment]
Work in progress:
https://github.com/department-of-veterans-affairs/vsp-integration-experience/blob/igor/Makefile-va.gov-team%2332667/Makefile

**Comment by considerable** [comment]
Merged to main.

**Comment by ewilson-adhoc** [comment]
This looks like it was merged. Closing. Please reopen if there is more work to be done here.
