### ISSUE TITLE
[Reverse Proxy / EKS] Set up load balancer listener for testing network configuration 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32663]
## Description
Set up a load balancer listener that routes requests to Traefik so that we can test connections to the reverse proxy in EKS. 

## Technical notes
The listener should contain a rule that uses a header, a path, or another mechanism to route requests. 

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jsgarmon** [comment]
A listener rule now exists on the revproxy-dev ALB to forward any traffic with header "revproxy-eks: true" to the dev EKS cluster.

This is verified to work using curl: `curl -LH "revproxy-eks: true" dev-api.va.gov` produces a 404 from Traefik (on EKS), while `curl -L dev-api.va.gov` returns the standard API greeting.
