### ISSUE TITLE
Add mhv unified sign-in monitoring to datadog synthentic tests

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32675]
# Description
This ticket covers synthetic testing for logging/monitoring for the MHV Unified Sign-In Page

# User Story
**As a** Identity engineer
**I want** to automate testing for logging/monitoring of the Unified sign-in page
**So that** I am aware of any issues before release

# Acceptance Criteria
- [ ] Synthetic testing for MHV USIP is implemented
- [ ] We need this monitor for dev, staging, and production
- [ ] complete for mhv, idme, and dslogon for each environment: https://docs.google.com/spreadsheets/d/1EjCo4chnkItE1za_vfK-rk1yNxsLfJ0ipkI-jsf_Vow/edit#gid=0

https://www.myhealth.va.gov/mhv-portal-web/user-login?redirect=/mhv-portal-web/home

**Comment by nsoutouras** [comment]
@joeniquette Whenever you get a sec just let me know if the ticket details are accurate.  Thanks!

**Comment by nsoutouras** [comment]
Planning 1/31/22: @sylvesterlee1911 needs to schedule time with @joeniquette due to lacking proper credentials

**Comment by nsoutouras** [comment]
If anyone picks this up, the Datadog Chrome plugin is approved on CAG devices.

**Comment by joeniquette** [comment]
This ticket has been split into smaller tickets
Prod: https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/38665
Staging: https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/38664
Dev: https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/38630

Closing this ticket.
