### ISSUE TITLE
Changing H3s to H2s in featured content blocks from Sitewide Content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32673]
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [ ] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * < description > 
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ X ] **Other**
   * Please describe in detail
      For accessibility purposes, we need to change the header levels in the blue featured content blocks from H3s to H2s. Currently there is a Q&A component that automatically codes the header as an H3. Rather than taking text out of this and putting it into a rich text field manually across pages, we want to change the component so that the header is always an H2.

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* This is not urgent but something we are trying to fix over the next few sprints.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Sitewide Content
- DEPO product owner: Beth Potts
- Product manager: Randi Hecht
- Designer: N/A
- FE engineer: N/A
- Product/team Slack channel: va-sitewide-content

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by kelsonic** [comment]
Hey @RLHecht could you lmk what blue boxes you're referring to? What pages can I find them on?

**Comment by RLHecht** [comment]
@kelsonic The featured content blocks. We have them on a lot of our eligibility pages. 
Here's an example: https://www.va.gov/disability/eligibility/

**Comment by kelsonic** [comment]
@RLHecht perfect, thank you! So is the ask to have every QA template's header be an h2 instead of an h3? CC @joshkimux 

![image](https://user-images.githubusercontent.com/12773166/144265628-8b1932d1-fa09-44c5-a608-f1c6a921dde6.png)

**Comment by joshkimux** [comment]
@kelsonic It depends? If these are always going to be direct children of the `h1`, then yes, a `h2` would make sense. If these may sometimes be nested under a `h2` FAQ section, then they may need to be `h3`s. 

If we've considered the full breadth of use cases and these blue boxes will _always_ be direct children of the `h1` and not nested under other `h2`s, we can definitely grab the easy win here by setting them all to `h2`s 😄

**Comment by kelsonic** [comment]
Oh wow, so we'll need some javascript logic in there then to make it smart if we are to go through with this change 🤔

**Comment by joshkimux** [comment]
It depends on the context, I'm sure @RLHecht can chime in there!

**Comment by RLHecht** [comment]
On benefit detail pages, the only items in the template that can be added above the featured content block are alerts and the on this page TOC component. Both of those would be H2s but I think the featured content would also be an H2 since it wouldn't need to nest under it.

You can check this at prod.cms.va.gov/node/add/page

**Comment by joshkimux** [comment]
Great context! @kelsonic , looks like we can set these to `h2`s without worrying about javascript logic

**Comment by kelsonic** [comment]
Awesome! ✅

**Comment by kelsonic** [comment]
@tmac9494 we just need to change [`paragraphs/q_a.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/paragraphs/q_a.drupal.liquid) to only use an h2 then! 🙂 

![image](https://user-images.githubusercontent.com/12773166/144478163-494976a6-c63d-486c-a048-e553eedb8e40.png)

**Comment by kelsonic** [comment]
Sent up a PR for this: https://github.com/department-of-veterans-affairs/content-build/pull/809 should go out with daily today

**Comment by kelsonic** [comment]
Validated in production, closing
