### ISSUE TITLE
Adding Jeremy Curcio to DSVA Slack

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#32688]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add jcurcio@tistatech.com as a full member.  Please note that his Slack profile was previously deactivated due to his leaving Caseflow, however he was rehired and rejoined Caseflow so we need to add him back to Slack.  Also if you can please get this taken care of today 11/10 as we had a delay in getting his corporate email set up and he has effectively been on the project as of 11/1.  Thank you!

**Comment by LizCallaghan** [comment]
done!
