### ISSUE TITLE
PIV research

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#32689]
This is done when we have answers to the following questions:

1. What integrations need to happen to authenticate with a PIV card in the browser?
2. Where/How is PIV authentication done currently?
3. What can we leverage from existing PIV authentication solutions?
4. How feasible is it to incorporate PIV authN in:
   1. The prototype?
   2. The final solution? 

We also must diagram the flow and integrations of PIV authentication when the above questions are answered.

**Comment by ken-non** [comment]
PIV card may not be a good option because of how long it takes to get one. is it still viable if it takes 4 months for a developer to get access?

**Comment by ken-non** [comment]
"something like keycloak can use multiple identity backends, which would allow us to allow access via github first and transition someone to PIV once they have it?" @dginther

**Comment by patrickvinograd** [comment]
Braindump of thoughts:
- Technically there is a CIO mandate from a couple years ago saying all VA _internal_ systems are to be accessed using PIVs. So policy-wise this would be a strong place to be. But, access to SaaS products, GitHub, AWS, etc via PIV is not always feasible and for that reason (as well as the latency of issuing PIVs) the VA.gov ecosystem has not used PIVs for authentication.
- There's something to be said for using PIVs for elevated access like for direct access to production systems - it's a very high level of identity and authentication assurance. Perhaps with an explicitly temporary workaround for people who have trouble getting their PIV issued/renewed. I don't know how this would play with AWS SSM. There is an SSH keypair on a PIV so it would be possible to enforce PIV-based shell access in some form. 
- The most mainstream-at-VA way of enabling PIV authentication is through SSOi (for on-VA-network clients) or SSOe (for off-VA-network clients). But I would not recommend tying access to the platform to either of those systems if we can avoid it. 
- Okta can nominally do PIV/smartcard authentication. I set up one of the sandbox envs where it would prompt for PIV/PIN as a credential option. The validation of the PIV is local-to-Okta, by uploading the certificate chain that issued the PIV. This means that it will ensure that a valid PIV is being presented, and that the PIV hasn't expired. But it has no way of enforcing PIV revocation - i.e. if somebody was booted out of VA but held on to their PIV, Okta would have no way of knowing. Whereas I believe you do get that capability from SSOe/SSOi. 
- Damien from the IAM team mentioned there was a non-VA smartcard validation service built by another government agency. This was a couple years ago so the details are escaping me, but it was proposed as a possible way of implementing PIV auth for a new authentication service. I will refresh my memory/ask around if that is still an existing thing.

**Comment by patrickvinograd** [comment]
This is definitely a case where I hope we can dial up/down the convenience vs. assurance tradeoff - like a key question is "how many times a day does a developer need to present their PIV". If it becomes burdensome then can we dial it down to only being required for sensitive actions/access, or extend the PIV-based session duration to make it less of a burden.

**Comment by patrickvinograd** [comment]
Info about external PIV validation:

> It's a service hosted by department of treasury who run a shared service provider (SSP) PKI (which VA now uses). I don't see any information on their site about it but I know I have some information saved. I can look for it tomorrow when I'm at my desk.
> 
> http://pki.treas.gov/index.htm

**Comment by ken-non** [comment]
duplicate
