### ISSUE TITLE
Track appointment request date preferences

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#32684]
## Description
As Product/Design, we would like to track appointment request date preferences users submit so we can better understand their expectations on when they want an appointment.

Goal: Make the date preference selection clearer 

![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/005cabf0-77b1-4164-9de8-b8a39ad7069f)

**Example**
Current date is January 4, 2021
Calendar preferences are Jan 14 AM, Jan 14 PM, Jan 13 AM
Days between values are 10, 10, 9

---

## Acceptance Criteria

Given VA request flow
When user has 1 or more preferences
Then track days difference between current date and preference date(s)
And include null selections (i.e. always send 3 values)

Given CC request flow
When user has 1 or more preferences
Then track days difference between current date and preference date(s)
And include null selections

### Technical Notes
- Per VSP Analytics, this would be done with a custom dimension associated to an event
https://dsva.slack.com/archives/CBU0KDSB1/p1636570295081000
- Likely associate with the submission events

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Event names and parameters are documented in this ticket

**Comment by laurenernest** [comment]
@jenniemc What's the event name and parameter? The VSP Analytics team will need that to implement on their end.

**Comment by jenniemc** [comment]
@laurenernest, this is the first time i'm working GA using custom dimension so i'm taking a stab at the event name and parameter forVA request. The event name is `vaos-request-submission-successful`, the parameter is `vaos-number-of-days-from-preference`  Below is an example of what you can expect.

      event: 'vaos-request-submission-successful',
      flow: 'va-request',
      'health-TypeOfCare': 'Primary care',
      'health-ReasonForAppointment': 'routine-follow-up',
      'vaos-preferred-combination': 'afternoon-evening-morning',
      'vaos-number-of-days-from-preference': '1-1-null',

CC Request event name is `vaos-community-care-submission-successful` and parameter is `vaos-number-of-days-from-preference`


      event: 'vaos-community-care-submission-successful',
      flow: 'cc-request',
      'health-TypeOfCare': 'Primary care',
      'health-ReasonForAppointment': undefined,
      'vaos-community-care-preferred-language': 'english',
      'vaos-number-of-preferred-providers': 1,
      'vaos-number-of-days-from-preference': '1-1-null',
      'vaos-preferred-combination': 'afternoon-evening-morning',

**Comment by laurenernest** [comment]
Thanks! I'll leave this in validate until we can confirm everything is passing correctly.

**Comment by laurenernest** [comment]
The way I'm getting this back in GA isn't what I was expecting so I've asked the analytics team if we need to update our code or if they can do it in GTM.

**Comment by laurenernest** [comment]
Too great of LOE to update when we have manual workarounds at the moment. closing ticket.
