### ISSUE TITLE
[Discovery] Migrate VA.gov megamenu items to Drupal 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32681]
## Issue Description
_Identified a situation where title case capitalization is being used on Va.gov homepage megamenu. Sitewide content team determined that sentence case is our style across the board. This update needs to happen on the frontend as this is not in Drupal. Desired state would be to have all megamenu items in Drupal._

## Ideas for Exploration 
- Let's explore sub domain megamenu items to come from Drupal instead of hard coded.  What would this take, and what are the associated risks? What is the possible quick path for implementation. 

## Screenshot 
![Screen Shot 2021-11-09 at 2 53 39 PM](https://user-images.githubusercontent.com/70410912/141011598-1af46c6a-b38f-4904-ba93-c86531c5277c.png)

## Front end tasks
- Migrate all megamenu items to Drupal for future content editing 
- Identify technical solution 
- Identify and note risks 
- Determine viable path forward with this level of migration

## Acceptance Criteria
- [x] Discovery ticket is updated with dev feedback to include recommended technical solution, risks and implementation path forward.
- [x] Close ticket when work is completed

**Comment by brianalloyd** [comment]
We could use this ticket to explore sub domain megamenu items to come from drupal instead of hard coded.  Reshaping ticket to support.

**Comment by kelsonic** [comment]
Moving to backlog

**Comment by brianalloyd** [comment]
Closing ticket and moving related issue to backlog.
