### ISSUE TITLE
Access for kkomes

### ISSUE THREAD

**Issue by kkomes** [department-of-veterans-affairs/va.gov-team#32685]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Komes Komes

### Your Email

komes.komes@adhocteam.us

### Name of Your Team

VA Platform Spike Team

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDERmJ0GMDZDgJo0Wbs/mthiYrKZ2BwtBpofL8zoFfR8/KYNfGjBIN1lSyABexdf8etXYsC39aBedrUyTMEHheqo6kBGEu+1HwNfY1f/rjQRPsxLniCR2PqLtFgInAws0cuSLV3VY1IPkhq+c0NOAqRCBnQJUBLO/m6MDLlcWb1QuNKdWLW2iaaYg8hswXHH5vr+sKv61YD68FUT2t5UbqjC6SzHVTeOPHuZaiCwWbUF7/kfhKDL1Gui5g/pcCOwodZ9SzezbbjUnFaroib+GJCb+dYW1A0Ydht4y16xbftXMteYWGcD9IJwarKLo7iV195dpblAsb4l28NaDRH+7erKLmLzTFubopoPQyFOVPNUXsBQyCPfW4v9RAjZA5Jyb9FjbzHrqfCCUP1h8yBppZO8ZnciFbaiU7s67vxMrGdbLvZLkSFbmosA/k4Qjlkv0I5C8FWEfFWFmM3tYd12c5AnS0wgQS22KE73Ck+YQgGkGdfD9BPzR0Stu4witT/1BE= komeskomes@Komes-Komes-MacBook-Pro.local

**Comment by mleclerc00** [comment]
Hi @kkomes 

your ssh key has been deployed and you should be able to access the socks prox with the following [tutorial](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Internal+tools+access+via+SOCKS+proxy) .  Just wanted to confirm that you have been able to set this up successfully before closing the ticket.

Thanks!
