### ISSUE TITLE
Provider selection information missing for CC request 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#32687]
## What happened?
Provider information is missing from the "Review your appointment details" page and request card happening only with grethel.g.petryniec@id.me test user.

## Steps to Reproduce

1. Login to VAOS as a test user (grethel.g.petryniec@id.me)
2. Follow the steps to create a request for CC supported type of care (Eg:- Optometry, Food and Nutrition, Primary Care etc.)
3. Choose a provider from the list and click on continue 
4. Fill in the required fields to enter a CC request 

Expected Results: Previously selected provider information should display on the "Review your appointment detail" page and Request card details 

Actual Results: Both "Review your appointment detail" page and Request card details display as "No provider selected"
![Provider_selection_error](https://user-images.githubusercontent.com/69315717/141036502-9081bd38-36af-444a-8673-db10aecba82f.PNG)
![Provider_selection_error1](https://user-images.githubusercontent.com/69315717/141036664-342298a5-e2ae-4849-9f2e-fe581fe7d872.PNG)

**Comment by ldelacosta** [comment]
@marcynadeau - please test and let us know if you have any issues. Thanks!

**Comment by aarathi-poldass** [comment]
Re-tested the ticket and the issue still exists. After selecting a provider form the list the provider information is missing once the request is created. Please find the screenshot attached 
![Error_Retested](https://user-images.githubusercontent.com/69315717/144311515-4a3d0b31-aae5-43ec-95f0-970f7c1bf939.png)
:

**Comment by ldelacosta** [comment]
Aarathi - I have reopened this ticket for you. Thanks.

**Comment by laurenernest** [comment]
Moving back to Ready per SQA validation findings

**Comment by ldelacosta** [comment]
@marcynadeau - This is ready for testing. Please let us know if there are any issues. Thanks.

**Comment by aarathi-poldass** [comment]
Re-tested the defect and the issues has been resolved. Closing the ticket.
![Uploading image.png…]()
