### ISSUE TITLE
Access for Preston Davies

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#32697]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Preston Davies

### Your Email

preston.davies@adhocteam.us

### Name of Your Team

VSP Design System Team

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqiaZL1Ck7yGglzxECfQS2pDXZG3XpxFBpw2xdT1ORZxfFebkssbeNBsdrAl0PM+0xs3W36+9qAQs8guHatNKmn+gorZ5orGaXjBecC+UW7mKHufJbEXdh6z5ILmNHX3q+2/jGjs/OOe3qKn7JwwA9uup+OX2v+c6YOKEea5iKbkUWFCzZOLPS+He2AdCAoArPP+YOHC94Has1GNua++PTYgMs1wW+12b8K6f2XOgar4+zJt7Y19pbpGNMU+WM8+KOwBFCk8nvGkyOFCYAFtCFxXsTktHgbmGvRcgk1GtQYJwwu0usRZvNW9nmKDSy4OWxdcWdLfaQEu7q9QNzaK5qyoZzbCCu12jpQxi1PTB5++Z5gtMV4hWsVpEnRHgv4ZXRdJ3cgS3xDvhi3H3UypgTqGuxa0gwCdOFgbiMkGl881qxpTgnziDQ1XdfAIlzlTQZbwQYgFSaekZuEZllf14QR4cJeaGeP+YHatJpbG9kDWeim/fUvj2PkNCTV1HPGPs= prestondavies@Preston-Davies-MacBook-Pro.local

### Desired AWS Services

None

**Comment by mleclerc00** [comment]
Hi @pdavies88 

I apologize for the delay on this request but You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

Assuming all goes well please let me know so I can close this ticket.  Thanks!

**Comment by pdavies88** [comment]
@mleclerc00 thanks I was able to access
