### ISSUE TITLE
Keycloak discovery

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#32714]
Keycloak looks like a good option as an identity broker, we need to do further discovery.

Task is done when:
we have answered the following questions and added the answers to a doc in our confluence space.

- How would we use it?
- How it could work with PIV cards?
- What are its limitations?
- What would a prototype look like?
- Can it use github/adfs or limited to oidc/saml?
- How easy is it to set up?
   - configuration
   - any custom work?
   - what does deployment look like?
- What does future maintenance look like?

**Comment by kjduensing** [comment]
https://www.keycloak.org/

**Comment by kjduensing** [comment]
From Harshil: https://stackoverflow.com/questions/63308925/aws-cognito-in-place-of-keycloak

**Comment by kjduensing** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/edit-v2/1974173750?draftShareId=f031464a-b0db-438b-8037-f1b927ba10c4
