### ISSUE TITLE
Access for James Daniel Bell

### ISSUE THREAD

**Issue by JamesDanielBell-VA** [department-of-veterans-affairs/va.gov-team#32712]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

James Bell

### Your Email

james.bell@libertyits.com

### Name of Your Team

axolotl

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClZm6mk+Lso5UuvXdirr9ko5tSGZOPSj9yTGm/vMNkSgTv42t+CEks9dcDJ6YzlYEWd95uqvE9eiB3kC5fw4/mJjp3MKCEg7jOG5xISKLFRIHou+BcpC3PLjdLDM+3qyxg1D+/c6idrV6uB2vl474q0hD0WlPDSXQD6lQouH7/GpcH/LMVTkLtN+qp6kFniSC7HOg5gn+BS+B2cz7KZwaHJv7rSxHCvUjO27v19Z7NjyuBim6cWIxmMGSgjDEc9IkYDDQ3vjRqEAPgHYwL731VzZt1qrD5MEp6otVrm8jbe2uSit9vqo2f61F+XMjD8SNED/7LQp7NNLKIyVLJjXvke2RSfCIuonlphBlduTwm+++ZejRP3ibYGDpg3k/os77pRFv7NVdf32UagrOV591RFXy5XcSsuddDc2o+pZwhcEnDQGUHfsM94GmWAojDP21CTPX800W8oWG0jnWO5WeKld10Js4z2tl7Hwhufrx7iNm5zh65ldNS84mWYNLVm2U= jd_va@WIN-KB5OBIAHLQJ

### Desired AWS Services

I need access to Kibana for CCE API metrics

**Comment by JamesDanielBell-VA** [comment]
Updated with incorrect SSH key. This version is the one I use.

**Comment by JamesDanielBell-VA** [comment]
Missing a step involving installing linux on my machine. Will update ticket when I have the correct SSH key.

**Comment by JamesDanielBell-VA** [comment]
Updated with correct ssh key.

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: James Bell
COR: Cecila Lee
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @JamesDanielBell-VA 

I apologize for the delay on this request but You should be able to access socks now with the following socks tutorial

If you have any issues feel free to drop a message in #vsp-platform-support

**Comment by mchelen-gov** [comment]
@mleclerc00 EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by mleclerc00** [comment]
Hi @JamesDanielBell-VA 

Are you able to access Kibana with socks alone or is there more action that needs to be taken with aws?

**Comment by mleclerc00** [comment]
closing this ticket, please re-open if needed
