### ISSUE TITLE
MAINTENANCE: Draft guidance around zoom links in PW

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32725]
- [x] Find prior art, if any, around linking to Zoom meetings in publicly findable websites
- [ ] Have a few possible recommendations (ie course of action)
- stretch - Finalize a rec so that we can develop guidance

**Comment by lianilychee** [comment]
11/11 Thurs:
- by SU tomorrow, share findings/resources (any examples that did this well)

**Comment by lianilychee** [comment]
11/12 Fri:
- Yesterday: Didn't find any resources; think we'll have to pick a strategy
- Today: https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1974567071/Zoom+link+strategy
- Options (can incorporate linter)
  **- List Zoom links anywhere in PW or Operational docs content**
  -   Considerations: 
    - Make sure that meeting settings are secure and links don't expose the PW
    - Phrasing is consistent
  **- Centralized space that's _not_ in PW, ex: Community of practices in operational docs**
  **- Centralized space in PW**
    - Considerations:
      - Will have to develop guidance around consistency

**Comment by lianilychee** [comment]
11/18 Thurs:
- Today:
  - after RR sync, will fill in pro/con list as much as I can; if got questions, will ask G

**Comment by lianilychee** [comment]
11/19 Fri:
- Did find other examples that are more suited for Operational docs
- Have 2 solutions options in the [pro/con list](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1974567071/Zoom+link+strategy)
- 11/29: Gretchen will look at the Conf page; in the meantime Amy will focus on linter

**Comment by lianilychee** [comment]
12/6 Mon:
- Gretchen to review whenever she has time
- would be cool if we could flag zoom links in linter

**Comment by lianilychee** [comment]
12/7:
- Gretchen: I'll put it on the list for today!

**Comment by lianilychee** [comment]
12/8 Weds:
- let's hold to next year!

**Comment by andreahewitt-odd** [comment]
This has not popped up recently as a problem so I think we should close this
