### ISSUE TITLE
MAINTENANCE: Dynamic footer and wordlist compliance

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32723]
# User story
As a Content team member, I need to modify existing PW pages so that they deliver a consistent user experience.

# Tasks

- [ ] Go thru the Collab Cycle tab and follow the instructions (both in the xls)
- [ ] Inform Andrea that it's done

# Reference info
- [Footer audit xls](https://docs.google.com/spreadsheets/d/11hmaDJgzXCodsmFH8O2LnQHfxGCOc5IZahDGH8j97qE/edit#gid=0)

**Comment by andreahewitt-odd** [comment]
Footer exists on every page
