### ISSUE TITLE
Create release notes template with categories for component-library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#32736]
Create release notes template with categories

**Comment by bkjohnson** [comment]
Here is the [documentation for the template](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#creating-a-template-for-automatically-generated-release-notes). In order for it to be effective we will need to use labels for our PRs. Perhaps we can base the labels on types/categories from these two methodologies:

- https://keepachangelog.com/en/1.0.0/
- https://www.conventionalcommits.org/en/v1.0.0/
