### ISSUE TITLE
Create Legacy Page Status Tracker

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#3273]
Problem: We are all losing track of legacy page statuses and are in and need a tracker so that everyone has insight. 

Solution: Review content tickets on our ZenHub board and determine status, last comments, next steps, who's responsible, timeframe. Create an excel document that includes this information.

**Comment by lunascoop** [comment]
Here is the Google sheets version: https://docs.google.com/spreadsheets/d/1-fEDCKfrBwz-g4_VhB-lyo2HtbG5RGCHK0uL4iCMeqk/edit#gid=39961378

Here is the excel spreadsheet version:
[Legacy Page Status Tracker.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3866707/Legacy.Page.Status.Tracker.xlsx)

**Comment by Karak888** [comment]
this should encompass all redirect URLS she has captured in her tickets.  This spreadsheet is an attempt to consolidated document.  This will be used as the master redirect.  Legacy page tracker is just for remaining legacy page 

@jenniferlee-dsva

**Comment by Karak888** [comment]
@lunascoop looks good.  Can you please add this to our GH repo as well?  Going to close this so you can focus on the redirect spreadsheet for Benefit Hub URLs for redirect, thanks!!

**Comment by jenniferlee-dsva** [comment]
Hey - Since we've now solidified with Platform team that Mikki will be the designated keeper of redirects log, let's not duplicate (and create another 'source' of truth). @lunascoop - can you please simply refer to/use Mikki's source spreadsheet - to track your own comms work? 

@mnorthuis @meganhkelley  ^ we on same page?
