### ISSUE TITLE
Add Pre-Checkin for appointment reminders

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#32748]
The Checkin project needs to be able to send a link as part of the confirmation message for appointment reminders.  To achieve this , VEText will need to implement additional functionality to support this. 

**This work needs to be completed before 11/30

- [ ] Add a checkbox to clinic configuration that indicates the clinic / stopcode is included in pre-checkin. 

- [ ] Add a new Message replacement variable %PRE_CHECK_IN_URL%

- [ ] When check box is checked and url exists, post to the new lorota endpoint with the data necessary and get back lorota uuid. 

- [ ] Shorten UUID and include in appropriate reminder of the replacement variable.

**Comment by lindsay-insco** [comment]
https://github.com/department-of-veterans-affairs/chip/blob/master/src/initiateCheckin/index.js

https://github.com/department-of-veterans-affairs/chip/blob/fd275d906060c63e4f6f939b018d234e41129a58/src/initiateCheckin/index.js#L54

**Comment by shanemelliott** [comment]
https://github.com/department-of-veterans-affairs/lorota

**Comment by shanemelliott** [comment]
New URL https://dsva.slack.com/archives/C022AC2STBM/p1636582260385600?thread_ts=1636472991.331100&cid=C022AC2STBM

**Comment by shanemelliott** [comment]
The caveat is that for grouped appointments that are kept or canceled together, they should get one link for the group. (Which is why appointmentIENs is an array)

**Comment by lindsay-insco** [comment]
Waiting to resume E2E w/CHIP

**Comment by lindsay-insco** [comment]
Awaiting IOC test

**Comment by lindsay-insco** [comment]
- Deploying first produce run
