### ISSUE TITLE
Access for Carl Alquisola

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#32741]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Carl Alquisola

### Your Email

carlanthony.alquisola@va.gov

### Name of Your Team

Platform Spike Teams - Access Management

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLs4Drk/V/aPlfgK2uTT7vLv8o9U3nyHeTG4uJUSOP55Xzbfi32ObGTY0DHg6DhJ/HucIu1UGd//Py6LW5rmj6kCp8xIXGLLgnSFWhgHxU8sLPObp8sl0bwkxJtGEAu1BXAp3PM2+yNx0N2DqDwY7FMSJs8HMFfzjYxsmIN7gBwSBmJTAJh/ZbDonSKEXeo8Oae65MSMai+We6jKRxXaGgcajD6jQ3CJfaiW+yPQBHw0/c45/v3zwbvbqNGsQmIuImFKthgle6U61ejZJXW2lqGW2cGtWqvGYe1g/vD4ySjlzmIv7K8s3S0Z1ca8+gqc7KL4Fi65wQk3XR/QfzsXS2IyFkGBhUn2CZD3piQm66MgRbf/bCoh+PQ19l1t97li8NOE3AV/GobkFcJigdGoT+S5xE2YGZJIwmrs7iaaci93wDlbyqLvBMq941C9nLa571H2L7VOXt1Fq+Z8l95vk3gyPdBwX76zec8kL/lf1kiUl/bD+ANJeTdJLROBVo0y8= carlalquisola@Carl-Alquisola-Macbook

### Desired AWS Services

platform-amt role

**Comment by calquisola** [comment]
My onboarding representative has been Sabrina Ammon: Sabrina.Ammon@libertyits.com | Sabrina.Ammon@va.gov.

Thanks!

**Comment by mleclerc00** [comment]
Hi @calquisola 

can you confirm that the socks access you needed was provided in order to close this ticket? 

Thanks!

**Comment by calquisola** [comment]
Hi,

My socks access works now. thanks. 

Best,
Carl

**Comment by jhouse-solvd** [comment]
Re-opening for AWS access. Need to determine what services and permissions are being requested.

**Comment by jbritt1** [comment]
#### For AWS Access:

User: Carl Alquisola
Vendor: Sabrina Ammon: Sabrina.Ammon@libertyits.com | Sabrina.Ammon@va.gov
Approval required: @mchelen-gov

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Carl Alquisola
COR: Cecila Lee
Approval needed: @mchelen-gov

**Comment by jbritt1** [comment]
Will need `platform-amt` group membership once approved.

**Comment by mchelen-gov** [comment]
@jbritt1 EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by jbritt1** [comment]
First time login credentials for AWS provided to user at this time.
