### ISSUE TITLE
Contact Center Review for VA Mobile App - Vaccine Records

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#32766]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
New functionality in the VA mobile app that displays VA vaccine records so users can access their VA immunization history in list and details views. 

### Launch Date
New feature will be released on 11/23/21

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
*Please provide product guide link*
[VA Mobile App Product Guide- Call Center Support (11-21).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7527895/VA.Mobile.App.Product.Guide-.Call.Center.Support.11-21.docx)

### Product Video

*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @ashley-matthews. The new material looks good! I added a title page and revision history page to this version of the guide, so they'll be on there moving forward for any future revisions. I've also shared with VEO for their approval. Please let me know if you need anything else. Thanks!
[VA Mobile App Guide 3.0_11-21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7530937/VA.Mobile.App.Guide.3.0_11-21.docx)

**Comment by starlow00** [comment]
VEO had no comment. Closing.
