### ISSUE TITLE
Fix Storybook story height issues

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#32763]
## Description
In some of our stories—for example in the story for the [va-featured-content component](https://design.va.gov/storybook/?path=/docs/components-va-featured-content--default)—the height of the story container is not auto-expanding to the height of the component. We need to resolve this so that the stories for each component are shown at the proper height and users do not need to scroll.

![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/09f8d4e2-3b12-4ec0-bd3f-9994be5c6c98)

## Acceptance Criteria
- [ ] Stories for all components on the Storybook auto-adjust for the height of the component

## Notes
- This heights for each individual component should not be hardcoded.
- This is happening for web-components and React components
- Currently, when the page is first loaded, the height of the story is too short, but if you navigate to another component and then navigate back, the height is correct.

**Comment by pdavies88** [comment]
Issue is related to Firefox

**Comment by pdavies88** [comment]
Recommended fix inside of `/packages/storybook/.storybook/style.scss`
* Remove Negative Margin via Default Storybook CSS
* This is causing the show code button to overlap with components
* Height Auto fixes Firefox Bug with height being set to a fixed 70px value

`.docs-story {
    & > div {
        margin: 0;
        & > div {
            height: auto;
        }
    }
}`

![Screen Shot 2021-11-30 at 10.27.03 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/d336396b-a59d-4baa-93d3-b4de532bbee4)
![Screen Shot 2021-11-30 at 10.27.29 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/44957c71-d9bc-48ea-bd0e-b54d513a62e2)

**Comment by pdavies88** [comment]
PR: https://github.com/department-of-veterans-affairs/component-library/pull/231
