### ISSUE TITLE
[Design] How to Present Details/Confirmation for Already Checked-in Appointments from Appointment List 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32788]
## User Story
As a Veteran, I want to click on an already checked into appointment from the appointment list so that I can see details of the appointment and that it was confirmed. 

## Description
Look into potential designs for if a Veteran clicks on an already checked-in appointment from the appointment list. 
Potential option would be to load a screen with the same details as the confirmation screen to let the veteran know it was checked into. 

For future thought - add way-finding details. 

Slack thread with additional details [here](https://dsva.slack.com/archives/C02GXKL8WM6/p1636724938133800). 

## Acceptance Criteria
- [ ] Create mockups/wireframes 
- [ ] Review with appropriate team members (Product, engineering, etc.)

**Comment by julieadair1** [comment]
@jparker0425 how much of a priority is this?  Is it a frequent use case?  Edge case? Do we need to consider brining in to the next sprint?

**Comment by julieadair1** [comment]
@jparker0425 this is related to pre-check-in epic correct?

**Comment by kristenmcconnell** [comment]
@kristenmcconnell UX has some clarifying questions on this ticket before we can point.
