### ISSUE TITLE
Discovery: Consolidate CTA widgets

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#32789]
## Details

We have a lot of call-to-action widgets that largely use the same pattern. We should investigate if we can consolidate them somehow into a component that could be called with whatever specific information is needed.

This would probably be a good component to live in the Design System, we should coordinate with that team on this.

### Current CTA widgets:

- cta-widget (this is the current “global” widget, though not all CTA widgets use it)
- covid-vaccine-updates-cta (this may not be needed anymore, we should consult with the team that owns it)
- manage-va-debt
- view-modify-dependent/686-cta
- view-modify-dependents/view-dependents-cta
- view-payment-history
- vre-chapter31
- vre-chapter-36

### To Do

- Determine exactly what work needs to be done in order to consolidate these widgets
- Discuss work with the Design System team
- Make tickets for getting the work done
- Update the documentation for call-to-action widgets

If the widgets cannot be moved into the design system, but can be consolidated they should be moved into a platform-level component.

**Comment by rmessina1010** [comment]
[CTA Widget Evaluation Recommendation](https://vfs.atlassian.net/wiki/spaces/~96033397/pages/2078801963/CTA+Widget+Evaluation+Recommendation)

**Comment by timwright12** [comment]
Pinged in slack, but also updating here that design system has requested screenshots and links to CTA instances, so we'll need to update that doc

**Comment by rmessina1010** [comment]
Discovery complete. Closing.
