### ISSUE TITLE
[FE] Make "Go to another appointment"  Link Static on Confirmation Page 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32784]
## User Story
As a Veteran, I want to be able to return to my appointment list after checking in for an appointment so that I can view all other appointments for the day, even if I cannot check into them at the current time. 

## Description
Currently, the "Go to another appointment" link of the appointment confirmation page only shows when there are other available appointments the Veteran can check into at that time.  We need to make this link static so it always shows. This will allow the veteran to go back to the appointment list and still view what is scheduled for that day. 

![image.png](https://images.zenhubusercontent.com/60ae5b64364d5b0b5078b4d5/817c0173-cc55-49e6-a5fe-a6ede2005b3c)

## Acceptance Criteria
- [ ] "Go to another appointment" link of appointment confirmation page becomes static so it always appears.

**Comment by julieadair1** [comment]
@jparker0425 which epic should this story be attached to?

**Comment by sarahknoppA6** [comment]
@niradatta1 and @zach-park to review on thurs/fri

**Comment by zach-park** [comment]
Upon checking in to a single appnt, if 'go to another appnt' is clicked, the user still has the ability to check-in. @niradatta1 @brianseek

**Comment by sarahknoppA6** [comment]
We need to create a new FE ticket to look into the above issue. Please reference ticket number here before closing this one.

**Comment by loripusey** [comment]
@brianseek This ticket was brought up during planning as needing a follow-on ticket; can you help me understand what the follow-on work is?
cc: @sarahknoppA6

**Comment by brianseek** [comment]
@loripusey sorry I missed this message a few weeks back. I don't remember the issue exactly, but something was buggy about the link. Did a ticket ever get made?
