### ISSUE TITLE
Access for Aubrey Arcangel

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#32786]
### COR Name

Jeffrey Hayter

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Aubrey Arcangel

### Your Email

aubrey@thesocompany.com

### Name of Your Team

VSP Contact Center

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqLphhbLR1fYxJPCN11Yh+7/NRzdGcKZYlBRm0MqRY4q//52++mnCyKb3qEvfi8qeppm2a3bDaInb8rQ/3lWFU1YHPqt35clN5DyRJz5VdIYl3EV/wH8mIAMQDKKyeLIZxgoxID6fV+hXcIOfl+EGmUVmyHYIoCprJsska9mq08PKpb5+fOIIEMzZgn/GsWQkyUNgVd0it1ckbVSCBtxwmTClUvrDyOfpRpHxveGFdZl2f4vpyBGb2TcVL2jLN+IEDHBeaR+vwstvvZDYZ5b3MSDgL3Vh3wAvpgEGjPfSPWxd7SXFfNEBOe93PxWKZCONRFTHiFluJDYmLBJvThJAtkTUS5+VrNlsHlgUVtYbWB1FTDKSKl3sRU0A/kojksuurKNyWMqlrVh2vAIBwdZJhjxJ8m9fR90mL3pLFjMgEeBN7sNK4Xtac9zBP89M6Qac/5i4RoEybWHN9d5geEMZS32YWN4FhScZckVDvYd4q26jkwRihzLUUVis23br5ySU= aaworkmacpro@MacBook-Pro

**Comment by rwilliams-oddball** [comment]
Added.

**Comment by jhouse-solvd** [comment]
@aubreyarcangel - Your SOCKS access is set up and should be working. 

Let us know if you have any other questions!
