### ISSUE TITLE
[FE] Display Confirmation Page to User Who Visits Pre-Check-In Link after Completing Pre-Check-In

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32782]
## User Story
As a Veteran, if I have forgotten that I already completed pre-check-in and attempt to do it again, I want to know that I already completed the process so that I don't have try to do it again and waste my time.                     

## Wireframes
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/PGkmnvx   

## Acceptance Criteria
- When I
     - Click a pre-check-in link after I have already completed pre-check-in for the appointment
- Then I
    - See the confirmation page that tells me I have completed pre-check-in for my appointment and shows me my appointment information

## Tasks
- [ ]

**Comment by julieadair1** [comment]
Blocked on:
1. Are we getting the data? - CHIP
2. What does the page need to look like? - UX

**Comment by julieadair1** [comment]
@kristenmcconnell - Do we need a ticket to mock up this page?  @acrollet do we need a chip ticket to see if we are getting the data?
cc: @jparker0425

**Comment by kristenmcconnell** [comment]
@julieadair1 I actually think that was the intent of this [ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34960). It was really about all error messages when the Veteran will receive a URL, but should really continue on in the check-in experience. We probably need to update the UX ticket to more explicitly cover all the use cases.

**Comment by acrollet** [comment]
@julieadair1 I think it may be a back-end ticket rather than chip...

LoROTA [returns a 404 if the id does not exist](https://github.com/department-of-veterans-affairs/lorota/blob/25a6e654ca093d9d0c638e6044efecfb3e32a64e/src/lambdas/project-LoROTA-get/index.js#L48) or [403 when the id has expired](https://github.com/department-of-veterans-affairs/lorota/blob/25a6e654ca093d9d0c638e6044efecfb3e32a64e/src/lambdas/project-LoROTA-get/index.js#L56) along with a message 'data has expired'.

 @dillo @randomsync @kanchanasuriya do we or can we pass these statuses back to the front end so that a specific page could be shown?

**Comment by randomsync** [comment]
Currently, vets-api doesn't return a specific error code in those scenarios. It returns a generic HTTP 400 Bad Request if any downstream call returns anything other than 200:
```
{
	"errors": [
		{
			"title": "Operation failed",
			"detail": "Operation failed",
			"code": "VA900",
			"status": "400"
		}
	]
}
```
We (backend team) have had discussions on updating the code to be able to handle errors better and it would also allow us to send specific error messages to front-end. A related spike is: #36032. It'll be great if it can be prioritized.

**Comment by sarahknoppA6** [comment]
@jparker0425 @kristenmcconnell @niradatta1 @zach-park @ytsaoca we will need wireframes for this if it is a priority, in addition to the back end work.

**Comment by acrollet** [comment]
@loripusey we pointed this and pulled it in for Dan, couldn't find other actionable work.

**Comment by acrollet** [comment]
Staging validation:

pre-check-in functioned normally the first time:

![Screen Shot 2022-05-06 at 9.31.21 AM.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/a816d306-32c9-4612-a303-c6d7a7abdae0)

After completing pre-check-in, I loaded the same link again in a private browser window and was taken straight to the confirmation page after logging in:

![Screen Shot 2022-05-06 at 9.32.32 AM.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/c8fc4a1e-3857-4ef9-ace5-4ad25d84a443)

The pre-check-in complete endpoint was not called.
