### ISSUE TITLE
Request Content Review: HLR Step 4 - Submit Application

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3279]
**User story**
As a member of Benefits and Memorials team building on VSP, I need my content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3224)
- [InVision Design](https://vsateams.invisionapp.com/share/54USSB4RMA2#/393030462_Review_Application_-_Expanded)

**Acceptance criteria**
- [x] Content reviewed 
- [x] Required content updates/changes provided to Benefits and Memorials team

**Comment by peggygannon** [comment]
Hi, @carolynwill I've reviewed the "Review application" screen in the mockup. Please let me know if you have any questions about my comments. 

If you can let me know when the mockup is updated and I'll give the changes a final proof. Thx. 

cc @YanaRoy

**Comment by YanaRoy** [comment]
@rileyorr
