### ISSUE TITLE
[SSL Certificates Management] Document monitoring and renewal workflow 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32790]
## Description
As a platform operator, I need operational documentation that describes how SSL certificates are managed. 

## Background / context 
While documentation exists describing the renewal process specifically, what's needed is a high-level doc with links to additional resources, inventory, jobs, monitoring, and the like. 

- [Obtain or Renew Publicly Signed SSL Certificates](https://vfs.atlassian.net/wiki/spaces/OT/pages/1644625921/Obtain+or+Renew+Publicly+Signed+SSL+Certificates)
- [Obtain VA Signed SSL Certificates for External Backend Connections](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594013/Obtain+VA+Signed+SSL+Certificates+for+External+Backend+Connections)
- [Jenkins job that alerts on SSL certificates](http://jenkins.vfs.va.gov/job/utility/job/cert-expiry-scanner/617/console) that results in a notification that to #devops-deploys Slack channel, like [THIS](https://dsva.slack.com/archives/C37M86Y8G/p1636490399171800).

---

## Acceptance Criteria (AC)
- [ ] Operational documentation exists in Confluence for managing SSL Certificates
  - [ ] Summarize how SSL certs are monitored, tracked, and renewed
  - [ ] Link to the resources provided above
  - [ ] Provide links to Infrastructure as Code (IaC)

**Comment by mchelen-gov** [comment]
related issue to migrate Jenkins job: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32800

**Comment by jhouse-solvd** [comment]
relates to #32790

**Comment by jhouse-solvd** [comment]
I can pick this up and start the doc. I'll get feedback from those familiar w/ the process to ensure accuracy.

**Comment by jhouse-solvd** [comment]
Document [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/2418507777/Monitor+SSL+TLS+Certificate+expiration)

**Comment by johnny-jesensky-adhoc** [comment]
Thank you for looking into this @jhouse-solvd - that makes sense, and agree with your assessment. We recently received some separate feedback to increase the robustness of our External Integrations docs, so will look to include this in those updates.

We will close this ticket out, and create a separate card to add some greater guidance on requesting SSL certs.

FYI @jknipes
