### ISSUE TITLE
Migrate CMS infrastructure into VSP-managed services

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#328]
## Description

The Drupal CMS infrastructure was launched using a separate pattern in a separate AWS environment from the VSP. However, now the management of this infrastructure is going to be handed off at the end of contract to VSP staff, so we need to bring it under the management of the VSP tooling (Jenkins, Terraform, Ansible, etc). This epic is to track work on the VSP side to assist in this effort.

**Comment by ElijahLynn** [comment]
Subscribed. cc @jonpugh

**Comment by ElijahLynn** [comment]
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/328

**Comment by ricetj** [comment]
Timeline found in this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/388

**Comment by ricetj** [comment]
A lot of the work is being tracked in the CMS's team Jira, but will update here as needed.

**Comment by ricetj** [comment]
this work will continue and we will be working closely with the skeleton crew.

**Comment by ricetj** [comment]
@wyattwalter to add line about updating oncall docs
