### ISSUE TITLE
Discovery: Scoping work needed to implement MuleSoft as part of 10-10CG

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#32807]
## User Story

As an engineer I would like to understand the requirements needed as part of the implementation of MuleSoft to ensure as a seamless transition as possible. 

## Goals

Define any further next steps and develop a larger release plan as needed; ensuring we document our approach.

## Acceptance Criteria

 - [x] Investigate/Review CARMA Interface Document
 - [x] Document VA.gov implementation needs (re: switching over, testing)
 - [x] Testing/promotion plan (between environments)
 - [x] Identify necessary tech debt to tackle before do any switching e.g. Logging/monitoring
       - Might need to elevate Grafana/Loki work
 - [x] Cutover approach i.e. feature toggle or not, env variable, % percentage increase
 - [x] Create any eng implementation or further discovery tickets

**Comment by jchilders** [comment]
### Implementation will require the following:

1. Adding Flipper toggle to indicate whether to use Salesforce or MuleSoft
1. Storing the secrets needed for authentication
    - Add to AWS SSM Parameter Store. See [Store a secret in Parameter Store](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html#StoreasecretinParameterStore-Additionalresources)
1. Create new class(es) needed to submit form data and attachments
    - Add new config for MuleSoft to settings.yml: url, endpoint(s)
1. Update existing submission logic to respect Flipper toggle

### Testing

1. MuleSoft host visibility from vets API has already been confirmed
1. Per the CARMA team, an HTTP 200 response from MuleSoft will indicate successful submissions
     - No matching GET endpoint will be made available at this time
     - Vets API will log both the POST to MuleSoft, as well as the response

**Comment by MickinSahni** [comment]
New tickets added to the overarching epic. Can close this discovery ticket out
