### ISSUE TITLE
[Research] Pre-check-in Metrics/Monitoring

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32808]
Description: Work with engineering to decide on how we want to collect metrics. Document ideas on pre-check-in (and check-in) metrics. Gather ideas from the rest of the team. Review current dashboards (not mobile dashboards) to see what is available/confirm that it is accurate.

Conversation with engineering on metrics: https://dsva.slack.com/archives/C022AC2STBM/p1636731000399600

Tasks:
- [ ] Talk to Corey about previous metrics work
- [ ] Meet with engineering
- [ ] Document ideas

Acceptance criteria:
- [ ] Alignment on top 4-5 metrics for pre-check-in and confirm technical feasibility of these items
- [ ] Provide link to document (in GitHub) to the team

**Comment by kristenmcconnell** [comment]
Look into how might we capture whether Veterans revisit valid links for pre-check-in.  This will determine if we need to change the pre-check-in workflow if Veterans do revisit pre-check-in links.

**Comment by niradatta1** [comment]
Closing this out due to some scope change for this ticket (learning steps we need to take to understand GA). Will create a new ticket.  'cc @kristenmcconnell @ytsaoca @zach-park
