### ISSUE TITLE
Access for Troy Mosher

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#32818]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Troy Mosher

### Your Email

troy.mosher@oddball.io

### Name of Your Team

Platform Security, Security Lead, Oddball Inc.

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUKFMCiKvq+SdhxPMbQ16gy6hBWJ/ZpbW4QV6lNcQ1SzJJ2NiPFqT2T1Bpn1HPJj5qUJ7UUAfUyWavLsYPXuIpzu9PHzGMLBM1rKd4RqtfefFw/bgUOFBfw9+ctujtt8crQ3bt7XyjS8ZW/hbuT85luoa1VEax5yy8wUz9Eyq7nawSCV+8K//Dty+x14FFuyWSTvLga3rHwBmvOIgTxSH7BpipUwSy4ryGL57rHFNBNpWTQpcID1dJQ+dhrB9dPiRiPQugBnUVObeqT22rQoFHN4COE1LTe43Dzz/cF5q4i1VEFcPJ887OJYW9Ng+Itx2v/C+OfGZ6ohf4xDO3e8fCeubhrMt2VqBXziggYshgArN96NsUaE2lEnMgxX2pt9RruABgW3kNzKD8VbTfg97s4utaBvoHvj/C7NBmUTUQT0ocgfm9P56mCyhhHkuXNHtMm8SQ63YxC4frNfgrdJX8mAABeQOHM8SxA6z925X8eKDjW8SmEacswp9LT5TL6zU= mosher@DESKTOP-MCCDDJ5

### Desired AWS Services

Need read access to dsvagovcloud AWS account for Security auditing

**Comment by mleclerc00** [comment]
### AWS Access

User: Troy Mosher
COR: Amber Malcolm
Approval required: @mchelen-gov

**Comment by mchelen-gov** [comment]
@mleclerc00 EQIP transmittal date confirmed, request approved 👍

**Comment by mleclerc00** [comment]
Passed along login info to Troy, closing this ticket
