### ISSUE TITLE
Request Content Review: HLR: Submitted page (confirmation step)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3281]
**User story**
As a member of Benefits and Memorials team building on VSP, I need my content reviewed on the HLR: Submitted page to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3225)
- [InVision Design](https://vsateams.invisionapp.com/share/94USUZWV7MY#/393047724_HLR_-_Submission)

**Acceptance criteria**
- [x] Content reviewed 
- [x] Required content updates/changes provided to Benefits and Memorials team

**Comment by peggygannon** [comment]
Hi, @carolynwill I've reviewed the HLR Confirmation page mockup. Please let me know if you have any questions about my edits. I would like to look at the mockup again once my changes have been implemented. thx! 

cc @YanaRoy

**Comment by YanaRoy** [comment]
+ @rileyorr
