### ISSUE TITLE
Form controls are not properly aligned at some viewport widths

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#3282]
## What happened?

When resizing the browser while using Facility Locator I noticed that the form control layout breaks at approximately the small tablet, phablet, and mobile phone horizontal width. Enclosed screenshot was taken on my iPhone 8 Plus in landscape.

![facility-locator-breakpoint-form-issue](https://user-images.githubusercontent.com/57469/68698236-7b279100-054e-11ea-90ca-192151d7a468.PNG)

## Specs:
- Device: All
- Browser: All

## Steps to Reproduce
1. Go to https://www.va.gov/find-locations
2. View at viewport approximately 800 pixels wide — if on computer resize browser window; if on phone, turn to landscape view

## Desired behavior
Form controls should align and break to stacking when necessary to fit properly.

## Acceptance Criteria
As a VA.gov user I want to readily view the form inputs so that I can enter necessary data, enter my search, and view relevant locations.

**Comment by alexpappasoddball** [comment]
@mmiddaugh removing the triage-incident as this is correctly assigned to your team!

**Comment by mmiddaugh** [comment]
This issue is resolved
