### ISSUE TITLE
[Bug] Staging header v2 - iOS - missing VA logo

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#32821]
## What happened?
In **iOS phone Safari**, on **[Staging Homepage](https://staging.va.gov/)**, the following styling anomalies were observed:
- **Page-header** was missing **VA logo**
- **VA facility and status updates** alert close-box was missing, rendering alert undismissable.

**Screenshot**

![mh-bug-iphone-alert-no-closebox](https://user-images.githubusercontent.com/587583/141661684-03a1f3be-0862-4f66-b1c5-570df58f6a3e.png)

## Specs:
- Device: Apple iPhone 11
- Browser: Safari

## Steps to Reproduce
- URL: https://staging.va.gov/ [alert should display on initial load]
- Observe that:
  - **Page-header** doesn't have **VA logo**
  - **VA facility and status updates** alert doesn't have a close-box at top-right corner.

## Desired styling
- [ ] Header should have VA logo.
- [ ] Alert should have a close-box at top-right corner.  Clicking that should close the alert.

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
Just need to add width 40px to the logo svg: 
![image](https://user-images.githubusercontent.com/12773166/141834825-f15007e8-82be-425d-8df0-bedd06616af6.png)

alert close-box was missing, rendering alert undismissable should be done in separate ticket as that's a design system issue CC @brianalloyd

**Comment by brianalloyd** [comment]
@kelsonic @tlei123 the `alert close-box was missing, rendering alert undismissable` can be found in ticket #32630, this was identified last week during testing as the dismissible function is hidden and users have to swipe right in order to dismiss.

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy tomorrow
