### ISSUE TITLE
Create Github document on process for updating rates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32833]
## Issue Description
Every year the Sitewide Content team needs to update various rates pages with new numbers and information. When we do this we also turn the current rates page into a past rates page. We need to document this process so that any content team member will know how to do this going forward. 

## Tasks
- [x] Create a GH doc with all the essential info about how to create new rates pages (including cloning the page, checking the numbers against the original doc, updating the info in the left nav, which stakeholders to contact for which rates pages, among other specifics) (Selina)

## Acceptance Criteria
- [x] New process doc is in Sitewide Content teams folder

**Comment by lunascoop** [comment]
@RLHecht here's the new rates updates process doc.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-update-rates-pages.md
