### ISSUE TITLE
TUD: Number of TUD Accounts Unavailable

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#32831]
The inverse of this ticket - 
https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/32164

As a TUD stakeholder, I would like to have a dashboard card that will show how many TUD Accounts are unavailable in the tool.

## Tasks
- [x] Create a Domo Dashboard Card that visually represents the total number of test accounts unavailable in TUD.
    * This data requires the prior `Evaluate TUD Data Ingestion` task to be completed first.

## Acceptance Criteria
- [x] _A dashboard card exists reflecting the total number of TUD account unavailable._

**Comment by holdenhinkle** [comment]
Compete:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/bf80b87f-a978-4688-a52a-64e4d38c802a)

**Comment by pjhill** [comment]
Looking good
