### ISSUE TITLE
Adding Brandon Clapp to DSVA Slack

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#32834]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add [brandon.clapp@accenturefederal.com] to DSVA Slack as a full member. 

Are you requesting to add an individual as a:

-[x] **Full member**

Brandon Clapp recently joined us as a new FE developer on the AFS Education team. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
