### ISSUE TITLE
Access for Lauren Simpson

### ISSUE THREAD

**Issue by laurensimpson14** [department-of-veterans-affairs/va.gov-team#32841]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Lauren Simpson

### Your Email

lauren.simpson@empiricalpath.com

### Name of Your Team

Analytics and Insights

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCt6wbo+LPe+G7tGnKzXmhu7mYIft7nsdJbsytu3o3BuafKUasdI4TIMT7o2eYXJoflUq9Fdo7/i4nqbBC570/9OCGHWwayNPKCInSjVcWLkgCSrXh6DNDasV8RMTgTF3SvsHCkL1ILvZbJE/uRnoNKDBtvqE6Oz3T/MRkugBcW3R32J3rvMf6e5KE84kmhY4Oehl6PcvmOxmDny257ynf7Z8fsKAy/3VXBwyfgHGsDD3j1ekmGJxQYKrEvpKY7GkElZFvoSDu0gVenmUg825jmAVnG2iU73vgzczmDHHdPRmOXqrJKvMNCeQ0mmriZBLVkeDQO1gLISrDipORZ2Yg3ecqogZR7dQ/hQyWJKen8/hTFK3rVpOEddw/UOTjE/3m1+GNk8YILZoS1D3IHOGciziWKzPH7VFEXgj+uw3iwvc7pWzFUkOOsE2K7P14VrmWNzhwrKu5gyA0QIx6cpgjGoz2M3qnhpJutFr303B8MyCtiK4zGCR3imhK8GUKTjok= laurene7@LaurensLaptop

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
