### ISSUE TITLE
[BE] Profile: Personal Information Revision - Demographics Service Object

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32847]
## Issue Description
As a BE engineer, I want to create the demographic service object to support the integration of PI data from the VA Profile demographics API.

---
## Tasks
Create Service Object:
- [x] Service class
- [x]  Response class

## Acceptance Criteria
Create Service Object:
- [x] Service class
- [x]  Response class

**Comment by MarciMcGuireGCIO** [comment]
Blocked until we have specs from MPI

**Comment by Samara-Strauss** [comment]
Removing @lihanli from this work, as he will be focusing on the on-site notifications integration. Tom can own this now, though he shouldn't hesitate to ask Lihan questions as needed.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for the update, @tpharrison !

**Comment by Samara-Strauss** [comment]
Thanks for the update, @tpharrison. You and Marci should meet to figure out what you can get done in this coming sprint (tomorrow), and that may also involve a convo with VA Profile on any further delays or updates you should expect to get up and running.

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison would you like me to create a testing ticket for this work, or is that already factored in?  Thanks!

**Comment by tpharrison** [comment]
Yes, I think thats a good idea since the API may not be finalized yet. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Great; thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @tpharrison !
