### ISSUE TITLE
Design Feedback - Midpoint Review Decision Tools: Find a VA Form - PDF Download Instructions

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#32842]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Remove the drop shadow form the button. See [design.va.gov](https://design.va.gov/components/buttons)

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by zacharymorel** [comment]
Good afternoon, which button has a drop shadow? I am unable to fine a drop shadow on the buttons on the modal.

**Comment by MarciMcGuireGCIO** [comment]
@seanasewell neither Zach nor I have been able to reproduce a drop shadow on any of the buttons in Find a VA Form.  I've tested on Windows Edge, Chrome and also iOS Safari.  Zach has tested on Mac Firefox.   Do you have a screen shot or can you give us the conditions under which you saw the shadow?  Thanks!

**Comment by seanasewell** [comment]
> @seanasewell neither Zach nor I have been able to reproduce a drop shadow on any of the buttons in Find a VA Form. I've tested on Windows Edge, Chrome and also iOS Safari. Zach has tested on Mac Firefox. Do you have a screen shot or can you give us the conditions under which you saw the shadow? Thanks!

It was originally from the "working" section of the Sketch designs so you can disregard. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@seanasewell - Good deal; thanks!
