### ISSUE TITLE
Original Claim Messaging for Missing IDs

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3284]
## User Story or Problem Statement
As a Veteran attempting to file for a disability claim for the first time, I need the proper VA IDs so I can begin the application process.

## Goal
_Capture which VA ID is missing in order to start application process_
_Display messaging to user who cannot move forward in the process_

## Acceptance Criteria
Scenario: A system user intends to file a disability claim for the first time
GIVEN a user has successfully logged in
WHEN the user selects to begin their application 
*and* the user is missing necessary VA ID 
THEN the system will provide messaging to the user giving other options to complete the 526 form.

## For Reference
[Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3285)

**Comment by kevinstachura** [comment]
@ndsprinkle the design for this is located here: https://vsateams.invisionapp.com/share/JNUPVDECGFK#/393288220_526_Gating_-_Edge_Case_Alert
