### ISSUE TITLE
[Tier 3] Salesforce Case 06100481- Logon Issue

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#32849]
## Issue Description
_Please review details from Salesforce CRM describing the issues that veteran has been experiencing for some time._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Case Notes
In April the Veteran came to the United States and got a new computer and printer and scanned all of his documents, but then he couldn't upload the information to va.gov because he couldn't sign in.

On 8/27 the Veteran got an email from VA Tech Support acknowledging his having contacted the WHH for assistance with his email address issue when logging into va.gov (05588522 was his ticket number). His problem was that he couldn't log into va.gov through a computer, only through his phone - it had nothing to do with his email address.

On 9/1 he spoke with someone at the WHH. He created a claim on his phone. _(Possible PII, Removed)_ is his claim number as of 10/1/21, and VA said they did receive it, but he wants to add his medical records to the VA claim, for what he is claiming, but he does not know how to upload them from his phone (there is no clear direction specifically for that on va.gov).

The Veteran tried again to sign in to va.gov and was taken to an IBM screen, and he sent a photo of it to the va.gov technical team. The last contact with VA IT was 9/4 in an email he'd sent them in which he asked for acknowledgement of receipt of his email message, but he has not heard back from them.

On 9/27 he spoke with Nicholas at 800-983-0937, who said the Veteran could log in via e-Benefits, but when he did that it took him to va.gov, and it was easy to log in using his cellphone, but he couldn't do anything by using his computer - which is what he really needs to be able to do.

The Veteran has not been able to log in using DS Logon or I.D. Me, he kept getting "Error 16" when trying I.D. Me, with no other text appearing. The Veteran has been using Chrome.

**Comment by codyreinold-usds** [comment]
Could you please provide the screenshots referenced (IBM screen)?

**Comment by codyreinold-usds** [comment]
Additionally, I see this issue is from 9/27; could we connect with him to see if the issue is still occurring?

VA IAM recently resolved an issue where non-US English devices (eg: those with Spanish set as the default language) would not successfully authenticate and would show and IBM screen. This may be related.

**Comment by starlow00** [comment]
Followed up with user, per @codyreinold-usds 's request. Awaiting response.

**Comment by Kimberley2019** [comment]
From: REDACTED 
Sent: Thursday, December 2, 2021 9:43 AM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: Technical issues with VA.gov -- are you still experiencing them?

Good Morning,

I logged on last night with my laptop, I had to log in to ebenefits first, then I went to the va site sucessfully.  However, I get an error 16 message if I log directly to va from my laptop or cell phone.

Thank you,

REDACTED

**Comment by Kimberley2019** [comment]
@codyreinold-usds just sent you the email containing the screenshots.

**Comment by codyreinold-usds** [comment]
Our vendor has resolved this issue, and they should now be able to access. Please have the Veteran retry.

**Comment by Kimberley2019** [comment]
Case closed.
Assistance provided.
