### ISSUE TITLE
[Tier 3]Salesforce Case 06008478 - Foreign Address Issue

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#32850]
## Issue Description
_Please review details from salesforce CRM case concerning foreign address issue._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Case Notes
Help Case Notes
verified PII
veteran called in stated he is trying to use VA.gov website. veteran stated he is a NASA engineer and is unable to use website.

veteran stated if he cant use the system then you know the system is outrageous. veteran stated the web based platform will not accept his foreign address or phone number.

veteran stated the VA pays ID.me to handle that and they should know better and the system should be adept enough so a veteran doesn't have to go through this.

veteran stated this is a nightmare and needs to be fixed as soon as possible.

veteran stated he has spoken to patient advocate, assistant director and director, with no avail.

veteran is requesting someone to contact him about this.

**Comment by starlow00** [comment]
Hello @codyreinold-usds . Following up on the status of this. Thank you!

**Comment by Kimberley2019** [comment]
@codyreinold-usds any updates?

**Comment by codyreinold-usds** [comment]
The Veteran was successfully contacted on 12/13 by ID.me. He elected to pause the process, as he is waiting for his DD214 to arrive. There is no further timeframe provided by the Veteran.

**Comment by Kimberley2019** [comment]
Thank you @codyreinold-usds would you like to keep this ticket open until you hear ack form the veteran?

**Comment by Kimberley2019** [comment]
@codyreinold-usds closing case.
