### ISSUE TITLE
[Design] Original Claim Messaging for Missing IDs

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3285]
## User Story or Problem Statement
As a Veteran attempting to file for a disability claim for the first time, I need the proper VA IDs so I can begin the application process.

## Goal
_Provide an inability to continue response to Veterans who are missing VA IDs required to fill out an original 526 claim_

## Tasks
- [x] Design messaging screen
- [x] Request content review #3609 

## Acceptance Criteria
Scenario: A system user intends to file a disability claim for the first time
GIVEN a user has successfully logged in
WHEN the user selects to begin their application 
*and* the user is missing necessary VA ID 
THEN the system will provide messaging to the user giving other options to complete the 526 form.

**Comment by kevinstachura** [comment]
Invision design link: https://vsateams.invisionapp.com/share/JNUPVDECGFK#/393288220_526_Gating_-_Edge_Case_Alert

**Comment by kevinstachura** [comment]
Alert messaging in design needs a content check - @peggygannon can you take a look?

https://vsateams.invisionapp.com/share/JNUPVDECGFK#/393288220_526_Gating_-_Edge_Case_Alert
