### ISSUE TITLE
Access for Jacob Gacek

### ISSUE THREAD

**Issue by jgacek** [department-of-veterans-affairs/va.gov-team#32854]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT - Scott Mason

### Your Name

Jacob Gacek

### Your Email

jacob.gacek@thoughtworks.com

### Name of Your Team

Team Orchid (Virtual Agent) - Developer - Thoughtworks

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need access to the AWS secret manager so I can add pipeline secrets for the va-virtual-agent team to AWS. I had access to AWS before but I believe it was taken away because I did log on for 90 days.

**Comment by mydesignrocks** [comment]
@mchelen-gov please review for AWS access.

**Comment by mchelen-gov** [comment]
@mydesignrocks EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by mydesignrocks** [comment]
DMd the password to the user.
