### ISSUE TITLE
Add component migration functionality for SegmentedProgressBar

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32862]
## User Story

Dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/32860

Once the Web Component is written, we need to have [the migration script](https://github.com/department-of-veterans-affairs/vets-website/tree/master/script/component-migration) be able to handle `<SegmentedProgressBar>` -> `<va-segmented-progress-bar>`

## Tasks

- [ ] Add transformer to migration script for new component
- [ ] Add sample file covering use cases of current React component

**Comment by pdavies88** [comment]
Related PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19583
