### ISSUE TITLE
[SSL Certificates] Clean up wildcard *.vets.gov key & certificate

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#32863]
## The Problem
The `*.vets.gov` wildcard cert is expired (as of 6:59pm EST Nov 12) but still exists in a number of places. It should be deleted.

## Extra Context
- The wildcard cert is configured as the "Default" certificate on our revproxy ALBs (not sure if we need a new default or can just survive w/o a default cert)
- In the `prod` revproxy deployment config, the `wildcard.vets.gov.key` & `wildcard.vets.gov.chained.crt` files were modified to actually contain the `vets.gov` key & cert respectively ([link to code in PR](https://github.com/department-of-veterans-affairs/devops/pull/10270/files#diff-80eddf247de17c8391b49f21b49284df5b3b06ef1112d5b85e45a4f3b5f32ccbR153-R162)). The names of these files should be updated to reflect the fact that they are no longer "wildcard". This will require changes to revproxy nginx config.
- This is a followup item for https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/333

## Work to be Done
Delete the wildcard cert from...
- [x] credstash
- [x] AWS SSM (if it exists here, I'm not entirely sure)
- [x] lower-env BRD deployment config, nginx confg, & jinja templating
  - [x] dev
  - [x] staging
  - [x] sandbox
- [x] Update `prod` BRD deployment config to rename `wildcard.vets.gov` key & cert to `vets.gov` (see the "Extra Context" section of this ticket for details) 
- [x] AWS ALB & IAM terraform
  - [x] prod 
  - [x] dev
  - [x] staging
  - [x] sandbox
- [x] The devops GH repo

**Comment by jhouse-solvd** [comment]
Assigning to Jeremy. Jeremy will lead a mob session with the team to raise awareness for the cert infra.

**Comment by jbritt1** [comment]
For tracking, our original attempt did not pan out in sandbox env (https://dsva.slack.com/archives/CBU0KDSB1/p1642706555084100) due to the nature of how things are set up in our nginx configs. We wound up reverting and continuing to work on https://github.com/department-of-veterans-affairs/devops/pull/10608.
