### ISSUE TITLE
TUD: Release Plan

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#32865]
## Assumptions
- Users will check-in and check-out users using the approved process
- Synchronizing test user attributes from the test session to TUD is more helpful than hurtful
- SREs have a playbook with sufficient information to field most of the support requests for TUD
- Documentation built into TUD's GUI helps users
- TUD will mostly be helpful for new people who do not have preferred test accounts already
- TUD will help automatically maintain the integrity of test account information

## Stakeholder Bets
- This is not going to make much of an improvement in VFS team testing experience because the problem isn’t finding test users, it’s having the right test users with the right test information associated.
- The TUD documentation assumes a lot of knowledge about building on VA.gov and may cause confusion in some users.
- The test data associated with test users could be automatically scanned and updated in TUD.

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:
- Desired date range or test duration: Q4 2021
- Desired number of users: 3 (Testing Tools Team Members)
- The group(s) from which you'll recruit test users: VSP
- How you'll recruit test users: Voluntold
- How you'll give test users access to the product: All users on the team can access
- What "Success" criteria will you look at before launch? We looked to ensure that the product works as intended based on current functionality
- How you'll measure your "Success" criteria? Initially success will be measured by how many people adopt/use the Test User Dashboard

### Results:
- Number of users: 2
- Results per your "Success" criteria: TUD seems to work as intended based on current functionality
- Number of bugs identified / fixed: None
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes
  - The current approach with basic Auth is not ideal for wider adoption, so we will prioritize this feature for a future iteration
  - There were no metrics being tracked for usage, so we identified and created mechanisms to track those metrics
  - There is currently no process for creating new test users
  - Current sets of Test Users exist in markdown files spread across the platform, we would like to be able to condense those into TUD, and create a single source of Test User credentials.

### Planning:
- Desired launch plan: We will plan to release to a small set of teams, 2 at a time - allowing us to get them up to speed, ensure our documentation and support is sufficient, and also to understand their current sets of test users so that we can phase those markdown files out as we ramp teams up on TUD
- Desired launch date: 12/6/2021
- Post-launch KPI 1: During the rollout, the number of accounts loaded into TUD is increasing
- Post-launch KPI 2: During the rollout, checkout and use of accounts through TUD is increasing

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by holdenhinkle** [comment]
This comment will be deleted.

Links re design, content, etc.:
[Test User Accounts_Mock Up revisions #20113](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20113)

[TUD: Implement design audit fixes #23838](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23838)

[[Content review] - Test User Dashboard #25352](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25352)

[TUD - Content review audit implementation #25354](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25354)

[[Content review] - Test User Dashboard #25850](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25850)

[Test User Dashboard Content Review](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1683980297/Test+User+Dashboard+Content+Review)

[Wireframes](https://whimsical.com/test-user-dashboard-content-feedback-CPAoi2ehrK4SD2Aq8N3Kn3)

[TUD: Fix minor accessibility bugs #26177](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26177)

**Comment by pjhill** [comment]
WASA Scan Requested 3/21 -- REQ6726301
