### ISSUE TITLE
[Tier 3] Salesforce 06188266 - Cannot view disability letter 

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#32869]
## Issue Description
_Please review details below from Salesforce CRM to assist with issue veteran is experiencing._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Case Notes
Veteran can log into MyHealtheVet but when he tries to see the awards letter it takes him back to the login and continues to give an error. He has been dealing with this for months, he has submitted a ticket before and he was told it fixed but it is not fixed. The Veteran just wants to see his disability letter. He has spoken with MyHealtheVet and they told him its not them it would be with us. Let's get this fixed as soon as possible!
Verified PII- email and phone number are up to date.

**Comment by starlow00** [comment]
Hello @vhenry07, @Mottie, @michelpmcdonald, just checking in to see if there has been a status change on this. Thanks!

**Comment by Mottie** [comment]
From the front-end perspective, I need to know what error is being seen. We would need some information about this Veteran, so we can look up the record. As it stands now, there's nothing we can do without more information.

I've been focusing my time elsewhere, so I apologize that I haven't kept these support tickets higher on my priority list.

**Comment by vhenry07** [comment]
@Kimberley2019 Would it be possible to set up a call with this Veteran? It would help speed troubleshooting efforts to see what they are seeing realtime.

**Comment by Kimberley2019** [comment]
@vhenry07 I have reached out to the veteran.  Once he responds I will pass that along so that your team can set up a call to troubleshoot.



From: VA Technical Support 
Sent: Thursday, December 9, 2021 5:53 PM
To: 'n.bennett007@gmail.com' <n.bennett007@gmail.com>
Subject: RE: VA Benefits Letter Issue

Good Evening Mr. Bennett,
Can you please advise if you are able to have a shadowing call with our engineering department in order for the team to assist in resolving this issue?
If you are able and willing to be a part of this process, please provide your best contact number and a few days and times that you would be available.  The process would be around 30 minutes.
Looking forward to hearing back from you.



Kind Regards,
The VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
@vhenry07 @Mottie 

From: VA Technical Support 
Sent: Wednesday, December 15, 2021 10:19 AM
To: 'n.bennett007@gmail.com' <n.bennett007@gmail.com>
Subject: RE: VA Benefits Letter Issue

Good Morning Mr. Bennett,
After further review, the team would like to set up a shadowing call with you so that they can see the error in real time.
Are you able to provide three dates and times that work best for you?
We look forward to hearing back form you in order to move forward with assist you in this matter.

Ref Number: 32869

Kind Regards,
VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
No response from caller.  Closing ticket
