### ISSUE TITLE
Access for Hocine Halli

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#32873]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Hocine Halli

### Your Email

hocine.halli@va.gov

### Name of Your Team

AFS- Legacy AO Team 3

### Service(s) You Want Access To

SOCKS

### Public SSH Key

AAAAB3NzaC1yc2EAAAADAQABAAABgQC1ULVk7XTzWblSYfI1PXvENCbnRHymSG2SCvnJVvgVoV9aDmLViqsJI0OT9Q8cpx7dDbK/07u5NYPaZ/GOCszyH0a2pMwXMiJs0Fk+cv6e31rUWfAYukECce4X2InevjAzTk7MKCHtRgyhpch23lIJIyD+bHDgsbwGkxfUr3sW7ppgtIna5dvmTRGzxOo6WHjAtTT9KtwOeq2jzVULnipMhGISR+6QB6x2BgdYK9zzhDjDhpzS9KjC6nnGN3lejbd2sGwwOer91rqrdOAnUEy4mWmWenm58bBINphMpTdBON2vXaRaqZV6RdpmINRlRtzx1lUlVZNWP/lzy4pZ28IDDE03Gy/cz8dB7+MzMzUIy+AhoXrvIL6GYKzZFFKldffv/6+2/x9hG9O/W1wj9v6EQ4Icwm+Jqm2+33M9jUWBCu6URVq+4v4titS7YsgYD1APuVSZSp/GhDqy1QRC5fvZU/nQNN7Ex1dEfD8Vbo8KzwzANxEP6pFSVJ6QHHW90hE= hocine.halli@AFSMWB8MW2H6F5P

**Comment by hallihocine** [comment]
COR Name: Riley Ross

**Comment by mydesignrocks** [comment]
@hallihocine - key has been updated, please verify access

**Comment by hallihocine** [comment]
@mydesignrocks - Yeah, key approved. I have my Socks proxy up and running. Thanks!

**Comment by mydesignrocks** [comment]
thanks for confirming, closing.
