### ISSUE TITLE
Access for Ian LaFlamme

### ISSUE THREAD

**Issue by ilaflamme-va** [department-of-veterans-affairs/va.gov-team#32879]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Ian LaFlamme

### Your Email

ian.laflamme@libertyits.com

### Name of Your Team

Lighthouse API Development and Operations. Software Developer. Liberty IT Solutions.

### Service(s) You Want Access To

SOCKS

### Public SSH Key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRGqWETaPeC2QkUd1xk7t3nnvu2BYkgERdgk6v/+53t5F2NAV4z5DI2k2t+cX6WxSAbbe/vPHZ07ePndaO1VC1EKnVWcrCkNIM4cCr0+qFzb5jt7hSG3mIHjlo6wkYTsELvUoRo4N1vBRG2DY5jX4hlI1IyGg778PTMZAPC3XsdblOG2YmMxBg7ln0JiYj9+fbz2mnUYQRSHM29/5gDTH8AVWvwQcFf51rJGpiPSDO+BvDrNaLQf0RSQ88vE8Hs48v68GGtn11DG1HAsRxVKcr8DTMGqcl5uh0d8jw5IfEyiTgIwITL391qMirb0eoGvS8z4VIPX06/OymO2GcEJRDU1mOtalUqo/af9pdguAowhi8v8X5kvofEsFq9yzYbICFws85ph6XuI3A66/wdfn8x/EYn4BI8GnIII1LNIx9lE6gONlVqilXxC5MD1Nt1zycgfDvO8uUdBZcRjXdzMlUXwjGK3ahwCtdY5Bq7bZsE+A9UrQFLjZ5xoTxj0Ii5b8= ilaflamme@Ians-MacBook-Pro.local
```

### Desired AWS Services

Soxy proxy access for supporting projects as part of the Lighthouse contract.
Specifically kibana logging, etc.

**Comment by ilaflamme-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ilaflamme-va** [comment]
I previously had access, but need to refresh with a new key.

**Comment by mydesignrocks** [comment]
@ilaflamme-va can you please verify your socks access now.

**Comment by mydesignrocks** [comment]
closing this, please reach out to platform support slack channel for any issues.
