### ISSUE TITLE
Filter & Transform node-documentation_page content

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#3288]
## Problem Statement

Our tome-sync data doesn't match up with our templates, and we need to follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835) to ensure that the data will be compatible with our current templates.

## Goal

Content from `node-documentation_page` entities match their corresponding entities from pages.json

**Comment by cvalarida** [comment]
Not sure that these are supposed to be published. Looks like they're for internal use.

Can you verify, @ElijahLynn, @swirtSJW, or @jefflbrauer?

**Comment by jefflbrauer** [comment]
They are to be published from drupal but there are no FE templates that consume this content type atm so it’s fine. There may be a future where we do read this content and style on web, TBD
