### ISSUE TITLE
Discovery: Surface the chromatic storybook link for each PR

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32888]
## Issue Description

In the `component-library` repo, we are running a job in every PR that [deploys storybook to chromatic](https://github.com/department-of-veterans-affairs/component-library/blob/996d31551d9c628c9b78794e33d8a1d50548d82c/.github/workflows/chromatic.yml#L32-L40) on each push. Right now it isn't very obvious that this is happening, and it is hard to find the link.

There are two relevant chromatic links for this:

- Storybook link for the entire branch
- Storybook link for a specific commit 

The second link is logged in the GH action:

![image](https://user-images.githubusercontent.com/2008881/141864286-8d1d9c47-04fd-481e-9194-36f289b419b1.png)

But we may want the first link to be what gets "pinned" to a PR somehow. Chromatic gives us this:

> Get a permalink to component-library’s latest published Storybook on a given branch. Replace `<branch>` with the designated branch.
>
> `https://<branch>--60f9b557105290003b387cd5.chromatic.com`

---
## Tasks
- [ ] Come up with and consider solutions for making the chromatic storybook link more visible on PRs

**Comment by andresriveratoro** [comment]
Using the permalink and replacing `<branch>` with `33479-va-accordion-item-e2e-test` works, but it doesn't for `34279/progress-bar-aria-label`. I also tried `34279-progress-bar-aria-label` and `34279progress-bar-aria-label`.

**Comment by andresriveratoro** [comment]
We could modify `PULL_REQUEST_TEMPLATE.md` to include a section titled Chromatic with
`https://<branch>--60f9b557105290003b387cd5.chromatic.com` and have the developer replace it with the correct branch name. It would be awesome if we could automate it.

**Comment by andresriveratoro** [comment]
https://github.com/apps/handlebar-templates

**Comment by andresriveratoro** [comment]
https://github.com/tzkhan/pr-update-action

**Comment by andresriveratoro** [comment]
## Recommendation

We can modify `PULL_REQUEST_TEMPLATE.md` to include a section for Chromatic with a default link of `https://{{head.ref}}--60f9b557105290003b387cd5.chromatic.com`. This GitHub action will replace `{{head.ref}}` with the branch name.

GitHub Action: https://github.com/marketplace/actions/dynamic-template
Repo: https://github.com/luigibertaco/dynamic-template-action

This is the code for this GitHub Action. We can use this Action or create our own using this as a reference.

```

const core = require('@actions/core');
const github = require('@actions/github');
const mustache = require('mustache');

async function run(){
    try {

      // requires GitHub Token to allow PR updates
      const ghToken = core.getInput('token', {required: true})

      // Get the JSON webhook payload for the event that triggered the workflow
      const payload = JSON.stringify(github.context.payload, undefined, 2)
      //core.info(`The event payload: ${payload}`);

      // Show PR details
      const pr = github.context.payload.pull_request;
      core.info(`Pull request body: ${pr.body}`);
      core.info(`Pull request title: ${pr.title}`);

      // update PR body
      const octokit = github.getOctokit(ghToken);
      const request = {
        owner: github.context.repo.owner,
        repo: github.context.repo.repo,
        pull_number: github.context.payload.pull_request.number,
        body: mustache.render(pr.body, pr),
        title: mustache.render(pr.title, pr),
      }
      core.info(`update request: ${request}`);
      const response = await octokit.rest.pulls.update(request);

      core.info(`Response: ${response.status}`);
      if (response.status !== 200) {
        core.error(`Updating the pull request has failed: ${response.text}`);
      }

    } catch (error) {
      core.setFailed(error.message);
    }
}

run();
```
