### ISSUE TITLE
PST-IET demo API: Street Address Validation 

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#32899]
# PST-IET demo API: Street Address Validation 

As there is a need to improve the integration experience with upstream/partners/3rd-party APIs, a demo model microservice API for Street Address Validation must be researched, programmed, and demonstrated to use the public USPS free API functioning as otherwise VA upstream API.

## Implementation

A production-grade demo microservice high performance Go API to interface with USPS free API service for address validation with a call like
**https: //secure.shippingapis.com/ShippingAPI.dll?API=Verify&XML=...**
as per [https://www.usps.com/business/web-tools-apis/#dev](https://www.usps.com/business/web-tools-apis/#dev)
that will process the PII data (street address) without saving it and will report/log the metrics of the call to Datadog to make it available for the Statuspage React app.

## Acceptance criteria

The application must be containerized with HTTP endpoint, a log entry per every call is produced for performance measuring purpose only with no PII data included, the data meets VA enrollment system standards as per:
https://github.com/department-of-veterans-affairs/vets-api/pull/5565

**Comment by ewilson-adhoc** [comment]
Moving to the icebox since this is not relevant to our current goal of splitting vets-api into microservices.
