### ISSUE TITLE
Capture and report frontend build metrics

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#32896]
## Details 

As a Platform engineer or PM, I need to be able to view metrics related to our build pipeline over time so that I can track trends, identify issues, and learn how to iterate and improve.

Based on outcome of discovery ticket #9556 

Updates: 
- We have released GitHub Actions! :tada:
- DataDog's pipeline visibility tool is available for GitHub Actions! :tada: 

This ticket is to implement the Datadog pipeline visibility tool. May be split into multiple tickets once we dig into the tool's implementation and estimate.

Metrics we need to surface: 
* Build duration in vets-website and content-build
* Full pipeline duration in vets-website and content-build
* Full deploy success/failure rate in vets-website and content-build
* Success/failure rate of content releases

**Comment by meganhkelley** [comment]
As discussed in sprint planning today, we should start with vets-website. 

CMS team is implementing build metrics for some portions of content-build. Once we've done vets-website, we can assess whether their metrics meet our needs for content-build or whether we should do content-build as well. 

@alexandec Could you please give this a story point estimate before you begin work on it? Thanks! (Include both vets-website and content-build work in the estimate — we can change the plan as needed)

**Comment by meganhkelley** [comment]
Unit test tracking — 

* Unit test tracking is our of scope for this ticket
* Check with testing tools team on what they're tracking and whether we should add the datadog test tracking stuff here or whether that would be duplicative 
* If we decide we should add the unit test tracking functionality, make new ticket for that

**Comment by alexandec** [comment]
Pricing note from DataDog's [Set up Tracing on GitHub Actions Workflows](https://docs.datadoghq.com/continuous_integration/setup_pipelines/github/) page:

> The GitHub Actions integration is in beta. There are no billing implications for activating the GitHub Actions integration during this period.

This implies a potential future charge, just FYI.

**Comment by alexandec** [comment]
I'm unable to complete installation of the DataDog CI Visibility integration because I don't have organization owner privileges for `department-of-veterans-affairs` on GitHub. I created [a ticket](https://github.com/department-of-veterans-affairs/github-user-requests/issues/9142) in github-user-requests to request installation by someone with the correct privileges.

I also tried installing the integration using my personal GitHub account. Installation was successful, but I was not able to enable the integration for `vets-website` or `content-build` -- it was only installable for repos I owned inside my account.

**Comment by alexandec** [comment]
Progress here: I created a GitHub app from within DataDog. I had to create the app in my personal GitHub account. Then I requested to transfer the app to the department-of-veterans-affairs org. They will need to approve the transfer and add the app to the two repos we want to monitor.

**Comment by alexandec** [comment]
Transfer was approved and the DataDog CI Visibility integration is now functioning! All builds for `vets-website` and `content-build` are being recorded. URL is https://app.datadoghq.com/ci/pipelines
