### ISSUE TITLE
[Content/Design] Cancellation/Reschedule Review 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#32894]
### Request

Request review and recommendation for the cancellation message content to the user. We are working on a short term solution for re-scheduling an appointment or a request for an appointment. 

There is a concern that the veteran may not read that they need to contact the facility to reschedule when confirming they wish to cancel their appointment. The goal is to show an explicit message to the veteran if they want to reschedule their appointment or request that they must call the facility. The veteran also has the option to cancel the appointment/request and book a new appointment/request in the VAOS application. 

---
### Background

When a user wants to re-schedule their current appointment/request, the user will need to cancel the appointment/request and schedule a new appointment/request. 

--- 

### Screenshots

Use Case 1: 
User enters the home page and views the Upcoming appointments and clicks on Details to cancel their appointment:

<img width="1153" alt="Direct_Schedule_Flow" src="https://user-images.githubusercontent.com/90797205/142451283-95b39b01-5da3-47b5-9567-4d5596e8764b.png">

<img width="1266" alt="Details_Direct_Schedule_Cancel_Flow_2" src="https://user-images.githubusercontent.com/90797205/142451479-6fd377d4-e59b-411d-8db0-7002f7973565.png">

The veteran may also call the facility to reschedule their appointment. 
We may also want to consider showing a message to the veteran that a facility will not be contacting to reschedule an appointment. 
What would be the recommendation message for the vet? 

Use Case 2: 

User enters the home page and views the Requested appointments and clicks on Details to cancel their requests:

<img width="944" alt="Details_Request_Cancel_Flow_1" src="https://user-images.githubusercontent.com/90797205/142451450-6a2dd7ae-9f1e-4760-a5ea-ff50ba485110.png">

<img width="592" alt="View_Appointment_Request_Flow" src="https://user-images.githubusercontent.com/90797205/142452428-bdf8251a-5f7d-4584-a01a-d8cdd0e468f9.png">

The veteran only sees a message asking the veteran if they would like to cancel the request. We have no instructions on how to reschedule an appointment request. After the user cancels the request, the message states that the VAOS application has notified the facility on the canceled request. The VAOS application does not notify the facility when a request has been canceled. Please advise on how this should be displayed to the veteran. 

We may want to show a message stating to the user that the facility will not be contacting the user for rescheduling a request for an appointment. 

Use Case 3: 
User enters an appointment request and successfully submits it, then on the request appointment details screen the user can click on Cancel request: 

<img width="676" alt="New_Request_Schedule_Flow" src="https://user-images.githubusercontent.com/90797205/142452588-ab257697-8462-4cc2-9126-7650b059c712.png">

<img width="592" alt="View_Appointment_Request_Flow" src="https://user-images.githubusercontent.com/90797205/142452428-bdf8251a-5f7d-4584-a01a-d8cdd0e468f9.png">

_This is similar to Use Case # 02_    
The veteran only sees a message asking the veteran if they would like to cancel the request. We have no message on how to reschedule an appointment request. After the user cancels the request, the message states that the VAOS application has notified the facility on the canceled request. The VAOS application does not notify the facility when a request has been canceled. Please advise on how this should be displayed to the veteran. 

We may want to show a message stating to the user that the facility will not be contacting the user for rescheduling a request for an appointment. 

Use Case 4: 
User schedules a direct appointment in the VAOS application but cannot cancel the appointment from the confirmation appointment details screen. 

<img width="1267" alt="New_Direct_Schedule_Flow" src="https://user-images.githubusercontent.com/90797205/142452636-ce6c93a8-06fe-4455-bc3f-44cd292e259d.png">

Currently this use case doesn't allow the veteran to cancel the appointment from the confirmation details page. In the event if we have the cancel action available, would we want the message to be similar to what we would implement in use case 1?

**Comment by DanielleThierryUSDSVA** [comment]
## Use case 1

### Action screen
_Note: Adding language around how to reschedule. I think we can frame in the positive, avoiding the explicit “we won’t contact you” and still be clear about how to reschedule. Also, we typically use "Are you sure" type language in cases like this where we want to confirm that the person wants to take an action they initiated. Would recommend that here as well. Finally, made some suggested tweaks to the buttons. I think "No, don't cancel" is clearer than "No, take me back."_

**Are you sure you want to cancel your appointment?**
If you want to reschedule, you’ll need to call us or schedule a new appointment online.
_[button 1]_ Yes, cancel my appointment
_[button 2]_ No, don’t cancel

### Status message
_**Note:** Consider adding a sentence re: how to reschedule here as well._

**You canceled this appointment.** If you want to reschedule, call us or schedule a new appointment online.

## Use Case 2
### Action screen
**Are you sure you want to cancel your request for an appointment?**
If you still need an appointment, you’ll need to call us or schedule a new appointment online.
_[button 1]_ Yes, cancel this request
_[button 2]_ No, don’t cancel

### Confirmation screen
**We’ve canceled your appointment request**
If you still need an appointment, call us or request a new appointment online.
_[button]_ Continue

## Use Case 3
### Request screen
_**Note:** Can we change “How to be seen” to “Type of visit”? “How to be seen” feels a bit awkward and unclear and it also relies on sighted language._  

### Pending appointment screen
_**Note:** Tweaks to make active voice, remove sighted language, and make the 2nd link a CTA_
**Thank you for submitting your request.** We’ll contact you to schedule the first available appointment.
_[link 1]_ Review your appointments
_[link 2]_ Request a new appointment
_[button – make sure the “r” is lowercase]_ Cancel request

### Action screen
Are you sure you want to cancel your request for an appointment?
If you still need an appointment, you’ll need to call us or schedule a new appointment online.
_[button 1]_ Yes, cancel this request
_[button 2]_ No, don’t cancel

[confirmation screen]
**We’ve canceled your appointment request**
If you still need an appointment, call us or request a new appointment online.
_[button ]_ Continue	

## Use Case 4
### Confirmation screen
_**Note:** Tweaks to make active voice, remove sighted language, and make the 2nd link a CTA_
**We’ve scheduled and confirmed your appointment.**
_[link 1]_ Review your appointments
_[link 2]_ Request a new appointment
_**Note:** Yes, if we make the cancel action available, let’s use similar messaging to use case #1 – thanks!_

**Comment by laurenernest** [comment]
Design request:
- D/T/M template or specs for modal changes

No confirmation page specs needed unless there are styling changes.

**Comment by Cieramaddox** [comment]
@JRRoof @ldelacosta @laurenernest 
These designs are approved. Here is the [Design link ](https://www.figma.com/file/d6enlZQ15NZEuJNVD64Npg/Cancelation%2FReschedule?node-id=28%3A2834)

**Comment by ldelacosta** [comment]
@Cieramaddox - one minor update on the second modal for canceling the booked appointments. If we can update the text "We've canceled your appointment" instead of showing "You canceled this appointment." If you have any questions, please let me know. Thanks!

**Comment by Cieramaddox** [comment]
@ldelacosta - Designs have been updated.

**Comment by outerpress** [comment]
@ldelacosta any more work needed on this, or can we close?

**Comment by ldelacosta** [comment]
The changes have been implemented. Thanks.
