### ISSUE TITLE
migrate CI pipelines for drupal testing

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#329]
## Description

As part of the migration of the CMS into VSP, we need to setup a testing pipeline job for the CMS repo(s). I know that currently their build artifact is a Docker image which will need to be pushed to ECR and marked that as a dependency on this ticket.

## AC

- [ ] pipeline job for CMS repo(s) (get list from CMS team) in Jenkins under the `testing/` folder
- [ ] result of pipeline job is Docker image uploaded to ECR

**Comment by ricetj** [comment]
@wyattwalter to close

**Comment by wyattwalter** [comment]
The CMS team decided to use a Drupal-specific tool rather than migrating into our Jenkins. They'll continue to use it for infra builds, but this particular task doesn't need doing.
