### ISSUE TITLE
PST-IET demo API: First-Middle-Last Name

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#32900]
# PST-IET demo API: First-Middle-Last Name

As there is a number of upstream/partners/3rd-party APIs with potentially different standards for First-Middle-Last Name Verification, there is room for a microservice API that first will test person's name against Login.gov criteria and then against all the criteria VA upstream APIs might have.

## Implementation

A production-grade demo microservice high performance Go API to check how Login.gov and all VA upstream APIs a satisfied with person's full name split and fit into the 3 standard fields:
- first_name: 
- middle_name:
- last_name:
 
## Sample dataset
- Alan A. A. Donovan
- Alan A A Donovan
- Alan AA Donovan
- Alan Donovan
- Alan A.a. Donovan
- Donovan, Alan A. A.
- Donovan, Alan A. A., 1976-
- Patrick O’Donovan

## Acceptance criteria

The application must be containerized with HTTP endpoint, a log entry per every call is produced for performance measuring purpose only with no PII data included, the validation must be good for Login.gov and all VA upstream APIs, list of which is to be determined. 
Some testing ideas might be inspired by [https://developers.login.gov/testing/](https://developers.login.gov/testing/)

**Comment by considerable** [comment]
Good to know how much of **SentryLogging** found in **vets-api/lib/saml/user_attributes/id_me.rb** and **vets-api/lib/saml/user.rb** can be used to gauge the performance of vets-api.

**Comment by ewilson-adhoc** [comment]
Moving to the icebox since this is not relevant to our current goal of splitting vets-api into microservices.
