### ISSUE TITLE
Create feature flag for New Design (without login.gov content)

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32907]
- [x] Create a feature flag for new design `login_new_design` in features.yml
- [x] Create a feature flag on the FE for new design in the `featureFlagNames.js`
- [x] Gate the new design behind the new feature flag, should not include Login.gov button

**Comment by AGarcia-Clarity** [comment]
Should be merged in the morning for Joe to test on dev & staging. Will go live tomorrow.
