### ISSUE TITLE
Access for Joseph Hall

### ISSUE THREAD

**Issue by joehall-tw** [department-of-veterans-affairs/va.gov-team#32901]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Joseph Hall

### Your Email

joe.hall@thoughtworks.com

### Name of Your Team

Team Orchid, Developer, Thoughtworks

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need access to the AWS secret manager so I can add pipeline secrets for the va-virtual-agent team to AWS.

**Comment by mydesignrocks** [comment]
@mchelen-gov please review for AWS access

**Comment by jsgarmon** [comment]
new approval group: @department-of-veterans-affairs/operations-aws-approvers

@joehall-tw : they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that your COR has added your transmittal date to the Sharepoint doc?

**Comment by joehall-tw** [comment]
I apologize for the late reply.

I went through a background check. I remember eQIP being a precursor to
that,  and I remember uploading completed files to the SharePoint site.
I'll track down my COR to verify. Is there something more formal you need
to satisfy this requirement?

Thanks.
-- Joe

**Comment by jsgarmon** [comment]
Someone in @department-of-veterans-affairs/operations-aws-approvers will need to check and verify the transmittal date. Either your COR or onboarding representative can ping Mike Chelen if everything looks good.

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by td-usds** [comment]
Reached out to VOR today

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
