### ISSUE TITLE
CIE - Training/Demo Environment

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#32910]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a non-technical person, I need a system that allows me to set up appointments for test patients and walk through the check-in process outside of our actual production system, so that I can train new hires and demonstrate how the system works. 

## Hypothesis or Bet
**If** we create a training/demo environment for end users **then** we expect wider adoption and understanding of our application. 

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
We will need a way for trainers in the field to interact with our system in a non-production environment at a large scale.
Self service
Can be used for training and demos

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by loripusey** [comment]
How it this epic different than [this ]([url](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/36829))one?
