### ISSUE TITLE
HCA Facility Info bugs

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#32912]
## Technical task 

As I was QAing my work for [task](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/25411) I noticed two small bugs located in the same file.

One of which is when you press the AdditionalInfo expandable component it also checks the check box. Probably just need to increase margin so they don't both press on same click.

![hca-facility-info-bug.gif](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/d6699b41-0877-49e5-b40b-80fc03006808)

The other one is on the review page when you go to the section that question is in the AdditionalInfo component is being shown in the review box should only be title content there. Need to use CustomReviewField that is being used in PR that is related to the ticket linked above. The CustomReviewField only uses title for the review field. 

![hca-facility-review.gif](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/5abcf517-a893-4c2d-a66b-4e468d6c0033)

## Expected Behavior

The click handler for AdditionalInfo and checkbox should be separate clicks. AdditionalInfo should not be on review page. See above gifs.

## Acceptance Criteria

- [ ] Review field for facility should only contain the field title.
- [ ] The click for AdditionalInfo and checkbox should happen on separate clicks.

**Comment by longmd** [comment]
Closing. Bugs have been sorted out.
