### ISSUE TITLE
Access for Nick Barthelemy

### ISSUE THREAD

**Issue by nbarthelemy** [department-of-veterans-affairs/va.gov-team#32916]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Nicholas Barthelemy

### Your Email

Nicholas.Barthelemy@va.gov

### Name of Your Team

AFS-Education, developer, Accenture Federal Services

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEsSXA713T2gR5YHU9iC1MkYqpTWwY4TxIIB+9RtQtDpNGAoQDjyVMtn3ibw+cQynPDQvM/0tp8vZuzGg61tx3DxSbmRf3IRlPTsswlI0rvBu4waD9p4Daae54GlJuJOx2LcJoj49mm/sIYKDp7/hav7w0PjvgP3M2GI4IweKkmJ2pLm7bOsX7Ih+3A29GGJ58pxPQ3Vxbp6YtYVKsTV3sM9lY37IgHoKqfG1NcQLfDvvQnwg2FTivbwP7JNoxpz+U4eVp29LdsnrHSRSeOu4RSX41/rK/ki+ZzuVRfKN2X9duBoevWB2CQnkYrgM3MtHgLJMTGQ4dS3hvVaue7EbbbtEx/bH+F9E4ybqTCYptdXAil6uxFxt7wRqCJOAUguQIFAV4kbBlUJT35sQ/IGzGMrPlSjb2avX5b6kWiJubg28mzVamagjNXQ3Im0r7HpVd0lkMsKcS8REZivZkokfgqyT7IrgSO9kno8OPJzQq+HP7hwMxkjfWQTk300h3xn0= nick.barthelemy@AFSMWN8UWF5TG9N

### Desired AWS Services

My team has assumed maintenance/support for Comparison Tool, Feedback tool, etc. from the current team. Please add me to the created group “afs-vfs-developers” and provide the same access as others in this group.

**Comment by mydesignrocks** [comment]
@nbarthelemy  socks granted, please verify.

**Comment by mydesignrocks** [comment]
@mchelen-gov please review for aws access

**Comment by mchelen-gov** [comment]
EQIP transmittal date confirmed, access approved 👍

**Comment by jbritt1** [comment]
First time login credentials for AWS provided to user at this time.
