### ISSUE TITLE
HLR v2 Next phase - Design Intent Feedback

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#32929]
## Issue Description
Address HLR v2 design intent feedback

---
## Tasks
- [x] Complete all outstanding design tasks/updates

## Acceptance Criteria
- [ ] New mockups and collab cycle ticket updated with comments
---

**Comment by kevinstachura** [comment]
Design intent and midpoint review feedback have been implemented and can be found in the design here:

https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6
