### ISSUE TITLE
[BE] Pre Check-in: Implement the common structure for routes and controller

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#32943]
## Description
Implement the common structure for routes and controller for pre_check_in controller.

## Tasks
- Implement the controller and routes for patient_check_in
- Add show and create methods without any implementation (return `not_implemented`)
- Add specs for the methods
- Add feature flag
- Add `authorize` to return routing_error unless the feature flag is on

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by dillo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/32943?planning-poker) with ZenHub @randomsync @kanchanasuriya
