### ISSUE TITLE
(B) Reach Out to Form Configuration Tool Devs for Assistance

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3294]
Discuss validation issues with Form Config Tool devs to figure out why the form does not validate

Document in GH the results

**Comment by micahchiang** [comment]
I _think_ this can be closed. As far as I know, @cohnjesse looked into this and determined that our issue is in fact a known issue with the form system itself.

**Comment by jason-gcio** [comment]
If it rears up, we can recreate.  Thanks @micahchiang 
cc: @cohnjesse
