### ISSUE TITLE
Replace Search Drop Down Component with Custom Search Component- New Mobile Header V2

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32940]
## Description 
_Preparing to launch New Mobile Header V2 and was originally looking to implement Search teams new search component however based on timing our team will need to replace your drop down component with a custom search component, that can be used for launch of the V2 header in support_

## Acceptance Criteria
- [ ] Replace search drop down component with custom search component in support of new VA.gov mobile header V2
- [ ] Ensure rendering in staging and validated 
- [ ] Test and validate
- [ ] Close ticket once validated 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
PR merged: https://github.com/department-of-veterans-affairs/vets-website/pull/19429 should be on staging here shortly
