### ISSUE TITLE
Get BE people on PST-IET training for Kubernetes

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#32948]
# Get BE people on PST-IET training for Kubernetes

In development, a microservice can be a Docker container exposed to the host.
In production, a microservice is a Pod on Kubernetes network, exposed or not.
Taking advantage of an instructor-led Kubernetes training is only natural.

Get BE people on PST-IET training for Kubernetes.

## Example resource for the self-paced training

[https://goteleport.com/blog/microservices-containers-kubernetes/](https://goteleport.com/blog/microservices-containers-kubernetes/)

## SuperOrbital Core Kubernetes workshop

Ask Demian Ginther  (@dginther) in #engineering-chat to be added to the group of people willing to use roughly half of their Ad Hoc continuing ed money next year for the SuperOrbital Core Kubernetes workshop [https://superorbital.io/workshops/core-kubernetes/](https://superorbital.io/workshops/core-kubernetes/)

**Comment by ewilson-adhoc** [comment]
Assigning this to Igor -- I think the training you're doing this week counts towards this. This story can be closed when your k8 training is done.
