### ISSUE TITLE
Access for Dana Harris AWS to Transcription and S3 buckets dvpuxresearchinput and dvpuxresearchoutput

### ISSUE THREAD

**Issue by Dmharris625** [department-of-veterans-affairs/va.gov-team#32958]
Please grant me access to AWS Transcription and S3 buckets dvpuxresearchinput and dvpuxresearchoutput.

Please provide your Contracting Officer's Representative (COR) name.

- Cecilia Lee

Please provide your name.

- Dana Harris 

Please Provide your email.

- dana.harris@adhocteam.us

Please provide the name of your team, your role on that team, and the name of the company you work for.

I am a member  of the UX team at VA Lighthouse APIs.  I'm researcher working for Ad Hoc LLC.

Requesting SSH key authorization?

NO.
I don’t need socks proxy, just a limited AWS account with S3 and Transcribe access in iAM. Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1603395713414900

What is your public SSH key? If you don't have a SSH Key or know how to find it click here for instructions. (Example below)
N/a (?)

Grant AWS Console access?

- YES

What AWS services do you need access to and why?

- I need to access the transcription service to transcribe interviews that I conduct with non-Veteran users, and also to S3 buckets dvpuxresearchinput and dvpuxresearchoutput

**Comment by jbritt1** [comment]
### For AWS Access:

User: Dana Harris
COR: Cecilia Lee
Approval needed: @mchelen-gov

**Comment by mchelen-gov** [comment]
@jbritt1 EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by jbritt1** [comment]
First time login credentials for AWS provided to user at this time.
