### ISSUE TITLE
Analytics KPI dashboard request for [Public Websites - Benefit Hub]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32965]
# Request a Standard KPI Dashboard

## What this form is for

Use this template to request a KPI dashboard on Domo for your product. 

We are currently only supporting standardized dashboards for Forms, Content, & Search products. If you have another VA.gov product, please reach out to the Platform Analytics & Insights team on #vfs-platform-support. Please note that these dashboards will require additional data and design discovery, and will take additional time to deliver.

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 

- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).

### Expected delivery timelines

Your KPI dashboard request will be added to the Platform Analytics & Insights team's customer support queue, and we expect tickets at the top of the queue to be pulled in every Platform Sprint Planning & Refinement (every Wednesday). We appreciate your patience.

- Once your ticket has been pulled into the Platform sprint, we expect to deliver your completed dashboard within the next 4 business days. Please use this ticket for any follow up questions.

## Instructions for the VFS team

- [X] **Please fill out [this template](https://docs.google.com/spreadsheets/d/1dIh-MVmVYCc2mZ_b_8y-cPVZB5-8RIShuOP_ng9uqAA/edit#gid=0) ([attached Excel sheet]
[KPI Dashboard Template - Benefit Hub.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7549383/KPI.Dashboard.Template.-.Benefit.Hub.xlsx)
- [X] Add your team label to follow progress
- [X] If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

## VFS-provided information

[Funnel Information](Add your product/feature's funnel information here) - Add your product/feature's funnel information here

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Build (See [internal process document](https://vfs.atlassian.net/wiki/spaces/AT/pages/1464598569/New+KPI+Dashboard+Request+Process) & [how to](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/WIP%2B-%2BHow%2Bto%2Bcreate%2Bstandardized%2Bdashboards%2Bin%2BDomo))

- [ ] Add the `VSP Analytics & Insights` Group as the dashboard owner
- [ ] Structure funnel data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Document any blocked/unavailable metrics in the Analytics team space
- [ ] Update the dashboard header, including Google Analytics links
- [ ] If any, add [implementation issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) for additional necessary implementation

2. Q&A

- [ ] Please see & complete the [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

3. Share

- [ ] Add VFS group & default group to the dashboard

  *For new VFS customers only:* 

- [ ] Schedule onboarding meeting

- [ ] Host the meeting to explain how the dashboard works

## Definition of Done

- [ ] Acceptance Criteria has been completed
  - [ ] KPI Dashboard full QA checklist completed
- [ ] Dashboard has been shared back with the VFS team

**Comment by chloedotbrown** [comment]
Thanks for submitting this, @brianalloyd! The request spreadsheet looks good. 

I'm also tagging our new PM, @michelle-dooley, so our team can discuss this in our Grooming session tomorrow. We'll keep you in the loop with updates!

**Comment by brianalloyd** [comment]
Sounds great, thanks @chloedotbrown and @michelle-dooley for the support.

**Comment by chloedotbrown** [comment]
Hi @brianalloyd – wanted to give you a quick update on the status of this dashboard. Pulling in the Benefit Hub product has massively increased the size of our data, so we're just taking a little extra time to optimize the result set and minimize performance issues. 

We'll keep you in the loop on this ticket – but if you have any questions in the meantime, feel free to reach out!

**Comment by jennaouellet** [comment]
## QA

### Highlights

Chart title | Assets | Pass / Fail
-- | -- | --
Usage trends |  [Custom segment](https://analytics.google.com/analytics/web/template?uid=7zpGkovqR3yQ8oIK8IyOJg)   |  :green_circle: PASS
Unique users | [Custom segment](https://analytics.google.com/analytics/web/template?uid=7zpGkovqR3yQ8oIK8IyOJg) |  :green_circle: PASS
Unique pageviews |  Filtered report:  [report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20211121&_u.date01=20211127&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22www.va.gov~2Fdisability~2F$%7Cwww.va.gov~2Feducation~2F$%7Cwww.va.gov~2Fcareers-employment~2F$%7Cwww.va.gov~2Fpension~2F$%7Cwww.va.gov~2Fhousing-assistance~2F$%7Cwww.va.gov~2Flife-insurance~2F$%7Cwww.va.gov~2Fburials-memorials~2F$%22,0%5D%5D&explorer-table.plotKeys=%5B%5D/) |  :green_circle: PASS
Avg. seconds to click |  (BigQuery only metric)  |  :green_circle: PASS
Avg. star ratings |  n/a  |  :green_circle: N/A
Total clicks by device | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=GROYgwyQRaCOmwF_8xA6TA) |   :green_circle: PASS

### Links

Chart title | Assets | Pass / Fail
-- | -- | --
Link engagement rate | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=6SX8ua-oRRGFSABhrohnww) | :green_circle: PASS
Avg. link clicks per session | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=6SX8ua-oRRGFSABhrohnww) | :green_circle: PASS
Total link clicks | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=6SX8ua-oRRGFSABhrohnww) | :green_circle: PASS
Links with highest engagement |  Custom report: [template](https://analytics.google.com/analytics/web/template?uid=6SX8ua-oRRGFSABhrohnww) | :green_circle: PASS

### Buttons and action links

Chart title | Assets | Pass / Fail
-- | -- | --
Buttons with highest engagement | n/a | :green_circle: N/A
Button engagement rate | n/a | :green_circle: N/A
Avg. button clicks per session | n/a | :green_circle: N/A
Total button clicks | n/a | :green_circle: N/A

### Anchor Links

Chart title | Assets | Pass / Fail
-- | -- | --
Anchor link engagement rate | [Custom segment](https://analytics.google.com/analytics/web/template?uid=urKHf17rSCC0q6emrFSiRw) |  :green_circle: PASS
Avg. anchor link clicks per session | n/a | :green_circle: PASS
Total anchor link clicks | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=Dps0O3WVT5u8FcVIDI7Wpw) | :green_circle: PASS
Anchor links with highest engagement | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=Dps0O3WVT5u8FcVIDI7Wpw) | :green_circle: PASS

### Accordions

Chart title | Assets | Pass / Fail
-- | -- | --
Accordions with highest engagement | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=39a8vl2XQUuNQlhVANq4AA)  | :green_circle: PASS
Accordion engagement rate | n/a |  :green_circle: PASS
Avg. accordion opens per session | n/a | :green_circle: PASS
Total accordion opens | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=39a8vl2XQUuNQlhVANq4AA) | :green_circle: PASS

### Misc
Chart title | Assets | Pass / Fail
-- | -- | --
Avg. scroll depth | Custom report: [template](https://analytics.google.com/analytics/web/template?uid=COhEqcRDQIiBHi6FgZE8rQ) | :green_circle: PASS
Top pages previously viewed |  Custom report: [template](https://analytics.google.com/analytics/web/template?uid=7Kpbr1WpTI-nRizKZmTASQ) |  :green_circle: PASS
Devices used to access the page |  Custom report: [template](https://analytics.google.com/analytics/web/template?uid=GROYgwyQRaCOmwF_8xA6TA)|  :green_circle: PASS

**Comment by jennaouellet** [comment]
@brianalloyd  QA has been completed and you can now view your data by filtering the product at the top of the Content KPI dashboard to Benefit Hub.

I'll close this ticket, but please let us know if you have any questions!
