### ISSUE TITLE
FE | Profile | Connected Apps | Tech Debt / Bug | content is falling outside of container

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#32963]
## What happened?
On screens smaller than 323px (e.g. iPhone 5) the connected app content is going outside of it's container.

<img src="https://user-images.githubusercontent.com/55992116/142052607-2611f220-7d19-4877-adbd-ba19fdf8d9a0.png" size="320" />

## [Specs:](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/p/0E8B5CFE-DD9A-46CE-9369-6ED367B57063/canvas)
- Device: MacBook
- Browser: Chrome emulater, iPhone 5
- Test User _(if applicable)_: 36

## Steps to Reproduce
- URL: https://staging.va.gov/profile/connected-applications
- Test User _(if applicable)_: 36

## Desired behavior
Content respects padding declaration on container

## Acceptance Criteria
- [ ] Content respects padding declaration on container on all screen sizes

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO I noticed this as part of the work I'm doing for #32074.  I also noticed that this is the only section of profile that has the CTA button on the right side of the container, which is something we changed in other sections earlier this year.

There are some other inconsistencies too:
- padding on the app container is 24px vs 32px in other parts of profile
- margin between two containers is 16px vs 48px
- the button being on the right side of the container creates some consistency issues on mobile with the size of the button (it can't expand the full width of the overall container. Instead, it expands to the full width of the column it's in
- because of the button being on the right side, I _think_ it's harder to follow the pattern we have for success/error messages in other parts of profile. I'm mocking it up like it _should_ be but I think it'll be a big PITA from a code perspective to do that.

You may want to consider evaluating with the rest of the profile team whether or not all of this should be cleaned up and if so, then this bug may be fixed with that.

**Comment by MarciMcGuireGCIO** [comment]
Thanks! I'll bring it up for discussion.

**Comment by andaleliz** [comment]
@SKasimow this is another one that was sitting around with no assignee

**Comment by SKasimow** [comment]
@jcatergovy - another one you might be able to tackle for current sprint?

cc: @adamwhitlock1

**Comment by mtcA6** [comment]
This looks good, we just need a little padding between the button and the link 

Staging: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/104c5adf-ddd0-47cd-9c18-2696a6bb54b6)

Screen grab from the design file:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/778a790d-db37-4d71-bc47-4f71ab37e195)
