### ISSUE TITLE
Documentation | Public API & Translations

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#32974]
## Story

As a PM, I'd like to understand the impact of the Public API/CMS that is under construction and how that will effect and change our ability to provide translated content for VA.gov.  

This includes:

- how we will call the new API for translated content
- what new systems or modules need to be in place to support translated content (ie: multi-lingual Drupal module)
- what is needed to automate the workflow between content creators and translators  (ie: Xliff)
- and any additional modules or code that will be needed to move to this service

## Acceptance Criteria

- architectural diagram depicting systems in play and flow of content from creation to translation to website posted to GitHub folder
- write up describing the above posted to Github folder
- sprint and team demo

**Comment by adamwhitlock1** [comment]
Diagram of flow for back-end and front-end

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/translation-recommendation-project/translation-report-artifacts/Proposed%20Future-Translation-Management-System-Workflow.pdf

Summary write up:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/translation-recommendation-project/translation-report-artifacts/Proposed-Future-Translation-Management-System.md
