### ISSUE TITLE
Staging Review [Design System Team - Additional Info Web Component]

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#32982]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [ ] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] Staging URL and staging test-user information
Link for testing: https://additional-info-bkj--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-additional-info--default
PR: https://github.com/department-of-veterans-affairs/component-library/pull/221

- [ ] Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/web-component-pilot.md
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: Carol Wong
- OCTO-DE Product lead: Ryan Thurlwell
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Brooks Johnsons
- Katy Bowman
- Natalie Hill (optional)
- Andres Rivera (optional)
- Preston Davies (optional)

### VFS Attendees

- Content and IA: 
- Accessibility: 
- QA specialists: 

## Scheduling

December 2 at 1:30pm or 2pm

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@caw310 this has been scheduled for 12/2 at 1:30pm ET

**Comment by peggygannon** [comment]
Hi, @caw310 I have no content feedback for this review. Thx!

**Comment by ddzz** [comment]
No QA feedback for this review.

**Comment by noahgelman** [comment]
What is the different between this and an accordion?

https://60f9b557105290003b387cd5-rtshxufvmf.chromatic.com/?path=/docs/components-va-accordion--default

Is it just visuals? If so, would it be better to have just 1 component and use a design option flag?

**Comment by allison0034** [comment]
No design feedback

**Comment by allison0034** [comment]
@noahgelman additional info components are similar to accordions, however they are only display 1 at a time and are typically "more info" (eg definition of a word). I believe DST is just fixing a bug for this component, the pattern and styles are currently in design system so there are no changes.

**Comment by bkjohnson** [comment]
The component already exists as a React component - we are creating a Web Component which can be used in React applications as well as static html pages. This also includes a bugfix that has to do with the left blue border.

The difference between this and an accordion is the visual styles as well as the use cases.

**Comment by noahgelman** [comment]
Accessibility Feedback
This component, while functionally the same as the [accordion component](https://60f9b557105290003b387cd5-rtshxufvmf.chromatic.com/?path=/docs/components-va-accordion--default) is missing key accessibility features that the accordion component does have. You can compare to the accordion HTML to see which `aria` attributes are missing

1. You can't open the drawer with the enter key
2. It does not announce it's open/closed state

**Comment by bkjohnson** [comment]
> 1. You can't open the drawer with the enter key

I'll make sure that Enter can be used to toggle the expanding text.

> 2. It does not announce it's open/closed state

Does `aria-expanded` need to be on the inner `<a>` instead?

![Peek 2021-12-03 14-15](https://user-images.githubusercontent.com/2008881/144680129-dac90174-b7c3-44ec-8244-031386c2831a.gif)

**Comment by noahgelman** [comment]
@bkjohnson The HTML should be the same structure as the accordion component. It should be on the inner `a` tag. Also check the accordion component for additional `aria` values that need to be added
