### ISSUE TITLE
Create S3 Bucket for Vets API Build Artifacts

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#32997]
## Description
Currently, we're testing a bundler caching solution. We'll need to host an archived directory (bz2) to significantly decrease build times across all environments while maintaining proper Docker-build hygiene.

It is planned for this file to be updated nightly via a scheduled GitHub Action Workflow. For initial testing, we'll manually upload the file.

## Background/context 
The contents of this archive are not private and will need to be publicly accessible. The contents are simply a cache of .gem files (specific to vets-api) pulled from rubygems.org.

The bucket may be used for other build artifacts but currently only a gem/bundle cache has been discovered. It would be nice if the name was generic (e.g. `vets-api-build-artificats` or `vets-api-docker-support-files`). 

---
## Tasks
- [x] Create an S3 bucket with world read.

## Acceptance Criteria 
- [x] An S3 bucket is available for Backend Tools team to upload files to.

**Comment by mydesignrocks** [comment]
created bucket and granted appropriate permissions. team was able to validate...

**Comment by jhouse-solvd** [comment]
Looks good. 

Closing.
