### ISSUE TITLE
Accessibility Research Plan

### ISSUE THREAD

**Issue by Vngpire** [department-of-veterans-affairs/va.gov-team#33012]
This is a research plan that needs to be written out before conducting research. Link to the document: [https://docs.google.com/document/d/1V80iXt1lJY01k9ahrvm4ueQKriH0pNyMx_7azBkf4IM/edit?usp=sharing]

**Comment by joeniquette** [comment]
John R. has the document for this task, received 12/6.

**Comment by APorter-Clarity** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login.gov/Sign-In_Accessibility_Research_Study.md

**Comment by nsoutouras** [comment]
Research plan was sent over.  After some back-and-forth we were informed that Olga (person reviewing the plan) was leaving the program.  As of now status is:

> Due to the research freeze and a change in roles and responsibilities. The research plan is still in review. We’ll likely have to readjust our proposed dates. We hope to have more information by COB today.
