### ISSUE TITLE
Cerner Content Rewrite from Mobile App team

### ISSUE THREAD

**Issue by msmanak** [department-of-veterans-affairs/va.gov-team#33010]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [X] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [X] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

The mobile app team has a request for change for our content on Cerner medical center alerts. I did some sleuthing around the va.gov and I found this link: https://www.va.gov/spokane-health-care/programs/my-va-health/

First screen is original MVP that we want to eliminate each parenthesis  "(Now using My VA Health)" after each location. Using the link, I thought we could do something similar language for the 2nd screen but would like your eyes on this.

**Here's my proposed new language.** VA is here to help Veterans who are using My VA health within their medical centers. To manage your health care with My VA Health providers, please go to the My VA Health website:

**Acceptance criteria:**
This ticket should aim to incorporate messaging in the 1st and/or 2nd paragraphs that:
- [ ]  Describe that the facilities listed below now use My VA Health 
- [ ]  Includes the "Go to MyVA Health link" so that it doesn't have to be a separate link at the bottom

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*
![image](https://user-images.githubusercontent.com/18237410/142239970-263ec4d0-3c10-4a74-b9e3-1804d5e87ba6.png)

**original content**: https://www.sketch.com/s/2f57b5b0-1b81-4237-a2e6-e522d5e37d11/a/v8M0wlM  | https://www.sketch.com/s/2f57b5b0-1b81-4237-a2e6-e522d5e37d11/a/Qb83Vwb
**new content**: https://www.sketch.com/s/2f57b5b0-1b81-4237-a2e6-e522d5e37d11/a/YG7rzMO

**github ticket:** https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1905

## Will this work be going through the Collaboration Cycle? 
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: 
- Estimated staging review date:
- Content and IA work needed by: 11/23/2021

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: @msmanak @drjecker  
-	FE engineer: 
-	Product/team Slack channel: # va-mobile-app

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
Discussed this in meeting and is up next in priority.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @msmanak. I worked with the authenticated experience team recently to rework the Cerner alert for better accessibility and cognition. Here's what we landed on for that. I'm not sure of the context of the original feedback, but 2 things to note: 1) I think we can make the content shorter, and 2) The alert pattern needs to accommodate the possibility of a Veteran being registered at both Cerner and non-Cerner facilities. Let me know what you think about this pattern here.

## Choose your health management portal

Your care team may now use our new My VA Health portal. Choose your portal based on the facility for your appointment:

- **For Charles P. Wylie Veterans Outpatient Clinic:** [link] Use My VA Health
- **For any other VA health facility:** [link] Use My HealtheVet

**If you have trouble accessing the portal:** Make sure to disable your pop-up blocker. If you’re prompted to sign in again, use the same account you used to sign in to VA.gov.

**Comment by msmanak** [comment]
Thanks let me share this with @drjecker

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @msmanak Is this work complete or still in progress? We currently have it in our blocked column and trying to figure out the status. Thanks!

**Comment by drjecker** [comment]
Hi @RLHecht this is complete so I will close the issue. Thank you!
