### ISSUE TITLE
New VA.gov header V2 AUTH styling fixes

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33027]
## Issue Description
_Since the launch of VA.gov in late 2018, the site has featured one responsive Global header element that was not optimized for Mobile view. As a result, for our growing base of Mobile users._

[Sketch Files](https://www.sketch.com/s/63193c20-04fc-4d4f-8b54-abf698c48636/a/Vr8Zzrw)

_The proposed solution: A mobile-only optimized header that streamlines the size of the header by utilizing the "hamburger menu." More details in this [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/product-outline.md)._

## Front end tasks
- Update "auth" styling and ensure rendering same as unauth experience
- Test and ensure "auth" is working as desired 

## Acceptance Criteria
- [ ] Auth experience for V2 header styling and rendering is tested and validated to match "unauth" experience

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19453

**Comment by kelsonic** [comment]
PR merged
