### ISSUE TITLE
Staging/Prod Env Prep

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#33028]
## Technical Task

As we get ready for launch we need to have staging environment working for QA with as little mocked data as possible so we will know if something breaks or is fixed. We also need UAT testing on Friday Dec 3rd so we need to have production ready and configured for all external systems.

## Expected Behavior

Staging environment should use with all whitelisted users with as little mock data as possible.

## Acceptance Criteria

- [ ] Staging environment works with all staging users
- [ ] Prod is working and connected and ready for UAT
- [ ] As little mock data as possible is being used

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/10353) where Prod URL and key are being configured to the prod env level.

**Comment by LinnJS** [comment]
Prod configuration with URL and API key is merged as of now.

**Comment by denisecoveyduc** [comment]
For tracking purposes adding a note that this issue did roll over from Sprint 61 to Sprint 62 due to SSH related details as well as the need to log data to get back to LETT which took a while to get access.

**Comment by denisecoveyduc** [comment]
This will roll over into Sprint 63 due to higher priority MCP fixes.
