### ISSUE TITLE
Update megamenu item label - "VA plans, budget, finances, and performance"

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#33022]
# Quick context

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/6b573ce1-a702-4e94-bdc9-27843cb90a79)

There is a request to change the name of “VA plans, budget, and performance” link to “VA plans, budget, finances, and performance”.

## Acceptance Criteria

- [x] Change the name of “VA plans, budget, and performance” link to “VA plans, budget, finances, and performance” in the megamenu.
- [x] Notify Josh Tuscher (Send email on 11/17 @12:15)

**Comment by kelsonic** [comment]
PR merged, will go out with the daily deploy tomorrow

**Comment by brianalloyd** [comment]
Action completed, closing ticket in support.
