### ISSUE TITLE
Conduct UAT (Dep Ver)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33020]
5 sessions - already scheduled

**Comment by candy-gcio** [comment]
Of the 5 new sessions, we had 4 no shows and one where the participant could not get logged into their account. With the new information from BGS on the CMP/diaryentry data, we are going to hold off on rescheduling these participants.

**Comment by candy-gcio** [comment]
[session notes](https://governmentcio-my.sharepoint.com/:x:/g/personal/candy_clark_gcio_com/ETECGnNSxJNIs7yLhv40P6AB_a5ifp2nvlrbY0Yr2tN_qA?e=aBAjRG)
