### ISSUE TITLE
[10-10CG] Tracker for CARMA MuleSoft Changes

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#33034]
This issue is for collecting info received from the CARMA team relating to their transition to MuleSoft for 10-10CG form submissions. 

Igor Khurgin: igor.khurgin@salesforce.com
- Dev implementing MuleSoft

Jubilee Miremba: jmiremba@salesforce.com
- Implemented mock server

Nov 19: Mock MS instance available for testing (IK). Probably sooner.

**Comment by jchilders** [comment]
[VA.GOV-1010CG.postman_collection.json.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/7557794/VA.GOV-1010CG.postman_collection.json.zip) - Postman collection for testing MuleSoft 10-10CG endpoints. Endpoints are currently static.

**Comment by jchilders** [comment]
MuleSoft hosts:

```
dev.vapi.va.gov - dev
test.vapi.va.gov - QA
stage.vapi.va.gov - stage
vapi.va.gov - prod
```

**Comment by SKasimow** [comment]
@jchilder is this being used for tracking anything or can it be closed?

**Comment by RudyOnRails** [comment]
Transferred this info to the epic so we can close...
