### ISSUE TITLE
Clarify ownership of the vets-json-schema repository and update permissions and codeowner information

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33037]
## Details
Ownership of the [vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema) repo is unclear and different teams are listed as the owner(s) in different locations.
- This [spreadsheet](https://docs.google.com/spreadsheets/d/1k_zjWoNx0KxPRMOqqMUdZ4fQblz2gd_lQAWW-ztnm44/edit#gid=2031012343), which is being used by some to determine which team should respond to support requests, lists the Backend Tools team as the owner (it previously listed the Backend Tools team as the owner in one tab and the Design System team in another tab, but this was recently changed so that the two tabs match).
- The [backend-review-group](https://github.com/orgs/department-of-veterans-affairs/teams/backend-review-group) and the [frontend-review-group](https://github.com/orgs/department-of-veterans-affairs/teams/frontend-review-group) are listed as codeowners on the repo. Neither [vsp-design-system-fe](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-design-system-fe) or [vsp-design-system-team](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-design-system-team) have ever been codeowners on this repo.
- The backend-review-group and the frontend-review-group both have write permissions for this repo. Neither the vsp-design-system-fe or the vsp-design-system-team have any permissions for this repo.

## Discussion
Relevant Slack threads:
- [Support request where spreadsheet was initially referenced](https://dsva.slack.com/archives/CBU0KDSB1/p1636054236313900)
- [Discussion between @k80bowman and @ericboehs (and other members of the Backend Tools team) about who should own vets-json-schema](https://dsva.slack.com/archives/CQHBJ5U06/p1636120422072500)
- [Question from @ericboehs about taking ownership of vets-json-schema](https://dsva.slack.com/archives/CJRQ85PQB/p1637081191208500)

@f1337 has [asserted](https://dsva.slack.com/archives/CJRQ85PQB/p1637158924233200?thread_ts=1637081191.208500&cid=CJRQ85PQB) that the repo should be co-owned by the Backend Tools team, the Frontend Tools team, and the Design System team.

@k80bowman has pointed out that, since the Design System team has never had any involvement with this repo, they should not own it, or at least not own it alone.

## Action items
- [ ] Determine ownership of the vets-json-schema repo
- [ ] Update permissions, codeowners, and repo README accordingly

**Comment by micahchiang** [comment]
@laineymajor - Yes, you can transfer ownership of this ticket to our team (pst-forms-library). I think our team should co-own this repository alongside the Backend Tools team, the Frontend Tools team. The Design system team doesn't need to have ownership here. @k80bowman let me know if you agree.

**Comment by k80bowman** [comment]
@micahchiang this sounds appropriate to me.

**Comment by micahchiang** [comment]
@laineymajor - I've created a [PR into vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/697) to add the forms library team to that repo as a codeowner.
