### ISSUE TITLE
Document and Test Xliff on Drupal Instance

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#33052]
## Story

As part our effort to research and understand the work that will be needed to add multi-lingual modules to Drupal, we'd like to document and test an automated workflow using Xliff.

>XLIFF is an XML-based format used to standardize the data transfers between systems. Also, it's one of the most common formats used for the localization process and by CAT Tools. This special format enables translators to concentrate on the text to be translated, without worrying about text layout. Xliff communicates which parts of a file need to be translated and how.

> Basically, content that needs to be translated is extracted from the original text and written to a XLIFF file, while the original document's structure is kept in a 'skeleton file'. The translator doesn't get any information regarding the original file's structure. As soon as a XLIFF document is translated and merged back into the skeleton file, you end up with a fully structured translation of your original content.

## Acceptance Criteria

- [x] Test exporting the Covid-19 Vaccine page from the Drupal instance and then import the "translated" version of the page.
- [x] Demo and document to C+L Github dev folder

**Comment by adamwhitlock1** [comment]
Summary of usage and a demo walkthrough is located here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content-localization/development/translation-mgmt/drupal
