### ISSUE TITLE
Create Covid-19 Booster Page in Drupal Instance

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#33055]
## Story

As a PM, I'd like to test and validate our ability to create and view  translated content in the Drupal test instance using the multi-lingual module.

## Acceptance Criteria

- [ ] Re-create and demo the translated Covid-19 Booster page in the Drupal test instance and document on the  C+L Github folder.

**Comment by adamwhitlock1** [comment]
Since I was able to actually use an instance of the current VA CMS with Covid content, this ticket can be marked as complete.
