### ISSUE TITLE
Missing footers on OPRM.VA.GOV

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#33067]
Story: As a Veteran viewing the following pages: 
Community Care (https://www.va.gov/COMMUNITYCARE/programs/veterans/index.asp)
Patient Rights (https://www.va.gov/health/rights/patientrights.asp)
Privacy Service (https://www.oprm.va.gov/)
I expect to see a footer injected. 

There is currently a bug that is not injecting the footer

Acceptance Criteria: Footer renders as expected of the following pages 

Community Care (https://www.va.gov/COMMUNITYCARE/programs/veterans/index.asp)
Patient Rights (https://www.va.gov/health/rights/patientrights.asp)
Privacy Service (https://www.oprm.va.gov/)

**Comment by leahkeeler** [comment]
Platform request opened https://dsva.slack.com/archives/CBU0KDSB1/p1637245641314500

**Comment by kelsonic** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/19461) and validated on staging: https://staging.va.gov/health/?targetEnvironment=vagovstaging Will go out with daily deploy today
