### ISSUE TITLE
Confirm local workflow for testing proxy rewrite is working

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#33074]
[Slack context](https://dsva.slack.com/archives/CBU0KDSB1/p1637245641314500)

Current documentation: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/proxy-rewrite/README.md

To Do:
- See if this documentation is accurate
- If it isn't update it or fix the local workflow

**Comment by CBonade** [comment]
Closing as stale

**Comment by timwright12** [comment]
Can this be reopened? It's an important testing feature for teamsites
