### ISSUE TITLE
A11y fixes for search in header v2

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#33080]
Story: As a Veteran who utilizes search on VA.gov I expect to see consistent styling

To-do: 

- [ ] The search button icon needs a sr-only "Search" span nested within it
- [ ] Remove the aria-label "enter a keyword," the label "Search" won't read out if there is an aria-label
- [ ] Add a div with a role="search" around the form element

![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/05e86826-f477-4198-8b1b-2102a96e1a4e)

AC: The search component displays "Search" as expected in the search component after the code fix has been applied

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19471

**Comment by kelsonic** [comment]
PR merged, will go out with daily tomorrow
