### ISSUE TITLE
[UX] Research/Design Emergency Contact 

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33088]
## Description
As a veteran I need a way to update my emergency contact during pre-check-in so that I can ensure the correct person is on file for contacting in case of an emergency.

Read only

1. Where does it belong in the flow?
2. Consider 'same as nok' check box functionality

## Tasks
- [x] Create Wireframe

## Acceptance Criteria
- [x] Wireframe link: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/nRzZkwp

**Comment by zach-park** [comment]
- Check what type of data is coming in (i.e., emergency contact data available). - Check with Stephen --> or Shane
- Be mindful of desktop (mobile responsive) experience
- Explore options (and discuss and decide for user test if necessary) in where the UI flow would appear
   Earlier in pre check in flow vs profile 'mobile responsive' version
   Ref: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/kav0oQg
   Ref: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/L0dzEE3
   Ref: https://staging.va.gov/profile/contact-information

**Comment by zach-park** [comment]
Hi @stephenBarrs, can I ask what type of data is coming in for emergency contact so that it can be displayed during the pre-check-in? If not, could you kindly let me know whom I could follow up with the question (Kristen mentioned that Shane Elliot may be the next person to ask)? Thank you! (Cc: @kristenmcconnell )

**Comment by zach-park** [comment]
Added the draft wireframe for review. Cc: @kristenmcconnell @niradatta1 @ytsaoca @julieadair1 @jparker0425
