### ISSUE TITLE
Update "more info component" location on page for 10-10EZ Pension question

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#33087]
The 10-10EZ Pension was recently given its own page. The more info component needs to be consistently placed under the question.

## Expected Behavior
The more info component is under the question

## Acceptance Criteria
- [x] FE is updated to design
- [x] Functionality is tested
- [x] Designer signs off RI
- [x] Update is in prod

## Design mocks

# Current problem (old)
![Screen Shot 2021-11-18 at 10.56.51 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/91ff696a-a866-4ce4-9df5-c1aa76fd6682)

# Correct design
![Pension design.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/72124658-7857-46a7-8bfd-9659e750c50a)

**Comment by LinnJS** [comment]
About to merge [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19468) to fix this issue.

**Comment by LinnJS** [comment]
Issue is merged and should be in staging in 30mins or so.

**Comment by Dene-human** [comment]
Confirmed in prod
