### ISSUE TITLE
Filter & Transform media-video content

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#3308]
## Problem Statement
Our tome-sync data doesn't match up with our templates, and we need to follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835) to ensure that the data will be compatible with our current templates.

## Goal
Content from `media-video` entities match their corresponding entities from `pages.json`

**Comment by ncksllvn** [comment]
Moving to backlog, because it appears we're blocked on this until we have a replacement for the Drupal GraphQL `derivative` function, which is used to create links to scaled images.

**Comment by cvalarida** [comment]
cc @ElijahLynn

**Comment by drorva** [comment]
@cvalarida close? If not, apply cms-transfomer label.

**Comment by jhonnyoddball** [comment]
This has been resolved!
