### ISSUE TITLE
[BE] SPIKE - Determine the best way to add metrics from CHIP and LoROTA services in to DataDog

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#33082]
## Description
Currently, platform supports sending metrics through vets-api code using StatsD to DataDog (link to current dashboard: https://app.datadoghq.com/dashboard/tmn-f5f-e9r/check-in-vets-api). This spike is to investigate the best way to add CHIP and LoROTA metrics to DataDog so that we can see consolidated data in a single dashboard.

## Acceptance Criteria

- [ ] Documentation on how to add the metrics from CHIP and LoROTA to DataDog
- [ ] Implementation Stories created

**Comment by julieadair1** [comment]
@randomsync , @jparker0425 - is this ticket related to pre-check-in?

**Comment by randomsync** [comment]
The starting point for this spike will be to have a conversation with relevant folks on the approach.

**Comment by dillo** [comment]
This ticket is no longer relevant since the CHIP team will be integrating CHIP and LoROTA metrics/logs with their own Datadog account. Closing.
