### ISSUE TITLE
[TUD] Set up in EKS staging environment 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33093]
## Description
The Testing Tools team (TT) needs to set up the Test User Dashboard (TUD) in the EKS staging environment. In addition to the deployment pipeline, additional network and infrastructure configuration may be required. The process should be documented to make this more self-service for platform crew teams in the future. 

## Background/context 

- [TT MVP TUD initiative](https://docs.google.com/document/d/1dmLagteKWUiqTH3zux3a6N3oY4dF0i8pd_oDkJx_9Yc/edit) 
- The app is already being deployed with ArgoCD to EKS in dev. 
- TT will be able to make some of the required configuration changes. 
- Ops can approve PRs to help them get the app deployed. 
- [Recent Slack conversation](https://dsva.slack.com/archives/CJYRZK2HH/p1637250674113800) w/ TT

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Deploy TUD to staging cluster
- [x] etc, TBD

## Acceptance Criteria 
- [x] TUD can be accessed via http://tud-staging.vfs.va.gov

**Comment by jhouse-solvd** [comment]
Need to link up conversations or artifacts that record the decision for hosting this in staging, and later moving to a "platform-tools" URL.

**Comment by jbritt1** [comment]
For the task of configuring reverse proxy for this new endpoint, do we actually want staging.va.gov/tud or are we to follow the existing pattern that has already been used in two other environments (dev and utility) leveraging the *.vfs.va.gov domain? (See https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-identity/test-user-dashboard/utility/ingress.yaml#L15 && https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-identity/test-user-dashboard/dev/ingress.yaml#L15

**Comment by jbritt1** [comment]
I believe all this will really take is:
 - Copy/paste existing dev configs into new staging directory (swap out anything `dev` for `staging`)
 - Setup new project for TUD on staging cluster in ArgoCD
 - Profit

**Comment by jbritt1** [comment]
We did a mob session today and have deployed TUD to staging EKS cluster. Only piece left at this time is to create a doc for this process. @mleclerc00 and i have plans to collab on this next week and we will do an open invitation to the rest of the team for any that may want to also contribute.

**Comment by mchelen-gov** [comment]
Where is the initiative for TUD rollout?

**Comment by pjhill** [comment]
[Here](https://app.zenhub.com/workspaces/planning-board-testing-tools-team-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/13714)'s the TUD MVP Initiative Epic.

The TUD MVP product outline and release plan are stored in Confluence [here](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1982791702/Test+User+Dashboard).

The staging hosting solution for TUD was requested as a result of the GitHub OAuth solution we created. That ticket is [here](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/31083). We recently punted that to post-MVP, but if the progress here is indicative of a fix to our hosting blocker then we may want to move that back into the MVP. I'm not sure.

**Comment by jhouse-solvd** [comment]
@pjhill - Do you have what you need from the Operations team at this time? ie is TUD up and running per your team's requirements?

**Comment by pjhill** [comment]
> @pjhill - Do you have what you need from the Operations team at this time? ie is TUD up and running per your team's requirements?

Hey Jesse, I think it's safe to say this ticket can be completed. Unfortunately, switching out the hosting solution for EKS doesn't appear to have solved our issue with the GitHub OAuth cookie becoming invalid. However, this effort and the ops office hours combined to spur a different solution to our issue which we are currently investigating.  For the time being, let's keep the EKS hosting and the legacy hosting of TUD going, but in the next few sprints we will probably end up decommissioning the EKS hosting solution created as a result of this ticket.

Thanks to you and Jeremy and the whole team for your effort and help on this!

**Comment by jhouse-solvd** [comment]
@pjhill - Thanks so much for the additional info and context. Too bad that didn't address the GitHub OAuth issue, but glad we could support testing that approach. 

Please do create an additional ticket when you are ready to decommission TUD in EKS. 

Use the Ops issue template and assign it to mee, or drop it in the vsp-operations channel in DSVA Slack and mention me. From there, we'll get it in the backlog and make sure to do the needful.

**Comment by jhouse-solvd** [comment]
This is done. Closing.
