### ISSUE TITLE
Urgent vs. emergency care R&S article

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#33102]
# User story

As VHA, we want people to know that they can get care for many minor illnesses and injuries at urgent care locations faster than in an emergency room.

**Note:** This request is linked to the urgent vs. emergency care campaign landing page and will serve as the destination for the CLP main call to action link.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I've worked with VHA to create this R&S article: http://preview-prod.vfs.va.gov/preview?nodeId=37196

Could you please do a copy edit review and also change the CTA link URLs to go to filtered views of urgent care locations and emergency care locations, respectively? Thank you!

cc @davidconlon  @brianalloyd for awareness since this is linked to the CLP

**Comment by RLHecht** [comment]
This page is reviewed and published. Moving to validate and will close once live.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Published this and validate on live Site. Closing issue. Thanks!
