### ISSUE TITLE
[Initiative] VAOS appointment enhancements to support MHV on VA.gov

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33100]
## Background
VAOS is partnering with the Digital Health Modernization (Health Apartment) team to move the appointment section of the My HealtheVet (MHV) website into a 'My HealtheVet'-branded section of VA.gov.

Currently, both MHV and VAOS display an appointments list and appointment details. The first part of this Health Apartment effort is to consolidate the appointment experience from MHV into VAOS on VA.gov.

Additional information on the larger Health Apartment project can be found in their [Onboarding Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/onboarding.md#health-apartment-team-onboarding-guide).

**Comment by ldelacosta** [comment]
We have a new epic to handle any work moving to MHV on VA.gov - see Epic MHV on VA.gov Unified Appointment Experience Phase 2B - Appointments FE #57209. cc: @JRRoof
