### ISSUE TITLE
Consolidate Domo BQ service accounts

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#33113]
We have 3 separate BigQuery Service Account Domo connectors that are attached to user accounts and not the shared Platform Analytics & Insights account.

![image](https://user-images.githubusercontent.com/62304138/142660490-f0a44fbc-f116-4bc5-bd8d-86ca62ce4e18.png)

We should...

- [x] Investigate if a group can be used for Domo dataset ownership
- [x] Create a new Domo <> BQ service account connector owned by the shared Platform Analytics & Insights account.  This can be an existing key or a new one.
- [x] Logged in as the shared account, take ownership of each Google Analytics BQ dataset and re-configure to use new connector.  You can hover over the "Datasets" [value to see what is connected to each account](https://va-gov.domo.com/datacenter/accounts).
- [x] Remove old service account connectors once they are detached from all GA datasets
- [x] Remove all JSON keys from Domo dashboarding service account in GCP except for the one we are now using

**Comment by jonathan-epstein13** [comment]
@jonathan-epstein13 is willing to assist on this ticket.

**Comment by bsmartin-ep** [comment]
@obrienjulie -

Looks like we can bulk reassign datasets to a new owner....

https://domohelp.domo.com/hc/en-us/articles/360042926054-Managing-User-Accounts-for-Connectors#:~:text=To%20transfer%20ownership%20of%20DataSets%20associated%20with%20a%20user%2C

**Comment by obrienjulie** [comment]
I have the new json key for the new service account for anyone that needs it.   I am not allowed to disconnect the existing BQ accounts as I'm not the account owner.
