### ISSUE TITLE
Adding [Ero Gray] to DSVA Slack

### ISSUE THREAD

**Issue by FredAllen6608** [department-of-veterans-affairs/va.gov-team#33118]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

User needs access to assist with the transition of Caseflow to Booz Allen

Are you requesting to add an individual as a:

- Please add [_erogray@navapbc.com_] as a single-channel guest to [_caseflow-transition-support_].

- What channel(s) do they need to be added to?
caseflow-transition-support

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
Project Management assistance for the Caseflow transition

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
