### ISSUE TITLE
AWS Staging:  VAOS Direct Scheduling and Requests Not Working When Locations Are Enabled in VATS

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#33115]
Steps to Recreate:
 In VATS for Cheyenne (983)  and Fort Collins (983GC) for all types of care (except Podiatry as Podiatry is not in VATS) set both direct scheduling and requests, set to YES Any.  This will make it so that the veteran should be able to select Cheyenne or Fort Collins in VAOS for any type of care selected. 
Log into VAOS (Judy Morrison).  Select to start scheduling, select type of care.
Expected Response:  User is prompted to select location
Actual Response:  System displays message:  We couldn’t find a VA facility
Here is the endpoint and  the response body.
https://staging-api.va.gov/vaos/v2/scheduling/configurations?facility_ids[]=983&facility_ids[]=984&facility_ids[]=983QE&facility_ids[]=983QA&facility_ids[]=983GD&facility_ids[]=983GC&facility_ids[]=983GB&facility_ids[]=984GF&facility_ids[]=984GC&facility_ids[]=984GB&facility_ids[]=984GD&facility_ids[]=984GA
"id": "983",
  {
            "id": "211",
            "name": "Amputation Services",
            "stopCodes": [
              {
                "primary": "211"
              }
            ],
            "direct": {
              "patientHistoryRequired": false,
              "patientHistoryDuration": 0,
              "canCancel": true,
              "enabled": true
            },
            "request": {
              "patientHistoryRequired": false,
              "patientHistoryDuration": 365,
              "submittedRequestLimit": 2,
              "enterpriseSubmittedRequestLimit": 2,
              "enabled": true
            }
          },
983GC
 {
            "id": "211",
            "name": "Amputation Services",
            "stopCodes": [
              {
                "primary": "211"
              }
            ],
            "direct": {
              "patientHistoryRequired": false,
              "patientHistoryDuration": 0,
              "canCancel": true,
              "enabled": true
            },
            "request": {
              "patientHistoryRequired": false,
              "patientHistoryDuration": 1095,
              "submittedRequestLimit": 1,
              "enterpriseSubmittedRequestLimit": 2,
              "enabled": true
            }
          },
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/f353dcac-e502-431f-b21d-787754696f37)

**Comment by grossb1** [comment]
Here is the associated VAOSR ticket:
https://issues.mobilehealth.va.gov/browse/VAOSR-2665
