### ISSUE TITLE
Redirect Request: Home loans "How to apply page"

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#33128]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: TBD

### Redirects 
Current URL  |  Redirect to | Notes
---  |  --- | ---
www.va.gov/housing-assistance/home-loans/how-to-apply/ | www.va.gov/housing-assistance/home-loans/how-to-request-coe/ | ---
www.benefits.va.gov/homeloans/purchaseco_certificate.asp  | www.va.gov/housing-assistance/home-loans/how-to-request-coe/ | Update the existing redirect on this page
www.vets.gov/housing-assistance/home-loans/apply-for-certificate-of-eligibility/  | www.va.gov/housing-assistance/home-loans/how-to-request-coe/ | Update the existing redirect on this page

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
This redirect can be done at any time, but determined to wait until H1 is updated on page. 

cc @bethpottsVADEPO

**Comment by mnorthuis** [comment]
H1 change will be done by 3/15 by @RLHecht 

@brianalloyd @LindaLi123 please coordinate with the drupal URL change for this redirect.

**Comment by RLHecht** [comment]
@LindaLi123 Sitewide Content can change the URL in Drupal for you. We will be changing the H1 today and can let you know when it's live. I think your redirect will happen before we change the URL in Drupal, but I'll have @mnorthuis confirm.
