### ISSUE TITLE
Draft Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33132]
## Background
While we are request a midpoint review, we should start the research plan and conversation guide for the representative work so that when its time to do those usability session and test what we have built we are ready to move forward.

## Tasks
- [x] Start a draft of the research plan and conversation guide, if applicable for the representative work.

## Acceptance Criteria
- [x] the Research plan (and conversation guide, if applicable) has been started

**Comment by jason-gcio** [comment]
sprint 62

**Comment by candy-gcio** [comment]
These are a little more detailed than rough draft, but still have placeholders for scope to change from just view to view + search + appoint (especially the conversation guide).

- [Research Plan DRAFT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/usability-testing/view-rep-research-plan.md)
- [Conversation Guide OUTLINE DRAFT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/usability-testing/view-rep-convo-guide.md)
