### ISSUE TITLE
"Preferred providers only" filter option not working

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#33143]
## What happened?
Unable to check/uncheck the checkbox "Preferred providers only" under VET TEC providers filter option in order to filter properly.
See screenshot: 
<img width="1083" alt="Checkbox" src="https://user-images.githubusercontent.com/86266024/142906540-c4ee6eae-9d7b-44f2-8452-d6bb9449443a.png">

## Steps to Reproduce
- Navigate to URL: https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=name&name=LEARN%20ACADEMY&excludeSchools=true&excludeEmployers=true
- Inside the "Filter your results" accordion, select the checkbox "Preferred providers only" under "VET TEC providers" filter option
- Click on "update results" button located at the bottom of the accordion

## Desired behavior
- The checkbox "Preferred providers only" should be checked
- The Search results page will return only VET TEC providers with the option "Preferred providers only" 

## Acceptance Criteria

- [ ] When "Preferred providers only" under "VET TEC providers" is checked, **ONLY** VET TEC preferred providers will be returned 
- [ ] When "Preferred providers only" under "VET TEC providers" is unchecked, **ALL** VET TEC providers will be returned

**Comment by dan-brooking** [comment]
@hallihocine @mrblanco1 So this filter is no checkable and uncheckable. I think there might be a bigger issue where filters overall are not working... but I can't tell. If so, that would definitely be much bigger scope and I imagine we'd want another ticket for that.

But right now, this option has been updated to be selectable.

**Comment by mrblanco1** [comment]
@ERRonat0609 - Can you please run a couple of test cases to make sure the filter is working? We think it does not work properly as it returns Vet Tec institutions that are not Preferred.

**Comment by hallihocine** [comment]
Ticket has been validated in staging
- Without using the filter "Preferred providers only": it returns all VET TEC institutions 
<img width="643" alt="Before filter" src="https://user-images.githubusercontent.com/86266024/145460471-d621eab8-773c-47a1-9356-43f193da5d2a.png">
- Using the filter "Preferred provider only": it returns only preferred VET TEC institutions 
<img width="855" alt="After filter" src="https://user-images.githubusercontent.com/86266024/145461143-d6f4a74e-67b3-4fd5-9f22-4de7f7c34196.png">

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2676&group_by=cases:section_id&group_order=asc&group_id=3070
- Test Script/Steps:
[Preferred providersonly-filter option not working .xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7687866/Preferred.providersonly-filter.option.not.working.xlsx)

**Comment by ERRonat0609** [comment]
Closed - approved UAT by Joe Preisser on 12/13.
