### ISSUE TITLE
Analytics Implementation or QA Support for [Public Websites - VA Mobile Header V2]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33145]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Public Websites Team - New VA.gov Mobile Header V2]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - [11/23/2021]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
#### Requested Items 
- We're looking to gain insights for the below items marked as "NONE" that was worked in ticket [32528](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32528). Also looking to ensure all the below are tracking on the New Mobile Header component and not the legacy header component. 
-----

Interaction|Is it currently tracked?
----|-----
Toggling expanded/collapsed state for official govt website accordion|**el:** int-accordion-expand<br>**ea:** Accordion - Expand - (not set) - Here’s how you know - (not set) - (not set)
Clicking VCL|**el:** nav-crisis-header<br>**ea:** Navigation - Crisis Modal Clicked - Header
Clicking Logo|None (no tracking on non-mobile either)
Clicking Sign in|**el:** int-modal-show<br>**ea:** Modal - Click - (not set) - (not set) - (not set) - (not set) - Sign in 
Expanding/collapsing Menu|None/None
Expanding/collapsing menu item level 1s| **el:** nav-header-top-level<br>**ea:** Navigation - Header - Open Top Level - <text>
Clicking menu item level 2s| **el:** nav-header-second-level<br>**ea:** Navigation - Header - Open Second Level - Health care
Clicking Back to menu button|None

(Note - we may have legacy events for some of these like the `^nav-header-logo` I see in `Navigation Action - Lookup Table`.  And maybe `^nav-header-link$` for the Back to menu button.)
    
### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by laurensimpson14** [comment]
Hello @brianalloyd 👋 I hope you had a great Thanksgiving 🦃 

>(Note - we may have legacy events for some of these like the ^nav-header-logo I see in Navigation Action - Lookup Table. And maybe ^nav-header-link$ for the Back to menu button.)

I checked to see if there are any legacy events getting pushed in the dataLayer since these are in the lookup table in Google Tag Manager, however I don't see any custom events getting passed when the logo is clicked. 

This means that all three of the `None` items above that we want tracking for need to have a custom event pushed in the dataLayer for us to implement tracking. Below are the dev specs for each: 

| Interaction | Dev Spec | 
| -- | -- |
| Clicking Logo | 'event': 'nav-header-logo' |
| Expanding/collapsing Menu | 'event': 'nav-header-menu-expand` |
| Clicking Back to menu button |  'event': 'nav-header-back-to-menu` |

I'll move this ticket to "Standby - VFS Developers" while those dev specs are getting implemented. Once complete please let me know and I can implement the tracking & QA! 🙂

**Comment by brianalloyd** [comment]
@kelsonic looping you into this ticket, I know we implemented some insight interactions for the new mobile header, could you please review the above and ensure we've got these  implemented in support of tracking.  Please ping @laurensimpson14 once ready and she'll work the tracking & QA actions.

**Comment by kelsonic** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19539

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy tomorrow

**Comment by brianalloyd** [comment]
@laurensimpson14 this should be ready for Tracking and QA actions.  Please advise, looking to get tracking on this soonest so we can determine next step in our release plan.  Once tracking is a available can you link me into the data for review.  TIA.

**Comment by laurensimpson14** [comment]
@kelsonic When I click the logo (and the menu & back buttons) I don't see those events being passed in the dataLayer. For example, below is a screenshot of what I see in the dL when I click on the logo: 
![image](https://user-images.githubusercontent.com/80417436/144137116-95d8d6f2-7c10-4d23-9b4c-f18b8cb6d9c0.png)

The event `'event': 'nav-header-logo'` isn't in the dL. 

I'm not sure why that would be. Do you know why this may be happening?

**Comment by kelsonic** [comment]
@laurensimpson14 are you sure you're looking at header v2?

**Comment by brianalloyd** [comment]
@laurensimpson14 could you verify the above, wanting to get some tracking on this ASAP based on its recent launch.  Thanks for the support.

**Comment by laurensimpson14** [comment]
Yes - I just pinged Kelson and we got it figured out. My account is now able to see it. Hold tight for QA (15 min max).

**Comment by laurensimpson14** [comment]
| Interaction | Interaction Screenshot | Interaction QA Screenshot | QA Status |
| -- | -- | -- | -- |
| Clicking Logo |![image](https://user-images.githubusercontent.com/80417436/144315655-8be6acd2-04bb-4b69-b4c4-a22da68143a4.png)| ![image](https://user-images.githubusercontent.com/80417436/144315735-e267007c-e524-4f6f-a6f0-160d55e439be.png) | 🟢 Tracking Correctly |
| Expanding/collapsing Menu | ![image](https://user-images.githubusercontent.com/80417436/144315824-fe5c40be-dd73-49cc-967a-3cffaae5cd6f.png) |![image](https://user-images.githubusercontent.com/80417436/144316107-d8644f0e-790b-4e0c-93e2-b921b2285bd3.png)| 🟢 Tracking Correctly |
| Clicking Back to menu button | ![image](https://user-images.githubusercontent.com/80417436/144316843-d9cda22f-938c-4e1b-ba37-5408cd088525.png)| ![image](https://user-images.githubusercontent.com/80417436/144316900-b9a5a01b-834c-4c31-951b-7e9fdd4dfaf4.png)| 🟢 Tracking Correctly |

@brianalloyd All tagging has been implemented and QA completed. These events are now tracking.

**Comment by brianalloyd** [comment]
@laurensimpson14 could you pass me a GA link to the data?  TIA.

**Comment by laurensimpson14** [comment]
Yes!

Here is a [link to the data in production](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20211201&_u.date01=20211201&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Navigation%20-%20Header%20-%20Logo%7CNavigation%20-%20Header%20-%20Menu%20-%20Expand%7CNavigation%20-%20Header%20-%20Back%20to%20Menu%22,0%5D%5D/), however it looks like no users in production have triggered the `Navigation - Header - Back to Menu` event yet. 

Here is a [link to the data in staging](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20211201&_u.date01=20211201&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Navigation%20-%20Header%20-%20Logo%7CNavigation%20-%20Header%20-%20Menu%20-%20Expand%7CNavigation%20-%20Header%20-%20Back%20to%20Menu%22,0%5D%5D/). Here you can see that internal users have triggered all three events in staging.va.gov.
