### ISSUE TITLE
[UX] Add/Edit Emergency Contact

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33148]
## Use Cases
1.  As a veteran I need to be able to add an emergency contact when I am pre-checking in so that if anything happens to me the VA will know who to contact. 
2.  As a veteran I need to be able to edit my emergency contact when I am pre-checking in so that the VA contacts the correct person in case of an emergency. 

Tasks
- [x] Design wireframes - UX can be worked on.  
- [x] The whole pattern of editing profile information in a workflow needs to be reviewed design system team (including accessibility).
- [x] Sync with profile on mailing/home address syncing pattern (since they are working on this, it is out of scope for us for this ticket)

Acceptance Criteria
- [x] Post to Sketch Cloud

**Comment by kristenmcconnell** [comment]
[Information on a similar pattern done on the Claims and Appeals team. ](https://dsva.slack.com/archives/C02GXKL8WM6/p1638303129266000)

**Comment by zach-park** [comment]
Cc: @kevinstachura @Mottie

**Comment by kristenmcconnell** [comment]
The profile team is working on a solution to get users to review both their mailing address and home address (if they don't check the box to apply changes to both). Liz Lantz is taking the following proposal to content tomorrow: https://app.mural.co/t/vsa8243/m/vsa8243/1639511492636/a7d05e80d5289ba70da1cd6f7b99fb8f7bf3276f?sender=uc940f53ad96ac0203d6d3631

**Comment by kristenmcconnell** [comment]
Calling out the focus is editing in pre-check-in.

**Comment by kristenmcconnell** [comment]
Wireframes: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/AC688E7F-3561-496C-ABA9-9870E6D71163
