### ISSUE TITLE
Switch to va-loading-indicator from LoadingIndicator

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33142]
The LoadingIndicator component is deprecated in favor of the va-loading-indicator web component. We should evaluate switching to it.
https://design.va.gov/components/loading-indicators

Communication from VSP Design System team: https://dsva.slack.com/archives/C5HP4GN3F/p1637245800148300

Known differences:
- 

Tasks:
- Try out replacing a few LoadingIndicators with va-loading-indicator and document any differences that appear

**Comment by laurenernest** [comment]
Similar work as #25890

**Comment by ptouchton** [comment]
@laurenernest I am finishing up the work on this new component and I have a question about this task in the ticket. 

> Determine if can switch over all our alert boxes in this ticket, or if we need to create new tickets or make design changes

I can't figure out how our alert boxes are tied to the loading indicator...can you clarify this A/C for me...or would Jennie know what I should be looking at?

Thank you

**Comment by ldelacosta** [comment]
@ptouchton - I believe that was done by mistake. Please disregard and I will update the ticket shortly. Thanks.

**Comment by ldelacosta** [comment]
This doesn't apply to this ticket:
