### ISSUE TITLE
Access for Demian Ginther

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#33155]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Demian Ginther

### Your Email

demian@adhocteam.us

### Name of Your Team

PST Access Management - Infrastructure Engr - Ad Hoc LLC

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+06x7fCmz+Ru04sd9zqIklo932CgvdX4Put9wxf2KU4k11vh1yPZ3w9w34zmttlpBKxiKRu5KiKs7ZadXx4f5I9vu/eYcmh2Vq8rDUE0LJlEejkYDzrXzx2ihZkOjEdFHAbFFY8J1i3ooTCWi+uS/IaGoXXZGhLc8c1qKQZd6KAKqNkMstux3NKU4Gx5GagDeNxfG1EMrQgT5q0ySRKft19jeTOQQOESLihhQvRvshGkuT26uDirCt9YPe5F+JPcq56Vy4soqAZO1E6lNNgNI4MBGZF/IA/80X6qFqgBziSaBfjqnEzEZct+2moRZ+ZLL1LXC6VsnIKonm/EthP2V demian@adhocteam.us

### Desired AWS Services

I will need access to Cognito, Parameter Store, EKS, and likely S3.

**Comment by mleclerc00** [comment]
Socks access deployed, will work with Demian as far as the AWS permissions that will be needed for his new spike team.

**Comment by mleclerc00** [comment]
Passed along aws console account info.  Closing ticket
