### ISSUE TITLE
Filter & Transform media-image content

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#3316]
## Problem Statement
Our tome-sync data doesn't match up with our templates, and we need to follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835) to ensure that the data will be compatible with our current templates.

## Goal
Content from `media-image` entities match their corresponding entities from `pages.json`

**Comment by drorva** [comment]
@cvalarida close? If not, apply cms-transfomer label.

**Comment by meganhkelley** [comment]
@jhonnyoddball is this ticket relevant anymore?

**Comment by jhonnyoddball** [comment]
This has been resolved!
