### ISSUE TITLE
[01/07/22] Pharmacy Pitch Deck

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#33170]

**Comment by aschulhof** [comment]
@aschulhof to follow up with Lindsay

**Comment by lindsay-insco** [comment]
Finished and will be presented at 01.12.22 OOH

**Comment by lindsay-insco** [comment]
[OfficeHours.12Jan22.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7989602/OfficeHours.12Jan22.pptx)
Slide 3
