### ISSUE TITLE
Update Documentation for forms controls

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#33178]
Linked Tickets:
* https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33177
* https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33114
Task: 
* Documentation on https://design.va.gov/ will need to be updated to reflect the changes made in the linked tickets
Goal:
Provide a straight forward guideline of:
* Why we are moving to web components from react components
* How to use the web component instead of the react component
* The issues that are being solved now by the web component

## Acceptance Criteria
- [x] Storybook links on design.va.gov point to web components
- [x] Guidance for using these components in React applications has been added to Storybook
    - We should be directing users to the [React application documentation ](https://design.va.gov/about/developers#react-applications)on the For developers page on design.va.gov

**Comment by pdavies88** [comment]
Need to determine how we want to handle documentation on Form Controls for Web Components since the current documentation needs to exist and exclusively references React Components: https://design.va.gov/components/form-controls
* Current bindings on forms used are set up to use React Components
* However this ticket would reference the work we did to convert the React Components over to Web Components
* Considerations need to take place over how a developer could migrate their form from using the React Components over the Web Components
* New documentation should be written for each form component to correctly reflect how they are to be used as a web component and any accessibility considerations that may come along with their usage.

**Comment by pdavies88** [comment]
@caw310 @k80bowman with all the updates that we have done in Storybook and design.va.gov recently this ticket is now invalid. We also link to https://design.va.gov/about/developers#using-web-components on every component in SB which would provide developer with the guidance they need if they are unsure.

**Comment by caw310** [comment]
@pdavies88 thanks. We can close or update tickets as needed.
