### ISSUE TITLE
Access for Brandon Clapp

### ISSUE THREAD

**Issue by brandon-clapp** [department-of-veterans-affairs/va.gov-team#33174]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Brandon Clapp

### Your Email

brandon.clapp@va.gov

### Name of Your Team

AFS-Education, developer, Accenture Federal Services

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEuOO0C5MgXGayNoLuvyiVNF5HwjgLyyNJKfNSHhCPxZ/fQbEwejuUqLsgZxTIkxlJBp51Gkj2ttpYliLznESRPZKS/Nejh4l+wFgmd3Xho5H+Kt8BfLkmv97zK1fuIchqrO3Kt1ArdivHsGycGlnGgwDs23LjgM4nDdSnciDuUa0dgAG7I8rHHqr2Sfdw+ubVYLZgDsU0pwhwd9utEKjPr3+Zo3Hol1WSXMMBiMyMjQbAN1ogqm/+8DpgAsShumIrdLv9tVYyY8oDurD8nL7RZQWNGtiE8sd+rcdhthNCjwcjwYefIbQKbEoHfKjbsBxuhZGq5GmX1XSUCKcUaUVheChO8rRBEJA2GYJtHbwU2KBWV/cw90ezirp8XX67HNL3e7LNtzDIpRcsUuJT7XRcbZ2ftWGs/ZCB0TTU2Zdc82EpcmrTRtTM1ppI53HmI4YyewzvL8VagRRNQnLlD8EMux5svcFEKsPsIz5hMhttL96oN1wFBr3/kz7I0bvKJ+hKJzxtfWUqnnPfoRG3Nh9AMCQffloQJHYGf5k1p8Ilp0EE2STazWbPCxF2ATCBx9E/cmhAS5KetNpfY1WjlUAKpC+QpMhvBwOLR0ooxwekdXi8xBG8JmyTbRSm7nggR69eLRCcEgTleZY83w72ti+QFovgHY6frI9N90OwRJ5rxQ== brandon.clapp@AFSMWQ9H7YS3V8J

### Desired AWS Services

My team has assumed maintenance/support for Comparison Tool, Feedback tool, etc. from the previous team. Please add me to the created group “afs-vfs-developers” and provide the same access as others in this group.

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Brandon Clapp
COR: Doris Lin
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @brandon-clapp 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

Please note that if any of your teammates need aws access or modifications to their permissions, they should open a access request stating so for transparency and tracking. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=Environment-Access-Request-Template.yml&title=Access+for+%5Bindividual%5D
