### ISSUE TITLE
Access for Samuel Vang

### ISSUE THREAD

**Issue by Vngpire** [department-of-veterans-affairs/va.gov-team#33175]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Samuel Vang

### Your Email

svang@clarityinnovates.com

### Name of Your Team

Identity, User Experience Designer, Clarity Innovations

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDE0Pyi+kg7UQxfb7dUEXH3zOU9OOHjaEXIytv9NSy/8Fc5q9JbBXJxhafH2fMZdWHqSOJ1/ykpi15EdSFHcVn4p+tudgvmiZMkcNJRFb23dqGUM21FM/y/TB4n6oiGgW1F0p488wFumJwid8JOXV15wPIXFmruujrp8qVpMY29/XVHgNzdCeO+r2o5qF+/YIcSQU0FqWrLzg41W4xQkjcwN4P+WzKCTyjSLVk8y79v9NyQgpYfgi5B+NG03oeBzp8JoXoh0S89yy2teUaJNakcYDhGdW+IhnvhWQ6hwuOzu/ZvYFu0f+EhtEhD+oxvqMf04KeEvoIp6rdeRbKoN9z9VzQtVk+bbGU3bZutmBOi+dgU6Bv4Ye0NAqCaZ3z2PrGSENcT57+bNv3hT6zEsdypQ7+li2+rbJM4At0yidwfLuFXzoPHQfn92D6ABEUN1FigDy5684cFz+aRZCZAifK1eKm5SquG4s0FMJa8/zq/KTFpd5zGbLnFlHEVdBDSHS0= samuelvang@samuels-mbp.lan

**Comment by mleclerc00** [comment]
Hi @Vngpire 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
