### ISSUE TITLE
[PERFORMANCE] Discovery: Audit dependency usage

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33188]
## Description
According to Google's Lighthouse tool, we have several dependencies in our web components and react components that we import, but don't use very much of. As part of an effort to reduce our package size, we'd like to audit our dependencies and make recommendations for ways we could reduce the amount of unused JavaScript we are importing.

The shaded areas in the dependency tree map below represent the unused JavaScript in our package.

![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/ee6fa828-bc7e-4a47-964f-009ecd494105)

## Acceptance Criteria
- [ ] Review each of our dependencies (not dev or peer dependencies)
    - How often are they used?
    - Are they necessary? Could what we are using them for be easily accomplished with native JS? (thinking especially about datefns here)
- [ ] Make recommendations for how we can reduce the amount of unused JavaScript we are importing from our dependencies
- [ ] Create tickets for completing this work.

**Comment by pdavies88** [comment]
## Notes on package.json packages
## react-components
### classnames
* Widely used across many files - Suggestion: Keep

### core-js
* In `package.json` in `react-components` but not imported on any files and it will still exist as a peer dependency of babel - Suggestion: Remove

### lodash
* All functions can be replaced by native JS - Suggestion: Remove and convert functions below
Functions used:
* uniqueId - https://youmightnotneed.com/lodash/#uniqueId
* isUndefined - https://youmightnotneed.com/lodash/#isUndefined
* isString - https://youmightnotneed.com/lodash/#isString
* range - https://youmightnotneed.com/lodash/#range
* has and isPlainObject and mapValues all used in the `dirtyAllFields` function in `fields.js` but `dirtyAllFields` is not used in any other files and can probably be removed

### number-to-words
* `react-components` -> `src/components/ProcessList/ProcessList.jsx` - Suggestion: Remove and convert via steps below
* Only used to convert integer to word ie: 1 to one
* Strategy on how to do that with native JS: https://ourcodeworld.com/articles/read/353/how-to-convert-numbers-to-words-number-spelling-in-javascript

### prop-types
* Complimentary package for React widely used - Suggestion: Keep

### react-focus-lock
* In `package.json` in `react-components` but not imported on any files - Suggestion: Remove

### react-focus-on
* Used only in `Modal.jsx` - Suggestion: Keep
* Used to fix the following issue: https://github.com/department-of-veterans-affairs/component-library/pull/66

### react-scroll
* Used only in `CollapsiblePanel.jsx` - Suggestion: Remove
* Used to do an animated scroll to the top of the panel
* There is native JS to use to do smooth scrolling: https://css-tricks.com/snippets/jquery/smooth-scrolling/
* However IE11 will need a polyfill to work properly or an if/else to determine the browser like below:
```
document.addEventListener('DOMContentLoaded', () => {
      //  little hack to detect if the user is on ie 11
      const isIE11 = !!window.MSInputMethodContext && !!document.documentMode;
      // ie 11 does not support smooth scroll, so we will simply scroll
      if (isIE11) {
        window.scrollTo(0, document.querySelector(ref).offsetTop);
      } else {
        window.scroll({
          behavior: 'smooth',
          left: 0,
          // top gets the distance from the top of the page of our target element
          top: document.querySelector(ref).offsetTop,
        });
      }
    });
```
* Note - CollapsiblePanel has been deprecated in favor of `va-accordion`

### react-transition-group
* Used only in `ExpandingGroup.jsx` - Suggestion: Remove
* Used only for a Fade Toggle
* Same effect can be recreated completely in CSS with opacity, height and transition
* Example: https://gomakethings.com/how-to-a-fade-in-to-vanilla-javascript-show-and-hide-methods/

### recast
* Used in the `build.js` file to flatten paths with requires when parsing through the JS tree
* Honestly I don't really want to mess with the build process of the `react-components` so I think we should leave it alone

## web-components
### @stencil/core and @stencil/postcss and postcss-url
* Keep core stencil packages - Suggestion: Keep

### classnames
* Widely used across many files - Suggestion: Keep

### intersection-observer
* Needed for back to top component to determine when to display - Suggestion: Keep

## storybook
### date-fns
* Remove from `MaintenanceBanner.stories.jsx` - Suggestion: Remove
* Remove from devDependencies as it is not being used per https://github.com/department-of-veterans-affairs/component-library/pull/243

## core 
### date-fns-tz
* Remove from `package.json` not in use - Suggestion: Remove

### react-focus-on
* See above

### react-scroll
* See above

### react-transition-group
* See above

### moment 
* Removed via https://github.com/department-of-veterans-affairs/component-library/pull/39

**Comment by k80bowman** [comment]
@pdavies88 This all looks good to me, thank you for digging into this. We will want to make sure that as we make changes to your dependencies that we are thoroughly testing every change in all supported browsers (including IE11 for now) to make sure everything works. Would you mind adding an item for that to the acceptance criteria for the tickets you are creating?

**Comment by pdavies88** [comment]
### Related Tickets

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34418
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34419
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34435
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34436
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34437
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34438
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34439
