### ISSUE TITLE
Adding Booz Allen Hamilton Team Members to DSVA Slack (Caseflow Transition to BAH)

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#33185]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add the following list of email addresses as full members of Slack.  Please note that Booz Allen Hamilton is taking over the Caseflow contract from TISTA and will need to be added to Slack, thus the mass of email addresses in this request.  Thank you for inviting each team member.  
--
barnwell_jeremy@bah.com
brady_matthew@bah.com
buckholz_ian@bah.com
figueroa_maggie@bah.com
franke_denise@bah.com
gray_matthew@bah.com
guerrero_jaymie@bah.com
jones_jennifer2@bah.com
knotts_jason@bah.com
lewis_lowell@bah.com
lu_janet@bah.com
martin_gregory2@bah.com
mccormack_will@bah.com
moreland_joseph@bah.com
muradaz_rey@bah.com
newman_lianna@bah.com
Quillman_Samantha@bah.com
roberts_matthew@bah.com
ross_kevin@bah.com
shields_jeremy@bah.com
termolen_dylan@bah.com
thomas_jason2@bah.com
tsang_jonathan@bah.com

**Comment by FredAllen6608** [comment]
I would like to get a status on this request please. I need them granted access to Slack so that we can continue with our transition efforts. @tlakemper

**Comment by LizCallaghan** [comment]
sure, I will work on it now

**Comment by LizCallaghan** [comment]
done!

**Comment by FredAllen6608** [comment]
Thank you
