### ISSUE TITLE
Filter & Transform node-health_care_local_health_service content

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#3318]
## Problem Statement
Our tome-sync data doesn't match up with our templates, and we need to follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835) to ensure that the data will be compatible with our current templates.

## Goal
Content from `node-health_care_local_health_service` entities match their corresponding entities from `pages.json`

**Comment by bkjohnson** [comment]
Closed by https://github.com/department-of-veterans-affairs/vets-website/pull/11476
