### ISSUE TITLE
Audit DOT NEXUS accounts

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#33190]
When we're nearing or at the end of our GHA work, there is a need to audit the DOT NEXUS accounts that were created.

To Do:
- [x] Gather all accounts that were handed out
- [x] Decide which ones should be left active and which should be turned off

Copying @mchelen-gov on this ticket

**Comment by oseasmoran73** [comment]
Groups that were created:

- npm-public
- npm-public-nocache
- https://devops.va.gov/dots-nexus/repository/platform-npm-4988449-4988452-4988453-4988454-release/
- https://devops.va.gov/dots-nexus/repository/platform-npm-4988449-4988452-4988453-4988454-snapshot/
- https://devops.va.gov/dots-nexus/repository/platform-npm-group/
- https://devops.va.gov/dots-nexus/repository/platform-npm-group-nocache/

Reached out to Jared to remove the following:
- https://devops.va.gov/dots-nexus/repository/platform-npm-4988449-4988452-4988453-4988454-release/
- https://devops.va.gov/dots-nexus/repository/platform-npm-4988449-4988452-4988453-4988454-snapshot/
- https://devops.va.gov/dots-nexus/repository/platform-npm-group/
- https://devops.va.gov/dots-nexus/repository/platform-npm-group-nocache/

**Comment by oseasmoran73** [comment]
Jared has replied and removed the following

- https://devops.va.gov/dots-nexus/repository/platform-npm-group/
- https://devops.va.gov/dots-nexus/repository/platform-npm-group-nocache/

He will be removing the others hopefully EOD so we can close out this ticket

**Comment by oseasmoran73** [comment]
![image](https://user-images.githubusercontent.com/10648480/145293375-51b49e49-ab1c-454c-9292-ee74274d62fc.png)

We will need to delete the team associated if we want to permanently delete. Thoughts? We are not using NEXUS anymore, so no point for us to keep those teams

**Comment by oseasmoran73** [comment]
With screenshot above provided from DOTS and syncing up with @mchelen , will be moving forward to delete those teams

Once they have been removed, will reach out to Jared to give another go

**Comment by mchelen-gov** [comment]
Deprecating these teams is reasonable since they are now unused. Was there a DOTS issue created to report the pain points when using NEXUS?

**Comment by oseasmoran73** [comment]
The VA network dependency was reported and was troubleshoot from DOTS via email. Unfortunately, there was so much they can control in that matter.

Regarding install time increasing, I can't recall if it was reported to them or not, but more than happy to submit one and try to find workflows with time increased

**Comment by oseasmoran73** [comment]
Teams created from [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27798) have now been deleted. Reaching out to Jared

**Comment by oseasmoran73** [comment]
Closing ticket as email has been sent to Jared
