### ISSUE TITLE
Access for Lisa Zapson

### ISSUE THREAD

**Issue by lzapson** [department-of-veterans-affairs/va.gov-team#33206]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Other

### Your Name

Lisa Zapson

### Your Email

lisa.zapson@adhocteam.us

### Name of Your Team

10-10, Senior Front End Engineer, Ad Hoc

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC89wvsUVwNZ9qzmnhXfVp9HSBRpBs9Qw+CqxkM4iv5zgRLQaz364jA9LtHwlUiyg60c5FE6BxViK4bbgXOTeXJMb0wrMVNlEw9BesaQJXAjkg2btp17pYh8lPMGrRV/IgJDWLXZDwr4CZ1e1k3b2H8cuZQK1mppYiIhExgL0BQc3y4mwesnA72UvgOenixHhmaCrKCvy5jjBihUwkkRiTuklc4ngwNeU8J2OJTRAsNwfcUKfyQzmaBNYThG86bVjPhZ83XePr5FdJmZm49DybzR5FUbFCE1OF/D8Zj7nYmf0bZr8Sp2Z1LLMF51Mu4hdBkNTX1/BeNlSAJfgw14DcDE90qAPuC5K1AH6EroDxtx2tnUCtJYAbnW03/xQ1eh4RNbriejMwki1F44+LUy0wdq9/JIKKYb4zpqf8SHh6YrLPMu1gqMev1E/qw7GrNMZPq1BxMtzM/vxwoY9AeJRiDsUr5Og3z9VyuqIvsKPJxuxbbqxahe4WR/YSaRmaZ8V8= lzapson@LisaZapson-HP

**Comment by mleclerc00** [comment]
Hi @lzapson 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
