### ISSUE TITLE
VA.gov Letters page banner from VA Mobile team

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#33200]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [X] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

The VSA Claims & Appeals team recently implemented a banner on the claims status page that highlights the app to users. See this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30252). We'd like to implement a similar banner on the [Letters landing page](https://staging.va.gov/records/download-va-letters/) that lets users know that they can use the mobile app to download letters as well. We expect to use almost identical language to the Claims banner, and to follow this pattern:

- If iOS is detected, a link to the app in the App store is displayed
- If Android is detected, a link to the app in Google play is displayed
- Otherwise both links are displayed

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Leanna Miller
-	Product manager: Ambika Roos
-	Designer: Jen Ecker
-	FE engineer: Patrick saxton
-	Product/team Slack channel: #va-mobile-app

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@ambikaroos What's the work you need us to do? Is it putting the banner on the page or reviewing the text? If it's the same language that was used for the other banner, not sure if it needs to be reviewed again. Thanks!

**Comment by ambikaroos** [comment]
@RLHecht the work needed is implementing the banner on the page. The content would need to be tweaked to be specific to letters, rather than referencing claims.

**Comment by RLHecht** [comment]
@ambikaroos Got it. What's the date for this to be done by?

**Comment by ambikaroos** [comment]
@RLHecht we expect that implementing the banner will result in a spike in mobile downloads/logins (this was the case for the claims banner, though that is a more heavily trafficked page). I don't have a clear date, but my guess is we would want to turn on the banner in January (given code freezes and holidays in December).

One dependency to note: we'll be mirroring what VA.gov does implementing the login.gov credential. We'll want to make absolutely sure that this rollout on the app is seamless and secure before driving more traffic to the app via the Letters banner.

**Comment by RLHecht** [comment]
Thanks for the background. I'll make a note that we will work on this in January and we can check in as it gets closer to see if we're still on track.

**Comment by RLHecht** [comment]
@ambikaroos Is this a react widget or a content alert we are posting in Drupal? If the content changes depending on if it's iOS or Android, I think it needs to be a react widget but we should confirm with public websites @brianalloyd @kelsonic. They would then need to create it with the content we give them and we would add it to the Drupal page.

**Comment by ambikaroos** [comment]
@RLHecht @vhenry07 's team implemented the existing banner on the claims page, so she may be able to answer this. Thanks!

**Comment by ambikaroos** [comment]
hey @RLHecht just wanted to follow up on this, we're eager to have it implemented asap cc @leanna-usds

**Comment by RLHecht** [comment]
Hello @MekoHong ! This work is dependent on Public Websites. They need to create the react widget with the content we provided them. I know that they've had some FE turnover on their team and other fires to put out, so I'm not sure where they are with this. I think it's slated for this sprint, but I'll have @brianalloyd confirm.

**Comment by RLHecht** [comment]
@MekoHong Public Websites finished the react widget and we just published the page It should be live later this afternoon. Please let us know if you need anything else.

**Comment by MekoHong** [comment]
@RLHecht thank you so much for the update!  CC: @leanna-usds
