### ISSUE TITLE
[Reverse Proxy / EKS] Validate solution approach using Traefik

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33205]
## Product Outline
[Application Hosting and Deployment using Container Orchestration](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration)

### Service Doc
[Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy)

## High-Level User Story
As a DevOps engineer on the Platform Operations team, I need to test the networking configuration of reverse proxy in EKS. 

_Note: The goal of this epic is to validate the solution approach using Traefik._ 

## Hypothesis or Bet
If we test the networking configuration, then we expect to be able to compare the performance with the existing implementation of reverse proxy in BRD. 

## OKR
O3. Platform security and stability approach is comprehensive, on par with industry leaders

### What must be true in order for you to consider this epic complete? 

- The performance of revproxy running in EKS using Traefik has been demonstrated is working via cURL (demo for the Ops team internally is fine).
- Data has been gathered that describes the performance: measure the request latency (using cURL) with revproxy on EC2, then on EKS with Traefik. 
- _If the performance is good, and we decide to move forward with this solution, then:_ **[A security review has been requested](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) before we bring up this service using this pattern.**

**Comment by jhouse-solvd** [comment]
To be able to compare, we will need to understand the baseline performance of the reverse proxy in BRD. 

Some high-level thoughts on helpful metrics:

For the reverse proxy in BRD:
- Latency of requests 
- Avg # of requests over time
- Maximum # of requests 
- Memory consumed per request 
- CPU consumed per request   

For the reverse proxy in EKS using Traefik
- Latency of requests 
  - BE requests 
  - FE requests
  - External services 
- Load testing based on data collected for the reverse proxy in BRD _(above)_

**Comment by mleclerc00** [comment]
all the upfront issues that we were seeing with revproxy are now fixed

if you run
```
curl -L --header "revproxy-eks: true" dev-api.va.gov
curl -L --header "revproxy-eks: true" dev.va.gov
```
or use something like modheader in your browser to modify the header passed along with your request it will toss you through the eks revproxy https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en


![image](https://user-images.githubusercontent.com/76792875/144640786-ad73310e-0675-4a5a-a450-ca4bb478ab59.png)

The listener rule on the dev revproxy alb will point at the eks revproxy when it captures the header `revproxy-eks: true`

**Comment by rbeckwith-oddball** [comment]
[https://app.zenhub.com/files/133843125/35ad696a-fad2-4bcf-88af-2d0d85437cfc/download](https://app.zenhub.com/files/133843125/35ad696a-fad2-4bcf-88af-2d0d85437cfc/download)[https://app.zenhub.com/files/133843125/5fc8b099-9cf6-4bbb-b24c-6b3b57570e38/download](https://app.zenhub.com/files/133843125/5fc8b099-9cf6-4bbb-b24c-6b3b57570e38/download)

**Comment by jhouse-solvd** [comment]
This is done. See https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/365 for pending security review.
