### ISSUE TITLE
Redirect Request

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33201]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] VAMC has changed the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
ASAP

### Redirects 
current URL |  Redirect to
--- | ---
https://www.va.gov/san-diego-health-care/locations/mission-valley-va-clinic/   |  https://www.va.gov/san-diego-health-care/locations/kearny-mesa-va-clinic/

### Vanity URLs 
N/A

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by kelsonic** [comment]
Redirect implemented + live on prod ✅

**Comment by SgardnerPMP** [comment]
Tested and validated.  Closing Ticket.  Thank you.
