### ISSUE TITLE
Access for Kevin Cranmer

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#33204]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kevin Cranmer

### Your Email

Kevin.Cranmer@libertyits.com

### Name of Your Team

Matsumoto

### Service(s) You Want Access To

AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCq7k9zIxZvIcMjzswMnJQGEKDXOmYoiIV7/9aCu+/mHpTPXw/XnWkFNQZcS+oLK9BW6rh5Sw9ISQR4x9S6XAEHKletSEvanvJexB6TtRv4aZ7OS4wB79nKupwPHL0Qv7KmV/cPsdFqt+ngt3TBdro3TxylO6ixPIwfmrCsahfwnnynHicKkP9lHF7uh40Qm2f+9jvX2eJ/LFqLXcwmAplzxolJfLjHJS/3qAVKfYBzZI+TPNl3oWlBeYyOQ4EYTENVgrUxtrbzCseSfEZG0IseX1nA9mabou+mPlSn13xvQV/Ab+NUF4l/ufXrtIJsFwttXJctZMr6Ax6xiTjyc78C61/ylH0HDvr56skxG34t+pp+jqv5i1bgWd4BeJPbUGlpdTJYkVapa/UHQ0atZ5K67c1Dmxg18N6QaPEzynScVbLgfRkB8twsR5CfaUmlXVaLC0hVuAHPSwbSrDzvQZN30defwn4Ab30BsyTOQvap7yIjRgha7FMf7ElEZpdVwDc= AzureAD+KevinCranmer@DESKTOP-4NF76QS

### Desired AWS Services

Please mirror all access that Mark Viterna has (including prod access and all accesses given under the AWS Console).

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Kevin Cranmer
COR: Cecila Lee
Approval needed: @mchelen-gov

**Comment by mleclerc00** [comment]
Hi @KevinCranmer

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by mchelen-gov** [comment]
EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by mleclerc00** [comment]
Added Kevin to the adhoc-vetsgov-ssm-prod policy, closing this ticket
