### ISSUE TITLE
[Ops Onboarding] Add CAG/Venafi instructions to onboarding checklist

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33210]
## Description
Add CAG/Venafi instructions to the "Ops Onboarding checklist" issue template in GitHub. This will help to ensure that team members have the information necessary to begin the process as soon as possible. 

## Background/context 
CAG/Venafi are tools required for managing SSL certificates (et al)
[Ops Onboarding checklist issue template
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Operations&template=ops_onboarding_checklist.md&title=VSP+Operations+Onboarding)

---
## Tasks
- [ ] Update GitHub issue template for Ops Onboarding

## Acceptance Criteria 
- [ ] Issue template has been updated with links to CAG/Venafi setup instructions

**Comment by jhouse-solvd** [comment]
@ph-One - Since you're going through the onboarding process now, can you take this on? The goal would be to ensure that the template is updated with links to relevant documentation that a team member needs to get set up for CAG & Venafi access.

**Comment by rmtolmach** [comment]
Here is the documentation for getting Venafi access: https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates
You need your PIV card to gain Venafi access, so maybe this can be towards the end of the onboarding checklist

I don't think there is any documentation for getting CAG access. I think I had the team walk me through it during standup or something?
