### ISSUE TITLE
Inventory of endpoints owned by platform

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#33215]
## Description

To get started on spinning off services from vets-api, we need to come up with a list of target endpoints that could migrate out first. To do this, we're going to pull out the list of endpoints and marking ones clearly under ownership of platform and identifying those that might make sense to pull under platform ownership in the future.

## AC:

- [ ] inventory of current API endpoints with speculative list of platform-owned APIs

**Comment by considerable** [comment]
work in progress:
https://docs.google.com/spreadsheets/d/14iNeWOyaMe0aqVtgfCqTE7cl3xAfQ7YJDsjRbADOXCk/edit#gid=1482742543

**Comment by ewilson-adhoc** [comment]
This has been completed (see attached google link) and presented to the wider team.
