### ISSUE TITLE
Confirm Default Sorting for Payment History

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33213]
## Background
A veteran has shown that the sorting for payment history was not sorting as we thought it was supposed to.

## Tasks
- [x] Confirm that the sorting is by date by default (where the latest, most recent, payments are at the top, on the first page)

## Acceptance Criteria
- [x] The sorting is confirmed

**For FE's ticket:**
- The sorting has been changed for prod (stretch)
- A PR has been requested (stretch)

**Comment by kathleencrawford** [comment]
For the first test user, the payments are returned in this order:

                  <scheduledDate>2021-11-23T00:00:00-06:00</scheduledDate>
                  
                  <scheduledDate>2021-11-05T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-10-20T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-09-15T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-08-25T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-07-19T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-06-21T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-05-25T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-04-15T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-03-17T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2021-02-23T00:00:00-06:00</scheduledDate>
                  
                  <scheduledDate>2021-01-25T00:00:00-06:00</scheduledDate>
                  
                  <scheduledDate>2021-01-19T00:00:00-06:00</scheduledDate>
                  
                  <scheduledDate>2020-12-22T00:00:00-06:00</scheduledDate>
                  
                  <scheduledDate>2020-12-08T00:00:00-06:00</scheduledDate>
                  
                  <scheduledDate>2020-08-14T00:00:00-05:00</scheduledDate>
                  
                  <scheduledDate>2020-08-03T00:00:00-05:00</scheduledDate>

**Comment by kathleencrawford** [comment]
Example payment data for another test user: 

                  <scheduledDate>2021-11-23T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2021-10-20T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-09-15T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-08-25T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-07-19T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-06-21T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-05-25T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-04-15T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-03-17T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2021-02-23T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2021-01-25T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2020-12-22T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-03-20T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2019-02-20T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-01-24T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-01-24T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-01-24T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-01-24T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-01-24T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2019-01-24T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2018-01-16T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2017-12-06T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2017-11-15T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2017-10-12T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-09-13T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-08-22T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-07-14T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-06-21T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-05-17T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-04-12T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2017-03-10T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2017-02-16T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2017-01-19T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2016-12-16T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2016-11-14T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2016-10-19T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-09-22T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-08-18T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-08-01T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-07-14T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-06-20T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-05-12T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-04-13T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2016-03-09T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2016-02-11T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2016-01-20T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2015-12-21T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2015-11-16T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2015-10-15T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-09-16T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-08-20T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-07-10T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-06-15T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-05-15T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-04-09T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-03-12T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2015-02-13T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2015-01-09T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2014-12-22T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2014-11-19T00:00:00-06:00</scheduledDate>
                  <scheduledDate>2014-10-20T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-09-11T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-08-11T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-07-25T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-06-24T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-05-28T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-04-28T00:00:00-05:00</scheduledDate>
                  <scheduledDate>2014-04-04T00:00:00-05:00</scheduledDate>
