### ISSUE TITLE
[Access Management] Identify additional opportunities for automation 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33212]
## Description
Processing onboarding and offboarding requests involve a lot of manual processes. It would be good to identify opportunities for automation that would help provide a better access management experience. Those ideas could then be prioritized and individual initiatives, epics, or issues could be created to track their implementation. 

## Background/context 
- There are manual processes involved in provisioning access for personnel, both for onboarding, and offboarding
- The security and access management teams are key stakeholders that can be consulted when developing solutions
- There will be benefits to the users that are requesting onboarding and offboarding, as well as... 
- This will help to reduce administrative overhead 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jhouse-solvd** [comment]
@kjduensing - Hey Kevin! 

This was a high-level ticket created in the past to look at new opportunities for automating onboarding and offboarding processes. There's no specific approach mentioned. It was more of a general "we should look into this" type of issue for tracking. 

I'm thinking that you may have something similar on your roadmap. if so, we might be able to close this one out in favor of an issue with a better, more-specific scope and approach. 

Let me know what you think? Thank you!

**Comment by jbritt1** [comment]
A lot of work has been done by PST-AMT this year for this need. We can re-evaluate if/when more is needed.
