### ISSUE TITLE
re-activate Access for Igor Yegorov

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#33234]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Igor Yegorov

### Your Email

igor.yegorov@adhocteam.us

### Name of Your Team

PTEMS VA.gov PLATFORM ENHANCEMENTS

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPpDZTAjvETlyNFIbf9Y78lvUzSxQkwedHIlVysaL3wEEjPvvXkZS6X32C26wMd3LBmQLYt1zcdgIy0V0S64f8ki4IsPb3RS/fxljmFJ8Hryty+0KvgwZol5tnm4gmxdE7AxyQSgTIsfLwiKz1O4/8nB/8dqwXn+SQ9SlDDboqrVTHwTx6ZjsEvTFJBXiahmHkcF2VZDpTyteZB8ck8ccnVGoZX1mAwNVzsAEMSXMi/0sjLeZ+4jE34+u34DOAjqAYkJz9YDtxcpqWDMFuRMbKDA38FvE/xPiT7RUojqDf58Jc2kvVR+XFuXdX0K2Iiz9ZTFe+fwVkzaWobWepcxs9/jyjooDeqDjXbV7qY6WfPqkyJWlHK92wbELCMuyVp4IyQ7fxUKlFn6MVNUbLC7rTwHcRX9llaeJ25Yr6kIcGR7p22TeVHUswj0p4+PMNeT4vX/LzX0+hCJe42LZ1ixO8BfJd/T7o90lx0lVeYvHjl/1jeQY4/ovfgrvvc7hf1wk= igor.yegorov@adhocteam.us

### Desired AWS Services

I need access to coming vets-api Amazon EKS

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Igor Yegorov
COR: Crystal Moultrie
Approval needed: @mchelen-gov

**Comment by mchelen-gov** [comment]
@mleclerc00 EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by considerable** [comment]
Additional info. 
The Platform Spike Team for Integration Experience  (PST-IET) is dynamic as it is still forming, 
currently consists of 4 people:
- PM: roger.sarkis@adhocteam.us
- PcMgr: daniel.choi@adhocteam.us
- DevOps: igor.yegorov@adhocteam.us 
- UX Research:  jimmy@adhocteam.us 
https://vfs.atlassian.net/wiki/spaces/IET/overview?homepageId=1908801923
of which, Dan and myself surely need AWS access for playing with current (EC2) and future (EKS) versions of vets-api on a sandbox.
What kind of access = admin. What kind of sandbox = @f1337 must know for sure.

**Comment by mleclerc00** [comment]
@considerable 

> future (EKS) versions of vets-api on a sandbox

As for getting access to eks and having a environment to test in, creating a separate issue with the following link would be better suited

https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=

> Dan and myself surely need AWS access

Daniel Choi will need to fill out his own access request here as well

https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=Environment-Access-Request-Template.yml&title=Access+for+%5Bindividual%5D

**Comment by mleclerc00** [comment]
Passed along aws account information to Igor, closing this ticket.
