### ISSUE TITLE
Standardized KPIs:  Document user interview findings and report out

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#33246]
## Issue Description
We conducted user interviews with VFS teams using standardized dashboards in order to get a better sense of the ways that users understand and interact with their dashboards. Our hypothesis is that if we understand how users are using or expecting to use the Domo dashboards, we can better curate KPIs and target new training resources, which will increase meaningful usage of our data products.

This is a continuation of the work from ticket #32732 (conducting user interviews)

Once this ticket has been completed, the work of brainstorms within the Analytics team to inform a plan for redesign will take place on other tickets.

---
## Tasks
-[x] Review mural board with team
-[x] Synthesize findings
-[x] Create readout deck
-[x] Present to key stakeholders

**Comment by pavanhothi** [comment]
Completed.
