### ISSUE TITLE
Address questions & concerns from ADR and office hours

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#33258]
1. What are some things to be aware of when setting up a client to use an ID Broker?
2. How does this help the internal VA developer?
3. What were unexpected hurdles/smooth-sailings?
4. How will authorization work? (in general - a deeper dive will be needed on this)
5. How will we integrate authentication & authorization at the IdB level including with external records--of-truth?

**Comment by ken-non** [comment]
@kjduensing and @ken-non to set up documentation in confluence

**Comment by kjduensing** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2054258689/Ongoing+List+of+Questions
