### ISSUE TITLE
Set up identity broker

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#33256]
Dependency:
#33255 

Depending on which identity broker we choose (Cognito vs Keycloak) steps will be different. 
All we will need to do is configure - possibly automated. 
(to be further refined with dependency is addressed)

**Task is done** 
when a user can be directed through the broker to the provider for login

**Comment by dginther** [comment]
Setting up the Keycloak that was already running in EKS to be persistent in case we decide to use KC.
