### ISSUE TITLE
PPMS provider address information (Backend Test VAOSR-2248) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33271]
- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2248 still exists
- Coordinate with VAMF as needed to resolve

**Comment by grossb1** [comment]
I was able to verify that the ccLocation field was present for booked cc appointments.  For propsed cc appointments the ccLocation field is empty.  This is by design.
