### ISSUE TITLE
VAOS: Error fetching an appointment (Backend Test VAOSR-2615/2728)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33276]
- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2615 (fixed)
- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2728
- Coordinate with VAMF as needed to resolve

**Comment by grossb1** [comment]
VAOSR-2615 was closed out on the VAMF end because this issue causing it had been resolved, however, this ticket still needs to be retested when the following additional issue has been resolved:
https://issues.mobilehealth.va.gov/browse/VAOSR-2728

**Comment by grossb1** [comment]
When MAS can’t locate an appointment by ID, it returns a 404. If this happens when a client is trying to cancel an appointment through the vaos-service, the client gets back a 500 due to a NPE.

If MAS can’t locate an appointment by ID, then VAOS should also return a 404.
