### ISSUE TITLE
Need created date for requests (Backend Test VAOSR-2592) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33273]
- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2592 still exists
- Coordinate with VAMF as needed to resolve

**Comment by grossb1** [comment]
VAOSR-2592 was closed out on the VAMF end because this issue causing it had been resolved, however, this ticket still needs to be retested when the following additional issue has been resolved:
https://issues.mobilehealth.va.gov/browse/VAOSR-2728
