### ISSUE TITLE
VAOS: Error creating va appointment - booked (VAOSR-2751)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33277]
- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2616 still exists (this was closed)
\- validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2751
- Coordinate with VAMF as needed to resolve

**Comment by grossb1** [comment]
Consolidating tickets related to an error posting a va booked appt.  The following is from #33938 which will be closed:
Associated VAOS-R ticket:
https://issues.mobilehealth.va.gov/browse/VAOSR-2751

I'm getting an a 500 error with the following POST request:
URL:
https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012845331V153043/appointments

Request Body:
'{"kind":"clinic","status":"booked","locationId":"983","clinic":"1081","slot":

{"id":"3230323131323230313633303A323032313132323031373030"}
,"comment":"test","extension":{"desiredDate":"2021-06-15T23:59:00.000+00:00"},"patientIcn":"1012845331V153043"}'

Response:
{:detail=>"failed to fetch clinic data", :source=>{:vamf_url=>#<URI::HTTPS
https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012845331V153043/appointments

, :vamf_body=>"{\"id\":\"10f47c11-dbd5-43bb-9772-7d07b21e7e5b\",\"code\":500,\"errorCode\":8004,\"traceId\":\"06884f52bc41e72cd72bd54819d97d3a\",\"message\":\"failed to fetch clinic data\",\"meta\":{\"upstreamErrorSource\":\"mobile-facility-service\",\"upstreamErrorId\":\"1ced7ca6-2972-468d-bf08-409235547897\"}}", :vamf_status=>500}, :code=>"VAOS_502"}
