### ISSUE TITLE
[Design] Update documentation on check-in text messages

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#33288]
Need to move the current Mural over to Sketch that documents all the current text messages sent related to check-in. Need to coordinate with CHIP (Adrian) to update to wording currently coded and mark any scenario where there is a difference. CHIP might need a ticket to help us with this.

Tasks:
- [x] Create text message landscape diagram (Mural or Sketch)
- [x] Review what's implemented with CHIP (Adrian)
- [x] Identify gaps to communicate to CHIP to address

Acceptance Criteria:
- [x] Landscape map shared with UX and CHIP
- [x] Schedule time with CHIP

**Comment by kristenmcconnell** [comment]
Blocked by the following CHIP ticket: https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/276

**Comment by kristenmcconnell** [comment]
The outcome of the CHIP audit:https://github.com/department-of-veterans-affairs/chip/blob/chip276-messaging-docs-update/docs/chip-messaging.md

**Comment by kristenmcconnell** [comment]
Messaged @niradatta1 for a review and asked Danielle if we could review at content office hours on Thursday.

**Comment by kristenmcconnell** [comment]
@aschulhof @Hortonio The site-wide content team is currently reviewing this spreadsheet with the proposed text message changes. Their final review should be completed by EOD Jan. 11. I'll be able to close out this ticket then. I was hoping that we could talk about the "source of truth" location for these messages. The benefit to [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) is that you can see the entire decision tree and flow. However, only UX will be able to maintain it. We could create a GitHub page for all the error messages and link to the page your team already created, so your page would be the source of truth. Thoughts?

**Comment by Hortonio** [comment]
@kristenmcconnell Makes sense with Sketch. I like the idea of linking to the Github readme and having the Github documentation be the source of truth. Sounds like we are on the same page.

When it is ready, can you please send us a link to the source of truth page your team is creating so we can also link to our page? This way we can have both pages linked to each other for easy reference.

**Comment by kristenmcconnell** [comment]
@Hortonio Sounds like plan. I will message you when everything is complete.

**Comment by julieadair1** [comment]
@kristenmcconnell - what is needed to close this ticket out?

**Comment by kristenmcconnell** [comment]
Danielle is reviewing the text messages by EOD today. I confirmed with her earlier today. Once I hear from her, I'll be creating a source of truth GitHub page. Then, I will message CHIP (@Hortonio) with the recommended changes. This might not be closed until tomorrow or really late tonight.

**Comment by kristenmcconnell** [comment]
Danielle's changes were shared via [Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1641934573040700).

**Comment by kristenmcconnell** [comment]
A GitHub page has been created where we can document all text and error messages for check-in and pre-check-in: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md#precheckin

It will serve as the source of truth. 

@julieadair1 @jparker0425 I was able to complete the review of all the CHIP messages, sync with content, create the above GitHub page, and move the user flow to Sketch. However, I will create new UX stories to:
- add all the VA.gov error messages to this new source of truth document.
- sync with VeText on their error messages.

@hortonio Here is the final CHIP text and error messaging wording: https://docs.google.com/spreadsheets/d/1sC-KOHAuewSvlwIoeKhGGJY1Pc_APOD_rUmIHnYOJ_k/edit?usp=sharing. The wording was review and approved by the site-wide content team. Let me know if you have trouble accessing this spreadsheet. Also, let me know what you think about the GitHub source of truth page (I know that it still needs to be completely filled out) via Slack.

I'm going to close out this story for now.

**Comment by Hortonio** [comment]
Thanks @kristenmcconnell, we will proceed with updating the hard-coded messages on the CHIP side! To track progress you can reference ticket [297](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/297).
