### ISSUE TITLE
"Platofrm" typo in QA document

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va.gov-team#33280]
### Description
The first sentence on this page has a minor typo -- 
Generally, QA is the practice of preventing mistakes and defects in a product or service. As it pertains to the **Platofrm**,

### Relevant URLs 
https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-(QA)-testing.1241579982.html

**Comment by lianilychee** [comment]
Oh jeez, how ironic.  I've fixed it; thanks for flagging!  Out of curiosity, did you submit this issue through the Feedback and Support link at the bottom of the [Quality assurance (QA) testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-(QA)-testing.1241579982.html) page?

**Comment by TKDickson** [comment]
Yep, I used that link.
