### ISSUE TITLE
Accessibility Research and Design

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33283]
## High Level User Story
1. As a hearing impaired veteran, I need options for checking into my appointments that will accommodate my accessibility challenges so I can check in for my appointments.
2. As a vision impaired veteran, I need options for checking into my appointments that will accommodate my accessibility challenges so I can check in for my appointments.
3.  As a mobility impaired veteran, I need options for checking into my appointments that will accommodate my accessibility challenges so I can check in for my appointments.\

## Goals
_What outcome(s) do we want to see?_ 

## Issues to create within this Epic

```
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**

**Comment by jparker0425** [comment]
Closing out this epic, all items complete @julieadair1 . Will create new epic in future if additional accessibility focused research is done for check-in or pre-check-in.
