### ISSUE TITLE
HSRM appointments without identifiers are missing (Front End Test - VAOSR #2286)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33291]
Will need to research what is needed to test the front end

- Validate if issue in https://issues.mobilehealth.va.gov/browse/VAOSR-2286 still exists
- Coordinate with VAMF as needed to resolve

**Comment by ldelacosta** [comment]
@grossb1 - I believe this was re-tested successfully and closed on the VAMF side. Please advise. Thanks.

**Comment by grossb1** [comment]
We were able to validate that this was resolved and tested in the front-end as well.  We can close this.
