### ISSUE TITLE
[BE] Emergency Contact (Read Only)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33298]
## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by dillo** [comment]
@julieadair1 @jparker0425 I think this is a duplicate of #33302

**Comment by julieadair1** [comment]
Yep, I agree.  Will close this one in favor of 33302
