### ISSUE TITLE
[FE] Emergency Contact (Read Only)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33297]
## Issue Description
As a veteran I need to be able to review my emergency contact for accuracy when I am checking in so that I can let a staff member know if I need to make updates to it.
This should follow the same rules and logic that NoK is following. 

Question: Is the data in Lorota already? 

## Front end tasks
- [x] Add Feature Flip. 
- [ ] Page is styled according to design spec. 
- [ ] Show new page if FF is enabled in day of app
- [ ] Show new page if FF is enabled in pre-check in
- [ ] create unit tests
- [ ] Create e2e tests

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by julieadair1** [comment]
Moving to "blocked" until we can determine whether the data is already in Lorota or not.

**Comment by mdewey** [comment]
Unblocked from a FE perspective https://dsva.slack.com/archives/C02G6AB3ZRS/p1638464838086400

**Comment by brianseek** [comment]
@ytsaoca / @niradatta1 / @kristenmcconnell / @zach-park Are there sketch mocks for Emergency contact page anywhere? I didn't see them on the usual sketch link.
