### ISSUE TITLE
Create 2022 health care copay rates page and 2021 past rates page-HOLD TO PUBLISH 12/23

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#33309]
The 2022 health care copay rates take effect January 1. We need to reach out to the stakeholder to get the new numbers to create the 2022 page. We also need to turn the 2021 page into a past rates page. 

As we are creating the 2022 page we should also review the page for sighted language that needs to be corrected.

2022 rates: [https://app.zenhub.com/files/133843125/f56dbc84-9e38-4e50-a098-efc05298de03/download](https://app.zenhub.com/files/133843125/f56dbc84-9e38-4e50-a098-efc05298de03/download)

Tasks:

- [x] Create 2022 page (Selina)
- [x] Review and check numbers against doc (Randi)
- [x] Create past rates page (Selina)
- [x] Review (Randi)
- [x] Set up left nav (Randi)
- [x] Publish pages (Randi)
- [x] Notify stakeholder that pages are live (Randi)

Acceptance criteria:

- [x] 2022 copay rates page is live
- [x] 2021 past rates page is live

**Comment by RLHecht** [comment]
Reach out to Jeff Grandon.

**Comment by RLHecht** [comment]
I emailed Jeff 12/1. Will post the rates here once I have them.

**Comment by RLHecht** [comment]
I've added the rates above. We need to hold on publishing until 12/27 but we can send a preview link to stakeholders before. Moving this to sprint 63.

**Comment by RLHecht** [comment]
Confirmed with stakeholders that we can publish these on 12/23, We will send them a preview link beforehand to review.

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. I've also updated sighted language instances.

2022 VA health care copay rates: http://preview-prod.vfs.va.gov/preview?nodeId=703
Past rates: 2021 VA health care copay rates: http://preview-prod.vfs.va.gov/preview?nodeId=42031
Past rates: 2020 VA health care copay rates: http://preview-prod.vfs.va.gov/preview?nodeId=11755

**Comment by RLHecht** [comment]
I reviewed these pages and checked numbers against word doc provided. Sending a preview link for stakeholders to review and will hold to publish until next week.

**Comment by RLHecht** [comment]
These pages are now published. Moving to validate and will close when live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket
