### ISSUE TITLE
VAOS Sustainment | Design System updates to web components

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33308]
## Description
The Design System team is switching from react components to web components. As the new web components are ready for implementation, we should make the relevant updates in VAOS.

The following components have been identified for this switch. 
- Accordion - n/a
- Additional Info - #33739 
- Alert Box - #25890
- Back to Top -  n/a
- Banner Official - #54831
- Breadcrumb - #40139
- Button Pair - #45517
- Checkbox - tbd
- Featured Content - n/a
- File Input - n/a
- Link - #47132
- Loading Indicator - #33142
- Modal - #38608
- On this Page - n/a
- Pagination - n/a
- Process List - n/a
- Progress Bar/Segmented Progress Bar - n/a
- Promo Banner - n/a
- Privacy Agreement - n/a
- Published Card - n/a
- Radio Buttons - #45792 - determined not used in VAOS. 
- Select - #29418
- Tables - n/a 
- Telephone - #40034, #45155
- Text Input - tbd

**Comment by ldelacosta** [comment]
We have completed this initiative. No additional work is needed. Closing out the ticket. cc: @JRRoof
