### ISSUE TITLE
Access for Scott James

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#33306]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Scott James

### Your Email

Scott.James@gcio.com

### Name of Your Team

Debt Foregiveness, Sr Back-End Developer, GovernmentCIO

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDM8/RGeYwscRw04vivjZJ0HIhxWfFsmpKtMz6xTQs8jjzUzdR+oZo/Kp+mdXVRRyBhr/6In6qKtZwbTeOcHsSu/KN4UEgzwwxN+4pS2mRuPSzmH3T6B4PeL0Hs4EYkUTMMqxVkqlBY6F54nLW6B2E8b4F2BNLWPaCHs9cOLWlH9lojVgsA0wToAWmk3LtBjh28gesKp790Otwx4S7+wdG/7ZZ/lWOAS0xqThLsAn6Ocf98ER56Q4AjnpU1qMLOl/6ZRRUKsRGtTwtMnjgmFhDHi+45YkrLyBdyHY2+7AwoXRqpcFjPh+sEQkWcHIcKZ3UCBoxojZegrerCq6+ArnVWEsU6dLkVq1u59DPKahfSZ7wkS+TMTWPX72Obh2ccqgtB3E6+xLFO+WLCbs9q+xiUtKsPgNT/8ChkAtZOFVwykMBfnWfFkoMLHcdNjgyyVRaxckyf2GVkZ73mcGM/ary4Dot08Nmx97Mm7S+6PAuolhNzHp/7m1Svtn047KNNY1E= macbook@Macbooks-MBP-2

### Desired AWS Services

S3 for attachments, CloudFront for Logs, Systems Manager for Parameter Store, and EC2 to view staging instances

**Comment by ScottyRJames** [comment]
Additional Notes:

Originally submitted access [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30264) when first onboarding but the ssh key provided was one manually generated and not the `id_rsa_vagov` one generated by vtk.

**Comment by jbritt1** [comment]
> Additional Notes:
> 
> Originally submitted access [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30264) when first onboarding but the ssh key provided was one manually generated and not the `id_rsa_vagov` one generated by vtk.

Since the AWS approval process is already connected to the original ticket, let's close this one and update your public key on the existing one.
