### ISSUE TITLE
Adding BAH Team Members to DSVA Slack

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#33318]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add the following list of email address as full members as part of the continuing transition process for Caseflow:
njyothiboggaram@razortalent.com
sward@take2it.com
George.Hovakimyan@lefant.org
lberry@take2it.com
giorgio.thomas@bw-thinking.com
justin.sulak@bw-thinking.com
akayad@take2it.com
isaucedo@take2it.com
jaimebenitez@tuckerrose.com
mrahaman@take2it.com
jdavison@take2it.com

**Comment by FredAllen6608** [comment]
This one too @LizCallaghan

**Comment by LizCallaghan** [comment]
alrighty

**Comment by LizCallaghan** [comment]
done!
