### ISSUE TITLE
Filter & Transform paragraph-number_callout content

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#3331]
## Problem Statement
Our tome-sync data doesn't match up with our templates, and we need to follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835) to ensure that the data will be compatible with our current templates.

## Goal
Content from `paragraph-number_callout` entities match their corresponding entities from `pages.json`

**Comment by bkjohnson** [comment]
**Blockers**

- `entityId`
- potentially the wysiwyg `processed` field.  This can be odd with whitespace and other things.

Example from `pages.json`

```json
{
  "entity": {
    "entityBundle": "number_callout",
    "entityId": "6848",
    "fieldShortPhraseWithANumber": "30 days",
    "fieldWysiwyg": {
      "processed": "Average time to process education claims"
    }
  }
}
```
