### ISSUE TITLE
Access for David Montagna

### ISSUE THREAD

**Issue by MontagnaDave** [department-of-veterans-affairs/va.gov-team#33315]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

David Montagna

### Your Email

david.montagna@agile6.com

### Name of Your Team

PTEMS VA.gov Modernization, Delivery Manager, Agile 6

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/uNDqvLnhWRHtpiykGwLjFLcG7QLLtHOvaPMYvxQDZ7id2eNZEG2dJnvp3I06OUZokleALSFSxTNnRD0ibm4OcGPu9q2hoRy/ajsQh6NpZX1VZuK6ZpgYaq82xp7si77MLhddSQaszLlNBmGPGmBHwLKeKEp0R/B4KMe1uSoT8RhNaW7mCJEJ7z+CECKB3dSUv10GuADFi7Y4u0icocv1yWhxq3nS5hjUhtQQHBoRQnD9XmYvnJsa2VBPJe9MrzH3GqqwWDlA93QucQc8oaDbm5x0AvOkPbUMO+5Spm7eBo/SAdJB2QGDZiFiTGEloL749Bi2CffTar6XRWLg4WmoI3tfb07RHasPbNYVgvr4I5QeQ/jEIj3Aalle5ZYdTCHSHr6JsqaujB5JSKTQWNbkJ+quCujfhuzL2/G1Q5OR61s/IvJPTvnoc8XSmjeZYkqo7COn+DHkWhxcMPYheG23IEoVAnpgXnyDgdWW1j9hJbbwkHGrL5G4o5IIB04cXNc= montagnadave@Agile6-A71

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
