### ISSUE TITLE
[Discovery] Dynamically generate ID for forms

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33326]
## Description
Original ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/383#

The health questionnaires feature is not just one single form that a Veteran will fill out once. In the future, Veterans could have a questionnaire to fill out for every medical appointment. What questionnaire is displayed to the Veteran is based on a combination of appointment type (such as primary care, cardiology...this is also known as the stop code), appointment date, and the associated clinic/facility where the appointment will take place. A Veteran can even have multiple instances of the same form to complete depending upon their appointments.

As a result, we needed the forms library to be much more dynamic to accommodate our use case. We are proposing that the following changes be added to the platform, so other teams can utilize them if needed:

Forms should be able to have a dynamically generated id. Currently, the form needs a static Id, such as COVID-VACCINE-TRIAL. In order for the user to have multiple instances of the form, the form needs to be generated, not hardcoded. The ability to supply a function or a string for the form id would solve this problem.

What we need to know from this card is what work would be necessary in order to allow teams to add a dynamically generated ID without losing the current functionality.

## Notes
Right now, it looks like IDs come from this [constants](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/constants.js) file.

## Acceptance Criteria
- [ ] Research what it would take to allow teams to add a dynamically generated form ID without losing the current functionality
- [ ] Create a plan for getting the work done. This may mean creating one ticket with all the technical details necessary. This may mean dividing the work up between multiple tickets, depending on what kind of work is necessary.

**Comment by caw310** [comment]
Time box this discovery work to 2 days maximum.

**Comment by andresriveratoro** [comment]
In order to support a dynamically generated formId, we will need to make the following changes:

## vets-website 

`src/platform/forms-system/src/js/containers/FormApp.jsx`
```javascript
render() {
  ...
  if (typeof formConfig.formId === 'function') {
    formConfig.formId = formConfig.formId(this.props);
  }
  ...
}
```

## vets-api
Any application that utilizes the forms library will have to replace hardcoded formId (if it exists) values in its controller and model.

Using `health_care_application` as an example, remove FORM_ID and update where it's used with a value of `params[:id]`.

`app/controllers/v0/health_care_applications_controller.rb`
```javascript
module V0
  class HealthCareApplicationsController < ApplicationController
    FORM_ID = '1010ez'

    skip_before_action(:authenticate)

    def create
      load_user

      health_care_application = HealthCareApplication.new(params.permit(:form))
      health_care_application.async_compatible = params[:async_all]
      health_care_application.google_analytics_client_id = params[:ga_client_id]
      health_care_application.user = current_user

      result = health_care_application.process!

      clear_saved_form(FORM_ID)

      render(json: result)
    end
...
```

`app/models/health_care_application.rb`
```javascript
# frozen_string_literal: true

require 'hca/service'
require 'hca/rate_limited_search'
require 'hca/user_attributes'
require 'hca/enrollment_eligibility/service'
require 'hca/enrollment_eligibility/status_matcher'
require 'mpi/service'

class HealthCareApplication < ApplicationRecord
  include TempFormValidation
  include SentryLogging

  FORM_ID = '10-10EZ'
...
```

The following files are using hardcoded formId values and may have to be updated to support a dynamic formId:

```
app/models/health_care_application.rb
app/models/dependents_application.rb
app/models/form_profile.rb (FORM_ID_TO_CLASS)
app/models/form526_submission.rb
app/models/gi_bill_feedback.rb
app/models/in_progress_form.rb (default_expires_after)
app/models/saved_claim.rb (submit_to_structured_data_services)
app/models/form_profiles/va_526ez.rb
app/models/form_profiles/va_0873.rb
app/models/form_profiles/va_0994.rb
app/models/form_profiles/va_1990s.rb
app/models/form_profiles/va_10203.rb
app/models/preneeds/burial_form.rb
app/models/saved_claim/ask.rb
app/models/saved_claim/burial.rb
app/models/saved_claim/caregivers_assistance_claim.rg
app/models/saved_claim/dependency_claim.rb
app/models/saved_claim/dependency_verification_claim.rb
app/models/saved_claim/disability_compensation.rb
app/models/saved_claim/education_career_counseling_claim.rb
app/models/saved_claim/pension.rb
app/models/saved_claim/veteran_readiness_employment_claim.rb
app/models/saved_claim/disability_compensation/form526_all_claim.rb
app/models/saved_claim/education_benefits/va_0993.rb
app/models/saved_claim/education_benefits/va_0994.rb
app/models/saved_claim/education_benefits/va_1990.rb
app/models/saved_claim/education_benefits/va_1990e.rb
app/models/saved_claim/education_benefits/va_1990n.rb
app/models/saved_claim/education_benefits/va_1990s.rb
app/models/saved_claim/education_benefits/va_1995.rb
app/models/saved_claim/education_benefits/va_5490.rb
app/models/saved_claim/education_benefits/va_5495.rb
app/models/saved_claim/education_benefits/va_10203.rb
app/workers/bgs/submit_form674_job.rb
app/workers/bgs/submit_form686c_job.rb
app/workers/education_form/process10203_submissions.rb
app/workers/education_form/delete_old_applications.rb
app/workers/education_form/create10203_applicant_decision_letters.rb
app/workers/education_form/create10203_spool_submissions_report.rb
app/workers/evss/disability_compensation_form/form8940_document.rb
app/workers/evss/disability_comepnsation_form/submit_form0781.rb
app/workers/preneeds/delete_old_uploads.rb
lib/evss/disability_compensation_form/form4142_processor.rb
```

**Comment by andresriveratoro** [comment]
Coordinate with backend tools team for vets-api work

**Comment by k80bowman** [comment]
@micahchiang we may want to talk about this one as well.
