### ISSUE TITLE
Make title and subtitle dynamic on forms 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33327]
Original ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/383#

The health questionnaires feature is not just one single form that a Veteran will fill out once. In the future, Veterans could have a questionnaire to fill out for every medical appointment. What questionnaire is displayed to the Veteran is based on a combination of appointment type (such as primary care, cardiology...this is also known as the stop code), appointment date, and the associated clinic/facility where the appointment will take place. A Veteran can even have multiple instances of the same form to complete depending upon their appointments.

As a result, we needed the forms library to be much more dynamic to accommodate our use case. We are proposing that the following changes be added to the platform, so other teams can utilize them if needed:

The title, and by extension the other details, such as the subtitle, of the form, should be dynamic. It is helpful to supply React components of functions for the title to add be able to add custom logic.

**Comment by k80bowman** [comment]
I believe this is already possible. It was implemented in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13998) and there is an example of it being used in this [second PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14052).

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new bug.
