### ISSUE TITLE
[Discovery] Make expiration date dynamic 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33323]
## Details
Original ticket:  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/383#

The health questionnaires feature is not just one single form that a Veteran will fill out once. In the future, Veterans could have a questionnaire to fill out for every medical appointment. What questionnaire is displayed to the Veteran is based on a combination of appointment type (such as primary care, cardiology...this is also known as the stop code), appointment date, and the associated clinic/facility where the appointment will take place. A Veteran can even have multiple instances of the same form to complete depending upon their appointments.

As a result, we needed the forms library to be much more dynamic to accommodate our use case. We are proposing that the following changes be added to the platform, so other teams can utilize them if needed:

Dynamic expiration date: the default form system has a 60 sliding expiration date for a form's data. For our use cases, 60 days is not correct. A questionnaire expires on the day of the appointment. This is about passing the expiration date to the SIP system.

According to this Slack thread, it may be possible to pass in a date value for the `expires_at` datetime column in the VSA Healthcare database through the frontend. We need to do some discovery, however, to see if this is possible. If it is, we can create a card to get the work done. We should also keep in mind that this may not be the only database that uses the form expiration date, so we'll want to be careful about how we implement this change.

## Notes
- [Slack thread #1](https://dsva.slack.com/archives/CBU0KDSB1/p1606842454309000?thread_ts=1606839615.301800&cid=CBU0KDSB1)
- [Slack thread #2](https://dsva.slack.com/archives/CBU0KDSB1/p1603470261455700)

## Acceptance Criteria
- [ ] Do the research to determine if this is possible using the VSA Healthcare database
- [ ] Make sure this can be done without disruptions to the current functionality
- [ ] If it's possible, create a plan for getting the work done. This may mean creating one ticket with all the technical details necessary. This may mean dividing the work up between multiple tickets, depending on what kind of work is necessary.

**Comment by caw310** [comment]
Time box this discovery work to 2 days maximum.

**Comment by pdavies88** [comment]
It looks like some work was done the Vets-Api to allow for a custom expiration date via this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5581/files
However it takes in a `days_till_expires` value to set up the custom expiration [here](https://github.com/department-of-veterans-affairs/vets-api/blob/f37e3fffc49625b9177c03df0c4cb0963af2caf2/app/models/in_progress_form.rb#L111) and then sends that to the flipper [here](https://github.com/department-of-veterans-affairs/vets-api/blob/f37e3fffc49625b9177c03df0c4cb0963af2caf2/app/models/in_progress_form.rb#L69) to determine if it uses the `custom_expires_after` or `default_expires_after`

**Comment by pdavies88** [comment]
I believe that to achieve the result being requested a developer would need to add an additional parameter to their form configuration that would specify the correct ending date for that form set as daysTillExpires.

Overall this request will ultimately effect a lot of current forms and probably should lead to a larger conversation with the PST Forms Team about how to handle this request as they rework the current forms system.

**Comment by k80bowman** [comment]
Thanks @pdavies88 for looking into this!

@micahchiang tagging you here for visibility. We can talk about how our teams might want to handle this at our next meeting.
