### ISSUE TITLE
Ensure all User UID queries search by IDME or Login.gov UID

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#33324]
Trevor to add details

**Comment by bosawt** [comment]
Here is a list of different queries and what I could find in our code base:

# Ensure all user_uuid queries search by ID.me or Login.gov
#oddball/zenhub/33324

* Searches to make
	* `account_id`
		* `accountable.rb`
			* Used to associate `AccountLoginStat`
		* `notifications_controller.rb`
			* `Notification`
				* `account_id` used to find `Notification`
				* These are deleted when `Account` is deleted
		* `dismissed_statuses_controller.rb`
			* `Notification`
				* `account_id` used to find `Notification`
				* These are deleted when `Account` is deleted
		* `account_login_stat.rb`
			* Validates `account_id` presence as it is an associated model
		* `notification.rb`
			* Validates `account_id` presence as it is an associated model
		* `preferred_facility.rb`
			* Validates `account` presence as it is an associated model
		* `user.rb`
			* `account` function 
		* `schema.rb`
			* `account_login_stats`
			* `covid_vaccine_registration_submissions`
			* `notifications`
			* `preferred_facilities`
		* `registration_controller.rb`
			* `account_id` used to associate a `RegistrationSubmission` with a user
	* `Accountable`
		* Used by `after_login_actions.rb`
	* `user_uuid`
		* Used in a ton of places, here is an abridged list using only potentially relevant examples:
			* `authentication_and_sso_concerns.rb`
				* Used in `sso_logging_info`, might want to add a field that describes which type it is
			* `sentry_controller_logging.rb`
				* Used in `set_tags_and_extra_context`, might want to add a field that describes what type it is
			* `in_progress_form.rb`
				* `id_me_user_uuid` is a funky function and should probably change
			* `process10203_submissions.rb`
				* This queries `Account` table by `idme_uuid` or `logingov_uuid`
			* `form526.rake`
				* This queries `Account` table by `idme_uuid` or `logingov_uuid`
	* `account_uuid`
		* `test_user_dashboard` uses this to correlate test accounts
		* In `schema.rb`
			* `test_user_dashboard_tud_account_availability_logs`
			* `test_user_dashboard_tud_account_checkouts`
			* `test_user_dashboard_tud_accounts`
		* `lighthouse/session.rb`
			* `account_uuid` used here for `session_id`
		* `mobile/application_controller.rb`
			* `lock_vets360_linking`
				* Uses `account_uuid`
			* `vet360_linking_locked?`
				* Uses `account_uuid`
		* `tud_account_availability_log.rb`
			* Validates `account_uuid`
		* `tud_account.rb`
			* Uses `account_uuid` to find `UserIdentity`
		* `test_user_dashboard/account_metrics.rb`
			* Uses `account_uuid`
		* `vaos/session_service.rb`
			* Uses `account_uuid`
		* `vaos/user_service.rb`
			* Uses `account_uuid` for sessions
		* `vaos/extend_session_job.rb`
			* Uses `account_uuid` to update session token
	* `user.uuid`
		* Used in a ton of places, here is an abridged list using only potentially relevant examples:
			* 
	* `Account.`
		* `user_session_form.rb`
			* Uses `Account` to find an identifier when it cannot be found
		* `account_creator.rb`
			* A lot of `Account` reference here
		* `create_test_user_account.rb`
			* Potentially creates an `Account`

**Comment by bosawt** [comment]
[Uploading... Ensure all user_uuid queries search by ID.me or Login.gov.rtf]

**Comment by bosawt** [comment]
I don't think there's any that are truly concerning except for possibly `InProgressForms`, we may need to make an update so they can be saved with a `logingov_uuid`. I added a story to track this
