### ISSUE TITLE
[PERFORMANCE] Locate unused CSS in Formation

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33336]
## Details
We'd like to see if we could use a tool like [PurgeCSS](https://purgecss.com/) to identify CSS in Formation that is not being used on VA.gov.

Once it is identified, we would need to consult with with the DSC to see if it is appropriate to delete any of it, but if we can it could help reduce our package size.

## Acceptance Criteria
- [x] Evaluate if it is possible to use a tool like PurgeCSS to identify CSS in Formation that is not being used on VA.gov
- [ ] If so, document the unused CSS
- [ ] Consult with DSC about deleting unused CSS
- [ ] If approved, create tickets for deleting unused CSS

**Comment by bkjohnson** [comment]
I did some experimenting with PurgeCSS - both as a command line tool and as a webpack plugin in `vets-website`. I wasn't able to get the kind of list that we are looking for, so identifying unused CSS will likely have to be done manually.
