### ISSUE TITLE
Add a Cancel appointment link to the Confirmed Details Page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33330]
## Description
A veteran cannot cancel the appointment after booking the appointment. The updated changes will allow the user to cancel the appointment right after they have confirmed their appointment.

**Current Behavior:** 
![Screen Shot 2021-12-13 at 2.51.17 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ba7c2016-c49a-4746-848a-e3dc132acde2)

---

## Acceptance Criteria

Given when the new appointment workflow 
When the user schedules a direct appointment 
Then the user will see a cancellation link on the confirmation details page
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#confirmation-states) 
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/dlQRdz3), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/dlQRdz3), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/Qb5EyKY) 

### Design Assets
[M/T/D design specs](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63?search=VA-APPT_CONFIRMED)
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by grossb1** [comment]
It was determined that in order to display the Cancel Appointment link on the Appointment details confirmation page,the back-end would need to be updated to return the newly created appointment from the POST request.  Currently it returns a 204 with an empty response body.  Due to the fact this will require an enhancement to the vets-api v0 endpoint, the team has decided to hold off on this until v2 is live.

**Comment by ldelacosta** [comment]
This is no longer an issue. The cancel link appears on the confirmation details page.

See latest screenshot from staging on 06/28:
![Screenshot 2023-06-28 at 2.16.00 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/11b08809-e49d-4355-8f32-d261d5edbb4d)


Closing out the ticket: @JRRoof
