### ISSUE TITLE
Update FormSignature component to use va-checkbox

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33340]
## Details
When the FormSignature and Attestation forms system components were [first created,](https://github.com/department-of-veterans-affairs/vets-website/pull/17525) the va-checkbox component was not yet available. In order to make the FormSignature component more accessible using aria-describedby, we need to update it to use the va-checkbox component, which accepts an aria-describedby prop.

## Acceptance Criteria
- [ ] FormSignature is updated to use the va-checkbox component, passing the ariaDescribedBy prop that comes from the Attestation component
- [ ] Unit tests are updated to reflect the change

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
