### ISSUE TITLE
Create monitor for IAM SSOe

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#33350]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021/2021-11-29-autoscale-group-asg-cycle.md#action-items

**Comment by joeniquette** [comment]
This task has evolved into documenting the current monitors that the Identity team has setup in datadog and other areas. This ticket can be closed as another ticket has been made.
