### ISSUE TITLE
Access for Chikaodi Adibemma

### ISSUE THREAD

**Issue by cadibemma** [department-of-veterans-affairs/va.gov-team#33353]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Chikaodi Adibemma

### Your Email

chika.adibemma@adhocteam.us

### Name of Your Team

VA Mobile API, Backend Software Engineer, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3Il0sjlYGPDKF0UrxWm72enP4nbEJC3TFDjN756Ku5G/FMMQK3S9SfbBSird1MlT0HVZucIDQ4BsCle8x5nnGyqVxdzK/F1rzP8OsXNU4ig5j6HDe5KdszBQ0UU+dSoHK2WKapXxOPVU8myh864IcWf/9jLX2nDNVlh4qcE0sE5TYbNFcd87T2DIGEP6nXq6mEoWEllLu2RzLAkRn5Eoe5f1x2GLxPf6ValdtzzjPqLWrPdsmbGRD+Fpj5kcxfULm+3SvfEUteujZ3Qwoop7HOhPZ3qjFrAuHC+evpA9i7wLt51MaF76PvI0KOIAyL/6TbXd23/nQwWIWMoPMSLS73esPZHogUe+8A+atvNEwlW8gsWfh4TmMbOXwKBs3k4fzH5+7EAlyOerlFkx5LXjlmTpCDMkJYgD+7aX0RnC9SMoQpmr9gBWaDqt14mwnAwQP9qDD3a/dkB2LKeqaSfVQpz0UYIUiBC20pbGddgX1y28XOlXDuZFialMFgc35Az8= chikaodiadibemma@chikaodbemmambp.lan

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Note: please allow up to 10 minutes for the changes to be deployed before attempting connections**
