### ISSUE TITLE
[Campaign Landing Page Production Launch]- VA Network of Support Pilot Program

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33368]
## Description 
(Per William Brinley, Office of Outreach) Looking to kick off a Campaign focused on providing background and enrollment information about the VA Network of Support Pilot Program 

### Goal: 
To encourage Veterans to enroll in the VA Network of Support Pilot Program. 

### What we want to do on this page:

To provide relevant information that provides background and enrollment information about the VA Network of Support Pilot Program. 

## Key Info

**CMS Clone URL/Node**
_[PENDING]_ 

**Who is Requesting**

- Requestor name: William Brinley (OTED) / Charles D Gallucci 
- VA organization: Office of Outreach, Transition and Economic Development 
- Email address: cgallucci@mitre.org, william.brinley@va.gov

**About the Campaign**

- Name or focus of Campaign
   -  VA Network of Support Pilot Program 
   
- Target audience(s) [up to 3]:
   - Veterans, Caregivers, Families, TSMs
   
- Campaign start and end dates: 
   - Start Date: Dec 7, 2021
   - End Date: Dec 31, 2021 (Pending how long Pilot Program lasts, could be extended)
   
- Campaign page target launch date: 
  -  Dec 5, 2021
  
- Preferred URLs: 
  -  Vanity URL: www.va.gov/network-of-support
  -  Canonical URL: www.va.gov/initiatives/network-of-support
   
- What will you to drive awareness of this Campaign and this page? 
   - Social media, blogs, VSO briefings, YouTube Videos.  
   
- What metrics will you want to know to measure success of the Campaign landing page? 
   - Site visits, Page Views, Click throughs to existing reference materials (CTAs), measured reduction in unnecessary Veteran emergency care visit numbers. 

**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Built Pilot but might need a refresher
  
- Who will build the campaign landing page in the VA.gov CMS?
  - Tanekwa Bournes, VBA Program Analyst.
  
- Who will review and give approval to publish the page? 
  - William Brinley, Outreach Team
  
- Who will update/maintain the landing page during the campaign?
  - Tanekwa Bournes, VBA Program Analyst.
  
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - Dec 31, 2021 is the retired date, however it depends on how long pilot program runs and could extend into Jan/Feb 2022. 

## What Needs to Be Done

- [x] CMS: Set up the CLP clone page in CMS for the build template 
- [ ] Product & IA: Validate that the requested vanity URL is workable/optimal 
- [ ] Product: Get the Analytics dashboard set-up and set-up VA stakeholder to create their UTM URLs

**Comment by brianalloyd** [comment]
@xiongjaneg I copied you on email traffic for the CLP request.  Would need to clone in support of initial build.

**Comment by brianalloyd** [comment]
@mnorthuis @DanielleThierryUSDSVA @bethpottsVADEPO could you please review the requested URL and advise of recommendation for this initiative.  URL determination would need to happen NLT tomorrow in support.

**Comment by xiongjaneg** [comment]
CLP was created in Drupal at https://prod.cms.va.gov/initiatives/nos
Saved under VBA, which Tanekwa has access to in Drupal

**Comment by brianalloyd** [comment]
Confirmed with CLP requesting team the desired URL
   - Vanity URL: www.va.gov/network-of-support
   - Canonical URL: www.va.gov/initiatives/network-of-support

@xiongjaneg could you update the `clone` to reflect the above URL structure, thanks.

**Comment by brianalloyd** [comment]
This CLP is Live.  Closing this ticket in support
