### ISSUE TITLE
[Research] Login.gov as CSP in the VAOS application tool 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33360]
## Description
Identity team plans to rollout Login.gov next week (12/8) and we will need to do research to see if this update will impact the VAOS application. 

---
## Background
Login.gov Back-end Impacts
We don't anticipate the addition of Login.gov as a CSP to require any major changes on the part of other teams.  However, from a back-end perspective, areas utilizing `uuid` may be impacted as the past assumption was that this was equivalent to `idme_uuid`. Now, `user_uuid `may be `idme_uuid` or `logingov_uuid `.

Given this, it would be good for teams that work with these parameters to ensure queries for user's account data from Accounts now search for either for a matching `idme_uuid` or `logingov_uuid`

Best practice moving forward is for teams to use `@current_user.uuid` in place of `account_id`

Login.gov Front-end Impacts: Any content or features which is CSP-specific should be re-evaluated.

Additional info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/User%20Accounts%20Proposal/user_accounts_proposal.md

**Comment by grossb1** [comment]
I reached to both Alistair Dawson and Trevor Bosaw (as they are both much better versed in the auth and session flow than I am) and both indicated that this change shouldn't impact us.

**Comment by laurenernest** [comment]
Thanks for validating. closing ticket.
