### ISSUE TITLE
Create TUD Playbook and Train SREs

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#33367]
## Issue Description
We need to create a playbook to allow support personnel to effectively assist VFS teams in using the TUD

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Draft PR - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/96

**Comment by holdenhinkle** [comment]
Notes:
There's a lot of information in the 

- TUD readme - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard
- Help doc - http://localhost:8000/help

Sections that can be added:

- What happens when the service is done
- How to manually update the tud_accounts table
- Information about the daily maintenance job that checks accounts back in

**Comment by holdenhinkle** [comment]
How to trouble shoot the maintenance job
checking logs - where to check? sentry- what an error might look like
examples as they arise
look up by file path?
checking metrics - setup tud grafana - determining if things are healthy
What happens when the service is down - contact ops

**Comment by holdenhinkle** [comment]
I wrote the content for the following new sections of the Playbook:

- Sentry Error Logs For `vets-api`
- How to Manually Update the `tud_accounts` Table
- Daily Maintenance Job

I'll write the following sections in the morning:

- TUD is Down
- TUD DOMO Dashboard

**Comment by holdenhinkle** [comment]
I added content for these sections:

- TUD is Down
- TUD DOMO Dashboard

**Comment by holdenhinkle** [comment]
Google doc - https://docs.google.com/document/d/1xQ2m3eQzck8fWAZfTmKgar959N6sijB2BoRxvgcyr7g/edit?usp=sharing

**Comment by holdenhinkle** [comment]
Confluence document created - https://vfs.atlassian.net/wiki/spaces/TTT/pages/2003730467/TUD+SRE+Playbook

**Comment by holdenhinkle** [comment]
Contacted OPs about how to create additional basic auth credentials - https://dsva.slack.com/archives/CBU0KDSB1/p1638803036475400

**Comment by holdenhinkle** [comment]
Add new section - 'How to create new Basic Auth user credentials for TUD' - https://vfs.atlassian.net/wiki/spaces/TTT/pages/2003730467/TUD+SRE+Playbook#How-to-create-new-Basic-Auth-user-credentials-for-TUD

**Comment by pjhill** [comment]
Playbook is done!
