### ISSUE TITLE
Investigate Issue with the SHR

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#33378]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/context 
https://dsva.slack.com/archives/CU1E4CX9U/p1638290398215500

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Closing. Please re-open a new issue with detailed information if this is still needed.
