### ISSUE TITLE
Filter & Transform node-event_listing content ## Problem Statement

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#3338]
Our tome-sync data doesn't match up with our templates, and we need to follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2835) to ensure that the data will be compatible with our current templates.

## Goal
Content from `node-event_listing` entities match their corresponding entities from `pages.json`

**Comment by meganhkelley** [comment]
Is this transformer complete/who needs to validate before this ticket is closed?

**Comment by drorva** [comment]
@cvalarida close? If not, apply cms-transfomer label.

**Comment by swirtSJW** [comment]
Just to clarify the source data.   So for events, all the related events are found in `field_reverse_list`.  When it comes to the subquery that gave `pastEvents`  that comes down to looking at `field_reverse_list` keeping any that happen before the current time.   The content file knows nothing about the currrent time, so it can't sort them into the two piles the way the original graphQL did.

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/11543.
