### ISSUE TITLE
Calendar labels and navigation alignment are incorrect

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33389]
## Summary
The request calendar on the calendar page has day of the week headers (Mon-Fri). The alignment is incorrect on all responsive sizes.
The margins on the Next button also appear off.

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** Jacob

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/
2. Select Nutrition
3. Select Fort Collins

### Actual Result
1. Monday-Friday label alignment is incorrect

**Desktop**
![Screen Shot 2021-11-30 at 4.37.20 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/5815a9cc-5a57-4db4-be14-2a6ea9d8097b)

**Tablet**
![Screen Shot 2021-11-30 at 4.37.36 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/70849e10-6a39-4a83-ad50-e233112a129a)

**Mobile**
![Screen Shot 2021-11-30 at 4.37.51 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/548dbc17-fa2b-441b-bf35-dbffe2d0ad9d)

2. There's a little extra margin to the right of the next button
![Screen Shot 2021-12-01 at 10.50.41 AM.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/abf56806-934a-4851-a1dc-5b2a7b536c18)

### Desired Result
- Day of week text should be aligned with the day numbers
- Next button margin should be right aligned with the underline (like Previous is aligned to the left)
- Should match the specs:
  - [Request calendar (m/t/d)](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/p/E68B491D-ED59-4EF0-A4D2-73A161AE0632)

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by laurenernest** [comment]
@outerpress ready for UX review

**Comment by outerpress** [comment]
@laurenernest looks good!

**Comment by laurenernest** [comment]
@ptouchton Is this persistent focus state on click intentional? I don't remember it doing that before.
![Screen Shot 2021-12-09 at 8.45.06 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f866e329-4a4b-4e07-8d3e-ee667ec4e11c)
![Screen Shot 2021-12-09 at 8.44.52 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/22692fd0-7a11-47d5-b14b-33d6776c697e)

**Comment by ptouchton** [comment]
@laurenernest ..I didn't see this in my testing and I can't recreate the issue using the browser to emulate. Can you tell me what browser/mobile you are using?....Thanks

**Comment by laurenernest** [comment]
Mac, Chrome Version 96.0.4664.93
It might only be a desktop issue(?). I checked on a real mobile device and it didn't show up.

**Comment by ptouchton** [comment]
@laurenernest ...that style is an existing style from the vaos.css when the button is in focus.

**Comment by laurenernest** [comment]
Thanks! I'll find out if this behavior is expected for accessibility. Additional work for this is out of scope of this ticket so closing this one out as the issue described has been fixed and verified.
