### ISSUE TITLE
[Components and pattern standards] Design components or patterns don't align with Design System guidelines. (04.07.6)

### ISSUE THREAD

**Issue by AdamFreemer** [department-of-veterans-affairs/va.gov-team#33391]
#### VFS team name
Education Application (BAH)

#### VFS product name
Comparison Tool Redesign

#### Point of Contact/Reviewers
Ryan Thurlwell (OCTO Design Lead)

---

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
The alerts are not pushing content down when clicked. Instead they remove current content and replace it with the alert. This ticket is explicit to the functionality on the actual School Profile Page shown after clicking on Search result card.

### Other References
WCAG SC 3.2.4 AA

---

### Platform Recommendation
Either make the alert expand and push content down or consider using Leyda new expandable alert styles. See link for example

### Screenshot and Example

Example https://staging.va.gov/gi-bill-comparison-tool-sandbox/institution/21853035
![Screen Shot 2021-11-29 at 2.52.39 PM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/b0d41ae3-2beb-4172-b46c-6781d772a730)

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

**Comment by hallihocine** [comment]
Ticket has been validated in staging

https://user-images.githubusercontent.com/86266024/144498800-2f6a0d76-8443-4740-a82b-01306cb301fb.mov

**### Screenshots**

- Before clicking on the alert: 
<img width="1382" alt="Before clicking the alert" src="https://user-images.githubusercontent.com/86266024/144499003-07328714-6a95-48b0-bf9f-6ad08addf734.png">

- After clicking on the alert: the content under the alert is pushed down:
<img width="1398" alt="After clicking the alert" src="https://user-images.githubusercontent.com/86266024/144499358-e6e1ec31-6909-48a8-8de1-e65fdf9e28a6.png">

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2638&group_by=cases:section_id&group_order=asc&group_id=3070
- Test script/steps:
[[Components and pattern standards] Design components or patterns don't align with Design System guidelines. (04.07.6).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7644954/Components.and.pattern.standards.Design.components.or.patterns.don.t.align.with.Design.System.guidelines.04.07.6.xlsx)

**Comment by mrblanco1** [comment]
UATd during 12/06/2021's EDU/AFS Digital Engagement session.  Tammy approved.
