### ISSUE TITLE
How might VFS teams collab with Platform for External Services?

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#33413]
### Description
broken link in first item for "Active Directory Federation Services"

### Relevant URLs 

https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Service-Integrations.1889599494.html#ExternalServiceIntegrations-ExternalServiceIntegrations:

**Comment by lianilychee** [comment]
hi!  Thanks for flagging this, Mike Chelen.  The Platform Content/IA team will get to this as soon as we can.

**Comment by andreahewitt-odd** [comment]
@mchelen-gov I'm going through the backlog with @vbellissimo and I'm confused by this ticket. Is this about documentation for external services? Shouldn't we just be pointing to documentation they provide? I think it'd be really tricky to maintain documentation about something we don't own or iterate on.

**Comment by mchelen-gov** [comment]
@andreahewitt-odd Ok then issues need to be triaged to the appropriate team. Who owns this external service?

**Comment by vbellissimo** [comment]
@mchelen-gov @andreahewitt-odd I don't actually see any links being broken anymore. You're welcome to check this as well. If so, is it okay to close this ticket?
