### ISSUE TITLE
Update TUD GitHub OAuth implementation

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#33416]
Update GitHub OAuth callback to hit it new TUD (spa) endpoint instead of `vets-api`. Set `state` param.

State:
From https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#parameters
> An unguessable random string. It is used to protect against cross-site request forgery attacks.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/93

I have lots of this done. However, this update requires us to setup a CORS proxy. See https://stackoverflow.com/a/43881141

CORS error:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ebf2988f-0ff9-4196-8d0c-3f68e9122990)

**Comment by holdenhinkle** [comment]
WIP PR for updating `vets-api` per Fleet's idea - https://github.com/department-of-veterans-affairs/vets-api/pull/8557

**Comment by holdenhinkle** [comment]
PR for implementing GH OAuth with JWT and Proxy:
- https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/93/files

Gatekeeper Express app that acts as a proxy between TUD and GitHub OAuth:
- https://github.com/holdenhinkle/github-oauth-proxy

**Comment by holdenhinkle** [comment]
New OAuth Approach:

The new `/login` page has the following variables:
- `scope` - which is set to `read:user` and `read:org`
- `clientId` - which is set to the given GitHub OAuth App `client_id`
- `redirectUri` - which is set to a new endpoint in TUD, `/oauth`
- `state` - which is set to a randomly generated 10 character string

`state` is an unguessable random string. It is used to protect against cross-site request forgery attacks.

The user clicks a `Login` button with the above-mentioned values set as query params in link URL to the GitHub OAuth `login/oauth/authorize` endpoint - `https://github.com/login/oauth/authorize?scope=${scope}&client_id=${clientId}&redirect_uri=${redirectUri}&state=${state}`

GitHub then redirects the request to the `redirectUri`, `/oauth` with two query params: `code` and `state`.

The `/oauth` page does the following:

Grabs the `code` and `state` values from the query params. Checks the state value that was sent from GitHub against the state value that was generated and saved as a cookie.

If a value for `code` and `state` exists and `state` matches the generated value
- the query params are deleted
- the `state` cookie is deleted

A post request is then sent to `https://github.com/login/oauth/access_token` through the Gatekeeper app that acts as a proxy between the client and GitHub. The Gatekeeper app has the GitHub OAuth `client_id` and `client_secret`.  We include the temporary `code` to the request to the proxy, and then proxy then makes the request to GitHub withe the `client_id`, `client_secret`, and `code`. If the request is successful, GitHub responds with a `token`.

Using `token` we make a request to the GitHub api endpoint `/user/orgs` and make sure the user is part of the va org. If they are, we make a request to the GitHub api endpoint `/user` for the user's info, which in included their GitHub `id,` `name`, `email`, etc.

We then create a new `private_key` and `public` key pair, create a `jwt` with the users `id`, `email`, `login`, and `name` values as payload and sign it with the `private_key`. The `public_key` is then `base64` encoded, and the `jwt` and `public_key` are saved to local storage.

Finally, we redirect the `/` and has the following state values:
`{ authorized: true, currentUser }`

---

Upon each new request to all endpoints (`/`, `/help`/, `/login`, `oauth`) we call the `isAuthorized()` function which is imported from `src/utils/isAuthorized.js`, which grabs the  `jwt` and `public_key` from local storage, and verifies that the `jwt` is valid. `isAuthorized()` returns values from the `jwt` payload -- `{ id, email, login, name }` -- or `false`. If the response is 'truthy' (if the response includes the user object), the `authorized` state value is set to `true` if it's `false` and the `currentUser` state value is set to the returned user object if it is `null`. If the returned value is `false` we make sure `authorized` is `false and `currentUser` is `null`.

The `jwt` expires in an hour. When it expires, `isAuthorized.js` returns `false` and the user is required to login again.

Saving this...

Still in a work in progress...

**Comment by holdenhinkle** [comment]
I created a `/logout` page to handle the logout, because the TUD app as we inherited it isn't setup to track a logged in state at a high level.

If I add an `onClick` event to the 'Logout' button that calls a function like `handleLogout` then I can't update the `authorized` and `currentUser` states without reloading the page, using `window.location.reload();`. Again, this is a shortcoming of the current structure of the app. I opted for creating a `/logout` endpoint.

**Comment by holdenhinkle** [comment]
A note about refreshing the user's token (to keep the user logged in) and invalidating the user's token (for logout):

The logout and refresh github oauth endpoints aren’t available to clients right now (only servers):

GitHub:
> We are working on @octokit/auth-oauth-user-client to provide a simple API for all methods related to OAuth user tokens.

Here are all of the endpoints for app servers - https://github.com/octokit/octokit.js#app-server

I think my solution for logging out is okay (I just delete the JWT and PK from local storage).

I don’t think not being able to refresh the JWT before it expires is a big one. Users will just get logged out every hour. Logging back in is simple: you just click the login button and you’re almost instantly logged in (the code checks with github that you’ve granted access and you have already so there’s nothing to do, you’re just redirected home).

**Comment by holdenhinkle** [comment]
## To-do

Write notes in ticket - DONE

Refactor logout - DONE

Submit PR - DONE

Update callback in OAuth App - 

Requesting organization approval for OAuth Apps
 - https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

Submit request with ops to setup the proxy - 

Update the post request to new proxy url (dependent on new proxy) - 

Submit request for WASA scan -

**Comment by holdenhinkle** [comment]
12/20/21:
Jesse House:spiral_calendar_pad:  1 hour ago
Hi @Holden Hinkle - Thanks for bringing this to our attention. Typically, with requests like this, the approach is to evaluate them as a team so that they can be worked into an upcoming sprint. Right now it’s a bit of a special case since it’s a double-sprint for the rest of the year. That aside…
Can you provide the following in the issue?
When your team hopes to have this implemented
What initiative or larger effort this relates to
Thanks in advance for the info.
cc: @Joe Tice (edited) 

Holden Hinkle  1 hour ago
Hi Jesse, Thank you! Joe Tice is out for the next two weeks, just an FYI.
Here’s the info you requested:
When your team hopes to have this implemented:
=> If possible, by the end of this double sprint (Jan 4th) but if it’s not, might the end of the next sprint be doable (Jan 18th)?
What initiative or larger effort this relates to:
=> Post-MVP Release of TUD / Replacing TUD Basic Auth with GitHub OAuth
Please let me know if you need anything else. Thanks! (edited) 

Jesse House:spiral_calendar_pad:  31 minutes ago
@Holden Hinkle - That’s great info. Because of staffing and existing priorities, this will need to be picked up in the next sprint. The request seems clear, but we may need to reach out to clarify requirements.  Will you remind me as we get back from the break? I’ll set a reminder as well, but more can’t hurt :wink:

Holden Hinkle  29 minutes ago
Totally understandable, thanks. I’ll check back in with you in the new year.

**Comment by holdenhinkle** [comment]
Peter and Ryan Beckwidth both pulled the TUD OAuth branch down to test TUD. It didn't work for them while it's been working for me. Ryan Beckwidth and I paired on the problem on his machine because I couldn't replicate the problem on mine. He drove while I guided the session. It turns out that the value for `email` in the GitHub user profile was `undefined` or `null` for them (I can't remember which). I created a user object from some of the GitHub user attributes and saved it in the JWT payload. To verify the JWT, I also looked at the payload to make sure it contained the expected values. I had a validation in the code that each value existed (that it was truthy). It was failing because the value of `email` was `null` or `undefined`. I updated the validation to just check that the expected properties in the user object were present. Peter and Ryan pulled the update and TUD OAuthnworked for them.

I merged TUD, and got an issue:

**Issue 1**
The production value of `environmentSpa` is incorrect, as seen here:

```
https://github.com/login/oauth/authorize?scope=read:user,read:org&client_id=d9cdce0d74f2e4e4eeb4&redirect_uri=https://tud.vfs.va.gov//oauth&state=e4374b1bda
```

The `redirect_uri` should be `redirect_uri=https://tud.vfs.va.gov/oauth`, not `redirect_uri=https://tud.vfs.va.gov//oauth`.

Pic:
![image](https://user-images.githubusercontent.com/9326247/151239388-1fe25bd3-d769-4e5d-a9fc-4a7ea664c89b.png)

PR to fix it - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/106

---

Issue 2
For some reason TUD is redirecting some requests (301 redirect) to the same URL, but the `http` version instead of the `https` version at port `9000`.

Examples:

```
Request URL: https://tud.vfs.va.gov/oauth?code=3c5c4526d0066ba9f715&state=0798451501
Request Method: GET
Status Code: 301 
Remote Address: 127.0.0.1:2001
Referrer Policy: no-referrer-when-downgrade
content-length: 162
content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';
content-type: text/html
date: Wed, 26 Jan 2022 20:48:07 GMT
location: http://tud.vfs.va.gov:9000/oauth/?code=3c5c4526d0066ba9f715&state=0798451501
referrer-policy: no-referrer-when-downgrade
server: nginx
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

```
Request URL: https://tud.vfs.va.gov/login
Request Method: GET
Status Code: 301 
Remote Address: 127.0.0.1:2001
Referrer Policy: strict-origin-when-cross-origin
content-length: 162
content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';
content-type: text/html
date: Wed, 26 Jan 2022 21:06:43 GMT
location: http://tud.vfs.va.gov:9000/login/
referrer-policy: no-referrer-when-downgrade
server: nginx
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

I contacted Ryan Beckwidth and he is looking into this because this seems like a server-related issue. I also contacted Alexander Garcia:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ed30d6c1-f39b-441a-9337-289104610ef0)

TUD is currently not working.

## Several other small PRs related to the merging OAuth:

### Add trailing slash to Gatsby Navigate argument and to Link
Link - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/107

I noticed that direct entry into pages like `/login` were redirecting to `/login/`. I then read that Gatsby requires the trailing `/` - https://zenofreact.com/why-the-trailing-slash-gatsby/ So, just to be safe, I updated redirects and links to have a trailing `/`.

### Refactor login
Link - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/108

PR notes:
> It seems, in production (this wasn't happening locally), there's a race condition with `state` being set in the GitHub link vs the `state` value being generated. I noticed that it's sometimes appearing as `undefined`. This PR should fix that.

**Comment by holdenhinkle** [comment]
The redirect issue continues.

Joe, Peter, Ryan Beckwith and I attended Ops Office Hours on Friday to talk about the problem. Matt Leclerc gave Ryan some direction.

Here's the ticket for this issue - https://github.com/department-of-veterans-affairs/va.gov-team/issues/36136#event-5981444478

**Comment by holdenhinkle** [comment]
This was merged on Friday.

**Comment by pjhill** [comment]
This has been operating well for a week now. Thanks SO much for sticking to this! This is going to make a significant difference in usability for TUD.
