### ISSUE TITLE
Platform doc page should be indicate that TUD is not available yet

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#33429]
### Description
VA Platform Developer docs has a TUD page, but TUD is not available yet.
I wasted time trying to figure out why I could not get to TUD.  The doc mentions "be sure to have Host Wildcard proxy switching enabled for *vfs.va.gov " so i figured that was my issue.  I have no idea what "Host Wildcard proxy switching" is so I spent time googling around on that and trying to figure out what that screen shot "Switch Rules" is referring to,
Turns out the issue is that TUD is not available yet.

So I would suggest adding that info to the top of the page, and perhaps offer some additional context around the "Accessing TUD" and explaining the screenshot that seems to offer a way to "have Host Wildcard proxy switching enabled for *vfs.va.gov"
BTW, I finally figured out that that screen shot was for a browser proxy extension.  
I don't use a browser proxy extension, so I had no idea what the screenshot was referring to.

### Relevant URLs 
https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html

**Comment by lianilychee** [comment]
hi hi!  Gosh, thanks for flagging this @michelpmcdonald .  I'm gonna send this feedback to the TUD team.

**Comment by pjhill** [comment]
Hey, @michelpmcdonald , thanks for pointing this out. We've added a disclaimer to the top of the documentation to indicate that a wide-release of the Test User Dashboard has not occurred yet.
