### ISSUE TITLE
[Design] Auth Profile - Personal Info Revision -  Research pilot, recruiting

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33438]
## Issue Description
_Tasks needed in support of upcoming research project_

## Preparatory tasks
- [x] Review prototype
- [x] Share research plan and conversation guide with Lauren Alexanderson for approval and recruiting
- [x] Make note-taking spreadsheet
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Christina (Moderator)"
- [x] Run pilot
- [x] Debrief pilot
- [x] Revise conversation guide

## Acceptance Criteria (AC)
- [x] Pilot sessions complete; ready to run research sessions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - I copied a prep task list that Cindy uses, using her normal estimate as a starting point for you.  This appears to cover mock test, kickoff for recruiting, and your prep tasks ahead of the actual user study.

**Comment by MarciMcGuireGCIO** [comment]
This is currently blocked due to the Perigean contract ending

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske are there any tasks on this ticket that can be broken into a smaller ticket to work on between now and when you leave for the holidays?  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO scheduling/running/reviewing Pilot session(s) could be on their own ticket together along with revisions to Conversation Guide based on sessions. 

And perhaps the items regarding recruitment (Review recruited participant list for requirements met and Follow up with Perigean re participant list) could be grouped, as they both deal with making sure we're meeting recruitment recruitments and following inclusive research practices.

Most of the other items seem like small things that would be done right before or along with sessions - or generally throughout the research.

**Comment by MarciMcGuireGCIO** [comment]
Noting that I am breaking up this ticket into two parts since all of it cannot be completed by the end of Sprint 63 due to the holidays and vacation schedules.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - would this estimate be reduced since we peeled half the tasks out into a new ticket?  Thx!

**Comment by MarciMcGuireGCIO** [comment]
Pilot has been completed.
