### ISSUE TITLE
Update Punchlist for Representative

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33432]
Once this is in viewable in staging, outline all non-content changes in the content punch list (making one list)

**Comment by candy-gcio** [comment]
Updated based on screenshots from front end
- [Punch list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/Search-Appoint-PunchList.md)
