### ISSUE TITLE
Install DataDog APM for Vets API

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#33446]
For better insight into what's happening within the Vets API application, Application Performance Monitoring (APM) should be installed.

- [x] Investigate options.
  - DataDog APM - Should be considered first as we have 50 licenses for this.
  - Scout APM - This would be the cheapest option.
  - New Relic APM - A popular option but UI is less than optimal/intuitive.
  - Something else?
- [x] [Open DOTS issue](https://vajira.max.gov/servicedesk/customer/portal/1/group/3) requesting number of DD APM licenses needed. See [thread](https://dsva.slack.com/archives/C01U8EYHSEM/p1638475591017100).
  - According to Demian, one instance = 1 license.
- [x] Decide what environments we should monitor.
- [x] Create issues for testing, setting up, and installing chosen option.
- [ ] Create internal (VSP facing) documentation regarding APM if needed from a BE Tools perspective

## Related
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16919
- https://github.com/department-of-veterans-affairs/vets-api/pull/5774
- [Conversation](https://dsva.slack.com/archives/C028MUQV2TS/p1638200219003100) in #vfs-incidents
- [2021-11-29 Incident Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021/2021-11-29-autoscale-group-asg-cycle.md#action-items)

**Comment by ericboehs** [comment]
I talked with Chelen and he says we should try Datadog APM in a lower environment. Ideally, we should get this going on a review instance.

**Comment by LindseySaari** [comment]
DOTS issue [opened here ](https://vajira.max.gov/servicedesk/customer/portal/1/DOTSD-11198)

**Comment by LindseySaari** [comment]
Monday update: [PR opened here in the devops repo](https://github.com/department-of-veterans-affairs/devops/pull/10428) to add the DD APM env var and [PR to add DD Client to vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/8659)

**Comment by LindseySaari** [comment]
Thursday update: Ops is working on some issues around the datadog-agent. The app also seems to still not be sending traces. [See thread](https://dsva.slack.com/archives/CTYQL39FE/p1639678499121500?thread_ts=1639499702.475800&cid=CTYQL39FE) I've been working to re-deploy changes/detach instances to test as changes are pushed up, but the deletion/detachment process is somewhat timely.

**Comment by LindseySaari** [comment]
Monday update: Ops will be moving to staging for testing and Dev testing has proven successful. If everything checks out in staging, the plan is to turn on tracing for production.

**Comment by jsgarmon** [comment]
Dev and staging environments are successfully sending traces from vets-api workers and servers to the Datadog dashboard. Instances are not showing unusually high network throughput or resource usage.

No debugging was required in staging once this change was made. We expect promotion to production to go smoothly, but will monitor network/resource usage once deployed to check for impacts on workers and servers. Will start promotion once we get the thumbs up from @mchelen and/or @f1337.

**Comment by LindseySaari** [comment]
Cost implications for 50 DataDog licenses:

<img width="781" alt="Screen Shot 2022-01-05 at 1 55 37 PM" src="https://user-images.githubusercontent.com/5834818/148272984-7132b5f3-289a-45d2-aba6-0cd6d8f3dab0.png">
