### ISSUE TITLE
[SPIKE] URL Shortener

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33444]
Determine best way to build a url shortener.  Current url shortener fails often due to rate limits.  We need something that will scale.  
The use case is for VetText or us to be able to shorten a va.gov check in or pre check in url via an api.  There is no need for a UI component at this time. 

## Artifacts Needed
Proposed architecture diagram
Implementation plan

**Comment by jparker0425** [comment]
Linking Collab Cycle ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33988).

**Comment by acrollet** [comment]
I've uploaded an initial draft of a design doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md

cc @stephenBarrs, I've love to have a review when you're able.

**Comment by jparker0425** [comment]
@acrollet based on go/no go meeting we had, I was thinking of closing this ticket out and creating one for the work, and making an epic to place them in. What are your thoughts? Do we need this item open still?

**Comment by acrollet** [comment]
@jparker0425 sounds good altho maybe we can pair on creating the implementation tickets on Tuesday at some point? I'm thinking there will be at least a few rather than one "do the thing" ticket 🙂

**Comment by jparker0425** [comment]
Sure thing @acrollet! I will set some time on Tuesday for us to sync on this.

**Comment by acrollet** [comment]
Closing as the design doc was created and approved and implementation is in process.
