### ISSUE TITLE
Outdated or duplicative links

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#33450]
USER STORY

As a platform content team member,
I need to review this ticket to understand the issue,
so that I can have next steps for a solution

ACCEPTANCE CRITERIA

Recommend next steps to solve for this issue.

DESCRIPTION

### Description
https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Integrations.640909834.html#ExternalIntegrations-Morelinksandresources includes 2 links:

1) https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/VA-Systems/data-services-for-vsp-products.md#viers
this content appears outdated and also duplicative of https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Service-Integrations.1889599494.html#ExternalServiceIntegrations-ExternalServiceIntegrations:

2) https://github.com/department-of-veterans-affairs/devops/tree/master/docs/External%20Service%20Integrations
this duplicates the list and contents of https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Service-Integrations.1889599494.html#ExternalServiceIntegrations-ExternalServiceIntegrations:

### Relevant URLs 
- https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Integrations.640909834.html#ExternalIntegrations-Morelinksandresources
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/VA-Systems/data-services-for-vsp-products.md#viers
https://github.com/department-of-veterans-affairs/devops/tree/master/docs/External%20Service%20Integrations

**Comment by vbellissimo** [comment]
For content team: Not related to Q3 initiative

Needs further investigation

**Comment by amygoldman** [comment]
Some observations:

- None of these links are currently active on GitHub or the Platform website
- The initial page provided, https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Integrations.640909834.html#ExternalIntegrations-Morelinksandresources, contains links to the GitHub versions of the pages. It should be updated to link to the Platform website versions
- There's an External Service Integrations page in the Platform website Drafts space https://vfs.atlassian.net/wiki/spaces/PWD/pages/1889599494/External+Service+Integrations with many child pages
- - Follow up: Why is it there? Was there a launch-blocking issue found during deployment, or is it being worked on?

**Comment by amygoldman** [comment]
Update: sent @LindseySaari [a message on Slack](https://dsva.slack.com/archives/C01AS05BQ79/p1656690518587159) to find out why the External Service Integrations is in the drafts space

**Comment by amygoldman** [comment]
Update 7/1: 

- Response from Rachal Cassity: We are waiting for [vfs-backend](https://dsva.slack.com/archives/CTXGRFUNN/p1654261295371459) and [vfs-all-teams](https://dsva.slack.com/archives/CE4304QPK/p1654261269996359) to approve this document as well.

**Comment by taylojill** [comment]
11/1/2022 - Hi @RachalCassity @LindseySaari @laineymajor We would like to close this old ticket from Mike Chelen. The [page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/external-integrations) in question has been published. Can you update and/or remove the two links Mike referenced above? If updating, please link to the Platform website versions. Let me know if I can assist. Thank you!

**Comment by vbellissimo** [comment]
@mchelen-gov This page has been iterated on many times since this ticket was opened in 2021. I looked for the original issue documented here and could not find it anymore. I'm going to close this ticket but if you have any other questions regarding this content, let us know and we will look for a Platform subject matter expert. Thank you.

**Comment by vbellissimo** [comment]
@mchelen-gov Thank you. We will update the hyperlinks. Do you suggest the links are re-worded or does it make sense to keep them as "Upstream services used by Vets API"?

**Comment by mchelen-gov** [comment]
> @mchelen-gov Thank you. We will update the hyperlinks. Do you suggest the links are re-worded or does it make sense to keep them as "Upstream services used by Vets API"?

Probably rename to "External Service Integrations" to match the target page?

**Comment by vbellissimo** [comment]
Ok, great. We've just updated those links. Here is the [Confluence version of that page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations). The published version will reflect the changes later today after 3:30pm. Let me know if there's anything else we can correct on this page. Thanks.

**Comment by vbellissimo** [comment]
@mchelen-gov This has been published now. Thank you.
