### ISSUE TITLE
[SCREENREADER] Static templates shouldn't end main content container early

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#33459]
- [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## User Story or Problem Statement

As a user who uses assistive tech, I expect that the main content area contains all of the trailing elements (contact info, last updated, etc.), so that I'm able to receive this without having to exit the main content area and navigate into other containers which follow that same structure.

## Details

I noticed this while working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/31200. In this example template, the main content area ends so that the `contact_information` template can use markup & styling to achieve that full-width background color as seen in the screenshot.

https://github.com/department-of-veterans-affairs/content-build/blob/7d782fb348749c464f9a57d1f1df1103dc32234d/src/site/layouts/faq_multiple_q_a.drupal.liquid#L116-L121

https://github.com/department-of-veterans-affairs/content-build/blob/7d782fb348749c464f9a57d1f1df1103dc32234d/src/site/paragraphs/contact_information.drupal.liquid#L2-L5

I don't have a proposed solution that can be immediately applied, but I found [an example](https://css-tricks.com/full-browser-width-bars/#using-viewport-units) that uses CSS to achieve a page-wide background color while keeping the content in the same container.

## Acceptance Criteria

- [ ] Contact information ("Need more help") section is included with the main content area
- [ ] Contact information section still has the full-width background color
- [ ] Other trailing elements (`<va-back-to-top>`, "Last updated") are in the main content area

## Steps to Recreate

1. Look at the markup for https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement
1. Notice how semantically, the main content area extends down to include "Last updated", but this is not true in the DOM

### Annotated markup & page

![image](https://user-images.githubusercontent.com/2008881/144299132-68504c32-0ba2-421d-93ab-d89d17871ac0.png)

**Comment by laflannery** [comment]
This is correct - layout is marked up with landmarked appropriately. Closing
