### ISSUE TITLE
Update Vets API Synthetic Monitoring

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#33453]
Update uptime and latency alerting for api.va.gov.

- [ ] Determine if anything synthetic monitors are defined in Prometheus.
  - [ ] Remove any found and ensure they're in DataDog.
- [ ] Configure [this synthetic test](https://app.datadoghq.com/synthetics/details/zar-gsc-f3i?live=1h) to alert in #oncall.

## Related
- [Conversation](https://dsva.slack.com/archives/C028MUQV2TS/p1638200219003100) in #vfs-incidents
- [2021-11-29 Incident Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021/2021-11-29-autoscale-group-asg-cycle.md#action-items)

**Comment by zachclarity** [comment]
Monitors are defined here:  https://github.com/department-of-veterans-affairs/devops/blob/d4d16ec166bdb54735aa9d13b87866eecae749d5/ansible/deployment/config/prometheus-vagov-prod.yml
