### ISSUE TITLE
[Research] Training Environment Discussions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#33465]
Description:
Meetings and discussions on what we need to do for the training environment.

Tasks:
- [x] Prep for user journey meeting
- [x] Attend planning/user journey meeting

Acceptance Criteria:
- [x] Create list of UX needs

**Comment by julieadair1** [comment]
Notes:
We think these are the personas:
1. MSA Trainers (for training)
2. PO/Stakeholders (for demos)
3. Administrator (to manage test patients)

Use Cases
1. MSA training
2. Demonstrations to stakeholders
3. Administrative setup to enable 1 and 2 above

**Comment by kristenmcconnell** [comment]
We created [this Mural ](https://app.mural.co/t/vfscie8528/m/vfscie8528/1638369748490/bb07afd40b463ee1dfae4bca2ad68a1944a6b8e8?sender=uc940f53ad96ac0203d6d3631)to guide discusses on:
- what are the use cases/personas that the training environment needs to cover 
- what should the journey map look like for each persona. 

A cross-functional group from check-in met with Shawn Adams on Dec. 2 to fill out the Mural.

@julieadair1 and @jparker0425 are going to follow-up with Patrick on next steps, but it seems like the ask is for staging to mirror prod. If this is the case, then there is no further UX work needed related to the training environment. Will wait for final word from Julie and Corey before closing this ticket.

**Comment by kristenmcconnell** [comment]
We will need a UI to manage test users and schedule appointments. Look into what Insomnia currently does.
- See existing appointments
- Phone number changes
- Make appointments

Corey is going to talk to Katherine about VSE staging capabilities.

**Comment by kristenmcconnell** [comment]
This [Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1637700241469700) has VSE plans listed.

This [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1639516822299400) has the newest ideas on a training/testing environment. All of the proposed ideas don't seem to require UX work.
