### ISSUE TITLE
[Research] Planning for Team Splitting into Two Groups

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#33469]
Description: 
What is the structure of UX when we split into two groups? What is the overall structure? Sync with product and engineering representatives.

Tasks:
- [ ] Identify team members to meet with
- [ ] Meet with team members

Acceptance Criteria:
- [ ] Document a plan or recommendations

**Comment by julieadair1** [comment]
@dillo will assist

**Comment by Evafloyd** [comment]
@sarahknoppA6 is taking the lead on facilitating this ongoing process so I believe we can close this ticket for myself and Dillo as it will be a full team effort going forward.
