### ISSUE TITLE
Access for Antony Zimzores

### ISSUE THREAD

**Issue by azimzores** [department-of-veterans-affairs/va.gov-team#33463]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Antony Zimzores

### Your Email

antony.zimzores@libertyits.com

### Name of Your Team

Leeoroy Jenkles

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDReGJtNstoXpH0tYLl6b1IUMYv7mvQr1q+wDJJwItA1iFYqOr1snwbI6QHJFrYzAR5c7ouJHzDbd0RQu9xAyE4qw6sV0XcGdJjSUViGv1svLbA5SaqOo+ZheDaCoQAlmVXSNVgjZTCmzull9phmIzY0iPR7JD3mdep5gCI8zQApvun4DaPQT/Sy921Si6u2OFLm/dr4NmuJbFuuLKHkm0cgV/4WdEpYjGiLHZy6jmf5lsoCItBCM7RMUPMDqREW2SHMeLxnzK07ZwMdwo/CZd8eb2pZJTR22V1PRlHYQB8B79MdDS6VRSKfoCSJG8o8FUsOaidqtxG9a+WMwwwu9IwdC3wUrmTXjN0NoFMGRwX3zBRLS2CcS53Cvlb7PBiyTlhLCG45COzi1NNjk01GZ/SEn21Q9onH1ziQ4QvAiWcWtNGLYHsxqoyYwd9VOjXDcaBedGwWnBCBe9rtGTjXI1yAqyihXeKFvE8795ZPsIXb3CSGdLVKXda8S7dnIs/cUU= azuread\antonyzimzores@DESKTOP-TGLP4IC

### Desired AWS Services

Access to EKS, ECS, S2, EC2 and other standard services for the Leeroy Jenkles team.

**Comment by jbritt1** [comment]
### For AWS Access:

User: Antony Zimzores
Vendor: Michael Lovejoy
Approval needed: @mchelen-gov

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Note: Please allow 5-10 minutes for the changes made to be deployed**

**Comment by mchelen-gov** [comment]
@azimzores who is your PM?

**Comment by mchelen-gov** [comment]
No EQIP record found, please contact your COR and PM.

**Comment by golavarr-va** [comment]
@mchelen-gov Antony's EQIP is in progress. His COR is Cecilia Lee. Is this enough to provision AWS access?
