### ISSUE TITLE
Adding [Tyler Watkins] to DSVA Slack

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#33466]
# Description

Please add tyler.watkins@accenturefederal.com to DSVA Slack.

<describe the request>

Are you requesting to add an individual as a:

**- Full member**

Tyler is an Accenture Federal Services team member who works with the SalesForce team where it integrates with the GI Bill Feedback Tool on VA.gov. Please provide him access so that he can communicate with the necessary platform teams when he needs assistance. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
