### ISSUE TITLE
Access for Wesley Rowe

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#33480]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Wesley Rowe

### Your Email

wesley.rowe@agile6.com

### Name of Your Team

CMS - Sr. Product Manager – Agile Six

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoPSkW4MZx6FhPAC3CN7HPZNvk6ylBmm1IwHRG8NGsM0GmlqeIK+osizuG5awXQQh3CVn+b2F0cksrYNdcYh4iFmiP85PArIq3nutCG63CqYvyDPSaLixevdpRXatL96EFYuzhWeu9GkmRoUvnQ3lLvX5HLXSZEUUXPN0XLdD357CFdHlo+PKphn0yhk8cwvm5wy7FO/h94KEMLKHbK/np+yIN4Rz2HIcJgbXomwZf7DfpCBQIIepgxNArYRjHZAaPqYNwKmhqRlwrREhervmJVwrAFrp5JaQ9+10lz3M7pUuEHLm5w7bp7eX6xveLNR9S83qP8AKwaPnQ1UN+NIB+yYocPhoH+y3ixUCtF3J0AwVJC/t5Lx8fgMDWRHaL4H0hCfcHEAfrf0UGct745UiSWaEsX12hKSDbLXM29JMn3Ra6EoQeKtyXCr88sxT3Jw6ODy2HlKF85k/ZiT+vi8kQryJgD2sl080SLoofBNCd+BqotWedhV+/7DDc5NEDeRE= wesley.rowe@agile6-as-MacBook-Pro.local

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
