### ISSUE TITLE
Access for Kris Pethtel

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va.gov-team#33481]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kristopher Matthew Pethtel

### Your Email

kris.pethtel@adhocteam.us

### Name of Your Team

VA Mobile

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4L6lzE08khFo6OvH3/mWg3Xe2d6KHzr9PHNwj1J1XT+h3xW6IZJY81eig1CNBQVRGk6nQ38U5Hj7PLnwC1JCVtJ2oKjmb1ytIpQ/u4MagXLo/X6wI7jzqsSGu79I4p/U46qa0WFP/IhzWTEds29qL7DY2cKRSDDA3WT9Vw1R9bp6J6SdF6SQY55vcHzhTGHBASwqluHmrNfF2q2jFNqOFc86NPlSqGOlpaAzpkwdc+EMZMJ7NPbrS6ExlW26V4uidiCfDYdGi5HQFp7pOlFrJNKQ6RkhziRtctCE9wQL68ijaZSR0M7gv5HOUk4Ezw4kJvrsg1N1AZ+jm9XZk5gDW3F587yz9sk0Fqy4Y3E0AU0i9wUgDc+/FVYFH7Ps7lcnh6lHIt58mVAfN8tNG93loa9y07OjZ4jgu7Dgt8x+vGW3DqlG8LECjlpIAjadft8MdKtncm/blxiQnhSqxin6t/zpiEcliA+1MxrXVEjFmJEcPNtg5eTDCYlubDhS506s= krispethel@Kris-Pethtel-MacBook-Pro.local

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
