### ISSUE TITLE
[Discovery] Determine how to handle Modal React dependencies inside web component

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33489]
## Description
The way the Modal React component is currently developed is very dependent on React features. We need to figure out how we can develop it as a web component outside of the React ecosystem.

## Notes
Some examples of web component modals:
- [Adobe Spectrum](https://github.com/adobe/spectrum-web-components/tree/main/packages/modal)
- [Ionic](https://github.com/ionic-team/ionic-framework/tree/main/core/src/components/modal)

## Acceptance Criteria
- [ ] Research how to the React Modal to a web component
- [ ] Create a plan for getting the work done. Add details to #30138. Create additional cards as necessary.

**Comment by bkjohnson** [comment]
The specific dependency is `react-focus-on`:

https://github.com/department-of-veterans-affairs/component-library/blob/4a7c522fe2f21d8ba0e7b0bea795fe0d959a2a0c/packages/react-components/src/components/Modal/Modal.jsx#L4

And the `returnFocus` prop that may change behavior:

https://github.com/department-of-veterans-affairs/component-library/blob/4a7c522fe2f21d8ba0e7b0bea795fe0d959a2a0c/packages/react-components/src/components/Modal/Modal.jsx#L157

We'd need to know:

1. What that dependency is doing
1. How to accomplish those things in a non-React environment

**Comment by k80bowman** [comment]
Just some background on `react-focus-on`... it is a package that combines [`react-focus-lock`](https://github.com/theKashey/react-focus-lock), [`react-remove-scroll`](https://github.com/theKashey/react-remove-scroll), and [`aria-hidden`](https://github.com/theKashey/aria-hidden). 

`react-focus-lock` is based on [`focus-lock`](https://github.com/theKashey/focus-lock/). It also says in the documentation that it provides vanilla JS solutions (but it doesn't say more than that).

`react-remove-scroll` might be able to be replaced by [`body-scroll-lock`](https://www.npmjs.com/package/body-scroll-lock).

`aria-hidden` is not React-specific.

It is probably worth doing some searching to see if there is a vanilla JS solution that combines these three aspects into one the way `react-focus-on` does. The advantage to using `react-focus-on` for React modal components is that, while it combines three packages, it is also optimized and smaller than using the three individually. If we do need to go the individual route, we'll want to watch our package size.

**Comment by andresriveratoro** [comment]
`react-focus-on` provides:
- traps focus - keyboard focus management - limits keyboard navigation to modal
- prevents scrolling outside of the modal
- traps voice reader - limits voice reader to modal

## Keyboard focus management
We need to make sure that keyboard navigation is limited to the modal. This means using the keys `TAB` or `SHIFT+TAB` should move the focus to the next or previous element inside the modal. The focus cannot move to elements outside of the modal. This is referred to as focus trapping and is provided by `react-focus-lock`.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role#required_javascript_features and https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html cover the keyboard navigation behavior. 

Related packages:
**https://github.com/theKashey/focus-lock**
https://github.com/focus-trap/focus-trap

## Disable scrolling for content outside of modal
We need to make sure that we limit scrolling to the modal. Any content outside of the modal should not be scrollable. 

Related packages:
**https://github.com/willmcpo/body-scroll-lock**
https://github.com/FL3NKEY/scroll-lock

## Trap voice reader
We need to make sure that the voice reader is limited to the modal. This means that only content in the modal should be read by the voice reader.

Related packages:
**https://www.npmjs.com/package/aria-hidden**

## Recommendation
Katy was spot on with her alternative package recommendations. I have been unable to find a vanilla JS solution that includes all the features listed above in 1 package. The packages that we should move forward with to include this functionality are in bold.

**Comment by k80bowman** [comment]
Thank you for looking into this, Andrés!
