### ISSUE TITLE
Build OMBInfo web component

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33491]
## Description
Build a web component version of the OMBInfo React component. This work is dependent on the completion of #30138, since this component uses the Modal component.

## Acceptance Criteria
- [ ] Build an OBMInfo web component
- [ ] Add OMBInfo web component to Storybook
- [ ] Add tests
- [ ] submit component for [Staging Review](https://vfs.atlassian.net/wiki/spaces/DST/pages/1998192674/Staging+Review+process)

**Comment by bkjohnson** [comment]
Closing as finished: https://github.com/department-of-veterans-affairs/component-library/pull/491

Staging review is now part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/986
