### ISSUE TITLE
Manual Functional Testing: Create Test Fail Rate Visualization

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#33495]
As a stakeholder, I'd like to be able to see what percentage of my tests in testrail are resulting in failures vs how many total test runs I've made.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1144715840

This one's all set. Starts at a product level and drills down to individual tests.

**Comment by pjhill** [comment]
This is a pretty great high level visualization and the bottom level drill down is great as well!
