### ISSUE TITLE
MAS can't locate an appointment by ID 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33493]
When MAS can’t locate an appointment by ID, it returns a 404. If this happens when a client is trying to cancel an appointment through the vaos-service, the client gets back a 500 due to a NPE. 

If MAS can’t locate an appointment by ID, then VAOS should also return a 404. 

Reference: [JIRA ticket 2728](https://issues.mobilehealth.va.gov/browse/VAOSR-2728)

**Comment by grossb1** [comment]
Closing dup of #33276
