### ISSUE TITLE
Discuss Future of MegaMenu

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#335]
We need to discuss the future of the MegaMenu. As of right now the way it works in vets-website is very complicated. There have been suggestions to make this only in vets-website and not in a componenet library. Which mean that it will not be reusable. Initially it was thought that the MegaMenu would be something that can be used on other application. Now that it has been implemented we need to discuss the future of what we want to do with it. 

Trying to implemented the header section on another application was a real pain. The code is very dependent on vets-website specific code. We would need to rethink it to make it modular if we want to go that route.

**Comment by timwright12** [comment]
would like to roll this into a full rebuild of the header/footer
