### ISSUE TITLE
Manual Functional Testing: Create # of user stories verified by test cases visualization

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#33502]
As a product stakeholder, I'd like to be able to see how many user stories my manual functional testing is verifying. This will help determine if we are using manual functional testing effectively to address our issues.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1950369682/kpis/details/1339791027

All good here

**Comment by pjhill** [comment]
This is... pretty cool. I kind of love seeing this. We may have to do some data quality checks and make some tweaks in the future, but this is awesome.
