### ISSUE TITLE
Campaign Landing Page (CLP) Intake Process Review

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33504]
## About your support needs 
With the initial launch of CLPs, we identified gaps in the intake process and need to explore new ways to better align CLP requests with the proper teams for intake, triage and support.   This ticket serves as a place holder to kickstart discussions and review process for CLP intake actions.

Discussions / Decisions will be outlined in the attached word document -- [PENDING].

### Current Process Flow / Governance Product Guide
[VA.gov.Campaign.Landing.Page_Governance_Product_Guide_11302021.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7643379/VA.gov.Campaign.Landing.Page_Governance_Product_Guide_11302021.pptx)

### Desired End State 
Establish a turnkey intake process in place Q1 2022 that allows business lines (approved CLP Stakeholders) a quick and efficient request process that accounts for a triage and support process to ensure quality and timely CLP build actions in support of VA Marketing campaigns forward.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA @bethpottsVADEPO Do you know if this ticket/request is still viable? Thanks!
