### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by julialeague** [department-of-veterans-affairs/va.gov-team#33519]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: julialeague
- Reason access is required: My team (VA OCTO Hypertension Rapid Ready For Decision) want to have access to monitor our Sidekiq worker in `vets-api`

**Comment by ericboehs** [comment]
✅

**Comment by julialeague** [comment]
I'm in! Thanks @ericboehs
