### ISSUE TITLE
[Outreach & Events MVP/Filtering, Recurring Events Enhancement] VSA-QA Test Plan

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33513]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: \[[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)]
- Product/Feature Epic: \[Product EPIC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28918)
- Product/Feature Copy deck(s): \[[Product Features Copy](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts)]
- Product/Feature Design prototypes: \[[Product Design Library](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/design)]

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Cassandra Allen
Content/IA: Sitewide Content Team
Front-end: Kelson Adams
Back-end: N/A
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \[Outreach & Events Product Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts/Product%20Use%20Cases.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by brianalloyd** [comment]
@tlei123 just FYI we moved up our staging review to this Friday 1/7/2022, mainly so Kelson can be present and support before he leaves contract on 1/11.  Let me know what questions you have on the test cases for QA and how we can support and enable the process.  Thanks.

**Comment by tlei123** [comment]
@brianalloyd , i've completed test-runs for the in-scope cases except for recurring events.

@kelsonic , please let me know where recurring events can be tested.  [Brian mentioned some kind of Drupal environment yesterday.]  Thanks much!  :)

**Comment by tlei123** [comment]
@brianalloyd , I've completed all MVP test-runs EXCEPT for Recurring events\*.  QA-artifact links are below, and will also be in Staging Review ticket #34622.

One defect [duplicate] logged so far: #34762

- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=3088)\*
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/2639)\*
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/289)\*
- [Summary (Defects) report]()\*

\*Recurring events test-case still Untested, pending Drupal environment availability & access instructions from @kelsonic .

**Comment by tlei123** [comment]
@brianalloyd , Recurring-events test-runs completed [Mac Chrome & Firefox only, due to SOCKS-proxy requirement], and Summary (Defects) report link is below \[and also updated in Staging Review ticket #34622\].

Defect #35392 logged.

- Final [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/291)

**Comment by brianalloyd** [comment]
Thanks @tlei123 we'll scrub into this issue soonest.  Thanks for the support.

**Comment by brianalloyd** [comment]
@srsuddath let's prioritize defect ticket mentioned above for action.

**Comment by brianalloyd** [comment]
Closing this ticket as work is completed for above mentioned defect.
