### ISSUE TITLE
Pivot from Newsletter - Update the initiative release checklist

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#33517]
## Issue Description
Currently, the initiative checklist indicates that Platform teams should post announcements to #vsp-service-design for the Service Design team to coordinate external communications.  The checklist should be updated to indicate that Platform teams are responsible for communicating with VFS teams about their initiative or product change, and include a link to the Guidelines for Platform communications to VFS teams.

Purpose: Set expectations for how, where and when Platform teams will provide VFS teams information about changes to establish consistent and reliable communications. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
2/16/2022:
Closing this since it is not prioritized for now.
