### ISSUE TITLE
Define Use Cases - American Indian Question 10-10EZ 

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#33516]
_The purpose of this document is for designers, PMs, and engineers to align early on on potential use cases and edge cases so these things aren't coming up randomly and late in the process. We recommend the team schedule a 30 minute meeting to brainstorm all use cases/edge cases early on.  Examples of cases that could be captured here include: "Veteran logs in but is not LOA3ed.", "Veteran searches and gets no results." etc etc_

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product/product-outline.md)
[Design](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6)

</details>

## A. Authenticated Use Cases and Scenarios: without pre-populated data
* **Description** Check for correct text display and button functionality:   
       - Does the American Indian question appear on the 10-10EZ on-line application form as per design mock (after after the race, ethnicity, origin question)?
       - Does clicking the drop-down button next to "What it means to be recognized..." display appropriate additional text?
       - Do the "Yes" and "No" choices display correctly and allow for only one option to be selected? (Will this be a required field? If not, how does it  work if you click “Yes” and then decide you don’t want to answer – does clicking outside the radio button remove selection?)
       - Does an error message display if user selects "Continue" without choosing "Yes" or "No"? (What is message – “This field required”?)
       - Does selecting the "Continue" button take user to next screen?
       - Does the "Back" button take user back to previous screen?
       - Can user opt to “Finish this application later” and see confirmation that the app was saved along with button to “Continue your application”

##  B. Authenticated Use Cases and Scenarios: with pre-populated data
* **Description** Check for correct text display and button functionality:   
       - Does the American Indian question appear on the 10-10EZ on-line application form as per design mock (after after the race, ethnicity, origin question question)?
       - Does clicking the drop-down button next to "What it means to be recognized..." display appropriate additional text?
       - Do the "Yes" and "No" choices display correctly and allow for only one option to be selected? (Will this be a required field? If not, how does it            work if you click “Yes” and then decide you don’t want to answer – does clicking outside the radio button remove selection?)
       - Does an error message display if user selects "Continue" without choosing "Yes" or "No"? (What is message – “This field required”?)
       - Does selecting the "Continue" button take user to next screen?
       - Does the "Back" button take user back to previous screen?
       - Can user opt to “Finish this application later” and see confirmation that the app was saved along with button to “Continue your application”

##  C. Unauthenticated Users
* **Description** Check for correct text display and button functionality:   
       - Does the American Indian question appear on the 10-10EZ on-line application form as per design mock (after after the race, ethnicity, origin question question)?
       - Does clicking the drop-down button next to "What it means to be recognized..." display appropriate additional text?
       - Do the "Yes" and "No" choices display correctly and allow for only one option to be selected? (Will this be a required field? If not, how does it            work if you click “Yes” and then decide you don’t want to answer – does clicking outside the radio button remove selection?)
       - Does an error message display if user selects "Continue" without choosing "Yes" or "No"? (What is message – “This field required”?)
       - Does selecting the "Continue" button take user to next screen?
       - Does the "Back" button take user back to previous screen?
       - Can user opt to “Finish this application later” and see confirmation that the app was saved along with button to “Continue your application”  - Unauthenticated User:

**Comment by MickinSahni** [comment]
- submitted one before, can they start a new one
- unauth path
- auth path 
- auth path + prefilled
- American Indian question available

**Comment by MickinSahni** [comment]
Reached out to Tze re: scope of use cases. Waiting for feedback

**Comment by tlei123** [comment]
hi @SKasimow !  The Use Cases look pretty good, and should all be in-QA-scope.  Below are just a few things for follow-up...

- **Description**: No need to include interactive/implementational details; that's what I'll flesh-out in my test cases in TestRail.  [But thx for saving me some work there!  :D]  Just a brief description of the distinct user-flow for each Case would be enough.  Feel free to ping me going forward if you encounter another update this small.
- **Designs**: IF you got one from your Designer, please add above.  IF not, that's fine as long as I get a link to the **copy deck**.
- **Test-accounts**: Please provide one each for Cases A & B above.

Thanks much for getting these Cases together!  I should have time tomorrow to get started on TestRail test-cases -- I'll keep you posted.
