### ISSUE TITLE
Pivot from Newsletter - Coordinate timing of Slackbot and other channel reminders

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#33518]
## Issue Description
Tuesdays are the busiest days in #vfs-all-teams (ToT reminders, follow-ups, SLO reports, etc.).  Coordinate channel messages to ensure reminders about business process and procedures (threading responses, analytics opt-out, etc.) aren’t overlapping with important announcements about Platform changes.

Purpose: Ensure important announcements aren’t getting lost in the noise in #vfs-all-teams.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
2/16/2022:

Closing this since it is not prioritized.
