### ISSUE TITLE
Discovery: Verify Analytics/Logging when Adding New Questions to 10-10 Forms

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#33528]
## Issue Description
The 10-10 team needs to verify how Domo is ingesting data from Google Analytics as it relates to all questions for 10-10EZ and 10-10CG to determine whether analytics needs to be requested for future form questions/configurations. 

## Acceptance Criteria
- [x ] Verify how Google Analytics is set up to track data at the question level, page level, form level

**Comment by SKasimow** [comment]
@jchilders @MickinSahni @lzapson @Dene-human - I checked with the Analytics team on what needs to happen to capture analytics when new questions are added to the 10-10 forms:

> If it's using the Design System Component then you'll just need to enable those checkboxes/text areas for tracking by passing in the questions and/or answers along with the event using our [data layer specs](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) If the questions will be on additional URLs and your funnel will be changing, we will need a ticket to update the dashboard.
