### ISSUE TITLE
Contact Center Review - American Indian Question, Medicare Claim Number Field, and Self-Identifying Gender Identity 10-10EZ [DRAFT]

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#33525]
# Request the Contact Center Review 

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
10-10EZ Application form for VA Health Care benefits. 

### Launch Date
*Please provide the launch or rollout date and details.*

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
*Please provide product guide link*

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by hdjustice** [comment]
@markfallows  We need to ensure the guide gets updated before August 8th for this one.  We can work on it next sprint.

**Comment by hdjustice** [comment]
American Indian question has been removed, per Business Policy.  The Self-identifying Gender Identity question is still on hold pending business decisions.  Medicare claim number field will be updated with Household Section Optimization guide updates
