### ISSUE TITLE
Perform Accessibility Review - American Indian Question 10-10EZ

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#33524]
Collab cycle accessibility [testing guide.](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) 

---------

# Accessibility staging review preparation

Teams must conduct their own accessibility testing **before** scheduling a DEPO Platform Collaboration Cycle [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review). DEPO Platform accessibility specialists will verify teams have completed foundational accessibility testing before the staging review can start. Teams are **required** to complete the [foundational accessibility tests](#foundational-accessibility-tests-required) and encouraged to complete as many of the [advanced accessibility tests](#advanced-accessibility-tests-recommended) as time and techincal proficiency allow.

If teams have not completed their foundational testing, DEPO Platform will escalate to DEPO leadership.

Staging reviews test the [happy path](https://en.wikipedia.org/wiki/Happy_path) through the application or content page(s). This may not catch all accessibility issues, but will ensure basic functionality is accessible. (Accessibility specialists conduct a [more thorough post-launch audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) when an application is relatively code-stable in production.)

## Foundational accessibility tests (required)

- [x] Axe scans in daily development - [read more about the axe browser plugin](#axe-scans-in-daily-development)
- [x] Axe scans included in end-to-end (e2e) tests - [read more about e2e tests with axe checks](#axe-scans-in-end-to-end-tests)
- [x] Color tests for proper contrast and colorblindness - [read more about contrast and colorblindness](#color-tests)
- [x] Content zoomed to 200%, 300%, 400% - [read more about zoomed layouts](#content-resize-check)
- [x] Keyboard navigation - [read more about navigating with the keyboard](#keyboard-navigation-check)

## Advanced accessibility tests (recommended)

- [x] Screen reader tests (VoiceOver + Safari or NVDA + Firefox) - [read more about getting started with screen readers](#screen-reader-tests). Teams are encouraged to conduct their own screen reader tests as part of the software development lifecycle (SDC). _DEPO Platform acknowledges this testing is aspirational._
- [x] WAVE tool spot checks - [read more about the WebAIM WAVE tool](https://wave.webaim.org/)

**Comment by hdjustice** [comment]
I ran NVDA on the [American Indian question page](https://staging.va.gov/health-care/apply/application/veteran-information/american-indian) and it went through with no issues.  I have requested Tiffany Pender (Shared Services team) to run through it with VoiceOver to be sure we didn't miss anything.

**Comment by hdjustice** [comment]
I ran Colorblindly and WCAG Color contrast checker with no issues - No color changes were made as part of this additional question

**Comment by hdjustice** [comment]
I tested at 400%, 300% and 200% zoom levels, as per instructions on how to test with zoomed layouts.  No scrolling or odd text configurations appeared.

**Comment by hdjustice** [comment]
I tested keyboard navigation.  The tab focus flows from the breadcrumb link to the accordion link, to the radio buttons, to the Back button then to the Continue button.  All other tab orders remain the same on the rest of the page.  The arrow buttons allow for changes to be made to the radio button selections.
