### ISSUE TITLE
[Design] Adding a cancel appointment action link to the confirmation details screen

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#33529]
When a user is in the new appointment workflow and confirms the appointment, the confirmation details screen does not show the cancel appointment link. The veteran should be able to cancel an appointment on the page. 

Example: 

![New_Direct_Schedule_Flow.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/860aa474-9cb6-4afd-8879-9b867fcf4f6c)

The existing page details for the appointment details screen has the ability to cancel. The user experience should be the same for both workflows. 

Example: 
![Direct_Schedule_Flow.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/d725a872-b0f2-4a5c-8ffe-423449d5570d)

**Comment by outerpress** [comment]
In dev ([33330](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/33330)), closing
