### ISSUE TITLE
Update release plan template to include documenting current functionality

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#33534]
## Details 

As a Platform team member, I need to fully understand the supported functionality of a Product that I am iterating on, so that I can properly test it and lower risks of iteration. 

Coming out of [postmortem for callback issue](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-11-24-content-release-govdelivery-callback.md)

## To Do 

- [ ] Determine which Platform template includes reference to manual QA 
- [ ] Update to include that manual QA should rely on a robust test plan that has documented current supported functionality (if that functionality is not currently documented, that must be done as part of the release of a feature)

**Comment by laineymajor** [comment]
@ndsprinkle does this fit into anything you're currently reviewing/working on?

**Comment by jhonnyoddball** [comment]
Logged over a year, platform focused. Closing
