### ISSUE TITLE
[BE][MuleSoft] | Adding Credentials to Rails/Mulesoft Service  

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#33538]
Submitting form data and/or attachments to CARMA/MuleSoft will require passing `client_id` and `client_secret` headers as part of an HTTP POST. 

## Expected Behavior

This ticket covers storing reading credentials in rails service and passing to Mulesoft. 

## Acceptance Criteria

[x] The `client_id` and `client_secret` values are read from the application settings
[x] Client id and client secret  are passed to Mulesoft as part of the http header

**Comment by MickinSahni** [comment]
Hey @dillo assigning you as well to this ticket since the team doesn't have access to AWS right now

**Comment by SKasimow** [comment]
Closing....Janes and Sharon reviewed ticket for completeness.
