### ISSUE TITLE
Access for Chikaodi Adibemma

### ISSUE THREAD

**Issue by cadibemma** [department-of-veterans-affairs/va.gov-team#33532]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Chikaodi Adibemma

### Your Email

chika.adibemma@adhocteam.us

### Name of Your Team

VA Mobile API - Backend Software Engineer - Ad Hoc

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need AWS console access to proceed with MFA setup

**Comment by jbritt1** [comment]
### For AWS Access

User: Chikaodi Adibemma
Vendor: Michael G. Lovejoy
Approval needed: @mchelen-gov

**Comment by mchelen-gov** [comment]
@jbritt1 EQIP transmittal date confirmed, request approved :thumbsup:

**Comment by jbritt1** [comment]
First time login credentials for AWS provided to user at this time.
