### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by NatashaJIbrahim** [department-of-veterans-affairs/va.gov-team#33536]
Access to the Sidekiq Admin UI is managed through a GitHub team under the department-of-veterans-affairs/va.gov-sidekiq team. Please provide your GitHub username to be added to that team, along with a reason access is required.

GitHub username: NatashaJIbrahim
Reason access is required: My team (VA OCTO Hypertension Rapid Ready For Decision) want to have access to monitor our Sidekiq worker in vets-api

👋 Me too please. Thank you!

**Comment by ericboehs** [comment]
✅ Done

Give https://api.va.gov/sidekiq a try.
