### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by tadhg-ohiggins** [department-of-veterans-affairs/va.gov-team#33535]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: tadhg-ohiggins
- Reason access is required: My team (VA OCTO Hypertension Rapid Ready For Decision) want to have access to monitor our Sidekiq worker in `vets-api`

**Comment by ericboehs** [comment]
✅ Done

Give https://api.va.gov/sidekiq a try.
