### ISSUE TITLE
Alignment issues on 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#33546]
Label should be aligned with field

### Military Service
![Screen Shot 2021-12-02 at 4.48.39 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d70cc7a8-58c0-4693-ac80-31c0d5672e7d)

### Medicare
![Screen Shot 2021-12-02 at 4.47.38 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/27aaffa1-4aa0-4a3b-96fb-aea874f33c56)

**Comment by markfallows** [comment]
Need to review whether this issue still exists.

**Comment by markfallows** [comment]
Issue has been resolved.  @hdjustice to add screenshots and close the ticket.

**Comment by hdjustice** [comment]
Confirmed both Military Service and Medicare Effective date screens are showing good alignment

![image](https://user-images.githubusercontent.com/92328831/175123176-f319a153-672b-4588-b0f5-b0bbf02e85d4.png)




![image](https://user-images.githubusercontent.com/92328831/175123058-f6c0c3a2-1e76-4c70-8383-01bec47c830a.png)
