### ISSUE TITLE
Add null check for ineligibilityReason

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#33544]
This is to address the issue Marcy was having when trying to schedule an new appointment with Jacqueline Morgan.  Marcy would encounter an error after selecting a va facility.  This would eventually result in a call to the v2 patient eligibility endpoint that returns, among other things a list of ineligibility (coded) reasons.  However, if that list is blank the service does not return a list of ineligibilityReasons at all and the code was assuming that it did resulting in the read of a null field and hence the error.

The fix is to do a null check on that field prior to reading it.

**Comment by jenniemc** [comment]
Bug reported on https://dsva.slack.com/archives/CMNQT72LX/p1637697637123900

**Comment by ldelacosta** [comment]
@marcynadeau - This ticket is ready for testing. Please let me know if you have any questions. Thanks!

**Comment by marcynadeau** [comment]
Retested and passed.  
Select Start Scheduling, Select Amputation, Select More Sites, Select Cheyenne
Expected Response:  List of Locations Display
Actual Response:   List of Locations Display. 
Note, I have enabled other types of care for Cheyenne and Dayton for Direct Scheduling and Requests. And other types of care are working as expected.

**Comment by ldelacosta** [comment]
Closing out the ticket. Was validated and it was successful.
