### ISSUE TITLE
[BE][MuleSoft] Add new service to submit 10-10CG to MuleSoft

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#33540]
### Description
The API components used in submitting 10-10CG form data and attachments to CARMA need to be updated. Creates a new service which submits 10-10cg form and attachment data to Mulesoft.

- [x] Use Flipper to determine whether to submit to MuleSoft or SalesForce (the existing submission scheme)
- [x] Ensure `client_id` and `client_secret` are used for authentication

## Assumptions
- MuleSoft is successfully updating the CARMA DB

## Acceptance Criteria

- [x] Unit Testing 
- [x] Verify payload with local submission
- Note: as we ramp up traffic to MuleSoft, we'll see in logs the transition away from SalesForce

**Comment by SKasimow** [comment]
Per @jchilders - we can close this out; work completed. If new issues arise we will address in new tickets.
