### ISSUE TITLE
 CC update selected provider preference card

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33553]
## Description
Currently in VAOS, the distance of a provider's address relative to a reference location is used to sort options for a user to select from. Once a selection is made, the distance information is not relevant. We should not show information that no longer helps the user in the flow.

Current state preference selected
![33553 scope1.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/31b865c2-feb4-4261-b139-2c0a8f00c536)

Current state remove preference modal
![2Screen_Shot_2021-12-02_at_2_37_50_PM.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/6998df3a-1803-4c2a-ad3b-32822be64877)

---

### AC1 - Preference selected
Given any user on the CC provider preference page
When user makes a provider preference selection
Then show selected provider's name and address
And page design matches the design spec
And card heading is sentence case (see [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-provider-preference.md#33553)) 

### AC2 - Remove preference modal
Given any user on the CC provider preference page with a selected provider
When user selects remove
Then show removal confirmation message
And show selected provider's name and address
And design matches the spec

### Design Assets
[M/T/D specs](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/p/DDD647E4-0E6E-427C-A57C-ED62A519C7C6)
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@laurenernest specs added to design assets. Also, I noticed the card header "Selected Provider" should be in sentence case, so changed it to "Selected provider" in the spec.

**Comment by laurenernest** [comment]
LGTM

@outerpress ready for your specs review as well

**Comment by outerpress** [comment]
@laurenernest looks good (sounds good on VO too)
