### ISSUE TITLE
[MCP]: Derive StatementId for FE

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#33565]
## Technical Task

When cross examining the PDF statementIds with the statementIds we have on the frontend we realized they did not match. Looks like the statementId is derived similar to VistaID with 16 digits being required with 000s in the middle as passing. The values used are Facility Num on the first half, and EDIPI on the second half.

Maybe pass a new derived value to FE called statementId?

![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/d779c589-c55e-4616-90a4-b17882460631)

Was testing this on user 81.

## Expected Behavior

Returns a statement ID looking like 6491001005154223		

## Acceptance Criteria

- [ ] BE returns a statementId derived from facilityNum and EDIPI

**Comment by LinnJS** [comment]
[Slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1638480491322400) where this was discussed.

**Comment by LinnJS** [comment]
The unknown right now is figuring out where the `"#{facilityId}#{100}#{edipi}"` 100 is coming from in this string.

**Comment by craigwheeler** [comment]
change was made on FE to render vals from pHCernerAccountNumber -> pHAccountNumber so we just need to ensure the acct number being generated is using the key `pHAccountNumber`
