### ISSUE TITLE
Adding [Sandeep Khurana] to DSVA Slack

### ISSUE THREAD

**Issue by LucianaAlexanderMorais** [department-of-veterans-affairs/va.gov-team#33562]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Please add Sandeep Khurana as a SINGLE guest to DSVA so he can access the following channels:
- va-virtual-agent-public
- va-virtual-agent-team

Sandeep is a member of Microsoft and the virtual agent team needs easy communication with him. Thank you!

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
Hey Luciana, need the email address so I can add the person, thanks! Liz
