### ISSUE TITLE
Spike: Investigate if login.gov has any impact to our functional areas

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#33569]
Platform is going to be adding login.gov as an authentication method to the VA website and back-end Rails application.

As a group, we are responsible for Feedback Tool and Comparison Tool.

We need to investigate if adding login.gov has any impact/work on us and task that out.

Here's a link to the slack conversation related to the login.gov details:

https://dsva.slack.com/archives/C02G07X54C8/p1638292475041200

**Comment by nbarthelemy** [comment]
After assessing the login mechanisms in the Comparison and Feedback tools, I am not aware of any major impacts imposed by platform using login.gov to authenticate users.  It provides a standard interface for validation of credentials.
