### ISSUE TITLE
[Design] Add Medicare claim number to 10-10EZ

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#33561]
[Product Folder for Medicare Claim Number](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Medicare%20Claim%20number)

Requested by HEC team on 11/23/2021.
Add the Medicare Claim number as section 6C. after the effective date.   The Enrollment System already has a section ready to accept the data as you will see from the next screen shot.

![image002.jpg](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/0b9d2312-4e71-4746-8553-39e798afff7c)![image001.jpg](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/18c7e5ae-488b-4ce6-a8cc-d21fb878b737)

### Acceptance criteria

- [x] Medicare claim number field is added to 10-10EZ after the effective date question
- [x] Error handling design for claim number field is included
- [ ] Finalize content

**Comment by Dene-human** [comment]
[https://app.zenhub.com/files/133843125/060dfe47-1bc8-42bc-92a2-0b80c9161c85/download](https://app.zenhub.com/files/133843125/060dfe47-1bc8-42bc-92a2-0b80c9161c85/download)

**Comment by Dene-human** [comment]
Hey @nicko-amida You probably already saw this, but just wanted to link it here: [Transition hub-Features-Medicare claim number](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/Transition%20hub/In%20progress%20features/Medicare%20claim%20number.md)

**Comment by Dene-human** [comment]
Cool. Yeah i think it makes sense for it to appear on the same page as the effective date. This page is only shown if user selects "yes" to the previous question that asks if they have medicare.

The only other thing to consider is error state. Do we want to validate with 11 characters? If so, we need to draft an error message.

**Comment by nicko-amida** [comment]
@Dene-human @hdjustice A few new updates: 
* The claim number field [now has an expandable info alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ygw2kK8)
* The [open expandable info](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/eKeE8dq)
* The [closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbpzrqd) and [open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/wLqej1V) error states.

**Comment by Dene-human** [comment]
Cool! Couple questions:
1. Did you already work with a content person on this? 
     - A couple of things I'm thinking about
       1. I think we should be consistent with the [Insurance detail page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4aGLkPm)
       2. Label could be _" Why we ask this information?"_
       3. inner content could be inspired by (needs to be rewritten in plain language): _"VA uses the claim number to create an Explanation of Benefits, known as Medicare Remittance Advice, outlining what Medicare would have paid VA if Medicare would not prohibited by law from paying for health care services provided by the VA to eligible Veterans. The MRA is used by VA to create a secondary bill to those carriers that require an EOB from Medicare prior to making payment."_
       4. Then the hint text under label could be (needs Danielle to polish): _Your Medicare claim numbers is 11 characters and can be found on the front of your Medicare card._ ([hint text example](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nRwYPad))
       5. Error message could be (needs Danielle to polish): _"Your Medicare claim must consist of 11 characters made up of only numbers and uppercase letters"_

Some reasons behind my thinking:
- Consistency with the rest of the insurance section
- I worry that providing an example number is actually confusing
- With error we want to give user guidance on a solution

Feel free to disagree with the above, we can talk through it and figure it out. Will you be able to bring this to our weekly content meeting with Danielle?

**Comment by Dene-human** [comment]
Yeah I hear you on that. Ok let's talk through it with Danielle. As a rule when we add/edit a question we are trying to add a "Why we ask this information" component to most. But we can think through and balance that with user's need to find where/what the number is. 

If you don't mind, you can come to the weekly content meeting with a couple of different mockup variations?

**Comment by nicko-amida** [comment]
@Dene-human Sure, will do.

**Comment by nicko-amida** [comment]
@DanielleThierryUSDSVA Here's what we can use to run by Tarsha:

**Original:** "VA uses the claim number to create an Explanation of Benefits, known as Medicare Remittance Advice, outlining what Medicare would have paid VA if Medicare would not prohibited by law from paying for health care services provided by the VA to eligible Veterans. The MRA is used by VA to create a secondary bill to those carriers that require an EOB from Medicare prior to making payment."

**Draft plain language:** The VA uses your Medicare claim number to notify health care providers that the VA is covering the health care costs that Medicare normally would.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @nicko-amida. Let's ask Tarsha to review this Medicare explanation for accuracy. I don't think the language above is quite accurate, as I believe it's not that VA is covering the costs Medicare normally would, but that VA is billing the other insurance provider the person may have. But we'll definitely need an accuracy check on this. Let me know if you have questions!

**Why we ask for this information**

We use your claim number when we need to create a Medicare explanation of benefits.  

We don't bill Medicare for any services. By law, Medicare can't pay for our services. But this explanation shows what Medicare would have paid for services if they could. It's also called a Medicare remittance advice (or MRA). 

We may need to bill Medicare supplemental insurance or a private insurance provider for certain services. And some providers must have this explanation before they'll pay the bill. 

**Note:** Having Medicare or other health insurance doesn’t affect the VA health care benefits you can get.

**Comment by nicko-amida** [comment]
@DanielleThierryUSDSVA Awesome, thank you!

**Comment by nicko-amida** [comment]
@DanielleThierryUSDSVA Thanks!

**Comment by hdjustice** [comment]
Adding this information here for historical purposes to reference if needed.
Per a Slack message from Dene', she confirmed with Joshua that the Medicare Claim number is supported. We will be sure to test end 2 end.

> Dené Gabaldón
> I had to talk to Josh about something else so I went ahead and asked about this too. Here’s what he said:
> Medicare is entered under insurance and already supports a policy number
> Medicare claim number is supported in the model; we have never tested it with this service though; i ‘think’ it should work fine though.
> I told him that one of our engineers would coordinate with him to test before we push to prod

**Comment by hdjustice** [comment]
@nicko-amida - Can you provide the latest content here?  Patrick is asking to confirm that we will still hit the recommended language from HEC with our plain language.
Thanks!

**Comment by hdjustice** [comment]
Thanks Nick!   I just cc'd you on an email response to Patrick.

**Comment by markfallows** [comment]
@nicko-amida Can this be closed out?

**Comment by nicko-amida** [comment]
@markfallows Oh - yes!
