### ISSUE TITLE
[BUG] CLP Embedded video not working as expected on the frontend.

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33571]
## What happened?
_Embedded video in CLP doesn't work as expected on the frontend: playback error in the live environment but when previewing the page/video I don’t have an error._

## Specs:
- Device:  ALL
- Browser: ALL
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/initiatives/flu/
- [Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1638554373349700) 

![Screen Shot 2021-12-03 at 11 21 59 AM](https://user-images.githubusercontent.com/70410912/144653534-54092800-990f-41ed-81bf-8f6055c6c5f6.png)

## Desired behavior
_The video should play inline as intended.  Need to resolve this issue soonest as it does block a major employee email push that will mention this CLP and video component._

## Acceptance Criteria
- [ ] Support `/watch?v=id` syntax for youtube URLs.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy monday

**Comment by brianalloyd** [comment]
Validated, closing ticket in support.
