### ISSUE TITLE
Ingest Lighthouse data into BigQuery for Dashboard

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#33579]
In order to have all relevant site accessibility/performance metrics tracked, we need to:

- [ ] Determine which metrics need to be tracked for the sake of completeness of data (Lighthouse results data, for one url, is 22,000 lines of json)
- [ ] Get this data uploading to BigQuery
- [ ] Get the BigQuery data into Domo Data sets.

**Comment by CBonade** [comment]
Chatted with Oseas this morning about this, as some of this overlaps with an effort of the FE Tools team. While awaiting some changes from their end on the Daily Lighthouse Scan workflow, I started digging through the Lighthouse results files to figure out what data we felt was important to track. I believe I've narrowed it down to:

1) Url tested
2) Date tested
3) The "categories" (Performance, Accessibility, etc) and their scores etc.

I'd love to discuss further just to ensure there's no critical data missing from my decision here.

Additionally, I started the construction (and mostly finished) of a data ingestion mechanism that will process the lighthouse data and prep it for being uploaded to BigQuery.

**Comment by CBonade** [comment]
This is working, just awaiting approval for the PR on `vets-website`.

Hopefully, what I took a little time to set up extra here will serve our front end unit test effort as well, as it should hopefully be able to be used for the coverage report.

**Comment by pjhill** [comment]
This is such a nice set of data to have -- hooray.
