### ISSUE TITLE
[Design] Appointments list onboarding ideas

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33581]
## Background
As part of the work to move appointments from MHV to VAOS, VAOS will likely get users who have never used the application before. There is a visual difference between the appointments list in MHV compared to VAOS that users may need help transitioning to.

## Request
Mock up ideas for an onboarding experience for navigating the appointments list(s) and detail pages.

Key areas to consider:
- Appointment statuses
- Navigating to appointment details
- Appointment type indicators (icons, labels, etc)

### Out of Scope
Interactions related to scheduling appointments and the scheduling flow are out of scope for this request.

**Comment by outerpress** [comment]
@JRRoof I didn't see anything in the research that showed a need to orient Veterans to VAOS when they come from MHV. I think the upcoming design changes will improve the learnability of the list for those folks, so this won't be needed.

cc: @ldelacosta @Cieramaddox

**Comment by JRRoof** [comment]
@outerpress - Agreed, I don't see a need for training veterans with the planned improvements.  Will close out this issue.
