### ISSUE TITLE
[BE] Auth Profile: Bad Address Indicator: Include bad address indicator in backend response

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#33582]
## Background
VA Profile has an indicator in their data source that can notify us if an address in the Profile Contact Info has been flagged as bad because mail has been returned, or some other event that we have not yet determined. This work is to mock up what a "bad address" message would look like in the Profile Contact Info UI if the mailing and/or home address were flagged as bad.

## Tasks
- [ ] Include bad address indicator in backend response so that the frontend can use it.

## Acceptance Criteria
- [ ] Bad address indicator from VA Profile data source has been added to the back end response.

**Comment by tpharrison** [comment]
Follow up questions (answered by Barry Wilbanks):

- Question:  Data returned from some of the contact-information endpoints contain a “badAddress” field. Is this the field we’re looking for?
  - Answer:  This would be field

- Question:  If a user updates an address that is flagged with a “bad indicator”, the assumption is that the flag will be removed. This doesn’t necessarily mean the new address is valid or won’t be flagged with a “bad indicator” at some point in the future. Is this assumption correct?
  - Answer:  True assumption with this to consider.  If new address is updated through VA.gov, and failed the UAM address validation, VA.gov/Person would be alerted immediately in the UI.

- Question:  I think I asked during the meeting but didn't make note — is there an ETA on the decision about possibly moving the flag to the “bad repo”?  
  - Answer: Will be discussing it in VA Profile PI Planning next week.  Should know more after that.

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison - can you confirm that this field is now part of the back end response and can be accessed by the front end?  Thanks!

**Comment by tpharrison** [comment]
Yes - I tested that the field in the review instance.

**Comment by MarciMcGuireGCIO** [comment]
Perfect; thanks so much!
