### ISSUE TITLE
Checkbox not selectable

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#33608]
## What happened?
Unable to select the checkbox "I'll be taking classes outside of the U.S. and U.S. territories" for the radio button "Other location" inside the accordion "Learning format and location". See screenshot below.
<img width="1030" alt="Screen Shot 2021-12-06 at 9 50 25 AM" src="https://user-images.githubusercontent.com/86266024/144868513-d4368262-bf91-41e4-a5bb-edcef001a363.png">

## Steps to Reproduce
- Navigate to : https://staging.va.gov/gi-bill-comparison-tool-sandbox/institution/31000548
- Inside "Calculate your benefits" box, open the accordion "Learning format and location"
- Select the radio button "Other location" then select the checkbox "I'll be taking classes outside of the U.S. and U.S. territories"

## Desired behavior
User should be able to select the checkbox "I'll be taking classes outside of the U.S. and U.S. territories" in case if he is taking his classes outside the U.S

## Acceptance Criteria
- [ ] Checkbox should be selected when user clicks on it.

**Comment by SebVortex** [comment]
PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/19738

**Comment by hallihocine** [comment]
Ticket has been validated in staging: checkbox no longer broken.

https://user-images.githubusercontent.com/86266024/147142404-9e243f26-b772-4c22-8995-10ae7e0b557e.mov

**### Screenshots**
<img width="1008" alt="checkbox checked" src="https://user-images.githubusercontent.com/86266024/147142483-999109a6-172d-4808-a566-7f63d59a986a.png">
<img width="956" alt="Checkbox unchecked" src="https://user-images.githubusercontent.com/86266024/147142504-61342f4e-0fe4-4bb5-a044-739b6c646bfa.png">

**Comment by hallihocine** [comment]
- Test run in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2745&group_by=cases:section_id&group_order=asc&group_id=3251
-Test Script/Steps:
[Checkbox not selectable.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7764684/Checkbox.not.selectable.xlsx)

**Comment by mrblanco1** [comment]
EDU UAT occurred and passed on 12/30/2021.
