### ISSUE TITLE
Access for Kayla Watanbe

### ISSUE THREAD

**Issue by klwatanabe** [department-of-veterans-affairs/va.gov-team#33619]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kayla Watanabe

### Your Email

kayla.watanabe@adhocteam.us

### Name of Your Team

Dash, Product Manager, Ad Hoc LLC

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJnRPEMkIjo1VrupGDogGdl37QTmOdE8CAkKVBsCS/j5coFliQe/WCrJwBDOojlDXaly6Smv+UGiJV08p5IwHJNYYz3w9DeQ1lblvq2BZ50j8iKkGq2/aAljF0D3O3sKUmt8TOhsK0yErdpVr/RPhWFkMpSUVyp3BK7xG97ZriHr96NUGeOm9xM8HBq+mVXRBlcHs4+Z8dLqWW6D4lNmKCfd9GM+Tkyop3TRdYyfmIBriSc/FwzGJQXZtBd5Po8amZhee9eyKMP6NyS1ekCoVctEdPprWZnhIRKlJqTBZ3ex7OkEAmAXTeNOfMAT3/Hqa524+oOCTJfZJ0uS14O84vZAxhSZ2aH3fZ14voWpv6gOX6Y39J8vVmbfZ/zFwxsrYnZ58wbDAhZAG1u+IiK2cGdjifQd/sqTvbVnN4Kn+2uLhM3URPEPv3x1j5DHGVbOqvGm5xIxpotudgKpqT81/urGOJCetPzvMdbyTVPnF0CB96+jXOgHj2FiRBOPjk+ek= kaylawatanabe@Kayla-Watanabe-MacBook-Pro.local

### Desired AWS Services

I am setting up SOCKS Proxy for Kibana access.

**Comment by omgitsbillryan** [comment]
SOCKS access granted. Please allow 15 minutes before attempting to connect. 

https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

If you still have issues, reach out in #vfs-platform-support slack channel.
