### ISSUE TITLE
"Search by location" tab fails for Negative testing

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#33616]
## What happened?
The "Search by location" tab is failing for a negative testing. Searching with an invalid zip code (using 6 digits), it's not returning the correct error message. See screenshot below:
<img width="1214" alt="Screen Shot 2021-12-06 at 10 37 27 AM" src="https://user-images.githubusercontent.com/86266024/144875725-8e3ba362-e718-49f3-a80c-328cceafe40e.png">

## Steps to Reproduce
- Navigate to: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
- Click on "Search by location" tab
- Type and search with an invalid zip code (ex: any zip code with 6 digits)

## Desired behavior
- When searching with an invalid zip code, the displayed error message should be something like: 
1. 
<img width="631" alt="Screen Shot 2021-12-06 at 11 02 09 AM" src="https://user-images.githubusercontent.com/86266024/144880212-ac26b3ac-2604-4b9f-b523-f79da9dff615.png">
2.
<img width="674" alt="Screen Shot 2021-12-06 at 11 04 28 AM" src="https://user-images.githubusercontent.com/86266024/144880282-1c35406d-c4a6-49b1-afdc-bb1f5ad2aea7.png">

## Acceptance Criteria
- [ ] A correct error message should be displayed when searching with an invalid zip code.

**Comment by hallihocine** [comment]
Ticket has been validated in Staging: a correct error message is displaying when trying to search with an invalid postal code (6 digits or more)
<img width="1284" alt="Screen Shot 2022-01-05 at 4 44 31 PM" src="https://user-images.githubusercontent.com/86266024/148295256-73ef58ff-b424-4db4-b2e1-2771c42d8f3d.png">

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2810&group_by=cases:section_id&group_order=asc&group_id=3319
- Test Script/Steps:
[Search by location tab fails for Negative testing.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7818032/Search.by.location.tab.fails.for.Negative.testing.xlsx)

**Comment by mrblanco1** [comment]
UATd and passed on 1/06/2022
