### ISSUE TITLE
Deprecate VA.gov Playbook

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#33625]
## Details 

As a user of VA.gov, I want to not have the option to visit va.gov/playbook, so that I can avoid being confused by this very out of date and full of bugs section of the website.

FE Tools is planning to deprecate the VA.gov Playbook. 

[Deprecation plan here.](https://vfs.atlassian.net/wiki/spaces/FTT/pages/1995407406/2021-11-29+VA.gov+Playbook+Deprecation+Plan)

## Acceptance Criteria 
- [ ] VA.gov Playbook is no longer accessible in production 
- [ ] Source code is deleted (clean up tech debt)

**Comment by timwright12** [comment]
Submitted redirect request to public websites team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34240

**Comment by timwright12** [comment]
PR to remove Sass related to the playbook: https://github.com/department-of-veterans-affairs/vets-website/pull/19735
