### ISSUE TITLE
Adding Brittany Lannuzzi to DSVA Slack

### ISSUE THREAD

**Issue by BoDavis-BD** [department-of-veterans-affairs/va.gov-team#33631]
# Description

new user requests - verified that the user does not already exist in dsva.slack.com

Please add brittany.iannuzzi@adhocteam.us as a full member.
Brittany Lannuzzi is a UX Researcher for the Platform Spike Teams.
Are you requesting to add an individual as a:

**Comment by LizCallaghan** [comment]
done!
