### ISSUE TITLE
Access for Peyton Lucas

### ISSUE THREAD

**Issue by peyton-lucas** [department-of-veterans-affairs/va.gov-team#33679]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Peyton Lucas

### Your Email

peyton.lucas@oddball.io

### Name of Your Team

Lighthouse: Team Quokka, Software Engineer, Oddball

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBkz7yoYazLj+pjAvh5gMOCoM5889noNKvNEiMxJnxiJ5IVPNCdNc83QV9tI1spmrU628IulfdtoVngZag/i7bCeKROsvjHw6eoTmzJQTzT/jvOwvS6AIq9s9BvBmJygHCMggA2MySMCfzI9JK2tICE4taGx0Lpf88SqseYVFi+pfbIOkVwtsrvnmmTe4CRjzRL4+PDferi/88MON9P5Q3yIdSo+YDwufnrKKnSkQEnZGU+wkgFcvQ0lKwdiEWrLVW3l2YO9VKUHryFpeuj5/iFHBYkyRiAdT+FkMzj9trljOyRfr5RcPq3VoTqJU4stWaga8KvMi+JycTSS3kRqh+XtTyxMJuWCbg0w8SRKMsX2DzflL4woYawTSujTkBuu09hHYvleuO3LGO1PF7ri6jnv6d75bvE/sOY8YKt1gsziPxP+RGyRaQ851M1OCnmLWE8CefidyUa4NlN4nELFRehawHPymOnDTE0xG4RbLEM4/+5+0iHGo//0LvYQ7Khpk= plucas@MacBook-Pro.lan

**Comment by omgitsbillryan** [comment]
SOCKS access granted. Please allow 15 minutes before attempting to connect.

https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

If you still have issues, reach out in #vfs-platform-support slack channel.

**Comment by omgitsbillryan** [comment]
**For AWS Access**
User: Peyton Lucas
Vendor: Liberty IT - Michael G. Lovejoy
Approval needed: @mchelen-gov

**Comment by peyton-lucas** [comment]
Hi! Just checking in on this. Do you previous posts mean I have SOCKS access? It says at the bottom, I am still awaiting approval.

**Comment by rbeckwith-oddball** [comment]
SOCKS access has been granted. The AWS portion of the request is still awaiting approval.

**Comment by jsgarmon** [comment]
new approval group: @department-of-veterans-affairs/operations-aws-approvers 

@peyton-lucas : they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that your COR has added your transmittal date to the Sharepoint doc?

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by peyton-lucas** [comment]
Sorry I missed this. I was on Christmas holiday leave. I can confirm I submitted my eQIP on 23 or 24 November 2021, and it was received and passed along to the investigative team. I also got my PIV card appointment. for next week.

**Comment by td-usds** [comment]
Understood, I need the VOR to confirm this by putting it in our tracking spreadsheet though :) This was not something you needed to do, so no worries!

**Comment by peyton-lucas** [comment]
Cheers for the update! Apologies for the confusion :)

**Comment by td-usds** [comment]
Reached out to VOR today
Also, @peyton-lucas can you describe the specific AWS services you need access to? Right now none are listed (and so none would be granted on conclusion of this issue :) - which probably isn't what you intended)...

**Comment by td-usds** [comment]
Tentative approval based on access eligibility but the actual scope of access needs to be defined before it can be granted

**Comment by peyton-lucas** [comment]
@td-usds 
AWS Console access for developing and maintaining the Lighthouse dev portal.

I'm on the same team as Dina Steeve, Team Quokka - can I be granted the same permissions as the other active team members?

**Comment by mleclerc00** [comment]
Passed along account information to Peyton, closing ticket
