### ISSUE TITLE
R&S: Tally of the faqs covered in R&S articles

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#33723]
## Issue Description
We need an accurate count on the number of IRIS and GIBHP faqs that we've replaced with R&S articles. (Faqs that are covered on tier 1 pages are not a part of this count.)
**Tasks**

- [x] Use GH status tables to identify all faqs we've included in R&S articles (Laura)

**Acceptance Criteria**

- [ ] Current total and date listed in comments below

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Here's the tally you asked for. LMK if you have questions or need additional details. 

![image](https://user-images.githubusercontent.com/53535663/145103171-8b11ba54-7716-4d87-b0ad-3b6cb5272b14.png)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Is there a way to capture this in the github chart somewhere? That these numbers apply to the first 70 articles created?

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - I can't add it to either of the existing tables because it doesn't match the columns/rows structure. I can put it in a third table.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Would you create a new file for this chart and just make it clear that this is for articles that went live in 2020 and 2021? That way we can add to these totals as we go by checking the github list Randi has going for when we're launching each one. Thanks!

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - ^ Yes, I included Section 702 as "FAQs Covered by R&S Articles" as we have an article in development.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Here's the GH table. Just above the table, you'll see a bold header with an "as of" date. We can change the date whenever we update the table. teams/vsa/teams/sitewide-content/resources-and-support/iris-gibhp-tally.md

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Thanks! This is great. What I'd also like it to show is X number of IRIS FAQs migrated/consolidated into X number of VA.gov articles. Could you add a column? I know it's kind of a pain in GH, sorry about that.

So the first column would be: # of IRIS or GIBHP FAQs migrated
Second column would be: # of R&S articles covering this content

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - I'm assuming ^ is for live articles only because articles still in review could still either be condensed into fewer or expanded into more articles, correct?

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 We'll operate under the assumption that we'll get the following additional articles live this year and that none of them will change templates or expand into multiple articles (so count 4 for these articles):

- GI Bill extension
- GI Bill refunds
- failing grade
- in-state tuition under section 702 of VCA

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - I revised the table in GH with the total number of 2020/2021 R&S articles that cover the topics (Account & Profile, Burials & Memorials, etc.). That's now the 1st column. The 2nd column shows the number of faqs covered by the articles. Let me know if you need anything else on this. 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/resources-and-support/iris-gibhp-tally.md

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Thank you for this! I'll ask you to update the chart with health care numbers once Danielle gives me that. I also have a couple questions: the number for housing for FAQs covered by R&S articles is 18. Is that the number covered in the 5 articles or so that are sitting with Raleigh right now? And are the 48 future articles unwritten?

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 From Danielle: 
- 3 nursing-home related IRIS questions consolidated into 1 R&S Q&A that leads to the benefit hub page for more info
- 3 health care/prescription eligibility IRIS questions consolidated into 1 R&S Q&A that leads to the benefit hub page for more info
- 2 health care concern/complaint resolution IRIS questions consolidated into 1 R&S article

Could you add this info to the tally chart and also update the IRIS status by FAQ chart?: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/resources-and-support/iris-status-by-faq.md (Can you figure out which IRIS IDs she's referring to?)

Also, can you see if you can figure out which IRIS debt FAQs (aside from the education ones already accounted for in the EDU numbers) are now covered by the live debt content in R&S? And which are covered by tier 1 debt content. This is a bit of an audit exercise...

**Comment by lwalsh617** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA -- I can't identify which faqs were used as sources for the articles ^. Danielle, if you can let me know, I'll add them to the chart we have that shows the status of each IRIS faq. Thank you.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - 
QQ: Where would you like the debt faqs listed -- under the "Other Topics & Questions" section in the table?
Also, I updated the tally table in GH with the health care info provided ^^.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Yes, debt can go under other topics and questions. Thanks for updating the tally chart.

**Comment by bethpottsVADEPO** [comment]
I think we can close this ticket now.
