### ISSUE TITLE
Access for Harshil Moradia

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va.gov-team#33722]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Harshil Moradia

### Your Email

harshil.moradia@adhocteam.us

### Name of Your Team

Platform Spike Teams - Access Management

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLAtM6X7UNaEQqD0K5B16vlBSUT9oXOKYSOYU924dAMhr4QYvP/DPacnXtDnTLLO1jYHUmUonMRblSjf5VOAcw62mHfKlZdZgrvVe5jXawoqBFctlnQIKuEPg9T3MvWAiBTR9jxjGEhcjZ2oeC4IMbR6+ZEtWbhNgIYhvj+TZifO3hbIPDlBRpb3zHCK9xPQyvz4PVjLdeDHNd/mVQAlEs6EKYoOV36pjgJl2fDYZHDAwOdiJ/AI4jRC3oVtDpEf77O/OtwukgUmgShgb4TcWFspSUwR9xRqN0Bl910yLyVzxRqVHxAWnoVQ4jHJHlMJyE+Ob9i0Gx2Okz0m1d5VIpiHkwgr+lP1Y7yRFLik4TH1pgraUhcv2eK6LTuYV2jF7OH8VCvSmHUdx26Xl14BiXW/j5XF2Yx5aoOXfqGE8t8sej2BLj7VA9ObfIgkv9IwiC8fo71ozNBYhAviq4FopL6kkC0eYlfrpfJnBKRnPrqfqHHvFQjDWcRLAkkTQx0n8= harshilmoradia@harshilradiambp.lan

**Comment by omgitsbillryan** [comment]
SOCKS access granted. Please allow 15 minutes before attempting to connect.

https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

If you still have issues, reach out in #vfs-platform-support slack channel.
