### ISSUE TITLE
COVID-19 booster/omnicron updates week of 12/6

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#33720]
- Some updates made Friday, 12/3. Noted below.

Page 1 – Main mini-hub:

![main mini-hub page 12-3 updates.jpg](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/e04ca11f-ce07-4b06-928f-4ab6bf1fbf1b)

Page 2 – boosters and additional doses
![booster shots 12-3 update.jpg](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/584a7504-724d-4b6e-8ccb-a2e98a745db8)

![booster shots 2 12-3 update.jpg](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/ae9e5537-230e-4d28-86e1-983c9c47667f)

- Additional updates made Tuesday, 12/17. Captured in Drupal.

We need to publish these and then do the translation work. 

- [x] Review changes made (Randi)
- [x] Get approval to publish (Danielle)
- [x] Publish (Randi)
- [ ] Update chatbot (Selina)
- [x] Review FAQs and other pages if updates are needed (Selina)
- [ ] Review updates on other pages and publish (Randi)
- [x] Send text to translators (Randi)
- [x] Input Spanish translations (Selina)
- [x] Input Tagalog translations (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send live links to volunteer translation team (Randi)

**Comment by RLHecht** [comment]
Just reviewed and made a few change that we discussed over slack.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's the updated vaccine records page with adding the mobile app in. Also moved links up in the step-by-steps. Lauren and Leanna confirmed this is good to go from an accuracy perspective. Can you let me know when you've reviewed this? http://preview-prod.vfs.va.gov/preview?nodeId=34795 I'll then send over to clinical folks. Thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I reviewed this. The VA network won't let me check that the Google Play link is correct. It tells me it's restricted. Can you let me know if it works for you? Otherwise everything else looks good.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I checked it on my other computer and it works. My only question is do you think the build will break because it's appearing as a broken link?

**Comment by RLHecht** [comment]
It shouldn't be an issue. I think the CMS team has now set up a system where it takes a certain number of broken links to break the build so this shouldn't affect it. It also doesn't show as a broken link in CMS, just when I click it I get an error message that I can't access it. I'll keep an eye on it when we publish though to see if there are any problems.

**Comment by lunascoop** [comment]
@RLHecht I added the note re: vaccine choice. These pages are ready for review.

Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580
Sobre las vacunas COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36461
Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475
Tungkol sa bakuna laban sa COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36427

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published.

**Comment by RLHecht** [comment]
@lunascoop Here are the newest translations back:
[https://app.zenhub.com/files/133843125/ad3c4828-decf-452c-884a-24e7e87d7d3c/download](https://app.zenhub.com/files/133843125/ad3c4828-decf-452c-884a-24e7e87d7d3c/download)
[https://app.zenhub.com/files/133843125/35e6ac4b-3e79-4d95-9e98-25bf7b81e8ad/download](https://app.zenhub.com/files/133843125/35e6ac4b-3e79-4d95-9e98-25bf7b81e8ad/download)

**Comment by lunascoop** [comment]
@RLHecht I have made updates to the pages below.

Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408
Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394

A couple of things:

- This content needs to be translated for both Spanish and Tagalog

> When to get your booster shot
> * If you got 2 doses of the Moderna or Pfizer-BioNTech COVID-19 vaccine: Get your booster 6 months after your second dose.
> * If you got the single-dose Janssen (J&J) COVID-19 vaccine: Get your booster 2 months after you got your vaccine.

- There's some content from the Tagalog doc that wasn't translated.
   - The CDC recommends that everyone who is at least 18 years old should get a booster shot. Teens ages 16 and 17 can also now get a booster shot. 
   - If you're at least 18 years old, you can choose which vaccine to get for your booster dose.

**Comment by RLHecht** [comment]
Thanks @lunascoop I published these and will send to Mateo. I also reached out to the translators to check on the omicron work we're waiting on.

**Comment by RLHecht** [comment]
@lunascoop Here are the translations.

[https://app.zenhub.com/files/133843125/5f04e26d-f62a-41a7-a650-74ae6b13ed9f/download](https://app.zenhub.com/files/133843125/5f04e26d-f62a-41a7-a650-74ae6b13ed9f/download)

[https://app.zenhub.com/files/133843125/bc5b9442-93fc-468f-b4d7-6326554b77a5/download](https://app.zenhub.com/files/133843125/bc5b9442-93fc-468f-b4d7-6326554b77a5/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. Some of the translations are outdated and were ignored. 

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Sobre las vacunas COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36461
- Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16475
- Tungkol sa bakuna laban sa COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36427
- Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394

**Comment by RLHecht** [comment]
Thanks @lunascoop I published all of these. Will wait until they are live to send the links to Mateo's translation team to review.

**Comment by RLHecht** [comment]
Text is live and I sent Mateo links to the content to review. Closing ticket and will reopen if he has changes.
