### ISSUE TITLE
Update Cerner links

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33740]
## Issue Description
In #31109, we added redirects to the Cerner portal from within the "Manage your health online" box based on a Cerner flag in CMS identifying systems which have cutover (currently just Spokane).. These redirects were to a general Cerner login page.  We have now information on the task-specific deep link. 

![image](https://user-images.githubusercontent.com/55411834/145094247-505e764f-5e3a-47cf-957c-f0fdf71fd5d0.png)

Notes: 
Once scheduling is active, we can provide the link to the scheduling page (future issue).
There is no equivalent task in Cerner for ordering hearing aid supplies

## Tasks 

Replace general links in "Manage your health online" with task-specific deep links according to the chart below

Task | url
--- | ---
Refill and track prescriptions | https://patientportal.myhealth.va.gov/pages/medications/current
Send a Secure Message |  https://patientportal.myhealth.va.gov/pages/messaging/inbox
Schedule and manage health appointments | https://patientportal.myhealth.va.gov/pages/scheduling/upcoming 
Download your medical records | https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes
View lab and test results |  https://patientportal.myhealth.va.gov/pages/health_record/results 

## Acceptance Criteria
- [ ] When `field name vamc_ehr_system` indicates Cerner system,  the following links within the "Manage your health online" direct Veterans to the appropriate deep link for the Cerner patient portal
     - "Manage your health online"
     - "Refill and track your prescriptions"
     - "Send a secure message to your health care team" 
     - "Schedule and manage health appointments"
     - "Download your VA medical records (Blue Button)"
     - "View your lab and test results"
- [ ] Preserve existing experience for "Order hearing aid batteries and accessories"

**Comment by GcioNapoleon** [comment]
Modified the liquid.filters.topTaskUrl to have all of the changes in the table

![Screen Shot 2021-12-28 at 5 00 06 PM](https://user-images.githubusercontent.com/95312667/147613281-616eedde-4957-4a59-8c80-eecfbbc4b223.png)
