### ISSUE TITLE
NEWSLETTER PIVOT: Execute experiment

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#33767]
Pending sync with Service Design

**Comment by lianilychee** [comment]
from 12/9 Thurs SD<>C/IA sync:
- use template to fill in pros/cons of these two recommendations
  - Rec to remove editorial bar
  - Rec to have PMs contribute (instead of Service Design scraping for info)

**Comment by andreahewitt-odd** [comment]
Newsletter no longer exists -- closing
