### ISSUE TITLE
NEWSLETTER PIVOT: Set editorial bar level

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#33766]
# User story

As a Content team member, I need to know what level of editorial check effort to apply to the communications roundup experiment, so that:
(a) I can execute the experiment
(b) I don't detract from future team initiatives

# Tasks

# Acceptance criteria
- [ ] Keep Rachael Roueche abreast of details

# Reference info
- [Communications roundup experiment](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1985708208/Experiment+Communications+Roundup?atlOrigin=eyJpIjoiYWIyNzkwMzRhMjBiNDhmNjkwNWIxMzJiMTMyMDNiZmYiLCJwIjoiYyJ9)

**Comment by lianilychee** [comment]
this might go away, pending SD<>C/IA sync tmr

**Comment by lianilychee** [comment]
12/9 Thurs:
- pending SD/Content sync later today
- thought: want to make sure that this research does not have implications to the broader role of needing editorial checkpoints

**Comment by lianilychee** [comment]
12/14 Tues:
- Today
  - Gretchen to relay to Jonathan and Rebekah, gonna see if Rebekah is willing to separate the doc
  - Liani can separate if Rebekah is unable to

**Comment by lianilychee** [comment]
12/15 Weds:
- pause pending Andrea:Liani

**Comment by andreahewitt-odd** [comment]
Newsletter no longer exists -- closing
