### ISSUE TITLE
[Design] Auth Profile - Address Change Messaging - Write FE specs

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33773]
## Background

The UX for the 'Address Changing' message work need to be written and stored with the project documentation for future reference.

## Tasks
- [x] Document the user experience using a combination of UI and explanatory text

## Acceptance Criteria
- [x] Document has been created and stored with the Profile documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-change-messaging/design)

**Comment by Samara-Strauss** [comment]
1. @cgednalske is this already done?
2. If not, this can be moved out of sprint 72, @SKasimow. We have way higher priorities that we need to focus on.

**Comment by SKasimow** [comment]
@cgednalske Hi - does the FE documentation include high fidelity mocks? Or would that be a separate ticket?

**Comment by cgednalske** [comment]
Hi @SKasimow! The fidelity mocks are already done, so in this case neither! 😃

**Comment by Samara-Strauss** [comment]
I think the scope of this ticket is a little bit unclear:

- The frontend design is done, so I don't think "frontend specs" are needed if we are defining frontend specs as something Adam would use to build.
- If Marci was intending for you to write documentation on how this feature works in general so a future designer/team member could easily see how it works, then I think that makes sense. We don't have a template for this kind of design documentation right now, however, so I don't have guidance on how to do this. It might help to talk to Liz or other designers on how they document their work.

**Comment by Samara-Strauss** [comment]
BTW, [you can put any design documentation here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-change-messaging/design).

**Comment by SKasimow** [comment]
Closing this ticket. We can open a new ticket to address this point if needed:

>If Marci was intending for you to write documentation on how this feature works in general so a future designer/team member could easily see how it works, then I think that makes sense. We don't have a template for this kind of design documentation right now, however, so I don't have guidance on how to do this. It might help to talk to Liz or other designers on how they document their work (or how they would like to document their work if they don't already).

**Comment by Samara-Strauss** [comment]
I think it could be helpful to have design documentation for how this feature works if you wanted to open a new ticket or just repurpose this one. ([You can put any design documentation here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-change-messaging/design).

**Comment by SKasimow** [comment]
@Samara-Strauss @cgednalske Hi - I came across this design doc Christina and Marci put together for "Bad Address Indicator" that looks like a good template to start with ([link here)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/frontend/FE%20documentation.md#contact-information-page-alert). I'll re-open and update this ticket for Christina and I to work on.

**Comment by cgednalske** [comment]
@Samara-Strauss sounds good! 👍  @andaleliz and I have had some informal convos about different documentation processes lately, so will regroup on that and make sure this follows the ideal template.

**Comment by andaleliz** [comment]
I'll be happy to discuss w/ @cgednalske but I do think it's a larger conversation we need to come to a team consensus on. It feels like in general, we need a single document that captures the various states and interactions for each feature that is updated when we add things or make changes.

The way things are set up today, a person would have to know specifically which initiative work was done under (e.g. designating between address validation and bad address indicator) to find documentation. I think it'd be more clear if it was part of either the product outline or some other kind of long term documentation. I'm currently looking to teams who have similar situations and how they handle docs like this.

**Comment by SKasimow** [comment]
It would be really nice if we could combine or leverage whatever form this documentation take and use for the Product Outline. :)

**Comment by Samara-Strauss** [comment]
>  I think it'd be more clear if it was part of either the product outline or some other kind of long term documentation. I'm currently looking to teams who have similar situations and how they handle docs like this.

I agree that we need something that's project-agnostic and clearly documents each feature as they are currently today (or whenever "today" is in the future). I'm sorry I don't have better guidance on this now. I think it's OK if we start something and iterate on it over time.

Re: the product outline -- depending on how long documentation gets, we might want to have docs separate from product outlines so they don't get super long and unmanageable. But we should definitely link to documentation from the product outlines. I can walk you all through how I have things structured if you need me to do it.

**Comment by cgednalske** [comment]
Following Liz's recommendations resulting from her documentation work, I created a [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-change-messaging/use-cases/home-address-updated.md) for Address change messaging, coupled with [FE documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-change-messaging/frontend/fe-documentation.md) closer to that of BAI. Adam has looked over an added a few things as well.

**Comment by Samara-Strauss** [comment]
Thank you for this! I linked to these docs from [the contact info product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/README.md). Also, I changed the location of the use case documentation and moved it to the README for that folder. Great work!

We can close this, yes?

**Comment by cgednalske** [comment]
@Samara-Strauss yep! I'll close it out.
