### ISSUE TITLE
Add additional unit test coverage to the Dashboard Data repo

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#33796]
## Issue Description
Add additional unit test coverage to the Testing Tools Team Dashboard Data repo. Unit test coverage is currently ~40%.

---
## Tasks
- [ ] Create unit tests
## Acceptance Criteria
- [ ] Unit test coverage is 90% or greater

**Comment by pjhill** [comment]
OBE
