### ISSUE TITLE
Restructure the Github ingestion mechanism in the Dashboard Data repo to be extensible

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#33794]
## Issue Description
Restructure the Github ingestion mechanism in the Dashboard Data repo to be extensible to things like commit rate, lines of code add/subtract, etc. Similar restructure to what we did with Mochawesome.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by CBonade** [comment]
Refactored using Javascript classes. There's now a parent github class that handles generic things such as fetching the data from any endpoint with dynamic params and uploading the data to BigQuery. There's then a child class that extends the parent class and is handling anything specific to the issues. New subclasses can be created to extend the github class for collecting different data types.

**Comment by CBonade** [comment]
After some revisions, this is now complete. To create a new GitHub Data stream, a subclass can be created with 3 variables and one data map to shape the data. Everything else will happen automagically.

**Comment by pjhill** [comment]
Heck yes, I'm excited to have this debt paid down!
