### ISSUE TITLE
Dependency Upgrade - Yarn

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33798]
## Description
Submitting this request on behalf of the Design System Team. We would like for the `yarn` dependency on vets-website to be upgraded from version 1 to version 3. This will make it easier for us to link the vets-website repo with the component-library repo locally in order to test new/updated design components.

**Comment by timwright12** [comment]
@bkjohnson can you add details here about what you're looking for? Just an update to the engine? https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L248

**Comment by k80bowman** [comment]
Yes, we would just like to upgrade Yarn to version 3 (we're using version 3.0.2 in the component-library).

**Comment by bkjohnson** [comment]
Yes, but I think it would be more than just upgrading the engine. [This guide](https://yarnpkg.com/getting-started/migration#step-by-step) has some instructions that helped use when we did the same thing to `component-library`.

**Comment by k80bowman** [comment]
@timwright12 any way we could get this prioritized soon? Testing Design System components in `vets-website` locally would be much easier with this update.

**Comment by bkjohnson** [comment]
I needed to test some local `component-library` changes in `vets-website` and `content-build` so I did this again and this time committed the changes. I followed the instructions in the earlier linked guide. Here are the branches:

- https://github.com/department-of-veterans-affairs/vets-json-schema/commit/3a366ffeb10957259b3980418391837d1d24b739
    - This is so the `postinstall` won't fail. It tries to run a script, and yarn 3 respects what's in the `files` property and removes everything else. The script wasn't there so the `postinstall` was failing.
- https://github.com/department-of-veterans-affairs/vets-website/compare/bkj-yarn3-update

**Comment by timwright12** [comment]
sure, we can get this on the list for next sprint. It's a little odd since yarn isn't technically a dependency of vet-website so we'll need to understand any VFS ramifications as well

**Comment by timwright12** [comment]
Update: This (no surprise) seems to be a problematic update because of all the breaking changes from yarn 1 -> 3. We'll need to make a lot of changes in CI ([PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20293)). Because of the large amount of updates needed, we'll also need a test plan created and tracked

**Comment by timwright12** [comment]
@bkjohnson Getting these issues when running yarn install:
```
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide @department-of-veterans-affairs/formation (pc959a), requested by @department-of-veterans-affairs/web-components
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react (p40b9e), requested by react-focus-on
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react (pacd1e), requested by react-scroll
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react (pa708c), requested by react-transition-group
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react (p2f9dc), requested by @department-of-veterans-affairs/react-components
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react-dom (p78559), requested by react-scroll
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide react-dom (p88153), requested by react-transition-group
➤ YN0002: │ @department-of-veterans-affairs/component-library@npm:6.2.1 doesn't provide web-components (p5284a), requested by @department-of-veterans-affairs/react-components
➤ YN0002: │ @department-of-veterans-affairs/react-components@npm:4.0.3 [e4de1] doesn't provide react-dom (pbc1b2), requested by react-scroll
➤ YN0002: │ @department-of-veterans-affairs/react-components@npm:4.0.3 [e4de1] doesn't provide react-dom (p84f8d), requested by react-transition-group
➤ YN0002: │ @department-of-veterans-affairs/web-components@npm:2.2.1 [e4de1] doesn't provide postcss (p1012c), requested by postcss-url
➤ YN0002: │ @formatjs/intl-locale@npm:2.4.37 doesn't provide @types/node (p14a82), requested by @formatjs/intl-getcanonicallocales
```

**Comment by bkjohnson** [comment]
Those are all peer dependency warnings. We could probably tweak our `package.json` to remove some or all of those.

I think the last one for `postcss` & `postcss-url` is a leftover from when we had the `web-components` branch and were doing the build locally, so those were needed in `dependencies`. We should be able to move them into `devDependencies` now.

**Comment by bkjohnson** [comment]
Those warnings should be fixed with https://github.com/department-of-veterans-affairs/component-library/pull/300. I've published a prerelease for local testing and didn't see those same logs.

I listed react `16.3.1` as the peer dependency, so now we're seeing things like this:

```
➤ YN0060: │ vets-website@workspace:. provides react (p586f9) with version 17.0.2, which doesn't satisfy what @department-of-veterans-affairs/component-library and some of its descendants request
```

However, we're also seeing that for other dependencies related to mocha, `react-router`, etc. I can set this to use react 17 if you want, I was just being cautious.

---


You can test the changes on the yarn 3 branch in `vets-website` with:

```
 yarn add @department-of-veterans-affairs/component-library@^6.2.2-2
 ```
 
 I wasn't able to commit the change since the install was still failing for `vets-json-schema`.

**Comment by timwright12** [comment]
gotcha, thanks! I think the general build still functions with those messages so we might be OK

**Comment by timwright12** [comment]
We'll need to roll the yarn upgrade in content-build out with this one. Current status is that Github Action workflows in both content-build and vets-website are passing, but Jenkins in vets-website is not and review instances are not spinning up properly. Once vets-website issues are worked out, we should be able to merge at the same time as content-build

**Comment by k80bowman** [comment]
Thank you for working on this!

**Comment by timwright12** [comment]
CI in vets-website and content-build are passing now. Review Instances seem to be working as well. Going to run through a test plan and if all goes well will merge and communicate the change to VFS teams after the daily deploy Monday

**Comment by timwright12** [comment]
Created test plan for this upgrade: https://docs.google.com/spreadsheets/d/1zHfChHWemZq7eMSPz6c_k7FCtHzy6BkBJ8egDrvH9so/edit?usp=sharing

**Comment by timwright12** [comment]
Experiencing a sea of failed unit tests on the upgrade branches now, going to pull this back and regroup. The yarn lock file keeps conflicting as well causing extra changed files after a master merge.

**Comment by rmessina1010** [comment]
Yarn workspaces  may be blocking this ticket,  as  we need v. 1.9.1.  (pending review). Closing.
