### ISSUE TITLE
Add tests for the BE unit test BiqQuery code in vets-api

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#33792]
## Issue Description
Add tests for the BE unit test BiqQuery code in vets-api.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by JoeTice** [comment]
This is Done for TUD
