### ISSUE TITLE
[Debt Letters]: Enable e2e cypress test

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#33804]
## Technical Task

Public websites skipped test due to failing in CI/CD re-enable them so we have full test coverage again.

## Expected Behavior

All debt letters e2e test are enabled.

## Acceptance Criteria

- [ ] Fix and re-enable debt letters cypress test

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19590#pullrequestreview-826646043) where test were skipped due to blocking builds.

**Comment by craigwheeler** [comment]
The download Debt Letters table is using the `<Table/>` [component](https://design.va.gov/components/tables) provided by the design system and we seem to getting an accessibility error causing the tests to fail and blocking this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20223) moving ticket to blocked until a fix is merged

**Comment by craigwheeler** [comment]
issue being tracked by platform informed they will be working on it next sprint .. https://github.com/department-of-veterans-affairs/va.gov-team/issues/36910

**Comment by denisecoveyduc** [comment]
Resolved as part of the platform issue.
