### ISSUE TITLE
REMOVE User from DSVA Slack (Warren David Benson)

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#33819]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

**Please remove Warren David Benson from DSVA Slack**

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
