### ISSUE TITLE
[BE] Add statds logging to help troubleshoot BGS ch33 latency issue

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#33812]
tasks:
contact bgs about ch33 latency
add statds measure around bgs ch33 calls

**Comment by MarciMcGuireGCIO** [comment]
Noting that the issues seems to be resolved at the moment.  Moving this to Icebox to be worked on if it arises again.

Relevant Slack thread: https://dsva.slack.com/archives/C909ZG2BB/p1639144939247600
