### ISSUE TITLE
Access for Brian DeConinck

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#33829]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Brian DeConinck

### Your Email

brian.deconinck@adhocteam.us

### Name of Your Team

Platform Product Support Team - Software Engineer / Accessibility Specialist

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/RG7A3z7YM1pB+CauJBDdLYPqGt3B9SW7K3as4S2MX9Wq+CvKvs6TljsrV7hH9WIHnUZoB1aKhPoVokSNsp6Enun35IFA2vEzt7kQoL/ljlOEZQmiwtbqLgtdD7DTjbhKkPBMcvdweMee3KLLsp/U877z3dbpvfeVU2JPfv6nkQn+j0yWwE7x/1Ho2GRI+T/qOJ1x0O5hgcUIIMzGwCq2Q6XYgzX25A31kYpOd/+fawnmRqVuRlpGXIgmxr9ZzMRPm+4ic76AltKPAW64DtNx/0VdAD9HA06qmyDrCIUyz9qwJgwDLYbokzR+D6rpSARv6b7ZggKC5/xlhFUFv7ft0c9fx1Q1s3LWR2U6QdupbORllX7clfz+9ZQmiSGf++CzTtGNfGFteZhaz+u5rzJndZCFhHhZM0lxsRPkFKRaxKpA6SdqhAt3cGkLm6bTFlbwG0QgUe1T3hZk4D2oI6wGoFMZRBnI4SruR8nh/CW6HXN4Q/VYAZKyzxDG7ax1vB0= briandeconinck@BrianDeConinck-HP

**Comment by omgitsbillryan** [comment]
Socks has been granted. Please reach out in #vsp-platform-support if you need further assistance.
