### ISSUE TITLE
Add New Hires to DSVA Slack as Full Members

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#33828]
Please add the following new people supporting VSA as full members to the DSVA Slack:
Tom Harrison tom.harrison@adhocteam.us
Tyler Simoni  tyler.simoni@gcio.com
Lametria "Mimi" Taylor  lametria.taylor@gcio.com
Nicole Leonard nicole.leonard@gcio.com

Thank you!!

**Comment by LizCallaghan** [comment]
done!
