### ISSUE TITLE
Design Update to HLR Request an Informal Conference (step 3)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3382]
## User Story 
As the FrontEnd Engineer on the Benefits and Memorials team, I need incorporate all of the design updates from the design mockups so that the HLR form step 3 screen can be finalized.

## Goal
_Step 3 screen to be updated with updated design in the design mockups_
[InVision Design Mockup](https://vsateams.invisionapp.com/share/8JUSQKTUM76#/388976567_Default)

## Acceptance Criteria
- [ ] _HLR Step 3 screen has been updated with design changes provided in InVision mockups_

**Comment by sshein** [comment]
Hi all - just a quick note. I think the copy on the designs still needs a little bit of work to make it clear that the user is scheduling a meeting *to schedule the review*.  @kevinstachura we can talk tomorrow about making sure that happens. Also added a few notes on the inVision.

**Comment by Mottie** [comment]
The update for this step has already been completed and merged. For any updates to the content, we'll open a new ticket. Thanks!
