### ISSUE TITLE
Parse Multiple CorpIDs based on A and H values

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#33830]
If the user has no value, a single value, or multiple values with a single ^A value, they should be permitted through (with the ^A value being used).

This is similar for IENs and EDIPIs. That ticket will be moved over to in progress and should be tested alongside this ticket.

**Comment by nsoutouras** [comment]
Nick: Similar to earlier MHV story (and DS Logon version).  Certain ID's (GCID) are parsed by IAM and put in SAML header.  Their parsing doesn't appear to be as solid as we'd like.  If a user has multiple CORP ID's, even if some are inactive they are still returned by IAM.  This work lets us parse it ourselves.  

**If a user has an inactive Corp ID, they potentially would not be able to log in.  This fix would allow them to log in.**  

**Corp ID's:**
IEN 
CorpDB ID
EDIPI
