### ISSUE TITLE
[Bug] [iOS Safari] Medical Copays - Overview page - COVID alert missing close button off-screen

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#33846]
## What happened?
In **iOS Safari**, on **[Staging Medical Copays](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details)** - Overview page, **COVID alert** close button was off-screen.

## Specs:
- Device: iOS phone & tablet [Update: iOS 14 (not occurring in 15)]
- Browser: Safari
- Test User _(if applicable)_: `vets.gov.user+81@gmail.com` (Travis) [for passwords see [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc]

## Steps to Reproduce
- Use **iOS phone/tablet Safari** [Update: use iPhone 13 or iPad gen9]
- URL: https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details
- Test User _(if applicable)_: [see above]
- On **Overview** page, observe that **COVID-alert** is missing the close buttton.  It's off-screen, and requires swiping to reveal & tap to close alert.

**Screenshots**:

**iOS phone**:
![image](https://user-images.githubusercontent.com/587583/145319951-27a45a40-c42c-4ed4-83b7-e8fcbe34d8f4.png)

**iOS tablet**:
![image](https://user-images.githubusercontent.com/587583/145320868-235bfe7a-79eb-472a-98bc-398e5b4d7aca.png)

## Desired styling
- [x] **COVID-alert** close-button should be displayed on-screen upon initial-load.

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
@brianalloyd I think this falls into your space ;)

**Comment by denisecoveyduc** [comment]
Hey @brianalloyd just a little nudge.. is the a PW fix?

**Comment by brianalloyd** [comment]
@denisecoveyduc we'll take a look, since this has migrated not sure our FE team can fix this issue.  I'll follow up shortly.  @srsuddath @tmac9494  looping you into the issue for review. @denisecoveyduc I'm also going to add our Public Websites label on this issue.

**Comment by longmd** [comment]
@brianalloyd ... Not sure what has changed in the app between when this was reported in December and now, but this appears to be rectified. I tested in BrowserStack on both iPhone and iPad and then pulled up the page on my own iPhone and all show the same alert with the dismiss button present. See the attached screenshots:

- <img width="491" alt="Screen Shot 2022-02-22 at 2 36 27 PM" src="https://user-images.githubusercontent.com/6738544/155206997-1e25a112-17ec-43a7-869a-7b5f4270633c.png">
- <img width="627" alt="Screen Shot 2022-02-22 at 2 41 11 PM" src="https://user-images.githubusercontent.com/6738544/155207034-6c65f2d8-9199-48bb-8539-d98726c0d147.png">
- ![Screenshot of Issue #33846 in Mobile Safari - iPhone 13](https://user-images.githubusercontent.com/6738544/155207052-4ccd56e1-0892-4033-832d-d4a93e207151.png)

**Comment by tlei123** [comment]
@brianalloyd / @longmd , looks like it's fine on iPhone 13 & iPad gen9 (iOS 15), but not 12 or gen8 (iOS 14).  Just so you know, I usually test against last-year's model hardware.  [If I had more time I'd test against current & last.]

BTW, @pjhill , is our browser/device support standards still purely based on traffic %s?

iPhone 13 (iOS 15):
![2022-02-23_11-14-29](https://user-images.githubusercontent.com/587583/155382060-7111fb18-027c-43c2-8841-71e116f584ed.png)

iPhone 12 (iOS 14):
![2022-02-23_11-09-56](https://user-images.githubusercontent.com/587583/155381047-19373dad-5a1b-4cdf-b5f5-8262702542d8.png)


iPad gen9 (iOS 15):
![2022-02-23_11-25-47](https://user-images.githubusercontent.com/587583/155383529-89910e77-dce3-4eed-94d2-6f3a8b81e92b.png)

iPad gen8 (iOS 14):
![2022-02-23_11-29-30](https://user-images.githubusercontent.com/587583/155384127-3477718b-f0a2-4af3-bd52-e6e1d9ff266c.png)

**Comment by longmd** [comment]
@tlei123, thanks for that update! That give me a good place to start with this.

**Comment by tlei123** [comment]
@pjhill , acc. to GA these last 30 days, **iOS 14** traffic's only around **0.047%**.

Is our support threshold still 0.5%?

**Comment by tlei123** [comment]
@longmd , another FYI...  It's the iOS version more than the phone-model.  i just checked my own iPhone 12 (w/ iOS 15) and the close-box did show up.

iPhone 12 (iOS **15**):
![2022-02-23_13-49-47](https://user-images.githubusercontent.com/587583/155406154-d5057df8-f38f-475f-ad9e-e7236cbd491b.png)

**Comment by pjhill** [comment]
> @pjhill , acc. to GA these last 30 days, **iOS 14** traffic's only around **0.047%**.
> 
> Is our support threshold still 0.5%?

In the context of IE11, that has been our support threshold. I can't point you at a publicly documented official decision that indicates that's the threshold generally.

**Comment by longmd** [comment]
@tlei123 , the fix for this is available in all environments - dev/staging/prod. I have validated on BrowserStack and we are back in business.

**Comment by tlei123** [comment]
Validated on Staging.  Bug fixed on iPhone & iPad, iOS 15 & 14.  Thanks, @longmd !

**iPhone 13 (iOS 15)**:
![2022-03-02_11-00-23](https://user-images.githubusercontent.com/587583/156420906-31258342-e59e-46f8-977d-4822bc3794e0.png)

**iPhone 12 (iOS 14)**:
![2022-03-02_10-41-25](https://user-images.githubusercontent.com/587583/156418010-f5443c53-c5bd-441a-ac7d-6750bb6b7089.png)

**iPad gen9 (iOS 15)**:
![2022-03-02_10-57-15](https://user-images.githubusercontent.com/587583/156420458-8d65218c-c298-4f93-9955-a7396841d10a.png)

**iPad gen8 (iOS 14)**:
![2022-03-02_10-53-31](https://user-images.githubusercontent.com/587583/156419897-d961866c-ff88-42cb-8d60-9d72d0c046fb.png)
