### ISSUE TITLE
Access for Napoleon Kernessant

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#33845]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Napoleon Kernessant

### Your Email

napoleon.kernessant@gcio.com

### Name of Your Team

Facilities

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1kXskCyrzs+uI19yPKaykl2RwVjG2AVT2ytXLi2+soc+rRFkUMG2FR3CpXGyI1bxTmsKnfQUSeIv6zKarWo9KCkEMzOxjSxyTioGuPVsSBiQkOYa5lHu33nLkoOSeKFthV1XB2juCWhGllmKGJzpc1rQER52QLS0ca1AJUGSyjNKXtNbkbe9kcH3o51bxX617GXixixEzxr872NY4tcNMRVAl5H0OcRrMCebcFMPHKt2brFt1lwv+yHNGLJHrVTX1bH2VQQw06j6MubHdZgUlL5g9QUmjrQYAFfjy4nNb6ui6h78kW7tbYJm6RedwHMU6tpOw78vfnGUaiGY2nolf0L1fFxUJzDEu7DppbwB5vwNwhX10w/n8VWhVeMx2/6V9Fa1EewKc4YE7anzeDGG7JBo9U7fQEVtPtJoUwa6tc6vQ2092iGK1I1MqlqVaeikSTdLYT0WEcM96/tNlESu3bFuQkofg1rPMB4dF/AWdjVG88Tg3hXVI+G+BvL0vLok= nkernessant-c02yj3jmjhd2@Nkernessant-C02YJ3JMJHD2s-MacBook-Pro.local

**Comment by omgitsbillryan** [comment]
Socks has been granted. Please reach out in #vsp-platform-support if you need further assistance.
