### ISSUE TITLE
[Bug] [IE11] Medical Copays - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#33844]
## What happened?
In **Windows IE11**, on **[Staging Medical Copays](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details)**, the following content/styling anomalies were found:
(1) On **Overview** page, **COVID-alert** was not styled as expected, and missing close button.
(2) On **Detail** page, **accordion subsection togglers** were missing.

## Specs:
- Device: Windows 10 desktop
- Browser: Internet Explorer 11
- Test User _(if applicable)_: `vets.gov.user+81@gmail.com` (Travis) [for passwords see [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc]

## Steps to Reproduce
- Use **Windows Internet Explorer 11**
- URL: https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details
- Test User _(if applicable)_: [see above]
- In an active-bill's **balance-card**, click **Check details...** link.
- (1) On **[Overview](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details)** page, observe that **COVID-alert** is not styled correctly, and close button is missing.
- In 1st active-bill (non-zero-balance) **balance-card**, click **Check details...** link.
- (2) On **Detail** page, under **How do I pay...** and **How do I get financial help...**, observe that **subsection titles/togglers** are missing.

**Screenshots (IE11)**:

**Overview** page:
![image](https://user-images.githubusercontent.com/587583/145321624-eb7f6baa-70e3-410d-b16e-d646eda85484.png)

**Detail** page:
![image](https://user-images.githubusercontent.com/587583/145314635-32cb4a32-fb38-47fb-a538-bc68789cf594.png)

## Desired content/styling
- [ ] **Overview** page, **COVID-alert** should be styled correctly, and close button should be displayed.
- [ ] **Detail** page, subsection titles/togglers should be displayed, and working.

## Acceptance Criteria
[see **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by craigwheeler** [comment]
@tlei123 these issues also seem to be related to problems with the following [design system components](https://design.va.gov/components/)

- [va-alert](https://design.va.gov/components/alertboxes)
- [va-accordion](https://design.va.gov/components/accordions)

**Comment by denisecoveyduc** [comment]
@tlei123  If these two IE11 issues are in fact design system component should we reassign this issue or close and make a new one so we can close out the staging review epic?

**Comment by tlei123** [comment]
@denisecoveyduc , yes, please re-route to Design Systems team.  Thanks much!

**Comment by denisecoveyduc** [comment]
Hey @caw310 We wanted to pass this ticket over to you since this seems to be a design system component not something for the VSA Debt team to resolve. Let us know if we can assist at all.

**Comment by jamigibbs** [comment]
@caw310 @k80bowman  Could this ticket potentially be closed with IE11 no longer being supported? https://dsva.slack.com/archives/CBU0KDSB1/p1659124057949649

**Comment by tlei123** [comment]
^ PTEMS-QA says yes.  :)
