### ISSUE TITLE
Adding Shibu Shamsuddin to DSVA Slack

### ISSUE THREAD

**Issue by zinalpatel09** [department-of-veterans-affairs/va.gov-team#33847]
This request is to add Shibu Shamsuddin (shibu.shamsuddin@thoughtworks.com) as a Full member

Description: Shibu Shamsuddin is a Developer on the Long Covid project. In order to do his job efficiently, he needs slack to help him keep up to date on any communication and activities for the project.

Please also add Shibu to these Channels:

#health-care-products-all-teams
#long-covid-public
#long-covid-team

**Comment by LizCallaghan** [comment]
done!
