### ISSUE TITLE
[Bug] Medical Copays - Detail page - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#33843]
## What happened?
On **[Staging Medical Copays](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details)** - Detail page, the following content/styling anomalies were found:
1. **How do I pay...** section > **Option 3** section: Note re. pay-stubs said "**...print it below**".
2. **Notice of rights...** modal > **Pay your bill** section > **By Mail** bullet-item: "payment stub" was missing a period before next sentence.
3. Same modal > **Notice to customers** section, 1st sentence "**...payment asa check.." is missing a space between "as" and "a".

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vets.gov.user+81@gmail.com` (Travis) [for passwords see [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc]

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details
- Test User _(if applicable)_: [see above]
- In an active-bill's **balance-card**, click **Check details...** link.

- On **[Overview](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/balance-details)** page, in 1st active-bill (non-zero-balance) **balance-card**, click **Check details...** link.
- On **Detail** page, under **How do I pay...**, click **Option 3...** to expand accordion.
- (1) In expanded section, observe that the **Note** re. paystubs say "**...print it below**".
- Under **What to do if you have questions...**, click **Notice of rights...** link.
- In **Notice of rights...** modal:
  - (2) Under **Pay your bill** section, in **By Mail** bullet-item, observe that 1st sentence (ending in "**...payment stub**"), is missing a period.
  - (3) Under **Notice to customers..** section, observe that 1st sentence "**...payment asa check...**" is missing a space between "as" and "a".

### Screenshots
(1) **How do I pay...** section:
![image](https://user-images.githubusercontent.com/587583/145309919-37c8b736-7f02-4881-bc8d-e33e00a0bc8d.png)

(2) **Notice of rights...** modal > **Pay your bill...** section:
![image](https://user-images.githubusercontent.com/587583/145310008-d23e2cea-53ef-42cb-a5cd-2ace909295a3.png)

(3) **Notice of rights...** modal > **Notice to customers...** section:
![image](https://user-images.githubusercontent.com/587583/145311930-4c5b9411-fdf7-4656-94f2-c64f86f3723c.png)

## Desired content/styling
- [x] (1) **How do I pay...** section > **Note** re. paystubs should say "**...print it above**".  [Download section has been moved up.]
- [x] (2) **Notice of rights...** modal > **Pay your bill** section > **By Mail** item, "**...payment stub**" should have a period at end of sentence &mdash; "**payment stub."
- [x] (3) Same modal > **Notice to customers...** section, "...payment asa check transaction..." should have a space between "as" and "a" &mdash; "**...payment as a check transaction...**".

## Acceptance Criteria
[See **Desired content/styling** above]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by craigwheeler** [comment]
@tlei123 merged updates and verified changes on staging if you'd like to verify and close when you get time thanks!

**Comment by tlei123** [comment]
Closed as fixed.  Validated on Staging.
