### ISSUE TITLE
Adding Holly Hansen to DSVA Slack

### ISSUE THREAD

**Issue by zinalpatel09** [department-of-veterans-affairs/va.gov-team#33848]
This request is to add Holly Hansen (holly.hansen@thoughtworks.com) as a Full member

Description: Holly Hansen is a UX Researcher on the Long Covid project. In order to do his job efficiently, she needs slack to help him keep up to date on any communication and activities for the project.

Please also add Holly to these Channels:

#health-care-products-all-teams
#long-covid-public
#long-covid-team

**Comment by LizCallaghan** [comment]
done!
