### ISSUE TITLE
[Content review:] Update podiatry language

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3384]
As a veteran, I want to understand that I should only select podiatry as a type of care if I think I may be eligible for community care so that I don't run into a dead end while trying to schedule my appointment.

AC
- [ ] Content snippet exists for podiatry selection on the type of care page in vaos.

**Comment by peggygannon** [comment]
@markgreenburg @lalexanderson-dsva  
Here are some content recommendations for Podiatry. I'm unable to get onto staging to see the **Type of Care** screen and where podiatry is listed, so I might need to tweak further once I get access to staging. Please let me know your thoughts. 

Option 1: 
- Keep Podiatry in the type of care list and update it to: 

{radio button} Podiatry (only available online for Community Care appointments)

- Add note to below the type of care list: 

**Please note:** If you want to schedule a VA podiatry appointment, please [call your local VA medical facility](va.gov/find-locations/).

Option 2: 
- Remove Podiatry from the type of care list. 
- Add note to below the list: 

**Please note:** Podiatry appointments can only be scheduled online for Community Care appointments. If you want to schedule a VA podiatry appointment, please [call your local VA medical facility](va.gov/find-locations/).

**Comment by peggygannon** [comment]
@markgreenburg @lalexanderson-dsva hi,there. I'm able to get on staging and I think for the Podiatry wording, I would recommend Option 1. 

My concern is that if we remove Podiatry from the list and just put it in a note, that people won't see it. They'll miss the note below and will think Podiatry isn't an option offered (even if it's only for a handful of users.

**Comment by lalexanderson-dsva** [comment]
We should not remove podiatry from this list, we should definitely keep it. They are working actively on adding it for VA.gov. I think Option 1 makes the most sense.

**Comment by peggygannon** [comment]
I'm closing this issue, as the edit to Podiatry is now captured in this ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3631
