### ISSUE TITLE
Alter mock MPI to be pre-check

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#33854]
This is a nice-to-have, but we should continue investigating how we could modify the plugin or come up with a different solution to making mock MPI be a pre-check rather than a post-check. This way, the user wouldn't be created in Keycloak and we won't clutter up the user pool with non-VA identities (at the very least, there might be other benefits).

Done when: I can attempt to log into a client with blocked credentials and then log into Keycloak and see that a user was NOT created.

**Comment by ken-non** [comment]
Did not work with Keycloak, will need to do something like this, but not this specifically.
