### ISSUE TITLE
Integrate with Splunk

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#33859]
Splunk exists at the VA and was described as a SIEM tool in this conversation: https://dsva.slack.com/archives/C02GQ27HXQW/p1636037003059900

IF DEEMED NECESSARY, we should integrate with splunk.

**Comment by ken-non** [comment]
VA will probably require this eventually - but will close for now.

**Comment by kjduensing** [comment]
deprioritize
