### ISSUE TITLE
Research: Are the logs in keycloak enough info?

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#33856]
Keycloak provides logs out of the box.

- [x] Is this the correct info in terms of what a security (or other) audit would look for?

Out of the box, and default logging level it does not log what is needed.
If log level is set to "DEBUG" then MOST things required are logged. 
The stuff they would look for is outlined here: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2096234538/Keycloak+Logging+Details+and+Logging+Requirements#Audit-Logging-Events-required

- [x] If not, what else do we need?

The things not logged in keycloak, are the update actions. It logs that an update has occurred, and the resource type that was updated, but it does not list what was updated on the resource. 
For example, from the log you can tell 
"The user with id 43623-234523-5432-4554 was Updated at this time, by the user with id 002332-32223-4444-4444"
But you cannot tell that the user was enabled/disable, or what attributes were updated. Same with roles, groups, and clients. 

So if we need to be fully audit-compliant for MVP, we need to figure out a way around this. I have idea, but we should meet to determine if we need to do it now first.

- [x] (redundant) How do we access those logs? 

Loki. As long as the log level is set to debug, all logging should automatically go to loki (streamed from the k8s pods stdout log)

duplicated by #36337

**Comment by ken-non** [comment]
set debug logs in in keycloak

**Comment by kylesoskin** [comment]
I will look into this. It would be helpful if we had a list of "what a security (or other) audit would look for?"

If not, who would know this that I can ask? Would Thomas know and/or have a had list of requirements for audit? Or is it not known, and I should just ask around/do some googling?

**Comment by kylesoskin** [comment]
Just as an update, I slacked with Troy Mosher today. He is going to get me an official list of all access management logging and retention requirements for audit compliance. He is getting them out of the:

"NIST controls and VA policy in our System Security Plan"

He plans to deliver on Monday. I can then crossref and remediate anything missing and/or do more keycloak research as required to ensure compliance is met.
