### ISSUE TITLE
Research: Roles & policies - what can we automate?

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#33853]
Right now, there is a lot of manual creation of roles in Keycloak. Can we automate this? What would it take?

**Comment by calquisola** [comment]
Keycloak has a rest admin api that allows us to automate adding of users, creating roles and assignment of roles. 

Roles
https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_roles_resource

Users
https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_roles_resource

**Comment by calquisola** [comment]
We can also customize and extend this by using the keycloak binary/lib.

This is well explained in this article. 
https://medium.com/chain-analytica/keycloak-work-with-client-roles-in-spring-boot-a34d74947c93
