### ISSUE TITLE
Research: Splunk

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#33858]
- [ ] What does Splunk do?
- [ ] How do we (users) access Splunk?
- [ ] How could we integrate with Splunk?

**Comment by ken-non** [comment]
paging @kjduensing  Harshil is out for the next few weeks.

**Comment by kjduensing** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2023260209/Splunk. Still need to address the question of how AMT might integrate with the existing VA cloud-based Splunk.

@td-usds do you know who we need to talk to to integrate Keycloak -> Splunk when we're ready?

**Comment by kjduensing** [comment]
backburner until we can complete research

**Comment by ken-non** [comment]
VA will probably require this eventually - but will close for now.

**Comment by kjduensing** [comment]
Deprioritize
