### ISSUE TITLE
[Content styleguide ]- Content doesn't align with style guidance in VA.gov content style guide (05.08.3)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33865]
#### VFS team name
AFS Education

#### VFS product name
GI Bill Comparison Tool

#### Point of Contact/Reviewers (Practice area)
Randi Hecht (Content) 

---

### Platform Issue
Content doesn't align with style guidance in VA.gov style guide

### Issue Details
We don't use sighted language like "See" and "View" 

### Link, screenshot or steps to recreate
<img width="354" alt="Screen Shot 2021-12-09 at 10 10 33 AM" src="https://user-images.githubusercontent.com/48728214/145422096-e9592f29-c846-4943-911c-194fc571a77c.png">

![Screen Shot 2021-12-09 at 10.41.53 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/84bf6dc3-4ad1-4844-a00d-ed97b000b4b7)

### VA.gov Experience Standard

[Category 05, Issue 08 ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
 

### Other References
WCAG SC 3.2.4_AA

---

### Platform Recommendation

Suggested changes: 

Find more
Check the current housing allowance payment rates

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket. 

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by mrblanco1** [comment]
Closing this issue since all "See more" links have been removed through a different ticket. Abe B.

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/ac55e028-64b2-4583-87e1-a39d11622409)
