### ISSUE TITLE
Remove "Latitude/Longitude Issues" section from GIDS

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#33864]
Given we are updating our geocoding process to geocode on save of institutions, we want to remove the census latitude longitude section and all associated back-end code to prevent existing correctly geocoded items from being overwritten. Please remove it from GIDS (https://staging.va.gov/gids) . This is in the gibct-data-service project

Screenshot attached![Screen Shot 2021-12-09 at 9.54.01 AM.png](https://images.zenhubusercontent.com/60e8347034d7f9aecbba74bb/4c7c585d-7666-4b5c-990e-05a9f6bafdaa)

**Comment by mrblanco1** [comment]
Circling back with Brian G. to see if this is something we want to pursue.

**Comment by mrblanco1** [comment]
Per Brian G. this ticket can be closed as he will not be impacted by this change.

**Comment by mrblanco1** [comment]
Brian G. confirmed we can move forward with this change as he will not be impacted.

**Comment by nbarthelemy** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/873

**Comment by dbarnes-VA** [comment]
Moved to In Progress, currently still seeing the "Latitude/Longitude Issues" section display in https://staging.va.gov/gids/dashboards

**Comment by af-manish** [comment]
There are issues with deploying on GIDS to allow this to be QAed. @PJart is working with platform, but there will not be activity until after Jan 4, 2022 due to lack of resources on the platform team..

**Comment by dbarnes-VA** [comment]
Test Run: https://dsvavsp.testrail.io/index.php?/runs/view/2809
Test Script:

**Comment by dbarnes-VA** [comment]
Tested on https://staging.va.gov/gids/dashboards
"Latitude/Longitude Issues" section has been removed from GIDS.

**Comment by mrblanco1** [comment]
UATd and passed on 1/06/2022
