### ISSUE TITLE
Research: User pool generation

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#33861]
Per Thomas, one way we could side-step MPI integration for now is to generate the user pool of existing users initially, and from then on perform a manual onboarding step for new users.

- [ ] How would we get the users who need to have access?
- [ ] Is there an API we could integrate with?
- [ ] How related to this is figuring out how to create or find a "source of truth" team manifest?

**Comment by calquisola** [comment]
For our source of truth,  we can start with the list of people with sock access and also we can get the I AM credentials.

**Comment by calquisola** [comment]
Team needs to have a discussion on how to save the list in a datastore and keep the data updated.
