### ISSUE TITLE
[Content styleguide] - The content isn't written in plain language and contains excess words and modifiers (05.05.2)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33872]
#### VFS team name

AFS Education

#### VFS product name

GI Bill Comparison Tool

#### Point of Contact/Reviewers (Practice area)

Randi Hecht (Content)

---

### Platform Issue

The content isn't written in plain language and contains excess words and modifiers

### Issue Details

The "learn more" modals in the left column and the institution comparison should be further reviewed for plain language. We should avoid using words like "fraudulent," "scope," "regulatory or legal scrutiny" among others. 

### VA.gov Experience Standard

[05.05](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation

My suggestion is to open a Sitewide Content intake request for the team to review the larger areas of text to make sure it meets plain language standards.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket. 

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by mrblanco1** [comment]
Brian to do some research in GIDS - caution flags. 3/24/2022
Most of the recommended words might be able to be updated, but some will not since they come directly from the Department of Education.

**Comment by mrblanco1** [comment]
Brian Grubb with VA EDU confirmed these type of words come from the Department of Eduation and therefore neither VA EDU Brian Grubb or AFS can update them.
