### ISSUE TITLE
Add follow-up page to request flow when veterans select podiatry but are not CC-eligible

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3391]
The VA does not currently support online scheduling podiatry appointments (but will in a few months). However, podiatry is still eligible within CC care, so should be selectable from the Type of Care page. When a veteran selects podiatry but is then _not_ community care eligible, we need to show them a follow up page asking them to go back and make a new selection (or maybe call their VA?), so that they can continue booking their appointment.

**Comment by rtwell** [comment]
@peggygannon @lalexanderson-dsva i think we've all asynchronously chatted about this screen: I think it should be a modal, like cancel, so users dont have to go back 

![image](https://user-images.githubusercontent.com/12564977/69096370-4ae66380-0a22-11ea-8efa-24098c48e1d0.png)

**Comment by markgreenburg** [comment]
@jbalboni would love some input on this approach and how much of a lift it is. Also probably want to standardize the approach for this with VA appointments where no facility in your system supports the type of care you want.

**Comment by jbalboni** [comment]
It would be easier for this to be its own page, but this is doable, too. I'm not sure this approach would work for the facility/system messages, though.

**Comment by peggygannon** [comment]
@markgreenburg @rtwell 
Please see below for updated messaging for the podiatry follow-up screen/modal


**You can’t schedule a podiatry appointment right now**
At this time, podiatry appointments can only be scheduled online for Community Care appointments. To schedule a podiatry appointment at a VA facility, please call your local VA medical center, or use the [facility locator tool to find your nearest VA medical facility](va.gov/find-locations).
