### ISSUE TITLE
[Tier 3] VA Benefit Letter Issue - SF 06354811

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#33918]
## Issue Description
_Caller is experiencing issues when attempting to download VA benefit letter on VA.gov_

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
This sounds like the Veteran is having difficulty logging in. Is that correct? Or is it they there is a problem with letter afterwards?

**Comment by Kimberley2019** [comment]
Case Notes from Salesforce:
Veteran was calling in because when he tries to download his benefits letters it asks him to log in. He does it with his ID.me account and it takes him to the authenticating site, then back to VA.gov, where it then asks him to sign in again. He is stuck in this loop. Made sure he is using a desktop and Google Chrome. Had him clear his cache and cookies, and tried again. He is having the same issue. Escalated to tier 2. Gave him the number to the NCC and transferred him there to get the letters.

**Comment by Kimberley2019** [comment]
@vhenry07 it seems as though he can get to the portion to download, but when he tries, it tells him to login again and then it begins to loop him.

**Comment by Kimberley2019** [comment]
@vhenry07 any updates on this ticket?

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders 

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by Kimberley2019** [comment]
Case closed.
Assistance provided
