### ISSUE TITLE
Discovery: Identify which REACT components to convert to web components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33927]
Identify the remaining components we should migrate from REACT to Web Component. 
Measure the impact of the components to decide which to migrate from REACT to WC. 

- [x] Review component usage report 
- [ ] Assess impact of existing REACT components
- [x] Identify which REACT to convert to web components

**Comment by bkjohnson** [comment]
Table of components which we would like to prioritize developing as web components (green):

https://vfs.atlassian.net/wiki/spaces/DST/pages/2040332297/React+components+to+web+components
