### ISSUE TITLE
Rework the navigation of design.va.gov

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33924]
As discussed with Ryan, let's rethink the top navigation for design.va.gov. 

- [x] Work with Meg on top navigation
- [x] Consider combining some of the tabs such as components, utilities and patterns
- [x] Create a document with the proposed new top navigation 
- [x] Share navigation with DST

### High-level navigation changes
- [x] Bring Experimental components and patterns into their respective sections
- [x] Clean up Patterns by creating a new Templates section and moving non-patterns to the appropriate section

**Comment by humancompanion-usds** [comment]
Meg and Mikki put together some IA recommendations:
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1626728596606/b28ee6edd4513fa17754c0f021ed53b1bc63dbee?sender=u9ae4d29a0ed5c3d2753a7824

For the most part I agree with their assessment but that are a few things that give me pause. For one, I'm not sure devs will look under Visual Design for layout and grid. There also should be a section for page templates and layouts which are currently mixed into Patterns. I'd like to take this and build upon it and incorporate some feedback from front-end-devs on the team or on the platform. Perhaps a short card sort in Mural would help.

**Comment by humancompanion-usds** [comment]
I've created new tickets for related issues. This is now in review while we collect feedback from users.
