### ISSUE TITLE
Business intake form for Debt Resolution: FSR Submission Confirmation Email

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#33925]
## Requestor Name
Debt Resolution Team

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
Provide veterans a confirmation of their submission.

## What is an overview of the notification use case? (required 3-5 sentences) 
Notify veterans when they have successfully submitted the Financial Status Report (FSR). 

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
Once a Veteran submits their Financial Status Report (FSR), a notification will be sent to their email. We'll also notify them on the submission confirmation screen that they can expect an email notification. This will provide reassurance that their form was been correctly submitted. Additionally, Veterans have expressed in previous usability studies that they would take a screenshot of the confirmation page as proof it was submitted. By providing them an email notification, they'll be provided that submission confirmation in a more empathetic and accessible format.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No

## What kind of notification would this be? (required Email, Text, Not sure)
Email

## If you have a draft of the content you’d like to send - please upload here. Please note we collaborate with all of our users on their content to ensure it meets standards. (optional - blank) 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/FSR-Submission-Email-dt-edits/products/Debt%20Resolution/Financial-Status-Report/Notifications/FSR-Submission-Email.md

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
No

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
vets-api

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes, the business logic is to send the notification on submission of the form.

**Comment by denisecoveyduc** [comment]
@bevnobev @rileyorr is right the unauthenticated FSR is on our roadmap currently slated for Q322 so what you mentioned on the call about ensuring an email is asked for on the form is a good thing to highlight. We will keep it in mind that the notifications may be impacted as we get closer.

**Comment by denisecoveyduc** [comment]
@miabecker Could you please add the following debt team members: 

Denise Coveyduc -  denise.coveyduc@gcio.com
Scott James - scott.james@gcio.com
Riley Orr  - riley@amida.com
Justin Linn -  justin.linn@gcio.com
Craig Wheeler -   craig.wheeler@gcio.com

**Comment by miabecker** [comment]
@miabecker will send link and then we'll assign folks to DMC service with edit capabilities and read only to VA.gov that way they can copy content.

**Comment by miabecker** [comment]
@miabecker checking in with the team on this.

**Comment by mjones-oddball** [comment]
@denisecoveyduc I agree, thanks for looping back to this ticket!
