### ISSUE TITLE
How do we follow up from quarterly satisfaction surveys

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#33929]
As a member of the SD team, I want a process to follow when following up with people who leave their information on the quarterly satisfaction survey so we can know what value we expect to get out of it and do it consistently. 

AC:

- [ ] Define who we follow up with
- [ ] Define the value we'd get from it
- [ ] Define process 
- [ ] Define how it fits with what's currently on the roadmap

**Comment by Khyatinp18** [comment]
Andrea and Rachael suggested not to work on this so no longer this issue is needed, closing it now
