### ISSUE TITLE
Check Community Care Eligibility

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3394]
As a veteran, I want to be able to request a CC appointment only if I'm eligible, so that I don't accidentally schedule something that I shouldn't have.

AC
- [ ] Front end checks CC eligibility using vets-api's community-care service
- [ ] Front end checks CC scheduling support of facilities in chosen system using vets-api's community-care-supported-sites service
- [ ] Veterans who are both CC-eligible and have a facility within their chosen system that supports CC scheduling are able to choose CC care
- [ ] Veterans who either are not CC eligible or are not in a system that has any sites which support CC scheduling do not get the CC / VA choice page

**Comment by jbalboni** [comment]
One other thing to note: the CCE api requires a type of care for each request, and those types of care do not match the VAOS CC types of care. So we need to map each type before making the request. 

They seem to have obvious matches, but need to make sure we take this into account.

Types can be viewed here: https://developer.va.gov/explore/health/docs/community_care?version=current
