### ISSUE TITLE
Quality Assurance Feedback - Midpoint Review - Personal Information Revision

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#33949]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- These [test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile-personal-info.md) are looking good! I'd recommend going through the effort of putting these into TestRail. Also, is there any reason in particular that you recorded these tests in va.gov-team-sensitive? I'm not seeing any sensitive information in the tests.
- These [regression tests](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=63&group_order=asc&display_deleted_cases=0) look useful, are you going to be running these or adapting them for future use for this effort?

**Consider:**
None

**Comment by MarciMcGuireGCIO** [comment]
@pjhill thanks!  I will enter them into TestRail.   The regression tests were, I assume, created for the MVP, so they will need to be adapted since this change will alter an existing page, the left-side navigation and will add a new page.

**Comment by MarciMcGuireGCIO** [comment]
No QA changes needed
