### ISSUE TITLE
Recurring Events URL structure for Outreach & Events from Public Websites Team

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33953]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [X] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
- Link to or attach user flows: [User Flow | Designs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts)
- Link to prototype or mockups: [Prototype](https://bit.ly/3FYjFsE) 
- Link to any epics/issues that may be helpful: [EPIC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28918) 
- Context: Public Websites team is working on a Filtering/Recurring events MVP for outreach and events, the challenge is determining URL structure for the recurring events as we want to get the best SEO possible but also keep them as simple as possible.

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: January 2022 (DTG TDB)
- Estimated staging review date: January 7, 2022
- Content and IA work needed by: Dec 21, 2021

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [X] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: David Conlon
-	Product manager: Brian Lloyd
-	Designer: Cassandra Allen
-	FE engineer: Kelson Adams
-	Product/team Slack channel: #vsa-public-websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
A few notes from meeting with @kelsonic and @davidconlon 
- It was determined that the current H1 as URL approach is not sustainable going forward, and that SEO is not a huge concern for individual events.
- We also discussed that these events need to be treated as COPE content that can be uased not only as global events but also pulled into individual experiences such as VAMC site calendars. 
- a parameter based URL structure was discussed and determined the best approach, parameters will include the entityID and possibly date/time info  
- This should be discussed with CMS to determine impact of change from using H1 as URL to entityID/parameter based URLs
- It was determined that the event listing page design needs to accommodate the scenario of someone trying to go to an invalid/expired event URL to avoid a 404 experience.  
- Will need to discuss what needs to be done (if anything) for existing event detail URLs using H1s.  Per Kelson these will continue to go to the legacy version of the event page, is this an issue? Team agrees that we are not looking to do mass redirects, if we need to take these down, we will capture them with the new "not found" error message.

URL structure documented here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34556

**Comment by brianalloyd** [comment]
Clear on direction, going to close this ticket out in support.
