### ISSUE TITLE
Adding Ana-Costa1 to DSVA Slack

### ISSUE THREAD

**Issue by Ana-Costa1** [department-of-veterans-affairs/va.gov-team#33960]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Single guest

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
The following guest user Ana.Costa1@va.gov should be switched from single-channel to multi-channel guest and then added to vfs-platform-support

**Comment by LizCallaghan** [comment]
done!
