### ISSUE TITLE
[Tier 3] VA Benefits Letter Issue - SF 0657140

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#33961]
## Issue Description
_Caller is experiencing issues view VA benefit letters and other benefit items on VA.gov._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Case Notes
Veteran has a accessing the Information on the va.gov website-He cannot access his information on the website- it is as if a link/bridging is missing creating the issue of the Veteran not being able to access his Veterans Benefits information-he continually receives and error message stating the website is down, or the information is not present, the information cannot be accessed- Veteran is trying to access the va.gov- he has been trying to access the Benefits Letter or his payment history- He continues to give him an Error message stating he has no payment history or the ability to access the Benefits- He feels that somewhere the system and his account have a Disconnect problem- it is a hit or miss as far as his accessing his information- he cannot see things such as his disability rating, his Dependents, He has tried access his information from other systems- He has had the same issue with access his information on another computer. Veteran is also stating that when someone on the va.gov side try's to access his information the information is present. BUT HE CONTINUALLY HAS TRIED TO ACCESS THE INFORMATION WITH NO SUCCESS- WITH GETTING TO HIS BENEFITS INFORMATION, LETTERS, PAYMENT HISTORY.

**Comment by Kimberley2019** [comment]
From: Henry, Veronica (GovernmentCIO) <Veronica.Henry@va.gov> 
Sent: Friday, December 10, 2021 9:47 AM
To: Daniels, Kimberley N. (Oddball, Inc.) <Kimberley.Daniels@va.gov>
Cc: Self, Matthew <Matthew.Self2@va.gov>
Subject: RE: Would this be yours?

Hey Kimberly,

If someone else can access the information, but he can’t, sounds like something related to his particular profile or id. Feel free to open a ticket, but if you could provide the following, would help with troubleshooting:

-	Application ID
-	Date/time of issue
-	Screenshot of error message(s)


Thanks!

**Comment by Kimberley2019** [comment]
From: REDACTED
Sent: Friday, December 10, 2021 10:30 AM
To: Daniels, Kimberley N. (Oddball, Inc.) <Kimberley.Daniels@va.gov>
Subject: [EXTERNAL] RE: VA benefits letter issue

SirMa’am,
My assumption on the problem is that there is an account level disconnect somewhere in the system (or a second account that I am unaware was built?).  I have tried to access on Android, Edge, Chrome, and Explorer, all with the same results.  I have tried multiple computers from a variety of networks, no change.

Prior to my retirement processing, the only interaction with the VA that I had was receiving my initial VA Home Loan letter, which may have been done using another account (most likely under REDACTED).  This error may exist due to a separate account (that I have no record of, and was most likely built while I was deployed to facilitate receiving the letter).

Disability File Number:  REDACTED

Date/Time of Issue:  Constant since August 2020 (from my initiation of my VA account for retirement).

3 Screenshots attached.

I can access parts of VA.gov and EBenefits.gov just fine.  I have changed/validated mailing address, bank account information, applied for and received my Veterans ID card, applied for and received VGLI, and reviewed other insurance related programs without error.

I have a valid, completed compensation claim.  The Claim Status screenshot shows one does not exist.  I have never been able to see or monitor my claim status since initiation through completion.  My Veterans Service Organization (VSO) Agent and VA personnel I’ve talked with on the phone have all been able to see and monitor my documents and claims, but have been unable to help resolve why I cannot access them online.

I received my first disability payment on 1 December, but the system still shows no record of payment.  DFAS shows the payment for my retirement Earning Statement.

I can confirm my mailing address for the VA Letters, but when I go to try to select them, I am receive the same error as listed in the screenshot.  

Feel free to call to assist in resolving this.  

Respectfully,
Jared S
Phone Number REDACTED

**Comment by Kimberley2019** [comment]
From: VA Technical Support 
Sent: Friday, December 10, 2021 1:12 PM
To: REDACTED
Subject: RE: [EXTERNAL] RE: VA benefits letter issue

Good Afternoon Mr. REDACTED,

Thank you for your response and for this helpful information. We appreciate your patience as we find a resolution to your problem. I have passed these details along to the appropriate team to review.  

The team may reach out to you directly if additional information is required.  Once the process is complete, they will reach out to you directly and inform you.  

Due to this process being managed by another team, we are unable to provide an exact timeframe of when this may be resolved, however, if you feel the need to check on the status, please respond to this email and we can follow up accordingly.

Thank you for your understanding. 

Reference Number: 33961

Please click here for additional information about VA.gov and its resources.




Kind Regards,

VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders any updates on this ticket?

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders 

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by cnemeth** [comment]
Closing ticket. We don not have sufficient info to trace issue.
