### ISSUE TITLE
[Safari][MacOS] - Inner content of widget violates the top of the modal

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#33972]
### **Description**
On VA.gov, the "Sign In" text at the top of the modal is violating the upper bounds of the text area.

### **User Story**
**As a** va.gov Product Owner
**I want** the modal text to properly align with the text of the modal
**So that** users have the desired experience

### **Repro Steps**
1.) Visit va.gov (Mac OS, Safari)
2.) Click "Sign In"
3.) Modal pops up

**What happens:** Text violates upper bounds of modal (see image below)
**What should happen**: Text should stay within bounds of modal

### **Acceptance Criteria**
- [ ] Text stays within bounds of the modal

### **Notes**
This issue was reported by @codyreinold-usds, full text of report below:

_in Safari, on MacOS, the inner content of the widget violates the top of the modal when scrolled. when I scroll the widget, I see a few pixels that appear above the modal, only in the center 80% where content is held. content should not extend past the top of the modal._!

**Media**
[2.png](https://images.zenhubusercontent.com/609e8d5b852e7429aab750c8/0ebfe9cf-13dc-4b6a-ae43-fcc494422329)

**Comment by Kwoly** [comment]
Going to create a ticket for the design system team as this is an issue with the modal component as a whole. The issue arises from a browser rendering bug that occurs when an element has a scrolled overflow with a `transform: translate()` css property.

It is not necessarily fixable as it's an issue on the browser renderer, but it can be alleviated with a 1px white border top and bottom. We are going to leave it up to the discretion of the design system team to fix or not.

If they decline to want to take action, we can decide internally to "force" it in via our own code.

**Comment by Kwoly** [comment]
Created Issue for design system team: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/614

**Comment by nsoutouras** [comment]
1/19: Still Blocked - waiting for design system team: CLOSE NEXT SPRINT IF NOT RESOLVES

**Comment by nsoutouras** [comment]
Closing as design team has a ticket for this one.
