### ISSUE TITLE
[Reverse Proxy] Automated deployments to lower environments on change/commit

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#33977]
## The Problem
When teams wish to test changes to the revproxy, they must:
1. Make their PR
2. Get it approved by OPS
3. Get OPs to trigger the `dev` and/or `staging` revproxy Jenkins deploy

It's a needless interruption for the ops team and it blocks dev teams who just want to test.

## Extra Context
A support slack thread where a team is testing revproxy redirects - [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639158181290400)

## Work to be Done
- [ ] Modify the Jenkins job to run the full BRD when changes to "revproxy-related" files are modified in the `master` devops branch

**Comment by jhouse-solvd** [comment]
This is a duplicate. See #46249 for a newer issue relating to this need.
