### ISSUE TITLE
Iterate homepage designs based on stakeholder/VA feedback

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#33986]
- [x] Socialize iterated designs at scheduled design meetings, design office hours, or design intent meeting for VA stakeholder input
- [ ] Evaluate and  iterate or down-selected design suggestions
- [ ] Provide feedback on all down-selected design suggestions to VA-PO / VA-DL
- [ ] Iterate any design suggestions previously down-selected, if recommended by VA-PO

**Deliverable:** Iterated homepage designs

**Comment by jsing0** [comment]
Here is the link to the [Sketch Deck](https://sketch.com/s/7ddd2962-35f2-4f08-8c84-fe35ebb3476a)
& The [burnboard for tracking changes until the next official review](https://app.mural.co/invitation/mural/innovationboards1199/1638999763255?sender=u363f843c6d3533347d471444&key=11637cf0-4f15-4a11-8857-7e4c15110bad)

**Comment by jsing0** [comment]
Here is the [link to the burn board and tracking changes mural for Sprint 8](https://app.mural.co/invitation/mural/innovationboards1199/1640715601448?sender=u363f843c6d3533347d471444&key=eb3b6ed3-9e88-49d7-b140-2bcd232a7a1b)
