### ISSUE TITLE
Redirect Request for Vet Centers live as of 12/10/21

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33998]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

As the new Vet Center pages are rolled out, the legacy details pages for Facility Locator, Directory location pages and key staff pages need to direct Veterans to the new web presence. These requests will be made in bulk for the locations which have gone live in the previous two weeks.

Note: Outstations have their own Directory location and key staff pages but will be part of the new respective main Vet Center's Location page. Mobile Vet Centers do not have their own Directory location pages and are suppressed from the Facility Locator.

### Implementation date
No specific date - at your earliest convenience

### Redirects 

Current URL | New URL
-- | --
~https://www.beckley.va.gov/locations/princeton_vet_center.asp~ | ~https://www.va.gov/princeton-vet-center/~
www.va.gov/find-locations/facility/vc_0120V | https://www.va.gov/babylon-vet-center/
www.va.gov/find-locations/facility/vc_0136V | https://www.va.gov/cape-cod-vet-center/
www.va.gov/find-locations/facility/vc_0876MVC | https://www.va.gov/dubois-vet-center/
www.va.gov/find-locations/facility/vc_0227V | https://www.va.gov/dubois-vet-center/
www.va.gov/find-locations/facility/vc_0809MVC | https://www.va.gov/erie-vet-center/
www.va.gov/find-locations/facility/vc_0222V | https://www.va.gov/erie-vet-center/
www.va.gov/find-locations/facility/vc_0538V | https://www.va.gov/great-falls-vet-center/
www.va.gov/find-locations/facility/vc_05381OS | https://www.va.gov/great-falls-vet-center/
www.va.gov/find-locations/facility/vc_0648V | https://www.va.gov/guam-vet-center/
www.va.gov/find-locations/facility/vc_0804MVC | https://www.va.gov/lewiston-vet-center/
www.va.gov/find-locations/facility/vc_0129V | https://www.va.gov/lewiston-vet-center/
https://www.va.gov/find-locations/facility/vc_0606V | https://www.va.gov/los-angeles-vet-center
www.va.gov/find-locations/facility/vc_0138V | https://www.va.gov/nassau-vet-center/
www.va.gov/find-locations/facility/vc_0128V | https://www.va.gov/new-bedford-vet-center/
www.va.gov/find-locations/facility/vc_0115V | https://www.va.gov/portland-me-vet-center/
www.va.gov/find-locations/facility/vc_0232V | https://www.va.gov/princeton-vet-center/
www.va.gov/find-locations/facility/vc_0109V | https://www.va.gov/queens-vet-center/
www.va.gov/find-locations/facility/vc_0874MVC | https://www.va.gov/sussex-county-vet-center/
www.va.gov/find-locations/facility/vc_0243V | https://www.va.gov/sussex-county-vet-center/
www.va.gov/find-locations/facility/vc_0214V | https://www.va.gov/washington-dc-vet-center/
www.va.gov/find-locations/facility/vc_0220V | https://www.va.gov/white-oak-vet-center/
www.va.gov/find-locations/facility/vc_0215V | https://www.va.gov/wilmington-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=740&dnum=All | https://www.va.gov/babylon-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5618&dnum=All | https://www.va.gov/cape-cod-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5624&dnum=All | https://www.va.gov/dubois-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=587&dnum=All | https://www.va.gov/erie-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6075&dnum=1 | https://www.va.gov/great-falls-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6475&dnum=1 | https://www.va.gov/great-falls-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=767&dnum=All | https://www.va.gov/guam-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5435&dnum=All | https://www.va.gov/lewiston-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5470&dnum=1 | https://www.va.gov/los-angeles-vet-center
https://www.va.gov/directory/guide/facility.asp?ID=5960&dnum=All | https://www.va.gov/nassau-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5437&dnum=All | https://www.va.gov/new-bedford-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5438&dnum=All | https://www.va.gov/portland-me-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=400&dnum=All | https://www.va.gov/princeton-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=747&dnum=All | https://www.va.gov/queens-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6148&dnum=All | https://www.va.gov/sussex-county-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=503&dnum=All | https://www.va.gov/washington-dc-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=589&dnum=All | https://www.va.gov/white-oak-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5016&dnum=All | https://www.va.gov/wilmington-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=740 | https://www.va.gov/babylon-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5618 | https://www.va.gov/cape-cod-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5624 | https://www.va.gov/dubois-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=587 | https://www.va.gov/erie-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6075 | https://www.va.gov/great-falls-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6475 | https://www.va.gov/great-falls-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=767 | https://www.va.gov/guam-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5435 | https://www.va.gov/lewiston-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5470 | https://www.va.gov/los-angeles-vet-center
https://www.va.gov/directory/guide/keystaff.cfm?id=5960 | https://www.va.gov/nassau-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5437 | https://www.va.gov/new-bedford-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5438 | https://www.va.gov/portland-me-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=400 | https://www.va.gov/princeton-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=747 | https://www.va.gov/queens-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6148 | https://www.va.gov/sussex-county-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=503 | https://www.va.gov/washington-dc-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=589&dnum=All | https://www.va.gov/white-oak-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5016 | https://www.va.gov/wilmington-vet-center/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mmiddaugh** [comment]
formatted adjusted per Kelson

**Comment by mnorthuis** [comment]
A few minor corrections made per convo with Michelle.  

@brianalloyd this one is ready to go at your earliest convenience.  The ID parameter is the key parameter for the redirect in each of the parameter based URLs.  Thank you!

**Comment by brianalloyd** [comment]
Thanks @mnorthuis we'll scrub in now in support.

**Comment by kelsonic** [comment]
On it ✅ PR incoming

**Comment by kelsonic** [comment]
cross-domain redirect PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19709

other redirects PR: https://github.com/department-of-veterans-affairs/devops/pull/10452

**Comment by kelsonic** [comment]
All redirects (except cross-domain redirect) are now on prod, cross-domain will go out with daily deploy

**Comment by kelsonic** [comment]
CC @mmiddaugh

**Comment by mnorthuis** [comment]
That first redirect is invalid and I forgot to remove that one (https://www.beckley.va.gov/locations/princeton_vet_center.asp).   The original sub-domain is fully redirected to the new VAMC, so we can't redirect that specific page.

@mmiddaugh I don't see a Princeton Vet Center, but there is a Beckley Vet Center: https://www.va.gov/find-locations/facility/vc_0231V.  Can you confirm if this is the URL you want redirected to https://www.va.gov/princeton-vet-center/?

**Comment by mmiddaugh** [comment]
Princeton Vet Center is vc_0232V - it is published and can be directed. 
Beckley Vet Center is vc_0231V - it is _not yet_ published and should _not_ be redirected.

**Comment by mnorthuis** [comment]
Ok, that is already on the list above, so @kelsonic I'm removing the very top line from this redirect request.

**Comment by kelsonic** [comment]
Can we close this issue? All redirects are implemented 💯

**Comment by brianalloyd** [comment]
Looks great, thanks @kelson.  Closing ticket now in support.
