### ISSUE TITLE
[Design] My VA: Consider My VA structure design overhaul

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33994]
## Background

Sharing design thoughts around My VA structure as a whole

## Tasks

- [ ] Meet with Samara and team on thoughts around My VA as a whole, providing suggestions and topics of discussion

## Acceptance Criteria

- [ ] Elevate concerns, questions and suggestions of the My VA structure for improvements of use and visual presentation

**Comment by tressaellen** [comment]
All designs and comments will be in [this Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1638553268085/b0514c6d027e35eb98f636fa3c614872dd14b8a2?sender=tressafurner7646)
