### ISSUE TITLE
"You are here" progress meter

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#34]
- These are pretty consistent across forms, but a frequent source of questions from new folks.
- They track "chapters" rather than screens to create less jitter when conditional logic would change the number of screens a Veteran sees. 
- This falls down a bit when as we start embedding multiple forms in a single flow (e.g. 526)

**Comment by jaredcunha-usds** [comment]
Depending on how we break this down, this could be a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/50

Unless this how we describe multi-step forms with a progress meter at the top? But that can even be further generalized if we are describing the problem as "tracking progression" or something to that extent.
