### ISSUE TITLE
Sort, label, & organize VA900 errors in Sentry

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#340]
## User Story
As a member of the VSP triage team, I need to map VA900 errors in Sentry so that I can identify patterns that may lead to solutions to those errors.

## Goal
VA900 errors are accurately mapped 
Team members are able to use these mappings to identify trends if they exist

## Acceptance Criteria
- [ ] Modify error handling in vets-api such that VA900 are grouped properly

**Comment by alexpappasoddball** [comment]
Need to revise acceptance criteria and goals

**Comment by kfrz** [comment]
Closing this as we will approach on a case-by-case basis and open new issues as appropriate.
