### ISSUE TITLE
Add Report Option for Opted Out Vets

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#34007]
VAMC user requesting the addition a report that returns the number of veterans Opted Out of VEText by station/facility/etc.

**Comment by chancetheoriginal** [comment]
VAMC user requesting the addition a report that returns the number of veterans Opted Out of VEText by station/facility/etc.

**Comment by jwowk** [comment]
Don't track which station Veteran opts out to so there is no way to display a filtered report by station.
