### ISSUE TITLE
[Tier 3] Claim submission issue - SF 06228145

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34002]
## Issue Description
_Caller is having issues with submitting a claim_

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
From: REDACTED 
Sent: Friday, December 10, 2021 8:25 PM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: Claim submission issue

First of I followed all the steps it required. I am using an HP Pavilion. The browser is Chrome. 
The problem come when I go to summit. I get a message that says sorry it is taking so long to progress. We will send an email when it has been processed. But there is never a response back. It then remains as a intent to file. 

Get Outlook for Android
________________________________________
From: VA Technical Support <VATechnicalSupport@va.gov>
Sent: Friday, December 10, 2021 11:59:14 AM
To: REDACTED
Subject: Claim submission issue 
 
Good Afternoon, 
Thank you for your inquiry. Are you still experiencing this issue? If yes, we will need more information to investigate the problem and find a solution. In as much detail as you can, please respond to this email with answers to the following prompts and questions: 
 
•	Please provide step-by-step details of what actions you are taking and what happens when you do. 
•	Please copy and paste the URL or web address you were on when you experienced the issue.
•	If you saw an error message, please copy and paste the exact text of the error message.
•	What type of device are you using (i.e., Dell laptop, MacBook, iPhone, etc.)?
•	Try a different browser (i.e., Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all browsers?
•	What account do you use to sign into VA.gov (DS Logon, My HealtheVet, ID.me)?
 
Please click here for additional information about VA.gov and its resources.
 
 
Case Number: 06228145
 
 
 
 
 
Thank you,
 
VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
From: VA Technical Support 
Sent: Monday, December 13, 2021 10:06 AM
To: REDACTED
Subject: RE: Claim submission issue

Good Morning Mr. REDACTED,

Thank you for your response and for this helpful information. We appreciate your patience as we find a resolution to your problem. I have passed these details along to the appropriate team to review.  

The team may reach out to you directly if additional information is required.  Once the process is complete, they will reach out to you directly and inform you.  

Due to this process being managed by another team, we are unable to provide an exact timeframe of when this may be resolved, however, if you feel the need to check on the status, please respond to this email and we can follow up accordingly.

Thank you for your understanding. 

Reference Number: 34002

Please click here for additional information about VA.gov and its resources.




Kind Regards,

VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
From: Daniels, Kimberley N. (Oddball, Inc.) 
Sent: Monday, December 13, 2021 10:49 AM
To: Henry, Veronica (GovernmentCIO) <Veronica.Henry@va.gov>; Garrison, Robin E. (Government CIO) <Robin.Garrison@va.gov>
Subject: FW: Claim submission issue - ZH ticket created

Good Morning BAM,

Please see the PII listed in the email chain attached for ZH issue, [Tier 3] Claim submission issue - SF 06228145 · department-of-veterans-affairs/va.gov-team (zenhub.com)



Kind Regards,

Kimberley

From: VA Technical Support 
Sent: Monday, December 13, 2021 10:43 AM
To: REDACTED
Subject: RE: Claim submission issue

Good Morning Mr. REDACTED,

Thank you for that information.

I have redacted some of the information that you have provided to me for security purposes.  

I will provide this information to the team reviewing your issue.


Kind Regards,

VA.gov Technical Support Team

From: REDACTED 
Sent: Monday, December 13, 2021 10:40 AM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: Claim submission issue

This is my email but my correct name is REDACTED last four REDACTED
REDACTED

Get Outlook for Android
________________________________________

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders No movement on this case.

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by Kimberley2019** [comment]
Case 'In Progress'

**Comment by Kimberley2019** [comment]
Assigning new members/teams for historical purposes.
After review, case may be closed by either team/team members.

**Comment by Kimberley2019** [comment]
New Tier 3 benefits team review.  Modified follow up template sent.  Will reopen if/when user responds with needed information for resolution of issue.
