### ISSUE TITLE
Reorganize Call Center Github Documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3400]
## User Story or Problem Statement
How might we reorganize call center documentation in Github?

## Goal
Reorganize triage call center documentation for easier viewing and discovery.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [x] Create master list of all call center documentation across VA.gov-team repos
- [ ] Review list of call center documentation to remove duplication and consolidate articles
- [ ] Identify locations(s) for documentation to be stored
- [ ] Write new READ.me for call center repo

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@Kimberley2019 work with @clantosswett on AC.

**Comment by clantosswett** [comment]
I have created a document with all all the call center related document across triage, insights, and a few other places. Next steps will be to review the documentation and determine which articles are redundant, figure out ways to consolidate, and then determine where the final list of documentation should live. 

https://docs.google.com/spreadsheets/d/1y6gWc6lHvCOYoKxgM13wZwiSyt1yppiyjwv5Ar2eJvc/edit?folder=0AHNjNORlRrZHUk9PVA#gid=0

**Comment by Kimberley2019** [comment]
I have reviewed the document and given feedback on the documents that I have created or assisted in creating.
This has been sent to Matt for review and action.

**Comment by joanneesteban** [comment]
Insights has provided documentation to Content & IA. Closing this issue.
