### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#34013]
Hi Brian,
I'm a Product Manager who just joined Agile Six on the CMS Sitewide team. I would like to get access to GA. I found my way to this issue template. Below is my basic information, please let me know what else you need? Thank you.
Name: Wesley Rowe
Email: wesley.rowe@agile6.com
Phone: 323-313-5447
Github: wesrowe

**Comment by laurensimpson14** [comment]
Hi Wesley! You now have access to Google Analytics - you should get a welcome email 🚀 Feel free to re-open this request if you have any issues getting logged in!
