### ISSUE TITLE
On-Boarding | Set up Local Environment for VETS API

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34010]
## User Story

_As a new FE  I would like to have VETS API run on dockers in Window so I can create and test my code. 

## Acceptance Criteria

- [x] _Working environment established on dockers in Window on local machine

**Comment by lzapson** [comment]
Worked with platform support, needed to temporarily disable the winnat service, to resolve docker permission access errors
