### ISSUE TITLE
Infinite loop on logon with incorrect local time

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#34028]
### **Description**
A small subset of users are seeing an infinite loop on login to va.gov.  This appears to be caused when the user has their machine clock set improperly.

### **User Story**
**As a** va.gov user
**I want** to be able to log on, even if my local machine time is improperly set
**So that** I can access VA services.

### **Business case**
While the fix is relatively easy (have user set their clock to use automatic date/time), this results in a call to VA support, and the support staff identifying the issue correctly and relaying instructions to the user.  Best if we can find a fix that makes this unnecessary.  

### **Acceptance Criteria**
- [ ] User is able to log in with local time not set properly.

**Comment by nsoutouras** [comment]
12/13/21 Planning - Potential issues around detecting the cause of this issue.  
Best course of action now is to go through logs and detect how often this is occurring.  If it's frequent, we need to create logging that can notify help desk to hopefully solve this more quickly with veterans.  

**TO DO**
- [ ] Create ticket for logging work

**Comment by asg5704** [comment]
Closed as duplicate.
