### ISSUE TITLE
Draft Elixir Design Document

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#34027]
Provide technical details on:
- How it was selected
- Why it was selected
- Comparison to Ruby re: performance
- Current knowledge / skill level for Elixir on the VSP Identity team
- Any risks / concerns / unknowns

As an engineer I should be able to fully understand the decision behind choosing Elixir for the new sign-in service so that any potential risks or concerns are addressed as part of the integration into the current VSP infrastructure.

**Comment by joeniquette** [comment]
Draft: https://github.com/department-of-veterans-affairs/va.gov-team/pull/35283

**Comment by nsoutouras** [comment]
Team is going to do an RFC and create a research document and new design document.
