### ISSUE TITLE
Jenkins is running on degraded hardware set to be turned off on the 20th

### ISSUE THREAD

**Issue by rbeckwith-oddball** [department-of-veterans-affairs/va.gov-team#34020]
## Description
[AWS Events](https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Events:) will show you the scheduled event to disable the EC2 instance that is running on degraded hardware

## Background/context 
Jenkins is scheduled to be disabled since it is running on degraded hardware

---
## Tasks
- [x] Spin up a new instance and swap drives to the new instances (possibly with snapshot instead)

## Acceptance Criteria 
- [x] Old degraded hardware should be decommissioned after replacement

**Comment by jhouse-solvd** [comment]
As of now, here’s the high-level plan: 
- set a maintenance window for Wed 12/15 after 1800 ET
- reboot the server to get fresh ‘hardware’
- messaging goes out Wed morning, just before reboot, and once things are good to go
- Bill Ryan on standby to assist Ryan Beckwith if anything unexpected happens

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball - Can you please drop a note confirming what was done. If you can, please include a screenshot or details that verify that the machine is running on new "hardware". Thank you, sir! 

Also, please mark off the tasks and acceptance criteria. You can re-write them to be accurate as needed.

**Comment by jbritt1** [comment]
Jenkins was restarted and migrated to non-degrading hardware. Currently, only two Appeals/Caseflow owned instances are set for retirement. Reached out to them in https://dsva.slack.com/archives/CAM9FJ85P/p1642615456102800, but as for the scope of this ticket it is done. Closing.
