### ISSUE TITLE
Research paid vs. free data warehousing tools

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3403]
## User Story or Problem Statement
 How might we store historical data that we can't right now?

## Goal
Recommend technical approaches for storing historical data from multiple data sources

## Objectives or Key Results this is meant to further
- Launch Grey Sky Product Health Tool

## Acceptance Criteria
- [x] Insights hosts discussions with Platform teams (BE and/or Ops)
- [x] Insights reaches out to Joy W for VA team data warehouse usage
- [x] Insights summarizes use cases & platforms in a shareable deck
- [x] Update [Roadmap]( https://docs.google.com/spreadsheets/d/1tYzIGe3bWug8Ryy0MuaJ3ubNhPrYxSIxW_hGXEw0FYI/edit?usp=sharing) and [Tooling Sheet](https://docs.google.com/spreadsheets/d/1tYzIGe3bWug8Ryy0MuaJ3ubNhPrYxSIxW_hGXEw0FYI/edit#gid=0)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@joanneesteban @JoyOfTech @jonwehausen I set up time for the 4 of us to meet next Wednesday at 12:30-1. Thanks!

**Comment by joanneesteban** [comment]
@nedierecel please add spreadsheet!

**Comment by nedierecel** [comment]
@joanneesteban Updated the summary with the tooling sheet

**Comment by joanneesteban** [comment]
We should also loop in Andrew G and Nancy to the conversation and make sure we get weigh in from Ops on Prometheus needs.

**Comment by nedierecel** [comment]
Follow-up discussions: 

- The Analytics-Insights team will pull sample data values that would be stored in the data warehouse. As it will mostly be Google Analytics, call center summaries, and back-end data, these values will not store PII. This will be shared with Andrew

**Comment by nedierecel** [comment]
@joanneesteban I am going to close this issue and insert remaining notes into #1843
