### ISSUE TITLE
Receive MuleSoft creds for production

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#34030]
## User Story

As the 10-10 team, we need the new authentication creds for MuleSoft so we can successfully integrate with their service. 

## Expected Behavior

CARMA team send over `id` + `secret` for all environments (dev, ~~staging~~(DONE), prod)

## Acceptance Criteria
- [x] prod.mulesoft credentials have been received

**Comment by RudyOnRails** [comment]
I checked Param Store and don't see any for prod yet.



  | Name | Tier | Type | Last modified
-- | -- | -- | -- | --
  | /dsva-vagov/vets-api/dev/form_10_10cg/carma/mulesoft/client_id | Standard | SecureString | Wed, 19 Jan 2022 16:04:33 GMT
  | /dsva-vagov/vets-api/dev/form_10_10cg/carma/mulesoft/client_secret | Standard | SecureString | Wed, 19 Jan 2022 16:05:36 GMT
  | /dsva-vagov/vets-api/staging/form_10_10cg/carma/mulesoft/client_id | Standard | SecureString | Tue, 01 Feb 2022 17:52:59 GMT
  | /dsva-vagov/vets-api/staging/form_10_10cg/carma/mulesoft/client_secret | Standard | SecureString | Tue, 01 Feb 2022 17:53:42 GMT

I've also asked Igor for them: https://dsva.slack.com/archives/C02MJCT59S7/p1645114105045439

**Comment by RudyOnRails** [comment]
@SKasimow why was this unblocked and closed?
