### ISSUE TITLE
Identity Assisting Auth Exp 9DEC21

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#34033]
### **Description**
On production, users trying to view their CH.33 (GI Bill) Benefits experience timeouts while trying to access direct deposit information.  We are assisting AuthExp team with this as Joe has a VA.gov account that meets their needs.  **This issue only exists in Prod**

### User Story
**As a** Veteran
**I want** to access my GI Bill Direct Deposit Information
**So that** I can use the benefits I am entitled to

**Comment by joeniquette** [comment]
Ticket to record time dedicated towards helping auth exp team troubleshoot a production ch33 issue.

**Comment by nsoutouras** [comment]
Ongoing services.  User story: On production if a user tries to view their CH.33 (GI bill) benefits, call times out and doesn't display any information related to direct deposity.

**Comment by joeniquette** [comment]
no further work being conducted for this task.
