### ISSUE TITLE
[FE] Modify *authenticated* 10-10ez to be uneditable

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34049]
## User Story

As a Veteran, I need to avoid inappropriate modifications to MPI so that my data remains accurate.

**If the user is authenticated,** we pre-populate some of the fields for them, based on the values in the Master Person Index (MPI). However, these fields are editable, and may be changed by the user.

## Expected Behavior

The purpose of this story is to ensure that veterans are unable to edit fields based on the values per the MPI. At present, despite their pre-population, these fields are editable. They should not be.

Design Ticket: #31989

### For the *authenticated/logged-in experience*:
- [x] User should not be able to type into already populated forms. 
- [x] UI reflects design and new flow and applies to Name, DoB, and SSN only

### For the un-authenticated/logged-out experience:
- [x] Question order should reflect flow

## Resources
- [Design PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/7539409/Personal.info-locked.11.3.pdf)

- **_NOTE LINK:_** Find a VA location tool link: https://www.va.gov/find-locations 

- Flow for authenticated & unauthenticated experience (click to make bigger)

![flow.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/7705d24a-079c-4248-9dd3-a3309544f125)

**Comment by lzapson** [comment]
on first page of user input, on authenticated and unauthenticated, add the following description: 
"You aren’t required to fill in all fields, but we can review your application faster if you provide more information."

**Comment by Dene-human** [comment]
@lzapson We will put the suffix after the name: [first name] [last name] [suffix]

### Example design
![Screen Shot 2022-01-20 at 11.30.08 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/fea7aae9-8f09-4479-9e28-92bfa0aebd52)

### Suffix list
![Screen Shot 2022-01-20 at 11.25.32 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/c78f64e7-9082-4c04-9a49-d4b141167693)
