### ISSUE TITLE
Claim Status Tool - Endpoint Analysis

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34042]
## Issue Description
Per our last touchpoint with the Lighthouse team, they are prepared to help us migrate backend connectivity from EVSS to Lighthouse. 

---
## Tasks
- [x] Review logs/data. Document EVSS endpoints.  

## Acceptance Criteria
- [x] Documented endpoints that we can share with Lighthouse team. 
---

**Comment by cnemeth** [comment]
Attached file for backend `vets-api` EVSS Endpoints.

[vets-api-evss-endpoints.md](https://github.com/department-of-veterans-affairs/va.gov-team/files/7856327/vets-api-evss-endpoints.md)
