### ISSUE TITLE
Collaboration Cycle Kickoff [10-10 Caregivers, Mulesoft Integration]

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34055]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
- Wireframes, mockups, or prototypes: N/A
- Any other artifacts you have so far: [Epic](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/31307)

**Enhancement Overview**

Today, VA.gov interfaces directly with Carma (Salesforce) for 10-10CG form submissions. In the future, VA.gov will no longer connect directly to Carma. Instead, VA.gov will connect to Mulesoft, which in turn will connect to Carma (see screenshot below):

![Screen Shot 2021-12-15 at 5.43.54 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/223bdd9f-e95a-4611-b294-7e4f4cd480a6)

How does this benefit VA.gov?

The change was initiated by Carma team and the VA.gov integration to Mulesoft will support increased traffic, ability to scale, and reduce drops.

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [ ] Yes
- [x] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [x] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: Update to interface with Mulesoft ---> Carma (vs Carma directly)

design?
- [ ] Yes
- [x] No

### 5. Are you doing research with VA.gov users?
- [ ] Yes
- [x] No

### 6. Will your work involve changes to: (select all that apply)

- [x] Tools and applications* -  transparent to end-user
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [ ] Changes to existing content

### 8. Are you making a change to the user flow?
- [ ] Yes
- [x] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [x] Yes
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

### 12. Does your team have a Github label for this product?

- [ ] No. 
- [x] Yes. Please specify: Mulesoft

### 13. Who is the VA business owner for this body of work?

- [x] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
@MickinSahni Hi Mickin - please take a look and then I'll submit

**Comment by shiragoodman** [comment]
@SKasimow do you have any documentation I could review regarding scope? Specifically, what is MuleSoft, why are you integrating it and how will it be used? Feel free to point me to existing tickets if that's easier.

**Comment by SKasimow** [comment]
@shiragoodman - I will add an overview and link to epic. Will ping you when ready.

**Comment by shiragoodman** [comment]
Hi @SKasimow. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project has no visible changes so we are recommending the following Collaboration Cycle touchpoints: 

- [Privacy, Security, Infrastructure Readiness Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)


We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by RudyOnRails** [comment]
@SKasimow looks like this can be closed? Now that it's in production...
