### ISSUE TITLE
[Tier 3] Claim Status not showing - SF 06259690

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34051]
## Issue Description
_Veteran is unable to view claim status while on VA.gov.  Review details in comments section._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Case Notes from SF
Verified Veteran

Veteran called in due to not being able to see her claim status online.
Veteran states this has been going on for a few months.
Veteran states she has even went to a different device with same error message.
Veterans error message is " compensation issue"
Veteran states the only thing she can see is pending claim.
Veteran states she can not even see any information/ evidence in the claim
Veteran states she has been having to call the National Call center for claim status.

**Comment by Kimberley2019** [comment]
@vhenry07 email was sent to you containing PII.


From: REDACTED 
Sent: Monday, December 13, 2021 3:51 PM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: Claim status tool issue

The issue happens on every device mac or dell, safari or explorer or google chrome. I use va.gov. When I click my claim it never shows the status. Just says there is a compensation issue.



On Dec 13, 2021, at 1:56 PM, VA Technical Support <VATechnicalSupport@va.gov> wrote:
 
Good Afternoon, 
Thank you for your inquiry. Are you still experiencing this issue? If yes, we will need more information to investigate the problem and find a solution. In as much detail as you can, please respond to this email with answers to the following prompts and questions: 
 
•	Please provide step-by-step details of what actions you are taking and what happens when you do. 
•	Please copy and paste the URL or web address you were on when you experienced the issue.
•	If you saw an error message, please copy and paste the exact text of the error message.
•	What type of device are you using (i.e., Dell laptop, MacBook, iPhone, etc.)?
•	Try a different browser (i.e., Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all browsers?
•	What account do you use to sign into VA.gov (DS Logon, My HealtheVet, ID.me)?
 
Please click here for additional information about VA.gov and its resources.
 
 
Case Number: 06259690
 
 
 
 
 
Thank you,
 
VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
@alsleaders @vhenry07 No movement on this case.

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by Kimberley2019** [comment]
Case closed
Assistance provided.
