### ISSUE TITLE
Infinite loop on login due to incorrect time - Logging work

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#34052]
### **Description**
A small subset of users are seeing an infinite loop on login to va.gov.  This appears to be caused when the user has their machine clock set improperly.  We want to determine how frequent this is happening.

### **User Story**
**As a** va.gov Engineer
**I want** to be able to understand how frequently users are getting the infinite loop issue
**So that** I can assign an appropriate priority to this issue.

### **Business case**
Potential fixes for this issue are difficult.  We want to see how often it is happening before we fix it.

### **Acceptance Criteria**
- [ ] Logging is created to determine how often users are experiencing the infinite loop.

**Comment by nsoutouras** [comment]
As of 1/24/2022 We are not aware of a way to get present what time we think it is relative to what time their system clock thinks it is without making an API call to an NTP server.

@codyreinold-usds How far do we want to chase this one?  This is that issue we all got on a call with a veteran on who had been unable to log in for a year, and it turned out his system clock was set improperly.

**Comment by asg5704** [comment]
This is documented with troubleshooting steps for the Contact Team.  This cannot be solved by the FE yet.
