### ISSUE TITLE
Help Desk SOP Guide

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#34056]
- [x] Meet with @lindsay-insco to discuss document
- [x] Create rough draft document 
- [ ] Present to VT leadership

**Comment by chancetheoriginal** [comment]
Doc drafted and sent to leadership.

**Comment by aschulhof** [comment]
Awaiting feedback from @lindsay-insco , @pcshah1026 , @jwowk , and @aschulhof
