### ISSUE TITLE
Access for Daniel Choi

### ISSUE THREAD

**Issue by CosmicSyntax** [department-of-veterans-affairs/va.gov-team#34061]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Daniel Choi

### Your Email

daniel.choi@adhocteam.us

### Name of Your Team

Integration Experience Team

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBXwQz/D/erdGk7BtjdsPAe0Bp4JnAit3nnd7FhTVyY6OQdP3TfzsTTJB4TDAWkS9w1KPHmEFHXF3H9RbTZjlirFX2rTR1xvyC8zOCqBR6lVVzc9NIfTcNL7CMxvn09Gjpilx0PJJu9SkH4fG0Q66DXrgHV8ARx0mz7NTSAFdaWuQE91A9f2rLaFHPkhl4ufQqBAgbLgsZ/FlV/pK59Sskox4KyO2JjTfur82s6NZQwRRGraWV+7xG2C9c+nB3aW0Ez1FFe+d0D3ziUgFIoInK3PPwxCbFYfv8c29feeIhX5gJSt5HurtTrV9T8OpWy3V98iRHlEwWSEaEYG+Zy9jSKykeXyWZhJVxX2gkLKo46+GTNeFkOHGkwSLBhksaPHgbpbrbnkzLS6pEyzap7LDAfbhT3OUuMA0PvN0g113YJS/SY+3CklTk4RqnnL0HJf1uaBqIMbbroRzwVPQxMpGEVe/lbjcuQz0UPCTLV9TPCRNXFisvsRc6TO6Ls6HUPvk= dtchoi@Daniels-MacBook-Pro.local

### Desired AWS Services

My team was tasked by our PO to explore possible features to turn into micro-services.
Hence, I need access to EC2, S3, and EKS for sandboxing / prototyping for the project.

**Comment by jbritt1** [comment]
### For AWS Access

User: Daniel Choi
Vendor: Michael G. Lovejoy
Approval needed: @mchelen-gov

**Comment by jsgarmon** [comment]
new approval group: @department-of-veterans-affairs/operations-aws-approvers

@CosmicSyntax : they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that your COR has added your transmittal date to the Sharepoint doc?

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by td-usds** [comment]
Reached out to VOR today

**Comment by td-usds** [comment]
Approved
