### ISSUE TITLE
Adding Jennifer Schleicher to DSVA Slack

### ISSUE THREAD

**Issue by JennSchleicher** [department-of-veterans-affairs/va.gov-team#34071]
# Description

- Please add schleicher_jennifer@bah.com as a full member.

COR Name
Edward Hensel

Vendor Onboarding Representative Name
BAH - Jessica Riggs

Your Name
Jennifer Schleicher

Your Email
schleicher_jennifer@bah.com

Name of Your Team
BID APL Help Desk

**Comment by JennSchleicher** [comment]
Please add to Batteam channel

**Comment by LizCallaghan** [comment]
done!
