### ISSUE TITLE
Build Optimization: Only Lint Changed Files for PR's in vets-api

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#3407]
### The Problem
For PR builds of `vets-api`, we run the rubocop lint tool over the entire codebase. This currently takes ~1m44s on average. This time could be reduced if we only linted the files that are changed.

![image](https://user-images.githubusercontent.com/3077884/68781083-3ad71a00-0605-11ea-9c75-5171431ff85d.png)

### More Context
During the [work to break out our `make ci` into individual stages](https://github.com/department-of-veterans-affairs/vets-api/pull/3485), it was discovered that the lint stage is taking too much time.

### More Useful Info
- With the way we make [jenkins checkout source code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Jenkinsfile#L28), it runs git in a detatched head state... the local git is not aware of any other branches on the remote
- `danger` magically has knowledge of which files have been changed in a PR, we may be able to piggy-back off of it

### Work to be Done
- [ ] Discover exactly how much time would be saved if we only linted changed files
- [ ] For PR builds, only lint files that have been changed

**Comment by alexpappasoddball** [comment]
Anne's Comments:Rubocop has a parallel flag?  If committed to code cliament?

**Comment by annaswims** [comment]
the parallel flag went in a few weeks ago https://github.com/department-of-veterans-affairs/vets-api/pull/3882

**Comment by johnpaulashenfelter** [comment]
@alexpappasoddball i think we should close this since we have faster linting with the `parallel` tag

**Comment by omgitsbillryan** [comment]
The lint still takes 1m30s (as opposed to 1m40s). The `parallel` flag helps with optimizing our lint stage, but really isn't the spirit of what this ticket is poking at.

I have a few WiP PR's open that attempt to only lint changed files.
- https://github.com/department-of-veterans-affairs/vets-api/pull/4036
- https://github.com/department-of-veterans-affairs/va.gov-devops-jenkins-lib/pull/14

**Comment by johnpaulashenfelter** [comment]
@omgitsbillryan I'd like to put this back in the icebox or make it part of the CircleCI move since this would take place there.

**Comment by johnpaulashenfelter** [comment]
Also seems like `pronto` would be the right kind of tooling to take a look at  for this https://github.com/prontolabs/pronto

**Comment by omgitsbillryan** [comment]
Looks like a neat tool. I noticed this blip:

> Pronto runs the checks on a diff between the current HEAD and the provided commit-ish (default is master).

This could be problematic in CI because of how our Jenkins checks out from source control in a detached HEAD state. Basically, the local git has no awareness of any other branch (including `master`) so any `git diff` operations will fail.

**Comment by alexpappasoddball** [comment]
@omgitsbillryan removing this from the BE Tools board and adding it to the Ops board, might want to double check my labels to make sure it doesn't get lost on the Ops board.

**Comment by omgitsbillryan** [comment]
Linked one final ticket ☝️ , but ya, this is donezo.
