### ISSUE TITLE
Request Preliminary ATO Review

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3408]
## Goal
We want to ensure the risks to VA operations are acceptable so that our feature does not have any conflicts or friction with other services.

## Notes
**VA.gov link (WIP - [not yet created by Public Websites](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3767)):**
_https://staging.va.gov/disability/view-disability-rating_
**Tool Page (WIP):**
 _https://staging.va.gov/disability/view-disability-rating/rating_
- **What data are you collecting? For example, what data are you requesting from users?**
After the Veteran logs in, no data is collected, rather, data is displayed related to their Rated Disabilities (main VA rated disability as well as individual disabilities)

- **What data are you using? For example, what data are you requesting from some VA service?**
The main rated disability number is called `user_percent_of_disability` and the individual ones are called: {TBD}

- **Where does that data come from? For example, what API endpoint are you getting the data from?**
Rated Disabilities calls endpoints from the `vets-api` via the EVSS `findRatingInfoPID` service.

## Acceptance Criteria
- [ ] Feedback has been shared with the eBenefits Team.

**Comment by jason-gcio** [comment]
Holding until Andrea Hewitt gets back to us

**Comment by steve-gov** [comment]
Falls under existing ATO
