### ISSUE TITLE
Appointment Notifications

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#34089]
## Status
This is research that will be done by another team with us playing a support role. The research plan has already been developed by the other team.

## Description
Based on feedback we've received from veterans, there is a need to assess the current appointment notification landscape for potential consolidation and/or improvement so that veterans are not overloaded with appointment notifications.  Research shows that when veterans receive multiple appointment notifications via multiple modalities, they experience notification fatigue and may begin to ignore them altogether.  This leads to a couple of challenges:
1. Veterans see any notification from the VA as an annoyance or as spam, which gives them an unfavorable opinion of the VA.
2. No show rates increase when veterans ignore their appointment notifications.  No show rates cost the VA time and money. 

# Use Cases
1. As a veteran I would like to be reminded of my upcoming appointment in a way that is convenient for me, so that I know I will receive the reminder and pay attention to it. 

## Success Looks Like
1. Veteran satisfaction increases.
2. No show rates decrease.
3. Appointment reschedules increase.

**Comment by jparker0425** [comment]
@julieadair1 since Appointment Notifications is such as large landscape, and we know we are wanting to prioritize email, how do you feel about refactoring this epic to be more specific to **email**? We can make other epics specific to different modalities as we plan to incorporate in the future.

**Comment by julieadair1** [comment]
@jparker0425 that seems reasonable.  I'll update the epic to reflect this change.

**Comment by julieadair1** [comment]
@jparker0425 my only concern is that if we don't look for a solution to the notification overkill problem, such as allowing them to opt in or out to their preferred notification types, adding the PCI link to email will just be overlooked and we won't be any better off than we are now.  Can we have a discussion with UX about this?  I feel like we might need to tackle something like a notification opt in/out preference first so we know they will actually be paying attention to the emails.  
@kristenmcconnell any thoughts on this?

**Comment by jparker0425** [comment]
Based on discussion with team:

- scope narrowed to including PCI link in MyHealtheVet for only email 
- Need to set meeting with MyHealtheVet
   - Arienne Walter - UX Lead 
   - Lexi Wunder - UX
   - Bring up communication preferences 
   - What is the business logic around multiple appointments?
- Consideration needs to be made for emails being sent from Mobile Applications Platform (MAP). VAOS backend services.

**Comment by sarahknoppA6** [comment]
Talked w/Stephen about including Pittsburgh in the VAOS appt notification study. He said as long as we go through proper channels and get signoff from Shane Strassberg, we should be good to engage with them. Please keep Stephen/us in the loop.
