### ISSUE TITLE
[Design] O&E Design Updates from topline research summary 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34085]
## Issue Description
_In a recent top-of-mind summary of trends observed in the research sessions for the Outreach and events MVP, several design and FE updates are needed based on user feedback, the desired changes are detailed below in support_

Link to [Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/topline.md) 

## Desired Updates
- Remove the `Next week` and `Next month` options from the date filter because they were confusing for some participants, and the functionality can be supported more clearly using the `Custom date range` option instead. 
- Remove the "Up to 12 months in advance" text on the date entry screens. 

## Design Tasks 
- Migrate all megamenu items to Drupal for future content editing 
- Identify technical solution 
- Identify and note risks 
- Determine viable path forward with this level of migration

## Acceptance Criteria
- [x] Discovery ticket is updated with dev feedback to include recommended technical solution, risks and implementation path forward.
- [x] Close ticket when work is completed

**Comment by callen2563** [comment]
All updates have been made and discussed with the team. [Sketch file](https://sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1)

**Comment by brianalloyd** [comment]
Work is completed, closing ticket in support.
