### ISSUE TITLE
[FE] Make ID attributes in the footer unique by prepending footer-${id}

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34096]
## Issue Description
_In a recent daily a11y report and issue was identified via a dupe ID on the following [Page](https://www.va.gov/minneapolis-health-care/programs/) and was passed to the PW team who owns the footer actions_

Link to [Slack Thread](https://dsva.slack.com/archives/C01RAS1KAQK/p1639498380042900) 

## Tasks 
- make id attributes in the footer unique by prepending footer-${id} to them
- validate with a11y team 
- close ticket once completed

## Acceptance Criteria
- [ ] Make id attributes in the footer unique by prepending footer-${id} to them
- [ ] A11y issue has been resolved and tests are passing as a result

**Comment by kelsonic** [comment]
PR merged, will go out with daily tomorrow
