### ISSUE TITLE
[Tier 3] Disability claim upload issue - SF 05763854

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34103]
## Issue Description
_Caller is unable to upload disability claim.  Please review details from encrypted email._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
From: VA Technical Support
Sent: Thursday, September 9, 2021 3:42 PM
To: REDACTED
Subject: Claims issue

Dear REDACTED,

Thank you for your inquiry. We understand you have contacted MyVA411 for assistance with your disability claim application issue.
We apologize for any problem you may have experienced with the disability claims system. If you are aware or have been informed that your claim has already been received/submitted, please disregard this message.
If you have not been able to successfully apply due to errors with the submission form, we now recommend that you try again.  For some Veterans, recent upgrades have solved the problem, but we cannot guarantee this will fix all issues.
After you have tried again, if you are still experiencing the issue, please reply to this email with a screenshot of the Application ID number.  An example screenshot can be viewed in the attachment. This information will help the Benefits
 
Note: The system through which disability claim applications are submitted will not accept claims for Veterans with National Guard or Reserves obligations that have an end date more than 180 days in the future. The system will only accept dates up to 180 days in the future.
We appreciate your patience. Our technical teams are hard at work on this issue, and we remain committed to helping you submit your benefits application as soon as possible.
If you have already filed and are having difficulty obtaining information about your application, please note that we at VA.gov Technical Support are unable to access specific details. However, VA Benefits is prepared to assist. Please contact them at their service desk number, 1-800-827-1000. eBenefits Technical Support is also available at 1-800-983-0937.
If you need additional VA.gov technical support assistance, the best way is to email us at vatechnicalsupport@va.gov. If you are still unable to successfully submit your disability claim via VA.gov, the following options are available:
•	Submit your claim by mail: File your claim by mail using an Application for Disability Compensation and Related Compensation Benefits (Download VA Form 21-526EZ). Print the form, fill it out, and send it to this address:

Department of Veterans Affairs
Claims Intake Center
PO Box 4444
Janesville, WI 53547-4444
•	Submit your claim in person: Bring your application to a VA regional office near you. Find a VA regional office near you.
•	Submit your claim via fax: 1-844-531-7818 (toll free) or 1-248-524-4260 (foreign claims)

In service,
VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
Details below are from veteran.  All information has not been included, however, encrypted email has been sent to @vhenry07 for her review.




From: REDACTED 
Sent: Tuesday, December 14, 2021 12:16 PM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] RE: Claims issue

Hello, 

I’m reaching out again as I’ve continued not to be able to upload my disability claim. This issue has been ongoing, I have mailed in but I’m concerned I won’t be able to upload supporting documents because on the continual error. I did attempt to put in my application again. I will attach the photos again. I have not heard back from anyone from tech support, is my ticket still open? Will I be able to upload documents if the mailed in forms are uploaded? 

Any help, advice or pointing me in the right direction would be greatly appreciated. I am using Google Chrome, everything is updated. I’m unsure what the issue could be. Recently after I click submit the “it’s taking longer than usual” comes up but then returns to the previous error message I’ve sent in or when I check the status it says there’s no claim submitted.

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders No movement on this case.

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by Kimberley2019** [comment]
Case 'In Progress'

**Comment by Kimberley2019** [comment]
Assigning new members/teams for historical purposes.
After review, case may be closed by either team/team members.

**Comment by Kimberley2019** [comment]
– New Tier 3 benefits team review.  Modified follow up template sent.  Will reopen if/when user responds with needed information for resolution of issue.
