### ISSUE TITLE
[Tier 3] VA Benefits letter download issue - SF 06215265

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34107]
## Issue Description
_Veteran is having issues downloading VA benefit letter.  Please refer to encrypted email that was sent containing a screenshot._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
On Dec 9, 2021, at 2:42 PM, VA Technical Support <VATechnicalSupport@va.gov> wrote:
 
Good Afternoon, 
Thank you for your inquiry. Are you still experiencing this issue? If yes, we will need more information to investigate the problem and find a solution. In as much detail as you can, please respond to this email with answers to the following prompts and questions: 
 
•	Please provide step-by-step details of what actions you are taking and what happens when you do. 
•	Please copy and paste the URL or web address you were on when you experienced the issue.
•	If you saw an error message, please copy and paste the exact text of the error message.
•	What type of device are you using (i.e., Dell laptop, MacBook, iPhone, etc.)?
•	Try a different browser (i.e., Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all browsers?
•	What account do you use to sign into VA.gov (DS Logon, My HealtheVet, ID.me)?
 
Please click here for additional information about VA.gov and its resources.
 
 
Case Number: 06215265
 
 
 
 
 
Thank you,
 
VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
PII has been redacted from email below.  Encrypted email has been sent to @vhenry07 that contains screenshot.

From: REDACTED
Sent: Friday, December 10, 2021 7:58 PM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: VA Benefits Letter download issue

I tried directly logging in either through E benefits or va.gov.  
I used all 3 user either DS login, my healthvet or Id.me and still have the issues.
I’ve tried using a Chromebook, MacBook Pro or iPhone which I’ve used in the past and never had an issue.
URL 
https://www.va.gov/records/download-va-letters/letters/letter-list
I’ve tried using different browsers like fox or Internet explore and still have the same issue

**Comment by Kimberley2019** [comment]
From: VA Technical Support 
Sent: Tuesday, December 14, 2021 1:35 PM
To: REDACTED
Subject: RE: VA Benefits Letter download issue

Good Afternoon Mr. REDACTED,

Thank you for your response and for this helpful information. We appreciate your patience as we find a resolution to your problem. I have passed these details along to the appropriate team to review.  

The team may reach out to you directly if additional information is required.  Once the process is complete, they will reach out to you directly and inform you.  

Due to this process being managed by another team, we are unable to provide an exact timeframe of when this may be resolved, however, if you feel the need to check on the status, please respond to this email and we can follow up accordingly.

Thank you for your understanding. 

Reference Number: 34107

Please click here for additional information about VA.gov and its resources.




Kind Regards,

VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
@alsleaders caller reached out for a status update.  Encrypted email sent.  Please advise.

From: Daniels, Kimberley N. (Oddball, Inc.) 
Sent: Thursday, December 23, 2021 12:34 PM
To: Leaders, Amanda L. (Government CIO) <Amanda.Leaders@va.gov>
Subject: FW: VA Benefits Letter download issue

Good Afternoon Amanda,

Can you please provide a status update on the issue below?



Kind Regards,

Kimberley

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders 
Customer is asking if they need to contact their congressman in order to get movement on this issue.  See below.

Please provide and update as soon as possible.

From: R G 
Sent: Tuesday, January 25, 2022 7:32 AM
To: VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: VA Benefits Letter download issue

It's been over a month, and I haven't heard anything on my status! I've email and no response. Do I have to contact my congressman or media to get Some form of Resolution?
Sincerely,

**Comment by alsleaders** [comment]
Hello @Kimberley2019 and @vhenry07 
I'm sorry I dropped the ball on this - I was unsure about how to access benefit letter information and did not circle back to ask my team after the holidays.  

Kimberley, I've also sent you an email update.  Do you have the veteran's ICN number that you could forward me?  The screenshot the veteran sent doesn't have any information I need to move forward.

**Comment by Kimberley2019** [comment]
@alsleaders how can I get you that information?  Is it considered PII?  I can send an encrypted email if it is.

**Comment by alsleaders** [comment]
Thank you.
And thank you for sending the ICN. (I will double check on whether or not its PII.)

I have looped @michelpmcdonald - he has access I don't to be able to see the letters available to this veteran - so I forwarded him the original email so he could see the error as well.

**Comment by Kimberley2019** [comment]
@alsleaders @vhenry07 

I BCCed you both on the correspondence I just sent to the caller.  Do you think that this will be viewed today so that we can provide some information?

From: VA Technical Support 
Sent: Wednesday, January 26, 2022 10:47 AM
To: 'R G' 
Subject: RE: VA Benefits Letter download issue

Good Morning Mr. REDACTED,

Thank you for reaching out to our department for a status update.

We apologize for the delay in getting back to you.  I have contacted the appropriate team and have informed them of the urgency of your request.

I am hopeful that they will be contacting me today with an update on your issue progress.



Kind Regards,

VA.gov Technical Support Team

**Comment by vhenry07** [comment]
@Kimberley2019 we're still researching to try to understand the backend letters pathways. Will update as soon as we can.

**Comment by alsleaders** [comment]
@Kimberley2019 I just sent you a follow up email, asking if you would reach out to the veteran and make sure they are trying to download the benefit summary and service verification letter, and also that they've been unable to see this document in the "My Document" tab on ebenefits.va.gov.

**Comment by Kimberley2019** [comment]
Reached out to customer for more information.

BCC @alsleaders @vhenry07 on email in order not to cause any bottlenecks if customer responds with information they are able to use in order to resolve issue.

From: VA Technical Support 
Sent: Friday, January 28, 2022 11:31 AM
To: 
Subject: RE: VA Benefits Letter download issue

Good Morning Mr. 

I have heard back from the team and they are needing you to confirm two things:

1.	You are trying to download is the benefits summary and service verification letter (we want to make sure since the letter title wasn’t clear in the screenshot).
2.	You have been unable to see this letter in the “My Documents” screen on ebenefits.va.gov?  

I will get that information over to them as soon as you respond with the required information.

Looking forward to getting this issue resolved.



Kind Regards,

VA.gov Technical Support Team

**Comment by Kimberley2019** [comment]
@alsleaders @vhenry07 
Caller emailed back multiple times.  Unsure if you received any messages (you both were BCC on the email), however, I will be sending over to you shortly.

**Comment by vhenry07** [comment]
We'll take a look and get back to you as soon as we can.

**Comment by Kimberley2019** [comment]
Case closed.
Resolution provided.
