### ISSUE TITLE
Design Feedback - Midpoint Review - Public Websites - Outreach & Events

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#34109]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change search styling to match current approved styles: Showing 1-10 of 546 results for "**1010**"
- Move “Filter by” above drop down
- Center text on buttons (Filter by, Register, Check other times)
- Use the styling found in [Storybook for drop downs](https://design.va.gov/storybook/?path=/docs/components-dropdownpanel--default)

**Should:**

**Consider:**

**Comment by brianalloyd** [comment]
This design work has been completed.  Closing ticket in support.
