### ISSUE TITLE
[BE] Onboarding: Tom Harrison

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#34115]
## Background

Welcome, Tom! We can use this ticket to track onboarding to the new profile team.

### Chats

- [x] Meet with Marci
- [ ] Meet with Christina
- [x] Meet with Adam
- [ ] Meet with Samara

### Code Review
- [ ] Review Contact Info Service

We'll have you meet with Lihan once he's back from his winter break.

### Team docs

- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md)
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/product-outline.md)

### Onboarding to the LGBTQ data work

- [x] [Adding preferred name, pronouns, gender identity, and sexual orientation to the VA.gov profile](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md)

### Onboarding to existing Profile features

**Staging**

- [x] Log into staging to explore the profile ([List of staging users for each feature](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users))

**Profile overview**

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [Profile folder and list of products](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)
- [x] [Profile roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/profile-roadmap.md)

**Contact information**

- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/README.md)

**Direct deposit**

- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)

**Communications preferences** (aka Notification preferences)

- [x] [Communications preferences project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)

**Comment by tpharrison** [comment]
Just a reminder that I will be on vacation 12/27 - 12/31.

**Comment by tpharrison** [comment]
@Samara-Strauss, @MarciMcGuireGCIO - I've read through the documentation, but I've only had a one-on-one chat with Adam.

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 64; Tom was not able to schedule 1-1 on meetings with everyone due to holiday schedules
