### ISSUE TITLE
526 - Failed Submission - Email Content Review

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#34119]
## Issue Description
We have written some preliminary copy for an email to notify a user if their 526 disability compensation form has failed. We now need to send it to our content SMEs to ensure it fits the voice and tone of VA.gov.

---
## Tasks
- [x] Submit email content to Beth (or content SME) to refine the language in the email

## Acceptance Criteria
- [x] email content/copy has been submitted and communicated to content SMEs
---

**Comment by kevinstachura** [comment]
Email content:

Subject: An error occurred with your disability claim application on VA.gov.

Hello [user],

Due to a technical error, we couldn’t process your form. This can occur after the form has been submitted on the VA.gov website. At this time, we advise that you [fill out and submit our 526 paper form].

Send in your completed form and any evidence in support of your claim to:

Department of Veterans Affairs
Evidence Intake Center
PO Box 4444
Janesville, WI 53547-4444

Alternatively, you can bring your application to a [VA regional office near you] and submit in person.

We apologize for the inconvenience.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop Would you please work on this in a separate internal ticket that you can tag me in to review before we post here?

**Comment by RLHecht** [comment]
@kevinstachura Here is the edited text ready for your team:


Subject: We couldn't process your VA.gov disability claim application

Dear ((First name)),

We’re sorry. Your Application for Disability Compensation and Related Compensation Benefits (VA Form 21-526EZ) didn’t go through. Something went wrong on our end.

Please fill out a new application and submit it to us by mail or in person.
[Download VA Form 21-526EZ (PDF)](https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf)

**To submit your application by mail,** send your completed form and supporting documents (evidence) to:

Department of Veterans Affairs
 Evidence Intake Center 
PO Box 4444 
Janesville, WI 53547-4444

**To submit your application in person,** bring your completed form and supporting documents (evidence) to your nearest VA regional office.
[Find a VA regional office near you](https://www.va.gov/find-locations/?facilityType=benefits)

We apologize for the extra work this causes for you.

**Comment by kevinstachura** [comment]
Excellent, thank you so much @RLHecht and @bethpottsVADEPO !

@vhenry07 I'm not certain what the next step is here, but we might need to engage the VA Notify team or to whomever enters content into our VA emails. 

Closing this task as complete, as all acceptance criteria has been satisfied.
