### ISSUE TITLE
Get "Product Health Tool" to Education Stakeholders

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3412]
## User Story or Problem Statement
As an VFS Education stakeholder, I need access and accurate data so I can use the Tool for data-driven decisions.

## Goal
Add real targets to the “Product Health Tool” prototype so that we can “launch” it to Education stakeholders for real use

## Objectives or Key Results this is meant to further
- Launch Grey Sky Product Health Tool

## Acceptance Criteria
- [ ] Education stakeholders need to know about the Tool
- [x] Education stakeholders need to have GA access
- [ ] Insights collaborates on relevant links to the "missing" data on the Tool
- [ ] Insights receives targets for available charts
- [ ] Insights adds real targets 
- [ ] Insights "onboards" Education stakeholders

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Additional data for "Grey Sky"

| Chart Name                                                                                                     | Link or Comment                                              |
|----------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|
| Percent difference from target over time                                                                       | @amycesal - add chart description                            |
| High Level KPI Goals                                                                                           | @amycesal - add table description                            |
| Paper Form Submissions                                                                                         | Data TBD                                                     |
| Time to complete the form                                                                                      | Data TBD                                                     |
| Funnel Conversions                                                                                             | @jonwehausen & @nedierecel for links                         |
| Downtime Percent                                                                                               | Data TBD                                                     |
| Backend Systems                                                                                                | Data TBD                                                     |
| Customer Satisfaction Score Average                                                                            | Please contact VSP Analytics & Insights for ForeSee data     |
| Answers to the survey prompt "What Education and Training information or services were you looking for today?" | Please contact VSP Analytics & Insights for ForeSee data     |
| White House Hotline Call Center Calls                                                                          | Please contact VSP Analytics & Insights for Call Center data |

@amycesal Can you also get the "Help Text" for the charts over to Nicola?

@deweydell Would you also be able to add a Contact Us to the site? 
`Please direct further inquiries to #vfs-platform-support` on DSVA Slack

**Comment by joanneesteban** [comment]
11/18/19 - @deweydell added help text to charts on the FE solution.

**Comment by joanneesteban** [comment]
@nedierecel & @jonwehausen to huddle with @deweydell on error rate chart.

**Comment by joanneesteban** [comment]
Checking in on the following deliverables for this sprint:

@amycesal 
- Help text for:
   - Page Views on Introduction Page
   - Paper Form Submissions
   - Downtime Percent
   - Backend Systems
   (/work with @deweydell on the missing help texts or contact info for our blank charts)
- GA Access: Matt and Kevin have GA access, but if there are other stakeholders for testing Education who need GA access, let me know and I can follow up with them.
- "Onboarding" - the brief conversation guide or training that we'll need to onboard the test users
- Getting the mini user research test started. 
    For this rollout, our hypothesis: "If VFS teams have an easier to read metrics targeting tool, then they will use that data to guide their product strategy."
   What we'd be looking for to determine product strategy guidance:
      - Do they have questions on the result of their data in relation to their target?
      - Did they check in with the tool after we onboarded them? (can't be measured on the API, but maybe there's a workaround of recording the stats COB...Nicola, there's no way for us to "opt out," is there?)
      - If their resulting data fell below target, did they have any resulting actions?

@jonwehausen @nedierecel please help provide Nicola links for Funnel Conversions.

**Comment by amycesal** [comment]
### Help text for:
#### Page Views on Introduction Page
Total number of page views on the introduction page of the form for unauthenticated users per month. Source: Google Analytics

#### Paper Form Submissions
Total number of forms submitted on paper per month. Source: PA&I data
^ @joanneesteban is that correct?

#### Downtime Percent
The percent of time per month the form has been unable to be submitted. If there are no submissions, the form is assumed to be up. Source: Grafana

#### Backend Systems
The other systems that this form relies on and the percent of time per month those systems have been unavailable. Source: Grafana

**Comment by amycesal** [comment]
## User research for beta users 

#### Time:
One month after onboarding beta users

#### Hypothesis:
If VFS teams have an easier to read metrics targeting tool, then they will use that data to guide their product strategy.

#### Research Question:
- Did they check in with the tool after we onboarded them?
- Do they have questions on the result of their data in relation to their target?
- If their resulting data fell below target, did they have any resulting actions?

#### User Research Questions: 
- How has the past month been for you?
- Did you look at the *insert name of tool* in the past month?
- Can you talk about why you did not use it?
- Can you talk about what you used it for, and if it was helpful?
- Were having targets for the month helpful? Did you make decisions based on them? Do you want to adjust them in the future? 
- Do you think you will use the tool in the future? How often?
- What can we do to make the tool more useful?

**Comment by joanneesteban** [comment]
@clantosswett Can you add help text for the Call Center items on the Tool? (Adding to contact Insights or you / @Kimberley2019 for more info)
- HRC Call Center Calls
- White House Call Center Calls
- Tier 1 Call Center Calls
- Tier 2 Call Center Calls (we should actually change this to "Tier 3 Call Center Calls" @deweydell @amycesal  )

**Comment by joanneesteban** [comment]
@amycesal @deweydell Re: Paper form submissions - that's right. We're hoping to get more info, like time to complete/time to benefits, but total submissions is probably most likely.

**Comment by nedierecel** [comment]
@deweydell From our Slack thread, here is the format for pulling goalXXConversionRate using Form 1990 as an example.

https://ga-dev-tools.appspot.com/query-explorer/?start-date=2018-11-08&end-date=2019-11-05&metrics=ga%3Agoal1ConversionRate&dimensions=ga%3AyearMonth&samplingLevel=higher_precision

**Comment by joanneesteban** [comment]
**Summary from meeting with Kevin H on 11/22/19**:

- Metrics will trend based on the time of year
- Usage metrics have had an upward trend year after year
- Setting targets requires more nuance than looking at previous three months: Education has PA&I data and can incorporate VA.gov usage vs. Benefit usage vs. Time of Year into target setting

**Insights/Next Steps:**
- We will need to journey map data use for each metric to determine how targets will be set
- We will need to re-evaluate how targets will be displayed on each graph given how targets will likely change month after month. This may include adding historical data from the year before (vets.gov in this year's case)

**Comment by joanneesteban** [comment]
Pivoting on adding targets to `Page Views` and `Online Submissions` and will work on getting more actionable data for the Tool before sending out to Education Stakeholders.

Will still need the next steps from the previous comment (done at a later sprint).

**Next Sprint Steps**
- Still add relevant links and missing data to the Tool
- Add Error Rates to the Tool
