### ISSUE TITLE
Access for Andrew Herzberg

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va.gov-team#34127]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Michael J Lovejoy

### Your Name

Andrew Herzberg

### Your Email

andrew.herzberg@adhocteam.us

### Name of Your Team

Ad Hoc - VA Mobile team - backend engineer

### Service(s) You Want Access To

AWS

### Desired AWS Services

AWS Console access

**Comment by aherzberg** [comment]
COR name is Travis Newby

**Comment by jbritt1** [comment]
### For AWS Access

User: Andrew Herzberg
Vendor: Michael G. Lovejoy
Approval needed: @mchelen-gov

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by aherzberg** [comment]
Could I get a status update on this? are you still waiting on EQIP transmittal date?

**Comment by td-usds** [comment]
Yep, reached out to your VOR and awaiting response

**Comment by aherzberg** [comment]
Apologies. Turns out my COR is actually Cecilia Lee. Is COR equivalent to VOR?

**Comment by aherzberg** [comment]
I'm not sure on the exact services but it may be easier to mirror the permissions given to someone on my team that was recently just onboarded as well. For example: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33522

**Comment by aherzberg** [comment]
Will mirroring that users permissions suffice?

**Comment by kreek** [comment]
@td-usds Andrew needs AWS permissions setup so that he can MFA and then SSM into staging instances of vets-api and vets-api workers. Although if there's a permissions template for backend engineers working on vets-api then that 😄

**Comment by jbritt1** [comment]
> @td-usds Andrew needs AWS permissions setup so that he can MFA and then SSM into staging instances of vets-api and vets-api workers. Although if there's a permissions template for backend engineers working on vets-api then that 😄

Our baseline developer group would allow that: https://console.amazonaws-us-gov.com/iamv2/home#/groups/details/dsva-vfs-developers?section=permissions

**Comment by aherzberg** [comment]
The baseline developer group should work great.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Approved

**Comment by jbritt1** [comment]
First-time login credentials passed to user at this time.
