### ISSUE TITLE
Fix Accordion documentation on design.va.gov and Storybook

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#34126]
## Description
The documentation around the accordion component on design.va.gov has a missing storybook iframe and does not match the current implementation of the accordion component. We need to update the documentation and fix the storybook iframe.

## Details
The default behavior of the accordion component now allows multiple accordions to be open at once. Engineers need to specify that they only want the user to be able to open one at a time using the `open-single` prop.

The following updates need to be made to support this change:
- The documentation for [multi-selectable accordions](https://design.va.gov/components/accordions#multi-selectable) on design.va.gov needs to be removed
- Documentation for single-selectable accordions needs to be added to design.va.gov
- The default Storybook story for accordions needs to set `open-single` to undefined. If we don't do that, Storybook tries to set it to undefined on its own, which sets `open-single` to a truthy value and causes Storybook to show the accordion as single-selectable when page is first loaded. We need to fix it so that the multi-selectable accordion appears as the default.

## Acceptance Criteria
- [ ] remove multi-selectable accordions documentation from design.va.gov
- [ ] add single-selectable accordion documentation to design.va.gov
- [ ] fix default accordion Storybook story to show multi-selectable accordion

**Comment by pdavies88** [comment]
Related PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/613
