### ISSUE TITLE
Analytics Implementation or QA Support for VAOS-Calendar GTM

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#34128]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - VAOS, follow-up from conversation in [Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1636570295081000)
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - #32684
    
- **When is the launch date?**
    - Whenever dev ticket is in Production

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - Custom parameter in event

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by laurenernest** [comment]
@laurensimpson14 this is in staging now. here's the note from the dev:

The event name is `vaos-request-submission-successful`, the parameter is `vaos-number-of-days-from-preference`  Below is an example of what you can expect.

      event: 'vaos-request-submission-successful',
      flow: 'va-request',
      'health-TypeOfCare': 'Primary care',
      'health-ReasonForAppointment': 'routine-follow-up',
      'vaos-preferred-combination': 'afternoon-evening-morning',
      'vaos-number-of-days-from-preference': '1-1-null',

CC Request event name is `vaos-community-care-submission-successful` and parameter is `vaos-number-of-days-from-preference`


      event: 'vaos-community-care-submission-successful',
      flow: 'cc-request',
      'health-TypeOfCare': 'Primary care',
      'health-ReasonForAppointment': undefined,
      'vaos-community-care-preferred-language': 'english',
      'vaos-number-of-preferred-providers': 1,
      'vaos-number-of-days-from-preference': '1-1-null',
      'vaos-preferred-combination': 'afternoon-evening-morning',

**Comment by laurensimpson14** [comment]
@laurenernest I've added in the CD, and it is passing correctly for the `vaos-request-submission-successful` event. 

I'm not sure how to reach the CC flow to test the `vaos-community-care-submission-successful` event. Do you have a link to that flow?

| Event | Current Date | Time selected | dL screenshot | Status |
| -- | -- | -- | -- | -- |
| `vaos-request-submission-successful` | January 5 | ![image](https://user-images.githubusercontent.com/80417436/148245648-2a32a8f2-ed95-4cf0-88c8-f35afee6af3b.png) | ![image](https://user-images.githubusercontent.com/80417436/148246502-bcf6f10e-deb3-4b37-927a-a1bca4e12564.png) | 🟢 Tracking Correctly (January 18 - January 5 = 13 days; only one preference selected)|
| `vaos-community-care-submission-successful` |  | | | |

**Comment by laurenernest** [comment]
@laurensimpson14 The CC flow comes up for certain selections. Try Judy with Podiatry and that should take you down the CC flow.

**Comment by laurensimpson14** [comment]
Ahh ha, I found it! I've updated the table above with screenshots. Everything appears to be tracking correctly. 

@jennaouellet I've made the updates in GTM workspace [34128](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000584/tags). Could you please QA my work and then publish the changes?

**Comment by jennaouellet** [comment]
Event | Current Date | Time selected | dL screenshot | Status
-- | -- | -- | -- | --
vaos-request-submission-successful | January 5 | ![image](https://user-images.githubusercontent.com/85642160/148307144-0f0fa8e9-0819-4cfe-87ed-82768cb084b3.png) |  ![image](https://user-images.githubusercontent.com/85642160/148306853-703c3829-d870-430f-ba87-7d90fa0fed19.png)  | 🟢 Tracking Correctly (January 20 - January 5 = 15 days; only one preference selected |
vaos-community-care-submission-successful | January 5 | ![image](https://user-images.githubusercontent.com/85642160/148307851-6e0b5b5d-e665-44a7-a52f-30b392f44a0d.png) | ![image](https://user-images.githubusercontent.com/85642160/148307813-672497e9-0976-4bc4-a297-33eace70ec62.png) | 🟢 Tracking Correctly (January 31 - January 5 = 26 days; only one preference selected | 
 


@laurenernest 
QA is complete and the GTM container has been published and is live. Thanks!

**Comment by laurenernest** [comment]
@laurensimpson14 @jennaouellet I took a look at the [Prod results](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension144&explorer-table.rowStart=0&explorer-table.rowCount=100&_r.drilldown=analytics.eventLabel:vaos-request-submission-successful/)  and I'm wondering if it's possible for it to be visualized so that there are counts for each "number of days" instead of the 3 combo as one reference. I'm not sure if this is something we would have to update in our code or if there's something that can be done in GTM.


Is something like this possible? If we have to update our code, can you provide guidance on how the values should be returned so that the selections are counted individually? I can manually do it in excel if I have to.
![image](https://user-images.githubusercontent.com/72046525/148427552-2156ee8a-ab89-4112-bd98-be6e062e2a99.png)

**Comment by laurensimpson14** [comment]
@laurenernest Right now the results are doing something _similar_ to what you want where they're showing a count, but it's a count of a 3 combo. For example, below it's showing a count of 1,743 for the `5-null-null` preference. 
![image](https://user-images.githubusercontent.com/80417436/148836152-55a8d747-dbc0-4e21-a02a-84d9ce7edc3a.png)

The only way I can think of to get it close to what you're looking for is to have 3 different parameters rather than one total with the three preferences in it. The three parameters would be: 
1. vaos-number-of-days-from-preference-one
2. vaos-number-of-days-from-preference-two
3. vaos-number-of-days-from-preference-three

Then you could filter to `vaos-number-of-days-from-preference-one` and see a the number of days out (your column one above) and the `Total Events` (the count of how many users selected that - your column 2 above). 

When you filter to `vaos-number-of-days-from-preference-two` and `vaos-number-of-days-from-preference-three` you'll have "null" as a line item.

It would be collecting the same info now, the biggest difference would be that you wouldn't be able to view all three preference selections at the same time. You'd have to view all of the 1st preference selections at once, then all of the 2nd preference selections at once, and then all of the 3rd preference selections at once. 

Would that be better?

**Comment by laurenernest** [comment]
Thanks for the info! It might be more LOE than it's worth to separate out. Will keep as is for now.
