### ISSUE TITLE
Access for Harshil Moradia

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va.gov-team#34125]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Harshil Moradia

### Your Email

Harshil.Moradia@va.gov

### Name of Your Team

Platform Spike Teams - Access Management

### Service(s) You Want Access To

AWS

### Desired AWS Services

I am part of the PST Access Management team and request to be added to this group platform-amt.

**Comment by jbritt1** [comment]
### For AWS Access

User: Harshil Moradia
COR: Cecila Lee
Approval needed: @mchelen-gov

**Comment by jsgarmon** [comment]
new approval group: @department-of-veterans-affairs/operations-aws-approvers

@harshil1793 : they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that your COR has added your transmittal date to the Sharepoint doc?

**Comment by harshil1793** [comment]
Yes, e-QIP has been submitted on 12/06/2021. Transmittal date is 12/13/2021.

Also, it has been added to my record in Jira. Now waiting for Certificate of Investigation.

**Comment by harshil1793** [comment]
@jsgarmon: I am not sure whom to contact for the update of AWS access but if you need anything from my end please let me know.

**Comment by td-usds** [comment]
Reached out to VOR for eQIP transmittal date

**Comment by td-usds** [comment]
Transmittal date confirmed
@jsgarmon approved

**Comment by jbritt1** [comment]
Temporary credentials passed to user at this time.
