### ISSUE TITLE
Adjust Radio Button Results For More Granularity

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34137]
## Background
It was recommended that we adjust the results of yes/no responses to be more broken apart so that a large dropdown does not appear suddenly.

## Considerations
- Check with FE to ensure that the Form System can handle this behavior (most likely fine, but just check in for funsies)

## Tasks
- [x] Adjust mockups to ensure more granular outcomes when certain radio buttons are selected.

## Acceptance Criteria
- [x] Mockups are adjusted for and shared with team/commented in this ticket

**Comment by candy-gcio** [comment]
Updated Wireframes](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/a/WKqK8MA)
[Updated hub page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-apply-SAHG/research-design/README.md)
