### ISSUE TITLE
Update Wait Time Alert Copy

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#3414]
## Scenario 1: **Care needed urgently:** When preferred date is today *and* requests are available

{page title} **Appointment calendar**
{alert}
**This is the earliest date we can schedule your appointment**
The earliest we can schedule your appointment is November 1, 2019 at 10:00 a.m. ET. 
If this date doesn’t work, you can: 
-Submit a request for an earlier date, **or**
-Pick a date from the calendar below, **or**
-Call your local VA medical center

If you have an urgent medical need, please: 
Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
Go to your nearest emergency room or VA medical center. [Find your nearest VA medical center](va.gov/find-locations/)

{button} Request an earlier appointment    {link}[Call your local VA medical center](phone number)

{end alert}

## Scenario 2: **Care needed urgently, request flow not viable:** When preferred date is today *and* requests are **NOT** available

{page title} **Appointment calendar**
{alert}
**This is the earliest date we can schedule your appointment**
The earliest we can schedule your appointment is November 1, 2019 at 10:00 a.m. ET. 
If this date doesn’t work, you can: 
-Submit a request for an earlier date, **or**
-Pick a date from the calendar below, **or**
-Call your local VA medical center

{button} Request an earlier appointment    {link} [Call your local VA medical center](phone number)

## Scenario 3: **VA not meeting standard of care, request flow viable:** Preferred date >5 days away, *and* next avail appointment is >20 (mental health) or 28 (other ToCs) days away from the preferred date, *and* requests are `enabled` for the selected facility

{page title} **Appointment calendar**
**We’re sorry. We can’t find a date for your appointment**
This medical facility doesn’t accept online appointment requests. Please call them directly to schedule your appointment. 
[Contact your local VA medical center](va.gov/find-locations/*TK link to that facility*)

## Scenario 4: **VA not meeting standard of care, request flow not viable:** Preferred date >5 days away, *and* next avail appointment is >20 (mental health) or 28 (other ToCs) days away from the preferred date, *and* requests are `disabled` for the selected facility

{page title} **Appointment calendar**
**We’re sorry. We can’t schedule your appointment**
If this is an emergency or you have an urgent medical need, please: 
-	Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
-	Go to your nearest emergency room or VA medical center. Find your nearest VA medical center

If this isn’t an emergency, please call your local VA medical center to schedule your appointment. 
[Contact your local VA medical center](va.gov/find-locations/*TK link to that facility*)

_Originally posted by @peggygannon in https://github.com/department-of-veterans-affairs/va.gov-team/issues/2712#issuecomment-551990068_

**Comment by narin** [comment]
@peggygannon I separated the discussion about copy into this new ticket, but I think there might have been some miscommunication when we were discussing this last, specifically for scenarios 3 and 4.  

In both those scenarios, direct scheduling **IS** available, but the next available appointment is not within 20 days (28 in the case of mental health). The difference being that for scenario 3, the user has the option to request an appointment instead, and for scenario 4, they do not have the option.

So for those scenarios, I'm not sure that the "We’re sorry. We can’t schedule your appointment" alert headline makes sense, since they technically _**are**_ able to schedule, but further in the future.

Just so we are on the same page, do you mind reviewing each scenario again? As a visual aid, scenario 1 is looking like this:

![Screen Shot 2019-11-18 at 2 20 57 PM](https://user-images.githubusercontent.com/786704/69099234-20d77600-0a0f-11ea-88dc-273dd9854b0b.png)

Thanks!

**Comment by peggygannon** [comment]
thanks, @narin I'll take another look at this. I'm out of the office starting tomorrow. Is it ok for me to give you feedback after the Thanksgiving holiday?

**Comment by narin** [comment]
Hi @peggygannon, I was out last week as well.  If you're back and could take a look within the next few days that'd be great! Thanks.

**Comment by peggygannon** [comment]
@narin I'm looking at scenarios 3 and 4, and would it be accurate to use the alert heading: 
**This is the earliest date we can schedule your appointment** for both of these situations, but with scenario 3, the user can either request another appt or call? and with scenario 4, the user's only option is to call? 

cc @markgreenburg

**Comment by peggygannon** [comment]
@narin Hi, see updated content suggestions below. Can you let me know if I got the messaging correct for these two scenarios? 

Scenario 3 
{alert}
**This is the earliest date we can schedule your appointment**
The earliest appointment we can schedule for you is {date, time}. 

If this date doesn’t work, you can: 
*Submit a request for an earlier date, **or**
*Call your local VA medical center

{button} Request an earlier appointment {link}[Contact your local VA medical center](/get-locations/)

------
Scenario 4
**This is the earliest date we can schedule your appointment**
The earliest appointment we can schedule for you is {date, time}. 

If you need to schedule this appointment for an earlier date, please call your local VA medical center. 

{link} [Contact your local VA medical center](/get-locations/)
