### ISSUE TITLE
Search UI Consistency for UX and Find a Form

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#34156]
Placeholder until I meet with Megan for more context

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Designer, I need make front-end development changes to Search specific components based on design comps and Search UI spreadsheet so I they are consistent. 

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.
Create design comps for R&S Article pages to align with the rest of VA.gov
Related information, VA Benefits, Need more help? section styling should align with the rest of VA.gov
## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mgleo** [comment]
[Mobile designs](https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4)

[Desktop designs](https://vsateams.invisionapp.com/console/share/SD10IE31CENR)

[Style Spreadsheet](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit#gid=0)

**Comment by nicole-leonard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34156?planning-poker) with ZenHub @TSimmz @srsuddath

**Comment by nicole-leonard** [comment]
Nicole and Dave spoke about this. We will complete this ticket for the sprint and explore the search consistency on a change by change basis.
