### ISSUE TITLE
Overall Goal of IET Sandbox Env

### ISSUE THREAD

**Issue by CosmicSyntax** [department-of-veterans-affairs/va.gov-team#34154]
Goal: we want to have a sandbox environment that mimics EKS prod (where VETS API is being migrated to) as much as possible to enable us to prototype services dedicated to file upload, feature toggle, etc.
Currently:
Igor has access to socks and aws;  Dan has submitted a request for socks and aws
Igor (and probably eventually me) has (have) limited access
We cannot see any existing EC2 instances, and AWS customer support is disabled
Perhaps this is be policy?
Action Items:
Ensure our understanding and vision of what is in sandbox is aligned with platform
Help address access issues
Identify (if any) knowledge gaps about VETS API and current EK8 migration efforts
We completed an inventory of VETS API endpoint. Input on whether or not it looks ok

**Comment by ewilson-adhoc** [comment]
Closing out this ticket for the time being -- we were able to create a 'hello world' application which was part of the goal of this ticket. The conversation of what we want an IET sandbox environment for is still ongoing, but probably doesn't need to be it's own ticket.
