### ISSUE TITLE
[Tier 3] VA benefit letter download AND claim submission issues - SF 06272750

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34158]
## Issue Description
_Caller is having issues with downloading VA benefit letter AND submitting a claim.  Please review information in this ticket and from the encrypted email containing more details. _

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@vhenry07 encrypted email was sent to you containing all information.

From: REDACTED
Sent: Tuesday, December 14, 2021 2:47 PM
To: PM VA Technical Support <VATechnicalSupport@va.gov>
Subject: [EXTERNAL] Re: VA benefits letter access issue


Hello,

I still cannot access my letters, and the only thing that happens is that nothing appears.

I have another issue where I cannot submit a claim.

1.I login, do everything for my claim, and then when I get to the end it just doesn't let me submit and tells me there is an issue,

2. https://www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation

3. Is pasted below
We’re sorry. Something went wrong when we tried to submit your claim.
For help submitting your claim:
	Please call Veterans Benefits Assistance at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET, or
	Get in touch with your nearest Veterans Service Officer (VSO). Find out how to contact your nearest VSO


4. HP Laptop running regular windows

5. I primarily use Chrome however I have tried all browsers

6. I have logged in with DS login and ID Me.

Please call me at any time so I can explain further.
Application ID Number: 3989530

Thank you so much,

REDACTED

**Comment by michelpmcdonald** [comment]
The error on this is:

[{"key"=>"form526.submit.establishClaim.serviceError", "severity"=>"FATAL", "text"=>"Benefit Type, Payee code or EP Code is not valid. Benefit Type must be CPD, Payee code must be 00, 10 - 29, 50, 60 or 70 - 78."}]

This issue has been seen in the past and seems to be related to multiple IDs tied to the vets, possibly a spouse ID might be a factor

**Comment by Kimberley2019** [comment]
@michelpmcdonald thank you for the information.  Please advise if we need to reach out to the Veteran for any additional information.

**Comment by Kimberley2019** [comment]
closing ticket to route this issue to EVSS team for review and resolution.
