### ISSUE TITLE
Access for [Heather Justice]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34159]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Heather Justice

### Your Email

heather.justice@adhocteam.us

### Name of Your Team

Authenticated Experience, Product Manager, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9/bZ6LAbyhP7R/BqALJk06uqUW7MlSb+6Du3yqELY0AQF1pmHGnPE+t1YChLkyzqZsDgIctYglqeHCW81ANKFyur1OpZYWRLEIJVjr7/Vx+YMXd/6/iZDDQFkkXlhoo/3UZXtZYQGQ5cBxJBb/FAg8u4zjcPDQJaI4eOoeSp48UOm1jA8uLxzkbZfe9Sc2ukaNn3je1ZPv8KM9axrl2OJPFbSUFoeRlclTHbzY2KaAa/a0c6XHdBAQVeJ/hjonq5GTw8666Y+tFYkMf5FJN8Seb7VdDwWaEq0QZrhBFFf633YbvmXow1P2xlgcU40VyBZXTepRYsJl8s69sfT2ybNiO4VmT5SjoRKAzXgFrBGugHGdycyGsn4WpLnTw879sIN3vt+LL1CIGIsmFr3PZcJDLuIE/CJYM0pkOybVrGQiTz/nRPXFQWtbs9mq1y/dto9c8BfX9Csxfd9HwsQKSFpi7X+W2Nz6V01Nd48MtcjdKctIMgywQwuKiwXCunVih0= hdjustice@HeatherJustice-HP

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
