### ISSUE TITLE
Adding David Hirsch to DSVA Slack

### ISSUE THREAD

**Issue by HirschDavid** [department-of-veterans-affairs/va.gov-team#34179]
Please add Hirsch_David@ne.bah.com as a full member.

COR Name
Edward Hensel

Vendor Onboarding Representative Name
BAH - Jessica Riggs

Your Name
David Hirsch

Your email
Hirsch_David@ne.bah.com

Name of Your Team
BID APL Help Desk

**Comment by LizCallaghan** [comment]
I see he is already a member.
