### ISSUE TITLE
508-defect-3 [SEMANTIC MARKUP]: Download link for statements should have download attribute and should not open in a new tab

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#34177]
#### VFS team name
Debt Resolution

#### VFS product name
Medical Copays (MCP)

#### Point of Contact/Reviewers
Josh Kim (@joshkimux) - Accessibility

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
The download link for statements has several issues to be addressed including:
- it forces a new tab to open which violates WCAG guidance (g200) opening new windows and tabs from a link only when necessary (this can be very confusing for screen reader users)
- it doesn't have a download attribute

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
We recommend to:
- Remove `target="_blank"` and allow the download to happen within the current window
- Add a download attribute to the download link e.g. `download="[insert name here].pdf"`

Check out this article on accessible download links for more guidance

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by tameracorson** [comment]
@MarciMcGuire did you mean to drop this ticket into health hub myhealth MOTeam?

**Comment by MarciMcGuire** [comment]
Hm... I didn't put that ticket there AFAIK. It looks like a debt resolution team ticket from a while back.

**Comment by MarciMcGuire** [comment]
Ugh yeah I did apparently, by mistake. Fixing that now

**Comment by MarciMcGuire** [comment]
@tameracorson it shouldn't be in the board.  I think I accidentally connected two workflows last month which generated an email before I undid that change.  I don't see it on your team's board now.
