### ISSUE TITLE
[Prometheus] Routine maintenance needed

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#34180]
## The Problem
Prometheus (prod) is experiencing some instability. It sometimes goes offline:
![image](https://user-images.githubusercontent.com/3077884/146217758-ee23c75a-cca6-4513-803f-0b1c993effa1.png)

I _think_ this is related to some combination of:
- the amount of metrics we're collecting
- the various prometheus configurations for how we store data & how long it's stored for
  - `storage.local.target-heap-size`
  - `storage.local.memory-chunks`
  - `storage.local.max-chunks-to-persist`

## Extra Context
- [slack link for prometheus logs during an outage](https://dsva.slack.com/archives/C30LCU8S3/p1639504573258000)
- multiple alerts to #devops-alerts of `ApplicationMetricsWarning` & `PrometheusLocalStorageMemorySeriesWarning`
  - https://dsva.slack.com/archives/C24RH0W11/p1639561888248900
  - https://dsva.slack.com/archives/C24RH0W11/p1639562218249000

## Work to be Done
- [ ] investigate the shortcomings of our prometheus config & if they're related to outages
- [ ] Make changes to our config and/or

**Comment by jbritt1** [comment]
Not likely to be prioritized for the foreseeable future as we wish to sunset Prometheus, closing.
