### ISSUE TITLE
Establish a data completeness baseline

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3419]
**As the Facility Locator team, we need to know the baseline for data completeness so that we can request missing data from the source and so we can measure progress.**

## Goals
- Understand the differences between the data supplied via Vets-API and Facilities API
- Identify facilities with missing data in one or both APIs
- Identify facilities present in one API but not the other

## Minimum data elements

**VHA**
- Name of facility
- Facility type
- Address
- Main phone number
- Mental Health phone number
- Directions
- Hours
- Satisfaction Scores (urgent care)
- Satisfaction Scores (routine care)
- Appointment Wait times (new patient)
- Appointment Wait times (existing patient)

**Vet Centers**
- Name of facility
- Facility type
- Address
- Main phone number
- Directions
- Hours

**Benefit Centers**
- Name of facility
- Facility type
- Address
- Main phone number
- Directions
- Hours

**Cemetery**
- Name of facility
- Facility type
- Address
- Main phone number
- Directions
- Hours

## Task
For locations (VHA, VBA, NCA) currently served by Vets-api and/or Facilities-api, please supply the name, facility ID, type of missing data and which API was referenced.

This analysis does not include data supplied by PPMS for Community Care locations.

**Comment by mmiddaugh** [comment]
@davidconlon will you please confirm that my list of expected data elements for each facility is correct? Thanks!

**Comment by mmiddaugh** [comment]
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/292c16c0-9eba-4188-8b4d-fe2e57388263)

@davidconlon the image above shows the classifications affiliated with each type of facility in the Facilities API (as found in the DSVA Airtable)
We may want to 
1- confirm that all are also available in the vets-api
2- confirm that the Facility Locator should surface all classifications in search results

**Comment by davidconlon** [comment]
1. We need to also be tracking VACO Administration like the one I work in. These are, I believe, labelled as offices now but appear as cemeteries.  Low priority in terms of flushing these out, but we should have the delineation present.

2. Regional Benefit Office is listed twice, is that an error or is there a difference between the two in unseen column attributes.

3. I believe that Vets-API and Facilities API are, for all intents and purposes, using the same data from the data warehouse. 

4. I think cross-walking the datasets is a good catch. We should validate from a data standpoint what Facility Locator is currently surfacing or, more importantly, not surfacing. When we migrate to Facilities API we Start with what we are currently surfacing and understand why we might be excluding some facility types/subtypes if they are important to the veteran's journey.

**Comment by mmiddaugh** [comment]
Regarding 2. above: thanks for catching that. Completely my error.

**Comment by mmiddaugh** [comment]
@davidconlon what do you think about adding tasks to each of the api transition issue to document the data available in the vets-api and then the data available via facilities api as part of this baseline and to validate the success of the transition?
