### ISSUE TITLE
VBA SME interview artifact

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34192]
## Issue Description
We conducted interviews with VBA SMEs with the goals of

- Evaluating the current VBA taxonomy against the mental models of users: names, scope, and categorization of services
- Evaluating the list of benefits obtained from our survey of groups against the list of services offered in reality.
- Detecting missing services or context that will allow for better follow-up questions with users.
- Understanding the major pain points around accessing benefits to better be able to prepare for users’ stories.

This issue to document the findings/learnings from those interviews and next steps, including how they will frame upcoming Veteran research sessions on this topic. 

### Related artifacts 

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/benefits-taxonomy-research-SME/research-plan-benefits-taxonomy-SME-interviews.md)
- [Convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/benefits-taxonomy-research-SME/benefits-taxonomy-SME-conversation-guide.md)

---
## Tasks
- [ ] Create an artifact with key findings, learnings, next steps

## Acceptance Criteria
- [ ] Documentation is available in research folder

**Comment by Dave-Sukharan** [comment]
[SME Benefits Research.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/7771135/SME.Benefits.Research.pdf)
Here are the raw notes from our first two sessions. I can make a more formal output of research, if necessary, for these interviews as well!
