### ISSUE TITLE
Discovery Sprint Prep 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3420]
## User Story or Problem Statement
As a UX Designer, I need to logistically prepare for the discovery sprint so the design team has guidelines to follow for the discovery sprint.

## Goal
_A solidified plan for that determines the discovery methods, user research methods, and outputs/artifacts for the upcoming discovery sprint_

## Objectives or Key Results this is meant to further
- _This preparation furthers the research plan, user interview conversation guide, and outputs for the discovery sprint_

## Acceptance Criteria
The design team needs to:
- [x] _Determine the discovery methods needed_
- [x] _Determine user research methods needed_
- [x] _Determine discovery outputs and artifacts_
- [x] _Create a Discovery Project Brief ([link to discovery brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/discovery-nov19/discovery-project-brief.md))
- [x] _(If required) Share document with the team & team lead_
- [x] _Ensure Discovery Project Brief is in GH_

**Comment by rebeccawalsh** [comment]
Here is a link to the [Discovery Project Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/discovery-nov19/discovery-project-brief.md) - this document has been shared with the team in vsa-bam-2 on Nov 18 @ 2:27pm, pending feedback.
