### ISSUE TITLE
Form 28-1902w Presenting old Form Name

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#34202]
## What happened?
The title of VA Form 28-1902w is “Veteran Readiness and Employment (VR&E) Questionnaire”. The old title is “Rehabilitation Needs Inventory (RNI)”.

Questions that need answered regarding this issue: 
1. What name should the FE be showing? 
2. Are we pushing anything to Lighthouse including this name? 

28-1902w is showing the "wrong" name in our search results as it has been changed upstream. The title of VA Form 28-1902w is “Veteran Readiness and Employment (VR&E) Questionnaire”. The old title is “Rehabilitation Needs Inventory (RNI)”.
When the form was uploaded to the internet forms website the title was changed on the Admin. Page for this form however the old title still appears on the Find A Form website.We can see that the name has been updated in the CMS on the draft detail page as the "Form Title" but the "Form Name" is the legacy name. I'm not sure if this is intentional. This "wrong" name is also in Lighthouse API as the name of the form.
 
Mark said the Drupal database only pulls one. This is most likely indicated wrong in Drupal. Reach out to Allison Bernheimer

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/End2End-Find-Forms.png

Placeholder- Waiting for more context. 

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by srsuddath** [comment]
@swirtSJW we need to get with you to do some validation to see what the correct name for this form is and what we might need to do to standardize this

**Comment by swirtSJW** [comment]
In the nightly migration we pull in the "FormTitle" from the FormsDB  and populate two CMS fields 'field_va_form_name' and 'field_va_form_title'

![image](https://user-images.githubusercontent.com/5752113/148301286-549c5acb-a0ba-4bf8-bed6-8e85aa3de193.png)
when the form first appears in the FormsDB.

On subsequent updates however, the migration only updates 'field_va_form_title'
This was an intentional request.  If we updated both, then there would be no reason to have two identical fields.

The original intent  had something to do with always needing the editor to be able to overide 'field_va_form_name'   And have their override persist.   Which is why  'field_va_form_name' is editable and 'field_va_form_title' is not.

![image](https://user-images.githubusercontent.com/5752113/148302403-24782b89-864a-49c4-8c04-7228a356f523.png)

**Comment by nicole-leonard** [comment]
@swirtSJW Thank you so much for this explanation. This leads me to 2 more questions is I may. How many forms have different names in those fields out of all of the forms? Who would be responsible for fixing this in the DB for this specific form? Thank you! Nicole @TSimmz for transparency.

**Comment by swirtSJW** [comment]
@nicole-leonard 
> How many forms have different names in those fields out of all of the forms?

Good question.  I don't know.  We don't have a report of that type built.  If it is an important audit to have you can create a [CMS feature request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Enhancement%2C+Needs+refining&template=cms-enhancement.md&title=%3CSummary+of+enhancement%3E)  

>  Who would be responsible for fixing this in the DB for this specific form?

Sorry, I'm not sure who the current editors are for the forms product.

**Comment by nicole-leonard** [comment]
@srsuddath please help guide me. Steve has identified the issue. Who exactly do I reach out to to get it fixed?

**Comment by nicole-leonard** [comment]
Complete
