### ISSUE TITLE
[Research] Document Telemedicine Analytics Findings

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34217]
Description: Create GitHub pages documenting all telemedicine findings to this point.

Tasks: 
- [ ] Gather documentation
- [ ] Create GitHub page

Acceptance Criteria:
- [ ] Publish GitHUB page and send to team

**Comment by niradatta1** [comment]
@kristenmcconnell Just found this ticket, I'm guessing this wasn't done? I see the screenshot data in the related ticket #31070

**Comment by kristenmcconnell** [comment]
It was. The link was just never added. Here is the GitHub page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/Telemedicine%20Analytics.MD

**Comment by kristenmcconnell** [comment]
We just didn't find out a lot from analytics. Well, not the answers to the questions that we had.
