### ISSUE TITLE
Flag Dead Endpoints

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#34215]
Define what constitutes a dead endpoint then flag dead endpoints in the endpoint inventory sheet

**Comment by CosmicSyntax** [comment]
Possibly dead endpoint:
veteran/v0/representatives
v0/medical_copays
v0/form1010cg/attachments
v0/apidocs
pg_hero/home
covid_research/volunteer/submissions
claims_api/v1/forms/power_of_attorney
check_in/v2/sessions
check_in/v2/patient_check_ins

**Comment by ewilson-adhoc** [comment]
This work was done as part of the effort here: https://docs.google.com/spreadsheets/d/14iNeWOyaMe0aqVtgfCqTE7cl3xAfQ7YJDsjRbADOXCk/edit#gid=1482742543
