### ISSUE TITLE
Access for Brian DeConinck

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#34227]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Brian DeConinck

### Your Email

brian.deconinck@adhocteam.us

### Name of Your Team

Platform Product Support Team - Software Engineer / Accessibility Specialist

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzuXM0C0O7r5qwnkatNhn2ZNakbRje/cKR6BSS2rB7VwtE5BOCuC1cURFF5aoIwdcdhWMWGAQBHt+40yhaNneSQnu6aQxf7etkhGJ0rSMJIHdpMrLICSIcRgVDtkcSq0VDcstR2as/vs5KRKC5beYzvWhmXq0ixu4bpGRBf9oZHFxcmIi6sO9Q8evfqqx58Ai579d0P/SxGY7i6OcZ2bCqMKMbeUreMLOBqy7YqObCwGKH5Vd1WegD2sigO2XokZIVICqqgOxbKtxPRQi4K5vxoVr3nyU/UuDGpG0w3xQKJWE2Eg7BBYH1O/4OAV9P+jmRlDmvnhC4CL0HMQzV5efKvrjR1nt2q6rN39YEWElbPr1DkSfD8uk6jZklfJBW4BAROAYIUiSnbpKNqTcHS5dGdQHLt/jOB8B1tUrB2sYBaYyI1z7ihxv56AbQA+d0urpz19PB7ANf0Z8XiFjCWqCneRW4KiGrMw7z7zOoLxHgXuXsgK9zUqbfxcBmow9GiDs= briandeconinck@BrianDeConinck-HP

**Comment by briandeconinck** [comment]
Note that SOCKS access was previously granted in #33829. Had a hardware issue and got a new machine, so I'm going through the process again. Thank you!

**Comment by rbeckwith-oddball** [comment]
SOCKS access has been enabled and your old key has been replaced. Please give it about 15 minutes before attempting to use it.
