### ISSUE TITLE
Historic health apartment project onboarding: Jesse

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#34236]
- [x] Review [Health Apartment Onboarding Guide]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/onboarding.md) in GitHub
- [x] Review iterative design in [Project mural room] (https://app.mural.co/t/innovationboards1199/r/1631551671896) in Mural
- [x] Review the [platform tools] (https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-tools.1872855066.html) list and follow directions for all tools appropriate for your profession
- [x] Review [historic generative research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/research/generative-research-study-1/OCTO%20health%20research%20report%2022%20Mar%202021.pdf) on health portal research
- [x] [History of research projects on Veteran Facing Tools]  (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md)

**Comment by jsing0** [comment]
completed and reviewed
