### ISSUE TITLE
[Tier 3] Appeal viewing issue - SF 06339872

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34232]
## Issue Description
_Please review details in case below and from encrypted email for issue with veteran viewing her appeal._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@vhenry07 @alsleaders 
Encrypted email containing details of case have been sent.

From: Daniels, Kimberley N. (Oddball, Inc.) 
Sent: Wednesday, December 15, 2021 5:13 PM
To: Henry, Veronica (GovernmentCIO) <Veronica.Henry@va.gov>
Subject: FW: [EXTERNAL] Re: Appeal status issue

Good Afternoon Veronica,

I wanted to pass this along to you since it contains screenshots that contain PII.  The ZH ticket number is below.

[Tier 3] Appeal viewing issue - SF 06339872 · department-of-veterans-affairs/va.gov-team (zenhub.com)

Kind Regards,

Kimberley




From: REDACTED 
Sent: Monday, December 13, 2021 10:47 PM
To: Daniels, Kimberley N. (Oddball, Inc.) <Kimberley.Daniels@va.gov>
Subject: [EXTERNAL] Re: Appeal status issue

When accessing my disability claim using VA.gov, My HealtheVet, and ID.me and receive the following message:

"
"Supplemental claim for disability compensation updated on November 1, 2021
Status: We don’t know your status
Issues on review: 4 compensation issues
Submitted on: November 1, 2021"
I have used my Dell computer and my Android device to log in and I receive the above error message on all websites. I have used Internet Explorer and  Chrome.  I have cleared my cache  and cookies. I have signed in with VA.gov, DS Logon, My HealtheVet, and ID.me and receive the same  message.

**Comment by alsleaders** [comment]
We are waiting for the veteran to get back to us with some more information to research their appeals status issue.

**Comment by jason-gcio** [comment]
Blocked until more Veteran info is supplied.
Question: is this reproducible?  Is the submitted date legit?  Can the Veteran see the 526 in their eFolder? (If we can get a hold of their VA file number, we can get into VBMS and look ourselves)

**Comment by Kimberley2019** [comment]
From: VA Technical Support 
Sent: Monday, December 20, 2021 1:58 PM
To:REDACTED
Subject: RE: [EXTERNAL] Re: Appeal status issue

Good Afternoon,

Are you able to provide us with your application number?  The team needs this information in order to do more research.

Please review the information below in order to know what information we need.  You should be able to see that every time they make a change and click “back” or “continue” buttons and that number should appear just underneath those buttons. 

After you have tried again, if you are still experiencing the issue, please reply to this email with a screenshot of the Application ID number. An example screenshot can be viewed in the attachment. This information will help the Benefits

**Comment by Kimberley2019** [comment]
customer never responded to the request form more information in order to review and resolve issue.

Closing ticket
