### ISSUE TITLE
Update VAOS in-flow redirect

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#34233]
## Background
Currently, if a user directly enters a page in the flow, they are redirected to the Type of Care page to begin scheduling.

## User Story
As Product, I would like users who attempt to directly enter the middle of a VAOS flow to be redirected to VAOS homepage so they don't miss any steps in the scheduling flow.

## Acceptance Criteria

Given any user
When user **directly enters** any page in the flows (`/health-care/schedule-view-va-appointments/appointments/new-appointment*` or `/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment*`)
Then redirect user to the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`)

## Technical Notes
After a user signs in `?postLogin=true` is appended to the URL

## Definition of Done

- [ ] All acceptance criteria are met

**Comment by jenniemc** [comment]
@ldelacosta, I'm wondering about situation when user book marked start of new appointment flow or type "/health-care/schedule-view-va-appointments/appointments/new-appointment" directly in the URL. Would that situation redirect user to landing page? cc @ptouchton

**Comment by ldelacosta** [comment]
@jenniemc - Per acceptance criteria, the site whether they typed it in or clicked on the bookmarked link, it will re-direct the user to the VAOS homepage. Thanks.

**Comment by ldelacosta** [comment]
@JRRoof - please validate in staging.

**Comment by JRRoof** [comment]
Tested workflow with users judy.morrison@id.me (v0) and kidys.b.quankep@id.me (v2).
Tested workflows with both users authenticated and unauthenticated.
Tested using the following URLs:
https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment*
https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment*

Test Result:  Passed all tests.  

Test results with screen shots in attached document:
[https://app.zenhub.com/files/133843125/964cae1e-719c-43a2-9514-9f7593d4d486/download](https://app.zenhub.com/files/133843125/964cae1e-719c-43a2-9514-9f7593d4d486/download)
