### ISSUE TITLE
Prototype Cerner offboarding experience from VAOS homepage

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#34234]
## Request

How might we direct Cerner users to the My VA Health portal if they skip the static landing page and navigate directly to the VAOS homepage/appointment lists?

Note- we already have it covered in the scheduling flow.

## Background
The authentication widget on the static landing page detects if a user is registered at a Cerner site and displays a link to the My VA Health portal.

If user goes directly to the VAOS homepage and is a Cerner user, they will miss the information on the SLP directing them to the My VA Health portal for some of their appointment management and scheduling.

![slp cerner widget.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/ed38fe8d-b601-499e-842c-6897e89c9f6e)

## Business Requirements
- Scheduling and appointments for Cerner sites are managed in the My VA Health portal
- Veterans registered at Cerner sites and eligible for Community Care can use VAOS to request Community Care appointments

**Comment by laurenernest** [comment]
Moving this to the product column. Holding on dev ticket until we have a better idea of the SLP content changes and if we can bypass it.

**Comment by outerpress** [comment]
@ldelacosta this is the work we're doing for MHV on VA.gov - do you want to repurpose this ticket for that or do we already have tickets covering it? Feel free to close out if so

**Comment by outerpress** [comment]
This work is being covered by #57036 , closing
