### ISSUE TITLE
Redirect Request: /playbook/** to /

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#34240]
We are retiring all content under `/playbook` and will be forwarding to the homepage (`/`) until the content is removed in 1 month. The redirect will stay in place.

- [slack reference and approval](https://dsva.slack.com/archives/CE4304QPK/p1638813077231400)
- [full deprecation plan](https://vfs.atlassian.net/wiki/spaces/FTT/pages/1995407406/2021-11-29+VA.gov+Playbook+Deprecation+Plan?atlOrigin=eyJpIjoiZDIxOGJkZWEyZWQ4NDQ2ZGEzYTNhZTBiMDYwZDcxNzgiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: Flexible timeline, as soon as possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/playbook/ | https://www.va.gov/
https://www.va.gov/playbook/* | https://www.va.gov/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/10451

**Comment by mnorthuis** [comment]
@brianalloyd @kelsonic Ok, this is clear and ready to roll.  Thank you!

**Comment by kelsonic** [comment]
Redirects are in production:
https://www.va.gov/playbook/
https://www.va.gov/playbook/blah
