### ISSUE TITLE
[BE] Setup Betamocks for Pre-Check-in

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#34267]
## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by jparker0425** [comment]
@randomsync here is the ticket for betamock specific to pre-check-in. Split from 31500 that is check-in specific. Is this specific to unauthenticated users like the title says, or does that need to be more generic?

**Comment by randomsync** [comment]
> @randomsync here is the ticket for betamock specific to pre-check-in. Split from 31500 that is check-in specific. Is this specific to unauthenticated users like the title says, or does that need to be more generic?

It can be more generic, updated.
