### ISSUE TITLE
[Tier 3] Application submission issue - SF 06198425

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34273]
## Issue Description
_Caller is experiencing issues with submitting an application.  Please review notes below and encrypted email for more details._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@alsleaders encrypted email sent.

From: Daniels, Kimberley N. (Oddball, Inc.) 
Sent: Thursday, December 16, 2021 4:00 PM
To: Leaders, Amanda L. (Government CIO) <Amanda.Leaders@va.gov>
Cc: Henry, Veronica (GovernmentCIO) <Veronica.Henry@va.gov>
Subject: FW: VA Benefits Letter download issue

Good Afternoon Amanda,

I wanted to pass this along to you since it contains screenshots that contain PII.  The ZH ticket number is below.


[Tier 3] Application submission issue - SF 06198425 · department-of-veterans-affairs/va.gov-team (zenhub.com)


Kind Regards,

Kimberley

**Comment by Kimberley2019** [comment]
@alsleaders @vhenry07 No movement on this case

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by Kimberley2019** [comment]
Case 'In Progress'
