### ISSUE TITLE
<va-progress-bar> aria-label default value uses percent with multiple decimals

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#34279]
## Issue Description
Migrating and testing `<va-progress-bar>` on `vets-website` led to the discovery of percent values with multiple decimals passed in as a prop resulting in a bad user experience when using a screen reader. This component's `aria-label` value defaults to the percent prop value when a label isn't given. 

![Screen Shot 2021-12-16 at 17.42.38.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/ae41ff4e-56f5-4289-a484-587640532da8)

## Acceptance Criteria
- [ ] The value of percent when used as the aria-label should be an integer

**Comment by andresriveratoro** [comment]
When using a screen reader, this reads as "17.3291......% complete, 17%, progress...". I believe the second percent value is coming from aria-valuenow and that value is being rounded.

**Comment by bkjohnson** [comment]
Also, we noticed that this is not a regression in the web component. This behavior is already live in the `<ProgressBar>`.

![image](https://user-images.githubusercontent.com/2008881/146468453-728d63bb-5470-4ac0-83ac-f129fa2ad804.png)
