### ISSUE TITLE
Create list of other online digital tools not on top 25 forms landing pages list

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#3427]
@lunascoop commented on [Wed Nov 13 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19969)

Cross-check top 25 forms landing pages and list pages that have online tools that aren't on the list.

**Comment by lunascoop** [comment]
Hi @lwalsh617 . Here is the list of digital tools not included in your top 25 forms page list. See my highlighted notes. 
[Digital Tools not included in top 25 VA Forms List.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3846678/Digital.Tools.not.included.in.top.25.VA.Forms.List.xlsx)

**Comment by lwalsh617** [comment]
Hi @lunascoop,
Here's the copy deck for the 25 top forms LPs. Elements are as follows:
- Form Number
- Form Name
- Related to: (Insert the benefit hub(s) that apply)
- When to use this form (with download CTA that includes form number)
- There's also an online tool (if applicable)
- Related forms and instructions (If applicable. These tend to be other forms that must also be completed as part of the process, and Spanish language versions.)
- Helpful links (At minimum, we have default ones for direct deposit, address, medical records and military records. In some instances, we've added other)
There's another piece that I'm working on for the 25 that you'll need to incorporate as well. Here's direction from Jen:  
...please also include at the top of each copydeck, a place where we can include SEO and IA info for when we start building these. Some of this, you'll need to consult with Mikki later to determine, but others, we can provide when we're closer to delivering. (Can make a new ticket just for this phase of work .)
BREADCRUMB: {Mikki}
CANONICAL URL: {Mikki}
META (BROWSER) TITLE:
META DESCRIPTION:
1-2 SEO TERMS:

**Comment by Karak888** [comment]
@lunascoop should this go back into "in-progress," or has this been validated by Laura and or Jen? Thanks!

**Comment by lunascoop** [comment]
@Karak888  Thanks. I moved it back to In Progress.

**Comment by lunascoop** [comment]
@lwalsh617 
[VA.Forms.LP.WIP.copy_v0.3_11-20-19-1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3870431/VA.Forms.LP.WIP.copy_v0.3_11-20-19-1.docx)

**Comment by Karak888** [comment]
@lwalsh617 please review this one!

**Comment by lwalsh617** [comment]
Looks good. Thanks, @lunascoop. :) Am adding to my master deck and will find SEO keywords.
