### ISSUE TITLE
[Discovery] Improvements to the migration script

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#34284]
## Description
As we use the migration script for migrating more and more React components to web components, we are discovering more and more weaknesses in the script. We'd like to take a little time and figure out if there are some ways we can improve it.

## Acceptance Criteria
- [ ] Review the migration script and consider any improvements we might make
- [ ] Document any necessary improvements in this ticket
- [ ] Tag Katy and Carol for review

**Comment by k80bowman** [comment]
@bkjohnson if you have any examples of how the script has failed, feel free to add them here.

**Comment by bkjohnson** [comment]
Here's an example of the script failing on a component that has nested curly braces:

```
yarn migrate-component --dir src/applications/personalization/profile/components/alerts --component AlertBox
```

<details>

![image](https://user-images.githubusercontent.com/2008881/146567092-0c7d9d01-e772-4f2c-bdab-1b50a5dcd9d8.png)

</details>

Here's another failure related to the transformer expecting some form of headline, as well as something involving the `content` prop:

```
yarn migrate-component --dir src/applications/hca --component AlertBox
```

<details>

![image](https://user-images.githubusercontent.com/2008881/146567735-9b5e1f6a-56f3-4211-873a-be070b627239.png)

![image](https://user-images.githubusercontent.com/2008881/146567866-9c1cd49e-37c3-4983-a186-c770ed8f21f6.png)

</details>

Here's another example where closing tags get messed up:

```
yarn migrate-component --dir src/applications/hca --component LoadingIndicator
```

<details>

![image](https://user-images.githubusercontent.com/2008881/146569543-8c400603-98da-4172-af95-73f9776c7a44.png)

</details>

**Comment by k80bowman** [comment]
We are going in a different direction for our migrations, closing this ticket for now.
