### ISSUE TITLE
Upgrade Ansible to 2.9 in DevOps repo

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3428]
New version of ansible is out, we should upgrade to it (there are several deprecations and warnings to handle)

Beware that this release drop support for yum+python3, so amazon linux nodes will need both for actioning these if you intend to add py3 support)

## AC
- [ ] running 2.9.x
- [ ] no new warnings
- [ ] fix current deprecated stuff
- [ ] still works in vens/python 2.7
- [ ] don't upgrade credstash past 1.15

**Comment by nathanhruby** [comment]
similar work here: department-of-veterans-affairs/vets-contrib#3294

**Comment by ricetj** [comment]
Need to check if DVP is doing this

**Comment by wyattwalter** [comment]
We are not going to be doing this. We'll start with new stuff at the latest version and not worry about the in-place upgrade on it.
