### ISSUE TITLE
Integrate a service (ArgoCD) with cognito

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#34293]
A two way configuration needs to happen between the ID provider and the client, so the broker can direct appropriately. In order for that redirect to happen we need to integrate the service we are using with cognito by configuring an app client
- [ ] Create & configure new app client with cognito
- [ ] Configure tool to integrate with cognito

Task is done when:
- [ ] app client is present in cognito

**Comment by dginther** [comment]
We decided to go with Keycloak, over Cognito
