### ISSUE TITLE
Button URL change request from Auth-Profile

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34290]
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [x] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**    Yes
   * We are splitting apart the Personal Information and Contact Information pages in VA.gov Profile and need a URL on a button changed.
   
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md
- Link to or attach user flows: N/A
- Link to prototype or mockups: https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i
- Link to any epics/issues that may be helpful:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/31180

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [X] **Other**
We need the button link on https://www.va.gov/change-address/ changed from https://va.gov/profile/personal-information to  https://va.gov/profile/contact-information
![image](https://user-images.githubusercontent.com/73354907/146392330-e3fae06e-8d99-42b0-bb19-d263eeb98b64.png)

      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

- Estimated launch date:   Feb 2022
- Estimated staging review date:  Late-mid Jan 2022
- Content and IA work needed by:  mid Jan 2022

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Auth - Profile
- DEPO product owner: Samara Strauss
- Product manager: Marci McGuire
- Designer: Christina Gednalske
- FE engineer: Adam Whitlock
- Product/team Slack channel: #vsa-authd-exp

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by kelsonic** [comment]
PR is up, we won't merge it until you give us the green light ✅ https://github.com/department-of-veterans-affairs/vets-website/pull/19719

**Comment by MarciMcGuireGCIO** [comment]
I’m sorry for the confusion @Samara-Strauss , I checked off my to creating the requests, not that the work in the tickets themselves have been completed. I just listed the new ticket numbers for reference.

**Comment by brianalloyd** [comment]
Hi @MarciMcGuireGCIO any sensing on timing for this ticket?  Just want to make sure we keep it on the radar forward.

**Comment by MarciMcGuireGCIO** [comment]
@brianalloyd  I don’t have a great sense of timing yet because we have a significant dependency on the group that manages the MPI database.  Hopefully after our next meeting with them this week I’ll be able to better predict.  Thank you for checking in!

**Comment by MarciMcGuireGCIO** [comment]
@brianalloyd Quick update- we were advised yesterday that we will now be integrating with VA Profile vs directly with MPI, so our timeline is still a bit fuzzy. We are aiming for March, but I will update you if anything changes.

**Comment by brianalloyd** [comment]
@MarciMcGuireGCIO thanks for the update. I'm going to place this in our backlog and can action when things come into scope.  Just let us know when you get the green light and we'll scrub into the issue.

**Comment by kelsonic** [comment]
CC @srsuddath this is the ticket for which I have a PR open fysa: https://github.com/department-of-veterans-affairs/vets-website/pull/19719

**Comment by SKasimow** [comment]
@adamwhitlock1 - I was going to ask you if we should put the work outline above (updating the button for changing addresses) to ticket #40351 but looks like Kelson already did the work; I see a PR submitted with a "hold" for this request
[here](https://github.com/department-of-veterans-affairs/vets-website/pull/19719).

Could you take a look and lmk if this would be something you could push out when we launch?

There is also a small content change outside of the widget but think that Danielle's team would handle.

**Comment by Samara-Strauss** [comment]
Thanks for having an eye on this, @SKasimow! Yes, Danielle's team would handle the content updates, and there might not be anything for @adamwhitlock1 to do if Kelson's work looks good. Let's keep an eye on this and make sure it goes out with the larger launch.

**Comment by SKasimow** [comment]
Great - thanks for the feedback!

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - can you check the PR and see if we can use to update the link in the green button to take user to the new stand-alone Contact page?

**Comment by Samara-Strauss** [comment]
![image](https://user-images.githubusercontent.com/34068740/178799565-c5667afe-f926-4245-88fb-021e1c96705d.png)

Is there a separate ticket to update the copy in this widget? Or should that copy change be handled as part of this ticket?

**Comment by SKasimow** [comment]
@adamwhitlock1 - are you able to make the content change on the widget?

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 I'm sorry for the confusion, and my above comment is definitely confusing. This is the way I think things work:

- Content team updates content *outside* of the widgets (red area in screenshot)
- A FE dev needs to update anything to do with the widgets, whether that is content or functionality (blue area in screenshot)

So, yes, it would be great if you could update the copy in the widget to change the bolded text from "Personal and contact information" to "Contact information"

![image](https://user-images.githubusercontent.com/34068740/179014465-6779554a-f00b-4905-af83-d8b8bca32a27.png)

**Comment by adamwhitlock1** [comment]
Oh that makes more sense! Sure ill update the copy in the widget. Thanks @Samara-Strauss

**Comment by adamwhitlock1** [comment]
Update has been made and is live in staging @Samara-Strauss and @SKasimow 

![Screen Shot 2022-07-19 at 11.40.04 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/5176b393-8130-44af-bbc5-5dfd22f1ec45)

**Comment by SKasimow** [comment]
@adamwhitlock1 - am I following correct steps to test bc this is what I am seeing:

- sign into staging and click https://staging.va.gov/change-address/
- links to https://www.va.gov/change-address/
- asks me to sign in
![Screen Shot 2022-07-20 at 10 22 37 AM](https://user-images.githubusercontent.com/74627978/180008292-28f133ee-6a69-4566-ace9-a91589da38ab.png)

**Comment by adamwhitlock1** [comment]
You have to sign in to staging to see the widget @SKasimow

**Comment by SKasimow** [comment]
@adamwhitlock1 - if I am logged in, open another tab and enter https://staging.va.gov/change-address I see the correct alert box. 

if I try to do get there using search within the staging account I am signed into, then things go awry. Maybe I shouldn't have used this sequence (?) but I'll show you what I am doing and seeing when we talk later fwiw.

**Comment by adamwhitlock1** [comment]
oh that is probably just the wonkiness with the staging search app. I wouldnt rely on that for getting to a specific location in staging.
