### ISSUE TITLE
[Bug] [IE11] Medical Copays - Overview page - Styling anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#34324]
## What happened?
In Windows **Internet Explorer 11**, on **[Staging Medical Copays > Balances Overview](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)** page, **No-history** alert styling didn't match mockup.

\[COVID-alert styling anomaly already logged in #33844\]

## Specs:
- Device: Windows 10 desktop
- Browser: IE11\*
- Test User: `vets.gov.user+86@gmail.com` (Brian)  \[see [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc \[in private repo\] for password\]

## Steps to Reproduce
- URL: Sign-in\* first on [homepage](https://staging.va.gov/), then go to https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/
- Test User: \[see **Specs** above\]
- On authenticated **Overview** page, observe that **No-history** alert styling doesn't match mockup.

**Screenshot**:
![image](https://user-images.githubusercontent.com/587583/146594270-cbfc39b9-a386-468b-8c13-49a52539ce6f.png)

## Desired styling
Alert styling should match [mockup](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141468842/simulate/no-panels):
![image](https://user-images.githubusercontent.com/587583/146595341-8d027215-6b45-443b-80bd-7d6ef70d26d3.png)

## Acceptance Criteria
\[see **Desired styling** above.\]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

\* Click **Proceed anyway** when ID.me "complains" about IE11.

**Comment by craigwheeler** [comment]
hey @tlei123 looking into this issue and ID.me is returning an error on staging saying IE11 is not supported so wanna confirm this with you?

![1VA-General Desktop 2022-01-04 09-26-24](https://user-images.githubusercontent.com/7518899/148074462-9f63cdab-b082-42bb-b606-9977c1609b05.png)

![1VA-General Desktop 2022-01-04 09-25-00](https://user-images.githubusercontent.com/7518899/148074497-448b0820-ab48-4887-aae4-1335fc9fbfdd.png)

**Comment by tlei123** [comment]
> error on staging saying IE11 is not supported

@srsuddath , try clicking **Proceed anyway** if you see that button on the same screen &mdash; that's been working for me so far using IE11.  IF that button doesn't work for you, please let me know.

**Comment by craigwheeler** [comment]
@tlei123 still not able to bypass the compatibility check by pressing "Proceed anyway" but looking into these issues I noticed that all of these IE11 styling anomalies seem to be related to [platform design system components](https://design.va.gov/components/). Could take a look at the design system to verify you're seeing the same issues with the following components when you have time?.. thanks

- [alerts](https://design.va.gov/components/alertboxes)
- [accordions](https://design.va.gov/components/accordions)

**Comment by denisecoveyduc** [comment]
@caw310 Another one for the design system team. Thanks ;)

**Comment by caw310** [comment]
@k80bowman , adding you as an assignee so we look into this one.

**Comment by caw310** [comment]
No longer supporting IE11 so closing.
