### ISSUE TITLE
Align VBA list display

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34327]
## Issue Description
The Services list on VBA detail pages contains spelling/spacing errors and other deviations from the list as displayed in the search dropdown. 

![image](https://user-images.githubusercontent.com/55411834/146595259-fe12a020-c5b6-49ab-86b3-720047f19dde.png)

![image](https://user-images.githubusercontent.com/55411834/146595417-0de9646c-28a4-4c07-91ca-dbbee1bdbfae.png)

![image](https://user-images.githubusercontent.com/55411834/146595472-47d5b2c0-b152-4594-8115-6794cca12091.png)

[Example detail page](https://www.va.gov/find-locations/facility/vba_306h)

---
## Tasks
- [ ] Ensure the services appear on the detail page as they are presented in the service type dropdown. 

## Acceptance Criteria
- [ ] When displayed on a detail page for a given location, VBA services should appear as

> Applying for benefits
> Burial claim help
> Disability claim help
> eBenefits registration help
> Education and career counseling
> Education claim help
> Family member claim help
> Help for homeless Veterans
> VA home loan help
> Insurance claim help and financial counseling
> Integrated Disability Evaluation System assistance (IDES)
> Pensions
> Pre-discharge claim help
> Transition help
> Updating direct deposit information help
> Vocational rehabilitation and employment help

**Comment by mmiddaugh** [comment]
Gaida did similar work in #20567

**Comment by GcioNapoleon** [comment]
This is the function that's causing the problem. Instead of passing the Front End camelcase values it would be a better option if the CMS sent us values that don't need nay modification.


![Screen Shot 2021-12-23 at 11 56 17 AM](https://user-images.githubusercontent.com/95312667/147276662-6efcbaf2-58db-4664-84aa-88689171dc34.png)


https://api.va.gov/facilities_api/v1/va/vba_306h

"services": {
                "benefits": [
                    "ApplyingForBenefits",
                    "BurialClaimAssistance",
                    "DisabilityClaimAssistance",
                    "eBenefitsRegistrationAssistance",
                    "FamilyMemberClaimAssistance",
                    "UpdatingDirectDepositInformation"
                ]
            },
