### ISSUE TITLE
10-10EZ | Addition of American Indian Question | PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34326]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

As a Native American, I want to be able to specify this information during enrollment on the 10-10EZ, in order to receive appropriate VA Health Care. This is a new question being added on both the paper form and online.

- [Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product/product-outline.md)
- [Product/Feature Epic](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/28973)
- [Product/Feature Design prototypes](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6)
- [Test Rail](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: @Dene-human 
Content/IA: @DanielleThierryUSDSVA 
Front-end: @lzapson 
Back-end: @jchilders 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to [Use Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/American%20Indian%20question/product/american-indian-question%20Use%20Cases.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by SKasimow** [comment]
@tlei123 Hi Tze - you reviewed an earlier draft write-up for these use-cases so they will probably look familiar. I know you said I didn't need to include interactions but left them in since I had them :)

I think I've covered everything needed for this ticket...except for a staging account for the authenticated user. Would I just take an account from the staging accounts repository??

Thanks and happy hols!

**Comment by tlei123** [comment]
@LinnJS / @jchilders , a couple requests if you wouldn't mind:

1.  Please takea look at the [provided Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/10-10ez/use-cases.md), and let me know if we really need separate cases to **test the AIQ page itself**?\*
2.  Once the above is decided, please help determine the Staging test-account(s) for the Case(s).

Thanks much!  :)

\*I'm thinking we just need one use-case for the AIQ, since I'm not seeing AIQ-specific usage/behavior changing between the current separate cases, but I might be wrong.


cc @SKasimow

**Comment by jchilders** [comment]
@tlei123 A single use case should be fine.

**Comment by hdjustice** [comment]
Hi @tlei123 - We received an approval to publish the American Indian question.  We have some content changes to implement first, and I wasn't sure if this still needed to go through QA with you.  I do not believe this requires a Staging review, as it seems there was determination some time ago that this change did not require a full collab cycle.  
Let me know if you have any questions.  I will keep you looped in as soon as the content changes are made.
Thanks!

cc: @markfallows

**Comment by hdjustice** [comment]
@tlei123 I have asked Shira about it, since I have gotten conflicting information. Pending response.

**Comment by hdjustice** [comment]
Hi @tlei123 - Looking to turn this feature on in Staging within the upcoming sprint (Sprint starts tomorrow 6/28-7/12).  I found some Use cases and will be setting up an Accessibility testing document to run through too.  I will keep you looped in when we want to start running those tests.

**Comment by tlei123** [comment]
Thanks, @hdjustice !  FYI, I currently have Fri 7/8 through Mon 7/11 booked up for Authd-Exp test-runs.  I'll keep you posted on any timeline changes there.

**Comment by hdjustice** [comment]
Got it, I will be checking on the feature this morning and will let you know our plan.  Thanks so much!

**Comment by markfallows** [comment]
Should this still be in the Icebox?

**Comment by markfallows** [comment]
Closing ticket as unnecessary and/or completed.

Team did QA internally on the question.
