### ISSUE TITLE
[FE] Create an API mock server that tracks UUID

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34325]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Update the new single source `api` to track UUID across sessions. This is for pre-check and the day of check-in to use the same logic and have a shared experience. 

Create a set of standardized UUIDs to pre-fill different experiences.

Each UUID needs to have a last4 and lastName 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by loripusey** [comment]
@mdewey can you add some information to this ticket so that I can understand the need?

**Comment by loripusey** [comment]
No response to questions, I'm closing this ticket.
