### ISSUE TITLE
DocuSign PDFs fail upload

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#34336]
When uploading a DocuSign PDF, a 500 occurs. This is due to `pdfinfo` failing to parse the PDF correctly (xref table too large error).

A fix was merged into poppler master on [Dec 23rd, 2020](https://gitlab.freedesktop.org/poppler/poppler/-/commit/4f478daa6a9734b8f269a6586bdce2909844bb6f). I'm not certain which version it's fixed in but I know it's not working on 20.09.0 and it is working in 21.11.0. The [CHANGELOG](https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/NEWS) fails to mention the fix.

Here's how to repro the issue and fix with just the ruby image from Docker Hub:
```
# Installs 2020.11 and Fails (Bottom Left)
docker run -it --rm -v /Users/ericboehs/Downloads:/tmp ruby:latest bash
apt-get update; apt-get install -y poppler-utils
pdfinfo /tmp/VA21-22-kostya-signed.pdf > /dev/null 2>&1 && echo "Success" || echo "Failure"

# Installs 2021.11 and Succeeds (Bottom Right)
docker run -it --rm -v /Users/ericboehs/Downloads:/tmp ruby:latest bash
echo "deb http://ftp.debian.org/debian experimental main contrib non-free" >> /etc/apt/sources.list
apt-get update; apt-get install -y -t experimental poppler-utils
pdfinfo /tmp/VA21-22-kostya-signed.pdf > /dev/null 2>&1 && echo "Success" || echo "Failure"
```

[Here's an example PDF](https://github.com/department-of-veterans-affairs/vets-api/blob/4130ead4214487d5922b5ba2c138a919974354e7/spec/fixtures/pdf_info/VA21-22-kostya-signed.pdf) which will cause the error.

Installing the experimental poppler-utils packge in the [vets-api Dockerfile](https://github.com/department-of-veterans-affairs/vets-api/tree/k8s/Dockerfile) causes gcc not to be installed which makes all Ruby gems with native extensions fail to compile.

<details><summary>Attempt 1 (native gems won't install)</summary>

```patch
diff --git a/Dockerfile b/Dockerfile
index fe09f1fae..cb5cf0fad 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -13,42 +13,8 @@ RUN groupadd --gid $USER_ID nonroot \
 
 WORKDIR /app
 
-RUN apt-get update \
-  && apt-get install -y build-essential libpq-dev git imagemagick curl wget pdftk poppler-utils file \
-  && apt-get clean \
-  && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* /tmp/* /var/tmp/*
-
-# Relax ImageMagick PDF security. See https://stackoverflow.com/a/59193253.
-RUN sed -i '/rights="none" pattern="PDF"/d' /etc/ImageMagick-6/policy.xml
-
-COPY config/clamd.conf /etc/clamav/clamd.conf
-
-# Download VA Certs
-RUN wget -q -r -np -nH -nd -a .cer -P /usr/local/share/ca-certificates http://aia.pki.va.gov/PKI/AIA/VA/ \
-  && for f in /usr/local/share/ca-certificates/*.cer; do openssl x509 -inform der -in $f -out $f.crt; done \
-  && update-ca-certificates \
-  && rm .cer
-
-ENV LANG=C.UTF-8 \
-   BUNDLE_JOBS=4 \
-   BUNDLE_PATH=/usr/local/bundle/cache \
-   BUNDLE_RETRY=3
-
-RUN gem install bundler:${BUNDLER_VERSION} --no-document
-
-RUN wget -q https://vets-api-build-artifacts.s3-us-gov-west-1.amazonaws.com/bundle_cache.tar.bz2 -O - \
-  | tar -xjvf - -C /usr/local/bundle/
-COPY modules ./modules
-COPY Gemfile Gemfile.lock ./
-RUN bundle install \
-  && rm -rf /usr/local/bundle/cache/*.gem \
-  && find /usr/local/bundle/gems/ -name "*.c" -delete \
-  && find /usr/local/bundle/gems/ -name "*.o" -delete \
-  && find /usr/local/bundle/gems/ -name ".git" -type d -prune -execdir rm -rf {} +
-COPY --chown=nonroot:nonroot . .
-
-EXPOSE 3000
-
-USER nonroot
-
-CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
+RUN echo "deb http://ftp.debian.org/debian experimental main contrib non-free" >> /etc/apt/sources.list
+RUN apt-get update
+RUN apt-get install -y build-essential libpq-dev git imagemagick curl wget pdftk file
+RUN apt-get install -y -t experimental poppler-utils
+RUN gem install pg
```

</details>

<details><summary>Attempt 2 (gcc fails to install)</summary>

```patch
diff --git a/Dockerfile b/Dockerfile
index fe09f1fae..3d0fb3d00 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -13,42 +13,8 @@ RUN groupadd --gid $USER_ID nonroot \
 
 WORKDIR /app
 
-RUN apt-get update \
-  && apt-get install -y build-essential libpq-dev git imagemagick curl wget pdftk poppler-utils file \
-  && apt-get clean \
-  && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* /tmp/* /var/tmp/*
-
-# Relax ImageMagick PDF security. See https://stackoverflow.com/a/59193253.
-RUN sed -i '/rights="none" pattern="PDF"/d' /etc/ImageMagick-6/policy.xml
-
-COPY config/clamd.conf /etc/clamav/clamd.conf
-
-# Download VA Certs
-RUN wget -q -r -np -nH -nd -a .cer -P /usr/local/share/ca-certificates http://aia.pki.va.gov/PKI/AIA/VA/ \
-  && for f in /usr/local/share/ca-certificates/*.cer; do openssl x509 -inform der -in $f -out $f.crt; done \
-  && update-ca-certificates \
-  && rm .cer
-
-ENV LANG=C.UTF-8 \
-   BUNDLE_JOBS=4 \
-   BUNDLE_PATH=/usr/local/bundle/cache \
-   BUNDLE_RETRY=3
-
-RUN gem install bundler:${BUNDLER_VERSION} --no-document
-
-RUN wget -q https://vets-api-build-artifacts.s3-us-gov-west-1.amazonaws.com/bundle_cache.tar.bz2 -O - \
-  | tar -xjvf - -C /usr/local/bundle/
-COPY modules ./modules
-COPY Gemfile Gemfile.lock ./
-RUN bundle install \
-  && rm -rf /usr/local/bundle/cache/*.gem \
-  && find /usr/local/bundle/gems/ -name "*.c" -delete \
-  && find /usr/local/bundle/gems/ -name "*.o" -delete \
-  && find /usr/local/bundle/gems/ -name ".git" -type d -prune -execdir rm -rf {} +
-COPY --chown=nonroot:nonroot . .
-
-EXPOSE 3000
-
-USER nonroot
-
-CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
+RUN echo "deb http://ftp.debian.org/debian experimental main contrib non-free" >> /etc/apt/sources.list
+RUN apt-get update
+RUN apt-get install -y -t experimental poppler-utils
+RUN apt-get install -y build-essential libpq-dev git imagemagick curl wget pdftk file
+RUN gem install pg
```

</details>

(Testing was completed on the k8s branch of vets-api.)

It seems we may need to just install it from source. Pursuing Chris' PR may be the best option.

## Related

[Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639169773357800)
[Chris' PR](https://github.com/department-of-veterans-affairs/vets-api/pull/8991)

**Comment by thilton-oddball** [comment]
Details from email mentioned in thread: 

Currently, on vets-api, the poppler utils (http://poppler.freedesktop.org) are installed to support the application’s ability to analyze pdf documents.  The current version installed is version:

 

vets-api@93a7ab682114:~/src$ pdfinfo

pdfinfo version 0.71.0

Copyright 2005-2018 The Poppler Developers - http://poppler.freedesktop.org

Copyright 1996-2011 Glyph & Cog, LLC

 

This version is from 2008.

 

If this utility is asked to analyze a pdf that has been generated via docusign this is the result:

 

vets-api@93a7ab682114:~/src$ pdfinfo ./del_me/VA21-22-kostya-signed.pdf

Syntax Error: Gen inside xref table too large (bigger than INT_MAX)

Syntax Error: Couldn't find trailer dictionary

Syntax Error: Gen inside xref table too large (bigger than INT_MAX)

Syntax Error: Couldn't find trailer dictionary

Syntax Error: Couldn't read xref table

 

 

If we upgrade to a version from 2021:

vets-api@93a7ab682114:~/src$ /srv/vets-api/src/util/bin/pdfinfo -v

pdfinfo version 21.11.0

Copyright 2005-2021 The Poppler Developers - http://poppler.freedesktop.org

Copyright 1996-2011 Glyph & Cog, LLC

 

This is our result:

 

vets-api@93a7ab682114:~/src$ /srv/vets-api/src/util/bin/pdfinfo ./del_me/VA21-22-kostya-signed.pdf

Title:

Subject:

Keywords:

Author:

Creator:

Producer:        PDFKit.NET 21.3.101.25665 DMV6

CreationDate:    Mon Oct 18 16:07:27 2021 UTC

ModDate:         Mon Oct 18 16:07:27 2021 UTC

Custom Metadata: no

Metadata Stream: yes

Tagged:          no

UserProperties:  no

Suspects:        no

Form:            none

JavaScript:      no

Pages:           1

Encrypted:       no

Page size:       612 x 792 pts (letter)

Page rot:        0

File size:       66622 bytes

Optimized:       no

PDF version:     1.6

 

 

This command line utility is wrapped by a file called pdf_info.rb.

 

Usages:

app/models/evss_claim_document.rb on line 109:
def unencrypted_pdf?
  return unless file_name.match?(/\.pdf$/i) && file_obj

  metadata = PdfInfo::Metadata.read(file_obj.tempfile)
  errors.add(:base, I18n.t('errors.messages.uploads.encrypted')) if metadata.encrypted?

 

app/workers/central_mail/submit_saved_claim_job.rb on line 83
def get_hash_and_pages(file_path)
  {
    hash: Digest::SHA256.file(file_path).hexdigest,
    pages: PdfInfo::Metadata.read(file_path).pages
  }
end
 
3.     app/uploaders/validate_pdf.rb on line 13
def validate(temp_file)
  metadata = PdfInfo::Metadata.read(temp_file)
  if metadata.encrypted?
    raise Common::Exceptions::UnprocessableEntity.new(detail: I18n.t('errors.messages.uploads.pdf.locked'),
                                                      source: 'ValidatePdf')
  end
 
4.    lib/shrine/plugins/validate_unlocked_pdf.rb on line 13
metadata = PdfInfo::Metadata.read(cached_path)
errors << I18n.t('errors.messages.uploads.pdf.locked') if metadata.encrypted?
 
5. modules/appeals_api/workers/higher_level_review_pdf_submit_job.rb on line 59 (this is for appeals)
'numberPages' => PdfInfo::Metadata.read(pdf_path).pages,
 
6.     lib/appeals_api/hlr_submit_wrapper.rb (appeals api)  line 19
 'numberPages' => PdfInfo::Metadata.read(pdf_path).pages,
 
7.    claims_api/document_validations.rb (claims api) line 22
  def valid_page_size?(file)
   size_in_inches = PdfInfo::Metadata.read(file.path).page_size_inches

**Comment by thilton-oddball** [comment]
Issue is with the version of ubuntu that is being used in docker. It comes packaged with an old version of poppler-utils. We will need to use a new release of ubuntu that comes packaged with a new version of poppler-utils.

**Comment by npeterson54** [comment]
This needs to be fixed in both the master and K8's branches
