### ISSUE TITLE
ch33 issue

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#34337]
https://dsva.slack.com/archives/CBU0KDSB1/p1639499732000200

Channel dedicated to this here: https://dsva.slack.com/archives/C02Q9FL124F

**Comment by ericboehs** [comment]
Confirming this can be closed in thread.

**Comment by thilton-oddball** [comment]
This has been taken over by another team and appears to essentially be resolved. The root issue was that Loki can’t handle the ingestion of info level logging. Logging has been reduced from info to warn and that seems to have resolved the issue.
