### ISSUE TITLE
Issue with Domo BQ datasets scheduling

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#34345]
We have a systemic issue in Domo where the `hasGoogleAnalyticsDataLoaded` is not functioning correctly.   It is supposed to RAISE an exception if the previous day's GA table is not loaded.  It does that, but Domo suppress the exception and marks the update as successful (though with 0 added rows).  

Here's an example where you can see "successful" updates with 0 rows....

https://va-gov.domo.com/datasources/7939ffc8-d32d-4787-981b-92c9b5c92477/details/history

The earlier in the morning the update is scheduled, the more missing days we have.  Though all datasets could potentially be affected.

### FIX

Currently we have this general structure to our queries...

```sql
BEGIN

     CALL `.....stored_procedures.hasGoogleAnalyticsDataLoaded`();

     <THE QUERY>;

EXCEPTION WHEN ERROR THEN
    RETURN;
END;
```

...which needs to be changed to...

```sql
CALL `.....stored_procedures.hasGoogleAnalyticsDataLoaded`();

<THE QUERY>;
```

Be sure to keep the trailing semi-colons in the CALL and your query.

Example of an updated dataset...
https://va-gov.domo.com/datasources/24ff29ec-4329-45a4-8b0f-06dfde513817/details/settings

I would suggest reviewing each BQ dataset owned by Platform Analytics & Insights...

- [x] Is it not missing any days? Still reformat as above and ensure schedule is correct (> 8am ET, try again every 60 min 10 times).
- [x] If it is missing days, reformat as above and backfill data back to the earliest date in the current dataset. Then adjusting back to previous APPEND schedule.

**Comment by obrienjulie** [comment]
The BQ datasets have been updated to reflect the new syntax and backfilled where needed.
