### ISSUE TITLE
Access for Emily Wilson 

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#34346]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Emily Wilson

### Your Email

emily.wilson@adhocteam.us

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9k6takXQ7xEYG1euBpWykKC3FYgrM837B7RZubTbpc4rJ94sKJZ/X/J25CSfXaEP8awuRfVYug64p6q7yyQCjSt8GxGPYCxyyYZVKNyIBkJpc/C9vCRfuUs3xmuN0j/ix14KDfOuBhNj1RpHjedpegsK8q6xCfOBXZ33wEh4D1BO8ROIkfEVtzbkZN4KEATce2zBXcClxj5QqZ622AgdAriR6sh9uBC+L1lglLvOAMJJ1Tt0QNDBEh0wGf5CGGKDl9WU89TQRmtLShotxzk1rQOUlDKjmvnIimBagmTx8Qkt/9ia4gv+TMCw9uslPpxiM6Rf3e+D0UTkIJFWJR5RdsT3WPIRpNDl45QqLOuErpbNpklu/U859e4nc511aCPT4PXyMaWhYzD3IdJMiVFVedrZFurh7AXtq9giDaVvDY8NceQxVpRjO/tHbToxVbMgfYEXiIYHUxhqTFRtcM21T8IYhB1oyP72tXolcbe3TG05xMeoU3KBOEltmcTQ7z/8= emilywilson@EmilyWilsonMBP.mord.haus

**Comment by rbeckwith-oddball** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/10463
