### ISSUE TITLE
GIDS issue

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#34344]
[Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639763626214000)

**Comment by thilton-oddball** [comment]
Had to update Rails and Brakeman because of the CVE issues. Doesn't look like they have kept up with gem updates in that repo so it is requiring a lot of additional updates that are causing problems.

**Comment by thilton-oddball** [comment]
Has updated Rails and merged.
