### ISSUE TITLE
VN1990 issueVN1990 issue

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#34343]
[Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639762416212300)

**Comment by thilton-oddball** [comment]
- Duplicate VN1990s are being sent. 

- Already have a VN1990 on file for each ‘applicant’, and the first VN1990 on each case was received during either August 2017 or September 2017.

- Both the old and new VN1990 have different confirmation numbers on them.

**Comment by thilton-oddball** [comment]
Current thinking is that the kms jobs may be causing the issue with the updating of decryption_verified_at date. Holding off on running the jobs until we can determine if this is indeed the case.

**Comment by thilton-oddball** [comment]
This was finally resolved. We did determine that the kms job was what caused the issue, were able to make the needed corrections to get the spool files to print without the duplicates. Details have been logged [here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34448)
