### ISSUE TITLE
SOCKS issue

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#34341]
[Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639678340141400)

**Comment by thilton-oddball** [comment]
Getting timeout error when running vtk socks setup. User doesn't have file permissions to edit .ssh/config.

**Comment by thilton-oddball** [comment]
User said to close ticket for now. She will open a new ticket if she still experiences issues once she has proper rights on her machine.
