### ISSUE TITLE
Iterate unauth homepage 

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#34359]
Acceptance criteria:
- [ ] unauth mobile and web homepage evolved to reflect changes to the auth designs
- [ ] unauth mobile and web homepage evolved based on feedback from design intent

**Comment by JordanSWhite** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/34359?planning-poker) with ZenHub @JaredMostudio @jsing0 @nprimak

**Comment by jsing0** [comment]
[The Sprint 8 Mural ](https://app.mural.co/invitation/mural/innovationboards1199/1640715601448?sender=u363f843c6d3533347d471444&key=eb3b6ed3-9e88-49d7-b140-2bcd232a7a1b)
[The Sprint 8 Sketch files](https://sketch.com/s/7ddd2962-35f2-4f08-8c84-fe35ebb3476a)
both of these include unauthenticated screens for desktop and mobile.
