### ISSUE TITLE
Create example

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#3435]

**Comment by peterhill-oddball** [comment]
Dan and JP are working on understanding the code associated with Search box on the landing page of va.gov.  A test project for the search box might be beneficial as I can poke Dan and JP while they work on it.

**Comment by peterhill-oddball** [comment]
Created a small test project based on Search functionality here --
https://dsvavsp.testrail.io/index.php?/projects/overview/2
