### ISSUE TITLE
[BE] Auth Profile: Catch up on latency findings

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34365]
## Background
There have been ongoing latency issues when calling the BGS service for edu direct deposit info.  This latency was impacting our ability to load the VA.gov profile in a timeline manner. 

Most of the pertinent technical findings are documented in:
- The [#bgs-direct-deposit-payment-info-debugging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34248#Hypotheses) Slack channel.  
- A [GitHub epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34248) and the [CH3 related issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34317).   Conversation centered around logging impact is found [here](https://dsva.slack.com/archives/C02Q9FL124F/p1639786132335600). 
- [A Slack thread](https://dsva.slack.com/archives/C02Q9FL124F/p1639786132335600) related to a second call that Trevor Bosaw discovered and modified to reduce stack trace errors.

## Tasks
- [x] Catch up on what has transpired by reviewing the Slack and GitHub links provided above.

## Acceptance Criteria
- [x] Have a good understanding of what transpired between Dec 1-21, including different hypotheses, changes made in code and logging.

**Comment by lihanli** [comment]
i was able to catch up on the causes of the latency issue by attending the meeting today
