### ISSUE TITLE
[BE] Auth Profile: Determine if logging should change, make changes if so

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34369]
## Background
There have been ongoing latency issues when calling the BGS service for edu direct deposit info.  This latency was impacting our ability to load the VA.gov profile in a timeline manner. 

After reviewing the information referenced in #34365, determine what, if anything can be done with logging on the BE to prevent additional latency.  If there are changes that can positively impact performance, make those changes.

## Tasks

- [ ] Determine if we need to make any changes to our logging to prevent additional latency.
- [ ] If changes can be made, make those changes.

## Acceptance Criteria

**Comment by bosawt** [comment]
The reason there's a stack trace with most of the ch33 calls:
When we make a call to get_ch33_dd_eft_info from the BGS service, we first make a call to generally get user's bank account information, find_ch33_dd_eft. We then make a second call for find_bank_name_by_routng_trnsit_nbr. The problem, we assume that the routing number is nil on the original call if the user has no bank account info. In fact, the routing number appears to be set to 0 with no bank info set up, so right now we consider that valid and pass it along to the second call

**Comment by bosawt** [comment]
The solution for now will be to check if the initial call returns with nil or '0', in either case we will prevent the second call from happening, as it is unnecessary

**Comment by lihanli** [comment]
we're not doing an excessive amount of logging with the direct deposit api, the `get_ch33_dd_eft_info` is normally logging 4 lines of data with every call
```
D, [2021-12-27T16:27:52.349820 #30236] DEBUG -- : HTTPI /peer GET request to internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com (net_http)
D, [2021-12-27T16:27:52.996866 #30236] DEBUG -- : HTTPI /peer POST request to internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com (net_http)
D, [2021-12-27T16:27:53.578116 #30236] DEBUG -- : HTTPI /peer GET request to internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com (net_http)
D, [2021-12-27T16:27:54.128512 #30236] DEBUG -- : HTTPI /peer POST request to internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com (net_http)
```

i'm seeing that there is an option in the savon library to turn off logging, we could do that for now, but this level of logging should not be causing any problems unless the logging library or api is already broken

**Comment by MarciMcGuireGCIO** [comment]
@lihanli is it set to Debug in Production?  If so, is there an option to drop it down to Warn or Error?

**Comment by lihanli** [comment]
right now the log level for all of vets-api is set to warn so these messages are not being logged. i don't think any direct deposit specific logging needs to be changed though since when it's turned on there are only 4 lines of logs written for each call.

**Comment by MarciMcGuireGCIO** [comment]
Ok; thanks!
