### ISSUE TITLE
Changed apps only builds in PRs: Release Plan

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#34398]
## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: Begin December 13, 2021 (with release of changed app only builds to prod)
- Desired number of users: 1 VFS team
- The group(s) from which you'll recruit test users: VFS
- How you'll recruit test users: Identify good candidate among VFS teams (must regularly submit PRs on app, app must not have cross-app dependencies, we must have reliable method communication with the VFS team)
- How you'll give test users access to the product: Add VAOS to allowlist
- What "Success" criteria will you look at before launch?
   - Production build time for PRs from apps not on the allowlist 
- How you'll measure your "Success" criteria?
   - [TO COME — clarify with Tim/Theo]

### Results:

- Number of users: 1 VFS team
- Results per your "Success" criteria:
- Number of bugs identified / fixed: x/x
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: lorem ipsum  

### Planning:

- Desired launch date: January 2021
- Post-launch KPI 1: Production build times in PRs
- Post-launch KPI 2: Number of apps (technically) eligible for allowlist

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by theodur** [comment]
I created a [dashboard](https://app.datadoghq.com/dashboard/efx-b6p-6ds/vets-website-builds?from_ts=1641985644140&to_ts=1642000044140&live=true) in Datadog to help us keep track of production build times in PRs.

We can specify a specific date (launch date) to start tracking build times from in one of the widgets, and compare that to the average build times before launch.

**Comment by theodur** [comment]
I created a [spreadsheet](https://docs.google.com/spreadsheets/d/1oKsyPwsTjPD2nelVwP6bEOmi_wmEoOcYCoSnzz6PJE4/edit#gid=0) for keeping track of the number of eligible apps for the allowlist overtime. Eligible apps are pretty much apps that are isolated in the `vets-website` repo.

**Comment by theodur** [comment]
Following the go/no go meeting, we can move forward with adding other teams to the allowlist for beta testing. 
Notes from the meeting: https://vfs.atlassian.net/wiki/spaces/FTT/pages/2061107403/Go+no+go+January+2022

**Comment by theodur** [comment]
I [confirmed](https://dsva.slack.com/archives/C5HP4GN3F/p1642790615024400?thread_ts=1637176642.141900&cid=C5HP4GN3F) with the Check In team that we can add them to the allowlist. They will be the first grouped app to be placed on the allowlist.

PR for adding them on the allowlist: https://github.com/department-of-veterans-affairs/vets-website/pull/19988

**Comment by theodur** [comment]
The PR for adding the `check-in` apps to the allowlist has been merged. I followed up with the Mark from the team, and will get feedback in about 1-2 weeks on changed app builds

[Slack thread](https://dsva.slack.com/archives/C5HP4GN3F/p1643045653028800?thread_ts=1637176642.141900&cid=C5HP4GN3F)

**Comment by theodur** [comment]
After [confirming](https://dsva.slack.com/archives/CPE4AJ6Q0/p1643221221061869) with the VSA Debt team that they would like to be beta testers, I [added](https://github.com/department-of-veterans-affairs/vets-website/pull/20049) the medical copays app to the allowlist

**Comment by theodur** [comment]
I [confirmed](https://dsva.slack.com/archives/C02825JJJRW/p1643734706036709) with the Education Benefits team that they're okay with adding Education Inbox and Enrollment Verification to the allowlist. I opened a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20112) for adding them

**Comment by theodur** [comment]
I opened a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20152) for adding the login app to the allowlist after confirming with the identity team

**Comment by theodur** [comment]
## Types of apps for user acceptance testing
We can group apps that we're using for testing into different categories that represent most apps in the repository.

### Form apps
Apps that are powered by the Forms System. This will probably cover most apps in the `vets-website`.

### Non form apps
Apps that don't use the Forms System. These are apps that do various other tasks that don't involve submitting a form.

### New apps
Apps that were recently added to the `vets-website` repo. We want to monitor how new apps that may scale and change do in changed app builds

### Grouped apps
Apps that are grouped with other apps in a subdirectory in [src/applications](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications).

### General apps
Apps that serve a more general purpose, such as logging in, authentication, etc.

The apps added to the allowlist over the past few weeks represent one of the categories above. Here is a list of apps being used for testing

| Application | Type | Date added to allowlist |
| --- | ----------- | ------ |
| check-in | Grouped app | January 24 |
| education-inbox | New app | February 4 |
| enrollment-verification | New app | February 4 |
| login-page | General app | February 7 |
| medical-copays | Non form app | January 27 |
| vaos | Form app | November 10 |

**Comment by theodur** [comment]
## Feedback from teams with apps on the allowlist
- check-in ([slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1645119403148139))

**Comment by theodur** [comment]
Changed apps only builds in PRs has been released ✅
- [x] Documentation has been published: https://depo-platform-documentation.scrollhelp.site/developer-docs/Single%2Fgrouped-application-builds.2031484979.html
- [x] Announcement has been sent to [#vfs-frontend](https://dsva.slack.com/archives/C5HP4GN3F/p1646764238256139)
- [x] All currently eligible apps have been added to the allowlist ([PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20431)).

We will continue to add apps as needed when teams request so
