### ISSUE TITLE
Adding Dalton Atkins to DSVA Slack

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34399]
# Description

**new user requests**: 

- Please add Dalton Atkins [_dalton.atkins@accenturefederal.com_] as a **full member** in DSVA Slack.

Dalton is a new member on the AFS-Education team who will be replacing Gina Ronat as the Product Analyst when she retires at the end of this year. 

_We aim to complete slack requests within 24hrs._

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
