### ISSUE TITLE
Adding Type of Care to the Appointment Details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#34392]
## Description

Currently, the appointment details page does not show the type of care to a veteran. 

When the user books an appointment or views their booked VA appointment, then the veteran will see the type of care on the appointment details page. Update the page content on the appointment details page with the clinic location information.

**A few examples of the current Appointment Details Page:** 
<img width="1034" alt="Screen Shot 2021-12-20 at 3 06 40 PM" src="https://user-images.githubusercontent.com/90797205/146826464-f057c37b-75ad-4cd6-a5ec-221f48716fee.png">

---

## Acceptance Criteria

Given the user is in the new appointment workflow, 
When the user books the appointment, 
Then user will be able to see the type of care on the confirmation details page, 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/kav7j5l), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/AxE3j11), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/kav7j5l)

Given the user is in the VAOS homepage, 
When the user views their booked VA appointment,  
Then user will be able to see the type of care on the appointment details page, 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/jgJd8gm), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/7y8zmP2), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/8ybZDjR) 

Given the user is in the VAOS homepage, 
When the user views their canceled VA appointment,  
Then user will be able to see the type of care on the appointment details page, 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/jgJd8gm), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/7y8zmP2), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/8ybZDjR) 

Given the user is in the VAOS homepage, 
When the user views their past VA appointment,  
Then user will be able to see the type of care on the appointment details page, 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md)
And page design matches the design spec [desktop](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/jgJd8gm), [mobile](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/7y8zmP2), and [tablet](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7/a/8ybZDjR) 

### Design Assets
[Sketch Design File](https://www.sketch.com/s/dad7ec72-ffc6-4fd8-b072-674a314be2d7)
Page structure guide [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/content) reference
 
## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
Hi @ptouchton - would you please update the spacing between the Type of Care and the VA location. There is a lot of white space. It should be the same amount of space  between the section ending in TTY and the section that starts with add calendar.

 ![Screen Shot 2022-01-26 at 4.03.06 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/1e11d647-681f-4e2e-9536-c79dea9b3b50)

**Comment by ptouchton** [comment]
@ldelacosta I'm not sure what is going on at the moment. I will keep researching. This is the view we were working with during the PR review and we were not seeing that large of a gap. 

![image](https://user-images.githubusercontent.com/3951775/151394935-57e4d58a-97a7-4275-b9e5-c59f28e0d449.png)
