### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by alsleaders** [department-of-veterans-affairs/va.gov-team#34393]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: alsleaders
- Reason access is required: 
I would like sidekiq access to be able to investigate errors in form 526 submission

**Comment by ericboehs** [comment]
Added.
