### ISSUE TITLE
SUPPORT: BAH A (VET TECH)

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#344]

**Comment by joanneesteban** [comment]
@rroueche Is this in support of today's launch?

**Comment by andreahewitt-odd** [comment]
@rroueche @joanneesteban Could we close this ticket or is there work for Product Support to do?

**Comment by joanneesteban** [comment]
@rroueche @joanneesteban I'm not sure what the context is for this ticket - it can be closed on the Analytics & Insights end.

**Comment by rroueche** [comment]
This was an experiment for tracking VFS Teams actively on VSP, we're not using this method anymore. Closing.
