### ISSUE TITLE
[Tier 3] Claim Submission Issue - SF 06220271

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34404]
## Issue
_Veteran is having issues submitting claim.  Please review details from SF case notes below and information provided in encrypted email that was sent._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Salesforce Case Notes:
Veteran verified PII. Calling re: She is using Chrome to sign in to her VA.gov with her PIV Card DS Logon. She is getting an error when submitting her compensation claim. Saying that "We're sorry something went wrong on our end. Please try back again with in 24 hours." This error message has been happening for a week now. I had her try using just user name and password and she had to re-register to see if that changes anything. She gets the same error message. Reference number is F0F91350D81F316787565D8C. Escalated to Tier 2.

**Comment by Kimberley2019** [comment]
@alsleaders encrypted email has been sent.

From: Daniels, Kimberley N. (Oddball, Inc.) 
Sent: Tuesday, December 21, 2021 9:35 AM
To: Leaders, Amanda L. (Government CIO) <Amanda.Leaders@va.gov>
Cc: Henry, Veronica (GovernmentCIO) <Veronica.Henry@va.gov>
Subject: FW: [EXTERNAL] Re: Disability Claim application issue

Good Morning  Amanda,

I wanted to pass this along to you since it contains screenshots that contain PII.  The ZH ticket number is below.

[Tier 3] Claim Submission Issue - SF 06220271 · department-of-veterans-affairs/va.gov-team (zenhub.com)


Kind Regards,

Kimberley

**Comment by alsleaders** [comment]
I'm blocked on this until I can research In Progress Id 3202623

**Comment by alsleaders** [comment]
Hi @Kimberley2019 
I sent you an email with an update: I know the ticket said "I cannot submit" but I cannot replicate that error and as far as I can tell from the user's InProgress data, there are no errors in the data and they should be able to submit.

**Comment by Kimberley2019** [comment]
Reached out to customer to attempt task again.

BCC @alsleaders @vhenry07 on email in order not to cause any bottlenecks if customer responds with information they are able to use in order to resolve issue.

**Comment by Kimberley2019** [comment]
sent encrypted email with screenshots for review.

**Comment by Kimberley2019** [comment]
Case 'In Progress'

**Comment by Kimberley2019** [comment]
Assigning new members/teams for historical purposes.
After review, case may be closed by either team/team members.

**Comment by Kimberley2019** [comment]
7/8/22– New Tier 3 benefits team review.  Modified follow up template sent.  Will reopen if/when user responds with needed information for resolution of issue.
