### ISSUE TITLE
Access for Lindsey Hattamer and Travis Hilton

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#34405]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Lindsey Hattamer

### Your Email

Lindsey.Hattamer@oddball.io
Travis.Hilton@oddball.io

### Name of Your Team

VSP Backend Tools

### Service(s) You Want Access To

AWS

### Desired AWS Services

Request access to RDS snapshots for vets-api.

When a SavedClaim is created, a corresponding EducationBenefitsClaim is created. See [validation here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/education_benefits.rb#L8). The daily spool file job processes all EducationBenefitsClaim records with a processed_at date of nil.

DAILY, a cron job runs to remove old EducationBenefitClaim records that are more than 2 months old.

Theory:
What we think happened is that "old" SavedClaim records still existed in the database (that didn't have a corresponding EducationBenefitClaim or it was cleaned up by the deletion job). For the SavedClaim records without a EducationBenefitClaim, [this line](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/education_benefits.rb#L8) would run when the verified_decryptable_at date was saved, creating an education_benefits_claim that would be marked for processing again.

I think to test this, we could have Ops pull up a db snapshot (maybe sometime before last Friday?) We could get a list of SavedClaims that DON'T have a corresponding EducationBenefitClaim Then, we could compare to the records in the prod db now that do have a EducationBenefitClaim

^^ If we find the difference, we can find the records that were reprocessed

**Comment by td-usds** [comment]
Access approved *until* end-of-day 2021-DEC-21. Please file a ticket to revert this access at end-of-day and link to it in here.

**Comment by mydesignrocks** [comment]
done and closing
