### ISSUE TITLE
[FE] Auth Profile: Require certain fields based on initial API response data

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#34406]
## Issue Description
As a front end developer, I want to build the logic to detect data that has come in from the API response and require certain fields to have data based on that response.

## Front end tasks
- [x] If the MPI-derived value for Preferred Name, Pronouns, Gender Identity or Sexual Orientation are NULL/blank, then the field shall not be flagged as required. If the MPI-derived value is other than NULL/blank OR the user enters a value and updates, the field shall be flagged as required and cannot be changed to NULL/blank through this UI.

Please use the below files for reference

[Edit State Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw)
[UXPin Prototype](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i)

## Acceptance Criteria
- [x] Preferred name is required is initial data comes back as not null from the api response
- [x] Pronouns is required is initial data comes back as not null from the api response
- [x] Gender Identity is required is initial data comes back as not null from the api response
- [x] Sexual Orientation is required is initial data comes back as not null from the api response
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
Will likely need to move to Sprint 64

**Comment by adamwhitlock1** [comment]
This issue has actually been addressed in this PR

https://github.com/department-of-veterans-affairs/vets-website/pull/20793

> Add Required to the edit states of both the fields. This turned out to be a challenge because the fields should not be required if there is no initial data, but if data exists from the api then the field should be required. Essentially we cannot delete the field's data once it has been set, and can only update it to different data.

This issue should be good to close at this point.
