### ISSUE TITLE
VFS developer documentation - changed app only builds in PRs

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#34401]
## Details 
As a VFS developer, I need to understand how builds in PRs work if I am on (or not on) the "changed app only" allowlist.

On 12/13, we released changed apps only builds in PRs to production. Only VAOS is on the allowlist currently, but we plan to release this functionality to additional teams in 2022. We need developer documentation for this. 

### Qs to answer in documentation 
- [x] What is this feature? 
- [x] How does it work? 
- [x] What is the allowlist, and how do teams get added to it? 

Documentation should be added to Platform Website wherever applicable

**Comment by theodur** [comment]
Draft documentation for changed app builds: https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/2031484979?draftShareId=7f53e7cf-225a-45ab-a379-b2a16cb468a7

**Comment by theodur** [comment]
I'm holding off on publishing the documentation since we aren't going to release to all teams just yet. More info [here](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2061107403/Go+no+go+January+2022).

**Comment by theodur** [comment]
In relation, the cross app import documentation has been [published](https://depo-platform-documentation.scrollhelp.site/developer-docs/Cross-app-imports.2033778881.html) though, since we don't need to wait until release to start encouraging app isolation.

**Comment by theodur** [comment]
Since we recently added [Slack notification functionality](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36598) for changed app builds, I updated the draft documentation to include information on how this option can be used.

**Comment by theodur** [comment]
The documentation is still on hold to be published, until we get the approval to release changed app builds in PRs.

**Comment by theodur** [comment]
Documentation has been published: https://depo-platform-documentation.scrollhelp.site/developer-docs/Single%2Fgrouped-application-builds.2031484979.html ✅
