### ISSUE TITLE
Usability Testing w/ VAOS

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#34402]
Per release plan for changed apps only builds in PRs, VAOS is the first VFS team on the allowlist. 

Host feedback session with VAOS ([notes](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2026536988/Feedback+session+w+VAOS))

Document usability here issues and address.

Release plan ticket #34398
Changed app only builds in PRs initiative ticket #29132

**Comment by theodur** [comment]
Closing this ticket since we've connected with VAOS and confirmed there were no issues with changed app builds
