### ISSUE TITLE
Hand off repo migration process to content&IA

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#3440]
Now that content & IA has an engineer on their team, we need to spend time handing off the repo migration process to him and explaining the scripts we're using. 

AC:
- [ ] Meet with Bill Fienberg to go over repo migration process

**Comment by johnpaulashenfelter** [comment]
Walked bill through the script, improving it and adding docs. Will help him run a few real instances next week.

**Comment by johnpaulashenfelter** [comment]
@andreahewitt-odd @meganhkelley can we call this done?
