### ISSUE TITLE
Revoke Temporary Access for Lindsey Hattamer and Travis Hilton

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#34410]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Travis Hilton

### Your Email

Lindsey.Hattamer@oddball.io Travis.Hilton@oddball.io

### Name of Your Team

VSP Backend Tools

### Service(s) You Want Access To

AWS

### Desired AWS Services

We were granted [temporary access to RDS snapshots for vets-api](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34405). This ticket serves to revoke that access at EOD 2021-12-21.

**Comment by mydesignrocks** [comment]
temp access revoked. If needed as a permanent route, please go through the standard access request route.
