### ISSUE TITLE
Update existing user guides

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#34411]
Make initial updates, looking at: 

- clarity

- consistency

- grammar

**Comment by lindsay-insco** [comment]
@vlivshin please break up into each user guides you're updating and include dates you intend to have them completed in brackets at the beginning (example: [01/05/22] Pharmacy User Guide Update)

**Comment by lindsay-insco** [comment]
Moved to individual user guide tickets
