### ISSUE TITLE
Access for Antony Zimzores

### ISSUE THREAD

**Issue by azimzores** [department-of-veterans-affairs/va.gov-team#34420]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy
COR: Cecilia Lee

### Your Name

antony zimzores

### Your Email

antony.zimzores@libertyits.com

### Name of Your Team

Leeoroy Jenkles

### Service(s) You Want Access To

AWS

### Desired AWS Services

Access to EKS, ECS, S2, EC2 and other standard services for the Leeroy Jenkles team.

**Comment by mydesignrocks** [comment]
@mchelen-gov please review for aws access.

**Comment by jsgarmon** [comment]
new approval group: @department-of-veterans-affairs/operations-aws-approvers

@azimzores  : they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that your COR has added your transmittal date to the Sharepoint doc?

**Comment by azimzores** [comment]
> new approval group: @department-of-veterans-affairs/operations-aws-approvers
> 
> @azimzores : they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that your COR has added your transmittal date to the Sharepoint doc?

its still in process

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by azimzores** [comment]
@jsgarmon jsgarmon EQIP is completed and PIV has been issued @golavarr-va

**Comment by td-usds** [comment]
@azimzores can you have your VOR reach out to me and share your eQIP transmittal date? I have to hear it from them.
Also, what is the Leroy Jenkles team?

**Comment by td-usds** [comment]
I did reach out to the VOR earlier today and an extra nudge from your end would be beneficial as well

**Comment by azimzores** [comment]
@td-usds @mramirez-va Thomas are you referring to the COR, Cecilia Lee? I am on the Leroy Jenkles lighthouse team. I would need similar AWS Service access to Edison Velez

**Comment by azimzores** [comment]
@td-usds What is your email that I can have the VOR ping you?

**Comment by golavarr-va** [comment]
@td-usds The transmittal date was 12/20/2021. Antony Zimzores is a member of DVP/Lighthouse. Leeroy Jenkles is the names of the DevOps team in Lighthouse.

**Comment by td-usds** [comment]
VOR confirmed eQIP transmittal; Approved

**Comment by jsgarmon** [comment]
Access granted. Sent user first-time log in information via Slack DM. Feel free to contact me in slack on #vfs-platform-support if you have any trouble or need additional permissions.
