### ISSUE TITLE
Document static pages app. Determine deprecation path

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#3442]
## Background

- Static pages app has several non standard apps / js in it. It also relies on lazy loading that is not completely implemented and is error prone
- In general, anything on the site should be treated as an app and the markup on the page should load the correct application. The static pages app lazy loads based on the url which couples url management with app loading 
- report unit test coverage on widgets?

## tasks 

- maybe establish guidelines for adding functionality to widgets for the short term
- evaluate why static pages app takes it current approach instead of the approach used by full SPA

**Comment by meganhkelley** [comment]
Relevant conversation: https://dsva.slack.com/archives/CBU0KDSB1/p1628782837381900

tl/dr — VFS team member feature request to move CSS for static pages to content-build repo

**Comment by meganhkelley** [comment]
Static pages app is being addressed in #30572
