### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by AdamFreemer** [department-of-veterans-affairs/va.gov-team#34422]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: AdamFreemer
- Reason access is required: Monitoring of active jobs and debugging

**Comment by ericboehs** [comment]
Already added when I checked today.
