### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#34421]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: af-manish
- Reason access is required:  To be able to review sidekiq jobs

**Comment by ericboehs** [comment]
This is already added when I checked today.
