### ISSUE TITLE
[FE] My VA: Add screen reader headings to each link list within My VA Dashboard

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34432]
## Background

After talking with Josh Kim regarding accessibility on the new Payment Information section on My VA, he mentioned that we should consider having Screen Reader headings (SR Only, Screen Reader Only) for each link list within each section (Claims & Appeals, Health Care, and Payment Information).  Currently, they may read as links that pertain to the card within the section.

See Mid-point Review ticket #34621 for Onsite notifications, **[Josh's feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621#issuecomment-1016708550)**
      
EXAMPLE:  
- The links within the Health Care section should be identified as part of the Health Care action items, and not action items related to the upcoming appointment shown.  
- As they read currently, they seem like child-links for managing the appointment, not necessarily for the broader Health Care management.

![Screenshot of mockup, highlighting the link lists for each section](https://user-images.githubusercontent.com/92328831/146986681-f50e308c-1091-49e4-a026-dcaa8e065281.png)

- sr-only (screen reader only) headings. Without these headings, screen reader user may interpret these actions as belonging to "Next appointment" instead

![Screen Shot of Health care section and suggestion of sr-only heading](https://user-images.githubusercontent.com/14154792/150174047-fe1e16ed-c357-42db-9d8f-b9b2991515a1.png)

## Tasks

- [ ] Determine what the headings should be for each link list section(image suggestion above)
     - Discuss with Liz and/or Heather if you have any concerns about the heading verbiage
     - The verbiage should be consistent for all 3 sections
- [ ] Add the sr-only headings to each of the link list sections

## Acceptance Criteria

- Each link list within each of the 3 sections on My VA include Screen Reader headings to ensure the information is clearly identified as belonging to the section as a whole, and not to any one piece of the section.

**Comment by hdjustice** [comment]
@tressaellen @tmitchellgcio  Ticket created and in the backlog for addressing the Link List within each section of My VA - adding screen reader headings to make the site more clearly understood and accessible.

**Comment by hdjustice** [comment]
Ticket was not completed, as this was pulled in as unplanned work to start, and was not completed by the end of the sprint.  This will move on to a future sprint.

**Comment by hdjustice** [comment]
Validated that the sr-only headers are added in the link lists, and is read via screen reader.  Tagging @joshkimux and @Saraharaba8 for a quick run-through to ensure the headers are working as expected.  Would you all mind checking this on My VA?  Users 1 and 41 can be used so you can see the headers for all 3 sections.

![image](https://user-images.githubusercontent.com/92328831/153499839-b426f31c-02fd-48fc-8d8d-00b41cdfa143.png)
![image](https://user-images.githubusercontent.com/92328831/153499960-9af4c2bf-2f76-4de8-a2b2-5859e3f1b8a9.png)
![image](https://user-images.githubusercontent.com/92328831/153505185-0729c997-af38-46a3-8717-8009c1fb708d.png)

**Comment by joshkimux** [comment]
@hdjustice these look to be within `span`s instead of `hx` elements. Would be able to [verify using headingsMap](https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi?hl=en)?

**Comment by hdjustice** [comment]
Thank you @joshkimux , I didn't know about this plug-in and that is really helpful!  So the headings do not show up there, as I am assuming they should.  @tmitchellgcio Can you speak to using the `span` element?
![image](https://user-images.githubusercontent.com/92328831/153610025-da46e7f4-4126-4c45-8f23-3f91cac65858.png)

**Comment by tmitchellgcio** [comment]
Oh yeah those should be header tags. I'm not sure why I did that like that. I apologize. I will fix that.

**Comment by tmitchellgcio** [comment]
Sorry about that. I missed a key screenshot on these. They are now sr-only h3s with Popular actions for {section name} as the text. I apologize for that

**Comment by joshkimux** [comment]
No worries at all @tmitchellgcio , thank you for the quick fix!! 🥳 🎉 
@hdjustice could you take one more pass validating with headingsMap? If the hierarchy is as intended we can close this out 😄

**Comment by hdjustice** [comment]
Thanks @tmitchellgcio for getting this in!  @joshkimux - FYI: Validated that the sr-only headings are listed in the hierarchy expected (after the section's card, if applicable).  I am closing this out.  Thanks all!

![image](https://user-images.githubusercontent.com/92328831/154097839-e31b8cd1-7ccb-4ed4-a947-2e6783d171ff.png)
