### ISSUE TITLE
Tech Debt: Remove and convert number-to-words in react-components

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#34435]
Remove and convert `number-to-words` dependency in `react-components`
File it is being used in `src/components/ProcessList/ProcessList.jsx`
The package it being used to convert integer to word ie: 1 to one
Strategy on how to do that with native JS: https://ourcodeworld.com/articles/read/353/how-to-convert-numbers-to-words-number-spelling-in-javascript

## Parent Issue
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33188

## Acceptance Criteria
[] `number-to-words` dependency is removed
[] File where method is being used has been converted to native JS
[] Tested and confirmed working in all supported browsers: https://depo-platform-documentation.scrollhelp.site/developer-docs/Browser-Support-Policy.1847951366.html

**Comment by bkjohnson** [comment]
This will be taken care of in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/632
