### ISSUE TITLE
[DESIGN/RESEARCH] Methods for contacting VAMCs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34431]
## Issue Description
Previously we added the VA health connect phone number to Facility Locator search results and Contact information on VAMC pages for VISN 8 facilities. This was done as a stop gap measure until a more elegant solution could be determined. 

Several factors make returning to this work a priority
- VA health connect will be rolling out nationally.
- December 2021 Executive order emphasizes use of online tools/chat

Previous research found that secure messaging is a trusted and preferred method of communication, preferred over phone calls, and second only to in-person conversation, for established patient Veterans.

### Problems to be solved
How might we
- elevate options for contacting VAMC
- help Veterans understand which option should be chosen for a given scenario
- simplify the list of options
- discover meaningful labels which support Veteran use of the various methods

### Communication methods
**VA health chat (Discovery effort in #27686)**
   - **_Chat live with a clinician_** for issues such as Medical advice for a minor injury or illness, Medication questions, Lab/imaging test results

**Secure messaging (Discovery effort in #27687)**
- **_async service for non-urgent, non-emergency health-related questions_**, such as providing updates on one's condition, requesting VA referrals, test results, and prescription renewals, managing appointments, asking routine administrative questions
 - Response time ~24 hours

**VA health connect (Discovery effort in #27688)**
   - Clinical contact center
   - **24 hours live by phone** - Regional phone numbers (mapped to health system)
 
**Telehealth**
  - "**_remote visits with health care providers_** - technologies include video conferencing, home telehealth (which lets you send us vital health information, like blood pressure readings, over the phone or internet), and store-and-forward telehealth (which helps you send your health information to experts at VA facilities using secure technology)" _from health service on VAMC pages_
  -  for certain specialties, types of care
  - could be accessed from home, using VA provided device or at VA locations where technology is available
  - [more info - VA.gov page](https://telehealth.va.gov/digital-divide)

### Research findings and recommendations
<details>
<summary> Key findings from audit</summary>

[Link to details for findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/communication-audit-research-findings.md#key-findings---detailed)

- Many labels sound similar and don't clearly indicate their purpose.
- Contact information is fragmented across various pages and sections globally and within health systems.
- Contact methods are often embedded within lengthy pages of dense text.
- Alternatives to phone communication are missing from Contact us pages.
- When and how a sub-labels get implemented is inconsistent across VAMC pages.

</details>

<details>
<summary>Recommendations related to research</summary>

- Communication method labeling and naming should be simplified; audit and test with Veterans for understandability, interpretability.
   - How does label naming support the task a Veteran is trying to accomplish? "Make an appointment" more likely matches a Veteran's mental model when trying to complete a task than does "Telephone care".
- Conduct Veteran research and review analytics of Veteran communication usage.
   - Which contact methods do Veterans use most today? Why?
   - In previous studies, multiple Veterans mention a preference for the "nurse line". For what purpose(s) do they call this number over other numbers? 
   - How do Veterans learn about this number? 
   - How does the information provided on VA.gov match a Veteran's experience outside of the website. Do other mediums offer a different set of contact methods? 
   - How might we cater to first time users while offering shortcuts to existing users?
</details>

### Relevant work

- Epic: VAMC options for Veterans to communicate with the VA #26770
- FE: FL search results #32552 
- [Synthesis for VAMC communication options](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/discovery/communication-audit-research-findings.md) #27689

## Success metrics
- Click through rate for options on Facility Locator and VAMC pages
- Veterans are selecting the appropriate method (calls to abc rather than xyz)
- Increased use of these tools generally
- VAMC or Facility Locator as initiation point for use of tool

## Relevant pages
It may help to review the following areas where contact information is currently displayed
- Location and contact information on facility page, such as [VA Pittsburgh health care > Locations > Pittsburgh VA Medical Center-University Drive ](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
- Inside service accordions on facility level pages, such as [VA Pittsburgh health care > Locations > Pittsburgh VA Medical Center-University Drive ](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
- Locations section on the main system page (at least for the main locations - usually 1 or 2 per system), such as [Pittsburgh health care](https://www.va.gov/pittsburgh-health-care/)
- Contact us page - available on left nav, such as [VA Pittsburgh health care > Contact us](https://www.va.gov/pittsburgh-health-care/contact-us/) 

## Tasks
- [ ] Determine a method for gathering Veteran feedback on communication methods with the goal of learning which option Veterans would choose in a given scenario, how (name/search terms) they would search for it, where (on the VAMC pages) they would expect to find it, and what information they need to know in order to choose it

## Acceptance Criteria
- [ ] Research plan and conversation guide

**Comment by nicko-amida** [comment]
This research plan/conversation guide is being finished up in #38150 !

**Comment by mmiddaugh** [comment]
[Research plan and convo guide](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html)
