### ISSUE TITLE
Tech Debt: Remove and convert react-scroll dependency

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#34437]
`react-scroll` is used only in CollapsiblePanel.jsx
* It is used to do an animated scroll to the top of the panel when the panel is clicked
* There is native JS to use to do smooth scrolling: https://css-tricks.com/snippets/jquery/smooth-scrolling/
* However IE11 will need a polyfill to work properly or an if/else to determine the browser like below:
```
document.addEventListener('DOMContentLoaded', () => {
      //  little hack to detect if the user is on ie 11
      const isIE11 = !!window.MSInputMethodContext && !!document.documentMode;
      // ie 11 does not support smooth scroll, so we will simply scroll
      if (isIE11) {
        window.scrollTo(0, document.querySelector(ref).offsetTop);
      } else {
        window.scroll({
          behavior: 'smooth',
          left: 0,
          // top gets the distance from the top of the page of our target element
          top: document.querySelector(ref).offsetTop,
        });
      }
    });
```

## Parent Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33188

## Acceptance Criteria
[] `react-scroll` has been removed from `react-components` and `core` `package.json` as a dependency
[] ` react-scroll` has been converted to native js for the `CollapsiblePanel` component
[] Tested and confirmed working in all supported browsers: https://depo-platform-documentation.scrollhelp.site/developer-docs/Browser-Support-Policy.1847951366.html

**Comment by bkjohnson** [comment]
`<CollapsiblePanel>` is used a total of 8 times across two apps, so I think we would be better off communicating with those app teams to [get them converted to `<va-accordion>` components](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32872) instead of doing work on deprecated code to use a native JS solution.

![image](https://user-images.githubusercontent.com/2008881/157314364-55ba9317-a7ed-4e9c-b9b6-2ceaa74934c3.png)

**Comment by pdavies88** [comment]
@bkjohnson I would agree. 
@k80bowman are you ok with me rewriting this ticket to focus on helping teams remove CollapisblePanel from vets-website and then removing the CollapisblePanel and its dependencies from the Component Library?

**Comment by k80bowman** [comment]
@pdavies88 we already have a ticket for that #32872

**Comment by pdavies88** [comment]
> @pdavies88 we already have a ticket for that #32872

Then we should probably close this ticket in favor of the other one
