### ISSUE TITLE
Research | On-line Apps | Candidates for Translation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34444]
## Story

Based on the discovery work done in [ticket 344430](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34443), the C+L team would like to see if any of the on-line forms are simple enough to do a translation using an override in the existing Forms Lib.

Check these 2:
- VA Form 21-526EZ: Application for Disability Compensation and Related Compensation Benefits (yes! on-line tool for auth users)
- VA Form 21-0781: Statement in Support of Claim for Service Connection for PTSD (yes! on-line tool)
## Acceptance Criteria

- [x] After analysis is complete, document findings and recommendation(s) in GitHub folder
- [x] Present to the team at weekly stand-up

**Comment by adamwhitlock1** [comment]
Findings:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/Candidates%20for%20Translation.md
