### ISSUE TITLE
[FE] HLR Informal Conference section on Review page

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3444]
## User Story or Problem Statement
As a claimant, I need to review and submit my HLR form so I can ensure all of the information I provided is accurate and submit my form.

## Goal
_Build a user friendly view of information specific to Informal Conference to be reviewed and submitted_

## Tasks
- [ ] Include Informal Conference details on review page

## Acceptance Criteria
Scenario: System user wants to review and submit their HLR form
- GIVEN the HLR review form has been completed by a user_
- WHEN the user reviews their provided form responses_
*and* confirms their responses are accurate
*and* selects to submit their application
- THEN the system submits their HLR form

## Design Info
[GH Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3443)
[InVision Mockup](https://vsateams.invisionapp.com/share/BKUTWR2T457#/393337658_Review_Application_-_Expanded_-_Informal_Conference_-_Representative)

**Comment by rileyorr** [comment]
The Invision mockups can be found here: https://vsateams.invisionapp.com/share/BKUTWR2T457#/393337658_Review_Application_-_Expanded_-_Informal_Conference_-_Representative
(Please note that these screens have not gone through content/design review(s) yet. Will update as those meetings happen)
