### ISSUE TITLE
[Tier 3] Disability claim application - SF 06254773

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34440]
## Issue Description
_Review case notes below and details sent in encrypted email in order to review and resolve issue veteran is experiencing._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Case Notes
Veteran verified PII. Calling re: Stated that the issue has been happening since 10/31/2021. Error Message "We are sorry something went wrong when trying to submit your claim."
He is using a desktop and Google Chrome. I had him clear his cookies and cache history. He is signing into his DS Logon account again. He is continuing the compensation application. Submitting the application with same error message. Escalated to Tier 2.

**Comment by Kimberley2019** [comment]
@alsleaders encrypted email sent.

From: Daniels, Kimberley N. (Oddball, Inc.) 
Sent: Tuesday, December 21, 2021 4:48 PM
To: Leaders, Amanda L. (Government CIO) <Amanda.Leaders@va.gov>
Subject: FW: [EXTERNAL] Re: Application Submission Issue

Good Afternoon Amanda,

I wanted to pass this along to you since it contains screenshots that contain PII.  The ZH ticket number is below.

[Tier 3] Disability claim application - SF 06254773 · department-of-veterans-affairs/va.gov-team (zenhub.com)


Kind Regards,

Kimberley

**Comment by alsleaders** [comment]
I'm blocked on this until I can research In Progress Id 4241853.

**Comment by Kimberley2019** [comment]
@alsleaders @vhenry07 

Please provide a status update, work around for veteran, or an ETA of when this will be reviewed and resolved.

**Comment by vhenry07** [comment]
This is still in our support queue and we'll get to it as soon as we can.

**Comment by Kimberley2019** [comment]
Case 'In Progress'

**Comment by Kimberley2019** [comment]
7/8/22– New Tier 3 benefits team review.  Modified follow up template sent.  Will reopen if/when user responds with needed information for resolution of issue.
