### ISSUE TITLE
Access for Patrick Arthur

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#34450]
### COR Name

Other

### Vendor Onboarding Representative Name

Other

### Your Name

Patrick Jason Arthur

### Your Email

patrick@arthuremail.com

### Name of Your Team

AFS-Education

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2Bxex1rypfm2ci9SVld8q44P6BKJ//ftF9Z6Rrq9b7FCgbvhoVbwT7px3KfCn6LJ0KU6NGBPUtC6FRKY2nszXzKZ1OKpVn5pse4k38jKnucA1erl8zqOnxznun37edSKw0680widQL6Ni8n0R1MPidZqJ0wH8Oj1M2Pktv84tK0bgjNXK4B4ewRqWyRjMxs+QVxVZ1Nk1e+h8r01Y8dgGXojg4XsWVQSWrRZIyXI84YBnYFY0wX2k5c1J3CIfwxh8NfHNZ0w7+iOtESS6C1eLZKSdi5Cq2+mLpxJH6ypNpyk9GjMsi/La5xOJcDrxZ+swnBp53uhAb5P64tfzHSq/laUbAQa7fLWqsLnwzmBuNoYhQHAeOB4ZBNfs5bbxaJqERqqdSvlgY1u/zgUhkUaTi8faTV/whruvVFmdeEGiAvE8nKERea3HyhiKmMXtuqD9b82CluOPJI8ZQ3hrzjp3tEID8e5rEAxmWUJi5tdZb1jg9VUtKqokOj7A5vS96ZM= patrick.arthur@AFSMWFR8MB5TPA3

**Comment by jsgarmon** [comment]
This looks done. @PJart : See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack #vfs-platform-support if you have any trouble.
