### ISSUE TITLE
Backend Onboarding: AWS

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34465]
## Background
When a new member joins VSA, there are a number of different milestones that are needed.  Some need simple knowledge transfer, others require more in-depth assistance to get set up.

## Tasks
- [ ] Once AWS access has been obtained, we want to perform a few different asks in there

## Acceptance Criteria
- [ ] New team mate has a clear understanding of how we (VA.gov) operate in AWS

**Comment by jason-gcio** [comment]
Access, and proxy for local dev should be good to go?

**Comment by alsleaders** [comment]
Yes, Jeremy has gotten me all the access I need to get into EC2 instances and I have tested it successfully.
