### ISSUE TITLE
DISCOVERY | Analytics for Legal Rep Updates

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34464]
## Story

As a PM, I would like to measure whether "Bet A" for improving the legal representative experience is successful.

Domo Dashboard: https://va-gov.domo.com/page/1905395623

## Acceptance Criteria

- [ ] Confirm data source for tracking the success rate of doc uploads (GA event vs Grafana?)
- [ ] Confirm data source for drop off rates for current vs new pages

New Pages (draft):[https://app.zenhub.com/files/133843125/f9482149-8b42-4ca0-b5f9-fa1095e64210/download](https://app.zenhub.com/files/133843125/f9482149-8b42-4ca0-b5f9-fa1095e64210/download)

**Comment by SKasimow** [comment]
Hi @Dene-human - anything else we want to try to track? Also, could you add the current screenshot to the ticket so we have old and new in same place? Thanks!

**Comment by Dene-human** [comment]
Looks good @SKasimow Are we able to track time spent on page?


# Current (old)
![Screen Shot 2021-12-22 at 1 58 05 PM](https://user-images.githubusercontent.com/80857940/147141902-00f319d2-9ca2-44ec-812d-dd8c20ae7596.png)

![Screen Shot 2021-12-22 at 1 57 51 PM](https://user-images.githubusercontent.com/80857940/147141906-ac5348e8-f9e9-40ea-9833-5465bc0d66b8.png)

![success](https://user-images.githubusercontent.com/80857940/147142028-10e2792b-179a-446d-8db9-423ae35996bf.png)

**Comment by SKasimow** [comment]
Per Analytics team, here's what needs to happen to capture analytics when new questions are added to the 10-10 forms:

> If it's using the Design System Component then you'll just need to enable those checkboxes/text areas for tracking by passing in the questions and/or answers along with the event using our [data layer specs](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) If the questions will be on additional URLs and your funnel will be changing, we will need a ticket to update the dashboard.
