### ISSUE TITLE
better approval process on devops repository

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3446]
## Problem Statement

In order to support VFS teams pushing changes to the platform, we need to allow developers from any team to submit PR's which means write permissions to the repo. However, the repo is shared between a few teams for deployment tooling, and does not currently have CODEOWNERS setup. For the short term, we locked down permissions on the repository so that a few groups have to be the ones who merge PR's, but this is not scalable and not creating a collaborative environment. How might we setup the repo to allow others to continue their work, but still ensure that an appropriate VSP-level review has taken place before merging?

## Goal
Setup the repository in such a way that DVP, Appeals, and VSP have their own rules about who needs to review, but also not lock down merges to only those groups to avoid Ops being gatekeepers.

## Acceptance Criteria
- [x] a review from appeals-devops, dvp-infrastructure, or vsp-operations member is required, but teams are free to merge when they are ready

**Comment by ricetj** [comment]
@wyattwalter can you fill in a bit.

**Comment by wyattwalter** [comment]
I think there might be a duplcate ticket, but Jeremy just did this. Assigning and closing.
