### ISSUE TITLE
Access for Zachary Lewis

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#34461]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Zachary Lewis

### Your Email

zlewis@clarityinnovates.com

### Name of Your Team

Platform - SRE

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2tngvUyzZIc3vlyzVuPZu/TneRcGhF7KwseP6g8FYcHYgma9b8LJBOEajbNkL6QQYJKXPKyDS1BJKiTdVJ5CNWIuUmhGlytwek4QHJHJ06FunxEUSWIb69sIwJcbq1+BAqQ0OtirTmBxEo00ERW41vSIqfCYFvVRHisqpiVJS12M+1IAAkECgO4oN6y9sJblfoSGJ0dkaD2ukOOrtB99GcoNHZt4NvVs/2J1AiDkbqDKgJB0X/JMpDOUlJPlS9NcJbBnBstLEy5Z/Ah/E+Qy58TuMOUiHE4K2FzWJpdepxV2Aio3fONywq9c0PR168AES8QEgYbupyozHQSHRNJhiV88AJZI6/MlBrMlRPzYiBmYA9qGkMgCYdnKJk9Cu0H6bsoQdR+epU+ecHZMUXueYGxk04h/FXcT06yk4j2wrUITTLkaPhG07QBlflSjWVmbgZq0J9Yjw10IUIEUGYt4tmBajOSbTHBHzBlM7KQy+14Xh0tOznT/ZRnbxdutmy1c= zachlewis@zlewis01.local

### Desired AWS Services

 I need to access Datadog, Grafana, and Loki”

**Comment by mydesignrocks** [comment]
Hi @zachclarity - you need socks to get to grafana/loki
Can you please generate your ssh keys from your local mac/pc and plug to this request.
For AWS access, we need to wait for your e-quip submittal, if that hasnt been done yet and further approval from our octode contact Mike Chelen.

**Comment by mydesignrocks** [comment]
and for DD, you should receive an email invite to be able to get in.

**Comment by jsgarmon** [comment]
@zachclarity : please follow [these instructions](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) for settings up SOCKS access via VTK. Once you have your SSH public key, update this ticket (under Public SSH Key) with it, and we can get you added.

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
