### ISSUE TITLE
Redirect Request - GI Bill Comparison Tool URL Change

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#34480]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: 

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/gi-bill-comparison-tool | www.va.gov/education/gi-bill-comparison-tool
**update existing redirect** <br> www.vets.gov/gi-bill-comparison-tool | www.va.gov/education/gi-bill-comparison-tool
**update existing redirect** <br> www.benefits.va.gov/gibill/comparison_tool.asp | www.va.gov/education/gi-bill-comparison-tool

</body>
</html>

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by brianalloyd** [comment]
@mnorthuis just getting back into the office from PTO.  Is this ready to go now, understand there might have been some back and forth on this issue and wanted to be clear on readiness for implementation.

**Comment by kelsonic** [comment]
Moving this to blocked until we get the green light from folks ✅

**Comment by dan-brooking** [comment]
The new URLs are deployed now.  

Old url is https://www.va.gov/gi-bill-comparison-tool and new URL is https://www.va.gov/education/gi-bill-comparison-tool.

Both are still active. Once the redirect is in place, I can remove the old url.

**Comment by kelsonic** [comment]
Redirects deployed to prod, let us know if you need anything else! 🙂 

http://www.va.gov/gi-bill-comparison-tool
http://www.vets.gov/gi-bill-comparison-tool
http://www.benefits.va.gov/gibill/comparison_tool.asp

**Comment by brianalloyd** [comment]
Team, this work has been completed, going to close the ticket in support.  Please let me know if any questions exist. Thanks.
