### ISSUE TITLE
Add accent to "información" in Spanish COVID-19 page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#34492]
## Issue Description

Our new access to the SiteImprove tool shows that we have 2 instances on the [COVID-19 vaccine Spanish language page]([url](https://www.va.gov/health-care/covid-19-vaccine-esp/)) where we don't have the accent mark on the "o" in "información."

We need to add the accent mark.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/55161de3-541b-4cf5-89b8-b89fd4781d17)

**Comment by lunascoop** [comment]
@RLHecht these changes are ready for review.
Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

It's in the accordion "Vacunas contra el COVID-19 actualmente disponibles" in the **Antes de vacunarse** section.

**Comment by RLHecht** [comment]
Thanks @lunascoop Just reviewed and published.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
