### ISSUE TITLE
[Tier 3] Disability claim issue - SF 06484296

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#34517]
## Issue Description
_Please review encrypted email and details below in order to review and resolve claim submission issue for caller._

---
## Tasks
- [ ] _Review provided details in ticket_
- [ ] _Review additional information from encrypted email_
- [ ] _Advise if additional information is required for review and resolution_
- [ ] _Contact veteran and set up shadowing call if needed_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@alsleaders encrypted email sent.

**Comment by alsleaders** [comment]
@michelpmcdonald helped me and we  pulled the info on this submission based on the PII in the email.

The 526 submission failed with PIF in Use. Not sure how to proceed.

1. No technical workaround, requires manual field review of vet's data, and manual clearing of stuck PIFs.
2. We don't have a way to manually kick off the pif clearing process.
3. To make sure we covered all bases Michel tried to submit it from his end and got the same error.

Just to be clear, at this point, this claim that this vet submitted is not going to be processed until the PIFs are manually cleared and a BE engineer from the claims and appeals team is told to try submitting the claim again.

The failed claim submission will not be visible on the vets Claim Status Tool page.

form526_submission_id: 996651, job_id: "8143ebd69cae5778c86b2f5a"

**Comment by jason-gcio** [comment]
Silent failure emails should be implemented here I think?
We are (going to be) incrementing some of our submissions after we detect the PIF error for the Dependency Claims (686) to get around the PIF already established error which might be helpful here but I need more info around the EP code process for 526's.  I recommend this ticket go into Blocked until we se some daylight on our fix and see if it helps with this error. 
cc: @kathleencrawford, @vhenry07 (Ronnie - I didn't want to edit your report too much....)

**Comment by Kimberley2019** [comment]
Assigning new members/teams for historical purposes.
After review, case may be closed by either team/team members.

**Comment by Kimberley2019** [comment]
7/8/22– New Tier 3 benefits team review.  Modified follow up template sent.  Will reopen if/when user responds with needed information for resolution of issue.
