### ISSUE TITLE
ForeSee Implementation for VAOS

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3452]
# Analytics Implementation or QA Request

## Description
ForeSee comment card application

- Who is this request for?

    - Lauren A.
    
- What team/project is this work for?
    VAOS
    
- Provide the Domain where Google Analytics needs to be implemented
    1. https://www.va.gov/health-care/schedule-view-va-appointments/appointments/
    2. https://www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/confirmation
    
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [x] ForeSee tested on Staging
- [ ] ForeSee implemented on Prod

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Comment card tested & QAd on staging 11/13/19.
*staging.va.gov/health-care/schedule-view-va-appointments/appointments/
*staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/confirmation

![image](https://user-images.githubusercontent.com/48964695/68807507-e6985e00-0635-11ea-8902-a90b1d049300.png)

![image](https://user-images.githubusercontent.com/48964695/68807580-134c7580-0636-11ea-94e2-725f16d5fecc.png)

**Comment by joanneesteban** [comment]
Comment card added to the following links on Prod:
*va.gov/health-care/schedule-view-va-appointments/appointments/
*va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/confirmation

I don't have access to verify this in production. @lalexanderson-dsva would you be able to validate that the feedback button & comment card are live?

**Comment by joanneesteban** [comment]
Will stay in review until VAOS launches the site on Prod to review the Feedback buttons.

**Comment by lenaecb** [comment]
@joanneesteban - saw that the Analytics reporting is blocked by this ticket. Is the block just a 'QA' on production once we've started the rollout? Just want to make sure there isn't any additional implementation on the VAOS dev side. Thanks!

**Comment by joanneesteban** [comment]
@lenaecb Thanks for reaching out! The block is just QA on prod - no additional implementation needed!

**Comment by lenaecb** [comment]
@joanneesteban - we are now live with about 5% or so of users. Can we go ahead and test Foresee now in production? Thanks!

**Comment by joanneesteban** [comment]
Thanks, @lenaecb !

Checked the survey results, and we currently haven't had any user feedback from the 5% of rollout users yet.

Can you check on the Prod URL that the blue feedback button appears? It should look like this (on the right hand side of the page):

![image](https://user-images.githubusercontent.com/48964695/76768564-8fd09b80-6771-11ea-910d-92f54011d947.png)

You may need to refresh your browser cache or unblock site cookies.

**Comment by lenaecb** [comment]
@joanneesteban - yep! got the blue foresee button and when clicked got this prompt:
![Screen Shot 2020-03-16 at 2.06.32 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/cc4da186-9d64-4eb7-b7ba-3db2b786645a)

If a user gives a rating is there also a prompt to leave written feedback as well? Just curious. 

If we're good here, I'll close out this ticket.

**Comment by joanneesteban** [comment]
@lenaecb Great! 

Unfortunately, right now there isn't written feedback but we're working to get that into Medallia when that gets stood up (no timeline on that just yet). In the meantime, we'll probably look into getting that as an addition to ForeSee so you can get product specific feedback.

Closing this ticket, but please feel free to reach out for any other questions!
