### ISSUE TITLE
Optimize Filtered Views of Product QA Dashboard Cards

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#34521]
Our cards currently show all products as a default view, while allowing them to be filtered by a single product. There are two different ways filters can be applied, however, and they achieve different results depending on how that's done. While we may create a drill down view that applies when a single product is clicked, when the page filters by a product it will not access that drilled down view. It accesses the top level view just filtered down to that one product. It can still be drilled down from here, but that provides a really clunky user experience that results in you just seeing a different view of the same data. This leads us to a place where we have to decide on a singular view that displays both the overall picture we want, as well as an appropriate filtered view when a page filter is applied. There's a few considerations we need to make:

- What data is the most important to be displayed for a single product?
- What chart conveys this data the most effectively. Things such as context and goals need to be taken into consideration here.
- How can we structure an overarching view to display this data properly when it's filtered down? This will likely involve us thinking about platform-level views vs product-level views and the separation between the two. Maybe a platform view is better to show each product when unfiltered, but for a product view an overall va.gov average works better to filter down to a specific view we want for a product.

**Comment by CBonade** [comment]
Did some mulling on this today and adjusted the lighthouse data to reflect my findings. Looking to discuss a further plan for this early next week.

**Comment by CBonade** [comment]
Made some updates on this today changing some of our charts that have only one number from a single bar to something more suited for one number and started adding some drill paths. On the way, I discovered some of our data needs a bit more work to be able to be displayed in Domo properly (particularly our coverage report data) so I've made a ticket to address that and will come back to this when that task is completed.

**Comment by CBonade** [comment]
I feel like the overall state of this is in a really good place. We'll always have small changes we make over time as we both learn more about Domo as well as more about how people prefer to use the dashboard - but for the time being I believe we can call this done.

**Comment by pjhill** [comment]
Agreed, let's draw the line for an MVP where we are now. Subsequent changes can be discrete post-MVP efforts.
