### ISSUE TITLE
Analytics Clean-up for VAOS Express Care

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#34528]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [x] QA

- **Who is this request for?**

    - VAOS
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - n/a
    
- **When is the launch date?**
    - n/a

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - There are currently 2 custom dimensions for Express Care in VAOS that can be removed. These are no longer needed as the Express Care feature has been sunset and prior data has been saved in external files.
![Screen Shot 2021-12-23 at 11 16 35 AM](https://user-images.githubusercontent.com/72046525/147294231-886a86cc-c78a-4229-90e9-8bac3da07045.jpg)

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jonathan-epstein13** [comment]
@laurensimpson14 @jennaouellet @bsmartin-ep just tagging you all here in regards to this ticket for when you all get back. Happy Holidays!

**Comment by laurensimpson14** [comment]
@jennaouellet I deleted the two CDs in the workspace [34528 - Analytics Clean-up for VAOS Express Care](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000582). Could you please QA & publish?

**Comment by jennaouellet** [comment]
QA is complete and the new workspace version has been pushed to live. Thanks!
