### ISSUE TITLE
Make the Respondent Burden section of the Privacy Act Statement optional

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#34524]
## Description
[Original feature request ticket](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/381)

"Health questionnaires will not have a respondent burden or OMB control number. Therefore, the entire respondent burden section of the privacy act statement does not apply. The health questionnaires team discussed keeping our own version of the privacy act statement minus the respondent burden in our code. However, we wouldn’t know when and if any updates occur to the privacy act notice section. Therefore, we wanted to know if the respondent burden paragraph could be made optional at the platform level?"

![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/2e3fae93-a523-4e0b-9f1a-c3945b652894)

## Acceptance Criteria
- [ ] make the Respondent Burden section of the Privacy Act Statement optional (it should appear by default)
- [ ] fix/add any necessary tests

**Comment by andresriveratoro** [comment]
This functionality already exists using the `resBurden` property on the component, but we want to make it clearer by providing a description of this behavior in Storybook. This issue is now about updating OMBInfo story in Storybook with this information.
