### ISSUE TITLE
[BE] Vets-api to call initiate pre-checkin endpoint with UUID

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#34534]
## Description
To refresh pre-check-in data, vets-api needs to call initiate pre-checkin endpoint with UUID. 

Plan is to have vets-api make call to LoROTA GET, then with that data make call to CHIP InitiatePreCheckIn endpoint, then make another call to LoROTA GET before sending data back to FE. 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by kanchanasuriya** [comment]
Existing endpoint in CHIP expects lastName & last4 to be sent in payload and the controller in vets-api receiving request from frontend for pre-check-in refresh doesn't have access to lastName & last4.  Implementation blocked until new pre-check-in refresh endpoint available in CHIP.

**Comment by kanchanasuriya** [comment]
We discussed about the issue in our standup and settled down on having new implementation for refresh endpoint from CHIP.  

@acrollet could you please provide some insight here if this has been taken to CHIP team or yet to be discussed with them?  Accordingly @julieadair1 or @jparker0425 will help on taking the request to CHIP team.

**Comment by acrollet** [comment]
@kanchanasuriya I think we still need to make the request to CHIP.

**Comment by julieadair1** [comment]
@jparker0425 will follow up on this one

**Comment by julieadair1** [comment]
@acrollet do you know if this work still need to be done?  Asking because I spoke to Chris H about it this morning and he said he thought this was done.  Thanks!

**Comment by acrollet** [comment]
@julieadair1 the work was done to let the existing pre-checkin endpoint accept a UUID parameter and refresh the data in LoROTA. However, as @kanchanasuriya mentioned it still requires the veteran lastname and last4, which vets-api doesn't cache for security reasons. We need access to a refresh endpoint that only requires the UUID and updates the data in LoROTA, whether that's modifying the existing endpoint again or creating a new one.

cc @Hortonio

**Comment by sarahknoppA6** [comment]
@randomsync to review
