### ISSUE TITLE
[FE] Pre-Check-in: Implement 24 Hour Check for Confirmation Status 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#34532]
## Description
This ticket is regarding the need to implement a check to see if the pages in the pre-check-in workflow have been confirmed within the past 24 hours. 

- Demographics
- NOK
- Emergency Contact 

For each page, if confirmed within the specified timeframe, the page with need be hidden on the **day-of** check-in. i.e., if Demographics is confirmed, but NOK and Emergency Contacts are not, only hide the Demographics page but still present the other two pages for day-of. 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by sarahknoppA6** [comment]
@brianseek to double check and see if this can be closed

**Comment by brianseek** [comment]
I couldn't find the slack thread I was thinking of. We should test this in an end of sprint validation session.
