### ISSUE TITLE
RESEARCH | LOE to Remove SSN from 10-10 Forms

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#34530]
## Background

We received a request to assess the level of effort that would be required to remove SSN fields from the 10-10 forms. At this point, there aren't any concrete plans to do this nor what might be used lieu of SSNs so the ask is just to evaluate effort to remove from front-end nd back-end required fields.

## Tasks

-[ ] Determine front-end/UI changes that would be needed for the 10-10ez and 10-10cg 
-[ ] Determine what back-end changes would be needed for 10-10ez and 10-10cg 

## Acceptance Criteria

-[ ] Estimate of LOE for front-end/UI work
-[ ] Estimate of LOE for back-end work

**Comment by hdjustice** [comment]
There have not been any further requests for this information.  Closing ticket.
