### ISSUE TITLE
[Design] My VA - Payment Info and On-site Notifications: Update design docs with changes from research

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34544]
## Background

Research sessions and synthesis is complete.  We have some immediate changes we will implement as part of our MVP, which need to be updated within the design documentation.

## Reference Materials

- [Sketch File](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=30b328dd-61fa-4e9c-a615-80a4db99566d)

## Tasks

- [ ] Update design documentation to include the changes for:
     -  ....

## Acceptance Criteria

- Designs are updated with the most recent changes from research to reflect our MVP

**Comment by andaleliz** [comment]
Closing this in favor of the more specific tickets created.
