### ISSUE TITLE
Access for Tyler Simoni

### ISSUE THREAD

**Issue by TSimmz** [department-of-veterans-affairs/va.gov-team#34546]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Tyler Simoni

### Your Email

tyler.simoni@gcio.com

### Name of Your Team

Search & Discovery

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1xDSh4rL49Qg4ZtWaRQcnFMFbUbhfQYl2Rha3VekMYiSGfQr1KZ8uRe+FuOiDWx0sYS7+gmFIluLNCkvezIn4OIsH/c/lSn/h8G/2GZmWCINakOXlG5jqlfhH8JvbYDcx10Paj9DJ71d8uWcqZSivjyLxMV7F680MQeyL4F0Anx51P2b/JUEf1DPBaEUv+xiyvx0+Vk/y+UegiaV+hm3AI6gZBNKUkIpbJ48h9aWQbIJP95OiQp181pzV3aM4m1It2B1jNPVkvEG31foTwL0LvcPJcQYr4N3ZlLSm0ua77KB19vNprYcSoBi2fscxRHHse2BdBJKh00XHcYpifX16/oZGL9XPX9XGPjKaQyOU5wEEgl11JR+vhPjx+zQEGhr7WRha2y8jniZj5zDAy2iwe8FnZdIjAfIo4Sz+kuuLmXDoLayWgXOTajVh/6xoMFVIzbvHPTfl+AsBhHHGlyRx9QZ9kURUedvqvrt9iQZ7EUuZ/BEGNAnZkQvAkstIoVc= tylersimoni@tsimoni-C02CK4A0LVDL.localdomain

**Comment by jsgarmon** [comment]
Access granted. Please allow for 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
