### ISSUE TITLE
[Build] Chronological order of appeals / claims

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3454]
## User Story
As a claimant, I want to have a visual representation of the order in which I submitted my claims so that can see them in an organized fashion.

## Goal
List the appeals / issues within the Claim Status Tool in chronological order (order by date).

## Tasks
- [ ] Display claims in chronological order

## Acceptance Criteria
Scenario: A Veteran has multiple appeals and claims that they are able to see in the order the appeals/claims were made.
GIVEN that the user has multiple appeals and claims
WHEN the claims are displayed within the Claim Status Tool
THEN the system displays them in chronological order

**Comment by ndsprinkle** [comment]
In-vision app design: https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/screens/395958869_Claims_Landing_Page_-_Updated_Chron_Order_-_V1
