### ISSUE TITLE
[UX] Brainstorm Ideas for End-to-End Testing in Prod for PCI and CI with Veterans

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#34540]
## Problem Statement
Determine how end-to-end testing can take place in production for pre-check-in and day-of check-in with Veterans.  Ideally, we'd have vets who have upcoming appt. who could potentially do a diary study to share experience from PCI->day of CI. 

## Background Info
We have been hearing some feedback from St. Louis about the confusion between pre-check-in and check-in. We haven’t run an end-to-end study, since the MVPs of both pre-check-in and check-in went live. We will be gathering some feedback when we go on-site at St. Louis. However, that study will not capture feedback as a Veteran is actively engaging with pre-check-in. It will all be after the fact. Nira and I were discussing that a diary study may be a possibility to get feedback as a Veteran is actively completing pre-check-in, then we can follow the diary study all the way through the day of check-in. We discussed when this study would have the most impact from our UX perspective. We thought this might be something to do immediately following the new editing scope and translation work. We would also like to content test some wording within pre-check-in, since pre-check-in was mentioned to be a confusing term too. With our suggested timeline, we might be able to make some changes (if need be) before we are live everywhere.

## Tasks
- [x] Brainstorm ideas for how we could accomplish this e2e testing for both PCI and CI virtually.
- [x] Brainstorm ideas for how we could accomplish this e2e testing for both PCI and CI in person.

**Comment by benbrasso-agile6** [comment]
@loripusey think we can modify this to just include the first two tasks only, e.g., the two brainstorming tasks. that might be good for this sprint.

**Comment by loripusey** [comment]
@benbrasso-agile6 split the other tasks into this [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39708)

**Comment by benbrasso-agile6** [comment]
@benbrasso-agile6 to drop in initial notes here

**Comment by benbrasso-agile6** [comment]
Perfect, thanks @loripusey

**Comment by benbrasso-agile6** [comment]
We initially talked about doing a diary study. Any other methodologies that might work well here? 

The goal is to get feedback on the entire process. E.g., includes pre-check-in and check-in. Of course, this limits us to facilities in St. Louis. 

Perigean could recruit for us. But, in total, their pool is about 4,000 individuals. So, not sure how many individuals are in St. Louis from that group. And, of those people, how many have an appointment coming up? 

If that doesn't work, we could speak to Research Ops team (Shane, Clayton, etc.) about alternative recruiting. So, what might that look like? 

The other option could be that we use Perigean, and we work with engineering to ensure we can create a "fake" test and appointment. 

So, the questions we want to answer are: 

Who can we test with? 
How will we recruit? 
What's the testing methodology? 
What are the drawbacks to that plan? 

@ytsaoca

**Comment by ytsaoca** [comment]
Created this Mural for brainstorming: https://app.mural.co/t/vfscie8528/m/vfscie8528/1649366237889/5c7791fe3ad70cccc71db888c26f509b3c03a1c7?sender=u70b8b2930b03d3ef317d2520

**Comment by benbrasso-agile6** [comment]
Here are the [end-to-end PCI and CI Veteran testing options](https://docs.google.com/spreadsheets/d/1SY0tILazYPZtylrXOXFSpBUjek4LOEwkr2SfmJp4otw/edit?usp=sharing).

@ytsaoca @niradatta1 take a look. CC @zach-park feel free to look as well, although you missed our initial internal sync on this. 

Ideally, we meet beginning of next week to discuss thoughts/feedback on what we should move forward with for the research plan. I can set a meeting for us to review and chat.

**Comment by benbrasso-agile6** [comment]
I also want to grab @acrollet and run him through these to confirm assumptions/feasibility. I will set up time with him.

**Comment by benbrasso-agile6** [comment]
Updated document based on adrian discussion

**Comment by benbrasso-agile6** [comment]
@niradatta1 @kristenmcconnell I think we can close this ticket. Thoughts? 

Our work is in the comments. And, when we pick this work back up in a later sprint, we'll have these notes available.

**Comment by kristenmcconnell** [comment]
I agree that it can be closed.
