### ISSUE TITLE
[12/29/21] Update General User Guide

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#34552]
Make initial updates, looking at:

- clarity
- consistency
- grammar

**Comment by vlivshin** [comment]
Should be ready for review tomorrow, Tues, Jan 4th.

**Comment by vlivshin** [comment]
@jwowk, updates ready for your review. I sent the link to your VA email.

**Comment by jwowk** [comment]
I approve of suggested edits.
