### ISSUE TITLE
Create new URL structure for event detail page

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#34556]
# Description

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1640283433038200

After discussing with @mnorthuis and @davidconlon, we have decided that the URL structure for event detail v2 pages will follow this syntax: `/events?eventID={entityId}&dateIndex={dateIndex}`.

We need to update the [`events v2 app`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/events/index.js) to listen to query params to conditionally render the new event detail page.

We will additionally need an error state + behavior where `eventID={entityId}` does not match any event we have. We will need a design for this error state on the `/events` page.

We should also discuss how this will impact the VAMC events listing pages.

## Acceptance Criteria

- [ ] Create design for error state + behavior if `eventID={entityId}` does not match any event we have.
- [ ] Implement this in our events v2 app.

**Comment by callen2563** [comment]
When the user enters a URL for an event detail page that no longer exists they will be redirected to the main event list page with this error message.  @RLHecht @DanielleThierryUSDSVA @bethpottsVADEPO When one of you have some time can you provide some error message copy? Thanks! :)

![Outreach   Events - Desktop - Error](https://user-images.githubusercontent.com/68560244/147598756-8df98449-a639-488b-958e-ba98db928311.png)

**Comment by callen2563** [comment]
@DanielleThierryUSDSVA @RLHecht @bethpottsVADEPO There has been a change to the above error message the user will instead be seeing the standard 404 page so you can disregard the content request. Thank you :)
