### ISSUE TITLE
[MCP]: Facility Phone Numbers not always showing

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#34562]
## Technical Task

On Medical Copays we have to interact with a ton of facilities. For some reason some facilities do not show their phone number. We need to figure out which facilities don't show phone number and figure out why. We use a global VSP resource to lookup facility phone number maybe more need to be added or there is a key mismatch.

## Expected Behavior

All facilities show phone number on overview page.

## Acceptance Criteria

- [ ] All facilities show phon e number on overview page.

**Comment by craigwheeler** [comment]
this appears to only happen when there is a zero balance with no contact info in the payload so we should either include the contact info in the response or remove it from the UI

 ![Medical Copays  Veterans Affairs 2022-01-04 09-43-02(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/5e5e24ef-8b55-477c-a3fd-cb7639bc3508)

**Comment by denisecoveyduc** [comment]
[MCP] Remove the VA health care facility's contact information on the overview and details pages#34734 will resolve this issue
