### ISSUE TITLE
[Content Review] Add confirmation checkbox to Additional Evidence Upload Screen in Claim Status Tool

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3456]
**User story**
As a member of Benefits and Memorials team building on VSP, I need the 'checkbox to Additional Evidence Upload Screen in Claim Status Tool' content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3455)
- [InVision Design](https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/394760072_Upload_Additional_Evidence_-_Checkbox_-_Revised)

**Acceptance criteria**
- [x] Content reviewed 
- [x] Required content updates/changes provided to Benefits and Memorials team

**Comment by kevinstachura** [comment]
Hi @peggygannon  - Can you please take a look at the checkbox label and accompanying text (beneath it) for content quality? Thank you!

Link: https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/394760072_Upload_Additional_Evidence_-_Checkbox_-_Revised

**Comment by peggygannon** [comment]
Hi, @kevinstachura Please see below for my content recommendation for the checkbox label and text. Do you need me to review the other content on the page or just this part? 


{Checkbox label}
{checkbox} The files I uploaded are supporting documents for this claim only. 

To submit supporting documents for a new disability claim, please visit our [how to file a disability claim](/how-to-file-claim) page. 

{button}
Submit files for review

**Comment by YanaRoy** [comment]
@peggygannon the content review was for the checkbox and the gray messaging box at the top that currently says "Only upload evidence that supports this claim"

**Comment by peggygannon** [comment]
@yana thanks. I've updated my recommendation above ^^

**Comment by YanaRoy** [comment]
@kevinstachura

**Comment by kevinstachura** [comment]
Hi @peggygannon - Changes you have suggested have been added to the Invision proto: https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/screens/394760072_Upload_Additional_Evidence_-_Checkbox_-_Revised

To answer your question:

_do we need to add anything to the message that the evidence should be new supporting evidence and not evidence that they already submitted for that particular claim?_

The goal is more to ensure they're not trying to upload new evidence **unrelated** to that claim or trying to upload decision review forms in an existing, open claim (which we've seen as well). If they need to submit evidence for a totally new and unrelated claim, we want to guide them in the right direction to do so. 

That all said, I don't think it hurts to steer them away from duplicate entries (only **new** and relevant evidence for that claim), which would likely slow down the process as well. I think your revised content captures that elegantly.

Let me know if you have any other changes - thanks so much, Peggy!

**Comment by peggygannon** [comment]
thanks, @kevinstachura I posted a few comments in the mockup. also if there is an inline error message for that checkbox, can you add that to the mockup, so I can review that too?

**Comment by YanaRoy** [comment]
@kevinstachura @peggygannon has everything for this ticket been resolved? Can I close?

**Comment by peggygannon** [comment]
@YanaRoy I believe I still need to see the last of the content tweaks I provided above. Also, @kevinstachura  is there an inline error that appears if users don't check the checkbox? or do I need to write one?

**Comment by kevinstachura** [comment]
Hi @peggygannon - there is currently a checkbox error that exists with some generic messaging - I have produced a mockup to show what we currently have: 

https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/397765347_Upload_Additional_Evidence_-_Checkbox_-_Revised_-_Error_State

Please feel free to advise on better messaging for it!

The other changes have been implemented and can be viewed here:

https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/394760072_Upload_Additional_Evidence_-_Checkbox_-_Revised

Apologies for the delay on this, and let me know if you have any further changes. Thanks @peggygannon !

**Comment by peggygannon** [comment]
Thanks, @kevinstachura I added a comment/made a suggestion on the inline error. Thank you for the updates. 

Peggy
