### ISSUE TITLE
[Build] Add confirmation checkbox and box for messaging to Additional Evidence Upload Screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3457]
## User Story or Problem Statement
As a claimant, I need proper instruction on where I can upload evidence so I can ensure that I am providing it in the proper location for review.

## Goal
- Design best way to display where a user can upload documentation, either as additional evidence to an existing, open claim, as a new disability claim or as a decision review_
- Provide user with a method of acknowledgement (checkbox?) that they understand that the Additional Evidence Upload is specific to the existing claim they have open.

## Tasks
- [ ] Add checkbox 
- [ ] Add messaging box (feel free to change this wording)

## Acceptance Criteria
Scenario: A Veteran has a evidence to submit to an existing claim 
GIVEN the user is logged in 
*and* is on the Claim Status - Additional Evidence Upload screen
WHEN the user attempts to upload evidence
THEN the system provides a checkbox to acknowledge that the evidence is for the specific claim opened
*and* provides messaging area with information regarding other methods of submitting evidence if it is not relevant to the opened claim

**Comment by ndsprinkle** [comment]
Design ticket: #3455

**Comment by ndsprinkle** [comment]
Invision: https://vsateams.invisionapp.com/share/S2U2NQZZ76A

**Comment by kevinstachura** [comment]
https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/screens/394760072 <--- more direct  🙂
