### ISSUE TITLE
Links to Access Request issues seem wrong

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#34587]
### Description
On the page "Analytics customer support guide" there are three links labeled "Analytics Access request template on Github." The first instance of the link is correct and opens a github issue with the proper checkboxes etc. The second and third instances open a blank issue with no template at all.
**Suggestion:** Update the links.
<img width="599" alt="Screen Shot 2021-12-28 at 11 11 44 AM" src="https://user-images.githubusercontent.com/4054752/147599501-53cbbf1b-bf89-4cc6-aa8c-74a1591f45c4.png">

### Relevant URLs 
Page where bad links are: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html
Destination for the blank Request issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo

**Comment by lianilychee** [comment]
Hello @wesrowe !  Thanks for the patience as we go through these tickets.  This issue has already been resolved by the Analytics and Insights team.
