### ISSUE TITLE
Create a document for Daily A11y Scan of `content-build`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34589]
# Description
Let's document the process by which the daily accessibility scan executes against the `content-build`. I started a document that contains high level summary of the operation of the daily accessibility scan [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2031255561/Daily+Accessibility+Scan+for+content-build). Feel free to throw that away or expand on it. Either way, we need to iterate on the document in our private Confluence space before moving it over to the Develop Docs space for publication on the Platform Website.

**Comment by ddzz** [comment]
Conflluence has been updated with additional details: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2031255561/Daily+Accessibility+Scan+for+content-build

**Comment by pjhill** [comment]
Nice, thanks for that write-up. I'm thinking about publishing this to -- https://depo-platform-documentation.scrollhelp.site/developer-docs/Accessibility-testing.1255931908.html.
