### ISSUE TITLE
[Build] Incorporate content for confirmation checkbox on Additional Evidence Upload Screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3458]
## User Story or Problem Statement
As a claimant, I need proper instruction on where I can upload evidence so I can ensure that I am providing it in the proper location for review.

## Goal
- Design best way to display where a user can upload documentation, either as additional evidence to an existing, open claim, as a new disability claim or as a decision review_
- Provide user with a method of acknowledgement (checkbox?) that they understand that the Additional Evidence Upload is specific to the existing claim they have open.

## Tasks
- [ ] Incorporate approved content by checkbox
- [ ] Incorporate approved content in messaging area

## Acceptance Criteria
Scenario: A Veteran has a evidence to submit to an existing claim 
GIVEN the user is logged in 
*and* is on the Claim Status - Additional Evidence Upload screen
WHEN the user attempts to upload evidence
THEN the system asks to the user to acknowledge that the evidence is for the specific claim opened
*and* provides information regarding other methods of submitting evidence if it is not relevant to the opened claim

**Comment by ndsprinkle** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/11193

This is the same PR used for 3457.
