### ISSUE TITLE
[VAMC] Review and validate VAMC System pages have Operating Status link is in place [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34598]
## Story
As a Veteran I need to have a link to the Operating Status on the system page, so I can quickly find facility operational status.

## Tasks
- [x] Review the VAMC system pages and confirm that Operating Status link is correct and updated.

## Acceptance Criteria
- [x] Validation of all VAMC systems have operating status complete.

**Comment by ltrombley** [comment]
Task #34598 - Review and validate VAMC System pages have Operating Status link is in place [BA] - is Complete and moved to Validate
