### ISSUE TITLE
[Report] Direct scheduling data & visuals - December (due 1/10)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#34593]
## Request

Data and visualizations for direct scheduling metrics in Loki for the full month of December (12/1-12/31)

**Submission errors**
- [x] Spreadsheet of error reasons and counts 
- facility or site id
- clinic id
- error reason friendly description
- error code
- number of times occurred 
- [x] Screenshot of trend chart

**Clinic names**
- [x] Spreadsheet of clinic names and counts 
- facility or site id
- clinicName
- clinicFriendlyLocationName
- number of times displayed

If too much data to work with for full report, then check clinic names for the following facility IDs:
517, 650, 580, 664BY, 688, 612GH, 688GE, 508GE, 512, 539GC, 549BY, 558GB, 558GC, 580GL, 612GD, 642, 646GE, 678GE, 502, 508GF, 508GH, 508QC, 528GD, 528GN, 537QA, 539GA, 541, 549GK, 558GA, 558GE, 580GD, 580GF, 580GG, 580GJ, 605GC, 626GA, 640GC, 642GH, 646, 660GJ, 664GB, 672, 672GC, 672QA, 673QJ

### Due by
EOD Mon, 1/10

**Comment by ldelacosta** [comment]
@laurenernest - this is ready for you to review. Thanks.

**Comment by laurenernest** [comment]
@cferris32 are you also able to provide the trend chart screenshot and clinic name data?

**Comment by laurenernest** [comment]
all report info accounted for. closing ticket.
