### ISSUE TITLE
[02/11/22]VEText Newsletter Template

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#34594]
To better communicate news and increase touchpoints with VEText users, a newsletter which was previously sent out pre-product support team, will be re-integrated into the VEText environment. Steps to bring this newsletter back into the world include:

- [x] Establish content strategy for newsletters
- [x] Newsletter Cadence established
- [x] Determine Sharepoint template
- [x] Determine distribution strategy
- [x] Finalize with leadership
- [x] Execute first newsletter.

Moving forward these newsletters will be a regular product of VEText and tickets for newsletters will be created for each iteration and include the newsletter in order to close the ticket.

**Comment by aschulhof** [comment]
Meeting Wednesday to discuss

**Comment by lindsay-insco** [comment]
01/15/21 - first draft

**Comment by lindsay-insco** [comment]
- Newsletter cadence = Wednesdays opposite office hours to increase knowledge retention
- Distribution plan = email and sharepoint
- Draft submitted to leadership

**Comment by lindsay-insco** [comment]
Newsletter sent for VEText
