### ISSUE TITLE
Temporary Access to Production data containing PII

### ISSUE THREAD

**Issue by AdamFreemer** [department-of-veterans-affairs/va.gov-team#34628]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Adam Freemer

### Your Email

adam.freemer@accenturefederal.com

### Name of Your Team

Legacy AO Team 3

### Service(s) You Want Access To

AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEgKKrgZOlGfpGjQD7hdycOZktFCeqTqsH2FpOQdzCh3ytbUybynfdyo6GjVBvEBQz/xdY0FHjIqasxaBkIMKkDLTopzxnMyXwKEgermV3zNDDBQdOrGuVfDDYUXD6svOzDZ0JPU5Jwddi/5UHYcT8a+JDQaEs8ZPfFnLaHssFnzmX3M9DAzsRla7E3Ll5mGNxPBv1nnCLaOPEtM1EMN4qYSc4zaeqmr7jWC/DDq38h6Fgj7HSybtc7Vs5ti6MrGrIPgEZrgWhxWOOK3zxaN0kxmsA+CbqFJDpIUC9NqrRP1p8J473LDqFO5JDIN9i5m0f7ik1R6fTDV65w+ueCT1FWizUFMn38s+1Wm5VJ4nNVVGCLfUTTREbUJqL0jPaTkt8VXbfNujjcs2V9uWhuKE9iJEC316y9Zz+HQgXmJ/ViLo6wdAhAg8ovzuAY2MfkqtyJwbWc+d6ZUc+pZ8xnP+qM1wTRvblZITHuu/+HArlFP/G4B2sMy+ORjyAToafs9U= adam.freemer@AFSMWX9K3EV6YHQ

### Desired AWS Services

I already have AWS access, but need access to a copy of production data, or the ability to query it (on some other container possibly). Please see thread: https://dsva.slack.com/archives/CBU0KDSB1/p1640642389088800

**Comment by jsgarmon** [comment]
DB in question seems to be `dsva-vets-api-prod-2`.

**Comment by jhouse-solvd** [comment]
@mchelen-gov & @f1337 - Flagging you for awareness.

**Comment by mchelen-gov** [comment]
@td-usds can security team review and provide guidance?

**Comment by troymosher** [comment]
Alot of security feedback in the linked slack discussion above.  Should be done by giving read-only access to a copy of the prod database, not the live instance.  Also, would need a defined time frame requested, with a start and end time/date for access at which time it would be revoked.  Also reiterate that data should not be exported/dumped from the copy to anywhere else.

**Comment by AdamFreemer** [comment]
@troymosher - Your recommendations all sound very reasonable, thanks for the response. How much notice would I have to give you folks to prepare for this, and how would we proceed? What else do I need to do on my / our end?

**Comment by jsgarmon** [comment]
access no longer needed, closing.
