### ISSUE TITLE
Design for Facility health service

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34635]
## Issue description
VA health and non-clinical services may be offered at more than one location for a given health system. Editors can indicate if the main address should appear or a specified address should be used. 
- When the service is offered at the facility street address, only the wing/floor/room info should be displayed within the accordion (to avoid duplicating the street address, which is displayed elsewhere on the page). 
- When the service is offered at an alternate location (defined by the editor), the specified location address should be displayed.  
- In some cases, the service can be offered at more than one location, each specifying either facility or alternate address. 

## Problems to solve

- Service locations (for both health services and non-clinical services) render in interesting ways when no name is provided, particularly when multiple service locations exist at a single facility.
- Multiple services locations are not visually separated, making information such as hours appear to be a continuation of a previous location (probably also causing accessibility issues for those using assistive tech)
- In some cases, the editor may not specify wing/floor/room info which results in no address display. 
- The absence of a name heading impacts heading hierarchy 

## Screenshots 

<details>
<summary> Scenario: Service is delivered at an alternative location </summary>

![image](https://user-images.githubusercontent.com/55411834/147702141-54948f9a-5efc-494c-8a79-0e750012d72b.png) 

![image](https://user-images.githubusercontent.com/55411834/147702179-53577f3e-aae8-4b60-9db7-45d0fc338381.png)

</details>

---

<details>
<summary> Scenario: the editor has specified the facility address should be used but did not include additional wing/floor/room info.  </summary>

![image](https://user-images.githubusercontent.com/55411834/147701972-48c6012a-5446-4252-9037-41c47862b802.png)

</details>

---

<details>
<summary> Scenario: an annotated example from production (as it stands currently) with multiple service locations at a single facility  </summary>

![image](https://user-images.githubusercontent.com/6863534/147594478-21d651c0-f599-47f1-84d1-0fe342d1153d.png)

---

Here is the same data as it will appear with the new logic for displaying service location address (or, in this case, _not_ displaying service location address when "use facility address" box is checked. see #7339):
![image](https://user-images.githubusercontent.com/6863534/147595220-1ad70197-bd3e-410c-8242-81b0809162b1.png)

---

Here's an example from https://www.va.gov/alaska-health-care/billing-and-insurance/ recreated with fake data to model multiple locations

![image](https://user-images.githubusercontent.com/55411834/147985797-0aa8272a-1520-4eaf-a544-6926f50834f8.png)

</details>

<details>
<summary> Drupal editorial experience </summary>

![image](https://user-images.githubusercontent.com/55411834/148834008-0f4a8a30-4f4c-4df0-bab5-526133f07405.png)

![image](https://user-images.githubusercontent.com/55411834/148834080-f928fffa-ceab-4664-abac-9a465a0f0b4b.png)

![image](https://user-images.githubusercontent.com/55411834/148834223-0c273431-52d3-4f49-900c-dd26b35a09cc.png)

</details>
## Tasks

- Reference the VA.gov style guide for formatting [Dates, times, phone numbers, and addresses](https://design.va.gov/content-style-guide/dates-and-numbers) but be aware that data formatting (especially hours) may make current displays inconsistent with style guide recommendations
- Create a design spec which Iterates on facility health and non-clinical service location design and accounts for the following possible scenarios
  - Service is offered at a single location which _uses_ the facility address (displaying only a wing/room/suite)
  - Service is offered at a single location which _does not_ use the facility address (displaying a full address, including - possibly- another city)
  - Service is offered at multiple locations, each of which _may or may not_ use the facility address

## Acceptance Criteria
Design includes
- Method for visually separating and distinctly announcing to screen readers when more than one location is displayed
- Method for maintaining header hierarchy in scenarios described above
- Consistent semantic markup and visual design

Design: here's the updated [UXPin for health service design](https://preview.uxpin.com/c53f89d47dcf140eac97df4e70896be4f40877c2#/pages/146478035/documentation/no-panels?mode=i) - Nick O

**Comment by nicko-amida** [comment]
@mmiddaugh Here's a [UXPin](https://preview.uxpin.com/c53f89d47dcf140eac97df4e70896be4f40877c2#/pages/146478035/documentation/no-panels?mode=i) which the different scenarios, and engineering documentation included. There's a lot of little details in these cases, so let's chat about what I've included to make sure I didn't leave out anything.

**Comment by mmiddaugh** [comment]
this work will continue in #35855
