### ISSUE TITLE
Infra Recommit - Replatforming the platform

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3463]
## User Story and Problem Statement

As a team developing on VA.gov, I want to have a stable platform that allows my team and others to grow at our rate, empowering us to develop using best practices, so that we can create and expand upon great services for our Veterans.

### High Level User Story/ies or Description: 
Reworking our platform so that we can meet the needs of VSP and VFS teams and give veterans the best quality of service we can.

### Initiative Outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/infrastructure_recommit/product_outline.md

### Discovery readout:
https://docs.google.com/presentation/d/1mESrMGEn5nGG9M0HUIkoBfIUCtk9ZrdV7FkMsWOH4XE/edit#slide=id.g76a7f82c07_0_265

### Pain Points being addressed:
- Complexity
- Brittleness/older technology 
- Lack of self-service on the platform. 
- Amount of support due to the complexity 
- Lack of confidence due to the current ecosystem

## VSP Objective (Q1 & Q2 2020)
O3: Stability and resiliency of the Platform's systems and teams continue to improve.	

### VSP in Q2 2020
Furthers the to improve the theme around Testing & Isolation.

## Goals
Rework the platform in order to accommodate it's growing need. 			

## High Level Plan
- Implementing new Logging Solution #10529
- Phase 1: Migration of Ops Owned Services #8649
- Phase 2: Migrate Remaining Services #8656
- Future

## Measuring Success (KRs/KPIs)
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- [VSP KR] Increase in customer NPS
- Team sentiment of complexity (decrease)
- Cycle time for work (decrease)
- DevOps support for routine tasks (decrease)

### Assumptions and Hypotheses

We **hypothesize** that **if** we have a self-service Infra, **then** teams will be able to have more control over their application.

**Comment by jhouse-solvd** [comment]
Need to move relevant information from this epic into [this Q4 initiative](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14065) which has been re-framed to more accurately reflect the relevant work to be done surrounding this topic.

**Comment by jhouse-solvd** [comment]
There may be some information to harvest from this ticket, but it is no longer representative of our upcoming initiatives which we are working to re-define now.

**Comment by mchelen-gov** [comment]
This appears to be resolved, with further work occurring in: https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+label%3Aeks+label%3AVSP-Initiative
