### ISSUE TITLE
VBA taxonomy research synthesis

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34638]
## Issue description
Synthesize Veteran input from sessions conducted according to [Research Plan Drafted Services Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/services-benefits-taxonomy-USERS/research-plan.md) and [Convo Guide Drafted for Services Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/services-benefits-taxonomy-USERS/conversation-guide.md) with the goals of 
- to gain understanding about Veteran mental models for the identification/organization/classification of VBA services
- answer questions such as
   - What tasks do Veterans do at benefit facilities? 
   - What are the words they use to describe them?
   - How do Veterans categorize these services? 
   - How do Veterans search for benefit-related services and the locations where they can receive them?
   - What other personas (caregivers? beneficiaries?) should be considered for this taxonomy?

## Tasks
- Synthesize findings 

## Acceptance Criteria
- Prepare findings and recommendations for any changes to names and organization of VBA services

**Comment by Dave-Sukharan** [comment]
Synthesis Presentation attached
https://github.com/department-of-veterans-affairs/va.gov-team/commit/7cf1002b3974365c136481f8eb04ee6f225e77b0

GitHub Findings Page to come soon

**Comment by mmiddaugh** [comment]
Created the following issues to pull through changes recommended in these findings 
- Increase VBA service information available in the Facility Locator #37632
- Increase VBA facility information available in Facility Locator #37633
