### ISSUE TITLE
Update form 22-1990s VRRAP: add new information to form

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34641]
This ticket is to add the fields as dictated by the platform-approved design. This work cannot be started until the design work is completed and approved by all parties.

[Additional information to be added as needed]

--
## Tasks
- [ ] tbd 
- [ ] tbd

--
## Acceptance Criteria
- [ ] New fields have been added to the form, per approved design.
- [ ] tbd

**Comment by mrblanco1** [comment]
This ticket is no longer needed.
