### ISSUE TITLE
[VAMC] Please review and create redirects from General VAMC - to main medical center - Campus Maps 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34645]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live:  In next 14 days.

### Redirects   - 25 total redirect corrections
Current URL  |  Redirect Destination or New URL
--- | ---
https://www.va.gov/albany-health-care/albany-stratton-va-medical-center-campus-map/  |  https://www.va.gov/albany-health-care/samuel-s-stratton-va-medical-center-campus-map/
https://www.va.gov/coatesville-health-care/coatesville-campus-map/  |  https://www.va.gov/coatesville-health-care/coatesville-va-medical-center-campus-map/
https://www.va.gov/durham-health-care/durham-health-care-campus-map/  |  https://www.va.gov/durham-health-care/durham-va-medical-center-campus-map/
https://www.va.gov/eastern-oklahoma-health-care/ernest-childers-campus-map/  |  https://www.va.gov/eastern-oklahoma-health-care/ernest-childers-department-of-veterans-affairs-campus-map/
https://www.va.gov/fargo-health-care/fargo-health-care-campus-map/  |  https://www.va.gov/fargo-health-care/fargo-va-medical-center-campus-map/
https://www.va.gov/montana-health-care/fort-harrison-campus-map/  |  https://www.va.gov/montana-health-care/fort-harrison-va-medical-center-campus-map/
https://www.va.gov/eastern-oklahoma-health-care/jack-c-montgomery-campus-map/  |  https://www.va.gov/eastern-oklahoma-health-care/jack-c-montgomery-department-of-veterans-affairs-medical-center-campus-map/
https://www.va.gov/palo-alto-health-care/livermore-division-campus-map/  |  https://www.va.gov/palo-alto-health-care/palo-alto-va-medical-center-livermore-division-campus-map/
https://www.va.gov/louisville-health-care/louisville-health-care-campus-map/  |  https://www.va.gov/louisville-health-care/robley-rex-department-of-veterans-affairs-medical-center-campus-map/
https://www.va.gov/palo-alto-health-care/menlo-park-division-campus-map/  |  https://www.va.gov/palo-alto-health-care/palo-alto-va-medical-center-menlo-park-division-campus-map/
https://www.va.gov/houston-health-care/michael-e-debakey-medical-center-campus-map/  |  https://www.va.gov/houston-health-care/michael-e-debakey-department-of-veterans-affairs-medical-center-campus-map/
https://www.va.gov/palo-alto-health-care/palo-alto-division-campus-map/  |  https://www.va.gov/palo-alto-health-care/palo-alto-va-medical-center-campus-map/
https://www.va.gov/charleston-health-care/ralph-h-johnson-va-medical-center-campus-map/  |  https://www.va.gov/charleston-health-care/ralph-h-johnson-department-of-veterans-affairs-medical-center-campus-map/
https://www.va.gov/indiana-health-care/richard-l-roudebush-va-medical-center-campus-map/  |  https://www.va.gov/indiana-health-care/richard-l-roudebush-veterans-administration-medical-center-campus-map/
https://www.va.gov/salem-health-care/salem-health-care-campus-map/  |  https://www.va.gov/salem-health-care/salem-va-medical-center-campus-map/
https://www.va.gov/salt-lake-city-health-care/salt-lake-city-health-care-campus-map/  |  https://www.va.gov/salt-lake-city-health-care/george-e-wahlen-department-of-veterans-affairs-medical-center-campus-map/
https://www.va.gov/sheridan-health-care/sheridan-campus-map/  |  https://www.va.gov/sheridan-health-care/sheridan-va-medical-center-campus-map/
https://www.va.gov/butler-health-care/va-butler-health-care-campus-map/  |  https://www.va.gov/butler-health-care/butler-va-medical-center-campus-map/
https://www.va.gov/erie-health-care/va-erie-health-care-campus-map/  |  https://www.va.gov/erie-health-care/erie-va-medical-center-campus-map/
https://www.va.gov/fayetteville-coastal-health-care/va-fayetteville-coastal-health-care-campus-map/  |  https://www.va.gov/fayetteville-coastal-health-care/fayetteville-va-medical-center-campus-map/
https://www.va.gov/oklahoma-city-health-care/va-oklahoma-city-health-care-campus-map/  |  https://www.va.gov/oklahoma-city-health-care/oklahoma-city-va-medical-center-campus-map/
https://www.va.gov/salisbury-health-care/wg-bill-hefner-salisbury-campus-map/  |  https://www.va.gov/salisbury-health-care/wg-bill-hefner-salisbury-department-of-veterans-affairs-medical-center-campus-map/
https://www.va.gov/west-palm-beach-health-care/west-palm-beach-health-care-campus-map/  |  https://www.va.gov/west-palm-beach-health-care/west-palm-beach-va-medical-center-campus-map/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
URL corrections needed for the destination pages per core VAMC IA.  This issue is blocked until those changes are made, and then we will evaluate whether redirects are needed.

**Comment by mnorthuis** [comment]
@SgardnerPMP none of these redirects are done.  Was there a decision not to complete them?  Can add you info here?

**Comment by SgardnerPMP** [comment]
@mnorthuis,  I did research back in my notes.  This Redirect request is closed.  All of the campus maps URLs had low to no traffic and VHA DM approved moving them to the correct parent.   They have already been updated and redirects are not required.  Please return to close.
