### ISSUE TITLE
Update 22-1990S VRRAP: Update the OMB date

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34642]
## Issue Description
Need to update the OMB expiration date on the front page bottom of the form to reflect the correct expiration date.

Per Rodney Hopkins, EDU VRRAP team, the correct date is October 31, 2024

--
## Tasks
[ ] update the expiration date to October 31, 2024

--
## Acceptance criteria
[ ] The new expiration date appears on the front page of the online form.
[ ] tbd

**Comment by mrblanco1** [comment]
The OMB Expiration Date is already up to date in production. This was verified on 1/7/2022. 

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/1af63677-bdb9-4b83-b786-d14f2054b054)

Abe Blanco.
