### ISSUE TITLE
Access for Kelson Adams

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#34664]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Kelson Adams

### Your Email

kadams@governmentcio.onmicrosoft.com

### Name of Your Team

Public Websites

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQglHyOvfKx/xU4rzBGKmXiyWUagcXUUqRjcC6uPFG5H68VJW7TtLRLMXXRhXUQBZS/HfbX0nzxWtdms6m/YhnOb8V/PFJkqieiXKTdpage7hFIEgbkzV63mhL+BK8FmpgQvZjZmKDWwUCYGR6Cqhpnt2zKbK4ttWIRyxzX+Yn6MArZAQUQciOi/EYB6a/XsGKWssGSupCfBePPoM20heKBNTc1CuuyFpqTdO3ezSt+hdk26w7O1LSUZg5qiJwYjLW8tly0OI1hZjAqXDKPEN3U7MPig6X95bjdRP4czt1PYF97rdn/ZfpRVpWlUQhCeTBeiM+wdGB3yoLdVkOxsFtnMUpERDMs8Rugb0FWssFm/XU9I37OCzND2r6iaCtuMA1T18YlU0uGCKKh6QSizEt2PSYTX4CZp27TnPvfryNuZlTdGNi0z+nAMN304aR0dKA+fGULqKUUAOfxCl1wRKJRbHYxFau9CjmgH6jykMkqYfzwd3ncQcy3woHVseGvvc= kelsonic@Kelsons-MacBook-Pro.local

**Comment by kelsonic** [comment]
Recently acquired a new computer so I went through the `vtk socks setup` process and it led me here. Thanks for the help! 🙂

**Comment by jsgarmon** [comment]
I updated your email to your business email (this affects how your key is named, and will make it easier to find your info if we need to make updates).

Access is granted and your key added to our system. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
