### ISSUE TITLE
[FE] Phase 1 10-10EZ short form implementation - flow changes

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#34662]
## User Story

As a Veteran applying for health care, I would like to expedite the HC application so I can complete it faster, remove blockers, and have less confusion.

## Expected Behavior

This is the first step in implementation of short form (if an applicant's disability rating is 50% or higher, they can skip some parts of the application). This first step reorders the specified questions to enable the short form functionality in the future.

1. The VA Benefits section (includes VA disability question and dependent VA pension question) becomes Step 2
     - This is directly after Step 1 Veteran information section (directly after email/phone question)
     - This is directly before **_now_** Step 3 (previously step 2) Military Service section

2. The Marital status question (currently in Step 1 Veteran information) moves after the Financial disclosure question within the Household information section.
     - This is directly after Financial disclosure question
     - This it is dependent on a "Yes" answer to the financial disclosure question _(same as the rest of this section)_
     - This is directly before the Spouse's information questions
     - **Please note:** The "Spouse's information" questions are dependent on the marital status answer. This logic **shouldn't** change.

### Applies for both authenticated and unauthenticated:
- [ ] VA Benefits questions are moved as specified above
- [ ] Marital status question is moved as specified above
- [ ] Marital status question maintains same logic for "Spouse's information" display 
- [ ] Payload structure sent to ES is not modified 
- [ ] Reviewed by designer in RI
- [ ] Successfully tested 

## Resources
- [Mural board flow](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923531828/474bfdde942c22a0df26ad416a0b23e36b834d4a?sender=u6ad375c1c8425e5bfec67027) - Note the stickies that show where each question is moved

**Comment by SKasimow** [comment]
@lzapson here's the info on what can be pre-populated (it's also part of the tickets in the epic): https://github.com/department-of-veterans-affairs/va.gov-team/issues/26762
