### ISSUE TITLE
Analytics Implementation or QA Support for [Public Websites - Outreach & Events MVP]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34675]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Public Websites Team]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Staging Link](https://staging.va.gov/outreach-and-events/events/)
    
- **When is the launch date?**
    - 1/11/2022 Target Date

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]
    - Toggle "Find other times for this event"
    - Click onto a recurring event time
    - Click "Show more times"
    - Click "Add to calendar"
    - Click "Share on FB"
    - Click "Share on Twitter"
    - Click CTA (register)
    - Click "See all events"

- Events Listing Page Interactions: 
    - Apply filter (with various options set like startsAtDay startsAtMonth endsAtDay endsAtMonth filterBy)
    - Click event link
    - Pagination clicks

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by brianalloyd** [comment]
@laurensimpson14 please let us know if you need any additional details on this ticket, we have a programmed staging review on 1/13 in support.  Looking to get analytics tracking connected ASAP.  Thanks.

**Comment by laurensimpson14** [comment]
Hi @brianalloyd please see my notes below for each interaction. 

| Interaction |Screenshot of Interaction | Screenshot of dL | Status |
| -- | -- | -- | -- |
| Toggle "Find other times for this event" | Where can I find an example of this button? ❓ | | |
| Click onto a recurring event time | Where can I find an example of this button? ❓ | | |
| Click "Show more times" | Where can I find an example of this button? ❓ | | |
| Click "Add to calendar" | ![image](https://user-images.githubusercontent.com/80417436/148833701-46cdc29d-3ac0-4abd-875e-1a8123919ba8.png) | ![image](https://user-images.githubusercontent.com/80417436/148833730-12a28f40-2620-4d4b-a209-b445da3259e0.png) | 🟢 Tracking Correctly |
| Click "Share on FB" | ![image](https://user-images.githubusercontent.com/80417436/148833803-96c4d4e4-7cc7-44fe-b2d2-6cb6a1e0c828.png) | ![image](https://user-images.githubusercontent.com/80417436/148833840-fc83910e-ed34-4ed7-afbe-7df20bce9980.png) | 🟢 Tracking Correctly |
| Click "Share on Twitter" | ![image](https://user-images.githubusercontent.com/80417436/148833897-8c660abd-7f13-455d-acee-70ab49c7e1b7.png) | ![image](https://user-images.githubusercontent.com/80417436/148834012-7517226b-4057-42fd-a8eb-059035d0dd78.png) | 🟢 Tracking Correctly |
| Click CTA (register) | ![image](https://user-images.githubusercontent.com/80417436/148834300-6b77df41-c4a1-49b5-be4b-24b8205353df.png) | ![image](https://user-images.githubusercontent.com/80417436/148834417-57abf1e7-63cf-40be-9401-e3d3fd467b2d.png) | 🟡 Tracking currently as an outbound link click. Will all outbound links that are linked to the "Register" CTA go to a zoom link with the word "register" in it? If so, then we can filter for all outbound links that contain those phrases, however if some links won't have "register" in it, then we may want to track this a different way.|
| Click "See all events" | Where can I find an example of this button? ❓ | | |
| Apply filter (with various options set like startsAtDay startsAtMonth endsAtDay endsAtMonth filterBy) | ![image](https://user-images.githubusercontent.com/80417436/148834807-f9bb112b-d1d3-4744-aaf6-8f608e059192.png) | N/A | 🔴 Not currently tracked. In order for this to be passed I'll need your developer to pass a dataLayer spec. I'm working on getting this for you now. |
| Click event link | ![image](https://user-images.githubusercontent.com/80417436/148835129-59c5082c-5cd3-42b7-9faf-45f5f0993003.png) | N/A | 🟡 Tracking currently as previous page path, so the number of times an event is clicked on can be determined in GA by filtering the pageviews report to events pages where the "previous page" was the outreach events page. Will this work for what you're looking for? |
| Pagination clicks | ![image](https://user-images.githubusercontent.com/80417436/148834650-b31f34d7-b7f0-4eb5-a117-7a2557ad0ec8.png) | ![image](https://user-images.githubusercontent.com/80417436/148834675-1f0a279a-b446-4131-bc8f-72e3660a2b73.png)| 🟢 Tracking Correctly |

**Comment by brianalloyd** [comment]
@laurensimpson14 thanks so much for the quick reply.  In terms of the `"CTA Register"` that is currently set up as an outbound click element and will likely remain forward. Can we set up filtering for all outbound links that contain those phrases `"Register"` and that should help us at least track level of traffic from that funnel.  

@srsuddath could you scrub in when you have some time to address the `DataLayer Specs` for the `Apply Filter` component as noted above?

**Comment by brianalloyd** [comment]
@laurensimpson14 Also wanted to advise that the `recurring event` are currently only in `tugboat env` current which might require us to revisit this once that component is fully pushed to production in order to implement tracking based on CMS dependency.

**Comment by brianalloyd** [comment]
@laurensimpson14 last point of clarification.  The "See all events" is actually now called the "See more events" can is at the bottom of the Events details page: 
![Screen Shot 2022-01-12 at 3 08 40 PM](https://user-images.githubusercontent.com/70410912/149231150-f5eb45dd-f48f-4f39-8262-c238769625f8.png)

**Comment by laurensimpson14** [comment]
>In terms of the "CTA Register" that is currently set up as an outbound click element and will likely remain forward. Can we set up filtering for all outbound links that contain those phrases "Register" and that should help us at least track level of traffic from that funnel.

@brianalloyd Yes, we can filter on `Register`. I've updated the table below to show green for this interaction. 

@srsuddath Was the drop down created with the drop down component? If so, could you please enable analytics to `true`? 

>Also wanted to advise that the recurring events (top three items) are currently only in tugboat env current which might require us to revisit this once that component is fully pushed to production in order to implement tracking based on CMS dependency.

Sounds good, I've updated the status for those items in the table below. 

>The "See all events" is actually now called the "See more events" can is at the bottom of the Events details page
Perfect - that is tracking! I updated the table below for this interaction. 

| Interaction |Screenshot of Interaction | Screenshot of dL | Status |
| -- | -- | -- | -- |
| Toggle "Find other times for this event" | | | 🟡 Interaction is currently in tugboat env, waiting for component to be pushed to production |
| Click onto a recurring event time | | |🟡 Interaction is currently in tugboat env, waiting for component to be pushed to production |
| Click "Show more times" | | |🟡 Interaction is currently in tugboat env, waiting for component to be pushed to production |
| Click "Add to calendar" | ![image](https://user-images.githubusercontent.com/80417436/148833701-46cdc29d-3ac0-4abd-875e-1a8123919ba8.png) | ![image](https://user-images.githubusercontent.com/80417436/148833730-12a28f40-2620-4d4b-a209-b445da3259e0.png) | 🟢 Tracking Correctly |
| Click "Share on FB" | ![image](https://user-images.githubusercontent.com/80417436/148833803-96c4d4e4-7cc7-44fe-b2d2-6cb6a1e0c828.png) | ![image](https://user-images.githubusercontent.com/80417436/148833840-fc83910e-ed34-4ed7-afbe-7df20bce9980.png) | 🟢 Tracking Correctly |
| Click "Share on Twitter" | ![image](https://user-images.githubusercontent.com/80417436/148833897-8c660abd-7f13-455d-acee-70ab49c7e1b7.png) | ![image](https://user-images.githubusercontent.com/80417436/148834012-7517226b-4057-42fd-a8eb-059035d0dd78.png) | 🟢 Tracking Correctly |
| Click CTA (register) | ![image](https://user-images.githubusercontent.com/80417436/148834300-6b77df41-c4a1-49b5-be4b-24b8205353df.png) | ![image](https://user-images.githubusercontent.com/80417436/148834417-57abf1e7-63cf-40be-9401-e3d3fd467b2d.png) | 🟢 Tracking Correctly (Tracking as an out, in analysis will filter on the phrase `register`)|
| Click "See more events" | ![image](https://user-images.githubusercontent.com/80417436/150030033-cd5a5c93-ee1e-4adb-b2a5-d77754ff6a2d.png) |![image](https://user-images.githubusercontent.com/80417436/150030072-da6c8d02-9809-4dad-9d48-75dda435859f.png) |🟢 Tracking Correctly |
| Apply filter (with various options set like startsAtDay startsAtMonth endsAtDay endsAtMonth filterBy) | ![image](https://user-images.githubusercontent.com/80417436/148834807-f9bb112b-d1d3-4744-aaf6-8f608e059192.png) | N/A | 🔴 Not currently tracked. Checking with Sam to see if the drop down was created with the drop down component. If so, analytics needs to be enabled to true.|
| Click event link | ![image](https://user-images.githubusercontent.com/80417436/148835129-59c5082c-5cd3-42b7-9faf-45f5f0993003.png) | N/A | 🟢  Tracking currently as previous page path, so the number of times an event is clicked on can be determined in GA by filtering the pageviews report to events pages where the "previous page" was the outreach events page. Will this work for what you're looking for? |
| Pagination clicks | ![image](https://user-images.githubusercontent.com/80417436/148834650-b31f34d7-b7f0-4eb5-a117-7a2557ad0ec8.png) | ![image](https://user-images.githubusercontent.com/80417436/148834675-1f0a279a-b446-4131-bc8f-72e3660a2b73.png)| 🟢 Tracking Correctly |

**Comment by brianalloyd** [comment]
@srsuddath looping you into this ticket to see if you can help with details needed to link the `Apply filter` component for analytics tracking.

**Comment by brianalloyd** [comment]
@tmac9494 looping you into this ticket, to see if you can help with details needed to link the `Apply filter` component for analytics tracking.

**Comment by LindaLi123** [comment]
Hello @tmac9494 @bsmartin-ep What is going with this ticket at the current moment?

**Comment by longmd** [comment]
@bsmartin-ep , do you happen to know what the expected dataLayer spec is for the "Apply Filter" interaction mentioned above? It looks like Lauren was putting something together at some point, but it never got dropped into this ticket. I can approximate something based on the data options, but want to make sure what we're passing is what your team would be expecting.
