### ISSUE TITLE
Identity Monitoring and Alerting Improvements 2022

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#34679]
## Description
This Epic encompasses improvements we want to make to our Alerting tools and processes.  We want to try to reduce the signal-to-noise ratio so users can more readily check status of the systems we monitor/are responsible for, and our internal team can more quickly respond to issues.

## User story
**As a** VSP Engineer
**I want** to quickly and easily check and be updated on the status of identity-managed systems
**So that** I can understand if there are any ongoing issues, and respond as-necessary

## Acceptance Criteria (WIP)
- [ ] Dashboard
- [x] Demo Worthy?

**Comment by nsoutouras** [comment]
Mid-sprint check-in 1/10: This is progressing slowly as Joe is currently quite engaged.  Sylvester is starting to pick up parts of this as he completes onboarding.

**Comment by nsoutouras** [comment]
Demo next week

**Comment by bosawt** [comment]
@joeniquette Any reason to keep this epic around?
