### ISSUE TITLE
Access for Sylvester Lee

### ISSUE THREAD

**Issue by sylvesterlee1911** [department-of-veterans-affairs/va.gov-team#34683]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Sylvester Lee

### Your Email

sylvester.lee@oddball.io

### Name of Your Team

VSP Identity

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRJX3aviw5LqOiTx9B5XUrqohS35ElJZAFBi4yVtbTR8LUd0rsQIJojm6Ny3ZZZPWatrZCy9MulFr9nFgXe4eHyh9dh0mUSaRbiUnl2Q1GBLnkCT9lezgDZJET94tkTpR7muvWD3njx1dI1B8etShrCnqqC7lXufwDTUpeLqlcAEIrQntIDUmhcuW4JR+Ew56gxRq6cwH/RCF3K4ZaiYsDfzafvxzRTrBFwc9PSD9mMLQorDyRkJlj5RK8zkKKj4ojJ1lo3B9eoyARKe+a6TRLmgO2B9vn3ivVSMW4eqNCnjm8kQd3gvT24GNAF8IzO66ey/yZvywTdEsMuolX7X3LsmvENkBUcV6Xnyah4c506I+6Vldi0dQ6hMhjsOaNIE72/WQ2WfUG62cSBFJ10c9FM9Cz6hGoGocBJGvR8Rg1u1E6McaaZvPdI8VY1uXvoK+CDl/OOMws50JPDIrxct1cKBAOgFOWzqBiPxYAOwhQolYnmzkVhoGzGURTT86pyd8= slee@DESKTOP-9655QNS

### Desired AWS Services

I am a security engineer on the VSP Identity team and I require the same permissions as the other security engineer on the team, Joe Niquette. My responsibilities require me to have access to perform security audits and functions within AWS, mostly focused around logging and monitoring of va.gov.

**Comment by mleclerc00** [comment]
**For AWS Access:**
User: Sylvester Lee
COR: Mary O'Toole
Approval needed: @department-of-veterans-affairs/operations-aws-approvers

**Comment by mleclerc00** [comment]
Hi @sylvesterlee1911 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by td-usds** [comment]
Reached out to VOR for EQIP Transmittal Date

**Comment by td-usds** [comment]
Reached out to VOR

@mleclerc00 I'm not sure they need equally broad permissions as Joe because Joe may have been grandfathered into more permissions than he really ought to have... Can you work with @sylvesterlee1911 to figure out what is needed?

**Comment by jhouse-solvd** [comment]
@sylvesterlee1911 -If you can articulate which specific tools/resources/information in AWS you are looking to access, that would be very helpful. We are still waiting on your approval for AWS access, but this will be helpful in the meantime. 

After Joe began, a lot of logs were moved to Grafana Loki, so there may be less need for certain information in AWS. We can also discuss a bit more to make sure you are oriented with the right tools. Feel free to reach out on Slack as well if it's helpful.

**Comment by td-usds** [comment]
This is *tentatively* approved from an eligibility for access perspective
However, before final approval, we need to nail down what the desired access is actually for

@jhouse-solvd or @mleclerc00 can you confirm this approach? Do I keep the "Awaiting Approval" for now or do I delete it?

**Comment by jbritt1** [comment]
We actually have a working `vsp-identity` IAM group I believe that we could likely apply to this user.

**Comment by jbritt1** [comment]
https://console.amazonaws-us-gov.com/iamv2/home?#/groups/details/vsp-identity?section=permissions

**Comment by td-usds** [comment]
`vsp-identity` makes sense to me; final approval

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
