### ISSUE TITLE
Ideation/Whiteboarding Session(s)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3469]
## User Story or Problem Statement
As a UX designer, I need to conduct ideation/whiteboarding sessions after synthesizing data so I can collaborate with designers and developers to create solutions prior to prototyping.

## Goal
_A Mural board containing the results of ideation/whiteboarding sessions meant to provide solutions and/or low fidelity wireframes based on synthesis_

## Objectives or Key Results this is meant to further
- _The form's design and flow_

## Acceptance Criteria
- [ ] _Create a Mural board for the ideation/whiteboarding session(s)_
- [ ] _Schedule time(s) with design/development team_
- [ ] _Conduct ideation/whiteboarding session(s)_
- [ ] _(Optional) Present Mural board to team/team lead_
- [ ] _Link Mural board in the comment section of this ticket_

**Comment by leahkeeler** [comment]
Closing - work completed already
