### ISSUE TITLE
Appointment request failing 

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#34695]
The following appt. req fails in vets-api:
{"kind":"cc","status":"proposed","locationId":"984","serviceType":"podiatry","comment":"test","contact":{"telecom":[{"type":"phone","value":"2566832029"},{"type":"email","value":"C_Natalie.Yun@cerner.com"}]},"requestedPeriods":[{"start":"2022-01-12T00:00:00Z","end":"2022-01-12T11:59:00Z"}],"preferredTimesForPhoneCall":["Morning"],"preferredLanguage":"English","preferredLocation":{"city":"Juneau","state":"AK"},"practitioners":[{"identifier":{"system":"http://hl7.org/fhir/sid/us-npi","value":"1669673596"}}]}

Here is the error:
{"errors":[{"title":"Bad Request","detail":"Cannot deserialize value of type `java.util.ArrayList<gov.va.mobile.vaos.v1.client.model.Identifier>` from Object value (token `JsonToken.START_OBJECT`)\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 336] (through reference chain: gov.va.mobile.vaos.v1.client.model.Appointment[\"practitioners\"]->java.util.ArrayList[0]->gov.va.mobile.vaos.v1.client.model.Practitioner[\"identifier\"])","code":"VAOS_400","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012846043V576341/appointments","vamfBody":"Cannot deserialize value of type `java.util.ArrayList<gov.va.mobile.vaos.v1.client.model.Identifier>` from Object value (token `JsonToken.START_OBJECT`)\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 336] (through reference chain: gov.va.mobile.vaos.v1.client.model.Appointment[\"practitioners\"]->java.util.ArrayList[0]->gov.va.mobile.vaos.v1.client.model.Practitioner[\"identifier\"])","vamfStatus":400},"status":"400"}]}

**Comment by ldelacosta** [comment]
Need to determine whether we need to address this fix. 
Also, will need to communicate to the VAMF team to see if this issue exists on their end. A possible JIRA ticket maybe created.

**Comment by ajmagdub** [comment]
Steps to reproduce:
1.  Login as Jacqueline Morgan
2. go to 'Schedule and health appointments'
3. click on 'Go to the VA appointments tool'
4. click on 'Start Scheduling'
5. click on 'Podiatry' the continue
6. Select a Date and 'AM' or 'PM' for best time to contact then continue
7. Select 'Cheyenne, WY' then continue
8. Click on 'Choose a provider'
8.1 Select  a provider
8.2 Click on 'Choose provider' then continue
9. Select 'English' as the preferred language then continue
10. Enter a comment then continue
11. Select a best time to call you then continue
12. click on 'Request appointment' 

The problem occurs when a selected provider is sent to VAMF. Currently the Vets Website, in the request body, sends the Practitioner Identifier element as a single object,  but the Practitioners Identifier should  a single item array as in the following example:
```
practitioners”: [
        {
            “identifier”: [
                 {
                   “system”: “http://hl7.org/fhir/sid/us-npi”,
                   “value”: “1639367600"
                 }
            ]
        }
    ] 

```
This modification will need be done in the Vets Web application (Vets API normally does not modify the request body from the Web site).
