### ISSUE TITLE
Integrate Teams into Triage Tooling

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#347]
## High Level User Story
As a VSP triage team member, I need teams building on the VSP to integrate into our triage tooling so that monitoring is consistent across teams.

## Hypothesis/(es)
**If** all teams are integrated into the same triage tooling **then** troubleshooting and triaging will be more timely and effective.

## Goals
All teams building on VSP are integrated into our triage tooling.

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## Definition of Done
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**

**Comment by alexpappasoddball** [comment]
Closing this ticket in favor of newly created epics during triage zenhub re-org
