### ISSUE TITLE
Adding [Pratap.singh@saic.com] to DSVA Slack

### ISSUE THREAD

**Issue by jlang10761** [department-of-veterans-affairs/va.gov-team#34719]
Please add Pratap.singh@saic.com to the channels below. He is with Coforma and will be providing general project support.
new user requests:

Are you requesting to add an individual as a: Multi-channel
What channel(s) do they need to be added to?
• cpm-public
• lcs-public
• cds-team
• Cds-tools-team
• Cpm-onboarding

**Comment by LEHigley** [comment]
done but couldn't add to cds-team or cpm-onboarding
