### ISSUE TITLE
[Bug] Higher Lever Review v2 - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#34714]
## What happened?
On Staging Higher Level Review form, the following content/styling anomalies were found:
1. **Issues eligible for review** page: Preamble paragraphs order didn't match mockup.
2. **Add-issue** page: Preamble paragraph content didn't match mockup.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test236@id.me` (Charde) [see [HLR Test Users doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md) (in private repo) for credentials]

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Issues eligible for review** form-page, completing any interim pages on the way.
- Observe that (1) the **preamble paragraphs**' order doesn't match mockup.
- Click **Add a new issue** link.
- On **Add-issue** page, observe that (2) the **preamble paragraph** content doesn't match mockup.

**Screenshots**
![hlr-bug-issues-preamble](https://user-images.githubusercontent.com/587583/147999251-abd10e19-d12f-4426-97f2-f5f6c2a2bd41.png)
![hlr-bug-add-issue-preamble](https://user-images.githubusercontent.com/587583/148099968-bbcd554d-1ba9-4876-89b4-06932094c0c1.png)

## Desired content/styling
- [ ] (1) Issues-page preamble paragraphs order should match [mockup](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/qeWk92n).
- [ ] (2) Add-issues-page preamble paragraph content should match [mockup](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/L0dAPoE).

**Screenshots**
![hlr-spec-issues-preamble](https://user-images.githubusercontent.com/587583/147999344-4030da84-aa60-4192-be64-c1cb7fc39d23.png)
![hlr-spec-add-issue-preamble](https://user-images.githubusercontent.com/587583/148099993-cb9d56f0-f47e-4b21-a473-3aeabcb44b0d.png)

## Acceptance Criteria
- [ ] [see **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
A fix has been made and is now available in staging. Thanks!

**Comment by tlei123** [comment]
Closing now.  Item #1 fixed, #2 now outdated.
