### ISSUE TITLE
[2/11/2022] Helpdesk Dashboard

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#34711]
No date set yet

Helpdesk Metrics Dashboard

**Comment by Cmjones233** [comment]
Broke out and built dashboard into 4 pages- summary, message request, user requests, support requests

**Comment by Cmjones233** [comment]
need verify table columns match with power bi

**Comment by Cmjones233** [comment]
fixed data connection for support requests friday 1.14

**Comment by Cmjones233** [comment]
met with Chance and Misti 1/20 and straightened out list so that they can be merged. that was successful. Updating board with notes from meeting 1/19

**Comment by Cmjones233** [comment]
Met with team to sort out manual spreadsheet 1/21. Next review 1/25.

**Comment by Cmjones233** [comment]
Dashboard posted for review 1/27. Data source fixed with power flow

**Comment by lindsay-insco** [comment]
Data pull issue. @Cmjones233 @chancetheoriginal - please expand

**Comment by Cmjones233** [comment]
Testing data flow 2/7

**Comment by Cmjones233** [comment]
data flow working and board up to date
