### ISSUE TITLE
Adding Rebecca Tolmach to DSVA Slack

### ISSUE THREAD

**Issue by nsmith1982** [department-of-veterans-affairs/va.gov-team#34727]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Good morning,

Please add Rebecca Tolmach (rebecca.tolmach@adhocteam.us) to DSVA slack as a full member.  Rebecca is a Backend Engineer joining the Platform's Backend Tools Team.  Please give her access to the following channels:

# vfs-platform-support
# vfs-all-teams
# vsp-tools-be

Thank you!

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
already a member?

**Comment by nsmith1982** [comment]
interesting, not sure how. Unless she came from another contractor who gave her access previously

**Comment by LizCallaghan** [comment]
I double checked, she is also already in all of the channels you requested.

**Comment by nsmith1982** [comment]
thanks!
