### ISSUE TITLE
Redirect Request: Massena VA Clinic to Potsdam VA Clinic

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-team#34725]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: as soon as possible but needs to be coordinated with CMS team immediately before the change is implemented

### Redirects 
Current URL  |  Redirect Destination or New URL
--- | ---
https://www.va.gov/syracuse-health-care/locations/massena-va-clinic/  |  https://www.va.gov/syracuse-health-care/locations/potsdam-va-clinic/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@brianalloyd @kelsonic This is good to go.  Please note the request to coordinate with CMS on the timing of this redirect.

**Comment by brianalloyd** [comment]
@kelsonic this came in for support, figured it might be a good change for a collaboration with yourself and @srsuddath on redirects.  LMK

**Comment by brianalloyd** [comment]
@JayDarnell I believe this redirect has been actioned.  Please close when validated.  Please reach out if you need anything else in support.

**Comment by kelsonic** [comment]
Redirect is in prod ✅
