### ISSUE TITLE
[FE] Day Of - Add time zone to appointment page

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#34730]
This ticket comes as a result of the UX review that was done on the day of check-in experience.  See this document:
https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1933420590

**Comment by mdewey** [comment]
This is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/34651 

Can we close this @julieadair1 ?

**Comment by julieadair1** [comment]
yep, closing.
