### ISSUE TITLE
Adding [individual] to DSVA Slack

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#34733]
Please add allexe.law-flood@adhocteam.us as a full member to DSVA Slack. She's a Senior Researcher for the Lighthouse program.

Add them to these channels:
#vsa-design
#vfs-platform-support
#feedback-backchannel
#vfs-test-accounts
#research-ops
#design
#api-coordination

Thank you!

**Comment by LizCallaghan** [comment]
done!
