### ISSUE TITLE
Update Product Directory with query listing Collab Cycle github tickets per product

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#34740]
## Issue Description
For the VA.gov Product Directory, we can have 2 links. The first shows Cycle status which would lead to the query results for the core gh tickets (AKA where the product is in the CC journey). The 2nd link would be governance status which would also lead to query results, but this time the open staging issues tickets for the product.

**Comment by shiragoodman** [comment]
Closing as this view was determined to be unnecessary per prototype review with @rroueche on 1/20/2022.
