### ISSUE TITLE
User Testing: Research Plan

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3474]
## User Story or Problem Statement
As a UX Designer, I need to create a research plan so I can document the research's purpose, goals, hypothesis, and user testing recruitment needs. 

## Goal
_A completed research plan sent to Perigean for user testing recruitment_

## Objectives or Key Results this is meant to further
- _User testing to validate the Medical Procurement Tool's design and/or uncover gaps, improvements, and pain points_

## Acceptance Criteria
- [ ] _Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)_
- [ ] _Review research plan with design team_
- [ ] _Send research plan to Perigean_
- [ ] _Add research plan to GH_

**Comment by rebeccawalsh** [comment]
In light of the new VSP research process, we will be running this plan/conversation guide by both Shawna and VSP before porting it over from google docs into GH markdown. So our deliverable right now is a link to the google document here: https://docs.google.com/document/d/1XjajdtjyKfd6B31IEYzbXxThN-ZsWBUsNsLLgV1XDwQ/edit

We anticipate a good deal of feedback in these first two checkpoints, so we're avoiding work duplication :)

@leahkeeler let me know if we need to provide a PDF of this WIP for any stakeholders who don't have access to google.
