### ISSUE TITLE
Update Storybook with information about using React bindings

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#34746]
## Description
This ticket is dependent on the React bindings documentation being added to design.va.gov as part of [this ticket](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/610).

In order to improve our developer documentation, we need to add information about importing and using components using React bindings to the Storybook stories for any components that need to listen to custom events or use props that are not a string or number.

## Details
What I would recommend doing is adding a note to the props where, if someone uses them, they would need to use the React bindings version of the component that points people to the documentation on design.va.gov.

For example, for the `va-alert` component, if someone wants to use the `onClose` prop and provide a function, they would need to use the React bindings version. So, in the description for the prop in Storybook, we could say "In order to provide a function to the onClose prop, you need to use the React bindings version of this component. Please see the documentation on the Design System website." with a link that points to the correct documentation.

## Acceptance Criteria
- [ ] Identify web components and props that would prompt the need to use the React bindings version
- [ ] Add text to the description of these props that points to the React bindings documentation on design.va.gov.

**Comment by caw310** [comment]
According to Brooks, use build data to add events and listeners to Storybook.

**Comment by andresriveratoro** [comment]
Brooks suggested https://stenciljs.com/docs/docs-readme as a possible solution
