### ISSUE TITLE
Offboarding of Gaida Escobar

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#34757]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Gaida Escobar
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Facilities, FE Engineer, 12/16/2021, GovCIO
- Please provide any type of access they may have and their GitHub username. 
  > ex: SOCKS, Pagerduty, Google analytics, etc.
  
 
## AC
*Performed by Platform team*
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack (if applicable)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-support/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights

**Comment by jennaouellet** [comment]
GA and Domo not applicable

**Comment by jbritt1** [comment]
No Sentry user found

**Comment by jbritt1** [comment]
YubiKeys not applicable to this user

**Comment by jbritt1** [comment]
No PagerDuty

**Comment by jbritt1** [comment]
No Datadog

**Comment by mleclerc00** [comment]
Removed from org -> https://github.com/department-of-veterans-affairs/github-user-requests/issues/9403
No aws
Removed from socks
