### ISSUE TITLE
Test App: Log in via IdB

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#34755]
##### Dependency: Create two test users in IdB
**Test user 1** has functioning credentials
**Test user 2** has non-functioning credentials

This test does not include username or password verification, it simply tests the pathway after verification.

##### 01
Test users can access a login module
 - **GIVEN**   I am a test user
 - **WHEN**  I navigate to the test login page
 - **THEN**  I see a button - "Log In"
 
<img src="https://images.zenhubusercontent.com/60099ba779174e24ae511332/ee61feaa-558e-4e06-a9a4-c7b31484800d" alt="wireframe" width="350"/>

##### 02
When a test clicks "log me in", their request is sent to the identity broker.
 - **GIVEN**   I am a test user on the test login page
 - **WHEN**  I click "log me in"
 - **THEN**  My information is sent to the identity broker and either scenario **AC06** occurs.  

##### 03
Test User 1 will see claims from the verified token 
 - **GIVEN**   I am a test user on the test login page
 - **WHEN**  I click the "Submit"
 - **THEN**  I am served a page with claims from the authenticated token

**Comment by ken-non** [comment]
there is no username or password - just a button, updating AC

**Comment by ken-non** [comment]
login works, but logout does not. 
written in react, node.js app needs to be docker-ized to launch in K8.

**Comment by dginther** [comment]
Adds manifest to manifest repo:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/273

Adds app to ArgoCD:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/275
