### ISSUE TITLE
Design for Cerner Medical records link

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34763]
## Issue Description
The current VA blue button medical records widget will not provide the best experience for Veterans receiving care at Cerner facilities. Until we can provide a more elegant solution, we can replace the widget for a simple link [to view clinical notes via the patient portal](https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes).

### Other relevant work
- #31109 added redirects to the a general login page for the Cerner portal from within the "Manage your health online" box based on a Cerner flag in CMS identifying systems which have cutover. 
- #33740 will update the general links with task-specific deep links.

**This work will block the release of the hardened medical records page.** 

### Current experience

Example page: [Spokane Medical records](https://www.va.gov/spokane-health-care/medical-records-office/)
![image](https://user-images.githubusercontent.com/55411834/146585204-f145570b-1d52-4ff3-acfd-827a979eadb2.png)

### Expected experience

Something similar to:
![image](https://user-images.githubusercontent.com/55411834/146585141-6f36f973-a661-43b9-95db-90383d48aab3.png)

## Tasks
- [ ] Review design system for options which can be used to direct Cerner patients [to their relevant portal](https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes) to request medical records 

## Acceptance criteria
- [ ] Cerner patients have way to link to Cerner portal to request medical records

([UXPin to Cerner portal link design is here](https://preview.uxpin.com/42f2f277005d817321187dda7b843618aa2b09aa#/pages/146742657/documentation/no-panels?mode=i) - Nick O.)

**Comment by nicko-amida** [comment]
@mmiddaugh [UXPin to Cerner portal link design is here](https://preview.uxpin.com/42f2f277005d817321187dda7b843618aa2b09aa#/pages/146742657/simulate/no-panels?mode=i)

**Comment by mmiddaugh** [comment]
looks great! Thank you!
