### ISSUE TITLE
[Bug] O&E - Custom-date-range filter finds no events when Start-date selection is present/past date

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#34762]
## What happened?
On **[Staging Outreach events](https://staging.va.gov/outreach-and-events/events/)** page, **Custom date range** filter didn't find any events when **Start date** was current or past.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [n/a]

## Steps to Reproduce
- URL: https://staging.va.gov/outreach-and-events/events/ .  Note that as of 1/4/2022, Staging should display All-upcoming events from 1/5 to 3/8.
- From **Filter by** dropdown, choose **Custom date range**:
  - For **Start date**, choose a **past** date or **today**.
  - For **End date**, choose a date **after 3/8**.
- Click **Apply filter**.
- Observe that no events are found, even though there actually are events within range [as seen in initial All-upcoming results].  [Choosing 1/5 or later Start-date would display all the events again.]

**Screenshot**:
![o e-bug-custom-date-range](https://user-images.githubusercontent.com/587583/148137155-dbb2d90e-3fa2-4c68-a515-5a265776889c.png)

## Desired behavior
- [ ] Custom-date-range events should be listed even with Start-date in the past or present (today).

**Screenshot**:
![o e-spec-custom-date-range](https://user-images.githubusercontent.com/587583/148137244-08425cd6-78ee-4ea2-9ccb-95968157a2b0.png)

## Acceptance Criteria
- [ ] [see **Desired behavior** above]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
Thanks @tlei123 we found this one earlier as well and are address in ticket: #34767 which I'm linking here as well.

**Comment by tlei123** [comment]
Closing as duplicate of #34767.
