### ISSUE TITLE
Facility operating status design iteration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34761]
## Issue Description
Following the design intent meeting today, we need to make some slight iterations in the design

**Takeaways from meeting**
Limited services and hours should use a yellow background with a warning alert icon
Square corners should be used since rounded = interactive and we have a mix
Need to get accessibility input on active link/underline
The chevron for "Locations" can be dropped if text acts as a link.

**Takeaways from conversation with Angela**

- Placement under the name gives enough context
- operating status display should be coded as a link if it is intended to take the user somewhere. Clicking on it should open in the same tab (user will need a way to get back via back button or breadcrumb. Focus should move to pertinent area on the new screen.
- Facility Locator is not currently announcing the operating status to screen readers.
- Consider aria live region so details are announced (may want to also consider polite)
- Difference in urgency level (informational vs alert) can be included in screen reader announcement

We should inform group of design designs in advance of staging review.
---
## Tasks
- [ ] Update UX pin based on feedback above

## Acceptance Criteria
- [ ] Spec incorporates feedback and is ready for FE implementation

**Comment by mmiddaugh** [comment]
[UX pin](https://preview.uxpin.com/ad1daf77e161cbde903ca3cbe0b65177a7e7bdf2#/pages/144397776/documentation/no-panels?mode=i)

**Comment by nicko-amida** [comment]
@mmiddaugh Hey, here's a better [link for the UXPin](https://preview.uxpin.com/ad1daf77e161cbde903ca3cbe0b65177a7e7bdf2#/pages/144397776/documentation/no-panels?mode=i), with updated documentation.
