### ISSUE TITLE
Access for Devon Hills

### ISSUE THREAD

**Issue by devonjhills** [department-of-veterans-affairs/va.gov-team#34783]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Devon Hills

### Your Email

devon.hills@adhocteam.us

### Name of Your Team

Claims and Appeals, Frontend Engineer, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxq/bgTbz5L0l2xyt1m3vFVa+2VreKqhNW1AsP8DcSCabuMJTHBmZzLVOJ1gWg49isomjFTnycVudzW8b63wN9bMBhAiv5UPZfP2Dd3s9iU2L6Z44Yj5T7QnKVVK2cC+VBxfz/r+ip5rutewMXrPN4EKEIC60DUQebhVqz4HBIhTkIs/kfoeKuMuHFJF/+A+TyJgw/wBdJ6HNZBAC6nNaqiAQG1a8N9gYlY8SGOWc4rIme1nibokfezWQzvojq4SdfNNBNi2lrkvL9/Onum5uL2gQl0BStzFsfFg0+VXcV3Fhh/ajzEc+4VoeB5F+HmPoEuK5M1lpml0qnFg1+HMpjsCn5T8ohEEZwVZU4cYJ8Hvyu+7PyPjl3e0iXedjkyIEH7vZAvdl49RgdGqKIvFXaiKW7NUGWlYC12KH2pqUU/ExeCgkE6SmRde7wMqPIfbr0IJcQlON8RTbqGoOLIFzTghkQ8fLbqQqai9ly6mHfmFqwKGVdva+KbYKCO6Vm6Rc= devonhills@Devon-Hills-MacBook-Pro.local

**Comment by mleclerc00** [comment]
Hi @devonjhills 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
