### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#34798]
## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [X ] Google Analytics

## 2. User Email Address to Receive Access - Will post on /support/Analytics

---

### Definition of Done
- [x] Provide access to user
- [x] Ensure user received email confirmation

**Comment by jennaouellet** [comment]
Access has been granted
