### ISSUE TITLE
LINTER: Troubleshoot error display issues

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#34792]
# User story

As a Platform website author, I need to see all the error messages so that I can remediate my content.

# Tasks

- [ ] (Amy) create QA checklist, send to Samara on Thurs
- [ ] (Amy) confirm if there's something off with YAML syntax
- [ ] potentially contact k15t

# Acceptance criteria
- All content errors trigger linter error messages. 

# Reference info
- n/a

**Comment by lianilychee** [comment]
1/6 Thurs:
* blockers yesterday:
  * I missed a page, will do that before passing to Samara
  * will continue to troubleshoot independent of Samara's QA
* request: take a quick look at checklist

**Comment by lianilychee** [comment]
1/10 Mon:
- today: 
  - Thinking can get through 6 of the color-coded chunks
  - Create own page with errors

**Comment by lianilychee** [comment]
1/12 Weds:
- Today:
  - Amy 
    - wants to address what Samara found
    - gotta draft message to k15t, will share in Slack channel once drafted
  - Samara
    - found out: 
      - enable plugin to access it
      - linter didn't flag errors right away, might need refresh the page
    - today: fill in the errors from checking, onto the spreadsheet

**Comment by lianilychee** [comment]
1/13 Thurs:
- Done
  - Wrote up the message
- Today
  - Need to get the screenshot

**Comment by lianilychee** [comment]
1/14 Fri:
- Done:
  - Amy sent help message to k15t
  - Samara sent further glitches to Amy
- Today:
  - Amy continuing to troubleshoot given what Samara sent

**Comment by lianilychee** [comment]
1/19 Weds:
- was focused on demo and internal The So Company work
- will return to this tmr, and fairly certain that case sensitivity was culprit here, need to verify with k15t

**Comment by andreahewitt-odd** [comment]
Closing because there's not enough information to work on this.
