### ISSUE TITLE
[Research] My VA - Payment Information and On-site Notification: Complete research synthesis

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34802]
## Background
We have conducted our research sessions, shared the topline summary, and gained feedback.
We now need to finalize the research synthesis.

## Tasks
- [x] Create a final synthesis, incorporating research findings, recommendations and team feedback (if applicable)
- [x] Share summary with the team

## Acceptance Criteria
- Research synthesis is completed and shared

**Comment by andaleliz** [comment]
@Samara-Strauss and @hdjustice [the payment info synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/findings.md) is ready for your review! I'm using a new markdown editor so please let me know if you see any weird formatting things that I didn't catch.

I'll move this into validate as I await your feedback and edits.

Thanks!
Liz

**Comment by Samara-Strauss** [comment]
Liz, this report is so excellent. It is so thorough and clear. Amazing, amazing work!!

### Research goals

> Starting up, Putting down roots, and Retiring

This is from a journey map, right? If so, can we link to it?

### Recommendations

> Create logic so that alerts can only be permanently dismissed once the action is addressed, rather than by a person’s action.

I would be interested if people felt this way if the notification was part of a more robust notification center. Maybe? But maybe not (thinking how notifications are handled on Facebook, Twitter, etc). I'm hesitant to actually follow this recommendation given (1) it would be programmatically complex and (2) the functionality we were testing is a very MVP representation of what will likely be larger notification center. I think all the feedback makes a ton of sense given when people saw, but I want to consider it in a larger context.

> Include amount of remaining education benefits and a link to information about how what’s left in the Benefit payment and debt section.

We will definitely add more robust functionality for education benefits when the edu team is able to support us in this effort.

**Comment by Samara-Strauss** [comment]
Oh, one more thing -- we should probably have a quick regroup to talk through what updates are actually happening more immediately as a result of the research and what are longer term/not right now recommendations.

**Comment by andaleliz** [comment]
Thanks so much @Samara-Strauss! I'm thrilled that you are happy with the report.

>This is from a journey map, right? If so, can we link to it?

Yep, added the link.

>I would be interested if people felt this way if the notification was part of a more robust notification center. Maybe? But maybe not (thinking how notifications are handled on Facebook, Twitter, etc). 

Same here! I think we got good data around this, but would really love to revisit with folks who _actually_ have debt and context around whatever the notification is we're showing them. And in a scenario where we have more than just one notification. Almost all the participants were speaking hypothetically.  I do think there's a difference in dismissing social media notifications vs something telling you you have debt with a government organization.

>I'm hesitant to actually follow this recommendation given (1) it would be programmatically complex and (2) the functionality we were testing is a very MVP representation of what will likely be larger notification center.

I knew in writing it that it may not be feasible for MVP, or at all, but I wanted to capture it as a recommendation based on what we learned in the research. I clarified that in the next steps portion of the doc, which brings me to my next comment...

> we should probably have a quick regroup to talk through what updates are actually happening more immediately as a result of the research and what are longer term/not right now recommendations.

Yes, good point. Heather set something up for tomorrow - to aid our conversation, I updated [the next steps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/findings.md#next-steps) portion of the doc with what I'm thinking and start our conversation. I'll update that once we're all in agreement.

**Comment by Samara-Strauss** [comment]
Sounds great, Liz! I'm really thrilled with this work, and to be clear, I know that the recommendations are kind of a mix of things, and I appreciate that you included them all. We'll figure out what we're taking immediate next steps on when we meet, but no need to remove anything from this doc that is a more long-term recommendation.

**Comment by hdjustice** [comment]
@andaleliz @Samara-Strauss @tmitchellgcio 
FYI - based on the near-term MVP findings, I created tickets to address them (listed below).  We have the synthesis review on Wednesday 2/2, where we can talk more through these.

- [#35823 in progress](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35823) Put the travel reimbursement link under health care
- **No ticket needed** Keep onsite notifications at the top of the page, and within sections.
- [#36184](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36184) Update the number of debts in the onsite notification.
- [#36188](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36188) & [#36190](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36190) Display a “you have no debt” confirmation message in Benefit payments and debts, and possibly also a link to debt management so Veterans can get more information.
- [#36191](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36191) & [#36180](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36180) Add a heading for the onsite notification section at the top of the page, when there is a notification to display.
- [#36182](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36182) Iterate on the alert design to improve usability for people with low vision.
- **Ticket TBD** Validate changes with Veterans in a combined UAT/usability session

**Comment by andaleliz** [comment]
Moving this back to in progress since I'm working on the findings deck.

**Comment by andaleliz** [comment]
[Findings deck posted in our folder on GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/my-va-payment-onsite-notification-research-findings.pptx)

**Comment by hdjustice** [comment]
Looks so great @andaleliz !!

**Comment by Samara-Strauss** [comment]
Fantastic! Great work, Liz!

**Comment by andaleliz** [comment]
Should we invite anyone from the debt or VA notify team as optional to our read out Wednesday? I was thinking I'd share the link to the deck with them, at a minimum.

**Comment by Samara-Strauss** [comment]
It can't hurt!

**Comment by hdjustice** [comment]
I will them.  Thanks!
