### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#34808]
## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ X] Google Analytics

## 2. User Email Address to Receive Access 
 1. This issue's link:  
 2. Emails that need access: sending via slack

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jennaouellet** [comment]
Lori linked her va.gov email to Google - access all set
