### ISSUE TITLE
[FE] My VA - Payment Information: Development for error states

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34806]
## Background

Technical discovery is now complete (#[34704](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34704)), and we are ready to implement the error states expected for the payment information section

Reference **[Frontend document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)**

## Tasks

- [ ] Implement error states for failed calls on payment information and debt information

## Acceptance Criteria

- Benefit payments and debts section will have applicable error states when we receive failures from the payments and/or debts endpoints

**Comment by tmitchellgcio** [comment]
@hdjustice yes an empty array is different from an error response. They should have two different response statuses

**Comment by hdjustice** [comment]
Great @tmitchellgcio! Thanks so much!

**Comment by hdjustice** [comment]
@tmitchellgcio - I am tagging you on a slack message too.  Because we are using the _old_ error styles in production today for an actual error, and we are changing the notification/alert style (#36487) to use the warning style, we don't want both situations using the same style.
This means we will retain the old error style on **actual errors** for now (this ticket will use va-alert-error).  
We will use the warning style (va-alert-warning) for the notifications/alerts. 
Liz will update the mockups to match what we have come up with.
cc: @andaleliz @aagosto90 - in case I mis-stated.

**Comment by andaleliz** [comment]
Hi! I have a follow up question from [the slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1645034247155299) I started.  

Are there any error states we need to account for where an error occurs that causes us to not show the section (when maybe we should) and we need to show an error message elsewhere on the page?

**Comment by tmitchellgcio** [comment]
@andaleliz the only error state would be if it can't be reached because the server is down. Other than that I believe it should just show an empty array.

**Comment by hdjustice** [comment]
Did not complete in sprint 67 due to technical issues encountered during development testing and code merging.  Will complete in sprint 68.

**Comment by hdjustice** [comment]
Reviewed PR and code changes.
