### ISSUE TITLE
Implement updated design for event detail page v2

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#34815]
# Description

> @callen2563 and I needed to update the event detail page design to resolve the Add to calendar ability, so we came up with this, which will make it so that there's 0 javascript required and it'll be super easy to maintain + quick to implement.

## Design

![Outreach & Events - Desktop - detail.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/102ad4bb-a50c-410a-8dfb-4d21e132ad91)

![Outreach & Events - Mobile - detail - more occurrences - show more.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/e4eba1d9-90e3-43c6-85c0-f0c33ba3bb76)

## Acceptance Criteria

- [ ] Tweak event detail page v2 to match new design

**Comment by brianalloyd** [comment]
Update is completed, closing this ticket in support. Great work on this @callen2563 love the team work and collaboration here.
