### ISSUE TITLE
526 Product Flowchart Review

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34819]
## Issue Description
We need to have up-to-date documentation outlining product flow, decision trees and checks made at each step of the form.

---
## Tasks
- [x] Review and update existing [product flowchart](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/workflow-diagram.png). 

## Acceptance Criteria
- [x] Document updated and saved in GitHub
---

**Comment by Mottie** [comment]
@vhenry07 Is this what you mean? https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/526-overall-flow.md. If so, then we can close this ticket! 😸

**Comment by vhenry07** [comment]
Yes, thank you Robin!
