### ISSUE TITLE
Automation Data Discovery

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#34820]

**Comment by Cmjones233** [comment]
researching automation potential with python

**Comment by Cmjones233** [comment]
found solution to refresh pbi desktop files via python. looking for way to publish to specific workspace

**Comment by lindsay-insco** [comment]
@Cmjones233 any updates?

**Comment by Cmjones233** [comment]
waiting for python app approval

**Comment by Cmjones233** [comment]
python has been downloaded on computer, need to get interpreter

**Comment by Cmjones233** [comment]
interpreter added, trying to create virtual environment to begin testing

**Comment by Cmjones233** [comment]
requesting gateway for clinical db.

**Comment by lindsay-insco** [comment]
Requesting follow-up

**Comment by Cmjones233** [comment]
Request #13155 pending review as of 1/13

**Comment by Cmjones233** [comment]
Request #13155 still pending review as of 1/24

**Comment by Cmjones233** [comment]
Request #13155 still pending review as of 1/27

**Comment by Cmjones233** [comment]
comment from BISL team on 1/31 below. I reached out to Ryan directly to explain i have access to the db but just needed a gateway. He responded in teams  that he read the request wrong and would take another look.

**Comment by Cmjones233** [comment]
BISL has approved. Waiting for Andy to get the server account info so that BISL can complete

**Comment by Cmjones233** [comment]
Dashboard switched to scheduled refreshed. Waiting to confirm they don't fail

**Comment by Cmjones233** [comment]
Gateways set up and working
