### ISSUE TITLE
[Content style guide] Content doesn’t align with VA.gov voice and tone content principles. (05.04.1)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34825]
#### VFS team name

Virtual Agent 

#### VFS product name

Chatbot - Pilot

#### Point of Contact/Reviewers (Practice area)

Randi Hecht (Content)

---

### Platform Issue

Content doesn’t align with VA.gov voice and tone content principles.

### Issue Details

This is an awkward sentence construction: You can tell us how you feel about this virtual agent when you’re finished by clicking on the link included in your recruitment email and tell us what you think.

<img width="331" alt="Screen Shot 2022-01-06 at 9 30 45 AM" src="https://user-images.githubusercontent.com/48728214/148398565-d130df63-d3c1-4235-8491-a8ce9d5a144d.png">

### VA.gov Experience Standard

05.04

### Platform Recommendation

Change the sentence to the following: You can tell us what you think about this virtual agent when you’re finished by clicking on the link included in your recruitment email.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket. 

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by allison0034** [comment]
This ticket has been reassigned from CCIssue00.00 "No VA.gov Experience Standard for the issue found" to CCIssue05.04.1 "Content style guide". No VFS action is needed.

**Comment by Joy-Elizabeth** [comment]
@MarciMcGuire This was an open ticket in our most recent governance cycle, though it is over a year old. Since this ticket,  our team has changed the content to the following. Please confirm that this current content is approved so we can either **1)** close this ticket as complete, and/or **2)** open a ticket specific to the current content.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98479064/d236259d-1cdc-4fd2-b2cf-25124ccfd11f)

**Comment by Joy-Elizabeth** [comment]
> @MarciMcGuire This was an open ticket in our most recent governance cycle, though it is over a year old. Since this ticket, our team has changed the content to the following. Please confirm that this current content is approved so we can either **1)** close this ticket as complete, and/or **2)** open a ticket specific to the current content.
> 
> ![image](https://private-user-images.githubusercontent.com/98479064/293089933-d236259d-1cdc-4fd2-b2cf-25124ccfd11f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDYxODQsIm5iZiI6MTcwMzcwNTg4NCwicGF0aCI6Ii85ODQ3OTA2NC8yOTMwODk5MzMtZDIzNjI1OWQtMWNkYy00ZmQyLWIyY2YtMjUxMjRjY2ZkMTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE5MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZjNiZGZjMGRhYWM5MDEwNzg3N2FlMzI5ZWMyNmFlYWUwZTllODcwYjQ5YmVmM2QyZDM2MDFlZWRiNjhmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.258InGThrfh_22koPeLpVsJdLhsPOaYfe35n9-aQmWU)

@shiragoodman

**Comment by MarciMcGuire** [comment]
@Joy-Elizabeth hi! I'm not quite sure how I got associated to this ticket as I've never been on the virtual agent/chatbot team or content team.  

I just wanted to let you know so you can see if there is someone else who can approve.  Thank you!

**Comment by Joy-Elizabeth** [comment]
@shiragoodman please advise if we should **1)** close this ticket as complete, and/or **2)** open a ticket specific to the current content.

**Comment by Joy-Elizabeth** [comment]
@shiragoodman Just want to bump this up for your response. I will send you a slack message as well.

**Comment by Joy-Elizabeth** [comment]
Closing per lack message with @shiragoodman .

**Comment by allison0034** [comment]
@Joy-Elizabeth Shira has been out sick. Has the new content been approved by CAIA and did the Governance team see it?

**Comment by shiragoodman** [comment]
thanks @allison0034  - Joy and I connected offline. we closed out the ticket as more recent updates of the Chatbot have since gone thru Collab Cycle.
