### ISSUE TITLE
Access for Csaba Nemeth

### ISSUE THREAD

**Issue by cnemeth** [department-of-veterans-affairs/va.gov-team#34839]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Csaba Nemeth

### Your Email

csaba.nemeth@gcio.com

### Name of Your Team

vsa-claims-appeals, backend engineer, GovernmentCIO

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmw9wQho406jKBt32M08rrHrf9toKA/JgNSJIiUjId4xUKWXnJPLZJvJWIVzN3b2eqpBYrYuVPKzrGZtDE3GCWgnCpg2Sd59362p4s/9zmVQfvqZQ9EhdqnbqxlGloJi5TSmF1gFCPylYyfs1duHj9+JxIsw3SQtjRnaHfzm3i9WAKY0XouJGqIii/3/aRdFcTWXQwEw5kzPKd0EczMJUCVR4gaeTypxByZU/6AevENKAgCactiliDMNmxig3iFdyfqQj9VY8KJgAGeCDVYzQzg966AyZBJk3aDSmmZeAE0dxmgEQxYxofNvIGPB1Gtw8OeYPiAA3e/8ChmrFonpWCnwNomWifW0Zl3irIupKBwh1PGRzFA+4SKceu/6hWrnLrLIikP0IYsRIwaCmvENcQAK2ypkNBDP/SFJ1CAfZCkVAOXpz2BuHwcODTrQIuOYmzCOWUPNvyL7K0UtqJZod0C0XZ5skxHvpR7oIE9PaKDKdGXs/yCHbfz1nwHHqgasc= cnemeth-c02g20zyml7j@CnemethML7JsMBP

**Comment by mleclerc00** [comment]
Hello @cnemeth 

you will need to provide a ssh key to get socks access

This will be a part of the [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

**Comment by cnemeth** [comment]
@mleclerc00 Updated request with ssh key.
