### ISSUE TITLE
Update current prod deploy to create new build/release

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34836]
## Description

The [current daily production](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/daily-deploy-production.yml) deploy grabs the latest release created by the most recent commit into  `master`. Once we turn on single app builds, the latest commit may not contain a full build, so we need to update the deploy to create that.

An example of a full build can be found in the [CI workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/continuous-integration.yml#L56).

## Definition of Done

- [x] Daily production deploy for vets-website updated to run a full prod build
- [x] Daily production deploy for vets-website updated to create a new release from the full build

**Comment by mydesignrocks** [comment]
dev and staging manual build merged and tested
auto deploy for prod merged

**Comment by mydesignrocks** [comment]
jobs ran successfully, closing the issue.
