### ISSUE TITLE
Look into improving the stability of self-hosted runners

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#34841]
We're using some self-hosted runners for out CI pipeline in github actions that have presented some flaky behavior.

This is a ticket to look into that and either implement fixes or create recommendations.

**Comment by timwright12** [comment]
Related ticket: https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/31911

**Comment by mydesignrocks** [comment]
Couple of things noticed and marked for improvement:
1. dependabot security credentials inclusion for the respective AWS service account secrets, that the action tries to get from the secrets manager
2. allocated different set of runners for vets-website and content build, so there is enough runners for apps using vets-website as its ASG definition. (noticed running out / conflict of runner availability)

**Comment by mydesignrocks** [comment]
looking to include a timely job to cleanup the storage on self-hosted runners

**Comment by mydesignrocks** [comment]
going into support mode on this, will tackle as and when there is a need that arises.

**Comment by timwright12** [comment]
@mydesignrocks can we document what was completed on here and if there are open items that remain?

**Comment by mydesignrocks** [comment]
sure @timwright12 let me gather the details and see what was done over the course of time.

**Comment by mydesignrocks** [comment]
following were addressed: 
1. dependabot security credentials inclusion for the respective AWS service account secrets, that the action tries to get from the secrets manager
2. allocated different set of runners for vets-website and content build, so there is enough runners for apps using vets-website as its ASG definition. (noticed running out / conflict of runner availability)
3. datadog monitoring / alerting
4. ASG limits increased within the desired/min/max values
5. made some re-order adjustments as to when the runner needs to be up and when can be shut down
6. looking OK so far with a couple of expected networking glitches when github tries to connect to aws runners
