### ISSUE TITLE
Plan to track KR1 -- Greater than 20 unique QA dashboard users on average per sprint

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34854]
# Description
We need to create a plan for tracking and reporting the number of unique users viewing the QA dashboard each sprint.

# Acceptance Criteria
- [x] A plan to track unique users visiting the QA dashboard is defined in this ticket
- [x] A plan for how to visualize the number of unique users visiting the QA dashboard is defined in this ticket

**Comment by CBonade** [comment]
Our general activity log in Domo does not seem to track unique users of any sort, just total visits and even that doesn't auto-total without an exported spreadsheet. Some research into Domo solutions points to an app called DomoStats that allows you to pull stats about all your domo pages, cards, and more. Using this, we can generate a visualization that will track our usage and report it. We can place this card on a new dashboard that tracks usage statistics for our QA dashboard and add other metrics over time such as which cards are being utilized most by our users.

**Comment by pjhill** [comment]
Done
