### ISSUE TITLE
Implement KR1 Tracking for (Greater than 20 unique QA dashboard users on average per sprint)

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34857]
# Description
Implement the plan defined in the [planning ticket](https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/34854).

## Tasks
- [ ] Use the plan defined in the planning ticket to create this card / visualization
- [ ] Create some explanatory text to describe how the dataset is collected and why it is visualized how it is

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/2074254045 Here's our new dashboard, complete with KR1 tracking card on it. The Card defaults to the last two weeks, as Domo doesn't really have a way to implement "sprints". Possible future initiative, if we can create a lookup table in BigQuery for sprint start and end dates, we can likely join on that data set and only show the most recent sprint.

**Comment by pjhill** [comment]
This is a good beginning to our KR visualization board.
