### ISSUE TITLE
Implement KR2 Tracking for (Greater than 8 products are viewed in QA dashboard each week)

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34858]
# Description
Implement the plan defined in the [planning ticket](https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/34855).

## Tasks
- [x] Use the plan defined in the planning ticket to create this card / visualization
- [x] Create some explanatory text to describe how the dataset is collected and why it is visualized how it is

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/2074254045/kpis/details/1964053752

I altered this card slightly to suit these needs. The card will only show dashboards that have at least 1 unique user. I also changed the timeframe to the most recent 7 days. If an existing dashboard does not have a line on the graph, it means it hasn't had any visitors this week.
