### ISSUE TITLE
Plan to track KR2 -- Greater than 8 products are viewed in QA dashboard each week

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34855]
# Description
We need to create a plan for tracking and reporting the number of unique products being visited in the QA Dashboard.

# Acceptance Criteria
- [x] A plan to track which products are viewed in the QA dashboard is defined in this ticket
- [x] A plan for how to visualize the number of products viewed in the QA dashboard is defined in this ticket

**Comment by CBonade** [comment]
Domo provides data for dashboard usage as part of DomoStats. We can create a chart that will show how many visitors visit each dashboard over the course of a week, and then filter this chart by requiring that they have more than one visitor to show up. This will give us a snapshot of how many are being visited each week.
