### ISSUE TITLE
Plan to track KR3 -- Greater than 10 products have a custom QA product view

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34856]
# Description
We need to create a plan for tracking and reporting the number of products that have a custom QA product view available for team use in Domo.

# Acceptance Criteria
- [x] A plan to track how many products have a custom QA view in Domo
- [x] A plan for how to visualize the number of products with a custom QA view in Domo

**Comment by CBonade** [comment]
Did some research into this today and what our options might be. I feel that the only way we may be able to get information about how many of these pages exist and/or how many of them are being accessed, is we need to have separate pages for each product. The separate pages could share cards that would reflect shared changes from a central location. These pages would mostly serve 2 purposes:

1) A set of default filters that apply relevant to that product
2) A tracking mechanism for us to gauge activity

We'll need to decide if this is the way we want to go, but from what I've looked at I can't think of another approach that makes sense for our goals we are trying to accomplish.

**Comment by CBonade** [comment]
Now that we have our dashboards as separate pages, we can easily count them and keep track of them. We plan to list these dashboards on the main QA Dashboard splash page, and could consider numbering them for easy visibility into how many we have. If desired, we could create an additional card to display this information.
