### ISSUE TITLE
Implement KR3 Tracking for (Greater than 10 products have a custom QA product view)

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34859]
# Description
Implement the plan defined in the [planning ticket](https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/34856).

## Tasks
- [x] Use the plan defined in the planning ticket to create this card / visualization
- [x] Create some explanatory text to describe how the dataset is collected and why it is visualized how it is

**Comment by CBonade** [comment]
We have also changed our default QA Dashboard splash page to have a table of contents, that we can number if we wish to. No card has been created at this time, but we could create a card to display a count of dashboard products if we wish.
