### ISSUE TITLE
Update E2e test execution based on outcome of QA standards team discussion

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34866]
## Description

Coming out of our meeting with @pjhill and @JoeTice we offered to create an e2e test run that is connected to the deploy of a single app, so we don't have to run a full test suite in master CI for single app build/deploys.

While we don't have single app deploys active in master yet, this functionality will be a blocker once we do, so we want to get that prototype out the door quickly.

There should be a separate workflow created that triggers at the end of a single app deploy; this workflow should run a full build from the commit that triggered the run (the single app build commit, not latest master). A full e2e test suite should be run, and #status-vets-website should be alerted if a test were to fail. 

## Definition of Done

- [x] New workflow created to run e2e test from a commit (if one is provided)
- [x] New workflow should be triggered at the end of a master CI run by allowedlist apps (or we can add it to the end of the daily deploy - either way, we just want to test that it works)
- [x] Slack is alerted to failures

Once this is up and running we will need approval from @pjhill and @JoeTice so they can allow test selection in master for single app build.

**Comment by theodur** [comment]
I created a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20205) for the prototype of this new workflow. I have it in a draft state working in the branch based on testing changes

**Comment by theodur** [comment]
The PR for the [E2E workflow](https://github.com/department-of-veterans-affairs/vets-website/actions/workflows/e2e-tests.yml) prototype was merged, and is successfully running. Here is an [example run](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/1860084843).

It runs on each commit that completes CI in `master`. Once triggered, the workflow will decide whether the commit is a single app build or not. If it is, the full Cypress test suite will be executed. If not, the workflow will cancel itself.

**Comment by theodur** [comment]
Closing this ticket out, since the workflow has been monitored and working as expected over the past few weeks
