### ISSUE TITLE
Update unit test for master build to run only for changed apps

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34865]

**Comment by timwright12** [comment]
Noting that we also need to rework the coverage report generation and upload (S3 and Big Query)

**Comment by theodur** [comment]
After [confirming](https://dsva.slack.com/archives/C01CHAY3ULR/p1646929532881199) with the QA standards team, we should be okay to enable unit tests on only changed apps in `master` without any changes to the Big Query reports.

For our S3 coverage report upload, we'll just need to skip uploading for changed app builds. So the `Upload coverage report to S3` step in the `Unit Tests` job in [continuous-integration.yml](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/continuous-integration.yml) will only run for full builds.

**Comment by theodur** [comment]
Opened a PR for enabling unit tests for changed app builds in `master`
https://github.com/department-of-veterans-affairs/vets-website/pull/20480

**Comment by theodur** [comment]
The PR has been merged and confirmed working 🚀.  We already had our first commit in `master` that ran unit tests on only the changed app: https://github.com/department-of-veterans-affairs/vets-website/actions/runs/1965573846

Closing this out, but will continue to monitor ✅
