### ISSUE TITLE
Create test plan

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34864]
A test plan is needed for E2E testing for builds of only changed apps (in master). 
The following test plan can be used/iterated on - https://docs.google.com/spreadsheets/d/1KxJpc6a7XeJOQVG9C1IGQF6SnQsRMvj3WoaOz0bhbAs/edit#gid=0

**Comment by theodur** [comment]
I added a customized testing plan for the changed app builds in master epic
https://docs.google.com/spreadsheets/d/1Lz3cfJhs_oorT8mk5yEMwcpEZWPToFsCQZgChGH31DE/edit?usp=sharing
