### ISSUE TITLE
Update GitHub Actions jobs for changed apps build in main (master) branch

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34868]

**Comment by theodur** [comment]
I merged a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20680) for updating the necessary jobs in GitHub Actions for changed app builds. The updated jobs were:
- `contract-tests`
- `linting`
- `security-audit`
- `testing-reports-contract-tests`
