### ISSUE TITLE
Update appointment list page to match latest mocks

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#3487]
We have new mocks for the different appointment list cards.

Main changes:

- Top color bar, instead of color icon
- Reordering of top level information
- Cancel button becomes a link at bottom
- Show more/less pattern uses AdditionalInfo link

Note:

- Use the "appt created outside of VAOS" design for VA appointments. The other variant is in a separate ticket.

Screenshots to come

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/68898622-cf24a800-06fd-11ea-991b-030a658b1f70.png)

**Comment by rtwell** [comment]
canceled states:

![image](https://user-images.githubusercontent.com/12564977/68899209-25461b00-06ff-11ea-9f8e-b26854f5a80a.png)
