### ISSUE TITLE
Adding External Clarity Team Managers to DSVA Slack

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#34889]
# Description

My Clarity contract managers wanted to be apart of the internal clarity team group.   I am unsure if this is outside of the rules.

Single Channel:   clarity-team-internal

Description:

They are Clarity Our Sub-Contractor managers for each of the persons in the single channel clarity-team-internal

- Please add cbabst@clarityinnovates.com  as a single-channel guest to clarity-team-internal
- Please add  tbaumgartner@clarityinnovates.com  as a single-channel guest to clarity-team-internal
- Please add  cpaul@clarityinnovates.com as a single-channel guest to clarity-team-internal

**Comment by LEHigley** [comment]
done
