### ISSUE TITLE
Update cancel link to always show modal

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#3488]
The cancel link should always show a modal for confirmed appts. For Video and CC appointments, we'll have different modal content to tell users how to cancel their appointment.

AC:
- The cancel link is present for all cards on the appointment list page
- The modal for VVC and CC shows the content below
- The modal for regular VA appointments and all requests allow you to cancel online

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/68898656-e2377800-06fd-11ea-9d51-bfb6ebfff6ec.png)

**Comment by peggygannon** [comment]
Hello, @rtwell @narin  please see below for my copy recommendations for the cancel modals. 

Telehealth appointment modal
**You need to call your VA medical center to cancel this appointment**
VA Video Connect appointments can’t be canceled online. Please call the below VA facility to cancel your appointment. 

please update button to: OK (caps) 


-----

Community Care cancel modal
**You need to call your provider to cancel this appointment**
Community Care appointments can’t be canceled online. Please call the below provider to cancel your appointment. 


please update button to: OK (caps)

**Comment by narin** [comment]
@markgreenburg @peggygannon According to Jeff, we do not have access to a facility Id or phone number for video appointments.  We have a system ID, which we can get a phone number for, but I'm not sure if that is the appropriate place to call to cancel a video appointment.

**Comment by jbalboni** [comment]
In the future, we'll be able to get the right facility info, but for now I think we need some generic text that you need to contact the facility where you scheduled the appointment.

**Comment by peggygannon** [comment]
@narin @jbalboni are we still able to show their local facility? If so, is the message I provided above generic enough for these use cases? I didn't put a phone number in them, but please let me know if the facility name will be listed.

**Comment by jbalboni** [comment]
@peggygannon @narin As best I can tell, video appointments are the same as in regular VA appointments in that the info they send us is the health care system, not their actual facility. So we can't show a facility name or phone. I'm not 100% positive on that, but that appears to be the case and it'll be a little bit before I can actually verify for certain.

**Comment by jbalboni** [comment]
Note that we've resolved the above, we can show the full facility info.

**Comment by narin** [comment]
@jbalboni I know this is old and looks like you started some work on it already, but I still have this PR open from before it was blocked in case you want to reference/use some of the work: https://github.com/department-of-veterans-affairs/vets-website/pull/11335

**Comment by jbalboni** [comment]
@narin Gah, I didn't even think to look for an in progress PR. I will definitely steal some of that work.
