### ISSUE TITLE
[Design] Profile: Update desktop Sketch mockups to reflect radio/checkbox text solution discussed with Design System team 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34891]
## Background
We met with the Design System team and Angela Fowler to brainstorm ideas for how the open text field should work in the checkbox and radio button groups for Sexual Orientation and Pronouns.  

The consensus is that the open text field and its label should be present by default, and for the benefit of users with cognitive issues or low threshold for tech frustration, we will add a visual cue that shows it is associated with the last radio button or checkbox in the list.

This would be accomplished by following nearly the same pattern in Kevin's original error state mockup, except that the line to the left would be in blue, and the error message would not yet be displayed.  That is also similar to the pattern shown in the Storybook for a Radio Button option with expanded content.
Since this would be a change to the Design System, Christina will mock up in Sketch and Adam will put it on Staging so that Angela can confirm it is accessible to screen reader users.

The updated edit state would follow the below pattern in both the radio button and checkbox button group components.
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/2f608d45-86d9-4bde-9655-d0659f34c8af)

And the error state would follow this pattern: 
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/1393fae1-73a0-4a0d-a02d-565ef1746383)

## Tasks
- [x] Update the Personal Info Sketch desktop files so that they follow the above mockups.

## Acceptance criteria 
- [x] Personal Info Sketch desktop files follow the above mockups.

**Comment by MarciMcGuireGCIO** [comment]
Noting that pending this design being approved by the Design Council, we will create a new task to update the mobile mock-ups.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske would you mind dropping the link to the Sketch files here just so we have it for reference? Thank you!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO here's the sketch file showing Pronouns for reference! https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/nRMa9qd

**Comment by MarciMcGuireGCIO** [comment]
Thank you!
