### ISSUE TITLE
Dashboard - TUD: Record GA interaction events for each TUD account

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#34897]
As a TUD stakeholder, I would like to have dashboard cards that display user interactions with TUD accounts, like `button_click` events for each account:
- when the 'Go to staging' button is clicked
- when the email copy button is clicked
- when the password copy button is clicked
- when the 'Get one-time security code' button is clicked
- when the 'Get one-time security code' copy button is clicked
- when filters are added or removed

**Comment by holdenhinkle** [comment]
Record 'Go to staging' button clicks for each account.

The `value` for the click is the TUD account `email` value:

```
              window.gtag('event', 'button_click', {
                event_category: 'engagement',
                event_label: 'Go to staging',
                value: original.attributes.email,
              });
```

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/959d6e2f-18a1-43db-8992-3dc107af6c7c)

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/b49a073e-5798-4268-a913-377da95bab59)

**Comment by holdenhinkle** [comment]
Btw, I'm working off this same branch (`add_google_analytics_tracking`) - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/100

**Comment by holdenhinkle** [comment]
All of these events are being tracked now:

- when the 'Go to staging' button is clicked
- when the email copy button is clicked
- when the password copy button is clicked
- when the 'Get one-time security code' button is clicked
- when the 'Get one-time security code' copy button is clicked

I also completely refactored all the GA code for TUD. It's nice and tidy now.

I need to refactor `multiSelect.js` a little bit, which is where all the GA filter events are being triggered. That'll be easy.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/afce3a95-9efc-4a3a-a33a-ab6077a9a6f8)

**Comment by holdenhinkle** [comment]
The GA part is 100% done. It took a little longer than expected because of the way multi select works and because there are 4 ways to clear filters and each had to be handled. I'm going to demo this to Peter in the morning. I'll also start creating the DOMO cards.

**Comment by holdenhinkle** [comment]
Added tracking for the following:

TUD account note modal interactions:
- X (close)
- Save
- Cancel

Navigation links / button clicks

Breadcrumb link clicks

**Comment by holdenhinkle** [comment]
This is complete. 

The events are being recorded in GA. We have decided not to display them in DOMO for now.

**Comment by pjhill** [comment]
Hooray for this being in place!
