### ISSUE TITLE
(Q1) IET Initiative

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#34908]
## Problem Statement 
*Explore the feasibility and the challenges around how to break up vets-api into smaller services, thus informing the VA’s eventual strategy-making discussions relating to re-architecting vets-api.

## Hypothesis or Bet
* Rearchitecting vets-api will enhance security, scalability, stability, and code deployment experience across the VA ecosystem

## We will know we're done when... ("Definition of Done")
* We are done when a plan and a series of PoCs are developed that serve as a guide for how to break apart vets-api into more efficient and discrete microservice units
* 
## Known Blockers/Dependencies 
* We depend on the console services team to support our work by providing context and technical expertise/knowledge transfers about the current state of the vets-api monolith
* Though not a dependency, we would note that IET must manage and balance the expectations of multiple teams/stakeholders, including OCTODE/VSP, VFS, Console UI

**Comment by rogersarkis** [comment]
@jmcconn120

**Comment by ewilson-adhoc** [comment]
This initiative was successfully completed as summarized here https://vfs.atlassian.net/wiki/spaces/IET/pages/2132410379/Q1+Retrospective -> closing this issue for now.
