### ISSUE TITLE
Removal of Help for Afghanistan Veterans and families banner and COVID banner from check-in-experience apps

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#34913]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We would like to not show the banners (the promo and the COVID banner)  in the following screenshots in our check-in or pre-check-in applications. Here are the URLs of the applications:
health-care/appointment-check-in/*
health-care/appointment-pre-check-in/*
 
![148122289-9dc4dcef-e029-44a1-bcd8-ff8c5a09f6ef](https://user-images.githubusercontent.com/13967174/148457513-34e8b883-a41a-486d-bf69-70ebe66d9d98.jpg)

![File (4)](https://user-images.githubusercontent.com/1793923/148590910-b643a239-9bf3-49e5-98b4-2cc18c997587.jpg)

- Link to prototype or mockups: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e
- Link to any epics/issues that may be helpful: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34651

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: Already launched
- Estimated staging review date: n/a
- Content and IA work needed by: End of sprint 1/11

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Check-in Experience
-	OCTO-DE product owner: 
-	Product manager: Julie Adair
-	Designer: Ya-Ching Tsao
-	FE engineer: Brian Seek
-	Product/team Slack channel: #check-inexperience

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
Update: I removed the COVID-19 banner and am awaiting approval from Josh Tuscher to remove the promo banner. Will post here once I hear back.

**Comment by brianseek** [comment]
> Update: I removed the COVID-19 banner and am awaiting approval from Josh Tuscher to remove the promo banner. Will post here once I hear back.

Thanks for the update!

**Comment by RLHecht** [comment]
Got approval to remove the promo banner. Will post here again once it's removed on prod!

**Comment by RLHecht** [comment]
@brianseek The banner is now off those pages. Closing this ticket.
