### ISSUE TITLE
Removal of Covid Vaccination Banner from Comparison Tool from EDU and AFS Comparison Tool

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#34911]
## What does your team need support for? Check all that apply.
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [X] Something else (please add details in the next question)

## What do you need help with?
  - [X] IA support
  
VA.gov Comparison Tool is displaying 2 Covid banners:
1) Covid-19 Vaccines at VA
2) Coronavirus and VA education benefits

Mr. Brian Lloyd has requested to remove one of the banners. Per EDU, their request to remove the top/Covid-19 Vaccines at VA banner since the one displaying at the bottom (#2) is relevant to the Comparison Tool.

https://www.va.gov/education/gi-bill-comparison-tool/

The ask is to remove #1: Covid-19 Vaccines at VA
  
## Supporting Artifacts
Mr. Brian Lloyd has requested to remove one of the banners. Per EDU, their request to remove the top/Covid-19 Vaccines at VA banner since the one displaying at the bottom (#2) is relevant to the Comparison Tool.

https://www.va.gov/education/gi-bill-comparison-tool/

- Please see attached screenshot.
[CovidBanner.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7824880/CovidBanner.docx)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: asap please
- Content and IA work needed by: asap please 

## Do you plan to bring this to an upcoming content office hours session?
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Darla van Nieukerk (OIT)
-	FE engineer: Dan Brooking (AFS)
-	Product/team Slack channel: Abe Blanco (AFS Team Lead)

**Comment by RLHecht** [comment]
Updated this in Drupal. Will validate after the next content release.

**Comment by RLHecht** [comment]
@mrblanco1 The COVID alert is now off the comparison tool page. Closing ticket.
