### ISSUE TITLE
Adding @cms-product-support and @cms-content-ops groups to DSVA Slack

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#34926]
# Description
Please add the following groups in DSVA slack:
- Group Name: CMS Product Support
  - Handle: @cms-product-support
  - Purpose: To help collaborate across this workstream
  - Default Channel: #cms-team

- Group Name: CMS Content Ops
  - Handle: @cms-content-ops
  - Purpose: To help collaborate across this workstream
  - Default Channel: #cms-team

Request in #slack-workspace-admin: https://dsva.slack.com/archives/C01S729LX6X/p1641435070000100 and https://dsva.slack.com/archives/C01S729LX6X/p1641435107000200

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
