### ISSUE TITLE
Upgrade Grafana to 6.6

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3492]
## Description
Grafana 6.6 is out, we should upgrade from our current 6.4.3:
- https://grafana.com/docs/guides/whats-new-in-v6-5/
- https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-6/

## Acceptance Criteria
- [ ] http://grafana.vfs.va.gov/shows 6.6.x as running version
- [ ] Several dashboard have been checekd

## Process 
The last upgrade was done on department-of-veterans-affairs/devops#5820 and really, we should just need to update the version int eh deployment yaml file and test in vagrant.

Before doing a build in prod, log in to the AWS console and snapshot the RDS just in case.

**Comment by ricetj** [comment]
@nathanhruby to fill in a bit on this one.

**Comment by ricetj** [comment]
Done and working
