### ISSUE TITLE
Create a Domo Dashboard to Monitor KRs

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34934]
# Description
In order to understand our progress with meeting key results related to the QA Dashboard Product View initiative, we need to create a dashboard to collect and visualize data related to our key results.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/2074254045 all done!

**Comment by pjhill** [comment]
Dashboard has been created with one example of KR measurement already available. Subsequent visuals for KRs will be added to this dashboard.
