### ISSUE TITLE
Add support for dynamically generated formId in Forms

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#34938]
## Issue Description

Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33326

In order to support dynamically generated formId for forms, we want to add the ability to pass a function to formId to generate the id. This is opt-in and hardcoded formIds will continue to work.

`src/platform/forms-system/src/js/containers/FormApp.jsx`
```javascript
render() {
  ...
  if (typeof formConfig.formId === 'function') {
    formConfig.formId = formConfig.formId(this.props);
  }
  ...
}
```
## Acceptance Criteria
- [ ] Forms accepts a function for formId

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
