### ISSUE TITLE
[FE] Hide the  Feedback Modal

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34947]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Ticket found](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34653)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

From UX: 
```
I noticed the "We'd welcome your feedback!" modal with a link to a survey pops up on the login page and sometimes mid flow. Are we able to disable that? It may be distracting for a user who is trying to pre-check-in, which is a different use case vs. someone browsing the VA site. Will attach screen shot. 
```
## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
working slack thread: https://dsva.slack.com/archives/C02GXKL8WM6/p1641563550035500

**Comment by julieadair1** [comment]
pinged @jwoodman5 for an update.

**Comment by jwoodman5** [comment]
I have not received any follow-up information from the ForeSee team since putting this request in 13 days ago. I just reached out for an ETA and will advise. Thanks.

**Comment by mdewey** [comment]
Thread says its addressed and the modals are not showing in production
