### ISSUE TITLE
QA Feedback - Staging Review - Public Websites - Outreach & Events MVP

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#34958]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/34622

**Comments:**
- None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Address [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34762).
- Fix these element overlap issues:

<img width="753" alt="Screen Shot 2022-01-07 at 11 31 42 AM" src="https://user-images.githubusercontent.com/3535749/148584074-88964fe0-2913-4a00-964d-c26f3830d974.png">

<img width="762" alt="Screen Shot 2022-01-07 at 11 36 02 AM" src="https://user-images.githubusercontent.com/3535749/148584087-64adf0d9-3595-46e0-8c43-ec5c7df8841b.png">

**Should:**
- When specifying a custom date range, no message or warning is shown when the start date is after the end date. Determine if an error message or other warning should be shown.

**Consider:**
None

**Comment by brianalloyd** [comment]
@kelsonic looping you into this issue as we work toward staging review actions.

**Comment by brianalloyd** [comment]
@kelsonic can you review this before EoD?  Let me know what questions exist.

**Comment by kelsonic** [comment]
Yeah, I wondered if we were going to need custom error styling for this. I think that's what we should do, I'll try to get a PR out for this before I leave 🙂

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19852

![image](https://user-images.githubusercontent.com/12773166/148826690-e5a712db-e1d9-477d-934f-4c8afc11faca.png)
![image](https://user-images.githubusercontent.com/12773166/148826737-44310efa-2e1c-4649-a385-5cc9e406290b.png)
![image](https://user-images.githubusercontent.com/12773166/148826755-a1e17926-d0ff-47f7-b005-5c1c41544175.png)

**Comment by kelsonic** [comment]
PR merged, closing 🎉

**Comment by ddzz** [comment]
@brianalloyd The ticket has been reopened and updated with the comment on custom dates. @tlei123 and I will update this again if we find any issues when testing recurring events.

**Comment by brianalloyd** [comment]
@ddzz thanks for the follow up and support.  Looking forward to any feedback you have in regards to recurring events.

**Comment by tlei123** [comment]
@ddzz , Recurring-events test-runs completed on Drupal-dev [Mac Chrome & Firefox only due to SOCKS-proxy requirement].  Here's the [final Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/291) \[report-link also updated in Staging Review ticket #34622\]

cc @brianalloyd

**Comment by brianalloyd** [comment]
Closing ticket in support, updates have been applied.
