### ISSUE TITLE
Web Components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#34955]
## Problem Statement 
In order to have a consistent user experience, individual components in applications and content should be identical across the user experience. For example, the user interface of a simple form should not appear or behave differently in different parts of VA.gov. However we currently do not maintain a library of components that is technically agnostic, so teams building in each of the three technical approaches draw from different shared/reusable code bases.

How might we create a technically agnostic approach to our design system and the components and patterns within it that will allow a team to build a new React app, new content, or hybrids without recreating components from a specific technical stack or creating more code that is unique to a single component.

## Hypothesis or Bet

- VFS teams will be able to build more consistent applications across different technical environments
- VSP will be able to maintain a single source of truth for multiple technical environments

## We will know we're done when... ("Definition of Done")

- DST has built the following web components:
1. ProcessList
2. Pagination
3. Banner
4. Table
5. PromoBanner
6. Modal
- Migration scripts are available to teams so they can update to web components

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
* By end of Q1 2022

### Documentation
* **`PRODUCT_NAME`**: Web Components
* **Product Outline**:  Web Components Product Outline https://vfs.atlassian.net/l/c/5X9MRsJv
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: See Product Outline
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by humancompanion-usds** [comment]
The overall majority of components in the Design System (design.va.gov) are now converted from React to web-components and we have a plan to deprecate the React versions: https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components

There are 10 React components that we will likely leave behind and not support moving forward and 1, [MaintenanceBanner](https://design.va.gov/components/banner/maintenance), that we will convert at some point in the future.
