### ISSUE TITLE
Access for Tom Harrison

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#34957]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Tom Harrison

### Your Email

tom.harrison@adhocteam.us

### Name of Your Team

Authenticated Experience - Profile, Backend Engineer, Adhoc

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need to access the staging environment (assuming EC2 servers) to test vets-api calls.

https://dsva.slack.com/archives/CBU0KDSB1/p1641574498084600

**Comment by mleclerc00** [comment]
For AWS Access:
User: Tom Harrison
COR: Mary O'Toole
Approval needed: @department-of-veterans-affairs/operations-aws-approvers

**Comment by tpharrison** [comment]
Can I get a status update on this?  Thanks!

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
@mleclerc00 approved

**Comment by mleclerc00** [comment]
First time login passed along.  Closing this ticket
