### ISSUE TITLE
HRT Landing Page Design Prototype in UXPin 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34962]
## Issue Description
_ORDMI PIFs have never actually produced any design mockups for the harassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled.  We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems.  The designs will be used for both design intent review and initial FE build of the prototype_

[Draft Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/research-plan.md) 

## Design tasks
- Create a prototype in UX pin for user research testing (Content Landing Page)
- Test prototype to ensure functionality is working as intended
- Validate with @cindymerrill ISO research efforts 
- Update/Finalize as needed 

## Acceptance Criteria
- [ ] UXPin prototype is ready to use in support of research efforts 
- [ ] Designer posts link to Prototype for review by Research/PM/PO
- [ ] Researcher reviews prototype ISO research plan
- [ ] Feedback is documented on ticket for follow up and review

**Comment by cindymerrill** [comment]
Is there a possibility that this might be on Staging instead so can include screen reader users in the research, @brianalloyd ? You said you were going to ask @kelsonic about how he did that previously.

**Comment by brianalloyd** [comment]
@cindymerrill waiting until Kelson and I meet to review. Going to determine is this is feasible (without Kelson) and will update ticket accordingly.
