### ISSUE TITLE
Initial Update of AVS User Guide

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34969]
Initial edit, looking at:
[ ] Clarity
[ ] Grammar
[ ] Consistency

Notes: Sharepoint URL: https://dvagov.sharepoint.com/sites/vhaavs

**Comment by jwowk** [comment]
Transfer to SharePoint is complete. Rob took a look and had the following comments:

Need updated screenshots
Need section for PVS and DVS - not high priority

He updated the installation instructions as well.

**Comment by lindsay-insco** [comment]
Completed and uploaded to SP
