### ISSUE TITLE
[1/19/2022] Set up Helpdesk PowerApp Frontdoor for AVS 

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34973]

**Comment by jwowk** [comment]
Granted Chance full control to AVS SharePoint site to start building out necessary architecture for support app.

**Comment by aschulhof** [comment]
Clone existing power app - strip out vetext and send to new shared inbox.

**Comment by chancetheoriginal** [comment]
App built and shared.
