### ISSUE TITLE
[1/21/2022] Build PowerBI Dashboard for AVS 

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34974]
- [ ] request a new workspace for AVS so it has a standalone App
- [ ] Building out a dashboard to track site adoption, usage 

Note: We can get dataset from Rob Durkin.

**Comment by aschulhof** [comment]
We need to begin an AVS dashboard ASAP please. We can take tomorrow to give you a chance to ask questions but we have a need for a dashboard at with # of sites using AVS, and # of AVS printed. Shane pointed to these tables. It's time-sensitive so I'd like to be able to have an internal review by Monday

**Comment by aschulhof** [comment]
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5ee7789b129fd2147cccd47f/57ba9ba8-8506-4796-ab59-162604d9f319)

**Comment by aschulhof** [comment]
@Cmjones233  to schedule internal review Tuesday

**Comment by Cmjones233** [comment]
Dashboard link posted to slack for review (1/14/22)

**Comment by Cmjones233** [comment]
review with Shane 1/18.
notes- create second page with station breakdown of usage, fix stations to show only parent, only last 12 months of bar chart, include top 10, include active sites

**Comment by Cmjones233** [comment]
Notes applied and posted for 2nd internal review 1/24

**Comment by Cmjones233** [comment]
Reviewed by Shane 1/25. Need to make Users and Provider distinct and to drop patients from Line graph

**Comment by Cmjones233** [comment]
Final updates to make providers, patients and users count distinct done, Approved by Shane
