### ISSUE TITLE
[1/21/2022] Develop Initial AVS Training Plan

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34970]
- [ ] Create breakdown of training plan for training modules (new user, admin, etc)
- [ ] Planning Training Programming (e.g. Setting up Office Hours, feature-update trainings, etc)

**Comment by aschulhof** [comment]
Create training from userguide - https://drive.google.com/drive/folders/1SwQpBbuUGmfR8GUjnWDPHadAR_ofWSpe

**Comment by djfredvs** [comment]
Preliminary training plan is complete. Waiting for review.

**Comment by djfredvs** [comment]
[https://app.zenhub.com/files/133843125/0089c9b3-cdf7-420e-9cf8-d65d41913472/download](https://app.zenhub.com/files/133843125/0089c9b3-cdf7-420e-9cf8-d65d41913472/download)

**Comment by aschulhof** [comment]
It looks like @djfredvs  created the training plan for VEText in the doc above. I synced with him and he is now createing training plan for AVS, based on the user guide and demo in this folder. https://drive.google.com/drive/folders/1SwQpBbuUGmfR8GUjnWDPHadAR_ofWSpe

**Comment by djfredvs** [comment]
The AVS training plan is attached here.[https://app.zenhub.com/files/133843125/89ed9127-35eb-455a-9edd-e1a7d80e1512/download](https://app.zenhub.com/files/133843125/89ed9127-35eb-455a-9edd-e1a7d80e1512/download)

**Comment by aschulhof** [comment]
Link here: https://docs.google.com/document/d/18JN3mo5BW-ft77x1DhDUfNn3VdkAUsQR/edit

**Comment by djfredvs** [comment]
Training plan has been reviewed

**Comment by aschulhof** [comment]
Training 1 - AVS Overview
Agenda
Introduction - OIG mandate
AVS Overview / Sites using AVS
Section 7
AVS Benefits
AVS Feature Overview
Quick Demo
AVS Product Support Links


Training 2 - AVS Installation
Agenda
Introduction on AVS
How to Install at your site - Step by Step
Setup Shortcut on CPRS Tools Menu
Create user class AVS Administrator
Assign users for the Facility
Quick Demo (Fred to coordinate with team to get video)
Need Support - link to our product support resources
Sharepoint site link
Helpdesk App Link
Teams Channel link
Training 3 - Admin Settings
Agenda
Introduction on AVS
How to configure AVS for your Site (basics of what you can do in admin)
XX
XX
XX
Need Support - link to our product support resources
Sharepoint site link (user guide)
Helpdesk App Link
Teams Channel link
