### ISSUE TITLE
[1/14/2022 ] Setting up AVS Teams Channel

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34972]

**Comment by jwowk** [comment]
Team channel created [AVS]. Chance and Misti added as owners.

**Comment by aschulhof** [comment]
Add link to SP and mirror Vetext

**Comment by jwowk** [comment]
Added SharePoint tab, User Guide tab, and Setup Instructions tab. Also added link to teams channel on SharePoint Homepage and Footer.
