### ISSUE TITLE
Build metrics dashboard for AVS to track incoming request volumes

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34977]
- [x] Chance and Misti to set up data process for AVS
- [ ] Crystal to create dashboard

**Comment by Cmjones233** [comment]
Dashboard connected to sharepoint 1/20, building out board currently.

**Comment by Cmjones233** [comment]
Dash built and submitted for review 1/24

**Comment by Cmjones233** [comment]
Done, just need more data 1/25
