### ISSUE TITLE
Develop Marketing Materials / Overview of AVS 

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#34983]
Pitch deck / PR / one-pager

**Comment by aschulhof** [comment]
Ppt Linked Here: https://oddball.slack.com/archives/C02ER7WV33J/p1643052035153100?thread_ts=1642715369.105700&cid=C02ER7WV33J

**Comment by aschulhof** [comment]
[https://app.zenhub.com/files/133843125/8f26eedf-95e8-4185-92b2-688914d0a313/download](https://app.zenhub.com/files/133843125/8f26eedf-95e8-4185-92b2-688914d0a313/download)

**Comment by lindsay-insco** [comment]
Posted to Sharepoint
