### ISSUE TITLE
Access for Gino Perlangeli

### ISSUE THREAD

**Issue by gperlangeli** [department-of-veterans-affairs/va.gov-team#34988]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Gino Perlangeli

### Your Email

gperlangeli@clarityinnovates.com

### Name of Your Team

Site Reliability Engineer Team

### Service(s) You Want Access To

AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCy4YK49+gK19CWQppBZHqcsEBcuMa0IofTSdJ5J57/yXc4aOpPNBsUCo9u4qkgg0mK40oBgKq1nD1EBxmA1WGQPGWwNeu1IvZ1qm3vjAqlWDyvAcOmwBAPp1jdOSlu24zC+z9iFgQBTwSX52nksHYSpP4aCuBXrRHeS1GTw9L2lJgBHf1UR5uKp7wqi7Xuo61OoY2osBDddIioPVVXy15RQmiRADgpi0vSm+bDIq9ssJyor8MzRhs3MsOkYkSsN8QJ7Fxm0JBdCE6Y6LlGgmQMbeP/H3CZU8tmlomBX2K5EfUrubiBhoBll1AytsCQj+O4oVQq3zsD3ykojzvTzQl6crn/Fi2YQk0LhBf17F52a5mCudQQc2ih9eYfViuQ69gwQFjSU0pRH2KHylUCjLFgFWYRJo862pczGuPJOBm50HKXds7L3tfVaRBRG13nNX9G/6nxEZaqhOZuirKGWWiVl/dppr7Bu0W1I9ct+MJgnyyP9f6tLNtIqNyKJa0m6tM= gperlangeli@DESKTOP-M5IICU3

**Comment by mleclerc00** [comment]
For AWS Access:
User: Gino Perlangeli
COR: Mary O'Toole
Approval needed: @department-of-veterans-affairs/operations-aws-approvers

**Comment by td-usds** [comment]
Reached out to VOR

@gperlangeli which concrete AWS services do you need access to? None are listed so none would be granted. Can you tell us which specific things you need access to?

**Comment by td-usds** [comment]
Tentatively approved from an eligibility perspective; before final approval, we need to define what the actual access requirement is.

**Comment by jbritt1** [comment]
> Reached out to VOR
> 
> @gperlangeli which concrete AWS services do you need access to? None are listed so none would be granted. Can you tell us which specific things you need access to?

Gino is part of the SRE team and will largely be working on incoming support requests in the near future to the best of my knowledge. In my opinion, we could likely get away with the typical baseline developer access we give out in the current model. More granular IAM policies is not likely to be prioritized by the Operations team anytime soon from what I currently understand as we have more pressing initiatives like migrating vets-api to EKS. So I would say the current options are we can grant Gino that baseline developer access or grant nothing until we get support or leadership prioritization around forming new / refactoring old IAM groups, policies, etc. which could be an indefinite amount of time and would prevent Gino from really being able to accomplish much from a support perspective.

**Comment by td-usds** [comment]
Approved for option "A) we grant Gino that baseline developer access"

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
