### ISSUE TITLE
VSP Operations Onboarding for Oseas Moran

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#34995]
# Ops Onboarding
## Overview
Welcome to the platform and more particularly the VSP Operations team.  This ticket is a checklist and guide to try and improve the onboarding process and get you up to speed.

If you have any questions/need access please reach out to Jesse House (@jhouse-solvd) or Demian Ginther (@dginther).

### Admin work
- [x] If new to VA, will need background check. Fill out forms from Amber, get fingerprinted, and fill out eQIP investigation request in order to get a PIV card
- [x] set up [TMS](https://www.tms.va.gov/secureauth35/SecureAuth.aspx) account and take required trainings

### Access to what you need
- [x] [Getting setup](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
- [x] Share your calendar with VSP: va-vsp-team@gmail.com and  vsp-team.group@adhocteam.us
- [x] Ensure you're in Google Groups [va-vsp-team](https://groups.google.com/a/oddball.io/g/va-vsp-team) and [va-vsp-engineering](https://groups.google.com/a/oddball.io/g/va-vsp-engineering)
- [x] Ensure you have access to Google Drive folder ["VSP team"](https://drive.google.com/drive/u/0/folders/0AJ6yVhfytxhFUk9PVA)

**Tools**
- [x] DSVA Slack Workspace
  - [x] #vsp-operations
  - [x] #vsp-operations-internal
  - [x] #platform-team (vetsgov-devops is archived)
  - [x] #vfs-all-teams
- [x] Github: join 'department-of-veterans-affairs' org
- [x] [Zenhub](https://app.zenhub.com/workspaces/platform-operations-team-6112bc325f570300140f7852/board?repos=133843125)
- [x] [Setup SOCKS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#how-can-i-set-up-access) to access below apps:
  - [x] [Jenkins](http://jenkins.vfs.va.gov/)
  - [x] [Sentry](http://sentry.vfs.va.gov/)
  - [x] [Grafana](http://grafana.vfs.va.gov/)
  - [x] [Argo CD](http://argocd.vfs.va.gov/)
- [x] [Pagerduty](https://dsva.pagerduty.com/)
- [x] [Confluence](https://vfs.atlassian.net/wiki/home)
  - [x] [Operations Team space](https://vfs.atlassian.net/wiki/spaces/OT/overview)
- [x] Keybase
- [x] Prometheus (not used directly)
- [x] [Datadog](https://app.datadoghq.com/) (ask for invite)
- [x]  AWS ([access request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=Environment-Access-Request-Template.yml&title=Access+for+%5Bindividual%5D))

### Understanding VSP and where we sit
- [x] [Overview of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Welcome%20to%20VSP.md#welcome-to-the-veteran-facing-services-platform)
- [x] [Getting to know VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/vsp-team-member-onboarding.md)
- [x] [Overview Presentation of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/VSP%20Mission%2C%20Objectives%2C%20Roadmap%2C%20and%20OKRs%20-%207-23-19.pdf)

### VSP Operations
High level:
- [x] [High level info of the team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/operations#operations)
- [x] [Team charter](https://vfs.atlassian.net/wiki/spaces/OT/pages/1817084282)
- [x] [Delivery Infrastructure Overview demo presentation](https://docs.google.com/presentation/d/1dXE3kkG56fXu7QvqH7qu5mGE3gfalD0FRf-gbnnjnHc/edit?usp=sharing)
- Meet the members of the team
  - [x] Jesse
  - [x] Michael Fleet
  - [x] Jeremy
  - [x] Matt
  - [x] John 

More details on our work:
- [x] [Infra recommit work](https://docs.google.com/document/d/1cVFlFXuwjg_dbapwiCZ-iT01mywcZdHBhfzPjAq-7TI/edit)
- [x] [VSP Onboarding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/onboarding.md)
- [x] [Oncall role](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/daytime-oncall-support-role.md)
- [x] [DevOps repo](https://github.com/department-of-veterans-affairs/devops)
- [x] Talk with Jesse about Sprint Objectives & Quarterly Initiatives
- When creating an issue in GH, make sure to use the “ops issue template”

**Comment by oseasmoran73** [comment]
Closing ticket as most actions have been done prior to joining Ops. Requested access where applicable
