### ISSUE TITLE
[BE] **Discovery** | Legal Rep Payload Question

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#35009]
## Background

The CG/Carma team would like to have in the payload which box was checked for the application signature question:

- Veteran
- Legal representative for the Veteran 

Purpose would be to create an alert for processors to check that appropriate documentation was sent if the legal rep  button was clicked.

This isn't a new question/answer so this may already be in the payload we are sending. This ticket is to determine whether we send this information today with the CG form

## Acceptance Criteria

- [x] Document in comments whether or not info is included today

**Comment by SKasimow** [comment]
@jchilders can this be completed in current sprint 64?

**Comment by SKasimow** [comment]
@jchilders - can you add findings for AC

**Comment by jchilders** [comment]
Looking at the payload that is generated, it does not look like this is getting sent. If it is needed it will need to be added
