### ISSUE TITLE
Access for Oseas Moran

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#35003]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Oseas Moran

### Your Email

oseas.moran@adhocteam.us

### Name of Your Team

VSP Infrastructure (VSP-Operations)

### Service(s) You Want Access To

AWS

### Desired AWS Services

Have AWS Access under `FE-Tools` or `fe-review-group`. Would like to change permission/role to vsp-operations/devops/ops

**Comment by oseasmoran73** [comment]
CC @jhouse-solvd

**Comment by mleclerc00** [comment]
Oseas has already gone through the equip process and has AWS access currently.  This ticket is for tracking purposes.
