### ISSUE TITLE
User is being requested to upgrade MHV account with an already upgraded MHV account

### ISSUE THREAD

**Issue by boris-ning-usds** [department-of-veterans-affairs/va.gov-team#3500]
### Status

[UNRESOLVED]

### Severity Analysis
sev 2 - needs SME

### User Impact 

User cannot view his VA appointments via va.gov, as it forces him to upgrade via MHV.

### Description

User is running into an issue using his ID.ME credentials in the system believing he need an upgraded MHV account when he already upgraded. If he try to upgrade, it tells him it can't and to try again. If he log in with MHV credentials, it doesn't present him with this need to upgrade.

Logging in on https://www.va.gov/health-care/schedule-view-va-appointments/ using ID.me will prompt him to upgrade his account.

### Steps to Reproduce

We'll need the user to reproduce it. The ServiceNow ticket is filed under INC8349045.

#### Expected Results

User should be able to view his VA appointment without having the MHV upgrade, as he is already upgrade.

ServiceNow (or other source) link: INC8349045

#### Screenshots

Screenshots came from the user.

1. Logged in on https://www.va.gov/health-care/schedule-view-va-appointments/ using ID.ME prompting me to upgrade my account.
![image](https://user-images.githubusercontent.com/41026275/68920151-64499000-0742-11ea-9b8a-9ba50bc06aeb.png)

2. User sees failed to upgrade page.
![image](https://user-images.githubusercontent.com/41026275/68920167-6f042500-0742-11ea-988f-4e0bfa97acca.png)

3. Correct screen/options shown when logged in with MHV creds.
![image](https://user-images.githubusercontent.com/41026275/68920300-cbffdb00-0742-11ea-9272-4d928a872807.png)

### Proposed Solution

I recommend we work with the user to figure out why there's a difference in experience for appointment viewing between MHV and va.gov, even though the user thinks he already has the necessary credentials/access to it.

**Comment by boris-ning-usds** [comment]
User is saying that the issue might've been resolved on its own on a different channel.
I'm wondering if it has anything to do with a bad data source if va.gov/VFS is pulling data from MHV.

Investigation is needed to ensure nobody else is affect or this problem reoccurs.

**Comment by omgitsbillryan** [comment]
Seems that it may be related to that bad data source, especially since it seems MHV has since fixed their issues.

**Comment by patrickvinograd** [comment]
This _could_ be related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/3271

**Comment by lkoenigsberg** [comment]
Also not confident that this is related to the other issue. This one has a login/identity issue while the other didn’t.

**Comment by chrisj-usds** [comment]
@boris-ning-usds Since you're the one who opened this ticket.... any chance you have contact info for the user who submitted it?

**Comment by lkoenigsberg** [comment]
Spoke to Bill this morning via phone.  He's been in contact, via email, with the ID.me Member Support team but no resolution provided yet. 

I'm coordinating a Skype call with Bill, ID.me, and VA.gov members so we might see what's going on from both the FE and BE, hoping to identify a root cause and recommend a solution.

**Comment by shawn-adams** [comment]
This happened to my own personal account as well.  Issue resolved itself.  I was already a premium MHV user with an ID.ME account.  There was no reason to solicit me to upgrade my account as it was already upgraded and linked to MHV account.  I kept getting the prompt and failing the upgrade and the next day (about 12 hours later) I was able to log in without the prompt appearing.

**Comment by lkoenigsberg** [comment]
Issue is resolved. Turns out he had not actually been able to access VA.gov in over a year. After a browser update he was able to complete is 2fa and was able to access as expected.

**Comment by shawn-adams** [comment]
Can you contact me regarding this?  shawn.adams@va.gov  This issue looks originally sourced from an ESD ticket I logged.  If so, I've accessed VA.GOV multiple times over the past year. 
 https://yourit.va.gov/va?sys_id=e6a1dd76db4948d8587fff1e0f961985&view=sp&id=ticket&table=incident

**Comment by boris-ning-usds** [comment]
Ah, @lkoenigsberg, this is the wrong ticket for the resolution. You should be resolving #3499 
ESD also routed me two tickets, so I created two github issues to match them; one with Bill's issue (#3499 ), the other with Shawn's issue (#3500).

@shawn-adams I believe that the MHV team has fixed this issue, regarding an API that the va.gov team uses. I know that you have already stated that you no longer see the issue, do you mind if I close out this issue as a resolution as well?

**Comment by shawn-adams** [comment]
close
