### ISSUE TITLE
Mulesoft | Privacy & Security Review

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#35019]
## Background

- Complete Collab Ticket for 10-10CG Mulesoft Implementation here: [Ticket 377](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/377).

- Link to documentation: [Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/eng-docs)

## Acceptance Criteria

-[ ] Ticket is completed and ready to review with Privacy and Security team

**Comment by SKasimow** [comment]
@shiragoodman we're working with Troy from the Privacy and Security team to complete this ticket (just need to provide a little more info).

Once that happens and they sign-off, are we complete with collaboration cycle?

**Comment by shiragoodman** [comment]
correct! we didn't request any other Collaboration Cycle touchpoints... only the privacy and security review. Thanks for checking @SKasimow !

**Comment by SKasimow** [comment]
@shiragoodman - kewl, thanks!
