### ISSUE TITLE
Increase font size on non-caution flags

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#35034]
## Issue Description
Issue #29367 was completed but the font on non-caution flags is too small and looks "unfinished". This ticket is to increase the font size to the same size as caution flagged cards.

---
## Tasks
Increase the font size to the same size as caution flagged cards.

## Acceptance Criteria
Increase the font size to the same size as caution flagged cards.
---
## How to configure this issue
- [X] **Labeled with Practice Area** (`frontend`)
- [X] **Labeled with Type** (`bug`)

**Comment by hallihocine** [comment]
Ticket has been validated in staging. The styling looks good: the font size is similar to the one the cards with caution flags, it's inside a grey box with a vertical green bar on the left side. See screenshot:
<img width="1069" alt="Screen Shot 2022-01-19 at 8 49 17 AM" src="https://user-images.githubusercontent.com/86266024/150150773-9e224a40-3fb9-4952-b9e6-e0ba620f657a.png">
