### ISSUE TITLE
Screen readers should first read Institution Name, City, and then State for institutions with the same name (remove code)

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#35036]
## Issue Description
Currently a code is read for institutions with the exact same name. Screen readers should first read Institution Name, City, and then State for institutions with the same name (remove code). (This issue is related to #33881)

---
## Tasks
Screen readers should first read Institution Name, City, and then State for institutions with the same name (remove code)

## Acceptance Criteria
Screen readers should first read Institution Name, City, and then State for institutions with the same name (remove code)
---
## How to configure this issue
- [X] **Labeled with Practice Area** (`design`)

**Comment by nbarthelemy** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19968

**Comment by nbarthelemy** [comment]
Still waiting on PR review for this one.

**Comment by nbarthelemy** [comment]
Follow up PR based on feedback from QA: https://github.com/department-of-veterans-affairs/vets-website/pull/20086

**Comment by hallihocine** [comment]
Ticket has been validated in staging.
- Test Run: 
https://dsvavsp.testrail.io/index.php?/runs/view/2884&group_by=cases:section_id&group_order=asc&group_id=3598

**Comment by mrblanco1** [comment]
QA and UAT Passed. Feature Flag Removed.
