### ISSUE TITLE
[BE][MuleSoft] Staging & RI envs: Add Mulesoft Config to Ansible Playbooks

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#35040]
## Background

In order to communicate with the MuleSoft servers we need to add configuration to Ansible.

## Acceptance Criteria

- [x] Configuration have been updated for staging and RI's
- [x] PR submitted for configuration updates

**Comment by jchilders** [comment]
@SKasimow Who verified this?

**Comment by SKasimow** [comment]
@jchilders I've asked that you comment on the tickets and update the status so I know that they are complete. If this has not been done, please re-open and add comments on why it wasn't complete and current status.

**Comment by jchilders** [comment]
@SKasimow I'm sorry if you were unaware, but we only recently received the credentials from Carma for staging, this past Wednesday I believe. This issue was closed that same day. Based on that it was my understanding that those credentials had therefore been added. Is this not the case?

**Comment by SKasimow** [comment]
@jchilders I've re-opened the ticket.

**Comment by jchilders** [comment]
@SKasimow Can you assign it to @dillo or would you like me to?

**Comment by RudyOnRails** [comment]
Looking at this ticket, I don't see a PR linked to it, so at first thought, I don't believe it is complete. However we would not be able to submit to Mule if we hadn't configured it, so maybe it was just an oversight. I am going to track down the PR and link it here so we can confirm this was done

**Comment by SKasimow** [comment]
Thank you @RudyOnRails

**Comment by RudyOnRails** [comment]
This was already completed for staging/RI envs.

I'll create a new placeholder ticket so that when we get prod credentials we can complete the ticket.
