### ISSUE TITLE
Access for Kyle Crockett

### ISSUE THREAD

**Issue by kaipyroami** [department-of-veterans-affairs/va.gov-team#35047]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Kyle Crockett

### Your Email

kyle.crockett@oddball.io

### Name of Your Team

Platform Security

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need access to all services grated to @gary-fallon in support of Platform Security's mission. 
@td-usds can provide more information if required.

**Comment by jbritt1** [comment]
#### For AWS Access

User: Kyle Crockett
COR: Mary O’Toole
VOR: Oddball - Amber Malcolm
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by jhouse-solvd** [comment]
Updated title to reflect individual's name.

**Comment by td-usds** [comment]
eQIP confirmed; approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
