### ISSUE TITLE
Redirect Request - legacy /Privacy page

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#35042]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request ne
ed to be live: anytime

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/Privacy |  https://www.oprm.va.gov/

**Please note: there is already a redirect in place for the lower case version of this URL (/privacy) that was completed back in 2019 to handle a URL change on one of our modernized pages.   This redirect request captures a legacy page that also exists with a capitalization difference.   This redirect should be implemented (or the old redirect updated) to it is not case sensitive and captures all variations.**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [x] Implementation team: Work is complete
- [x] Implementation team: Validated in production
- [x] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@brianalloyd This redirect can be done at your discretion.

Please note: there is already a redirect in place for the lower case version of this URL (/privacy) that was completed back in 2019 to handle a URL change on one of our modernized pages. This redirect request captures a legacy page that also exists with a capitalization difference. This redirect should be implemented (or the old redirect updated) to it is not case sensitive and captures all variations.

cc @davidconlon

**Comment by brianalloyd** [comment]
Thanks @mnorthuis appreciate the notes, super helpful for our FE team.  We'll slot this for upcoming sprint in support.

**Comment by brianalloyd** [comment]
@tmac9494 please review this ticket and notes ISO implementation.

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/10583

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/10586

**Comment by brianalloyd** [comment]
@mnorthuis this is now on prod, can you validate and close when you have a moment.  TIA.

**Comment by mnorthuis** [comment]
The redirect doesn't capture all casing variations, I can still get to the legacy page at va.gov/PRIVACY

Can this redirect capture any casing?  If not, it has to capture this all caps version as well, as VA often does that.

**Comment by tmac9494** [comment]
@mnorthuis  not it currently only catches "Privacy".  the reason this is case specific is because /privacy lowercase already had a redirect which takes you tohttps://www.oprm.va.gov/privacy. If it's okay to override that one I can replace it with a redirect that catches all cases.

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/10600

**Comment by mnorthuis** [comment]
www.va.gov/privacy and www.va.gov/Privacy work but www.va.gov/PRIVACY is not working for me

**Comment by tmac9494** [comment]
concerns addressed and updated build is deployed

**Comment by brianalloyd** [comment]
@mnorthuis please validate on your end, everything looks good from my prospective.

**Comment by mnorthuis** [comment]
Done!
