### ISSUE TITLE
Site search does not return forms

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#35044]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Nicole Leonard  6 minutes ago
oddly when I put it in the search bar on the home page it does not come up
white_check_mark
eyes
dilbert

mark viterna  5 minutes ago
I think they just deployed. Very strange. They seem to be on a new cycle. I've not done a deployment for some time so maybe things have changed, I'll try to get the new schedule so we have testing time in the future.
white_check_mark
eyes
dilbert

mark viterna  5 minutes ago
but I think we are good now. We have decided not to delete the duplicate and the "correct" one is in va.gov now
white_check_mark
eyes
dilbert

mark viterna  5 minutes ago
are we comfortable marking this as resolved?
white_check_mark
eyes
dilbert

Dave Conlon  4 minutes ago
@Nicole Leonard define "main page"
white_check_mark
eyes
dilbert

Nicole Leonard  4 minutes ago
@Dave Conlon va.gov

Dave Conlon  3 minutes ago
you mean on the Site Search?

mark viterna  3 minutes ago
@Nicole Leonard Those are completely seperate engines. If you are talking the search bar at the top right
:heavy_plus_sign:
1

Nicole Leonard  3 minutes ago
Oh wow. Ok.

mark viterna  3 minutes ago
one thing to note, it doesn't have a form detail page, so that won't help the main search

Nicole Leonard  2 minutes ago
That is super confusing to a user. If I go to VA.gov and I know my form put it in and it does not come up. :thinking_face:

Nicole Leonard  2 minutes ago
Thank you for the insight.

Dave Conlon  1 minute ago
When they put in the collision, I think it killed the form detail page.
Therefore Search.gov isn't indexing it so we're not getting anything in the search.

Dave Conlon  1 minute ago
next steps would be to get content in there for a Forms Detail page and then also consider a "Best Bet" for this form.

Nicole Leonard  1 minute ago
Ok. We should def fix that.
New

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/CUB5X5MGF/p1641925529034600?thread_ts=1641585715.002000&cid=CUB5X5MGF
