### ISSUE TITLE
Site shutdown checks 521QA

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35051]
## Description
Site 521QA (Callahan, AL) is no longer active and has been shut down.

To the extent feasible, we should test the frontend experience for a user registered at this site. The goal is that a user cannot schedule/request an appointment at this site.

### Technical
- Run scenario in Review instance

### Product
- Document validation checklist

**Comment by grossb1** [comment]
@marcynadeau said we could close this one after verifying that 521QA hasn't received any 'traffic' in a few months.
