### ISSUE TITLE
Compare 686 form submission data structure to 686 form Schema to determine inconsistencies

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#3505]
## User Story
As a frontend engineer, I want to resolve validation errors in the Dependents workflow so that I move forward with getting that form completed.

## Considerations
When submitting the rainbows team form 686 there is a validation error at the end of the form shown in the Redux form state object. This error is not coming from the validation of the data entered into the form but rather from the shape of the data structure in comparison to the shape of the JSON schema for the form. We need to determine where the inconsistencies are, aided by notes from the previous front end engineer on the project Erik Hansen, so that we can determine a path forward to fixing them.

[Notes from Erik Hansen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/NotesFromErikHansen.md)

## Goal
We want to establish the depth and scale of how much needs to be fixed in the form 686 as well as what the specifics of fixing it looks like so that we can determine the best path forward to getting the form working on production.

## Tasks
- [ ] Compare data structures

## Acceptance Criteria
- [ ] Document [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering) in GitHub inconsistencies between the form submission data shape and the shape of the JSON schema for the form.

**Comment by micahchiang** [comment]
I've just started some initial investigation into the issues with the current 686, and have updated [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686FrontEndResearch.md) with a list of everything found thus far. Will continue to add notes.
