### ISSUE TITLE
Update Collaboration Cycle - Contact Us page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35054]
## Issue Description
The[ Contact Us page ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-us.1764524036.html)under the Collaboration Cycle section of Platform Website needs to be updated to reflect the current resources. The page should state:

Practice Area specialists

Design: Allison Christman & Sean Sewell 
Content: TBD
Information Architecture (IA): Jim Ryan 
Quality Assurance (QA):  Dariusz Dzien 
Accessibility: Brian DeConinck & Sarah Koomson
Product: Shira Goodman 
Research: Shane Strassberg
Analytics: Michelle Dooley 
Privacy and Security: Thomas Delrue & Troy Mosher
Contact Center: Jason Woodman & Kimberley Monroe-Daniels 

Right now, the practice area specialists are headers and not consistently applied:
![image](https://user-images.githubusercontent.com/71330581/148816697-5173f2cd-0866-4589-891a-67c816ba978a.png)

This ticket should have 'Practice area specialists' as the header and the roles/people listed underneath not as headers.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@chaseakirby @shiragoodman this is ready for your review https://vfs.atlassian.net/wiki/spaces/PPST/pages/2050457666/Allison+Copy+of+Contact+us
