### ISSUE TITLE
Feedback Tool - Remove references to 1607 benefit

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#35063]
## Issue Description
Rodney Hopkins with EDU requested an update to the Feedback Tool by removing references to 1607.  The 1607 benefit appears to be located in Step 2 of 5: under Education Benefits [see attachment]. 

## Tasks
Removing references to 1607

## Acceptance Criteria
Remove references to 1607

## How to configure this issue
- [X] **Labeled with Practice Area** (`frontend`)
- [X] **Labeled with Type** (`request`)

Attachment:
[https://app.zenhub.com/files/133843125/83be00eb-8628-4537-9662-3d890c330828/download](https://app.zenhub.com/files/133843125/83be00eb-8628-4537-9662-3d890c330828/download)

**Comment by nbarthelemy** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/669

**Comment by nbarthelemy** [comment]
The PR was merged in to the vets-json-schema repo. I assume the deployment will update the gem in the vets-website. If not, I may need to update the gem on vets-website and submit a PR for that.

**Comment by mrblanco1** [comment]
@af-manish - Hi! Can you please work with Nick on this issue? Thanks!

**Comment by nbarthelemy** [comment]
I was able to find some [instructions](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/sidekiq-enterprise-setup.md) on updating the schema across the apps:

Follow up PR for vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/20087
Follow up PR for vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/9004

**Comment by hallihocine** [comment]
- Test run in test rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2894&group_by=cases:section_id&group_order=asc&group_id=3649
- Test steps: 
[Feedback Tool - Remove references to 1607 benefit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8043683/Feedback.Tool.-.Remove.references.to.1607.benefit.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT Passed on 2/14/2022.
