### ISSUE TITLE
[Design] Optimize Poster for Size 8.5 x 11

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35061]
## Description 
Current day-of check-in poster is not optimized for 8.5 x 11. This item is to address that and make poster available in that size for clinics if they choose.

**Comment by julieadair1** [comment]
## Description
Currently the poster is 24x36 or 11x17.  We need to optimize it for 8.5x11.

**Comment by julieadair1** [comment]
## Acceptance Criteria
1. Link the final pdf design to the github page : https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral
2. Post the final design to sketch for teams or sketch cloud.

**Comment by zach-park** [comment]
8.5x11 version of the check-in poster is ready for review now at:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral
Cc: @jparker0425 @julieadair1 @kristenmcconnell

**Comment by julieadair1** [comment]
Reviewed.  Looks great!

**Comment by jparker0425** [comment]
Agreed, looks good to me @zach-park !
