### ISSUE TITLE
Accessibility Research Synthesis

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35068]

**Comment by Vngpire** [comment]
[Affinity Mapping](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1641929777317/3e0480460973aaf0fd1c963a95a9d99df9b34d0a?sender=uf0a37d7d95f814df24ee3557)

[Identity Sign-In A11y Readout](https://docs.google.com/presentation/d/1tkzq7cem96L1Va7vEYXF-0Jdrt61RVBA/edit?usp=sharing&ouid=112061296914247135510&rtpof=true&sd=true)

Aiming to get the research down to GitHub. Might take me a bit more time than usual.
