### ISSUE TITLE
[BE] Update vets-api dev environment settings to point to the LoROTA dev environment

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#35067]
## Description
Currently, it's pointing to 'int' environment, whereas it should point to 'dev'.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on dev.

**Comment by acrollet** [comment]
This turned out to be a mistaken priority, the CHIP team prefers dev.va.gov to point at their integration environment. (ref: https://dsva.slack.com/archives/C02G6AB3ZRS/p1641916791100900?thread_ts=1641848561.089900&cid=C02G6AB3ZRS)

Closing to no action.
