### ISSUE TITLE
Discovery: Github Actions API Capabilities

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#35065]
For the console UI work we need to know the capabilities and limitations of the Github Actions API. We need to get and strong understanding of how the API can talk to the console and also how the console can talk to the workflows.

Questions to answer:
- Can we communicate the status of a workflow with the console? (e.g. a failed deploy)
- Can the console trigger a workflow (e.g. retry a failed deploy or trigger a new one to any environment)
- Can we output workflow logs and information from github actions into the console display?

**Comment by alexandec** [comment]
I've created a [Google Doc](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk) to record my GitHub API findings. Initial findings are already recorded. I'll continue to update the doc as I learn more.

**Comment by alexandec** [comment]
@timwright12 I've added a lot of information to the Google Doc. See what you think of that. I'm happy to expand any of the areas, or explore new pieces if needed.

**Comment by alexandec** [comment]
We've confirmed in [the prototype](https://github.com/department-of-veterans-affairs/console-prototype-release-tools) that we can fetch the data we need, and perform the required actions, with the GH API. The [Google Doc](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.hwy3rcbtf3j0) contains further information. Closing this.
