### ISSUE TITLE
[1/14/2022] Submit request for shared AVS Email Group

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#35074]

**Comment by jwowk** [comment]
Rob said AVSUserGroup@va.gov is already in place. Need to determine if this is a mailbox or distro group and whether we want to change to something simpler like AVS@va.gov or AVSSupport@va.gov.

**Comment by aschulhof** [comment]
Our preference is for shared inbox. Paras to put in SNOW ticket. Let's request AVS@va.gov

**Comment by chancetheoriginal** [comment]
Request submitted: REQ6315234.
