### ISSUE TITLE
[SOCKS] SSH service fails due to name resolution failures (DNS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35078]
## Description
There was a recent issue where users were unable to connect to the network via the SOCKS proxy. A problem with DNS name resolution prevented the SSH service from starting on SOCKS-related instances. SOCKS is dependent on SSH working properly to establish connectivity for end-users. 

## Background/context 
- Initial report in #vfs-platform-support channel in [this thread on DSVA Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1641326833292800) (see note from Demian Ginther [here](https://dsva.slack.com/archives/CBU0KDSB1/p1641397867319500?thread_ts=1641326833.292800&cid=CBU0KDSB1))
- Discussion with Infrastructure Team in #vsp-operations-internal channel in [this thread on DSVA Slack](https://dsva.slack.com/archives/CTYQL39FE/p1641398871452800)
- The issue was caused by the SSH service failing to start because of failed name resolution on the instances in question
- Name resolution was failing because on those instances because they are configured to use localhost for resolution but the DNS service (BIND) would not start
- Bind was failing to start due to duplicate entries in zone files
- There were duplicate DNS entries in the zone files in question because of a process in Jenkins (related to review instance deployment) that allows users to manually specify a host entry 

## Related Issues
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20495
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21027

## Technical notes
- According to members of the Infrastructure team, BIND may no longer be a requirement on those machines
- It's possible that the machines in question can be configured to use Route53 
- There should be some protection against the creation of duplicate DNS entries
- The manual specification of DNS entries (without validation) should also be avoided 

---
## Tasks
- [x] _What things need to happen?_

## Acceptance Criteria 
- [x] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jhouse-solvd** [comment]
Please also see #21027 for a related issue.

**Comment by jbritt1** [comment]
Pretty confident this issue was resolved by the above linked pull request, but will leave this issue open a bit longer as we monitor for any new occurrences.

**Comment by jbritt1** [comment]
Plan is to continue to monitor today and if the issue is not observed to close this Monday 3/7.

**Comment by jhouse-solvd** [comment]
The core of this issue was essentially a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/20495

This has now been addressed. See #20495 for relevant PRs. 

Closing.
