### ISSUE TITLE
Content review: View Dependents mockup

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#3507]
## Story  
As a member of the eBenefits team building with VSP, we need our content reviewed before a usability session to ensure it's accurate, aligns with VA style, and is error-free.

## Goal  
**Content:** To review the content in the [**View Dependents**](https://xd.adobe.com/view/bfe6786c-67a3-4bdf-5d4d-7a98f900ebc7-c9d7/screen/42d53597-0b53-4b17-9ba2-56f0e7dd4fd4/View-Dependents-1/?x_product=cc-slack%2F1.4.0) mockup.

**Comment by peggygannon** [comment]
@sporeboy @jason-gcio Hello, I took a preliminary look at the View Dependents mockup and I think we need further conversation on how this page fits with the current Add Dependents page: https://www.va.gov/disability/add-remove-dependent/
 
I know you are early in your design and research, but I think we should discuss entry points and content soon, so we can determine how this page will be found and how it fits with the current dependents page. 

some things I noted from my prelim review: 
- How users will get to the View Dependents page? Are you thinking there'd be a CTA button on the current Add Dependents page to take users to this tool? 
- The same Eligibility content appears on the View Dependents mockup and the Add Dependents eligibility box.  As much as possible, we should point users to the Add Dependents eligibility content, not have duplicate content.

cc'ing @mnorthuis @jenniferlee-dsva @Karak888

**Comment by jason-gcio** [comment]
Hi @peggygannon,

Yes, I agree that there quite a few options as to where the links that lead to these pages go.  I was thinking a link on the "/add-remove-dependents/" page that said something like, "View My Dependents" could go to "View Dependents" (or however that gets renamed) after authentication, and have the current green button that sends them to eBenefits be changed to something like "Update/Modify My Dependents" which would take the Veteran to "Update Dependents" (or however it gets renamed) after authentication.

Does this make sense? 
cc: @sporeboy

**Comment by mnorthuis** [comment]
@jason-gcio have you talked with Samara on the authenticated experience team?  Wondering if this information is actually part of profile and not buried within disability.  We should have some discussions around where this ultimately lives.

**Comment by jason-gcio** [comment]
Definitely @mnorthuis!  I'll see about setting up a call and check in with you in Slack if that works?

**Comment by jason-gcio** [comment]
@peggygannon I think we can close this as we have an idea where "View Dependents" is going to live (off the root) and we have summarized the list of inbound and outbound points.  We would like to request a more formal review of the content.  I'll close this and create a new ticket if that sounds ok to you.

**Comment by peggygannon** [comment]
@jason-gcio Yes, sounds good. Please open a new ticket for a more formal Content review. I'll look out for that!
