### ISSUE TITLE
release playbook performance optimization

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3509]
## User Story or Problem Statement
The current release process of vets-website uploads dev, staging, and production builds to the release API, and does so sequentially. Together, they make up almost 90s of the time to do a release. How might we improve this?

## Goal
Reduce the release time for vets-website to 30s using a combination of cleaning up tasks that maybe aren't strictly necessary or parallelizing tasks that are currently done sequentially.

## Objectives or Key Results this is meant to further
Enable agile VFS delivery of performant applications

## Acceptance Criteria
- [ ] Release times for vets-website job are consistently around 30 seconds

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by benniemosher** [comment]
Code ready to be merged, currently sitting in code freeze:

https://github.com/department-of-veterans-affairs/devops/pull/6157

**Comment by wyattwalter** [comment]
Merged today!
