### ISSUE TITLE
Pagination web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35098]
## Description
Build a web-component version of our [Pagination React component](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/react-components/src/components/Pagination).

## Details
Styles: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/8ce0431d342a5be24170d9329e19257eb6e678db/packages/formation/sass/modules/_va-pagination.scss

This work was started a few months ago in [this PR](https://github.com/department-of-veterans-affairs/component-library/pull/84). We would need to start a new PR as the repo is structured differently now, but we could use this work as a starting point.

## Acceptance Criteria
- [ ] `va-pagination` is written
- [ ] E2E tests are written
- [ ] component is checked for accessibility issues
- [ ] Alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by andresriveratoro** [comment]
We have an opportunity to update the HTML structure to be more semantic for this component using `nav`, `ul` and wrapping buttons in a `li`. We should also look into the "..." button. It has no onclick functionality, but looks exactly like the other buttons in the pagination component. I've noticed Pagination components from other design systems display it as text and cannot be focused or clicked.

**Comment by pdavies88** [comment]
General note for whoever picks up the ticket please reach out to @Mottie if you have questions about the [initial PR](https://github.com/department-of-veterans-affairs/component-library/pull/84)
