### ISSUE TITLE
Table web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35107]
## Description
Build a web-component version of our [Table React component](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/react-components/src/components/Table).

**Update**
This ticket is only for the basic component. Sort functionality will be added separately. Acceptance criteria have been updated.

## Details
Styles: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/8ce0431d342a5be24170d9329e19257eb6e678db/packages/formation/sass/modules/_m-table.scss

There is a very [old in-progress branch](https://github.com/department-of-veterans-affairs/component-library/tree/wc-table) with a start on the table web component. Might be good for inspiration

## Acceptance Criteria
- [ ] `va-table` basic functionality is written
- [ ] E2E tests are written
- [ ] Merge component - add notice that component is not ready for use in Storybook.

**Comment by k80bowman** [comment]
React Table bug to be aware of: https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/595

**Comment by itsnotpavani** [comment]
I wish to get started out on this issue .It would be great if someone helps to let me know more about it.

**Comment by k80bowman** [comment]
@CourtneyChambers77 before we start development work on this, could you please review the [Table React component](https://design.va.gov/storybook/?path=/docs/components-table--default) and add comments to this ticket about any accessibility issues you find?

**Comment by CourtneyChambers77** [comment]
When using the keyboard and selecting the Tab key using navigating the table can't sort the data within the table this is not accessible

**Comment by k80bowman** [comment]
Table accessibility issue to be aware of: [Update current tables with caption component for accessibility reasons](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/9717)
