### ISSUE TITLE
utilize artifact feature in jenkins to pass builds of vets-website between jobs

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3510]
## User Story or Problem Statement
One slow step in the deployment of vets-website to production is a download of the release artifact from GitHub. Storing this asset in GitHub is something we do need to do, but we can keep these artifacts locally inside Jenkins and pass them between jobs to cut out this longer step. How might we utilize this artifact locally through our Ansible playbooks instead of downloading from GitHub?

## Goal
Utilize the artifact feature in Jenkins so that we can only do local file copies and cut out a long download time from GitHub to get the files to deploy to vets-website.

## Objectives or Key Results this is meant to further
Enable agile VFS delivery of performant applications

## Acceptance Criteria
- [ ] Deployment of vets-website does not need to download from GitHub

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
@nathanhruby the deeper I get on #3509, the more that I think that ticket and this one are the wrong solutions to the problem. We're not likely to ever get the upload to under 30 seconds to GitHub. I think we should turn our attention on that task to using S3 (either keeping the files in place and updating tags or uploading to a separate releases location) which would be much faster and more reliable since we can use VPC endpoints for it. Then, this task becomes irrelevant as the download should happen in a couple of seconds. We could avoid a lot of complexity for not a lot of gain here by doing that and skipping this particular task.

**Comment by nathanhruby** [comment]
This is about keeping a local cache in jenkins so the build product is available throughout the pipeline without any external dependencies.  That said, I think we thought about this as a solution not knowing/remembering that all the builds are already shipped to s3 per ref.

What I assume as well was that we *must* upload releases to githib for some contractual reason.  If that's not the case, then yes, let's stop doing the github uploads.  

Since I'm about to change the prod builds to look up the ref and pull it from s3, I don't know if we really need to add extra releases, they are resolvable from the git tag.

[sidebar: this is also somethign we'd re-evaluate later if we decided to use a better / deifferent artifact repository than github releases]

**Comment by wyattwalter** [comment]
Yeah. I am not finding a reason that we must upload to GitHub. I'm going to say we can stop doing that. That doesn't happen for things that get bundled up as AMI's, so there's really no reason that this has to be special. I don't see any justification for it anywhere historically.

The primary reason that I'm advocating for not doing this is that 1) if we can use S3, it negates a lot of the benefit for this solution and 2) there's enough jobs involved here that I think we're going to create further mazes of dependencies between jobs if we start having to pass artifacts around and keeping track of what's where. I'm primarily worried about what it looks like getting artifacts between the build and release since they aren't technically downstream/upstream jobs. If they're uploaded to S3 and then downloaded quickly for a deploy, we're adding a good deal of complexity for a few seconds worth of benefit.

**Comment by nathanhruby** [comment]
closing this since we're not doing it.
