### ISSUE TITLE
[Research] Moderate usability research on 10-10CG sign as rep/ doc upload

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#35115]
## User Story

As a legal representative of a Veteran or a Veteran, I need to know who should sign this application in my circumstance and what documents I should and should not upload, in order to prove that I have the legal right to represent the Veteran.

## Expected Behavior

- Moderate and run research on 10-10CG content

## Acceptance Criteria
- [x] Research plan & conversation guide sent to recruiting
- [ ] Moderate research

## Resources
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/Sign-as-a%20Rep-Round3-Oct2021/Usability%20research/usability-research-plan.md)
- [Conversation guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/Sign-as-a%20Rep-Round3-Oct2021/Usability%20research/conversation-guide.md)

**Comment by hdjustice** [comment]
Hi @Dene-human I believe the Milestone tagged on this ticket may not be right for your team, it is coming up under my team's milestone.

**Comment by Dene-human** [comment]
> Hi @Dene-human I believe the Milestone tagged on this ticket may not be right for your team, it is coming up under my team's milestone.

@hdjustice You are totally right! Thanks for catching this. I have cleared it.

**Comment by Dene-human** [comment]
@SKasimow Why was this moved into icebox? I believe this should be closed, correct?

**Comment by SKasimow** [comment]
@Dene-human I'll close. Where are you seeing that I moved it to Icebox?
