### ISSUE TITLE
Set Up High Availability Keycloak in K8 

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35112]
1. build one in dev cluster and make sure we know how everything works
2. move to utility cluster
3. use HELM chart

Create Database, parameter store, values in terraform

**Task is done when:** HA Keycloak installed in utility VPC

**Comment by ken-non** [comment]
linked to #10573

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/272
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/273
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/274
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/276

**Comment by dginther** [comment]
Deployed at https://keycloakvfs.va.gov

![Screen Shot 2022-01-17 at 2.24.57 PM.png](https://images.zenhubusercontent.com/5ce30eebaa8711267b95ebdf/33827716-8a92-4a7f-a32a-43bba1d383eb)![Screen Shot 2022-01-17 at 2.24.37 PM.png](https://images.zenhubusercontent.com/5ce30eebaa8711267b95ebdf/e29d1762-2d5f-444e-8a1a-c1dee411048e)

Admin password provided to Carl Aquisola, Harshil Moradia and Kevin Duensing via keybase
