### ISSUE TITLE
[MCP] Change 'Learn how to pay your copay bill' to 'Pay your copay bill' per staging review feedback 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35111]
## Issue Description
We received feedback during staging review that the 'Learn how to pay your copay bill' button and link language isn't descriptive and/or their purpose isn't clear. Users may think they're being redirected to a tutorial. To make the action more direct, we have been advised to update it to 'Pay your copay bill'. 

[View the updated UXPin here. 
](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141834693/simulate/sitemap?mode=i)

**Screenshot for reference:**
![Screen Shot 2022-01-11 at 11.07.47 AM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/648b3967-46f5-4fbd-bf2d-17b366361180)

---
## Tasks
- [ ] Update the content on the facility's detail page from 'Learn how to pay your copay bill' to 'Pay your copay bill'

## Acceptance Criteria
- [ ] The detail page's UI has been updated with the new content

**Comment by denisecoveyduc** [comment]
Hey @craigwheeler think we could pull this one into Sprint 65? Needs an estimate though. let me know what you think.
