### ISSUE TITLE
[UX] Screen Reader Testing of PCI and CI

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#35126]

**Comment by julieadair1** [comment]
Review with Angela Fowler.  Scheduled for Thursday 1/13.

**Comment by niradatta1** [comment]
@kristenmcconnell @ytsaoca Documented in git-hub:
- [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/checkin/research/accessibility/conversation-guide.md)
- [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/checkin/research/accessibility/research-guide.md)
- [researching findings ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/accessibility/research-findings.md)(still need to populate)
