### ISSUE TITLE
[Spike] Update button on the Past status page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#35128]
## Background/Request
The team is working on re-organizing the VAOS homepage status list. On the Past status page there is an Update button that the veteran clicks after selecting the time period. Once the user clicks on Update, the UI gathers the past appointments for the given time frame and displays the list to the veteran. 

### Goal
To remove the Update button on the Past status page. 

### Requirements to Consider
If the Update button is removed: 
- The default view will display the appointments for the past 3 months. 
- If the user wants to change time periods, they will select the timeframe from the dropdown. Once it has been selected, the UI will display the selected period. 
---

## Tasks
- Answer the following questions:
  - Will there be a performance issue if we remove the Update button? 
  - Can the user toggle between the time periods and have the UI display the selection on the screen? 

## Time Box
3 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

## Design Spec
[New Past status page](https://www.sketch.com/s/7ceea77b-e368-4ed1-af98-3b7c57cf3124/a/bgvA444)

**Comment by jenniemc** [comment]
1. Performance will NOT be hampered when `Update` is deleted. 
2. User can toggle the timeframe from the dropdown and auto update display of the past appointment list on the UI

Technical notes: 
From the component file `PastAppointmentsDateDropdown.jsx`,  remove the button tag and move the onChange event handler after the state variable declaration. See example below.

```
Export default function PastAppointmentsDateDropdown({
  currentRange,
  onChange,
  options,
}) {
  const [dateRangeIndex, updateDateRangeIndex] = useState(currentRange);
  if (currentRange !== dateRangeIndex) {
    onChange(dateRangeIndex);
  }

  return (
    <>
      <label
        htmlFor="date-dropdown"
        className="vads-u-display--inline-block vads-u-margin-top--0 vads-u-margin-right--2 vads-u-margin-bottom--0 vaos-hide-for-print"
      >
        Select a date range{' '}
        <span className="sr-only">for your appointments</span>
      </label>
      <Select
        options={options}
        onChange={e => {
          updateDateRangeIndex(Number(e.target.value));
        }}
        id="date-dropdown"
        value={dateRangeIndex}
      />
    </>
  );
}

PastAppointmentsDateDropdown.propTypes = {
  currentRange: PropTypes.number.isRequired,
  onChange: PropTypes.func.isRequired,
  options: PropTypes.array.isRequired,
};
```
