### ISSUE TITLE
Access for Peter Lane

### ISSUE THREAD

**Issue by mendacitees** [department-of-veterans-affairs/va.gov-team#35122]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Peter Lane

### Your Email

peter.lane@adhocteam.us

### Name of Your Team

VSP Design System Team, Ad Hoc, Senior Software Engineer

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1CT8AWri2wJgnLIzF03sbzcotWmrABEDibgYBZb9TYlL5Os0qBJmtPmUwyaar9zfm2tIn6KUS073vtJp5U4U6MSpk9DpW82dHOd8WleKaqe2XeWP1isPqyVv+DC1NRgrtKQVjtYUEOOrzqnB/lBCnEMP59p/hMf3T2vannkYSSQcCInJ1+cDDSrXMvhgZpEAKmlqKjFjsJAjriyBOUav6+QA/dWJRA/RABt2ZRjQaR+L6HRKKhDCOa3cOj02QLuCGRCOpKMRwMFyA0HZPa/7rtZcp9X/y23yZAS9QvPWX13cI2m+ESyZULYW9sQsHJQ71CcTPamLeD9KBLh/cgEdbxeW7Eq2cz5Vs5tdlY5LptL02hKH5tFtX9GlPixRZBtlV35iUjTDan7F5uKpTngdBNFUzUHl/kujrFc5FLmsKiJ0Vohtc4ZIiFrj4OAPqYjrsMz7cxesV/emJj1VMO8Y4ETrf7//c5atlZq18yLoragl0VQ3MN6f2YGmW7Rj9N58= peter@PeterLane-HP

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
