### ISSUE TITLE
[UX] - Determine Research Timeline(s) with St. Louis

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#35121]
## Description
Several things are happening at St. Louis this sprint and we'll need to coordinate timing.  We can use this ticket to track that coordination plan.  
1. Pilot go live(s) - estimated date 1/24
2. appointment notification research - MSA Supervisor, my healthevet coordinator (site's coordinator), clinic managers and an MSA will be needed.  Ideally we talk to these folks at both a CBOC and a larger VAMC.
3. Research plan for MSA's to gather feedback on pilot program (check-in)

**Comment by kristenmcconnell** [comment]
I met with Julie today to go over the exact ask we have for St. Louis. She is going to begin recruiting MSAs for the pilot feedback tomorrow during the training sessions. The plan is to talk with Katonya Riddle, who may be able to help us identify participants for the appointment notifications study.

**Comment by kristenmcconnell** [comment]
Met with St. Louis on Friday, January 21. They are putting together a list of staff that we can talk to.

**Comment by kristenmcconnell** [comment]
We are estimating that we can start getting feedback from MSA and staff on the pilot sometime next week. The appointment notifications study still needs to have staff identified.
