### ISSUE TITLE
[Bug] Medical Copays - Content anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#35129]
## What happened?
On Staging Medical Copays, authenticated Balances and Detail pages, some content anomalies were found:
1. **Balances** page: In **Not-enrolled-in-health-care** alert, there's a **space between phone number & comma**.
2. **Detail** page: In **main** alert, there's also a **space between phone number & comma**.
3. **Detail** page: Under **How do I pay...** section, in expanded **Option 1** expanded-accordion, there's a  **space between phone number & period**.

## Specs:
- Device: \[device-agnostic\]
- Browser: \[browser-agnostic\]
- Test Users: `vets.gov.user+3@gmail.com` (Kenneth); `vets.gov.user+81@gmail.com` (Travis) [passwords on [private repo page](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)].

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/pay-copay-bill/ (landing page)
- Sign-in as **`vets.gov.user+3@gmail.com` (Kenneth)** \[not enrolled in healthcare\]
- On landing page, click **Review your current copay balances** CTA-link
- On **Balances** page, in **Not-enrolled-in-health-care** alert, 2nd paragraph, observe that (1) there's a **space between phone number & comma**.
- Sign-out, then back in as **`vets.gov.user+81@gmail.com` (Travis)** \[active/resolved bills, multiple facilities\]
- Back on **Balances** page, click an active **balance**-card.
- On **Detail** page:
  - In **main** alert (light-blue), last paragraph, observe that (2) there's a **space between phone number & comma**.
  - In **How do I pay** > **Option 1** expanded-accordion, last paragraph, observe that (3) there's a  **space between phone number & period**.

### Screenshots

**Balances** page > **Not-enrolled-in-health-care** alert:
![mcp-bug-overview-content](https://user-images.githubusercontent.com/587583/149001425-fdd78753-d051-4b1a-a426-20bb23b49b24.png)

**Detail** page > **main** alert:
![mcp-bug-detail-content1](https://user-images.githubusercontent.com/587583/149001574-8c919932-47e3-4f35-957c-8ba145704195.png)

**Detail** page > **How do I pay** > **Option 1** alert:
![mcp-bug-detail-content2](https://user-images.githubusercontent.com/587583/149001642-0be93293-6d91-4d4d-966c-e67bbc263fcb.png)

## Desired content
There should be no space between phone numbers and subsequent punctuations:
1. [x] in **Balances page's **Not-enrolled-in-health-care** alert
2. [x] in **Detail** page's **main** alert
3. [x] in **Detail** page's **How do I pay...** > **Option 1** alert

## Acceptance Criteria
\[see **Desired content** above\]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by craigwheeler** [comment]
hey @tlei123... just merged fixes for this and should be live on staging now if you wanna close this ticket thanks

**Comment by tlei123** [comment]
Closing.  Validated on Staging.  Thx, @craigwheeler !  :)
