### ISSUE TITLE
Product-Focused QA Dashboard Research

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35123]
# Description
We need to create a new dashboard in Domo that allows viewer to focus on a single product hosted on VA.gov at a time. This effort will provide teams with just the information they need about their QA practice as it pertains to a specific product.

## Context for this work:
- Establish tracking for the KRs to support our objective/initiative
  * KR1: >20 unique QA Dashboard users on average per sprint
  * KR2: >8 of VA.gov products are getting weekly views
  * KR3: >10 VFS Products have a QA Product View
- Research what we're doing and how we'll do it
- Develop it
- Launch it

**Comment by rjohnson2011** [comment]
Discussed the structure of `manifest.json` files along with `product_id`s. Brainstormed the creation of UIDs.

**Comment by rjohnson2011** [comment]
Added an update of products to the `product-directory` repository.
