### ISSUE TITLE
optimize sync times of files to s3 for vets-website builds

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3512]
## User Story or Problem Statement
The current implementation to deploy files to S3 for vets-website utilizes the s3_sync module from Ansible. This was a convenient Ansible-native way to push these files and worked fine when we did fewer deploys and had fewer files. We're now seeing minute+ file syncs, which creates very slow deploy times. How might we optimize this to not spend more time than necessary syncing files?

## Goal
Switch s3_sync module usage in Ansible to the command module with `aws s3 sync`, translating options across.

Tune options for the module to make this as fast as we can. Goal time is 10s for a single sync of files.

## Objectives or Key Results this is meant to further
Enable agile VFS delivery of performant applications

## Acceptance Criteria
- [ ] Deployment of vets-website does not need to download from GitHub

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nathanhruby** [comment]
As noted in first pass PR, we need to check the call to deploy in the prod deploy Jenkinsfile to use ref to download form s3 (since that is how the patching work in the bucket)

**Comment by nathanhruby** [comment]
This is done, finally
