### ISSUE TITLE
Print view update 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#35137]
## Description
Currently when the veteran prints their appointment list, the user will receive a printed view of the VAOS homepage with their appointments listed. We will need to revise the print view so that the user will receive a clean and organized list of their appointments when printed. 

Current state of when the user does a print view: 
<img width="1433" alt="Screen Shot 2022-01-11 at 1 29 46 PM" src="https://user-images.githubusercontent.com/90797205/149003578-e34dda84-3231-4b5b-acf9-ef881b58a10a.png">

---

## Acceptance Criteria

Given when the veteran is in the VAOS homepage 
When the status of the appointment is Upcoming
Then the veteran clicks on print, the print view page matches the [design spec](https://www.figma.com/file/MNanAQBGzQbRJeb89d1OVz/VAOS-IN-Reschedule-and-home?node-id=5%3A15345). 

Given when the veteran is in the VAOS homepage 
When the status of the appointment is Requested
Then the veteran clicks on print, the print view page matches the [design spec](https://www.figma.com/file/MNanAQBGzQbRJeb89d1OVz/VAOS-IN-Reschedule-and-home?node-id=5%3A15306).

Given when the veteran is in the VAOS homepage 
When the status of the appointment is Past and user selects the time period
Then the veteran clicks on print, the print view page matches the [design spec](https://www.figma.com/file/MNanAQBGzQbRJeb89d1OVz/VAOS-IN-Reschedule-and-home?node-id=5%3A15267). 

Given when the veteran is in the VAOS homepage 
When the status of the appointment is Canceled
Then the veteran clicks on print, the print view page matches the [design spec](https://www.figma.com/file/MNanAQBGzQbRJeb89d1OVz/VAOS-IN-Reschedule-and-home?node-id=6%3A16064). 

Design Spec Example - Your appointments (Upcoming status) 
<img width="433" alt="Screen Shot 2022-01-11 at 2 42 15 PM" src="https://user-images.githubusercontent.com/90797205/149010414-c38f7904-2137-41f1-b356-6dfdcd8cb1e5.png">

### Design Assets
[Design Specs](https://www.figma.com/file/MNanAQBGzQbRJeb89d1OVz/?node-id=5%3A14770)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@vbahinwillit - I tried to validate the changes in staging and it looks the same. Could you please confirm if your changes have been implemented in staging? ![Screen Shot 2022-01-24 at 6.12.40 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/9e082fbc-45ca-484e-8e5d-460e3302ba89)

**Comment by vbahinwillit** [comment]
GM. Just confirmed and the appointment list print changes appear to be in staging. The screenshot is for COVID.

**Comment by ldelacosta** [comment]
Per our discussion, the changes have not been implemented in staging (at least when I tried to test it). Please see latest screenshot. Thanks. ![Screen Shot 2022-01-25 at 11.58.59 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3b837b40-02ca-4327-abb5-d57a4cf3b30c)

**Comment by ldelacosta** [comment]
Validated the changes in staging and the print view for the appointment list has been updated 

![Screen Shot 2022-01-26 at 3.45.28 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/a0f59efe-4fcf-40b2-8895-4214bfaf5e3b)

![Screen Shot 2022-01-26 at 3.45.41 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7559ee93-ad1b-4932-8352-9cb986c9837a)

![Screen Shot 2022-01-26 at 3.46.10 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/6b3cde81-e022-4581-8105-7572eb61228d)

![Screen Shot 2022-01-26 at 3.46.33 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/85e59ea6-24bc-428f-af0b-4a37115c53d7)
