### ISSUE TITLE
vets-website release + deploy time improvements

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3513]
## Product Outline
[link]()

## High Level User Story/ies
As a content editor, I need updates to the website to go out much faster so I can get news and information out to Veterans and their caregivers faster. Currently the process takes about 10 minutes to create a new release, copy files around, and complete the deployment to production.

While there is larger work going on to improve overall build times, this epic is focused on the operations needed to perform a release and deploy that release to the website.

## Hypothesis or Bet
If we optimize file copy operations and I/O usage in Jenkins, we expect to be able to remove at least 5 minutes from this process.

## VSP OKR
Enable agile VFS delivery of performant applications

## Definition of done
From the time a release is initiated in Jenkins, it should be live on www.va.gov within 5 minutes.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by brandonrapp** [comment]
CMS Superteam information related to this work can be found here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/2778

**Comment by ricetj** [comment]
Done
