### ISSUE TITLE
Create a Workflow Document for Addressing E2E Test Failures in Master

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35136]
# Description
Per [this prompt](https://dsva.slack.com/archives/C01CHAY3ULR/p1641925379009300) from Tim, we should establish a process for resolving an E2E test failure during the master CI workflow.

Maybe this looks like a triage workflow with a few branches. At the end of each branch is a clear action to take. Eventually this may be a responsibility we could pass off to SRE team given a good enough document.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/2108948599/Resolving+E2E+Test+Failures

**Comment by pjhill** [comment]
This is great. I made a few grammar-type edits, and will re-publish. Thanks for whipping this up!
