### ISSUE TITLE
Table web component: migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35133]
## Description
Dependent on #35107

Write the ESLint rule for the Table web component.

For an example ESLint rule, see https://github.com/department-of-veterans-affairs/vets-website/pull/20002

Create guidance for converting existing patterns inside the Liquid templates to these components and add it to our [Liquid template migration guidance ](https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance)Confluence page.

## Acceptance Criteria
- [x] write ESLint rule
- [x] test ESLint rule
- [ ] Add Liquid templates conversion guidance to Confluence page

**Comment by caw310** [comment]
Decision made that we will not support sorting in IE 11.

**Comment by bkjohnson** [comment]
Liquid template guidance has been [added to Confluence](https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-table).
