### ISSUE TITLE
Table web component: Announcement and documentation update

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35148]
## Description
Dependent on #35107 and #35106

Announce the component at least in the #vfs-frontend channel. Might be worth reaching out to the teams who work on the static page templates as well.

The Pagination React component is used in several applications, we could reach out to the teams that manage them and encourage them to migrate.
- messages
- disability-benefits
- personalization

Add component to Storybook, update component documentation in design.va.gov, and add note about component release to the [What's new?](https://design.va.gov/documentation/whats-new) page.

## Details
Sample announcement:

>:wave: The Design System has just published a new version of component-library which includes <va-additional-info>, as well as made it available in vets-website. The migration script is also capable of automatically migrating your directories to this new component.
Why does this matter to me
The new additional info Web Component has a number of  enhancements/fixes:
Keyboard control with space and "Enter" key
Design fix for the blue border when expanded
Improved colors for contrast & consistency
The web component is already loaded into the site, so removing your old AdditionalInfo imports will reduce application bundle size and improve performance.
How do I migrate
First, make sure your branch is using the latest master, and run yarn install.
We have a script that you can use to assist with this process. You pass it two arguments:
--directory - the directory you wish to migrate
--component - the name of the React component to find and transform into a web component
For example, to run this migration in the platform directory, you would run:
yarn migrate-component --dir src/platform --component AdditionalInfo

>---
>*NOTE:* One change with <va-additional-info> is that it no longer exposes onClick for an external analytics event. There is still an internal component-library-analytics event that gets fired which includes the action (expand/collapse) and the trigger text. Just be aware of this so that you don't lose any tracking data that may be used in your dashboards. Reach out to us if you have any questions/concerns about this.

## Acceptance Criteria
- [x] Craft announcement and post in #vfs-frontend
- [x] Reach out to frontend teams individually about migration
- [x] Add component to Storybook
- [x] Update design.va.gov
- [x] Add note to What's new? page

**Comment by bkjohnson** [comment]
Current `<Table>` usage:

![image](https://user-images.githubusercontent.com/2008881/162027921-4d025704-2176-46cf-8f2f-f67e6801b48f.png)

- The team for "Debt Letters" [will be moving away from the Table component in favor of a list](https://dsva.slack.com/archives/CPE4AJ6Q0/p1649089224285829?thread_ts=1649088104.276469&cid=CPE4AJ6Q0)
- [Reaching out to team for "View Payments" app](https://dsva.slack.com/archives/CLY6Q69RV/p1649264174267969)
- "Medical Copays" appears to be owned by the debt team as well, so I added a comment to the earlier thread
- It's unclear who owns the "My Messages" app. The component is [used here](https://github.com/department-of-veterans-affairs/vets-website/blob/74a01a9fa884c93f571bcc4ce45c5e03971b3091/src/applications/messages/components/Table.jsx#L26-L46), but the [codeowner](https://github.com/department-of-veterans-affairs/vets-website/blob/74a01a9fa884c93f571bcc4ce45c5e03971b3091/.github/CODEOWNERS#L102) for `src/applications/messages` doesn't exist:    
    ![Issue with the team in codeowners file](https://user-images.githubusercontent.com/2008881/162040467-408aafd4-17a6-4001-92c6-b7af0aaa05fd.png)

- [Reaching out to team for "Dashboard"](https://dsva.slack.com/archives/C909ZG2BB/p1649268440975309)
