### ISSUE TITLE
[Authenticated Experience/Payment Information] VSA-QA Test Plan

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35149]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

The Authenticated Experience team is adding a new section called "Benefit payments and debts".  This section will display when a logged-in user has received payments at any time from VA.  This section will have a payment information block, showing details of the most recent payment made to the user;, a debt notification, showing the number of outstanding debts the user has; and a link that directs the user to manage their direct deposit information within the Profile page.

- Product/Feature Outline: [Payment Information Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history)
- Product/Feature Epic: [Payment Information Epic #31611](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31611)
- Product/Feature Copy deck(s): [Payment Information Mural Board](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=u5ad49c107baa41137f271007)
- Product/Feature Design prototypes: [Payment Information UX Prototype](https://preview.uxpin.com/45251888896c8dd47ef62aa20d3a89a334726ac1#/pages/145483168/simulate/no-panels?mode=i)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Liz Lantz
Content/IA: Danielle Thierry
Front-end: Taylor Mitchell
Back-end: Lihan Li
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**:  [Payment Information use cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] [Test Cases [in TestRail]](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=3309&group_order=asc&display_deleted_cases=0) finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@hdjustice , did the Use Cases doc get moved?  The provided link is now broken.

**Comment by hdjustice** [comment]
Hi @tlei123 It looks like the file was renamed.  I fixed the link above.  Thank you for letting me know!

**Comment by hdjustice** [comment]
Hi @tlei123 - I was finally able to get User #11 set up with a specific scenario (current debt with old >30 days payment history).  I updated the Use case document and the TestRail test cases with the user (Test case C13019).  I do see that the screenshots are slightly different layout than the staging environment.  I will check on that with the team today.  Please let me know if you have any questions (I am sure you would).  We are thinking it will be ready for QA in Sprint 67 (Feb 9-22), after our small post-research testing changes.

**Comment by hdjustice** [comment]
@tlei123 Hi Tze!  It looks like we will need to target Sprint 68 (2/23 - 3/8) for QA.  We have additional changes that will extend into the next sprint and will not be ready.  Please let me know if you have any questions or concerns.  Thanks!

**Comment by tlei123** [comment]
@hdjustice , let's plan on syncing up about the changes once they're ready on Staging or at least finalized, whichever's earlier.  I can then update my TestRail test-cases.

Thx much for the heads-up!  :)

**Comment by tlei123** [comment]
@hdjustice , I just checked the updated Use Cases, and the **test-users 36 & 21** for **No-outstanding-debts** cases actually have debts showing on Staging.

Does anyone on your team have bandwidth to find appropriate test-users (w/ no outstanding debts)?  Alternatively, does B/E have a way to update/fix 36's & 21's existing Staging mock-data to return no debts?

**Comment by hdjustice** [comment]
There is a PR pending final approval and deployment for a bit of the changes, I am just waiting for it to be completed in staging.  The development will address the scenario when the user has no debt.  That should resolve what you are seeing for those two test-users
