### ISSUE TITLE
List of all Benefit Hub URLs to be Redirected

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3514]
### **Task:** 
Create a list of all URLs by Benefit Hub with status of redirects for each page. This will be a master running list of URLs indicating which benefit hub pages have been redirected, and which ones still need to be redirected.  These URLs should be included as a single worksheet tab of spreadsheet for sorting and tracking purposes.  

### **Acceptance Criteria** 
- [ ] Compiled list of all benefit hub pages with redirect status in single tab on spreadsheet.

**Comment by Karak888** [comment]
This is a reference to the larger epic as it still contains info necessary for other teams, etc. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/1615

**Comment by Karak888** [comment]
@lunascoop - Please check with Mikki as this should encompass all redirect URLS she has captured in her tickets (consolidated into one spreadsheet).  The intent of this spreadsheet is to become the master tracker of all benefit Hub URLs to be redirected.

**Comment by Karak888** [comment]
@lunascoop is this still in progress, or did you decide on another alternative?  just checking, thanks!

**Comment by lunascoop** [comment]
@Karak888 meant to close this issue as Mikki will be responsible for tracking URL redirects. See Jen's comment on another ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/3273#issuecomment-559137628
