### ISSUE TITLE
Redirect Status for all URLs by Benefit Hub

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3515]
### **Epic Overview:**
In order to maintain and more easilly track the status of redirect work for benefit hubs, we will retire this larger epic "Coordinate Redirect work based on parity and rewritten legacy pages,"and replace with this Epic: "Redirect Status for all URLs by Benefit Hub." 
Please note that we will leave the larger epic open for reference information and can be found here:   #3514

**Comment by MickinSahni** [comment]
PW Grooming: 
Closing out this epic. Likely resolved by new process i.e. VSP redirect requests --> PW.
