### ISSUE TITLE
Communicate new GH teams process (defined by the Infrastructure team) in Platform Orientation 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35154]
## Background
Getting access to vets.gov-write is contingent upon the new VFS team member completing general orientation. This is the VFS-facing guidance on Platform Website. However this process isn't scalable, and the current guidance is failing. Governance Team has been unable to collect all of the GitHub handles at Orientation sessions due to the increased number of attendees. Even if all GitHub handles were captured, there are many individuals who have not yet gotten access to the VA GitHub organization, a prerequisite to getting Platform repo access. Instead, VFS teams request Platform repo access using alternate paths - a DM to Shira, a #vfs-platform-support request for the wrong team, etc. It has been difficult to manage and grant access appropriately. In addition, Product Support has struggled to include this step alongside the other orientation materials because the other orientation materials exist in a GitHub ticket - Platform Orientation template. Getting access to vets.gov-write is a prerequisite to being able to begin orientation activities.

Current Platform Website guidance:
![image](https://user-images.githubusercontent.com/71330581/149027911-8a8cc334-227d-4c86-a7eb-e5cd6fa2a3e4.png)

For more information, see [Getting new VFS team members read/write access to GitHub Platform repos](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1991802892/Getting+new+VFS+team+members+read+write+access+to+GitHub+Platform+repos)
## Issue Description
~This ticket will be the creation of a new process for TBD team to follow for granting new VFS team members access to vets.gov/write. The ticket will include updates to and creation of the following documentation:~
- ~Platform Website / Getting Started / Request Access to Tools / Github / Getting repo access~
- ~Operational guidance (to be created)~

## Updated Issue Description
VFS teams (product owners, program directors) should be responsible for setting up their own GitHub team, assigning themselves the appropriate repos, assigning a maintainer, and managing access for their team members. VFS teams should not be given access to vets.gov-write as that is the GitHub team that the Platform uses to manage access of Platform team members. The following tasks will be the responsibility of the Platform Infrastructure team:
 
1. Define a process for new VFS teams to follow.
2. Clean up vets.gov-write and create GitHub teams for existing VFS teams
  - identify what GitHub teams will need to be created
   - identify what repos those these should have access to (possibly modeled off of va.gov-vsa)
   - identify who should be the maintainer of the new teams
   - assign VFS team members to the new team
   - remove VFS team members from vets.gov-write
   - ensure VFS teams know how to manage their team, repos, members, and maintainers 

Governance team is available for assistance if needed.

The purpose of this ticket is to:

1. Communicate the new process defined by the Infrastructure team (per 1 above) via:
   - Platform Website / Getting Started / Request access to tools page
   - "New VFS Team" ticket
2. Update the VFS Team Roster to add the field GitHub team name 
3. Update the VFS Team Roster with the GitHub team names of existing VFS teams.
4. Identify which individuals in vets.gov-write are non-Platform and should be removed (to assist Infrastructure team if needed)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by troymosher** [comment]
@shiragoodman I reviewed the docs and had the following input from a security perspective:

With Github not being within our ATO boundary, it won't have any impact on compliance of our controls within the VFSP-va.gov package, but from an operational security perspective reviewing the doc a few thoughts:

-I can agree that orientation/training may not be necessary for an account, especially as the footnote states it doesn't appear to provide any fundamentally required info.
-Someone with authority should provide a valid access authorization for the access, especially in the absence of a training requirement. We shouldn't have folks gaining access with no traceback to orientation or a valid authorization.
-The actual act of granting of access should be done by OPs, not Prod support, based on authorization given by an authority (ie. not the user themselves).
-There doesn't appear to be a process for removing stale or old permissions for VFS team members that no longer have a need for access. ie. left the contract/org. Centralizing that valid access authorization with an approval can help maintain accurate lists/roster that could then be audited on routine schedule (quarteryl/annually) to remove folks who no longer have a need.

Would recommend they use Idea no.5, provides a valid access authorization from the PO, allows the roster to be updated and subject to an eventual meaningful audit for stale accounts, and has OPs as the implementer of granting the access.

**Comment by shiragoodman** [comment]
@troymosher thank you for taking a look at this! So much has changed within the last week and we have decided another approach is necessary (I haven't had time to update this ticket!) . I am going to tag you in a thread on Oddball Slack so you can see what we're thinking now. We can touchbase 1:1 if necessary. My plan is to document the new approach and I would value your input/feedback from a security perspective. I think you'll favor the new direction. Let me know if you have any questions/concerns.

**Comment by shiragoodman** [comment]
@jhouse-solvd @troymosher FYI - I updated this ticket to reflect my teams new tasks, ALL of which are contingent upon defining the new process for VFS teams and cleaning up the existing repos/teams. Let me know if you have any questions!

**Comment by mchelen-gov** [comment]
Proposed approach:
1. Add VFS team members to `vets.gov-write` during Platform Orientation https://github.com/department-of-veterans-affairs/va.gov-team/issues/39321
2. Create GH teams for each VFS team, nest them under `vets.gov-write` add during Platform Orientation
3. Move VFS GH teams under new parent team `vfs-all-teams` with permissions matching `vets.gov-write`
4. Refine permissions of `vfs-all-teams`

**Comment by shiragoodman** [comment]
step 2 is the new VFS team issue template.

**Comment by jhouse-solvd** [comment]
@shiragoodman & @mchelen-gov - I'm tracking this. 

Let me know what needs to be done by the Platform Infrastructure team. ☺️

**Comment by shiragoodman** [comment]
@jhouse-solvd we have completed step 1 specified[ in this comment.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35154#issuecomment-1084968306) I will be meeting 2ith @mchelen-gov today and we will discuss how to proceed.
