### ISSUE TITLE
PromoBanner web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35152]
## Description
Build a web-component version of our [PromoBanner React component](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/react-components/src/components/PromoBanner).

## Details
Styles: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/8ce0431d342a5be24170d9329e19257eb6e678db/packages/formation/sass/modules/_m-promo-banner.scss

## Acceptance Criteria
- [ ] `va-promo-banner` is written
- [ ] E2E tests are written
- [ ] Add Chromatic link to #36836, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by k80bowman** [comment]
@CourtneyChambers77 before we start development work on this, could you please review the [PromoBanner React component](https://design.va.gov/storybook/?path=/docs/components-banners-promobanner--default) and add comments to this ticket about any accessibility issues you find?

**Comment by pdavies88** [comment]
Places where it is used:
Content Build: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/components/banners.drupal.liquid
Vets-Website: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/promoBanners/index.js (This will ultimately be removed during migration)

Documentation Link: https://design.va.gov/components/promo-banners
