### ISSUE TITLE
[1/14/2022] Updating Installtion Instructions for AVS and adding to Sharepoint

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#35150]

**Comment by jwowk** [comment]
Rob updated on 1/11/22 directly on SharePoint site. Need to verify this is final version.

**Comment by aschulhof** [comment]
Rob has verified that the installation instructions are ready to go

**Comment by jwowk** [comment]
AVS SharePoint site with updated instructions published to all of VA on 1/12/22.
