### ISSUE TITLE
[Spike] Patient is not privileged to clinic error

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35167]
## Background/Request
Apprx 91% of direct schedule submission errors are due to "The patient is not privileged to the clinic being booked." 

The business explains this as:

> Some clinics are prohibited access- meaning only [privileged] users can access it and need to be added as [privileged]...for VAOS self-scheduled the viabproxy user needs to be added as a [privileged] user for Veterans to self-schedule

As Product, I would like to understand how we might be able to utilize this user access information to provide them only scheduling options available to them before a submission attempt.

### Goal
The outcome we want is that users are informed as early as feasible if they can't make an appointment in the tool, and provide an alternative path if available. We want to avoid a user making it to the end of the flow and is unable to make an appointment.

---

## Tasks
- Answer the following questions:
  - Currently, how and when do we know the patient isn't privileged to the clinic?
  - How might we query for this information before the point of direct or request flow is determined?
- Identify if frontend, backend, or backend services might need dev work if we make changes related to this

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by ldelacosta** [comment]
Spoke to @ajmagdub . This ticket was moved back to the Ready queue since the team is working on E2E testing for V2.

**Comment by ajmagdub** [comment]
Created MAPS support ticket, [MAPS-126](https://issues.mobilehealth.va.gov/browse/MAPS-126) for assistance.

Over the last month, the Appointment creation error rate was 6.8%.  

Here's a breakdown of the errors:
- 90% were from the VistA Scheduling Provider (VSP) errors
- 7% were Community Care (HSRM) errors
- 3% were misc errors (clinic data fetch errors, veteran identifier fetch errors from MVI)

Please find attached the appointment creation Datadog logs covering last month:
 [Appt-create-errors.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a210a99d074ba2619e99a13933fc24746fa44f1/Appt-create-errors.xlsx)

**Comment by ldelacosta** [comment]
@JRRoof - let me know when you get an update.

**Comment by JRRoof** [comment]
Moved this ticket to [VAOSR-8349](https://issues.mobilehealth.va.gov/browse/VAOSR-8349), as MAP sustainment board in JIRA is not monitored by any team.

**Comment by ldelacosta** [comment]
@JRRoof - I think we are good to close out the ticket.

**Comment by ldelacosta** [comment]
No additional info is needed. Closing out the ticket. cc: @JRRoof
