### ISSUE TITLE
Access for Shaunna Smith

### ISSUE THREAD

**Issue by ShaunnaS** [department-of-veterans-affairs/va.gov-team#35166]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Shaunna Smith

### Your Email

shaunna.smith@adhocteam.us

### Name of Your Team

VA-API Lighthouse, UX Researcher, Ad Hoc

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need full access to AWS for use in my research.

**Comment by jbritt1** [comment]
### For AWS Access

User: Shaunna Smith
COR: Courtney Bethea
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level access: no

**Comment by td-usds** [comment]
Reached out to VOR
@ShaunnaS can you explain what you mean by "full access"? We try to scope access as tightly as possible to what it is that you actually need. Too broad access is a security issue and access is granted on an "as needed" basis.

**Comment by ShaunnaS** [comment]
Hi,

Sorry, I was unsure what to put in the reason. I'm an Ad Hoc researcher
working on VA-API Lighthouse so I will need to be able to use AWS to create
transcripts from interview audio. Please let me know if you need more
information.

Thanks,
SS

**Comment by td-usds** [comment]
Approved for the scope as explained in https://github.com/department-of-veterans-affairs/va.gov-team/issues/35166#issuecomment-1012424524

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
