### ISSUE TITLE
Create documentation steps for every sprint

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#35180]
Product Outline
Link

High Level User Story/ies
As a _____, I need _____ so I can _____.

Hypothesis or Bet
If we make this change then we expect this to happen.

OKR
Which Objective / Key Result does this epic push forward?

Definition of done
What must be true in order for you to consider this epic complete?
Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.

**Comment by rmessina1010** [comment]
Template. Closing.
