### ISSUE TITLE
Communication with apps that are almost eligible for allowlist

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#35184]
High Level User Story/ies
As a VFS team, I need an understanding of what is preventing my app from being eligible for the allowlist.

Hypothesis or Bet
If we [release tools team] complete an audit to
a) better understand which apps are near eligible for the allowlist, and 
b) communicate with candidate apps what is preventing them from being eligible,
we will have more apps join the allowlist.

Definition of done

- [x] Audit of cross app imports
- [x] List of apps that are near eligibility (including what work they have remaining to make them eligible)
- [x] Communication to candidate (nearly eligible) teams about their status and what remains to make them eligible for allowlist: 1 ticket per app team (nested within this epic)
- [ ] Respond to any VFS requests for assistance

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSP---Release-Tools-FE-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/35184?planning-poker) with ZenHub @ndsprinkle

**Comment by ndsprinkle** [comment]
Tickets created for two teams to add six total applications to the allow-list:
- https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45095
- https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45096

These tickets have not been assigned to the teams yet.

**Comment by laineymajor** [comment]
@ndsprinkle have you been in communication with anyone from the above teams? If so, who? I'm trying to determine who I should follow-up with. Thanks!
