### ISSUE TITLE
[Call Center] Obtain Access to MS and IRIS

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#352]
## User Story
As an Analytics team member, I need access to current and available Call Center data so I can evaluate the data.

## Goal
Provide Joy and Joanne with access to Microsoft Dynamics & IRIS.

## Acceptance Criteria
- [x] Joy is given access to MS Dynamics
- [x] Joy is given access to IRIS
- [ ] Joanne is given access to MS Dynamics
- [ ] Joanne is given access to IRIS

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic**
- [ ] **Labeled with Team**
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Currently Blocked: MS Dynamics still needed

**Comment by joanneesteban** [comment]
Added @joanneesteban to access request.

**Comment by joanneesteban** [comment]
No IRIS access will be given to @joanneesteban because the platform needs a PC.

**Comment by joanneesteban** [comment]
@clantosswett would I be able to get access to Salesforce?

**Comment by clantosswett** [comment]
Probably. I'll reach out and see if we can get you and @JoyOfTech access.
