### ISSUE TITLE
Potential user stories for the Platform Console

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#35207]
- [ ] As a user, I’d like to be able to authenticate myself so that I can view my apps. (Dependent on AMT team, probably not for us)
- [ ] As a user, I’d like to be able to unauthenticate myself (logout).( Dependent on AMT team, probably not for us)
- [ ] As a user, I’d like to create and deploy a new app using a Dockerfile. (need to convert to issue)
- [ ] As a user, I’d like to see what version/commit is deployed. (need to convert to issue)
- [ ] As a user, I’d like to trigger a manual deployment. (need to convert to issue)
- [ ] As a user, I’d like to choose which branch to deploy. (need to convert to issue)
- [ ] As a user, I’d like to view the environments my app is deployed in. (need to convert to issue)
- [ ] As a user, I’d like to link my app to a GitHub repository for various reasons (e.g. view CI status).(need to convert to issue)
- [ ] As a user, I’d like to see my app’s CI status from GitHub Actions. (need to convert to issue)
- [ ] As a user, I’d like to be warned if I attempt to deploy with a red CI status. (need to convert to issue)
- [ ] As a user, I’d like to see an audit log of Console events that have occurred on my application (e.g. deploys, env var changes). (need to convert to issue)

**Comment by ericboehs** [comment]
Closing until Console project is active.
