### ISSUE TITLE
[PM/PO] Auth Profile: Bad Address Indicator Discovery - Initial research

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35216]
## Background
We want to display some type of indicator on addresses in VA.gov Profile Contact information if the address has been flagged as invalid in the VA Profile data source.  This issue is to do initial research on bad address indicator to understand product scope. We need to figure out the following:
- What is a "bad address"?
- What triggers the bad address indicator?
- What data do we get from VA Profile when we're told that someone has a bad address?
- What happens if someone is determined to have a bad address?
- Do we know how many people currently have bad addresses?
- Does the bad address indicator indicate bad data for anything other than home or mailing address (eg. phone numbers or email address)?

## Tasks
- [ ] Determine and document answers to above questions

## Acceptance Criteria
- [ ] Questions in Background section have been answered and documented

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by MarciMcGuireGCIO** [comment]
Slack thread for reference: https://dsva.slack.com/archives/C7TE0PFTL/p1642168955020100

**Comment by MarciMcGuireGCIO** [comment]
Met with Barry Wilbanks today to get more context around the Bad Address Indicator (BAI), where it is stored, how it is managed.  It currently resides in a "good data" repository, but they are currently discussing the possibility of moving it to the "bad data" repo, which would mean we would need to request good AND bad data.

**Comment by Samara-Strauss** [comment]
[Here are my notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/product/meeting-notes/call-with-barry-1.25.22.md) from today's call if we need them. @MarciMcGuireGCIO if you have other bad address indicator background info, feel free to add it to the product folder.
