### ISSUE TITLE
[01/14/2022] AVS Announcement Email

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#35220]

**Comment by lindsay-insco** [comment]
Hey @ahicksfearless I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/vetext-team-6037e6489f650a000f9f08a9/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by aschulhof** [comment]
Draft in review - https://docs.google.com/document/d/14g6x1Kwh3FEnYSXzBRz7aeddsCvuFG5gsnBb4sO1aHo/edit

**Comment by aschulhof** [comment]
Sent to Dr. Layden for Review.

**Comment by aschulhof** [comment]
Dr Layden wants to slow roll sending this out, still need list of emails

**Comment by jwowk** [comment]
Emails sent in FY2022
