### ISSUE TITLE
[Spike] Redirecting to SLP

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35231]
## Background
A recent fix by the Identity team ensures all "sign-in from" urls are being respected. 

See [Slack](https://dsva.slack.com/archives/CMNQT72LX/p1638905945158800?thread_ts=1638904832.155400&cid=CMNQT72LX) conversation with Identity team for more info.

### Goal
There is informational content on the static landing page (unauthenticated) appointments page before the authenticated VAOS tool. We would like users who attempt to enter VAOS to be redirected to landing pages so that users receive required information before using the tool. Example: the auth widget has additional logic included for Cerner users that includes a CTA to the My VA Health portal.

### Requirements to Consider
- Scheduling and appointments for Cerner sites are managed in the My VA Health portal
- Veterans registered at Cerner sites and eligible for Community Care can use VAOS to request Community Care appointments

### Scenarios to Consider
*Scenario 1**
Given user is not logged in
When user directly enters the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`)
And successfully authenticates
Then redirect user to the static landing page (`/health-care/schedule-view-va-appointments/`)

**Scenario 2**
Given user is logged in
When user directly enters the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`)
Then redirect user to the static landing page (`/health-care/schedule-view-va-appointments/`)

**Scenario 3**
Given user is logged in
When user navigates to the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`) from another VA.gov page
Then load the VAOS homepage

---

## Tasks
- Determine how we might implement the homepage to static landing page redirect

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket
- Indicate if more time is needed for discovery

**Comment by vbahinwillit** [comment]
It was suggested that to meet these requirements, the platform reverse proxy would need to be configured to do the redirects. The following ticket #36132 has been created with the devOps team requesting access to modify the necessary files or someone to make the necessary changes for the VAOS team.

**Comment by ldelacosta** [comment]
@vbahinwillit - let us know when #36132 has been completed. @JRRoof will create a new ticket for the upcoming work. Thanks!

**Comment by ldelacosta** [comment]
Closing out the spike.
