### ISSUE TITLE
526 - Combat Question Addition

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35235]
## Issue Description
Add new question to the front end (fear of terrorist activity)

---
## Tasks
- [ ] Work with Design to add new question to Frontend

## Acceptance Criteria
- [ ] Page added to flow
---

**Comment by Mottie** [comment]
Oops, I opened a new ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/35437 - closing this one as a duplicate
