### ISSUE TITLE
Update What's new section w/content style guide additions & send GovDelivery email out to VA users

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3523]
@RLHecht - When the Naming and Error messages pages go live, please also:

[ ] Update the What's new page in the design system.
[ ] Email update message to VA users.

You should be able to find an example of how the content items were added here on this page: https://design.va.gov/documentation/whats-new.html

And I can show you how to send an email out to VA users via GovDelivery. 

FYSA @Karak888 - keeping this in icebox for now until Randi is ready to work on it. Please be sure to work with her on sizing.

**Comment by Karak888** [comment]
will do!

**Comment by RLHecht** [comment]
The what's new section has been updated. Once @jenniferlee-dsva reviews and merges PR I will send out the govdelivery email.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - can you send me the link to the PR? I have not seen it.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I looked at the updated MD file and found the PR and merged it.

**Comment by RLHecht** [comment]
All work completed. Closing ticket. FYI @Karak888
