### ISSUE TITLE
Front-end does not correctly handle cancelling cc appointments (VAOS service) 

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#35233]
Currently when logging in with Jacqueline Morgan and attempting to cancel a CC appointment the application sends a PUT request to vets-api and the appointment is successfully cancelled as far as our upstream services are concerned.  However, the  resulting appointment object is not configured correctly and our FE application can't distinguish it as a cancelled appointment but instead displays it as not cancelled in the UI.  

Details:
When the appointment is cancelled the comments fields is over-written with CANCELLED_BY_PATIENT.  We need to determine what field the front-end is currently (with Judy Morrison) keying off of to identify a cancelled appointment.

Update:
When going through the same flow with Judy Morrison it looks like we key off the status: "Cancelled" field returned in the appointment object.

**Comment by ajmagdub** [comment]
Per backend group the status for a CC appointment does not change to canceled immediately when canceled by a patient, the status field changes to canceled when the clinic's staff cancels an appointment.

The cancellable field is updated to false once a patient submits a cancel request. The Web front end is updated to reflect the fact that only the cancellable field reflects the patients wish to cancel the appointment.
