### ISSUE TITLE
Access for Ian Harrison

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#35239]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ian Harrison

### Your Email

ian.harrison@adhocteam.us

### Name of Your Team

Release Tools - Software Engineer - Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Vo/QYTgrC++qla9oShgdQ2IWMXY6u5CES6v4CNmo9YC5IDZiMKod3Sok/evcqYpzGuWlDrvP4zdigZyXb35XxJ25Bvp6DqNQ59N3tLP5Ncz64muKQfr9lYqvXxFMJ/ocLKc76rH9xJgPiv6RgmdcqaDj1HCjVRZydVBBtxVPvkJ8BKpBrm6yEpjv2y0BDEain+9oo1SP2QzLQLrTt/Ksv9aAlFWsVROwt9S+byjrd60ZaEuUBkMJsTJIW/OSmfuMX9DS7xjO7cXDM2OwMfd3+eA86Z045mEasyxxHSYYzzAOtCU+6A2hAds13J563Ozooo7Bz97z+IPeGj7p8RK2l9ahMZXctz4QfBYWS663QH9AgsFyE3/A8bIcp79JPqSEcPt3GJSLLyLyOjDktAWfrIPec+r6f4ebLmRwXu3lmR3XxyTl6m6DlTq0TTulm87zUmIaCUE66cz7If7t23eWvrRYTgT3RQOhFeV9F5xF0QUfNMMnrbPtz9MkTwwYpo8= ianharrison@IanHarrisonMBP

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
