### ISSUE TITLE
[BE] Enable reliable logging in vets-api/check_in module 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#35259]
## Description
Needing to Enable reliable logging in vets-api/check_in module with out focus on increased monitoring and logging. 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by sarahknoppA6** [comment]
PM has approved
