### ISSUE TITLE
Create Accounts in station 500 for CHIP team 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#35261]

**Comment by aschulhof** [comment]
Create accounts in VistA for CHIP team, based on Vista recording from 1/10. 

Recording LInk: https://dvagov-my.sharepoint.com/:v:/r/personal/allison_schulhof_va_gov1/Documents/Recordings/Walk-through%20Vista%20_%20Postgres-20220110_130344-Meeting%20Recording.mp4?csf=1&web=1&e=NMUpfj

Shane said to let him know if you need another walk-thru

Start with creating your own accounts, then check with @aschulhof . If they haven't already created their own accounts, I'll have you add: 

Charley Stran
Alex de los Reyes
Michael Kimball
Mike Olasin
Chris Wilmsen

**Comment by aschulhof** [comment]
https://login.microsoftonline.com/e95f1b23-abaf-45ee-821d-b7ab251ab3bf/oauth2/authorize?client_id=00000003-0000-0ff1-ce00-000000000000&response_mode=form_post&protectedtoken=true&response_type=code%20id_token&resource=00000003-0000-0ff1-ce00-000000000000&scope=openid&nonce=7DC579877FEC88F785DB2D4FF3CF1EA338BD6C8476782A38-178C95794492583F09712BB442E5C6800019C3DE675E35A4964C0E517D21572C&redirect_uri=https%3A%2F%2Fdvagov-my.sharepoint.com%2F_forms%2Fdefault.aspx&state=OD0w&claims=%7B%22id_token%22%3A%7B%22xms_cc%22%3A%7B%22values%22%3A%5B%22CP1%22%5D%7D%7D%7D&wsucxt=1&cobrandid=11bd8083-87e0-41b5-bb78-0bc43c8a8e8a&client-request-id=962616a0-505b-c000-a55f-18ba2dd095dd

**Comment by aschulhof** [comment]
Set up time with Shane to go through DUZ. Lindsay setting up time!

**Comment by chancetheoriginal** [comment]
Accounts created and emailed to users.
