### ISSUE TITLE
(HOLD) Reroute Walla Walla registered users (Cerner)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35269]
## Description
As a Walla Walla VA registered Veteran, I want to be able to manage and schedule/request my appointments in the My VA Health portal instead of VAOS.

**Anticipated launch 3/26/22**

Similar tickets from previous Cerner site launch #6639, #6964

## Business Requirements

- Scheduling and appointments for Cerner sites are managed in the My VA Health portal
- Veterans registered at a Cerner site and eligible for Community Care can use VAOS to request Community Care appointments
- Veterans who are only registered at a Cerner site cannot schedule or manage their appointments in VAOS
- Veterans who are registered at both a Cerner site and a VistA site can schedule or manage VA appointments for their VistA sites, but not for the Cerner site
- Veterans who are registered at a Cerner site and are eligible for Community Care can schedule and manage their Community Care appointments in VAOS

---

## Acceptance Criteria
Background: the `toggle` toggle is on

**AC1**
Given user is registered at Walla Walla
When user navigates to any appointment list
Then user cannot see or manage Cerner appointments in VAOS

**AC2**
Given user is registered at Walla Walla and eligible for Community Care
When user clicks Start Scheduling
Then user can attempt to request an appointment through the Community Care flow

**AC3**
Given user is registered at Walla Walla and a VistA site
When user clicks Start Scheduling
Then user can attempt to schedule a VA appointment through the VA flows

**AC4**
Given user is registered at Walla Walla and a VistA site
When user selects any Cerner facility on the Facility Selection page
Then direct to My VA Health portal

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
This ticket is no longer needed. Closing the ticket. cc: @JRRoof
