### ISSUE TITLE
Reach out to USWDS team and establish connection

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35289]
## Description
Katy and Carol can work on this together.

We would like to establish a connection with the team working on USWDS. We have heard they are working on web components and that seems like something we may want to discuss with them.

## Acceptance criteria
- [ ] Determine who we need to connect with on the USWDS team
- [ ] Conduct an initial meeting to establish connection

**Comment by caw310** [comment]
Had initial call on 1/19. Have a follow up call on 2/7.
