### ISSUE TITLE
Linking to the Medical Copay Tool on the Debt Portal's Content page from the Debt Resolution Team

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35286]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [X] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
We've launched the Medical Copay Tool and noticed that [the 'Manage your VA debt' content page](https://www.va.gov/manage-va-debt/) directs Veterans to call the Health Resource Center if they have health care and prescription charges. We'd like to incorporate a button that links to [the Medical Copay Tool](https://www.va.gov/health-care/pay-copay-bill/) in case Veterans navigate to the debt portal instead of the medical copay tool. 

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: 
- Estimated staging review date:
- Content and IA work needed by: ASAP

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: The Debt Resolution team 
-	OCTO-DE product owner: @mattpointzxer0 
-	Product manager: @denisecoveyduc 
-	Designer: @rileyorr 
-	FE engineer: @craigwheeler 
-	Product/team Slack channel: #vsa-debt

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
Danielle added this to the page and it's now published. Will close once validated on live site.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
