### ISSUE TITLE
Deal with AWS_PROFILE in a more consistent manner

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#3529]
## User Story or Problem Statement
Given the hack we needed to make in department-of-veterans-affairs/devops#5927 what can we do to better support AWS_PROFILES in out configs so we don't have to make these sorts of changes

## Goal
Consistent documented AWS creds access.

## Acceptance Criteria
- [ ] consistent AWS_PROFILE handling thought up and applied
- [ ] come up with a plan(Plan which will be broken into other tickets)
- [ ] docs on what / how 
- [ ] present to the group

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Given that we plan to put BRD into maintenance mode and re-tool here, I'm going to close this one as something we won't fix.
