### ISSUE TITLE
[Feature Request [Test]: 108

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#35307]
### Describe the problem

Test

### Who will benefit

Test

### Describe your idea

Test

### Provide evidence

Test

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [ ] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [X] Other

**Comment by rroueche** [comment]
@jonathanjnelson we're working on this this sprint! would you be available to participate in some rapid paper prototyping as a part of our discovery?
