### ISSUE TITLE
Add Time Zones to Facility Hours

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#3530]
## User Story or Problem Statement
As a veteran, I need to know the time zone of a facility so I can understand the open/close time of a facility within the context of the time zone.

## Goal
Comply with the style guide and show Facility times as
8:00 a.m. - 9:00 p.m. ET
REF: https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones

## Objectives or Key Results this is meant to further
- Veteran Experience

## Acceptance Criteria
- [ ] Find method to determine time zone relative to each facility (ET, CT, MT, PT) being wary of the 'gotchas' like AZ
- [ ] Format date/time to comply with style guide including time zone

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Need to create discovery issue to look for existing methods of handling

**Comment by mmiddaugh** [comment]
This will be addressed by the Lighthouse team and can be integrated into Facility Locator when we transition from vets-api to facilities-api. 
Closing this issue
