### ISSUE TITLE
[FE] Update Content for Appointment Card if too late to Check-in 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35306]
## User Story
As a Veteran, I want to messaging around time thresholds for my appointment so that I know why I can't check-in for certain appointments if too late. 

## Description 
Currently the content presented to a Veteran when trying to check in late for an appointment (i.e. past the set time parameter) shows specific to a 10 minute threshold. The configuration on the BE is set to 5 minutes across the board, so we need to update the static content to say 5 minutes instead of 10. 

Link to [Slack](https://dsva.slack.com/archives/C02G6AB3ZRS/p1639687064370400) thread. 

![image.png](https://images.zenhubusercontent.com/60ae5b64364d5b0b5078b4d5/eae32a6f-de3b-4423-986e-b6769c068ee8)

## Tasks
- [x] Update UI static content to say 5 minutes 

## Acceptance Criteria 
- [ ] UI static content updated to show 5 minutes.

**Comment by sarahknoppA6** [comment]
@niradatta1 and @zach-park to review in stg later this week.

**Comment by zach-park** [comment]
@mdewey In staging, it still says 15 minutes. @niradatta1 @brianseek

**Comment by sarahknoppA6** [comment]
@acrollet confirmed 15 mins is correct, so we are closing this one.
