### ISSUE TITLE
Discovery: research possibility of using React components directly inside Liquid templates

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35310]
## Description
As part of our discussions in creating the Discovery Initiative (#34951), it was mentioned that it might be possible to find a way to use React components directly inside Liquid templates. Though we are moving forward with web components, which we know are easy to use inside Liquid templates, we should take a little time and explore this option as well.

This research should be timeboxed to 1 day max.

## Acceptance Criteria
- [ ] Research options for using React components directly inside Liquid templates
- [ ] Write up results of research and add them as a comment to this ticket. Tag Katy and Carol.

**Comment by pdavies88** [comment]
Overall there is very little documentation on doing this. The one resource I found on how to do it is here: https://www.cadence-labs.com/2019/12/how-to-add-react-to-a-shopify-theme/
Github Repo: https://github.com/pmourer/react-shopify-example/tree/post-2-data-attrib

Also there is no place where I could demo and put this code online as to show as the example requires a Shopify store, but in theory this is how putting React in Liquid would be accomplished.

**Comment by pdavies88** [comment]
Following the files it would be:
1. https://github.com/pmourer/react-shopify-example/blob/post-2-data-attrib/scripts/Components/CartToolTip.js - React Main Component
2. https://github.com/pmourer/react-shopify-example/blob/post-2-data-attrib/scripts/Components/CartSummary.js - React Child Component
3. https://github.com/pmourer/react-shopify-example/blob/post-2-data-attrib/snippets/react-cart-tool-tip.liquid - New React Component Specific Liquid Template for binding
4. https://github.com/pmourer/react-shopify-example/blob/post-2-data-attrib/scripts/cart-tool-tip.js - React related script to bind with the Liquid template in step 3
5. https://github.com/pmourer/react-shopify-example/blob/post-2-data-attrib/sections/header.liquid - Final location where the new React Component via the Custom Liquid Template will be utilized
6. https://github.com/pmourer/react-shopify-example/blob/post-2-data-attrib/webpack.common.js - Make the React Component known and accessible in our build via Webpack

**Comment by k80bowman** [comment]
This is great, Preston, thank you! Is there any way we could try this out and confirm it works with one of our existing React components inside the Liquid templates in the content-build repo?

**Comment by pdavies88** [comment]
This process is already in use to get all of the Static Page Widgets loaded into Vets-Website ie:
https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/static-pages
