### ISSUE TITLE
Remove show redesign links on GIDS dashboard

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#35329]
GIDS dashboard currently has show redesign links. Given we are now live with the redesign, we would want to remove these links. Screenshot attached.![Screen Shot 2022-01-13 at 12.28.12 PM.png](https://images.zenhubusercontent.com/60e8347034d7f9aecbba74bb/c8bd4eb1-b2f0-4ca9-8456-4523c07692ec)

Note: This is frontend and backend. Backend references an env variable, which we should confirm with platform is removed from the deployed environment variables if it is set in ansible

**Comment by hallihocine** [comment]
Ticket has been validated in staging: the "Show redesign" links removed from the GIDS dashboard.
<img width="1606" alt="Screen Shot 2022-02-01 at 1 19 59 PM" src="https://user-images.githubusercontent.com/86266024/152029145-7db9a018-7250-4f76-a5d9-b4e0c3c6e34e.png">

**Comment by hallihocine** [comment]
- Test Run in TestRail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2883&group_by=cases:section_id&group_order=asc&group_id=3598
- Test cases: 
[Remove show redesign links on GIDS dashboard .xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7981073/Remove.show.redesign.links.on.GIDS.dashboard.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT Passed on 2/3/2022.
