### ISSUE TITLE
[FE] Dynamic Value for appointment time parameter when outside of check-in window. 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35322]
## Description
Need to make the numeric value in the appointment card dynamic if we make check-in window configurable per clinic. 

[Slack](https://dsva.slack.com/archives/C02G6AB3ZRS/p1639687064370400)

![image.png](https://images.zenhubusercontent.com/60ae5b64364d5b0b5078b4d5/053b5932-d02d-4d2c-b71d-e65bfb02f32e)

**Comment by julieadair1** [comment]
@jparker0425  - let's discuss whether this should be prioritized soon.  Per FE team it is a relatively small lift.

**Comment by jparker0425** [comment]
@julieadair1 I think if we end up doing time param configuration per clinic this is something we need to do. I do not know that right now we would need to prioritize based on the discussions taking place around if that config will be allowed at the clinic level. I _think_ OVAC was planning to send a survey around this. 

My assumption is we will end up needing this, it may just be a little further down the road.

**Comment by julieadair1** [comment]
@jparker0425 , @stephenBarrs - I'll move this to the icebox for now.
