### ISSUE TITLE
Access for Sebastian Caso

### ISSUE THREAD

**Issue by s-caso** [department-of-veterans-affairs/va.gov-team#35330]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

sebastian caso

### Your Email

sebastian.caso@accenturefederal.com

### Name of Your Team

My Education Benefits, Rails developer, Seneca Resources

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8fEsv/LVkiXDtUQIJlIPkK1C24DqhG/Ftq6Z9Ru/rjT4DJ83fr7tm3g9demuAy7x5hEwtV2/X6le7h9PaKeVoeZQETQxayQHSB3/JDHERUV0zQhSD94wHaC/2OYGmax7b7IsUEi6dNIgs+0EiFzSAZkFjHWlp1zukwp9xWhp4evOVEVXajlG3BpigGL7aglrj98sgfps98067Dqj0jg2pGUOYywqRZEeejcTjSENF0RImnyXnRCPyPTjm4uj9KXSFzfUQLYnOSaZDlGXy9Aj2i6o3EHcBiPBGlKCK5RbN0LQaCI6JkzWLg51a18evoLs9+QaMMyu1E7NS+9V1tZQ+W7U6LXuAvjl0vib/hpGrEzLn/TmFGz/PyWM0mKWAS80Qgs4mRrQkehgNrE1n2GSvJW43aCNbp1xRZc7QFEotY7GPkRk5+dI+qWs8E0JxfgSFBu5V9N76b/ZiQsJyzHshHc8iPXeUVuzvjTZnY6OTNPlEPGndZbpX4ccAK5GFwjE= sebastian.caso@AFSMWASRSZ686G1

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
