### ISSUE TITLE
Update Address Suggestions Endpoint to return overridable addresses only

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#3533]
Right now the address suggestions endpoint returns an address even if it includes errors of type `FATAL` from vet360. These aren't overridable, so we should strip the validation key from any response to indicate this.

**Comment by Justin-Pickett** [comment]
@hinzed1127 can this ticket be closed?

**Comment by Justin-Pickett** [comment]
Closing this ticket. If we see this during QA we'll open a new ticket for this .
