### ISSUE TITLE
Discovery: Try out using our web components in a simple Angular app

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35334]
## Description
Our theory is that it should be relatively easy to use our web components inside any framework, but we want to experiment and find out for sure.

If possible, please run this experiment in an online coding environment like Codepen or Repl where you can share a link to your work. (It doesn't matter what you use, just something where it would be easy for someone else to view and run the code without installing a bunch of stuff locally)

For this ticket, you'll need to:
- build a quick "hello world" Angular app (use the latest version of Angular)
- import a couple of our web components and display it in the app
    - maybe start with a simple one, then try one that takes a function as a prop
- write up the process, noting any special things you had to do to make it work.

## Acceptance Criteria
- [ ] Build a simple Angular app in an online coding environment
- [ ] Import one of our simpler web components and use it in the app
- [ ] Import a web component that will take a function as a prop and use it in the app
- [ ] Record your process in a comment on this ticket. Include a link to your experiment.

**Comment by pdavies88** [comment]
Web Components will need to be imported within the `.html` file of the Angular Component and Event Binding is done via the following syntax: https://angular.io/guide/event-binding
