### ISSUE TITLE
[1/19/2022] AVS Batch Printing User Guide

### ISSUE THREAD

**Issue by vlivshin** [department-of-veterans-affairs/va.gov-team#35358]
- [x] Write up steps to print
- [ ] Add section to Sharepoint userguide

**Comment by vlivshin** [comment]
Ready for review: https://docs.google.com/document/d/130tr1zw0TetIMDgSeX662D9E8Ll8VG8vxXimD_ldQoc/edit

**Comment by lindsay-insco** [comment]
Rob approved and published
