### ISSUE TITLE
[FE] Routing Corrections needed within Check-in Workflow - "back to last screen" 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35368]
Scenario 1:  Currently on demographics page.  Select YES (info is correct).  Select "back to last screen" in top-left.  Taken back to demographics page.  Select NO (info is incorrect).  Taken to page telling me to see staff.  Select "back to last screen" in top-left.  Taken back to demographics page.  Select YES.  Immediately taken to authentication page with last name/ssn requested. If I hit refresh, it will take me back into the workflow.

Scenario 2:  Currently on demographics page.  Select NO (info is incorrect).  Told to see staff.  Select "back to last screen" in top-left.  Taken back to demographics page.  Select YES (info is correct).  Immediately taken to authentication page with last name/ssn requested. If I hit refresh, it will take me back into the workflow.

Slack [thread](https://dsva.slack.com/archives/C022AC2STBM/p1642103788174900) that contains the details found by Shawn Adams. 

## Tasks
- Determine if this is still happening and create a new bug ticket if it is

## Acceptance Criteria

**Comment by brdunfield** [comment]
From what I can see locally and on staging, this doesn't appear to still be an issue.

When I follow the scenerios:
> Currently on demographics page. Select YES (info is correct). Select "back to last screen" in top-left. Taken back to demographics page. Select NO (info is incorrect). Taken to page telling me to see staff. Select "back to last screen" in top-left. Taken back to demographics page. Select YES.

Selecting YES brings me to the next page as expected and does not kick me out to the authentication page. Same story for scenario 2.

@loripusey I'm going to close this ticket given the above, if it needs to be re-opened for something I didn't understand let me know and I'll take another look.

**Comment by loripusey** [comment]
Thanks @brdunfield !
