### ISSUE TITLE
[S3] Create bucket for VSA eBenefits team 

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#35367]
## Description
VSA eBenefits team is requesting a new S3 bucket be created for a new feature being built on VA.gov.

## Background/context 
VSA eBenefits team is building a new integration between Vets-API and LGY (Loan Guaranty).  One of the features allows the Veteran to download their COE (Certificate of Eligibility) which is a PDF file that is provided by LGY.  We need to save the file to an S3 bucket and provide the URL to our FE to present to the user.

---
## Tasks
- [ ] Create resources
- [ ] Assign permissions

## Acceptance Criteria 
- [ ] The team can access the resources requested

**Comment by jason-gcio** [comment]
Hey Jeremy! (@jbritt1) - I assigned you **just for awareness**... please let me know if it should be someone else?
Thanks again for your help on this.

**Comment by jbritt1** [comment]
Reassigned to Ops leadership for grooming/prioritization

**Comment by jhouse-solvd** [comment]
@mchelen-gov - Can you take a look at this and let us know if you have any questions? I'm not clear on the platform's guidance for offering upload and storage functionality for integrations like this. The request may be relatively straightforward from a technical standpoint, but we want to be sure that the platform is prepared to support it. ☺️

**Comment by jhouse-solvd** [comment]
@kathleencrawford @jason-gcio - Checking in w/ our product owner and will follow up with details in the near future. 

In the meantime, can you share any parent initiative or background that provides info on timeline, urgency, etc? 

Thank you for submitting, and please contact me if you need any follow-up.

**Comment by jhouse-solvd** [comment]
@kathleencrawford or @jason-gcio - Is this still needed?

**Comment by jason-gcio** [comment]
Hi @jhouse-solvd - my apologies, I totally missed these messages, I think GH sent these to my junk folder on my VA email for some reason.  Yes, we do still need this as we are sharing documents from the LGY line of business to the Veteran.  Thanks for pinging us again on this.

**Comment by jhouse-solvd** [comment]
@jason-gcio - No worries. 

We can get this scheduled for an upcoming sprint. 

Do you have any timeline for this need?

**Comment by jason-gcio** [comment]
Awesome, thanks @jhouse-solvd 
Probably end of April, but we (we meaning, you really haha) might need to talk to whoever is picking up after this team.  I am not sure of the ramifications of an S3 bucket sitting in all our environments without being used for 4-6 weeks.  

Context: We had a totally different perspective when we originally made this request - sorry for being wishy-washy, I just don't know the effort or impact of this as well as I would like.

**Comment by jhouse-solvd** [comment]
@jason-gcio - I would say it could be good to pick this up w/ the team that will be implementing the S3 bucket. Part of the implementation will include permissions, etc. So, it might make sense to work on that with the new team. 

Does that make sense to you? 

If so, I might even prefer to close this request, and re-scope with that team once arrived.

**Comment by jhouse-solvd** [comment]
Closing. The next team can make a request based on their requirements and scope.
