### ISSUE TITLE
Submit Feedback Tool 2.0 - Medallia Exploration

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#35364]
## Issue Description
_Meeting to discuss Medallia's capabilities_

---
## Tasks
- [ ] _Add meeting notes as comments_

## Acceptance Criteria
- [ ] _Meeting notes and decisions are recorded_

**Comment by nicole-leonard** [comment]
Meeting scheduled with Jason Woodman for 1/14/2022 to discuss using Medallia vs. good/bad rating component to streamline Veteran experience for user feedback.

**Comment by nicole-leonard** [comment]
@mgleo and I met with Jason Woodman on utilizing Medallia and Medallia has evolved to offer the functionality we need to replace Good/Bad Component. Nicole is scheduling time with @davidconlon to discuss.

**Comment by mgleo** [comment]
Notes from 1/14/21 Meeting with Jason Woodman:
- Medallia Feedback Survey Tool is changing from a blue button appearing on the right hand side of a page to appearing above the footer. It will appear similar to the blue "Is this page useful?" section near the footer on [gov.uk](https://www.gov.uk/).
- Demo will be shown at the next ToT
- Will appear on VA.gov next month for testing
- Medallia's Feedback Survey Tool that we are interested in utilizing will allow users to rate multiple article pages on R&S.
- Medallia's Intercept Tool allows users to submit feedback only once and will not reappear until 90 days later. We will not be utilizing this tool.

**Comment by mgleo** [comment]
Hi @jwoodman5, 
Thank you for meeting with us last week and for sharing the new mockups for the feedback button. Here are some follow up questions regarding the update to the Medallia Feedback Survey Tool:

- What will users see after they click the blue feedback button near the footer? Currently a modal appears when a user clicks the blue button on the right side of the page, is anything changing after a user clicks the blue button?

<br>

- Can you share more details on the release/testing plan? And can R&S article pages be a part of testing?

<br>

- Is this userflow possible with Medallia? If a user rates the page poorly a list of issues (such as "Typo") with checkboxes will appear to allow users to report problems with the page. 
![userflow-submit-feedback-tool.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/6c7bf1d1-1a4a-43c2-8821-1f7d0cff49d2)

**Comment by jwoodman5** [comment]
Hi @mgleo - Here are my answers in bullet order:

- A modal with the three standard Feedback survey questions we currently serve; nothing in that regard is changing _right now_.
- Yes, we do plan to test functionality on staging for each template and also run general 508 accessibility tests. I don't see a reason why R&S pages couldn't be included in this, but I will confirm.
- I do believe this is possible, though will likely require a fair amount of customization (i.e. engineering) on our side. This type of scenario would also likely need to go through our experimental design process. Either way, it will be a bit before we can support this, but we plan to start pursuing it towards the end of Q1.

**Comment by jwoodman5** [comment]
Hi @mgleo - If the questions are already PRA approved (VA requirement), I would think about 3 weeks, though I can't commit to this because it would require work from an outside team. That being said, I don't see these questions on the PRA approved list. I attached that here for reference. Please let me know if I missed them or if there are others you'd like to use. Otherwise, we need to explore the process of getting your questions PRA approved. Hope that helps. 

[Medallia Survey PRA Approved Questions.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7930166/Medallia.Survey.PRA.Approved.Questions.xlsx)

**Comment by nicole-leonard** [comment]
Complete and ready for next steps/tickets
