### ISSUE TITLE
[COGNITION]: GIBCT Section 116 - Add screen reader only text for the benefit breakdowns by time

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3537]
## Description

The VET TEC benefits that VA pays upon enrollment, upon completion, and upon employment could include some screen reader only text for assistive technology users. As I was listening to the read outs this morning, it wasn't clear to me what the 25%, 25%, and 50% were referring to. I had to go back and figure out the VA pays out amount above was the entire amount, and these were the breakouts. Screen shot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I want to hear a more descriptive label read aloud. This could be:
  * Upon enrollment in program, VA pays to provider (25%):
  * Upon completion of program, VA pays to provider (25%):
  * Upon employment, VA pays to provider (50%):
* This text should not adjust or modify the visual display

## Screenshots or Trace Logs

![Screen Shot 2019-11-18 at 11.51.49 AM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/62f62b4c-be05-4f9e-8580-ceb2d9e44e28)

**Comment by ksantiagomorgan6** [comment]
pull request https://github.com/department-of-veterans-affairs/vets-website/pull/11138

**Comment by delli-gatti-michael** [comment]
@1Copenut This is now in staging

**Comment by 1Copenut** [comment]
@delli-gatti-michael I verified in Staging with VO. Moving to close.
