### ISSUE TITLE
[1/28/2022] Create AVS Overview Training Content

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#35376]
- [ ] Develop New User Training Content

**Comment by aschulhof** [comment]
Allison to send @djfredvs  PPT template

**Comment by djfredvs** [comment]
Overview and Introduction training completed waiting for review.[https://app.zenhub.com/files/133843125/98823bc7-6a2d-43a4-8cec-a087cdaf913b/download](https://app.zenhub.com/files/133843125/98823bc7-6a2d-43a4-8cec-a087cdaf913b/download)

**Comment by djfredvs** [comment]
Updated file and screenshot[https://app.zenhub.com/files/133843125/e307a0eb-bec1-44d1-8bfe-76d09fedc2e9/download](https://app.zenhub.com/files/133843125/e307a0eb-bec1-44d1-8bfe-76d09fedc2e9/download)

**Comment by djfredvs** [comment]
Updated Overview training deck. Removed original slide two[https://app.zenhub.com/files/133843125/9c524cc6-28da-448b-a303-4c48dab7c54b/download](https://app.zenhub.com/files/133843125/9c524cc6-28da-448b-a303-4c48dab7c54b/download)

**Comment by djfredvs** [comment]
Overview Training deck updated and posted.

**Comment by djfredvs** [comment]
Edited and updated Overview video file

**Comment by lindsay-insco** [comment]
Posted to Sharepoint - Approved by @lindsay-insco @jwowk @aschulhof
