### ISSUE TITLE
[FE] Claim Status Tool React App Build (Sitewide Team)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35382]
## Issue Description
_The mobile app team has asked us to put an alert on the [Download VA benefit letters](https://staging.va.gov/records/download-va-letters/) page similar to an alert they recently added to the Claim Status Tool. This will need to be a react widget since the text will change depending on what system a user is on. Sitewide Content team is working on the content and PW team will need to create the widget for sitewide content team to add to the page._ 

- [Link to Sitewide Teams Intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33200)

## Frontend tasks

- [x] When approved content is provided build react app based on above linked ticket requirements 
- [x] Collaborate with content team and claims team on implementation steps 
- [x] Ensure AC is meet and close ticket 

## Acceptance Criteria
- [x] react app is in place in support of the Claims Status tool as desired 
- [x] Claims team validates react app component is working as desired

**Comment by RLHecht** [comment]
@brianalloyd We now have approved content for this react widget. It's in ticket #35360 but placing it here as well. Please let me know if you need anything else! @SgardnerPMP FYSA

H2: Download your VA letters on your mobile device
You can use our new mobile app to download your VA letters on your mobile device. To get started, download the **VA: Health and Benefits** mobile app.

[Get the VA: Health and Benefits app from the Apple app store](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596)
[Get the VA: Health and Benefits app from the Google Play store](https://play.google.com/store/apps/details?id=gov.va.mobileapp)

**Comment by brianalloyd** [comment]
@longmd can you scrub into this issue.

**Comment by longmd** [comment]
This is in production. Widget code for content is `<div data-widget-type="letters-mobile-cta"></div>`

**Comment by RLHecht** [comment]
Thanks @longmd I put it into Drupal but it doesn't seem to be rendering correctly. It should be showing under the H2 "Get your VA letters online" but nothing is showing in preview for me. Not sure if it's a Drupal issue or something with the widget. 
<img width="858" alt="Screen Shot 2022-02-24 at 5 54 17 PM" src="https://user-images.githubusercontent.com/48728214/155621165-fe250a72-d96b-409c-b532-ba27d1d1c277.png">

Happy to screen share if that's helpful.

**Comment by longmd** [comment]
@RLHecht , I'm having a look through some of Kelsons old tutorial videos this morning and seeing if there is a step I missed in this. So far I'm not seeing anything... but I'll mention that this widget was directly designed off of the Medical Copays CTA widget. MAYBE if you can reference how that was implemented into Drupal, that could help us resolve this one.

**Comment by brianalloyd** [comment]
@RLHecht @longmd is out on PTO today, should be able to follow up on this tomorrow in support.

**Comment by longmd** [comment]
@RLHecht / @brianalloyd , good news on this one... finally found the missing piece to the rendering for this one. Waiting on PR to go through and we should be good. I expect this will go to Staging here by EOD and will be ready for tomorrow's PROD deployment.

**Comment by RLHecht** [comment]
Thanks @longmd I can check back in tomorrow to see if it all looks good on your end and see what happens when we put it in Drupal.
