### ISSUE TITLE
From CSS Audit: Address Recommendations for Deletions

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#35384]
Audit doc located here: https://docs.google.com/document/d/1WfMzLFpIZwe35hrmhXl2-ii2DjWaik352vHWfp3RJ7Q/edit?usp=sharing

## Definition of Done

- [ ] All "Solutions" relating to CSS classes that can be deleted in the audit doc are addressed
- [ ] A ticket to handle the corresponding class(es) is created for the appropriate team OR
- [ ] A PR addressing the situation is created
- [ ] The audit doc is updated to show that the class(es) has been addressed

**Comment by jhonnyoddball** [comment]
All necessary changes were made
