### ISSUE TITLE
[FE] My VA - Payment Info: Update logic for direct deposit link

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35387]
## Background
 To avoid confusing our users, we want to update the logic for the Direct Deposit link.  This link should only appear in the Benefit payments and debts section if the user has Direct Deposit information set up within the profile.
If the user does not have Direct Deposit set up, we should not show this link.

## Tasks
- [ ] Update the logic for the Direct Deposit link to appear only when the user has Direct Deposit set up in their profile

## Acceptance Criteria
- The Direct Deposit link will appear for Direct Deposit users only.

**Comment by tmitchellgcio** [comment]
I will need to check if the API is working for this. This had a check before and I was told to remove it since the API was failing and it wasn't anything we could control. I will need to research this one

**Comment by hdjustice** [comment]
@tmitchellgcio You are right, i totally forgot about that!  Let me propose that we just show the link all the time, and then we can do some research on whether the conditional display is feasible.  I will let you know ASAP.

**Comment by Samara-Strauss** [comment]
Please show the direct deposit link no matter what if people have this section available to them. For people who receive direct deposit for comp & pen, they can set up direct deposit if they currently receive paper checks. Unfortunately, people who receive edu payments can not set up direct deposit if they don't already have it, but I still think showing the direct deposit link conditionally is a bad idea. If people are receiving payments from the VA, it's most likely that they already have direct deposit set up.

**Comment by hdjustice** [comment]
@Samara-Strauss Thank you!  In that case, we will not require any logic to show the link conditionally and I will close this ticket.
