### ISSUE TITLE
Research: Enforce 90% test coverage for changed files in vets-api PRs

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#35398]
# Description

Research the possibility of creating enforcement around BE unit tests.

## Acceptance Criteria

- [ ] Write up a proposed solution in a ZenHub ticket for enforcing changed file code coverage with SimpleCov

**Comment by pjhill** [comment]
* SimpleCov doesn't evaluate just changed files
* The interwebz says this has been done in the past. It will require some customization.

**Comment by pjhill** [comment]
Potential path to enforcement of changed file code coverage --

* Use git to group changed files and evaluate

**Comment by ddzz** [comment]
This example works with the latest version of simplecov: https://gist.github.com/arsduo/d34be94b3c7aef7063a2d0728ac260ec

Additional configuration would be required to integrate this into GitHub Actions.

**Comment by pjhill** [comment]
Our assessment was that this was not feasible at this time for a couple reasons right? I can recall the fact that enforcing 90% for the entire repo is possible, but might not be fair to individual contributors as we cannot assess coverage related to only the modules or functionality that a PR touches. Was there another reason as well?
