### ISSUE TITLE
Provisioning of Elasticache instance (Redis) for platform-console

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#35394]
## Description
The console services team has created the [platform-console application](https://github.com/department-of-veterans-affairs/platform-console). Given this, the console services team will need an Elasticache resource (Redis) provisioned for key/value storage (e.g. Sidekiq).

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35354

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Redis cluster is up and live: https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#redis-group-nodes:id=dsva-vagov-dev-platform-console-api;clusters

**Comment by jbritt1** [comment]
Sooo I made a big oops and made these resources for dev instead of utility, working on moving to utility infra and naming convention(s).

**Comment by jbritt1** [comment]
New UTILITY Redis: https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#redis-group-detail:id=dsva-vagov-utility-platform-console-api

**Comment by jbritt1** [comment]
Think this is complete at this time, @LindseySaari feel free to reopen this if I am closing in error or if there is still something we need to do.
