### ISSUE TITLE
[Bug] O&E - Event-detail page - Content/styling/functional anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#35392]
## What happened?
On Drupal-dev **Outreach Events** > **event-detail** page, the following content/styling/functional anomalies were found:
1. **Repeats** line was missing frequency info ("daily"/"weekly"/"monthly").
2. **View other times...** > **Add to Calendar** links didn't match mockup, and also navigated to event-detail pages [not what link-texts indicated].
3. **Show more times** button was missing.
4. **Register** button was missing.

### Screenshots
![2022-01-13_17-56-06](https://user-images.githubusercontent.com/587583/149434417-8fa0bde8-8f46-4275-8a6e-80f21977b40d.png)

## Specs:
- **[SOCKS-proxy](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)** set up for accessing Drupal-dev environments
- **[Allow-CORS](https://prod.cms.va.gov/help/demo-environments-tugboat-guides/how-to-load-external-assets-in-tugboat-web-environments-how-to-disable-cors)** browser-extension added to Mac Chrome [Firefox extension's not working]
- Device: [device-agnostic]
- Browser: [browser-agnostic] BUT, to see assets on the page, Allow-CORS browser-extension currently only works in Mac Chrome.
- Test User: \[n/a\]

## Steps to Reproduce
- URL: https://web-43gdezdssgpjvowq7wez2c3k7wfhqgex.ci.cms.va.gov/saginaw-health-care/events/morning-meditation-with-mallory-0/ [IMPORTANT: See **Specs** above for tech requirements.]
- Under **When** section, observe that (1) **Repeats** line is missing frequency info ("daily"/"weekly"/"monthly").
- Below **social-links**, observe that (2) **Register** button is missing.

## Desired content/styling
- [ ] (1) **When** > **Repeats** line should include frequency info.
- [ ] (2) **View other times...** > **Add to Calendar** links should either (a) download ICS calendar-file, or (b) be removed and date-time line made a link that navigates to appropriate event-detail page.
- [ ] (3) **Show more times** button should be displayed.
- [ ] (4) **Register...** button should be displayed.

### Screenshots
![2022-01-13_18-04-37](https://user-images.githubusercontent.com/587583/149434998-c43683ea-afa0-4082-8b01-3c99c0272ff4.png)

## Acceptance Criteria
\[See **Desired content/styling** above\]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
@tlei123 a few comments, 1. was part of the design specs but we've pulled that from scope based on some limitations from CMS (Not having this data to pull in to support that model). 3&4. Not all events have a register button, those are dependent on editors to link as they are external register links placed in CMS for the events. 2. We are working to fix. Looping in @srsuddath

**Comment by tlei123** [comment]
> Not all events have a register button

@brianalloyd , thx much for your responses!  I have just a couple follow-up questions [cc @srsuddath]:

(3a) Will **Show more** [recurring date-times] still be displayed, and if yes, conditionally [maybe based on recurring date-times list-length]?
(4a) If a **Register** button isn't displayed, will we always get a **More details** button instead, or may we also have no button at all?  I did see some **More details** buttons on Staging for events that don't have Registration available, but don't know if that's always the single alternative state.

Pls. let me know.  Thx much!  :)

**Comment by brianalloyd** [comment]
3a. We'll show 6x events and if a single event has more then 6x events it will have the "show more" button.  
4a. Yes, if no register button displayed, it will will always have a "More details" in its place.  
Let me know if any additional questions exist.

**Comment by brianalloyd** [comment]
@srsuddath please go ahead and make the `en dash` change with this ticket. Per grooming discussion.

**Comment by srsuddath** [comment]
@brianalloyd with the except of the recurring events portion, this ticket has been completed and can be closed. We should create a follow-on ticket for the recurring events portion, as I am still figuring out how to spin up a branch in tugboat to test
