### ISSUE TITLE
Provisioning of RDS instance for platform-console

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#35393]
## Description
The console services team has created the [platform-console application](https://github.com/department-of-veterans-affairs/platform-console). Given this, the console services team will need an RDS resource (Postgres 13.x) provisioned.

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35353

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Postgres 13.5 db created in referenced pull request. Database password added to parameter store with path: `/dsva-vagov/platform-console-api/dev/db_password`

**Comment by jbritt1** [comment]
Sooo I made a big oops and made these resources for dev instead of utility, working on moving to utility infra and naming convention(s).

**Comment by jbritt1** [comment]
New UTILITY RDS DB: https://console.amazonaws-us-gov.com/rds/home?region=us-gov-west-1#database:id=dsva-vagov-utility-platform-console-api;is-cluster=false

**Comment by jbritt1** [comment]
Think this is complete at this time, @LindseySaari feel free to reopen this if I am closing in error or if there is still something we need to do.
