### ISSUE TITLE
Create another version of the test app that connects through OIDC

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#35391]
Currently, the test app uses the keycloak library to connect.  We need a version that connects using the vanilla OIDC

Task is done when: we can log in and see token for vanilla OIDC instance

**Comment by ken-non** [comment]
replicate how grafana connects to keycloak 
use case - if an application want to integrate and want to use their own OIDC
 - use existing OIDC library

**Comment by ken-non** [comment]
ready to deploy to dev

**Comment by ken-non** [comment]
@dginther to deploy
