### ISSUE TITLE
Add OMBInfo guidance on design.va.gov

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35397]
## Description
There is currently no documentation on design.va.gov about the OMBInfo component. We need to add it to the [components](https://design.va.gov/components/) section.

## Acceptance Criteria
- [ ] Add OMBInfo documentation to design.va.gov
- [ ] Check with Natalie and Courtney about any design or accessibility considerations

**Comment by mendacitees** [comment]
OMB Info page is being added to https://design.va.gov/components/   Each component is detailed there and contains an Accessibility Considerations section.  Courtney will be providing this information.

**Comment by CourtneyChambers77** [comment]
Was able to update the component and the SR JAWS is able to read and announce the content to the users [Uploading... JAWS_OMBInfo.mp4]

**Comment by mendacitees** [comment]
While working on this ticket, I discovered broken links on https://design.va.gov/components/buttons  The links for "Action Links" were linked to a nonexistent page.  The correct link was to:  https://design.va.gov/experimental-design/action_links  The 3 links on the page were all updated.

**Comment by k80bowman** [comment]
@CourtneyChambers77 I'm going to remove you from this ticket. I created a separate ticket for the accessibility documentation, we'll prioritize it in a future sprint.

@mendacitees we'll move ahead with this ticket with the PR you already submitted.
