### ISSUE TITLE
Create production idme monitor in datadog

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#35404]
# Description

# User Story
**As a** VSP Engineer
**I need** to know the health of the idme credential as it would flow through production va.gov
**So that** we are able to develop our applications to function correctly with a high level of security. 

# Acceptance Criteria

# Technical Description

**Comment by sylvesterlee1911** [comment]
Does this one meet the criteria for this one in datadog?

https://app.datadoghq.com/synthetics/details/9sc-mj9-i64

**Comment by sylvesterlee1911** [comment]
Working with Joe to determine if this one is complete to close
