### ISSUE TITLE
Access for [Paul Touchton]

### ISSUE THREAD

**Issue by ptouchton** [department-of-veterans-affairs/va.gov-team#35409]
### COR Name

Other

### Vendor Onboarding Representative Name

Other

### Your Name

Paul Touchton

### Your Email

paul.touchton@b3groupinc.com

### Name of Your Team

VAOS

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDnmB9o/VIvL7nC9z8xY4Fn8oVuTXr//DO2Rlc59KoEw1w4WifebHSvSpCs64hdE1tppE2C7X19J3htw7SK24eKMqiRhIidWgIFSLsQQXbCRK3qEuJ7XxC2wsJrAHObbD01xViToK3i0r+AbYMNxERV+pgH4i49NKs4IpidxZBCbo2FcGYRuzbquZjot0hlhX96ziiI6JtQoidkCjfrQAc58UGMAusWKgjd61QsemudIZh05+uIpflo73IZokmsPIHAEPx0fSAHP16SdiOYu9RiOU5iRDULUF0vp9EMcMvKCuoVdGzVx+1O1yeav6CpuPsbD4W7Wic+dxwA5w2y5rbxWeZm7gS8AX65gkQsxJ9AukxudVNkauO4iOEXnKYDe0AUxLN4EW580ctppyNUVHbu0Xokks9qzYSUiNAqC4rJuTVONpM6bH/XRtt2kEcduY7W4NN4l0KdquqlHwt15/FCIkaOiC0jvse9q6B0hfdM/LqAqne1c/DAqPY5eOwbR10= paultouchton@B3-04609-MAC.local

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
