### ISSUE TITLE
[ZOOM]: GIBCT Section 116 - Benefit amounts wrap to two lines when zoomed above 300%

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3540]
## Description

The Your Estimated Benefits module text starts to wrap unexpectedly when I zoom my layout greater than 300% at 1280px width. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a user who prefers to zoom my desktop layout, I want to see the Your Estimated Benefits module display text correctly up to 400% zoom.

## Steps to Recreate

1. Enter `https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/HACK%20REACTOR%20SOFTWARE%20ENGINEERING%20ONLINE` in browser
2. Zoom your browser to 400%
3. Scroll down to the Your Estimated Benefits section
4. Confirm the text is wrapping incorrectly

## WCAG or Vendor Guidance (optional)

* [WCAG 2.1: Understanding Success Criterion 1.4.10: Reflow (https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)

## Screenshots or Trace Logs

![Screen Shot 2019-11-18 at 12.16.45 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/e85ad77e-2518-44aa-b381-78a55d9cb20a)

**Comment by 1Copenut** [comment]
Closing this issue as the 116 audit is complete.

**Comment by elder-joseph** [comment]
@1Copenut Hey I actually have a fix for this I was getting ready to submit a PR.

**Comment by 1Copenut** [comment]
@elder-joseph Cool. PR looks solid.

**Comment by elder-joseph** [comment]
@1Copenut Awesome! thanks for the review!

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-11-21 at 8.38.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aa7894f6-17b7-42c3-9c7b-82f9c07f0756)

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-11-21 at 8.40.10 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c9fb5776-a5f4-49cd-af4d-921e6e4d2215)

**Comment by sonntag-adam** [comment]
@1Copenut

**Comment by sonntag-adam** [comment]
In staging.

**Comment by 1Copenut** [comment]
@sonntag-adam I verified this in Staging using the listed Acceptance Criteria. Moving to close.
