### ISSUE TITLE
Small change to display of hours

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3541]
**Following https://github.com/department-of-veterans-affairs/va.gov-team/issues/2405, we need to make a small change to the display of time, consistent with the [style guide](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones).**

**Task:** 
Add a space between the time and "a.m." and "p.m."

**Current Behavior:**
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/fab833d4-f39e-4a57-afcc-b6f541d18301)

**Acceptance Criteria:**
- Times are written out, using a.m. and p.m. with periods: 9:00 a.m.
- Noon and midnight are spelled out (not using 12:00 p.m. or 12:00 a.m.)
- Time is specified in hours and minutes, even when on-the-hour.
- Time ranges use the – en dash (not the shorter - hyphen) and a space on either side. 
- There is a space between the last number and the "a" or "p".

Addressing time zones are outside the scope of this issue and will be addressed in [#3530].

**Comment by brangi** [comment]
it's merged, closing
