### ISSUE TITLE
Discovery: Try out using one of our web components in a simple Vue app

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35417]
## Description
Our theory is that it should be relatively easy to use our web components inside any framework, but we want to experiment and find out for sure.

If possible, please run this experiment in an online coding environment like Codepen or Repl where you can share a link to your work. (It doesn't matter what you use, just something where it would be easy for someone else to view and run the code without installing a bunch of stuff locally)

For this ticket, you'll need to:
- build a quick "hello world" Vue app (use the latest version of Vue)
- import a couple of our web components and display it in the app
    - maybe start with a simple one, then try one that takes a function as a prop
- write up the process, noting any special things you had to do to make it work.

## Acceptance Criteria
- [ ] Build a simple Vue app in an online coding environment
- [ ] Import one of our simpler web components and use it in the app
- [ ] Import a web component that will take a function as a prop and use it in the app
- [ ] Record your process in a comment on this ticket. Include a link to your experiment.

**Comment by pdavies88** [comment]
Codesandbox Link: https://codesandbox.io/s/va-and-vue-cli-4lmiz

**Comment by pdavies88** [comment]
Docs from Stencil about usage: https://stenciljs.com/docs/vue
`The above technique for integrating a Stencil custom element library has been tested on a Vue application that was created using the vue-cli with ES2015 and WebPack as primary options`
* Also this was done with Vue 2 so the process may be different if someone uses Vue 3
* Based on this [article](https://vueschool.io/articles/news/which-vue-js-version-to-use-in-2021-and-why/#:~:text=Vue%203.0%2C%20codename%20One%20Piece,complete%20rewrite%20of%20the%20framework.) and this [one](https://dev.to/perenstrom/migrating-a-vue-2-project-to-vue-3-hdj) it seems that Vue 2 is currently what is being pushed by the Vue community until Vue 3 gets more integrations built out

**Comment by pdavies88** [comment]
To bind to a property, we use the `:` character. To bind a property to the dropdown title property, we write `:title="myTitle"`. In our Vue component, we have a `myTitle` property that has its value assigned to the title of the dropdown component.

To listen to events, we use the `@` character. Our dropdown has a single event show. To listen to this event, we write `@show="log"`. This event binding will call the `log` method on our Vue component whenever the show event occurs.

Real Code Example:
`In the <template>`
```
      <va-accordion-item
        id="first"
        :subheader="accordionSubHeader"
        @accordionItemToggled="accordionItemToggled"
      >
        <h6 slot="headline">First Amendment Headline</h6>
        Congress shall make no law respecting an establishment of religion, or
        prohibiting the.
      </va-accordion-item>
    </va-accordion>
```
In the `<script>` below the `<template>`
```
<script>
export default {
  name: "HelloWorld",
  data: function () {
    return {
      accordionSubHeader: "Subheader Test",
    };
  },
  methods: {
    accordionItemToggled: () => {
      console.log("Accordion Toggle");
    },
  },
};
</script>
```
