### ISSUE TITLE
Search by location not refreshing as expected

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#35419]
## Issue Description
When searching by location, if you do a search by city name, e.g. Chicago, IL, USA; you can type another city (e.g. New York, NY USA) to search and it will load with no issue.  But if after you search by city name, you type in a zip code, it does not refresh and shows the original search, e.g. Chicago, IL USA.

**Comment by SebVortex** [comment]
Looking over this, I believe there is a functionally deeper issue with the search.
The description of this task does not always manifest. But issues always occur after geoLocation is attempted.

Even if the button is not clicked, some searches prompt geolocation and the button for using my location gets clicked onSubmission

**Comment by SebVortex** [comment]
Looking over this, I believe there is a functionally deeper issue with the search.
The description of this task does not always manifest. But issues always occur after geoLocation is attempted.

Even if the button is not clicked, some searches prompt geolocation and the button for using my location gets clicked onSubmission when using the autofill in the search bar.

Solving this might solve other issues too but that remains to be seen.

**Comment by SebVortex** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20041

**Comment by hallihocine** [comment]
Ticket has been validated in staging: search by location is now refreshing as expected. After two autocomplete searches, if you type in a zip code then hit the "Enter" key on the keyboard, it does refresh the search and shows the new search results. See Below: 

https://user-images.githubusercontent.com/86266024/151402215-bd20583a-1bf5-4e27-b94c-984c50f8c7de.mov

**Comment by hallihocine** [comment]
- Test Run in TestRail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2879&group_by=cases:section_id&group_order=asc&group_id=3598
- Test script/steps:
[Search by location not refreshing as expected.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7952244/Search.by.location.not.refreshing.as.expected.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT approved on 1/28/2022.
