### ISSUE TITLE
STEM (Form 22-10203): checkbox not checkable (in Step 5 of 6: Personal Information)

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#35414]
## What happened?
In Step 5 of 6: Personal Information, unable to check the checkbox : [ ] I would like to receive text messages from VA about my GI Bill benefits.
-Screenshot below: 
<img width="563" alt="Screen Shot 2022-01-14 at 11 55 36 AM" src="https://user-images.githubusercontent.com/86266024/149556812-7b6d2902-8814-430b-b57e-e119ec5567cc.png">

## Steps to Reproduce
- Navigate to: https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction
- Proceed to Step 5 of 6: Personal information
- Select the checkbox - [ ] I would like to receive text messages from VA about my GI Bill benefits.

## Desired behavior
- User should be able to check/uncheck the checkbox

## Acceptance Criteria
- [ ] User should be able to check/uncheck the checkbox

**Comment by nbarthelemy** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19998

**Comment by nbarthelemy** [comment]
I have reached out to @dan-brooking and @SebVortex for assistance on this ticket.

**Comment by hallihocine** [comment]
Ticket has been validated in staging: the checkbox is now checkable/uncheckable. 

https://user-images.githubusercontent.com/86266024/152552951-b2805bc8-51e4-4fab-bd29-edccc744e6ba.mov

**Comment by hallihocine** [comment]
- Test Run in TestRail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2888&group_by=cases:section_id&group_order=asc&group_id=3598
- Test Steps: 
[STEM (Form 22-10203) checkbox not checkable (in Step 5 of 6 Personal Information).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8004099/STEM.Form.22-10203.checkbox.not.checkable.in.Step.5.of.6.Personal.Information.xlsx)

**Comment by mrblanco1** [comment]
PASSED QA and UAT on 2/7/2022.
