### ISSUE TITLE
[COGNITION]: GIBCT Section 116 - Suggest adding semantic markup to SCO contact lists for assistive device users

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3542]
## Description

The SCO primary and secondary contacts lists could be marked up as lists with smart heading labels for better usability by assistive technology users. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I would like to hear the primary and secondary SCO lists announced as lists, with the number of items included.
* As this user, I would also like these lists to be labeled by their respective headings

## Possible Fixes (optional)

```html
<h4 class="contact-heading" id="primary-contact-header>Primary Contact Officials</h4>
<ul aria-labelledby="primary-contact-header">
  <li>
    Thomas Jefferson
    President
    tjefferson@providername.com
    123-456-7890
  </li>
  ...
</ul>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## PRs
https://github.com/department-of-veterans-affairs/vets-website/pull/11197

## Screenshots or Trace Logs

![Screen Shot 2019-11-18 at 12.22.46 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/d68ee45d-366d-4722-b2cc-36e15fe4bb87)

**Comment by hughes-dustin** [comment]
branch: bah-3542
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11197

**Comment by delli-gatti-michael** [comment]
Local testing complete with Voiceover. Once this is in Staging I can test again with JAWS and NVDA

**Comment by delli-gatti-michael** [comment]
@1Copenut This is now live in Staging and ready for your review.

[This profile page has several Primary and Secondary School Certifying Officials](https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/HACK%20REACTOR%20SOFTWARE%20ENGINEERING)

**Note:** The Phone number and Email have been removed, so you will only be able to see the Name and Title for each SCO.

**Comment by 1Copenut** [comment]
Just tested this in JAWS (IE11, Chrome) and NVDA (Chrome, Firefox) and VoiceOver. It's announcing as expected and throwing no axe errors. Moving to close.
