### ISSUE TITLE
Archive redirected Agent Orange pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35427]
## Issue Description
The Sitewide Content team moved all the Agent Orange information from individual pages to the [Agent Orange exposure and VA disability compensation](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/) and redirected the individual pages. We can now archive these old pages within Drupal.

Here is the list to archive: 
VA Agent Orange Registry exam: http://preview-prod.vfs.va.gov/preview?nodeId=877
Agent Orange exposure in Vietnam or Korea: http://preview-prod.vfs.va.gov/preview?nodeId=879
Agent Orange exposure on Navy or Coast Guard ships: http://preview-prod.vfs.va.gov/preview?nodeId=876
Agent Orange exposure on Thailand military bases: http://preview-prod.vfs.va.gov/preview?nodeId=881
Agent Orange exposure from C-123 aircraft: http://preview-prod.vfs.va.gov/preview?nodeId=875
Agent Orange testing and storage outside Vietnam: http://preview-prod.vfs.va.gov/preview?nodeId=880

## Tasks
- [x] Archive articles in Drupal

## Acceptance Criteria
- [x] Redirected Agent Orange pages are now archived

**Comment by lunascoop** [comment]
These pages are now archived.
