### ISSUE TITLE
Add GitHub Actions

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#35422]

**Comment by LindseySaari** [comment]
@RachalCassity I started a branch [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/lhattamer-create-platform-console-dir-structure) with some boilerplate directories and a deployment.yml file

**Comment by RachalCassity** [comment]
> @RachalCassity I started a branch [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/lhattamer-create-platform-console-dir-structure) with some boilerplate directories and a deployment.yml file

**Comment by RachalCassity** [comment]
@LindseySaari I do not have access to clone this repository. DO I need to be added to a list?

**Comment by LindseySaari** [comment]
> @LindseySaari I do not have access to clone this repository. DO I need to be added to a list?

Oh that makes sense. It looks like I don't have admin access, so you may need to request access from the Infrastructure team.
