### ISSUE TITLE
[Discovery] View All Contested Issues

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3543]
## User Story or Problem Statement
As a claimant, I need to view all of my contested issues in a single location so I can be sure what issues I have contested.

## Goal
_A user is able to see all of their contested issues on a single page_

## Tasks
- [x] _Identify if a page with all contested issues already exists_
- [ ] *If not,* design a page that displays all contested issues (new design)

## Acceptance Criteria
Scenario: A Veteran wants to see all of their contested issues, not just ones applicable for a Higher Level Review
GIVEN a system user is logged into va.gov
WHEN the user selects to view all of their contested issues
THEN the system directs them to a page that has all of the contested issues listed

**Comment by YanaRoy** [comment]
@rileyorr this is discovery only - one of the other VSA teams said they were working on this page. Not sure which team.

**Comment by rileyorr** [comment]
@YanaRoy I believe the eBenefits team is working on this page. I've started a convo between me, Jason, Robin, Kevin to see where that team is at in the design process and whether or not our design needs to change for the time being. I will keep you updated as I get more info

**Comment by rileyorr** [comment]
@YanaRoy The eBenefits team _is_ working on this page and it is [currently in staging](https://staging.va.gov/disability/view-disability-rating/rating/) undergoing review. @Mottie has the link, so we may be good to close this ticket unless you need anything else from me!
