### ISSUE TITLE
Access for Aaron Hietpas

### ISSUE THREAD

**Issue by aaronhietpas** [department-of-veterans-affairs/va.gov-team#35430]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Aaron Hietpas

### Your Email

aaron.hietpas@libertyits.com

### Name of Your Team

Team Name = Matsumoto Company = Libertyits Role = Software Engineer

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqnl2kgIEMWXiTyY7rXkbMGJzO+3rOUY1ynzVwv5K/OkbxhoqNX5ykwlffBbXepk363d7yfHwePOoOorRGPSunOegTGNsHT1qwVVNmU6L0hBiHy6Zwy3yPRPyxSs0tAoujZdJKkC0W9bJ4aSibB+yF+tEB/g7VIZplf3ZmMtM5ecJ1cuEcrWzJjHpKrG8gimj96QHpaTuwaoIYoc9FDNZfIgVJCNJUuRrW14dfFB1W+zA4xAuxDAoHixxKZUfY0UrCTj9ukUGtRy2fBeLP5PlP1ZxV/XNFTM7ciFe2a2rurd/M/w9IdkXmlmziExvApikLqNPhJnfvmvySKuVSf7RjKN59OE7h52T+ugjkJmZktucst37b2I3PwwvJxgghJ3Y17J0lya91MK5SHideTDeoPJA2Zw62dvYZwe2kkBpyNhIjcZqy8oGeHw3iC69n0JbuisO/VXBrjlKu6YNdFMaweB+JZm5W5jjtqgooi8GLUIKHc5iweutEck+U6/eNzME= AzureAD+AaronHietpas@DESKTOP-AO80DSI

### Desired AWS Services

YES
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

**Comment by jbritt1** [comment]
### For AWS Access

User: Aaron Hietpas
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level access: no

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Approved

**Comment by jbritt1** [comment]
First-time login credentials passed to user at this time.
