### ISSUE TITLE
URGENT REQUEST - Adding Alexander Spottswood to DSVA Slack

### ISSUE THREAD

**Issue by margaret-figueroa** [department-of-veterans-affairs/va.gov-team#35438]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

URGENT REQUEST: please grant Alexander Spottswood to DSVA slack. His email is spottswood_alexander@bah.com

Add individual as a:

- Full member
- Add to #appeals channel

Alec is a tech lead on our project supporting production issues. He needs access to DSVA slack urgently to triage production issues that are coming through. 

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!
