### ISSUE TITLE
Create datadog isam metadata monitors

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#35436]
Example dev monitor: https://app.datadoghq.com/synthetics/details/2r7-e82-zzk

Create the same as above but for the following URLs
- [x] Create for staging: https://sqa.eauth.va.gov/isam/saml/metadata/saml20idp
- [x] Create for production: https://eauth.va.gov/isam/saml/metadata/saml20idp

**Comment by sylvesterlee1911** [comment]
production complete.

**Comment by sylvesterlee1911** [comment]
Completed and reviewed.
