### ISSUE TITLE
Create a GitHub CSV File Ingest

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35433]
# Description
Plan and implement an ingestion mechanism that extracts a CSV file form a DSVA org owned GitHub repo and loads it into BigQuery.

## Acceptance Criteria
- [x] Create a workflow that results in an up-to-date table in BigQuery containing the details for all products described in the Product Directory CSV
- [x] The ingest handles product name changes
- [x] The ingest handles product additions
- [x] The ingest handles product deletions

**Comment by CBonade** [comment]
Created a feature branch today and have set up a child class to feed off our main github class and fetch a file, then decode the base64 encoded file back into the regular file and output it. Tomorrow, will handle processing the file.

**Comment by CBonade** [comment]
This is complete and merged in. It is currently disabled pending the actual repo creation and product list's existence. Comments have been added with everything that will need to be updated when the product list is available.

**Comment by pjhill** [comment]
Hooray CSV!
