### ISSUE TITLE
Research Programmatic Creation of a Domo Dashboard from a Template

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35434]
# Description
In order to be able to spin up new dashboard without significant manual intervention from Platform, we need to be able create a new dashboard for a product programmatically.

* Does Domo have the capability to create new dashboards through its API?
* How best should we trigger that creation?
* What if we created a dashboard template from which we copied to create new dashboards?

## Acceptance Criteria
- [x] We have evaluated the option of storing a set of attributes for the automatically generated dashboards in BQ tables. Commentary and analysis is added to this ticket.
- [ ] Given the question prompts above, we have documented a process for using Domo's API to generate new product dashboards based on events.
- [x] We have evaluated the viability of generating a new dashboard with product specific filters pre-applied. Commentary and analysis is added to this ticket.
- [ ] Define a process to modify the dashboard template based on parameters retrieved from the product directory CSV

**Comment by CBonade** [comment]
Created a feature branch today and have set up a child class to feed off our main github class and fetch a file, then decode the base64 encoded file back into the regular file and output it. Tomorrow, will handle processing the file.

**Comment by pjhill** [comment]
Given the outcome of the research effort, we will not be pursuing automated creation of customized product-focused QA dashboards at this time. Given that Domo is under active development, it may be prudent to revisit the capabilities in the second half of 2022.
