### ISSUE TITLE
Define Schema for Product Directory in CSV Form

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35431]
# Description

In order to maintain the usability and parse-ability of the product directory we need to establish a schema by which products must adhere in order to be registered in the product directory.

Consider CSV, JSON, YAML

This effort may require synch time with --

* `vets-website` SME -- [This ](https://docs.google.com/spreadsheets/d/1KJZuxNYKEaCQg3F9zJNMSwa2NGguZ86VVZ8cMIUTXq8/edit?usp=sharing)exploration of `vets-website` will be useful
* `vets-api` SME
* Domo SME
* GitHub SME

## Acceptance Criteria
- [x] We have a list of product attributes that we need to link products to all the data sources we use
  - [x] Governance team has a stake in the solution and has provided the product attributes they require of a Product Registry
- [x] We treat the CSV like a [flat file](https://www.techopedia.com/definition/25956/flat-file) for a database
- [x] We have defined a schema for the CSV
- [x] We have a document in Confluence explaining the schema for the CSV
- [x] Our document defines each value and describe what it will be used for
- [x] Prescribe a repository to store the CSV in

**Comment by rjohnson2011** [comment]
Reached out to discuss parameters for the schema across several teams. Putting information together in a Confluence doc to share soon.

**Comment by rjohnson2011** [comment]
Schema is defined in the following Confluence doc -> https://vfs.atlassian.net/wiki/spaces/TTT/pages/2062155780/Product+Directory+Schema

**Comment by pjhill** [comment]
> Schema is defined in the following Confluence doc -> https://vfs.atlassian.net/wiki/spaces/TTT/pages/2062155780/Product+Directory+Schema

Nice, thanks for throwing that into a document. I have a couple questions / requests --
1. The name and data type is a good start. Are we able to add an explanation for the intended use? For example, `codeowner` is inteded to be used to hold an array of GitHub groups marked as codeowners in the `vets-website` repository -- or something like that.

**Comment by pjhill** [comment]
- [ ] @JoeTice provide information on how to coordinate sharing requirements with Governance

**Comment by rjohnson2011** [comment]
Per post-standup discussion, QA team will proceed with CSV file as documented and planned on QA Standards sprint board.
