### ISSUE TITLE
[Design] Logged in notice displays global content

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3544]
## Problem Statement
The gray box that is displayed when a user is logged in does not show content that is currently identified globally for all forms. The language needs to be updated to display accurate wording.

## Goal
_content in logged in gray box should display wording that has been identified for all forms_

## Acceptance Criteria
- [x] _Content in logged in gray box has been updated in design mockups_

## Global Content for Logged in box
![Screen Shot 2019-11-18 at 12.22.38 PM.png](https://images.zenhubusercontent.com/5d52c3244773cd34ebdf4867/8004c0be-720e-41f3-9bfb-11be042f53c3)

**Comment by rileyorr** [comment]
@YanaRoy Where is the current screenshot coming from? The mockup I see for this page already has the correct message: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385994366_Signed_In-File_A_Higher_Level_Review_

**Comment by rileyorr** [comment]
<img width="832" alt="Screen Shot 2019-11-21 at 3 44 16 PM" src="https://user-images.githubusercontent.com/46329147/69375314-0d7a1400-0c76-11ea-831d-0fa74aafb1bf.png">

Screenshot from the education benefits form for reference

**Comment by rileyorr** [comment]
@Mottie pls see above comments, you may know more about this

**Comment by Mottie** [comment]
That component is shared across all forms. I think we're not seeing the "prefill" message because we're not hooked into an API yet. Once we are, then we can revisit this issue.
