### ISSUE TITLE
Access for Rebecca Tolmach

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#35449]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Rebecca Tolmach

### Your Email

rebecca.tolmach@adhocteam.us

### Name of Your Team

VSP Infrastructure, Backend Engineer at Ad Hoc

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDncj7TKhc7F3Xb7kWi9qskvhk71ocAWReoQwJE+xeSOSvX0A4Gh+bbu8r2bzShjPHoKrYYRq8tGw7Q9Eb5of86ZJMG5JxmjrV2WeA+p+M99SFwu4f1WSjyK2YU/SQs1Pok9GWpW+2TIbjg2FFvaVEJP1iTZh0KkQZP4WHvjVttdaH4in19rwTwistlkV1dZXN/gBYd2lzSsZZUFuIjPqocMC/p+oMiXwT0VmzznAqoZDocsXwS6eIxiWPP7O73iTBOC4PV7Hp7mgP8iVviWai4ihmP3n50AM5ArmK8nJKVA9fdFlPM00oVgkupz6YoKbnOp5SHjZV9ivXuKO1aIVNDfkIERkZMJfN4T2z5w4Loai3C6CB3AphFczgZk8iXw07uQ8+81m7Z8wT5M4QKKy9ydBL4c+Ca3GHKYqPyeX7KUbDFT8QQxodRklzjZdMru9DzuzQouv/BAAIR+fH1pyiyl6uIVNVzWjzyOS0mEsnr+b30djZzVMtkOYG4D5NGbjc= rebeccatolmach@RebeccalmachMBP.attlocal.net

### Desired AWS Services

I'm on the operations/platform infrastructure team and will need full admin access. Thanks!

**Comment by jbritt1** [comment]
### For AWS Access

User: Rebecca Tolmach
COR: Mary O’Toole
VOR: Oddball - Amber Malcolm
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level access: yes (platform infrastructure team)

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Comment by td-usds** [comment]
Reached out to VOR for eQIP transmittal date. @jbritt1, can you she is a member of the ops team? The permission boundary that applies to your team would apply to her as well (i.e. it's not actual 'full' admin)

**Comment by jbritt1** [comment]
> Reached out to VOR for eQIP transmittal date. @jbritt1, can you she is a member of the ops team? The permission boundary that applies to your team would apply to her as well (i.e. it's not actual 'full' admin)

Definitely a new vsp-operations/platform infrastructure team member, can confirm.

**Comment by td-usds** [comment]
Still awaiting information from VOR; VOR is aware of data call.

**Comment by td-usds** [comment]
Approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
