### ISSUE TITLE
[Bug] VA.gov Profile  - Personal Information radio button does not select unless label is clicked

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35443]
## What happened?
When accessing the Personal Information page in the VA.gov Profile on Staging a selection is only made when clicking on the label, but not when clicking the radio button itself.    This does work as expected in the [Design System](https://design.va.gov/components/form-controls#radio-buttons) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-radiobuttons--default). 

## Specs:
- Device: Windows 10
- Browser: Chrome
- Test User vets.gov.user+36@gmail.com

## Steps to Reproduce
- URL:   https://staging.va.gov/profile/personal-information
- Test User _(if applicable)_: vets.gov.user+36@gmail.com
- Click the Gender Identity section, then click on one of the radio buttons to attempt to select gender identity. Observe that the selection does not occur.  Click the label next to one of the radio buttons and observe that the selection does occur.  The same problem occurs in the Sexual Orientation section.
 
## Desired behavior
A selection should be made regardless of whether the radio button or its corresponding label is clicked.

## Acceptance Criteria
- [x] Clicking the radio button or its corresponding label both result in a selection being made

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by adamwhitlock1** [comment]
This is ready to validate in staging now @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
🎆 🎉 Looks great @adamwhitlock1!  Nice job!  cc @Samara-Strauss
