### ISSUE TITLE
Create an MVP of the Product Directory CSV

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35440]
# Description
In order to continue with the work of generating and using a CSV product directory, we need an MVP-version of one that we can use for development and testing.

Updates to the MVP should be through Pull Requests to the repository housing the CSV.

## Acceptance Criteria
- [ ] We have a MVP of the CSV product directory created using information that our team gathered without VFS team input as a starting point from which to begin

**Comment by rjohnson2011** [comment]
Created internal repo to hold the CSV file at https://github.com/department-of-veterans-affairs/product-directory

In process of converting existing metrics data into a CSV file and pushing to the repo.

**Comment by rjohnson2011** [comment]
Created a Sheet to generate the CSV from, currently populated by available information from QA Standards and Governance teams -> https://docs.google.com/spreadsheets/d/1i3stItblzCWZXHKTMsRoprk1zhReaZehL0AsOWDI59c/edit?usp=sharing

Continuing to add to the spreadsheet and will upload the exported CSV to the new repo.

**Comment by rjohnson2011** [comment]
In the process of writing a script to combine the tables of QA Standards & Governance products, removing duplicates. Once done, the process will combine multiple team's product tables automatically. Will upload that to the repo along with the generated CSV when done.

Also added a property 'Referral' to the table to identify which team submitted a product to the products list.

**Comment by rjohnson2011** [comment]
Uploaded the Python script to combine product tables automatically. The file `combineTables.py` takes Table A and fills in any missing details from Table B, by matching according to the column of Product Name. When a row has been updated, the Referral appends the name of that team to that value. 

The CSVs for QAProducts (exported from https://docs.google.com/spreadsheets/d/1_F1jMh9lgWAdNVcUmyUEuY5e3nytH8ywE0IP0mgDx8s/edit#gid=0) & GovProducts (compiled from https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) are on the repo as well as the resulting combination CSV, `CombinedProducts.csv`.

https://github.com/department-of-veterans-affairs/product-directory

**Comment by rjohnson2011** [comment]
Closing ticket for now - will reopen if any more tables / columns are to be appended to the Product Directory CSV.
