### ISSUE TITLE
Redirect Request for Vet Centers live as of 1.14.22

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35453]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

As the new Vet Center pages are rolled out, the legacy details pages for Facility Locator, Directory location pages and key staff pages need to direct Veterans to the new web presence. These requests will be made in bulk for the locations which have gone live in the previous two weeks.

Note: Outstations have their own Directory location and key staff pages but will be part of the new respective main Vet Center's Location page. Mobile Vet Centers do not have their own Directory location pages and are suppressed from the Facility Locator.

### Implementation date
No specific date - at your earliest convenience

### Redirects 

Current URL | New URL
-- | --
www.va.gov/find-locations/facility/vc_0235V | https://www.va.gov/annapolis-vet-center/
www.va.gov/find-locations/facility/vc_0134V | https://www.va.gov/berlin-vet-center/
www.va.gov/find-locations/facility/vc_0516V | https://www.va.gov/farmington-vet-center
www.va.gov/find-locations/facility/vc_0801MVC | https://www.va.gov/hartford-vet-center/
www.va.gov/find-locations/facility/vc_0117V | https://www.va.gov/hartford-vet-center/
www.va.gov/find-locations/facility/vc_0832MVC | https://www.va.gov/farmington-vet-center/
www.va.gov/find-locations/facility/vc_5162OS | https://www.va.gov/farmington-vet-center/
www.va.gov/find-locations/facility/vc_5161OS | https://www.va.gov/farmington-vet-center/
www.va.gov/find-locations/facility/vc_0118V | https://www.va.gov/south-burlington-vet-center/
www.va.gov/find-locations/facility/vc_0805MVC | https://www.va.gov/watertown-vet-center/
www.va.gov/find-locations/facility/vc_0135V | https://www.va.gov/watertown-vet-center/
www.va.gov/find-locations/facility/vc_0123V | https://www.va.gov/white-plains-vet-center/
www.va.gov/find-locations/facility/vc_0803MVC | https://www.va.gov/white-river-junction-vet-center/
www.va.gov/find-locations/facility/vc_1221OS | https://www.va.gov/white-river-junction-vet-center/
www.va.gov/find-locations/facility/vc_0122V | https://www.va.gov/white-river-junction-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5936&dnum=All | https://www.va.gov/annapolis-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5646&dnum=All | https://www.va.gov/berlin-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=490&dnum=All | https://www.va.gov/farmington-vet-center
https://www.va.gov/directory/guide/facility.asp?ID=653&dnum=All | https://www.va.gov/hartford-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5467&dnum=All | https://www.va.gov/farmington-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=477&dnum=All | https://www.va.gov/south-burlington-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5619&dnum=All | https://www.va.gov/watertown-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5303&dnum=All | https://www.va.gov/white-plains-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=6245&dnum=All | https://www.va.gov/white-river-junction-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=478&dnum=All | https://www.va.gov/white-river-junction-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5936 | https://www.va.gov/annapolis-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5646 | https://www.va.gov/berlin-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=490 | https://www.va.gov/farmington-vet-center
https://www.va.gov/directory/guide/keystaff.cfm?id=653 | https://www.va.gov/hartford-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5467 | https://www.va.gov/farmington-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=477 | https://www.va.gov/south-burlington-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5619 | https://www.va.gov/watertown-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5303 | https://www.va.gov/white-plains-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=6245 | https://www.va.gov/white-river-junction-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=478 | https://www.va.gov/white-river-junction-vet-center/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@brianalloyd These redirects are ready and can be completed at your earliest convenience. 

Please note: the "id" parameter is the key element in the existing URL. That ID must redirect regardless of any other parameters in, or what order the parameters are in.

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/10630

**Comment by tmac9494** [comment]
merged into prod yesterday afternoon

**Comment by mnorthuis** [comment]
Validated.
