### ISSUE TITLE
VAOS Swagger Updates

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#3545]
As part of our aggressive MVP release schedule we've had to put swagger documentation of the API on the backburner for the time being. This issue is to keep track of this as necessary tech debt and address in sprint shortly after release.

documentation on swagger blocks: https://github.com/fotinakis/swagger-blocks
there should also be a bunch examples of existing swagger that you can find by doing a search for that includes statement: `include Swagger::Blocks`

**Comment by sjbrush** [comment]
created swagger blocks files for community eligibility and supported sites.  Will create PR for those 2.
