### ISSUE TITLE
VAOS Status Homepage - Pending 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#35450]
## Description
Create a new view to display open/canceled appointment request(s). Currently the Veteran views their request for appointments on the VAOS homepage if the status is Requested. We will add a new link "Pending" on the homepage which will re-direct the veteran to a separate view displaying their appointment request(s). 

![Screen Shot 2022-01-19 at 10.25.37 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/4476efbe-0d85-4249-bfed-dd725b5dd200)
---

## Acceptance Criteria
Background: the `va_online_scheduling_status_improvement` toggle is on

Given the user lands on the VAOS homepage
When the user clicks on the Pending link
Then the user will be routed to a new view that will show their open and/or canceled appointment request(s). 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/status-list-pending.md) 
And page design matches the [design spec](https://www.sketch.com/s/7ceea77b-e368-4ed1-af98-3b7c57cf3124/a/WKQoDDw)

Given the user lands is on the Pending appointments view, 
When the user wants to return back to the VAOS homepage
Then the user will click on the breadcrumb "Your appointments" to be re-directed back to the homepage
And page design matches the [design spec](https://www.sketch.com/s/7ceea77b-e368-4ed1-af98-3b7c57cf3124/a/WKQoDDw)

Update the existing URL link to match the page title. Currently the URL shows Requested. We should display Pending: 

**Current URLs:** 
- _Staging_ `https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/requested`
- _Production_  `https://va.gov/health-care/schedule-view-va-appointments/appointments/requested`

**Updated URLs:** 
- _Staging_ `https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/pending`
- _Production_  `https://va.gov/health-care/schedule-view-va-appointments/appointments/pending`

Update the page metadata to display Pending instead of Requested 
<img width="413" alt="Screen Shot 2022-01-18 at 6 36 06 PM" src="https://user-images.githubusercontent.com/90797205/150035956-b5834d0e-4a3c-473e-9b31-a4bda509e62c.png">

### Design Assets
[Concept]()

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
When picking up the ticket, please review the print view work ([#35137](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/35137)) to see if there will be any issues/conflicts that may happen if these changes are implemented.

**Comment by vbahinwillit** [comment]
Changes where addressed #35271

**Comment by ldelacosta** [comment]
Validated the URL link and page metadata in staging: 
![Screen Shot 2022-02-16 at 3.54.53 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/275f9b06-da1b-4f6f-a041-7e5cddfa8287)

**Comment by ldelacosta** [comment]
Validated the acceptance criteria #1 and #2 in staging. 

![Screen Shot 2022-02-16 at 3.57.19 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/268d2051-36ae-4172-8c2c-4e31aed8a9ea)
