### ISSUE TITLE
VAOS Status Homepage - Past appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#35458]
## Description
Create a new view to display past VA booked appointment(s). Currently the Veteran views their past appointments on the VAOS homepage if the status is Past. We will add a new link "Past" on the homepage which will re-direct the veteran to a new view displaying their past appointment(s).

![Screen Shot 2022-01-19 at 10.29.24 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/4b9c4618-22cf-4b33-b516-f879355faf44)

---

## Acceptance Criteria
Background: the `va_online_scheduling_status_improvement` toggle is on

Given the user lands on the VAOS homepage
When the user clicks on the Past link
Then the user will be routed to a new view that will show their past VA booked appointment(s).
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/status-list-past.md)
And page design matches the [design spec](https://www.sketch.com/s/7ceea77b-e368-4ed1-af98-3b7c57cf3124/a/bgvA444)

Given the user in the Past appointments view
When a user selects a time period 
Then the user will no longer see the update button 
And the user will be able to view their selection based on the timeframe they have selected

Given the user lands is on the Past appointments view, 
When the user wants to return back to the VAOS homepage
Then the user will click on the breadcrumb "Your appointments" to be re-directed back to the homepage. 
And page design matches the [design spec](https://www.sketch.com/s/7ceea77b-e368-4ed1-af98-3b7c57cf3124/a/WKQoDDw)

Use the existing URLs for the past appointments when user is routed to the new view: 
**Current URLs:** 
_Staging_ `https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/past`
_Production_ `https://va.gov/health-care/schedule-view-va-appointments/appointments/past`

### Design Assets
[Concept]()

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
When picking up the ticket, please review the print view work ([#35137](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/35137)) to see if there will be any issues/conflicts that may happen if these changes are implemented. 

Also there is a [spike ticket ](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/35128)for the update button. Please review if there is a conflict for this work.

**Comment by ldelacosta** [comment]
Please review the technical notes for removing the Update button on the past appointments view. [Spike Ticket #35128](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/35128)

**Comment by vbahinwillit** [comment]
Content update changes where address in #35271.

**Comment by ldelacosta** [comment]
Validated the changes in staging. 

Selecting the different time periods: 
![Screen Shot 2022-02-14 at 9.53.04 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/70ec6c62-2fe1-4269-9f51-8151c957933d)

Past view (default to past 3 months): 
![Screen Shot 2022-02-14 at 9.52.37 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2270bb0e-3945-4baa-a022-147b71f1f4f8)

Sample past appointments (All of 2021): 
![Screen Shot 2022-02-14 at 9.59.33 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/31a5dd91-9e01-4582-8a5e-39e35dcde138)
