### ISSUE TITLE
Business intake form for Lighthouse Appeals - Notice of Disagreement digital submission

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va.gov-team#35461]
## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
We would like to send a notification email when the Notice of Disagreement (NOD) has been received by VA. This will give the Veteran confidence in the submission and prevent duplicate submissions.

## What is an overview of the notification use case? (required 3-5 sentences) 
This notification will work exactly like the recent one implemented for Higher Level Review (and soon Supplemental Claims) but with a Notice of Disagreement template.

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
A Veteran will submit a Notice of Disagreement on VA.gov. Once the submission have been accepted by the Central Mail Portal, we will send the Veteran an email saying we have received the submission. This will give Veterans the confidence that they do not need to resubmit.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No. Digital submission of NOD will be new functionality.

## What kind of notification would this be? (required Email, Text, Not sure)
Email

## If you have a draft of the content you’d like to send - please upload here. Please note we collaborate with all of our users on their content to ensure it meets standards. (optional - blank) 

> Dear Jane,
> 
> Thank you for filing a Notice of Disagreement.
> 
> To check your appeal status, go to https:///www.va.gov/claim-or-appeal-status/ to sign in to our claim status tool. Please allow at least three business days for your Notice of Disagreement to show up there.
> 
> Your Appeal details are below:
> Notice of Disagreement
> 
> Date Submitted
> January 2, 2022
> 
> If we have questions or need more information, we may contact you. We’ll notify you once we have processed your Notice of Disagreement. If you need to contact us please visit https://va.gov or by phone: 1-800-827-1000.
> 
> Thank you for your service,
> VA
> 
> You are receiving this email because you filed a Notice of Disagreement with VA. Please do not reply to this email.

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
This content has been approved by Board leadership per John Gosnell.

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
vets-api

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
Yes

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
not sure exactly how it will work yet but we have discussed it with our stakeholders. (Premal Shah, John Gosnell)

## What is your estimated volume of notifications per day, week, month? (optional - open space)
Could be up to ~6000 per month, but more likely will be ~2000 per month, at least to start.

## When does this notification need to be in production? (optional - open space)
We would like to add this functionality to our API before the NOD app goes live on VA.gov, but there is no set timing for that yet.

**Comment by miabecker** [comment]
@kellylein great to hear from you! I sent you an email with how to login to our UI which we recently launched. Let me know if you have any questions but you'll be able to create the notification yourself.

**Comment by bevnobev** [comment]
Hi @kellylein. Checking to see if you have a timeline for going live in Production.  cc: @mjones-oddball

**Comment by kellylein** [comment]
We are in the same situation for this one as for Supplemental Claim, though this one will likely be sooner.
