### ISSUE TITLE
Discovery: Try out using our web components in a simple Node JS app

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35468]
## Description
Our theory is that it should be relatively easy to use our web components inside any framework, but we want to experiment and find out for sure.

If possible, please run this experiment in an online coding environment like Codepen or Repl where you can share a link to your work. (It doesn't matter what you use, just something where it would be easy for someone else to view and run the code without installing a bunch of stuff locally)

For this ticket, you'll need to:
- build a quick "hello world" Node app using only vanilla JS
- import a couple of our web components and display them in the app
    - maybe start with a simple one, then try one that takes a function as a prop
- write up the process, noting any special things you had to do to make it work.

## Acceptance Criteria
- [ ] Build a simple Node app in an online coding environment
- [ ] Import one of our simpler web components and use it in the app
- [ ] Import a web component that will take a function as a prop and use it in the app
- [ ] Record your process in a comment on this ticket. Include a link to your experiment.

**Comment by pdavies88** [comment]
Vanilla JS CodeSandbox: https://codesandbox.io/s/web-components-vanilla-js-0ir2h?file=/index.html
Stencil JS Docs: https://stenciljs.com/docs/javascript

Notes:
* `index.js` has examples of using event listeners for custom events and dynamically setting props
* In general props can be added inline or inserted with JS

**Comment by pdavies88** [comment]
Express App which leverages Node to create the Web Server: https://codesandbox.io/s/express-web-components-7k675?file=/public/index.html
Stencil JS Docs: https://stenciljs.com/docs/javascript

Notes:
* `index.js` has examples of using event listeners for custom events and dynamically setting props
* In general props can be added inline or inserted with JS

**Comment by pdavies88** [comment]
The set up for web components in both is the same as they are both using Vanilla JS. 

Side note Codesanbox does have some handy templates to use when setting up Hello World apps in their environments. For this ticket I used:
* https://codesandbox.io/s/vanilla-vanilla
* https://codesandbox.io/s/express-example-starter-ilobh
