### ISSUE TITLE
VAOS Switch Virtus to Dry-Types

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#3546]
Virtus for types coercion is mostly deprecated. We should switch to using dry-types instead. Don't have time to grok this right now, but should tackle shortly after MVP launch.

**Comment by saneshark** [comment]
I think we want to move this to Icebox. No? I don't think we're going to be able to deliver on this one as originally spec'd, might at most be able to do a partial implementation because of some limitations we ran into with dry-rb suite being immutable.

**Comment by lenaecb** [comment]
@saneshark - deliver post MVP or at all? Trying to understand impact of no being able to complete this now or the near term. Thanks!

**Comment by saneshark** [comment]
There might be a way to do it in the future and worth re-evaluating, but it's not a launch blocker and going to be a time sink to investigate.

**Comment by saneshark** [comment]
Closing this because it's not quite as easy as we had thought. Too error prone. Will just get rid of it if we can every get rid of v0
