### ISSUE TITLE
[FE] Reduce swiping/tabbing for screen-readers

### ISSUE THREAD

**Issue by niradatta1** [department-of-veterans-affairs/va.gov-team#35472]
We have the following sentence on a few different pre-check-in and check-in pages: 

"Your appointment is on [date]"

Screen reader testing showed that the user has to swipe / tab many times to get through the sentence. To reduce the number of swipes/tabs for screen-reader users, we can ensure the sentence is split across two lines: 
"Your appointment is on" one line
"[date]" second line

Ensure this is applied across pages in the flow.

**Comment by ytsaoca** [comment]
![Introduction page_Standard_V2](https://user-images.githubusercontent.com/90633685/151191470-c04261f6-a74e-4863
![Confirmation_Ordinary_No Change](https://user-images.githubusercontent.com/90633685/151191527-79551334-1b1c-4e44-84ec-7142065ba92b.jpg)
-9783-84c2ac9fc0f7.jpg)

**Comment by ytsaoca** [comment]
The screen reader read like this: need swiping to move to the next word.
Pages with this formate: 
- Pre-check-in: Introduction page and confirmation apge
- Check-in: Appointment details
![Confirmation_Ordinary_No Change](https://user-images.githubusercontent.com/90633685/151192299-574db629-3a0f-41e2-b471-3bf480f17d2a.jpg)
![Introduction page_Standard_V2](https://user-images.githubusercontent.com/90633685/151192505-a90ac174-1158-404a-8114-f5fdaf2a8f1d.jpg)
