### ISSUE TITLE
[Discovery] HLR Opt Out checkbox location

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3547]
## Problem Statement
A final decision needs to be made regarding where the opt out checkbox and text will be displayed. Currently it is part of the Intro flow; discussions also placed the Opt out to be included in Step 2C where a person would select the contentions and provide additional details for those issues. 

## Goal
_Identify where the Opt out checkbox should be displayed_

## Acceptance Criteria
- [x] _Opt out checkbox location has been agreed upon_
- [x] *If new design is needed,* new design ticket created for this work

**Comment by rileyorr** [comment]
@YanaRoy We decided that the best design solution would be to add a screen for Veterans to select legacy issues that they want to include in the HLR. The check box would be included on the bottom of that page. [The design ticket can be found here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3750).
