### ISSUE TITLE
Adding Jeff Roof to DSVA Slack

### ISSUE THREAD

**Issue by anerbovig** [department-of-veterans-affairs/va.gov-team#35470]
Hello! Please add Jeff Roof (jeff.roof@adhocteam.us) as a full member to DSVA Slack, he is joining Ad Hoc as a Senior Project Manager working with the VA Online Scheduling team.

**Comment by LizCallaghan** [comment]
done!

**Comment by anerbovig** [comment]
Thanks very much, Liz!
