### ISSUE TITLE
Discovery: Improving the form schema creation process

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35474]
## Description
The current process for creating form schemas makes it possible for engineers to easily build schemas that cause bugs and/or are difficult to parse when trying to resolve an issue. We'd like to do some discovery on how the form schema creation process could be improved, making it easier both to build the schemas correctly and to fix problems when they arise.

## Details
Recent examples of issues:
- [Schema from vets-json-schema not being used](https://dsva.slack.com/archives/CBU0KDSB1/p1641927207247500?thread_ts=1641586749.101900&cid=CBU0KDSB1)
- [Difficulty using uncommon pattern](https://dsva.slack.com/archives/CBU0KDSB1/p1641422485346900?thread_ts=1641421690.345400&cid=CBU0KDSB1)

## Acceptance Criteria
- [ ] Generate a list of options for improving the form schema creation process and add as a comment on this ticket
- [ ] Discuss viability of options with team
- [ ] Make tickets for completing work on viable options

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
