### ISSUE TITLE
[FE] Multiple appointments: Optimize multiple appointments page for screenreader

### ISSUE THREAD

**Issue by niradatta1** [department-of-veterans-affairs/va.gov-team#35473]
During screen-reader testing, we found the following issue: 

Use case: When a user has multiple appointments and is late for one on day of check-in

Issue: When the user lands on the page that lists all appointments they can check into, the screen reader doesn't start from the H1. Instead, it seems to start reading the body content appearing in the first appointment card. This may pose more risk if a veteran with multiple appointments is late. The screen reader will first read that they're late. It's possible the veteran may not know that they need to scroll down to check-in for upcoming appointments.  

Recommendation: Ensure expected screen reader behavior on the multiple appointments page, so that it starts reading from the H1.

**Comment by ytsaoca** [comment]
We recommend to start reading H1 for all pages
![1_3_1_Appointment details: Option 1 Multiple Appointments](https://user-images.githubusercontent.com/90633685/151196948-abee19c3-9335-459a-86a3-2b1b1e629c06.jpg)
.

**Comment by niradatta1** [comment]
@brianseek Once the screen reader is behaving as expected (e.g. starts at the H1), we're now recommending that we don't need to provide any extra content to set up expectations that this page lists more than one appointment. We infer that Angela may have gotten confused because her screen reader didn't start at the appropriate part of the page. Hence, she didn't realize she needed to scroll down the page to check-in because she missed the sentence under the H1. That said, we're making a note of this and will see if we can do more testing down the road with screen -reader users. Let us know if you have any questions or concerns on that approach.  Thanks! 'cc @ytsaoca
