### ISSUE TITLE
[FE] My VA - Payment Information: Update display logic for the new section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35483]
## Background
During usability testing/research with veterans, we found that we need to update the logic on how the section appears, depending on the scenario. 
- The "Benefit payments and debts" section should only appear when the user has received payments from VA.  Even if the payment history is old, and may not be receiving payments any longer, we still want to show this section.
- The "Benefit payments and debts" section should not appear when the user has never received payments from VA.

**Note**: This is not the same logic we will use for the actual payment info block itself.  The payment info block itself will remain as: visible with details for payments received in last 30 days, and statement only (You haven't received any payments.. etc) for payments received more than 30 days ago.

### Reference 
- [Front End documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)

## Task
- [ ] Update logic for Benefit payments and debts section
- Only display section to user if **ANY** payments have ever been received by the user
     -  If user has **NEVER** received a payment from VA, we will not display any portion of this section (logic may be revisited in a future iteration)

## Acceptance Criteria
- Only users who have a payment history (have ever received payments from VA) will be able to see the "Benefit payments and debts" section on their logged-in My VA page.

**Comment by andaleliz** [comment]
>The "Benefit payments and debts" section should not appear when the user has never received payments from VA

FYI this might change if we decide to move forward with research recommendations about displaying confirmation that a user has no debt. We may want to update the criteria to say "has never received or made payments to VA"

**Comment by hdjustice** [comment]
Do we know where we can check to see if a user has ever **made payments** to VA?  Is that information available on va.gov?

**Comment by andaleliz** [comment]
>Do we know where we can check to see if a user has ever made payments to VA? Is that information available on va.gov?

I have no idea. Maybe @lihanli or @tmitchellgcio know?

**Comment by andaleliz** [comment]
@lihanli is the payment history team the same as the debt portal team?

**Comment by hdjustice** [comment]
@tmitchellgcio Hi Taylor!  Can you describe the changes you made?  I want to be sure I am looking at this right.

For this ticket, we needed a condition added for when to display the whole Benefit payments and debts section.
1. Display section if user has **ever** received payments from VA (has payment history)
2. Hide section if user has **never** received payments from VA (does not have payment history)

Is this in-line with your understanding?

**Comment by tmitchellgcio** [comment]
Yep exactly how I did it. I have tests written for it as well

**Comment by hdjustice** [comment]
Awesome!  Were there specific users that were used for testing?  I wanted to validate but running into a snag, so i want to be sure I am using the right ones.
Thanks!

**Comment by hdjustice** [comment]
@tmitchellgcio - When I try to validate with a user that has no payment history, the section is still appearing.  When you get some time, can you take a peek?
1. [User #39](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md#test-cases-for-benefit-payments-and-debts) - Has never received payments, however the Bp&d section is still displaying on My VA. 
     - The section should not display for this user
<details>

![image](https://user-images.githubusercontent.com/92328831/152550537-62228c4d-23f7-4727-a9c5-3f15bee82966.png)
![image](https://user-images.githubusercontent.com/92328831/152550603-a4462236-aff3-413f-896a-dc26973fdb0f.png)

</details>

As an aside, would you be able to set up [user #21](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md#test-cases-for-benefit-payments-and-debts) for this feature?  I duplicated a scenario but did not have the right user for it.

**Comment by tmitchellgcio** [comment]
I will look into it and check what's coming back from the api. Maybe something is still coming back when my code expects an empty array

**Comment by tmitchellgcio** [comment]
@hdjustice user 21 is on

**Comment by tmitchellgcio** [comment]
I have a new update that should fix this

**Comment by hdjustice** [comment]
Ok great!! thank you so much for checking this out today.  And for adding user 21!

**Comment by hdjustice** [comment]
Validated with User 39, and the payment section does not appear, as expected (no payment history for this user)
![image](https://user-images.githubusercontent.com/92328831/153066063-ace5d55e-8d1a-4594-95c6-e911e93147ae.png)

**Comment by andaleliz** [comment]
Just curious, what is that stray `0` under the Go to your profile link?

**Comment by hdjustice** [comment]
Not sure, but Taylor is looking into it.  I pinged him after I saw it for this validation.

**Comment by tmitchellgcio** [comment]
I am still working on figuring this out. I think I have seen something similar once before

**Comment by hdjustice** [comment]
I will create a ticket for it.  Thanks for checking it out @tmitchellgcio

**Comment by tmitchellgcio** [comment]
Got a fix coming
