### ISSUE TITLE
[FE] On-site Notifications: Update the URL on the "Manage your VA debt" link

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35485]
## Background
During our usability testing/research with veterans, we found that the URL for 'Manage your VA debt' in the on-site notification (top of the page) needs to be updated so that it directs the user straight into the actual debt page.

### Reference 
- [Front End documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)

## Task
- [ ] Update On-site Notification - Debt notification - URL on link, as described below (screenshot in Details)
     - Within the On-site Notification - Debt notification (top of the page), "Manage your VA debt" link should be **https://www.va.gov/manage-va-debt/your-debt**

<details>

![image](https://user-images.githubusercontent.com/92328831/149207349-9352e889-43c4-45e5-a65e-fc8db174c7c2.png)

</details>

## Acceptance Criteria
- URL on notification will direct users to their debt pages, showing them a list of their debts.

**Comment by tmitchellgcio** [comment]
Ah this is because I need to add it to users. since we separated the flags. I will do that now.

**Comment by tmitchellgcio** [comment]
Should show on user 1 now

**Comment by hdjustice** [comment]
Validated that the URL in the Onsite Notification has been updated.
![image](https://user-images.githubusercontent.com/92328831/151846447-9be7521c-3329-4a76-beea-b749d5088e64.png)
