### ISSUE TITLE
Analytics Bug Report

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#35499]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - [Insert role, team and project]

- Is this a feature request or a bug?

  - [ ] Feature request
  - [x] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new bug:

- Steps to reproduce the issue
  - The Platform website KPI dash is not receiving/displaying data for 1/10-14.
  - Navigated to dash: https://va-gov.domo.com/page/1182586883
  - Filtered by custom date range 1/10-14.
- Test user (if applicable) - n/a
- Expected result
  - At least some traffic data!  Unless... this means that _no one_ hit the Platform website at _all_ last week?
- Observed result
  - Received "No data in filtered range" message.  See screenshot below. 
![Screen Shot 2022-01-18 at 9 48 47 AM](https://user-images.githubusercontent.com/6895034/149971412-24ea4239-e31e-48c4-9ce5-23f41518e707.png)

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

Maybe there isn't a bug.  Maybe there really was no traffic 😅 

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by obrienjulie** [comment]
@lianilychee - Hi Liani, the Platform website KPI dashboard is now up to date. Please let me know if you see any other issues. Thanks.
