### ISSUE TITLE
Request access to BigQuery

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#35490]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics (Already have)
- [ ] Domo (Already have)
- [X] (Platform Teams only) BigQuery
I also need access to this page in Domo: https://va-gov.domo.com/datasources/f802aec9-6533-4abc-b0b4-989b7317fc8f/details/overview

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Hey @pdavies88 - what BQ datasets and type of access (read vs write) do you need? 

> I also need access to this page in Domo: https://va-gov.domo.com/datasources/f802aec9-6533-4abc-b0b4-989b7317fc8f/details/overview

As in the ability to change this dashboard and its datasets?

**Comment by pdavies88** [comment]
@bsmartin-ep I am looking to gain the same access as @bkjohnson and @k80bowman.
I believe that is `write-access` for the Design System Component Usage dataset and the ability to change that dashboard and its datasets

**Comment by bsmartin-ep** [comment]
Dataset admin access given to @pdavies88.  Domo role promoted to Editor.  Read service key keybased.

Let me know if you need anything else.

**Comment by pdavies88** [comment]
@bsmartin-ep I was trying to run a BigQuery report and got the following error:
<img width="1387" alt="Screen Shot 2022-02-04 at 4 14 15 PM" src="https://user-images.githubusercontent.com/11822533/152604045-6456c9a4-872e-4663-93f7-bcc3588145ad.png">
<img width="771" alt="Screen Shot 2022-02-04 at 4 08 47 PM" src="https://user-images.githubusercontent.com/11822533/152604056-8982d9c9-a6d6-4b26-9760-516f602d8836.png">

I was hoping you'd be able to help me gain access to the save permissions as @k80bowman and @bkjohnson to be able to run reports in this enviornment.

Thanks!

**Comment by bsmartin-ep** [comment]
Please give it another attempt @pdavies88.

**Comment by pdavies88** [comment]
@bsmartin-ep thank you no longer seeing that issue. I appreciate the help
