### ISSUE TITLE
Update 'telehealth' appointment type to 'VA Video Connect'

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3549]
'Telehealth' option should read 'VA Video Connect' so that veterans can more easily understand how the appointment is administered.

AC
- [ ] 'How would you like to be seen' page has option for 'VA Video Connect'

**Comment by narin** [comment]
Bundled with other content update ticket in PR https://github.com/department-of-veterans-affairs/vets-website/pull/11158
