### ISSUE TITLE
Disability Calculator - Conduct 508 audit

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#355]
[This ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18214) will launch a disability calculator to `/disability/about-disability-ratings/`. Currently, the tool is on Staging at https://staging.va.gov/disability/about-disability-ratings-beta/.

Once the tool is more polished, we should conduct a 508 audit to ensure that the tool meets any accessibility concerns, such as tab index, keyboard focus, handling special keys, etc.

**Comment by 1Copenut** [comment]
@jenniferlee-dsva && @Karak888 I've finished the audit of the disability calculator beta. It was pretty quick as a one-page application. Very cool design and user flow!

This link will show you the 5 issue tickets I wrote: https://github.com/department-of-veterans-affairs/va.gov-team/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+author%3A1Copenut+Disability+Calculator

Four are 508 specific, one is an IE11 bug.

I'll move the ticket into Validate, and defer to you for closing when ready.

**Comment by 1Copenut** [comment]
* Users
* Use cases
* Where does code live
* API involved?
  * Lots of sub-questions
* Finding out in-depth, about the product, what teams are brining onboard
  * Designs, where are these at?
  * Where are they at with 508
  * What do teams have now?
  * What do teams intend to do going forward
* Discover what we can, and discussing strategy
* Plan implementation around what we've found on day three
