### ISSUE TITLE
Error Message Index available in error message directory

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35506]
## Issue Description
_Sitewide content team is iterating on "error message directory" and needs PW team to do a search for all the error messages used sitewide on VA.gov._

- [Link to Slack Thread](https://dsva.slack.com/archives/C5AGLBNRK/p1641578983014200)

## Frontend tasks

- [x] Search for all available error messages used on VA.gov
- [x] Compile an "index" of all available error messages used on various apps on VA.gov and provide to Sitewide content team 
- [x] Ensure AC is meet and close ticket 

## Acceptance Criteria
- [x] List of available and used error messages are provided to Sitewide content team 
- [x] Claims team validates react app component is working as desired

**Comment by RLHecht** [comment]
For sure @brianalloyd We currently have an [error message dictionary](https://design.va.gov/patterns/messaging-dictionary) in the design system to lists all the error messages products use. For example, what a user sees when they do something in a tool that doesn't work.  We are pretty sure there are error messages being used across different tools that aren't saved in this dictionary though. So we want to do an audit of all the ones that teams are using, make sure we are consistent with the ones being used and eventually update the dictionary to include all the error messages. Does that help? Happy to provide you with more info if you need.

**Comment by brianalloyd** [comment]
@RLHecht closing this out in support.  Please let us know if you need anything else.
