### ISSUE TITLE
Remove homepage refresh toggle

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35524]
## Item Description
The homepage refresh changes are live and in sustainment. The non-refresh code was removed in #27665 so we need to remove the flipper control in the admin.

## Tasks
- Remove FE `va_online_scheduling_homepage_refresh` toggle
- Remove BE `va_online_scheduling_homepage_refresh` toggle

## Acceptance Criteria
- Functionality remains the same as when the toggle is `true`
- Flipper no longer appears in the admin UI

## Definition of Done
- All tasks are complete
- All acceptance criteria are met

**Comment by ldelacosta** [comment]
Jennie - moved this ticket to In Progress. Let me know if you are not working on the ticket and I'll put it back in Ready. Thanks!
