### ISSUE TITLE
"Use my location" option overlaps the search field

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#35533]
## What happened?
On "search by location" tab, we see the "Use my location" option overlapping the search field. This is happening in both: staging and production. Screenshot below: 
<img width="1090" alt="Screen Shot 2022-01-18 at 3 20 29 PM" src="https://user-images.githubusercontent.com/86266024/150016610-c19ca25c-65b8-4bfb-a1c3-679c18236541.png">

## Desired behavior
- The "Use my location" option should not overlap the search field (Should be moved a little form the search field.)

## Acceptance Criteria
- [ ] - The "Use my location" option should not overlap the search field (Should be moved a little form the search field.)

**Comment by hallihocine** [comment]
Ticket has been validated in staging: issue was fixed and now the "Use my location" link is not overlapping the search field. See screenshot: 
<img width="1159" alt="Screen Shot 2022-01-19 at 1 46 40 PM" src="https://user-images.githubusercontent.com/86266024/150196667-1eb0054f-971b-4524-978f-b0e04343339b.png">

**Comment by hallihocine** [comment]
- Test Run in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2842&group_by=cases:section_id&group_order=asc&group_id=3384
- Test Script/steps: 
["Use my location" option overlaps the search field.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7899930/Use.my.location.option.overlaps.the.search.field.xlsx)

**Comment by af-manish** [comment]
The two scripts that ran are:

 lib/tasks/fix_coord_mismatch.rake      
 lib/tasks/fix_phys_country_coord.rake

They are checked in github here: https://github.com/department-of-veterans-affairs/gibct-data-service/tree/master/lib/tasks

**Comment by mrblanco1** [comment]
Conducted UAT Demo to EDU on 1/20/2022 - Passed and approved by Joe P.
