### ISSUE TITLE
Adding Bernard King to DSVA Slack

### ISSUE THREAD

**Issue by hbomb88** [department-of-veterans-affairs/va.gov-team#35531]
DSVA Slack Request

Please add Bernard.King@va.gov as a full member to #appeals with access to the following channels:

, #appeals-announcements, #appeals-batteam, #appeals-data-workgroup, #appeals-devops, # appeals-devops-alerts, #appeals-intake-alerts, #appeals-job-alerts, #appeals-swat, #appeals-training, #general, #random, # vfs-all-teams, #vfs-platform-support

Bernard King is newly onboarded to Booz Allen Hamilton's Appeals product line in Application Support role and needs to be able to respond to the requests/alerts, especially those for the BAT team that come in via Slack.

@LEHigley @LizCallaghan @KevinMHoffmanUSDS

**Comment by LEHigley** [comment]
done

**Comment by hbomb88** [comment]
I'm so sorry, I was given bad info - we need to change the e-mail that Bernard uses for access from this VA address to his contractor address (King_Bernard@ne.bah.com).  Do I need to submit  new issue?

**Comment by LizCallaghan** [comment]
just invited him
