### ISSUE TITLE
Create v2 of Facility Locator wireframe

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3553]
**As a Veteran, I need to quickly and accurately search for facilities with urgent care or emergency services available nearby so that I can address my medical needs.**

**Task:**
Continue work from [#3054] to create v2 of the Facility Locator wireframe, incorporating feedback received from team review. 

**Goal:**
Continue redesigning the experience for Veterans searching for an urgent/emergency care facility.

**Acceptance criteria**
Incorporate community and urgent care research, Facility Locator discovery research and feedback into iteration. 
A second draft wireframe for incorporating Urgent Care into FL tool
Design Review

**Comment by mmiddaugh** [comment]
@davidconlon @arickalewis1 not sure where to put this but also don't want to lose track of it. 

Dave M mentioned that "drive time" (rather than mileage) is available for VHA but not for VBA or NCA (and guessing not for Community Care). 

We heard user feedback about how important this is but I don't know how to handle it if the data is different for non-VHA....

**Comment by arickalewis1** [comment]
[FL-downloadPDF-UrgentCare-UserFlow (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3917342/FL-downloadPDF-UrgentCare-UserFlow.1.pdf)


I sent this flow to Ryan as we work on the prototype that will accompany the Urgent Care usability study.

**Comment by mmiddaugh** [comment]
@arickalewis1 can we close this?

**Comment by arickalewis1** [comment]
> @arickalewis1 can we close this?

Yep!
