### ISSUE TITLE
Post-auth validation in Keycloak with live data 

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35534]
Add a post-auth flow to keycloak instance that validates users with whitelisted data, instead of test data. 
Testing with:
 - real people (more than 4 test accounts)
 - real database
 - external database

[whitelist for SOCKS proxy](https://github.com/department-of-veterans-affairs/devops/tree/60b9c9410d45ea951d3d26da28778d8f97591b49/ansible/roles/dsva-config/files/authorized_keys)

**Write a plugin** 
to keycloak that grabs the whitelist or stores it somewhere (a simple database from the whitelist) 
Check after authentication if an email matches an email in the database.
 - if yes, continue
 - if no, we show a generic error "login failed"

**Deploy plugin**
Discovery has been done by Carl (ticket?)
DevOps work needs to be done to pull from the correct repo when updates are made. 

Note:
 - we cannot create a user if email doesn't match whitelist. 
 - can we use information in the user info endpoint to grab the email? would need to grab the token etc
 - do a PR for this

Travel Analogy:
Have a passport, only get past customs if you're whitelisted

**Comment by calquisola** [comment]
Post validation plugin was deployed in dev cluster. 

pipeline was created by Demian.

Notes:
1.  User will still be created on first login but will not be authenticated if they are not on the whitelist. 
2. Email will be taken from keycloak's users table not the userinfo endpoint.
