### ISSUE TITLE
Adding Mariette Tchinkou to DSVA Slack

### ISSUE THREAD

**Issue by hbomb88** [department-of-veterans-affairs/va.gov-team#35530]
DSVA Slack Request

 Please add tchinkou_mariette@ne.bah.com as a full member to #appeals with access to the following channels:

, #appeals-announcements, #appeals-batteam, #appeals-data-workgroup, #appeals-devops, # appeals-devops-alerts, #appeals-intake-alerts, #appeals-job-alerts, #appeals-swat, #appeals-training, #general, #random, # vfs-all-teams, #vfs-platform-support

Mariette Tchinkou is newly onboarded to Booz Allen Hamilton's Appeals product line as a Database Admin and needs to be able to respond to the requests/alerts that come in via Slack.

@LEHigley @LizCallaghan @KevinMHoffmanUSDS

**Comment by LEHigley** [comment]
done

**Comment by LEHigley** [comment]
sent invite to email above and got a bounce back

**Comment by hbomb88** [comment]
Thank you for the notification.  Mariette provided me with her VA e-mail address, I will ask her to confirm the correct address.

**Comment by hbomb88** [comment]
Please use tchinkou_mariette@ne.bah.com, requested above amended
