### ISSUE TITLE
Research plan to test new Facility Locator workflow

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3554]
**As a Veteran, I need to quickly and accurately search for facilities with urgent care or emergency services available nearby so that I can address my medical needs**

**Background:**
Wireframes for redesign of Facility Locator workflow are captured in [#3054] and [#3553] 

**Acceptance Criteria**
- Completed research plan to seek user feedback on redesigned Facility Locator workflow

**Comment by arickalewis1** [comment]
Research Plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care/research-plan.md

**Comment by mmiddaugh** [comment]
Waiting for prototype to be finished but otherwise complete.

**Comment by mmiddaugh** [comment]
Discussion Guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care/discussion-guide.md
