### ISSUE TITLE
VSO/accredited rep tool landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35546]
## Issue Description

This is the epic for all the work involved in creating the root-level page for the VSO/accredited rep tool landing page.

**Comment by mnorthuis** [comment]
Added the IA issue to this epic for reference.    Please note there is a redirect that is needed to retire and redirect the old page to the new.  That redirect request has not been created.

**Comment by RLHecht** [comment]
Old epic. Closing.
