### ISSUE TITLE
[Spike] Cerner site list in VAOS

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35547]
## Background/Request
In anticipation of the next Cerner site going live, we would like to understand what work in the code, if any, is necessary for the FE to acknowledge there's another Cerner site.

Previous tickets related to Cerner site launches #6639, #6964

Related [conversation in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1642186217226900)

[Cerner Go Live task list](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/16fd6afe93b749555b4f48a98342dad1c8dcbe53/teams/vsa/teams/public-websites/cerner.md) 

List of [Cerner Sites](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/cerner/index.js#L5)

Note- Spokane implementation is a closer use case for upcoming launches (e.g. Walla Walla). Columbus was a unique implementation, but should be reviewed.

---

## Tasks
- Answer the following questions:
  - Are we maintaining any lists that must be updated with every new Cerner site?
  - How are we using the `isCerner` flag?

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by simiadebowale** [comment]
The CMS team is going to be working on making that cerner file (found in src/platform/utilities/cerner/index.js in vets-website) more dynamic and not hardcoded. On our end, we use a selector that checks the Ids on that file. We don't need any additional efforts on our end. We won't need to be updating that file manually anymore.

**Comment by ldelacosta** [comment]
This ticket is no longer needed.

cc: @JRRoof
