### ISSUE TITLE
Platform Orientation Template [Jeff Roof]

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#35548]
## Welcome and Introduction
Welcome to the Veteran's Administration (VA) Veteran Facing Services (VFS) team! 
As a new VFS team member, you will be working in the web ecosystem we call the VA.gov Platform (or "**The Platform,**" for short).  The tasks on this list are designed to get you up to speed on the role of Platform, making it easier for you to do your job.

Because the VA is a huge organization that serves millions, the Platform it runs on is equally big, complex and multilayered. Most people find that even learning the basics for their own practice area entails a significant learning curve.  The tasks on this checklist will help you acquire those basics as quickly and efficiently as possible. 

## User Story
As a new VFS team member, I need to complete onboarding activities so I can successfully work on my project and support the VA.gov Platform.

## How to fill out this ticket
- [ ] Add your github handle as the Assignee
- [ ] Add your teams github label under Labels
- [ ] Add your name to the ticket title
- [ ] Complete the Onboarding Checklist below
- [ ] Under **Get set up for your practice area,** you only need to complete the items for your role
- [ ] You can close this ticket when all items are completed in the Onboarding Checklist and the Platform Checklist

### Share your info with Platform
- [ ] Complete the fields below:
 - Name:
 - Preferred pronouns (e.g. she/her):
 - Role:
 - Email:
 - Github handle:
 - Start date:
 - VFS Team:

### General

- [ ] Attend General Orientation meeting ([schedule via Calendly](https://calendly.com/collaboration-cycle/general-orientation-for-va-gov-platform?month=2021-11))
- [ ] Watch [VA.gov overview video](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Gettingstarted)
- [ ] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack) with Program, Team, Role and Company
- [ ] Review [Welcome](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html) documentation
- [ ] Review [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html) documentation
- [ ] [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
### Norms and standards
- [ ] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [ ] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [ ] Review [Orientation materials](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) on Platform Website
- [ ] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [ ] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
### Working on the platform
- [ ] Review the [Platform Principles](https://vfs.atlassian.net/wiki/spaces/AP/pages/1391853669/Platform+Crew+Principles)
- [ ] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [ ] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/digitalmodernizationstrategy.pdf)
- [ ] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/the-new-va.gov-briefing-2019-07.pdf) documentation
- [ ] Review the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) documentation on Platform Website
- [ ] Review the [Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809)

#### Designers & Researchers
- [ ] Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] Review the [VA.gov Design System](https://design.va.gov/)
- [ ] Review the [Research and Design Guide](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) on Platform Website
- [ ] Request design orientation with @ Allison Christman in Slack
- [ ] Request 508 intro with @ Noah Gelman in Slack

#### Front-end Engineers
- [ ] Review [frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [ ] Request Front-end orientation with @ Megan Kelley in Slack
- [ ] Request analytics intro with @ Michelle Dooley in Slack
- [ ] Request 508 intro with @ Noah Gelman in Slack
- [ ] Request QA intro with @ Peter Hill in Slack

#### Back-end Engineers
- [ ] Review [backend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Backend-developer-documentation.1886289964.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [ ] Request Back-end orientation with @ Nate Peterson in Slack
- [ ] Request QA intro with @ Peter Hill in Slack

#### Product Managers
- [ ] Request PM intro with @ Shira Goodman in Slack
- [ ] Request analytics intro with @ Michelle Dooley in Slack
- [ ] Request 508 intro with @ Noah Gelman in Slack
- [ ] Request QA intro with @ Peter Hill in Slack

### Off-boarding of teammates
- [ ] Review [process for when a teammate leaves](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/contractoroffboarding.md)

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [ ] New VFS Team member has been added to the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)

CC: @department-of-veterans-affairs/vsp-product-support

**Comment by shiragoodman** [comment]
@JRRoof please be sure to complete this ticket. thanks.

**Comment by JRRoof** [comment]
Duplicate template

**Comment by shiragoodman** [comment]
@JRRoof can you please share the link of the correct template?

**Comment by JRRoof** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35525
