### ISSUE TITLE
Deploy test app to same URL in subpaths

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35556]
**Notes**
In kubernetes -

- Have a cluster and inside that are pods. 
- a pod can have more than one container
- pod can run multiple apps
- each of those can have a different url

define an ingress to ports and that will allow access to multiple URLs
don't need to do a separate manifest and application in argo, just a pod with all of them in it
need to add them to the manifest

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app/pull/4
https://github.com/department-of-veterans-affairs/pst-amt-keycloak-node-test-app/pull/2
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/289

**Comment by kjduensing** [comment]
Not worth doing for now
