### ISSUE TITLE
Conduct Usability Study (Part 2)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3555]
## Story
As a member of the eBenefits Design Team, I need a usability study regarding the tools page implementation so that I can validate that the new components on the tools page are an effective choice for conveying disability ratings.

## Tasks
- Using the approved research plan and conversation guides, conduct several usability sessions that validate work done on for both Rated Disabilities and Dependents
- Seek information about how to make informed design decisions on Rated Disabilities and View Dependents

## Acceptance Criteria
- [x] Conduct about 8 usability studies (total 15), with notes [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/session-notes) for later synthesis

`this ticket will be split since studies will straddle the beginning and end of the sprint`

**Comment by sporeboy** [comment]
All sessions complete. Recordings and notes available for all attended sessions. Notes are here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/session-notes
