### ISSUE TITLE
Adding Keya Sengupta to DSVA Slack

### ISSUE THREAD

**Issue by zinalpatel09** [department-of-veterans-affairs/va.gov-team#35551]
This request is to add Keya Sengupta (keya.sengupta@thoughtworks.com) as a Full member

Description: Keya Sengupta is a Developer on the Long Covid project. In order to do his job efficiently, he needs slack to help him keep up to date on any communication and activities for the project.

Please also add Shibu to these Channels:

#health-care-products-all-teams
#long-covid-public
#long-covid-team

**Comment by LizCallaghan** [comment]
done!
