### ISSUE TITLE
Configure keycloak in utility VPC

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35557]

**Comment by dginther** [comment]
Keycloak is configured to use Login.gov as an IdP. Successful login to the console and user was created:
![Screen Shot 2022-02-14 at 10.39.47 AM.png](https://images.zenhubusercontent.com/5ce30eebaa8711267b95ebdf/642361bd-fedf-4ad9-8ef8-d66d80af7e59)
