### ISSUE TITLE
paragraph tags in CSS not separating lines in Vet Center accordions

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-team#35553]
## What happened?
In Vet Center content type, Prepare for your visit accordions panel, in Parking field, paragraph tags are formatted correctly between lines in the CMS, but the live page appears to ignore the paragraph tags.

## Specs:
- Device: Mac
- Browser: Chrome
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://staging.cms.va.gov/section/vha/vet-centers/escanaba-vet-center
- Test User _(if applicable)_:

1. From the Vet Center dashboard, find the Main Vet Center card and click Edit.
2. Scroll down to the Prepare for your visit accordions, then click Edit next to Parking. 
3. Check the formatting of the paragraphs.
4. Scroll down and unlock the node.
5. Scroll up and click the Preview button.
6. Scroll down the single page preview page to Prepare for your Visit and expand Parking to see the error.

## Desired behavior
The accordion should show the paragraphs properly formatted on separate lines.

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by kevwalsh** [comment]
FWIW, I was able to reproduce fix this in my browser by hacking the shadow root. 

<details><summary>Screenshot</summary>


![image](https://user-images.githubusercontent.com/643678/150153373-f0347e12-7e83-45c0-a480-15b5b8ab8e1e.png)


</details>

**Comment by xiongjaneg** [comment]
[Slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1642544274006800) for more info
