### ISSUE TITLE
Make Login.gov Go To Prod checklist

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35567]
**Background**
login.gov requires some steps to go to production, not using sandbox. 

We need these steps clearly outlined so we can gauge where we are in the process - this is specifically for making the checklist, not completing items on it. 

**Task is done when**
we have a confluence document that outlines the list of tasks in login.gov documentation

**Comment by kjduensing** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2085027848/Login.gov+Prod+Deployment
