### ISSUE TITLE
Documentation: Custom app integration process

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35569]
**task is done when**
We have a document in confluence that outlines two ways to integrate with access management process

**Comment by calquisola** [comment]
We cover the custom integration process here:
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2095939604/Incorporating+authentication

**Comment by ken-non** [comment]
@kylesoskin to add paragraph on ruby

**Comment by kylesoskin** [comment]
> @kylesoskin to add paragraph on ruby

I think we decided after making this comment, that we don't need a rails specific paragraph outlined here. 

We CAN however probably put some examples (in ruby, javascript, curl, etc, etc) in the 
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2095939604/Incorporating+authentication#Using-an-HTTP-library-(OIDC)
section
