### ISSUE TITLE
Access for Mark Viterna

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#35564]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Mark Viterna

### Your Email

mark.viterna@libertyits.com

### Name of Your Team

Matsumoto

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCVUcDdIuE/tETb3USVZxzARQVXx5s41xHQOk+7PAgyM7K30pOONhCQezdniUcvgJDpTv9jf7ysTsccH4dKP9uMqYLr69kc1AM1BlrYrfSJaM+qKoqg9pam7GyuI1aFnMiSwxA0wpTFWM9nWXr6lM8J5h3WSVO1U15syEANMuZZGcvDlWGhk1veRxaK+nF3iHDw+WypKiPGPi1WAQ4LfbotBL5c9xVamL6ySe3rtU6/d6NlG9IaslhLcsSdwpFPTJZONu6iPxsARGcU/7gg+KI9Qw1FQ0HIErGHEiX/nXiAOhXaEK5pMEsa22KkWP06BSXQpZEcsI2zEz9SfNL6d9trbns92S5m/8hwWVpZDqKFAteT9R0l8vopwmgG0i9kW8H7QLTGs/lfOUkLnOyRNeQS12Tz1J3fSh9sUlu3rEqntjxgbuVoJ/xHPXvxiJ5RNotOu6IL5O8csdbB8CV4B2g9I+nDCnpJWmQ+TZ5kqRYTflgCLGpfsBcvCyaCNPlst6E= osboxes@osboxes

### Desired AWS Services

Same access as Cris Shupp. Includes CloudWatch,S3, ECS etc

**Comment by jsgarmon** [comment]
@mviterna : you already have AWS access with the same access as Cris Shupp. Are you having issues accessing something?

**Comment by mviterna** [comment]
@jsgarmon My HDD failed on my PC, taking my working key with it. Good to hear on the AWS, I wasn't sure if it was somehow tied to the same socks key or not.

**Comment by mviterna** [comment]
So yes, we need to update it with the new one I just generated

**Comment by jsgarmon** [comment]
Key has been updated. Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
