### ISSUE TITLE
Review/QA Std KPD Dash metrics vs VA.gov All Dash metrics 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#35576]
## Issue Description
Review the how metrics are defined and their data sources and how they may differ in Std KPI Dashboards vs. VA.gov All dashboard.  Standardize any differences so they both provide the same results and if they cannot provide more detail to the differences so it is clear when a team is comparing their dashboard to the VA.gov All dashboard why metrics may vary.

---
## Tasks
- [x] Compare metrics and identify where they do not match 

## Acceptance Criteria
- [x] We have reviewed all the metrics and standardized them across and/or provided more details as to why they are different.

**Comment by chloedotbrown** [comment]
Hello! I put together a [very quick test page](https://va-gov.domo.com/page/935341439) showing 2021 submission totals from the Standardized Forms and All VA datasources. Turns out that only 10-10EZ and 526-EZ are currently shown on both. Each table shows both unique and total events for each form, with the version currently shown on the dashboard highlighted in blue and called out in the header. 

I believe the discrepancy is coming not just from the difference in metric calculation by unique vs. total, but also from which exact "events" we are looking at. All the steps for both these forms are defined by page hits on specific URLs, but in the All VA data, we're counting `--submission-successful` hit events instead.

@obrienjulie and @bsmartin-ep, what do you think?

**Comment by michelle-dooley** [comment]
Hey...@chloedotbrown @obrienjulie @bsmartin-ep.  So I would like the way we define these events to be the same for standard and all VA dashboards.  Which way of calculating is more accurate/better representation of what we are trying to show/track?  @bsmartin-ep does one way correspond closer to the metrics we will get from GA4?  I feel like changing the std dashboard will cause more disruption b/c people are already using those but with that said if we feel the all va version is the better way to define then we should do that.  Thoughts?

**Comment by bsmartin-ep** [comment]
@chloedotbrown / @obrienjulie / @michelle-dooley -

I think I sorted out the discrepancy.

1. This [form events dataset](https://va-gov.domo.com/datasources/7c6bed43-1daa-43bb-bfcf-e44fd6b78958/details/history) was missing a day and needed to be backfilled.
2. The above dataset is counting any event with a `^Form -` event action on **any page on the site**.  Our standardized queries are restricted to only pulling events we have in our `forms` lookup table.  When I restrict the above dataset to just those pages (using a similar INNER JOIN), the numbers line up...

![image](https://user-images.githubusercontent.com/62304138/151472214-be1dda76-d826-423a-9aaf-5da18195151e.png)

Here is a [GA report where you can see all the different URLs](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20210101&_u.date01=20211231&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=disability-526EZ--submission-successful&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22disability-526EZ--submission-successful%22,0%5D%5D/) with the successful submission event.

Now why is this happening?  Good question.  Maybe a bug with app routing where the URL isn't changing correctly?  Or something weird with the save-in-progress functionality?

**Comment by bsmartin-ep** [comment]
Also, the beast modes counting `--submission-successful` events were also counting the `survey--submission-successful` events, so I filtered the survey events out.

**Comment by chloedotbrown** [comment]
Thank you @bsmartin-ep for solving this mystery!!

**Comment by michelle-dooley** [comment]
Going to schedule a meeting to discuss:  
Is all the data validation complete/updated
What metric will we use - unique or total?  Why and how to present out.

**Comment by michelle-dooley** [comment]
The metrics have been validated.  The standardized forms dashboard metrics have been updated to total submissions instead of unique submissions per session which is a more accurate representation of form submission rates and matches what is displayed in the All VA.gov dashboard for metric standardization.
