### ISSUE TITLE
Seeded data for local keycloak testing

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35570]
We need testing for other developers integrating with our access management solution to be simple. 

By adding a preconfigured instance of keycloak to the example repo, we can make integration testing easier for other teams.

This points to a larger issue - we need an examples repo but that is not covered in this ticket.

- [x] Update the docker compose file
- [x] Run keycloak image with preset configuration

**Task is done when**
The repo can be downloaded and run and test data is loaded automatically

**Comment by ken-non** [comment]
Blocker - need to chat with platform ops team to get access to tables.  #35852
code is semi ready
need to use newer version of sdk

**Comment by calquisola** [comment]
template is ready. https://github.com/department-of-veterans-affairs/pst-amt-keycloak-local

We  just need to add the Realm with the roles, groups and permissions.
