### ISSUE TITLE
Fix TUD SSL & Redirect HTTP To HTTPS

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#35571]
The SSL certificate for TUD is not valid and needs to be updated:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/e1a6357b-2b90-438b-a412-589b353ef3c6)

Additionally, `http` requests need to redirect to `https`.

Done:
- [ ] SSL cert has been updated
- [ ] `http` requests redirect to `https`.

**Comment by rbeckwith-oddball** [comment]
Occurring in `dsva-vagov-utility-cluster`
