### ISSUE TITLE
Adding Dale Durham to DSVA Slack

### ISSUE THREAD

**Issue by eslagle** [department-of-veterans-affairs/va.gov-team#35572]
The following individual [ddurham@flexion.us] needs be added as a full member to [#lcs-dev, #cpm-alerts]

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
already a member
