### ISSUE TITLE
Add Grafana Presentation Link to BE Tools Documentation 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#3558]
## User Story or Problem Statement
As a VSP Engineer, any information on how to use our tools is material that should be documented. This presentation is a great visual resource for existing VSP developers as well as a resource for onboarding new developers in relation to Grafana:

https://zoom.us/recording/play/5_P-TvNi6qdk0eyOHUU-oISTBlTN82XjUCipr2hfMRit48p_2s1ySexBBHNpq98W?continueMode=true

## Acceptance Criteria
A link is placed within new or existing documentation related to Grafana.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
@thilton-oddball any thoughts on adding this to our current Grafana docs?

**Comment by thilton-oddball** [comment]
I think it would be great to add in. I'll figure out where it would best fit in and get it in there.

**Comment by LindseySaari** [comment]
Thanks @thilton-oddball! Feel free to close the ticket when this is complete
