### ISSUE TITLE
URL Shortener - Create S3 Bucket 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35586]
## Description 
When a veteran visits a shortened URL such as https://www.va.gov/c/abcdef, the VA.gov reverse proxy forwards the request to the web-hosting enabled S3 bucket with the same object identifier. 

This story is to create the bucket with the proper configuration. 

Link to [design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md)

## A/C
- [ ] Bucket is created in each environment 
- [ ] Bucket is accessible by rev proxy servers
- [ ] Website hosting in enabled 
- [ ] Bucket is not publicly accessible 
- [ ] Bucket allows the shortener lambda to list & create objects

**Comment by acrollet** [comment]
This ticket is currently blocked on obtaining expanded permissions for the CHIP AWS infrastructure deployment. ([Ticket](https://wfm.vaec.va.gov/servicedesk/customer/portal/2/VAEC-22187) has been submitted to VAEC support)

**Comment by acrollet** [comment]
@jparker0425 NB I added an A/C but I don't think it affects the estimate.

**Comment by acrollet** [comment]
Sample bucket policy to allow lambda IAM user access:

```json
{
  "Id": "Policy1643132964684",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1643131977854",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:PutObjectLegalHold",
        "s3:PutObjectRetention"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws-us-gov:s3:::chip-url-shortener-expiration-test/*",
      "Principal": {
        "AWS": [
          "<ARN for IAM user>"
        ]
      }
    },
    {
      "Sid": "Stmt1643132959739",
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws-us-gov:s3:::chip-url-shortener-expiration-test",
      "Principal": {
        "AWS": [
          "<ARN for IAM user>"
        ]
      }
    }
  ]
}
```

**Comment by acrollet** [comment]
Closing as we made the [decision to go with DynamoDB instead of S3](https://dsva.slack.com/archives/C02G6AB3ZRS/p1643649142159969?thread_ts=1643647614.222829&cid=C02G6AB3ZRS).
