### ISSUE TITLE
URL Shortener - API to create shortened URL 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35590]
## Description 
Shortened URLs are created by invoking a Lambda function via API gateway with the URL to be shortened as the main parameter. The Lambda function generates a short unique identifier and creates an S3 object with a redirect to the provided URL. Finally, the Lambda function returns the shortened URL (e.g. https://www.va.gov/c/abcdef) to the API consumer.

## A/C
- [x] Request and Response match what is in the [design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md)
- [x] API endpoint is accessible by VeText and AWS initiate check-in lambda
- [x] Logs are generated according to [Logging section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md#logging) design doc
- [x] Request to shortened URLs not from staging.va.gov, sandbox.va.gov, dev.va.gov, www.va.gov should be rejected

**Comment by acrollet** [comment]
This is done except for the logging requirements, we can either move back to in progress or split out the logging into a new ticket.

**Comment by sarahknoppA6** [comment]
@acrollet would recommend moving back to in progress since logging is in the acceptance criteria.

**Comment by acrollet** [comment]
[PR created](https://github.com/department-of-veterans-affairs/chip/pull/556) to add logging and verified in dev environment:

![image (21).png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/04cf8b06-9a67-40cb-b3d4-ca2656ca2095)

**Comment by acrollet** [comment]
Logs PR has been merged to the CHIP integration environment.
