### ISSUE TITLE
Compile list of attributes in eauth saml response headers amongst different signed-in credentials

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#35592]
Track the different attributes with inbound and outbound responses and show them in this document:

https://docs.google.com/spreadsheets/u/1/d/1EdBBNUdxPZzhBTnK4nWqfpijmvhRpSFBovId80xTMyE/edit?usp=sharing

Once the google sheets document is filled out, great a Github markdown document and store this in the Identity team folder for permanent documentation

**Comment by codyreinold-usds** [comment]
Can we use Confluence or GH markdown for this?

**Comment by bosawt** [comment]
@codyreinold-usds Yes, the plan is to put this in Github after the google sheets is filled. I'll specify in the story description though

**Comment by bosawt** [comment]
List compiled here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/ssoe/ssoe_saml_response_attributes.md

**Comment by bosawt** [comment]
@codyreinold-usds Some credential combinations are missing but mostly I'd say that currently gives us quite a good idea of what attributes are given for different credentials
