### ISSUE TITLE
URL Shortener - Load Testing of API and End-user Visible Service 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35593]
## Description 
Load testing should be performed at 2X the expected combined usage rate for pre-checkin + check-in in order to ensure that AWS Service Quotas do not need to increased and that no other performance issues are encountered.

## A/C 
- [x] Estimate prod usage for both services and document on [design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md#logging)
- [x] Load test API on dev infrastructure at 2x max anticipated usage rate 
- [x] Load test FE service (when user clicks new shortened link) on dev infrastructure at 2x max anticipated usage rate
~- [ ] Check generated S3 objects to ensure no objects have more than 1 version (which would indicate that a duplicate key was generated)~
- [x] @Hortonio has been notified of this outcome for CHIP team production planning

**Comment by acrollet** [comment]
Per @shanemelliott in https://dsva.slack.com/archives/C02G6AB3ZRS/p1643646228032369?thread_ts=1643389576.932609&cid=C02G6AB3ZRS, max throughput for VEText is 500 messages per second.

**Comment by acrollet** [comment]
Added a/c to keep @hortonio in the loop

**Comment by acrollet** [comment]
Load testing has been completed, report is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/performance_testing_report.md

**Comment by stephenBarrs** [comment]
This load testing report looks complete to me and demonstrates that this URL shortener should operate under expected loads.

**Comment by brianseek** [comment]
Report looks good to me too. Very well put together and nice work @acrollet !
