### ISSUE TITLE
URL Shortener - Delete Expired Shortened URLs

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35591]
## Description
In order to limit object hosting costs and avoid storing irrelevant short URLs, short Urls should be removed once they are no longer necessary.

[Design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md#logging)

## A/C
- [ ] Short urls are automatically removed on or after expiration time

**Comment by acrollet** [comment]
Updated to remove implementation details.

**Comment by acrollet** [comment]
This has been implemented using the DynamoDB TTL feature.
