### ISSUE TITLE
Figure out how to keep staging/dev content deploys from interfering with the auto deploy job

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#356]
## User Story
In Drupal you can trigger a staging/dev deploy, which does a content only build for either staging or dev, then deploys those changes. This entails fetching the build tarball for the most recent master commit. If there's an in progress build, then that tarball doesn't exist yet, and the content only build fails.

This isn't necessarily the worst outcome, except that failed content only deploys look like failed vets-website master builds and will cause problems with the auto-deploy if they're the most recent master build. Even though we probably have releasable code.

## Goal
When staging/dev builds are triggered, their failures don't stop a prod deploy

## Acceptance Criteria
- [ ] When staging/dev builds are triggered, their failures don't stop a prod deploy

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@tskinn Can this be closed?

**Comment by ricetj** [comment]
done
