### ISSUE TITLE
[COGNITION]: In mobile view or zoomed to 400%, the repetition of the sidenav accordion label takes up vertical space making it difficult to read the content in context

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#3560]
## Description

**[COGNITION]: In mobile view or zoomed to 400%, the repetition of the sidenav accordion label takes up vertical space making it difficult to read the content in context**

![pittsburgh-sidenav-repeated-labels.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/4aa5d817-a02b-4d29-85af-422925d831f2)

## Point of Contact

Jennifer

## Acceptance Criteria

As a low-vision user, I want to be able to access the website content using my magnification software, settings, or plugins, in order to read the information in context.

## Environment

* Operating System: all
* Browser: all
* Assistive Tech: zoom to 400% in a 1280px wide browser to replicate magnification software/plugins

## Steps to Recreate

1. Enter `https://staging.va.gov/pittsburgh-health-care/` in browser
2. Set browser width to 1280px wide
3. Zoom to 400%
4. Reload the screen
5. Tab, Skip to Content
6. Tab to Locations, press Spacebar or Enter to open the accordion
7. Digest the content within the context shown

## Possible Fixes (optional)

Rather than repeat the label, make clearer what the link will go to. For example, Locations could changed to 'All Area Locations' or moved to the bottom of the list and labeled 'View All Area Locations.'

**Comment by mmiddaugh** [comment]
I will add this criteria to [#3448] as close this as a duplicate.
