### ISSUE TITLE
Adding Bernard King to DSVA Slack (Correct E-mail)

### ISSUE THREAD

**Issue by hbomb88** [department-of-veterans-affairs/va.gov-team#35603]
DSVA Slack Request - amended*

Please add King_Bernard@ne.bah.com as a full member to #appeals with access to the following channels:

, #appeals-announcements, #appeals-batteam, #appeals-data-workgroup, #appeals-devops, # appeals-devops-alerts, #appeals-intake-alerts, #appeals-job-alerts, #appeals-swat, #appeals-training, #general, #random, # vfs-all-teams, #vfs-platform-support

Bernard King is newly onboarded to Booz Allen Hamilton's Appeals product line as a Application Support Analyst  and needs to be able to respond to the requests/alerts that come in via Slack.

*I'm so sorry, I was given bad information on the previous request.  We need to add using contractor e-mail, please feel free to revoke access for Bernard.King@va.gov and let me know if you need anything else. Again, my apologies!

@LEHigley @LizCallaghan @KevinMHoffmanUSDS

**Comment by LEHigley** [comment]
already a member
