### ISSUE TITLE
Analytics Reporting Request for Benefits & Memorials 1

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#3561]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
This is for @kevinstachura on the Benefits and Memorials 1 team. This is a request for a deeper dive into the analytics already provided in ticket [#3142] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3142)
    

## Timeframe for Analytics Requested
_to be completed by the end of the next sprint - Tuesday, Dec 3rd_

## Analytics to Track Down
Analytics for this ticket have already been reported - however, assistance is being requested in better understanding the following metrics provided:

[Please see the Google Analytics report filtered down to basic activity for `/decision-reviews`](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.filter=~2Fdecision-reviews~2Findex.html&explorer-table.plotKeys=%5B%5D/)

>- Pageviews - 22,911
>- Sessions - 13,198 (To measure how many sessions viewed this page, we use the `Unique Pageviews` column. This means there were 13K sessions where this page was viewed at least once).

Nuances:
- There is a parameter called `fbclid` which is a Facebook parameter, so a communications team is likely sending traffic there. We can remove this parameter to make the reports cleaner (and in doing so, we can still see what sources of traffic send activity there using other reports)

[Friction Points: This is the flow report that shows where users are coming from and where they go next (or drop off).](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.filter=~2Fdecision-reviews~2Findex.html&explorer-table.plotKeys=%5B%5D&_r.tabId=navigationsummary&_r.drilldown=analytics.pagePath:~2Fdecision-reviews~2Findex.html&navigationsummary-keySelector.searchTerm=decision-reviews/)

- Of the pageviews coming from a previous page, over 1/3 come from `/disability/file-an-appeal/index.html`
- More then 75% are moving onto another page, with `/disability/file-an-appeal/index.html` as the next page viewed

## Which Product Questions are you trying to answer?
- In order to determine how to best structure the flow to the Decision Review area of the va.gov website, we need to first understand how users are getting there currently and what potential friction points they are experiencing when navigating to (or within) the Decision Review section of the website.

## Additional Comments
@nedierecel already provided the above metrics (thank you!) - just wanted to gain a deeper understanding of them where possible.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@kevinstachura Thanks again for the conversation last week. As a summary, here are additional reports I recommend you review. The reports listed above use the Modernized View. Here are reports that expand on pathing so you can see if legacy pages are also contributors to Decision Review's inbound traffic:

[Decision Review Pathing on All VA.gov Production View](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fdecision-reviews~2F&_r.tabId=navigationsummary)

[Decision Reviews Subdirectory](https://analytics.google.com/analytics/web/?authuser=0#/report/content-drilldown/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePathLevel1:www.va.gov~2F,analytics.pagePathLevel2:~2Fdecision-reviews~2F) - This will allow you to drill into the pages within the `/decision-reviews` subdirectory to understand the top pages. 

I'll shift this to the QA/Review column--please let me know if there are additional items I can provide, or we can close this ticket. Thanks!

**Comment by nedierecel** [comment]
@kevinstachura Thanks again for sharing the deck with me. I'll go ahead and close this issue, and we can open a new one for future work.
