### ISSUE TITLE
[BE]SPIKE - Identify thresholds for check in and pre-check-in (scalability)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#35616]
The intent of this spike is to answer a few questions:

What are the individual parts of the check-in and pre-check-in processes that could break?
How can we test the thresholds for each of those parts?
What is needed to ensure that each. piece in the workflow is able to scale across the VA health system?

Consider starting with a system map?

**Comment by julieadair1** [comment]
## Description
The intent of this spike is to answer a few questions:
1. What are the individual parts of the check-in and pre-check-in processes that could break?
2. How can we test the thresholds for each of those parts?
3. What is needed to ensure that each. piece in the workflow is able to scale across the VA health system?

**Comment by dillo** [comment]
Could we define the criteria for determining scalability of our systems?

**Comment by loripusey** [comment]
Close this one
