### ISSUE TITLE
Metrics showing # of users who moved forward after viewing modal

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35620]
- [ ]  Add track events to how many eligible MHV users dismissed the notification (Notification modal/eligible) [FE]
- [ ]  Add track events to how many eligible MHV users clicked to transition their account to Login.gov (Notification modal/eligible) [FE]
- [ ]  Add track events on how many eligible MHV users clicked the 'Send Data to Login.gov' button (Eligible Login.gov Account Transition page/Consent page) [FE & BE]
- [ ]  Add track events on how many eligible MHV users successfully upgraded their account to Login.gov (Login.gov Successful Creation page) [FE & BE]
- [ ]  Add track events on how many eligible MHV users failed to upgrade their account (AuthApp page with specific error codes & criteria) [FE & BE] *should track in Google Analytics AND Sentry

Google Analytics: 

eligible modal count 
ineligible modal count
Count for number who saw modal
Count for who clicked action

**Comment by asg5704** [comment]
Closing until we have MHVIP go-live date
