### ISSUE TITLE
Sessions controller route when user clicks to verify

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35633]
## Issue Description
---

Occur when an eligible user clicks ‘verify’ on frontend

Returns a redirect for the login.gov verify route

Another context to add to the sessions/*/new route
sessions/logingov_verify/new or something like that

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras @joeniquette This can be deleted/closed
