### ISSUE TITLE
Create a consent page for eligible users

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35630]

**Comment by AGarcia-Clarity** [comment]
@nsoutouras This can be closed in favor of #34945 (as we are combining the consent & information page)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras This can be closed. Duplicate of https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/34945
