### ISSUE TITLE
Request for Research Interviews Regarding User Roles and Permissions in VA ecosystem.

### ISSUE THREAD

**Issue by jchapin** [department-of-veterans-affairs/va.gov-team#35638]
## Description

From Jimmy McConnell, who is conducting research for the @department-of-veterans-affairs/platform-pst-amt and @department-of-veterans-affairs/platform-pst-console-ui teams.

* Research Background/Ask for VSP Infrastructure team:
  * The Access management team is developing a roles/permissions scheme for the VA Developer Console. In order to complete this software development, the Access Management team will be performing an audit of existing tools/products in the VA ecosystem in order to determine list of tools and corresponding roles/permissions schemes currently existing in these tools. In addition to tool audits, Researchers would like to perform a semi-structured interview (1-hour long) with tool admins (VSP Infrastructure team) to determine tool usage, roles/permissions context, as well as gauging user thoughts on current role paradigms for tools used in the VA ecosystem.
* Interview Attendees:
  * Mike Chelen (manager of Infrastructure team), Jesse House, Jeremy Britt, Matt Leclerc, John Stevens-Garmon, and Michael Fleet (Team Lead)
* Research Artifacts:
  * Kickoff: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2049409029/UX+Research+AxMan+Roles+Permissions
  * Conversation Guide: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2048786443/Roles+and+Permissions+Conversation+Guide

---
## Tasks

* For VSP Infrastructure Team: Please provide the Access Management Team (specifically Jimmy McConnell and Thomas Ferrin) some 1-hour long slots that the Infrstructure team would be available for a 1-hour long knowledge sharing session with researchers. Ideally, these times would be Monday 1/24 through Wednesday 1/26.

Thomas Ferrin is @TPurple on Github and can help coordinate communication with Jimmy. Otherwise, I (@jchapin) will be willing to assist as well.

## Acceptance Criteria 

@TPurple will need some acceptable dates and times for conversations.

Thank you very much for your help.

**Comment by jmcconn120** [comment]
Discussion with the Ops/Infra team will be scoped to only AWS IAM and GH Teams topics.

**Comment by jhouse-solvd** [comment]
@jchapin - Can you provide any update on this request?

**Comment by jchapin** [comment]
@jhouse-solvd I asked @TPurple for an update.

Jimmy McConnell (@jmcconn120) has moved on to another job. In which case, we probably need to remove his user from the VA org... I'll open that issue.

**Comment by jchapin** [comment]
From @TPurple:

> Jimmy tried multiple times to schedule an interview with the Infrastructure team, but they never responded. So we came up with [recommendations](https://dsva.slack.com/archives/C02GQ27HXQW/p1643391562735309) without them. Unless AMT needs to have this conversation, I think this ticket is closeable.

Closing then.
