### ISSUE TITLE
Adding Kateleigh Clark to DSVA Slack, #va-virtual agent-public channel

### ISSUE THREAD

**Issue by sstrassberg** [department-of-veterans-affairs/va.gov-team#35644]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<Kateleigh Clark is already a mutli-channel guest and needs to be added to the #va-virtual-agent-public channel>

Are you requesting to add an individual as a:

- Multi-channel
- What channel(s) do they need to be added to?
#va-virtual-agent-public channel

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Kateleigh works for Booz-Allen on VA Omni-Channel Initiatives, and is supporting some research for the virtual agent. She needs access to this public channel to share relevant materials to their support work.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
done
