### ISSUE TITLE
Maintain a Severity Rating System and Process for Application Vulnerabilities

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35652]
# Description

# User Story
**As a** VSP Engineer
**I need** to make sure that certain ratings of Vulnerabilities are not introduced into the coding environment.
**So that** there are minimum vulnerabilities found in production code.

# Acceptance Criteria

# Technical Description

# Expected end date
End of Sprint 1 (5/25/2022)

**Comment by sylvesterlee1911** [comment]
Document on process around critical and high.

**Comment by sylvesterlee1911** [comment]
Reviewing this to close.

**Comment by sylvesterlee1911** [comment]
This was added in one of our meetings.  We have reviewed and do not have a plan forward for this at the current time.  Closing this one to reopen once we have a clearer direction.

**Comment by joeniquette** [comment]
This still needs to be done, we should have it in the backlog instead of closing it.

**Comment by sylvesterlee1911** [comment]
Finalizing edits and formats.  Info is in document.
