### ISSUE TITLE
Add field on user serializer to let frontend know if MHV user is eligible for upgrade

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35656]
## Issue Description
Whenever /user endpoint is called, if user logged in with MHV, but has no logingov_uuid in their Accounts table, make a call to MHV and see if they are eligible

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bosawt** [comment]
Gonna close this. If we have additional inherited proofing tasks we can replan
