### ISSUE TITLE
[UX][RESEARCH] Incorporate Veteran Feedback in Product Workflow 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35668]
## User Story
As a Veteran, I want a feedback/survey option for the Check-in product, so that I can submit feedback on the mobile check-in experience _**while in the product workflow**_.

## Description 
Currently interactive PDFs are being sent to clinic staff members to collect feedback from Veterans on the mobile check-in experience. We would like to incorporate some type of feedback/survey mechanism in the check-in workflow to capture that information in a more streamlined way and help improve the overall experience. 

This ticket is to research the optimal way for that feedback to be incorporated.

Slack thread with more details [here](https://dsva.slack.com/archives/C02GXKL8WM6/p1642446566014900). 

## Acceptance Criteria::
- [ ] UX has discussed and documented possible solutions to incorporate feedback in Check-in Product
- [ ] UX has met with appropriate teams (Product, engineering, etc.) on recommendations.
- [ ] Design ticket has been created

**Comment by kristenmcconnell** [comment]
Just heard from ToT update...
**The Contact Center team (Medallia peeps)**
- The blue feedback tab is moving down to become a button above the footer
- Feedback survey is currently opt-IN, but is changing to opt-OUT (for VFS implementation on their pages) - this means the feedback button will show up on all pages unless you say you don't want it there

**Outstanding questions**
- Does the above meet our needs? 
- If not, do we need to turn off Medallia?
- When do these changes take effect? Talk to Medallia.

**Comment by kristenmcconnell** [comment]
Screenshot of the Medallia changes. 
![Screen Shot 2022-01-25 at 1.51.02 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ea4be55a-d766-4d2b-8139-03057842a043)
