### ISSUE TITLE
Integrate Sitewide Content into Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35673]
## Background
Earlier in 2021, the Sitewide Content team was introduced. Their mission was to help provide content guidance and support the VFS teams with during product development. At that time, the role of content on the Platform (specifically within the Collaboration Cycle) was limited to validating that products adhere to VA.gov content standards. Please refer to the Sitewide Content direction distinguished from Platform content standards review document for additional information regarding the differences between the 2 teams.

## Problem Statement
As the process matured, it has been challenging for the Collaboration Cycle to know which VFS teams are engaging with the Sitewide Content team. The guidance that VFS teams receive from Sitewide Content may be beneficial for Collaboration Cycle reviews, and the lack of visibility could lead to misaligned feedback. Additionally, Sitewide Content team may not be engaging with teams that could greatly benefit from their support. Since Collaboration Cycle doesn’t provide strategic content guidance to VFS teams and only validates for VA.gov content standards, it’s possible there are products live on VA.gov that don’t adhere to the overall content strategy of VA.gov.

Please see the [Integrate Sitewide Content intake request into Collaboration Cycle](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2004025355/Integrate+Sitewide+Content+intake+request+into+Collaboration+Cycle) documentation for additional details. Beth and Danielle with Sitewide Content communicated on 1/18 that they'd like to move forward with Option 1.

---
### Platform Website updates
- [x] Create the Sitewide Content and IA intake request touchpoint page in the [Documentation Drafts space](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2064252940/Shira+-+Sitewide+Content+and+IA+intake+request)
   - [x] Ask for input from Sitewide Content team
   - [x] Make edits to the page per Sitewide Content team feedback
- [x] Update[ Touchpoints page ](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints)to add Sitewide Content and IA intake request
- [x] Update [Overview page](https://vfs.atlassian.net/wiki/spaces/CC/overview?homepageId=1524891996) to:
   - [x] Add Sitewide Content and IA intake request to The "Define" Phase
   - [x] Add Sitewide Content and IA intake request to image
- [x] Update [Contact us page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us) to add Sitewide Content (Beth & Danielle?)
   - possibly update "Content" entry to "Platform Content"
- [x] Draft Change History post announcing Sitewide Content and IA intake request being included in the Collaboration Cycle
   - [x] Share post with Sitewide Content team for review/approval

### Confluence updates (aka Operational docs)
- [ ] Modify response script in the [Collaboration Cycle kickoff moderator responsibilities guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) to include Sitewide Content and IA intake request
- [x] Update [Custom Tracks flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow) to include Sitewide Content and IA intake request on tracks 1-4

### Misc. updates
- [ ] Possibly add `collab-cycle-review` github label to [Sitewide Content & IA intake request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) in github

## Acceptance Criteria
- [x] VFS teams recognize that Sitewide Content and IA intake is part of the Collaboration Cycle
- [x] Platform and/or others will no longer need to recommend to teams at Design Intent and/or Midpoint Review that they submit a Sitewide Content and IA intake request
- [x] Sitewide Content team will engage with all teams/products coming through the Collaboration Cycle

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
hi @bethpottsVADEPO and @DanielleThierryUSDSVA. This is the ticket we created to integrate the Sitewide Content and IA intake request into the Collaboration Cycle. I have 2 requests. First, review the full ticket and let me know if you have any questions or concerns, or if you notice something is missing. 

Second, can you please review the draft of the future [Sitewide Content and IA intake request touchpoint page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2064252940/Shira+-+Sitewide+Content+and+IA+intake+request) for Platform Website? Right now it is mostly blank... I included the headers used on most touchpoint pages, but please  let us know if any aren't applicable. The content of this page is mostly up to you, but we do try to have a consistent format across all touchpoints. Feel free to review the other [Touchpoints pages](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) for reference. I _think_ you have Confluence access, so feel free to edit the page directly, or you can just send us a word doc or gh markdown page. Either works.

Thanks and looking forward to hearing from you soon!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @shiragoodman! Will review and reach out with any questions (or if we have trouble with Confluence). Thanks again!

**Comment by shiragoodman** [comment]
sounds good! tagging @mnorthuis for awareness :)

**Comment by shiragoodman** [comment]
hey @DanielleThierryUSDSVA and @bethpottsVADEPO  - any updates on this? Please let us know how we can help move this along. Thanks!

**Comment by mnorthuis** [comment]
I took a stab at the [touchpoint page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2064252940/Shira+-+Sitewide+Content+and+IA+intake+request) just to get us started.

**Comment by DanielleThierryUSDSVA** [comment]
I have not been able to get to this on my end yet, @shiragoodman. Will try to look at it this week. Thanks!

**Comment by shiragoodman** [comment]
The draft page looks great! Thank you for putting it together. As stated before, Sitewide Content team is the owner of this touchpoint so you have full control over how support is communicated.

@bethpotts @DanielleThierryUSDSVA when we spoke on Friday, I think we had discussed the possibility of adding the `collab-cycle-review `github label to the template. Is this okay with you? All Collab Cycle touchpoints have this label to make querying simpler. Please let me know. 

I will be moving forward with the other tasks listed in this ticket, including drafting the post for the Collab Cycle Change History log. Would you like to review that before we publish?

Thanks again.

**Comment by mnorthuis** [comment]
I may have a couple of really minor edits to Danielle's changes, but she is traveling today so I will let you know.  

The intake is used for more than collab cycle type work, it is also for general content tickets into the team, so adding the collab cycle label may not be pertinent to all tickets created using that template.  

For the Contact Us page referenced in the tasks, I would want Sitewide IA also referenced, so not sure how to distinguish between Jim and myself for that. 

For the Overview page, I'm assuming this intake ticket step would be part of the initial Define phase, correct?

**Comment by mnorthuis** [comment]
The touchpoint page is ready to go, I'm going to leave it as is. 

I can work with Stan on getting the label added, our intake process is a bit in flux right now, so this may not happen right away.

**Comment by mnorthuis** [comment]
@shiragoodman Just wanted to follow up on remaining open tasks for this work.     Is there anything that you are waiting for us on?

One of the big things we are trying to tackle with this, is making sure that teams do not associate our work as a checkpoint or review process.  The step of creating the intake ticket is part of the collab cycle, but there is a lot of ongoing collaborative work that happens after that with our team that is not collab cycle work.  So anything we can do to make it clear that the collab cycle is just asking for them to submit the ticket to kick-off _working and collaborating with us_, that will help.

**Comment by shiragoodman** [comment]
Thanks for following up, Mikki. Sorry, I have not had the time to address this ticket after I last commented. I don't believe there's anything else I need from you at this time.

Regarding your concern, I completely understand. The Analytics Request, Contact Center Review, and Privacy, Security and Infrastructure Readiness Review are all similar - it's not just a "one and done" but more of a collaborative process. I do believe that's communicated appropriately in the draft page. After it's published, if you're finding that teams are surprised by the process or unaware that this is how the Sitewide Content & IA Intake request works, then we can talk about other ideas to make sure it's communicated clearly.

**Comment by shiragoodman** [comment]
@mnorthuis @bethpotts @DanielleThierryUSDSVA Please review the draft I created of the [Platform Website Contact Us page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2112848108/Shira+-+Contact+us) and let me know how you'd like me to communicate your names and titles.

**Comment by shiragoodman** [comment]
@mnorthuis @bethpotts @DanielleThierryUSDSVA The supporting pages have been drafted and are ready for your review (in addition to the Contact us page above).

- [Sitewide Content and IA intake request](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2064252940/Shira+-+Sitewide+Content+and+IA+intake+request) touchpoint page on Platform Website (has not been modified by us)
- [Contact us](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2112848108/Shira+-+Contact+us) page on Platform Website 
- [Collaboration Cycle overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2112848151/Shira+-+Copy+of+Collaboration+cycle+overview) page on Platform Website
- [Change History log](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2112880935/Shira+-+Copy+of+Change+history) on Platform Website
- [Collaboration Cycle Kickoff Moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2112880971/Shira+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) on Confluence (note: this is an internal doc. The only thing that changed is our response script now includes a reference to the Sitewide Content & IA Intake request)

**Comment by shiragoodman** [comment]
@mnorthuis @DanielleThierryUSDSVA @bethpottsVADEPO Have you been able to review this yet? Please let me know.

**Comment by bethpottsVADEPO** [comment]
@shiragoodman We'll have feedback to you by Wednesday!

**Comment by bethpottsVADEPO** [comment]
@shiragoodman This all looks great! @mnorthuis, @DanielleThierryUSDSVA, and I just had one suggestion for grouping teams on the contact us page to make it clear that sitewide content and IA is a different team (since there's been ongoing confusion about that). What do you think about doing something like this with subheads?:

## Platform teams enforcing standards in the Collaboration Cycle

**Governance Team**
Product Manager: Shira Goodman
Delivery Manager: Chase Kirby
Design: Allison Christman & Sean Sewell
Content: Cheryl Evans
Information Architecture (IA): Jim Ryan
Quality Assurance (QA): Dariusz Dzien
Accessibility: Brian DeConinck & Sarah Koomson
Research: Clayton Zook

**Analytics & Insights Team**
Product Manager: Michelle Dooley

**Platform Security**
Platform Security Lead: Troy Mosher
OCTO-DE Security Lead: Thomas Delrue 

## Other teams supporting product development in parallel with the Collaboration Cycle

**Contact Center Team**
Product Manager: Jason Woodman
Contact Center Lead: Kimberley Monroe-Daniels

**Sitewide Content & IA** 
Content Leads: Danielle Thierry and Beth Potts
IA Lead: Mikki Northuis

**Comment by bethpottsVADEPO** [comment]
Sounds good @shiragoodman. Thanks for the collaboration on this.
