### ISSUE TITLE
Investigate running Keycloak locally and integrating with that.

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#35674]
Get Keycloak running locally for everyone on Console Services

- [ ] Document how this can be run locally for everyone (readme) 
- [ ] Get everyone on the team running this

**Comment by npeterson54** [comment]
Talking with Kevin Duensing, they are preparing a way for us to run keycloak locally, reach out to him for details.

**Comment by thilton-oddball** [comment]
Talked with Kevin Duensing and told him I was able to run Keycloak locally with Docker and he said, "The only thing that we would add is an integration with Login.gov as an identity provider. We don't intend to use Keycloak as an identity broker itself, instead farming out to something with better identity assurance. We can get you that realm export file soon."
