### ISSUE TITLE
Content Review: Higher-Level Review Form (Review Application Screens)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3567]
## User Story or Problem Statement
As a UX designer, I need a content review for the HLR form so I can ensure that the design contains copy that follows VA.gov guidelines.

## Goal
_A content review on the HLR form for the "Review Application" screens_

## Objectives or Key Results this is meant to further
- _Designing/developing the HLR form following VA.gov design guidelines_

## Acceptance Criteria
- [x] _Peggy reviews the HLR "Review Application" screens_
- [x] _[Screen 1](https://vsateams.invisionapp.com/share/J8UWM0P3KHM)_
- [x] _[Screen 2](https://vsateams.invisionapp.com/share/B6UWM12NZ4F)_
- [x] _[Screen 3](https://vsateams.invisionapp.com/share/RGUWM1G97N2)_
- [ ] _(Optional) Peggy and the designer meet to discuss content edits_
- [x] _The designer updates mockups with Peggy's content edits_

**Comment by peggygannon** [comment]
Hi, @rileyorr I reviewed screens 1, 2, and 3. Please let me know if you have any questions about my content recommendations. I'll give these screens a look again once the changes have been incorporated.

**Comment by rileyorr** [comment]
@peggygannon All updates have been incorporated except one on screen 3, which I've responded to and tagged Robin in case he has more insight. LMK if you wanna hop on a call to discuss at some point!

**Comment by peggygannon** [comment]
thanks, @rileyorr I reviewed your updated mockup and the changes look good. I don't have anything else to add to this issue, so I think we can close this one. 

cc @YanaRoy
