### ISSUE TITLE
Adding cms-change-management user group to DSVA Slack

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#35686]
# Description
Looking to add the following:

**Group Name**:
  CMS Change Management

**Group Handle**:
  @cms-change-management

**Group Purpose**:
  To help collaborate across this practice area

**Group Default Channel**:
  #cms-team

<describe the request>

Are you requesting to add an individual as a:

- Full member
- What channel(s) do they need to be added to? #cms-team

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
I think we already have this group?

**Comment by cmaeng** [comment]
hi @LizCallaghan . i don't think this one has been set up yet. this is what i see when trying to search for it in DSVA slack:

**Comment by cmaeng** [comment]
@LizCallaghan sorry, just noticed that in the request I didn't change the group name to the new one. my apologies, looking to set up @cms-change-management, not @cms-product-support (which already exists)

**Comment by LEHigley** [comment]
done
