### ISSUE TITLE
Investigate Cognito and login.gov logout mechanisms

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#35694]
Including:
- Cognito logout callbacks
- login.gov logout callbacks
- Login.gov logout in separate apps (same credentials with two different apps, are they both logged out?)
- Cognito logout in separate apps (same credentials with two different apps, are they both logged out?)
- Are logouts (Cognito and/or login.gov) an API call or browser redirect? Any options here?
- Does Cognito need to be polled for expired session or will it send a logout request automatically?

**Comment by bramleyjl** [comment]
Cognito/Login.gov Logout research has been compiled here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/logout_research.md
