### ISSUE TITLE
Adding Google Optimize script to GTM

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#35690]
# Background
In order to gain more insight into Veterans usage preferences we would like to begin running A/B tests on our team's apps. These A/B tests will give us access to information that moderated tests can't including much larger sample sizes as well as data that reflects a real cross-section of our user base ( moderated tests often are conducted with a limited number of users and this skews the data to be bias toward those user's abilities). In order to begin A/B testing we would like to first run a "pilot" test on one of our Apps to allow us to establish a good working structure for A/B tests in the future.

To set up the pilot A/B test we need to include the Google Optimize script on our App's page. To do this using best practices we are proposing that we set up the Google Optimize script to load inside Google Tag Manager based on a page trigger for our App's URL. This will minimize the risk of page flicker, as the script will be one of the first to load on the page, as well as allow us to deploy a test without a code deploy and let us easily expand testing ability to other pages simply be changing the page trigger in GTM.

For further context, here are a few links -

[Here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/ab-testing/rated-disabilities/table-sorting) is the link to a page about the actual test we will be running

[Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/ab-testing/rated-disabilities/table-sorting/Implementation.md) is a link to a page about how we will implement the test using Google Optimize

Per [this](https://dsva.slack.com/archives/CBU0KDSB1/p1642616513023800) conversation in Slack, here are the answers to specific questions folks had -

`Who will be handling the creation and deployment of experiments?` - At this point I will be the only one creating and deploying experiments however we are creating a "guidebook" that any other team could pick up in the future that will tell them how to run a test but that will be a ways off in the future.

`What does this pilot look like? Just something we test internally with a GTM debug URL?` - I believe the two links above answer this but  this pilot will be a live test on VA.gov but we will be testing internally using a GTM debug URL while we are building the test.

`And who will handle configuration in GTM?` - I was hoping that the Analytics team would but I can handle this if needed.

**Comment by laurensimpson14** [comment]
Hi @cohnjesse 👋 

I'm working on getting this into GTM for you! I have two questions: 
1. What is your `Optimize Container ID`?
2. What are the URLs for the pages that the GTM trigger needs to fire this script on?

**Comment by cohnjesse** [comment]
@laurensimpson14 Hey Lauren, it looks like the `Optimize Container ID` is `8805919` and the URL for the page for the trigger to fire on is `/disability/view-disability-rating/rating`

**Comment by laurensimpson14** [comment]
Thank you!! 

@jennaouellet Could you please QA for me? I've added a new tag and trigger to the GTM workspace [35690](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000592).

**Comment by cohnjesse** [comment]
@laurensimpson14 Yep, it looks like it is firing

**Comment by jennaouellet** [comment]
The tag is firing on the intended page - QA is complete.

**Comment by laurensimpson14** [comment]
@cohnjesse Here is a GTM debug URL: https://tagassistant.google.com/#/?id=GTM-WFJWBD&url=https%3A%2F%2Fwww.va.gov%2F%3Fnext%3D%252Fdisability%252Fview-disability-rating%252Frating&source=TAG_MANAGER&gtm_auth=1UtLdDClVh-hAFBTOvnnlA&gtm_preview=env-1687

**Comment by michelle-dooley** [comment]
This work has been completed, we are closing this ticket.  If you need anything else please reach out.
