### ISSUE TITLE
SideNav - Test with 1 more level deep for nav items

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#3570]
# Context
This ticket pertains to the new SideNav, which is viewable [here](https://staging.va.gov/pittsburgh-health-care).

# Current Behavior
While the SideNav will render 1 more level deep of nav items successfully, it does not look like the design spec.

# Desired Behavior
The SideNav should be able to handle 1 more level deep of nav items and still match the design spec.

# Acceptance Criteria
- [ ] Ensure that the SideNav can handle 1 more level deep for nav items and match the [design spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/design/VA-gov-on-page-nav-MASTER.pdf).

**Comment by MickinSahni** [comment]
Blocked until designs are updated based on research
