### ISSUE TITLE
Add the `yarn version` plugin to the component-library repo

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35709]
## Description
We would like to add the `yarn version` plugin to the component-library repo to make the versioning process a little easier. We also need to update the README with instructions on how it should be used.

## Acceptance Criteria
- [ ] Install `yarn version` plugin
- [ ] update README with instructions on how to use it

**Comment by pdavies88** [comment]
Command to install is `yarn plugin import version`
