### ISSUE TITLE
Create CI action in components-library requiring a proper label for all PRs

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35707]
## Description
In order to automate our versioning process, we would like to require that anyone submitting a PR to the `component-library` repo add a label of `major`, `minor`, `patch`, or `ignore-for-release`. In order to enforce this, we would like to add a CI step as part of the PR verification process that checks for this label and fails the PR if the label is not present. This failure should be merge-blocking.

## Details
We really want to make sure that a `major`, `minor`, or `patch` label is added to any PRs that make changes to the `react-components` and `web-components` directory. If it is possible to enforce this rule only on changes to those two directories, we may not need to use the `ignore-for-release` label. We would also want to make sure that a PR only uses one of these labels.

## Acceptance Criteria
- [ ] As part of the PR CI check process, CI looks for the appropriate label on the PR and fails if it is not present.

**Comment by bkjohnson** [comment]
[This github action](https://github.com/marketplace/actions/require-labels) seems like it will allow us to do what we want.
