### ISSUE TITLE
UXW SUPPORT: Contact Center - consult on team's Platform website content

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#35716]
# User story
As a Contact Center team member, I want to know where to put Platform website docs so that I can share info w/ VFS teams _while_ maintaining Platform website structure.

# Tasks
- [x] Schedule two sessions with Jason Woodman
- [ ] More actions to come after Session 1

# Acceptance criteria
- We have shared a recommendation with Contact Center, regarding where their docs should live on the Platform website

# Reference info
- Contact Center / Content notes https://docs.google.com/document/d/1klQBDOfISFTWB2AkBj7VkUCCNuPGTOu1zmlkJoHar_8/edit#

**Comment by lianilychee** [comment]
pause pending Jason mtg

**Comment by lianilychee** [comment]
Fri 1/28:
- pending Jason to send links, perhaps post SU to discuss IA

**Comment by lianilychee** [comment]
Tues 2/1:
- see how the four docs that jason sent can fit into the templates

**Comment by amygoldman** [comment]
Which doc fits which template: https://docs.google.com/document/d/1klQBDOfISFTWB2AkBj7VkUCCNuPGTOu1zmlkJoHar_8/edit#bookmark=id.t08rurfzoanp
