### ISSUE TITLE
Design intent [CMS-Offices - Offices Directory]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#35718]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [x] Respond to Platform feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [x] Yes
- [ ] No

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/tier-3-fom)
 
 
 
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes – see Mural link below
- [x] User flow – [Mural link](https://app.mural.co/t/vagov6717/m/vagov6717/1640629873689/0636fba7cfcd46d16f1b4e3b16e4a2b304c4bf10?wid=0-1641405363068) (upper right of board, "Flows we care about" should be linked directly)
- [ ] Any other artifacts you have so far

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by seanasewell** [comment]
@wesrowe No design feedback but here is a link to the [find a form](https://www.va.gov/find-forms/) resource I referenced on Friday. Good work so far, excited to see this what this looks like at Midpoint!

**Comment by seanasewell** [comment]
Here is the link to the [Zoom call](https://us06web.zoom.us/rec/share/wIP1ZkFaLAaQ8nj4dFKQADRSx6uSfjRYR3v8tOxce_C9eYupA9u65JL5NzUIui43.uRdFevC3-27dE8b5) Password is !9H?U%fY

**Comment by jimuhh** [comment]
No IA feedback. Really like the work so far.
