### ISSUE TITLE
Friendy clinic name not returned to the front-end

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#35711]
This ticket is to track and retest the follow VAOS-R ticket:
https://issues.mobilehealth.va.gov/browse/VAOSR-2892

**Comment by cferris32** [comment]
Verified through manual retesting that the clinic friendly names are displaying as expected per the original Jira ticket and match what's in VAR Resources.

![Screen Shot 2022-03-14 at 1.01.10 PM.png](https://images.zenhubusercontent.com/5fcfbc1c239ebd98b2acfe6c/1b7430da-7ef6-420e-90be-9d21d46af1b9)
