### ISSUE TITLE
[FE] Log Runtime Errors to Sentry

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35712]
## Description 
FE currently only logs in GA but would like to log to Sentry. 

FE Team met to discuss how error logging could be logged in Sentry. This ticket is an outcome of that meeting to log API errors to Sentry.

#Tasks

## Acceptance Criteria 
- [ ] FE errors pertaining to runtime are now logged in and visible in Sentry.

**Comment by sarahknoppA6** [comment]
to be covered at Sentry working session

**Comment by mdewey** [comment]
@sarahknoppA6  Team was given an overview, this is good to close
