### ISSUE TITLE
Remove "Home" from breadcrumbs

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#3572]
# Current Behavior
Breadcrumbs currently include the "Home" link. You can see an example of this [here](https://staging.va.gov/pittsburgh-health-care/stories).
![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/5e1d49c1-f6e2-4c0e-8794-426f1d2928b1)

# Desired Behavior
Breadcrumbs should not include the "Home" link.
![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/1347ed30-4262-499d-ba7d-04932c514746)

# Acceptance Criteria
- [ ] Remove "Home" link from breadcrumbs.

**Comment by ncksllvn** [comment]
Hey @kevwalsh @jefflbrauer, it looks like we want to start excluding the `Home` link from the breadcrumbs. We have a PR ready in vets-website to skip that link from the Drupal breadcrumbs data, but I'm wondering if we could do that on the Drupal side. What do you think?

**Comment by kevwalsh** [comment]
This is a simple change on Drupal end. I'll see if I can get this into today's CMS deploy, but it might be for Monday

**Comment by kevwalsh** [comment]
@kelsonic @ncksllvn this is site wide right? At least, all CMS hosted products? Benefits hubs, VAMC, outreach materials...

**Comment by ncksllvn** [comment]
@kevwalsh Yep, that's my understanding! @jenniferlee-dsva do you want to provide any more context?

**Comment by jenniferlee-dsva** [comment]
@kevwalsh @ncksllvn - we're doing this first on Pittsburgh as part of side nav (left nav) work. So not sitewide at this time.
