### ISSUE TITLE
va-text-input does not render HTMLElement inside its label

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#35734]
## Issue Description
Our `va-text-input` web component has a property named `label` that accepts either a `string` or `HTMLElement`. If an HTMLElement is given for label, the component will render improperly or not render at all. This was tested with and without bindings.

![Screen Shot 2022-01-20 at 20.18.11.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/31f99f32-4144-45b8-bbe8-a7fbb4f4baf1)

## Tasks
- [ ] Add a named slot inside va-text-input's label element

## Acceptance Criteria
- [ ] va-text-input accepts a HTMLElement to be rendered inside its label

**Comment by pdavies88** [comment]
@andresriveratoro @k80bowman with the completion and merging of this ticket do we want to create a separate ticket to update https://design.va.gov/experimental-design/hint-text and either remove that page or put a link to https://design.va.gov/components/form-controls#text-inputs that I will now exist in `va-text-input` and then probably add the Storybook example to the form-controls page.
