### ISSUE TITLE
Improve GA reporting of Direct Deposit save errors

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3573]
We currently track when DD save/updates fail due to a bad/missing address or phone number. All other errors are simply tracked as 'other-error'.

We'd like to have more granular tracking of other DD save/update errors. So we'll report errors related to:
- being flagged for fraud: 'fraud-alert-error'
- having an invalid/incorrect routing number: 'incorrect-routing-error'
- maybe others??

Relevant code is at https://github.com/department-of-veterans-affairs/vets-website/blob/8a7a0cdaa7e62d8c610d1e291c9d2a5f18e9b81c/src/applications/personalization/profile360/actions/paymentInformation.js#L98-L99 and also https://github.com/department-of-veterans-affairs/vets-website/blob/129735cb5b19dbcb2648ef05545a7749907d09c5/src/applications/personalization/profile360/util/index.js#L66-L85

**Comment by erikphansen** [comment]
@clantosswett @nedierecel Tagging you for awareness. I'll follow up in this ticket with more details about the different save/update failures that we can get and potentially report to GA.

**Comment by nedierecel** [comment]
Thanks @erikphansen From my standup, we won't need to adjust any other GA settings, so we should be able to catch any new error keys that you decide on passing to this parameter.

@clantosswett Once it is implemented, we'll expect to see the `other-` error key decline or go to zero depending on Erik's implementation. 

CC: @jonwehausen for QA later

**Comment by erikphansen** [comment]
@nedierecel @clantosswett I have a PR up that will expand the list of possible error keys we'll send GA when Direct Deposit saves fail.

The full list will be:
- `'mailing-address-error'`
- `'home-phone-error'`
- `'work-phone-error'`
- `'flagged-for-fraud-error'`
- `'invalid-routing-number-error'`
- `'payment-restriction-indicators-error'`
- `'other-error'`

**Comment by erikphansen** [comment]
@nedierecel @clantosswett Can either of you verify that you are seeing the new error keys in GA and close this issue if you do? There should definitely be some `flagged-for-fraud-error` errors in there since this went live yesterday at 3ET. Thank you.

**Comment by nedierecel** [comment]
@erikphansen Of the 3 new error keys, I see the `flagged-for-fraud-error`. I can continue to monitor through Monday and see if the additional errors appear.

**Comment by nedierecel** [comment]
@erikphansen @Justin-Pickett @Samara-Strauss 

Confirming I see `invalid-routing-number-error` as well, but I have not seen an instance of `payment-restriction-indicators-error` yet.

**More Research**: After our Slack thread last week, I did more digging on the mismatch with Sentry. As DD and any other features grow in Audience size, granular reports within Google Analytics may be sampled as we filter to more specific points like `error-key`. We did not see this when it was in 10% beta but will encounter this onward when viewing the dashboard. 

I realized this as I clicked through to the report and see this yellow icon.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/238603e1-c581-4e7b-b4f5-0c80163edf79)

For our post-Thanksgiving discussion: 
- We **do** have access to this Unsampled Data via an Unsampled reports scheduler, which I can send as a routine report and also show you how to access so you can self-service. 
- Compare Sentry data to unsampled data and determine path forward for reporting error key

CC: @joanneesteban @jonwehausen

**Comment by Samara-Strauss** [comment]
Reopening because I have questions:

> After our Slack thread last week, I did more digging on the mismatch with Sentry. As DD and any other features grow in Audience size, granular reports within Google Analytics may be sampled as we filter to more specific points like error-key. We did not see this when it was in 10% beta but will encounter this onward when viewing the dashboard.

I'm so confused. So the data we're seeing in GA is not raw data, but a sampling of data? How are we supposed to interpret it, then?

Also, we were seeing significantly fewer errors in Sentry than GA — if the GA data is a sample size of users, shouldn't we be seeing fewer errors in GA than Sentry and not more errors?

I guess we'll discuss this on Monday, but let me know if you have any thought before then @department-of-veterans-affairs/digital-experience

**Comment by nedierecel** [comment]
@Samara-Strauss @Justin-Pickett @erikphansen Thanks for syncing up for :30 today. Here are the follow-ups:

1. Unsampled data is available to download should we run into this again within the interface. I'll reach out to GA Support since it was unusual that we ran into that error.
2. Erik, we'll sync up again on how Sentry increments errors (e.g. if they happen within a certain timeframe, how does it measure errors?)
3. I'll add Form Saves to the Personalization dashboard.

**Comment by Justin-Pickett** [comment]
Closing this ticket. Will open a new ticket to be tracked during Sprint 10.
