### ISSUE TITLE
Access for David Lennon

### ISSUE THREAD

**Issue by dlennon-va** [department-of-veterans-affairs/va.gov-team#35730]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

David Lennon

### Your Email

david.lennon@libertyits.com

### Name of Your Team

Matsumoto - Lighthouse, Team Lead, Liberty IT Solutions

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJt2k6hJwYs1liN8YHbrSuvYmXVLee9K65cOgq+btWQf1m+3MktUbZIVuyR9MCRgkm/EUZriW/yfN3HImTfWTVSoyvVPELRTZriPta1grbqD73Vms9bBbbFBHMc3MHxc5yq2tbBLyuiebBj+UWE4492qIJb0DmOwJZ0nbLG1mCcf+m+rB7A9p0HTHj7eY2nNV50/igZ8jVAAeUfcBV4KyWLdgPIUNAgf0DVMDW9G3Lbpy8VS9Sm/NirlyFg9ElS7mA0lSnOd9t72zUZpRfqadwkvrBvIaYo/gQfbJ/FyL+Sg6q4sQYqyIVfcVCgfjk2Wq5u9HAVpvaY8fsaJsA5tqp davidlennon@Davids-MBP

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
