### ISSUE TITLE
[FE][SPIKE] Look into Speedcurve for page performance insights

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35731]
## Description 
Need to look into if/how we could incorporate Speedcurve for FE insights. 

SpeedCurve provides insight into the interaction between performance and design to help you deliver fast and engaging user experiences.

SpeedCurve also provides performance feedback of each app such as page size and how long it takes to load a page, and can show you the impact new features have on the performance of the app.

Slack [thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1642775941306700) with more details.

**Comment by sarahknoppA6** [comment]
bundle w/sentry working session this week. Sarah to schedule

**Comment by sarahknoppA6** [comment]
@mdewey team is unsure if these are ready to close
