### ISSUE TITLE
AVS Overview

### ISSUE THREAD

**Issue by djfredvs** [department-of-veterans-affairs/va.gov-team#35740]
The document here contains how the AVS overview will be presented in training.[https://app.zenhub.com/files/133843125/7c02a626-fe19-4c8d-a416-ede23e5c8d2b/download](https://app.zenhub.com/files/133843125/7c02a626-fe19-4c8d-a416-ede23e5c8d2b/download)

**Comment by lindsay-insco** [comment]
Duplicate
