### ISSUE TITLE
Feedback Tool Staging Issue

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#35741]
## What happened?
Unable to submit an application in the FT Staging environment. This is happening in both cases when signed in and without signing in. Getting this: 
<img width="640" alt="Screen Shot 2022-01-21 at 10 39 52 AM" src="https://user-images.githubusercontent.com/86266024/150566005-68bf0a8c-82ff-4fd2-9b58-1cf337a8f311.png">

## Steps to Reproduce
- Navigate to: https://staging.va.gov/education/submit-school-feedback/introduction
- Proceed till the last step then submit the application

## Desired behavior
- Application should be submitted successfully.

## Acceptance Criteria
- [ ] FT application should be submitted successfully

**Comment by mrblanco1** [comment]
Closing as this issue no longer can be reproduced. Abe B.
