### ISSUE TITLE
Inventory Platform team member CAG access status

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#35758]
## Goal
Determine how much of Platform team is able to access VA resources using remote desktop (CAG).

## AC
- [x] CAG status for Platform team members is listed
  - [x] [VSP team members](https://docs.google.com/spreadsheets/d/1kZSbabHLNDgSpKDMwqDsxUImMi8nU9_GqJq1TftVV3c/edit)
  - [ ] Spike team
  - [x] Platform CMS
- [x] Followup issues created for team members without working CAG access
  - [x] VSP
  - [x] Spike team
  - [x] Platform CMS
- [x] Create followup issue #45602

**Comment by nsmith1982** [comment]
Link to Platform Contract Onboarding Status https://docs.google.com/spreadsheets/d/1kZSbabHLNDgSpKDMwqDsxUImMi8nU9_GqJq1TftVV3c/edit#gid=951810306

**Comment by nsmith1982** [comment]
possibly split out alerting task

**Comment by mchelen-gov** [comment]
Updated issue to clarify scope, separate monthly status check into followup issue.

**Comment by cmaeng** [comment]
Platform CMS team as of 8/11/22:
- Eric Oliver = able to access CAG
- Jessica Alexander = able to access CAG
- Tim Cosgrove = able to access CAG
- Cameron Eagans = able to access CAG
- Aaron Ponce = able to access CAG
- Tanner Heffner = able to access CAG
- Elizabeth Neal = able to access CAG
- Penny Lischer = able to access CAG

**Comment by mchelen-gov** [comment]
@nsmith1982 Reminder to create followup issues for any VSP team like @andreahewitt-odd who do not have working CAG access.

**Comment by andreahewitt-odd** [comment]
@laurylzenobi Send to Chelen and CC ray, matt, thomas

**Comment by mchelen-gov** [comment]
Closing as complete.
