### ISSUE TITLE
Design Feedback- Design Intent - eBenefits Migration Team - Specially Adapted Housing Grant

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#35764]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great Work!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- We are no longer using green buttons. Replace "Sign in to start your application" green button with a blue button. 
- The text link that says "Start your application without signing in" under the "Sign in to start your application" button should not be bold.

**Should:**
- The action link that says "Apply for a housing grant" that is located under the "Follow these steps to apply for a housing grant" section should be consistent in language and styling as the call to actions displayed earlier in the experience. We would recommend replacing the action link with the same blue button that says "Sign in to start your application" followed by the same text link that says "Start your application without signing in". Reference this experience when updating your designs: https://www.va.gov/education/apply-for-education-benefits/application/1990N/introduction 
- Replace text input field with text area field for Step 4 of 5: Your current living situation under the the question "Is there anything else you would like for us to know?". Reference https://design.va.gov/components/form-controls#text-area

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by candy-gcio** [comment]
Latest designs are in [sketch](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/p/5C807B24-B423-4109-9BC4-7230F0E21AEB).

There is a current [content review ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/36978) to review overall wording, including the "step 4 of 5" question in "should"
