### ISSUE TITLE
508 Spot Check Findings for Rated Disabilities

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#3577]
This will be a container for all issue ticket findings for the Rated Disabilities 508 Spot Check Review, related to [#3521](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3521).

**Comment by jenstrickland** [comment]
Trevor and I are capturing web performance in our audits, since perf has an impact on the ability of assistive technology to connect to web pages and apps.

![3577-perf-profile.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/67fe7c98-dea3-434f-b149-f27a2f10a43d)

![3577-lighthouse-perf.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/ba98390d-eb75-4e0d-8225-8965cf5c4c32)

**Comment by jenstrickland** [comment]
Trevor and I are capturing web performance in our audits, since perf has an impact on the ability of assistive technology to connect to web pages and apps.

![3577-perf-profile.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/fa2ff8b0-aa5d-4eb5-8e15-a4c651f89640)

![3577-lighthouse-perf.png](https://images.zenhubusercontent.com/5d6685f1a77bcf04870bc81c/178b27f2-0c10-4feb-8c9d-5672ac4ac60e)

**Comment by jenstrickland** [comment]
@jason-gcio - This spot check audit is complete.

**Comment by jason-gcio** [comment]
Thank you!
Chat soon

**Comment by jenstrickland** [comment]
@jason-gcio Are the items from this spot check addressed, anticipating the Pre-launch 508 Review?

**Comment by jenstrickland** [comment]
@jason-gcio and team addressed all issue noted above, apart from two regarding web performance that the VA gov web performance team is evaluating website performance impact on the functionality.

**Comment by jenstrickland** [comment]
Moved two potentially performance related issues to https://github.com/department-of-veterans-affairs/va.gov-team/issues/4404
