### ISSUE TITLE
Define process for creating a new app on the console

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#35785]
## Purpose
We need to define/note the process for creating a new app on the platform console. This includes (but not limited to) the manifest files, GHA pieces, creating a new repo and permissions. WIth a streamlined process, we will have the ability to quickly integrate applications with the console

## Definition of done
- [ ] Define all the pieces needed for creating a new app

## What we need to do
Currently, we don't have this process defined or any existing scaffolding

**Comment by LindseySaari** [comment]
# Automated process for spinning up a new app for the console

1. Create a private repo
2. Set up secrets AWS_ACCESS_KEY_ID and SECRETS in GH
3. Open up a ticket to make repo public
4. Scaffold out a dockerfile and versions file
5. Create ticket for ECR Repo
6. Possibly Open a PR For above step
7. RDS? Elasticache?
8. Argo project?
9.  Scaffold out the K8s deployment.yml and other manifest files
10. Scaffold the GHA - Mirror Images to ECR, Semantic release, update image tag in the deployment.yml
11. Add entry to main.jsonett for autosync
12. Argo permissions, K8s permissions?

**Comment by ericboehs** [comment]
Closing until Console project is active.
