### ISSUE TITLE
[1/25] Get access to AVS dev space for product support

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#35795]

**Comment by chancetheoriginal** [comment]
CPRS/AVS Access requires either GFE with correct profile assignment or CAG/1VA-Clinical desktop.
- If 1VA-Clinical does not autoload, it needs to be requested via YourIT/General Request.

Access achieved.

**Comment by lindsay-insco** [comment]
Demo with Shane complete - @chancetheoriginal accessed

**Comment by aschulhof** [comment]
Link to recording of demo - https://dvagov-my.sharepoint.com/:v:/g/personal/shane_elliott_va_gov/EYx7kB6QoD1Fjao_UOV3c1YBnu4XjbLSLFnGR7n3VEiIFA
