### ISSUE TITLE
Offboarding of all Caseflow team members 1/24/22

### ISSUE THREAD

**Issue by KCollinsBrown** [department-of-veterans-affairs/va.gov-team#35793]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
> Edwin Wong (github: NavaNavaEWong)
> Matthew Gardner (github: allthesignals)
> Amy Lai (github: amylai-nava)
> Omar Donnadieu Mercado (github: odonnadieu)
> Kim Ladin (github: KimLadin)
> Elizabeth Manning (github: lizzieamanning)
> Eileen McFarland (github: eileen-nava)
> Matt Wagner (github: n1zyy)
> Steve Taylor
> Bryant Kelley
> Brian Gantick (github: bgantick)
> Paula Bradin
> Stephen Cooke (github: scooke11)
> Matt Kerns (github: mkerns355)
> Meckila Britt (github: meckila)
> David (Nate) Martin (github: NateMartinTista)
> Monique Baena-Tan (github: mbaenatan)
> Latoya Maben (github: lmaben10)
> Abby Ranson (github: sahalliburton)
> Shalanda Boykins-Garrett
> Yang Yang (github username: nanotone)
> Jerome John
> Yoom Lam (github: yoomlam)
> Rajinder Bhanot (github: rajinderbhanot)
> Joseph Quirin
> Rutvika Gupta (github: rutvigupta-design)
> Sally Maki (github:  leikkisa)
> Anya Roltsch (github: aroltsch)
> Will Turner (github: wturne)
> Raven Tolson
> Lowell Wood (github:  lowellrex)
> Angel Gil (github: agil632)
> Brian Skeen (github: skeenb)
> Fred Allen (github: FredAllen6608)
> Joel Robinson (github: JoelRobinson-Tista)
> Tom Adams (github: tomjadams87)
> Ryan Roy
> Nikolaus Weinmeister (github: nweinmeister)
> Kavitha Krishnan
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Caseflow team
- Please provide any type of access they may have and their GitHub username. 
  > Slack and Github
  
 
## AC
*Performed by Platform team*
 - [ ] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack (if applicable)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [ ] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights

**Comment by jsgarmon** [comment]
equest Edwin Wong

**Comment by jennaouellet** [comment]
No GA or Domo access for any of these users

**Comment by jsgarmon** [comment]
No SOCKS, AWS, Pagerduty, Sentry, or Datadog access for any of these users.

**Comment by jsgarmon** [comment]
All user with Github names have been removed from the org.
