### ISSUE TITLE
[ ] 10-10CG - Introduction: Update introduction of 10-10CG

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#35807]
## High Level User Story
As an applicant, I want to be clear of the requirements and necessary preparations before I start my application. 

## Goals
Especially be clear about requirements before starting
- Veteran must be enrolled in VA HC
- Representative must prepare proper legal rep docs
- CG must live with Veteran _(this needs to be confirmed as true)_

## Acceptance Criteria

- [ ] Update entire Intro page with content specialist
- [ ] Update Intro design
- [ ] Create FE ticket

**Comment by markfallows** [comment]
I believe this has already been completed.  Can we close this one out?

**Comment by markfallows** [comment]
@markfallows and @hdjustice to do some additional research into this to confirm the goals and what research needs to be done.

**Comment by markfallows** [comment]
Caregiver requirements listed on [The Program of Comprehensive Assistance for Family Caregivers](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/#:~:text=Eligibility%20requirements%20for%20the%20Veteran&text=The%20Veteran%20has%20a%20VA,in%2Dperson%20personal%20care%20services) page.

**Caregiver Requirements**
- Must at least 18 years old and either of the following must be true:
  - Must be a spouse, son, daughter, parent, stepfamily member, or extended family member of the Veteran
  - Live full time with the Veteran, or be willing to live full time with the Veteran if designated as a family caregiver

**Veteran Requirements**
- Must have a disability rating (individual or combined) of at least 70%
- Was discharged from the U.S. military or has a date of medical discharge
- Needs at least 6 months of continuous, in-person personal care services
- Must be enrolled in VA health care (10-10EZ)

**Comment by jessicastump** [comment]
Looking at those original ticket goals - we did address those in the content of the intro page or the static page with these July updates. My vote is to close this ticket.

**Comment by hdjustice** [comment]
agreed, closing!
