### ISSUE TITLE
Business intake form for [Business or team]

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#35818]
## What is the business outcome you are trying to achieve? (required 1-2 sentences)
We would like an automated alert to notify a Veteran if their disability claim submission has failed and provide instructions for how to resolve.

## What is an overview of the notification use case? (required 3-5 sentences) 
Today, when a Veteran submits a disability claim on va.gov, most of the time the claim is successfully received and proceeds through upstream processing. However, there is no notification of failure. When for technical or other reasons, that claim submission fails, the Veteran has no way of knowing.

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
The Veteran will attempt to submit a claim via our online application. If that submission fails, then the Veteran should be notified so that they can try again.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No

## What kind of notification would this be? (required Email, Text, Not sure)
Email or text

## If you have a draft of the content you’d like to send - please upload here. Please note we collaborate with all of our users on their content to ensure it meets standards. (optional - blank) 
Template has already been created, but I can't view it:
https://notifications.va.gov/service/5bda137e-689e-4532-b3d2-2c81c0324331/templates/7e7719cb-f2c8-4856-9733-825e25f39dd8

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure)
No, but at this point, staging use only

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
vets-api claim submission

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes, We already have a notification configured for when a form526 submission succeeds. We would like to add notifications for the final time a job fails and we can call and can make that call from: EVSS::DisabilityCompensationForm::SubmitForm526#sidekiq_retries_exhausted

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
yes

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
not sure, free for vets-api i think

## What is your estimated volume of notifications per day, week, month? (optional - open space)
~50 per day

## When does this notification need to be in production? (optional - open space)
30-90 days

**Comment by bevnobev** [comment]
duplicate of #35819
