### ISSUE TITLE
Campaign landing page template: instructional call-outs

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#3582]
Add instructional call outs to campaign landing page (CLP) template to provide additional guidance to content creators.

Will involve design + content

This is a subtask of: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2839

**Comment by jenniferlee-dsva** [comment]
@Karak888 - please hold off on this subtask for now. We'll need to pick this up when it's closer to building in Drupal as a page template. Thank you!

**Comment by jenniferlee-dsva** [comment]
Ryan and I are finalizing this work.

**Comment by jenniferlee-dsva** [comment]
@rtwell - could you upload your wip design files with the guidance/content requirements call-outs in this folder?  

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates

**Comment by rtwell** [comment]
done. 

attaching PNGs here: 

## Maximal - large screen
![image](https://user-images.githubusercontent.com/12564977/77204377-fda9f980-6ac8-11ea-8fe5-1f8ef739a6e1.png)
## Maximal - small screen
![image](https://user-images.githubusercontent.com/12564977/77204427-14505080-6ac9-11ea-9550-19557e555ece.png)

**Comment by rtwell** [comment]
## Maximal - no images
![CLP-Maximal-no-images](https://user-images.githubusercontent.com/12564977/77204451-20d4a900-6ac9-11ea-9714-6d360ab9a040.png)

## Maximal - Markup
![CLP-Maximal-markup](https://user-images.githubusercontent.com/12564977/77204554-5aa5af80-6ac9-11ea-8945-7b0d029dbb4d.png)

## Minimum required - with images
![CLP-required sections](https://user-images.githubusercontent.com/12564977/77204463-25995d00-6ac9-11ea-929b-541d0ab223c6.png)

## Minimum required - no images
![CLP-required sections-no-images](https://user-images.githubusercontent.com/12564977/77204461-2500c680-6ac9-11ea-9d48-10d9b0591893.png)
