### ISSUE TITLE
[UI] Review Check-in User Flow Documentation

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35840]
# Description:
Kristen updated the user flow documentation to answer CHIP's questions within this [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1642788324195800) thread. However, she has questions about some of the error states on the VA.gov side. This ticket is to review the user flow document and let Kristen know if anything needs to be updated/changed.

# Task:
- [x ] Review [user flow document in Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [x ] Come up with list of any changes/update if necessary

# Acceptance Criteria
- [ x] Send list of updates/changes to Kristen

**Comment by niradatta1** [comment]
A note that @ytsaoca worked  mainly on the pre-check-in error messages, and have less familiarity with the day of check-in user flow. Here are some questions: 

1) Have we agreed as a team that we will lock veterans out after three failed login attempts? My understanding is that we have yet to decide. For pre-check-in, we don't tell the veteran they are locked out, but that they can call a number. However, they can still technically try to log in after three attempts. 
2) Compared to pre-check-in error message: We are seeing some inconsistent UI pattern and verbiage for the validation error when a veteran attempts less than 3 times, and 3 times or more (noted this in Sketch file too). 
3) We can create a ticket for to write an error message for the emergency contact e.g. if someone selects "no" for the update emergency contact page. We can leverage the Contact Info/NOK error message, so this should be a light lift.  We would like to confirm with engineering what we're sending out currently.

**Comment by kristenmcconnell** [comment]
For 1 and 2, I will confirm with engineering what is implemented. I would like to review your findings at today's UX sync. I'll check on 3 with engineering as well to see what is implemented, then write a ticket.

**Comment by niradatta1** [comment]
Per our UX discussion, provided feedback to @kristenmcconnell will close this out.
