### ISSUE TITLE
Update the instructions/message when canceling a booked VA appointment in VAOS. (Part 1) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#35857]
## Description
The veteran will need clear instructions on how to re-schedule their appointment. Currently, the application does not allow the user to re-schedule. The veteran can call the VA facility to reschedule their appointment or they can cancel their appointment and book a new appointment in VAOS.  

**Current Appointment Details Page**
_The user will cancel the booked appointment on this screen_
<img width="599" alt="Screen Shot 2022-01-31 at 2 39 22 PM" src="https://user-images.githubusercontent.com/90797205/151861172-bc467f87-20d0-4b21-bfe6-2a6bcc1b77d3.png">

**Current modal for canceling a booked appointment**
_After user clicks on Cancel appointment, the first modal will display_
<img width="434" alt="modal_appointment" src="https://user-images.githubusercontent.com/90797205/152184335-c694cc08-6f2b-43c6-b349-121bf5840893.png">

**Current modal for when a user cancelled the booked appointment**
_After user confirms on canceling the appointment, the second modal will display_
![Screen Shot 2022-02-03 at 12.58.56 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c875a140-8685-4ac3-bf29-4d1d07b1fb6b)

**Current Appointment Details Page**
_The appointment details screen once the user canceled the booked appointment_
<img width="513" alt="final_appt_canceled" src="https://user-images.githubusercontent.com/90797205/152184002-68a1b6c5-bb92-4890-99dc-da067004e1f6.png">

---

## Acceptance Criteria

Given the user is on the Appointment details page
When the user clicks on Cancel appointment
Then the user will receive a confirmation message on the cancellation 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#confirmation-states) 
And page design matches the [design spec](https://www.figma.com/file/d6enlZQ15NZEuJNVD64Npg/Cancelation%2FReschedule?node-id=0%3A1)

### Design Assets
[Desktop, Mobile and Tablet Design Specs ](https://www.figma.com/file/d6enlZQ15NZEuJNVD64Npg/Cancelation%2FReschedule?node-id=0%3A1)

## Definition of Done
- [ ] All acceptance criteria are met
-  The updated modal before confirming the cancellation.
-  The updated modal once the appointment has been canceled. 
-  The updated alert message on the appointment details page.
- [ ] Documentation is updated

---

**Comment by jenniemc** [comment]
Hey @outerpress , because we are using a VA web component for the alert messages, bolding cannot be done in the body of the alert text. It can however be achieve by separating out "[who] cancelled the appointment" as the title. See option 2.  Let me know your preference. 
cc: @ldelacosta @Cieramaddox 

<hr />

Option 1 
![image](https://user-images.githubusercontent.com/54327023/152813151-e68ed0b5-c029-4bbb-87a0-d66d6583820b.png)

Option 2
![image](https://user-images.githubusercontent.com/54327023/152813320-d33eb52c-6070-4ab0-8635-3ad26f6ccbaa.png)

**Comment by outerpress** [comment]
@jenniemc let's go with option 2 to keep it consistent with the alert structure. 

@Cieramaddox could you update the design file to reflect this?

Thanks!

**Comment by ldelacosta** [comment]
Validated the changes in staging. 

Clicking on cancel appointment on the appointment details page: 
![Screen Shot 2022-02-14 at 9.42.30 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/66a2d06c-9967-49ce-9d92-4c8e50d4deb0)

Modal when the appointment has been canceled: 
![Screen Shot 2022-02-14 at 9.42.53 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c386e50f-fd5d-4af8-b933-1e43835412bd)

Appointment details page when the appointment has been canceled: 
![Screen Shot 2022-02-14 at 9.43.15 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/477256dd-e480-4463-8cbd-085b430fc007)
