### ISSUE TITLE
Access for Carl Alquisola

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#35852]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other

### Your Name

Carl Alquisola

### Your Email

carlanthony.alquisola@va.gov

### Name of Your Team

Platform Spike Teams - Access Management/ Senior Software Engineer/ Adhoc

### Service(s) You Want Access To

AWS

### Desired AWS Services

Hi! 

I already have my AWS account created. 

I would need access to DynamoDB. 

Please allow me to create/delete tables and perform CRUD operations.

**Comment by jbritt1** [comment]
@department-of-veterans-affairs/operations-aws-approvers, user is requesting an increase in AWS permissions that includes manipulating DynamoDB data. @calquisola, please state what environments you would like this permission for.

**Comment by td-usds** [comment]
Awaiting input from @calquisola before approving

**Comment by calquisola** [comment]
Hi i just need this for dev environment. thank you.

**Comment by td-usds** [comment]
Approved

**Comment by jbritt1** [comment]
Gave user pretty wide access to DynamoDB service with explicit denies on anything dealing with manipulating currently existing tables there. Hopped on quick call with Carl this morning and verified he has all necessary permissions to continue his work and has no ability to do anything with currently existing tables other than see that they exist:

![image](https://user-images.githubusercontent.com/56260532/151405606-656ce257-894b-49ae-8295-2ef6466440b6.png)

**Comment by jbritt1** [comment]
Reopening. Relevant slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1643307113124759

**Comment by jbritt1** [comment]
Met with Carl on another quick zoom. The attempts being made are from the service his team is creating. I have instructed him to open a new ticket to request a service account for the service as AWS API calls won't work due to the force-mfa policy we apply (unless the service could obtain an MFA'd session somehow)
