### ISSUE TITLE
[2/3/2022] AVS Installation Training

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#35854]

**Comment by djfredvs** [comment]
Installation training complete waiting for review and video to be recorded.[https://app.zenhub.com/files/133843125/84cc16e5-ca03-4fd7-b4e1-5aa65a6f17e1/download](https://app.zenhub.com/files/133843125/84cc16e5-ca03-4fd7-b4e1-5aa65a6f17e1/download)

**Comment by djfredvs** [comment]
Working on the Recording for this training program

**Comment by jwowk** [comment]
New eta is 2/16/22

**Comment by djfredvs** [comment]
Video is complete posted to Slack for review

**Comment by djfredvs** [comment]
Updated video recording.
https://ablevets-my.sharepoint.com/:v:/p/fred_sidoti/ERwq2T4gOz9LtakmG79I1-sBABiQ62882SlzEhQYPjRgJg?e=4%3aFAxPn1&at=9
