### ISSUE TITLE
Complete mapbox version upgrade

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3585]
This issue is to complete the mapbox upgrade

**Acceptance criteria**
[ ] Run automated scans periodically 
[ ] Audit with the Lighthouse plugin to ensure web performance, accessibility, best practices, SEO, and even progressive web app support 
[ ] Run the axe-core plugin while developing new components. Many automated errors can be avoided or fixed during the development cycle.
[ ] Review internally with BE or another engineer before the BE Team
[ ] Once internally reviewed, share with the BE Review Team at the VSP (team name?)
[ ] Documentation and points of contact for any new backend dependencies
[ ] Links to important dashboards for investigating relevant issues
[ ] Request a VSA Development Review/Accessibility Audit [#3978]

**Comment by mmiddaugh** [comment]
This issue was estimated at a 13...if not a 21. We should look at ways to break the task down further, if possible.

**Comment by mmiddaugh** [comment]
@brangi please document breaking changes that occur as part of this upgrade. Thank you!

**Comment by brangi** [comment]
Mapbox release versions - https://github.com/mapbox/mapbox-sdk-js/releases

**Comment by brangi** [comment]
For sdk documentation here: https://github.com/mapbox/mapbox-sdk-js/blob/master/README.md

**Comment by mmiddaugh** [comment]
PR is pending release
