### ISSUE TITLE
Redirect Request: Spotsylvania County VA Clinic to Massaponax VA Clinic

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-team#35858]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: Unsure; H1 is already changed because facility name is already changed within VAST.

### Redirects 
Current URL  |  Redirect Destination or New URL
--- | ---
https://www.va.gov/richmond-health-care/locations/spotsylvania-county-va-clinic/ |  https://www.va.gov/richmond-health-care/locations/massaponax-va-clinic/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
Blocked pending conversations and decisions for handling name change scenarios.

**Comment by davidconlon** [comment]
@mnorthuis Why is this blocked?
This should already be done.

1. CMS detects change.
2. CMS update URL in CMS
3. CMS works with PW to implement redirect(s) as needed.
4. Public Websites Coordinate activity for redirect with CMS to execute on redirect and update of URL to minimize site errors.

Now, there may be a feedback loop we want to consider upon confirmation to the site owner via VHA Digital Media or even from the help desk themselves to say "You may want to consider making X changes to your site" but we do not know what strategies the facilities have had in place leading up to this change. (News releases, email blasts, etc)

In addition, other products such as the Facility Locator and anything dependent upon VAST data (e.g. VAOS) that needs to have this stuff be in alignment.

**Comment by mnorthuis** [comment]
@brianalloyd This redirect is ready to go. Can you please mark as urgent and pull in as soon as you can?  Thank you!

**Comment by longmd** [comment]
[PR ](https://github.com/department-of-veterans-affairs/devops/commit/1c1bbf812d17d6b18abb8574723d5483952dcee2) has been merged for this request.
