### ISSUE TITLE
Display Canceled requests - Pending View 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#35856]
## Description
As a veteran, I would like to see a section for my open appointment request(s) and a section that will display the canceled appointment request(s). Currently the VAOS application groups the pending appointments and canceled requests in one list. 

**Current Requested View:** 
<img width="530" alt="Screen Shot 2022-01-24 at 8 01 21 PM" src="https://user-images.githubusercontent.com/90797205/150890924-f53984f8-6a73-4997-af18-688395a5fdc7.png">

---
## Acceptance Criteria
Background:  the `va_online_scheduling_status_improvement` toggle is on

Given the user is on the Pending view screen 
When the user has open and canceled appointment requests
Then the user will see two categories that will display "Pending appointments" and "Canceled requests" 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/status-list-pending.md/)
And page design matches the [design spec](https://www.figma.com/file/gCjrlgjlJUwVUb5SlE8i6J/34487-surface-requested-appointments?node-id=46%3A1472) 

Given the user is on the Pending view screen 
When the user has open request(s) and no canceled request(s)
Then the user will see the open requests under "Pending appointments"
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/status-list-pending.md) 
And page design matches the [design spec](https://www.figma.com/file/gCjrlgjlJUwVUb5SlE8i6J/34487-surface-requested-appointments?node-id=46%3A1472)

Given the user is on the Pending view screen 
When the user has no open and canceled request(s)
Then the user will see "Pending appointments" with a message indicating there are no requests and instructions on how to schedule an appointment
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/status-list-pending.md) 
And page design matches the [design spec](https://www.figma.com/file/gCjrlgjlJUwVUb5SlE8i6J/34487-surface-requested-appointments?node-id=46%3A1472) 

![Screen Shot 2022-01-25 at 1.50.32 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3eab7601-6252-4ff8-b157-3cd81adc0358)

### Design Assets
[Mobile, Tablet, Desktop Concept](https://www.figma.com/file/gCjrlgjlJUwVUb5SlE8i6J/34487-surface-requested-appointments?node-id=46%3A1472)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by vbahinwillit** [comment]
Is there a design spec for this? The link aren't working.

**Comment by ldelacosta** [comment]
@vbahinwillit - Re-adding he links to the ticket. Thanks!

**Comment by ldelacosta** [comment]
Validated when a user has no open request and canceled request(s) in staging: 

![Screen Shot 2022-02-14 at 9.51.38 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/77e5e08c-7059-4d3d-bf10-6f77d109b24b)

**Comment by ldelacosta** [comment]
Validated when user has an open requests and canceled requests in staging: 

![Screen Shot 2022-02-16 at 3.57.19 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/068b3c6b-9581-4c7f-b875-3969320c3bc3)

**Comment by ldelacosta** [comment]
Validated when there are no pending requests or canceled requests in staging: 

![Screen Shot 2022-02-22 at 2.56.29 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/a6bb299d-dd4f-4351-a7a4-6a53697c6944)
