### ISSUE TITLE
Adding [Peyton Lucas] to DSVA Slack

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#35881]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Peyton Lucas to DSVA Slack workspace

Are you requesting to add an individual as a:

- Full member

Peyton Lucas - Lighthouse: Team Quokka, Software Engineer, Oddball
Access request ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33679

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [peyton.lucas@oddball.io] as a full member.

**Comment by LEHigley** [comment]
looks like they're already a member
