### ISSUE TITLE
Formation - Upgrade Foundation Dependency from v5 to v6

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#35896]
## Issue
* Dependabot recently suggested upgrading to v6 https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/733
* We have been on v5 since the existence of this repo
* We are using Foundation's Grid System in `vets-website` on a number of files as evidenced by the use of `class="row"` or `class="columns` https://get.foundation/sites/docs/grid.html
* Foundation v6 changes the Grid name from Grid to Float Grid
* Foundation v6 also recommends using their XY Grid instead of the Float Grid
* If we want to change from v5 to v6 we will need to update the location of the imported file and its name here: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/7aa93f985375434ec57686338e7e86a2fd3682a3/packages/formation/sass/core.scss#L9 since Block Grid no longer exists and Grid was renamed to Float Grid

## Related Slack Convo
* https://dsva.slack.com/archives/G01BJ3ESXL4/p1643123215378200

## Foundation Docs
* v5 - https://get.foundation/sites/docs-v5/components/grid.html
* v6 - https://get.foundation/sites/docs/grid.html

**Comment by bkjohnson** [comment]
Won't fix - we are moving to USWDS3 and their grid system and will no longer include other 3rd party CSS libraries.
