### ISSUE TITLE
'Need Help' component

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3589]
As a veteran, I want clear contact info for the help lines that I need to call so that I can resolve any issues I run into while scheduling an appointment.

AC
- [ ] 'Need Help' component shows on all VAOS pages
- [ ] Content & UI matches mocks

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/69184819-96ad1180-0ae3-11ea-9242-4fd1dbcc9172.png)

**Comment by peggygannon** [comment]
@markgreenburg @rtwell @narin 

Here's my recommended content for the Help component. (this aligns with the wording of other form Help components): 

**Need help?**
For help scheduling an appointment, or if you have questions about enrollment or eligibility, please call: 

Please change VA facility and Community Care appointments TO: 
**VA or Community Care appointments:** 

All other copy in the mockup looks good.

**Comment by narin** [comment]
@rtwell @peggygannon @markgreenburg What URL should the "leave feedback" link lead to?

**Comment by rtwell** [comment]
@lalexanderson-dsva knows this

**Comment by narin** [comment]
Separated "Leave feedback" link into a new issue: #3845
