### ISSUE TITLE
Create a base docker image for vets-api

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#359]
**User Story**
As a VSP developer I want a base docker image that includes prebuilt dependencies so that local and jenkins builds are faster.

**Acceptance Criteria**
There's a base vets-api docker image hosted on AWS ECR and vets-api is updated to use it.

**Comment by wyattwalter** [comment]
@kreek 

I added the ECR ticket as a dependency. Note that ECR cannot host public images, so you would need to be signed in via Docker to use this image in local development.

What were you thinking would be in this base image? There's some apt installs that we do in the `Dockerfile` that may add a small amount of time to builds locally, but the majority of time would be spent doing installs via bundler. Were you envisioning like a base image that would occasionally get all the deps installed at some point in time, and then local builds would just update from that? Or maybe something else entirely?

**Comment by kreek** [comment]
@wyattwalter Ya a base image with all deps installed. A test I did was moving the apt installs above the ARG and ENV setting for sidekiq enterprise, then ruby + apt installs is the [base image](https://cloud.docker.com/repository/docker/kreek/vets-api). Using that base took 1:33.99 vs 2:53.49 for ruby:2.4.5-slim-stretch and installs.

Agree that the majority of time is bundler which is why I was [asking](https://github.com/department-of-veterans-affairs/vets-api/pull/3113#issuecomment-502889783) if there's a way to have a bundle cache volume that jenkins builds could like we can for local dev? 

A private image could include sidekiq enterprise being setup, not sure how burdensome signing in to Docker is for local dev is, depends on how long the session lasts 😄

**Comment by kreek** [comment]
@wyattwalter looks like from [this article](https://blog.bigbinary.com/2018/07/25/speeding-up-docker-image-build-process-of-a-rails-application.html) the [Job Catcher](https://wiki.jenkins.io/display/JENKINS/Job+Cacher+Plugin) plugin could be used to share bundle caches.
