### ISSUE TITLE
Install Jenkins Datadog Plugin 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#35901]
To assist with SRE Operation Support we need to know the status of builds.   Datadog is the centralized logging of events and metrics to assist with automating responses to requests and events.

Setup Guidance Here:
https://plugins.jenkins.io/datadog/

We need Data collected
This plugin is collecting the following events, metrics, and service checks:

Events
Default events type
Event name	Triggered on	Default tags	Associated RATE metric
Build started	RunListener#onStarted	branch, event_type, jenkins_url, job, node, user_id	jenkins.job.started
Build aborted	RunListener#onDeleted	branch, event_type, jenkins_url, job, node, user_id	jenkins.job.aborted
Build completed	RunListener#onCompleted	branch, event_type, jenkins_url, job, node, result, user_id	jenkins.job.completed
SCM checkout	SCMListener#onCheckout	branch, event_type, jenkins_url, job, node, user_id	jenkins.scm.checkout

**Comment by jhouse-solvd** [comment]
@zachclarity - Is there anything needed from the Platform Infrastructure team on this? 

If not, I'd like to remove the "operations" label if that's okay with you.

**Comment by little-oddball** [comment]
Determined to be OBE
