### ISSUE TITLE
[Bug] Un-checking worsened condition should remove that condition from treatment facility

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#3591]
## What happened?
Discovery issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1536

526 forms were failing to submit for veterans due to an error from EVSS involving conditions being linked to treatment facilities without that condition actually being submitted in the veteran's list of disabilities.

## Steps to Reproduce
- URL: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
- Test User: User 229

1. Start a new 526 form and navigate to the page below and select "One or more of my rated conditions that have gotten worse"
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/40a5dc74-8afb-40e4-ad85-f0fe497df87b)

2. Continue through the form to the page below and select one or more Rated Disabilities
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/516437af-9b7e-4e22-abf0-8ab76931774f)

3. At the step below, select "Yes" for the first prompt and select "VA medical records" for the second
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/f4249a89-ad4e-4b5c-b841-9f7b2095b887)

4. On the next page, fill out all required fields with any information and then select one or more of the previously selected conditions
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/f156bcbc-27bf-43ac-81c7-e6cb37391180)

5. Navigate to the review step and deselect one or more of the conditions that were selected for the facility in the previous step
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/2a478aa3-9779-433b-b6d1-da5b6885d3ef)

Notice that under "Supporting evidence" and then under the "VA medical records" section will be the facility previously created, but the condition just removed will not be there. This is a false positive as the condition remains linked to this facility behind the scenes.
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/3f527439-1545-4230-b939-02a0c5bd664b)

6. Submit the application and the submission will fail
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/9a0a63ba-3620-48e6-a747-2907e5ca2a9c)

Observing the submitted JSON to vets-api will reveal that the removed condition is in fact still linked to the treatment center:
![image.png](https://images.zenhubusercontent.com/5d5ebd091325bafe068c37dc/83a17a42-2c83-494f-af1e-e7782ac47025)

## Desired behavior
The removed conditions should also be removed from the linked treatment facilities and the submission should be successful.

## Acceptance Criteria
- [ ] Conditions removed from being "worsened" are removed from linked treatment facilities
- [ ] The form submits successfully under these conditions

**Comment by Mottie** [comment]
I've been discussing a similar issue with @kevinstachura where validation messages aren't shown & related subsequent steps aren't being handled or updated properly (related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2138). For example, on the review page, all rated disabilities can be unselected with no warnings or error messages showing.

I think this is an issue with all forms, not just 526. We should either show validation messages & alert boxes, or find some way to redirect the user back to the actual form step to edit the content, then back to the review page; but this second method is probably too round-about and complex to implement.

**Comment by Mottie** [comment]
I found a fix for this issue, but it broke a bunch of unit tests; and since I'm not 100% sure if modifying the unit tests or the data would be appropriate here, the data system has very complicated & convoluted rules. I mentioned this to Nick and he and I agree that it might be better to fix this on the back-end.

<details>
<summary>Details</summary>


First change:

` src/applications/disability-benefits/all-claims/submit-transformer.js`
```diff
@ -77,7 +77,9 @@ export function transformProviderFacilities(providerFacilities) {
  */
 function getDisabilities(formData) {
   // Assumes we have only selected conditions at this point
-  const claimedConditions = formData.ratedDisabilities || [];
+  const claimedConditions = (formData.ratedDisabilities || []).filter(
+    condition => condition['view:selected'],
+  );
```
Of course,`ratedDisabilities` didn't include the `view:selected` key/value, so I had to pass the original data.

```diff
   // Depending on where this is called in the transformation flow, we have to use different key names.
   // This assumes newDisabilities is removed after it's split out into its primary and secondary counterparts.
@@ -229,7 +231,7 @@ export function transform(formConfig, form) {
       // Add POW specialIssue to new conditions
       const powDisabilities = transformRelatedDisabilities(
         clonedData.powDisabilities,
-        getClaimedConditionNames(formData),
+        getClaimedConditionNames({ ratedDisabilities, ...formData }),
       ).map(name => name.toLowerCase());
       clonedData.newDisabilities = clonedData.newDisabilities.map(d => {
         if (powDisabilities.includes(d.condition?.toLowerCase())) {
@@ -367,7 +369,7 @@ export function transform(formConfig, form) {
         'treatedDisabilityNames',
         transformRelatedDisabilities(
           facility.treatedDisabilityNames,
-          getClaimedConditionNames(formData),
+          getClaimedConditionNames({ ratedDisabilities, ...formData }),
         ),
         facility,
       ),
```

Then I discovered conditions that were associated with unemployability weren't being included:

```diff
   const claimedConditions = (formData.ratedDisabilities || []).filter(
-    condition => condition['view:selected'],
+    condition =>
+      condition['view:selected'] || condition.unemployabilityDisability,
   );
```

I had to update the `src/applications/disability-benefits/all-claims/tests/data/secondary-new-test.json` file to ensure certain fields were included

```diff
@@ -148,7 +148,7 @@
         "decisionText": "Service Connected",
         "ratingPercentage": 100,
         "disabilityActionType": "NONE",
-        "view:selected": false
+        "view:selected": true
       },
       {
         "name": "Diabetes mellitus1",
@@ -169,7 +169,8 @@
         "decisionCode": "SVCCONNCTED",
         "decisionText": "Service Connected",
         "ratingPercentage": 100,
-        "disabilityActionType": "NONE"
+        "disabilityActionType": "NONE",
+        "view:selected": true
       },
```

At this point, 2 tests were still failing. I'm not sure how to fix it. Modifying the pre-transformed data would fix the action type entries, but not fix the entries in the `treatedDisabilityNames` array. I'm getting into territory where I'm afraid I'd modify the post-transform data to make it work; but I'm not sure how this would effect how the back-end would process the data. It might make things even worse.

```bash
16 passing (2s)
2 failing

1) transform should transform secondary-new-test.json correctly:

    AssertionError: expected { Object (form526) } to deeply equal { Object (form526) }
    + expected - actual

           {
             "decisionCode": "SVCCONNCTED"
             "decisionText": "Service Connected"
             "diagnosticCode": 5238
    -        "disabilityActionType": "INCREASE"
    +        "disabilityActionType": "NONE"
             "name": "Diabetes mellitus0"
             "ratedDisabilityId": "0"
             "ratingDecisionId": "63655"
             "ratingPercentage": 100
           {
             "decisionCode": "SVCCONNCTED"
             "decisionText": "Service Connected"
             "diagnosticCode": 5238
    -        "disabilityActionType": "INCREASE"
    +        "disabilityActionType": "NONE"
             "name": "De-selected"
             "ratedDisabilityId": "1"
             "ratingDecisionId": "63655"
             "ratingPercentage": 100
         "standardClaim": false
         "vaTreatmentFacilities": [
           {
             "treatedDisabilityNames": [
    +          "Diabetes mellitus0"
    +          "De-selected"
               "knee replacement"
             ]
             "treatmentCenterAddress": {
               "city": "Bigcity"
    
    at Context.equal (src/applications/disability-benefits/all-claims/tests/submit-transformer.unit.spec.js:52:68)

2) transform should transform maximal-test.json correctly:

    AssertionError: expected { Object (form526) } to deeply equal { Object (form526) }
    + expected - actual

         "standardClaim": false
         "vaTreatmentFacilities": [
           {
             "treatedDisabilityNames": [
    +          "Diabetes mellitus0"
    +          "Diabetes mellitus1"
               "myocardial infarction (MI)"
             ]
             "treatmentCenterAddress": {
               "city": "Bigcity"
    
    at Context.equal (src/applications/disability-benefits/all-claims/tests/submit-transformer.unit.spec.js:52:68)
```
</details>

**Comment by Mottie** [comment]
I did not make any progress on this issue in sprint 16

**Comment by Mottie** [comment]
Fixed by https://github.com/department-of-veterans-affairs/vets-website/pull/12063
