### ISSUE TITLE
Research - Determine how we're submitting practitioners for CC requests

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#35923]
When a veteran is submits a CC request, are we sending the provider NPIs in Appointment.practitionerIds, or Appointment.practitioners?

**Comment by ajmagdub** [comment]
We are sending the provider NPI's in the Appointment.practitioners property. The practitioner's identifier (NPI) is contained in an identifier array within the Appointment.practitioners property which itself is an array. Currently, Vets Web is only sending one practitioner identifier to Vets API and CC, but Vets API and VAMF appear to be set up to accept more than one.

The following is an example of the practitioners property from a CC appointment request payload:    "practitioners": [
        {
            "identifier": [
                {
                    "system": "http://hl7.org/fhir/sid/us-npi",
                    "value": "1932440997"
                }
            ]
        }
    ]

**Comment by ldelacosta** [comment]
CC: @JRRoof
