### ISSUE TITLE
Implement an ICN/UUID correlation mechanism

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#3592]
## User Story or Problem Statement
How might we establish a correlation between VA ICNs and ID.me UUIDs so that the fraud detection team can run analysis on authentication events ?

## Goal
The VBA fraud detection team has mechanisms in place to detect fraudulent payment-related events (e.g. improper changes in direct deposit information). They are connected to IAM/DSLogon and have a newly implemented API with ID.me to fetch events related to an IP or user.

However, they typically query in terms of a VA user identity such as an ICN. ID.me, being external to VA, does not have a record of the user's ICN. They do have a UUID. If the fraud detection tools could map from an ICN to an ID.me UUID this would suffice. 

Users who have used ID.me authentication via SSOe will have such a correlation stored by MVI. 
At some point in the near future VA.gov sign-in will be integrated transparently with SSOe and that correlation will happen for VA.gov users.

In the meantime, users who have only ever signed in to VA.gov via ID.me, will not have such a correlation stored in MVI or any other system. VA.gov does not store that information persistently, it re-queries that mapping on each authentication event. 

*If* we need to satisfy that latter case, then we need to establish a correlation and lookup mechanism usable by the fraud detection tools.

## Alternatives
1. Store mapping from UUID to ICN in a VA database table. Provide an internal-only API for resolving one from the other. 
2. Stream authentication events to a system like Splunk that is accessible to the fraud detection tools, and document the format of such log events such that they can be queried as needed.
3. Back-populate (via an ETL process) a mapping of ICNs to UUIDs for the historical set of VA.gov users.
4. ???

## Acceptance Criteria
- [ ] Determination of whether this use case needs to be fixed separately from the SSOe integration work - i.e. does the fraud detection work need to happen right now, or potentially have a look-back period?
- [ ] If yes, pick a mechanism for implementing this.

**Comment by lkoenigsberg** [comment]
Created an associated DEPO Board issue for decision.  https://github.com/department-of-veterans-affairs/digitalservice/issues/1018

**Comment by ambikaroos** [comment]
We need to talk to the fraud detection team (Rhys/Adam) to understand their needs are. Follow up on Lisa's email.

**Comment by patrickvinograd** [comment]
The Accounts table in vets-api may also be a viable repository of this mapping - it should store a mapping from ID.me UUID to ICN.  We should verify that, then do a spike on exposing that as an internal API to the fraud detection team.

**Comment by patrickvinograd** [comment]
This is  now duplicative of https://github.com/department-of-veterans-affairs/va.gov-team/issues/4868, so closing in favor of that one which has more details about a proposed  approach.
