### ISSUE TITLE
[Design] Explore ways to help Android users know how to scan QR code

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35930]
# Description
Some early feedback from St. Louis ([Slack thread](https://dsva.slack.com/archives/C02UP02HHGX/p1643131873043200) )is that Android users are having trouble scanning the QR code. How do we solve this problem?

# Tasks
1. Gather relevant data from GA
1. Brainstorm ideas (ensure we consider amount of content)

# Acceptance Criteria
1. Make a decision on direction

# Ideas
1. Update current poster to say ' this only works with version... for androids"
2. Update current poster to include instructions for androids
3. Create a separate poster for iphone/android

**Comment by niradatta1** [comment]
@zach-park to research what version of OS/app is needed to scan QR code with camera

**Comment by niradatta1** [comment]
Background: Based on @zach-park research, Android OS8 supports use of camera to initiate QR code scan. These are Androids that came out after 2017. So any Androids prior to 2017 would require the use of a third-party QR code app. There also tends to be a tendency for Android users to hold onto their phones for longer. This means there may be more users currently holding on to phones prior to 2017. 

UX decision: Update poster to indicate to address the QR code scanning issue on Android phones.. We agreed to do this in a way with minimal visual clutter on the poster. We'll create a new iteration of the poster as a separate ticket  'cc @kristenmcconnell

**Comment by kristenmcconnell** [comment]
@niradatta1 @julieadair1 @jparker0425 We will need a UX ticket added to the backlog to actually do the poster content.

**Comment by jparker0425** [comment]
@kristenmcconnell @niradatta1 [poster change story](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/36507) has been created and in backlog.
