### ISSUE TITLE
B:[01/28/22] Align Current Text Message Templates with Messaging Template Policy

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#35937]
Text messages are broken into segments at 160 characters, which is contributing to large delays in time-sensitive communication between veterans and healthcare providers. To mitigate the issue, VEText needs to strictly enforce the 500 character limit. This is the first step in enforcing the policy to maintain timely communication. 

- [x] @chancetheoriginal will pull the current messages for @vlivshin and I to ensure they meet messaging template policy.
- [x] Edit top priority messages to below 500 characters 
- [x] Consult with leadership on message template content
- [x] Reach out to sites in batch 01 from [https://app.zenhub.com/files/133843125/c5fb7a23-f2a8-4957-ba93-adc35ff9c5bb/download](https://app.zenhub.com/files/133843125/c5fb7a23-f2a8-4957-ba93-adc35ff9c5bb/download) - include updated template
- [x] If no coordination within 24 hours, update template manually.

**Comment by lindsay-insco** [comment]
- @ahicksfearless and @vlivshin were able to cut every message template down to below 700 characters in VEText. 
- Top priority messages reduced as much as possible and pending leadership decisions, will be down below 500.
- Next steps: Give top priority message sites (~35 facilities) 1 business day to touch up message and include suggested change in email for consideration. If no response, or unwillingness to cut message, will begin to update them post-warning.
- Long term steps - continue this process by VISN 1 week at a time to reduce every template to below 500 characters and continue to express the importance at office hours.

**Comment by lindsay-insco** [comment]
@ahicksfearless & @chancetheoriginal - completed demo and will proceed accordingly.

**Comment by lindsay-insco** [comment]
@ahicksfearless & @chancetheoriginal - Create a ticket week-by-week ticket w/numbers & dependency on ticket.

**Comment by ahicksfearless** [comment]
Worked on this with @chancetheoriginal and made some good progress. Next step is to use the dashboard and identify the few that still need to be edited. Working on this as possible alongside ATO documents.
