### ISSUE TITLE
Console Services: IET - De-comission Sidekiq UI from the Vets-API

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#35939]
## User Story

_As a vets-api developer, I do not want old junk hanging around my codebase, therefor components pulled into microservices should be removed from the monolith._

## Expected Behavior

_When running vets-api the sidekiq endpoint /sidekiq should return a 404. There should be no other behavioral changes. IMPORTANT: this change should not be merged and deployed until we are ready to deploy the sidekiq UI service._

## Acceptance Criteria

- [ ] _Sidekiq UI-specific configuration is removed from vets-api._
- [ ] _Sidekiq UI-specific routing is removed from vets-api._
- [ ] _Put in a feature request if needed https://vfs.atlassian.net/wiki/spaces/AP/pages/1909293082/Feature+request+process+-+User+guide+for+Platform+teams_

**Comment by rogersarkis** [comment]
We need to go to Platform office hours to get talk about this

**Comment by ewilson-adhoc** [comment]
This was discussed in https://vfs.atlassian.net/wiki/spaces/AP/pages/2098659346/2+22+22+Office+Hours+Agenda+Notes

Action Items for our team:
- Verify that the service is identical to functionality as the old service. 
- Establish a baseline of performance against the old service and verify that the performance remains the same. 
- Verify all documentation has been updated to reflect the new service (technically, this change should be invisible from a user's point of view, so this may not be needed, good to confirm). 
- Determine who will be responsible for the long-term maintenance of this service. 
- Integrate with existing CI/CD pipelines

Once this has been completed and we've been given permission to move forward we can:
- Switch over DNS to point to the microservice (will need to pick infrastructure's brain about what this will look like)
- Remove the route within the vets-api code and deploy a version of vets-api with this service removed.

**Comment by ewilson-adhoc** [comment]
This story should be broken into smaller components and the ones that we think should be completed this sprint should be pulled into it.

**Comment by ewilson-adhoc** [comment]
Removing from this sprint -- it's an important part of this project, but can be done later.
