### ISSUE TITLE
Sort order for Request queue in VAOS not working correctly 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#35934]
## What happened?
Sort order for requested queue in VAOS not working correctly for one test user (Jacqueline.morgan@id.me) 

## Steps to Reproduce
1. Login as test user Jacqueline.morgan@id.me
2. Enter a new CC request 

**Actual Results:** The newly entered request is being lost in the requested queue
**Expected Results:** The sort order for requests should be newest on the top (descending order)

**Below is an example of how it's showing up (Sent by Marcy)**
Type of care | Requested Date | Created Date | ID
Nutrition              1/24                     1/19          74065
Primary Care        1/25                     1/19          23105
Podiatry               1/30                     1/24          74306
Podiatry                1/16                    1/10          72103
Optometry            1/30                    1/12          72116
Podiatry                 1/16                    1/12          72119

**Comment by ldelacosta** [comment]
Reviewing.

**Comment by ldelacosta** [comment]
Business Rule for the order: 
_Requests are listed in the order the request was submitted, with the newest at the top._

Tested the following:
Submitted a bunch of appointment requests on 01/28. Order was Audiology, Eye care (Ophthalmology), Move! weight management program, Pharmacy, Nutrition, Primary Care, Sleep medicine, and Social work. The UI does not properly list the order correctly. 

**Requests listed in the backend:** 
![Screen Shot 2022-02-07 at 7.58.48 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2d3f2ba5-e222-469a-ade7-c448203d3176)

**UI (highlighted in green was the requests from 01/28/2022):** 
![Screen Shot 2022-02-07 at 9.06.21 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/5eb9869f-7be6-4314-b374-1df5e4942269)

**Comment by ldelacosta** [comment]
@marcynadeau & Aarathi - this is ready for testing. Thanks!

**Comment by aarathi-poldass** [comment]
Validated the fix the request is sorted by created date newest on the top (descending order) for VAOS service patient. Please find attached a screenshot for you reference. Closing the ticket. 
![Capture](https://user-images.githubusercontent.com/69315717/154150890-00ffdeb7-d856-42f5-9235-312e93d32f25.PNG)
