### ISSUE TITLE
Contact Center Review for VAOS - Homepage refresh & sustainment

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#35952]
# Request the Contact Center Review 

## Description
VA Online Scheduling - schedule and manage health appointments

### Launch Date
n/a - catching up on prior updates, cleaning up screenshots, and reorganizing

### Version Number
Version 01/24/2022

### Product Guide
[vaos-product-guide-01242022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7938206/vaos-product-guide-01242022.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by laurenernest** [comment]
Tagging @JRRoof and @ldelacosta from my team who will likely take on any follow-up coordination.

**Comment by starlow00** [comment]
Hi @laurenernest . I've attached my draft here. Everything looks good; I just added a cover page. One area you'll want to check are the links to the error examples at the end document, as most of them are 404s (see notes). Share your copy with me once those are set and I'll share it with VEO call center. Sent draft via Slack.

**Comment by laurenernest** [comment]
Uploading draft for records
[vaos-product-guide-SRT-01242022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7946237/vaos-product-guide-SRT-01242022.docx)

**Comment by starlow00** [comment]
Hi @laurenernest. Just following up on this so I can send to VEO.

**Comment by ldelacosta** [comment]
Hi @starlow00 - @JRRoof and I will work on this item. Thanks.

**Comment by starlow00** [comment]
Hi @laurenernest and @JRRoof. Just checking in to see if you have a final draft I can share with VEO. Thanks!

**Comment by ldelacosta** [comment]
@starlow00 - I will send it to you by tomorrow. Thanks.

**Comment by ldelacosta** [comment]
@starlow00 - Please see document attached. 
[vaos-product-guide-SRT-02082022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8188285/vaos-product-guide-SRT-02082022.docx)

Lauren E. is no longer part of the VAOS team. Any questions, please reach out to @JRRoof or myself.

Thanks,
Leah

**Comment by starlow00** [comment]
Great, thanks @ldelacosta

**Comment by starlow00** [comment]
Shared copy with VEO, awaiting response

**Comment by starlow00** [comment]
VEO has no objections. Document attached, closing ticket 
[VAOS-product-guide-020822.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8248542/VAOS-product-guide-020822.docx)
