### ISSUE TITLE
Conduct data discovery to understand where the data sits and what systems house the data we need

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#35965]
Acceptance Criteria:
- [ ] Documented details of enrollment system
- [ ] Mapped external and internal dependencies
- [ ] Met with technical point of contact for enrollment system and/or Informatics division (DEPENDENCY: Tarsha to give us contact name by Thursday 1/27 COB)

**Comment by ashleybcastillo** [comment]
-Documented details of enrollment system
- Mapped external and internal dependencies

**Comment by JordanSWhite** [comment]
We started a data discovery doc and thought through options, but since we don't have points of contact yet, the team thought through options (given the information currently available).

**Comment by tameracorson** [comment]
Current link to work in progress https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/tech/options-for-enrollment-system-data.md
