### ISSUE TITLE
Prepare for user research by creating the documentation needed to conduct research

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#35967]
Acceptance Criteria:
- [x] Drafted research plan and conversation guide (to be updated as stimuli evolves)
- [x] Reviewed and edited by internal team
- [x] Shared with VA-PO
- [x] Reviewed and approved by research manager

**Comment by JordanSWhite** [comment]
Will be assigned to James Lewis

**Comment by JordanSWhite** [comment]
Hey @jamesldesign I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/1095b-tax-form-61e19735167b2500170b2146/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by tameracorson** [comment]
Link to draft conversation guide in Box https://mostudio.app.box.com/file/913875488731?s=q2mfid2n0otqda8jmi6uzdrtxtapuizp

**Comment by jamesldesign** [comment]
Available to review here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/1095b-tax-form/research
