### ISSUE TITLE
Draft prioritized backlog for MVP and post-MVP enhancements

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#35971]
Acceptance Criteria:
- [x] Wrote initial MVP and post-MVP stories
- [x] Prioritized stories in Zenhub backlog

**Comment by JordanSWhite** [comment]
Will be assigned to Ashley

**Comment by ashleycastillo** [comment]
Mural: https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1643907581165/b80fb9dbbef9a6beb4af59cbcfba076830226051?sender=u64d6a3de6070c833f88e7826
