### ISSUE TITLE
[UX] SPIKE - Training Documents for Check In Experience

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#35988]
## Description
We need to provide documentation that outlines each possible workflow in the CIE for the staff to use as a resource to ensure that they feel confident CIE is working the way it should.  For example, show the workflow for when a patient needs an insurance verification using screenshots and explanations.

Consider creating a deck that can be provided to clinic staff and posted to github for internal reference.  Deck should accessible and editable.  

# Tasks
1.  Determine where to keep this documentation.
2. Determine who should have editing access.

**Comment by kristenmcconnell** [comment]
Met with CHIP this morning. 
- Each team will oversee their own error/text message documentation on GitHub, but we will cross-link to each other's documentation. This GitHub page will be the [overview page for all of check-in and pre-check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md). 
- @hortonio is checking with the VeText team to discuss their documentation source of truth. He will share the outcome. Hopefully, we will be able to link to it from the overview page listed above. 
  - For now, Rob Durkin shared the VeText messages, so I will be able to update the user flow Sketch document and product guides.

Documentation for staff will be in the product guides. These GitHub sources of truth is where we will copy text/error messages from for the product guides.

**Comment by Hortonio** [comment]
@kristenmcconnell The VEText team created a Github repo and readme link for documenting messaging: https://github.com/department-of-veterans-affairs/vetext-docs/blob/master/README.md

There is not content yet but you can use the link for the current messaging hub.

**Comment by kristenmcconnell** [comment]
Thank you. I will add that to the messaging hub.
