### ISSUE TITLE
A11y documentation audit: Review Alert Boxes component documentation

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35995]
## Description
We want to audit our accessibility documentation on design.va.gov to make sure that it is up-to-date with current accessibility guidelines.

For this ticket, we need to review the [accessibility guidelines for the Alert Boxes component](https://design.va.gov/components/alertboxes#accessibility-considerations) on design.va.gov and provide any updates that need to be made to the existing documentation as a comment on this ticket.

## Details
Just for reference, here are some useful links:
[Platform accessibility standards](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1777893393/WCAG+2.1+success+criteria+and+foundational+testing)
[VFS Team accessibility responsibilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/roles-and-responsibilities/accessibility.md#accessibility)
[VA.gov experience standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
VSP WCAG 2.1 Presentations:
[VSP WCAG2.1 Foundational Testing Redux](https://app.zenhub.com/files/133843125/368da85e-7f1f-4332-8ccb-6808e52a8a51/download)
[VSP WCAG2.1 New Success Criteria](https://app.zenhub.com/files/133843125/5475fd9b-9d2e-4a6a-901f-97682664eb33/download)

## Acceptance Criteria
- [ ] Review accessibility guidelines on the following pages of design.va.gov:
    - [ ] https://design.va.gov/components/alertboxes#accessibility-considerations
- [ ] Make sure accessibility guidelines match the performance of the component in Storybook
- [ ] Add notes on any necessary updates as a comment on this ticket
- [ ] Ping Katy, Carol, and Natalie for review

**Comment by CourtneyChambers77** [comment]
The alert component messages are to communicate information to our users. It is used to display a message to the user that attracts with the user’s attention. Ensure focus is received to communicate the message without interrupting the user’s current task. Use the ARIA role="alert" is equivalent to aria-live="assertive" to inform assistive technologies of a time-sensitive and important message that isn’t interactive. If the message is interactive, use the alertdialog role instead. Use a close button, containing an ARIA label of aria-label="close", and the icon has aria-hidden="true" so it is ignored by assistive technologies. Don’t visually hide alert messages on the page and then make them visible when they are needed. When using the tab key is used to move focus to the close button within the notification and the Space key or Enter key activate the button to close the notification. Users of older assistive technologies may still be able to perceive the alert messages even if they are not currently applicable.

**Comment by k80bowman** [comment]
This looks good, thank you!
