### ISSUE TITLE
[AXE-CORE]: Facility Locator - Provider Detail page has an UL that needs to be nested properly

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#360]
## Issue
The Community Care provider detail views have some nested unordered lists that are not wrapped in list items. The [Chrome aXe plugin](https://deque.com/axe) is reporting a mid-level error. Screenshot attached below.

## Acceptance Criteria
* As a tester, I do not want to see the aXe error reported on future scans
* As a user, I do not want the visual design to change

## Environment
* MacOS Mojave
* Chrome latest
* [Chrome aXe plugin](https://deque.com/axe)
* https://staging.va.gov/find-locations/provider/ccp_1851813299 (example provider)

## Steps to Recreate
1. Enter `https://staging.va.gov/find-locations/` in browser
2. Enter `Salt Lake City` in the first input area
3. Select `Community Care` from the second dropdown
4. Enter `nurse practitioner` in the third input (typeahead)
5. Press Search button
6. Click on one of the results
7. Run the aXe scan from dev tools and verify the error exists

## Possible Fixes (optional)
Wrapping the `<ul>` in an `<li>` will clear the error. Some CSS may be in order to avoid double list item bullet points.

## WCAG or Vendor Guidance (optional)
* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

---
![Screen Shot 2019-06-21 at 9 58 23 AM](https://user-images.githubusercontent.com/934879/59932071-053e5400-940c-11e9-8be4-5dccff925625.png)

**Comment by Karak888** [comment]
Hi @kelsonic I know you have some facility locator tickets in progress and in validate but we need to be careful at this point about making any changes without client approval.  Thanks!  

@jenniferlee-dsva

**Comment by kelsonic** [comment]
Going to unassign myself from this for now then, thanks @Karak888! :)

**Comment by Karak888** [comment]
@1Copenut is this still something we need to handle in the near future? Thanks!

**Comment by mmiddaugh** [comment]
This is no longer an issue as the detail pages have been removed from Community care results.
