### ISSUE TITLE
A11y documentation audit: Review Sidenav component documentation

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36003]
## Description
We want to audit our accessibility documentation on design.va.gov to make sure that it is up-to-date with current accessibility guidelines.

For this ticket, we need to review the [accessibility guidelines for the Sidenav component](https://design.va.gov/components/sidenav#accessibility-considerations) on design.va.gov and provide any updates that need to be made to the existing documentation as a comment on this ticket.

## Details
Just for reference, here are some useful links:
[Platform accessibility standards](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1777893393/WCAG+2.1+success+criteria+and+foundational+testing)
[VFS Team accessibility responsibilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/roles-and-responsibilities/accessibility.md#accessibility)
[VA.gov experience standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
VSP WCAG 2.1 Presentations:
[VSP WCAG2.1 Foundational Testing Redux](https://app.zenhub.com/files/133843125/368da85e-7f1f-4332-8ccb-6808e52a8a51/download)
[VSP WCAG2.1 New Success Criteria](https://app.zenhub.com/files/133843125/5475fd9b-9d2e-4a6a-901f-97682664eb33/download)

## Acceptance Criteria
- [ ] Review accessibility guidelines on the following pages of design.va.gov:
    - [ ] https://design.va.gov/components/sidenav#accessibility-considerations
- [ ] Make sure accessibility guidelines match the performance of the component in Storybook
- [ ] Add notes on any necessary updates as a comment on this ticket
- [ ] Ping Katy, Carol, and Natalie for review

**Comment by CourtneyChambers77** [comment]
@pdavies88 Please confirm the URL is the one we are using https://60f9b557105290003b387cd5-qhcjdudpcs.chromatic.com/iframe.html?id=components-date--default&viewMode=story - This is what I am getting https://images.zenhubusercontent.com/133843125/dcbb43b9-c86e-4675-a8b6-2cb2fce6671f/jaws_date2.mp4

**Comment by pdavies88** [comment]
@CourtneyChambers77 the most link is this: https://60f9b557105290003b387cd5-kdzjshpbzk.chromatic.com/?path=/docs/components-va-date--default

**Comment by CourtneyChambers77** [comment]
Some accessibility questions should there be a hover state on the side nav menu item current section (its active), but should this change when hovering on the current section? Can developers add in additional sub nav items into this side nav element, or will that be added in as a different ticket?

**Comment by k80bowman** [comment]
@CourtneyChambers77 are these questions things that you would add to the documentation on this page? https://design.va.gov/components/sidenav#accessibility-considerations

**Comment by k80bowman** [comment]
Thank you @CourtneyChambers77, this is fine. Closing.
