### ISSUE TITLE
Make all widgets lazily load from S3 bucket directly, rather than through reverse proxy

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#36018]
### Overview
Currently, all lazily loaded widgets hit the reverse proxy which then hits the S3 bucket; it would be nice if the widgets loaded directly from the S3 bucket. A [previous attempt](https://docs.google.com/document/d/1W_O-tJ8st02xWjrs-cnRKIBZXzx2PjQaGO2b04t8C60/edit?usp=sharing) was made to fix this issue, but was not successful.

### Definition of done
- [ ] all widgets load directly from S3

**Comment by laineymajor** [comment]
Closing as we have tried on 3 different occasions, but unable to execute.
