### ISSUE TITLE
Display correct facility information on appointment list page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#3602]
The data we get back from the appointment service contains a facility id and a clinic id. VAOS uses `facilityId` to mean either the 3 digit system id or the full 5 digit id. In this case, it's the former, which means that we need more information than the id to figure out the location of the appt.

The legacy app uses a bolted-on custom text solution, where in VATS you configure the facility name based on combinations of facility and clinic id. This is really brittle and not something we should perpetuate.

The solution for us is to get the full facility id based on the system and clinic id. There is a service that will give us all the clinics for a system: https://veteran.apps.va.gov/cdw/v2/facilities/442/clinics?pageSize=0. We could use this to fetch all the clinics for the registered systems and then use that list to find the full institution code. Then we can send that to the facilities api to get the real address.

**Comment by jbalboni** [comment]
cc @markgreenburg

**Comment by saneshark** [comment]
@jbalboni how "required" is this change? Lets talk through this before the holidays and see if we can get on the same page here. It looks like relatively low level of effort though.

**Comment by jbalboni** [comment]
@saneshark I would say it's pretty important. The location information for confirmed appointments is pretty bad currently and this unlocks a lot of options for making it better.

**Comment by kreek** [comment]
@jbalboni using https://veteran.apps.va.gov/cdw/v2/facilities/442/clinics?pageSize=0 as an example the first record is 
```json
{
	"locationSID": 43120,
	"locationIEN": "16",
	"facilityId": "442",
	"locationType": "CLINIC",
	"locationName": "CHY LAB OUTPATIENT-X",
	"primaryStopCode": 674,
	"primaryStopCodeName": "ADMIN PAT ACTIVTIES (MASNONCT)",
	"secondaryStopCode": 108,
	"secondaryStopCodeName": "LABORATORY",
	"institutionSID": 561596,
	"institutionIEN": "442",
	"institutionName": "CHEYENNE VA MEDICAL",
	"institutionCode": "442",
	"medicalService": "MEDICINE",
	"appointmentLength": 15,
	"variableAppointmentLength": true,
	"directSchedulingPatient": false,
	"displayAppointment": true,
	"sta6aid": "442",
	"vaStationName": "Cheyenne VA Medical Center",
	"etag": "e045c932017f790ed306c5da00993beeaf56b3b694bfd863bfadb7ee237df902"
}
```
The `institutionCode` field is also the facilityId (442, aka the systemId) what field, or combination of fields, is the full institution code to send to the facilities api for the real address?

**Comment by jbalboni** [comment]
@kreek `institutionCode` or `sta6aid` is the id we care about. If you search through the data from that service for `442GD`, you'll see one where those fields are different from `facilityId`. 442 is both a system id and also a valid institution code, so there are some clinics where that is the correct id.
