### ISSUE TITLE
COE Punch List

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36022]
- Let's ensure that the staging env matches the mockups
- Join FE (Jerek)
- Kelli's emails
- Include the reference number (ask Kelli for number schema)

**Comment by sporeboy** [comment]
COE reference numbers added to "status" alert boxes on the following screens:

- Your COE Auto screen
- Your COE General Pending
- Your COE Pending/Downloads
- Your COE Pending/Uploads Requested
- Your COE Pending/Uploads Requested Submit
- Your COE Pending/Uploads Requested Success
- Your COE Pending/Uploads Requested Connection Error
- Your COE Pending/Uploads Requested File Size Error
- Your COE Pending/Uploads Requested File Type Error
- Your COE Denied
- 26-1880 Introduction Signed-in Available COE
- 26-1880 Introduction Signed-in Auto COE
- 26-1880 Introduction Signed-in Pending COE
- 26-1880 Introduction Signed-in Pending/Upload
- 26-1880 Introduction Signed-in Denied
- 26-1880 Confirmation

Screens start here: [(Link to UXPin screens)](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139511607)
