### ISSUE TITLE
Documentation Mapping (Table of Contents)

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#3603]
## User Story or Problem Statement
As a _____, I need _____ so I can _____.
As a new member of the Backend Tools team, I need a one pager (table of contents) that links me to all the relevant documents that I need so I can be be more productive in finding information across the different repos.

## Goal
To create a one page document that is broken out into sections that assists us as a new team in finding important information that is dispersed across different repos.

## Acceptance Criteria
- [ ] Anna Reviewed Doc
- [ ] Bill Reviewed Doc
- [ ] Johnny Reviewed Doc
- [ ] Keifer Reviewed Doc
- [ ] Travis Reviewed Doc
- [x] Lindsey Reviewed Doc
- [ ]A table of contents is created and stored is a centralized location that links to any and all of the relevant  documents or practice areas.

**Comment by annaswims** [comment]
There's room for improvement, but this is a start https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/README.md

**Comment by alexpappasoddball** [comment]
@annaswims @jholton @thilton-oddball @omgitsbillryan @kfrz @LindseySaari 
In an effort to make sure we have what we need from this, can each one of you review the README.md file that Anna linked to see if there are any gaps and make the necessary changes you see fit.  

Once you have reviewed it, please check the box in the acceptance criteria under your name so we know everyone has reviewed it.
