### ISSUE TITLE
va-accordion does not open/close on IE11

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#36046]
## Issue Description

`va-accordion` does not open/close on IE11

This happens whether clicking or selecting using keyboard navigation.

IE11:
![20220126_21_14_33_internet explorer_11.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/4009f14a-d917-4952-a1d8-e96929d23692)

## Acceptance Criteria
- [ ] va-accordion should open/close on all supported browsers

**Comment by xiongjaneg** [comment]
On [Escanaba Vet Center](https://prod.cms.va.gov/help/va-medical-centers-vamcs/about-events-content-for-vamcs/how-to-edit-an-existing-event) (and other Vet Center pages which have these standard accordions), the accordions are collapsed to start with, click once to expand them, but it appears to take four clicks to collapse them again.
<img width="719" alt="Screen Shot 2022-01-26 at 3 33 04 PM" src="https://user-images.githubusercontent.com/73648238/151250602-aa4aa2ff-b4e2-4be3-b281-0788a1f11461.png">

**Comment by andresriveratoro** [comment]
Using https://www.va.gov/health-care/about-va-health-benefits/ for testing:

Safari 9 - Accordions are opened on page load. Unable to toggle open/close state.
Safari 10 - Accordions are opened on page load. Unable to open, but icon changes.
Safari 11 - Accordions are closed on page load. Open/close toggle works.

**Comment by kevwalsh** [comment]
There's a report from one user that on the preview server (eg [Dallas Vet Center](http://preview-prod.vfs.va.gov/preview?nodeId=3859)), accordions are not rendering at all.

**Comment by k80bowman** [comment]
@xiongjaneg and @kevwalsh just to get a sense of the urgency here, is this issue blocking anything on your end?

**Comment by pdavies88** [comment]
Per Browser Support Policy: https://depo-platform-documentation.scrollhelp.site/developer-docs/Browser-Support-Policy.1847951366.html

As of today versions are:
- Firefox: 96 and 95
- Chrome: 97 and 96
- Edge: 97 and 96
- Safari: 15 and 14
- IE11

@kevwalsh and @xiongjaneg we are looking into the issue regarding IE11, however we were unable to replicate on this issue on the other supported browsers. Do you happen to know the versions of the browsers that your users were testing on when they encountered the issues you reported?

**Comment by xiongjaneg** [comment]
The IE accordion bug I found was on the version on 1VA-General Desktop virtual desktop. I don't see this as a blocker as the workaround is to use a different and modern browser. However, we have gotten reports of one or two Vet Centers still using IE. I would assume their work computers have an alternate browser.
<img width="387" alt="Screen Shot 2022-01-27 at 10 27 00 AM" src="https://user-images.githubusercontent.com/73648238/151406955-7ef37b5b-9fd8-4fc5-9e19-1183ed2b27e5.png">
