### ISSUE TITLE
[Drupal] Create landing page for "Find a VA Form" as a draft in Drupal

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#3604]
The page itself contains quite a bit of content, most of which should be managed by the content team via Drupal. If not, content editors would have to go through an engineer to make any content adjustments, which is not ideal. So, we should create this page from Drupal, with a React widget added for the gray box area containing the search input and search results. This page should be created as a draft, so that we can see our widget render within the content without impacting production.

**Comment by ncksllvn** [comment]
@jenniferlee-dsva Are there any concerns with creating the page for Find a VA Form as a Drupal draft? We can also create it first on GitHub, but then we'll sort of have to do the work twice - first in Markdown on GitHub, then from Drupal.

**Comment by jenniferlee-dsva** [comment]
Per slack convos, we will build the content in Drupal as draft; and build the dynamic search/results funcationality on GH (and include the blue top task card content in the REACT for now.)  

When those top task card components on the the Pittsburgh site become available on non-VAMC pages, we can move that content into Drupal. 

Thx @ncksllvn

**Comment by ncksllvn** [comment]
I created this page in Drupal at `https://prod.cms.va.gov/find-va-forms`. It's also editable using its node ID at `https://prod.cms.va.gov/node/2352`. 

@kelsonic there isn't a great way to work with this page right now, because it's a draft in Drupal production. If we create it in Drupal Dev, it'll eventually be overwritten as the data is synced from Prod downwards. I think the easiest way is to just copy the [Drupal data structure](https://app.zenhub.com/files/133843125/e7361fa8-a6d2-4878-96e4-fc92be49d8ff/download) and paste it into your `vets-website/.cache/localhost/pages.json`. It'll be lost next time you pull Drupal though, so you'll have to paste it again.

**Comment by ncksllvn** [comment]
Here's the preview - http://preview-prod.vfs.va.gov/preview?nodeId=2352 - 

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/5ae02129-58e5-4f40-b1ea-dc3c5f7ed9d2)

Not the prettiest page in the world right now, but enough to get us started.

**Comment by ncksllvn** [comment]
@Karak888 We'll definitely have to adjust the content for this page via Drupal as we go forward, but we have a start. I think we can close this :smile:

**Comment by Karak888** [comment]
thanks @ncksllvn !

**Comment by jenniferlee-dsva** [comment]
@Karak888 I am reopening this issue and assigning to @RLHecht to do a copycheck and update any content per the copydeck here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-slp-conversion-paths-110519.docx

Randi - Nick has built a draft of this page in Drupal. Could you review and update the content based on the copydeck linked above? Please also be sure to look at the search results table headers, too. (If you do a fake search, results will display.) 

Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=2352 

Unassigning Nick and Kelson for now.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I'm having trouble finding some of the text that needs to be updated in the actual Drupal page. There is text in the preview but I can't seem to find it when I'm in the actual page in Drupal prod. I also can't see how to edit the text for the search results. When I did a fake search I got an error message. @ncksllvn Would you be able to help me with this?

**Comment by jenniferlee-dsva** [comment]
@RLHecht - Some of the content on this page live inside the REACT component (like the search widget and the top task cards, I believe). So that might be the source of not seeing some text in Drupal AX. 

Nick or Kelson would be able to provide text update support for things inside the REACT component. Just FYSA Kelson is on deadline for an upcoming downtime messaging banner, so I'd like to make sure that gets priority first. 

Also, not sure if you've been following other tickets - We're launching without the new "Related to" and "Available online" data fields, as they're not ready in Kevin Reid's database. GH having a lot of problems with file uploads, so I will slack you the screenshot I can't seem to add here.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I reviewed the text on the page and added the H2 and copy that were in the copy deck. @kelsonic made the update to the text that was in the widget, which he did in a separate ticket but is referenced above. Let me know if there is any more I need to do for this page. @Karak888
