### ISSUE TITLE
User Survey Request for Virtual Agent Chatbot 

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#36055]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
Pilot a virtual agent chatbot for veterans to interact with and get answers to their questions.

### Launch Date
February 28, 2022

### Staging URLs
https://staging.va.gov/virtual-agent-study/

### Production URLs
http://www.va.gov/contact-us/virtual-agent/

### Request

Replace the questions on our current survey with the following from the PRA approved question bank, in this order. The bold and italicized text are just notes and refer to the line on the Excel spreadsheet and shouldn't be included in the survey.

**_[Line 181]_** Did you find what you were looking for today? 

**_[Line 230]_** What are you trying to do on VA.gov today? 

**_[Line 22]_** Which of the following describes you? 

**_[Line 184]_** Please select your age range. 

**_[Line 281]_** How did this interaction change your trust in Veteran Affairs? 

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by jwoodman5** [comment]
Thank you for submitting this request. We are in the middle of relocating the Feedback button on staging and will work in this request around mid next week, after that is done. I will keep you updated.

**Comment by ianpsant** [comment]
Hi @jwoodman5, just checking to see how the Feedback button relocation is going and the status of this ticket. We've received our production URL from IA which will be **http://www.va.gov/contact-us/virtual-agent/**.

How will that work for placement of the Medallia survey (with our updated questions) in production? Do you need the page live or can it be worked out behind the scenes before we launch the page?

**Comment by jwoodman5** [comment]
@ianpsant The feedback button is a couple of weeks delayed. We will hopefully be testing on staging by later this week, but we are still up to several weeks out from production. Your survey with updated questions should be available on staging at some point next week. 

Unless you have an exact copy of prod (after the survey changes have been pushed), I don't think the survey would fire correctly. Hope that helps.

**Comment by jwoodman5** [comment]
@ianpsant I got an update today that we should be live on staging next Wed., the 16th. I'll let you know when I get confirmation.

**Comment by jwoodman5** [comment]
@aubreyarcangel This is the new custom survey we talked about. (staging) URL is in description and here (https://staging.va.gov/virtual-agent-study/). Staging survey # is 24. We are clear to add on staging only. Thanks! 

cc: @ianpsant

**Comment by jwoodman5** [comment]
@ianpsant Happy Friday! We are live on staging with your custom survey. I tested it out and all looks good, but please do the same and let us know if you have any questions or concerns. We will wait to hear from you about your production release before moving this to prod. Thanks.

**Comment by ianpsant** [comment]
@jwoodman5 Happy Friday! I've reviewed with Luciana in staging and we think it looks good! We won't be flipping the content switch to publish our prod page (http://www.va.gov/contact-us/virtual-agent/) until 2/28 2pm (if all goes to plan). Would we be able to coordinate the release of the survey into prod around that time?

**Comment by ianpsant** [comment]
@aubreyarcangel @jwoodman5 During our Go / No Go meeting for the Chatbot, we noticed a typo in our Medallia survey. On our last question we say Veteran Affairs instead of Veterans Affairs (no 's'). Would it be possibe to have this be corrected for our production release?

**Comment by jwoodman5** [comment]
@ianpsant This request has been submitted to the Medallia team. I will let you know when it's complete, which should be today or tomorrow.

**Comment by jwoodman5** [comment]
@ianpsant The question was updated. Please confirm and let us know if you need anything else. Thanks.

cc: @aubreyarcangel

**Comment by jwoodman5** [comment]
Production survey is live and looks good. Closing.
