### ISSUE TITLE
[Front-End] Create a prototype for the React widget

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#3605]
The gray box area containing the search input and the search results will be a React widget, containing its own actions and reducer(s), that will be rendered from the `static-pages` bundle entry like our other widgets. 

A few key points - 

1. In the beginning, we can assume that it's okay to just load up all of the forms data into the memory, and handle queries purely from the client-side. This may change later if we discovery that the response payload is very large, but I think it's okay for now.
1. We should develop this first without hitting the API, because that API needs some work too in order to be exposed to the browser. So, we should create an action creator as if it hits an API that dispatches results asynchronously, but really, it's just leveraging a static JSON file that I'll attach to this ticket.
1. We should determine if we need to work with the URL at all - as in, do searches need to be bookmark-able like the Facility Locator? My gut says no, but this will likely be a defining point for its architecture. 
1. We should also include the blue boxes as part of this widget, because there isn't a Drupal content model for this yet. Eventually, this will likely be removed from the widget in exchange for a content model from Drupal.

**Comment by ncksllvn** [comment]
Response JSON from `https://dev-api.va.gov/services/va_forms/v0/forms`:

[va_forms.json.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/3870190/va_forms.json.txt)

**Comment by Karak888** [comment]
foundation prototype to start.

**Comment by ncksllvn** [comment]
@jenniferlee-dsva Should search results for this be bookmark-able? As in, after a user searches for a form with title `disability`, should the URL update to `www.va.gov/find-va-form?q=disability`, or something like that?

**Comment by ncksllvn** [comment]
This work is being done in the connected PR, but I chunked out part of this and created a follow-up ticket for the search behavior - https://github.com/department-of-veterans-affairs/va.gov-team/issues/3701.

**Comment by ncksllvn** [comment]
Alrighty, we have a start on the Find VA Forms page! The draft is viewable here - http://preview-prod.vfs.va.gov/preview?nodeId=2352.

CC: @jenniferlee-dsva

**Comment by Karak888** [comment]
perfect @ncksllvn I am moving to close this one, thanks!
