### ISSUE TITLE
Access for Pavanjit Hothi

### ISSUE THREAD

**Issue by pavanhothi** [department-of-veterans-affairs/va.gov-team#36062]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Pavanjit Hothi

### Your Email

pavan.hothi@oddball.io

### Name of Your Team

VSP Analytics

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1MBb813RpseVgDQxrMo2+LC+q2ul4ODkZK6Zy4pHPf0kzuQkW7DEMR1Vqvd4NoLntJ9Px3eftEXwLJSj0wNB9hzejz3xnC4zxFQzD8wujU1Wr6OO47ayY6Nr+iiXVhMvQBDd2cfI1G2Wopj715EPZCmkQIt9jZTedmruYVvoNBqbxf62YIxF6LILZLiHoT5zHvaKun22xHSxjYLsSd63Goj74WS1sPyrVMLBBaiPWihEr2Rc+w113DGm8v6hRdJ/pH4FWE0lLz0mAlxlIZHs6ZeokUmbQe4rX5HZhMRBljUbVgjTjmrIZBfjEYKjAD6giAKRKvTrmKY75KLqcy3kxAlWaLBlnEfqG4Saxm6AXZijH9x714LMpIJ0+ZXJvvnOi3r228qY8uDAxgzugWz4DeZvkNJJZCGBvUalG5GOfOnzMC+IWFXXET5rVkemVjB2XJi6oDozOf1rSiEaCavhpOrtOeI4ZHy9waSUuCEXVT6ZLkhJty1lntf1FpmpXVwc= pavanhothi1@DESKTOP-JR4H4AN

**Comment by mleclerc00** [comment]
Hello @pavanhothi 

What you provided for ssh key looks like a fingerprint. Can you please update the request with the contents of your public key (.pub) in the `~/.ssh` directory

Thanks

**Comment by pavanhothi** [comment]
Hello, updated the request with the correct public ssh key.

**Comment by mleclerc00** [comment]
@pavanhothi 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
