### ISSUE TITLE
Access for David Lennon

### ISSUE THREAD

**Issue by dlennon-va** [department-of-veterans-affairs/va.gov-team#36067]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

David Lennon

### Your Email

david.lennon@libertyits.com

### Name of Your Team

Lighthouse - Matsumoto, Liberty IT Solutions

### Service(s) You Want Access To

AWS

### Desired AWS Services

S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house. This is required for Production support of the Vets-APIs that my team supports. Model permissions after Cris Shupp if possible.

**Comment by mleclerc00** [comment]
### For AWS Access

User: David Lennon
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers

**Comment by dlennon-va** [comment]
Are there any updates here? Is there something I need to do in order for this progress? @mleclerc00

**Comment by td-usds** [comment]
Approved

**Comment by jbritt1** [comment]
User has no reachable Slack profile to deliver credentials...

**Comment by jbritt1** [comment]
Is there another method I should use to deliver first-time login credentials?

**Comment by jbritt1** [comment]
First-time login credentials passed to user at this time.
