### ISSUE TITLE
[Analytics] Determine and implement Google Analytics for React widget

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#3606]
We'll need Google Analytics added into our React widget to capture key events, so that we know how our widget is being used. We may also want to record clicks to download forms, so that we know what forms are most popular.

We also need Google Analytics added to the links on the page content (outside of the REACT widget). The primary purpose of this MVP is to increase conversions to digital tools, so we definitely want to track clicks not just to forms but to our digital products via page links. [EDIT: JL]

This might be a little premature right now, because we haven't started the FE implementation yet.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - thank you for creating this ticket! I added an additional criteria ^ for GA tracking. @Karak888  for awareness: this ticket will have to get into the analytics team queue.

**Comment by Karak888** [comment]
@jenniferlee-dsva @ncksllvn I will fill out a analytics request with Nedie and Joanne.

**Comment by jenniferlee-dsva** [comment]
@Karak888 just providing more info: there will be 2 things for forms mvp and analytics. 

1/ one is as described above for the search page: REACT component AND the links in the body content. 

2/ second is analytics for the form 'master detail' landing pages. this 2nd part isn't ready yet, bc lw is still working on finishing the content and we haven't started building these pages yet in drupal. 

Just fyi - so they can think about how they want to track and ticket this work.

**Comment by ncksllvn** [comment]
@jenniferlee-dsva Should we keep this ticket scoped to just the search page? I'm not completely in the loop on the master detail landing pages, and I'm not sure if we want that to hold this ticket/launch up because of that.

**Comment by ncksllvn** [comment]
I'm not sure if it was done already or not, but I submitted a request to the analytics team to define the analytics requirements for this page. That ticket is here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/4458.

**Comment by ncksllvn** [comment]
We've started coordinating on this w/VSP Analytics, so I'm gonna go ahead and move this into Ready w/the blocked label

**Comment by Karak888** [comment]
@ncksllvn I agree with you that we should have a separate ticket for the work you are doing on the VA Forms REACT for search, so I will create a ticket for you for that and revise this one so we don't have to wait until FE is done to add Analytics.  I will follow up with Nedie and make sure she is clear on both analytics requests.

**Comment by aeltarhoni** [comment]
Closing in favor of #4547
