### ISSUE TITLE
Pre-Check-in Edit Capability - Demographics

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36064]
## Notes
- [Notes on where we left off when we de-prioritized this Epic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/edit/editing-wrap-up.md)

## Problem Statement
As a Veteran, I want to have the ability to edit my demographic information if needed so that I can ensure the VA has my most current information on file.  For Pre-check-in, we need to allow editing for demographics, NOK, and Emergency Contact information. 

Initial priority for edit will be for demographic information. 

## These Epics are Releated
- [Edit Demographics](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/36064)
- [Edit Emergency Contact](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38909)
- [Edit Next of Kin](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38910)

**Comment by julieadair1** [comment]
1. Do we need to validate the value to the veteran?
2. what does it look like?
3.  Where is the data coming from?
4. Where is the data going and how is it getting there?
5. How do we know that we are successful?  KPIs, metrics?  What does a successful edit implementation look like and how do we measure success? (Reliability, Google Analytics, number of successful check ins, etc)

**Comment by julieadair1** [comment]
Team sizes this at an XL

**Comment by acrollet** [comment]
@loripusey should the tickets for this epic be in the backlog or closed out?

**Comment by loripusey** [comment]
I think when we revisit this epic we will need to do some cleanup, but I'm reluctant to close anything until we pick this up again
