### ISSUE TITLE
Form 5490: Update Exp. Date to 1/31/2025

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#36077]
## Issue Description
This ticket requires to update the Exp. Date to 1/31/2025 on Form 5490

---
## Tasks
Update Exp. Date to 1/31/2025 on Form 5490

## Acceptance Criteria
Form 5490 exp. date will be updated to 1/31/2025
---

**Comment by hallihocine** [comment]
Ticket has been validated in staging: The Exp. Date on Form 0994 is now updated to : 01/31/2025
<img width="777" alt="Screen Shot 2022-01-28 at 4 25 38 PM" src="https://user-images.githubusercontent.com/86266024/151624970-3de87c36-6543-456e-aa66-ed86d93285d6.png">

**Comment by hallihocine** [comment]
- Test run in TestRail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2880&group_by=cases:section_id&group_order=asc&group_id=3598
-Test script/steps:
[Form 0994 Update Exp. Date to 1:31:2025.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7961969/Form.0994.Update.Exp.Date.to.1.31.2025.xlsx)

**Comment by mrblanco1** [comment]
@AdamFreemer - There was a mistake. This ticket was originally meant to update form 5490. We'll revert the change and update form 5490.

**Comment by hallihocine** [comment]
Ticket has been validated in staging: The Exp. Date on the form 5490 is now updated and set to 01/31/2025.
<img width="546" alt="Screen Shot 2022-01-31 at 10 06 37 AM" src="https://user-images.githubusercontent.com/86266024/151819909-6263ccee-4870-4390-bb6f-6d3c942b9c99.png">

**Comment by hallihocine** [comment]
- Test Run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2881&group_by=cases:section_id&group_order=asc&group_id=3598
- Test Script/Steps: 
[Form 5490 Update Exp. Date to 1:31:2025.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7971882/Form.5490.Update.Exp.Date.to.1.31.2025.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed on 1/31/2022. Closing now.

**Comment by mrblanco1** [comment]
Passed QA and UAT. Removed feature flag. Will go out to prod today.
