### ISSUE TITLE
MHV Inherited Proofing Research

### ISSUE THREAD

**Issue by Vngpire** [department-of-veterans-affairs/va.gov-team#36098]
# Description

# Current Action items
- [x] Wizard meeting

**Comment by Vngpire** [comment]
- [ ] Primary and Secondary Research
- [ ] Research Plan

**Comment by Vngpire** [comment]
Finished up with research:
[Primary and Secondary Research for MHV Inherited Proofing - Google Doc](https://docs.google.com/document/d/1kJSjRKi4jsCkonk2vUKGpg7vL7lcZl6rzf3iIDLM_qY/edit?usp=sharing)

Does this research live in the login.gov repo?
[# Primary and Secondary Research for MHV Inherited Proofing.md](https://github.com/department-of-veterans-affairs/va.gov-team/files/7960999/Primary.and.Secondary.Research.for.MHV.Inherited.Proofing.md)
?

**Comment by APorter-Clarity** [comment]
@Vngpire I think it's being classified as something else. We will need to have a new folder created for the MHV transition in this repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity

**Comment by APorter-Clarity** [comment]
@Vngpire Folder has been set up: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/MHV%20Inherited%20Proofing

**Comment by Vngpire** [comment]
[Research Plan: MVH Inherited Proofing](https://docs.google.com/document/d/1cw3QhjA6Iha7J5p5AJx_EmyVe-5kOMZTBVi_OIanmT8/edit?usp=sharing) Will be required to ask permission to access.

**Comment by Vngpire** [comment]
[Conversation Guide Draft](https://docs.google.com/document/d/1AJFWsYV4Rn2ZhGI7kLKCpS5VnTHAuhI2y0c3Myn1dok/edit?usp=sharing) Will be required to ask permission to access.
