### ISSUE TITLE
Request Content Review: 526 Original Claim Messaging for Missing IDs

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3609]
**User story**
As a member of Benefits and Memorials team building on VSP, I need my content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3285)
- [InVision Design](https://vsateams.invisionapp.com/share/JNUPVDECGFK#/393288220_526_Gating_-_Edge_Case_Alert)

**Acceptance criteria**
- [x] Content reviewed 
- [x] Required content updates/changes provided to Benefits and Memorials team

**Comment by peggygannon** [comment]
@YanaRoy Hi, Yana for this gating message, do we want to let the user know that it's their *VA ID* that they're missing, or do you want to keep this message more general?

**Comment by peggygannon** [comment]
@YanaRoy Here's my content recommendation for the 526 gating message. I kept it more general. Please let me know if you want me to add in detail that they are missing their VA ID. 

also, can we make the link a jump link so it takes user to the right spot on the How to file page? 

**You can’t file a claim online right now**
It looks like we’re missing some information needed for you to file your claim online. You can file your claim by mail, in person. or with the help of a trained professional. Learn about the [other ways to file your claim](https://www.va.gov/disability/how-to-file-claim/#other-ways-to-file-disability-claim).

**Comment by YanaRoy** [comment]
it's not the VA ID they are missing when they get this message - it's a BIRLS ID. @peggygannon

**Comment by kevinstachura** [comment]
Thanks @peggygannon ! The content changes have been reflected in the Invision link: https://vsateams.invisionapp.com/share/JNUPVDECGFK#/393288220_526_Gating_-_Edge_Case_Alert

Please let me know if there is anything further you'd like to change.

@YanaRoy - I will comment and reference this updated design within the associated frontend ticket for awareness.

**Comment by peggygannon** [comment]
thanks, @kevinstachura the update looks good. I do have one more edit. In the header, can we change 
"a claim" to "your claim"? 
so the header would read: **You can't file your claim online right now**

sorry, I missed this in my first edit.

**Comment by kevinstachura** [comment]
No problem! Change is now reflected in the Invision proto: https://vsateams.invisionapp.com/share/JNUPVDECGFK#/393288220_526_Gating_-_Edge_Case_Alert

**Comment by peggygannon** [comment]
@kevinstachura OK, thank you. The update looks good.
