### ISSUE TITLE
Run fix_coord_mismatc on gibct-data-service production

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#36095]
## Description
Request to run `fix_coord_mismatc` script on `gibct-data-service` production after data was reverted again. 

## Background/context 
Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1643303778203149

## AC
- [ ] `fix_coord_mismatc` script has been run on `gibct-data-service` production

**Comment by mrblanco1** [comment]
Hi @rileyanderson - Just wanted to see if script #1 was kicked-off about an hour ago or if there is anything else you need from our end. Thanks!

**Comment by mchelen-gov** [comment]
@mrblanco1 What day and time period are you requesting this script to be run within?

**Comment by mrblanco1** [comment]
We requested script #1 to be executed ~1 hr ago please. WE are highly impacting all Veterans using Search by Location in Comparison Tool until both scripts are executed.

**Comment by rileyanderson** [comment]
@mrblanco1  I think you team is requesting access to be able to run it.
