### ISSUE TITLE
For VA appointment requests reasonCode.text field is required (VAOS service)

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#36102]
When attempting to request a VA appointment, the application encounters an error indicating that the reasonCode.text field is required.  For now please use the coding[0].code field and duplicate that value into reasonCode.text.

AC:

[] the reason.text field is set to the value of coding[0].code in the POST body when making a va appointment request.

Error in creating proposed appointment
- Go to VA Online Scheduling tool
- Start Scheduling
- Select Social Work
- Select VA Clinic (Sydney)
- Select Date and Time
- Select Reason and any additional text
- Choose type of appt (office)
- Confirm contact info and enter time of day to call
- Request appointment

**Comment by ldelacosta** [comment]
Per discussion with Brad, we are good to close out the ticket. Thanks!
