### ISSUE TITLE
Access for Patrick Arthur

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#36104]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Patrick Arthur

### Your Email

patrick.arthur@accenturefederal.com

### Name of Your Team

Accenture Dev - EDU

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need access to the gids production server to be able to run some scripts to update institutions

**Comment by jbritt1** [comment]
Tagging @mchelen / @td-usds for approval on SSM-prod access. 

@PJart, one question I suspect will be asked is "how long will this elevated access be needed?"

**Comment by PJart** [comment]
My guess is a week or two, only reason I would need access is if someone on edu clicks on the dashboard and I need to update the institutions until the dashboard issue is fixed, we told them not to touch it so hopefully I won't need to run it.

**Comment by jbritt1** [comment]
> My guess is a week or two, only reason I would need access is if someone on edu clicks on the dashboard and I need to update the institutions until the dashboard issue is fixed, we told them not to touch it so hopefully I won't need to run it.

Thank you for providing that. Now we just have to await approval.

**Comment by td-usds** [comment]
approved

**Comment by jbritt1** [comment]
@td-usds, should i do a two week reminder?

**Comment by td-usds** [comment]
> @td-usds, should i do a two week reminder?

Yes please

**Comment by td-usds** [comment]
@PJart for future timed requests, please use the "Access Expiration" field

**Comment by jbritt1** [comment]
SSM prod access granted at this time. Setting two week reminder to remove

**Comment by jbritt1** [comment]
Temporary prod SSM access revoked at this time.
