### ISSUE TITLE
[FE] Send Demographic Confirmation Status to BE for Day-of Check-in

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36109]
## Feature Flag
check_in_experience_demographics_confirmation_enabled

## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> As a Veteran, I want my confirmations to be stored and made available to staff so that I can keep my information current and staff aware of any changes needed. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> Currently, we only capture the demographic confirmation status for check. This item is to capture this data for the day-of check-in experience and send to CHIP to store.

Link to [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1643139433222900) thread.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
Stephen to look into if check-in should continue if data changes are needed.

**Comment by sarahknoppA6** [comment]
this may move to the ready or blocked cols at some point bc it is dependent on a new endpoint

**Comment by sarahknoppA6** [comment]
@stephenBarrs can you please provide an update on if check in should continue if data changes are needed?

**Comment by sarahknoppA6** [comment]
@stephenBarrs do you have an update?

**Comment by stephenBarrs** [comment]
Per the business owner we cannot allow the Veteran to complete Check In if they indicate that they have information to update.  

it would still be beneficial to determine how Veterans would most like this to happen, as we may be able to revisit this topic in the future.

**Comment by sarahknoppA6** [comment]
@jparker0425 I think the ticket should go back to you now for next steps, but it doesn't sound like this should remain blocked any longer.

**Comment by jparker0425** [comment]
@sarahknoppA6 and @stephenBarrs this item is related to the FE work needed to send the confirmation status to BE while BE works with CHIP on sending to the new endpoint for day-of Check-in. It was prioritized for this sprint. 

I do not think it is related to allowing veterans to complete check-in if updates are needed.

**Comment by stephenBarrs** [comment]
@jparker0425 agree this ticket is not for allowing a Veteran to complete day of check in if they have demographic data updates, and is actual for sending the demographic confirmation data to vets-api and then to CHIP so that it is reflected in the staff facing application.

**Comment by stephenBarrs** [comment]
@jparker0425 can we link the tickets for the BE work and the CHIP work so they are easy to access from any ticket?

**Comment by dcgoodwin2112** [comment]
I have a WIP branch for capturing the demographics responses in the Day-of check-in flow, but I came across a UX concern I wanted to bring up with the team. 

Before, we've been halting the flow immediately when a Veteran answers no to any of the questions about Demographics, EC, and NOK being up-to-date. They are forwarded to the See Staff page which has a slightly different message depending on which question they answered no to.

In the new flow, we are capturing all of the responses first and then forwarding to the See Staff page before displaying any appointments. This lets up capture all of the question responses even if the veteran can not complete check-in

**Question**: can we show a single unified message on the See Staff page, or should the message still change based on which questions a Veteran answers 'yes' or 'no' to?

cc: @stephenBarrs @niradatta1 @kristenmcconnell @ytsaoca @zach-park

**Comment by dcgoodwin2112** [comment]
After call/discussion with @acrollet, we decided to update this branch to only send updates to the demographics endpoint for pages that a veteran has reviewed instead of assigning default values. This will match up with pre-check-in and prevent the edge case of having a false response assigned to a page that was intentionally skipped.

Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1646937926043839?thread_ts=1645791682.440809&cid=C02G6AB3ZRS

**Comment by dcgoodwin2112** [comment]
Validation needed:

- Enable feature flip in staging
- Test demographics api call on See Staff page and Appointment confirmation page
- Enable feature flip in production

**Comment by dcgoodwin2112** [comment]
Tested and verified on production 03/22/22

**Comment by sarahknoppA6** [comment]
This is to be validated in prod today (3/23) and this ticket will be closed if there are no issues.
