### ISSUE TITLE
When attempting to submit a booked VA appointment slot.start and slot.end field are not allowed. (VAOS service)

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#36103]
When attempting to submit a booked VA appointment, the application encountered an error indicating that the slot.start and slot.end fields are not allowed.

AC

[] The slot.start and slot.end fields are absent in the POST body when submitting a booked VA appointment

- Go to the VA appointments tool
- Start Scheduling
- Choose type of care (audiology)
- Choose where you want to receive your care (VA Medical Center or clinic)
- Choose a VA location (Cheyenne)
- Choose a VA Clinic (CHY AUDIOLOGY)
- Select the earliest day available (today)
- Select a day and time
- Choose a reason (routine) and enter text (testing)
- Confirm contact info
- Confirm appointment

**Comment by ldelacosta** [comment]
Per discussion with Brad, we are good to close out the ticket. Thanks!
