### ISSUE TITLE
Access for Manish M Shah

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#36112]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Manish M. Shah

### Your Email

m.c.shah@accenturefederal.com

### Name of Your Team

Tech lead

### Service(s) You Want Access To

AWS

### Desired AWS Services

SSM to production servers

**Comment by jbritt1** [comment]
tagging @department-of-veterans-affairs/operations-aws-approvers for approval

@af-manish, what is the length of this request?

**Comment by af-manish** [comment]
> tagging @department-of-veterans-affairs/operations-aws-approvers for approval
> 
> @af-manish, what is the length of this request?

Let's make it 1 year please.

**Comment by td-usds** [comment]
Hey @af-manish is there a subset of SSM you need access to (and can the request be scoped down to just those things)? I've received confirmation from you VOR about eQIP confirmation but would like to understand what exactly it is we'll be giving you access to and how broad that really should be within the SSM service.

**Comment by td-usds** [comment]
Hi @af-manish can you provide feedback to https://github.com/department-of-veterans-affairs/va.gov-team/issues/36112#issuecomment-1032938973 ?

**Comment by jbritt1** [comment]
Could we perhaps with a 90 day timer like we granted in https://github.com/department-of-veterans-affairs/va.gov-team/issues/37086 @td-usds

**Comment by mleclerc00** [comment]
Sorry for the delay @af-manish, you should have the correct permissions now.  Closing this ticket but set up a reminder for the team to check in again with you in 90 days

**Comment by af-manish** [comment]
Yes please.

**Comment by rmtolmach** [comment]
@af-manish, it's been another 90 days. Do you still need SSM access to production servers?

**Comment by rmtolmach** [comment]
We have a bot that alerts us about AWS users who are approaching 90 days of inactivity within AWS and [Manish was listed](https://dsva.slack.com/archives/C03JZS08VV4/p1661785261192979). Because of this and since I haven't heard anything back, I am going to remove `adhoc-vetsgov-ssm-prod` access.
