### ISSUE TITLE
Access for Yang Yang

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#36110]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Yang Yang

### Your Email

yangyang@navapbc.com

### Name of Your Team

OCTO Benefits Delivery - Software engineer at Nava PBC

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIY6xtTXf6o0obCN1YNjBzc8JaSGhgL/9ST3WclRhpfin2ea5iHywPPIkuV1w5a6h2dBPvcVZe5oifUogmFI8EPT8xCIVhafzi1klZeTFzSMsk1qeOXMnV3AphxaVtr60hBZskTnRGcXXbrFSHBbLFNXjE1UYkeu2/2Y7jV1TX+K3XxSrQFh8F/+zA9l3lmIYvTLAkkfZcYW5pHFViFfvtMST6zK+uXCMjBVv2YGkL3HTvYpgqbaHBOvGhqtF1NdA8oSlwwdnI4M5ZtWrlmnnJDkhC4dQSlJueENzHgmcTLL2E3gjlx5BBO9+8s7WTsNWr9jH31fGCeoRX5zfm8nwN yang@medea.home

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
