### ISSUE TITLE
Enabling Will Huang to DSVA Slack

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#36122]
# Description
- Please activate will.huang@adhocteam.us as a full member. He is an engineer on the Platform Spike Teams and he starts today. He has a slack account from previous program work, but needs his 2FA reset.

**Comment by jjulian** [comment]
Will is still getting prompted for 2FA, but he no longer has access to that authenticator. Can we reset his 2FA to get him in?

**Comment by MrBilnon** [comment]
I'm still prompted for 2FA which I don't have access to anymore

**Comment by CoryTrimmUSDS** [comment]
As of time of writing, I have disabled @MrBilnon's 2FA.

Moving forward, please do not assign @LizCallaghan Slack related requests since she has moved offices.

Please close the ticket if Will can access his Slack account.
