### ISSUE TITLE
Higher Level Review - VSO question implementation

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36135]
## Issue Description
Frontend implementation of new question related to [design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36134). 

---
## Tasks
- [ ] Add new question to HLR flow. 

## Acceptance Criteria
- [ ] Question added, tested, implemented.
---

**Comment by Mottie** [comment]
The design for this implementation was not done ([design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36134)) - adding a question about an established VSA per a 12-22 form is not currently supported by the backend either. We will need to discuss this with the stakeholder & team.
