### ISSUE TITLE
Access for Yoom Lam

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/va.gov-team#36133]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Dung "Yoom" Lam

### Your Email

yoomlam@navapbc.com

### Name of Your Team

OCTO Benefits Delivery - Software engineer at Nava PBC

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjpGPjUAw4y8+JO2eGp43mTx8TMFz2bsJuy6Y0uXfPsMM4eJe0X/EyRVmItdgx1B1fJeDTnQwbQmSFpg71ZJwd/Nd+tq48Djf4/ALLcaIWBgLdm4+xWp29lt+Cu+HWkxNbsKc6Y1dbEyLH3tEfjB/dKO2F8ed9WO/VLLOriZqLWP/uGWDaJtBLF3B2nRwaOf0ZdQlc0haU1NUyNRRA9McZqerLFKWkDXj/PQs3xkwCrc4jP8qr7ctYT0U7a+jPmLHWtqOrqfV4EceleIzGe/Ip1XbhsZ4MIj+5+f2ARohvrpdgKF2zt6sFzxEhEohMjVsq7lrJcIskEl1vl/RBDjGU1zzUlTnFyJsRuyMdqOISOJF1bq0O0oORQafiSwOGvg55sjfOCnYKEW98RwEs/ZbS6AQ/ISyKZc833BCjTFq38dpUUaf8oA35PeSIMIMyLzL16buW/yEDsIj5unYdB0nybVACoHU7bSh6nCrsY56Oih2zTWeUlH7kD/qYJL9VwX0= yoomlam@yoom-mac

### Desired AWS Services

I need access to S3, where our team's software uploads generated pdfs for VMBS eFolder, to ensure files are correctly uploaded and the file contents are correctly formatted.

I need access to the Rails console in a production EC2 instance to investigate and resolve any problems/failures with Form 526 submissions and our hypertension fast tracker code when running against real data, in addition to ensuring that submissions continue to process after addressing the failures.

### Access Expiration

On-going.

**Comment by yoomlam** [comment]
Hi @mleclerc00! When should I expect to get access? Is there any additional information you need?

**Comment by jbritt1** [comment]
### For AWS Access:

User: Dung "Yoom" Lam
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level access: no

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Comment by mchelen-gov** [comment]
@yoomlam Have you implemented Loki and Sentry logging for these errors?

**Comment by yoomlam** [comment]
Hi @mchelen-gov,

Context: Our RRD (Rapid Ready of Decision) prototype currently hooks into Form 526 submissions, so we've been using [existing Form 526 Grafana charts](http://grafana.vfs.va.gov/d/000000066/form-526-disability-compensation?orgId=1), which include retryable error and non-retryable error counts over time.

Currently we [email errors to ourselves](https://github.com/department-of-veterans-affairs/vets-api/blob/434177d0be24f2c4c58ec31b8d2d83879f35d4e0/app/workers/fast_track/disability_compensation_job.rb#L50) to get notified and have an idea of the source of the problem. I believe Sentry provides the same backtrace information. We then ask one of your backend engineer to go into prod to get more details about the error. If it's a transient error, we later ask to check if the form submission eventually succeeded. In some cases where there's a bug, it takes several back-and-forth session with the backend engineer to find the root cause.

Another pain point is when developing and testing in non-production environments, non-realistic data from external data sources (Lighthouse staging for example) does not reflect the subtleties in real data, which causes failures in the production environment. Having access to prod would mitigate such production errors, speed up development, and reduce our use of your engineers' time.

**Comment by NatashaJIbrahim** [comment]
cc @zachgoldfine44 Is this something you could help move along?

**Comment by mchelen-gov** [comment]
> Hi @mchelen-gov,
> 
> Context: Our RRD (Rapid Ready of Decision) prototype currently hooks into Form 526 submissions, so we've been using [existing Form 526 Grafana charts](http://grafana.vfs.va.gov/d/000000066/form-526-disability-compensation?orgId=1), which include retryable error and non-retryable error counts over time.
> 
> Currently we [email errors to ourselves](https://github.com/department-of-veterans-affairs/vets-api/blob/434177d0be24f2c4c58ec31b8d2d83879f35d4e0/app/workers/fast_track/disability_compensation_job.rb#L50) to get notified and have an idea of the source of the problem. I believe Sentry provides the same backtrace information. We then ask one of your backend engineer to go into prod to get more details about the error. If it's a transient error, we later ask to check if the form submission eventually succeeded. In some cases where there's a bug, it takes several back-and-forth session with the backend engineer to find the root cause.
> 
> Another pain point is when developing and testing in non-production environments, non-realistic data from external data sources (Lighthouse staging for example) does not reflect the subtleties in real data, which causes failures in the production environment. Having access to prod would mitigate such production errors, speed up development, and reduce our use of your engineers' time.
> 
> If it's a factor in getting access, I only need [read-only access](https://dev.to/molly/how-to-setup-a-readonly-rails-console-1j1a) in the Rails console ([`--sandbox`](https://stackoverflow.com/questions/5043956/can-i-specify-in-database-yml-that-a-rails-environment-should-have-readonly-acces)).

@yoomlam Interesting, thank you for the context! What error information is needed for debugging which is not available through Sentry or Loki logs?

**Comment by drorva** [comment]
The team often needs to look at the Form 526 JSON for a claim that might not have gone through; that form is available in the encrypted production db, but obviously not in Sentry or Loki.

**Comment by yoomlam** [comment]
@mchelen-gov 

Here are responses from our team:
* We often need to look at the Form 526 JSON for a claim that might not have gone through; that form is available in the production `vets-api` database but not in Sentry or Loki logs.
* Bugs that are due to data content, for example Form 526 submissions that have `auth` headers that are in a format that we didn't expect.
* We currently track our jobs using the `Form526JobStatusTracker` but we don't have access to the associated DB records (in the `form526_job_statuses` table).
* Having access would allow us to get the url for the pdf when there are bugs related to the data being included there.

**Comment by jbritt1** [comment]
So to clarify, we are to give Yoom SSM prod access at this time? With an ongoing timeframe? @td-usds

**Comment by jbritt1** [comment]
> Note S3 access request as well:
> 
> > I need access to S3, where our team's software uploads generated pdfs for VMBS eFolder, to ensure files are correctly uploaded and the file contents are correctly formatted.

S3 readonly access would be granted as a baseline permission

**Comment by yoomlam** [comment]
Hi @td-usds, it appears @jbritt1 is asking for a follow-up approval.

**Comment by td-usds** [comment]
@yoomlam Can we approve for 6 months and then revisit the requirement? I want to make sure we don't end up in a situation where folks acquire and retain access privileges due to grandfathering-in...

**Comment by yoomlam** [comment]
@td-usds Sure, that will allow me to further assess the value of having prod access. cc: @zachgoldfine44

**Comment by jbritt1** [comment]
[Reminder set](https://dsva.slack.com/archives/CTYQL39FE/p1645113386365979), working on access now

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.

**Comment by jbritt1** [comment]
@yoomlam, do you need prod access at this time? Reminder to remove the perms fired today so checking in before removal.

**Comment by yoomlam** [comment]
@jbritt1 Yes, I'm still using prod access to check on Form 526 submissions for RRD (rapid ready for decision).

**Comment by jbritt1** [comment]
@td-usds

**Comment by jbritt1** [comment]
@td-usds, please approve the extension for Yoom as time allows.

**Comment by raywangoctova** [comment]
approved for 90 day extension on behalf of Thomas and Mike since they are on leave.

**Comment by jbritt1** [comment]
New reminder created for 90 day extension.

**Comment by rmtolmach** [comment]
@yoomlam do you need prod access at this time? Reminder to remove the perms fired today so checking in before removal.

**Comment by rmtolmach** [comment]
@td-usds Yoom is requesting an extension for ssm prod access.

**Comment by rmtolmach** [comment]
I think Thomas might be out today. @raywangoctova, can you approve this access?

**Comment by raywangoctova** [comment]
Approved for 90 day extension on behalf of Thomas and Mike since they are not available at this time.

**Comment by rmtolmach** [comment]
Reminder set in #platform-cop-devops
<img width="719" alt="image" src="https://user-images.githubusercontent.com/10993987/202032633-31b29163-ac4b-4652-8e52-de68eacf242d.png">
