### ISSUE TITLE
[UX] Create Presentation Material for Designers/Researchers around Accessibility Research Method 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36145]
## User Story 
As a UX Researcher, I want to document and present the research method used for accessibility so that I can give insight into how the research was conducted and potentially help improve methods for other teams. 

## Description 
UX team has completed comprehensive accessibility research for the check-in experience. The method used to conduct the research is something the Accessibility team has shown interest in learning more about and it would be great to present to the design/research team for VA. There is also possibility of presenting to additional stakeholder groups.

This story to create material to present to the various stakeholders about the method used for the accessibility research that was done. 

[Slack](https://dsva.slack.com/archives/C02FDKJNT46/p1643312977359289) thread.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Accessibility map Google spreadsheet](https://docs.google.com/spreadsheets/d/14AxfTv29bsKu6pKdRZIjmOBd4pTEl5Fu2Kbf_XUfhFg/edit?usp=sharing)
- [Accessibility user journeys Mural]()

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Tasks 
- [ ] Process/method has been documented ([Report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md
))

## Acceptance Criteria 
- [ ] An outline/draft presentation has been created

**Comment by ytsaoca** [comment]
Presentation deck structure brainstorm: https://app.mural.co/t/civicactions3117/m/civicactions3117/1647464442696/f6f270e1fd1bfcac309a9da6cd6f2f4cd79fdb0f?sender=u70b8b2930b03d3ef317d2520

**Comment by ytsaoca** [comment]
Deck draft: https://docs.google.com/presentation/d/1xfn_A9_h_tyo3Pft0hgA5rGGjG8yNPTi3bAmNC8iqcs/edit#slide=id.ge2a21743f5_0_124

**Comment by niradatta1** [comment]
@loripusey After re-evaluating our tickets and priorities this sprint, we need to put this back in the "ready" coloumn. We'll know by next week if we're able to pull this in depending how our other tickets go. 'cc @ytsaoca
