### ISSUE TITLE
Offboarding of Michelle Steigerwalt

### ISSUE THREAD

**Issue by CoryTrimmUSDS** [department-of-veterans-affairs/va.gov-team#36151]
# Description
- **Note** - this is an Office of the CTO individual.
- Please provide the name of the individual needing offboarded.
   > Michelle Steigerwalt
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > OCTO Engineer on Translation / Public Websites | Last Day - Friday, January 28, 2022 | Team - Office of the CTO
- Please provide any type of access they may have and their GitHub username. 
  > Unsure of access levels.
  > Government Github Username `yuffster-usds`. Other Github Username `yuffster`.
  > Emails include `michelle.steigerwalt@va.gov` and `michelle.steigerwalt.va@gmail.com`
  
 
## AC
*Performed by Platform team*
 - [x] Remove from [Sitewide Content / Translation](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack < OCTO People Operations will Handle this.
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by jennaouellet** [comment]
No GA or Domo access for this user

**Comment by mleclerc00** [comment]
No Socks
No AWS
Neither user `yuffster` or `yuffster-usds` is part of the github org
No sentry
No pagerduty
No datadog
Instructed to ignore slack

**Comment by CoryTrimmUSDS** [comment]
Thanks for the quick turn on this @mleclerc00 - much appreciated.

Can we also confirm that there is no access to the Flipper?

**Comment by mleclerc00** [comment]
@CoryTrimmUSDS 

Confirmed that said user does not have flipper access
