### ISSUE TITLE
Write content for 1095-B pages

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36164]
Acceptance Criteria:
- [x] Stored content in copy doc on Github
- [x] Drafted MVP content
- [x] Reviewed by VA-PO

**Comment by tameracorson** [comment]
1095-B Tax Form Content Needs & Scope document  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/Content/1095b%20Content%20needs.md
