### ISSUE TITLE
QA Testing for Address Validation Modal

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3616]
## Info 
Add the vsa-qa label  [Yana, Michelle: this is a change from qa to vsa-qa]
Select the Milestone sprint, or otherwise provide due-date for testing results.

Provide the following info to support testing (via links if documented elsewhere):

## Test-accounts** (usernames) for all UX scenarios/flows.

**Comment by Samara-Strauss** [comment]
Closing. Duplicate of #3948.
