### ISSUE TITLE
[Design] Personal information revisions: Remove "prefer not to answer" from pronoun field in mockups

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#36173]
### Background

Related FE ticket #36174.

Apparently, MPI does not support a "prefer not to answer" option for pronouns, which means VA Profile can not support it either since VA Profile needs to connect to MPI. So, we need to remove this from the mockups.

### Tasks

- [x] Remove "prefer not to answer" for pronouns in mockups
- [x] Update relevant documentation for frontend

**Comment by cgednalske** [comment]
This change has been made in mockups and updated in [FE Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md)

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by cgednalske** [comment]
Hi @Samara-Strauss -- just answered your related question in the other ticket. Once the hint text place holders are complete, I was planning to create new components for each field that would update automatically in these two mockups, so I can avoid having to update each field for every change we have.

If it helps, I can move these mocks to a different Sketch page in the meantime so as to not cause any confusion - and then add them back once those are set!

**Comment by Samara-Strauss** [comment]
Just saw you're other message -- we're good, and thanks for letting me know! No need to do anything, and thank you for the clarification. I'll close this back out.

**Comment by cgednalske** [comment]
Ok great - thank you! Ya those two mockups have been causing updates to be done multiple times, so figured it was time to take care of that and streamline moving forward.
