### ISSUE TITLE
Access for Saman Moshafi saman-moshafi-va

### ISSUE THREAD

**Issue by saman-moshafi-va** [department-of-veterans-affairs/va.gov-team#3617]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Michael Domanski
- Please provide your name.
   > Saman Moshafi
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > team Falcon, Software developer, ThoughtWorks
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/gs7NFVeHY2R9+DzC3mroW2mwsO4+NaMernNPDbvIPEH5M0MNXTqTxLK+D0r1R9SgQtl3dT5HmdeVYQUioUdbECbQYEsD/klm+AWTXRTr7xslMZoI6FUuv3pHaZC++3MdnoMibBLi6JgnELv72jj4lS42oEadomwwlvPqU+1D2SCOAjpX4nDphzaf+oIAZO6kuHVaO6KEoJJV5oATKj3KS/2ahzaV/xHc6dMffVQ4PNuwf16o+NmuFE6VoPIjPv94cOdGjIU36b03Tt3zP5f7cuobBITzhUQQTNwfZM+felNNVw8aZ+dkrOpmaXG9W2jXiuhvTDfHJIoHWvfvO2uU/Eo8uHVlsZHg+HAjDCqeYnE/lz6MRZI9k5yHRYQGjBe5mVL+Ya1MyJCN3y3CXt6G9fP8j1e2lcnCbl2H6Xql62b0sCkOxlR8+xaFNOkOfWavxtjDMZIt6PXoMDir5U8P9l+Iwa49zgBCb6AXonb4UmMGkXgyZBw0w/QxRL8eWwhFhDgCiKQ4eSWcECveHzQXQ6HvEUwDCI9c1Y+2en0zvrqC7LzLFLBvgeKoDqe+NKfSeY9gsZTln26JNlooO9PAAl8wqWF7PLGsYWWJo9UKWNvtgH/tpNKzVtUCO7aueMC5JOPkYraGn9Yn3Rb5LzzGvpkl3fQcs+ZzVWkHkfV+nw== saman.moshafi@thoughtworks.com
- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by saman-moshafi-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Michael Domanski
User: Saman Moshafi

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.
