### ISSUE TITLE
[Platform SRE] Define process to escalate support bot requests to GitHub issues

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#36179]

**Comment by oseasmoran73** [comment]
I believe this is what the Support Tier Model defines. We also have this [ticket](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/42337) for recent process.

I think we can close it out
