### ISSUE TITLE
Analytics Implementation or QA Support for [cedar-1095b - Form 1095-B]

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36175]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - 1095-B 
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - April 1, 2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by laurensimpson14** [comment]
Hi @JordanSWhite 👋 

I'm happy to help you with getting tracking on this form! I've got a couple of questions for you: 
1. What is the URL to the form? 
2. Is the form currently only on staging? 
3. When is the launch date?

**Comment by JordanSWhite** [comment]
@laurensimpson14 
1. URL to come (still figuring out exactly where this form needs to live)
2.  It's not. That probably won't come until late February or early March
3. April 1 is our target MVP launch date

**Comment by tameracorson** [comment]
Collaboration cycle meeting; no points. Added after sprint start to track collab cycle meetings

**Comment by laurensimpson14** [comment]
Thank you @JordanSWhite! I've moved this ticket to standby since we need the form to be on staging before we're able to implement any tracking. 

@tameracorson The 4 sprint timeline won't start until the form is on staging. Once it's on staging, we'll pull it in. If the launch date is less than 4 sprints away we do our best to meet the launch date deadline 👍

**Comment by JordanSWhite** [comment]
@jennaouellet We're not in staging yet, but our URL will be www.va.gov/records/download-your-irs-1095-b

**Comment by jennaouellet** [comment]
@JordanSWhite Thank you! 
Please let me know once the site is accessible in staging and which interactions you'd like to track and I can begin implementation.
