### ISSUE TITLE
Update designs to high fidelity

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36181]
- [x] Foundational components in full color
- [x] Interaction states created 
- [x] Annotations as considerations for development added
- [x] Reviewed with team
- [x] Reviewed with VA-PO
- [x] For desktop and mobile (but not tablet)

**Comment by graceerinhongfrog** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/8c1dff8fe6bd9f608366440a44f64bd1cd690410/products/health-care/1095b-tax-form/design/wireframes/Wireframes.pdf
