### ISSUE TITLE
Access for Marisa Hoenig

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/va.gov-team#3618]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Michael Domanski
- Please provide your name.
   > Marisa Hoenig
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Falcon, Software Developer, ThoughtWorks
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCy+PyB/93ihtty/KG5KL9UHem13CHmHtuLQydC8ghKsIbf/k2+uMGsjvdQ2mJFU5r77mLtCVZNuOT1j7AYJrssqmTvKe9w6xJiK+eUYldpqLvCW6EgXVAAnKVildRrjm39I4co57aEYdryYtRzoOz07rGdBJ+l8aZRFrID4vy6P2opul4YOw6wyJoOH7q28/Si8B8z/hKPsVr1m64WcHHicdugkD9WSy2e5rkp6Bfc+szopDCbor2yywq0NOJiogEHvrynGzSC/EPBuY4OWw7er/E2IizvwA02PLrO2DcGQaRNkIU4C6+zzsvbYWzRp9iKdmdio4oib3QpcDQEgnwf73v0vA48ni+PZzk1ryiqSEoOJXTE6aNfjQ1EqKp658ORU8NILsF9Oa3sAnGhka8Fw3FgrhM9cNohqSfomwCeKAVvBCecPaYjSpH+wk/6LS4V3RyzN5Rpw4Rkw1mGZpsS4wcjaoweWaTv3UUOBlEyEL3oKz+F+bCbvnOR3RWvLIvCTy4V9WnJj8lAUn1j9Cn/IaeYWF1wN8UULXJuXNbF91yBeoGDXjVQ7ecV0AEobDWhaUDQ1Qj8pLbGjiqPufCJervBDt/qdtjHQHzfSLVpRKi59heKUET3L+IILg+QTUXKrdfs2O5WgD/9dzkFwRhuLlYoKJCk3BzDiRfaImKVDw== marisa.hoenig@thoughtworks.com
```

- [Grant AWS Console access?]
  > NO

**Comment by marisahoenig** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Michael Domanski
User: Marisa Hoenig

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.
