### ISSUE TITLE
Develop standards/guidance and request process for VA.gov search "Best Bets"

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#36194]
"Best Bets" are a key feature of VA.gov search that can be used to improve findability of content within VA.gov. 

We need to develop some standards and guidance for how to best utilize this feature, as well as a process for requesting, recommending and implementing them.

**Comment by mnorthuis** [comment]
**Some questions around guidance:**
- How many best bets per term?
- How do we prioritize when multiple items are requested for a best bet (i.e. performance of each item, page views of destination, importance to business, etc)?
- Should we link directly to PDFs or other files in a best bet?
- How specific or broad is the keyword - how much content relates to it?
- Who should be the key audience for our best bets -i.e. Fiduciary supports both the beneficiaries of the service as well as those becoming a fiduciary
- How many terms should one page be listed under?
- what are top searched terms related to web page
- 

**Process things to think about:**
- recommendations made with IA/content work
- Request process from stakeholders
- implementation process
- how do we evaluate performance of best bets and follow up with stakeholders on changes
- how do we maintain to ensure no errors, retired pages, outdated info, etc
-

**Comment by mnorthuis** [comment]
High level standards sent in response to fiduciary request:
- Maximum of 2 best bets per search term. 
- Best bets will prioritize content related to Veteran and their beneficiaries.
- Best bets on a single term should be distinctly different content. 
- VA.gov search experience will not link to external sites.
- Search best bets will not link to documents.  The only exception to this is key forms/applications that we do not have a landing page for.

**Comment by mnorthuis** [comment]
Work in progress....
[bestbets.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10668356/bestbets.docx)

**Comment by mnorthuis** [comment]
Some example recent tickets for reference:
Disability comp rates: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/49897
Mental health: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/49894
Dependents:https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/49906
Payment history:  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/49893

**Comment by mnorthuis** [comment]
To finish up this ticket:
- [ ] publish draft standards in markdown in the [IA standards folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/standards)
- [ ] publish high level process for reviewing and implementing best bets in [IA process folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/process)

This will get us to documents that we can continue to route for review, utilize, and tweak as requests come in.

**Comment by jennymayoco** [comment]
- [Standards for requesting search best bets](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/requesting-search-best-bets.md) is now live in the [IA standards folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/standards)
- [Search best bets process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/process/search-best-bets-process.md) is now live in [IA process folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/process)

Marked all the above tasks as complete.

**Comment by RLHecht** [comment]
Thanks, Jenny. Going to close this.
