### ISSUE TITLE
[Spike] How to organize a new repo

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#36203]
## Background/Request
_What details are necessary for understanding the specific work or request tracked by this issue?_

New repos we create for vets-api related micro-services must be organized as best practices. 

As per [vets-api/blob/master/SECURITY.md](https://github.com/department-of-veterans-affairs/vets-api/blob/master/SECURITY.md), 
> The Department of Veterans Affairs participates in a Responsible Vulnerability
Disclosure Program through Bugcrowd. Please report any security-related issues
using our [Bugcrowd program](https://bugcrowd.com/va-vdp).      
If your Bugcrowd submission is related to an open GH issue, please include that
issue ID in the description field of your disclosure.       
But, please do not open new security-related issues. If you are a developer and
have concerns, you can reach out on our internal Slack channel
[#platform-security](https://dsva.slack.com/archives/C02K1C7175Y).

### Goal

Establish a routine for new repo creation that adheres to the best practices.

### Requirements to Consider

Compare to SECURITY.md in of vets-api repo.

---

## Tasks
- Answer the following questions:
  - What are current best practices for making a new repo?
  - Is the new vets-api-monitoring-suite repo in compliance? 

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by considerable** [comment]
@CosmicSyntax @ewilson-adhoc  - I ran this question via #platform-security and I was told we can reference that same file vets-api/blob/master/SECURITY.md that is good and current.

**Comment by ewilson-adhoc** [comment]
@considerable can we close this, or is there more work to be done on this story?
