### ISSUE TITLE
[FE] My VA: Add aria labeling within the Apply for VA Benefits section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36218]
## Background

After talking with Josh Kim regarding accessibility on My VA, he mentioned that we should consider having aria codes to assist with better screenreader functionality.

See Mid-point Review ticket #34621 for Onsite notifications, **[Josh's feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621#issuecomment-1016708550)**

- `aria-label` s for links without a visible purpose/target. 
<details>

<img width="742" alt="Screen Shot 2022-01-19 at 11 38 24 AM" src="https://user-images.githubusercontent.com/14154792/150174910-93323008-af08-4c6b-a6e1-044d2c8758a7.png">

</details>

- Opportunity to reduce the length of some of the headings that include form names by using `aria-describedby` to link the text _above_ the heading directly to the heading itself  (screenshot in details below)
<details>

<img width="556" alt="Screen Shot 2022-01-19 at 11 36 14 AM" src="https://user-images.githubusercontent.com/14154792/150174417-6def2743-8d3f-4cfa-9724-080e3812b7ce.png">

</details>

## Tasks
- [ ] **Need to discuss these changes and add appropriate tasks**

## Acceptance Criteria
- My VA will align with better screenreader accessibility, by having aria labels to identify specific information within the Apply for VA benefits section

**Comment by hdjustice** [comment]
@hdjustice reach out to Josh for a bit more clarity on these suggestions.

**Comment by hdjustice** [comment]
Hi @joshkimux - During a team discussion, we were unsure about the 2nd suggestion you provided:

> - Opportunity to reduce the length of some of the headings that include form names by using `aria-describedby` to link the text _above_ the heading directly to the heading itself  (screenshot in details below)
> 
> <img width="556" alt="Screen Shot 2022-01-19 at 11 36 14 AM" src="https://user-images.githubusercontent.com/14154792/150174417-6def2743-8d3f-4cfa-9724-080e3812b7ce.png">

In staging and production, the application numbers only show at the top of the block, and we have an `aria-describedby` for that heading.  Is this what you were looking for?
![image](https://user-images.githubusercontent.com/92328831/155597318-fc599bac-a1d8-4e2f-83ad-6beb3803411e.png)

**Comment by hdjustice** [comment]
Also @joshkimux - for the first item, it seems we already have `aria-label `s for the links.  

![image](https://user-images.githubusercontent.com/92328831/155598142-63c7f8ba-adde-4444-a226-a9cb00e7fe6b.png)

![image](https://user-images.githubusercontent.com/92328831/155598757-01a36e3e-2ee0-498c-96b1-c5c44a27548d.png)

**Comment by joshkimux** [comment]
@hdjustice That's correct! Using `aria-describedby` there removes the need to repeat it within the heading itself.

**Comment by hdjustice** [comment]
Items suggested for improved accessibility had already been implemented.  The sketch file and other mock-ups going forward will be updated to reflect what we have in production.
