### ISSUE TITLE
TUD: Implement the Prose/Gatekeeper functionality in vets-api (TUD GitHub OAuth Proxy)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#36211]
# Description
In an effort to use fewer external services, implement the Prose/Gatekeeper functionality in `vets-api`.

## Acceptance Criteria
- [x] The Gatekeeper proxy previously used for this functionality can be decommissioned.
- [x] `vets-api` github oauth proxy endpoint successfully responds to requests for github oauth from TUD UI
- [x] RSpec tests for the new TUD github oauth proxy endpoint are passing

**Comment by holdenhinkle** [comment]
I coded this up on Saturday:

vets-api pr - https://github.com/department-of-veterans-affairs/vets-api/pull/8983
tud pr - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/111

I created a new TUD endpoint to handle this - `/test_user_dashboard/tud_github_oauth_proxy` - which expects a `code` URL query param.

I just need to quickly handle some potential errors and write some rspec tests.

I'll continue this after we get the TUD redirect issues sorted out.

**Comment by holdenhinkle** [comment]
The new TUD endpoint - `/test_user_dashboard/tud_github_oauth_proxy` - grabs the temporary code that GitHub provided after a user grants access to TUD, then makes a request to `https://github.com/login/oauth/access_token` with the `client_id` and `client_secret` (which are stored in the AWS Param Store) and the `code`. Basically, we're exchanging the `code` with a `Bearer `access_token`. This must request must be made from a server, not a client (GitHub does not allow this request to made from clients).

I used `Faraday` as the `http` client to handle the request because it was already included in the `vets-api` `Gemfile` (and it's one of the most popular `Ruby` `http` clients).

Here's the code to handle the request and response:

```
    def github_oauth_access_token_request(code:)
      url = 'https://github.com/login/oauth/access_token'
      body = {
        client_id: Settings.test_user_dashboard.github_oauth.client_id,
        client_secret: Settings.test_user_dashboard.github_oauth.client_secret,
        code: code
      }.to_json
      response = Faraday.post(url, body, 'Content-Type': 'application/json')

      response.body.split('&').each do |string|
        if string.start_with?('access_token=')
          array = string.split('=')
          return { array[0] => array[1] }
        end
      end
    end
```

We parse the response and create a hash that looks like:
```
{
  access_token: 'asdfasdfasdf'
}
```

And render it as `json`.

Btw, the request from this endpoint is made from the OAuth callback endpoint in the TUD application. Here's that file - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/blob/9fa414343599e03fca348786e27d0988814e605d/src/pages/oauth.js

**Comment by holdenhinkle** [comment]
Darius wrote a test yesterday for the new proxy controller.

I think he's going to write some code to handle errors, then another test.

**Comment by holdenhinkle** [comment]
vets-api PR is submitted - https://github.com/department-of-veterans-affairs/vets-api/pull/8983

**Comment by holdenhinkle** [comment]
TUD PR - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/111

**Comment by holdenhinkle** [comment]
Both PRs were finally merged.

**Comment by pjhill** [comment]
Yay, thanks for sticking with this, taking feedback, and tackling this last minute change to the product!
