### ISSUE TITLE
Iterate designs based on Collaboration Cycle Midpoint Review feedback

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36228]
- [x] Feedback prioritized in terms of what will be updated immediately vs long term vs backlogged
- [x] Feedback tracked on excel
- [x] Wireframes updated
- [x] Reviewed across internal team

**Comment by JordanSWhite** [comment]
Will be estimated once we've received the feedback.

**Comment by graceerinhongfrog** [comment]
Feedback spreadsheet: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/Sprint%203%20Design%20Feedback.xlsx
