### ISSUE TITLE
Allow AFS devs to merge PRs created in gibct-data-service

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#36227]
## Description
Currently, AWS devs cannot merge PRs they create in gibct data service. Only platform can. This is a request to allow AFS devs to merge in PRs created in the gibct-data-service project. - https://github.com/department-of-veterans-affairs/gibct-data-service
## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
@af-manish : would this be the [afs-code-reviewers team](https://github.com/orgs/department-of-veterans-affairs/teams/afs-code-reviewers), or are you looking to create a new team for gibct?

**Comment by af-manish** [comment]
> @af-manish : would this be the [afs-code-reviewers team](https://github.com/orgs/department-of-veterans-affairs/teams/afs-code-reviewers), or are you looking to create a new team for gibct?

Thx John. Yes, that team.

**Comment by jsgarmon** [comment]
Done
![image](https://user-images.githubusercontent.com/47490730/152393535-cb165399-73cf-4a5d-95b3-f04f9165a0f8.png)

**Comment by af-manish** [comment]
@jsgarmon  It looks like we are not able to still merge into the gibct project. <cc @rileyanderson > Can you help?

**Comment by af-manish** [comment]
This is one that one of my team members couldn't merge: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/903

Here's the support requesting asking for someone to merge it for him: https://dsva.slack.com/archives/CBU0KDSB1/p1647436939527219

**Comment by jsgarmon** [comment]
If your team member is in the `afs-code-reviewers` group, he/she should be able to merge anything that's been approved. Can you give me any more specifics? Typically, there is a message by the merge button saying why a merge cannot be completed.

**Comment by af-manish** [comment]
I created a test PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/905 and am seeing this:

<img width="1059" alt="Screen Shot 2022-03-16 at 4 25 55 PM" src="https://user-images.githubusercontent.com/86117086/158684557-389ef47c-aa5f-4d8a-ba20-f36a22b1dd29.png">

**Comment by jsgarmon** [comment]
any change now?

**Comment by af-manish** [comment]
> any change now?

still same

**Comment by rileyanderson** [comment]
> > any change now?
> 
> still same

@af-manish Can you try now? I approved the PR.

**Comment by af-manish** [comment]
Ok, so its related to being able to approve prs?

**Comment by af-manish** [comment]
Ok, I think this is good as it is. Closing
