### ISSUE TITLE
Audit Front-End Unit Tests

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#36238]
# Description
Doing an audit of all of our front-end components to get an idea of what our current unit tests cover, listing out areas we currently test and areas we do not presently test but should test.  Also includes retro of the looping and button overwriting login container and determining if there are unit tests that can prevent that in the future.

# User Story
**As a** Identity Front-End Engineer
**I want to** Audit and improve my existing unit tests and add new ones
**So that** I can ensure I have proper coverage from a testing and QA standpoint

# Acceptance Criteria
- [ ] Create FE tests audit and improvement documentation

**Comment by Kwoly** [comment]
https://vfs.atlassian.net/wiki/spaces/~207362431/pages/2076672130/Identity+FE+Tests+Audit
