### ISSUE TITLE
Create list of 10 products to be included in Q1's dashboard initiative

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#36232]
Create list of 10 products to be included in Q1's dashboard initiative.

- [x] List of products has been created

**Comment by holdenhinkle** [comment]
Joe's thoughts:
So thinking about getting a good spread of differing results - This is not set in stone, just a thought

- 10 Products
  - 6 Active products
    - 2 that show good results (good in terms of having the most types of data associated)
    - 2 that show mid level results
    - 2 that show bad/few results (bad in terms of,they have lots of blanks so we can't associate it well)
  - 2 forms products (one that shows good results if possible, one that doesn't)
  - 2 legacy products (one that shows good results if possible, one that doesn't)

Peter's thoughts:
Special considerations for product selection --

- legacy product — not in active development, not touched for >6 months
- form product — uses the form system
- active — under active development

Curt's thoughts:
I'd also say try and keep the following in mind:

- One that has all our test types
- One that has some
- One that has none/barely any

**Comment by holdenhinkle** [comment]
Chat with Darius about this ticket because he probably has more insight into products than I do because I never touch any of them. He made the following suggestions:

Active products:

- facility location
- vaos

Form products:

- Open cypress and looks for tests that use the form tester
- 10cg (or something)
- one for filing claims

Legacy:

- covid stay informed tool (the one our team worked on over a year ago)

**Comment by holdenhinkle** [comment]
Convo with Peter:

Form products:
527ez pension benefits

**Comment by holdenhinkle** [comment]
All products that have cypress tests that use the form-tester:

- ask-a-question
- caregivers
- disability-benefits/686c-674
- edu-benefits/994
- edu-benefits/1990
- edu-benefits/1995
- edu-benefits/5490
- edu-benefits/5495
- edu-benefits/5655
- hca
- health-care-questionnaire/questionnaire
- my-education-benefits
- vre/28-1900
- vre/28-8832

**Comment by holdenhinkle** [comment]
Apps that have contract tests:

- ask-a-question
- coronavirus-vaccination
- facility-locator
- messages

**Comment by holdenhinkle** [comment]
Legacy apps

Asked Tim Wright if he knows of any - https://dsva.slack.com/archives/C01CHAY3ULR/p1643740640706679

**last updated > 3 months ago**

- messages - last updated 8 months ago, e2e, unit
- discharge-wizard - last updated 4 months ago, e2e, unit
- ask-a-question - last updated 3 months ago, e2e, unit, contract
- caregivers - last updated 4 months ago, e2e, unit
- coronavirus-screener - last updated 4 months ago, e2e, unit
- coronavirus-vaccination-expansion - last updated 3 months ago, e2e
- coronavirus-vaccination - last updated 4 months ago, e2e, unit, contract
- terms-and-conditions - last updated 4 months ago, e2e
- third-party-app-directory - last updated 8 months ago, 
- yellow-ribbon - last updated 3 months ago, e2e, unit

## Organized by type of tests
**has e2e + unit**

- messages - last updated 8 months ago, e2e, unit
- discharge-wizard - last updated 4 months ago, e2e, unit
- caregivers - last updated 4 months ago, e2e, unit
- coronavirus-screener - last updated 4 months ago, e2e, unit
- yellow-ribbon - last updated 3 months ago, e2e, unit

**has e2e + unit + contract**

- ask-a-question - last updated 3 months ago, e2e, unit, contract
- coronavirus-vaccination - last updated 4 months ago, e2e, unit, contract

**has e2e**

- coronavirus-vaccination-expansion - last updated 3 months ago, e2e
- terms-and-conditions - last updated 4 months ago, e2e

**has unit**

- third-party-app-directory - last updated 8 months ago, unit

**Comment by holdenhinkle** [comment]
Darius Dzien  2:09 PM
`src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js` is the long test I mentioned, looks like it’s for the Caregivers team

**Comment by holdenhinkle** [comment]
# Proposed List
- caregivers
  - has the longest running Cypress tests which use the `form-tester`
- ask-a-question
  - Legacy product. Has e2e, unit, contract
- coronavirus-vaccination
  - Legacy product. Has e2e, unit, contract
- ask-a-question
  - Legacy product. Cypress tests use the `form-tester`
- comparison tools
  - Active on TestRail
- facility-locator
  - Active product
- vaos
  - Active product
- third-party-app-directory
  - Legacy product. Only unit tests
- terms-and-conditions 
  - Legacy product. Only e2e tests
- edu-benefits/1995
  - Product is nested in ed-benefits (test nested product).  Cypress tests use the `form-tester`

**Comment by holdenhinkle** [comment]
Products that use `form-tester` (Google sheet) - https://docs.google.com/spreadsheets/d/1mNycNGFGk0gbLIyVyCKj_JDss4eylNajhJ-15Rlo_lQ/edit?usp=sharing

**Comment by CBonade** [comment]
In implementing the manifest IDs, we ran into the trouble that the `third-party-app-directory` does not have a manifest. Let's replace it with the `personalization/profile` product, which will currently be titled as `Address Validation`. This directory contains multiple products and will be a good test case for how we can solve these issues.

**Comment by holdenhinkle** [comment]
That sounds good to me!

**Comment by pjhill** [comment]
Thanks for creating the list.
