### ISSUE TITLE
Create official post-mortem documentation around latest sign-in bug

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#36239]
# Description
There is currently a bug on production that causes a button to load on the sign-in page, then be overwritten by our login containers.  Recently another user introduced lazy loading that caused a button to overwrite our containers.  On the sign-in page we have a flipper that turns off most of the header nav, when the sign-in page loads it tries to insert content into the nav bar, this doesn't work when the nav bar doesn't exist.

This is to create a post-mortem for the bug, and create tickets to prevent this from happening in the future so lazy loading can be re-implemented.

**Comment by Kwoly** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022-01-27-sign-in-page-rendered-wrong-component.md
