### ISSUE TITLE
Investigate 502 issues related to Traefik in EKS DEV 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36241]
## Description
Investigate the issue with  EKS,on the dev-api domain has been unreachable since approximately 01/31/2022 - 1:57pm ET.

Perform more research needed to know who to be proactive in detecting and responding to issues like this.

http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22traefik%5C%22%7D%20%7C%3D%20%5C%22failed%5C%22%22%7D%5D

## Background/context 
The following was discussed.

Thoughts about it being related to  dev ingress to fail  invalid traefik manifest 
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/305

slack thoughts:  https://dsva.slack.com/archives/CTYQL39FE/p1643663959130449

---
## Tasks
- [ ] Meet with team to discuss the issue in full.   

## Acceptance Criteria 
- [ ] Creation of a Playbook for K8 issue and points of failure.

**Comment by jhouse-solvd** [comment]
@zachclarity - I believe this has been taken care of. Can you please confirm and close out if no longer needed?

**Comment by oseasmoran73** [comment]
Closing ticket as this issue has been resolved

Additional details can be found in [slack](https://dsva.slack.com/archives/CTYQL39FE/p1643664625130509?thread_ts=1643663959.130449&cid=CTYQL39FE)

**Comment by oseasmoran73** [comment]
Feel free the reopen as needed @zachclarity
