### ISSUE TITLE
[BE] | 10-10 EZ Change to New Endpoint

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36248]
## High Level User Story/ies

As a Veteran, I need to apply for VA benefits so I can receive support.

## Context

On 1/31/22 we received a request from the 10-10EZ team to change an endpoint due to a Cloud move.
Specifically:

The Cloud move is already completed and traffic is being proxied from old endpoint to the new one.
Need to request permanent change to the host endpoint from the client app as below:
 
## Staging
Old host: `vaww.esrpre-prod.aac.va.gov`
New host: `sqa.ves.va.gov`

## Production
Old host: `vaww.esr.aac.va.gov`
New host: `ves.va.gov`

### What must be true in order for you to consider this epic complete? 
- Successful tests of VA.gov's 10-10EZ product pointing to the new Cloud endpoint 

## Acceptance Criteria
- Successful submissions of the 10-10EZ applications

**Comment by jchilders** [comment]
Untagged for sprint 66 so we can groom per normal.

**Comment by SKasimow** [comment]
@jchilders - can you add in what additional tasks and acceptance criteria are needed and point this so we can close loop with Josh on plans.

cc @RudyOnRails

**Comment by SKasimow** [comment]
@jchilders @kevwalsh fyi - added you both to the ticket and labeled for sprint 67. we can decide who will own when we do sprint planning on 2/7.

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---10-10-Team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/36248?planning-poker) with ZenHub @jchilders

**Comment by jchilders** [comment]
@RudyOnRails I usually move it to validate after the PR has been merged, or the story is otherwise "done" from my point of view. Let's talk about this further offline if you'd like.

**Comment by RudyOnRails** [comment]
This change has been live in production since Friday.

@SKasimow I think we are ok to close so I did, but if you or someone can do a production test or look at a metric somewhere to confirm 1010EZ's are coming in ok, then feel free to reopen.

**Comment by SKasimow** [comment]
@RudyOnRails Yes, I can see successful submissions for 1010ez through-out the month with no interruption. I also saw a note Joshua responded to on this confirming he was seeing traffic on new end-points, so we are indeed good to close.
