### ISSUE TITLE
Complete Onboarding - Security Engineer

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#36261]
- [x] Setup IDE on work station, ensure environment is setup to run python scripts
- [x] Setup docker on workstation, get ubuntu running (used for github action simulations critical to our tasks)
- [x] Setup and run sonarqube scan against vets-api
- [x] Conduct initial review of vets-api logging capabilities, initiate conversations with security team to draft plan to implement log streaming to splunk
- [x] install slack as app on workstation
- [x] familiarize yourself with grafana and sentry (documentation is in team folders)
- [x] Setup OWASP Zap

**Comment by sylvesterlee1911** [comment]
Schedule.

**Comment by sylvesterlee1911** [comment]
Complete.
-Sonarqube running on windows machine.  Vets api cloned to local machine and scanned.
-Need to schedule time to discuss what was found scanning vets api.
-Docker has been setup on a ubuntu box.  Confirmed connection.  I need to run test with our data.

**Comment by sylvesterlee1911** [comment]
Meet with Troy Mosher (security lead) to find out how splunk currently is set up.  Then write plan with his team how to transition from loki to splunk.  For security logs only.

**Comment by joeniquette** [comment]
Need to reopen the following tasks for additional followup:

-  Setup IDE on work station, ensure environment is setup to run python scripts
-  Conduct initial review of vets-api logging capabilities, initiate conversations with security team to draft plan to implement log streaming to splunk
-  familiarize yourself with grafana and sentry (documentation is in team folders)
-  Setup OWASP Zap
