### ISSUE TITLE
Update VAOS Team in flipper admin

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#36264]
## Description 
As product, I want eng leads and product team members to have access to the feature flipper admin so that they can control the rollout and testing of features.

## Tasks
- Add Jeff Roof to admin list
  - jeff.roof@adhocteam.us

## Technical Notes
Jeff has an ID.me account setup with this email address already.

The file to update: https://github.com/department-of-veterans-affairs/vets-api/blob/448d67a4120d0743c71174b0a71ca3d4febfb4c5/config/settings.yml#L658

**Comment by jenniemc** [comment]
Hi @JRRoof, you've been added as admin user for toggle flipper flag. https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L819

cc @ldelacosta

**Comment by JRRoof** [comment]
I now have access.  Thanks!
