### ISSUE TITLE
[Vets-API] Mount vets-api-mockdata in EKS dev

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#36265]
## Description
Mockdata is used on dev.va.gov stack for MPI calls (and many other things). Without it, auth fails for verified users. 

## Background/context 
[Recent conversation in DSVA Slack](https://dsva.slack.com/archives/CJYRZK2HH/p1643663456507999) #vsp-operations channel

## Technical notes
Need to mount the vets-api-mockdata repo inside of a volume that can be made available to the Vets-API deployment running in EKS dev 

---
## Tasks
- [x] Need to mount the vets-api-mockdata repo inside of a volume that can be made available to the Vets-API deployment running in EKS dev 

## Acceptance Criteria 
- [x] Log in works for verified users in dev.va.gov

**Comment by jhouse-solvd** [comment]
Tied to #35618 for tracking.

**Comment by jhouse-solvd** [comment]
@jbritt1 - If you can: 

- clarify tasks 
- link relevant PRs
- move to "Review" when ready

...that would be awesome. Thank you!

**Comment by jbritt1** [comment]
Some commits that ultimately led to this working:

- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/201/commits/8a77e621be465a4de168ed96f94b61f96b10cd16
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/201/commits/0fd3b42b2d3f4d28e496a492792abac866194cea
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/201/commits/8e579220f6f0509c7b65c17d5f95ac7051e07a6e

All are in a draft pull request that has tracked all of the work so for on this initiative: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/201

What we had to do was use an init container to pull and mount the [vets-api-mockdata GitHub repo](https://github.com/department-of-veterans-affairs/vets-api-mockdata) and then mount it to the vets-api pod in an expected location.

**Comment by jbritt1** [comment]
TODO: cleanup the image used for git commands. Currently using a test image in a `jb-test` ECR repo I used to testing. Very light lift, but noting here as to not forget.

**Comment by jbritt1** [comment]
Made proper repo in GitHub and ECR to house the alpine-git image 

GitHub repo: https://github.com/department-of-veterans-affairs/vsp-infra-git

ECR Repo addition: https://github.com/department-of-veterans-affairs/devops/pull/10751

Manifest update: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/d0df00cf8e4c80dd136cf2bec5268e8efea9466e
