### ISSUE TITLE
Adding Mike Haley to DSVA Slack

### ISSUE THREAD

**Issue by tBaxter** [department-of-veterans-affairs/va.gov-team#36274]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Mike Haley to DSVA slack. He is a new engineer here at Ad Hoc on the PST program.

Are you requesting to add an individual as a:

- Full member

**Comment by LEHigley** [comment]
need the email address

**Comment by tBaxter** [comment]
mike.haley@adhocteam.us
