### ISSUE TITLE
Discovery: Research Argo API

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#36271]
We will want to research the Argocd API to prepare for future work making API calls to Argo from platform-console. We will want things like deployment status, sync status, k8s resources, etc. [Swagger docs here](https://github.com/argoproj/argo-cd/blob/master/assets/swagger.json#L5142-L5190)

**Comment by LindseySaari** [comment]
You can find the Swagger docs by setting the path to /swagger-ui in your Argo CD UI's: http://argocd.vfs.va.gov/swagger-ui

**Comment by garfield786** [comment]
Meeting notes Naoufal, Lindsey and Eric.
List of functionalities from ArgoCD
1. Sync Status
2. App Health
3. Current Commit
4. Previous Commit
5. Deploy Times

**Comment by garfield786** [comment]
### GET API for ArgoCD

- You will need to be authenticated!

1. Sync Status
endpoint: `/api/v1/applications/{name}`
```json
"status": {
    "sync": {
        "status": "String",
        "revision": "String"
    },
```

2. App Health
endpoint: `/api/v1/applications/{name}`
``` json
"status": {
    "health": {
        "message": "string",
        "status": "string"
    },
}
```

3. Current Commit
endpoint: `/api/v1/applications/{name}`
```json
"status": {
    "sync": {
        "status": "String",
        "revision": "String"
    },
```

4. Previous Commit, last item in the history array
endpoint: `/api/v1/applications/{name}`
```json
"status": {
    "history": [
        {
        "deployStartedAt": {},
        "deployedAt": {},
        "id": "string",
        "revision": "string",
        "source": {}
        }
    ]
}
```

5. Current Deploy Time and Author
endpoint: `/api/v1/applications/{name}/revisions/{revision}/metadata`
```json
{
  "author": "string",
  "date": {
    "nanos": 0,
    "seconds": "string"
  },
  "message": "string",
}
```

**Comment by LindseySaari** [comment]
@garfield786 What does the authentication piece entail? Since argocd is behind socks, will that pose any barriers for us?

**Comment by garfield786** [comment]
Yes that's what I meant, a JWT so your app can authenticate to ArgoCD

**Comment by LindseySaari** [comment]
> @LindseySaari Yes that's what I meant, a JWT so your app can authenticate to ArgoCD

Awesome! Would you want to look into the SOCKS piece that I mentioned in my above comment?

**Comment by garfield786** [comment]
if your application is going to run on the same cluster as ArgoCD you don't need SOCKS. Is that the case ?

**Comment by LindseySaari** [comment]
> if your application is going to run on the same cluster as ArgoCD you don't need SOCKS. Is that the case ?

Yes, I believe that both argocd and platform-console will both live in the utility cluster

**Comment by LindseySaari** [comment]
@garfield786 Do the api docs say anything about the ttl of the returned token? I wonder if we will want to get a new token per request or maybe cache the token for a period of time?

**Comment by garfield786** [comment]
It does not tell about TTL, but I think you can set it when you set your cookie no ?

**Comment by LindseySaari** [comment]
> It does not tell about TTL, but I think you can set it when you set your cookie no ?

I'm guessing the jwt will have a TTL. Eric and I talked about storing the jwt in postgres or possibly caching it for reuse per user.

**Comment by garfield786** [comment]
JWT token generated by ArgoCD can be customized to expire after certain time or not to expire at all, you can generate a JWT token after creating a local user and give them necessary RBAC permission / project
