### ISSUE TITLE
Refactor Manifest Ingest to Use Product IDs

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#36287]
# Description
Based on the Product List CSV/Manifest/Product IDs, we need to update our approach to ingestion approach to focus on the Product ID and a single product instead of many.

## Acceptance criteria
- [ ] Ingestion approach is refactored to reference a specific Product ID
- [ ] Results in BigQuery/Domo verify that it is referencing a single Product based on the specified ID

**Comment by JoeTice** [comment]
Duplicate
