### ISSUE TITLE
Research a Method for Associating Product IDs with TestRail

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#36289]
# Description
Currently, TestRail is setup to track testing activity based on teams. Often a VFS team will have a single shared account due to a request from Platform to keep licensing costs for the tool down.

## Tasks
- [x] Come up with a way to get at least 10 products linked to the product id in our product directory.

## Acceptance Criteria
- [x] TestRail projects are linked to the correct products in our product directory.

**Comment by CBonade** [comment]
After chatting with Peter for this task, we decided to add the existing testrail `project id` to the GItHub product directory CSV as a new column.

The one caveat here is that testrail data is team-focused as opposed to product-focused, so only a small number of connections were able to be made here. This will need to be overcome in the future to expand out Testrail data to more products.

**Comment by pjhill** [comment]
Nice, there is indeed a bit of a problem looming that we have kicked down the road. We'll need to address a future fix to TestRail projects in the future.
