### ISSUE TITLE
[SW-Content] Audit existing pages for compliance with VA design-style, 508 compliance, and content standards [SWC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36283]
## Product Outline
[Sitewide Content](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content)

## High Level User Story
As a _____, I need _____ so I can _____.

## OKR
-Improve content standards, remove 508 issues

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by RLHecht** [comment]
We can close this. Work complete.
