### ISSUE TITLE
Design for newly hardened Medical records pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#36293]
## Issue description
We need to doublecheck the newly hardened Medical records page to ensure consistency of design now that the new content model has been implemented. 

## Problem to be solved
- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)
- Medical records page needs to account for padding around either VA blue button widget or Cerner medical records link

Medical records
- [Content model mural - Medical records](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595862359396/4d517fc3ffe0e6e9ec9fb81ff4325a4d7d1946d4)
- Example [Medical records page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/medical-records-office/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/medical-records-office
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/medical-records-office

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152041575-75944bda-2664-43f4-9552-fde87487ce07.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152041852-652a0cee-8688-418c-8e46-dd3cc331ff8e.png)

</details>

## Tasks
- [ ] Create design spec for front end implementation 

## Acceptance Criteria
Design includes
- General spacing and font specs
- Heading levels
- Consistent semantic markup and visual design
- Examples with more than one location
- Example of VA Blue button implementation
- Example for Cerner implementation

**Comment by nicko-amida** [comment]
Update! Here are both VA Blue button and Cerner link versions of the designs. The main dev notes are on the VA Blue button version of the page, as the Cerner link page is the exact same except for the Cerner link replacing the VA Blue button CTA:
- UXPin design for [Medical records office - VA Blue button](https://preview.uxpin.com/2e7af3cf44ec68fd41899e7ddb6071ea3bb2b61b#/pages/147616704/documentation/no-panels?mode=i), including dev notes
- UXPin design for [Medical records office - Cerner link](https://preview.uxpin.com/2e7af3cf44ec68fd41899e7ddb6071ea3bb2b61b#/pages/147640656/documentation/no-panels?mode=i)

**Comment by mmiddaugh** [comment]
This will be implemented in the front end in #37365
