### ISSUE TITLE
Integrate Formation releases with the Github release tab

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#363]
Moved from: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15407#event-2407469707

Acceptance criteria:
- When someone needs to release a new version of the npm module, they can run a command that will create a GH release as well
- GH release info should have the changes listed in that release (https://github.com/usds/us-forms-system/releases is a good format example, as well as other open source projects)

We need to do some research to determine what the workflow is for other open source projects, but it's important that we document what's changing in each release of Formation as we go forward.

This is for future reference. This is a post regarding integrating github releases into the Jenkins continues integration flow. Github tags activates a release.

https://medium.com/@systemglitch/continuous-integration-with-jenkins-and-github-release-814904e20776

**Comment by rianfowler** [comment]
`yarn release` command in vfs tools seems to expect a version of Node that supports ES modules, but we’re only on v10.

**Comment by caw310** [comment]
@k80bowman IS this still relevant?

**Comment by k80bowman** [comment]
Closing in favor of #35993
