### ISSUE TITLE
Adding "Application" names to headers to assist with data endpoint mapping

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#3630]
As part of the endpoint mapping we be adding the "application" name to each request that is made.

We will be leveraging the list of "app" names stored in the manifest files.

**Comment by cvalarida** [comment]
Adding a little more flavor:

In the [`startApp`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/startup/index.js#L32), we can add a bit that sets a `window.appName` (or something). In the [`apiRequest` helper](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/api/index.js#L68), we could set a new header using the value in `window.appName`.

This would then be sent off with every API request, and trackable if something weird happens (like the `window.appName` is `undefined` or something unexpected).

**Comment by brandonrapp** [comment]
Here is what we used to populate the name of the applications in the header:

find -name 'manifest.json' | xargs -I _ rg '.*"entryName": "(.*)".*' --replace '$1' _ | sort

0993-edu-benefits
0994-edu-benefits
0996-higher-level-review
1990-edu-benefits
1990e-edu-benefits
1990n-edu-benefits
1995-edu-benefits
526EZ-all-claims
526EZ-claims-increase
5490-edu-benefits
5495-edu-benefits
686-dependent-status
account
auth
beta-enrollment
burials
chapter31-vre
chapter36-vre
claims-status
connected-accounts
dashboard
dependents-view-dependents
disability-my-rated-disabilities
discharge-upgrade-instructions
facilities
feedback-tool
gi
hca
id-card-beta
letters
my-health-account-validation
pensions
post-911-gib-status
pre-need
profile-360
proxy-rewrite
public-outreach-materials
search
static-pages
terms-and-conditions
vaos
verify
veteran-id-card
veteran-representative
vic-v2

In reality, though, I'm guessing some of these will never come up. Like auth or proxy-rewrite. I also think static-pages won't.

**Comment by brandonrapp** [comment]
This work was completed.
