### ISSUE TITLE
Discovery: Yarn Workspaces

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#36308]
## Description

[Workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) are a way to set up your package architecture that’s available by default starting from Yarn 1.0. It allows you to setup multiple packages in such a way that you only need to run yarn install once to install all of them in a single pass.

We have many dependancies within vets-website and as we move more towards bringing autonomy to the app teams, they will need to manage their own dependancies. Yarn workspaces may be a step in that direction for the platform. We should probably also look into [Lerna](https://github.com/lerna/lerna) while we're here.

This should be timeboxed to 1 sprint.

## Definition of Done / Questions to answer

- [ ] Initial research for implementing Lerna into vets-website
- [ ] Report on what the benefits / risks are
- [ ] Does anything in vets-website need to change to support workspaces?
- [ ] Recommendation on whether we should offer this as a service to App teams

**Comment by ddzz** [comment]
I've worked on [this open-source project](https://github.com/bmish/check-dependency-version-consistency) that should be helpful with maintaining dependencies if we decide on using workspaces.

**Comment by timwright12** [comment]
@laineymajor @rmessina1010 should this be closed out? I think we completed it on another ticket

**Comment by rmessina1010** [comment]
Closing. Completed as tickets: #40214  and #39814

**Comment by rmessina1010** [comment]
Closing. Completed as tickets #39814 and  #40214
