### ISSUE TITLE
Fix forms utilities test

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36302]
## Description
The `get focusable elements.should return an array of focusable elements` test in src/platform/forms-system/test/js/utilities/ui.unit.spec.js failed at deploy time two days in a row. I could not figure out quickly what the issue was, so I submitted a [PR to temporarily skip it](https://github.com/department-of-veterans-affairs/vets-website/pull/20092), but we do need to figure out what's going on and get it fixed.

## Details
[First failure in GHA](https://github.com/department-of-veterans-affairs/vets-website/runs/5011717854?check_suite_focus=true)

I was unable to force the test to fail locally. Things I tried:
- Checking out the branch that failed
- removing node_modules and reinstalling
- Running the tests using ` CHOMA_SEED=mfjiUe68aE yarn test:unit --reporter=spec` so that they run in the same order that failed in GHA

## Acceptance Criteria
- [ ] Test is fixed and the `.skip` is removed

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
