### ISSUE TITLE
Access for Elizabeth Neal (eneal49)

### ISSUE THREAD

**Issue by ENeal49** [department-of-veterans-affairs/va.gov-team#36300]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Elizabeth Neal

### Your Email

elizabeth.neal@agile6.com

### Name of Your Team

Platform-CMS

### Service(s) You Want Access To

SOCKS

### Public SSH Key

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDYu/5hG2u1ZU+b2lt8xNj8dNNNI2k+0guLOJjXb1DAHV3CZZuGjqhhbZtwL4PxO5qjbtnhVHNRdr3GP7qse+5yLMnnedTuIWMME31KoOKg8gJePtU4zcM5+VFP0NUveOym+hAmhMt6yqWcAsnpT0ukCvVTlfTe8OrPlj2x6skrnL9udQ8sqv6j7IwtZnwiF+fqLvy4eHc7B4RV4mcxyKepsBQpjPYsIoiMc5ofa5E6p3HVJUe9XoiDBtokupd0qpv7Sim0AHH9NH24Kkuj59qxwXXh/Y4Fv6KG4ovb24wRfacX8ZIAh/JSapaOyCgXdHnWHcxcpJcioEol3NOLQ+4RHvBSWsEl6dL2mdbWRMHJNTHGe9MQdIFQ0pS7VeKecG7YTLAYyx4EF616cGtlfNnjn9v6SQzht2qGlazFzo/gL/0ULxfLVtkdGISZ1JXaNi46C2VDNdNqTVN35gdRFRv0cSqmzg1OQ73kko5nbAopEbHwDUoVozCC//d/abjyDE= elizabeth.neal@agile6.com
```

### Access Expiration

ongoing

**Comment by ElijahLynn** [comment]
@ENeal49 is already setup, but somehow her key got deleted on her box so we need to replace it with this one. Thanks.

**Comment by oseasmoran73** [comment]
Updated SSH Key. You should be all set @ENeal49 .

Closing ticket.
