### ISSUE TITLE
[BE] | Discovery | EVSS Sunset

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36307]
## Description

The Lighthouse API  team has asked if any of our apps utilize EVSS services.  The current EVSS Services will be going away. 

- [x] Determine whether any of our applications leverage EVSS
~~- [ ] Add to spreadsheet below (on VA.gov network):~~

https://dvagov-my.sharepoint.com/:x:/g/personal/kelly_lein_va_gov/Ean3c9spOOFGsCEmJp1h-kABdTypjSL3P8ogqzjQrFh86g?e=a8gsUj

non-emoji link: `https://dvagov-my.sharepoint.com/:x:/g/personal/kelly_lein_va_gov/Ean3c9spOOFGsCEmJp1h-kABdTypjSL3P8ogqzjQrFh86g?e=a8gsUj`

![image.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/b8c73a50-0891-40c6-99fc-315ddfcaa217)

**Comment by SKasimow** [comment]
Hi @kellylein - James checked the code and isn't seeing any references to EVSS but can you provide the hostnames so we can be sure? 

+ @MickinSahni

**Comment by kellylein** [comment]
I'm not sure about the host names but @drorva may be able to help more there.

**Comment by SKasimow** [comment]
Hi @drorva  - can you provide some guidance to us on how we can determine whether our apps use EVSS today?

**Comment by drorva** [comment]
So http://grafana.vfs.va.gov/d/XYv1D0D7k/external-service-front-end-source?orgId=1&var-data_source=Prometheus%20(Production)&var-frontend_app=All&var-service=All
shows the relationship between frontend apps and backends.

The frontend app names are described in https://raw.githubusercontent.com/department-of-veterans-affairs/content-build/master/src/applications/registry.json and backends.

Note however, that apps that submit via a background job are not included in here. It's only apps where the frontend talks directly to vets-api and waits for the result that are covered.

The following are the EVSS ones AFAICT.

> EVSS/Claims <- claims-status
EVSS/Claims <- dashboard
EVSS/Claims <- mobile
EVSS/Common <- dashboard
EVSS/Common <- disability-my-rated-disabilities
EVSS/Common <- profile
EVSS/DisabilityCompensationForm <- 526EZ-all-claims
EVSS/DisabilityCompensationForm <- disability-my-rated-disabilities
EVSS/Documents <- mobile
EVSS/GiBillStatus <- 10203-edu-benefits
EVSS/GiBillStatus <- post-911-gib-status
EVSS/Letters <- letters
EVSS/Letters <- mobile

**Comment by SKasimow** [comment]
Thank you @drorva 

cc @jchilders @RudyOnRails @MickinSahni

**Comment by SKasimow** [comment]
@jchilders need your comment on what research was done and why incomplete.

**Comment by RudyOnRails** [comment]
> @jchilders need your comment on what research was done and why incomplete.

Here's an [example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36504#issuecomment-1033848892) of what I did for mine. Take, tweak, or toss...

**Comment by SKasimow** [comment]
@jchilders - does droves comment above help you to determine whether we are using EVSS today?

**Comment by SKasimow** [comment]
rolling over to sprint 67

**Comment by RudyOnRails** [comment]
Ok so I matched up the FE applications below with the entry If found in the FE registry, doesn't look like any are ours.

> EVSS/Claims <- claims-status
```
{
appName: "Claims Status",
entryName: "claims-status",
rootUrl: "/track-claims",
template: {
title: "Track Claims",
layout: "page-react.html",
description: "Track the status of your VA claims and appeals."
}
}
```

> EVSS/Claims <- dashboard
```
{
appName: "Dashboard",
entryName: "dashboard",
rootUrl: "/my-va",
template: {
title: "My VA",
layout: "page-react.html"
}
}
```




> EVSS/Claims <- mobile
```
No app found in registry
```

> EVSS/Common <- dashboard
```
  {
    "appName": "Dashboard",
    "entryName": "dashboard",
    "rootUrl": "/my-va",
    "template": {
      "title": "My VA",
      "layout": "page-react.html"
    }
  }
```

> EVSS/Common <- disability-my-rated-disabilities
```
  {
    "appName": "Rated Disabilities",
    "entryName": "disability-my-rated-disabilities",
    "rootUrl": "/disability/view-disability-rating/rating",
    "template": {
      "layout": "page-react.html",
      "vagovprod": true
    }
  }
```

> EVSS/Common <- profile
```
  {
    "appName": "VA Profile",
    "entryName": "profile",
    "rootUrl": "/profile",
    "template": {
      "title": "Your Profile",
      "layout": "page-react.html"
    }
  }
```

> EVSS/DisabilityCompensationForm <- 526EZ-all-claims
```
  {
    "appName": "21-526EZ disability compensation claim form",
    "entryName": "526EZ-all-claims",
    "rootUrl": "/disability/file-disability-claim-form-21-526ez",
    "template": {
      "title": "File for disability benefits",
      "layout": "page-react.html",
      "description": "Learn how to apply online for disability compensation.",
      "hideFromSidebar": true
    }
  }
```

> EVSS/DisabilityCompensationForm <- disability-my-rated-disabilities
```
  {
    "appName": "Rated Disabilities",
    "entryName": "disability-my-rated-disabilities",
    "rootUrl": "/disability/view-disability-rating/rating",
    "template": {
      "layout": "page-react.html",
      "vagovprod": true
    }
  }
```

> EVSS/Documents <- mobile
```
No app found in registry
```


> EVSS/GiBillStatus <- 10203-edu-benefits
```
  {
    "appName": "22-10203 Education benefits form",
    "entryName": "10203-edu-benefits",
    "rootUrl": "/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203",
    "template": {
      "vagovprod": true,
      "title": "Apply for the Rogers STEM Scholarship",
      "heading": "Apply for the Rogers STEM Scholarship",
      "layout": "page-react.html",
      "description": "Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today.",
      "order": 1,
      "hideFromSidebar": true,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "name": "Education and training",
          "path": "education/"
        },
        {
          "name": "Other VA education benefits",
          "path": "education/other-va-education-benefits/"
        },
        {
          "name": "Edith Nourse Rogers STEM Scholarship",
          "path": "education/other-va-education-benefits/stem-scholarship/"
        },
        {
          "name": "Apply for the Rogers STEM Scholarship",
          "path": "education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203"
        }
      ]
    }
  }
```


> EVSS/GiBillStatus <- post-911-gib-status
```
  {
    "appName": "Post 9/11 GI Bill Status",
    "entryName": "post-911-gib-status",
    "rootUrl": "/education/gi-bill/post-9-11/ch-33-benefit/status",
    "template": {
      "layout": "page-react.html",
      "title": "Check Your Post-9/11 GI Bill Benefits Status",
      "heading": "Check your Post-9/11 GI Bill benefits status",
      "display_title": "Check Post-9/11 GI Bill benefits",
      "collection": "education",
      "spoke": "Manage benefits",
      "order": 2,
      "in_maintenance": false,
      "maintenance_line1": "We’re sorry. Our system is temporarily down while we fix a few things. Please try again later.",
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "education/",
          "name": "Education and training"
        },
        {
          "path": "education/about-gi-bill-benefits/",
          "name": "GI Bill"
        },
        {
          "path": "education/about-gi-bill-benefits/post-9-11/",
          "name": "Post-9/11 GI Bill"
        },
        {
          "path": "education/gi-bill/post-9-11/ch-33-benefit/",
          "name": "Check Post-9/11 GI Bill benefits"
        },
        {
          "path": "education/gi-bill/post-9-11/ch-33-benefit/status",
          "name": "Post-9/11 GI Bill Statement of Benefits"
        }
      ]
    }
  }
```


> EVSS/Letters <- letters
```
  {
    "appName": "Debt Letters",
    "entryName": "your-debt",
    "rootUrl": "/manage-va-debt/your-debt",
    "template": {
      "vagovprod": true,
      "title": "Your VA Debt",
      "layout": "page-react.html"
    }
  }
```

> EVSS/Letters <- mobile

I searched the workers/jobs as well to see if anything popped up and got `139 results - 23 files`, and none of them seem related to `hca`, `1010`, `caregiver`. Let me know if you can think of any other keywords to search by.
1. app/workers/central_mail/submit_form4142_job.rb
2. app/workers/education_form/process10203_submissions.rb
3. app/workers/evss/create_user_account_job.rb
4. app/workers/evss/delete_old_claims.rb
5. app/workers/evss/dependents_application_job.rb
6. app/workers/evss/document_upload.rb
7. app/workers/evss/failed_claims_report.rb
8. app/workers/evss/request_decision.rb
9. app/workers/evss/retrieve_claims_from_remote_job.rb
10. app/workers/evss/update_claim_from_remote_job.rb
11. app/workers/evss/disability_compensation_form/evss_document.rb
12. app/workers/evss/disability_compensation_form/form8940_document.rb
13. app/workers/evss/disability_compensation_form/job_status.rb
14. app/workers/evss/disability_compensation_form/job.rb
15. app/workers/evss/disability_compensation_form/metrics.rb
16. app/workers/evss/disability_compensation_form/submit_form526_all_claim.rb
17. app/workers/evss/disability_compensation_form/submit_form526_cleanup.rb
18. app/workers/evss/disability_compensation_form/submit_form526.rb
19. app/workers/evss/disability_compensation_form/submit_form0781.rb
20. app/workers/evss/disability_compensation_form/submit_form8940.rb
21. app/workers/evss/disability_compensation_form/submit_uploads.rb
22. app/workers/evss/disability_compensation_form/upload_bdd_instructions.rb
23. app/workers/rapid_ready_for_decision/disability_compensation_job.rb
