### ISSUE TITLE
<Creating a react widget for Contact Us page> from <Sitewide Content>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#36319]
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [ ] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * < description > 
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ X ] **Other**
   * Please describe in detail

The Virtual Agent chatbot team needs us to add a react widget to the [Contact Us](https://www.va.gov/contact-us/) page as described in #33905. The chatbot info will only be showing to a percentage of users. 

We are still finalizing the content for this and can place the text in this ticket once it's complete. 

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* <Desired/target implementation date>
Estimated launch date is 2/28/22.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *Sitewide Content*
- DEPO product owner: *Beth Potts*
- Product manager: *Stan Gardner*
- Designer: *enter name*
- FE engineer: *enter name*
- Product/team Slack channel: *enter*

--- 
#### Acceptance Criteria
- [x] Convert this request into a Zenhub epic
- [x] Follow-up with requestor to address any lingering questions/concerns
- [x] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by brianalloyd** [comment]
@ianpsant thanks for the update in timing, this helps.  I have this slotted for action @tmac9494 could you pick this up, thanks.

**Comment by ianpsant** [comment]
Hi @brianalloyd just checking the status of this ticket. It'd be great to have this completed this week in advance of our stakeholder go/no go meeting next week Tuesday 2/22?

**Comment by brianalloyd** [comment]
@ianpsant sorry for the delay, we've had some FE Dev turn over and its affected our velocity.  We do have this slotted for action this sprint and hope to have it ready by the 2/22 deadline above.

**Comment by ianpsant** [comment]
@brianalloyd Thanks for the update! Also, will this request be available in staging for us to view leading up to our launch? And if so, is there a way to manipulate the feature toggle so we're part of the 25% that are presented the alert box?

**Comment by brianalloyd** [comment]
@RLHecht @ianpsant do we have the content for this, trying to point my FE dev to the content so we can completed the widget build.  @ianpsant not sure we have a clean solution for a phased release as we've only done a full push on our end.

**Comment by RLHecht** [comment]
@brianalloyd Here's the final text. I thought I put it into a ticket, but apparently not this one!

**VA virtual agent**
You can also use our virtual agent (chatbot) to get information about VA benefits and services.

[Go to the virtual agent](http://www.va.gov/contact-us/virtual-agent/)

@ianpsant Can you confirm I have the right URL there for the link?

**Comment by brianalloyd** [comment]
@longmd Please find the above details in support.  @RLHecht and @ianpsant thanks for the quick response.

**Comment by ianpsant** [comment]
Whenever this feature is complete, could we schedule a meeting with myself just so we can review the solution, understand launch timelines, and outline the support we may need in the future (e.g. killing the link, or tweaking the % of users who can view the widget)?

**Comment by brianalloyd** [comment]
@ianpsant happy to sync up once ready, as advised not sure we can help with the phased approach, as this is typical a feature switch which results in full release or none at all.

**Comment by brianalloyd** [comment]
Work is completed, waiting for PR to merge, meeting scheduled for tomorrow to review details.  Closing ticket in support.

**Comment by RLHecht** [comment]
@brianalloyd Can you let me know what the widget code is to put into the Drupal page? Thanks!

**Comment by brianalloyd** [comment]
@longmd @tmac9494 could you all pass the widget ID to @RLHecht soonest.  TIA.

**Comment by longmd** [comment]
`<div data-widget-type="contact-chatbot-cta"></div>`

**Comment by RLHecht** [comment]
Thanks @longmd Should it be showing correctly for me already in Drupal or am I jumping the gun? When I put in the code I'm getting this:
<img width="921" alt="Screen Shot 2022-02-23 at 4 35 57 PM" src="https://user-images.githubusercontent.com/48728214/155412591-5bb7c048-8adf-46a0-af4c-5d707a685e86.png">

**Comment by longmd** [comment]
@RLHecht We are still waiting for PR approval for this widget to be able to publish to production.

**Comment by agmurphy** [comment]
@RLHecht @longmd @brianalloyd Dan Brooking just confirmed he approved the PR
