### ISSUE TITLE
[BE] URL Shortener - API Error Alerting

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36324]
## Description 
Based on a discussion around the URL Shortener work, it was determined additional alerting would be needed. This ticket is to add alerting around API errors for the URL Shortener. 

## Tasks 
- [ ] Create alerting for the following: API errors

## Acceptance Criteria 
- [ ] Alerting structure has been implemented and API errors successfully populate

**Comment by loripusey** [comment]
@acrollet do we still need this ticket?
cc: @sarahknoppA6

**Comment by acrollet** [comment]
@loripusey I think we need to keep this ticket until we can put alerting for API errors in place or verify that it's covered by the CHIP team's current work.
