### ISSUE TITLE
Can't trigger personalized user nav from mobile menu

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#36322]
## What happened?
I'm trying to access the personalized nav from the header on mobile, and it won't open. This means I'm not able to access My VA, Profile, or sign out. I looked at the January GA reports for the events that are triggered from the items in this menu, and it looks like something broke on January 20 that is preventing people from accessing this menu.

[This is a link to the GA report I reviewed.](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220101&_u.date01=20220131&_.useg=builtin28,userK0YBSMouQ2-eI-QjiaViDQ&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Navigation%20-%20User&explorer-segmentExplorer.segmentId=analytics.eventAction/)

Report screenshot in case you can't see it:
![image](https://user-images.githubusercontent.com/55992116/152075359-5da14a23-3756-46d2-8334-10c12584b9a6.png)

Video of bug:

https://user-images.githubusercontent.com/55992116/152075408-243e6580-dc52-4abc-9c7e-d4cb8d1faa53.mov

## Specs:
- Saw in Chrome device emulator on Macbook, and Safari on an iPhone 12
- Test User _(if applicable)_: cecil.morgan@id.me (staging), I used my own VA.gov account on production

## Steps to Reproduce

1. Visit VA.gov or staging.va.gov on a mobile device, or using a device emulator set to a mobile screen width (e.g. 375px)
2. Log in
3. Click on the user name in the header

## Desired behavior
Drop down menu should appear with 4 options: My VA, Profile, My Health, Sign Out

## Acceptance Criteria
Drop down menu appears with 4 options: My VA, Profile, My Health, Sign Out

**Comment by brianalloyd** [comment]
@srsuddath and @tmac9494 could you guys jump into the code and see if you can diagnose the issue.

**Comment by andaleliz** [comment]
👋  Hi, I'm just following up on this. Do you have any updates to share?

**Comment by brianalloyd** [comment]
@tmac9494 @longmd let's prioritize this after the O&E MVP launch actions, need to get this resolved as this is a priority action that Veterans need on mobile.  Let's review in SU tomorrow need actions to diagnose and resolve. 

@andaleliz we'll follow up once we've had a chance to review the details and do some discovery, we'll close the loop soonest.

**Comment by longmd** [comment]
@brianalloyd @tmac9494. lets discuss options for the fix for this during SU tomorrow. I've completed the discovery & diagnoses of the issue.

**Comment by andaleliz** [comment]
@longmd can you share any details about what you've learned? I'm most interested in what caused the problem.

**Comment by longmd** [comment]
@andaleliz, the super short version is the toggle function on that button is getting fired twice on click. So we are telling that menu to close immediately after telling it to open and thus it's doing nothing.

**Comment by brianalloyd** [comment]
@andaleliz this appears to be working on my end, could you review and validate as a second reviewer.

**Comment by andaleliz** [comment]
Hi Brian! It’s working on my end too, I checked in Chrome on my iPhone,
with vets.gov.user+15. Screenshot attached.

Thanks so much!


-- 
Liz Lantz
Senior UX Designer, Ad Hoc
adhoc.team
<https://www.google.com/url?q=https%3A%2F%2Fadhoc.team%2F&sa=D&sntz=1&usg=AFQjCNE4MGCYSFhDl_lZwwTif1R0KYNm0w>
|
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>
@adhocteam
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>

**Comment by brianalloyd** [comment]
Awesome, closing this ticket out in support.
