### ISSUE TITLE
[AXE-CORE Medium]: Heading levels should increase by one

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#3633]
## Description

**[AXE-CORE Medium]: Heading levels should increase by one**

Ensure the order of headings is semantically correct. This h3 follows the h1.

```HTML
<h3 class="vads-u-font-family--sans vads-u-margin-y--1">Individual disability ratings</h3>
```

## Point of Contact

Jennifer

## Acceptance Criteria

As a screenreader user, I want to navigate the heading hierarchy so I may understand the content of the page.

## Environment

* Operating System: all
* Browser: all

## Steps to Recreate

Run axe-core scan to check compliance.

## Possible Fixes (optional)

Change the h3 to an h2. Alternatively, change the h3 to an h2, and use a utility class to look like an h3.
```HTML
<h2 class="vads-u-font-family--sans vads-u-margin-y--1">Individual disability ratings</h2>
```

## WCAG or Vendor Guidance (optional)

[Heading levels should only increase by one](https://dequeuniversity.com/rules/axe/3.4/heading-order?application=coconut)

**Comment by jenstrickland** [comment]
![image](https://user-images.githubusercontent.com/57469/69971948-b6363800-14ee-11ea-9e55-96c331183a4b.png)

**Comment by jason-gcio** [comment]
Addressed in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4013
