### ISSUE TITLE
Local keycloak instance in docker

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#36331]
**Done When:**
Developers can test implementation locally before deploy to dev. Developer can download docker and run local tests

### Notes
 - running a single instance of keycloak in a docker container
 - docker accessible by anyone in the DSVA org
 - hard to do via socks proxy, so local gives us a solution
 - upload docker file to example repo
 - tub docker compose that runs an instance of keycloak with a test user
 - configure keycloak via command line

**Comment by kjduensing** [comment]
is this a dupe?
