### ISSUE TITLE
Investigate idme_dslogon and idme_mhv capabilities

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#36344]
# Description
Part of Sign-in Service.  We believe we should be able to access via the ID.me interface by changing scope.

**Comment by joeniquette** [comment]
reached out to Kyle from Idme on 2/2. He responded that he will get us the info.

**Comment by joeniquette** [comment]
met with IDme on 2/3, they stated they would setup our test app with the additional scopes of idme_dslogon and idme_mhv. They are going to email me directly when its ready.

**Comment by bosawt** [comment]
Existing implementation with SAML ID.me:

> <samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
>   xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://api.id.me/saml/SingleSignOnService" ForceAuthn="false" ID="FIMREQ_c616ea82-017e-186a-b777-b12d4816c914" IsPassive="false" IssueInstant="2022-02-04T18:54:57Z" Version="2.0">
>   <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://eauth.va.gov/isam/sps/saml20sp/saml20</saml:Issuer>
>   <samlp:Extensions>
>     <vagov_saml_request_artifact>{"timestamp":"2022-02-04T18:54:52+00:00","transaction_id":"1a513574-a3f6-4adb-aa70-8e1d898654a1","saml_request_id":"_22a9217b-0e7c-48f3-81b0-97806cbd8a02","saml_request_query_params":{}}</vagov_saml_request_artifact>
>   </samlp:Extensions>
>   <samlp:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></samlp:NameIDPolicy>
>   <samlp:RequestedAuthnContext Comparison="minimum">
>     <saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/1/vets</saml:AuthnContextClassRef>
>   </samlp:RequestedAuthnContext>
> </samlp:AuthnRequest>

**Comment by bosawt** [comment]
Existing implementation with SAML MyHealtheVet:

> <samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
  xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://api.id.me/saml/SingleSignOnService" ForceAuthn="false" ID="FIMREQ_c61dba1d-017e-1f10-9812-b12d4816c914" IsPassive="false" IssueInstant="2022-02-04T19:02:24Z" Version="2.0">
  <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://eauth.va.gov/isam/sps/saml20sp/saml20</saml:Issuer>
  <samlp:Extensions>
    <vagov_saml_request_artifact>{"timestamp":"2022-02-04T19:02:18+00:00","transaction_id":"bbb4b9ea-e75c-49ed-adc5-da382cfc6d60","saml_request_id":"_ab8a2ec9-bf7e-41d6-869b-dc4d2212ffbc","saml_request_query_params":{}}</vagov_saml_request_artifact>
  </samlp:Extensions>
  <samlp:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></samlp:NameIDPolicy>
  <samlp:RequestedAuthnContext Comparison="exact">
    <saml:AuthnContextClassRef>myhealthevet</saml:AuthnContextClassRef>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>

**Comment by bosawt** [comment]
So it's true that `AuthnContextClassRef` is what sets ID.me versus MyHealtheVet. Still need to prove that setting the proper scope (or something like that) will change the backing Identity Provider

**Comment by bosawt** [comment]
We are able to get the dslogon or myhealthevet authentication page simply by setting `dslogon` or `myhealthevet` as the OAuth auth scope
