### ISSUE TITLE
VAOS Staging: 404 error while creating a CC request and accessing the request in the requested queue 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#36356]
## What happened?
User (Jacqueline.morgan@id.me) encountering a 404 error 
Scenario 1- VAOS is throwing a 404 error while creating a CC request 
Scenario 2-  VAOS is throwing a 404 error when accessing the request from the requested queue 

## Steps to Reproduce 
**Scenario 1 -** 

1. Login in to VAOS as Jacqueline.morgan@id.me
2. Follow the steps to create a CC request with a preferred provider 
3. Validate the information enter is displayed correctly on Review your appointmnet screen and click on "Request Appointmnet" button

**Actual Results:** System is throwing a 404 error and an message displays "We're sorry, We've run into problem" 
**Expected Results:** A new appointmnet should be created

**Request URL:**
https://staging-api.va.gov/v1/facilities/ccp/1669673596
 **Response:**
{"errors":[{"title":"Not found","detail":"There are no routes matching your request: v1/facilities/ccp/1669673596","code":"411","status":"404"}]}

**Scenario 2 -** 

1. Login in to VAOS as Jacqueline.morgan@id.me
2. Access the requested queue in the VAOS home screen 
3. Scroll down the queues list and find the newly created request 
4. Click on the Details>link 

**Actual Results:** System is throwing a 404 error and an message displays "We're sorry, We've run into problem"
**Expected Results:** System should display the pending appointmnet details as entered while creating the request 

**Request URL:**
https://staging-api.va.gov/v1/facilities/ccp/1669673596
 **Response:**
{"errors":[{"title":"Not found","detail":"There are no routes matching your request: v1/facilities/ccp/1669673596","code":"411","status":"404"}]}

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

![404_error](https://user-images.githubusercontent.com/69315717/152208896-84cd6bdf-ae8f-4047-a0af-927a6f7ea6bf.PNG)

**Comment by aarathi-poldass** [comment]
Please note for scenario-1 we are getting the error only when the provider is selected. If provider is not selected the request is created successfully.

**Comment by ptouchton** [comment]
@aarathi-poldass @ldelacosta - I am unable to reproduce the error in Stage. I used Jacqueline.morgan@id.me and since this ID has recently changed to use VAOS service, I also tried Ruben.Moreno@id.me (which is now being used for production test cases). In either scenario I was able to create the CC request. Would you mind verifying that you are still seeing the 404. Thank you

**Comment by ptouchton** [comment]
@aarathi-poldass - Thank you!
