### ISSUE TITLE
Investigate all areas that use EVSS for ct, ft, and forms

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#36351]
EVSS looks like it is being deprecated.

We are being asked to identify all areas that EVSS is integrated. For each section, please investigate where there are EVSS integration points:

- Comparison Tool
- Feedback Tool
- Forms
- GIDS

We will need to investigate this in the rails, react, and gids codebases.

**Comment by AdamFreemer** [comment]
Comparison Tool: no impact
Feedback Tool: no impact
GIDS: no impact

edu-benefits forms:
0993: no-impact
0994: back-end / front-end (mock data)
1990(x): back-end / front-end (mock data)
1995: front-end (mock data)
5490: front-end (mock data)
5495: front-end (mock data)
10203: front-end / back-end (major implementation)

Note: There is core platform code on vets-website and vets-api which would have to be updated which impacts app wide services. Most of the heavy lifting overall is in these areas. The assumption would be that platform would be re-writing this code with an alternate provider of EVSS sourced data services.

**Comment by mrblanco1** [comment]
Provided the above data to Kelly Lein on 2/3/2022. Will contact her to learn more about EVSS' retirement.

**Comment by mrblanco1** [comment]
Abe provided Kelly Lein a list of areas we found will be impacted on 2/3/2022. This ticket can be closed now.
