### ISSUE TITLE
QAST CONTENT: Conduct baseline research (5)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#36363]
# User story

As a Platform customer, I need easier-to-follow, more succinct documentation so that I can perform QA and Testing tasks more easily.

As a QAST team member, I need to know customer sentiment and gaps in our current docs set so we can improve our docs (thus allowing customers to execute QA and Testing tasks more easily).

# Tasks

- [x] write research plan
- [x] recruit participants
- [x] sched participants
- [x] sched pilot
- [x] run pilot
- [x] execute sessions
- [ ] synthesize

# Acceptance criteria

Share synthesis with OCTO-DE.

# Reference info
- n/a

**Comment by lianilychee** [comment]
2/3 Thurs:
- today:
  - have sent rsch plan for Naomi to review, but her feedback is not a blocker for conducting the studies
  - mostly recruiting and scheduling
    - pick a pilot participant from spike teams and schedule them for Monday
    - draft slack msg to recruit participants
    - want to briefly explore Calendly for participants (how do I connect to it?  CAN I connect to it?)

**Comment by gmaciolek** [comment]
2/4 Fri:
yesterday:
- set up calendly account
- started recruiting
- validated one of our research hypotheses re: the audience for these docs while I was recruiting, realized we need to change our recruiting plan or change the research. talked to naomi a bit. messaged joe.
- scheduled pilot for Monday with Micah Chiang

today:
- checked in with andrea to get her input. 
- need to choose different research participants--limiting scope to QA specialists and FE engineers (pending Joe's response to my message--may include a BE dev)
- continue recruiting
- write conversation guide

monday:
- conduct pilot
- refine conversation guide, as needed

**Comment by gmaciolek** [comment]
friday:
- edited research plan -- main change involved change to the recruiting strategy. (Focusing on FE, QA, and PMs for this research)
- continued recruiting
- drafted [conversation guide](https://vfs.atlassian.net/l/c/02zpBG8o)
- rescheduled pilot for tomorrow (Tuesday)

today:
- nudge joe for feedback on conversation guide
- continue recruiting/scheduling
- make note-taking doc
- add a notetaker to each meeting invite

blockers:
- a few people have not responded to recruitment message. need to nudge them today

sorta blockers:
Would really like Joe's feedback on tasks in conversation guide before the pilot

**Comment by gmaciolek** [comment]
yesterday:
- tweaked conversation guide
- got a little feedback from Joe

today:
- run pilot
- try to recruit a PM
- share note-taking doc and observer guidelines
- add notetaker to newly added meeting(s)

**Comment by lianilychee** [comment]
2/8 Tues:
- did the brainstorming session for publishing 
- today:
  - Amy - coordinate w Jill for notes, summarize twice-weekly deploy
  - Amy Gretchen - schedule intake brainstorming session for tmr afternoon
  - Amy - set up MURAL board for tmr's intake brainstorming

**Comment by gmaciolek** [comment]
Yesterday:
- did pilot session
- recruited a PM
- added Joe as optional to all meetings and Amy to meetings as notetaker

Today:
- need to tweak conversation guide and MURAL a bit again
- doing first research session this afternoon

**Comment by gmaciolek** [comment]
yesterday:
- finalized conversation guide and updated MURAL

today:
- 4 sessions scheduled today. so far so good!

No blockers

**Comment by gmaciolek** [comment]
friday:
- started synthesis. made progress on pulling together data on a notes doc: https://vfs.atlassian.net/l/c/w0NoKEVg

today:
- finish pulling together data
- write key findings and recommendations
- findings will ultimately be written here: https://vfs.atlassian.net/l/c/o5TRXau9
