### ISSUE TITLE
VAOS Staging: Tell us the reason for this appointment (Additional details/ comments) not being transferred to HSRM

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#36372]
## What happened?
For VAOS Service test user (Jacqueline.morgan@id.me) Additional details/comments are not going through to HSRM and also not displaying on the pending appointmnet page. 

SQA team initially opened a JIRA ticket (https://issues.mobilehealth.va.gov/browse/VAOSR-2905). Brad Crosby's suggestions to test with VAOS Test UI  to determine if this is a VAOS FE (or) BE issue. Here are the steps we took- 1) Submit a community care appointment request with additional comments, 2) Checked HSRM and validated the comments are being transferred and identified this issue is related to front end.

## Steps to Reproduce
1. Login to VAOS as Jacqueline.morgan@id.me
2. Follow the steps to enter a CC request and enter additional comments in "Tell us the reason for this appointment" section (Note: Please don't select a provider as the system is throwing a 404 error when provider is selection. Please refer to -#36356 for more details)
3. Validate the information entered is disapplying correctly with additional details on the "Review your Appointmnet details" page
4. Click on request appointment button and validate the request is created successfully

*Actual Results: * On the "Pending Appointmnet" page the "You shared these details about your concern" show up as **none** and additional details/comments are not being transferred to HSRM
Expected Results: The comment entered while creating the CC request should display on the pending appointmnet page as well as it should be transferred to HSRM

Please see the screenshots for reference. 
![Request_VAOS test harness](https://user-images.githubusercontent.com/69315717/152234736-24c9705c-2726-4d80-8010-537323091d47.PNG)
![Request_VAOS](https://user-images.githubusercontent.com/69315717/152234745-3fcfd0e8-3bd0-405a-8b7d-bee089986353.PNG)

**Comment by ldelacosta** [comment]
@marcynadeau & Aarathi - This is ready for testing. Thanks!

**Comment by aarathi-poldass** [comment]
@ldelacosta - Validated the ticket and the additional comment entered while creating the CC request are display correctly on the pending appointmnet page in VAOS as well as it is being transferred to HSRM correctly. Please find attached the screenshots for reference. Please go ahead and close the ticket.

Thank you!

[Capture.PNG](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/a199b19d-2803-4764-97ee-6c7473cdeb83)
