### ISSUE TITLE
Investigate Introspection Endpoint Requirements

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#36377]

**Comment by jscanish** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/introspection_attributes.md

**Comment by jscanish** [comment]
Attributes will be cached in Redis. We will extend the User model to make those attributes accessible.
