### ISSUE TITLE
Analytics Tools 

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36384]
## Issue Description
In order to understand how analytics can help inform our development decisions, our backend engineers need a thorough review of how to use our monitoring tools. 

---
## Tasks
- [ ] Schedule follow-up session with Dillo to continue demo of Datadog, Grafana, Sentry

## Acceptance Criteria
- [ ] Backend engineers will be able to use our tools to monitor application health and drive product development.
---

**Comment by cnemeth** [comment]
Dill will schedule next session, possibly next week.

**Comment by cnemeth** [comment]
Closing. Not relevant at this time.
