### ISSUE TITLE
[Platform Infrastructure] Update Application onboarding template 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#36389]
## Description
There are multiple teams looking to deploy applications to the platform's container orchestration environment using Amazon EKS.  The template is out of date and should be updated to gather better information that will streamline the application onboarding process. 

## Background/context 
Template in question [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+kubernetes%2C+devops&template=kubernetes-onboarding-template.md&title=)

## Technical notes
Issue with suggested updates [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36358)

---
## Tasks
- [x] Update the [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+eks%2C+kubernetes%2C+infrastructure%2C+infrastructure-request&template=kubernetes-onboarding-template.md&title=%5BInsert+app+name+here%5D+-+Application+onboarding+infrastructure+request) with more accurate information

## Acceptance Criteria 
- [x] The updated template is ready to be shared with the teams that are ready to begin the application onboarding process

**Comment by jhouse-solvd** [comment]
In a future ticket, capture the items that need to be in place for a service to be fully operational. 

For example: logging, monitoring, alerting, etc

**Comment by jhouse-solvd** [comment]
We iterated on the template based on feedback from @timwright12. 

The [template has now been shared](https://dsva.slack.com/archives/CJRQ85PQB/p1644253064322379) with the Console UI and IET teams, and we are awaiting their feedback. 

This issue can likely be closed, though there may be additional feedback that could spawn the creation of a new issue.

**Comment by jhouse-solvd** [comment]
Good feedback here from @rmtolmach regarding use of ie vs eg (text provides examples) 

https://github.com/department-of-veterans-affairs/va.gov-team/pull/36468#pullrequestreview-873661139

**Comment by jhouse-solvd** [comment]
moving this back to "To Do" 

some ideas: 

- how might we link in sub-templates/requests
- I noticed that in the case of #36494, the user removed the links for examples/docs
- maybe this issue could be closed and we could move that template to YAML? 
- will keep this issue open until a decision is made

**Comment by jhouse-solvd** [comment]
If add'l infrastructure service is required...

- database selection
- version selection
- message about default version: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.DBVersions
---

we want to try and capture as much as possible in the one template/request, rather than having multiple sub requests. the team pointed out that a lot of this could be done in one PR.

**Comment by jhouse-solvd** [comment]
We’ll also likely be able to automate the PR generation process based on standardized naming conventions captured through a request

**Comment by oseasmoran73** [comment]
Matt brought up an important detail that may want to be added in the "For Ops todo". Infra needs to add the team being onboarding into argoCD for manifest repo to update with changes accordingly

**Comment by jhouse-solvd** [comment]
Define a project in ArgoCD and map a GitHub team to it 

Example PR: 
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/31/files

**Comment by jhouse-solvd** [comment]
Excellent feedback from @ewilson-adhoc can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2102067219/2022-02-24+Feedback+from+IET)

**Comment by jhouse-solvd** [comment]
Add'l feedback from Platform Console UI team can be found [here](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2104688835/Post-Mortem+-+EKS+Onboarding)

**Comment by jhouse-solvd** [comment]
background section "describes" typo

**Comment by jhouse-solvd** [comment]
Before closing this out, create a new issue w/ specific updates based on what's been captured above.

**Comment by jhouse-solvd** [comment]
Add' summary feedback [here](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2104688835/Post-Mortem+-+EKS+Onboarding?focusedCommentId=2126905445#comment-2126905445)

**Comment by jhouse-solvd** [comment]
This issue can be closed. 

However, some of the info linked here will be useful as we update the template during this quarter's (Q2 '22) initiative. 

Please see #38890 for more info.
