### ISSUE TITLE
Request access to Google Analytics and Domo

### ISSUE THREAD

**Issue by pilarmo** [department-of-veterans-affairs/va.gov-team#36394]
# Request Google Analytics and Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ X] Google Analytics
- [ X] Domo
- [] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

Edit access
For BigQuery I won't be 

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@pilarmo You have been granted access to both Domo and GA. You should get a welcome email from each platform with instructions for getting logged in. Please feel free to re-open this ticket if you have any issues! 🚀
