### ISSUE TITLE
Staging: COVID Direct Scheduling/Booking Error

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#36396]
## What happened?
Log in as a patient and go through Direct Booking Process for COVID for Cheyenne.  On the screen where you review the appointment details and select confirm appointment, this is where you get an error.  

## Specs:
Chrome.
Jacqueline.morgan@id.me  Password1234!

## Steps to Reproduce

1. Log into VAOS AWS staging, ID.me as J Morgan
2. Select COVID, No to previous dose, Select Cheyenne as location. Select any of the Cheyenne COVID clinics.  Select an appointment date and time.  Confirm contact information
3. On the "Review Appointment Details Page" select confirm appointment.  
4. Expected response:  Booked Appointment Details display
5. Actual response:  Error modal displays:  We couldn’t schedule this appointment.  We’re sorry. Something went wrong when we tried to submit your appointment. You’ll need to call your local VA medical center to schedule this appointment.

Dev tools shows a 400 Error for this URL:  https://staging-api.va.gov/vaos/v2/appointments![StagingCOVIDDirectSchedulingBookingError.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/bb6107a3-77ae-4d33-be7a-5decc07d0fdc)

**Comment by ldelacosta** [comment]
@marcynadeau - This is ready for testing. Thanks!

**Comment by beth-wodzinski** [comment]
Looks good to me. I made 6 different appointments for j.morgan and all completed successfully.

**Comment by ldelacosta** [comment]
QA validated this bug and issues have been resolved.
