### ISSUE TITLE
Access for Sylvester Lee VSP Identity

### ISSUE THREAD

**Issue by sylvesterlee1911** [department-of-veterans-affairs/va.gov-team#36397]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Sylvester Lee

### Your Email

sylvester.lee@oddball.io

### Name of Your Team

VSP Identity

### Service(s) You Want Access To

SOCKS

### Access Expiration

never

**Comment by oseasmoran73** [comment]
Hi @sylvesterlee1911 

Can you please update the ticket with your Public SSH Key? It is required in order to obtain SOCKS

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/10504

**Comment by oseasmoran73** [comment]
Closing ticket as request has been fulfilled in PR stated above. Please feel free to reopen or create a new ticket if we need to update SSH key.

**Comment by sylvesterlee1911** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcH+FLDOTp+WVnDIhksFPp47COPxMVr0PUaDJosePSYP+iMViURr6s74e+2h8H4rCX1HKZdvetpWaOqzMWhHioH3JgUorSjzvFr2bIhn1uUVqGh1vgHjuhaqRAFertFaJR874Gz3biNfA5DTgTnrRLR8M1VHdtiUI+Z5sK50wCLpc8Sw27ic6+SLxIQu6MMyl5lt17QJsXPRi41r+WyPoVGdOFn6Fvq6b+YZnRy8MdbSSpAVF0mRJIz+MQsV/b5lSAQJ6jZ0tNCc8xhTCynZkI2k5L3LA376DVLJqEiJalMHA04ck1SNC6mX0h0OlJ7+yavFKXN24fWuWGxW4uYBz8zIp4Nv5VQ+v3zi1DN3OSXvabU17FgNkZcoBReK003E88HwP8kaXI7+kwrGX7PSv7ZNPKLETVwuiyFy5Kw2qFLouSrDZ40CtuOGHuqa0nm2uDrSVOz6oZqhenbjRHPtGFdvrCzTOCLPifEVlT5IPc1ZzrSwB0hB0sncNeXJyvVEM= sylvester@DESKTOP-9H81PT5

**Comment by sylvesterlee1911** [comment]
I had to add the public key.  Then I reopened this issue.  Please do the needful. 


Thank you,

Lee

**Comment by jbritt1** [comment]
So you want us to replace the key that was added for you in https://github.com/department-of-veterans-affairs/devops/pull/10504?

**Comment by sylvesterlee1911** [comment]
Yes it has changed.  I'm working on a different box.  Please advise.

**Comment by jbritt1** [comment]
> Yes it has changed. I'm working on a different box. Please advise.

Roger that, will update it shortly

**Comment by jbritt1** [comment]
New key being deployed now, please allow 10-15 minutes and your connection should be good. If any issues arise, please feel free to reach out in the #vfs-platform-support channel of the DSVA Slack workspace using the [support workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
