### ISSUE TITLE
Remove redesign flag

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#36391]
When we launched the redesign, we added a feature flag: gi_sandbox_comparison_tool_toggle

This story is to remove the feature flag and associated implementation of it.

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2893&group_by=cases:title&group_order=asc
Test case: [Remove redesign flag.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8017520/Remove.redesign.flag.xlsx)
