### ISSUE TITLE
Formation.js accordion does not work in IE11

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#364]
**Specs:**
- Device: VirtualBox on Mac
- Browser: IE11

**Steps to Reproduce**
url: https://design.va.gov/components/accordions

**What happened:**
Accordions do not work. Nothing happens when clicked. Content is hidden on open accordions when the page loads.

<img width="1057" alt="Screen Shot 2019-06-06 at 11 16 35 AM" src="https://user-images.githubusercontent.com/25435289/59044968-24a28200-884d-11e9-8e4b-abd1d1c8df2b.png">

**Desired behavior:**
Accordions should function as they do in Chrome

Need to add `Array.from` polyfill to the formationjs build: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18873#issuecomment-503300243

**Comment by caw310** [comment]
We will not be supporting IE11.  See 688 which references no longer supporting IE.
