### ISSUE TITLE
Add time zone to Direct Deposit call center hours

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3640]
Change the copy of the Direct Deposit help text from `We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m.` to `We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET`, adding `ET` to the call center hours.

**Comment by erikphansen** [comment]
@Justin-Pickett can you validate this one? I just merge it so it should be on staging now. You can sign in with user 1 and go to https://staging.va.gov/profile/#direct-deposit to see the change.

**Comment by Justin-Pickett** [comment]
## Screenshot of change on staging 

![Screen Shot 2019-11-22 at 10.32.13 AM.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/474ec21a-ca19-4b3d-b981-5d074152916a)



@erikphansen I have validated this in staging. Closing this ticket
