### ISSUE TITLE
Create reusable workflows

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#36401]
## Description
We will want to create reusable workflows [as seen here](https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/) for the [deploy](https://github.com/department-of-veterans-affairs/platform-console-api/blob/master/.github/workflows/deploy.yml) and [push-images](https://github.com/department-of-veterans-affairs/platform-console-api/blob/master/.github/workflows/push-images.yml) workflows. The microservices that will be on platform-console will use (pretty much) these exact same workflows and it will be cleaner to have a single source of truth to maintain. 

Notes:
- We are unsure if workflows can be reusable across public repos in the same organization. E.g. Could pghero reference a reusable workflow from within platform console? They are both public repos currently. According to [this doc](https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-to-reusable-workflows) if the called workflow is stored in a public repository, it appears that a reusable workflow can be use by another workflow if the called workflow is stored in a public repo. 
- It appears that you can pass in variables to the reusable workflows, which will make customization for microservices straightforward.

**Comment by LindseySaari** [comment]
It appears that you can create a workflow template (e.g. in platform console) and then reference the reusable workflow from the new workflow/job and pass in any variables that are needed.

**Comment by LindseySaari** [comment]
[Example on how to use reusable workflows with inputs and secrets](https://dev.to/n3wt0n/avoid-duplication-github-actions-reusable-workflows-3ae8)

**Comment by npeterson54** [comment]
@LindseySaari can this issue be closed?

**Comment by npeterson54** [comment]
@LindseySaari has said this can be closed
