### ISSUE TITLE
Access for [Andrew Rodiek]

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#36413]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Andrew Rodiek

### Your Email

andrew.rodiek@govcio.com

### Name of Your Team

Debt Resolution, Front End Engineer, GovCIO

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeUWbT8tTsmy5rJhbbwkl0VtxETOdHp92SQnKVcytliizbr2EF/6vZohE5dHTwLTT8mG86Bf66TUco5EhT8ih5CZARAvWau1Rj2RZ33KPLfV5K+bYAI1ZA4yvcbxvTd/DOVi94SiDll7qBwxYhbxPRh5G7gxRC6y5TorbFMGqWz3UniRGlEyhAS0/55FiErPXKz5tN8kEUtzD+WBNUjm7dWzqNritH5KS0xaZxzvca+9WimJysyz+6J/q52rt2f/1AbzIRhSL+gITbgxrVUWuKepwT3++FOSruKMKfdc3mmjJaUlNTjmx91P4IkZn235MJ6fVW4uI+tBhgraFZDC4uqE1fbzogoM8s33zBNbZIh/RAxSmtTbysVss/1Wu0bIXQtu1tC/bCYdStnmBvYwjVWBylovWEhpRuRsyImQEAJK+Scm7qP20MihDk0D3xVpytoGTD5Reh7i+dAf8wAyDx781RorwmLAq6rhfdQo85flT9PD6bUE++42D5/PTU0O0= andrew.rodiek@c02yq8g2lvcf.lan

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
Hi @Dr-Pongo 

Can you please update email address to not use personal email?

**Comment by rmtolmach** [comment]
Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble
