### ISSUE TITLE
Access for [Brandyn Sullins]

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#36412]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Brandyn Sullins

### Your Email

brandyn.sullins@govcio.com

### Name of Your Team

Debt Resolution - FE Engineer - GovCIO

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNzlvT7drzUv52EtSMMqrzq5j4NMB7S9tpQuJ3k3fBVMIEavQpgp3eRMfnqb2q0mrAeb8OVhjfErEzBWcX/sdWs/GkZ6Rzb3qLyCA/YXVz+sSpR8EXvax44+n1+49SrbbBh87AIfnj3eds5X3XG568Keruh2SarEWDwBwmG5H1rsRvpmZcmVE9xJErPSqFm5Y13N0FkueiJ5oef48B2X0VexTV4/ErxzErnYXOv4+It4I/6xUp2k1F1naNjVeLOcSC7WDix0wPMkMunRlry+MJiI7peMnGm4oT3kHf+z3ZF5LmWtVeZBL5ZelBlINqG8aJbagBAq6hnd/+tRH+zZSbDTZKP+xN4iBcT5UhIN24cpO3muG3e1+fkJCQLIbFX1+DY7S08tzf5uxZysyUYIRhYYNrvy992UchkMwZv/a66IoVskaMwEw9fVPLDrAWQn80GaZO+1X9tXiKgBC1fghzuqG5Z4SknjjdxAQwdhMd8/6SluztuGeNCDZn3qm2cnM= brandyn.sullins@C02DG1P1MD6R.local

### Access Expiration

Ongoing

**Comment by oseasmoran73** [comment]
Hi @OptionSelect 

Can you please update email address to not use personal email?

**Comment by rmtolmach** [comment]
Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
