### ISSUE TITLE
[BE][MuleSoft] Revert SSL verification bypass

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#36410]
Due to SSL cert issues, communication between vets-api and MuleSoft were in staging. In order to work around this error and to facilitate continued testing a [change](https://github.com/department-of-veterans-affairs/vets-api/pull/9018) was made to vets-api disabling certificate validation. This change was and is expected to be temporary, lasting only until these SSL issues have been resolved.

This issue covers reverting that PR.

Acceptance criteria:

- [ ] [vets-api PR 9018](https://github.com/department-of-veterans-affairs/vets-api/pull/9018) has been reverted
- [ ] 10-10CG submissions to MuleSoft succeed in all environments

**Comment by RudyOnRails** [comment]
Closing this out, as we are tracking it now in https://github.com/department-of-veterans-affairs/va.gov-team/issues/37183
