### ISSUE TITLE
Access for James Daniel Bell

### ISSUE THREAD

**Issue by JamesDanielBell-VA** [department-of-veterans-affairs/va.gov-team#36416]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

James Daniel Bell

### Your Email

james.bell@libertyits.com

### Name of Your Team

axolotl

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXLCVDGJ2tzf7wD4DjgRZkZufHOr+AAgnQab3xXptR56NImO0EzxVvUeNJTYeYN548q3p3rd9kTDOfH44ZrCXValdEIiQ6ij5umL8hAZYZNLZx834XPS/ne63aV3IMhKWs2l/wgU8AoxmrbjTjQUSacPWpnW7OTV7EoyDMJSaRjJP5CZVnZnqi37g9tm7y4avkCbqsyb1kTI42EKcUrPi8+6AW7ISLWAvSM6HffYPe1zqM5T1NXjvy+beK1NiC/MKHGXfL0lWdTeOnLSxk5Oh5uxdiUubV5DR3Zn1yT1oEQKa8zb71QPshBtXvAQgHPWV8XQ33bvQ+fI3Vd0ymPRuV3c/BBhj7qLn7bO8O8QvHsqO240qVUNMZYW0Ga+Js3NZ/0lB7KZ9kHnicQgAM2LU/aoNyNeq0GOC18kPiTLMu6nhYJuXRsR64vHYqsaebijTfYP9jVtpYPJSOdgBJYGz27YvBgq/ewAJ62KMbDkEmNN3F31PL2Reghs2qEYvjqm8= jd_va@WIN-KB5OBIAHLQJ

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
You were already in the [config.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml#L222) file, so I left you there and just updated your SSH key ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
