### ISSUE TITLE
Offboarding of [Maria Becker]

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/va.gov-team#36428]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Maria Becker
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VANotify Team
   > Product Manager
   > 1/31/2022
   > Thoughtworks
- Please provide any type of access they may have and their GitHub username. 
  > Google analytics, Big Query, Domo, Mural, Sketch, Slack
  > Already removed from Github: https://github.com/department-of-veterans-affairs/github-user-requests/issues/9743
  
 
## AC
*Performed by Platform team*
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack (if applicable)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by bsmartin-ep** [comment]
GA and Domo access removed.

**Comment by rmtolmach** [comment]
✅ removed from VFS team roster
✖️ no socks access
❓ I don't think Maria has AWS access, but I'll leave it to @oseasmoran73 to confirm.
✅ confirmed that `miabecker` is no longer in the VA GH org
✖️ not in pager duty, datadog or sentry.
✖️ bot user GH accounts: N/A

**Comment by oseasmoran73** [comment]
No AWS

**Comment by miabecker** [comment]
Thanks - also want to make sure I was removed from Zenhub and Datadog? I do have AWS Access so will need to remove that. I thought I was in PagerDuty but maybe already removed.

**Comment by ffafara-tw** [comment]
@miabecker VANotify had separate (from VSP) instances of DataDog, AWS and PagerDuty.
This request is only about VSP tooling.
You have already been removed from all VANotify tools.

**Comment by rmtolmach** [comment]
Thanks for that clarification @ffafara-tw!
re: Zenhub. I believe it's connected to your GitHub account. And you were removed from the va org here: https://github.com/department-of-veterans-affairs/github-user-requests/issues/9743, so you should be good.

**Comment by rmtolmach** [comment]
Reopened because Maria has two Slack accounts and one of them is still active
![image](https://user-images.githubusercontent.com/10993987/153062649-a3af2144-ede2-4598-8042-3d958926991d.png)

**Comment by CoryTrimmUSDS** [comment]
The `Maria Becker` affiliated with the DSVA Slack is properly deactivated.

The `Maria Becker` that is not deactivated and has the green silhouette is from the VA OIT DevOps instance of Slack.

**Comment by rmtolmach** [comment]
ok, thanks for checking!
