### ISSUE TITLE
Drupal practice VBA: Update pension rates on benefit hub pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3642]
**User story 1:** As a pension beneficiary, I want to know the most recent and correct pension rates information.  

**User story 2:** As a VBA VACO digital media stakeholder, I want to be able to make simple updates in Drupal, using the new editorial review process. 

**Action item:**  The pension rates on the below 2 pages need to be updated for **December 1.** 
(Note from stakeholder: "....the rates are popular with Veterans and are also a high profile item.")

**Desired ETA:** Dec 1, 2019

https://www.va.gov/pension/veterans-pension-rates/

https://www.va.gov/pension/survivors-pension-rates/

**Document from stakeholder:** 
[2019-12-01 Pension Rate Tables_Approved_11122019.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3875225/2019-12-01.Pension.Rate.Tables_Approved_11122019.docx)

@RLHecht - We will use this content task to walk Misty through her making these updates using our editorial review and publish process.  FYSA @Karak888

**Comment by Karak888** [comment]
@RLHecht - this is the pension rates ticket that Misty did, so moving to close this.  Per your note, I am going to close this out, and if you need to create additional tickets, you can always reference this even if closed.  Thank you!!
