### ISSUE TITLE
Offboarding of [Jasvir Singh- Jsing0]

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#36430]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Jasvir Singh
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > 1095-B Tax form team, Lead Designer, 2/4/2022, The MO Studio
- Please provide any type of access they may have and their GitHub username. 
  > Sketch, Slack, GitHub, ZenHub Jsing0
  
 
## AC
*Performed by Platform team*
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack (if applicable)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by bsmartin-ep** [comment]
No GA or Domo access.

**Comment by rmtolmach** [comment]
🤷 I checked Slack and his account is listed under Jesse Singh and is already deactivated. I commented with `/remove` and no 👀 reaction appeared. I think we're good here. 
✅ removed Jesse Singh from the VFS roster
✖️ No socks access
✅ removed from github with [this issue](https://github.com/department-of-veterans-affairs/github-user-requests/issues/9746)
✖️ not in pagerduty, datadog, or sentry
✖️ bot user gh account: N/A
❓ I don't think he has AWS access, but I'll leave it to @oseasmoran73 to confirm.

**Comment by oseasmoran73** [comment]
No AWS

**Comment by rmtolmach** [comment]
Hi 👋 I'm new and don't know what I'm doing 😂. I accidentally used `/remove` instead of `/request` for Jesse's Slack access removal. He was already deactivated from Slack, but it looks like the bot put eyes on the request anyway 🤷

**Comment by CoryTrimmUSDS** [comment]
No worries @rmtolmach - it appears that Jesse Singh has been deactivated from Slack.
