### ISSUE TITLE
update code.gov

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#3644]
https://code.gov/ is a  designed to support reuse and public access to custom-developed Federal source code. As open-source developers for the federal government we should keep our entry up to date  so that more developers may find our code.  

The vets.gov entry should be removed, the va.gov entry should be updated as well as the url in the Gi bill comparison tool. 
https://code.gov/projects/va_oit_epmo_1_gi_bill_comparison_tool
https://code.gov/projects/va_oit_epmo_1_va_gov_website
https://code.gov/projects/va_oit_epmo_2_vets_gov_website

Code.gov pulls data from https://www.va.gov/code.json . It is unclear how that file is updated but contacting OSSOFT@va.gov would  likely be a good first step.

**Comment by alexpappasoddball** [comment]
Something to think about: similar tasks to look at is data.gov.

**Comment by alexpappasoddball** [comment]
Sent an email to that email address to see if we can't get the old vets.gov-website one removed in favor of the va.gov one.  Once I hear back I'll see if we can't get the gi bill one updated as well

**Comment by alexpappasoddball** [comment]
@annaswims Do you know what the correct url for the GI Bill Comparison tool should be?

**Comment by alexpappasoddball** [comment]
Got a response from Terri Gainsburg (Program Analyst).

"Thanks for letting us know about this.  I will look into it when our office creates the agency's next JSON file (currently done quarterly, last done in November) which is the source of the information on code.gov.  I may reach back out to you if we have questions".

I'll continue to work with Terri to get these updated for the next update.

**Comment by annaswims** [comment]
the Gi bill comparison tool is part of va.go (vets-website) https://www.va.gov/gi-bill-comparison-tool/ . https://github.com/department-of-veterans-affairs/gibct-data-service  is the repo for the data service.  The data service is for administrators to edit data and  what vets-api calls to get data, but veterans don't interact with it directly.

**Comment by johnpaulashenfelter** [comment]
Closing since there's not a lot of momentum here (with quarterly updates)
