### ISSUE TITLE
[Spike] Type of Care COVID-19 vaccine appointment 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#36455]
## Background/Request
When a veteran books a COVID-19 vaccine appointment, the appointment details page displays the type of Care as Primary. 

### Goal
The veteran will see COVID-19 vaccine as the type of care. 

### Requirements to Consider
- Assumption we are displaying the type of care based on the veteran's selection (for ex: COVID-19 vaccine)

---

## Tasks
- Answer the following questions:
  - Does the backend data treat COVID-19 vaccine appointments as Primary care? 
 

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by grossb1** [comment]
Currently in V0, the covid vaccine service type is being returned in the field char4: "CDQC", we should be keying off that field when displaying serviceType (typeOfCare) for covid vaccine appointments.
