### ISSUE TITLE
TestRail Account Setup for Aaron Hietpas

### ISSUE THREAD

**Issue by aaronhietpas** [department-of-veterans-affairs/va.gov-team#36456]
## Description
- I need a TestRail account for https://dsvavsp.testrail.io/ so that I can perform testing on one of my team's APIs

## Tasks
- Account created
- Account info sent to Aaron Hietpas

## Acceptance Criteria 
- Account info is sent to Aaron Hietpas and can be used to log in to https://dsvavsp.testrail.io/

**Comment by oseasmoran73** [comment]
Closing ticket as it has been handed over to Testing Tools team. See [slack](https://dsva.slack.com/archives/CBU0KDSB1/p1644002345847329?thread_ts=1643997414.852999&cid=CBU0KDSB1) for more details
