### ISSUE TITLE
[BE][MuleSoft] Add MuleSoft connection diagnostics

### ISSUE THREAD

**Issue by jchilders** [department-of-veterans-affairs/va.gov-team#36454]
In order to diagnose/verify connectivity to MuleSoft, a log statement needs to be added indicating the result of a test connection to MuleSoft. This will only indicate host availability. The value for the host is given by `Settings.form_10_10cg.carma.mulesoft`. Logging should occur regardless of whether or not MuleSoft is enabled, so long as there is a valid host given by `Settings.form_10_10cg.carma.mulesoft`.

## Acceptance Criteria

- [ ] During vets-api application startup, the result of a non-blocking call to MuleSoft is logged indicating whether MuleSoft is reachable from vets-api.

**Comment by RudyOnRails** [comment]
I think it’s good to run this by Platform to see if they already have something in place. I think the fwd proxy config file has health check url’s for this purpose.
