### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by jw81** [department-of-veterans-affairs/va.gov-team#36467]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username:  `jw81`
- Reason access is required:  I'm the lead developer on the Benefits Claims API in Lighthouse.  We have a lot of backgrounded logic that uses Sidekiq.  Access to the web ui would help in troubleshooting issues with background job failures.

**Comment by ericboehs** [comment]
Added
