### ISSUE TITLE
Align with Technical POCs on approach and handoffs

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36478]
- [x] Document created of expectations/requests for enrollment system team
- [x] Document shared with enrollment team
- [x] Process started to get sign off from enrollment system team that they can deliver, with agreed upon timeline for batch script to give 1095-B team the data needed

**Comment by ashleycastillo** [comment]
Batch script already done on enrollment side, so no 'agreed upon timeline' needed
