### ISSUE TITLE
Community Care Request - Incorrect Date Selection (VAOS service) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#36488]
## Summary
When testing userID Jacqueline.morgan@id.me and creating an appointment request for Podiatry. Selected the first earliest date 02/14 PM and 02/14 AM. On the review page, it shows the correct date selection. When the request has been submitted, the request details page shows the incorrect date selection. 

**Review details page:** 
<img width="481" alt="Screen Shot 2022-02-07 at 11 41 02 AM" src="https://user-images.githubusercontent.com/90797205/152832734-00f31dac-a5ec-4326-8c6a-483892dd2e8c.png">

## Steps to Reproduce
**Test User:** *Jacqueline.morgan@id.me*

1. Go to: [ttps://staging.va.gov]
2. Login as Jacqueline.morgan@id.me
2. Click on Schedule and manage health appointment 
3. Click on Start scheduling 
4. Click on Podiatry 
5. Select the first available date and AM and PM. Make sure the previous days are greyed out.
For example: 
<img width="414" alt="Screen Shot 2022-02-07 at 11 50 58 AM" src="https://user-images.githubusercontent.com/90797205/152833907-266fe8b6-15e6-4b7e-9a18-9ed74d2691f2.png">

### Actual Result
**Request details page**
<img width="415" alt="Screen Shot 2022-02-07 at 11 41 49 AM" src="https://user-images.githubusercontent.com/90797205/152833041-fac1cd6d-b404-44c5-b1dc-ac6c34bc338a.png">

### Desired Result
02/13/2022 date should not be displayed since it was not selected. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made

---

**Comment by aarathi-poldass** [comment]
This defect also affects VA Appt requests. Please find the screenshot attached
![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/dc0dcf7e-f448-4194-822d-c81ebe7dbd4c)

**Comment by ptouchton** [comment]
@aarathi-poldass 
   Nice catch...our fix is also handling the VA appointment request as well. Here is a screenshot from this morning's testing.
![image](https://user-images.githubusercontent.com/3951775/156043942-074b7ce0-0bff-4b6b-ac55-bcf86be57e6b.png)

**Comment by ldelacosta** [comment]
@aarathi-poldass - Please validate the VA appt requests issue you detected. Let us know if you have any issues. Thanks!

**Comment by ldelacosta** [comment]
Validated the changes in staging and the issue has been resolved. 

![Screen Shot 2022-03-10 at 10.46.34 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c6e27e91-91f0-4746-b330-70e6ce427f80)

![Screen Shot 2022-03-10 at 10.46.34 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/a8be2941-f6a9-4ea5-95c4-09ab36dbeee4)

**Comment by aarathi-poldass** [comment]
Successfully validated the defect for both VA and CC requests and the system is working as expected. VAOS is now displaying correctly date selection. Please see attached screenshot for reference. Please close the ticket.  
![VA_Request](https://user-images.githubusercontent.com/69315717/157759045-3de7a4ac-ff5a-4776-9645-9eee0129b131.png)
![CC_Request](https://user-images.githubusercontent.com/69315717/157759049-7ce7378c-68a4-454b-8c21-9922fb973c14.png)

**Comment by marcynadeau** [comment]
@ldelacosta This passed testing so I closed the defect.  cc @grossb1
