### ISSUE TITLE
Character of service field should not be conditional, or it should have the same visual treatment as other conditional fields in the form

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#3649]
## What happened?
Step 2 of Form 10-10EZ has 3 questions when the step loads: 

1. Last Branch of Service
2. Service Start Date
3. Service End Date

After you answer Service End Date, the Character of Service field appears below.  It doesn't disappear when responses to the above question are changed like our other conditional fields do, and the options make me think this is required regardless of the responses to the questions above it.

So, this is possibly a bug, and the field should be showing all the time.

But, if it is NOT a bug in the logic, and it is indeed a conditional field, then it should have the same treatment that other conditional fields get, with the blue bar along the left side.

Field in question:
<img width="683" alt="Screen Shot 2019-11-21 at 11 23 16 AM" src="https://user-images.githubusercontent.com/55992116/69357454-202f2180-0c53-11ea-882d-338479f68e05.png">

Example of conditional field:
<img width="967" alt="Screen Shot 2019-11-15 at 10 47 22 AM" src="https://user-images.githubusercontent.com/55992116/69357647-74d29c80-0c53-11ea-9c06-54f60e17c39f.png">

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User _(if applicable)_:  not signed in

## Steps to Reproduce
- URL: https://www.va.gov/health-care/apply/application/military-service/service-information

1. start w/ the URL above, and choose the option to start the form without signing in
2. make your way to step 2, `Last Branch of Service` question
3. provide responses to the 3 questions displayed
4. watch Character of Service field auto-magically appear

## Desired behavior
If the field is not conditional, it should display when the step loads. If it is conditional, it should be visually consistent with other conditional fields in the form

## Acceptance Criteria
- Field displays on screen when step loads OR has same visual treatment as other conditional fields

**Comment by Justin-Pickett** [comment]
@bradl3yC can you take a look into this bug?

**Comment by Samara-Strauss** [comment]
@bradl3yC please hold off until I confirm who should be fielding health care application related questions.

**Comment by AZSchneider** [comment]
It looks like this probably shouldn't be conditional. A veteran needs to have separated from service to be eligible for healthcare, and the terms of discharge may affect eligibility, so I'd say it's a bug. It's not preventing the form from being submitted, it doesn't seem, so we can look at prioritizing fixing it, but it doesn't look urgent to me.

**Comment by ndsprinkle** [comment]
After digging into this, I understand the conditional field and the conditions that cause it to appear/disappear. The Character of Service field will only appear when the Service End Date is before "today", which would mean the veteran is already discharged. If the Service End Date is changed to be after today, then the Character of Service field will disappear. None of the other fields impact whether or not Character of Service appears as a field, only Service End Date. This mostly makes sense as the Character of Service field describes why the veteran was discharged and if the veteran hasn't been discharged yet then it wouldn't make sense to fill out that field. 

However, based on what you are saying @AZSchneider , it sounds like we really need the validation to be around the Service End Date field to make sure the date is before today? Whether or not that is the case, it definitely sounds like Character of Service needs to be visible all the time, so I'll start with that change and if there needs to be validation around the Service End Date, then I will add that as well.
