### ISSUE TITLE
Benefit application notes

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#365]
Lauren, Ryan, Alex, Layla, and Jared went over some of the content of in the Benefit Applications draft page: https://dev-design.va.gov/patterns/benefit-applications

This is a list of things to do. I don't think publishing the page should be dependennt on all tasks getting completed. The page should be published when it's _good enough_. When is it _good enough_? 
- All notes in the page content are addressed
- There is nothing in the content that is blatantly wrong

## In General (all sections)
- [x] Use sentence casing for all headings
- [x] We liked the overall structure of the Eligibility documentation, so we'd like to format the other sections the same way, with images. Maybe if @KevinMHoffmanUSDS could provide his sketch file
- [ ] Repeat the illustrations with a smaller image, but highlight the current section being documented. @jaredcunha-usds can do this.
- [ ] Jared will look at adding anchor links to the diagrams

## Intro section
- [ ] "Think about eligibility" -> "check eligibility"
- [x] "Application introduction apply page" -> Apply now. This would be to create unity between the numbered list of epics and right rail.
- [ ] Add context to the numbered list. Maybe one sentence to define
- [ ] Finesse the intro text a bit. @lalexanderson-dsva seemed to have some ideas.

## Eligibility
- [x] remove commas in the bulleted lists
- [x] Consider alphabetic instead of numeric references to the different sections
- [x] "Common Scenario Overview" -> “Critically important info”
- [x] Update the do/dont example to use do don't pattern. Jared can do this.
- [x] Update documentation so there is only **one** blue box per page. In the do and don't
- [x] Alerts are not built to go above the H1 and intro text. Goes below intro text.
- [x] Team felt common scenario section and prerequisite section were not be totally resolved. How should a designer decide what goes in common scenarios and what goes in prerequisites? We will need input from the content team on this.
	- Maybe the blue box is universally applicable, and the no. 4 content is stuff that really matters if it applies
        - Jen: blue box is eligibility that applies to everyone/vast majority. outside of the blue box goes into more nuance for people who have additional requirements… super nichey info for smaller Veteran groups that still have a pathway to get that benefit.
          - "Prerequisites" -> "More detailed eligibility info and additional scenarios"
- Primary action section
	- [x] Generalize content to be more about call to action to help designer decide when to use a wizard or when to use another call to action. For information about differences between signed in and signed out experience, forward to [signed out vs signed in](https://design.va.gov/patterns/signed-out-signed-in)
	- [x] Remove content about how wizards to work to [wizards documentation](https://design.va.gov/patterns/wizards)
  - [x] We probably don’t need the summary of components to be at the bottom. We should think about if can be brought in line to the relevant locations in content or moved in whole towards the top

## How to apply
- [ ] Use the images and structure from Eligibility write-up
- [x] In _Preparing to apply_,  indicate the need to send users to eligibility section to make sure they are eligible.

## Apply Now
- Information to add:
  - [x] Explain that it's not a static page, start of react application
  - [x] Indicate what content from other pages we repeat
  - [x] Eplain why it's a seperate page

(this is as far as we got)

**Comment by peggygannon** [comment]
@jaredcunha-usds
@rtwell
 hello, I've made some updates to the "How to Apply" and "Apply" sections. PR is here below: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/129

I'm unable to merge this PR, however, can someone merge this for me? or give me access to merge?

**Comment by jaredcunha-usds** [comment]
I merged it. Should be on https://dev-design.va.gov/patterns/benefit-applications in 5-10 minutes of the time I'm writing this.

**Comment by caw310** [comment]
Closing as this is over 3 yrs old and should be addressed.
