### ISSUE TITLE
Deploy updates to Azure Govt resource within Github Action container

### ISSUE THREAD

**Issue by khathuynh-tw** [department-of-veterans-affairs/va.gov-team#36510]
## Description
The Virtual Agent Chatbot team is updating our Github pipeline to deploy changes to a resource in Azure Government. Previously, the pipeline commands were successful when pointing to a commercial instance. We are now seeing errors after updating the connection to point to an Azure Govt instance.

After touching base with Microsoft, we are looking for support with troubleshooting potential network restrictions within VA Github Action containers.

## Background/context 
The team is preparing for a Feb 28 launch and is in the process of setting up three deployment environments in Azure Government: dev, staging/preprod, and prod. Therefore we are updating an existing pipeline to deploy changes to QnAMaker to no longer point to the commercial resource, and instead to the new dev resource in Azure Govt.

## Technical notes
The resource in question is QnAMaker. 

Here's the errors:
For write operation
```Handling qnamaker knowledge bases...
Qnamaker build failed: Cannot read property 'knowledgebases' of undefined
```

For read operations
```Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
```

There are two things of note:
- Microsoft Bot Framework CLI commands work for old commercial instance of QnAMaker in the _pipeline_, but not for new Azure Govt instance in the _pipeline_.
- Microsoft Bot Framework CLI commands work successfully on local machine for the new Azure Govt instance. 

Github Action .yml and package.json-defined script:
[yml](https://github.com/department-of-veterans-affairs/va-virtual-agent/blob/master/.github/workflows/deploy-qnamaker-staging.yml)
[script](https://github.com/department-of-veterans-affairs/va-virtual-agent/blob/master/automated-content/scripts/deploy-qna.sh)

---

## Acceptance Criteria 
- [ ] Be able to run Microsoft Bot Framework CLI commands against QnAMaker resources located in Azure government, within GitHub Action container/pipeline. Specifically `bf qnamaker:build`

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
The infrastructure team doesn't have any access or knowledge of Azure resources. Current GitHub runners have fully open egress rules (should be allowed to connect to anything). I'm not sure we're going to be able to help here.

**Comment by khathuynh-tw** [comment]
Thanks for the reply. We will reconnect with the Microsoft team to see toward a resolution.
