### ISSUE TITLE
GovCloudPlus: Create maintenance window for 10-10CG (in PagerDuty)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36529]
## Description

The Caregiver team will be migrating from Gov Cloud to Gov Cloud Plus around Feb 25/26th.
In support of this effort, we will need to take the app offline via PagerDuty.

## Background
- Platform Support request opened: https://dsva.slack.com/archives/CBU0KDSB1/p1644899024861899

## Tasks
- [ ] Get PagerDuty access
- [ ] Add a maintenance window once we know exactly when the GovCloudPlus migration date/time is.

**Comment by SKasimow** [comment]
@RudyOnRails I broke the ticket up into 2 parts with the 2nd part being taking the app off-line at appropriate time.
Is there a way to test this out in staging before going to prod? If so, lmk and I can update ticket.

**Comment by RudyOnRails** [comment]
Good idea on the two tix. I am looking into the FE downtime alert.

**Comment by RudyOnRails** [comment]
I asked around and so far I've been told that downtime can be added to PagerDuty. I think we need to create a PS request or they will give someone on our team access and we add the time block directly.
