### ISSUE TITLE
Cancel (PUT) appointment makes a call to new_appointment, that needs to be fixed.

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#36521]
In the appointment controller update_appointment is currently making a call to new_appointment incorrectly.  It should be calling update_appointment in the get_clinic method.  Please see https://issues.mobilehealth.va.gov/browse/VAOSR-2955 for more details

**Comment by ajmagdub** [comment]
modified V2 appointment controller update call to use updated_appointment method instead of new_appointment call.

**Comment by grossb1** [comment]
We were able to validate this ticket when testing:
https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/34787
