### ISSUE TITLE
"Use my Location" search issues

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#36539]
## Issue Description
When trying "Use my Location" feature I found the following issue:

If I started my map search with a city and then tried “Use my location” it would not refresh.

---

## Acceptance Criteria
Users should be able to changing to/from feature when using "use my location"
---
## How to configure this issue
- [ ] **Labeled with Type** (`bug`)

**Comment by nbarthelemy** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20329

**Comment by hallihocine** [comment]
Currently it's working only if you execute the first search using Keyboard. It's not working if you are using the mouse.  This needs to be fixed.

**Comment by nbarthelemy** [comment]
Updated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20389/

**Comment by nbarthelemy** [comment]
Moved to validate. Here is a screen recording of the functionality working as expected.

https://images.zenhubusercontent.com/133843125/f8a481e4-aa17-4098-8386-90cc88aa7f29/screen_recording_2022_03_04_at_10_42_03_am.mov

**Comment by hallihocine** [comment]
Ticket has been validated in staging: the results are now refreshing when switching to "Use my location" link. See below:

https://user-images.githubusercontent.com/86266024/156835941-2fbc89ad-794d-4bae-81b5-732563c05771.mov

**Comment by hallihocine** [comment]
- Test Run in Test rail:
https://dsvavsp.testrail.io/index.php?/runs/view/3025&group_by=cases:section_id&group_order=asc&group_id=3710
- Test Steps: 
["Use my Location" search issues.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8188579/Use.my.Location.search.issues.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed on 3/7/2022.
