### ISSUE TITLE
Discover GitHub support for multiple Pull-Request templates

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#3654]
\[Low priority - Work on this as time allows]
## User Story
As a VSA Engineering team member, I want to open a PR and see boilerplate guidelines/content specific to VSA PRs (as distinquished from VSP or other non-VSA PRs).

## Goal
Determine possibility/feasibility of hosting two separate PR-templates in a GitHub repository -- one for non-VSA PRs and one for VSA-specific PRs.

## Objectives or Key Results this is meant to further
- Improve QA/testing process documentation & dissemination
- Improve quality of PRs opened by VSA team members

## Acceptance Criteria
- [ ] Research documented sufficiently here to support implementation decisions.

**Comment by tlei123** [comment]
GitHub does have support for multiple PR-templates.

So far, however, the only relevant GH documentation I've found describes accessing the different templates via URL-parameters \[see links below].

See these two different PR-templates created in my test-repo:

- PR-template 1: [https://github.com/Tze1/test-repo/compare/master...test-pr-templates/?expand=1&template=pr-1.md](https://github.com/Tze1/test-repo/compare/master...test-pr-templates/?expand=1&template=pr-1.md)
- PR-template 2: [https://github.com/Tze1/test-repo/compare/master...test-pr-templates/?expand=1&template=pr-2.md](https://github.com/Tze1/test-repo/compare/master...test-pr-templates/?expand=1&template=pr-2.md)

I'll continue research on exposing the different PR-templates in the UI.  I'm hoping there's a way to present the templates the same way one is presented with the [Issue-templates screen](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose) when one opens a new issue.

**Comment by tlei123** [comment]
Nothing in the GitHub repository settings enables any UI-support of multiple PR-templates.  The templates-selection screen was only implemented in GitHub for issue-templates.

I'll start researching customizing the PR buttons via a custom browser extension (the same way ZenHub customizes GH screens with added PM/CI/CD features).  Hopefully, the PR buttons can be customized into a "pull-down" button displaying PR-template options.

I recall @erikphansen has developed a custom Chrome extension, and I will discuss feasibility & effort estimate of a browser-extension with him.

**Comment by erikphansen** [comment]
@tlei123 I am an absolute noob at browser extension development but it seems like it might be feasible to do. BUT, it would probably be fragile (GitHub might change something in the page we're modifying and our extension would break) and we'd also need a Firefox extension that does the same thing. It would be a fun thing to look into, but my gut tells me that it might not be worth the effort.

Also, and this is a minor point, I am probably in a very tiny minority here but I use the `hub` command line tool to make the PRs, so I'd never see this pull-down button that would allow me to choose which PR template to use :) Buuuuuuut it would be totally possible for me to adjust my command line script (https://github.com/erikphansen/bin/blob/master/fish/functions/pr.fish) to use a different PR template depending on the flags I used when running the script.

**Comment by tlei123** [comment]
Thanks, @erikphansen !  I will start looking into Hub..

I think both browser-extension and Hub implementations are going to be brittle code-wise, but just having a PR-process doc & email telling contributors to manually add a pr-template url-parameter is probably going to be even more brittle process-wise.

I will also start researching GitHub-App implementation to see if robust access to GitHub APIs can help improve maintainability.

Stay tuned!

@jcosta-gcio , your interim input is welcomed.

**Comment by tlei123** [comment]
Closing.  No GH UI-feature for multiple PR-templates, and no time to research developing GH app or browser-extension.
