### ISSUE TITLE
Access for Austin Covrig

### ISSUE THREAD

**Issue by acovrig** [department-of-veterans-affairs/va.gov-team#36545]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Austin Covrig

### Your Email

austin.covrig@oddball.io

### Name of Your Team

VA API, Rails Engineer, Oddball

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAW67WHNE48PKrF+428mR03hc32G29zUbXZ+9rsDA/Ys1BAgsrILh6gcyNX+Gj5xpm+2V38M6cMWqmblcqOP+FcsqleNXr6lnrHanGELlAlYPOzz6MxiXtaTmjLeTIA3Lu7aw5MPhgi+iTBhLu81OX2dDYt8jKZWfARqZYRxbJnvEnJG0kzoaCMYoGsimA3FBflsCUhhzDsTprs0kwvZazO+qnR+Th5PIIK7wqel/EpJzYQeH6ajJdbFPtlQF0iBAFKpS8np09HepXvXv3KPeneG2vsCBHuL28tmPZXiDU+m+Tqns2MNaFy9tgBZvZxcHWGiB5Vjombzs++1L2FVMCL/QKe1U4EL0asTpvyk4RSgvObYrk8v+KOm3Qi/OI/M4u2F8t0nS4q656+gUUq4XQl5TDqan2fY13kAjqKUDLGQ3IIwUivk3cWUyjiGF5FT2uS2Zcm2gp4Nr4qk49x1q8GjbnUtyJYC2+oLox8V0RNQMkAkPqq3TOzVFkGPEHeD8= austinc@oddball

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
