### ISSUE TITLE
Create a research plan for user testing with FE engineers

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#36555]
As part of the [Discovery Initiative]: Improve Design System Technical Process we will be doing user research with FE engineers to identify areas for improving documentation and usage of the Design System. 

- [x] Review the Mural board from the research exercise to pull out the questions that came up (Carol)
- [x] Draft research plan for interviews with frontend engineers who use the design system (Carol with help)
- [x] Identify list of 8 FE engineers to interview (Katy and DST engineers)
- [x] Reach out to the engineers and schedule sessions (Carol or Katy)
- [x] Draft script for user research sessions (Natalie)

**Comment by GnatalieH** [comment]
@k80bowman and @caw310 I've created a draft of the script [here on Confluence](https://vfs.atlassian.net/wiki/spaces/DST/pages/2092367933/FE+Engineer+Conversation+Guide). We may want to make some tweaks, but I think we'll be right at our target time (45 minutes, including intros and closings) for each session with the number of questions we have now.
