### ISSUE TITLE
R&S Article Collab Kick Off Next Steps

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#36564]
Hi @nicole-leonard. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to static content page(s) so we are recommending the following Collaboration Cycle touchpoints:

Design Intent

Staging Review

Privacy, Security, Infrastructure Readiness Review

Since your work impacts static pages, please reach out to Dave Conlon to review how your work may overlap with any existing work. This will help them prioritize and identify possible areas of support needed from other teams.

The following practice areas will be included throughout the Collaboration Cycle process:

Design
Content
Information Architecture (IA)
Quality Assurance (QA)
Accessibility
Product
We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately.

Your project has been added to the Platform Collaboration Point Tracker. When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the Collaboration Cycle Touchpoints page.

In addition, Resources & Support articles are out of scope for Collaboration Cycle, but since this work impacts the look and feel of all R&S pages, I think it makes sense for us to provide feedback. Thanks for bringing it to us!

**Comment by nicole-leonard** [comment]
@davidconlon Please see this comment and let me know how we should proceed. 

Since your work impacts static pages, please reach out to Dave Conlon to review how your work may overlap with any existing work. This will help them prioritize and identify possible areas of support needed from other teams.

**Comment by nicole-leonard** [comment]
@davidconlon I still need you to take a look at this.

**Comment by davidconlon** [comment]
@nicole-leonard I don't believe this overlaps with any existing work. Thanks for checking.

**Comment by nicole-leonard** [comment]
Confirmed that this change does not affect any other pages outside of R&S. Collab cycle may proceed.
