### ISSUE TITLE
Track if DD errors occur during DD setup or update

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3656]
We currently report the following error types to Google Analytics when there is an error in saving/updating Direct Deposit bank info:

- 'mailing-address-error'
- 'home-phone-error'
- 'work-phone-error'
- 'flagged-for-fraud-error'
- 'invalid-routing-number-error'
- 'payment-restriction-indicators-error'
- 'other-error'

But we don't know if those errors happen for users who are _updating_ their existing bank info that's on file, or if they are _setting up_ direct deposit for the first time. We should track that info as well. The motivation for this is that we want to better understand if users who are setting up DD for the first time are running into errors more frequently that those who are updating their bank info.

I would recommend appending `enroll` or `update` to the ends of each of the above error codes that we report to GA.

**Comment by erikphansen** [comment]
@nedierecel @clantosswett For now I'll plan to change the strings that we send as the `error-key` when DD save errors happen, as described above. Let me know if you want to instead add a additional key to the object we send to GA when the errors happen.

**Comment by nedierecel** [comment]
Thanks @erikphansen - Based on our chat, we can append `update` or `enroll` to the error key in lieu of creating a new key to the object.

**Comment by erikphansen** [comment]
re-opening and moving to Validate. The change will go out today. Once it's live @nedierecel can confirm that the updated strings are getting sent to GA.

**Comment by nedierecel** [comment]
@erikphansen - I'll confirm. We should see this appear within the dashboard. Thanks!

**Comment by Justin-Pickett** [comment]
@nedierecel can you confirm that this is appearing in the dashboard now. Thanks so much. Looking to close out this ticket.

**Comment by nedierecel** [comment]
@erikphansen @Justin-Pickett I'll do that - I'll check back later today and tomorrow AM.

**Comment by Justin-Pickett** [comment]
Okay great! Im going to assume (which i try not to do to often)that the info will be on the dashboard and go ahead and close this ticket for this sprint 9. If you find that its not on the dashboard when you check back, we can reopen this and just get it in Sprint 10 which begins for us tomorrow. Thanks again @nedierecel
