### ISSUE TITLE
Offboarding Requests - Remove Users from Domo

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36586]
## Issue Description
We need to add a step to our offboarding request process to remove users from Domo and any other systems we own rather than archive.  Update offboarding docs to look for any datasets or dashboards owned by the user.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laurensimpson14** [comment]
@chloedotbrown I deleted all archived users who didn't own any assets. 

There were 6 users who owned assets (Ben McGrady, Jason Cavnar, Joanne Esteban, Jon Wehausen, Mandy Massengill, and Rebekah Hickey). I reassigned all of their assets to you. Are you able to access them? If so, I think it's safe to delete those individuals now too.
