### ISSUE TITLE
Access for Matthew Ng

### ISSUE THREAD

**Issue by Matth-Ng** [department-of-veterans-affairs/va.gov-team#36595]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Matthew Ng

### Your Email

matt.ng@adhocteam.us

### Name of Your Team

PTEMS - Console UI - Senior Software Engineer - Ad Hoc LLC

### Service(s) You Want Access To

AWS

### Desired AWS Services

EKS
RDS

This ticket follows https://github.com/department-of-veterans-affairs/va.gov-team/issues/35821 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/36587 where @ericvoshall @jchapin  requested access for the same reasons.

- My E-QIP has been completed

### Access Expiration

Ongoing

**Comment by td-usds** [comment]
Approved for the same scope as https://github.com/department-of-veterans-affairs/va.gov-team/issues/35821

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.
