### ISSUE TITLE
Update Slack failure notification to inform app teams about build failures

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#36598]
## Details
When single/grouped app pipelines fail in `master`, app owners should be informed in the Slack. We currently have failure notifications sent to [#status-vets-website](https://dsva.slack.com/archives/C02V265VCGH) when commits fail from the [notify failure job](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/continuous-integration.yml#L960). This job should be updated to handle notifying teams when needed.

There are two possible approaches for notifying teams
- Tag teams in the alert message in the #status-vets-website Slack channel
- Send the alert to the team's specified Slack channel

The [changed app build config](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/changed-apps-build.json) may need to be updated to allow teams the option of adding a Slack channel, depending on the implementation that's used.

**Comment by theodur** [comment]
After a mob session that Sri, Tim, and I had last Friday, we were able to get the functionality for this working. I opened a [draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20286), and tested the notification in the [#test-single-app-builds](https://dsva.slack.com/archives/C032FM8LFCN) Slack channel.

**Comment by theodur** [comment]
Since we don't have single/grouped app builds enabled in `master`, we shouldn't be alerting teams yet, because failures could be unrelated to app changes in a commit. I added an environment variable (`ALERT_TEAMS`) to the `Notify Failure` job in CI that will prevent teams from being alerted until we release in `master`.

**Comment by mydesignrocks** [comment]
Looking good, we could probably close this ticket and reconvene when it is time to give the respective teams' channels for alerting. Thanks @theodur !

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20286) has been merged ✅. The `ALERT_TEAMS` variable is set to `false` for now. We'll need to set this to `true` when we [enable single/grouped app builds](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34868) in `master`.

The changed app build [draft documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/2031484979?draftShareId=7f53e7cf-225a-45ab-a379-b2a16cb468a7) has also been updated to include information on single/grouped app build notifications.
