### ISSUE TITLE
[FE] Modify *authenticated* 10-10ez to be uneditable | Pt 2

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36613]
## User Story

As a Veteran, I need to avoid inappropriate modifications to MPI so that my data remains accurate.

**If the user is authenticated,** we pre-populate some of the fields for them, based on the values in the Master Person Index (MPI). However, these fields are editable, and may be changed by the user.

## Expected Behavior

The purpose of this story is to ensure that veterans are unable to edit fields based on the values per the MPI. At present, despite their pre-population, these fields are editable. They should not be.

Design Ticket: #31989

### For the *authenticated/logged-in experience*:
- [x] Prefilled MPI data not modified in payload sent to ES
- [x] Payload structure sent to ES is not modified 
- [x] Reviewed by designer in RI

## Resources
- [Design PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/7539409/Personal.info-locked.11.3.pdf)

- **_NOTE LINK:_** Find a VA location tool link: https://www.va.gov/find-locations 

- Flow for authenticated & unauthenticated experience (click to make bigger)

![flow.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/7705d24a-079c-4248-9dd3-a3309544f125)

**Comment by SKasimow** [comment]
@lzapson here's part 2 of #34049. I left some of the shell in so feel free to remove if not relevant.

**Comment by RudyOnRails** [comment]
@lzapson added a quick BE ticket to sum up what we discussed with @lihanli 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/37098
