### ISSUE TITLE
Network - update error page on TIC gateway

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3661]
## User Story or Problem Statement
At the TIC gateway, there's a configuration for a page to serve to users when the gateway can't reach our systems and the app has to be marked as down. The current web flow has a VBA error page configured, and the TIC will redirect users there instead of proxying it. Additionally, static assets on the error page are served from www.va.gov and that doesn't work when the error page is being served. How might we update this configuration to load a page that we control and force the page to have an http status that indicates an error rather than redirecting to a separate site?

The second part of the work:
This is a ticket to track work related to incident where all ingress traffic was not making it to api.va.gov and partially to www.va.gov on Jan 17, 2020.

Raised with GW Ops as INC9156670

Conversation / alarms started here: https://dsva.slack.com/archives/C30LCU8S3/p1579241593008900
Some additional distilling of info here: https://dsva.slack.com/archives/C0S6H6BQU/p1579251491003800
From this issue: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4962

## Goal
When our backends are unreachable by the TIC gateway devices, a user should see a page that the VSP group designed, and the user should be able to refresh the page to see if it loads correctly.

## Objectives or Key Results this is meant to further
Ensure VA.gov is a reliable site for Veterans to use

## Acceptance Criteria
- [ ] error page is agreed upon by VSP leadership
- [ ] the TIC gateway is able to serve that page even if it can't reach VSP systems
- [ ] Sync up health check for www.va.gov and api.va.gov

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
@ricetj is there an epic that this could fall under?

**Comment by ricetj** [comment]
> @ricetj is there an epic that this could fall under?

@wyattwalter, not one that can fit cleanly. Do you think there is enough work here for it to be its own epic?

**Comment by jhouse-solvd** [comment]
Q's: 

Do we know if this is still a problem? 
How can we reproduce?

**Comment by wyattwalter** [comment]
Hey Jesse, I would be shocked if it were changed. The only way we'd know is if the revproxies are unreachable from the F5's (which would mean that the site was down) or if Gateway Operations tells us. This is a setting that they set and we should be the ones to tell them what to do. They'll want to proxy or redirect to an error page rather than try to host the error page. I'm not sure what the right answer is there as to what should be fought for. Happy to help further if you need more.

**Comment by jhouse-solvd** [comment]
@meganhkelley - Noticed this in our backlog (quite old) but the goal is: 

When our backends are unreachable by the TIC gateway devices, a user should see a page that the VSP group designed, and the user should be able to refresh the page to see if it loads correctly.

Let me know if this is on your radar

**Comment by jhouse-solvd** [comment]
@f1337/@drorva/@mchelen - This is older but still interesting. Can you read the problem statement and goal and let me know how/when we might want to prioritize something like this? I don't think it's a super high priority, so wanting to possibly stick it in the icebox if it's not something that we need to tackle this year.

**Comment by drorva** [comment]
The solution is probably to have the TIC redirect users to a page on S3. That way, we can change the page to our hearts content. Not sure if S3 will let you return a 5xx response. 
And of course, we need to make sure that once things go back to normal, the TIC send users back to va.gov.
The biggest challenge I see here is testing this. 
Let's revisit at the end of Q3.

**Comment by jhouse-solvd** [comment]
Relevant recent discussion: https://dsva.slack.com/archives/C03FECE9K/p1629895537023900

@mchelen-gov - We feel like part of the work here is to design a web page that providers a better experience for VA.gov users when there are network or operational issues. 

The ops team can certainly assist, but would love for you to evaluate this issue and see if there is another team that might help move it forward. It's been on our backlog for a long time.

**Comment by jbritt1** [comment]
Is this closable? Coming up on 3 years in backlog and not likely to be prioritized anytime soon...

**Comment by rmtolmach** [comment]
There is not a need for this at this time. Closing.
