### ISSUE TITLE
Setup Test in Google Optimize (A/B Test Rated Disabilities)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36623]
## Background
One of the mechanisms in getting the A/B test completed is to setup Optimize appropriately.

## Considerations
- This is different than the initial script effort with Optimize; this is for the test itself.

## Tasks
- [x] Setup Optimize for this A/B test
- [ ] TBD

## Acceptance Criteria
- [x] Google Optimize has been configured

**Comment by cohnjesse** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/36894

**Comment by jason-gcio** [comment]
1. content security policy
2. set up feature toggle ✔
3. write code change for sorting
4. run test
