### ISSUE TITLE
Internal Testing with Address Validation Modal

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3663]
## Background 

This is ticket serves as  internal testing ticket for the work completed for the Address Validation Modal. 

## Goal 

To test in staging the address validation modal and validate the dev work is working as intended. 

## Acceptance Criteria 

1. Team has tested the modal on staging  
2. Ready to send to QA to be tested

**Comment by bradl3yC** [comment]
Save/Update API is not using addresses from the validation endpoint in the condition there is only 1 CONFIRMED address
