### ISSUE TITLE
[VAMC] Research and document current status of VET Center deployment accross Districts [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36647]
## Story
As a Veteran I need to know where my district is in upgrade, so I can find and review my new VET center website

## Resources
VET Center Tracking in Help Desk

## Tasks
- [x] Develop Excel data chart with tracking information from CMS

## Acceptance Criteria
- [x] Artifact tat can be used for data and graphic tracking.

**Comment by ltrombley** [comment]
Task #36647 - Research and document current status of VET Center deployment across Districts - is Complete and moved to Validate
