### ISSUE TITLE
[AWS/GitHub]: Repository service account for Console UI Team

### ISSUE THREAD

**Issue by ericvoshall** [department-of-veterans-affairs/va.gov-team#36648]
### Link to GitHub repo

https://github.com/department-of-veterans-affairs/backstage-test

### Team Name

Console UI Team

### Product Owner

In the process of transitioning from Rachael Roueche to Mike Pritchard.

### Product Manager

Lee Helmer

### Related Issue

#36494

### Acceptance Criteria

- [x] aws_iam_user created
- [x] policy attached to user
- [x] terraform applied
- [x] AWS API keys created for aws_iam_user
- [x] AWS API keys added to team's repo (specified above)

**Comment by jhouse-solvd** [comment]
@ericvoshall - Thanks for submitting this! We'll get started on it. 

In order for the Infrastructure Team to add the AWS/GitHub service account credentials to the repo provided above: 

**Please grant admin access on the repo to** [VSP Operations team - @department-of-veterans-affairs/vsp-operations](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-operations)

**Comment by ericvoshall** [comment]
@jchapin - can you grant that access?

**Comment by jchapin** [comment]
@ericvoshall, Yes I can!

@jhouse-solvd, I went ahead and granted access to:

https://github.com/department-of-veterans-affairs/backstage-test - Which is our Backstage test/prototype repo

https://github.com/department-of-veterans-affairs/platform-pst-console-ui-configuration - Which is a separate repo we're using just for configuration, it's included as a git submodule in the repo above... so we can have a wider audience collaborate on config.

https://github.com/department-of-veterans-affairs/test-oclif-console-cli - Our prototype CLI project we're using to explore authentication to key cloak on the command line, this one you might not, "need" but I want to make sure you have everything you might want.

**Comment by jsgarmon** [comment]
`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` added as secrets to the backstage-test repo. Once we get everything else set up, we can add workflows to that repo to automate pushing images to ECR and updating the k8s manifest.

**Comment by jhouse-solvd** [comment]
@jsgarmon - I think this is good to go? Please comment and close if so. thank you :)

**Comment by jsgarmon** [comment]
Yep, all tasks for this completed.

**Comment by jchapin** [comment]
![Screen Shot 2022-02-11 at 2 01 59 PM](https://user-images.githubusercontent.com/116142/153653428-1442e78b-fc7c-48fa-9158-dbf70480ecaf.png)

Confirmed. We see that they're added.
