### ISSUE TITLE
Request access to Domo

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#36657]
Domo access request:

Name(s): Russell Lyons
Email(s): russell.lyons@va.gov
Team: DGIB
(Optional) Dashboard: N/A

**Comment by laurensimpson14** [comment]
You have been granted access to Domo! 🚀 You should receive a welcome email with instructions on how to get logged in. Please feel free to re-open this ticket if you have any trouble or questions!
