### ISSUE TITLE
Support - Create Robust Sample Project for VFS teams

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#3666]
### User Story

As a VFS team, I want a sample project to look to for guidance so that I know what we are creating is inline with VSP's expectations.

### Problem Statement

Right now, we don’t have an example new or old VFS teams can turn to and get a perfect example of all our practice areas best practices. 

## VSP Objective (Q1 & Q2 2020)

O5: All customers comply with the Platform's standards.

## Measuring Success (KRs/KPIs)
Reduction in non-compliance across VA.gov products for at least 5/10 practice areas.
Avg volume of tough convos per customer
% customers meeting IA standards
% customers meeting content standards
% customers meeting design + research standards
% customers meeeting QA standards
% customers meeting 508 standards
% customers meeting coding standards
% customers meeting product mgmt standards
% customrs meeting performance standards
% customers meeting analytics standards
% customers meeting security and privacy standards

## Details and Notes
The BE team has started utilized a project on VA.gov but most of the practice areas were not taken into account when building it. 

### Assumptions and Hypotheses

We **hypothesize** that  **if** we create a sample project that meets all our standards **then** VFS teams will be able to look at that as an example and ask less questions/create better code/features in their first attempt.

## Definition of Done
A feature on VA.gov adheres to the best practices of all the practice areas. 

AC:
[ ] - QA Example
[ ] - Product management included
[ ] - 508 included
[ ] - Design included
[ ] - Engineering included
[ ] - Timeline of checkins with VSP included
[ ] - Content included
[ ] - IA included
[ ] - Analytics included

**Comment by rroueche** [comment]
@andreahewitt-odd  I think the product here is the "Sample Project" not Support, but again open to pushback if you want to make the case for the other way!
