### ISSUE TITLE
Access for Allison Lu

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#36670]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Other

### Your Name

Allison Lu

### Your Email

allison@cityfriends.tech

### Name of Your Team

PTEMS VA.gov Modernization, Sr. Frontend Engineer, Friends From The City

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCy07k2s6fBAMI2fIFJelMB9jQa/lctVDwItTR9wXo/WmsrJRxPR2uJ74lbQDwJq25X9gOT6daNmJHaV7/DaFBlidsZgSOglYr1uXEqwOyv/r9nY/U0zsdQgNIISbI85uDUibO/4fo4YoR64lDINhTBbMShsVrqHKEKmta2NKNjMo++QGbqHZUn6ck1/tl6TWmuyXhQAThbbJSaC9ZVWaXneyOQJ7poA6MylcUYlWEuLYr/eREljZpReRnU6VpXdkDPAWQYdVBmbH+I+m02bsRQRoSg7tQttAJaS19UTT8P4rSXqGNUfA0YmmehmyT3/P6lYfAILgLk+kgKcAekbPgOJsBbsM6m5BKuNb23B4B4sHblvdbDXplZctjy1hSyK4GGUTlEkqrvc8dTvd7iwjRgq9YiEgJTFYKCD7z/AuBawQrN4Ow3KSpUQfhqGqXz6Pnz4uebKv2Wu4K0TCwLpjEiUs5/sInaFNhdDuqivYEDzJci2vWeZmOwV62MSJdtorE= allison@allisons-MacBook-Pro

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
