### ISSUE TITLE
Send GovDelivery email to content style guide subscribers about recent updates

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3668]
User story: As a subscriber to the VA.gov content style guide newsletter (via GovDelivery), I want to be notified when significant changes or updates are made to the content style guide. 

[ ] Add updated info to the What's new section of the design system: https://design.va.gov/documentation/whats-new.html  [See example screenshot.]

[ ] Write and send GovDelivery email. ( @RLHecht - set up a time with me when you're ready for this part and I'll show you. ) 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/57373fe7-e1f5-4f71-a974-023388f0aa0f)

**Comment by RLHecht** [comment]
This work was completed. Closing issue. @Karak888
