### ISSUE TITLE
Request public web sites intake

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36688]
## Considerations
- gather needs for COE's landing page with public websites
- review [IA recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md)

## Tasks
- [x] Get the ball rolling with ensuring the top of funnel pages were in place.
- [ ] ...

## Acceptance Criteria
- [x] A request has been made

**Comment by candy-gcio** [comment]
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/37424
