### ISSUE TITLE
Access for Austin Covrig

### ISSUE THREAD

**Issue by acovrig** [department-of-veterans-affairs/va.gov-team#36681]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Austin Covrig

### Your Email

austin.covrig@oddball.io

### Name of Your Team

VA API, Rails Engineer, Oddball

### Service(s) You Want Access To

AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAW67WHNE48PKrF+428mR03hc32G29zUbXZ+9rsDA/Ys1BAgsrILh6gcyNX+Gj5xpm+2V38M6cMWqmblcqOP+FcsqleNXr6lnrHanGELlAlYPOzz6MxiXtaTmjLeTIA3Lu7aw5MPhgi+iTBhLu81OX2dDYt8jKZWfARqZYRxbJnvEnJG0kzoaCMYoGsimA3FBflsCUhhzDsTprs0kwvZazO+qnR+Th5PIIK7wqel/EpJzYQeH6ajJdbFPtlQF0iBAFKpS8np09HepXvXv3KPeneG2vsCBHuL28tmPZXiDU+m+Tqns2MNaFy9tgBZvZxcHWGiB5Vjombzs++1L2FVMCL/QKe1U4EL0asTpvyk4RSgvObYrk8v+KOm3Qi/OI/M4u2F8t0nS4q656+gUUq4XQl5TDqan2fY13kAjqKUDLGQ3IIwUivk3cWUyjiGF5FT2uS2Zcm2gp4Nr4qk49x1q8GjbnUtyJYC2+oLox8V0RNQMkAkPqq3TOzVFkGPEHeD8= austinc@oddball

### Desired AWS Services

As a developer on the Benefits Claims API within Lighthouse,
My role requires me to connect to BGS, EVSS, and VBMS for local development.
I would need access to the AWS console so I can find out the IP addresses for those services so that I can connect to them.

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
@acovrig this is a request specifically for AWS since SOCKS was granted previously in https://github.com/department-of-veterans-affairs/va.gov-team/issues/36545, correct?

**Comment by acovrig** [comment]
Correct. I need both and have functioning SOCKS at the moment.

**Comment by jbritt1** [comment]
> Correct. I need both and have functioning SOCKS at the moment.

Roger that, thanks for the additional info!

**Comment by jbritt1** [comment]
### For AWS Access

User: Austin Covrig
COR: Courtney Bethea
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by td-usds** [comment]
Regarding 
> I would need access to the AWS console so I can find out the IP addresses for those services so that I can connect to them.

Do those IP addresses change? Is this the only thing that you need to do in the console (i.e. look up IPs?)

**Comment by acovrig** [comment]
At the moment I need the IPs, but may need additional functionality in the future.

**Comment by td-usds** [comment]
@acovrig  are you unblocked (for now) if you have the IPs? Can that be enough to hand you (and then when it would be needed, we can elevate/grant the actual access)? I'm trying to avoid handing out access if that access is not strictly needed.

@jbritt1 or @jsgarmon could you provide @acovrig with the requested IPs via a secure channel since that is what is needed right now?

**Comment by jbritt1** [comment]
> @acovrig are you unblocked (for now) if you have the IPs? Can that be enough to hand you (and then when it would be needed, we can elevate/grant the actual access)? I'm trying to avoid handing out access if that access is not strictly needed.
> 
> @jbritt1 or @jsgarmon could you provide @acovrig with the requested IPs via a secure channel since that is what is needed right now?

We could give IPs, but it isn't a very sustainable model since a lot of our services deploy daily. So IPs given today won't necessarily work tomorrow...

**Comment by td-usds** [comment]
Understood... @jbritt1 is there anything we can do to scope the permissions so that we don't grant what isn't needed?
Access approved

**Comment by jbritt1** [comment]
> Understood... @jbritt1 is there anything we can do to scope the permissions so that we don't grant what isn't needed? Access approved

I almost always fall back to "baseline developer access" for these until the day we can get more granular in our IAM policies.

**Comment by jbritt1** [comment]
First-time login credentials provided via DM in the DSVA Slack workspace at this time.
