### ISSUE TITLE
[BE] Auth Profile - update all va profile certificates

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#36687]
all va profile certificates are expiring in the beginning of march, we need to coordinate with the va profile team and devops to get them all updated

**Comment by Samara-Strauss** [comment]
Update: This is a DevOps issue that Jeremy Britt is working on. [More context from Slack](https://dsva.slack.com/archives/CE4304QPK/p1644334170695339).

I don't believe there is anything else for our team to do. I think the work might actually be [happening here](https://github.com/department-of-veterans-affairs/devops/pull/10688), but not sure. We should make sure we know where and how to track this work before closing this ticket.

**Comment by MarciMcGuireGCIO** [comment]
Confirm that Platform is handling; if so, we can close.

**Comment by MarciMcGuireGCIO** [comment]
This issue has been closed on the Ops end, so I am closing this issue.
