### ISSUE TITLE
Updates to Accredited Rep Prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36686]
## Background
UX and Front-end compared the prototype and staging. In addition to items found for Front-end, we found instances where the design system has changed. We should update the prototype to reflect the latest designs. 

## Considerations
There are 2 sections of the [punch list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/Search-Appoint-PunchList.md): one for font-end to update the code and one for design to update [uxpin](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145482056/simulate/sitemap) 

## Tasks
- [x] update UXPin prototype for each of the "To be updated in UXPin" sections

## Acceptance Criteria
- [x] UXPin has been updated

**Comment by candy-gcio** [comment]
- [uxpin](https://preview.uxpin.com/123ff026cdc405f517913514fd1a0da167d94b54#/pages/146744029)
- [punchlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/Search-Appoint-PunchList.md)
