### ISSUE TITLE
Add Mochawesome as a Reporter for FE Unit Tests

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#36701]
Add Mochawesome as a reporter for FE Unit Tests and upload test results to BigQuery.

Old pr - https://github.com/department-of-veterans-affairs/vets-website/pull/20161 

New pr - https://github.com/department-of-veterans-affairs/vets-website/pull/20163

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/20163

**Comment by holdenhinkle** [comment]
I fixed the issue with Mochawesome not being picked up as a reporter for Unit Tests. I also fixed an issue that was causing the links to the Mochawesome Unit Tests reports having `undefined` for a directory name.

However, the Mochawesome reports for Contract and Unit Tests aren't rendering properly. You just see a blank page:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/510edae3-09b1-42fa-8f07-225dba862ef3)

**Comment by holdenhinkle** [comment]
Okay, i have the reports working again - https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/vets-website-unit-test-reports/mochawesome.html

Now i have to put each report in it's own directory

**Comment by holdenhinkle** [comment]
As of end of day Friday, both PRs are approved and merged.

This is complete.

**Comment by pjhill** [comment]
Thanks for picking this up and polishing off, Holden!
