### ISSUE TITLE
CC Priority #5 (generic functionality)

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#36721]

**Comment by jwowk** [comment]
Waiting on addition of new trigger in consult toolbox (est. late April). 

3/29/23 new requirements requested:
Customize the system to allow sites to have more control over the messaging system. 

- Ability to configure what time messages go out
- Ability to configure how many messages per day go out
- Ability to pause messages
- Ability to trigger sending a letter if an appointment has not been scheduled 14 days after text message sent.

**Comment by jwowk** [comment]
Closing due to duplicate
