### ISSUE TITLE
Follow-up message for cancelled appointments to ask if appointment still needed (if not, close appt request)

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#36738]

**Comment by lindsay-insco** [comment]
Pending OVAC Decision - @shanemelliott

**Comment by shanemelliott** [comment]
I agree, keep the initial options simple:

Confirm or Cancel



and then if Cancelled:



Do you want to reschedule?

Y1: Call me to reschedule

Y2: I will call to reschedule

N: No longer needed

**Comment by shanemelliott** [comment]
[2:09 PM] Elliott, Shane M
 Monday. SD Patch 814 has the new cancellation reasons we need to discuss implantation.

**Comment by shanemelliott** [comment]
[Uploading... VeText Veteran's Choice Proposal (1) (1).pptx]

**Comment by jwowk** [comment]
Duplicate
