### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#36743]
Google Analytics access request:

Name(s): Russell Lyons
Email(s): russell.lyons@va.gov
Team: DGIB
(Optional) Dashboard: N/A

**Comment by laurensimpson14** [comment]
Hi @rlyons89 👋 You'll need to unlink your va.gov email from your personal Gmail and create a full Google account with it. Instructions [here](https://accounts.google.com/SignUp?hl=en).

Click Use my current email address instead

**Comment by laurensimpson14** [comment]
You now have Google Analytics access! You should get a welcome email from GA with instructions on how to get logged in. Please feel free to re-open this ticket if you have any questions!
