### ISSUE TITLE
Create Sign-in Service Diagram

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#36753]
This will be ongoing as we build out the Sign-in Service

Sign-in Service diagrams are currently being hosted in LucidChart: https://lucid.app/documents#/documents?folder_id=285167358

**Comment by bramleyjl** [comment]
[Unified Sign in Service Diagram](https://lucid.app/lucidchart/a4a141e0-b348-4ecf-8f1a-ad03f4fe998f/edit?beaconFlowId=1D46653E626FA998&invitationId=inv_9ba7f56a-c47b-4556-8f02-122c1c19c5ce&page=0_0#)

**Comment by bramleyjl** [comment]
The following Lucidchart documents have been reviewed for accuracy and updated:

* Sign in Service - Web
* Sign in Service - Mobile
* Sign in Service Session_Token Management
* Unified Sign in Service Diagram

Links to all of these documents can be found in the link to the Identity Team Folder further up this ticket.
