### ISSUE TITLE
Fix flaky Form Signature tests

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36766]
## Description
A couple of Forms System tests for the Form Signature component started failing intermittently and have been skipped. We need to fix them so they can run again.

## Details
- [The PR which skipped the tests](https://github.com/department-of-veterans-affairs/vets-website/pull/20146/files)
- [More failing tests that have been skipped](https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/vets-website-unit-test-reports/f6423fe4-60b2-4ac8-a3e4-cffb8058e222.html)

## Acceptance Criteria
- [ ] Tests are fixed and are no longer being skipped.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. f there is still an issue file a new bug.
