### ISSUE TITLE
R&S search input gray background - Search UI consistency

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#36763]
## Issue Description
![r-s-input.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/494572d5-aeda-4e83-a3ff-89325bbf86cf)

[Mobile designs](https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4)

[Desktop designs](https://vsateams.invisionapp.com/console/share/SD10IE31CENR)

[Style Spreadsheet](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit#gid=0)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nicole-leonard** [comment]
@mgleo to create separate tickets for R&S and FaF
