### ISSUE TITLE
[SW-Content]  Update Helpful VA Phone numbers to include "Home Loan number" [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36769]
## Story
As a Veteran, I need to have easy access to home loan numbers, so I can quickly complete my home buying journey.

## TASK

- [x] Include Home Loan numbers on "Helpful VA Phone Numbers" Section.

## Acceptance Criteria
* New Numbers have been added to Help VA phone number area

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Helpful VA phone numbers: http://preview-prod.vfs.va.gov/preview?nodeId=8427

**Comment by RLHecht** [comment]
Thanks, @lunascoop I reviewed and published this. Moving to validate.
