### ISSUE TITLE
KPI Tracking - Implement measurement of Information Architecture health of VA.gov

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3676]
### User Story

As a Veteran using VA.gov, I want to be able to find the tool or service I’m looking for, so that I can efficiently access information about my benefits.

### Problem Statement

How might we as VSP regularly track the information architecture “health” of VA.gov, so that we can set baseline standards and identify problem areas for remediation?  

## VSP Objective (Q1 & Q2 2020)

O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.

## Measuring Success (KRs/KPIs)

TBD

## Details and Notes

IA health of VA.gov is one of [VSP Content & IA Team's KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/content-ia-team-okr-kpis.md). This super epic will allow us to begin tracking it.

### Assumptions and Hypotheses

- We **assume** that in order to provide IA support to VFS teams, we need to have an overall picture of the existing IA of VA.gov and how it is working for users. 
- We **assume** that VFS teams are not going to measure the IA of VA.gov holistically on their own.
- We **hypothesize** that **if** we provide effective IA support to VFS teams, **then** the overall IA health of VA.gov will remain steady or improve.

## Definition of Done
- [ ] Protocol for testing IA health of VA.gov has been created
- [ ] IA health of VA.gov has been tested to obtain baseline metrics

**Comment by meganhkelley** [comment]
Initial ideas from @mnorthuis: A few options for testing site IA —

- Analytics should be tracked for % of unique users that use top nav and % of unique users that use search. This number wouldn't be used on its own, but would be used as a benchmark and trending tool and as supplemental data.  
- To test straight up core IA (as in the organization of content on the site), I would recommend a tree test of the site IA against 10-12 key tasks/content.
- To test effectiveness of key wayfinding elements (top nav, search, hub pages, left nav, breadcrumbs), a First Click test can be done on specific pages to evaluate the perceived usefulness in general wayfinding around the site.  This can focus on key Veteran tasks/content or on general navigating tasks.  
- To test findability in a more wholistic manner, the best approach is a moderated user study on key tasks/content.  This will provide insights on findability of items, usability of navigational components and understandability of links/labels. This can also focus on key Veteran tasks/content or on general navigational tasks.

**Comment by mnorthuis** [comment]
@shiragoodman just an fyi, this is no longer relevant to platform work.
