### ISSUE TITLE
Prevent invalid selector error in review form 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#3677]
## What happened?

On the Higher-Level Review review page, when the contested issue followup is edited, a JS error reporting an invalid selector is seen

![issue-update](https://user-images.githubusercontent.com/136959/69449181-e37d2c00-0d1f-11ea-9bbb-b187b266d5d8.gif)

The HLR form config schema includes a `'view:contestedIssueFollowup'` page.

The [`ReviewCollapsibleChapter.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/1611663a57471556c86b8b6841cf1ead4b107945/src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx#L37-L40) component uses the schema key as an id, but doesn't escape the colon within the `'view:contestedIssueFollowup'` selector.

## Underlying issue

After examining this section of code

```js
focusOnPage(key) {
  const pageDiv = document.querySelector(`#${key}`);
  focusElement(pageDiv);
}
```

I don't think it actually does anything. I added a `console.log(key);` and noticed the key of another section, e.g. `contestedIssues`, appear. There is no element with that ID in the DOM.

After clicking on the "Edit" button, the element and focus disappears, but luckily pressing <kbd>Tab</kbd> jumps to the next focusable form element within the block being edited. So, I'm not sure if we need to explicitly move focus to that first element, or let the browser do the work (if all browsers behave the same).

## Steps to Reproduce

On the HLR review page, edit one of the contested issues (followup questions) & look in the console for the error

## Desired behavior

No JS error; and maybe give focus to the first form element within the block to be edited?

## Acceptance Criteria

- [ ] No JS error
- [ ] Possibly move focus to the first form element within the block being edited

**Comment by jenstrickland** [comment]
go to [https://staging.va.gov/disability-benefits/apply/form-0996-higher-level-review](https://staging.va.gov/disability-benefits/apply/form-0996-higher-level-review) and step through the form... it's mostly already populated with mock data

**Comment by Mottie** [comment]
We'll address the edit button focus problem in another issue/PR.
