### ISSUE TITLE
Previous Education Funding Data appearing on FSR

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#36785]
## What happened?
Veteran has reached out to the DMC to indicate that old education funding data is appearing on their FSR form. 

## Supporting Info
We know that this data  is coming from BGS. 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
@ScottyRJames Can you look into this one?

**Comment by ScottyRJames** [comment]
Payment histories coming from BGS from the service [here](https://github.com/department-of-veterans-affairs/vets-api/blob/26a87caa523bc38c0f8dcbd4e5a05a654e9d805b/app/services/bgs/payment_service.rb#L5).

Sorting to fetch most recent education payment is calculated in the DMC payment service [here](https://github.com/department-of-veterans-affairs/vets-api/blob/26a87caa523bc38c0f8dcbd4e5a05a654e9d805b/lib/debt_management_center/payments_service.rb#L58-L77)

Tested sort with staging user (User #228) with data from mock data repo and sorting calculation worked as intended to use value from most recent education payment.

**Comment by ScottyRJames** [comment]
Forms have been prefilled with payment data without regard for date of the most recent payment. They should only be filled in if payments have been received within the past month. 

Future work [captured](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/37482)
