### ISSUE TITLE
Update link on Recruiting Participants page

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#36784]
### Description
On Platform in the Research and Design section, on the page for Recruiting Participants, under heading "Remote unmoderated studies" the link titled "Learn more about planning unmoderated studies." points to a github document that declares itself not updated and links to https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html

I'd suggest this link be changed from the github link to the relevant Platform page

### Relevant URLs 

Platform page with link to update
https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html#RecruitingParticipants-Remoteunmoderatedstudies

Current link on that page
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/unmoderated-research-guidance.md

Suggested updated link
https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html

**Comment by lianilychee** [comment]
Received, thanks @claytonzook !  Gretchen and I will address this -- either make the change or punt it to someone more appropriate -- when we triage later this week.

**Comment by lianilychee** [comment]
Hello @claytonzook - This page is in the Research & Design space, which technically doesn't have an owner.  BUT!  Since you are new, why don't you come to office hours?  We'll walk you through the update and go-live process so you know how to modify the Platform website in the future

You can check out #vsp-confluence for office hours info

**Comment by claytonzook** [comment]
@lianilychee That works! Unfortunately I have a conflict for Content & IA office hours today. I'll try to join the next one
