### ISSUE TITLE
[Design] Successful/Error upon Editing Submission

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36793]
# Description
When a Veteran submits an update to their contact information, next of kin, and emergency contact, they need feedback on if the update was successfully submitted or not.

# Tasks
- [ ] Create sketch wireframes 

# Acceptance Criteria
- [ ] Communicate to engineering team, so a FE ticket can be written.

**Comment by ytsaoca** [comment]
Success: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/Gm73lmO
Error: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/rbmGdl7
