### ISSUE TITLE
Access for Nadya Primak

### ISSUE THREAD

**Issue by nprimak** [department-of-veterans-affairs/va.gov-team#36805]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Magnum Opus - Paula G. Mendoza

### Your Name

Nadya Primak

### Your Email

nprimak@pluribusdigital.com

### Name of Your Team

MOVE, Software Engineer, Pluribus

### Service(s) You Want Access To

AWS

### Desired AWS Services

Our goal is to populate the 1095B tax form pdf with veteran data so they can eventually go paperless and save money not sending tax forms in the mail

Our proposed architecture [detailed here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/tech/architecture-plan.md)requires us to have an S3 bucket with permissions to receive data in flat file format from the Enrollment System. We then want to run an ingest script to take the flat file data and put it into an Aurora PGSQL database, which we also need to stand up. 

### Access Expiration

ongoing

**Comment by nprimak** [comment]
@jbritt1 Thank you for the clarification, I will be sure to do that!

**Comment by nprimak** [comment]
@jbritt1  Looking at vets-api code it seems like it makes more sense for us to add a table to the existing database rather than creating a new one since that appears to be the convention. Can you confirm? We also aren't opinionated about the S3 bucket in terms of needing to create a new one vs. integrating with an existing one, as long as it can receive flat files from the enrollment system. I guess I'm wondering if we still need to create an ops issue ticket if that is the case, or if there is someone I can ask these questions?

**Comment by jbritt1** [comment]
> @jbritt1 Looking at vets-api code it seems like it makes more sense for us to add a table to the existing database rather than creating a new one since that appears to be the convention. Can you confirm? We also aren't opinionated about the S3 bucket in terms of needing to create a new one vs. integrating with an existing one, as long as it can receive flat files from the enrollment system. I guess I'm wondering if we still need to create an ops issue ticket if that is the case, or if there is someone I can ask these questions?

This would be questions that could likely be answered by the team that owns vets-api. Please reach out with these requests for more info in the #vfs-platform-support channel in the DSVA Slack workspace using the support request workflow described [here](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by nprimak** [comment]
@jbritt1  Can I still get access to AWS? Sorry for the confusion.

**Comment by jbritt1** [comment]
> @jbritt1 Can I still get access to AWS? Sorry for the confusion.

Awaiting approval from the tagged group of aws access approvers: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36805#issuecomment-1035399211

**Comment by td-usds** [comment]
@nprimak, I don't think Paula G Mendoza is still the VOR (or at least, her VA address no longer resolves), can I get an updated VOR Contact which I will need to approve this?

**Comment by ashleycastillo** [comment]
@td-usds Replying on Nadya's behalf - the VOR Contact is Tami (Tamera) Corson

**Comment by tameracorson** [comment]
tamera.corson@va.gov

**Comment by tameracorson** [comment]
@td-usds I'm her contract representative... the COR is Mary O'toole and her assistant is Vilay Senthep.... all of us on Va.gov

**Comment by td-usds** [comment]
AWS _access_ approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user via Slack DM at this time.
