### ISSUE TITLE
Remove dupe accounts from DSVA Slack

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#36819]
# Description
1) Please remove Neha Mohta's duplicate account from DSVA slack - ID: U0236N7BNCU
She has another account under her VA.gov email we want to keep, the first one isn't used anymore.

2) Please remove Steve Haye's duplicate account from DSVA slack: ID: U6KR7KHED  @stevenwhayes
He doesn't have access to this account anymore and is now using a VA.gov-based account.

**Comment by karlbrown-va** [comment]
hi @LEHigley can you confirm this was done? I just checked and I still see both of those accounts as active, but maybe it hasn't synced to my desktop slack as yet?

**Comment by LEHigley** [comment]
done

**Comment by karlbrown-va** [comment]
Thanks!
