### ISSUE TITLE
Define VFS Github teams permission model

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#36817]
Current state: all VFS staff are added to `vets-gov-write` team https://github.com/orgs/department-of-veterans-affairs/teams/vets-gov-write

AC
- [ ] ADR created
- [ ] ADR reviewed
- [ ] Followup tickets
  - [ ] External Docs
  - [ ] Internal Docs

**Comment by td-usds** [comment]
Adding @kjduensing

**Comment by mchelen-gov** [comment]
Deprecated by https://github.com/department-of-veterans-affairs/va.gov-team/issues/43048
