### ISSUE TITLE
[BE][MuleSoft] PROD: Add Mulesoft Config to Ansible Playbooks and AWS Parameter Store

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#36824]
Repeat of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35040 but for prod env when prod.Mulesoft credentials are ready.

parameter names should be:
- `/dsva-vagov/vets-api/prod/form_10_10cg/carma/mulesoft/client_id`
- `/dsva-vagov/vets-api/prod/form_10_10cg/carma/mulesoft/client_secret`

**Comment by SKasimow** [comment]
@RudyOnRails - is this ticket a dupe  for [this]? (https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/35040)

**Comment by RudyOnRails** [comment]
> @RudyOnRails - is this ticket a dupe for [this](https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/35040) one?

No it's...

> Repeat of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35040 but for prod env when prod.Mulesoft credentials are ready.

**Comment by RudyOnRails** [comment]
prod client_id created in AWS Param Store:
<img width="1366" alt="Screen Shot 2022-03-24 at 4 31 28 PM" src="https://user-images.githubusercontent.com/1021154/160013834-ff8a27ce-c9a6-48b7-9f19-22eee151960c.png">

prod client_secret created in AWS Param Store:
<img width="1398" alt="Screen Shot 2022-03-24 at 4 33 51 PM" src="https://user-images.githubusercontent.com/1021154/160014160-a4937b95-1dcc-454b-a1ed-432b5d40611b.png">

Devops PR is at: https://github.com/department-of-veterans-affairs/devops/pull/10970

**Comment by RudyOnRails** [comment]
@SKasimow sorry I never know sprint numbers. Are we in 70? I just closed this and wanted to make sure it had your correct label you need.

**Comment by SKasimow** [comment]
Yup we are in 70 – last and final :0

From: Kevin Musiorski ***@***.***>
Reply-To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Date: Friday, March 25, 2022 at 1:16 PM
To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Cc: "Kasimow, Sharon" ***@***.***>, Mention ***@***.***>
Subject: Re: [department-of-veterans-affairs/va.gov-team] [BE][MuleSoft] PROD: Add Mulesoft Config to Ansible Playbooks and AWS Parameter Store (Issue #36824)


@SKasimow<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSKasimow&data=04%7C01%7Csharon.kasimow%40govcio.com%7C5e7d87018a7d48aa21bb08da0e833b92%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637838254046698911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RKxCpMGSR8TuRhHpiTmNv0pv02NCLfrbvolivF%2BGez8%3D&reserved=0> sorry I never know sprint numbers. Are we in 70? I just closed this and wanted to make sure it had your correct label you need.
