### ISSUE TITLE
Pagination web component: accessibility review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36827]
## Description
**This ticket needs to be complete by Tuesday, February 15th so we have time to resolve any issues before the scheduled Staging Review**

We need to conduct a full accessibility review of the new Pagination web component. The component can be viewed in Storybook here: https://60f9b557105290003b387cd5-plkfbufsna.chromatic.com/?path=/docs/components-va-pagination--default

## Acceptance Criteria
- [ ] Full accessibility review of the pagination component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

**Comment by caw310** [comment]
Here is the link to the development ticket. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/35098

@CourtneyChambers77 the developer on this is @andresriveratoro

**Comment by CourtneyChambers77** [comment]
When completing the Pagination review - Focus moves to buttons within the nav - Passes 
Name	          Describes itself as pagination navigation - Passes
Role	                  Discoverable by screen reader as navigation landmark - Passes 
Group	          n/a
State	          Current page is indicated on focus - Passes https://images.zenhubusercontent.com/133843125/5e43ab25-f2a4-4f17-b8af-daca3db4f915/jaws_va_pagination.mp4

**Comment by CourtneyChambers77** [comment]
https://images.zenhubusercontent.com/133843125/b5c80679-b66f-4283-b597-8b81ee845687/screen_recording_2022_02_15_at_9_03_12_pm.mov

**Comment by CourtneyChambers77** [comment]
https://images.zenhubusercontent.com/133843125/964713a2-c841-4c48-a62f-61b6b71ebd99/nvda_va_pagination.mp4

**Comment by CourtneyChambers77** [comment]
[Uploading... JAWS_va-pagination.mp4]

**Comment by CourtneyChambers77** [comment]
https://images.zenhubusercontent.com/133843125/e00c0315-2640-4492-8920-d6cb585eedf1/jaws_va_pagination.mp4

**Comment by CourtneyChambers77** [comment]
[https://app.zenhub.com/files/133843125/57aa3c86-185c-4363-bfa4-44e7f54f3614/download](https://app.zenhub.com/files/133843125/57aa3c86-185c-4363-bfa4-44e7f54f3614/download)

**Comment by k80bowman** [comment]
This looks great, @CourtneyChambers77 thank you! @andresriveratoro pinging you to let you know the accessibility review passed. 

This ticket is OK to close.
