### ISSUE TITLE
Resolve Dependabot alerts in component-library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36826]
## Description
As of 2.11.22 we have 37 open Dependabot alerts in the component-library repo that need to be resolved.

## Acceptance Criteria
- [ ] All critical, high, and moderate Dependabot alerts have been resolved.
- [ ] Release is created and consumed in vets-website with updates

**Comment by pdavies88** [comment]
Changing to update sass-loader and remove node-sass and replace with dart-sass

**Comment by pdavies88** [comment]
Related Closed PRs: https://github.com/department-of-veterans-affairs/component-library/pull/287
 and https://github.com/department-of-veterans-affairs/component-library/pull/290

**Comment by k80bowman** [comment]
@pdavies88 In vets-website sometimes we use [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) for updating dependencies of dependencies when we can't update the primary dependency for whatever reason. You can see that here: https://github.com/department-of-veterans-affairs/vets-website/blob/b8453ccaddf15b74a9bc6fc5198946875e3b1ec5/package.json#L322-L360

**Comment by pdavies88** [comment]
Most of the issues tie back to us using Storybook v6.3 instead of v6.4 where I would hope these issues would be patched.

**Comment by pdavies88** [comment]
Current vulnerabilities: https://github.com/department-of-veterans-affairs/component-library/security/dependabot
PR: https://github.com/department-of-veterans-affairs/component-library/pull/292/files
Adds in resolutions to fix the issues but the core issues lie in upgrading the packages below:

Dependency: 
- Diff steps to fix upgrade mocha
- Trim steps to fix upgrade @mdx-js/react
- Postcss, minimist, glob-parent, json-schema, and node-sass steps to fix upgrade to webpack5 in storybook
- node-fetch steps to fix upgrade storybook to webpack5 and upgrade puppeteer
