### ISSUE TITLE
PromoBanner web component: accessibility review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36836]
## Description
We need to conduct a full accessibility review of the new PromoBanner web component. The component can be viewed in Storybook here: [insert Chromatic link]

## Acceptance Criteria
- [ ] Full accessibility review of the PromoBanner component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

**Comment by pdavies88** [comment]
@CourtneyChambers77 
Link on Chromatic: 
- https://60f9b557105290003b387cd5-niorwjsrhj.chromatic.com/?path=/docs/components-va-promo-banner--default
- https://60f9b557105290003b387cd5-niorwjsrhj.chromatic.com/iframe.html?id=components-va-promo-banner--default&viewMode=story

**Comment by CourtneyChambers77** [comment]
@pdavies88 I was able to complete the evaluation the banner is looking good, passes.
