### ISSUE TITLE
Table web component: accessibility review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36835]
## Description
We need to conduct a full accessibility review of the new Table web component. The component can be viewed in Storybook here: https://wc-table2--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-table--default

## Acceptance Criteria
- [ ] Full accessibility review of the Table component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

**Comment by bkjohnson** [comment]
Here's a link for the in development `<va-table>` in storybook:

https://wc-table2--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-table--default

**Comment by CourtneyChambers77** [comment]
One question with the table is this a layout tables, this tables are used to position elements in a document. Layout tables do not represent or imply any relationships among content. If a users would like to use JAWS or NVDA they have no relationship within the TH or TD so recalling or location within the tables will be very hard or impossible to get the connection of the table TH with the TD - However if this is going for purely a linear, sequential fashion yes it does the job it not we will need to work this https://images.zenhubusercontent.com/133843125/2d1e02e8-e5e7-405d-9fe7-9f5ec0d5543b/jaws_tables.mp4https://images.zenhubusercontent.com/133843125/76924072-75b3-4e42-b3b6-d2793ad021c2/jaws_tables.mp4

**Comment by bkjohnson** [comment]
This is not a layout table. [Our guidance says](https://design.va.gov/components/tables#when-to-consider-something-else):

> ### [](https://design.va.gov/components/tables#when-to-consider-something-else)When to consider something else
> 
> - Avoid layout tables (tables that contain no data and are used solely for text formatting purposes).

**Comment by CourtneyChambers77** [comment]
@bkjohnson The table is reading well able to Identify the headers and it lets me know where I am within the tahttps://images.zenhubusercontent.com/133843125/ea9c9489-1660-40c2-9fae-d13895a069f5/jaws_tables2.mp4ble please see SC recording:

**Comment by CourtneyChambers77** [comment]
Passing!
