### ISSUE TITLE
Banner web component: accessibility review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36833]
## Description
We need to conduct a full accessibility review of the new Banner web component. The component can be viewed in Storybook here: https://60f9b557105290003b387cd5-wfmvkkodri.chromatic.com/?path=/docs/components-va-banner--default

## Acceptance Criteria
- [ ] Full accessibility review of the banner web component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

**Comment by pdavies88** [comment]
@CourtneyChambers77 Link in Chromatic to test for accessibility: https://60f9b557105290003b387cd5-wfmvkkodri.chromatic.com/?path=/docs/components-va-banner--default

**Comment by CourtneyChambers77** [comment]
Got it -thanks

**Comment by CourtneyChambers77** [comment]
For true accessibility consideration adding banner region for this component will ensure users are able to identify and navigate the component

**Comment by pdavies88** [comment]
@CourtneyChambers77 here is the update I made: https://github.com/department-of-veterans-affairs/component-library/pull/284/commits/c97422a922b65a7b9aad419d135044d2370e9016
Here is the new Chromatic Link: https://60f9b557105290003b387cd5-jpyjrtvpvg.chromatic.com/?path=/docs/components-va-banner--default

**Comment by CourtneyChambers77** [comment]
@pdavies88 I checked again 3 times and I not hearing the banner - ensure the users will under the component being announced to them. This one needs a little more word, banner should be announced to the users. https://images.zenhubusercontent.com/133843125/53711d48-ffaa-4fdb-bd73-82b3da1457ee/jaws_banner.mp4https://images.zenhubusercontent.com/133843125/a2e4d6b0-6bb4-42e4-8392-bffbe193e82c/nvda_banner.mp4

**Comment by pdavies88** [comment]
@CourtneyChambers77 updates per our call have been made
New Chromatic Link: https://60f9b557105290003b387cd5-rjtjlomnqq.chromatic.com/?path=/docs/components-va-banner--default
Commit if you are interested: https://github.com/department-of-veterans-affairs/component-library/pull/284/commits/0501ab776cd822505302f04b72e526a1223586e9

**Comment by pdavies88** [comment]
Current Issue is due to nested Aria roles. The role on the `va-alert` is taking over the role on the wrapping banner component. Therefore the JAWS result is to announce the "alert" role on the `va-alert` instead of the "region" role on the `va-banner`

**Comment by CourtneyChambers77** [comment]
JAWS is able to identify the component, the Banner is now region, passes ![Banner Region PM.png](https://images.zenhubusercontent.com/61b2260296ae8721195bcef1/e012c9b2-12e9-4de4-86ee-4f4982c00cf6)
