### ISSUE TITLE
Claim Status Tool Accessibility Issue

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36832]
## Issue Description
In the Claim Status Tool listing, the lightly colored dots are not in alignment with accessibility standards. 

---
## Tasks
- [ ] Implement solution design from this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36831). 

## Acceptance Criteria
- [ ] Frontend changes implemented.
---

**Comment by devonjhills** [comment]
Closing. Already fixed by https://github.com/department-of-veterans-affairs/vets-website/pull/20211
