### ISSUE TITLE
[SW-Content] Update Iris -gibhp tally sheet in github repository for as of January 2022 [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36846]
## Story
As a 

## Resources
[Migration overview - Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/resources-and-support/iris-gibhp-tally.md)

## Task
- [x] Update iris-gibhp-tally md document in Github with latest numbers

## Acceptance criteria
- [x] New document with updated information/data is uploaded to github repo

**Comment by RLHecht** [comment]
@bethpottsVADEPO I fixed the first column of numbers so they are now what we talked about earlier today. This is ready for your note on the page that we will no longer be updating this.
