### ISSUE TITLE
[02/16/2022] VEText Prescription Tracking

### ISSUE THREAD

**Issue by djfredvs** [department-of-veterans-affairs/va.gov-team#36857]

**Comment by jwowk** [comment]
Live training on 2/16/22

**Comment by djfredvs** [comment]
VEText Prescription Tracking Video completed on 2/11/2022. File is too large to post here. It has been added to Slack teams for review.

**Comment by lindsay-insco** [comment]
@djfredvs - can you please post a link from the VA side to this card?

**Comment by djfredvs** [comment]
I am not sure what link you want me to post for this ticket.
