### ISSUE TITLE
AppointmentRequest object should use an array for option date and times

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#3685]
We currently have something like the following:

    attribute :option_date1, String
    attribute :option_time1, String
    attribute :option_date2, String
    attribute :option_time2, String
    attribute :option_date3, String
    attribute :option_time3, String

Need to investigate a better format for sending these. If VAMF requires it in this format that's ok, but ideally we wouldn't expose future FE developers to this aberration. It ought to be normalized.

**Comment by markgreenburg** [comment]
Going to close this:
1. As a rule of thumb I think we're trying to stay away from transforming VAMF data
2. This will likely change with EAS so probably doesn't make sense to spend cycles on it in the meantime.
