### ISSUE TITLE
[FE] Fix JS Linting rules in FE code 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36859]
## Background 
Evaluate VA.gov code to determine required linting changes needed to comply with new React rules

## Tasks
- Review existing componenets and code to determine changes needed to comply with new React linting rules
- Compile a list of updates needed so PM can use to create new tickets
- Estimate each update given available information

**Comment by adamwhitlock1** [comment]
We have been reviewing JS linting errors and cleaning up as we go. I am going to close this now, as its an ongoing effort and this ticket isn't needed anymore.
