### ISSUE TITLE
[FE] | Bug |10-10ez Refactor Introduction Page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36865]
## What happened?
Problems with page flow and path using the forms system: application page had no content when changed path property on 1st page in form, which is the static page to display authenticated profile information

## Desired behavior
Form will function accordingly with any page path.

**Comment by lzapson** [comment]
Troubleshooted and validated next page functionality for unauthenticated and authenticated flow. Validation is acceptable. 

- Unauthenticated flow uses platform code to get the next available page, including conditional pages. 

- Authenticated flow gets "save in progress" data, which specifies a return URL. The return URL was the URL path prior to the change in path, causing the application to not act accordingly.
