### ISSUE TITLE
AppointmentRequest Patient ID always EDIPI?

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#3686]
Need to discovery to see if the patient_id provided in POST and PUT is always going to be EDIPI. This seems suspicious and might just be how the examples I've seen had it. Right now it's hardcoded to EDIPI but might cause problems.

cc: @jbalboni @markgreenburg

**Comment by markgreenburg** [comment]
@saneshark was anyone able to answer this for you? Believe you may have asked Lynne directly & want to document here if you now know the answer.

**Comment by saneshark** [comment]
No. Marcy or Shawn would be the best to ask.

**Comment by lenaecb** [comment]
@saneshark - is this a show stopper for rollout?

**Comment by saneshark** [comment]
OK, So my understanding on this ticket is that at some point VAMF started favoring ICN over EDIPI and made some changes where *i think* this should never become an issue. I'm going to move it to icebox since we haven't seen any evidence that it is an issue, but I'm hesitant to say it's "closed" either. We just can't seem to get a clear resolution on it, but maybe with some data / metrics / analytics we can finally close it.

**Comment by lenaecb** [comment]
@saneshark - I want to follow back up on this. Doesn't seem to be an issue. I'd like to close unless follow up remains.

**Comment by saneshark** [comment]
yeah, i think we're good to close this one -- hasn't been an issue at all and we get tons of DS Logon sign in users.
