### ISSUE TITLE
Update NPM token for publishing component-library

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36875]
## Description
In order to publish the component-library to NPM we have been using a token from @bkjohnson. We need to update this to a token from VA.

## Details
@bkjohnson has the details on this one. See also #32892.

## Acceptance Criteria
- [ ] NPM token has been updated so that we are now using a VA token to publish component-library

**Comment by bkjohnson** [comment]
Closing this ticket. We were able to get the token in https://github.com/department-of-veterans-affairs/component-library/pull/302, but the [`va_vsp_bot_npm` account](https://www.npmjs.com/~va_vsp_bot_npm) hasn't been able to accept an invitation to join the [`department-of-veterans-affairs` npm org](https://www.npmjs.com/settings/department-of-veterans-affairs/members). This means that the account will not have write access to publish our packages.

![Screenshot of the bot's account page, highlighting that it isn't a member of any npm org](https://user-images.githubusercontent.com/2008881/156213968-2bc0cf7d-159a-4280-9bec-3f15270d6948.png)


Once the bot account has joined the org we can unpause that draft PR and begin publishing using the provided token.
