### ISSUE TITLE
AppointmentRequest Validations

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#3687]
We're currently not doing any validations server side before sending the request to VAMF. We should do this. Need to start doing some discovery to see what some validations are that we think we'd like to add, but the only way I can think of doing this is by trial and error since the API is not documented.

@jbalboni or @narin can you keep a running list of validation issues or Bad Requests that you encounter while integrating with this endpoint and report those here in this ticket please?

**Comment by jbalboni** [comment]
For cancel PUT requests, we know the following are required:

```
{
  "optionDate1":"12/01/2019",
  "optionTime1":"AM",
  "optionDate2":"No Date Selected",
  "optionTime2":"No Time Selected",
  "optionDate3":"No Date Selected",
  "optionTime3":"No Time Selected",
  "status":"Cancelled",
  "appointmentType":"Optometry",
  "visitType":"Office Visit",
  "facility":{
    "name":"CHYSHR-Wheatland VA Mobile Clinic",
    "facilityCode":"983HK",
    "parentSiteCode":"983"
  },
  "phoneNumber":"(555) 555-5555",
  "createdDate":"11/26/2019 09:20:05"
}
```

**Comment by saneshark** [comment]
closing this ticket, feel free to reopen if it's helpful. I think we've just been going the trial and error route for now.
