### ISSUE TITLE
Scheduled CC appointments - Provider Address - (Frontend) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#36871]
## Description
An enhancement is in the works for CC appointments scheduled using HSRM.  Both the HSRM team and the VAOSService team are making updates that will result in the provider address being returned once the appointment is scheduled on the HSRM side.  Vets-api will be forwarding this data to vets-website where it will be displayed on the appointment details page. 

## Acceptance Criteria

Given a booked CC appointment
When that appointment detail is requested on the appointment detail page
Then the provider's address is displayed with the provider information

### Design Assets
TBD 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Once we have some data coming back from HSRM, we will determine what design updates (if needed) on the appointment details page.

**Comment by cferris32** [comment]
https://issues.mobilehealth.va.gov/browse/VAOSR-3048

**Comment by cferris32** [comment]
We will need someone to book the appointment in HSRM in order to test this - talk to Beth Wodzinski or Aarathi Poldass

**Comment by ldelacosta** [comment]
@aarathi-poldass - Please book an appointment through HSRM and see if we have the NPI information. Thanks!

**Comment by aarathi-poldass** [comment]
Re-teste the ticket and it failed validated. The NPI value is not coming through from HSRM when an CC appointmnet is booked using HSRM. I was able to value on the developer tool that when we create the request the NPI value is being transferred to HSRM, but when the appointmnet is booked HSRM is not sending the NPI value back to VAOS.  Please find attached the screenshot and word doc for reference. @ldelacosta can you please assign this ticket back to the developer for further analysis. 



[](url)![Capture.PNG](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/b0a74330-2621-46a9-87af-178f0267fc1a)
[](url)[https://app.zenhub.com/files/133843125/883d284c-6590-46bc-a91c-6366794aa409/download](https://app.zenhub.com/files/133843125/883d284c-6590-46bc-a91c-6366794aa409/download)

**Comment by cferris32** [comment]
Since we are receiving and displaying provider address to the frontend, the AC for this ticket is satisfied so we'll be closing this one out. We may create a new ticket in the future to capture displaying the provider name/phone on the appointment details page.

![Screen Shot 2022-04-19 at 11.12.34 AM.png](https://images.zenhubusercontent.com/5fcfbc1c239ebd98b2acfe6c/d13849ea-7b7a-455c-a76f-f113a519a921)

**Comment by ldelacosta** [comment]
I will discuss this with the Product and Design team and will create a ticket for the new work (if needed). Closing out the ticket.
