### ISSUE TITLE
[Research] Draft Conversation Guide - Veteran Top Tasks

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36878]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will help identify what Veteran top tasks are for use in future user research and product design on VA.gov. 

### Considerations
- The upcoming homepage redesign effort might change if/how top tasks are represented on the home page
- This should be focused on Top Tasks only 
- Possible card sort as an option (initial discussion point)## Issue Description

### Tasks
- [x] Draft conversation guide for moderated research sessions
- [x] Share with someone from UX team, Brian, Dave, Designer, and incorporate their feedback

Link Here:

**Comment by cindymerrill** [comment]
Finished drafting conversation guide, incorporated feedback, and submitted with research plan to launch recruiting.
