### ISSUE TITLE
Introduce a middleware that logs all VAMF requests. Add JTI as a tag.

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#3688]
We need to make sure we are logging the JTI and every request we make into VAMF idempotent or non idempotent.

@kreek or @saneshark will tackle this once we've built out all integrations. This is a high priority before broader production release.

**Comment by lenaecb** [comment]
@saneshark - is this ready to be closed?

**Comment by kreek** [comment]
@saneshark PR for fixing the middleware order bug is here https://github.com/department-of-veterans-affairs/vets-api/pull/3993
