### ISSUE TITLE
[Design] My VA - Copays: Create designs for Copays on My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36902]
## Background
As discussed in **[ticket #33267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33267)**, and based on the discovery completed on **[ticket #36899](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36899)**, we would like to begin exploring designs on adding copay information as part of My VA.  

#### Resources
- [GH Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/Copays)
- [Link to medical copay content page](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)
- [Link to detail page showing list of copays and detailed information] - Must be logged in(https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)

## Tasks
- [ ] Draft designs to consider for adding copays to My VA
- [ ] Share these designs with the team

## Acceptance Criteria
- Create and share designs for adding copays to My VA

**Comment by hdjustice** [comment]
I think we can consider this ticket done.  Agree @aagosto90 ?

**Comment by aagosto90** [comment]
Yes! Closing it now.
