### ISSUE TITLE
[BE] Add specs for StatsD config

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#36903]
## Description
So far, we haven't added rspecs for StatsD configuration/usage. We should add those to prevent issues like #36789.

## Related Documentation

- https://github.com/shopify/statsd-instrument#rspec

## Tasks
- [ ] add rspecs for StatsD

## Acceptance Criteria

- [ ] validated, reviewed and merged to master

**Comment by loripusey** [comment]
closing because too much effort for the value
