### ISSUE TITLE
TUD: Fix bug with id.me-only accounts (not-login.gov accounts) showing the 'get one-time password' button.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#36909]
## Issue Description
Quick ticket:
Fix bug with `id.me`-only accounts (not `login.gov` accounts) showing the `get one-time password` button.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/124

Merged and deployed.

Fixed:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/32e65e4e-e012-42dd-b938-f0552cb98254)

**Comment by pjhill** [comment]
I think the display for TUD accounts that have both ID.me and login.gov identity provider logins needs some work --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/c7609b5a-3507-44df-aee2-c86b77ab984e)
