### ISSUE TITLE
Need ability to upload files on gids dashboard staging

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#36907]
## Description
Need to test out process of uploading Weams csv, currently not able to click on choose file when in upload section

## Background/context 
When I click on "Choose File" here gids/uploads/new/Weam, can't seem to do so, think its permission reltated

## Technical notes
email used was a test user I created, not sure if my email parthur@accenturefederal works, was running into same issue

**Comment by mrblanco1** [comment]
This was resolved. GIDS buttons fail to work in Chrome. They do work in other browsers. This is a Chrome issue.
