### ISSUE TITLE
Search this area of the map not centering on results

### ISSUE THREAD

**Issue by jfinnern** [department-of-veterans-affairs/va.gov-team#36906]
When moving in the search by location map and clicking "Search this area of the map", the map is refreshed and zoomed to the entire United States with the "Search this area of the map" enabled. Manual zoom and re-centering of map is required to view results.

https://user-images.githubusercontent.com/86262877/153950103-1a533ce9-f1ef-4dfa-923f-1cf134dd179d.mov

Steps to reproduce:
Perform a Search by location search, drag the map to another location, and click "Search this area of the map"

Acceptance Criteria:
- [ ] The map should not relocate or adjust zoom level when using "Search this area of the map"

**Comment by dsrr47** [comment]
This no longer appears to be a bug.

**Comment by jfinnern** [comment]
Validated working as expected in staging and production
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2939&group_by=cases:title&group_order=asc
Test case: [Search this area of the map not centering on results.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8127651/Search.this.area.of.the.map.not.centering.on.results.xlsx)

**Comment by mrblanco1** [comment]
/QA and UAT  Passed 2/28/2022 and Flag was removed on 3/01/2022. Closing this ticket
