### ISSUE TITLE
Team members need read/write access to vagov-content, vets-website repos

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#3690]
The following team members need read and write access to the vagov-content, vets-website repos: 
- tammy.hurley1@va.gov; GH: TamGIBill
- Joseph.Preisser@va.gov; GH: josephpreisser
- lucas.tickner@va.gov; GH: lucastickner
- lori.record@va.gov; GH: ??

Thank you!

**Comment by bobrox1973** [comment]
@desireeturner, I need a team to assign them to, can you please provide that for me? Also, do you have Github usernames for the users?

**Comment by bobrox1973** [comment]
All 4 users have been invited to the BAH-526-developers team which has write access to the repos requested. I invited 3 users with their GH username and the last user by email address (no GH username was provided.)
