### ISSUE TITLE
Access for [Chandana Eluru]

### ISSUE THREAD

**Issue by joe-git-developer** [department-of-veterans-affairs/va.gov-team#36905]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Chandana Eluru

### Your Email

chandana.eluru@accenturefederal.com

### Name of Your Team

My Education Benefits, Java Developer, Greenbrier Government Solutions Inc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL/g1rB8e7zH7tVUJ/7iy0JtIf2R6KsMgm/IXURF+NyJ chandanaraj.pols@gmail.com

### Access Expiration

02/20/2022

**Comment by jsgarmon** [comment]
@joe-git-developer : I'm going to need the pull public key for the user, not the fingerprint. This would be the contents of `~/.ssh/id_rsa_vagov.pub` on a Mac/Linux machine if VTK was used for setup.

**Comment by ElijahLynn** [comment]
> @joe-git-developer : I'm going to need the full public key for the user, not the fingerprint. This would be the contents of `~/.ssh/id_rsa_vagov.pub` on a Mac/Linux machine if VTK was used for setup.

The new `ed25519` type keys are that short.

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.

**Comment by joe-git-developer** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAXbMf1oRx3XaFZQ2vNqEhBZzsSTxurqwzr14pfoy9uJAz93zxnPu2EZwyfArKQtu6vj2/HsH51ewrf65cJSDHgFff1a/8BvLzK36tSqRkT/0e6xpfKgZTi+6ouqaKRi+kSwPaEwP8P16uSH6g7Z5GbSVwpgqpWIlQ9VGMrviqGd+IrEMS/wVL7mTz7Dcq1em8wue63azk67N3kjplOjMUTc3xhNVv58nhoTPnu0V0bmzt1d9rPvTCDIfdQ/XMLhcyL5HDc2um6T25muqAAZTVxbP48jtTRnPXvDQWFppIzr9iw2HApBU+clpWX3gl3lfM+dJO9DsthhYe+i/imrQ2FgOmSJP3GKYKTFUZSeLpF+zr9neM0pz/VPhJq7aq9nI92eXPX0Kmq6VDxu6aqCBIoJ3oiP5k6gDbPikDtG6oRgovFQVtv7wAPyAAf29P5DjKwkV1jLmspuXF6gcfs0G/uR2fjC25lwEkxGbY8O6EGXHrqJInpNLjP0IaeeWOAJc= chandana.eluru@AFSMWNUP9M2D5BG

**Comment by joe-git-developer** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAXbMf1oRx3XaFZQ2vNqEhBZzsSTxurqwzr14pfoy9uJAz93zxnPu2EZwyfArKQtu6vj2/HsH51ewrf65cJSDHgFff1a/8BvLzK36tSqRkT/0e6xpfKgZTi+6ouqaKRi+kSwPaEwP8P16uSH6g7Z5GbSVwpgqpWIlQ9VGMrviqGd+IrEMS/wVL7mTz7Dcq1em8wue63azk67N3kjplOjMUTc3xhNVv58nhoTPnu0V0bmzt1d9rPvTCDIfdQ/XMLhcyL5HDc2um6T25muqAAZTVxbP48jtTRnPXvDQWFppIzr9iw2HApBU+clpWX3gl3lfM+dJO9DsthhYe+i/imrQ2FgOmSJP3GKYKTFUZSeLpF+zr9neM0pz/VPhJq7aq9nI92eXPX0Kmq6VDxu6aqCBIoJ3oiP5k6gDbPikDtG6oRgovFQVtv7wAPyAAf29P5DjKwkV1jLmspuXF6gcfs0G/uR2fjC25lwEkxGbY8O6EGXHrqJInpNLjP0IaeeWOAJc= chandana.eluru@AFSMWNUP9M2D5BG

**Comment by joe-git-developer** [comment]
I have posted the new key that was generated by vtk socks setup.

**Comment by joe-git-developer** [comment]
I have posted the new key that was generated by vtk socks setup.

**Comment by jsgarmon** [comment]
Your key has been updated to the RSA key above.
