### ISSUE TITLE
Access for [individual] Steven Brush

### ISSUE THREAD

**Issue by sjbrush** [department-of-veterans-affairs/va.gov-team#3691]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)  --  i believe it's just VAOS
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > None (VA employee)  Supervisor Ellen Crowe if you need it.
- Please provide your name.
   > Steven Brush
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > i am working on the VAOS team with Kam
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRwd4yr6plD6opIARWS9UrdXrWlpTfP5/zH6Zg/siQPEn8WV0vPpWsQrDpR6Gek1TfJkrgbAW/P0aV+iy6E8Hw3l3w7ZO6N6z+GOPO7UdAq9vNqXg7CYYcZGJcfMHRjdXaGtZ33iZdV3y+bj5lItjpwCL/oAaENO8OKiXcHfEITqMMcUVR61Fa37ggadDdax9uD1eoh3Lmjl1pqndsTqg21MNpE9itw7oK14diuZ1pwGzUvzQACPuADEOmeeE07azOb15N/nnm5hgUq9nHPCod8M2p2HeR0Y7v7wjwMRey2v+Ey5KsY1x3sR6mrum5fVMaFhVhClynopL+N8kF6jyL sjbrush@MacBrush.local
```

- [Grant AWS Console access?]
  > YES 
  >  So that I can use the developer tools such as Jenkins, Grafana, and Sentry.

**Comment by sjbrush** [comment]
@department-of-veterans-affairs/vsp-operations  please process.  Thanks.

**Comment by ricetj** [comment]
granted
