### ISSUE TITLE
Domo Dashboard/Dataset Clean Up - Next Steps

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36925]
## Issue Description
Meet with teams that own/utilized Domo datasets/dashboards identified as candidates for removal to ensure there wil be on issues with their elimination.

https://docs.google.com/spreadsheets/d/1Y_PLJaBwkz6vaQSg0I1lFt7PCwws8bDuNeMPUpajlXY/edit#gid=0

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathan-epstein13** [comment]
Looking into row counts for Domo Datasets from this [Dashboard](https://va-gov.domo.com/page/2108534589/kpis/details/565265462)

**Comment by michelle-dooley** [comment]
@jonathan-epstein13 approved to remove/delete [[RETIRED] - KPIs - Facility Locator](https://va-gov.domo.com/page/444997301).  Added note to worksheet.

**Comment by jonathan-epstein13** [comment]
Ran the [GCO Log Export-Domo Costs](https://docs.google.com/document/d/1BrjQuuSv_YkhJqLTZS9n-ZIIVjsKJ-dRjEIRJxjD6VM/edit) and saved the view in google drive. Waiting on next steps.

**Comment by michelle-dooley** [comment]
@jonathan-epstein13 approved to remove/delete [WIP - Logged-In VA Profiles in KPIs - Authenticated Experience - Profile 2.0](https://va-gov.domo.com/page/1223795645) and [Reporting Request - Matt Schae - Authenticated Experience - Profile 2.0](https://va-gov.domo.com/page/1477970759).  Added notes to worksheet.

**Comment by jonathan-epstein13** [comment]
Already deleted what was approved so far, and met on 3/3 with Brian about the `domo_costs (query)` started creating the card to project domo costs data per query per day per user. Will also create a dashboard to include the [Domo Dataset Tracking](https://va-gov.domo.com/page/2108534589/kpis/details/565265462) and the [Domo Dashboard Tracking](https://va-gov.domo.com/page/2108534589/kpis/details/1774897923)

**Comment by michelle-dooley** [comment]
@jonathan-epstein13 please delete https://va-gov.domo.com/page/1872052027 as discussed in office hours.
