### ISSUE TITLE
Add and Update Web Content for the new 'View your disability rating' feature

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3692]
### **High Level User Story**
As a Veteran with a rated disability (or multiple rated disabilities), I need an easy way to see my combined VA rating and know that I can do this online, instead of calling VA or looking for my VA letters.

**Feature**
This feature displays the Veteran's total VA combined rating + list of all of their disabilities that are rated.

### **Content Tasks:**
- [ ] Revise and write new additional copy for the static landing page. (See mockup from apps team).
- [ ]  Incorporate into nav
- [ ]  Update existing disability hub and detail pages as appropriate.
- [ ]  Loop in Peggy Gannon to review close-to-final content and incorporate feedback.
- [ ]  Work with Disability stakeholder to verify content with SMEs and gather relevant feedback. (Paul Shute is our Disability stakeholder lead, but he may need to loop in technical or business SMES to review.)
- [ ] Send Steve Kovacs and Disability stakeholder final preview page before go-live.
- [ ]  Let Steve Kovacs and Disability stakeholder know when updates are published.

_**Note:**_  All information about background on content work that's needed is in this epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3761

**Comment by Karak888** [comment]
@jenniferlee-dsva - This is for content tasks only for view disability rating.  I have associated it with the new epic I created. Will need to be estimated.

**Comment by lwalsh617** [comment]
Here's a first draft of page content. 
[view-disability-ratings-static-page-copy-12-03-19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3923048/view-disability-ratings-static-page-copy-12-03-19.docx)

**Comment by RLHecht** [comment]
@lwalsh617 Here are my copyedits on this. Apologies for taking this before it was ready for me! Let me know if you have any questions. I can review it again once Jen has done her read if it's changed a lot. [https://app.zenhub.com/files/133843125/702d7b5e-a3e7-44c5-af9d-8cfcec3ac1c1/download](https://app.zenhub.com/files/133843125/702d7b5e-a3e7-44c5-af9d-8cfcec3ac1c1/download)

**Comment by jenniferlee-dsva** [comment]
@lwalsh617: 

1/ Uploading doc with comments and edits.  Happy to 1:1 to provide rationale behind feedback. I used track changes on top of Randi's tracked doc. 
[rh-ed-view-disability-rating-static-pg-jl.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3934252/rh-ed-view-disability-rating-static-pg-jl.docx)

2/ Didn't see in the doc updates to the existing About disability rating page. Not sure if you meant to provide that as a separate doc. This would be checkbox #3 in the list above. (Details in the epic, and I can also provide quick walk through on call.)

Please be sure to get @peggygannon's eyes on this before it goes live. She's been working on the tool itself, so it will be good to make sure there are no disconnects between the unauth info page and the tool view.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva 
Hey Jen, quick question on your comment about the more/related info component. Please see attached. Thanks!
[more-related info.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3946358/more-related.info.docx)

**Comment by lwalsh617** [comment]
@Karak888 @jenniferlee-dsva 
Here's a complete first draft of the page itself, as well as edits to the "about disability ratings" page. Jen, the latter are pretty extensive per our phone chat. I'd love to walk you through them if there's a time when we can chat! Thanks! 
[rh-ed-view-disability-rating-static-pag_v2.2_12-13-19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3962761/rh-ed-view-disability-rating-static-pag_v2.2_12-13-19.docx)

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - uploading your copydeck with changes and comments. 
- The VIEW page updates you made look good, and can go live after sharing preview with SMEs (before going live). 
- The ABOUT page has more changes/comments; please take a look and let's tb if anything unclear or you would like to understand rationale better. 

Let me know when the preview is ready to share (post-Peggy sync) and I'll connect you with SME. I think it will be Paul Shute for this content. 

[rh-ed-view-disability-rating-static-pag_v2.2_12-13-19-jl](https://app.zenhub.com/files/133843125/ca4e0279-f385-47f9-a2b0-ee72867767bd/download)

**Comment by lwalsh617** [comment]
@peggygannon Here is the "View" page as a separate document as that's the higher priority. Will post the "About" page separately. Once you have reviewed, we'll get this over to the SME. Thank you! [https://app.zenhub.com/files/133843125/756b4b1b-2ea2-47f0-9104-7a4c3aa6c381/download](https://app.zenhub.com/files/133843125/756b4b1b-2ea2-47f0-9104-7a4c3aa6c381/download)

**Comment by lwalsh617** [comment]
@peggygannon 
@RLHecht 
Here are the updates for the "about disability ratings" page. We needed to add the react widget above the calculator so that changed the intro. Also a few other edits. Jen has reviewed this and I updated this deck based on her feedback. 
Thanks for taking a look
[https://app.zenhub.com/files/133843125/dd9a6d26-34ca-44c2-8a53-a51b88806618/download](https://app.zenhub.com/files/133843125/dd9a6d26-34ca-44c2-8a53-a51b88806618/download)

**Comment by RLHecht** [comment]
@lwalsh617 Here is that page with my edits. I just had one update.
[About disability ratings page-RH edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3973523/About.disability.ratings.page-RH.edit.docx)

**Comment by peggygannon** [comment]
@lwalsh617 

Here is the updated View your VA disability ratings page. Please let me know if you have any questions about my feedback. 

[https://app.zenhub.com/files/133843125/ae6658fd-7cf2-431e-bde8-369e9798e4aa/download](https://app.zenhub.com/files/133843125/ae6658fd-7cf2-431e-bde8-369e9798e4aa/download)

**Comment by lwalsh617** [comment]
Hi @Karak888 
Peggy has reviewed this as well as Jen and Randi, so it's good to be put into a preview, which will then go to an SME (as opposed to sending SME this Word doc). 
Not sure who to alert to get it into a page preview... [https://app.zenhub.com/files/133843125/7579e657-efbe-4ef6-ad0b-8bcb28dc48e6/download](https://app.zenhub.com/files/133843125/7579e657-efbe-4ef6-ad0b-8bcb28dc48e6/download)

**Comment by lwalsh617** [comment]
@RLHecht @Karak888 
This copy deck is now ready to go into Drupal. Goal is to send the SMEs a preview page ASAP. 
Randi, how is your bandwidth? (Apologies--wish I had access already!!)

[https://app.zenhub.com/files/133843125/1bcbf03a-1dda-4e62-ad3f-7e0ee513c796/download](https://app.zenhub.com/files/133843125/1bcbf03a-1dda-4e62-ad3f-7e0ee513c796/download)

**Comment by Karak888** [comment]
@RLHecht can we get @lwalsh617 a preview to send to SMEs before going live? Thanks!

**Comment by RLHecht** [comment]
@Karak888 @lwalsh617 I'm starting work on this today and should hopefully have the preview for you tomorrow.

**Comment by RLHecht** [comment]
@lwalsh617 This page is now built with your content, though it's blocked until the react widget can be put in, which @ncksllvn will be working on. The preview link is preview-prod.vfs.va.gov/preview?nodeId=2408

**Comment by peggygannon** [comment]
@lwalsh617 Here are my content review edits for the "About VA disability ratings" page
Please let me know if you have any questions! 

[https://app.zenhub.com/files/133843125/eb415aa2-5185-446b-9bf7-88619e032ec3/download](https://app.zenhub.com/files/133843125/eb415aa2-5185-446b-9bf7-88619e032ec3/download)

cc @RLHecht

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 LMK if the above VIEW page is ready to send to SME, we can tb who to send preview link to and instructions to include for them. 

If the ABOUT page updates are also ready, we can send that page at the same time (but not required, as we want to ensure the VIEW page is ready for tool launch).

**Comment by jenniferlee-dsva** [comment]
@lwalsh617  - info for sending out SME review for the VIEW page: 
TO: Paul Shute - Disability compensation business stakeholder
CC: Misty Sweet, Sandy Tadeo, Adrienne Hooten, JP DiMartino (VBA digital media), me
.
Please include for them the Drupal preview link, letting them know that:
- the whole page is new and will be the unauthenticated launching point into the authenticated/signed in disability ratings dashboard. 
- the dashboard is migrating an existing eBenefits feature into VA.gov.
- we need the SME to review the page for accuracy by X date. 
- we can schedule a call if needed.

^I think with ppl being out for holidays, we should give the a generous time frame, maybe in that first full week of Jan after new year holiday. I'll forward you an email with Paul et al VA email addresses, since you don't have access yet to VA Outlook gal. 

And if the ABOUT page updates are ready, please include the Heroku preview link to that as well, and a screenshot of the section that's changed exactly, so they know to focus on that part. Thank you so much, Laura!

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @peggygannon @Karak888 -- I made the edits to the about page. Am looping in @RLHecht to get it into Drupal. 
[va-aboutdisabilityratings-rwupdate-v2-010220.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4015876/va-aboutdisabilityratings-rwupdate-v2-010220.docx)

**Comment by RLHecht** [comment]
@lwalsh617 The react widget was added to this Drupal page and all the other changes have been made. Note that the right text for the widget won't appear until after the code freeze. Here's the preview ID to send to the SMEs: preview-prod.vfs.va.gov/preview?nodeId=2408

**Comment by Karak888** [comment]
@lwalsh617 @peggygannon @RLHecht per Randi's last comment, do you know if we are awaiting any copy or changes. I know widget if functional and in Drupal but didn't know if this was incorporated?  Since this is an internal request from Steve Kovacs (we don't need to waste a lot of time on preview, and I can send to PM of that team to have review.  So, guess I am just asking on status of content!

**Comment by jenniferlee-dsva** [comment]
Correction @Karak888 - Because these are benefit hub pages, they always get a preview link sent to SME/stakeholder. 

@lwalsh617 - correct me if I'm wrong: you already received Paul Shute's review and okay, via our phone call, yes? And he emailed written confirmation as requested?

**Comment by Karak888** [comment]
thanks @jenniferlee-dsva for clarification!  @lwalsh617 @RLHecht please let me know if this is all incorporated with widget in Drupal please?  thank you!

**Comment by RLHecht** [comment]
@lwalsh617 This widget is showing correctly on the page in Drupal. Can this be closed? FYSA @Karak888

**Comment by lwalsh617** [comment]
@RLHecht @Karak888 Yep, widget is in, so we can close this. Thanks!

**Comment by RLHecht** [comment]
Closing this issue per @lwalsh617 comment above. @Karak888

**Comment by jenniferlee-dsva** [comment]
@Karak888 (CC @lwalsh617 @RLHecht ) - Are these 2 pages ready to be published and other items on the content checklist? Thinking specifically if you have coordinated and informed Steve Kovacs, whose team is waiting to do UAT testing with the static landing page access points for their tool. 

(See epic for more details and hub landing page link addition). 

**New static landing page**: View...  www.va.gov/disability/view-disability-rating/

**Update existing page:**About VA disability ratings https://www.va.gov/disability/about-disability-ratings/

From [epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3761): 
### **Content Tasks:**
- [ ]  Revise and write new additional copy for the static landing page. See mockup from apps team.
- [ ]  Incorporate into nav
- [ ]  Update existing disability hub and detail pages as appropriate.
- [ ]  Loop in Peggy Gannon to review close-to-final content and incorporate feedback.
- [ ] Work with Disability stakeholder to verify content with SMEs and gather relevant feedback. (Paul Shute is our Disability stakeholder lead, but he may need to loop in technical or business SMES to review.)
- [ ] Send Steve Kovacs and Disability stakeholder final preview page before go-live.
- [ ] Let Steve Kovacs and Disability stakeholder know when updates are published.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva - We received approval from Paul Shute after the call we had on 1/3 with he an Sandy, but I never heard back from Misty or Adrianne, who were on the email with the preview links. Should I email them again or would Paul have followed up with them? 

Posting email from Paul Shute to document his approval of:
1. The new "View Your Disability Ratings" static page: 
preview-prod.vfs.va.gov/preview?nodeId=2408
2. Copy changes to the About Disability Ratings page: 
preview-prod.vfs.va.gov/preview?nodeId=866
![Screen Shot 2020-01-16 at 3 38 29 PM](https://user-images.githubusercontent.com/53535663/72562002-6a5e0900-3878-11ea-8b68-27a27f4eff35.png)
![Screen Shot 2020-01-16 at 3 38 29 PM](https://user-images.githubusercontent.com/53535663/72562154-bdd05700-3878-11ea-8a3f-36a438fd54db.png)

**Comment by jason-gcio** [comment]
We had a look with Randi and it seems like this page's content looks great and we can move forward.  We are going to auth gate the page and test further once its up.  @Karak888 can I simply reach out to when we are ready to push this draft to live?

**Comment by Karak888** [comment]
That's awesome to hear @jason-gcio - I would recommend when you have done your UAT and are ready to push the draft live you can certainly tag me, but more importantly please address everyone involved (I don't actually have the talent I just try and coordinate). And will do a better job of keeping in contact with you on next go around!  So when you are ready make a request here, please include:  @jenniferlee-dsva @ncksllvn @RLHecht  and myself.  Hoping to make this a reality so let us know!

**Comment by jason-gcio** [comment]
Sure, although I think we are actually going to request it be moved from draft to live and gate it as Nick suggested.  I'll tag everyone then though!

**Comment by Karak888** [comment]
@jason-gcio maybe create a separate ticket in that case (also probably what you are saying)- and yes assign to @ncksllvn and tag @jenniferlee-dsva and @RLHecht for awareness.  Thanks!

**Comment by jason-gcio** [comment]
@Karak888 - I started this one and will assign folks once we get some breathing room on our board.  We want to give this a little more attention but are steeped in other tickets at the moment. :)

**Comment by Karak888** [comment]
Moving to close this ticket for Public Websites team as this work has been completed.  Per @jason-gcio note above, ebenefits team has created a new ticket #4961 and will tag above individuals when needed.  FYSA:  @jenniferlee-dsva @peggygannon @ncksllvn @RLHecht
