### ISSUE TITLE
Access for Jeremy Wu

### ISSUE THREAD

**Issue by jhwuz** [department-of-veterans-affairs/va.gov-team#36928]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Jeremy Wu

### Your Email

jeremy.wu@oddball.io

### Name of Your Team

Platform Console Services Team, Software Engineer, Oddball

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLV78UuNrToscuFN4JGrOsixnKAuC6rZAus2mfJjqAaBbV9tsipNxXE4/G+G17J5iNKe3GE/mYD5angI+PH9owP6HKmDJEtU6zl+DRoNYjHSYTvc/BLm541SD3fI9pYVgcy4vNexbeb9J+1Y27aQcmQTwR41Pr4rah2kuyZAJuS81JU4ZXmJ3UEg5MmurZKs0302Hik5iZdCtUdX9pYBhtI7yUVakHzIx8MkabmydNNwpE+DR6qqK3ax4k9gaAOUPapm7GV0oSD74yJJ/WRnMOUNeQ2dxDuJlOpBNVcNW3KZ8u5R8ApbdXeh7Ttia/PtodskZs6OTpC+xqmnQdue4JChMMcoBOBI4gMj4T5g8ZEfeMUe1iyIncdmp8YecYtxEos++JeyKidV39N9btO6K/el+g0x0JmJMXP5r8l1CGZqA9sFzNZkpQ7JTfDucSRZ9/FCnBe10NvyRgioM1vyo9dk9oMAUp9YofUoaklKRsRiw06cUIHs5hnzzCfRQjjjE= work@MacBook-Pro.localdomain

### Desired AWS Services

RDS/ECR read access, read access to Vets-API production servers

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
For AWS access:
approval group: [@department-of-veterans-affairs/operations-aws-approvers](https://github.com/department-of-veterans-affairs/operations-aws-approvers)

@jhwuz: they will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that someone has added your transmittal date to the Sharepoint doc?

**Comment by jsgarmon** [comment]
Someone in the approvers group will reach out if they need more info

**Comment by td-usds** [comment]
@jhwuz can you elaborate on why you'd need _ongoing_ access to production servers. Is this to solve a particular problem or is this a "access so I can use it when I need it"?

**Comment by td-usds** [comment]
@jhwuz can you elaborate on https://github.com/department-of-veterans-affairs/va.gov-team/issues/36928#issuecomment-1043305839 ?

**Comment by td-usds** [comment]
AWS access approved

**Comment by jsgarmon** [comment]
User added, first-time login instructions sent.
