### ISSUE TITLE
Access for Rachal Cassity 

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#36927]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Rachal Cassity

### Your Email

rccassity@gmailcom

### Name of Your Team

Console Services, Backend Engineer, Oddball Inc.

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/zd4ULRP9/VkRCQMtc2N8uJDq5eBNCbedJa+/KaPjixWzdu6Vhbwm7PQ9rrDF0Nn+ZsOOE4eDZNjKn3MAryou1iL+nlXpsquKsTX2WKVrYJLDV8RUOGbzcBWq8K/FBzxAKPhlLbOenZ6XITao1cPVNfL06sIMNC/7fqsPaRQOkcT74Q6vJcrBICa4jmzhpHPYASAfdWnuhJUfD25q8GAicnf5Re6vrmvSP8Tkt1xehMHJACJeEWaEGnsTDpKenDnP/2fioGrQGufOmyPucclvzkIO7jOvpcddHwS5dJXpAbbzwpaERMFxt/MevP2BjxcQ98UIUwnKUrEzjo7q/K+iiJ6+PB7xQ2MUTZP/AqnTlaG8d8kPlnQ/piNlH3Ig/eoOTriILdvxbJO5mHyVwajkTm9k9+7uaFUSCGZ8mc3nUppdjsF0KMJbwNKQS5NgemVBz/zZbnSLV+Q82ZE+t5cU7Rp5JtUaKIcsmUOakmsRpP+NPBmd03KW7/UzbF6Elzs= rachalcassity@rachals-mbp.lan

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
