### ISSUE TITLE
**PLACEHOLDER** | Discovery | Translation Work Estimations

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36930]
Just making some notes for now....

- addition of Chinese, Korean and vietnamese
     - new fonts?

- can we pick one hub to do discovery work on?

-

**Comment by adamwhitlock1** [comment]
I'm not sure if this is the ticket we were looking for updates on, but it is the only one that I see as having questions on not latin languages.

I have updated this document to note some additional criteria for Non-latin languages to consider.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/research/non-latin-character-content-discovery.md

**Comment by SKasimow** [comment]
Closing
