### ISSUE TITLE
ensure that we don't reference personal gists in vets-api

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#3693]
Move the script referenced by to a place owned by department-of-veterans-affairs (likely vets-api)
https://github.com/department-of-veterans-affairs/vets-api/blame/1764473084fd135d723f62546c12594eb16b672d/bin/setup-osx#L127

**Comment by annaswims** [comment]
It appears that the gist no longer works, perhaps due to an OS upgrade.  
and maybe we just need to get rid of pdftk https://github.com/department-of-veterans-affairs/va.gov-team/issues/3032

**Comment by johnpaulashenfelter** [comment]
Closing in favor of #9489
