### ISSUE TITLE
Access for Teagan Stephenson

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36935]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Magnum Opus - Paula G. Mendoza

### Your Name

Teagan Stephenson

### Your Email

teagan.stephenson@bracari.com

### Name of Your Team

1095-B

### Service(s) You Want Access To

AWS

### Desired AWS Services

Our goal is to populate the 1095B tax form pdf with veteran data so they can eventually go paperless and save money not sending tax forms in the mail

Our proposed architecture [detailed here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/tech/architecture-plan.md)requires us to have an S3 bucket with permissions to receive data in flat file format from the Enrollment System. We then want to run an ingest script to take the flat file data and put it into an Aurora PGSQL database, which we also need to stand up.

### Access Expiration

Ongoing

**Comment by JordanSWhite** [comment]
@jsgarmon He's already PIVed, so has completed his EQIP, I believe. @stephte can you confirm?

**Comment by stephte** [comment]
Yeah, I completed the EQIP stuff when getting my PIV

**Comment by td-usds** [comment]
Approved

**Comment by jsgarmon** [comment]
@stephte @JordanSWhite : just so I'm clear on this:
1. you need a single bucket, or are you going to have multiple environments (dev, staging, prod) that will each need a bucket?
2. who/what needs access to this bucket? Is reading-writing going to be done by an application or by humans?
3. It sounds like this bucket will store PII/PHI, correct? Is this something you're ok with individuals being able to access @td-usds?

**Comment by JordanSWhite** [comment]
1. We'll have multiple environments that will each need a bucket. 
2. @stephte needs access to it, and read for humans, read-write for application
3. Yes, we're storing PII.

**Comment by JordanSWhite** [comment]
@jsgarmon @td-usds How should Teagan (@stephte) get access? Is there a notification that goes to his VA email, or his work email?

**Comment by jsgarmon** [comment]
@stephte @JordanSWhite : please put in a a separate [infrastructure request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=devops%2C+needs-grooming%2C+operations&template=ops_issue_template.md&title=New%20infrastructure:) for the bucket. Generally our process for approving and prioritizing new infrastructure is different than for access.

I can give access once there is something to give access to.

**Comment by ashleycastillo** [comment]
@td-usds Thanks for approving @stephte for access! Can you please send us the link where @stephte can login and check to make sure his access works?

**Comment by td-usds** [comment]
Pinged @stephte via slack with the link
