### ISSUE TITLE
BDD - EP 336 Pre-Discharge Excluded Claims not showing in Claim Status Tool

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36931]
## Issue Description
As a Veteran, I would like to be able to see my BDD claims in CST so that I can upload STRs.

From Barry:
MSCs are reporting that SMs still can’t see their claim in the claims status tool on VA.gov when the EP is 336 – Pre-Discharge Excluded (BDD shows up, not 336).  Therefore, they can’t upload any documents to their claim (i.e. STRs) after they submit the claim. 

---
## Tasks
- [ ] Work with Barry to reproduce issue and find out if this is related to our frontend or EVSS. 

## Acceptance Criteria
- [ ] Issue resolved by our team or communicated to EVSS. 
---

**Comment by barrycooper727** [comment]
I received the below email from Michael Harlow of EVSS today, 2/15.

You don’t need to setup a meeting because I found the issue. The 336PDE claim you created is included in the BGS BenefitClaimWebService (see below). However, VA.gov gets its claim data from a different BGS service which does not have the 336PDE claim. EVSS supports the claims API used by VA.gov, so we will ask BGS to update their EBenefitsBnftClaimStatusWebService to include 336PDE.

         <BnftClaimDTO>
            <bnftClaimId>600289306</bnftClaimId>
            <bnftClaimTypeCd>336PDE</bnftClaimTypeCd>
            <bnftClaimTypeLabel>Compensation</bnftClaimTypeLabel>
            <bnftClaimTypeNm>Pre Discharge Excluded</bnftClaimTypeNm>
            <bnftClaimUserDisplay>No</bnftClaimUserDisplay>
            <claimJrsdtnLctnId>123725</claimJrsdtnLctnId>
            <claimRcvdDt>2022-07-01T00:00:00-05:00</claimRcvdDt>
            <claimSuspnsDt>2022-02-25T12:11:53-06:00</claimSuspnsDt>
            <cpClaimEndPrdctTypeCd>336</cpClaimEndPrdctTypeCd>
            <intakeJrsdtnLctnId>123568</intakeJrsdtnLctnId>
            <jrnDt>2022-02-15T12:11:53-06:00</jrnDt>
            <jrnLctnId>317</jrnLctnId>
            <jrnObjId>cd_clm_pkg.do_update</jrnObjId>
            <jrnStatusTypeCd>U</jrnStatusTypeCd>
            <jrnUserId>VBACOCOOPEB</jrnUserId>
            <payeeTypeCd>00</payeeTypeCd>
            <payeeTypeNm>Veteran</payeeTypeNm>
            <pgmTypeCd>CPL</pgmTypeCd>
            <pgmTypeNm>Compensation-Pension Live</pgmTypeNm>
            <preDschrgTypeCd>BDDE</preDschrgTypeCd>
            <ptcpntClmantId>600260867</ptcpntClmantId>
            <ptcpntClmantNm>DONG RALEIGH</ptcpntClmantNm>
            <ptcpntMailAddrsId>15510050</ptcpntMailAddrsId>
            <ptcpntPymtAddrsId>15510051</ptcpntPymtAddrsId>
            <ptcpntVetId>600260867</ptcpntVetId>
            <stationOfJurisdiction>499</stationOfJurisdiction>
            <statusTypeCd>PEND</statusTypeCd>
            <statusTypeNm>Pending</statusTypeNm>
            <submtrApplcnTypeCd>VBMS</submtrApplcnTypeCd>
            <submtrRoleTypeCd>VBA</submtrRoleTypeCd>
            <svcTypeCd>CP</svcTypeCd>
            <tempJrsdtnLctnId>347</tempJrsdtnLctnId>
            <temporaryStationOfJurisdiction>317</temporaryStationOfJurisdiction>
            <termnlDigitNbr>05</termnlDigitNbr>
         </BnftClaimDTO>

**Comment by michelpmcdonald** [comment]
Thanks Barry, I'd like to leave this ticket open at least until we get an answer from BGS to see if they are going to update their EBenefitsBnftClaimStatusWebService to include 336PDE, or leave it open until we can test....

If BGS-EVSS can't come up with a solution to update their existing EBenefitsBnftClaimStatusWebService to include 336PDE, perhaps there is an existing BGS endpoint that vets-api could call directly to fetch 336PDEs.
