### ISSUE TITLE
GHA workflows for vets-api on K8s

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#36945]
We will need GHA workflows for the following:

- [x] To auto push new ECR images after push to k8s branch (This can be manually triggered by the K8s branch currently)
- [x] To auto update the manifests repo with the new image tag (This can be triggered manually by the K8s branch currently)
- [x] To rebase the K8s branch with master after push to master (this is temp, but necessary)

**Comment by jhouse-solvd** [comment]
Attaching to the Vets-API in dev migration for tracking purposes. Thanks for creating this @LindseySaari ☺️

**Comment by jhouse-solvd** [comment]
@LindseySaari - Thanks for doing this. Can you provide the current status?

**Comment by LindseySaari** [comment]
Closing this 👍  @jhouse-solvd
