### ISSUE TITLE
research 10-10CG attachment job error

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#36952]
When submitting a test 10-10CG for staging.mulesoft (when it was pointed at staging.SF) I saw this issue pop up in Sentry: 

http://sentry.vfs.va.gov/organizations/vsp/issues/79299/events/3b572f5249a3435ba5f275c4e2b43b6c/?environment=staging&project=3&statsPeriod=1h

## Questions
- is this related to Mulesoft only? Or does it happen on direct-to-SF submissions to?
- is this new functionality? has the PoA attachment always been around?

**Comment by RudyOnRails** [comment]
My thoughts on this are:

1. The web request is sparking a job even though no attachment exist

**Comment by SKasimow** [comment]
@RudyOnRails this is for backlog/no sprint assigned, correct?
