### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#36958]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- **GitHub username**: @hinzed1127
- **Reason access is required** : I'm an engineer on the Benefit Claims API for Lighthouse. We've been diagnosing some bugs on flows that are pretty reliant on Sidekiq. It would be helpful to have access to the UI to help see more detailed info on the Sidekiq (failures, retries, etc).

**Comment by ericboehs** [comment]
Added.
