### ISSUE TITLE
Console UI: Show recent GHA runs by team

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#36966]
**Console UI Prototype**
Platform Console: In Q1 2022, we are attempting to launch an MVP version of the Console that will enable certain FE VFS developers to log in and manage their FE deployments. 

[**MVP:**
](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2042232849/Requirements+Gathering+MoSCoW+for+MVP+-+Console+UI)
- ATO, TRM, Authentication, Authorization
- Ability to log in (initial UI by CONSOLE UI , functionality and complete UI by ACCESS MANAGEMENT)
- **Deployment mgmt feature RELEASE TOOLS TEAM**
- **Enabled to add a feature via conversation with Console UI engineers RELEASE TOOLS & CONSOLE UI**
- Have the ability to add a feature through  x method (shown in a service blueprint)
- Have documentation on the Console CONSOLE UI? 
- **Have documentation on deployment mgmt feature RELEASE TOOLS TEAM**

**Comment by alexandec** [comment]
This is now implemented in the [prototype React app](https://github.com/department-of-veterans-affairs/console-prototype-release-tools). Our approach is to fetch recent commits and recent runs, correlate them, and filter by team. Here's a screenshot:
![console-ui-commits-runs-example.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/7f4f8cb7-20e6-4bc9-be2f-58ece4c3dca2)
