### ISSUE TITLE
Console UI: Show app-level lighthouse/frontend performance information

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#36965]
**Console UI Prototype**
Platform Console: In Q1 2022, we are attempting to launch an MVP version of the Console that will enable certain FE VFS developers to log in and manage their FE deployments. 

[**MVP:**
](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2042232849/Requirements+Gathering+MoSCoW+for+MVP+-+Console+UI)
- ATO, TRM, Authentication, Authorization
- Ability to log in (initial UI by CONSOLE UI , functionality and complete UI by ACCESS MANAGEMENT)
- **Deployment mgmt feature RELEASE TOOLS TEAM**
- **Enabled to add a feature via conversation with Console UI engineers RELEASE TOOLS & CONSOLE UI**
- Have the ability to add a feature through  x method (shown in a service blueprint)
- Have documentation on the Console CONSOLE UI? 
- **Have documentation on deployment mgmt feature RELEASE TOOLS TEAM**

**Comment by laineymajor** [comment]
@mydesignrocks What is the status of the S3 bucket? Sounds like that is a dependency for this ticket. Thanks!

**Comment by alexandec** [comment]
General outline of the steps we need to complete:

1. Create new S3 bucket with correct CORS settings (Sri completed this already)
2. Modify [lighthouse workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/749fd52d55118c42539f4245b674fe0b1a9dddfc/.github/workflows/daily-lighthouse-scan.yml) to send output to new bucket
3. Modify FE Support Dashboard to reference lighthouse files in new bucket
4. Work on displaying lighthouse results in the console UI prototype by fetching results from the bucket

**Comment by alexandec** [comment]
Progress here: [PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/20322) to send lighthouse output to the new bucket. Will verify functionality, then switch the FE Support Dashboard to use the new bucket.

**Comment by alexandec** [comment]
Created and merged a second PR to update the FE Support Dashboard links to point to the new bucket: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/778

**Comment by alexandec** [comment]
Deploy succeeded. Links in the dashboard are updated. Next step is to work on adding lighthouse results to the console UI prototype

**Comment by alexandec** [comment]
Can display links to the lighthouse results, which are in the bucket, but still working on showing some of the actual results. Still a CORS issue with the bucket. Looking into it.

**Comment by alexandec** [comment]
CORS issue is resolved. Functionality works and [final PR is merged](https://github.com/department-of-veterans-affairs/console-prototype-release-tools/pull/11). Closing this ticket.
