### ISSUE TITLE
va-telephone: Add support for vanity phone numbers

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#36964]
## Issue Description
We would like `va-telephone` to support displaying vanity phone numbers. This is a pattern that is discouraged, but we do make an exception for it at https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers.

Example vanity phone number:
877-222-VETS (8387)

## Acceptance Criteria
- [ ] va-telephone accepts and displays vanity phone numbers

**Comment by pdavies88** [comment]
Per conversation with @bkjohnson we will be taking the approach of adding a new prop named vanity which takes in a string. This will provide us with further flexibility and future proofing if more than 4 digits are needed
`<va-telephone contact="8772228387" vanity="VETS"></va-telephone>`
