### ISSUE TITLE
Vet Center Dashboard Access Discovery (Domo and/or GA)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#36962]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [x] Google Analytics and/or Domo
- [ ] (Platform Teams only) BigQuery

This is a request to determine the best way to provide Vet Center page data to field editors and leadership. The Content dashboard in Domo is one available method for providing Vet Center analytics. 

**Questions**
- How would individuals request access?
- How to roll-out this initiative?
- Training? (I'd love to keep it simple enough for a one-pager)
- How to update/revoke access?
- Access or exported report?

## Field level
- Field editors will want access to their own Vet Center data.
- There are 300 Vet Centers nationally with an average of 2 users per location. 50% are live so user access could be on a rolling basis through the next 2 quarters. 
- Each Vet Center has only two urls: -vet-center/ and -vet-center/locations/
   - Examples - [Reno Vet Center main page](https://www.va.gov/reno-vet-center/) and [Reno Vet Center Locations page](https://www.va.gov/reno-vet-center/locations/) 
- Managing access through personnel changes is a consideration. 
- I'm guessing data at a monthly level will satisfy the need, at least initially. 

### Questions they will want to answer at the field level 
_(these are my assumptions - they've never had web pages before so most don't even know what to ask for)_

**Minimum**
- Are users new or returning?
- How often is my Vet Center main page being viewed?  (-vet-center/)
- How often is my Vet Center locations page being viewed? (-vet-center/locations/)
- Which accordions are most frequently opened within "Prepare for your visit" and "Services"?
**Next level**
- How often do users click on my phone number?
- How often do users click on the Call center number?
- How often do users click on a link in the Spotlight or from an accordion?
- How often do they click on the directions link?

## Leadership level
**We also have leadership personnel who will want higher level aggregated data at a national (or possibly District level).** 
- 3 of the 5 total districts are kicked off. 
- This is a relatively small and stable group of users. 

### Questions they will want to answer at the national/district level (aggregated)
This could be a single report, with option to filter by District
- Are users new or returning?
- Traffic for main pages?  (-vet-center/)
   - Possibly top x Vet Centers
- Traffic for locations pages? (-vet-center/locations/)
   - Possibly top x Vet Centers
- Referral sources (previous page viewed)
- Which accordions are most frequently opened within "Prepare for your visit", "Services" and FAQs?
- How often do users click on Vet Center phone numbers?
- How often do users click on the Call center number?
- How often do users click on a link in the Spotlight or from an accordion?
- How often do they click on the link for directions?

Contact: Michelle Middaugh with the Facilities team (Dave Conlon, VA Product Owner)

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by michelle-dooley** [comment]
Research how we can get Vet Centers access to Domo dashboards, GA reports or some other sources.

**Comment by michelle-dooley** [comment]
@mmiddaugh we believe the best solution to get all the Vet Centers access to Domo is to create one master account they all share.  Do you feel that is a viable solution?

**Comment by mmiddaugh** [comment]
Checking with RCS leadership

How would they request access?

**Comment by michelle-dooley** [comment]
@mmiddaugh good questions!!  

- We can use this ticket as the request for access.
- Good point about someone leaving and still have the shared login credentials.  We we limit their view to read only and so they can only see the one dashboard so not sure how much risk that will be?!?  I will discuss with the team this afternoon in planning.
- And to your previous question they would just filter to their vet center.

**Comment by mmiddaugh** [comment]
Our Vet Centers won't have access to GitHub to request - I could chat with the support team about having the Vet Center staff submit a support request and then they could convey the request to you?

**Comment by michelle-dooley** [comment]
@mmiddaugh they don't need to submit, you can submit on their behalf via this ticket.  We will just need a shared email account for the Domo account login/access.  I imagine one does not exist, could you get one set up for them?

**Comment by mmiddaugh** [comment]
I'll check on that! Thanks

**Comment by mmiddaugh** [comment]
@michelle-dooley  a few more questions/concerns came up with regard to this universal log in plan:
- if two individuals log in at the same time (with the same login) will they be able to see their own filters/Vet Center?
- is there an option for scripted reports which could be generated at some regular interval (monthly, perhaps)?
- Vet Center leadership may be willing to buy additional licenses - is that an option and if so, can you share pricing? (You can send this info directly to Dave Conlon if it is sensitive)

**Comment by michelle-dooley** [comment]
@mmiddaugh - good questions.  The team has a grooming session this afternoon and we will discuss our options here a bit further and get back to you.

**Comment by michelle-dooley** [comment]
@mmiddaugh - see responses below...

- if two individuals log in at the same time (with the same login) will they be able to see their own filters/Vet Center? yes they will only see the filters that they set in their session.

- is there an option for scripted reports which could be generated at some regular interval (monthly, perhaps)?  Domo has limitations when it comes to exporting data, also this would require someone to create reports for every Vet center, no way to automate so unfortunately not an option at this time.

- Vet Center leadership may be willing to buy additional licenses - is that an option and if so, can you share pricing? (You can send this info directly to Dave Conlon if it is sensitive) - its less of a cost issue and more of a maintenance issue.  We manage all the access requests and removal of access when someone leaves and with the number of Vet centers this would be a challenge for our team to manage/maintain.  If shared access does not work could the maintenance off access be by managed by a Vet center resource?

**Comment by mmiddaugh** [comment]
thank you! I'll discuss with Dave and Jessica next week

**Comment by mmiddaugh** [comment]
Hi @michelle-dooley please provide DOMO access for jessica.schiefer@va.gov and barbara.kuhn@va.gov. We'll start with just these two. 
I will plan to do a walk through with them.

**Comment by bsmartin-ep** [comment]
@mmiddaugh -

I re-added Barbara. Email should be incoming.

**Comment by mmiddaugh** [comment]
@bsmartin-ep it looks like Barb was given access to GA rather than to DOMO.

**Comment by bsmartin-ep** [comment]
Sorry @mmiddaugh.  Domo access granted.

**Comment by michelle-dooley** [comment]
@mmiddaugh I'm going to close this ticket, if you have others you want to add later just let us know.  Thanks!!
