### ISSUE TITLE
Access for Naoufal El Hilali

### ISSUE THREAD

**Issue by garfield786** [department-of-veterans-affairs/va.gov-team#36973]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Naoufal El Hilali

### Your Email

naoufal.elhilali@adhocteam.us

### Name of Your Team

Console Services - DevOps Engineer - AdHoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLq4CmpNnc3R8aqaa/3E3jNRlfeaQUHjnSdKQF8J7/kngikzWE6arBUNs19z2l+w0wsQsZlBsMKUjPPI2MlhlBPxS9uyiPjifLhdmg1WaFEFIDJ1AOKLhlnRzKTFNEDWNUJvKoWF842easRAEaxcP8rgTeh9G2p6F6YXi4O6LHxBJbVLb4OBFhvdrX/Wln3XHAxa8fBXu9gaFfyd1K0woeX4ezJah8aIoRkGBlP6flkcLqpuZCj/sz3AVc0RjMbUuasTCFKkd4h/vBTMnHjqv8oCqrGdx1oA5H0j21lI13EPV0Cr2fUNJU2DxgiQs01ewsoB+vZXjJYcWcX1a5EbemQRFDNZECrCbkoP8oihFJVNZBiKjnQ5HIQxzvvpuiNHcLtbtfUbQbglgs1nNaNBrfkfEjc1CxrPmNccBpKORcCKIZkYv1VZRZK+hToAbbw8HBpl7K2k6tkBJ36oHgw7YoqjbfldQ/U39pkzh52i693cM+gL6VSZtWz+1Wg16B3mU= naoufal@adhoc.local

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free to contact me in slack on #vfs-platform-support if you have any trouble.
