### ISSUE TITLE
User Guide Structure

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#36992]
We need to create a user guide for developers creating integrations to make the process easier and cut down on support time as more tools are onboarded to the AMT solution. 
 - Determine overall structure for AMT documentation
 - A "choose your own adventure" format will help us support multiple use cases and allow developers to determine their needs for custom setups with a minimum of active support. 
- this will be a kind of main page or index for the other documentation in this epic. 

**Done When**
spec / outline is present in confluence

**Comment by kjduensing** [comment]
Template link: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2095972353/User+Guide+Template
