### ISSUE TITLE
Set up Permissions for Console

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#36997]
[**Attribute-based access control** (**ABAC**)](https://en.wikipedia.org/wiki/Attribute-based_access_control), also known as **policy-based access control** for [IAM](https://en.wikipedia.org/wiki/Identity_management "Identity management"), defines an access control paradigm whereby access rights are granted to users through the use of policies which combine attributes together. [1](https://en.wikipedia.org/wiki/Attribute-based_access_control#cite_note-1) The policies can use any type of attributes (user attributes, resource attributes, object, environment attributes etc.).

ABAC needs to be set up in Keycloak for Console. To set it up, we need the following information:
 - Resources roles 
 - Auth scopes

Assumptions:
 - Will likely be "ABAC 'light'" - not attributes on users, likely on resource role and scope
 - Will likely not have many other attributes

**Done When**
Can go into keycloak and can see that for the consoleUI client there are the following things set up
- [ ] scopes
- [ ] resources
- [ ] roles
- [ ] policies
- [ ] (overall) permissions

<img src="https://images.zenhubusercontent.com/60099ba779174e24ae511332/17d8de28-8829-45b5-aff0-71871f15d062" alt="drawing" width="350"/>

**Comment by kjduensing** [comment]
Closing this for now. Added roles and roles to team members. @jchapin and team to get back to us with how they want to protect Backstage resources per: https://dsva.slack.com/archives/C02SLSSGSBX/p1648664739739019
