### ISSUE TITLE
Augment Reference Implementation of the AMT Solution include Permissions Check / Demands

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#36999]
A reference implementation will serve as a canonical reference for other teams to follow. It will augment the existing repo. It can serve as protection against scope creep & will make our lives easier in the future as more teams onboard. 

 - "so you want to log in" 
 -  permission check / demand
 - something that can be checked into a repo so others can reference it
 - sign in / sign out and permission checks / demands
 - scoping what people can expect from us

**Done When**
Have code in repo & link to it in user guides and other documentation.
Make sure that it gets shared as frequently as the user guides are shared.

**Comment by kjduensing** [comment]
@calquisola developed the initial reference implementations. For more info, talk to him.

https://github.com/department-of-veterans-affairs/pst-amt-keycloak-node-test-app
https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app

**Comment by ken-non** [comment]
close when pr approved

**Comment by calquisola** [comment]
this is done.  https://github.com/department-of-veterans-affairs/pst-amt-keycloak-node-test-app
