### ISSUE TITLE
Process: Add a New User in Dynamo through Socks Proxy

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37003]
- What is the CI process for onboarding new SSH keys to the socks server when they merge?
 - When there's a new user how to add them in?
 - Could we use same process to add email to dynamo?
 - How does ops team do onboarding? (jenkins process)
 - does this need to be automated off the bat? 
 - can we tie into an automated process that exists, tap into alerts?

**Done When**
A test user can add a socks proxy key & be automatically added to our DB

**Comment by calquisola** [comment]
PR created. https://github.com/department-of-veterans-affairs/devops/pull/10888

**Comment by calquisola** [comment]
PR approved. this is live.
