### ISSUE TITLE
Use my location activating when using Enter key to search

### ISSUE THREAD

**Issue by jfinnern** [department-of-veterans-affairs/va.gov-team#37015]
When performing a Search by location, if the search is repeated by pressing the Enter/Return key, the "Use my location" option is triggered.

https://user-images.githubusercontent.com/86262877/154311598-d0287917-1e05-401c-a420-e10a65ad7a83.mov

Steps to Reproduce:
- Perform a Search by location search
- Click in the search box to return focus (without editing search text) and press Enter

Acceptance Criteria
- [ ] Pressing Enter to execute a search does not trigger "Use my location"

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/2943&group_by=cases:title&group_order=asc
Test case: [Use my location activating when using Enter key to search.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8133343/Use.my.location.activating.when.using.Enter.key.to.search.xlsx)

**Comment by mrblanco1** [comment]
/QA and UAT  Passed 2/28/2022 and Flag was removed on 3/01/2022. Closing this ticket
