### ISSUE TITLE
Iterate designs based on VA-PO and research feedback

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#37019]
- [x] Documented feedback in spreadsheet
- [x] Reviewed internally with team
- [x] Reviewed with VA-PO

**Comment by graceerinhongfrog** [comment]
Feedback spreadsheet: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/Sprint%203%20Design%20Feedback.xlsx
