### ISSUE TITLE
Create product video for contact center review

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#37014]
- [x] Meeting scheduled with contact to create video
- [x] Video produced

**Comment by ashleycastillo** [comment]
How-to: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/product-demo-video-process.md

**Comment by ashleycastillo** [comment]
Jordan asking Jason if we can push the product video to beginning of Sprint 4 so we can have fully final wireframes for the video

**Comment by tameracorson** [comment]
Jason said OK to move back to next sprint with 3 weeks to launch so designs are matured.

**Comment by CarlDickerson** [comment]
@starlow00 @jwoodman5 Product video recorded and uploaded for review. File was too large to attached directly. I have uploaded to Box and provided download link here: https://mostudio.box.com/s/587ia8xt73fz332rrkqid3pmvuls9jfz

**Comment by starlow00** [comment]
@CarlDickerson Thank again for the quick turnaround on this. The video works well! I will share it with the VEO call center.

**Comment by tameracorson** [comment]
Carl, is there a new video?

----

Tamera (Tami) Corson, RN, MBA, CNOR
Senior Analyst II - Remote

SERVE Advisory Group
Office: (240) 437-4754 x125
Direct: (202) 991-8550 ViOP
Email: ***@***.******@***.***>
Pronouns: She|Her|Hers

***@***.***
www.serveadvisory.com<http://www.serveadvisory.com>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by starlow00** [comment]
Postponed sharing with VEO per Carl due to redesign.
