### ISSUE TITLE
Run second round of user testing and synthesize

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#37022]
- [x]  Conducted a minimum of 6 research sessions with Veterans with a more diverse slate of Veterans than in the first round
- [x] Synthesized findings following guidelines from platform team
- [x]  Uploaded notes from all sessions into Github research folder

**Comment by tameracorson** [comment]
Research synthesis in ( GitHub https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/round2-research-report.md )

Research report deck ( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/RESEARCH%202%20Demo%20deck.pdf )

Research spreadsheet ( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/round-2-synthesis%20spreadsheet.xlsx )
