### ISSUE TITLE
Iterate designs based on Business Owner feedback

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#37020]
- [x] Reviewed wireframe with Business Owner
- [x] Feedback tracked in excel
- [x] Feedback prioritized and/or incorporated in wireframes

**Comment by ashleycastillo** [comment]
No business owner feedback in this sprint from review meeting; will send wireframes after next round of editing (for Midpoint Review) to collect feedback for Sprint 4
