### ISSUE TITLE
Privacy and Security review

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#37025]

**Comment by tameracorson** [comment]
Not sure if this applies to this ticket, but there was an existing template but the content read: this type of ticket has been moved to the va.gov-team-sensitive repository.  Go here to open an issue: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new/choose

**Comment by tameracorson** [comment]
Notes from Privacy and security office hours https://dsva.slack.com/archives/C02TUH5U3HS/p1647278738302099?thread_ts=1647278694.222809&cid=C02TUH5U3HS
