### ISSUE TITLE
Unified sign in force IAL2/LOA3 Backend

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#37031]
**As a** security engineer of the VA mobile app
**I want** to ensure we only make authn IAL2/LOA3 calls to the appropriate CSPs
**So that** users of the mobile app are able to fully access all required functionality

# Background:
We have a unified sign in page service offering that allows apps within the VA to use. Each app that uses the unified sign in page have different requirements for their users. In the case of the mobile app and OCC, they only want to allow verified users to access their app in an authenticated state. The frontend is going to send the backend a param in the URL that indicates the authn call should only use verified authns.

If a user attempts to login with an unverified account they will drop onto the eauth error page indicating to them that they cannot signin to the app because they do not have the correct level of assurance. For this iteration our flow ends here. In future iterations we should consider a redirect back to va.gov sign in which helps the user resolve the issue or better explain the problem. That issue coverage is not in scope for this ticket.

Acceptance criteria:
- [ ] User tries to login with idme on mobile unified sign in page with an LOA1 account and is dropped on eauth error page
- [ ] User tries to login with login.gov on mobile unified sign in page with an IAL1 account and is dropped on eauth error page
- [ ] User tries to login with idme on mobile unified sign in page with an LOA3 account and returned to the mobile app in an authenticated state
- [ ] User tries to login with login.gov on mobile unified sign in page with an IAL2 account and is dropped on eauth error page

**Comment by nsoutouras** [comment]
@jscanish and @bosawt test in prod and close if working
