### ISSUE TITLE
Research & Exploration for E2E Coverage Tracking & Standards

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#37035]
## Overview

Two desired features for Automated End-to-End Testing are:

1. Track/Display E2E Code Coverage in QA Dashboards.
2. Explore Enforcing E2E Code Coverage and enforcing a standard.

Review documentation from https://docs.cypress.io/guides/tooling/code-coverage#Introduction and create an assessment on the feasibility & tasks required to complete the above two items.

**Comment by rjohnson2011** [comment]
Reading documentation and taking notes from https://docs.cypress.io/guides/tooling/code-coverage#Introduction

Continuing to go through the remainder of the Cypress docs & videos while taking notes on various methodology of E2E testing. In the process of summarizing in a report.

**Comment by rjohnson2011** [comment]
Running the VA's current implementation of Cypress from `vets-website` on my local environment to inspect the process and compare to the best practices from the Cypress documentation. Ran into a few stumbling blocks when running the Cypress test suite locally, attempting to do so again and generate reporting results.

**Comment by pjhill** [comment]
Hey, if you get stuck for too long trying to get Cypress running locally then please ping myself or one of our teammates who has more experience with Cypress like Darius or Holden who both dug into this work a bit previously.

**Comment by rjohnson2011** [comment]
Generated an `instrumented` application code folder within `vets-website` to test comprehensive e2e coverage locally. Modified the Cypress `plugins` and `support` files as needed to rerun Cypress to generated a complete e2e coverage summary. After making some changes to the `index.js` file and adding some additional packages, in the process of running and creating the coverage summary.

**Comment by rjohnson2011** [comment]
Ran into a series of errors when attempting to run the e2e coverage summary. Removed and rebuilt the yarn dependencies and reran the instrumentation commands. Mostly resolving each of the errors, so not so much blocked as get navigating around various obstacles to run the e2e coverage summary. Currently debugging `Cannot find coverage file vets-website/.nyc_output/out.json  Skipping coverage report`.

**Comment by rjohnson2011** [comment]
Successfully generated the full E2E Coverage summary.
In the process of adding the report to the ticket and documenting steps to generate the report.
Next steps are to evaluate how to replicate generating this summary in a production environment.
```
=============================== Coverage summary ===============================
Statements   : 71.7% ( 27351/38144 )
Branches     : 57.67% ( 13017/22573 )
Functions    : 69.05% ( 7225/10463 )
Lines        : 71.86% ( 26675/37123 )
================================================================================
```
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/ceacfee6-1974-4cf9-ba39-10a123180052)

**Comment by rjohnson2011** [comment]
[https://app.zenhub.com/files/133843125/055446c9-b9a6-46a6-a64b-77bc35048c21/download](https://app.zenhub.com/files/133843125/055446c9-b9a6-46a6-a64b-77bc35048c21/download)
Attached is a zip file of the `coverage` directory, within contains the `lcov-report` and inside is the `index.html` that contains a detailed e2e coverage report.

**Comment by rjohnson2011** [comment]
Closing the local report generated portion of this ticket and moving on to generating the E2E coverage report on production in this ticket - https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/37766****
