### ISSUE TITLE
Access for Rachal Cassity

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#37039]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Rachal Cassity

### Your Email

rccassity@gmail.com

### Name of Your Team

Console Services, Backend Engineer, Oddball Inc.

### Service(s) You Want Access To

AWS

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/zd4ULRP9/VkRCQMtc2N8uJDq5eBNCbedJa+/KaPjixWzdu6Vhbwm7PQ9rrDF0Nn+ZsOOE4eDZNjKn3MAryou1iL+nlXpsquKsTX2WKVrYJLDV8RUOGbzcBWq8K/FBzxAKPhlLbOenZ6XITao1cPVNfL06sIMNC/7fqsPaRQOkcT74Q6vJcrBICa4jmzhpHPYASAfdWnuhJUfD25q8GAicnf5Re6vrmvSP8Tkt1xehMHJACJeEWaEGnsTDpKenDnP/2fioGrQGufOmyPucclvzkIO7jOvpcddHwS5dJXpAbbzwpaERMFxt/MevP2BjxcQ98UIUwnKUrEzjo7q/K+iiJ6+PB7xQ2MUTZP/AqnTlaG8d8kPlnQ/piNlH3Ig/eoOTriILdvxbJO5mHyVwajkTm9k9+7uaFUSCGZ8mc3nUppdjsF0KMJbwNKQS5NgemVBz/zZbnSLV+Q82ZE+t5cU7Rp5JtUaKIcsmUOakmsRpP+NPBmd03KW7/UzbF6Elzs= [rachalcassity@rachals-mbp.lan](mailto:rachalcassity@rachals-mbp.lan)

### Desired AWS Services

RDS/ECR read access, read access to Vets-API production servers

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
@RachalCassity : Is there a reason you need access to the production servers, or do you need the same permissions as other members of the console services team?

approval group: @department-of-veterans-affairs/operations-aws-approvers 

They will require that your EQIP has been completed and transmitted. Can you verify that you have submitted your EQIP, and, if so, that someone has added your transmittal date to the Sharepoint doc?

**Comment by RachalCassity** [comment]
@jsgarmon I just need the same permissions as the other members of the console services team. 

I have submitted my EQIP. I will have to see if my transmittal date was added to the Sharepoint doc.

**Comment by td-usds** [comment]
aws access approved

**Comment by jsgarmon** [comment]
User added, first-time login instructions sent.
