### ISSUE TITLE
[SSL Certificates] Replace fwdproxy/vetsgov-eoas-<env>-cert.pem BEFORE 2022-04-11

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#37059]
## Issue Description
Replace SSL certificates before they expire. (See Jenkins alerts below)

---
## Resources
Recent Jenkins alerts from #devops-deploys:
```
ATTENTION: /ansible/deployment/config/fwdproxy/vetsgov-eoas-dev-cert.pem expires in less than 60 days: 2022-04-11T14:58:12+00:00
ATTENTION: /ansible/deployment/config/fwdproxy/vetsgov-eoas-prod-cert.pem expires in less than 60 days: 2022-04-11T15:06:57+00:00
ATTENTION: /ansible/deployment/config/fwdproxy/vetsgov-eoas-staging-cert.pem expires in less than 60 days: 2022-04-11T15:12:05+00:00
```
Instructions [HERE](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md)

## Tasks
- [x] Remove unused SSL certificates

## Acceptance Criteria
- [x] Unused certificates removed

**Comment by jhouse-solvd** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team-sensitive #417](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/417) via [**ZenHub**](https://www.zenhub.com/)
