### ISSUE TITLE
Add form start link from VSA claims & appeals

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#37052]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md
- Would like to add a button to Request a Notice of Disagreement on [this page](https://staging.va.gov/decision-reviews/board-appeal/). Similar to what we have for the [HLR product](https://staging.va.gov/decision-reviews/higher-level-review/). 
- 
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: 02/25/22
- Estimated staging review date: complete
- Content and IA work needed by: complete

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Ronnie Henry
-	Designer: Kevin Stachura
-	FE engineer: Robin Garrison
-	Product/team Slack channel: vsa-claims-appeals

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by Mottie** [comment]
Note: A work in progress alert currently shows when the feature flag is set to not show the form

https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/

**Comment by mnorthuis** [comment]
As part of the launch of this form, a link should also be added to the left nav. Will the form be live for 100% of users?  If so, then please add the left nav link as well. 

For reference, the IA was documented in [issue #21819](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21819)and documentation can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-board-appeal.md

**Comment by RLHecht** [comment]
@mnorthuis When we add this to the left nav will it be the first child item in the Board Appeals section (above Board hearings with a Veterans Law Judge)?

<img width="275" alt="Screen Shot 2022-02-24 at 10 59 11 AM" src="https://user-images.githubusercontent.com/48728214/155560448-8ad111f7-00dd-46c1-ad0c-1227c01de1cb.png">

**Comment by mnorthuis** [comment]
Yes, that is correct!

**Comment by lunascoop** [comment]
@psanders86 this page is ready for review.
Board Appeals: http://preview-prod.vfs.va.gov/preview?nodeId=3029

**Notes**

- Opted to not include/rework the steps for completing the form (ex: check off option 1...etc.). In reviewing both the online and PDF form, these steps are a standard and required part of the form process. We typically call out parts of the form for special use cases (ex. Unclaimed Veterans for burial allowances, requesting an optional call for a Higher level review). If you do decide to include the steps, here are my write-ups:

  - (For the online form) In Part II of the form, check 1 of 3 Board Appeal options —Direct Review, Evidence Submission, and Board Hearing. Also, list the issue(s) you want to appeal and our decision date for each.

  - For the PDF application) In Step 2 of the application process, list the issue(s) you want to appeal and our decision date for each. In Step 3, select 1 of 3 Board Appeal options —Direct Review, Evidence Submission, and Board Hearing.

- Moved the content for getting a copy of the form by phone or visiting a regional office to the By Mail section. Typically, the **by mail** section includes the link for downloading the PDF and other information. See the [How to apply for Disability claim](https://www.va.gov/disability/how-to-file-claim/) page.

- Made additional tweaks to the page. Specifically, I removed the form link in the Option 2 of the What are my Board Appeal options? section. I also changed the bolded text in the middle of the sentence and just made the sentence a note. It goes against our style guide.

**If you want to review the online form in staging,** use these credentials: vets.gov.user+504@id.me, Password1234!

Online form in staging: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction

Other user accounts for testing: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users

**Comment by SgardnerPMP** [comment]
@RLHecht & @psanders86 please reach out to Ronnie and confirm new launch.  Ready for Patrick's review.

**Comment by SgardnerPMP** [comment]
@psanders86 - Please review -  No date set - Not high priority as we do not have a launch date.  Waiting for customer.

**Comment by bethpottsVADEPO** [comment]
I've reviewed the work the content team did to add the CTA to the new form. There was some reworking of the content needed. I did edit a bit and swapped the green button for an action link. I can't "at" mention Randi Hecht yet because of onboarding/zenhub lag, but I'll post the ticket in our channel for her to take a final edit of this and run through the pre-pub checklist along with the new copyeditor before we publish next week. 

We're waiting to hear what the launch date is. @Mottie any latest word on that?

**Comment by bethpottsVADEPO** [comment]
For copyediting (and Randi, please double check the CTA url next week if you're in drupal by then):

![NOD.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/6a18ba78-b431-486d-ae13-e9fb6cc8ea7a)

**Comment by RLHecht** [comment]
This content is currently in a react widget on the page until the form is available to 100% of users. I created ticket #40656 for taking the react widget out and putting the content and action link straight onto the Drupal page once the form is at 100%. We will also add the form to the left nav in this ticket. Closing this ticket.
