### ISSUE TITLE
Access for Zach Lewis - AWS API Gateway for Lambda SRE Auto Answer

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#37078]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Zachary Lewis

### Your Email

zlewis@clarityinnovates.com

### Name of Your Team

Platform SRE

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need an API Gateway created or permissions to create an API Gateway for my work in progress SRE Auto Answer Lambda arn:aws-us-gov:lambda:us-gov-west-1:008577686731:function:sreautoanswer01. 

API name:  sreautoanswer01
Integrations: sreautoanswer01 (Lambda)

I get error:  User: arn:aws-us-gov:iam::008577686731:user/Zachary.Lewis is not authorized to perform: apigateway:PUT on resource: arn:aws-us-gov:apigateway:us-gov-west-1::/apis

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
Tagging @department-of-veterans-affairs/operations-aws-approvers. Note: this is a request for extension of existing permissions as Zach already has an AWS account.

**Comment by td-usds** [comment]
Elevation approved

**Comment by jbritt1** [comment]
Permissions added as requested/approved.
