### ISSUE TITLE
Update DevOps repo with Decision Review API Settings

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3708]
## User Story or Problem Statement
As a Back-end engineer on the Benefits and Memorials team, I need update the devops repo api settings with Decision Review settings, including a working api-key so I can move forward in establishing a connection for Higher Level Review.

## Goal
_Decision Review API settings updated on DevOps repo_

## Acceptance Criteria
- [ ] DevOps repo API settings have been updated with Decision Review settings

**Comment by SMLuthi** [comment]
@ncksllvn has been looking into this for another lighthouse API integration. He and I have discussed the API key integration at length. We have settled on having one api key for va.gov (do we need a specific one for each environment?) that can access all needed lighthouse APIs. I will follow up with Nick on this work and forward this to @edmangimelli / Philip to make sure the API key(s) we use have the proper access credentials.

**Comment by ncksllvn** [comment]
Thanks @SMLuthi! Adding my team here as well, because we'll need it for https://github.com/department-of-veterans-affairs/va.gov-team/issues/3563

**Comment by SMLuthi** [comment]
This ticket is essentially done. However, the api key work has moved beyond the scope of this ticket. We need the lighthouse team(s?) to create an api key for vets-api (that it can use in dev/staging) that has access to all lighthouse apis. This then needs to be added to credstash and the access for the key needs to be integrated into the devops repo.
