### ISSUE TITLE
Access for Patrick Arthur AWS gi-bill-data-service production

### ISSUE THREAD

**Issue by PJart** [department-of-veterans-affairs/va.gov-team#37086]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Patrick Arthur

### Your Email

patrick.arthur@accenturefederal.com

### Name of Your Team

Accenture Dev - EDU

### Service(s) You Want Access To

AWS

### Desired AWS Services

I need access to gi-bill-data-service production sercvers for 3 days, need to be able to ssh in to run some commands for an update

### Access Expiration

3 days

**Comment by jsgarmon** [comment]
@department-of-veterans-affairs/operations-aws-approvers : user is asking for elevated permissions to access production server for 3 day window.

**Comment by td-usds** [comment]
approved

**Comment by jbritt1** [comment]
90 day reminder set https://dsva.slack.com/archives/CTYQL39FE/p1645194097292459

**Comment by jbritt1** [comment]
90 day reminders set on both sides:
- https://dsva.slack.com/archives/CBU0KDSB1/p1645194037543769?thread_ts=1645125359.430239&cid=CBU0KDSB1
- https://github.com/department-of-veterans-affairs/devops/pull/10766

**Comment by jbritt1** [comment]
SSM-prod access granted at this time, closing
