### ISSUE TITLE
Schemaform issue: Can't make ui elements outside of input fields

### ISSUE THREAD

**Issue by SebVortex** [department-of-veterans-affairs/va.gov-team#37080]
### User story(ies)
As a developer, I need a way to render non input fields in schemaforms so I can fulfill the design requirements of this issue (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23485).

It seems that this SHOULD be possible using schemaforms, but I've been unable to get the desired effect. Even when working with @andresriveratoro from design. (Relevant thread: https://dsva.slack.com/archives/CBU0KDSB1/p1645028528355829)

It was on his recommendation that I open a support ticket.

### Additional details/notes/links
I've been able to render non-standard elements that I need, but only as a child component to a field input. (Example below)
<img width="535" alt="Screen Shot 2022-02-16 at 3 16 10 PM" src="https://user-images.githubusercontent.com/86262790/154530862-2d6da5aa-9e8c-4ac8-b410-ed15f1fa8d0c.png">

### Acceptance criteria
I need to be able to create ui elements that are not a part of the rendering properties of the forms' input fields. 

### Point(s) of contact
Design support: @andresriveratoro 
Team Manager: @mrblanco1

### What type of issue is this? 
- [ ] Possible Bug

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. f there is still an issue file a new bug.
