### ISSUE TITLE
Setting up your local frontend environment Documentation Update

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#37088]
### Description
Content-build steps requires an additional set up step due to code changes in the app. If building content from Drupal, it requires a one-time setup of a `.env` file to supply connection information.

```
cd content-build
cp .env.example .env
```

### Relevant URLs 
https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html
https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html#Settingupyourlocalfrontendenvironment-content-build

### Relations
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7965

**Comment by gmaciolek** [comment]
@timwright12 Can you help with this one? I'm happy to assist with making and publishing the updates.

**Comment by timwright12** [comment]
Yeah, I'll update the docs. Thanks for the ping

**Comment by timwright12** [comment]
I'll keep and eye on the PR for this update to make sure we don't publish docs before it has been merged https://github.com/department-of-veterans-affairs/content-build/pull/972

**Comment by olivereri** [comment]
PR #972 has been merged.

**Comment by timwright12** [comment]
Content has been updated, just waiting on approval to publish

**Comment by timwright12** [comment]
This has been publish https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html#Settingupyourlocalfrontendenvironment-content-build
