### ISSUE TITLE
[repo-migration]: Product Support - Accessibility

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#3709]
- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Run migration script on linked migration plan file (dev)
- [x] PR for va.gov-team (dev)
- [x] PR for vets.gov-team (dev)
- [x] Review/approve PRs
- [x] Merge va.gov-team PR (dev)
- [x] Merge vets.gov-team PR (dev)
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1Bn5Aym9NE6qM0MLMsRVxOk1nmn0jCdJxvbYzV4VWC8k/edit#gid=1543607318

**Comment by billfienberg** [comment]
PRs:
`vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20045
`va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3751

**Comment by thatmattjohnson** [comment]
PRs #3751, #20045 all reviewed/approved

**Comment by billfienberg** [comment]
Merged

**Comment by thatmattjohnson** [comment]
Completed UAT for #3751, #20045; all looks good. Closing this issue.
