### ISSUE TITLE
replace data that was removed from FE payload

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#37098]
10-10EZ Fields that are not meant to be edited (that come from MPI/MVI?), are being removed from the form submission on the FE. In doing so, those fields' data that end up getting submitted in the payload to ES, need to be replaced.

BE can get that data from the user profile. That's what this ticket is for.

**Comment by RudyOnRails** [comment]
@lihanli feel free to add/edit anything here.

**Comment by SKasimow** [comment]
@lihanli assigning to you to pick up once you're done with dashboard :)

**Comment by lihanli** [comment]
@lzapson can you provide an example of the new JSON payload that will be sent to the backend?

**Comment by lzapson** [comment]
The following items have been removed from the payload. 

- Authenticated
   - "veteranFullName"
   - "veteranSocialSecurityNumber"
   - "veteranDateOfBirth"

- Unauthenticated
   - none

**Comment by lzapson** [comment]
Authenticated - with items included, before change 
{
    "isEssentialAcaCoverage": false,
    "vaMedicalFacility": "636A8",
    "wantsInitialVaContact": false,
    "isCoveredByHealthInsurance": false,
    "isEnrolledMedicarePartA": false,
    "isMedicaidEligible": false,
    "discloseFinancialInformation": false,
    "vaCompensationType": "highDisability",
    "lastServiceBranch": "air force",
    "lastEntryDate": "2010-10-17",
    "lastDischargeDate": "2012-09-17",
    "dischargeType": "honorable",
    "sigiIsAmericanIndian": false,
    "isSpanishHispanicLatino": false,
    "hasDemographicNoAnswer": true,
    "maritalStatus": "Never Married",
    "veteranDateOfBirth": "1989-11-11",
    "veteranSocialSecurityNumber": "888887777",
    "cityOfBirth": "Madison",
    "stateOfBirth": "WI",
    "veteranFullName": {
        "first": "Kenneth",
        "middle": "William",
        "last": "Andrews"
    },
    "mothersMaidenName": "James",
    "gender": "M",
    "veteranAddress": {
        "street": "1493 Martin Luther King Rd",
        "street2": "Apt 1",
        "city": "Fulton",
        "postalCode": "97062",
        "country": "USA",
        "state": "NY"
    },
    "veteranHomeAddress": {
        "street": "PSC 808 Box 37",
        "city": "FPO",
        "postalCode": "09618",
        "country": "USA",
        "state": "AE"
    },
    "privacyAgreementAccepted": true,
    "dependents": []
}

**Comment by lzapson** [comment]
Authenticated payload example - without items, after change
{
  "isEssentialAcaCoverage": false,
  "vaMedicalFacility": "636A6",
  "wantsInitialVaContact": false,
  "isCoveredByHealthInsurance": false,
  "isEnrolledMedicarePartA": false,
  "isMedicaidEligible": false,
  "discloseFinancialInformation": false,
  "vaCompensationType": "highDisability",
  "lastServiceBranch": "air force",
  "lastEntryDate": "2010-04-04",
  "lastDischargeDate": "2012-03-17",
  "dischargeType": "general",
  "veteranAddress": {
    "street": "1493 Martin Luther King Rd",
    "street2": "Apt 1",
    "city": "Fulton",
    "postalCode": "97062",
    "country": "USA",
    "state": "NY"
  },
  "sigiIsAmericanIndian": false,
  "isSpanishHispanicLatino": false,
  "hasDemographicNoAnswer": true,
  "maritalStatus": "Never Married",
  "mothersMaidenName": "James",
  "cityOfBirth": "Madison",
  "stateOfBirth": "WI",
  "gender": "M",
  "veteranHomeAddress": {
    "street": "PSC 808 Box 37",
    "city": "FPO",
    "postalCode": "09618",
    "country": "USA",
    "state": "AE"
  },
  "privacyAgreementAccepted": true,
  "dependents": []
}
