### ISSUE TITLE
[Issue Template] Update Environment Access Request (AWS) template

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#37100]
## Description
The Environment Access Request template should give DevOps and Security engineers more useful information about what specific resources the user is requesting, and what specific actions the user needs to perform on those resources.

Addition fields/questions to add:
- Is there a user with permissions you would like to copy?
- Please list which resources (bucket names, parameter store paths, EC2 instance name, etc.) would you like to access.
- What type of access will you need (read, read-write, etc.)
- If you need additional infrastructure, please open a separate Ops request to create that infrastructure.

Remove:
- "Desired AWS services"

## Background/context 
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/31272, but for now could split the template a little more clearly between SOCKS and AWS.
https://dsva.slack.com/archives/CTYQL39FE/p1645111853291729

## Acceptance criteria 

- [x] New "Environment Access Request" is ready for use with the additional fields and questions listed above

**Comment by jhouse-solvd** [comment]
Looks good. Closing.
