### ISSUE TITLE
[repo-migration]: Product Support - QA

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#3710]
- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Run migration script on linked migration plan file (dev)
- [x] PR for va.gov-team (dev)
- [x] PR for vets.gov-team (dev)
- [x] Review/approve PRs
- [x] Merge va.gov-team PR (dev)
- [x] Merge vets.gov-team PR (dev)
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1pKR1bZqxNR0kF8bKATMjvR5CU1iKOxfacQPhQU5nF2Q/edit#gid=1416971709

**Comment by billfienberg** [comment]
PRs:
`va.gov-vfs.teams`: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/46/files
`va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3749
`vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20044

**Comment by thatmattjohnson** [comment]
PRs #46, #3749, #20044 all reviewed/approved

**Comment by billfienberg** [comment]
Merged

**Comment by thatmattjohnson** [comment]
UAT completed for #46, #3749, #20044; all looks good. Closing this issue.
