### ISSUE TITLE
Add kubernetes manifest in yaml to vsp-infra-application-manifests for vets-api-sidekiq-ui

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#37105]
## User Story

_A developer of the standalone sidekiq-ui  application I would like manifest files for my application so that it can be deployed with ArgoCD_

## Expected Behavior

_A Kubernetes manifest and appropriate project directory is added to `vsp-infra-application-manifests`_

## Acceptance Criteria

- [x] _A new directory is created for the project in `vsp-infra-application-manifests`_
- [x] _Relevant Kubernetes manifests are added to this directory._
- [x] _These manifests have been reviewed and approved by the infrastructure team._

**Comment by ewilson-adhoc** [comment]
PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/341

**Comment by oseasmoran73** [comment]
sidekiq-ui issue from docker. see [slack](https://dsva.slack.com/archives/CJYRZK2HH/p1645488451148339) thread for more details
