### ISSUE TITLE
[repo-migration]: Product Support - Engineering - DS

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#3711]
- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Run migration script on linked migration plan file (dev)
- [x] PR for va.gov-team (dev)
- [x] PR for vets.gov-team (dev)
- [x] Review/approve PRs
- [x] Merge va.gov-team PR (dev)
- [x] Merge vets.gov-team PR (dev)
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1Yq3dJGFGr3tuujEpd0jZdP062qspsuvJvxDpj2RJOMQ/edit#gid=1420264421

**Comment by thatmattjohnson** [comment]
#4055: all discrepancies reviewed and resolved in migration plan

**Comment by thatmattjohnson** [comment]
reviewed PRs; #4055 and #4057 have issues re: file counts noted in PRs.  All others look good.

**Comment by billfienberg** [comment]
WIP PRs to migrate files from `vets.gov-team` to `va.gov-team`:
• `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20073
• `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/4055
___
WIP PRs to migrate files from `vets.gov-team` to `va.gov-team-sensitive`:
• `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20074
• `va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/25
___
WIP PRs to migrate files from `va.gov-vfs-teams` to `va.gov-team`:
• `va.gov-vfs-teams`: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/51
• `va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/4057
___
WIP PRs to migrate files from `va.gov-vfs-teams` to `va.gov-team-sensitive`:
• `va.gov-vfs-teams`: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/52
• `va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/26

**Comment by thatmattjohnson** [comment]
reviewed/approved #51, #4055, #4057.

**Comment by billfienberg** [comment]
All PRs have been merged

**Comment by thatmattjohnson** [comment]
UAT findings: va.gov-vfs-teams content migrated to va.gov-team-sensitive as part of this batch has redirect links which are throwing 404s as the destination folder (https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/platform/engineering) doesn't match the URL (https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/va.gov-vfs-teams).  Need to back these out and do them over. All other placements/redirects from this batch look okay.

**Comment by billfienberg** [comment]
PR to redo the migration of the files in the `va.gov-team-sensitive` repo:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/31

**Comment by thatmattjohnson** [comment]
approved 31; UAT uncovered bad links in deprecation messaging for these files, corrected manually. All else looks good. Closing this issue.
