### ISSUE TITLE
[repo-migration]: Product Support - Engineering - JPA

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#3712]
- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Run migration script on linked migration plan file (dev)
- [x] PR for va.gov-team (dev)
- [x] PR for vets.gov-team (dev)
- [x] Review/approve PRs
- [ ] Merge va.gov-team PR (dev)
- [ ] Merge vets.gov-team PR (dev)
- [ ] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1od5Zjr9CCyH9JsBucCdrKy4gikG05u585DPaNa7k2_c/edit#gid=1858382522

**Comment by billfienberg** [comment]
PRs to migrate files from `vets.gov-team` to `va.gov-team`
* https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20046/
* https://github.com/department-of-veterans-affairs/va.gov-team/pull/3813

PRs to migrate files from `vets.gov-team` to `va.gov-team-sensitive`
* https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20047
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/20

PRs to migrate files from `va.gov-vfs-teams` to `va.gov-team`
* https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/47
* https://github.com/department-of-veterans-affairs/va.gov-team/pull/3817

**Comment by thatmattjohnson** [comment]
Conflicts resolved in migration plan document. Please advise whether script needs to be re-run prior to PR reviews.

**Comment by thatmattjohnson** [comment]
Above PRs all reviewed and approved.

**Comment by thatmattjohnson** [comment]
Reviewed/approved #47 per request.

**Comment by thatmattjohnson** [comment]
UAT completed for all PRs, all looks good. Closing this issue.
