### ISSUE TITLE
[repo-migration]: Product Support - Administrative

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#3713]
- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Run migration script on linked migration plan file (dev)
- [x] PR for va.gov-team (dev)
- [x] PR for vets.gov-team (dev)
- [x] Review/approve PRs
- [x] Merge va.gov-team PR (dev)
- [x] Merge vets.gov-team PR (dev)
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration

**Comment by thatmattjohnson** [comment]
link to migration plan: https://docs.google.com/spreadsheets/d/1D47rxF4rDZjw-W4F3EEvrAHCGAGpVrbp6NZB_sVmi1o/edit#gid=2131398488

Note that in addition to the migration plan there is a separate set of files which per Andrea have already been migrated and only require deprecation messaging.  She asked if it would be possible for us to run just the deprecation script against these.

**Comment by billfienberg** [comment]
PRs for files migrated from `vets.gov-team` to `va.gov-team`
`vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20056/
`va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3889

PRs for files migrated from `vets.gov-team` to `va.gov-team-sensitive`
`vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20057/
`va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/22

PRs for files migrated from `va.gov-vfs-teams` to `va.gov-team`
`va.gov-vfs-teams`: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/49
`va.gov-team`: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3896

**Comment by thatmattjohnson** [comment]
all PRs reviewed/approved, ready for merge

**Comment by billfienberg** [comment]
All PRs have been merged

**Comment by thatmattjohnson** [comment]
UAT completed for all PRs, all looks good. Closing this issue.
