### ISSUE TITLE
review indexes in GIDS

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#3717]
in relation to 11/21 outage.
I know that the indexes are not properly reflected in schema.rb

**Comment by wyattwalter** [comment]
@annaswims I'm not sure how you want to assign out this work, but I believe that a big one that we need to look into is on the institution search API. Looks like that's the landing page you get to when you click "Search for Schools" whether or not you use an autocompleted response. It's consistently ~300ms on the backend and was one of the biggest spikes. During the incident, latency of that rose significantly more than the others.
