### ISSUE TITLE
Access token schema

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37190]
## Issue Description
Description of planned access token schema

## Acceptance Criteria
- [ ] Access token schema documented in Github

**Comment by bosawt** [comment]
This is completed by other stories

**Comment by bosawt** [comment]
Fields are:
      :session_handle,
      :user_uuid,
      :refresh_token_hash,
      :anti_csrf_token,
      :last_regeneration_time,
      :parent_refresh_token_hash,
      :version,
      :expiration_time,
      :created_time

**Comment by bosawt** [comment]
And those fields are wrapped up in a JWT with these fields:
iss
aud
client_id
jti
sub
exp
iat
session_handle
refresh_token_hash
parent_refresh_token_hash
anti_csrf_token
last_regeneration_time
version
