### ISSUE TITLE
Set non-functional requirements of token theft detection

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37205]
# Description
This ticket covers auditing usage that may imply token theft, such as an expired token being used after a new one (both refresh and access)

# User Story

# Acceptance Criteria
- [ ] Criteria for potential token theft defined
- [ ] FE/BE Team provided details 

# Technical Description

**Comment by joeniquette** [comment]
this article discusses some of the threats we are concerned with and provides examples of how to mitigate them: https://owasp.org/www-community/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies#validate-device-cookie

**Comment by joeniquette** [comment]
## Non-functional requirements for token theft:

1. After issuing a new token with an existing token, an attempt is made to use the original token. This would indicate that either the attacker has a new token or the original user has a new token but the other party still has the old.
    a. All sessions related to the original refresh token MUST be invalidated.
        i. This will force the user to login again.
2. Change in browser/device fingerprint. This method would detect if an issued token was then being used by a different device or browser, indicating another person has intercepted the auth token.
    a. A device cookie SHOULD be issued upon successful authentication.
    b. If the device cookie is missing when a refresh token is used:
        i. All sessions related to the original refresh token SHOULD be invalidated.
            a. This will force the user to login again.
    c. If the device cookie is invalid when a refresh token is used:
        i. All sessions related to the original refresh token SHOULD be invalidated.
            a. This will force the user to login again.
3. Change in IP address. This method detects if the original IP address of the token has changed, often indicating another person has intercepted the auth token.
    a. Information SHOULD be collected to log the difference in IP address.
    b. No further action is required after logging the event.

**Comment by nsoutouras** [comment]
@nsoutouras make tickets for above.

**Comment by joeniquette** [comment]
@nsoutouras sorry for the poor formatting above, markdown converter from google docs wasnt as great as I'd hoped. But the list is complete. We should have a ticket per outer subject (7 in total).

**Comment by nsoutouras** [comment]
@joeniquette all tickets created in this epic: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/41894
