### ISSUE TITLE
Usage Audits for tracking potential token theft

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37206]
# Description
This ticket covers auditing usage that may imply token theft, such as an expired token being used after a new one (both refresh and access)

# User Story

# Acceptance Criteria
- [ ] Criteria for potential token theft defined
- [ ] FE/BE Team provided details 

# Technical Description

**Comment by joeniquette** [comment]
completed and added to DD dashboard
