### ISSUE TITLE
TUD: Onboard Authenticated Experience team to TUD

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#37220]
## Issue Description
Onboard the Authenticated Experience team to TUD.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Relevant threads:
- https://dsva.slack.com/archives/C909ZG2BB/p1644963107886989
- https://dsva.slack.com/archives/C01CHAY3ULR/p1645032039531059

Heather provided the following list of test users her teams uses:

MVI Staging users list
vets.gov.user+1@gmail.com
vets.gov.user+11@gmail.com
vets.gov.user+21@gmail.com
vets.gov.user+36@gmail.com
vets.gov.user+39@gmail.com
vets.gov.user+41@gmail.com
vets.gov.user+80@gmail.com
vets.gov.user+81@gmail.com

Login.gov Staging User list
vets.gov.user+228@gmail.com
vets.gov.user+201@gmail.com
vets.gov.user+204@gmail.com
vets.gov.user+378@gmail.com

All but 4 of those years are already loaded into TUD.

Ryan Beckwith, Peter and I compiled the user attributes for the 4 users. I added the 4 new users to the `test_users.csv` file and reset the test users on staging. The 4 users are now in TUD.

PR to add the 4 new users - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/412

**Comment by holdenhinkle** [comment]
The team was onboarded yesterday, Wednesday, 3/2/2022.

**Comment by pjhill** [comment]
Indeed, this is done!
