### ISSUE TITLE
Adding Kenneth Harbin to DSVA Slack

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#37288]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)
Kenneth Harbin[kenneth.harbin2@va.gov] is a part of the EVSS team, not on the Platform.  Much of the work our team manages is reliant on constant communication with this team.  Please provide each member access.

Are you requesting to add an individual as a:

- Single guest

- What channel(s) do they need to be added to? va-tech-evss-collab

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

N/A

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@Kimberley2019 the channel is not coming up for me as an option

**Comment by Kimberley2019** [comment]
@LEHigley below is the link for the channel

https://join.slack.com/share/enQtMzEyODY4NjgyMjg2Ni02MGJiNDA1M2FjYzk3OTJhYTBlYzg0YjBlMTUyMTM0MjhmZTk4YzU5ODY3YTZmYTVkMjgzZTRmNDQzNmI0Yjhj

**Comment by LEHigley** [comment]
@Kimberley2019 i need to be added/invited it looks like before i can add people

**Comment by Kimberley2019** [comment]
@LEHigley just added you to the channel

**Comment by Kimberley2019** [comment]
Thanks
