### ISSUE TITLE
Centralized Logging with Loki and Grafana

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#37285]
[Centralized Logging with Loki and Grafana](https://depo-platform-documentation.scrollhelp.site/developer-docs/Centralized-Logging-with-Loki-and-Grafana.619119010.html)

**Comment by considerable** [comment]
Hello @lianilychee @ewilson-adhoc - i tried to make tkt for Loki in Grafana, but mine version did not save.
Yet I found this tkt in the icebox, so here is my comment:
At Platform-PST-IET we created this dashboard that allows you to do quick search per EKS namespace, or pod,  or through all the Loki data:

https://grafana.vfs.va.gov/d/vets-api-file-upload-dashboard-1/loki-dashboard-quick-search?orgId=1

The above dashboard is based on this blogpost:

https://grafana.com/blog/2020/04/08/loki-quick-tip-how-to-create-a-grafana-dashboard-for-searching-logs-using-loki-and-prometheus/

My apologies for hijacking the tkt.

**Comment by ewilson-adhoc** [comment]
This is the other ticket -- unclear why this isn't showing up
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/40201

**Comment by ewilson-adhoc** [comment]
@lianilychee giving you this ticket back

**Comment by lianilychee** [comment]
thanks!  made this ticket for Platform Content to do some internal tracking.  I'll go ahead and close
