### ISSUE TITLE
Iterate on "one pager" for devops presentation

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#3729]
## Background:

DevOps in practice showcasing VA.gov Dec 11th. Def need to have something adjacent to this by then for that meeting. 

## Goal:
Update the "one pager" deck to be well positioned for this particular use case. Less about attracting teams, and more about “this is how we built VA.gov and how great we are.” How Platform enables DevOps culture.

Research readout: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/roes/research/usage-study/roe-research-presentation.pdf

## Definition of done:

Leah
- [ ] set up pre-meeting (prior to Dec 11 w/enough time to update also) w/Charles to get feedback and alignment
- [ ] Find out from Charles: what else will be different from peoples’ current experiences/expectations of building products at VA? What things do they LIKE about their current options/processes that this will take away?
- [ ] What is Platform (or DEPO, or Charles's?) goal in this meeting? That should inform our closing slide.

Kevin
- [ ] Ask a few DEPO leads if they had to write 2 short paragraphs describing what Platform is and why it exists, what would they write? Use that to craft / inform / update the first 2 slides of the deck

Patrick / Leah 
- [ ] Modular callouts for value adds that will resonate w/target audience. What are their biggest problem statements? What gaps / difficulties might they be excited to learn Platform could fulfill?
- [ ] Populate "sample features" slide with good "categories" and list the features that enable those things
- [ ] Audit deck and adjust language language/terminology to map better to the directives of DevOps and HCD

Rachael
- [ ] Create "master feature list" slide w/categories that resonate. Start w/categorizing by practice area, might change that though.
- [ ] Add content that's transparent about the give and take of working w/us
- [ ] Determine what to include in leave behind deck appendix vs what to delete in the versions of this deck we create for various stakeholders bc they're template slides just for us. 
- [ ] Update overall design and formatting to be accessible (bump up contrast (greys)) and readable from far away.
- [ ] Iterate on workflow visuals per research
- [ ] Fill in the example slides w/a real devops/incident scenario where we've helped a VFS team, and screenshots/visuals (in line with the workflow visual we put in) that illustrate this. Can there be a story arc? Here was a big challenge that might be familiar to any team building tech in govt. Here's a real story about how Platform solved it / made that experience better or easier in our work w/a VA Product Team.

Andrew
- [ ] [Describe user flow, features, and responsibility splits (VA Product team vs Platform) for an example relevant to DevOps](https://docs.google.com/presentation/d/1q2QZIJXH6nSAzdVlANUd1Mt1KVFFiL1uRZgWSsXucJg/edit#slide=id.g622b241dfc_1_1)

General
- [ ] Hand off to Leah and Patrick for DevOps meeting / presentation

**Comment by rroueche** [comment]
@batemapf could you share the notes from your Charles convo here?

**Comment by batemapf** [comment]
here you go! https://docs.google.com/document/d/1EnLb8mgy7VvXm68Qji3lBJCdXt3o-oPvTUJ_Td-mkBs/edit?usp=sharing

**Comment by rroueche** [comment]
We pivoted and Patrick did his own preso due to the nature of the meeting and the audience. Copying the edit details into https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3243
