### ISSUE TITLE
Update prototype for second round of testing

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#37307]
- [x] Prototype created (e.g., linking together the wireframes we created in Sprint 2) to be used in second round of testing to enable discussion
- [x] Reviewed across internal team

**Comment by graceerinhongfrog** [comment]
Completed prototype: [https://www.sketch.com/s/1f2a2fbd-8d48-47c6-8e95-b26d5259a211/a/PGeRmgL/play]
