### ISSUE TITLE
[02/25/22] Discovery: VEText/Teams Bot

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#37308]
## Description
Research on how to build and apply Teams chat bot to to VEText channels to redirect users who enter text/ask questions to the VSA for submission and logging.

---

## Acceptance Criteria

Example: 
- [x] Application and implementation research
- [x] Build bot
- [x] Implement bot to channels
- [x] Approved by Justin/Paras/Allison/Lindsay
---

**Comment by chancetheoriginal** [comment]
Working task from Power Automate angle.

**Comment by chancetheoriginal** [comment]
Bot Minimum Viable Product built, currently replies to user as myself within 3-5minute window per the Power Automate API response. Bot-related replies are hitting a bad gateway pointing to potential security/permissions config issues. Future update will address this as acceptable.

**Comment by lindsay-insco** [comment]
Up and running
