### ISSUE TITLE
[02/22/22] Pharmacy Training - Martinsburg, WV

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#37306]
## Description
Train Martinsburg, WV on Prescription Tracking Program
---

## Acceptance Criteria
Acceptance criteria are pre-defined requirements that must be met to mark a task as complete. What needs to be done to mark this task as complete?

- [x] Training email sent
- [x] Training Date Established - 02/22/22 1:00PM ET
- [ ] Get reports-level access list to @chancetheoriginal
- [ ] Conduct Training
- [ ] Send follow-up resource email 
---

**Comment by djfredvs** [comment]
Training completed
