### ISSUE TITLE
[DISCOVERY] vets-api 0 downtime rollout strategy

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#37304]
## Tasks

We will also want to research a rollout strategy. It looks like you can specify a min number of containers available during the rollout process to allow for a rolling deploy with 0 downtime

- [ ] Stories are created to accomplish whatever we discover.

**Comment by LindseySaari** [comment]
Note to self: Scaling page 123 in O'Reilly K8s up and running

**Comment by LindseySaari** [comment]
https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

**Comment by npeterson54** [comment]
We have this figured out.
