### ISSUE TITLE
Investigate Potential Flakiness with COVID-19 Vaccine Tool Cypress Test

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#37349]
# Description
There may be a race condition with the `cy.focus` command as seen in this [build](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/1877380977/attempts/1).

**Comment by JoeTice** [comment]
This ticket is out of date and the build logs are no longer available to check it - closing
