### ISSUE TITLE
OAuth scaffolding set up in services directory

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37350]
# Description
This ticket is to help determine how we want all the CSP connections to work with our new Sign-in Service.

# Acceptance Criteria

# Technical Description

**Comment by bramleyjl** [comment]
The [initial scaffolding PR](https://github.com/department-of-veterans-affairs/vets-api/pull/9238) displays the new Sign in Service architecture. In summary:
* incoming requests & callbacks are routed to the V2 Sessions controller
* the sessions controller uses the included `type` param to identify the CSP and call the appropriate authentication service to provide detailed information and handle connections with the CSP
* authentication services live in `lib/auth`, and include both general services in the directory root as well as CSP-specific services in their own subdirectories, such as `lib/logingov/service`

This is not a large departure from the current V1 architecture, with the new `lib/auth` services fulfilling many of the same functions for V2 that `lib/saml` services provides V1.
