### ISSUE TITLE
Access for Jonathan Julian (SOCKS)

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#37361]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Jonathan Julian

### Your Email

jonathan@adhocteam.us

### Name of Your Team

Platform Spike Teams (Console UI), engineering lead, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLFDQJ9s3XzmVmH+3zbbWmqgYG+yTymcpf9FpTaaEkUN/Adn/I9mGw8l1MehBia0OoSG+51GEA1XIAVqgqRDPVzF1yTN1B7mK+PEh9rwNFFCsCPAMqkGWTY8mRi+0lUZN5TDwlfmECKPmCHm0PNmf34dJMMZpPrrGCscwHLVnLefbBRnPy7+6BJWHGR1yYdwOwmAPrLsujbYKbMSouhnsuXvduiZlv5ZgI33KJRCarX2WWoXX04vbK+dpSKx+Vpqy49z+PMHe/B6qdfI7dy5k9yjazDRkgds0G4306rbvDCxRu6VeevGGu+Gx7byP+HsVki4mfw8b3yn487WDoXrmwRFJ7rahU/2X/PnanAyUaIgL0mbt6aldRqdrDMItcQi0LWPmss7kUHr8h3LSXtFFwL/jajt0xiMz1TgABb279ZApYKVE8qOF9MkODJ+CAolJ3nlbPEFzrbPqkOzQfkD+rw5+aVNAAUElhx762tDCP6Pt4dL/bln9n8lzFMKAGPtU= jjulian@Jonathan-Julian-Macbook

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
@jjulian: access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
