### ISSUE TITLE
Plugin Development Documentation

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37378]
Document how to develop a custom authenticator plugin in keycloak. There are a lot of different plugins for Keycloak, need to communicate a standardized way to create an authenticator one as they're the most prevalent kind that will be needed. 

**Task is done when:** 
Page is present in confluence

**Comment by calquisola** [comment]
documentation created. 
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2099412995/Keycloak+Plugins
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2097152785/Post+Auth+Validation+Plugin
