### ISSUE TITLE
Ruby on Rails / Keycloak demo app

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37389]
Developers using the platform primarily use Ruby on Rails. 

As we have been creating test apps primarily in node and react to this point, we need to create a test app in Ruby on Rails that has the same functionality. 

 - There should an example of fine grained permissions also already build in/demo’d (User A can click 2 buttons. User B can only click 1 button. etc)
 - It can query keycloak for authorization, to do different thing based on permission. Like only show the buttons user has access to, etc

**Is completed when:**
When keycloak and rails app both run from a script and you can login to the rails app via the keycloak instance

**Comment by kylesoskin** [comment]
Repo is here and will be added to:
https://github.com/department-of-veterans-affairs/pst-amt-keycloak-rails-test-app

**Comment by kjduensing** [comment]
Related to #36999
