### ISSUE TITLE
On-Point Rotation Update

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#3738]
## Problem

There are 3 problems that we want to solve for:
 - The team is spreading themselves thin when responding to incidents that come up
 - We do not have a defined process for who is watching/cleaning up sentry alerts at any given time
 - Finding PRs that team members should be reviewing is time consuming and confusing

## Objectives
The objective of this task is to create and promote a process within the BE Tools team that would assign one team member each sprint to be the "lead" for all three of outlined problems listed above.  That team member (on their assigned sprint) would make it their priority to attend to Sentry alerts, take point on incident resolution (in conjunction with other teams if needed and pull in help from other team members only when needed), and be the gate keeper to assigning out PRs for review within the team.

This will reduce the burden of the rest of the team members so that they can focus on their tasks associated with sprint objectives.

## Acceptance Criteria
 - [x] Task 1: Come up with a name (other than On-Point) that the team agrees up
 - [x] Task 2: Create the documentation that clearly outlines the responsibility for this "On-Point" individual including all supporting docs that are identified
 - [ ] Create a schedule (where it makes the most sense) that includes each team member that aligns with our sprints
 - [ ] Conduct a training session for the entire team to ensure all members understand fully the responsibility during their time as "On-Point".

**Comment by alexpappasoddball** [comment]
@omgitsbillryan Here you go!

**Comment by johnpaulashenfelter** [comment]
https://docs.google.com/document/d/1JWjP-o3MO7BdKEftJ8jRaWONn4UaMbHtKDnrbCunnYo/edit

**Comment by kfrz** [comment]
**Thoughts on Sprint 17 Utility Dev**

- There were a lot of Sentry issues in the #vfs-sentry-alerts channel, though they aren't #1 priority, they do become overwhelming. We should continue our efforts to:
	- reduce the level of noise
	- automate some of this error handling assignment

- I should have opened a ticket for the incident response and customer support stuff I did so I don't have to backtrack through my week and do it later

- Maybe we can implement a checklist via simple Slack bot that pings utility dev on each business day at EOB in their time zone, which would log if they've got all the required tickets added

**Comment by alexpappasoddball** [comment]
@kfrz & @johnpaulashenfelter Can we close this issue?  Has Keifers comments been address in our internal documentation where needed?

**Comment by kfrz** [comment]
@alexpappasoddball we will address these questions and make sure the document is updated in our meeting tomorrow (02/06/20) morning.

**Comment by kfrz** [comment]
Based on the comments above I don't see any immediate action items to add to backlog - if I were following the existing docs I should have had no issues.

The other points are just ideas and don't warrant issues at this point.

Closing this ticket.
