### ISSUE TITLE
Offboarding of Rachael Roueche

### ISSUE THREAD

**Issue by td-usds** [department-of-veterans-affairs/va.gov-team#37392]
# Description
Please provide the following information about the individual being offboarded:
- name:
  > Rachael Roueche
- team name:
  > Platform Crew
- role on team:
  > Crew Chief
- expected last day:
  > 2022-FEB-15
- company they work for:
  > VA/Government
- email:
  > rachael.roueche@va.gov
- GitHub username:
  > @rroueche
- additional access they may have:
  > Google analytics, and anything else
  > NOTE: Rachael *remains* a VA employee, she is just no longer working on VA.gov
 
 
## AC
*Performed by Platform team*
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack (if applicable)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights @td-usds

**Comment by bsmartin-ep** [comment]
GA and Domo access removed.

**Comment by CoryTrimmUSDS** [comment]
Removed from Slack.

**Comment by oseasmoran73** [comment]
Not part of VFS
No SOCKS associated to VA, removed previous AdHoc
No AWS
Request to remove from Github - https://github.com/department-of-veterans-affairs/github-user-requests/issues/9915
Removed from PagerDuty
No Datadog
No Sentry
N/A for bots
