### ISSUE TITLE
Offboarding of Michael Fleet

### ISSUE THREAD

**Issue by nsmith1982** [department-of-veterans-affairs/va.gov-team#37390]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Michael Fleet
- team name:
  > VSP
- role on team:
  > Eng Lead
- expected last day:
  > 2/21/22
- company they work for:
  > Oddball
- email:
  > Michael.Fleet@oddball.io
- GitHub username:
  > f1337
- additional access they may have:
  > SOCKS, Pagerduty, Google analytics, AWS
 
 
## AC
*Performed by Platform team*
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable)
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] DSVA Slack (if applicable)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable) 
 - [x] Datadog account disabled (if applicable)
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by rmtolmach** [comment]
✖️ not in the VFS roster
✖️ no aws
✔️ removed from SOCKS
* not in gh https://github.com/orgs/department-of-veterans-affairs/people?query=f1337
* He is in pagerduty: https://dsva.pagerduty.com/users/P877JLV but this slack outage needs to be resolved or an admin needs to reassign it to another person:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/10993987/155184910-0e2931d8-32cd-47d2-b6e4-7f96bc44038b.png">

* He is in Sentry but an admin needs to remove him http://sentry.vfs.va.gov/settings/vsp/members/?query=fleet
* He's in Datadog, but I'm not sure how to delete him from there, either https://app.datadoghq.com/organization-settings/users?filter=fleet

**Comment by CoryTrimmUSDS** [comment]
Removed from Slack.

**Comment by bsmartin-ep** [comment]
No GA, Domo, GCP, or GTM access.
