### ISSUE TITLE
Remove In the spotlight feature on VAMC stories page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37397]
## Issue Description
The Stories feature for VAMC pages has experienced a regression.

## Current behavior
[Salt Lake City Health Care system stories page](https://staging.va.gov/salt-lake-city-health-care/stories/) is displays the "Back on the Ice" story "in the spotlight". This story is also the most recent, causing a duplication at the top of the page. Until we determine the desired behavior for this page, we need to remove the featured story display entirely. 

![image](https://user-images.githubusercontent.com/55411834/155193593-11919011-646d-42e7-8d76-806b42f06db6.png)

## Expected behavior
When a Veteran views the Stories page for their health care system, no "In the spotlight" area should be visible at the top of the page. 

## Dev Notes
Template:
```
<!--
  layout: story_listing.drupal.liquid
  path: salt-lake-city-health-care/stories
  entityId: 6821
-->
```

## Task
- [ ] Remove "In the spotlight component from top of Stories page
- [ ] Validate in tugboat using several different health care systems

## Acceptance criteria
- When a Veteran views the Stories page, they see the Stories heading and intro text, followed by the first story.
- Functionality of Featured spotlight stories area of main page is maintained.

**Comment by mmiddaugh** [comment]
@GcioNapoleon 
Expected behavior:
Most recent published story should still appear on Stories page - just not in an "In the spotlight at..." component. 


## Currently on Prod
Salt Lake City health care - top story on stories page is "VA Salt Lake City Veteran goes for snowboard gold in Beijing" 
<details>
<summary> Production stories page screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/157090125-7d8f61fc-e109-4e86-8db3-752177c34110.png)
</details>

## Validation on Tugboat
Salt Lake City health care - Top story on stories page is "Back on the ice"
<details>
<summary> Tugboat Salt Lake city health care stories page screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/157092719-bc8d1813-d097-42c9-a3c1-c0a15f372ee4.png)
</details>

<details>
<summary> Tugboat Salt Lake City health care system page </summary>

![image](https://user-images.githubusercontent.com/55411834/157092790-a7bcdf2f-066d-43dd-84cd-1a9537d9548e.png)
</details>

---
## Currently on Prod
Cheyenne health care - top story on stories page is "VA Rocky Mountain Network - 2021 Year in review"
<details>
<summary> Cheyenne  Stories page screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/157092399-6c03765b-e229-49e5-93b0-bfe711bb6526.png)
</details>

## Validation on Tugboat
Cheyenne health care - Top story on stories page is "Upholding Valor podcast"
<details>
<summary> Tugboat Cheyenne health care stories page screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/157092338-8c173f8f-6307-4449-beef-d58e803b94b8.png)
</details>

Cheyenne health care - top story on system page is "VA Rocky Mountain Network - 2021 Year in review"
<details>
<summary> Tugboat Cheyenne health care system page 

![image](https://user-images.githubusercontent.com/55411834/157092535-6e54dd2b-188f-4c43-94b5-e2d7726080dd.png)


</details>

**Comment by GcioNapoleon** [comment]
Can We please create a new ticket for the task: "Most recent published story should still appear on Stories page - just not in an "In the spotlight at..." component." The only reason I sized this ticket a 1 is because I thought we were only removing the component. i did to investigate how to get the data to do this new thing you're asking.

![Screen Shot 2022-03-07 at 12 27 04 PM](https://user-images.githubusercontent.com/95312667/157095350-c9d5cd3f-c755-4693-a25f-d23b0640a568.png)
emoving just the component

**Comment by mmiddaugh** [comment]
Validated in Tugboat viewing Puget Sound health care, Houston health care, Salt Lake City health care and Spokane health care.
