### ISSUE TITLE
Update Link on Education Hub

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/va.gov-team#3740]
We need to update the page at 

https://www.va.gov/education/

so that the link in this module

![image](https://user-images.githubusercontent.com/50150810/69666802-db442a00-105a-11ea-96ec-7e090089e708.png)

which is

https://www.benefits.va.gov/gibill/school_resources.asp

is updated to the new SCO resources page at 

https://www.va.gov/school-administrators/

The refresh is in place to get it to do what it's supposed to, but why trust a refresh? ;)

**Comment by Karak888** [comment]
ah was just going to have @RLHecht can you please take a look at this and see what you can do?  :cc @ncksllvn only because it was related to the redirect you just did for SCO.

**Comment by KevinMHoffmanUSDS** [comment]
Just FYI, the redirect is fine/necessary. Just changing the link so that it's not dependent on it in the future.

**Comment by RLHecht** [comment]
@KevinMHoffmanUSDS I updated the link in Drupal so it's now the school administrators one. @peggygannon could you please review and publish the page? Thanks!

preview-prod.vfs.va.gov/preview?nodeId=71

**Comment by RLHecht** [comment]
@jenniferlee-dsva see my comment above. Didn't realize Peggy is out the rest of this week. Could you please take a look and publish? preview-prod.vfs.va.gov/preview?nodeId=71

**Comment by jenniferlee-dsva** [comment]
Done

**Comment by KevinMHoffmanUSDS** [comment]
Thank you!!!!

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing issue.
