### ISSUE TITLE
HLR v2 Support Request

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#37407]
## Issue Description
Stakeholder has reported the following issue:

A lot of the 996s that are coming in from vagov are getting hard to read the verbiage is overlapping other words.

![image.png](https://images.zenhubusercontent.com/5ffca1cc8ef760e3db881927/7786c16e-e151-4714-9cf7-22792b81c312)

---
## Tasks
- [ ]Troubleshoot issue and apply fix.

## Acceptance Criteria
- [ ] Fix applied or update rolled back.
---

**Comment by cilestin** [comment]
PR for the fix: https://github.com/department-of-veterans-affairs/vets-api/pull/9190

**Comment by michelpmcdonald** [comment]
Vets-api does not actually create the HLR pdf that is currently used to submit HLRs(no auto-established VA endpoint is avail)

For HLRs, we use Lighthouse.  We send Lighthouse the form data, and internal to Lighthouse, they generate the HLR pdf this ticket is referring to.

Lighthouse has fixed the issue in the PR linked above, so I'm closing this ticket

**Comment by michelpmcdonald** [comment]
Vets-api does not actually create the HLR pdf that is currently used to submit HLRs(no auto-established VA endpoint is avail)

For HLRs, we use Lighthouse.  We send Lighthouse the form data, and internal to Lighthouse, they generate the HLR pdf this ticket is referring to.

Lighthouse has fixed the issue in the PR linked above, so I'm closing this ticket
