### ISSUE TITLE
Access for Thomas Ferrin

### ISSUE THREAD

**Issue by TPurple** [department-of-veterans-affairs/va.gov-team#37414]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Thomas Ferrin

### Your Email

thomas.ferrin@adhocteam.us

### Name of Your Team

Console UI, Researcher, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkkZli40lgvWSxrGR+eYTqMnhe+SedNAAVxMPQlJwF3pb1+cBYgRsLCionPZ0l0VaH4fql28rVesyTk2aOoMm3BZMiz6HlxzURbA4Q1S553/ZbK7uXfoKf3CEwtgEomXreD0/xHa71zjwlLVKpUoCPjEfg1sWvF3OgvdfXCatAe2apS8sMWxT2S+xmBAhpHIveQSsG8C+2ievSRkbqKM/o1dv9QIB2JEfay6oDHyWOrSUza5MwORG0Jr8CMTUtzoLH96/Wxep8hY9HYx2K2lVJVEPhLTVXQhFhTsq+akzwSc1nV9bOCqYvMm/+W7d224QBBbxjej4aopylO9SXXj+mH33lOn6IFRleuTO5W88dEi2Cffu6VMtyrEnuAm8SQewrdTxKCPLFMPCVSB9/Yarv9EYTKAO5imBmqQZXp4DezSToPHqC0pes6wxXbf1evoRAXsaY8Um3B/EUeHydy8TVtywES8ED2pqqJo7fSAgRL76WONsP0yw7hOUdrYm7VbE= thomasferrin@Thomas-Ferrin-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
