### ISSUE TITLE
[Copy] Candidate Address/Override: Revise modal copy based on user testing feedback

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#3741]
@peggygannon let's figure out how we can get this into your workload for this sprint/the next sprint when we're all back from the holiday.

### Background

[We conducted user testing on the address validation mockups](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/user%20testing/Research%20Summary.md) between November 13 – 21. As part of that, some of the main pain points we heard were:

1. Users didn't understand what it meant that their address wasn't "valid." ([More here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/user%20testing/Research%20Summary.md#participants-did-not-know-what-valid-meant))
2. Users didn't understand why they were sometimes able to override the determination that their address wasn't valid because they didn't understand why they should be able to save an address if something was wrong with it. ([More here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/user%20testing/Research%20Summary.md#there-was-a-lot-of-confusion-around-why-people-could-select-their-original-address-if-those-addresses-werent-valid))
3. Users wanted the VA's 800 number on screens where they were not able to override the "invalid" determination. ([More here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/user%20testing/Research%20Summary.md#people-mentioned-the-800-number-would-be-helpful-on-screens-where-you-cant-select-the-original-address-entered))
  - From a UX perspective, I'm conflicted about this feedback since I know that people working at VA call centers would also not be able to override the "invalid" determination and therefore won't be able to help people who might call in with this issue.

### Updates needed

Given the above, I've outlined some suggested copy below. If it is helpful, [here are some real-world examples of address validation for inspiration](https://baymard.com/checkout-usability/benchmark/step-type/address-validator).

**Address is invalid. User can override this determination or pick a suggested address.**

For this use case, it is important that we both flag a potential problem while also communicating that if they do choose to override the determination that this address might not be valid, their mail will still likely get delivered. Copy updates include :

- I removed any mention of the word "valid."
- I changed the main heading to "Please confirm your address" since override is allowed. I thought this language made it seem less likely that we were allowing people to save an address that was bad or would result in mail not getting delivered.
- For the body copy, I took a similar approach — make this more about confirming their original entry since override is allowed instead of communicating that the address is bad (and therefore making them question whether they should save it if they know it to be correct).

![7  Scenario 1: Override; Suggestions](https://user-images.githubusercontent.com/34068740/69666568-712b8500-105a-11ea-92a5-d782eef5188e.png)

**Address is invalid. User can override this determination, but there are no suggestions.**

Goals/changes are same as the above since override is allowed. The only copy difference is that I took out mention of choosing a suggested address since there are none.

![13  Scenario 2: Override; No suggestions](https://user-images.githubusercontent.com/34068740/69666674-9f10c980-105a-11ea-915f-5482130993cc.png)

**Address is invalid. User can not override this determination. They can only edit or pick a suggested address.**

Since override is *not* allowed in this use case, we need to communicate that the address is problematic and that it can not be saved as the person's mailing address. 

- I removed any mention of the word "valid."
- For the heading, I went with "We couldn't verify your address." This more clearly communicates that the address wasn't recognized and not that the address was in the wrong format (which is an interpretation that was pointed out by a testing participant).
- For the body copy, I made it more clear that they can not save this as their VA mailing address. 
- Note: I did *not* include the 800 number here since call center staff can't override the "invalid" determination. However, if you thought we should include it anyway, we can, but we should mention that call center staff can't force this address to be saved if it's not recognized by USPS.

![18  Scenario 3: No override; Suggestions](https://user-images.githubusercontent.com/34068740/69666955-20685c00-105b-11ea-84cd-da03f00d5198.png)

**Address is invalid. User can not override this determination. They can only edit their address.**

Same as above, but removed mention of selecting a suggested address.

![23  Scenario 4: No Override; No Suggestions](https://user-images.githubusercontent.com/34068740/69667125-66252480-105b-11ea-9ccb-e764db69267e.png)

**Comment by peggygannon** [comment]
@Samara-Strauss Please see below for my content recommendations for the updated Address messaging. Please let me know if you have any questions or want to discuss further.



Scenario 1: Address is invalid. User can override this determination or pick a suggested address.

**Please confirm your address**
We couldn’t confirm your address with the U.S. Postal Service.  Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, please edit it or choose a suggested address below. 

----

Scenario 2: Address is invalid. User can override this determination, but there are no suggestions.

**Please confirm your address**
We couldn’t confirm your address with the U.S. Postal Service.  Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, please edit it. 

---

Scenario 3: Address is invalid. User can not override this determination. They can only edit or pick a suggested address.

**We couldn’t verify your address**
We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered or choose a suggested one below.  

---

Scenario 4: Address is invalid. User can not override this determination. They can only edit their address.

**We couldn’t verify your address**
We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered. 

Our button style is sentence-case, so please lowercase address
{button} Edit address

**Comment by Samara-Strauss** [comment]
@peggygannon this knocks it out of the park. Thank you so much!

**Comment by Samara-Strauss** [comment]
Closing. FE is in #3890.
