### ISSUE TITLE
Access for Michael Haley

### ISSUE THREAD

**Issue by mhaley37** [department-of-veterans-affairs/va.gov-team#37416]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Michael Haley

### Your Email

mike.haley@adhocteam.us

### Name of Your Team

console-cli, Software Engineer, Adhoc team LLC

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDawE54HnCLWoPWgx1GhU3ykN+pX1l/T0DJGTzAQewCeVo5bz55K+5wdGiAsgpvB/VEydIiHDKmwjg9V4N7DMkB+vxS6/XCYeHXDEcqDr5izWrUZhrJf8ZhJm/p2Jv0GGjEHDjFvLSPuUgx7W9QIn0pQJIrYB3XEwCU1Ynuff1QpX7Mscpu51cSijndOCvwFgBUGn94PLb5QrvF3KcE7evvWUGIirF8xXZDUXIpOk3YhepOS8vfVZc5F3O5jMh3RZSvwIAzxsuiIBi1Rta84JN5xfJTvmC2o7hZn4Zmn7OEcqvA7lO8fyBkU0Wmhyx3nzMSD6Wsu/5YE5NpEHlUX5IOTRwZUtYcdd20aI0t/M7blOGc4szx0GIaUXv1cBN1SoDngnVpOFhtMjoDYwnC3RxMiYsjkm4XeOizk5ViJG5ArM/ZnFZmSM4QraHVB3DzZSdv94gLKKwDMEAt/ToWw3UKCAEOGLZS9TUbdlcrbQmrQtpwmWNKbfhisGJqrXvX7oE= michaelhaley@Michael-Haley-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
