### ISSUE TITLE
Expose KPIs programmatically 

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#3742]
## Problem Statement

It is difficult to extract KPIs, this is a manual process that requires looking into different systems and takes time away from developers each time these KPIs are required to be reported on.  These stats are in one or many systems already and we need to identity where they are and consolidate them, with the goal of exposing them in an easy way so it reduces the burden of reporting them when they are needed.

## Goal

- Identify and prioritize a list of KPI's that ultimately fall under our teams "jurisdiction"
- Propose a solution that would automate the reporting of these KPIs in real time

## VSP Q1 + Q2 2020 OKRs

O4: All of the Platform's KPIs are easily measured and shared openly.

## Questions

Where should KPI data be displayed?  Should other teams display their KPI's in a centralized location?

## Definition of done
- A list of high priority KPIs are identified
- A proposal to exposing these to the platform team (and leadership) is drafted.

**Comment by rroueche** [comment]
@alexpappasoddball what objective is this in pursuit of? please add to the description.
