### ISSUE TITLE
"Request COE" page updates from eBenefits Migration

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#37424]
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [x] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [ ] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Yes, this is to support the migration of viewing and requesting Certificate of Eligibility from eBenefits to va.gov. This tool allows users to view an existing COE or request a COE to assist in securing a home loan. 
* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE)
    * [Feature Flow Diagram](https://xd.adobe.com/view/6c65f5c2-36e1-4051-81be-6f8b9415a3cd-3936/)
    * [Prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap?mode=f)
    * Usability Testing: [Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-topline-summary.md), [Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-readout.md)
    * [IA Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md)

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 

   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [x] **Other**
   * This tool has several new pages associated with it. We are envisioning the following pages (described in the [IA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md)), which have been reviewed with VA stakeholders.
    * "How to request a COE page" - existing, but URL needs to be modified
    * "Request COE online" - existing, but URL needs to be modified
    * "Check COE status" static page - this is a new page for unauthenticated users
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* March 31

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: eBenefits Migration
- DEPO product owner: Matt Self
- Product manager: Jason Wolf
- Designer: Jim Adams
- FE engineer: Jesse Cohn, Jerek Shoemaker
- Product/team Slack channel: #vsa-ebn-migration

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by brianalloyd** [comment]
Connected to #36571 and #28677 and #23573.

**Comment by longmd** [comment]
@RLHecht , this widget will be available in production today after the 3P ET daily deploy. 

@candy-gcio , I see there will be some URL redirects that will need put in as part of this as well, is that correct? If so, do we know what those will be and when they will need to be activated? I have some other redirect tickets that I can batch these into if the timeline is close enough.

**Comment by longmd** [comment]
@RLHecht , that is correct. Just wanting to verify what the expected function is after the user completes the login process. After reviewing the slack discussion. I'm thinking I might have to tweak this a bit.

**Comment by longmd** [comment]
@RLHecht , this is now available for you in Drupal. The ID is `home-loan-coe-login-widget`.

**Comment by RLHecht** [comment]
Thanks @longmd The CTA button in that react widget doesn't seem to be working. It should be the same link that is currently in the "Sign in create an account" CTA button on the widgets on this page: https://www.va.gov/view-change-dependents. I can't see where it points to myself.

**Comment by longmd** [comment]
@RLHecht GRRR... Okay... I know which route to go. Will take care of this in the AM along with the redirects.

**Comment by longmd** [comment]
@RLHecht , This has been approved, merged and will be available after tomorrows daily. The updated ID will be `home-loan-coe-status` and this will be a CTA widget, just like the one on the dependents page you shared as an example.

**Comment by longmd** [comment]
@RLHecht , this should be available for you to use in production!

**Comment by RLHecht** [comment]
Woo hoo! Thanks, @longmd It looks great!
