### ISSUE TITLE
Fix/Refactor Thread Safety Issues Caught by Rubocop

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#3745]
## The Problem
`vets-api` contains code that is not thread safe. 

## Context
[A thread safety plugin was added to rubocop to scan for thread safety issues](https://github.com/department-of-veterans-affairs/vets-api/pull/3543), as a result of some MHV user data being mixed up between requests. At the time, it was believed that `vets-api` may contain a thread safety issue.

## Work to be Done
- [ ] Find any thread safety offenses that are being ignored and review them (~71 offenses)
- [ ] Either fix or add a "why" comment for each thread safety issue found by rubocop

**Comment by ericboehs** [comment]
We should break this up into a few tickets. Maybe by types of ThreadSafety violations (e.g. NewThread, MutableClassInstanceVariable, InstanceVariableInClassMethod).
