### ISSUE TITLE
Implement Changes to Proto per Latest Punchlist (COE)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37505]
### Background
There are a series of changes required to sync the COE prototype screens with the tools in development.

### Considerations
- [Link to COE punchlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/coe-design-punchlist.md)
- There are several questions that need resolution

### Tasks
- [x] Implement changes to UXPin prototype 
- [x] Update punchlist

### Acceptance Criteria
- [x] Updated UXPin prototype

**Comment by sporeboy** [comment]
Changes made to COE prototype. Most are within the form itself... [(Link to UXPin prototype)](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137584273)

**Comment by sporeboy** [comment]
Note: As yet, no changes have been made to the uploader feature in the form or Your COE tool.
