### ISSUE TITLE
[BE] | Datadog Dashboards | 1010EZ

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#37500]
## High Level User Story/ies
The 10-10EZ Team needs access to reporting data to monitor the health of its application on a daily, weekly and monthly basis to ensure the applications are performant.

## Metrics to Track

By any given set of dates:
-  How many attempted submissions
-  How many went through to ES (Enrollment System)
-  ~How many were blocked by MPI~ (not applicable)
-  How many were blocked by errors (can we define possible error types here?)
-  API response times 
     - Show an average response time by day/week/month from the time the "submit" event occurs until a 1) success or a 2) failure is returned
- Core stats: Daily Submission (Attempts | Successful | Blocked | Client Failures)
- Calculated stats: Daily Submission Failures = Attempts - Successful - Blocked

## Acceptance Criteria

- [x] All team members can access and view dashboards on key performance indicators (as defined above)
- [x] Notification alerts are set up and sent to slack based on pre-defined thresholds
- [x] Screenshot of dashboard shared here

**Comment by lihanli** [comment]
@SKasimow "How many were blocked by MPI" - how should this metric be calculated?

**Comment by lihanli** [comment]
![image](https://user-images.githubusercontent.com/830084/157744203-cccfcfb4-1872-4460-a42d-618a540cc48c.png)
