### ISSUE TITLE
[Phase 3] Use Service Connected  Combat Status to Fast Track Completion of 10-10EZ

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#37501]
## Story

As a veteran who has served in combat, I should be able to skip sections of the 10-10EZ.

Definition of served in combat:

- Served in a theater of combat operations after November 11, 1998, or were discharged from active duty on or after January 28, 2003, and 

- Were discharged less than 5 years ago 

Note: As a returning combat Veteran, you're eligible for these enhanced benefits for 5 years after discharge. At the end of this enhanced enrollment period, we'll assign you to the highest priority group you qualify for at that time.

## Acceptance Criteria

-[ ] Add query for combat rating for authenticated users
-[ ] Authenticated users with disability rating of 50% or higher should see messaging re: their eligibility for short-form application
-[ ] Upon clicking xx, user is taken to yy screen

**BLOCKED: awaiting stakeholders direction on what comprises eligibility**

**Comment by hdjustice** [comment]
After meeting with Christopher Hawkins (HEC Leadership and SME for Service History), it was discovered that the Service History items on the application require additional verifications, and some require the financial information (Means test=financial assessment) to make priority group determinations.  Therefore, we will not be pursuing this work right now.  There does not seem to be any service history that can be fast-tracked through the Short Form flow.
[8/16/22 Meeting Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/Bi-weekly%20Stakeholder%20Mtg%20notes/8-16-2022%20Bi-weekly%20Health%20Care%20App%20Update.md)
[Presentation review & notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/Bi-weekly%20Stakeholder%20Mtg%20notes/8-16-22%20Short%20Form%20-%20Expansion_%20Service%20History%20review.pptx)
