### ISSUE TITLE
[BE] Fix 1010cg validation error

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#37519]
http://sentry.vfs.va.gov/organizations/vsp/issues/81456/?environment=production&project=3&query=is%3Aunresolved+level%3Aerror+controller_name%3Acaregivers_assistance_claims&statsPeriod=14d

Add Logging to monitor for this error

**Comment by SKasimow** [comment]
@lihanli hi - was this completed or should I roll-over to sprint 69?

**Comment by lihanli** [comment]
@SKasimow i haven't started on it yet, it looks like this error rarely happens

**Comment by hdjustice** [comment]
@lihanli Do you think this might be related to the fix you completed yesterday?

cc: @markfallows

**Comment by lihanli** [comment]
@hdjustice no, this issue is for the 1010cg and not related to the 1010ez errors

**Comment by hdjustice** [comment]
oh right, sorry.. I got them mixed up.  Thanks!

**Comment by hdjustice** [comment]
Converted to epic in error.  Created new ticket #40185 for the effort.
