### ISSUE TITLE
Access for Ian Harrison 

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#37518]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ian Harrison

### Your Email

ian.harrison@adhocteam.us

### Name of Your Team

fe-tools

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMRX7VT5tUDqU3SFhymnkP13TUe/jDLGDECHOz6JswAz ian.harrison@adhocteam.us

### Access Expiration

ongoing

**Comment by it-harrison** [comment]
I had to delete my old SSH key and add a new one, so I need to get access again.

**Comment by oseasmoran73** [comment]
Updated SSH Keys. Closing ticket.
