### ISSUE TITLE
VSP Identity Splunk Rollout

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37524]
# Description
This epic encompasses the rollout of Splunk within the VSP Identity team - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Splunk/splunkdeploy.txt

# User Story
**As a**Engineer
**I want to**implement splunk.
**So that I can**our team can search data faster and efficiently.

# Acceptance Criteria
- [ ] Item
- [ ] Item
- [ ] Documentation created 
- [ ] End of Sprint Demo?

**Comment by sylvesterlee1911** [comment]
Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@sylvesterlee1911 
department-of-veterans-affairs
/
va.gov-team
Public
Code
Issues
5k+
Pull requests
106
Actions
Projects
35
Security
Insights
va.gov-team/products/identity/Splunk/splunkdeploy.txt
@sylvesterlee1911
sylvesterlee1911 Add files via upload
Latest commit fc805c3 9 minutes ago
 History
 1 contributor
65 lines (52 sloc)  2.88 KB
   
Splunk Project Oddball.io

10 Servers

3 - Heavy Forwarders
3 - Indexers
2 - Search Heads
1 - Control Master
1 - Deployment Servers

Load Balancer

SSL 
************************************************************************************************
Recommended hardware for management components
A Splunk Enterprise distributed deployment requires several management components. These components often run on their own instances, and can include:

Deployment Server
Heavy Forwarders
Indexer Cluster Management node
License Master
Monitoring Console
Search head cluster deployer
***********************************************************************************************



Search Heads

Minimum search head specification
An x86 64-bit chip architecture.
16 physical CPU cores, or 32 vCPU at 2Ghz or greater speed per core.
12GB RAM.
For storage, see What storage type should I use for a role?
A 1Gb Ethernet NIC, optional 2nd NIC for a management network.
A 64-bit Linux or Windows distribution. See Supported Operating Systems in the Installation Manual.

Indexer
When you distribute the indexing process among many indexers, the Splunk platform can scale to consume terabytes of data in a day. Adding indexers distributes the work of search requests and data indexing across all of the indexers. This horizontal scaling of indexers increases performance significantly.

Minimum indexer specification
An x86 64-bit chip architecture.
12 physical CPU cores, or 24 vCPU at 2GHz or greater per core.
12GB RAM.
For storage, see What storage type should I use for a role?
A 1Gb Ethernet NIC, with optional second NIC for a management network.
A 64-bit Linux or Windows distribution. See Supported Operating Systems in the Installation Manual.
Mid-range indexer specification
This specification adds additional cores and RAM to provide overhead for additional search concurrency in a distributed Splunk Enterprise deployment:

An x86 64-bit chip architecture.
24 physical CPU cores, or 48 vCPU at 2GHz or greater speed per core.
64GB RAM.
For storage, see What storage type should I use for a role?
A 1Gb Ethernet NIC, with optional second NIC for a management network.
A 64-bit Linux or Windows distribution. See Supported Operating Systems in the Installation Manual.
High-performance indexer specification
This specification adds additional cores, RAM, and storage performance to use for improving indexing throughput and providing overhead for additional search concurrency for use cases where sustained search performance is critical, such as Premium Splunk apps.

An x86 64-bit chip architecture.
48 physical CPU cores, or 96 vCPU at 2GHz or greater speed per core.
128GB RAM.
For storage, see What storage type should I use for a role?
A 1Gb Ethernet NIC with optional second NIC.
A 64-bit Linux or Windows distribution. See Supported Operating Systems in the Installation Manual.
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete

**Comment by nsoutouras** [comment]
Closing as Sylvester has left the team
