### ISSUE TITLE
Sort order for Vet Center Location pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37528]
## Issue description
As a Veteran, I want to view locations which offer Vet Center services more often first so that I can choose the location which is right for me. 
## Background
Vet Centers may have one or more associated Satellite locations. Outstations can be identified by facility ID. Community Access Points do not have facility ids

## Tasks
Add sort order logic to the Locations page so that locations are displayed within the Satellite locations list according to the following
- If present, outstations are displayed first using alpha order if more than one is present
- If present, Community access points are displayed using alpha order, if more than one is present
- If present, the Vet Center's associated Mobile Vet Center should be displayed under the community access points. 
- If present, other Mobile Centers should be displayed in alpha order, following the Vet Center's affiliated Mobile Vet Center. 

## Examples
[Great Falls Vet Center](https://www.va.gov/great-falls-vet-center/locations/)
<details>
<summary>Locations page </summary>
 Current behavior lists the following Satellite locations
- Great Falls Vet Center - 120th Airlift Wing (CAP)
- Great Falls Vet Center - Blackfeet Veteran’s Alliance Building (CAP)
- Great Falls Vet Center - Browning’s New Eagle Shield Building (CAP)
- Great Falls Vet Center - Grace Home Veterans Center (CAP)
- Great Falls Vet Center - Havre Job Service Center (CAP)
- Great Falls Vet Center - MSU Great Falls Veterans Success Center (CAP)
- Great Falls Vet Center - Rocky Boy Veteran Success Center (CAP)
- Great Falls Vet Center - University of Providence (CAP)
- Helena Outstation (Outstation)

---
Desired behavior 
- Helena Outstation (Outstation)
- Great Falls Vet Center - 120th Airlift Wing (CAP)
- Great Falls Vet Center - Blackfeet Veteran’s Alliance Building (CAP)
- Great Falls Vet Center - Browning’s New Eagle Shield Building (CAP)
- Great Falls Vet Center - Grace Home Veterans Center (CAP)
- Great Falls Vet Center - Havre Job Service Center (CAP)
- Great Falls Vet Center - MSU Great Falls Veterans Success Center (CAP)
- Great Falls Vet Center - Rocky Boy Veteran Success Center (CAP)
- Great Falls Vet Center - University of Providence (CAP)
</details>

---
[Elkton Vet Center](https://www.va.gov/elkton-vet-center/locations/)
<details>
<summary>Locations page </summary>
 Current behavior lists the following Satellite locations
- Aberdeen Outstation (Outstation)
- Elkton Vet Center - Centreveille (CAP)
- Elkton Vet Center - Chestertown (CAP)
- Elkton Vet Center - Elkton (CAP)
- Elkton Vet Center - Salisbury (CAP)
- Salisbury Outstation (Outstation)

---
Desired behavior 
- Aberdeen Outstation (Outstation)
- Salisbury Outstation (Outstation)
- Elkton Vet Center - Centreveille (CAP)
- Elkton Vet Center - Chestertown (CAP)
- Elkton Vet Center - Elkton (CAP)
- Elkton Vet Center - Salisbury (CAP)
</details>

---
[Nashville Vet Center](https://www.va.gov/nashville-vet-center/locations/)
<details>
<summary>Locations page </summary>
 Current behavior lists the following Satellite locations
- Clarksville Outstation (Outstation)
- Nashville Vet Center - Bowling Green (CAP)
- Knoxville Mobile Vet Center (nearby Mobile)
- Memphis Mobile Vet Center (nearby Mobile)
---
Desired behavior 
- Clarksville Outstation (Outstation)
- Nashville Vet Center - Bowling Green (CAP)
- Knoxville Mobile Vet Center (nearby Mobile)
- Memphis Mobile Vet Center (nearby Mobile)
</details>

---
[White River Junction Vet Center](https://www.va.gov/white-river-junction-vet-center/locations/)
<details>
<summary>Locations page </summary>
 Current behavior lists the following Satellite locations
- Keene Outstation (Outstation)
- Hartford Mobile Vet Center (nearby Mobile)
- Lewiston Mobile Vet Center (nearby Mobile)
- White River Junction Mobile Vet Center (affiliated Mobile)
---
Desired behavior 
- Keene Outstation (Outstation)
- White River Junction Mobile Vet Center (affiliated Mobile)
- Hartford Mobile Vet Center (nearby Mobile)
- Lewiston Mobile Vet Center (nearby Mobile)
</details>

---

## Acceptance criteria
- If present,  outstations are listed first under Satellite locations on the Locations page
- If more than one outstation is present, the locations are listed in alpha order.  
- If present, Community access points are displayed alphabetically under the outstations. 
- If present, the Vet Center's associated Mobile Vet Center should be displayed first.
- If present, other Mobile Centers should be displayed in alpha order.

**Comment by mmiddaugh** [comment]
Consider doing at same time as #35241

**Comment by davidmpickett** [comment]
Duplicate with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12096
