### ISSUE TITLE
[Design] HLR Opt Out of Legacy Issues

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3753]
## Problem Statement
Veterans need to be able to opt out of individual legacy issues when submitting a Higher-Level Review form. Because of this, there needs to be a design that displays all of a Veteran's legacy issues so that individual ones can be selected. The "Opt Out Checkbox" needs to be included in the design as well. 

## Goal
_Design a screen that allows Veterans to select individual legacy issues and confirm that they would like to opt out of the legacy appeals process_

## Objectives or Key Results this is meant to further
- _Create a way for Veterans to opt out of individual legacy issues_

## Acceptance Criteria
- [x] _Create a mockup in Invision and link to this ticket_
- [x] _Present design to Yana and/or Andrea_
- [ ] _Make edits if needed_
- [ ] _Tag Peggy in content review ticket when ready_ #3754 

## Invision Mockup

**Comment by rileyorr** [comment]
@YanaRoy I created [mockups](https://vsateams.invisionapp.com/share/W5U21BDFTQK) for two scenarios I think the legacy issues flow could go.
I'd like to meet with you, Kevin, and Andrea to discuss

**Comment by YanaRoy** [comment]
@kevinstachura

**Comment by kevinstachura** [comment]
Riley did create these screens via Sketch/Invision that we will not be using for MVP: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/396690609_HLR_Legacy-Issues_default

Closing this ticket out as we will not be using this flow for the HLR process/flow any longer.
