### ISSUE TITLE
[03/04/22] Support App / Email Subject Unique IDs

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#37531]

**Comment by chancetheoriginal** [comment]
Power Apps allows for this functionality but despite the Action syntax being correct, the form is not passing the input text to the Subject line as expected. 

Work ongoing.

**Comment by chancetheoriginal** [comment]
I've reached out to internal VA Power Platform/support contacts for further assistance. Awaiting response.

**Comment by chancetheoriginal** [comment]
Solution found and deployed to VEText/AVS support forms.

**Comment by lindsay-insco** [comment]
Working!
