### ISSUE TITLE
[01/01/23] Renewal of Certificates

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#37533]

**Comment by jwowk** [comment]
Renew certs coming up for renewal for year https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyourit.va.gov%2Fnav_to.do%3Furi%3D%252F%24pa_dashboard.do%253Fsysparm_dashboard%253Dce92f8df1b1e19945d46cb78624bcbc8%2526sysparm_tab%253Daeb2f8131b5e19945d46cb78624bcba3%2526sysparm_cancelable%253Dtrue%2526sysparm_editable%253Dundefined%2526sysparm_active_panel%253Dfalse&data=05%7C01%7C%7C3c2df373f19c4d2f238708daf269bce7%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638088833204025542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BJMKcM%2BS9B8usYbQN3k5%2F1Y9spG1ad6k%2FYcPJCrP%2BH0%3D&reserved=0
