### ISSUE TITLE
Link to safety protocol document needs to be updated

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#37547]
### Description
The link at the bottom of [this page](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Participantsafetyandrespondingtoemergenciesduringremoteresearchsessions) doesn't point to the master branch for the document.

The link (text is "Read more about our participant safety and emergency protocols.") is currently pointing to `https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/research/safety-protocol.md)` and it should point to `https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/safety-protocol.md` so people have the latest information

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Participantsafetyandrespondingtoemergenciesduringremoteresearchsessions

**Comment by gmaciolek** [comment]
Hi @andaleliz! Thanks for catching that. I've updated the link on the page: https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html
