### ISSUE TITLE
[Request Content Review] HLR Opt Out of Legacy Issues

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3754]
**User story**
As a member of Benefits and Memorials team building on VSP, I need my content reviewed to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3753)
- [Invision Mockup]()

**Acceptance criteria**
- [ ] Content reviewed 
- [ ] Required content updates/changes provided to Benefits and Memorials team

**Comment by kevinstachura** [comment]
We still need to align with AMO to determine intended copy on some of these screens to ensure they are both usable/understandable for the user but also meet AMOs internal goals. Once we have that meeting (hopefully tomorrow 3/10) then we can send this out to the content team to fix/refine copy.

**Comment by luke-gcio** [comment]
This will now be part of the collaboration cycle with VSP - OBE and new ticket will be created.
