### ISSUE TITLE
Engineering Support for Pilot

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#37552]
As a Veteran, I want to easily check in to my VA medical center appointment using my mobile device.

The purpose of this ticket is to allocate engineering support to the pilot effort. Issues have been coming up daily that require investigation and triage; we'd like to allocate one engineer from TEVI and one engineer from Chick'n Eggsperience to triage issues, assist with crosstraining, and participate in planning for a better/smoother support structure for pilot issues.

Acceptance Criteria:
- Determine one rep from each team to provide triage support for pilot issues for the sprint
- Start documenting triage knowledge/information and place in centralized place (github) for team members to easily reference. (To clarify- just a starting point for documentation would be great. A document shell and a designated place where this is stored would suffice. Time permitting, some triage notes captured at or after the knowledge sharing sessions would be great too.)
- Conduct cross training/knowledge sharing session(s) as needed to ensure that any engineer can pick this duty up in a future sprint, and to identify where triage issues will go (what types of issues do we expect to come up? what to look for? how to triage an issue coming in? where should certain types of issues go/who is the best person to address these types of issues?)

**Comment by acrollet** [comment]
I have definitely done a lot of engineering support this sprint but haven't made progress on the actual ACs. Do we want to keep the ticket in this format for the next sprint? I honestly think each AC could be its own ticket...

@loripusey @sarahknoppA6
