### ISSUE TITLE
Fix DEV environment VA profile connection

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#37577]
## Description
Trying to get a status on the following ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36578

We (profile team) think it may have already been taken care of by the devops team.

Reached out to Jeremy Britt on 2/24, but he was OOO.

**Comment by jhouse-solvd** [comment]
@tpharrison - Thanks for submitting! 

We'll take a look at this and follow up with questions or information as soon as possible. 

Feel free to tag me in this issue directly if you have any questions.

**Comment by tpharrison** [comment]
@jhouse-solvd - can you provide an update on this when you get a chance?  Thanks!

**Comment by jhouse-solvd** [comment]
@tpharrison - Can you help me understand what you're looking to verify? I looked through #36578, but I'm not sure I follow. Are you looking for a way to verify that the connection is working?

**Comment by tpharrison** [comment]
@jhouse-solvd - all I really know about this is in the #36578 ticket - I was just asked to follow up on the status.  Should I reach back out to Jeremy Britt?

**Comment by MarciMcGuireGCIO** [comment]
@lihanli - could you possibly provide a little more context to help Jesse determine how to confirm that this connection has been fixed?  This is a support ticket to follow up on this ticket you created -- #36578.   Thank you!

**Comment by lihanli** [comment]
the original issue was created because of this slack thread where jeremy britt said that the certificate for the dev va profile api was expiring
https://dsva.slack.com/archives/CE4304QPK/p1644334170695339

**Comment by jhouse-solvd** [comment]
Thanks for the extra info here. I'll reach out to the team to have them take a look. 

We should be able to get back to you tomorrow or next. Thanks for your patience on this!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @jhouse-solvd !

**Comment by jbritt1** [comment]
This is taken care of. The SSL certificates were updated and simple curl commands to the endpoint (through the forward proxy) show a working connection with a 200 HTTP response code:

```[root@ip-10-247-96-202 ~]# curl -vvv https://internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com:4433/contact-information-hub/sba/health
*   Trying 10.247.96.159...
* TCP_NODELAY set
* Connected to internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com (10.247.96.159) port 4433 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=.; L=.; O=.; CN=*.us-gov-west-1.elb.amazonaws.com
*  start date: Feb 23 23:42:25 2017 GMT
*  expire date: Feb 21 23:42:25 2027 GMT
*  common name: *.us-gov-west-1.elb.amazonaws.com (matched)
*  issuer: C=US; ST=.; L=.; O=.; CN=*.us-gov-west-1.elb.amazonaws.com
*  SSL certificate verify ok.
> GET /contact-information-hub/sba/health HTTP/1.1
> Host: internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com:4433
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< transfer-encoding: chunked
< vaprofiletxauditid: fac35e9e-47a3-4851-a838-6f54cd9afdfc
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< pragma: no-cache
< expires: 0
< strict-transport-security: max-age=31536000 ; includeSubDomains
< x-frame-options: DENY
< content-security-policy: script-src 'self'
< content-type: application/vnd.spring-boot.actuator.v3+json
< date: Thu, 10 Mar 2022 19:26:49 GMT
< referrer-policy: no-referrer
<
* Connection #0 to host internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com left intact
{"status":"UP","groups":["liveness","readiness"]}
```

**Comment by MarciMcGuireGCIO** [comment]
Excellent!  Thank you, @jbritt1 !
