### ISSUE TITLE
Respond to IRIS Claims/Benefits Issues

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#3757]
## Problem description. 
How might we work together in order to resolve the issues that are listed below that users are continuing to experience when it comes to claims?

## Goal
We are wanting to see users being able to upload documents, view their claim status, view GI Bill benefits, and view previous claim history.

## Acceptance Criteria
- [ ] VSA Benefits & Memorials is aware of the issues raised from IRIS/Call Centers
- [ ] Issues are added to VSA Benefits & Memorials queue
- [ ] VSP Analytics & Insights can follow progress on the Call Center issues

**Comment by Kimberley2019** [comment]
@YanaRoy Below is the Google Doc link that shows multiple issues from IRIS for claims or benefits.  Please advise if any additional information is required.

https://docs.google.com/spreadsheets/d/1bqBqcDU8GtdsemkfQjNAJXEQAGqw5lEvIK8g1R9cEcU/edit#gid=122763910

10/10/2019 01:52 PM	191009-000675	Escalated	 Devine	
The health benefits explorer tool on the VA website doesn't work. I've tried 5 different web browsers with the same result. After asking the last question "are you a medal of honor recipient", when you select either yes or no and press the next button, you're directed to a page that remains blank and never loads any information. The tool just locks up at this point. If you select the back button, it takes you back to the medal of honor question. No matter how many times you try going to the next page, the page never loads and the screen remains a blank gray screen.	
Benefit Hubs/Content	Personal info

10/11/2019 01:11 PM	191010-000196	Escalated	McCloskey	
I received a letter from the VA requesting additional information/supporting documentation; the letter states that the best way to provide this documentation is to upload it through the website. With that being said, why doesn't the upload function on the website work?? I've been attempting to upload the requested documents for a week and the site continues to return the same error. What is the problem?	
Claim Status	GENERAL ISSUES

10/14/2019 08:10 PM	191014-000609	Escalated	Maldonado
“Upload Evidence to Support your Claim”  under Disability section not available on our end. Trying to upload a completed VA Form 21-674	
Claim Status	Uploading docs

10/15/2019 07:12 AM	191015-000059	Escalated	 Leo	
Why is it I cannot see the status of the Claims I submitted on Aug 4, 2019. I just had a C&P exam on Oct 11, 2019?	
Claim Status	GENERAL ISSUES

10/15/2019 10:47 AM	190811-000322	Unresolved	Xiong	
I still can not view my GI BILL benefits on my VA.Gov account.	
GI Bill Statement of Benefits	GENERAL ISSUES

10/15/2019 10:47 AM	191010-000902	Escalated	Kabala	
I'm no longer able to follow the status of my claim, see updates, or view documents attached to my open claim. I called the VA hotline, but they said it was a site technical issue and to send a message here. Thanks!	
Claim Status	GENERAL ISSUES

10/15/2019 10:47 AM	190910-000529	Escalated	Grady	
Can’t get PDF files to upload keep getting internet server error. I have the latest version of explorer, adobe reader.  The files are well within limits   Question if I upload in JPEG it’s a single page at a time and that look undersized, when you receive a claim with JPEG do you have a way to resize them to make them readable? Is there a fix for both?	
Other	Uploading docs

10/15/2019 10:47 AM	191009-001151	Escalated	Neilson	
2 weeks ago, all the information on my Check Claim Account disappeared except that fact that it is in review and decision, and a computer generated completion date. All the activity trail is gone. The letters that was sent in, all 7 requests and what is going on with those requests are gone. Everything. Why is the information gone? I would like it to become visible again so I don't have to call to check on my claim status.	
Claim Status	Personal info

10/15/2019 11:00 AM	190906-000784	Unresolved	Cuarenta	
Requesting a copy of Veteran’s Service-Connected Disability Letter issued by the VA. I keep trying to download a copy, but the system keeps stating it's down. I'm in the process of completing the College Fee Waiver application for my child. Thanks for the help!	
VA Letters and Benefits	Downloading docs

10/15/2019 11:00 AM	190910-001174	Escalated	Jackson	
I am unable to view my disability claims online.  I used to be able to check the status.  please advise	Claim Status	GENERAL ISSUES

10/15/2019 11:00 AM	190911-000894	Escalated	Barber	
I am trying to submit my claim and have filled out all areas in question. Every time I select the submit button nothing happens and I have tried on different computers and with different browsers with the same outcome of it being not submitted, which is holding my case up.	
Claim Status	Uploading docs

10/15/2019 11:00 AM	190922-000192	Escalated	Adkins	
I don't understand why I keep getting the message saying "No Valid Address on File" when trying to download VA Letters	
Claim Status	GENERAL ISSUES

10/15/2019 11:00 AM	190918-000032	Escalated	Lewis	
I don't understand why I keep getting the message saying "No Valid Address on...	VA Letters and Benefits	Downloading docs

10/15/2019 11:00 AM	190930-000392	Escalated	Hock	
I am unable to submit a NEW disability claim via VA Benefits online.  I receive an error that the request cannot be completed.  I have tried submitting on different days, times, and computing platforms.  I was directed to use this utility to seek assistance.	
Claim Status	Uploading docs

10/22/2019 06:03 PM	191022-001230	Escalated	WHISENANT	I still are unable to submit my claim. It shows an error when I press the submit button. I have made numerous calls, put in a trouble ticket with no luck.	
Claim Status	Uploading docs

10/24/2019 10:44 AM	191024-000277	Escalated	King	
I am attempting to file a claim for compensation on VA.GOV. I first attempted this on October 9, 2019 and have an intent to file, but every time I hit the submit button I get an error message that says, sorry cant submit your form. I have attempted to submit it multiple times a day since the original date and have spent countless hours on the phone where nobody can explain what the issue is. I was told to submit my question here and I could possibly get help.	
Claim Status	Uploading docs

10/24/2019 02:15 PM	191024-000693	Escalated	Carlos	
Why Can I not submit my Claim Application? It says that there might be some blank requirements but I have revised it several times and there is nothing wrong I have even restarted it. It wont let you continue if it is blank so I know there is nothing missing.. How can I submit my claim?	
Claim Status	Uploading docs

10/25/2019 11:56 AM	191025-000433	Escalated	Ivery	
I need Technical Support for VA.gov every time I attempt submit my claim it errors our with the following code: 02e09a2dfc3ed271da0a0448 and	
Claim Status	Uploading docs

10/25/2019 12:46 PM	191025-000520	Escalated	Bodine	
As you can see by Inquiry number 191021-000840, I have been trying to check my transferred 9/11 GI benefits from my Father.  As directed, I have created my own DS Logon and attempted to check my education benefits, yet the only message VA.gov gives me is “…We’re having trouble finding your GI Bill benefit statement…”  This leads me to believe that I will never be able to see my educational benefits on line and the VA doesn’t really care because the bureaucracy is just too large.  Oh well, sucks to be me	Education Benefits Applications	GENERAL ISSUES

10/25/2019 06:01 PM	191025-001020	Escalated	hutchinson	"VAI 191025-001020
341/NCC/CGC
 Veteran is filling out 526ez on VA.gov has input his active duty time, moved onto the next page and va.gov is asking for his national guard and reserve time.  The veteran only has active duty time and tried to bypass the screen without entering any information and was unable to bypass screen without inputting information about the national guard and or reserve."	Claim Status	Personal info
10/27/2019 02:42 PM	191027-000168	Escalated	Session	I submitted a ticket with eBenefits Help Desk due to not being able to submit a claim. I was informed via email by eBenefits that the issue would be best handled with VA.gov help desk team as that feature has migrated from eBenftis to VA.gov.	
Claim Status	Uploading docs

10/28/2019 09:16 AM	191028-000170	Escalated	Griffith	
I am using the Post 9/11 GI Bill. I have recieved one book stipend, and the school has been paid for one semester. I use Ds login premium (CAC) to view my account, but it does not allow me to see any information about payment history, enrollment status, or eligiibiilty. Is there a way to view this information online?	
GI Bill Comparison Tool	GENERAL ISSUES
						
10/28/2019 01:45 PM	191028-000767	Escalated	O'Hara	
When attempting to sumbit claim website says it's taking too long and provides me with a ref. number (02a4bb4a40b446a396b2bfd2.). Unable to submit claim for a long time.	
Claim Status	Uploading docs

10/28/2019 04:54 PM	191028-001235	Escalated	Verloove	
Why can’t I see all the documents I uploaded to va.gov I used to be able to see everything in ebenefits now I cannot see anything. PLEASE FIX ASAP!!	
Claim Status	Uploading docs

10/31/2019 10:13 AM	191031-000281	Escalated	Ekstein	
The va.gov website is the worst. Functions of ebenefits website were supposedly moved to the va.gov website. They are not there. I needed to see a history of claims, it is not on any directory, nor listed under any sub directory. Also there is no help desk number listed. To top it off the dang thing takes so long to navigate within the website it times out. I have been passed around for over an hour.	
Claim Status	GENERAL ISSUES

11/02/2019 02:18 PM	191102-000212	Escalated	Oberg	
Apparently the VA needs my spouse's social security card and a 21-4138 form before I can claim her as a dependent, but now the website is refusing to let me upload the documentation with no explanation other than a vague "VA.gov is having trouble loading claims information at this time." Is there another way I can get this uploaded today?	
Claim Status	Uploading docs

**Comment by clantosswett** [comment]
I am adding a few other issues here as well. Let us know if these issues should be broken down into smaller tickets and how we can assist with tackling them: 

**Date:** 11/15/2019
**Issue Number:** 191113-000011
**Issue Type:** Appeal Status Incorrect
**Issue Description:** Veterans IRIS Inquiry concerns va.gov showing that VA granted his claim for service connection for left 5th finger sprain with degenerative arthritis. Veteran has submitted a screenshot (we don't have this because IRIS does not allow attachments but apparently it was verified by an agent), of the va.gov page that, in fact, says “VA has granted one or more issues on September 26, 2019.” “The appeal is now closed” (there never was an appeal-it was a new claim), and “Granted, Service connection, limitation of finger motion.”
However…
There never has been a grant for this contention. Rating Decision dated 08/12/2019, denied the issue. Notification letter was sent to Veteran explaining what to do if he disagrees. On 08/26/2019, the Veteran submitted a VA 21-0958 NOD(obsolete form). An EP 400 was opened, and subsequently closed on 09/26/2019, after a letter was sent to Veteran explaining that he needs to submit his disagreement on a 20-0995, 0996 or 10182 (new AMA forms).
Please provide explanation to Veteran as to why va.gov shows that this contention was granted – in contravention to the actual Rating Decision of 08/12/2019.


**Date:** 12/01/2019
**Issue Number:** 191031-000604
**Issue Type:** Claim and Appeal Status Disappeared
**Issue Description:** I had access to my claim and appeal status until a few weeks ago. When I sign in using either DS Logon, Myhealthevet, ID.me and go to "myVA" I'm not able to see my current appeals, it only shows closed appeals. I see the following error message "Appeal status is unavailable VA.gov is having trouble loading appeals information at this time. Please check back again in a hour. Please note: You are still able to review claims information.  This has happened on all devices - iPhone, iPad, MacBook, HP Desktop 


**Date:** 12/03/2019
**Issue Number:** 191023-000731
**Issue Type:** Appeal Status Incorrect
**Issue Description:** I submitted a notice of disagreement. My representative (DAV) says that they are able to see the status but when I login to VA.gov it does not show.


**Date:** 11/07/2019
**Issue Number:** 191101-000002
**Issue Type:** Claim and Appeal Status Disappeared
**Issue Description:** My VA. Gov website does not work and have not worked in 3 months. I can login but I can't see any of my claims ....I called everybody that I can and no one has been able to get my site to work


**Date:** 11/21/2019
**Issue Number:** 191110-000324
**Issue Type:** Evidence Uploading Issue
**Issue Description:** I had recently submitted two DBQ's 20 pages of documents plus one letter. All together totaling 21 pages. I uploaded them in the additional evidence tab and I was notified that the VA had received all of the paper work. How ever on the files tab it now says in the "Documents filed You haven’t turned in any documents to VA". I would like to know why it is that it says this. Please advise.

**Comment by Kimberley2019** [comment]
As of 12/30/2019, no updates after reaching out to @YanaRoy due to the Holidays and team members being out of the office.  @YanaRoy will verify once she is back in the office.

**Comment by Kimberley2019** [comment]
Slacked @YanaRoy for a status update on ticket.

**Comment by Kimberley2019** [comment]
Sent email to Yana and Luke to schedule a follow up meeting on issues that have been sent to them.

**Comment by Kimberley2019** [comment]
Roy, Yana M. - GovernmentCIO
Wed, Jan 8, 1:38 PM (22 hours ago)
to me, yanamroy@gmail.com, lmajewski@governmentcio.com, Chante

Hi Kimberley! Happy New Year!

I just spoke with Luke about this yesterday while he is transitioning into the Product Manager role on the Benefits and Memorials team and was planning on sending him the ticket we currently have from you today.

I think a meeting to discuss this with Luke would be great in order to establish a cadence and tracking method. I know we had originally agreed on an excel spreadsheet, however I do believe there needs to be some other way to categorize and track the issues being shared with us. I don’t currently have an idea on how to do that and am hopeful that Luke can come up with some sort of a suggestion.

Thank you for the email and I apologize for not having any progress to report on.

Yana



Kimberley Daniels <kimberley.daniels@adhocteam.us>
Jan 8, 2020, 2:36 PM (21 hours ago)
to Yana, yanamroy@gmail.com, lmajewski@governmentcio.com, Chante

Good Afternoon,

Thank you for the update Yana.

Congratulations Luke! I understand that there is time needed for transitioning, I will reach out to you on Friday with a few dates and times for an introduction meeting.  This will allow you time for Yana to provide you with any historical information that she needs to share with you.  If none of the options that are provided work for you or your team members, please feel free to suggest more feasible days and times so that we can schedule accordingly.

Looking forward to connecting with you.

Kind Regards,

Kimberley Daniels

**Comment by Kimberley2019** [comment]
Kimberley Daniels <kimberley.daniels@adhocteam.us>
Jan 14, 2020, 4:03 PM (18 hours ago)
to lmajewski, Chante

Good Afternoon Luke,

I hope that this correspondence finds you well.  Following up to see if you were able to review any historical data with Yana in order for us to move forward with scheduling our call.  Please advise if next week is suitable to schedule our Call Center Introduction call.  If so, I will send over options for days and times.  If not, please advise a feasible time frame that this call could take place.  

Looking forward to connecting with you.



Kind Regards,

Kimberley Daniels

**Comment by Kimberley2019** [comment]
Kimberley.Daniels 5:33 PM 1/15/2020
Good Afternoon Luke.
I am reaching out via slack because I am unsure if you have been able to review the email correspondence that you have been one.  I understand you are now the PM for Benefits and Memorials, congratulations on your new role.
My colleague and I are with the Contact Center Support team which manages reporting technical issues to the appropriate teams that are reported from Call Centers or from IRIS directly.  We ae attempting to set up meetings with different teams whose issues we have discovered; we have had this meeting previously with Yana.  I understand that due to this transition, you may need time with Yana to review any historical data that she has for you.  If/Once that takes place we are hoping to schedule time with you and your team in order to continue forward movement with the process.
Looking forward to hearing from you soon.

Luke Majewski 9:32 AM 1/16/2020
Hi Kimberley, nice to meet you! I'd be happy to sit down. I'm traveling this week and next week would definitely be better. I'll also meet with Yana to try and understand a little bit before we meet. What times next week work for you?


Kimberley.Daniels 11:10 AM 1/16/2020
Hi Luke.  My apologies for the delayed response.  Below is our availability for the Call Center Introduction meeting. Please advise which day and time works best for you and your team.  We will schedule for one hour and if we don't use the entire hour, then you get some valuable time back.  Once we schedule a time, I will send the documents that we will review during the call.
Tuesday: 2:00 - 3:30 EST
Wednesday: 12:30 - 2:00 EST
Thursday:  10:00 AM - 2:00 EST

**Comment by Kimberley2019** [comment]
Meeting with Luke is scheduled for 1/22/2020 at 1:00.

**Comment by joanneesteban** [comment]
### Grooming Follow Up

@Kimberley2019 to follow up with Luke. We may have to break this issue up into smaller tickets as it has become a larger task.

CC: @clantosswett

**Comment by Kimberley2019** [comment]
Breaking issues into smaller tickets is an ideal solution.

Follow up needed between @clantosswett and I to figure if this ticket needs to be closed due to the amount of time that has passed.  Unsure if issues still exists for all users listed above.  My suggestion is to close and open additional tickets as needed.

**Comment by Kimberley2019** [comment]
Closing ticket.

I will be closing the ticket due to the amount of time that it has been open.  Slacked Luke to inform of this and advised that he can still have his team do the research if he'd like.  

I will create a follow up template to contact the individuals listed in this ticket to see if they are still experiencing the issues.  

If so, a new ticket will be opened with the new information that has been provided to us by the users.
