### ISSUE TITLE
Determine which endpoints are owned by the platform

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#37588]
## User Story

_As a  stakeholder involved in the strategy for splitting up vets-api into microservices, I would like to know which of the current endpoints are owned by platform and which ones are owned by VFS, so that I can make informed recommendations about the structure of these services._

## Expected Behavior

_Column B of this doc should be populated with the appropriate data https://docs.google.com/spreadsheets/d/14iNeWOyaMe0aqVtgfCqTE7cl3xAfQ7YJDsjRbADOXCk/edit#gid=681198224&fvid=316271190_

## Acceptance Criteria

- [ ] _Every endpoint has a designation as either a platform endpoint or a VFS endpoint._

**Comment by ewilson-adhoc** [comment]
We are in the process of trying to figure out what work exactly needs to be done to get this ticket complete, and whether or not this work has already been accomplished elsewhere.

**Comment by ewilson-adhoc** [comment]
We should coordinate with the console UI team to eliminate duplicated work with https://github.com/department-of-veterans-affairs/backstage-test/issues/110#issuecomment-1059462423

**Comment by ewilson-adhoc** [comment]
Some historical context for this ticket
https://dsva.slack.com/archives/C02HFBJV11P/p1637790282174100

We have the data that we need for this stage of this project, and I've added links to the google document into confluence for ease of reference. In the future we may want to consider having this live somewhere more persistent.
