### ISSUE TITLE
Analytics Implementation for Authenticated Experience - My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#37589]
# Google Analytics Implementation Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Authenticated Experience - My VA
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - Project epic # My VA 2.0 Enhancements #31611
    - [**Product outline**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md)
    - **[OKR & KPI](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history#measuring-success)** 
         - **Objective**: Meet user need/expectation and elevate payment and debt information to user dashboard.
         - **Key result**: Increase overall clicks into payment history and debt information by 10%.

 
- **When is the launch date?**
    - Phased launch - Tentatively March 2022 (preferably before April)

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_

We are looking to track clicks into the URLs below, originating from va.gov/my-va. 
   
|KPI/metric|
|----------|
|Clicks to view all payments ("[View your payment history](va.gov/va-payment-history/payments)")|
|Clicks to view all debts ("You have n oustanding debt payments. [Manage your VA debt](va.gov/manage-va-debt/your-debt")| 
|Clicks to manage direct deposit ("[Manage your direct deposit](va.gov/profile/direct-deposit)")|
|Clicks to request travel reimbursement ("[Request travel reimbursement](va.gov/health-care/get-reimbursed-for-travel-pay/)")|
    

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Use case and users document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md) (stored in the `va.gov-team-sensitive` repository)
    - [Staging users and passwords document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) (stored in the `va.gov-team-sensitive` repository)

- **Any additional comments**

    - None at this time

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jennaouellet** [comment]
Hi @hdjustice! The links are tracking correctly and I've QA'd them below:


Item | GA Event |dL screenshot | Status
--| -- | -- | --
Clicks to view all payments |  Event Action: "Navigation - Link List - Benefit payments and debts - View your payment history" | ![image.png](https://images.zenhubusercontent.com/60e704a432c33f4d25bce83c/3b45e649-92d4-4466-856b-87528e0200a2) | 🟢 Tracking Correctly |
Clicks to view all debts | Event action: "Navigation - Alert Box - Link Click - warning -  - (not set) - Manage your VA debt" | ![image.png](https://images.zenhubusercontent.com/60e704a432c33f4d25bce83c/c83706ad-18ed-4449-aebc-1b65023a7ca8) | 🟢 Tracking Correctly |
Clicks to manage direct deposit | Event action: "Navigation - Link List - Direct deposit - Manage your direct deposit" | ![image.png](https://images.zenhubusercontent.com/60e704a432c33f4d25bce83c/b8941e55-288d-4157-bce8-e2426aebd2e7) | 🟢 Tracking Correctly |
Clicks to request travel reimbursement | Event action: "Navigation - Link List - Health care - Request travel reimbursement\" | ![image.png](https://images.zenhubusercontent.com/60e704a432c33f4d25bce83c/e4fe1da9-f441-4fcc-b8b2-9167aec082ee) | 🟢 Tracking Correctly |



Is there anything else you're hoping to track? If not I'll close out this ticket. Thank you!

**Comment by jennaouellet** [comment]
No problem! As always feel free to ping us if you have any questions!

**Comment by Samara-Strauss** [comment]
Hi all -- Thank you for implementing everything in our original request! We really appreciate it.

I am reopening this request to add one additional thing. I want to get a sense of how performant the dashboard is, and given that each element of the dashboard connects to different endpoints, we have to track this individually for each section. Would it be possible for us to track how often we successfully load people's payment information, and how often this fails? [We currently do this for the claims API on the existing My VA GA dashboard](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/), so I'm looking to add similar metrics for the payment information.

Please let me know if I should close this request and open another request for this information -- I'm happy to do that! And thank you for your help!

**Comment by jennaouellet** [comment]
Closing this ticket as we are tracking in #38739
