### ISSUE TITLE
Redirect 2 legacy Yellow Ribbon pages to new consolidated one

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#3759]
We need to redirect 2 legacy Education/Yellow Ribbon pages to the single new one which is live on VA.gov.

2 legacy pages:
https://www.benefits.va.gov/gibill/yellow_ribbon.asp
https://www.benefits.va.gov/GIBILL/yellow_ribbon/yrp_list_2019.asp

**Both** need to redirect to:
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/

@selina, the 2 YR Education SMEs are Lucas Tickner (lucas.tickner@va.gov) and Tammy Hurley (tammy.hurley@va.gov), for your email. Let me know if I can help with this.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] * (`frontend`, `devops`, `design`, `, `product`, `ia`, `content`)
- [ ] **Labeled with Type**

**Comment by AnneHurley** [comment]
@Karak888 @jenniferlee-dsva I assigned this to the open content parity Epic for Education, but I'm not sure if this even needs to be in an Epic - does it?

**Comment by AnneHurley** [comment]
@kelsonic @ncksllvn @mnorthuis FYI the closed Yellow Ribbon ticket is: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2612

**Comment by mnorthuis** [comment]
@Karak888 @ncksllvn redirect is vetted, documented and good to go when you are ready to implement.

**Comment by jenniferlee-dsva** [comment]
Also @lunascoop !

**Comment by Karak888** [comment]
@lunascoop can you please let us know when you have heard back from SMEs?  Thanks!

**Comment by lunascoop** [comment]
@Karak888 @ncksllvn @AnneHurley @jenniferlee-dsva I have sent redirect notification to SMEs. The scheduled redirect date is 12/11.

**Comment by lunascoop** [comment]
@mnorthuis @ncksllvn @AnneHurley @Karak888 @jenniferlee-dsva, I have validated that the redirects have gone live and will notify the stakeholders, close this ticket and update my communication log.
