### ISSUE TITLE
Discovery & Research for File Upload Protype

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#37591]
## User Story

_As a IET developer I would like to understand the technical limitations and industry standards associated with file upload services so that I ill be able to create technical specifications for the file upload service prototype implementation._

## Context
_This ticket represents a time-boxed research into both the existing vets-api code and other industry offerings required to gain context into the design of this project._

## Acceptance Criteria
- [x] _Other industry offerings are examined in order to look at the types of features that are supported (note -- we're not thinking about using any of these solutions, we're just looking at them from a product POV and trying to answer 'what are other people doing?')_
- [ ] _This list is divided into must have features and nice to have features._
- [ ] _The development team agrees that they have sufficient understanding of technical system limitations and feature requirements to begin technical design._

## Associated Documentation
**Requirements Gathering:**
https://vfs.atlassian.net/wiki/spaces/IET/pages/2101510336/Heroku+File+Upload+Plugins
https://vfs.atlassian.net/wiki/spaces/IET/pages/2108620842/Draft+RFC+File+Upload+Selection

**Comment by ewilson-adhoc** [comment]
I did a timeboxed (45 minutes)  research spike into the types of add-ons available for heroku and the functionality that they would provide to the application to think about this problem from the "other" side (ie - what are common features file upload services provide for a platform) versus needs specific to our platform. Findings can be found here: https://vfs.atlassian.net/wiki/spaces/IET/pages/2101510336/Heroku+File+Upload+Plugins

**Comment by ewilson-adhoc** [comment]
One of the end products of this should be an RFC that can be shared with a wider audidence.

**Comment by rogersarkis** [comment]
This story needs to be broken down into multiple stories

**Comment by ewilson-adhoc** [comment]
Smaller stories have been split off of this ticket, see https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/39982, https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/37592 and https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/37736
