### ISSUE TITLE
Summarize & Investigate our End to End Testing Processes for a Release

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#37597]
## Background Info
As a patient, I would like a stable and working check in experience when I go to my appointments.

This came out of the team of teams meeting on 2/24- we need to better document our testing strategy so that it can be shared with other teams and we can determine a time for feature freezes and code deployments due to prioritizing stability of our application. 

## Tasks
- Clean up and/or summarize (e.g. readme.md) what we currently have
- Identify what gaps we have in our documentation
- Determine how much time we need for testing before releasing a new feature
- Add tickets for any additional documentation work

Next step after this is completed (new ticket needed)- work with CHIP team to integrate our testing plans and determine a day and time when we will freeze new work going out, and a day and time for new code deployments.

**Comment by acrollet** [comment]
I added a basic background and ACs, subject to refinement :)

**Comment by sarahknoppA6** [comment]
@acrollet I'm so sorry, I think I may have wiped out your edits :( I was also adding the details I could remember and didn't know you were updating at the same time so I didn't see it :(((((((

**Comment by acrollet** [comment]
@sarahknoppA6 no problem, my edits were actually for the wrong issue anyway.

**Comment by acrollet** [comment]
Adding comment to say that [testrail](https://depo-platform-documentation.scrollhelp.site/developer-docs/Getting-Started-with-TestRail.1600716881.html) may be a good tool for this.

**Comment by loripusey** [comment]
@sarahknoppA6 can you provide some context on this ticket and the needs
