### ISSUE TITLE
Backend Error Metrics Integrated into Existing OnCall Infrastructure

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#376]
## High Level User Story
As a Backend VSP Engineer, I need a way for backend application errors to reach PagerDuty, so that I can be alerted when critical backend application errors occur. 

## Hypothesis/(es)
If we allow for backend error metrics to be integrated into our existing #oncall infrastructure, then backend developers can be quickly notified if critical errors occur. This is in contrast to what we have now, which is to manually look in Sentry to see if anything is wrong, where, problems may sit idly for hours or days.

## Goals
A way for backend application error metrics to be tied into the existing StatsD/Prometheus/Grafana/PagerDuty alerting infrastructure we have today.

## Objectives
_Which VSP Objectives does this body of work push forward?_ 
- `Automation + Instrumentation`
- `Support`,

## Definition of Done
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**

**Comment by kfrz** [comment]
We are probably able to do this w/ X-Ray now that it's available in AWS GovCloud US
