### ISSUE TITLE
EMAIL - [FE] Create HTML for Email page

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#37604]
## User Story
As a veteran, I would like to be able to update my email address so that the VA has my most up to date information 

## Wireframe
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/90A68D56-3723-440B-B74C-295003A1FA43

## Description
- Given I
    - Am performing pre-check-in
- When I
    - Am asked to confirm my email address
    - Choose to edit the email
- Then I
    - Can edit the email address (required) 

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by loripusey** [comment]
@sarahknoppA6 can you provide some information for this ticket so that I know what this is?

**Comment by benbrasso-agile6** [comment]
No comments from me. Doesn't look like this task was started.

**Comment by mdewey** [comment]
Work has been completed and are ready for review, see screenshots


![screencapture-localhost-3001-health-care-appointment-pre-check-in-edit-email-2022-04-04-10_33_48](https://user-images.githubusercontent.com/1793923/161567729-731661e8-bccc-4ae8-bf60-fad6ff44dd42.png)
![screencapture-localhost-3001-health-care-appointment-pre-check-in-edit-email-2022-04-04-10_38_00](https://user-images.githubusercontent.com/1793923/161567918-af7dd510-a0f3-46c0-9da2-d4e7664b0dd3.png)
![screencapture-localhost-3001-health-care-appointment-pre-check-in-edit-email-2022-04-04-10_37_50](https://user-images.githubusercontent.com/1793923/161567927-221fdc31-3e89-46ae-8943-e863b02c48b5.png)

**Comment by loripusey** [comment]
Screen shots look good to me. @zach-park please review as well.
