### ISSUE TITLE
[Content] Change your address content page: Remove subway map and replace with dynamic modal

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#3760]
This is a low priority enhancement. We'll get to it when we get to it. Not assigning this for now.

### Background

[In address validation user testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/user%20testing/Research%20Summary.md#showing-a-sign-in-link-on-the-change-your-address-content-page-is-confusing-when-a-user-is-already-signed-in), we noticed the "Change your address" content page uses subway map directions to tell you how to change your address. This means we show "Step one: Sign in to VA.gov" even when people are already signed in. This caused some confusion for participants who thought they had to sign in again.

### Design & Content

I recommend changing the subway map to a dynamic modal. We will need the following 3 states:

1. Sign in to VA.gov
2. Verify your identity
3. Go to the VA.gov profile

![Change address content page](https://user-images.githubusercontent.com/34068740/69677988-41887700-1072-11ea-8c96-4c6160e01172.png)

**Comment by tressaellen** [comment]
Since we are combining this with #8420 will track progress there, I am closing this ticket.
