### ISSUE TITLE
ADDRESS - [FE] Create HTML for Address Page

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#37603]
## User Story
As a veteran, I would like to be able to update an address for me, my emergency contact, or my next of kin so that the VA has my most recent information. 

## Wireframe
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/760BBCDA-2157-4F1F-BC42-AE6B2730B869

## Description
- Given I
    - Am performing pre-check-in
- When I
    - Am asked to confirm any contact information that has an address
    - Choose to edit the address for the contact
- Then I
    - Can edit the following
        - Indicator for "I live on a US military base"
        - Country (required)
        - Street address (required)
        - Street address 2
        - Street address 3
        - City (required)
        - State (required)
        - Zip code (required)

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
Brian to follow up for a meeting with UX on the changes needed.

**Comment by brianseek** [comment]
@zach-park here is a screen shot, at first glance I see that some of the spacing got lost in my last refactor if this. Feel free to make a list of needed changes here or we can jump on a quick call. Let me know what works best for you.
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287(Pixel 5).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/d048683a-2189-4312-a1f2-8c0f5749c5d2)

**Comment by zach-park** [comment]
@brianseek , here is the recommendation from the UX audit:
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/B0CB0B00-58E0-4CB3-B2B8-3F348E99DA4A
(Cc: @loripusey @kristenmcconnell )

**Comment by brianseek** [comment]
@zach-park since we are pausing on edit, I think we should park these changes for now. @loripusey Should we go ahead and close these tickets? I am making note of the incomplete UX review items for the edit notes.

**Comment by loripusey** [comment]
@brianseek @zach-park I think we should finish up what work we have for the ticket that we can complete this sprint, but if there is any follow-on work let me know and I'll create a new ticket so we can capture the work if and when we pick it up later

**Comment by sarahknoppA6** [comment]
@brianseek @zach-park are there any items that need to be reviewed to close the ticket? the notes are a little confusing, i can't tell
