### ISSUE TITLE
NAME - [FE] Create HTML for Name page

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#37611]

**Comment by brianseek** [comment]
Ready for UX review![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (2).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/333907cf-a34a-4ae2-80a7-282f4aa9966b)![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/9d9a7c69-81fe-45fe-83f6-7d68b75b3345)

**Comment by sarahknoppA6** [comment]
This is ready for UX review.

**Comment by brianseek** [comment]
@zach-park This one is ready for UX review. See screenshot in comment above.

**Comment by zach-park** [comment]
Hi @brianseek , here is the recommendation from the UX audit.
EC Name Edit: https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/GmRgbbE
NOK Name Edit: https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/OmjMZZG

**Comment by sarahknoppA6** [comment]
@brianseek @zach-park was there any other follow up on this ticket?
