### ISSUE TITLE
vets-api Liveliness/Readiness probe failures

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#37625]
The liveliness and readiness probe failures were causing puma to not start and the pod to fail for vets-api. [The code was removed here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/366), but we need to investigate the root cause. It could possibly be that we need to increase the interval or timeout.

**Comment by npeterson54** [comment]
@LindseySaari Can this be closed?
