### ISSUE TITLE
Increase VBA service information available in the Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37632]
## Problems to solve
Findings from VBA taxonomy research in February 2022 include
- Veterans appreciate any knowledge to help speed their VBA location visit or confirm their prior knowledge and research.
- Veterans who receive the wrong information (or perceive the information as wrong) can be subject to critical errors and loss of trust.
- Veterans don't often want to seek help at a physical location. When they do, they are looking for targeted, personal, and specific help.

Associated recommendation from VBA taxonomy research in February 2022
- Increase the amount of information offered alongside each service label.
- Provide a link, dropdown, or short, standard description for each service label in the Location 
   - Specific Pages to allow Veterans to confirm their understanding of the labelʼs meaning.

## Related issues
- #4865 - VBA taxonomy epic
- #34638 - research synthesis
- #37368 - presentation readout

**Comment by davidmpickett** [comment]
This will be a logical follow up to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10517

**Comment by davidmpickett** [comment]
Closing as duplicate with VBA MVP efforts https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10517
