### ISSUE TITLE
New VFS Team VA Notify Forms Strike Team

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#37635]
## Welcome and Introduction
We are excited to welcome your team to VA.gov. As a new VFS team, this template should be completed by your teams Product Owner and/or Product Manager. 

## User Stories
As the leader of a new VFS team, I need to share basic info about my team with Platform so that Platform teams can have knowledge of my team for future collaboration.

As the leader of a new VFS team, I need to ensure my team follows the instructions for new VFS team members so that they're aware of Platform policies and processes, and Platform is aware of who supports my team for future collaboration.

As the leader of a new VFS team, I need to ensure my teams product information is correct so that Platform can have an accurate list of VA.gov products.

As the leader of a new VFS team, I need to complete ATO orientation so that VA.gov continues to be a secured and approved application within the VA. 

## New Team Info
Add your team's practice and contact information below.

- **Team Name:** Forms Strike Team

- **OCTO-DE Product Owner:** Beverly Nelson

- **VA Business Owner:** Lauren Alexanderson

- **Crew:**
Delivery Manager: Zachary Law zachary.law@oddball.io
Product Manager: Megan Siddle megan.siddle@oddball.io
Lead Developer: Nathan Wright nathan.wright@oddball.io
UI/UX: Ian Hilton ian@oddball.io and Elissa Folk elissa.folk@oddball.io
Developer: Andrew andrew@docme360.com and Olaf Minkowicz ominkowicz@rise8.us
QA: Chris Peck chris.peck@oddball.io

- **Github team label:** Strike
 
- **Team launch date:** Jan 25th 2022
 
- **Public slack channel:** va-notify-forms-strike-team

 
- **Other team names:** Forms Strike Team

- [x] This information has been added.

## Platform Orientation for your team members
In addition to providing information to Platform and completing necessary tasks at the team level, there are also tasks that need to be completed at the individual level. As a team leader, you will need to: 
- [x] Direct your team member to the [New VFS Team members section](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-NewVFSTeammembers) on the Platform Orientation page of Platform Website
- [x] Ask all of your team members to follow the instructions provided

## Review and update your team's product information 
- [x] Go to the [VA Product Directory](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview)
- [x] Review to make sure that all of your team's products are listed and assigned correctly
- [x] Confirm that you have edit access for the page (you'll see the pencil/edit icon on top right side of page) 
- [x] If you don't have edit access, reach out to the [#vfs-platform-support channel](https://join.slack.com/share/enQtMjk1NjI2OTUyMzI4Ny03NTJiYjkxZTljMWQwYjczNTI1ZjUyYmUzNTYxN2IyMjMzNWUzMDBjN2UyOGQyNzA5MmM2YWVlNGJjMGFkYzZi) in Slack. Please note that access is given to Product Owners only.
- [x] If anything needs to be changed or added, edit the page in Confluence

## ATO (Authorization to Operate) orientation
- [x] Reach out to Faith Owusu-Sekyere on Slack
- [x] Request and schedule an ATO team orientation
- [x] Confirm that the orientation has been completed

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [x] New VFS Team has been added to the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)

**Comment by shiragoodman** [comment]
hi @megansiddle - could you please be sure to direct your team to complete the guidance under [New VFS Team Members ](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-NewVFSTeammembers) on Platform Website? Thank you!

**Comment by shiragoodman** [comment]
@megansiddle for Crew, we're asking which OCTO Crew your team is part of. The options are:

1. Platform
2. Benefit Tools
3. Sitewide 
4. Health Tools
5. Account Experience

Also, it sounds like you're Business Owner is OCTO-DE (via Lauren Alexanderson). 

Let me know if you have any questions/concerns. Thanks!

**Comment by megansiddle** [comment]
@shiragoodman our team is part of Account Experience. I've directed the team to complete the New VFS Team Members process. I've also got us scheduled for the ATO team orientation for March 8th.

**Comment by shiragoodman** [comment]
sounds good. Thanks @megansiddle !

**Comment by megansiddle** [comment]
hi @shiragoodman the team has completed the ATO Compliance training. Please let me know if there are any other steps.

**Comment by shiragoodman** [comment]
thanks for checking @megansiddle  - you're good to close this ticket!
