### ISSUE TITLE
[Research] - Auth Profile - MHV Profile - Create research plan

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#37646]
We're kicking off research for the MHV <> VA.gov profile alignment and need to do some planning for how we'll tackle this. 

Tasks
- Document approach to research goals outlined in the [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/mhv-profile-research)

**Comment by andaleliz** [comment]
@Samara-Strauss clarification question - are we strictly talking about the "My Profile" page of MHV, or are we including the other sections under "Personal information", which includes "My account", "Download my data" and others ([full IA map available here](https://app.mural.co/t/vsa8243/m/vsa8243/1645732777530/3b751dac638c58f4463823ac9476e4e25dc1240f?sender=lizlantz1528))

**Comment by andaleliz** [comment]
Nvm - I just saw in the project outline (linked above) the scope of this research includes everything in personal information.

**Comment by andaleliz** [comment]
[Research strategy draft here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/research-strategy.md) (not yet ready for review)

**Comment by andaleliz** [comment]
Good morning @Samara-Strauss! I added details to the [project outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/README.md)so that can function as more of a research strategy doc.  Initially I created a separate doc (above if you are curious), but it felt like too much duplication.  

Let me know how this all looks. Happy to edit as needed.

**Comment by Samara-Strauss** [comment]
This is great, @andaleliz! I think the timeline/approach is perfect. And agreed that you don't need to create a separate plan/document just for the sake of it since it would be too duplicative. This is clear and looks good to me.

**Comment by andaleliz** [comment]
Wonderful! I'll go ahead and consider this complete then :)

**Comment by MarciMcGuireGCIO** [comment]
Whooo!  Thanks!
