### ISSUE TITLE
508/compliance analysis testing on VRRAP high demand occupation pdf

### ISSUE THREAD

**Issue by jfinnern** [department-of-veterans-affairs/va.gov-team#37659]
Perform analysis testing to see if the VRRAP high demand occupation pdf is 508/compliance ready. (On both versions: Web and Download)

https://benefits.va.gov/GIBILL/docs/vrrap-high-demand-occupation-list.pdf

**Comment by hallihocine** [comment]
Our findings after performing some 508/Compliance testing using different screen readers (Voice Over with Safari and chrome on Mac, NVDA with Firefox for Windows) are: 

1. Unable to read the logos, it says only: image (no visible title to interact)
2. In web version using Voice Over with chrome, it skips the Logos
3. It reads everything else on the pages in both versions (web and download ) but with different issues of: 
 - Not highlighting/reading the text correctly, it breaks the sentences and paragraphs. (Voice Over with Chrome)
 - Page not scrolling down to see the read/highlighted text. (Voice Over with Safari)

**Comment by mrblanco1** [comment]
On 2/25/2022 Tammy Hurley confirmed the VRRAP High Demand Occupations pdf was not 508 compliant. She fixed it and AFS QA did testing finding the above. Closing this defect as Tammy Hurley confirmed this pdf is now 508 compliant.
