### ISSUE TITLE
Access for Lee Helmer

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#37652]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Lee Helmer

### Your Email

lee.helmer@adhocteam.us

### Name of Your Team

Console UI, Product Manager, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpgB8WsDIJW96heCo1tuKmpxZfS+NxU2cZlPHOB7MZrkkmTk9GnwHNQXXWr3wMyz9ZtlBXoBkdo+eAb58jMnMrXhQuSocuekm3LYPUokX3Py8BIffk1Y7P6+4rGZPHwoZrgTQqOnL6v1yQWPL8VreeWlVFxz9DB3iJLaG5KOKYjyZwmgiRvQtKQVQc5rdUebEX91uA2gw+sfuT6gVHfZhtZiITU2vQ4CKchhpoa3+ZuJhUiP7N75QJu72Etc5kpC6FAzotURluRA0fgHPHxWqaH5gihPjccCpFnfs4lXzbhryzFQ6MV4TOLlZ6ZuJRO6c9+36CJhcYFo2F9C3iKTsyXXE3c10tlkYDkxbJ6Cx+sRJFxOVhZDBmhg71SBEGNKw7qWr2RT79Zo2QhQcdfJ2OIW/Y14anyFuzscttU2ufFWFnGwnr0TDp64gwp/GVUgfttwm7xAGPWSbPTNmea59wduo4sEtdrkjNh5istkDq13yMIS7ASLV+Q3ChqnrEEzk= leehelmer@Lee-Helmer-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
@lhelmer Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
