### ISSUE TITLE
Add sign in widget for View your disability rating feature

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3767]
### **High Level User Story**
As a Veteran with a rated disability (or multiple rated disabilities), I need an easy way to see my combined VA rating and know that I can do this online, instead of calling VA or looking for my VA letters.

**Feature**
This feature displays the Veteran's total VA combined rating + list of all of their disabilities that are rated.

### **Frontend Engineering Tasks and Analytics**
- [x]  Build REACT widget on relevant pages and locations
- [ ]  coordinate with Drupal author for preview and go-live.
- [ ]  Add tracking to new landing page
- [ ]  Redirect URLs

Details
URL of new static landing page: www.va.gov/disability/view-disability-rating/
[Confirmed w/Mikki on call w/Peggy, 11/13/2019 ]

Benefit hub: Disability
Nav link location: Under Manage benefits spoke > After/below “Check claim or appeal status” link
Hub landing page location: Same as nav location.

Update existing page:
About VA disability ratings https://www.va.gov/disability/about-disability-ratings/

Add the REACT VIEW RATING tool on this page after/below the calculator (w/appropriate header text IF NEEDED)
Content notes for assigned web content person
disability-view-rating-static-landing-pg-ticket-content-notes-111319.docx

For reference
Mockup with DRAFT content here:
https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/

OLD ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2244
IA ticket: #2584

**Comment by Karak888** [comment]
@jenniferlee-dsva this is for REACT piece to View disability ratings feature migration into VA.gov- I have applied the epic, but this will need to be estimated and assigned at future sprint planning.

**Comment by lwalsh617** [comment]
My understanding was that I needed to revised draft content that had been written for the static page at https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/
which I did. (See attached). Am not clear on what "Add sign in widget"/REACT piece means. Will follow up with Jen. 
[view-disability-ratings-static-page-copy-12-03-19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3923023/view-disability-ratings-static-page-copy-12-03-19.docx)

**Comment by ncksllvn** [comment]
I implemented a CTA widget for the Disability Ratings page. Two things -

1. Similar to other CTA widgets and the disability rating calculator, you'll need to add it as content in the Drupal page. See the [change-direct-deposit](https://prod.cms.va.gov/change-direct-deposit) page for an example. The only difference is that the `WIDGET TYPE` field should be `disability-ratings`, instead of `direct-deposit` -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/8e73077c-fd70-4c3a-81d1-229b53cf5d8a)

2. Since Drupal is edited in prod (prod.cms.va.gov) and thereby points to production JavaScript code, this widget won't be available until after the next production release, which is delayed due to the holiday code freeze. This means that we can't configure the widget until after January 3rd.

**Comment by ncksllvn** [comment]
@Karak888 @lwalsh617 I don't think there's anything left to do on this ticket, dev-wise. What are the next steps for this ticket?

**Comment by ncksllvn** [comment]
Per @RLHecht, this widget is now on the page in Drupal. So, closing. @lwalsh617 @RLHecht LMK if you have any issues.

**Comment by lwalsh617** [comment]
Thanks @RLHecht for finding this ticket. @MickinSahni @jenniferlee-dsva Am reopening because am wondering if the widget got added to the VDR page itself, but never to the About disability ratings page--but we closed ticket assuming it was added to both. Will dig into this more tomorrow!

**Comment by MickinSahni** [comment]
it's already estimated so that's good but do we have room to pull it into sprint 14? @lwalsh617

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- Things left:
  - Left nav - Randi
  - Link added to Disability landing page - Anne 
  - Widget added to About Disability - Nick

**Comment by AnneHurley** [comment]
Blurb for Disability hub. 
[Blurb for Disability hub for disability calculator.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4167159/Blurb.for.Disability.hub.for.disability.calculator.docx)
@RLHecht  @lwalsh617  Let me know if this works as a blurb to tease to the page from the Disability hub.

**Comment by RLHecht** [comment]
@lwalsh617 @AnneHurley Is this too long? It should be similar to the other links and text here: https://www.va.gov/disability/#manage-your-veterans-disability-benefits

**Comment by AnneHurley** [comment]
@RLHecht @lwalsh617  sorry, I thought it was going higher on the page. How about just deleting that last sentence:

H: Learn how to find and calculate your combined disability rating
If you have more than one service-connected condition, use our calculator to find your VA combined disability rating. 
:

**Comment by RLHecht** [comment]
@AnneHurley @lwalsh617 I think this ticket is saying the link and blurb on the hub page should be referencing the **View** your disability ratings page. The calculator is on the **About** VA disability page so this text doesn't work. Anne, do you mind writing a new one?

**Comment by ncksllvn** [comment]
I have a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/11650) open to add some space between the sign-in widget and calculator on this page - http://preview-prod.vfs.va.gov/preview?nodeId=866. LMK if I should merge it.

**Comment by RLHecht** [comment]
@ncksllvn That makes sense. Do I need to wait for today's deployment before I publish the page for it to show up correctly? FYI @lwalsh617

**Comment by ncksllvn** [comment]
@RLHecht there spacing fix won't be there until today's deployment but you can go ahead and merge

**Comment by RLHecht** [comment]
@ncksllvn Looks like that PR was already merged! https://github.com/department-of-veterans-affairs/vets-website/pull/11650

**Comment by AnneHurley** [comment]
@RLHecht  @mnorthuis  

H: View your disability rating
If you have one or more disability ratings, you can see your VA combined disability rating and your individual ratings.

https://www.va.gov/disability/view-disability-rating/

How's this^

**Comment by RLHecht** [comment]
@jenniferlee-dsva @lwalsh617 and I just reworked this together to try to eliminate the complexity around individual/combined ratings. How is this? We will hold off on publishing till we get the OK.

H: View your disability rating
See the rating we assigned you based on the severity of your disability or disabilities.

**Comment by RLHecht** [comment]
I've published the About Your Disability page. @lwalsh617 @jenniferlee-dsva @MickinSahni @ncksllvn

**Comment by MickinSahni** [comment]
@RLHecht are we ready to close?!

**Comment by RLHecht** [comment]
@MickinSahni Not yet. The page hasn't been validated as live on the site yet and another piece needs to get done on Monday: adding the link on the hub landing page--the text is written above. Waiting on Jen's approval.

**Comment by jenniferlee-dsva** [comment]
@RLHecht (CC @lwalsh617 ) - Please use the edited: 

__View your disability rating__  
View your VA disability ratings and which of your ratings are service-connected.

Link to: https://www.va.gov/disability/view-disability-rating/

**Comment by MickinSahni** [comment]
2020-02-10 PW Standup
- Received correct text from Jen and will go live today and closed by tomorrow - Randi

**Comment by RLHecht** [comment]
@peggygannon Can you please review this new text on the disability hub landing page as well? If it's good, you can publish the page!

**Comment by peggygannon** [comment]
@randi.. reviewed and published!

**Comment by RLHecht** [comment]
These changes have been validated on the live site. The widget is showing on the About disability page and there is a link with text for the View your disability rating on the disability hub landing page. Closing ticket. @MickinSahni
