### ISSUE TITLE
Access for Naoufal El Hilali

### ISSUE THREAD

**Issue by garfield786** [department-of-veterans-affairs/va.gov-team#37685]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Naoufal El Hilali

### Your Email

naoufal.elhilali@adhocteam.us

### Name of Your Team

Console Services

### Service(s) You Want Access To

AWS

### Desired AWS Access

I need the standard DevOps role for the console services team.

### Access Expiration

on-going

**Comment by jbritt1** [comment]
### For AWS Access

User: Naoufal El Hilali
COR: Mary O’Toole
VOR: Oddball - Amber Malcolm
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: yes and no. Naoufal is a DevOps Engineer on the Console Services Team. have we decided yet how this model will look? will he be given matching permissions to that of the ops/platform-infra team? or will we need to devise a new policy that gives admin level perms, but only on resources owned by the assigned team? the overall permission scope likely needs more discussion, but we could at least get this part moving with general / baseline access to get something started while we deliberate on the remaining points/topics/questions.

**Comment by td-usds** [comment]
aws access approved

**Comment by jbritt1** [comment]
First-time login credentials passed to user at this time. Also requested a couple test operations to ensure the IAM policy applied works as intended and is properly scoped in accordance with https://dsva.slack.com/archives/CTYQL39FE/p1646405439308839.
