### ISSUE TITLE
add deployment verification configuration

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#377]
## Description

Robert added some playbooks for deployment verification a while back, but it didn't work for the vets.gov deployments at the time due to some differences in the jumpboxes. We didn't take the time to fix it back then, but now jumpboxes shouldn't be an issue so we should enable that where we can. 

## AC

- [ ] deployment verification is added to all "vagov" deployments in BRD

**Comment by njdister** [comment]
Note that deployment verification is only for the deploy-instances role and not the deploy-asg role.

**Comment by njdister** [comment]
This didn't work when I tested deployment verification for Jenkins the other day.  Need to test on scratch instances and investigate.
