### ISSUE TITLE
Caregiver KPI Workshop

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3771]
## User Story
As a VFS team, I need to set my KPIs so I can see what my data-driven product goals are before I begin building my veteran facing product.

## Goal
Hold KPI workshop with the Caregiver team and set KPI tracking expectations.

## Objective
Workshop KPI setting with VSA Benefits & Memorials 2 and VSA Caregiver so that they can set data-centered goals for their product before they begin to build.

## Acceptance Criteria
- [ ] Schedule KPI setting workshop with the team
- [ ] Send out pre-workshop work
- [ ] Host KPI setting workshop
- [ ] Send KPI workshop excel sheet to the team
- [ ] Follow up with team PM on KPI check ins

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@joanneesteban This is scheduled for Alayna and team on 1/3 from 2-4. Similar to the BAM2 workshop:

- [ ] May I grab your Zoom link?
- [ ] I have not followed up with pre-work if you can please distribute.

**Comment by joanneesteban** [comment]
[KPI Workshop](https://docs.google.com/spreadsheets/d/1I3K3qsfhw63Lc1XsXyT2v8ptg7Mpzt_Q3ieUR5IVwf0/edit#gid=1554481611) occurred on Monday, 1/6/20.

From the feedback, we will follow up with KPIs vs. tracked metrics prioritization with their product owner and product manager. We will also test a 1.5 hour format from Caregiver feedback.
