### ISSUE TITLE
AWS Staging:  Clinic List Not Being Filtered after selecting a new location and going back to previous location

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#37719]
1. VATs for Cheyenne Optometry is set to Yes, 36 months for both DS and Request. Cheyenne optometry has at least three clinics that are configured for direct scheduling.   Loveland optometry has DS = No.  Request = yes 12 mos.  
2. Login as Noah Staknis.  Noah has only been seen in 	CHY VISUAL FIELD (friendly name Visual Field), so this should be the only clinic that displays in VAOS.  noahjames.j.staknis@id.me
3. Select Start Scheduling, Select Eye, Select Optometry, Select Cheyenne VAMC.  
4. System shows CHY Visual Field as the only clinic available for direct scheduling.  This is as expected.  
5. Select the back button and select another site, Loveland.  System displays must have appt in last 12 mos. This is as expected. Close modal and Select Cheyenne again.  
6.  Actual response:  This time Cheyenne shows 5 clinics plus I need a different clinic.  Expected response:  Only Visual field should display as this is the only clinic veteran has been seen in in the last 24 mos.  

**Noah's past Optometry appts at Cheyenne VAMC** for the last three years
Appt Mgt Module               Feb 25, 2022@13:24:58          Page:    1 of    1 
Patient: STAKNIS,NOAH JAMES JOANCARLOS (9777) MT: COPAY EX            Outpatient
Total Appointment Profile        * - New GAF Required    
-----Clinic--------------------Appt Date/Time--------Status---------------------
 1   Chy Visual Field          05/01/2019@08:00      Checked Out           
 2   Chy Visual Field          07/10/2019@09:00      Checked Out           
 9   Chy Visual Field          04/21/2020@09:00      Cancelled By Patient  
 10  Chy Visual Field          04/23/2020@10:00      No Action Taken    

![ClinicsNotFilteredFrontEnd_37719.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/614b2699-af8c-4247-b264-979855900093)

**Comment by jenniemc** [comment]
Hold off merging code fix per Brad G.
https://github.com/department-of-veterans-affairs/vets-website/pull/20492#issuecomment-1068220308

**Comment by ldelacosta** [comment]
@marcynadeau - This ticket can be re-tested. Please let us know if you are experiencing any issues. Thanks!

**Comment by beth-wodzinski** [comment]
I tested this again today, and it worked as expected. 

Note: because of existing issue [VAOSR-3238](https://issues.mobilehealth.va.gov/browse/VAOSR-3238) I had to use Sidney to validate, instead of Loveland; but the behavior described in the defect is now working as expected .

@ldelacosta

**Comment by ldelacosta** [comment]
Closing out the ticket. No new issues reported.
