### ISSUE TITLE
[Research] - Auth Profile - MHV Profile - Collect data on MHV profile usage

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#37741]
We want to understand how people are currently using the MHV profile fields. Specific questions will be outlined in our project outline doc ["questions for profile team" section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/README.md#for-mhv-profile-team).

**Tasks**

- [x] Identify who can provide this information, if anyone
- [ ] Gather data

**Comment by andaleliz** [comment]
Sharing an update on this, @MarciMcGuireGCIO and @Samara-Strauss 

- I'm working with the By Light team to get some data. I received one data set about the "What is your relationship with the VA?" checkboxes, which I added to our sensitive repo in the `[profile/data/mhv-personal-information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization/profile/data/mhv-personal-information)` directory. I'll add more data here as I get it.
- I've got questions out to a few folks to try to make sense of that data
- I also updated the project outline to include some specific data related questions (see link above) will update as more questions come up.

To be continued :)

**Comment by Samara-Strauss** [comment]
Fantastic work, @andaleliz! Thank you for the update!

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO I have gathered some data but there's some outstanding, so I've moved this into sprint 69

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO this should be added to the sprint 69 issue we reviewed in planning today.

**Comment by MarciMcGuireGCIO** [comment]
Added! Thank you @andaleliz!

**Comment by andaleliz** [comment]
**Progress update**
I've gathered some data about usage of fields in my profile. One thing I was curious about is if people use the optional fields in the profile. My thinking was that comparing the `null` to `not null` values would tell us if Veterans are actually filling this out in the profile. 

However, in my meeting with Carnetta yesterday, she confirmed that some data is automatically populated once a MHV account is matched against other VA databases. In other words, if a MHV user leaves any optional fields blank, but that data is stored in IAM (identity access mgmt, another VA data source), then it's automatically filled out in their profile. So the `null` vs `not null` comparison is worthless.

MHV stakeholders have already identified several fields in My Profile they want to remove. For those that are undecided, we'll need to gather qual vs quant data to understand their value to Veterans and VA staff that support them.

There are a few of pages in Personal Information that we need to learn more about - neither the health apt or MHV teams have confirmed plans for them:
- In Case of Emergency
- Health Information
- My Links

We can use analytics for these pages to understand if/how these pages are being used, and supplement the data w/ feedback in interviews. 

**Next steps**
- I've asked the By Light team for analytics on those pages.
- Going to confirm with Carnetta that there aren't any data points I should be looking at that I haven't thought of.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for this update, @andaleliz ! 

That's too bad about the null vs not null.

You may have already asked this, but I wonder if there is a field in the DB that identifies the source of the data -- like a manual entry or name of an interface that wrote the record.

**Comment by andaleliz** [comment]
Oh, that's a great question @MarciMcGuireGCIO, I hadn't thought of that. I'll ask.

Let me know if you think of anything else!

**Comment by MarciMcGuireGCIO** [comment]
It's just a thought. We had a field for user IDs at a previous employer so customer service could see who updated a record last, and they also captured the app ID so we could pinpoint the source if something funky started happening to the records when  multiple apps needed to update the same records.

**Comment by Samara-Strauss** [comment]
This is great, Liz. Let us know what kind of analytics you can get on those pages, if any. I'll be interested to hear what people say about those sections in user research.

**Comment by andaleliz** [comment]
I scheduled some time with Carnetta tomorrow, and I'll ask her at that time about any fields that might ID the source of data.

Otherwise, I see that we have access to MHV analytics available in our GA suite, so I have access to any further data I'll need. Closing this out.

**Comment by MarciMcGuireGCIO** [comment]
Thank you!
