### ISSUE TITLE
[Research] - Auth Profile - MHV Profile - Analyze data on MHV profile usage

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#37740]
Now that we have the data on MHV usage, we need to understand it. (see [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/mhv-profile-research)). This ticket captures the necessary work for data analysis.

- usage for each optional field in My Profile (% of null compared to not null)
- For "What is your relationship to VA" what % of profiles have values other than the default "VA Patient" value?
- Are any optional fields not null by default. For example are the facilities under "My VA Treating Facilities" checked by default when MHV receives data that a person is registered somewhere?
  - If it is checked by default, then how many people ever make changes to those facilities?
- and probably more :)

**Tasks**
- [ ] Analyze data
- [ ] Document findings

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO this will go into sprint 69, fyi

**Comment by MarciMcGuireGCIO** [comment]
Thank you @andaleliz !

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO this should be added to the sprint 69 issue we reviewed in planning today.

**Comment by andaleliz** [comment]
I have some answers to our questions:
|Question|Metric|Result
|----|----|----|
| How many people visited the personal information sections of MHV in the last 12 months? | Pageviews for each page in the section,  and % of total  | TBD |
|  For “What is your relationship to VA” what % of profiles have values other than the auto checked “VA Patient” value? | % of null values compared to not null | Values could be auto checked once a match is made in IAM, so there isn't a quantitative way to evaluate if Veterans are providing this information |
| usage for each optional field in My Profile | % of null values compared to not null | Many profiles are set up through a MHV coordinator who tell Veterans they have to provide info (even if optional in the form) so quant data isn't a good way to evaluate if this is useful to Veterans|
| How many users have changed any checkbox selections on the facilities section checkboxes in the last 12 months? | # of profiles with a last changed date for checkbox fields within the last 12 months | The change date applies to all changes in the profile, so it wouldn't tell us about this specifically. As far as we know, there isn't a way to quantitatively measure usefulness of this field |
| Is there any data about the MHV admin portal usage to help us understand how coordinators use this information? | tbd | TBD |

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz great progress on this! Thank you!

**Comment by andaleliz** [comment]
It seems that quantitative data isn't as meaningful as we'd hoped.
1. Info the MHV profile can be manually updated in the UI by the logged in user OR auto-populated by MPI once the profile is matched. So null vs not-null values is not helpful in determining how much people use the profile.
2. We have analytics data, but there are many variations of the same URL and no one seems to know exactly why or what they mean.  It seems likely that the URLs with the highest counts are the most relevant, but we can't place full confidence in these URLs.

Given that, I'm inclined to focus data analysis on a few pages I have questions about so that I have some usage stats in my back pocket as I talk to Veterans. I updated the original first question in the table "How many people visited the personal information sections of MHV in the last 12 months?" to focus on the specific pages.

Here's how the answers to our questions are looking:

|Question|Metric|Result
|----|----|----|
| How many people visited the health information card page in the last 12 months?| Pageviews for each page in the section,  and % of total  | 587,510,  0.11%  |
| How many people visited the My Links page in the last 12 months? | Pageviews for each page in the section,  and % of total  | 148,332, % of Total: 0.03% |
| How many people visited the Account activity history page in the last 12 months? | Pageviews for each page in the section,  and % of total  | 196,177, 0.04% |
| How many people visited the In case of emergency in the last 12 months? | Pageviews for each page in the section,  and % of total  | 491,883, % of Total: 0.09% |
|  For “What is your relationship to VA” what % of profiles have values other than the auto checked “VA Patient” value? | % of null values compared to not null | Values could be auto checked once a match is made in IAM, so there isn't a quantitative way to evaluate if Veterans are providing this information. The database doesn't record the data source. |
| usage for each optional field in My Profile | % of null values compared to not null | Many profiles are set up through a MHV coordinator who tell Veterans they have to provide info (even if optional in the form) so quant data isn't a good way to evaluate if this is useful to Veterans|
| How many users have changed any checkbox selections on the facilities section checkboxes in the last 12 months? | # of profiles with a last changed date for checkbox fields within the last 12 months | The change date applies to all changes in the profile, so it wouldn't tell us about this specifically. As far as we know, there isn't a way to quantitatively measure usefulness of this field |
| Is there any data about the MHV admin portal usage to help us understand how coordinators use this information? | n /a | We learned coordinators don't use the self-entered information in the Personal Info section to support Veterans |

@Samara-Strauss or @MarciMcGuireGCIO, are there any other analytics or data points that might be helpful? If not, I'll close this out.

**Comment by MarciMcGuireGCIO** [comment]
Thanks @andaleliz I will dive in tomorrow!

**Comment by Samara-Strauss** [comment]
This is great, Liz. I don't think I have any other questions. For pages that aren't readily used, these numbers are helpful for us making our case for retiring these pages instead of bringing them over to VA.gov.

As for the questions we have that we can't get quantitative metrics on, I think we have helpful insight from the stakeholder interviews and/or will get insight from user testing.

I think we can call this done unless Marci has additional questions.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO I'm going to assume you don't have any more questions and close this out. But please lmk if that's not the case :)
