### ISSUE TITLE
[SW-Content] Copy/place new react widget on Virtual Agent page and publish [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37746]
## Story
As a Veteran I need precise information on the Virtual Agent Chatbot landing page, so I will know my next steps, what I can perform, and how to complete my request.

## Resources
#36443

## Task
- [x] Load new react widget created by PW
- [x] Test widget and location on page and publish

## Acceptance Criteria
* Page is published and Stakeholder is informed of update.

**Comment by RLHecht** [comment]
I added the react widget and published the page. PW is still testing to make sure it's working correctly but our part is complete.
