### ISSUE TITLE
Development of type ahead search component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#37744]
There was an experimental design request to add type ahead search as an experimental design component. Since there was a lot of research already done, the DSC decided to have type ahead search added as a component to the design system. 

Here are links to related tickets on type ahead search.. 
Standardize type ahead search pattern - https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/308

Experimental Design System Request: Typeahead
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/637

Create mockups for Type-ahead component - https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/641

- [ ]  develop type ahead search component based on designs
- [ ] E2E tests are written
- [ ] Merge component

**Comment by k80bowman** [comment]
closing, this work is done.
