### ISSUE TITLE
Offboarding of Carla Chapa

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#37750]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Carla Chapa
- team name:
  > VFS-CMS Offices Team
- role on team:
  > Delivery Manager
- expected last day:
  > 2/25/22
- company they work for:
  > Agile 6
- email:
  > carla.chapa@agile6.com
- GitHub username:
  > carla-chapa
- additional access they may have:
  > SOCKS, DSVA Slack
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-support/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by bsmartin-ep** [comment]
No GA or Domo access.

**Comment by oseasmoran73** [comment]
No SOCKS
No AWS
Remove from VA Org -- https://github.com/department-of-veterans-affairs/github-user-requests/issues/9955
No PagerDuty
No Datadog
No Sentry
No Bots

**Comment by CoryTrimmUSDS** [comment]
Removed from Slack.
