### ISSUE TITLE
Access for Jonathan (Yoni) Doron-Peters

### ISSUE THREAD

**Issue by yonidoronpeters** [department-of-veterans-affairs/va.gov-team#37759]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Jonathan Doron-Peters

### Your Email

jonathan.d@thoughtworks.com

### Name of Your Team

Digital Health Platform (DHP) Team, Developer, Thoughtworks

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFnHCvE/TVahasqBC1/nN5rIZpVVfXGjKHdprAZij7yufa9U8mgjtsQMCDmaYtRkuKPCUHXvWJo5IU6w49sNnGBFtNKOdEySlBBZQTI00kT511jTeV4hrBqVZZtKd/jWRRAdjSnUsEirQNLPyGjCLLEtc9/qy+arqkgc+ULZHQv0Pd1/paJZy3wsnpyekIw1qfosUWPAgRKPnzw+ofXkFtAKUEVmT0am4gQ3MzZjntc1CY3l5zommpnOxh3YLXqpaDWsC5H5h/u9sfpN7ebcNbsTL3K/pvTCPN5t0vaRlgw4Q9j2R3gEiUq84gnYiWwCmEyBSQIiSc352TNnop0VuqO+EFGRo/t3vqcdpTRMN6qqAo1u1zVtwsT7+YV1lqW5cUkULkUumKeXs891axGRCMOia2K9KQZjNDXNqpwknbGUq4dji8F/RjZAQQlYsGeYoqagxyRtjv6WaTGVaZd6SbBsRiZInd7BzyvML4UaMcv2dj6VndPP0SvNMnmuFcEk0= ydp@Yonis-MBP

### Desired AWS Access

For now I just need an AWS account and access to logs/metrics/jenkins via SOCKS

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Comment by oseasmoran73** [comment]
## For AWS Access

User: Jonathan (Yoni) Doron-Peters
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers

**Comment by yonidoronpeters** [comment]
@oseasmoran73 Updated the issue description with the correct ssh key after following the example [here](https://www.youtube.com/watch?v=OnBhO3FVTTg)

**Comment by td-usds** [comment]
Access approved

**Comment by oseasmoran73** [comment]
User added, first-time login instructions sent.
