### ISSUE TITLE
System Down View web component: migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#37758]
## Description
Dependent on #37733

The SystemDownView React component is only used in two places in `vets-website`, so I don't think we need an ESLint rule. Both files where this component is used are owned by the Frontend Review Group, so we can migrate those uses on our own.
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/user/authorization/components/RequiredLoginView.jsx
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/veteran-id-card/components/RequiredVeteranView.jsx

## Acceptance Criteria
- [ ] migrate both uses of the React SystemDownView component to the new va-system-design-view web component

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated.
