### ISSUE TITLE
Update VFS applications with current product owners

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3775]
## User Story or Problem Statement
How might we see who owns what VFS application so that we can accurately map metrics to each VFS application?

## Goal
Have a set list of current and active VFS applications (forms/views) and the product owners/managers.

## Objectives or Key Results this is meant to further
Work with VFS teams to update the Product Directory for accurate VFS applications to product owners so that we can begin mapping KPIs to VFS applications per QASP requirements.

## Acceptance Criteria
- [ ] Update the list of VFS applications with product owners and descriptions for 
    - [ ] Education
    - [ ] Claims
    - [ ] Personalized Tools
    - [ ] Health Care
    - [ ] Burial & Pre-Need
    - [ ] Discharge
    - [ ] Pension
    - [ ] Unauthenticated Experience
- [ ] Ensure onboarded teams' VFS applications are listed out (and mapped to the categories above)
    - [ ] Public Websites
    - [ ] Benefits & Memorials 
    - [ ] Benefits & Memorials 2
    - [ ] VAOS
    - [ ] VAMC
    - [ ] eBenefits
    - [ ] Authenticated Experience
    - [ ] Caregiver
    - [ ] Facility Locator

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
### Objective

The purpose of this is multi-fold:
- Have a map to link KPIs to VFS applications per QASP
- Have a map to add other products to the Product Success Tool when we're ready
- Be able to link KPIs to the products on the Product Success Tool
- Be able to link owners/stakeholders back to products on the Product Success Tool

## Approach

Iterate on the [Education Intro Links template](https://docs.google.com/spreadsheets/d/1kXX2I971mtShe2EVwAn1-eFK3GheUNnls76sb3bf2r4/edit#gid=680304574) to include a VFS team column (i.e. VSA eBenefits, VSA Facility Locator, VAOS, etc.) and expand to the other products listed on the [Sheets MVP](https://docs.google.com/spreadsheets/d/1kXX2I971mtShe2EVwAn1-eFK3GheUNnls76sb3bf2r4/edit#gid=680304574), under the "Aspirational Copy" (marking the applications that have and don't have Google Analytics data/what is 'aspirational').

@amycesal

**Comment by joanneesteban** [comment]
**Nice to Have**: Start list of applications that are in development (not currently on VA.gov).

**Comment by amycesal** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1e1I_iqnNOCqtc2SxrX0eLKTzOFJiImgX4hWYGZ_siV4/edit#gid=0

It would be helpful to have leadership go through and add who is assigned (or not assigned) to each product and see if we are missing any products in this list. We did this with Kevin for Education, and I think it worked really well.
