### ISSUE TITLE
Offboarding of [George Chewning]

### ISSUE THREAD

**Issue by eunicegar** [department-of-veterans-affairs/va.gov-team#37760]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > George Chewning
- team name:
  > [all-va](https://github.com/orgs/department-of-veterans-affairs/teams/all-va)
  > [CTO-office](https://github.com/orgs/department-of-veterans-affairs/teams/cto-office)
  > [va-cto-health-products](https://github.com/orgs/department-of-veterans-affairs/teams/va-cto-health-products)
  
- role on team:
  > 
- expected last day:
  > 2/18/22
- company they work for:
  > 
- email:
  > george.chewning@va.gov (deactivated already)
- GitHub username:
  > @GeorgeChewningVA
- additional access they may have:
  > ex: SOCKS, Pagerduty, Google analytics, etc.
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [ ] DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-support/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by rmtolmach** [comment]
/request George Chewning

There are two Georges in Slack. One is deactivated, but the other is a guest? Associated with Lighthouse?

**Comment by rmtolmach** [comment]
✅  removed from VFS roster
✖️  no SOCKS
✖️  not in AWS
✅  Removed https://github.com/department-of-veterans-affairs/github-user-requests/issues/9953
✖️  not in pagerduty
✖️  not in datadog
✖️  not in sentry
n/a bot user access

**Comment by jennaouellet** [comment]
No GA access
Domo access removed
