### ISSUE TITLE
Offboarding of [Wanmei Ou]

### ISSUE THREAD

**Issue by eunicegar** [department-of-veterans-affairs/va.gov-team#37761]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Wanmei Ou
- team name:
  > [all-va](https://github.com/orgs/department-of-veterans-affairs/teams/all-va)
  > [cds-tools-platform-write](https://github.com/orgs/department-of-veterans-affairs/teams/cds-tools-platform-write)
  > [covid-patient-manager-write](https://github.com/orgs/department-of-veterans-affairs/teams/covid-patient-manager-write)
  > [CTO-office](https://github.com/orgs/department-of-veterans-affairs/teams/cto-office)
  > [hdp](https://github.com/orgs/department-of-veterans-affairs/teams/hdp)
  > [data-catalog-write](https://github.com/orgs/department-of-veterans-affairs/teams/data-catalog-write)
  > [lung-cancer-screening-platform](https://github.com/orgs/department-of-veterans-affairs/teams/lung-cancer-screening-platform)
  > [va-cto-health-products](https://github.com/orgs/department-of-veterans-affairs/teams/va-cto-health-products)
- role on team:
  > Product
- expected last day:
  > 3/10/22

- company they work for:
  > https://github.com/department-of-veterans-affairs
- email:
  > wanmei.ou@va.gov
- GitHub username:
  > @wanmeiou1776
- additional access they may have:
  > ex: SOCKS, Pagerduty, Google analytics, etc.
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [ ] DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-support/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights

**Comment by rmtolmach** [comment]
/request Wanmei Ou

There are two Wanmei Ou members in Slack. One is deactivated already and one is not.

**Comment by rmtolmach** [comment]
✖️  not in VFS roster
✖️  no SOCKS
✖️  no AWS
✖️  no pagerduty 
❓ Wanmei has a pending invite in Datadog. When I try to delete the invite, I get an error message. https://app.datadoghq.com/organization-settings/users?filter=wan
✖️  no sentry
✅  removed from github org in https://github.com/department-of-veterans-affairs/github-user-requests/issues/9954

**Comment by rmtolmach** [comment]
✅  Jeremy was able to delete Wanmei from datadog.

**Comment by jennaouellet** [comment]
No GA or Domo access

**Comment by rmtolmach** [comment]
Both Wanmei Ou members in Slack have been deactivated
<img width="458" alt="image" src="https://user-images.githubusercontent.com/10993987/156055331-5fdedbae-d3f8-48c6-a23e-504801f0b946.png">

Closing.

**Comment by rmtolmach** [comment]
Hi @eunicegar, I just noticed that Wanmei's last day isn't until the 10th. Is she going to be okay without Slack and GitHub access for the next 10 days?

**Comment by rmtolmach** [comment]
😅  ok, thanks for letting me know.

**Comment by eunicegar** [comment]
No problem!
