### ISSUE TITLE
Grafana/Sentry Testing

### ISSUE THREAD

**Issue by sylvesterlee1911** [department-of-veterans-affairs/va.gov-team#37765]
# Description

# Acceptance Criteria

# Deliverables

**Comment by nsoutouras** [comment]
@sylvesterlee1911  needs details.  Please work with @joeniquette and possibly @jscanish

**Comment by sylvesterlee1911** [comment]
Get more familiar with these systems.  Check out what is in here and what is assigned to our team.  

Schedule some time with Joe on this.
