### ISSUE TITLE
As a Veteran, I want my 1095-B document to be accessible (508 compliant)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#37764]

**Comment by tameracorson** [comment]
- [ ] Update base setting in PDF

**Comment by ashleycastillo** [comment]
Needs to be pushed to following sprint once we identify how to get access to XC document or original PDF from IRS in order to change the settings

**Comment by tameracorson** [comment]
Closing ticket in lieu of staging accessibility checklist
