### ISSUE TITLE
Access for Zachary Lewis Cloudwatch Dashboard Create

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#37778]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Zachary Lewis

### Your Email

zlewis@clarityinnovates.com

### Name of Your Team

Platform SRE

### Service(s) You Want Access To

AWS

### Desired AWS Access

I need the ability to create a Platform SRE Dashboard for planning, research and support.

username: Zachary.Lewis

ARN: arn:aws-us-gov:iam::008577686731:user/Zachary.Lewis

I get error:  There was an error while creating a new dashboard
To create a dashboard you need cloudwatch:PutDashboard permission.[Learn more.](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/dashboard-permissions-update.html)

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
Tagging @department-of-veterans-affairs/operations-aws-approvers. Note: this is a request for extension of existing permissions as Zach already has an AWS account.

**Comment by td-usds** [comment]
Elevation Approved

**Comment by jbritt1** [comment]
Permissions added as requested/approved.
