### ISSUE TITLE
[Campaign Landing Page] - VA VOTE

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37773]
## Description 

As part of VA.gov's Campaign Landing Page, the Veterans Experience Office (VEO) wants to launch a CLP in support of a an initiative to provide resources and information to Veterans on how to register to vote. 

## Key Info

**Who is Requesting**

- Requestor name: Tim Hudak
- VA organization: VEO
- Email address: timothy.hudak@va.gov

**Who is Creating the CLP**

- Requestor name: Melissa Bryant
- VA organization: VEO
- Email address: Melissa.bryant@va.gov

**About the Campaign**

- Name or focus of Campaign: Vote
- Target audience(s) [up to 3]:
   - Veterans
   - Families
   - Survivors 
- Goals of the Campaign:  
   - To provide resources and information to Veterans on how to register to vote.
- Campaign start and end dates: 
   - March 7, 2022 - 12/31/2022
- Campaign page target launch date: 
  - March 7, 2022 
- Preferred URL: 
   - www.va.gov/vote - va.gov/initiatives/vote
- Retirement strategy: This website is part of a pilot to establish a voter assistance program across the enterprise and the website will be retired at the conclusion of the pilot. A replacement permanent page will be established depending on the outcome of the pilot program. 

**Note:** the secretary is aware of this effort. They are hoping to launch by 3/7
## What Needs to Be Done

- [X] CMS: Set up the CLP page in CMS for Tim to use as his build template
- [x] Product: Get the Analytics dashboard set-up and UTM campaign code for Tim and his team
- [x] Product & IA: Validate that the requested URL -- www.va.gov/vote - va.gov/initiatives/vote --
- [ ] Product: coordinate with stakeholders and CMS team in support of launch strategy.

**Comment by xiongjaneg** [comment]
[Drupal prod link to CLP](https://prod.cms.va.gov/initiatives/vote)

**Comment by mnorthuis** [comment]
@brianalloyd the requested vanity URL is good to go.  I do not need a separate redirect ticket if you prefer to just do all work from this one, but you are welcome to open a separate one if you prefer.

**Comment by brianalloyd** [comment]
Thanks @mnorthuis appreciate the follow up and support. We'll keep this simple and manage the redirect from this ticket. Thanks again for the review.

**Comment by brianalloyd** [comment]
Cross linking out Analytics Ticket Here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37987

**Comment by brianalloyd** [comment]
Provided the latest update:

> Thanks for reaching out to validate the launch date. I am presenting this website to the Deputy Secretary and other senior leaders tomorrow, so I’ll need to push back the launch date until the language is final approved. I am also trying to triangulate our CLP launch with other moving pieces from the White House, so it may be as late as March 30th—but it will definitely be this month!
> I will keep this group apprised—please standby. Many thanks!
> 
> Melissa
> Melissa A. Bryant
> Deputy Assistant Secretary for Public Affairs
> Department of Veterans Affairs
> (m) 202-689-7810
> [melissa.bryant6@va.gov](mailto:melissa.bryant6@va.gov)

**Comment by davidconlon** [comment]
@LindaLi123 and @leahkeeler 
FYSA:  OPIA asked this morning: "Can anyone on this email confirm that VA.gov/vote has been established and ready for the launch? "

I included you on my response: 
"The last information I have is attached from 3/7 stating we were on hold and could be as late as 3/30.
Looking at the CMS it looks like the CLP was published on 3/18.

Do we have the green light to process the redirect from 
https://www.va.gov/vote to https://www.va.gov/initiatives/vote/

Waiting to hear. Documenting in issue

**Comment by davidconlon** [comment]
@LindaLi123 @leahkeeler 
Please move forward on the redirect.  We would like to have this operational today (3/21) so we can share with officials and stakeholders over the next couple days then promote widely on the 25th  via #VetResources

**Comment by LindaLi123** [comment]
@davidconlon  Waiting for analytics team to confirm the URLs and we’ll be able to close it out.
