### ISSUE TITLE
Re-architect tools/triage to backend/frontend tools

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3778]
Due to restructuring of VSP tools and triage teams, we must restructure the tools and triage areas of the `va.gov-team` repo to suit the needs of these users. 

### Definition of Done
- [x] Meet with tools and triage teams to conduct discovery of IA pain points and needs
- [ ] Define and propose IA for new areas to be used by legacy tools and triage teams (now frontend and backend tools)
- [ ] Implement restructured IA for frontend and backend tools teams and call centers content (previously part of triage team)

**Comment by thatmattjohnson** [comment]
Duplicates #3167; consolidating and closing this issue.
