### ISSUE TITLE
Access for Liz Lantz

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#37784]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Liz Lantz

### Your Email

liz.lantz@adhocteam.us

### Name of Your Team

VSA Authenticated Experience, UX Designer, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+4/gOhQ1N2jsALHpaZm9+2ZZV5fJNisQMpzF63mLR6bsw1LmaVIfZkGw8YYGW/0GoTICuVDLE2UPAEVAaUstEN98//WnpvUyZDhpiLTRRJLGA2ru4hUDmscLM8sU2ccVicvdf4Ekanwpc20wNndNann/EZmFC3JF8AiAxoZr1ay+xcOF0ZirZAuFlb3z7ave7rTaz1MhriYoJ4aqMT4JoYAPUXxbypnvm4HmfmifCJQ3GlevfEEkDVGYRyKSD+kehMWdvUaVO34ZYnlUQvc8kbXlWW5HCJMWX4LRoTSl6yXtrZUFv6vyIdd4G7GFTiQRroqqhJnlz06Tkz/Ixr7tc57gRyOT8jQ2YjKRoZsU0Vu8wbH8mAEo4phGSW3uiCK+IzThT4XXN3kyoCcj61xcZGNtnnIvNRofC1oLtPKbvAiU+ReyuZjlIMFxZ2G8eMw7W2/4KdkGVE3xgaTxlsawLXduj/1FyFjWcYUUOl1r1lgGROqJWu69qdvp6vGftqHU= elizabethlantz@ElizabeantzsMBP.attlocal.net

### Access Expiration

Ongoing

**Comment by rmtolmach** [comment]
@andaleliz 
Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
