### ISSUE TITLE
Access for William Gardner

### ISSUE THREAD

**Issue by allthesignals** [department-of-veterans-affairs/va.gov-team#37780]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

William Gardner

### Your Email

mattgardner@navapbc.com

### Name of Your Team

OCTO Benefits Delivery - Software engineer at Nava PBC

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDwy+Bks9K49G9hOF+CfT6+Q0N/UmzMEma3/4fH+qEXeWrO2Zdouk7nYA5fF3IkiW99R6T7SE20pGky9E+aoOAo0MgLR/jVJ8ODQjNMcX/Oil0F7q3MMX6XHjvOATHx2UJOekxlSoOalbdhFfb6O1tG5IdYhhlfc3IXntXwqLJ17nazpkC6Pm8BdyWEw8/Tegr9yuUkg6NCaxnZt24rD0l6uKjBZc3d47shs/3x7WxaPVw07y0K2JdHd5CS8fN0iOCKfay378bpciEUcGXnnG6Y06IkwBeAu/Wfs1gAmLmK9zG0dSnckCtiWw+Z/iD7IKIJAWUkEc77A6/yakN4AxZ1aAurIYIsv6vESdNEkRLpV2LA7p/UJMDcDu/1KzPCSt2Kt3ommTOP8E68JXqBuuXF9ZUrkpa2q5cQE9/tg9hPbDzRBe1c3jxUwKPa4xN8iPpxwhwVy2pjyRRmxruRizGV/yHIt73U3mcnzauseBfOamRPoGtexsTuWeV/KqRtDU0= mattgardner@Windows-Phone.localdomain

### Desired AWS Access

I need access to S3, where our team's software uploads generated pdfs for VMBS eFolder, to ensure files are correctly uploaded and the file contents are correctly formatted.

I also need SOCKS access for testing PRs.

### Access Expiration

ongoing

**Comment by mleclerc00** [comment]
## For AWS Access

User: William Gardner
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers

**Comment by mleclerc00** [comment]
Hello @allthesignals 


You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by mleclerc00** [comment]
Reopening for aws approval

**Comment by allthesignals** [comment]
Sorry about that!

**Comment by td-usds** [comment]
access approved

**Comment by mleclerc00** [comment]
@allthesignals can you provide the name of the s3 bucket you are looking to access?

**Comment by allthesignals** [comment]
@mleclerc00 Hi! I believe it's `dsva-vetsgov-prod-evss`. Same as @yoomlam for his [access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36133#issuecomment-1035113164). Thank you!

**Comment by mleclerc00** [comment]
@allthesignals, does Yoom currently have access to the bucket you are requesting with his permissions?

**Comment by allthesignals** [comment]
> @allthesignals, does Yoom currently have access to the bucket you are requesting with his permissions?

He does, yes — we're looking to have a fallback person in case of absence.

**Comment by allthesignals** [comment]
Hi @mleclerc00, sorry, I'm not sure if access was revoked but I'm now seeing this message in AWS:

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/5004319/163467278-3214c063-58cc-4258-a0fd-536d0503ba58.png">

Is there another step needed for getting s3:ListAllMyBuckets permission?

**Comment by jsgarmon** [comment]
Hi @allthesignals : you'll need to set up MFA in order to have permission to view anything. See the docs if you need help doing this:
https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781475/Set+up+your+AWS+Account

Once set up, you'll need to log out and log in again with MFA.

**Comment by allthesignals** [comment]
@jsgarmon woops! Amazing, thank you for the quick response. Got it resolved.
