### ISSUE TITLE
Login.gov production monitors (Datadog)

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37782]
# Description
Adds Login.gov monitors for Prod to Datadog:

# Acceptance Criteria (Engineer)
- [ ] Monitors Created
- [ ] Add Monitor to [this sheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Monitoring%20and%20Alerting/Monitors_Alerts_Datadog.md#identity---production-inbound-mhv-unified-sign-in-vagov-auto-sign-in-test-idme-)

# Deliverables (Product manager)
- [ ] Monitors Created
- [ ] Add Monitor to [this sheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Monitoring%20and%20Alerting/Monitors_Alerts_Datadog.md#identity---production-inbound-mhv-unified-sign-in-vagov-auto-sign-in-test-idme-)

**Comment by joeniquette** [comment]
These tests are covered in this ticket: https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/37966

Closing.
