### ISSUE TITLE
Define Design specific guidance for Design Intent

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#37799]
## User Story
As a UX Designer supporting the Governance team, I want to define how I review a product at Design Intent related to design, so that I can create a consistent approach with each future Design Intent and so I can set the framework for other practice areas within the Collaboration Cycle.

- Intended Audience: Governance Team
- Desired Outcome: Framework of how to perform a Design Intent for Design feedback
- Due Date: N/A

## Description
While working through the Research Plan Process, there was discussion around creating practice area specific guidance for each touchpoint. 
This is not intended to prescribe exactly how to review the feedback, this is intended to ensure that all practice areas are reviewing consistently.

## New Artifacts 
[Confluence: How to complete a Design Intent review: Design](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2104426655/How+to+complete+a+Design+Intent+review+Design)

## Acceptance Criteria
- [ ] Governance team Designers have determined "required tasks" to complete a Design Intent: Design review
- [ ] [Confluence: How to complete a Design Intent review: Design](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2104426655/How+to+complete+a+Design+Intent+review+Design) document has been created per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
this work was completed a while back. closing.
