### ISSUE TITLE
Restrict access to vets.gov-team and va.gov-vfs-teams (“shut down plan”)

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3779]
### Problem Statement

How might we leverage our ability to restrict access and permissions to legacy GitHub repositories to ensure that the new consolidated repos — `va.gov-team` and `va.gov-team-sensitive` — become the single source of truth for documentation on building on VA.gov moving forward?

**Comment by vbellissimo** [comment]
Cancelling/old task.
