### ISSUE TITLE
Define access restriction details and timeline for vets.gov-team

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3780]
### Definition of Done

- [x] Draft timeline of access restrictions (“shut down plan”) to vets.gov-team
- [x] Incorporate feedback of DEPO and VSP leadership into shut down plan
- [ ] Socialize and distribute the plan (present at ToT, distribute via Slack)

**Comment by vbellissimo** [comment]
Cancelling/old task.
