### ISSUE TITLE
[SW-Content] COVID-19 - Copyedit and publishing drupal pages and chatbot [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37811]
## Story
As a Veteran I need current and updated information for COVID-19 vaccines, so I can  find my best health care solution.

## Resources:

http://preview-prod.vfs.va.gov/preview?nodeId=11463

http://preview-prod.vfs.va.gov/preview?nodeId=34627

http://preview-prod.vfs.va.gov/preview?nodeId=34054

## Task(s)
- [x] Update and align Chatbot react widget
- [x] Copy edit and publish drupal pages

## Acceptance Criteria
* Pages are updated and published
* Chatbot updated and tested.

**Comment by RLHecht** [comment]
These pages have been reviewed and published and Selina updated the chatbot. Moving to validate.
