### ISSUE TITLE
Create and distribute post-launch survey to validate implementation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3782]
The goal of the MVP of the plain language linter is to prove that we’ve put it in a logical place in a VFS team member’s workflow. To do so we will gather qualitative data ~5 days after launch to assess whether any VFS team members have seen the plain language linter. Simultaneously, we are moving forward on implementing the ability to gather quantitative data to measure adoption of the tool — that will be tracked in a separate issue.

### Definition of Done
- [ ] MVP validation survey is drafted
- [ ] Target users (for distribution of survey) are identified
- [ ] Feedback from plain language linting team is incorporated into survey
- [ ] Survey is distributed to target users
- [ ] Results are synthesized and recorded in GH

**Comment by peggygannon** [comment]
@meganhkelley Do you think we should move this to the icebox?

**Comment by vbellissimo** [comment]
Cancelling/old task.
