### ISSUE TITLE
Remove Rachel Murray from DSVA Slack Channels

### ISSUE THREAD

**Issue by zinalpatel09** [department-of-veterans-affairs/va.gov-team#37823]
**Description of Request**

This request is to remove Rachel Murray from the following Channels in DVSA slack (do NOT remove her from DVSA slack space - only remove from channels):

- #health-care-products-all-teams
- #long-covid-public
- #long-covid-team

Rachel's email addresses are: Rachel.Murray1@va.gov and/or rachel.murray@thoughtworks.com

**Comment by LEHigley** [comment]
@zinalpatel09 did this get taken care of?

**Comment by zinalpatel09** [comment]
@LEHigley yes it did, thank you

**Comment by zinalpatel09** [comment]
@LEHigley, this issue is still open. I see that Rachel is in all the channels that I requested her to be removed from.

**Comment by LEHigley** [comment]
can't do long covid team looks like a private channel
