### ISSUE TITLE
Analytics Request for Mission Act Congress Report 2021

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#37824]
# Metrics Reporting Request Update

## Ticket Description
Need to update the Mission Act deck with 2021 metrics for annual report to Congress.  The objective of this deck is to answer how did Veterans and caregivers use community care information and how did they use/access the community care resources

Who is this request for?  
Mission Act Report to Congress
Need 2021 Updates - requested by Erica Robbins & Julia Badillo on behalf of Chris Johnston & Lauren Alexanderson

Deck from 2020 that needs updated with 2021 metrics:
https://dsva.slack.com/archives/C034LDRC99S/p1645730393527869

Sites/Pages/tools for report:

https://missionact.va.gov/
https://www.va.gov/health-care/eligibility/
https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/
https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction
https://www.va.gov/pittsburgh-health-care
https://www.va.gov/welcome-kit/

VAOS: https://www.va.gov/health-care/schedule-view-va-appointments/appointments
Facility Locator: https://www.va.gov/find-locations
-
**Product questions to think through if you're requesting new data features:**

- Who is your audience?  Congress
- Why do you need this data?  Mission Act must submit a report to Congress every year
- What area of the VA are you hoping to assess?  Community Care
- How frequently do you need this data?  Annually

**Comment by mmiddaugh** [comment]
**For Facility Locator**
Total 2021 Community care provider searches
- 2021 total unique Facility Locator searches = 5,570,641  
- 2021 unique Community care provider searches = 319,590 (5.74%)   

<details>
<summary>2021 Top 5 Community care searches </summary>

Service type (search term) | Corresponding NUCC code | Unique searches
-- | -- | --
Clinic/Center: Urgent Care | 261QU0200X | 25,165
Optometrist | 152W00000X | 16,780
Chiropractor | 111N00000X | 15,012
Clinic/Center: Primary Care | 261QP2300X | 14,719
Dentist | 122300000X | 12,106
</details>


<details>
<summary> Top 5 Community Care specialty searches by month </summary>

Month | Total unique searches of any type | Service type (search term) | Corresponding NUCC code | Unique searches(% of total)
-- | -- | -- | -- | --
January 2021 | 25,778 | Clinic/Center: Urgent care | 261QU0200X | 2,828(10.97%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,766(6.85%)
  |   | Optometrist | 152W00000X | 1,562(6.06%)
  |   | Chiropractor | 111N00000X | 1,202(4.66%)
  |   | Dentist | 122300000X | 881(3.42%)
February 2021 | 28,876 | Clinic/Center: Urgent care | 261QU0200X | 2,419(8.38%)
  |   | Optometrist | 152W00000X | 2,070(7.17%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,552(5.37%)
  |   | Chiropractor | 111N00000X | 1,460(5.06%)
  |   | Dentist | 122300000X | 1,093(3.79%)
March 2021 | 38,845 | Clinic/Center: Urgent care | 261QU0200X | 2,714(6.99%)
  |   | Optometrist | 152W00000X | 2,587(6.66%)
  |   | Chiropractor | 111N00000X | 1,788(4.60%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,545(3.98%)
  |   | Dentist | 122300000X | 1,392(3.58%)
April 2021 | 30,231 | Clinic/Center: Urgent care | 261QU0200X | 2,218(7.34%)
  |   | Optometrist | 152W00000X | 1,364(4.51%)
  |   | Chiropractor | 111N00000X | 1,218(4.03%)
  |   | Clinic/Center: Primary care | 261QP2300X | 945(3.13%)
  |   | Dentist | 122300000X | 855(2.83%)
May 2021 | 26,024 | Clinic/Center: Urgent care | 261QU0200X | 2,109(8.10%)
  |  | Internal Medicine: Clinical Cardiac Electrophysiology | 207RC0001X | 1,096(4.21%)
  |  | Optometrist | 152W00000X | 1,052(4.04%)
  |  | Chiropractor | 111N00000X | 991(3.81%)
  |  | Dentist | 122300000X | 847(3.25%)
June 2021 | 25,514 | Clinic/Center: Urgent care | 261QU0200X | 1,915(7.51%)
  |   | Optometrist | 152W00000X | 1,110(4.35%)
  |   | Chiropractor | 111N00000X | 1,007(3.95%)
  |   | Internal Medicine: Clinical Cardiac Electrophysiology | 207RC0001X | 937(3.67%)
  |   | Dentist | 122300000X | 878(3.44%)
July 2021 | 25,600 | Clinic/Center: Urgent care | 261QU0200X | 1,892(7.39%)
  |   | Optometrist | 152W00000X | 1,135(4.43%)
  |   | Chiropractor | 111N00000X | 1,053(4.11%)
  |   | Clinic/Center: Primary care | 261QP2300X | 954(3.73%)
  |   | Dentist | 122300000X | 876(3.42%)
August 2021 | 28,823 | Clinic/Center: Urgent care | 261QU0200X | 1,967(6.82%)
  |   | Optometrist | 152W00000X | 1,367(4.74%)
  |   | Chiropractor | 111N00000X | 1,237(4.29%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,073(3.72%)
  |   | Dentist | 122300000X | 920(3.19%)
September 2021 | 23,513 | Internal Medicine: Clinical Cardiac Electrophysiology | 261QU0200X | 2,078(8.84%)
  |   | Optometrist | 152W00000X | 1,260(5.36%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,255(5.34%)
  |   | Chiropractor | 111N00000X | 1,164(4.95%)
  |   | Dentist | 122300000X | 1,106(4.70%)
October 2021 | 22,380 | Clinic/Center: Urgent care | 261QU0200X | 1,652(7.38%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,287(5.75%)
  |   | Chiropractor | 111N00000X | 1,278(5.71%)
  |   | Optometrist | 152W00000X | 1,139(5.09%)
  |   | Dentist | 122300000X | 1,025(4.58%)
November 2021 | 22,211 | Clinic/Center: Urgent care | 261QU0200X | 1,634(7.36%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,380(6.21%)
  |   | Chiropractor | 111N00000X | 1,341(6.04%)
  |   | Dentist | 122300000X | 1,108(4.99%)
  |   | Optometrist | 152W00000X | 1,085(4.88%
December 2021 | 21,900 | Clinic/Center: Urgent care | 261QU0200X | 1,739(7.94%)
  |   | Clinic/Center: Primary care | 261QP2300X | 1,285(5.87%)
  |   | Chiropractor | 111N00000X | 1,273(5.81%)
  |   | Dentist | 122300000X | 1,125(5.14%)
  |   | Optometrist | 152W00000X | 1,049(4.79%)

</details>


<details>
<summary> 2021 urgent care searches by month </summary>

Service type definitions
- Community urgent care = returns community network providers only
- Urgent Care = returns VA urgent care locations only
- All in-network urgent care = returns single list containing community network providers + VA urgent care locations
- All Urgent Care = legacy pathway which is no longer available in UI


Month | Facility type | Service type | Unique searches
-- | -- | -- | --
January 2021 |   |   | Total = 55,831
  | Urgent care | All in-network urgent care | 34,461(61.72%)
  | Urgent care | Community urgent care | 19,037(34.10%)
  | Urgent care | Urgent Care | 1,998(3.58%)
  | Urgent care | All Urgent Care | 335(0.60%)
February 2021 |   |   | Total = 47,275
  | Urgent care | All in-network urgent care | 29,549(62.50%)
  | Urgent care | Community urgent care | 15,747(33.31%)
  | Urgent care | Urgent Care | 1,703(3.60%)
  | Urgent care | All Urgent Care | 276(0.58%)
March 2021 |   |   | Total = 51,652
  | Urgent care | All in-network urgent care | 32,281(62.50%)
  | Urgent care | Community urgent care | 17,439(33.76%)
  | Urgent care | Urgent Care | 1,671(3.24%)
  | Urgent care | All Urgent Care | 261(0.51%)
April 2021 |   |   | Total = 47,484
  | Urgent care | All in-network urgent care | 29,332(61.77%)
  | Urgent care | Community urgent care | 16,612(34.98%)
  | Urgent care | Urgent Care | 1,330(2.80%)
  | Urgent care | All Urgent Care | 210(0.44%)
May 2021 |   |   | Total = 46,336
  | Urgent care | All in-network urgent care | 29,244(63.11%)
  | Urgent care | Community urgent care | 15,552(33.56%)
  | Urgent care | Urgent Care | 1,336(2.88%)
  | Urgent care | All Urgent Care | 204(0.44%)
June 2021 |   |   | Total = 50,486
  | Urgent care | All in-network urgent care | 32,056(63.49%)
  | Urgent care | Community urgent care | 16,798(33.27%)
  | Urgent care | Urgent Care | 1,388(2.75%)
  | Urgent care | All Urgent Care | 244(0.48%)
July 2021 |   |   | Total = 53,087
  | Urgent care | All in-network urgent care | 33,539(63.18%)
  | Urgent care | Community urgent care | 17,932(33.78%)
  | Urgent care | Urgent Care | 1,389(2.62%)
  | Urgent care | All Urgent Care | 227(0.43%)
August 2021 |   |   | Total = 60,684
  | Urgent care | All in-network urgent care | 39,422(64.96%)
  | Urgent care | Community urgent care | 19,343(31.87%)
  | Urgent care | Urgent Care | 1,613(2.66%)
  | Urgent care | All Urgent Care | 306(0.50%)
September 2021 |   |   | Total = 56,161
  | Urgent care | All in-network urgent care | 38,925(69.31%)
  | Urgent care | Community urgent care | 15,019(26.74%)
  | Urgent care | Urgent Care | 1,756(3.13%)
  | Urgent care | All Urgent Care | 461(0.82%)
October 2021 |   |   | Total = 54,745
  | Urgent care | All in-network urgent care | 40,051(73.16%)
  | Urgent care | Community urgent care | 12,802(23.38%)
  | Urgent care | Urgent Care | 1,482(2.71%)
  | Urgent care | All Urgent Care | 410(0.75%)
November 2021 |   |   | Total = 55,158
  | Urgent care | All in-network urgent care | 40,483(73.39%)
  | Urgent care | Community urgent care | 12,782(23.17%)
  | Urgent care | Urgent Care | 1,483(2.69%)
  | Urgent care | All Urgent Care | 410(0.74%)
December 2021 |   |   | Total = 64,270
  | Urgent care | All in-network urgent care | 47,931(74.58%)
  | Urgent care | Community urgent care | 14,306(22.26%)
  | Urgent care | Urgent Care | 1,541(2.40%)
  | Urgent care | All Urgent Care | 492(0.77%)

</details>


<details>
<summary> Click through on CTA to learn about in-network urgent care benefits </summary>

Month | Unique clicks
-- | --
January 2021 | 0
February 2021 | 0
March 2021 | 0
April 2021 | 0
May 2021 | 0
June 2021 | 0
July 2021 | 0
August 2021 | 1495
September 2021 | 6044
October 2021 | 5602
November 2021 | 5542
December 2021 | 6728
</details>

<details>
<summary>2021 Community pharmacy care pharmacy searches by month </summary>

Legacy pathways 
- Community care providers + Pharmacy: Community/Retail Pharmacy 
- Community care providers + Pharmacy 
- Community care providers + Compounding pharmacy 
- Community care providers + Specialty pharmacy 
- Community care providers + MCO pharmacy 
- Community care providers + Mail order pharmacy 

Month | Facility type = Pharmacy | Community care providers + Pharmacy: Community/Retail Pharmacy (3336C0003X) | Community care providers + Pharmacy (3336C0002X) | Community care providers + Compounding pharmacy (3336C0004X) | Community care providers + Specialty pharmacy (3336S0011X) | Community care providers + MCO pharmacy (3336M0003X) | Community care providers + Mail order pharmacy (3336M0002X)
-- | -- | -- | -- | -- | -- | -- | --
January 2021 | 14,230 | 74 | 10 | 1 | 0 | 3 | 0
February 2021 | 13767 | 55 | 8 | 0 | 1 | 0 | 1
March 2021 | 14743 | 92 | 9 | 2 | 2 | 1 | 0
April 2021 | 11703 | 64 | 1 | 1 | 0 | 0 | 0
May 2021 | 11250 | 62 | 2 | 1 | 0 | 1 | 1
June 2021 | 11677 | 77 | 2 | 0 | 1 | 0 | 0
July 2021 | 12248 | 62 | 2 | 0 | 2 | 0 | 1
August 2021 | 14100 | 37 | 4 | 0 | 5 | 0 | 0
September 2021 | 20505 | 61 | 12 | 1 | 4 | 0 | 1
October 2021 | 24930 | 94 | 10 | 0 | 0 | 0 | 3
November 2021 | 17576 | 53 | 4 | 1 | 0 | 0 | 1
December 2021 | 17542 | 55 | 12 | 0 | 1 | 0 | 0


</details>

**Comment by bsmartin-ep** [comment]
Mission Act (2021) dashboard can be accessed:

https://va-gov.domo.com/page/1865233622
