### ISSUE TITLE
[BE] | Discovery | Identify Back-end Impacts to 10-10EZ Short-form

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#37822]
## Description

The 10-10EZ short-form will enable both authenticated and unauthenticated Veterans with a disability rating of 50% or higher, to bypass sections of the application form. 

This ticket is to determine what (if any) changes will need to be made on the back-end prior to submission of the shortened form to ensure the form can still be submitted successfully.

(Note: we are only sending what is filled out on the form prior to submission so will not be pulling in any of the "skipped" data).

## Acceptance Criteria

The attached spreadsheet details the fields that will no longer need to be filled out with the implementation of Phase 1 of the Short-form for authenticated and non-authenticated applicants.

- [ ] Test the fields in columns D + E  ("Phase 1") and note which, if any, will cause an error if omitted when submitting the application (this can be tested in the lower environments SQA + Pre-prod).

[https://app.zenhub.com/files/133843125/c2ada4ce-c282-404c-a9b6-f9fe8c501787/download](https://app.zenhub.com/files/133843125/c2ada4ce-c282-404c-a9b6-f9fe8c501787/download)

**Comment by SKasimow** [comment]
Dene is going to designate what fields are optional vs required and then BE dev can start this ticket.

**Comment by SKasimow** [comment]
[https://app.zenhub.com/files/133843125/d774e537-1ddb-42a0-82b5-0ff26b5fa741/download](https://app.zenhub.com/files/133843125/d774e537-1ddb-42a0-82b5-0ff26b5fa741/download)

**Comment by lihanli** [comment]
of all the fields that are no longer required for the short form, only the medicaid field produces an HCA API error when it is not present

```xml
<?xml version="1.0" encoding="UTF-8"?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
  <S:Body>
    <ns0:Fault xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.w3.org/2003/05/soap-envelope">
      <faultcode>ns0:Server</faultcode>
      <faultstring>formSubmissionException</faultstring>
      <detail>
        <VoaFaultException xmlns="http://va.gov/schema/esr/voa/v1" xmlns:ns0="http://jaxws.webservices.esr.med.va.gov/schemas">
          <faultExceptions>
            <faultException>
              <code>VOA_0068</code>
              <message>Missing Required Field: Medicaid eligibility.</message>
            </faultException>
          </faultExceptions>
        </VoaFaultException>
      </detail>
    </ns0:Fault>
  </S:Body>
</S:Envelope>
```
