### ISSUE TITLE
Wrong event instance for recurring event showing on event listing page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#37833]
## What happened?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/643678/156202106-7b9edca4-a172-4bd0-ae0e-fb18bd23b8c1.png)

</details>

## Steps to Reproduce
1. Go to https://web-5kfpv6vznchkcxw4bgycflzjjodfbtbe.ci.cms.va.gov/pittsburgh-health-care/events/ 
2. See that the last instance of https://web-5kfpv6vznchkcxw4bgycflzjjodfbtbe.ci.cms.va.gov/pittsburgh-health-care/events/44034/ shows up, instead of the first instance

## Acceptance Criteria
- [ ] Recurring events show on event listing page based on their most upcoming (next) instance, not the last instance. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jilladams** [comment]
Since https://github.com/department-of-veterans-affairs/content-build/pull/1025 merged, can this ticket be closed?
