### ISSUE TITLE
Business intake form for eScreening

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#37838]
## Requestor Name
Angela Gant-Curtis

## Business Line
eScreening

A web app that allows medical centers and programs to create assessments or surveys. National assessments or ad hoc (care and treatment follow-ups). Can access eScreening remotely (due to covid/pandemic). They have an email that already sends for this.

Each medical center has its own eScreening application. Long term it would be good for the centers to be able to manage their own, but short term it’ll be centralized content.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 

It’s being sent by email, they are going to start with text for now. Long term it would be good to absorb email as well to notify by email or text based on preference.

## What kind of notification would this be? (required Email, Text, Not sure)

Text. Going to start with Eastern Colorado – need to get an area code for that.

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 

Rajashree can dig into the eScreening code to figure out the trigger.

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 

Yes there are already events being triggered for email

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)

Will need to get ICN from Vista

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)

This will be under OCTO

## What is your estimated volume of notifications per day, week, month? (optional - open space)

Angela will look into email load that’s going out now so we can get an idea for text.

## When does this notification need to be in production? (optional - open space)

No commitments yet

**Comment by mjones-oddball** [comment]
Service and api keys exist and were sent to Rajashree.

**Comment by bevnobev** [comment]
duplicate
