### ISSUE TITLE
[vets-api-file-upload] - Application onboarding infrastructure request

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#37839]
## Summary
The purpose of this template is to capture requirements for onboarding a software application to the Platform's delivery infrastructure. 

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

### Guidance
- Please fill out the sections below with as much info as possible 
- If you don't have info or know the answer to a given prompt, _it's okay to leave it blank_
- The Infrastructure Team will assist you with gathering requirements _and_ performing key setup and configuration tasks 

---

## Description of application
_Please provide a brief description of the application, ie What does it do? Who does it serve?_

### Basic info:
**Team Name:**   
_"Integration Experience - Platform Spike Team" (GitHub team: platform-pst-iet)_
**Application Name:**  
_"File Upload" (GitHub repo: vets-api-file-upload)_  
**Functionality:**  
_"Microservice to manage S3 file upload for binary data directly to the signed URL"_  
**Language/Stack:**  
_"Ruby on Rails"_  
**Ports/Networking needed:**  
_ie "80, 443" for standard HTTP and HTTPS_    
**Other infrastructure needed:**  
_"S3, Lambda, Monitoring for Logs, Metrics, and Error Traces"_  
Preferred name for S3 bucket to be created: **vets-api-file-upload-s3-dev**

### Background/Context/Resources
_The need and purpose of the application is to centralize file upload code and establish Platform ownership over the upload process, starting from the [current sprint](https://vfs.atlassian.net/wiki/spaces/IET/pages/2092367967/Sprint+11+Goals)_

### Technical Notes
_Additional technical info that describes the desired setup and configuration can be found in [IET Confluence](https://vfs.atlassian.net/wiki/spaces/IET/pages/2102624451/S3+file+uploading+process)_

---

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] **GitHub repo:** _[vets-api-file-upload](https://github.com/department-of-veterans-affairs/vets-api-file-upload)_  
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   
_Requesting team; Infrastructure Team can assist_  
- [x] **Dockerfile:** _[Dockerfile](https://github.com/department-of-veterans-affairs/vets-api-file-upload/blob/main/app0/Dockerfile)_ | [Example](https://github.com/department-of-veterans-affairs/platform-console-api/blob/master/Dockerfile) | [Docs](https://docs.docker.com/engine/reference/builder/)  
_Requesting team; Infrastructure Team can assist_  

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions**, ie `svc-gha-team-name` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS Elastic Container Registry (ECR) repository for the app container:** _provide name of ECR repo here_  
_Infrastructure Team_ | [PR #10820 ](https://github.com/department-of-veterans-affairs/devops/pull/10820)  
- [ ] **Automation to release and tag the app's GitHub repo with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team; Infrastructure Team can assist_  
- [ ] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation. 
_Requesting team; Infrastructure Team can assist_  
- [ ] **Kubernetes manifest in YAML, Jsonnet, or Helm Chart** in `vsp-infra-application-manifests` [PR #388](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/388) | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps) | [Docs](https://argo-cd.readthedocs.io/en/stable/)  
Note: must be compatible with ArgoCD  
_Requesting team; Infrastructure Team can assist_  
- [ ] **Automation to update the Kubernetes manifest** when a new version of the app's container is pushed to ECR | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/update-manifests.yaml)  
_Requesting team; Infrastructure Team can assist_

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** ie `/dsva-vagov/team-name/` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS SSM Parameter Store parameters that the app needs to run,** ie `/dsva-vagov/team-name/env/secret-name` | [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)  
_Requesting team_

---

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by jsgarmon** [comment]
@considerable : please as `vsp-operations` as admins on the `vets-api-file-upload` repo so we can add GitHub secrets for AWS credentials.

**Comment by considerable** [comment]
@jsgarmon :  team vsp-operations is in admins now.

**Comment by oseasmoran73** [comment]
> Preferred name for S3 bucket to be created: vets-api-file-upload-s3-dev

Marking for visibility as resource section was recently updated. See [slack](https://dsva.slack.com/archives/CJYRZK2HH/p1646758437455449) thread for more details

**Comment by jsgarmon** [comment]
secrets have been added to the [vets-api-file-upload repo](https://github.com/department-of-veterans-affairs/vets-api-file-upload)

**Comment by jsgarmon** [comment]
@considerable : you should be good to test your CI pipeline. I noticed you have a `--build-arg s3_bucket=${{ secrets.S3_BUCKET }}` line in your GitHub action, though no ARG for s3_bucket in your dockerfile. Regardless, you'll want a different bucket for each environment, so you'll want to set that at deploy only, as you've done in [your PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/388/commits/46d38364c791b149bf5718c295523befc38747fd).

The bucket `dsva-vagov-dev-vets-api-file-upload` has been created for you to test your app in dev.

**Comment by considerable** [comment]
These PRs have to do with S3 permissions:
https://github.com/department-of-veterans-affairs/devops/pull/10977
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/457/files

**Comment by ewilson-adhoc** [comment]
We have deployed a basic applications into development, closing this for now.
