### ISSUE TITLE
Access for Angela Agosto

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#37857]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Other

### Your Name

Angela Agosto

### Your Email

angela.agosto@adhocteam.us

### Name of Your Team

VSA - Senior UX Designer 2 - Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlRorODFx9BK0IXj4L2bFr4GZqz2Zn0gCRsJGcc1iYMROICyzRgj63iFALdKMUZ8A+XGBoAkrXWfWcDvqHdWTEYn9OfaGEM8H5O1hh6fNgnJWhcKDQcTM99DQeE39FFRavAzv+InulSpiKYCKEJ9exrSeTDUgy2Bj95MqYsFrY/H3LIFfz15c5niPUmCE2gJ5dXykrzOhvkR45Xs883nr+wmcqUYFy7nY7bcNeN9O9y8ga6uvsDfjM8YJ42nI2bPB6injpc26ARv1dqGGlFhhImYSHmaCsnXF8qDnNlD1riRnE/o0XKCuDkJoaYLmhPdnHhcMlYIf/m/bSCGD9cbcBV3yDPI5NYPicBeC0S3R/FFlzXZzxaN4GMGXmuxjjGBK+0Lsy2ClSiBUFdzGNb41Z/TW9rbf/Fdw7OdKqw2sSu0n2Z0Y8KAc845mPIkH5ZKu+S2taZ4esMJ45gp1TfgjTeShbJS9TgDmLiU9z5whxYsjmLlGSSVhpXb64hWFvD20= angelaagosto@AngelaAgostoMBP.fios-router.home

### Access Expiration

ongoing

**Comment by aagosto90** [comment]
Vendor Onboarding Representative Name: Valene Dallos (GovCIO)

**Comment by rmtolmach** [comment]
@aagosto90 
Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
