### ISSUE TITLE
Update Synthetic Monitor Playbook

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#37851]
# Description
Platform engineers need to be able to understand what they should do if a Datadog hosted synthetic monitor is triggering an alert.

## Tasks
- [x] Create a new synthetic monitor playbook that describes how to detect, respond to, and resolve a PagerDuty alert resulting from a synthetic monitor failing

## Acceptance Criteria
- [x] Updated playbook has been published to our [internal use Confluence space](https://vfs.atlassian.net/wiki/spaces/TTT/pages/1848999954/OnCall+Playbook+for+Handling+Canary+Alerts)

**Comment by rbeckwith-oddball** [comment]
Since it will essentially be new documentation, estimating a 2

**Comment by pjhill** [comment]
Hey @rbeckwith-oddball , is the document that you're almost done with prescribing the use of Datadog to create a monitor, or is this for AWS Canaries?

**Comment by rbeckwith-oddball** [comment]
Documentation for the existing canary monitors can be found [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2132836394/Synthetic+Monitors+-+AWS+Canaries). Since it isn't technically a how-to, and since we're moving away from AWS canaries, the page can likely be archived or moved to a more appropriate location.

**Comment by pjhill** [comment]
I believe that for this ticket, we need something more like an update to [this document](https://vfs.atlassian.net/wiki/spaces/TTT/pages/1848999954/OnCall+Playbook+for+Handling+Canary+Alerts) for the AWS Cloudwatch version that indicates how the SREs need to interact with and resolve issues with the Datadog version of the monitors.

**Comment by rbeckwith-oddball** [comment]
How-to page is in progress [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2164785226/Synthetic+Monitoring)

**Comment by JoeTice** [comment]
Update Playbook based on feedback Peter provided: https://vfs.atlassian.net/wiki/spaces/TTT/pages/1848999954/On-Call+Playbook+for+Handling+Synthetic+Monitor+Alerts

**Comment by pjhill** [comment]
This looks good. We may have to make some updates to reflect a slightly altered alerting scheme in the near future, but we can close this and work that under a new ticket if necessary.
