### ISSUE TITLE
Update Grafana App Manifest for Keycloak Auth

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37859]
We need to add an Auth Generic Config to the Grafana Application Manifest in the Application Manifest Repo

In Line 38 [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/grafana/values.yaml)
 - Add a new section for keycloak (auth.generic)
 - Make a PR in the application manifest
 - Integrate Grafana with Keycloak

**Task is done when:**
- [ ] I can log into Grafana using Login.gov via Keycloak

**Comment by calquisola** [comment]
[PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/669) created.
