### ISSUE TITLE
Confirm Grafana Integration in Utility

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37861]
## Confirm Integration
The Grafana integration must be reviewed before it can be released.
It must pass the "Launch Checklist" outlined in #37856

right now we're using a test instance. we need to **be in prod with login.gov** to complete this

**Task is done when:**
Anyone can log in to grafana with login.gov

**Comment by kjduensing** [comment]
A must-do.
