### ISSUE TITLE
Create CI process that builds and pushes Keycloak container to ECR and tags appropriately

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37863]
This needs to be able to modify the (values-utility.yaml) app manifest

**Task is done when:**
App manifest can be updated automatically by CI process in github actions console

**Comment by dginther** [comment]
New CI processes which run separately for each version of Keycloak are created: https://github.com/department-of-veterans-affairs/pst-amt-keycloak/tree/main/.github/workflows

Please see the README.md for details on how this works: https://github.com/department-of-veterans-affairs/pst-amt-keycloak/blob/main/README.md
