### ISSUE TITLE
New Docker File in keycloak repo

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37862]
The current container in utility is a oneoff, if we update to a new container we will need to update anyway.

File should use code centric version 16 base until we're familiar with 17

**Task is done when:*** 
An automated container build is stored in ECR

**Comment by dginther** [comment]
Dockerfiles added for dev, next, and utility keycloak, as well as separate .env files.
Please see the README.md for details: https://github.com/department-of-veterans-affairs/pst-amt-keycloak/blob/main/README.md
![Screen Shot 2022-03-14 at 12.07.49 PM.png](https://images.zenhubusercontent.com/5ce30eebaa8711267b95ebdf/97787f71-d166-4cee-95be-7a43a28edad7)
