### ISSUE TITLE
Access for Alex Taker

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/va.gov-team#37874]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Alex Taker

### Your Email

alex.taker@adhocteam.us

### Name of Your Team

Console UI, Senior Software Engineer, AdHoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkeCrLukKtOdvP1uWjY+DSIsibov6EQ+vZ8o+0Zt0p6ooTzabxawDsEfk2KkgjPDMeCjUykKbt5kY4Hb8FiLbxyquKYg1CbJelTYIJpuF5D0hBUzDdBA9o3IxMlXPTxTpg9SIIjKypbcKlZCM6j32IF7d715xcoM3LqJ4I81qrRsDmozNZo+ncK7B562CodTkU6iYuY/hk9BRChHvNN2uSQZtMPucFJYFezlzwzW9HlUIj23ZWY1FTc8vzK4/ueiexGojNhkmawPdFqOi6hzgDx5JEnxCCCi5qIoR156AtLJ2BsRaGkCtLZtAb/06SpgeA3ajLiY0zesLvrKWd/goC7k63R+Or5W7YbesrtmwWSaZSWBeeZKEp+vPiaL6xLOO/gv3IzBUbjIVZm4AK4KqY/iY3+9LwdNffkPVRyYL0FYIBKYkgEQx6MuQfgOJAeKjWQi/rBhsAJ6UB7qqNxw5xJvWv1WFhb9EWbknCqlwJexGCxd52aYOk5L61JtS/DjM= alextaker@Alex-Taker-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
@ataker 
Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
