### ISSUE TITLE
[Ongoing Service]VSP ATO - Ensure we stay compliant. 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3787]
## User Story and Problem Statement
As a member of VFS and VSP, I want our ATO to stay correct and compliant, so that VFS and VSP teams can continue to help Veterans on VA.gov 

### High Level User Story/ies
These tasks are for ensuring we keep our ATO in place. 

## VSP Objective (Q1 & Q2 2020)
O3: Stability and resiliency of the Platform's systems and teams continue to improve.
 
## Measuring Success (KRs/KPIs)
- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month

**Comment by jhouse-solvd** [comment]
Need to apply latest initiative template so that information is captured in the right format.

**Comment by jhouse-solvd** [comment]
Need to update this with more recent platform objective info as well as tickets that are being worked on.

**Comment by jhouse-solvd** [comment]
@troymosher - This is a longstanding, ongoing service that the Operations team was performing. It would be good to check in on where we sit with this given the recent re-organization and the responsibilities taken on by the Security team. 

It may be useful to you in understanding some of the past tasks over the past couple of years. 

I'm trying to make a determination as to what the Infrastructure team's role will be with respect to ATO.

**Comment by jbritt1** [comment]
@troymosher, can you weigh in on this one as time allows please sir? Is this an ongoing epic we need to keep on our board? Or is this something that should transition to the Security team board with the understanding that we will need to implement solutions deemed necessary by the Security team in order to stay ATO compliant?

**Comment by jbritt1** [comment]
Bump

**Comment by jbritt1** [comment]
Bump

**Comment by troymosher** [comment]
@jbritt1 this can be closed.  We have all the ATO tasks on our board.

**Comment by jbritt1** [comment]
> @jbritt1 this can be closed. We have all the ATO tasks on our board.

Beautiful! Thanks for letting me know @troymosher.
