### ISSUE TITLE
AWS Staging: Preferred Provider information missing for CC request 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#37906]
## What happened?
Provider information is missing from the "Review your appointment details" page and request card for VAOS service test users.

## Steps to Reproduce
- Login to VAOS as a any test user (Ex:- grethel.g.petryniec@id.me)
- Follow the steps to create a request for CC supported type of care (Eg:- Optometry, Food and Nutrition, Primary Care etc.)
- Choose a provider from the list and click on continue
- Fill in the required fields to enter a CC request

Expected Results: Provider information should display on the "Review your appointment detail" page and Request card details

Actual Results: Both "Review your appointment detail" page and Request card details display as "No provider selected"

![Capture](https://user-images.githubusercontent.com/69315717/156422257-18ceeb80-a654-4986-a8c7-118259736474.PNG)

**Comment by grossb1** [comment]
Closing this following ticket as a dup
https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/38689

**Comment by cferris32** [comment]
https://issues.mobilehealth.va.gov/browse/VAOSR-3163

**Comment by cferris32** [comment]
This ticket needs to be done after this work: https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39145

**Comment by ldelacosta** [comment]
@cferris32 - Since #39145 is done and closed, can we move this ticket back to Ready/In Progress to resume the work? Please let me know when you have a chance.

**Comment by cferris32** [comment]
@ldelacosta  I believe our API response returns all the provider data we need now, and it can be surfaced to the webpage. So we should be good to unblock this ticket.

**Comment by marcynadeau** [comment]
@ldelacosta Is this ticket ready for testing?

**Comment by ldelacosta** [comment]
@marcynadeau - Please validate this ticket. Thanks!

**Comment by marcynadeau** [comment]
assigned to Beth for testing.  @beth-wodzinski

**Comment by aarathi-poldass** [comment]
Due to [VAOSR-3611](https://issues.mobilehealth.va.gov/browse/VAOSR-3611) this ticket cant be tested at this time. Current the VAOS BE team is working with the HSRM team to investigate the delays on their side.

**Comment by aarathi-poldass** [comment]
Re-teste the ticket and it failed validated. The preferred provider information is still displayed under "Review your appointment detail" page and "Request card" details. @ldelacosta can you please assign this ticket back to the developer for further analysis. Please find attached screenshots for reference.  

![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/085e5af5-7741-4c69-89e7-dcaafd0e9e46)

**Comment by ldelacosta** [comment]
Re-assigned back to @cferris32

**Comment by ldelacosta** [comment]
@cferris32 
VAOSR-3611 is done. Do we need additional backend work? Or can we move the ticket back to validate for additional testing?

**Comment by cferris32** [comment]
We will need to wait on VAOSR-3636 to be dev complete before finishing the work on our side for this ticket

**Comment by ldelacosta** [comment]
This ticket will be re-tested after the work is completed in #36913

**Comment by marcynadeau** [comment]
This is currently blocked by VAOSR-3700.  https://issues.mobilehealth.va.gov/browse/VAOSR-3700

**Comment by aarathi-poldass** [comment]
Failed validated preferred provider information is still missing on the missing on "Review your appointment detail" page and "Request card". Validated the above steps with multiple test users, multiple type of care and seeing the same results. Please find attached a screenshot for reference. @ldelacosta 

![image](https://user-images.githubusercontent.com/69315717/171255083-dad9381a-9dc1-453b-9fa1-c8d6e4c396b8.png)

**Comment by jenniemc** [comment]
Display just the provider/practice name; no need to show address when it is at pending status. This ticket is a dup for #42146 cc: @marcynadeau , @aarathi-poldass

**Comment by aarathi-poldass** [comment]
This ticket can't be tested due to an outstanding issues with PPMS provider search [VAOSR-3976](https://issues.mobilehealth.va.gov/browse/VAOSR-3976) once the issue had been addressed I can test this defect.

**Comment by aarathi-poldass** [comment]
@ldelacosta @JRRoof @jenniemc Validation Failed - Preferred provider name is still missing on the "Review your appointment detail" page. Validated the above steps with multiple test users, multiple type of care and seeing the same result. Please find attached a screenshot for reference.
 
![GitHub](https://user-images.githubusercontent.com/69315717/178040616-a30b7e74-6b93-4c1c-b1b0-b3d6d1e09ae0.png)

**Comment by ldelacosta** [comment]
@jenniemc - I was able to validate the provider's info in #42146 for patient999. Not sure if something had happened after this validation.

**Comment by marcynadeau** [comment]
@ldelacosta @aarathi-poldass This was tested and passed testing.  Also note that provider on past requests is also now displaying.  You can close the defect.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
