### ISSUE TITLE
Access for Kerry Powell

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#37911]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Kerry Powell

### Your Email

kerry.powell@adhocteam.us

### Name of Your Team

Platform SRE

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBgBTWoe+zwuZnlnvBDh9oB6BCsIARsc5hqU6WwtsLsTsISbLWEq8EMvKLGkX4MmxOC4WYhxX2UX4/tcuW5SBm8FZMX0OQfC+kq9IHTK7JY0T3A9Md8mJMapcd+XEg5hSDjydVRDYucixVDqOZkWaTZK6iLghdCUXV1/tsqWzlzFZz3q4mFeholNp+litNqDdEI87j6VZCBBeVL204urLUZzVQ/Q/M5vqlTYv71XpTi8hMUn+hRWPqsaZOlQeGWJ2rPtLy+C/3r8Kh1vSfH6ccGjBn2Dl6HJkgx6aliBacVcDMOtThFHCPM97aDYlIJjc2VBZx89hwa3RshUBkSxS+6ttAL9LBrgG7OSkAWNF5Nq/XNEjQ5yokV5pHNOiXCEAjhi8CEpPF2jAhl/QfBWFHDNzxyC+0vzX2EBQWVBuyW+EkIPb1oA0UyvmL1RZ+P607biGR9CScxP5fTn/cPawZ9er/X3d75p/cp3SlYDuFFUVV6/EWXYjm1VHPvS18Xpc= kerrypowell@Kerry-Powell-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
@powellkerry 
Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
