### ISSUE TITLE
Test Selection for Changed Apps Only Builds in Master

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#37921]
# Description
In order to accommodate the switch to changed apps only builds for the CI workflow running against master, we need to make some updates to the CI workflow config in GHA. 

1. When building an app from the approved list in master, execute only the Cypress tests that are associated with the app.
2. When building an app from the approved list in master, collect the changed files from only the most recent commit in order to get an accurate assessment of the changes for test selection.

[Link ](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2104131615/DRAFT+Revise+Cypress+Test+Selection+for+Changed+Apps+Only+Builds)to ADR for reference.
[Changed apps build and approved list description for reference](https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/2031484979?draftShareId=7f53e7cf-225a-45ab-a379-b2a16cb468a7).
Here's an example of [retrieving the files changed in a commit](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/e2e-tests.yml#L55-L57) from the new E2E flow.

## Acceptance Criteria
- [ ] Master builds that are triggered by changes to an app on the approved list only run the Cypress tests associated with that app
- [ ] Master builds compare only the changes in the squashed commit being merged instead of the branch being merged

**Comment by ddzz** [comment]
WIP branch: https://github.com/department-of-veterans-affairs/vets-website/compare/test-selection-master?expand=1

**Comment by ddzz** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20413

**Comment by ddzz** [comment]
The PR is ready for review, just waiting for approvals.

**Comment by pjhill** [comment]
Hooray -- nice job, and thanks for switching contexts to this task so quickly.
