### ISSUE TITLE
Access for Kyle Soskin

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#37936]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kyle Soskin

### Your Email

kyle.soskin@adhocteam.us

### Name of Your Team

Name of Team: PTEMS: Platform Spike Team - Access Managment, Role: Software Engineer, Company: Ad Hoc Team LLC

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqzFXuX/NKYYEpddN3VhEeWQDm5ZP0IOaTUBTSHIxMzByoeUnITU2fMNE39MZDhkqXWiZpdB2V6ZID+uUjwYDgWMmbelHXbAObRJq1H5HIYnGQkJpd74xuaIWHIFxqZME/gh4XpNJn8EMoYCk9fE6fZG7Q2bKxr39dE9h8itSNd0aFA56FiwibOjoyt5SHNhHgti6c2VJeE9HMS0PeNwUJiIQn4ewTymd7n/ke1rr4KGEt/RDIaX434PzMCEkR5K3XAUu2bbbq3aleAxbfsMSG5B60aBIcJrBztT2Dqa+i2tTyNh+m0LPl64NMWXJw9BzGwuXvX8aJEO4Zzs2DgwMtMNm5mie70aV/bmG5J7tioUJLghzhvLvOQVZswCe9jdBO4tqaTdDNNb1Wz51IWRgSbtx9UrZRNx3vwySxfqRMeLihkuphZ1TrqHfHs3DI4VXrKd6HMC4AHtY1u5j+N0cU5E8PgLUFz+mqdr5tHmyDzY44wliRiYUPcYubn581baM= kylesoskin@Kyle-Soskin-MacBook-Pro.local

### Desired AWS Access

Whatever access "Kevin Duensing" and "Carl Alquisola" have. 

Mostly need to be able to access dev and utility env from what I have gathered. Specifically anything related to the keycloak instances they are standing up and any surrounding AWS components. 

I can get more specific info if required.

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
SOCKS access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.

Please leave this ticket open until we're able to give you AWS access.

**Comment by jsgarmon** [comment]
### For AWS Access
User: Kyle Soskin
COR: Courtney Bethea
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: [@department-of-veterans-affairs/operations-aws-approvers](https://github.com/department-of-veterans-affairs/operations-aws-approvers)
Admin level: no

**Comment by td-usds** [comment]
AWS access approved

**Comment by jsgarmon** [comment]
User added, first-time login instructions sent.
