### ISSUE TITLE
Discovery: Explore options for collecting metrics on Design System CSS class usage

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#37934]
## Description
We would like to find a way to track Design System CSS class usage in the `vets-website` and `content-build` repositories. We have two goals with this data collection:
1. Measure the usage of these classes similar to the way we measure the usage of Design System components
2. Surface classes that that get used together or in close proximity to one another on a frequent basis to help us determine where a new component might be useful.

## Details
- Take a look at what we are doing with measuring component usage in the [design-system-dashboard-cli](https://github.com/department-of-veterans-affairs/design-system-dashboard-cli) repo.
- We may not want to track _all_ of our CSS classes. It might be good to identify a few key classes we'd like to start with.
- Finding classes that are used together or in close proximity to one another is going to be tricky. What we're looking for here are ideas for how we might go about this.
- Timebox this discovery to three days.

## Acceptance Criteria
- [ ] Explore methods for accomplishing the goals laid out above. Add your findings as a comment on this ticket.
- [ ] Discuss findings with the DST engineers

**Comment by pdavies88** [comment]
@k80bowman moving this into QA/Review to chat about during a Monday meeting

**Comment by k80bowman** [comment]
Action items from engineering discussion:
- Look into Stylelint to identify where we can use a component to replace a CSS class from this ticket with the component and see if that is valuable to help with migration. 
- For those that don’t have a component look into potentially adding to the Web Components with the CSS classes that are in use.
- Look into creating a measurement for the utility classes (vads-*) using categories and try to collect that as granular as possible. Need to figure out if total number count or line graph would be better to present the data. Potentially each app would be a bucket that we would look into to determine the usage.
