### ISSUE TITLE
Setup workflow protection for the daily production deploy in vets-website and content-build

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#37939]
## Description

Currently, anyone added to the organization as a contributor can manually trigger a production deploy with the [daily-production-deploy workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/daily-deploy-production.yml). This is something we do not want to allow since there is a [deployment process/policy](https://depo-platform-documentation.scrollhelp.site/support/Deployment-Policies.1279787009.html) in place right now.

I reached out to Github and while there isn't a solution to hide the "run workflow" button the UI, we can restrict it to teams programmatically. [Read more on the Slack thread](https://dsva.slack.com/archives/CU1E4CX9U/p1646253758917859).

This should probably be restricted to [vsp-frontend-repo-admins](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-frontend-repo-admins/members) for now. But also Github will have to be allowed to deploy.

## Definition of Done

- [ ] Daily production deployment for vets-website is restricted to vsp-frontend-repo-admins
- [ ] Daily production deployment for content-build is restricted to vsp-frontend-repo-admins
- [x] The deployments both still work with the normal deployment schedule
- [ ] Reach out to the CMS team to see if they would like any restrictions put on the content-release, if so, implement those restrictions.

**Comment by jhonnyoddball** [comment]
From a CoP perspective is not relevant at this point. Closing for now.
