### ISSUE TITLE
[EKS] Rolling update failures due to pod disruption budgets

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#37958]
## Description
Rolling update failures cause issues with nodes in EKS clusters. 

## Background/context 

99 percent of the time when eks rolling update fails, it is because of the Loki pod disruption budgets defined on one of the components

![image](https://user-images.githubusercontent.com/76792875/156612330-35e5fbe9-6d62-40f8-9fbc-39c8c2fb7668.png)

This is defined in the helm charts and currently is not configurable, e.g. [the querier defined here](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml)

- When eks rolling update comes in and starts cycling out nodes it will attempt to evict these pods one by one working on a single node at a time and bringing them up on new nodes.  
- If for any reason one of the new pods fails to come up on the new node it will send the rolling update into a refresh loop waiting for the new pod to become healthy.  
- This is because the pod disruption budget is defined to allow only 1 pod to be unavailable at any given time.

As we can see in the [eks rolling update logs](https://github.com/department-of-veterans-affairs/devops/runs/5394408490?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/76792875/156613792-d1c8367f-6219-4532-bd1a-0bf77cd6e1cc.png)

More information about eks rolling update can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1827897404/EKS+Rolling+Update) 

## Technical notes
This can be worked around manually if you actively see eks rolling update failing with this error by modifying the disruption budget temporarily to be more than 1 for the component that is failing to be evicted.  However, if the rolling update had previously failed outright, you will need to account for tags that have been added to the worker node ASG as explained in the confluence doc as it can cause a difference between the expected and actual number of nodes.

A more permanent solution would be likely to figure out why said pods are failing to come up and adjust our deployments/configurations (requests) across the board so we don't run into this.  Or to see if it's feasible to create a PR against the real helm chart itself to make the pod disruption budget configurable, but the Grafana/Loki team may have reasons for statically setting this to 1 so there would need to be more investigation done there first.

---
## Tasks
- [ ] TBD

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by rmtolmach** [comment]
I just looked at the [eks rolling update logs](https://github.com/department-of-veterans-affairs/devops/runs/5394408490?check_suite_focus=true) you linked and dang! that ran for 6 hours! Did a human have to go in and cancel it? Is there a timeout that would have cancelled it eventually?

Your more permanent solution of root-causing the pod failures seems like a good next step.

What I don't understand is the connection between the helm chart configuration and the rolling update failure. How does a configuration in helm-chart's code impact that? I mean... I see the `PodDisruptionBudget` and the `maxUnavailable: 1` in the config, but... I'm missing some key piece here.

**Comment by mleclerc00** [comment]
I am circling back on my comment to modify the helm chart and going to try and add some more context here.

The real issue that needs to be approached is setting reasonable requests and limits for all of our deployments.  The root cause of this is likely the unrealistic requests that we have set for some of the loki components that we had done when loki was blowing up in prod and utility.  The requests are causing the scheduler to reserve far too many resources and then preventing daemon sets to come up on a particular node when needed.

The good news is we can revisit goldilocks (https://www.fairwinds.com/blog/introducing-goldilocks-a-tool-for-recommending-resource-requests), which I had previously set up in all of our clusters but just haven't had time to come back to.  This tool provides a dashboard which can recommend what requests and limits should be set for a particular pod based on usage.

for example 
![image](https://user-images.githubusercontent.com/76792875/156671532-354d1835-9d7e-4a68-8269-84287f1f975c.png)

**Comment by jhouse-solvd** [comment]
@mleclerc00 - Can we get tasks and acceptance criteria added to this one? Let us know if you need help w/ that.

**Comment by mleclerc00** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/428
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/423

These two PRs to define more reasonable requests addresses the comment I made above, which as far as I can tell has solved this issue which was mostly showing up in utility and prod.
