### ISSUE TITLE
Create ADR for Microservices on EKS

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#37950]
## User Story

_As a future developer of vets-api microservices I would like to be able to easily access the reasoning behind the choice to deploy these services in EKS._

## Expected Behavior

_This document exists and captures our core decision making points._

## Acceptance Criteria

- [x] _A simple ADR is created describing the architecture of a simple microservice (our implementation of pgHero or Sidekiq UI) as well as the deploy pipeline._
- [x] _This document has been reviewed by relevant stakeholders before being shared with a wider audience._

**Comment by considerable** [comment]
These 3 sources from our reality might help with  THE HOW:
- Amazon blog on EKS with ECR: [link](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/deploy-java-microservices-on-amazon-eks-by-using-amazon-ecr-and-eksctl.html)
- Amazon workshop on Argo CD: [link](https://www.eksworkshop.com/intermediate/290_argocd/)
- Argo CD official documentation: [link](https://argo-cd.readthedocs.io/en/stable/)

This older source begins with explaining THE WHY:
- Amazon Dev center hands-on [link](https://aws.amazon.com/getting-started/hands-on/break-monolith-app-microservices-ecs-docker-ec2/)

This IET confluence page talks about both THE WHY and THE HOW but on a more abstract level:
- Strangler Fig Pattern [link](https://vfs.atlassian.net/wiki/spaces/IET/pages/1991540880/Strangler+Fig)

**Comment by ewilson-adhoc** [comment]
https://vfs.atlassian.net/wiki/spaces/IET/pages/2109636630/ADR+Microservices+on+EKS
