### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by nathanbwright** [department-of-veterans-affairs/va.gov-team#37953]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: nathanbwright
- Reason access is required:  I'm the lead & production support person for the VA Notify Forms Strike Team team. We are in the process of adding a number of jobs for sending out emails via VaNotify and having access to the sidekiq admin UI would greatly help with job introspection & debugging, rather than just relying on the rails console to work with them.

**Comment by ericboehs** [comment]
Added.
