### ISSUE TITLE
Datadog tests for forced authentication routes

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#37966]
# Description
We need new tests for IAL1/LOA1 and IAL2/LOA3 forced authentication in Datadog

# Notes
The route will be `/v1/sessions/<verified_option>/new`

With verified_option being one of these 6 values
`[mhv_verified, dslogon_verified, idme_verified, idme_signup_verified, logingov_verified, logingov_signup_verified]`

# Acceptance Criteria (Engineer)
- [ ] Tests are created
- [ ] Tests are documented in team [monitor and alerting document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Monitoring%20and%20Alerting/Monitors_Alerts_Datadog.md)

# Deliverables (Product Manager)
- [ ] Tests Created
- [ ] Tests are documented in team [monitor and alerting document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Monitoring%20and%20Alerting/Monitors_Alerts_Datadog.md)

# Reference
**Slack Thread:** https://dsva.slack.com/archives/C019S3NSSAD/p1646335517048509

**Comment by joeniquette** [comment]
@sylvesterlee1911 these datadog tests should be completed within the Sprint: Apr 27 - May 11, 2022.

CC: @nsoutouras

**Comment by sylvesterlee1911** [comment]
Make sure that these routes are alive.  Verified route.

**Comment by sylvesterlee1911** [comment]
can do dslogin, logingov. idme.  

can not do mhv until piv card is activated.

**Comment by bosawt** [comment]
Don't think this is current anymore
