### ISSUE TITLE
[Ongoing Service] Medallia and Salesforce Data Refresh

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#37979]
## User Story
As a consumer of Medallia survey and Salesforce support data in DOMO, I want the data updated weekly, so I can monitor user feedback and support issues on a regular basis.

## Artifacts
- Link to product outline - [Medallia User Surveys](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product+Outline)
- Link to product outline - [Tier 2/3 Support](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product+Outline)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by ATMiddleton** [comment]
Complete
