### ISSUE TITLE
[SW-CONTENT] Update NADL page with new contact info [CW]

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#37984]
## User story
As a Veteran looking for an NADL, I need to have the correct contact information in case I need to ask questions. 

Stakeholder Raleigh Contreras reached out with new contact info for the NADL page. 

Resources: 
Info stakeholder provided in email:

Our office created a new team for NADLs.  The contact email/phone are different but the operating hours are the same. (*note this number is also for governments to contact us about MOUs to offer NADL Tribal Trust lands).  Could we have the info below included at the bottom of [Native American Direct Loan | Veterans Affairs](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/)?
 
“Eligible Veterans and Native American Tribal governments can contact a NADL Coordinator via email at NADL@va.gov, or by phone at 888-349-7541.”

## Tasks
- [x] Update page
- [x] Review edits
- [x] Copy edit page

## Acceptance Criteria
- [x] Ready for final OCTO-DE final review

**Comment by lunascoop** [comment]
@psanders86 this update is ready for review.

Native American Direct Loan: http://preview-prod.vfs.va.gov/preview?nodeId=758 (mirrored language in blue box on page about tribal government)
Made tribal gov info a note since this page's audience is really the Veterans
