### ISSUE TITLE
[FE] Display Message to User when Attempting to Pre-Check-In on the Day of Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#37983]
## Problem Statement 
As a Veteran, if I access a pre-check-in link after it has expired, I want to know that I can no longer perform pre-check-in.
 
## Wireframes
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/eKnpEma
     
## Acceptance Criteria 
- When I
     - Click a pre-check in link on the day of my appointment
     - Log in using LoROTA
- Then I
    - See a message telling me that I cannot complete pre-check-in
- [ ] This message is displayed even when pre-check-in has been completed for the appt

## Tasks
- [ ] Change message content when link expired

## Questions for Stephen
- Could we add info to read.basic so that the user does not have to auth before we show this message
     
## Work for other teams
- CHIP needs to make LoROTA expire at EOD on appointment day
- VeTTEXT needs to make short url expire at EOD on appointment day

**Comment by acrollet** [comment]
Adding a note that this will depend on CHIP work to:


- change the LoROTA expiration date from the end of the day _before_ the appointment(s) to the end of the day _of_ the appointment(s)
- change the short URL expiration date to match

However that work does not block this, the front end work can and should be done before the CHIP work is deployed.
