### ISSUE TITLE
Analytics KPI dashboard update request for [Public Websites Team - Campaign Landing Page]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37987]
# Request an Update to Your Standardized KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing standardized KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

If the dashboard that needs updating and is not a standardized dashboard (also called an “edge case”), please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information about how to request changes. 

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next **2-4 business days** from this time. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [X] **Content**: Add or remove pages included
Note- This is a new CLP that needs to be added to our existing KPI dashboard.  Please reach out if you have any questions.

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or (downloaded Excel version) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [X] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) (or download Excel version)
- [X] Complete worksheet as instructed
- [X] Link your completed spreadsheet here: [Copy of KPI Dashboard Product Details - Template.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8186728/Copy.of.KPI.Dashboard.Product.Details.-.Template.xlsx)
____
- [X] Check your sharing settings to make sure the Analytics team will be able to access it
- [X] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by michelle-dooley** [comment]
@brianalloyd - thank you for your update request.  We will review and get assigned during our sprint review on Wednesday.

**Comment by michelle-dooley** [comment]
@brianalloyd can you confirm the new urls are live in production yet?  And if not when they will be?

**Comment by brianalloyd** [comment]
@michelle-dooley they are not, launch was intended for 3/7 but was delayed to NLT 3/30.  We'll ping here once urls are live in order to kickoff analytics tracking.

**Comment by jonathan-epstein13** [comment]
@LindaLi123 will let you know as soon as it's ready and then you can close the ticket. Thank you!

**Comment by LindaLi123** [comment]
Hello @jonathan-epstein13 is this ready yet?

**Comment by jonathan-epstein13** [comment]
We've QA'd the data and everything matches up. So we will go ahead and close the ticket. The QA chart will be going into the ticket with the report links for documentation purposes.
