### ISSUE TITLE
Adding [individual] to DSVA Slack

### ISSUE THREAD

**Issue by taylor-hogge** [department-of-veterans-affairs/va.gov-team#37989]
# Description

The following guest user taylor.hogge@va.gov should be switched from single-channel to multi-channel guest and then added to vfs-platform-support

**Comment by LEHigley** [comment]
sorry @taylor-hogge i don't see you in slack at all--should i be adding you as a multi channel guest?

**Comment by taylor-hogge** [comment]
Hi Lacey,

Yes, that would be great. Thanks and let me know if you need me to do anything else.

Taylor Hogge, PhD
Junior Data Scientist (Contractor)
VA VBA Fraud Prevention Services
Cell: (757) 813-4585 | Email: ***@***.******@***.***>

From: Lacey Higley ***@***.***>
Sent: Monday, March 7, 2022 10:15 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Hogge, Taylor G. (booz Allen Hamilton Inc.) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding [individual] to DSVA Slack (Issue #37989)


sorry @taylor-hogge<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftaylor-hogge&data=04%7C01%7C%7C7cd1a61b508d4bafd4a708da004d4bc3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822629227164528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=80iBgwnGfEYxGyQyh8yllJxYrb6hubCqYOyFYLKkK9s%3D&reserved=0> i don't see you in slack at all--should i be adding you as a multi channel guest?

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F37989%23issuecomment-1060796914&data=04%7C01%7C%7C7cd1a61b508d4bafd4a708da004d4bc3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822629227164528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ni0IhRnt1ZKtNGGbfvHBvvDGb5n%2BATzU4iQqB4PAf94%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYCGILRPWB5EEXETQMWMOULU6YMQLANCNFSM5P53Z24Q&data=04%7C01%7C%7C7cd1a61b508d4bafd4a708da004d4bc3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822629227164528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gP5ugp%2BsINymorPivAIR0gI7BSItUAC7szDxiCyhohc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C7cd1a61b508d4bafd4a708da004d4bc3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822629227164528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c6gw4iU3Z9x%2BKZxTmiYIAbf2bpqGRXUR7qKcYyp4zd4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C7cd1a61b508d4bafd4a708da004d4bc3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822629227164528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c5%2B%2BLXfyXsr95BRkR9vR4F2I2kRX9a%2FU3f9guR%2F%2FYx8%3D&reserved=0>.
