### ISSUE TITLE
[Platform Infrastructure]: Setup and configuration for Testing Team

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#37992]
### Team name

Testing Team

### Application name

Developer portal

### GitHub repository

https://github.com/department-of-veterans-affairs/developer-portal

### Product owner

Meg Marsha

### Product manager

Ron Ronald

### Related issue

https://github.com/department-of-veterans-affairs/developer-portal/issues/395

### Infrastructure needed

Need access to an S3 bucket to store data.

### Users and service accounts

AWS user: Shawn.Shell

### Acceptance Criteria

- [ ] _TBD_

**Comment by jhouse-solvd** [comment]
Used for testing purposes. Closing.
