### ISSUE TITLE
Access for Ryan Smith

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#37995]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ryan Smith

### Your Email

ryan.smith@adhocteam.us

### Name of Your Team

Platform SRE, Software Engineer, Ad Hoc

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwNOyTZlFHRemfNRKF2XFPIEwZD7If7Lz79qRJAjfMumrvoEkz0I/V6WxmJrAwLvaAT7jGvXjbUbFo8hJbU9jpHbQKBA4qUtmTHc1Dqnxs1v84Xn4EyfjMiIVwHDZdKMiuwh5qkCSXR3CiEso83osvfceLqtTy1sA7QPf6nwXbBOWM3c2PFQIGrk/9hbkPiB3mzgB5Qp1h2EueE5rcAZVMiEmjh84wCA5cboljDSAx9tRTPHVJbs8vGoJYzGQ1fHZsp7ctYTBrP92QpZYOeyXHG9NNeg5V9fV4Og43cfw3WJhc4erNCuzIyNyYaaFzTC7awt58hlLqjTdqyVGq9RglbjH/YH/yXoCw/EkH7oA7BaYnohkyFWDcMrqaaPx1b1WVUCjMKjSqgu/ep18XeM1TGmKwFllSeONgkS4IUXgfDJOZJqgPSMk1TprElndRKe5IthP/NYmK/QdkuqYgQppTrPSpNSwlp8KMQSLkPXvK5IvODaI9gXKKMPEdRjQfx7s= ryansmith@Ryan-Smith-MacBook-Pro.local

### Access Expiration

Ongoing

**Comment by rmtolmach** [comment]
@rsmithadhoc Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
