### ISSUE TITLE
[Support Slackbot] Investigate ways to make backend more reliable

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#37999]
The goal is to prevent `/support` Slackbot outages. Investigate ways to strengthen the backend of the Slackbot in order to achieve that. The bot uses a google spreadsheet to store data. Occasionally, the Slackbot breaks when unexpected changes are made to the spreadsheet. [Link to infamous Google Sheet](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU). There are a few columns in the spreadsheet that a human user touches (columns M-S. "Was a ticket created?", "Was documentation provided?", etc.).

Questions to be explored:
1. Do we want to completely get off of the spreadsheet?
2. What would be involved in turning the backend from a google sheet into a database?
3. If we moved to a database, how would a user (SRE, for example) add the information to a request that is currently added manually in the spreadsheet?
4. Bi-weekly reports are created from the spreadsheet using Google Data Studio. Will this work if we have a db backend? 
5. What would be the simplest way of making the slackbot more reliable?
6. The spreadsheet is large. Does the number of rows impact performance? Would archiving the data on a monthly(?) basis to keep the main spreadsheet lean make the spreadsheet more reliable?

**Comment by little-oddball** [comment]
Determined OBE
