### ISSUE TITLE
Reason code update

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#37991]
Due to the way VAOS Service is handling reason codes, we're looking to update how we send them to the back-end.

- Set Appointment.reasonCode.coding[1].code to the radio selection value. One of:
   - "Routine Follow-up"
   - "New Problem"
   - "Medication Concern"
- If the selection was "Other", set Appointment.reasonCode.text to the patient's reason.
- For new appointments, ensure Appointment.reason is not being set in the POST body
- When viewing an appointment's details, if "Other" was selected then it should be reflected in the appointment details.

Starting in vaos-service 1.18.1, not only will Appointment.reason be deprecated, we will also be rejecting new appointment requests where it is set: only reasonCode will be permitted for conveying reason data.

Note: We are not updating the UI, just the formSubmitTransformer (v2) mapping specifically for VAOS Service.

**Comment by cferris32** [comment]
https://issues.mobilehealth.va.gov/browse/VAOSR-3158
