### ISSUE TITLE
disabled states

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#38]

**Comment by jaredcunha-usds** [comment]
Disabled states can be applied to components, such as buttons and form inputs to prevent the user from interacting with it based on permissions, conditions, or other criteria.

What types of variations of disabled content do we have? For example, do this apply? 
- Default: Cannot be clicked, selected or interacted with, nor read by screen readers. Appears visually disabled. This is how most things are disabled.
- Read-only: The user cannot interact with it, but the content is still readable and accessible to a screen reader. 
- Hidden: does not appear on the page, is not available to screen readers.  Usually, this applies when they do not have permission to use something. Cannot access, and will not be able to access. 

These three examples are from IBM's Cobalt

## Accessibility

Disabled components do not need to pass Section 508 contrast rules 

## When not to disable components 

Do not disabled submit buttons until a user fills out required fields. The user might think they have filled out the form and will grow frustrated that they cannot click the button. Allow the user to make an error so the error message can be presented.

Do not display information that cannot be edited in a disabled input field. The user may think there would be a way that content can be edited. Use plain text instead.

Can someone send me screenshots of disabled things? Especially from deeper within parts of the application.

**Comment by rtwell** [comment]
captured here #89
