### ISSUE TITLE
Facility Locator - Community Care provider detail view throws an intermittent error on first load 

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#380]
## What happened?
Sometimes when I click on a community care provider link from the Facility Locator, it throws an error and the page does not render correctly. /cc @ncksllvn && @Karak888 

Attaching a screenshot from Firefox (MacOS) and a text file stack trace.

This error has been traced to [line 17 in the ProviderServiceDescription.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/09c72ff4c97279bcde7942d2cfc5274883cc1150/src/applications/facility-locator/components/ProviderServiceDescription.jsx#L17) file:

```javascript
const ProviderServiceDescription = ({ provider, details = false }) => {
  if (details) {
    const { specialty } = provider.attributes;
    if (specialty && specialty.length < 1) return null;
``` 

## Related Items
* https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/15452
* https://github.com/department-of-veterans-affairs/vets-website/pull/10277

## Specs:
- MacOS Mojave MacBook Pro
- HP Windows 10 laptop
- All current browsers (IE11, Edge, Chrome, Firefox, Safari)

## Steps to Reproduce
- https://staging.va.gov/find-locations/ or https://va.gov/find-locations/
- Enter a search string like "Salt Lake City"
- Change `Search for` to "Community Care"
- Enter "Nurse Practitioner" as the service type
- Click one of the community care provider name links on the left
- The error may or may not appear. It is hit or miss.

## Desired behavior
The community care provider detail views render as expected every time without throwing an error.

## Acceptance Criteria
- [ ] Test users can click on multiple community care names, in multiple cities, with multiple specialties, and see views render correctly.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

---
![image](https://user-images.githubusercontent.com/934879/60117685-2cfd2700-9740-11e9-8bd0-772143c969c9.png)

---
![Screen Shot 2019-06-25 at 9 11 25 AM](https://user-images.githubusercontent.com/934879/60137734-8596e900-976d-11e9-99a4-ac4c4fe3b684.png)

---
[provider-detail-specialty-log.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/3326435/provider-detail-specialty-log.txt)

**Comment by accbjt** [comment]
@1Copenut I think we can probably put a if statement to check if specialty is undefined like so. Even though I would think this should never get past the initial if statement, but it does. I tried it out and I actually got the error the first time around but after that I had a hard time replicating it. I think by checking if specialty is undefined we can suppress this error. This should probably go after the first initial if statement.
```
if (!specialty) return null;
```

**Comment by 1Copenut** [comment]
@accbjt If you've got bandwidth, mind taking a shot at resolving this one? I've got a few things going that I need to stay focused on.

**Comment by accbjt** [comment]
@1Copenut Sure. I'm not sure how we would test it but we can at least keep an eye on it on Sentry.

**Comment by 1Copenut** [comment]
FWIW, I first saw this issue while working on localhost. There's some mocked Community Care providers in there, and with enough test runs, I could usually get the error to fire.

**Comment by mmiddaugh** [comment]
Community care providers are no longer linked in the results list so this issue is no longer present/relevant
