### ISSUE TITLE
Booked Appointment canceled by patient not returned correctly in response body

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#38009]
Booked appointment canceled by the patient is returned incorrectly on the POST call response body. Moreover, it does not return the serviceType Optometry leaving a blank entry next to Type of Care.

 ![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/ccbccf84-b713-440f-a185-c6f4c2f10c5e)
![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/41abbeb1-08e1-4e81-a557-484e17eebb1d)

However, the same canceled appointment is returned correctly on a GET call by its ID. The response body has `serviceType` and the correct `cancelationReason` array object.
![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/eccbd74d-249e-4d78-9c4d-585cecc35540)

![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/65746e07-ff3c-4f2f-b200-52f39ad20639)

**Comment by ajmagdub** [comment]
This is a vaos-service issue; the correct response is not being returned for the PUT cancellation request.
The following VAOSR tickets have been created:

[VAOSR-3118 - Booked Appointment canceled incorrect response body, cancel reason](https://issues.mobilehealth.va.gov/browse/VAOSR-3118 )  

[VAOSR-3119 - Booked Appointment canceled incorrect response body, service type](https://issues.mobilehealth.va.gov/browse/VAOSR-3119)

**Comment by grossb1** [comment]
https://issues.mobilehealth.va.gov/browse/VAOSR-3119
