### ISSUE TITLE
[Jenkins] Access for Zachary Lewis

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#38005]
## Description
I need access to Jenkins deploy on Dev, Staging as part of my role supporting Console Services (Backend) Merge and deploy requests.
[Jenkins deploy action - dev](http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-dev-post-deploy/build)
[Jenkins deploy action - sandbox](http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-sandbox-post-deploy/build)
[Jenkins deploy action - staging](http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-staging-post-deploy/build)

## Tasks
- [ ] Access Provided to deploy on [Jenkins deploy action - dev](http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-dev-post-deploy/build) , [Jenkins deploy action - sandbox](http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-sandbox-post-deploy/build), and [Jenkins deploy action - staging](http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-staging-post-deploy/build) 

## Acceptance Criteria 
- [ ] Deploy permissions.

**Comment by jhouse-solvd** [comment]
@zachclarity or @jbritt1 - Is this still in progress? 

Also, the AC isn't quite clear to me. Can we possibly update that to something that articulates the outcome we're looking for? "Zach can do X action on Y resource(s) for Z purpose(s)"

Thanks in advance for your help. :)

**Comment by oseasmoran73** [comment]
Closing ticket due to inactivity. @zachclarity Please feel free to re-open if needed
