### ISSUE TITLE
[BE] Track down EVSS endpoints for migration

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38014]
## Background
Dana Harrison the EVSS team [messaged us on Slack](https://dsva.slack.com/archives/C909ZG2BB/p1646059785245599) Feb 28 to request information about the EVSS endpoints that we use for a meeting on 3/7.

## Tasks
- [ ] Review BE code and record EVSS endpoints to share with EVSS migration team on 3/7

## Acceptance Criteria
- [ ] Review BE code and record EVSS endpoints to share with EVSS migration team on 3/7

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison when you get a chance, can you make sure that the information you found about EVSS endpoints and any other info you feel is pertinent is documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/evss-migration/evss-endpoints.md)?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison --- saw your updates.  Just FYI, I added a directory for backend specs, so the path has changed slightly.  [Updated link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/evss-migration/backend-specs/evss-endpoints.md).

**Comment by tpharrison** [comment]
@MarciMcGuireGCIO I'm going to make a few more updates to the doc...just some code references.  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Perfect!  I just wanted you to be aware that I moved it a level deeper.
