### ISSUE TITLE
Analytics Implementation of Foresee 5 star comment card for Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3802]
# Analytics Implementation or QA Request

## Description
- We'd like to implement the Foresee 5 star comment card on the Facility Locator main page so that we can begin to gather baseline user satisfaction metrics. 

- Dave Conlon and Michelle Middaugh
- Facility Locator Team(# vsa-facilities)  
- Domain: https://www.va.gov/find-locations/?zoomLevel=4&page=1&address=1780%20Harrison%20Court%20Northeast%2C%20Issaquah%2C%20Washington%2098029%2C%20United%20States&facilityType=all&serviceType&location=47.55%2C-122.04&context=Issaquah%2C%20Washington%2098029%2C%20United%20States

    
 - Facility Locator is part of the unauthenicated experience and there is no PII passed. 
    
- We are working on a UX redesign and plan to implement additional customer feedback options once Madelia(?) is available, pending the approval of additional questions
 
> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@mmiddaugh Are you looking to place the Comment Card on this specific URL:

https://www.va.gov/find-locations/?address=1780%20Harrison%20Court%20Northeast%2C%20Issaquah%2C%20Washington%2098029%2C%20United%20States&context=Issaquah%2C%20Washington%2098029%2C%20United%20States&facilityType=all&location=47.55%2C-122.04&page=1&serviceType&zoomLevel=4

or generally on:

https://staging.va.gov/find-locations/

?

**Comment by mmiddaugh** [comment]
@joanneesteban we'd like to have the Comment card on the general https://www.va.gov/find-locations/ page.

**Comment by joanneesteban** [comment]
# Comment Card added to Staging & Production

### Comment Card added to staging & tested: staging.va.gov/find-locations/

![image](https://user-images.githubusercontent.com/48964695/70660473-44699700-1c30-11ea-8735-ec1281276f57.png)

### Comment Card added to production: https://www.va.gov/find-locations/

![image](https://user-images.githubusercontent.com/48964695/70660660-c0fc7580-1c30-11ea-8280-cfd81efd564b.png)

![image](https://user-images.githubusercontent.com/48964695/70660704-d5407280-1c30-11ea-8fa7-8cdd8e4ad97d.png)

@mmiddaugh the feedback button has been added - let me know if you have any questions!
