### ISSUE TITLE
Adding Michael Ramirez to DSVA Slack

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#38020]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

Please add Michael Ramirez as a multi-channel guest to this channel: #cds-platform-public. The CDS Platform team is working with them on an integration for the Virtual Care Manager. Thank you!

**Comment by katieho-va** [comment]
Emails for Michael: michael@apothesource.com, michael.ramirez9@va.gov

**Comment by LEHigley** [comment]
@katieho-va can you please follow the template above? also, what email address should we use to add michael to slack?
