### ISSUE TITLE
Iterate on designs from Business Owner feedback (round 2)

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#38038]
- [x] Send Tarsha final wireframes and request her feedback within X days
- [x] Prioritize feedback 
- [x] Update wires
- [x] Write tickets to tech to communicate requested changes
- [x] Track feedback

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/a6a6f1ad-a67f-41e5-a597-27a21330b2eb/download](https://app.zenhub.com/files/133843125/a6a6f1ad-a67f-41e5-a597-27a21330b2eb/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/e0534c79-3a2a-458b-998b-554f70a39098/download](https://app.zenhub.com/files/133843125/e0534c79-3a2a-458b-998b-554f70a39098/download)
