### ISSUE TITLE
Understand what is needed for legal review and impact to timeline​

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#38039]
- [ ] Followed up with Tarsha on requirements for legal review
- [ ] Documented requirements and process as Tarsha sends it over to us

**Comment by ashleycastillo** [comment]
On hold until we hear back from Tarsha

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/028cb663-e338-48d5-bc1e-96a2090b9616/download](https://app.zenhub.com/files/133843125/028cb663-e338-48d5-bc1e-96a2090b9616/download)
