### ISSUE TITLE
Research into VANotify and how 1095-B might use VANotify 

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#38036]
- [x] Meeting held with VANotify team
- [x] Documented notes 
- [x] Access obtained for VANotify system

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/aa0ba0da-ee7a-4a61-99a5-cfcc24f619ea)
