### ISSUE TITLE
Conduct design QA of coded designs

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#38035]
- [x] Reviewed frontend code
- [x] Reviewed standards set in VA design system
- [x] Documented errors and communicated to tech

**Comment by tameracorson** [comment]
Sitewide is building unauthenticated state

**Comment by JordanSWhite** [comment]
Dependency: full build in staging

**Comment by jamesldesign** [comment]
@JordanSWhite please advise when build is in staging and I can review
