### ISSUE TITLE
[Design] HLR: Incorporate Design Feedback for Review Submission 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3804]
## User Story:
As a designer on the Benefits and Memorials team, I need to update the Review Submission design so that I can ensure it follows the recommendation of the design team's review.

## Tasks
- [x] Update the Review Submissions page with design feedback from Emily 

## Acceptance Criteria:
- [x] Design team's feedback has been incorporated into the Review Submission page

**Comment by rileyorr** [comment]
@YanaRoy I have updated the Review Submission page with Emily's suggestions. The mockups can be found [here](https://vsateams.invisionapp.com/share/W5U21BDFTQK).
