### ISSUE TITLE
Manually Test / Assess the Accuracy for the 10 Product QA Dashboards

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#38045]
# Description
Verify that the 10 Product QA Dashboards listed [here](https://va-gov.domo.com/page/1950369682) have accurate data and are free from any anomalies in their visualizations.

## Acceptance Criteria
- [x] Ask A Question Dashboard reviewed for accuracy of data and visualization quirks
- [x] Caregivers reviewed for accuracy of data and visualization quirks
- [x] Comparison Tools reviewed for accuracy of data and visualization quirks
- [x] Coronavirus Vaccination reviewed for accuracy of data and visualization quirks
- [x] Edu Benefits/1995 reviewed for accuracy of data and visualization quirks
- [x] Facility Locator reviewed for accuracy of data and visualization quirks
- [x] Personalization/Profile reviewed for accuracy of data and visualization quirks
- [x] Terms and Conditions reviewed for accuracy of data and visualization quirks
- [x] VAOS reviewed for accuracy of data and visualization quirks
- [x] Vre/28-8832 reviewed for accuracy of data and visualization quirks

**Comment by holdenhinkle** [comment]
### Ask A Question Dashboard
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ef16cdcf-485b-4522-910e-4578a10f0b57)

**Comment by holdenhinkle** [comment]
### Caregivers
Looks good

**Comment by holdenhinkle** [comment]
E2E
Avg Product Test Suite Execution Time
=> ms time seems to be incorrect:

Using VAOS as an example:
```
7.257 ms
2022-03-07	VA Online Scheduling	appointment-list	4225.9	2988
2022-03-07	VA Online Scheduling	community-care	6706.13	2988
2022-03-07	VA Online Scheduling	va-appointment	12285	2988
2022-03-07	VA Online Scheduling	covid19-vaccine	5657.43	2988
2022-03-07	VA Online Scheduling	va-request	7411.38	2988

7.148 ms
2022-03-04	VA Online Scheduling	community-care	6829.67	2988
2022-03-04	VA Online Scheduling	covid19-vaccine	5391	2988
2022-03-04	VA Online Scheduling	appointment-list	5028.25	2988
2022-03-04	VA Online Scheduling	va-request	7479.5	2988
2022-03-04	VA Online Scheduling	va-appointment	11015	2988
```

**Comment by holdenhinkle** [comment]
Contract Tests

The period being displayed in the graph is missing:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/58b40e88-b1db-4dba-9fb6-08c5f8bd19ef)

The queries look good however.

**Comment by holdenhinkle** [comment]
Lighthouse...

Looks good!
-  Performance: it looks like it's only run Mon-Fri. I think we should run it on weekend too.
- Accessibility: it looks like it's only run Mon-Fri. I think we should run it on weekend too.
-  SEO: it looks like it's only run Mon-Fri. I think we should run it on weekend too.
-  Best Practices: it looks like it's only run Mon-Fri. I think we should run it on weekend too.

**Comment by holdenhinkle** [comment]
To-do - Manual Functional

**Comment by holdenhinkle** [comment]
This ticket is complete!

**Comment by pjhill** [comment]
Awesome feedback, thanks!
