### ISSUE TITLE
Mobile Designs

### ISSUE THREAD

**Issue by tmulrooney-va** [department-of-veterans-affairs/va.gov-team#38052]
Already Exist:
- MHV home
- Secure Messaging Landing
- Pharmacy Landing

**Comment by jonathanjnelson** [comment]
- [x] [Updated landing page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/VrxYEoo)
- [x] [Pharmacy landing page ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/MygOZP9)
- [x] [Pharmacy in this section ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/8ygK17D)
- [x] [Pharmacy "additional info" expanded  ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/g0xj9Pk)
- [x] [Appointments landing page ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/YGx1AGm)
- [x] [Appointments in this section ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Kvgrbvg)
- [x] [Updated messages landing page ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/1Kp7O8w)
- [x] [Messages in this section ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/m1xQbQ8)
- [x] [Health care benefits landing page ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/YGxrZ5M)
- [x] [Health care benefits in this section ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/KvgL0Rn)
- [x] [Records landing page ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/L08Y4nW)
- [x] [Records in this section ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/7yLG1aE)
- [x] [Copay and bills landing page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/PGEn1oL)
- [x] [Copay and bills in this message ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/g0xG1Zq)

**Comment by MarciMcGuire** [comment]
@jonathanjnelson @tmulrooney-va is this ticket OK to close?  Thx!

**Comment by MarciMcGuire** [comment]
Thank you!  I'm going to retroactively create an MVP epic to attach all the previous MVP work so it will be easy to track down closed tickets if needed later.
