### ISSUE TITLE
Redirect Request: Effective Dates page in Disability

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#3805]
**Current page** disability/about-disability-ratings/effective-date/
**Redirect** /disability/effective-date/

Background: The effective dates page has moved in the left nav of disability. 
A redirect needs to be implemented so that the old page won't result in a 404. 

Date to be implemented by: 12/11/19

**Comment by mnorthuis** [comment]
Please note, there are actual 3 URLs that need to be redirected.  Two of them are already redirected but need to be updated based on this change.  Here are the 3 URLs that need to be redirected/updated:

NEW: www.va.gov/disability/about-disability-ratings/effective-date/
UPDATE: www.vets.gov/disability-benefits/after-you-apply/date/
UPDATE: www.benefits.va.gov/compensation/effective_dates.asp

These should be implemented asap - the two that need updating are currently returning a 404.

**Comment by Karak888** [comment]
@RLHecht @ncksllvn is this the ghosting issue that @kevwalsh was working to fix, or is this something different?  Thanks

**Comment by ncksllvn** [comment]
So this page-move has already been performed, so now `disability/about-disability-ratings/effective-date/` leads to a 404. Does this redirect need to be prioritized as a result?

**Comment by Karak888** [comment]
sorry @ncksllvn - @RLHecht I would assume if this is a 404 we need to prioritize this on Nick's list?

**Comment by RLHecht** [comment]
Yes, per Mikki's comment above, these should be done ASAP. @Karak888 @ncksllvn I had put in the 12/11 date based on the two-week turn-around that was recommended but it seems it should be done sooner.

**Comment by ncksllvn** [comment]
The redirect is live!

**Comment by lunascoop** [comment]
@mnorthuis @ncksllvn  @Karak888 @jenniferlee-dsva, I have validated that the redirects have gone live and will close this ticket.
