### ISSUE TITLE
[Design] HLR: Incorporate Design Feedback for Review Submission screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3806]
## User Story:
As a designer on the Benefits and Memorials team, I need to update the Review Submission screen design so that I can ensure it follows the recommendation of the design team's review.

## Tasks
- [x] Update the Review Submission screen with design feedback from Emily 

## Acceptance Criteria:
- [x] Design team's feedback has been incorporated into the Review Submission screen

**Comment by rileyorr** [comment]
@YanaRoy if this ticket is to incorporate feedback for displaying contested issues on the Review Submission screen, then that has been completed and the mockups are [here](https://vsateams.invisionapp.com/share/W5U21BDFTQK).
