### ISSUE TITLE
[Analytics] Profile: Help us figure out what errors are being shown in our GA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#38065]
# Analytics Questions

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

This request is coming from the authenticated experience team for the VA.gov profile with regards to [this direct deposit dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/_u.date00=20211101&_u.date01=20220306/).

In the screenshot below, I am trying to figure out which backend error codes map back to the following errors. 

1. other-error
2. invalid-routing-number

I can't see that by drilling down. Is there a way to figure that out? I need this so I can get my backend devs to look into what is causing these errors and why. Data is for November 1 - March 6.

![image](https://user-images.githubusercontent.com/34068740/157068868-2486af2e-2fd4-401c-b8ac-6c1e511295da.png)

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
cc/ @MarciMcGuireGCIO for awareness

**Comment by bsmartin-ep** [comment]
@Samara-Strauss - 

I'm not seeing a ton of helpful context in the analytics, so you may want your devs to investigate.

But taking a quick look at the code, that is all set in here...

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/profile/util/index.js

`other-error` is a default error code [for when none of these errors are returned](https://github.com/department-of-veterans-affairs/vets-website/blob/99e06fac1ffb487735355c4d64d674a6aab32457/src/applications/personalization/profile/util/index.js#L110).

`invalid-routing-number` is used when error `payment.accountRoutingNumber.invalidCheckSum` is returned or a generic error message with 'Invalid Routing Number' in the text.

And all of these error codes have "enroll" or "update" appended depending on the action...

```js
errorCode = `${errorCode}${isEnrolling ? '-enroll' : '-update'}`;
```

**Comment by Samara-Strauss** [comment]
Thanks @bsmartin-ep. I'll check in with our team and see if they can figure this out.
