### ISSUE TITLE
Prep initial scaffolding

### ISSUE THREAD

**Issue by froehlichcr** [department-of-veterans-affairs/va.gov-team#38084]
- [x] Standup development environment
  - [x] Setup vets-api
  - [x] Setup vets-website
  - [x] Configure development environment for API (through MVH) testing
- [ ] Inventory existing APIs from mobile and va.gov to identify (1) what exists currently that is suitable for our use cases, (2) what is missing entirely and needs to be implemented, (3) what is partially implemented and needs additional work to meet our needs
  - [ ] Document this process for MHV teams
  - [ ] Write first PR
  - [ ] Deploy to staging
  - [ ] Verify new API is working on Production
- [ ] Create skeleton React app using Secure Messaging as the design concept
  - [x] Developer documentation for React
  - [x] Component documentation
  - [ ] Stock views (List all messages, get full message by id, get messages by folder, get message count (read/unread), create new message)
- [ ] Abstract app composition from prototype Secure Messaging
  - [x] Documentation
  - [ ] Component Library
  - [ ] Routes/Views/Models/etc
- [ ] Review with Barry

**Comment by MarciMcGuire** [comment]
Hi @froehlichcr !  I'm doing a little cleanup and want to confirm that I can close this issue.  Thx!
