### ISSUE TITLE
Login.gov not working on vets-api native setup

### ISSUE THREAD

**Issue by bradbergeron-us** [department-of-veterans-affairs/va.gov-team#38083]
In local development the login.gov sign on option is not appearing on the master branch from vets-api. I have verified that Feature flags for login.gov are enabled. This scenario is on the master branch with the vets-api native setup. The feature toggle network request from within the login modal is failing. 

NOTE: We saw the changes in this PR and needed to know is there a config or a reason for our missing option for local native setup ?  https://github.com/department-of-veterans-affairs/vets-website/pull/19432

<img width="752" alt="Screen Shot 2022-03-07 at 12 48 18 PM" src="https://user-images.githubusercontent.com/8945799/157093927-481bc76a-3fcb-480d-9fca-2f0864cde5f0.png">
<img width="841" alt="Screen Shot 2022-03-07 at 12 13 55 PM" src="https://user-images.githubusercontent.com/8945799/157093932-0d80e6a1-83cb-4455-b91f-db1acb6c4ce2.png">
<img width="1416" alt="Screen Shot 2022-03-04 at 5 06 22 PM" src="https://user-images.githubusercontent.com/8945799/157093937-2a6b150d-642b-4755-b921-2b8948b58fb8.png">
<img width="1194" alt="Screen Shot 2022-03-07 at 2 09 05 PM" src="https://user-images.githubusercontent.com/8945799/157101602-66d86396-8f7c-422d-9511-f36717dba571.png">

**Comment by zachclarity** [comment]
@ericboehs   We created this to track the resolution.
