### ISSUE TITLE
Redirect request: DIC page moving from Burials/Memorials to Disability hub

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#3809]
**Current page:** /burials-memorials/dependency-indemnity-compensation/
**Redirect to:** /disability/dependency-indemnity-compensation/

The DIC page is moving from the Burials/Memorials hub to the Disability hub. 

Date needed to be implemented by: 12/11/19

**Comment by mnorthuis** [comment]
@RLHecht There are 4 URLs slated to be redirected to this page.  
- The first one is the change from old URL to new URL
- The vets.gov page is already redirected and needs to be updated
- The bottom 2 benefits.va.gov URLs should be redirected if the new page is in parity.  Can you take a look at the bottom 2 and confirm that those 2 redirects are ready, or if we should hold on those?

www.va.gov/burials-memorials/dependency-indemnity-compensation/
www.vets.gov/burials-and-memorials/survivor-and-dependent-benefits/compensation/
www.benefits.va.gov/COMPENSATION/types-dependency_and_indemnity.asp
www.benefits.va.gov/COMPENSATION/types-dependency_and_indemnity_parents.asp

**Comment by RLHecht** [comment]
@mnorthuis It looks like the information in those bottom two pages are incorporated in the current page, so I think they are OK to be redirected. @jenniferlee-dsva can you confirm I'm not missing something?

**Comment by mnorthuis** [comment]
The 2 server side/drupal changes are complete.  Just the server side redirects remain: 

*DONE* www.va.gov/burials-memorials/dependency-indemnity-compensation/**
*DONE* www.vets.gov/burials-and-memorials/survivor-and-dependent-benefits/compensation/**
www.benefits.va.gov/COMPENSATION/types-dependency_and_indemnity.asp
www.benefits.va.gov/COMPENSATION/types-dependency_and_indemnity_parents.asp

**Comment by ncksllvn** [comment]
@mnorthuis I have the client-side redirects ready in vets-website as described in your comment here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/1729#issuecomment-530844035/

The redirects in that comment though are different than the ones in this thread. Are these related? Or, what's going on?

**Comment by mnorthuis** [comment]
This ticket is only requesting a redirect for those URLs impacted by the launch/change of the `/disability/dependency-indemnity-compensation/` page.  The 4 URLs/pages impacted are listed above. Two of them were not slated to be redirected until parity work was complete, and that is complete per Randi's comment above.  

Issue #1729 references these AND also includes the 2 new DIC rates pages and the all the URLs/pages that need to be redirected when those launch.  This is issue is just part of the work in 1729.

**Comment by lunascoop** [comment]
@mnorthuis @ncksllvn  @Karak888 @jenniferlee-dsva, I have validated that the legacy redirects have gone live and will notify the stakeholders, close this ticket and update my communication log.
