### ISSUE TITLE
Create a plan for onboarding VSA teams

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#381]
## Story
As a VSP product support member, we need a plan for onboarding 4-5 VSA teams.

## Goal
Create a plan that enables VSP product support team to prepare for onboarding up to 5 new VSA teams.

## AC
- [x] A plan has been drafted
- [x] A list of questions has been compiled
- [ ] Identify who backfills what support roles when people are out (i.e. how to always remain able to provide support even when teammates are out)
- [ ] Make sure everything is in the correct repo
- [ ] Include process to make the 508 audit process more agile
- [ ] Reviewed by DSVA platform owners
- [ ] Shared in Github 

## Def of Done
- [ ] AC is complete
- [ ] Connected to an epic

**Comment by smoonpeyes** [comment]
Draft: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/Onboarding-Plan.md

**Comment by smoonpeyes** [comment]
@emilywaggoner Do we need a meeting with DSVA to review the draft?

**Comment by hpjaj** [comment]
Moving to backlog until this gets re-prioritized
