### ISSUE TITLE
[BE] My VA - Payment Info: Add payment history performance alerts to #vsa-authd-exp-alerts channel

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38100]
## Background
During troubleshooting an issue with the Edu direct deposit endpoint performance, Lihan created a channel, **#vsa-authd-exp-alerts**, to track and monitor any issues and alerts coming from the endpoint.
We would like to add the payment history and debt portal endpoints into this alert tracking channel.

APIs
```
/v0/debts
/v0/profile/payment_history
```

## Tasks
- [x] Integrate payment history endpoint alerts into **#vsa-authd-exp-alerts** Slack channel
- [x] Integrate debt portal endpoint alerts into **#vsa-authd-exp-alerts** Slack channel

## Acceptance Criteria
- Alerts for Payment History and Debt portal performance will populate in the **#vsa-authd-exp-alerts** Slack channel, mirroring the type of alerts we already receive for Edu direct deposit.

**Comment by hdjustice** [comment]
Hi @tpharrison and @lihanli - We would like to have this ticket implemented in next sprint (4/6 - 4/19) so it can be ready before going live.  Is this doable?

**Comment by lihanli** [comment]
yes i can do it next sprint if i'm still a part of the team

**Comment by hdjustice** [comment]
No matter where you are Lihan, you are always part of the team!
Seriously tho, thank you!  If you have other team duties, that is understandable and we can figure out how to get it done.

**Comment by tpharrison** [comment]
@lihanli - do you mind if I pair up with you when you work on this?

**Comment by lihanli** [comment]
> @lihanli - do you mind if I pair up with you when you work on this?

sure we can pair on it
