### ISSUE TITLE
Request design review for Higher-Level Review form in staging

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3810]
### For reference

[Accessibility Best Practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md)

**VSA** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/review-process.md#design-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/review-process.md#design-review)

## Product Name

Higher-Level Review

## Checkpoint Stage

[ ] **Design Intent** (for early discussions about needs, priorities, concepts, research planning, and direction)

[X] **Design Review** (for design work validation of best practices and alignment with the va design system)

### Where in the process is this? 

[ ] Initial concept

[ ] Initial mockup

[X] Final mockup

## Point of contact

Riley Orr - Designer
Yana Roy - Product Manager

## Preferred times

We are not ready for a review in staging yet and have created this issue as a placeholder for the time being.

## Next steps

This issue *automagically* creates a Zenhub ticket (assigned to Emily, Crystabel, and Jennifer (VSA Accessibility Specialist), and VSP will schedule a design review.

**Comment by rileyorr** [comment]
@YanaRoy I'm going to close this ticket since neither of us are working on HLR anymore.
