### ISSUE TITLE
[1010 EZ Short Form] PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#38104]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

In order to improve the submissions and user experience for Veterans applying for health care using the online 10-10EZ application, we are looking to implement the ability to recognize automatic qualifiers and use those to skip portions of the online form. The first phase will focus on using the user's disability rating to skip sections of the form containing information that is no longer relevant, such as military service and financial information.

For authenticated users we will provide the short-form if their disability rating is 50% or higher.
Fir UN-authenticated users, we will provide the short-form if their **self-reported** disability rating is 50% or higher.

The experience would be as follows:

- The Veteran begins the 10-10EZ online form
- If they have logged in, when we retrieve their account information we will also retrieve their  disability rating. Otherwise, they will need to provide their disability rating in order for us to determine whether or not to show the shortened form.

- The Veteran will fill out any remaining or blank personal information (address, phone #, etc.)
- If the  disability rating meets the qualifications, we will inform the Veteran they may skip other sections and then take them to a later point in the form.

High level design and flows:
1. Retrieving new profile information (disability rating)
2. Dynamically altering the flow to skip chapters and sections
3. For any information we skip, we are investigating whether may need to send certain default values to the backend system.
4. There will be a new screen/messaging to discuss the fact that the veteran can skip sections.

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
- Product/Feature [Epic](https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/27679)
- Product/Feature Copy deck(s):  Design prototypes

## Product/Feature Design prototypes 

**Note:** the clickable prototypes below are for demo purposes only and content/screens may not be up to date
- [Authenticated clickable prototype](https://preview.uxpin.com/acda277e33e9629a7ab817f6c93c251b4a60ac56#/pages/141488399/simulate/no-panels?mode=i)
- [Unauthenticated clickable prototype](https://preview.uxpin.com/2a1ce93f62d447e101cfce3c803d20941fba7203#/pages/141808810/simulate/no-panels?mode=i)

- Authenticated-immediate alert ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/EL9RYvq))
- Authenticated-self-report ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/jgDjqJb))
- Unauthenticated-self-report ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dlvDq7j))
- Full application flow/ less than 50% disability rating ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxZzO2l))

## Design
- [Authenticated first alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGdWmvL)
- Auth & Unauth [accordion alert ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGeGRKd)on every page at top
- Auth/Unauth [confirmation page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbOa3g7)
- Auth/Unauth self-report [FIRST Short form alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/bgWPqbz)
- Auth & Unauth [short form review page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbdvz8d)## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: @Dene-human 
Content/IA: @DanielleThierryUSDSVA 
Front-end: @lzapson 
Back-end: @RudyOnRails 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/Short-form-use-cases.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@SKasimow , below are the TestRail HCA-SF QA Test Plan & Cases links.
**NOTE**: Test-cases are still WIP right now.  I'll finalize them once I can validate test-accts & flows in a PR Review Instance -- I'll ping the Team on Slack and update with another comment here when they're final.

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3094)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4151)

cc @Dene-human @lzapson in case you'd like to check them out. [Obtain TR creds from Sharon]

**Comment by tlei123** [comment]
@SKasimow , QA test-runs now completed.  QA-artifact links are below [and also in [Stg Rvw tic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38031)]:

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3094)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4151)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/300)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/299)*

\***NOTE**: I did NOT log a defect for the Safari-specific form-submission errors, as the tests were in the PR review-instance.  Successful form-submissions in other browsers actually redirected from the RI form to the _Staging_ Confirmation page.

cc @lzapson @Dene-human

**Comment by tlei123** [comment]
Once merged into master branch, run another round of tests in Staging against more devices/browsers.

**Comment by SKasimow** [comment]
@tlei123 are we QA complete?

**Comment by tlei123** [comment]
@SKasimow , when your Team's done scoping/grooming Platform-feedback items for Staging/Launch, pls. ping me and we'll sync-up on in-scope changes for our Staging QA.  If you have a feel for rough timeline to code-complete on Staging, pls let me know that too &mdash; wouldn't want to have a conflict w/ [Profile Pers-Info Update](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40249).

Thanks much!

**Comment by Dene-human** [comment]
Hi @tlei123 Just wanted let you know that @hdjustice is our new PO. Sharon has moved to another team.

**Comment by tlei123** [comment]
Oops!  Thx @Dene-human !  Just fixed my Comment above, @hdjustice .  ^^

**Comment by hdjustice** [comment]
@tlei123 - FYI We are planning to deploy the Short Form in Staging by Thursday afternoon.  We plan for additional QA running through to make sure it is still working as expected.  It will be behind a feature flag, so we will have specific test users for the testing.  I will confirm those and make sure we have them ready when the feature is deployed.  Let me know if you have any questions or concerns.  Thanks!

**Comment by tlei123** [comment]
@hdjustice , thanks much for the heads-up.  I have a few questions for now:

- [ ] (1) Will the "bug" Darius mentioned in his QA-Feedback ticket #40504 be fixed ?
- [ ] (2) Will there be any other change(s)?
- [ ] (3) Assuming there'll be changes, will updated Design mockups be provided for them?
- [ ] (4) Will F/E know for sure by end of Wednesday whether everything'll be ready in Staging the following day?

My plan is to immediately start test-runs Staging's ready, working into the evening to complete all test-runs.  I might start late, so if you need to chat just park a DM for me in Slack and I'll check that when I come online.

**Comment by tlei123** [comment]
All test-runs now completed on Staging.  TestRail Test-Plan/-Cases links are below. Will check on reports generation tmrw (Fri).

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3265)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4151)

**Comment by hdjustice** [comment]
@tlei123 I fixed the [Use Cases link ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Short%20Form/Short-form-use-cases.md)in the main description.
