### ISSUE TITLE
[FE] | 1010EZ Short-form | Make Marital Status Mandatory in Schema

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#38105]
2. The Marital status question (currently in Step 1 Veteran information) moves after the Financial disclosure question within the Household information section.
     - This is directly after Financial disclosure question
     - This it is dependent on a "Yes" answer to the financial disclosure question _(same as the rest of this section)_
     - This is directly before the Spouse's information questions
     - **Please note:** The "Spouse's information" questions are dependent on the marital status answer. This logic **shouldn't** change.

**Comment by SKasimow** [comment]
Hi @lzapson - opened a draft for you....

**Comment by Dene-human** [comment]
@nicko-amida tagging you in this so you're aware that at some point the marriage question will only show (be dependent) on a "yes" answer to financial disclosure. Thought it might affect your thinking on the new design of the Household info section.

**Comment by hdjustice** [comment]
Closing this ticket for now.  Short form bypasses this question, so making this mandatory in schema would cause conflicts.

**Comment by markfallows** [comment]
Closing this ticket for now. Short form bypasses this question, so making this mandatory in schema would cause conflicts.
