### ISSUE TITLE
Determine what QA is needed for the file upload project

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#38117]
## User Story

_As an IET developer, I would like to begin to determine what our testing strategy is for this project, so that I will be able to determine the performance/robustness of our prototype implementations._

## Expected Behavior

_This ticket is a reminder to reach out to the QA team and begin figuring out what the test process should look like, document what tools are available and what the protocol is like for something like stress testing._

## Acceptance Criteria

- [x] _IET has begun to think about QA_

**Comment by considerable** [comment]
Platform developer docs section [Testing and releasing](https://depo-platform-documentation.scrollhelp.site/developer-docs/Testing-and-releasing.1847820556.html) among other things says, _"Contract testing on VA.gov is accomplished using Pact"_ and _"Load tests need to be run before launching new endpoints or substantial updates to existing endpoints to ensure the stability of the API"_.

**Comment by considerable** [comment]
One kind of testing not done by Platform in past is **Chaos Testing**, a testing technique that emerged along with the need to test Microservices on Kubernetes. 
Amazon blog: [Chaos Engineering with LitmusChaos on Amazon EKS](https://aws.amazon.com/blogs/containers/chaos-engineering-with-litmuschaos-on-amazon-eks/) explains how Chaos experiment can be launched using the Litmus ChaosCenter UI by creating a workflow to test   
**Hypothesis**: Amazon EKS cluster should auto scale when cluster capacity is insufficient to run the pods.

**Comment by ewilson-adhoc** [comment]
I found this page https://vfs.atlassian.net/wiki/spaces/IET/pages/2107572231/File+Upload+Test+Plan let's capture some of this data there in a RFC

**Comment by considerable** [comment]
ok, one more thing to capture - looks like the infra team has already been looking into the Chaos testing setup - https://vfs.atlassian.net/wiki/spaces/SRE/pages/2032599080/Initial+Questions+Tasks+from+Zach+Lewis

**Comment by ewilson-adhoc** [comment]
One of the questions that we should be thinking about is what sort of testing we need to do to determine if our new services is "better" than the old service. I think a good first step might be to look at the existing endpoints and see if we can find results of previous load tests. I don't think we need to worry about chaos testing for this project (the fact that we're on EKS will help make our system self-healing).

Do you know if it is feasible to use Pact on endpoints that are still liable to change? We'll definitely want to use it once we've nailed down the inputs/outputs of our API -- but for the initial prototype, the API is liable to change.

**Comment by ewilson-adhoc** [comment]
I think we've satisfied the acceptance criteria of this. We can reopen additional tickets as we need to do QA work.
