### ISSUE TITLE
Add structured logs to prototype of file upload

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#38118]
## User Story

_As a VFS developer, I would like the file upload utility to have a robust logging solution, so that I can triage issues. Therefor I would like to set the groundwork for this by implementing structured logging in the early prototype._

## Expected Behavior

_Structured logs are implemented in the prototype. The precise data that we will need to log will be implemented at a future time._

## Acceptance Criteria

- [x] _Structured logs are implemented in the prototype._
- [x] _Logs go to stdout._
- [x] _Some data from the request response headers is added to the logs._
- [x] _Access the logs in a simple dashboard (using Grafana)._

**Comment by considerable** [comment]
Recent [DZone article](https://dzone.com/articles/rest-api-versioning-strategies-1) along with [REST API Tutorial](https://restfulapi.net/versioning/) do recognize 4 REST API Versioning Strategies:
- Versioning through URI Path
- Versioning through Query Parameters
- Versioning through Custom Headers
- Versioning through content negotiations

Of which the content negotiations looks both HTTP-native and human-friendly, i.e. a request header as following
```
Accept: application/vnd.vets-api-maintenance-window+json;version=1.0
```

**Comment by ewilson-adhoc** [comment]
We can probably use the container images as versions -- this doesn't leak information, but it gives a clear idea of where this version comes from.

**Comment by considerable** [comment]
Implemented FastAPI-bounded JSON logging with https://github.com/mostepunk/fastapi-json-log

There are two loggers "main" It needs for log your data, and request/response log as middleware for logging all incoming and outgoing information.

**Comment by considerable** [comment]
Some access logs can be produced by accessing the [Swagger UI](http://file-upload-dev.vfs.va.gov/api/v1/docs)
Subsequently, the logs can be monitored with Loki in [Grafana UI](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-file-upload%5C%22%7D%22%7D%5D)
