### ISSUE TITLE
Analyze Accessibility Testing Duties for Potential Gaps

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#38111]
# Description
We need to understand what potential gaps there are in coverage for accessibility testing duties prior to Noah's departure, so they can be formally understood and handed off to other team members.

* Which accessibility testing duties has Noah performed in the last 6 months that do not have a formal process in place?
* Are there any areas of Noah's day-to-day that are poorly defined in documentation?
* Are there any responsibilities that QAS team leadership might not know about?
* Are there any files that Noah owns in Google that we need to transfer to avoid pain when Noah's accounts are removed?

## Acceptance Criteria
- [x] Any potential gaps in job responsibility coverage have been identified
- [x] Undocumented processes supported by Noah have been documented
- [x] All job responsibilities have been formally handed off to other team members in a meeting

**Comment by noahgelman** [comment]
Git
https://github.com/department-of-veterans-affairs
https://github.com/department-of-veterans-affairs/vets-website
https://github.com/department-of-veterans-affairs/content-build
https://github.com/department-of-veterans-affairs/vets-website/tree/E2E-Keyboard-Test-Port-to-Cypress
https://github.com/department-of-veterans-affairs/vets-website/tree/edit-button-focus-update
https://github.com/department-of-veterans-affairs/vets-website/tree/issue-414-error-messages-must-be-announced-when-tabbing-through-fields (Katy Bowman is in charge of this branch now)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29466#issuecomment-1026067067
https://github.com/department-of-veterans-affairs/vets-website/pull/20397#pullrequestreview-899439465



Confluence
https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2069430426/A11y+improvements+for+2022
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2042921088/Accessibility+Sync+Meeting+Notes
https://vfs.atlassian.net/wiki/spaces/pilot/pages/1601307071/How+to+Adding+accessibility+test+cases+in+TestRail
https://vfs.atlassian.net/wiki/spaces/PPS/pages/2002059367/Steps+of+an+Accessibility+Audit
https://vfs.atlassian.net/wiki/spaces/pilot/pages/1777893393/WCAG+2.1+success+criteria+and+foundational+testing
https://vfs.atlassian.net/wiki/spaces/PWD/pages/2099872052/WCAG+2.2+Success+Criteria+and+Foundational+Testing
https://vfs.atlassian.net/wiki/spaces/PPST/pages/2031812634/Proposal+to+remove+Full+Accessibility+508+Office+Audit+from+the+Collaboration+Cycle
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2057502870/Assess+QA+Standards+Products+for+Integration+with+Platform+Console
https://vfs.atlassian.net/wiki/spaces/PPS/pages/2059763776/How+to+complete+an+accessibility+review+for+Staging+Review


Depo
https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html
https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Developerdocs
https://depo-platform-documentation.scrollhelp.site/developer-docs/WCAG-2.1-success-criteria-and-foundational-testing.1777893393.html
https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to:-Adding-accessibility-test-cases-in-TestRail.1601307071.html

Google Spreadsheets
https://docs.google.com/spreadsheets/d/1IkIX7CgbFneFvlia1r9mYD8QU7uML5HWILkM7qsxizs/edit#gid=333168944

Slideshows
https://docs.google.com/presentation/d/1rJLur5iIB0H47JVoTTUKd39U6TbvP12KbxICXgXNu0w/
https://docs.google.com/presentation/d/1ThlnJIIbBNBXcAYGiswFBlWnrtTLKly0j3J6vLFoxBA/

Misc
https://www.w3.org/TR/WCAG21/
https://www.w3.org/TR/WCAG22/
https://www.w3.org/TR/wai-aria-practices-1.1/examples/
