### ISSUE TITLE
Wireframes for Yellow Ribbon tables

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#3812]
Create wireframes demonstrating improved UX on YR tables.  

Solution must:
- present data in a dynamic way that allows users to find schools matching their criteria
- support Drupal file upload to populate table content
- be responsive, accessible, and fit within va.gov design standards

**Comment by Karak888** [comment]
I think this may be a dupe or cart before horse?  I am moving to close this but if anyone feels differently please let me know!

**Comment by andaleliz** [comment]
@Karak888 we'll still need wireframes for these tables.

**Comment by Karak888** [comment]
@andaleliz these wireframes are complete correct?  That's what I saw from your email link, just wanted to check so we can remove any blockers, etc.  Thanks!

**Comment by andaleliz** [comment]
This ticket may be too broad. Do we need a separate issue for each version of wireframes?

What I have completed now is a lo-fi version that I'm ready to share via a VSP/VSA Design Intent review.  If they are good with them, I'd like to show to the larger team and then we could move to hi-fi before development.

**Comment by andaleliz** [comment]
Closing this out as it will only cover initial wireframes and we will create more specific tickets for future work per @Karak888
