### ISSUE TITLE
Design feedback - Design intent The Debt Resolution Team - Combined VA Debt Portal

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#38128]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- These user flows are great!
- Pay attention to alert styles, [background only alerts](https://design.va.gov/components/alertboxes#background-color-only-alert) are for immediate feedback , however you may want to propose a version of the [mobile friendly expandable alerts](https://design.va.gov/experimental-design/expandable-alert) that is currently in experimental design.
- I don't think you need the < Return to copay balances link. It will duplicate the bread crumb. If you do want to proceed with this, you will need to go through the experimental design process as this is not approved navigation.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by rileyorr** [comment]
Thank you for the feedback @allison0034! I've incorporated your feedback into our prototype ([UXPin link](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148307563/simulate/sitemap?mode=i)). 

I was thinking more about the alert notifying the Veteran that they have VA debts when they're on the 'Copay list' page (and vice versa for copay bills on the 'Debt list' page); I'm not sure that an alert about VA debts fits within the context of a page about copay balances. I've been exploring a togglable section of the page, 'View other VA debt and bills', that would only display only if the Veteran had other VA debt/bills ([View mocked up design of what that would look like on the copay list page](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148355892/simulate/sitemap?mode=i)). 

I had a conflict with this week's design office hours, so I'd love any feedback on that approach if you have the time. My thinking is we can validate during usability if that provides enough information for Veterans to navigate back to their other debts, and if it doesn't then we can iterate on a more prominent alert. 

Thanks again for the feedback!

**Comment by allison0034** [comment]
Hi @rileyorr I like this idea and I think it is great to test it. Thank you!
