### ISSUE TITLE
Update Error Messages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38136]
## Feature Branch
Some tickets in this Epic are in a feature branch.  Feature branch name: check-in/epic/update-error-messages

## Problem Statement
As a Veteran, when I click on a pre-check-in and there is a problem that is preventing me from performing pre-check-in, I would like to know what the problem is so that I will know what I need to do.

## Use Cases
- Veteran clicks on a pre-check-in link that has expired
- Veteran clicks on a pre-check-in link when they have already completed the pre-check-in
- General error occurs

**Comment by brianseek** [comment]
PR for this epic's feature branch: https://github.com/department-of-veterans-affairs/vets-website/pull/21119/files#diff-1f1a7251baf5db9de31431da6e970890096332d981f7e4c685b00576000dd196
