### ISSUE TITLE
Import Medallia GA/GTM data into DOMO

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#38142]
## Context and Conclusions
We are using GTM to capture Medallia form interactions (invitations, accepts, declines, submissions, etc). We would like to import this data into DOMO to track trends in the survey decline rates. I'm open to discussion on the frequency of data pulls, but weekly would be great for now.

## List of fields needed
- Event Action (this can be pre-filtered to match "Forms - Medallia")
- Event Label
- Medallia Survey ID (survey-form-id)
- Medallia Survey Status (survey-status)
- Medallia Survey Contents
- Page
- Submission date
  
## Acceptance Criteria
- [x] DOMO DataSet has been created
- [x] Data has been added to the DataSet
- [x] Quick data review to ensure data meets requirements (@ianMcCullough-ob can do that)

## How to configure this issue
- Labeled with team-name

**Comment by bsmartin-ep** [comment]
How's this look @ianMcCullough-ob?  It's just 2022-03 for now.

https://va-gov.domo.com/datasources/c0cb147c-41fd-4fee-8b83-6f4dae69b96c/details/overview

**Comment by ianMcCullough-ob** [comment]
Thanks, @bsmartin-ep! This looks great, was toying around with it and I think I can make it work.

There still seems to be a discrepancy between the data in GTM and the data in Medallia. Medallia shows 213 submissions for 03/01/2022, but that number isn't popping up on the GTM data.

survey-submission is showing 190, and survey-submission-total is showing 181. I'd like to do more testing on the tags, but would need access to the invitation display. I'll inquire about that.

**Comment by ianMcCullough-ob** [comment]
Hey, @bsmartin-ep I'll address the data differences later. This is sufficient for now. Can I get this populated with data back to July 2021?

**Comment by bsmartin-ep** [comment]
@ianMcCullough-ob - 

We usually guesstimate 80-90% collection rate with GA due to ad blockers and network filtering, so that sounds about right.

> Can I get this populated with data back to July 2021?

Backfilled to 2021-07-01 and scheduled for daily appends.  Look OK?
