### ISSUE TITLE
[SW-Content] OCTO-Review - Education page - Montgomery GI Bill -Active Duty (Ch. 30) rates

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38151]
## Story
Please provide OCTO review of content composed for Education rates page - Montgomery GI Bill - Active duty (Chapter 30)

## Resources
#8634

## Tasks
- [ ] Final review of content composed for Education rates page - Montgomery GI Bill - Active duty (Chapter 30)
http://preview-prod.vfs.va.gov/preview?nodeId=5355

## Acceptance criteria
* Review and with final recommendations and/or improvements to content that will be provided to all editors with approval to publish.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I've reviewed, edited, reworked. It's ready for the team to complete the 2 tasks we talked about on our call:
- Fix TTY instances.
- Rework content in charts that have only 2 columns--don't use chart format in those instances. 

Thanks!

**Comment by bethpottsVADEPO** [comment]
I've edited this page and sent it to stakeholders for feedback.

**Comment by RLHecht** [comment]
This is an old ticket. closing.
