### ISSUE TITLE
Alignment breadcrumb issue on Chrome

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3815]
## What happened?
Seeing odd left alignment spacing issue in the breadcrumbs - but only on Chrome. (Mozilla looks okay.) Screenshot attached. 

![image](https://user-images.githubusercontent.com/43381063/69765188-fb4e1900-1140-11ea-8b12-aee5b0a454f2.png)

Background: We did a content deploy via Drupal (pension rates change had to go out for Dec 1 turnover). The content updates we made look correct, but seeing alignment issue on Chrome. Unclear if ^ issue is due to content deploy or from breadcrumb changes happening in Pittsburgh Staging.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x ] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
I am unable to reproduce this issue both on `staging` and `production`. @jenniferlee-dsva 

**Production:**
![image](https://user-images.githubusercontent.com/12773166/69871217-35720480-1280-11ea-8202-df0b399a5b76.png)

**Staging:**
![image](https://user-images.githubusercontent.com/12773166/69871242-46bb1100-1280-11ea-818d-91979265eb84.png)
