### ISSUE TITLE
[FE] My VA: Bug found in Staging - White space and link list showing in 2 columns under Health care header

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38167]
## Background
During informal click-through testing of the payment info section, we noticed that the Health care section is showing white space and the link list in 2 columns, rather than having the link list move over into the 1st column (when there are no appointments to list).

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/f9afbbb2-4917-4362-950f-eb446db0dca5)

- As of today (3/8/22), this was happening on user 12, 36 and 369.   User 41 shows the unread messages alert along with an error box for the appointment information.
- Also, I have been receiving different errors when attempting to click on My Health with user 41 and 369.  Perhaps there might be an issue with receiving information from MHV?

## Tasks
- [ ] Research root cause of the white space/2 column display within the Health Care section
- [ ] Implement fix, if necessary to address the issue

## Acceptance Criteria
- Root cause of the issue has been discovered and addressed as needed.

**Comment by Samara-Strauss** [comment]
Hi all -- Sorry to reopen this, but it's not quite done. The links should be left aligned if there are no appointments or messages to be consistent to how we handle things if there are no claim updates or no benefit payments/debts. In those cases, we left align the links under the main heading and any additional copy.

TBH I am not sure what to do if there is no appointment but there ARE new messages -- best to confirm with Angela if the links should left align or right align in that case. This should match however we handle things in Benefit payments & debts when there is no recent payment but there is a debt.

![image](https://user-images.githubusercontent.com/34068740/159562015-3f8b65da-f02c-43aa-a9d3-1d3a601fdbbf.png)

**Comment by hdjustice** [comment]
We have a ticket in next sprint #38658 to address the realignment when there are no messages or appointments.  
The Benefit payments and debts section does show 2 columns when there is a debt, but no recent payment.
![image](https://user-images.githubusercontent.com/92328831/159562460-471f8377-74a4-486f-b1ed-819ed59452d6.png)

The link list for the Health care section is a bit longer, and so creates more whitespace there, discussed in that other ticket as well
https://user-images.githubusercontent.com/97965610/159341528-fb21162b-df3d-46b0-abae-89e0cad97d14.png

**Comment by Samara-Strauss** [comment]
Great! I'll close this out again. Thanks for clarifying everything -- we can handle the realignment issue in the ticket for next sprint.
