### ISSUE TITLE
[SW-Content] Update CTA on R&S article about getting replacement EDU COE [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38161]
## Story
As a Veteran I need all widgets, links, and URLs to be up to date, so I have the latest and most relevant information for my eligibility.

## Resources
[EDU COE page](https://www.va.gov/resources/can-i-get-a-replacement-gi-bill-benefit-certificate-of-eligibility/)

## Task(s)
- [x] Replace the URL for this CTA with the widget link--the same one used on the contact us page

## Acceptance Criteria
* Action link is updated on EDU COE page and confirmed after publishing.

**Comment by RLHecht** [comment]
This work is complete. Moving to validate.
