### ISSUE TITLE
[FE] Add Bene Travel Link Utilization to Analytics Dashboard 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#38176]
## Description 
We need to capture some Google Analytics data on how often this link is being utilized

## Tasks 
- [ ] Add Event Tracking for the link "Find out how to request travel pay reimbursement" (see [Event Tracking in GA](https://www.gravitatedesign.com/blog/event-tracking-google-analytics/))
    - Category = Links
    - Action = click
    - Label = Request Travel Pay Reimbursement

**Comment by loripusey** [comment]
@acrollet @brdunfield @brianseek Is this something easy that one of you could pick up this sprint?

**Comment by benbrasso-agile6** [comment]
There seems to be a convention in GA for doing this. I'm not sure if we'd want to create our own that doesn't follow the existing convention in VA's GA account. 

Plus, I'm not even sure if we have room to include this in the existing custom dashboard. 

I'm happy to think through, 1) what we should track, e.g., event, referral page, etc., and 2) where we want to track and review this data, e.g., dashboard, if so, what widget, or just in GA, or maybe now is the time for GA data studio

**Comment by benbrasso-agile6** [comment]
For example, some of the data is there already - https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22get-reimbursed-for-travel-pay~2F%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&_r.tabId=navigationsummary&_r.drilldown=analytics.pagePath:~2Fhealth-care~2Fget-reimbursed-for-travel-pay~2Findex.html&navigationsummary-keySelector.searchTerm=get-reimbursed-for-travel-pay~2F&navigationsummary-fromNavigationSummaryTable.filter=complete/

**Comment by brianseek** [comment]
@benbrasso-agile6 Can we co-work on this a bit on Monday? There are some differences between the details you are asking for and the rest of the record event actions in the app.

**Comment by loripusey** [comment]
We should go with the established convention

**Comment by benbrasso-agile6** [comment]
I'll sync with Brian today and we'll hash it out

**Comment by brianseek** [comment]
Getting deployed tomorrow 7/12 @benbrasso-agile6 to validate after a day or so of traffic.

**Comment by benbrasso-agile6** [comment]
Will check this link periodically - https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20220711&_u.date01=20220712&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=check-in&explorer-table.rowStart=0&explorer-table.rowCount=25/

**Comment by benbrasso-agile6** [comment]
@brianseek think the event is firing? I haven't seen any events come through for this query in GA - https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22get-reimbursed-for-travel-pay~2F%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&_r.tabId=navigationsummary&_r.drilldown=analytics.pagePath:~2Fhealth-care~2Fget-reimbursed-for-travel-pay~2Findex.html&navigationsummary-keySelector.searchTerm=get-reimbursed-for-travel-pay~2F&navigationsummary-fromNavigationSummaryTable.filter=complete/

**Comment by loripusey** [comment]
Does it matter that this is not the dashboard that we've been using (to my knowledge); here is the dashboard I [use ](https://analytics.google.com/analytics/web/#/dashboard/1iHzB1FJTq6wHfngzN0LQg/a50123418w177519031p176188361/_u.date00=20220404&_u.date01=20220408/)

**Comment by benbrasso-agile6** [comment]
That dashboard is not currently set up to pull the new event in. We would need a new ticket to add the event to the dashboard. Brian took care of adding the event, which is step 1 of 2.

**Comment by loripusey** [comment]
How come the link I have for WBC and the link you have show different things?
![image](https://user-images.githubusercontent.com/86678742/178756958-b363c8b3-4db5-4b88-8655-db2753504e11.png)
![image](https://user-images.githubusercontent.com/86678742/178757020-054fdb9e-61c1-4779-ab8f-5d674a1b2123.png)

**Comment by benbrasso-agile6** [comment]
Chcked this morning, Still dont' see anything. Maybe my query is wrong? Or maybe it didn't get pushed?  Something else?

**Comment by brianseek** [comment]
@benbrasso-agile6 It may be worth getting platform analytics support now.

**Comment by sarahknoppA6** [comment]
Was there a resolution on this item, or does there need to be additional discussion?

**Comment by brianseek** [comment]
I think we are going to need a new ticket to look at all the events that we have vs. what we can see. Then work with the analytics team to set those events up. Also we may find that we don't really need some of them.

**Comment by loripusey** [comment]
I'll create a ticket
