### ISSUE TITLE
[Design] - Auth Profile - Address Change Messaging - Support FE build

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38180]
## Background
Provide feedback, suggestions, review FE updates on Staging as needed

## Tasks
- [x] Provide feedback, suggestions, review FE updates on Staging as needed

## Acceptance Criteria
- [x] Provide feedback, suggestions, review FE updates on Staging as needed

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske can you please estimate this ticket to the best of your knowledge?  Thank you!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO I'm a little unsure about this one - if it will be quick or more continuous back and forth - but have estimated at a 2 for now.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - sounds good!  We can always adjust if it turns out to be smaller/bigger!
