### ISSUE TITLE
[FE] Profile: Notification preferences -- Update list of facilities that can see the prescriptions preference

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#38187]
## Background

Currently, there are three notification preferences:

- Appointment reminders (shows conditionally only to health care users)
- Appeals reminders (shows to everyone)
- Prescription shipment notifications (shows conditionally to people at participating facilities)

Recently, new facilities were added to the prescription shipment notification pilot. The list is attached to this ticket. We need to make sure that patients that are assigned to the facilities in the list will see the prescription shipment notification preference in the Notification Preferences tab of their profiles.

## Tasks

- [ ] Update code so that all patients assigned to the facilities in the attached list will see the prescription shipment notification preference in the Notification Preferences tab of their profiles.

[VEText_  Pharmacy Shipment Notifications.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8209811/VEText_.Pharmacy.Shipment.Notifications.xlsx)

**Comment by Samara-Strauss** [comment]
cc/ @MarciMcGuireGCIO for awareness

**Comment by MarciMcGuireGCIO** [comment]
Thank you @Samara-Strauss! I really appreciate you creating this and providing the details!

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - I somehow omitted this from our Sprint Plan.  When you have a few minutes, can you please take a look and estimate the time needed to make this change?  Thank you, and I am sorry for the last-minute ask.

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO and @Samara-Strauss 
I should be able to prep this today and get a PR in for Monday morning.

**Comment by adamwhitlock1** [comment]
I merged this PR, and was just able to validate that it will show for user 36, and will not show for ssoissoetesting+mhvcss4@gmail.com which is a cerner test user. 

I got those test users from the initial issue comments: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28982#issuecomment-918596204

We will still need to update the help text though on a future ticket to not show the Asheville / Denver text and make it more general.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @adamwhitlock1 ! I will get a content request going for this.

**Comment by Samara-Strauss** [comment]
[Via Adam from Slack](https://dsva.slack.com/archives/C909ZG2BB/p1648497742870829?thread_ts=1648497268.469109&cid=C909ZG2BB):

> I was able to verify this as well. The help text I was seeing was when the channel Id was equal to channel14-1 and the facility number didn't match one of the listed facilities on our list. I’m still looking into what channel ID represents

We need to figure out what the channel ID is and exactly when that helper text shows in order to update the copy accordingly.

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 @Samara-Strauss just making sure I'm interpreting correctly - once @adamwhitlock1 is able to determine the significance of the Channel ID, I will still need to open a Content request to handle those edge cases?

**Comment by Samara-Strauss** [comment]
> once @adamwhitlock1 is able to determine the significance of the Channel ID, I will still need to open a Content request to handle those edge cases?

Yes-- the current copy sounds like it will be inaccurate once the update goes out. I think these should be next steps:

- Talk to Paras -- will the facilities be able to tell people whether they offer text prescription tracking updates or not? Is this good guidance to give people?
- Based on that, open a content ticket, and work with content to determine if we need copy in the first place or not. If yes, they'll help us update. If no, we can remove.

**Comment by MarciMcGuire** [comment]
Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Noting that we're creating a new ticket for updating the content for the edge case.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss We should be able to validate this that it still works as expected for the 2 users that I had used before for initial testing here:

> I merged this PR, and was just able to validate that it will show the notification setting for user 36, and will not show for ssoissoetesting+mhvcss4@gmail.com which is a cerner test user. I got those test users from the initial issue comments: #28982 (comment)

**Comment by Samara-Strauss** [comment]
Validated!

- Works for user 36
- Does not show for the Cerner user who should not see this setting

I think this ticket is good to close, but let me know if you need to reopen it for any reason.
