### ISSUE TITLE
Contact Center Review for Authenticated Experience - Payment Information section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38181]
# Request the Contact Center Review 

## Description
Updating current My VA product guide to include a new Benefit payment and debts section, that will display the most recent payment made to the Veteran (within the last 30 days), a notification of any debts owed by the Veteran, and links to other financial resources.
We are also cleaning up screenshots to reflect minor copy changes.

### Launch Date
Anticipating 1st week of April

### Version Number
Guide Version date 3.03.08.2022

### Product Guide
[*My VA Product guide link*](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/My.VA.2.0.Product-Guide.Version.3.03.08.2022.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @hdjustice. Looks good, and the links check out! Here's a clean draft. I added "2.0" to the title page; let me know if that's what you'd like. If this looks good to you, let me know and I'll share with VEO call center for their approval.
[MyVA_2.0_ProductGuide_V3_SRT_030822.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8227563/MyVA_2.0_ProductGuide_V3_SRT_030822.docx)

**Comment by hdjustice** [comment]
Hi @starlow00 , thank you so much for reviewing the guide!  The "2.0" version number was used internally only to reference the different states of My VA, however we did not want to keep this on the guide.  The product is My VA, and the version number means nothing really.  We no longer use that terminology within our team, and will be very careful in future updates to refrain from using that kind of erroneous verbiage.

**Comment by hdjustice** [comment]
@starlow00 Hi Steven, is there anything else that needs to be updated or added to the guide?
Also, due to some issues out of our control, we will be pushing our launch date out a bit.  I am not sure on the date, probably 2 weeks out from the original 4/6 date.

**Comment by starlow00** [comment]
Hi @hdjustice . I'm good! If you're happy with the draft (minus the 2.0), I can share with VEO for their approval.

**Comment by starlow00** [comment]
Sent to VEO for review.

**Comment by starlow00** [comment]
VEO has no objections, copy of guide attached. Closing ticket.
[MyVA_ProductGuide_V3_030822.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8327859/MyVA_ProductGuide_V3_030822.docx)

**Comment by hdjustice** [comment]
Great news, thank you Steve!
