### ISSUE TITLE
Adding Dev Keycloak monitoring

### ISSUE THREAD

**Issue by sGplkrsh** [department-of-veterans-affairs/va.gov-team#38199]
**Description:** As a user I need to be able to track usage and issues for keycloak by adding keycloak monitors in datadog

**Acceptance:** This ticket would be considered complete by executing below tasks:

- [x] Gaining access to datadog
- [x] which metrics?
- [x] send metrics directly to datadog (modifying settings need to be handled as well to support this effort)
- [x] which montiors?
- [x] add monitors in datadog
- [ ] look into and/or setup reporting cadence for monitors/metrics.

**Comment by calquisola** [comment]
Just an update. 

Which metrics? 
We haven't formally discussed what metrics we wanted. However, we are using [open source project](https://github.com/aerogear/keycloak-metrics-spi) that will create a metrics endpoint for us. 

We send these metrics over to datadog:
"metrics": [
            {"keycloak_login_attempts": "keycloak.login_attempts"},
            {"keycloak_logins": "keycloak.logins"},
            {"keycloak_failed_login_attempts": "keycloak.failed_login_attempts"},
            {"keycloak_client_logins": "keycloak.client_logins"},
            {"keycloak_refresh_tokens": "keycloak.refresh_tokens"},
            {"keycloak_refresh_tokens_errors": "keycloak.refresh_tokens_errors"},
            {"keycloak_registrations": "keycloak.registrations"},
            {"keycloak_registrations_errors": "keycloak.registrations_errors"},
            {"keycloak_code_to_tokens": "keycloak.code_to_tokens"},
            {"keycloak_code_to_tokens_errors": "keycloak.code_to_tokens_errors"},
            {"keycloak_response_errors": "keycloak.response_errors"},
            {"keycloak_request_duration": "keycloak.keycloak_request_duration"},
            {"jvm_buffer_pool_used_bytes": "keycloak.jvm_buffer_pool_used_bytes"},
            {"jvm_buffer_pool_capacity_bytes": "keycloak.jvm_buffer_pool_capacity_bytes"},
            {"jvm_buffer_pool_used_buffers": "keycloak.jvm_buffer_pool_used_buffers"},
            {"jvm_memory_bytes_committed": "keycloak.jvm_memory_bytes_committed"},
            {"jvm_memory_bytes_max": "keycloak.jvm_memory_bytes_max"},
            {"jvm_memory_pool_bytes_used": "keycloak.jvm_memory_pool_bytes_used"},
            {"jvm_memory_pool_bytes_committed": "keycloak.jvm_memory_pool_bytes_committed"},
            {"jvm_memory_pool_bytes_max": "keycloak.jvm_memory_pool_bytes_max"}
        ]

the dashboard can found [here](https://app.datadoghq.com/dashboard/2zu-qd9-gwt/amt-test-dashboard?fullscreen_end_ts=1649105505429&fullscreen_paused=false&fullscreen_section=edit&fullscreen_start_ts=1649091105429&fullscreen_widget=545850915833239&from_ts=1649081825991&to_ts=1649096225991&live=true)

**Comment by calquisola** [comment]
as per @kjduensing, reporting is not yet needed. closing this ticket.
