### ISSUE TITLE
write expectations doc on what should or should not be public

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#382]
## Description

Problem statement raised during our retro today:

The new va.gov-team repository is public, but there's some hesitation from team members on what should or should not be written and shared in this public repository.

Overall we value transparency, but there are likely to be some things we deal with may be VA-sensitive in nature and shouldn't be in this repository. We need a reference to guide everyday decision making about whether or not information should be public, and if not, where non-public data should be recorded and communication take place.

Some concerns to address:

- some items (like PHI, etc) should NOT go in GitHub period; define these categories and establish expectations around handling of this data
- compliance and security related information, particularly issues that may be current on the running site
- vendor selection process — if we are involved in trials of services or software, does us exposing details about it somehow violate procurement policies or somehow present risk to the process?
- documentation of VA systems and architecture — some areas like the TIC may be particularly sensitive and sharing of them could have negative consequences for the project
- phone numbers and internal email addresses that we may not want to be public, but need to share within the team
- test user information for lower environments
- postmortems

**Comment by batemapf** [comment]
@Jeff-Hayter re the concern raised above:

> vendor selection process — if we are involved in trials of services or software, does us exposing details about it somehow violate procurement policies or somehow present risk to the process?

Any thoughts?

**Comment by Jeff-Hayter** [comment]
I suggest we add PII just so that folks are reminded to be careful and if we need a more granular definition we as a team can determine that threshold based on what information you might want to make public.

On the vendor question, yes it is possible for this to happen   To Leah and Patrick's points though it should be raised with us first and definitely has to be tied to a sprint objective.

Should passwords be included on here as well?

**Comment by wyattwalter** [comment]
@batemapf @leahbannon @gunsch One more category came up today. What about postmortems? We also stored them in vets.gov-team. Having them public would be ideal from a transparency standpoint in my opinion.

Risks of storing the raw info publicly I can think of:
- we may get some heavily filtered information from folks during an incident review when someone knows info will be public (and they absolutely should know this), which would reduce their value
- we may also need to store some sort of stripped down version if it gets into some areas that we consider sensitive
- while we try to be blameless, having names and details about where problems occurred (regardless of the language) could be viewed negatively

**Comment by batemapf** [comment]
Only less-than-satisfactory solution I can think of is to store a robust, uncensored version in a private repo and, once it has been completed, generate a public facing version that strips out any sensitive info and protects the privacy of those involved.

**Comment by gunsch** [comment]
Yeah, I think as a rule postmortems should be in the private repo. 

@leahbannon @batemapf @wyattwalter I have a PR out at https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1 for this guidance. Just added a bit about postmortems too.

**Comment by gunsch** [comment]
Resolved by https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1
