### ISSUE TITLE
[VAMC] Content - Run Book content documentation for section - 5.2 Planning for Content

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38213]
## Story
As a Veteran I need to know that future web modernization groups will have a run book to modernize Veteran websites, so I can find my benefits, health, and services in a more precise and clear fashion.

## Resources
[Section 5 - Data Collection](https://salientcrgt.sharepoint.com/:f:/s/VSATeam/EpF7WFBPYvdMkZnSOHaXrDQBxa2Ienhuwhm1DCs5emhdJQ?e=uYzZdA)

## Tasks
- [x] Compose content to describe Process of reviewing and pulling information from legacy site needed for transformation
* Section 5.2 Planning for Content

## Acceptance Criteria
* Section is drafted on Word document and saved on approapriate section and file located on GCIO/VAMC - Web modernization,  Web modernization.

VAMC - SPRINT 69

**Comment by larrywest52** [comment]
DONE
