### ISSUE TITLE
Request preliminary ATO review: HLR

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3821]
#### What data are you collecting? For example, what data are you requesting from users?
- Nothing is being stored on the va.gov's end; we are working with the Lighthouse team to use their API to update Caseflow.

#### Where does that data come from? For example, what API endpoint are you getting the data from?
Need to check with Silvio the API endpont.

**Comment by luke-gcio** [comment]
Not necessary, will be part of collab cycle.
