### ISSUE TITLE
[VAMC] VAMC - Run Book content documentation for section - 2.7 Set and communicate standards and change management

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38228]
## Story
As a Veteran I need to know that future web modernization groups will have a run book to modernize Veteran websites, so I can find my benefits, health, and services in a more precise and clear fashion.

## Resources
[Section 2 - Lessons Learned](https://salientcrgt.sharepoint.com/:f:/s/VSATeam/EsabaJ7COx1KsEiIIuxDM-0BCIz47rjAYk7MuPX54Qgj1w?e=1ZHemY)

## Tasks
- [x] Compose content to describe Process of reviewing and pulling information from legacy site needed for transformation
* Section 2.7 Set and communicate standards and change management

## Acceptance Criteria
* Section is drafted on Word document and saved on appropriate section and file located on GCIO/VAMC - Web modernization.

**Comment by ltrombley** [comment]
Task #38228 - VAMC - Run Book content documentation for section - 2.7 Set and communicate standards and change management - is Complete and moved to Validate.
