### ISSUE TITLE
[SW-Content] Review tickets in backlog and update story status in comments [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38237]
## Story
As a SW Content editor I need to know the status of all the current stories, so I can quickly updated the next steps and move the story along.

## Resources
* Sitewide backlog

## Task(s)
- [x] Review known stories in Backlog and review, get status information from owners, and update status in comments section.

## Acceptance Criteria
* Stories in backlog have update status information in comments section.

**Comment by RLHecht** [comment]
I've updated all stories in the backlog that didn't have recent comments explaining where the work stood. Moving this to validate.
