### ISSUE TITLE
Vets - APi Endpoint - API Schema - Hearing Aid Battery MOC

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3823]
## User Story:
As a Back-end dev, I need to complete the API schema 1-page spec so that I can propose specifics to our front-end devs.

### Front-end Sign-off
- [x] JSON schema for battery status
- [x] Describe it in no more than one page, with examples for GET and PUT
- [x] Meet with Front-end Devs to review schema

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Agreement on API schema from Front-end
- [ ] Preliminary comment on API schema from DLC IT team

## Next Steps:
- Build skeleton code for Controller, Router , and Serialize
- Build skeleton code for Service Object 

##Blockers / Dependencies 
- [ ] Agreement from Front-end Devs

## Configuration
- [ ] **Attached to a Milestone**: 9
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`,)
- [ ] **Labeled with Practice Area**: backend
- [ ] **Labeled with Type**: documentation

**Comment by jcosta-gcio** [comment]
Here is the MOC Data for the hearing Aid 
[MOCData-HearingAid.json.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/3941458/MOCData-HearingAid.json.txt)

**Comment by jcosta-gcio** [comment]
Hearing Aid Endpoint Data in Excel format

[HearingAid-Batery-MocData.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3945517/HearingAid-Batery-MocData.xlsx)

**Comment by jcosta-gcio** [comment]
The URL for the Endpoint is as follow 

http://localhost:3000/v0/dalc/hab/[ID]

Example: http://localhost:3000/v0/dalc/hab/1010

Once I have a STG link I will add another comment
