### ISSUE TITLE
Mark - Knowledge Transfer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38240]
## Problem Statement
Mark needs to transfer knowledge to the other frontend engineers prior to exiting the project. Following should be considered in the transfer:
- [x] Code knowledge
- [x] Process knowledge
- [x] Any ongoing work that may not be finished prior to exit

**Comment by sarahknoppA6** [comment]
includes full auth w/pre check in flow currently

**Comment by sarahknoppA6** [comment]
we have a knowledge transfer session set up for mark's full auth work on 4/1 with the engineers.

**Comment by mdewey** [comment]
Notes from Transfer session

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-docs/edit-demographics/full_auth_notes.md
