### ISSUE TITLE
Generate JSON or HTML file of Content to Be Translated

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38259]
## Problem Statement
We need to get the Spanish translation for all content, messages, controls and prompts in our CI and PCI features.

## Acceptance Criteria
- [x] Find out if they have a template we can use?
- [x] Extract content to be translated from the application or product guide
- [x] Prepare JSON or HTML file with the content to be translated

**Comment by loripusey** [comment]
@acrollet can you work with UX to determine the best way to extract our content (either from the application or the product guide)?

**Comment by acrollet** [comment]
The JSON file and word count have been shared with UX here: https://dsva.slack.com/archives/C02G6AB3ZRS/p1647034799986349?thread_ts=1646939732.858079&cid=C02G6AB3ZRS

**Comment by niradatta1** [comment]
@kristenmcconnell and I are meeting with Danielle on Friday to confirm if the json file is OK to submit as is, or if there is a preferred template we need to use.

**Comment by niradatta1** [comment]
Shared with Danielle who will be submitting the file to the State (unable to link directly to the file her, but it can be found in the Slack thread @acrollet posted). 'cc @kristenmcconnell
