### ISSUE TITLE
Pre-Check-in for Telephone Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38258]
## Background and agreement from Patrick to release this feature
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1657636994325549)

## CHIP Dependencies (COMPLETE)
https://github.com/department-of-veterans-affairs/chip/issues/864#issuecomment-1157873275

## Stop Code Info
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/dc4bfe71-faa4-4497-8512-3f4d55a9404f)

## Feature Flag
check-in-experience-phone-appointments

All code should be behind the feature flag

## Problem Statement
Currently, pre-check-in is only available for in-person appointments. As part of the roll-out to VIZN 8, we are being asked to extend the use of pre-check-in to telephone appointments.

We need to determine an MVP for this based on research efforts.

Email from Kristen indicating that we will be focusing on phone appointments:
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/2f25646f-8f89-476d-8b75-bf966aa2bd62)

**Comment by loripusey** [comment]
@acrollet The CHIP [dependency ](https://github.com/department-of-veterans-affairs/chip/issues/864#issuecomment-1157873275) is in progress this sprint; can you touch base with CHIP and let me know if we think we can get this Epic out this sprint so I can update the release date; thanks

**Comment by acrollet** [comment]
@Hortonio says the ETA is July 12th :-)

**Comment by loripusey** [comment]
@brianseek it appears that all of the work has been completed for this epic; what were our plans for testing this?

**Comment by acrollet** [comment]
The CHIP PR has been merged, we should be able to test everything on staging after the next CHIP staging deployment. (We can request a deployment if we want, otherwise there'll probably be one in the next day or two anyway)
