### ISSUE TITLE
[Research] - Determine MVP Scope for PCI for Virtual Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38261]
## Problem Statement
As a team, we need to understand what is required to support CI and PCI for virual appointments and determine what we can accomplish by the May 2 rollout of VIZN 8.

## Acceptance Criteria
- [ ] Talk to vetext (Shane Elliot) (phone)
- [x] Talk to Pauline Anderson (video) (Stephen might have other stakelholders for us to talk to)
- [x] Document current processes
- [ ] Recommend an MVP for this feature
- [ ] Run MVP by Stephen and get buy in

**Comment by kristenmcconnell** [comment]
Outline for 3/14's conversation with telemedicine stakeholders: https://dsva.slack.com/archives/C02GXKL8WM6/p1647014653764989

**Comment by kristenmcconnell** [comment]
After talking with VVC stakeholders, Pauline and Dr. Gilpen, it was determined that our scope will consist of only telephone appointments for now. 

As a result, I messaged Shane Elliott over Slack late yesterday to try and schedule a meeting to understand more about telephone appointments.

**Comment by kristenmcconnell** [comment]
We created a [GitHub page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/telephone-appointments). We will list the scope we have determined, our outstanding questions, and our next steps. Nira will update ticket when complete.

**Comment by niradatta1** [comment]
Link to the [git-hub page ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/telephone-appointments/README.md)with our initial discovery, research scope and next steps.
