### ISSUE TITLE
[Design] Update Retries Documentation

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#38268]
# Description
The retries sign-in wording has been updated. See [slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1646843282890739?thread_ts=1646772434.302529&cid=C02GXKL8WM6).

The new wording needs to be added to our [error message source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) and Sketch. 

The product guide will be added within https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/37900

# Tasks 
- [ ] Update source of truth
- [ ] Update Sketch
- [ ] Talk to Nira when done

# Acceptance Criteria
- [ ] Documentation updated

**Comment by ytsaoca** [comment]
Check-in login error
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/1KMbqy4
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/ZOo3YgY

Pre-check-in login error
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/Qb5E7q7
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/JndY4v0

**Comment by kristenmcconnell** [comment]
Reviewed this ticket. It looks like the [source of truth GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md

![Screen Shot 2022-03-17 at 3.33.58 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/07623d5c-7c30-47c4-9cb5-549aa9bb892f)
![Screen Shot 2022-03-17 at 3.34.17 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/47693b7a-bac6-4ded-b17b-399ce2502763)) still needs to be updated.

**Comment by ytsaoca** [comment]
Updated ![Screen Shot 2022-03-18 at 11.06.34 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/3d0c612f-d790-43be-8795-a321c01377e6)![Screen Shot 2022-03-18 at 11.09.30 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/e0014ecc-4cb6-465f-8513-1927875e5261)
