### ISSUE TITLE
Explore options in fixing language parameters on PDF

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#38267]
- [x] Programmatically update language parameter for accessibility 

Note: May be blocked if IRS has locked PDF

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/31140a5f-71a9-41a4-b9f4-f5aaee9b16fb)

**Comment by tameracorson** [comment]
LInk to testing of final IRS document https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/Accessiblity/Accessibility%20check%20new%20IRS%20document%203.25.2022.pdf

**Comment by tameracorson** [comment]
Link to platform guidance https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-request-support-from-VA-508-Office.1857913061.html

**Comment by tameracorson** [comment]
Link to ticket for assistance from VA accessibility office of 508 compliance https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/Accessiblity/Accessibility%20check%20new%20IRS%20document%203.25.2022.pdf
