### ISSUE TITLE
Access for Teagan Stephenson

### ISSUE THREAD

**Issue by stephte** [department-of-veterans-affairs/va.gov-team#38278]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Magnum Opus - Paula G. Mendoza

### Your Name

Teagan Stephenson

### Your Email

teagan.stephenson@bracari.com

### Name of Your Team

1095-B team, Backend Engineer, MO

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQd9Wb42G7xTJmomvVCLSj+TmtEdbrAPFvcZGVAA3gBxmX+7kStq6Js7WfNvmYEjllRZA1m/LqlAjeX423JsH1Gsb07hUdz/R03Z+lyvOA5obnUy6Bcef+qbl9iv3SQBN5fRxxhQ9fJV6eTnPKub8SCtedAcYfw3tmKNoASIkU31QqMkEdEn2CHI99whEytnLTxa3PLY0DTqR3uUJTXyso13H/zsKAjWVsi8lNTKwHB5HSaAS2y4Dwk2KjDzpP0A9A3mtp26Ys3XHERvxls2h2r033VncS+K5vPvCtGl8qS5luL7MqeZMq7IE5zBClHV/qOp+dd8NFxIas/InRqPRGxFkRXl0mha2fMyK4IhGqMMvYQ4hjBv3aof7ojvAJrvwl3jHENHNKjsKePs1KfAYd5BuBI7U1z7whBTmU2jOOmIFZ1badDmfS8uBqQZu3VZhtAqFnSOfODdbxeo9qgnXw7D1pAtUEzPUenTSK1ctJ9A3jh+VQH3Xo1OrtBU5+2BE= mac_de_teagan@Teagans-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Comment by stephte** [comment]
thank you!
