### ISSUE TITLE
[Research] - Auth Profile - MyHealteVet  Research - Prepare questions for MHV coordinators & help desk staff

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38279]
## Background
As part of the research, we will want to talk with MHV coordinators and help desk staff

## Tasks
- [ ] Prepare questions for MHV coordinators & help desk staff

## Acceptance Criteria
- [ ] Prepare questions for MHV coordinators & help desk staff

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO I added this to the current sprint

**Comment by andaleliz** [comment]
Per conversation w/ Susan Haidary + Brenda Torres-Hill, we don't need to interview these folks anymore.
