### ISSUE TITLE
[Research] - Auth Profile - MyHealtheVet Research - Kick off recruiting for research

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38275]
## Background

After the conversation guide and research plan have been approved, we will need to kick off the recruiting effort for this exercise.

## Tasks
- [ ] Kick off recruiting with Perigean

## Acceptance Criteria
- [ ] Kick off recruiting with Perigean

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO this isn't needed since we have the issue where I submit the plan and guide to OCTO; OCTO will send to Perigean once they approve.
