### ISSUE TITLE
Contact Center Review | 1010 EZ Team | Short-form 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#38288]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description for 10-10EZ Short-Form

In order to improve the submissions and user experience for Veterans applying for health care using the online 10-10EZ application, we are looking to implement the ability to recognize automatic qualifiers and use those to skip portions of the online form. This initial release uses the Veteran's disability rating if 50% or higher, to skip sections of the form containing information that is no longer relevant, such as the household and financial information.

### Launch Date

April 2022

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
[10-10 Short-Form Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/HCA.Product.Guide.shortform.FinalDraft.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @SKasimow. Just checking in to see if you have a draft ready on this one.

**Comment by SKasimow** [comment]
Hi - nope,  haven't started yet; just wanted to get the ticket opened so we could get going :)

cc @Dene-human

**Comment by starlow00** [comment]
Hi @SKasimow. Here are the two guides to which I have access. One appears to be the same you link to above.
[HCA.Product.Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8269025/HCA.Product.Guide.docx)
[Online-10-10CG-Product-Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8269026/Online-10-10CG-Product-Guide.docx)

**Comment by SKasimow** [comment]
@starlow00 thanks so much Steve!

**Comment by starlow00** [comment]
Hi @SKasimow .
[HCA.Product.Guide.ShortForm.CC.draft1_srt_033122.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8393720/HCA.Product.Guide.ShortForm.CC.draft1_srt_033122.docx)
 This draft of the short-form looks good. I gave it some polish. If it works for you, I can share a copy with VEO.

**Comment by SKasimow** [comment]
@starlow00 - yes this looks great!! Thanks for the polish!!! Will send over next flow shortly :)

**Comment by SKasimow** [comment]
@Dene-human here is the product guide for the auth/50% flow: [here](https://github.com/department-of-veterans-affairs/va.gov-team/files/8393720/HCA.Product.Guide.ShortForm.CC.draft1_srt_033122.docx)

**Comment by SKasimow** [comment]
@Dene-human and here's the self-disclose version which just needs a bit of polishing: [here]([https://app.zenhub.com/files/133843125/4c1ddd59-2dd3-4498-9708-c460f0065e90/download](https://app.zenhub.com/files/133843125/4c1ddd59-2dd3-4498-9708-c460f0065e90/download))

**Comment by starlow00** [comment]
Hi @SKasimow . Just checking in to see when the expanded portion of this will be ready for me to review. No rush on my part, just wanted to make sure I was updating our team's sprint plan.

**Comment by hdjustice** [comment]
Hi @starlow00 - I have transitioned to the 10-10 team now (Sharon is on the Auth Exp-Profile team!), and this guide update will be done in the next day or so.  Thanks so much for checking in!

**Comment by starlow00** [comment]
Hi @hdjustice. Just following up to see if the guide update is ready. Thanks!

**Comment by hdjustice** [comment]
Hi @starlow00 - I thought we would be ready last week, but we decided to integrate the new feature into the overall product guide so the centers would not have to keep up with multiples.  It is being worked on as we speak, and hope to have it to you by the end of this week.

**Comment by hdjustice** [comment]
@starlow00 - We have finallly completed the final draft of the guide to include the Short Form flow within the current process.  We have also updated screenshots and information, since this document had not been updated for some time.  We would recommend a full review of the guide, and welcome any feedback you have.  Thank you!

**Comment by starlow00** [comment]
Hi @hdjustice. Here's the draft after my review. Looks good, only a few small things. After you review, I can make sure the clickable TOC page numbers match and then share with VEO. Thanks!
[HCA.Product.Guide.shortform.FinalDraft_srt_05232022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8758663/HCA.Product.Guide.shortform.FinalDraft_srt_05232022.docx)

**Comment by hdjustice** [comment]
hi @starlow00 !  Thanks so much for the quick review!  Your suggested changes look good to us.   Let us know if anything else is needed for VEO approvals.

**Comment by starlow00** [comment]
Sounds good! Sharing with VEO.

**Comment by starlow00** [comment]
No changes from VEO, thus approved. Attaching guide for reference.
[HCA.1010EZ_shortform_05252022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8789700/HCA.1010EZ_shortform_05252022.docx)

**Comment by hdjustice** [comment]
@starlow00 Fabulous news, thank you Steven!
