### ISSUE TITLE
[R&D] Get an Estimated word count of the entire workflow for CI and PCI

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38301]
## Problem Statement
 In order to allow the translation team to do budgeting, we need to provide them with a word count.

## Acceptance Criteria
Gather word count for:
- CI workflow
- PCI workflow
Provide to translation team

## TO DO
- [x] Check to see if the word count is still needed (DONE)
- [x] What type of estimate do they need (DONE)
- [x] Check with Engineering to see if they have an automated tool that can get the word count
- [x] Get the word count (either by UX doing it or engineering doing it)

**Comment by kristenmcconnell** [comment]
File posted in [Slack](https://dsva.slack.com/archives/C02G6AB3ZRS/p1647034799986349?thread_ts=1646939732.858079&cid=C02G6AB3ZRS)
