### ISSUE TITLE
Capture Type of Care, Provider's Info in Loki 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#38313]
## Description
Based from our recent research study on the appointment list, Product and Design would like to see if we have data around showing the type of care and displaying the provider's information. (Spike Ticket #38010) 

---

## Requirements
Create a new iteration of the logging to capture the following details in Loki:
- show which appointments have the type of care
- show which appointment does not have the type of care
- show which appointment have the provider's information
- show which appointment does not have the provider's information 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ajmagdub** [comment]
The type of care and provider info is now logged into Vets API server logs.  Next, we should determine how long to let the logging run, then let the logging run (remove the logging code when done), then collect and format the results so they can be analyzed.

**Comment by ajmagdub** [comment]
Below is the summary of the data collected; a spreadsheet with the data collected is attached for a more detailed view.

Over one week, approximately 675,000 appointments were sampled. with 472,552 (69.91%) Clinic, 125,619 (18.58%) Telehealth, 38,905 (5.76%) phone, and 38,870 (5.75%) Community Care.
![Counts_of_Total.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/72f101b2-150c-47b9-afd8-1841e6625719)

The majority of appointments with Type of Care were Clinic appointments: 293,414 Clinic appointments with Type of Care; 71,759 Telehealth appointments with Type of Care; 1,109 Phone appointments with Type of Care; and 747 Community Care appointments with Type of Care (See Pivot Tables tab in the attached spreadsheet for a detailed breakdown).![Type_of_Care_Count.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/d02c3ff5-48fc-4be5-a2f7-25dec87e75c7)

The Treatment Specialty were all from Community Care appointments (See Pivot Tables tab in the attached spreadsheet for a detailed breakdown); 38,123 Community Care appointments with Treatment Specialty.![Treatment_Specialty.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/25c9a7af-a4ea-4c3b-acdf-e2f5755004a9)

The majority of the appointments with Provider Information were Community Care appointments: 37,953 Community Care appointments with Provider Information, 10,649 Telehealth appointments with Provider Information, 37 Clinic appointments with Provider Information, and 1 Phone appointment with Provider Information (See Pivot Tables tab in the attached spreadsheet for a detailed breakdown).![Provider_Info.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/748db6e8-5a99-4d36-a557-b9d15c701a07)

**Comment by ajmagdub** [comment]
[https://app.zenhub.com/files/133843125/56ae344b-b244-48c9-b38b-5e08bf0ef9e1/download](https://app.zenhub.com/files/133843125/56ae344b-b244-48c9-b38b-5e08bf0ef9e1/download)

**Comment by ldelacosta** [comment]
Part two for the logging was created [ticket #57255](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/57255)
