### ISSUE TITLE
Travel Logistics for Research Trip to STL

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38311]
## AC
Determine:
- [x] Poster we are using and print them, if needed
  - [x] Talk to sites to determine what poster they have displayed (Lori/Sarah to help us find out and talk to Kaytona).
- [x] Determine Who's going & Book flights
- [x] Sync with VSE team and whoever is traveling as well (Talk to Katherine Shelor)
- [x] Submit cost estimates

**Comment by kristenmcconnell** [comment]
People traveling:
- Zach, Ya-ching, Ben
- Back-ups: Kristen and Nira
- Someone from the VSE team

**Comment by kristenmcconnell** [comment]
Blocked until we know what sites we are visiting.

**Comment by benbrasso-agile6** [comment]
11x17, 8 1/2 x 11

3 per office 

@benbrasso-agile6 will add additional information here
