### ISSUE TITLE
[FSR] Combined VBA/VHA FSR with the updated list loop designs

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38319]
## Issue Description
The online [Financial Status Report (FSR)](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) currently allows Veterans to request financial assistance with their benefit-related debts. Our team is now working to incorporate medical copay statements into the FSR while incorporating usability findings that replace the form's list loop components. 

We need to consolidate [the combined FSR prototype](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142318108/simulate/sitemap?mode=i) and [the redesigned list loop prototype](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages//simulate/sitemap?mode=i) into one.

I think the easiest way to do this is to incorporate the combined FSR prototype pages relating to VHA debts into the list loop redesign prototype because there are fewer art boards to update. 

Both of the prototype files can be found in the Debt Resolution Sketch workspace under the names:
- Combined FSR (VA5655)
- Financial Status Report (VA5655) - V2

---
## Tasks

- [x] Incorporate the following pages into [the Financial Status Report V2's prototype](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/simulate/sitemap?mode=i):
   - [The debt selection page - default state](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617814/simulate/sitemap?mode=i)
      - [The debt selection page - error handling](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617813/simulate/sitemap?mode=i)
   - [Resolution options - all debts waived](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617671/simulate/sitemap?mode=i)
      - [Resolution options - all debts waived + education debt checkbox](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617670/simulate/sitemap?mode=i)
   - [Resolution options explainer](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617672/simulate/sitemap?mode=i)
   - [Benefit debt resolution options](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617679/simulate/sitemap?mode=i)
      - [Benefit debt - waiver](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617678/simulate/sitemap?mode=i)
      - [Benefit debt - extended monthly payments](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617675/simulate/sitemap?mode=i)
      - [Benefit debt - compromise offer](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617674/simulate/sitemap?mode=i)
   - [Copay debt resolution options](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617677/simulate/sitemap?mode=i) 
      - [Copay debt - extended monthly payments](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617676/simulate/sitemap?mode=i)
       - [Copay debt - compromise offer](https://preview.uxpin.com/d8307359c0a22d9e09b86d4803be3dce030d24ff#/pages/142617673/simulate/sitemap?mode=i)

**Please let Riley know if you have any questions!** 

## Acceptance Criteria
- [ ] The prototypes have been consolidated into the FSR V2 prototype and the UXPin is linked in this ticket

**Comment by aagosto90** [comment]
Work is complete except for one question for @rileyorr so we'll wait to close it until she returns on 3/15. My question is whether we need to keep two pages that are currently in the [UXPin prototype](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146486998/simulate/sitemap?mode=i) or if they're now outdated: "Resolution Options" page and its sub-page "Resolution options, Extended Payments". The Sketch file is also updated.

**Comment by rileyorr** [comment]
Good morning @aagosto90! Thanks so much for putting this together - it looks great. We don't need [the existing resolution options page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146486998/simulate/sitemap?mode=i) or [the sub-page for extended payments](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146486999/simulate/sitemap?mode=i).

**Comment by rileyorr** [comment]
Hi @aagosto90! What size would you give this ticket? I forgot to ask when I created it for ya
