### ISSUE TITLE
DAST Scan

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#38316]
# Description
OAuth Scan using the Zap tool.  Scans our code as it goes into production to ensure that it does not have any vulnerabilities.

# Acceptance Criteria (Engineer Check Off)
- [x] DAST Scan is set up in Zap
- [x] Results post to Github

# Technical Description

# Deliverables (Product Manager Check Off)
- [x] Scan results in Github [LINK](https://app.zenhub.com/files/133843125/1ba9dc07-6c1f-4b57-9111-2d8bfa5bf6e2/download)

# Expected Finish Date
- [x] March 30

**Comment by sylvesterlee1911** [comment]
Documentation folder has been created, scans, folder for dast has been created.  Documentation has started to be created.  Should include links to setup install configuration.  Onbaording.  - Initial dast is setup with default policy, using owasp zap.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/scans/dast

**Comment by sylvesterlee1911** [comment]
Results uploaded to git folder.[https://app.zenhub.com/files/133843125/1ba9dc07-6c1f-4b57-9111-2d8bfa5bf6e2/download](https://app.zenhub.com/files/133843125/1ba9dc07-6c1f-4b57-9111-2d8bfa5bf6e2/download)

**Comment by joeniquette** [comment]
@sylvesterlee1911 Please dont post security scan results to the public folder, they must go in the sensitive folder [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity).

Also can you publish results that only have the staging.va.gov domain, not the other domains please. Then post the document in the correct folder and delete the old results from the public side folder.

**Comment by sylvesterlee1911** [comment]
noted.  changing to the private.  then deleting what was in public.

scheduling to rerun the scan.

**Comment by sylvesterlee1911** [comment]
will close once scan is reran and data is updated. Only VA.GOV extensions.

**Comment by sylvesterlee1911** [comment]
Include in documentation- step one set up as a manual scan so that you can enter credentials.  Then automate.

**Comment by joeniquette** [comment]
Looks good to me!
