### ISSUE TITLE
QA Feedback - Staging Review - Design System Team - Modal web component

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#38329]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

https://github.com/department-of-veterans-affairs/va.gov-team/issues/37957

**Comments:**
- None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- When the close button is hidden, the modal can still be closed with the `Esc` key. Determine if this is acceptable behavior.

**Consider:**
None

**Comment by andresriveratoro** [comment]
@ddzz `va-modal` was updated to remove the option to hide the close button. Users have at least 2 ways to close the modal by default: close button or escape key. Developers also have the option to allow user clicks outside of the modal contents to close the modal. Thanks!

https://github.com/department-of-veterans-affairs/component-library/pull/298#issuecomment-1064440433
