### ISSUE TITLE
[FE] Display Message when General Error Occurs during Pre-Check In

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38346]
## User Story
As a Veteran, when I try to complete pre-check-in and there is a general error, I would like see some information telling me what to do next.
 
## Wireframes
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/pan0jAA
    
## User workflow
- When I
     - Click a pre-check-in link and there is a general error at any point in the pre-check-in process
- Then I
    - See a message telling me that they system is unable to complete the check in
     
## To Do 
- [ ] Replace content of existing general error message
- [ ] Add the date, if possible, for when can check in online (4 digits for the year [i.e. MM/DD/YYYY])
@zach-park to double check the format for the date

**Comment by brianseek** [comment]
@ytsaoca This is ready for review. Here are screenshots where we have the appointment date data and where we don't.

![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (4).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/507d64e6-7ea8-47de-bae5-bd3321a2092c)

![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae28.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/4ef17b12-1d44-402b-ba4b-0f5f3ffb9333)

**Comment by brianseek** [comment]
@zach-park see screen shots in comment above.

**Comment by loripusey** [comment]
Looks good.
