### ISSUE TITLE
[Support Slackbot] Add new dropdown for request type

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#38353]
@zachclarity Has requested that a new field be added to the slackbot for getting more information about the support request. Specifically it would be helpful to know who the request is coming from. ie. If it is a developer who is working off of a local environment.

My first attempt at defining this field is to create a category field with options like the following:
- Pull Request
- Access Request
- Development Question
- Build Failure
- Outage
- Other

**Comment by rmtolmach** [comment]
@powellkerry, I was talking to Jesse about this and if it's useful, we could engage the Service Design Team to help us collect feedback on which categories would be the most helpful to SRE and our users (we don't want to disrupt ppl disrupting support).
