### ISSUE TITLE
[Support Slackbot] Update team names

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#38352]
A request has been made to update team names: https://dsva.slack.com/archives/CJRQ85PQB/p1646681525021259

The requests asks that we replace 'Collab Cycle' with 'Governance Team' in the Channel Topic. Also It is suggested that 'Collab Cycle' be retained in the drop down when making a support request and that 'Governance Team' be added. Both of these selections would make assignments to the 'Governance Team'

Restrictions:
- There is a 250 character limit on the channel topic which we are already very close to. Changing the text/structure of the channel topic would be necessary to make this change.

**Comment by npeterson54** [comment]
It looks like Backend Tools Team needs to be updated to "Console Services Team".
