### ISSUE TITLE
Business intake form for Authenticated Exp - VA.gov Profile

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38350]
## Business Line  
VBA

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
Today there are roughly 340K Veterans whose mailing addresses have been flagged as invalid in VA Profile, and they are not made aware of it when visiting VA.gov.  The business outcome will be that Veterans will be made aware that their address has been flagged and given the opportunity to update it or confirm that it is indeed correct.  Ultimately, this means that fewer Veterans will fail to receive important mail and/or prescriptions from the VA.

## What is an overview of the notification use case? (required 3-5 sentences) 
 We would initially send an email to all Veterans whose mailing addresses have already been flagged, as well as an event-based notification that is sent when a new flag is added to a mailing address.

**Comment by Samara-Strauss** [comment]
@mjones-oddball or @bevnobev does this still need to be open? Happy to leave it if so, but it's not clear to me whether we are using this ticket or now.

**Comment by mjones-oddball** [comment]
@Samara-Strauss Let's hold off until we discuss at our sync on Tuesday.

**Comment by SKasimow** [comment]
Hi @mjones-oddball @bevnobev -  do we need to keep this open or ok to close?

**Comment by mjones-oddball** [comment]
@SKasimow Ok to close, doing so now!
