### ISSUE TITLE
Add pagerduty banner alert for login.gov

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#38358]
Create a metric within prometheus that measures the success rate of login.gov in production. The rules are [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/external_service.rules.j2) and should go below the three we currently have for idme, mhv, and dslogon.

**Comment by bosawt** [comment]
@joeniquette Can we close this ticket?

**Comment by joeniquette** [comment]
No we need to have something that displays to the user automatically when login.gov isn't functioning. @ianhundere Im throwing this one into your bucket.

Lets make it so when the return percentage of login.gov drops below 35% we throw up the banner similar to how we do for dslogon and the other creds.

**Comment by asg5704** [comment]
Requirements:
- [ ] Creation of a new external service in PagerDuty for Login.gov
- [ ] Ensure vets-api integration with the External Services
  - [ ] Verify for `/v0/backend_statuses` that `logingov` is in the list of external services
  - [ ] Verify for `/v0/backend_statues/logingov` that it reports as expected
- [ ] Ensure vets-website integration with Backend Statuses
  - [ ] Verify on Sign in Modal & Unified Sign in Page that a bad Login.gov status will display

**Comment by rileyanderson** [comment]
> Investigating why `logingov` is not showing up in `/v0/backend_statuses` in deployed envs

This is actually working on `prod` and `sandbox`. `dev` and `staging` expect different PagerDuty prefixes 😒 

- Production - `External: {service_name}`
- Sandbox - `External: {service_name}`
- Dev - `Dev: External: {service_name}`
- Staging - `Staging: External: {service_name}`

Created services in PagerDuty:
- [Staging](https://dsva.pagerduty.com/service-directory/PESHE6D)
- [Dev](https://dsva.pagerduty.com/service-directory/PRWS6JU)

PR to fix Dev and Staging:  
- department-of-veterans-affairs/vsp-infra-application-manifests#1900

**Comment by rileyanderson** [comment]
Confirmed working in all environments

**Comment by asg5704** [comment]
![homer](https://github.com/department-of-veterans-affairs/va.gov-team/assets/67602137/1dddf04b-a705-4696-9c45-b2282802aaa7)
