### ISSUE TITLE
Design Feedback - Staging - Design System Team - Modal Web Component

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#38354]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- There isn't a hover state for the close icon. Close icon hover state color should be .vads-u-color--primary-darker / $color-primary-darker or (#003E73).
- Button text should be sentence case.
- Buttons should span the width of the content when they can’t fit side by side in the viewport. Should appear like this https://d.pr/i/9SOfni instead of https://d.pr/i/0N03VM 

**Should:**
- None

**Consider:**
 - None

**Comment by andresriveratoro** [comment]
@seanasewell I've corrected this at https://github.com/department-of-veterans-affairs/component-library/pull/298#issuecomment-1064440433. Thanks!
