### ISSUE TITLE
Resolve Dependabot alerts in vets-design-system-documentation

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#38356]
## Description
As of 3-10-2022, we have 15 open Dependabot alerts in the `vets-design-system-documentation` repo that need to be resolved.

## Acceptance Criteria
- [ ] All critical, high, and moderate Dependabot alerts have been resolved.

**Comment by pdavies88** [comment]
We will need to add a resolution file like we have on `component-library` for `glob-parent`
`glob-parent` is a dependency of `gulp` so we'd need to update `gulp` to fix overall.
Also the rest of the errors will be taken care of by: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/679

**Comment by pdavies88** [comment]
Per: https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions
Leveraging: https://github.com/rogeriochaves/npm-force-resolutions
To solve issues
