### ISSUE TITLE
IA Review of Form Detail Landing Pages

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#3836]
This ticket is related to ticket #2020. 
 
We are developing 25 custom search landing pages for the 25 top-ranking VA forms, as well as 12 additional pages for forms that have an online tool alternative. 

Current detail pages exist for each form. We need to determine the best use of existing versus new urls for each page, and create breadcrumbs. 

While VA.gov's forms search page results take users directly to the form itself, an external search will take users to these new search landing pages. Page patterns vary depending on whether there is an online tool equivalent to the form, and/or multiple versions of the same form (such as Spanish-language versions).

**Comment by Karak888** [comment]
@mnorthuis @lwalsh617 this seems similar to a request from @ncksllvn in ticket [](url)https://github.com/department-of-veterans-affairs/va.gov-team/issues/3548 but sounds like we are awaiting next steps from @jenniferlee-dsva as she had a conversation with Mikki per #3548 stating that there was an approach but needed recommendations.  Please let me know if we should keep this ticket or follow the one that Nick created.  Thanks!

**Comment by mnorthuis** [comment]
This appears to be for the search landing pages, which I understood to be sort of a separate work effort from the core tool.

**Comment by Karak888** [comment]
@mnorthuis I agree.  @ncksllvn I am going to close this ticket and keep your #3548 as the main ticket.  Please let me know if you need it re-opened.  Thanks!

**Comment by jenniferlee-dsva** [comment]
Hey @Karak888  @mnorthuis @lwalsh617  @ncksllvn - this ticket is (I believe) to determine the IA and urls of the __form 'master detail' landing pages__ per Mikki's comment above . It is NOT the main/default search and search results page. 

So it is separate from Nick's [#3548](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3548), which duplicates Mikki's [#3887](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3887). 

THIS ticket does need Mikki's consult, so I wouldn't necessarily close it.

And to be clear, there are 2 kinds of form 'master detail' landing pages that need IA and URL support:
1 / The customized landing pages (for those 25-35 top forms)
2/ The standard landing pages (for all the other forms that we are not customizing the content for)

__Here is an example of a current existing form master detail landing page URL:__
https://www.va.gov/vaforms/form_detail.asp?formno=10ez  -- each landing page has a unique 
"?formno=XXXX" string. 

@lwalsh617 has the GA data on these landing page URLs, so we can share that with you Mikki as part of your assessment.

**Comment by Karak888** [comment]
@peggygannon @lwalsh617 @jenniferlee-dsva - Laura to get together a meeting to determine helpful links on forms pages. 

@Karak888 to create a ticket for usability study, PDFs to @1Copenut  for screenreaders.

**Comment by mnorthuis** [comment]
@lwalsh617  Can you provide a list of all forms you plan to do custom landing pages for?   I will need that to review and determine a URL pattern for the custom ones as well as the standard ones.  Thank you!

**Comment by lwalsh617** [comment]
@mnorthuis - Please see the attached copy deck. Page 1 has a table of contents that lists all the forms we're doing the custom landing pages for. (25 top forms, plus 7 forms that aren't in the top 25, but for which there are online tools). Let me know if you have questions. 
[va-forms-slps-copy-v1.2_01-14-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4072511/va-forms-slps-copy-v1.2_01-14-20.docx)

**Comment by mnorthuis** [comment]
@lwalsh617 @jenniferlee-dsva @ncksllvn 
Some considerations for handling the redirects of the legacy landing pages.  I believe we originally talked about option 1, but want to make sure we are aligned on the approach. 

**Option 1**
- Select key legacy landing pages will be redirected to a specific new form detail page (the top 25 custom pages)
- All other legacy landing pages will be redirected to the VA Forms search tool
- Considerations: Key page redirects will ensure we maintain/transfer SEO value to the new detail page, while the general redirect to VA forms search tool will mean SEO value on legacy landing pages will be lost/not transferred to the new form detail page. If SEO value on many of the landing pages is very low, this is a more simplistic redirect approach. The general redirect approach will also mean that users who click through old links will have to execute their search again in the forms search tool to get to a result.

**Option 2**
- All legacy landing pages are individually redirected to a corresponding new form detail page
- Considerations: We maintain all SEO value on all legacy landing pages without adding additional steps for our users. This is an more extensive mapping exercise.

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - RE option #1 - Not quite right. I think you're mixing up THE OTHER landing pages which are part of redirecting as part of ticket #5163 (which are the forms search and related pages currently linked to/from the live forms search page). 

I will add edit/comment ^.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva I think we need to talk through this, I was not mixing up the redirect tickets and stand by my original proposed options.  The difference between, is that for the legacy landing pages that don't have much SEO value, instead of redirecting those to the new landing page, we can just redirect them to the forms search.  The new landing pages will still appear in search.  Its really just whether we want to map all ~550 legacy landing pages to new landing pages. 

Original post: 

**Option 1**

- Select key legacy landing pages will be redirected to a specific new form detail page (the top 25 custom pages) - this means that these legacy landing pages will be mapped to the new landing pages
- All other legacy landing pages will be redirected to the VA Forms search tool - this means that the other 530 legacy landing pages will not be mapped, we will just redirect them to the form search since they don't transfer any SEO value anyway
Considerations: Key page redirects will ensure we maintain/transfer SEO value to the new detail page, while the general redirect to VA forms search tool will mean SEO value on legacy landing pages will be lost/not transferred to the new form detail page. If SEO value on many of the landing pages is very low, this is a more simplistic redirect approach. The general redirect approach will also mean that users who click through old links will have to execute their search again in the forms search tool to get to a result.

**Option 2**

- All legacy landing pages are individually mapped and redirected to a corresponding new form detail page
Considerations: We maintain all SEO value on all legacy landing pages without adding additional steps for our users. This is an more extensive mapping exercise.

**Comment by mnorthuis** [comment]
Recap from @jenniferlee-dsva :

Decision and next steps - re redirecting form detail landing pages. Call with @ncksllvn @mnorthuis @mickin and @jenniferlee-dsva

We will do server-side redirects of form detail landing pages with the following approach:
- For X number of high search value form detail landing pages, we will do 1:1 redirect mapping from the current legacy form detail landing page to the new.
- For the remaining (562 - X) landing pages, we will do a default redirect to the new main search page URL (va.gov/find-forms)

Next steps:
1. Determine the cut-off point for the X number of forms that will get the 1:1 redirect mapping. Jen will review the GA data that Nedie had provided previously and share out info to Mikki, Nick, and Mickin.
1. RE Drupal and dynamic URLs: Investigate how Drupal auto-generated URLs for the basic (not custom) template form detail landing pages can apply the URL pattern recommended by Mikki. @ncksllvn will loop @mnorthuis into ongoing conversations with @kevwalsh re API and other implementation of form detail landing pages in Drupal.

Per @mnorthuis:  Once the above mentioned Drupal conversation(s) and details are figured out, I will finalize the URL structure for this work.

**Comment by kevwalsh** [comment]
For form detail pages, I would have assumed that both "basic" (~470) and "custom" (~30) would follow the same URL structure. I can't think of any reason why they shouldn't, although of course i haven't been present to all these conversations so forgive me if that's already been stated.

**Comment by mnorthuis** [comment]
@kevwalsh Yes, they will definitely have the same structure...I really just need to understand the data and the drupal capability for generating the URL.

**Comment by kevwalsh** [comment]
@mnorthuis there aren't really any constraints in capability. Have you written the ideal spec somewhere? It would be easier to react to that than to talk in the abstract.

**Comment by mnorthuis** [comment]
@kevwalsh working on getting them documented and then will set time up for us to talk through it.

**Comment by MickinSahni** [comment]
On VSA side, re-associating to newer epic for detail landing pages

**Comment by mnorthuis** [comment]
@jenniferlee-dsva Here is the final IA for the form detail pages.  The exact form data to be used to generate the the URL is TBD.   Next step in this is to create the redirect request and a mapping of all the URLs to be redirected. 

cc @kevwalsh This includes some Drupal requirements for generating and locking down URLs.  Let me know if we need to discuss. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-forms-detail-pages.md

The details are documented in GH and will remain accessible so this issue can be closed at your discretion.

**Comment by mnorthuis** [comment]
FYSA - I am revising the IA for the form detail pages based on the decision to make the detail pages part of the UX flow from the forms search tool.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva @stephorkandatx 
IA revised to now show parent/child relationship between Find a form tool and form detail pages.  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-forms-detail-pages.md

**Comment by jenniferlee-dsva** [comment]
Will close this ticket, as this work is completed per this file: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-forms-detail-pages.md
