### ISSUE TITLE
Write net new "QA tools and resources"

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#38375]
# Acceptance criteria
- Net new doc has been added to live Platform website space and is ready to publish; just waiting for twice-weekly deploy

**Comment by lianilychee** [comment]
3/18 Fri:
- today
  - schedule accountability meeting with Peter
  - start writing based on outline of page; can't be more specific bc writing work just beginning

**Comment by lianilychee** [comment]
3/21 Mon:
- blocked by time, but DO have accountability sesh with Peter
- today: prep for Peter session

**Comment by lianilychee** [comment]
Weds 3/23:
- Accountability session with Peter tmr (Thurs)

**Comment by lianilychee** [comment]
Thurs 3/24:
- have something ready to show Peter but confidence is 50%, hoping that can hand over to Peter
- Am on track to hand off to Peter by EOS

**Comment by gmaciolek** [comment]
Fri 3/25:
- Met with Peter and posted meeting notes/action items in QAST docs channel
- We agreed on an overall structure for the page and I'm optimistic we can fill in the details and finalize the doc by the end of next week
- Set up another meeting for Tuesday afternoon

**Comment by lianilychee** [comment]
4/1 Fri: 
- was sick since Tues, refreshing memory on what I have to do
- have already scheduled meeting with Peter Joe and Jill for accountability

**Comment by lianilychee** [comment]
4/12 Tues:
- almost ready to send to Peter, want to incorporate Amy and Lauren's text first

**Comment by lianilychee** [comment]
4/13 Weds:
- told Peter to prioritize Amy ad Lauren's q's

**Comment by lianilychee** [comment]
4/15 Fri:
- wait till Weds till Peter returns

**Comment by lianilychee** [comment]
4/22 Fri:
- will nudge on Monday https://github.com/department-of-veterans-affairs/va.gov-team/issues/39409

**Comment by lianilychee** [comment]
4/25 Mon:
- Jill and Amy to take action based on Peter's response to COnf comment

**Comment by amygoldman** [comment]
Removed "contract testing" section based on Peter's response 

For Tues 4/26: This is a new doc, so it could be moved to/published in Developer docs --> QA testing
