### ISSUE TITLE
[Jenkins] Build fail with non-zero return code error 

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#38380]
## What happened?
Intermittently, a Jenkins build will fail with the error, “non-zero return code”. I looked into this and wanted to document my findings, so hopefully, when this fails again, we can track down the point of failure. 

Failure:
```
16:17:14  TASK [Run Setup] ***************************************************************
16:17:14  Tuesday 01 March 2022  21:17:13 +0000 (0:00:01.616)       0:00:20.464 ********* 
16:17:40  fatal: [ip-172-31-11-251.us-gov-west-1.compute.internal]: FAILED! => changed=true 
16:17:40    cmd: cd /configuration && bash setup-deployment-utility-jumpbox-20220301-211655.sh >> /var/log/cloud-init-output.log 2>&1
16:17:40    delta: '0:00:23.912207'
16:17:40    end: '2022-03-01 21:17:37.772768'
16:17:40    msg: non-zero return code
16:17:40    rc: 2
16:17:40    start: '2022-03-01 21:17:13.860561'
16:17:40    stderr: ''
16:17:40    stderr_lines: <omitted>
16:17:40    stdout: ''
16:17:40    stdout_lines: <omitted>
16:17:40  fatal: [ip-172-31-9-183.us-gov-west-1.compute.internal]: FAILED! => changed=true 
16:17:40    cmd: cd /configuration && bash setup-deployment-utility-jumpbox-20220301-211655.sh >> /var/log/cloud-init-output.log 2>&1
16:17:40    delta: '0:00:24.805369'
16:17:40    end: '2022-03-01 21:17:38.666428'
16:17:40    msg: non-zero return code
16:17:40    rc: 2
16:17:40    start: '2022-03-01 21:17:13.861059'
16:17:40    stderr: ''
16:17:40    stderr_lines: <omitted>
16:17:40    stdout: ''
16:17:40    stdout_lines: <omitted>
```
(seen in [this Jenkins build](http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/1062/console))

[Link to the section of code in update.yml that’s failing](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/update.yml#L118-L135). This line:
`cd /configuration && bash setup-{{ deployment_id }}.sh >> /var/log/cloud-init-output.log 2>&1` does a few things:
1. cd into the configuration directory
2. If that succeeds (`&&`), proceed on to the right side of the `&&`.
3. Run the setup-deployment_id.sh file
4. And redirect all the output from the shell command and any stdout and stderr to the .log file. 

It's failing with a return code of 2. That means there is likely some kind of syntax error happening in a shell file that’s being run. Example of an exit code 2 error:
```
rebeccatolmach ~ cat nada.sh 
#! /bin/sh

empty_function() {}
rebeccatolmach ~ bash nada.sh
nada.sh: line 3: syntax error near unexpected token `{}'
nada.sh: line 3: `empty_function() {}'
rebeccatolmach ~ echo $?
2
rebeccatolmach ~ 
```
The shell file is declared directly above where it's run in update.yml and that _also_ runs a `.sh` file. 

When this does fail, go to [Grafana](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22Loki%20(Utility)%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapp%3D%5C%22jumpbox%5C%22,filename%3D%5C%22%2Fvar%2Flog%2Fcloud-init-output.log%5C%22%7D%22%7D%5D) and look for `cloud-init-output.log`. We want to know if there are any hints or juicy details on why we're getting an exit code of `2`. 
![image](https://user-images.githubusercontent.com/10993987/157748168-1abf02de-93b6-4083-8fea-9ed18c261cc2.png)

## Specs:
n/a

## Steps to Reproduce
Intermittent. There will be a failure (usually in Utility Jumpboxes) in [Jenkins](http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/).

## Desired behavior
The build should be passing.

## Acceptance Criteria
- [ ] Error has been fixed.

**Comment by rmtolmach** [comment]
Good news: haven't seen this fail since I wrote up this bug.
Bad news: Failure is still a mystery.

**Comment by rmtolmach** [comment]
Update: failure still hasn't been reproduced.

**Comment by jbritt1** [comment]
Issue has not been observed again for several months, closing. Happy to reopen or make a new ticket around resolving if it returns.
