### ISSUE TITLE
Establish a Plan for Product Iteration (Phase 1)

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#3838]
## User Story
As a product engineer, I want to know how users naturally use my application without me there to guide them, so I can gain an accurate, unbiased view into what can be improved, changed, fixed, etc.

## Considerations
- Moderated user acceptance testing (UAT) as outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)
- Flipper UI could be an option to release View Rated Disabilities to a _percentage_ of production traffic incrementally. [More here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-flags/)
- Consider where this will divert from
- Should have the unauthenticated page created first

## Goal
_What outcome(s) do we want to see?_
- This should probably be a team-wide meeting, potentially with the analytics team & whoever else is heavily involved with launching a new product, to determine what our UAT plan should be. 
- The outcome of this ticket should be a solidified plan for conducting UAT. 
- The outcome of this ticket should be a ticket that executes the plan agreed upon for UAT.

## Acceptance Criteria
- [ ]  A plan for carrying out UAT has been agreed on and solidified. The plan should be actionable and should result in UAT that delivers some sort of measurable and usable data.
- [ ] Define and document the UAT plan in GH

**Comment by jason-gcio** [comment]
Initial doc is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/UAT/release-plan.md

**Comment by steve-gov** [comment]
As we discussed, I think there's some conflation here of UAT and product iteration, so I'm gonna nix this in favor of some further iteration issues.
