### ISSUE TITLE
Overall user experience - Design component or pattern in use isn't considered a best practice. (01.01)

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#38395]
#### Point of Contact/Reviewers (Practice area)
Jim Ryan, IA
*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Issue Details
**Launch blocking issue**
As the accessibility reviewers noted, lack of an x-out may pose problems for vision impaired users unfamiliar with the escape key function.
But in general, adding a simple, low-overhead affordance like the customary "x" makes it easier for a wide range of users with a wide range of cognitive styles and abilities to understand what the modal does and how they should interact with it. That's a good argument for keeping it in.

 

### Link, screenshot or steps to recreate

[Modal without x-out control](https://60f9b557105290003b387cd5-itttoqxdrx.chromatic.com/?path=/docs/components-va-modal--default#hide-close-button)
 

### VA.gov Experience Standard
Overall user experience | [Design component or pattern in use isn't considered a best practice](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html). | 01.01
 

### Other References
 

---

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket. 

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add the VFS team and product name
- Add your name and practice area under Point of Contact(Practice Area)
- Add the Platform Issue. The Issue column from the [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
- Add the Issue Details and any links, screenshots or steps to recreate
- Add the [VA.gov Experience Standard](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html) number
- Move to the Feedback pipeline on the Platform Product Support board
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by k80bowman** [comment]
@andresriveratoro this has already been resolved, correct?

**Comment by andresriveratoro** [comment]
@jimuhh @k80bowman This has been corrected at https://github.com/department-of-veterans-affairs/component-library/pull/298#issuecomment-1064440433. Thanks!
