### ISSUE TITLE
Suggested updates to "Setting up your local frontend environment"

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#38409]
### Description

- This applies to any/all pages, but noticed it here - Can we remove the `$` from the front of commands so copying them is easier via select line (triple-clicking on the line) or the **Copy** button on the UI? This character isn't part of the command and would have to be removed before running it, it just signifies that it is being run in a terminal.
- Under **Step 1: Set up Node** > **1.** > **install nvm, Mac** - Install `nvm` for Mac is missing a step to get `nvm` command working in the terminal.
    - We recommend Homebrew installation but nvm repo says _"Homebrew installation is not supported. If you have issues with homebrew-installed nvm, please brew uninstall it, and install it using the instructions below, before filing an issue."_ The instructions from nvm also include adding `nvm` to your terminal.
    - Questions
        - Why do we recommend installing via Homebrew if nvm doesn't?
        - If we want to continue recommending installing via Homebrew, should we include instructions or a link to add the `nvm` command to the terminal? Otherwise, the person following the instructions can't proceed because the `nvm` command will not work (at least it didn't for me, I had to do this https://stackoverflow.com/a/27652360).
- Under **Step 3: Start up the front end** > **2. & 3.** > **`yarn build`** - are these instructions redundant? 
    - Is this the same command and same folder for `yarn build` in `vets-website`? It does not specify to switch folders, so you would be running the exact same thing twice.
        - If it is not the same, maybe some more explanation or supporting links around this. Explanation of who needs the CSS and JS generated (or what you will miss out on without it).
- Under **content-build** > **3.** > **_"Build content-build. Make sure you configured the SOCKS proxy to fetch content from Drupal."_**
    - Include a note about how long this step will take and that running the cached version (step 4. below it) will be a much faster way.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html

**Comment by timwright12** [comment]
Going to pass this over to @rmessina1010 since he's leading that team now. Ray, I'm happy to advise, just let me know.

**Comment by lianilychee** [comment]
hey all -- I'm removing my team as assignees, and adding Lainey and Ray to refine in backlog as they see fit.

**Comment by timwright12** [comment]
Closing out, I went ahead and updated this documentation. It will go out with the next publish.
