### ISSUE TITLE
SRE VA.gov and API Status Page

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#38417]
## Product Outline

To enhance the customer experience and awareness of the current status of the system and other components.  The Lighthouse team uses https://valighthouse.statuspage.io/ and we plan to include this as an enhancement to the https://api.va.gov/v0/status to provide more info.

## High Level User Story/ies
As a user of va.gov  I need to know the status of various services. to help me know when things are not working and what is being done about it.

## Hypothesis or Bet
If we make this change then users will not have to open support requests for things they know are down , becuase we can provide the relevant info and  status info to answer their questions about various services.

## OKR
Customer Support and reliability services

### What must be true in order for you to consider this epic complete? 

The user will be able to goto https://api.va.gov/v1/status and get information on the status of services, builds and past incidents.

**Comment by powellkerry** [comment]
- With a revision number, we should be able to pull a list of the most recent commits from git history
- We also may be able to pull in recent incidents and alerts from pagerDuty and DataDog
- The challenge will be creating a design that will display all of this data in a readable format. These also may be part of a v2

**Comment by rsmithadhoc** [comment]
Compiling a list of questions and links here that I will update as I have more. I'm not expecting anyone to jump in and answer, these are things we can discuss as a team.

- Do we want a Statuspage.io (as well as the custom page) to track uptime, incidents, and performance stats? Example: https://www.intercomstatus.com/
    - https://support.atlassian.com/statuspage/docs/what-are-system-metrics/
    - https://support.atlassian.com/statuspage/docs/add-a-datadog-metric/
- For the custom status page, should it be a widget or application?
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/Adding-applications-and-features.1847591039.html
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/Creating-a-new-application.1847525496.html

**Comment by little-oddball** [comment]
Ideally want to close this as DUP but associated it w/ another EPIC #38743 as it has some good supporting / additional information to support.
