### ISSUE TITLE
Suggested updates for "Internal tools access via SOCKS proxy"

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#38410]
### Description

- _"You can configure connecting to GitHub via SSH instead if you prefer."_
    - While that is true and it links to GitHub's guide, the SOCKS setup overrides `~/.ssh/config`, so if you previously set up GitHub SSH, it will need to be re-added to this file. [GitHub - Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent). Instead of `Host *`, you can use `Host github.com` to limit it to GitHub connections.
        ```
        Host github.com
        AddKeysToAgent yes
        UseKeychain yes
        IdentityFile ~/.ssh/id_ed25519
        ```
    - Alternatively, the script that modifies `~/.ssh/config` could be changed to append to that file instead of overwriting it and not use `Host *` for its SSH key, so any previous SSH keys added for GitHub remain and still work.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

**Comment by gmaciolek** [comment]
Thanks, @rsmithadhoc -- I'll work on tracking down the right subject matter expert to address your suggestion. 

Coincidentally, there's another ticket related to this doc and it sounds like @rmtolmach will be making changes to it soon. Rebecca, does Ryan's suggestion overlap at all with the changes you'll be making?

**Comment by rsmithadhoc** [comment]
> Thanks, @rsmithadhoc -- I'll work on tracking down the right subject matter expert to address your suggestion.
> 
> Coincidentally, there's another ticket related to this doc and it sounds like @rmtolmach will be making changes to it soon. Rebecca, does Ryan's suggestion overlap at all with the changes you'll be making?

Hi @gmaciolek, it looks like Rebecca's updates may not have any overlap. I'm happy to help with a separate update once a subject matter expert can take a look, thanks!

**Comment by rmtolmach** [comment]
oh hey! Just seeing this. My bad. 

There is an open issue for this in the `vtk` repo, where the override happens. @ericboehs is the `vtk` SME. Comment with your thoughts on the issue https://github.com/department-of-veterans-affairs/vtk/issues/23

**Comment by rmtolmach** [comment]
@rsmithadhoc Can we close this as a duplicate of the issue we commented on in the vtk repo?

**Comment by rsmithadhoc** [comment]
> @rsmithadhoc Can we close this as a duplicate of the issue we commented on in the vtk repo?

@rmtolmach Yeah, I will go ahead and close it, thanks.
