### ISSUE TITLE
[FE] Migration to Cerner to Health System Vs Facility Name

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38428]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)

[Link to Tech Discovery Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37594) 

##### Context: Original Ask
`Email Ask`: Yesterday, someone brought to my attention: On our health tools pages on va.gov (Rx Refill, Secure message, etc.) when we are pointing Veterans to the Cerner portal, we have been using the formal name of the parent facility, versus the name of the health system (VA Spokane health care). When sites move to the new cerner EHR, the entire health care system goes live with it – inclusive of all of the CBOCs and related clinics.
 
With Walla Walla’s ship date around the corner (3/26) I’m wondering if we should be using the health system name instead of the facility name, and if so, how big of a lift is that for the sitewide team? I don’t think a change is needed on the facilities pages, based on my discussions with Sam before he left.
 
So, in the image below, instead of “For Mann-Grandstaff” we would use For “VA Spokane health care”

<img width="545" alt="Screen Shot 2022-02-24 at 10 42 01 AM" src="https://user-images.githubusercontent.com/70410912/155578265-e8719f5d-b556-4d36-9d68-04b23b340818.png">

### Possible Solution (based on tech discovery)
- Content revises the array to provide the actual names of the locations they want to display.
We create a JSON file that serves as a look-up for the facility names. Maybe each individual center is in an array with the parent key being the system they want to display. If we find the facility in the array we return the parent system back as a string to the widget. Obviously we would need to construct this file based on data that would be provided to us. 
- **Note:** That could be very time-consuming and, potentially, that file could be VERY large and maybe this is a bit taxing, but its an
- Recommendation: Feasible, would need to be completed post contract award on 4/7/2022. 

### Tasks
TBD

### Acceptable Criteria 
TBD

**Comment by ryguyk** [comment]
Closing. This work was completed [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9074)
