### ISSUE TITLE
Research BI Tools

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#3842]
## User Story or Problem Statement
How might we leverage a business intelligence tool in our development of the product success tool? 

## Goal
Determine the best solution to move forward with. 

## Acceptance Criteria
- Determine viable options for product success tool BI solution
- Determine pros vs cons of each tool
- Populate BI/Visualization Solutions tab [here](https://docs.google.com/spreadsheets/d/1tYzIGe3bWug8Ryy0MuaJ3ubNhPrYxSIxW_hGXEw0FYI/edit#gid=0)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Duplicated issue from https://github.com/department-of-veterans-affairs/va.gov-team/issues/406. Closing this issue.
