### ISSUE TITLE
Onboarding New Team:  2 Designers and PM

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38436]
## Issue Description
_Three new people have joined the team and we need to get them up to speed_

---
## Dan Tasks
- [x] Read through [SD space in confluence](https://vfs.atlassian.net/wiki/spaces/SDT/overview)
- [x] (Designers) Read through [Design and research community of practice space](https://vfs.atlassian.net/wiki/spaces/DCP/overview)
- [x] (All) Read through [About the Platform Space](https://vfs.atlassian.net/wiki/spaces/AP/overview?homepageId=1375240354)
- [x] Join a VSP orientation session 

## Nicole Tasks
- [x] Read through [SD space in confluence](https://vfs.atlassian.net/wiki/spaces/SDT/overview)
- [x] (Designers) Read through [Design and research community of practice space](https://vfs.atlassian.net/wiki/spaces/DCP/overview)
- [x] (All) Read through [About the Platform Space](https://vfs.atlassian.net/wiki/spaces/AP/overview?homepageId=1375240354)
- [x] Join a VSP orientation session 

## Bryan Tasks
- [x] Read through [SD space in confluence](https://vfs.atlassian.net/wiki/spaces/SDT/overview)
- [x] (Bryan) Read through [Product community of practice space](https://vfs.atlassian.net/wiki/spaces/PMCP/overview) 
- [x] (All) Read through [About the Platform Space](https://vfs.atlassian.net/wiki/spaces/AP/overview?homepageId=1375240354)
- [x] Join a VSP orientation session

**Comment by shiragoodman** [comment]
hey @steel36  - all of our Platform Orientation sessions are shared internally on Confluence via the[ Platform Orientation/Orientation Sessions page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions). This is how Platform folks can sign up for the orientation sessions. Let me know if you have any questions.

**Comment by steel36** [comment]
Hey @gopixelsgo I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
