### ISSUE TITLE
[Administrative] Update "DevOps Contacts" in devops repo 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#38432]
## Description
There are outdated points of contact on the readme in the devops repo. They should be updated for accuracy. 

## Background/context 
["DevOps Contacts" in devops repo](https://github.com/department-of-veterans-affairs/devops#devops-contacts)

---
## Tasks
- [x] Update the document with correct contacts 

## Acceptance Criteria 
- [x] The information for DevOps points of contact are accurate on the page listed above.

**Comment by oseasmoran73** [comment]
PR is ready to go. Feel free to change it to `ready` once Kyle is ready for this transition

**Comment by jbritt1** [comment]
Updated contact for Appeals team: https://github.com/department-of-veterans-affairs/devops/pull/11120

**Comment by oseasmoran73** [comment]
PR has been merged with Kyle's contact information. Closing this ticket
