### ISSUE TITLE
Research, Establish, and Launch Service Design Guidelines for the Platform

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38442]
## High Level User Stories
As a Platform team member, I want to know what SD standards to employ to help ensure VFS teams can find and have a good user experience with my product/service.

As OCTODE/Platform Leadership, I want teams to use approved SD standards to ensure that platform services are being planned and thought about holistically. 

## Hypothesis or Bet
If we provide clear and concise Service Design guidelines, Platform teams will be able to build products and services that will better serve VFS teams.

## Definition of Done
- [x] Service Design Guidelines are established and documented.
- [x] Service Design Guidelines are easily accessed in suitable space.

**Comment by chrisj-usds** [comment]
@raywangoctova @steel36 
are these guidelines in a publicly available document somewhere?

**Comment by steel36** [comment]
@chrisj-usds
