### ISSUE TITLE
Evaluate improvement paths for providing Customer Insights

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38446]
## Problem Statement
The Platform Satisfaction Survey has been conducted quarterly for several years.  It has returned insights that Platform teams are able to review and prioritize for planning each quarter.

However, participation has always remained very low, (<15% typically), and we would like to increase it to garner better representation of VFS team members.  In addition, we would like to enhance the insights provided by gathering a wider variety of feedback.

We intend to research potential causes for low participation, as well as avenues for improving the feedback that is submitted.

Operative question:  How might we increase participation and also gather insights that are more actionable by Platform teams and Octo leadership?

## High Level User Stories
As Platform leadership, I want to see actionable insights so that I can prioritize projects that are valuable to VFS teams.

As a Platform team member, I want to have access to specific, actionable insights so that I can prioritize pursuits that are valuable to VFS teams.

## Bet
By researching the why(s) behind low participation and pursuing potential improvements, we can gather insights that are more actionable and plentiful.

## Definition of Done
- [ ] Decisions will be made on direction for improvements 
- [ ] Decisions and processes will be documented

### KRs / HMs
Increase in survey participation

Decrease in survey abandonment rate

Increase in actionable feedback

### Documentation

- PRODUCT_NAME: directory name used for your product documentation

- Product Outline: link to Product Outline

- User Guide: link to User Guide

### Measurement
Success metrics: link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping

Release plan: link to Release Plan ticket

## Issue thoughts and discussion
How to improve response rate & utility?
How to get more useful responses?
How to get more responses?

Is the survey too frequent?  Should we reduce the survey to 2 times a year (such as 1st and 3rd quarters)

How to make it easier to access?

7/28/22 Convo w/ Ray:  How to make the results more actionable?  How to confirm that teams are acting on feedback?
1) Compare qtr over qtr?
2) Have Product Lead review and meet w/ teams to prioritize or assign where appropriate?
What is the follow-thru mechanism?

How to begin tracking results between quarters and displaying them in a meaningful way?

Idea:  post insights locally around the user space within the Overview Map associated with a feedback item

9/1 Sync w/ Naomi:  Predefine Corrals for questions to help minimize wide-openness of questions.  Could be by tools.  Could have blanks for further exposition.

Maybe even conditional questions?

**Comment by annekerr49** [comment]
@steel36 Please update this requested item

**Comment by annekerr49** [comment]
@steel36 - Mike Chelen is requesting that these product boards be updated every month. If there is no change to the plan just make that note.

**Comment by annekerr49** [comment]
@steel36: Bryan we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues. Please let me know if you have any questions.

**Comment by steel36** [comment]
This is an Initiative for the quarter.  It is scheduled to be addressed around mid-qtr.

**Comment by steel36** [comment]
You're welcome.  It has not begun yet.
