### ISSUE TITLE
Offboarding of [emily-mann]

### ISSUE THREAD

**Issue by eunicegar** [department-of-veterans-affairs/va.gov-team#38440]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Emily Mann
- team name:
  > [all-va](https://github.com/orgs/department-of-veterans-affairs/teams/all-va)
  >[depo](https://github.com/orgs/department-of-veterans-affairs/teams/depo)
- role on team:
  > Product
- expected last day:
  > 3/11/22
- company they work for:
  > Department of Veteran Affairs  
- email:
  > emiliy.mann@va.gov
- GitHub username:
  > emily-mann
- additional access they may have:
  > ex: SOCKS, Pagerduty, Google analytics, etc.
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*

 - [x] Remove from Confluence (if applicable) 
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights , @department-of-veterans-affairs/confluence-admins

**Comment by eunicegar** [comment]
Please do not remove from Slack.

**Comment by jbritt1** [comment]
> Please do not remove from Slack.

Until when?

**Comment by jbritt1** [comment]
Not found in VFS team roster
No SOCKS
No AWS
No PagerDuty
YubiKeys not applicable
No Datadog
No Sentry

**Comment by jbritt1** [comment]
Not found as a current user in Confluence

**Comment by bsmartin-ep** [comment]
GA and Domo access removed.

**Comment by eunicegar** [comment]
Slack access has been removed,
