### ISSUE TITLE
[Design] Create List of Epics Topics from Accessibility Research

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#38453]
# Description
Nira and Ya-ching completed an accessibility audit of check-in and pre-check-in. They have identified numerous items that need to be turned into Epics for future work. This work needs to be summarized in a way that it can be handed off to product, so it can later be prioritized.

Outcome from this ticket: A list of all the future Epic topics with a summary, so product can understand what problem needs to be solved.

# Tasks
- [x] Create document to handoff to product

# Acceptance Criteria
- [x] Handoff documentation to product

**Comment by niradatta1** [comment]
The deliverable will build on the first iteration of high-impact epics we put together in the accessibility roadmap (and handed off to Product) : https://app.mural.co/t/vfscie8528/m/vfscie8528/1646755501997/334928d21a9f53faa98e2c3225500aaafec23dad?sender=niradatta0802  'cc @ytsaoca
