### ISSUE TITLE
AWS Staging: Discrepancy with Requested queue sorting order for requests submitted on the same day

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#38467]
## What happened?
SQA team has noticed a discrepancy with sorting order in VAOS for requested queue. This issue is seen only with requests submitted on the same day. The sort order is performed differently for VAOS service user (it is based on type of care - alphabetical order) and for VAR Resource user (it is based on created time)

## Steps to Reproduce
**Scenario 1:** 
1. Login to VAOS as Ruben Moreno (VAR Recourses test user) 
2. Follow steps to schedule 2 VA requests for different types of care (ex:- Amputation care and then Pharmacy)
3. Validated on the “Requested” tab the sorting order is based on the requests created time

![VAR Res](https://user-images.githubusercontent.com/69315717/157983149-94cfb952-7156-4750-802c-903ef8e25a40.PNG)

**Scenario 2:** 
1. Login to VAOS as Grethel Petryniec (VAOS Service test user)
2. Follow steps to schedule 2 VA requests for different type of care (ex:- Food and Nutrition and Routine hearing exam)
3. Validated on the “Requested” tab the sorting order is based on type of care (Alphabetical order)

![VAOS service](https://user-images.githubusercontent.com/69315717/157983207-54285a5f-05d0-47ba-961f-6718d22e6b6a.PNG)

## Desired behavior
VAOS service test user should also sort requests made on the same day by request created time.

**Comment by aarathi-poldass** [comment]
@ldelacosta @grossb1 - Please let me know if you have any questions or concerns

**Comment by ptouchton** [comment]
In researching this issue. I discovered that the front end does not sort these responses. It comes from the backend sorted in the var scenario.

**Comment by ajmagdub** [comment]
VAOSR-3178 declined to be worked on, work will be picked up by Vets API team.

**Comment by ldelacosta** [comment]
@beth-wodzinski , This can be re-tested. Thanks!

**Comment by beth-wodzinski** [comment]
I checked with both Ruben and Grethel, and for both, the most recent request is at the top of the list. 

@ldelacosta this passes testing.
