### ISSUE TITLE
Access for Travis McKinstry

### ISSUE THREAD

**Issue by TravisGM** [department-of-veterans-affairs/va.gov-team#38464]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Travis McKinstry

### Your Email

travis.mckinstry@thoughtworks.com

### Name of Your Team

Digital Health Platform (DHP) Team, Developer, ThoughtWorks

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCwDGsUwhycDOs50GLzgCvXRdRiqlDt44k7/LPuwqXATKBqiDkc8vhb5DpQWOujIPCFBfWeuQwBBoG4D3zfb1Uemg4MSODD5wayTHYDnk2knAX3bXM6MIBmFz2q4JjX22j4beb10vMfv0WE/7M78Gd6cYqkV3E8VESGz3+AYTlpRKnPI97BbKiYebZazPLEQKnefNB3YTImGB2XywSg/sXqQfZ2/66yEeqjeSkqCGMkvhdCYtzTvrcP0fIRH6MX0dBwrjA48HHaaNY/mB4ERqDQHwzAJCzCcArEk7AoJFSqrqqiodfTjHw2DWVo3AIaWP0OBrGjdOQ5/uh/iFHdvy1iaRhDMSBstTwo8TZFFeqIvHENud8+2q07GC9aOldMb7qUnVa3rCsMJFE/yYbpCSPzlU/PgcruEtw9OGBqYDyKUKt8LzkoRVo8b0FMBjMxcrghA5FeFHhWuVwPJgjljE46JmDIi5wjkaRYI2MQeT0GQcpTvhAvjwTsGAgxwb955c= travismckinstry@Traviss-MacBook-Pro.local

### Desired AWS Access

For now I just need an AWS account and access to logs/metrics/jenkins via SOCKS

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
SOCKS and AWS are separate things. We are going to set you up with SOCKS now and if you decide to also request AWS we can reopen the ticket.

**Comment by jbritt1** [comment]
### For AWS Access

User: Travis McKinstry
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
requested AWS approved

**Comment by jbritt1** [comment]
First-time login credentials and instructions passed to user via Slack at this time.
