### ISSUE TITLE
Content Request from Authenticated Experience - Profile Team for Bad Address Indicator Email and Alerts

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#38468]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [X] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
We are preparing an email template to send out through VA Notify to alert Veterans that their email address has been flagged as invalid and needs reviewing. We are also adding in-line alerts on the Personal information page and Contact information page. 

This request is to review the email draft and alert content.

------ 

### Email Draft:

Dear ((First Name)) ((Last Name)), 

The mailing address that the U.S. Department of Veterans Affairs currently has on file for contacting you about some of your VA benefits may no longer be valid because mail addressed to you was returned, or could not be delivered for some other reason. 

The address we have for you:

((First Name)) ((Last Name))
((Address 1))
((Address 2))
((City)), ((State)) ((Postal Code))

This address is used for the following VA benefits and services:

- VA health care (including prescriptions, appointment reminders, lab and test results, and communications from your VA medical center)
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)

If the address listed is correct, please confirm by visiting some URL for confirming an incorrectly flagged address. 

If you need to update your address, log into your VA.gov profile at http://va.gov/profile/contact-information.

If you have questions about how changing your address updates your information, please visit https://www.va.gov/change-address/. 

------ 

### Profile Alert - Personal information:

**Heading:** 
Please update your mailing address

**Body:** 
We believe the mailing address we have on file for you may no longer be valid. 

**Link to Contact information Mailing address:**
Review and edit your address

<img width="673" alt="Screen Shot 2022-03-15 at 9 39 48 AM" src="https://user-images.githubusercontent.com/79372956/158428023-baea012a-2f1e-45e8-a62a-fda72cd1d5c7.png">

------  

### Profile Alert - Contact information: 

**Heading:** 
Please update your mailing address

**Body:** 
We believe the address we have on file for you may no longer be valid. 
Review and edit your mailing address below.
If the address listed is correct, confirm it here.

**Button:**
Confirm my address

<img width="633" alt="Screen Shot 2022-03-15 at 9 40 03 AM" src="https://user-images.githubusercontent.com/79372956/158427968-55df24ed-b7d3-486e-8499-7d9e1b51f080.png">

---------

### Confirmation Modal

**Heading:**
Confirm your mailing address

**Body:**
Confirm that you want us to use this mailing address. Or, cancel to go back and edit it.

**Button:**
Use this address

<img width="771" alt="Screen Shot 2022-03-15 at 2 09 38 PM" src="https://user-images.githubusercontent.com/79372956/158473173-fde6878d-a4fe-4b89-9d31-3ea63446bcd2.png">

 ------ 

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/bad-address-indicator
- Link to or attach user flows: N/A
- Link to prototype or mockups: 
   - Desktop: https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/3OMD28m
   - Mobile: https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/WK0EMb0
- Link to any epics/issues that may be helpful: N/A
- Discovery doc by Marci: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/discovery/va-notify-discovery.md

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD
- Estimated staging review date: TBD
- Content and IA work needed by: Mid-March

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Authenticated Experience - Profile Team
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Marci McGuire
-	Designer: Christina Gednalske
-	FE engineer: Adam Whitlock
-	Product/team Slack channel: #vsa-authd-exp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by cgednalske** [comment]
Hi @SgardnerPMP and @DanielleThierryUSDSVA! Noting that our designs have changed slightly - altering a few things in the Personal Information Alert text and adding new text for a Confirmation Modal. All updates are included above.
Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @cgednalske! Going to post content recommendations here as I get to them.

First up - email! 

**Notes:**

- I think the first paragraph is saying that the postal service returned or couldn't deliver mail VA recently tried to send to the Veteran at this address, correct? I want to make sure I didn't change the meaning there. 
- I think we can use headers to make this easier to read/digest.
- What do you think about moving the info about how we use the address down below the directions on confirming/changing the address? The reason I suggest this is that by doing that, we bring the address we're showing them and the "what to do" closer together so they don't have to scroll as much to check the address and then take action.
- Consider sending folks to the resources and support article on changing your address across different benefits and services to provide that broader info in case they need it.

Let me know your thoughts and questions on this and I'll keep looking at the other pieces. Thanks!

# Confirm your address on file with VA

Dear ((First Name)) ((Last Name)),

We recently sent you mail that the U.S. Postal Service couldn't deliver to the address we have on file for you. We want to make sure you receive all information about your VA benefits and services. So we need your help to confirm or change your address.

## Your current address on file at VA

Here's the address we have on file for you:
((First Name)) ((Last Name))
((Address 1))
((Address 2))
((City)), ((State)) ((Postal Code))

## What you need to do now

**If this is your correct address,** go to this link: _(insert url)_. Then choose **Confirm my address**.

**If you need to change your address,** sign in to your VA.gov profile at: http://va.gov/profile/contact-information. Then choose **Edit** to change your address.

## How we use the address in your VA.gov profile

We use this address to send you information about these VA benefits and services:
- VA health care (including prescriptions, appointment reminders, lab and test results, and communications from your VA medical center)
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)

Do you need to change your address for other VA benefits and services too? Find out how to change your address for different benefits and services here: https://www.va.gov/resources/change-your-address-on-file-with-va/.

**Comment by cgednalske** [comment]
Hi @DanielleThierryUSDSVA - thank you for this great feedback! The way you've laid out the info looks wonderful - super easy to process! 

Looping in @MarciMcGuireGCIO as well. She worked on the draft so I want to make sure I'm not missing anything with the initial context/intentions, but I don't see anything that wouldn't work as you've formatted it. 

Marci, the one thing I'm wondering about is the "What you need to do now" section. Is the first sentence for Confirm my address still somewhat of a placeholder? Will they need to go to VA.gov regardless or do we think there is a separate, direct way to confirm? This question goes beyond this content review, but it might alter that section a bit.

**Comment by Samara-Strauss** [comment]
We've discussed this on Slack, but we can not send addresses over email, so we will need to remove that entire section of the email. 

> We recently sent you mail that the U.S. Postal Service couldn't deliver to the address we have on file for you. We want to make sure you receive all information about your VA benefits and services. So we need your help to confirm or change your address.

I think we could be more direct and get to the point quicker. How about:

> We recently sent you mail that the U.S. Postal Service couldn't deliver and returned to the VA. Please log in to VA.gov to update your address information, or confirm that your current address is correct.

Since we can not show someone's address over email, this would be followed by the "What you need to do now" and "How we use the address in your VA.gov profile" sections.

Otherwise, I think Danielle's email draft looks great.

**Comment by Samara-Strauss** [comment]
Actually, one more thing:

> If this is your correct address, go to this link: (insert url). Then choose Confirm my address.
> 
> If you need to change your address, sign in to your VA.gov profile at: http://va.gov/profile/contact-information. Then choose Edit to change your address.

People will be confirming their addresses or changing their addresses at the same page, so I think we consolidate this a bit more to something like:

> To change your address, sign in to your VA.gov profile at: http://va.gov/profile/contact-information. Then choose Edit to change your address.
> 
> If your address is correct, you can also confirm it from your profile

I also put the copy to change you address first since that will be the primary action for most people (much more unlikely that the address is actually correct in the first place).

**Comment by cgednalske** [comment]
Thanks, @Samara-Strauss! So with those changes, the newest draft would be the following. I'll link here from our related sprint ticket as well, so it's recorded there too.

# Confirm your address on file with VA
Dear ((First Name)) ((Last Name)),

We recently sent you mail that the U.S. Postal Service couldn't deliver and returned to the VA. Please log in to VA.gov to update your address information, or confirm that your current address is correct.

## What you need to do now
To change your address, sign in to your VA.gov profile at: http://va.gov/profile/contact-information. Then choose Edit to change your address.

If your address is correct, you can also confirm it from your profile.

## How we use the address in your VA.gov profile
We use this address to send you information about these VA benefits and services:

- VA health care (including prescriptions, appointment reminders, lab and test results, and communications from your VA medical center)
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)

Do you need to change your address for other VA benefits and services too? Find out how to change your address for different benefits and services here: https://www.va.gov/resources/change-your-address-on-file-with-va/.

**Comment by MarciMcGuireGCIO** [comment]
Looks great @cgednalske !

**Comment by Samara-Strauss** [comment]
Looks great! I'd still like @DanielleThierryUSDSVA to sign off on the copy updates, as I am not familiar with the content guidelines and may have unintentionally written something that doesn't match our current content standards. But if Danielle signs off on it, it looks good to go to me!

**Comment by MarciMcGuireGCIO** [comment]
@DanielleThierryUSDSVA if you have time, can you please review the updated email draft Christina posted above and let us know if we need to make changes?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@DanielleThierryUSDSVA @cgednalske - Linking to the feedback from the Design Intent review held yesterday.

- [Design Intent Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38727) 

- [Design Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38886)
- [Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38905)
- [Content & IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38922)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MarciMcGuireGCIO. Just made some tweaks. Here you go - thanks! 

# Confirm your address on file with VA
Dear ((First Name)) ((Last Name)),

We recently sent you mail that the U.S. Postal Service couldn't deliver and returned to us. Please sign in to your VA.gov profile to change or confirm your address on file with VA. 

## What you need to do now
Sign in to your VA.gov profile at: http://va.gov/profile/contact-information. Then review the address listed in your profile.

To change your address, choose **Edit**. If your address is correct, choose **Confirm.**

## How we use the address in your VA.gov profile
We use this address to send you information about these VA benefits and services:

- VA health care (including prescriptions, appointment reminders, lab and test results, and communications from your VA medical center)
- Disability compensation
- Pension benefits
- Claims and appeals
- Veteran Readiness and Employment (VR&E)

Do you need to change your address for other VA benefits and services too? Find out how to change your address for different benefits and services here: https://www.va.gov/resources/change-your-address-on-file-with-va/.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - are you good with this language?  LMK if we need to adjust.  I'd like to get this to Privacy & Security so they can sign off.  Thanks!  cc @SKasimow

**Comment by Samara-Strauss** [comment]
This is great! Just want to know the profile design is changing slightly (design work still in progress), so this line will likely need to be updated:

> To change your address, choose Edit. If your address is correct, choose Confirm.

I'm pretty sure we are removing the "Confirm" button that was in the original designs since it caused a lot of confusion in the design intent.

That being said, @MarciMcGuireGCIO -- you can probably still review with privacy and security unless they need 100% finalized and perfect copy. This should be good, though, since no PII is going out in the email.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - ah, yep; good catch.  I'll mention that in the request.  Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Okay, awesome! @Samara-Strauss If you all do remove that Confirm button, here's a line that could potentially work:

> To change your address, choose **Edit**. If your address is correct, you don't need to do anything.

**Comment by Samara-Strauss** [comment]
Thanks @DanielleThierryUSDSVA! People whose addresses are correct likely WILL need to do something, so we should hold off on tweaking that last line until Christina has a chance to make her final design updates.

**Comment by DanielleThierryUSDSVA** [comment]
Ha! Got it, @Samara-Strauss - thank you! Look at me getting ahead of myself :)

**Comment by SKasimow** [comment]
@cgednalske - can we close this?
