### ISSUE TITLE
Analytics Reporting Request for Charles W.

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#3846]
# Metrics Reporting Request
As DSVA leadership, I want to understand the flow of users between Modernized content to key events on MHV.

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for? 
Charles W. 

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._

## Analytics to Track Down
- [ ] Segment of users who start on Modernized content and then complete a MHV transaction.

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] Analytics-Insights team QAs the approach.
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
12/2 Progress - Building segments for key transactions to track users that start on Modernized content and then complete a MHV event.

**Comment by nedierecel** [comment]
@jonwehausen Can you help me QA this segment I built? The goal is to obtain the total **users** who started on Modernized content (e.g. homepage or hubs) then proceeded to complete a `rx-refill` event.

https://analytics.google.com/analytics/web/template?uid=5FEO7aSmSDKOT-sNprIctQ

Please copy and paste this segment to your personal assets, then use the "All Production Website" view to see total users.

If this logic in my segment sequence looks right, I'll then build the other necessary segments.

**Comment by jonwehausen** [comment]
Hi @nedierecel, 

Just checked - this looks great to me 👍

**Comment by nedierecel** [comment]
@jonwehausen For a final gut check, can you please:

- [ ] Review the segments below updated from users to sessions 
- [ ] Review the unsampled report link

## Segments Created
1. [Modernized to View or Fill RX](https://analytics.google.com/analytics/web/template?uid=C4ozIgXiShig6g6i-ms8CQ)
2. [Modernized to View Appointments](https://analytics.google.com/analytics/web/template?uid=QGrkrg7IQRmoQt1VIdK6Sw)
3. [Modernized to View or Send Secure Messages](https://analytics.google.com/analytics/web/template?uid=z6TlFvAFTHyZ7WtoYy1NBg)
4. [Modernized to Health Record Download](https://analytics.google.com/analytics/web/template?uid=Isj3rlwoSvCEJyPJzl89NA)

## Custom Report
I applied these segments to an overview report and downloaded the Unsampled Report here. I attempted with the GA Sheets Plugin but was highly sampled (only 6% reporting using the All VA.gov Production View).

[You can find that report here](https://analytics.google.com/analytics/web/#/opusreport/SilVvaiFQKiujgppl7pS_w/a50123418w177519031p176188361/_u.date00=20191101&_u.date01=20191130&_u.date10=&_u.date11=&_u.dateOption=&_r.dsa=1&overview-graphOptions.primaryConcept=analytics.visits&_.useg=userQVVmqPb0RKuXIYLW4Mq9jg,usermwiubkxcRnK1w5tJJPVVyg,userPXTxk-H9SYenRoJ7wlBfeg,userG2effqrMTr6DGYxhNsKfrw/).

**Comment by jonwehausen** [comment]
Segments and report look good @nedierecel 👍 .

Confirmed these are looking at sessions and report is based on 100% of sessions.

**Comment by nedierecel** [comment]
This was provided today to Charles via email. I will upload the final Excel file via LFS.
