### ISSUE TITLE
Access for [Rebecca Green]

### ISSUE THREAD

**Issue by reblg** [department-of-veterans-affairs/va.gov-team#38492]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Rebecca Green

### Your Email

rebecca.green@thoughtworks.com

### Name of Your Team

Digital Health Platform (DHP) Team, Developer, Thoughtworks

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHAb5TlGMYjycJxmfUYRQ8FYI/yokJF2ryyqvQN2zK8bp0secr8kV0iu6rDOzD7Y/gAjilZRTVC3piYUnb3uxK6/lA2xXzL2GWMiJkdCS3xXhwjM84vtJu1HkSvRu45MTu+nzhEfQcfkcA83kKEkr1TDWNxvIlGIaFddsrR9dDXaW33AWguoDtaNrmkyeG1OM3lZTn9d1xOsTDR22cG2rhoh7cKzuT2Vof5GIWDwqrpP6HAiiY49xQ2G2az8P1jsoQLVjDVBLpFOtFZVEjq6L5eUFqJcDCn4S5uz0kJQgJTAWvBFx00k8bVNyhKLnDGyN4fyQBRL12V2UAVJHOQM8dpuHquA/Uj/U6cRY5UgPS0AZ7t7/rJIXzzjLFSHue3BTd2gpN5VHmp8Q9MfLGMqA+DcnSgQsjdM3LISMI56cMy9gwswaCUg3NPz1Iw3zz66B1O1WvOHK3y6v7737JzBZUpYrb/cbVI8Pltq1JlrFawuJfldW/O8VG4b//SeyZd7s= rebeccagreen@Rebeccas-MBP-2

### Desired AWS Access

For now I just need an AWS account and access to logs/metrics/jenkins via SOCKS

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
### For AWS Access:

User: Rebecca Green 
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by jbritt1** [comment]
First-time login credentials and instructions passed to user via Slack at this time.
