### ISSUE TITLE
Access for [Jonathan Epstein]

### ISSUE THREAD

**Issue by jonathan-epstein13** [department-of-veterans-affairs/va.gov-team#38498]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Jonathan Epstein

### Your Email

jonathan.epstein@oddball.io

### Name of Your Team

VSP Analytics

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKCyKKwgFfyruSKPQ0Wi/0U9w3d376FtU2iVEobWd6W1/0b1h+bQR6vld1W1fEdRdSIm3i9JDVGg1Bfc5deS7efB+ZneRJHaMW8ElkxA50iZKvO+QdhdFGqbYjzpm8oOet10XFUVo9aKxaxVnnD7ButoFzpygQcnJKakc8gxTVEC2nbECJvVvG8Xxt5+b7UVS7fQ2etYBGEtnXcgxb33e8k4dfgihZLAmuc3nO42rhbP2l/2mw3bXyF4iSicfiTmH5shCBGXIDtvSqMoI6VwwVi0dFOkvYdmf17x0FdRuBqif/TSzC6v4UIOHZsCG7INwRiSR6pJ/2JWyYocDblwJhimrI74VyfJyKq+8ysqU4DSiSn/uYfvHx7iDWEqsociaQH1I8j5lbN+dhQBb0FjnsTSWvYBGrOm9RukcF6m+PgtlT31ozDtroftdWhKIxs+TbfdojJO7LNTPd4w0Yo7C1Gx8UYGuYmQafewH3/kUFRiCa0/lS2wbEFr9WRR24h2E= jonathanepstein@JONISAAC-LAPTOP

Other: _/home/jonathanepstein/.ssh/id_rsa_vagov.pub_

### Desired AWS Access

No response

### Access Expiration

No response

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via #vfs-platform-support if you have any trouble.
