### ISSUE TITLE
Access for Matthew Ng

### ISSUE THREAD

**Issue by Matth-Ng** [department-of-veterans-affairs/va.gov-team#38502]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Matthew Ng

### Your Email

matt.ng@adhocteam.us

### Name of Your Team

PTEMS - Console UI - Senior Software Engineer - Ad Hoc LLC

### Service(s) You Want Access To

AWS

### Desired AWS Access

I need access to the System manager parameter store on AWS to view the parameters used for my project

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
@Matth-Ng : you should have access to add parameters to the path `/dsva-vagov/platform-console-ui/`. Is there any other path you need?

**Comment by Matth-Ng** [comment]
That is all I need. When I try to reach that I get the following error message "Matthew.Ng is not authorized to perform: ssm:DescribeParameters on resource" or hitting a 404. Am I missing something?

**Comment by jsgarmon** [comment]
You have `ssm:Describe*` permissions on all resources. Can you trying logging out and back in?

**Comment by Matth-Ng** [comment]
I have logged in and out twice but still get the same issues

**Comment by jsgarmon** [comment]
Looks like you haven't set up your MFA device, which is required to do most things within our AWS account

See [this documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781475/Set+up+your+AWS+Account) for help.

**Comment by Matth-Ng** [comment]
That was the problem. Thank you @jsgarmon. This issue is completed
