### ISSUE TITLE
Access for Brandyn Sullins [OptionSelect]

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#38516]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Brandyn Sullins

### Your Email

brandyn.sullins@govcio.com

### Name of Your Team

Debt Resolution

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9y12kR1bLul7ijxSe67ZfiHSOd9AWcpyfhtZzNKWthkXpbrMnRMp1kP5r/547EIPEVGLz4Nuwaj3OzeOQuKVqv8AupYp0C2COiRzcOJNCBlAxnS6v4OtdHrJQNquaIojQIgD2/z2uG81DdlYUHtEw3dtvqeY5acZftJ2w0GOHxqA8e0D5gPrTtfS+yStndxDhRXjx37hrCquN0oOyeA0mFky4DaQroolYJRtX3y2IVwITz8uQg2pyWq8M7OqB3sjKuoL5itLe+CKP1uPPikUPQ7Nm9pbsw1r7RDNjgoWyGHAa+nO5JZ/Y0FBUtv2vgXYhb/47kYrFpzNPoLh4M4RJ3ICDSnoPtGdLjwlAl4QAHfISpnjDmxCkic23qj/BdejPpqwsYc9HJPG9T6RyD12E3gRMpe9r/SQHfrDNJUVzhfrRrW9KTRD71lMK94flQEjj9IveRTKLmF8uw3ksc9mTgOERKV0K8qcuAvB1P1ylXHtMtpAFZ8NFd1TAOrVqWaE= brandyn@DESKTOP-BRG13CE

### Desired AWS Access

N/A

### Access Expiration

ongoing

**Comment by OptionSelect** [comment]
Of note, this is for a new machine. Old one needed to be replaced due to various issues.

**Comment by jsgarmon** [comment]
Key updated. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
