### ISSUE TITLE
Operating status enhancements 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38511]
## Issue Description
This issue will contain updates and improvements to consider related to operating status for Facility Locator, VAMC and Vet Centers

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19636 now tracks the child issues that weren't completed in this epic.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13598 was the Q4 2024 iteration on operating statuses.
