### ISSUE TITLE
Access for Kyle Matheny

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#38513]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Kyle A. Matheny

### Your Email

kyle.matheny@oddball.io

### Name of Your Team

Operations

### Service(s) You Want Access To

AWS

### Desired AWS Access

I require full admin access to all AWS accounts owned by the operations team.

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
**For AWS Access**
User: Kyle Matheny
COR: Vilay Senthep
VOR: Oddball - Amber Malcolm
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: yes

Kyle is joining the Infrastructure team as team lead, and will have the same permissions as the other engineers on that team (full admin).

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Checked with VOR again; awaiting information

**Comment by td-usds** [comment]
Approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user and confirmed successful login at this time.
