### ISSUE TITLE
evaluate moving GIDS to fwdproxy or send traffic directly to it from revproxy

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3852]
## User Story or Problem Statement
During a recent GIDS issue, it was discovered that GIDS still has requests flowing directly to it instead of through the forward proxy like all of the other backends added after the fwdproxy was created. This design leaves us with a bit less visibility on this backend and would be useful to make it uniform. We also discussed briefly whether vets-api was adding value by being in the middle since this was an API that is also controlled by VFS teams. How might we rectify this inconsistency and either have these requests use the same flow as others or bypass vets-api entirely?

## Goal
Discovery on which approach might be preferred (does vets-api add additional value here?) and ticket out implementation of the decided direction.

## Objectives or Key Results this is meant to further
- Ensure long-term ownership of maintenance of and iteration of VFSs
- Enable agile VFS delivery of performant applications

## Acceptance Criteria
- [ ] Documented decision on directly (GIDS API traffic directly sent to GIDS backend or implement fwdproxy)
- [ ] Epic to scope out and document work to accomplish above decision

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
I don't know that having GIDs behind vets-api is beneficial but I still lean in that direction because it seems more consistent with what we already have setup. I'm not convinced that is the best reason.

One concern that I don't know much about, is the ATO of GIDs. If we expose the service directly through the revproxy how does that affect ATO?

At first pass I think that exposing GIDS directly might be more work or maybe just that there are some more unknowns at the moment. So far it appears that moving GIDs behind the forward proxy would require at least the following:
- [ ] update the haproxy template to allow non-ssl backend (currently they all assume ssl)
- [ ] create a gids backend in each fwdproxy environment pointing to the gids load balancer
- [ ] update vets-api config to use fwdproxy for gidssdssui

**Comment by patrickvinograd** [comment]
GIDS is considered part of the vets.gov/VA.gov system for ATO purposes. I don't foresee any issues there.

**Comment by patrickvinograd** [comment]
There was some response rewriting happening, mainly around the JSON API `link` metadata for paginated results, e.g. to make the base hostname and resource path correct. Other than that it was mostly a pass-through last time I  looked at it. (But do your own investigation).

**Comment by wyattwalter** [comment]
+1 to what Patrick said here.

I think the biggest benefits to having it in the fwdproxy is that we get built-in health checking and can potentially do some tuning of connection limits to the backend.

During the investigation, I've noticed that some of request/response cycles have different endpoints to the GIDS backend as well, so I think it's changed a bit recently in terms of being "mostly passthrough".

**Comment by alexpappasoddball** [comment]
@ricetj Is there anything that the backend tools team needs to do for this?  It has our label and is on our board but we are unclear to if we have any action items here.

**Comment by ricetj** [comment]
> @ricetj Is there anything that the backend tools team needs to do for this? It has our label and is on our board but we are unclear to if we have any action items here.

@alexpappasoddball we have this one now, so I will take your label off.

**Comment by tskinn** [comment]
After talking with Wyatt this morning we are going to move forward with moving GIDs behind the forward proxy. It seems to be bets bang for our buck at this point. Moving it behind the revproxy would require more complex changes and the forward proxy will give us more insight into GIDs status and give us some more separation. 

epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4692
