### ISSUE TITLE
[Vets-API] Mark failing backends offline to avoid cascading connection pileups 

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3853]
## User Story or Problem Statement
During a recent GIDS outage postmortem, it was discovered that while vets-api does have circuit breakers that can kick in to mark a failing backend offline, it doesn't have anything like the [bulkhead pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead) explicitly implemented to avoid a situation where a particular backend can cascade connection pileups into the entirety of vets-api. There may be some limits, but they weren't hit during that incident and GIDS is not currently being serviced through the fwdproxy. How might we limit these upstream requests in order to ensure a large amount of connections to one doesn't starve others and result in a degraded service?

## Goal
Discovery, scoping, and implementation epic on a strategy to add something like the bulkhead pattern to avoid some forms of cascading failures related to traffic to backends.

## Objectives or Key Results this is meant to further
- Ensure VA.gov is a reliable site for Veterans to use

## Acceptance Criteria
- [ ] Epic for implementation of service protection feature created and scheduled

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
We will need to work with BE tools team for this task.

**Comment by alexpappasoddball** [comment]
@ricetj @wyattwalter is there anything that BE tools needs to do to wrap this up?  Its been siting on our board and just curious around priority, if it is still an issue we need to solve.  @johnpaulashenfelter and I were wondering what we can do to move this one along or toss it.

**Comment by jhouse-solvd** [comment]
@ericboehs & @npeterson54 - I'm curious to know if this is still relevant. Do you know if this situation still exists, and whether or not any work has been done that might address the concern here? Thank you both! 

cc: @mchelen

**Comment by ericboehs** [comment]
I think it is. @npeterson54 Let's discuss this when you're back.

**Comment by npeterson54** [comment]
@jhouse-solvd It looks like this is still an issue, I'll work with my PO to see if this should be prioritized.

**Comment by jhouse-solvd** [comment]
> @jhouse-solvd It looks like this is still an issue, I'll work with my PO to see if this should be prioritized.

Excellent. Thanks for the follow-up. Can we remove the "operations" label... If it feels like something that's w/in your team's wheelhouse?

**Comment by oseasmoran73** [comment]
- Vets-api has circuit breakers done automatically and in Prod. When we migrate over from BRD to EKS, they will come out of the box
- It looks like to do bulkhead pattern in EKS, the reroute goes dedicated pod. Questions I have regarding that
  -  Is that pod spun up dynamically? I presume not since we want "standby" or something along those lines. Just curious if it will be on a per service (which we have a few)
- Still need a more research on actual how circuit breaker + bulkhead will work

**Comment by oseasmoran73** [comment]
[Slack](https://dsva.slack.com/archives/D036ZT6SK99/p1666200540681949) convo detailing some good stuff! Will be spinning up tickets
