### ISSUE TITLE
User research library - Create searchable library of user research

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3855]
## User Story

As a team member building on or in support of VA.gov (VFS or VSP), I want to be able to search through past user research, so that I can re-use research that is applicable to my work.

## VSP Objective (Q1 & Q2 2020)

O2: Customers use qualitative and quantitative user data to build and iterate on VFSs. 

## Measuring Success (KRs/KPIs)

TBD

### Links

- [History of VFS research projects list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md)

### Goal(s)

- Give teams better access to past user research in order to further encourage human-centered design
- Save time and resources by not conducting the same user research again 

### Assumptions and Hypotheses

- We **assume** that the current list of user research (linked above) is insufficient. 
- We **assume** that user research has learnings and implications that are valuable beyond the immediate use case (that future teams and projects can benefit from having better access to past research). 

## Areas for Discovery

- Should this include only Veteran-facing research? Or should this also include VSP research and other internal studies?

**Comment by vbellissimo** [comment]
Cancelling/old task.
