### ISSUE TITLE
Access for Peter Holyoke

### ISSUE THREAD

**Issue by pjholyoke** [department-of-veterans-affairs/va.gov-team#38556]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Peter Holyoke

### Your Email

peter.holyoke@adhocteam.us

### Name of Your Team

PTEMS - Console UI - Senior Software Engineer - Ad Hoc LLC

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMToVZE/H7xZkSZcT8vshX9bfe03v5uRUh38DYwtvVSC9Sgm+n2so1vncyRRZopHFZivF7owRuoKPmem5Bf4mNX+tlAiMdQunbZKrNb1UK65m15zDABLymdZf6d/PLjU9Z7hXn2G8i61p+jNInHwR4+/NfFJRbWrrSaVF/Ip1/LJ+VpeIJcEnG/6DCSOaXHwGv3KpcO8uNe7u1yPmIe3rMyUIE7/GMxZkMwbn7wvFqdAMXTgEZxh0wOxqbTDzoxKzEb5CPMTvA3rbzl1EEskH8h6WjbnsQt7eVOY/EhNTK0pZ6ZDi/SkWmGhaw7Qm11icWB/VDPVANZ+XEXs6mKuN2BSJjg9sAlbnv0OceDNG8yTe9D/zl5Q16+wkcCODUAC5FnyHbbRWGOHtnevo8W69aB1f4XGfgZIsX/+qlXLb8i5EMGIfO1FCcGr1SPvGjiVgxUCxKEhd9LItgvYKzD48st4cG2OpA5H7xHXcDGBjh/0+fLTifDBXnh4mlU6M2slM= pholyoke@PeterHolyoke-HP

### Desired AWS Access

The resources for the Platform Console UI Team.
EKS, RDS, and System Manager - Parameter Store

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
**For AWS Access**
User: Peter Holyoke
COR: Courtney Bethea
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

User requesting same access as other members of the platform-console-ui team

**Comment by jsgarmon** [comment]
SOCKS access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via #vfs-platform-support if you have any trouble.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR, awaiting confirmation
