### ISSUE TITLE
Communicate w/ Facility Staff on Arrival Details

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38562]
## AC
- Get list of Facility staff that will be participating in the St. Louis trip
    - Perhaps get from Katonya, during the weekly meeting, the staff we need to coordinate with
- Questions for each facility
    - Find out high-volume days 
    - Do they need posters
    - Which poster version they are using
- Communicate and coordinate with Facility staff on our arrival details
    - When
    - Who ask for when show up
    - Where to go (if necessary)

**Comment by kristenmcconnell** [comment]
The contact at St. Louis to coordinate with are:
Samantha Hoover (samantha.hoover@va.gov) and Katonya Riddle (katonya.riddle@va.gov).

Stephen Barrs would like to be cc'd on all communications.

**Comment by benbrasso-agile6** [comment]
@loripusey @kristenmcconnell any issues if I pull this into this sprint since it's related to https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39077

**Comment by benbrasso-agile6** [comment]
Ok, I'll wait until then. Thanks
