### ISSUE TITLE
Console UI: Open links in new windows

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#38564]
**User Story**: as a user of the app I want links to open in new windows so that I don't lose my place in the app after clicking on the link.

**Comment by alexandec** [comment]
Links to the commit and the GHA run should open in new windows. This avoids the annoyance of losing your place in the app, then having to switch teams and reload commits.

**Comment by rmessina1010** [comment]
Console UI work on hold

**Comment by jhonnyoddball** [comment]
Console UI work, closing for now.
