### ISSUE TITLE
[Research] Conduct Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38565]
## AC
- [x] Perform on-site study with Veterans at St. Louis facilities
- [x] Perform on-site study with VA staff at St. Louis facilities
- [x] Take notes (one interviewer, one or more note takers)
- [x] Send out 2-3 bullet survey to check-in Slack channel at the end of each day, which highlights key takeaways from the day (send disclaimer that the summary make evolve as we complete analysis)

## Related Documents
TBD - insert link to research plan
TBD - insert link to conversation guide

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 I added the summary at the end of each day to the AC.
cc @zach-park and @ytsaoca
