### ISSUE TITLE
Create Research Documentation and Ticket Templates

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38568]
## AC
- [x] Create GitHub document that documents steps for planning and executing a research effort (trip or virtual)
- [x] Implement Kristen's new research templates

**Comment by kristenmcconnell** [comment]
Lori created the templates that I sent to her. They have been added to GitHub.

**Comment by kristenmcconnell** [comment]
Send draft to team [for review via Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1648845524358469).

**Comment by kristenmcconnell** [comment]
Made a [GitHub page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/process.md) in check-in's research folder.

**Comment by sarahknoppA6** [comment]
@kristenmcconnell does someone in particular need to validate this work item so we can close it out this sprint?

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 - Your comments have been incorporated into the [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/process.md).
