### ISSUE TITLE
[PagerDuty] Access token to make API requests from Github Actions (CMS Team)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#38580]
## Description
The CMS team is looking to trigger PagerDuty incidents from failure states in Github Action workflows for the content release pipeline. 

## Background 
- The workflow is in the content-build repo [here](https://github.com/department-of-veterans-affairs/content-build)
- CMS team is looking for a token to use when making PagerDuty REST requests; outlined [here](https://support.pagerduty.com/docs/api-access-keys#section-generating-a-general-access-rest-api-key) 

## Technical notes 
If this should be scoped to a particular team or escalation policy, here are the relevant ones:
* Escalation policy: https://dsva.pagerduty.com/escalation_policies#PW3ZKRA
* Team: https://dsva.pagerduty.com/teams/P6QVQSV/users

## More info from Tim Cosgrove: 

> The access token should provide the ability to that escalation policy to create incidents via the REST API. I do not have knowledge of how PagerDuty scopes access tokens, so I can't give guidance there. 
> 
> When available, the access token should be installed to SSM such that it is retrievable in a Github Actions workflow. We have a number of items under `/cms/prod/`, and that might be the right place to store them, but again we trust Infrastructure's direction there.
> 
> Let me know what other information I can provide to move this forward. Thank you!

**Comment by jhouse-solvd** [comment]
@timcosgrove - Just checking in. Is this still something that your team needs? Have there been any changes to requirements on your side? 

If not, we'll look at scheduling in the near future and reach out to clarify as needed. :)

**Comment by jhouse-solvd** [comment]
After speaking with Tim, it sounds like all that is needed is the PagerDuty API Key. The CMS team already uses Parameter Store for managing secrets. So, once they have the credentials or API key, they can take it from there. 

My vote would be to give them the ability to create API Keys in PagerDuty directly so that they are not blocked by the Platform Infrastructure team.

[From the PagerDuty documentation: 
](https://support.pagerduty.com/docs/api-access-keys#section-generating-a-general-access-rest-api-key)
> "Admins and Account Owners can create, disable, enable and delete general access REST API keys."

I'm following up w/ Platform Engineering so that they can make that call.

**Comment by jhouse-solvd** [comment]
@ElijahLynn @ndouglas - According to @little-oddball, you may already have the permissions needed to generate a REST API key in PagerDuty. If not, please let him know so that he can adjust permissions accordingly. 

cc: @timcosgrove

**Comment by oseasmoran73** [comment]
Closing ticket based on information provided by Jesse and Clint.

Please feel free to reopen if you all run into issues

**Comment by timcosgrove** [comment]
Thanks. We'll follow up on our end. At the time we opened the request, I believe we were unable to generate the necessary credentials. I'll have @ElijahLynn and/or @ndouglas look at this to see if they do in fact have permission.

**Comment by ndouglas** [comment]
I think I do indeed have that access 😎 

![Screen Shot 2022-07-20 at 3 23 06 PM](https://user-images.githubusercontent.com/1318579/180064977-8320e334-9304-4ab6-911d-0961c74a53a1.png)
