### ISSUE TITLE
Remove defer from web-components.js in Content Build header.html

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#38581]
## Old Issue
https://github.com/department-of-veterans-affairs/content-build/blob/302f019c5105308a80df09578f05fbebb44e6037/src/site/includes/header.html#L41

Our team added a defer about a year ago to help an issue with the Web Components loading properly in IE11. Since we load a lot of JS onto the page there were some conflicts and for rendering to occur properly the web-components.js was deferred until after the rest of the JS. 

## Current Issue
When using web components inside of Vets Website during the initial load of the page you can see a flash of unstyled text from the web component. This flash is not ideal and can be fixed by removing the defer on web-components.js. 

## Cavet 
defer cannot be removed until we sunset IE11 support

## Videos (Tested with Chrome no throttle)
With defer
![Screen Shot 2022-03-08 at 8.49.52 PM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/a96c61a2-3edc-4772-8ea7-9d80b44bf539)
https://images.zenhubusercontent.com/133843125/ba5ae85f-c473-4082-a2d9-05be2bb3b00b/screen_recording_2022_03_08_at_8_48_47_pm.mov

Without defer
https://images.zenhubusercontent.com/133843125/f5815fc9-264f-47fb-83c2-f3082b63db92/untitled.mp4

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated.
