### ISSUE TITLE
Access for Nicola Beuscher

### ISSUE THREAD

**Issue by deweydell** [department-of-veterans-affairs/va.gov-team#3859]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   >  Nicola Beuscher
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Analytics, front end engineer, Ad Hoc LLC
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUeE+W6/EpbataO3MKNuejSTiCiCX7udcoYOaBcvRajivhsKG/K1gYWeRdFbhajt2emeJ1FXKjrblzwzJqUgz5ellD/OnDalvsZ+viApyIeEdbH//CymwysyTcFPw1P8f1TEJBXyklTgk2THSR6QW3itpu5iVFfaQfyw+SHLk5AU5tsnUlndpCqAS6R6bwdvL+mNJM6GiiOzhQwf9GvSVn+6qXL0rBaZuKlGlNSTde00D5Ydy9dNNHPwB08ikRjZq4rMSI8bqijmB6wzU6qhljPcnFzgbhvzBOheex2Q0lKwauusgfQI3qDNZU74iK9DCSQwvDdMwWGjVMu7mjNvjj nicola@Nicolas-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > NO

**Comment by deweydell** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Nicola Beuscher
COR: Yourself

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS access.
