### ISSUE TITLE
[VAOS] Redirecting to Static Landing Page

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#38606]
## Description
A recent fix by the Identity team ensures all "sign-in from" urls are being respected. 

See [Slack](https://dsva.slack.com/archives/CMNQT72LX/p1638905945158800?thread_ts=1638904832.155400&cid=CMNQT72LX) conversation with Identity team for more info.

### Goal
There is informational content on the static landing page (unauthenticated) appointments page before the authenticated VAOS tool. We would like users who attempt to enter VAOS to be redirected to landing pages so that users receive required information before using the tool. Example: the auth widget has additional logic included for Cerner users that includes a CTA to the My VA Health portal.

### Requirements to Consider
- Scheduling and appointments for Cerner sites are managed in the My VA Health portal
- Veterans registered at Cerner sites and eligible for Community Care can use VAOS to request Community Care appointments
---

## Acceptance Criteria
**Scenario 1**
Given user is not logged in
When user directly enters the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`)
And successfully authenticates
Then redirect user to the static landing page (`/health-care/schedule-view-va-appointments/`)

**Scenario 2**
Given user is logged in
When user directly enters the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`)
Then redirect user to the static landing page (`/health-care/schedule-view-va-appointments/`)

**Scenario 3**
Given user is logged in
When user navigates to the VAOS homepage (`/health-care/schedule-view-va-appointments/appointments/`) from another VA.gov page
Then redirect user to the static landing page (`/health-care/schedule-view-va-appointments/`)

### Design Assets
It was suggested that to meet these requirements, the platform reverse proxy would need to be configured to do the redirects. The following ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/36132 was created with the devOps team requesting access to modify the necessary files or someone to make the necessary changes for the VAOS team.

DevOps response: If you know what changes need to be made, feel free to put in a pull request to change [the redirects file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml). We can always deploy dev revproxy from your branch to test. I'm not sure off-hand how one would use the revproxy to determine if a user is logged in or not.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JRRoof** [comment]
Still seeing loop when a veteran is registered at a Cerner facility.  Can we back this code out until we figure out what is going on?

**Comment by ldelacosta** [comment]
@vbahinwillit @JRRoof - I will create a feature toggle ticket for this effort. Thanks

**Comment by ldelacosta** [comment]
We will need to review the requirements and determine the best solution.

**Comment by ldelacosta** [comment]
@JRRoof - The Public Websites team handles all unauthenticated redirects. To request a redirect, we need to submit a [GH ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=Sitewide+IA&template=redirect-request.md&title=Redirect+Request).

**Comment by ldelacosta** [comment]
We will not proceed with the work. Closing out the ticket.
