### ISSUE TITLE
Adding several individuals to DSVA Slack

### ISSUE THREAD

**Issue by tBaxter** [department-of-veterans-affairs/va.gov-team#38610]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

I have a bunch of new hires I need to get access for:

Aselemi Danide - PST Engineer
Andrea Singh - PST Engineer
Nick Gaydosh - PST Engineer
Lauren Maxwell - PST Engineer
Peter Holyoke - PST Engineer
Mihir Busa - PST Product Manager
Kavitha Krishnan - PST Designer
Robyn Singleton - PST Researcher.

I think that's it. All of these are Full Members.

**Comment by LEHigley** [comment]
@tBaxter i need email addresses, please!

**Comment by tBaxter** [comment]
Ah yes

Aselemi Danide - Aselemi.Danide@adhocteam.us
Andrea Singh - andrea.singh@adhocteam.us
Nick Gaydosh - nick.gaydosh@adhocteam.us
Lauren Maxwell - lauren.maxwell@adhocteam.us
Peter Holyoke - peter.holyoke@adhocteam.us
Mihir Busa - mihir.busa@adhocteam.us
Kavitha Krishnan - kavitha.krishnan@adhocteam.us
Robyn Singleton - robyn.singleton@adhocteam.us

**Comment by LEHigley** [comment]
already in slack or invited: robyn, mihir, peter

updated account type: kavitha

everyone else added
