### ISSUE TITLE
[Design] Accessibility improvements: Changing error and confirmation pages to have H1

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#38614]
# Description
Based on the recommendation from the accessibility team, we want to have H1 for each page. However, some of the error or confirmation page only include an alert (with no H1) and some of the pages present H1.

There are two scenarios where the designs need to be updated:
- ![Screen Shot 2022-03-15 at 2.41.48 PM (1).png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/3184d8c4-a740-4572-82da-e95a95969ab3)
  - The screen on the left needs to look like the screen on the right.
- ![Screen Shot 2022-03-15 at 2.42.12 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/25168eab-f97a-44b5-bdfd-b786b43c6a7a)
  - This scenario also needs to be updated. 

These scenarios were easy to identify and update at the same time as #38268.

# Acceptance Criteria
- [ ] Update Sketch
- [ ] Update the [error message source of truth documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md)
- [ ] Work with Lori to have FE tickets created

**Comment by ytsaoca** [comment]
Check-in brainstorm. Will confirm one at the UX sync meeting

![Screen Shot 2022-03-17 at 11.04.57 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/8d517d81-dea6-4435-8817-e652b2d2a891)

**Comment by ytsaoca** [comment]
Final design of the check-in confirmation page
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/YGmJ5Ge
