### ISSUE TITLE
1010 Team | Transition Tickets

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#38624]
## High Level User Story/ies
Given the upcoming transition of the 1010 Team (both EZ and CG) we want to provide as much detail as possible relating to the applications, technology, features etc. The hubs below are what we will use to add documentation, diagrams and link to relevant materials. 

Please open tickets to capture your work and include this epic.

Link to [10-10CG Hub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Transition%20hub)

Link to [10-10EZ Hub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/Transition%20hub)

### What must be true in order for you to consider this epic complete? 

- [x] Transition Hub pages must be completed for 10-10CG
- [ ] Transition Hub pages must be completed for 10-10EZ

**Comment by RudyOnRails** [comment]
Just a heads up, the link in the description for the CG, goes to the EZ. No biggy! But just wanted to share I am editing it to point to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Transition%20hub
