### ISSUE TITLE
[03/23/22] PHI/PII Helpdesk FAQ

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#38622]
## Description
Create FAQ section for PHI/PII in VEText for users and helpdesk.
---

## Acceptance Criteria

- [x] Cover rules for PHI/PII with @jwowk 
- [x] Draft FAQs
- [x] Post draft to team slack channel for review
- [x] Send to Shane for review
- [x] Approved by Shane
---

**Comment by chancetheoriginal** [comment]
Draft posted to Slack channel.

**Comment by chancetheoriginal** [comment]
SharePoint link sent to Shane 4/6, awaiting approval.
