### ISSUE TITLE
Update OOB process guidance

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#38620]
## Background
OOB deploy was triggered without OCTO-DE Platform approval https://dsva.slack.com/archives/CBU0KDSB1/p1647379728070959

## AC
- [x] [Deployment policies](https://vfs.atlassian.net/wiki/spaces/PWD/pages/1279787009/Deployment+Policies) updated to specify OCTO-DE Platform crew is required for OOB approval
- [x] Guidance shared out with platform teams
- [x] Train SRE team on Guidance
- [x] Created Templates

**Comment by zachclarity** [comment]
Add details to [Deployment policies](https://vfs.atlassian.net/wiki/spaces/PWD/pages/1279787009/Deployment+Policies)

**Comment by zachclarity** [comment]
Created [new OOB Deploy Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-sre%2C+operations%2C+Console-Services%2Cfrontend&template=OOB-Deploy-Request.md&title=OOB+Deploy+Request).

**Comment by zachclarity** [comment]
TODO: Update public Developer Document with OOB info.

**Comment by little-oddball** [comment]
We additionally notified TLs in the TL channel.

**Comment by little-oddball** [comment]
The developer manual request page updates are in-flight waiting on auto deploy, which should occur Wednesday.
