### ISSUE TITLE
Update tuition and filter results accordions/buttons are displayed before search has been executed 

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#38631]
## What happened?
On mobile in both mode portrait and landscape, I noticed that in "Search by location" tab, the update tuition and filter you results buttons/accordions are displayed in the landing page before search has been executed. 

1. Portrait mode: 
<img width="503" alt="Screen Shot 2022-03-16 at 10 51 36 AM" src="https://user-images.githubusercontent.com/86266024/158626419-6662483c-2ac5-4ff8-9a71-9264fee3414a.png">
2. Landscape mode: 
<img width="706" alt="Screen Shot 2022-03-16 at 10 52 52 AM" src="https://user-images.githubusercontent.com/86266024/158632328-7cad5a26-851b-4848-bbe7-10d53a0c71d0.png">

## Steps to Reproduce
- On a mobile in portrait mode, navigate to: https://staging.va.gov/education/gi-bill-comparison-tool/
- Click to expand the "Search by location" tab. 
- Verify if update tuition & filter your results buttons are displayed.
- Switch the view to landscape mode 
- Verify if update tuition & filter your results accordions and buttons are displayed

## Desired behavior
- On Portrait mode, the Update tuitions & filter your results buttons should be displayed only after the search has been executed.
- On Landscape mode, only the update tuition & filter your results accordions should be displayed after the search has been executed. Remove the extra buttons.

## Acceptance 
- [ ] Update tuition & filter you results accordions/buttons should be displayed in the search results page along with the results (only after search has been executed) not in the landing page.

**Comment by hallihocine** [comment]
Ticket has been validated in staging: on mobile in both modes (Portrait and landscape), the "Update tuition  and housing estimate & filter your results" buttons/accordions, are displaying only after the search has been executed. 

1. Portrait mode: 
- Before search:                                                            
![Screen Shot 2022-03-22 at 4.05.06 PM.png](https://images.zenhubusercontent.com/60e7390c5052ef146bcc412e/bdcae4f6-adc5-4b03-8016-ff507774f646)
- After search: 
![Screen Shot 2022-03-22 at 4.05.44 PM.png](https://images.zenhubusercontent.com/60e7390c5052ef146bcc412e/17a2be58-f6ea-4f0d-9b82-751cd8c1346b)

2. Landscape mode: 
- Before search:
![Screen Shot 2022-03-22 at 4.06.24 PM.png](https://images.zenhubusercontent.com/60e7390c5052ef146bcc412e/0b068a51-73a7-473f-935c-958101cd6653)
- After search: 
![Screen Shot 2022-03-22 at 4.07.14 PM.png](https://images.zenhubusercontent.com/60e7390c5052ef146bcc412e/18dd1e8a-8a19-4ce8-89b1-44e6c0b1a10a)

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3099&group_by=cases:section_id&group_order=asc&group_id=4063

**Comment by mrblanco1** [comment]
QA and UAT passed on 3/28/2022.
