### ISSUE TITLE
Finalize Platform team facing guidance

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#38644]

**Comment by gmaciolek** [comment]
- [Platform website guidance](https://vfs.atlassian.net/l/c/wXY0kyA0) and [changelog](https://vfs.atlassian.net/l/c/9LuMHEjo) are updated.
- [Platform deployment process instructions](https://vfs.atlassian.net/l/c/muAS1R1n)
