### ISSUE TITLE
Research - Separate API Domains

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38657]
## Product Outline / Direction
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
[Setting Direction](https://docs.google.com/document/d/1i0WgBFcOK0sL1x_WL5V7JMDRxPsM9aRcszput9iVkp8/edit#heading=h.tgg7b8o5t7ok)

## Hypothesis or Bet
**If** we separate the domains used by vets-api and the Lighthouse APIs, **then** we expect restraints on traffic routing to be easier to navigate, and to gain the ability to move the Kong API gateway out of the DSVA environment and into the DVP/Lighthouse environment.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

- Intended partitioning of vets-api and Lighthouse traffic is clear and defined in a document
- Review the [Explainer](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap#Decoupling-options-%5BHighly-Speculative%5D) and confirm that the untangling option has been chosen

## How to configure this issue
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by alwerner** [comment]
Closing as complete. cc: @madebydna
