### ISSUE TITLE
[Design, FE] My VA: Align Health care link list on left when there are no appointments or messages

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38658]
## Background
Now that we have added the 'no appointment' text for users that have no upcoming health care appointments, we need to ensure the alignment of the link list is consistent on the page.  This change will be behind the same feature flag as payment info changes.

For the Health Care section, when there are no unread messages AND no upcoming appointments, the link list should align to the left side, underneath the message "You have no appointments scheduled in the next 30 days."

![image](https://user-images.githubusercontent.com/92328831/158676464-a562a7f5-90d3-492e-a0cf-abab7aca3c2c.png)

## Tasks
- [x] Update design sketch file to include a mockup of the alignment update
- [x] Update the code to align the link list in the event of no unread messages and no upcoming appointments

## Acceptance Criteria
- Health care link list will be aligned appropriately, depending on whether there are unread messages and/or upcoming appointments

**Comment by hdjustice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/38658?planning-poker) with ZenHub @aagosto90 @tmitchellgcio

**Comment by aagosto90** [comment]
If the user DOES have unread messages, we will still align the links on the right though, correct?
![Screen Shot 2022-03-21 at 2 37 18 PM](https://user-images.githubusercontent.com/97965610/159341528-fb21162b-df3d-46b0-abae-89e0cad97d14.png)

@Samara-Strauss @hdjustice @andaleliz

**Comment by andaleliz** [comment]
I think so, since there is content other than a single line of text in the left side. It does look a little weird with the empty space.

**Comment by Samara-Strauss** [comment]
>If the user DOES have unread messages, we will still align the links on the right though, correct?

Yes, correct. This will match the pattern in the Payments section, where the alerts are also left aligned.

**Comment by aagosto90** [comment]
@tmitchellgcio 
[Sketch design for desktop if user has no messages or appointments in the next 30 days](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/GmRbwjE)

[Sketch design for same scenario on mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/OmjZoGG)

**Comment by hdjustice** [comment]
Incomplete in Sprint 70 - work on an unplanned test fix took longer than expected, which pushed this work to the next sprint. Anticipate this will be completed in sprint 71.

**Comment by hdjustice** [comment]
Tested with user 12 and user 36 - information shows in one column, as expected.
<Details>
<Summary>Screenshot of links and 'no appts in 30 days" message in one column</Summary>

![image](https://user-images.githubusercontent.com/92328831/162444375-bf468fb1-ca20-48f9-83c4-135165112816.png)

![image](https://user-images.githubusercontent.com/92328831/162444769-c5e9bf80-ef32-4442-828e-23b5ff666885.png)


</Details>


Testing with Users 1 and 41 display the error for Appointment API fail.  The links display in a second column, as expected.

<Details>
<Summary>Screenshot of appointment error and links in 2 columns</Summary>

![image](https://user-images.githubusercontent.com/92328831/162445391-43ec5329-edb2-43dd-8fff-3426f8dcb73f.png)

</Details>

I am not able to find a test user with unread messages.  The one we had (User 41) no longer has unread messages.

cc: @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Looks great!
