### ISSUE TITLE
Business intake form for Insurance Product Line

### ISSUE THREAD

**Issue by vickilinscombe-coleman** [department-of-veterans-affairs/va.gov-team#38653]
## Requestor Name
Vicki Linscombe-Coleman, GovCIO
vicki.linscombe-coleman@va.gov
512.285.0857

On behalf of the VA Insurance Product Line
## Business Line
Insurance Product Line

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
Send text messages to Veterans when they have Insurance documents from their policies.

## What is an overview of the notification use case? (required 3-5 sentences) 
GIVEN the user has a policy in LifePRO
WHEN an Insurance user creates any letter in LifePRO
AND the user communication preference is electronic
THEN the letter is saved in the document repository
AND the LIPAS system through SmartComm can send a text message with a link to the LIPAS OPA website 
AND the LIPAS system through SmartComm can send an email with a link to the LIPAS OPA website

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
The Veteran will receive a text message with a link to the insurance web site so they can access their policy document. 

As a LIPAS system I need to send electronic communications to policyholders

Text Message
You have a new document from VA Life Insurance: https://insurance.va.gov/home

Email Message 
Dear <policyholder name>

You have new VA Life Insurance documents to review at https://insurance.va.gov/home.

VA Insurance Center

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No; it is a new service we need to make available to the Veteran.

## What kind of notification would this be? (required Email, Text, Not sure)
Text.

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
Not sure.

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
LIPAS LifePRO through SmartCOMM

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes.  SmartCOMM will generate the text to send.

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
Yes. 

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
Not sure.

## What is your estimated volume of notifications per day, week, month? (optional - open space)
Uncertain at this time.

## When does this notification need to be in production? (optional - open space)
VALI is scheduled to be a product offered by VA Insurance on 1 January 2023.  The expectation is we have it in our PPD system soonest.

**Comment by bevnobev** [comment]
Hi @vickilinscombe-coleman.  Thanks for reaching out.  Quick question for you.  Are LIPAS LifePRO and SmartCOMM VA systems or external systems?  cc: @mjones-oddball

**Comment by vickilinscombe-coleman** [comment]
Hello
So glad to see this here.

They are internal systems to the VA.  LIPAS is the modernization of the legacy Life Insurance system.  LifePRO and SmartCOMM are two components of the overall 4 components that make up the modernized system.

Please let me know that my next steps are to further this request.
Vicki

Vicki L-Coleman, (Contractor) PMP
GovernmentCIO, Portfolio Director
***@***.******@***.***>
***@***.******@***.***>
512.285.0857

From: Beverly Nelson ***@***.***>
Sent: Wednesday, March 16, 2022 3:21 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Linscombe-Coleman, Vicki V. (GovernmentCIO) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for [Business or team] (Issue #38653)


Hi @vickilinscombe-coleman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvickilinscombe-coleman&data=04%7C01%7C%7Cf1f1195a4a5d40a3377208da078a8878%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637830588814920324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jwigx8SFvXnE7sfiCCasVeqQ1Iz5X1akiWZMVWFbEVc%3D&reserved=0>. Thanks for reaching out. Quick question for you. Are LIPAS LifePRO and SmartCOMM VA systems or external systems? cc: @mjones-oddball<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmjones-oddball&data=04%7C01%7C%7Cf1f1195a4a5d40a3377208da078a8878%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637830588814920324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JY6HLWPFEeQBOHqPOcbznnTqE0nOtd2OB0FMrBLTsk8%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F38653%23issuecomment-1069586659&data=04%7C01%7C%7Cf1f1195a4a5d40a3377208da078a8878%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637830588814920324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ScorC79FJ2RUPryJNgl1nEyNkvE03jaNHNeYF6kIi4Q%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ2CJXNPP4PUPQG4XPCNGD3VAI7D3ANCNFSM5Q4UO2UQ&data=04%7C01%7C%7Cf1f1195a4a5d40a3377208da078a8878%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637830588814920324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3QEVAOoVxwIprecDW3acgU5xJdfFWzhDba12PMYbsLg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf1f1195a4a5d40a3377208da078a8878%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637830588814920324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hYvbA6R62K%2BKhP2p%2FIClHpyVC3eTlnKW587Oc5ez6zs%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf1f1195a4a5d40a3377208da078a8878%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637830588814920324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mdHLo56bzwPA4W3uxMYnskIXnowzIaeXah24WerdxQ4%3D&reserved=0>.

**Comment by bevnobev** [comment]
Hi @vickilinscombe-coleman.  Can you share some dates/times that are available next week for us have a chat?

**Comment by vickilinscombe-coleman** [comment]
Hello Beverly
Please let me know your availability and I will make sure I can attend any discussion.  This is a high priority item for us so the sooner we can get with your team the better for us.
Vicki

Vicki L-Coleman, (Contractor) PMP
GovernmentCIO, Portfolio Director
***@***.******@***.***>
***@***.******@***.***>
512.285.0857

From: Beverly Nelson ***@***.***>
Sent: Thursday, March 17, 2022 7:53 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Linscombe-Coleman, Vicki V. (GovernmentCIO) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for Insurance Product Line (Issue #38653)


Hi @vickilinscombe-coleman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvickilinscombe-coleman&data=04%7C01%7C%7Cd59f2b84c76045d3816c08da0879ab05%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637831615900505568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FTbLG0EQHcdcQPJTULCCdJVN4gcfxRWl%2B0s4QKylyVg%3D&reserved=0>. Can you share some dates/times that are available next week for us have a chat?

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F38653%23issuecomment-1071912207&data=04%7C01%7C%7Cd59f2b84c76045d3816c08da0879ab05%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637831615900505568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KBXx0vqXpinewmiwn2jHlO6fPCLDFtq2F3VSMXX3gGw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ2CJXOKHOM2544MMYVM7W3VAPHXBANCNFSM5Q4UO2UQ&data=04%7C01%7C%7Cd59f2b84c76045d3816c08da0879ab05%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637831615900505568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AOxPfthKPS6tHJA%2FSWk1kuhnjNpATY3EvhUk4PynpX0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd59f2b84c76045d3816c08da0879ab05%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637831615900505568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mMZc3eup2dbma0OJtmCVQ0dbl1OnRgg5chtMKelzwcU%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd59f2b84c76045d3816c08da0879ab05%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637831615900505568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1KOqc1%2Bj6yopA%2FyPgqRLyuuPvbxWjirM3RtuPP8c2WU%3D&reserved=0>.

**Comment by bevnobev** [comment]
@vickilinscombe-coleman  tomorrow (Tuesday) 2pm-3:30pm and Wednesday 1-2pm.  If we could keep the meeting to 30 mins, that would be great.
