### ISSUE TITLE
Datadog Alert: Production Outbound

### ISSUE THREAD

**Issue by sylvesterlee1911** [department-of-veterans-affairs/va.gov-team#38663]
# Description
This covers alerts for ID.me LOA1 users and MHV basic users connectivity.  If users are unable to access VA.gov, this alert will trigger.

# User Story
**As a** VSP Engineer
**I need** to make sure that datadog alerting has full coverage.
**So that** we have full visibility of the applications we are responsible for.  

# Acceptance Criteria (Engineer Checks Off)
- [ ] If ID.me LOA1 user login fails, alert triggers.
- [ ] If MHV basic user login fails, alert triggers.

# Technical Description

# Deliverables (Product Manager Checks Off)
- [ ] Datadog alert for ID.me LOA1 user login failure
- [ ] Datadog alert for MHV Basic user login failure

# Expected to Finish:
- [ ] March 30

**Comment by sylvesterlee1911** [comment]
Needed: idme loa1, mhv basic

**Comment by joeniquette** [comment]
MHV basic prod test: https://app.datadoghq.com/monitors/61944538
IDme loa1 prod test: https://app.datadoghq.com/synthetics/details/erd-8q7-dna
This was completed back in January and shouldnt have had its own ticket
