### ISSUE TITLE
Access for Andrea Singh

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38669]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Oddball - Sabrina Ammon

### Your Name

Andrea Singh

### Your Email

andrea.singh@adhocteam.us

### Name of Your Team

CIT - Platform Spike Team

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6xowxGHP2nXld8/edmB+3uCTLsVzwnFMCYnMZqofdXD4CBNqAJYXvXtfGimY25Gl1U0CfMTmBrCPKXwOxLO7HUgW9FC0t4eY/VctyFcXdRIzMVJFIJFSVlNZVnT6sdT0Ha+OzDNWFnmEFDpySkH5BQZkvMwRXh1mwTqiXaocOFyHM98DdUVUEljFt0Hb+VHOtHpbHbvKRCoVPf69al33BbF0LlZu8D7PyU4LtRFFh/kP7AcjzNyU0APVzhCotOrEEkYcb132vsrL13oF7BLBlt5AWEr5A+kBuMtvKPYGeyBpwigbsgRkYuxNsq6yhBLINEwM2o6vE+BefoTEimW1Aiqh6tQFeaC2tQuPGy7IvWcDW6HO+vip3KO6U5py4smytYO2xVqbfkOYBsSzY9zaN4iS7+miT2anPsI/CR9fzYZmqvVEt7q/H+Om3hidj3SwhOJrKD7XKFlZ0L4McaRql6FpT1aG3nA9rHJFtDbZIQjg1sgIYFDDOJDgfAzIauxs= andrea.singh@adhocteam.us

### Desired AWS Access

My team lead, @dginther, will create a team in Terraform for us.

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
SOCKS access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.

**Comment by jsgarmon** [comment]
**For AWS Access**
User: Andrea Singh
COR: Courtney Bethea
VOR: Oddball - Amber Malcolm
Approval needed: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by dginther** [comment]
My apologies, it is Sabrina Ammon.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR, awaiting confirmation

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS Access Approved

**Comment by jbritt1** [comment]
First-time login credentials provided via DSVA Slack workspace DM at this time.
