### ISSUE TITLE
[Content Review] HLR: Identify Legacy Issues on Submission Review Screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3866]
**User story**
As a member of Benefits and Memorials team building on VSP, I need the legacy issues content reviewed  on the submission review screen to ensure it's accurate, aligns with VA style, and is error-free.

**Screenshot and Links**
- [Design ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3861) - this ticket was closed as OBE.
- [InVision Design]() - Never had a real link here

**Acceptance criteria**
- [ ] Content reviewed - OBE
- [ ] Required content updates/changes provided to Benefits and Memorials team - OBE

**Comment by luke-gcio** [comment]
Closing as OBE after doing a review.  No more legacy issues on the submission review screen but we will need additional content support.  New tickets will be written under this Epic.
