### ISSUE TITLE
Search by location map shifting horizontal alignment during search

### ISSUE THREAD

**Issue by jfinnern** [department-of-veterans-affairs/va.gov-team#38667]
When performing a Search by location search **for the first time**, the Search results column will pop in and out of display on the page while the results are being loaded. This causes the map to shift to left alignment when the Search results column disappears and then shift back to right alignment when the Search results column reappears. Subsequent Search by location searches do not show this behavior.

https://user-images.githubusercontent.com/86262877/158681280-2f1432ff-f213-421f-90be-dcc7d171c8e8.mov

## Steps to Reproduce
- Navigate to https://staging.va.gov/education/gi-bill-comparison-tool/
- Select the Search by location tab
- Enter a location in the search bar and click Search

## Acceptance Criteria
- The Search by location map remains in a fixed position while the search results are loading and being displayed

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3104&group_by=cases:section_id&group_order=asc
Test case: [Search by location map shifting horizontal alignment during search.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8336749/Search.by.location.map.shifting.horizontal.alignment.during.search.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed on 3/28/2022.
