### ISSUE TITLE
Chrome extension 'axe-coconut' no longer available

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38666]
### Description
Per the website referenced in the Advanced Accessibility tests for axe-coconut, the extension is no longer available.  Per the comments at the bottom of that page, any learnings from that extension were rolled into the axe Devtools extension.
In this case, I am suggesting to remove axe-coconut from the recommended testing.

### Relevant URLs
[How to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)
[Referenced blog mentioning axe-coconut](https://www.deque.com/blog/test-leading-edge-accessibility-axe-coconut-axe-core-3-0/)

**Comment by gmaciolek** [comment]
Thanks for catching this and letting us know, @hdjustice! 

@briandeconinck or @ddzz can one of you address Heather's feedback? I also found a mention of axe-cocunut in the [How to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) doc.

**Comment by ddzz** [comment]
@shiragoodman @Saraharaba8 @briandeconinck

**Comment by briandeconinck** [comment]
Agree that the references to axe-coconut should be removed.

I'll also mention: I think it's probably worth spending some time revising/re-thinking what we're recommending for advanced accessibility testing. There's not a ton of guidance there now, and the item on screen reader testing might be a heavy lift for some VFS teams.

**Comment by gmaciolek** [comment]
@shiragoodman can you have your team remove the axe-coconut references? 

We're announcing soon that the Platform content team is going to start twice weekly Platform website content "deployment." If your team removes the info, you don't have to worry about making the change live using Scroll Viewport. Our team can care of that when we publish all pending changes to the live Platform website on Tuesday.

I assume spending time re-thinking advanced accessibility testing would be an item for your team's backlog, so I'll leave that to you to decide what to do with it.

**Comment by shiragoodman** [comment]
thanks @gmaciolek. yes, we can make the change to remove the reference. I'll get a ticket written up.

Re: the twice weekly PW "deployments" - where can I read up on this? That's a great idea!
