### ISSUE TITLE
GIBCT School Certification Officer 508 Document Epic

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3867]
This will be the epic where all of the document-related findings are stored for the SCO improvement on GIBCT. This has been opened as a separate epic to keep VA 508 office findings separate, and will focus on the documents only.

**Comment by dneel-bah** [comment]
There are no musts; and all remaining issues have been passed to the EDU for updating of PDFs.  Closing this issue and remaining items are remaining open in the backlog.
