### ISSUE TITLE
Update Kubernetes configmap with cert lowers change

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#38677]
In a recent PRL https://github.com/department-of-veterans-affairs/devops/pull/10923
va-vsp-bot recommended we update the Kubernetes settings as well:
Please update the corresponding values in the k8s ConfigMap https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/settings-configmap.yaml.
 If you have updated a secret value, please also update the corresponding secrets.yaml https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/secrets.yaml.

**Comment by joeniquette** [comment]
Completed in https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/39693
