### ISSUE TITLE
[Design Review] HLR: Identify Legacy Issues on Submission Review Screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3868]
## Story
As a designer I want to have my work reviewed by the proper members of the platform team so that I know that what is being produced is consistent with intent, design language and messaging.

## Goal
Present legacy issues on the HLR Submission Review screen layout to Design community.

## Task
- Schedule time with Platform for review and feedback of  latest mockup for the "HLR Submission Review" screen 
- Gather and incorporate feedback to ensure consistent application of design system components. Troubleshoot potential design/development related issues. 
- Communicate concerns regarding design/research constraints or roadblocks.

## Acceptance Criteria
- [ ] Scheduled and conduct review session 
- [ ] Incorporated feedback and re-presented layout as needed.

## Correlating Tickets
[Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3861)

**Comment by rileyorr** [comment]
@YanaRoy I'm going to close this ticket. I think BaM1 is well beyond this ticket's task in regards to HLR
