### ISSUE TITLE
Access for Mike Haley

### ISSUE THREAD

**Issue by mhaley37** [department-of-veterans-affairs/va.gov-team#38680]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Mike Haley

### Your Email

mike.haley@adhocteam.us

### Name of Your Team

PTEMS - Console UI, Software Engineer, Adhoc team LLC

### Service(s) You Want Access To

AWS

### Desired AWS Access

Access to `parameter store path: dsva-vagov/platform-console-ui/` as was granted to my colleague in #3850

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
**For AWS Access**
User: Mike Haley
COR: Crystal Moultrie
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Approvers will check with your VOR on your EQIP status.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
approved

**Comment by jsgarmon** [comment]
User added, and first-time login instructions sent via Slack.
