### ISSUE TITLE
Access for [Aselemi Danide]

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38692]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Aselemi Danide

### Your Email

aselemi.danide@adhocteam.us

### Name of Your Team

PST- Cloud Isolation Team

### Service(s) You Want Access To

SOCKS, AWS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9YNi4CkaIeiAoBrgG8Z4lEwZBdgN3pyrYnoMt9RFnRJMSc8bigvrWPrDmzDCWEc0dw/QU82ZRXhk8WivCWY/3COLBUlIWIr+sHc8X3O+NjNTL9rUH0SHBPsvIr9gxe7e8wdsRKCpIkRTlReWwO4Q4zCIsxGC2P4KvABgHyb9hXyFR61b4albhDKwtkYEcho3mngQfXVFjDcwF0VQlDSZNGyKEcAuL78/BBbQ9n/h3rojGuYfVLLJHPfC8vKd2cNRBBYrQaTtoaTbPJpFqLEf4AeLDyMY2yK2j8bBciDrcQYVfEgNHwbeVAu5m1jevzJR07CRFU/4zWxw/sUGPbW0L aselemi.danide@adhocteam.us

### Desired AWS Access

My team lead, @dginther, will create a group for the team in Terraform.

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
SOCKS access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.

**Comment by jsgarmon** [comment]
For AWS Access
User: Aselemi Danide
COR: Courtney Bethea
VOR: Oddball - Amber Malcolm
Approval needed: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Approvers will check with your VOR on your EQIP status.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
@dginther; the VOR in the issue advised me that Aselemi is not on her list; which VOR should I reach out to?

**Comment by ph-One** [comment]
User has been removed from all socks proxies.

**Comment by dginther** [comment]
Stopping this process for the moment.

**Comment by dginther** [comment]
Onboarding for this user will not continue. Closing this ticket.
