### ISSUE TITLE
Accessibility Feedback for Midpoint Review | 1010 EZ | Short Form

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#38694]
# Accessibility Feedback for Midpoint Review | 1010 EZ | Short Form

Reviewed with @Dene-human earlier today! Feedback along with fixes that have already been made have been documented below.

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Must
- None

### Relocate the "why are you asking" above the continue/back buttons ✅  (RESOLVED)
Screen reader users will likely not know that this component exists as it is below the two key navigational buttons. This has already been resolved by @Dene-human and @lzapson 🥳 

<img width="1321" alt="Screen Shot 2022-03-17 at 9 45 35 AM" src="https://user-images.githubusercontent.com/14154792/158840229-e4323198-b43a-48c9-a225-87a687bc3ef1.png">

### Consider removing or finding an alternative pattern to the alert asking if users are sure ✅  (RESOLVED)
Due to technical challenges we've observed in the past, building this alert to work inclusively with screen reader users may prove to be a challenge. @Dene-human and @lzapson are deleting this for now, but will plan to track analytics and make this a question to explore in future research 🙏 

<img width="1288" alt="Screen Shot 2022-03-17 at 9 49 05 AM" src="https://user-images.githubusercontent.com/14154792/158841040-5b862716-1f78-4e8e-8329-509657e324fe.png">

### Consider testing or gathering more feedback on the persistent green alert that reminds users they're on a shortened form
@Dene-human has had a chat with @AngelaFowler82 about this. I have a _very_ slight concern this might be bothersome to screen reader users if it appears repeatedly on every page below the step x o y heading with no way to dismiss it. Curious to see how this would perform in usability testing in the future.

<img width="1096" alt="Screen Shot 2022-03-17 at 9 54 09 AM" src="https://user-images.githubusercontent.com/14154792/158843516-a7d72876-13db-42dd-b88e-b153e88904d1.png">

### Consider designing mobile wireframes 📱 
As 50%+ of Veterans access VA.gov using mobile devices, we recommend designing mobile wireframes for touchpoint reviews 🙏

**Comment by SKasimow** [comment]
Hi @joshkimux - can this be closed?

cc: @Dene-human

**Comment by joshkimux** [comment]
Yes, closing this out 👍
