### ISSUE TITLE
AWS Staging: Improve error message when double booking 

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#38693]
1. Cecil Morgan has an existing appointment at CHY PC VAR 2 on 10/7/22 at 12:00. 
2. Log in to VAOS as Cecil Morgan and attempt to direct schedule an appointment that overlaps that. (I used the 12:10 slot.)
3. The system (correctly) generates an error instead of booking it. The back end returns this error:

{"errors":[{"title":"Conflict","detail":"patient already has overlapping booked appointment","code":"VAOS_409A","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012845943V900681/appointments","vamfBody":"{\"message\":\"patient already has overlapping booked appointment\"}","vamfStatus":409},"status":"409"}]}

4. The front end, however, displays a generic error. (see attachment.) 

Much more useful to let the user know what the problem is, based on the information passed in by the back end, instead of the current vague message. The user could just pick another time, if they knew that was the problem. 

![genericError.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/8ff682c7-b613-4d00-8c80-5d5383fc9c58)

**Comment by marcynadeau** [comment]
@ldelacosta I will assign to Beth for testing but right now there is an issue in Staging and we can't direct schedule.   @beth-wodzinski @aarathi-poldass

**Comment by ldelacosta** [comment]
@beth-wodzinski - Is this still an open issue on your end? Please advise when you have a chance. Thanks.

**Comment by beth-wodzinski** [comment]
@ldelacosta I tested this again and it looks great. The message now says "We’re sorry. You already have an overlapping booked appointment. Please schedule for a different day." Verified!

**Comment by ldelacosta** [comment]
This has been validated and no issues reported. Closing out the ticket.
