### ISSUE TITLE
[UX] Gather and package final translation documents

### ISSUE THREAD

**Issue by niradatta1** [department-of-veterans-affairs/va.gov-team#38700]
We need to generate three documents to deliver to the State for translation estimates: 
1) JSON file of content in the app (completed in ticket xxx)
2) JSON file of content in SMS texts
3) Excel file of content in poster

Tasks

- [x] Work with VeTEXT / CHIP to auto-generate a JSON file for the content in the SMS texts (check-in and pre-check-in)

##Acceptance Criteria

- [ ] Zip file of all content to be translated delivered to Danielle in a slack message
- [ ] Total word count documented and delivered to Danielle

**Comment by kristenmcconnell** [comment]
@loripusey @acrollet @randomsync  I thought that I had all the information from our team to create this final package. However, we realized that we need a list of all the relationships possible for NOK and emergency contacts (spouse, mother, etc). Do you want a separate ticket to handle that? or how do you want to deal with that? UX discussed pulling this ticket into this sprint, so I could need that information to complete this ticket.

**Comment by loripusey** [comment]
We already have a [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38863) out there

**Comment by kristenmcconnell** [comment]
@loripusey I brought this up during stand-up. Mark said that @acrollet might be a good person, but I was wondering if we actually need someone with VISTA access to pull the list. Relationship is a VISTA data point that we are pulling in.

**Comment by loripusey** [comment]
@kristenmcconnell is this comment related to translations or pulling the list of relationships for EC and NOK?

**Comment by acrollet** [comment]
I believe this was mentioned on the call with VA Profile this morning, @brianseek did they provide a definitive list anywhere that we can use?

**Comment by loripusey** [comment]
I copied the list into this [ticket ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38863)

**Comment by kristenmcconnell** [comment]
Created a .json with the poster, SMS, and NOK relationship information. Posted it to [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1648507736613359). I'll review it with Nira tomorrow.

**Comment by kristenmcconnell** [comment]
Due to new scope for editing, we need to gather the new content, then .zip the files to send to Danielle. The new scope of this ticket is now complete.
