### ISSUE TITLE
Analytics Reporting Request for Patrick & Caseflow team

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#3871]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [ ] ~Additional Comments~

## Description
The Caseflow team is interested in how many veterans are checking their appeals status on VA.gov, a transaction that has a dependency on the Caseflow API.

Please send results to @patrick (Bateman) on Slack.
    
## Timeframe for Analytics Requested
No rush.

## Analytics to Track Down
- [x] Number of time a user clicks on `View claim or appeal status` on the homepage
- [ ] Number of times a user clicks on a specific appeal to get status info
- [ ] Number of calls from `vets-api` to the Caseflow API

## Which Product Questions are you trying to answer?

To what extent is VA.gov dependent on the Caseflow API?

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
Shifting this to In Progress - Creating custom report to pull users checking claims

**Comment by nedierecel** [comment]
@jonwehausen For your awareness (in case you ever need to run yourself), I created a custom report in [Disability & Claims>Custom Reports to pull users by Custom Dimension 8 (Track Claims)](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/DbqwabtzQ269gLzdNb0R4A/a50123418w177519031p184341898/)

For the last 30 days, there are 400,372 users tracking claims.

**Comment by nedierecel** [comment]
@batemapf - Please see the follow-up to your questions. 

**Timeframe: 11/20/2019-12/21/2019**

1. [Clicks to Tracking Claims from Homepage - 690K Total Events (See Total Events in the Link)](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Navigation%20-%20Zone%20One%20-%20-%3E~2Fclaim-or-appeal-status)

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/52f51af3-a525-4160-8721-66c2f562ece0)

2. [Clicks to Tracking Claims from Main Navigation Menu - 29K Total Events](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Navigation%20-%20Header%20-%20Check%20your%20claim%20or%20appeal%20status%20-%20https:~2F~2Fwww.va.gov~2Fclaim-or-appeal-status)

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/d91e6db2-3c74-49ff-90c1-4fa81d63e7d4)

3. [Clicks to Individual Claim Details -  1.5MM Total Pageviews](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20191120&_u.date01=20191221&_r.drilldown=analytics.eventCategory:Transactions,analytics.eventAction:Claims%20-%20View%20Details&explorer-table.plotKeys=%5B%5D/) 

I'll check with the Ops team on the Caseflow-API calls.

**Comment by nedierecel** [comment]
Hi @wyattwalter - Within Prometheus, can we retrieve the total API calls to the Caseflow API? Patrick is interested in reporting this to the Caseflow team.

**Comment by nedierecel** [comment]
1/16/2020 Progress - Reactivated public key via GH to try to get Grafana access and set up proxy; Reached out to Nathan via Slack for help since I'm still having issues

**Comment by nedierecel** [comment]
Time scheduled with TJ on 1/23 to unblock Grafana access.

**Comment by nedierecel** [comment]
We regrouped with TJ and were provided a snapshot of performance in the last 7 days:

- Requests: 4600
- Errors: 46
- Uptime: 98.82%

Screenshot also available:
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/e1e8eba2-0207-4cdf-a564-e6ed2f8ecbb4)

**Comment by nedierecel** [comment]
Hello @KevinMHoffmanUSDS - Patrick had requested this information previously for Caseflow API usage. Would you like me to share this with any other stakeholders?

**Comment by KevinMHoffmanUSDS** [comment]
Thanks, @nedierecel! This wasn't something he put on my radar to follow up on, to the best of my memory. I'd say let's share it with the Caseflow team for sure. I'll forward this their way.

**Comment by joanneesteban** [comment]
Thanks! Closing this issue.
