### ISSUE TITLE
Redirect Request for Vet Centers: FL detail pages, legacy directory and key staff live as of 3/25

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38716]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

As the new Vet Center pages are rolled out, the legacy details pages for Facility Locator, Directory location pages and key staff pages need to direct Veterans to the new web presence. These requests will be made in bulk for the locations which have gone live in the previous two weeks.

Note: Outstations have their own Directory location and key staff pages but will be part of the new respective main Vet Center's Location page. Mobile Vet Centers do not have their own Directory location pages and are suppressed from the Facility Locator.

### Implementation date
No specific date - at your earliest convenience

### Redirects 
Current URL  |  Redirect Destination or New URL
--- | ---
www.va.gov/find-locations/facility/vc_0207V | https://www.va.gov/chesapeake-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=403&dnum=All | https://www.va.gov/chesapeake-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=403 | https://www.va.gov/chesapeake-vet-center/
https://www.va.gov/find-locations/facility/vc_5381OS | https://www.va.gov/great-falls-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=5466&dnum=1 | https://www.va.gov/farmington-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=5466 | https://www.va.gov/farmington-vet-center/
https://www.va.gov/find-locations/facility/vc_0621V | https://www.va.gov/western-oahu-vet-center/
www.va.gov/find-locations/facility/vc_0126V | https://www.va.gov/worcester-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=635&dnum=All | https://www.va.gov/worcester-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=635 | https://www.va.gov/worcester-vet-center/
www.va.gov/find-locations/facility/vc_0317V | https://www.va.gov/charlotte-vet-center/  
www.va.gov/find-locations/facility/vc_0705V | https://www.va.gov/corpus-christi-vet-center/ 
www.va.gov/find-locations/facility/vc_0532V | https://www.va.gov/provo-vet-center/ 
www.va.gov/find-locations/facility/vc_0808MVC | https://www.va.gov/richmond-vet-center/
www.va.gov/find-locations/facility/vc_0217V | https://www.va.gov/richmond-vet-center/
www.va.gov/find-locations/facility/vc_0212V | https://www.va.gov/williamsport-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=485&dnum=All | https://www.va.gov/charlotte-vet-center/  
https://www.va.gov/directory/guide/facility.asp?ID=5460&dnum=1 | https://www.va.gov/corpus-christi-vet-center/ 
https://www.va.gov/directory/guide/facility.asp?ID=581&dnum=1 | https://www.va.gov/provo-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=404&dnum=All | https://www.va.gov/richmond-vet-center/  
https://www.va.gov/directory/guide/facility.asp?ID=5441&dnum=All | https://www.va.gov/williamsport-vet-center/  
https://www.va.gov/directory/guide/keystaff.cfm?id=485 | https://www.va.gov/charlotte-vet-center/  
https://www.va.gov/directory/guide/keystaff.cfm?id=5460 | https://www.va.gov/corpus-christi-vet-center/  
https://www.va.gov/directory/guide/keystaff.cfm?id=581 | https://www.va.gov/provo-vet-center/ 
https://www.va.gov/directory/guide/keystaff.cfm?id=404 | https://www.va.gov/richmond-vet-center/ 
https://www.va.gov/directory/guide/keystaff.cfm?id=5441 | https://www.va.gov/williamsport-vet-center/ 
https://www.va.gov/find-locations/facility/vc_0858MVC | https://www.va.gov/baltimore-vet-center/
https://www.va.gov/find-locations/facility/vc_0201V | https://www.va.gov/baltimore-vet-center/
https://www.va.gov/directory/guide/facility.asp?ID=497&dnum=All | https://www.va.gov/baltimore-vet-center/
https://www.va.gov/directory/guide/keystaff.cfm?id=497 | https://www.va.gov/baltimore-vet-center/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@longmd @LindaLi123 This redirect is ready for implementation.
