### ISSUE TITLE
Product Guide Update- demographics confirmation change

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#38722]
This ticket needs more details filled in- related to https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38721 

We had a last minute stakeholder request to change demographics confirmation duration from 3 days to 7 days. The code fix is anticipated on 3/18- product guides will need to be updated after this goes live because they currently specify 3 days.

**Comment by loripusey** [comment]
I think that we need to change the verbiage to state that the time frame is configurable by the facility

**Comment by loripusey** [comment]
@kristenmcconnell Do we know if the product guides actually specify 3 days? I checked and couldn't find where it mentioned 3 days. 
cc: @sarahknoppA6

**Comment by kristenmcconnell** [comment]
The day of check-in guide did. It is in a couple of places, such as the bottom of page 6.

Ben already updated it and posted the changes to GitHub, so this ticket is actually complete.

You mentioned "I think that we need to change the verbiage to state that the time frame is configurable by the facility." From what I know it isn't configurable by facility. It is currently a global change.

**Comment by benbrasso-agile6** [comment]
Pages 4, 6, 8 and 9 are where timing is specified in the day-of guide.

**Comment by loripusey** [comment]
@benbrasso-agile6 can you please close this ticket if it is complete?
cc: @sarahknoppA6
