### ISSUE TITLE
Accessibility Feedback - Design Intent - VA Notify Forms Strike Team - In Progress Reminders

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#38729]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- HTML emails are notoriously difficult to make accessible, mostly because of the limitations of what HTML and CSS email clients will render. So this is a heads up to expect some more technical notes at the Midpoint Review!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- **Plaintext version.** Some assistive technology users prefer to use a plaintext email client. Make sure you're thinking about a plaintext version of your message as you move forward with the HTML message. The plaintext message may require slightly different copy or structure of content in order to make sense.
- **Unique link text.** If/when you're providing cards for multiple in-progress forms, the "Continue Application" links need to have unique text. Screen reader users often navigate through content by pulling up a list of the links on the page, and multiple links with the same text aren't particularly useful. On a typical webpage, we would use an `aria-label` or `sr-only` text to provide a unique accessible name, but neither of those techniques are fully supported in HTML emails. Instead, you will need to make the link text fully descriptive and unique, eg. "Continue your application for dependent status."

**Should:**

**Consider:**
- **Link to My VA at the beginning of the message.** Since HTML emails can be difficult to for some AT users, you sometimes see email marketing messages with a "View this message on the web" link at the very top of the message, above all of the branding and content. Users can then open the message in a browser tab where it may be easier to navigate the content. This isn't a marketing message so doesn't make sense to point to a public webpage with the same content. But consider doing something similar by linking to My VA above the blue VA branding. The line of text already in the message body now ("To view and complete unfinished applications...") would actually be a good fit for this.

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by ElissaFolk** [comment]
In order to address the "Must" Feedback, we created a plaintext version of the email.
![or Remove Dependents) Copy 2](https://user-images.githubusercontent.com/87875579/159990046-66165c5d-96d3-4a5a-b4c0-c277b165fb2d.png)

**Comment by ElissaFolk** [comment]
In order to address the "Must" Feedback, we opted to eliminate all action links and styles and make the application name the link
![or Remove Dependents) Copy](https://user-images.githubusercontent.com/87875579/159990467-ed4c5f5f-4549-45c3-a76c-065f04811027.png)
![or Remove Dependents)](https://user-images.githubusercontent.com/87875579/159990471-b0e410c1-b964-4433-9178-d816dbc4655d.png)

**Comment by ElissaFolk** [comment]
We did not put a link to the MyVA page at the beginning of the message because of the page the user would land on is in flux at the moment.

**Comment by briandeconinck** [comment]
@ElissaFolk this all looks great! Thank you!
