### ISSUE TITLE
Quality Assurance Feedback - Midpoint Review - 1010 EZ | Short Form

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#38737]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Even if your project requires minimal verification of functionality, it is prudent to develop a test plan that ensures quality is baked into your product. You have user stories which are a great way to call your shots. Now, you need to develop a test plan that verifies your user stories have been developed to satisfy functional requirements and business needs.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- We recommend using TestRail for tracking manual testing of your feature.  You can use TestRail's `reference` field to link directly to tickets stored in GitHub. By default TestRail references `va.gov-team` repo issues. If you create `va.gov-team` tickets for your user stories then you can march them through the project management workflow of GitHub/ZenHub AND you can provide excellent reference material for the test cases that verify the stories are completed to satisfaction.
- Read through [Getting Started with TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/Getting-Started-with-TestRail.1600716881.html)

**Consider:**
None

**Comment by SKasimow** [comment]
hi @tlei123 - do we have a test rail link I can include in here? If not, can you just send when available? thanks!

**Comment by tlei123** [comment]
@SKasimow , I should have something for you in TestRail next Mon/Tue.

**Comment by tlei123** [comment]
@SKasimow , below are links to TestRail plan and cases (WIP).  Sorry for the delay!

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3094)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_id=4151&group_order=asc&display_deleted_cases=0)

cc @ddzz

**Comment by SKasimow** [comment]
Hi @tlei123 closing this ticket as it is a dupe to the one I opened: [here](https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/38104)
