### ISSUE TITLE
[Analytics] Adding performance information to the My VA GA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#38739]
# Analytics Feature Request/Bug Report

## Ticket Description

Who is this request for? What is your role, and which team/project is this work for? 

This request is for the authenticated experience team, specifically for our My VA dashboard, for which we have a [current Google Analytics dashboard](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/).

- Is this a feature request or a bug?

  - [X] Feature request
  - [ ] Bug report

## Request/Report Description

I am looking to understand how performant the My VA dashboard is. Given that each section of the dashboard is supported by a different backend, this needs to be done section by section.

Specifically, I am looking to understand how often we successfully load people's information, and how often these endpoints fail. [We already show this on the My VA Ga dashboard for the claims endpoint](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/), and I am hoping we can either add tracking or level-up existing tracking for the following:

- Next appointment
  - Successful retrievals of this information
  - Failed retrievals
- Disability rating 
  - Successful retrievals of this information
  - Failed retrievals

If we already have this tracked in GA and it simply needs to be added to the existing GA dashboard, let me know. If we can not add it to the existing GA dashboard because their are already too many widgets, let me know that, too. I might want to create a separate dashboard for performance only.

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
cc/ @hdjustice

**Comment by Samara-Strauss** [comment]
Great, thank you for explaining all of this, @jennaouellet!

@hdjustice -- can you add a task for Taylor for sprint 70 to add success/fail tracking to the following for My VA:

- Disability rating
- Next appointment
- Most recent payment

**Comment by hdjustice** [comment]
@Samara-Strauss - #38858 created and scheduled.  Thank you so much @jennaouellet for that great information!

**Comment by hdjustice** [comment]
Hi @jennaouellet - Taylor has implemented the API success/fail tracking in the Staging environment.  Would you be able to see if you can locate them there? Or would you be looking in Production only?

cc: @Samara-Strauss @tmitchellgcio

**Comment by Samara-Strauss** [comment]
@jennaouellet you can use User 36 for the success state. Unfortunately, we can't test the failed state in staging unless it happens naturally. There's not a way for us to force this, except maybe locally.

**Comment by jennaouellet** [comment]
@Samara-Strauss got it, thanks! Do you happen to have the event code that has been implemented? I'm having a hard time seeing the event firing or locating it in GA reporting.

**Comment by Samara-Strauss** [comment]
No, I am not sure what the even code is. Can you please work directly with @tmitchellgcio on this? He is our frontend dev and hasn't worked much with implementing analytics, so there might be issues he needs help with working out.

**Comment by Samara-Strauss** [comment]
Pulling in @ajakabcin for awareness since Heather has moved to the 10-10 team.

**Comment by tmitchellgcio** [comment]
@jennaouellet I am using this

```
recordEvent({
        event: `view-payment-history-failed`,
        'error-key': `${error.status}_server_error`,
        'api-name': 'GET payment history',
        'api-status': 'failed',
      });
```

and this

```
recordEvent({
      event: `view-payment-history-successful`,
      'api-name': 'GET payment history',
      'api-status': 'successful',
    });
```

I am assuming the event code is the `view-payment-history-successful`

**Comment by jennaouellet** [comment]
Hi @tmitchellgcio! The event name should actually be api_call

#### API Success

> {
> event: 'api_call',
> api-name: 'Get Payment History',
> api-status: 'successful'
> }

#### API Failure

> {
> event: 'api_call',
> api-name: 'Get Payment History',
> api-status: 'failed',
> 'error-key': '500 timeout message'
> }

The api-name parameter should be the name of the API, but the event parameter itself should be set as above. 

Please let me know once it's been updated and I will re-test. Thank you!

**Comment by tmitchellgcio** [comment]
Oh weird. Ok I will get that fixed in the morning

**Comment by tmitchellgcio** [comment]
This is corrected and should be good to validate. I meant to update this ticket last week sorry for the delay

**Comment by Samara-Strauss** [comment]
Just to clarify -- did your updates include adding this tracking for the Next Appointment block and Disability rating @tmitchellgcio?

**Comment by jennaouellet** [comment]
@tmitchellgcio @Samara-Strauss The events are coming in correctly now, below are the ones that triggered on My VA when I loaded the for vet user 23. 


UA-50123418-17 
Category: API Calls 
Action: API Request - GET payment history - successful 
Label: api_call

UA-50123418-17 
Category: API Calls 
Action: API Request - GET debts - failed 
Label: api_call

I used user 36 for the appointment and disability rating:

UA-50123418-17 
Category: API Calls 
Action: API Request - GET appointments - successful 
Label: api_call

UA-50123418-17 
Category: API Calls 
Action: API Request - GET disability rating - successful 
Label: api_call

The disability rating did fire twice, but if the API is called twice/that is intentional then everything looks good to me!


Once it is in production, please let me know and I can help with the dashboard as well. Thanks!

**Comment by Samara-Strauss** [comment]
Thank you @jennaouellet! Once these are in prod, can you help me add these to the table entitled ["Successful and failed GETs" on this dashboard](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/)?

**Comment by Samara-Strauss** [comment]
Sorry we lost sight of this, @jennaouellet. Have these updates been pushed to production?

cc/ @ajakabcin @ericasauv09 for awareness that we had performance analytics added for the different items we show on My VA and want to add them to our [analytics dashboard for My VA](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/).

**Comment by jennaouellet** [comment]
@Samara-Strauss The dashboard has been updated with the new API calls. Let me know if there's anything else we can help with. Thank you!

**Comment by Samara-Strauss** [comment]
@jennaouellet THANK YOU! This is super helpful!!
