### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by Bernardo994** [department-of-veterans-affairs/va.gov-team#38742]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
  [ x] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access: 

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
[x] Provide access to user
[] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Access granted.

**Comment by Bernardo994** [comment]
Thanks so much for getting me access.  How does one use Google Analytics though? Is there some training on how to use this tool?



From: Brian Martin ***@***.***>
Sent: Friday, March 18, 2022 1:58 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Szymczak, Bernardo J. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #38742)


Access granted.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F38742%23issuecomment-1072657370&data=04%7C01%7C%7C04504ce6ac5f43097a6108da0908ee31%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637832231198510781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SvMAs76GIhTSS8NDoxoZY0HnmpORfEqNJRksSZm8wKQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYJKKN7XOLBYTF3JRVONVCTVAS74HANCNFSM5RCHTX2A&data=04%7C01%7C%7C04504ce6ac5f43097a6108da0908ee31%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637832231198510781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sJm1yqrEMKJuLXbMR8Miv5%2BdtJD1cSnKWdPFubMS9bg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C04504ce6ac5f43097a6108da0908ee31%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637832231198510781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b01gaF7%2F%2Bqutj6nolvaoQdWmJsC9IFnb6MZ58OgcLk4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C04504ce6ac5f43097a6108da0908ee31%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637832231198510781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JpuefP5yvY2wiVwTQ625ofN5joUx7D%2Bo5KcGJ8lEpQs%3D&reserved=0>.

**Comment by bsmartin-ep** [comment]
@Bernardo994 -

Here is an introduction to the  VA's GA properties...
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/New-Users-to-Google-Analytics.1877704964.html

And a (very) basic intro to GA itself....
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics.1877999672.html

Some frequently asked questions...
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Frequently-Asked-Questions.1783333118.html

We can answer specific support questions in the #vfs-platform-support channel on the DSVA slack and we also host twice-weekly open office hours for questions.

We also like to recommend some of Google's training resources, like their beginner courses...
https://analytics.google.com/analytics/academy/course/6

Let me know if you have any questions.

**Comment by Bernardo994** [comment]
Are we able to create custom views? I am trying to figure out how to get metrics on a very specific page?  Thanks

From: Brian Martin ***@***.***>
Sent: Monday, March 21, 2022 9:56 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Szymczak, Bernardo J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #38742)


@Bernardo994<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBernardo994&data=04%7C01%7C%7C968b6938d301424f538f08da0b428d0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637834677725241015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L8a3viZnwV4jifCMU04iITKZf4Do8UJo7TLSiYgXQus%3D&reserved=0> -

Here is an introduction to the VA's GA properties...
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/New-Users-to-Google-Analytics.1877704964.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdepo-platform-documentation.scrollhelp.site%2Fanalytics-monitoring%2FNew-Users-to-Google-Analytics.1877704964.html&data=04%7C01%7C%7C968b6938d301424f538f08da0b428d0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637834677725241015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zYT%2B7Tsxf0bhOnRvEZzXFtPlVTS%2FWvEyZSc0b7KcydM%3D&reserved=0>

And a (very) basic intro to GA itself....
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics.1877999672.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdepo-platform-documentation.scrollhelp.site%2Fanalytics-monitoring%2FGoogle-Analytics.1877999672.html&data=04%7C01%7C%7C968b6938d301424f538f08da0b428d0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637834677725241015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5w4PRj03SjFJnyVWmPafIDOyDEp1tGS6wR5Tt4E7aqA%3D&reserved=0>

Some frequently asked questions...
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Frequently-Asked-Questions.1783333118.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdepo-platform-documentation.scrollhelp.site%2Fanalytics-monitoring%2FFrequently-Asked-Questions.1783333118.html&data=04%7C01%7C%7C968b6938d301424f538f08da0b428d0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637834677725241015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sQyYw3r1gh4XWx5Tzn%2BEGr81A2b5e1kxOdJN03HLVWA%3D&reserved=0>

We can answer specific support questions in the #vfs-platform-support channel on the DSVA slack and we also host twice-weekly open office hours for questions.

We also like to recommend some of Google's training resources, like their beginner courses...
https://analytics.google.com/analytics/academy/course/6<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fanalytics.google.com%2Fanalytics%2Facademy%2Fcourse%2F6&data=04%7C01%7C%7C968b6938d301424f538f08da0b428d0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637834677725241015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RTyEPsXxeGb0%2BIJzBwfC%2Fi4Dzjitov7tODj5bQJDkoI%3D&reserved=0>

Let me know if you have any questions.

-
