### ISSUE TITLE
IA Feedback - Design Intent - In Progress Reminders

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#38748]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
Simple interactions aren't easy! Up-front discovery research and detailed user journey mapping increase your chances of getting things right. 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**
Revise existing user flow into separate, [flowchart-format swim lane diagram](https://bigbangip.com/swim-lanes-guides-user-experience-design/) featuring

- Brief scenario that defines: 
  - user persona, 
  - their desired outcome 
  - and context of use.

**Swim lanes** that map the interplay between:

1. User actions, including the ones that get them to the site to begin with
2. System interactions and database back-end, including the data that user is passing to and getting back from the system
3. UI and content messaging on system front end
4. User's experience quality at each step. Represent this as a fever chart

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by hubgitian** [comment]
We've added a scenario that includes user persona, their desired outcome, and context of use as well as swimlanes that differentiate between the site and email channels.

We attempted to add a fever chart but ultimately deleted the effort as we didn't have a gauge of the user's experience.

[Application reminders user flow.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8366172/Application.reminders.user.flow.pdf)

**Comment by jimuhh** [comment]
Thanks @hubgitian! Hope it helped you understand the process in more depth!
