### ISSUE TITLE
Create downtime window for CARMA last minute SF db maint

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#38758]
Sat, tmrw, 11-11:30 pm Eastern.

**Comment by RudyOnRails** [comment]
cc @SKasimow - new ticket

**Comment by RudyOnRails** [comment]
PagerDuty maint. window requested from Platform: https://dsva.slack.com/archives/CBU0KDSB1/p1647627057300459

**Comment by SKasimow** [comment]
thanks - sprint 69 I assume?

**Comment by RudyOnRails** [comment]
Yup! `Sprint: Mar 9 - Mar 22, 2022`

**Comment by RudyOnRails** [comment]
Platform created the window in PagerDuty:
![Screen Shot 2022-03-18 at 1 30 24 PM](https://user-images.githubusercontent.com/1021154/159095635-bbab114c-b362-4c30-b992-4922be7020af.png)
