### ISSUE TITLE
Design Feedback - Midpoint Review - 1010 EZ - Short Form

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#38761]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Would love to see some mobile designs

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- [Start healthcare application button](https://d.pr/i/bkcKRn) should be a [green action link](https://design.va.gov/experimental-design/action_links)
- Add [“i” icon ](https://d.pr/i/butZrN)and heading to [info alert](https://design.va.gov/components/alertboxes#informational-alert)
- Update [subtitle form name](https://d.pr/i/Zf5fZs) to “Form 10-10EZ”. Font should be assigned class [schemaform-subtitle](https://d.pr/i/9v1AHN)
- The line height of the font in the [personal information block](https://d.pr/i/O30xEU) is too large. Refer to the [current experience](https://d.pr/i/0X9UOe) for guidance.
- Add [“Finish this application later” link](https://d.pr/i/eLtIwZ) above the back and continue buttons on all pages.
- Add [“i” icon](https://d.pr/i/aKhr8u) and heading to [info alert](https://design.va.gov/components/alertboxes#informational-alert) 
- Update the [“You can fill out a…” success alert box](https://d.pr/i/rHhN23) to an [info alert box](https://design.va.gov/components/alertboxes#informational-alert). 

**Should:**
- [Statement of intent font](https://d.pr/i/5SFE2Q) should be assigned class [va-introtext](https://d.pr/i/6P9fbo)
- The [personal information](https://d.pr/i/9Or3fv) overview page should remain the first step and include the [step indicators and title](https://d.pr/i/Ow2S7w). 
- Remove [“Enrollment Application for Health Benefits (VA Form 10-10EZ)”](https://d.pr/i/n7HWGk) and add “Form 10-10EZ” to the right of the H1 (same formatting as [other pages in the steps](https://d.pr/i/NugJE0))
- The [“You can fill out a…” success alert box](https://d.pr/i/rHhN23) doesn’t need its own page. On the [introduction page](https://d.pr/i/jCv0qx), replace the [“Note: Since you're signed in to…” info alert box](https://d.pr/i/jCv0qx) with the “You can fill out a…” info alert box. Only replace for authenticated users.
- Remove the [expandable alerts](https://d.pr/i/exmVLn) on all of the pages. The alerts are redundant and unable to be dismissed.
- Disability confirmation page (see below)
  - Move [contextual help](https://d.pr/i/RFEtZU) additional info component into info alert
  - The “Back” and “Continue” buttons should be consistent in location and language to the user while they are filling out the application. Remove them from the info alert box and place them at the [bottom of the application page](https://d.pr/i/3dKsjY). Update “Confirm” button language to “Continue”.
  - Add a [checkbox](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default#with-description-string) with a descriptive string [underneath the info alert component](https://d.pr/i/2DMSB3) asking to confirm that the user is receiving service-connected pay for a 50% or higher disability rating. The question could be more direct like “Please confirm that you receive VA disability compensation” and the checkbox underneath could read “Yes, I confirm that I receive service-connected disability pay for a 50% or higher disability rating” (work with content on this).
  - A [proposed design solution](https://d.pr/i/tQBvUz) for all of the above

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by Dene-human** [comment]
Hey @allison0034 @seanasewell Thanks for the discussion this morning! I worked on the treatments for these two feedbacks based on what we talked about. Please let me know your thoughts



> Add [“i” icon](https://d.pr/i/aKhr8u) and heading to [info alert](https://design.va.gov/components/alertboxes#informational-alert)


We discussed turning this into [featured content](https://design.va.gov/patterns/content-presentation). Here is a [mockup](https://github.com/department-of-veterans-affairs/va.gov-team/files/8318194/Confirmation.screen.as.a.featured.content.pdf)


<br>


> Update the [“You can fill out a…” success alert box](https://d.pr/i/rHhN23) to an [info alert box](https://design.va.gov/components/alertboxes#informational-alert).


Please let me know what you think about these two different informational [alert mockups](https://github.com/department-of-veterans-affairs/va.gov-team/files/8318199/Athenticated-prequal-upon.auth-as.info.pdf)


I'll share my research plan (once complete) to try out the bigger design changes.

**Comment by seanasewell** [comment]
@Dene-human The mockup of the confirmation page using the featured content box looks good. The informational alert box with the title is probably the best option of the two but either one will work! Thanks for working on these. Excited to see what it looks like at staging!

**Comment by Dene-human** [comment]
Thanks so much @seanasewell appreciate you and @allison0034 noodling with me!

**Comment by hdjustice** [comment]
Closing ticket, all feedback was addressed, and Short Form feature was launched 9/2022
