### ISSUE TITLE
FE update 10-10EZ button to action link for authenticated 

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#38763]
## Background
When a Veteran is logged into VA.gov and on the [Introduction page](https://staging.va.gov/health-care/apply/application/introduction), the current button style to start the application is not the most up-to-date advisement from the Design System.  We should be using a Primary Action Link.

See Screenshots below:

[Primary action link](https://design.va.gov/components/link/action) on both places on this page.

>![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/85bbb80a-a0fa-4cf2-a5df-d4daf4a042e4)

Current Button
>![image](https://user-images.githubusercontent.com/92328831/177632680-0b02a860-03e0-4dba-bed7-fa7d3cb0d1cd.png)

## Tasks
- [ ] Update the Introduction page for authenticated users to reflect the Primary Action Link to start the application

## Acceptance Criteria
- The current green button on the authenticated introduction page will be replaced with the Action link.

**Comment by hdjustice** [comment]
updated screenshots

**Comment by longmd** [comment]
@hdjustice , this button is coming from the form system and is not something we can change. It is part of a component from them related to the save in progress feature. The forms team would need to be the one to make the change to this component.
