### ISSUE TITLE
GA follow up for reporting of direct deposit save errors

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3877]
Here are the follow-ups from Nedie on our last call on 12/2/19:

1. Unsampled data is available to download should we run into this again within the interface. I'll reach out to GA Support since it was unusual that we ran into that error.
2. Erik, we'll sync up again on how Sentry increments errors (e.g. if they happen within a certain timeframe, how does it measure errors?)
3. I'll add Form Saves to the Personalization dashboard.

### Check on below
- [x] Follow up with Nedie to see if GA support offered any info on the interface issues. 
- [x] Check if "add form saves" to the Personalization board have been added.

**Comment by Samara-Strauss** [comment]
This is on Sprint 10 objectives but not assigned to anyone — can we get this triaged accordingly?

**Comment by Justin-Pickett** [comment]
Sorry, I thought I tagged Nedie and Erik originally. I have corrected it now.

**Comment by erikphansen** [comment]
2. Sentry is not doing any filtering of errors, so it's still a bit of a mystery why GA is showing significantly more errors than Sentry. If GA was always showing duplicates (ie if total events was always exactly twice as many as unique events) that might indicate an obvious bug in the FE code where an event was logged twice when it should be logged once, but that's also not the case. So no real progress as far as to why there's a discrepancy between GA and Sentry errors.

**Comment by nedierecel** [comment]
1. Further clarity on using the Dashboard or other detailed reports - Google support cautions against using the current day as your end-date (e.g. today is 12/11, and you use the timeframe 10/31-12/11). The premium version of Google Analytics still has a processing latency, so same-day data within reporting can be sampled. Please use the prior day.
2. I don't have any further reasoning on the discrepancy. 
3. @erikphansen In looking again at Profile Saves, I believe we are only sending a very broadly named `Profile Saved` event after **any** Profile form saves. The impact to adding it to the Google Analytics Dashboard is it would include Profile Saves for other user interactions.

**Comment by Justin-Pickett** [comment]
@erikphansen will verify point #3 above and then we can consider closing this ticket.

**Comment by erikphansen** [comment]
@nedierecel when the Direct Deposit save/update succeeds we send this data to GA:

```
{
  event: 'profile-transaction',
  'profile-section': 'direct-deposit-information',
}
```

As far as I can tell we only send this specific data to GA when DD info has been saved. There are lots of places where we send GA data with `event: 'profile-transaction'` but with different values for `profile-section`

**Comment by Justin-Pickett** [comment]
@nedierecel and @erikphansen can we close this ticket?

**Comment by nedierecel** [comment]
@erikphansen Thanks - if this is only sent with successful submissions:

`{
  event: 'profile-transaction',
  'profile-section': 'direct-deposit-information',
}`

Then this section of the dashboard covers saved submissions:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/20780587-f872-442f-b66c-ac52b07b4beb)

**Comment by Justin-Pickett** [comment]
@erikphansen and @nedierecel just confirming with you two, I believe this ticket can be closed? The AC was met for this ticket.

**Comment by nedierecel** [comment]
This is correct. Thanks @Justin-Pickett

**Comment by Justin-Pickett** [comment]
@nedierecel  Thank you. Closing this ticket out.
