### ISSUE TITLE
Collab Cycle Kickoff [CMS Offices team, Home Page iteration on subdomain]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#38774]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- [Product outline for VA unauthenticated home page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page
- Wireframes, mockups, or prototypes – see [Sketch file](https://sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857), screen called "VA-home-step-3a"
- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [ ] Yes
- [x] No – **not in production, we're planning on deploying to a subdomain**

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [x] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: VA.gov unauthenticated home page

### 4. Are you making changes to the visual design?
- [x] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [x] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [x] Changes to existing content

### 8. Are you making a change to the user flow?
- [ ] Yes
- [x] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [ ] Yes
- [ ] No
- [x] Not sure, **I couldn't find a dash for the Home Page, found this surprising**

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [x] Yes – GA setup for our modified Home Page on a subdomain of VA.gov (subdomain TBD)
- [ ] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [ ] No. 
- [x] Yes. Please specify: `homepage`

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [x] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by wesrowe** [comment]
@shiragoodman, Sorry that was ambiguous. No, if and when this reaches prod it would definitely constitute a change. We are expecting be on a subdomain for a while, though. Cc: @davidconlon

**Comment by shiragoodman** [comment]
ah ok. Thanks, Wes. That question is the first decision point in our flow... if you answer no (no visual change), then you essentially bypass the majority of the Collaboration Cycle touchpoints and the only required touchpoint is the Privacy, Security and Infrastructure Readiness Review. This is mostly for backend changes. If you answer yes (yes visible changes), then you'll likely be recommended more of the Collaboration Cycle touchpoints like Design Intent, Staging Review, etc. Visible changes are what we evaluate in the [VA.gov Experience Standards. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

To me it sounds like YES, visible changes. If you disagree let me know. I will follow up in the morning with the recommended Collab Cycle touchpoints based off a YES response.

**Comment by davidconlon** [comment]
@shiragoodman Yes visual changes. A fair amount of them.
For context: The intent is to build an "alternate" version of the homepage as experimental so that we can evaluate it heavily with users, screen readers, stakeholders etc. Lots of usability testing and evaluation of the design.
Along the lines of the historical use back in 2018 of "preview.va.gov" as we were exploring and experimenting with the homepage at the Vets.gov prior to final dev and cutover.

**Comment by wesrowe** [comment]
Thanks, @shiragoodman, I'll schedule the Design Intent soon.
