### ISSUE TITLE
[BE] Add vcr recordings for mulesoft

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#38771]
mulesoft client does not have any real tests, everything is stubbed

**Comment by RudyOnRails** [comment]
I started to here: https://github.com/department-of-veterans-affairs/vets-api/blob/85d2cbcf6ed2309edad780b9b558bd90c3d2b397/spec/jobs/form1010cg/deliver_attachments_job_spec.rb#L388

Main ticket is: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37820
