### ISSUE TITLE
Medallia 508 Issue Resolution

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#38781]
## Product Outline
[Medallia User Surveys](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product+Outline)

## High Level User Story/ies
As a VA.gov user with accessibility challenges, I need all user surveys to be accessible, so I can leave feedback for the VA.

## Hypothesis or Bet
**If** _we make user surveys fully accessible_ **then** _all users can leave feedback for VA, which will help us improve our service to Veterans_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jwoodman5** [comment]
Sprint 74:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6377 (not part of original set but should be prioritized)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26567
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26580
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26577

Need some additional research but may be fixed in upcoming sprints:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26580
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26575

Need to be addressed by Medallia tech team (not us):
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26581
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26579
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26577
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26568
lmk if you have any questions. I’m happy to hop on a quick zoom to talk through.
Also from the Medallia convo the other day, I created a ticket to add the button to the remaining drupal pages for sometime later in the near future:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38735

**Comment by joshkimux** [comment]
@jwoodman5 @aubreyarcangel hi y'all, has there been any movement on Medallia's end regarding these issues? @artsymartha68 for awareness

**Comment by jwoodman5** [comment]
Adding @ATMiddleton. She is the PM for this team now.

**Comment by ATMiddleton** [comment]
Resolved
