### ISSUE TITLE
Add more info component to 10-10EZ compensation question

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#38805]
1. Add a "where do I find this info" component
2. Look into the possibility of people answering "i don't know" or "application in progress"

### Currently in production screenshot

![Screen Shot 2022-03-25 at 9.44.07 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d762e44a-e3c6-420f-b876-58a3a75f0faf)

**Comment by Dene-human** [comment]
Questions (for HEC team?)
- How do we handle an "I don't know" or "Waiting decision response" with ES?
- Will application processors handle an "I don't know" or "Waiting decision" response change how they handle the application? - Will they followup with the applicant?
     - If not, what is the followup note? (eg. "If you receive a disability rating within X days of applying let us know") also Do we need to give information on how to followup on disability rating application? 
- Does HEC team get notified if Veteran's disability rating status changes? (this might affect priority group)

- How are people notified of compensation? (if by letter- what is letter called?)

How can people find out this information (keeping in mind some are unauthenticated and might not have login account)
-letter name?
- Call?
- online profile? where (on banner?)

**Comment by Dene-human** [comment]
@hdjustice I have been hesitant to add this agenda item to our HEC meetings, but at some point we probably should bring these questions to them. Alternatively, if you have extra time @markfallows maybe you can dig into this a bit?

**Comment by markfallows** [comment]
@hdjustice, if you feel it's better to do the research instead of approaching the HEC team, then I'm happy to dig into it.  Just let me know.

**Comment by hdjustice** [comment]
@markfallows - Yeah, if there is anything we can find out on our own, I think that would be good.  We would then at least have something to present and start an intelligent conversation with the HEC team

**Comment by markfallows** [comment]
- How do we handle "I don't know" or "Waiting on a response"?
  - Follow up with HEC
- Will "I don't know" or "Waiting on a response" change how an application is handled?
  - Follow up with HEC
- What should a Veteran do if they receive a Disability Rating after applying for health benefits?
  - Follow up with HEC
- Does HEC get notified if a Veteran's Disability Rating changes after applying?
  - Follow up with HEC
- How are Veterans notified of compensation
  - Packet sent with decision; no name provided
- How can Veterans find their Disability Rating?
  - Call
    - VA Benefits Hotline: 800-827-1000
  - Profile
    - Visible just below main navigation header
  - Letter
    - Disability claim packet; no specific name given

**Comment by Dene-human** [comment]
Is this something we want to have further discussion with HEC about? For context adding this info was a request from Lauren.

**Comment by Dene-human** [comment]
Yeah I get that. I'd like to hear more of her thoughts on wanting the "i don't know " option. The part that I would really like to provide is the "how do i find my disability rating?" - which i can work on based on this with Danielle.

**Comment by Dene-human** [comment]
Thanks! Yeah I'm still trying to think through the benefit of adding more  selection options ("I don't know" and "waiting for a response"). Is it to help the Veteran get through that question without having to pause and return? or is there something that the HEC team can do with that info?

**Comment by markfallows** [comment]
Will not do at this time.  Closing ticket.
