### ISSUE TITLE
Engineering: Approach for how MHV will move to va.gov (URLs)

### ISSUE THREAD

**Issue by TraceyMulrooneyUSDS** [department-of-veterans-affairs/va.gov-team#38818]

**Comment by batemapf** [comment]
@MarciMcGuire does this still belong in `Current Sprint`? Not totally clear on the work under consideration here. Are we talking about URL redirects? Or URL construction as determined by VA.gov IA?

**Comment by MarciMcGuire** [comment]
@batemapf I'm afraid this issue precedes me, and I'm not sure of the original intent.  I suspect it's what the new URLs will be, and requesting redirects within VA.gov for links that currently point to MyHealtheVet.
