### ISSUE TITLE
[FSR] - Form Able to Save With Validation Errors

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#38834]
## What happened?
Forms can save with validation errors in fields. Experienced in FSR employment history when inputting invalid dates. 

## Desired behavior
Update save logic in `RoutedSaveableApp` to handle preventing saving of invalid data.

## Acceptance Criteria
- [ ] Saving invalid data prevented

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
1/10/2023 - Leaving this open to validate NaNs aren't coming through any longer

**Comment by OptionSelect** [comment]
Per convo with Andrew closing this one out. It's more of a placeholder for work that's been done at this point and if we do encounter other NaN's we should have a specific ticket for handling them. Validation is being added to the form in a lot of places thanks to EFSR.
