### ISSUE TITLE
[Research] Add Appointment Notification Questions to Staff Conversation Guide once VAOS is Complete

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38840]
## User Story
As a product team, we want to add the appointment notification questions to the staff conversation guide once VAOS is complete.

## Related Documentation
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/37949

## Tasks
- [x] Update the conversation guide

**Comment by kristenmcconnell** [comment]
I talked to Peter Russo. Here is [the conversation guide](https://docs.google.com/document/d/1DWE2QdxR_WW-GapCdYJpkbB8SoxVlOimYmgC-FDgY2Q/edit#heading=h.8scnnixlz5v1) that he has for the appointment notification study. He asked if we could help surface the following items within our study:
- Some of the tools and methods used for notifications at that facility
- Pain points around those

**Comment by kristenmcconnell** [comment]
I updated the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/conversation-guide.md) with VAOS's appointment notification questions. I will review with the UX team later today at the UX sync after planning.

I also updated the research questions and hypothesis in our [research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/research-plan.md)to cover some of the future feature exploration topics. I messaged Peter to ask if they had research questions for the appointment notification study that I could add as well.

**Comment by kristenmcconnell** [comment]
I added the research questions and hypothesis from VAOS.

**Comment by kristenmcconnell** [comment]
I incorporated team feedback into the conversation guide and research plan posted above.
