### ISSUE TITLE
Offboarding of Jeff Thompson

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#38841]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Jeff Thompson
- team name:
  > Program
- role on team:
  > Engineering Lead
- expected last day:
  > 3/1/22
- company they work for:
  > GovCIO
- email:
  > jeffrey.thompson@govcio.com
- GitHub username:
  > jt20816
- additional access they may have:
  > ex: SOCKS, Pagerduty, Google analytics, etc.
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [ ] Remove from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights , @department-of-veterans-affairs/confluence-admins

**Comment by rmtolmach** [comment]
/request Jeff Thompson

✅  deleted from VFS roster
✖️  no SOCKS or AWS
✅  removed from github org in https://github.com/department-of-veterans-affairs/github-user-requests/issues/10186
✖️  not in pd, Datadog, or Sentry
✖️  not an ops member

@department-of-veterans-affairs/confluence-admins please remove Jeffrey Thompson from Confluence

**Comment by CoryTrimmUSDS** [comment]
Removed from Slack.

**Comment by bsmartin-ep** [comment]
No GA or Domo access.

**Comment by nsmith1982** [comment]
removed from Confluence

**Comment by YanaRoy** [comment]
@rmtolmach Jeff is still receiving emails for all tickets he is tagged in when any action is taken. Can he be fully deactivated from them?

**Comment by rmtolmach** [comment]
@YanaRoy, emails from GitHub? I think that's something Jeff will have to do from his account. When we offboard someone from Github, all we do is remove them as a member of the `department-of-veterans-affairs` org. 

If the tickets are in a public repository, he can unsubscribe from each of them individually or stop watching an entire repo by choosing notification preferences in the repo:
![image](https://user-images.githubusercontent.com/10993987/159781588-493659dc-7c4f-4380-850b-0365ce8a393d.png)

Is Jeff getting emails from tickets in repositories that are private?

**Comment by YanaRoy** [comment]
@rmtolmach per Jeff: I did the downselect mentioned below, and it did not stop the emails. In fact, I turned off all notifications of all types, and they still come. I was able to access the va.gov repo in github, and I am able to see that I am still listed as a 'watcher'. I dont have access to remove myself, but if someone could go in and do that, I think it would resolve the notifications problem.

**Comment by oseasmoran73** [comment]
@YanaRoy Are these from tickets he has already been tagged for or new ones that are being created that he is getting notification? I suspect he is referring to ones he was previously tagged in. As Rebecca mentioned, he was removed from the org, so no new tickets should be coming his way.

`va.gov-team` is public repo, so he may still be on watch for those (and not just repo he was working on -- assuming its public)

Unfortunately he may need to unsubcribe to tickets (see below in screenshot). Should be located on the right side of the ticket he is being notified from.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/10648480/159981128-602c09b5-273a-4226-951a-c10bb7fcd67d.png">

**Comment by rmtolmach** [comment]
@YanaRoy That's bizarre... 
I found someone else was having similar problems: https://github.community/t/cant-stop-email-notifications/1044. Can you have him review his subscriptions. 

I am not able to remove him as a watcher. (There's this [hacky way](https://stackoverflow.com/a/56396741) that might be a last resort.)
