### ISSUE TITLE
Login.gov New User Landing Page

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#38847]
# Description
We'd like to create a page for new Login.gov users to land on when returning to VA.gov explaining the benefits of their account, and reasons to identity proof.  

# User Story
**As a** new Login.gov user
**I'd like** to know what benefits my account has, as well as benefits of a proofed account
**So that** I can make informed decisions about whether to Identity Proof

# Acceptance Criteria
- [ ] Non-verified Login.gov users who register via VA.gov are returned to page
- [ ] Page explains what they can do with their basic Login.gov account (create, submit, and save forms, etc...)
- [ ] Page explains benefits to verifying identity (view medical records, financials, etc...)
- [ ] Page directs user to process for verifying identity

**Comment by asg5704** [comment]
Closing until we have MHVIP go-live date
