### ISSUE TITLE
Content support from VSA Claims & appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38849]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

When logged in with a non-verified user (not LOA 3), our Higher-Level Review (and Notice of Disagreement) forms will not properly load prefill or form data necessary for completion of the form. In this case, we will prevent the Veteran from starting the form until they are verified (LOA 3). I copied & modified the alert shown on the `/save-form` page (in the save-in-progress component) with a link to `/verify`.

Sadly, I don't know of any LOA 1 users for you to test this with:

![HLR intro page showing the verify your identity link](https://user-images.githubusercontent.com/136959/158820352-cc2de933-3fc2-4649-859a-6587ef87fc98.png)
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: No timeline
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Claims & Appeals
-	OCTO-DE product owner: @mattpointzxer0 
-	Product manager: @vhenry07 
-	Designer: @kevinstachura   
-	FE engineer: @Mottie   
-	Product/team Slack channel: #vsa-claims-appeals

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@Mottie Do you want us to do a content review on this alert?

**Comment by lunascoop** [comment]
I don't think there's a content ticket for this so posting it here. 

@psanders you can review the revised content for this alert below.

 **Message title:** We need you to verify your identity

You’ll be able to complete this form after your identity is confirmed. This helps us keep your information safe during the application process.
[Verify your identity](Link)

**Notes:**
I think most alerts have a message title. Changed ordering of content (“you have to do this first to access the form” then the benefits (ie., safety)). 

Some lingo taken from https://design.va.gov/patterns/messaging-dictionary#engagement-messaging  (“this helps us…”)
“ be able to” seen here: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/
https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/
https://www.va.gov/health-care/family-caregiver-benefits/champva/
https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/

**Comment by psanders86** [comment]
Thanks, I'll review this today.


[cid:6abb7071-0cf5-4736-a71e-8f6e3692beee]

Patrick Sanders

Content Writer



M:  240-444-6116


About<https://governmentcio.com/about>   |   Services<https://governmentcio.com/services>   |   Careers<https://governmentcio.com/careers>

Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.­

________________________________

**Comment by Mottie** [comment]
This is what it would look like with the recommendations:

<img width="541" alt="verify identity alert" src="https://user-images.githubusercontent.com/136959/160134293-5a70f985-de53-4f2e-b963-8b924e87644d.png">

**Comment by RLHecht** [comment]
@psanders86 still need to review but we should change the first sentence to active voice: You'll be able to complete this form after we've confirmed your identity.

**Comment by psanders86** [comment]
@Mottie When someone clicks "Verify your identity" where are we sending them, please?

**Comment by psanders86** [comment]
@RLHecht 

After consulting with @lunascoop and @Mottie, I think we can make a couple minor tweaks here:

Message title: We need you to verify your identity

You’ll be able to complete this form after we confirm your identify. This helps us keep your information safe.

<link>Verify your identity

**Comment by RLHecht** [comment]
This looks good to me. @DanielleThierryUSDSVA could you do a final review of this? Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Mottie. Sorry for being slow on this one. Juggling a lot of requests!

I would reframe this for these reasons:
- Connect verifying your identity to being able to start the request in the header and link for greater clarity
- Explaining in plain language what we been by verifying your identity

Feel free to send any questions/follow-up thoughts. Thanks!

**Verify your identity to start your request**

Before we give you access to your personal information, we need to make sure that you’re you—and not someone pretending to be you. This helps us keep your information safe.

[link] Verify your identity to start your request
