### ISSUE TITLE
[FE] My VA: Add success/fail tracking to APIs

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38858]
## Background
As a result of seeing retrieval failures on My VA components, we would like to add API tracking to the data points below.
- Disability rating
- Next Appointment
- Most recent payment

Reference feedback on #38739:
>It looks like we are currently only tracking the Claims API, but the same event logic can be re-used for any other API. These events will have to manually be implemented and fired when the API succeeds or fails. From our data dictionary are our standard API events:
>
>API Success
{
event: 'api_call',
api-name: 'View Claims and Appeals',
api-status: 'successful'
api-latency-ms: 20000,
api-request-id: "55d07138-4056-405f-b361-e03ef56a386e"
}
>
>API Failure
{
event: 'api_call',
api-name: 'View Claims and Appeals',
api-status: 'failed',
'error-key': '500 timeout message'
api-latency-ms: 20000,
api-request-id: "55d07138-4056-405f-b361-e03ef56a386e"
}
>
>The event parameter "api_call" should remain as is. For the api-name, you can use any name that will help you identify the specific API. The api-status will be either successful or failed, and the others are optional. Your current dashboard does look at the error keys and latency so I suggest including those parameters.

## Tasks
- [ ] add the 'successful' and 'failed' events to the APIs for:
     - Disability rating
     - Next Appointment
     - Most recent payment

## Acceptance Criteria
- 'Successful' and 'Failed' events will be implemented, and the Analytics team will be able to locate the events and assist in pulling them into a dashboard/widget for monitoring.

**Comment by ajakabcin** [comment]
Hi @jennaouellet now that we're able to confirm #38739 is good to go can we can confirm this issue as well? cc @tmitchellgcio thank you!

**Comment by ajakabcin** [comment]
thank you!
