### ISSUE TITLE
IA Review for VA Forms Search

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#3887]
## Goal  
To review the IA structure, URL and entry points and provide feedback on the redesigned VA Forms Search tool.  Current tool: https://www.va.gov/vaforms/

## Background
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/agenda-va-forms-082819.pdf

**Context:** 
_- The primary users are Veterans, family members, caregivers, VSOs, and others who need to submit a form to VA. The primary task they are trying to accomplish is to find a form and download it, so they can complete it and submit it. 
Many users are unaware that some of these tasks are now available as online tools. The new MVP page should provide them the same access to paper VA forms while also making users aware of digital alternatives, if one is available._

**Mockup/Prototype:** 
Note: Copy not final

_- Default search  
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/Find-VA-form-search-pg-draft-mockup.png

- Search results 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/Find-VA-form-results-pg-draft-mockup.png

**User research:** 
_- SEO research and GA data research have been completed. No user research at this point. We may possibly conduct user research for MVP 2.0 (which will be to improve the actual search function).

Past SEO research can be found in this archived issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1482 [please note - this is an archived repo and no longer active/current]

**Keywords:** 
_- va forms, va form

**Additional Info/Considerations:**
_- Based on historical Google Analytics data, the current search page URL/s have tremendous organic search value. Given this, I recommend we maintain the existing URL and simply eliminate and redirect the weird search-action.asp URL that's competing with the main search.

## Definition of Done
- [x] Mock-ups or prototype reviewed with IA
- [ ] IA feedback/recommendations documented in ticket

**Comment by mnorthuis** [comment]
@lwalsh617 @jenniferlee-dsva Can you complete the info above and I will in turn document feedback/recommendations?  Thank you!

**Comment by jenniferlee-dsva** [comment]
Hi @mnorthuis - I've been shepherding search and search results page, so this is me. Will fill out above. Per our previous convo, the current search page URL/s have tremendous organic search value, so I'd like to maintain the existing URL and simply eliminate and redirect the weird search-action.asp URL that's competing with the main search.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva Do the existing form landing pages need to remain available to users until you launch the new landing pages?  

Example: https://www.va.gov/vaforms/form_detail.asp?FormNo=10EZ

**Comment by ncksllvn** [comment]
@mnorthuis Heads-up that we can't do a server-side redirect for https://www.va.gov/vaforms/search_action.asp (at this time) due to an edge case. The API we're using to query form data generates its database by scraping the page at https://www.va.gov/vaforms/search_action.asp. If we redirect that page, then the API for our modernized forms search won't be able to function.

**Comment by mnorthuis** [comment]
## IA Review and Feedback: 
If you have any questions or would like to talk through this feedback, please let me know.  This issue documents IA feedback and can be closed at your discretion.

### Structure, Breadcrumbs & URLs
- Pages shown in site map under the “Veteran Tools ” group: https://app.moqups.com/Rnc4BDEKrA/view/page/a4dc7a719

**PAGE:** “Find a VA form” tool landing page
- URL: www.va.gov/find-forms
*Please see notes below under “Redirects” regarding this URL recommendation*
- Breadcrumb: Home > Find VA forms

### Navigation, Entry Points and Crosslinking: 
**Top Nav, Header and Footer**
-	Keep existing “Find a VA Form” link within footer
-	No additional options to be added to the top nav, header or footer. Update footer link.

**Crosslinking**
- VA.gov Search Results page right rail “More VA Search Tools” module - https://www.va.gov/search/?page=1&query=example+search
	- Add an option to “Find a VA Form”, or replace the current “Find VA Forms and publications” option. 
	- Recommend placing this as the first option in the list if it is one of the most frequently used search tools on the site

### Redirects / Canonical Tags
There is some question as to the ability to redirect the old URL to a new one based on the current technical implementation of the data source for the forms search.  

**Option A**
If the new URL recommended above is implemented, there are several considerations/goals of the redirect work:
- all SEO value on the existing `/vaforms/` URL must be retained, this means that a permanent 301 redirect is required. 
- The `/vaforms/search_action.asp` URL also has high SEO value and will need to be permanently redirected to the new URL. 
  - There are many  child URLs that act as search landing pages for specific forms – i.e. https://www.va.gov/vaforms/form_detail.asp?FormNo=22-1990.  Each individual variation/form will need to be redirected to a specific new URL.  This will need to be mapped out. 
- Additional investigation should be done to identify any other content/sub-URLs that may be impacted. 
To execute on the redirects, please submit a redirect request per the [Redirect Request Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/request-redirect.md).   

**Option B**
If redirecting the current URL(s) will create a technical challenge with the planned data implementation…
- The current URL of `www.va.gov/vaforms/` should be retained.    
- The `/vaforms/search_action.asp` URL  (plus any parameters) should have a canonical tag added to point search engines to the primary URL and ensure that users are no longer directed to that page.    The page will still be accessible if directly accessed since it will not be redirected. 
 - The many  child URLs that act as search landing pages for specific forms – i.e. https://www.va.gov/vaforms/form_detail.asp?FormNo=22-1990 – should each still be redirected to specific new URLs.  This will need to be mapped out.
- Additional investigation should be done to identify any other content/sub-URLs that may be impacted. 
To execute on the canonical tags, please work with your front-end developer. 
To execute on the redirects, please submit a redirect request per the [Redirect Request Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/request-redirect.md).

**Comment by mnorthuis** [comment]
Regarding the URL/redirect options above,  @jenniferlee-dsva will be setting up a meeting to discuss with Lighthouse and @ncksllvn during the week of Jan 13.

**Comment by ncksllvn** [comment]
Option A sounds like the best option for SEO value and ultimately bring users to the best experience for searching forms. The potential issue I hinted at is that our API for querying VA forms generates its database by scraping the webpage of the legacy forms search, so we just have to be sure that a permanent redirect won't cause that API to stop functioning. I'm going to research this now with Devops.

**Comment by jenniferlee-dsva** [comment]
This IA/URL work is for the Find a VA form epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1632

**Comment by mnorthuis** [comment]
Recap from to our discussion with Michael Bastos, @ncksllvn @kelsonic  and @jenniferlee-dsva on 1/14/20:

We will move forward with Option A above with some additional details. 

**Option A**

The core search form URLs listed below will be permanently redirected (301) to the **new URL: www.va.gov/find-form/**
- https://www.va.gov/vaforms/
- https://www.va.gov/vaforms/default.asp
- https://www.va.gov/vaforms/search_action.asp
- https://www.va.gov/vaforms/search_action.asp[all parmater variations]

To support the technical implementation/API work, a duplicate version https://www.va.gov/vaforms/search_action.asp will be created for the API to hit and collect data.  
- **URL: www.va.gov/find-form-data**
- This new duplicate page must have a "noindex" tag and be excluded from the xml sitemap. 

The many child URLs that act as search landing pages for specific forms – i.e. https://www.va.gov/vaforms/form_detail.asp?FormNo=22-1990 - will not be impacted by this form search work.  Each individual variation/URL will be redirected to a specific new URL. This will be mapped out as part of the form search landing page work. 


@ncksllvn @kelsonic We should probably document this implementation in a md page in gh for future reference.

**Comment by jenniferlee-dsva** [comment]
^ @mnorthuis @ncksllvn @kelsonic : I added Mikki's notes ^ to the Find a VA form product folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

We can use the Readme file for the product to document more decisions in the future. 

Epic is here with links to all the related tickets and subtasks is : https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1632

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - One note I added ^ re the duplicate search-action index page: 

"/JL note: this duplicate page can be removed once the API can point directly to the forms database, per Michael./"

**Comment by ncksllvn** [comment]
A core takeaway here is that we need a way to move the legacy Find Forms to a new (private) location. So I suppose we could do one of two things - 

1. Have a TeamSite admin duplicate the page to a new location, which we'll add to VA.gov `robots.txt` to prevent from being indexed by search crawlers.
1. Work with DevOps to create a URL-rewrite, that essentially creates an alias location for the legacy page.
1. See if we can redirect GET requests to the legacy page but let POST requests pass through.

Investigating the bottom two options now.

**Comment by ncksllvn** [comment]
I'm exploring the idea of creating a "backdoor" that'll preserve the legacy form search for our internal purposes, but so we can redirect the public URL valuable to SEO.

For my own notes, [this dev document](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) is what I'm looking at.

**Comment by ncksllvn** [comment]
I created an [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4981) for the technical implementation of preserving the legacy page for internal purposes but redirecting it to our modernized version for SEO. I was thinking it would be easier to create a "/find-form-data" version of the legacy page, but actually, I think we can redirect only when the request type is GET, which is the only request type that matters for SEO purposes.

Either way, I think we can proceed from here knowing that we'll be able to do the technical implementation required for the forms search. However, I think the forms search is planned to launch with the forms detail pages, so those will have to also be done before we can actually do this implementation.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - one clarification re your comment above: 
>However, I think the forms search is planned to launch with the forms detail pages, so those will have to also be done before we can actually do this implementation.

Actually, they do not need to launch together. We can launch with the forms search and results first without the new forms detail landing pages (around 30 custom + all the rest as dynamic templated). 

(The forms search today brings up the actual individual PDF forms from the forms DB, and does not show form landing pages in the results.)

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - I'm just noticing that ^ doesn't include the 3 other forms search related pages that need redirecting as part of the search page launch. (Sorry - this was in an older version of the search page copydeck, but it was so long ago when Ryan and I did the FE design and content for that page...)  

Let me know if we should create an additional ticket for these 3 additional pages. Below is the full list of pages that should be redirected as part of the search page launch (minus the form detail landing pages). 

https://www.va.gov/vaforms/
https://www.va.gov/vaforms/search_action.asp 
https://www.va.gov/viewer.htm <-- 1. This 
https://www.va.gov/vaforms/help.asp <-- 2. This
https://www.va.gov/vaforms/contact.asp <-- 3. And this... should be redirected to the main forms search. 

#s 1 - 3 are currently linked to from the current search. Low MSV. Analytics attached (2018-2019 year's view). NVMD - GH won't let me attach - says too big. LMK and I can Slack it to you.)

**Comment by mnorthuis** [comment]
@jenniferlee-dsva Thank you for adding these, I wouldn't know they exist!   All of the redirects should be documented and submitted in a redirect ticket when your team is ready to do that.

**Comment by ncksllvn** [comment]
Side note - I'm realizing now that this redirect path must be exact - www.va.gov/vaforms/ - to make sure subdirectories aren't also captured.

But then we need to make sure we capture everything about  `www.va.gov/vaforms/search_action.asp` because of the parameters after a search - `/vaforms/search_action.asp?FormNo=&tkey=health&Action=Search`.

**Comment by mnorthuis** [comment]
@ncksllvn how can we document that to make sure its clear?  Just notes with each redirect?

**Comment by ncksllvn** [comment]
Redirecting a certain page/directory but leaving subdirectories is always kind of a gotcha for me. I suppose it just seems weird conceptually to be ready to redirect a parent before the subdirectories (although I totally understand it in each context.)

I suppose maybe if we want to make sure that a redirect is scoped only to a directory/page and no further, we could mark with an `*` or highlight it in red to show that it's "strict" or scoped only to that one level. As in -

`/vaforms/`*
`/vaforms/search_action.asp`

* Child directories must not be impacted.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - RE note above - I think Michael on API team mentioned that * used as a kind of 'wildcard' - 'grab everything after this.' Just want to make sure that the idea above of using * to equal 'do not redirect anything after this'  is doable?  (I'm out of my depth here, so apologies if asking a dumb Q.)

**Comment by ncksllvn** [comment]
@jenniferlee-dsva Ah good point, the * is misleading. I meant it as just a reference to a foot note, but now it looks like it's suggesting picking up child paths too. I updated the comment to be a little clearer

**Comment by mnorthuis** [comment]
In an effort to make sure this info is easily findable and not just living in this GH issue, I've moved the IA info to a markdown file:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-forms-search.md

**Comment by MickinSahni** [comment]
@ncksllvn @mnorthuis can we consider this particular ticket closed? Is there a follow-on ticket to incorporate any changes? I can one open if not

**Comment by ncksllvn** [comment]
I think we can close this in favor of the redirect request, https://github.com/department-of-veterans-affairs/va.gov-team/issues/5163

**Comment by MickinSahni** [comment]
Sweet. Thanks, Nick
