### ISSUE TITLE
Triage - Vets-API Server Instance in cycling loop 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#38876]
### Status

[RESOLVED]

### Severity Analysis

- `sev 1` 
    - Prod Sidekq Job Queue - [Slack Thread](https://dsva.slack.com/archives/C30LCU8S3/p1647869510129479)
    - Vets-api is Cycling Instances
    - SideKiq Queues Busy -- [SideKiq Busy Queue]()[Sidekiq Chart](https://grafana.vfs.va.gov/d/000000017/vets-api?viewPanel=21&orgId=1&from=now-1h&to=now)
    - External support services having issues AWS, Github, etc.. [AWS Outage Map](https://downdetector.com/status/aws-amazon-web-services/
AWS issue)
   - Charts for Proxy [Datadog charts](https://app.datadoghq.com/dashboard/pew-5za-287/forward-proxy?from_ts=1647955815814&to_ts=1647970215814&live=true)

        
### User Impact 

- First Identified: Sidkekq Job Queue: [Slack Thread](https://dsva.slack.com/archives/CQHBJ5U06/p1647870288840519)
- Vets-api is Cycling causing blips for Lighthouse APIs  - [Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1647874193259819)
- Duplicate Emails sent [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1647973634042339?thread_ts=1647973018.016179&cid=CBU0KDSB1) [Main Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1647973018016179)
- Vets-api eBenefits  submissions lacking PIDs at some alarming numbers [Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1647894654860649?thread_ts=1647893838.189709&cid=CBU0KDSB1)
- VBA claims documents submitted through the [Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1647874193259819)  are getting stuck in the UPLOADED status
- Forward Proxy Status:  [Datadog Link](https://app.datadoghq.com/dashboard/pew-5za-287/forward-proxy?fullscreen_end_ts=1647972364810&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1647957964810&fullscreen_widget=7098604533484448&from_ts=1647958053877&to_ts=1647972453877&live=true)
- Proxy Links: [Grafana Link]()https://grafana.vfs.va.gov/d/000000050/backend-service-report?viewPanel=76&orgId=1)
    
### Description

There seems to be issue with request from [EVSS - Enterprise Veterans Self-Service Portal Platform](https://depo-platform-documentation.scrollhelp.site/developer-docs/EVSS.1887240213.html) and [Central Mail](https://depo-platform-documentation.scrollhelp.site/developer-docs/Central-Mail-API.1885798523.html)

- vets-api-workers asg is at max capacity of 24
- Vets-api server is Cycling Instances
- Network Issue between AWS and AZURE [Slack Thread](https://dsva.slack.com/archives/C02THDWQAER/p1647960731655519)
- May need to up timeout.  [Github Code Change](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-prod.yml#L105)
- [more Timeout settings](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy/haproxy.conf.j2#L95-L97)
- Slack Thread with images and links [SRE Slack Thread](https://dsva.slack.com/archives/C02RLAUM2LV/p1647958568436079)
### Steps to Reproduce

Ruby Network hang code example.   Maybe add a Sleep to requests.  Simulate a long requests and retrys.

-  Reviewing the Diff of changes to Vets-API for week.   [Github Compare](https://github.com/department-of-veterans-affairs/vets-api/compare/0fcdc168cfc2db7b369ce6500deb99d77646d868..885f6609ec6bf2424f363c4a4749d660e2ff6f9b)
- Vets-Api Datadog [Metrics Link](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3A%28production%29&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanViewType=networks&streamTraces=true&viz=stream&start=1646762409222&end=1647972009222&paused=false)

### Proposed Solution

The following actions were performed to enhance vets-api .

https://github.com/department-of-veterans-affairs/vets-api/pull/9437 Inefficient code removed to ease load

https://github.com/department-of-veterans-affairs/devops/pull/10976 vets-api server tuned

https://github.com/department-of-veterans-affairs/devops/pull/10975 vets-api server scaling policy updated

https://github.com/department-of-veterans-affairs/devops/pull/10978 vets-api worker instances tuned

https://github.com/department-of-veterans-affairs/devops/pull/10985 vets-api worker scale policy changed from network to CPU based

**Comment by zachclarity** [comment]
Adding more Sidekiq instances one thing attempted:  because of [Slack Thread](https://dsva.slack.com/archives/C02RLAUM2LV/p1647966909134839?thread_ts=1647958568.436079&cid=C02RLAUM2LV)

**Comment by ph-One** [comment]
https://dsva.slack.com/archives/CJYRZK2HH/p1647885329438649

**Comment by ph-One** [comment]
We have had a healthy queue all day today, for the first time since this began on Monday. For both Monday and Tuesday vets-api was degraded, but not completely out.

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/9437 Inefficient code removed to ease load

https://github.com/department-of-veterans-affairs/devops/pull/10976 vets-api server tuned

https://github.com/department-of-veterans-affairs/devops/pull/10975 vets-api server scaling policy updated

https://github.com/department-of-veterans-affairs/devops/pull/10978 vets-api worker instances tuned

https://github.com/department-of-veterans-affairs/devops/pull/10985 vets-api worker scale policy changed from network to CPU based

**Comment by jhouse-solvd** [comment]
@zachclarity - At the top of this issue, I noticed it says "RESOLVED". Is there anything more needed from our team before closing out this issue?

**Comment by zachclarity** [comment]
Note: we are watching for future events.
