### ISSUE TITLE
Add 'state' to sign-in service authorize

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#38872]
Mobile has requested us to add a parameter called 'state' to the sign_in_controller `authorize` function, this parameter will then be returned to the client on the response (along with the `code` parameter in the response).

We probably should create some requirements for the `state` parameter that are sensible, perhaps alphanumeric and required to be between certain length requirements

**Comment by AGarcia-Clarity** [comment]
@bosawt I've started writing some smaller utility functions for this.  Currently I have it as alphanumeric and a length of 28 but I can reduce it if necessary.

**Comment by bosawt** [comment]
This has been completed
