### ISSUE TITLE
High Schools should be selected by default

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#38874]
## Issue Description
Due to an issue with codes in GIDS, EDU is requesting to have High Schools selected by default. The original requirement was to have High Schools unselected but since some Colleges have the wrong code in the db, having High Schools selected will remporarely help Veterans easily find the desired college. 

---
## Tasks
Set High Schools to be selected by default

## Acceptance Criteria
Set High Schools to be selected by default

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3100&group_by=cases:section_id&group_order=asc
Test case: [High Schools should be selected by default.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8327725/High.Schools.should.be.selected.by.default.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed 3/23/2022.
