### ISSUE TITLE
[FE] Review and Add "How To Test" Section to UAT Document for Edit Feature

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38899]
## Description
We need engineering to review the UAT document and add to it. We don't have the "How to test" section filled out for example. There is also probably some other engineering info to be added, similar to this old test cases document.

Here is an example of a previous [UAT document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md).

## Acceptance Criteria
- [x] Review UAT [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-docs/edit-demographics/testing/test-cases.md)
- [x] Add the "How to Test" section
- [x] Add other engineering info as needed
- [x] Communicate comments or revisions to Ben & UX

## Note
The last 3 test cases will be handled under this [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39217)

**Comment by brianseek** [comment]
@loripusey & @benbrasso-agile6 This is ready to review here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-docs/edit-demographics/testing/test-cases.md

I missed that there was already a bunch of test cases and wrote a few of my own and then merged the two a bit and refined some of the specifics around relative pages and where submission happens. Let me know if you have any other suggestions or want to co-work more on this.

**Comment by benbrasso-agile6** [comment]
Reviewing this now

**Comment by benbrasso-agile6** [comment]
Looks good. Made a couple updates - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-docs/edit-demographics/testing/test-cases.md

There are a few outstanding test cases to write, pending more information on implementation. 

@kristenmcconnell as I was reading this ticket this morning, I was realizing that I mention "pre-check-in" process a few times. In reality, is this for the day-of check in process? If so, would need to revise the "how to test" information.

**Comment by loripusey** [comment]
I am also confused, when we originally created this ticket I thought it was for the edit feature, but it mentioned questionnaires, so I really don't understand what this UAT is for. @kristenmcconnell @sarahknoppA6
