### ISSUE TITLE
[UX] Move Pre-Check-in Wireframes to Updated Sketch Location

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38893]
## Description
We never moved the MVP pre-check-in wireframes to our updated Sketch location, because engineering was utilizing them at the time. We reorganized Sketch a while ago. We need to go back and move the MVP pre-check-in wireframes from the "Check in - UXUI" file to the "Pre check in - UXUI" file.

## Acceptance Criteria
- [x] Move PCI Wireframes to Updated Sketch Location

**Comment by loripusey** [comment]
@zach-park can we go ahead and tack care of this?

**Comment by zach-park** [comment]
PCI (MVP) is moved to the "Pre check in - UXUI" file: 
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/1FE30041-97B7-4C9B-BBC0-1E6D2CE72ECC/canvas
