### ISSUE TITLE
Aligned on path forward regarding PDF accessibility

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#38903]
- [ ] Documented plan
- [ ] Agreed on plan with Tracey and Tarsha

**Comment by munishmo** [comment]
Just checking my access to Zenhub

**Comment by tameracorson** [comment]
![Screen Shot 2022-03-29 at 3.17.01 PM.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/7b1a98d0-aa27-4c6b-a2c6-c86019243f41)

**Comment by tameracorson** [comment]
Link to ticket for assistance from VA accessibility office of 508 compliance https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/Accessiblity/Accessibility%20check%20new%20IRS%20document%203.25.2022.pdf
