### ISSUE TITLE
Front End - Address Validation User Testing Updates 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3890]
This is the ticket for the front end build for updates resulting from Address Validation Usability Testing
  

## User Story: 

As a user, I need to understand why I'm being told the VA can't confirm/verify my address so I can make the best decision on how to move forward and save my address. 

## Tasks 

@bradl3yC copy updates are ready for the address validation feature for all states except the bad unit number case (which is being tracked in a separate ticket). Here are the four use cases we need copy updates for:

### Address is invalid. User can override this determination or pick a suggested address.

**Please confirm your address**
We couldn’t confirm your address with the U.S. Postal Service.  Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, please edit it or choose a suggested address below. 

![7  Scenario 1: Override; Suggestions](https://user-images.githubusercontent.com/34068740/70181837-a8301500-16b0-11ea-9bd3-c94644f7b23a.png)

### Address is invalid. User can override this determination, but there are no suggestions.

**Please confirm your address**
We couldn’t confirm your address with the U.S. Postal Service.  Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, please edit it. 

![13  Scenario 2: Override; No suggestions](https://user-images.githubusercontent.com/34068740/70181850-abc39c00-16b0-11ea-8608-3a4420c20581.png)

### Address is invalid. User can not override this determination. They can only edit or pick a suggested address.

**We couldn’t verify your address**
We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered or choose a suggested one below.  

![18  Scenario 3: No override; Suggestions](https://user-images.githubusercontent.com/34068740/70181859-af572300-16b0-11ea-8b2c-0ef0f1720e85.png)

### Address is invalid. User can not override this determination. They can only edit their address.

**We couldn’t verify your address**
We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered. 

{button} Edit address
{button} Cancel

![23  Scenario 4: No Override; No Suggestions](https://user-images.githubusercontent.com/34068740/70181863-b1b97d00-16b0-11ea-9ea6-84c0a4dddd71.png)

## Acceptance Criteria: 

- [ ] All copy has been updated.

**Comment by erikphansen** [comment]
Just a suggestion that it might be nice to be able to click on the `edit it` or `edit the address` text that appears in the Alert boxes.
