### ISSUE TITLE
Improve promo-banner footer padding in vets-website

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#38915]
## Issue Description

There was [some discussion](https://github.com/department-of-veterans-affairs/vets-website/pull/20457#discussion_r822074695) about the existence/removal of the `va-pad-promo-banner` CSS class. This class is defined [exclusively in `vets-website`](https://github.com/department-of-veterans-affairs/vets-website/blob/885a3cad31aa64190de0ab67893ea2c4303891ef/src/platform/site-wide/sass/modules/_m-footer.scss#L31-L37). That discussion led to that class being added to the `<body>` within a `component-library` component (https://github.com/department-of-veterans-affairs/component-library/pull/316).

Other related PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/20435
- https://github.com/department-of-veterans-affairs/vets-website/pull/20457

### Problems

This change creates a few issues.

- `component-library` is expected to make styling accommodations specific to `vets-website`
    - It shouldn't be the responsibility of the component library to adjust the spacing of elements outside of it.
- Maintainability is more challenging
    - An engineer looking through the `component-library` code for `<va-promo-banner>` might see the `document.body.classList.add('va-promo-banner')` and have no idea why it is there or what is doing. It requires specific knowledge about `vets-website`.
    - In `vets-website`, `va-pad-promo-banner` is not used in any markup, so an engineer might think it's safe to remove the CSS.
    ![image](https://user-images.githubusercontent.com/2008881/159547425-3d77ca07-e2b1-456b-863d-1e8b92f8900c.png)

- Unknown changes in other projects
    - Projects which use `component-library` but don't have `va-pad-promo-banner` defined will not receive this "fix"

### Recommended solution

Rather than dynamically adjusting the padding based on the presence of `<va-promo-banner>`, the footer could just have more padding by default. Here's an example of that change in `vets-website`:

```diff
diff --git a/src/platform/site-wide/va-footer/components/Footer.jsx b/src/platform/site-wide/va-footer/components/Footer.jsx
index a74e0b7943..c2ae6df4f1 100644
--- a/src/platform/site-wide/va-footer/components/Footer.jsx
+++ b/src/platform/site-wide/va-footer/components/Footer.jsx
@@ -40,7 +40,7 @@ class Footer extends Component {
   render() {
     return (
       <div>
-        <div className="footer-inner">
+        <div className="footer-inner vads-u-padding-bottom--6 medium-screen:vads-u-padding-bottom--4">
           <DesktopLinks visible={!this.state.isMobile} links={this.linkObj} />
           <MobileLinks
             visible={this.state.isMobile}
```

---
## Acceptance Criteria
- [ ] Revert https://github.com/department-of-veterans-affairs/component-library/pull/316 (or at least the `va-pad-promo` changes - the `line-height` may not be related)
- [ ] Styling changes to the [footer in `vets-website`](https://github.com/department-of-veterans-affairs/vets-website/blob/2e42c4dd81ee234840122da48021cd56fcc45761/src/platform/site-wide/va-footer/components/Footer.jsx#L43) stays in `vets-website`.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by caw310** [comment]
Closing as this is old and the VADS components have been updated so this should no longer be an issue. IF you are still seeing the issue with the new components, file a new bug.
