### ISSUE TITLE
IA Feedback -Design intent-Authenticated Profile - Bad Address Indicator

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#38922]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great to see design thinking/ideation artifacts like "five whys" that show how your team reached its decision. 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- Build out user flow into separate swimlanes representing each human and machine player in each interaction and using flowchart symbols to represent decision points and interactions. 
- Investigate feasibility of combining this info:
  - Here's the information we have
  - Confirm (this is correct) CTA
  - Edit CTA
into a single control using an experimental design system pattern. 
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by SKasimow** [comment]
Closing...working thru mid-point review and feedback now.
