### ISSUE TITLE
Update Backend Tutorial Docs

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#38920]
### Description
We need to update this Backend Endpoint Tutorial documentation.     

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/Backend-Endpoint-Tutorial.1886978053.html

**Comment by gmaciolek** [comment]
@zachclarity it looks like @LindseySaari has worked on this doc recently. Can you give more detail on what needs to be updated? Maybe Lindsey has already made the updates that address your concerns?

**Comment by gmaciolek** [comment]
CC: @amygoldman

**Comment by lianilychee** [comment]
Did not hear back, so reassigned to @zachclarity

**Comment by vbellissimo** [comment]
Followed up with Zachary via Slack on 6/30/22

**Comment by zachclarity** [comment]
closing covered in ongoing Q3 work.
