### ISSUE TITLE
Access for Nicholas Gaydosh

### ISSUE THREAD

**Issue by nickjg231** [department-of-veterans-affairs/va.gov-team#38926]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Nicholas Gaydosh

### Your Email

nick.gaydosh@adhocteam.us

### Name of Your Team

PTEMS - Forms Library Team

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZO+aqKDmI0RccisT/hDX1k/sPlldXAaxMGYq9uuKUDRjCpCHdoEjzTXUp3QVuJO7TXKmkxPw8yt2jwqgFWt38Rw31CdmbsTWLbg0KX0BHPfxPLlc3E90a0J9RtCYKz860i2dplZmu+b0dz3JilWQcesSPFro9RzxgOlej+KXeGKr0l32s8U4uCf3Jufm/qyTWT275QJEhgeu41zl7MJlqVZT83pqzhcpztfsS7sC2VikZdUDC4e0746oObC17V4lQqO9LNdM51pjJMzwZeDXVcnzPzEgRj5BmEaiDuoQzBSfeaVJv7XaxckZqZyoDRxAUDVX+I1djsFNFcdgSNCWb3V3qPRTgecnvsoZGE+edvG2MbiaT2wWVJJBGJFizVFUxn+0eMADDq7mJfixb4ERFOdvoxni+t5AG6FZHU1puM4BEZ1zbqLuccjzzrzAyjJhcNyUyniYiW4uYb8dWuhSgXob/bwFdGP9BiEF9lLbzn52CtnL1N0BpbSoLuLP+IDM= nickgaydosh@Nick-Gaydosh-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
