### ISSUE TITLE
[UX] Gather Images for the Resources and Support Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38927]
## Description
We need to pull images that Danielle needs for the resources and support page. Details in this Slack [thread](https://dsva.slack.com/archives/C01K37HRUAH/p1647964908659399).

## Acceptance Criteria
- [x] Gather images
- [x] Send to Danielle Thierry

**Comment by benbrasso-agile6** [comment]
@ytsaoca could you provide a new screenshot / png of the check-in log in page to replace the current one on the VA's Resources & Support page? I was going to pull one but it looks like the Sketch file includes an additional menu that's not present on VA.gov. E.g., Search, Contact Us, Sign In. Should those be in our Sketch file? Either way, I think if you strip that menu out and export a png, we should be all good. Thanks! 

![Screen Shot 2022-04-13 at 9.37.16 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/2871edd6-2905-4626-8bf1-0e30fc9a9e14)

**Comment by ytsaoca** [comment]
@DanielleThierryUSDSVA 

![Verify Identity.jpg](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/dce8b46e-785f-4f93-8872-07c3fc3b9243)
'cc@benbrasso-agile6
