### ISSUE TITLE
Access for Tze-chiu Lei

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#38937]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Tze-chiu Lei

### Your Email

tze@adhocteam.us

### Name of Your Team

VSA Engineering

### Service(s) You Want Access To

SOCKS

### Public SSH Key (for SOCKS requests only)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+Y5LHWpt9RfLZ/2EtX1aTIHGGMXp32nuffQK8Ogdu81LnesuSnQKP5KIFT0sMuSa9xlX1q0erjD6Knn5BXKWgPxF+ZwwHm4PjjQwC+kAsvEwjXPivrEx2Y4m6MRf/GOzLEgNjhVYRmbup8FD2ERnLDiT11km6CibEK80QNH363SmtVS/OaYoCmoA8eOpdDLaoQ/5v876OyVc+THuZe/jqOAJJfmb+7ruRT0ueWwGzKQsGFxL7A/Pg6nYWYUTNbD/M+Vz/Kelq1kYmv7LUH5MLaqt9OorBMyk5fcfU6vfye/sRSgwhLkt5lnbl4oZ3FrN4e3HTQQBlgbku75ZgSLLh5e/ti9LHoBpdIW2tU/HWaCE2Bkoiiz8PpqE+mOoSXJS+/Dolh8RmcLxwJpAG3N4+o76cUgTo7IUUXkToTFf92eOLpNhjoLxWCPJErm0CE+C/unVaFvnHLX1unKB7UUd8Gou+I80acwgKosLRWllxvj8BOqGztWjiT95nJGuS44k= tzelei@Tze-chius-MacBook-Pro.local

### Access Expiration

ongoing

**Comment by tlei123** [comment]
Hi folks, this is a new access-request.  I just had my Ad Hoc laptop re-imaged, and couldn't get socks proxy working using the old SSH keys I restored from backup.

**Comment by oseasmoran73** [comment]
Hey @tlei123 

I was looking at previous [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31329) and found this one.

Do you still want to keep your windows one and just update the mac one? Or should I remove windows one?

Just want to double check :)

**Comment by tlei123** [comment]
Hi, @oseasmoran73 !  Pls. keep my Windows SSH pub key.  I'll need that for potentially QA'ing PRs in review instances against Win browsers.  RIs are behind SOCKS proxy.  Thx much!  :)

**Comment by oseasmoran73** [comment]
@tlei123 All set!

**Comment by tlei123** [comment]
hi, @oseasmoran73 !  I re-Opened this 'cuz today I can't Pull from GitHub VA-dept repositories.  I'm getting error messages saying "git@github.com: Permission denied (publickey).

Do you need to add my new pub-key to the Department of Veterans Services GitHub Organization?

Pls. let me know.  Thx much!  :)

**Comment by oseasmoran73** [comment]
The error message reads to me that the key you saved in Github does not match the local one. All that is needed from our end is Pub SSH key

Found this [doc](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used), but I suspect this is what is happening

Let me know if you have any dice or not and we can look into it further together

**Comment by tlei123** [comment]
Ah!  So, sorry!  You're right, I just forgot to add my new pub-key to my GitHub Settings.  🗡️ 

Thx so much for the clarification!  I added it to GH Settings and now I can Pull from the VA-dept repos.  :)
