### ISSUE TITLE
Configure production URL shortener to use www.va.gov as the hostname

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#38934]
## User Story

As a veteran, I wish check-in links to work no matter what network I am on, so that I may pre-check-in and check-in for my medical appointments.

## Background

Users on the VA internal network are unable to access va.gov (as opposed to www.va.gov) and therefore cannot use the pre-check-in or check-in apps.

## Acceptance Criteria
- [ ] The URL shortener allows shortening links for va.gov AND www.va.gov
- [ ] The URL shortener always returns short URLs and redirected URLs pointing at www.va.gov, instead of va.gov

## Rollback Instructions

From [CHIP PROD DEPLOYMENT](https://github.com/department-of-veterans-affairs/chip/actions/workflows/prod-deploy.yaml) Action in GitHub
Click ‘Run workflow’ drop-down on the right
Select v2.0.0 tag
Click ‘Run workflow’

**Comment by loripusey** [comment]
@acrollet Did you want to pull this ticket into the new sprint? If so, can you add an estimate for it?
cc: @sarahknoppA6

**Comment by acrollet** [comment]
@loripusey estimate added, most of the effort will be in testing/validation. As to pulling it into the new sprint, I'll defer to you and @stephenBarrs :-)

**Comment by brianseek** [comment]
worked with other FE to put up this draft PR in the chip repo. Will bring to check-in api scrum tomorrow https://github.com/department-of-veterans-affairs/chip/pull/1445

**Comment by loripusey** [comment]
@brianseek can I move this out of this sprint? last comment was from December 1. Is there more work to do? We should not keep tickets in the sprint backlog unless we intent to work them

@sarahknoppA6

**Comment by brianseek** [comment]
Met with pci-api team today and they are reviewing

**Comment by brianseek** [comment]
Testing Notes:  Added a subdomain env variable to non-prod and confirmed that it works with long urls that contained the subdomain and those that didn't. All returns had the correct subdomain. I reverted the change and re-deployed, but I was still seeing the subdomain being added. I co-worked with Adrian a bit and we discovered that the variable didn't get updated in the build through deletion. I pushed another change to add an empty string as a subdomain on non-prod and that worked as expected. I then reverted that commit and everything still worked after a deployment.

**Comment by loripusey** [comment]
@brianseek is this now ready to close?
cc @sarahknoppA6

**Comment by michaelkimball** [comment]
Rollback instructions: Run [prod deploy action](https://github.com/department-of-veterans-affairs/chip/actions/workflows/prod-deploy.yaml) with v2.0.0 tag

**Comment by brianseek** [comment]
@loripusey this went out today (1/31) https://dsva.slack.com/archives/C03E5FEBTLH/p1675194346939149

Moving to closed.
