### ISSUE TITLE
FE- Auth Profile - Personal Info Revision - Retrieve PI data for a user

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38950]
## Background

Retrieve PI data for a user including gender identity and preferred name. Pronouns and sexual orientation are not approved fields yet and will not be included in this issue's work.

## Tasks
- [ ]  Add ability to retrieve PI data for a user

## Acceptance Criteria
- [ ] Add ability to retrieve PI data for a user

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
This is deployed to staging. For validation, when logging in with **user 36** you will see a preferred name and gender identity present, and that data is coming from vets-api when the profile loads.

**Comment by SKasimow** [comment]
@adamwhitlock1 confirmed - I see it in staging as well :)

**Comment by SKasimow** [comment]
Validated in staging - closing
