### ISSUE TITLE
FE - Auth Profile - Personal Info Revision - Change gender identity field back to single-select

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38955]
## Background

VA Profile has advised that MPI does not currently support multi-select (checkboxes) for gender identity.  That being the case, the field needs to be changed back to single-select (radio buttons)

## Tasks
- [ ] Change gender identity field back to single-select

## Acceptance Criteria
- [ ] Change gender identity field back to single-select

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
Helloooo @adamwhitlock1 when you have a minute, can you drop an estimate on this ticket? Thank you!

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 I'm moving this over to sprint 71 since it looks like this isn't done yet.

**Comment by adamwhitlock1** [comment]
I had to wait on a PR review, but it is up on staging now and can be validated @Samara-Strauss 

![Screen Shot 2022-04-06 at 9.56.23 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/0a15c558-a908-45c5-9d9f-a36dfe301336)
