### ISSUE TITLE
FE - Auth Profile - Personal Information Revision - Add ability to Add/Update Gender Identity

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38952]
## Background

Add ability to Add/Update Gender Identity

## Tasks
- [x] Add ability to Add/Update Gender Identity

## Acceptance Criteria
- [x] Add ability to Add/Update Gender Identity

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
@SKasimow and @Samara-Strauss This is up on staging and ready to validate.

If a user doesn't have a gender identity you can add one, and otherwise it may be be updated if previously set.

**Comment by Samara-Strauss** [comment]
Looks great to me! Validated with user 36.

**Comment by Samara-Strauss** [comment]
I just went in with user 1 and saw this. It looks like they don't have the copy that tells people to edit to add a gender identity.

![image](https://user-images.githubusercontent.com/34068740/166320473-6283f237-8ecf-40ec-9741-5da479135c81.png)

**Comment by adamwhitlock1** [comment]
@Samara-Strauss I fixed up the issue with the UI not displaying the placeholder text in my latest PR. Just verified on staging as well.

![Screen Shot 2022-05-03 at 12.59.38 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/f368393a-32bc-4802-a80c-19c5f4e270c6)

**Comment by Samara-Strauss** [comment]
Thanks! Validated with user 12. Looks good to me!

**Comment by SKasimow** [comment]
@adamwhitlock1 question - should the placeholder text stop appearing for Preferred name once a user adds a nickname? I noticed that it disappears when I select a Gender but not when I add a preferred name.
![Screen Shot 2022-05-03 at 3 29 49 PM](https://user-images.githubusercontent.com/74627978/166552203-94a82832-0d89-4ce6-9945-ff6695391709.png)

**Comment by adamwhitlock1** [comment]
@SKasimow

The placeholder text for Preferred Name is '**Edit your profile to add a preferred name**' I dont see that present when a name has been set. Are you seeing that text present when a name is set?

**Comment by Samara-Strauss** [comment]
I think there might be some confusion on the empty state text -- which does disappear -- and the helper text/directions, which do not disappear.
