### ISSUE TITLE
Rename "Platform Engineering Council" to "Platform Leadership Engineering"

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#38964]
The title "Engineering Council" is somewhat vague and ambiguous. The name should be updated to reflect that this is the group for Platform Leadership to discuss the topic of Engineering, including appropriate OCTO, vendor, and advisory staff.

## AC
- [x] Update Confluence page https://vfs.atlassian.net/wiki/spaces/ECP/pages/1871380563/Platform+Engineering+Council
- [x] Rename Slack channel [#platform-engineering-council](https://dsva.slack.com/archives/C021VJHTRS8) to `#platform-leadership-engineering`
- [x] Create Slack group @platform-leads-engineering and add current members
- [x] Rename confluence group `platform-engineering-council` to `platform-leadership-engineering`
- [x] Update meeting invite
- [x] Update Platform meetings page https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings

**Comment by mchelen-gov** [comment]
Ok I think all the items that require my perms have been completed.

**Comment by little-oddball** [comment]
Updated invite and confluence pages.
