### ISSUE TITLE
My VA: Audit conditional code

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38967]
## Background
For this collection of work, we want to audit the conditional code for each section.  We need to document each scenario in which the section appears, changes or remains hidden.
This exercise will also help us to determine where conditional code could be simplified, which will result in easier maintenance of My VA as a whole.

**Goal of this work:** To understand all the conditionals we have for each section in hopes of simplifying logic across (and therefore, management of) My VA. This does not yet have to be on GitHub -- if a Mural board or something more visual like that is an easier way to analyze and see states, let's start there.

**Comment by ajakabcin** [comment]
Closing this epic as audit work is complete. Implementation of findings from the audit can be tracked in #41934
