### ISSUE TITLE
Design - Auth Profile - Personal Info Revision - Create mockups with only preferred name/gender identity

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38965]
## Background

Since the sexual orientation and pronouns fields have not been approved by OMB, we cannot launch the MVP with them.  In order to complete our Contact Center documentation, we need mockups with only preferred name & gender identity, but also keep the mockups showing all four fields for future use.  

## Tasks
- [x] Create mockups that contain only preferred name and gender identity fields.

## Acceptance Criteria
- [x] Create mockups that contain only preferred name and gender identity fields.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Here are links to Personal info [Limited Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/dlVxdm3) and [Limited Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/ZODxr23) mockups - including the Date of Birth, Preferred name and Gender identity fields only. Any changes to hint text clarifying fields are optional will also need to be applied here.

**Comment by MarciMcGuireGCIO** [comment]
Looks great! Thank you, @cgednalske ! Cc @Samara-Strauss
