### ISSUE TITLE
Conduct research on urgent care PDF 

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#3897]
## User Story 
As the Facility Locator team, we need to validate our MVP assumptions and identify pain points in the user flow so we can improve the next iteration. 

## Objectives or Key Results this is meant to further
- Improve the Veteran Search Experience (Veterans have the information they need to be prepared for an urgent care visit. )
- Reform Community Care Implementation

## Tasks
- Conduct user research to: 
  - Understand how Veterans expect to learn about urgent care benefits and eligibility.
  - Discover patient friendly language for naming urgent care facility types
  - Collect feedback on the MVP workflow based on the Veteran urgent care  journey, including: 
    - If current workflow matches how Veterans expect to search for urgent care facilities, urgent care walk-in locations and urgent care/non-VA pharmacies
    - If Veterans are able to use the MVP workflow to distinguish between the sub-types of urgent care facilities and choose one that meets their need. 
     - If Veterans are able to use the MVP workflow to learn about benefits available at urgent care facilities, urgent care walk-in locations and urgent care/non-VA pharmacies
  - Obtain Veteran input on the urgent care PDF content. 
  - Learn from Veterans if there would be additional benefit in displaying  _Call 833-4VETNOW to verify eligibility_ outside of the PDF. 

## Goals
- Identify pain points in the user flow and areas to improve the next iteration
- Collect user feedback to share with Office of Community Care

## Acceptance Criteria
[ ] Research notes from 5 participants

Synthesis follows in [#4004]

**Comment by mmiddaugh** [comment]
@davidconlon 

1. Please review my "Tasks" and "Goals" additions above and edit as needed.
2. Regarding your "Urgent Care Facilities" section above, does this also pertain to pharmacies? 
3. Are you suggesting we should do user research with these user types? 
4. (And if so, is it possible, @arickalewis1?)

**Comment by mmiddaugh** [comment]
Note: For urgent care, urgent care walk-in, and urgent care pharmacy community care facility types we will not necessarily need a referral, unlike other facility types in Community care. This is an area with risk of causing confusion. 
@arickalewis1, we'll want to determine how to present this information for the various location sub-types: 

![image (7)](https://user-images.githubusercontent.com/55411834/70479927-48ac7d80-1a93-11ea-983e-035c3a109819.png)

**Comment by mmiddaugh** [comment]
@arickalewis1 please include link to artifacts when available (and then close this issue)

**Comment by arickalewis1** [comment]
Here's the  topline summary: 
[Facility Locator Urgent Care & PDF Topline Summary.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4125255/Facility.Locator.Urgent.Care.PDF.Topline.Summary.pdf)
