### ISSUE TITLE
[Build] HLR: Incorporate Design Updates on Review Submission screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3898]
## User Story:
As a Front-end developer on the Benefits and Memorials team, I need to update the Review Submission page so that I can ensure it follows the recommendation of the design team's review, which has been reflected in the latest design mockup.

## Tasks
- [ ] Update the Review Submissions page with design changes 

## Acceptance Criteria:
- [ ] The Review Submission page has been updated on in staging to reflect the latest mockup.

## Design Reference
#3806
[Invision Mockup](https://vsateams.invisionapp.com/share/J8UWM0P3KHM)

**Comment by Mottie** [comment]
Worked in #3532
