### ISSUE TITLE
Research - Auth Profile - MHV Research - Start final synthesis for all MHV research

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38998]
## Background

Start final synthesis for all MHV research

## Tasks
- [ ] Start final synthesis for all MHV research

## Acceptance Criteria
- [ ] Start final synthesis for all MHV research

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
[Draft started here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/final-synthesis.md)
