### ISSUE TITLE
Research - Auth Profile - MHV Research -  Run sessions

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38996]
## Background
Run research sessions with Veterans

## Tasks
- [ ] Run research sessions with Veterans

## Acceptance Criteria
- [ ] Run research sessions with Veterans

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
Sessions completed on 4/4
