### ISSUE TITLE
Console UI: Add unit tests

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#39002]
**User Story**:  In order to ensure the longterm reliability and stability of the RT plugin, the system should have unit tests.

Our console UI app has been an early stage prototype, so we don't have any unit tests. Now that the prototype has some features added, we should add unit tests to encourage refactoring and avoid regressions.

Backstage uses Jest to run tests, and includes React Testing Library. So we should be all set to use both of those.

**Comment by alexandec** [comment]
Completed unit tests for the Jobs component. PR merged: https://github.com/department-of-veterans-affairs/platform-console-ui/pull/339

**Comment by alexandec** [comment]
Completed tests for Container component. PR merged: https://github.com/department-of-veterans-affairs/platform-console-ui/pull/358

**Comment by alexandec** [comment]
Unit tests are now working in the [PR to add the design system](https://github.com/department-of-veterans-affairs/platform-console-ui/pull/349).

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSP---Release-Tools-FE-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/39002?planning-poker) with ZenHub @alexandec

**Comment by alexandec** [comment]
I'll close this one out since unit tests are in place for almost all the components and we're above 80% coverage. We can add the remaining tests in the course of our usual work on the plugin.
