### ISSUE TITLE
Front End - Initial  frontend setup to prevent DSLogon LOA3 users from accessing Direct Deposit

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3900]
Users who used DSLogon to verify their identity (ie are LOA3 via DSLogon) should be prevented from accessing the Direct Deposit feature.  

## Tasks 
We still need design and copy, but in the meantime we can hide the DD component and show temp messaging.

**Comment by Samara-Strauss** [comment]
Adding blocked label — we may decide to implement this feature later, but we also may not. Either way, this is on hold and is being removed from this sprint's to-dos.

**Comment by Samara-Strauss** [comment]
Should have closed this a while ago — DEPO team decided to not move forward with this.
