### ISSUE TITLE
Address impact of SSOe integration on developers

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#3901]
An effort is underway to integrate SSOe with VA.gov sign-in, such that signing in to VA.gov will also establish an SSOe session.

This introduces a dependency on SSOe for VA.gov including in the dev/staging/localhost environments, and could impact developers as follows:

1. If SSOe is down, VA.gov sign-in will fail. SSOe's lower environments (pint/int/sqa) are potentially less reliable than we would like them to be.
2. During this SAML interaction SSOe provides the data that we today look up from MVI. But in dev we mock MVI and are able to inject/update user attributes. We would lose that ability and need to have all test users added to the appropriate MVI environment (either pint or int). This potentially causes conflicts or changes in data with some of the test users we have become accustomed to using. 

Options:
* Go with the flow, account for SSOe outages in our development workflow. Audit current set of test users and get additional ones provisioned in MVI int/pint environments. Figure out if there's a path to self-service here.
* Mock the SSOe component in localhost or dev environments. This is not infeasible - the SAML proxy that is used in the VA API program actually provides 90% of this capability, including the ability to look up info from MVI (and which is mocked in dev) and inject it into the SAML payload. But it's more complicated than the usual betamocks use case because it's a browser-mediated interaction and hence requires a service to be running that a browser can access - i.e. it can't be stubbed out at the Rails level. 

In either case in order to maintain staging's similarity to prod, I think it should maintain a hard dependency on SSOe's equivalent environment.

**Comment by ambikaroos** [comment]
We got an agreement that once we're further along we can connect dev to their sqa environment, which takes care of the issue of developers needing VPN access. The issues about downtime are less predictable and will be an awareness issue to include in the FAQ. The mocking issue is in RFC about removing MVI lookups - we could have an option where in dev we still inject mock data.
