### ISSUE TITLE
Add "Server-side Redirects" link on "Front-end Architecture" > "Routing"

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#39010]
### Description

- There is no link under the **Server-side Redirects** section. The information described there looks to pertain to a different file than the one linked above. I believe it is https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/Routing.1844872008.html

**Comment by timwright12** [comment]
@gmaciolek @amygoldman That link is correct, however, platform doesn't handle redirects. I'm not sure how the new public websites contract is structured, but redirects traditionally fell on that team to update: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/redirects.md

**Comment by lianilychee** [comment]
Closing, since this has gone stale.
