### ISSUE TITLE
Add a "back to top" type button to an open log

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#39014]
**User Story**: as a user of the app I want a means of jumping back to the top of a job's log entry so that I don't have waste time scrolling back to the top of the logs.

The logs for a job in a workflow can be quite long; if a user scrolls down it is time consuming to scroll up or down far enough to get to the the next job log or the rest of the app. If we add a button  that hovers off to the side which, when clicked, will take the user to the top of the log entry, this problem will be eliminated.

**Comment by laineymajor** [comment]
@it-harrison is this something I can close? It's part of the original console ui prototype epic.

**Comment by it-harrison** [comment]
> @it-harrison is this something I can close? It's part of the original console ui prototype epic.

I think we might want to leave it open since it is still relevant, though there might be a different solution to the issue.

**Comment by laineymajor** [comment]
@it-harrison I added it to 'now initiatives' since you and chris are working on the improvements. we can close later if needed.

**Comment by rmessina1010** [comment]
Console UI work on hold ( this ticket may have been completed, check with @it-harrison )

**Comment by jhonnyoddball** [comment]
Console UI work, closing for now.
