### ISSUE TITLE
Submit intake forms for VA Profile (opt-in)

### ISSUE THREAD

**Issue by ashleycastillo** [department-of-veterans-affairs/va.gov-team#39020]

**Comment by tameracorson** [comment]
input ticket here: https://vajira.max.gov/servicedesk/customer/portal/12/create/568

Sample form:
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/550e4ebf-73aa-4aa7-999b-f10c9c955e3e)
