### ISSUE TITLE
2019-11-21 GIDS latency incident

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3902]
## Incident investigation / postmortem

On 2019-11-21, the GIDS application experienced a high volume of requests which created latency in that application. This latency then cascaded back up into vets-api. This epic is to track investigation and follow-up work from that investigation.

Link to PM: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/17

## Definition of done
Incident report is done and merged in the sensitive repo, follow-up items are triaged and actioned.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by alexpappasoddball** [comment]
@ricetj Removing BE Tools label for now.  Let us know if there is something you need our help with.
