### ISSUE TITLE
[SW-Content] Update Burials and Memorial pages [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39035]
## Story
As a Veteran all pages should have accurate information, so I know if I am eligible for benefits and/or services.

## Task(s)
- [x] Review and then delete the word(s) "active-duty" in 2 places on the Eligibility for burial in a VA national cemetery page

## Acceptance criteria
* Words are removed and pages are published.

**Comment by RLHecht** [comment]
I updated the page, published, and notified the stakeholder that the changes are live. Moving to validate.
