### ISSUE TITLE
Searching while back-end unavailable returns no search results

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#3903]
When the back-end for search is unavailable, a search returns an empty result set instead of correctly indicating that an error was encountered.  Example steps --

1. Start up the front-end locally
2. DO NOT start up the back-end
3. Perform a search from the main page using a string that is known to have results (example: "burial")
4. Note that the results come back empty instead of providing any indication to the user that their search was not actually performed because the back-end for search was unavailable

**Comment by mandifrances** [comment]
Was used as an example
