### ISSUE TITLE
[SW-Content] OCTO review of $600 Buy up rates page

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39037]
## Story
Please review final copy for the below listed Story

## Resources/Story
Patrick Sanders
#8636 Education Rates page - $600 Buy up rates page

## Tasks
- [x] Final review of content and design created for Education Rates page.
http://preview-prod.vfs.va.gov/preview?nodeId=5572

## Acceptance criteria
* Review and/or provide any final recommendations or improvements to content.  Thank you.

**Comment by bethpottsVADEPO** [comment]
I've made some edits to this page and it's ready to send to stakeholders. Will send the preview link to Education Service once I have 3-4 more pages for them to review.

**Comment by RLHecht** [comment]
@megzehn With Beth OOO this week, she asked if you can do a copyedit of this so that I can send to the stakeholders to keep these moving. Thanks!

**Comment by RLHecht** [comment]
I sent this to the stakeholders for their review on 6/23.

**Comment by RLHecht** [comment]
Old ticket. Closing.
