### ISSUE TITLE
Find a VA Form - PDF modal launched in Dec is not appearing

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39039]
## What happened?
In December, a feature was added to Find a VA form so that users see a modal when attempting to download a PDF.  The modal provides info on how to download and open, as well as a link to a research and support page with more information, and was coded to only appear once every 24 hours.

That modal is no longer appearing on the Find a Form search page or detail pages, and there doesn't appear to be a ticket related to removing or disabling it.

## Specs:
- Device: Windows 11 PC,  iPhone 11
- Browser: Chrome/Safari
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: https://va.gov/find-forms/
- Test User _(if applicable)_: N/A

## Desired behavior
A modal should be displayed when a user clicks a PDF download link in the form search results or a given form's detail page.

## Acceptance Criteria
- [ ] A modal should be displayed when a user clicks a PDF download link in the form search results or a given form's detail page.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MarciMcGuireGCIO** [comment]
@davidconlon I'm unsure who currently maintains Find a VA Form, but wanted to make someone aware of this issue.  Thank you!

**Comment by davidconlon** [comment]
@MarciMcGuireGCIO I discovered this yesterday myself!
@leahkeeler and @TSimmz I think this might be the same as the "popup blocker" issue I identified.

**Comment by davidconlon** [comment]
This was fixed
