### ISSUE TITLE
VAOS Staging: Direct Scheduling into Friendly Name FTC Amputation 502 Error

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#39048]
## What happened?
This issue has been reported by Marcy Nadeau (https://issues.mobilehealth.va.gov/browse/VAOSR-3151).  Opening a GitHub ticket  as per Jenna's last comment " please open a front end ticket for them to triage on their side and link through to this ticket"

## Specs:
Environments, users, and patients tested in:
CHYSHR
[judy.morrison@id.me](mailto:judy.morrison@id.me)
cecil.morgan@id.me

Versions Tested: 
vaos-service 1.17.0

## Steps to Reproduce

1. Set VATS Direct Scheduling Fort Collins Amputation to Yes Any
2. Log into VAOS as Judy Morrison or Cecil Morgan.  Select Amputation. Select Fort Collins.  
3. System will display Choose VA Clinic.  Select Make my appointment here (clinic will show as Friendly Name FTC Amputation).
4. Enter April 1, 2023
5. System will display available time slots.
6. Select a slot. then a reason and enter text in reason text box. 
7. For contact information you can update or change as desired (note no email/text gets sent so you can accept the default information).
8. Select Confirm appointment.
9. **Results Expected:**  Appointment is confirmed
10. **Results Seen:**  Dev tools shows 502 error

I was able to schedule into this clinic in VistA.

I was able to schedule into this clinic with VAR-Resources (ruben moreno)

I checked and the max number of future days is not the issue. Prohibit access to clinic is not the issue.  

We have over 36 clinics configured for direct scheduling across all the specialties for CHYSHR and DAYTSHR.  I have NOT tested all the clinics. 

I tested without issue CHY PC VAR2 and WHT AUDIO VAR2 and was able to successfully schedule. 

**End User Impact:** 
Veterans will get errors when trying to direct schedule

![FTCAmputationDirectScheduling](https://user-images.githubusercontent.com/69315717/159924163-09513ca2-e19a-4d87-8703-f2fea83582ec.png)

**Comment by aarathi-poldass** [comment]
@ldelacosta - Can you please prioritize and add all the additional details to the ticket

**Comment by marcynadeau** [comment]
@ldelacosta just tested this again with VAOS Service 1.81.2 and MAS 2.17.1 and this is now working.  You can close this ticket.

**Comment by ldelacosta** [comment]
No longer an issue. Closing out the ticket.
