### ISSUE TITLE
Code checks for PR unable to find mapping file inside that PR

### ISSUE THREAD

**Issue by alsleaders** [department-of-veterans-affairs/va.gov-team#39049]
I talked to Riley about [this ticket](https://github.com/department-of-veterans-affairs/vets-api/pull/8893) roughly 2 months ago and then I got pulled onto other things and never circled back.  I have a test failing in this PR with the message that it cannot find the mapping file.  The mapping file is part of the PR and when I try to change the name of the mapping file from `21-22a.yml` to `21-22A.yml` the test continues to fail.  (I tried to change the file name in this PR and the renaming didn't register, so I tried it on a whole new branch, and either way I name the mapping file the test fails with the same message.).  I'm not sure what steps to take to make the mapping file visible to the test.

**Comment by zachclarity** [comment]
@rileyanderson  I had them create a ticket to keep track since this was an old requests and may need some research.
