### ISSUE TITLE
Investigate flaky Cypress E2E tests

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#39053]
This task is to look into all flaky Cypress tests in `vets-website` and to find a fix for the flakiness. [This Domo dashboard](https://va-gov.domo.com/analyzer?pageId=1118639976&cardid=1521020182&userId=486588602) has been keeping track of flakiness in CI.

**Comment by pjhill** [comment]
Although this is never truly done, the scope of the fixes for this round of fixes has been completed.
