### ISSUE TITLE
[Enabler] High Schools not coming up at all when only the High School filter is enabled 

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#39069]
## Issue Description
Cinda with EDU reported having found certain High Schools not coming up at all when only the High School filter is enabled. Cinda will provide use cases and requiremens for AFS Dev to investigate and figure out why they are not displaying when their code is correct and should display.

This story is to conduct analysis.

---
## Tasks
This story is for Dev to conduct analysis.

## Acceptance Criteria
High Schools with the right codes must be displayed when only the High Schools filter is selected.

**Comment by MitchLivingstone** [comment]
Dev already implementing this change through #39715
