### ISSUE TITLE
[UX] Coordinate with STL Staff for Research Trip

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39077]
## People Going
David (VSE)
Ben
Zach
Ya-Ching

## AC
- [x] Reach out to STL staff
   - Samatha Hoover
   - KaTonya
- [x] Nail down dates for trip (locations and dates/times)

**Comment by kristenmcconnell** [comment]
The contact at St. Louis to coordinate with are:
Samantha Hoover (samantha.hoover@va.gov) and Katonya Riddle (katonya.riddle@va.gov).

Stephen Barrs would like to be cc'd on all communications.

**Comment by kristenmcconnell** [comment]
David's email is also david.dunnam@va.gov.
