### ISSUE TITLE
"Please call" text change (grammar) on Facility Locator Detail page

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#3907]
## What happened?
Text on facility detail page says "Planning to visit? Please call first _as information on this page change._" 

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/cbc1362a-1f3f-4590-9f65-ee91c42eaedb)

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/facility/vba_311

## Desired behavior
- Text should say: "Planning to visit? Please call first as information on this page may change." (insert the word "_may_")

## Acceptance Criteria
[  ] Text should say: "Planning to visit? Please call first as information on this page may change." (insert the word "_may_")
[  ] This change is reflected on facility detail pages for all types (VHA, VBA, Vet Centers, Cemeteries).

**Comment by mmiddaugh** [comment]
Merged!
