### ISSUE TITLE
Create proposal for improving Storybook organization

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39086]
## Description
It was clear from the user interviews we conducted in Q1 that the lack of organization of our Storybook has led to confusion among some VFS engineers. We would like to find a way to organize our Storybook stories in a way that will help VFS team members (designers, engineers, product mangers, researchers, etc.) clearly understand what components are available in our design system, where they can be used (for example, React components can only be used inside React applications), and what state they are in (i.e. ready for use, under review, deprecated, under development, etc).

What we're looking for here is a plan for how we should organize Storybook and how we should break up the work to get it done. What should come out of this ticket is a detailed plan and a set of tickets for completing the work.

## Details
See this [Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1647035715991879) for some inspiration. Storybook also has a lot of other implementation examples on their site.

## Acceptance Criteria
- [ ] Create plan for adding organization to our Storybook site
- [ ] Create plan for completing work
- [ ] Review plans with team
- [ ] Create epic ticket with final plans
- [ ] Create tickets for completing work

**Comment by pdavies88** [comment]
Per conversation on Hierarchy Side Navigation in Storybook should follow this pattern:
` title: 'Components/Pagination/React Components/Pagination',`
`title: 'Components/Pagination/Web Components/va-pagination',`

If a component does not have a corresponding React Component associated with it it should follow this pattern:
`title: 'Components/Pagination/va-pagination',`

![Screen Shot 2022-04-15 at 2.58.21 PM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/e5bfc6eb-7c0b-4e02-a4e8-a27db8b62b25)

**Comment by k80bowman** [comment]
I'm interested to know what you think about some other classification methods for our components, similar to the way we group our form control components on design.va.gov. As part of this ticket, I'd appreciate it if you could dig into that a little further and provide a recommendation. For inspiration, there are a lot of examples on the [Storybook](https://storybook.js.org/showcase/) site. I pulled some of the ones I liked into [this Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1647035715991879).

**Comment by k80bowman** [comment]
Would also be a good idea to look at the [documentation site IA mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1649702628893/aa89b2e053fd5037f9a95a13c78eff127841de3c?sender=u9ae4d29a0ed5c3d2753a7824)

**Comment by pdavies88** [comment]
Addons to leverage: 
- https://storybook.js.org/addons/@storybook/addon-storysource/ (shows the way we built the story without having to dig into the code via the repo)
- https://storybook.js.org/addons/@storybook/addon-a11y/ (general accessibility testing prior to accessibility reviews)

**Comment by pdavies88** [comment]
**Preface: This is a potential plan for upgrading our existing Storybook infrastructure and layout**

**Side Navigation Layout:**
- Per conversation on Hierarchy Side Navigation in Storybook should follow this pattern:
  - title: 'Components/Pagination/React Component/Pagination'
  - title: 'Components/Pagination/Web Component/va-pagination'
- If a component does not have a corresponding React Component associated with it it should follow this pattern:
  - title: 'Components/Pagination/va-pagination'
- Groupings and Titles should match side navigation groupings on https://design.va.gov/components/ ie:
  - Form and Progress Bar should be broken out further
    - title: 'Components/Form/Radio button/React Component/RadioButtons’
    - title: 'Components/Form/Radio button/Web Component/va-radio’

**Storybook Addons:**
* https://storybook.js.org/addons/@storybook/addon-storysource/ 
  * This shows the way we built the story without having to dig into the code via the repo within the Canvas tab
* https://storybook.js.org/addons/@storybook/addon-a11y/ 
  * This provides general accessibility testing prior to accessibility reviews within the Canvas tab

**Maturity Scale:**
* Label tags that we use on design.va.gov should also exist on Storybook in the Docs tab below the name of the component and above the link to design.va.gov. Example code snippet missing: 
```
<span class="usa-label site-component-status site-component-status--use-deployed">Use: Deployed</span>
```

**About Documentation:**
I would recommend leaving the structure as is with Introduction and How to use Storybook but I would recommend adding additional topics to both pages.
* For the Introduction page: 
  * Using the Design System - Link to https://design.va.gov/about/developers#using-the-design-system
  * Contributing to the Design System - Link to https://design.va.gov/about/contributing-to-the-design-system 
  * Report an issue - Link to https://design.va.gov/about/feedback 
  * Design System Backlog - Link to https://design.va.gov/about/backlog 
  * Maturity Scale - Link to https://design.va.gov/about/maturity-scale 
  * How to Migrate - Link to https://vfs.atlassian.net/wiki/spaces/DST/pages/2052161541/Migration+to+Web+Components this should also include a blurb about how we have ESLint rules in place on vets-website that can be used via VS Code to automatically migrate some components. We should also include that list of ones available within this blurb
  * Web Components vs React Components - We should have a blurb on the difference between web components and react components and why we are performing the migration from react components to web components. I believe this context will be helpful for current developers when they are trying to pick the correct component to utilize.
* For the How to use Storybook page:
  * How to use the Canvas Tab - We should have a blurb showing where the ‘Canvas’ tab lives and what exists inside of it. This should include screenshots of the tab and its sub-tabs as well as information about what task each sub-tab performs.

**Docs Section:**
* Add to description for all components “Information on this components accessibility, html output, and how it is used within Storybook can be viewed by clicking the `Canvas` tab”

**Comment by pdavies88** [comment]
@k80bowman please see above as an opening discussion point into some changes for Storybook

**Comment by k80bowman** [comment]
@pdavies88 [Add Maturity Scale to Storybook component stories](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/831)

**Comment by k80bowman** [comment]
@pdavies88 in your research, have you seen ways that we could make Storybook more interactive?

**Comment by pdavies88** [comment]
@k80bowman I definitely think the prototyping features of Storybook would be more of a Phase 2 approach. I am going to add a Discovery requirement to my original comment talking about looking into that type of work to make storybook more of a read and create system.

**Comment by pdavies88** [comment]
## Feedback:
* Introduction Page Documentation should exist on design.va.gov specifically - React vs Web Components and How to Migrate since they don't exist or exist in Confluence and should be added to design.va.gov
* Backlog should link to our repo with the issues filtered by our team
* Canvas tab link iFrame should also exist in design.va.gov

**Comment by pdavies88** [comment]
## Design.va.gov
Will need to be updated when the sidenav is changed since all of the links will have changed via the new hierarchy. 

## Announcement
Once all links are changed put an announcement in #vfs-frontend #vfs-all-teams #vfs-engineers and #design

**Comment by pdavies88** [comment]
Priority:
* Update documentation portions and linking portions first
* Then add addons
* Then fix Sidenav hierarchy

**Comment by pdavies88** [comment]
Related Tickets: #41381 #41384 #41386 #41388
