### ISSUE TITLE
VR&E 28-1900 Claims / PID-less report / Feb1-NOW

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#39099]
Due to the MPI issues the past few days, many 28-1900 claims were unable to be uploaded to VBMS due to participant_id's not being found in Redis.
Our stakeholder, Veteran Readiness & Employment, has requested a CSV of all "PID-less" claims recently.
If you could run the following snippet in production like you have recently, we'd really appreciate. This is NOT a regular thing, just incidental.

```
Benchmark.measure do |bm|

  starting_date = DateTime.parse("Feb 1, 2022")

  pidless_claims = SavedClaim::VeteranReadinessEmploymentClaim.where(created_at: starting_date..Time.now).select do |claim|
    claim.parsed_form["veteranInformation"]["pid"] == nil
  end

  require 'csv'

  attributes = %w(created_at first_name last_name regional_office ssn main_phone email)

  CSV.open(Rails.root.join('tmp',"pidless_#{starting_date}-to-#{Time.now}.csv"), 'w', write_headers: true, headers: attributes) do |csv|
    pidless_claims.each do |claim|
      vet_info = []
      vet_info << claim.created_at
      vet_info << claim.parsed_form['veteranInformation']['fullName']['first']
      vet_info << claim.parsed_form['veteranInformation']['fullName']['last']
      vet_info << claim.parsed_form['veteranInformation']['regionalOffice']
      vet_info << claim.parsed_form['veteranInformation']['ssn']
      vet_info << claim.parsed_form['mainPhone']
      vet_info << claim.parsed_form['email']
      csv << vet_info
    end
  end
end
```

keybase username is `rudyonrails`

**Comment by RudyOnRails** [comment]
@jason-gcio

**Comment by zachclarity** [comment]
@rileyanderson I am unsure we need to do this for other teams also.

**Comment by RudyOnRails** [comment]
@zachclarity you _may_ not have to. These claims were most likely still transmitted to the backup repository, Central Mail, which we use as a plan B in case VBMS is having problems or the Veteran truly does not have a participant_id.

Since it is more work for the VR&E dept to process claims that are not in VBMS/e-folders, the stakeholder would like a report to get a bird's eye view of the larger work/situation at hand.

Thank you,
Kevin

**Comment by rileyanderson** [comment]
@RudyOnRails I keybased you the `.csv`
