### ISSUE TITLE
[Design] On-site Notifications: Explore style options for alerts/notifications on My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39090]
## Background
In ticket #[36340](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36340), screenshots were gathered of various notifications vs errors on MyVA and guidance was provided from the platform team on which component should be used across the board. 

<Details>
<Summary>Guidance from Natalie Hill:</Summary>

> I recommend the Warning alert -- either the standard full-width style or the background only style -- for the scenario you are describing. We can also talk about making it dismissible if you'd like that option. (NOTE: we would not want to dismiss warnings)

</Details>

During this review, it was determined that further exploration on the current 'warning' style is used for the 'alerts' (aka notifications) for Onsite (top) and Inline (sections).  This ticket to work through that exploration of the styles available, or potentially create a new style that calls out the alert more than the styles we have already tried.

Thoughts discussed on the ticket above:
>**Samara**: We use the warning alert style (right?) for notifications on My VA. Having all of our errors have the same style might start to feel confusing re: what is a notification vs. what is an error message.
>- **Angela**: Absolutely agree on your first point and the fact that we're using that type of alert for notifications has literally been keeping me up at night. This is something I'd love to address in our roadmap in the near future if you agree because I think we all viewed changing the notifications to that style as a band-aid and not the ultimate solution. Now we're seeing yet another reason why we probably shouldn't use the warning style alerts for notifications. Maybe we should address this before working on updating these alerts.
>
>**Samara**: Error messages should never be dismissible. I don't want people dismissing an error alert, reloading a page, and then getting no feedback that a system isn't working. We'd be losing really valuable feedback for the user on what's going on if they can X out of error messages.
>- **Angela**: Also agreed that they don't need to be dismissible; I let Natalie know that wasn't necessary.

## Tasks
- [ ] Explore thoughts and ideas on "Alerts" styles to use on My VA for Onsite Notifications, and Inline/Section notifications.

## Acceptance Criteria
- Exploration of styles used on My VA for Alerts is shared with the team for discussion

**Comment by ajakabcin** [comment]
reviewed style options with team on Monday 5/2
