### ISSUE TITLE
[Mission Act] Facilities Locator showing inaccurate map data

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#391]
### Status

*UNRESOLVED*

### Severity Analysis

As this is considered Mission Act, according to OI&T, a fix is mission critical. 

### User Impact 

A veteran may see incorrect/inaccurate map data when searching for facilities, which could negatively impact their care.

### Description

From ServiceNow:

> When I went in to find a community provider for two veterans now, both from Covington, it claims mileage to Roanoke/Salem area is about 30 miles.  So when doctors are approving community consults, they may see these same errors and think that in fact a provider in this area is that close.  I just wanted to let you all know, especially **** and **** since they work with the providers more frequently.  The providers would probably want to verify with Bing Maps just to make sure when authorizing an In-Network provider closer to the patient.

 > If I am a Veteran from Covington and I look for the nearest VA, it shows Salem 25 miles closer than it really is.

### Steps to Reproduce

- *List steps required to reproduce the issue in question*

### Screenshots
![unnamed.png](https://images.zenhubusercontent.com/5951581361b4ca3b0a725a57/f91cddf1-7818-464f-8bd5-a4fc45e4348e)

![unnamed (1).png](https://images.zenhubusercontent.com/5951581361b4ca3b0a725a57/3c687cf7-c52d-471f-b7fc-82caad354364)
### Further Details

- ServiceNow # INC6199383

### Proposed Solution

- *Summary of solution*
- *Link to related tickets*

**Comment by cvalarida** [comment]
![image](https://user-images.githubusercontent.com/12970166/60202509-8d9f6900-97ff-11e9-83f4-6a0b9440c462.png)

Looks like that 35.8 miles comes from the distance as the crow flies, not driving distance.

What's the expected behavior for calculating distance?

**Comment by cvalarida** [comment]
**Update:** Looks like this is the expected behavior, but it's not what Mission expects.

The facilities API on developer.va.gov is currently under development and will be used for the Mission Act data.

Source: Slack, @dhall

**Comment by kfrz** [comment]
Closing this issue until further notice. See discussion [here](https://dsva.slack.com/archives/C0MQ281DJ/p1561486544079700) in DSVA Slack.
