### ISSUE TITLE
[FE] My VA - Health Care update: Add new Anchorage health system as Cerner in My VA (POSTPONED) 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39129]
## Background 
Anchorage health system is being added as a Cerner health system in July.  We will need to add this to the list of Cerner facilities IDs that we have, and update the copy of the Cerner Alert. 

> ID 463 - Anchorage: Go-live -- 7/16/2022

## Tasks
- [ ] [FE] Add filtering so Cerner alert will now show for Anchorage. The facility number is **463**.
- [ ] [FE] Update the copy in the alert  (Copy and logic may be revisited before this implementation - [Ticket #39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by ajakabcin** [comment]
Closing - this work was originally postponed and then later the process for adding Cerner facilities changed to be managed through a drupal integration.
