### ISSUE TITLE
Chaos engineering Environment for observing how the system responds, and implementing improvements

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#39121]
- Start Date: 2022-03-25
- Gatsby Issue: [Chaos engineering Environment for observing how the system responds, and implementing improvements #39121](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39121)

# Summary

Create a  Chaos engineering.setup of vets-api. 

NOTE: This will not be a public facing website, and only needs ip access for the SRE team and Operations.   The goal is to run tests and not simulate user activity.

Chaos engineering is the process of stressing an application in testing or production environments by creating disruptive events, such as server outages or API throttling, observing how the system responds, and implementing improvements. 

# Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

- Chaos Engineering methods help improve the reliability and stability of our complex environment.

- We have many external dependencies that create many difficult to diagnose issues and errors.

- To create playbooks for various incidents by simulating failures from all of the potential points of failure.

- The SRE Team is tasked with helping to improve the reliability and stability of systems and to reduce the incidents and response to known incidents.   

- Chaos engineering helps enhance and improve incident response playbooks and system resiliency, by creating the real-world conditions needed to uncover the hidden issues and performance bottlenecks that are difficult to find in distributed systems. 

# Detailed design

NOTE: This will not be a public facing website, and only needs ip access for the SRE team and Operations. The goal is to run tests and not simulate user activity.

Create new Chaos Engineering Env Simulated with a K8 cluster for each of the key network points 
 
- [ ] Create a new K8 cluster setup to simulate the following for vets-api 
   - [ ] Sidekiq queue Failure
   - [ ] Reverse Proxy ALB 
   - [ ] Forward Proxy 
   - [ ] Two Vets-Api K8 for failure over
   - [ ] Network access to Sentry and Datadog

# Drawbacks

Why should we _not_ do this? Please consider:

- The initial setup will required some time from the Operation team
- AWS resources for the simple K8 cluster

**Comment by zachclarity** [comment]
Limiting this to key Single Point of Failure and Monitor triggers.

**Comment by little-oddball** [comment]
Determined OBE
