### ISSUE TITLE
[FE] My VA - Health Care update: Add new Portland health system as Cerner in My VA (POSTPONED)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39134]
## Background 
Portland health system is being added as a Cerner health system in November 2022.  We will need to add this to the list of Cerner facilities IDs that we have, and update the copy of the Cerner Alert. 

> ID 648 - Portland: Go-live -- 11/5/2022

## Tasks
- [ ] [FE] Add filtering so Cerner alert will now show for Portland. The facility number is **648**.
- [ ] [FE] Update the copy in the alert  (Copy and logic may be revisited before this implementation - [Ticket #39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by ajakabcin** [comment]
Closing - this work was originally postponed and then later the process for adding Cerner facilities changed to be managed through a drupal integration.
