### ISSUE TITLE
[FE] My VA - Health Care update: Add new Dayton health system as Cerner in My VA (Feb 2023)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39135]
## Background 
Dayton health system is being added as a Cerner health system in Feb 2023.  We will need to add this to the list of Cerner facilities IDs  that we have, and update the copy of the Cerner Alert. 

### **NEED TO GET THE FACILITY ID FOR THIS**

> ID TBD - Dayton: Go-live -- 2/18/2023

## Tasks
- [ ] [FE] Add filtering so Cerner alert will now show for Dayton. The facility number is **TBD**.
- [ ] [FE] Update the copy in the alert  (Copy and logic may be revisited before this implementation - [Ticket #39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by ajakabcin** [comment]
Closing - this work was originally postponed and then later the process for adding Cerner facilities changed to be managed through a drupal integration.
