### ISSUE TITLE
[FE] My VA - Health Care update: Add new Marion/Fort Wayne health system as Cerner in My VA (May 2023)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39136]
## Background 
Marion/Fort Wayne health system is being added as a Cerner health system in May 2023.  We will need to add this to the list of Cerner facility IDs that we have, and update the copy of the Cerner Alert. 

### **NEED TO GET THE FACILITY ID FOR THIS**

> **ID TBD** - Marion/Fort Wayne: Go-live -- 5/6/2023 (Note: not clear to me whether these are separate or one health system)

## Tasks
- [ ] [FE] Add filtering so Cerner alert will now show for Marion/Fort Wayne. The facility number is **TBD**.
- [ ] [FE] Update the copy in the alert  (Copy and logic may be revisited before this implementation - [Ticket #39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by ajakabcin** [comment]
Closing - this work was originally postponed and then later the process for adding Cerner facilities changed to be managed through a drupal integration.
