### ISSUE TITLE
[04/01/22] Align Current Text Message Templates with Messaging Template Policy

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#39148]
Text messages are broken into segments at 160 characters, which is contributing to large delays in time-sensitive communication between veterans and healthcare providers. To mitigate the issue, VEText should align text messages with the existing text message policies.

- [ ] Edit down messages above 483 characters

- [ ] Ensure messages follow text message policies

- [ ] Update excel spreadsheet for leadership

**Comment by lindsay-insco** [comment]
Down to 160 templates over 4 segments
