### ISSUE TITLE
[03/25[22] Draft Vetlink Memo

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#39146]
Include the following content:

- [x] We are aware of the VetLink situation and the potential expiration on Wednesday and you are looking for a solution should this happen.

- [x] Unfortunately, VEText is not made to replace VetLink

- [x] We recommend you reach out to other sites with contingency plans already in place to look at ideas, or potentially use a view only mode so that patients can view their schedules.

**Comment by lindsay-insco** [comment]
Approved draft
