### ISSUE TITLE
Platform Slack channel usage guidelines

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#39142]
## Overview

Each Platform team has both a public and private channel. Currently there are a number of non-Platform users in Platform public team channels, and members from outside the team in private channels.

To reduce crosstalk and standardize communications between Platform and VFS teams, and within Platform, we need to standardize membership in both public and private channels.

This will be done first by announcement and then by admin removal.

## Message templates

Public team channel (i.e. #platform-qa-standards)
> @channel Please be aware that this channel is only for communication by Platform team members. If you are not on a Platform team, kindly exit this channel and direct any Platform questions through #vfs-platform-support. Thank you! For more information about this guidance see: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39142

Private team channel (i.e. #platform-qa-standards-private)
> @channel Please be aware that this channel is only for communication by Platform [Team Name]. If you are not a member of Platform [Team Name], kindly exit this channel and direct any communication through [#platform-team-public-channel]. Thank you! For more information about this guidance see: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39142

Exemptions:
Platform OCTO-DE and Platform vendor leadership

## AC
- [ ] PM for each team has made announcement in Slack channels
  - [x] #platform-infrastructure
  - [x] #vsp-operations-internal
- [ ] Incorrect members have been removed
  - [ ] #platform-infrastructure
  - [x] #vsp-operations-internal
- [ ] [Update Platform Website to include `#platform-*` channels](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40374)
- [ ] [Document internal guidance for Platform Slack channel membership](https://vfs.atlassian.net/wiki/spaces/AP/pages/2167767071/Draft+Slack+Usage+Guidelines+for+Platform+Teams)
- [ ] Followup issue is created to identify and remove users

**Comment by ph-One** [comment]
Gave two notices, with the final notice going out on Tuesday, May 31st.

**Comment by mchelen-gov** [comment]
^ Refers to `#platform-infrastructure` and `#vsp-operations-internal`

**Comment by andreahewitt-odd** [comment]
Guidance Kevin Drafted: https://vfs.atlassian.net/wiki/spaces/~497183570/pages/594182160/Slack+Usage+Guidelines+for+Teams+on+the+Veteran+Facing+Services+Platform+VSP+Contract?focusedCommentId=1679720481

**Comment by mchelen-gov** [comment]
Per Leadership sync today, I am closing this issue as it includes implementation aspects and replacing it with https://github.com/department-of-veterans-affairs/va.gov-team/issues/44996 to focus on creation of guidance.
