### ISSUE TITLE
Remove references and logic for calls to V0 in vets-website

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#39153]
To ensure that vets-website is no longer using VAR Resources, we will remove the V0 endpoints.

TBD - when do we want to implement this? (after it goes live, stabilizes, etc)

AC:

consumers of vets-website can no longer route requests to V0 endpoints

**Comment by ajmagdub** [comment]
Moving to blocked until we get a notification that VAOS Service (V2) is in production and stable
