### ISSUE TITLE
Review Platform Support FAQs Outline

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#39157]
### Description

All the information is in this Slack thread https://dsva.slack.com/archives/C01AS05BQ79/p1648222149408969, thanks!

**Comment by rsmithadhoc** [comment]
@gmaciolek I'm no longer on the team that needed this, you may want to check-in with the SRE team to see if they still want to pursue it, thanks!

**Comment by lianilychee** [comment]
hi @zachclarity !  I'm weirdly unable to open the Slack convo that Ryan linked... is it possible for you to drop a screenshot here so I have context?  **OR** is the ticket obsolete and can be closed?

**Comment by lianilychee** [comment]
Didn't hear back.  Reassigning to @zachclarity

**Comment by vbellissimo** [comment]
Followed up with Zachary via Slack on 6/30/22

**Comment by zachclarity** [comment]
closing covered in ongoing Q3 work.
