### ISSUE TITLE
Remove V0 implementations from vets-api

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#39154]
After VAOS service has stabilized and we have removed routes to V0, we will want to completely remove all V0 implementations from vets-api

**Comment by cferris32** [comment]
TBD - when do we want to implement this? (after it goes live, stabilizes, etc)

**Comment by ajmagdub** [comment]
Moving to blocked until we get a notification that VAOS Service (V2) is in production and nobody is using VAR (V0)

**Comment by ajmagdub** [comment]
Vets API V0 code has been removed.
