### ISSUE TITLE
CST: Content review of claim status page 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39164]
## Description

The claim status page for a specific claim includes a timeline of events within the "Initial review" section. When there are more than 5 events, a "See older updates" button is added to the bottom of the list. When clicked, the button disappears and the remaining events are appended to the list. None of this is accessible (see https://github.com/department-of-veterans-affairs/va.gov-team/issues/38778).

When presenting this problem to the Design System Council, the final decision was

>  Pull the most recent out and then have list show or hide with number of items in the list. 

To get to this page:
1. Log in to ID.me with `vetsgov+test233@id.me` ([get password here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md))
1. Go to https://staging.va.gov/track-claims/your-claims/600219085/status in browser

<img width="905" alt="claim status tool compensation claim status page for a mock user" src="https://user-images.githubusercontent.com/136959/160178459-ed317816-3496-416f-a327-eab1f5e8d2f0.png">

Related tickets:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/38778
- department-of-veterans-affairs/va.gov-team#39206

## Tasks

- [ ] Update timeline to show one event and a button to show and hide more events

## Definition of done

- [ ] All tasks complete

**Comment by humancompanion-usds** [comment]
I attached a Sketch file and description of the contents to https://github.com/department-of-veterans-affairs/va.gov-team/issues/39206

**Comment by Mottie** [comment]
Done. Thanks Matthew & Kevin!
