### ISSUE TITLE
Design- Auth Profile - Comp & Pen Deposit Notifications - Request content & IA review

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39167]
## Background
As a designer, I want to request a content and IA review of the mockup I updated so we can get feedback to VA Profile team.

## Tasks
- [x] Create a content and IA review request for the updated Notification Preferences mockups

## Acceptance Criteria
- [x] Create a content and IA review request for the updated Notification Preferences mockups

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Hi @Samara-Strauss - a couple questions as I'm finishing up this content/IA request. Is there a specific date that content and IA work is needed by? In addition, do we have an estimated launch date and staging review date? Thank you!

cc @SKasimow

**Comment by Samara-Strauss** [comment]
>  Is there a specific date that content and IA work is needed by?

Yes, ASAP so we can communicate requirements back to the VA Profile team, who will be implementing our suggestions.

> In addition, do we have an estimated launch date and staging review date? 

No, this is something that is out of the normal collab cycle, so we won't have a staging review. As for launch date, I'm not sure what VA Profile has planned. We'll continue to talk to them about when they think this might be ready and pushed to our staging account for review by our team.

**Comment by cgednalske** [comment]
Thanks @Samara-Strauss! Here's the [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39883) for the request.

**Comment by Samara-Strauss** [comment]
Closing since the request has been put in, but we shouldn't lose track of this and keep tracking #39883
