### ISSUE TITLE
FE - Auth Profile - Bad Address Indicator - Build UI

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39162]
## Background
Build Bad Address Indicator user interface according to the mockups and front-end documentation.   Once the scope of the build is understood, this ticket will probably need to be broken apart into more discrete tasks.

## Tasks
- [ ] Build user interface
- [ ] Test

## Acceptance Criteria
- [ ] Build user interface
- [ ] Test

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Consolidated with #39342
