### ISSUE TITLE
Design - Auth Profile - Comp & Pen Deposit Notifications - Add Comp & Pen deposit to mockups

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39166]
## Background

VA Profile/VANotify is ready to support a new notification and notification preference. We need to update our VA.gov mocks and then review them with content and IA to get final content and group placement #39167. 

Here is the info VA Profile gave us as of now. **We will need to update this content per our content guidelines, so don't take this as final copy**. We'll mostly use this updated mock as a conversation guide with our internal teams before we land on anything final.

*** Related resources

- [Design documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/design/notifications-ux-decisions.md) for Notification Preferences MVP
- [Front end documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/frontend) for Notification Preferences MVP

**Group**: Payments
**Item**: C & P Deposit Notification
**Channel**: Text only

## Tasks
- [ ]  Add the new Comp & Pen deposit notification option to the Notification Preferences mockups 

## Acceptance Criteria
- [ ]  Add the new Comp & Pen deposit notification option to the Notification Preferences mockups 

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
@Samara-Strauss and @SKasimow -- Here are the links to the Notification settings mockups with the new section added ([Desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/7yJKGDb) and [Mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/rbadYmA)). I'm finishing up the Content/IA ticket now, but please let me know if any changes are needed in the meantime! 

I noticed that, overall, the different states represented in the desktop vs. mobile mockups do not match, so I'm also updating those where needed. This won't affect the content/IA ticket though, as the copy and section order stays the same throughout.

**Comment by Samara-Strauss** [comment]
> I'm finishing up the Content/IA ticket now, but please let me know if any changes are needed in the meantime!

Great, thank you! For the content/IA ticket, we are looking for input on the following:

- Group name (currently "Payments" in the mockup)
- Item name (currently "Compensation and pension deposit notification" in the mockup)
- In what order the groups should appear (currently health care > applications, etc > payments in the mockups)

> I noticed that, overall, the different states represented in the desktop vs. mobile mockups do not match, so I'm also updating those where needed. 

Thank you!

**Comment by Samara-Strauss** [comment]
Closing this since the work is done.
