### ISSUE TITLE
Content review of CST from Claims & Appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39170]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

While discussing the "See older updates" button on the aforementioned Claim Status Tool (CST) page, Allison suggested we get a **content review of the page after the design change has been made** - see https://github.com/department-of-veterans-affairs/va.gov-team/issues/39164.

To get to the page for review:

1. Log in to ID.me with `vetsgov+test233@id.me` ([get password here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md))
1. Go to https://staging.va.gov/track-claims/your-claims/600219085/status in browser
 
<details><summary>Current content of status page</summary>

![claim status tool specific claim status page with non-accessible event timeline button](https://user-images.githubusercontent.com/136959/160178459-ed317816-3496-416f-a327-eab1f5e8d2f0.png)</details>

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: Before April 7 - Claims & Appeals contract ends
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VSA Claims & Appeals
-	OCTO-DE product owner: Matt Self 
-	Product manager: Veronica Henry
-	Designer: Kevin Stachura
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #vsa-claims-appeals

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@Mottie Would you let me know when the design changes have been made and I'll review all the content here and give you edits on the page as a whole?

**Comment by Mottie** [comment]
Hi @bethpottsVADEPO, the design is still in progress. You can follow along here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/39206#issuecomment-1081112934

**Comment by Mottie** [comment]
Hi @bethpottsVADEPO, the design is still in progress. You can follow along here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/39206#issuecomment-1081112934

**Comment by bethpottsVADEPO** [comment]
Great, I'll take a look today! Thanks, @Mottie

**Comment by bethpottsVADEPO** [comment]
@Mottie Some edits for you so this aligns with our plain language standards and VA.gov style and voice (specifically addressing instances of passive voice):

(2) Initial review
We assigned your claim to a reviewer. The reviewer will determine if we need any more information from you. 
**Latest update
July 12, 2021** Thank you. We received your claim.

**Past updates (47)**
Button text: Show past updates / Hide past updates

If we can change this language, please do! And I'm wondering if by "correspondence" we mean "supporting evidence" or "additional information." If that's the case, would you change that wording? "Correspondence" isn't very plain language, so I'd like to find out what we mean by that and if there's any alternative phrasing. But please do go ahead and at least make the other edits here:

You or someone else submitted correspondence. We'll notify you when we've reviewed it. 

@DanielleThierryUSDSVA for awareness

**Comment by bethpottsVADEPO** [comment]
@Mottie Sorry, I overlooked the alert under **(5) Complete.** Does this new text meet the messaging needs?:

**We don't know yet when we'll be able to make a decision on your claim** 
To decide your claim, we need to complete your in-person claim exam. But we don't know yet when we'll be able to schedule your exam. We stopped scheduling in-person claim exams because of COVID-19. Now we're starting to schedule these exams again in many locations.
[Find out where we offer in-person exams now]

**Comment by Mottie** [comment]
The alert under (5) isn't part of the update, but I will gladly make that change.

**Comment by Mottie** [comment]
> And I'm wondering if by "correspondence" we mean "supporting evidence" or "additional information."

I forgot to add that the content after the date is provided by the API. I don't have any control over that content.

**Comment by Mottie** [comment]
Actually @bethpottsVADEPO, the "Correspondence" part of the sentence is from the type of file that was uploaded. Maybe it'd be better to switch that out with the actual file name, e.g. "some_file.pdf".

**Comment by bethpottsVADEPO** [comment]
@Mottie Interesting... that might be better? Unless the file name is long or complex. If there's a long list of files uploaded and they all have different names, some long, some short, etc., would that start to look too busy and feel overwhelming? Is there any way, instead, to substitute "more information" for "Correspondence"? I think that phrasing would be general enough. 

You or someone else submitted more information. We'll notify you when we've reviewed it.

**Comment by Mottie** [comment]
Sorry, I should have been more clear. In the mock data I have available, "Correspondence" is one file type, other types I see are "VA 21-526EZ, Fully Developed Claim (Compensation)" and "Buddy / Lay Statement". There could be more. Here is a screenshot of it showing the file name, but if the file name doesn't exist (a case in the mock data), it then shows the file type
<img width="542" alt="Screen Shot 2022-03-30 at 12 57 18 PM" src="https://user-images.githubusercontent.com/136959/160900537-3e77dc8e-1c73-4fcc-89fe-145537f3db81.png">

**Comment by bethpottsVADEPO** [comment]
@Mottie I see. I like this idea of yours. Though it's a little busy, it's better than a generic message next to each date. That doesn't seem very helpful. I also think we could cut the repeated line "We'll notify you when we've reviewed it." Do you think we need to keep that message somewhere? If so, I'll look at what might make sense. But let's simplify the text across from each date to this (change "others" to "someone else"):

You or someone else submitted *file name or type*.

**Comment by Mottie** [comment]
Seems a bit cleaner. I tried to add more examples of other event types... I had to guess at some of the dat
<img width="566" alt="CST initial review and evidence gathering sections expanded, both have older updates expanded" src="https://user-images.githubusercontent.com/136959/161097390-0143488f-776b-4dff-8693-0def5fce9751.png">
a

**Comment by bethpottsVADEPO** [comment]
@Mottie I'm still considering whether we just strike that sentence altogether or try to nest it somewhere in No. 2. Do you know how we notify the Veteran when we review an update/submission? Do they get an email notification? Snail mail? Or are we just saying we post the update here in the list of past updates? (Side note: you'll still change "older" to "past," right?)

**Comment by Mottie** [comment]
I'm not sure how Veterans are notified. I'm pretty sure they _always_ get a snail mail copy. I don't know about other notifications.

And I totally missed changing "older" to "past", thanks!!

**Comment by bethpottsVADEPO** [comment]
Looks great! Want to double check that you changed the corresponding button to match "Hide past updates":

"Show past updates."

**Comment by Mottie** [comment]
LOL sorry.. in the code, I'm only changing the "Show" or "Hide" part of the button text, so they both were changed at the same time 😄 

<img width="589" alt="collapsed show past updates button" src="https://user-images.githubusercontent.com/136959/161143410-896fd85f-fa62-4150-91cd-c88a48c1dbb9.png">

**Comment by Mottie** [comment]
Done. Thanks Beth!
