### ISSUE TITLE
Access for Cam Bui

### ISSUE THREAD

**Issue by ncbui** [department-of-veterans-affairs/va.gov-team#39174]
**COR Name**
Cecilia Lee

**Vendor Onboarding Representative Name**
Liberty IT - Michael G. Lovejoy

**Your Name**
Cam Bui

**Your Email**
[cam.bui@thoughtworks.com](mailto:cam.bui@thoughtworks.com)

**Name of Your Team**
Digital Health Platform (DHP) Team, Developer, Thoughtworks

**Service(s) You Want Access To**
SOCKS

**Public SSH Key (for SOCKS requests only)**
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChZhUjndAKFP9rLdNIie8tZlFrXWTndA4qnmluszaXRMlaxAf2mg1mVUit0I2PFTlzGhJfhuwJB8hlmh+c02U0Z+zbHDIFC7cnwNHuAOHSXdRWbK4A1Q1xmiP2DLAPZetSOZqGkkUewElgc+YMcpd6DkCsi3M0oCEe7esqQCpLxdyCDMAq1ykpIoyQIRTklP7jexsR8FlTBkvWLwcfczFgpeL8gAaYCQDT4C9pjamen37b9wVfy8LGpCrY9aKDBs1RdhG8AabIBdc92QJBSw5FddOVki9kwB8g5oIzYEH8N8vrhGQZOrQvedxT3z56413HsEOug0qRRqOZvsy1EVVWaRhugU2xTe3fC4XgJxqUiz8H81nlG+mSvw0+NoC8XRTTCFnJagZIdj7E1kh1DlqQNvXq5q7Nr0NbauX/PfZmLhEHqrl/U7ZCctq1GE8W0HmWs12kTHlB0leGNgvjq/dScMeLbnNJMQPBlgElAHvhUJRQ2KdKBLfrqZSycloHOL0=cbui@Cams-MacBook-Pro-2.local

**Desired AWS Access**
For now I just need an AWS account and access to logs/metrics/jenkins via SOCKS

**Access Expiration**
ongoing

**Comment by oseasmoran73** [comment]
Hi @ncbui 

Please use our new request form for [AWS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D)

I will process this ticket for SOCKS only

**Comment by ncbui** [comment]
Thanks @oseasmoran73, will submit using that form
