### ISSUE TITLE
SOCKS access for Cam Bui

### ISSUE THREAD

**Issue by ncbui** [department-of-veterans-affairs/va.gov-team#39179]
### Your Name

Cam Bui

### Your Email

cam.bui@thoughtworks.com

### Your Role

Developer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5ebrf+CtT43dk4K4QBMTdgGm8n5zaPkMbnhOHAFa41qjN8ohKy1qIl1i1OJ2uklkN0sOYLGu8yYiApzHnt/mnqA5ZqOo6zrTofaT9nK8j1go78o36LsjezpYgocv2S8Q1QBWvUr+kChk3PlFpriZKjVQsS5HaIkwHLRlqb8Oa+Mit26q/dzwKKTHVaqfBv1SDxyAiyAl2vxI/Y/d1eXJwsG3WE6BzUxfHlI4KY61QDaW3K5CIRZStUvx87wo42yEg01E4EZv5W9TB7l7ChR79BR00BMEBNlrmw0at29xqz+YshJDku4CWPulalO9yylJamg+79kDkY5uddruQBc2a0D/K5++G3MloTEdsjBLlExolH5xhBiiTnYwXQiF3NE2yhErBtc7ghIxfj0r2Qc1TaG1Gflx4+jwMkIXbhnr9OrPQCoYvhtHfpAxEJYvqZh+ion2DKxBJnm7JBmDnZCMf4wB8TfLBoa+t6DSDEQTlLDzUb0lwcCpZdkTXPjuosT8= cbui@Cams-MacBook-Pro-2.local

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
