### ISSUE TITLE
Manually trigger old workflows

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#39180]
**User Story**: as a VFS developer I want to be able to rerun a workflow for any commit, not just a commit that is among the most 100 recent, so that I can deploy or test my code as needed.

Right now a user is only allowed to manually trigger a workflow if the commit is within the most recent 100 commits; we should allow users to re-run older, valid commits.

**Comment by laineymajor** [comment]
@it-harrison can I close this?

**Comment by it-harrison** [comment]
> @it-harrison can I close this?

yes
