### ISSUE TITLE
[DOCUMENT]: GIBCT SCO - Dear SCO letter images need alt text

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#3918]
## Description

VA 508 office has identified the [Dear School Certifying Official](https://www.benefits.va.gov/GIBILL/docs/fgib/107_TandF_SCO_letter.pdf) PDF as needing alt text for two images. Screen shot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Remediation Resources
* [Add alternative text to a shape, picture, chart, SmartArt graphic, or other object](https://support.office.com/en-us/article/add-alternative-text-to-a-shape-picture-chart-smartart-graphic-or-other-object-44989b2a-903c-4d9a-b742-6a75b451c669)
* [Add Alternative Text - Adobe](https://www.adobe.com/accessibility/products/acrobat/pdf-repair-add-alternative-text.html)

## Acceptance Criteria

* Screen readers announce image alt text properly

## WCAG or Vendor Guidance (optional)

* [Non-text Content: Understanding SC 1.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html)

## Screenshots or Trace Logs
![Screen Shot 2019-12-03 at 10 08 16 PM](https://user-images.githubusercontent.com/934879/70112620-85075600-161b-11ea-91ed-af4d5f5ae186.png)

**Comment by desireeturner** [comment]
@1Copenut The Education team has been informed of this issue.

**Comment by TamGIBill** [comment]
Corrected 508 issues.

**Comment by 1Copenut** [comment]
Thank you Desiree. I sent the update to the VA 508 office.

**Comment by 1Copenut** [comment]
@desireeturner I heard back from the VA 508 office that these were fixed. I'll close this issue, and open a few new ones for some broken links and list.

**Comment by TamGIBill** [comment]
This was resolved a while ago.  The link is no longer valid.  The document has been removed.
