### ISSUE TITLE
Develop Product List

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#39189]
## Issue Description
Develop a product list based on the findings of the [Define Solution ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/39188).

(Ticket will be updated when the solution is defined)

---
## Tasks
- [ ] Develop a solution according to the design/plan

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by CBonade** [comment]
https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0

Current list in progress - a few columns are complete and research for the values for other columns is well in progress.

**Comment by pjhill** [comment]
We need to add some details to this ticket about the process that we're using to develop the list. We also need to call out the schema when it is finalized.

**Comment by CBonade** [comment]
Process:

1) Decide on the list of actual products that are going to make it on the list. Step one of this was to take the Governance Team's most recent list here: https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0 . This list, is in terms of features and it was determined after conversations with the Governance Team, that the "parent product" column would be a more true representation of "products" on va.gov as the list was derived from interviews with the teams.

2) Decide on a schema for the list and create the columns accordingly.

3) Further discussions with both the Governance Team and Release Tools pointed us to that a likely starting place for deciding how to link products to code is the manifest.json files that exist in vets-website. So we start by generating a list of manifest files that exist and attempting to match them up to our current list. What's leftover are potentially orphan products.

4) Identifying Orphan Products that belong on the list. The starting place for this is manifests that we have that do not have a product name that we can link to. The first step of this process would be to investigate the code surrounding each of these manifests to determine if they seem like they are products based on the code and their function. The second step would be checking the root url of each of these and seeing if this product still appears to be live on va.gov. If the product is live, it is likely an orphan product that has not been decommissioned, but no team claims ownership to. These orphan products are then added to the list.

5)  Fill out the list sourcing information from existing lists, context from the code in vets-website, and directly inquiring for information with other teams.

6) Upload CSV to GitHub



As of this writing, we are knee-deep in step 5.

**Comment by CBonade** [comment]
The list is currently populated with most of the data that can be obtained without involving other teams/outside sources. Our next steps will be sharing this out with other teams to get their data aligned to it that is necessary for their specialized use cases.

**Comment by CBonade** [comment]
As the list is created and moved into GitHub, the list should be considered "done" as far as an MVP is concerned. There will still continue to be filling and maintenance, but the bulk of the filling is completed.

**Comment by pjhill** [comment]
I think the parameters of the list are fairly settled, and we have seeded it with an MVP amount of data. I'm leaving this in `Review` for now because our ADR specifying the behavior of the product list is still receiving comments, and this ticket's main body needs some updates to reflect the work.

**Comment by pjhill** [comment]
This ticket is OBE at this point.
