### ISSUE TITLE
Bug: Process list and Background only alert web components are displaying incorrectly in Storybook when viewed in Safari

### ISSUE THREAD

**Issue by GnatalieH** [department-of-veterans-affairs/va.gov-team#39181]
## What happened?
The Process list and Background alert (without and with icon) web components are not rendering properly in Safari when viewed in Storybook.

## Specs:
Safari Version 15.1

## Steps to Reproduce
View the following in Safari 15.1:

- [Process list web component](https://design.va.gov/storybook/?path=/docs/components-va-process-list--default). Numbers in steps are not displaying. 
![Screen Shot 2022-03-24 at 10.04.06 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/1c97c39a-1fc8-4914-8de6-1aab90d9e7e2)

- [Background only alert web component](https://design.va.gov/storybook/?path=/docs/components-va-alert--background-only). The text is pushed too far down and doesn't align properly, vertically. 
![Screen Shot 2022-03-24 at 10.04.43 AM.png](https://images.zenhubusercontent.com/6111980ab6b167c27c9a5723/64073db6-d202-408d-a94d-c160f0d76c18)

## Desired behavior
Reference these components in Chrome to see the desired style.

**Comment by k80bowman** [comment]
These issues seem to have been resolved. Closing.
