### ISSUE TITLE
[FE] Replace Last 4 with DOB in LoROTA Login

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39194]
## Description
We need to replace the capturing of the Last 4 of the SSN with the DOB for LoROTA login.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Work is mostly complete. Waiting to hear back on what the backend will want for format and some outstandting UX questions

**Comment by brianseek** [comment]
Moving to closed since this is merged and there is already a UX review/wireframe ticket in the mix and this is still off behind the feature flag. 
cc @loripusey
