### ISSUE TITLE
LoROTA Security Updates

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39193]
## Dependencies
[CHIP Epic](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/698)

## Feature Flag
check_in_experience_larota_security_updates

## Description
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/c443e6e7-5700-4ac8-9d45-e7c76ea85339)

These 3 will need to be completed by the CHIP team. Here is their [Epic ](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/698)to handle these security updates.
    - Hash the Last Name and DOB in LoROTA datastore (see note from Cody below)
    - Only populate LoROTA data when it is about to be presented to the Veteran. The initial LoROTA record creation will not contain any PHI/PII.
    - Proactively remove LoROTA entries as soon as possible – if the record needs to be retained until the time of the appointment, remove all unneeded PHI/PII.

**Comment by loripusey** [comment]
@acrollet I moved the "delete tickets to a new epic"; as soon as CHIP is done QA'ing this [ticket](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/941) do you think maybe next Sprint we can get our LoROTA work (minus delete) out to production?

**Comment by acrollet** [comment]
> @acrollet I moved the "delete tickets to a new epic"; as soon as CHIP is done QA'ing this [ticket](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/941) do you think maybe next Sprint we can get our LoROTA work (minus delete) out to production?

yep!
