### ISSUE TITLE
CHIP ----- [BE] Populate LoROTA Data on Demand ONLY

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39197]
look at ticket 696

## User Story
As the VA, we need to only only populate LoROTA data when it is about to be presented to the Veteran so that it is more secure. The initial LoROTA record creation will not contain any PHI/PII.

## Acceptance Criteria
- [ ] Only populate LoROTA data when it is about to be presented to the Veteran. The initial LoROTA record creation will not contain any PHI/PII.

## Tasks
- [ ] Deploy and test on staging.

**Comment by acrollet** [comment]
This work will happen in CHIP - see https://github.com/department-of-veterans-affairs/chip/issues/698 and https://github.com/department-of-veterans-affairs/chip/issues/696
