### ISSUE TITLE
Identify existing comm channels for external services

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#392]
## User Story
As a VSP Triage team member, I need to know the communication channels we have access to for updates from external services that VA.gov and VSP depend on so I can be proactive about managing user impacts from changes to these services.

## Goal
- VSP team is aware of changes to external services we rely on _before_ they occur and thus can identify potential user impacts early
- Identify incoming outage schedules.

## Acceptance Criteria
- [x] All external services we depend on for VA.gov and VFS are documented
- [x] Existing channels of communication for each of those services are identified and documented
- [x] Gaps in communications are identified
- [x] Documentation exists in GH

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Here's a good [start](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Data/README.md)

**Comment by omgitsbillryan** [comment]
Here's more, which I think has some duplication of what @kfrz mentioned above.

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Data/README.md

**Comment by alexpappasoddball** [comment]
Consolidate and create a team focused document and identify other gaps.  These documents are stored in the Triage github.

**Comment by kfrz** [comment]
[Here is a table](https://airtable.com/shrjN4BllVN6412Ix) including all upstream services and links to their Docs, Contacts, Monitoring, and Outage information (where known).
