### ISSUE TITLE
[PM] Onboarding: Sharon Kasimow 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#39204]
## Background

Welcome, Sharon! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Christina Gednalske (Designer)
- [ ] Liz Lantz (Designer who floats between My VA and Profile)
- [x] Adam Whitlock (Frontend)
- [x] Tom Harrison (Backend)

### Meet with Samara

- [x] Intro call
- [ ] Any other calls we need to get fully onboarded to project and process

### Project onboarding

- [ ] Go through all documents in [the "Product portfolio" section of Marci's onboarding doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/profile-team-transition-2022.md#product-portfolio)
- [ ] Review MHV Research plan and findings

### Profile overview

Here are some helpful documents to review on the profile. It would also help if you log into staging and check it out for yourself to get a sense of the full section.

- [ ] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [ ] [Profile folder and list of products](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)
- [ ] [Profile roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/profile-roadmap.md)
- [ ] Staging info

### Log into staging and check out the profile
You can use the following info to get into staging:

Go to VA.gov.
- Sign in to staging with user 36 ([staging user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)).
- Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.
- Existing profile products

Here are some of the products that currently live within the profile.

- [ ] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/README.md)
- [ ] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [ ] [Preferences project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)

### Current projects

Here are the projects we currently have going on the profile team.

- [ ] [Personal information revisions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md)
- [ ] [Bad address indicator](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/README.md)

**Comment by SKasimow** [comment]
Updated to include some additional relevant documents to review....

-S

**Comment by Samara-Strauss** [comment]
@SKasimow can you add an estimate to this ticket and remove the "needs grooming" label?

**Comment by Samara-Strauss** [comment]
@SKasimow can we close this? I think we can consider you onboarded even if you haven't done things exactly as outline in this ticket.

**Comment by SKasimow** [comment]
yup...closing
