### ISSUE TITLE
Visuals for how MHV will look on va.gov before the MHV landing page is released on va.gov

### ISSUE THREAD

**Issue by tmulrooney-va** [department-of-veterans-affairs/va.gov-team#39219]
We need a visual (flow diagram) to help frame the conversation around Drupal pages...

**Comment by jonathanjnelson** [comment]
[Please see Mural board ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1648505461076/8e689d3bbfe651de79cbc3ae8d02c8944b06a169?sender=jonathannelson8855)
