### ISSUE TITLE
[DISCOVERY] Complete A thru C in Lebanon_PA Health Services Playbook [BA] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#3921]
## User Story 
As a Content Writer, I need Health Service guidelines input in the Lebanon-PA Playbook, so I can write the content to match the guidelines and requirements of the API and page.

## Goal/Objective
- _Complete 5 of 54 total guidelines for all Health Services Content for all associated Lebanon clinics _

## Objectives or Key Results this is meant to further
- _Reduction in overall word and page count and reduce click through _

## Acceptance Criteria
- _The following Health Services criteria tabs are complete for content and API creation_
- [x] _Addiction and substance abuse treatment_
- [x] _Audiology and speech_
- [ ] _Cancer care_
- [x] _Cardiology_
- [x] _Caregiver support_

**Comment by cblakelyGCIO** [comment]
All services above have been completed.  There was no tab on the Master Playbook sheet for cancer care.  Waiting for decision on whether we should duplicate the template and create an additional tab on the master.
