### ISSUE TITLE
Investigate using DEX locally with ARGO

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#39223]
**Problem we are trying to solve:** 
Add Keycloak to Argo's Dex (add Keycloak to the dex sso config) 

Currently we use Keycload as a provider, 

We would like to see if Dex is possible.  (Argo is being used in product with Argo), we need to determine if this will work for our needs.  

**Acceptance Criteria**

Verify that Dex works 

- [ ] Verify bearer token from Keycloak still works with argo when using dex

**Comment by RachalCassity** [comment]
The Keycloak Access Token will not work work with when Dex is the Argo provider.
