### ISSUE TITLE
Adding [Cary Brizendine] to DSVA Slack

### ISSUE THREAD

**Issue by zinalpatel09** [department-of-veterans-affairs/va.gov-team#39245]
# Description

This request is to add Cary Brizendine (cbrizen@thoughtworks.com) as a Full member. Please note: it looks like Cary is already in DSVA but her account is deactivated so maybe we need to add her again? 

Description: Cary Brizendine is a project manager on the Long Covid project. In order to do her job efficiently, she needs slack to help him keep up to date on any communication and activities for the project.

Please also add Cary to these Channels:

#health-care-products-all-teams
#long-covid-public

**Comment by LEHigley** [comment]
already a full member
