### ISSUE TITLE
AWS Parameter Store path for DHP team

### ISSUE THREAD

**Issue by yonidoronpeters** [department-of-veterans-affairs/va.gov-team#39259]
Hello, the [Digital Health Platform team](https://github.com/orgs/department-of-veterans-affairs/teams/digital-health-platform) need our own path in the AWS Parameter Store for storing secrets in vets-api. Would you be able to create a parameter store path under `/dhp/` for us please?
Our developers are still in the process of creating an AWS accounts. But I will provide the names of devs who need access to this path in a followup request.
My AWS account (already created) email is: Jonathan.Doron-Peters@va.gov
Thank you

**Comment by jsgarmon** [comment]
Hi @yonidoronpeters : is this purely for vets-api integration? If so, we'd probably use the normal vets-api root path, so you can have parameters in `/dsva-vagov/vets-api/dhp/*`.

**Comment by jsgarmon** [comment]
This is completed, you should now be able to view and create parameters in `/dsva-vagov/vets-api/dhp/*` and `/dsva-vagov/vets-website/dhp/*`.

As your teamates request AWS access, they should request to copy your permissions so that whoever picks up the ticket knows which groups to add them to.

**Comment by jsgarmon** [comment]
We use the account one for most things. If using the Console, you'll select "My current account". If through the API, you'll use the key alias `alias/aws/ssm`.

**Comment by jsgarmon** [comment]
This appears to be working, so closing this issue.
