### ISSUE TITLE
AWS access for Cam Bui

### ISSUE THREAD

**Issue by ncbui** [department-of-veterans-affairs/va.gov-team#39258]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Cam Bui

### Your Email

cam.bui@thoughtworks.com

### Your Team, Role, and Company

Digital Health Platform (DHP) Team, Developer, Thoughtworks

### Desired AWS Access

Copy permissions from @yonidoronpeters 

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
**For AWS Access**
User: Cam Bui
COR: Cecila Lee
 VOR: Liberty IT - Michael G. Lovejoy 
Approval needed: [@department-of-veterans-affairs/operations-aws-approvers](https://github.com/department-of-veterans-affairs/operations-aws-approvers)
 Admin level: no

**Comment by td-usds** [comment]
Validated with VOR, access approved

**Comment by jsgarmon** [comment]
User created in DSVA AWS, and first-time login instructions sent via Slack. Please respond to the Slack message if you have questions or issues.
