### ISSUE TITLE
Extract platform-level Github Action workflows from vets-website and content-build so they can be remotely executed

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#39265]
**All Github Actions currently live paired with their respective repositories**
Big picture: Identify all within the central repo and when an app asks for a CI -> Build, Release, Deploy + Archive

- [x] Identify the 'uses' within the respective workflows

- [x] Try adding them as a workflow/install type to be able to grab from a repo of its own (= centralized repo)

- [x] Update and test one of the workflows tying back to the 'global' repo

- [x] Extract github action workflows into a centralized repository so they can be remotely used

- [x] Update deployment and CI actions so they can be used in multiple repositories
*If an application were to leave vets-website, could it still use the same deployment workflow?

**Deliverables**

- [x] ADR for rearchicting Github Actions workflows so they so they can be remotely used

- [x] Supporting documentation about what updates need to be made to extract workflows from vets-website and content-build

- [x] Execution of the re-architecture solution

**Comment by mydesignrocks** [comment]
@laineymajor - this seem to require to be discussed based on how we progress into monorepos and discuss the architecture accordingly. I have been intending to make some progress with this ticket first and then circle back with the plan of action here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39205

**Comment by mydesignrocks** [comment]
common actions has been identified. As next steps, we need a central repo of sorts and publish it.
@mchelen-gov - can you please help create a public github repo where all workflow action dependencies can be stored. (if this ask should go through a different channel, please advise. I will drop a note in slack #platform-release-tools as well). thanks!

**Comment by mchelen-gov** [comment]
> common actions has been identified. As next steps, we need a central repo of sorts and publish it.
> @mchelen-gov - can you please help create a public github repo where all workflow action dependencies can be stored. (if this ask should go through a different channel, please advise. I will drop a note in slack #platform-release-tools as well). thanks!

see https://github.com/department-of-veterans-affairs/github-user-requests/issues/new/choose to change repo perms. tag me on ticket if approval needed

**Comment by mydesignrocks** [comment]
Hi @mchelen-gov one more help please. I see this is grayed out to me when I am trying to release an action to market place to be able to consume it as a global action by other workflows. ![image](https://user-images.githubusercontent.com/69813558/166724986-772a1f8c-7f98-4f98-a2ed-820a75d240d3.png)

wondering if that would be you to agree to it or pass it along as a request (cc you) to the github team. thank you!

**Comment by mchelen-gov** [comment]
Hmm nope, I think you need to ask in #github_information

**Comment by mydesignrocks** [comment]
After successfully creating a new global repo and moving one of the actions tied to `security-audit`, these are the findings for implementing custom actions:

1. Actions should be sequential to create runs and wrapped into single workflow
2. Secrets or variables scope is not available in custom action
3. Checkout repos are conflicting
4. Found less independence actions in vets-website and content-build, which basically translates to the effort 
5. References of previous actions in workflow can get repetitive

**Comment by mydesignrocks** [comment]
Identified composite actions and moved them to a global repo.
they are: aws-credentials, security-audit, configure-bigquery, init-data-repo, slack-notify
1. QA actions tied to bigquery and init-data-repo are not in use for now within vets-website
2. aws-credentials is already a market place action and not a huge gain in moving it over to global action
3. moving security-audit and slack-notify
https://github.com/department-of-veterans-affairs/platform-release-tools-actions/pull/4/files

**Comment by mydesignrocks** [comment]
this is now complete and all the new single app builds and what not can use the composite-actions from here: https://github.com/department-of-veterans-affairs/platform-release-tools-actions
