### ISSUE TITLE
[FE] Direct User How to Update their Contact, Emergency Contact, and Next of Kin Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39273]
## User Story
As a Veteran, when I am completing my pre-check-in workflow, if I have some updates to my contact, emergency, and/or next of kin information, I would like to understand how and where I can make those changes so that I will know what the next step is.

## Wireframes
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/5D647D7E-68C0-4E3B-948C-162CE11A9EB0
- Put edit message in accordion (content stays the same)
    - Default accordion to expanded
    - All other accordions will default to closed
- Move "Go to your appointment details" link to under the appointment date/time
- Move the "Bring your insurance" message to under appointment date/time  
- Put "Bring your insurance" message in blue box w/ info icon
- Make "What if I have questions" an according

## Workflow
- Given I
    - Am a Veteran who has received a link to complete pre-check-in for an appointment
- When I
    - Complete the pre-check-in process
    - Have answered "No" to one or more of these questions
        - "Is this your current contact information?" 
        - "Is this your current emergency contact?" 
        - "Is this your current next of kin?" 
- Then I
    - See messaging that indicates how to update my information based on to which of the 3 questions I answered "no" 
        - For contact info
             - See messaging that tells me I can either update my info in my VA profile or with a staff member on the day of my appointment
             - See a link to my VA profile (not just the login page but my profile page)
        - For EC info
             - See messaging that tells me I will need to update the information with a staff member on the day of my appointment
        - For NOK info
             - See messaging that tells me I will need to update the information with a staff member on the day of my appointment

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by loripusey** [comment]
@acrollet Do you know why the team was not able to get to this work this sprint?
cc: @sarahknoppA6

**Comment by loripusey** [comment]
Thanks, yep, I recall that. We probably should not have pulled this in and should not have involved Dan in the discussion on Thursday seeing as how Friday was his last day.  There was a lot of churn happening in multiple directions on this one.
cc: @sarahknoppA6

**Comment by acrollet** [comment]
Yep, Dan just confirmed that he wasn't able to begin dev work on this.

**Comment by brianseek** [comment]
@zach-park @ytsaoca This is ready to review see screen shots below of several of the message scenarios:

![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (7).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/aaa86267-0d68-42c2-8aa0-b37584a89479)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (8).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/b71432c7-a158-4ad9-bc09-f3059b29f819)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (9).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/06470da7-f140-4226-918b-75711c25a785)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (10).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/694f383d-d3af-4693-ab47-835ca3620b70)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (11).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/a5a7a94e-a76c-4cfd-a0ad-8013d5f6d07c)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (12).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/b69904ff-90df-4fdd-b0ef-7d69cd75c4d3)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (13).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/91cc549f-5195-4b1d-bdd2-03b9625a7b2a)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (14).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/ab000d10-73a6-40c0-b996-539a8a403098)

**Comment by brianseek** [comment]
some of those screenshots show a yellow border and blue fill, that was just my inspector getting in the way. Let me know if you want new screenshots for those but the content is really what matters in the different variations.

**Comment by loripusey** [comment]
Looks good
