### ISSUE TITLE
[UX] Pass off Product Guides to the Contact Center after Updates for LoROTA and Edit Messaging

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39286]
## Description
The product guides need to be passed off to the contact center. [Here is the process that we need to follow to do that](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md). We need to set aside time for someone to do this work (doesn't necessarily have to be UX).

## Acceptance Criteria
- [ ] Follow the contact centers process for passing off the product guides
    - Set up video meeting
    - Have meeting to review Product Guide
    - Create GitHub ticket

**Comment by sarahknoppA6** [comment]
Regarding the video meeting for the product demo- Stephen mentioned he will be recording a product demo this week. We may want to check w/him to see what he is recording- not sure if it will be usable for this purpose, but could possibly reuse part of his script/scenarios as a starting place.
