### ISSUE TITLE
[UX] Gather and package final translation documents based on New Priorities

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39281]
We need to generate three documents to deliver to the State for translation estimates: 
1) JSON file of content in the app (completed in ticket xxx)
2) JSON file of content in SMS texts
3) Excel file of content in poster

Tasks
- [x] Update JSON file to send to the State Department after we design the edit messaging
- [x] Update the content review spreadsheet after we design the edit messaging
- [x] Zip all JSON files
- [x] Send zipped file to Danielle

##Acceptance Criteria
- [x] Zip file of all content to be translated delivered to Danielle in a slack message
- [x] Total word count documented and delivered to Danielle

**Comment by niradatta1** [comment]
Need to remember to add final word count total as well.

**Comment by niradatta1** [comment]
Zipped files sent to Danielle (below). Contains two JSON files: (1) content from the SMS texts and poster ( word count~285) (2) content from the in-app content in pre-check-in / check-in (word count is ~1096)
[https://app.zenhub.com/files/133843125/24d20f33-e793-4370-8cca-91bfefbbc17e/download](https://app.zenhub.com/files/133843125/24d20f33-e793-4370-8cca-91bfefbbc17e/download)
@loripusey @sarahknoppA6 @brianseek @zach-park
