### ISSUE TITLE
Document Platform wide meetings

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#39282]
## Description
Platform wide meetings are those that include more than one Platform team. A central reference is needed for both OCTO and Platform vendors to have awareness of meetings that are occurring, know when they occur, who to contact, and where to look for notes.

## AC
Meeting [listed](https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings) with time & date, participants, maintainer, and link to meeting notes
- [x] OCTO-DE Platform Crew Weekly Meeting
- [x] Platform Office Hours
- [x] Platform Leadership Sync
- [x] Platform End of Sprint Demos
- [x] Console Sync
- [x] Team of Teams
- [x] VA.gov Design Sync
- [x] Architecture Working Group
- [x] Engineering Council
- [x] Engineering Huddle
- [x] Security Working Group
- [x] Design system council

**Comment by andreahewitt-odd** [comment]
Console Sync mondays 11:30 ET

**Comment by mchelen-gov** [comment]
@andreahewitt-odd who are the participants and owner of console sync?

**Comment by mchelen-gov** [comment]
@troymosher @td-usds is Security Working Group still active?
