### ISSUE TITLE
[Content & IA Design] Combined debt portal

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#39294]
**From epic:**  
Based on our meeting with Jill from a couple weeks ago, our team is moving towards combining the VBA Debt Portal and Medical Copay Tool into one VA Debt Portal. We've previously discussed IA constraints that prevented us from releasing a combined portal as part of the MVP, so I'd like to brainstorm how we can combine these tools. 
  
## Supporting Artifacts
- Link to product outline: [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/product_outline.md)
- Link to or attach user flows: [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1645453970389/5712442eb61e558df96599ac35c346436aafcc9c?sender=riley5075) | [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_va_debt_portal/design/user-flows)
- Link to prototype or mockups: [UXPin prototype](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages//simulate/no-panels?mode=i)

## When does this work need to be done?
- Research starting:  
- Estimated launch:

## About your team

- Team name: The Debt Resolution Team
-	OCTO-DE product owner: @mattpointzxer0 
-	Product manager: @denisecoveyduc 
-	Designer: @rileyorr and @kevinstachura 
-	FE engineer: @Dr-Pongo and @OptionSelect 
-	Product/team Slack channel: #vsa-debt

**Comment by mnorthuis** [comment]
@rileyorr Can you update the top with a link to the latest and greatest prototype for us to work off of?  Thank you!!

cc @kevinstachura

**Comment by rileyorr** [comment]
@mnorthuis I just added links to the prototype, user flows, and product outline!

**Comment by mnorthuis** [comment]
Hi @rileyorr!  I am picking this up today, so I will reach out if I need anything.  Very sorry for the delay!

**Comment by mnorthuis** [comment]
@rileyorr @denisecoveyduc - @DanielleThierryUSDSVA and I met yesterday to talk about the shifting of pages from health care to debt, and the content changes needed to better accommodate the combined debt experience. 

High level notes that we can discuss today:
- The top level static page will be modified as follows
  - The H1 and URL will change to include the reference to copays
  - The content on the page will be restructured to focus on 3 actions (in priority order):  manage your debt and copays, pay your debt and copays now, and request financial help with your debt and copays
  - Some of the content on the existing page may be moved to resources and support, and some content may be moved to a new page for requesting help (see next bullet)
- We are proposing a new static page above the FSR to provide information/content that is currently placed on the existing debt landing page, 2 pages within the copays section, and content from the existing wizard on the FSR
- All URLs for pretty much every page in this experience will change from what they are today due to the above changes
- We have not reviewed detailed content and link labels, but there may be changes there 
- Entry points are not established yet

One additional note, in a recent conversation, I learned that we may not be able to bypass the static landing page and deep link authenticated users into the specific areas of the tool (i.e. copays vs debt). This is something that we should discuss so we can either find a solution, or alter link labels at entry points.

The initial draft of the IA can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/debt-portal.md

**Comment by rileyorr** [comment]
Following up regarding our discussion of deep links: 
- When I'm authenticated (I used test-user-1) and attempt to navigate directly to a debt's detail page within [the VBA debt portal](https://staging.va.gov/manage-va-debt/) a site 404 returns
- I'm able to successfully navigate directly into a facility's copay detail page within [the medical copay tool](https://staging.va.gov/health-care/pay-copay-bill/) while authenticated (I used test-user-81)

This information might be useful during our discussion with Andrew, Brandyn, and Robin tomorrow afternoon. Thanks for setting that meeting up @denisecoveyduc!

**Comment by mnorthuis** [comment]
@rileyorr @denisecoveyduc I was able to deep link to both a copay detail and a debt detail page.  We should see if we can pinpoint the reason why this may be working for some and not for others - this could impact the work the My VA team is doing to direct link to the detail pages.   They have a design intent meeting this morning for that work, and I will mention this potential issue.

**Comment by mnorthuis** [comment]
@rileyorr @denisecoveyduc @Dr-Pongo @kevinstachura @OptionSelect 

I dropped some example flows illustrating the deep linking into Riley's mural for us to use to continue discussions

https://app.mural.co/t/vsa8243/m/vsa8243/1645453970389/5712442eb61e558df96599ac35c346436aafcc9c?sender=mikki1741

![image](https://user-images.githubusercontent.com/20994159/166080858-117a786a-2923-4b67-a7eb-8322ed0edd13.png)

**Comment by mnorthuis** [comment]
Hi all @rileyorr @denisecoveyduc @Dr-Pongo @kevinstachura @OptionSelect

Just following up on the above to see if there are any questions/details you would like to discuss?

**Comment by mnorthuis** [comment]
My ears were burning! :-)  

I finalize URLs typically once content is done, so they reflect the H1 structure.  @DanielleThierryUSDSVA and I spoke yesterday, and we will work towards finalizing H1s, but there is content work that needs to also be done for the revised static landing page, the new summary level page, and at least a review of all the other tool pages for any impacts due to the consolidation/linking/top level page changes. 

Can you provide an update on your timeline and when you need info from us by, so we can put this into our work plan accordingly?

**Comment by denisecoveyduc** [comment]
Yes! That is the current timeline. 

@DanielleThierryUSDSVA - Should @rileyorr or @kevinstachura open a content intake request to capture the work to **revise** the static landing page and to **review** the new summary level page and the other tool pages?  Do you have everything you need from our team?

**Comment by mnorthuis** [comment]
@rileyorr @denisecoveyduc @Dr-Pongo @kevinstachura @OptionSelect
A bit of a change to the breadcrumb direction from previous discussions. Because the static pages provides entry points into 2 different tools/options (the debt summary and the FSR), the static page should remain available for users to access and visible in the breadcrumb.  This doesn't change the deep linking approach and the ability to bypass this page for deep links, but want to keep that page in the breadcrumb.  Let me know if there are any questions/concerns.

**Comment by mnorthuis** [comment]
IA information has been updated to include new URLs.   

@DanielleThierryUSDSVA and I reviewed and worked through H1s together to land on this structure, which resulted in the URLs and breadcrumbs documented.  We still have some work to do on link labels - primarily the entry point links that will deep link into the tool.  There is a very slight possibility that those decisions may result in slight tweaks to the H1s, but the URLs should hold pretty strong. 

Let me know if there are any questions. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/debt-portal.md

**Comment by rileyorr** [comment]
Hi @mnorthuis! I'm just now catching up after PTO - thank you for providing these updates. All those points make sense, and I'd love to brainstorm about how we can test the static pages in the full flow. I'll put something on the calendar for next week. 

Here's the research plan and conversation guide for the study in case it's helpful to look at ahead of our meeting:
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/conversation-guide.md)
