### ISSUE TITLE
Staging: Scheduling Manager Requests Not Being Updated with Email in VAOS Request

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#39301]
Cody discovered that after the request has been created, the front end calls a separate endpoint to update Scheduling Manager notification preferences. This endpoint does not exist in VAOS service.  

The front end still needs to call the notification preferences endpoint in VAR-Resources so that the email gets updated in Scheduling Manager.  Scheduling Manager will still be on VAR Resources so this should not present any issues.  

**Steps to Reproduce:** 

1. In SM find a VAOS service patient with a submitted request.  Note the email address associated with the request.  
2. Login as that patient in VAOS.  Submit a request using a different email address than in the existing submitted request.  
3. Expected Response:  The newly submitted request has the email address as entered in VAOS. The email address on the existing submitted request updates to the email address submitted on the latest request. 
4. Actual Response:  The newly submitted request email address is incorrect.  The email address on the existing submitted requests is unchanged.  

![SMEmail.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/a3ad5fd3-04a9-4252-a928-368ef9634cfa)

![VAOSEmail.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/71f71134-a630-432c-9a61-09a658f1c1ca)Note I tested the above scenario with Ruben Moreno (VAR Resources) patient and this works as expected. Expected = Actual Response.  

End User Impact: 

Veteran is not properly notified when a request is processed.  

Environments, users, and patients tested in:
Staging (DAYTSHR)

ola.e.edgecombe@id.me

**Comment by grossb1** [comment]
This associated ticket to remove this logic once VAR resources is sunset:
https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39319

**Comment by marcynadeau** [comment]
@grossb1 @ldelacosta As discussed on Scrum this failed testing and same issue as originally reported.

**Comment by ldelacosta** [comment]
Moving this ticket back to In Progress

**Comment by aarathi-poldass** [comment]
Re-tested the defect and the issue still exists. Attached below is a screenshot for your reference:
![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/ea7605ec-20aa-467e-b85f-d2193c776fcd)

**Comment by ldelacosta** [comment]
Thanks @marcynadeau . Will let you know when the issue has been fixed.

**Comment by marcynadeau** [comment]
@beth-wodzinski assigning to you for testing.

**Comment by beth-wodzinski** [comment]
This passes testing. 

In SM, I found a request for Ola Edgecombe. The email address was aarathi.poldass@va.gov. In VAOS, I entered a new request for Ola, with my email. 

When I refreshed SM, the email for both the old request and the new request was beth.wodzinski@va.gov, as expected. 

@ldelacosta verified

**Comment by ldelacosta** [comment]
This has been validated. Closing out the ticket.
