### ISSUE TITLE
Deploying code to lowers and to prod

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#39317]
**From Epic/Initiative:**
USER STORY: As a VFS team, I want to have a centralized location where I can perform and view status of core VFS tasks, allowing me to complete my work more efficiently. 

BET: If VFS teams have a centralized location where they perform and view key engineering tasks, they will be able to more efficiently complete core VFS tasks.

DOD: Core VFS tasks relevant to the Release Tools team are included in the Release Tools plugin for Console UI MVP.

- [ ] perform tasks on a given commit (ex: deploy) to a lower environment

- [ ] redeploy

- [ ] view status

**Comment by rmessina1010** [comment]
CUI  work is on hold.

**Comment by jhonnyoddball** [comment]
Console UI work, closing for now.
