### ISSUE TITLE
Remove call to VAR in the V2 new appointment flow

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#39319]
We are adding to logic to resolve the following issue:
https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/39301
This will need to be removed once var resources is sunset.

**Comment by ajmagdub** [comment]
Moving to blocked until we get a notification that VAOS Service (V2) is in production and nobody is using VAR (V0)

**Comment by simiadebowale** [comment]
@vbahinwillit - this ticket is already resolved with ticket #52955. See above comment
