### ISSUE TITLE
Desktops/laptops show mobile view

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#39312]
## Issue Description
For some reason desktops/laptops are displaying on mobile view. 

---
## Tasks
Conduct analysis and implement a fix.

## Acceptance Criteria
Desktops and laptops must retain their designed view and not mobile.

**Comment by abuchanan83** [comment]
This is the issue causing this problem is the code below. Not sure why it was added,  but its identifying the user's window as landscape and defaulting to mobile view. To fix the issue, we will need to understand why this code was added and then add the proper logic to handle it. 

  const isLandscape = () => {
    const islandscape = window.innerHeight < window.innerWidth;
    const mobileDevice = !!navigator.maxTouchPoints;
    if (islandscape && mobileDevice) return true;
    return false;
  };

**Comment by abuchanan83** [comment]
To reproduce this issue, please ensure you are on the master branch of the vets-website. Then open dev tools, select the option to simulate devices, then select the "Next Hub Max" view. This will allow you to reproduce the issue.![Screen Shot 2022-04-01 at 9.18.40 AM.png](https://images.zenhubusercontent.com/61fafcd50cf8302de42d01ba/2d3e8dcb-7664-4ebc-a2f5-4e1c66cd22eb)

**Comment by hallihocine** [comment]
Ticket has been validated: the issue has been resolved. Desktops/laptops retain and are displaying their designed view and not switching to Mobile view:
<img width="754" alt="Screen Shot 2022-04-01 at 3 20 33 PM" src="https://user-images.githubusercontent.com/86266024/161572680-8bdff4bb-b76a-4b3e-8b16-9fbae52c345a.png">

**Comment by hallihocine** [comment]
- Test Run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/cases/view/15991&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4169
- Test Steps:
[Desktops:laptops show mobile view.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8410844/Desktops.laptops.show.mobile.view.xlsx)
