### ISSUE TITLE
Previewing and demoing products

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#39316]
**From Epic/Initiative:**
USER STORY: As a VFS team, I want to have a centralized location where I can perform and view status of core VFS tasks, allowing me to complete my work more efficiently.

BET: If VFS teams have a centralized location where they perform and view key engineering tasks, they will be able to more efficiently complete core VFS tasks.

DOD: Core VFS tasks relevant to the Release Tools team are included in the Release Tools plugin for Console UI MVP.

- [ ] Link to review instance

- [ ] See where code is deployed to

**Comment by rmessina1010** [comment]
Console UI work is on hold.

**Comment by jhonnyoddball** [comment]
Console UI work, closing for now.
