### ISSUE TITLE
Update Platform Orientation to include adding new team member to vets.gov-write

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39321]
## User Story
As a VFS team member, I want to have an easy, minimal process for getting onboarded through Platform Orientation so that I can begin supporting my VFS team as soon as possible.

As a Governance team member, I want to be able to direct new VFS team members to 1 spot for getting onboarded through Platform Orientation so that the process is seamless and easy to follow.

- Intended Audience: VFS teams and Governance team
- Desired Outcome: 
- Due Date: 

## Description
The current guidance for getting onboarded with Platform Orientation requires:

1. New team members to [request Github repo access ](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Gettingrepoaccess). This step is  currently a prerequisite for the following step.
2. New team members to follow the [process for New VFS team members ](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html#Guidancefornewteamsandteammembers-NewVFSTeammembers)(ie completing the Platform Orientation template). 

Governance team recently learned that new team members can actually complete step 2 above without getting repo access first. The only thing they cannot do is "click “Assignees” and select your name.*" - aka assign themselves the ticket.

In order to simplify the orientation process, Governance team will be removing the guidance around assigning themselves the ticket and merge the guidance for getting repo access into the Platform Orientation template. 

_Additional background for [Launch new Platform Orientation](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/13709) initiative <br />_

## Artifacts Needing Updates

- [Request Access to tools ](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Gettingrepoaccess)section of Platform Website
- [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html) page on Platform Website
   - Note: User flow image is taken from [this MURAL board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1621540297622/94e7421ea7c560ea7dcaa1ca54cd6920731f48ae?sender=u0574179b1d97118ccc0e3591)
- [Platform Orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) on Github
- [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D) on Github

## Artifacts for Review

- Draft[ request access to tools](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2163474460/Shira+-+Request+access+to+tools). Note: only the GitHub: Getting repo access section has changed.
- Draft [Guidance for new teams and team members](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2163474486/Shira+-+Guidance+for+new+teams+and+team+members)
- [Pull Request for Platform Orientation gh template](https://github.com/department-of-veterans-affairs/va.gov-team/pull/40097)
- [Pull Request for New VFS Team gh template](https://github.com/department-of-veterans-affairs/va.gov-team/pull/40102) Note: this template did not _need_ updates however minor changes were made.
- New VFS Team Members Confluence guidance, specifically [Add new VFS team member to vets.gov-write GithHub team](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2041086016/New+VFS+team+members#Add-new-VFS-team-member-to-vets.gov-write-GithHub-team*)

## Acceptance Criteria
- [x] Request access to tools page on Platform Website has been updated per guidance
- [x] Guidance for new teams and team members on Platform Website has been updated per guidance
- [x] Platform Orientation GitHub template has been updated per guidance
- [x] New VFS Teams GitHub template has been updated per guidance
- [x] New VFS Team Members guidance on Confluence has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled
- [x] Change has been communicated to VFS teams via the Playbook Communication guidelines
   - [x] Slack announcement on #vfs-all-teams
   - [x] ToT announcement

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Initiative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby @mchelen-gov FYI this ticket is still a work in progress, however I wanted to get it documented before departing for PTO. I will continue to modify this when I return on 4/4.

**Comment by mchelen-gov** [comment]
Note: broader issue of GH team management & permissions is spun off in https://github.com/department-of-veterans-affairs/va.gov-team/issues/35154

**Comment by shiragoodman** [comment]
@chaseakirby would you take a look at the Artifacts for Review section and peer review this ticket? I haven't updated any operational docs yet but I wanted to check-in first and see if my changes make sense. Thanks!

**Comment by chaseakirby** [comment]
@shiragoodman I think that they do! I made a comment on the [Request Access to Tools](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2163474460/Shira+-+Request+access+to+tools?focusedCommentId=2161476446#comment-2161476446). I think that it is fine as is but we may want to consider changing the language so we keep their focus on adding the requested info and going through the checklist rather than them wonder if they have to find a way to submit it to Platform (I'm also making an assumption that some people may have not used GitHub and don't understand how we are using labels).

**Comment by shiragoodman** [comment]
@chaseakirby i am going to push the changes to Platform Website so they're picked up on the Tuesday scroll viewport publishing. I will plan to announce the changes Tuesday afternoon (once live) and will announce the planned change in the Tuesday ToT meeting.

**Comment by shiragoodman** [comment]
@chaseakirby closing!
