### ISSUE TITLE
SOCKS access for Mary (Lauren) Maxwell

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va.gov-team#39331]
### Your Name

Mary Lauren Maxwell

### Your Email

lauren.maxwell@adhocteam.us

### Your Role

Software Engineer III

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC61OAZ2e1P8s10Cuhm7d6dF0fMmcgaoediwpMLutkAI3hNb1jhw3vlwCCQjBBur4byI1c+nSgVhPXJzrWC4xb7hiMbks3Xsf2pPU9Y0kGTTO09RZfvINaD2hXUKQnddG6dvqU7SsJ/JFXzkb3T4EKSFn7xYyyLz3xa9nEQ8L6S77iRz6eKDDxxN/SgqmFgBqpCMLq+F0MH2Box20SnFInNZYx4YEQUNRT2SX7XzWkbuApXPR3Md0YarllYVLlpudIlGJiHJMGIQjU/9E0+fXqQvJMku7JtQn0AwnFIJ8WDWRJ11H8f5//O0djsJ/PPJAeQLOYrHOYKECiEv97no+NtMvbj5RNDKREkIiBWboe1uGJk357weO9N5na8MH/K1yu3wTiGCyZsCL07GhPqtpaNxrB1toys107G1oN+C8tbah9ugU4UH1c+YOOwVaQEF6UrHTjMWGxdJCSrJ0rc0dstzVmCe0X/SGG1OkCGnd/WlkA8DxTLjNnwjmSQGKLavoc= laurenmaxwell@Laurens-MacBook-Pro.local

**Comment by mlauren** [comment]
There was a previous request I made last week for PC access. Please revoke access to this PC if needed.

**Comment by rmtolmach** [comment]
@mlauren, access granted ✅ 
The previous SSH key associated with your email address has been replaced with this MacBook key.
