### ISSUE TITLE
FE - Auth Profile -  Bad Address Indicator- Unit and e2e tests

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39346]
## Background
As a FE engineer, I want to conduct all unit and e2e tests to verify that my code is valid and passes required tests.

## Tasks
- [ ] Conduct all unit and e2e tests

## Acceptance Criteria
- [ ] Conduct all unit and e2e tests

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Consolidating with #39342
