### ISSUE TITLE
FE - Auth Profile - Bad Address Indicator- Verify same address update functionality

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39344]
## Background
As a FE engineer, I want to verify that sending an update with the same address (edge case where user's flagged address is actually correct) will clear out the bad address flag in the VA Profile database and no longer be flagged as invalid.

## Tasks
- [x] Test sending the same address in an update and verify that the flag is removed

## Acceptance Criteria
- [ ] Test sending the same address in an update and verify that the flag is removed

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by mdewey** [comment]
![Screen Shot 2022-06-02 at 11 12 25 AM](https://user-images.githubusercontent.com/1793923/171732475-3c24c359-1036-459d-9bfc-d09f61bab160.png)

I just tried this when testing out the new features and I am getting that response for downstream service.

**Comment by mdewey** [comment]
Blocked until BE work is complete. 

**unblocked when**: The POSTing of `badAdress` flag work is done.

**Comment by SKasimow** [comment]
Closing...being worked as a BE ticket #39345
