### ISSUE TITLE
AWS access for Rebecca Green

### ISSUE THREAD

**Issue by reblg** [department-of-veterans-affairs/va.gov-team#39359]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Rebecca Green

### Your Email

rebecca.green@thoughtworks.com

### Your Team, Role, and Company

Digital Health Platform (DHP) Team, Developer, Thoughtworks

### Desired AWS Access

Copy permissions from @yonidoronpeters

### Access Expiration

ongoing

**Comment by td-usds** [comment]
Elevation of AWS permissions approved

**Comment by reblg** [comment]
Confirmed I have access!
