### ISSUE TITLE
[OCTO-DE Crew Onboarding]: Ray Wang

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#39354]
### What OCTO-DE Crew is the team member joining?

Platform

### What OCTO Community of Practice is the team member part of?

Product

### Has user received VA.gov email address?

- [x] User has @va.gov email address

### VA Email Address

gang.wang@va.gov

### Has user been added to Department of Veterans Affairs Github Organization?

- [x] User is member of Github org

### Github Username

@Raywangoctova

### Has user been added to DSVA Slack?

- [X] User is member of DSVA Slack

### Slack Username

[@Ray Wang](https://dsva.slack.com/team/U038KPD3MK5)

### Crew Specific - Platform

- [x] Add to Slack group: @octo-de-platform
- [x] Add to Github group: octo-de-platform
- [x] Post welcome Slack message: #platform-team
- [x] Register for Platform Orientation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D
- [x] Add to Confluence
- [x] Add to Confluence group "platform-crew-octo-de" https://admin.atlassian.com/s/10f8a514-fd86-4b32-8ba3-c0bfc6969f88/groups/81f1ea1a-fc6d-4b27-aed5-0bb73dd86c02
- [x] #40015
- [x] #40017
- [x] Schedule recurring 1:1
- [x] Link to Platform team welcome guide https://vfs.atlassian.net/wiki/spaces/AP/pages/1413808450
- [x] Link to Platform team meetings https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings
- [x] Update Slack profile in accordance with https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack
- [x] Onboard to Pagerduty https://dsva.pagerduty.com/

**Comment by RayWangUSDS** [comment]
1:1 with the following people:

Lisa Koenigsberg
Mike Chelen
Rachael Roueche
Matt Self
Kevin Hoffman
Cory Trimm
Chante Swett
Lauren Alexanderson
Dave Conlon
Chris Johnson
Leanner Miller
Ric Miller
Martha Wilkes
Charles Worthington

[signature_1204807837]<http://www.usds.gov/>

Ray Wang
Product Management

U.S. Digital Service
***@***.***



From: mchelen-gov ***@***.***>
Sent: Thursday, March 31, 2022 12:40 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Wang, Ray EOP/OMB ***@***.***>; Mention ***@***.***>
Subject: [department-of-veterans-affairs/va.gov-team] [OCTO-DE Crew Onboarding]: Ray Wang (Issue #39354)

What OCTO-DE Crew is the team member joining?

Platform

What OCTO Community of Practice is the team member part of?

Product

Has user received VA.gov email address?

  *   [ ] User has @va.gov email address

VA Email Address

No response

Has user been added to Department of Veterans Affairs Github Organization?

  *   [ ] User is member of Github org

Github Username

@RayWangUSDS<https://github.com/RayWangUSDS>

Has user been added to DSVA Slack?

  *   [X] User is member of DSVA Slack

Slack Username

@Ray Wang<https://dsva.slack.com/team/U038KPD3MK5>

Crew Specific - Platform

  *   [X] Add to Slack group: @octo-de-platform
  *   [ ] Add to Github group: octo-de-platform
  *   [X] Post welcome Slack message: #platform-team
  *   [ ] Register for Platform Orientation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D
  *   [ ] Add to Confluence
  *   [ ] Add to Confluence group "platform-crew-octo-de" >https://admin.atlassian.com/s/10f8a514-fd86-4b32-8ba3-c0bfc6969f88/groups/81f1ea1a-fc6d-4b27-aed5-0bb73dd86c02<<%3ehttps:/admin.atlassian.com/s/10f8a514-fd86-4b32-8ba3-c0bfc6969f88/groups/81f1ea1a-fc6d-4b27-aed5-0bb73dd86c02%3c>
  *   [ ] Update Team Roster (private) >https://vfs.atlassian.net/wiki/spaces/OCLP/overview#Meet-the-team<<%3ehttps:/vfs.atlassian.net/wiki/spaces/OCLP/overview#Meet-the-team<>
  *   [ ] Update Team Roster (public) >https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623<<%3ehttps:/vfs.atlassian.net/wiki/spaces/AP/pages/1908834623%3c>
  *   [ ] Schedule recurring 1:1
  *   [ ] Add to Platform meetings >https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings<<%3ehttps:/vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings%3c>
  *   [ ] Add to team meetings
  *   [ ] Update Slack profile in accordance with >https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack<<%3ehttps:/depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack<>

**Comment by RayWangUSDS** [comment]
My va github handle is raywangoctova and email address is Gang.Wang@va.gov.

**Comment by RayWangUSDS** [comment]
Can you grant access to me to edit the ticket? I think I only can comment.

**Comment by raywangoctova** [comment]
Registered for platform orientation.

**Comment by raywangoctova** [comment]
Updated Slack profile.

**Comment by raywangoctova** [comment]
1-1 was scheduled for Tuesday at 11am.

**Comment by mchelen-gov** [comment]
Ray which github account are you using, @RayWangUSDS or @raywangoctova? We need to get you added to the proper orgs and teams.

**Comment by RayWangUSDS** [comment]
Raywangoctova

Sent from my phone
Ray Wang
Product Management
U.S. Digital Service
***@***.***
M: 202-881-7951


On Apr 12, 2022, at 8:52 AM, mchelen-gov ***@***.***> wrote:

﻿

Ray which github account are you using, @RayWangUSDS<https://github.com/RayWangUSDS> or @raywangoctova<https://github.com/raywangoctova>? We need to get you added to the proper orgs and teams.

**Comment by mchelen-gov** [comment]
@raywangoctova Ok I believe all the onboarding tasks are complete except for https://github.com/department-of-veterans-affairs/va.gov-team/issues/40017! Are there any other onboarding steps you would like help with?

**Comment by mchelen-gov** [comment]
Added item for onboarding to Pagerduty
