### ISSUE TITLE
RFC: AMT integrators can describe fine-grained permissions using JSON

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#39351]
Add to the "design section" of the Gherkin + Auth RFC. 

**RFC Link:** https://vfs.atlassian.net/wiki/spaces/AMT/pages/2142011842/RFC+6+Permissions+described+in+Gherkin+will+enable+more+contributors+to+participate?src=mail&src.mail.action=view&src.mail.notification=com.atlassian.confluence.plugins.confluence-mentions-plugin%3Amention-created-notification&src.mail.recipient=8a7f808a7ee01030017ee0324cd90026&src.mail.timestamp=1648499737539

**Done when:** Kevin and I review changes in the RFC and agree it is complete.

**Comment by kjduensing** [comment]
I riffed on the pending JSON structure:
```json
{
  "permissions": [
    {
      "name": "editors and admins can approve comments",
      "resource": "comments",
      "scopes": "approveComment",
      "restrictions": [
        {
          "type": "role",
          "attributes": {
            "roles": ["editor", "admin"]
            "negate": false
          }
        },
        {
          "type": "group",
          "attributes": {
            "groups": ["team-usa", "team-canada"]
            "negate": false
          }
        }
      ]
    }
  ]
}
```

**Comment by kjduensing** [comment]
The things I like about the above:
1. It frames things in permissions - you immediately know what each thing in the permissions array is
2. It raises up the common stuff - `app`, `resource`, `scopes`
3. It reframes "policies" as "restrictions" which I think is more intuitive
4. It types and scopes attributes of each restriction/policy so we can easily expand in the future

I'm sure there are things I didn't think of though - what are your thoughts @kylesoskin @calquisola @iriteshp?

**Comment by kjduensing** [comment]
Hmm good point, thanks. I feel like that's ok though. I'd rather be explicit than concise, and JSON was never a pithy format to begin with. Thoughts?

**Comment by kylesoskin** [comment]
I agree, long JSON can be fine. 

I like the JSON, just making sure we all still like the JSON before we decide what to pitch in the RFC

we COULD simplify even more to something like we were trying to do with cucumber, but with more rules in place. like 

```${x} CAN ${y} ${z}
x=role
y=scope(s)
z=resource

viewers CAN read and create userdata
editors CAN read, create, and update userdata
admins CAN read, create, update, and delete userdata```

And we could get to our JSON from just that

Or some more advance if we need it

```
editors CAN read, create, and update userdata IF User:onCall == true
viewers CAN delete and update userdata IF userdata:owner == User.self

editors CAN read, create, and update userdata UNTIL User:RotationEnds > Time.now()
viewers CAN delete and update userdata UNLESS userdata:owner != User.self
```

We can also have the same flexibility in json.... again, just bringing it up. I still favor the JSON.

**Comment by kjduensing** [comment]
Good point, thanks for bringing it up. Yeah I think building a DSL like this would be SUPER fun but probably not needed at this point. Also brings a support burden with it. 

I'm good with plain ol' JSON if y'all are 🙂

**Comment by kjduensing** [comment]
Also, I imagine we're gonna need the JSON anyway, so we might as well start there.
