### ISSUE TITLE
PM - Auth Profile - Personal Information Revision - Request QA review for 5/4 - 5/17 sprint

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39373]
## Background

Put in a request with Tze to do a QA review in the 5/4 - 5/17 Sprint in preparation for Midpoint review.

## Tasks
- [x] Put in a request with Tze to do a QA review in the 5/4 - 5/17 Sprint 

## Acceptance Criteria
- [x] Put in a request with Tze to do a QA review in the 5/4 - 5/17 Sprint 

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
This will likely need to be later in the 5/4 - 5/17 window, but I think we can still go ahead and get this on Tze's radar.

**Comment by SKasimow** [comment]
QA ticket has been opened and Tze notified #40249
