### ISSUE TITLE
PM- Auth Profile - Bad Address Indicator - Start on QA use cases

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39379]
## Background

Describe the issue background and scope

## Tasks
- [ ] Add tasks here that must be completed

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Closing; dupe to 39381

**Comment by SKasimow** [comment]
Closing - dupe to #39168
