### ISSUE TITLE
PM- Auth Profile - Personal Information Revision - Finish QA Prep

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39374]
## Background

Complete all prep & artifacts required for Tze to do QA testing during the  5/4 - 5/17 Sprint.

## Tasks
- [ ] Complete all prep & artifacts required for Tze to do QA testing

## Acceptance Criteria
- [ ] Complete all prep & artifacts required for Tze to do QA testing

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
Gonna close this and consider it a duplicate. I think these tasks are covered in #34466 and #34008.
