### ISSUE TITLE
PM - Auth Profile - Bad Address Indicator - Document Staging user info for flag

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39380]
## Background

The information about which user(s) can be updated to add/remove a bad address flag need to be included in the QA documentation

## Tasks
- [ ] Create a QA document that explains how to get a bad address flag added to a test user for QA testing - Tom and Adam should be able to provide this information.

## Acceptance Criteria
- [ ] Create a QA document that explains how to get a bad address flag added to a test user for QA testing - Tom and Adam should be able to provide this information.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@tpharrison - do you think we can document how to set a BAI and have QA do themselves? Or would it be better to just have you update the staging accounts they plan to use?

**Comment by tpharrison** [comment]
@SKasimow - I think it might be easier for me to do it.

**Comment by SKasimow** [comment]
I suspected as much. I'm going to close this ticket. TY!
