### ISSUE TITLE
Clean up the prototype from our initial sessions for further development

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#39388]
## User Story

_As a developer of file upload I would like my project to follow some best practices regarding code structure, as well as implement basic CI, linters, etc_

## Expected Behavior

_This ticket represents a timeboxed effort to clean up the results of our initial prototyping sessions and think about how we want to structure this code base._

## Acceptance Criteria

- [x] _Refactor code to use flask-restful instead of flask_
- [x] _Document and implement linters/style guides_
- [x] _Review code for anti-patterns and refactor as needed._
- [x] _Unit tests should be added_
- [x] _Basic CI should be performed before merges to main_

**Comment by ewilson-adhoc** [comment]
Today I will be implementing a basic test harness and looking into tools that will give us code coverage analysis. Stretch goal is to set up CI on github.

**Comment by ewilson-adhoc** [comment]
Added test harness and basic linter + CI using GH actions. Working on adding code coverage report to these actions.

**Comment by ewilson-adhoc** [comment]
We are playing with fastAPI as an alternative to flask (more lightweight, modern)

**Comment by ewilson-adhoc** [comment]
Broke remaining tasks into separate tickets (#39976) and (#39973)

**Comment by considerable** [comment]
old apps deleted - https://github.com/department-of-veterans-affairs/vets-api-file-upload/pull/39
