### ISSUE TITLE
PM - Auth Profile - Notification Preferences Update - Share IA/content recommendations with VA Profile

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39381]
## Background

Christina will be working on mockups (#39166) and making a content and IA request (#39167) for adding a new Comp & Pen section to the Notification Preferences page.   Once that is complete, share the mockups and content/IA feedback with the VA Profile team (Slack [#va-profile](https://dsva.slack.com/archives/C7TE0PFTL) so that they can provide feedback.

## Tasks
- [ ] Share mockups and content/IA feedback with VA Profile team

## Acceptance Criteria
- [ ] Share mockups and content/IA feedback with VA Profile team

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
Hi! I just sent the email to Mike Richard (VA Profile) with the content and IA feedback, so I'm gonna close this. It was going to take me just as long to give you details about what the email should include as it was to write the email myself, so I just did it 😃

**Comment by SKasimow** [comment]
Ok, thank you!
