### ISSUE TITLE
Adding Megan Graham to DSVA Slack

### ISSUE THREAD

**Issue by laurylzenobi** [department-of-veterans-affairs/va.gov-team#39412]
# Description

Please add Megan Graham(megan.graham@adhocteam.us) to DSVA slack as a full member, to the following channels:
- #design
- #vetsdotgov-research
-  #vfs-all-teams
- #feedback-backchannel

Megan is a UX researcher working on the MHV to VA.gov team.

**Comment by laurylzenobi** [comment]
@LEHigley @KevinMHoffmanUSDS pinging to avoid it getting lost

**Comment by LEHigley** [comment]
@laurylzenobi email address?

**Comment by laurylzenobi** [comment]
Any updates to this?
