### ISSUE TITLE
[Infrastructure Request]: Setup and configuration for Platform Console UI

### ISSUE THREAD

**Issue by ericvoshall** [department-of-veterans-affairs/va.gov-team#39431]
### Team name

Platform Console UI

### Application name

Platform Console UI

### GitHub repository

https://github.com/department-of-veterans-affairs/backstage-test

### Product owner

Mike Chelen

### Product manager

Lee Helmer

### Related issue

https://github.com/department-of-veterans-affairs/backstage-test/issues/149

### Infrastructure needed

We need access to an S3 bucket for our Dev instance to store dynamically generated technical documentation. 

We will also need a way for our application to be able to connect to the S3 bucket to store and retrieve data - I think we will need a service account, a token, or something else to be able to configure our application to perform those actions.

### Access needed

Eric.Voshall, John.Chapin, Matthew.Ng, Mike.Haley

### Acceptance Criteria

- [ ] _TBD_

**Comment by jhouse-solvd** [comment]
@ericvoshall - Acknowledging that we have received this request. The request appears straightforward. We may reach out if we need to clarify requirements. 

We have a number of high-priority tasks in progress, but can potentially pick this up next sprint.  

Do you have any hard timelines that you are working towards? Thank you in advance for any info.

**Comment by ericvoshall** [comment]
@jhouse-solvd We would like to have this set up this month as we ramp up users and developers on the Console UI.

**Comment by ericvoshall** [comment]
@jsgarmon - thank you! We need to supply configuration values to our application (an AWS Access Key ID and AWS Secret Access Key) to make use of this bucket. Should I use the `/devops/svc-gha-platform-console-ui/AWS_ACCESS_KEY_ID` and `/devops/svc-gha-platform-console-ui/AWS_SECRET_ACCESS_KEY` keys for this? Or something else?

> your app in EKS should have read-write access via the role that it assumes.

I am also unsure what you mean by this.

**Comment by jsgarmon** [comment]
There is an AWS role for your service. I've just put in a PR to make the connection between your service and role via a service account. Deploying from that PR branch, the container can assume that role:
![image](https://user-images.githubusercontent.com/47490730/162287944-d3dd097f-57a6-46e1-8b83-e97b27504933.png)

EKS apps and services should not need to use access keys or secrets to access other AWS services.

**Comment by ericvoshall** [comment]
Thank you, this is working.

**Comment by ericvoshall** [comment]
@jsgarmon A comment came up in a PR for our application - is it possible to add a `-techdocs` suffix to this bucket? We may have a need for more buckets in the future and would like to have them easily identifiable.

**Comment by jsgarmon** [comment]
@ericvoshall : sure, but I can't change the bucket name without destroying and recreating the bucket. Is there anything in there you want to keep?

**Comment by ericvoshall** [comment]
@jsgarmon Nope, you can delete it.

**Comment by jsgarmon** [comment]
This is done. Please re-close this issue if all looks good.

**Comment by ericvoshall** [comment]
Thank you!
