### ISSUE TITLE
Update VAMC Facility Health Service front end to utilize new office hours field

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-team#39436]
## Issue Description

We need to update the front end to pull the hours data for VAMC Facility Health Service nodes from the new field_office_hours field.

VAMC Facility Health Service nodes contain hours and contact information. This data is stored in a Service location entity referenced by the field_service_location field. Within the Service location entity we historically stored hours data in the field_facility_service_hours field but this field will be going away in the near future and has been replaced by field_office_hours. 

## Front end tasks
- Replace hours data for VAMC Facility Health Service nodes from the field_facility_service_hours field with hours data from the field_office_hours field.

## Acceptance Criteria
- [ ] Hours data for VAMC Facility Health Service nodes is pulled from field_office_hours field
- [ ] Display of hours information should match what the CMS provides to editors

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/content-build/pull/1080

**Comment by JayDarnell** [comment]
Associated PR is closed so I believe this should be marked as complete
