### ISSUE TITLE
SOCKS access for Fernando Boza

### ISSUE THREAD

**Issue by FernandoBoza** [department-of-veterans-affairs/va.gov-team#39444]
### Your Name

Fernando Boza

### Your Email

fernando.boza@accenturefederal.com

### Your Role

Frontend Developer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDvnOgZbTyD9N/74xjZf8oYdWElKr1LlqgP3HPesflH93j4+CQRG+3Wf0OMa1PBHajK//Bl+1bFun3sacP+9Yv7hhKTHficDtWnkE1gjPV2Rruns4Iipqixzn8WJvpk4gGD/WjxkxxSg04AaCQ+nyLir2c5tG4L0IRnd75Er745Vf2CMO1QjhEy2SQJOWOGozptmfvwVaK/T3XtsF9Ns9K636Ci258MBg6xQqarfZCcej1ffakrdNPtobhkDcnp6wRmgrAJgYB72ugVkIrMLE/be+KPfDb35XLiQpJZMaIin9bJhoSw+Q3eYwqPlS+g09ZqqmvTma9+r57gzxwLFoifYg0H8ZXEAMvzkwTzEA8RARj1/Gc0vwYNRVmu6MBB8XopflftGBGs7KanQJZUUq/NljUX/1Ya7Tneqi6AdA8/g0ZnFOB3JT+FCxNij1uYTb2SjxDNUfyl1oZpbSf5Gs3MVrMhuR49SKG03xpJG1DdNwpU/n8/13/2b9MbaTf7eZVn9HzNW2y9ZXTz3eYkGZxF9EDx97M0QsE3ZkIhcsX2rPiCWYxQKCyElHWYbXjDKwq5z4fd+UoD06II6ejQGOo23k5/6lcz41ltjGYho/+SesgOYXwlxW6/bOhAcAyXUxbPUobpbKz6G94LLXHk3NVeqLM6N/jA9NbxP6cXxxqB/w== fernando.boza@AFSMWTOK79M4FIQ

**Comment by rmtolmach** [comment]
@FernandoBoza: Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
