### ISSUE TITLE
Need to document and log uses of back and EVSS calls from va.gov

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/va.gov-team#39449]
The lighthouse team is working to identify all EVSS dependencies, however the EVSS team does not log the consumers of their services. In an effort to figure out which EVSS services are used by the [VA.gov](http://va.gov/) team, we wanted to be able to log calls to the EVSS libraries to 100% know that this code is still being used.
I believe these are the libraries of interest.
Can we just submit a pull request with the details of the changes and have them reviewed?

**Comment by jhouse-solvd** [comment]
@pshahVA - Thanks for submitting this issue. 

Above, you mentioned: "I believe these are the libraries of interest." 

Did you intend to link to any libraries of interest? 

At first glance, I'm not sure if the Platform Infrastructure team is the best resource to assist with this request, though it may be. 

I do think that submitting a PR would be welcome. Do you know against which repo(s) the PR will be submitted? That may help us understand which team is best positioned to assist. 

Thank you in advance for any additional info you can provide.

**Comment by pshahVA** [comment]
Thanks for getting back to me. Yes, I meant to include a link to the [vet.api evss libraries](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/evss)

**Comment by pshahVA** [comment]
Just wanted to get a status update on this.

**Comment by pshahVA** [comment]
Hello, I wanted to know if there was any movement on this ticket.

**Comment by jhouse-solvd** [comment]
@pshahVA - Please forgive me as I was out of the office for a couple of weeks unexpectedly. I will inquire with the team and see how we can move this forward.

**Comment by jhouse-solvd** [comment]
@pshahVA - Have you taken a look at Loki logs in Grafana to see which calls are being logged?  

As far as reviewing PRs to the Vets-API repo, I _believe_ you would want to consult w/ @ericboehs and the Console Services team if I'm understanding your request correctly. Have you had a chance to consult w/ them yet?

**Comment by pshahVA** [comment]
No I haven't consulted with them yet. I didn't actually look in the logs, as I don't think they are currently being logged right now.

**Comment by patrickvinograd** [comment]
[Loki Link with above query ](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%221657750722277%22,%221657754322277%22,%22Loki%20(Staging)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22fwdproxy%5C%22%7D%20%7C%3D%5C%22evss_back%5C%22%20%7C%20pattern%20%5C%22%3C_%3E%20evss_front~%20evss_back%2Fevss_primary%20%3C_%3E%20%3Ccode%3E%20%3Cbytes%3E%20-%20-%20----%20%3C_%3E%20%3C_%3E%20%5C%5C%5C%22%3Cmethod%3E%20%3Cpath%3E%20HTTP%2F1.1%5C%5C%5C%22%5C%22%22%7D%5D)(staging, can swap to prod).

**Comment by patrickvinograd** [comment]
Then if you aggregate that and group by path, you can see counts for how many times each was invoked.
Here's all evss request paths over the last 24 hours (set to an "instant" query in Loki to get a nice table instead of a timeseries:
```
sum (count_over_time (
    {app="fwdproxy"} |="evss_back" | pattern "<_> evss_front~ evss_back/evss_primary <_> <code> <bytes> - - ---- <_> <_> \"<method> <path> HTTP/1.1\"" [24h]
  )) by (path)
```
[Loki link](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%221657750722277%22,%221657754322277%22,%22Loki%20(Staging)%22,%7B%22expr%22:%22sum%20(count_over_time%20(%5Cn%20%20%20%20%7Bapp%3D%5C%22fwdproxy%5C%22%7D%20%7C%3D%5C%22evss_back%5C%22%20%7C%20pattern%20%5C%22%3C_%3E%20evss_front~%20evss_back%2Fevss_primary%20%3C_%3E%20%3Ccode%3E%20%3Cbytes%3E%20-%20-%20----%20%3C_%3E%20%3C_%3E%20%5C%5C%5C%22%3Cmethod%3E%20%3Cpath%3E%20HTTP%2F1.1%5C%5C%5C%22%5C%22%20%5B24h%5D%5Cn%20%20))%20by%20(path)%5Cn%20%22,%22instant%22:true,%22range%22:false%7D%5D)

**Comment by ericboehs** [comment]
Console Services was planning on adding [Coverband](https://github.com/danmayer/coverband) at some point (via https://github.com/department-of-veterans-affairs/va.gov-team/issues/29895). This would tell us if the code was getting called internally.

Does that sound like something that would help?

**Comment by jhouse-solvd** [comment]
@pshahVA - I'm passing this ticket to the Console Services team who can better assist with this request. Please see Eric's comment above as a potential solution. ☺️

**Comment by patrickvinograd** [comment]
@pshahVA Not my call...personally I'd run the query over like 30 days just to be safe...Loki should be capable of that kind of scale.

**Comment by pshahVA** [comment]
@ericboehs , I think that would certainly help in the long term.
@patrickvinograd , I ran the query again and I see that PCIU services are called. 
![image](https://user-images.githubusercontent.com/49729315/180066707-26809398-fef0-4ef9-bd5d-8ef018dd9bb0.png)
Can we tell who the calling services are?
