### ISSUE TITLE
Analytics Implementation for VA Notify - Site Usage

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#39452]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Team: VA Notify
    - Points of contact: 
        - @mjones-oddball Melanie Jones (PM) - melanie.jones@oddball.io
        - @bevnobev Beverly Nelson (VA PO) - beverly.nelson@va.gov
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - We would like to track 2 environments:
        - Production: https://notifications.va.gov
        - Staging: https://staging.notifications.va.gov
    
- **When is the launch date?**
    - Both sites are live and behind the VA firewall, however we've only had a soft launch.

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by bevnobev** [comment]
Thanks @mjones-oddball I updated that the sites are live, and we have soft launched.

**Comment by mjones-oddball** [comment]
Question: https://dsva.slack.com/archives/CE4304QPK/p1648828810683559 ... VA Notify site is for internal VA users, not veterans. Will we be impacted by this - "Please remember to opt out of Google Analytics on all of your browsers on your work machines, personal machines (if you are not a Veteran yourself using the site for your own applications), and mobile devices! This helps ensure that we’re not tracking everyone as end users of [VA.gov](http://va.gov/)"?

**Comment by jennaouellet** [comment]
Hi @mjones-oddball and @bevnobev! This will be set up as a new GA property and we'll exclude the opt-out event. Which metrics are you interested in tracking? The standard GA implementation includes pageviews, though interaction events can be added as needed. Thank you!

**Comment by mjones-oddball** [comment]
@bsmartin-ep Pretty low traffic. It's an internal application and right now we only have ~30 users. The homepage might get more hits as you don't have to be logged in yet, but it's a site that you go to if you're trying to use our service it's not something you'd be looking at daily for new content. That's part of why we'd like GA implemented. It would be nice to know how often people are checking us out.

**Comment by mjones-oddball** [comment]
@jennaouellet For this initial implementation basic tracking like pageviews, active users, time spent on site, bounce rates, etc. would be nice. Can we also track clicks on our login buttons so we can tell who is logging in vs just looking at our homepage?

**Comment by jennaouellet** [comment]
Hi @mjones-oddball! I just wanted to give an update that we are working on this currently. I'll send over any questions we have but I believe we have everything we need from your side to get things set up.

**Comment by mjones-oddball** [comment]
@jennaouellet Thank you!

**Comment by michelle-dooley** [comment]
This work is complete, please let us know if you have any futher questions.
