### ISSUE TITLE
On Call Documentation Clean Up and Training

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#3945]
## User Story or Problem Statement
As a engineer on the platform, I need a complete set of resources so I can effectively perform my on-call duties.

## Goal
Look through our current on-call documentation and troubleshooting guides to identity and fill gaps as well as hold a training for all members on the on-call rotation to ensure everyone knows where to find the resources and SOP for troubleshooting.

## Objectives or Key Results this is meant to further
Gaps in the documentation have been identified or resolved and a training is scheduled.  Gaps that haven't been resolved have been documented to resolve.

NOTE:  Working document can be found [here](https://docs.google.com/document/d/1tIg_adkOYHq_pt135DCWoZT8gmFQ-XTCv6xqAJU4HiM/edit?ts=5de593cb#)

## Acceptance Criteria
- [ ] Identify and fill gaps where needed
- [x] Schedule training session with all on-call members.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alexpappasoddball** [comment]
@annaswims not sure why this one was sitting in the backlog, that might have been my fault when I created it.  But I know you have held the training and are working on it (if not completed already).  Can update this task accordingly, add an update and move it to the correct column.  Thanks!

**Comment by annaswims** [comment]
we've had a training on 12/13  and updated the documentation in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/OnCall
