### ISSUE TITLE
[FE] [BUG] Incorrect spacing on alert when pre-checkin is completed

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39462]
## User Story
> these should be why the veteran cares, and the veteran gets out of it.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

At least in Safari, the spacing is incorrect on the alert with the text "A staff member will help you on the day of your appointment to update your information.". To reproduce:

- Start pre-checkin
- Answer "no" to at least one question

You will see:

![Screen Shot 2022-03-31 at 5.17.35 PM.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/487e70c2-f695-4169-94e7-19747a5f2b77)

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
This doesn't seem to happen with pre-check-in.

**Comment by brianseek** [comment]
Issue logged with DS: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1080

**Comment by brianseek** [comment]
@loripusey this is in the DS teams hands now. Should this get closed or should we keep it open to keep track?

**Comment by loripusey** [comment]
I'll close it. Thanks. @brianseek
