### ISSUE TITLE
[Research] Legacy Appeals vs Decision Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3946]
## User Story or Problem Statement
As a researcher, I need I need a clear understanding of the differentiation between legacy appeals and decision reviews so I can provide the right recommendation for future design to access the Decision Review page on va.gov.

## Tasks
- [x] Meet with Fred Sommers

## Acceptance Criteria
- [x]  Determine the feasibility of switching the focus from legacy to AMA process

**Comment by kevinstachura** [comment]
Notes taken for this meeting are located here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/notes/stakeholder-interviews/sme-meeting-with-fred-s.md
