### ISSUE TITLE
[Content organization] Your page doesn't follow heading hierarchy. Headings aren't properly nested, and headings and/or labels aren't relevant to the page. (02.05.1)

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#39470]
#### VFS team name
Authenticated Experience

#### VFS product name
My VA Dashboard

#### VFS feature name
Payment Information

#### Point of Contact/Reviewers
Angela Fowler (@AngelaFowler82) - Accessibility

For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Your page doesn't follow heading hierarchy. Headings aren't properly nested, and headings and/or labels aren't relevant to the page.

### Issue Details
Since the line informing of the previous payment is a level three heading, it makes sense that the line informing of total debt is also a level three heading.

### VA.gov Experience Standard
[Category Number 02, Issue Number 05](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.1

---

### Platform Recommendation
Josh: I'd recommend collaborating with the designer to explore the initial reasons behind this heading structure. As the total debt line is a one liner, and not something starting a full section, this may be more of a content organization issue (which might be better addressed in future versions of the my va dashbaord).

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by aagosto90** [comment]
This isn't relevant anymore since we're no longer using the in-line notification style for debt and it follows the same heading structure as payments :)
