### ISSUE TITLE
[Design] Design Intent

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3947]
## User Story:
As a designer on the BaM team, I need clearly define the design intent for Notice of Disagreement so that I can drill down further in design of individual steps of the form.

## Tasks
- [x] Create a design intent document - Mural

## Acceptance Criteria:
- [x] Design intent created

**Comment by YanaRoy** [comment]
Blocked while the handling of legacy issues is being finalized.

**Comment by kevinstachura** [comment]
Design Intent document has been created and is located here: https://app.mural.co/t/vsa8243/m/vsa8243/1574193061780/6424902fd07999e3388f34a872ebdc1c62450f63
