### ISSUE TITLE
[Content organization] Long or complex sections of content aren't broken up into content chunks or bulleted lists. (02.06.1)

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#39480]
#### VFS team name
Authenticated Experience

#### VFS product name
My VA Dashboard

#### VFS feature name
Payment Information

#### Point of Contact/Reviewers
Jim Ryan (@jimuhh) - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Long or complex sections of content aren't broken up into content chunks or bulleted lists.

### Link, screenshot or steps to recreate
https://github.com/jimuhh/drafts/blob/main/Screen%20Shot%202022-03-31%20at%203.32.07%20PM.png

### VA.gov Experience Standard
[Category Number 02, Issue Number 06](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.1

---

### Platform Recommendation
If possible, break individual pieces of actionable information in the "compensation claim received" section into new lines with punctuation. 

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by hdjustice** [comment]
@jimuhh - Can you confirm what information you are referring to?  We were thinking maybe the "Status" line of the Claims box.  Thanks!

**Comment by aagosto90** [comment]
We determined that the status we're showing in this mockup is pulled directly from the claims tool and it's the most awkward looking one but that is why it's such a long status. The title for the claim and when it was received is already split up with punctuation.
