### ISSUE TITLE
SOCKS access for Therese Dickson

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va.gov-team#39493]
### Your Name

Therese Dickson

### Your Email

therese.dickson@adhocteam.us

### Your Role

Senior Software Engineer, QA

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDU2c0W14iiUXf2LJ+lywd/whSwcH9x4IDg1Q5wxiG3lg9awKDklwTKS4sCCd4TAV3q3pcVt0Fd9gFwJgqpNk2dADCzuPS6G19Edrqrg2Y320hhHoqp3Ba0XkECyWDaQn7Md1CLA/Dgn9hhpNpwmAcXo3vKmw3hXsgfEEeEIcXcJNeZUGEzZmbNgW0zfcBrMEXPsWHkxPRkI8lOwI4dhQgMp8r9FXGER/WNxJNrOMmtLiEhNM/qEal5ELQzeRSc3nJdq4ivIlEeRXhmEOIfHsoQAXNg8lSNv2Z82auDAbwZHnP0KQiZgFnlvu3+lE2Lu9tWroz+5HwztZf26XuKaGT+AR8rWtfX9YsAjeqNYEsyrxh33wirqXFHo2m8Ti965kuphu+uFpiDTALj9Q+ytwqdUVj1AnZGaF/TB0gEbGB3+PKcyvkkAeGK5kEnzeUI21FI2+t2VNfunLill8bb98RFSlYkAzXeF+xzS9K0UXxysAIG5H11LOjNfbUdUwmtXs0= theresedickson@Therese-Dickson-MacBook-Pro.local

**Comment by mleclerc00** [comment]
Hi @TKDickson 

You should be able to access socks now with the following [socks tutorial](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html)

If you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
