### ISSUE TITLE
SOCKS access for Jen Ecker

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#39509]
### Your Name

Jen Ecker

### Your Email

jen.ecker@adhocteam.us

### Your Role

UX Lead

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7GVc9wJHjmC4iCSw9s/L8oUNxPsqWBXM62R219JloHKoEsqtqEUwJPEDsQpRXEr957QpjFYDqHtO8QxEPBzFXfVXH1huY4OxvTcwYZz++kIp8EY1yHo4cbtoqpJJDZLQA+HzOU/Hw6gZGrEyXqBpD0GI9V/XyQi7D4+yoNE2ojxUojDPCW1WID+ZxSgUDEGFjFnFxIhF5pJcH8XE7F21fRFxz3D5uP6T5aeI1FXYIUjk8mhjayklpfFsGEAeUSLWV9/znUiFewZolOJtEDngtSI2Ps/89pIwZU8Enz2audn1f5atyvFDFbRn/GZqMzib1O+bamp19tv0fEbsLeABBKFKEjT55tHd+2A2pa5mCJO7t2+7sTZdvD8HqAWNaJakGIhh5OGbdsxPRjf269AHRdHk+re5af7Lh0br5LDJArOx9WfvE1W8owh1Fj6doOuddw8B1nUEweLtaerYyVOEgSzlXV5BVR0b0zCtHir3l6QtCGq8Oaz+ySOYt1rZZID8= jenniferecker@Jennifer-Ecker-Macbook.local

**Comment by rmtolmach** [comment]
@drjecker Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
