### ISSUE TITLE
[UX] Share Translated Control Text with UI Control Folks

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39508]
## Background Info
Refer to slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1648835642596929)

## Description
We need to share the following translations:
    -  For va-text-input, the two items needed are:
        - Required
        - Max. {Number} characters
    - For Date, the items I’m seeing are:
        - Required
        - Please provide a response
        - Please provide a valid date
        - Please enter a year between {minYear} and {maxYear}
with these folks:
    - Carol Wong
    - Katy Bowman

**Comment by acrollet** [comment]
Sent to Carol and Katy and pinged on Slack: https://dsva.slack.com/archives/C01DBGX4P45/p1651871439064789?thread_ts=1649781669.566199&cid=C01DBGX4P45
