### ISSUE TITLE
Finalize HEC documents for translation with hybrid MVP designs

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#39516]
**User guide, Product guide, FAQ, Cover letter**
- [x] Update content to reflect Hybrid MVP for accessibility
- [x] Insert final design (approved by sitewide content IA) to documents
- [x] Have another team member audit/approve work
- [x] Turn over to PM to give to VA-PO for translation at after text test of widget with Jaws is a pass

**Comment by CarlDickerson** [comment]
@Documents for review can be found in Box at https://mostudio.app.box.com/folder/167650627839

**Comment by tameracorson** [comment]
Documents from v1 MVP returned, requesting edits from Randi Hecht.  Documents turned over to Carl 7/20/22 via email and uploaded into BOX for reference https://mostudio.app.box.com/folder/167927453552

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/b341eeb0-af03-43f4-8d48-341789e4a652)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/98368cd0-318d-4537-acfd-7f023cd089db/download](https://app.zenhub.com/files/133843125/98368cd0-318d-4537-acfd-7f023cd089db/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/db699c89-a438-4d45-912a-44cb5ec36720/download](https://app.zenhub.com/files/133843125/db699c89-a438-4d45-912a-44cb5ec36720/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/9a849f51-60fa-4ebd-b00b-672c540718ae/download](https://app.zenhub.com/files/133843125/9a849f51-60fa-4ebd-b00b-672c540718ae/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/f8fa1636-51b3-47b2-bbd9-13d59ab91d89/download](https://app.zenhub.com/files/133843125/f8fa1636-51b3-47b2-bbd9-13d59ab91d89/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/756545be-b90e-4c60-a715-d1e3a737b8d6/download](https://app.zenhub.com/files/133843125/756545be-b90e-4c60-a715-d1e3a737b8d6/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/2ea46b33-cd2e-442e-a5c6-37e575897ba1/download](https://app.zenhub.com/files/133843125/2ea46b33-cd2e-442e-a5c6-37e575897ba1/download)
