### ISSUE TITLE
IA Feedback-Midpoint Review- VA Notify Forms Strike Team, In Progress Reminders

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#39512]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
Emails designed to prompt people to complete tasks perform far better when they describe the benefits of completing the desired task and finish with a clear call to action. 
## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- submit email subject line for content review

**Should:**
- Describe what needs doing and how it might benefit the user, (e.g. "Make sure the  information we have on file is correct and up to date so you can get all the benefits you deserve.") 
- Separate out the name of incomplete form from the call to action (see example below)
______
#### [Finish your application](https://www.va.gov/view-change-dependents/)
______

**Consider:**
- Making the CTA a button 
## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by megansiddle** [comment]
@jimuhh the email subject line will be "You have an unfinished application on VA.gov"

**Comment by megansiddle** [comment]
We have updated the email to include: “Make sure your application process is complete so the VA can properly process your request.”
We decided to not follow the actionable link recommendation due to the prior feedback from accessibility and the concerns with screen readers.
