### ISSUE TITLE
Adjust Direct Deposit CTA widget to show different messaging to DSLogon LOA3 users

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3953]
## User Story: 

As a DSLogon LOA3 user on the Direct Deposit static page, I want to be told that I'll need to sign in via ID.me or MHV to access the Direct Deposit feature.

## Tasks 
- [ ] adjust the logic in the CTA widget to show different content (temporary filler content at the moment) if the user is signed in as a DSLogon LOA3 user

**Comment by erikphansen** [comment]
@Samara-Strauss I assume this should be blocked as well? I'm adding that tag.

**Comment by Samara-Strauss** [comment]
@erikphansen yes, thank you.

**Comment by Samara-Strauss** [comment]
We're not doing this. Closing.
