### ISSUE TITLE
Login.gov Account Created Page

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#39537]
Create a page that users are redirected to after they have initially created a login.gov account

## If user IAL1
1. page must list the items that the user can now access as an IAL1 account
1. page must list what a verified account can do to demonstrate the difference
1. page must list how a user can verify their account
1. page may list details of what to expect during the verification process and how they can get help
## If user IAL2:
1. page must list the items that the user can now access as an IAL2 account

**Comment by asg5704** [comment]
Closing until we have MHVIP go-live date
