### ISSUE TITLE
Document metrics for error 104

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#39548]
- [x] Produce report for avg number of 104 errors before, during, and after Trevor bug fix
- [x] Produce report which shows % of users for missing idme/logingov uuids, in particular before during, and after Trevor bug fix

**Comment by joeniquette** [comment]
Numbers from the backend reporting of error 104:
![image.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/67c96d15-5040-4bcc-a22d-8f1c9269d8da) 

Frontend reporting of errors appear to be reporting an anomaly which requires further frontend and backend investigation. As can be seen in the image below, 104 errors have been reported on the frontend before and after the bug was fixed which caused some users to not be able to re-attempt auth as they normally would be able to:
![image.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/6ec806fc-0faa-458f-9f96-b90594387ec0)
[Source of graph](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220101&_u.date01=20220405&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=login-error-code-104&explorer-graphOptions.selected=analytics.nthWeek/)

**Comment by joeniquette** [comment]
[Loki query](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22,%20filename%3D~%5C%22.%2Bjson.log%5C%22%7D%5Cn%7C~%20%5C%22(%3Fi)User%20attributes%20is%20missing%20an%20ID.me%20and%20Login.gov%20UUID%5C%22%5Cn!~%20%5C%22(%3Fi)context:custom%5C%22%5Cn!~%20%5C%22(%3Fi)extra_context%5C%22%5Cn%7C%20regexp%20%5C%22(%3FP%3Ctime%3E%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd)%20(%3FP%3Cprocess_name%3E%5C%5C%5C%5Cw%2B.%5C%5C%5C%5Cd)%20%5C%5C%5C%5Cs%2B%20(%5C%5C%5C%5C%7C)%20(%3FP%3Cjson%3E.%2B)%5C%22%20%5Cn%7C%20line_format%20%5C%22%7B%7B.json%7D%7D%20%5C%22%23Remote_IP%20%3D%20%7B%7B.named_tags_remote_ip%7D%7D%5C%5Ct%5C%22%5Cn%7C%20json%22,%22maxLines%22:5000,%22datasource%22:%22Loki%20(Prod)%22%7D%5D) to see problematic 104 errors. What I mean by problematic is that we are getting the error 104 from a login that is something other than context=custom.

Another view of same board: https://grafana.vfs.va.gov/d/PWC9MJ47k/vsp-identity-log-queries-dashboard?editPanel=9&orgId=1&from=now-1h&to=now&var-env=Loki%20(Prod)

You will need to change the picker to set it to past one hour and env set to loki prod

**Comment by joeniquette** [comment]
The intent of reporting on the numbers of 104 errors is complete. During the process of identifying the numbers we discovered that there are still a number of users who seeing this error. [This](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22,%20filename%3D~%5C%22.%2Bjson.log%5C%22%7D%5Cn%7C~%20%5C%22(%3Fi)User%20attributes%20is%20missing%20an%20ID.me%20and%20Login.gov%20UUID%5C%22%5Cn!~%20%5C%22(%3Fi)context:custom%5C%22%5Cn!~%20%5C%22(%3Fi)extra_context%5C%22%5Cn%7C%20regexp%20%5C%22(%3FP%3Ctime%3E%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd)%20(%3FP%3Cprocess_name%3E%5C%5C%5C%5Cw%2B.%5C%5C%5C%5Cd)%20%5C%5C%5C%5Cs%2B%20(%5C%5C%5C%5C%7C)%20(%3FP%3Cjson%3E.%2B)%5C%22%20%5Cn%7C%20line_format%20%5C%22%7B%7B.json%7D%7D%20%5C%22%23Remote_IP%20%3D%20%7B%7B.named_tags_remote_ip%7D%7D%5C%5Ct%5C%22%5Cn%7C%20json%22,%22maxLines%22:5000,%22datasource%22:%22Loki%20(Prod)%22%7D%5D) loki query shows users who are being returned to va.gov after calling auth which is supposed to travel from eauth through idme, to the respective CSP (dslogon or mhv), and be returned back to va.gov without an idme uuid.

On 4/28 I sent over three sets of transaction IDs to Damien which should show what happened to these users inside the eauth logs. Damien stated he could not find any of these logs with the transaction IDs and requested we send over ICNs. I sent over ICNs on the 29th. Damien confirmed he saw one of the logs showing that a user did go through eauth and be returned back to va.gov without an idme uuid but should have. He is going to investigate further.

This document has the log information produced by vets-api: https://docs.google.com/document/d/1W8iZkbCH62TiVxo-eC-WN6wxDbZHU6cZsvpcBofdc-s/edit

**Comment by joeniquette** [comment]
moving to a blocked state until we hear back from IAM (Damien).

**Comment by joeniquette** [comment]
someone from IAM was assigned to the servicenow ticket. Received a question on 9May22 and responded back. They wanted to get some timelines for when the logs occurred because they were not able to find the logs in question as displayed in the ticket. I gave them the timestamps from the logs.

**Comment by joeniquette** [comment]
I was sent logs from the IAM team (from ISAM) that matched our log instances. After looking at the DSLogon example here is what I found:
Ok so I looked through the logs that Brent provided which show what your talking about here with the eauth_uid. That value alone wouldnt cause an issue but then when we parse the gcids from eauth and it also does not have a valid IDme or Login.gov uuid then we cannot log a user in. The logs prove to me that eauth sent us both that eauth_uid with first.m.last but also the gcids did not include the idme uuid.

here are the gcids from that log which had the eauth_uid=first.m.last:
<stsuuser:Attribute name="va_eauth_gcIds" type="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
<stsuuser:Value>1028552135V657740^NI^200M^USVHA^P|2986253^PI^200CORP^USVBA^A|1186873960^NI^200DOD^USDOD^A|1186873960^PI^200CH^USVHA^A|1028552135^PN^200PROV^USDVA^A|595162182^PI^200BRLS^USVBA^A</stsuuser:Value>

You will notice here that there is no VIDM value in there. The user then logs in with idme after, according to the logs, and we see the matching ICN to prove its the same person, and also that the EDI (Dslogon identifier) is in the GCIDs of the IDme CSP login

**Comment by joeniquette** [comment]
Reviewed the MHV logs sent by IAM and its the same as the DSLogon logs they sent. They prove that ISAM is not sending us the IDme uuid even though we are making proper MHV through idme calls (outbound). I reported this to Traci from the IAM team and she stated she will run this by the team on 16JUN22.

**Comment by nsoutouras** [comment]
Still waiting...

**Comment by nsoutouras** [comment]
Still waiting.... some more.

**Comment by joeniquette** [comment]
Im moving this to backlog, this effort likely will not get resolved and if the SiS pilot is successful we will not have this issue anymore.
