### ISSUE TITLE
[Placeholder] Update the debt portal notifications with the new Combined Debt Portal URL

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#39545]
## Issue Description
There are plans to update the breadcrumbs as part of the Combined Debt Portal's launch, so we need to review and update the URLs in the VA Notify notifications. The following notifications will need to be updated:
- Debt notification
- Financial Status Report submission 

---
## Tasks
- [ ] Review and update the notifications with the new URL

## Acceptance Criteria
- [ ] The notifications have been updated

**Comment by denisecoveyduc** [comment]
@ScottyRJames Can you check into the notification portal too see which URL the debt notification is pointing to?

**Comment by denisecoveyduc** [comment]
Notifications are set up to go to the manage-va-debt url. which is what we want. No change needed
