### ISSUE TITLE
Documentation Cleanup SiS and MHV IP

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#39549]
- [x] convert sign in service from google doc to markdown doc
- [x] add important diagram sources to github
- [x] move MHV inherited proofing documents into "Inherited Proofing" folder @nsoutouras

**Comment by nsoutouras** [comment]
New Inherited Proofing Folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Inherited%20Proofing

**Comment by nsoutouras** [comment]
New SiS Folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Sign-In%20Service

**Comment by joeniquette** [comment]
I added all the diagrams I have to this location: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity/diagram_sources

**Comment by joeniquette** [comment]
converted sign in service pkce google doc to a github doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Sign-in-service_PKCE-OAuth.md
