### ISSUE TITLE
Spike: Redesign School search filters

### ISSUE THREAD

**Issue by jfinnern** [department-of-veterans-affairs/va.gov-team#39541]
The Schools filter checkboxes currently include "filters" (Public, Private, etc.) and "sub-filters" (High school, Flight, etc.) which can lead to confusing search results.

Perform analysis on updating the filter checkbox display and/or behavior to provide more transparency to the user about how the search filters are performing.

**Comment by AdamFreemer** [comment]
On the topic of exclusiveness for the Filter checkboxes:

> (Without regard to how the comp tool design was developed), all approved facilities are designated as 1 of these 3 types.  This determines T&Fs payments (among other approval related things) like Brian said.  The facility code identifies the profit status.  The 1st character in the facility code is either ‘1’ for public, ‘2’ is for profit and ‘3’ indicates private (aka non-profit).
>  
> 
>  
> Each of the remaining types are also categorized as public, for profit or non-profit described above.  These additional school types are not strictly determined by the facility code (other than Foreign  by location indicated by the last 2 digits of the facility code).  Flight, Correspondence and High Schools are designated by the type of training offered at an approved institution.  To expand on what Joe mentioned- flight training may be offered at a public, for profit or private college/university or the flight school can be a stand-alone NCD school that is public, for profit or private.
>  
> IHL training vs. NCD training vs OJT/APP training is designated the 2 digit of the facility code.  Flight, correspondence and high schools are not separately identified by the 2 digit, they are sub-types of training rather than specific categories.
>  
> 
> Clear as mud…
>  
> Cinda
>  
> From: Preisser, Joseph, VBAVACO <Joseph.Preisser@va.gov> 
> Sent: Monday, April 4, 2022 9:19 AM
> To: Grubb, Brian D., VBAVACO <Brian.Grubb@va.gov>; adam.freemer@accenturefederal.com
> Cc: abelardo.blanco@accenturefederal.com; m.c.shah@accenturefederal.com; Quattrini, Cinda, VBAVACO <cinda.quattrini@va.gov>
> Subject: RE: [External] RE: Institution Tags
>  
> Good morning, all.
>  
> The classifications below are generally exclusive.  Only exception that I can think of is when a university (typically Public) offers flight training as a non-college degree program.  Looping in Cinda in case, I missed something.
>  
> Thanks,
> Joe

**Comment by mrblanco1** [comment]
This Spike was completed and should have been closed. This feature was developed and tested (passed) with https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/39715
