### ISSUE TITLE
SOCKS access for [ian hundere]

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#39557]
### Your Name

ian hundere

### Your Email

ian.hundere@oddball.io

### Your Role

devops engineer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHWpJOXRjAtA/mONNh9QVPGjPgIuQ1uV0DcAFdxs4ajhGGErN2QgemsYYGb7Gg9QT0jscI7WRWvELhKOPAdDbkdPaMNgpX4iuJpzQT6M8ETSSIuodzc7dJEK2qXc60tW/lNY/SUL5MQx6Hf2uk46vfr3wNShK+HUpfNOLbKF88djHYkaWbKbOCRjHCphhTySoxkV158iXiTzcRZYrlBW3s+VGHnpNDiXGQMhRkxJOf7Y6E0EIPtgxtFrUtooWp2GbtSA42OiySw/w8SOx2U/Uo3WNWk+Yo3q6ehDkZs3t4xGy6YPch5JG6gNiU2e8VuHaSz116mOgwkb7JDSDuCZ3eHlnxNVBchwnr6BaoWEOgGS+IVSawEmZjvHaweEHbo0yEtrew0nafgTwTSIAhBXXQHiYGW6+XpXBeTMMKof3uzwf4SyuHxXePcXbo3gt0KOujL0Z0+LGk1JzH4zLINjocrzUfN5mARgreBtwx3lbUvGCtQaTki7oSxiqtX2wdOnk= ianhundere@MacBook-Pro

**Comment by rmtolmach** [comment]
@ianhundere: access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
