### ISSUE TITLE
NumberInput: Web Component Development

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#39550]
## Description
Build a web-component version of our [NumberInput React component](https://design.va.gov/storybook/?path=/docs/components-numberinput--default).

## Details
Most of the inner workings of this component can be replicated from: https://design.va.gov/storybook/?path=/docs/components-va-text-input--default
Additional missing props: `max`, `min`, and `pattern`
May need to consider setting the inputmode and type to be locked down to number related properties

## Acceptance Criteria
- [ ] `va-number-input` is written and added to Storybook
- [ ] E2E tests are written
- [ ] Add Chromatic link to https://github.com/department-of-veterans-affairs/va.gov-team/issues/39674, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by pdavies88** [comment]
Action Item: Create Discovery Ticket that explores combining `va-text-input` and `va-number-input` into a `va-input` component. The difference between to two components will be the props of `max`, `min`, and `pattern` which are used on `va-number-input`. Part of Discovery ticket should be to loop in the forms library team to get their opinions on combination as well.

**Comment by caw310** [comment]
Staging review scheduled for 4/21
