### ISSUE TITLE
Pass MHV IP success param from callback to frontend

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#39555]
Login.gov will make a call to vets-api informing the backend that the inherited proofing was successful or not. The backend must pass a parameter to the frontend to indicate that the IP process was successful to enable the Frontend to display a "successful IP info page"

**Comment by joeniquette** [comment]
Login.gov will make a call to vets-api informing the backend that the inherited proofing was successful or not. The backend must pass a parameter to the frontend to indicate that the IP process was successful to enable the Frontend to display a "successful IP info page"

**Comment by asg5704** [comment]
Closing until we have MHVIP go-live date
