### ISSUE TITLE
[Research] Profile: MHV Research -- Card sort analysis

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#39562]
Tasks
- [ ] Analyze results from card sort
- [ ] Factor results into [final recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/final-synthesis.md)

**Comment by andaleliz** [comment]
@SKasimow (cc @Samara-Strauss while Sharon is onboarding), FYI I created this ticket to add to the upcoming sprint. Since we have quantitative data, I'll need to do a separate analysis of these results outside of the topline summary.

**Comment by Samara-Strauss** [comment]
Great, thanks for letting us know, Liz!

**Comment by andaleliz** [comment]
I included answers to the questions we wanted to answer through a card sort in a [section of our topline summary.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/mhv-user-interviews/topline-summary.md#card-sort-findings)
