### ISSUE TITLE
IaC Decision Doc

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39575]
We should evaluate a few different IaC frameworks to make sure we're choosing the right one.

Example decision doc: https://vfs.atlassian.net/wiki/spaces/AMT/pages/1959067732/Identity+Broker+Decision

This doesn't have to follow the example in ^. 

It doesn't have to be long, but it should be thorough and compelling.

## Done when

- [ ] A decision doc is created in confluence
- [ ] Approval by Thomas and perhaps Demian

**Comment by mb365247** [comment]
Only RFC is required.
