### ISSUE TITLE
RFC: Keycloak IaC Provider

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39578]
From the decision doc, we should generate an RFC recommending the chosen IaC approach from the decision doc. Please use the template: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2110226433/RFC+Template

**Comment by kjduensing** [comment]
@iriteshp since you're working on learning the keycloak terraform provider as well, can you start filling out this RFC please? https://vfs.atlassian.net/wiki/spaces/AMT/pages/2158067713/DRAFT+Keycloak+configuration+will+be+managed+by+Terraform+to+support+automation

**Comment by iriteshp** [comment]
completed RFC.

https://vfs.atlassian.net/wiki/spaces/AMT/pages/2158067713/Keycloak+configuration+will+be+managed+by+Terraform+to+support+automation
