### ISSUE TITLE
Analytics Implementation | 10-10EZ | Short-Form

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#39570]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

## Description

- As a Veteran applying for health care, I would like to expedite the HC application so I can complete it faster, remove blockers, and have less confusion.

## Goals

- Track changes in drop-off and submission rates.

-[ ] Submit new page for confirmation for Veterans who self disclosure a disability rating 50% or greater 

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

<br>

- **Who is this request for?**

This is a request from the 10-10EZ team to add GA tracking to a newly created confirmation page on the 10-10EZ Short-Form. This page applies to Veterans that self disclose a disability rating 50% or greater.

<br>

      
- **Provide the link(s) for Google Analytics implementation or QA**
  
       path: '/health-care/apply/application/va-benefits/confirm-service-pay'    

<br>

 **When is the launch date?**

   - Mid-April 2022

<br>

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jennaouellet** [comment]
Hi @SKasimow! Since the GA page tracking happens automatically, are there further changes to the form structure that require editing the form submission/start/failure events? If those form events don't need to be modified and the form name is staying the same, then we will only need the different funnels for the Domo dashboard.

**Comment by SKasimow** [comment]
Hi @jennaouellet -ok thanks. I was under the impression that if it was a new page/new URL we had to have your team implement but if that's not the case, great! We're adding a new confirmation page for the shortened form so don't think that impacts events.

@hdjustice will be picking up this project going forward so will complete this request for the additional funnels in the DOMO dashboard. Do you have the current spreadsheet of the funnel we can use as a starting point?

**Comment by jennaouellet** [comment]
@hdjustice Please let me know if you haven't yet received the current spreadsheet from Michelle or would like it sent over again. As the GA work here is complete, I'll close out this ticket and we can use the existing dashboard request ticket to track the Domo work. Thanks!

**Comment by hdjustice** [comment]
thanks @jennaouellet !  I have one for 10-10cg but not for 10-10ez.  Do we have a spreadsheet for that?

**Comment by SKasimow** [comment]
@hdjustice Here's the spreadsheet for [10-10EZ](https://docs.google.com/spreadsheets/d/1XxkQhWL17AJnVmMg49RY7f2l-vmjR5lolXl9SuzOn6w/edit?usp=sharingfunnel)
