### ISSUE TITLE
Iterate designs to include content and address change by sitewide

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#39581]
*VA-PO would like a button to on page that would take Veteran directly to the appropriate address change in profile that will change the address in HEC data used to build the 1095-B.  This would decrease the need to call the HEC call center for this issue.*
- [x] add content surrounding address change delay in online availability of updated 1095-B form (4 business day delay)
- [x] iterate desktop and mobile designs to include address change widget based off of sitewide design construct
- [x] upload copy of final designs GitHub repo by date of iteration

**Comment by JordanSWhite** [comment]
Ask Kit for overall process

**Comment by tameracorson** [comment]
![1095-b_Authenticated state_Desktop.jpg](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/3869f1c3-af26-481a-af55-b266f6ded3f1)![1095-b_Authenticated state_Mobile 2.jpg](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/8fdda50f-012d-42b1-989f-89fd6deca48e)![1095-b_Unauthenticated state_Desktop.jpg](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/15e9425f-91eb-4409-8beb-7cddd5bb38a9)![1095-b_Unauthenticated state_Mobile.jpg](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/e0df96de-524b-4ad9-a795-0b86d6b11cfe)
