### ISSUE TITLE
JSON-defined permissions to Terraform config

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39587]
In order to make permissions management accessible and automatable, we need to design a machine-readable schema that describes permissions and their relationships to applications and roles. [RFC 6](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2142011842/DRAFT+RFC+6+AMT+integrators+can+describe+fine-grained+permissions+using+JSON) describes the proposed JSON schema with context. 

The next step in using this schema is to convert the JSON into Terraform configuration. 

Acceptance criteria:
- [ ] Our Keycloak config repo is created
- [ ] RFC 6 is in the `ACCEPTED` state
- [ ] The finalized JSON schema is committed to our Keycloak config repo
- [ ] A script is created that generates valid Terraform configuration
- [ ] Applying the generated TF configuration produces a valid set of permissions in Keycloak.

**Comment by kylesoskin** [comment]
Repo: https://github.com/department-of-veterans-affairs/pst-amt-keycloak-authorization-terraform-parser
RFC6: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2142011842/RFC+6+AMT+integrators+can+describe+fine-grained+permissions+using+JSON
