### ISSUE TITLE
RFC: IaC + Infrastructure Integration

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39580]
In order for us to test additional terraform capabilities, we need to integrate the keycloak terraform provider in Dev.

This allows us to test:
- webhooks on merge of config PR

We're done when:
1. A developer PRs a change to TF config in a repo
2. A developer merges the pull request
3. We see evidence of the Terraform plan being applied
4. We see the changes made in Keycloak

**Comment by kylesoskin** [comment]
@iriteshp should we call this issue "blocked", since we want to get our process together/tested first, then describe it via RFC?

**Comment by iriteshp** [comment]
@kylesoskin  yes, that sounds good.

**Comment by kjduensing** [comment]
@iriteshp can you please reference the ticket this is blocked by? if there is no existing ticket, let's create a stub and set up the blocked-by relationship.

**Comment by iriteshp** [comment]
@kjduensing @iriteshp added blocked by dependency.

**Comment by girldadmk** [comment]
@iriteshp nudge.

Publish and close...

**Comment by iriteshp** [comment]
added RFC here and it is ready to review: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/amt/rfc/keycloak-terraform-pipeline/rfc/2022/2022-07-12%20-%20Keycloak%20Terraform%20Pipeline.md

**Comment by iriteshp** [comment]
no unresolved comments on the RFC. closing the ticket.
