### ISSUE TITLE
Create Mockups for Submit 686/674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3959]
## Story
As a eBenefits Team member, I need a series of mockups showing the initial workflow and screens for the 21-686c UX/UI so that I can understand the process and proceed with development.

## Considerations 
- Develop a system (or changelog) where:
  -  Current implementation breaks from known 686 process.
  - When there is a change, note that in the mockup so the highlighted deltas are easy for FE to see.
- Consider a pre-form/wizard that establishes upfront what the user intends to do 
- Add interactivity to prototype to simulate branch-points in 686 process.
- Consider form configuration tool

## Tasks
- [ ] Create an MVP mockup based on current code in VA.gov staged environment.

## Acceptance Criteria
- [ ] An initial draft of a mockup that represents the current state of Submit 686 is shared in GH

## Next steps
- Check that the rainbows work functions and get it connected as an MVP, with only 2 out of 10 of the current business logic workflows in place.
- Add functionality incrementally

**Comment by sporeboy** [comment]
XD walkthrough for Add Dependent workflow is here: https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/
