### ISSUE TITLE
Discovery: Can we use ESLint to Encourage use of Web Components vs CSS Classes

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#39607]
## Overview
Currently we have CSS classes via Formation that are used to create components that mirror the look and feel of existing Web Components. The goal of this discovery is to see if we can leverage ESLint to create a rule or rules that would inform users when they using the css classes listed in the parent ticket that there is a Web Component available to them that would perform the same task and is the preferred way to complete the work.

## Parent Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37934

## Acceptance Criteria
- [ ] Outline if this work can be done, and if so what the best approach would be to notify developers that Web Components not CSS Classes are the best way to build components via linting

**Comment by bkjohnson** [comment]
Here's an [example of how linting could have guided someone to use `<va-telephone>` instead of `<a href="tel:..."`](https://github.com/department-of-veterans-affairs/vets-website/pull/21799#pullrequestreview-1053359120).

**Comment by bkjohnson** [comment]
And [another example](https://github.com/department-of-veterans-affairs/vets-website/pull/21926#discussion_r945960467).

**Comment by bkjohnson** [comment]
Closing - will be tracked in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/864
