### ISSUE TITLE
[SW-Content] OCTO review of Education Rate page - Post-9/11 GI Bill (Chapter 33) rates 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39615]
## Story
OCTO review of Education rates (Chapter 33 rates) work from Sitewide content team

## Resource
#8593

## TASK
- [x] Review composed content for Education rates (Chapter 33 rates)
http://preview-prod.vfs.va.gov/preview?nodeId=1009

## Acceptance Criteria
* Provide guidance and feedback to team before approval to proceed.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I reviewed this page, made some edits, changed the dates and rates. I'd like someone on the team to double check the dates and rates to make sure I didn't miss any of them. Can you create a ticket for this work for this sprint? Another task you should add to the ticket is to update the past rates section, to drop 2019 and add 2022 (which would be (on the legacy page) 2021-2022. I'll probably need the same kind of double check for the other rates pages I'm working my way through. Thanks!

**Comment by RLHecht** [comment]
Thanks, @bethpottsVADEPO I created a ticket to check the rates. I'm moving this ticket to Validate do you don't get confused with all the others you're still reviewing. But I'll leave it open for now so it doesn't get lost and I'll set up separate tickets for sending all of the pages to the stakeholders and all that follows once we're ready!

**Comment by RLHecht** [comment]
This work is complete. Closing!
