### ISSUE TITLE
When VAOS service flag is on, the eligibility check uses the wrong api call to retrieve past appointment history

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#39624]
When the toggle flag is set to true for VAOS Service (v2), the eligibility check is using the v0 api call to get the past appointment history. It should be using the v2 api call to get past appointment history.  

![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/0b37aa63-05a3-4314-8c45-3befebea06ff)

**Comment by simiadebowale** [comment]
V2 End point we will be calling: /vaos/v2/appointments?_include=facilities,clinics&start=${start}&end=${end}&statuses[]=${status}
sample response body:
{
"attributes": {
"cancelationReason": null,
"cancellable": true,
"clinic": "437",
"comment": "Follow-up/Routine: I have a headache",
"contact": {
"telecom": [
{
"type": "email",
"value": null
}
]
},
"description": "Upcoming in person appointment",
"end": "2022-02-21T18:19:34",
"id": "00aa456va",
"kind": "clinic",
"locationId": "983",
"minutesDuration": 30,
"patientIcn": null,
"practitioners": [
],
"preferredTimesForPhoneCall": [
],
"priority": 0,
"reason": "Routine Follow-up",
"requestedPeriods": null,
"serviceType": "primaryCare",
"slot": null,
"start": "2022-02-21T18:19:34",
"status": "booked",
"telehealth": null
},
"id": "00aa456va",
"type": "Appointment"
}

**Comment by ldelacosta** [comment]
Checked with @jenniemc that this work can be done before V2 rollout.
