### ISSUE TITLE
 [SW-Content] OCTO review of Montgomery GI Bill - Selected Reserve (Chapter 1606) rates

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39631]
## Story
OCTO review of Montgomery GI Bill - Selected Reserve (Chapter 1606) rates work from Sitewide content team

## Resources
#8635

## TASK
- [ ] Review composed content updated for Montgomery GI Bill - Selected Reserve (Chapter 1606) rates
http://preview-prod.vfs.va.gov/preview?nodeId=5449

## Acceptance Criteria
* Provide guidance and feedback to team before approval to proceed.

**Comment by RLHecht** [comment]
old ticket. closing
