### ISSUE TITLE
[04/08/22] OSM Clinic Report

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#39634]
## Description
Individuals from the OSM group tasked with increasing the adoption of OSM has requested some more detailed data - instead of just the sites that have enabled OSM at this moment, they are looking to see what clinics/specialties at said facilities have it enabled. 

---

## Acceptance Criteria
- [x] Confirm request with Lindsay and Shane
- [x] Build out report 
- [x] Post draft to team Slack channel for review by Paras and Lindsay
- [ ] Review data with Shane
- [ ] Approved by Shane 
---

**Comment by Cmjones233** [comment]
Reviewed out Power bi meeting and currently building out dash

**Comment by Cmjones233** [comment]
need to update filter and work with Justin for a notifications alert automation

**Comment by Cmjones233** [comment]
After second round of feedback 4/12 new dashboard has been posted to slack for review

**Comment by Cmjones233** [comment]
clinic ien dropped from table and approved by Shane
