### ISSUE TITLE
Quality Assurance Feedback - Midpoint Review - VA Notify Forms Strike Team, In Progress Reminders

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#39630]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Thanks for using TestRail!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- As you reach completion of your feature, we recommend adding additional details to the test cases in your test plan so that the feature is ready for testing once we reach the Staging Review.
- Read through [Getting Started with TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/Getting-Started-with-TestRail.1600716881.html)

**Consider:**
None

**Comment by megansiddle** [comment]
Thank you so much for providing the link! Its very helpful. I updated the test cases as needed. Thank you!
