### ISSUE TITLE
Accessibility Feedback - Midpoint Review - VA Notify Forms Strike Team, In Progress Reminders

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#39640]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
Thank you for incorporating the feedback from the Design Intent!

No must/should/consider changes to the final design, but here are some notes on implementing this in code for the engineers who work on it:
* A lot of HTML emails use `<table>`s for layout, since many email clients don't support more modern layout techniques. If you go this route, make sure any tables have `role="presentation"` on them. Exceptions would be actual data tables, but I don't think you're planning on adding those.
* Even with the table layouts, be sure to follow other accessibility and semantic HTML coding best practices. A few things that might be easily missed:
  - Remember to set a `lang` attribute on the HTML document.
  - Use a logical heading structure: H1 for the main topic of the email, and any sections/subsections as H2s/H3s/etc. (With just one in-progress form, I think you could get away with just an H1 and no H2s/etc. As more forms are included and the message becomes more complex that may change.)
  - Totally okay to use semantic sectioning elements like `<section>` and `<article>` where appropriate, even if you're dropping them inside the table layout. (Email clients that support them will provide extra value to assistive technology users. Email clients that don't should ignore them.)

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by megansiddle** [comment]
Thank you for your insights! I've sent them to our team.
