### ISSUE TITLE
Add Utility Keycloak monitoring in Datadog

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39646]
**Description:** As a user I need to be able to track usage and issues for keycloak by adding keycloak monitors in datadog

**Acceptance:** This ticket would be considered complete by executing below tasks:

- [x] sending keycloak utility metrics to datadog
- [x] add utility-specific monitors in datadog

**Comment by kylesoskin** [comment]
Metrics are now going from Utility to datadog. @iriteshp is going to make a dashboard in datadog for them that is based off the other one carl made for dev.

**Comment by iriteshp** [comment]
Added new dashboard in Datadog for Utility.

https://app.datadoghq.com/dashboard/fhp-4wm-dgv/amt-dashboard?from_ts=1650912484482&to_ts=1650916084482&live=true
