### ISSUE TITLE
ArgoCD + Dex + Keycloak Local Setup

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39643]
## Purpose
- Supports Console Services Team in integrating ArgoCD to Keycloak
- Support Console Services Team's AND AMT's initiative work

## Notes
- CST has set it up so far to NOT use Dex
- We need to incorporate Authorization
- ~We should assume we're using Dex since this is how Utility works~ Not using Dex
- If Keycloak is unavailable, Dex apparently doesn't allow for any auth method - this is a showstopper if we can't get around this

## Acceptance Criteria
- [x] Be able to demo an integration of ArgoCD + Dex + Keycloak locally
- [ ] Handles GitHub + Login.gov identity merging

## Next steps
Set up the same integration for a dev ArgoCD instance.

**Comment by mb365247** [comment]
Carl working w/ Demian and would need more time.

**Comment by calquisola** [comment]
blocked by https://github.com/department-of-veterans-affairs/github-user-requests/issues/10552
