### ISSUE TITLE
AWS access for Michael Chaffee

### ISSUE THREAD

**Issue by mchaffee-tw** [department-of-veterans-affairs/va.gov-team#39649]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Michael Chaffee

### Your Email

michael.chaffee@va.gov

### Your Team, Role, and Company

Digital Health Platform (DHP), Lead Developer, Thoughtworks

### Desired AWS Access

Copy permissions from @yonidoronpeters 

### Access Expiration

ongoing

**Comment by jbritt1** [comment]
### For AWS Access

User: Michael Chaffee
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
Admin level: no

**Comment by jbritt1** [comment]
First-time login credentials provided to user via Slack DM at this time.
