### ISSUE TITLE
AWS access for Aurelio Nogueira

### ISSUE THREAD

**Issue by aurelionog-thoughtworks** [department-of-veterans-affairs/va.gov-team#39648]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Aurelio Nogueira

### Your Email

aurelio.nogueira@thoughtworks.com

### Your Team, Role, and Company

Digital Health Platform (DHP) Team, Developer, Thoughtworks

### Desired AWS Access

Copy permissions from @yonidoronpeters

### Access Expiration

ongoing

**Comment by td-usds** [comment]
Reached out to VOR, awaiting confirmation

**Comment by rmtolmach** [comment]
@aurelionog-thoughtworks: no. Someone on our end will keep reaching out to the VOR for confirmation. If access is granted, this ticket will be updated and you will be DM'd your AWS credentials over Slack by someone on the Infrastructure team.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS access approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user via Slack direct message (DSVA workspace) at this time.
