### ISSUE TITLE
SOCKS access for Michael Chaffee

### ISSUE THREAD

**Issue by mchaffee-tw** [department-of-veterans-affairs/va.gov-team#39650]
### Your Name

Michael Chaffee

### Your Email

michael.chaffee@va.gov

### Your Role

Lead Developer

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA4Drwn6PRCl9zPZ13oIf972nlMQK11baSy29NbotgOa mchaffee@thoughtworks.com

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
