### ISSUE TITLE
Analytics Implementation or QA Support for [Product]

### ISSUE THREAD

**Issue by Bernardo994** [department-of-veterans-affairs/va.gov-team#39662]
# Google Analytics Implementation or QA Request

## What this form is for = 

**I need to collect metrics on this web address: Contact Us | VA Wilmington Health Care | Veterans Affairs (https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an)**

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [ ] Google Analytics implementation
     - [ X] QA

- **Who is this request for?** This is for Wilmington VAMC

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    
    
- **Provide the link(s) for Google Analytics implementation or QA** 
  
    - [Insert link(s)] https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an
    
- **When is the launch date?** ASAP
    - [Insert launch date]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_ I need to know how many times this link has been visited: https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jennaouellet** [comment]
Hello! Which metrics on the page section would you like to track? Since the parent contact-us page is already being tracked, would an additional event that fires when a user views this section be sufficient? This would give you a count of times the section was seen but would not differentiate if it was scrolled to or directly entered from the full URL after the #.

**Comment by jerinb-sdi** [comment]
GTM QA has been completed for this - events fired.

**Comment by jennaouellet** [comment]
Hello! The change has been published to GTM. Once production data is flowing in to GA, I will send over the report you can use to track views to this section of the page. Thanks!

**Comment by jennaouellet** [comment]
Hello, the event is now live and collecting data. To view how often this section is viewed, [this report ](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventAction:wilmington-health-care-contact)contains all views to that section beginning from April 24th. If you run into any issues accessing the report, please let us know. Thank you!
