### ISSUE TITLE
[Enabler] Create a plan for Syncing GIDS files in Staging and Prod

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#39669]
## Issue Description
Create a plan for Syncing GIDS files in Staging and Prod.

---
## Tasks
Dwight Mann and team will create a plan to sync GIDS files in Staging and Production.

## Acceptance Criteria
Dwight Mann and team will create a plan to sync GIDS files in Staging and Production.

The plan has to be reviewed and approved by Brian Grubb (EDU), Manish Shah, and Abe Blanco.

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/3a959ad9-59b5-4e36-b3b4-b99f49869d41)

**Comment by af-manish** [comment]
Files have been geocoded in staging environment. Please verify staging and compare to prod.
