### ISSUE TITLE
Update Synthetic Monitor Creation / Maintenance Document

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39677]
# Description
Platform engineers need to be able to understand how the Datadog hosted synthetic monitors are created and how to maintain them going forward.

## Tasks
- [x] Adapt this document about [best practices for alerting](https://vfs.atlassian.net/wiki/spaces/TTT/pages/1801617441/Canary+Alerting+Best+Practices) that is currently targeting AWS Cloudwatch and canaries to target Datadog

## Acceptance Criteria
- [x] Updated best practice patterns for creating, configuring, and maintaining synthetic monitors is available for internal use in our Confluence space

**Comment by rbeckwith-oddball** [comment]
Updated document (still in progress) can be found [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2164785226/Synthetic+Monitoring)

**Comment by pjhill** [comment]
Looks to be in a good state, thanks!
