### ISSUE TITLE
Access for Eric Murphy

### ISSUE THREAD

**Issue by murphytwin** [department-of-veterans-affairs/va.gov-team#39676]

**Comment by jbritt1** [comment]
Please provide a description of the access you are requesting.

**Comment by murphytwin** [comment]
I am part of the VA Spike team. I am requesting access for work performed on Console UI
https://platform-console-ui-dev.vfs.va.gov/
--

**Comment by jbritt1** [comment]
I am thinking we could likely start with SOCKS. I am going to point you back to the documentation for setting up and accessing the SOCKS proxy https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html and close this ticket as following that prescribed process will automatically make a new one for you as you go through them and it will have everything we need to get you squared away.

**Comment by murphytwin** [comment]
@jbritt1 how do i submit a new request with the instructions that should appear?

**Comment by jsgarmon** [comment]
SOCKS request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D

AWS request (if you need it): https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D

**Comment by oseasmoran73** [comment]
Closing ticket as URLs to create SOCKS/AWS has been provided
