### ISSUE TITLE
Staging:  Direct Scheduling Choose Date Time:  Select Previous Or Next Month Displays Error to User

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#39675]
**Steps to Reproduce:** ![ChooseDateTimeSelectPreviousNextOrMonthError.png]
1.  Configure VATS to allow direct scheduling for a type of care Yes Any.  Select a patient that has had a past appt in that type of care in the last 24 mos.  I used judy morrison.  Amputation and Fort Collins.  
2.  Log into VAOS. Start scheduling. Amputation. Fort Collins. Enter a date at least one calendar month ahead for the desired date of appointment.
3.  System displays clinic availability on the Choose a date and time page.  Select to move forward a month or two and then move back using the <previous and next > buttons.  
4. Results Expected: Clinic availability displays on the on the Choose a date and time page.
4. Results Seen:  System displays an error.  We’ve run into a problem trying to find an appointment time.  To schedule this appointment, you can submit a request for a VA appointment or call your local VA medical center. Dev tools does NOT display any errors.   Console shows errors.  
instrument.js:109 TypeError: e.start.localeCompare is not a function
    at actions.js:628:35
    at Array.sort (<anonymous>)
    at actions.js:628:12
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at se (index.js:346:8)
    at a (index.js:346:8)
(anonymous)	@	instrument.js:109
a	@	error.js:67
(anonymous)	@	actions.js:635
l	@	runtime.js:63
(anonymous)	@	runtime.js:294
(anonymous)	@	runtime.js:119
se	@	index.js:346
a	@	index.js:346
Promise.then (async)		
se	@	index.js:346
a	@	index.js:346
(anonymous)	@	index.js:346
(anonymous)	@	index.js:346
(anonymous)	@	actions.js:537
(anonymous)	@	index.js:8
onPreviousMonth	@	index.jsx:185
(anonymous)	@	CalendarWidget.jsx:181
prevOnClick	@	CalendarWidget.jsx:319
Ye	@	react-dom.production.min.js:52
Ke	@	react-dom.production.min.js:52
(anonymous)	@	react-dom.production.min.js:53
xr	@	react-dom.production.min.js:100
Pr	@	react-dom.production.min.js:101
(anonymous)	@	react-dom.production.min.js:113
Re	@	react-dom.production.min.js:292
(anonymous)	@	react-dom.production.min.js:50
jr	@	react-dom.production.min.js:105
Jt	@	react-dom.production.min.js:75
Qt	@	react-dom.production.min.js:74
t.unstable_runWithPriority	@	scheduler.production.min.js:18
Zo	@	react-dom.production.min.js:122
De	@	react-dom.production.min.js:292
$t	@	react-dom.production.min.js:73
r	@	helpers.js:73

**End User Impact:** 
Veterans  will not be able to direct schedule if they need to select an alternate date than the desired date entered.  

**Environments, users, and patients tested in:**
Staging (CHYSHR)
Judy Morrison

![ChooseDateTimeSelectPreviousNextOrMonthError.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/3e3d7a5c-39a7-445d-9b8c-9b8103622137)

**Comment by ldelacosta** [comment]
@marcynadeau - Please validate the ticket and let us know if it is still an issue. Thanks.

**Comment by ajmagdub** [comment]
@marcynadeau @ldelacosta, please hold off on verifying. VFS Platform support is experiencing some issues and hasn't been able to deploy anything since last Friday. They'll let us know when they'll be able to deploy.

**Comment by ajmagdub** [comment]
@marcynadeau @ldelacosta, VFS Platform has resolved the deployment issues. This can now be validated.

**Comment by ldelacosta** [comment]
@marcynadeau - This can be re-tested. Let us know if you are experiencing any issues. Thanks!

**Comment by beth-wodzinski** [comment]
Previous and Next buttons work as expected on Direct Scheduling. Verified! 
@ldelacosta

**Comment by ldelacosta** [comment]
This ticket has been re-tested and no issues reported. Closing the ticket.
