### ISSUE TITLE
[Vets-API/EKS] Kubernetes Security Benchmark

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39688]
## Description
Run a security benchmark on our cluster and evaluate -- not resolve -- the results. Share your findings with the team.

## Background/context 
- We need to know how well our cluster is configured and areas of improvement

## Technical notes
- https://github.com/aquasecurity/kube-bench is one such tool that would fulfill this request

---
## Tasks
- [x] Run `kube-bench` on the Kubernetes cluster

## Acceptance Criteria 
- [x] `kube-bench` results and evals are documented and shared with the team

**Comment by oseasmoran73** [comment]
@ph-One It looks like if we want to do local testing it needs to be ran under [linux](https://github.com/aquasecurity/kube-bench/discussions/766) :( 

I will look for other alternatives, but if we want to move forward, I think John is the only one (aside from you) that has Linux distro installed

**Comment by oseasmoran73** [comment]
I was researching more into it and I think I misunderstood the statement above. I think we can still using [running in an EKS cluster](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools). Still doing some investigation

**Comment by oseasmoran73** [comment]
Rolled out `kube-bench` on dev & staging. All successful with exception of warning, will update in our internal Confluence prior to closing this ticket out.

Huge thanks to Kyle for helping me out on this!!

**Comment by oseasmoran73** [comment]
Created confluence of discovery. Closing ticket
