### ISSUE TITLE
Update General Orientation slide deck to include Sitewide Content & IA intake request

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39694]
## User Story
As a new VFS team member, I want to know about the Sitewide Content & IA intake request while going through VA.gov Platform General Orientation so that I know what to expect when I engage in the Collaboration Cycle.

- Intended Audience: VFS teams
- Desired Outcome: General Orientation slide deck is updated to include a new slide for the Sitewide Content & IA intake request
- Due Date:  End of April. Next general orientation is scheduled for May 3

## Description
In March 2022, we added the Sitewide Content and IA Intake request to the Collaboration Cycle as an official touchpoint. However, we did not create a slide for this touchpoint in the General Orientation session for the VA.gov Platform. The purpose of this ticket is to add a new slide to the slide deck.

Please refer to the [Sitewide Content & IA Intake Request page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html) on Platform Website for information to populate the slide.

## Artifacts Needing Updates
[VA.gov Platform General Orientation slide deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit)

## Acceptance Criteria
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled
- [x] Sitewide Content and IA team has reviewed the slide and given their approval (Beth, Danielle and/or Mikki)

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@mnorthuis @bethpottsVADEPO @DanielleThierryUSDSVA this has been on our backlog for too long now and I think it might be best to ask for help. Please review the ticket and let me know if you have any questions. 

FYSA - I added a placeholder slide in the [deck that was shared](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html#CalendlyOrientationSessions-GeneralOrientation) at the May 3 General Orientation Session.

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA @bethpottsVADEPO I took a stab at a slide based on the other content we have created. 

[General Orientation - SC&IA slide.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8894778/General.Orientation.-.SC.IA.slide.pptx)

**Comment by shiragoodman** [comment]
@mnorthuis thank you! Since the orientation is today, I'm going to add to the deck and present. If you (or @DanielleThierryUSDSVA or @bethpottsVADEPO ) would like to make changes, please let me know. I'll keep the ticket open.

Please keep in mind that this is a live deck that is always changing, so even when this ticket is closed, if you'd like to make changes, please just create a ticket and tag `governance-team` - thanks!
