### ISSUE TITLE
[Documentation] Data Contacts/Collaboration Record

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#397]
## User Story
As an Insights team member, I need a shared document that shows our analytics contacts so I can decrease analytics contact duplication.

## Goal
Create and share document of contacted va.gov POCs.

## Acceptance Criteria
- [ ] Contact Record Created
- [ ] Contact Record Shared

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@JoyOfTech Please add the Google Doc link here.

**Comment by JoyOfTech** [comment]
Google Doc link: https://docs.google.com/spreadsheets/d/1oc2NT2s7sW0haqA7usR9Pvc9xnvxZDnKISe2FGjd7vI/edit?usp=sharing

**Comment by joanneesteban** [comment]
Google Doc linked to [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/Undiscovered%20Metrics%20Research/readme.md)
