### ISSUE TITLE
[Story] High School filters to leverage weams csv file instead of facility code

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#39715]
## Issue Description
Update filters to key off of weams data column specifically delineating an Institution to be a High School, vs via inference through facility code digit.

---
## Tasks
Update vets-website api calls and front-end code.
Update GIDS to ingest new "high_school" column in spreadsheet.
Update GIDS to serve filtered data results off newly added column vs. facility code digit.

## EDU deliverables
EDU needs to provide temporary or permanantly updated weams file for testing and actual release.

## Acceptance criteria
Front-end filtered results adhering to weams data file tested by EDU.

**Comment by AdamFreemer** [comment]
Code has been updated, awaiting new weams file from edu to then integrate in sample data and use for updated code testing suite.

**Comment by mrblanco1** [comment]
File was provided to Dev on 5/20/2022. Dev making progress.

**Comment by AdamFreemer** [comment]
Updated code pushed. Awaiting for what looks like updated weam file from Brian that has high school column data populated to test. @MitchLivingstone  @mrblanco1

**Comment by AdamFreemer** [comment]
After publishing of current data by @PJart - functionality is now available on staging.

**Comment by hallihocine** [comment]
Ticket has been validated in staging: By checking/unchecking the high school checkbox, you can include/exclude the High School cards in/from the search results.

**Comment by hallihocine** [comment]
- Test Run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3262&group_by=cases:section_id&group_order=asc&group_id=4656
- Test Steps: 
[High School filters to leverage weams csv file instead of facility code.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8808431/High.School.filters.to.leverage.weams.csv.file.instead.of.facility.code.xlsx)

**Comment by MitchLivingstone** [comment]
Completed and in production. Closed on 06/01/2022
