### ISSUE TITLE
[Spike] - High Schools not coming up at all when only the High School filter is enabled

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#39716]
## Background/Request
This Spike is for after EDU fix the GIDS data. Dev then can begin their analysis and come up with a strategy and plan to get this resolved.

### Requirements to Consider
EDU must fix the data in GIDS before Dev can begin this spike.
---

## Tasks
Joe Preisser and Brian Grubb are currerntly working on fixing the GIDS data. They will let Dev know once their task in completed. Dev can begin analysis at that point.

**Comment by MitchLivingstone** [comment]
This Spike was completed by Adam,
