### ISSUE TITLE
Evaluate quick and longer-term paths to usability-test new home page components with Vets

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#39719]
Dave Conlon asked my team to explore ways to deploy new homepage components in a publicly accessible environment. (Slack thread in the #vfs-platform-support slack channel on 3/21.) That pursuit has forked into two separate paths, for each of which we need support from y'all. I'm reaching out now to ask how to engage you on each. How should we engage you?
The 2 paths:
1) Activating a new subdomain of VA.gov is seen as having significant value, and Dave asked me to engage the Platform team to design a path forward based on needs that Dave is most familiar with.
2) In the near term, Tim W suggested in the earlier thread that we could probably deploy alternative homepage components on dev.va.gov conditional on the environment. This is the quicker path to getting a component live for usability testing. We would like to talk through methods we've come up with and get guidance on which is best for the ecosystem.
(FYI, the issue tracking our exploration is here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8478#issuecomment-1089062911. )

@ryguyk is the engineer on CMS-Offices who did the exploration thus far and will be involved in implementing Path 2 above.

**Comment by zachclarity** [comment]
The backend vets-api team is aware and will respond soon.

**Comment by npeterson54** [comment]
For #2, this may be what is needed: https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Using+feature+toggles+to+progressively+release+changes
