### ISSUE TITLE
[User Testing] HLR: Conduct user testing sessions

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3971]
## User Story or Problem Statement
As a UX designer, I need to test the Higher Level Review digital form (in password protected production) with real users so I can receive feedback on the design and improve it.

## Goal
Collect feedback on the Higher Level Review digital form via usability testing

## Objectives or Key Results this is meant to further
- Refinement of design based on human centered design principles.

## Acceptance Criteria
- [x] Test the prototype with # users 
- [x] Create notes and drop scrubbed data into GH
- [x] Share notes with team

**Comment by chrvalla** [comment]
All usability sessions have been completed. The notes from sessions are located here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review/research/notes
