### ISSUE TITLE
MonthYear web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39725]
## Description
Instead of making a separate web component for the [MonthYear React component](https://design.va.gov/storybook/?path=/docs/components-monthyear--default), we have decided to develop this as a variant of the [va-date](https://design.va.gov/storybook/?path=/docs/components-va-date--default) web component.

## Details
Styles are in this file: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-form-elements.scss

Where possible, use native HTML events.

## Acceptance Criteria
- [x] month-year is a variant of the va-date web component and is shown on Storybook
- [x] E2E tests are written
- [ ] Add Chromatic link to #39727, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by pdavies88** [comment]
MonthYear is used in 1 location: https://github.com/department-of-veterans-affairs/vets-website/blob/d0e8ab17792f3e69a91a1858a6c65ceb50c4c3f5/src/applications/financial-status-report/components/EmploymentRecord.jsx#L128 and could become a prop within the `va-date` component as it just removes a single `va-select` component from the `va-date` component

**Comment by bkjohnson** [comment]
I'm pausing work on this since there will be [changes to the fieldset `aria-label`s](https://github.com/department-of-veterans-affairs/component-library/pull/438#issuecomment-1145050900), so I want to wait until that's finished instead of having to throw away the work I have that's in progress.
