### ISSUE TITLE
NumberInput web component: Documentation and Sketch update

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39738]
## Description
Two things need to happen as part of this ticket:
1. We need to update design.va.gov to point to the new web component version of the NumberInput component and update the documentation there if anything was changed in the conversion to a web component that needs to be noted.
2. We need to move the documentation about this component on design.va.gov from the Forms page to its own page, which then becomes a sub-section of the Forms category page.
2. We need to check in with @GnatalieH to make sure that any changes that were made are added to Sketch if necessary.

## Acceptance Criteria
- [X] Update design.va.gov
- [x] Check with Natalie on Sketch updates
- [ ] Move NumberInput documentation to it's own sub-page under the Forms category on design.va.gov

**Comment by pdavies88** [comment]
There is no current documentation on the `NumberInput` React Component however it should be added here: https://design.va.gov/components/form-controls#text-inputs with text prior to the example explaining that has the type of number hardcoded.

**Comment by GnatalieH** [comment]
I checked Sketch, and this component doesn't need a design update. It's just an input field as far as the design asset goes. We will need to update all of our form element symbols with the new naming hierarchy, however.

**Comment by k80bowman** [comment]
@GnatalieH is there a plan for completing those updates already?

**Comment by k80bowman** [comment]
@pdavies88 and @GnatalieH can we please add documentation on this component to design.va.gov as part of this ticket?

**Comment by pdavies88** [comment]
@k80bowman pr is linked for review

**Comment by GnatalieH** [comment]
@k80bowman I'm not sure if @humancompanion-usds is working on the Form controls renaming in Sketch, yet. But we should do all of them at once, IMO.

What should be documented on design.va.gov for this component, @pdavies88? I am not sure what this means: "text prior to the example explaining that has the type of number hardcoded."

**Comment by pdavies88** [comment]
@GnatalieH sorry that comment was old and we reworked it to be its own page not a sub portion of the form controls
