### ISSUE TITLE
[FE] Onboarding: Mark Dewey

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#39749]
## Background

Welcome, Mark! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Samara Strauss [PO]
- [x] Sharon Kasimow (PM)
- [x] Christina Gednalske (Designer)
- [x] Adam Whitlock (Frontend)
- [x] Tom Harrison (Backend)

### Team docs

- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md)

### Profile overview

Here are some helpful documents to review on the profile. It would also help if you log into staging and check it out for yourself to get a sense of the full section.

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [Profile folder and list of products](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)
- [x] [Profile roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/profile-roadmap.md)

**Staging info**

- [x] Log into staging and check out the profile 

You can use the following info to get into staging:

- Go to VA.gov.
- Sign in to staging with user 36 ([staging user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)).
- Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.

### Existing profile products

Here are some of the products that currently live within the profile.

- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/README.md)
- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [x] [Communications preferences project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)

### Current projects

Here are the projects we currently have going on the profile team.

- [x] [Personal information revisions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md)
- [x] [Bad address indicator](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/README.md)

**Comment by mdewey** [comment]
Chatted with Adam on Thursday 4/7

**Comment by mdewey** [comment]
Met with the rest of the team and just completed looking through the documents

**Comment by mdewey** [comment]
I am cool with closing this ticket @Samara-Strauss and @SKasimow

**Comment by Samara-Strauss** [comment]
Great!! Thank you!
