### ISSUE TITLE
[BE] Write Timestamp to User's VA.gov Profile when Demographics Confirmed

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39740]
## Questions
- Is this work we need to do or CHIP?
- What about timestamps for EC and NOK?
- Do we need to send all of the data back to them along with the timestamp?

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/c7426bfa-209e-4b0e-bb1d-51a7fabc1480)

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/ee3ca555-6070-499e-99e0-2722299ffd26)

**Comment by loripusey** [comment]
@acrollet is this something that we need to do or CHIP?

**Comment by acrollet** [comment]
I think it's most likely that CHIP will do this since the data needs to go there anyway to be sent to the staff app. TBD though.
