### ISSUE TITLE
Demoable IaC Prototype

### ISSUE THREAD

**Issue by mb365247** [department-of-veterans-affairs/va.gov-team#39741]
We should prepare a demo of Keycloak management via Terraform. The demo should

- [x] Run locally
- [x] Show a plan and an apply
- [x] Add at least a client
- [x] (nice to have) show what happens on failure

## Done when
Demoed

### Benefit
- IaC paves the way for our Q2 automation objective
- An IaC framework Keycloak even more robust

### Current State
- Locally running Terraform & locally running Keycloak

### Next Steps
- Integrate Terraform to Dev Keycloak
- Set up webhooks for automated configuration

**Comment by calquisola** [comment]
I created a PR for this one. 
https://github.com/department-of-veterans-affairs/pst-amt-keycloak-local/pull/2

Had Kevin run locally and looks good.
