### ISSUE TITLE
Bug Fix: Web Components Error Message Prop Empty String Enables Red Border

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#39748]
## Description
To mirror the behavior of React Components which we are deprecating the following Web Components error prop CSS needs to be updated: `va-radio`, `va-checkbox`, `va-checkbox-group`, `va-text-input`, and `va-select`

Currently the React Components have it where the prop of `errorMessage=""` allows the CSS that adds in the Red Border to be disabled. However the Web Components listed above have it where `error=""` causes the CSS that adds in the Red Border to be enabled.

Goal of this ticket is to have the CSS be updated for the components listed above to have it where `error=""` does not enable the Red Border.

![Screen Shot 2022-04-07 at 11.38.23 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/f008cd39-8fde-4887-a5f6-9fbedfe1295d)
![Screen Shot 2022-04-07 at 11.40.24 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/f54e69c1-9cd1-4444-bbb4-4485f9e0867a)
![Screen Shot 2022-04-07 at 11.42.46 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/d06d8e81-409f-4f64-8223-e4cda8b9e990)
![Screen Shot 2022-04-07 at 11.42.56 AM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/da578b16-0b9d-46ec-ac26-37185d69a65d)

## Acceptance Criteria
- [ ] For the components listed above if the error prop equals an empty string the CSS that shows the error Red Border does not appear

**Comment by andresriveratoro** [comment]
This was fixed as part of this [PR](https://github.com/department-of-veterans-affairs/component-library/pull/466).

**Comment by caw310** [comment]
Works been done so closing.
