### ISSUE TITLE
Use calc() for calculations in formation/sass/base/_b-variables.scss 

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#39750]
## Issue Description
In vets-design-system-documentation we've upgraded to using Dart Sass thru Jekyll. That's now throwing some warnings about sass that has been deprecated:

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($multiple, 4) or calc($multiple / 4)
More info and automated migrator: https://sass-lang.com/d/slash-div
    ╷
191 │   0p25: $multiple / 4,
    │         ^^^^^^^^^^^^^
    ╵
    node_modules/@department-of-veterans-affairs/formation/sass/base/_b-variables.scss 191:9  @import
    src/assets/stylesheets/application.scss 2:9                                               root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($multiple, 2) or calc($multiple / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
    ╷
192 │   0p5:  $multiple / 2,
    │         ^^^^^^^^^^^^^
    ╵
    node_modules/@department-of-veterans-affairs/formation/sass/base/_b-variables.scss 192:9  @import
    src/assets/stylesheets/application.scss 2:9                                               root stylesheet
```

Given that this is only currently impacting our vets-design-system-documentation repo we will take care of fixing this.

**Comment by k80bowman** [comment]
Thank you for checking on this, @pdavies88. Would interpolating the `$multiple` variable (as suggested [here](https://stackoverflow.com/questions/17982111/sass-variable-in-css-calc-function)) fix the issue?

**Comment by pdavies88** [comment]
@k80bowman yes that fixed it screenshot here:
<img width="1393" alt="Screen Shot 2022-04-14 at 9 42 34 AM" src="https://user-images.githubusercontent.com/11822533/163403394-ab44b374-8590-436f-97e9-ed3c8db02008.png">

Updating my PR now
