### ISSUE TITLE
Access for Liani Lye

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#39754]
I'm the PM for the Platform Content team.  Need SOCKS access for Console UI work.

**Comment by rmtolmach** [comment]
@lianilychee Hello! Have you gone through these steps? https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

The video in those docs and the `vtk` command line tool will walk you through generating an ssh key that will pop up the SOCKS request form
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D

**Comment by lianilychee** [comment]
@rmtolmach another access ticket should be coming in soon then.  JFYI, I _did_ follow the instructions, but there is a mismatch between the VTK terminal prompts and the video.  The VTK terminal guides me to submit this (pretty useless) empty access ticket

**Comment by rmtolmach** [comment]
@lianilychee Thank you for letting me know that! 🙏  I'll try to reconcile the video with the documentation.

**Comment by rmtolmach** [comment]
This should be all fixed now. Sorry for the extra steps you had to go through!
