### ISSUE TITLE
Staging:  Direct Scheduling Error 400 Error Says Clinical Service is Null

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#39762]
Talked to Brad C on backend, he says this is front end issue. Brad C has logged a JIRA story related to this https://issues.mobilehealth.va.gov/browse/VAOSR-3230.  VAOS: Validate query parameters for eligibility decision requests

**Steps to Recreate:**

1. Configure VATS for Cheyenne Optometry Yes any Veteran
2. Login as Cecil Morgan. Select start scheduling, eye care, Optometry and Cheyenne.  Select Friendly Name Optometry as clinic.  
3. Select confirm appointment
4. Response Expected:  Confirmed appointment details display. No errors in dev tools
5. Response Seen:  Error message displays to veteran.  We couldn’t schedule this appointment.  We’re sorry. Something went wrong when we tried to submit your appointment. Call your VA medical center to schedule this appointment.  Dev tools shows a 400 post error for this endpoint:
6. Note....repeated same steps with Judy Morrison and same clinic and got same results.  
7. Note.....repeated again with Cecil Morgan and this time I chose a different Optometry clinic, CHY Visual Field. No errors and appointment was booked.  

https://staging-api.va.gov/vaos/v2/appointments
400 POST
{errors: [,…]}
errors: [,…]
0: {title: "Bad Request", detail: "the clinical service is not enabled at the facility", code: "VAOS_400",…}
code: "VAOS_400"
detail: "the clinical service is not enabled at the facility"
source: {,…}
vamfBody: "{\"message\":\"the clinical service is not enabled at the facility\",\"detail\":\"facility=983, clinical service=null\"}"
vamfStatus: 400
vamfUrl: "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012845943V900681/appointments"
status: "400"
title: "Bad Request"

**End User Impact:** 
Vets will not be able to direct schedule appointments

**Environments, users, and patients tested in:**
Staging:  CHYSHR, Cheyenne
cecil.morgan@id.me.  Password1234!

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/669975d7-c106-4d0c-916f-d921f1d228e9)

**Comment by ajmagdub** [comment]
blocked by: https://issues.mobilehealth.va.gov/browse/VAOSR-3546

**Comment by ajmagdub** [comment]
Should not be getting 400, the clinical service is not enabled at this facility. Submitted [VAOSR-3230](https://issues.mobilehealth.va.gov/browse/VAOSR-3230)

**Comment by ldelacosta** [comment]
Moving the ticket to the Blocked queue. Once VAOSR-3603 is resolved, will move it back to In Progress.

**Comment by ajmagdub** [comment]
https://issues.mobilehealth.va.gov/browse/VAOSR-3603 is ready for retesting.

**Comment by marcynadeau** [comment]
@ldelacosta @ajmagdub Is this ready for testing?

**Comment by ajmagdub** [comment]
@marcynadeau, yes, this is ready for testing.

**Comment by ldelacosta** [comment]
Assigned to @marcynadeau

**Comment by beth-wodzinski** [comment]
Tested and passed these scenarios:

Cecil Morgan, Chy Opt Var 1
Cecil Morgan, Friendly Name Optometry
Judy Morrison, Chy Opt Var 1
Judy Morrison, Friendly Name Optometry

@ldelacosta this passes verification.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
