### ISSUE TITLE
SOCKS access for Liani Lye

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#39768]
### Your Name

Liani Lye

### Your Email

liani@adhocteam.us

### Your Role

Product manager

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrLyoBatLSQEY/2IDeMxNIbygmUyo5pIcqb28pCTe5Pep6RCUsij6YDjBoAFWwPirYdlLTGzNSeBu/K3NOlMcSvz1p7gLsgGSWHc6/K04Em/B58n1qLLBaTjoEkuI+pzH9eQOJU229ZKrn6OagyLdlr9Ud2BALkd1uodvHtgMLBcpVffnqC1CwWf+2u49fpO90852dygrOP7k7bmOFNV53xmnfjdqoQwHG8hrqysKHMSneKtQC5Wc/vaT1fRI5ml4wJrTrD4EgLc5dk/BHhkMZ9jd4wqxwWIrdIcRgvgm45YKMykmPJ0GncWj1DJ9pvsQSUgimI3QEvxfYJ84rEx9UAqpQFAbw8tD+4xVUHvuNwoPqwnaF4MfEs0z1ej8YwdstM9Pq40n/EO0K1g+Fe98Y6EyA+qqpgXIAum5BAF+PFTfqr/RZlp0cRqx107TD/goh0XY9h+iQ1Jfms5na4i1S+COx83/wePgt5DgYN07LZTbCjtCXpEPVGT8dHMW1j9U= lianilye@Liani-Lye-MBP

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
