### ISSUE TITLE
SOCKS access for Gretchen Maciolek

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#39777]
### Your Name

Gretchen Maciolek

### Your Email

gretchen.maciolek@adhocteam.us

### Your Role

UX Writer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbe+oAml+0wYqTTgSkd/xvJGCluyyalQLYCTiGG5p0YjLio87Uo61eQQhslkuITDLIrhNzko3aMPxWZoY76TNTKwNJZFJNQFsUD4ECfcnrDGgRMIkyLPyVQ/YKFhqlNNzAFbMBTdmiPWtW4uKSKaa9om4oQdDVg3iV68gaf4qMFmy3Ha/ndy7AfSMdpAQd6pMtBgz8ckXbJwnl8UBSekEskC51gpig/zMQYwbKVt9q9JJHnjnvFGypwPrGS/ZFz3dIHXxl0XYVptRr3xqOtvatBaXR7js2wKtH9Ro+THyKLxwd6+VpLm6y0oCq66MLy2At3qqH/2UYjGj9KuAnzPG8H3o4GqQA14K0LIUdipLXciv41uErIzFd8V4WrjhGH4gjQ2qHBP69AMx6NIa5p8Ciqjx8Nij0Le/P5DYQsGAIrPkNDuiLEAz29Ij+ymH8wzt3ucXV2h1BtEUJT3ggC+/jEeLRANuOzIvgFttFS7A49atvB6s8dw3EoTS2FvSAk1k= gretchenmaciolek@GretcheoleksMBP.attlocal.net

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
