### ISSUE TITLE
QA Test Plan for Manual UI  testing of Facility Locator url VAMC redirect 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3977]
## Product/Feature Summary

- The link from facility locator search results should be redirected to the new facility detail page as new VAMC detail pages are rolled out live. Existing interstitial pages for each facility will no longer be part of the workflow from the search results page.
- Facility Locator receives the new link from the Facilities API. 
- Facility Locator is an unauthenticated experience. 
- Anticipated timing for cutover: **January**
- [#3385]

## Proposed Scenarios
 
**Veteran enters Pittsburgh and VA Health as search parameters on [Facility Locator](https://www.va.gov/find-locations/?zoomLevel=9&page=1&address=pittsburgh&facilityType=health&serviceType)**: 

When University Drive (vha_646) is selected from the search results, the user should be directed to https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
- Interstitial page (i.e: https://www.va.gov/find-locations/facility/vha_646) should not be visible to the user _in this or following scenarios._

When H. John Heinz III (vha_646A4) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

When Beaver County Clinic (vha_646GC)is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

When Belmont County Clinic (vha_646GA) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

When Fayette County Clinic (vha_646GE) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic

When Washington County Clinic (vha_646GD) is selected from the search results, the user should be directed to:-> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic

When Westmoreland County Clinic (vha_646GB) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic

**Existing functionality for all other facilities should be maintained.**

Unit testing for subdomain logic has been implemented for regression purposes. 

## SMEs

- Facility Locator FE: Gibran Rodriguez
- Facility Locator BE: Lance Sanchez
- Facility Locator PM: Michelle Middaugh

## Review

Reviewed & approved by PM.

## Staging Test-Readiness

- No staging test accounts will be needed as Facility Locator is within unauthenticated domain. 

## Definition of Done

- [x] - Engineering-team review completed.
- [x] - Test Plan finalized.

**Comment by tlei123** [comment]
Awaiting notification of PR - will move this to In Progress then.

**Comment by tlei123** [comment]
@mmiddaugh , please review* the [Test Plan](https://dsvavsp.testrail.io/index.php?/runs/view/12&group_by=cases:section_id&group_order=asc) I've put together on TestRail.

You should already have login creds, but ping me if you need them again.

Thx much!  :)

* Let me know who else should be regularly included in our Test-Plan reviews, and feel free to send me a mtg. invite if you'd like everyone to review & discuss at the same time.

**Comment by mmiddaugh** [comment]
@tlei123 please send creds! I am unable to access these tests

**Comment by mmiddaugh** [comment]
They look good to me! Thanks!

**Comment by tlei123** [comment]
@mmiddaugh @brangi , here's my Test Plan Summary Report with for your review...

All left-panel text-result title-links are successfully navigating to the new facility pages, but not the corresponding map-icon location-popups' title-links -- logged defect #5272.

Feel free to ping me for any further discussion.

Thanks much!

**Comment by mmiddaugh** [comment]
@tlei123 can this be closed?

**Comment by tlei123** [comment]
@mmiddaugh , I added my Test Plan Summary Report link above (in my previous Comment) -- sorry I forgot!  Closing this now.
