### ISSUE TITLE
Remove any best bets that point to the chatbot

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#39788]

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA  There are no best bets directed at the chatbot.

Based on the last 3 months of GA data
- there were 3,295 page views
- 30% of the traffic to the chatbot is entering va.gov on that page
- Of the rest of the traffic 98.92% is coming from the coronavirus faq page

**Comment by DanielleThierryUSDSVA** [comment]
Awesome. Thank you, @mnorthuis!
