### ISSUE TITLE
Sunset the coronavirus chatbot

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#39785]
# Story

The coronavirus chatbot has served Veterans and VA well during the height of the pandemic. At this time, both chatbot use and contact center volume around COVID-19 has lessened significantly. In addition, VA is creating a new virtual agent that can serve Veterans’ customer service needs, including responding to COVID-19 inquiries. OCTO colleagues and contractors who are maintaining the COVID-19 chatbot’s content and development are preparing to move to other initiatives.

Our goal is to responsibly retire the COVID-19 chatbot while still providing excellent customer service.

### April 15, 2022 - April 30,2022

- Add notices that the chatbot will retire on May 15 on the chatbot page and other locations or scripts where we currently link to the chatbot. Include a note on where people can find information that’s in the chatbot (OCTO - Sitewide content and IA/Virtual agent team)
- Add a direct link to the CDC’s COVID-19 symptom checker page on the coronavirus FAQs and COVID-19 vaccine pages (OCTO - Sitewide content and IA)
- Ensure that the virtual agent is successfully surfacing COVID-19 links for relevant queries (OCTO - Virtual agent team)
- Ensure that no best bets are in place that drive site visitors to the COVID-19 chatbot (OCTO - Sitewide content and IA)
- Communicate the chatbot’s upcoming retirement to all COVID-19 communications partners throughout VA as well as our VSOs (ITSC comms).

### May 1, 2022

Remove all links to the chatbot from VA.gov pages and other communications. (OCTO sitewide content and IA + our VA partners)

### May 15, 2022

Retire chatbot. Redirect link to the main coronavirus FAQs page. (Virtual agent and sitewide teams)

**Comment by ianpsant** [comment]
Hi @DanielleThierryUSDSVA. We spoke about some of the tasks assigned to us yesterday and had a few questions.

- Add notices that the chatbot will retire on May 15 on the chatbot page and other locations or scripts where we currently link to the chatbot. Include a note on where people can find information that’s in the chatbot (OCTO - Sitewide content and IA/Virtual agent team)

Do we have an action here? Are you able to edit the chatbot page? We'll need to check if we're able to, and if so when might we expect the content and desired styling to be available?

- Ensure that the virtual agent is successfully surfacing COVID-19 links for relevant queries (OCTO - Virtual agent team)

Currently for covid queries in our chatbot we are surfacing the coronavirus FAQ, this link: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/. Is this enough? Or were there other specific queries that you had in mind?

Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ianpsant. Both great questions - thanks!

> Add notices that the chatbot will retire on May 15 on the chatbot page and other locations or scripts where we currently link to the chatbot. Include a note on where people can find information that’s in the chatbot (OCTO - Sitewide content and IA/Virtual agent team)

I know I can edit the chatbot, but it's been a long while since I've gotten in there myself rather than the content team folks so let me double check and I'll get back to you. And then I'll need help pushing the edits to production.

For timing: I'm coordinating comms with the IT Strategic Communications group. I'll check with them on timing thoughts, but I'm thinking within the next 2 weeks. I'll post an update as soon as I know for sure.

> Ensure that the virtual agent is successfully surfacing COVID-19 links for relevant queries (OCTO - Virtual agent team)

I think that's good to point all covid queries to that main faqs page, yes. That page then links folks off to the vaccine info, testing info, etc. so it's a good catch-all destination. Thank you for confirming!

**Comment by ianpsant** [comment]
@DanielleThierryUSDSVA Hi Danielle, per the timeline above, we wanted to add the "leaving soon" language to the Covid Bot web page by the end of the week. Our team has capacity this week to work on it, so wanted to see if there was an update to the last comment 1. Can you edit the page yourself? 2. If not, Is the copy ready for us to make the edit? 

Whichever way this goes, our team is happy to assist in any way!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ianpsant! Thanks so much for checking in. Adding @RLHecht here who will be working on this with us. Thanks!

**Comment by RLHecht** [comment]
Approved text to add as an alert to the top of the chatbot:

Header: This chatbot won't be available after May 15, 2022
To get answers to your questions about COVID-19 and your VA benefits and services, go to our coronavirus FAQs page.
[Go to our coronavirus FAQs page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)

@ianpsant I will reach out to the chatbot team to ask about the code for adding an alert and can update the chatbot.

**Comment by RLHecht** [comment]
@ianpsant The alert is ready on the chatbot. Should this go live tomorrow?

**Comment by RLHecht** [comment]
The chatbot alert is live on prod: https://www.va.gov/coronavirus-chatbot/

**Comment by DanielleThierryUSDSVA** [comment]
This work is complete! Closing epic. @leahbannon2 labeled this as octo-health for your tracking purposes too. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
This work is complete! Closing epic. @leahbannon2 labeled this as octo-health for your tracking purposes too. Thanks!

**Comment by RLHecht** [comment]
Looks like this one never got closed.
