### ISSUE TITLE
Add notices that the chatbot will retire on May 15 to all relevant locations

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#39789]

**Comment by DanielleThierryUSDSVA** [comment]
@agmurphy I'll provide content and work with your team to add to chatbot page. Aiming for 4/15 for this, but no big deal if it pushes into the following week. Thanks!

**Comment by RLHecht** [comment]
This work is complete and noted in the comments in the epic. Closing this ticket.
