### ISSUE TITLE
Verify that LoA1/IAL1 users are not able to authenticate successfully via mobile

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#39797]
# Description
In the event of a non-verified login to the VA.gov mobile app, the app is supposed to prompt the user to verify their account to IAL2/LoA3 and prevent them from authenticating if they do not verify. The vets-api backend does not play a role in any of these validations and will create a session & tokens for mobile IAL1/LoA1 authentication requests. In order to prevent unwanted behavior upon the public rollout of SiS for mobile, the following scenarios should be tested to ensure that the user in each is unable to authenticate:

* [x] SiS - Login.gov `IAL1` acr authentication
* [x] SiS - ID.me `LoA1` acr authentication
* [x] iam_ssoe_oauth - Login.gov `IAL1` acr authentication
* [x] iam_ssoe_oauth - ID.me `LoA1` acr authentication

Further information is in this [Slack thread](https://dsva.slack.com/archives/C019S3NSSAD/p1666036052049469)

**Comment by joeniquette** [comment]
pivot: verify this is already done

**Comment by bramleyjl** [comment]
Using the VA.gov development Android app I was unable to alter any of `sessions/new` SSOe & `sign_in/authorize` SiS calls to vets-api
