### ISSUE TITLE
Design Discovery for APO/FPO/DPO

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3979]
## User Story: 

As a Designer/Researcher I need to explore and document how the proposed APO/FPO/DPO design solutions impact other forms with address components on VA.gov so that I can convey scope, impact and potential dependencies. 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Identify forms on VA.gov that have an address component - 4 hour(s) - @artistgreen 

- [x] Understand which forms get pre filled information from VAProfile - 3 hours - @artistgreen 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] Testable Outcome Y 

- [ ] Testable Outcome Z

**Comment by artistgreen** [comment]
In an effort to understand the impact on other forms on VA.gov this list was compiled. These are the forms that have an address section which may be impacted by these changes.

https://staging.va.gov/records/download-va-letters/letters/confirm-address

https://staging.va.gov/health-care/apply/application/veteran-information/personal-information

https://staging.va.gov/pension/application/527EZ/applicant/information

https://staging.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information

https://staging.va.gov/profile/

**Comment by artistgreen** [comment]
For the Letters section, users are asked to make sure their address is current. This edit address uses the same components as the profile edit address component. When a user updates their address here, the changes take effect on their profile also.
![image](https://user-images.githubusercontent.com/53535009/70333713-06c0d480-1812-11ea-9fd1-337ef15eb43d.png)

![image](https://user-images.githubusercontent.com/53535009/70333732-0f190f80-1812-11ea-9d2a-4e151b492b19.png)

**Comment by artistgreen** [comment]
Technical discovery info from @lihanli :

https://staging.va.gov/records/download-va-letters/letters/confirm-address
This uses the same component as the /profile mailing address editor, changes to this address will update to /profile and changes from /profile will update here.

https://staging.va.gov/health-care/apply/application/veteran-information/personal-information
https://staging.va.gov/pension/application/527EZ/applicant/information
These use the profile address

https://staging.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information
This uses the profile address and EVSS PCIU address. Profile address has priority but if it's blank then PCIU address will be used. 

- For the forms that do get pre filled profile information, if the user changes their address in the form will that update in their profile?
No, except in the letters url above.
