### ISSUE TITLE
[Design] Update Poster for Low Vision

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39808]
## Background
https://dsva.slack.com/archives/C02GXKL8WM6/p1649253050815509
I think the test for “check in with your smartphone” could be lightened or just set in white.
And of course, all those light backgrounds simply won’t be seen at a distance.

## AC
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/7e0ed222-1c6e-4135-a54f-4fbd5243305a)
- [x] Make the above change
- [ ] Update the screen shot of the poster in the Product Guide
- [x] Update it in GitHub
- [x] Review with team
- [x] Send link to Martha Wilkes & Shawn Adams

## UX Deliverable
**Updated poster:**
[24x36](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/7yK5JgZ): https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/7yK5JgZ
[11x17](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/ZO9lwgG): https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/ZO9lwgG
[8.5x11](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/Jn5oGWe): https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/Jn5oGWe

**PDF posters on [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md)**:  
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md

**[Poster for Danielle (VA site)](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/52wJ4OE)**: 
https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/52wJ4OE

**PNG version for product guides and VA site** (@DanielleThierryUSDSVA)
**8.5x11:** 
![8.5x11-v1.1.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/97323217-df99-42bf-ae38-2b36c4e5dfdb)

**11x17:**
![11x17-v1.1.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/fc2fe6e2-fcb2-472d-af28-3828d197acc1)

**24x36:**
![24x36-lowvision-v1.5.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/ef97d784-9550-479d-83db-663bf4005c71)

**24x36-lowvision-v1.5 (for Danielle Thierry, VA site):**
![24x36-lowvision-v1.5 (for Danielle, VA site).png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/dc681125-d49b-4181-a71c-10b4e01a5238)

**Comment by niradatta1** [comment]
@zach-park once you're done with this, would you be able to provide the link to @DanielleThierryUSDSVA  as well? Her team will need the code replaced with ###. Here's a slack thread for more context: https://dsva.slack.com/archives/C02GXKL8WM6/p1649694200437539

**Comment by zach-park** [comment]
@niradatta1 @benbrasso-agile6 @kristenmcconnell @loripusey , I've attached the png posters in the ticket for the product guide use. So please let me know if they would work. Thank you!

**Comment by benbrasso-agile6** [comment]
Yeah, @zach-park I think this ticket is done. And the product guide ticket can be worked on separately. Curious, does @loripusey or @niradatta1 have thoughts on whether the product guides should have the actual phone number vs. the ### number? 

@zach-park did you Danielle the ### version already?

**Comment by loripusey** [comment]
I don't have an opinion either way

**Comment by zach-park** [comment]
@benbrasso-agile6 , yes the link for it is attached in the ticket above (https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/52wJ4OE). Thank you!

**Comment by niradatta1** [comment]
@benbrasso-agile6 @zach-park I'd recommend we use the actual phone number in the screen shot we'll place in the product guides. This is what the Veterans will see on-site, and will likely be referencing if / when they need to call the contact center. 'cc @loripusey

**Comment by sarahknoppA6** [comment]
Closing this ticket. I added putting the new version of the poster into the product guide update ticket.
