### ISSUE TITLE
[Support Slackbot] Update reports to pull data from new database

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#39815]
The current report uses google sheets as its data source. The data source will need to be updated to pull data from the new RDS database tables.

The support request report can be found here: https://datastudio.google.com/reporting/c4259d38-3515-486f-8fad-82ea06dadc4f/page/F3VEC

**Comment by little-oddball** [comment]
Determined DUP #41092
