### ISSUE TITLE
Access for Jill Adams

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#39824]
* COR = Courtney Bethea
* My name = Jill Adams
* My email = jill.adams@agile6.com
* Team = Sitewide CMS, CMS-offices (Public Websites moving forward)
* Role = Delivery Manager
* Company = Agile6
* Requesting SSH Access = Yes
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdw27WwY5zscyPCy6McH1bKLPZlamiZLnTSUt/k9WbBT3xTn45ZzNitfkJUfiht8gKKCjSO/Sw35XWqme4ckdZt+yPpQxKTv/UfM6eMenadCPQ1H6pUWJ99bl5s8HM1hKuYzU4A79iit8yxGJI3xwc4bk8UPNsEMOqt7mUrgHmPbAX2O/nb5+J1YQyPmVSPSls2Pvz7zbA7Xi0HnyorT7/Bghk16bs2AzVJChD3GVzcSo4RUIqk3NfmfX/mwccQs9XPFmEd9W0GSu1WnJvtI12Hpl7IznitvQ0CMar083m5MBfZq3x27kXkyKNAroVN3RwOvuWHA2IUmLJdkNI4VhYD5ZeVKGQKIJtmsdiyoPXu3uLo1+yKm6+XU8797KpnbGHkb1/IWgXvEQ3twjIXal3YxQDictwDP5XLXiDVSCIDn1wuX0oQTN8MgkmMBi+FVN07ejuJ5og7xltTWbyWTeLkMUtaRDLTeHpc3o3lqidVBOuzmKM/J1p/L0PJXEWJI8= jilladams@Agile6-A86.local
```

The prompt from `vtk socks setup` to open the request didn't populate the form with template info (it used [this URL](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2C+operations%2C+ops-access-request&template=Environment-Access-Request-Template.yml&title=Access+for+%5Bindividual%5D), maybe a missing template?), so have provided what was suggested in [the Youtube tutorial](https://www.youtube.com/watch?v=OnBhO3FVTTg). If you need any additional information, please let me know!

**Comment by jilladams** [comment]
I did! Installed the gem last Friday. Thanks!

**Comment by rmtolmach** [comment]
phew! 😅 Thanks!
