### ISSUE TITLE
Create presentation on synthesis from research of Learn More buttons

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#3983]
As a UX researcher, I want to know more about best practices for synthesizing feedback from research sessions so that I know I'm gathering feedback and utilizing it in the best way possible. 

AC: 
- [x] Created a presentation to give to other UX folks that shows how feedback was synthesized on the Learn More research

**Comment by 1Copenut** [comment]
@KevinMHoffmanUSDS The research has been synthesized for the Learn More buttons in this document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/product-dev-support/research/additional-info-tooltip-modal-usability/synthesis.md

I'm going to be adding several issue tickets to this epic to capture next steps.

/cc @CrystabelReiter && @emilywaggoner
