### ISSUE TITLE
Create QA onboarding breakout session

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#3985]
As a VFS team, I want to know how to do QA on the platform so I know how to do my due dillegence of testing and meet expectations

AC: 
- [ ] Create QA onboarding presentation for engineers, UX, PM

**Comment by peterhill-oddball** [comment]
Working on a slideshow here -- https://docs.google.com/presentation/d/1ULGWjk_yeMFvnl_kULnlqLWavkWp_hkMNs-mkiVJaAE/edit?usp=sharing

**Comment by peterhill-oddball** [comment]
Slideshow is done.
Survey template is here -- https://adhoc.optimalworkshop.com/questions/qa-onboarding
