### ISSUE TITLE
AWS access for Krutarth Joshi

### ISSUE THREAD

**Issue by krutarthj** [department-of-veterans-affairs/va.gov-team#39861]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Krutarth Joshi

### Your Email

krutarth.joshi@adhocteam.us

### Your Team, Role, and Company

Ligthouse Team Koala, Engineering Team Lead, Ad Hoc

### Desired AWS Access

I need same permissions as Dina Steeve

### Access Expiration

ongoing

**Comment by jsgarmon** [comment]
**For AWS Access**
User: Krutarth Joshi
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no (lighthouse-developers group)

Approvers will check with your VOR on your EQIP status.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS access approved

**Comment by rmtolmach** [comment]
@jsgarmon Can this be closed?

**Comment by jsgarmon** [comment]
Access granted and first-time login instructions sent.

**Comment by ianhundere** [comment]
asking for additional perms specifically the ability to run/maintain specific ECS clusters and RDS instances as per:
- https://dsva.slack.com/archives/CBU0KDSB1/p1668545596909119

**Comment by td-usds** [comment]
Provided this is similar to Kevin Gin's request, the same requested permissions are approved

cf.:
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1319104037 
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1320169859

**Comment by td-usds** [comment]
Provided this is similar to Kevin Gin's request, the same requested permissions are approved

cf.:
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1319104037 
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1320169859
