### ISSUE TITLE
VA Request Flow - Update the character limit from 250 to 100 (My reason not listed) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#39864]
## Description
When VAOS moves to V2 endpoints, a front end change will be required. Currently in the VA request flow, if the Veteran selects My reason is not listed on the Choose a reason for your appointment page, then the user is allowed to write a comment up to 250 characters. Since the V2 service does not accept characters over 100 for the field, the application will not proceed with the submission of the request. We will need tor reduce the character limit from 250 to 100. 

This change is only for VA Request flow when selecting My reason is not listed.  This change does not apply to VA direct and CC requests.  This change does not apply to comments for other reasons, which should remain at 250 characters.

![Screen Shot 2022-04-12 at 10.57.30 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/95d91127-c8d7-4113-9245-992898e868ac)

---

## Acceptance Criteria

Given when the user is on the VA request flow
When the user clicks on My reason is not listed on the reason for your appointment page 
Then the user can add their comments up to 100 characters 

### Design Assets
N/A 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@jenniemc - I'm reviewing this in staging using Judy Morrison and when I'm in the VA request workflow, it still shows 250 as the character count. Could you please advise? 

![Screen Shot 2022-04-28 at 4.27.16 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/646db9ad-3711-4b98-8dd2-8d7e2872f850)

**Comment by jenniemc** [comment]
{
"id": "97054",
"identifier": [
{
"system": "http://med.va.gov/fhir/urn/vaos/ars/id",
"value": "e5fe1f1b80241f60018066daa81a0016"
}
],
"kind": "clinic",
"status": "proposed",
"serviceType": "outpatientMentalHealth",
"reasonCode": {
**"text": "This is just a test to see the number of characters allowed for this entry. It is currently at limit"**
},
"patientIcn": "1012845943V900681",
"locationId": "983",
"created": "2022-04-26T11:10:47Z",
"requestedPeriods": [
{
"start": "2022-05-06T12:00:00Z",
"end": "2022-05-06T23:59:59.999Z"
}
],
"contact": {
"telecom": [
{
"type": "email",
"value": "[veteran@gmail.com](mailto:veteran@gmail.com)"
},
{
"type": "phone",
"value": "5035551234"
}
]
},
"preferredTimesForPhoneCall": [
"Evening"
],
**"comment": "This is just a test to see the number of characters allowed for this entry. It is currently at limited to 100 for submission."**,
"cancellable": true,
"extension": {
"ccLocation": {
"address": {}
}
}
}

**Comment by ldelacosta** [comment]
Validated the changes in staging and there is no error. 

**_For VA request workflow_**
When the Veteran enters the comment (up to 250) in the My reason isn't listed field, the logic will send the `text` field which will include the first 100 characters of the comment. In addition, it will send the Veteran's comment (up to 250) in the `comment` field (see response body below) 

![Screen Shot 2022-04-28 at 5.13.55 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/5d03814d-c7a7-4291-ad23-edddd27c4cc2)

**Response Body**
{
  "id": "97361",
  "identifier": [
    {
      "system": "http://med.va.gov/fhir/urn/vaos/ars/id",
      "value": "e5fe7920806ca5ba0180720659d30002"
    }
  ],
  "kind": "clinic",
  "status": "proposed",
  "serviceType": "ophthalmology",
  "reasonCode": {
    "**text**": "`Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Te`"
  },
  "patientIcn": "1012845331V153043",
  "locationId": "983GD",
  "created": "2022-04-28T15:14:20Z",
  "requestedPeriods": [
    {
      "start": "2022-05-31T12:00:00Z",
      "end": "2022-05-31T23:59:59.999Z"
    }
  ],
  "contact": {
    "telecom": [
      {
        "type": "email",
        "value": "test@id.me"
      },
      {
        "type": "phone",
        "value": "2566832000"
      }
    ]
  },
  "preferredTimesForPhoneCall": [
    "Afternoon",
    "Morning"
  ],
  "**comment**": `"Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test250Test!",`
  "cancellable": true,
  "extension": {
    "ccLocation": {
      "address": {}
    }
  }
}

**Comment by ldelacosta** [comment]
This has been validated, closing out the issue.
