### ISSUE TITLE
Create Video Tutorial for TestRail

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#3986]
As a QA person working on VA.gov features, I want to know how to used TestRail so I can be meeting the QA expectations of the platform

- [x] Create video
- [x] Distribute video

**Comment by peterhill-oddball** [comment]
OBS Studio

**Comment by pjhill** [comment]
Videos have been created, uploaded, and shared here -- https://drive.google.com/drive/folders/1_LGqyaORIttL6Jf98pJhS8fIk3AXT1t1

The videos are referenced from the QA platform documentation area here -- 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/testrail
