### ISSUE TITLE
Discovery: Define ownership of Grafana/DataDog Graphs

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#39877]
Determine which graphs in Grafana and DataDog are owned by Console Services.

## AC

- [x] A list of Grafana and DataDog graphs/dashboards that are owned by Console Services are documented.
- [ ] Related issues for said graphs' migration are created.

## List of Owned Grafana Graphs
https://docs.google.com/document/d/1EBxYyHz8p0RRaQ6-vfVoimJe0qwTcaxQsKIQk0qmbR4/edit#
## Related
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38518

**Comment by garfield786** [comment]
API (https://grafana.vfs.va.gov/dashboards/f/GyoeXowZk/api)
    API Error Rates
    Api Gateway Instances
    API Gateway Kong
    Api Gateway Monthly Report
    Api Gateway Services
    API Request Capacity
    Check-in Dashboard
    Check-in Phase 1 Minimal Auth Copy
    COVID Research (Production)
    COVID Research (Staging)
    ebenefits
    Flipper Metrics
    SSOe Stats
    VAOS PPMS
    Vets-API
    vets-api puma tuning
    vets-api to app mapping

VSP (https://grafana.vfs.va.gov/dashboards/f/k5kEuTQZk/vsp)
    Application Request Breakdown
    Backend Service Report
    Backend Service request count and latency
    Backend to Frontend App Mapping
    Breakers
    Error Rates
    External Service Performance Indicators
    External Service Status
    Forward Proxy
    http 499
    Job Queue
    Pact Broker
    Revproxy
    Semantic Logger - Loki Query
    semanticlog - Behind
    VSP Identity Log Queries Dashboard

VSP Utility (https://grafana.vfs.va.gov/dashboards/f/aK46uoQWz/vsp-utility)
    GitHub Metics Playground
    Github Runners
    Jenkins
    New Great Panel Copy
    Prometheus Stats
    Pull Request Dashboard
    Redis
    Sentry

**Comment by npeterson54** [comment]
Closing
