### ISSUE TITLE
DSLogon SAML Metric Bug

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#39875]
Need to figure out why the DSLogon SAML metric in this graph shows more successes than attempts: https://app.datadoghq.com/dashboard/97h-d7e-tgr/vsp-identity-monitor-dashboard?fullscreen_end_ts=1649776467907&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1649690067907&fullscreen_widget=8235376662564578&from_ts=1649688985564&to_ts=1649775385564&live=true

**Comment by bosawt** [comment]
@joeniquette Is this ticket still relevant?
