### ISSUE TITLE
Staging Review [Design System Team - Number Input Web Component]

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39882]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] Staging URL to access Number Input web component -  https://60f9b557105290003b387cd5-rmlfyhhrkt.chromatic.com/?path=/docs/components-va-number-input--default

- [ ] Product outline for Web Components - https://vfs.atlassian.net/l/c/XJX4274f 
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Your product’s content source of truth
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] List of known issues

     •	Issue 1
     •	Issue 2
     •	Issue 3

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by chaseakirby** [comment]
Review has been scheduled for April 21st at 1:30pm ET

**Comment by CherylEvans** [comment]
No Content FB at this time.

**Comment by ddzz** [comment]
No QA feedback, looks good!

**Comment by jimuhh** [comment]
Nice control. A few minor questions/issues

1. The usual term for this UI element is "[numeric stepper](https://balsamiq.com/learn/ui-control-guidelines/steppers/)" or "[input stepper](https://www.nngroup.com/articles/input-steppers/)" New VFS team designers are likely to call it that. 
2. Is there any context of use in which choosing a negative quantity, as the control allows, might be valid?
3. How can a field that already contains a default value of zero be "required" if zero is a valid answer to a question such as, "how many boa constrictors do you own?"   
4. If zero is **not** a valid minimum value, should it be available? The "number of passengers" steppers on travel sites have a default value of one. They do not allow you to search flights for zero people. 
5. Given that the developer can specify a valid default value, and set nonzero, positive, minimum and maximum values in code parameters, how could a properly configured control ever throw an error?

**Comment by briandeconinck** [comment]
No accessibility feedback. Thank you!

**Comment by pdavies88** [comment]
@jimuhh thank you for your notes I think this really opens up a conversation around governance of the input fields that have a type of number. A lot of the points I think should be brought up in a larger DSC conversation about how to handle situations we know would provide incorrect results. 
Additionally here is a more updated link to the component in Storybook: https://60f9b557105290003b387cd5-pqxrdpllos.chromatic.com/?path=/docs/components-va-number-input--default
We have made the decision to visually hide the steppers to mimic the behavior of the existing  React NumberInput component.

**Comment by allison0034** [comment]
No design feedback, thank you

**Comment by pdavies88** [comment]
@caw310 @k80bowman so we decided that we are going to keep Number Input in the Design System so I guess should this ticket be to put a conversation on the DSC calendar about governance in regards to this component since it is pretty open currently.

**Comment by allison0034** [comment]
@pdavies88 I filled out [a ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/719) and we discussed it at DSC. The decision was to leave the number input as is for right now.

**Comment by pdavies88** [comment]
@allison0034 thank you, should I close this ticket since it looks like we would not have action items on it at this time?
