### ISSUE TITLE
[FE] VA Alert

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39886]
There is default text for the close button aria label that needs translation.

Follow example in earlier commits of this PR to see an example of the va-text-input webcomponent: https://github.com/department-of-veterans-affairs/component-library/pull/346

Also example of DS teams implementation here: 
https://github.com/department-of-veterans-affairs/component-library/pull/367

https://github.com/department-of-veterans-affairs/component-library/pull/372

Test using the 8.4.0-0 version of the DS https://www.npmjs.com/package/@department-of-veterans-affairs/component-library/v/8.4.0-0

## AC
- [ ] Change the alert DS component to react to selected language
- [ ] Review with DS team?????

**Comment by loripusey** [comment]
I think this is a duplicate of 39885

**Comment by brianseek** [comment]
@loripusey This is not a dupe, this one is for a different component.

**Comment by loripusey** [comment]
@brianseek Thanks for catching.

**Comment by brianseek** [comment]
Created draft PR in DS repo. Have some questions due to maybe just weirdness on my local: https://github.com/department-of-veterans-affairs/component-library/pull/411

**Comment by brianseek** [comment]
Closing since this didn't make it into translations and has a work around to pass translated values to the aria-label. More details here: https://github.com/department-of-veterans-affairs/component-library/issues/343#issuecomment-1097210319
