### ISSUE TITLE
[FE] VA Text Input

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39885]
There is default text for the close button aria label that needs translation.

Follow example in earlier commits of this PR to see an example of the va-text-input webcomponent: https://github.com/department-of-veterans-affairs/component-library/pull/346

Develop using the 8.4.0-0 version of the DS https://www.npmjs.com/package/@department-of-veterans-affairs/component-library/v/8.4.0-0

## AC
- [ ] Change the alert DS component to react to selected language
- [ ] Review with DS team?????

**Comment by brianseek** [comment]
PR ready on DS codebase, waiting on translations: https://github.com/department-of-veterans-affairs/component-library/pull/398

**Comment by brianseek** [comment]
PR is merged in the design system. Moving this to closed.
