### ISSUE TITLE
Content/IA Request from Authenticated Experience - Profile Team for Notification Settings

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#39883]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [X] IA support
  
VA Profile/VANotify is ready to support a new notification and notification preference in the Notifications settings section of VA.gov Profile. We've updated the Notification Settings mockups to include a new group for Payments - Comp & Pen notifications. Our team would like to request a content and IA review of the mockups so we can discuss and confirm the wording and placement for this new section. 
 
We are looking for input on the following:
- Group name (currently "Payments" in the mockup)
- Item name (currently "Compensation and pension deposit notification" in the mockup)
- In what order the groups should appear (currently health care > applications, etc > payments in the mockups)
 
Screenshots:

<img width="606" alt="Screen Shot 2022-04-12 at 9 49 45 AM" src="https://user-images.githubusercontent.com/79372956/163013774-17b9071f-99f1-48ff-a0f0-f0b387401e9a.png">

<img width="601" alt="Screen Shot 2022-04-12 at 9 50 05 AM" src="https://user-images.githubusercontent.com/79372956/163013787-4dbb4cd3-8134-4ffa-885e-01b0ab7d6e9e.png">
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- Link to or attach user flows:
- Link to prototype or mockups:
[Desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/7yJKGDb)
[Mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/rbadYmA)
- Link to any epics/issues that may be helpful: #39166 

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: TBD - We'll continue to talk to VA Profile about when they think this might be ready and pushed to our staging account for review by our team.
- Estimated staging review date: No staging review
- Content and IA work needed by: As soon as possible so we can communicate requirements back to the VA Profile team, who will be implementing our suggestions

## Do you plan to bring this to an upcoming content office hours session?
- [X] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Authenticated Experience - Profile
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Sharon Kasimow
-	Designer: Christina Gednalske
-	FE engineer: Adam Whitlock, Mark Dewey
-	Product/team Slack channel: #vsa-authd-exp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Beth Potts.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by Samara-Strauss** [comment]
Hi all 👋 Wanted to give this a gentle nudge. I know y'all are swamped, but is it possible to get an estimate on when you might be able to slate in this work? I'm looking to set expectations for our downstream partner, so just let us know when you'll have bandwidth. Thank you!

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA will have recommendations on labeling the groups, here are my thoughts around the ordering of them..

I looked at various ways to order these - alpha, sequential, frequency, impact - and am inclined to order these based on frequency/popularity (to get the majority of users to what they need quicker), then by impact (how important/timely the notifications are). 
Health care - likely the source of the most frequent notifications, as well as timely and important to day to day activities
Applications, claims, decision reviews - this is a broad group that could be frequent or sporadic, but the notifications are likely timely and important
Payments - these are regular, but not necessarily urgent to day to day activities

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss. Thank you for the nudge! Lots of juggling while we await our new content team next week. Agree with Mikki on ordering. Here are the additional thoughts on labeling:

- Let's stick with **Payments** for now. As we add more notifications to this grouping, and as we get more Veteran feedback on labeling around financial groupings, we can definitely continue to revisit and iterate if needed. 
- I think we all agreed to drop the **Your** in **Your health care**.
- Let's change **Compensation and pension deposit notifications** to **Disability and pension deposit notifications**
- We're thinking about potentially dropping the word **appeals** in the first grouping just to save a word there. But Beth is helping us check with our VA partners on that first. I'll follow up here when we have an answer.

**Comment by Samara-Strauss** [comment]
Awesome, thank you! @cgednalske could you update the mockups based on @mnorthuis and @DanielleThierryUSDSVA's feedback? Re: the "appeals" issue -- let's leave that alone for now, and we can make updates later if Danielle and team decide to take it out.

Once the mockups are updated, I think this is good to close. The next step is letting VA Profile know what our suggestions are, @SKasimow.

**Comment by cgednalske** [comment]
@Samara-Strauss certainly! I'll make those changes. Thank you @DanielleThierryUSDSVA and @mnorthuis!
