### ISSUE TITLE
IA support from Claims & Appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39897]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
 
When viewing the [Claim Status Tool main page](https://staging.va.gov/track-claims/your-claims), an "Additional services" block includes a link to https://www.ebenefits.va.gov/ebenefits/homepage. We need to remove the e-benefits link and replace it with a new link, or links.

 <img width="632" alt="Claim status tool additional info block with link to e-benefits" src="https://user-images.githubusercontent.com/136959/163033678-a9cb6122-35f6-4c6f-b691-156b1acc1ce8.png">

The sentence "To update your personal information, get help filing claims or appeals, or view your uploaded documents, go to eBenefits." will send the Veteran to three different pages on VA.gov. Please confirm the destinations:

- Update your profile: `/profile/personal-information`
- Get help filing claims or appeals: `/disability/get-help-filing-claim/`
- View your uploaded documents: ?? - in the Claim Status Tool you can only see uploaded documents for a specific claim in the status tab as an event, or in the [files tab](https://vsateams.invisionapp.com/console/share/TNXSKHIK2P7/600538066)

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status
- Link to or attach user flows:
- Link to prototype or mockups: https://www.sketch.com/s/64bb337a-e31f-4a21-a92f-d89b50cba668/a/4aAdenq
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21207

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: No set date

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Claims & Appeals 
-	OCTO-DE product owner: Matt Self
-	Product manager: TBD (in transition)
-	Designer: TBD (in transition)
-	FE engineer: @Mottie
-	Product/team Slack channel: #vsa-claims-appeals

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Beth Potts.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@Mottie Sorry for the delay. We're so slow over here since we're currently in between contracts and the new team isn't onboarded yet. 

Will this work?:

**Additional services**

[Change your address and other contact information](https://www.va.gov/change-address/)
[Change your legal name on file with VA](https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/)
[Get help filing your VA claim or appeal](https://www.va.gov/disability/get-help-filing-claim/)

**Comment by Mottie** [comment]
Thanks!
