### ISSUE TITLE
Firefox (iOS) layout issue for sign-in modal

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#39898]
# Description
It appears there is a display issue for the sign-in modal on Firefox for iOS causing part of the page to be clipped (see attachment).  We'll want to fix this when possible.

# Acceptance Criteria
- [ ] Firefox for iOS displays the modal properly![Image from iOS.jpg](https://images.zenhubusercontent.com/609e8d5b852e7429aab750c8/79e2653a-4b6d-4b71-9454-320f36b11d40)

**Comment by nsoutouras** [comment]
Video of issue[Uploading... Image from iOS.MP4]

**Comment by nsoutouras** [comment]
We are unable to replicate this.

**Comment by AGarcia-Clarity** [comment]
Possibly able to close as we could not replicate it.
