### ISSUE TITLE
SOCKS access for Max Antonucci

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-team#39892]
### Your Name

Max Antonucci

### Your Email

max.antonucci@agile6.com

### Your Role

Front-end Engineer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBj5wgC5XNCoHwA0nDaG3vPj4q1bk6GBAko7t+QV0My91YtAtRUOieLImrWrS/mn8tMpx3DywzWZ/cyhvczmZ8h7/vb0LhapP8sJ8cta6UhqMqpoMx8GiplE+7LMyqgxfnziE0zfE05X0epD+HVUIxUqjOPUNvmBa9tuEg73Oz9DJCi68ai7nQPeqrpT2cg9nFiLbaI1IKLIQGT1WxFqegDcbClF23ys4riVz10wtbCcr+775JL2z40J7ErrKKjXcfuTsx3dbF9its/2b2zHhlxmhbBMj1WXSOfUU/43rPUyIipYvammATUGv2Rmp5MlnZrut/nkT7i4fJAPS0NzKYLh9dUYhlrALUcLH6FTZowPUb9SeLju11f2Iitx9BqQGlmo2Uvu0Xf/FhCSl8lnXajPr9WvI7FtDGQEEmjPZ1XxYxrPchjaInmIhIImBe2P7lhECtVxDCHrVwuWEnTimfEE84gPZ1TMJkc/z0TPFDxCRnQgjPxZ6UrjkqDRBKnXs= maxwellantonucci@Maxwells-MacBook-Pro.local

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.

**Comment by ryan-mcneil** [comment]
Adding for reference
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41602677/dd2991e7-9291-4424-9777-d3669adb3b43)
