### ISSUE TITLE
[Analytics] VEO Analytics Request

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#399]
## User Story
As a VEO user, I need monthly analytics for Education, Burials, and Claims so I can report on this data to internal stakeholders.

## Goal
- Provide monthly data for June in visualization 
- Provide links to Jack Yang within Google Analytics

## Acceptance Criteria
- [x] Monthly Data
- [x] Visualize Data

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@amycesal @joanneesteban I updated the post-launch metrics in Col. I, rows 72-77. 

FYI - the chart in the PDF used the label "Claims Submitted", but the metric we are pulling is "Claims Viewed".

**Comment by joanneesteban** [comment]
@nedierecel @amycesal Pre-launch metrics + Foresee CSAT are also updated.

**Comment by joanneesteban** [comment]
Data: https://docs.google.com/spreadsheets/d/1L_w8FhhcOttMitKB3_9ge8UN01GcSXmaPZWDIRJIhxI/edit?usp=sharing

**Comment by amycesal** [comment]
### Before
<img width="765" alt="Screen Shot 2019-07-03 at 1 34 20 PM" src="https://user-images.githubusercontent.com/1656046/60612733-5f89ce00-9d97-11e9-9d04-b226bd482381.png">

### After!
<img width="617" alt="Screen Shot 2019-07-03 at 1 33 47 PM" src="https://user-images.githubusercontent.com/1656046/60612742-67e20900-9d97-11e9-965a-f12a085b0873.png">

**Comment by nedierecel** [comment]
@joanneesteban I'm shifting the Milestone forward, as the training component of this issue will take place on 7/12/2019.

**Comment by joanneesteban** [comment]
Metrics have been sent. Will open new issue on training and metrics/visualization improvements
