### ISSUE TITLE
Adding Ashton Lee to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#39909]
I am requesting Ashton Lee DSVA Slack.

Please add lee_ashtonn@bah.com as a multi-channel guest.

Working on VA Lighthouse program on Benefits Intake API, Benefits Reference Data API, VA Forms API, VA Letter Generator API.

Thank you!

**Comment by LEHigley** [comment]
hi @regenauer-va do you know what channels i should use here? for multi-channel guest adds i need to add to at least one specific channel when setting up membership. 

thanks!

**Comment by regenauer-va** [comment]
@LEHigley I need Ashton to have access for multi-channel not single channel. sorry for the confusion
