### ISSUE TITLE
Add Analytics & Insights team labels to Platform Orientation templates

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39923]
## User Story
As an Analytics & Insights team member who is assisting with Platform Orientation, I want to make sure the tickets show up my teams backlog so that I can address them as they come up.

- Intended Audience: Analytics & Insights team
- Desired Outcome: `analytics-insights` label added to both Platform Orientation template and New VFS teams template
- Due Date: ASAP

## Description
Analytics & Insights team is helping manage the VFS Team Roster. They need to be informed of new VFS teams and new VFS team members so their label needs to be added to both the Platform Orientation template and New VFS teams template.

## Artifacts Needing Updates
[Github template - Platform Orientation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)  (Shira already added label)
[Github template - New VFS teams](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md)
[Platform Website page Guidance for new teams and new team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html) - update links to templates

## Acceptance Criteria

- [x] Platform Orientation GitHub template has been updated 
- [x] New VFS Teams GitHub template has been updated 
- [x] Guidance for new teams and team members on Platform Website has been updated 
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
@shira my bad, I meant to just close the pull request bc I did the same file twice

**Comment by allison0034** [comment]
@shiragoodman @chaseakirby this can be closed

**Comment by chaseakirby** [comment]
@allison0034 @shiragoodman Thanks Allison! Closing the ticket.
