### ISSUE TITLE
Print Materials for Trip

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#39947]
## AC
- Determine how many to print (10 each)
- Print documents
  - Word and PDF for staff is located here - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback
  - Word and PDF for vets is located here - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback
- Determine how many posters and sizes to print
  - Print posters 
- Determine if shipping or taking on plane 
- Send cost estimate to Sarah for printing materials

**Comment by benbrasso-agile6** [comment]
@zach-park the poster sizes are

8.5 x 11
11 x 17
24 x 36

We're scheduled for 6 clinics, but it's possible we visit more. Conservatively, I'd say we print 10 of each size. So, 10 of each size.

**Comment by zach-park** [comment]
Printed and brought them to the sites.
