### ISSUE TITLE
SOCKS access for Karan Krishnani

### ISSUE THREAD

**Issue by ksk385** [department-of-veterans-affairs/va.gov-team#39963]
### Your Name

Karan Krishnani

### Your Email

krkrishn@thoughtworks.com

### Your Role

Technical Lead (Dev)

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD279re+fNDGJxWlPcjqTYBJECZKiR0qu0kx3zseVkv4QTNSLiy/fPD+0+MNBYMnFJXGlAM853w4nhqs9iAmHlD2k4nBpvqVusdgu3Tj+5cPC7cJs3udlRzo/4pRxG/Byfl10jJs+RPv6hjWnjvwkQbh2cxwnS7TSujqJccNDaWSMg4EB22tX5DuxS693XuAWr6qpDWXtvwj3jQOVJs9wlSgFnBUggUt52F+J6adCvirM7GGR7BQI7mMOgeSxAnvdbMXyoDCkEyFvSnMJKGeasxaiB82vXz/AklLwiWXtiUpty6/5nFo3xlQcIMdPx3lei+TFjYKgjkx6dM0lLwCtYps73sBNiKbweQCZEY7ymPDAzDn0aqCk22TYrHjclBx8P+T9Ze3KCtJOa45f9Mn3SSkMC7xCpEJFzVhqFmGZ4wUQgF5vsHszY357TWMauAt5FTA6dwF6y0zK4JFoSGIJ/g7mmMhKVVtl5OpM6BrL6dkLD9Ee6PUC5Z9zfkhjW+eyc= karankrishnani@Karan-MBP.fios-router.home

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.
