### ISSUE TITLE
Update documentation: Form controls: Radio buttons

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39964]
## Issue Description
Make updates to Radio buttons on design.va.gov,  Storybook and Sketch to fix the discrepancies that have been identified. 

Discrepancies
- The Radio button focus halo in Sketch doesn't match how the coded component looks, where the halo expands the width of the entire radio button + text label row. 
- The focus styles do not match between va-checkbox and va-radio -- va-checkbox only puts the focus halo on the checkbox itself, not the checkbox + label. In both cases, the entire row is selectable. 

---
- [x] Add (Radio buttons web component) to the label for va-radio in Storybook 
- [x] Add link in Storybook back to Radio buttons on design.va.gov  https://design.va.gov/components/form-controls#radio-buttons
- [x] Update link to Storybook on design.va.gov to "View va-radio in Storybook"
- [x] Update Sketch file- The Radio button focus halo in Sketch doesn't match how the coded component looks, where the halo expands the width of the entire radio button + text label row. 

## Acceptance Criteria
- [x] va-radio  in Storybook  includes (Radio buttons web component)
- [x] Storybook has link to Radio buttons  on design.va.gov 
- [x] Radio button link to Storybook is labeled "View va-radio in Storybook"
- [x] Sketch file is updated so focus halo is on both the radio button and text

**Comment by GnatalieH** [comment]
I wanted to make a note that we are making the radio button focus halo look/behave like the checkbox focus halo, which just borders the form control, and we are not making the halo expand the entire width of the checkbox label. I've fixed the halo in Sketch to be circular and match our intended design. @caw310 and @k80bowman we'll need a follow up ticket for the development work. Thanks.
