### ISSUE TITLE
Rename #vfs-platform-support to #platform-support

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#39974]
## Summary

The [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) Slack channel is used as the entry point for providing help and support to VFS teams using Platform services.

To consolidate and streamline support requests between Platform teams, it is recommended that:

- All support requests go through a single channel, whether originating from VFS or Platform teams.
- Channel is renamed #platform-support

## List of known doc references
- [x] https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Getting-started-with-Platform-Analytics-&-Insights.1771864128.html
- [x] https://depo-platform-documentation.scrollhelp.site/developer-docs/Tracking-application-errors-with-Sentry.590774316.html
- [x] https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html
- [x] https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html
- [x] https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html
- [x] https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Closing.1823998114.html
- [x] https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html
- [x] https://depo-platform-documentation.scrollhelp.site/developer-docs/Manual-Testing.1904705636.html

## AC
- [x] Channel name has been updated
- [x] Channel description has been updated
- [x] Known documentation references have been updated

**Comment by EWashb** [comment]
This has been done. Also confirmed in each link above that the proper slack channel name is listed.
