### ISSUE TITLE
SideNav - Home breadcrumbs still display on staging

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#3997]
# Description

The `"Home"` breadcrumb still appears on the following pages:

* [VA Pittsburgh Health Care | Patient And Health Services | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/health-services/)
* [VA Pittsburgh Health Care | Locations | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/locations/)
* [VA Pittsburgh Health Care | Events | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/events/)
* [VA Pittsburgh health care | Veterans Town Hall | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/events/veterans-town-hall-1/)
* [VA Pittsburgh Health Care | Community Stories | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/stories/)
* [VA Pittsburgh Health Care | News Releases | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/news-releases/)

The desired behavior is that the "Home" breadcrumb does not appear on the above pages. While we originally thought this would be controlled by Drupal, it seems as though the breadcrumbs on these pages is actually custom within `vets-website`.

# Acceptance Criteria

- [ ] Remove "Home" breadcrumb on [VA Pittsburgh Health Care | Patient And Health Services | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/health-services/)
- [ ] Remove "Home" breadcrumb on [VA Pittsburgh Health Care | Locations | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/locations/)
- [ ] Remove "Home" breadcrumb on [VA Pittsburgh Health Care | Events | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/events/)
- [ ] Remove "Home" breadcrumb on [VA Pittsburgh health care | Veterans Town Hall | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/events/veterans-town-hall-1/)
- [ ] Remove "Home" breadcrumb on [VA Pittsburgh Health Care | Community Stories | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/stories/)
- [ ] Remove "Home" breadcrumb on [VA Pittsburgh Health Care | News Releases | Veterans Affairs](https://staging.va.gov/pittsburgh-health-care/news-releases/)

**Comment by ncksllvn** [comment]
Great job!!

**Comment by jenniferlee-dsva** [comment]
Hi @kelsonic - Just want to make sure I understand the list of page URLs you have above in this ticket. These are the pages that need to be worked on separately bc of the custom vets-website layer, not that these are the only pages you're removing the Home link from, correct?

**Comment by kelsonic** [comment]
This ticket was completed and merged and deployed a few months ago @jenniferlee-dsva 🙂The list of page URLs above do not have the `Home` breadcrumb anymore -- not sure if I understood your question, though!
