### ISSUE TITLE
Find all Wrong instances of "Blue Navy" and Replace with correct copy "Blue Water Navy Veterans""

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3998]
### **Bug Reported:**
Currently different variations of the Blue Water Navy web pages’ titles exist, and need to  be corrected and updated with “**Blue Water Navy Veteran**s”.

### **Correction Tasks:**
- [ ] Update and correct all instances of "Blue Navy" with "Blue Water Navy Veterans" 
- corrections should be made on pagy copy and meta/browser title as well where applicable
- 3rd item in screenshot provided is also showing incorrect formatting of meta titles
- "Top Recommendation' item text might need to be updated in the search.gov tool

**Details:**
- https://www.va.gov/search/?query=blue+water+navy
- https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/
- https://www.publichealth.va.gov/exposures/agentorange/locations/blue-water-veterans.asp

CC:  @ncksllvn @jenniferlee-dsva

**Comment by RLHecht** [comment]
@ncksllvn @jenniferlee-dsva Not sure where the search is pulling these pages from. The "Our Top Recommendations for You" page is not a current page in Drupal. 

That page is now this URL: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/ and iit's showing the correct format for a meta title tag: 

<img width="825" alt="Screen Shot 2019-12-06 at 1 48 06 PM" src="https://user-images.githubusercontent.com/48728214/70347679-139ff100-182f-11ea-8571-729cfe4f787b.png">

I'll keep looking for other instances in copy and titles, but not sure this is a fix I can make. Suggestions?

**Comment by aeltarhoni** [comment]
@jenniferlee-dsva top recommended search text is on search.gov and needs admin access

**Comment by Karak888** [comment]
@ncksllvn I believe you have admin rights to search.gov, so if you are able to investigate with @RLHecht and have a fix for this, that would be appreciated!! Thanks

**Comment by ncksllvn** [comment]
@RLHecht I update that link in the search.gov admin. Does it look right now? https://www.va.gov/search/?query=blue+water+navy

**Comment by RLHecht** [comment]
@ncksllvn That's the correct one though it doesn't have the "| Veterans Affairs" in the link title. Also, are you able to sentence case "Our top recommendations for you"?

**Comment by ncksllvn** [comment]
I added the `| Veterans Affairs` into the title but I'm noticing that other recommendations don't have that, so not sure.

I can sentence case that, sure. It'll be a PR in vets-website though, not a change in search.gov.

**Comment by RLHecht** [comment]
@ncksllvn you're right about none of the others having "| Veterans Affairs" after it. @jenniferlee-dsva can you weigh in on this? I had asked Nick to add it but in searching other pages none of the top recommendations have it after it. Is this purposeful?

**Comment by Karak888** [comment]
for  search.gov it pulling from meta title- manually in search.gov - search results except for top recommendations we control but the other pages are crawled by search.gov
