### ISSUE TITLE
Create sequence diagram for file upload

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#39982]
## User Story

_As an IET engineer I would like to define which operations the application will perform on an uploaded file_

## Expected Behavior

_A diagram is created and available to be shared with external audiences_

## Acceptance Criteria

- [ ] _sequence diagram for file upload is created_
- [ ] _Reach out to the security team to review this ticket._

**Comment by ewilson-adhoc** [comment]
https://vfs.atlassian.net/wiki/spaces/IET/pages/2161901623/DRAFT+-+File+Upload+Scan+Solution+Design

**Comment by MrBilnon** [comment]
![Untitled Diagram (3).png](https://images.zenhubusercontent.com/5d1b7f1a19ee4e0f38d34870/915c9559-f397-4708-bd7d-5666a4874213)
