### ISSUE TITLE
[Analytics Request] HCA Data Request

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#400]
## User Story
As a Personalization Product decision maker, I need data on the health care so I can use data in my decision making workflow.

## Goal
Provide TJ and Samara with requested HCA data.

## Acceptance Criteria
- [ ] Data has been aggregated
- [ ] Data has been shared with appropriate team

## Definition of Done
- [ ] **Attached to a Milestone**
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team**
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
Data for top events has been shared via the Analysis beta reports in https://analytics.google.com/analytics/web/?authuser=0#/analysis/a50123418w177519031p184318975/edit/dlBd1euRSxG2bOEbQRMchg
