### ISSUE TITLE
Confirm need for Facility Locator/Facility API URL link check function

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4001]
## Goal
Eliminate unnecessary redirect code. 
- As part of [#3385], logic was added to the Facility Locator so that the url for facilities returned in the search results would be directed to new facility detail pages as they go live. This process will begin in 1/2020 and is expected to continue for several years. Once all VAMC systems have gone live with the new template, this logic should be evaluated and considered for removal. 

## Acceptance Criteria
[ ] Unnecessary logic is removed if no longer needed
[ ] When a user clicks on the name of a Facility in Facility Locator search results list, the user is connected to the correct facility detail page.
[ ] Legacy Facility Locator interstitial facility details pages are not part of the user workflow.

**Comment by davidconlon** [comment]
this logic will likely need to persist during the migration of VBA and NCA Facilities, but we should monitor throughout the process.
