### ISSUE TITLE
Staging: Clinic with No Availability Shows 500 Error

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#40014]
Asked by Thomas Joyner  to log this as a front end bug. See https://issues.mobilehealth.va.gov/browse/VAOSR-3221 for full triage by Thomas.  

Steps to Reproduce: 

1. In VistA cancel clinic availability. This is done in VistA when the provider calls in sick, goes on vacation, etc.  CHY AUDIOLOGY  IEN 1014  Friendly Name Audiology
2. In VATS configure Cheyenne Audiology for Direct Scheduling Yes Any.  
3. In VAOS login as a veteran who has had a past Audiology appt at Cheyenne within last 24 mos.  cecil.morgan@id.me
4. Select Audiology. Select Cheyenne.  Select Friendly Name Audiology, yes make my appointment here.  Enter a desired date for appointment.  Select continue. 
5. Results Expected:  VAOS displays only an error message like VAR-Resources.  We couldn’t find an appointment for your selected date
6.  No error shows in Dev tools.  
7. Results Seen:  VAOS tells the user no slots (this is good) and then it shows an error message We've run into a problem trying to find an appointment time (this is BAD). Dev tools shows a 500 error.  
8.            https://staging-api.va.gov/vaos/v2/locations/983/clinics/1014/slots?start=2022-04-01T00:00:00-06:00&end=2022-05-31T00:00:00-06:00

errors: [

{title: "Internal server error", detail: "Internal server error", code: "500", status: "500"}
]

0: 

{title: "Internal server error", detail: "Internal server error", code: "500", status: "500"}
code: "500"

detail: "Internal server error"

status: "500"

title: "Internal server error"

 

End User Impact: 

User should not see the second error message.  This is conflicting with the above error message. Note this is not an issue in VAR-Resources.

 

Environments, users, and patients tested in:

Staging

cecil.morgan@id.me

Versions Tested: 

mobile-appointment-service 2.17.2

**Comment by ajmagdub** [comment]
VAOS V2 SystemsService get_available_slots was erroring out when no slots were found; updated get_available_slots method to handle cases where no available slots are found.

**Comment by beth-wodzinski** [comment]
@ldelacosta This passed testing. The expected error displayed, and no 500 error. Good to go.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
