### ISSUE TITLE
Update Team Roster (private) https://vfs.atlassian.net/wiki/spaces/OCLP/overview#Meet-the-team

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#40015]

**Comment by raywangoctova** [comment]
I was able to preview the update but not able to publish it.

**Comment by mchelen-gov** [comment]
@raywangoctova Added note about Confluence editing with GFE/VPN: https://vfs.atlassian.net/wiki/spaces/AP/pages/1287782439/Platform+Crew+operational+documentation

**Comment by mchelen-gov** [comment]
Added you to https://vfs.atlassian.net/wiki/spaces/OCLP/overview#Meet-the-team
