### ISSUE TITLE
Update Team Roster (public) https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#40017]

**Comment by raywangoctova** [comment]
I was able to preview the update but not able to publish it. Error: We’re having trouble connecting right now. Give us a few seconds to reconnect, and you can resume your work

**Comment by mchelen-gov** [comment]
@raywangoctova 
-  Added note about Confluence editing with GFE/VPN: https://vfs.atlassian.net/wiki/spaces/AP/pages/1287782439/Platform+Crew+operational+documentation
- Added you to Leadership section
- Analytics team roster is not showing for some reason
