### ISSUE TITLE
SOCKS access for [Lauren Conrad]

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#40016]
### Your Name

Lauren Conrad

### Your Email

laurenconrad1993@gmail.com

### Your Role

Sr UX Writer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpQweoPLKZoZv/bQ/5CkFREzSNgkTyhf2Yz/F9AdBGP+Gw0kLtgOtCl1aJwfNSKsuoFoRXhNZOm4NIL69KOTAmFsSAXY2l50ov1qdrQZD50y6jexio3AoMtIDF6JtY50mWNiHc13RNgylvOM1fnL/l+Diw7pIkLvwT+U5FNO3dRnTSa9X76w6K9UlU2s0BPQoYKpf3b1YHbSnaWvWqXmDnC27AJo3DBe9mJ7Y6ue9yZC2wl306eKbS2t2Lxir88NxgDF3W8FiwPESGo/4wLhHILwbDT+FmPzf4vF5BjgNDkeTY1vNru52Gc3+wGEdVib8WEamOTfGIEPc41K0szL7ejfnpbtY3egEP/lUGhwHfX6r9R2qHQkR4JtjXZyXXhI8nEL/A0jXxCeRGb5h7Rv7lpVeQOpubQ/pFKH4eaQWHw9tGfQUFvHW1PVE2VloZ6IoFDwFIIEpK73apIIs0EEy+lqEDR7DDqra8C33KyFuZF6H5yhz8LgncnMsRtXtY8s8= laurenconrad@LaurenConradMBP.fios-router.home

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.
