### ISSUE TITLE
Adding [Carolyn A. Williams; mostudiocarolyn] to DSVA Slack

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#40011]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request> DSVA Slack request

Are you requesting to add an individual as a:

- Full member **X**
- What channel(s) do they need to be added to? cedar_health_apartment

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
We have had new team members added to the 1095-B team

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [_caroline@themostudio.com_] as a full member.

**Comment by MOStudioCarolyn** [comment]
Typo in email above.

Please add [carolyn@themostudio.com] as a full member.

**Comment by tameracorson** [comment]
@LEHigley  Please see correction above.  I see "Caroline" in slack with caroline@themostudio.com in DSVA.   Can you change it to the correct version. **Carolyn Williams**; email **carolyn@themostudio,com**?  Sorry, my mistake on original ticket.

**Comment by LEHigley** [comment]
done
