### ISSUE TITLE
[Design] Direct Deposit: Latest call center guide updates

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4002]
Now that the functionality for direct deposit isn't changing, I can make the final call center guide updates and hand those off to Chante.

- [x] Add content about setting up direct deposit for the first time.
- [x] Get latest call center guide updates to Chante.

**Comment by Samara-Strauss** [comment]
@clantosswett Attached is the latest (and hopefully final) direct deposit guide for the call center. I added a screenshot of the "Add" flow we launched a couple weeks ago. It is in the “How to Access and Update Direct Deposit for Compensation & Pension” starting on page 4 (step 4 in the process). 

I also made some edits to the last section — "Additional Information on Direct Deposit for Compensation & Pension" on page 20 to mention that people can switch from paper checks to direct deposit online in addition to the other methods mentioned in the document.

Let me know if you have any feedback!

[Direct Deposit Call Center Guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3933784/Direct.Deposit.Call.Center.Guide.pdf)

**Comment by Samara-Strauss** [comment]
@clantosswett closing this. Let me know if you have any other feedback or need any other updates.

**Comment by clantosswett** [comment]
@Samara-Strauss would you mind uploading the word file of the product guide? I need to customize part of it for a specific call center use case. Thanks!

**Comment by Samara-Strauss** [comment]
Here you go!

[Direct Deposit Call Center Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3941845/Direct.Deposit.Call.Center.Guide.docx)
