### ISSUE TITLE
Integrate JSDoc with Design.va.gov for Events and Props Information

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#40046]
## Description
We currently use JSDoc to generate a JSON object that we digest in Storybook for our Events and Props information. We would like to use that same JSON object in design.va.gov to keep data in sync and add Events and Props information to each of our components pages on design.va.gov.

## Sample PR
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/compare/gulp-component-docs

## Acceptance Criteria
- [ ] Use gulp to leverage the JSON object from the component library that we can then parse to show Event and Props information on Component Pages
- [ ] Pick a component on design.va.gov and utilize this functionality to display the Event and Props data as an example to use for other components

**Comment by andresriveratoro** [comment]
I took a quick stab at this on this [PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/703) building off the `gulp-component-docs` branch.

**Comment by pdavies88** [comment]
@caw310 @k80bowman I think we can close this since it has been implemented already: https://design.va.gov/components/accordion#code-usage

**Comment by k80bowman** [comment]
That's great! Closing.
