### ISSUE TITLE
Urgent Care PDF Research Synthesis

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4004]
## User Story
As the Facility Locator team, we need to understand how to provide information on urgent care eligibility and benefits in preparation for a visit. 

## Tasks
Synthesize information gleaned from Urgent Care PDF research sessions

## Acceptance Criteria
[ ] Research readout summary which includes findings, recommendations, additional questions

This follows [#3897]

**Comment by mmiddaugh** [comment]
@arickalewis1 Please attach artifacts (or link) when available and then close this issue.

**Comment by arickalewis1** [comment]
Research findings document which includes supporting files: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-PDF/research-findings.md
