### ISSUE TITLE
SOCKS access for [Amy Goldman]

### ISSUE THREAD

**Issue by amygoldman** [department-of-veterans-affairs/va.gov-team#40056]
### Your Name

Amy Goldman

### Your Email

agoldman@thesocompany.com

### Your Role

UX Writer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmJrBnCghwVI/2pn1QtXS3MqJtSGU49iQ8vjOds7nVYciuzY3PW/u7edp6l0/STaxivZDCwBEdaIpCj8Chu6FfsSN0RMWfWx1EIzh7HL4l8EVHoWd32BIUQ90UTfT/iF6Mcag31XKd+4Y++M138plEUx/8SkYvTljX1wZZm8RnkvA42TNOqADhpcAX1coZGD6gITy17+IG5+YlY1R8pySN+zv4TfcvHIyZEYNmuORzGGEs/P99RrZwQKCgdwXjqSctVRc7B3c6f6COdlA5HouMg1qvTB/GyqQD1JAhM2oUvvbwDHtFUJDTyJYnRO73ceaB4nM0rXpx0ecPQPnaYuUqm8326BDbE4Y+iYFBErmXbot/qSQ0GIzIkCU3iPyiXaJ2o4aiiwE7SDfrrUywB8l+5qDJU7vXtKNCywtxb6QYqp3swKNKTctYUPQBacPQDFn1qXTdh/MJH26BNZpG4Xk1CYtqQKM/QokHzBTIfI5ax1EeWK+f6aSqoJ2UjVnlaK8= amygoldman@Amys-Air

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.
