### ISSUE TITLE
Offboarding of VSA team members

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#40059]
This is a mass offboarding request to remove all VSA team members that no longer support the work due to the VSA contract ending. The have all finished their work and can be removed immediately. 

# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
Brian Lloyd	GCIO	Product Manager	Public Websites   
Dillo Raju	GCIO	BE Engineer	username: dillo     dillo.raju@govcio.com
Kevin Musiorski	GCIO	  kevin.musiorski@govcio.com	
Lance Sanchez	GCIO	Engineering	Facilities    lance.sanchez@govcio.com
Larry West	GCIO	Content Writer	VAMC   username: larrywest52  larry.west@govcio.com
Tyler Simoni	GCIO	FE Engineer	Search & Discovery    username: tsimmz   tyler.simoni@govcio.com
Amanda Leaders	GCIO	BE Engineer	eBenefits    amanda.leaders@govcio.com
Candy Clark	GCIO	Designer	eBenefits      username: candy-gcio    candy.clark@govcio.com
Corey Parker	GCIO	Product Manager	Modernized Check In     username: jparker0425  corey.parker@govcio.com
Jason Wolf	GCIO	Product Manager	eBenefits      username: jason-gcio   jason.wolf@govcio.com
Kathleen Crawford	GCIO	BE Engineer	eBenefits     kathleen.crawford@govcio.com    
Lisa Tombley	GCIO	Business Analyst	VAMC       username: ltrombley   lisa.trombley@govcio.com
Megan Gayle Crigger	GCIO	Designer	Search & Discovery      username: mgleo   megan.gayle@govcio.com
Napoleon Kernessant	GCIO	FE Engineer	Facilities       username: gcionapoleon   napoleon.kernessant@govcio.com
Nicole Leonard	GCIO	Product Manager	Search & Discovery       username: nicole-leonard nicole.leonard@govcio.com
Patrick Sanders	GCIO	Content Writer	Content Team         username: psanders86  patrick.sanders@govcio.com
Ron Tafoya	GCIO	Content Writer	VAMC        username: ronrtafoya   ron.tafoya@govcio.com
Ronnie Henry	GCIO	Product Manager	Claims & Appeals            username: vhenry07   ronnie.henry@govcio.com
Selina Cooper	GCIO	Content Writer	Content Team   selina.cooper@govcio.com
Stan Gardner	GCIO	Product Manager	VAMC/Content Team     username: sgardnerpmp   stan.gardner@govcio.com
Troy Riser	GCIO	Content Writer	Shared         username: troyriser    troy.riser@govcio.com
Ed Boehme	GCIO	Business Analyst	VAMC        username: edwardboehme05   edward.boehme@govcio.com
Christian Valla	GCIO	Designer	Claims & Appeals      username: chrvalla  christian.valla@govcio.com
Csaba Nemeth	GCIO	BE Engineer	Claims & Appeals         username: cnemeth   csaba.nemeth@govcio.com
James Adams	GCIO	Designer	eBenefits         username: sporeboy   james.adams@govcio.com
Trent McDole	GCIO	FE Engineer	Public Websites         username: tmac9494   trent.mcdole@govcio.com
Randi Hecht	GCIO	Copy Editor	Content Team      username: rlhecht   randi.hecht@govcio.com
- team name:
  > 
- role on team:
  > 
- expected last day:
  > 
- company they work for:
  > 
- email:
  > 
- GitHub username:
  > 
- additional access they may have:
  > ex: SOCKS, Pagerduty, Google analytics, etc.
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Remove from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics, and Domo access removed (if applicable) 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights , @department-of-veterans-affairs/confluence-admins

**Comment by bsmartin-ep** [comment]
GA and Domo access removed. No GCP / BQ acccess found.

**Comment by CoryTrimmUSDS** [comment]
All names above with `/request ...` have been removed from DSVA Slack.

**Comment by oseasmoran73** [comment]
## Sentry

Removed access for the following:
- Dillo Raju
- Lance Sanchez
- Jason Wolf
- Kathleen Crawford
- Megan Gayle Crigger
- Csaba Nemeth

All other users were not found

**Comment by oseasmoran73** [comment]
## Datadog

Removed access for the following:
- Dillo Raju
- Lance Sanchez
- Corey Parker (under jparker)
- Jason Wolf

All other users were not found

**Comment by oseasmoran73** [comment]
## Pagerduty

No users found

**Comment by oseasmoran73** [comment]
## VA Github

Removed the following users from VA github:
- Dillo Raju https://github.com/department-of-veterans-affairs/github-user-requests/issues/10491
- Larry West https://github.com/department-of-veterans-affairs/github-user-requests/issues/10492
- Tyler Simoni https://github.com/department-of-veterans-affairs/github-user-requests/issues/10493
- Amanda Leaders https://github.com/department-of-veterans-affairs/github-user-requests/issues/10494
- Candy Clark https://github.com/department-of-veterans-affairs/github-user-requests/issues/10495
- Corey Parker https://github.com/department-of-veterans-affairs/github-user-requests/issues/10496
- Jason Wolf https://github.com/department-of-veterans-affairs/github-user-requests/issues/10497
- Lisa Tombley https://github.com/department-of-veterans-affairs/github-user-requests/issues/10498
- Megan Gayle Crigger https://github.com/department-of-veterans-affairs/github-user-requests/issues/10499
- Napoleon Kernessant https://github.com/department-of-veterans-affairs/github-user-requests/issues/10501
- Nicole Leonard https://github.com/department-of-veterans-affairs/github-user-requests/issues/10502
- Patrick Sanders https://github.com/department-of-veterans-affairs/github-user-requests/issues/10504
- Ron Tafoya https://github.com/department-of-veterans-affairs/github-user-requests/issues/10505
- Ronnie Henry https://github.com/department-of-veterans-affairs/github-user-requests/issues/10506
- Stan Gardner https://github.com/department-of-veterans-affairs/github-user-requests/issues/10508
- Troy Riser https://github.com/department-of-veterans-affairs/github-user-requests/issues/10509
- Ed Boehme https://github.com/department-of-veterans-affairs/github-user-requests/issues/10510
- Christian Valla https://github.com/department-of-veterans-affairs/github-user-requests/issues/10511
- Csaba Nemeth https://github.com/department-of-veterans-affairs/github-user-requests/issues/10512
- James Adams https://github.com/department-of-veterans-affairs/github-user-requests/issues/10514
- Trent McDole https://github.com/department-of-veterans-affairs/github-user-requests/issues/10515
- Randi Hecht https://github.com/department-of-veterans-affairs/github-user-requests/issues/10516

All other users were not found

**Comment by jsgarmon** [comment]
AWS access removed for Csaba Nemeth, Dillo Raju, and Lance Sanchez.
SOCKS access removed for all other users.

**Comment by jsgarmon** [comment]
@department-of-veterans-affairs/confluence-admins: can you verify all users have been removed from confluence?

**Comment by andreahewitt-odd** [comment]
Only one person (Dillo Raju) had confluence access and it's been revoked

**Comment by jbritt1** [comment]
Thank you @andreahewitt-odd!
