### ISSUE TITLE
Design - Bad Address Indicator - Create High Fidelity Mocks

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40058]
### Acceptance Criteria

**Comment by cgednalske** [comment]
[@SKasimow](https://github.com/SKasimow) and [@Samara-Strauss](https://github.com/Samara-Strauss) -- High fidelity mocks for bad address indicator are ready for review! Here's [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/eKeeAl0) and [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/EPqp12/a/wLqqgOp/r/O8adb4), which start on the Personal information alert and then go through the Contact information alert/states if you arrow right. Let me know if any changes are needed!

**Comment by SKasimow** [comment]
Looks good to me thanks!
