### ISSUE TITLE
Remove links to Health Benefits Explorer

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#40064]
## What's needed

VHA is deprecating the Health Benefits Explorer because there's not a team to adequately maintain it. 

- We need to remove the link to it from our "More resources" spoke (not on hub page, but in left nav).

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/3d2da2cf-8071-4802-ba7a-2ef21865d008)

- We need to edit the "Learn more about income limits" link on the eligibility page to point directly to the [income limits information page](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Fhealthbenefits%2Fannual_income_limits_health_benefits.asp&data=04%7C01%7C%7C2ffe747950d740ffb48308da1f1497d6%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637856470541027675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SkIyLNl28DIP52urlij7Lk7f03JoMfcRxJFiMCBPthM%3D&reserved=0) instead.

**Comment by mnorthuis** [comment]
This should go to Randi

**Comment by DanielleThierryUSDSVA** [comment]
This is complete. Validated on prod. Closing.
