### ISSUE TITLE
Renaming of some vsa Slack channels

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#40075]
# Description

Requesting to rename some existing slack channels due to recent transitions:

* #vsa-facilities to **#sitewide-facilities**
* #vsa-public-websites to **#sitewide-public-websites**
* #va-sitewide-content-ia to **#sitewide-content-ia**

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by cmaeng** [comment]
cc: @davidconlon

**Comment by LEHigley** [comment]
slack says #sitewide-facilities is already in use but the other two are done

**Comment by cmaeng** [comment]
thanks @LEHigley. when i do a channel search for "sitewide" it doesn't seem to come up. do you know how i could locate the existing one (#sitewide-facilities)? 
![image](https://user-images.githubusercontent.com/60702623/164011976-24055559-083d-4046-a38e-3362880dbd26.png)

**Comment by LEHigley** [comment]
sorry the exact error message is "that name is already taken by a channel, username, or user group"

**Comment by cmaeng** [comment]
thanks @LEHigley , could we try renaming once more please? i think i found the slack group and changed that so it should now be available.

**Comment by LEHigley** [comment]
looks like this was done!
