### ISSUE TITLE
SOCKS access for Brian DeConinck

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#40088]
### Your Name

Brian DeConinck

### Your Email

brian.deconinck@adhocteam.us

### Your Role

Accessibility Specialist

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD6J7SzpsEmghOLS6+uuQvxwseVpbEpHdJf0Huzi33VqWuyn90+voBaZVqGFOVL4+QwDChIzNl9tBMyBA6GTpeRFrERy4n/aanizElizg0ujR/mBhiH5Gz/6cgo9WXNF2PRsp26YpJyJpmX7wdtuhX2KQ5CJX+4yeVg5OYXp7RjjFGp2NCHTeNloI9/iyj3E8UXtNjDqIhMil0pnRERr3V9OS0RdBD3rBnGTqIZTKAVL50RQg123fChYeDU0CucnjoG4VkJiAUNwoxzNzUGy5F/bslhVb4yn/sAsXJQXM1UzUlMn8TLJdJp6aKZ3ePs9O5KL2mi94/9a38I2WC397MJ9e9y6PFt3k967fredijBdWl68QFVkDn1Zk4JtAqREiBaIeSm83vkUmM2zdhKu9uvLCK7JpgoQZnuGq+/YbgBD8xCSnrPVm6Gdp4iKtq2/fmDfQ88OCVVKXgEwWwwQXiwWd1zbDWxVvxp6/a2pWJ/ETIiZMLWP2mOw9PZcWyqRDM= briandeconinck@BrianDeConinck-HP

**Comment by briandeconinck** [comment]
Note: I had previously requested SOCKS access, and received it. At some point in the last few months I accidentally reset things on my machine and am reconfiguring SOCKS fresh. Sorry for the extra ticket.

**Comment by oseasmoran73** [comment]
@briandeconinck No worries! Will create a PR shortly to update information with new SSH-key

**Comment by oseasmoran73** [comment]
@briandeconinck All set! Updated SSH key accordingly. Relinking [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) should you need

Closing ticket
