### ISSUE TITLE
Adding multiple government individuals to DSVA Slack

### ISSUE THREAD

**Issue by RileyRPM** [department-of-veterans-affairs/va.gov-team#40084]
I'm requesting that the following government individuals be added as FULL MEMBERS:
 
Joseph.Pugh@va.gov
Madhu.Ramani@va.gov
Robert.Berry@va.gov
Dennis.Wang2@va.gov

These individuals will be assisting with the delivery of Education Benefits Products. 

Additionally, I'd like to request that someone look into the access for Darla.VanNieukerk@va.gov as I believe she was once invited but she has not been using slack... Maybe a refreshed invitation would be good? 

- Please add Joseph.Pugh@va.gov as a full member.
- Please add Madhu.Ramani@va.gov as a full member.
- Please add Robert.Berry@va.gov as a full member.
- Please add dennis.wang2@va.gov as a full member.

**Comment by LEHigley** [comment]
added first 4, darla is showing as an active member

**Comment by RileyRPM** [comment]
Sweet @LEHigley I appreciate it
