### ISSUE TITLE
[Research] 10-10EZ - Short Form: Run UAT on short form once in prod

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#40087]
## User Story

Once the Short Form functionality has been initially deployed to production, we need to conduct UAT to ensure that the functionality is working as expected from accessing, completing, submitting and downstream system success or failure.

## Expected Behavior

- Moderate and run UAT on 10-10EZ in prod

## Acceptance Criteria
- [ ] Research plan & conversation guide sent to recruiting
- [ ] Moderate UAT
- [ ] Organize and upload notes to github

## Resources
- Research plan and convo guide #37897

<Details>

<Summary>Slack Conversation on how testing will work with the feature toggle (Dene' and Lisa)</Summary>

**Dené Gabaldón**
 May 16th at 12:35 PM
Hey Lisa Zapson Heather Justice
 I just realized that we’re supposed to be conducting UAT in prod not staging (and this especially matters for folks that will be going through the authenticated experience). What do you all think of me flipping our UAT with usability research, and conducting our usability research in staging instead and UAT then in prod?

**Heather Justice**
How are we coming with the feature flipper?
I think that would be fine Dené Gabaldón
If we have the feature flipper in place, then should be no problem

**Lauren Alexanderson**
Agree wit hthis
For the feature flipper & UAT - are you building a % rollout and a whiltelist
that has proven critical for other apps doing uat in the past

**Dené Gabaldón**
Great! Lisa is going to let me know in the next couple of days when flipper will go on, we’ll spend the “recruiting week” testing it internally and then I’ll go ahead and conduct usability.
Yes to creating a whitelist
Will also need a plan in place to wipe the applications that get submitted during UAT

**Lauren Alexanderson**
i would consider not having them hit submit
or do a couple rounds
you want to validate in prod that the right screens show to the right people based on their data.

**Dené Gabaldón**
Yeah we can do that too. I just wasn’t sure since we had been having some errors on submission if we should have them go ahead and submit,

**Lauren Alexanderson**
yeah for r1 - i would do a “is everything showing that’s supposed tobe showing”
and then for r2 - when we do real UAT submissions, there is no ’pulling them back”
someone would actually be submitting a 1010
which, for other apps, we then work very closely with ES & HEC to track
But i generally take a rule of thumb with uat - a person participating in UAT shouldn’t have permanent changes to their va record as a result of participating in uat
i’d much rather we tke other measures to validate submission errors

**Lisa Zapson**
I created the Flipper Feature based on cookie and not user, because we want to roll out for both authenticated and unauthenticated. If user then we can only have a percentage based on authenticated and all for unauthenticated.  We can set a specific user with cookie,  You will need the user's ID to set for a specific user.  For example, this is  screen shot from flipper feature UI for cg poa, which is also cookie based as they are unauthenticated users.

**Dené Gabaldón**
Ok I’ll coordinate with you Lisa Zapson
 to understand. I think I’m confusing myself whether we can do auth usability testing (with real short form triggers) in staging or not. (edited) 

**Lisa Zapson**
Dené Gabaldón We should be able do usability testing in staging, with short form triggers and UAT testing in prod. I think both of those should be fine.

</Details>

**Comment by markfallows** [comment]
Can reuse the Conversation Guide and Research Plan as templates for this validation.
