### ISSUE TITLE
Discovery - automated metrics gathering for vale

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4008]
## Problem Statement
How might we measure the adoption of vale plain language content validations as part of VFS team members' workflow, so that we can better determine our impact and next steps for implementation?

## Description 
Explore (so that we can then implement) automated metrics gathering so that we can determine whether to invest more resources in automated content tests, whether to change our approach, or something else. 

### What to track
"Errors per PR over time" is the basic idea of appropriate measurement discussed by the team — this would allow us to track how many errors were appearing for users, _and_ whether users implemented changes in their own content as a result of the validations. 

Other ideas for metrics gathering: 
- # of nodes and/or PRs that show the validations at all (over total nodes and/or PRs?)
- Unique users who encounter the validations
- Most frequent validation? (Some measure of which validations people are encountering most and least)
- Validations per node and/or PR over time _specific to a certain validation_ (this would show us which validation people are most likely to act on!!) 
- Qualitative survey of VFS teams to get a sense of level of adoption 

## Definition of Done
- [ ] Initial metrics to gather have been chosen (based on research of technical implementation)
- [ ] Technical approach determined for above
- [ ] Next steps determined and captured as ZH tickets

**Comment by billfienberg** [comment]
The `vets-website` repo currently uses [Code Climate](https://codeclimate.com/) to track stats like test coverage and display potential issues with a PR. 

Code Climate dashboard for `vets-website`: 
https://codeclimate.com/github/department-of-veterans-affairs/vets-website

Example: https://github.com/department-of-veterans-affairs/vets-website/pull/11539
![image.png](https://images.zenhubusercontent.com/5dcadfa162b0b700019b1427/36a42ddf-c771-4e5d-bc21-ef3c57a8f42a)

Unfortunately, Code Climate doesn't currently have an existing `vale` (or other plain language linting) plugin: https://docs.codeclimate.com/docs/list-of-engines
