### ISSUE TITLE
Adding Ali Mizan to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#40096]
Good afternoon, 

Please add mizan_ali@bah.com as a multi-channel guest.  Channel - evss-devs

Working on VA Lighthouse program on Benefits Intake API, Benefits Reference Data API, VA Forms API, VA Letter Generator API.

Thank you!

**Comment by LEHigley** [comment]
@regenauer-va what channels should they be added to?

**Comment by regenauer-va** [comment]
Please add ***@***.******@***.***> as a multi-channel guest. Channel - evss-devs

Kara Regenauer  | Staff Technologist – Senior Consultant
Booz Allen Hamilton
407.718.4441
***@***.******@***.***>


From: Lacey Higley ***@***.***>
Sent: Monday, April 18, 2022 3:13 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Regenauer, Kara [USA] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Adding Ali Mizan to DSVA Slack (Issue #40096)


@regenauer-va<https://urldefense.com/v3/__https:/github.com/regenauer-va__;!!May37g!P7P5n6-VUEin65nCFYX4Bjb61UoPMSqpQH1wRqwQwVKKg6XUDL96zXACTBE8MK-5QBmXfUdHhJ9J1SI4HyJiQyplHQ$> what channels should they be added to?

**Comment by regenauer-va** [comment]
Please add Ali to Channel - evss-devs 

thank you!!
