### ISSUE TITLE
SOCKS access for [Sean Sewell]

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#40094]
### Your Name

Sean Sewell

### Your Email

sean.sewell@oddball.io

### Your Role

UX Designer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAX32i9HYdfIDOajNf9UhAAGddRb+sgqWpWfh77/MLIt1Gz9aEh6M6hCh4o7Hi8gxMz9UGhtfhV3Q9Y4pqh0ClDt4x1felctdwKhZxvf0g2I4Ei+1FD8cS4oZnotqUATr86R3skblzIfuhvJdtjQ1sOPpNz+hp5gnN/VqZ9qZzE0UYaB+q70GyJNim8InSLksXieziCEPcIrlvpDg2MTQ5tjYGmq5fEkz/T0gPRIIVDli6q0dOHaQS2uhBErxdx8KBxnrt9GTgpDghuhK6wBbh/ISoKgM4m9u4hn/5gAgWDij2NGndE+89WRyCKHuowRt+J/b8N31+C2g8RdofYNZfOOOAVbXOyZj2VLgWCn7nTCblgk/sd2Jz2fH4LolAXldrkhMY2//X0okp+gYK6W2NVCxFIXdKlrNOVNpYbWnpPzL6JhR+sw2IoR6UTst1pBn+cSkNJ42hmxbV4jtVLJOL/ZS/Gh8Ry9zxJiy+++mtX/wtkuQFT1lJtlpfbNXAtb0= seansewell@Seans-MacBook-Pro.local

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
