### ISSUE TITLE
SOCKS access for Ben Brasso

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#40092]
### Your Name

Ben Brasso

### Your Email

ben.brasso@agile6.com

### Your Role

UX Researcher

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYxBhWCuVwyC7ex4uSBVm7C4BukaggskHBO0cDBEqIxZ8eVf5eLqlzvnMWD7uGEwWnzwcEgJLXDsqKeQ0+Q9Ri/tx89suC1iW/ibWiOdFEb3hn56NNJjnIiuYW1PGx1GUxdijRZIdjcJmH0kUgkXKu0BsbF4HOcN7Y2JlgclZr3h4y05y1o1lLStqMaJ4z4JTKbCnFOUt2JuG0o/fIgHbKwsdNfC/5zA8AmLm3rIDCRqBs/QUyQECUDpug0PJwk8K5oZlFC97nae3O8sbIHPQcbDxcnhkHhz8s6Sy3MvMD8PEIGrUUHRtukRrNepSNJ6baUHJLnVVeyMzLAN/Q1Ni72KUnrr2B0BEIcjW2mfFWQc33L2r2bHIiL0SiM70t10J19W0Kv7jF2O9+K8OADOvx1M103jcfOgZo0JdJVgx5FyYHpGLAroF5YYc0Jti/46abXdhJr1YXTdGwn44+/65p08grqQaNGGf82UjeBHW5R3hy8w0DHDK2nCoMpi+jOrc= Ben.Brasso@Agile6A82.local

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
