### ISSUE TITLE
SOCKS access for Cheryl Evans

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#40090]
### Your Name

Cheryl Evans

### Your Email

cevans@thesocompany.com

### Your Role

Content Editor

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDv00BLlFh1qPEfTOcbW5IHGu/HxIsCr7A4fRHD/ySfuLXosEGQu0WLpCIUTAfcL/x5ERCaSINifk0H5R8WqPVmeiWsPySn79fVZXLZ/WN49mzlPDGLDdcU6ecwwVoyK6ochyu4OjUSwZ71f3iiXhsn5fRrFq0VId4CWv6ZrRLRMiWkLkwq+DwSP0ThHHN4WjxtUQj2XRdgPBZIcLbfzTVRkzrqlVhcNCziGl1SX9JEuhXUjKDRYembLh+562ceOnXfhl8KXyHXwTL2tO67SXe46WxHK4jGew16ca1sEjflUHxhZnPxHU4MnaTrrUfdKRoiPPjQ0UqoVZGt1jdKjnp1oj9Lbf9R31pWczFc1Oi37x5MBev0ABzD4coQ82e65we/FNQE37bzi5GJprcwxJMP5vPwmOiliGMIyNFV85buttnszj7BnfpJOWL4jgmDP/8aYGncqv2BbE65bDxAqQ9ojh1KRoUfcw5ge1qi+q568KZYH0PKSyeiozKkyngGM6k= cherylevans@Cheryls-MBP

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
