### ISSUE TITLE
SOCKS access for Clayton Zook

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40108]
### Your Name

Clayton Zook

### Your Email

clayton.zook@oddball.io

### Your Role

UX Researcher

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXW+YnUiuEMjPBnbZ8okUpdOsCo5fJsHnhonQ10h1sNa1EUl5ali4QjE0Rb5lP9dFEJUpyzqaNc+qgDMZqtzNbGVvU1tqoSKeEy7Ibw/t0xifwHhBDVIglLz8z4myTwQfHJU37tTcwxHpnLz6W1/U+L+9EG3p+OBHCD06zHxDcYtQVw2Wp2MpaTI/meBquKYPn2ThGQYCfUNgAS0ubG2HA+Ky4loZUhLqnyNGZbgYras3hVNEXgXgbdh/0ugzaYS/7112Pj0G+xgEdk1EeglnMZ8kKPnwMCU1Hvx5gib3c4wD1/2vYnninxjrfpYN8ZHGTUXvwxs+t+Y2PavG7f0nITmgzX//hRCGeuxBU91ig0D/nzfjCVfZwXOJmMRO+3in9zHPfQdN5ZCbjlFN2q4vaGpj3i2DpB0hwL+v4uhLWxW9nodaeJ/xY0QMkoMg272al+GVfE1v8qBzVMvpmnH59b792tu404ciobW+5slMn6x+1pE/yG9WdInAP12XMW60= czook@Claytons-MacBook-Air.local

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
