### ISSUE TITLE
CT: Section 107 - Iterative Solution: Calculate Housing Based on Location of the Campus where the Majority of Classes are taken

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4010]
## Purpose
As a user of the Comparison Tool, I need the Comparison Tool on VA.gov to support the legislative changes for Section 107 of the [Forever GI Bill](https://www.benefits.va.gov/gibill/forevergibill.asp) so that I am provided with complete and accurate information.

## Assumptions
- This Sub-EPIC includes all technical/functional implementation tasks for updating the Comparison Tool to support section 107 of the Colmery Act legislation.
- This work is dependent upon the completion of [#497](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/497)

## Acceptance Criteria
- All linked stories have been implemented and tested

## Supporting Artifacts
- This work is related to business requirements:
     - [#481](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/481)
     - [#483](https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool/issues/483)

## Original vets.gov-team epic: 
department-of-veterans-affairs/vets.gov-team#18790

**Comment by dneel-bah** [comment]
UI Enhancement was delivered to production on 02/20.
