### ISSUE TITLE
SOCKS access for Jim Ryan

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#40109]
### Your Name

Jim Ryan

### Your Email

jim.ryan@adhocteam.us

### Your Role

Information Architect

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC52KRC1ll6AyKIHmdjMLNdJdP/Z03RsKBS7KOoqwESK0Rw9Ff0kCJHR8AsabbPNMwYW4jA4Or8jzeFfrapMwJdzeuMyGFqJjGT6FAgmkf8FJWimFFrQ6ohuJQF96XZfsg77sfv5zvtjCGxreYk1ZBQi3Ebcm4EdwFU/y571LCX9Vl9o7TCk25DqtBUFjcnSDEr/tJGw0PEVeqDPC7w5lq0PjGubS2XkZ+/LY5H6xM6fdx3lZp2hdnfyMmyT2quuw7EHF74b9urAtDAN88/mIciyfnjThog26RqAH+69a5xP22wvSfSoI66SAdxxXGtQ/68OlpraXrFZuuteOQNCqXJSuHzicDqVlh9aqaGOjsIi2ZNpPYMjhZBRiN2pdOZ/CNg3t2oQ4KUfl0JPovz013jibVpTz57Fo2jrylGL1XDlVp8x5ZQVzVQLuA5ayGHR1GW1jB/hpSIYb/yTBU66Fl0QnK7cFsd1bLxamklj1yt5czdlNawV9jYHezC2MjVKGU= jamesryan@James-Ryan-MacBook-Pro.local

**Comment by oseasmoran73** [comment]
Hi @jimuhh 

The SSH key does not look accurate and correct. Can you please update using publish SSH?

**Comment by jimuhh** [comment]
@oseasmoran73 OK will do. Is my public SSH key the thing I generated in Github?

**Comment by jimuhh** [comment]
The same as my personal access token?

**Comment by oseasmoran73** [comment]
It's not the same as personal access token. If that is something that is being used in an application, I suggest rotating as those are meant to be private, not public.

Regarding public SSH, it is the same you associate your computer registered to Github. See this [doc](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) for additional details. You should not need to generate a new one, but rather just get one registered

**Comment by jimuhh** [comment]
I added a public SSH key above. LMK if I did that right.

**Comment by oseasmoran73** [comment]
![image](https://user-images.githubusercontent.com/10648480/163883086-03d97368-466f-412f-8bb0-b4121838271e.png)

It is not accurate. Please see the doc previously listed above

**Comment by rmtolmach** [comment]
@jimuhh I was looking at your edits and this one looks the most accurate, although the `ssh-ed` part doesn't look right. They usually start with `ssh-rsa AAAA...`
![image](https://user-images.githubusercontent.com/10993987/163885316-670ba284-bade-499b-bdcc-5fcfe444e199.png)

**Comment by jimuhh** [comment]
Thanks @rmtolmach -- It's encouraging to see that I might have accidentally done something almost right. 😉 . 
What should I do next to get it actually right?

**Comment by rmtolmach** [comment]
😆 @jimuhh Did you run `vtk socks setup` (explained in this documentation: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) during this process? If so, run this command to see your public ssh key: `cat ~/.ssh/id_rsa_vagov.pub` And then paste that in the **Public SSH Key** section of this issue.

**Comment by jimuhh** [comment]
`zsh: permission denied: /Users/jamesryan/.ssh/id_rsa_vagov.pub`

**Comment by rmtolmach** [comment]
Can you change your permission on that file? What does this command show? 
`ls -l ~/.ssh`

**Comment by jimuhh** [comment]
```
-rw-------  1 jamesryan  staff  6025 Apr 18 16:04 config
-rw-------  1 jamesryan  staff  2635 Apr 18 16:04 id_rsa_vagov
-rw-------  1 jamesryan  staff   592 Apr 18 16:04 id_rsa_vagov.pub
-rw-r--r--  1 jamesryan  staff  2418 Apr 18 16:04 known_hosts
```

**Comment by rmtolmach** [comment]
hm... that looks right 😕. I'll ping you on Slack to troubleshoot faster.

**Comment by rmtolmach** [comment]
@jimuhh Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
