### ISSUE TITLE
SOCKS access for [Jacob Uhteg]

### ISSUE THREAD

**Issue by Jake-Uhteg** [department-of-veterans-affairs/va.gov-team#40117]
### Your Name

Jacob Uhteg

### Your Email

jacob.uhteg@oddball.io

### Your Role

Test Engineer 

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjDNlr9OgilHGZ841WXeXeWRINdNj7dMswZNqW6hdyoOB1RmwdT9c616kT0CFLNF8l/uSJXl2qZo5qrXC1E2PVVxj4RW8OlJjgNz2uInTGTk5bKW8J1XWdCE/IWxLveK5mMQ5EgtmbEpuF2kF3Out9wrxCsZ/vbIXBaD6MDfaP9IoeP5IX2RPR/gu0h8jHdNp6uRbZ+b4+8zb7sCVO0XcbPgiTyE2ZkCgc0KXnDPw9vTuAh4qzCZZrmIbH4fGwd4mHzRpx131duKQz1V2PjBnOKpBSpnRMQQ6bnKMUEQCzDQSeSte1nF36Xgn65A9WNBaeCF1QL5mVud1DDKaW1ALIOTlyDkS6JT45E+snXAAJpMw+zy5NEFyNthDG4oI4k/7c0XzoE6/rjv8qa2VhkIDrFgOJ0XIQDeemDQ8EvjTrtTFEUwoxbM3rITpwcYIK5M4S8rgCRDsELVMxcDLzEo8iWNOIwzDTfodxAIb5xLKQ1YJ9OAGoukYLVHnwO9m2MHc= jake@Jakes-MacBook-Air.local

**Comment by jsgarmon** [comment]
Access granted. Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Feel free reach out on Slack via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) if you have any trouble.
