### ISSUE TITLE
Erica onboarding

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40124]
## Background

Welcome, Erica! We can use this ticket to track onboarding to the My VA team with the Account Experience Crew.

### Intro to team members

Please schedule a short chat with each of these folks (internal mtgs can come from Ad Hoc account):

- [x] Taylor Mitchell
- [x] Tom Harrison
- [x] Angela Agosto
- [x] Liz Lantz

### Meetings with Samara and AJ

- [x] Project overview call (we can have more than one of these if necessary)
- [x] PO/PM/APM roles and responsibilities call 

### Onboarding to ceremonies

- [x] Observe standup and be ready to run in sprint 73 (starting 5/12 due to PTO)
- [x] Observe sprint planning and then be ready to manage the next sprint planning session (5/18)
- [x] Observe grooming and then be ready to assist in the next grooming session (4/27)
- [x] Observe Team of Teams and then be ready to help create the next slide (4/26)

### Products/Projects

You'll talk about these more formally in your meeting(s) with Samara and AJ, but here are some helpful resources to review in the meantime:

#### My VA
Central product for the Authenticated Experience team
[My VA product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
- [Staging environment](https://staging.va.gov/)
- [Staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-passwords.md)

##### My VA Feature Work

**Benefit Payments & Debts**
_This is a new section on My VA_
- [Project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history#project-outline-add-paymentfinancial-info-to-the-my-va-dashboard)
- [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31611)
- GH label: my-va-dashboard
- [staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md)

**Health Care updates**
_Updates to the Health Care section of My VA - adding new facilities to the Cerner alert_
- [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39141) 
- GH label: my-va-cerner-alert

**My VA Audit**
_Audit of conditional states on My VA: We do not currently have documentation that hold all “if/then” conditional states of each section on My VA_
- [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38967)
- GH label: my-va-audit

**Onsite Notifications**
- [Project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md)
- [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30611)
- GH label: onsite-notifications
-  [staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Onsite-Notification.md)

**Comment by ericasauv09** [comment]
we are going to do roles and responsibilities call when I am back from OOO.
