### ISSUE TITLE
Comparison Tool updates for Colmery Act

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4014]
As a user of the Comparison Tool, I need the Comparison Tool on VA.gov to support the legislative changes for the [Forever GI Bill](https://www.benefits.va.gov/gibill/forevergibill.asp) so that I am provided with complete and accurate information.

## Assumptions
- This EPIC includes all technical/functional implementation tasks for updating the Comparison Tool to support the Colmery Act legislation.
- The stories linked to this EPIC have been agreed upon by reps from OIT, DSVA and EDU using the CCB process established by BAH team.

## Acceptance Criteria
- All linked stories have been implemented and tested

## Supporting Artifacts
- [Compare Tool - Colmery Impact Discovery.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3074019/Compare.Tool.-.Colmery.Impact.Discovery.xlsx)

**Comment by dneel-bah** [comment]
All issues addressable by the team have been resolved.  Closing this epic.
