### ISSUE TITLE
View of Platform Teams and VFS Teams sprint cadences

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#40144]
### Describe the problem

I've had to submit requests to the Public Websites team and the Sitewide Content Teams on a few occasions, and on one occasion I missed their planning meeting by a day and had to wait an entire sprint before my request could be considered.

Solving this problem will lead to better planning, coordination, and expectation setting and decrease missed deadlines or fire drills.

### Who will benefit

This will help VFS teams in their planning and timing for when to file an intake ticket with any other team they are dependent on.

### Describe your idea

It would be nice to be able to understand what the sprint cadences of Platform or VFS teams are, especially teams that provide a service. 
- Start and end days of sprints
- Sprint length
- Planning meetings

I don't think this needs to be overcomplicated, like trying to pull this programmatically from Github/Zenhub, but could come in the form of:

- A table documenting this on the Platform doc website 
- Each team setting their Slack channel room global message with this info
- Some sort of public calendar - Teams, Google, calendar on Platform website 

### Provide evidence

Personal experience from intake tickets being a black box and not knowing the schedule for when they might be considered aside from talking to the Project Manager or Product Manager.

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by shiragoodman** [comment]
@ianpsant thank you for sharing. My team is looking into this issue and we will follow up shortly.

**Comment by shiragoodman** [comment]
@andreahewitt-odd do we think a quick fix for this would be to just add sprint cadence to the VFS Team Roster under the teams tab? Or share are part of ToT? I feel like there's an easy solution here that can be quickly implemented.

**Comment by shiragoodman** [comment]
@jwoodman5 see my comment above. This is still on our teams backlog and I'm not sure how to move forward (or if we should at all).

**Comment by jwoodman5** [comment]
@shiragoodman Seems like something we should do and I'm sure there's a quick(ish) solution. I like the idea of adding this info somewhere that folks can go check when/if they need to, like the roster. But, can we talk about options when I return from PTO?

**Comment by shiragoodman** [comment]
@jwoodman5 resurfacing this. Not sure the request is something that's a Platform responsibility. Let me know if you'd like to discuss at our next 1 on 1.

**Comment by steel36** [comment]
Status check:  @shiragoodman @jwoodman5 Has there been any progress on this item? Is it still under consideration or still active in some capacity?

**Comment by shiragoodman** [comment]
@steel36 no movement on this. For what it's worth, I'm not sure this is something Platform should be accountable and/or responsible for. If VFS teams and Platform teams would find this information valuable, then it might be best to propose that teams add this info to their Team of Teams slide. @jwoodman5 any thoughts? Should we propose this?

**Comment by steel36** [comment]
Considering that all of Platform follows the same Sprint schedule, individual team reporting doesn't seem necessary. It seems like a published schedule on the Platform Docs site would be sufficient if this is something that is beneficial.  However, the examples given are VFS teams, and I don't know that their practices are in Platform's purview to augment.

**Comment by shiragoodman** [comment]
also, if it makes any difference, the person who submitted this request is no longer supporting a VFS team

**Comment by jwoodman5** [comment]
This is the only time/person I can recall this even coming up. So, with them out and this being almost 2 years old, I say we close it. I do agree with the points raised here if this becomes a problem and one worth solving.

**Comment by steel36** [comment]
Closing request.  Has only been raised once as an issue, and the consequence of no further action is at worst the potential to wait a sprint cycle before a team would consider a request.
