### ISSUE TITLE
Adding Randi Hecht to DSVA Slack

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40148]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

I'm not sure how to answer this. What do we usually do for contractors? I think "multi-channel" is correct rather than full member. Can you confirm?

- Please add r.hecht@bloomworks.digital as a multi-channel guest to these channels: 
vfs-all-teams
platform-collaboration-cycle
design
vagov-accessibility

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to? 

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
Randi is the new sitewide content team PM. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
wouldn't let me add to collab cycle but done

**Comment by bethpottsVADEPO** [comment]
@LEHigley I wasn't sure if I should have chosen multi-channel or full member. What's the difference? I think we need to switch her to be "full member" because we're having trouble inviting her to channels. It says, "only admins can add."

**Comment by bethpottsVADEPO** [comment]
@LEHigley I can't even get her into our content team channel.

**Comment by bethpottsVADEPO** [comment]
@LEHigley Sorry to bug you, but we need to get Randi up and running. Is there anyone else who you could point me to for help with this?

**Comment by LEHigley** [comment]
changed to full member
