### ISSUE TITLE
VAOS Staging: Preferred provider address not going through to HSRM

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#40156]
## What happened?
When a CC request is created with a preferred provider the address is not making it's way through to HSRM. 
We initially opened a Jira ticket to address this issues **VAOSR-3170** (https://issues.mobilehealth.va.gov/browse/VAOSR-3170), but on further analysis it was identified as Frontend issues. 
 
## Steps to Reproduce

1. Login to VAOS as a VAOS-service test user (eg:- jacobreid.r.iasimone@id.me)
2. Follow sets to create a CC request by making a provider selection 
3. Login to HSRM as a staff and access the newly created request under task list 

**Expected Results:** The newly created request should display the preferred provider information

**Actual Results:** System is transferring only the City, state and zipcode 

Please find attached the screenshot for reference.

![image](https://user-images.githubusercontent.com/69315717/164063126-725c134f-019b-437d-82b5-ae566ee08623.png)

**Comment by aarathi-poldass** [comment]
Here is Jason Willison's comment from the JIRA Ticket- https://issues.mobilehealth.va.gov/browse/VAOSR-3170.

After further investigating this bug through the vaos-test harness, we've determined that this issue is not a backend related bug. Submitted Appointment JSON to test harness: 

{
    "kind": "cc",
    "status": "proposed",
    "serviceType": "primaryCare",
    "reasonCode": {
        "coding": [
          {
            "code": "New Problem"
          }
        ]
      },
    "patientIcn": "1012845331V153043",
    "locationId": "984",
    "practitioners": [
      {
        "identifier": [
          {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "val"
          }
        ],
        "name": {
          "family": "wilson",
          "given": ["billy"]
        },
        "address": {
          "type": null,
          "line": [
            "123 Calhoun street"
          ],
          "city": "charleston",
          "state": "SC",
          "postalCode": "29414",
          "text": "123 Calhoun street,chareston,sc,29414"
        },
        "practiceName": "doc in box"
      }
    ],
    "requestedPeriods": [
      {
        "start": 1648291834.185814,
        "end": 1648896634.185814
      }
    ],
    "contact": {
      "telecom": [
        {
          "type": "phone",
          "value": "202-555-1234"
        }
      ]
    }
  } 

**Returned JSON from vaos-test harness:**

{
  "id": "91111",
  "identifier": [
    {
      "system": "http://med.va.gov/fhir/urn/vaos/hsrm/id",
      "value": "12132"
    }
  ],
  "kind": "cc",
  "status": "proposed",
  "serviceType": "primaryCare",
  "patientIcn": "1012845331V153043",
  "locationId": "984",
  "practitioners": [
    {
      "identifier": [
        {
          "system": "http://hl7.org/fhir/sid/us-npi",
          "value": "val"
        }
      ],
      "address": {
        "line": [
          "123 Calhoun street"
        ],
        "city": "charleston",
        "state": "SC",
        "postalCode": "29414",
        "text": "123 Calhoun street,charleston,SC,29414"
      }
    },
    {
      "identifier": [
        {
          "system": "http://hl7.org/fhir/sid/us-npi",
          "value": "npi: val"
        }
      ]
    }
  ],
  "created": "2022-03-29T19:44:00Z",
  "requestedPeriods": [
    {
      "start": "2022-03-26T10:50:34.185814Z"
    }
  ],
  "contact": {
    "telecom": [
      {
        "type": "phone",
        "value": "202-555-1234"
      },
      {
        "type": "email",
        "value": ""
      }
    ]
  },
  "preferredLocation": {
    "city": "",
    "state": ""
  },
  "comment": "",
  "preferredLanguage": "",
  "cancellable": true,
  "extension": {
    "ccLocation": {
      "address": {}
    },
    "ccRequestedCancellation": false,
    "hsrmTaskId": "12132"
  }
} 

You can see the address text coming through properly in the practioners.address.text field in our response from the vaos-test harness.

**Comment by marcynadeau** [comment]
@ldelacosta see comments above.  Aarathi and Thomas determined this bug is NOT back end related.  I am going to assign to you.

**Comment by ajmagdub** [comment]
The practitioners.address.line was not sent to VAOS Service; the params permit treated the address.line as a single string and not the array of strings. I modified the V2 Appointments Controller create params permit method to handle an array of address lines.

**Comment by ajmagdub** [comment]
@marcynadeau, this is ready for a retest.

**Comment by beth-wodzinski** [comment]
Tested and passed. The full provider address is now appearing in HSRM on the task detail:

preferredProviderInfo 1 careSiteAddress: 30 E APPLE ST STE 2200,DAYTON,OH,45409-2939

@ldelacosta this has been verified.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
