### ISSUE TITLE
[Design] Review & Sync with Design System on New Multi-Language Toggle Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40153]
## Resources
https://drive.google.com/file/d/1-mAhpBIr1mG5tR6eu8NPkQgRGfubLMQc/view?usp=sharing

## Tasks
- [ ] Write the experimental design ticket
  - We should complete [step 1 and 2 of this experimental design system process](https://design.va.gov/documentation/contributing-to-the-design-system)
- [ ] Review design w/ DS & Accessibility teams

**Comment by ytsaoca** [comment]
The experimental design ticket

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/919
