### ISSUE TITLE
GIBCT: Dashboard work with DSVA (12/9)

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4016]
Review Dashboard w Nedie
Underestand scope of what DSVA team can update before 12/20
Provide recs for updates

**Comment by amyknox** [comment]
Working version: Updates to dashboard- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/learn-and-improve/google-analytics/proposed-gibct-dashboard-enhancements-dec-2019.md
