### ISSUE TITLE
Blue ribbons

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#40161]
## What happened?

1. Accordions in "Calculate you benefits" section in the Institution details page have blue background:
![Screen Shot 2022-04-18 at 3.57.17 PM.png](https://images.zenhubusercontent.com/60e7390c5052ef146bcc412e/093a9c31-c8fd-415f-9d0f-23152a24f619)

2. On mobile view, the tabs "Search by name" and "Search by location" have blue background:
![Screen Shot 2022-04-18 at 4.14.00 PM.png](https://images.zenhubusercontent.com/60e7390c5052ef146bcc412e/add0db7f-c3ee-4c42-9915-3eb4838c2d32)

## Steps to Reproduce
1. Issue 1:
- Navigate to: https://staging.va.gov/education/gi-bill-comparison-tool/institution/13957113
- Inside the "Calculate your benefits" section, check the accordions background. 
2. Issue 2: 
- On a mobile, navigate to: https://staging.va.gov/education/gi-bill-comparison-tool/
- Check the background for both tabs "Search by name" and "Search by location"

## Desired behavior
- The accordions should have gray background
- Both tabs "Search by name" and Search by location" in mobile view, should have gray background

## Acceptance Criteria
- [ ] The accordions should have gray background
- [ ] Both tabs "Search by name" and Search by location" in mobile view, should have gray background

**Comment by dsrr47** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20833

**Comment by hallihocine** [comment]
Ticket has been validated in staging: blue ribbon (Blue Background) has been removed. The accordions and tabs have a gray background
1. Accordions: 
<img width="363" alt="Screen Shot 2022-04-19 at 2 24 45 PM" src="https://user-images.githubusercontent.com/86266024/164070817-0effa8ac-2c36-4037-9c6c-1b2aa149a6f2.png">
2. Tabs in mobile view
<img width="471" alt="Screen Shot 2022-04-19 at 2 27 54 PM" src="https://user-images.githubusercontent.com/86266024/164071226-ed678795-846b-477c-a025-a15f6ade317a.png">

**Comment by mrblanco1** [comment]
Defect fixed and QA passed on 4/19/2022.
