### ISSUE TITLE
FE - Notification Preferences - Research Front-end Implementation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40173]
### Background

We would like to document how the VA Profile - Notification Preferences feature was built on Profiles since we're continuing to add notifications and make improvements but we lack details on how this feature was created.

Having a better understanding of how the feature was set-up and documentation will be valuable as new people join the team. It will make future iterations more efficient by providing a clear understanding of what we need to do as we add new notification preferences.

### Tasks

- [x] Determine what information is sent to us by VA Notify and what, if anything is hard-coded on the page 

- For example, is the VA Profile sending us the groups (eg "Your health care), items (Appointment reminders) and channels (eg. text) or is some of this hard-coded on our end?

- The code to display the health care section conditionally is our code, but the other sections are not gated by any conditional logic

### Acceptance Criteria

- [x] Document the sources and logic in use today (include diagram if helpful) and post to Github folder (provide link)

**Comment by Samara-Strauss** [comment]
Just got off a call with VA Profile and I am wondering whether this was built very differently than I thought it was (the bad part about this having all happened on my maternity leave). From the call I was on, it sounded like there might be some stuff hard-coded, or some level of data translation (they send X, we display Y), instead of us just displaying stuff as-is based on the data we get from VA Profile. So, that's all to say I'm very curious what you find, and let's regroup after you've had a chance to review so we can determine what additional frontend work might be needed as this section grows to accommodate more preferences.

**Comment by mdewey** [comment]
Found full docs: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences. 

Will add a section there.

**Comment by mdewey** [comment]
@Samara-Strauss  I have created a short doc that breaks down whats happening: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/display-notes.md

Let's regroup to see what else we are looking for.

**Comment by Samara-Strauss** [comment]
@mdewey this is PERFECT! Thank you!! 

Based on your documentation, it's my understanding that if VA Profile sends us another Group and Item (Items 3A and 3B in your documentation), we shouldn't need to make any updates in our code, correct? The only things we'd need to update is if we added a new Channel (3C) or made other updates to the copy or items 1 & 2 on the page. Is this correct? I need to make sure I understand this so I'm planning work accordingly.

**Comment by mdewey** [comment]
Yes, that is correct! 

What updates are coming? I am can start to look specifically at that to get a better grasp of estimations.

**Comment by Samara-Strauss** [comment]
So the next change is that VA Profile (in partnership with VANotify) is in the process of adding a preference for payment deposit notifications. [Christina has mocked up what the new preference would look like](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/7yJKGDb), and from what I can tell, this shouldn't require any additional work from you. Is this correct?

**Comment by mdewey** [comment]
That looks correct!

**Comment by Samara-Strauss** [comment]
Great! Then we are good to close. Thank you SO much for documenting how the UI works!!
