### ISSUE TITLE
[Research] Present Different Scopes for Stephen

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#40170]
AC
- [ ] Create presentation by update the Mural
- [ ] Link the Mural to GitHub
- [ ] Meet with Stephen

Outcome with our looking for is:
- [ ] Defined MVP scope from Stephen

**Comment by niradatta1** [comment]
Presentation complete, all in agreement to proceed with the proposed MVP for telephone appointments work, focused on pre-check-in. Documented in this Mural. https://app.mural.co/t/civicactions3117/m/civicactions3117/1649777253301/29d43298818ec10044e3334ba33e950edc051be3?sender=niradatta0802

**Comment by niradatta1** [comment]
https://app.mural.co/t/civicactions3117/m/civicactions3117/1649777253301/29d43298818ec10044e3334ba33e950edc051be3?sender=niradatta0802
