### ISSUE TITLE
GIBCT: Final GitHub maintenance

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4017]
Cross check all docs are in the GH Repo. "All docs" includes but is not limited to 

Research Documents
- Discussion Guides
- Participant Notes
- Research Plan
- Readouts
Checkpoint deck
Discovery artifacts (PDF)
Prototype link
Sketch Files
Design decisions
Analytics

**Comment by amyknox** [comment]
Check here for more info https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/

**Comment by amyknox** [comment]
Include CT116 documents (in their correct location) as part of this story

**Comment by ccruzgra** [comment]
Uploaded design files to UI repo on 12/16.
Organized Design repo as content was missing and out of place after migration.

**Comment by amyknox** [comment]
@tmcmurdo - pls cross-check your local files & files you posted to our old vets.gov repo to ensure all GIBCT files are in our new va.gov repo

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/colmery-act-2019

Comment here when done.  I have to do the same and will close the ticket when we're both complete.

**Comment by amyknox** [comment]
- [ ]  Amy final effort
- [ ] Theresa final effort
- [ ]  Cindy final effort
