### ISSUE TITLE
Discovery Materials Review & Refresh

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4018]
As a UX practitioner, I want to review existing research and discovery materials so that I have a godo foundation for our continued GIBCT enhancements.

- [x] Research Review (Booz discovery research) - individual effort
- [x] Original EDU wish list (from John & Eddie) - collective effort
- [x] Review Enhancements list - collective
- [x] Review DSVA / EDU GIBCT Roadmap - collective
- [x] Document Key Points in GitHub Doc

Priorities for research review include
- Caution flags
- Yelp style reviews
- Ability for providers to update their own content
- Yellow Ribbon

**Comment by amyknox** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/research/gibct-2020q1-research-review.md

**Comment by amyknox** [comment]
- [ ] Theresa individual effort 
- [ ] Amy individual effort
