### ISSUE TITLE
SOCKS access for Samara Simmorins

### ISSUE THREAD

**Issue by SSimmorins** [department-of-veterans-affairs/va.gov-team#40189]
### Your Name

Samara Simmorins

### Your Email

ssimmorins@clarityinnovates.com

### Your Role

Tech Writer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4hEYiLFvWesRsRYjnbWhelrxJcr85zct13ZftNT6q6+iZLlytDKqjnHB1MIcKD4mu0/eAlj2VN8pNat1IAlc7xxkwk34JbqbX2/qsoY/FJb6SH5XJNyyIZf0gGZDf9VhWVpm6mzTXa8AJV+GjJ1ploqh+B92Gp1WQZ2/4jt8uGSvD949RbMRTjm3s6HrhqiQKviJqlVq50s0P7X96v6YWqU0v4+fDdO7oZFo9PyKCwggKiucn0VhRTni9Z3yRGj1cYQpx0+T/GMfvzYrZMC3FXPt7qJarfMnUdhqzz/UMRWPoWsdt6wBNPnp0AjCAU+QpRxM3rKDFImzQemG3Qn5vqz+JxixblyimYvGNJ1msGAMGd5lromdWv6Kz/A3g6avPfYKKDhcxnqiMCJNDsr1SbGXkWmuUgQDg+h1VpyLJJkFyLdyof7K3U04+27FqUena/RFTUhcFCousKC0f6OEOE+IEszcH4tOXIRiAP587QqxcvSLBbVq5rVt2dYtEXJU= ssimmorins@ssimmorins

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
