### ISSUE TITLE
[FE] Include Time Zone with Appointment Times in Check-in & Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40181]
## Need from CHIP
Ask CHIP to include the station timezone in appointment objects.

## User Story
We need to show the time zone with the appointment times.

## Acceptance Criteria
- Display the time zone for each appointment 

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Block on https://github.com/department-of-veterans-affairs/chip/issues/399
