### ISSUE TITLE
[BE] 10-10EZ: Discovery on errors in Staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#40183]

**Comment by lihanli** [comment]
the cause of the staging errors is the HCA API does not allow submissions from certain fake social security numbers. if i make submissions to the HCA API with certain users, the submissions always fail, but if i change only the SSN field, then it starts working. there are two users that i tested that don't get any SSN errors, we should only use those users when testing in staging: vets.gov.user+228@gmail.com (high disability) and vets.gov.user+11@gmail.com (low disability).
