### ISSUE TITLE
SOCKS access for [Jill Taylor]

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#40190]
### Your Name

Jill Taylor

### Your Email

jill.taylor@oddball.io

### Your Role

Product Technical Writer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTFRWNicHIAzd7U9POlWOVVfdRNh0Bskb8ujvcek9Hb9nG4KaCJM3fYzPWmWuUrY6XhfCnXTITYalgQ3A8MX3t6hAQtRXqcbyfMjx6wD9MC+ON3hqohKQv2RTEyKxRrpSpxf7FmAmASx0tSAVm0rPDP9QwujRneVRujOuZY965rWXC7pJR8mKaxyJKldSZT+sCmI2lidgUluJTzkfK5ozhfAjGf+zRWX8aWbxL7rwrGbWnTo2EIn7RV8tBc2TpvWx5tOk97JHWFJPYGUipPq2awn7A3piNcnomO+iAPFS+h9EljczeBNDu3vYf48cLseVgm+g/EyKoTmFzD8uCO6n4bG0rQnC4IzB9DSeKfyVy8omeEQDHjxK6bc/h9J6Q4eHS+OOL5W1DiEZnX6ZeHHGNiWgm4PFloZrbuPs1uWvBn7xPXazgCv32D1Lc4biPnjI8LuQh0vaaa/8eycIHqetM/q8sm8c8lRrOmN8mN03x21xP/UVvxl4kTCFBlR5rEeM= jtaylor@DESKTOP-E1VQ4Q2

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
