### ISSUE TITLE
School Certifying Officials (SCO) Migration

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4020]
## Purpose
As a SCO, I need the resources that I regularly use to be updated and migrated to VA.gov so that the resources are more useful and will be tools that I use in my day to day responsibilities.

## Assumptions
1. This Sub-EPIC includes all technical/functional implementation tasks for migrating and updating the SCO resource pages.

## Acceptance Criteria
1. All linked stories have been implemented and tested

## Supporting Artifacts
1. [190731 School Resource Page Redesign Requirements.docx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3636532/190731.School.Resource.Page.Redesign.Requirements.docx)

## Original Epic
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19505

**Comment by dneel-bah** [comment]
This functionality was completed and delivered in late 2019, closing this epic out as completed.
