### ISSUE TITLE
Final Layout Rated Disabilities to Include Accessibility Adjustments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4021]
## Story
As a screen reader user, I want to hear context of each piece of data presented so I may understand the context presented.

Also, as a member of the eBenefits team, I want to ensure that the features I produce are at the highest standard and leverage the most assistance to as many Veterans as possible when using a VA.gov in a browser.

## Considerations, Tasks, and Possible Solutions
- **Per Jennifer Strickland with the 508 Team**, when the screen reader reads the content for each of the disabilities there is nothing indicating what each of the items are. It would help the screen reader experience to have semantic context (such as a table or list items) with labels associated for each data point. The visual presentation of data within a grey box helps to convey the context of the data for sighted users. Screenreader users have no context for the data as it is read out.
  - For more context, please see [#3682](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3682) as well as this [example](https://www.w3schools.com/tags/tag_dt.asp).
  - Incorporate a semantic structure to provide context for the individual ratings, like this:
### Current code  
```HTML
<div class="vads-l-col--12 vads-u-background-color--gray-lightest vads-u-margin-top--0 vads-u-margin-bottom--2 vads-u-padding-top--1 vads-u-padding-bottom--2 vads-u-padding-x--2">
    <div class="vads-l-row">
        <div class="vads-l-col--9">
            <p class="vads-u-font-weight--bold vads-u-margin-top--0p25 vads-u-margin-bottom--0 vads-u-margin-x--0 vads-u-font-size--base">
                Allergies due to Hearing Loss
            </p>
        </div>
        <div class="vads-l-col--3">
            <p class="vads-u-font-weight--bold vads-u-font-size--lg vads-u-text-align--right vads-u-margin--0">
                10%
            </p>
        </div>
    </div>
    <div class="vads-l-row vads-u-margin-y--0p5">
        <div class="vads-l-col--12 vads-u-display--flex vads-u-flex-direction--column small-screen:vads-u-flex-direction--row">
            <p class="vads-u-margin--0">
                <i class="fas fa-medal vads-u-margin-right--0p5"></i>
                <span class="vads-u-font-weight--bold">
                    Service Connected
                </span>
            </p>
        </div>
    </div>
    <div class="vads-l-row">
        <div class="vads-l-col--12 medium-screen:vads-l-col--12">
            <p class="vads-u-margin--0">
                Effective date: 01/05/2012
            </p>
        </div>
    </div>
</div>
```
- [new mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL)
- `<div>` will go to `<dl>` tags
- order of info will be updated
- Individual Rating section has some styling 
- TCDR section: background, percentage moved

### Potential Solution
```HTML
<dl>
    <dt>Allergies due to Hearing Loss</dt>
    <dd><dfn>Disability Rating</dfn> 10%</dd>
    <dd><dfn>Origin of Disability</dfn> Service Connected</dd>
    <dd><dfn>Effective Date</dfn> 01/05/2012</dd>
</dl>
```
## Acceptance Criteria
- [x] Verify it's a string of data points with context in a screen reader
- [x] Latest mockup changes are implemented
- [x] Update any unit tests
- [ ] Update any e2e tests
- [x] remove `related to` text

**Comment by jason-gcio** [comment]
I am not sure if the description lists (`<dl>`), and subsequent description tags (`<dt>`, `<dd>`, etc) can use classes to keep them looking nice or if these description tags can simply wrap around the proper elements to make the screen reader a little happier.

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/11295
