### ISSUE TITLE
Research - Profile - Direct Deposit - Analytics

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40216]
## Background:

Gain better understanding of which type of users are encountering errors on Direct deposit feature.

## Task
- [x] Is there a difference between mobile and desktop users?

**Comment by andaleliz** [comment]
I looked into analytics and don't see anything that indicates this is a mobile vs desktop problem.  I was also able to see the desktop vs mobile data on the Medallia report where the comments came in, and the majority were from desktop users, so that debunks my theory.
