### ISSUE TITLE
Request for 1010EZ Redux Form data and Save In Progress production data for a specific veteran, date and time

### ISSUE THREAD

**Issue by lzapson** [department-of-veterans-affairs/va.gov-team#40223]
We are trying to troubleshoot and figure out an issue on the 1010EZ form that many veterans are having in production. We met with a Veteran on April 21 and have specific information and time when they recreated the issue. The issue showed that Redux form data was not available for veteran full name and date of birth.  

Using the following information can you provide Redux form data and Save In progress data for this specific incident. Please include veteran full name, veteran date of birth, spouse date of birth and marriage date. 

Following is some information about this incident to help you get the data we need. 
veteran IP address: 136.226.51.117
veteran first name: William
Spouse's date of birth: May 24, 1964
Date of marriage: November 11, 2011
save in progress - fetch(in UTC time on April 21) : GET https://api.va.gov/v0/in_progress_forms/1010ez [200] 14:02:24
This is the screen shot displayed in the browser:

![image](https://user-images.githubusercontent.com/32648173/164541752-a5110dc8-3961-4669-af59-eff620a115bc.png)

**Comment by zachclarity** [comment]
The issue started April 05 on some users.   It is unclear what has changed to their code.

**Comment by holdenhinkle** [comment]
Ticket author is no longer on the contract. Status of the issue noted in the description is unknown.
