### ISSUE TITLE
AWS access for Kevin Gin

### ISSUE THREAD

**Issue by kevingin9** [department-of-veterans-affairs/va.gov-team#40233]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kevin Gin

### Your Email

kevin.gin@adhocteam.us

### Your Team, Role, and Company

Senior Software Engineer, Ad Hoc

### Desired AWS Access

I need the same access as Krutarth Joshi (Team Koala, Lighthouse)

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
## For AWS Access
User: Kevin Gin
COR: Courtney Bethea
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Approvers will check with your VOR on your EQIP status.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS Access approved

**Comment by jbritt1** [comment]
@kevingin9, I do not see you in the DSVA Slack workspace... have you been through Platform Orientation?

**Comment by kevingin9** [comment]
@jbritt1 I have not been through any Platform Orientation. I requested an invite to the slack workspace but have not gotten an invite for it.

**Comment by jbritt1** [comment]
First-time login credentials provided to user via DSVA Slack workspace DM at this time.

**Comment by ianhundere** [comment]
asking for additional perms specifically the ability to run/maintain specific ECS clusters and RDS instances as per:
- https://dsva.slack.com/archives/CBU0KDSB1/p1668545596909119

**Comment by kevingin9** [comment]
Hi, I'm getting the following error when trying to use a script to connect to an ECS cluster:

An error occurred (AccessDeniedException) when calling the ListClusters operation: User: arn:aws-us-gov:iam::008577686731:user/Kevin.Gin is not authorized to perform: ecs:ListClusters on resource: * with an explicit deny in an identity-based policy

This is the script being used:

https://github.com/department-of-veterans-affairs/lighthouse-devops/blob/master/bin/ecs-ssm.sh


Beau ran into a similar issue when he was using this script (which has since been resolved for him):
https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/1657

So there is a difference in permissions between us that is allowing him to access but not me.

Thanks!

**Comment by kevingin9** [comment]
One more permission based on this error as well:

HTTP status code 400
User: arn:aws-us-gov:iam::008577686731:user/Kevin.Gin is not authorized to perform: ecs:RunTask on resource: arn:aws-us-gov:ecs:us-gov-west-1:008577686731:task-definition/dvp-dev-ecs-api-gateway:38 because no identity-based policy allows the ecs:RunTask action


ecs:RunTask

**Comment by td-usds** [comment]
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1319104037 
approved
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1320169859
approved
