### ISSUE TITLE
AWS access for Ovidio Reyna

### ISSUE THREAD

**Issue by ovidio** [department-of-veterans-affairs/va.gov-team#40235]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Ovidio Reyna

### Your Email

ovidio.reyna@adhocteam.us

### Your Team, Role, and Company

Liberty IT, Koala Team, Senior Software Engineer

### Desired AWS Access

Need the same access as Krutarth Joshi

### Access Expiration

ongoing

**Comment by oseasmoran73** [comment]
## For AWS Access

User: Ovidio Reyna
COR: Courtney Bethea
VOR: Liberty IT - Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Approvers will check with your VOR on your EQIP status.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS Access approved

**Comment by jbritt1** [comment]
@ovidio, I do not see in the DSVA Slack workspace which is where we typically pass first-time login credentials to AWS. Have you been through Platform Orientation?

**Comment by jbritt1** [comment]
Haven't made a pull request for this ticket yet, awaiting feedback from Ovidio and Kevin Gin on the Platform Orientation status before continuing.

**Comment by oseasmoran73** [comment]
Closing ticket due to inactivity. Please submit a new ticket
