### ISSUE TITLE
Auth-Profile - Personal Info Revisions - PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40249]
\[**Product Managers**: Open this ticket **at least 3 Sprints (6 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [VSA-QA process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

The Profile revisions for this update are as follows:

-  Separation of Personal info into 2 pages: Personal info and Contact info 
     - This introduces a new left-side navigation element
     - As well as a new page (Contact info)
     - New fields allowing for the ability to add and update a Preferred name and select Gender identity

 - Product/Feature Outline: \ [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md) 
- Product/Feature Epic: \ [ticket #31180](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31180)
- Product/Feature Copy deck(s): \[provide link, or type "In Design prototypes"] Design prototypes
- Product/Feature Design prototypes: \ [sketch](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/38FBF2AE-EAB2-495B-84A9-02A4F5E96932)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: @cgednalske 
Content/IA: @DanielleThierryUSDSVA 
Front-end: @adamwhitlock1 
Back-end: @tpharrison 
QA: @tlei123 

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by Samara-Strauss** [comment]
To be clear, we are asking for this QA sooner than than 6 weeks from now. We are aiming for this work to be ready for QA within the 5/4 - 5/17 sprint time frame, so 2 -3 weeks from now. Given that there are bunch of teams who've rolled off of VSA, I'm hoping it's possible to meet this request, but if not, let us know. Thanks!

**Comment by tlei123** [comment]
[**COMMENT-IN-PROGRESS**: Compiling Use Cases questions here, in prep for sync w/ team.  Will tag PM with completed questions-list by end of Monday (4/25)]

- [ ] 1. Is there a Copy deck?
- [ ] 2. **[Blank State](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md#test-cases-for-blank-state)**: Can a specific test-account be provided by 5/5?

**Comment by Samara-Strauss** [comment]
> Except for test-accts used during development, will all test-accounts' Preferred Name & Gender Identity start in blank-state on Staging?

Basically, all accounts are starting in a blank state, but yes, we'll need to provide you something for QA that we didn't use for our own testing during development.

**Comment by SKasimow** [comment]
Hi @cgednalske - can you check and lmk which version of the mock is final re: Tze's q2 in the comment above? Thx!

**Comment by SKasimow** [comment]
@tlei123 thanks Tze! Depending on how many more q's surface, happy to set up a call with you tomorrow to walk through :)

**Comment by Samara-Strauss** [comment]
I don't think we've had copy decks before, but I'm sure @cgednalske can figure out how to get you the copy you need (screenshots, etc) for QA.

**Comment by SKasimow** [comment]
@cgednalske - checked with Tze and the UI for the screens can serve as the source of truth for content. Would you check the links in the Use Case doc to make sure I am linking to final UI + content? I used a combination of screenshots when available, along with mocks in the sketch files when I couldn't provide the screenshot [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md)

(Also, assume for the mobile mock you provided we don't have one without sexual orientation and pronouns?)

**Comment by cgednalske** [comment]
@SKasimow sounds good - I will check out the links for the Use Cases and let you know if they're all accurate!

For the mobile mock, we do have that - sorry I didn't realize that was not the version with the initial fields. Here's the [link](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/v/q0mKLV/a/OmjMwxm) to the one without Pronouns and Sexual orientation

And because they're so easy to mix up, I want to confirm these general links for the Mobile and Desktop files without Pronouns  and Sexual orientation. They should have all the same fields that are included in the full versions.
[Desktop - Initial Fields - DOB, Preferred Name, GI](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/287E1E08-975D-4190-AD19-D4514223484C)
[Mobile - Initial Fields - DOB, Preferred Name, GI](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/BE56DBF8-B1BF-4A60-9379-DC9F2C5098BB)

**Comment by tlei123** [comment]
@SKasimow @cgednalske , thanks for starting replying to my questions so quickly!  

No need for sync-mtg.  I don't have any new questions, except maybe from updating/reconciling TestRail test-cases [which I doubt].

 I should have 1st round of TR test-cases updates done by end of this week.  We can sync closer to 5/4 to double-check on any further design/functionality changes for my final-round.

**Comment by cgednalske** [comment]
Thanks @tlei123 - happy to help! @SKasimow - just a few things for the Use Cases! Let me know if I can help with anything else.

For "User interacts with How to update your legal name component" -- Desktop goes to the Sketch file where the FAQ is closed. Does it need to be open like the Mobile link? If so, here's the [Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/4aqKkWz) for that.

For "User navigates to Contact information page" -- here's the [Sketch file](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/DPJ0VJJ) showing the whole page if you don't want to use the screenshots.

For the "Test cases for unsuccessful add" - below is a screenshot from staging for Preferred name. For Gender identity, I actually don't think the unsuccessful add case would ever happen because it's initially ok to leave it blank, and then once a selection has been made a radio button will always be checked. 
<img width="775" alt="Screen Shot 2022-04-25 at 9 19 47 PM" src="https://user-images.githubusercontent.com/79372956/165221005-782725c4-9768-4eba-b80c-028d967168f9.png">

**Comment by SKasimow** [comment]
@tlei123 Thanks Tze! Would you mind pinging me when test rail is updated - I have a ticket for that I am tracking.

**Comment by tlei123** [comment]
@SKasimow , yes, I'll ping you when 1st-round updates are ready.

**Comment by tlei123** [comment]
@SKasimow , yes, I'll ping you when 1st-round updates are ready.  Might be next Monday not this Friday &mdash; forgot I had scheduled my VA PIV appt for tmrw.

**Comment by tlei123** [comment]
@SKasimow @cgednalske @adamwhitlock1 @ddzz  ,  please **start reserving** your Staging test-users with this **[Personal information - Staging test-users](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/stg-rvw-test-users.md)** doc for reserving test-users Successful-add [which "burns" the test-users]. Add/update/delete table-row(s) as needed.

FYI, I've reserved test-user **297** to stay Blank-state, and a group of QA test-users (**285-296**) for Successful-add.

Feel free to ping me as needed with any further questions/concerns.

Thanks much!  :)

P.S.  @SKasimow , as we approach Staging Review, please also work w/ @shiragoodman to have the appropriate practice-area reviewers reserved their test-users.  We don't know right now who specifically will conduct those reviews.

**Comment by Samara-Strauss** [comment]
@tlei123 or @SKasimow -- can one of you consolidate [Tze's staging user test doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/stg-rvw-test-users.md) with [this staging user documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md) so it's all in one place? Thank you!

Also, @SKasimow -- [the main staging user doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md) should live [in the sensitive repo with all the other staging user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users). I should have caught this sooner. Can you please move this doc to the sensitive repo and then delete it in the public repo? Thanks!

**Comment by SKasimow** [comment]
@Samara-Strauss - sure!

Should I put the docs [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization) ?

**Comment by tlei123** [comment]
@ddzz , you mind if I recycle one of the Inactive users in TestRail for @SKasimow to access my PTEMS-Authd-Exp & PTEMS-Profile projects?  I got some test-cases & a test-plan to show her.

Please let me know.  Thanks much in advance!

**Comment by Samara-Strauss** [comment]
@SKasimow no, I linked to where the doc should go above --  [in the sensitive repo with all the other staging user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Administrative/vagov-users)

**Comment by SKasimow** [comment]
@Samara-Strauss - sorry my bad; I see it now

**Comment by SKasimow** [comment]
I consolidated [Tze's staging user test doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/stg-rvw-test-users.md) with [the main staging user documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md) in the sensitive repo [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts&use-cases-profile-revisions.md).

@tlei123 - I'd like to review this with you before I delete the docs and re-point to sensitive repo and also review Test Rail. I will look for some time for us to meet tomorrow.

**Comment by tlei123** [comment]
> I'd like to review this with you

@SKasimow , sure thing!  Invite accepted; see you _et al_ tmrw @ 3E.

**Comment by tlei123** [comment]
@SKasimow , I've just sent you an email with TestRail account/access instructions.  When you have a moment, please log in and reset your password.  **NOTE**: Please share credentials w/ any teammate who needs to access TR.

Once above is done, here are direct links to our TestRail test-plan/-cases:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3196)
- Test Cases:
  - [Personal info](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=161)
  - [Contact info](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4398)

**NOTE**: I have links in the plan & cases going to the _new_ [Test/Use Cases & Users doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile-personal-information.md) in va.gov-team-sensitive repo.

I've done my 1st-round updates to the test-cases.  We can do a final sync for any unplanned/interim changes once everything's ready on Staging.

**Comment by Samara-Strauss** [comment]
@SKasimow I reviewed the staging user test doc and have the following feedback:

- There needs to be a test to make sure we are able to retrieve information already save in the backend. We could use user 36 for this. The test is loading the profile and making sure previously saved information shows up.
- I see you have a test case for adding information for the first time, which is great. We also need a test case for making sure someone can edit and save new information after they have already saved a response.
- We need a test case for making sure opening the field and canceling works.
- **Test case for save error**: You might want to read through this section. The "test case" column mentions gender identity, but the "intended outcome" column mentions preferred name. I would think you would want two use cases here -- one for preferred name and one for gender identity -- to test this use case to make sure the right error copy shows up for each field.

Otherwise, this looks good, and thanks for combining your doc and Tze's doc into one.

**Comment by SKasimow** [comment]
@Samara-Strauss - thank you for reviewing this! I opened up a #40859 with your comments for tracking and will update the staging doc.

**Comment by tlei123** [comment]
Updates are QA-ready on Staging.  TR Test-cases updated.  Will start test-runs tmrw &mdash; QA-artifacts should be ready by late-Monday or early Tuesday.

**Comment by Samara-Strauss** [comment]
Great news!! Thanks, @tlei123!

**Comment by SKasimow** [comment]
@tlei123 - awesome news! Let us know how things go today!

**Comment by tlei123** [comment]
@SKasimow , all test-runs now completed.  

80% passed.  2 defects logged: #41419 & #41426.

Test plan and cases links are below:

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3196) (with Results)
- Test Cases:
  - [LOA1](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=149)
  - [Personal Information](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=161)
  - [Contact Information](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4398)

I'll add report links here once those are ready.  TestRail's having trouble right now generating them.

**Comment by tlei123** [comment]
[Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/331) now ready.  Summary (Defects) report still pending.

**Comment by tlei123** [comment]
FYI, @pjhill @ddzz , the Summary (Defects) report generation's _still_ showing in-progress after _almost 18 hours_ &mdash;  I started generating early this morning around 1AM ET.  Since the acquisition, I've noticed report generations taking much longer (from seconds to minutes), but this one setting a record.

Do we have any options to improve our hosted instance's performance?

I'll keep checking.  If you're curious, just go to https://dsvavsp.testrail.io/index.php?/projects/overview/4 &mdash; look for "Profile - Personal Info - Summary (Defects) 5/17/2022".

**Comment by pjhill** [comment]
> FYI, @pjhill @ddzz , the Summary (Defects) report generation's _still_ showing in-progress after _almost 18 hours_ &mdash;  I started generating early this morning around 1AM ET.  Since the acquisition, I've noticed report generations taking much longer (from seconds to minutes), but this one setting a record.
> 
> 
> 
> Do we have any options to improve our hosted instance's performance?
> 
> 
> 
> I'll keep checking.  If you're curious, just go to https://dsvavsp.testrail.io/index.php?/projects/overview/4 &mdash; look for "Profile - Personal Info - Summary (Defects) 5/17/2022".

I've noticed report generation taking quite some time as well. I'll lodge a complaint with Gurock and look into improved performance.

**Comment by tlei123** [comment]
> look into improved performance

@pjhill , thx much for the quick reply!  I'm wondering if super-long sessions might be a performance issue on their servers.  My TR session from last night is _still_ active &mdash; I JUST refreshed the page now and did not get redirected to Login.

**Comment by tlei123** [comment]
[Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/333) now ready.  QA-artifact links updated/added in [Staging Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40404).

**Comment by pjhill** [comment]
> > look into improved performance
> 
> @pjhill , thx much for the quick reply! I'm wondering if super-long sessions might be a performance issue on their servers. My TR session from last night is _still_ active — I JUST refreshed the page now and did not get redirected to Login.

@tlei123 , I created this [ticket ](https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/41739)for our team to investigate the slowness. Hopefully, we'll be able to get somebody to work this in the near future. That said, our complaints to Gurock about an endpoint being non-functional have not yet been resolved either.
