### ISSUE TITLE
SCO: Content Editor Guide -> GitHub Markdown file

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4024]
Create GitHub version of Content Editor Guide for easy access & updatinG

**Comment by ccruzgra** [comment]
Location of file: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/office-administration/vba/sco-migration/design/content/content-editor-guide.md

**Comment by ccruzgra** [comment]
@amyknox  All updates are in. This story can be closed.
