### ISSUE TITLE
SCO: Final GitHub maintenance

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4025]
Cross check all docs are in the GH Repo

- Research Documents
 - Discussion Guides
 - Participant Notes
 - Research Plan
 - Readouts
 - Checkpoint deck
- Discovery artifacts (PDF)
- Prototype link
- Sketch Files
- Design decisions
- Analytics

**Comment by ccruzgra** [comment]
Uploaded design files to UI repo on 12/16.

**Comment by amyknox** [comment]
@tmcmurdo - pls cross-check your local files & files you posted to our old vets.gov repo to ensure all SCO files are in our new va.gov repo
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/office-administration/vba/sco-migration
Comment here when done.  I have to do the same and will close the ticket when we're both complete.

**Comment by amyknox** [comment]
- [ ] Amy final effort
- [ ] Theresa final effort
- [ ] Cindy final effort
