### ISSUE TITLE
Content Review for Authenticated Experience Profile - Direct Deposit Updates

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#40253]
## Background
We're removing the conditional logic to display the direct deposit (DD) section of profile and instead will show it to all users regardless of if they are receiving payments or not.

In summer 2021, we blocked DD access for MHV and DS Logon users for security purposes (since they are not 2FA) and realized we didn't update the [changing DD content page](https://www.va.gov/change-direct-deposit/). We need to propose updates to that page too. 

## Items to review

1. Copy for alert we display to users in the direct deposit section of profile when we don't detect that they're receiving comp + pen, or edu payments.

Use warning alert w/ no heading. Copy:
Our records show that you’re not receiving payments for disability compensation, pension, or education benefits.   If you want to set up direct deposit for any of these payments from VA, please call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. 
![image](https://user-images.githubusercontent.com/55992116/164318700-f6239066-745d-4dae-b50c-9e29ca41c271.png)

2. Copy for sign in prompt under "[How to change your direct deposit information online" heading](https://www.va.gov/change-direct-deposit/#how-can-i-change-my-va-direct-). We need to update the note and alert.

**Note**
**Note:** You’ll need to sign in to VA.gov with ID.me or Login.gov to update your direct deposit information online. Once signed in, you’ll have to verify your identity and set up 2-factor authentication only if you haven’t done this already.

**Alert heading**
Sign in to change your direct deposit information online

**Alert body**
Sign in with your existing Login.gov or ID.me account. If you don’t have either of these accounts, you can create a free Login.gov or ID.me account now.

**Alert call to action button**
Sign in or create an account

![image](https://user-images.githubusercontent.com/55992116/164319133-d569b362-bcaf-407c-8533-9d83f093e2ad.png)

3. Copy for 2FA alert for users logged in with MHV or DS Logon. This will be the same alert we use in profile. Currently, the content page has text under the alert that is somewhat duplicative of what is in the alert (see screenshot). I think this is OK to keep because a person may have questions about something else on the page that isn't in the alert. I don't think it's harmful to repeat information about getting help..

**Note**
Remove note currently on content page.

**Alert heading**
You’ll need to verify your identity with Login.gov or ID.me to update your direct deposit information online.

**Alert body**
We require this to help protect your bank account information and prevent fraud. If you have a verified Login.gov or ID.me account, you can sign out and sign back in with that account. Then you can update your direct deposit information online. If you don't have one of these accounts, you can create one now.

[Create a login.gov account] (link)
[Create an ID.me account] (link)

**Note:** If you need help updating your direct deposit information, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. 

![image](https://user-images.githubusercontent.com/55992116/164319544-eac5eccf-ac7e-47c2-a110-3ba314cac2c7.png)

**Comment by andaleliz** [comment]
Hi @DanielleThierryUSDSVA , I'm creating this ticket to prep for office hours tomorrow, no need for you to do anything before then. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz! Following up on our slack conversation: I'll check out the first mockup (the new version) in Sketch this morning.

Here are some tweaks for the others. All phone #s and TTY should be in aria labels. 

## Copy for sign in prompt

[header] **Sign in to change your direct deposit information online**

Sign in with your existing **Login.gov** or **ID.me** account. Or create one of these accounts now. 

**Note:** If you sign in with a **DS Logon** or **My HealtheVet** account, you won't be able to change your direct deposit information.

[button] Sign in or create an account

## Copy for verify prompt

[header] **Verify your identity with Login.gov or ID.me to change your direct deposit information online**

Before we give you access to change your direct deposit information, we need to make sure you're you—and not someone pretending to be you. This helps us protect your bank account and prevent fraud.

**If you have a verified Login.gov or ID.me account,** sign out now. Then sign back in with that account to continue.

**If you don't have one of these accounts,** you can create one and verify your identity now.

[Create a Login.gov account] (link)
[Create an ID.me account] (link)

**Note:** If you need help to update your direct deposit information, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by andaleliz** [comment]
Thanks so much Danielle! Are there any changes you recommend on the new version of the Sketch mock-up?

**Comment by andaleliz** [comment]
Danielle and I reviewed the outstanding content via Sketch + Slack
