### ISSUE TITLE
SOCKS access for [Giang Nguyen]

### ISSUE THREAD

**Issue by giangnguyen2** [department-of-veterans-affairs/va.gov-team#40252]
### Your Name

Giang Nguyen

### Your Email

nguyen_giang@bah.com

### Your Role

Software Engineer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLmwdcrwZA6BlaGI0ogkLLeB7voix/q2LnetlxOzkEfKqAYpZ0b9zV7An/wzfhzJ1KuMzsnZ0NbixPBTmrtF3CNUZXCmgmdHgMs9cndRprHe0DfkIhr/ja8a/NPiTHeCqGfOgk6arxU5SUPx8rFhSURfDGOe5Buta8lnHO1d63XbUY5Wg9SEiO01lo5nTyadCOoYXvMl3AW7+GScyMQuZYH2SuSaAdWgnsevUUMrZxHSsqLV1Ksfxz6qnMMFLgqOdsM/hwLh7y0NgBxVA8iVnjEWVGFtd5urDL67FbRUMqn4sx1MuGnVcftHjQ3/ElgN2wwdmLVI2oy7VK2j91rjRYiSu8YzvBG1lMxb4RX5eEB9bD3SyyX9ZCdLtq3aKd4zR5XuUMwF7QPurt3oN2oXB5uzNqNYw4piNXNeS0lq7PPfthohwgLtFjEVRLiAHUtYzE+lk0BfXP0gtopeMh3oikHYMHAHfXMCYTlNorKEn2q9p0nkwPBgslpFT2feIpNB0= root@BAH5CG1387ZB2

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
