### ISSUE TITLE
Rename VSP-Identity (Github)

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#40255]
# Description
We've been asked to remove contract-specific language from our Github repositories.  We need to rename any VSP-Identity GH repos to something like VA-Identity.

**Comment by ianhundere** [comment]
i've searched a bit in `department-of-veterans-affairs` github org and i'm not finding anything except for this old archived repo by Julian; https://github.com/department-of-veterans-affairs/terraform-aws-vsp-identity

i'll keep looking 🤞

**Comment by ianhundere** [comment]
after further investigation, there are no repositories we own that need renaming. we also don't have admin access in GitHub, but the infrastructure team can handle that if necessary.
