### ISSUE TITLE
Adding Madhu Ramani to DSVA Slack

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#40260]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Request to add a new team member. Madhu is a developer who will support VA.gov Forms and other VA.gov pages AFS do not support. Dennis reports directly to Darla van Nieukerk - Darla.vanNieukerk@va.gov with OIT.

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Request to add a new team member. Madhu is a developer who will support VA.gov Forms and other VA.gov pages AFS do not support. Dennis reports directly to Darla van Nieukerk - Darla.vanNieukerk@va.gov with OIT.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add madhu.ramani@va.gov as a full member.

**Comment by mrblanco1** [comment]
Hi @LEHigley - Hope you are having a good day. I checked with Madhu and she informed me she did not receive an email letting her know she can now access slack. She checked her inbox, spam, and trash folders without any luck. Any idea how she will be informed she can now access slack and how?
Thank you for all your help! Much appreciated! Abe

**Comment by LEHigley** [comment]
sorry the email addresses throughout the request did not match--i did not see the address for Madhu when i looked/do not typically look at the "sample descriptions" section.

**Comment by LEHigley** [comment]
i also just resent the invite to her VA email to join slack

**Comment by mrblanco1** [comment]
> i also just resent the invite to her VA email to join slack

Thank you! She confirmed she received it.
