### ISSUE TITLE
Deploy test app to Utility

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#40264]
In order to discover and troubleshoot any issues with keycloak utility & login.gov prod, we need to deploy a test app to utility. The react test app should be good enough to test any issues. 

Motivation: SOCKS Proxy gets in the way of testing locally via the react test app -> keycloak utility

Done when, we have deployed the [React Test App](https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app) to utility.

**Comment by iriteshp** [comment]
We have deployed and tested react test utility.

URL: http://pst-amt-test-app-utility.vfs.va.gov/
