### ISSUE TITLE
SOCKS access for Kyle Crockett

### ISSUE THREAD

**Issue by kaipyroami** [department-of-veterans-affairs/va.gov-team#40289]
### Your Name

Kyle Crockett

### Your Email

kyle.crockett@oddball.io

### Your Role

Security Analyst 

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCy63jKnPKPtaH6oTGFu04kxnCHc8Wv2yujXBGtgUhT2w+N8dGMpNiqyf3Dh8Uu15SRetvIoL0x403RtBxufULstiYrmdogxvh1Gea1u88V4SP/v4Ei/EgBdwd2SO61jtvitF7NhRTv7o6cSsz8695p38WmCppc6FLMKtbPYZDp84Vy/6OF/apf4VjrXBPDAqhzJc9FkYnHJ/YC7AYCGl6yGmCvLEvsBaIQ1VWaKOK6KOAl2d+fgXhMdN48AoiQt5hzDKr+X+WIsJccEs8g40SHKV8q0KRUpdTSZ6Yea0/bCbLwXdpSDhzsSmOmj00Dewvph7lGlP/ItAHw0gYGRFi5fLNnYD1nnDbN8JGJAapjQP66jwehFk2I7SDH0XtKUEEgsvf3piYmAwez4ib8MsZs6tsn9kooN3IREv4NQiNajL7jFwkUQ7hD0zqrWAd44hpKTYHeZ3Xb8liSL9679caqosjNJQz0vefMxwoxYqYEhEej1+vLuDfnVm8crW9FLcE= kylecrockett@Kyles-MacBook-Air.local

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
