### ISSUE TITLE
GIBCT: Analytics Review & Report

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4029]
## Acceptance Criteria
Review Analytics
Identify Baseline Measures
Note findings in GH
Share data insights with stakeholders

## Supporting Information: 
Historical Dashboard from the era of Patrick: https://analytics.google.com/analytics/web/#/report-home/a50123418w177519031p184334251

NOTES FROM NEDIE
Self-serve links for Product documentation from Nedie:
a. Updated GIBCT Dashboard - I cleaned up the existing GIBCT dashboard and added a new widget to look at top form selection events and top "Learn More" events on Profile Pages
https://analytics.google.com/analytics/web/?authuser=0#/dashboard/PPUZ37Q0SOi_CiRCBb-HBg/a50123418w177519031p184334251/

b. Top Form Selection Events on Profile Pages - This report shows top events on the GI Bill profiles. You can then view occurrences of the new fields that we are tracking.
https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22GIBCT%20Form%20Change%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Fgi-bill-comparison-tool~2Fprofile~2F%22,0%5D%5D&explorer-table.rowCount=100/

## Original Issue: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20034

**Comment by amyknox** [comment]
Recommendations for dashboard: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/learn-and-improve/google-analytics/proposed-gibct-dashboard-enhancements-dec-2019.md

**Comment by amyknox** [comment]
Added notes for baseline measures https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/learn-and-improve/google-analytics/baseline-measures.md

Luke / EDU team will provide their input on questions they'd have that analytics may answer by COB 12/10

**Comment by amyknox** [comment]
No additional requests for tracking from Luke & team.
