### ISSUE TITLE
Train Second Engineer to Provide Production Support

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40299]
## AC
- Train a second engineer to provide production support

**Comment by loripusey** [comment]
@acrollet Sarah thought it would be a good idea to do this since you will be out 2 days next week.

**Comment by acrollet** [comment]
Info session scheduled for 4pm ET tomorrow - it'll be recorded for @brianseek to review later. @sarahknoppA6 @loripusey I added you as optional for awareness, feel free to attend if you're interested & available.

**Comment by acrollet** [comment]
Training was held with @dcgoodwin2112 @randomsync @brdunfield @kanchanasuriya @sarahknoppA6 @loripusey.

@brianseek I've forwarded you the recording info :-)
