### ISSUE TITLE
VET TEC Search results should display 10 results per page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4030]
The search results page for VET TEC programs displays all programs matching the search criteria. The search results are divided into pages that should display 10 programs per page. Currently, there are 30 programs per search results page. This bug is present in Production.

https://www.va.gov/gi-bill-comparison-tool/program-search

![searchresults](https://user-images.githubusercontent.com/45575003/69460347-ea1c9b00-0d41-11ea-9888-51959788a433.gif)

## PR: 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/512

Copied over from https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20022

**Comment by delli-gatti-michael** [comment]
Local testing for this issue is complete. The following PR is awaiting merge

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/512

**Comment by delli-gatti-michael** [comment]
Fix is now live in staging. Closing this issue
