### ISSUE TITLE
Create Platform Crew Leadership project board

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#40318]
## AC
- [x] Create project https://github.com/orgs/department-of-veterans-affairs/projects/623
- [x] Document board usage https://vfs.atlassian.net/wiki/spaces/AP/pages/2152300627/Platform+Crew+Leadership+Board
- [x] Adjust permissions as needed https://github.com/orgs/department-of-veterans-affairs/projects/623/settings/access
- [x] Announcement and demo at Platform Leads Sync
- [ ] Create issue template
- [ ] Automatically add labeled issues to board
- [ ] Share out finalized version at Platform Leads Sync

**Comment by andreahewitt-odd** [comment]
Duplicate
