### ISSUE TITLE
CT: Address RSpec/MultipleExpectations rubocop errors in GIDS

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4031]
As a developer, I need to address the RSpec/MultipleExpectations rubo-cop errors so that the codebase is more secure and stable.

## Assumptions:
1. These entire rubocop information is captured here: https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/.rubocop_todo.yml
2. Research to determine if fixing or turning off. 

## Acceptance Criteria:
1. There are no longer any of the following offenses:
     - RSpec/MultipleExpectations: # Offense count: 157

## Supporting Artifacts:
1. N/A

## Technical Notes:
For these stories:
     - in the .rubocop_todo.yml comment out the cop and indented lines below it
     - bundle exec rake ci
     - notice failures
     - Google the cop, there’s documentation with good vs bad examples
     - Fix the issues
     - bundle exec rake ci
     - notice failures are fixed
     - bundle exec rubocop --auto-gen-config
     - make PR

## PR: 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/508

## Original Issue
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19831

**Comment by delli-gatti-michael** [comment]
Local Testing complete

PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/508

**Comment by delli-gatti-michael** [comment]
The PR has been merged and this story has been re-verified in Master. Closing this issue.
