### ISSUE TITLE
[RI/GHA] Migrate Review Instance to Github Actions

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#40317]
## Who is the devops resource on your team?

@mydesignrocks 

## Description

CI and daily deploy are migrated from Jenkins to Github Actions for `vets-website` and `content-build`, with the exception of Review Instances. Currently there is an API call from Github Action to Jenkins to attach to the pull requests

[Slack](https://dsva.slack.com/archives/CQH357ZTP/p1650565329276119?thread_ts=1650554038.257489&cid=CQH357ZTP) thread

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mydesignrocks** [comment]
Based on the R&D so far and plan of action:
current state: jenkins —> ansible role of build/deploy —> docker compose —> RI
future state: GHA (which is in devops repo for all 3 repos) —> ansible role playbook —> docker compose —> RI  

Plan of action:
1. Convert Jenkins file into GitHub Action for review instances 
2. Do feasibility check (based on this: https://blog.marcnuri.com/triggering-github-actions-across-different-repositories) for running all three modules (vets-api, content-build, vets-website) from devops repository
3. Setup ansible controller from GitHub actions (leave it from ansible)
4. Run all three modules for vets-api, content-build, vest-website from ansible using existing playbook
5. Test and validate

**Comment by jhouse-solvd** [comment]
Based on #46783, this may be irrelevant or be de-prioritized in favor of a new solution. 

I suggest closing this issue if no longer needed. Adding the platform-cop-devops label so that the Platform DevOps Community of Practice can evaluate in the case that this is still desired.

**Comment by oseasmoran73** [comment]
Looks like it. Sync'd up with @CBonade privately via Slack and also found this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47575)

Closing
