### ISSUE TITLE
CT 116 Search results page - Pagination not working correctly

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4032]
## Description
When there are more than 30 programs to display on the VET TEC search results screen, the results are divided into pages. The pages can be navigated using the buttons at the bottom of the page (prev, 1, 2, next, etc...). There are 3 issues that exist with this functionality.

## Expected Behavior
1. The number of search results displayed at the top of the page is limited to only what is displayed on the current page (max of 30). This number should reflect the total number of search results.
2. When a user uses one of the filters, the page numbers persist. These numbers should only be present when additional pages of search results truly exist.
3. If a user applies filters and then attempts to go to another page of results, the filters are cleared. The applied filters should persist on all pages until removed by the user.
4. Google Analytics datalayer code for Provider filters has been updated in accordance with https://github.com/department-of-veterans-affairs/va.gov-team/issues/3048

## PRs
https://github.com/department-of-veterans-affairs/vets-website/pull/11154
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/499

## Supporting Documentation
![Screen Shot 2019-11-18 at 11.56.57 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e0b2d90f-9454-4f05-a321-e28621f0a190)

## Original Issue: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19992

---

![Screen Shot 2019-11-18 at 11.58.56 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ffaec811-e34d-42ac-a962-8fefb8b8ade3)

**Comment by delli-gatti-michael** [comment]
Local testing for this issue is complete. The Following PRs are awaiting merge:

- department-of-veterans-affairs/vets-website#11154
- department-of-veterans-affairs/gibct-data-service#499

**Comment by delli-gatti-michael** [comment]
Fix is now live in Staging. Closing this issue
