### ISSUE TITLE
Contact Center Review for Virtual Agent Chatbot Login and Claims

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#40321]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Virtual Agent Chatbot Beta allows users to interact with an AI bot to self-service and resolve their issues by asking questions and being presented content from VA.gov. This release will allow users to authenticate using VA.gov's login page and then ask about their open compensation claim status. It will also increase the percentage of people who can view the link to the chatbot on the Contact Us page to 50%

### Launch Date
Tentatively Monday, May 2, 2022

### Version Number
v2

### Product Guide
https://teams.microsoft.com/l/file/8765F675-4EA7-4775-8F74-0BF9334F49BD?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=docx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FOmnichannelExperience%2FShared%20Documents%2FVirtual%20Agent%2FVirtual.Agent.Chatbot.Product.Guide.docx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FOmnichannelExperience&serviceName=teams&threadId=19:8feb61bb36f24038a8b9635368e3d396@thread.skype&groupId=575bb298-dac9-4256-82cc-2598f3298ecc

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @ianpsant . Here's a draft of the product guide. I will wait for edits to be approved before making adjustments to the page numbers in the Table of Contents. Let me know if it works for you! 
[Virtual.Agent.Chatbot.Product.Guide_srt_04222022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8545216/Virtual.Agent.Chatbot.Product.Guide_srt_04222022.docx)

**Comment by ianpsant** [comment]
Hi Steve, Everything looks great. I've replied with notes on the comments
you left.

**Comment by starlow00** [comment]
Hi @ianpsant. Teams is saying I need permission to view the file at that link.

**Comment by ianpsant** [comment]
@starlow00 [Virtual.Agent.Chatbot.Product.Guide_ips_04252022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8557804/Virtual.Agent.Chatbot.Product.Guide_ips_04252022.docx)

**Comment by starlow00** [comment]
Sent draft to VEO for review (4/26).

**Comment by ianpsant** [comment]
@starlow00 Just curious, were there any further changes to the draft after I left my comments?

**Comment by starlow00** [comment]
Hi @ianpsant. Nothing. I flowed your descriptions right into the document.

**Comment by starlow00** [comment]
Oh, and VEO says it looks good, so everything is good if you want to close this ticket, @ianpsant.

**Comment by agmurphy** [comment]
@starlow00 @ianpsant  I'm having a hard time finding the non-commented document. Can someone link here? Is it on Teams?

**Comment by starlow00** [comment]
Yes, sorry about that, @agmurphy . Here it is:
[Virtual.Agent.Chatbot.Product.Guide_04252022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8587371/Virtual.Agent.Chatbot.Product.Guide_04252022.docx)

**Comment by agmurphy** [comment]
Thank you!

**Comment by starlow00** [comment]
PM and VEO approved. Closing.
