### ISSUE TITLE
[Platform Arch WG]: The Console UI will use the Catalog (a Core Feature of Backstage) to Provide Consistent Navigation, Inventory, and Dependency Tracking of VA Platform Assets

### ISSUE THREAD

**Issue by jchapin** [department-of-veterans-affairs/va.gov-team#40322]
### Topic

The Console UI will use the Catalog (a Core Feature of Backstage) to Provide Consistent Navigation, Inventory, and Dependency Tracking of VA Platform Assets

### Type

ADR

### Status

Ready

### Summary

The Console UI needs to have the following to meet the needs of the teams who will use it:

1. Some built-in ability to find or reference products, APIs, and infrastructure resources that compose The VA Platform
2. Consistent, easy navigation to the tools and top tasks associated with VFS applications
3. A accurate current inventory of VFS projects and Platform resources, as well as the teams that support them
4. A map of relationships (“dependencies”) between various products, APIs, and infrastructure, so teams can easily see which pieces would affect each another if their condition changed

Backstage—the software the Console UI is based upon—has a core/stock feature (the “catalog”) that we think will work well to fulfill all of the above needs. This catalog feature uses a system of interlinked “entities,” which can include products, APIs, pieces of infrastructure, and the teams that support these.

### Reference

https://vfs.atlassian.net/wiki/spaces/ECP/pages/2159247365/2022-04-15+The+Console+UI+will+use+the+Catalog+a+Core+Feature+of+Backstage+to+Provide+Consistent+Navigation+Inventory+and+Dependency+Tracking+of+VA+Platform+Assets

### Points of Contact

@jchapin, @lhelmer, @TPurple 

### Topic

- [ ] Frontend application
- [ ] Backend application
- [ ] Network
- [X] Other

**Comment by td-usds** [comment]
This appears to be a stale issue overtaken by events, can this be closed?
