### ISSUE TITLE
QA Feedback - Staging Review - My Education Benefits Team - My Education Benefits App

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#40328]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/39395

**Comments:**
- I ran into multiple failures when submitting the form. I was unable to determine if this was due to an issue with the feature itself or just a limitation of staging.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- The explanation field for incorrect service history is optional. Should this be required?

<img width="551" alt="Screen Shot 2022-04-21 at 3 11 53 PM" src="https://user-images.githubusercontent.com/3535749/164550480-1f5f27ab-4a88-45de-bf1d-e795b92b5f58.png">

- The PDF of the denial letter cannot be downloaded more than once. After the first download, the downloaded PDF is a zero byte file that cannot be opened. Determine if this is a limitation of staging or a valid issue.

- The pre-populated city for the address section contained trailing whitespace. This should be investigated to determine if this may cause issues.

<img width="489" alt="Screen Shot 2022-04-21 at 3 08 15 PM" src="https://user-images.githubusercontent.com/3535749/164550279-c9565abd-0a23-4d42-b590-9e610380ecc6.png">

**Consider:**
None

**Comment by cesaresantiago** [comment]
Determined that issue 1 "The explanation field for incorrect service history is optional. Should this be required?" is not an issue. this is optional per requirements.

**Comment by cesaresantiago** [comment]
For this issue:

"The pre-populated city for the address section contained trailing whitespace. This should be investigated to determine if this may cause issues."

We have investigated and found that the blank spaces are coming in straight from the VADIR API. For remediation, the DGIB team will add trimming code into mulesoft layer since we are not the only app affected by this. From MEB's perspective, there's nothing to be done.

**Comment by cesaresantiago** [comment]
I'll be closing these task as the 3 issues have been investigated and addressed. If the PDF issue resurfaces, we'll open a defect on our side.
