### ISSUE TITLE
SOCKS access for Aaron Young

### ISSUE THREAD

**Issue by TW-Aaron** [department-of-veterans-affairs/va.gov-team#40331]
### Your Name

Aaron Young

### Your Email

aaron.young@thoughtworks.com

### Your Role

Developer Consultant

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdMoD5Hqarp1MZcBYQypyufmO1Yeg52MdD/bRSQZR/yA01mqzcHHFYFvBVjeNxSy0diKn5A8E2nkC2pmAvTIKI+q2ONdsxBpg8H3z5TxTXinwOGgfnEDMYUi1eRrttYAxFHjOEWXxCeQvFnbE4toSWAa+0W1vgvW0wYPxuPMn03Q02ppQFolMIyDB7yDcJU7nnLr5n1ZOqRRdlE+kBUzDTrnZx/nqcnA02ckoBhZpKxjUr2FTmdqgbjjAQtwjOFyw8+qQEW8q+G1u+7B6ppYha6tITPpybWz6PYKuK1rHmzWx+kNae7hlOVq7o1xxlfMsVt1+Q3bCueRz22J3VOptmmOCV3h3JZdDl6U44TZ8Klj0Kq3ojYBcF/gF30NnpHGHCeKVSXbwOK9HJDLse+KEncBQEOZEHeef3noAzrTEfWNS/WBd+JT3rzmbktXKXtfm9ReFpfqjjTNyc1jV4fLwXFQX6jenPn9cdBT19G2qXYIx319MTYNIwAU+8gcUPyWc= aaronyoung@AaronsTW2019MBP

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
