### ISSUE TITLE
CT 116: Prod Flag Removal for Contact Info SCO Section

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4033]
As a developer, I need to remove the prod flag so that the SCO contact details are displayed on the VET TEC profile page.

## Assumptions
1. This functionality has been approved to go to Production as of [insert date].

## Acceptance Criteria: 
1. The functionality outlined in the following stories is now available in the Production Environment:
  - #19534
  - #19871 

## Original vets.gov-team issue:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19715

## Original PR(s)
These PRs are the original code that is currently behind a prod flag that is being lifted by this PR. 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/436
https://github.com/department-of-veterans-affairs/vets-website/pull/10690
department-of-veterans-affairs/vets-website#11124

**Comment by delli-gatti-michael** [comment]
Local testing for this story is complete. The following PR is awaiting merge:

https://github.com/department-of-veterans-affairs/vets-website/pull/11124

**Comment by zurbergram** [comment]
PR has been merged in

**Comment by delli-gatti-michael** [comment]
SCO information has not been uploaded to GIDS, so this story cannot yet be validated in production.

**Comment by delli-gatti-michael** [comment]
Validated in Production. Closing this issue

![Screen Shot 2020-01-22 at 7.43.03 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/99f93d32-7643-4692-893a-7c5b7ad9df8c)
