### ISSUE TITLE
CT 116: Add technical solution to account for duplicate program name at a single facility code

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4034]
As a Comparison Tool user, I need to be presented with a single program when the program data contains multiple programs with the same name at a single provider so that I am not confused by the Comparison Tool.

## Assumptions:
1. This work is completed behind a flag so that it is available in the staging environments and below.

## Acceptance Criteria:
1. When a provider has multiple programs with the same name, the program is only displayed once in the VET TEC search results.
2. When a provider has multiple programs with the same name, the program is only displayed once in the VET TEC profile page.
3. The provider filter count only reflects programs that are displayed in the search results.

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/502

## Supporting Artifacts:
1. N/A

## Original Issue: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20037

**Comment by delli-gatti-michael** [comment]
Local testing for this issue is complete. The following PR is awaiting merge:

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/502

**Comment by delli-gatti-michael** [comment]
Changes are live in master. Closing this issue
