### ISSUE TITLE
Quarterly survey synthesis and updating of mural boards

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40343]
## Issue Description
Quarterly survey synthesis and update to mural boards

---
## Tasks
- [x] Synthesize survey

## Acceptance Criteria
- [x] Customer Insights Mural updated

**Comment by tayism** [comment]
Synthesis workshop session scheduled for Monday, June 6th.

**Comment by tayism** [comment]
[Synthesis results:](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1654536055645/667377508f107d1b1c830167f2807d90d6c0eb18?sender=u9ea6bd3ca12795949b606150)
