### ISSUE TITLE
GIDS: Enhance the data file upload process.

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4035]
As a GIDS user, I would like to be able to upload files as they are received without having to manipulate them in any way so that extra steps are removed from my process.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Files that are delimited by the following values can be uploaded:
     - comma ,
     - pipe |
2. Files that have the following extensions can be uploaded:
     - .csv
     - .txt
3. Files that are exported use the default column separator specified for the CVS type in https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/config/csv_file_defaults.yml
4. When uploading a file with an opening double quote (") in a column but not a closing double quote (") an error message is displayed letting user know that there is bad data and it is related to missing closing double quote (")

## Supporting Artifacts:
1. N/A

## PR
department-of-veterans-affairs/gibct-data-service#504

## Original Issue: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20052

**Comment by delli-gatti-michael** [comment]
Local testing complete.

**Comment by delli-gatti-michael** [comment]
These changes are now live in master. Closing this issue
