### ISSUE TITLE
[Content styleguide] Content doesn’t align with style guidance in VA.gov content style guide. (05.08.1)

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40357]
#### VFS team name
DGIB - My Education Benefits

#### VFS product name
My Education Benefits

#### VFS feature name
My Education Benefits App

#### Point of Contact/Reviewers
Cheryl Evans (@CherylEvans) - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Content doesn’t align with style guidance in VA.gov content style guide.

### Issue Details
Application flow and screenshots, starting with page 4 and ALL applicable pages  > Step 1 of 7 > The sentence has incorrect verbiage.  It should read “Your application will be saved with every change.

### VA.gov Experience Standard
[Category Number 05, Issue Number 08](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

---

### Platform Recommendation
Replace “on” with “with”, on ALL applicable pages.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by cesaresantiago** [comment]
For MEB Reference: This is being tracked by MEB on Jira ticket SA-12763.

**Comment by cesaresantiago** [comment]
This text is set by the VA.gov's form system and changing it would affect all other VA.gov applications. This will not be addressed by MEB team. Please reach out to forms system team if it's still considered an issue.
