### ISSUE TITLE
[Overall user experience] Duplicate "Expand all" button - Design component or pattern in use isn't considered a best practice. (01.01.1)

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40368]
#### VFS team name
DGIB - My Education Benefits

#### VFS product name
My Education Benefits

#### VFS feature name
My Education Benefits App

#### Point of Contact/Reviewers
Brian DeConinck (@briandeconinck) - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Design component or pattern in use isn't considered a best practice.

### Issue Details
In Step 3 of 7: Service history, when a user has service history to display, there are two "Expand all" buttons that toggle open all of the accordions in the list. These buttons appear one after another in the tab order and have the same function.

This isn't strictly a violation of any rules, but it is a confusing pattern for keyboard and screen reader users. You would typically expect an expand/collapse toggle button to be followed immediately by the content that's being expanded or collapsed. Particularly for screen reader users who don't have the visual cues about changes on the page, a user may be confused about what's happening when they attempt to use one toggle and their next tab stop is a seemingly identical toggle.

**Note:** I think I might have also discovered a bug (not specifically an accessibility issue). When clicking the first "Expand all" button, both buttons' text changes to "Collapse all." But when clicking the second "Expand all" button, the first button doesn't change. 

### Link, screenshot or steps to recreate
1. Navigate to the My Education Benefits app on staging and log in as test user 39.
2. Complete the form up to step 3 of 7.
3. Press [tab] to move through the interactive elements on the page. Note that two consecutive tab stops have the same function.

<img width="458" alt="Duplicate expand/collapse toggles." src="https://user-images.githubusercontent.com/6844775/164743030-f17c509d-2510-41b5-9dbb-2756833925ef.png">

and

<img width="449" alt="expand-collapse-mismatch" src="https://user-images.githubusercontent.com/6844775/164743162-bd8805ff-6a81-4caa-8cc2-f4b03645176b.png">

### VA.gov Experience Standard
[Category Number 01, Issue Number 01](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
I would recommend removing the first "Expand all" button and keeping the second one.

The second one is part of the design system component and has a useful aria-label providing screen reader users some extra context about the interaction. It is also styled such that it's visually grouped with the accordions. The first one is styled to look like a link instead of a button (a little misleading to users) and isn't obviously grouped with the elements it controls.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by cesaresantiago** [comment]
Expand button issue tracked by MEB on JIRA ticket SA-12823

**Comment by cesaresantiago** [comment]
@briandeconinck : 

The two expand buttons you describe have 2 distinct functions. The key is that the service history can be a list of periods. In this example you see only one service period for Marine Corps reserve so that's why they look like they do the same.

The first "Expand All" link would expand each service history in the list. So, if you had Marine Corps service period, and a second Marine Corps Reserve service period, you would see them both expand.

The second expand button (the + sign) is meant to expand only that one Service Period. If there were 2 service periods you'd see a + sign next to each one and would open only that service period.

Still, I guess it does create confusion when only one service period shows up. What could be a good solution? An aria-label that clearly stated "Expand to see this service period's details?".

Thanks"

Cesar

**Comment by cesaresantiago** [comment]
The second expand button is working as designed. Closing issue.
