### ISSUE TITLE
SCO: Update "See past announcements" link

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4036]
As a developer, I need to update the "See past announcements" link so that it matches the update content and design.

## Assumptions:
1. The new link will redirect to the anchor tag on the linked page below the tabbed box.

## Acceptance Criteria:
1. The "See past announcements" link text is replaced with "See all announcements...".
2. The link links to the following page: https://www.benefits.va.gov/GIBILL/index.asp#Announcements 

## Supporting Artifacts:
1. N/A

## Original Issue
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20061

**Comment by sonntag-adam** [comment]
Testing passes QA. In staging. Closing Story.
