### ISSUE TITLE
FE Tech research: 10-10EZ Application status

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#40377]
## User story
As a Veteran I want to be able to check the status of my health care application

## Description
This is the next step for #39102. In which we need to give applicants the proper instructions to check their application status upon application submission. My VA no longer has the status and this copy will be removed from the confirmation page in #39299

## Acceptance Criteria
- [x] Enrollment status categories and display text are confirmed and/or updated [on the spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/enrollment-status-discovery/hc-enrollment-categories-and-display-text.xlsx)
- [x] Confirmation of where the status appears-does it only appear on the [authenticated introduction page](https://staging.va.gov/health-care/apply/application/introduction)?

**Comment by hdjustice** [comment]
New **[Enrollment Status folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Enrollment%20Status)** created.  I left all the 2-yr old discovery work in the Research folder.  Didn't see any need to move that over, however if you feel differently, let me know.  Thanks!
