### ISSUE TITLE
[Spike]: Rating System - Review and conduct an assessment on Rating System older code

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#40378]
## Issue Description
Review and conduct an assessment on Rating System older code (BAH)

---
## Tasks
Provide an assessment on whether the existing Rating System code in Staging can be resused, its state, etc.
Make sure to look at GIDS and see if everything is setup/connected
See if anything is hard coded
Please take notes on whether we will need to re-write anything

## Acceptance Criteria
Provide an assessment on whether the existing Rating System code in Staging can be resused, its state, etc.

## More Information:

Is the code easy to understand? Functionality?Is the code reusable?How hard would it be to make changes? i.e. updating the ratings from 5 stars to 4

This rating system was built by the previous contractor (BAH)

No idea how code or functionality is but seems to be in working conditions

The code is in staging only, behind a feature flag

There are two sections, one on top of the page, under the institutions name

and the other section is mid-page

Called "Veterans ratings"

Yes. Our goal is to make some minor modifications (new requirements from old ones)

But first we need to make sure the code is good and reusable.

Specially since it was not built by us.

My assumption is that we are going to be able to reuse it and just make minor changes to adopt new requirements.

Something else we need to evaluate please, is to make sure nothing is hard coded and code is "talking" to GIDS. We need to find out where this information is coming from and that is ready (or not) to be used.

**Comment by abuchanan83** [comment]
@mrblanco1 From my analysis the code seems to be written in a fashion to creating star ratings based on a data retrieved from GIDS. The logic is separated well and I believe is extendible if required. The core calculation is in a util method that can easily be updated without effecting multiple files. I believe we should be good to push the code through to prod and be able to maintain it moving forward.

**Comment by mrblanco1** [comment]
[https://app.zenhub.com/files/133843125/60b1f0a7-9c91-4726-887c-a07fc8aed85a/download](https://app.zenhub.com/files/133843125/60b1f0a7-9c91-4726-887c-a07fc8aed85a/download)

**Comment by mrblanco1** [comment]
Closing this spike as Anthony conducted thorough analysis on existing code (BAH) and decided it is fully functional and reusable.
Most requirements have been provided by EDU / JOe Preisser adn Brian Grubb. The last requirement we need from EDU is the formula they want to apply to this change.
