### ISSUE TITLE
CT: Research out of memory when uploading new WEAMS generated program file causes

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4037]
As a developer, I need to research the cause of the out of memory errors when uploading the new WEAMS program file so that a solution can be identified and implemented.

## Assumptions:
1. This is the error received:
> PG::OutOfMemory: ERROR: out of memory DETAIL: Failed on request of size 524288.
2. This occurs in the development, staging, and production environments.

## Acceptance Criteria:
1. A technical solution is identified and a plan for implementation is documented.

## Supporting Artifacts:
1. [WEAMS_SCHOOL_DATA_PGM_11182019.csv.zip](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3880168/WEAMS_SCHOOL_DATA_PGM_11182019.csv.zip)
2. http://sentry.vfs.va.gov/vets-gov/gi-bill-data-service-production/issues/84747/?query=is%3Aunresolved

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/509
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/507
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/501

## Additional info: 
pushing changes to dev and staging to use a configurable value for https://github.com/zdennis/activerecord-import#batching to begin testing on what an acceptable batch size is
The file in question was uploaded several times in GIDs production on 11/21/19 which cause site wide issues. The file upload causing site wide issues seems to have been resolved with https://github.com/department-of-veterans-affairs/devops/pull/5973 .

However there is still an issue currently with uploading the provided programs file that needs investigation. The file was again uploaded on 11/22/19 in GIDs production and caused a spike in CPU usage but did not cause site wide issues.

Suggested research path is to work with a group that has access to database logs for dev and staging GIDs environments and upload the file and view those logs to determine what issue is.

http://sentry.vfs.va.gov/share/issue/0ba25b591c944f16b70cc5449540c222/
http://sentry.vfs.va.gov/share/issue/228def4316f6493db0dac4d83ee83ac0/
http://sentry.vfs.va.gov/share/issue/ab8931d9140b4e0eb09dca857d778814/

## Original Issue: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20017

**Comment by zurbergram** [comment]
Testing with changes from related PRs, time in dev and staging for the approx. 400,000 row file is about 5 minutes

**Comment by delli-gatti-michael** [comment]
This had been validated in Staging. Closing this issue.
