### ISSUE TITLE
Analytics Implementation or QA Support for [Team Name - Feature Name]

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-team#40375]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Sitewide CMS team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - https://prod.cms.va.gov/help/search
    
- **When is the launch date?**
    - no hard deadline, but as soon as can be worked into a sprint would be great

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - The Sitewide CMS team is looking for data around terms being searched in the [CMS knowledgebase ](https://prod.cms.va.gov/help/search). 

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - We want to know what editors are searching for and how we might improve results to be more relevant. I am unsure if there is currently a data layer sending that to GA or if one will need to be implemented. A similar dashboard/report may already exist, and if so, would you point me in the right direction? Thank you.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jennaouellet** [comment]
Hi @msbtterswrth! We have configured the Google Analytics property, which can be found under the main GA account as "[GA4] VANotify".
Once you've added the analytics code to the application, pageviews will automatically collect for all pages. Below are the corresponding code snippets to initialize GA.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-SWFTGQGZM8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-SWFTGQGZM8');
</script>
```

 
Since this is an internal application, our team can assist with providing the GA4 event structure and best practices but ultimately additional tagging would be implemented on your end.
Events for all interactions should match GA4 standards. Others can be any event with any parameters, but should try to follow verb_noun or noun_verb structure like filter_accounts. Suggestions: link_click, button_click, table_sort.
We recommend using a React package like react-ga4 to initialize GA and push events. Events can be pushed in components in the application or via CustomEvent listeners for component library analytics a la vets-website.

**Comment by msbtterswrth** [comment]
Hi @jennaouellet, sorry for the delay in responding, I was out on vacation last week. 

We actually already have a GTM property (GTM-WQ3DLLB) loaded in drupal (where the KB lives) and are looking for a report on the search terms. Could we set up a call from an Insights engineer, myself, @kevwalsh and our PM @EWashb sometime this or next week perhaps?

**Comment by jennaouellet** [comment]
@msbtterswrth No worries! It would likely be best to discuss during office hours. The office hours are held on Tuesdays and Thursdays at 3:30ET at this [zoom link](https://us06web.zoom.us/my/platformanalytics?pwd=QlJGZVFncWhZV05XYjhDVENSWGJnQT09). If the timing doesn't work, let us know and we can find another time. Thanks!
