### ISSUE TITLE
[Enabler] Requirements gathering for Rating System

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#40376]
## Issue Description
This story is for AFS to gather detailed requirements from EDU/Joe Preisser's team.

---
## Tasks
- Mitch/Abe to set up a requirements meeting with education on week starting 4/25/2022 - Done
- Gather and document requirements - Done [see attached]
- Share requirements with the team - Done - Anthony is assigned to this feature
- Create an epic and break down the workload into small stories - Epic already exists from BAH - #29562

**Comment by mrblanco1** [comment]
RS [Rating System] "wireframe" from EDU:

[https://app.zenhub.com/files/133843125/5c7895b4-7461-450f-aaec-27a7c5e12c78/download](https://app.zenhub.com/files/133843125/5c7895b4-7461-450f-aaec-27a7c5e12c78/download)

**Comment by MitchLivingstone** [comment]
Waiting for Joe/Brian/Michael to provide finalized field headers, and formula to calculate the ratings.

**Comment by MitchLivingstone** [comment]
All Task are completed. Done / Closed on 06/16/2022
