### ISSUE TITLE
Clarify guidance around VFS usage of Platform team Slack channels

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#40374]
### Description

> Avoid direct messaging a Platform team member. Chatting openly in the [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) channel allows others to learn from the questions and answers discussed.

This also covers usage of Platform team channels, such as `#platform-infrastructure` or `#platform-release-tools`. Incoming communications from VFS teams should likewise be directed through `#vfs-platform-support`.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html

**Comment by taylojill** [comment]
@mchelen-gov Hello Mike. An information box containing your message already exists on the platform support page. Do you want us to rewrite the text in the blue information box to include individual team channels?

**Comment by mchelen-gov** [comment]
> @mchelen-gov Hello Mike. An information box containing your message already exists on the platform support page. Do you want us to rewrite the text in the blue information box to include individual team channels?

Hi Jill, yeah I think it would be helpful to mention that #vfs-platform-support should be used instead of Slack DMs *or* other Slack channels

**Comment by amygoldman** [comment]
5/20

- Mike Chelen requested that people who request support make the request through VFS-Platform-support instead of other channels
- not sure if this ticket belongs to us
- waiting for Liani to come back to discuss the next steps
  - Do we need to update the documentation to reflect this change? 
  - Should we socialize this through Slack?

**Comment by lianilychee** [comment]
Thanks, Amy!  This ticket still belongs to us.

Jill, can you rewrite the verbiage in the box to include instruction about other Slack channels?

**Comment by lianilychee** [comment]
Thanks, Amy! This ticket still belongs to us.

@taylojill , can you rewrite the verbiage in the box to include instruction about other Slack channels?

**Comment by amygoldman** [comment]
Friday 5/27:

- Jill and Amy will meet this afternoon to discuss

**Comment by amygoldman** [comment]
Suggestion:

> Avoid direct messaging a Platform team member or posting [questions/support requests] in Platform team channels. Chatting openly in the [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) channel allows others to learn from the questions and answers discussed.


* Might be able to just say “team channels”  and leave out “Platform” since we already specify “Platform team members”
* Is “questions” or “support requests” a better fit?
* If we go with “questions” we could say “asking” instead of “posting”

**Comment by laucon** [comment]
My thoughts:
1. The first sentence is a direct order and the second sentence is a general statement about how people do things. Can we change it so the second question is also a request or command? Instead if "chatting" we could say "we suggest you chat." I think it would be clearer and cleaner to have both sentences be a direct order or a gentle request. But this also requires us to decide, do we want to be telling people what to do or do we want to gentle request that they do things? Direct orders are clearer. But direct orders are also harsher. When people know what they need to do, it's clear. Bing bam boom. BUT, direct orders are also harsher. It indicated you're doing something wrong if you did it a different way.
2. Can we get rid of the passive language that the word "discussed" creates?

Original: Avoid direct messaging a Platform team member. Chatting openly in the [#vfs-platform-support] channel allows others to learn from the questions and answers discussed.
New version: Avoid direct messaging a Platform team member. We recommend you chat openly in the [#vfs-platform-support] channel to allow others to learn from the questions and answers you discuss.

**Comment by laucon** [comment]
Amy said that Mike requested that people who request support make the request through VFS-Platform-support instead of other channels. What kind of specific support are we talking about? Do we mean, when people outside the content team want to edit a platform article or create a new one? Do we mean when a person on a platform team, such as me, has an IT problem like they can't eject their PIV card reader (that was my problem 3 days ago.) I'm really confused what kind of support request we're talking about.

**Comment by laucon** [comment]
Also, if this entire article is telling them HOW to make a support request in the slack channel, I don't think we even want to mention the phrase, "or posting [questions/support requests] in Platform team channels" as part of that small note because it looks like the whole article is about that.

**Comment by laucon** [comment]
It sounds like we're telling them 2 different messages in 1 note, which is fine, but we need to specify that. First, we're saying not to direct message a team member. And second, we're saying to only use this one slack channel as opposed to any other slack channels. I think we need to break that up.

New Version: Only use the [#vfs-platform-support] channel to make Platform support requests. Don't use other slack channels for Platform support requests. Also, avoid direct messaging a Platform team member. Instead, chat openly in the [#vfs-platform-support] channel so others can learn from your discussions.

**Comment by laucon** [comment]
Alternatively, could we break this up into 2 notes?

Note 1: Avoid direct messaging a Platform team member. Instead, chat openly in the [#vfs-platform-support] channel to allow others to learn from your discussions.

Note 2: Only use the [#vfs-platform-support] channel to make Platform support requests. Don't use other slack channels for Platform support requests.

**Comment by lianilychee** [comment]
6/2 Thurs:
- I will do it today!

**Comment by amygoldman** [comment]
Here’s my updated suggestion:

**If you need help, post in #vfs-platform-support. Avoid direct messaging a Platform team member or asking questions in team channels.**

I think this works for the following reasons:
- It follows the plain language structure recommendation of "If you want to ___, do ____."
- It's direct without sounding harsh.
- It's easy to read/understand and only says what teams need to know.

This eliminates the part about other people learning from questions and answers, but I think that's okay. It's more context than an info box needs, it's wordier than an info box needs to be, and I don't think many Platform team members are reading that channel beyond getting their own questions answered. If we want to add that back in, it could be added to the text that comes before or after the info box.

**Comment by lianilychee** [comment]
6/5 Fri:
- amy to change verbiage in blue box, so that its' ready for tuesday deploy

**Comment by amygoldman** [comment]
Amy updated the verbiage in the blue box
