### ISSUE TITLE
SOCKS access for Clint Little

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#40381]
### Your Name

Clint Little

### Your Email

clint.little@oddball.io

### Your Role

Platform Eng Lead

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCw04H2a0J0p2DeR4/jNwhl4vG7MiR+EQmCXd86Ic0OfQ6W8kl21UC5I0ZY8Vx+4JZAO05DROwvkK8UH2Iu0D4ONPK76oJeNTqO/6yqDnpEEMI564jyo44Qbc/n/xb884McqnoVlKQM9yoxSdIpSAt8o1XJchvkEZLTq1ZlZFb3knpGRyWN7Cqffx0dYb0Ex4Eqy2yfuyCTmnXWnL7qV3ZEevSaoFKG/hz3BBcj/hxzz8tQQP86Uz4ERsvOzlMFC0KDz+ckJwZ/tgwTk76PHZDSuu6B2as/Ny5FxHt0YAJQhElZGFdFkIaxTcPG6zz3x8FJ6xwxndOiyAC7WmwvUTW+oyJRuYQe06Qb+r4XY3Y8rO/1IZc2xs0KxvdD+H+gGHOqJeAjq0fXw3HENUwlmMLG9sajVdygmvFLy5GbrH3mRGB9iZIHtyV63oc4TIr4kSae+UFfetcGE2c7JN38qMN1McDJeIn1muhdu5IuAPK37okp13K8qMij20FRSaIQrV8= clintlittle@Clints-MacBook-Pro-3.local

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
