### ISSUE TITLE
Update GIDS "latest production version" label

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#40387]
## Issue Description
This story is to update GIDS' current "latest production version" label to "Latest Live Version in Production" / "Latest Live Version in Staging".

---
## Tasks
update GIDS' current "latest production version" label to "Latest Live Version in Production" / "Latest Live Version in Staging".

## Acceptance Criteria
Validate GIDS' "latest production version" label is now "Latest Live Version in Production" / "Latest Live Version in Staging".
---

**Comment by PJart** [comment]
This is the branch, posted in the slack channel to get reviewed and merged

**Comment by hallihocine** [comment]
Ticket has been validated in staging: the label is updated to "Latest Live Version in Staging". Also, we updated the button from "Publish to Production" to "Publish to Staging" if the user is in staging. 
<img width="1749" alt="Screen Shot 2022-04-28 at 12 02 38 PM" src="https://user-images.githubusercontent.com/86266024/165797778-0cfb6e3d-f375-4e1a-ac13-cbc03290bdc0.png">

**Comment by hallihocine** [comment]
- Test Run in TestRail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3204&group_by=cases:section_id&group_order=asc&group_id=4407
- Test Steps: 
[Update GIDS label .xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8584713/Update.GIDS.label.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed on 5/05/2022.
