### ISSUE TITLE
GIDS: Refactor archiver to handle parent/child relationships.

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4038]
As a developer, I need to refactor the version archiver to handle data that is nested in a parent / child relationship so that additional enhancements can be made.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Archiver is configurable to archive tables with version id.
2. Archiver is configurable to archive tables modeled as children to tables with version id.
3. Archiver moves previous versioned data to configured corresponding archive tables.

## Supporting Artifacts:
1. N/A

##PRs

## Original Issue
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19876

**Comment by delli-gatti-michael** [comment]
Local testing complete and PR approved

PR:
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/550#pullrequestreview-352425918

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-11 at 9.51.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f62d44f5-9bed-4c8b-ba87-e87c9eaf0a21)

**Comment by sonntag-adam** [comment]
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/576

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-14 at 10.09.54 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/faae346d-8659-46b3-bb64-f12d78e05432)
##
![Screen Shot 2020-02-14 at 10.10.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0514bd39-096e-4eac-ba87-8092f1c47740)

**Comment by delli-gatti-michael** [comment]
Changes are live in Staging. Closing this issue
