### ISSUE TITLE
SOCKS access for Joseph Justice

### ISSUE THREAD

**Issue by joseph-justice** [department-of-veterans-affairs/va.gov-team#40389]
### Your Name

Joseph Justice

### Your Email

justice_joseph@bah.com

### Your Role

Associate Product Manager

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQzLKHGiNlW2uIe8jYij0vTG3uGBgio0kdX7a4qA8c9zAGEIlHgAiwerUKdFFF552X69vTAsqBVLDKpZtZU55NRQHTtZwAMWLGH7sweqQ3UndoNBI+3YAv8uTWuW7K0mjIUx/MyLiCuvP3qmafZ3ZSYKJM9yz5JtuNpy7fQLX0FCnOKGJ1x4J5uRT5tbgVpRe6IDT1RLkxvsvcYP7ZE6tvHTzkbj+KmAPqqbypltWMA2Z2SaoI8QlUaazQ9ZeCqznGF9r4at34MfmSN0Ck5+6bT4VUTmpMHzzUPMj4POlEWLJB2b+9pwx/vjvIdhscUaxqNeHFSEY240fD4JCm/WiAy6BGNE1kPBEKbwmHWUJNh2sHSaML0+3arine24l9/6rxjVCQWjXpLdHlsbK3ISAFE1FaYyaCqYJ1uC9URBDqoEA07wjLvknCj9Rlu1QcieDHh9M0CIXF/OCPY4U+B4qBp78VgqEmDhFb4WINrKDycPXE3+4FYnGKxMv69DE6gRc= joseph-justice@BAH5CG13902KJ

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
