### ISSUE TITLE
[Spike] for Military Details enhancement

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#40380]
## Issue Description
This spike is to conduct tech analysis and figure out what will require to complete Dev/QA work and define the amount of effort to update the Calculate your benefits filter section.

---
## Tasks
- Update the "Your military details" label (Mitch/Abe to get a recommendation or two from the Platform/Design team. Some ideas from EDU were "Your eduction details" or "Tell us about yourself")
- From the "Learning format and location" accordion, move "Will you be taking any classes in person? (Learn MOre) Yes - No to the "Your military details" accordion/section at the bottom.

## Acceptance Criteria
Provide detail on the amount of effort.
---

**Comment by af-manish** [comment]
Second bullet is completed, awaiting for Joe/education to provide final label tomorrow - Thurs 4/28/2022.

**Comment by mrblanco1** [comment]
Dev conducted and completed analysis and figured out what needs to be done in order to complete this work. Dev and QA will work on the actual story.
