### ISSUE TITLE
[Story] Military Details section enhancement

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#40384]
## Issue Description
This story is to enhance the "Calculate your benefits" filter section." in CT.

---
## Tasks
Update the "Your military details" label (Mitch/Abe to get a recommendation or two from the Platform/Design team. Some ideas from EDU were "Your eduction details" or "Tell us about yourself")
From the "Learning format and location" accordion, move "Will you be taking any classes in person? (Learn More) Yes - No to the "Your military details" accordion/section at the bottom.

## Acceptance Criteria
Update the "Your military details" label (Mitch/Abe to get a recommendation or two from the Platform/Design team. Some ideas from EDU were "Your eduction details" or "Tell us about yourself")
From the "Learning format and location" accordion, move "Will you be taking any classes in person? (Learn More) Yes - No to the "Your military details" accordion/section at the bottom.

**Comment by dan-brooking** [comment]
Not changing the label per EDU:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/90346049/166262390-e9cb7340-b184-4074-8e3b-44d275135bd5.png">

**Comment by hallihocine** [comment]
Ticket has been validated in staging: the filter question "Will you be taking any classes in person? (Learn More) Yes - No, is now moved from the "Learning format and location" accordion to  "Your military details" accordion.
<img width="315" alt="Screen Shot 2022-05-02 at 1 03 27 PM" src="https://user-images.githubusercontent.com/86266024/166294286-9dc1286f-2473-4c1d-8f57-15595153f364.png">

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3208&group_by=cases:section_id&group_order=asc&group_id=4407
- Test Steps: 
[Update the Calculate your benefits filter section.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8604940/Update.the.Calculate.your.benefits.filter.section.xlsx)

**Comment by MitchLivingstone** [comment]
QA and UAT passed on 05/02/2022.
