### ISSUE TITLE
[Design] Iterate Prototype Based on User Testing

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#404]
## User Story
As a Product Decision Maker, I need a clean usability tested dashboard so I can easily read the data that will be a part of my product workflow.

## Goal
Iterate on the Analytics Dashboard MVP Prototype based on findings from user testing.

## Acceptance Criteria
- [ ] Prototype design has been iterated
- [ ] Prototype has been shared with the team

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic**
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
To Do: Incorporate thresholds over time.

**Comment by joanneesteban** [comment]
The Product Health MVP has been iterated on [here](https://docs.google.com/spreadsheets/d/18CeQzeOxTwZ7Q1007ZUHgV12EtrjHawmgiVbsUtL8wY/edit?ts=5d261968#gid=786826286) with achievable design updates.

Adding the design blockers (access issues and thresholds over time) to https://github.com/department-of-veterans-affairs/va.gov-team/issues/458 and we will continue to add the additional relevant user findings to the MVP.

The first MVP iteration with user research input was created. Working on second iteration for accessibility and thresholds. Closing this issue.

**Comment by amycesal** [comment]
**Recommendation:** Consider allowing users to export the dashboard and individual charts as PNGs, JPGs, and PDFs.
> This functionality is basically possible in google sheets. Or with screenshots.
>
> <img width="577" alt="Screen Shot 2019-07-17 at 9 21 44 AM" src="https://user-images.githubusercontent.com/1656046/61378900-64a94b80-a874-11e9-9059-e73525effefc.png">

**Recommendation:** Rewrite labels and tooltips in plain language.
> I re-wrote all the column headers to be more plain language. The tooltips are still a little verbose, but I think it's helpful to have a more technical definition there. 
>
> <img width="601" alt="Screen Shot 2019-07-17 at 9 23 55 AM" src="https://user-images.githubusercontent.com/1656046/61379018-a934e700-a874-11e9-847c-c278ce907513.png">

**Recommendation:** Place Support Contact information in a visible and consistent place.
> This is at the top of every page now.
>
> <img width="501" alt="Screen Shot 2019-07-17 at 9 24 36 AM" src="https://user-images.githubusercontent.com/1656046/61379076-ccf82d00-a874-11e9-9b2b-66c9231e7f85.png">


**Recommendation:** Consider combining the icons + color and color-gradient versions so that the dashboards are accessible.
> This is not possible with google sheets. The conditional formatting tool only allows for color, not icon like Excel. It could be done manually (which is what was done for the prototype) but that sort of defeats the purpose of having an automatically generated dashboard. 

**Missing information:** 
- Traffic spikes
 > working on adding

- Bounce rates
 > working on adding

- 3rd party service statuses
 > not possible with the data that we have

- Last updated
> last deploy covers this 

- Custom date ranges
> not really possible in google sheets. This would need to be built in a dashboarding tool for this functionality to be possible. 

- Comparisons over time
> stretch goal (https://github.com/department-of-veterans-affairs/va.gov-team/issues/560)

- Usage (seasonal conversion rate, call center vs. usage)
> stretch goal (https://github.com/department-of-veterans-affairs/va.gov-team/issues/560)

- Ability to add a note that an issue has been addressed
> This was relevant when we had realtime metrics. However, that information better lives with the triage and development teams, rather than in a dashboard with historical data. 

- GI Bill Comparison tool
> I was confusing the comparison tool with the feedback tool. We still need to add the comparison tool.
