### ISSUE TITLE
GIDS: Identify OPE/IPED information that matches WEAMS/Crosswalk information.

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4041]
@dneel-bah commented on [Fri Dec 06 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20065)

As an EDU team member, I need the ability to review Dept of Education OPE/IPED information that matches WEAMS/Crosswalk information so that I can identify any data discrepancies and resolve them.

## Assumptions:
1. The crosswalk data can be linked to weams by facility code.
2. Extension campuses can be excluded from the query results.

## Acceptance Criteria:
1. If there is an exact match (non-case sensitive) in the "unitd" OR "opeid" of the "IpedsHD" file and the "iped" OR "ope" of the "Crosswalk" file the following information is displayed:
- Weams Institution Name
- Weams Facility Code
- Weams ipeds
- Weams ope
- IpedsHd unitid
- IpedsHd opeid
- Crosswalk ipeds
- Crosswalk ope

2. If there is an exact match (non-case sensitive) in the "unitd" OR "opeid" of the "IpedsHD" file and the "iped" OR "ope" of the "WEAMS" file the following information is displayed:
- Weams Institution Name
- Weams Facility Code
- Weams ipeds
- Weams ope
- IpedsHd unitid
- IpedsHd opeid
- Crosswalk ipeds
- Crosswalk ope

3. This information is displayed on a new page within GIDS. 

## Supporting Artifacts:
1. [Sample Crosswalk Display.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3932824/Sample.Crosswalk.Display.xlsx)

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/522
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/523

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `bah-crosswalk`

**Comment by delli-gatti-michael** [comment]
local testing is complete

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging
