### ISSUE TITLE
Approval to add pre-commit hooks to vets-website

### ISSUE THREAD

**Issue by ncbui** [department-of-veterans-affairs/va.gov-team#40428]
Hi, we’re looking to add a pre-commit hook for secret detection to our app, dhp-connected-devices, on vets-website. Our app does not make external API calls, but does send and receive from vets-api, which makes the external calls. We’re trying to take pre-emptive steps to prevent potential breaches.

We're considering two options:
(1) Using ESLint plugins that could also check for secrets [eslint-plugin-no-credentials](https://www.npmjs.com/package/eslint-plugin-no-credentials) and [eslint-plugin-no-secrets](https://www.npmjs.com/package/eslint-plugin-no-secrets). This is installed at the app-level and may affect other apps on va.gov. 
(2) [Talisman](https://github.com/thoughtworks/talisman). This is installed locally and should not affect other apps.

Our team is fairly new to developing for VA.gov, so we wanted to check to see if approval will be needed.

**Comment by mchaffee-tw** [comment]
Hi -

The DHP Team is focusing on a different delivery target in the near term.  We'll close this ticket for now, and revisit the matter if/when we have additional VA.gov work to push in the future.

Thanks!
