### ISSUE TITLE
GIDS: Identify OPE/IPED information that doesn't have a match in WEAMS/Crosswalk

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4042]
@dneel-bah commented on [Fri Dec 06 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20066)

As an EDU team member, I need the ability to review Dept of Education OPE/IPED information that matches WEAMS/Crosswalk information so that I can identify any data discrepancies and resolve them.

## Assumptions:
1. AC 1 is displayed on a new page within GIDS.

## Acceptance Criteria:
1. If there is no match (non-case sensitive) in the "unitid" OR "opeid" of the "IpedsHD" file and the "iped" OR "ope" of the "Crosswalk" file the following information is displayed:
- IpedsHd instnm
- IpedsHd unitid
- IpedsHd opeid

## Supporting Artifacts:
1. [Sample Crosswalk Display.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3932824/Sample.Crosswalk.Display.xlsx)

## PRs
department-of-veterans-affairs/gibct-data-service#531
department-of-veterans-affairs/gibct-data-service#530

**Comment by dmccurdybah** [comment]
This can be tested on the gibct-data-service branch `bah-ipeds-issues`

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/530

**Comment by delli-gatti-michael** [comment]
Test IPED File attached
[IpedsHd_test.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4064931/IpedsHd_test.txt)

**Comment by delli-gatti-michael** [comment]
This functionality is now in Staging. Closing this issue
