### ISSUE TITLE
Update documentation references of default branches for vets-website and content-build

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#40438]
## Description
There are places in our documentation that reference the default branch `master` directly. All `master` references for `vets-website` and `content-build` should be updated to `main`.

Documentation locations:
- [Frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) (can be edited [here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/687931428/Frontend+developer+documentation))
- [VA.gov | Client application documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/) (can be edited [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/documentation))
- [VA.gov Team Repository](https://github.com/department-of-veterans-affairs/va.gov-team)

## Definition of done
- [ ] All `vets-website` default branch references are to `main`.
- [ ] All `content-build` default branch references are to `main`.

**Comment by it-harrison** [comment]
[spreadsheet](https://docs.google.com/spreadsheets/d/1tyRIrWD5GL416h4biF6WhDFxGpZiahEX4GTa4EDrAtI/edit#gid=0) with the changes in Frontend developer documentation
branch with changes for `va.gov-team`: `update-documentation-refs-master-to-main`
branch with changes for `veteran-facing-services-tools`: `update-documentation-refs-master-to-main`
