### ISSUE TITLE
GIDS: Cleanup archiver versioning code

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4043]
@dneel-bah commented on [Tue Oct 29 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19879)

As a developer, I need to remove any remaining archiver versioning dead code that has not been replaced by the updated versioner.

## Assumptions:
1. The following stories have been completed:
     - #4064
     - #4037
     - #4063
     - #4044

## Acceptance Criteria:
1. All dead versioning archiver code is removed.

## Supporting Artifacts:
1. N/A

**Comment by delli-gatti-michael** [comment]
Local testing complete and PR approved

PR:
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/550#pullrequestreview-352425918

**Comment by delli-gatti-michael** [comment]
New PR:
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/581

**Comment by sonntag-adam** [comment]
In staging. Closing story.
