### ISSUE TITLE
[DISCOVERY] How do we do Authentication for users accessing Console-Services-API

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#40447]
## AC

API is secured by an authentication method.

- [x] Documentation on how we plan to facilitate API authentication for clients is created.
- [ ] Documentation for Github Oauth setup
- [ ] Document for Keycloak Oauth setup with Github integration

Possible Solution:
- Allow users to auth with keycloak through API and pass token back to use.
- API authentication must allow for users to hit Argo API and GitHub API without having to pass a different token. 
- Once an authentication method has been determined, update documentation.

## How will we know we are done?

We have determined a solution to implement

**Comment by ericboehs** [comment]
[Related PR](https://github.com/department-of-veterans-affairs/platform-console-api/pull/274)
