### ISSUE TITLE
GIDS: Add parent institution relationship to SCO & Program data

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4044]
@dneel-bah commented on [Tue Oct 29 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19878)

As a developer, I need to add a parent relationship to the SCO and Program data so that the database is more normalized.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Has_many relationship is established from institution to institution_program.
2. Has_many relationship is established from institution to versioned_school_certifying_official.
3. Archiver is configured to archive institution_program and versioned_school_certifying_official data.

## Supporting Artifacts:
1. 

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/527

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
In staging. Closing story.
