### ISSUE TITLE
AWS access for Brooks Johnson

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#40440]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Brooks Johnson

### Your Email

brooks@adhocteam.us

### Your Team, Role, and Company

Software Engineer, Ad Hoc

### Desired AWS Access

I need read and write access to S3 buckets for design.va.gov and its environments. The same permissions that [I originally had](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16283).

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
@jsgarmon re-enabled your account and I see that you have logged on today ✅ ✅ 

Slack thread for tracking purposes: https://dsva.slack.com/archives/CBU0KDSB1/p1650904443874609

**Comment by jsgarmon** [comment]
user has AWS access re-enabled, requesting access to a prod bucket.

**Comment by bkjohnson** [comment]
I'm requesting access to dev and staging buckets as well:

- staging-design.va.gov
- dev-design.va.gov
- design.va.gov

**Comment by rmtolmach** [comment]
@bkjohnson You should be good now 🎉  These are the groups you belong to:
![image](https://user-images.githubusercontent.com/10993987/165180260-3ee7fb1a-b6e8-41e9-b71a-8798f476b661.png)

**Comment by bkjohnson** [comment]
Here's what I see when I try to look at an S3 bucket:

![Insufficient permissions to list objects](https://user-images.githubusercontent.com/2008881/165187920-74c7e3b0-cb78-482e-a6aa-644753aba08e.png)

**Comment by oseasmoran73** [comment]
Please refer to our amazing gif above for future references. Glad its working though! Closing ticket
