### ISSUE TITLE
PM team to f/u on HEC Legal review

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#40455]
- [x] f/u with Tarsha regarding status of legal review

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/e3ad181a-9bb0-4c5a-b831-88f879f168ea)

**Comment by tameracorson** [comment]
Regulation that applies to this https://www.govregs.com/regulations/26/1.6055-2

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/ee2a739f-cdfb-4f9d-9193-9f76ac4ff408/download](https://app.zenhub.com/files/133843125/ee2a739f-cdfb-4f9d-9193-9f76ac4ff408/download)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/c163d9be-7f0e-4d72-af93-edb73ba417a1/download](https://app.zenhub.com/files/133843125/c163d9be-7f0e-4d72-af93-edb73ba417a1/download)

**Comment by tameracorson** [comment]
@tmulrooney-va Please advise as to next steps on 1095-B.   
1) I agree with Chris that we should be cleared to launch since opt in is a post MVP build.   If so what / how do we launch?  
2) Do we have to wait on Spanish translation to launch MVP?
3) Do you need us to recreate the opt-in email / letter to include the legalese from both the IRS document and the requirements from government regulations?
4) Do we need to attach these regulations to the opt-in ticket for VA Profile to ensure legal compliance on first build of opt-in?
5) Are we building way finding for the product or will that be profile?

**Comment by tmulrooney-va** [comment]
1. We cannot launch until we receive confirmation back from Tarsha.
2. We are waiting on the spanish translation
3. I don't think we need to add regulations
4. No need to add regulations until we hear from Tarsha how to move forward.
5. What do you mean by wayfinding?  We plan to send out an announcement that the 1095-B form is available online after the product has launched and it is closer to tax season.

**Comment by tameracorson** [comment]
@tmulrooney-va How do Veterans find the page now that it is built, does it rise to the level of navigation or content within resources.   We leared that records was where Veterans would look for it, but there is no way-finding to the site (Post MVP?)  Dark launch intentional to finish testing accessibility; eventually do we want to explore directing?

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/314bb549-3c3f-4c16-b21d-f0aa3b73aebd)
