### ISSUE TITLE
Auth- Profile | Personal Info Revisions | Release Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40467]
# Release Plan 

### Planning:

- **Desired date range or test duration:**  early June 2022
- **Desired number of users:**  Recruiting 12 participants with a target of completing 6 sessions
- **How you'll recruit the right production test users:** We will recruit users via Perigean.
- **How you'll conduct the testing:** We will conduct UAT over Zoom to ensure the different features work correctly.
- **How you'll give the test users access to the product in production w/o making it live on VA.gov:** The feature will be behind a feature flag.
**Link to Research plan for UAT:**
- Research Plan (add link)
- Conversation Guide (add link)

### Results
- **Number of users:** x
- **Number of bugs identified / fixed:** x/x
- **Types of errors logged: lorem ipsum**
- **Any UX changes necessary based on the logs, or feedback on user challenges, or VA challenges?** yes/no
If yes, what: lorem ipsum

### Planning:

- **Desired date range:** mid-June 2022.
- **How you'll make the product available in production while limiting the # of users who can find/access it:** The feature will be behind a feature flag.
     - 25% of users (3-5 days), Dates: ticket 1
     - 50% of users (3-5 days), Dates:  ticket 2
     - If all goes well, then go to 100% of users:  ticket 3

 "Success" criteria (by the numbers): 

- Link clickthroughs are successfully directing users to the intended pages with no errors 
- No P0's (launch-blockers) found
- Approval from the GO/NO GO call

# Go Live!

## Planning:

Desired date: June '22

### Objective: Allow people to more accurately define themselves within the VA.

**KPI**: See 10,000 updates to each new personal information field in the first 3 months after launch.

|Field name|Updates in first month after launch (dates TBD)| Second month after launch (dates TBD)| Third month after launch (dates TBD)|
|----------|------------|------------|------------|
|Preferred name| | | |
|Gender identity| | | |

**KPI**: We see at least a 95% success rate for retrieving this information from the backend.

|Field name|% of successful retrievals in first month after launch (dates TBD)| Second month after launch (dates TBD)| Third month after launch (dates TBD)|
|----------|------------|------------|------------|
|Preferred name| | | |
|Gender identity| | | |

**KPI**: We don't see a significant reduction in mailing/home address, mobile phone, or email address updates since those have been moved off of the landing page of the profile.

[Contact information report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/3Z1vT6SlQqevdav1s72QwA/a50123418w177519031p176188361/)

|Field name| Average monthly updates (total events) between Oct - Dec 2021 | # of monthly updates 1 month post-launch | 2 months post-launch | 3 months post-launch |
|----------|------------|------------|------------|------------|
|Mailing address | ~28,500 updates | | | |
|Home address | ~28,500 updates | | | |
|Mobile phone | ~14,000 updates | | | |
|Email address |~15,500 updates | | | |

**Comment by SKasimow** [comment]
@Samara-Strauss - would you mind taking a look at this and lmk if I missed anything or need to change anything?

(I put in loose placeholder dates for now).

**Comment by Samara-Strauss** [comment]
@SKasimow this looks great! Could you please copy/paste and save this in our github folder in [this doc that I created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/product/release-plan.md)? Thank you!

**Comment by SKasimow** [comment]
Added copy of this ticket to [github folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/product/release-plan.md)

**Comment by SKasimow** [comment]
Info is in template in GitHub ^
