### ISSUE TITLE
CT: Update auto-complete search functionality to use REDIS

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4046]
@dneel-bah commented on [Mon Dec 02 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20053)

As a developer, I need to update the auto-complete search functionality of the comparison tool to use REDIS, so that it uses cached data for search functionality to prevent performance issues when completing searches.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The non VETTEC institution auto-complete uses “cache-aside” to perform searches.
2. The VETTEC provider auto-complete uses “cache-aside” to perform searches.

## Supporting Artifacts:
1. N/A

## DSVA Notes:
I'm concerned by the following:

This is a synchronous request -vets-api will hold the request until the gids service responds.
Autocomplete endpoints tend to get called frequently
Even if the gids service is very responsive and FE devs use a sensible bounce interval for calling this endpoint, we should try to code defensively to protect vets-api. Have you made any considerations for performance?

Perhaps look into using cache_aside.

## PR
https://github.com/department-of-veterans-affairs/vets-api/pull/3622

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3622

**Comment by desireeturner** [comment]
Moving to icebox in anticipation of lifting the DSVA Code Freeze on 1/6.

**Comment by zurbergram** [comment]
@delli-gatti-michael PR is merged in

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
