### ISSUE TITLE
Update references of content-build default branch in other repositories

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#40471]
## Description

All references made to `content-build`'s `master` branch in other repositories should be updated to `main`. We need to create pull requests in each of the repositories that reference the default branch.

The inventory of `content-build` references can be seen [here](https://docs.google.com/spreadsheets/d/1yHX-LyHp4h_XcB50R9t8YRYBd1xEL9iW-ukeUqyLZ5k/edit?usp=sharing). All repositories on the list should be thoroughly searched, including the repositories that don't have multiple files referenced.

**Note**: These changes should in the other repositories should not be merged until the `main` branch in `content-build` has been completely setup.

## Definition of done
- [x] `content-build` default branch references in other repositories are updated to use `main`.

**Comment by it-harrison** [comment]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1_IAvxZm2QE_tQpGuX_nQMbPLgz_jeWWj1WTR8n6wNBE/edit#gid=0) details the changes made.

**Comment by it-harrison** [comment]
Draft PRs in other repos: 
[content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1113)
[devops](https://github.com/department-of-veterans-affairs/devops/pull/11186)
[va.gov-team-sensitive](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/479/files)
[vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/20962/files)
[performance-dashboard](https://github.com/department-of-veterans-affairs/performance-dashboard/pull/4073)
[va.gov-cms](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8944)

**Comment by theodur** [comment]
Closing this now that all related PRs have been merged
