### ISSUE TITLE
SOCKS access for Sarah Koomson

### ISSUE THREAD

**Issue by SarahKay8** [department-of-veterans-affairs/va.gov-team#40478]
### Your Name

Sarah Koomson

### Your Email

sarah.koomson@oddball.io

### Your Role

Accessibility Specialist, Platform Governance, Oddball Inc. 

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCus6iTUJ0xNcEtRPkBf2/bgDr4tdiVQvlVRTJSdSU7Es4PuPCGN3nXP/deRETugh5wAcaFrIzA4ls7LBbOaN9/+MVKV82BlQHxbXGPDscdqsnBub7kBy4u0p0G0ST5WEkLjHa/NQvo3mQFoMR2kk/F9FGKTMGA6r8LwJj33FhXh6fI52MCo8jpxh56XuHMha94ZO1LIl6ASD985WVmrUmADOPH4HbiinhEKwOadZXAh7s5QjQkxdcoA16h57KPKlJUJETgnC85ORKU3vXypi1c5akpT64YAy4CrtpZ7anI13e4+iwH2pYRhMVvfAID7GoMCzWHqrSOFDB7BdORV8ZL7E44utACjQ98Q5ov/9g+i7J2ov67PZBXnMBLwWFkurTEBFWOAX7zxyBj5S1P8Qo2Wxb+OLLQQnF4degyXnJUbgCWG+ua2kunfktlWZ4/2XhUafcxPX0FKHaK4AeUOaxq9mT9KMMNlCIbx+NkW/fkQg7cw4f9FBt9+hRn6zb16Cc= sarahkay3x@Sarahs-Air

**Comment by rmtolmach** [comment]
@SarahKay8 Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.

**Comment by SarahKay8** [comment]
> @SarahKay8 Access granted ✅
> 
> Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect. See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html
> 
> Reach out in #vfs-platform-support if you have any trouble.

Thank you!
