### ISSUE TITLE
[FE] 10-10EZ Short-form: Race/Ethnicity/Origin checkbox association > [Markup and meta data] Visual labels aren't included in the accessible label. (09.05.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40488]
#### VFS team name
10-10 Team

#### VFS product name
Health Care Application 10-10EZ

#### VFS feature name
10-10EZ Short Form (Auto-qualifiers)

#### Point of Contact/Reviewers
Brian DeConinck (@briandeconinck) - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Visual labels aren't included in the accessible label.

### Issue Details
In Step 1 of 3 [disability rating >50%], in the question on race and ethnicity, the question "What is your race, ethnicity, or origin? (Please check all that apply.)" isn't programmatically associated with the checkbox responses. If a screen reader user tabs directly to the first checkbox, the checkbox label will be announced without the context of what question it's answering.

### VA.gov Experience Standard
[Category Number 09, Issue Number 05](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 2.5.3_A

---

### Platform Recommendation
Right now, the checkboxes and their labels are wrapped in a `<fieldset>`, but the question itself ("What is your...") and the helper text ("Information is gathered for...") come before the fieldset.

Instead, I would recommend moving both the question and the helper text inside the `<fieldset>`, and turning the question into a `<legend>` instead of a `<p>`. (The helper text is fine to remain a `<p>`.)

### VFS Team Tasks to Complete

- [x] Comment on the ticket if there are questions or concerns
- [x] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by hdjustice** [comment]
@briandeconinck 
The 10-10EZ short form skips over this question, and does not appear during this process.  We agree that this does need to be addressed sooner rather than later, however this is in production now and we feel it should not be a launch blocker to functionality that does not display it.

Please let us know your thoughts.  Thank you.
