### ISSUE TITLE
[Design, FE] 10-10EZ Short-form: Review VA Facility fieldset implementation > [Overall user experience] Design component or pattern in use isn't considered a best practice. (01.01.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40497]
#### VFS team name
10-10 Team

#### VFS product name
Health Care Application 10-10EZ

#### VFS feature name
10-10EZ Short Form (Auto-qualifiers)

#### Point of Contact/Reviewers
Brian DeConinck (@briandeconinck) - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Design component or pattern in use isn't considered a best practice.

### Issue Details
On Step 2 of 3 [disability rating >50%], in the VA Facility questions, there are three main `<fieldset>` groupings of questions:
- Checkbox for ACA minimum essential coverage
- Select your preferred VA medical facility
- Do you want VA to contact you to schedule...

These three groupings are all wrapped in a larger `<fieldset>` with a `<legend>` of "VA Facility."

This is the only place in the workflow where fieldsets are nested inside another fieldset, and it's not entirely clear to me that "VA Facility" makes sense as a legend for the ACA checkbox or the scheduling question. It's also the only point in the workflow where the "You're filling out a shortened application" additional info component isn't the first element after "Step X of Y".

This isn't a technical failure, but it may potentially confuse users. Questions that aren't obviously related are grouped together, and they're grouped in a way that breaks the pattern they've seen up to this point.

### VA.gov Experience Standard
[Category Number 01, Issue Number 01](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
If possible, remove the surrounding `<fieldset>` and remove the "VA Facility" `<legend>`. And if it makes sense, consider breaking this up into multiple pages, one for each of the fieldsets.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by hdjustice** [comment]
2 issues here:
- Notice that Veteran is on a short form is under header, however it should be above the header - This will be in a new ticket and addressed prior to Short form launch.
- HTML is formatted so it looks like nested fieldsets.  This is already in production, and will be addressed after launch of Short Form

**Comment by lzapson** [comment]
This was automatically fixed by fixing issues #[40500 ](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/40500)
