### ISSUE TITLE
[FE] 10-10EZ Short-form: Progress bar not labeled correctly > [Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.2)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40494]
#### VFS team name
10-10 Team

#### VFS product name
Health Care Application 10-10EZ

#### VFS feature name
10-10EZ Short Form (Auto-qualifiers)

#### Point of Contact/Reviewers
Cheryl Evans (@CherylEvans) - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
The content has spelling, punctuation, or typo errors.

### Issue Details
Apply for health care: Under blue progress bar, it says, "Step 1 of 3".  According to the progress bar, it should read "Step 2 of 6"

### Link, screenshot or steps to recreate
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/1Kz2Pak

### VA.gov Experience Standard
[Category Number 05, Issue Number 02](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
Change "Step 1 of 3:" to "Step 2 of 6:"

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by lzapson** [comment]
Progress bar looks correct in application. It's not in sketch design, maybe that was the confusion. Screen shot below from application in RI.
![image.png](https://images.zenhubusercontent.com/6195603c38ef1a28570c4f7b/f47c1c90-9212-43f7-ad70-8a1434c283ed)

**Comment by hdjustice** [comment]
This issue was found on the sketch design, but does not exist in functional code. Closing ticket.

**Comment by shiragoodman** [comment]
thank you all for researching the issue!
