### ISSUE TITLE
[Design, FE] 10-10EZ Short-form: "Form 10-10EZ" inconsistently placed > [Content styleguide] The content isn't written consistently across static pages, tools, and devices.  (05.03.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40493]
#### VFS team name
10-10 Team

#### VFS product name
Health Care Application 10-10EZ

#### VFS feature name
10-10EZ Short Form (Auto-qualifiers)

#### Point of Contact/Reviewers
Cheryl Evans (@CherylEvans) - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
The content isn't written consistently across static pages, tools, and devices. 

### Issue Details
Throughout all of the other pages, "Form 10-10EZ" is positioned underneath "Apply for health care", except on this page it is placed beside "Apply for health care". 

### Link, screenshot or steps to recreate
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbdvz8d

### VA.gov Experience Standard
[Category Number 05, Issue Number 03](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
Place "Form 10-10EZ" underneath "Apply for health care", to make it consistent with other pages.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by Dene-human** [comment]
This is a prototype issue, please check the RI (screenshot attached
<img width="539" alt="Review page" src="https://user-images.githubusercontent.com/80857940/165743350-8fb0dbb5-f175-452e-b550-8e74d6de5181.png">
)

**Comment by hdjustice** [comment]
This issue was found on the prototype, but does not exist in functional code.  Closing ticket.
