### ISSUE TITLE
[FE] 10-10EZ Short-form: Missing progress bar > [Content organization] Your content or feature isn't placed within an appropriate or relevant area of VA.gov. (02.02.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40496]
#### VFS team name
10-10 Team

#### VFS product name
Health Care Application 10-10EZ

#### VFS feature name
10-10EZ Short Form (Auto-qualifiers)

#### Point of Contact/Reviewers
Cheryl Evans (@CherylEvans) - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Your content or feature isn't placed within an appropriate or relevant area of VA.gov.

### Issue Details
Apply for health care: Under blue progress bar, "Step 2 of 6" is missing.

### Link, screenshot or steps to recreate
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/YGLwZQO

### VA.gov Experience Standard
[Category Number 02, Issue Number 02](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
Add: "Step 2 of 6" under blue progress bar.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by lzapson** [comment]
Progress bar is included in application. It's not in sketch design, maybe that was the confusion. Screen shot below from application in RI. 
![image.png](https://images.zenhubusercontent.com/6195603c38ef1a28570c4f7b/201034b3-ddb1-40cf-8209-b94dde9faa96)

**Comment by hdjustice** [comment]
This issue was found on the sketch design, but does not exist in functional code. Closing ticket.
