### ISSUE TITLE
[Design, FE] 10-10EZ Short-form: Update content on Intro page > [Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40495]
#### VFS team name
10-10 Team

#### VFS product name
Health Care Application 10-10EZ

#### VFS feature name
10-10EZ Short Form (Auto-qualifiers)

#### Point of Contact/Reviewers
Cheryl Evans (@CherylEvans) - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
The content has spelling, punctuation, or typo errors.

### Issue Details
Gather your information: "Your military discharge information", and "Your deductible expenses for last year" have periods at the end even though they are not complete sentences, and the other bulleted items in the list do not have periods.

### Link, screenshot or steps to recreate
https://preview.uxpin.com/acda277e33e9629a7ab817f6c93c251b4a60ac56#/pages/141488399/simulate/no-panels?mode=i

### VA.gov Experience Standard
[Category Number 05, Issue Number 02](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
Recommend removing the periods from those two sentences.  They will then be consistent with the other bulleted items in the list.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by hdjustice** [comment]
In production.  We can address this when we have capacity/working on intro page.

**Comment by hdjustice** [comment]
@shiragoodman - 
What I meant was that the punctuation issue existed in Production, and that we did not plan to address it right away.  
That has since changed, I apologize, we should have added a comment that we decided to pull this in to the current sprint.  Lisa has completed the fix for this issue.
cc: @markfallows @lzapson

**Comment by shiragoodman** [comment]
thank you for clarifying!
