### ISSUE TITLE
Identify which backend services have statsd metrics

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#405]
## User Story
As a VSP Triage team member, I need to know which backend services we use have statsd metrics so I can build a custom alert for errors from those services.

## Goal
A list of all of our backend services that we use with a Y/N answer for statsd metrics for each

## Acceptance Criteria
- [ ] A list of all of our back end services exists
- [ ] Indication of stats-d metrics availability for each of them
- [ ] This documentation is available in GitHub

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
*These are the services for which we gather at least some specific metrics into StatsD. More details can be found in the StatsD initializer, found [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/statsd.rb)*

### SAML (each auth context, redirects)
### Sessions Callback/Login/Errors
### Appeals
### Benchmark
### GIBFT
### HCA Enrollment
### iHub
### MVI
### GiBillStatus
### Letters/PCIU
### Disability Comp Submission  (form 526)
### Vet360 
### eMIS
### PagerDuty
### Preneeds
### CentralMail
### SentryJob
### Search
### Workers
- should be instrumented with statsd-instrumented


*These services are missing metrics:*

### BlueButton/RX/SM
### MHV Logging
### OIDC
### Pension/Burial Procession OFfice
### Salesforce
### Reports
### VIC
### VSO Appt Forms
