### ISSUE TITLE
[FE] 10-10EZ Short-form: Error during submission not displayed > QA Feedback - Staging Review - 1010 EZ | Short-form Ph 1

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#40504]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/38031

**Comments:**
None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Using the account `vets.gov.user+228@gmail.com`, I was unable to submit the short-form when I inputted information only for required fields and did not enter any optional information. I saw this error in Chrome:
```json
{"errors":[{"title":"Form maritalStatus can't be null","detail":"form - maritalStatus can't be null","code":"100","source":{"pointer":"data/attributes/form"},"status":"422"},{"title":"Form isEnrolledMedicarePartA can't be null","detail":"form - isEnrolledMedicarePartA can't be null","code":"100","source":{"pointer":"data/attributes/form"},"status":"422"},{"title":"Form lastServiceBranch can't be null","detail":"form - lastServiceBranch can't be null","code":"100","source":{"pointer":"data/attributes/form"},"status":"422"},{"title":"Form lastEntryDate can't be null","detail":"form - lastEntryDate can't be null","code":"100","source":{"pointer":"data/attributes/form"},"status":"422"},{"title":"Form lastDischargeDate can't be null","detail":"form - lastDischargeDate can't be null","code":"100","source":{"pointer":"data/attributes/form"},"status":"422"}]}`
```
The confirmation page is blank and does not show an error. Should an error message be shown to the user if this scenario ever occurs in production?

**Should:**
None

**Consider:**
None

**Comment by ddzz** [comment]
The error mentioned in this ticket is due to a limitation of review instances and not a bug. This will be tested again once the feature reaches staging.

**Comment by hdjustice** [comment]
Further testing will be completed in Staging.  
Also, we are currently in discovery of error states in Staging and Production environments, so that we can confirm we have appropriate messages for them all.  Once the error states have been identified, and we confirm which still need to have messages displayed on the pages, we will begin the work to add them and any issues reported here should be resolved.
