### ISSUE TITLE
[SPIKE] Investigate how to log issues in Sentry as debug vs. error level

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40517]
## User Story
As a CIE engineer, I wish to be able to search on upstream error statuses and messages from CHIP and LoROTA, so that I can set up granular alerting.

## Background
https://dsva.slack.com/archives/C02G6AB3ZRS/p1649173731836539?thread_ts=1649093862.261139&cid=C02G6AB3ZRS

## Tasks
- [ ] Identify the errors we want to log in Sentry as debug vs. error level
- [ ] Investigate in vets-api how to log issues in Sentry as debug vs. error level

**Comment by wullaski** [comment]
@acrollet is this something we should be concerned with still?

**Comment by acrollet** [comment]
Looking at the slack thread, we may be able to accomplish the goal entirely in datadog now that we have vets-api logs there, example query: https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40payload.controller%3A%22CheckIn%3A%3AV2%3A%3ASessionsController%22%20-%40http.status_code%3A200%20-12345678-1234-1234-1234-0123456789ae&cols=host%2Cservice&context_event=AYSHUVwPAABdMkTdeGfcmADb&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=&from_ts=1668121239221&to_ts=1668726039221&live=true

Tagging in @kanchanasuriya for her input.

**Comment by kanchanasuriya** [comment]
Unfortunately, we only have successful logs in datadog.  Error logs still go to the sentry.  

We have the error logs streamed to vagov datadog instance from sentry ([Reference logs](https://vagov.ddog-gov.com/event/explorer?query=source%3Asentry&cols=&messageDisplay=expanded-lg&options=&sort=DESC&from_ts=1668729762147&to_ts=1668730662147&live=true)).  But no differentiation by debug vs error level

**Comment by brianseek** [comment]
@acrollet I read through the old slack thread and dug in a little bit on this, but can we pair a bit on Monday so I can get a better handle on it?

**Comment by brianseek** [comment]
Working with @acrollet and @kanchanasuriya, they set up an alert to the the #check-in-experience-apm slack for 500 errors from sentry: https://vagov.ddog-gov.com/monitors/102168. 

The plan is to ignore the known issues that there are tickets in the backlog for in sentry. Hopefully the filtered alerts will eventually be only new issues, or issues that pop up again after the ignore window passes.

**Comment by brianseek** [comment]
these are the known alerts so far that have been mute now for 30 days:
http://sentry.vfs.va.gov/organizations/vsp/issues/155145/
http://sentry.vfs.va.gov/organizations/vsp/issues/155463/
http://sentry.vfs.va.gov/organizations/vsp/issues/158333/
http://sentry.vfs.va.gov/organizations/vsp/issues/155738/
