### ISSUE TITLE
Analytics Implementation + QA | Auth Profile | Personal Info Revisions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40524]
# Google Analytics Implementation or QA Request

## What this form is for

Analytics set-up and QA for the following:
1.  New Profile/Contact Info page (currently Contact info resides on 1 page along with Personal Info; this effort will split them up into 2 pages).
2. Addition of two new fields on Personal Info page: Preferred Name and Gender Identity

### Required

**Is this request for **Google Analytics implementation** or **QA**?**

- [x] Google Analytics implementation
- [x] QA

**Who is this request for?**
  
Auth-Profile Team 
- DEPO Product Lead (required): **Samara Strauss**
- Product Manager (required): **Sharon Kasimow**
- Designer (required): **Christina Gednalske**
- Frontend engineer(required): **Adam Whitlock**
- Backend engineer (required): **Tom Harrison**    

**Provide the link(s) for Google Analytics implementation or QA**
- Va.gov/profile/personal-information
- Va.gov/profile/contact-information

**When is the launch date?**
      
Estimated launch: early June 2022

**What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
1. **Tracking for clicks into the new Contact Information link in the left-nav** (previously combined with the personal information section)

2. **Interactions to be tracked for preferred names**
- Clicks to preferred name edits (open)
- Count of fail saves
- Count of successful preferred name updates (saves)

3. **Interactions to be tracked for gender identity***

- Clicks on Gender Identity edits (open)
- Count of successful updates (saves) 
- Count of fail saves
- Clicks to "What to know before you decide to share your gender identity"

4. **Retrievals**
- Successful retrievals of personal information from the backend
- Failed retrievals of personal information from the backend

[Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    1. Please review for any additions we will need to make for GA/DOMO analytics.
    2. Would also like to request QA review once implemented.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by Samara-Strauss** [comment]
Great, let's plan to go over it.

**Comment by michelle-dooley** [comment]
@SKasimow - thanks for your submission.  We will get this added to our que.

**Comment by jonathan-epstein13** [comment]
@SKasimow @Samara-Strauss - Please let us know if you have any questions.

Personal Information
| Interaction | Screenshot of Interaction | Screenshot of dL | Status |
| -- | -- | -- | -- |
| Clicks to preferred name edits (open) | ![image](https://user-images.githubusercontent.com/91892981/166814475-0b1f0f2a-bb3b-494f-86c6-5fa61897a2cf.png)| ![image](https://user-images.githubusercontent.com/91892981/166814601-25dbd46a-c5e4-4539-a040-0579fb770bff.png)| 🟢Tracking Correctly|
| Count of fail saves| | { event: 'api_call', api-name: 'Profile - Personal Information Save', api-status: 'failed', 'error-key': '500 timeout message' api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }
| Count of successful preferred name updates (saves)| ![image](https://user-images.githubusercontent.com/91892981/166814732-ac561ca3-1685-423f-90d4-1182e2e1cdf2.png)| ![image](https://user-images.githubusercontent.com/91892981/166814842-9499b993-4c80-4e2a-b72d-d174b0f95d6d.png)| 🟢 Tracking Correctly |



Contact Information
| Interaction | Screenshot of Interaction | Screenshot of dL | Status |
| -- | -- | -- | -- |
| Clicks on Gender Identity edits (open)|![image](https://user-images.githubusercontent.com/91892981/166815095-ffc744fe-d73a-48fc-beb7-c9ca106a7c78.png)| ![image](https://user-images.githubusercontent.com/91892981/166815177-cab29c0e-88ff-447d-86f0-7b67a5de2f74.png)   | 🟢 Tracking Correctly |
| Count of successful updates (saves) |![image](https://user-images.githubusercontent.com/91892981/166815636-8384cc93-66e7-4cc2-9792-5c41b064713a.png)|![image](https://user-images.githubusercontent.com/91892981/166815735-3ed59b9d-fada-4167-b274-1983a3761f31.png)| 🟢 Tracking Correctly |
| Clicks to "What to know before you decide to share your gender identity"| |  | 🟢 Tracking Correctly |


These will need to be fired off from the application when the action(s) are taken:

Data Layer
| Interaction | dataLayer code |
| -- | -- |
| Successful retrievals of personal information from the backend | { event: 'api_call', api-name: 'Profile - Personal Information Retrieval , api-status: 'successful', api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" } |
| Failed retrievals of personal information from the backend | { event: 'api_call', api-name: 'Profile - Personal Information Retrieval', api-status: 'failed', 'error-key': '500 timeout message' api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }


The event name can stay as is. The api-name should be updated. The other parameters are optional.

**Comment by Samara-Strauss** [comment]
At this point, is there work required from our frontend developer, @jonathan-epstein13?

**Comment by jennaouellet** [comment]
Hi @Samara-Strauss, your developer will need to add these events for the failures and API retrievals:

**Fail to save personal information:**
{ event: 'api_call', api-name: 'Profile - Personal Information Save', api-status: 'failed', 'error-key': '500 timeout message' api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }

**Successful save personal information:**
{ event: 'api_call', api-name: 'Profile - Personal Information Save', api-status: 'successful', api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }

**Successful personal information retrieval**
{ event: 'api_call', api-name: 'Profile - Personal Information Retrieval , api-status: 'successful', api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }

**Failed personal information retrieval** 
{ event: 'api_call', api-name: 'Profile - Personal Information Retrieval', api-status: 'failed', 'error-key': '500 timeout message' api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }


The error-key, api-latency-ms, and api-request-id are optional and have example values. If you aren't recording those, you can just include in the event, api-name, and api-status.

Once those are in staging please let us know and we'll do a quick QA. Thanks!

**Comment by Samara-Strauss** [comment]
@SKasimow can you ticket the above work for Adam, to be implemented ASAP? If he has time, this sprint would be great. I think this is higher priority than his other work for the sprint (as I recall, he was light), but let me know if there's something I'm not thinking about.

**Comment by SKasimow** [comment]
Yes - I'm about to open this and another analytics ticket for him. I

**Comment by SKasimow** [comment]
Opened FE ticket #41067

**Comment by SKasimow** [comment]
@jennaouellet Yay! Thanks so much for the quick turn-around!

cc: @adamwhitlock1 @Samara-Strauss

**Comment by SKasimow** [comment]
@Samara-Strauss - yes I can but think we may just need to submit an analytics ticket.

@jennaouellet - is that correct?

**Comment by jennaouellet** [comment]
@SKasimow a ticket is fine! We can help out with the dashboard needs that way. When you're submitting the ticket, just include the events you'd like to have displayed and if they should be added to an existing dashboard or a new one.

**Comment by SKasimow** [comment]
@jennaouellet ok ty. I will join an office hours if I have any q's when drafting the ticket.

**Comment by Samara-Strauss** [comment]
All of this sounds good. Thanks!
