### ISSUE TITLE
Remove "referral" language on Facility Locator for urgent care, urgent care walk-in, and urgent care pharmacy community care facility types

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#4052]
## User Story or Problem Statement

For urgent care, urgent care walk-in, and urgent care pharmacy community care facility types we will not necessarily need a referral, unlike other facility types in Community care which will confuse veterans.  We need to be sure to step through the veteran health experience in urgent care to reflect their needs

## Goal
_What outcome(s) do we want to see?_

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
moving this info into [#3897] so it can be included in the next round of prototyping and user research
