### ISSUE TITLE
Discovery: Determine how Storybook should communicate event usage

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#40543]
## Description
We have lots of components where a user could use an event on that component. However we don't have a great way of showing what events we are using (native or custom) and what they are actually used for. 

This ticket is to explore adding further documentation within storybook to give users information on a given component about the events we are using within that component at a high level. Ie: onInput fires an even when a user enters data into an input field.
 
Overall we should have some information on what each event does, and when and how it is fired. This way future developers who view Storybook can understand better the use case for the event.

## Acceptance Criteria
- [ ] Determine and document an approach that we should use to help users get more information in Storybook about events we are using on our components - Timebox this work to 1 day.

**Comment by pdavies88** [comment]
Recommendations:
* https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/storybook/stories/events.js#L9 update link to https://design.va.gov/about/developers#custom-events
  * This will help point developers directly to implementation of the custom events
* Add a section in https://design.va.gov/about/developers above Custom Events about Native Events
  * We should detail out how to use Native Events and why they are available on the components

**Comment by pdavies88** [comment]
@k80bowman let's put this on the calendar for the Monday meeting. I went back and forth a lot on this ticket and ultimately think we can probably put some documentation on design.va.gov about native events and update our link in SB to go to that section of the page and that should cover us for event related questions moving forward.

**Comment by k80bowman** [comment]
@pdavies88 added it to the agenda.

**Comment by pdavies88** [comment]
Related #900
