### ISSUE TITLE
Create 404 Page for design.va.gov

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#40558]
## Description
Right now on design.va.gov if a user goes to an incorrect url they get a 403 Forbidden Message.

## Solution
We should create a 404 Page for design.va.gov to redirects users back to the home page if they go to an incorrect url.

## Acceptance Criteria
- [ ] Create and deploy a 404 page for design.va.gov

**Comment by k80bowman** [comment]
Closing in favor of https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/867
