### ISSUE TITLE
Add language to Feature Request Guide to clarify initial response

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40561]
## Issue Description
Add language to Feature Request Guide to clarify initial response.  It requires PL to recognize new item.  Does this need additional clarity or steps?

Guide: https://vfs.atlassian.net/wiki/spaces/AP/pages/1909293082/Feature+request+process+-+User+guide+for+Platform+teams
---
## Tasks
- [x] Consider and update language to make it clear that submissions are reviewed by PL and not SDT.

## Acceptance Criteria
- [x] Language is updated in the guide

**Comment by twoangstroms** [comment]
Will this get reviewed by someone on Platform? Are there any questions left about who would be reading this?
