### ISSUE TITLE
SOCKS access for Penny Lischer

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-team#40571]
### Your Name

Penny Lischer

### Your Email

penny.lischer@agile6.com

### Your Role

Software Engineer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4XzBAc0SsVX3LeqgtPK0o53zr8TUKvyszxv+ZvKkmsA/foqXey9/Gr7R9JLObrWCNm0J1QoULthZp/w37kwOfh+PVq/8wzEr1tjs9GiLf+wZ3NMLF6sszvUVZdUhWvnMS02oEJv76vVrQwyCtZTWeQpiyHcd/xQl0tLizkiVMTjax8sG6hgTpjgJoS47G76UB1gT+Kho3+2dazJjKoRamtw42KT9AD7nh/H+3TzJIiIoHxjpHjrNfL4BFY8LrZ20Zpw95GbCRpn1Knd1ozE3PVVul95721dZKDgqlSp+GpFJkYXilMUT3SKaScg2bT7JvKnLvhCe+N9hYefXLpLawRXpuME5QyCH/9OSGvdt7Ikd74pfEJKELuvA/7pdd/lu4Q57jVqPW9RTTqDzhctjdV5Axu9oEtz0ReebvTtmQCrUlcsYlCGYQbQ3WZ4Vvah6e4C+PlmNCi4GBfCN7uQgUIdsHQ7bU+I9Y7tCL1DZaiiXziDlBo4NAW5cUBfTqxZU= Penny.Lischer-a@Agile6-A89.lan

**Comment by rmtolmach** [comment]
@penny-lischer Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
