### ISSUE TITLE
[FE] Add 3 Information Accordions to Expired Message Pages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40586]
## Wireframes
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/m1l0PA7

## Description
Add 3 new accordions to all expired message pages (see wireframes)
- What is pre-check-in? 
    - Defaults to closed
- How can I update my information? 
    - Defaults to open
- Why can't I pre-check-in?
    - Defaults to closed

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
@zach-park This is ready for validation, see screenshots. The first screenshot is the midnight to apt. time message default state with the update info accordion default open. The next two is the content in the other two accordions. The last one is the default state of the after appointment lapse message.

*Note, this feature branch is not yet deployed.

![localhost_3001_health-care_appointment-pre-check-in__id=354d5b3a-b7b7-4e5c-99e4-8d563f15c521 (2).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/b36700d7-c3e0-4c82-9b07-6c1f51a773eb)
![localhost_3001_health-care_appointment-pre-check-in__id=354d5b3a-b7b7-4e5c-99e4-8d563f15c521 (3).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/bd8c9c14-6088-418e-9dfe-4f8c0ae7d42e)
![localhost_3001_health-care_appointment-pre-check-in__id=354d5b3a-b7b7-4e5c-99e4-8d563f15c521 (4).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/b0187918-07ce-403d-94ad-e64cd998d950)
![localhost_3001_health-care_appointment-pre-check-in__id=354d5b3a-b7b7-4e5c-99e4-8d563f15c521 (5).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/1fc8a8ee-0d31-4b58-930b-d7363a5bee7d)

**Comment by zach-park** [comment]
Hi @brianseek , just a quick question to confirm, are these for the in-person or telephone appointments?

**Comment by brianseek** [comment]
@zach-park This is specifically for pre-check-in which will apply to telephone but not exclusively.

**Comment by zach-park** [comment]
Hi @brianseek , they look really good overall. Here are the links to more comments from the UX review. Cc: @loripusey @niradatta1 @kristenmcconnell 

[Midnight to apt. time message default state ("Update Info" accordion open)](https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/00A39DC0-3D60-4208-A4B4-865E974931CB
): 
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/00A39DC0-3D60-4208-A4B4-865E974931CB

[[What is pre-...] First accordion open](https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/0A715BC0-DD3C-426C-A3B0-47BD711191F5):
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/0A715BC0-DD3C-426C-A3B0-47BD711191F5

[[Why can't I pre...] The third accordion open](https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/76610F0C-B151-4C84-A190-2B343C4A5A43):
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/76610F0C-B151-4C84-A190-2B343C4A5A43

Additional note: 
Please be sure to refer to the accordion content of each use case from the[ following link](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/09EgK8V):
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/09EgK8V

**Comment by zach-park** [comment]
@brianseek I added one additional comment in the annotation just now, apologies.

**Comment by brianseek** [comment]
@zach-park Thanks for the handy sketch annotations! When looking at these specific tickets, note that they are only scoped to one part of the page. This covers accordions only, so the H1 and footer stuff is not applicable. But this does bring up a question about the footer, currently the content in the footer is static across all pages, if we shouldn't be showing part of it, that needs a new ticket. Can you confirm that we need to change footer details based on error pages? If so @loripusey can you make us a ticket for that?

I created a PR for the one remaining issue of needing the line break here: https://github.com/department-of-veterans-affairs/vets-website/pull/21138

**Comment by loripusey** [comment]
@brianseek @zach-park I'd like to get to a place where FE and Designers can look at the product together over Zoom; the asynchronous nature of these interactions add additional overhead and time for the designer to have to generate annotations; it would be much better if we can just hop on a quick zoom, have FE show us the application (as it pertains to a specific story) and validate on the spot or determine if there are additional changes; I would also like to be included in these sessions but don't want to be a roadblock because of schedule; 
cc: @sarahknoppA6 @kristenmcconnell @acrollet

**Comment by brianseek** [comment]
I like that idea @loripusey, I think we could even do these things on the fly. If a UX person is reviewing and has questions, they can ask in slack to hop on a quick zoom to go over stuff and tag Lori in too if you have time to join.

**Comment by brianseek** [comment]
@zach-park here is the latest update with the line break:
![localhost_3001_health-care_appointment-pre-check-in__id=354d5b3a-b7b7-4e5c-99e4-8d563f15c521 (7).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/407159ac-27c9-4693-81ee-8fe27b55099a)

**Comment by zach-park** [comment]
LGTM. Thank you!!
