### ISSUE TITLE
AWS access for [Ian Hundere]

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#40594]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ian Hundere

### Your Email

ian.hundere@oddball.io /  Ian.Fitch-Hundere@VA.GOV

### Your Team, Role, and Company

Identity, DevOps Engineer, and Oddball

### Desired AWS Access

I'm not sure what y'all's scope of permissions is in AWS or if least privilege principle is followed, but I'll be working on the infrastructure team initially and then I'll primarily be working on the Identity team. Other than that, `AdminRole` is typically what I've been assigned in the past, but I'll take what I can get 🙂 .

### Access Expiration

ongoing

**Comment by rmtolmach** [comment]
User: Ian Hundere
 COR: Eunice Garcia
 VOR: Oddball - Amber Malcolm
 Approval needed: @department-of-veterans-affairs/operations-aws-approvers
 Admin level: Not sure @jbritt1, can you weigh in on access? 

Approvers will check with your VOR on your EQIP status.

**Comment by jbritt1** [comment]
> User: Ian Hundere  COR: Eunice Garcia  VOR: Oddball - Amber Malcolm  Approval needed: @department-of-veterans-affairs/operations-aws-approvers  Admin level: Not sure @jbritt1, can you weigh in on access?
> 
> Approvers will check with your VOR on your EQIP status.

Not my call. That is a decision to be made at the leadership level.

**Comment by ianhundere** [comment]
any progress?

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS access approved

**Comment by jbritt1** [comment]
@td-usds, are you approving admin level perms or general access? Could you please address the info in the description?

```
Desired AWS Access
I'm not sure what y'all's scope of permissions is in AWS or if least privilege principle is followed, but I'll be working on the infrastructure team initially and then I'll primarily be working on the Identity team. Other than that, AdminRole is typically what I've been assigned in the past, but I'll take what I can get 🙂 .
```

**Comment by ianhundere** [comment]
> @td-usds, are you approving admin level perms or general access? Could you please address the info in the description?

i believe @joeniquette spoke to someone about this already. i'll be onboarding with the infrastructure team as well.

**Comment by jbritt1** [comment]
> > @td-usds, are you approving admin level perms or general access? Could you please address the info in the description?
> 
> i believe @joeniquette spoke to someone about this already. i'll be onboarding with the infrastructure team as well.

Understood and happy to grant that, but need confirmation from Thomas Delrue or even Mike Chelen in writing (via comment here on this issue) so we have tracked PO approval on it.

**Comment by ianhundere** [comment]
yup yup, understood / just providing context.

**Comment by ianhundere** [comment]
> ...need confirmation from Thomas Delrue or even Mike Chelen in writing (via comment here on this issue) so we have tracked PO approval on it.

@td-usds / @mchelen could we get confirmation / approval on the scope of my permissions?

**Comment by ph-One** [comment]
For Ian to work with infra, he should be full admin, but once he settles in on the identity team, we will remove full admin and provide a more appropriate set of privs.

**Comment by jbritt1** [comment]
Working on AWS credentials now

**Comment by jbritt1** [comment]
First-time login credentials provided to user via DSVA Slack workspace DM at this time.
