### ISSUE TITLE
[FE, PM] My VA - Sign as a Representative: Launch feature to 75%

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#40592]
## Background
Following successful rollout of *Sign as a Representative* to 50% of users, we'll continue with a phased launch of the feature, increasing to a 75% rollout.

## Task
- [x] Flip feature flag to turn it on for 75% of users
- [ ] Monitor analytics post-launch

## Acceptance Criteria
- 75% of My VA users will have the feature enabled in production

**Comment by longmd** [comment]
Bumped to 75%.
