### ISSUE TITLE
QA - Create Regression Test Plans for Current VA.gov Products

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4059]
### User Story
As an engineer working on VA.gov, I want a suite of regression test plans I can use so that I know how to test if functionality I'm building is going to break something else.

### Problem Statement
Right now, all our test cases for different features on va.gov are all over the place. 

## VSP Objective (Q1 & Q2 2020)
O5: All customers comply with the Platform's standards.

## Measuring Success (KRs/KPIs)
Reduction in non-compliance across VA.gov products for at least 5/10 practice areas.

### Assumptions and Hypotheses

We **hypothesize** that  **if** we have a suite of regression test plans around products on VA.gov **then**  it will be easier for new teams to run tests against other functionality
We **hypothesize** that  **if** we have a suite of regression test plans around products on VA.gov **then** less bugs will be introduced because testing will be easier
We **hypothesize** that  **if** we have a suite of regression test plans around products on VA.gov **then** we can get people up and running on the platform faster.

**Comment by pjhill** [comment]
Here is a collection of open bugs in va.gov-team repo (55 bugs at the time of commenting) --
https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by pjhill** [comment]
Did some [analysis ](https://docs.google.com/spreadsheets/d/1Lo7AYuI32en6MN6Mm4L-X3v0xDd9p2DRTh0dLNwQmzw/edit?usp=sharing)about which product to tackle first.

**Comment by pjhill** [comment]
Created a first draft of [Facility Locator regression test cases.](https://dsvavsp.testrail.io/index.php?/suites/view/20&group_by=cases:section_id&group_order=asc)
