### ISSUE TITLE
Request for general information from VSP Platform TLs

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#40600]
Gather general Platform Team information from the TL of each of the Platform Teams. Information requested consists of:

- Team Boards
- Repos. owned or heavily frequented
- Office Hours
- Any development standards documentation followed for the team

Teams done:

- [x] QA Standards
- [x] Console Services
- [x] Analytics
- [x] Design System
- [x] Infrastructure
- [x] Release Tools
- [x] SRE
- [x] Identity

- [x] Platform content
- [x] Governance
- [x] Service Design
- [x] Security

Purpose is to ensure teams have most up to date information related to the items and that we can work to centralize / update in location(s) as needed.

**Comment by little-oddball** [comment]
Initial location of information is here:

https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2167144449/Team+Boards+Repos+Office+Hours+Standards+and+Purpose

But information will be moved as appropriate places are defined.

**Comment by mchelen-gov** [comment]
Can we get this info on their Confluence home page, and then aggregate using Excerpts? (similar to how roster works)

**Comment by little-oddball** [comment]
Added information via excerpt per the request.

https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster

**Comment by troymosher** [comment]
Updated https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2167144449/Team+Boards+Repos+Office+Hours+Standards+and+Purpose with Platform Security information.

**Comment by andreahewitt-odd** [comment]
@little-oddball to check with the 3 remaining teams.

**Comment by little-oddball** [comment]
I reached out to Governance to check about Office Hours the other remaining teams (Platform content and Service Design), look to have the main questions/items answered.

**Comment by little-oddball** [comment]
It was communicated this page was created:

https://vfs.atlassian.net/wiki/spaces/SUP/pages/2290810881/Office+Hours

I grabbed the Collab Cycle hours and added to the Governance Team page.
