### ISSUE TITLE
[BE] Use only candidate api for address validation api

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#4060]
## Background 
Candidate api has now been changed to include all validate api data so calling validate api is no longer needed

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Change candidate api  to include all validate api data so calling validate api is no longer needed
  

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [x] The change has been made and validated by dev.

**Comment by Justin-Pickett** [comment]
@lihanli can you confirm that PR 3642 is working and this ticket can be closed. Thanks.

**Comment by lihanli** [comment]
@Justin-Pickett it's not working because va-profile team rolled back their api https://dsva.slack.com/archives/C7TE0PFTL/p1576607794009000

**Comment by Justin-Pickett** [comment]
was validated by @lihanli prior to VA Profile team rolling back the validation api changes on their end. We will close this ticket. Will open a new ticket once the changes have been implemented by the VA Profile team if needed.
