### ISSUE TITLE
STAGING: Empty request calendar displayed instead of rolling to the next month

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#40612]
Steps to recreate:
1. Log in as Judy Morrison. 
2. Start scheduling/eye care/optometry/VA/Ft Collins. Veteran is dropped into the request flow. 
Business logic: the calendar shows available appointments starting at T+5.
Expected response: The request was initiated on 4/25/22. T+5 business days would be Monday, May 2, 2022. 
Actual response: the system displayed a calendar for April 2022, with all dates greyed out. It should have displayed the May calendar. 

Note: in order to reproduce this issue, you really need to place the order on exactly the right day; I am not able to reproduce it today (April 28).

End user impact: A veteran might see that she can't select a date presented to her and quit. In order to see a selectable date she has to select the Next button in the calendar and this is not obvious.

**Comment by ldelacosta** [comment]
@beth-wodzinski - This ticket is ready to be tested. Thanks!

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this issue was given a **Medium** priority

**Comment by ldelacosta** [comment]
@aarathi-poldass - Waiting for SQA to complete the validation. The changes will be deployed with the 08/02 code. Thanks! 

cc: @JRRoof

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
