### ISSUE TITLE
Conduct business partner discovery, part 2

### ISSUE THREAD

**Issue by MOStudioCarolyn** [department-of-veterans-affairs/va.gov-team#40610]
- [x] Conduct in depth discovery interviews with two or more business partners
- [x] Document discovery in a shareable format

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/9fa58c0a-cf62-4dbd-8618-73d29889b513)

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/c634e61c-31f3-49e7-9800-522063e3d900)

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/dc4d2b3c-d43a-45bf-8e43-e1e863cb7eb5)

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/2aeb8413-098a-4fa7-bca8-252edcdb3f10)

**Comment by tameracorson** [comment]
![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/a5c83b8a-31c7-4edc-bb48-350c3ba3eae8)

**Comment by tameracorson** [comment]
Mikki Northius notes[https://app.zenhub.com/files/133843125/e8a68f48-9522-45d2-a61f-7a03123d2278/download](https://app.zenhub.com/files/133843125/e8a68f48-9522-45d2-a61f-7a03123d2278/download)

**Comment by tameracorson** [comment]
Jeff Barnes Notes

**Comment by tameracorson** [comment]
Samara Strauss notes 
[https://app.zenhub.com/files/133843125/3754ed4c-66a9-42e0-a6cb-0a548c191fe3/download](https://app.zenhub.com/files/133843125/3754ed4c-66a9-42e0-a6cb-0a548c191fe3/download)
