### ISSUE TITLE
Community Care Booked Appointments - Phone Number and Provider's name

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#40621]
## Description
The VAOS application (FE) will need to display the phone number and provider's name when the application is fetching the Community Care booked appointments using V2 endpoints. 

**V0:** 
![Screen Shot 2022-05-03 at 11.03.32 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/8e69780a-7e6f-409c-9567-c70525d8c78d)

**V2:**
![Screen Shot 2022-05-03 at 11.03.47 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/27b2db37-c085-482d-bf0f-6d5830e1710a)

---

## Acceptance Criteria

Given the user is on the VAOS homepage 
When the user clicks on Details for their Community Care booked appointment 
Then user will see the appointment details 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-future) 

### Technical Notes 

- For v0, we can retrieve cc appointment data (which includes the provider phone number) from the following endpoint: `/var/VeteranAppointmentRequestService/v4/rest/direct-scheduling/patient/ICN/#{user.icn}/booked-cc-appointments`

- For v2, when we fetch the appointments list, the returned appt details appear to contain all the provider info including phone number.
Screenshot below are for Community Care appointments, which are the API responses when retrieving the appointment list. Phone numbers and provider's name are outlined in red boxes. 

![Screen Shot 2022-04-28 at 3.48.18 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/30625547-2e9a-4e54-bf26-c7b69b631bca)

![Screen Shot 2022-04-28 at 3.48.54 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3aba13e2-7e20-48d4-931f-2b6857fddc2e)

![Screen Shot 2022-04-18 at 3.49.28 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/d358f237-bd9e-4c41-a6fb-d8dd6c620ad9)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
Tried to submit a CC request, getting an error. Per Marcy's comment, This is a known bug. HSRM for some reason is taking + 30 secs to reply and the call is getting timed out. Thomas will be reaching out to HSRM to work on the VAOSR-3700 ticket. 

![Screen Shot 2022-05-24 at 5.23.53 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2fac39ff-bff7-4ae5-9ca3-e0c01cf8137f)

**Comment by ldelacosta** [comment]
@simiadebowale 

The type of care is not displayed for CC booked appointments.
I tested patient999@id.me in staging and here are my results: 

Requested to be seen on 06/29: ![Screen Shot 2022-05-31 at 2.22.28 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/291b2e16-1a44-4269-95c5-30ed01022278)

When the staff books my CC appointment for 06/15: 
![Screen Shot 2022-05-31 at 3.53.04 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/5af24898-6b3f-44b7-93dc-09fc97988bbe)

**Comment by ldelacosta** [comment]
HSRM information for the provider: 
![Screen Shot 2022-05-31 at 4.08.43 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7ed2f6b7-879a-4631-9b0d-12089e0fac76)

**Comment by simiadebowale** [comment]
![Screen Shot 2022-06-01 at 1.54.33 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/075e2801-2ac1-4518-89e4-bbf339f5774a)
this has been resolved cc: @ldelacosta

**Comment by ldelacosta** [comment]
Validated the changes in staging. No issues reported. Closing out the ticket. 

**Requested a CC appointment**
![Screen Shot 2022-06-02 at 10.03.00 _AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/93d320cb-571e-4570-89fc-1fbf234a4614)

**Booked CC appointment**
![Screen Shot 2022-06-02 at 11.30.22 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/478575ce-805f-480d-8b81-4e2c07dbd862)
