### ISSUE TITLE
QA Feedback - Staging Review - Design System Team - Typeahead search web component

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#40622]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/40215

**Comments:**
- None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- Using arrow keys to navigate through the suggestions causes the entire page to scroll. Is this just an issue in Storybook?

**Consider:**
None

**Comment by andresriveratoro** [comment]
Great catch! This was a problem with the component itself and not Storybook. I've updated `va-search-input` to prevent scrolling the page when navigating through the suggestions.
