### ISSUE TITLE
GIDS: Setup parent/child version relationships for institutions and zip code rates.

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4063]
@dneel-bah commented on [Tue Oct 29 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19877)

As a developer, I need to add a parent / child relationship so that the database is more normalized.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Version table is created.
2. Has_many relationship is established from version to institution.
3. Has_many relationship is established from version to zipcode_rate.
4. Archiver is configured to archive institution and zipcode_rate data.

## Supporting Artifacts:
1. N/A

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/519

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-12-17 at 9.13.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a9cb838c-c46c-4c19-9cf9-f91c1dda66ef)
##
![Screen Shot 2019-12-17 at 9.14.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/445e0437-c97c-4f29-988b-24758366fd0a)

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
In staging. Closing story.
