### ISSUE TITLE
GIDS: Refactor version generation to create a single publishable version

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4064]
@dneel-bah commented on [Tue Oct 29 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19875)

As a developer, I need to refactor the version generation so that duplicate data is not generated on version publication.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The same data set that is created on preview generation is used as the published version.

## Supporting Artifacts:
1. N/A

---

@hughes-dustin commented on [Wed Dec 04 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19875#issuecomment-561781956)

branch: bah-19875
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/510

---

@sonntag-adam commented on [Wed Dec 04 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19875#issuecomment-561796115)

Testing passes QA

**Comment by sonntag-adam** [comment]
Testing passes QA.

**Comment by sonntag-adam** [comment]
In staging. Closing story.
