### ISSUE TITLE
Communication for primary branch migration to 'main'

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#40641]
Problem statement:
VFS and Platform teams need to be aware of the migration of primary branch from 'master' to 'main'.

Create a [communication plan ](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2172715060/Communication+Plan+-+Migrate+Primary+Branch+Names+in+Vets-Website+Content-Build+to+Main+39544)that includes:

- [x] Explanation of what's happening

- [x] Why this change/information is important

- [x] Who does this change impact? How?

- [x] Supporting links and documentation

- [x] Channels of communication

- [x] Required documentation

**Comment by theodur** [comment]
Closing this since the communication plan was completed
