### ISSUE TITLE
SOCKS access for Ritesh Patel

### ISSUE THREAD

**Issue by iriteshp** [department-of-veterans-affairs/va.gov-team#40645]
### Your Name

Ritesh Patel

### Your Email

ritesh.patel@adhocteam.us

### Your Role

Software Engineer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC93YHRBFfAWzZFNg9lD/MjfuFbh8D5ir3l3ZwWLJgXbPS8bo3wxxRHC72E+5j3zMoaPJTBFhPsuQXpVHBvM1SSQ6SrqjCxCyHKz/Mfht0uBjcqibfFfWy5rr+C3FTGakGyubKTbDwsi+BIyW+T8eRYHQD++Za3p8dsMopPYILJ3fAGBpIa7NXMVOOWarKebDUQ4516myUKL3TiRj+Vy8ReM18PiLK/Lb70GALx7gL2gxjztltar+9gVuLAdsf72DJ6bRHcCP65nw3Xf/o27D0oy1gVO4wkgbSQhiwtgK5SNcY+JltbJijnJKmcwujquuA2uKTMrK80q8xU+EhoU5cfx5nvpGN4wvTAYT5Yq9dSh68bo8txHZ/GdlogZqEVkkTsIlOWWsAN3XEJBeSwDCcKcBK+nL6FzVswcXbKtKzhs/DWJR6nrHrJb6m8pPoFWsyt+7lC8VJFyl/0/hdRnjS1V4p5+dW0BmcymJBxciYvQKMvz9nSwgEuWhaZCxFa8zk= riteshpatel@Ritesh-Patel-MacBook-Pro.local

**Comment by rmtolmach** [comment]
@iriteshp Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
