### ISSUE TITLE
[BE] Run Load Tests for vets-api

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40652]
Coordinate with platform teams to run load test for the vets-api subsystem. Refer to [performance test strategy](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/performance-testing)

**Comment by randomsync** [comment]
done. #41142, #41144

**Comment by kanchanasuriya** [comment]
[Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42465) opened with platform team requesting host with dedicated IP for running the load test

**Comment by randomsync** [comment]
load test results: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/performance-testing/results/vets-api-load-test-results.md

**Comment by randomsync** [comment]
We had a discussion with platform infra team and added the outcome here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/performance-testing/results/vets-api-load-test-results.md#update-06292022-discussion-with-platform-infrastructure-team. Closing this ticket.
