### ISSUE TITLE
Protect/Approve automation to add users to dynamo

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#40678]
We need to inject an "approval" step to validate the requesting user's membership of the github organization.

Done when:
- [x] A user submits a ticket and AMT is requested/alerted to review

Note: There is a possibility of automating the department-of-veteran-affairs github org check. This would remove the need for a manual approval step and keep the time spent on this task to a minimum.

**Comment by calquisola** [comment]
@kjduensing , does this apply to utility only?

**Comment by calquisola** [comment]
[PR](https://github.com/department-of-veterans-affairs/access-management-integration/pull/56) created

**Comment by calquisola** [comment]
still in progress. this was on hold due to datadog migration.

**Comment by calquisola** [comment]
this was applied.

**Comment by kjduensing** [comment]
@calquisola what else needs to be done on this?
