### ISSUE TITLE
Monitor IA treejack (#1)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#40689]
- [x] Verify that treejack has successfully launched
- [x] Provide daily update to team on completion and insights
- [x] Report on tree test current state and any preliminary findings during design review and / or Demo 

*tests will stay open for two weeks

**Comment by MOStudioCarolyn** [comment]
Status of Treejack as of Design Review June 9
![Screen Shot 2022-06-10 at 10.24.52 AM.png](https://images.zenhubusercontent.com/62598d5028d5ea49e32f0d98/776a8e8e-bcb2-4b70-8a30-652abb5ca5b6)
![Screen Shot 2022-06-10 at 10.25.26 AM.png](https://images.zenhubusercontent.com/62598d5028d5ea49e32f0d98/10234be0-201e-45b3-a11e-a5e0f430529b)
