### ISSUE TITLE
SOCKS access for Daniel Cloud

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#40705]
### Your Name

Daniel Cloud

### Your Email

daniel.cloud@adhocteam.us

### Your Role

Managing Software Engineer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6tTYt7mx+A5nxiknmHoMPWdXjvpaMERxAHsLg8xdzW7ioCcOc8jFUIC/xSvFyzKpCXejEbBV2KFlWoJEvNzZs2myHnW7XWns1tEFgYDsfNHO0m5JIFwClGk27zvJN4/M80cL1ebH7y/j22OFy43eUExvD7coq9XdIgdbEIVPVkFRV4Y6seyCh/v9luYhKtKCo1LQuZn9imfUliKrW7LwaHSDABPxpp+qAnnxv6AoBdPBRFzWBId2TeMTEz+phdG8uvMp8lRqBabDVLRp6Lk6Kj9VfdI4JhO6i3PbegPQ2c0b4X6MfTWiM7ERVMCFuTybB/km2PS5FPZ3ooOwuS5NCeA66SLCsvxPNmsescmN3QDilHAYyGRNunSXJQ/lpHQIqOw3v0oIYnnDR4qmvvHML/4jowJizvinhxVJmRbi9A/fHcSee8yEdvIF0uLbdMF1mCEYvmVXlF+bjZzm8ww+j7txVMp5Lfob6B62fWuolL3tjXSc3B47VuYmsn/thDpU= daniel.cloud@adhocteam.us

**Comment by rmtolmach** [comment]
Hey @dcloud! Before we can grant you SOCKS access, you'll need to be officially added to the VFS roster, which is done as part of the onboarding described here: https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html. I'll check back on Monday to see if you've been added.

**Comment by rmtolmach** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40711

**Comment by rmtolmach** [comment]
I checked again and saw Daniel was added to the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665). I've kicked off the GH Action.

**Comment by rmtolmach** [comment]
@dcloud Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
