### ISSUE TITLE
STAGING: VCM appointments display provider as "undefined undefined" in VAOS

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#40704]
Steps to reproduce:
1. Create an appointment in HSRM. 
Or, look at the existing appointment for Judy Morrison for 4/29/2022 at 14:30. 
2. Display the appointment and detail in VAOS. 
Expected result: the provider name displays.
Actual result: VAOS displays "undefined undefined" (see screen shot) 

The provider name is being passed in (bold below):

["Audiology","Cardiology","DentalServices","EmergencyCare","Gastroenterology","Gynecology","MentalHealthCare","Nutrition","Ophthalmology","Optometry","Orthopedics","Podiatry","PrimaryCare","SpecialtyCare","UrgentCare","Urology","WomensHealth"],"operating_status":{"code":"NORMAL"}}}}},{"id":"97359","type":"appointments","attributes":{"id":"97359","identifier":[{"system":"http://med.va.gov/fhir/urn/vaos/vvs/id","value":"f256792b-6800-4386-84d2-3156a40b46fb"}],"kind":"telehealth","status":"booked","patient_icn":"1012845331V153043","location_id":"983"**,"practitioners":[{"identifier":[{"system":"dfn-983","value":"520647797"}],"name":{"family":"WODZINSKI","given":["ELIZABETH"]}**,"practice_name":"Cheyenne VA Medical Center"}],"start":"2022-04-29T20:30:00Z","end":"2022-04-29T20:50:00Z","minutes_duration":20,"cancellable":true,"patient_instruction":"","telehealth":{"url":"https://dev.care.va.gov/vvc-app/?join=1&media=1&escalate=1&conference=VAC000419641@dev.care.va.gov&pin=540186&aid=f256792b-6800-4386-84d2-3156a40b46fb#","group":false,"vvs_kind":"ADHOC"},"extension":{"cc_location":{"address":{}}},"location":{"id":"983","type":"appointments","attributes":{"id":"983","vista_site":"983","vast_parent":"983","type":"va_facilities","name":"Cheyenne VA Medical Center","classification":"VA Medical Center (VAMC)","timezone":{"time_zone_id":"America/Denver"},"lat":39.744507,"long":-104.830956,"website":"https://www.denver.va.gov/locations/directions.asp","phon![undefined.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/596f66ab-d17a-46f8-83e3-5226befe446b)e":{"main":"307-778-7550","fax":"307-778-7381","pharmacy":"866-420-6337","after_hours":"307-778-7550","patient_advocate":"307-778-7550 x7517","mental_health_clinic":"307-778-7349","enrollment_coordinator":"307-778-7550 x7579"},"physical_address":{"type":"physical","line":["2360 East Pershing Boulevard"],"city":"Cheyenne","state":"WY","postal_code":"82001-5356"},"mobile":false,"health_service":

**Comment by beth-wodzinski** [comment]
@ldelacosta new issue

**Comment by ldelacosta** [comment]
@beth-wodzinski - This ticket is ready to be tested. Please let us know if you have any issues. Thanks!

**Comment by beth-wodzinski** [comment]
Tested and passed. 

@ldelacosta this is good to go.
