### ISSUE TITLE
[FE] On-site Notifications: Allow for display of multiple notifications

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40710]
## Background
Per discussion in #36184 we need to change the way we show multiple notifications. For details on decision to show multiple notifications as individual see [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36184#issuecomment-1113324707).

## Tasks
- [ ] Update FE to show multiple notifications (when necessary) as individual on-site notifications with a timestamp
- [ ] Test

## Acceptance Criteria
- We show multiple on-site notifications as individual notifications with timestamps that reflect the time the notification was triggered.

**Comment by tmitchellgcio** [comment]
It sounds like we aren't pulling that information from VA Notify yet then so we will have to wait for that information as there wouldn't be a way to tell if it's a debt notification or otherwise or what type of debt notification it is exactly.

**Comment by Samara-Strauss** [comment]
**PM note**: Taylor has finished the work on this ticket, but we can't validate the work right now -- and maybe for a few weeks -- until the backend, devops, and VANotify work is done, AND until the backend (DMC) team has sent us data so we can QA certain users. Therefore, this will have to be validated in QA.
