### ISSUE TITLE
CT116: Remove Prod Flags for UAT/Design Feedback

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4071]
@dneel-bah commented on [Thu Dec 05 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20064)

## Description
This issue implements functionality covered in the following story: 
- #20013

## Original PR(s)
These PRs are the original code that is currently behind a prod flag that is being lifted by this PR. 
- department-of-veterans-affairs/vets-website#11140

## Testing
Local Testing

## Assumptions
1. This functionality has been approved to go to Production as of 12/10/2019. 

## Acceptance Criteria: 
- The functionality outlined in #20013 is now available in the Production Environment.

**Comment by desireeturner** [comment]
This should be available on Production.

**Comment by desireeturner** [comment]
@amyknox @ccruzgra @tmcmurdo this is available on Production for you all to do one last review. If everything appears as expected, please close out this issue. Thank you!

**Comment by amyknox** [comment]
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/20013

**Comment by ccruzgra** [comment]
@desireeturner Closing this story. Will revisit pending updates in production to the Contact Details accordion in January as the supporting file isn't in yet until 12/23. Will file any defects then, if needed.
