### ISSUE TITLE
[PM] Onsite Notifications: Determine analytics strategy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40712]
## Background
We need to think through the analytics strategy for on-site notifications MVP. Specifically we need to determine if we need to remove the debt alert in the payments and debts section of My VA before notifications launch in order to be able to effectively track activity from on-site notifications.

## Tasks
- [x] Investigate whether we can track clicks into the debt tool from the on-site notifications separately from clicks into the debt tool from the payments and debts section. _(if we can't track them separately then the link in the p&d section would need to go)_
- [x] Begin drafting analytics request for on-site notifications ([success metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md#measuring-success) for reference)

**Comment by ericasauv09** [comment]
At the analytics office hours they said it is possible to track both debt link clicks separately. This is also applicable to any future notifications we add. We will just need to submit an analytics implementation issue. 

Cc: @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Great! This will make things nice and easy since no changes to the Benefit payments & debts section are required.

**Comment by ajakabcin** [comment]
Spoke with Samara yesterday about what we want to track and Erica hunted down the answers we needed at last week's analytics office hours.
