### ISSUE TITLE
Staging: Type of Care Shows Blank/No Data for TMP Appointments

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#40716]
### ** NEW WRITE UP:  COMPLETE REVISION OF THIS DEFECT.** 
After analysis, this defect is being scaled back and is only concerned with TMP appointments missing type of care.  

1. VAR-Resources never displayed Type of Care for TMP appointments.  With the new VAOS service, Front End put in the Type of Care label but it was displaying as blank for the user.  
2.  Front end will remove the type of care from displaying for TMP appointments.  If there is a need to display type of care, then an enhancement can be entered for the front end. Marcy will follow up with OVAC on this.  

So from the original defect, we are only concerned with this appointment.   Alfred.castillo@id.me:  Tuesday May 9, 2022 @4 PM- MISSING TYPE OF CARE.   

### **OLD WRITE UP - SUPERCEEDED BY THE ABOVE WRITE UP**
There are three sources for VAOS appointments:  1 )  HSRM- Community Care 2) Video Visit Service (which is fed by Telehealth Management Portfolio (TMP)and Virtual Care Manager (VCM) and  3) VistA Scheduling Service. 

All of these services feed into Mobile Appointment Service (MAS). MAS is used by VAOS.  

1. IGNORE THIS WAS BECAUSE SITE 913 WAS NOT IN THE AWS STAGING CDW INSTANCE.  Alfred.castillo@id.me:  Tuesday May 3, 2022 @9 AM- MISSING VA Facility/Site Address  & Phone.   Ask Brad is this because this is site is 913 and we don't have 913 in Mock CDW?  https://veteran.apps-staging.va.gov/cdw/v3/facilities/913/clinics?pageSize=0.  {"data":[],"pageCount":0,"currentPage":0,"pageSize":0}

2. KEPT IN, SEE ABOVE.  Alfred.castillo@id.me:  Tuesday May 9, 2022 @4 PM- MISSING TYPE OF CARE.   Probably another TMP appointments.  See issue #1 missing type of care.  

4. THIS WAS JUST A REFERENCE RECOD. INGORE.  Alfred.castillo@id.me:  Weds May 4, 2022 @8 AM;  NO DATA ISSUES.  Just a reference so you can see that a record should look like.    

5. MARCY WILL TEST AGAIN AND LOG A SEPARATE GITHUB TICKET IF NEEDED.  THIS APPT WAS A VISTA TELEHEALTH APPT, NOT A TMP APPT 
 Judy.Morrison@id.me:  Tuesday May 12, 2022 @10 AM- MISSING TYPE OF CARE See issue #1 missing type of care.  This is a VistA appointment that I made in Chyshr in a clinic that had a telephone stop code. Note there is an associated issue where the response does not contain a phone only indicator/flag. That associated issue is NOT related to the missing type of care.

![MissingApptsDetails.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/f948fd64-82cd-4e71-9bb3-536b257fca6f)

**Comment by ldelacosta** [comment]
@JRRoof will follow up to see if we need to do any research on this ticket.

**Comment by marcynadeau** [comment]
@ldelacosta @JRRoof We need to discuss.  This will need to be fixed before deployment.

**Comment by marcynadeau** [comment]
@simiadebowale Updated the defect. Hope it makes sense now.  Please let me know if this works with what you and I discussed on Scrum of Scrums.

**Comment by ldelacosta** [comment]
@marcynadeau - I created a bug ticket to remove the type of care label for TMP appointments #42071. Instead of having two tickets to track the work #40716, I will assign this ticket back to you and if you can validate #4. If item #4 is a bug, please open a new ticket with the details. Thanks!

**Comment by marcynadeau** [comment]
Closing this ticket.  On issue #4:  Type of care is NOT displaying and this is due to back end issue because there is no stop code (service_type).   This type of telehealth appt is coming from VistA and service type (stop code) may be able to be sent.  Will log a VAOSR Jira ticket to see if possible to send the service type (stop code).  ![VistATelephoneClinicAppt.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/de951ec0-b1ef-4b98-b92c-9c0ada4ccf43)
