### ISSUE TITLE
Determine location for Service Accounts listing

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#40726]
In talking through gathering information related to Service Accounts and getting that initial list of them, it was also requested that we identify a central as possible location where these would reside for devs, etc. to be able to easily locate details and other information about them. In that discussion, it was mentioned that possibly the Console UI might be a good location due to the catalog capability it has.

The goal would be to work with OCTODE to identify the location that is the most ideal and to get that documented and actioned on.

**Comment by mchelen-gov** [comment]
Currently: https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2156724460/Platform+Managed+Accounts

**Comment by little-oddball** [comment]
Been moved to here based on feedback, etc. from Govt.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/service-accounts.md
