### ISSUE TITLE
Update pension rates pages with new numbers from SMEs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#4073]
## User Story or Problem Statement
As a pension beneficiary, I want to know the most recent and correct pension rates information.

## Goal
Changes were already made by stakeholders to update rate information in December. However, more changes need to be made (see Word doc in this issue), which will be done in Drupal by content team and then shared with stakeholder with a preview link. 

## Acceptance Criteria
- [x]  Information has been updated in Drupal
- [x]  Preview link sent to SMEs for approval

[https://app.zenhub.com/files/133843125/31f358dd-86b9-4de8-bfbb-900e67baf96e/download](https://app.zenhub.com/files/133843125/31f358dd-86b9-4de8-bfbb-900e67baf96e/download)
[https://app.zenhub.com/files/133843125/8d2ce5cd-206a-4ca1-a10f-88252d5b78d9/download](https://app.zenhub.com/files/133843125/8d2ce5cd-206a-4ca1-a10f-88252d5b78d9/download)

**Comment by RLHecht** [comment]
@AnneHurley I put in all the new info from the Word docs and am just waiting on the text to include for the pension penalty rate info.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Also Slacked you - can you tell me who the Pensions SMEs are, and I will reach out to them asap to get this updated info? thanks

**Comment by jenniferlee-dsva** [comment]
Hi @AnneHurley - looking at the Word doc that Randi attached, this looks like the content for the pension  penalty rate changes. I believe you were already working with Angie Smith about this. If Angie is not the SME, you can ask Misty, Adrianne, and Sandy (and CC myself) via email. (But I'm pretty sure it's Angie.)

**Comment by jenniferlee-dsva** [comment]
@RLHecht @Karak888 @AnneHurley for these types of ongoing ad hoc content updates (that are not part of a specific product launch or update, like VAOS or new HLR tool), please be sure to add it to the "Website content maintenance" epic. 

It helps me and DEPO have better visibility into all the ad hoc/one-off tickets (that are actually not random but part of normal ongoing work for the team). Thank you.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva @RLHecht  I'll follow up with Angie right now. We just need that definition of what the penalty amount really means.

**Comment by AnneHurley** [comment]
@lunascoop  @Karak888  - Selina, can you take a look at the ^ word docs attached to get up to speed. I had a question about what the "Pension Penalty Amount" dollar amount reflected. I will also forward you two emails Angie Smith sent in answer to that question. Let's talk it through together on Wednesday.

**Comment by AnneHurley** [comment]
@RLHecht  @lunascoop  - This is an instance of where the Team Site page is still live in parallel with the VA.gov site. 
Our page: https://www.va.gov/pension/veterans-pension-rates/ 
Legacy page: https://www.benefits.va.gov/pension/current_rates_veteran_pen.asp

What do we need to do, to redirect the second page above to the first, and have that second one retired?

I vote to do that and make the page live, even while Selina and I are still figuring out with Angie exactly what the "maximum pension penalty" figure means, because it's now December and people are searching for rates, and they are being served 2 pages in Google. 
@jenniferlee-dsva  FYI and @Karak888

**Comment by Karak888** [comment]
This still needs to be updated as it was in Drupal in June so need to review what happened. Pension Penalty to be cleared up with Angie.  @AnneHurley @lunascoop

**Comment by mnorthuis** [comment]
I just mentioned this page along with the survivors current rates page in the redirect ticket.  See #4231 for reference.  If you want it redirected it can be added to that ticket or you can wait and handle it separately.

**Comment by RLHecht** [comment]
@AnneHurley These pages are now published. We are still awaiting the penalty rate info so should leave this ticket open?

**Comment by AnneHurley** [comment]
@RLHecht I just emailed Angie, so let's wait till tomorrow, in the hopes that I can chat with her today or tomorrow to clear up the penalty sentence. If I can't connect with her by then, I would say close the ticket, and I'd open a new small one with just the additions of penalty rate info, once I understand how to message it. 
Sound ok?

**Comment by AnneHurley** [comment]
[Pension updates dec 2019-ah.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/3984956/Pension.updates.dec.2019-ah.docx)

**Comment by AnneHurley** [comment]
@RLHecht @peggygannon   - I made these edits in Drupal. Could one of you review and move it along if you feel it's ready?

Link: https://prod.cms.va.gov/pension/survivors-pension-rates

In Q&A section, 3rd question and answer. 

I thought I'd slacked you both but not seeing it.

**Comment by RLHecht** [comment]
@AnneHurley I reviewed this page, made a few copy edits and published the page. Moving to validate. @Karak888

**Comment by Karak888** [comment]
@RLHecht does this need to be approved by a SME?

**Comment by RLHecht** [comment]
@Karak888 I believe Anne had gone over this with the SME when she added this question. But I'll put back to draft form until she can confirm tomorrow. The rest of the page had been published and we were waiting on clarification on this one question.

**Comment by AnneHurley** [comment]
@RLHecht  @Karak888  I met with Angie and Robert on Friday and together we came up with wording to clarify the penalty issue. They also agreed to remove that dollar amount as it was confusing. I updated the page in Drupal, and hope it looks all right. As long as Randi or Peggy has reviewed my changes, it should be good to go live and redirect.

**Comment by RLHecht** [comment]
@AnneHurley @Karak888 This page is now published. Will close ticket once it's validated on live site.

**Comment by RLHecht** [comment]
@AnneHurley Was this new pension penalty rate info supposed to go on both the Survivors Pension Rates page as well as the Pension Rates for Veterans page? We reference the second one in a comment earlier in this ticket but we only made the change to the Survivors one. Here's the node ID for the Veterans one, which we haven't changed: preview-prod.vfs.va.gov/preview?nodeId=591

**Comment by AnneHurley** [comment]
@RLHecht  The SMEs added the penalty info only to the Survivors page, so I believe it's correct only on that one. Let's publish but I'll also check with Angie if that info shouldn't also be on the regular Veterans pension page.

**Comment by RLHecht** [comment]
@AnneHurley sounds good. The changes to the survivor pension page is now live so I'll close this issue and you can confirm with Angie that we don't need to also add it to the other one. Thanks! @Karak888
