### ISSUE TITLE
[FE] Research 10-10EZ Applicant Status API usage

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#40752]
We need to locate all of the areas in the 10-10EZ app that call the `/health_care_applications/enrollment_status` endpoint. We currently think the intro page is the only location, but need to verify that there are no other areas in the app where that function is available.

**Comment by longmd** [comment]
@Dene-human , I can confirm that the enrollment status is only available on the Introduction page of the app.

**Comment by Dene-human** [comment]
So quick! Thank you @longmd ! You're totally right, this is one half of #40377 Sorry about that, I forgot I had made that ticket awhile back.
