### ISSUE TITLE
Engineering Leadership requires a charter

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#40775]
In a previous meeting, it was requested that a charter for the Engineering Council was to be created. This task was defined as an Action Item to be completed.

Here is a link to the notes from the specific meeting the action item was created:

https://vfs.atlassian.net/wiki/spaces/ECP/pages/2151972907/2022-04-06+Meeting+notes

**Comment by mchelen-gov** [comment]
Renamed "Engineering Council" -> "Engineering Leadership"

**Comment by little-oddball** [comment]
WONT FIX
