### ISSUE TITLE
10-10CG Mulesoft Integration Phase 2: Asynchronous Submission

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#40794]
Introduce the ability to asynchronously process form submissions in the event that the initial call times out and/or cannot be processed in the normally allotted time.

We will need to make a single call with the data **and** the attachment.  We will also need to revise the Confirmation message so that the language is not misleading the applicant.  The message will confirm that the applicant has submitted the application, but does not confirm that the application was received or accepted.  We will also revise the Next Steps language to indicate that an email will be sent within 24 hours after receipt of the application.

**Comment by hdjustice** [comment]
All tickets are closed, the code has been deployed since 9/23/22 and have had successful results.  Closing this epic
