### ISSUE TITLE
SOCKS access for Helene McCarron

### ISSUE THREAD

**Issue by helene-mccarron** [department-of-veterans-affairs/va.gov-team#40798]
### Your Name

Helene McCarron

### Your Email

helene.mccarron@thoughtworks.com

### Your Role

Developer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzZSMU49VL2HjGMcUJpV13y5lyNJifeHtXCkyyCdqxcLL482pt9QxpHzJMdTEu22Zx9H4IRnj9pokb7Wky9wpT1WRnSUJF7s2uiLf44QmR6h2MwpVaX772+fGa/SVX6YALBwG1G2iPwuqW4x4bQL2zfRD3HJ7X1G1ILNqX1O7ERtaUOz4pTD5iSuQvN/tvBSShz5nNZQd48EUDC6xE0N685nrL8b3uRgSuGRVER5rPVTF2bgMbYcIX2PM4h5bKH311A/ThZ0+TQ9h8TqHHC1IYT0bqnhZpJcBf3LSs3GgiEXGji1F6CqAjRIAQSPnr5+nhgqw5eZvV5DkNa7VQ595mWHNXi0YWG4yWfxWWQAVObkuuiuf/TSFxaokvg59JF6Xov8u9mGa8aoTlvnSOYAszpS9zLSbwef7z3NuM50Ho0CK5CFFwHS72GNw5fLfTmVUUeTn64gCerQPsHT2F3m7i5kVlKA57xqLtSfl5dgWCEMUCfueqxMeJkMmEcKiB6Yk= helenemccarron@Helenes-MacBook-Pro.local

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
