### ISSUE TITLE
10-10CG Mulesoft Integration

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#40791]
**Description**
The integration with Mulesoft will give the 10-10EZ application the ability to asynchronously process submissions.  While the goal is to immediately process any submission that is made, this integration will allow for handling any unexpected delays/timeouts, meaning users will no longer need to manually submit their forms in the event their application is not immediately processed.

**Current State**
Right now, if an application times out during submission, the user must either manually print out the form and submit it that way, or fill it out and attempt to submit again at a later time.

**Problems**
We are currently unable to asynchronously process requests, so if the original call fails, then the whole process must either be started again or completed manually.

**Outcomes**
Reduce the amount of manual submissions required.
Reduce the number of times the form is filled out multiple times.
Allow us to handle submissions that would otherwise error out.

**Phases**
Allow asynchronous application submission

**Opportunities**

**Comment by hdjustice** [comment]
This work was implemented successfully 9/23/2022.  
![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/bf60a913-ba79-43e9-ad3a-03bfaa88870f)
