### ISSUE TITLE
Setup Health monitoring of service

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#40796]
Starting a list of the items we should monitor to determine current health of SiS:

- [x] 1. Outbound return rate by context: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696705833363&to_ts=1696878633363&live=false&tile_focus=4000704399837860
- [x] 2. Inbound success rate: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696705832961&to_ts=1696878632961&live=false&tile_focus=3293629744801296
- [x] 3. Outbound return rate (overall): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696705832967&to_ts=1696878632967&live=false&tile_focus=1994891441732101
- [x] 4. Loa1 and loa3 stats ssoe: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696705983859&to_ts=1696878783859&live=false&tile_focus=8457162644452883
- [x] 5. Ial1 and ial2 stats ssoe: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696705983864&to_ts=1696878783864&live=false&tile_focus=1538425627072732
- [x] 6. Logingov success login rate:https://vagov.ddog-gov.com/dashboard/e3q-6kp-9r4/vagov-identity-stats-public?refresh_mode=sliding&from_ts=1694289082113&to_ts=1696881082113&live=false&tile_focus=1923774624262032
- [x] 7. Idme success login rate: https://vagov.ddog-gov.com/dashboard/e3q-6kp-9r4/vagov-identity-stats-public?refresh_mode=sliding&from_ts=1694289082113&to_ts=1696881082113&live=false&tile_focus=1923774624262032
- [x] 8. Mhv success login rate: https://vagov.ddog-gov.com/dashboard/e3q-6kp-9r4/vagov-identity-stats-public?refresh_mode=sliding&from_ts=1694289082113&to_ts=1696881082113&live=false&tile_focus=1923774624262032
- [x] 9. Dslogon success login rate: https://vagov.ddog-gov.com/dashboard/e3q-6kp-9r4/vagov-identity-stats-public?refresh_mode=sliding&from_ts=1694289082113&to_ts=1696881082113&live=false&tile_focus=1923774624262032
- [x] 10. Latency monitor of mhv response: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=paused&from_ts=1697546305733&to_ts=1697560705733&live=false&tile_focus=234628508901688
- [x] 11. Latency monitor of idme response: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=paused&from_ts=1697546305733&to_ts=1697560705733&live=false&tile_focus=234628508901688
- [x] 12. Latency monitor of logingov response: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=paused&from_ts=1697546305733&to_ts=1697560705733&live=false&tile_focus=234628508901688
- [x] 13. Latency monitor of dslogon response: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=paused&from_ts=1697546305733&to_ts=1697560705733&live=false&tile_focus=234628508901688
- [x] 14. Oauth requests (SiS): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714210343&to_ts=1696887010343&live=false&tile_focus=4190774892194225
- [x] 15. Oauth responses (SiS): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714210343&to_ts=1696887010343&live=false&tile_focus=4190774892194225
- [x] 16. Oauth percent (requests vs responses) (SiS): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714210343&to_ts=1696887010343&live=false&tile_focus=4190774892194225
- [x] 17. Token health (token success numbers compared to callbacks): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714210343&to_ts=1696887010343&live=false&tile_focus=4190774892194225
- [x] a. Number of tokens generated
- [x] i. Total: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714210343&to_ts=1696887010343&live=false&tile_focus=4190774892194225
- [x] ii. By CSP: we dont have type in tokens
- [x] b. Number of tokens revoked: 
- [x] i. Total: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714580885&to_ts=1696887380885&live=false&tile_focus=8199666700020607
- [x] ii. By CSP: we dont have type in tokens
- [x] c. Number of tokens refreshed
- [x] i. Total: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714580881&to_ts=1696887380881&live=false&tile_focus=8611618024904424
- [x] ii. By CSP: we dont have type in tokens
- [x] 18. Authorize endpoint health
- [x] b. latency: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696714768127&to_ts=1696887568127&live=false&tile_focus=2204500936108892
- [x] 30. Introspection endpoint health
- [x] b. latency: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696716458430&to_ts=1696889258430&live=false&tile_focus=965442867907498
- [x] 33. Revoke endpoint health
- [x] b. latency: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696716458418&to_ts=1696889258418&live=false&tile_focus=1462894390666024
- [x] 36. SiS Logout
- [x] b. latency: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?refresh_mode=sliding&from_ts=1696716458482&to_ts=1696889258482&live=false&tile_focus=7592329839329091

**Comment by alyssagallion** [comment]
Reviewing if already completed work. Working on SiS doc.

**Comment by joeniquette** [comment]
all monitors completed.

Next up:

- [ ] create monitors for each usip client
- [ ] create monitors for latency measures (authentication timing) for each CSP
