### ISSUE TITLE
[UX] Create Template for Documenting Feedback from Site Calls 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40804]
## Background Information
From Kristen - I spoke with Chris Horton today about documenting feedback from the daily calls with the sites. It isn’t documented in a standard fashion anywhere. We (Chris and I) discussed adding a section for this within the GitHub [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research) that we already have, so all feedback will be in one place. Chris was also hoping to have a template that anyone on those calls could fill out and submit to the research folder. We need a ticket to create this new template and GitHub section. We will also need to share it with the others who are on the calls with the sites (Chris, Stephen, Patrick, etc).

## AC
- [ ] Create template, which should include this information
    - Who1: from whom did the feedback come (facility, person, title/role)
    - Who2: who captured the feedback 
    - What: details of the feedback
    - Why: what is the value to the Veteran
    - When: when was the feedback provided
    - How: how was the feedback delivered (e.g. site call, email, Teams channel)
    - Links & Attachments
- [ ] Add template to  [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research) 
- [ ] Share with Chris, Stephen & Patrick

**Comment by kristenmcconnell** [comment]
Here is the link to the template that was created: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/site-feedback/template.md

The folder where this information is to be housed is: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/site-feedback
