### ISSUE TITLE
Platform Console UI - Promotion to higher environments (EKS) 

### ISSUE THREAD

**Issue by Matth-Ng** [department-of-veterans-affairs/va.gov-team#40809]
## Summary
The purpose of this template is to capture requirements for onboarding a software application to the Platform's delivery infrastructure. 

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

### Guidance
- Please fill out the sections below with as much info as possible 
- If you don't have info or know the answer to a given prompt, _it's okay to leave it blank_
- The Infrastructure Team will assist you with gathering requirements _and_ performing key setup and configuration tasks 

---

## Description of application
_Please provide a brief description of the application, ie What does it do? Who does it serve?_

Our application is built on the premise to provide a place for all VFS teams to do their core tasks

### Basic info:
**Team Name:**   
Console UI
**Application Name:**  
Platform Console UI
**Functionality:**  
Place for VFS teams to perform their tasks
**Language/Stack:**  
Backstage/React/TS
**Ports/Networking needed:**  
3000, 7007
**Other infrastructure needed:**  
RDS, REDIS

### Background/Context/Resources
_Please link to an initiative or supporting documentation that desribes the need and purpose of the application_

https://vfs.atlassian.net/wiki/spaces/CUI/pages/2048950331/Product+Outline+-+Console+UI+MVP

### Technical Notes
_Additional technical info that describes the desired setup and configuration_

---

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] **GitHub repo:** https://github.com/department-of-veterans-affairs/platform-console-ui
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   
_Requesting team; Infrastructure Team can assist_  
- [x] **Dockerfile:**  https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/Dockerfile
_Requesting team; Infrastructure Team can assist_  

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions**, ie `svc-gha-team-name` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS Elastic Container Registry (ECR) repository for the app container:**
  - 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/platform-console-ui
- [x] **Automation to release and tag the app's GitHub repo with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation. 
_Requesting team; Infrastructure Team can assist_  
- [x] **Kubernetes manifest in YAML, Jsonnet, or Helm Chart** in `vsp-infra-application-manifests`
  - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/528
  - Still need to fix some things
- [x] **Kubernetes detect and update application** in `vsp-infra-applications-manifests` | [Environments](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/argocd-apps)  
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to update the Kubernetes manifest** when a new version of the app's container is pushed to ECR | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/update-manifests.yaml)  
_Requesting team; Infrastructure Team can assist_

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app**  
  - [/dsva-vagov/platform-console-ui](https://console.amazonaws-us-gov.com/systems-manager/parameters/dsva-vagov/platform-console-ui/dev/DB_PASSWORD/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:console-ui)
- [x] **AWS SSM Parameter Store parameters that the app needs to run,** ie `/dsva-vagov/team-name/env/secret-name` | [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)  
_Requesting team_

---

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by Matth-Ng** [comment]
Manifest file is in a PR, but that needs to be updated once the EKS, RDS, and Redis are created

**Comment by Matth-Ng** [comment]
I've created some essential Parameter stores that my team needs for the utility already, If they need to be removed let me know

**Comment by Matth-Ng** [comment]
AWS service account for GitHub actions, AWS ECR Repo - was set up as part of ticket #36494

**Comment by jhouse-solvd** [comment]
@Matth-Ng & @ericvoshall - Thanks for filling this out. Is this to set up the Console UI in higher environments, ie Staging?

**Comment by Matth-Ng** [comment]
@jhouse-solvd yep, we need utility, staging, and eventually prod

**Comment by jsgarmon** [comment]
I've promoted everything from dev into staging and utility. Please test and close if all looks good.

**Comment by jhouse-solvd** [comment]
@jsgarmon - Do you know what's needed to get the application running behind the URL "https://platform-console-ui-utility.vfs.va.gov/"? Is DNS record creation automated as part of this process? 

Thank you for any info you can provide.

**Comment by jsgarmon** [comment]
The URL is setup using the externalDNS API, which I've seen they've done [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/platform-pst-console-ui/backstage/utility/external-dns.yaml#L7). We just need to get this app added to Argo for utility, and once synced it will be created.

**Comment by jsgarmon** [comment]
@Matth-Ng : there's no parameter `/dsva-vagov/platform-console-ui/utility/BACKEND_SECRET`. Please either create the parameter or update the manifest to not point to it. https://platform-console-ui-utility.vfs.va.gov is created but pod is failing to launch.

**Comment by jsgarmon** [comment]
Looks good:
all green: https://argocd.vfs.va.gov/applications/platform-console-ui-backstage-utility?resource=
site up: https://platform-console-ui-utility.vfs.va.gov/

**Comment by jhouse-solvd** [comment]
@jsgarmon & @Matth-Ng - Are there any other tasks that can be marked as completed above? Thank you both!

**Comment by jsgarmon** [comment]
I'm out this week, but maybe @mleclerc00 or @ph-One can help you out

**Comment by ph-One** [comment]
I'll look into this in the morning

**Comment by ph-One** [comment]
You created a certificate issuer named, "selfsigned-console-ui" but are requesting a certificate from an issuer named, "selfsigned". As soon as I modified the certificate to use "selfsigned-console-ui" everything created as expected. I suspect this issue happened in other environments and someone messed with it enough that it started working.

Once the secret for the cert is generated, it will not make another request, so the error "goes away" until the next time the cert needs renewed, in which case it will throw another error about requesting a certificate from an issuer that does not exist.

![image](https://user-images.githubusercontent.com/1580012/170482202-f9eee824-56fb-402d-afbf-262e4b705971.png)

![image](https://user-images.githubusercontent.com/1580012/170482267-634f05d2-8fe2-4f9d-913d-bdcf7fb65213.png)

![image](https://user-images.githubusercontent.com/1580012/170482426-f448c79d-4f9c-4f54-a8d4-b198845d311f.png)

![image](https://user-images.githubusercontent.com/1580012/170482491-44bc6268-a580-4b85-8be0-664ecd3293f6.png)

---

I would go back and make sure that each certificate is correctly set to use the name of the certificate issuer. You can test that this is all working by deleting the secret that contains the cert, and then deleting the certificate object and letting it recreate the secret.

![image](https://user-images.githubusercontent.com/1580012/170482803-ed59f8eb-047e-4787-8457-24cc879e0462.png)

**Comment by ph-One** [comment]
That is a correct assumption that Staging is only temporarily fixed. You still need to update the manifest files the same as dev and utility.

**Comment by mleclerc00** [comment]
https://platform-console-ui-staging.vfs.va.gov

is all set

**Comment by jsgarmon** [comment]
I get `NET::ERR_CERT_COMMON_NAME_INVALID` for the staging site, but not for dev or utility. Anyone know why?
![image](https://user-images.githubusercontent.com/47490730/172864361-047b4e38-f19e-4712-9f4d-a50d6fc45c3b.png)

**Comment by mleclerc00** [comment]
staging is still using the tugboat cert 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/76792875/172901010-3d3892e6-50f0-46b3-b6d9-c06820938584.png">

dev and utility are using the vfs cert
<img width="462" alt="image" src="https://user-images.githubusercontent.com/76792875/172901168-d28a3f2b-9bb8-43e1-9dac-7132ba98c310.png">

**Comment by jsgarmon** [comment]
Closing this as staging appears to be working. Please open a separate ticket to promote to production when ready.

**Comment by jsgarmon** [comment]
load balancer cert needed updating, working now

**Comment by jhouse-solvd** [comment]
@ericvoshall & @jsgarmon - It would be awesome if you can provide notes in #43550.  _(ie perspective or lessons learned)_ related to promoting an application in EKS to higher environments. 

Your feedback will help create a streamlined experience as part of the Platform Infrastructure team's Q3 initiative.
