### ISSUE TITLE
SOCKS access for Zach Park

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#40817]
### Your Name

Zach Park

### Your Email

zach.park@agile6.com

### Your Role

UX designer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXYH7teWYlvgpNcLrjKk+IQIbuVs4NlpuqgyQGZlYmpZSNIRZmXlNE4SKpn7nm/XuRdIQ7d1yJqAJhVgDDdca4umUYqkwtfKUukoYw/uGv5MbG0aH3k79Clu6sdGVlvyNAh7IkYcXN9omg4fmRCsJwKKnObfF3cCJ1wViLyKlaUw5suLnUUxfqYwxetCg/h9aaf/TYgpN51hAZVevuVoEQxuq+w+AUmIvIhtKI9oPspZYiciyh0ynbj3P0McNR33pGMFpHTOWQX2pRJoi4upn5Aw9vMyYRz0PPTyQHpSYRQwgJ6ll1KU95w+ih47jCwLrI6cmMq1rvlL9Vh9gtd8OTKuum3F5t1CeQM0FKRtQE7CmffpRxmIvNHC+774ZL/VPOstIhszxbjo7KwByqpZMau/iixeTEOWBXVwHwKH1+ZQEBH8ym7AKFPOIUzdoMSY15aPJZ6P067voqipMxkCg+ckIy6LEZG4Q8Z2iLjbzmFiRJexu0Kt16dP0/wrb3lN0= zachpark@Zachs-MBP-2.san.rr.com

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
Located in VFS Team Roster, working this now. @zach-park, could you also comment here with your PM and PO names/email addresses as time allows please for tracking?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
