### ISSUE TITLE
Add a direct link to TUD somewhere in the TUD documentation

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va.gov-team#40818]
### Description
_Alternatively, if there is a direct link and I missed it, please mentally change the title of this to "make the direct link to TUD more obvious in this document"_ :)

I expected to find a direct link in the first paragraph of the "Accessing the Test User Dashboard" section.

TUD is a tool that the mobile testing team is going to be using very infrequently (likely every few months), so I figured I'd rather come back to the standard documentation as a jumping off point when I want to access it, just in case things have changed. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html

**Comment by lianilychee** [comment]
@pjhill @JoeTice flagging this for you two, to refine in your backlog as necessary.

**Comment by pjhill** [comment]
A direct link has been added -- thanks for pointing this out!
