### ISSUE TITLE
[BE] Onsite Notifications: Provide BE support for on-site notifications build

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40815]
## Background
As Taylor continues the on-site notifications build and connecting the frontend and backend he will likely need some BE support from Tom. Capturing that work here for capacity.

Work with Evan Parish and Kyle MacMillan to configure API keys.

## Tasks
- [x] Support Taylor is needed on on-site notifications build/ frontend and backend connection

**Comment by tpharrison** [comment]
@tmitchellgcio The `id` and `type` fields in the swagger doc are part of the JSON API specification.  The `type` is used to describe the type of resource being returned, so in this case it should always be `onsite_notifications`.  So I'm not sure this is the field you're looking for.  If you need a type, it should be in the attributes section of the response, but it's not currently there.  Let's meet to discuss this further.

**Comment by tpharrison** [comment]
@tmitchellgcio Currently, there is no `type` field.  The onsite notifications model consists of 3 attributes: `template_id`, `va_profile_id`, and `dismissed`. See ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/35144.

**Comment by tpharrison** [comment]
@ajakabcin I'm working with Evan Parish and Kyle MacMillan to configure API keys so I'll capture the work in this ticket.  

I'll probably update some of the technical documentation around security since Evan and Kyle are new to this project as well.  I'll keep you updated as things progress.

**Comment by tpharrison** [comment]
@ajakabcin @Samara-Strauss - I spoke with Evan and Kyle (from VA Notify) this morning and they brought up a valid concern over the authentication process that is currently in place for onsite notifications.

In short, some additional fields need to be added to the token that is used to authenticate requests to the vets-api.  This isn't a large effort (2-3 points), but it will need to be done by 5/17 or it'll start blocking the VA Notify team.

I'm assuming I should start working on this now, but want to check with you first.

Also, I can continue to use this ticket or open a new one.  Let me know what you prefer.

**Comment by ericasauv09** [comment]
@Samara-Strauss I created ticket #41268 for sprint 74
