### ISSUE TITLE
[UX] Develop Research Roadmap

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40820]
## Background Info
I talked to Ben and Nira quickly this morning about the ongoing on-site research request from Patrick (I had meetings with them about other stuff and we talked about it at the end of those meetings). We thought a good first step (maybe a ticket) would be to brainstorm a research roadmap, list out next steps, and any outstanding questions that we can think of. Nira brought up translation testing she did with San Diego gov’t and how she learned a lot about how well translations were understood. We could go to Puerto Rico or Miami to test Spanish. It also sounded like we needed to think about going to Bay Pines. If we had the rollout calendar, then we could plan more too.

## Ideas
- What questions need answering
- Create a roadmap
- Review all the research tickets we have in our backlog
- Consolidate tickets/Epics
- Plan trips (Spanish-speaking, Chicago (blink vets), Bay Pines)
   - Logistics
   - Rotating members

**Comment by kristenmcconnell** [comment]
I created this [Mural](https://app.mural.co/invitation/mural/vsa8243/1651761334352?sender=uc940f53ad96ac0203d6d3631&key=45788030-ba0c-4d95-acb7-53730c786262), in order to aid our decision of the roadmap.

**Comment by kristenmcconnell** [comment]
The Mural was updated yesterday after another meeting with product and UX. We will be presenting the Mural to Patrick and Stephen at Tuesday's (May 17) prioritization meeting. @sarahknoppA6 or @loripusey will be messaging Patrick and Stephen to let them know that we would like to review this with them.
