### ISSUE TITLE
[Bug] Rated Disabilities - Individual rating(s) displayed incorrect case

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#4082]
## What happened?
On **https://staging.va.gov/disability/view-disability-rating/rating/**, under **Individual disability ratings**, the rating title(s) were displayed in **all-lowercase**/**Title-Case**, instead of Sentence-case as specified by UX Design.

## Specs:
- This defect is browser-/device-agnostic
- Test Users:
    - vets.gov.user+123@gmail.com \[1 rating - all-lowercase]
    - vets.gov.user+45@gmail.com \[1 rating - all-lowercase]
    - vets.gov.user+38@gmail.com \[3 ratings - all-lowercase]
    - vets.gov.user+228@gmail.com \[5 ratings - Title-Case]

## Steps to Reproduce
- Go to https://staging.va.gov/disability/view-disability-rating/rating/ , using each of the above test-accounts.

## Screenshots

**All-lowercase** bug (e.g., for vets.gov.user+45@gmail.com):
<img width="1409" alt="rated-disabilities-defect-ind-rtg-lowercase" src="https://user-images.githubusercontent.com/587583/70487119-83bda980-1ab1-11ea-98fd-14bd2c2fc6e3.png">
\[same all-lowercase bugs for test-accounts 123 & 38]

**Title-case** bug (vets.gov.user+228@gmail.com):
<img width="1368" alt="rated-disabilities-ind-rtgs-title-case" src="https://user-images.githubusercontent.com/587583/70492995-8cb77680-1ac3-11ea-925b-ddb3e4722832.png">

## Desired behavior
Individual rating-titles should be displayed in Sentence case - see [Design Comp](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/8990839d-80b5-450d-8164-c1f203a8991d/RD-Screen-Tool-2/)

## Tasks
- Write functionality that ensures the first word is capitalized.

## Acceptance Criteria
- [ ] Desired behavior (see above) successfully validated post-fix on Staging for all 4 test-accounts.

**Comment by tlei123** [comment]
Not sure which Practice Area(s) to add label(s) for this bug.  This could be backend, frontend, devops, and/or maybe even the specific API team.

**Comment by tlei123** [comment]
Note that the 5-ratings scenario test-account vets.gov.user+228@gmail.com shows the 5 individual rating titles correctly in sentence-case: 
<img width="1368" alt="rated-disabilities-ind-rtgs-sentence-case" src="https://user-images.githubusercontent.com/587583/70488632-8f5f9f00-1ab6-11ea-99e7-70925e8d5e52.png">

**Comment by jason-gcio** [comment]
Thanks Tze.  This is coming from EVSS and is being displayed from there BUT we can make a ticket to check and ensure they start with in Sentence case.

**Comment by tlei123** [comment]
Thanks, @jason-gcio!  Feel free to Close-Won't-Fix at your discretion once EVSS has been alerted.  :)

**Comment by jason-gcio** [comment]
Actually, now that I think about it, this _is_ the ticket, we will move towards future proofing in case this is how data looks in prod.  Thanks @tlei123

**Comment by micahchiang** [comment]
This ticket will address _only_ adding logic for initial cap.

**Comment by steve-gov** [comment]
I don't think we do this anywhere else in the stack so we don't want text data to be munged in this one instance. Text comes from SOR in all manner of formats and cases and is presented faithfully across other touchpoints. Good to keep in mind for future work as we clean up data in the SORs tho.
