### ISSUE TITLE
Respond to IRIS/Call Center Issues: VA Letters

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#4083]
## Problem description. 
Correct contact information must be displayed on documentation produced for the va.gov user. 
Currently, there are users whose information is incorrect when attempting to print VA letters

## Goal
We want users to be able to produce VA letters that reflect their correct name and other important details within their contact information 

## Task
- [ ] _confirm with VA Profile (Vet360) team that contact info is being properly documented in letters_
- [ ] _

## Acceptance Criteria
- [ ] All contact information content has been properly matched to user fields within letters

**Comment by Kimberley2019** [comment]
Please review the three separate issues from IRIS below and advise on how to proceed.  If additional information is needed, please advise.

 
11/18/2019 02:07 PM       191118-000808      Escalated      E. Jeter    VA Home Loan   Downloading docs

Certificate of Eligibility for Home Loan is not loading up.



12/02/2019 04:57 AM        191202-000050     Resolved         B. Silver    VA Home Loan   Personal info

I went to get my VA home loan Certificate of Eligibility (COE) on the VA.gov and was shocked to see my former name which was legally changed and updated in the system and with the VA almost 20 years ago. How can I get this rectified?


12/02/2019 12:17 PM    191202-000565    Resolved    K. Babel     VA Letters and Benefits    Personal info

When I pull up my veteran's letters, my name reads incorrectly.  It shows first, middle initial and last name followed by BET and Bet.  There must be a middle name placement error in the system.  Can you please update?  I would like to download my letters.  Thanks in advance..

**Comment by Kimberley2019** [comment]
On 12/18/2019, I reached out to Barbie Flowers, Amy Rosenthal, and John Carroll-Gavula for additional assistance.
I was informed that in additional to reaching out to the individuals above, a Service Now ticket would need to be submitted.  
@YanaRoy has been provided with the ticket details and has possibly passed along to the Vets360 team.

**Comment by Kimberley2019** [comment]
On 12/18/2019, after reaching out to Barbie Flowers, Amy Rosenthal, and John Carroll-Gavula, I was told that a Service Now ticket would in fact need to be created.

Barbie stated that in the meantime, John Carroll-Gavula will work with me to get the details.

The VA Enterprise ticket number is:

**Comment by Kimberley2019** [comment]
On 1/7/2019 and email was sent to all to inform that no progress has been made on this issue.

I requested that if there are any updates that they are aware of, that it be shared by updating this ticket or by informing me so that I can update this ticket accordingly.

**Comment by Kimberley2019** [comment]
Fisseler, Nick, OEDAUSTIN <nick.fisseler@va.gov>
Tue, Jan 7, 9:37 AM (1 day ago)
to Julie,, Ken, John, Amy, VAProfile, Michelle,, Barbara, me, Chante, Kimberley

From the service now ticket :

I went to get my VA home loan Certificate of Eligibility (COE) on the VA.gov and was shocked to see my former name which was legally changed and updated in the system and with the VA almost 20 years ago. How can I get this rectified?            
Name: B. Silver 

Do we have more information about the user experiencing the issue?  Is this a Veteran or lender?

Also in the ticket from Kimberley:

They have stated that when they attempt to download certain VA letters, some of the information is incorrect. In two of the cases, the name is incorrect and in the other, the letter is simply not loading.

Are their multiple issues from the same user or is this referring to multiple users? 

This could be a few different things

If this is a lender and they are stating that their name appearing on the letter is incorrect and they are    
Logging in through lgyHub – their name is coming from AccessVA/ID.me and would need to be corrected with them (we have instructions to assist with this)
Logging in through VIP – the user can correct their own information through the My Profile page on VIP (VIP is being decommissioned soon)
If this is a lender saying the Veteran name does not match or a Veteran stating their name is incorrect
They should be able to put in an electronic application through ebenefits/weblgy and an RLC can perform the name correction
 
Please advise on what action for us to take, or assign the ticket to LGY and provide contact information for the affected user.

Thanks

Nick

**Comment by Kimberley2019** [comment]
Kimberley Daniels <kimberley.daniels@adhocteam.us>
Jan 7, 2020, 4:32 PM (19 hours ago)
to Nick,, Barbara, Julie,, Ken, John, Amy, Chante, Kimberley, VAProfile, Michelle,

Good Afternoon Nick,

Thank you for your response.

The issue description that is in the ticket what was entered by the user.  The only information that was modified were the names.

It appears that the only one that could possibly be a lender is the issue stating that the COE is not loading up (E. Jeter).  The others appear to be veterans; but this can be verified if needed.

These are multiple issues from multiple users.  I was informed that I could simply submit one ticket for the three issues that were discovered. 

If in fact they are veterans (which two of the issues most likely are), are there any details that can be shared with them?

From the previous email from Barbara, it appears that the ticket is already with the LGY group, is that not correct?  If in fact it is correct, please instruct on how the contact information can be provided to that group.

Please advise what additional information is needed from me in order to move forward with this matter.



Kind Regards,

Kimberley Daniels

**Comment by Kimberley2019** [comment]
Kimberley Daniels
12:43 PM (0 minutes ago)
to Nick,, Barbara, Julie,, Ken, John, Amy, Chante, Kimberley, VAProfile, Michelle,

Good Afternoon All,

Sending another follow up email.  I have not received any updates from LGY or from Enterprise VA IT through the  Your IT app on the VA Network.

Please advise if Slack is more efficient for communication rather than sending emails.  If so, that transition can easily be made.

Thank you in advance.



Kind Regards,

Kimberley Daniels

**Comment by Kimberley2019** [comment]
Fisseler, Nick, OEDAUSTIN
Jan 20, 2020, 9:43 PM (12 hours ago)
to me, Barbara, Julie,, Ken, John, Amy, Chante, Kimberley, VAProfile, Michelle,

The initial email was sent over a month ago and mentioned the users experiencing the problems ”a few weeks” prior to that.  It is likely the users took other means to solve their problems, but we can still contact them to see if that is the case.  The ticket is assigned to LGY and a developer is reviewing it.  Contact information should be added to the ticket or provided on this email and I can add it. 

In the future, it would benefit us if the user was directed to the LGY help page (https://lgy.va.gov/lgyhub/help).  If a ticket is entered by your team, please enter one per issue and include contact information of the user.

 

Thanks

Nick

**Comment by Kimberley2019** [comment]
Kimberley Daniels
10:34 AM (1 minute ago)
to Nick,, Barbara, Julie,, Ken, John, Amy, Chante, Kimberley, VAProfile, Michelle,

Good Morning,

Once I am able to log back onto the VA Network I will retrieve the contact information for the users.  Please advise the safest and most efficient way to get this information to you Nick, since an email address coupled with the users name could be considered PHI or PII.  

I'm unsure if you were able to review the previous email chain; I did ask if issues should have their own ticket, and was advised that they do not.  However, now that you provided the opposite guidance, moving forward issues will have their own tickets and I will link them together if that is an option.  As inquired above, should the contact information be entered into the ticket if it is coupled with other identifiable information that will reside there as well?

Thank you for providing the location of the LGY help page that can be given to the users that are experiencing issues.

Looking forward to hearing from you.



Kind Regards,

Kimberley Daniels

**Comment by Kimberley2019** [comment]
Jayanthan, Rathica, OEDAUSTIN <Rathica.Jayanthan@va.gov>
9:01 AM (1 hour ago)
to me

Good Morning Kimberley,

 

I am trying to troubleshoot the issue that you have reported.  The issue description is not clear for me, I understand that some letters are failing for you, but I want to know what is error that you were getting and what is the record#.  Also, what is the letter name.

Please provide more information.

 

Rathica Jayanthan

IT Specialist

Support/Product Support –Benefits

Austin, Texas

Office Phone: (512)326-6377

rathica.jayanthan@va.gov

**Comment by Kimberley2019** [comment]
Kimberley Daniels
10:45 AM (0 minutes ago)
to Kimberley, Rathica,

Good Morning Rathica,

The information that is in the ticket are the only details that the users provided, the only thing that I modified were the individuals name.

The errors were not clearly identified in the initial outreach and the fact that you cannot take screenshots in IRIS does not help.  

I can email the users and ask these specific questions as well as any additional questions that you may need.  Please advise if that is suitable for you.



Kind Regards,

Kimberley Daniels

**Comment by joanneesteban** [comment]
### Grooming Follow Up

@Kimberley2019 do you have an update on progress within this issue?

**Comment by Kimberley2019** [comment]
Closing ticket.
The customers were contacted previously via email through the IRIS system; no response from any customer was received.
Reached back out to customers today stating that there was no response to the initial email that was sent to them and that if the problem still exists to reach back out to us.
