### ISSUE TITLE
Add beforeunload hook to warn users about losing form data

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#4084]
Since we don't save forms in progress, we need to warn users about when they might be leaving a page in a way that will cause form data to be lost.

This can probably be done with the beforeunload hook that browsers offer.

**Comment by narin** [comment]
@peggygannon: Could you please assist with copy?  Probably something along the lines of, "Are you sure you want to leave this page? You will lose your changes."

@rtwell: I'm assuming we want to use the alert type modal we have been using, similar to the cancel modal

@lalexanderson-dsva: @markgreenburg mentioned you might have some thoughts on when/what triggers a form data reset and that we might want to be conservative about doing so.

**Comment by jbalboni** [comment]
@narin @peggygannon We don't really have any control over the message that displays when you use the `onbeforeunload` hook. Most (if not all) browsers will show their own message in the popup and ignore whatever we try to pass.
