### ISSUE TITLE
[Spike] Display Clinic Location using V2 endpoints 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#40858]
## Background/Request
We will need to revisit the requirements to see if we need additional requirements or work to complete the original request from [FE ticket 32593](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/32593)

Currently V0 does not have clinic location available. We will need to review what V2 offers for clinic location data. 

### Goal
To determine what work is needed to complete the work (FE and/or BE). 

### Requirements to Consider
Details in [32593](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/32593)

---

## Tasks
- Answer the following questions:
  - Do we need to add more FE requirements to ticket [32593](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/32593)
  - Do we need a separate ticket for any backend/technical change? 
  - Do we need support/ticket for the VAMF team to help complete the work?  

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by ldelacosta** [comment]
@ryanshaw - The physical location is not available in V0. It is the reason why we have decided to work on this clinic location after V2 goes live. Is there a way to extract the physical location in staging for some sites? I wanted to see if we can grab the data and show the inconsistency between the clinics.  I wanted to show this to the team so we can further discuss if we want to implement this feature once V2 is launched.

**Comment by ryanshaw** [comment]
@ldelacosta What's the best way for me to do this? I can push to a review instance via a draft or/un-merged PR and then the code would be on the review instance. I think you needs SOCKS to access so I could take screenshots. I am not sure what backend data is available to review instances but it's fairly straight forward to try as a start.

**Comment by ldelacosta** [comment]
Reassigning this to a different epic Improving the user flows in Appointments #42663
