### ISSUE TITLE
Update Yeoman Generator to auto-add to allow list

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#40854]
The current new app generator sets up a lot of app scaffolding for teams, but does not add new applications to the allowlist. Since new apps are very unlikely to contain cross app imports, that would be a good time to set that up for folks.

## Definition of Done

- [x] Add option to the app generator to capture a slack alert group
- [x] Update the allowlist with the new app

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSP---Release-Tools-FE-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/40854?planning-poker) with ZenHub @theodur

**Comment by theodur** [comment]
@laineymajor Just added my estimate ✅

**Comment by theodur** [comment]
PR for updating generator: https://github.com/department-of-veterans-affairs/generator-vets-website/pull/250

**Comment by theodur** [comment]
Changes to the generator have been published, and `vets-website` has been updated to use the latest version of the generator ✅
