### ISSUE TITLE
** Placeholder** [PM] | Update Use Cases | Profile Revisions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40859]
Adt'l Use Cases

~1. There needs to be a test to make sure we are able to retrieve information already save in the backend. We could use user 36 for this. The test is loading the profile and making sure previously saved information shows up.~
2. I see you have a test case for adding information for the first time, which is great. We also need a test case for making sure someone can edit and save new information after they have already saved a response.
~3. We need a test case for making sure opening the field and canceling works.~
4. Test case for save error: You might want to read through this section. The "test case" column mentions gender identity, but the "intended outcome" column mentions preferred name. I would think you would want two use cases here -- one for preferred name and one for gender identity -- to test this use case to make sure the right error copy shows up for each field.

**Comment by SKasimow** [comment]
@Samara-Strauss @adamwhitlock1 - just spoke with Tze and the first use case should be part of standard end-to-end regression testing so wouldn't be done in QA. Adam - can you confirm if you have this as part of your testing?

For 3rd item, we won't need a separate test case as Tze will do this as part of his regular testing.

cc: @tlei123

**Comment by Samara-Strauss** [comment]
Sounds good! Thanks!

**Comment by SKasimow** [comment]
@Samara-Strauss @tlei123 - items 2 and 4 have been added to the [staging doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile-personal-information.md).  (I just need to find a screenshot for  the gender identity error message for item 4)

**Comment by tlei123** [comment]
> find a screenshot for the gender identity error message

@SKasimow , please be sure any screenshots provided are NOT captured from Staging, the environment-under-test.  This would constitute _circular references_ &mdash; validating Staging against itself.

Hope this makes sense.  Feel free to reply back w/ questions/issues.

Thanks much!

**Comment by SKasimow** [comment]
Use Cases have been updated...closing
