### ISSUE TITLE
Send time zone of the facility to HSRM

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#40851]
## Summary
The preferred date for a CC request is not being transferred through correctly to HSRM. Tested with multiple test users (ex:- patient999@id.me) and creating an appointment request for Podiatry. Selected the first earliest date 03/28. On the review and pending podiatry appointment page, it shows the correct date selection, but when the request is transferred to HSRM the preferred date is displayed incorrectly (03/27)

Please find the screenshot for your reference.

## Developer Note

It looks like the date is being set back 4 hours probably due to some time zone modifications. We have logic that updates the times to the local facility time and there may be something squirrelly happening there.

Brad Crosby - It was decided in a SoS that the BE is not doing anything incorrectly. The FE needs to send the BE vaos-service a requested period that either includes the facility time zone offset, or adjust the requested period to account for the facility time zone.

## Steps to Reproduce

The preferred date for a CC request is not being transferred through correctly to HSRM. 

1. Go to staging.va.gov
2. Pick a test user (ex:- patient999@id.me) and create an appointment request for Podiatry. 
3. Select the first earliest date 03/28. 
4. On the review and pending podiatry appointment page, it shows the correct date selection.
5. When the request is transferred to HSRM the preferred date is displayed incorrectly as 03/27.

### Actual Result
When appointment request is transferred to HSRM the start time is earlier than the requested time because time zone information is not being passes.  See attached image.

### Desired Result
Requested appointment start and end time should include the time zone of the facility that the request is for.  Times in HSRM should not be offset by the time zone offset from UTC.

## Definition of Done
- [ ] Community Care appointment requests passed to HSRM reflect the day and time requested in VAOS
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [x] **Labeled with Team** (`vaos`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [x] **Labeled with** `Bug`
- [x] **Assigned to** Product for prioritization

![preferred_date_page](https://user-images.githubusercontent.com/97117349/166556018-0c67829a-a017-4b4e-9f4c-45bbcfc67414.png)

**Comment by ldelacosta** [comment]
We will need to add a Review Instance task once code is ready. @simiadebowale

**Comment by ldelacosta** [comment]
Can you let me know if this code is covered in V2 and if you can put this behind the V2 toggle? 

cc: @simiadebowale / @vbahinwillit

**Comment by aarathi-poldass** [comment]
Validation Passed. During testing we found that the preferred times for the appointment displayed in HSRM is a little confusing for the staff. After discussion with Grace/Marcy, it was determined it to be as a training issue for HSRM staff and they need to know that 00:00:00 means AM preferred time and 12:00:00 means PM preferred time. Please find attached the screenshot for reference. @ldelacosta Please close this defect. 

![image](https://user-images.githubusercontent.com/69315717/177771691-66d4e392-a2cc-44e5-896b-d18b9eec32a1.png)
