### ISSUE TITLE
Feature Toggle to display the Clinic location on the Appt. Details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#40860]
## Item Description
We will need to create a feature toggle for the upcoming work to display the [clinic location](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/32593) on the appointment details page. 

---

## Tasks

- Add FE `va_online_clinic_location` toggle
- Add BE `va_online_clinic_location` toggle

## Acceptance Criteria: 
The toggle is created in the frontend and backend. 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by ryanshaw** [comment]
@ldelacosta Most of the other VAOS specific feature toggles are named like this: `va_online_scheduling_status_improvement`. Should we name these `va_online_scheduling_clinic_location` instead?

**Comment by ldelacosta** [comment]
@ryanshaw - I'm ok with that. Thanks for keeping it consistent.
