### ISSUE TITLE
SOCKS access for Michael Hobson

### ISSUE THREAD

**Issue by michaelhobson** [department-of-veterans-affairs/va.gov-team#40861]
### Your Name

Michael Hobson

### Your Email

michael.hobson@adhocteam.us

### Your Role and Team

Product Manager on Banana Peels (Appeals APIs)

### Product Manager (PM) name and email

Kelly Lein kelly.lein@adhocteam.us

### Product Owner (PO) name and email

Premal Shah premal.shah@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsjxatYGoAdrm2lz7CyYO+rCC3OpiUgH0uTMKKd9jkNC0aPE/tQ+NWSbgmthamsT982zGm3ikxAwdQ6sRWbtZiq0CdYZpHPM4UrRTgZsoLhEtEN6l4ICRsZve60BRV2WYmHa9BiU1IuQXALv+G89k1ohVl0RDojuSxkN3qyNOIXXZTEBulRX2MtKV7Ipq8i4/ZsqVRNiiIRFWkGAsKd/EXA0bofgGJu7/11l/3X3XYYuJEtO6SZfvu6g5/EH5O0Z8ebMazXHN7gEjK7oe2E0CRRE2Mze8upJGeot63F9vsBdszRHhsUuYrz2ejXKqZgmxHUCZ+tuVbXpJ/7rDDCVd8rK58TF0an51ajrlWKsYvBsBvMQFb5md47PZ3VJAXAVF2Gw72O1GPhgBBW86U1YP/DVTIBUZDLSIT89U1Ya2g0IW2GaQfGnMI1efk6+7Rd0jb/BhQO5NsB+zSYlomXq0hYpFQEMwg7MLGHu4rNPBh+eMneT+Gp9TjCqvtxKUJq28= smh364@MichaelHobson-HP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
I was unable to locate in VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in correct location.

**Comment by michaelhobson** [comment]
Hi! I'm not on VFS, I'm on the Lighthouse API - I should have the same access as Kelly Lein and she told me to direct you to her if you have any questions.

**Comment by jbritt1** [comment]
> Hi! I'm not on VFS, I'm on the Lighthouse API - I should have the same access as Kelly Lein and she told me to direct you to her if you have any questions.

We understand, but it has recently been decided at the PO level (far above our heads) that going forward we are to treat Lighthouse folks as we would VFS teams when it comes to platform access. That being said, we are still going to have to require you to go through the platform orientation process linked above. Apologies for any inconvenience. 

![image](https://user-images.githubusercontent.com/56260532/167649048-610543f1-d27c-492d-ae66-0aa6b15b8c80.png)

![image](https://user-images.githubusercontent.com/56260532/167649237-dbb3bb70-4489-47a6-bd08-f56e067075a2.png)

**Comment by oseasmoran73** [comment]
Closing  ticket as there has not been movement. Once you have gone through platform orientation, please feel free to reopen this ticket or create a new one
