### ISSUE TITLE
[05/11/22] AVS Open Office Hours

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#40870]
## Description 
Every week the product support team hosts a bi-weekly office hours to advertize or demo new or existing features, communicate updates to our users, and hold an open forum to answer questions from users live. 

---

## Agenda 
What is the agenda for office hours?

---

## Acceptance Criteria
- [X] Agenda created and finalized
- [X] Email drafted
- [X] Email sent
- [X] Powerpoint created
- [X] Office Hours Conducted

--- 
** Before closing out, list number of attendees and link to the recorded meeting.

**Comment by djfredvs** [comment]
Attendance 60
