### ISSUE TITLE
Convert current eslint config in vets-website to a reusable eslint config

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#40875]
The current eslint configuration lives in content-build and vets-websute as copy/pasted code

content-build: https://github.com/department-of-veterans-affairs/content-build/blob/master/.eslintrc.js

vets-website: https://github.com/department-of-veterans-affairs/vets-website/blob/master/.eslintrc.js

When we need to update rules, they have to be updated in multiple places. This should be combined into a single package and published to npm, then consumed by the repositories remotely.

There is a current package inside [veteran-facing-services-tools](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/vagov-eslint/package.json) labelled "vagov-eslint" which diverts from the main linting used in vets-website and also does not follow eslint naming conventions. It is used in formation. This package should be deprecated by the team supporting it.

## Definition of done

- [ ] Create npm package called eslint-config-vagov inside veteran-facing-services-tools
- [ ] Update vets-website to use the npm package
- [ ] Update content-build to used the npm package

**Comment by timwright12** [comment]
This is merged and release

**Comment by theodur** [comment]
I'm not sure if this was intended, but the rules from the VA custom ESLint Plugin were removed from dependent repo's ESLint configs, but not added to the `@department-of-veterans-affairs/eslint-config-vagov` package. I opened PRs in [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/21079) and [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1131) to add them back to the ESLint config in the meantime. I also started a [draft PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/821) for adding the plugin in the npm package if that's the route we want to go

**Comment by theodur** [comment]
@timwright12 After digging further into this, I think we'll probably need to have `eslint-plugin-va` be its own separate package and apart from `eslint-config-vagov`. This is similar to how other projects do it, e.g. [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) & [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier). Also, it doesn't seem like you can use a custom ESLint plugin in a config without linking it as a dependency, and using [link](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/821/files#diff-e3f041980ebfa081d4be4a6e3b68920bb46a23ee6f11b2a4a84df35270906b94R40) isn't advised for a published package, so in a way we are kind of forced to turn this into a package if we want the custom plugin to be used in `eslint-config-vagov`.

**Comment by theodur** [comment]
I merged those PRs, so now the rules are back in the ESLint config like before. We should also consider the approach of setting up a `recommended` config for our custom ESLint plugin, similar to the approach taken in @jerekshoe's [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21078).

I implemented that in this [commit](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/821/commits/6901dd291e821ab978de934c2ee874bc07203d35) of my draft PR, but it's worth deciding which rules we want to be in `recommended`.

**Comment by theodur** [comment]
I ended up making a [PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/826) to change the package name to `@department-of-veterans-affairs/eslint-plugin`, for reasons specified in the PR

**Comment by theodur** [comment]
The new npm package [@department-of-veterans-affairs/eslint-plugin](https://www.npmjs.com/package/@department-of-veterans-affairs/eslint-plugin) is published. [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/21259) and [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1158) have been updated to use the new package.

[@department-of-veterans-affairs/eslint-config-vagov](https://www.npmjs.com/package/@department-of-veterans-affairs/eslint-config-vagov) can be deprecated now, but I'm going to wait a week before doing so, to give developers a chance to pull the latest changes from `main` into their local setup.
