### ISSUE TITLE
Update "Place of birth" field on the 10-10EZ

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#40883]
## Background

This refers to design issue [#32827](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32827).

## Goals

The 10-10 EZ "Place of birth" question needs to be updated to better reflect the VA design system, and to include the "Why we ask for this information" expandable info content.

## Mockups

**Place of birth closed:** [Sketch mockup - closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/v8wnal8)

**Place of birth open:** [Sketch mockup - open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4a0n21o)

## Acceptance Criteria
- [ ] Update the field labels with new content ("Your place of birth", etc.)
- [ ] Add the expandable info component and content
- [ ] Add the country field as a select menu

**Comment by longmd** [comment]
@nicko-amida , I just want to confirm here that we are taking what is 2 form fields now--a text input for city and select input for state--and replacing them with a single text input that they can put whatever they want into. Is that correct?

**Comment by nicko-amida** [comment]
@Dene-human @longmd Yeah it was - Matt hold off on this one if you're able, I think I misunderstood the design ask: the content mentioned in this issue is ok, but I think I need to add a field and update the labeling. Matt if the level of effort needs to be reassessed that's my fault - I can get back to you later today about my updates.

**Comment by longmd** [comment]
@nicko-amida , no worries at all. Take your time to reassess what is needed. The effort is minimal to actually do this update, but if we were going from two fields to one in that section, I wanted to research if that would trigger an update elsewhere based on the data. Just making sure I wasn't going to introduce an unexpected error, that is all!

**Comment by nicko-amida** [comment]
@longmd @Dene-human Made some updates! I'm not taking away any fields now, but a country select box has been added, along with some updated labeling (issue description also has updated links).

**Comment by longmd** [comment]
@nicko-amida , for the country select box.. do they get to choose any country in the world or are we limiting to a select list? I'll do some lookin but, I'm not sure we have a full list of all countries anywhere ... so we might have to do some research and make our own.

**Comment by Dene-human** [comment]
Also are we able to trigger a sort of "default" on United states - upon arrival it's "prefilled"

I also noticed that United state appears at the top of this list

**Comment by longmd** [comment]
@Dene-human , holy crap. Absolutely. I must have been looking at something different when I was asking that earlier. I don't see why I can't just do exactly what we're doing there in Mailing Address.

**Comment by Dene-human** [comment]
But to your point @longmd I don't know if adding this field might affect the payload?

**Comment by longmd** [comment]
I think it certainly will, I just don't know what that affects. @lihanli , we're looking to potentially add an additional key/value pair to the `view:placeOfBirth` form data object. Will you have to make a change on your end to pass that additional property along? Or do we need to notify whomever gets this form that an additional property will be included in the object?

**Comment by Dene-human** [comment]
BTW. In the meantime, it would be great to update with just the additional new text, and then figure out how to add the country payload later.

**Comment by lihanli** [comment]
@longmd i don't see placeOfBirth in the schema, how is it going to be passed to the backend?

**Comment by longmd** [comment]
@lihanli , I did notice that... There are a lot of `view:WHATEVER` fields in this form config that aren't in the schema. I'm going to make a small assumption here and go with those are MAYBE not even sent to the backend? If thats a correct assumption, in this case, we are collecting data that we seemingly aren't doing anything with...which is...interesting.

**Comment by Dene-human** [comment]
oh very interesting....I had asked if I could remove this question and the HEC team was insistent that it was required as an identity marker (even though it's not a required field). Maybe you can bring that up in the future (hopefully remove this completely  from the application maybe) @nicko-amida @hdjustice

**Comment by Dene-human** [comment]
Would be great to get a list of ALL the fields that we aren't currently passing in the payload.

**Comment by lihanli** [comment]
the 1010ez backend code does not pass along any `view:` fields, i think those are for temporary frontend storage

**Comment by longmd** [comment]
I can do an audit of that and see what else I come across. Many of them are actually being used to to help show or hide other things. So, @lihanli , I think you're 100% correct. And, that makes sense--except in this case, in which the entire fieldset isnt being utilized past just inputting data.

**Comment by lihanli** [comment]
is it being used to populate the `cityOfBirth` and `stateOfBirth` fields?

**Comment by hdjustice** [comment]
Oh wow, yeah I would rather not ask for information that we aren't even sending along.. but maybe that opens up the other question about why we aren't sending it, and should we?

**Comment by longmd** [comment]
@lihanli , It's the wrapper object for `cityOfBirth` and `stateOfBirth`...which I do see those in the schema.

**Comment by nicko-amida** [comment]
I am now seeing all the discussion - let me know if anyone needs anymore design input!

**Comment by lihanli** [comment]
@longmd does the 1010ez team that handles the applications say they can want a `countryOfBirth` field? i can't add any fields unless their api can accept them

**Comment by longmd** [comment]
@lihanli , thats a fantastic question, and one I don't have the answer to. @nicko-amida , do you have any insight on whether we can do this?

**Comment by hdjustice** [comment]
Here is Joshua's response:

> no there's not a field for country, but there is a generic state code for foreign country (FOREIGN COUNTRY=FG) as MPI historically did not accept country for place of birth, only city and state

The Enrollment system cannot accept Country of birth, as they do not have a corresponding field.
What I find interesting is that there is a generic State code for a foreign country, but we do not have it listed in our state dropdown.

**Comment by lihanli** [comment]
> 1) one field for all the information, as it currently suggests in the design system, or 2) keep the current fields, but add the country of birth field, which is the design I went with.
@nicko-amida neither of those options currently work with the enrollment system API. they want a `cityOfBirth` field and a `stateOfBirth` field, there is no country field.

**Comment by lihanli** [comment]
> What I find interesting is that there is a generic State code for a foreign country, but we do not have it listed in our state dropdown.

if a user selects "Other" as the state of birth, then it gets sent to the enrollment system as "FG" (foreign country)

**Comment by hdjustice** [comment]
I don't see an "Other" option in either staging or production.  I checked the whole list..

![image](https://user-images.githubusercontent.com/92328831/176235582-7beda20b-b86e-423d-8c39-547b05877174.png)

**Comment by longmd** [comment]
So @nicko-amida , maybe thats what we do with regards to the form fields? Leave as city and state and then we append `Other` to the bottom of select box for state and change the label to "State/Province/Region" as you have in the mockup.

**Comment by longmd** [comment]
@hdjustice , if you're referring to where "Other" lives in the combobox, logically it makes more sense to be last in the list. If you're asking about the order of city and state, that doesn't matter. Those can go in either order.

**Comment by nicko-amida** [comment]
@longmd @hdjustice That's certainly possible - but if adding "other" is the only thing we can do at this point - until a separate issue is created to get the back end to accept the additional information - should we even move forward with making the change? 

The expectation from the design system is to ask for a city, state, and/or country via a single field [see "birth information" here](https://design.va.gov/patterns/forms/applicant-information) - though in my most recent version I just added the country select field since I was worried about losing the data.

I didn't realize the backend couldn't even accept the other design updates yet, and I don't want to create any more confusion with what should and shouldn't be captured, since we will eventually change from the "other" select option to using the actual updated field.

**Comment by hdjustice** [comment]
@nicko-amida - Good points.   I doubt that the Enrollment System or MPI will make updates any time soon to support the single field, or even a new "Country" field.  
I do think that we should have "Other" available as a state, even if it is just until downstream changes are made.
I checked all 10-10 tickets and found nothing referring to removing "Other" from the states, but as Joshua stated, they can accept the "FG" code for a foreign country, which Lihan stated is triggered by choosing "Other".

Open to thoughts on that

**Comment by hdjustice** [comment]
Wow, the State/province/region field really opened up to alot more choices.  Was that all in the Schema and we just weren't displaying it?

**Comment by longmd** [comment]
Correct. So the default schema allows for all of the U.S., Mexico, Canada and then Other, but for some reason we were overwriting that in the form and only giving U.S. state options. So just had to expand it back to North America and Other.

**Comment by hdjustice** [comment]
fabulous, thank you Matt!
