### ISSUE TITLE
Analytics Bug Report for Campaign Landing Pages

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#40890]
## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)
Engineer and Contact Center Support on VSP Contact Center team

  _this adds research context for any data or features being requested_

  - [Insert role, team and project]

- Is this a feature request or a bug?

  - [ ] Feature request
  - [X] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 
the `recordEvent` function is throwing an error on all campaign landing pages

https://www.va.gov/initiatives/veteran-trust-in-va/
https://www.va.gov/initiatives/veterans-experience-action-centers/
https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/

![Screen Shot 2022-05-04 at 11 19 05 AM](https://user-images.githubusercontent.com/11021491/166714665-063b9452-d0e7-472c-9885-9a2e912df55d.png)
![Screen Shot 2022-05-04 at 11 19 30 AM](https://user-images.githubusercontent.com/11021491/166714762-a246a70d-772a-4482-9077-db69ef9bbff2.png)

It appears that the culprit here is the apostrophe in the `recordEvent` event labels.

For a new bug:

- Steps to reproduce the issue
navigate to any of the following pages:
https://www.va.gov/initiatives/veteran-trust-in-va/
https://www.va.gov/initiatives/veterans-experience-action-centers/
https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/
- Test user (if applicable)

- Expected result
n/a
- Observed result
Uncaught SyntaxError in console

## Additional Comments

This error also blocks the Medallia feedback button at the bottom of the content from firing.

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Thanks for bringing this to our attention @aubreyarcangel!  This looks like an issue with the CLPs themselves, so I've sent a message to their team:

https://dsva.slack.com/archives/CT4GZBM8F/p1651687126485379

**Comment by timcosgrove** [comment]
The code that would result in this appears to be in these two places:
https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/campaign_landing_page.drupal.liquid#L314

This generates the CLP onclick tracking event. Note that it does attempt to escape the title (`'clp-click-label': 'Download {{ resource.entity.name | encode }}'`)

Later in the build process, content-build gathers all `onclick` events and moves them to a single inline script tag at the bottom of the page, so that a nonce can be assigned: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/plugins/modify-dom/add-nonce-to-scripts.js#L39

Somewhere in this process, either the encoding of the title is failing when it is first written to page, or else the encoded title is getting decoded as part of the process of moving it to the bottom of the page.

**Comment by michelle-dooley** [comment]
The code needs to be updated to resolve this issue.

**Comment by wesrowe** [comment]
@michelle-dooley, was this issue resolved, or did you close this issue for some other reason...?

**Comment by aubreyarcangel** [comment]
@wesrowe 
I believe the problem is still happening on these two pages:
https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/
https://www.va.gov/initiatives/veterans-experience-action-centers/

**Comment by wesrowe** [comment]
@aubreyarcangel - thanks. Is that the same two pages where it was originally happening?
Dave Conlon also asked, is it possible that this defect is affecting other pages where apostrophes are being passed to analytics? To that end, I guess I'm wondering how you noticed it in the first place, and whether it might have been missed elsewhere...

**Comment by jilladams** [comment]
@aubreyarcangel nudging re: Wes's comment above. Any notes on how you observed this would be helpful.

**Comment by wesrowe** [comment]
It's definitely a code issue. My questions to Aubrey above were intended to ascertain whether this issue has broader impact than just the 2 CLPs. We have a developer about to look into this now, so that's another lens on catching where else this might be impacting.
