### ISSUE TITLE
SOCKS access for James Daniel Bell

### ISSUE THREAD

**Issue by JamesDanielBell-VA** [department-of-veterans-affairs/va.gov-team#40895]
### Your Name

James Daniel Bell

### Your Email

bell_james2@bah.com

### Your Role and Team

Software Engineer Axolotl

### Product Manager (PM) name and email

Joshua Jennings Jennings_Joshua@bah.com

### Product Owner (PO) name and email

James Costa James.Costa@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClUa21XAIvePFPoBH4wQsk/693lmBjxEBhsBXClt76tReQP2iEWpzLq5K4Ec9T2Yk/ZluZi+C6mnD3WHNOYgs2ZgtmyfJZ/ORr6VcRxXOI6u3z+AIQQUNeWYiLVyNpDOstjQfkVqSQ5Jb0t2H4MJniHyqIaU2WSUGRQRC1YFspWSG8FzJ227ddgZN9I4LzKpJTZbbenuogjKridvpYBs2cxtVffoY1usdKub8QNy3dCTJ3hfsBgChmmKbkhoHakUWkdpI8gMawKTHbmVgQ7pI4hCEnhzK4V71YOph3+kSFcN5LTm1UV0x8mahiYOOU2X9XXTQz6KKwvCjHGPycsYPK5/ja7EHQ3uL8ehLJX9Kje5rrG4sCvGPDBaJ0PONV191St3XOnHI/D0yGFVOcGJ/e92kdoklhluNN7h6WwmfhmJ8Qiv+ryNFbuvhEs67OQTfK8xLBsFXCbOzoq0gXEojnAOo7fSdikM0Ep4s7LJta9HeGw17HTADfzCqJL6Jzkoc= belljd009@BAH5CG13901X5

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
I was unable to locate in VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in correct location.

**Comment by JamesDanielBell-VA** [comment]
Hello, my teammates didn't have to go through this process. Here is one of their requests: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39743

Can you direct me to proper form?

**Comment by kjduensing** [comment]
Hi James, this is a new process, established after your teammate submitted their request and before you submitted yours. You can find a link to the form by following the steps (step 1a) in the platform orientation link Ritesh linked to in his comment. 

Please reach out if you have further questions. Thanks!

**Comment by oseasmoran73** [comment]
This request has gone stale. Should you still need access, please open up another request ticket
