### ISSUE TITLE
Create grafana dashboards for backend services with statsd metrics

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#409]
## User Story
As a VSP Triage team member, I need grafana dashboards for backend services with statsd metrics so I can create PagerDuty alerts for errors in these services.

## Goal
Historic performance metrics for each of the backend services are accessible in grafana so that error alerts with appropriate thresholds can be set up in PagerDuty.

## Acceptance Criteria
- [ ] A grafana dashboard exists for each of the backend services with statsd metrics
- [ ] Each of those dashboards can be used for setting up application error alerting thresholds in PagerDuty
- [ ] These dashboards are organized correctly within grafana
- [ ] There is sufficient explanation of what you're looking at on each of the grafana dashboards

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by omgitsbillryan** [comment]
A list of new dashboards & charts:

**New Dashboards**
- [GIBFT](http://grafana.vfs.va.gov/dashboard/db/gibft?orgId=1&from=now-2d&to=now)
- [PagerDuty](http://grafana.vfs.va.gov/dashboard/db/pagerduty?orgId=1)

**New Charts to Existing Dashboards**
- [Appeals External Service Request Total & Error (with error types)](http://grafana.vfs.va.gov/dashboard/db/appeals-status?orgId=1)
![image.png](https://images.zenhubusercontent.com/59c291c1b0222d5de4787932/8de6ea3e-8304-4d0a-9f15-757fbefc2619)
- [Updated EVSS Dashboard with More Relevant GIBS Data](http://grafana.vfs.va.gov/dashboard/db/evss?orgId=1)
![image.png](https://images.zenhubusercontent.com/59c291c1b0222d5de4787932/65fd36b3-e7f4-4ea7-980f-117a077d8252)
