### ISSUE TITLE
Draft current Experience Map (skeleton)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#40901]
Mapping the current Veteran experience regarding getting and managing benefits, identifying pain points.
- [x] Develop skeleton of Veteran Experience map for further development in later sprint
- [x] Socialize with team

**Comment by MOStudioCarolyn** [comment]
https://app.mural.co/invitation/mural/innovationboards1199/1652117087196?sender=u1e2c263656ad89ecadb41603&key=51ea7209-3fc9-4512-854c-4e7481474b3d
