### ISSUE TITLE
Develop IA Tree Test diagram Hypothesis 0 and Hypothesis 1 (Research #1)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#40905]
- [x] Develop current state IA tree test diagram to be used in research #1
- [x] Submit to VA research for edits / approval

**Comment by MOStudioCarolyn** [comment]
https://docs.google.com/spreadsheets/d/1B14UkjcpJsqlo4kZvIv3G4Pw1cgmTFYXYnvXv5MWSfQ/edit?usp=sharing

**Comment by tameracorson** [comment]
Deliverable https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/health-apartment/Health%20Hub/Research/IA%20Tree%20Test%201/HH%20-%20draft%20IA%20Trees%205.17.22.xlsx
