### ISSUE TITLE
Quality Tools - Automatically enforce code quality

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#4091]
# Overview

- There are several opinionated SaaS tools that we can use to enforce code quality standards. 
- Pull request reviews are time consuming and often slow down teams while providing little benefit

# VSP Q1 + Q2 2020 OKRs 
O5: All customers comply with the Platform's standards.

# Goals 

- Reduce the burden of code reviews on the platform group
- Improve code quality with explicit and automatically enforced standards
- Identify the recommended quality standards for the platform to measure
  - Security
  - Stability
  - Scalability
  - Maintainability

# Potential tasks  

- Review third party offerings 
- Determine constraints for using SaaS products for code review 
- Create a plan for running a few options through a trial 
- Determine rollout plan 

# Code quality tools to evaluate 

- code climate (currently in evaluation) 
- sonarcloud.io: https://sonarcloud.io/about
- Codacy https://www.codacy.com/
- Crucible
- Codefactor.io
- Helixswarm
- Smart bear collaborator
- Code scene empear
- sonarqube

## VSP Q1 + Q2 2020 OKRs 
O5: All customers comply with the Platform's standards

**Comment by rianfowler** [comment]
cc @johnpaulashenfelter @gunsch @brandonrapp 

- This will probably turn into an epic. 
- We don't have a good process for evaluating and rolling out tooling like this. Code Climate is a good example of something we tried with mixed results- it might be useful running a retro on its rollout / evaluation. 
- I think there are as yet undefined platform metrics that this work could be aligned against- code quality is not a goal. We are enforcing / providing governance for certain reasons and it might be good to hammer those out as part of this process.

**Comment by brandonrapp** [comment]
@rianfowler I made this a super-epic as it will entail a bunch of work plus and it will force us to be specific about the outcomes and how we will measure success.

**Comment by rroueche** [comment]
@brandonrapp don't we already automatically enforce code quality in a lot of ways? what is unique about this initiative that you'd like to take on "NEXT"?

**Comment by brandonrapp** [comment]
@rroueche We currently leverage code climate but we have concerns about how it is being used. We don't have a clear understanding of what it is "getting us". Part of this work is that we need to agree on what success looks like. We are more trialing code climate rather than implementing it. It is going to involve some upfront discussions about what we want to accomplish and we can then measure that.   We want to look beyond than just "having it" a quality tool in place.

**Comment by laineymajor** [comment]
closing as all related tickets have been completed
