### ISSUE TITLE
Meet with CPM Team on Telephone Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40921]

**Comment by niradatta1** [comment]
Met with CPM team, and identified the following changes: 
1) Add 15 minutes specificity to the "running late" message
2) Use the facility phone number for telephone and in-person appointments

Added these content design changes in Sketch and met with @zach-park to walk-through. he'll be updating the mockups in time for our user testing. 
'cc @kristenmcconnell @loripusey
