### ISSUE TITLE
[SPIKE] [TIME BOXED] How can we Identify which Appointments are Phone and In-Person

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40923]
## Timebox
Timeboxed to 2 days

## Questions to answer
- What changes are coming for V2 (VAOS DB) that might make it easier to make this determination?
- Can we definitively determine the appointment type?
- Can we only send out pre-check-in links when we are sure of the modality?

## Background
- VAOS is treating an "unknown" appointment as "in person"
- slack thread: https://dsva.slack.com/archives/C022AC2STBM/p1650654023118099
- from Kristen - we should be sure to consult with VAOS and VEText on this

**Comment by benbrasso-agile6** [comment]
When VAOS doesn't know, they set it to in-person

**Comment by acrollet** [comment]
@wamccarty added stop codes to the information returned from Vista-API: https://dsva.slack.com/archives/C02G6AB3ZRS/p1654884226534129?thread_ts=1654884184.261759&cid=C02G6AB3ZRS

**Comment by loripusey** [comment]
@acrollet does this mean that we will have to maintain a list of stop codes that correspond to phone appointment locations? Is there nothing in the system that designates the type of appointment? should there be?

**Comment by loripusey** [comment]
Set up meeting for 6/16 with various folks to discuss

**Comment by acrollet** [comment]
Summary of findings and next steps is here: https://dsva.slack.com/archives/C022AC2STBM/p1655406794088949?thread_ts=1650654023.118099&cid=C022AC2STBM

Closing this out since we now have a plan to move forward.
