### ISSUE TITLE
Emergency Management for Vulnerable Veterans - Phase II (est. 2 weeks)

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#40931]

**Comment by shanemelliott** [comment]
Tested today.

1) Created event and sent message successfully. 
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/ca793b31-38e0-4698-9b85-140f9d9b7a62)

**Comment by shanemelliott** [comment]
Recieved message but sent indicates 0, not 1
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/d7179df6-566f-4d09-8873-5c47ed6a414e)

**Comment by shanemelliott** [comment]
tried as non-super user and the dialog to label event does not pop up. 
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/a6ea51fa-d3d4-4ea6-a726-13def3736860)
