### ISSUE TITLE
Update RFC Process

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#40934]
## Requirements
- [x] [Create new repo](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture) @td-usds 
- [x] [Change repo permissions to public](https://github.com/department-of-veterans-affairs/github-user-requests/issues/10741)
- [x] [Create Github team `platform-leadership-engineering` with Platform OCTO and vendor eng leadership](https://github.com/orgs/department-of-veterans-affairs/teams/platform-leadership-engineering/members)
- [x] [Configure CODEOWNERS for `platform-leadership-engineering`](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/main/.github/CODEOWNERS)
- [x] Configure branch protection
- [x] Create RFC template
  - [x] Include fields: deadline, author name, team name
  - [x] https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/2
- [x] Document workflow in [README.md](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/master/rfc/README.md)
  - [x] Template usage
  - [x] Add new pull requests to https://github.com/orgs/department-of-veterans-affairs/projects/710/views/1
  - [x] Announcement in #platform-architecture when RFC is ready
  - [x] How to resolve comments
  - [x] Merge conditions
  - [x] https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/2
- [x] [Handle stale pull requests](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/4)
- [x] Add existing RFCs from va.gov-team
  - [x] https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/3
- [x] [Automatically add PRs to Project Board](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/6)
- [x] [Rename repo to `va.gov-platform-architecture`](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture)
- [x] Add Slack subscription to #platform-architecture `/github subscribe department-of-veterans-affairs/va.gov-platform-architecture +label:"RFC"`
- [x] [Auto label PRs based on path https://github.com/actions/labeler](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/12)
- [x] Update documentation
  - [x] https://vfs.atlassian.net/wiki/spaces/ECP/pages/660373515/When+to+write+ADR+Idea+RFC+or+Design+Doc
  - [x] https://vfs.atlassian.net/wiki/spaces/ECP/pages/1872363553/Platform+Architecture+Working+Group @little-oddball 
  - [x] https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/main/README.md
- [x] Grant `write` permission to `all-va` GH team on https://github.com/department-of-veterans-affairs/va.gov-platform-architecture
- [x] Create https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/28 @jjulian 
- [x] Go live announced to Platform teams
  - [x] Announce in Slack with link to [RFC readme](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/main/rfc/README.md) and [RFC PR](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/28) @little-oddball 

## Followup
- [x] Create pull request template - [reference](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [x] Add convenience link to prefill new RFC submission i.e.: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/new/main/?filename=rfc/2022/2022-01-01-my-rfc-title.txt&value=insert_rfc_template&message=create_rfc - **decision was made to not do this item**
- [ ] Deprecate legacy [project board](https://github.com/department-of-veterans-affairs/va.gov-team/projects/41)
  - [x] Close out legacy issues and comment with link to [new RFC process](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/main/rfc/README.md) - **discussed commenting on an open remaining items in old board and point them to the new board. Resolution remains up to author.**
  - [ ] Delete legacy project
  - [x] Deprecate Github Discussions RFC section https://github.com/department-of-veterans-affairs/va.gov-team/discussions/categories/rfc @mchelen-gov 
- [x] Configure `platform-leadership-engineering` to use round robin assignment https://github.com/orgs/department-of-veterans-affairs/teams/platform-leadership-engineering/edit/review_assignment

## Platform Arch WG
- [x] Update `va.gov-team` [Github Action](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/assign-to-one-project.yml#L34) to add new issues to new [Platform Arch board](https://github.com/orgs/department-of-veterans-affairs/projects/710/views/1)
- [x] Remove "RFC" type from dropdown (remove type field?) https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-architecture-working-group.yml

**Comment by joeniquette** [comment]
@mchelen-gov what exactly do we want to setup for branch protection?

**Comment by mchelen-gov** [comment]
- comments must be resolved
- >=1 approval from codeowner

**Comment by joeniquette** [comment]
Im not sure how we setup "comments must be resolved" other than to just create a reminder message when the PR is created. It would be fairly complex to ensure a "response" was made to a "comment" in the PR that met some form of standard, your talking about free text analysis with this type of solution.

Regarding 1 or more approval from codeowners, we achieve this by having the codeowners file. I thought we mentioned some other form of branch protection?

**Comment by td-usds** [comment]
> Im not sure how we setup "comments must be resolved" other than to just create a reminder message when the PR is created. It would be fairly complex to ensure a "response" was made to a "comment" in the PR that met some form of standard, your talking about free text analysis with this type of solution.

For comment resolution, we could use "Require conversation resolution before merging"

**Comment by td-usds** [comment]
I'm working on documenting the workflow in a readme.md (inside https://github.com/department-of-veterans-affairs/va.gov-platform-arch); I've also enabled the branch protection requiring all conversations to be resolved.

**Comment by td-usds** [comment]
I'll move the current RFC's into [va.gov-platform-arch](https://github.com/department-of-veterans-affairs/va.gov-platform-arch) as well

**Comment by joeniquette** [comment]
need to update links and information at the following:
https://vfs.atlassian.net/wiki/spaces/ECP/pages/640647408/Architectural+Decision+Records+ADRs
https://vfs.atlassian.net/wiki/spaces/ECP/pages/660373515/When+to+write+ADR+Idea+RFC+or+Design+Doc
https://vfs.atlassian.net/wiki/spaces/ECP/pages/660144129/Idea+Documents

**Comment by mchelen-gov** [comment]
> need to update links and information at the following:
> 
> * [ ]  https://vfs.atlassian.net/wiki/spaces/ECP/pages/640647408/Architectural+Decision+Records+ADRs - Once we have documentation to update the ADR then I will update this link, for now Im leaving as is.
> * [x]  https://vfs.atlassian.net/wiki/spaces/ECP/pages/660373515/When+to+write+ADR+Idea+RFC+or+Design+Doc
> * [ ]  https://vfs.atlassian.net/wiki/spaces/ECP/pages/660144129/Idea+Documents - no updates to be made here after further review.

good catch, added to AC along with https://vfs.atlassian.net/wiki/spaces/ECP/pages/1872363553/Platform+Architecture+Working+Group

**Comment by mchelen-gov** [comment]
Additional AC per Engineering Leadership meeting:
- [ ] Make platform arch repo writable (allow PR creation)

**Comment by td-usds** [comment]
Making the repo public is awaiting Angela's approval, Brett reached out to her.
Once Angela has signed off, it'll be flipped to public.

**Comment by jjulian** [comment]
[PR created in the va.gov-platform-architecture repo](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/28)

**Comment by td-usds** [comment]
Repo is public

**Comment by little-oddball** [comment]
- [ ] @little-oddball remove project from GH

**Comment by mchelen-gov** [comment]
Followup issue for review / assessment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39024

**Comment by mchelen-gov** [comment]
Project set as "closed" https://github.com/department-of-veterans-affairs/va.gov-team/projects/41
