### ISSUE TITLE
Evaluate engineer management tools 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#4094]
# Overview 

- Because of the complexity of organizational, contractural, and decision-making structures on vets-website, it's very difficult to quantify the impact of individual engineers and teams to the platform 

# Goals 

- Use git metrics to create insights on contributor behavior and to facilitate more constructive / critical feedback to stakeholders

# Potential tasks 

- Review third party offerings
- Determine constraints for using SaaS products for code review
- Create a plan for running a few options through a trial
- Determine rollout plan

# Third party tools to evaluate 

- git prime
- waydev
- gitalytics
- Velocity (code climate)

**Comment by rianfowler** [comment]
cc @johnpaulashenfelter @gunsch @brandonrapp

**Comment by timwright12** [comment]
Signed up for the free version of Velocity to try it out

**Comment by laineymajor** [comment]
@timwright12 is this one ready to close?

**Comment by timwright12** [comment]
I would like to implement something like this at some point. It's good to have, just not a priority

**Comment by rmessina1010** [comment]
Expired. Closing.
