### ISSUE TITLE
Verify route MHV DSLogon Testing

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#40955]
This task is to run a few tests within the sign in service and USiP to ensure we are not forcing MHV and DSlogon users to go through the idme verification steps when we make our verification auth route requests.

### Sign in service testing
- [x] When authenticating with idme_MHV[verified] in the sign in service on the VA mobile app we must not be forcing users to go through the idme verification process
- [x] When authenticating with idme_DSLogon[verified] in the sign in service on the VA mobile app we must not be forcing users to go through the idme verification process

### USiP Mobile App testing (pre-SiS):
We should also verify within the USiP for mobile which requires "verified" users that we are not forcing MHV and DSLogon users to go through idme verification.

- [x] When authenticating with idme_MHV[verified] in the USiP (through eauth) on the VA mobile app we must not be forcing users to go through the idme verification process
- [x] When authenticating with idme_DSLogon[verified] in the USiP (through eauth) on the VA mobile app we must not be forcing users to go through the idme verification process

**Comment by joeniquette** [comment]
- mhv basic accounts are being “forced” to verify through idme.
- mhv premium/advanced are NOT being forced to verify through idme.
- DSLogon accounts are NOT being forced to verify through idme.

**Comment by joeniquette** [comment]
SAML:
**Standard MHV call:**
[https://sqa.eauth.va.gov/isam/sps/saml20sp/saml20/logininitial](https://sqa.eauth.va.gov/isam/sps/saml20sp/saml20/logininitial)?
&ForceAuthn=true
&ITFIM_WAYF_IDP=https://api.idmelabs.com
&Target=https://sqa.eauth.va.gov/accessva/broker?
PartnerId=
https://[ssoe-sp-staging.va.gov](http://2fssoe-sp-staging.va.gov/)
&AuthnContextClassRef=myhealthevet
&AuthnContextComparison=exact

**Forced Verify Call:**

[https://sqa.eauth.va.gov/isam/sps/saml20sp/saml20/logininitial](https://sqa.eauth.va.gov/isam/sps/saml20sp/saml20/logininitial)?
&ForceAuthn=false
&ITFIM_WAYF_IDP=https://api.idmelabs.com
&Target=https://sqa.eauth.va.gov/accessva/broker?
PartnerId=
https://[ssoe-sp-staging.va.gov](http://2fssoe-sp-staging.va.gov/)
&AuthnContextClassRef=myhealthevet_loa3
&AuthnContextComparison=exact

**Comment by joeniquette** [comment]
Setup call for the 23rd to meet with IDme regarding this subject

**Comment by nsoutouras** [comment]
Still waiting on ID.me to provide solution

**Comment by joeniquette** [comment]
The solution for now is to read the MHV LOA1 response from IDme to make the determination if a user is LOA2 or not. We will not make a second call for an LOA3. IDme is also going to look into the ability to provide us with "minimum" for authncontext but does not have a timeline for this yet.
