### ISSUE TITLE
SOCKS access for Jared Cunha

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#40959]
### Your Name

Jared Cunha

### Your Email

jared@coforma.io

### Your Role and Team

Engineer on Benefits Team

### Product Manager (PM) name and email

Sade Ragsdale sade@coforma.io

### Product Owner (PO) name and email

Matt Self matthew.self@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDSw/ibzoOXwVbJwcSYzzZAGANEmQcpkSD+2LdB19u6mh6DOn3INAW9ruEWjMreN/OJi80gqy3SY6PRnf3GMn8Oif25rD0/QlnVituROSNpXUWxC5EK4u7BFC5c8Qj0+npFhU7cp3kT5jcVqbqqjp7TO/cOOJdmkUf3+eDFtBUqEkiwkeTrnSbyRGHZS0FyRc9foB8GFC3/GoCGr1GZ0r8T0TEwxO4d36zbEt5RrK3gu7Erh/XYhs5vARnNIZDvSU/PubhwX+8+shngy5hO+7ER1jymEJAnrWrS1NqKGX8Z2SwDR+PYliknd4RKgXnmgFVAdbqGNXZi7zhpSHTEkyapk0gR0whGgkSKY3F4xq6altqJY+it6tdv8NvXlA7ebYcs/eMIEnOYhV2KLgCiITLmQLfFIqFUIYbZ7gRlfDncKxcUFE75U3rjHqGW0kYv9/ATpscBTcj7ZmUfzs55WaLN2rTpZMVI1IFE7hh4u6ybroHDLWeN+YNLknXo+9Gceos= jaredcunha@Jareds-MacBook-Pro-2.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
