### ISSUE TITLE
1010CG Form Digitization - First Draft

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#4095]
## User Story
As a caregiver of a veteran, I need to fill the 10-10CG form out online so I can jumpstart the application processing process.

## Goal
Create a first draft of a digitized 10-10CG form

## Objectives or Key Results this is meant to further
- Create the default architecture of the application without wiring it up to redux or endpoint.

## Acceptance Criteria
- [x] all fields from 1010-CG are present on the online version
- [x] The appropriate details are present on each page of the form
- [x] There is a complete intro page with appropriate details
- [x] There is a complete review page with Signature/Checkboxes
- [x] Secondary caregivers are both optional and allow you to compete form with out each secondary caregiver (up to two)
- [x] Veteran/Service member and Primary Caregiver are required

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
[https://app.zenhub.com/files/133843125/5dc5ec65-5e82-4fb0-a748-bfd7f720c89f/download](https://app.zenhub.com/files/133843125/5dc5ec65-5e82-4fb0-a748-bfd7f720c89f/download)
