### ISSUE TITLE
SOCKS access for Andrew Mauricio

### ISSUE THREAD

**Issue by ajmauricio** [department-of-veterans-affairs/va.gov-team#40963]
### Your Name

Andrew Mauricio

### Your Email

andrew@docme360.com

### Your Role and Team

Senior Software Engineer

### Product Manager (PM) name and email

emily@oddball.com

### Product Owner (PO) name and email

megan.siddle@oddball.io

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFVAwTTCNLNnRQJHvaPvcyxYjISn1Dop7xHrgzOh5DaR amauricio89@gmail.com

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
I was unable to locate your email in the VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in the correct roster.

**Comment by kjduensing** [comment]
Hi @ajmauricio! We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with the platform orientation guide Kyle linked in his comment. If you're not newly joining the team, please reach out to your PM or PO for help. 

Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by calquisola** [comment]
Found @ajmauricio VFS Team Roster

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by ajmauricio** [comment]
Hello, I had to get a new laptop and need to update my vagov public key. Can someone please help? Here is the new key:

`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMl2Q6uIKhNam0zTKMDjSN/rA3yaCcWqBg1vR446f42O amauricio89@gmail.com`

**Comment by ajmauricio** [comment]
@calquisola can you please take another look at this?
