### ISSUE TITLE
AWS access for Andrew Mauricio

### ISSUE THREAD

**Issue by ajmauricio** [department-of-veterans-affairs/va.gov-team#40964]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Andrew Mauricio

### Your Email

andrew@docme360.com

### Your Team, Role, and Company

Senior Software Engineer

### Product Manager (PM) name and email

emily@oddball.io

### Product Owner (PO) name and email

megan.siddle@oddball.io

### Desired AWS Access

lighthouse developers IAM for developing and testing VaNotify notifications within vets-api.

### Access Expiration

July 2022

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
I was unable to locate your email in the VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in the correct roster.

**Comment by calquisola** [comment]
Found @ajmauricio in the VFS Roster.

**Comment by calquisola** [comment]
### For AWS ACCESS
User: Andrew Mauricio
COR: Other
VOR: Amber Malcolm
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by td-usds** [comment]
Reached out to VOR, used @raywangoctova as COR

**Comment by oseasmoran73** [comment]
Reached out to @ajmauricio and gave credentials along with instructions on how to get access. Please feel free to reopen/create new issue should you run into any issues

Thanks @iriteshp for the help! 

Closing ticket.

**Comment by nathanbwright** [comment]
Andrew is unable to access ec2 instances in the lower envs (staging, dev, etc). I believe that he is getting a `Access denied` error when clicking on ec2 in the AWS console.

Can someone look into why he doesn't have the access he needs?

**Comment by jsgarmon** [comment]
Andrew has not setup an MFA device for his AWS account, and will not have permissions to most things until he does so.
![image](https://user-images.githubusercontent.com/47490730/172726542-b9ba5e48-eba3-4aa5-89fe-adb51346b534.png)

See [this documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781475/Set+up+your+AWS+Account) for help.

**Comment by nathanbwright** [comment]
Our team was awarded an option year for VaNotify and so we will need to extend @ajmauricio AWS access (I'm the eng lead). What is the process to do this?

**Comment by jsgarmon** [comment]
Since he does not have elevated permissions, his access won't be revoked until we receive a request to do so (such as an offboarding ticket).
