### ISSUE TITLE
[FE] Direct Deposit: Change how we are tracking fraud errors in GA

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4097]
### Background

Per our Slack convo/call, we want to track `cnp.payment.routing.number.fraud.message` or `cnp.payment.flashes.on.record.message` as two separate data points in GA so we can more easily see the breakdown of how many of these errors are occurring. Currently, these two error keys are being tracked as one data point in GA and it's making it hard to tell what our actual problem is and why the "flagged for fraud" error is occurring at such a high rate.

### Acceptance criteria

- [ ] We can see occurrences for both the `cnp.payment.routing.number.fraud.message` and they `cnp.payment.flashes.on.record.message` error keys in GA.

**Comment by Samara-Strauss** [comment]
cc/ @nedierecel @joanneesteban @jonwehausen for awareness. I don't think Erik needs you to do anything but wanted to keep you in the loop on this update.

**Comment by nedierecel** [comment]
Thanks @Samara-Strauss - @erikphansen LMK what the output might be, so we can monitor once it's live. Thank you!

**Comment by erikphansen** [comment]
With this change we'll no longer send the generic `flagged-for-fraud-error` error keys to GA. Instead we'll send more specific `account-flagged-for-fraud-error` and `routing-number-flagged-for-fraud-error` error keys, depending on which error we get from EVSS PPIU.

**Comment by erikphansen** [comment]
Merged! so you should start seeing the new error codes later today.FWIW I expect you'll see roughly 10x more of the `routing-number-flagged-for-fraud-error` errors vs the `account-flagged-for-fraud-error` errors. moving to validate and when we confirm we see the new codes in GA we can close this.

**Comment by Justin-Pickett** [comment]
Need to validate this is showing up in google analytics. @Nedie can you confirm if you are seeing this in GA? Thank you.

**Comment by Samara-Strauss** [comment]
> Merged! so you should start seeing the new error codes later today. FWIW I expect you'll see roughly 10x more of the routing-number-flagged-for-fraud-error errors vs the account-flagged-for-fraud-error errors. moving to validate and when we confirm we see the new codes in GA we can close this.

I'm not seeing this yet but I it's still early yet and the error may not have occurred yet since the new code has been out. I'll make a note to check in again tomorrow.

**Comment by Samara-Strauss** [comment]
Saw this today. Super helpful to have this metric — thanks @erikphansen!

<img width="401" alt="Screen Shot 2019-12-12 at 10 10 43 AM" src="https://user-images.githubusercontent.com/34068740/70724030-e092ad00-1cc7-11ea-8572-fd9bfa3ec0db.png">
