### ISSUE TITLE
Staging: TMP Store Forward Missing & Erroneous Appointment Data

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#40974]
TMP - Telehealth Management Portfolio
CVT - Clinical Video Telehealth
VVC - VA Video Connect

Steps to Recreate
TMP Steps

1. Contact Card  Technology Type = Personal device.  Do Not Allow Emails = Allow, fill in email address.  
2. Select schedule appt, top banner.  In new screen that displays, select Appt Modality = SFT
3. Site = Middletown, OH CBOC (984GA)
4. Provider:  Dubbaka, Naveen
5. Scheduling package = TP:779 SFT - Pat CB, Pro CB, Ind, Intra
6. Log into 984.  Validate three VistA  logins show three green checks.  
7. From top banner use Find available times. 
8. Then in side window set Requested Date only select ASAP.  Then select find available times in side window.   
9. Select this clinic:  MID-V10 CRH EYE IMG SFT PT resource with date/time.  
10. Select Schedule.  
11. From top banner select Save. 
12. In middle of screen select Appointment Information to see the booked appointment. 

1. Log into VAOS as ralph.marshall@Id.me. View the upcoming appointment list. Find the TMP Appointment.
2. Expected: VAOS shows appointment as VA Video Connect at VA Location. VAOS shows similar instructions as seen when on VAR Resources.
3. Actual:

- Shows a VA Video Connect at home.  Should show VA Video Connect Appointment at a VA Location 
- Missing instructions for joining
- Missing facility name and address
- Missing clinic name and phone number
- For cancel wrong facility to contact is displayed

This is the endpoint that returns the data in VAOS Service screen shot: https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2022-04-05&end=2023-06-04&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled

![RalphVAOS_v_VarRes_StoreForward.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/93a56d5e-53d3-45f1-bbfc-247bac7c6437)

**Comment by vbahinwillit** [comment]
Is this fixed? I just logged into staging again and it's working. The 'kind' attribute is now 'telehealth'.

**Comment by vbahinwillit** [comment]
I don't know what changed but this appears to be working now. I will request that Marcy take a look again.

**Comment by ldelacosta** [comment]
@marcynadeau - Please re-test and let us know if the issue still exists. Thanks!

**Comment by marcynadeau** [comment]
I am seeing the same issues as before.  This is still broken.  If you want we can do a call and I can review.  @ldelacosta @simiadebowale 
![image](https://user-images.githubusercontent.com/62026291/168125949-5be1f935-d2b3-4a18-a853-fc943e9df24c.png)

**Comment by marcynadeau** [comment]
@ldelacosta @JRRoof This was discussed on a call with Front End and back end developers.  The front end needs to update logic so that if kind is Telehealth and no VMR link and there is a VA clinic data then front end can infer this is a VA Video Connect Appointment at a VA Location.
For a future enhancement Brad Crosby will look into 'beefing up the API' so that the client does not have to infer the modality.

**Comment by vbahinwillit** [comment]
Please verify again now that 'vvsKind' is being returned. I just logged into staging as [ralph.marshall@Id.me](mailto:ralph.marshall@Id.me) and here are the results:

![staging va gov_health-care_schedule-view-va-appointments_appointments_](https://user-images.githubusercontent.com/3587066/171697498-563bcc91-3d6f-44dc-aa37-802c39e35483.png)

![staging va gov_health-care_schedule-view-va-appointments_appointments_ (1)](https://user-images.githubusercontent.com/3587066/171697727-99df310f-2d9f-435f-af4a-0f328f714485.png)

```
{
    "id": "99177",
    "type": "appointments",
    "attributes": {
        "id": "99177",
        "identifier": [
            {
                "system": "http://med.va.gov/fhir/urn/vaos/vvs/id",
                "value": "b2301001-e8cb-ec11-983e-001dd8031c0f"
            },
            {
                "system": "http://med.va.gov/fhir/urn/vaos/vista/984/appointment/id",
                "value": "4285;20220616.120000"
            }
        ],
        "kind": "telehealth",
        "status": "booked",
        "patientIcn": "1012830757V803997",
        "locationId": "984GA",
        "clinic": "4285",
        "start": "2022-06-16T16:00:00Z",
        "end": "2022-06-16T16:30:00Z",
        "minutesDuration": 30,
        "slot": {
            "id": "3230323230363136313630303A323032323036313631363330",
            "start": "2022-06-16T16:00:00Z",
            "end": "2022-06-16T16:30:00Z"
        },
        "cancellable": false,
        "telehealth": {
            "group": false,
            "vvsKind": "STORE_FORWARD"
        },
        "extension": {
            "ccLocation": {
                "address": {}
            },
            "vistaStatus": [
                "CANCELLED BY CLINIC",
                "CANCELLED BY PATIENT",
                "NO ACTION TAKEN",
                "FUTURE"
            ]
        },
        "serviceName": "MID-V10 CRH EYE IMG SFT PT",
        "location": {
            "id": "984GA",
            "type": "appointments",
            "attributes": {
                "id": "984GA",
                "vistaSite": "984",
                "vastParent": "984",
                "type": "va_health_facility",
                "name": "Middletown VA Clinic",
                "classification": "Multi-Specialty CBOC",
                "timezone": {
                    "timeZoneId": "America/New_York"
                },
                "lat": 39.50603,
                "long": -84.316475,
                "website": "https://www.dayton.va.gov/locations/midtwn_cboc.asp",
                "phone": {
                    "main": "513-423-8387"
                },
                "physicalAddress": {
                    "type": "physical",
                    "line": [
                        "4337 North Union Road"
                    ],
                    "city": "Middletown",
                    "state": "OH",
                    "postalCode": "45005-5211"
                },
                "healthService": [
                    "Audiology",
                    "MentalHealthCare",
                    "Optometry",
                    "Podiatry",
                    "PrimaryCare",
                    "SpecialtyCare"
                ]
            }
        }
    }
}
```

**Comment by marcynadeau** [comment]
@simiadebowale @ldelacosta This has passed testing. ![TMP_SFT_RETEST_40974.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/9edfc8a1-a0e9-492b-ab49-754e7088144b)
