### ISSUE TITLE
Environment options for Phase 2 roll-out of redesigned VA.gov homepage

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#40975]
## Background 
The redesigned homepage will be released to dev/staging for Phase 1 - Veteran usability research.  This environment was chosen to enable testing with Veterans using screen readers and other assistive technology. Locating the test page at a subdirectory path under [env].va.gov instead of having it replace the existing homepage at the root avoids disrupting other teams. 

## Problem to solve  
We need to identify the appropriate environment to host the redesigned VA.gov homepage between usability and release to production (Phase 2). The goal of this Phase is to enable additional exposure/beta testing/etc. of the new design before release. 

**The following details about the criteria and environment options includes engineering discovery and IA input from Mikki.** 

## Environment criteria 

- Code can’t get lost, stale or accumulate merge conflicts 
- Must be publicly available (no SOCKS or VA network access required) 
- Redesigned version can co-exist with current VA.gov homepage (semi-permanent - for weeks, not minutes) 
- Redesigned/custom content is displayed and can be limited to this environment 
- Functionality mirrors production 
- Header, footer, banners, and links mirror prod and are updated in parallel to prod 
- Avoids indexing by site search or web crawlers 
- Beneficial (but not required) if the path lends itself to a more scalable use for other teams/experiences beyond the homepage (not a requirement) 
- Disruption for other teams is minimized 
- Needs a unique url (ideally on va.gov to allow for beta testing/exposure)

## Subdomain (e.g. preview.va.gov) 

Pros 
- Does not need involvement of Web Governance Board 

Cons 
- Considerable effort across many teams inside and outside OCTO-DE 
- It feels like a separate experience/ site, rather than as a "page" within the existing site _(could be perceived as a benefit, depending on the intent)_ 
- Not linked to production - by default, a link from preview.va.gov would be wired to preview.va.gov/page-in-question ( We don't want an entirely separate site. We just want a separate version of one page.) 
- Linking it to prod is probably technically possible but may be a significant lift 

Technical requirements 
- Maintain a FE "feature" branch for all code tied to subdomain- this would effectively be a second production branch 
- Separate "production" server to which we can deploy this branch 
- Separate "production" Drupal instance (depends) 
- CI/CD tweaks to treat this "feature" branch as a production branch (i.e. cannot deploy until tests pass, code approved, etc.) 
- Link replacement => some process to point links from subdomain back to primary domain (depending on needs of other possible experiences beyond homepage, this process might have to be customized based on each product, each page, or on some other more granular level) 

## Subdirectory (e.g. va.gov/homepage-preview) 

Pros 
- Fewer teams involved and less effort 
- Entirely in code = entirely in our control 
- Not subject to anything like DNS 
- Intact functionality, header, footer, and links  

Cons 
- Needs approval from Web Governance Board -  We currently do not own that subdirectory of VA.gov and we would need to ensure that there are no collisions either now or in the future. (May not need governance to use a subdirectory if it were limited to dev/staging?) 
- only works for the homepage - would not really scale beyond this one effort 
- Discoverability concerns - must prevent the path from being indexed by site search or web crawlers 

## Codespaces 

Pros 
- Publicly accessible, persistent, randomly generated URL 
- Optional access restriction 
- Compatible with existing repositories and network infrastructure 

Cons 
- Requires keepalive 

## Staging 

Pros 
- Path toward prod 

Cons 
- Not completely hidden - not indexed or on the site map but could be found 

Technical requirements 
- Use a build-time check to limit which environments build this second homepage 

## URL notes 

- Cannot replace existing homepage on staging or dev - needs a unique url 
- Randomizing would prevent accidental discovery but could make it more difficult to get users there during usability (outside of sharing the link) 
- Avoid using “beta” unless it is truly a beta situation 

## Usability/testing notes 
- Back button can be used to support navigation back to testing home page version during usability sessions 

## Timeline
- We are entering a period of user research to gather information about Veteran top tasks and conduct usability testing, which will include Veterans who use assistive technology to visit VA.gov

## Points of contact

- Product Owner: Dave Conlon (VA)
- Product Manager: Michelle Middaugh (Ad Hoc)

**Comment by jilladams** [comment]
This was solved via staging at https://staging.va.gov/homepage-test
