### ISSUE TITLE
Bug- Issue with iMessage related to QR Code on iPhone

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#40989]
As a Veteran checking in for an appointment, I would like to scan the QR code on the poster to start my check-in process.

Notes: This ticket pertains to a bug reported via Shawn Adams (which he heard from a VISN 8 facility that has gone live.) Link to Slack thread: https://dsva.slack.com/archives/C022AC2STBM/p1651781287543959

Shawn Adams, Sarah Knopp, and Kristen McConnell have all been able to reproduce the issue on their own iOS devices using the steps to reproduce below. Issue was reported on iOS version 15.4.1 with hardware iPhone XR, iPhone 13, iPhone 12 Pro

The issue reported is that if the user scans the QR code which opens iMessage with the prepopulated info, and then the user selects "Cancel" in iMessage, and then repeats the operation, the second iMessage screen freezes and the user cannot continue. There is no keyboard on the screen and canceling or sending do not work. 

Steps to reproduce:
1. Scan QR code
2. Select interactable offering
3. Text pre-populates
4. Select Cancel
5. Select interactable offering again (you may have to scan QR code again)
6. Error produced

The expected behavior is that the second iMessage prompt would behave the same way the first one does and allow the user to complete the text operation in order to start their check-in, or allow them to interact with the screen or cancel the operation.

**Comment by acrollet** [comment]
This is an iOS issue, I don't know if it's specific to the latest version or not. I think we should log it as a known issue and document the workaround of going to the home screen and re-opening the camera app to re-scan.
