### ISSUE TITLE
Testing code for VA Notify (Transition Refactoring)

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#40996]

**Comment by lindsay-insco** [comment]
Transitioning to testing

**Comment by lindsay-insco** [comment]
3 dependencies in order for us to go live with VA Notify outbound:
1. Getting twilio message SID - follow up with AVI invocation based ipon notification ID from VA Notify
2. AWS 10-DLC in phase 1 for long-code message in lieu of pool of twilio long-codes : VANotify needs to create 10-DLCs + 2 existing AWS-based use-cases abd currently any responses are being placed on SMS-queue. Rob created endpoint for AWS inbound messages deployed to staging
3. VA Notify will need to hand those above over

**Comment by lindsay-insco** [comment]
@mjones-oddball above for tomorrow's meeting

**Comment by mjones-oddball** [comment]
@lindsay-insco @jwowk Question about the dependencies, I believe getting the message sid in the notification object (to be able to retrieve Twilio status) is only required for the 2 way use cases - is that accurate? If so we could still proceed with testing and phase 1 cutover for other use cases e.g. one way or outreach. We also need to test that international works prior to moving forward which I don't think we've done yet.

**Comment by lindsay-insco** [comment]
@mjones-oddball - No it's not only for 2-way, it is for all

**Comment by lindsay-insco** [comment]
Currently testing in Staging environment

**Comment by lindsay-insco** [comment]
1. Getting notification/Twilio SID 
2. Being able to get inbound messages from AWS through API endpoint

Above marked as waiting for VA Notify action

**Comment by jwowk** [comment]
Transitioned to OSM...Appt reminders remain

**Comment by lindsay-insco** [comment]
Live with VA Notify
