### ISSUE TITLE
Discovery: Build process uses too much memory

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#4099]
## Problem Statement
Periodically, we're running into a problem with the `vets-website` build in Jenkins where the build stops with only `Killed` logged. After doing some digging, @ncksllvn found [this article](https://adminhacks.com/node-script-killed.html) which seems to mirror what we ran into.

We're running out of memory. This isn't the `--max-old-space` that we can pass to `node`, either. This happens when the _system_ doesn't have enough memory to allocate to Node. (Or that's how I understand it, at any rate.)

## Phase One: Discovery
We need to figure out which steps are taking the most memory.

One way we might do this discovery is with [`heapdump`](https://www.npmjs.com/package/heapdump). Temporarily modify the build process to generate a heapdump and load it into Chrome's devtools.

## Further reading
- [How to inspect the memory usage of a process in Node.Js](https://www.valentinog.com/blog/memory-usage-node-js/)

## Acceptance criteria
- [ ] Memory hogs in the build pipeline are identified
- [ ] Tickets are written for each
  - Bonus points for including possible solutions and expected gains

**Comment by ncksllvn** [comment]
Suggestion - To conserve memory, I don't think the assets added to the site via `metalsmith-assets` plugin are ever added into the Metalsmith buffer. Instead, I believe the assets directory is just copied over directly into the target output directory. If we do the same w/Drupal assets, I think we can fix this.

**Comment by cvalarida** [comment]
Good call. That should be the first place we check for memory usage. :+1:

**Comment by timwright12** [comment]
Closing as duplicative
