### ISSUE TITLE
[FE] | Discovery|  Personal Info Revisions | Update Messaging | User Clicks Edit --> Update | No Entries/Selections Made

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41001]
# Story

**Scenario 1:  Preferred Name/Update**
As a user viewing the Personal Information page prior to adding my Preferred name
IF
I click the "edit" button underneath the "Preferred name" field
AND
do not enter any information
THEN
Click "Update", I should see an in-line error message prompting me to enter my info

**Scenario 2:  Preferred Name/Cancel**
As a user viewing the Personal Information page prior to adding my Preferred name
IF
I click the "edit" button underneath the "Preferred name" field
AND
do not enter any information
THEN
Click "Cancel", my screen should revert back to the original "blank" state 
OR
display the previous response

**Scenario 3: Gender/Update**
As a user viewing the Personal Information page prior to choosing a gender identity
IF
I click the "edit" button underneath the "Gender identity" field
AND
do not make a selection
THEN
Click "Update", I should see an in-line error message prompting me to enter my info

**Scenario 4:  Gender/Cancel**
As a user viewing the Personal Information page
IF
I click the "edit" button underneath the "Gender identity" field
AND
do not make a selection
THEN
Click "Cancel", my screen should revert back to the original "blank" state 
OR
display the previous response

**Comment by SKasimow** [comment]
@adamwhitlock1 @cgednalske - can you review my stories and lmk if I've captured this correctly based on our "16th minute" discussion today?

**Comment by cgednalske** [comment]
Hi @SKasimow! Could it be helpful to include something like the following for Scenario 2 & 4 to clarify this would happen when there's already an answer in place as well?

"Click "Cancel", my screen should revert back to the original "blank" state **_or my previous response_**" 

And here are the mockups showing this alert for both [desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/jga1Lba) and [mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/qe1LZe2).

**Comment by SKasimow** [comment]
@cgednalske yes - good point! I added in another condition for #2 and # 4 as well as the mocks. Thanks a bunch!

**Comment by adamwhitlock1** [comment]
This PR has been merged and is live on staging. @SKasimow we can now validate that this works as expected and requires a value for both fields and the appropriate error messaging shows from validation.

**Comment by SKasimow** [comment]
Thanks @adamwhitlock1 . I have to run out for a few but will look at when I get back so I don't hold this up!

**Comment by SKasimow** [comment]
@adamwhitlock1 - I'm using a blank account (staging user 80) and doing the following:

- Preferred name --> edit
- don't enter any info
- hit "cancel"
- **expected result:** reverts back to initial "blank" state
- **actual result:**  get the in-line error message. 
     - if I then select "cancel" again, I revert back to original "blank" state screen
     
Note: works as planned if there is already a preferred name entered.

**Comment by adamwhitlock1** [comment]
Yes, that is an issue with the validation library in general in that other areas of the profile do the same thing. For instance if you go to the Contact Information and do the same process with a phone number the same thing will happen.

For example on user 36 there is no 'work phone' so if you hit edit on that field and immediately cancel you will see the same error message behaviour. I'm not really sure that there is a way around it not showing that initial error message at this point.

**Comment by SKasimow** [comment]
Closing discovery work...new ticket is #41319
