### ISSUE TITLE
Migrate Sidekiq Github team to Keycloak

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#41012]
Currently, SideKiq UI authenticates its users by ensuring they exist as a member in a Github team. Because this team is isolated and small, we can migrate the team to Keycloak and avoid having to make additional calls to Github to support authentication. 

Github team: [va-gov-sidekiq](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members)

Done when:
- [ ] A group is set up in Keycloak dev with the IET team members included
- [ ] A group is set up in Keycloak utility with the team members included from the team above

**Comment by ewilson-adhoc** [comment]
My team will begin active development against this feature this week -- we are pulling it into this sprint and will keep AMT abreast of things that we need configured. @MrMorie , @MrBilnon and @considerable when you get a chance could you create accounts on keycloak dev for yourselves.

**Comment by FHiatt** [comment]
@kjduensing Kevin - Can you please provide status on this story? Is there anything you need from IET on this story?

**Comment by girldadmk** [comment]
Moving to Icebox until Sidekiq UI is ready for production.

**Comment by ActualAbby** [comment]
@kjduensing Console UI Team thinks we have all our parts of this done, we have added links to the [new staging](https://github.com/department-of-veterans-affairs/vets-api/pull/10430) and dev environments. We are aware that the new production environment of sidekick is a Q4 or beyond goal.

**Comment by ewilson-adhoc** [comment]
@ActualAbby We will be aiming to promote sidekiq UI into utility in Q3 so this is something that we will need for the q3 timeframe.

**Comment by ewilson-adhoc** [comment]
It was decided by the team inheriting this service (console services) that we will not migrate existing users at this time, in order to better audit who is actually using this tool, and who needs access to what level of environment (production, dev, ect) Closing this out.
