### ISSUE TITLE
Dev: VAOS content edits for Direct Schedule flow

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#4102]
## User Story or Problem Statement
As a member of a team building with or on VSP, content needs to be reviewed to ensure it's accurate, aligns with VA style, and is error-free.

## Acceptance Criteria
 VAOS DEV team to implement content edits (below) in time for UAT testing of Direct Schedule screens. 

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments

**Content edits for Direct Schedule screens:** 

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/va-facility
- Update content TO: 
To schedule an online appointment, some locations require that you visited their facility within the past 12 months for the type of care you select. And some types of care are available at only certain locations.

-----
{alert recent appointment}
**We couldn't find a recent appointment at this location**
You need to have visited this facility within the past 12 months to request an appointment online for the type of care you selected.
If you haven’t visited this location within the past 12 months, please call this facility to schedule your appointment or search for another facility.

{alert outstanding request}
**You already have an appointment request at this location**
Our records show that you have an open appointment request at this location. We can’t schedule any more appointments at this facility until the open appointment requests are scheduled or canceled.

{no appointments at this location}
**There are no {type of care} appointments at this location**
We’re sorry. This facility doesn’t accept appointments for this type of care. Please call the medical center for more information. You can find contact information for this medical center at our [facility locator tool](/get-locations).

----

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/clinics
- change page title TO: Choose your VA clinic for your appointment
update copy to: 
In the last 24 months, you had a primary care appointment at the following locations: 

- Select a clinic where you have been seen before, or request an appointment in a different clinic.
Update this content TO: You can choose a clinic where you’ve been seen or request an appointment at a different clinic. 

----

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/preferred-date
- Update page title TO: Tell us when you want to schedule your appointment
- Update question TO:  When is the earliest you want to be seen? 

- Why does this matter link?  Update this link TO: Why are you asking me this? 
Update following text TO:
If you tell us the earliest date you’re available for your appointment, we’ll try to find the closest date to your request. Note we might not be able to find the appointment for that particular day. 
 
---

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/select-date
Update page title to: Tell us the date and time you’d like your appointment

Please select date and time for your appointment. Appointment times are shown in Mountain time (MT).

----

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment

- Change page title TO:  Choose a reason for your appointment
- Update first sentence TO: Please let us know why you’re making this appointment. 
 - Radio buttons: Update TO:
{button} Routine or follow-up visit
{button} I have a new medical issue
{button} I have a concern or question about my medication
{button} My reason isn’t listed here

- Alert: Please update emergency alert box TO: 

**If you’re having a medical emergency: **
- Call [911], **or**
- Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
- Go to your nearest emergency room or VA medical center. [Find your nearest VA medical center]

------

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-visit-type
- Change page title TO:  Choose a type of appointment
- Please add an intro sentence:  Please let us know how you would like to be seen for this appointment.
- Update radio buttons TO: 
{button} Office visit
{button} Phone call 
{button} Telehealth (through VA Video Connect) 

------

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/contact-info

- Update page title TO:  Your contact information
- Update the following labels:
Phone number TO Your phone number
Best times for us to call you TO: What are the best times for us to call you? 
Email address TO Your email address

--------

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review

add intro sentence: You’ve scheduled a {type of care} appointment

------

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/confirmation
We need update message saying your appointment has been scheduled. 

{alert}
Your appointment has been scheduled
Your appointment is confirmed. Please see your appointment details below.

**Comment by jbalboni** [comment]
Hi @peggygannon, on the https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment page, I think the text box label needs to have updated content for this flow.

Right now that label says: "Please give us more detail about why you’re making this appointment. This will help us schedule your appointment with the right provider or facility. Please also let us know if you have any scheduling issues, like you can’t have an appointment on a certain day or time."

However, in this flow, the Veteran is making an appointment directly (they've chosen a specific time that we know is available), so a scheduler won't ever see this submission. It'll go straight into VistA and I believe the only people who would see this info are providers.

**Comment by peggygannon** [comment]
@jbalboni OK, thanks. So for Direct Flow screen, please let me know if this updated content would work?

Please provide any additional details you'd like to share with your provider about this appointment.

**Comment by jbalboni** [comment]
@peggygannon That works for me, thanks!
