### ISSUE TITLE
Create Incident Response Playbook and Monitors for Github Deploy issues 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41020]
# Background

There have been issues with the GitHub Deploy.   We need to know how to detect issues and what steps need to be followed to resolve the issue.

## Slack Thread 
[OOB Request For update some content inside the react widget](https://dsva.slack.com/archives/CBU0KDSB1/p1651181744954229)
## PostMortem
[Postmortem for OOB](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/6f7846bb506b312e0d4ea8345e69ff62c51e97c3/Postmortems/2022-5-2-React%20widget%20content%20in%20scaled%20release)

# Problem

- We do not have a clear incident response playbook for Github Deploy issues.
- We do not have enough monitors in place to detect all of these GitHub bad merges and deploy issues.
- We need a process to respond to these merge and deploy issues

# Acceptance Criteria

- [ ] Create an incident response playbook issues with Github bad merges and deployment failures
- [ ] Create monitors to detect PR checks failures and bad merges on vets-website.
- [ ] Create monitors to detect that a va.gov and api.va.gov deployment has not occurred when expected.

**Comment by rmtolmach** [comment]
The example Slack thread was a frontend issue. For vets-api, we have a notification if CI fails on a PR that merged into master. Notification is in #devops-deploys. [Example](https://dsva.slack.com/archives/C37M86Y8G/p1687815478729399):
<img width="618" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/ecdf7202-5b47-4675-9650-362df0b85ae9">

**Comment by rsmithadhoc** [comment]
Closing issue:

- We have support checking for deploy issues daily for front-end.
- We have procedures in place for off cycle deployments.
