### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#41028]
# Description
As part of our Sign-in Service rollout we need to perform load testing

# Acceptance Criteria
- [ ] Allows to send traffic from cmd line
- [ ] Before and after limit testing
- [ ] Utilize Locust

# References
https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest

**Comment by joeniquette** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/11818
