### ISSUE TITLE
we need documentation and training around the subject of reporting an issue

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41025]
# Background

The platform users/customers are unclear on how to request help for issues they may have.   We have made some enhancements to the support bot and documentation that should be shared in a training or orientation for new users.

# Problem

- Users are unsure how to use the current documentation and the slack support channel for their issues
- We do not have an orientation and training on the best steps to take to get help with their platform support issues.

# Acceptance Criteria

- [  ] Create a training/orientation slide deck to be used for a monthly Orientation session.
- [  ] Work with the Collab Cycle team to plan to have a monthly getting support from platform Orientation session.

**Comment by alyssagallion** [comment]
There is now a Platform Orientation Slide 21 here: https://docs.google.com/presentation/d/15D3yDKBtQP4TXV5G2tYIMnfujNepgSJFEBjT4T4W25Q/edit?usp=drive_link

It points to a Youtube overview of how to work with our team and submit requests. Additionally, we have Support Best Practices that outline how they should submit tickets here: 

https://depo-platform-documentation.scrollhelp.site/support/support-overview
https://depo-platform-documentation.scrollhelp.site/support/support-best-practices
https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support

Closing!
