### ISSUE TITLE
Short Content Review for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4104]
## Story
As a Veteran using Rated Disabilities, I want to be able to read the newly recommended changes to the content so that the information is clear, concise and makes sense in a legible way.

## Considerations
Some design recommendations have changed the [Rated Disabilities Tool page](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL) enough that the content needs to have another look to ensure we are providing the best feature we can.
1. Do the titles make sense? (H1 & H2 seem redundant)
2. Plurality of ratings (H1 should be plural, to encompass all the ratings on the page(?), and combined disability rating should be singular?)
3. Breadcrumbs should match H1 titles either way
4. In the right rail, is the "Learn about VA disability ratings" language ok?
5. Confirm correct hotline numbers: general contact (on right rail) is the main hotline (800-827-1000), and within the 500 error, the number shown is the VA.gov help desk (855-574-7286)

## Acceptance Criteria
- [x] Feedback has been shared with the eBenefits Team for final implementation

**Comment by peggygannon** [comment]
@jason-gcio 
Hello, below are my content recommendations for the updated Rated Disabilities mock. 
I'm putting my comments in this issue, as the mock up still shows my content edits from V1 and I didn't want to confuse you. 

Also, I will need to see this mockup again, to ensure a smooth copy UX transition with the static landing page that the public website team is working on.  

Content review for updated mock up: 12/13/19 
*Screen 1*

I will need to see the update static content for the landing page once it's completed to make sure headings and copy aren't redundant. 

----

*Screen 2*

I think we should add a short intro to help users understand what they are reading (combined ratings vs. individual ratings) 

H1: **Your VA disability ratings**

H2: **Your combined disability rating**
New intro  copy: This is your rating for multiple conditions.

Update box copy, (as we've heard in recent research that some people don't understand what "pending" means) TO: 

This rating doesn’t include any disabilities for your claims that are still in process. 

H2: Individual disabilities
I recommend that we rewrite this head to say Individual ratings to tie in more closely with the H1. So this header would become: 

H2: **Your individual ratings** 
New intro copy: This is your rating for a single condition. 


Right rail: 
Update the last sentence under the header "How did I get this rating?" TO: 
"…and information from other sources, like federal agencies. 

Under the header "Learn about VA disability ratings"
Rewrite to make more active voice: 
To learn how we determined your combined VA disability rating, use our disability rating calculator and ratings table. 

The link "About VA Disability ratings" should be sentence-cased: About VA disability ratings

------

*Screen 6^
For this error, please remove "We're sorry." from the beginning of the first sentence. We're refining our usage of this term and want to make the messages more succinct with less noise. 

**We don't have a disability rating on file for you**

So message body copy would start: We can't find a disability rating for you..." 

----

*Screens 7 and 8* 
For the 500 errors, please add “the” before VA.gov help desk in: 
 the body of the message
So the sentence would read: please call the VA.gov help desk.... 


---

*Screen 9*
For this error, please remove "We're sorry." from the beginning of the first sentence. We're refining our usage of this term and want to make the messages more succinct with less noise. 

So message body copy would start: We can't find a disability rating for you..."

**Comment by jason-gcio** [comment]
Thanks @peggygannon, this is great.  Here is our latest mockup:  https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL/

**Comment by jason-gcio** [comment]
@peggygannon I think we are good to close this, thanks again!
