### ISSUE TITLE
Update product directory validation script

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41044]
## Issue Description
In our product-directory repository we have a validation script that validates entries based on our proposed data types. The validation script was written based on our old list and/or our in-progress list at the time. This script should be updated to reflect the new/current schema.

---
## Tasks
- [x] Update our product list validation script to properly validate our most up-to-date product list schema.

## Acceptance Criteria
- [x] All new entries to the product list are properly validated for formatting to preserve data integrity.
---

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/product-directory/pull/14

**Comment by holdenhinkle** [comment]
This is done. Moving it to review...

**Comment by pjhill** [comment]
Thanks for knocking this out!
