### ISSUE TITLE
[CDP] Update the 'Additional information' component's chevron color to blue

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#41050]
## Issue Description
As part of the Combined Debt Portal's midpoint review, we received feedback that we're not using the correct hex color code for the 'Additional information' component's chevron. The correct hex code is `#046b99`

---
## Tasks
- [x] Update the prototype' 'Additional information' components to the correct chevron color 

## Acceptance Criteria
- [x] The UXPin has been updated and linked in this ticket

**Comment by kevinstachura** [comment]
Only could locate one instance of the additional info component in the UXPin proto - on the 'debt detail' page:

https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148307615/simulate/sitemap?mode=i

It has been updated to the proper color. Closing as complete.
