### ISSUE TITLE
Redirect COVID chatbot link to the main coronavirus FAQs page

### ISSUE THREAD

**Issue by khathuynh-tw** [department-of-veterans-affairs/va.gov-team#41057]
On May 15, the coronavirus chatbot will be retired. By that date, we will want to redirect users who visit that link over to the main coronavirus FAQs page. 

See below:
https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/456
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/39785

The Virtual Agent Chatbot team is looking for guidance from sitewide teams to understand how we can put this redirection in place. Thank you!

**Comment by rmtolmach** [comment]
Closing. Please reopen if I'm mistaken.
