### ISSUE TITLE
[Copy] Direct deposit: Error state for blocked routing numbers

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4105]
## Background

We have an error key `cnp.payment.routing.number.fraud.message` that we are currently showing an error message that doesn't really apply to this use case. After talking with some folks at EVSS and BGS, we have a better understanding of what is actually happening on the backend and what we should communicate to users on the frontend with regards to this error.

## Design

![Profile with direct deposit_Edit modal open_Routing number error](https://user-images.githubusercontent.com/34068740/70564804-d6a16a80-1b5e-11ea-9f5a-e2528439cdad.png)

## Copy needed

The copy needs to explain:

- They can't save this routing/bank number.
  - We may not want to explain why we can't save this. The reason is because there is a list of routing numbers that have been associated with a fraud ring in 2015. The routing number/user may not necessarily be fraudulent/trying to commit fraud. These could be legit attempt and many of the routing numbers are legitimate. But the VA currently has a flag on them which means those routing numbers can not be updated online. 
- If they want to use this number, we need to do some additional verification.
- This request can be processed over the phone, by mail, or in person at a VA regional office.

**Comment by peggygannon** [comment]
@Samara-Strauss 
Hello, please see below for 2 options for copy recommendation for bank number message. I like how the bullet point option makes it clear to users they have two options for moving forward, but would love your thoughts if this won't work with the design. Let me know if you have any questions or feedback. 

I also wanted to check that the link I inserted below (/change-direct-deposit) is the correct place to send users? 

OPTION 1
**We can’t save your bank routing number**
We’re sorry. The bank routing number you entered requires additional verification before we can save your information.  To use this bank routing number, you'll need to call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday 8:00 a.m. to 9:00 p.m. ET. 
You can also update this information by mail or in person at a VA regional office. [Learn how to update your direct deposit bank information](/change-direct-deposit). 

-----

OPTION 2
**We can’t save your bank routing number**
We’re sorry. The bank routing number you entered requires additional verification before we can save your information.  To use this bank routing number, you'll need to: 
•	Call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday 8:00 a.m. to 9:00 p.m. ET, **or** 
•	Update this information by mail or in person at a VA regional office.  [Learn how to update your direct deposit bank information](/change-direct-deposit).

**Comment by Samara-Strauss** [comment]
Thanks for this, @peggygannon! I'm going to go with option 1 because the modal/error aren't very wide and the indent for the bullet, while small, will give the text even less width.

Otherwise, copy is perfect. I'll get this into mocks and move over to FE.

**Comment by Samara-Strauss** [comment]
FE in #4109
