### ISSUE TITLE
[FE] |Profile | Personal Info Revisions | Analytics Implementation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41067]
### Background

As part of the work for the Personal Info revisions, we'll need to update our analytics. We've outlined what we would like to track and have received input from the Analytics team in ticket #40524.

### Description

1. **Tracking for clicks into the new Contact Information link in the left-nav** (previously combined with the personal information section)

2. **Interactions to be tracked for preferred names**
- Clicks to preferred name edits (open)
- Count of fail saves
- Count of successful preferred name updates (saves)

3. **Interactions to be tracked for gender identity***

- Clicks on Gender Identity edits (open)
- Count of successful updates (saves) 
- Count of fail saves
- Clicks to "What to know before you decide to share your gender identity"

4. **Retrievals**
- Successful retrievals of personal information from the backend
- Failed retrievals of personal information from the backend

### Analytics Guidance:
**Personal Information**
| Interaction | Screenshot of Interaction | Screenshot of dL | Status |
| -- | -- | -- | -- |
| Clicks to preferred name edits (open) | ![image](https://user-images.githubusercontent.com/91892981/166814475-0b1f0f2a-bb3b-494f-86c6-5fa61897a2cf.png)| ![image](https://user-images.githubusercontent.com/91892981/166814601-25dbd46a-c5e4-4539-a040-0579fb770bff.png)| 🟢Tracking Correctly|
| Count of fail saves| | { event: 'api_call', api-name: 'Profile - Personal Information Save', api-status: 'failed', 'error-key': '500 timeout message' api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }
| Count of successful preferred name updates (saves)| ![image](https://user-images.githubusercontent.com/91892981/166814732-ac561ca3-1685-423f-90d4-1182e2e1cdf2.png)| ![image](https://user-images.githubusercontent.com/91892981/166814842-9499b993-4c80-4e2a-b72d-d174b0f95d6d.png)| 🟢 Tracking Correctly |

**Contact Information**
| Interaction | Screenshot of Interaction | Screenshot of dL | Status |
| -- | -- | -- | -- |
| Clicks on Gender Identity edits (open)|![image](https://user-images.githubusercontent.com/91892981/166815095-ffc744fe-d73a-48fc-beb7-c9ca106a7c78.png)| ![image](https://user-images.githubusercontent.com/91892981/166815177-cab29c0e-88ff-447d-86f0-7b67a5de2f74.png)   | 🟢 Tracking Correctly |
| Count of successful updates (saves) |![image](https://user-images.githubusercontent.com/91892981/166815636-8384cc93-66e7-4cc2-9792-5c41b064713a.png)|![image](https://user-images.githubusercontent.com/91892981/166815735-3ed59b9d-fada-4167-b274-1983a3761f31.png)| 🟢 Tracking Correctly |
| Clicks to "What to know before you decide to share your gender identity"| ![image.png](https://images.zenhubusercontent.com/60e704a432c33f4d25bce83c/3edcbed5-b4f2-4c8d-a7f3-a32972cb4a6c) | ![image.png](https://images.zenhubusercontent.com/60e704a432c33f4d25bce83c/695f9da6-3f6f-4954-b557-fbacd265693d) | 🟢 Tracking Correctly |

**These will need to be fired off from the application when the action(s) are taken:**

**Data Layer**
| Interaction | dataLayer code |
| -- | -- |
| Successful retrievals of personal information from the backend | { event: 'api_call', api-name: 'Profile - Personal Information Retrieval , api-status: 'successful', api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" } |
| Failed retrievals of personal information from the backend | { event: 'api_call', api-name: 'Profile - Personal Information Retrieval', api-status: 'failed', 'error-key': '500 timeout message' api-latency-ms: 20000, api-request-id: "55d07138-4056-405f-b361-e03ef56a386e" }

**The event name can stay as is. The api-name should be updated. The other parameters are optional.**

**Comment by SKasimow** [comment]
hi @adamwhitlock1 - can you review this and point it? We'd like to include in this current sprint as it is high priority.

**Comment by adamwhitlock1** [comment]
Putting this at a 5 since I have never added analytics to an application as of yet. Hopefully it doesn't take me as long.

**Comment by adamwhitlock1** [comment]
I added the analytics for these events and they are live now in staging @SKasimow for validation. I would say that you can use DataSlayer as a way to validate the events, but I can also comment with some screenshots of the event data.

**Comment by adamwhitlock1** [comment]
Getting personal information (success)

![Screen Shot 2022-05-17 at 7.24.31 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/aaa28a86-5793-4986-9b52-736c5503eff5)

Getting personal information (failure)

![Screen Shot 2022-05-17 at 7.27.33 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/6c46ca58-ee30-4037-8b54-c593f8cb4275)

Saving Preferred Name (failure)

![Screen Shot 2022-05-17 at 7.26.09 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/5148d497-3f3d-443d-a16a-76add6d69957)

**Comment by SKasimow** [comment]
Completed - no issues so closing. See #40524
