### ISSUE TITLE
Keycloak Dev Cert refresh

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#41068]
Our Keycloak cert in dev has expired. We need to upload a new one to Keycloak Dev and Login.gov Sandbox.

Done when:
- [x] I can see a non-expired cert in login.gov sandbox
- [x] I can authenticate to an application via keycloak dev

**Comment by calquisola** [comment]
certs updated.

**Comment by kjduensing** [comment]
@calquisola what needs to be reviewed here? If nothing, let's go ahead and close it
