### ISSUE TITLE
AWS access for Ritesh Patel

### ISSUE THREAD

**Issue by iriteshp** [department-of-veterans-affairs/va.gov-team#41075]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Other

### Your Name

Ritesh Patel

### Your Email

ritesh.patel@adhocteam.us

### Your Team, Role, and Company

Access Management, Senior Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Saipriya Gopalakrishnan

### Product Owner (PO) name and email

Thomas D.

### Desired AWS Access

same as Carl Alquisola

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@iriteshp Which access do you need for AWS?

**Comment by kjduensing** [comment]
Ritesh is on the platform team AMT

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by jsgarmon** [comment]
AWS access has been granted, and first-time login instructions sent via Slack DM.
