### ISSUE TITLE
Design intent [My Education Benefits - Authenticated 22-5490 Form (Fry/DEA) Updates]

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#41082]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [ ]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [ ] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [ ] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [x] Product outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Form%2022-5490%20Updates/Product%20Outline.md 
 
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes
https://accenturefederal.invisionapp.com/freehand/22-5490-FryDEA-Design-Intent-Updates-VIQCynPNO?zoomToItems=Y2wyeXg0azdiMDBhcjN4NnNscWQ5cWZ5Mw%3D%3D

- [ ] User flow
- [ ] Research Plan
- [ ] Any other artifacts you have so far

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
closing this as Design Intent was skipped and [Midpoint Review held on 5/20](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41090)
