### ISSUE TITLE
[FE] Direct deposit: Error state for blocked routing numbers

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4109]
Waiting on copy from #4105

## Background

We have an error key `cnp.payment.routing.number.fraud.message` that we are currently showing an error message that doesn't really apply to this use case. After talking with some folks at EVSS and BGS, we have a better understanding of what is actually happening on the backend and what we should communicate to users on the frontend with regards to this error.

## Design and copy

Copy

**We can’t save your bank routing number**

We’re sorry. The bank routing number you entered requires additional verification before we can save your information.  To use this bank routing number, you'll need to call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday 8:00 a.m. to 9:00 p.m. ET. 

You can also update this information by mail or in person at a VA regional office. [Learn how to update your direct deposit bank information](/change-direct-deposit). 

![Profile with direct deposit_Edit modal open_Routing number error](https://user-images.githubusercontent.com/34068740/70833536-0900d100-1dc6-11ea-82a2-d834f29a40e5.png)

**Comment by erikphansen** [comment]
I actually have a branch up that lays the groundwork for this work. I just need to update the routing number flagged error message when the copy is ready: https://github.com/department-of-veterans-affairs/vets-website/tree/4109-new-fraud-error-messages

**Comment by Samara-Strauss** [comment]
Awesome. Sounds great, @erikphansen!

**Comment by Samara-Strauss** [comment]
@erikphansen design and copy are ready and shown in the first comment above. Feel free to ignore this until sprint 11. Address validation work should take priority right now.

**Comment by erikphansen** [comment]
This will be a very quick change and I might do it when I need a break from the address validation work

**Comment by erikphansen** [comment]
@Samara-Strauss In the other DD error messages the TTY number we use is 800-829-4833. Should we stick with that instead of the 711 in this ticket?

**Comment by Samara-Strauss** [comment]
> In the other DD error messages the TTY number we use is 800-829-4833. Should we stick with that instead of the 711 in this ticket?

@peggygannon can you answer @erikphansen's question above ☝️ ?

**Comment by erikphansen** [comment]
Here is my version of this new error. Note that the error alert is directly below the modal's headline. This is consistent with the position of all the other errors. The mock positions the error lower in the modal. If you'd like I can move all the errors down to match this mock.

<img width="484" alt="Screen Shot 2019-12-17 at 9 23 38 AM" src="https://user-images.githubusercontent.com/20728956/71019526-4fe51400-20af-11ea-8905-e67fd4ac9370.png">

**Comment by Samara-Strauss** [comment]
@erikphansen this looks great. Let's leave this open until we hear back from Peggy on the phone number question.

**Comment by peggygannon** [comment]
@erikphansen Hello, let's use the same TTY number we use for the other DD error messages, so we're consistent. Thank you for checking in.

**Comment by erikphansen** [comment]
final screenshot in the PR https://github.com/department-of-veterans-affairs/vets-website/pull/11342

**Comment by erikphansen** [comment]
If we have a routing number that's been flagged by BGS or the fraud team, we can validate this on staging. Otherwise we can just close this. @Samara-Strauss @Justin-Pickett

**Comment by Samara-Strauss** [comment]
I reached out to the BGS team to see if we can get one of the routing numbers flagged for fraud. If we can't get that from them, we can close this. In the meantime, let's leave this open in case we hear back.

**Comment by Samara-Strauss** [comment]
Validated on staging with one of the routing numbers they sent along. Closing!
