### ISSUE TITLE
Implement solution for frontend app error alerts

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#411]
## User Story
As a VSP team member, I need to get frontend app error alerts in a timely and accessible manner so I can be aware of and respond to issues more quickly.

## Goal
VSP team members are able to receive and understand frontend app error alerts.

## Acceptance Criteria
- [ ] these AC are dependent on the discovery done in #410

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
We've got an on-point rotation outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Triage/On-point%20Rotation.md) that we're doing to clean up the alerts before we can use them. I think that pretty much fulfills the goal of this ticket.
