### ISSUE TITLE
[AXE-CORE, COGNITION]: Ensures input buttons have discernible text

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#4110]
# [AXE-CORE, COGNITION]: Ensure inputs have discernible text

## Description

The select element for Service Type does not display the complete text for each option. The options are too long to appear within the select element, are cut off, and it is impossible to discern what options are available. 

## Point of Contact

Jennifer Strickland

## Acceptance Criteria

As a VA.gov user, I want to choose from a list of service type options to to understand the full range of options available to me, in order to refine my search for service types, so I may find the location best for my needs.

## Environment

* Operating System: all
* Browser: all
* Server destination: https://www.va.gov/find-locations

## Steps to Recreate

1. Enter `https://www.va.gov/find-locations` in browser
2. Enter a city, state, or Zip Code in the input for Search city, state, or postal code
3. Select Community Care in the Search for [All Facilities] dropdown
4. Begin typing in the Service type combobox, for example, `dieti`
5. Verify that the options available are cut off in the display

## Possible Fixes (optional)

If it is possible, use `<optgroup>` to break items into groups and ensure options are never longer than 23 characters. On mobile, a select element can only display about 23 characters. 

## WCAG or Vendor Guidance (optional)

[axe-core 3.0 Links must have discernible text](https://dequeuniversity.com/rules/axe/3.0/link-name)

[axe-core 3.1 Buttons must have discernible text](https://dequeuniversity.com/rules/axe/3.1/button-name?application=lighthouse)

## Screenshots or Trace Logs
<img width="1103" alt="facility-locator-select1" src="https://user-images.githubusercontent.com/57469/70566175-91cb0300-1b61-11ea-8cb5-80f73f462735.png">
<img width="1057" alt="facility-locator-select2" src="https://user-images.githubusercontent.com/57469/70566182-955e8a00-1b61-11ea-95d6-9c2bb13f1c39.png">

**Comment by mmiddaugh** [comment]
This issue is resolved with UX changes. Closing this issue.
