### ISSUE TITLE
Contact Center Review for Auth-Profile | Personal Information Revisions 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41110]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
- Authenticated Profile section of VA.gov
### Launch Date
*Please provide the launch or rollout date and details.*
- Target is early June 2022

### Version Number
*Please provide the version number of the guide and/or video.*
- Version 5

### Product Guide
*Please provide product guide link*

[Product guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/VA.Profile.Product.Guide.version.5.05092022.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
Hi @starlow00! We're planning to launch some updates to the Personal Info section of the Profile feature in early June. The Staging review isn't scheduled until May 24th btw.

Additionally, we updated the Direct Deposit section to begin showing this feature consistently (vs conditionally); this will likely be launched around the same timeframe.

Lastly, we updated the overall doc to Brin current ---  so thought better to send sooner vs later to give you some time to digest.

Please ping with any q's!

Sharon

**Comment by starlow00** [comment]
HI @SKasimow. I follow the link above, but I'm not able to get to a point where I can view or download the Word doc. I can get to the .docx link, but that's it.

**Comment by SKasimow** [comment]
Hi @starlow00 - not sure what happened but I've updated the link; please lmk if you are able to download the doc now. If not, I'll just slack it over.

**Comment by starlow00** [comment]
Looks like that worked. Thanks, @SKasimow!

**Comment by SKasimow** [comment]
kewl - thank you!

**Comment by starlow00** [comment]
Hi @SKasimow. My draft review is attached. There are a few questions marked on the file.
[VA.Profile.Product.Guide.5.05092022_srt_05102022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8674083/VA.Profile.Product.Guide.5.05092022_srt_05102022.docx)

**Comment by SKasimow** [comment]
@starlow00 thanks Steve - I should be able to review this afternoon.

**Comment by starlow00** [comment]
Thanks for the share, @SKasimow. Edits look good! I shared with VEO for review.

**Comment by SKasimow** [comment]
Nice - thanks @starlow00   Lmk when ok to close out...

**Comment by SKasimow** [comment]
Closing....
