### ISSUE TITLE
Investigate HLR + NOD submission establishment

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#41127]
# Background
Both the HLR form and the NOD form have shown a large number of submissions that are not getting automatically established on submission. We need to investigate this issue and find out the root cause so that we can then fix that root cause.

## Tasks
- [x] Investigate HLR and NOD form submission establishment issues

## Acceptance criteria
- [x] We now know what is causing the HLR and NOD issues

**Comment by michelpmcdonald** [comment]
Lighthouse has merged in a fix, claim status are now updating as as expected, no vets-api code changes needed

**Comment by michelpmcdonald** [comment]
closing

**Comment by michelpmcdonald** [comment]
Lighthouse has merged in a fix, claim status are now updating as as expected, no vets-api code changes needed
