### ISSUE TITLE
Access for Lance Sanchez

### ISSUE THREAD

**Issue by darkbushido** [department-of-veterans-affairs/va.gov-team#4112]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Lance Sanchez
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > vsa-facilities, Senior Backend Engineer, GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDrcaIr/xyu8xR8TsUoiGy8VH/05tr4IPVaHnRQ8e8DC lanceweston@USRMonitors-MBP.guest
```

- [Grant AWS Console access?]
  > YES

**Comment by darkbushido** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Lance Sanchez
COR: Mary O'Toole

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.

**Comment by darkbushido** [comment]
Thank you, I will need AWS access.

**Comment by ricetj** [comment]
Per instructions here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md#additional-onboarding-steps-for-developers You will need to have submitted your eQIP, before being cleared for AWS.

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for AWS.

**Comment by jbritt1** [comment]
Initial login credentials / instructions provided via Slack DM.
