### ISSUE TITLE
Log LOA3/IAL2 records with incomplete birth_date values 

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#41137]
Certain records have incomplete birth_date values (format YYYYMM instead of YYYYMMDD), and get parsed as `birth_date=nil` in our MPI profile parser. These are IAL2/LOA3 records, and should have a complete birth_date. We should log these occurrences (with an ICN), and then, according to Damien: 'a ticket could be opened HcIDM may be able to review and update primary view based on the DOB available in correlations'

**Comment by bramleyjl** [comment]
Code for parsing MPI dob is in production; the Identity team is still looking for any of the MPI attribute parsing (name, ssn, dob) logs to appear in production.

**Comment by alyssagallion** [comment]
Joe looking for production logs today to build out DataDog component. Will close after.

**Comment by joeniquette** [comment]
Datadog monitor setup: https://vagov.ddog-gov.com/dashboard/3di-esj-7wy/identity-log-queries?tpl_var_deployment_env%5B0%5D=*&from_ts=1671534528336&to_ts=1671548928336&live=false&tile_focus=8390292325952346
