### ISSUE TITLE
PROTOTYPE- How do we Dynamically Show the "Page all in Spanish soon" Message

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41145]
## AC
- How can we dynamically show the "Page will be in all Spanish soon" message
   - Pull from english json if not in the spanish one; having to do this will trigger the message to be displayed
- How do we NOT use auto-translations but use the English if it's not translated

**Comment by brianseek** [comment]
It is possible to create a dynamic message, but we reach a consensus that it would be better to display an ever-present notification on every page for a language that is missing parts of the translation. This way the vet knows what to expect though out the app.

We discussed adding this to a header component. There is an existing ticket out there already: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/41229
