### ISSUE TITLE
STAGING: VAOS displays "Cancelled by facility" instead of "cancelled at your request" 

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#41152]
This is a minor subissue related to https://issues.mobilehealth.va.gov/browse/VAOSR-3222

Steps:

1. Enter a request in VAOS.
2. Find the request in Schedule Manager. 
3. Cancel the request; select the reason "Cancelled - Cancelled at Veteran Request." Save. 
4. Return to VAOS, refresh, and pull up the now cancelled appointment. 
Expected result: the detail says "You cancelled this appointment. If you still need an appointment, call us or request a new appointment online." 
Actual result: the detail says "cancelled by facility." 

![cxl.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/be906f70-325e-4b1a-8424-d2db99e4e570)

**Comment by simiadebowale** [comment]
For this appointment, we're getting the cancelationReason as "other" from the api response, this is why we're displaying "Facility canceled this request. If you still need an appointment, call us or request a new appointment online." in the UI. ![Screen Shot 2022-05-24 at 12.21.39 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/419acfd9-3d59-402b-bec3-d3daa29d32c7)
![Screen Shot 2022-05-24 at 12.27.13 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/d9178123-7cf2-4140-8015-5711c492a3bd)

To display "You canceled this request. If you still need an appointment, call us or request a new appointment online." in the UI, we expect the cancelationReason to be "The appointment was cancelled by the patient" with code "pat" as seen below:
 ![Screen Shot 2022-05-24 at 12.26.18 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/783c4bcf-d913-433b-a9c2-76ed41d89216)
![Screen Shot 2022-05-24 at 12.26.52 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/a38350ba-6574-4713-8076-9e554ec306ca)

@ajmagdub @cferris32 can we confirm that we are mapping the correct provider_message/veteran_message for this endpoint in Vets-api. Thank you
cc: @beth-wodzinski @JRRoof

**Comment by simiadebowale** [comment]
kidys.b.quankep@id.me can be used as a test user in staging.

**Comment by simiadebowale** [comment]
kidys.b.quankep@id.me can be used as a test user in staging.

**Comment by ajmagdub** [comment]
@simiadebowale verified that Vets API passes through the appointment detail body from VAOS Service to Vets Website. No mapping is performed.

**Comment by ldelacosta** [comment]
@marcynadeau @beth-wodzinski - can you please confirm if this issue still exists? Simi reviewed the ticket and seems like this is working fine in the FE and may be a VAMF backend issue. Thanks.

**Comment by beth-wodzinski** [comment]
Yes, I still see this issue. I just repeated it with grethel.g.petryniec@id.me; appointment request for Ft Collins Audiology. 

![image.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/0643fe70-72a2-43a2-8a26-1416d76b61c3)

**Comment by marcynadeau** [comment]
@simiadebowale I pulled the response body for the above cancellation that Beth did and it does show the wrong wrong cancel reason data. I will log a backend ticket.  



        "cancelation_reason": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/appointment-cancellation-reason",
              "code": "other",
              "display": "Other reason"
            }

**Comment by marcynadeau** [comment]
@ldelacosta @simiadebowale You can close this ticket as this is a backend issue.  I will create a JIRA ticket for this.

**Comment by ldelacosta** [comment]
This ticket is closed. SQA team will log a backend ticket.

**Comment by marcynadeau** [comment]
JIRA ticket logged:  https://issues.mobilehealth.va.gov/browse/VAOSR-3710
