### ISSUE TITLE
Review incident categorization documentation - Updates and Tasks

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41151]
based on [Incident Documents Review issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36810)

## Tasks/Updates from Review

- [  ] Are there too many categories?
- [  ] It seems severe and critical are quite similar?
- [  ] How do we define a timeline for varying levels of urgency?
- [  ] Are there SLAs that can guide how quickly or how urgent we should respond?
- [  ] Can we draw a line between issues that on-call personnel receive versus things that are classified as incidents? Or that - [  ] require an incident commander?
- [  ] Are minor incidents actually incidents? Or are they just issues?
- [  ] Which environments does this apply to? For minor, normal, and major, the categorization does not currently require escalating to the incident commander? Do we want to rope in the IC role for those incidents? During business hours? During off hours?
- [  ] Is there an incident issue template?
- [  ] How does the IC get updated if a M/N/M incident occurs and they were not paged?
- [  ] How do we communicate M/N/M incidents between the on-call personnel and the IC?

**Comment by alyssagallion** [comment]
We have outlined these items in this document: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Platform+Support+Best+Practices

- Severity Levels (More categories and sense of urgency)
- SLAs

Additionally, we have created an outline of Incident Commander best practices, which is on both of these pages:

- https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Platform+Support+Best+Practices
- https://vfs.atlassian.net/wiki/spaces/PTST/pages/2442854463/Incident+Commander

Closing this ticket.
