### ISSUE TITLE
Test Sign in Service with Safari Browsers

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#41157]
Currently users on production cannot login to va.gov through SSOe when using Safari browsers and iOS webkits (iOS device browsers).

This impacts roughly 40% of our user base. The Sign in Service may allow users to login through Safari browsers. This ticket is to conduct those tests.

**Comment by joeniquette** [comment]
Tested on safari browser in a mac with this URL: http://staging.va.gov/sign-in/?application=vamobile&oauth=true&code_challenge=1BUpxy37SoIPmKw96wbd6MDcvayOYm3ptT-zbe6L_zM=&code_challenge_method=S256

I was able to login successfully with a login.gov (joe.niquette+lgovial2@oddball.io), idme (ssoissoetesting+SPO1@gmail.com), and DSLogon (ace.a.mcghee1) account.

I am unable to test with MHV because I dont have Safari on CAG.

**Comment by nsoutouras** [comment]
Need to find a way to test mobile app stuff. @nsoutouras

**Comment by joeniquette** [comment]
The testing is complete for this. We have another ticket which is focused solely on MHV related tests for our USiP.
