### ISSUE TITLE
Incident playbook document review - Updates/Tasks

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41153]
# Updates/Tasks

- [x] Correct mentions of vets.gov
- [x] Should we separate incident comms from oncall comms?
- [x] Should we have dedicated channels for incidents? Security incidents? VFS incidents? Platform incidents? etc
- [x] Do we still want to broadcast updates to oncall Slack?
- [x] Do we want to leverage Datadog for declaring incidents?
- [x] Let's make sure security-related incidents and points of contact clear
- [x] It looks like the Security Incident Response document is out of date
- [x] Is the Canary Alerting best practices still relevant and up to date?
- [x] What does it mean to "find the dashboard"? Where are those found? Which ones are to be trusted and utilized by the SRE team?
- [x] Where are SLO's and SLA's documented?
- [x] How do we define priority levels?
- [x] What's the difference between impact assessment and categorization?
- [x] Who is the Information Security Office?
- [x] Who is the Privacy Officer?
- [x] Under troubleshooting? Is there a best place to capture notes?
- [x] Can we clarify what it means to "force breaker"?
- [x] Is the contact information and procedures up to date in the external services integration documentation?
- [x] Under restore service: Should the goal of incident response - from the SRE perspective - include active fixing of issues? What's the best handoff of responsibilities from SRE to SMEs during an incident?
- [x] Who is responsible for restoring primary branches to a deployable state?
- [x] Where do we mark the incident as resolved?

Also these things (there may be overlap)
## User Story

Need to update the Incident Commander and Incident Playbook documents to reflect the changes made to the platform team (loss of SRE team, addition of tech support team, etc.) as well as clarity around steps that need more details.

---

## Acceptance Criteria

- [ ] Documents are updated to reflect the updates to the teams and role of the Incident Commander
- [ ] Documents are updated to ensure all steps are clear and detailed
- [x] Documents are published and available on web site
- [ ] Teams are made aware of the updates

## Additional information

Here are the specific documents to update:

[Incident Playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook)
[Incident Commander](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2442854463/Incident+Commander)

**Comment by rmtolmach** [comment]
✅ I deleted the old incident commander page (with lots of references to SRE) and replaced the incoming links (pages that linked to the old page) with [the new page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2442854463/Incident+Commander).

- Should we have dedicated channels for incidents? Security incidents? VFS incidents? Platform incidents? etc
  - This usually is not needed. The thread in #vfs-platform-support is usually good enough. Sometimes it gets long, but I believe it's best to have the conversation in one spot to keep the postmortem easier to do. If the IC and the SMEs feel the need to make a temp channel for a longer incident, that's fine. This is documented in the IC documentation.  
- Should we separate incident comms from oncall comms?
  - I don't really know what this means, so I'm going to just check it off 🤷 
- Do we still want to broadcast updates to oncall Slack?
  - No.
- Do we want to leverage Datadog for declaring incidents?
  - "declaring incidents". I don't know how that would work. We are often alerted via Datadog that there is an incident. Not sure how declaring an incident in dd would help 🤔 
- ✅ clarified the security sections.
- Is the Canary Alerting best practices still relevant and up to date?
  - don't see this mentioned anywhere anymore.
- What does it mean to "find the dashboard"? Where are those found? Which ones are to be trusted and utilized by the SRE team?
  -  N/A. There are a couple dashboards listed and linked. 
- Where are SLO's and SLA's documented?
  - ❓ SLOs and SLAs for the IC or for the product? I'm going to guess the IC. I've commented in the IC docs: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2442854463/Incident+Commander?focusedCommentId=2704244985
- How do we define priority levels?
  - There's a section about this in the Incident Playbook: Classifying the Incident
- Who is the Privacy Officer?
  - ❓ Not sure. Asked in https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook?focusedCommentId=2704539977
- Is the contact information and procedures up to date in the external services integration documentation?
  - yep. done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/54574

**Comment by rmtolmach** [comment]
✅ We don't need to worry about the privacy officer. The privacy office takes care of that.

I updated and reorganized The incident Playbook: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook

**Comment by rmtolmach** [comment]
I'm updating some github docs as part of this
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1066

**Comment by rmtolmach** [comment]
I deleted a large section titled "Critical Communication Channels" because this is already talked about in multiple places in the Playbook: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook

All docs have been updated ✅
