### ISSUE TITLE
Add Incident to Support Bot Nature of Request List.   Topics in Spreadsheet.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41155]
Add new topic to Slack Bot support Nature of Request list.

- [  ] Update the Google Spreadsheet topics and add a Topic:  "va.gov Incident"

**Comment by zachclarity** [comment]
[comments from Slack](https://dsva.slack.com/archives/C02RLAUM2LV/p1652211267982449) :  My guess is that only the owner has permission to edit that tab, and the owner is [archivedaccounts@adhocteam.us](mailto:archivedaccounts@adhocteam.us). I may have to reach out to ad hoc IT to try and change the owner.

**Comment by zachclarity** [comment]
Permission was granted to @powellkerry

**Comment by powellkerry** [comment]
Ad Hoc IT transferred ownership of the Google Sheet to me, and I was able to edit the Topics sheet. I have also updated the permissions to include @zachclarity and @gperlangeli as editors on that sheet
