### ISSUE TITLE
[UX] Submit Round 2 Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41164]
## Additional sentence that needs to be translated
- 'This feature will be available in Spanish soon.` (OR WHATEVER THE SENTENCE WILL BE)

## Epics whose Translations should be included in the submission
- [LoROTA Security Updates ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39193)
- [Update Error Messages](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38136)
- [Telephone Appointments](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38258)

**Comment by loripusey** [comment]
@kristenmcconnell @niradatta1 @brdunfield 
- I create one ticket for the round 2 submissions of the translations and add it to the 4 Epics for which we need to include content
- I deleted the individual tickets in each epic
- I also referenced the sentence we need translated
Please add anything else to this ticket and add a link to the files when they are done.

cc: @sarahknoppA6 @acrollet

**Comment by niradatta1** [comment]
Adding "sign in " to Round 2 per https://dsva.slack.com/archives/C02GXKL8WM6/p1652211381244659

**Comment by kristenmcconnell** [comment]
@loripusey The cancelled appointment wording ticket hasn't been worked on yet. With the timing that we want to get round 2 translations out the door, we don't believe the cancelled appointment work can be included.

**Comment by loripusey** [comment]
@kristenmcconnell I will remove cancelled appointment from the list for this ticket then, thanks

**Comment by brdunfield** [comment]
[https://app.zenhub.com/files/133843125/1f9af868-8f58-496a-95c1-54326bbdaa5a/download](https://app.zenhub.com/files/133843125/1f9af868-8f58-496a-95c1-54326bbdaa5a/download)

Here's the JSON file for Round 2. It won't let me upload the JSON file directly so I've just zipped it up.

**Comment by niradatta1** [comment]
Danielle has sent the JSON to the State.
