### ISSUE TITLE
BE | Profile | Set Up Monitoring & Slack Alerts 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41176]
Setup monitoring and alerts for a single BE endpoint (TBD) in the vets-api so that the Profile team is alerted when:
- a 500 error occurs
- the rate of 400-range errors increases for a given period of time.

The goal is to set up something simple for single endpoint.  Once we feel the setup and configuration is working the way we want, we can start applying monitoring and alerts to additional endpoints using the same (or similar) configuration.

Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/40627.

## Tasks
- [x] Create a Auth Exp dashboard in Datadog.
- [x] Create monitors and alerts for when the rate of 400 range errors crosses a threshold.
- [x] Test monitors.

## Acceptance Criteria
Alerts should be sent to the Profile team's [Slack channel](https://dsva.slack.com/archives/C02SYJGH8FJ).

**Comment by tpharrison** [comment]
@SKasimow I've updated the ticket description - please review.  I estimated this at 3pts - even thought the setup in Datadog should go quickly, I think it will take more time to test that the monitoring and alerts are working properly.

**Comment by SKasimow** [comment]
@tpharrison Thanks Tom - looks good. I will set up some time for us to review all the alert tickets.
