### ISSUE TITLE
DE | Profile | Bad Address Indicator | Conversation Guide

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41174]
Placeholder....

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss -- Here is the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/research/conversation-guide.md) for review. I mentioned this in the research plan ticket, but I'll need to talk more with Mark and Adam when back next week to understand what is most feasible for them to do for testing (prod, CodePen, staging - see [comment in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1653517608262249)), so for now I've included info for both! Depending on the conversation around this, I foresee some of these questions extending partially into next Sprint.
Thanks!

**Comment by Samara-Strauss** [comment]
This is probably a first for me, but I don't have any feedback. This looks good, and we can adjust as needed once we decide on the specific method (code pen, prod, etc) for testing going forward.

**Comment by SKasimow** [comment]
@cgednalske - same, looks good!

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow awesome! 🎉  That's great news. Sounds great - will update with any adjustments that come out of our upcoming discussion on testing methods.
