### ISSUE TITLE
SOCKS access for Jack Watson

### ISSUE THREAD

**Issue by 94Jwatson** [department-of-veterans-affairs/va.gov-team#41189]
### Your Name

Jack Watson

### Your Email

j.watson@theta-llc.com

### Your Role and Team

Held Desk Support

### Product Manager (PM) name and email

@cmaeng 

### Product Owner (PO) name and email

@davidconlon 

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/x6a3WpuIejarc+TYo++AAisB4sX5Xj2LCJPIUP3xQ12PFizcHWxHJXXkqpgk0FoLMczMFdKQEh+PDMohg7PS0v+SSU4fhTKMVE/mdR5UKR7yYl3+MggctkdmndjdOqQ++O+EXPS5UoshYJumgYQw7hcIX9QdBrHPI7jSovHMdisI3hlTryTUCK/K6wjYiW0MzWJMf1AncrtPGbwy5mbD8eHceElfhaWOU185TIT+PPReqOcWJGypnCCsw/X7WLT7qTxEUw+NVzKzGkpNYenkUjRuIqOjK6ghwSnc2urm/kOuz8hGbKwibtdoQBpP2OSGm2rbRp70hSIv1bhyPYbBZarnBhxdLb0PPmlJqe9tHOsPyxJxWHf6QsPqa2J6N3f/q9IBV7rXHa9MzrSrBWQNa29RyQRMLSQCmAngn6y6LRY438CebLzmrysXoKmljMtdGLYz36kJ+SnEd0VMGwBjKMc/MApIaI1UdUuU9f0himSBBVWH6oMjpMXsXRHJajE= jwatson@Jacks-MacBook-Air.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Hi @94Jwatson! We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with [this platform orientation guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). If you're not newly joining the team, please reach out to your PM or PO for help.

Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by cmaeng** [comment]
thanks for your help on this @kjduensing . Jack is part of the helpdesk support team for the VFS-CMS / Sitewide crew projects. i don't think we've traditionally added our folks to the VFS team roster that this ticket is pointing to. how should we proceed?

**Comment by cmaeng** [comment]
@kjduensing i see some of our folks on there but not all and am unclear on the intake process for that sheet. who owns that sheet and what is it's purpose?

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
