### ISSUE TITLE
vets-json-schema repository access request

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#41191]
## Description
I'm looking to get access to the `vets-json-schema` repository for an issue I'm currently working on.

## Background/context 
I'm a newer engineer on the Benefits/Claims & Appeals team.

---
## Tasks
- [ ] access to `vets-json-schema`

**Comment by zachclarity** [comment]
Slack Thread.  https://dsva.slack.com/archives/CQHBJ5U06/p1652793729955719
