### ISSUE TITLE
Test Triage Incident Template

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#412]
### Status

[UNRESOLVED, RESOLVED]

### Severity Analysis

*Estimate of how critical this bug is*

- `sev 1` 
    - Immediate resolution needed
    - Critical incident
- `sev 2` 
    - Needs a special deploy
    - Needs SME
    - Regression that went uncaught in dev/staging
- `sev 3` 
    - Can go out in a regular deploy but still needs fixed ASAP
    - Can be put into the owning team's backlog and scheduled by PM

### User Impact 

- *Who is the user impacted by this problem?*
- *How does this problem affect the user?*

### Description

- *In one or two sentences, what is happening?*

### Steps to Reproduce

- *List steps required to reproduce the issue in question*

#### Expected Results

- *example:* 

  > The user is redirected to `profile`

#### Actual Results

- *example:* 

  > The user is redirected to `/` (the home page)

### Further Details
*Add any of the following as available:*

- Sentry Issue Link
- ServiceNow (or other source) link
- Components, Transaction, URL
- Platform, User Agent, Browser, Version
- Screen size, viewport, zoom level
- Screenshots

### Proposed Solution

- *Summary of solution*
- *Link to related tickets*

**Comment by lisac-usds** [comment]
Hi @minafarzad , @alexpappasoddball , do you have a preference for the `Template name`, `About` , or Optional additional items ? 
![Screen Shot 2019-06-28 at 14.41.04.png](https://images.zenhubusercontent.com/5ab11af44b5806bc2bcb9da5/7238e747-25e7-451b-821d-ce18659265f3)

**Comment by alexpappasoddball** [comment]
Triage Incident Template should be just fine!

**Comment by minafarzad** [comment]
we've confirmed everything works :)
