### ISSUE TITLE
Migrate Databases to VAEC

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4120]
## Problem Statement
In order for the VA to perform Database scans, they first need access to the DBs. Right now they can not access our DB, so we need to migrate them which will unblock the VA from doing the scans.

## Goal
_DBs migrated to the VAEC_

## Acceptance Criteria
- [ ] _Test to see how much downtime will happen_
- [ ] _Let others know about the mirgation_
- [ ] _Migrate the DBs_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nwalke** [comment]
Move from `dsva-vetsgov-*` to `dsva-vagov-*`

**Comment by nwalke** [comment]
Migration test notes:
```
Restored a dsva-gi-bill-data-service-prod snapshot to dsva-gi-bill-data-service-prod-restore-test in the same vpc and subnet groups (dsva-vetsgov-prod-gov (vpc-7a7f941f), dsva-gids-prod-db-sng) and security group (dsva-gids-prod-rds-sg (sg-d851e6bd)) as a multi-az instance.
Switch to single AZ at 4:41 p.m.  Finished at 4:47 p.m.
Started move to subnet group dsva-vagov-prod-cms-rds-sng and security group dsva-vagov-prod-cms-rds-sg (sg-b38bb3d4) (vpc-d50f49b0) at 7:40 p.m.  Finished at 7:47 p.m.
Switch to multi AZ at 12:30 a.m.  Finished at 12:42 a.m.
```

**Comment by nwalke** [comment]
Connection string stays the same between VPCs.  The proper subnet and security groups need to exist in the new VPC before you attempt the migration.
