### ISSUE TITLE
SOCKS access for Ryan Shaw

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#41207]
### Your Name

Ryan Shaw

### Your Email

ryan.shaw@adhocteam.us

### Your Role and Team

Senior Software Engineer, VAOS

### Product Manager (PM) name and email

Jeff Roof, jeff.roof@adhocteam.us

### Product Owner (PO) name and email

Lauren Alexanderson, lauren.alexanderson@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRd+iWanHISd7bbsyTdOO8hJSvGubPJQi7Snj0L8OA4J6z7Qwr38Gz2EYm0rJ9FIkORYJVFcC4m1RBL7zP824RUeQ+xmfqS228l2IK7wz33wMk0K4JzGIKfhEDT2DY3wVcouAXGtEgjGmSGBpmtcjhF4a5lIdZhgqkDJaIsHog1YV81V7LRK46wlhuVMpsgD5heN7uNllh+XG2Wm/wiMBoLckReMXaJIf2nZTOLqtFPUs+g2WInS5xMcdHJcq3nAwxJ6I6EjIyt8eYFv4T+cKHe1/5nRQ+GlQ6TujiQGBT9jKP1Gwjmh5ktUDLFdWoAjiSDKpWLzp0ClvJ6Z7y9ajffHXtc7NnIfRSTkxr5b7/s5GizOScr6CIYXt3xSgV+fLGvucdzY4L50EQXc0D6gphSu2JYfyZy6dgUHEe1sxlYAGD16NiPQjiuVlp+mH8oEht8ehhgCQu3/VEbo3YJrDvmwrfaNisUYs9mNll8BGytbpcLU06PDCnJVfuWvlOU2U= ryanshaw@ryanshaw.lan

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Ryan found  in the VFS Team Roster

**Comment by kjduensing** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
