### ISSUE TITLE
Create IAM "devops" group with Resource-Scoped Administrator Permissions 

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#41203]
# Description
As a devops engineer, I will initially be given admin access to all the things. Becoming familiar with the resources we, the identity team, maintain, I will be able to create resource-scoped admin permissions policies to apply to an `identity-devops` IAM group using [permission boundaries for IAM entities](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html).

This "could" be the basis for a generic devops engineer IAM group, but since all embedded devops engineers will be managing different resources, this may not be possible/applicable and/or continually be a work in progress.

# Acceptance Criteria
- Default and/or Custom AMI policies
- an `identity-devops` IAM group created with the appropriate resource-scoped admin IAM policies (e.g. permission boundary)
- possibly a "default" devops IAM policy / group (e.g. again, using permission boundary)

[more info](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2110029855/Grant+Resource-Scoped+Administrator+Permissions+to+Non-Infrastructure+Platform-Team-Attached+DevOps+Engineers)

- resources
    - https://policysim.amazonaws-us-gov.com/
    - https://carriagereturn.nl/aws/iam/policy/boundary/2021/10/07/iambound.html
    - https://www.applied-insight.com/bound-those-permissions/
    - https://aws.amazon.com/premiumsupport/knowledge-center/iam-permission-boundaries/

**Comment by jhouse-solvd** [comment]
@ianhundere - Please update the status when you return. :)

**Comment by ianhundere** [comment]
currently auditing resources against devops engineers access of resources via cloudtrail; ex:
`aws cloudtrail lookup-events --lookup-attributes "AttributeKey=Username,AttributeValue=Ryan.Beckwith" --query 'Events[].[EventTime,EventName,Username,EventId]' --output table`

**Comment by ianhundere** [comment]
reading a variety of best practice guides for configuring permission boundaries.

**Comment by ianhundere** [comment]
testing with policy simulator i have the following working w/ the perm boundary:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/1983ed79-c08d-4460-ab26-dc1e9da3f471)
![image.png]
(https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/9d16e197-4a2b-4ae1-87a0-e511c3bc32ac![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/8c441bd9-41c4-47c3-8c6b-e66ad4c13e77))
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/af9388da-4797-4609-8e85-754cefa003f3)
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/88d09bb4-5800-435b-b961-a04750325e7e)
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/9bd056a8-7581-479a-85b9-992dc49d5a82)

**Comment by ianhundere** [comment]
looking at what actions we might want to deny:
cloudtrail
```
"cloudtrail:DeleteTrail",
"cloudtrail:StopLogging",
"cloudtrail:UpdateTrail"
```

eks
```
"eks:DeleteCluster"
```

ecs
```
"ecs:DeleteCluster"
```

rds
```
"rds:DeleteDBCluster"
```

elasticloadbalancing
```
"elasticloadbalancing:DeleteLoadBalancer"
```

ec2
```
"ec2:DeleteVpc"
ec2:TerminateInstances"
```

**Comment by ianhundere** [comment]
posted it to [the confluence page](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2110029855/Grant+Resource-Scoped+Administrator+Permissions+to+Non-Infrastructure+Platform-Team-Attached+DevOps+Engineers)

**Comment by jhouse-solvd** [comment]
There is a follow-up issue (#45254) to develop the MVP of a permissions boundary for Platform DevOps personnel. 

This issue can be closed.
