### ISSUE TITLE
[FE] My VA - Health Care section: Release Next Appointment API in coordination with VAOS

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#41202]
## Background
Per the work completed in #40115, Mark has updated the Next Appointment API connection from v0 to v2 and is sitting behind our own feature flag at the moment. It's ready to be released when VAOS team is ready to go to prod on their end, which they anticipate doing by the end of the month (May).

### Resources:
- [V0 documentation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/docs/vaos/v0/vaos.yaml)
- [V2 documentation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/docs/vaos/v2/vaos_v2.yaml)

## Tasks
- [ ] launch v2 of the Next Appointment API connection to prod (`profile_use_vaos_v2_api`)
- [ ] Validate for any issues 

## Acceptance Criteria
- Service is updated in production to v2

**Comment by ajakabcin** [comment]
Moving out to sprint 77 - VAOs is working through some issues on the v0 to v2 transition and needs additional to work these out. We may need to make other changes to thing on our side but we won't likely know until things go to prod. Holding on this release for a few more weeks.

**Comment by ajakabcin** [comment]
@mdewey I'm still waiting to hear from VAOs on this so for now I'm going to leave in our backlog and will pull into our sprint if we need to hit go on it. Thank you!

**Comment by ajakabcin** [comment]
Per [slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1663877653137729) VAOS is planning to turn on v2 on Nov 15.

**Comment by tmitchellgcio** [comment]
@mdewey is v2 launched? If so I will work on this soon, just want to be sure it's good to go first

**Comment by ajakabcin** [comment]
@tmitchellgcio we need to check in with the VAOs team on this. For now you can leave it be until we get word from them.

**Comment by Samara-Strauss** [comment]
Closing! [We just went to 100% today](https://dsva.slack.com/archives/CMNQT72LX/p1671460002501459).
