### ISSUE TITLE
[FE] [Discovery] 10-10EZ: Errors on form for unauthenticated applicants due to missing data

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#41232]
## Background

The Backend says the applicant is logged out, and data is missing (name, ssn, dob)
May happen when applicant is logged in, fills out form, allows page to time out, then tries to submit form.  
Logging has been added as part of #40039. implemented evening of 5/11/2022.

## Tasks

- [ ] Additional research using logging and workflow is needed to determine the cause of this issue

## Acceptance Criteria

- [ ] Research the issue to determine root cause and potential solutions

**Comment by hdjustice** [comment]
@markfallows - FYI this ticket was created during grooming today

**Comment by markfallows** [comment]
Issue may have been resolved.  Keeping open for additional tracking to confirm.

**Comment by markfallows** [comment]
This has been addressed in another ticket.
