### ISSUE TITLE
[FE] 10-10EZ-Short Form: Research on adding feature flags to Short Form coding in Staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#41239]
## Background
Initially, the Short Form code did not include feature flags due to the immense amount of code being managed and updated.  Now that we are about ready to deploy into Staging environment, there is strong urging to put the feature flags in place to avoid the code being delivered to production at 100%.

We need to do some research around how to implement feature flags with the least amount of effort, and without having to re-code the work already done.

## Tasks
- [ ] Research feature flags for the Short Form code

## Acceptance Criteria
- Research completed on adding feature flags for the Short Form code and determine whether it is feasible.

**Comment by batemapf** [comment]
Suggest reaching out to the platform FE team for their take (likely via #vfs-platform-support in Slack). Also tagging in @stephenBarrs for his thoughts. @stephenBarrs might be some parallels here with the coronavirus research V2/update form, where we're doing a big update to an longstanding form that we want to release in a controlled manner.
