### ISSUE TITLE
[EC2 AMIs] Upgrade base images to Amazon Linux 2

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#41247]
## Description 
The base images that we use for deploying instances are using Amazon Linux 1 (AL1). AL1 is slated for its end of life (EOL) in the near future. Additionally, there are limitations related to package management that would be avoided by upgrading Amazon Linux 2 (AL2). 

## Hypothesis or Bet
If we upgrade the base image(s) from AL1 to AL2, then we expect to be able to re-deploy instances using the new image. 
If we upgrade the base image(s) from AL1 to AL2, then we expect to make it easier to install additional packages in the future. 
If we can make it easier to install new packages, then we can maintain the platform's stability and security posture more effectively. 

## Background 

- A previous decision ([ADR 003 in devops repo](https://github.com/department-of-veterans-affairs/devops/blob/187cbfe344eacaee05762279d727a79e8e26dcbc/docs/adr/0003-continue-leveraging-python-2.md)) was made _not_ to upgrade to AL1 last year, though the need has now become more important. 

### What must be true in order for you to consider this epic complete? 
_TBD_ @ph-One

**Comment by jhouse-solvd** [comment]
We may need to re-approach this one. There are challenges with the Ansible playbooks. This may require deeper investigation and planning before we pick this up. 

As we continue to migrate tenants and workloads to EKS, from BRD, this will become an easier challenge to tackle due to reduced complexity (e.g. fewer things to build and deploy).

**Comment by jhouse-solvd** [comment]
We will, however, upgrade AMIs to a version of Amazon Linux 1 that will be supported until mid-2024. This addresses the immediate concerns around the deprecation of the image that we are currently using. 

Please see #41289 for details.

**Comment by jhouse-solvd** [comment]
@ph-One -Can you check to see if this is still relevant given some recent updates to AMIs?

**Comment by ph-One** [comment]
We have new base AMIs built, but they are not rolled out to anything other than self-hosted GitHub Runners

**Comment by jhouse-solvd** [comment]
This is a stale issue that can be closed in favor of the following issues: 

- [SCCD] Ensure compliance is above 90% for machines using Amazon Linux 2 (AL2 AMI) [#492](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/492)
- [SCCD] Review and update Amazon Linux 2 AMI [#64326](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64326)
  - [AL2 AMI] Image Hardening [#65935](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65935)
  - [RevProxy] Discovery around moving revproxy to AL2 [#65525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65525)
