### ISSUE TITLE
Clear Patient Messages on Patient Change Tools Tab

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#41241]

**Comment by chancetheoriginal** [comment]
When viewing message history for Patient A, then swapping to Patient B without a message history, VEText would continue to render Patient A's history in the message list. The db table reload/clear function was not firing if there was no data to load.

**Comment by lindsay-insco** [comment]
@chancetheoriginal - Is this still an issue?

**Comment by chancetheoriginal** [comment]
> @chancetheoriginal - Is this still an issue?

Unsure, have not had any additional reports.
