### ISSUE TITLE
Design Method for KPI Reporting

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4124]
## User Story or Problem Statement
How might we design a way for VFS teams to consistently report KPIs so that data-informed conversations around product success become more of a norm?

## Goal
Design how VFS teams can report KPIs based on basic method determined in https://github.com/department-of-veterans-affairs/va.gov-team/issues/3774.

## Objectives or Key Results this is meant to further
- O2: Customers use qualitative and quantitative user data to build and iterate on VFS.

## Acceptance Criteria
- [x] User Journey Map 
- [x] Draft artifacts outlined in User Journey Map (ex: Forms, how the Slackbot will work)
- [x] Share results with team

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amycesal** [comment]
Miro Board: https://miro.com/app/board/o9J_kv6xbCc=/
![Screen Shot 2020-01-15 at 1.37.44 PM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/ee6f8d64-b438-4dd4-9ff6-96a3b4bd34f7)

**Comment by amycesal** [comment]
### Form template for KPIs. 
It will need to be customized for each team, but this is the basic structure. 
https://forms.gle/S2H1URirs3zviXRt9

![Screen Shot 2020-01-21 at 8.54.08 AM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/fa51a4ac-7084-4ed6-a3d8-553d52b601b3)

**Comment by joanneesteban** [comment]
Thanks, @amycesal! 

FYI @jchasia-adhoc this is the issue for the KPI reporting method.

**Comment by amycesal** [comment]
Adjusted the journeymap of how KPI's get reported: 

Miro Board: https://miro.com/app/board/o9J_kv6xbCc=/

![Screen Shot 2020-01-21 at 5.03.39 PM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/9c1ab25e-09f1-4a0b-8e80-8613933aa444)

**Comment by amycesal** [comment]
### Example SlackBot message in each team's channel:

![Screen Shot 2020-01-21 at 5.14.26 PM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/f7d1dfbc-d88d-41a6-94d9-40bada54399e)
