### ISSUE TITLE
Vaccine Workflow Content Review from VAOS (VA Online Scheduling) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#41256]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?

We anticipate to launch the update in February 2023.  

## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Feature Brief]()
- Link to or attach user flows: 
**Copy docs**
  - [COVID-19 vaccine appointment (Plan Ahead page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-plan-ahead.md)
  - [Have you received a COVID-19 vaccine? (Screener page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-received-dose-screener.md)
  - [We can't schedule your second dose online (Contact Facility page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-contact-facility.md)
  - [Choose a location (Facility Selection page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-choose-facility.md)
  - [Choose a clinic (Clinic Selection page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-choose-clinic.md)
  - [Choose a date (Calendar page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-calendar.md)
  - [When to expect a second dose (Second Dose Info page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/vaccine-second-dose-info.md)

- Link to prototype or mockups:
**Full VAOS screen flow** - To be added

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: February 2023
- Estimated staging review date: January 2023
- Content and IA work needed by: December 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VAOS (VA Online Scheduling) 
-	OCTO-DE product owner: Lauren Alexanderson, Katherine Lawyer, Patrick Bateman, Stephen Barrs, Mark Dewey
-	Product manager: Leah De La Costa and Jeff Roof 
-	Designer: Peter Russo and Ciera Maddox
-	FE engineer: Simi Adebowale 
-	Product/team Slack channel: #vaos-team 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by outerpress** [comment]
@ldelacosta I added a link to the user flow, lmk if you need anything else

**Comment by ldelacosta** [comment]
Will close out the ticket since this initiative is on hold. Will create a new ticket when we plan to resume the work.
