### ISSUE TITLE
[Application Hosting and Deployment] Developer forms {checklist, onboarding, promotion}

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#41250]
## Product Outline
[Application Hosting and Deployment using Container Orchestration (EKS)](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

## High-Level User Story/ies
As a developer using the VA.Gov Platform's application hosting and deployment system, I need forms that enable me to deploy an application. 

## Hypothesis or Bet
Forms will provide developers with an easy-to-use process that enables them to deploy an application. 
Automated processes will remove manual steps for developers. 

### What must be true in order for you to consider this epic complete? 
There are user-facing forms that allow developers to do the following: 
- onboard an application 
- promote an application from dev to a higher environment

**Comment by rmtolmach** [comment]
[Application Onboarding Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=devops%2C+eks%2C+infrastructure%2C+infrastructure-request%2C+operations&template=kubernetes-onboarding-template.md&title=%5BInsert+app+name+here%5D+-+Application+onboarding+infrastructure+request) will need to be updated to reflect the automation happening when the [Application Onboarding Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=va-vsp-bot&labels=application-onboarding%2Coperations&template=application-onboarding.yml&title=Application+to+Onboard%3A+%5Bapplication-name%5D) is submitted. A default helm chart is created that our users will need to go in and modify to fit their needs. 

"kubernetes detect and update application" can probably be removed from the checklist in the template.

**Comment by jhouse-solvd** [comment]
**need sub-issues for**
- updates to onboarding checklist
- updates to onboarding form
- promotion form

**need to clarify naming conventions and difference** between 
- application onboarding [form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=va-vsp-bot&labels=application-onboarding%2Coperations&template=application-onboarding.yml&title=Application+to+Onboard%3A+%5Bapplication-name%5D) 
- application onboarding [checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=devops%2C+eks%2C+infrastructure%2C+infrastructure-request%2C+operations&template=kubernetes-onboarding-template.md&title=%5BInsert+app+name+here%5D+-+Application+onboarding+infrastructure+request)

**Comment by jhouse-solvd** [comment]
This is the golden path for new developers: 

- Fill out an "Application Onboarding Requirements Checklist" 
  - Set up the app repo and container 
  - Set up app delivery pipeline 
  - Set up app secrets and parameters 
- Fill out an "Application Onboarding Form" 
- Build Helm chart 
- Automation to update the Kubernetes manifest
- Fill out an "Application Promotion Form"

---
The step to add "Automation to update the Kubernetes manifest" is being pulled out of the checklist. A new document will be created that instructs developers to set up this automation _after_ they've filled out the "Application Onboarding Form"

**Comment by jhouse-solvd** [comment]
This can be closed.
