### ISSUE TITLE
[Story] Run GIDS publishing process in coordination with EDU

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#41276]
## Issue Description
Brian Grubb requested support to run the GIDS publishing process on 5/12/2022.

---
## Tasks
Dev will execute the publishing process in GIDS in coordination with EDU.

**Comment by MitchLivingstone** [comment]
Waiting for feedback from Brian.

**Comment by PJart** [comment]
Brian published to production, geocoding script was run, did some validation and didn't see anything that stuck out https://www.va.gov/education/gi-bill-comparison-tool/?search=location&location=Webster%20Groves%2C%20Missouri%2C%20United%20States

**Comment by PJart** [comment]
Step 1: sudo su - -c 'docker exec -it gi-bill-data-service bash'
Step 2:  source config/.env.sh
Step 3: nohup rake fix_coord_mismatch & exit
Step 4: sudo su - -c 'docker exec -it gi-bill-data-service tail -f nohup.out'

**Comment by MitchLivingstone** [comment]
Waiting for OCTO production access. Access projected for 05/26/2022
