### ISSUE TITLE
[Story] Rating System: Implement development changes to the existing Rating System 

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#41273]
## Issue Description
Based on requirements provided by EDU (attached pdf), apply changes to the existing rating system. 

---
## Tasks
Apply changes to the existing CT Rating System based on the attached pdf
Apply changes to GIDS according to existing fields vs. what the new file will look like
QA Testing

## Acceptance Criteria
Apply changes to the existing CT Rating System based on the attached pdf
Apply changes to GIDS according to existing fields vs. what the new file will look like
QA Testing
---
[https://app.zenhub.com/files/133843125/4b8b4d11-da07-49da-8b01-1686d6ab1973/download](https://app.zenhub.com/files/133843125/4b8b4d11-da07-49da-8b01-1686d6ab1973/download)

**Comment by abuchanan83** [comment]
I am currently holding on the subtext for the different items being rated.

**Comment by abuchanan83** [comment]
This item has been implemented with mock data. We are missing the payload data fields and the subtext for the different items being rated. Once both items are received, I can complete the implementation.

**Comment by MitchLivingstone** [comment]
All development has been completed 06/02/2022. Closing this story, the remaining work the EDU has requested will be included into new stories.
