### ISSUE TITLE
Update high-fidelity mockup

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#41280]
## Issue Description
This ticket tracks the body of work of updating the high-fidelity mockup after Collab Cycle.  The following features will be reimplemented
- Dropdown accordion for questions about creating an account through the MHV Inherited Proofing process
- Re-add the table for quick information lookup when a user doesn't have preferred credentials
- Add time constraints (time burden) of Inherited Proofing task (ie how long it will take)
- Add video resources on what Identity Proofing is (* this might need to come later)

---
## Tasks
- [x] Update the high-fidelity mockup for Collab Cycle approval

## Acceptance Criteria
- [x] The high-fidelity mockup of the MHV Inherited Proofing page is complete

**Comment by nsoutouras** [comment]
5/18/22: Moving to blocked waiting on mind mapping
