### ISSUE TITLE
Facility Locator Urgent Care Service Type Splits (Data)

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#4129]
## User Story or Problem Statement
As a veteran I want to be able to find a Community Care Walk in Facility near me so that I can receive care.

Problem description. How can we delineate the urgent care subtypes in PPMS data via the existing API for:

> Specialty Code 3336C0003X (Pharmacy) 
> Place of Service Code (PoS) 17 (Walk-In Care)
> Place of Service Code (PoS) 20 (Urgent Care)

**Note: This is critical for the Optum inclusion and deprecation of TriWest link**

## Goal
Provide a way for the Facility locator to query PPMS for these PoS and Specialty codes based on a users' location with a quick (< 4 second _note: not required for MVP, but can iterate to achieve_) search return.

## Objectives or Key Results this is meant to further
- Mission Act/Urgent Care Facility Surfacing
- Facilitate removal of the Tri-West Locator Link

## Acceptance Criteria
- [ ] Within a given area, data within PPMS matches the facilities returned by the Facility Locator when a Veteran searches for urgent care in that area based on sub-type: 

> Specialty Code 3336C0003X (Pharmacy)
> Place of Service Code (PoS) 17 (Walk-In Care)
> Place of Service Code (PoS) 20 (Urgent Care)

- [ ] PPMS data returned via query can be differentiated by sub-type.  
> Specialty Code 3336C0003X (Pharmacy)
> Place of Service Code (PoS) 17 (Walk-In Care)
> Place of Service Code (PoS) 20 (Urgent Care)

**Comment by mmiddaugh** [comment]
Cannot estimate until data is accessed
