### ISSUE TITLE
Broken images on "Build and deploy process flows" page

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#41292]
## Description
**The questions below help our team to determine the project scope for incoming documentation support requests.**

**1. What do you need help with? Check one:**
- [ ] Creating new documentation
- [x] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

**2. Who are the primary users of your documentation? Check all that apply:**
- [x] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other: ____________________

**3. Estimate the number of pages to be created, updated, or reviewed? 2**

**4. Do the documents contain graphics such as screenshots, code snippets, diagrams, or videos?**
- [x] Yes, and describe: expecting a Lucid flow diagram  
- [ ] No

<img width="751" alt="Screen Shot 2022-05-12 at 1 13 54 PM" src="https://user-images.githubusercontent.com/8542413/168131477-15cc6bc2-c33e-476c-bf58-19bdcf7bfeac.png">

**5. Who is the point of contact for this documentation?** Not sure, possibly @gmaciolek ?

**6. Are there other documents, tickets, or artifacts that will be impacted by this update?**
- [x] Yes, and describe: another [Build and deploy process page](https://depo-platform-documentation.scrollhelp.site/developer-docs/Build-and-deploy-process-flow.2165669889.html) 
- [ ] No

**7. Are there plans to update other documents/pages that have similar content?**
- [ ] Yes
- [ ] No

### Relevant URLs:

https://depo-platform-documentation.scrollhelp.site/developer-docs/Build-and-deploy-process-flows.1844346924.html

https://depo-platform-documentation.scrollhelp.site/developer-docs/Build-and-deploy-process-flow.2165669889.html

**Comment by lianilychee** [comment]
Thanks @allisonlu !

@laineymajor @rmessina1010 since your team owns these docs, tagging you both so you can refine in your backlog as fit.

**Comment by vbellissimo** [comment]
Followed up with Lainey Trahan and Ray Messina via Slack on 6/30/22.

**Comment by rmessina1010** [comment]
The images were not showing up due to them being inclusions of a LucidChart graph. Images on both relevant links have been  replaced with screen shot pngs, given  proper captions and alttexts and confirmed to be working on Platform Docs. 
Issue closed.

**Comment by vbellissimo** [comment]
@allisonlu This content update has been resolved and we are closing this ticket. If you have any other questions regarding this content, feel free to contact the Platform Content team at #platform-confluence. Thank you.
