### ISSUE TITLE
[Issue] Issue with Chapter 35 (DEA) Philippines Housing Rate

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#41303]
## Issue Description
It was reported by EDU that all Philipines institutions (code 62) are presenting the wrong Housing Allowance. The currentl allowance presented in CT is $1298.00 when it is supposed to be $649 (50% of what is currently showing).

---
## Tasks
Make sure all institutions from Philipines (code 62) display the correct Housing allowance of $649

## Acceptance Criteria
Housing allowance for all institutions in the Philipines muswt be $649

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/e4163068-fceb-470d-8ebc-9a4ea9205574)

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3248&group_by=cases:section_id&group_order=asc
Test case: [(Issue) Issue with Chapter 35 (DEA) Philippines Housing Rate.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8733745/Issue.Issue.with.Chapter.35.DEA.Philippines.Housing.Rate.xlsx)

**Comment by MitchLivingstone** [comment]
UAT and QA passed on 05/25/2022
