### ISSUE TITLE
FE | Profile | Eliminate Error Messaging for Fields Left in "Blank" State

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41319]
# Background

While working on #41001, (Personal Information revision) we noticed that if a user hits the "edit" button for either Preferred name or Gender identity in it's "blank" state we show an in-line error message vs reverting back to blank slate.

Per Adam, this seems to be an issue with the  the validation library in general since other areas of the profile do the same thing. For instance if you go to the Contact Information and do the same process with a phone number the same thing will happen.

**Scenario 1:  Preferred Name/Update**
As a user viewing the Personal Information page prior to adding my preferred name
IF
I click the "edit" button underneath the "Preferred name" field
AND
do not enter any information
THEN
click "cancel", I should see my screen revert back to original "blank" state

**Scenario 2: Gender/Update**
As a user viewing the Personal Information page
IF
I click the "edit" button underneath the "Gender identity" field
AND
do not make a selection
THEN
Click "Update", I should see an in-line error message prompting me to enter my info
and upon clicking "cancel", the screen should revert back to the original "blank" state 
OR
display the previous response

**Comment by SKasimow** [comment]
Including slack thread with more insight on solution approach: [here](https://dsva.slack.com/archives/CBU0KDSB1/p1652805365896249)

**Comment by adamwhitlock1** [comment]
Going to work on doing validation only on 'submit' and therefore eliminating the need for the 'required' schema situation.

- Create custom field component
- Validate field on submit
- Show error messaging if update is attempted with empty field value
- Allow cancelling the edit state without any error messaging tripping up the cancel process

**Comment by adamwhitlock1** [comment]
@SKasimow I implemented a fix for this that checks for the field not having a value when submitted and only shows the validation error for it being required in that instance. Clicking edit and then immediately cancelling should now work as expected with no errors being presented.

**Comment by adamwhitlock1** [comment]
let me find some test users without a preferred name set and ill update this comment so you can validate the behavior

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - just tested and looks great! Much better user experience - thank you! Should we close this ticket now or wait until live in prod?
