### ISSUE TITLE
Business intake form for CARMA

### ISSUE THREAD

**Issue by starofaragon2010** [department-of-veterans-affairs/va.gov-team#41312]
## Your Details
1.  Caitlin Reyna, Marla Clayton, David Wald, Nitish Barman, Terry Taylor
​
2.  OIT 
​
## Notification Details
1.  **Notification type**
    MVP will be email.
​
2.  **Please describe your use case.**
    If a Veteran or Caregiver are interested in applying to the PCAFC program, they may go to VA.gov and complete the online form (1010CG). If the CARMA system is unavailable or taking a while to create a case, an message will display to the user that they do not need to wait and can check their email. Once the case is successfully made in CARMA, then an email will be sent to user that it was successfully made
​
3.  **What actions can the user take based on the notification they receive?**
    No longer need to submit an application
​
4.  **What is the desired business outcome?**
    Less call center volumne
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
   CARMA/Mulesoft
​
6.  **What will trigger the notification?**
    Submitting a 1010CG which will go into a queue
​
7.  **Provide sample content per notification type, if you have it.**
    “Your application has been successfully submitted to your designated VA Medical Center. Caregiver Support Program staff will contact you to discuss the application process.”
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    Yes, we know who the PO is (Rita G
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
   We will provide
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
 No - not existing functionality
​
11.  **What is the anticipated volume of notifications per day, week, month?**
      32/day
​
13.  **When does this notification need to be in production?**

**Comment by bevnobev** [comment]
Hi @starofaragon2010.  Thanks for reaching out.  Did you or your team get a chance to look at the playbook from the brown bag today?  If not, we can send it separately.  Please drop some dates/times you and your team are free next week for a chat

**Comment by starofaragon2010** [comment]
Hi Beverly,

Yes - we did attend your awesome presentation today. Marla downloaded the information and distributed it.

We would look at implementing this in Aug-Oct on our end (TBD until after our PI Planning session the last week of June).

As such, we would like to discuss this asap to be sure of its feasibility and application in our particular use case.


  *   10:00-11:30 pm ET Wednesday
  *   12:30-1:30 pm ET Friday

Thank you!


Caitlin Reyna (Contractor) SP, SSM, CAPMS, PMP
CORP TMSS Portfolio Program Manager
Office of Information & Technology, Development, Security, and Operations (OI&T DSO)
Software Product Management (SPM)
Phone: (240) 713-9833
***@***.******@***.***>
***@***.***

From: Beverly Nelson ***@***.***>
Sent: Thursday, May 12, 2022 4:32 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reyna, Caitlin M. (TISTA Science and Technology Corporation) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for CARMA (Issue #41312)


Hi @starofaragon2010<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstarofaragon2010&data=05%7C01%7C%7C785a613d0e3145e5f3d608da3456796b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637879843249110636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xdzpTczZvNRZgFWmtqNtC4KERlWsUFk1zt71rYEPTzc%3D&reserved=0>. Thanks for reaching out. Did you or your team get a chance to look at the playbook from the brown bag today? If not, we can send it separately. Please drop some dates/times you and your team are free next week for a chat

-
