### ISSUE TITLE
Switch Repo to Main

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41324]
# Description
The [product-directory repo](https://github.com/department-of-veterans-affairs/product-directory) is currently setup with both `master` and `main`. Let's switch the default to `main` and remove `master`.

# Tasks
- [x] Switch repo default to `main`
- [x] Remove `master`

# Acceptance Criteria
- [x] The default for `product-directory` is `main`

**Comment by rbeckwith-oddball** [comment]
I do not appear to have the necessary permissions to do this.![github_product_directory.png](https://images.zenhubusercontent.com/61265d854c842ee6052dd62e/256c5060-0028-4f00-afab-d50897987a24)

**Comment by rbeckwith-oddball** [comment]
Peter has corrected the issue.

**IMPORTANT**
Anyone with a local version of `product-directory` on their machine will need to perform the following to update their configurations accordingly:

```

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

```

**Comment by pjhill** [comment]
Nice, thanks for knocking this out quickly.
