### ISSUE TITLE
[FE] 10-10EZ Review page- American Indian title (before question is on in prod)

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#41337]
The content team requested that we update "Tribal affiliation" to: **Recognition as an American Indian or Alaska Native**

- Please post screenshot here
- Please let me know if this is too long (and what the character count max is)
![Review page.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d2985906-f5da-4d1a-878a-e1daeef18144)

**Comment by longmd** [comment]
Here is a screenshot of the title update:

![Screen Shot 2022-06-16 at 3 54 35 PM](https://user-images.githubusercontent.com/6738544/174153483-e773b609-12f1-451b-bffd-af4e884c1448.png)

**Comment by longmd** [comment]
And wrapped on mobile:

![Screen Shot 2022-06-16 at 3 56 32 PM](https://user-images.githubusercontent.com/6738544/174153740-e078d91e-e50b-497a-9a7a-649c8a9f241e.png)

I don't see any issue with the length of the text there.

**Comment by Dene-human** [comment]
Looks good to me. Thanks!
