### ISSUE TITLE
[BE] MyHealth - Retire v0 health API endpoints in vets-api

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41330]
## Issue Description
The old health API endpoints in vets-api need to be retired so they will no longer be used.

## Tasks
- [ ] Retire v0 health API endpoints in vets-api

## Acceptance Criteria
- [ ] Retire v0 health API endpoints in vets-api

**Comment by A6-toma** [comment]
Closing per Slack conversation with @MarciMcGuire and @ajakabcin.
