### ISSUE TITLE
Content and IA feedback for My Education Benefits Fry/DEA app

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#41338]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
[Fry/DEA wireframes](https://accenturefederal.invisionapp.com/freehand/FRYDEA-Target-Designs-WE63OVY4)

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ x] No

**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  TBD 2022-2023
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Form%2022-5490%20Updates/Product%20Outline.md 
- Link to or attach user flows:
- Link to prototype or mockups: https://accenturefederal.invisionapp.com/freehand/FRYDEA-Target-Designs-WE63OVY4?zoomToItems=Y2wycnBhc2o4MDBpczN4NnFndXc5YmsyYg%3D%3D
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done? 
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: Ongoing feedback with this team, would like more recommendations before Wednesday, May 18th 

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola Here's my feedback on the 3 screens about divorce/annulment (after some consideration, I think it does make sense to use the existing form label--and carry it through all 3 screens). Will it work to have 3 radio buttons as I have here rather than a simple yes/no?:

**Marriage information**

What’s your current marriage status with the service member?
[ ] Married
[ ] Divorced (or a divorce is in progress)
[ ] Marriage was annulled (or annulment is in progress)

If the user chooses the second or third option, then:

**Marriage information**

Have you gotten remarried since your divorce or annulment?

If yes:

**Marriage information**

What date did you get remarried?

**Comment by alexander-ferzola** [comment]
Happy Monday @bethpottsVADEPO , thank you for this feedback! The designers found your recommendations very helpful and we’ll be bringing your approach (slightly modified) to our next review.

**Marriage information**

_What’s your current marriage status with the Veteran or service member?_
[ ] Married
[ ] Widowed
[ ] Divorced (or a divorce is in progress)
[ ] Marriage was annulled (or annulment is in progress)

If the user chooses the second, third, or fourth option, then display corresponding questions under the header

**Remarriage**

If they choose Marriage was annulled:

_Have you gotten remarried since your annulment?_


If they choose Divorced:

_Have you gotten remarried since your divorce?_



If they choose Widowed:

_Have you gotten remarried since being widowed?_


If yes:

**Remarriage date**

_When did you get remarried?_

We understand the relation between all these questions and the want to put them under a single "Marriage information" label. However, from a design perspective, there is a need for more visual distinction between each question past the question itself, especially since they are all a part of the same step already (Additional considerations).

Thank you for all of your input thus far! We'll be submitting a midpoint review this week and will tag you in it for your awareness. We appreciate the thought you put into your feedback; we'll certainly reach out with any other copy-pitfalls we may come across!!

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola OK, and I have one tweak to give you on the above and then updates throughout the screens. Please make these updates before the midpoint review and next stakeholder review.

Would you please rephrase the above because "marriage" shouldn't be used as an adjective (my fault the first time around!) and "marital" isn't as good a choice for plain language reasons: 
**What’s the status of your marriage with the Veteran or service member?**

---------------------

### Application instructions, unauth

I would recommend not using 2 info alerts on this page. They both loose effectiveness. Keep for the sign-in alert only. Right under "Equal to VA Form 22-5490" here's what you can do instead (and I removed "Chapter 33" and "Chapter 35" because you don't need that info in 2 places on this page--it's also cluttered to have both "DEA" and the chapter info together in the parentheses):

**Note:** This application is only for these 2 education benefits:

- **The Fry Scholarship**
- **Survivors' and Dependents' Educational Assistance (DEA)**

[Check your eligibility for other education benefits]

I'd recommend shortening the labels for the additional info components like this (DEA is sufficient here because you've already spelled it out above and introduced the initialism / there's no need for these to be in the form of questions, which makes the labels longer):

Fry Scholarship (Chapter 33) eligibility requirements
DEA (Chapter 35) eligibility requirements

No. 2 in the subway map (and anywhere else throughout the flow where you currently have "sponsor"):
Change "your sponsor's" to "the Veteran's or service member's"

---------------------------

### Benefit selection

First screen:
- Change "your chosen service member" to "the Veteran's or service member's" (to match the rest of the language in this flow)
- Change "This is not" to "This isn't" (plain language standard)
- Change "will not be made" to "won't be made" (plain language standard)
- Change "If you are potentially eligible" to "If you're eligible" (plain language standard)
- Change "you'll need to give one up" to "you'll need to choose which one to use" (this is less negative language)
- Don't spell out DEA, just use the initialism DEA

Second screen:
Please follow our VA.gov style guide and don't bold "not" (in addition, you should use a contraction here): You're not eligible for this benefit

### Felony

Please change "and/or" to "or" (per VA.gov style guide)

### Notification preferences

In the info alert:
- Change "Two messages per month" to "You'll get 2 messages every month."
- Change text links to this (to avoid "view" which is sighted language and to place each link on its own line, which is our in-house style):
[Review our Terms and Conditions]
[Review our Privacy Policy]
- Change the preposition in the last question on the screen:
Would you like to receive text message notifications about your education benefits?

### Enter banking information

Change "VA makes payments only through direct deposit..." to "We make payments only through direct deposit"

### User is approved!

- We don't use exclamation points, so please just use a period after "Congratulations."
- Make the second sentence in the header active voice: "We've approved your application for DEA." 
- Don't spell out DEA in the first sentence, and delete "Chapter 35"--we don't need to keep saying this
- Under "What happens next?": To avoid "and/or" change the sentence in the fourth bullet to, "Review your direct deposit information in your VA.gov profile and make any needed updates."
- Change the additional info component label to: "What's a decision letter?"
- Change the first sentence within that component to: "A decision letter is an official VA document that shows your GI Bill benefit status."
- For the second sentence, the only change needed is to form a contraction: "If you're approved"

### User is denied

- First sentence in info alert: Remove "Unfortunately" (this isn't our voice) / change "we have determined you are not eligible" to "we've determined you're not eligible" / shorten to "eligible for DEA benefits at this time"
- Second paragraph in info alert: "Your decision letter, which explains why you're not eligible, is now available for you to download. We'll also mail you a copy of this letter."
- I'd recommend removing this whole section: "What happens next?" since Tammy has asked for the one bullet and the link to be removed, and the download link is already above, there's not much left except another option for how to get your decision letter, which might be confusing. I don't think we should provide 2 ways to get that. It's extra work for the Veteran to decide which of these routes to take. 

### User application is under review

- First box: Delete that first sentence. It's too vague and might prompt the user to think something's wrong. Instead let's say this: "After we've reviewed your application, we'll contact you about what happens next."
- Text under "What happens next?"
First bullet: Change "We will" to "We'll"
Third bullet: Change text to: "We'll notify you if you're eligible for VA education benefits."
I don't think the fourth bullet is very helpful, but if we must retain it, we have to make it active voice: You don't need to do anything else at this time.
- First bullet of "What can I do while I wait?": "Review your direct deposit information in your VA.gov profile and make any needed updates."

**Comment by bethpottsVADEPO** [comment]
@CherylEvans for awareness!

**Comment by CherylEvans** [comment]
Would it be possible to attach your FB to the core GH ticket?
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41090
<https://www.google.com/url?q=https://github.com/department-of-veterans-affairs/va.gov-team/issues/41090&sa=D&source=calendar&ust=1653322208663666&usg=AOvVaw3ZiBpXnwDRa1CVMhv74D3W>
Thanks again for the situational awareness!
Cheryl

Cheryl Evans | Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

203-580-3529 | ***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by mnorthuis** [comment]
Hi @alexander-ferzola, one thing that needs to be updated while you are working on this form, is correcting the current breadcrumb segment and the title tag to appropriately match the H1.  This is a design system standard.   Please note that the title tag is initial cased, while the breadcrumb is the same casing as the H1.

I believe I have mentioned this before, but across all the education forms the breadcrumb hierarchy and URLs are inaccurate and not modernized.  At some point, that will need to be corrected across the board.  Fixing the current page segment will at least get us partially inline with those standards.

**Comment by CherylEvans** [comment]
> @CherylEvans for awareness!

@bethpottsVADEPO Good morning Beth.  Thanks again for providing your FB for my SA.  :-) I'm looking over the provided artifact [wireframes](https://accenturefederal.invisionapp.com/freehand/FRYDEA-Visual-Designs-WE63OVY4) and am realizing that a lot of SWC's FB was not implemented.  I understand there are time constraints, so that is fine, but is it your understanding that these recommendations/edits will be implemented prior to Staging Review?  That is what I am interpreting from the comments in the ticket.  I just wanted to be on the same page with regard to expectations.
Thank you!!

**Comment by bethpottsVADEPO** [comment]
@CherylEvans I believe Alex is saying that they will address my feedback that applies to all the education forms in a future ticket and cc review, not as a part of the work on these new DEA/Fry screens. So, in your content QA step, you'd focus only on the new screens that have to do with marriage/remarriage.

@alexander-ferzola did I get that right?

**Comment by alexander-ferzola** [comment]
> 

This is what we had in mind! We've documented all of your feedback that applies universally across all the education application forms and will look to address those issues in a separate update. We'll respond and close this ticket at that point, as well.

**Comment by bethpottsVADEPO** [comment]
Sounds good, @alexander-ferzola -- so there's no ticket yet for that future work?

**Comment by CherylEvans** [comment]
@bethpottsVADEPO @alexander-ferzola Thank you for clarifying.  I definitely appreciate it!  :-)

**Comment by mnorthuis** [comment]
@bethpottsVADEPO is this work complete?

**Comment by bethpottsVADEPO** [comment]
Closing. This work is complete.
