### ISSUE TITLE
[05/18/22] Create Duplicate Site Removal Quick Guide

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#41347]
## Description
Before the implementation of a feature to remove the possibility for healthcare facilities to duplicate sites, there has been an uptick in mass duplication within VEText. In order to remove these duplicate sites and erase errors caused by them, a removal guide for sites to follow will be created.
---

## Acceptance Criteria

- [x] Create step-by-step guide to remove duplicate sites (draft)
- [x] Review with Ari
- [x] Post to group Slack channel for review
- [x] Approved by Justin/Allison/Lindsay
---

**Comment by chancetheoriginal** [comment]
Writeup made and passed to Justin for approval.
