### ISSUE TITLE
Documentation: Add engineering docs for keyboard-only testing

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41348]
## Description

As we add more Cypress keyboard-only e2e tests for app, it would help engineers to have detailed documentation. There is a page for [keyboard testing helper functions](https://depo-platform-documentation.scrollhelp.site/developer-docs/Keyboard-testing-helper-functions.1933607071.html). This ticket is for adding documentation with more examples.

## Tasks

- [ ] Add documentation with keyboard-only test examples

## Definition of done

- [ ] All tasks complete

**Comment by saderagsdale** [comment]
- Rocio to shadow.

**Comment by Mottie** [comment]
Completed, pending platform review - https://docs.google.com/document/d/11RYZOM-P8l7nO3PmAr0PDv87c0v1NYGnmnYgSCV848Q

**Comment by saderagsdale** [comment]
@Mottie what's the latest on this? Let me know if the platform review is in progress.

**Comment by Mottie** [comment]
I haven't followed up with that team since our Slack conversation 5 days ago. It looks like the 2 people I discussed this with are OOO today. So I left a message in that thread.

**Comment by saderagsdale** [comment]
@Mottie gonna unassign and deprioritize this. Let me know if you feel strongly about pursuing this.

**Comment by Mottie** [comment]
Done - https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-keyboard-only-end-to-end-tests
