### ISSUE TITLE
Research and implement solution to automate tracking and updating the last_updated in Product Directory

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#41361]
A process has been set up to automatically detect dependencies and cross-product imports and opening up pull requests for changes. We would additionally like to add automated scanning for the last_updated field.

"last_updated" - When was the last time the code for this product was updated in GitHub? This should run once weekly.

---
## Tasks
- [x] Set up a workflow to scan for changes to `last_updated` once a week, opens a PR with changes, and notifies slack of the open PR.

## Acceptance Criteria
- [x] Our product list has automated scanning for `last_updated` once a week with PR and slack notification features.

**Comment by holdenhinkle** [comment]
The code for this is done.

PR - https://github.com/department-of-veterans-affairs/vets-website/pull/21249

Here's the updated json file - https://github.com/department-of-veterans-affairs/product-directory/pull/244/files

It's not very useful because lots of the `last_updated` dates were when the `manifest.json` file was updated.

Perhaps I should look into filtering that commit out?

**Comment by holdenhinkle** [comment]
I'm filtering out that commit to update the `manifest.json` file on 5/12/2022 by Ryan Johnson.

**Comment by holdenhinkle** [comment]
PR submitted for review.

**Comment by holdenhinkle** [comment]
This has been merged.

**Comment by pjhill** [comment]
Heck yes, where's the accommodation to ignore the commit that affected a wide number of product manifests? I perused the PR, but I missed it.
