### ISSUE TITLE
SOCKS access for Claudio Nunez Jr

### ISSUE THREAD

**Issue by kind-claudio** [department-of-veterans-affairs/va.gov-team#41377]
### Your Name

Claudio Nunez Jr

### Your Email

cnunez@kindsys.us

### Your Role and Team

Senior Front End Engineer on Sitewide Public Websites

### Product Manager (PM) name and email

Wes Rowe wesley.rowe@agile6.com

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkozKX17+IDf1q/XLJNPzc9XfWXUuMfEGM/jy8vnMiqL4PYrHxowpOdME0PPpa+e6yKt9p3ZrF5D0U/LGrUi/58NMmrhuxxd4A2xwKuKeGhpCW8TyUUuXTOgLlXsP+1c6wytVqO0t+kIzSg+EApa+Mq/CZMUYL4Ge7zdz+DzIIPfaw+ypl9qMWJPCm/Qria5RI1Mp4ufgNsv3RdmvAyJkZqdilNxmaTA01rXIu/KC1L/Ii2/rkloK3YpB5zzf0AZj6jd7aENU277D8Q2x086uAq9uQ8ltR04rA91ciFMFjMhLnQFx6oW1iheDMxzJRgJtAWGGGmR7L5I+4UasuCWu8oZtVmCsh3OiF33FEy7oLMHxYQ9g+a2bwHrsLA9O3aas6F2sQIXwAThr5Yn6eZnYeY8vp7LETw+BbMM73RHhsChpoz7pCblCU7gygLd0nPIc55UjLlHwvcmX0+5PbcYlXpG/4sgS5TQIyADGtcvcM7Pa+SdLf9/eniIawco6cOp8= claudionunezjr@Claudios-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
Hi @kind-claudio! 
We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with [this platform orientation guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). If you're not newly joining the team, please reach out to your PM or PO for help.
Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by kind-claudio** [comment]
Hi Carl,

I've scheduled the Platform Orientation - the next one is on the 24th. Does
this mean I won't be able to get SOCKS access until then?

Very Respectfully,

*Claudio Nuñez Jr.*
Senior Front End Engineer
480-580-4212

**Comment by calquisola** [comment]
Hi Claudio,

We can't add you until we see in your name in the roster. 
Please reach out to your PM or PO so they can expedite this process. 

Best,
Carl

**Comment by jilladams** [comment]
Claudio has been added to the roster.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
