### ISSUE TITLE
[FE] MyVA: Update from AlertBox to Va-Alerts

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#41375]
## Background
AlertBox has been deprecated so we need to remove it from our code and replace it with va-alerts.

## Tasks
- [x] Research all places in the code that need to be updated
- [x] Update code
- [x] Test

## Acceptance Criteria
- [x] MyVA code is completely migrated from AlertBox to va-alerts

**Comment by tmitchellgcio** [comment]
Closing this. we discussed it with Angela and she looked at it already and said it had some minor formatting which she didn't see as a big deal and she would update the spec.
