### ISSUE TITLE
Slackbot Support Monitoring with Datadog

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41382]
# Description

The support bot needs a monitor setup to detect issues.

# Acceptance Criteria
 
- [ ] Add a status api feature that returns the status of the bot by checking Slack API connectivity and returning a status code.
- [ ] setup Datadog monitor to call this status feature for the bot.
- [ ] Add notification for SRE team and pagerDuty.

**Comment by alyssagallion** [comment]
Slackbot has been working fine, so no need for updates at the moment on the bug side of things. Closing.
