### ISSUE TITLE
AWS Staging: Type of Care not Displayed on a Booked CC Appointment Detail Page 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#41390]
## What happened?
When an CC appointment is scheduled trough HSRM. Under the Upcoming queue the CC booked/ upcoming appointment is missing the type of care attribute on the Detail page.
## Specs:
- Browser: (Chrome, IE, Edge)
- Test User _ This is happening across all the test users working on VAOS Service 

## Steps to Reproduce
**VAOS:**
- Login as to VAOS as a VAOS service test user (Ex;- patient999@id.me)
- Click on start scheduling 
- Select any CC supported type of care (Ex;- Optometry)
- Select up to 3 date 
- Select Dayton for closest city to you (as HSRM IPE integrates only with Dayton)
- Select a preferred provider from the list 
- Chose a preferred  language
- Enter a reason for the appointment 
- Enter phone number/ email address and best time to call 
- Enter the request and validate the request is displaying under the requested queue in VAOS
**HSRM:**   
- Login in HSRM/ CPRS and CTB and follow the steps to schedule an appointment for the preferred date/Provider

**Expected Results:** When looking at the detail card of a CC booked/upcoming appt the Type of care should be displayed

**Actual Results:** Type of Care is missing from the detail card on a CC upcoming appointment 
![image](https://user-images.githubusercontent.com/69315717/168659512-fc90c137-f5a7-4f04-a35f-001a0365bb76.png)

**Comment by aarathi-poldass** [comment]
@ldelacosta - I don't have permissions to add labels - project and assignees, can you please add them for me. Also, can you please prioritize this ticket. Thank you.

**Comment by ldelacosta** [comment]
@aarathi-poldass - We have reviewed this ticket and will address it in #41390 (V0 does not have type of care available and V2 has it available). I will let you know when the work is done so you can test. Thanks!

**Comment by ldelacosta** [comment]
@aarathi-poldass - This can be tested and let us know if you experience any issues. Thanks.

**Comment by ldelacosta** [comment]
Tried to submit a CC request, getting an error. Per Marcy's comment, This is a known bug. HSRM for some reason is taking + 30 secs to reply and the call is getting timed out. Thomas will be reaching out to HSRM to work on the. VAOSR-3700

**Comment by marcynadeau** [comment]
This is currently blocked by VAOSR-3700. https://issues.mobilehealth.va.gov/browse/VAOSR-3700. STAGING: Encountering 504 error while creating CC request

**Comment by aarathi-poldass** [comment]
Validation Failed - Type of Care is still missing from the detail card on a CC upcoming appointment. Please find attached a screenshot for reference. @ldelacosta

 
![image](https://user-images.githubusercontent.com/69315717/171267076-b1273507-cc06-4c26-964f-a9e761ac8a94.png)

**Comment by ldelacosta** [comment]
Moving this ticket back to Blocked since #40621 ticket is back in development for further review.

**Comment by ldelacosta** [comment]
@aarathi-poldass - This has been addressed. Please proceed with testing. Thanks!

**Comment by marcynadeau** [comment]
@ldelacosta I did a quick smoke test while I was in testing something else and this looks like it is fixed.  Aarathi has more detailed testing to complete the defect but I thought I would let you know in my smoke test this is working.

**Comment by ldelacosta** [comment]
Moving this ticket back to Blocked. Found an issue and team will address it.

**Comment by aarathi-poldass** [comment]
Re-tested the defect and failed validation. When a request is made through VAOS and booked using HSRM the "Type of care" is missing on the Upcoming appointment detail page. This issues was discussed on the BR scrum call and upon analysis the SQA team was suggested to run a Test using VAOS test harness and compare the results/ response. The test were run and in both scenarios the "Type of Care" is not being displayed in VAOS UI. Please find the screenshot below for reference. 

![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/8d6df836-521d-40e3-b1d8-7cceeafc50ee)

Note: The Response data was sent to Leah over slack. @ldelacosta - Can you please assign this ticket back to the developer for further analysis.

**Comment by ldelacosta** [comment]
We added the type of care label for booked CC appointments. 

![Screen Shot 2022-06-27 at 3.02.00 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/41b728f7-fd3b-4498-b04c-e37b6c76e69a)

Per review, the `serviceType` is not available when the `status` is `booked`
In the event that the data is available in the response body, the UI will display the type of care label for the CC appointments. 

We have a ticket #43460 to add a logic if the type of care data is not available, we will suppress the label on the frontend. 

cc: @aarathi-poldass

**Comment by ldelacosta** [comment]
@aarathi-poldass If you're good with this ticket, please close it out. As per my comment, we added the type of care but cannot be validated with data since HSRM is not sending back `serviceType`. In the event it does, FE will display the data and label on the appointment details page. 

cc: @simiadebowale

**Comment by marcynadeau** [comment]
Waiting on linked tickets to be fixed before we can test this one.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/41390

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this was issue given priority to be High

**Comment by ldelacosta** [comment]
@aarathi-poldass - This is ready to be tested since #43460 is completed.

**Comment by aarathi-poldass** [comment]
Re-tested the defect with 2 scenarios. Please find below the detailed discerption:

Scenario 1: When HSRM doesn't return the Type of Care field in the response body for a booked appointment, VAOS is not displaying the type of care on FE.
Response body:
{
"id": "117292",
"type": "appointments",
"attributes": {
"id": "117292",
"identifier": [
{
"system": "http://med.va.gov/fhir/urn/vaos/hsrm/id",
"value": "524621||6||1"
}
],
"kind": "cc",
"status": "booked",
"patientIcn": "1013120830V747912",
"locationId": "984",
"start": "2022-07-23T13:30:00Z",
"created": "2022-07-22T13:40:57Z",
"cancellable": true,
"extension": {
"ccLocation": {
"address": {
"line": [
"10640 MAIN ST ; STE 100"
],
"city": "FAIRFAX",
"state": "VA",
"postalCode": "22030",
"text": "10640 MAIN ST ; STE 100\nFAIRFAX VA 22030"
},
"telecom": []
},
"hsrmTaskId": ""
},
"location": {
"id": "984",
"type": "appointments",
"attributes": {
"id": "984",
"vistaSite": "984",
"vastParent": "984",
"type": "va_health_facility",
"name": "Dayton VA Medical Center",
"classification": "VA Medical Center (VAMC)",
"timezone": {
"timeZoneId": "America/New_York"
},
"lat": 39.74935,
"long": -84.2532,
"website": "https://www.dayton.va.gov/locations/directions.asp",
"phone": {
"main": "937-268-6511"
},
"physicalAddress": {
"type": "physical",
"line": [
"4100 West Third Street"
],
"city": "Dayton",
"state": "OH",
"postalCode": "45428-9000"
},
"healthService": [
"Audiology",
"Cardiology",
"DentalServices",
"Dermatology",
"Gastroenterology",
"Gynecology",
"MentalHealthCare",
"Nutrition",
"Ophthalmology",
"Optometry",
"Orthopedics",
"Podiatry",
"PrimaryCare",
"SpecialtyCare",
"Urology",
"WomensHealth"
]
}
}
}
image.png

Scenario 2: When HSRM returns the Type of Care field in the response body for a booked appointment. I tried multiple instance and HSRM is not returning the type of care, so I reached out to Kent and Moshe to see if we can send that field in the response so that I can validate it on the VAOS side. I'm still awaiting their response.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
