### ISSUE TITLE
[design] Create an onboarding deck/meeting for Design

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#414]
## Goal
As part of the epic for preparing to onboard our first VFS team, we will conduct a breakout meeting to onboard new designers.

## Acceptance Criteria
- [x] Reviewed with Product Support and Platform Design team

## Definition of Done

- [x] Slide deck for design/research onboarding meeting
- [x] An agenda that can be distributed in advance of the meeting
- [x] Links to resources discussed in the onboarding meeting for sharing with VFS team members

**Comment by hpjaj** [comment]
Hi @smoonpeyes - Heads up, instead of creating a dedicated issue for all four agendas, I am adding the agenda as a DoD item to each slide deck issue.  This way the deck's author can pump out the agenda really quickly.  So I added one DoD item to this for "creating an agenda".

**Comment by smoonpeyes** [comment]
@emilywaggoner We can probably use some stuff from DSVA's [How we UX deck](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Research/Vets.gov_HowWeUX_Jan2018.pdf).

**Comment by andreahewitt-odd** [comment]
@smoonpeyes Can you move the presentation from drive to github?

**Comment by smoonpeyes** [comment]
Presentation added: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/templates/VFS-UX-Onboarding.pptx
