### ISSUE TITLE
[Dupe] Update HLR Static Page Content 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4140]
@Karak888 FYI @jenniferlee-dsva will fill in later wanted to get in for groomint.

**Comment by Karak888** [comment]
@lwalsh617 to look into REACT tool to see if it has been represented in screenshot as don't need to go live with REACT piece NOW..

**Comment by peggygannon** [comment]
@Karak888 @lwalsh617 I posted my feedback in https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4139 ,as well as below: 

 Here some feedback/content recommendations from me for this page. Let me know if you have any questions or want to discuss the feedback in a call.

General question: When I was editing the HLR form, it said that the online form could be used for disability comp and pension claims. But the static page only mentions using the online tool for disability comp claims. I wanted to raise this as an question we need to resolve with that team/the SMEs.

---

Under Online header
I suggest recasting sentence to the below to more closely align with online
You can use our online tool to request a Higher-Level Review for disability compensation claims. This online option is available for only disability claims at this time.

---

Subway Map under step 2
To schedule an informal conference, select times and list a phone number in Part II of the form. A reviewer will call 2 to 4 weeks after VA processes your request.
Please rewrite first sentence to to make it more conversational:
If you’d like to schedule an informal conference, please select the times you’re available for a call and list a phone number in Part II of the form.

---

Subway map under step 4
This sentence seems duplicative, as we mention the PDF at the beginning of the subway map
Fill out the Decision Review Request: Higher-Level Review (VA Form 20-0996).
Download VA Form 20-0996 (PDF)
I recommend that we remove this line and replace it with:
Submit your form in one of the ways below.

So number 4 it would look like this:
Apply
Submit your form in one of the ways below.*

---

Fix odd spacing below By mail header
Under By mail header add the below sentence (and remove it from under the Benefit office addresses header)
Send your completed VA Form 20-0996 to the benefit office address that matches the benefit type you selected on the form. Find my benefit office address
can we make this link a jump link??
Please tweak/add the below sentence to under In person header (and remove it from under the By fax header
You can also ask a regional benefit office for a copy of this form to fill out. You can also request a form by calling the VA toll-free hotline at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

Benefit office addresses, bump up this header and remove the text next to it.
cc @jenniferlee-dsva

**Comment by lwalsh617** [comment]
**Please note:**  This ticket is a duplicate. See Ticket 4139 for the active thread on the HLR static page. 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4139
