### ISSUE TITLE
CatalogInfo.yaml for CUI

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#41401]
In order to integrate with the Platform Console we should add our repos and docs to the Console Catalog.

**Comment by kylesoskin** [comment]
Starting this today

**Comment by kylesoskin** [comment]
Meet with CUI team and gave feedback. Also got some input on what was done so far. I am adding a few more things today then will wrap this up.

**Comment by kylesoskin** [comment]
Just need to figure out where to put the yaml files and this will be complete.
