### ISSUE TITLE
AWS access for Jill Adams

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#41412]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Other
Scott Mason, Booz Allen Hamliton

### Your Name

Jill Adams

### Your Email

jill.adams@agile6.com

### Your Team, Role, and Company

Sitewide Public Websites, Delivery Manager, Agile 6

### Product Manager (PM) name and email

Wes Rowe, wes.rowe@agile6.com

### Product Owner (PO) name and email

Dave Conlon, david.conlon@va.gov

### Desired AWS Access

**S3 bucket**:  s3://vetsgov-website-builds-s3-upload/ 
**Access requested**: Read access to cp bucket assets using CLI
**Why**: Re: #9084, the Public Websites team assists with content audits. The most efficient way to satisfy requests like this is to grep through the contents of a content-build output, which are pushed to S3 daily. 

[This slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1652716912602589) suggested requesting this AWS access. Please let me know if you need more information or have concerns.

Note: I have SOCKS access as part of the Sitewide CMS team, from before the VFS Team Roster rule was in place, so am not in that roster.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jsgarmon** [comment]
@jilladams : I understand you've been using the platform for some time, but we can't move forward until you are on the VFS roster. Please ask you're manager to add you.

### For AWS Access
User: Jill Adams
COR: Courtney Bethea
VOR: Scott Mason, Booz Allen Hamliton
Approval needed: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no
Approvers will check with your VOR on your EQIP status.

**Comment by jilladams** [comment]
I've been added to the roster.

**Comment by td-usds** [comment]
reached out to VOR

**Comment by jsgarmon** [comment]
AWS access has been granted, and first-time login instructions sent via Slack DM.
