### ISSUE TITLE
Attend Designer presentation

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4144]
## User Story:
As a ___Front-end dev_______, I need _____to attend the discovery presentation_____ so that I can ___have a better understanding about  the product and the Veterans_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Attend meeting 1-hr

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] attend meeting 

## Next Steps
- Apply information to Front-end work 

## Blocker
-N/A

**Comment by rileyorr** [comment]
@mr0sari0 & @wygonikGCIO I am reopening this issue because the discovery readout meeting has not happened yet.
