### ISSUE TITLE
Staging Realm

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#41446]
Add a realm to Utility Keycloak to simulate a staging environment so we can break dev.

**Comment by calquisola** [comment]
the database was provisioned in the "dev" cluster.

**Comment by calquisola** [comment]
deployed in argocd. 
We have a pending[ PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/598) for config fixes

**Comment by calquisola** [comment]
Ops approved our PR today. This is live.
