### ISSUE TITLE
SOCKS access for Kha Huynh

### ISSUE THREAD

**Issue by khathuynh-tw** [department-of-veterans-affairs/va.gov-team#41455]
### Your Name

Kha Huynh

### Your Email

kha.huynh@thoughtworks.com

### Your Role and Team

Software Developer, Virtual Agent Chatbot team

### Product Manager (PM) name and email

Ian Santarinala, ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais, Luciana.Morais@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCYg/NEN0BlI2y3w2UPLVaPp12P8p7CuQ7pLFMQiithzR6RpLJUEoNRBIR8YRxFeMp4ojF3Qnck7HdIf5YH/uDN22q2QR+OblQygTp5QYBLQ+NUqCSzacGoNCi3RWtZiCBkNCYLsJQmI2txaWkt65D7ABb7sYA93e2Ptmm2Xc+e1EZvponxitxFfLKB9XOYzf8LANE/YFrOgV/IX2EFBr6v8+W6IDt1nBCnX2OqmZBv7CMZe3ukgeGaJShfvWe0KyDsO9v2yU22hoUaDsYdg4aVPkEP58MHr+tzo7pl1AHAEU3WIwpFMEVt7ZoNRLbqSu3pbOdVBpjvv7yp4kUEODqOBYMeQHzTM6sez5PP6xvOcd3D5KsagJOV4wEY0PAMgTI9zkTn1VMcZekBqvyX9LXbXzAYMkrqDnRvezP27WgQRbDpgt9Inle9qU+KD19dZSpnM++oFGUD8M2KFE3DF41vMqj88ofJk8gKCZhICsbBM8X7VwYcs4I8qTr0JW62A8= khahuynh@Khas-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
