### ISSUE TITLE
Attend Brainstorming meeting

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4145]
## User Story:
As a ___Front-end dev_______, I need _____to attend the brainstorming meeting_____ so that I can ___have a better understanding about direction the team is taking regarding the project_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Attend meeting 1-hr

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] attend meeting 

## Next Steps
- Apply information to Front-end work 

## Blocker
-N/A

**Comment by rileyorr** [comment]
@mr0sari0 & @wygonikGCIO I am reopening this issue because the brainstorming meeting has not happened yet.
