### ISSUE TITLE
[FE] Implement Lambda API Middleware for Staging Appointment application

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41463]
## User Workflow
We can use a main handler and then separate files per "endpoint"

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
This work is now feature complete, I'll close this out once we've tested that it's all working with the app.

**Comment by acrollet** [comment]
Haven't had any problem reports, closing this out
