### ISSUE TITLE
Update logic for displaying TMP/Telehealth info on booked appointments

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#41460]
When the frontend fetches appointment data, there is expected to be some amount of telehealth-related attributes so the UI can render the appropriate links and messaging for that kind of appointment. The structure of that data in V2 will differ from V0, so vets-website will need to update the logic to handle that.

This ticket is blocked until we get the final version of how the telehealth data will be structured.

AC:
[ ] UI displays appropriate links and messaging for telehealth appointments to cover the same cases as what's in V0.

**Comment by ldelacosta** [comment]
Waiting for VAOSR-3636 to be completed before the team can begin the analysis.

**Comment by ldelacosta** [comment]
Just adding the update that VAOSR-3636 is done. This ticket should not have any blockers. If there are any blockers/impediments, please let me know. Thanks!

cc: @cferris32
