### ISSUE TITLE
[FE] Create Patient Information page for Staging Appointment App

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41468]
## User Workflow
- after test patient is selected:
- select this page from a tab at top of the page
- ~Button to reset demographics info for test patient (so screens can be viewed again in the CIE app)~ split into #41974
- View appointments booked for the selected test patient in the next 7 days
- Generate UUIDs / pre-check-in / check-in links for a booked appointment (on AppointmentActions Modal. )
  
## Wireframes
- [Sketch]() **_insert link to sketch file_**
- NOTE: The following is a screenshot of the Sketch file at the time this ticket was created, if the screenshot differs from the Sketch file when this ticket is worked, please raise the issue with the team during stand up

  - **_insert screenshot of Sketch file that shows the work to perform in this ticket_**

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
Implemented this today.
