### ISSUE TITLE
SOCKS access for Salvador

### ISSUE THREAD

**Issue by MrMorie** [department-of-veterans-affairs/va.gov-team#41479]
### Your Name

Salvador Gutierrez

### Your Email

sal.gutierrez@adhocteam.us

### Your Role and Team

Backend Engineer

### Product Manager (PM) name and email

Sai Priya - saipriya.gopalakrishnan@adhocteam.us

### Product Owner (PO) name and email

Thomas Delrue - thomas.delrue@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkIMKAfa4lzhX54WxaQfr9u80dOLdCj+5iGi/+gJhSCS+3wBqbRIseK1Os9mBY593DdFicCDa/Iwjz/iFdgTVBC5kdNCzJFzbTMSTX53iZXkUmmRUra9VGv4ho1dLwa8nnBtCr3Kb6vDgH1grt/nJ8mPmXh+o01AyIFSTV+Aebu6Jj+ZY6vKkkrEIsQCHd1xmzikstb3oXdCWtgpSJh57tdhZVNxCQn+Gzv4YQnMpQ0cuZGgx0QEgdRenWGTEDRl82hXgzWDgcWyBI1FXNXy2/FOsHeURhyI583ZtOUe515JtKEw8H3KiLt+wJd7QitWVmCvcYxWIgjiYx10xYnO+0bUgrTRKMrybeQ9s3U+0npkvaDFgP3lRbQNQ0jRc0VXw9BsiOKnnJVMPm2JRoyejNHNWos/Y5jqB57aYPRuqGfsXiQVLN0YbgfI5qViB4EfVuBqNXvRVkbJKcPNTpdZriBz1rNNgzM3Vq+BOo9CaHJx+lnCN4oXnghLWB9fUZEac= salvadorgutierrez@AdHoc-MacBook.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@MrMorie is in the platform roster.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
