### ISSUE TITLE
vets-api repository access request

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#41476]
## Description
I'm looking to get access to the `vets-api` repository for an issue I'm currently working on.

## Background/context 
I'm a newer engineer on the Benefits/Claims & Appeals team.

---
## Tasks
- [ ] access to `vets-api`

**Comment by zachclarity** [comment]
@LindseySaari  gave the team vsa-bam-1-frontend access.  https://dsva.slack.com/archives/CQHBJ5U06/p1652808487284959?thread_ts=1652793729.955719&cid=CQHBJ5U06
