### ISSUE TITLE
[FE] Create Test Patient selection drop-down for Staging Appointment App

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41472]
## User Workflow
- User can select a test patient from a drop down. Once test patient is selected, the rest of the app populates
  

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
@brdunfield did this as part of #41467
