### ISSUE TITLE
Add pagination for VA form search results

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#4149]
## User Story:
As a Veteran when searching for a form, I need be able to see all my search results easily.

https://dev.va.gov/find-va-forms-beta/

## Acceptance Criteria:
- [ ] Add Formation "Pagination" component for the above page (You can find this [here](https://design.va.gov/components/pagination).)
- [ ] Add "Displaying x - xx out of xx results for {query}" above the table

**Comment by andaleliz** [comment]
@jenniferlee-dsva, FYI the pagination component will work with the table, so Kelson is going to move in that direction

**Comment by jenniferlee-dsva** [comment]
@andaleliz - what is the max number of results that would display before pagination becomes enabled?

**Comment by kelsonic** [comment]
@jenniferlee-dsva I talked to Liz and she said that we should start with 10 results for now! 🙂

**Comment by kelsonic** [comment]
I originally estimated this as a 5 but I think it turned out to be more of a 3. Updating...

**Comment by Karak888** [comment]
Validated and moving to close.  Thanks!
