### ISSUE TITLE
Display Type of Care on Community Care Booked Appointment [V2] 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#41492]
## Description
The Veteran should see the type of care for their booked Community Care appointment on the appointment details page.

V0 (current state): 
_We do not display Type of care in production since V0 does not have the data available._ 
![Screen Shot 2022-05-03 at 11.03.32 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/8e69780a-7e6f-409c-9567-c70525d8c78d)

---
## Acceptance Criteria

Given the facility booked the Community Care appointment 
When the user views their upcoming Community Care appointment in VAOS
Then the user will see the Type of care on the appointment details page
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-future)
And page design matches the [design spec](https://www.figma.com/file/WJ55KM4G2Sk15bfIGsRpzr/Add-Type-of-Care-%2332956?node-id=101%3A25)

Given the facility canceled the booked Community Care appointment 
When the user views their canceled Community Care appointment in VAOS
Then the user will see the Type of care on the appointment details page
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-canceled)
And page design matches the [design spec](https://www.figma.com/file/WJ55KM4G2Sk15bfIGsRpzr/Add-Type-of-Care-%2332956?node-id=101%3A25)

When the user views their past booked Community Care appointment in VAOS
Then the user will see the Type of care on the appointment details page
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-past)
And page design matches the [design spec](https://www.figma.com/file/WJ55KM4G2Sk15bfIGsRpzr/Add-Type-of-Care-%2332956?node-id=101%3A25)

### Design Assets
[Sketch Design File](https://www.figma.com/file/WJ55KM4G2Sk15bfIGsRpzr/Add-Type-of-Care-%2332956?node-id=101%3A25)
Page structure guide [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/content) reference

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@vbahinwillit 

Validated the changes in staging for patient999@id.me user.

I do not see type of care listed on the booked CC appointment. 

I submitted the CC request for 06/29: 
![Screen Shot 2022-05-31 at 2.22.28 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/f758cb21-be31-4c0a-a9b1-699dd2b421db)

HSRM staff booked my CC appointment for 06/15: 
![Screen Shot 2022-05-31 at 3.53.04 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/82f2c61c-f643-45b9-9c0c-26911b434d80)

**Comment by vbahinwillit** [comment]
Ready for PR
[http://e370a40bd8aaa4800719377a502e61da.review.vetsgov-internal/](http://e370a40bd8aaa4800719377a502e61da.review.vetsgov-internal/)

**Comment by ldelacosta** [comment]
Added the type of care label for booked CC appointments. We created a new ticket #43460 to remove the type of care label on booked CC appointments if the service type is blank or when service type is not available. 

![Screen Shot 2022-06-27 at 3.02.00 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2cafedbe-1046-4d1c-b41b-5eabf78b3447)

cc: @simiadebowale
