### ISSUE TITLE
Check Logs for Phone Numbers Associated to 2 or More Veterans

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41499]
Let's check the logs to see if two or more different veterans are associated with a phone number, and those veterans all have appointments at their respective facilities on the current date.

[Slack thread](https://dsva.slack.com/archives/C02UP02HHGX/p1652815562894789?thread_ts=1652724797.394879&cid=C02UP02HHGX)

**Comment by loripusey** [comment]
@acrollet can we close this one or is it still in progress?

**Comment by acrollet** [comment]
@loripusey there hasn't been a response on the slack thread but we have checked the logs, let's open a new ticket if any further work is requested.
