### ISSUE TITLE
Create a solution for error handling on form search

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#4150]
## User Story:
As a veteran, I need to know when the "find a form" service is down so that I don't think it's a user error when no results are found.

## Acceptance Criteria:
- [ ] API errors are addressed and surfaced to the user via an [`<AlertBox />`](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/).

**Comment by kelsonic** [comment]
Currently, there is no validation on the query the user can send to the `/forms` API endpoint, which is fine and means that there will be no user-created validation errors that I can think of.

However, the API could return back 500 errors currently in the case that the service is down for whatever reason. As a result, we should surface these errors to the UI so the user does not think they are doing something wrong.

After discussing with @ncksllvn, it seems like we could either use [`<AlertBox />`](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/) or [`<ErrorableTextInput />`](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/errorabletextinput/) to surface these 500 errors. Unless there's objections, we'll go ahead and proceed with using the `AlertBox` as errors coming from the text input may look like the user can do something about it, which they can't :)
