### ISSUE TITLE
[FE] [Discovery] 10-10EZ prefill alert message should only appear on pages that we have prefilled info

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#41514]
I'm not 100% if we have control over this, but I do notice that some pages have it and some don't. In an ideal world, we only show the blue alert on pages that we fill in info for that specific user. 

![Screen Shot 2022-05-17 at 4.36.12 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/7aca8fd0-e215-46f7-9202-00584b720d49)

Currently messaging bar is shown if we _can pre-fill data on that page_, even if there's no information to pre-fill.

**Comment by markfallows** [comment]
Question: Do we need to display it on every page that can be pre-filled, or is one message at the beginning enough to keep users informed?

**Comment by longmd** [comment]
Additional question: @lzapson, is there a master document or something somewhere that shows exactly what data is included in prefill?

**Comment by longmd** [comment]
@Dene-human , that is super helpful! Thank you!

**Comment by lzapson** [comment]
@longmd my understanding is prefill information comes from another system that can be prefilled in a form. So, I would think not.
