### ISSUE TITLE
Profile | Personal Information | Foundational Accessibility Testing

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41526]
Staging Review Process doc [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)

Checklist of the recommended and required accessibility tests have been completed for this effort.

**Foundational accessibility tests (required)**

- [x] Axe scans in daily development 

- [x] Axe scans included in end-to-end (e2e) tests 

- [x] Color tests for proper contrast and colorblindness 

- [x] Content zoomed to 200%, 300%, 400% 

- [x] Keyboard navigation 

**Advanced Accessibility tests (recommended)**

- [x] Screen reader tests (VoiceOver + Safari or NVDA + Firefox) 

- [x] WAVE tool spot checks 

** Additional Tasks**
- [x] Create tickets for any fixes that are required based on above testing

**Comment by adamwhitlock1** [comment]
Notes on foundational accessibility testing:

- Ran Axe scan on personal information page

![Screen Shot 2022-05-18 at 2.00.48 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/b50edc1a-f040-43f1-8e99-632866458ae3)

  - 9 'Needs Review' items, but no Critical, Serious, Moderate, or Minor issues reported
    - Of the 9 needs review issues, most were just the tool not being able to fully check color contrast, but I have manually checked the lowest contrast sections  of the UI (the gray detail text of preferred name) and the contrast was a AA passing contrast of 4.6:1 which is passing.


- Confirmed that Axe scans are included on all e2e tests
- Color contrast checked and verified to be 4.6:1 or better (see above axe comments)
- After zooming to 400, 300, and 200% confirmed that there are no apparent display or overflow scrolling that is happening within the page. All content has spacing between the edges and can be read appropriately.
- Keyboard can be used to tab logically through the form elements and can trigger their functionality.
	- Accordions received focus and were opened with the return key
	- Each field could be edited with return key and focus was set on the input field
	- Each field could be updated and canceled with the return key

**Advanced Accessibility Tests**

- Ran through the page with mac VoiceOver and was able to hear content read as expected as far as I could tell.
- Used the WAVE tool and spot checked the page with no error that pertained to our application code.
	- The errors / alerts that were shown on WAVE pertained to the header section and not our page specifically.

![Screen Shot 2022-05-18 at 2 20 09 PM](https://user-images.githubusercontent.com/8332986/169149196-246fad0d-81f5-43a4-b38f-8bed4c5192d3.png)

**Comment by adamwhitlock1** [comment]
At this time I don't have any issues that would require any further tickets based off this testing, so I think we are good to go for the staging review!

**Comment by SKasimow** [comment]
Completed....closing
