### ISSUE TITLE
[FE] - Profile: update feedback alerts

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#41529]
**Tasks**
1. We need to update the user feedback alerts in direct deposit to be consistent with what we do in other parts of profile. Currently, they display under the page `h1`, which is easy to miss on mobile devices. We need to move them so they appear above the button the user clicked to trigger the action:
- the edit button for a success message
- the update/save button for any error messages (discovery needed at the time of this writing)

We also need to simplify the copy and update it to say "Update saved" instead of the long copy there now.

2. Throughout profile (contact info, personal info, and direct deposit) we need to update the CSS on the alert so it fills parent to determine it's width. Currently it's an awkwardly narrow size that doesn't look quite right, which doesn't match the design files.

Here are examples from contact information that shows how the alert should display: [mock](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/jgLJlzG) 

~[desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/zx2qQ2e) and [mobile](https://www.sketch.com/s/59857eb5-~~d9f9-4145-99d3-d9a1de2d0655/a/oYO1LOj)~

**Acceptance criteria**

- [ ] DD alerts are consistent with other parts of profile
- [x] The width of the alert matches what is shown in the Sketch files

**Comment by andaleliz** [comment]
Hi all, just creating this ticket as a placeholder for when #41528 is complete. Added that as a blocker to this one.

**Comment by SKasimow** [comment]
@andaleliz - I verified this in staging; does it need to be checked in production as well?

**Comment by andaleliz** [comment]
Sorry I missed this while I was out @SKasimow. I'm not totally sure, I don't frequently validate tickets once they're coded out. I _think_ we typically only validate in staging, but maybe @adamwhitlock1 can confirm what the process is?

**Comment by adamwhitlock1** [comment]
Once it is validated in staging we will typically close the ticket, unless there is a specific validation process that we want to explicitly follow within a prod account. I will close this now though.
