### ISSUE TITLE
Iterate and finalize IA trees w/ Hlt-Apt team (#1)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#41538]
- [x] Hold mtgs with Business partners to iterate / comment on / amend / approve on IA trees for hypotheses testing
- [x] include approved trees in research plan

**Comment by tameracorson** [comment]
5.26.2022 IA Tree link in Google.  Last updated by @MOStudioCarolyn 
https://docs.google.com/spreadsheets/d/1B14UkjcpJsqlo4kZvIv3G4Pw1cgmTFYXYnvXv5MWSfQ/edit#gid=294134431

**Comment by MOStudioCarolyn** [comment]
Tasks here https://docs.google.com/document/d/1QN_wqztnz3Yh3xTk85afacnLjyZp_EnwqDw6Gj4RiR4/edit?usp=sharing

**Comment by tameracorson** [comment]
Final trees... saved to GitHub
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/health-apartment/Health%20Hub/Research/IA%20Tree%20Test%201/HH%20-%20Trees%20base%20H0%20H1%205.29.22.xlsx
