### ISSUE TITLE
Design and build IA treejack tests in Optimal Workshop (#1)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#41540]
- [ ] Design and build IA treejack test in Optimal workshop for all 14 cohorts plus pilot
- [ ] Socialize test with VA-PO

**Comment by MOStudioCarolyn** [comment]
Veterans Baseline: https://dj540s05.optimalworkshop.com/treejack/3l312tkk
Veterans H0: https://dj540s05.optimalworkshop.com/treejack/tsimbd6q
Veterans H1: https://dj540s05.optimalworkshop.com/treejack/3tcd71tc

Caregivers Baseline: https://dj540s05.optimalworkshop.com/treejack/f5mzmh07
Caregiver H0: https://dj540s05.optimalworkshop.com/treejack/tsimbd6q-0
Caregiver H1: https://dj540s05.optimalworkshop.com/treejack/3tcd71tc-0
