### ISSUE TITLE
Discover Readout meeting

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4154]
## User Story:
As a ___UX Desginer_______, I need _____to present the discovery presentation_____ so that I can ___my finding are know by the team_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] create a meeting 1-hr

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] attend meeting 

## Next Steps
- Apply information to Front-end work 

## Blocker
-N/A

**Comment by rebeccawalsh** [comment]
@wygonikGCIO We already have a ticket for this: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3439

Please close this one out to prevent confusion.
