### ISSUE TITLE
Discovery: Rough User Scenarios 

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4155]
## User Story or Problem Statement
As a UX Designer, I need to create rudimentary  scenarios so I can share this artifact with my team prior to the feature scoping activity.

## Tasks
- [x] Create a list of preliminary scenarios for our personas (1.5 hour)

## Acceptance Criteria
- [x] Rough list of scenarios uploaded to GH

## Next Steps
- Turn scenarios into customer journeys (and possibly service blueprints)

## Blockers
- Personas Creation [4298](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4298)

**Comment by rileyorr** [comment]
@wygonikGCIO & @rebeccawalsh: The user scenarios based on the personas can be found [in the same document as the personas](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/discovery-nov19/personas.md).
