### ISSUE TITLE
[BUG] Pre-checkin should not be allowed to be attempted more than once

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#41563]
## Time Box
1 day - let's spend 1 day trying to reproduce the bug, if we can't after 1 day we will close this ticket

## Background
Sometimes we receive an error from VistA for pre-checkin already complete. When this happens, the attempts are generally a minute or two apart. We need to reproduce the issue and fix it if possible.

https://dsva.slack.com/archives/C02U11L00TF/p1654020402374599
https://dsva.slack.com/archives/C02U11L00TF/p1652811582723779
https://dsva.slack.com/archives/C02U11L00TF/p1652711501978419

## Acceptance Criteria
- [x] Issue is reproduced
- [ ] Issue is fixed or follow-on created

**Comment by acrollet** [comment]
We met with @stephenBarrs @brdunfield @randomsync @brianseek @kanchanasuriya on Thursday to dig in on this issue. After some investigation, we discovered that this is what appears to be happening:

* veteran visits the pre-checkin link and finishes answering questions
* call is made to the complete pre-checkin endpoint - this call eventually hits the 30 second API Gateway timeout and the veteran sees an error page
* the call completes and the `pre-checkin complete` step is set in VistA
* the veteran re-tries pre-checkin, either by clicking the sms link or reloading
* the new call to complete pre-checkin errors out, because the appointment already has the `pre-checkin complete` step set in VistA

Next steps:

The ideal state is for the API call not to time out. To that end, @stephenBarrs suggested that we wait until the [VistA Api Cloud migration](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/791) is complete and re-evaluate the frequency of this issue. (The hope being that the migration will improve the scalability & performance of the endpoint)

If we're still experiencing trouble at that time, we can pursue one or more of the following approaches:

* modify the complete-precheckin call to return a success response with a specific message when pre-checkin is already complete, so that we can show more helpful messaging
* change the API approach to add a complete precheckin request to a queue and provide a status endpoint that the FE app can poll

**Comment by acrollet** [comment]
Blocking this on https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/791

**Comment by acrollet** [comment]
After further investigation, I can say that this is still happening but at a much reduced rate. Basically any error encountered during the complete-precheckin CHIP call will trigger this if the veteran reloads or returns to the link. I don't think we should dedicate more effort solely to this issue, but instead we should continue to pursue the [error monitoring effort](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/40517) and surface issues to the PCI API team as we find them and communicate impact/priority.

(I've added a comment to [one existing issue](https://github.com/department-of-veterans-affairs/chip/issues/1399#issuecomment-1329898024) as part of this work)

**Comment by acrollet** [comment]
@loripusey I've put this in validate, let me know if you agree with the conclusion or if you think we should dedicate more effort to preventing this error. Thanks!

**Comment by loripusey** [comment]
I agree, closing.
