### ISSUE TITLE
Platform Tools Page Change Log

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#41561]
### Description

Please add a change log on the Platform Tools page. It should track what information on the tools got changed, the reason and when was the change.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-tools.1872855066.html

**Comment by lianilychee** [comment]
Hey @raywangoctova , the Platform Content Team will refine in our backlog and prioritize against our other existing work.  We’ll also have to gauge your suggestion with our existing content strategy.  Will keep you posted!

**Comment by vbellissimo** [comment]
Hi Ray. Since the website is regularly updated and deployed, I'm going to close this ticket. If anyone asks for this information, my team or anyone in on the Platform is able to gather it for anyone who requests it.
