### ISSUE TITLE
SOCKS access for Justin Trieu

### ISSUE THREAD

**Issue by justin-trieu** [department-of-veterans-affairs/va.gov-team#41576]
### Your Name

Justin Trieu

### Your Email

justin.trieu@thoughtworks.com

### Your Role and Team

Orchid, Developer, ThoughtWorks

### Product Manager (PM) name and email

Alina Murphy, amurphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFL14wQgw4Qhy0+NBx+YAxsp664skwdHyIw+tNmfkouxthbLckA1D6LJNa02q4l/WmpfQl2sQdb7+SYAx76/qPmfRX4Nseuc+GD2rXj+9l8kqkmAYtZumbUmrPax3Z2qh3RCsBBGTTXVCP2kCj+WLmvmdNpt5uxYD6PoSJQHiOk0OtRQT4PgaTftVtb58ngnF/8jDWBz5879dgYebq6UINQ+svKm4IjremHmA4N4Euke5GUKZcihc5ngOA5JSTPxkjflJNPRcKF+G7y38QoyWKkg0fxPxogwPdzQYDx21gcpSuG8nkbMIcjrnLapkRZC1d0r7Az6AU+pY3u5UkKNqfOJr0UQ5mIE+nUmCUKAg4Zio+6SKTTRFaKEbMxKiGIiyv0biybXcED/B+9LzY1gtRtEk1OwpGh+9qRWwoj1iG/LCsUnPyfkXr1OFigcbuAYy0OTDDMOHPsBWnFdC/kMas2WiEIrqhzBSmLh0Qp52LLA7yE/xaIWJ7FrLe4WaV420= justin@Justins-MBP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@justin-trieu is in the VFS roster.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
