### ISSUE TITLE
SOCKS access for Mark Fallows

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#41580]
### Your Name

Mark Fallows

### Your Email

mark.fallows@adhocteam.us

### Your Role and Team

Associate Product Manager 10-10 Team

### Product Manager (PM) name and email

Heather Justice heather.justice@adhocteam.us

### Product Owner (PO) name and email

Lauren Alexanderson laura.alexanderson@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB6EEjUAxuTsF5sZ14u4QRfd3dvxqir1E2Fr6fsTZCE54Nb6XxecsQMZ6lijmxTrRRtD5X/Sqr8GJZBlXrZX481wK9U2EGF3oGWzsRvK7FTsRGKMxOLAeeO3lTLpdjD2+hERCYj4eASIMwH7m06NOS8ecoCtZbSCcCM+C2Xhzi32gbJVX08pNmrMQqJN9yuiD7TlcY53GZpxT6oHVPLU5RAMbXujvaRa9qXxobLiMp3KxdvSNje/eumU7wxTj/QUsixbms0z3RBX3+B3oJ8vJxKOYQV9n4s1Cn7cUCqBBXHuXM+MErFHBGvXmO49HAPmYfYIIWF02b2LLvW/bww/9+nAe5zTtVLcabrlwow8navlnYnKD2q8h7MBzU/sFt6vvVgHpg2UL8ESaGnc4KUBeRCWQqitLJ2XuMpyI/UovX8TrVBXiQEzJ9g0jsh4lM0JTocspvkXl1XE5C/zCcZmtNplVhW5r7BBa2ujstaUpthWLWqrKhzvQwfzyQsFdt7xc= markfallowsadhoc@MarkFallows-HP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@markfallows is in the VFS roster
