### ISSUE TITLE
Updates to sprint reports

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#41603]
Ray has requested changes to the VSP sprint report in a couple places: 

- [This thread](https://dsva.slack.com/archives/GJY0PL91S/p1652202353203209) in VSP-contract-leads
- https://vfs.atlassian.net/wiki/spaces/LEAD/pages/2195685436/Sprint+doc+examples

AC:

**Comment by andreahewitt-odd** [comment]
We need to define what is needed on the sprint Report, what process changes need to be defined and what needs to occur to make those happen. @little-oddball I tagged you too because if we want to validate sprint objectives with the POs and craft definition of done I think the TLs will need to be in those convos to make sure the tickets brought into the sprint align with the objectives.

**Comment by little-oddball** [comment]
@raywangoctova @andreahewitt-odd: I feel like it might be worth some additional conversation on this topic. I am looking through the referenced Confluence page and working to add comments, etc. that we can hopefully all talk about.

**Comment by little-oddball** [comment]
This has been worked and we are actively using updated Sprint reports based on team orientations, etc.
