### ISSUE TITLE
Plan For and Facilitate Handoff of Spike Teams' Work to Core Platform teams

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#41606]
The spike team contract ends Sept 11th and we need to prepare to hand off the work they have built to the Core Platform teams. 

We've started drafting thoughts in [this confluence doc](https://vfs.atlassian.net/wiki/spaces/AP/pages/2192211997/Spike+to+Core+Team+Feature+Product+Handoffs) but it is very much a draft at this point. 

AC: 

- [x] Figure out plan for who is taking what
- [x] Raise risks of this handoff to OCTODE
- [x] Facilitate hand off and reprioritization of team's work
- [ ] OCTODE review receiving teams

**Comment by mchelen-gov** [comment]
Requested additional information in Confluence doc.

**Comment by andreahewitt-odd** [comment]
@mchelen @raywangoctova @humancompanion-usds Can you rereview now that the new info is added.

**Comment by little-oddball** [comment]
Spike teams have been off the project since Sept 2022. Information, etc. was transferred prior.
