### ISSUE TITLE
[Design] Update Wireframes for Retry Limit Sub-Message

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41608]
Related to 39305

@zach-park We need an updated wireframe because we won't know if the user has an i-person or phone appointment until they have logged in; since this is the retry limit, we can't display a custom 2n'd part of the message; please update wireframes after talking to @niradatta1
Also affects https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/41366

## Wireframe

**Note**: 
The in-person appointment is prioritized over telephone appt. with an assumption that in-person has higher usage. 

Screensot:
![Screen Shot 2022-06-13 at 8.22.35 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/6926c913-2073-406d-b1a1-157dbb4ad856)

[Sketch link](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/639F8A94-55DC-47FE-8B41-D8AB8BAFD68A):
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/639F8A94-55DC-47FE-8B41-D8AB8BAFD68A

**Comment by zach-park** [comment]
@loripusey, wireframe is ready for review. Cc: @niradatta1

**Comment by loripusey** [comment]
Where are the wireframes for Check-in? @zach-park

**Comment by loripusey** [comment]
Looks good, thanks @zach-park

**Comment by sarahknoppA6** [comment]
this has been validated and can be closed
