### ISSUE TITLE
Profile | Bad Address Indicator | Foundational Accessibility Requirements

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41615]
Staging Review Process doc [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)

Checklist of the recommended and required accessibility tests have been completed for this effort.

**Foundational accessibility tests (required)**

- [x] Axe scans in daily development 

- [x] Axe scans included in end-to-end (e2e) tests 

- [x] Color tests for proper contrast and colorblindness 

- [x] Content zoomed to 200%, 300%, 400% 

- [x] Keyboard navigation 

**Advanced Accessibility tests (recommended)**

- [x] Screen reader tests (VoiceOver + Safari or NVDA + Firefox) 

- [x] WAVE tool spot checks 

** Additional Tasks**
- [x] Create tickets for any fixes that are required based on above testing

**Comment by mdewey** [comment]
Closing this. Feedback will happen after collab cycle review
