### ISSUE TITLE
Investigate how to expose vets-api http request timing 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#4162]
## Problem
There is no easy way to determine the length of time a request takes from the front end through vets-api to an external service.  We do not have a definitive way to monitor and expose requests to services outside of the scope of the VSP teams that are exceeding reasonable (and possibly) pre defined time limits.  Therefor, we can not push back on business leaders to escalate these issues to the responsible teams.

## Objective 
Investigate and prepare a document that describes how we can better report on the full picture of the timing of a http request to include vets-api and external services timing so we can show a more complete breakdown of the timing of those requests to internal team members, product teams and leadership.

This particular issue is NOT the implementation or prototype of the solution, it is simply an investigation task with an outcome of a proposed solution that we can than take to leadership for feedback.

## Acceptance Criteria
- [ ] Proposal document prepared which includes discovery around options 
- [ ] Feasibility of said options and proposed implementation strategy

**Comment by annaswims** [comment]
Here are some metrics that we have that may be a good starting place.

Mean Latency - measured from Nginx
http://grafana.vfs.va.gov/d/000000026/application-request-breakdown?orgId=1

“Latency breakdown” (Latency by endpoint) - measured from rack
“Mean latency” (especially interesting that it includes external requests)
Rails db_runtime and view runtime 
http://grafana.vfs.va.gov/d/000000017/vets-api?orgId=1

**Comment by LindseySaari** [comment]
Ideas to consider/include in the proposal document:

[Prometheus metrics](http://grafana.vfs.va.gov/d/lG2hMgBZk/http-request-timing)
vets-api metrics - api_rack_request_duration by controller, action
External service breakdown — metrics measuring request time calls to external services & endpoints 

[Datadog](https://docs.datadoghq.com/tracing/guide/metrics_namespace/)
[Retrace](https://stackify.com/retrace-code-profiling/) (Track External HTTP Calls)
NewRelic

[AWS X-Ray](https://aws.amazon.com/xray/) - not in [FedRAMP](https://aws.amazon.com/compliance/services-in-scope/) compliant
