### ISSUE TITLE
Deprecate legacy issues on Digital Experience Product Board

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#41621]
Deprecate outdated items on [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform)

- [x] Close issues from https://github.com/department-of-veterans-affairs/digital-experience-products/issues on the board
- [x] Replace with relevant issue from https://github.com/department-of-veterans-affairs/va.gov-team/issues
- [x] Create followup item to align boards:
  - https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform
  - https://app.zenhub.com/workspaces/platform-project-planning-63211892d241f62032d8aa58/board

**Comment by andreahewitt-odd** [comment]
Sai, Andrea and someone with board permissions walk through the board. Close issues and link up tickets correctly.

**Comment by mchelen-gov** [comment]
Followup meetings to review boards have been scheduled.
