### ISSUE TITLE
Draft Quarterly Planning Cadence for Q3

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#41628]
AC: 

- [x] Draft Quarterly planning Cadence - https://docs.google.com/presentation/d/1I110NPzRkNbIos0cimp7mZa54-4AAXA8FTM5I2r-9MA/edit#slide=id.g131a57f59bd_0_0
- [x] Move to Confluence - https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2221867152/Quarterly+Planning+Cadence
- [x] Get sign off from leadership - https://dsva.slack.com/archives/C01SCFMUNCA/p1654625499310079

**Comment by mchelen-gov** [comment]
This looks complete.
