### ISSUE TITLE
Create Platform Leadership issue template

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#41623]
### Description
Create an issue template for Platform Leadership issues. 

### Subject Areas

- [ ] Product
- [ ] Design
- [X] Engineering
- [ ] OCTO-DE

### AC
- [x] Template created https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/.github/ISSUE_TEMPLATE/platform-leadership.yml
- [x] GHA to add issues to project board https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/add-to-project.yml#L13

**Comment by andreahewitt-odd** [comment]
@mchelen Hey I used the issue template but the labels aren't showing up and it's not showing up on the board. Here's the ticket I created with the issue template: https://github.com/department-of-veterans-affairs/va.gov-team/issues/43224

**Comment by mchelen-gov** [comment]
Tested and confirmed working https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-leadership&template=platform-leadership.yml
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44993
