### ISSUE TITLE
Consolidate Office Hours information into one place

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#41622]
List of all [Office hours](https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings) offered by Platform Teams. 
- [ ] Collect list of all office hours

For each meeting, make sure the following are noted
- [ ] Time and day
- [ ] Target audience
- [ ] Hosted by/maintainer
- [ ] Meeting notes (if taken)

**Comment by little-oddball** [comment]
Would we want this to live on the Platform Roster Page? I recently did in exercise where I added the office hours to some of the Platform Team pages and then excerpted it back to the Platform Roster page. Just a thought.

**Comment by naomimarcussen** [comment]
Platform office hours currently live here on the [Platform Meeting page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings#Platform-Team-Office-Hours). We may want to break this out into it's own page.

**Comment by naomimarcussen** [comment]
@little-oddball I think that having it live on the Platform Roster page as an excerpt makes sense.

**Comment by little-oddball** [comment]
> @little-oddball I think that having it live on the Platform Roster page as an excerpt makes sense.

@naomimarcussen: This should already be the case for at least the core platform teams. On the Platform Roster page it should be in the Team Resources expand component.

If there are some missing, etc. I am happy to help get them into excerpts etc. if we have the information.

**Comment by naomimarcussen** [comment]
Office hours open to VFS Teams on Platform website
https://depo-platform-documentation.scrollhelp.site/support/office-hours

Office hours open to Platform teams on Confluence
https://vfs.atlassian.net/wiki/spaces/AP/pages/2407464993/Platform+Team+Office+Hours
