### ISSUE TITLE
SOCKS access for Anish Kshatriya

### ISSUE THREAD

**Issue by obliviga** [department-of-veterans-affairs/va.gov-team#41631]
### Your Name

Anish Kshatriya

### Your Email

anish.kshatriya@adhocteam.us

### Your Role and Team

Senior Software Engineer on FLT

### Product Manager (PM) name and email

Karen Taylor (karen.taylor@adhocteam.us)

### Product Owner (PO) name and email

Matt Dingee (matthew.dingee@va.gov)

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbKY7C4Nw+pxp6YuApPzgTU+vPP5384dnO0ZWdz8Yg5U+q1zI6OwKUe3NJ1Yf9mG0f+01pUgYaHqdfsPWnvsoO8a0FgsbZ9iIoDZc0H+gEghohjqKa6nqtheblODcqg/VmhAvsV17w41hurXwkNKJGQryK8SDLhBfYCvmklJkICM/UzxrRSE5OFsvSPywinwtRiZHxOj87GUwqTZ7APl2TwUMQ9VNLMUau9d0bu1QsKQW0KnBWz9rktgoI12DO05aqJmVU951RMI5+rOsLj/3l0rTb8h7Y5zkCFndJFPrLUeZyvVrwvk8ixsf4QkK6xVuThWMzlPI62j34YII2bABsQWExFK7+VmMF8ozuNJ3eR+T6mgQK0ya6kQPEViETLIeSMwPwMTqTqXGdTB+AJqpXwMvof9ZOZrQNROmfUsxvkcrMlfDwUNGvCJ2wx70qkvT6KKYIcSTyxc/l8DY8Kl+UMJfwngYH2rtzpc5eLxAaFbuGG02fowM1wQEsMta86I8= anishkshatriya@Ad-Hoc.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
Hi @obliviga ! 
We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with [this platform orientation guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). If you're not newly joining the team, please reach out to your PM or PO for help.
Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by micahchiang** [comment]
@calquisola 👋 @obliviga has been added to the VA github org and is on the[ Forms Library Spike team](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster#Forms-Library-Team). Could you please continue processing this request? Thanks!

**Comment by calquisola** [comment]
@obliviga is in Platform Roster

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
