### ISSUE TITLE
Add to the ABAC playground repo

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#41646]
Good morning Kyle.  Been finishing up my work for this, I’m going to use a configuration for the resource so its fine if they do not match between dev and “production”.
However, to test this fully I need to have three distinct users in the abac-realm:
**A user that is an admin (einstein)
A user this is an editor, but not an admin (feynman)
A user that is a viewer, but not an editor or admin (NOT Found)**
Could a user that matches the last bullet be added to the Abac Playground realm easilY?

**Comment by girldadmk** [comment]
@mhaley37 is this still a priority?

**Comment by mhaley37** [comment]
We are all good with this @girldadmk -- all necessary users needed for our testing purposes have been added to the abac configuration.  Thanks.

**Comment by girldadmk** [comment]
Thanks @mhaley37! I am new to the team, and I came across this aging card.
