### ISSUE TITLE
SOCKS access for Scott Meyers

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#41652]
### Your Name

Scott Meyers

### Your Email

scott.meyers@coforma.io

### Your Role and Team

Software Engineer on the Benefits team

### Product Manager (PM) name and email

sade@coforma.io

### Product Owner (PO) name and email

Matt Self, matt.self@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOQWdjDxwyFJ2mgzAOTxxmScuTlCrYJhS0i8S8ZBdxH9Rgzl/ld2SeWgQ0DwisoVPEjsLNFOtdKvEglen0mc9zeaRCcT76b7JeP1yOTGadhvW0NT2yIBbPUjRLSIBes8qx2EwUFXm/Rmx+jije3zb6akl42BPdI6Li142Z6xl9CMXhMnM6VJLiFViqwoM5KTSgJ6j/6JzSr5zTGsqj4o1yCEPXMT8pnXanaO55rmLVmWrNHXiz15+KlVnJ3Fy2MNP+x9thOU8qdu3TtThEWByefe14VdKE6OrJ9hgmdJIrd7Nvkes2571zmvtUCt+hvGVEXnI8QArjzGWO2U2f1nCkUhNKRyNxkSm3TXdUM3OmG9jqRAXIJ5AHw2v8vNXxRaQNQu0TVGdclHbD8rV11V0EMK75V7Zew4dbPjy02fJiA5jfvz3vFJf7jBHkuLkHusv1hr+41+5+NE4T1aL85vIHwZTJjB1ssdqAOmDYb6Ncx4iRcOhYpINzEXFypdjWx7s= scott@Scotts-MBP.home

### User must exist in a roster before SOCKS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by scottymeyers** [comment]
I can be found on the VFS Team Roster.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by scottymeyers** [comment]
@calquisola thank you!

**Comment by scottymeyers** [comment]
Looks like my Github handle is wrong in the VFS Team Roster, not sure if that'll have implications?

`scottmeyers` should be `scottymeyers`.

**Comment by calquisola** [comment]
hi @scottymeyers,

You are already part of the VA org, so i don't think there would be any implications. In any case you have an issue access wise, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)
