### ISSUE TITLE
Look into why the tests for On Site Notifications have to be skipped for the CI

### ISSUE THREAD

**Issue by tmitchellgcio** [department-of-veterans-affairs/va.gov-team#41688]
The  [My VA Dashboard Notifications E2E spec](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/tests/e2e/dashboard-notifications.cypress.spec.js) from [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21102) had to be skipped. They worked perfectly locally, but in the CI it refused to pass. We tried every known tactic in the book to get it to pass, but never succeeded in locally replicating the specific error in CI.

In CI, the tests are failing to find a specific element (`cy.findByTestId('dashboard-notifications')`).  In Local, however, 20x loops have failed to replicate this, instead failing on API-call intercepts.  Removing waits on those intercepts didn't help with replication.

**Comment by tlei123** [comment]
@tmitchellgcio , fyi, still trying different things in vain to replicate the flakes locally.  Thought I'd start tracking the results here going fwd.  This one below is around the 6th/7th fix attempt...

CI run 17512 (5/26) &mdash; Failed:

- [Summary](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2394228165)
- [Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2394228165#artifacts)
- Failing-spec log line: [1206](https://github.com/department-of-veterans-affairs/vets-website/runs/6619539319?check_suite_focus=true#step:10:1207)

**Comment by tlei123** [comment]
CI run 17560 (5/26) &mdash; Failed:
- [Summary](https://github.com/department-of-veterans-affairs/vets-website/runs/6631647007)
- [Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2398648737#artifacts)
- Failing-spec log line: [1206](https://github.com/department-of-veterans-affairs/vets-website/runs/6631647007?check_suite_focus=true#step:10:1207)
- [Changes](https://github.com/department-of-veterans-affairs/vets-website/commit/7ae94a64cc904a74c856625552cabdd4d1adae30)

**Comment by tlei123** [comment]
CI run 17560 (5/26) — Failed:

- [Summary](https://github.com/department-of-veterans-affairs/vets-website/runs/6631647007)
- [Artifacts](https://github.com/department-of-veterans-affairs/vets-website/runs/6631647007#artifacts)
- Failing-spec log line: [1206](https://github.com/department-of-veterans-affairs/vets-website/runs/6633219309?check_suite_focus=true#step:10:1207)
- [Changes](https://github.com/department-of-veterans-affairs/vets-website/commit/0bbb07e83b444de2d3aa603b1bfdff8345c761f3) - Commented out waits to see if they were interfering with assertions.

**Comment by tlei123** [comment]
CI run 17565 (5/27) &mdash; Failed:

- [Summary](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2399280645)
- [Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2399280645#artifacts)
- Failing-spec log line: [1206](https://github.com/department-of-veterans-affairs/vets-website/runs/6633219309?check_suite_focus=true#step:10:1207)
- [Changes](https://github.com/department-of-veterans-affairs/vets-website/commit/0bbb07e83b444de2d3aa603b1bfdff8345c761f3) - Disabled intercept-waits.

**Comment by tlei123** [comment]
CI run 17621 (6/1) — Failed:

[Summary](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2419012676)
[Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2419012676#artifacts)
Failing-spec log line: [1206](https://github.com/department-of-veterans-affairs/vets-website/runs/6682210830?check_suite_focus=true#step:10:1207)
[Changes](https://github.com/department-of-veterans-affairs/vets-website/commit/31dadb05a00edf072209e332f70211c30119b301) - Added waits back, with add'l callbacks wrapping all subsequent DOM commands/assertions.

**Comment by tlei123** [comment]
CI run 17650 (6/1) — Failed:

[Summary](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2423507614)
[Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2423507614#artifacts)
Failing-spec log line: [1206](https://github.com/department-of-veterans-affairs/vets-website/runs/6695314294?check_suite_focus=true#step:10:1207)
[Changes](https://github.com/department-of-veterans-affairs/vets-website/commit/d6b37fe09356272bf5fab812ec543ed485e08fad) - Enabled includeShadowDom config-option for spec.

**Comment by tlei123** [comment]
CI run 17676 (6/1) — Failed:

- [Summary](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2424621195)
- [Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2424621195#artifacts)
- Failing-spec log line: [1665](https://github.com/department-of-veterans-affairs/vets-website/runs/6698551622?check_suite_focus=true#step:10:1666)
- [Changes](https://github.com/department-of-veterans-affairs/vets-website/commit/23bcb8235635b69d7acd57af957c5060ada3a852) - Moved logins to beforeEach; Removed non-Notifications intercept-waits.

**Comment by tlei123** [comment]
CI run 19361 (7/11) &mdash; Failed:
- [Summary](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2652675760)
- [Artifacts](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2652675760#artifacts)
- 1st failing spec log line: [1603](https://github.com/department-of-veterans-affairs/vets-website/runs/7291492568?check_suite_focus=true#step:10:1604)
- Changes since previous Comment:
  - Added `waitForAnimations: true` to beforeEach config-block
  - Moved logins back into test-blocks
  - Added non-Notifications intercept-waits
  - Refactored DOM-queries to add parent (non-shadow) selector in front of potential-problem selectors
  - Moved assertions into callback function following above refactored queries.

**Comment by tlei123** [comment]
@ddzz , if you have some time to help troubleshoot this CI-flaky spec, I'd really appreciate it.  Feel free to either checkout my [bugfix-branch](https://github.com/department-of-veterans-affairs/vets-website/compare/41688-fix-flaky-dashboard-notifications-e2e-spec), or just start a new one.

The spec passes fine locally, but always flakes in CI.  I haven't been able to even replicate the DOM-query timeouts locally.  I've tried all sorts of test-code changes, but it continues to flake in CI.

**Comment by ddzz** [comment]
> 

@tlei123 I'll take a look tomorrow.

**Comment by ddzz** [comment]
> @ddzz , if you have some time to help troubleshoot this CI-flaky spec [maybe after your Cypress 10 PR gets merged?], I'd really appreciate it. Feel free to either checkout my [bugfix-branch](https://github.com/department-of-veterans-affairs/vets-website/compare/41688-fix-flaky-dashboard-notifications-e2e-spec), or just start a new one.
> 
> The spec passes fine locally, but always flakes in CI. I haven't been able to even replicate the DOM-query timeouts locally. I've tried all sorts of test-code changes, but it continues to flake in CI.

@tlei123 I'll take a look tomorrow.

**Comment by tlei123** [comment]
fyi, @ddzz , i'm gonna add you to Assignees just so this doesn't fall off your radar, but it's _not_ urgent &mdash; it's passing fine locally & only skipped in CI.

FYI, I'll also start a new branch off main, & keep at it from my side when I have time between other priorities.

Thx much for the cont'd help!  :)

**Comment by ddzz** [comment]
> 

@tlei123 I've been working on this in this branch: https://github.com/department-of-veterans-affairs/vets-website/compare/flaky-dashboard-e2e-fix

It appears that a component isn't rendering in CI. Trying to figure out why..

**Comment by ddzz** [comment]
@tlei123 @tmitchellgcio PR with a fix: https://github.com/department-of-veterans-affairs/vets-website/pull/21986

**Comment by tlei123** [comment]
^ @tmitchellgcio , pls. Approve Darius' fix PR above.  Thx much!  :)
