### ISSUE TITLE
Rework Domo queries to use new product list schema

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41685]
## Issue Description
All our queries in Domo that pull QA data for our QA dashboards were linking QA artifacts to a product by joining the product list on ID. As the product list schema has changed, all of our data sets have broken. We need to change all these data sets to use the new product list schema.

---
## Tasks
- [ ] Convert all Domo Data sets for the QA Dashboards to use the new product list schema

## Acceptance Criteria
- [x] All our QA dashboard data schemas are able to collect data successfully without errors.
---

**Comment by CBonade** [comment]
All set here! All dashboard data sets have been rerun and are showing no more errors.

**Comment by pjhill** [comment]
Hooray!
