### ISSUE TITLE
[BUG] Error Title Displays in English when in Spanish Mode

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41681]
## What happened?
Error title displays in English when in Spanish mode

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/f7e2fd75-394a-4359-ac53-1193050fc898)

## Steps to Reproduce
- URL: Pre-Check-in
- Force 3 failed login attempts

## Desired behavior
Error title should display in Spanish when in Spanish mode

## Acceptance Criteria
- [ ] Error title should display in Spanish when in Spanish mode

**Comment by kristenmcconnell** [comment]
I can confirm that this wording was sent as part of the Phase 2 translations.

**Comment by loripusey** [comment]
Thanks @kristenmcconnell , I'm going to leave the bug to make sure it gets resolved when we get the round 2 translations back.
