### ISSUE TITLE
VEText/AVS: Escalations to Rob/Manual ticket creation Support App Integration  [TBD]

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#41694]
## Description

Connect VSA/ASA to Rob's list for centralization.

---

## Acceptance Criteria

- [ ] Design and test implementation
- [ ] Publish
---

**Comment by chancetheoriginal** [comment]
Still in progress.

**Comment by lindsay-insco** [comment]
OBE
