### ISSUE TITLE
Documentation update: "Backend to running vets API locally"

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#41690]
## Why are we doing this? 

As part of our Q2 goals we need to update all reports that are owned for by our team.  This story will focus on the "[Backend of running vets API locally](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567963/Backend)" document

## Tasks

- [x] Update the document with current information if necessary

**Comment by RachalCassity** [comment]
This has been reviewed.
