### ISSUE TITLE
Auto switch from DEA (Ch 35) to Post-9/11 GI Bill (Ch 33) 

### ISSUE THREAD

**Issue by hallihocine** [department-of-veterans-affairs/va.gov-team#41705]
If I select for military status Spouse/Child the benefit DEA (ch 35),  then I change the military status to Veteran, Active Duty or National Guard, the benefit DEA (ch 35) remains selected. Which is not correct (Spouse and Child are the only options eligible for DEA (ch 35)). 

## Steps to Reproduce
- Navigate to: https://staging.va.gov/education/gi-bill-comparison-tool/institution/13957113
- In your military details accordions, select Spouse or Child for military status and select the benefit DEA (ch 35)
- Now, change the military status and select Veteran, Active Duty or National Guard
- Verify the DEA (Ch 35) still selected

## Desired behavior
- Auto switch from DEA (Ch 35) benefit to post-9/11 GI Bill (Ch 33) when changing the status from Spouse/Child to Veteran, Active Duty or National Guard

## Acceptance Criteria

- [ ] Auto switch from DEA (Ch 35) benefit to post-9/11 GI Bill (Ch 33) when changing the status from Spouse/Child to Veteran, Active Duty or National Guard

**Comment by hallihocine** [comment]
Ticket has been validated in staging: Benefit type will default to "Post-9/11 GI Bill" when the military status is changed. (EDU Team decided to keep this refresh option)

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3260&group_by=cases:section_id&group_order=asc&group_id=4656
- Test script: 
[Auto switch from DEA Ch 35 to Post911 GI Bill Ch 33.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8787185/Auto.switch.from.DEA.Ch.35.to.Post911.GI.Bill.Ch.33.xlsx)

**Comment by MitchLivingstone** [comment]
Went to production on 05/26/2022. Done / Closed

**Comment by MitchLivingstone** [comment]
Went to production on 05/26/2022. Done / Closed

**Comment by MitchLivingstone** [comment]
Went to production on 05/26/2022. Done / Closed
