### ISSUE TITLE
Product List: Create PR Template

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41711]
## Issue Description
We need a PR template for the automatically generated PRs that are created as the result of an update issue being generated. This PR request should explain all the relevant information we need to know about whether that PR is ready for approval.

---
## Tasks
- [x] Create a PR template for our GHA workflow to use when it creates PRs for updates.

## Acceptance Criteria
- [x] When PRs are generated for the product directory updates, this template is available.
---

**Comment by pjhill** [comment]
This is in a good spot for user research sessions. We will see what comes of that and adapt in post-MVP efforts.
