### ISSUE TITLE
'Add appointment to calendar'

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4171]
As a veteran, I want to be able to add healthcare appointments to my personal calendar so that I can easily keep track of them and be reminded of them.

AC
- [ ] 'Add to calendar' link / button is displayed next to confirmed appointments
- [ ] Clicking on link adds the event to a veteran's calendar

Not sure what other AC we need to track for this - e.g., what apps we expect this to work in, whether it should be ics, etc.

@rtwell to add a mock of what this looks like.

**Comment by rtwell** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3487
