### ISSUE TITLE
Product List: Create GHA workflow to update YAML template each merge

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41714]
## Issue Description
As we are using a YAML form template, we will not be able to fetch a current list of products. We will need to start with the current list at the time of creating the template, and when changes are made, we need to update the template with the most recent list. This should be able to be accomplished via a GitHub action triggered on merging of a PR.

---
## Tasks
- [x] Create a GitHub action and script that will update the YAML template every time a product list update is merged to make sure it has the most current list of products.

## Acceptance Criteria
- [x] Our YAML template product list gets updated every time a PR is merged.
---

**Comment by CBonade** [comment]
This is currently working. It will only run under the following conditions:

A PR to main in the `product-directory` repository is merged.
The PR that was merged has the label `update-request`
A product name was changed in the changes that were merged.

**Comment by pjhill** [comment]
This was a neat idea to close the loop on a static form. Nice job!
