### ISSUE TITLE
AWS access for Manish Shah

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#41729]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Manish M. Shah

### Your Email

m.c.shah@accenturefederal.com

### Your Team, Role, and Company

Tech lead - Legacy EDU

### Product Manager (PM) name and email

Abe Blanco abelardo.blanco@accenturefederal.com

### Product Owner (PO) name and email

Matt Self-  matthew.self2@va.gov

### Desired AWS Access

I needed access to GIDS prod. I run an update script for Brian Grub to geocode institutions and to do small queries on data if our group needs to research issues on production.

### Access Expiration

6/1/2023

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jsgarmon** [comment]
Closing this, as user has required access:
https://dsva.slack.com/archives/CBU0KDSB1/p1653072145812069?thread_ts=1653069634.650149&cid=CBU0KDSB1
