### ISSUE TITLE
[FSR] NaN are interfering with FSR column calculations

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#41721]
## What happened?
Veterans appear to be able to enter non numerical values when completing the FSR which is preventing the columns from being totaled. 

![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/1a8c01a9-25c9-44b4-9d1a-6d32d426f143)

![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/8a7ac5e8-dc25-4363-a336-19b59a325aba)

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
@Dr-Pongo @OptionSelect  Could one of you check.. is a Veteran able to enter non numerical characters currently or has this been rectified?

**Comment by Dr-Pongo** [comment]
It appears there's an issue with how the totals are calculated and it could be coming from the submission transform. 
**Submitted form data fields showing as NaN:**
- Net take home
- Total monthly payment
- monthly gross salary
- total monthly expenses
- total assets
- Installment Contracts
