### ISSUE TITLE
Analytics Implementation for [Auth Experience My VA - Onsite Notifications]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#41730]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**
Authenticated Experience - My VA team
    
    
- **Provide the link(s) for Google Analytics implementation**
    - va.gov/my-va
    
- **When is the launch date?**
    - early Q3 2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    - [Onsite Notifications success metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md#measuring-success)
    - Also need to track when notifications are dismissed

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jonathan-epstein13** [comment]
Hello @ajakabcin! We would like to know if you and your team are using a component for this and how are the notifications displayed? If it's a modal or alert box, we can give the taxonomy for those. Thank you!

**Comment by ajakabcin** [comment]
Hi @jonathan-epstein13! We are using the `va-alert` warning component and the notifications are triggered by a VA Notify API. Does that answer the question?

cc @AngelaFowler82 and @tmitchellgcio

**Comment by jonathan-epstein13** [comment]
Hello @ajakabcin I believe that does answer the question. If I have any other questions, I'll be sure to post here to the ticket. Thank you! Keep you posted on the status.

**Comment by jennaouellet** [comment]
@ajakabcin The component should be automatically tracked so we'll give it a quick test to make sure everything looks as expected. Is there a specific user that will have the notification or is there a way to trigger one manually?

Thank you!

**Comment by ajakabcin** [comment]
@jennaouellet we're actually building this in coordination with VA Notify and because of all the moving parts it's not yet visible on staging. We'll have to manually trigger the alerts via the Debt Management Center (DMC) so they won't show for any test users until we get that process set up. Would it make more sense to just let you know when we have those test users with alerts triggered so you can investigate?

**Comment by jonathan-epstein13** [comment]
Hello @ajakabcin. Please let us know as soon as you and your team are ready in staging. Let us know when you have those tests users. Thank you!

**Comment by ajakabcin** [comment]
HI @jonathan-epstein13! We're getting ready to do end-to-end testing with our partners on VA Notify and DMC. VA Notify discovered an issue on their end so need a bit of time before we can really get testing underway. That said, currently you should be able to see a debt notification on My VA with test user 36. I'll follow up next week to see what other information you need to continue with this work. Thank you!

cc @ericasauv09 @Samara-Strauss

**Comment by jonathan-epstein13** [comment]
Thank you @ajakabcin! I appreciate the update. Sounds good!

**Comment by ajakabcin** [comment]
Hey folks just following up from office hours last week to acknowledge on this ticket that the feature is in staging. You can check out the feature with any of the test users found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-onsite-notification.md). **Please don't dismiss any notifications at this time though as we're heading into QA and we need them all visible for Tze to do his work.** 

Thank you!

**Comment by jonathan-epstein13** [comment]
@ajakabcin I'll test it out with those users and let me know what you we find/tracking.

**Comment by jonathan-epstein13** [comment]
Hi @ajakabcin so here is the taxonomy to implement tracking if notifications are present or not for users without them clicking anything. You will need only need to fill in _api-name_ , _api-status_. 
```
{
     event: 'api_call',
     api-name: 'View Claims and Appeals',
     api-status: 'started',
}
```

An example would be :
```
{
     event: 'api_call',
     api-name: 'Onsite notifications',
     api-status: 'not delivered',
}
```
Let me know if you have any other questions.

**Comment by ajakabcin** [comment]
awesome thank you @jonathan-epstein13 ! We we also looking for click tracking on on the "manage your debt" link in the notification as well as on the dismiss button. Do we need the taxonomy for those or are those built in?

**Comment by jonathan-epstein13** [comment]
If they are not already being tracked, you can implement those changes as well to the taxonomy. I'll double check to see if they are being tracked. https://www.va.gov/manage-va-debt/ is this the only URL to use for that specific tracking or is there another one, just making sure. Thank you @ajakabcin

**Comment by ajakabcin** [comment]
Thanks @jonathan-epstein13 - correct just that url, but then also click tracking on the dismiss button

**Comment by jonathan-epstein13** [comment]
@ajakabcin I'm going to send the GA tracking for notifications and dismiss button here. Let me know if you have any questions

**Comment by jonathan-epstein13** [comment]
@ajakabcin @tmitchellgcio here are the results of the tracking. Let me know if you have any questions or others you wanted tracked for this ticket.

| Click the dismissal button| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/25b813a4-1163-418d-9a7e-2a61df2acdd1) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/794d5b42-a572-4b74-a363-b4e268b70bc1) | Status | 🟢 Tracking Correctly |

**Comment by jonathan-epstein13** [comment]
@ajakabcin @tmitchellgcio the following **tracking is for staging.va.gov/my-va:**

Format ->| Interaction | Screenshot of Interaction | Screenshot of dL | Status | 🟢 Tracking Correctly |


| Click the dismissal button|![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/1896cf5e-9ede-4b8c-ac18-7bc62e83deeb)  | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/0a5ed098-6903-49ac-b5c8-232b22f98f91) | Status | 🟢 Tracking Correctly |    


| Get Notifications| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/c91c0a51-ed1f-4092-8484-fd2508b54c2b) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/1f370660-32d6-4c85-ac07-90a87ea315a7) | Status | 🟢 Tracking Correctly |


| Click notification | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/32cf04af-c912-4776-a789-5406f39d2608) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/8b96131f-9856-468b-978f-ee659b503399) ||![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/4c5de6ab-80e2-4e9c-8054-c2a75837636d) || ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/ee9db60b-00ad-42a0-a7b9-b38aff0832b0) | Status | 🟢 Tracking Correctly |

| Click notification in new tab (ctrl + click)|![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/0e37c257-b45e-4968-996f-30e99fe566af) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/589aebe8-3379-4b34-ad81-a6d2e458f001) | | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/aee45082-d2e5-476b-978b-852fb9cabb25) |Status | 🟢 Tracking Correctly |

**Tracking for staging.va.gov/manage-va-debt/:**
| Click manage you VA debt button| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/5cbfeb7b-96c4-452d-9cb1-8b637cb1e98b) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/27c05ca9-0a3d-4773-8b9b-54eb6827af44) | | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/c75c2ea8-fe14-4383-b8ad-e838235a8150) |Status | 🟢 Tracking Correctly |

| Click manage you VA debt notification|  ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/6ac1c7ab-f202-4147-a30e-3e3c2f2330ae)  ||![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/1cb702d4-50c9-43ed-8986-6ddf00226638) ||![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/1533c4c7-1901-4ef0-ba71-96ed313d7f0c) ||![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/079acccb-311d-4913-a6d6-a4a916d9d5b4) | Status | 🟢 Tracking Correctly |

Please let me know if there is other tracking you would like to see on this ticket and if everything looks good.

**Comment by tmitchellgcio** [comment]
I think we need to check when the dismiss button fails to dismiss and when notifications fail to pull from the api as well as when notifications are being pulled, but no notifications exists. I'm not sure how you would check the first two though. Outside of that we are tracking everything else unless @Samara-Strauss wanted to check something else.

**Comment by jonathan-epstein13** [comment]
| Get Notifications (success no notifications)| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/e0e5d5a2-9775-4451-8d29-c66c23efd279) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/9e49f5dd-e5ef-4ffd-bc9f-1e0894fc5e60) | Status | 🟢 Tracking Correctly |


I can try to test the failed dismissal button, but then I would need more notifications to be generated. There are only a handful of users whom still have notifications to dismiss.

**Comment by ajakabcin** [comment]
Thanks @jonathan-epstein13 I think we're all set with the validation you've provided - thank you so much!

**Comment by michelle-dooley** [comment]
Resolved.  Closing again.
