### ISSUE TITLE
VEText: Support Form Attachments Included in Email Notifications [TBD]

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#41748]
## Description

Have VSA/ASA include submitted attachments in email notifications. 

---

## Acceptance Criteria

- [x] Design and test implementation
- [x] Publish

**Comment by chancetheoriginal** [comment]
Functionality added to both VEText and AVS support apps: Uploaded/attached files are included in automated email notifications sent to VEText/AVS.

**Comment by lindsay-insco** [comment]
Completed!
