### ISSUE TITLE
Analytics Implementation or QA Support for Auth-Profile Team | Migration of Military Info

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41743]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [x] QA

- **Who is this request for?**

    - Profile Team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - June 2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

We are moving the source of our Military Information page from eMIS (which is being sunset) to VA Profile and wanted to ensure that Google Analytics and DOMO are updated accordingly. Or, be advised what we need to do on our end to reflect this change.

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
Hi Michelle - this template did not have an assignee pre-populated so lmk if I should switch to someone else. Thanks!

**Comment by SKasimow** [comment]
Hello @pavanhothi - the link to the Profile - Military Information page is: https://va.gov/profile/military-information

**Comment by pavanhothi** [comment]
@SKasimow attached are all the API calls we are tracking on https://va.gov/profile/military-information in staging currently. Please confirm if this is everything you are expecting to see. If not, then you are able to add another API call event as needed using the code in the last screenshot I have included. The event parameter must remain as 'api_call', but every other parameter's values may be changed to what you want for any new events. 

Please let us know if you have any questions. 


![Capture2](https://user-images.githubusercontent.com/92319538/171296802-791b1556-67bf-4f31-9d17-2e93c724df5f.PNG)
![Capture](https://user-images.githubusercontent.com/92319538/171296803-9a2d3779-553d-498c-8887-14e8a46a8104.PNG)
![Capture1](https://user-images.githubusercontent.com/92319538/171296804-7e1bfc66-c314-4914-98af-134c231421e0.PNG)
![image](https://user-images.githubusercontent.com/92319538/171296806-edd7a8aa-2922-4259-9ec2-fdb9a9c2be29.png)
![Capture5](https://user-images.githubusercontent.com/92319538/171298114-f9e8f1b1-047e-4419-b107-5b08d7eebb46.PNG)
![Capture3](https://user-images.githubusercontent.com/92319538/171298115-f7e0f641-9c7b-40ab-a142-d90b785eb922.PNG)
![Capture4](https://user-images.githubusercontent.com/92319538/171298116-add12bd8-3b91-444c-a7b5-296ebb0953d4.PNG)
![Capture6](https://user-images.githubusercontent.com/92319538/171299105-0f900180-4ce3-4a22-9af9-6e03e760a656.PNG)

**Comment by SKasimow** [comment]
Changing the endpoint for Military Info doesn't necessitate a change for GA data. Will confirm we see traffic prior to 100% release.
