### ISSUE TITLE
SOCKS access for Rocio De Santiago

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#41741]
### Your Name

Rocio De Santiago

### Your Email

rocio@coforma.io

### Your Role and Team

Frontend Engineer on Benefits Decision Reviews Team

### Product Manager (PM) name and email

Sade Ragsdale, sade@coforma.io

### Product Owner (PO) name and email

Matt Self, matt.self@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj/TR5YlZvVadOd7t/Ug4G4r0ooVAQ2SZadg2CGWJpC+0imIfplpZCn6X43j96QNI8HDrs9w6UJ5KzjNnvZFGd0sdJneeqlhSO9+mqGqwaV5fb2dimLeSF+2e0+EnVPSDbtMUtIGTZ4qfGgLwtR6ycuuy5XMAmiZijZtS3JYJqQ/j+A+No9RwrGD3Z5I4/XG/3jTlIJIetyWyM7xXO2q3QhsFKeF4vSoY5i37sS8dvS1TUOJAm3YimG+FcjrIQjlEWbYAo1Hy5PUuQhG3Bbd5Et6tIaea2gtIjoG+YPhRPf8vxRm/3hpLpWV193TjSfDYaEztX7RvIBIBs6HLwzuRdIOszMdzh8yPLyXiOoL/b++pEnYPGQAdunEBAiadW5n2Q57QZ1MZIpuL+npeeQak5ccdQ+vX2a8C4e3Lm3Pmsehe7EAABzOn/thKM1fPadQEltVGlL5S0nvHxXBkJQWFB92hjoV83lfichIMTyCdRY6j4JLxD3b5DONz3Z7ILKbc= rociodesantiago@CoformaSantiago.lan

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
@rocio-desantiago is in the VFS roster.

**Comment by iriteshp** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by rocio-desantiago** [comment]
@iriteshp Reopening issue in case needed to re-set up SOCKS proxy on new laptop.

**Comment by iriteshp** [comment]
@rocio-desantiago can you please create a new ticket? I no longer work on the team managing SOCKS.

**Comment by rocio-desantiago** [comment]
@iriteshp sure thing! thank you for letting me know.
