### ISSUE TITLE
SOCKS access for Josh Mills

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-team#41747]
### Your Name

Joshua Mills

### Your Email

jmills@kindsys.us

### Your Role and Team

Frontend Engineer on Facilities Team

### Product Manager (PM) name and email

Roger Eagans roger.eagans@agile6.com

### Product Owner (PO) name and email

Wesley Rowe wesley.rowe@agile6.com

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPqzNUZ0ROZF3WND1kz2GNtqy4Y0V3nPP2QyXn2gvglEaV4NA2V/KciH1LOlysBCCGRk9B54FZhBirG6OmXasZk9rejN3gSlyWwsqIz9ezX5AAqGbJMkU8K1WPx31L6AEyoZv5Wm3YokNxEfiQiinLX8YhN9aizmtoG1Q6iGhdB3oz+tlRhW4l7ZEqXwP6oMzgquiwm7+4ZlvAyUvCw3A9bLVkIOQJKRmT6wItQYYBxL2lk9DyB/56QURBCj0g9a2LmOBll/YxKprCLeqy+8FOAIy0oaLc88iurJrjGav65pqHawCKYrWM7fnYwhf1fMQlJDOxT3tOOv5hUxo/LxEvGb/BunW2z8HLt0rfHsqm3BzDEsOT+pHqdaWgMI8WLJam+mpPcREYTajfPtCwcGJ2WGjlOPGLPa6aLUzREVgNW6OyOXsLsK2uRXIJaazisickWOh4U1OCPyEf4p6C1gcYVeV80BWrPZET1C9vXr6u+h2VfJmxX3zlMxqsSB7ZapU= jtmst@Joshuas-MBP.fios-router.home

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jtmst** [comment]
@iriteshp  it appears I am on the VFS roster, under Josh Mills.  my email is [jmills@kindsys.us](mailto:jmills@kindsys.us)

**Comment by iriteshp** [comment]
@jtmst is in the VFS roster.

**Comment by iriteshp** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
