### ISSUE TITLE
Benefits Gateway Service Documentation on Developers ScrollHelp.site Missing

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41754]
# Description
The following [documentation for Benefits Gateway Service](https://depo-platform-documentation.scrollhelp.site/developer-docs/Benefits-Gateway-Service.1887272987.html) is missing on the developer documentation scrollhelp.site.

# Tasks
- [  ] We need to restore or add the updated information on the the developer   developer documentation scrollhelp.site.

# Acceptance Criteria

- [  ] Documentation for the Benefits Gateway Service is accessible on the [Developer Documentation scrollhelp.site](https://depo-platform-documentation.scrollhelp.site).

**Comment by zachclarity** [comment]
Still not deployed -  Scheduled for Publish 5/27 ... Tracking in this thread.  https://dsva.slack.com/archives/C01AS05BQ79/p1653402089466479

**Comment by andaleliz** [comment]
Hi! Any updates on this? I noticed another page is missing too:
https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Profile.1885602002.html

**Comment by zachclarity** [comment]
I add [comments to our Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1653308327002419).

**Comment by little-oddball** [comment]
Determined STALE (6 months)
