### ISSUE TITLE
Devops- Auth Profile - Onsite Notifications - Add public key

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#41750]
## Background

The auth experience team has created a new `onsite_notifications` controller in vets-api that will be called from the VA Notify team.

The VA Notify client will use their private key to digitally sign requests to the vets-api.  The VA Notify team has sent the auth experience team their public key which will be used to verify requests to the vets-api.

Basic steps:
1. VA Notify signs JWT using VA Notify's private key
2. VA Notify sends request to Vets-API
3. Vets-API verifies JWT using VA Notify's public key

## Request

For QA, the vets-api will need to store the public key in staging in order to verify requests.  Two options:
- **Option 1.** Store the public key in a `pem` file and reference from the `staging-settings.local.yml.j2` file in the devops project.
- **Option 2.** Store the actual public key in the `staging-settings.local.yml.j2` file.  This will not require the `pem` file to be stored on the server.

Looking for some help to make sure the public key is configured correctly in the staging environment.  If option (1) is used, then I'll need devops to add the `pem` file.  If option (2) is used, then I can update `staging-settings-local.yml.j2` and won't need any further assistance.  Please advise as to which option should be used.

**Comment by zachclarity** [comment]
This seems to be a new process.  We need to define a process and verify with any teams that may need to approve this new access point.

**Comment by Samara-Strauss** [comment]
Thanks, @tpharrison! Assuming this *is* the ticket, and that another one does not need to be created...?

Also, have you discussed timeline with them? I'm assuming this needs to be done before we QA, but let me know if that is not the case. If it does, we need to make sure that timeline is clear to the devops team.

**Comment by tpharrison** [comment]
@Samara-Strauss - this ticket, along with [#41268](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41268) will need to be completed before QA can begin. 

I spoke with @zachclarity and we're going to go with option 2 for now (see above).  This option doesn't require devops to add any additional files to staging so I should be able to finish both tickets by EOD tomorrow.  If devops decides to go with option 1, then we can always make the configuration change later.

I did give an update to Kyle MacMillan and Evan Parish from VA Notify this morning to let them know that I am working on this, but I have not provided them with a timeline.

**Comment by tpharrison** [comment]
@Samara-Strauss - onsite notifications security works a bit differently (still secure though). My PRs to add the public key to validate onsite notification requests were just reviewed and here is the comment...

> _Yeah this is definitely new 😂 Let me do a bit research and resurface this with team...
Let me ask team and I will have an answer to you no later than tomorrow._

I don't think there will be any issues here...devops is just deciding the best way to store the public key.  I'll let you know when I hear back from them.

**Comment by Samara-Strauss** [comment]
Sounds good! Keep us posted.

cc/ @ericasauv09 since I don't think she's been tagged in this ticket and should have eyes on this while AJ is out.

**Comment by zachclarity** [comment]
[Comments from Slack. ](https://dsva.slack.com/archives/CQHBJ5U06/p1653317874431149) 

This is a little bit out of the ordinary for vets-api, where most of the things are either invoked by [VA.gov](http://va.gov/) frontend, or are Lighthouse endpoints with a variety of consumers. But it’s not without precedent.
As an example there’s a token verification service that Lighthouse uses internally to validate OAuth tokens.

**Comment by tpharrison** [comment]
@Samara-Strauss - support has decided that the public key needs to be stored in AWS SSM.  This is something that I will need to do.

I'm going to follow [this guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html).  If I have any issues, I will reach out to support.

I'm anticipating that I will be able to get this in place by sometime tomorrow.
