### ISSUE TITLE
10-10EZ: Research Form Email vs. Profile Email

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#41766]
How can we track when a user puts an email into the 10-10EZ form **that is different** from the email address already associated to their profile?

**Comment by lihanli** [comment]
i can add logging that will track (each unique user will log one of these events one time only): when an non-blank email is saved to the 1010ez save in progress form: if it's different from the va profile email, or if it's the same

**Comment by hdjustice** [comment]
@lihanli - Did we talk through this?  I can't remember.
If not, I think we would like to add that logging you mentioned.  Where (what program) would we see this?

**Comment by lihanli** [comment]
![image](https://user-images.githubusercontent.com/830084/211631026-c7bb014e-76fb-4409-8e88-9612a8f3dec3.png)
the data is in datadog
there have been 795 users that applied for the 1010ez with the same email as their va profile email and 248 users that applied with a different email.

if the user doesn't put their email in the 1010ez, then that isn't counted.
if the user put an email in the 1010ez and they have no va profile email or their va profile email is different, then they were counted as one of the 248 users with a different email.

**Comment by hdjustice** [comment]
Oh wonderful, thank you!  I will close this ticket then.
