### ISSUE TITLE
Store "VA.gov - login" Datadog Monitor as Code in Terraform

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41770]
# Description
In order to support maintenance and recovery we need to store "VA.gov - login" as code in Terraform.

# Acceptance Criteria
- [ ] "VA.gov - login" has been exported from Datadog as code
- [ ] "VA.gov - login" is stored in Terraform as code
- [ ] Updates to "VA.gov - login" are directed at Terraform code changes
- [ ] "VA.gov - login" change management uses GH and Terraform to integrate changes

**Comment by rbeckwith-oddball** [comment]
This is complete. Waiting for github permissions to create PR.

**Comment by pjhill** [comment]
Once the PR is merged we can close this out -- thanks for sticking to this!
