### ISSUE TITLE
Store "TUD - Status" Datadog Monitor as Code in Terraform

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41771]
# Description
In order to support maintenance and recovery we need to store "TUD - Status" as code in Terraform.

# Acceptance Criteria
- [x] "TUD - Status" has been exported from Datadog as code
- [x] "TUD - Status" is stored in Terraform as code
- [x] Updates to "TUD - Status" are directed at Terraform code changes
- [ ] "TUD - Status" change management uses GH and Terraform to integrate changes

**Comment by rbeckwith-oddball** [comment]
I have the code committed, but I need write access to the devops repo to create a PR

**Comment by pjhill** [comment]
Almost there -- thanks for sticking to this!
