### ISSUE TITLE
SOCKS access for Aslan French

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-team#41775]
### Your Name

David Aslan French

### Your Email

aslan.french@civicactions.com

### Your Role and Team

Product Designer

### Product Manager (PM) name and email

Wesley Rowe: wesley.rowe@agile6.com

### Product Owner (PO) name and email

Dave Conlon: david.conlon@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDM8aBBwbRwATcjnqzTvfQP2gCdj/kX+nVurxptaPw3v89uNwxBtnxnv7ocuYNQFHPHA4Lpc80hK9fr58Z/hoOECPhl9Gyaz13Zk8uXCotvMlIFMUlUCPgctCcER8j0irZpK5n2QD3IgPm4O13x/0RNFsfuEKauHfFwLjMIbJ387ohVSUD0c9uAJdOVHKSCuu+96+y2fI+zX7jGC65rk7PMMuCGilPVZQL/CyK90Mdfw5F4yq0fwM9licIlMp2aMCQLtXBa0tSjFIzzOVDx8aI1nfKFsSOir2X+/2/i30lHk+6oeDNUdIwoa/Jh/PFk0oaUagyWTlgPZAqpjlxNYlZZE/AxfMi+2WvV6DuOcLBjHGRY0dVeQXlXJ/WDiGmsARal8M988IciYiw6qDflvbstm7pQqWretkMK9/GaZnYQzjFtumbXoXWU/Vbi3syPOFkz+MJXjqynGCTWPJi0StS980Bqc6PlGqbJUJBxGgqp57rHSt3BbIbOgvPb9q3Y1U8= aslan@yvaral

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jcklpe** [comment]
I think label is PTEMS but I could be wrong on that.

**Comment by iriteshp** [comment]
I was unable to locate in VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in correct location.

**Comment by jcklpe** [comment]
Thanks @iriteshp : I have signed up for platform orientations next week. Thanks!

**Comment by kjduensing** [comment]
Aslan is now in the VFS team roster.

**Comment by kjduensing** [comment]
@jcklpe - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by jcklpe** [comment]
@kjduensing : excellent. I think I have this working. I followed the configuration on Windows guide and I can now access citrix workspace. Is that a complete SOCKS setup?
