### ISSUE TITLE
SOCKS access for Judge Parajuli

### ISSUE THREAD

**Issue by jpadhoc2022** [department-of-veterans-affairs/va.gov-team#41781]
### Your Name

Judge Parajuli

### Your Email

judge

### Your Role and Team

Senior Software Engineer DevOps on VA Platform Spike team - Cloud Isolation

### Product Manager (PM) name and email

Alan Werner (alan.werner@adhocteam.us)

### Product Owner (PO) name and email

Mike Chelen (michael.chelen@va.gov)

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/i7HG0TLdHVBqdZPCR4HvbFnY8bbkwZotV62iYCDy8In+OYrjMWZ9RZahNTBJ3NKZyOriBGTmGuhv/T34dKf/1ls8TRgzL5cRgZqLbtrGFvSoXlJZSy+z3/hcgKmemxk4AheMWA0yUtkeH3qnXzAlR6qOfoA8l9TukNidfvQabZ4UTDPZkbtB0zanVc+Cp3SrCqh/xbnFx7lBw3JLrn+tbzCgiDystaOR3ogaLT8J6CgjW5kSnroe9umRSp5qsQfJfPCAbUvzQPw0nR1wyi0iNOH7RuD/ldEB6Qsfgt7yfVxcNApQyD06YtBOG546wXEYOGZptPCMk0gBeTgZGJVFT4NM2U4UIJ9xXQo2oAV0MO+Dt5gkFLqlPGdpLseM9+lafUu+qiMK/QKVENTB6zEjEsnsphgRArTzht1Ztxbwa7Chk2d8DUQ0stT1L9GREYX04EY7Jo8PqPdBlMhePSSRQ2mq8q/NO4rjg+OEA75y5kIjLAqW0EIf5FaML2a3Y0U= jpadhoc2022@JudgeParajuli-HP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
I was unable to locate in VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in correct location.
