### ISSUE TITLE
[Ongoing Service] Customer Insights - Collect customer satisfaction ratings 

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#4178]
### **Problem Statement** ### 
VSP does not have a quantitative measure of overall customer satisfaction to report to clients.

VSP does not have mechanism to regularly collect feedback from all VFS team.  

_How might we provide VSP teams with customer feedback on an ongoing basis to help guide prioritization of work to improve the platform._

### **Measuring Success** ### 

- Survey response rate >25%
- Increase in customer satisfaction rating quarter-to-quarter.

### **Additional Information** ### 

**Initial Goal**
Identify and deploy a 3rd party tool for gathering and reporting customer NPS for the platform.  
_Using Optimal Workshop_

**Links**
[NPS Survey Overview](https://docs.google.com/presentation/d/1YlnFRit328WVsrl7y5uRJa6-tXDixlnraweq-X7jcUk/edit?usp=sharing)

[Research on NPS Shortcomings](https://docs.google.com/document/d/1_kKyCfC38wjacFCJXCjwmLc7ZCFfM_xVET3LOuVmFKo/edit?usp=sharing)

[Customer Feedback Loop System](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1580853363126/ef5036613c38f1afeffbc082f28d2d8016c66a4a)

**Comment by rroueche** [comment]
@jkassemi I see this more as a NOW or NEXT need than Future, what are your thoughts?

**Comment by rroueche** [comment]
From KH: could you do a multi-channel strategy to improve response rate to above 20-30%? (hypothesis: email might help)

**Comment by Khyatinp18** [comment]
2/16/2022:
Closing this since we are not going to this initiative moving forward.
