### ISSUE TITLE
Contact Center Review for Patient Check-In -  Updates to User Messaging

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#41790]
## Description

Patient Check-in allows Veterans to check in for their scheduled VA medical appointments using their own mobile phone. A Veteran or an authorized caregiver can check-in up to 30 minutes before and 15 minutes after their scheduled appointment. To complete check-in, a Veteran:

- Views a poster hung on the walls of the clinic waiting area where they have their scheduled appointment.
- Follow instructions on the poster to scan a QR code or text “check in.”
- Receives a text message with a unique link, such as https://www.va.gov/c/xxxxxxx/.
- Taps on the unique link on their phone and begins check-in on VA.gov.
- Reviews, or has confirmed, contact, next of kin, and emergency contact information within the last seven days.
- Remains in the waiting room until a staff member takes them back for their appointment when ready.
- Pre-check-in allows veterans to use their mobile phones to confirm if their contact, emergency, and next of kin information is up to date. Veterans can most often complete pre-check-in at least 7 days prior to their scheduled appointment, but the timing is based upon the facility’s setup. Veterans are unable to pre-check-in after 12:00 AM on the day of their appointment. 

This feature release contains improved messaging to Veterans during the pre-check-in experience. E.g., helpful information when errors occur and/or when pre-check-in is complete. Further information can be found in our [release notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/detailed-release-notes/update-messaging.md). 

### Launch Date

This feature has an estimated release for 5/26/2022. Production validation and and actual release will follow. 

The product launched 5/2/2022 for VISN 8 and will roll out to a new VISN every week. 

### Version Number

1.2

### Product Guide

[PRE-CHECK-IN_PRODUCT_GUIDE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8763342/PRE-CHECK-IN_PRODUCT_GUIDE.docx)

Comments have been used to mark changes to the Pre-Check-In Product Guide. 

No changes to the Check-In Product Guide at this time. 

### Product Video

No changes to the product video at this time as these changes do not reflect main workflow for Veterans. Original product video can be found here: 

https://drive.google.com/file/d/1feXtP9yVuTPE-7J73Sk8mVrQocU6QMNK/view?usp=sharing

https://github.com/department-of-veterans-affairs/va.gov-team/issues/41073

### Product Video Transcript

These files have not been updated. 

[Audio](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/Patient_Check_in_Demo_May_6_2022.m4a)

[Script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/Demo_Script_May_6_2022.pdf)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by benbrasso-agile6** [comment]
@loripusey CC

**Comment by starlow00** [comment]
Both guides edited/sent for approval on ticket #41073 (Request Contact Center Review for Patient Check-in ).
VEO had no changes, thus approved.
Pre-Check-In guide attached here for reference.
[PRE-CHECK-IN_product_guide_v1_1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8789692/PRE-CHECK-IN_product_guide_v1_1.docx)
