### ISSUE TITLE
Analytics show a high bounce rate for in-app Safari browser

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#4179]
Our analytics show a very high bounce rate for in-app Safari. This is a fairly high-traffic browser, and seems to point to apps (iOS) that launch Safari from within the native experience. This is worth a closer look to ensure there's not browser bugs causing rendering or functional issues when pages are loaded.

Please talk with @1Copenut for analytics links.

### Status
Unresolved

### Severity Analysis

* Severity unknown. Could be a long-tail research item.

### User Impact 

* Users to access our sites or pages through social media or other apps
* Users may have a bad or incomplete experience

**Comment by alexpappasoddball** [comment]
@brandonrapp triaging to the FE team.

**Comment by laineymajor** [comment]
closing as this has not been touched since 2019
