### ISSUE TITLE
Document analytics best practices for formation-react components and forms system

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#418]
## problem 
- no recommendations on how to capture analytics events in formation-react components or forms system 

## goal
- document current patterns with using optional event handlers e.g. [linkedClicked](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/MegaMenu/MegaMenu.jsx#L257)
- identify components that should be refactored to better support analytics tracking 

## notes
see [this](https://dsva.slack.com/archives/C5HP4GN3F/p1561657064139300) slack message

**Comment by meganhkelley** [comment]
@caw310 @joanneesteban perhaps this (old) ticket is made irrelevant by the current initiative y'all have in progress #3085? If so, please close this. Thanks!

**Comment by joanneesteban** [comment]
That's correct, @meganhkelley ! @caw310 we'll be working on this piecemeal this quarter, we'll just need y'all to review & approve our PRs for this (the Design System GTM Standardization Initiative from last quarter).
