### ISSUE TITLE
Add "intent to file" and delete VR&E info on Disability page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#4180]
## User Story or Problem Statement
As a Veteran, I need the most up-to-date information so I know how to file a disability claim.

## Goal
The "intent to file" Q&A from this [pension page](https://www.va.gov/pension/how-to-apply/) needs to be added to the [how to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/) page. 

In addition, the related links about VR&E at the bottom of the disability page need to be deleted per stakeholder request. 

## Objectives or Key Results this is meant to further
Gives Veterans the most current information they need to file a claim. 

## Acceptance Criteria
- [x] Remove VR&E related links
- [x] Add "intent to file" Q&A

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva Can you add to this ticket where the "intent to file" q&a needs to go on the disability page? Is it going at the bottom of the page before "More information about filing disability claims"? Also, are we added both questions from the pension page that discuss "intent to file"?https://www.va.gov/pension/how-to-apply/

**Comment by jenniferlee-dsva** [comment]
@RLHecht - could you make sure to make same "declare" update to disability intent to file, to match Pension intent to file if Peggy changes?

**Comment by Karak888** [comment]
waiting on some wording - waiting for ok on declare to submit.  this can be published today per @jenniferlee-dsva

**Comment by RLHecht** [comment]
Reviewed changes. Moving to validate and will then close.

**Comment by RLHecht** [comment]
Validated on live site.
