### ISSUE TITLE
Update List of External Services Contacts for Support or Incidents

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41808]
#  Description

The current [externals integrations/services ](https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Integrations.640909834.html) list is out of date with contacts and process for responding to issues or service interruptions. 

# Acceptance Criteria

- [  ] Update list of contacts and documentation for issues or service errors.

**Comment by little-oddball** [comment]
Maybe [this](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) can help w/ that. Long term, would be make part of on/off board process, etc. (possible create a ticket for that)

**Comment by alyssagallion** [comment]
The issue outlined has been resolved by having the VFS Product Directly list `https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory`. 

I reached out to Shira to identify if we should create a task on the off-boarding individuals ticket here `https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&projects=&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D`

Closing.

**Comment by rmtolmach** [comment]
@alyssagallion and @little-oddball You're saying if someone leaves who is listed on the [product directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory), removing them should be part of the offboarding checklist?
