### ISSUE TITLE
SOCKS access for Mark Viterna

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#41802]
### Your Name

Mark Viterna

### Your Email

viterna_mark@bah.com

### Your Role and Team

Engineer Lighthouse API

### Product Manager (PM) name and email

Kelly Lein kelly@adhocteam.us

### Product Owner (PO) name and email

Premal Shah premal.shah@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDH8rb/dNWjlD9Bu/WIOQajnv4SotYN6mlUohj0ukLxBhg5iq380COSEMwVy8fNZcSJ9NR4zIESaCSapgwdt3BxOPLLlxdWUCIsdLhf/RSgNH/3aUdhfIkusio7EfLsnJ4YX2B1lnRBpuSp97r0NkgXUJv87i6aQEkN88VdQ3yaOR2Y1CiKnmqKBgcecsEc8+F0jvKnDWTT1Tvc4PNQ93Cj9Nn68j3xWSR5tXfSc7P995WQXuluDR5taDLL2CaU53rNXevu9nwssVdaNX74yf0YAh3Dn8SEi9yxuyHEB50tvleZgiRfMo5f2SXtVap0PTU4atNFZXOAITFfe4zEZPWlNVEBtcKB9FU5+1U603oyajzbnn1BYfbyYiIPfPen2g1D+Jx53pikfizHkeCeJV81SeALuz8qlAFEsaxteQ3u9gLNwL+J0UKLh34MZiE2lb/Ru6QlPtlsFkEa4c7cChORgM+PSlvxWO6WpjLivaMPLdBCG/O+fTpnX85s8i7AEtM= vets-api@osboxes

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
I was unable to locate in VFS Team Roster (also checked Platform Roster just in case), please reach out to your team leadership about starting [platform orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that you can be added to the necessary roster. This is blocking and we are unable to process this request until the requesting user exists in correct location.

**Comment by mviterna** [comment]
Ok. Yeah, I used to be on team Matsumoto. I've asked the platform team if they can put me back on. Stand by and I'll let you know what they say. I'm hoping we don't need to go through the whole VFS onboarding again for our new team.

**Comment by mviterna** [comment]
We need to do the onboarding template first. I'll open a new one when ready
