### ISSUE TITLE
10-10EZ Short Form Analytics: Track Number of Short Form Submissions

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#41825]
How can we track how many short forms are being submitted vs. regular forms?

**Comment by markfallows** [comment]
- When pulling the information for authenticated users, setting a flag.
- For unauthenticated users, looking at disability rating
- Information only being displayed; not being captured on backend
- Can we create an event for when the Short Form Alert is shown?

view:totalDisabilityRating
vaCompensationType = "highDisability"

**Comment by markfallows** [comment]
Spoke with Analytics team on 7/7.  Work resuming on adding necessary analytics components; should be available in time for launch.

Follow up with Analytics team on 7/14.

**Comment by markfallows** [comment]
@hdjustice Can this ticket be closed since we're tracking short form and long form submissions now?

**Comment by hdjustice** [comment]
Yes, this can be closed since we are now at 5% production
