### ISSUE TITLE
Adding Michelle Smith to DSVA Slack

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#41821]
# Description
- Please add michelle.smith@adhocteam.us as a full member, they are the new program manager for the platform spike teams.

**Comment by michelle-d-smith** [comment]
For some reason Slack is forcing me to set up a new account to access this. My current account is member id: U03G7SK1KEV. To join the DSVA slack it is setting up a different account with the same email address and member id: U03H67XF57U. I only want to have the one Slack account. Is it possible to delete U03H67XF57U and assign my access to my Ad Hoc account: U03G7SK1KEV
