### ISSUE TITLE
Access for Mahariel Rosario

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/va.gov-team#4182]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toddle
- Please provide your name.
   > Mahariel Rosario
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: Benefits and Memorials 2
   > Role: Sr Front End Engineer
   > Company: GovernmentCIO

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0trNe2Y6OgVL+UlZK/eqy1XJLg0IGG5TNaCBrw5xbtkorxHMNZuaLr3+Q+Vi2OQk5aqKQWFcpwv66MJctO1hBBdKHNX+ChAakGw76mDm2XCHS+5Yb2GIKhLTA+tDl88sGfHFhEXY7YqkgwjBRUpbu4hYG4LtWRdv1BaMyOrnktSqnLyv2wIpoS5+VwOYdQ+xIMusIx3uQ+nN5T3OLMdAXNmLGo99A1IYPj8gcZceVWX4Aj88TnYVJMJH+pdMWumMI1plV4dNsvuAcxl5jfqPReAOYaYFfNfydcXreZck3dGoC+tNReaPL9DdujCOuOmycXYl38lo0Z/AJ3cujsCY+7HtDswjq1IyJ520eopgtlwRbjCulW8gUHxt2CXRq2M+qqnxbrZufZwzNpjG1+og5dct6dNmZnJMOlUnRuCxP4mLIibl+zfR+TLlP2QxyzaA61+CFbFS0TnQqSFbkJ++tT8wdotu7D0MA+mFKyTeBUy9vV7GKakpd/MAC4XIuMVzyO+pFLPa+0XfpeYoRqCQW3/LmjUbuvACJUQHkhoXScjCRhuufU4r/UcuZIeGlXrokhUwQsZWM37NXxYwZ39au0vMu6uA+TFgzOHVAE3SNmNt893eUXG3ldcWK/xmOuLiEJZ2OSelfIobXe+EXl+AAxZu9jsjmOlisQIwx2T/Bxw== mrosario@governmentcio.com

```

- [Grant AWS Console access?] No
  > YES / NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by mr0sari0** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
> @department-of-veterans-affairs/vsp-operations

Hello @mr0sari0 , for the SSH section above you provided your MAC address, we need your SSH key.

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Mahariel Rosario
COR: Mary O’Toole

**Comment by mr0sari0** [comment]
@ricetj Hi, I just updated the SSH key, taken from my id_rsa.pub. Please let me know if this is the correct key you need.

**Comment by ricetj** [comment]
> @ricetj Hi, I just updated the SSH key, taken from my id_rsa.pub. Please let me know if this is the correct key you need.

Hello @mr0sari0 , thanks for updating and yes that is what we need. Thank you.

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.
