### ISSUE TITLE
[06/02/22] VEText Admin Defining Document

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#41837]
[] Document outlines Admin responsibilities
[] Links to the various features of VEText (eg. how to configure clinics and how that connects with message templates, individual clinics vs. stop codes, appointment reminders..)
[] Pass off to Justin and Lindsay for review
[] Add to SharePoint
[] Include in the newsletter
[] Email out to list of identified Admin

**Comment by lindsay-insco** [comment]
Approved!
