### ISSUE TITLE
Content clarification from Benefits Team 1

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41835]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
On the Claim Status Tool, if you log into user 228 (Colder Polarbear) on staging. The main events listing page will include over 10 entries. When this happens, the listings are paginated. When a new page is selected the focus currently is set to the breadcrumbs

<details><summary>Click pager, focus moved to breadcrumbs</summary>

Note: The React pagination links are not accessible using the <kbd>Tab</kbd> key. I will be fixing that soon.

![focus moves to breadcrumbs after changing pagination page](https://user-images.githubusercontent.com/136959/170259164-f555c32f-1365-4927-adba-47c35eb7d8d0.gif)</details>

After discussing this with @joshkimux, he recommended we follow the pattern used by the facilities locator team, where a block of text is placed above the list, something like "Showing 11 ‒ 20 of 40 events, page 2 of 4". This pagination detail will then be focused after the page is changed by the pagination web component.

<details><summary>Page info block focused after page change</summary>

<img width="557" alt="'Showing 11 through 20 of 40 events, page 2 of 4' block is highlighted after changing pages" src="https://user-images.githubusercontent.com/136959/170262698-d0ba2ec1-a029-4bbb-b46d-5feba528f128.png">
</details>

What we need is clarification on the wording, "Showing 11 ‒ 20 of 40 events, page 2 of 4". The facilities locator page shows this without the "page 2 of 4" part. Josh recommended we consult Angela Fowler regarding the use of the en-dash versus actual words, because of how screenreaders would read that sentence.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*

At your convienence
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [The numbers page, exception section recommends using "to" and numbers in ranges](https://design.va.gov/content-style-guide/numbers#exceptions), e.g. "Choose from 1 of 5 VA-backed loan options." 
- [The Punctuation page, dashes section recommends using an en-dash for ranges](https://design.va.gov/content-style-guide/punctuation#em-and-en-dashes-hyphens), e.g. "9:00 a.m. ‒ 5:30 p.m. CT"
- [VA.gov search example](https://staging.va.gov/search/?page=1&query=veteran), e.g. Showing 1-10 of 999 results for "**veteran**"
- [Find VA locations in Washington, D.C.](https://www.va.gov/find-locations/?page=1&address=20005&facilityType=health&serviceType&latitude=38.909495&longitude=-77.028988&radius=10&bounds%5B%5D=-77.778988&bounds%5B%5D=38.159495&bounds%5B%5D=-76.278988&bounds%5B%5D=39.659495&context=Washington%2C%20District%20of%20Columbia%2020005%2C%20United%20States), e.g. Showing 1 - 10 of 19 results for "VA health", "All VA health services" near "Washington, District of Columbia 20005"
---

- Link to product outline: Sitewide level determination
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: N/A
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits-Team-1
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Pamela Hastings
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by Mottie** [comment]
I couldn't log into 228 either, using both ID.me and Login.gov. I tried user 189 and it worked.

**Comment by katherine-fung** [comment]
Hi @Mottie, after discussing with the content team and Josh, we're recommending that you follow this format:

"Showing 11-20 of 40 claims or appeals" 

The dash is a hyphen. We spoke to Josh, who said that the page number shouldn't immediately follow the number of displayed search results. The page numbers for navigation should go at the bottom of the results, and use "aria-current" to help people navigate. 

Let me know if you have any questions about this. Thanks!

**Comment by joshkimux** [comment]
Thank you @katherine-fung ! Also small note for @Mottie I should have added, `aria-current="page"` already exists in the design system component 😄
