### ISSUE TITLE
www.va.gov certificate renewal - Jan 2020

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#4183]
## User Story or Problem Statement

The SSL certificate for www.va.gov is coming up for renewal. Need to follow the usual [procedure](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md) for replacing this certificate so it does not expire.

## Goal
Replace SSL certificate with one that's valid.

## Objectives or Key Results this is meant to further
- Keep the site up

## Acceptance Criteria
- [ ] New SSL certificate should be on our infra, TIC, and EWIS nodes

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
@ricetj is there an epic that this should be slotted under. Basically "keep the site up" 🙃

**Comment by wyattwalter** [comment]
Gonna roll through this with Bennie.

I opened INC8799214 for the replacement at the Gateway.

**Comment by wyattwalter** [comment]
We got the internal cert updated on ALB/revproxy. Got the cert sent over to Gateway Ops and CRRC networking teams. Scheduled some time for tomorrow morning to do the install.

11:00 Eastern for internal cert update
1:00 Eastern for external cert update

**Comment by benniemosher** [comment]
This has been completed and confirmed with IT.
