### ISSUE TITLE
Investigate E2E failures caused by authentication issues

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#41838]
Multiple E2E tests have been failing in CI due to issues with an authentication endpoint. This task is to determine the root cause of these failures and implement a fix.

**Comment by pjhill** [comment]
@ddzz -- When you get a chance would you please add some details to the ticket and estimate the complexity of the effort to analyze, describe, and fix this issue?

**Comment by ddzz** [comment]
These failures were caused by the `eauth.va.gov/keepalive` endpoint causing [this domain error](https://github.com/cypress-io/cypress/issues/4220). This endpoint was not mocked out properly, causing the domain issue. The PR mentioned in this ticket fixed this mocking issue.

**Comment by pjhill** [comment]
Hooray, thanks for working through this!
