### ISSUE TITLE
508 findings - pre-launch 508 review for VAMC Facility Web Templates (Pittsburgh Pilot)

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#4184]
VAMC Facility Web Templates (Pittsburgh Pilot) 

This is the new site template for VA Medical Systems and their respective facility locations.

This includes all public-facing content pages and no login is required. The 508 testing should cover the URL below and all its subpages. 

https://www.va.gov/pittsburgh-health-care/

_Additional URLs_
- https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

- https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

- https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

- https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

- https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic/

- https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic/

- https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic/

**Comment by jenstrickland** [comment]
As this is site templates, this is not part of the VSA VAMC upgrades work.

**Comment by 1Copenut** [comment]
VSP is picking this up and will be full speed ahead on the work VSA started.

**Comment by 1Copenut** [comment]
@andreahewitt-odd Heads up that this has been identified as a VSP responsibility. I'm full speed ahead and moving on the audit now as my number one priority unless I hear different.

**Comment by 1Copenut** [comment]
Closing this epic. @mmiddaugh created #5723 for the template audit VSP is running. All issues have been migrated to that epic.
