### ISSUE TITLE
[Design] Develop SMS Messaging for Check-in to Appointment where eCheckIn is not Enabled

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41861]
## User Story
As a Veteran, when I attempt to Check-in for an appointment at a facility where eCheckin is not enabled, I would like to see a message that explains that to me so that I am not confused thinking that I don't have an appointment at the facility.

## Background
[Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653499137753019)

## Tasks
- Develop a message to return to the Veteran via SMS when they text "check in" but their appointment for the current day is at a facility where eCheckIn is not enabled

**Comment by loripusey** [comment]
@niradatta1 @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Saving this message too for reference - https://dsva.slack.com/archives/C02UP02HHGX/p1653500818155919?thread_ts=1653488587.597109&cid=C02UP02HHGX

Current error messages for CHIP/VeText that adrian mentioned are here - https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/8AD30A0A-3193-4B09-9616-70C9F1AC8A61/canvas
