### ISSUE TITLE
Evaluate website performance monitoring tools 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#4187]
# Overview

- website performance is not measured or monitored on va.gov 

# Goals 

- Evaluate third party performance measuring tools 
- Determine process for measuring and reviewing impact of website performance (see [related](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2858))

# Potential tasks  

- Review third party offerings 
- Determine constraints for using SaaS products for code review 
- Create a plan for running a few options through a trial 
- Determine rollout plan 

# Code quality tools to evaluate 
https://speedcurve.com/pricing/
https://www.datadoghq.com/rum/

**Comment by rianfowler** [comment]
**Create overview**
- product types (product agnostic) 
  - RUM 
  - Synthetic 
- How do product types overlap with existing tooling like GA? 
- High level of how each product type could be implemented as part of our CI 
  - How would the build process change?
  - Are there any third party scripts that need to be added to the site? 
- Summary of offerings
  - type of product offered 
  - first year, on going price (estimated according to site) 
  - any pertinent notes (unique offering) 
- integration effort 
  - approvals needed 

**Prototyping**
- Identify / engage some stakeholders 
  - apps teams PMs 
  - apps teams FE 
  - DEPO
  - platform PMs 
  - platform FE
- pick 2 vendors and prototype integration / evaluate demo 

**Pick vendor**
- get quotes 
- get necessary approvals

**Comment by jhonnyoddball** [comment]
### **Google Analytics - Web Performance**

The only information related with web performance monitoring inside GA is located at:
Reports -> Behavior -> Site Speed

Average loading times are important metrics.

![GA Avg Page Load](https://user-images.githubusercontent.com/55560129/71014508-06e98b80-20c0-11ea-94c1-69a4b16e49eb.png)

**Comment by jhonnyoddball** [comment]
### **Prometheus - Web Performance Monitoring**

it does not provide any real and liable data to be used for performance metrics

**Comment by jhonnyoddball** [comment]
### **Web Performance Monitoring Tools**

**Synthetic Monitoring** - The site receives a check once a minute or so 
**RUM** - Receives the data directly from the site because the script runs on the page.


| Monitoring Tool | RUM | Synthetic | Price | Score |
| :--- | :---: | :---: | :--- | :---: |
| [Akamai - mPulse](https://www.akamai.com/us/en/products/performance/mpulse-real-user-monitoring.jsp) | X |   | ? | 1 |
| [DotCom-Monitor](https://www.dotcom-monitor.com/website-speed-monitoring/) | X | X | Confusing | 1 |
| [Uptrends](https://www.uptrends.com/products/web-performance-monitoring) | X | X | Varies, $50 p/m + RUM usage | 2 |
| [DareBoost](https://www.dareboost.com/en) |   | X | $356 p/m | 3 |
| [RayGun](https://raygun.com/) | X |   | $649 p/m | 1 |
| [Rigor](https://rigor.com/) |   | X | ? | 2 |
| [DataDog](https://www.datadoghq.com) | X | X | ? | 4 |
| [SpeedCurve](https://speedcurve.com/) | X | X | $1,500 p/m | 5 |

**Comment by jhonnyoddball** [comment]
### **AKAMAI - MPULSE**

https://www.akamai.com/us/en/products/performance/mpulse-real-user-monitoring.jsp
https://developer.akamai.com/akamai-mpulse-real-user-monitoring-solution

- Mainly a RUM solution
- Most information can be found in GA
- Act on Problematic Resources
- Provide alerts

**PRICE**: Upon request
**DEMO**: Upon request. 
**SCORE**: 1

**Comment by jhonnyoddball** [comment]
### **DOTCOM-MONITOR**

https://www.dotcom-monitor.com/website-speed-monitoring/

- Mostly RUM with a little of Synthetic
- Detailed waterfall charts show root cause of issues.
- Video playback and screenshots of errors.
- Historical & real-time element reporting.
- Provide alerts

**PRICE**: Confusing (https://www.dotcom-monitor.com/pricing/)
**DEMO**: Upon request. 
**SCORE**: 1

**Comment by jhonnyoddball** [comment]
### **UPTRENDS**

https://www.uptrends.com/products/web-performance-monitoring

- Includes RUM and Synthetic
- Get alerted on website speed, the total number of bytes, or missing content
- Third party monitoring
- Provide alerts

**PRICE**: Varies, $50 p/m + RUM usage  (https://www.uptrends.com/pricing)
**DEMO**: Upon request. 
**SCORE**: 2

**Comment by jhonnyoddball** [comment]
### **DAREBOOST**

https://www.dareboost.com/en

- Website Speed Test
- Installation-free (only Synthetic)
- HTML, images, JavaScript, CSS analysis
- Tool provides solutions, ordered by priority
- Comparison feature
- Performance budget tool
- Custom alerts
- User Journey - Allows you to replicate any user navigation scenario

**PRICE**: $356 p/m (https://www.dareboost.com/en/offers#ifbefs_nfov)
**DEMO**: Upon request. 
Free Report (https://www.dareboost.com/en/report/a_15df7939f90b9981b244f29ce)
**SCORE**: 3

**Comment by jhonnyoddball** [comment]
### **RAYGUN**

https://raygun.com/

- Real User Monitoring in minutes using a lightweight library
- Automatically identify front-end performance issues causing slow and frustrating load times.
- Mobile app performance

**PRICE**: $649 p/m (https://raygun.com/platform/real-user-monitoring#rum-business)
**DEMO**: Upon request. 
**SCORE**: 1

**Comment by jhonnyoddball** [comment]
### **RIGOR**

https://rigor.com/

- Synthetic monitoring with an intelligent optimization engine
- Integrate Performance Management Throughout the DevOps Lifecycle
- Seamless Integration with Your Favorite Real User Monitoring (RUM) Solution
- Test Performance in Your Jenkins Build with the New Rigor Optimization Plugin

**PRICE**: No pricing. Only after trial.
**DEMO**: Upon request. 
**SCORE**: 2

**Comment by jhonnyoddball** [comment]
### **DATADOG**

https://www.datadoghq.com

**RUM** (https://www.datadoghq.com/rum/)

- Visualize load times, frontend errors, and page dependencies
- Correlate business and application metrics
- Troubleshoot quickly with app, infrastructure, and business metrics in a single dashboard
- Uncover an incident's root cause with full-stack context

**Synthetic** (https://www.datadoghq.com/synthetics/)

- Validate HTTP requests to your services from several locations
- Out-of-the-box integration with APM, infrastructure, and logs
- Waterfall visualization of each step with screenshots of end-user view
- Breakdown of performance by selected locations and devices
- Fast root cause analysis 
- Record user actions via a GUI-based Web Recorder
- Powerful validations with use of flexible assertions and variables
- Empower non-technical teams to create browser tests
- See metrics, traces, and logs in the context of test runs
- Visualize uptime data alongside key business metrics
- Latency display of DNS, SSL, TTFB, and more.
- Real-time alerting with rich context

Integration, dashboard, alerts, log management, network, monitoring, and API are features but sold separately.

**PRICE**: Varies based on product bundle (https://www.datadoghq.com/pricing/)
**DEMO**: Upon request. 
**SCORE**: 4

**Comment by jhonnyoddball** [comment]
### **SPEEDCURVE**

It is by far the most complete of all. It has both RUM and synthetic monitoring.  It has most of all competitor's features and more.

**RUM** (https://speedcurve.com/features/lux/)

- A lot of metrics
- Page Details
- Navigation timing
- Paint timing
- CPU time
- User timing
- Page design
- Interaction Metrics
- Customer Data
- Javascript Errors

Data collected by RUM:
https://support.speedcurve.com/en/articles/1707704-what-data-is-collected-by-lux-for-rum

Metric representation:
https://support.speedcurve.com/en/articles/74078-what-do-the-different-speedcurve-metrics-represent

**Synthetics** (https://speedcurve.com/features/synthetic/)

monitoring is built on top of WebPageTest,

- Track dozens of metrics, including custom metrics
- Create performance budgets and get alerts
- Diagnose performance issues at the page level (Provided with Google's Lighthouse & PageSpeed Insights audits, there is a list of performance rules, stacked and color-coded in their order of importance.)
- Analyze the performance impact of ads and third parties

**PRICE**: $18,000 per year for RUM and Synthetic (https://speedcurve.com/pricing/)
**DEMO**: Demo available
**SCORE**: 5

**Comment by jhonnyoddball** [comment]
### **SpeedCurve - Performance Budget**

![Screen Shot 2020-01-07 at 10 19 09 AM](https://user-images.githubusercontent.com/55560129/71905985-3cb9e700-3137-11ea-8ff5-03c1ea75d798.png)

Allows you to set a specific metric budget only per chart. there are about 50 different metrics

### Settings:

![Screen Shot 2020-01-07 at 10 21 40 AM](https://user-images.githubusercontent.com/55560129/71906274-beaa1000-3137-11ea-8ac7-2a9d76429c82.png)

### Chart:

![Screen Shot 2020-01-07 at 10 22 20 AM](https://user-images.githubusercontent.com/55560129/71906294-c669b480-3137-11ea-8be3-30ace23706db.png)

**Comment by jhonnyoddball** [comment]
### **SpeedCurve - Synthetic**

![Screen Shot 2020-01-06 at 11 16 10 AM](https://user-images.githubusercontent.com/55560129/71907906-02eadf80-313b-11ea-815e-460ab45fc53d.png)

It doesn't allow you to edit any metric on the dashboard

**Comment by jhonnyoddball** [comment]
### **PERFORMANCE METRICS**

[Recommended metrics from USWDS](https://designsystem.digital.gov/performance/glossary/#types-of-metrics)

This should be the main metrics you should focus on for Web Performance. `SpeedCurve` has all of them.

- **Speed Index**: it’s the average time at which visible parts of the page are displayed. It can only be used in a simulated environment
   - WebPageTest
   - SpeedCurve
- **First Meaningful Paint**: It’s the biggest above-the-fold layout change has happened, and web fonts have loaded
   - LightHouse
   - Chrome DevTools
   - SpeedCurve
- **First Contentful Paint:** It's the time at which users can start consuming page content.
   - SpeedCurve
- **Time to Interactive**: It measures how long it takes a page to become interactive
   - LightHouse
   - Chrome DevTools
   - SpeedCurve
- **Input Latency**: Only available in RUM. It’s the amount of time it takes for the app to respond to the users as they interact with it. 
   - LightHouse
- **Start Render**: It’s measured as the time from the start of the initial navigation until the first non-white content is painted to the browser display
   - WebPageTest
   - SpeedCurve
- **Backend Time or TTFB**: The time from the start of the initial navigation until the first byte of the base HTML page is received by the browser
   - SpeedCurve
- **Number of requests**
   - LightHouse
   - SpeedCurve
- **Total Size**
   - LightHouse
   - SpeedCurve

Most of the above metrics can be found in SpeedCurve under `Synthetic > Site`. However, FCP and FMP can only be found in a custom Dashboard or in the cascade chart.

SpeedCurve reply:

> “You can find First Contentful Paint and First Meaningful Paint when you drill down into your Synthetic test results. You can also create custom charts that track FCP (in LUX and Synthetic) and FMP (Synthetic only) in your Favorites dashboards, as well as create performance budgets and alerts for them.”

**Comment by jhonnyoddball** [comment]
### **PERFORMANCE METRICS**

[Recommended metrics from USWDS](https://designsystem.digital.gov/performance/glossary/#types-of-metrics)

This should be the main metrics you should focus on for Web Performance. `SpeedCurve` has all of them.

- **Speed Index**: it’s the average time at which visible parts of the page are displayed. It can only be used in a simulated environment
   - WebPageTest
   - SpeedCurve
- **First Meaningful Paint**: It’s the biggest above-the-fold layout change has happened, and web fonts have loaded
   - LightHouse
   - Chrome DevTools
   - SpeedCurve
- **First Contentful Paint:** It's the time at which users can start consuming page content.
   - SpeedCurve
- **Time to Interactive**: It measures how long it takes a page to become interactive
   - LightHouse
   - Chrome DevTools
   - SpeedCurve
- **Input Latency**: Only available in RUM. It’s the amount of time it takes for the app to respond to the users as they interact with it. 
   - LightHouse
- **Start Render**: It’s measured as the time from the start of the initial navigation until the first non-white content is painted to the browser display
   - WebPageTest
   - SpeedCurve
- **Backend Time or TTFB**: The time from the start of the initial navigation until the first byte of the base HTML page is received by the browser
   - SpeedCurve
- **Number of requests**
   - LightHouse
   - SpeedCurve
- **Total Size**
   - LightHouse
   - SpeedCurve

Most of the above metrics can be found in SpeedCurve under `Synthetic > Site`. However, FCP and FMP can only be found in a custom Dashboard or in the cascade chart.

SpeedCurve reply:

> “You can find First Contentful Paint and First Meaningful Paint when you drill down into your Synthetic test results. You can also create custom charts that track FCP (in LUX and Synthetic) and FMP (Synthetic only) in your Favorites dashboards, as well as create performance budgets and alerts for them.”

**Comment by jhonnyoddball** [comment]
### SpeedCurve - Metrics test

### Parameters

![Screen Shot 2020-01-13 at 10 10 03 AM](https://user-images.githubusercontent.com/55560129/72268173-56ec3d00-35ef-11ea-8b6c-48fbf4876c6e.png)

**Comment by brandonrapp** [comment]
What would do we think will be useful for VSP and VFS teams?

**Comment by brandonrapp** [comment]
What decisions do you think we can make using the data from speedcurve?

**Comment by jhonnyoddball** [comment]
### SpeedCurve - Github authentication

Their response:

> Hi there! We don't offer GitHub authentication at the moment, but we do support other forms of SSO including SAML, ADFS, and Google G Suite.

**Comment by jhonnyoddball** [comment]
### SpeedCurve - Usefulness 

> What would do we think will be useful for VSP and VFS teams?

- All metrics available
- Dashboards per team(s)
- Performance budget
- Snapshots in time (deploy)
- Custom metrics
- Slack integration
