### ISSUE TITLE
Add GFE configuration instructions to steps (i.e. how to get admin permission to install everything)

### ISSUE THREAD

**Issue by froehlichcr** [department-of-veterans-affairs/va.gov-team#41871]
### Description

Many GFE's do not have an out of the box developer experience OR admin permission to setup a developer experience. Among the required tools for developers using Windows GFE:

- Node
- NVM
- WSL2 & Ubuntu
- VS Code
- Github Desktop & Git CLI
- Powershell
- Docker
- ...many more

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html
https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-up-your-local-frontend-environment.1844215878.html
https://github.com/department-of-veterans-affairs/vets-api#base-setup

## Expected Results

Developers should have clear instructions on how to configure their GFE:
- whom to contact for support
- documentation for all supported operating systems
- complete list of tools (with version numbers if relevant), location and purpose (e.g. NodeJs, v14.15.0, `nvm`, platform development)
- process for getting admin access to install all these tools

## Follow Up

- Once the documentation of the above is complete, update the onboarding instructions for managers in order that GFE can be adequately prepped ahead of time for new engineering persons.

**Comment by vbellissimo** [comment]
Closing this ticket, categorizing as OBE.
