### ISSUE TITLE
Create a common slide deck layout for use across all product support presentations

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#419]
## User Story
As a platform support team member, I need common slide deck layout so I can create professional, consistent presentations.

## Goal
The goal is to create a common layout, as well as a common tool, for presentations.

## Acceptance Criteria
- [x] Collaborate with other VSP team members, in particular design and product, to arrive at a common layout
- [x] Collaborate with other VSP team members, in particular product and design, to arrive at a common tool for presentations (i.e. Google Slides, etc.)
- [x] Choose a home for where the "template" layout will live, and how it can be consistently shared moving forward
- [x] Communicate all deliverables to the rest of the product support team

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by hpjaj** [comment]
@smoonpeyes created a fantastic Google slides template that we can use here:

https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit?usp=sharing

**Comment by hpjaj** [comment]
@smoonpeyes - Once @accbjt establishes a common Google Drive folder for our team, if I haven't already done so, can you pls create a "template like" slide deck from your design, and drop it in that folder.

**Comment by smoonpeyes** [comment]
The template has been moved here: https://docs.google.com/presentation/d/1bVP_bLKHmpPA7WvDaEWyzdjjsZeZzU05TCbPJkMdAGo/edit?usp=sharing

@accbjt @hpjaj I think someone will have to add it as a Google Slides template on the Oddball Google drive. (I don't have access to do this.)

**Comment by hpjaj** [comment]
I'll move it 👍

**Comment by hpjaj** [comment]
I can work on this.  @smoonpeyes I might ping you if I need a hand.

**Comment by hpjaj** [comment]
Done!
