### ISSUE TITLE
CANCELED**Terminate session on change in device/browser fingerprint

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#41907]
# Description
In order to prevent potential token theft, we should terminate the user session if we notice a change in device or browser fingerprint.  In order to accomplish this, we should issue a device cookie upon successful authentication.  If that cookie is missing or invalid on refresh, all sessions related to the original refresh token should be invalidated and the user should be forced to log in again.  

# Acceptance Criteria
- [ ] On authentication, issue device cookie
- [ ] If cookie is missing or invalid when a refresh token is issued, all tokens are invalidated and the user has to sign-in again

**Comment by joeniquette** [comment]
@nsoutouras can you please add this to a "phase 4" sign in service epic

**Comment by joeniquette** [comment]
Waiting on permission to do this. Data is being captured as speak.

**Comment by kingbmike** [comment]
@bosawt is this ticket still relevant?  If not, I can close otherwise I will move it to the overall SiS epic as the 'tech debt' epic for SiS is going away.

**Comment by bosawt** [comment]
We eventually want something like this as part of fraud mitigation, but we still need an investigation the device/browser fingerprint
