### ISSUE TITLE
GIBCT: Clicking one of the autocomplete results does not refine a search

### ISSUE THREAD

**Issue by ksantiagomorgan6** [department-of-veterans-affairs/va.gov-team#4190]
@delli-gatti-michael commented on [Thu Dec 12 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20078)

After searching for schools in the Comparison tool, a user has the option to refine their results using a keyword.  When a user partially enters the name of a school or program, a drop-down appears with several valid options. A user should be able to click one of these options rather than typing it out completely. Currently, clicking one of the results will run a search using the partial name typed into the search bar. This applies to both regular and VET TEC search results.

1. Access https://staging.va.gov/gi-bill-comparison-tool/
2. Search for any school
3. On the search results screen Clear the keywords field and type "co"
- Several school names are displayed in the autocomplete drop-down
4. Select any option from the autocomplete drop-down
- The search is re-run using "co" rather than the selected option

![Screen Shot 2019-12-12 at 10.08.06 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/cb0fcf61-c4bc-490c-98bf-6ab85c3083fb)

**Comment by ksantiagomorgan6** [comment]
Pull request

https://github.com/department-of-veterans-affairs/vets-website/pull/11322

**Comment by delli-gatti-michael** [comment]
This fix is now live in master. Closing this issue
