### ISSUE TITLE
IE11 Deprecation Banner content request from Public Websites

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#41914]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

Per the [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/ie11-deprecation-banner/product-outline.md), we are creating a banner to alert IE11 users that they should switch browsers. We are working on the placement of the alert, but want to engage with you about the content of the alert. 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes – it will be conditionally displayed to IE11 users, <1% of all traffic.
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*

Mid-June
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/ie11-deprecation-banner/product-outline.md
- Link to or attach user flows:
- Link to prototype or mockups: 
![image](https://user-images.githubusercontent.com/4054752/170375779-1c31440f-3256-4ee3-b71f-18162b03b126.png)

- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: mid-June
- Estimated staging review date: mid-June
- Content and IA work needed by: early June

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Wes Rowe
-	Designer: Aslan French
-	FE engineer: Claudio Nunez Jr
-	Product/team Slack channel: sitewide-public-websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@wesrowe We are working on this this sprint and should have content for you the earlier part of next week. If that changes for some reason I will keep you posted.

**Comment by wesrowe** [comment]
@laurwill, thanks for sharing the draft for discussion.

- The 2nd-person language "You'll need to..." of option #2 seems advantageous for getting the user's attention. I'm afraid option #1's headline will seem like a generic update, not a message that was chosen for the particular visitor based on something they can control. 
- I wonder if we want to give some context in the message like "It appears that you are using the Internet Explorer browser." (Or "We detected...") We heard in the Design Intent meeting that many visitors don't really grasp what a browser is, or they lack awareness of their browser type. 
- Lastly, the idea of a browser "retiring" (anthropomorphism) feels a little strange to me in this context, but take with a grain of salt since I'm not familiar with VA.gov's editorial voice or style.

**Comment by laurwill** [comment]
Hello @wesrowe , thanks for this feedback! We reworked Option 2 to make it clear that the visitor is currently using IE and to try an alternative to "retiring." Here's the updated language:

**You'll need to use a different web browser soon**
You're using Internet Explorer 11 right now to access [VA.gov](http://va.gov/). Microsoft will stop supporting that browser on June 15, 2022. This means that you'll need to switch to one of these other browsers soon: Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

After June 15, change to:
**You'll need to use a different web browser**
You're using Internet Explorer 11 right now to access [VA.gov](http://va.gov/). Microsoft stopped supporting that browser on June 15, 2022. This means that you'll need to switch to one of these other browsers: Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

**Comment by wesrowe** [comment]
@jcklpe @jilladams @fmccaf1 @davidconlon, please share your thoughts on the draft language in the comment above.

**Comment by jcklpe** [comment]
Looks good to me!

**Comment by jilladams** [comment]
Newb, so this may violate rules of the road, but if possible to link to those browsers online for download, that would be a step-saver. Otherwise, language looks good to me!

URLs, if that's doable:
https://www.microsoft.com/en-us/edge
https://www.google.com/chrome/downloads/
https://www.mozilla.org/en-US/firefox/new/
https://www.apple.com/safari/

**Comment by bethpottsVADEPO** [comment]
@jilladams I'm not sure we want to add links as that may send the message that we're endorsing these browsers over others. @davidconlon what do you think?

@laurwill and I were also chatting about changing this line to the following so we're not implying that these are the only choices (which would also feel like an endorsement):
This means that you'll need to switch to another browser, like Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

So here's the whole text, with this revision:
**You'll need to use a different web browser soon**
You're using Internet Explorer 11 right now to access [VA.gov](http://va.gov/). Microsoft will stop supporting that browser on June 15, 2022. This means that you'll need to switch to another browser soon, like Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

After June 15, change to:
**You'll need to use a different web browser**
You're using Internet Explorer 11 right now to access [VA.gov](http://va.gov/). Microsoft stopped supporting that browser on June 15, 2022. This means that you'll need to switch to another browser, like Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

**Comment by jilladams** [comment]
@bethpottsVADEPO Dave agreed with you verbally in our refinement meeting just now re: links, so all good to leave them out on that front.

**Comment by jilladams** [comment]
@bethpottsVADEPO @laurwill 2 questions re: implementation (on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9075), for @kind-claudio : 

1. The code we've written will sniff for Internet Explorer, including 9 & 10, since some users may still be using an older version of IE. In this case, some users on 9 & 10 will encounter the IE11 language. This is a tiny percentage of users, and we'd like to use the provided language that specifies IE11 / retirement date, but want to confirm with you all if you have any edits based on that.
2. Should [VA.gov](http://va.gov/) be a clickable link?  It's clickable in the GH comment, but just want to confirm that should be interactive in our alert as well.

**Comment by bethpottsVADEPO** [comment]
@jilladams If Microsoft will stop supporting all versions of IE and we'll be showing this message for users of IE9 and IE10 (wow! people are still using those??), then we should remove "11"--thanks for bringing that up!

And VA.gov should not be a link. Many thanks for all the questions.

**Comment by kind-claudio** [comment]
@bethpottsVADEPO If we just remove the "11" in "IE11", the following sentence doesn't quite make sense - "Microsoft stopped supporting that browser on June 15, 2022."
^ this sentence is referring to IE11, specifically.

I feel the whole thing may need a rewrite so that all the wording is cohesive. Please advise w/ exact final copy ("quoted"), so that I'm 100% clear on what I'm updating the copy to.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO - Aliyah and I took a look at this, and tweaked the messages to address "all versions" of IE. Here's the text: 

**You'll need to use a different web browser soon**
You're using Internet Explorer right now to access VA.gov. Microsoft will stop supporting all versions of this browser on June 15, 2022. This means that you'll need to switch to another browser soon, like Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

After June 15, change to:
**You'll need to use a different web browser**
You're using Internet Explorer right now to access VA.gov. Microsoft stopped supporting all versions of this browser on June 15, 2022. This means that you'll need to switch to another browser, like Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thanks for handling since @laurwill is out!

**Comment by wesrowe** [comment]
Yes. Thank you.
