### ISSUE TITLE
Publish Human Readable List for VFS Team Use

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41915]
## Issue Description
In order to support the use case of VFS teams that need to update their product list entries, there needs to be a page where they can come and see their complete product list entry. This page should contain the following:

1. Orienting text for VFS team members, based on [the text and formatting on this page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2220556289/User+Research+Product+List)
2. A complete table of the product list

**Additional Feature:** Output of the page is automated to occur when the JSON file is updated

## Acceptance Criteria
- [x] Having the opening portion of the page properly formatted
- [x] The table comes through with the appropriate columns
- [x] The automation works as intended

**Comment by rsmithadhoc** [comment]
https://github.com/department-of-veterans-affairs/product-directory/pull/286 is out for review to wrap up this.

Slight modification to where the red text is and the verbiage. This was done so we can keep a standard disclaimer and apply it to every page without any additional effort needed.
![image.png](https://images.zenhubusercontent.com/62222b1c8a8a2d232882a99b/146e4ef8-52cc-48b0-9c5e-62b5276a011b)

**Comment by rsmithadhoc** [comment]
https://github.com/department-of-veterans-affairs/product-directory/pull/286 is ready for review.

**Comment by rsmithadhoc** [comment]
The change was merged in.

**Comment by pjhill** [comment]
This is great! Thanks for finishing this (forever ago).
