### ISSUE TITLE
Design intent [Public Websites - IE11 Deprecation Banner]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#41913]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [x] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/ie11-deprecation-banner/product-outline.md)
 
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes
![image](https://user-images.githubusercontent.com/4054752/170373481-75b3c81d-e9b9-4019-8ec1-32843f4aa28c.png)

- [ ] User flow
- [ ] Research Plan
- [ ] Any other artifacts you have so far

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by allison0034** [comment]
Hi @wesrowe confirming this for Tuesday May 31, 2022 at 11am ET. : )

**Comment by claytonzook** [comment]
@wesrowe I'd like to confirm 
1. Is there was any prior research on this? 
2. Is the team planning on doing any before Staging?

**Comment by allison0034** [comment]
No design feedback. Thank you for the thorough explanation.

**Comment by allison0034** [comment]
[Zoom recording](https://oddball-io.zoom.us/rec/share/QwUk7WcI-4gb5g6Sg8pxXZqKDwkQSWQbvKFPcyYmpj7b8F7TUzeRQLqqJuzCdLxl.2YljtjOxPjeM57AW)
Passcode: 4k^Ifw4f

**Comment by jimuhh** [comment]
No IA feedback. Thanks for addressing all my questions so carefully.

**Comment by CherylEvans** [comment]
No Content FB at this time.

**Comment by wesrowe** [comment]
> @wesrowe I'd like to confirm
> 
>     1. Is there was any prior research on this?
> 
>     2. Is the team planning on doing any before Staging?

There was no research performed, to my knowledge. There isn't a plan to do research prior to Staging.
