### ISSUE TITLE
Build Data Studio data QA dashboard from GA data

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41933]
## Issue Description
Build Data Studio data QA dashboard from GA data if work from [Document Dashboard Data QA Processes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41932) determines it is worth doing.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnny-jesensky-adhoc** [comment]
We are no currently supporting Data Studio, (now referred to as Looker), closing this _out_.
