### ISSUE TITLE
console-api Argo SuperUser Integration

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#41944]
## Description
As a workaround until the live Keycloak + Argo (without Dex) Integration is completed, we need a way to make Argo API calls. In order to get a valid access token, we will need to use a username/password as the authentication method. Ideally, once the Keycloak + Argo, we will use the access_token from keycloak to authenticate to Argo, but until then we need a working implementation.

## API docs
https://cd.apps.argoproj.io/swagger-ui#operation/SessionService_Create
https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/

[Related ticket](https://github.com/orgs/department-of-veterans-affairs/projects/547/views/1?filterQuery=argo)

## Acceptance Criteria
- [ ] Super user integration is used as Argo authentication method to make API calls

**Comment by npeterson54** [comment]
Duplicate ticket
