### ISSUE TITLE
Create UX for 10-10EZ short form edit current compensation on review page

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#41945]

**Comment by Dene-human** [comment]
Notes from FE research:

We can include a link to the page within the review expand

![image (2).png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/aebc702d-2b80-4661-9137-62ada17f5aa4)

**Comment by Dene-human** [comment]
Design ([Sketch](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/DPOeZ3W#Comment))

**Comment by Dene-human** [comment]
FE ticker #41988

**Comment by Dene-human** [comment]
@markfallows Do you need to see this for the sprint report? Just making sure you know about it before I close it

**Comment by markfallows** [comment]
Thanks for letting me know!
