### ISSUE TITLE
[Research] [Design] Audit all Content, Messages, & SMS Texts for Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41959]
## Problem Statement
As a team, we would like to do an audit of all of the content, messaging, and SMS texts that are used for the Pre-Check-in application so that we can determine what changes are needed, if any.

## Tasks
- [ ] Review all content, messaging, & SMS texts
   - Specifically look at these items
        - Re-imagining the "too late" messaging to reduce confusion (see [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/telephone/research-findings.md#14-the-too-late-message-confused-many-veterans))
        - As a Veteran, I would like to know when I can Pre-Check-in until so that I will know how long I have to do it.
- [ ] Make recommendations for changes

**Comment by niradatta1** [comment]
Audit completed here: https://docs.google.com/spreadsheets/d/1Z_W57lCBcbFcTCwHkPcg_Ep5emfdm9ywSkyY-i47Nis/edit?pli=1#gid=0

Next steps: Meet with UX and product  to align on prioritization, and create high-priority tickets.
