### ISSUE TITLE
AWS access for lighthouse-developers

### ISSUE THREAD

**Issue by evelez-va** [department-of-veterans-affairs/va.gov-team#41969]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Edison Velez Martinez

### Your Email

edison.velezmartinez@va.gov

### Your Team, Role, and Company

Lighthouse Leeroy-Jenkles, DevOps, Booz Allen Hamilton (formerly Liberty IT Solutions)

### Product Manager (PM) name and email

Mark Rioux, mark.rioux@va.gov

### Product Owner (PO) name and email

James Costa, james.costa@va.gov

### Desired AWS Access

The access requested here is for the `lighthouse-developers` group.

The permissions for lighthouse-developers covers most of what we need to manage our infrastructure within DSVA. However, we noticed there are some permission not listed that we might need to have added. Specifically for scaling of our ECS services and ES domains.

Context behind the need for these:
**ECS**

- We've had situations before where we have had to manually update the scaling policy of some of our ECS services like api-gateway during troubleshooting sessions either to handle an unexpected load, or to force the service to redeploy.
- These tend to/can happen during off business hours, where getting additional support might prove to be difficult, and we would like to be able to remediate the situation ASAP and then capture any changes.

Estimated permissions needed:
```
      "application-autoscaling:RegisterScalableTarget",
      "application-autoscaling:PutScheduledAction",
      "application-autoscaling:PutScalingPolicy"
```
**ES**

- On sort of the similar track, we've had moments where the increase in requests have generated more logs than we anticipated and filled up the ES domain storage. In order to immediately remediate this, we've had to scale up the nodes to get more storage and alleviate JVM pressure.

Estimated permissions needed:
```
      "es:UpdateDomainConfig"
```

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
Approval needed: @department-of-veterans-affairs/operations-aws-approvers

### Additional context: 
These are the current policy attachments for `lighthouse-developers` (From [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf#L2561)):
```
    "lighthouse-developers" = {
      path = "/"
      policy_attachments = [
        aws_iam_policy.CredstashReadAccess.arn,
        aws_iam_policy.lighthouse_developers.arn,
        aws_iam_policy.VagovSSMLowerEnvironmentAccess.arn,
        aws_iam_policy.developer_codebuild.arn,
        "arn:aws-us-gov:iam::008577686731:policy/dsva-ECS-deploy",
        aws_iam_policy.elasticsearch_readonly_policy.arn,
        "arn:aws-us-gov:iam::aws:policy/AWSCodeBuildReadOnlyAccess",
        aws_iam_policy.dvp_dynamodb_readonly_policy.arn
      ]
    }
```

46 users in iam_users.tf are members of the `lighthouse-developers` group. 

Link to the AWS docs for the additional requested access:
[RegisterScalableTarget](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_RegisterScalableTarget.html)
[PutScheduledAction](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html)
[PutScalingPolicy](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScalingPolicy.html)

[UpdateDomainConfig](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/configuration-api.html#configuration-api-actions-updatedomainconfig)

**Comment by evelez-va** [comment]
This ticket is now resolved with the merge of https://github.com/department-of-veterans-affairs/devops/pull/11353.

Thank you @jbritt1 for all the help and working this with us!
