### ISSUE TITLE
[PM] | GA Widget | Address Change Messaging

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41963]
Description:

Add a GA widget to the Address Validation board that tracks the following:

- how many times was the message displayed (count)
- clicks "yes"
- clicks "no"
- clicks "close"

![Screen Shot 2022-05-26 at 4.06.15 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/bf1cf55c-852e-47b1-ae19-320acf3cea51)

**Comment by michelle-dooley** [comment]
@SKasimow thanks for your submission, we will review during grooming tomorrow.

**Comment by michelle-dooley** [comment]
@SKasimow - this work is complete. Please let us know if you need any further asistance.
