### ISSUE TITLE
SOCKS access for Abby Blue

### ISSUE THREAD

**Issue by ActualAbby** [department-of-veterans-affairs/va.gov-team#41977]
### Your Name

Abby Blue

### Your Email

abby.blue@adhocteam.us

### Your Role and Team

Associate Product Manager

### Product Manager (PM) name and email

Lee Helmer

### Product Owner (PO) name and email

Mike Chelen

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIkmMCMGD4W/KUGJ1GywF4t+mzhP+M4Y2m5FRQx0ql3 actualabby@gmail.com

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
@ActualAbby is in the Platform Team Roster.

**Comment by iriteshp** [comment]
@ActualAbby can you please validate the SSH key? it doesn't look right.

**Comment by kjduensing** [comment]
To shed some further light, looks like this was a personal access token that may have been generated in response to [step 2 of the socks proxy access documentation](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy#How-can-I-set-up-access%3F). This is a necessary step, but you'll also need an ssh key. [Instructions to do that are here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). Once you've generated a key following the instructions above, simply replace the key listed above with the new one and we'll keep working on this request. Thanks!

**Comment by ActualAbby** [comment]
@keithdadkins Thank you for the clarification! I have updated this issue with the new one. Let me know if there is anything else you need from me!

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by ActualAbby** [comment]
Hello, Apologies it seems I did this a bit out of order. I am getting a Warning that my SSH Key is not approved yet. 

I have copied the SSH key to my clipboard that it gave me, that needs approval. I will paste it below, please give me a shout if there is anything I can clarify. Again sorry about that mix up

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7PBfiuCskqKDKoj4V3Wjf6typlUB2jBe+azZumW42/XowagBPtKme9ycnFXNXuItAf86XbPcdzIUjpXM5dCnKBn2O8iMIfHB7KZeOiuLh/NDCAmBJHXXRfV2+mjzB3ukqvLPTVJ9zvCrCoE0zaj+ZQhqw60jNIeQQADruAqMBOHGNCAP0DJHQBxOd9m0j7uzLKrmTI14osfDL10XKpl2Ymbmfw20gKsxcCs8hjSV5n6xMFBg74d0Ie8Rlk1vFxPS5ihVjBHfXQ5GXeq0zqESb4QpyqeIoNF69Rua0iU9TB5d93pOXDxJfBk3535fVe4OYxwXGeLaZehjKLZZUxH53IHSgkBG7C0yMxMwdKL8L8ceZJ6ZY1EZGvSwVvk+N4vFAFikN1z6ThiHtOs+KlogYKIXOkMP/7izCzoKxgoJ4HVTV0sd1lJwLbFjzUXKRtnzGjiuuelHb4rasnspbQrRjMYOjNsfjsPkGtnEUzAPq3mz+hdnBynnpohyqFDMKuRU= abbyblue@Abbys-MBP.localdomain
`

**Comment by kjduensing** [comment]
@ActualAbby, you should be good to go now! If you run into any additional issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by ActualAbby** [comment]
@kjduensing Thank you so much and I will reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html) if I need any more help,
