### ISSUE TITLE
SOCKS access for Daniel Sasser

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-team#42007]
### Your Name

Daniel Sasser

### Your Email

daniel.sasser@agile6.com

### Your Role and Team

Backend Engineer on VA.gov Public Websites, Sitewide Crew

### Product Manager (PM) name and email

Wes Rowe wesley.rowe@agile6.com

### Product Owner (PO) name and email

@davidconlon 

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNCwjbtdijSfQMHFgzIfC4Y+dIc2UD0HsDI2J2fCEgQ1hn7RSc/5MAeznNWkBhlzqvXWidyqx+2l1vgFSooT4Ci/+X13n1ud8OerQCYOh5x55ttQ8hNc+EVk8ntj34kTv0s1kHQdTtWqCfRhdA2M4IgPzqRQO4k3vPClkVuk2TSGFzmMyUacDC5qh21dE/MzIfHdQTvslIryFo35e6VklcGePtW0K04ZT+AP7pbtG3yCyVoYklWPS6iP4VpJ2K7t5tvmc6EWoQ4MvZT+Hya69jFjQQM8TgM7u9ScP8Y+yrK9+I1UKuoU1fHMX/UbZAEAwfPkQVjzc6B2zPfPwaqL80chG+I0onDhB4r7zPfUxi2KqBqIKG+M4d/UGMOWWPXbPH+pOtWYtJc+/26Of8XoYlyDhC1Qr4MyXKtI0xk58LLj8tMq90Zy40MTVDzNNBR5n1M2cmjKDUGPlJdszLoVB/M19yZAUhS6IHDICKKMBnMju7DI9oQ3+j1qQi6YIPcJE= danielsasser@MacBook-Pro

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
