### ISSUE TITLE
Type of Care & Doctor's Name Information 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42027]
## CHIP Dependency
CHIP [work](https://github.com/department-of-veterans-affairs/chip/issues/993)

From an email from Chris Wilmsen:
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/430a786f-91af-4126-8055-d97b26eee03c)

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1657559781261219)

## User Story
As a Veteran, when I see my appointment information, I would like to see some additional information such as physical location, doctor, and type of appointment so that I understand more about my appointment.

Additional information:
- Physical Location
- Doctor's name
- Type of appointment (e.g., primary care, cardiology)

NOTE: VAOS is currently working on making the Doctor's name and type of appointment available

## Background info
Slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653665302561659)
[Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/telephone/research-findings.md#9-veterans-suggested-a-variety-of-features-or-appointment-information-to-add-to-the-experience)

**Comment by loripusey** [comment]
@loripusey Ask Chris Horton if there is CHIP work to do

**Comment by loripusey** [comment]
Met with Chris Horton on 6/30; he will be adding tickets for the CHIP work to make Type of Care and Doctor's Name fields available

**Comment by loripusey** [comment]
@loripusey to reach out to Jeff Roof (VAOS) to find out when the V2 fields will be available for consumption

**Comment by brdunfield** [comment]
Screenshots for product guide: @benbrasso-agile6 
[https://app.zenhub.com/files/133843125/1ff21ab9-fb78-43a5-b016-8be3cb7a6142/download](https://app.zenhub.com/files/133843125/1ff21ab9-fb78-43a5-b016-8be3cb7a6142/download)

[https://app.zenhub.com/files/133843125/973819b4-745b-4fc8-96f6-e9412a2103b1/download](https://app.zenhub.com/files/133843125/973819b4-745b-4fc8-96f6-e9412a2103b1/download)
