### ISSUE TITLE
[Ongoing Service] Platform Infrastructure Maintenance

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4202]
## User Story and Problem Statement
As a VSP Operations Eng, I need to know what ongoing maintenance tasks need to be performed, so that we can keep the platform working properly.   

### High Level User Story/ies
These tasks are for ensuring we keep up with required platform maintenance. 
 
## VSP Objective (Q1 & Q2 2020)
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

## Measuring Success (KRs/KPIs)
- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month

**Comment by rroueche** [comment]
@ricetj could you adjust the title so it's clear to readers w/o context what this is for? Maybe something like "Platform infrastructure maintenance'?

**Comment by ricetj** [comment]
> @ricetj could you adjust the title so it's clear to readers w/o context what this is for? Maybe something like "Platform infrastructure maintenance'?

Updated 👍

**Comment by jhouse-solvd** [comment]
Closing, open issues moved to: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14990
