### ISSUE TITLE
Measure Urgent Care PDF downloads

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4203]
## Problem description
How might we  measure the number of users who download the urgent care benefit PDF?  

## Goal
We want to assess the success of the UX redesign as it relates to Veterans being able to search for urgent care locations and be prepared for the visit

## Objectives or Key Results this is meant to further
- Objective 2: Reform Community Care implementation
  - Key Results: A baseline for the percentage of users searching for urgent care who download the benefit PDF will be established by March 15, 2020.

## Acceptance Criteria
- [ ] A method for measuring the percentage of users searching for urgent care who download the benefit PDF has been implemented

**Comment by nedierecel** [comment]
@mmiddaugh Confirming we received - we are tracking PDF downloads now, so we should be able to track these PDF downloads.

**Comment by mmiddaugh** [comment]
Per the Office of Community Care 1/27/2020, PDF will not be used. FL will link to web page that will be developed by OCC. 
We'll need to think about measuring the # or % of users searching for Non-VA urgent care or Non-VA urgent care pharmacies who click through to that web page.

**Comment by nedierecel** [comment]
@mmiddaugh Thanks for the update on how an outbound link will be used in lieu of the PDF. We should be able to measure the frequency of the new link. 

Once you have more information on what the URL might be for the OCC content or a wireframe, please let us know.

**Comment by nedierecel** [comment]
@mmiddaugh - @jonwehausen created an issue that includes this request in #5690. Is it okay to close this one since the larger ticket outlines all the analytics deliverables?

**Comment by mmiddaugh** [comment]
I apologize for my delay. Sounds good to me! I'll close this, @nedierecel
