### ISSUE TITLE
Documentation Review: DataDog APM (Internal)

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42046]
## Description
As part of the [Console Services Documentation efforts](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38917) this document needs to be reviewed for correctness and updated as needed.

## Acceptance Criteria
- [x] Document is reviewed for correctness
- [x] Document is updated as necessary

**Comment by RachalCassity** [comment]
This might have to be edited after distribution metrics are correctly being sent to Datadog.

**Comment by RachalCassity** [comment]
Datadog APM documentation has been reviewed.
