### ISSUE TITLE
Documentation Review: How to use DataDog for APM

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42047]
## Description
As part of the [Console Services Documentation efforts](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38917) this document needs to be reviewed for correctness and updated as needed.

## Acceptance Criteria
- [x] Document is reviewed for correctness
- [x] Document is updated as necessary

**Comment by RachalCassity** [comment]
How to use DataDog for APM has been reviewed.
