### ISSUE TITLE
VA.gov Testing Tools - Assess state of existing test user accounts

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#4204]
**Problem Statement**
We do not have an accurate, up to date list of staging test accounts so people can easily identify the right one for their test case.

**Goals**
Address pain points around finding test accounts in order to:
Reduce the time it takes VFS teams to QA their products.
Make it easier to demo pre-production features and products.

**Hypothesis**
The current set of staging test accounts will meet teams’ QA and demo needs if we make it easier to find the right test account for a user scenario.

**Objective**
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

**Definition of Done**
- Gather and consolidate all documented information on staging test accounts.
- Run [rake task](https://github.com/department-of-veterans-affairs/vets-api/pull/3607#pullrequestreview-326904723) to pull accounts's user attributes from mvi database 
-  Publish updated test accounts list on Github to make it easier to identify what accounts match a given VA.gov product and use case.

**Comment by jchasia-adhoc** [comment]
List of staging test users: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/MVI%20Integration/reference_documents/mvi_stagingUsers_fullList.csv

**Comment by annaswims** [comment]
I [migrated]( https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/33) the test accounts to va.gov-team-sensitive
