### ISSUE TITLE
[FE] Address validation: Continue, Cancel, and X buttons are broken

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4205]
## What happened?

1. From the Edit Mailing Address from, I changed address from "811 Vermont Ave NW, Washington, DC 20571" (real address) to "811 Vermont St, Washington, DC 20592" (fake address).
2. When I clicked Update, I got the address validation screen (yay!).
3. However, the following went wrong on the address validation screen:

- Clicking the X didn't work.
- Clicking Continue changed the button to Edit Address (Continue should have sent me to the confirmation screen).
- Clicking Cancel also changed Continue --> Edit Address.

<img width="452" alt="Screen Shot 2019-12-12 at 2 26 23 PM" src="https://user-images.githubusercontent.com/34068740/70744188-375fad00-1cef-11ea-8c83-64abc90e1b82.png">

<img width="426" alt="Screen Shot 2019-12-12 at 2 55 02 PM" src="https://user-images.githubusercontent.com/34068740/70744371-8d345500-1cef-11ea-85da-954de241195d.png">

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User: This happened with user 226.

## Steps to Reproduce
- URL: https://staging.va.gov/profile

See top section for steps to reproduce.

## Desired behavior

1. X and Cancel should always close the form.
2. Continue should continue the user to the confirmation screen.

## Acceptance Criteria
- [ ] X and Cancel close the form.
- [ ] Continue takes the user to the confirmation screen.

**Comment by Samara-Strauss** [comment]
cc/ @erikphansen @artistgreen @Justin-Pickett for awareness.

**Comment by erikphansen** [comment]
@Samara-Strauss can you take another pass at this and close it if the modal is working correctly?

**Comment by Samara-Strauss** [comment]
Yes! Validated on staging. All buttons are working as expected now.
