### ISSUE TITLE
[Design] | Update Convo Guide | Personal Info revisions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42068]
### **Description:**

 VA Profile does not currently support the deletion of Preferred names or Gender Identity once added. We'd like to add a question to our upcoming research to see if Veterans feel this capability is something they would expect to be able to do and/or can foresee a need for this feature.

**Comment by cgednalske** [comment]
Updates have been made to the [convo guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/uat/conversation-guide.md)to make sure participants are aware that if they choose to add their information it cannot be deleted + ask about questions/thoughts they have on this and if they'd like to be able to remove this information. 

Unless there's anything else, I think this can be closed!

**Comment by SKasimow** [comment]
Sounds good...closing!
