### ISSUE TITLE
[BE] 10-10CG - Mulesoft Ph2: Vets API Retries

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#42079]
Implement retry functionality for when the MuleSoft API is unavailable to receive an application.

Questions:
- Do we send to Central Mail, and if so, when?
     - No, we will not be sending to Central Mail
- What happens if _absolutely everything_ fails?
     - SOP created to address "catastrophic failures".

[Vets-api retries for MuleSoft - Ultimate Failures process (SOP)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Vets-api%20retries%20for%20MuleSoft%20-%20Ultimate%20Failures%20process.md) created and stored in GH for quick reference.

**Comment by lihanli** [comment]
instead of sending encrypted emails, if we can send a plain text email with a link to an encrypted 7z file, that would be easy to do and not require any new integrations

**Comment by batemapf** [comment]
re: sending an email or other programmatic means of sharing submission info --> TL;DR, we don't need to do it. see https://dsva.slack.com/archives/CMJ2V70UV/p1657723510737339?thread_ts=1657651448.669859&cid=CMJ2V70UV
