### ISSUE TITLE
Update the Type of Care label on appointment details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#42071]
## Summary
We are requesting the label to be removed if the type of care data is not available for an appointment. 

### Actual Result
<img width="509" alt="Screen Shot 2022-05-31 at 3 03 02 PM" src="https://user-images.githubusercontent.com/90797205/171265531-b23fa2b5-1b82-4111-9c51-d69763609d28.png">

### Desired Result
The type of care label is removed from the appointment details page if the data is not available. 
[Please refer to VAOS FE copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#vvc-home-booked-future) and [Design Specs](https://www.figma.com/file/WJ55KM4G2Sk15bfIGsRpzr/Add-Type-of-Care-%2332956)

## Definition of Done
- [ ] Desired result is achieved

**Comment by simiadebowale** [comment]
@ldelacosta this is ready for validation.

**Comment by ldelacosta** [comment]
@marcynadeau - If you can help validate the use case when the type of care is not available for an appointment, the Type of Care label should not be displayed.
