### ISSUE TITLE
Design low fidelity prototype IA H1

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#42072]
- [x] Begin designing draft prototype for IA hypothesis H1
- [x] Iterate on prototype as plan #2 is refined
- [x] Socialize with VA business partners if qualitative plan is evolved

**Comment by MOStudioCarolyn** [comment]
link to sketch file 
https://sketch.com/s/8e92dcff-c676-4b2b-bd75-4ddbb4fdbd26
