### ISSUE TITLE
Adding Lauren Ernest to DSVA Slack

### ISSUE THREAD

**Issue by anerbovig** [department-of-veterans-affairs/va.gov-team#42086]
Hi there, could we reactive or create a new Slack account for Lauren Ernest, as a full member of DSVA Slack? Her email is lauren.ernest@adhocteam.us.

Lauren previously served as a Product Manager with the VA Online Scheduling team and will now be supporting delivery for the CEDAR Benefits teams. Thank you!

**Comment by anerbovig** [comment]
Hi there! We're still waiting on Lauren getting added to Slack. Thank you!

**Comment by LEHigley** [comment]
this email address isn't working for some reason--can you confirm this is correct?

**Comment by anerbovig** [comment]
Thanks Lacey! I checked again and that's the right email. Would it be an issue if an account was already created and then deactivated in Slack with that email address?

**Comment by laurenernest** [comment]
Lauren.Ernest@va.gov was my old email if that helps
