### ISSUE TITLE
GIBCT - Complaints in the last 24 months

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#4208]
Create language for Cautionary information accordion.  Content should explain that any complaints displayed have been collected in the last 24 months. FILE WILL BE GENERATED OUT OF SALESFORCE AND WILL ONLY HAVE DATA REPORTED IN THE LAST 24 MONTHS. 

Example - Ashford University
https://www.va.gov/gi-bill-comparison-tool/profile/21007103#viewWarnings

- [x] Draft content
- [x] Share w UX team & refine as necessary
- [x] Share w DSVA & refine as necessary
- [x] Update GIBCT content doc
- [x] Share with UX Designer to incorporate in prototype (separate ticket)
- [ ] Share w devs

**Comment by amyknox** [comment]
This needs an estimate and may need a "pulled in" label.

**Comment by tmcmurdo** [comment]
Hi @peggygannon 

Within the GI Bill Comparison Tool, on the School Profile page, we're modifying the copy in the "Cautionary Information" accordion to let users know that the count of student complaints represents the number of complaints received in the last 24 months.

*Current Copy*

![image.png](https://images.zenhubusercontent.com/5b73380097e4e42cb4c8c5d2/77f303f2-82ca-402a-9c1e-ca873d1e3204)

*Proposed Copy*

![image.png](https://images.zenhubusercontent.com/5b73380097e4e42cb4c8c5d2/c8831997-8d16-4d7e-90de-f7b37568da82)

For reference, here is a link to the current page, if you are interested.
https://www.va.gov/gi-bill-comparison-tool/profile/21007103

**Comment by ccruzgra** [comment]
@peggygannon Do you have any feedback on the proposed copy? We are leaning towards the first option, "4 Student complaints in the last 24 months (Source)" as it is more succinct. Thank you.

**Comment by amyknox** [comment]
@peggygannon - we learned yesterday that **"Student complaints in the last 24 months"** is the more accurate phrasing since there are many more complaints received in that timeframe. If you could provide feedback on that content only, that would be helpful.

Thank you!

**Comment by peggygannon** [comment]
@amyknox @ccruzgra Hello, This phrasing is fine **Student complaints in the last 24 months** I have no further edits. Tx!

**Comment by ccruzgra** [comment]
Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/colmery-act-2019/design/content/profile-accordion-cautionary-information.md
