### ISSUE TITLE
[Design] Update Poster for US Territories

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42081]
Need to talk to VeText folks about when the implementation for using a full phone number will be implemented.

## Background Info
Slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1654022933886219)

## Deliverable
US Territories (Philippines) poster created and uploaded:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md

**Comment by loripusey** [comment]
@loripusey

**Comment by loripusey** [comment]
@zach-park Can this one be closed?

**Comment by zach-park** [comment]
PDF version of US Territories (Philippines) uploaded on GitHub.
