### ISSUE TITLE
Business intake form for Benefits Team 1

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#42083]
## Your Details
1.  **Your Name**: 
  PM: @jacobworrell
  FE dev: @Mottie

2.  **Business Line**: Claims & Appeals
    (ex., claims, health, etc.)

## Notification Details
1.  **Notification type**: Email
    (email, text/SMS, or both)

2.  **Please describe your use case.**
    We were originally tasked with adding a dependency verification status as a popup notification to ensure Veterans verified their dependents regularly in order to get paid on time and in the correct amount and also to avoid overpayments and debt. The problem is that the modal is set to be shown to the Veteran every year, but [only when they view their dependents page](https://www.va.gov/view-change-dependents/view/) while logged in. 

 In order to make this more visible to the Veteran and achieve our goal of having more veterans actually change their dependents status before suffering adverse consequences, we think that using an email notification to remind them to check their dependents once a year (and maybe even if one of their dependents has an 18th birthday) would be the best solution

4.  **What actions can the user take based on the notification they receive?**
     Log in to [review their dependents page](https://www.va.gov/view-change-dependents/view/)

5.  **What is the desired business outcome?**
    Reduce overpayments, reduce complaints and dissatisfaction from veterans due to having to repay overpayments. 

6.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    BGS? But that's just a guess. We don't know and would like to be advised.

7.  **What will trigger the notification?**
    yearly timer, 18th birthday (but this is of secondary importance)

8.  **Provide sample content per notification type, if you have it.**
    This is only a sample, but message could read something like: 

"Please make sure your dependents are correct. 
    
 Our records show it has been a while since you verified information about your dependents. Please take a few minutes to review your information and add or remove dependents to reflect your current life circumstances. Doing so will help us provide you with the appropriate benefits. [Link to View/Change Benefits page]"

18th Birthday Version: 

"Please make sure your dependents are correct. 
 
 Our records show [person] has just turned 18. Please take a few minutes to review your information remove [person] from your list of dependents if they are no longer your dependent. Doing so will help us provide you with the appropriate benefits. [Link to View/Change Benefits page]"

9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    Not for this use case. And no I don't know who my PO is. 

10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    Email based on a Veteran with dependents

11.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    No

12.  **What is the anticipated volume of notifications per day, week, month?**

8-10% of veterans that receive some form of payment per month, but that's just an estimate. The volume would be large. 

14.  **When does this notification need to be in production?**

The pain point of veterans having to repay back overpayment money is severe enough to warrant this being prioritized in our view.

**Comment by bevnobev** [comment]
Hi @jacobworrell & @Mottie.  Can you suggest a date/time this week or early next week to have a quick chat around this?

**Comment by Mottie** [comment]
My schedule is pretty open next Monday & Tuesday. I'll leave it to Jacob since he probably has less free time.

**Comment by bevnobev** [comment]
@jacobworrell @Mottie I'm attaching our VA Notify Playbook for you to digest before we meet.  cc: @mjones-oddball [https://app.zenhub.com/files/133843125/52d29d2d-b64b-45c6-ab25-8f83509fad07/download](https://app.zenhub.com/files/133843125/52d29d2d-b64b-45c6-ab25-8f83509fad07/download)

**Comment by jacobworrell** [comment]
@bevnobev I'm free on Monday any time before 1pm ET. Might be a good idea to include Matt Self as an optional attendee too.

**Comment by Mottie** [comment]
@bevnobev This is the epic we've been working on - https://github.com/department-of-veterans-affairs/va.gov-team/issues/16345

**Comment by mattpointzxer0** [comment]
yes, pls!!

**Comment by bevnobev** [comment]
Hi @mattpointzxer0 We meet with your team to discuss the ask.  Assuming we would send an email to those Veterans that have a dependent, it's not obvious, from the time we have spent in the code, how to determine which Veterans have a dependent and how often to trigger the notification.  Thoughts?

**Comment by mjones-oddball** [comment]
Inactive - moving to closed
