### ISSUE TITLE
Vets-api 686c dependent creation file upload source is incorrect

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#42099]
# Expected behavior
Vets-api and lighthouse share the same repo and are deployed together, so currently they are the same codebase.  However, all interaction between vets-api and lighhouse should be done via rest calls, neither should call directly into each others code and instead they should use rest calls.
Since vets-api is calling directly into lighthouses service layer instead of making a rest call, some of lighthouses file upload code is being skipped(Controller, model).  I'm guessing that the missing code is providing logging and specifically we know that the "source" is not being set properly....**the source should be va.gov or vets-api**

## Current behavior
Currently app/controllers/v0/dependents_applications_controller.rb/create calls directly into lighthouse's service layer code to upload files(s), specifically the create results in a direct instantiation of ClaimsApi::VBMSUploader in vets-api/app/models/saved_claim/dependency_claim.rb in def upload_to_vbms

## Your fix
Changed the direct call into a rest call instead.  We may already have a lighthouse rest service wrapper in vets-api that can be used.

## How has this been tested?
TBD once dev is undertaken, depending on the details of the code

## Acceptance criteria
- [ ] vets-api is upload 686 dep files via a rest call to lighthouse

**Comment by saderagsdale** [comment]
@jacobworrell adding a note for you since LH may look for an update.
