### ISSUE TITLE
GIBCT - Not available on this campus. 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#4209]
Create language for Veteran programs accordion.  Content should explain that there's no data on Veteran programs for the institution and Veterans should contact the school / employer / provider directly with questions.  

- [x] Draft content
- [x] Share w UX team & refine as necessary
- [x] Share w DSVA & refine as necessary
- [x] Update GIBCT content doc
- [x] Share with UX Designer to incorporate in prototype (separate ticket)

Content Doc:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/colmery-act-2019/design/content/spp-accordion-va-programs.md

**Comment by amyknox** [comment]
Issue needs an estimate and may need a "pulled in" label.

**Comment by tmcmurdo** [comment]
Hi Peggy, 
We are creating content to display on the GI Bill Comparison tool when a school has no Veteran programs listed in the Veteran programs accordion on the school profile page.  

Here is what the accordion will look like if programs are available.

![image.png](https://images.zenhubusercontent.com/5b73380097e4e42cb4c8c5d2/42e56b22-3e6d-4bf2-953c-aa9a0fb1d71c)

When a school as 0 Veteran programs, we plan to display the following copy in the accordion:

"For information on which Veteran programs this school offers, please contact the school directly, or their military office, if available."

Feel free to suggest edits to this content.

Here is a link to the existing school profile page if you'd like to see the accordion in the context of the entire School Profile page:
https://www.va.gov/gi-bill-comparison-tool/profile/11929140

As part of this ticket, we'll be removing the right column which currently lists programs the school does not have.

**Comment by peggygannon** [comment]
@tmcmurdo Hello! Please see my content recommendation below: 

Please contact the school or their military office directly for information on the Veteran programs they offer.

**Comment by ccruzgra** [comment]
Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/colmery-act-2019/design/content/spp-accordion-va-programs.md
