### ISSUE TITLE
Contact Center Review for Patient Check-In - Spanish Translations

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42097]
## Description

Patient Check-in allows Veterans to check in for their scheduled VA medical appointments using their own mobile phone. A Veteran or an authorized caregiver can check-in up to 30 minutes before and 15 minutes after their scheduled appointment. To complete check-in, a Veteran:

- Views a poster hung on the walls of the clinic waiting area where they have their scheduled appointment.
- Follow instructions on the poster to scan a QR code or text “check in.”
- Receives a text message with a unique link, such as https://www.va.gov/c/xxxxxxx/.
- Taps on the unique link on their phone and begins check-in on VA.gov.
- Reviews, or has confirmed, contact, next of kin, and emergency contact information within the last seven days.
- Remains in the waiting room until a staff member takes them back for their appointment when ready.
- Pre-check-in allows veterans to use their mobile phones to confirm if their contact, emergency, and next of kin information is up to date. Veterans can most often complete pre-check-in at least 7 days prior to their scheduled appointment, but the timing is based upon the facility’s setup. Veterans are unable to pre-check-in after 12:00 AM on the day of their appointment. 

This feature release contains Spanish translations. Further information can be found in our [release notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/detailed-release-notes/spanish-translations.md).  

### Launch Date

This feature's launch date is TBD as it's dependent on multiple rounds of language review. Best guess is June 15, 2022. 

### Version Number

1.2

### Product Guide

Updates to product guides can be seen through track changes and/or comments. 

[Check In Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/files/8814955/PATIENT.CHECK-IN_PRODUCT_GUIDE.docx)

[Pre Check In Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/files/8814963/PRE-CHECK-IN_PRODUCT_GUIDE.docx)

### Product Video

No changes to the product video at this time. Original product video can be found here: 

https://drive.google.com/file/d/1feXtP9yVuTPE-7J73Sk8mVrQocU6QMNK/view?usp=sharing

https://github.com/department-of-veterans-affairs/va.gov-team/issues/41073

### Product Video Transcript

No changes to the product video at this time.

[Audio](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/Patient_Check_in_Demo_May_6_2022.m4a)

[Script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/Demo_Script_May_6_2022.pdf)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by benbrasso-agile6** [comment]
CC @loripusey

**Comment by starlow00** [comment]
Thanks @benbrasso-agile6. Additions look good! I'll forward to VEO for their review and update this ASAP.

**Comment by starlow00** [comment]
VEO has no changes/accepts guides. Closing.
[PRE-CHECK-IN_PRODUCT_GUIDE_1_2_06012022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8893857/PRE-CHECK-IN_PRODUCT_GUIDE_1_2_06012022.docx)
[CHECK-IN_PRODUCT_GUIDE_1_2_06012022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8893858/CHECK-IN_PRODUCT_GUIDE_1_2_06012022.docx)
