### ISSUE TITLE
[FE] Address validation: Copy is missing a period

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4211]
## Background

The address validation state that has override AND suggestions is missing a period at the end of the alert message copy. Per #3890, the final sentence of the alert copy should have a period — "If the address you entered isn’t correct, please edit it or choose a suggested address below."

<img width="417" alt="Screen Shot 2019-12-12 at 3 31 36 PM" src="https://user-images.githubusercontent.com/34068740/70747151-5bbe8800-1cf5-11ea-95eb-366e16fb6d8b.png">

## Tasks/Definition of done

- [ ] Add period to the end of this sentence.
- [ ] Confirm that all other states — override without suggestions; no override with suggestions; no override, no suggestions — all have periods at the end of the alert copy. Final copy and all states are outlined fully in #3890.

**Comment by Samara-Strauss** [comment]
cc/ @erikphansen @artistgreen @Justin-Pickett for awareness.

**Comment by erikphansen** [comment]
Screenshot showing that this has been fixed. The PR added a period to another piece of messaging as well.

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/097ef2e8-c760-450b-b9d6-da06acf54056)

**Comment by Samara-Strauss** [comment]
Looks great! Thanks!
