### ISSUE TITLE
Iterate on research plan #1 based on feedback VA

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#42129]
- [x] Add emails

**Comment by MOStudioCarolyn** [comment]
Research plan updated with Cohort links, submitted to Clayton for review before passing over to Perigean.

Final Plan here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/health-apartment/Health%20Hub/Research/IA%20Tree%20Test%201/2022%20Health%20Hub%20Tree%20Test%20research%20plan.md
