### ISSUE TITLE
CANCELED**Create a formal write-up for login.gov va.gov integration

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#42130]
Describe the journey of our login.gov implementation

- use of cognito, both saml and oauth
- use of ISAM
- use of SiS

**Comment by bosawt** [comment]
@joeniquette Can we close this?

**Comment by joeniquette** [comment]
We really should complete this write up/blog post. I'll add it to the upcoming sprint and try to get it done
