### ISSUE TITLE
[FE] Address validation: Clicking "Update" on the edit form should initiate the spinning animation for the "Update" button

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4213]
## Background.

Not filing this as a bug because I don't believe this was specified in the original build.

I noticed this today when I was trying to save an intentionally fake address to test address validation. After clicking the "Update" button in the Edit Mailing Address form, the "Update" button doesn't show the spinning animation. This is problematic because it took 2 – 3 seconds for the address validation screen to open, and without the animation, I wasn't sure if the "Update" button had registered my action.

On the contrary, when I save a real address and click "Update," the button shows the spinning animation as expected (and then the form closes and the address saves as expected).

<img width="443" alt="Screen Shot 2019-12-12 at 4 11 30 PM" src="https://user-images.githubusercontent.com/34068740/70749578-a55da180-1cfa-11ea-9406-df8fe7d19f0c.png">

## Tasks

- Make it so the "Update" button always shows the spinning animation after it has been clicked, whether it is going to the address validation form or saving the address and closing.

Note on timing: If the animation only triggers if the form is still open after a period of time (eg. 1 or 2 seconds), that's fine. We obviously don't need it if the address validation form opens immediately. But we should have it if the edit form is going to linger for a few seconds before opening the address validation screen.

## Definition of done

- [ ] The "Update" button shows the spinning animation after it has been clicked and before it opens the address validation screen.

**Comment by Samara-Strauss** [comment]
cc/ @erikphansen @artistgreen @Justin-Pickett for awareness.

**Comment by Samara-Strauss** [comment]
Hey @bradl3yC I wasn't able to validate this on staging. The spinning animation is not showing for me between the Edit modal and address validations screen. Does it only trigger after a certain amount of time?

**Comment by Samara-Strauss** [comment]
Moving our Slack convo here. I still can't get this to work on staging :-/

**Comment by Justin-Pickett** [comment]
@bradl3yC any progress on this being able to work in staging?

**Comment by Justin-Pickett** [comment]
This ticket is closed. This ticket is linked to #4483
