### ISSUE TITLE
GIBCT - 24 mo Complaints PROTOTYPE 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#4214]
- [x] Update GIBCT Prototype with approved content
- [x] Share prototype / content with EDU
- [x] Refine if necessary
- [x] Share approved prototype with Dev team

**Comment by ccruzgra** [comment]
Prototype: https://bahdigital.invisionapp.com/share/R3IACBMBWFJ#/screens/296026781
