### ISSUE TITLE
Update vets-website to use new provider lookup endpoint for CC request

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#42146]
Currently there is a known issue where the preferred provider name is not displayed upon submitting a CC request (referenced in ticket 37906: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/37906). 

Vets-api has completed development of a new endpoint where a provider name can be looked up by NPI - this work is captured in the following ticket: https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/36913

The provider NPI is available in the response from a submitted CC request. Vets-website will need to be updated to consume this new getProvider endpoint, passing in the NPI, and surface the returned provider name in the appropriate fashion.

Here is the mobile_ppms_service swagger containing details for this endpoint, /providers/{id} https://coderepo.mobilehealth.va.gov/projects/VAR/repos/mobile-ppms-service/browse/mobile-ppms-service/src/main/resources/swagger.json?at=refs%2Fheads%2FRelease%2F1.5

Swagger copy from the link:
```
Base URLs:
SQA https://veteran.apps-staging.va.gov/ppms/v1
Prod https://veteran.apps.va.gov/ppms/v1

GET /providers/{id}
id: the provider npi, type = integer, required = true

Example 200 response:
{
  "@odata.context": "https://nprod.api.ppms.va.gov/dws/v1.0/$metadata#Providers",
  "value": [
    {
      "ProviderIdentifier": 7511268789,
      "ProviderIdentifierType": "NPI",
      "Name": "ANDERSON, SARA JOE  ",
      "ProviderType": "Individual",
      "Address": "1640 GREGSON ST\r\nDURHAM, NC",
      "AddressStreet": "1640 GREGSON ST",
      "AddressCity": "DURHAM",
      "AddressStateProvince": "NC",
      "AddressCounty": "DURHAM",
      "ProviderStatusReason": "Active",
      "PrimaryCarePhysician": false,
      "IsAcceptingNewPatients": true,
      "ProviderGender": "Female",
      "IsExternal": true,
      "CanCreateHealthCareOrders": false,
      "ContactMethodEmail": false,
      "ContactMethodFax": false,
      "ContactMethodVirtuPro": false,
      "ContactMethodHSRM": false,
      "ContactMethodPhone": false,
      "ContactMethodMail": false,
      "ContactMethodRefDoc": false,
      "BulkEmails": false,
      "BulkMails": true,
      "Emails": false,
      "Mails": false,
      "PhoneCalls": false,
      "Faxes": false,
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "ModifiedOnDate": "2021-08-27T01:52:04Z"
    }
  ]
}

Example 400 response:
{
  "status": 0,
  "errors": {
    "status": 0,
    "code": "string",
    "detail": "string"
  }
}
```

AC:
[ ] vets-website calls the new getProvider endpoint to retrieve provider name by NPI
[ ] the returned provider name is appropriately displayed on the submitted CC request page

**Comment by ldelacosta** [comment]
@cferris32 - Please add the swagger doc when you have a chance. Thanks!

**Comment by ldelacosta** [comment]
![Screen Shot 2022-06-08 at 10.15.26 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/51039125-ff8c-4479-9628-9c4ed9280c03)

**Comment by ldelacosta** [comment]
Validated the changes in staging: 

![Screen Shot 2022-07-01 at 7.40.40 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/68a5bd54-a66f-47a5-98b4-1782027325c6)

![Screen Shot 2022-07-01 at 7.41.36 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/5d39e60d-7c67-4a1b-8053-bb87e5f77805)

![Screen Shot 2022-07-01 at 7.42.03 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/b32778e0-6196-4b3f-b42b-414420cfbaa6)
