### ISSUE TITLE
GIBCT - Not available on this campus PROTOTYPE

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#4216]
- [x] Update GIBCT Prototype with approved content
- [ ] Share prototype / content with EDU
- [ ] Refine if necessary
- [ ] Share approved prototype with Dev team

**Comment by ccruzgra** [comment]
Prototype: https://bahdigital.invisionapp.com/share/R3IACBMBWFJ
Includes two profile pages, one with the programs listed and the other with no programs displayed and the corresponding message.
