### ISSUE TITLE
Images on "Build and deploy process flows" do not appear

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#42170]
## Description

There are broken/missing images on https://depo-platform-documentation.scrollhelp.site/developer-docs/build-and-deploy-process-flows

**1. What do you need help with? Check one:**
- [ ] Creating new documentation
- [x] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

**2. Who are the primary users of your documentation? Check all that apply:**
- [x] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other: ____________________

**3. Estimate the number of pages to be created, updated, or reviewed? _____1_____**

**4. Do the documents contain graphics such as screenshots, code snippets, diagrams, or videos?**
- [X] Yes, and describe: __unknown, images do not appear__
- [ ] No

**5. Who is the point of contact for this documentation?** ____________________

**6. Are there other documents, tickets, or artifacts that will be impacted by this update?**
- [ ] Yes, and describe ____________________
- [ ] No

**7. Are there plans to update other documents/pages that have similar content?**
- [ ] Yes
- [ ] No

**Comment by SSimmorins** [comment]
@dcloud Hi! 
This is Samara.   The image is not showing on the Platform side because we do not support this plug-in.  In order for the image to be viewed, it would need to be a screenshot.  Please let us know when you have replaced the embedded files with screenshots.  Thanks.

**Comment by SSimmorins** [comment]
@k80bowman @ndsprinkle Daniel says that the LucidChart diagram doesn't show up on the Platform website view.  However, it is viewable (verified) on the Confluence view. That is because Scroll Viewport doesn't support the macro used.  Confluence shows that you were the most recent contributors to the doc.
Can you replace the two embedded files with screenshots instead? 
cc @caw310 @laineymajor

**Comment by vbellissimo** [comment]
@SSimmorins to follow up to see if we can get screenshot version of this image.

**Comment by vbellissimo** [comment]
![Isolated application build and deploy process](https://user-images.githubusercontent.com/106613300/176774557-1dc0ea0f-37e0-47a3-995f-bfdab03ceb2b.png)
![Standard build and deploy process](https://user-images.githubusercontent.com/106613300/176774570-3d960d02-cc3a-4e73-beae-f758138d6b77.png)
@SSimmorins I've attached the two diagrams in question. Can you upload to this page?

**Comment by vbellissimo** [comment]
@dcloud This content update has been resolved and we are closing this ticket. If you have any other questions regarding this content, feel free to contact the Platform Content team at #platform-confluence. Thank you.
