### ISSUE TITLE
Document Custom Work

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#42188]
We've done some work to extend Keycloak and its periphery. We should document this work so that folks can get a sense for anything "extra" our solution does that Keycloak doesn't do out of the box.

For each artifact, the documentation should include:
- [x] Deployment strategy
- [x] Tech stack
- [x] Motivation
- [x] Current state

It would be nice to have the following, though not as important:
- [ ] Known bugs
- [x] New features and improvements
- [ ] Contribution guide

***This ticket likely needs to be broken up***

Refer to this running list for AMT documentation:
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2218098691/Documentation

**Comment by calquisola** [comment]
[documentation](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2222620724/Allow+list+extension) created in confluence.

Currently no known bugs for this plugin.
