### ISSUE TITLE
[AXE-CORE]: All page content must be contained by landmarks

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#4219]
### [AXE-CORE]: All page content must be contained by landmarks

Some page content is not contained by landmarks. 

Specifically, the content that contains:

> You're on a preview of the new VA Pittsburgh health care website
We're building a new online experience to make it easier for Veterans to manage their health care. And we're building it with input from you — Veterans, family members, caregivers, and patient advocates — through user research and feedback.
> Please note: This site is still in development. You'll see new content and features added every day because we work iteratively using agile design and development practices.
> Not ready to use the new site yet? Go to the official Pittsburgh.VA.gov

<img width="1001" alt="pittsburgh-preview" src="https://user-images.githubusercontent.com/57469/70832487-31d39700-1dc3-11ea-9109-6101c1490e77.png">

When this content is read to a screen reader there is nothing to indicate it is a banner "alert" or "dialog". To clarify what this content is, it would be helpful to have a `role="dialog"`, `role="complementary"`, or `role="alert"` (_I would lean towards dialog_) on the container element.

## Type of Issue
Template

## Point of Contact

Jennifer

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: https://www.va.gov/pittsburgh-health-care/

## Steps to Recreate

1. Enter `https://www.va.gov/pittsburgh-health-care/` in browser
2. Start screenreading device 
3. Verify that there is no context provided for the content related to the area with the heading, "You're on a preview of the new VA Pittsburgh health care website".

### Current Code Related Nodes:
* #youre-on-a-preview-of-the-new-
```
<h3 class="usa-alert-heading" id="youre-on-a-preview-of-the-new-">You're on a preview of the new VA Pittsburgh health care website</h3>
```
* .usa-alert-text > p:nth-child(1)
* .usa-alert-text > p:nth-child(2)
* p:nth-child(3) > strong
* #\34 5d9ee57ffa3839deeb54035546f2e86
```
<div class="usa-alert-text">
        <p>We're building a new online experience to make it easier for
          Veterans to manage their health care. And we're building it with input
          from you
          — Veterans, family members, caregivers, and patient advocates —
          through user
          research and feedback.
        </p>
        <p>
          <strong>Please note:</strong> This site is still in development.
          You'll see new content and features added every day because we work
          iteratively
          using agile design and development practices.
        </p>
        <p>
          <strong>Not ready to use the new site yet?</strong>
          <a href="https://www.pittsburgh.va.gov/" id="45d9ee57ffa3839deeb54035546f2e86">Go to the official
            Pittsburgh.VA.gov</a>
        </p>
</div>
```
### Possible Fix
* Add `role="complementary"` or `role="dialog"` to the element that contains the announcement about the preview. Either will require additional labelling, as described in the **WCAG or Vendor Guidance** section in this issue.
```html
<div class="usa-alert-full-width usa-alert-full-width-info" role="complementary">
  <div aria-live="polite" role="alert" class="usa-alert usa-alert-info">
    <div class="usa-alert-body">
      <h3 class="usa-alert-heading" id="youre-on-a-preview-of-the-new-">You're on a preview of the new VA Pittsburgh
        health care website
      </h3>
      <div class="usa-alert-text">
        <p>We're building a new online experience to make it easier for
          Veterans to manage their health care. And we're building it with input
          from you
          — Veterans, family members, caregivers, and patient advocates —
          through user
          research and feedback.
        </p>
        <p>
          <strong>Please note:</strong> This site is still in development.
          You'll see new content and features added every day because we work
          iteratively
          using agile design and development practices.
        </p>
        <p>
          <strong>Not ready to use the new site yet?</strong>
          <a href="https://www.pittsburgh.va.gov/" id="45d9ee57ffa3839deeb54035546f2e86">Go to the official
            Pittsburgh.VA.gov</a>
        </p>
      </div>
    </div>
  </div>
</div>
```
* One day, the div could be a `<dialog>` element, which would communicate the landmark role and add semantic context for screen readers. However, the element is not currently supported in IE11, Firefox, Safari, iOS, Opera Mini, or Firefox for Android, so this is not possible today.
```html
<dialog class="usa-alert-full-width usa-alert-full-width-info">
  <div aria-live="polite" role="alert" class="usa-alert usa-alert-info">
    <div class="usa-alert-body">
      <h3 class="usa-alert-heading" id="youre-on-a-preview-of-the-new-">You're on a preview of the new VA Pittsburgh
        health care website
      </h3>
      <div class="usa-alert-text">
        <p>We're building a new online experience to make it easier for
          Veterans to manage their health care. And we're building it with input
          from you
          — Veterans, family members, caregivers, and patient advocates —
          through user
          research and feedback.
        </p>
        <p>
          <strong>Please note:</strong> This site is still in development.
          You'll see new content and features added every day because we work
          iteratively
          using agile design and development practices.
        </p>
        <p>
          <strong>Not ready to use the new site yet?</strong>
          <a href="https://www.pittsburgh.va.gov/" id="45d9ee57ffa3839deeb54035546f2e86">Go to the official
            Pittsburgh.VA.gov</a>
        </p>
      </div>
    </div>
  </div>
</dialog>
```

## WCAG or Vendor Guidance

* [w3c ARIA11: Using ARIA landmarks to identify regions of a page](https://www.w3.org/TR/WCAG20-TECHS/ARIA11.html)
* [MDN ARIA: Complementary role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Complementary_role)
* [MDN ARIA: Dialog role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role)
* [MDN <dialog>: The Dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)
* [Can I use.com Dialog](https://caniuse.com/#search=dialog)

**Comment by mmiddaugh** [comment]
This preview header is no longer in use.
