### ISSUE TITLE
Gather Estimated Average and Peak Transactions per Second for the VA Profile ICD

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42205]
## Problem Statement
As the VA Profile team, we need some estimated numbers for the average and peak transactions per second to the VA Profile API so that we can complete the ICD.

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/d598c550-a99d-4446-b9ef-0a1d6090c118)

**Comment by loripusey** [comment]
@stephenBarrs Reminder

**Comment by stephenBarrs** [comment]
from @charleystran 
> Looking at last week mon-thru friday we had a total of 214.39k for the week, at its peak usage was 5740 calls for a single hour, which is 96 calls a minute and 1.6 calls a second. That is all based on current usage, but I can’t say what the adoption rate is to extrapolate

[Slack Thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1655238379109339)

we estimated current rollout at about 15-20% and thus multiplied the estimate based on current usage to 8-10 calls per second. We will also reassess as we move forward and rollout continues.
