### ISSUE TITLE
Define a VSP code styleguide outline

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4221]
## User Story or Problem Statement

As an engineer contributing to VSP code, I need to have a handy style guide for coding best practices so I can adhere to a high standard of pull request.

This attempts to alleviate the problem of how we might improve the level of code quality and maintainability while reducing overall support efforts required. 

## Background

We have some [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering) which covers code review guidelines, specific tasks, on-boarding, communication norms, etc...However we don't have a single explicit styleguide for writing maintainable, performant `ruby` or `js`.

Having something like this would help as we could share it to contributors who might not be as familiar with the given language.

A large amount of the API code is uncommented, and this lack of documentation causes slowdowns when a dev explores the codebase. Comment hygiene is one topic we can cover. 

We should have styleguides for all major languages used in our stack (`ruby`, `js`)

## Acceptance Criteria
- [ ] Identify some styleguides as [examples](https://github.com/airbnb/ruby).
- [ ] Outline the VSP styleguide
- [ ] Ticket the work up to complete the guide

## Objectives or Key Results this is meant to further
- Support, Serviceability 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by timwright12** [comment]
I would pause this until we actually have "platform" code sectioned off. For now all we can do is enforce linting
