### ISSUE TITLE
Determine service Lighthouse is pulling claims status information from

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#42228]

**Comment by michelpmcdonald** [comment]
I'm not too sure about this one......who is after this info ?
Also, we would have to engage lighthouse, in theory, vets-api just make the call to Lighthouse, how they gather claim status is internal to their call.
That being said, their code is public, it's the vets-api\modules folder, so if someone is feelin froggy they could jump into that code and see if they can figure it out......
