### ISSUE TITLE
[Story] CT Rating System (Apply sample file headers to GIDS)

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#42243]
## Issue Description
Add process to take ratings CSV file and create a rating for each institution

## Acceptance Criteria
1) Brian is going to provide a CSV file with the ratings questions. - **Done**
2) Create the ability for Brian to update file into GIDS dashboard. - **In progress**
3) Add step to institution building process that creates the ratings. - **In progress**
4) Verify that it's in the payload - **In progress**

**Comment by MitchLivingstone** [comment]
Ready for staging. PR requested 08/08/2022.

**Comment by PJart** [comment]
working with Octo to look into failing tests, can not merge in branch until tests are passing

**Comment by MitchLivingstone** [comment]
Closed and complete
