### ISSUE TITLE
[Bug] [IE11] 10-10EZ Short Form - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#42256]
## What happened?
On **Staging Apply for VA health care (10-10EZ)** form, **Veteran Information** (birthplace) page, **Short-form alert** was missing.

## Specs:
- Device: Windows 10 PC
- Browser: IE11
- Test User _(if applicable)_: `vets.gov.user+228@gmail.com` (Colder)

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/apply/application/introduction
- Click **Sign in...** button, and sign-in as **`vets.gov.user+228@gmail.com`** (Colder).  [See [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for password]
- On **authenticated Apply for VA health care** page, click **Start... application**.
- On **Veteran Information** (personal) page, click **Continue**.
- On **Veteran Information** (birthplace) page, observe that **Short-form alert** is missing &mdash; a blank space is displayed instead.

### Screenshot
![image](https://user-images.githubusercontent.com/587583/171733843-79c0e5a6-3dfc-4d7c-9e81-2d93aa5783ae.png)

## Desired content/styling
- [ ] **Veteran Information** (birthplace) page: **Short-form alert** should be displayed. 
    ![image](https://user-images.githubusercontent.com/587583/171735372-efce094d-4bd6-47cb-9af3-8f967dab5899.png)

## Acceptance Criteria
[see **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by hdjustice** [comment]
Thank you @tlei123, we will chat about it and I will notate what we plan to do with this.  Thanks so much for catching it!

**Comment by lzapson** [comment]
@tlei123 In the steps to reproduce I think you meant sign-in as vets.gov.user+228@gmail.com

**Comment by tlei123** [comment]
> I think you meant sign-in as [vets.gov.user+228@gmail.com](mailto:vets.gov.user+228@gmail.com)

Thx, @lzapson !  Great catch!  Yes, and I just corrected it above in main description.

**Comment by tlei123** [comment]
@hdjustice , Closing this now...

I've seen similar IE11 alert-related bugs recurring after fixes.  It's probably not worth trying to fix &mdash; only to have it break again 'cuz IE11's no longer keeping up after EOL.

Feel free to re-Open if you think Lisa really should at least try.  It definitely wouldn't need to be high-priority.

cc @lzapson
