### ISSUE TITLE
Update feature flipper to percent of traffic

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4225]
As a developer, I want to incrementally increase the percentage of veterans who are able to see the VAOS opt-in banner on the scheduling page so that I can gradually roll the tool out.

AC
- [ ] VAOS not gated by whitelist
- [ ] VAOS opt-in banner percentage set to whatever level deemed initially acceptable

**Comment by saneshark** [comment]
Can we have a sync Monday with you, me, and Jeff about this? This is probably important part of roll-out strategy and might be super-ceded.

**Comment by lenaecb** [comment]
@saneshark - Given how we're rolling out MVP, this feels like it needs to be addressed, but perhaps it's already been? Mark showed me a screenshot of the feature flipper tool - https://api.va.gov/flipper/features/va_online_schedule

I don't have VA access so I can't login to this.

**Comment by saneshark** [comment]
@lenaecb is this ticket safe to close?
