### ISSUE TITLE
VFS User onboarding automation research

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#42257]
## What needs to be done?
We need to document the current process for new VA users getting access to tools, identify pain points with the current process, and find parts of the process that could be easily automated.

## Why does it need to happen?
So that we can better communicate the current process to onboarding users and start automating and improving parts of the process.

### Step 1: Gather information
- [x] Using existing documentation, list what tools users need to get access to and how they currently get access ([see Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1656701989098/5ffce934593034278a3e7bff3dfd55ce033915e5?sender=ubd9844c34b9b2bc7fae03486))
- [x] Talk to Shira Goodman (Governance Team) to learn about pain points in the current process ([see post here](https://dsva.slack.com/archives/CJRQ85PQB/p1657644422743159))
- [x] Meet with Governance and Infrastructure leads to discuss pain points
- [x] Create a [Confluence page](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2273607765/Findings+Tool+Access+Processes+Pain+Points) summarizing findings about pain points

### Step 2: Document current process
- [x] Create a diagram showing the current process for gaining access to tools (for both internal use and VFS users to see what tools are available and how to gain access)
- [x] Identify areas for automation

## When does it need to happen?
Step 1 by Jul 20
Step 2 by Aug 3

## Who should be involved?
@TPurple to gather pain points
@TPurple and @rbsingleton to draft diagram and work with @kjduensing and others to make it complete and accurate

## Acceptance criteria: what is the definition of done? What is the final output and what does that output need to include?

Done when: 
- [x] We have diagrammed the current processes in confluence
- [x] We have documented pain points with the current processes
- [x] We have documented a "common" list of tools that most people will need access to
- [x] We have listed automation opportunities within the current onboarding process in confluence (bonus points if they're rated by ease of automation!)
Report here: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2273607765/Findings+Tool+Access+Processes+Pain+Points

**Comment by kylesoskin** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools

https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member

**Comment by TPurple** [comment]
[Research plan here (#2)](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2228420687/Research+Plan+Integration+and+Onboarding)

**Comment by girldadmk** [comment]
@kjduensing can you follow up with diagrams?

**Comment by girldadmk** [comment]
@kjduensing can I include this in User Onboarding Research #40118 Epic?

**Comment by TPurple** [comment]
We met with Shira and Chase (Governance) as well as Jesse (Infrastructure) to discuss tool access processes and pain points

**Comment by TPurple** [comment]
The final report is here, along with proposed automations:
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2273607765/Findings+Tool+Access+Processes+Pain+Points
