### ISSUE TITLE
SOCKS Access instructions are confusing and don't properly match the intended anchor links

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-team#42272]
### Description

I click "Linux configuration guide" and it takes me back to the top of the page. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#InternaltoolsaccessviaSOCKSproxy-ConfiguringaccessonLinux

That anchor url should take me to the Linux configuration guide but it doesn't, instead it takes me to the top of the page which is very confusing.

**Comment by laucon** [comment]
I have updated the document so that now it is correct and there should be no issues. If you would like someone else to take a look before deploy, let me know. Otherwise, the work itself is done. The actual issue will be fixed on Tuesday after deploy.

**Comment by lianilychee** [comment]
@jcklpe for background on what Lauren means by "deploy" -- the Platform Content Team manually updates the Platform website twice a week (Tuesdays and Thursdays, appx 12 ET).  The fix that Lauren made last Thursday/Friday will go out tomorrow.

That the Platform website is following a deploy cadence is new as of Jan 2022, so I'm especially grateful for your and others' feedback thru tickets like these, as the team acclimates to _doing_ deploys and addressing customer challenges!
