### ISSUE TITLE
CT: Remove "Not available at this campus" content from Veterans Programs Section

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4227]
## User Story:
As a veteran, I only need to see the programs that are available at an institution when viewing a profile OR an informational message if there are no programs available so that I am provided with relevant information to my school research.

## Assumptions:
1. This is completed behind a flag so that it is only available in the staging environments and below.

## Acceptance Criteria:
1. The "Not available at this campus" column and related data is no longer displayed.
2. The "Available at this campus" header is no longer displayed.
3. If the are no programs available at a campus the following informational message is displayed: "Please contact the school or their military office directly for information on the Veteran programs they offer.".

## Supporting Artifacts:
1. 
<img width="987" alt="veteran_programs" src="https://user-images.githubusercontent.com/48260534/70801612-573db200-1d7d-11ea-9045-1352d1ad7d62.png">

2. [Mockup](https://bahdigital.invisionapp.com/share/R3IACBMBWFJ#/screens/296026785)
3. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/colmery-act-2019/design/content/profile-accordion-va-programs.md)

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/11349

**Comment by hughes-dustin** [comment]
branch: bah-4227
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11349

**Comment by delli-gatti-michael** [comment]
Changes are now in Staging
