### ISSUE TITLE
Documentation Review: Sidekiq Access

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42282]
## Description
As part of the [Console Services Documentation efforts](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38917) this document needs to be reviewed for correctness and updated as needed. This document will be archived in favor of the new Github Teams based Oauth solution that sits in front of Sidekiq UI

https://vfs.atlassian.net/wiki/spaces/VI/pages/926089332/Sidekiq+Access. 

## Acceptance Criteria
- [x] Document is reviewed for correctness
- [x] Document is updated as necessary
- [x] Archive Document

**Comment by LindseySaari** [comment]
Asked in [this thread](https://dsva.slack.com/archives/C01AS05BQ79/p1654265766316189) for the Sidekiq UI document to be archived

**Comment by npeterson54** [comment]
done
