### ISSUE TITLE
[bug] Certificate of Eligibility | LGY Service receiving inaccurate dataset

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#42284]
## What happened?
Application Dataset still not coming over to LGY correctly. Here is what is missing:
- Suffixes are missing when present - retested - failed
- “Still Own Ind” is always ‘N’ even if the Veteran has answered ‘Yes’ in the App (though it appears correctly under “Property Owned” at the bottom). - retested - failed

## Specs:
- Device: unknown
- Browser: unknown
- Test Users: 
vets.gov.user+56@gmail.com  
vets.gov.user+88@gmail.com  

## Acceptance Criteria
- [x] Suffixes appear when passed.
- [ ] “Still Own Ind” matches the response selected by the Veteran in the app.
- [x] Update the schema to allow the following formats: `11111` and `11111-1111`
- [x] Update the `prepare_form_data` method on the `vets-api` to correctly handle those suffixes, when included

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by scottymeyers** [comment]
For the suffix issue, it doesn't look like there is any inputs related to Suffix's in our UI, so we'll need to go ahead and add them.

For the _Still Own_ field, I've followed the data from our UI submission, through the API's Service layer and it looks like there _propertyOwned_ value being handled accurately and would be forwarded to LGY correctly. Perhaps a fix for this was addressed after this issue's creation? Screenshot Attached.

<img width="624" alt="Screen Shot 2022-06-13 at 3 15 41 PM" src="https://user-images.githubusercontent.com/969752/173428385-6d1b1008-69e7-4e38-8f5a-6fde4e5f055a.png">



<img width="624" alt="Screen Shot 2022-06-13 at 3 15 41 PM" src="https://user-images.githubusercontent.com/969752/173427967-c5f1ac14-bd28-487d-bdd1-d31b5edada6f.png">

**Comment by scottymeyers** [comment]
Spoke with Kelli and what we'll do for zip code suffixes is retain a single input for zip codes, but update the schema to allow the following formats:

1. `11111`
2. `11111-1111`

**Comment by Mottie** [comment]
Reopening to veriy “Still Own Ind” matches the response selected by the Veteran in the app.

**Comment by Mottie** [comment]
Verified that the `propertyOwned` form data is updating correctly and being passed to the server, but from reading through this ticket, I'm not sure that the `homeSellIndicator` should be the opposite of `propertyOwned`. If we have to, we could add another question to the form.
