### ISSUE TITLE
[Story] Adding For Profit Ownership Name - Front-end

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#42293]
## Issue Description
This story is to add For Profit Ownership Names to institutions cards to provide the end user further school information.  

The scope of this story is to update the front-end. 

## Acceptance Criteria
1. From the attached xls, import Institutions Name into GIDS
2. Display "Institutional Ownership: [Ownership Name] on each institutions details page [See screen shot]
3. The location to display this information should be under "Regional Accreditation", in the same module
4. The icon leading the text should be an office building:

![image.png](https://ima![Office Building Icon.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/786953b7-122a-4a92-9ba8-5b20a41a79e9)ges.zenhubusercontent.com/60e78c6b02152f0a04637267/bf1817a3-c9f7-4f82-b1ce-316ff2201d65)

Please reach out to Abe or Mitch if you have any questions. Thank you!

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/5f193330-5c8a-40cc-b4b7-c3f3471aedcd)

 [https://app.zenhub.com/files/133843125/2387689d-0eae-4173-af72-f8b7c0dda332/download](https://app.zenhub.com/files/133843125/2387689d-0eae-4173-af72-f8b7c0dda332/download)

**Comment by mrblanco1** [comment]
![Office Building Icon.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/6db8b443-fe4f-44a8-821a-d1b8fc3a8afd)

**Comment by mrblanco1** [comment]
[https://app.zenhub.com/files/133843125/708d0f5b-ab82-42ad-bde9-384f45524d7e/download](https://app.zenhub.com/files/133843125/708d0f5b-ab82-42ad-bde9-384f45524d7e/download)

**Comment by MitchLivingstone** [comment]
@SebVortex 
As a place holder, please use the "Careers hub icon" located on the Design page in place for the building. The building going through an approval process which can take up to a month before it's released.

https://design.va.gov/foundation/icons

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/963498f1-24f8-46a2-a5e3-f4d6c29e4fb3)

**Comment by MitchLivingstone** [comment]
An icon was selected by EDU for approval. When the approval for the icon is completed by the Platform team design, it can be added into the card. Thank you. 

07/14/2022

**Comment by MitchLivingstone** [comment]
**Update:** 07/20/2022
 
EDU have selected a building design that has been passed onto through the design team. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1018#issuecomment-1187692186

**Comment by MitchLivingstone** [comment]
Update: 07/22/2022
Please use the below building icon for the institutional ownership. 

https://fontawesome.com/v5/icons/building?s=solid

**Comment by dsrr47** [comment]
@MitchLivingstone  Will every institution have an Institution owner or should it only show for schools that do have them?

**Comment by MitchLivingstone** [comment]
@dsrr47 Only schools that show them.

**Comment by MitchLivingstone** [comment]
@dsrr47 Only schools that show them.

**Comment by MitchLivingstone** [comment]
In testing. Need to add code to the vets-api to be merged in.

**Comment by dsrr47** [comment]
There was an issue with the backend branch deployment and Im blocked from testing this until it is resolved.

**Comment by dsrr47** [comment]
Can be seen on staging for this institution here: 
https://staging.va.gov/education/gi-bill-comparison-tool/institution/21915164

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3527&group_by=cases:section_id&group_order=asc
Test case: [Adding For Profit Ownership Name - Front-end.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9427693/Adding.For.Profit.Ownership.Name.-.Front-end.xlsx)

**Comment by MitchLivingstone** [comment]
Patrick provided the link for Staging:
https://staging.va.gov/education/gi-bill-comparison-tool/institution/21915164

**Comment by MitchLivingstone** [comment]
Story has been approved for UAT. Please move to Production. This story will be updated with some added information in another story. 

Closed and completed on 08/29/2022

**Comment by MitchLivingstone** [comment]
UPDATE 09/15/2022: Story ownership names were added to GID which will allow the institutions to be utilized. 

Please remove all Prod flags and move to Production. @dsrr47

**Comment by MitchLivingstone** [comment]
Closed and completed.
