### ISSUE TITLE
FE update 10-10EZ contact page with new content

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#42291]
## User story
As a Veteran I want to make an active decision about what contact information I provide 

## Overview
Please add this content above the form fields- no other design changes should be made

## Content
Adding your email and phone number is optional. But this information helps us contact you faster if we need to follow up with you about your application. If you don't add this information, we'll use your address to contact you by mail. 
**Note:** We'll always mail you a copy of our decision on your application for your records.

 ![Screen Shot 2022-06-03 at 10.48.29 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/11fbbc51-5ce2-4374-9731-3d3e26b24b89)

**Comment by longmd** [comment]
@Dene-human , just thinking on this... how should the text display with regards to the short form alert and the prefill message that displays for authenticated users? Should the text go on top of both alerts, split them, or go underneath?

**Comment by Dene-human** [comment]
Thanks for asking @longmd I've put together a [quick mockup](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ka7xgxr), let me know if it answers your questions or not!

**Comment by longmd** [comment]
@Dene-human , yup!! That works for me. Easy enough.
