### ISSUE TITLE
AWS access for Peter Hill

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#42290]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Peter Hill

### Your Email

peter.hill@oddball.io

### Your Team, Role, and Company

Quality Assurance Standards Team Lead, Oddball

### Product Manager (PM) name and email

Joe Tice - joe.tice@oddball.io

### Product Owner (PO) name and email

Mike Chelen - michael.chelen@va.gov

### Desired AWS Access

Our team has been tasked with creating synthetic monitors that target production VA.gov. Part of our definition of done for the initiative is to store the monitors as code in Terraform to be published to DataDog. Please grant all privileges required to complete the workflow of creating synthetic monitors as code in Terraform. The exact scope of the privileges required to complete this workflow is not immediately clear but includes at least: read-write DynamoDB, read cms_datadog_api_key-iYTsP9, and read /cms/prod/drupal_api_users/datadog_api/password. There may be more privileges required to run `terraform plan` which we believe to be required for contributing a synthetic monitor to Terraform.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
For AWS Access
User: Peter Hill
COR: Eunice Garcia
VOR: Amber Malcolm
Approval needed: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
Admin level: no
Approvers will check with your VOR on your EQIP status.

**Comment by kjduensing** [comment]
@td-usds this appears to be a request for additional privileges, not an onboarding request - do you approve?

(Original AWS access request onboarding request: https://github.com/department-of-veterans-affairs/devops/pull/6295)

**Comment by pjhill** [comment]
Hey, sorry, to be clear, this request was on behalf of Ryan Johnson -- rjohnson2011. I was attempting to request the access on his behalf due to some nervousness about process based on an earlier snafu with regard to AWS privileges.

I (Peter Hill) do _not_ need additional privileges in AWS.

**Comment by td-usds** [comment]
@pjhill is it accurate that no action is needed for this request then (i.e. it can be closed)?

**Comment by pjhill** [comment]
We are currently working around Ryan Johnson's lack of access. However, it would be good if in the future Ryan Johnson and other engineers on our team could be added to a group/team with the appropriate privileges for creating and maintaining monitors in Terraform.

**Comment by pjhill** [comment]
This request can be closed with no additional action taken. Thank you!
