### ISSUE TITLE
Ensure redirect_uri query is approved/retained before redirect

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#42309]

**Comment by joeniquette** [comment]
@joeniquette to schedule call for this

**Comment by joeniquette** [comment]
@AGarcia-Clarity Can you please add in a description for what is needed here?

**Comment by AGarcia-Clarity** [comment]
Yeah I believe this is all good to go. The redirect_uri is already being parsed by the BE & entered in the Login.gov Dashboard.
