### ISSUE TITLE
Update 10-10 EZ/CG source of truth

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#42305]
## Description

This is part of the ongoing process to update the EZ/CG sources of truth when updates are pushed to production.

- The 1010EZ [source of truth document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-copy.md), as well as the [1010EZ flow Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923531828/474bfdde942c22a0df26ad416a0b23e36b834d4a?sender=u8a90be72499ecb4354e14700), needs to be updated to reflect recent design and content  changes.
- The 1010CG source of truth document, and the [1010CG Mural flow board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923499561/47a15bbef931c358b80a077c7085ede9b26dc25e?sender=u8a90be72499ecb4354e14700), need to be updated to reflect recent design and content changes.

## 10-10EZ Tasks

- [x] Update the place of birth design/content
- [x] Update Medicare part A question design/content
- [ ] Updated Medicare claim number design/content
- [ ] Update submission page confirmation/error design/content

## 10-10CG Tasks

- [x] Update address pre-fill checkbox design/content
- [ ] Update each page that has email encouragement content
- [ ] Update submission page confirmation/error design/content

**Comment by markfallows** [comment]
Closing.  New tickets have superseded this one.
