### ISSUE TITLE
Update 10-10EZ Confirmation screen content

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#42304]
## User story
As a Veteran applying for health care, I would like to know accurately know what to expect once my application is submitted.

## Acceptance criteria
- [ ] Update all content that is noted in the fuschia box in the image below
     - Including removal of the lines where we state an email will be sent
- [ ] We noticed that the "titles" within the bottom content are styled like H3 but are treated like an H2 class. I want to make sure this continues when this section is updated. It's important for accessibility.

## References 
- Content ([sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxvza3r))

![Screen Shot 2022-06-03 at 12.15.10 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/022cafdd-41d3-4a43-b36d-08c1ba7df2d2)

**Comment by Dene-human** [comment]
wow I didn't know that! Would you mind sending me a screenshot of the whole page?

**Comment by longmd** [comment]
@Dene-human , here ya go... 

![Screen Shot 2022-06-14 at 2 11 13 PM](https://user-images.githubusercontent.com/6738544/173660034-ede320cf-3bbe-4180-8c3d-7200d6cb67cf.png)

**Comment by Dene-human** [comment]
@hdjustice I've asked Matt to leave the email part in, but can we please add this to the agenda items to confirm with Tarsha that this is still true.

**Comment by hdjustice** [comment]
@Dene-human @longmd - Added to the agenda for next week's meeting (6/22)

**Comment by longmd** [comment]
Easy enough. I will pull that out and we'll be good to go with the rest of the provided content.

**Comment by hdjustice** [comment]
Tarsha just responded with the suggestion from HEC team.  Let me know what we think and I can respond and add you to the email.

> My leadership would like to change the language on the Confirmation page after application is submitted to the following:
> 
> **How long will it take VA to determine my eligible for VA health care?
> 
> We’ll contact you if we:
> 
> - Successfully receive and process your application, or
> - If we need you to provide more information or documents
>  
> If we haven’t contacted you within a week after you submitted your application
> 
> Please don’t apply again.  Instead, please call our toll-free hotline at 877-222-VETS (8387).  We’re here Monday through Friday, 8:00 am to 8:00 pm ET.**

**Comment by longmd** [comment]
That works for me. Kind of takes pieces of what was the email message and mixes it with what else was there. @Dene-human , what're your thoughts?

**Comment by Dene-human** [comment]
_This is what I'd like:_

### How long will it take VA to make a decision on my application?

We usually decide on applications within **1 week.**

We’ll contact you if we:

- Successfully receive and process your application, **or**
- If we need you to provide more information or documents

**If we haven’t contacted you within a week after you submitted your application**

Please don’t apply again. Instead, please call our toll-free hotline at [877-222-8387]. We’re here Monday through Friday, 8:00 a.m.to 8:00 p.m. ET.



> We’ll contact you if we:

Ideally I would like this to say "We'll call you if..." because it sets way better expectations, but until all that is confirmed I guess we can settle on contact.

> How long will it take VA to determine my eligible for VA health care?

This is not clear, so I'd like to leave it how it is.
