### ISSUE TITLE
Combined Debt Portal [CDP] PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#42301]
## Product/Feature summary

Providing Veterans with a singular combined experience where they can see all of their financial matters in one place. Including VA Debts, debt letters, and health care copay statements.

-  [Combined Debt Portal [CDP] Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/product_outline.md)
- [Epic #36131](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/36131)
- [User Flow](https://app.mural.co/invitation/mural/vsa8243/1645453970389?sender=riley5075&key=b9051645-ff1a-4307-a1df-bd9622b9ca31)
- [Design Prototype](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages//simulate/sitemap?mode=i)

## Product-team SMEs

*Design/Research:* Riley Orr, Megan Gayle
*Content/IA:* Danielle Theirry, Mikki Northius
*Front-end:* Andrew Rodiek, Brandyn Sullins
*Back-end:* Scott James
*QA:* Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

[Use Cases Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Added product-specific label (if any)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod environment].
- [ ] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

---
**See also**: Relevant [PTEMS-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

**Comment by tlei123** [comment]
@denisecoveyduc [cc @rileyorr @Dr-Pongo], thanks much for providing the Use Cases! I have some follow-up questions:

- (1) **[Use Case A](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-a----veteran-only-has-a-debt)**: Can you confirm test-user **81 (Travis)** the correct one to use?
  - The case shares the same test-user w/ [Use Case E](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-e---veteran-has-both-a-copay-bill-and-debt) but that can't be right.
  - On Debt-details page, I saw two Debts but no alert for no-copay-bill.[^1]
- (2) [Use Case B](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-b---veteran-only-has-a-copay-bill): Can you confirm test-user **80 (Oscar)** is the correct one to use?
  - On Debt-details page, I saw an API **error-message** "We can't access your debt records right now." [See screenshot below.]
- (3) **[Use Case C](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-c---veteran-has-neither-a-copay-bill-nor-debt)**: Can you confirm test-user **56 (Shirley)** is the correct one to use?
  - On Debt-details page, I saw the same **error-message** as for 80 (Oscar) above.
- (4) **[Use Case D](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-d---veteran-is-not-enrolled-in-healthcare)**: Can you confirm test-user **3 (Kenneth)** is the correct one to use? I saw the same error-message as for 80 (Oscar) above.
  - On Debt-details page, I saw the same **error-message** as for 80 (Oscar) above.
- (5) **[Use Case E](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-e---veteran-has-both-a-copay-bill-and-debt)**: Do we have a test-user with both a Copay-bill and a VA-debt?
  - The case shares the same 81 (Travis) w/ [Use Case A](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-a----veteran-only-has-a-debt) but that can't be right.

### API-Error screenshot
Occurred on Details page for test-users 80, 56, & 3:
<img width="661" alt="Screen Shot 2022-06-04 at 4 12 38 PM" src="https://user-images.githubusercontent.com/587583/172028392-d3762b38-f52a-496e-a8e1-4fc0af78aba7.png">




[^1]: Not sure if this is relevant, but `medicalCopaysZeroDebt` feature-flag appears to be false (disabled) in Staging.

**Comment by denisecoveyduc** [comment]
@tlei123 Just wanted to confirm, I believe we are able to close this issue now?

**Comment by tlei123** [comment]
Yes, Closing now.
