### ISSUE TITLE
Break Out Ansible Module 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4230]
## User Story
As a VSP Ops Member, I need to have one place for Ansible to live outside of the DevOps repo so I can have a clear understanding of the versions in use and have a shared resource with others who use it.

## Goal
_Separate Ansible Module repo_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Current plan is to redo most of this stuff. I'm going to close this ticket as it's just noise at this point around the project as a whole.
