### ISSUE TITLE
Cleanup job that removes Sessions that are no longer valid

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#42315]
# Description
Job that runs at a set time to remove expired sessions

# Acceptance Criteria
- [ ] Cleanup job schedule set
- [ ] Job runs at set interval
- [ ] Removes expired sessions

**Comment by bosawt** [comment]
On staging can confirm that no OAuthSessions exist before today, so the cleanup job must have been run
