### ISSUE TITLE
client_id for web and mobile

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#42313]
# Description
Utilized by sign-in controller.  Web and Mobile need to be selectable to determine how tokens are returned.

# Acceptance Criteria
- [ ] 
- [ ]

**Comment by bosawt** [comment]
Will be completed with : https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/vets-api/10011
