### ISSUE TITLE
[Story] Adding Ownership Name & Possibly Chief Officer - Backend - vets-api

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#42330]
## Issue Description
Ownership or Chief officer names will be added to the for-profit schools list to provide the end user further school information.  

The scope of this story is to update the back-end - vets-api

## Acceptance Criteria
When for-profit school are selected, Ownership or Chief officer information will be populated for selected for-profit schools.

**Comment by SebVortex** [comment]
Confirmed with @PJart this was already merged into the backend.

**Comment by MitchLivingstone** [comment]
Closed
