### ISSUE TITLE
[Research] My VA - Payment Info: Update Conversation Guide to Include Historical Debt Questions

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42332]
## Background
Based on our audit we want to determine if including historical debt information on My VA will be helpful for our users

## Tasks
- [ ] Update conversation guide to include questions around historical debt

## Acceptance Criteria
- [ ] Conversation guide is updated with new questions about historical debt

**Comment by ajakabcin** [comment]
No longer needed
