### ISSUE TITLE
[Story] Adding Ownership Name - Backend - GIDS

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#42331]
## Issue Description
Ownership or Chief officer names will be added to the for-profit schools list to provide the end user further school information.  

The scope of this story is to update the back-end - GIDS.

## Acceptance Criteria
When for-profit school are selected, Ownership or Chief officer information will be populated for selected for-profit schools.

**Comment by MitchLivingstone** [comment]
Will be moved to In progress when files are received from EDU,

**Comment by SebVortex** [comment]
Issue is addressed by [42330](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/42330)

**Comment by MitchLivingstone** [comment]
PR requested and found issue with local branch. Patrick is working on fixing branch and getting the build to run.

**Comment by MitchLivingstone** [comment]
Follow up with PR. 08/22/2022

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3543&group_by=cases:section_id&group_order=asc
Test case:
[https://app.zenhub.com/files/133843125/66b9548d-84df-47fc-91d5-95493b8450bd/download](https://app.zenhub.com/files/133843125/66b9548d-84df-47fc-91d5-95493b8450bd/download)

**Comment by MitchLivingstone** [comment]
Update 09/15/2022: UAT Approved Please remove all flags move to Prod.

**Comment by MitchLivingstone** [comment]
Closed and completed.
