### ISSUE TITLE
[FE] No vertical lines on Veteran reviewing information pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42344]
## Description
There should be no vertical line decoration on all pages where Veterans are reviewing their information. E.g., contact information, emergency contact information and next of kin. Instead, there should be a horizontal divider.  

**This includes both Check-in and Pre-Check-in.**

Designers need to confirm whether this is correct or if this direction was specific to "edit" wireframes. 

## Wireframes
TBD

## Tasks
- [ ] [FE] Make frontend changes per wireframe on **BOTH CHECK-IN AND PRE-CHECK-IN**

## Acceptance Criteria
- [ ] Frontend changes have been made

**Comment by loripusey** [comment]
@zach-park I need you to confirm if horizontal divider was specific to "edit" feature or if it is to be used for "non edit" as well. Can you please attach the correct wireframes to this ticket in the Wireframes section?
cc: @benbrasso-agile6

**Comment by brianseek** [comment]
@benbrasso-agile6 This is ready for validation. See screenshots of pre-check-in below. This is the same on day of check-in. Let me know if you want to see screenshots from that app too or if you want to see a demo over zoom.
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (18).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/4dbfa8c1-25d1-45ab-bb4f-c3bd8a903f5b)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (19).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/3f6af079-615f-4711-8365-5c7567589b8f)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (20).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/cdb2f829-4746-497d-a47a-2c9021c4e9a8)

**Comment by loripusey** [comment]
Looks good, line gone! Thanks!

**Comment by zach-park** [comment]
LGTM. Thank you! @brianseek (Cc: @benbrasso-agile6 @kristenmcconnell @loripusey )

**Comment by brianseek** [comment]
closing with validation
