### ISSUE TITLE
[FE] Accordion on Confirmation Page for Pre-Check-in Should have "Expand All"

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42349]
## Description
This is related to pre-check-in.  On the "confirmation" page, accordions should use the default design component. E.g., the expected result should be that the "expand all" functionality is present. Engineers should ensure that we can still support having an individual accordion expanded on page load while using this component.  

## Tasks
- [ ] Modify according to that the "expand all" functionality is present

**Comment by brianseek** [comment]
This is ready for review. See gif for action:
![expand-all.gif](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/73ba92a3-1891-468b-b429-b89bab9be9a6)

**Comment by loripusey** [comment]
Looks good to me, as soon as @zach-park concurs, it can be closed.

**Comment by zach-park** [comment]
LGTM. Thank you!
