### ISSUE TITLE
Pre-Warm Image Styles for CMS Content Export System

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#4234]
The default D8 behavior is that Image Style derivatives are only generated when requested for the first time. 

The new CMS Export system needs all the image styles to be on disk immediately during the "publish" operation so that they can be tarred right afterwards and made available for build consumption. 

Acceptance Criteria:
1. Pre-Warm all currently used Image Styles
_1_1_SQUARE_MEDIUM_THUMBNAIL
_21MEDIUMTHUMBNAIL
_23MEDIUMTHUMBNAIL
_32MEDIUMTHUMBNAIL
_72MEDIUMTHUMBNAIL
LARGE
https://www.drupal.org/project/image_style_warmer 

1. ITOK support disabled
https://drupal.stackexchange.com/questions/215165/how-do-i-remove-the-itok-token-from-the-image-urls/215168#215168

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/704
Elijah Lynn  ​Just needs the manual steps performed after release tomorrow

**Comment by ElijahLynn** [comment]
Just performed the one-time only manual step. All image uploads in PROD CMS now pre-generate all image derivatives/styles on the upload event, whereas they were only generated on demand in the past. 

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/704#issuecomment-586525981
