### ISSUE TITLE
[FE] Fix Yes and No Button Styling

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42346]
## Description
This is related to pre-check-in and check-in.  On all pages where Veterans are reviewing their information, e.g., contact information, emergency contact information and next of kin, Yes button should be "primary," e.g., blue background, and No button should be "secondary," e.g., white background. 

## Wireframes
TBD

## Tasks
- [ ] Change necessary buttons to "primary"

**Comment by loripusey** [comment]
@zach-park I need you to verify if the problem identified in this ticket is correct.
@benbrasso-agile6

**Comment by brianseek** [comment]
This is ready for review. See screenshots:
![localhost_3001_health-care_appointment-pre-check-in_emergency-contact (1).png](https://ima![localhost_3001_health-care_appointment-pre-check-in_emergency-contact.png](https://ima![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (17).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/66e17258-cb84-4be3-b781-1cb4f4e8c431)ges.zenhubusercontent.com/61523b5b9d354750f04823db/ca0d9920-fb01-426e-a809-3debeb50c974)ges.zenhubusercontent.com/61523b5b9d354750f04823db/ffcff478-5b2c-4238-a414-36b796008368)

**Comment by loripusey** [comment]
@brianseek Do the changes appear in both Check-in and Pre-Check-in?

**Comment by benbrasso-agile6** [comment]
I was about to ask what Lori asked. Looks good though. @zach-park

**Comment by brianseek** [comment]
Oh good question @loripusey and @benbrasso-agile6, yes the changes are in both apps.

**Comment by zach-park** [comment]
LGTM. Thank you!
