### ISSUE TITLE
[FE] Update Styling on Confirmation Page for Check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42352]
## Description 
This is related to check-in.  The "confirmation" page for check-in styling needs to be updated based on most recent sketch file. E.g., updates include new text for h1, information on page displayed in different order, etc. 

## Wireframes

https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/L03dRM3

## Tasks
- [ ] [FE] Make styling change

**Comment by benbrasso-agile6** [comment]
@ytsaoca has the sketch files and screenshots that need to be added to this ticket

**Comment by acrollet** [comment]
@ytsaoca could you add wireframes to this ticket when you get a chance? thanks! :-)

**Comment by ytsaoca** [comment]
This is the current wireframe https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/L03dRM3

**Comment by brdunfield** [comment]
Screenshot for validation:
![Screen Shot 2022-06-22 at 12.28.27 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/e24d08a7-9dbb-432c-af50-51e7e602a325)

**Comment by ytsaoca** [comment]
@brdunfield Looks good!
