### ISSUE TITLE
[FE] Change Styling on Too Many Attempts Page for BOTH PRE-CHECK-IN AND CHECK-IN

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42351]
## Description
This is related to pre-check-in and check-in.  After the 3rd unsuccessful attempt of verifying your identity, the message that appears needs to appear within the red background with an exclamation point. Currently, the message appears in a blue background. 

This applies to the 3rd attempt for **BOTH PRE-CHECK-IN AND CHECK-IN**.

## Wireframe
- This is an example of the styling (ignore the content) but needs to be done for **BOTH PRE-CHECK-IN AND CHECK-IN**.
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/4bb5d761-2d0b-4f59-b64b-4ba3a45f9f05)

## Tasks
- [ ] Make the desired change

**Comment by brdunfield** [comment]
Content change / question. The content "You can still check-in with your phone on the day of your appointment" seems like it only really works for pre-check-in. For check-in, I've modified the box to use an existing string in the app ("Check-in with a staff member"). See screenshot below
![Screen Shot 2022-06-16 at 2.51.18 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/98c69e80-5faf-41fa-9cc4-8b999b55bec3)
