### ISSUE TITLE
[FE] Add Need Help Information on Confirmation Page for Pre-Check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42350]
## Description
This is related to pre-check-in. On the "confirmation" pages, the "Need help?" information at the bottom of the page is not present. 

## Tasks
- [ ] Add "Need Help" information to the confirmation pages

**Comment by loripusey** [comment]
@niradatta1 Can we confirm if this information is needed on this page?
@benbrasso-agile6

**Comment by niradatta1** [comment]
@brianseek confirming we need to add "need help" on this page. We can use the same "need help" from the other pages in the pre-check-in flow. 'cc @benbrasso-agile6 @zach-park

**Comment by brianseek** [comment]
Validated via slack, closing ticket: https://dsva.slack.com/archives/C02GXKL8WM6/p1655934042654729
