### ISSUE TITLE
Analytics edge case KPI dashboard request for Benefits 2 - Debt Portal

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#42361]
# Request an Edge Case KPI Dashboard

## What this form is for

Use this ticket template to request a new edge case KPI dashboard on Domo for your product. Edge case dashboards are for products that fall outside of the scope of our standardized KPI dashboards (Forms, Content, and Search).

If you are unsure what type of dashboard your product qualifies for, please check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739) on Domo.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. Please note that these dashboards will require additional data and design discovery and will take additional time to deliver. You can also reach out for updates on this ticket.

## Instructions for the VFS team

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. For edge cases, we also ask for product outlines or other resources that will help us understand success for your product and define metrics: 

- [x] Make a copy of [this Google Sheet](https://docs.google.com/spreadsheets/d/1TSynjEUrOrm_HfLxb2NAPDXxnn7wyy1bSEb2RruC67Q/edit#gid=0) (or download Excel version).
  - [x] Fill out product information basics.
  - [ ] If a part of your product involves any sort of linear process/funnel for which you want to be able to measure conversions, please include it in the "Forms" tab of the template.
  - [ ] All other pages associated with your product for which you'd want to track visits and engagement should be added to the "Content" tab.
- [ ] Link to your completed spreadsheet here:_(Will attach it below)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it.
- [x] Answer the questions in the **VFS-provided information** section below.
- [x] Add links to the **VFS-provided information** section below.
- [ ] Add your team label to this ticket to follow its progress.

### Product questions

- The Debt Portal launched on January 4, 2021. Dashboard is a first generation dashboard and we would like to update it to the newer dashboard. If we can mirror it to the existing dashboard that would be great! Are you able to leverage that dashboard for the urls needed?

1. **What does your team consider a completed task?** I don't fully understand this question. The debt portal gives Veterans who have incurred a debt with the VA a place on VA.gov that will act both as a single landing page that explains the process of debt management at the VA, as well as the ability to be notified when new communications about debt are added to their file so they can view them on VA.gov after logging in.
2. **Who is your product's main user base?** Veterans
3. **Why does your product require an edge case?** Has a combination of pages and events across the portal that we are tracking.
4. **Does this product currently have a Domo dashboard?** Yes but it is a first generation dashboards so needs to be updated. Here is the link: https://va-gov.domo.com/page/74130670

### Product resources

- The Debt Portal launched on January 4, 2021. Dashboard is a first generation dashboard and we would like to update it to the newer dashboard.
- Additional resources for reference:
  - [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/new%20product_outline.md)
  - [GH Product Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp)
  - [First Generation Domo Dashboard](https://va-gov.domo.com/page/74130670)

**Additional info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards.
- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request it here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by chloedotbrown** [comment]
Closing ticket - have pasted resources from ticket in #42360, where work will continue.
