### ISSUE TITLE
Publish Human Readable List for Governance Team Use Case

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#42395]
# Description
In order to support the Governance team's use case, this Confluence page version will need to contain the following:

1.  Orienting text for the Governance team, based on the text and formatting located [on this page](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview)
2.  Add an additional note saying "Please Note: Changes made to this page will NOT be saved. To make changes to your product's listing, go here." (This will direct them to the full product list page -which is not created yet)
3.  A table of the product list limited the to attributes on [the Governance team page] (https://vfs.atlassian.net/wiki/spaces/VAProducts/overview)

**Additional Feature:** Output of the page is automated to occur when the JSON version is updated

# Acceptance Criteria
- [ ] Having the opening portion of the page properly formatted
- [ ] The table comes through with the appropriate columns
- [ ] The automation works as intended

**Comment by rsmithadhoc** [comment]
Started a [draft PR ](https://github.com/department-of-veterans-affairs/product-directory/pull/280) for this. 
- Functionality to publish to multiple pages, add content above the table, and only show certain columns is in place. 
- Some wrap-up to make sure it works on the full list if certain configuration options are missing/empty. Plus fixing up/adding unit tests.

**Comment by rsmithadhoc** [comment]
PRs out for review:
- https://github.com/department-of-veterans-affairs/product-directory/pull/279 (unrelated, a QoL improvement)
- https://github.com/department-of-veterans-affairs/product-directory/pull/280

**Comment by pjhill** [comment]
Nice, this looks awesome!
