### ISSUE TITLE
Create Documentation "How to Create Synthetic Monitors and Store them in Terraform"

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#42398]
# Description
Use the "How-to" template in Confluence to create a new document that describes the process of creating synthetic monitors in DataDog, exporting the monitors with `terraformer`, and storing them as code in the `devops` Terraform environment.

# Acceptance Criteria
- [x] A document following the "how-to" template available in Confluence is available in [our Confluence space](https://vfs.atlassian.net/wiki/spaces/TTT/overview)
- [x] The document describes a step-by-step process by which members of our team or members of other Platform teams can create a synthetic monitor and store it as code in Terraform
- [x] The document describes the explicit permission required to be able to store synthetic monitors in the Platform's Terraform environment

**Comment by rbeckwith-oddball** [comment]
I'm going to have to step through each permission that is necessary for the terraform code to run, so I'll continue to add them to the Confluence page.

**Comment by pjhill** [comment]
Document updates completed and updated for use with the new instance of Datadog.
