### ISSUE TITLE
Create a Day Three actionable meeting format

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#424]
Goal is to have an actionable meeting on day three where team can leave with direction, depending on their use case and implementation details.

**Comment by 1Copenut** [comment]
* What do we need to know in advance?
* What does the onboarding team need to do in advance?
  * What code / views do they want to share
  * Need Zoom access?
* Users
* Use cases
* Where does code live
* API involved?
  * Lots of sub-questions
* Finding out in-depth, about the product, what teams are brining onboard
  * Designs, where are these at?
  * Where are they at with 508
  * What do teams have now?
  * What do teams intend to do going forward
* Discover what we can, and discussing strategy
* Plan implementation around what we've found on day three
* Start gathering epics
  * Strategize the logical fault lines and epic buckets
  * Presentation of this meeting

**Comment by 1Copenut** [comment]
PR up here: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/20

**Comment by emilywaggoner** [comment]
Slide deck for this is here: https://docs.google.com/presentation/d/1-_34N7WdnQKH4bzyFnVaZl_dcxGEwYThDAkDIH7b0W8/edit#slide=id.g5df1fbe9dd_0_6

**Comment by andreahewitt-odd** [comment]
@smoonpeyes Can you add this deck to github?

**Comment by smoonpeyes** [comment]
Presentation added: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/templates/Discovery-and-Logistics-Workshop.pptx
