### ISSUE TITLE
[FE] My VA Audit UX Improvements: LOA3 Design Updates to Full Page

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42408]
## Background
Based on our My VA audit we determined that for LOA3 users we want to always show all sections. This would mean removing the conditional logic that dictates when to show certain sections. Angela will be updating designs for each individual section so we will include her designs in this ticket later. Showing all sections always includes 1.) Before they have applied for benefits 2.)when they have benefit applications in progress 

## Tasks
- [ ] Update code for LOA3 users to see all sections always
- [ ] Validate

## Acceptance Criteria
- [ ]  LOA3 users see all sections always

**Comment by ericasauv09** [comment]
Change this to a FE ticket to implement the coding work for this - design will be covered in other sections.

**Comment by ajakabcin** [comment]
Closing - no longer needed. Logic to always show all sections for LOA3 users is incorporated into individual section update tickets.
