### ISSUE TITLE
SOCKS access for Kyle MacMillan

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/va.gov-team#42409]
### Your Name

Kyle MacMillan

### Your Email

kyle.macmillan@oddball.io

### Your Role and Team

Tech Lead VA Notify

### Product Manager (PM) name and email

Melanie Jones melanie.jones@oddball.io

### Product Owner (PO) name and email

Beverly Nelson beverly.nelson@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+Y73QPZFqn07Q+XRl3bbq/6ArrsqJ5EEQxdPmv9wJlfIpBy0x6ca0orMb5sHs+OA4uGiTcWrAgV+KCG8xalWFcP3nIPsp8QxOBKl7nujLGcUpivBXW6M3xbPlqYic9tTGeqvL/ANDSEH+w/0l1CdbC/MquZX2DuvmWXo7Ns+SaDFY6kGqqCHqQwa1pgeCWVksQ5blUiC4L6nMNFYK1+p4YYQ2ZbPFCvj3AXQt6a/+KS+n9Bwmy3PL96TReaQDLE4kgxZMo5nz2Jp7RbUrg86bH6QacMqG0SkpO1rijM8oX6TrjS5u+YtXVl9RC6wYGexaYUBds56fiuW/gRE8ooqhpinq3+UX1ih7sLMPgI3WU5TMWd9fLyqX2EEgm1BTd/6W+h05xn4MENfEjgooqpqA0mWSwwkb/lWo2CUMw4HSQfm9uqIfn8/MvWMMPemtjtHujq1vACvdZBT+iQobNQ9hd0TN2S7e0n5wT7+OQP/Ncj7Jfq9e10M7j4ButjmpaIM=

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Hi @k-macmillan. We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with [this platform orientation guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). If you're not newly joining the team, please reach out to your PM or PO for help.

Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by k-macmillan** [comment]
@mjones-oddball @bevnobev 
Would you mind giving me a hand with the roster issue please?

Thank you!

**Comment by bevnobev** [comment]
Hi @kjduensing I'm the VA Notify PO.  Kyle has been on my team since Feb 2022.  How can I help expedite this?

**Comment by mjones-oddball** [comment]
@kjduensing Hi this is a fairly urgent technical blocker for our team as we have an integration enhancement we need to test with va.gov built and pending testing. I see there may be housekeeping items missing for our team but VA Notify itself is not new. To echo what Beverly said, how can we expedite this and work toward adding to your process as time permits? CC @Eallan919

**Comment by mjones-oddball** [comment]
CC @zlaw for visibility

**Comment by oseasmoran73** [comment]
Replied in Slack channel, but posting on here for visibility and ticket tracking purposes

> You can open a ticket in [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) using support bot and assign to Collab Cycle. They will be the ones to add to the roster and hopefully can expedite so we can grant SOCKS access

**Comment by bevnobev** [comment]
Thanks @oseasmoran73 I opened a support ticket is slack

**Comment by rmtolmach** [comment]
Not sure this is the fastest way, but if you follow the link @kjduensing posted and click on [Directions for new VFS team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html#Guidancefornewteamsandteammembers-NewVFSTeammembers), the workflow shows that once a platform orientation ticket is opened, the user will be added to the VFS roster. 

Here's a direct link to the platform orientation template: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D

**Comment by kjduensing** [comment]
Found @k-macmillan in the VFS team roster.

**Comment by kjduensing** [comment]
@k-macmillan - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html). Thanks for your patience.
