### ISSUE TITLE
Certificate of Eligibility Ops Template

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#42400]
### Description

I received a request to fill out an OPs template for the **Certificate of Eligibility** service, see here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34077

I'll comment below with what I was able to put together. Hopefully this is the correct location to share this document, and if now, perhaps you could let me the correct location for it!

**Comment by lianilychee** [comment]
Thanks for this, @scottymeyers !  I'm re-routing this certificate of eligiblity to the Platform Operations (aka Platform Infrastructure) team.

@jhouse-solvd @ph-One , passing to you two to prioritize as you see fit.

**Comment by jhouse-solvd** [comment]
@lianilychee - Thank you. We'll take a look!

**Comment by jbritt1** [comment]
Added documentation to the Confluence space that the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/?internal-user-opt-out=true) is built from. Updates there usually roll out on Tuesday and Thursday at noon ET. Will leave this open until then to ensure everything happens as desired.

**Comment by jbritt1** [comment]
This new doc should show as a child page under https://depo-platform-documentation.scrollhelp.site/developer-docs/external-service-integrations after noon ET tomorrow.

**Comment by jbritt1** [comment]
Seems my most recent knowledge of the Platform Website update deployment may be incorrect. This was actually published yesterday according to https://dsva.slack.com/archives/C01AS05BQ79/p1663013647891309 and can be seen in the live site at this time: https://depo-platform-documentation.scrollhelp.site/developer-docs/certificate-of-eligibility-coe. Thanks @scottymeyers for getting this over to us and apologies for the delay. Closing.
