### ISSUE TITLE
Documentation Review: Personal Identifiable Information (PII) guidelines

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42418]
## Description
As part of the [Console Services Documentation efforts](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38917) this document needs to be reviewed for correctness and updated as needed.

https://vfs.atlassian.net/wiki/spaces/pilot/pages/894271679/Personal+Identifiable+Information+PII+guidelines

Added a link for [Sensitive Documenation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md), which was referenced in this doc.

## Acceptance Criteria
- [x] Document is reviewed for correctness
- [x] Document is updated as necessary

**Comment by RachalCassity** [comment]
This document has been reviewed.
