### ISSUE TITLE
Copy edit of travel pay pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#42416]
## What's needed

We made changes to the main travel page to simplify it and move more information into R&S (the "how to file your travel pay claim online" page).

Before publishing, we need a copy edit of these 2 pages. SMEs have reviewed this content so need a light copy edit on this. 
- The [main VA.gov travel pay](http://preview-prod.vfs.va.gov/preview?nodeId=2431) with changes to simplify the page
- A new draft resources and support page on [how to file your travel pay claim online](http://preview-prod.vfs.va.gov/preview?nodeId=19367)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here are the travel pay pages we need copy edits on. Thanks!

**Comment by megzehn** [comment]
These are both reviewed and published!  

FYI:  This is a NEW R&S page, so @RLHecht would you mind double checking that I didn't miss any steps?

**Comment by DanielleThierryUSDSVA** [comment]
Yay! Thank you, @megzehn!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket!
