### ISSUE TITLE
SOCKS access for Alexander (Evan) Parish

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/va.gov-team#42424]
### Your Name

Alexander Evan Parish

### Your Email

evan.parish@oddball.io

### Your Role and Team

Backend Engineer VA Notify

### Product Manager (PM) name and email

Melanie Jones melanie.jones@oddball.io

### Product Owner (PO) name and email

Beverly Nelson Beverly.Nelson@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCw7Cuq1iGgUVAAQP/aRn7yeIC6j8DE4OZweEtgLB+8AyTHMGgXxjyuxuc+3P4/UrdoJxw31do7En1ccgC8k2ReCRRZyXcUH/cFVzaPrnBkIBC8bBn6LDZmuyXsrJ4wH4ETat0GxK5vfi8GwAvugSXUi7cavshP6/3QIlciW59mPr4vrNZ2T07VW4hFjZ7PW2nob50g/UWxpVQLi9PADyMhwkRnsMsbbXjBnlVM6tW8R67hfLQwZFacXSEHORJhNVuAUk9O7fScG8PqPbHZ3GCOv5LPJOXfMOvvV7tevm9Vc5K9kFq8NrAg25xJAXv/KyT1qKU4ofDhgxgCpot8wFlvAtGAV/Ot1SPN6mA+f2zcRM/SMBBf/up9b4g89lgVZj0lnQNAHl1UhA5smmZxG1Oqb4h7NonDZtrLAZwZiK5tFKYmC0scna96sqwWSLnz7HsFqiJ41CX6Mldskrqe2EpPde7KWMcgUAdvhA1gD7b+u71rUjBbEngu1z0iX2y429s=

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mjones-oddball** [comment]
Please see this platform ticket we submitted: https://dsva.slack.com/archives/CBU0KDSB1/p1654553319385389

In case that's relevant. 

Our tech lead's ticket is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42409 and we were told to submit a platform ticket in slack.

**Comment by kjduensing** [comment]
@mjones-oddball @bevnobev @EvanParish Hi there. I'm all caught up on the status of the platform tickets and Kyle's request. I'm continually monitoring the platform support channel and the roster, so once that request goes through I'll jump right on these. Thanks for your patience.

**Comment by kjduensing** [comment]
@EvanParish was found in the VFS roster.

**Comment by EvanParish** [comment]
Hello @kjduensing the key listed above isn't working and I've already talked to support about it. (https://dsva.slack.com/archives/CBU0KDSB1/p1655218000865579) I suspect it may be because I created a passphrase for that key. I have generated a new rsa key. Could we try to switch my key to this one?

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC73IHPjPHflthLAVltALr8Ge7EWt4XMUx5kXstnDbe1Fh+kjogIN0yBLvkTZYa+8LqcUnZFmF2TA3nyOcHkCWnzL3DLfi5syFEiwNqu5B9bTQEqoY9kL30CsS+A84fJUR/7PA2LQfbHR5Q4ZYVHHE5NTjsi5+H0RbG7bZlkdDwWuisUFi5mdq3vNMuv6UzHPzwz6vDds3Bv1mkjHpnAYqqE5OH2jeUNhdxhjAp71tJRC0QyU06C6m3zWRHlHQ90FEjaAnKBOnLdJjDCT5UVndRf7f70NJNPdXA79MHQIc2IVjCn6z7aoz3SSCD5zvg3A1uawN3EXGXQREq8kYW+705pUbEUN7OLTIjJGjBCxdKstpIrFD/UxjKOOr2VJOcZh5okKBwIzyMNsln9HQWHnOlMUZtt7eIbf4GXGLKTiHUcS2sqVWV8jwBgQWeoyw36HS3E3Q2kWKjs2OVhbPZsc1NGVPqHWH4o5r/DFNfqKbBp+4qPQVNkkFDhjJonos4SHE=

**Comment by calquisola** [comment]
Hi @EvanParish ,

Please try now. We've updated your rsa key. 

Best,
Carl

**Comment by EvanParish** [comment]
It looks like it's working now. Thank you! 
```
~$ vtk socks setup
Username for 'https://github.com': EvanParish
Password for 'https://EvanParish@github.com':
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 879 bytes | 879.00 KiB/s, done.
----> Testing SOCKS SSH connection... ✅ DONE
----> Configuring SOCKS tunnel to run on system boot... ✅ DONE
----> Configuring system proxy to use SOCKS tunnel... ✅ DONE
----> SOCKS setup complete.
```
