### ISSUE TITLE
Content and IA Request from MyHealth team (Secure Messaging): SM tool content

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42428]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [X] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We are in the process of moving MyHealtheVet functionality to VA.gov.  The first feature will be Secure Messaging.  We will need guidance on content, form labeling and IA since this tool currently exists outside VA.gov. 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [X] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
TBD, but current estimate is Q2 2023.

  
## Supporting artifacts

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/product/product-brief.md)
- [Link to user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1653576434058/bccd44ff0c18264f3ed814abd149cbfbe7d01d03?sender=jonathannelson8855)
     - [Moving a message](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D2D9BB09-3F4C-48DF-968A-2E7496A8EB3C)
     - [Deleting a message](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1E39EB4D-9861-4EB5-8114-011D48793A1B)
     - [Deleting a draft](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/2E118731-2E23-4967-8B05-A3B2232E8B78)
     - [Creating a folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/526A7E02-BC3F-4BF6-A7FB-EEF67C14ED73)
     - [Basic search](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/741EAD06-73F0-4C05-BA1E-F02445AF4030)
     - [Advanced search](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/79436C57-144F-4FD7-9D22-C0DD338CAA32)
     - [Autosave draft from compose page](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/A283B563-BA83-4166-BC07-1F4ECB618010)
     - [Autosave draft from reply pages](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/848A32AD-549A-42E2-B4EB-A54E49F1D4A6)
- Link to prototype or mockups: **Note - These screens and flows are currently being tested/subject to change**
     - [Desktop prototype](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/prototype/a/0C5CF38D-3AAC-477B-A479-B14220AA3503)
     - [Mobile prototype](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/prototype/a/0606632E-EBD2-4B8C-876D-64593DF9E556)
     - Landing pages (List Views):
          - Inbox  [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/My9L2Wl) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/dlJRdPm)
          - Trash [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/48AEB8C4-6AAA-4610-B819-21A289118A90) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/054AAC94-4802-40FF-8A94-A2955AEB54AF)
          - Drafts [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/053AF4BA-4003-44B3-B502-494E381553F5) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/E99F6FBF-849E-4DAD-971E-C8CAEE0A3980)
          - Sent [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/FA90EDA7-7DAB-46B9-AB38-32A4983950EA) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D739D6E9-E557-45B7-BB12-CAD2F92F0318)
          - My Folders landing page [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/BB9455C9-0F63-4A5E-8245-D94C0456FE11)
          - Custom folder (nested within My Folders) [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/F8233DF0-67BB-449D-81E8-9D03EB604C76) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/A666D229-A06A-49C6-A519-C309BFE0964D)
          - Search messages [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/2BBDC720-664E-4C6F-8EC6-915FB49AB978) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/97149C2D-1E28-4F3F-9D17-5D52893E9D40)
          - Advanced Search form [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/54D6116C-E062-4875-BA8E-EBC7DEE2FE8E) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/9DA8242E-E067-41B3-A5CC-786CF6436633)
     -  Inbox message detail [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/E407174B-56A5-4FD5-8EE7-E3250E4A3E23) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/YGejDvd)
     -  Compose message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1D42D2C4-859E-40EE-99FA-CEB9939865D4) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/6EF72EFE-D73B-4214-A184-2EB17E6207FF)
     - Edit draft message detail view (draft of a reply) [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/702EAC7E-FB05-4E4C-8611-0782B05F7DE9) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/432DE2C8-230F-4C6A-84E6-F02A4966CA12) 
     - Edit draft message detail view (draft of a New Message) [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/E1D8B12B-DCF5-4A04-BA20-C40637513CD2) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/33437166-C54A-4913-A343-C639EC87F5A8)
     - Sent message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/C3D8D126-84D2-4950-ACF4-7F6DFFF08774) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D739D6E9-E557-45B7-BB12-CAD2F92F0318)
     - Search results [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/C2008170-C3E4-4924-899D-4C7FE99431C0) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/237F8A88-6AE5-49DE-A40F-E644DBCBDEDA)
     - Deleted message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1570663C-093D-4ECC-99D7-9B5EFBC8001C) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/5BD11B6F-4BC1-4645-91B0-AAA9EFA98B8C)
     - Reply to message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/4550B031-AB89-4A93-AAF9-C201AA28D47D) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/93733CC4-442D-4504-A85D-BE71D24C3C34)
     - New pages added 11/15/22:
          - [Empty Inbox ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D7BD84EF-7A26-4C82-8AE3-0B9C770FE0BC)
          - Empty Drafts/Sent/Trash Folder [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/DB42EFA7-0954-4CAE-86A4-8B098663CB68) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1D5587B6-055E-416D-B35F-805EBB430E9B)
          - [Empty My Folders landing Page](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/8CAEA70F-39F4-490A-846C-8A3ED425C20D)
          - Messaging actions (modals):
               - [Confirm send message to trash](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/91D9AFE4-FBDF-46FB-8299-019EB88AAE69)
               - [Confirm discard draft](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/5418A7EC-62D2-4F28-A8E3-6C5F958834E5)
               - [Can't save attachments to drafts](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/43E42C46-E8C2-469D-AF90-B14F114C57BA)
               - [Cant save or send draft - incomplete fields](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/694472F3-95A4-4D93-A7B2-C3CC58174A1B)
               - [Move conversation](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/2DACB267-7B0C-4CB6-A999-4E1D9F817C19)
               - [Print message](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/AF29D60B-B4A2-4990-A6AF-D9AA0DC92E8A)
               - [Create new folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/131FBF82-CB49-4320-9768-0EF8057A38E1)
               - [Edit folder name](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/B8FF4AA5-2524-46E0-BB83-F21742D82600)
               - [Remove folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/28FAFCEE-DD86-4FB2-BB02-D9CE5903BA4F)
          - Alerts:
               - [Successfully deleted/removed folder ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/18933DF7-4460-49C6-B05A-BF4ACA03E0AE)
               - [Successfully renamed folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/68894BF7-6438-492A-BD0F-77F4819D4A1C)
               - [Can't reply to message because it is older than 45 days](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/0791E242-E0CF-47CB-8261-D1DFB6CA309F)
               - [Success and error alerts for Deleting a message (thread); saving/discarding a draft; sending a message; moving a message; and when the user tries to enter an unacceptable character. ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/594A1A57-04E6-45BC-92CA-E87F3DEF6464)
     - New pages added 12/16/2022
          - We would like guidance on the button labels for the [reply page](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/bgeA2VZ#Version)
          - [How might the search results page display the terms included in the search? ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/4azZq0A#Version)

- Link to any epics/issues that may be helpful: 
     - https://github.com/department-of-veterans-affairs/va.gov-team/issues/41827
     - [MHV, Cerner, and VAOS authenticated screens >> See Secure Messaging section of this Mural.](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1638893982626?sender=megpeters0505&key=46c036df-fac6-4106-890d-91f15142c646)
     - ["VA secure messaging" page on VA.gov](https://www.va.gov/health-care/secure-messaging/)
     - My HealtheVet user guide for secure messaging: [SMUserGuide-MHV.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8882134/SMUserGuide-MHV.pdf)
     - [Notes gathered when creating Messages FAQs mockups](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1654893985647?sender=megpeters0505&key=e5d0aa4b-ac0f-488a-b8fb-c427c4d38e35): These came from the "VA secure messaging" page on VA.gov, the MHV messages user guide, and conversations with MHV partners.

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Q1 2023 
- Estimated staging review date: Q1 2023
- Content and IA work needed by: Aug 2022 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Tracey Mulrooney
-	Product manager: Marci McGuire (Health Modernization Product Spike Team) / Bryan Riley (MyHealtheVet team)
-	Designer: Meg Peters, Jonathan Nelson, Arienne Walters, Lexi Wunder, Jessica Robertson
-	FE engineer: TBD
-	Product/team Slack channel: #mhv-secure-messaging

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by MarciMcGuire** [comment]
Additional page mockups:

Message FAQ pages:
Mobile auth
https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/R1K8kbZ
Desktop auth
https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/1KQWDzp

[Desktop: empty landing page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/nRjzpyk)
[Desktop: empty drafts folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Qbd5vEY)
[Desktop: empty sent messages folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/xrmapJm)
[Desktop: empty sent messages folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/EL35bVA)

[Mobile: empty landing page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/3OrEqvm)
[Mobile empty draft page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/m19dp7L)
[Mobile: empty sent messages folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/DPQ5bpe)
[Mobile: empty deleted messages](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/jgLW0Z7)

**Comment by mpeterz** [comment]
Message FAQ pages: 
[Mobile unauth](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/kaW1EJo)

[Desktop unauth](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/pa2wRoR)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @mpeterz, for the great conversation about this! 

@RLHecht Let's touch base about this one next week. I think it would be great if the team could start on building out the FAQs as a first step. We have some time with this project (a rare luxury!) so it'll be a great way for the team to get familiar with the product and dig into some content.

**Comment by mpeterz** [comment]
@RLHecht - 
- I added some resources in the main ticket, including content notes for Messages FAQs.
- Our team would be happy to walk you through Messages designs, which are mainly functionality, but we need some intro text and UX copy. The Messages FAQs pages have the most text, and there's existing content to leverage from VA.gov and the MHV user guide for messages.

Thank you, @DanielleThierryUSDSVA!

**Comment by RLHecht** [comment]
@mpeterz The link to the Mural is asking me to sign in. Our team doesn't have accounts. Is there a way to make it so we can be guests?

**Comment by mpeterz** [comment]
@RLHecht - I invited you to the Mural for Messages FAQs notes. LMK if you still have issues accessing the Mural.

**Comment by laurwill** [comment]
Hi @mpeterz , could you add me to the Mural for Messages FAQ notes as well? Thank you!

**Comment by jonathanjnelson** [comment]
Hi @laurwill, Meg actually rolled off VA.gov 

@MarciMcGuire can you help locate these notes? (I am still waiting to get re-access to DVSA Mural space)

**Comment by MarciMcGuire** [comment]
@laurwill does this link work for you?

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1654893985647/99fbb1cd0717859020e71ffd9ef5ad6b0a1fd8d6?sender=u71ad98f94f5263595f9a4390

**Comment by MarciMcGuire** [comment]
@bryan-riley-va @ArienneWalters @alexiawunder I'm going to take the core team's Secure Messaging tag off this issue and add your team's tag so you can see and track it on your team's Secure Messaging board.

**Comment by laurwill** [comment]
> @laurwill does this link work for you?
> 
> https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1654893985647/99fbb1cd0717859020e71ffd9ef5ad6b0a1fd8d6?sender=u71ad98f94f5263595f9a4390

Yes! that link works, thanks so much.

**Comment by mnorthuis** [comment]
@RLHecht @heyjoni There has been team turnover and some significant changes to the approach in this work, so I'm recommending we regroup on this to establish what needs to be done and prioritize it. 

@MarciMcGuire @alexiawunder It appear that none of the links to the sketch files in the original description work.  Please update with links to all pertinent artifacts and updated designs.  

Thank you!

**Comment by MarciMcGuire** [comment]
@alexiawunder I don't know the locations of the most recent versions of each screen.  Would you mind updating the links in the request?  Thanks!

**Comment by alexiawunder** [comment]
@mnorthuis @MarciMcGuire I am working on collecting the updated links now. Should I update the original ticket (and include the links Meg and Marci added in the comments back in June?), or put them in the comments here?

**Comment by mnorthuis** [comment]
You can update the original comment/request so there's no confusion.  Thank you!

**Comment by mnorthuis** [comment]
@alexiawunder just checking in on this, do you have links to the most recent designs?

**Comment by alexiawunder** [comment]
> 

Hi @mnorthuis @MarciMcGuire - Thanks for your patience! Sketch has been uncooperative lately. I have updated all the links in the original request, and added a few more. I wanted to provide as many links as I could, so I included desktop links that may not have mobile counterparts designed just yet, and vice versa, but the content should be identical on every device. Also, please note that some of these designs will change slightly pending the results of the active usability testing. Please let me know if you'd like a more thorough walkthrough of each page, as I'm sure there will be questions.

**Comment by laurwill** [comment]
Hi @alexiawunder , thanks so much for updating these links! I see a couple of success/error message screens linked here — are you still planning to collect a larger batch of error message content for review?

**Comment by alexiawunder** [comment]
@laurwill Yes - I have been working on putting together a document with as many as I have, but that is going to take a little more time and research. In the meantime, the alerts I've linked so far are all we need to focus on.

**Comment by heyjoni** [comment]
IA design doc created for phase 0: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/my-health-secure-messaging.md

**Comment by MarciMcGuire** [comment]
Added application name to this request so we can distinguish from the others related to MyHealth/Health Portal

**Comment by laurwill** [comment]
Hi! Just documenting that we've commented on all the Sketch screens linked at the top of this ticket with our content feedback and questions — we've checked off each screen in this content review ticket to show that our comments are ready for review and discussion with design: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50161#event-7923258428

**Comment by RLHecht** [comment]
Since work is being tracked for this in other tickets, I think this is OK to close.
