### ISSUE TITLE
[Issue] Update Housing Benefits for all Institutions in Philippines on Search by Name Page

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#42447]
## Issue Description
Housing Benefits for institutions in the Philippines was updated on May 25, 2022. The requirement received from EDU was to update the housing benefits on each of the institutions Calculate your benefits section only. This change only apply to Spouse or Child / Ch. 35 (ONLY). [Please see #41303]

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/41303

On 6/6/2022, it was reported from EDU housing benefits were still showing the incorrect amount on the Search by Name page.

This ticket is to apply the same changes that were made on #41303 to the Search by Name page for Spouse and Child - CH. 35.

---
## Tasks
Dev to make changes to the Search by Name for ALL institutions in the Philippines to reflect the correct amount of $649.00 Currently it displays $1298.00

## Acceptance Criteria
Update the Search by Name page for ALL institutions in the Philippines to reflect the correct amount of $649.00 since it currently displays $1298.00
---

**Comment by MitchLivingstone** [comment]
Closed and completed in story 42448
