### ISSUE TITLE
access_token requires refresh in order to be set

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#42443]
## To Reproduce
1. Configure your local environment to use keycloak. 
2. Authenticate with your login.gov ID. 

## Expected Behavior
After successfully authenticating, the user should be redirected to the root application (session && !session[:user_access_token].nil?). 

## Actual Behavior
The redirect does not function as expected and the user is not brought back to the root application (they get stuck in Login.gov). 

## Mitigation
If you manually navigate back to the root application, the user will be authenticated as expected.

**Comment by ewilson-adhoc** [comment]
Still debugging -- working on solution that stores sessions in redis, will push up on session-bugfix branch.

**Comment by ewilson-adhoc** [comment]
Returning back to this bug, I tried a workaround which involved storing the session externally (in redid). This did not resolve the problem as expected, so I decided to look back at the different requests the system was making to see if I could spot any problems. 

This is what I discovered:

- Navigate to localhost (local instance of application hooked up to keycloak) 
Everything behaves as expected, the session doesn't have a session key, so we are redirected to localhost/temp_code_auth

- We get correctly redirected to get the auth code. These are the requests 
`https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/protocol/openid-connect/auth?client_id=Sidekiq-UI-Dev&scope=openid+profile+email&grant_type=authorization_code&redirect_uri=http://localhost/auth/keycloak/callback?original_uri=/&response_type=code&login=true&prompt=select_account`
`https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/broker/oidc/login?session_code=eXkdS5oybEfSmtJFg0o9jK6KGBjeNe4rAxs0NeQplZU&client_id=Sidekiq-UI-Dev&tab_id=pBgB-ZTgJxo`
`https://idp.int.identitysandbox.gov/openid_connect/authorize?acr_values=http://idmanagement.gov/ns/assurance/loa/3&scope=openid profile email phone&state=7UyaNAKIidOgagtKAOzY0FLyEx7m61hDPMUn2MAy5sA.pBgB-ZTgJxo.Sidekiq-UI-Dev&response_type=code&client_id=urn:gov:gsa:openidconnect.profiles:sp:sso:va_gov:developer_access&redirect_uri=https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/broker/oidc/endpoint&prompt=select_account&nonce=iMFlYMKzio-bfQusMSWQMA`
`https://idp.int.identitysandbox.gov/?request_id=b9b06bfb-809d-4956-bd2d-0449fb1eb51d`

I enter my 2fa
`https://idp.int.identitysandbox.gov/openid_connect/authorize?acr_values=http://idmanagement.gov/ns/assurance/loa/3&scope=openid profile email phone&state=7UyaNAKIidOgagtKAOzY0FLyEx7m61hDPMUn2MAy5sA.pBgB-ZTgJxo.Sidekiq-UI-Dev&response_type=code&client_id=urn:gov:gsa:openidconnect.profiles:sp:sso:va_gov:developer_access&redirect_uri=https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/broker/oidc/endpoint&prompt=select_account&nonce=iMFlYMKzio-bfQusMSWQMA`
`https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/broker/oidc/endpoint?code=2e51cc6a-a6e5-4dba-9045-deafa3c46133&state=7UyaNAKIidOgagtKAOzY0FLyEx7m61hDPMUn2MAy5sA.pBgB-ZTgJxo.Sidekiq-UI-Dev`
`https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/login-actions/post-broker-login?client_id=Sidekiq-UI-Dev&tab_id=pBgB-ZTgJxo`
`https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/broker/after-post-broker-login?session_code=FnW0jcH6rbtQfBCuI4BteyxUk-zx6w90QTRlTQnG-V4&client_id=Sidekiq-UI-Dev&tab_id=pBgB-ZTgJxo`

The redirect keeps me on the login.gov page. If I click continue again. I get an error that says I'm already logged in. it doesn't look like the redirect occurs (I don't see anything trying to talk to my application). From what I can see, the code to put the access key in the session is never actually called at this point.  If I manually navigate back to localhost. 

- First we're redirected to http://localhost/temp_code_auth?original_uri=/ 
the session does not contain the access key {`"session_id"=>"a00e5d50588367283e9e39441486f0749e7aa22d64cc2aea50025e16a9196077", "csrf"=>"jXq7X7uQ0TNB5yMzKQj4NGzmzf8W5im35NK2IL5pJjg="}`

-We are redirected to keycloak
`https://keycloak-dev.vfs.va.gov/auth/realms/Login.gov/protocol/openid-connect/auth?client_id=Sidekiq-UI-Dev&scope=openid+profile+email&grant_type=authorization_code&redirect_uri=http://localhost/auth/keycloak/callback?original_uri=/&response_type=code&login=true&prompt=select_account`

-keycloak bounces us back to the auth_callback on local host
`http://localhost/auth/keycloak/callback?original_uri=/&session_state=9d5bd690-50f6-4a8d-9ff5-cf06685965bd&code=70b5d467-c56e-487a-a1d8-2e9c1ddfb7e0.9d5bd690-50f6-4a8d-9ff5-cf06685965bd.e1e05fcb-1dd6-44e7-ad17-f120bd8b1`
At this point we actually call the code that sets the user_access_token
`{"session_id"=>"a00e5d50588367283e9e39441486f0749e7aa22d64cc2aea50025e16a9196077", "csrf"=>"jXq7X7uQ0TNB5yMzKQj4NGzmzf8W5im35NK2IL5pJjg=", "user_access_token"=>"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMREVMS3Z5N0N6WXNQMkhQQnI1V25iU3R6OWotRmU4OHVTc01Gdlhxdm0wIn0.eyJleHAiOjE2NTY3MTE5NzEsImlhdCI6MTY1NjcxMTY3MSwiYXV0aF90aW1lIjoxNjU2NzExMjQzLCJqdGkiOiIyMzU1ZjZlNi1jOWM1LTRiZjctYWVkMy01YjljN2RmMDEzNzIiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLWRldi52ZnMudmEuZ292L2F1dGgvcmVhbG1zL0xvZ2luLmdvdiIsInN1YiI6Ijk1ZjAwNzU2LWJhZGMtNDgzZC04NmQ5LTJjZTdkNGE4ODY5YyIsInR5cCI6IkJlYXJlciIsImF6cCI6IlNpZGVraXEtVUktRGV2Iiwic2Vzc2lvbl9zdGF0ZSI6IjlkNWJkNjkwLTUwZjYtNGE4ZC05ZmY1LWNmMDY2ODU5NjViZCIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZXNvdXJjZV9hY2Nlc3MiOnsiU2lkZWtpcS1VSS1EZXYiOnsicm9sZXMiOlsiYWRtaW4iXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiOWQ1YmQ2OTAtNTBmNi00YThkLTlmZjUtY2YwNjY4NTk2NWJkIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiRkFLRVkgTUNGQUtFUlNPTiIsInByZWZlcnJlZF91c2VybmFtZSI6ImVtaWx5LndpbHNvbkBhZGhvY3RlYW0udXMiLCJnaXZlbl9uYW1lIjoiRkFLRVkiLCJmYW1pbHlfbmFtZSI6Ik1DRkFLRVJTT04iLCJlbWFpbCI6ImVtaWx5LndpbHNvbkBhZGhvY3RlYW0udXMifQ.WlqKu7njgWKgibNxgrwCOmEQ44ApJHHpGtwi1o7iymtyezE5Dxih1hP4RnQOW1_D2Ad6Lq7haEjbY_w--U65L_AAO1_hpSQqdNKqyAct4EX42wjxMv_NvSzeB4YyQTve_rjCZCvvGvlXeaa2eSvQerkzXAHomvdvVzIIKLmXvXLKrADfo4E5RliZr79EpcT6XOAQ-fpXOfwqptDv2VTaFjxNBqXf1vseVo9Ai7_RpnKjABi4KpwS5B69xrQFH3H3vN-PuI4y_YR6hwaE8XabXIWNPVs6Un82I98f78bxRHMbj9u6Ybwy2QR4ATbV5_2Qfq8dIMcbL0AWqUxKOKI03w"}`

**Open Questions**
- The first redirect doesn't happen, unless I manually go back to localhost. Do we expect login.gov to kick us back to localhost automatically? Do the requests look like they contain the information needed for this to occur. 
- Why do we need to go through this process twice to get the session to stick? The fact that I am able to navigate to localhost and don't need to enter anything any seems to indicate that the temp_ code is being set. Is there an issue with the way the redirects are set up?

**Comment by kylesoskin** [comment]
@ewilson-adhoc 

>Why do we need to go through this process twice to get the session to stick? The fact that I am able to navigate to localhost and don't need to enter anything any seems to indicate that the temp_ code is being set. Is there an issue with the way the redirects are set up?

Yea I do believe this is an issue in the Sinatra side with the redirects. When not directly redirecting and using a "successful login" landing page, everything works as expected. It is only an issue with a direct redirect, it feels like it has to be something logic wise in Sinatra either with the flow logic or the redirect itself.... still troubleshooting but in case of emergency, the interim login successful page can be a (crappy, but in my opinion acceptable) solution.

**Comment by FHiatt** [comment]
Emily has solution will test and deploy - target end of week
