### ISSUE TITLE
create login troubleshooting document for help desk

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#42458]
Use the known frontend errors in this doc: [https://app.zenhub.com/files/133843125/96ae0c10-74df-481d-8fe9-44bf9b8231ad/download](https://app.zenhub.com/files/133843125/96ae0c10-74df-481d-8fe9-44bf9b8231ad/download)

For each error create as much documentation as we can about how a help desk agent may assist the user during a call. Also include information on where the issue should be redirected next.

- [x] Publish the document in our public github
- [x] Peer review with team
- [x] Share with Kimberly from Contact Center Team for review
- [ ] Schedule every 3 months to review the document (add a calendar event, invite team)

**Comment by AGarcia-Clarity** [comment]
Sent Slack message to Contact Team lead (Kimberley) for review (also pinged in the PR + added to Reviewer)
