### ISSUE TITLE
Control over when changes go from staging to production

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#42467]
**Problem statement** 
VAOS would NOT like their app to be pushed to prod on a daily basis (current cadence). VAOS' QA team/process is complicated, as it touches many entities/teams, and it often requires more than a 24 hour period to complete the necessary work before fit to go from staging to production.

**Notes**
• VAOS is aware about feature toggles, but for their use case it is more time consuming to utilize FTs.
• VAOS (and other teams) like single app deployments as a concept, but want to be able to control when the changes get pushed to Prod. [ as opposed to a set cadence, or immediately on commit]
• As it stands, the autonomous deployment directive work we were doing was aimed at doing the latter option--automatically running a deploy-to-prod action immediately after a PR is merged to main.

The primary caveat is that we have multiple teams merging their branches to a singular staging environment with no way to cherry pick the code of any individual team once it has been merged to what is, in essence, a staging branch. Example: VAOS, facilities, and burials all merge PRs to staging and start their QA workflow. Burials finishes way ahead of the other teams and deploys to production by merging the staging branch (which also contains the code from VAOS and facilities) to main, thus inadvertently pushing VAOS' and facilities' code to production along with theirs. In an alternate scenario, burials is forced to wait for VAOS and facilities to be able to deploy to prod, which is also not ideal. So it seems what we really need is a way for teams to have their own, individual branch, synched to main and in a staging environment. Once the team is ready, they can merge with main, thus proceeding with the regular path to production/deploy.

**Solution**
It is for this reason I would suggest Updating [or creating] review instances, as an option , to mimic staging environment as the most efficient solution. Understanding that this would involve mainly the infrastructure team; I think it solves VAOS situation and, if full autonomy over WHEN a deployment is made is still desired, a GHA could be set up giving the option to run something similar to an out of band deployment whenever a staging branch is merged to main.

**Pros / Cons**
**Pros: Review instances... **
• already apply to individual commits (branches)
• can be applied to lower environments
• utilize a solution we already offer, so we wouldn't need to reinvent the wheel to create individual, main-synched, team branches in a production environment or drastically restructure our repo
**Cons: Review instances... **
• Require SOCKS access
• can be flaky

**Comment by laineymajor** [comment]
@rmessina1010 can you help me complete the info in this ticket.
And can you/should you bring this to the architecture work group?

**Comment by rmessina1010** [comment]
@theodur , @alexandec:

I was weighing through  these options and wanted a clarification on branches vs. environments. At  any given environment is a teams code insular? Given a situation in which we have managed to decouple `prod`  from `staging`,  and say there is a scenario in which 2+ teams have QA issues. Ignoring merge conflicts  for now,  say  one of the teams resolves their QA issue and is ready to go from `staging` to `prod`...  wouldn't  both teams' code be pushed to `prod`?

**Comment by rmessina1010** [comment]
**Problem statement** 
VAOS would like their app to not be pushed to prod on a daily basis . VAOS' QA team/process is complicated, as it touches many entities/teams, and it often requires more than a 24 hour period to complete the necessary work before are fit to go from staging to production.

**Notes**
	•	VAOS  is aware about feature toggles, but for their use case it is  more time consuming to utilize FTs.
	•	VAOS (and other teams) like single app deployments as a concept, but want to be able to control when the changes get pushed to Prod. [ as opposed  to  a set cadence, or immediately  on commit]
	• 	As it stands, the autonomous deployment directive work we were doing was aimed at doing the latter option--automatically running a deploy-to-prod action immediately after  a PR is merged to main.
 
The chief caveat is that we have multiple teams merging their branches to a singular `staging` environment with no way to cherry pick the code of any individual team once it has been merged to what is, in essence, a staging branch.  Example: VAOS, facilities, and burials all merge PRs to `staging` and start their QA workflow.  Burials finishes way ahead of the other teams and deploys to production by merging the `staging` branch (which also contains the code from VAOS and facilities) to `main`,  thus  inadvertently pushing VAOS' and facilities' code to production along with theirs.  In an alternate scenario, burials is forced to wait for VAOS and facilities to be able to deploy to prod, which is also not ideal.  So it seems what we really need is a way for teams to have their own, individual branch, synched to main and in a staging environment. Once the team is ready, they can merge with main, thus proceeding with the regular path to production/deploy.

**Solution**	 	
 	It is for this reason I would suggest **Updating [or creating] review instances, as an option , to mimic staging environment** as the most efficient solution. Understanding that this would involve mainly  the infrastructure team; I think it solves VAOS situation and, if full autonomy over WHEN a deployment is made is still desired, a GHA could be set up giving the option to run something similar to an out of band deployment whenever a `staging` branch is merged to `main`. 
 
**Pros/Cons**	 	
 	**Pros:  Review instances...  **
 	• 	already apply to individual commits (branches)
 	• 	can  be applied to lower environments 
	• 	utilize a solution we already offer, so we wouldn't need to reinvent the wheel to create individual, main-synched, team branches in a production environment or drastically restructure our repo

 	**Cons:  Review instances...  **
 	• 	Require SOCKS access
 	• 	can be flaky

**Comment by rmessina1010** [comment]
This is what lead "autonomous deploy" to be rephrased as "continuous deploy"; issue addressed. Closing.
