### ISSUE TITLE
SOCKS access for [Gary Fong]

### ISSUE THREAD

**Issue by garyjfong** [department-of-veterans-affairs/va.gov-team#42464]
### Your Name

Gary Fong

### Your Email

gary.fong@va.gov

### Your Role and Team

Developer - Long COVID Technical Team

### Product Manager (PM) name and email

Marian Adly - marian.adly@va.gov

### Product Owner (PO) name and email

Marian Adly - marian.adly@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMmjlQqyN4qCuH0VdL9xlIDEhgdIgcdsxUPfY3kxRQPEO5a/0Ldi2wM53ME+4Bc3vomJeeeyr3LlawM3aaSysk6Xz7RGjxVrgbi6n8iYd2V3hWnpSsMCeTwmSHvATSY+2fKwJQSn/KBCfpqrL9uAQ3hDERV+F/tM7+QaNGLMk4vUM2wYYp6uF5GBYY8HwLO/xopYky2G4uWuOCMBQ996mqGT+wA6EIOe0kMXFa+iGY/dbE5kOkbxnV2mN/FsPWW14SpDjJ8E+swaZGQh88xB+MfDeij7QlpY6+W+/cs06ZbTukvXQHIuu3Zi3HrFTSbxly2bG1bkkH8XaHmzs48nEs+HZ6vHkEkXYi1VBldKcEt2/vp5NMwq8t1mKttMBozVoRk1sBhmFe3hc2RxQez+3rXlHLk47qJgLlU4Bhz54c7WkbStXK4wX453dkMjsHSCZtOZLjF2f1s8S1hyVz3onvLUd4RajDmWxQQr6cWxQXlFvxxLPjAxxYR2NZhA6sBr0= garyfong@Garys-MBP-2.home

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@garyjfong found in the VFS team roster. Kicking off process.

**Comment by kjduensing** [comment]
@garyjfong - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
