### ISSUE TITLE
Document errors for frontend SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#42478]
Take the code [here](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/41299) and check in each definition for the message for each one. Document those error descriptions. 
![Screen Shot 2022-06-07 at 15.04.37.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/ff70e582-bdd2-48d3-86b6-e6e0f841536a)
Publish these errors in public github.

Notes: https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/

**Comment by AGarcia-Clarity** [comment]
Sent Slack message to Contact Team lead (Kimberley) for review (also pinged in the PR + added to Reviewer)
