### ISSUE TITLE
Layout/Styling Fixes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42481]
## Release Method
Feature Branch "check-in/epic-42481/layout-styling-fixes"

All code should be included in the feature branch and released together

## Problem Statement
On June 2, 2022, the UX team conducted a visual audit of the Pre-Check-in and Check-in applications to ensure that they were consistent with the wireframes and each other. These [issues ](https://docs.google.com/spreadsheets/d/1Z_W57lCBcbFcTCwHkPcg_Ep5emfdm9ywSkyY-i47Nis/edit#gid=0)came out of that audit.

**Comment by benbrasso-agile6** [comment]
42350 No
42352 Yes, complete. Replaced screenshot for confirmation page for check-in. 
42351 Yes, complete. Added screenshot in error areas for pre-check-in and check-in. 
42344 Yes, complete. New screenshot for confirm contact info on check-in. 
42346 No
42342 Yes, complete. Updated pre-check-in screenshot for start page for accordion update. 
42349 Yes, complete. Updated pre-check-in confirmation screenshot. 

Going to check other ticket now for the vaos link
