### ISSUE TITLE
Create a template for an MVP onboarding schedule

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#425]
## Goal
The goal is to create the recurring schedule of meetings, activities, etc., for both the VSP and VFS team members.  For example, what happens on day 1, day 2, day 1 minus 2 days (i.e. two days prior to day 1, assuming day 1 is the first day both teams have a meeting together), etc.

Other considerations are: 

- what does the first week look like
- where does this template/schedule live
- who has visibility and access to it

## Acceptance Criteria
- [ ] Collaborate with support and leadership members
- [ ] A document that outlines the schedule
- [ ] A sample VFS and VSP team implementation  (perhaps include items in a calendar view, as well)
- [ ] Decision where the template schedule lives

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by hpjaj** [comment]
Notes from our initial brainstorming session:


## Potential schedule
#### Monday
- Onboarding meetings
#### Tuesday
- Set up meetings
#### Wednesday
- Planning/Strategy/Implementation
#### Thursday/Friday
- Planned support slots of time
  - Can multiple teams attend together, or are there privacy issues?
- Higher availability in general for support

**Comment by accbjt** [comment]
Link to PR for this
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/19
