### ISSUE TITLE
Do not show the user any suggestions that are not "CONFIRMED" as deliverable

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4250]
There should't be a situation where the user sees something like this:

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/e3f16c6c-d540-49ca-9869-3f5480a93945)

We can avoid this by only showing the user suggested addresses that have `"delivery_point_validation": "CONFIRMED"`. It looks like I missed this particular use case in the AC I laid out here https://github.com/department-of-veterans-affairs/va.gov-team/issues/1287#issuecomment-553951745. So I'm updating item 7, the fallback case, to be more clear and mention that we should also allow the user to force through the address they entered if the validation API returned a validation key.

**Comment by tlei123** [comment]
@artistgreen , got a quick question about the **Edit address** link in the modal's validation screen...

Under **You entered**, when you click **Edit address** below your updated (new) address, would you expect the updated address to pre-populate the address form, or the original (old) address?

 I was kinda expecting the updated (new) address to pre-populate the form \[as in, "ooh, I made a little typo so I should be able to quickly fix that by clicking the Edit link"], BUT instead I saw the original (old) address pre-populate.

Please let me know.  We can always run a Slack-call when I come online Monday morning if need be.

Thanks much!

**Comment by artistgreen** [comment]
@tlei123 - whatever the user enters in the form will display under 'You entered:' on the next screen.  If the user clicks 'Edit Address', they are returned to the form with the address they entered.  Thanks!

**Comment by erikphansen** [comment]
@tlei123 @artistgreen I made a bug for this issue you mentioned: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4271

**Comment by tlei123** [comment]
Thanks, @artistgreen !  Just check the board & found #4271 already opened for this bug.  :)
