### ISSUE TITLE
SOCKS access for Kristen Brown

### ISSUE THREAD

**Issue by kristen-brown** [department-of-veterans-affairs/va.gov-team#42500]
### Your Name

Kristen Brown

### Your Email

kristen.brown@adhocteam.us

### Your Role and Team

Senior Software Engineer on EVSS/Documents (Lighthouse)

### Product Manager (PM) name and email

Kelly Lein - kelly.lein@adhocteam.us

### Product Owner (PO) name and email

Premal Shah - premal.shah@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDMh9emA/H6ZKai7fecBRuhJ/2s8x3mIoLl6dpo7CJfhpVHxdrWtxI9t+IeVE4sAI7H/7D2pLMK+dYr/+rTTFLDn0fnDZiRFqDe6BdRAstr/DQjJXusb7PTCtIPUyFBKQCm54Kz+6Dz1mr2sSh5rRbCPBuX5sX79lAaiLKiHY+x9zHMS5SVxffbzJIH5r3HuqKILZI9BhpFociItXzl+eWIKeO62Rjn4N55aA0TZWXSibBQq0q1dz14JgkNqHFN052J4X4w9I7ueYSEUfK8pt/yi4NS2iXCSLZpwb75nVcmn1sOlEtDTKdMQDTNjK0EQoRHrzDCZX1qP9MNAbu0TFPP1igk7u/UspcaxQ0A2HlWDJjgE+ArIrPw1n3cA9I2+GwnFwFqPaSNFzixt+E0DiAv8zjut7wrgshUJ5x+3MTZaJHMWfXOZTzvA8v5eVAnZIMsAIX9jpOq92xvIIqDR04P2qFB5HZfhRdrCUMKRfMLunHMz35Dz/tVbjdW4D5Zpc= kristenbrown@Kristens-MBP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@kristen-brown found in the VFS team roster - kicking off process.

**Comment by kjduensing** [comment]
@kristen-brown - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
