### ISSUE TITLE
CST: Update claim decision content with approved language and links

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42507]
## Value Statement
**_As a_** veteran, once my claim is decided
**_I want to_** see clearer language about the status of my claim as well as potential next steps
**_So that_** I can take the appropriate next steps, including pursuing disagreement pathways if appropriate.

---

## Acceptance Criteria
- [ ] "Your claim decision is ready..." language is updated with approved content (see comments)
- [ ]  All links work and point to a page in production
- [ ] Content approved on staging by @RLHecht

## Background Context
- See historical ticket information below

## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

Within the Claim Status Tool, when a claim decision is ready, the following information block is shown to the Veteran

<img width="1059" alt="cst_nod" src="https://user-images.githubusercontent.com/136959/172645074-4d600eae-c130-4556-aa22-8d8b5414d49f.png">

On this page, we need to:
- Find and change the eBenefit link to a VA.gov destination
- Update the content around the eBenefits link
- Determine if these links are still appropriate:
  - Find out how to reopen your claim: https://staging.va.gov/disability/how-to-file-claim/when-to-file/
  - File for a VA disability increase: https://staging.va.gov/disability/how-to-file-claim/
  - Learn more about filing an appeal: https://staging.va.gov/disability/file-an-appeal/ which redirects to https://staging.va.gov/decision-reviews/legacy-appeals/
  - Apply for VA health care: https://staging.va.gov/health-care/how-to-apply/

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:
  Ticket Matt Self opened - https://github.com/department-of-veterans-affairs/va.gov-team/issues/42508

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits-team-1
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
-	FE engineer: Jerek Shoemaker & Jared Cunha
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
Thanks @Mottie We are going to bring this into our next sprint. Please let us know if there's any urgency on this that we aren't aware of.

**Comment by Mottie** [comment]
@jacobworrell would know the urgency on this content

**Comment by RLHecht** [comment]
@Mottie Here is the finalize content for your team. Please let me know if you have any questions:
[Check.your.Claim.Status.Page_LW_June.27.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9010750/Check.your.Claim.Status.Page_LW_June.27.docx)

**Comment by jacobworrell** [comment]
@RLHecht Just to be clear, this content is approved for production?

**Comment by RLHecht** [comment]
@jacobworrell sorry, I uploaded a clean version now in the comment above. That should work. Thanks!

**Comment by jerekshoe** [comment]
@RLHecht 2 questions on this. Should the links be on a new line from the previous text like they are in the word doc or should they fall on the same line like they do in the current content? Also should these links open a new tab in the browser?

**Comment by jerekshoe** [comment]
![Screen Shot 2022-06-30 at 2 07 00 PM](https://user-images.githubusercontent.com/13838621/176758230-d91ee442-71be-4030-980d-a1aa4b5a3cdd.png)

This is what I have currently, let me know if any of the formatting needs to be changed

**Comment by RLHecht** [comment]
One small fix: Remove the period after the last link "Apply for VA health care benefits"

**Comment by jerekshoe** [comment]
Updated this to remove period. Latest version has been merged into main
