### ISSUE TITLE
SOCKS access for Florence McCafferty

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#42509]
### Your Name

Florence McCafferty

### Your Email

florence.mccafferty@agile6.com

### Your Role and Team

User Experience Designer on Public Websites

### Product Manager (PM) name and email

Wes Rowe: wesley.rowe@agile6.com

### Product Owner (PO) name and email

Dave Conlon: david.conlon@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIQsQ8DbpKCHwVa/RAAPXDmX3b2ssCrV5gT5Vxxgw2oTFJvQmcR3zspGIoSoN8Od6Pt2CxLJVD9xKRDRXiNXE4XOPDfd9biNGUGzTms+v8a6d+DAa6EJ/Z9JRPK+eiFflPegitnOd6iHPWKEF2i8IwRUZ21WkMsFtbU8EDCKsKxYReDpbw7N3dQyQlzv6mXom/yT/apPsmfXPdzbtaqGOuoqsxalzVBckICd09b1Z0A1DmSNb6W+Xs6LeZNmuqGX8kdrrOv0gheLsIUnzxNcPev1an67velPcOz/I247+9M+pncBPWGPR/aLkGjGah3XQTL8Tp8gsegGohpHZ581FAGQDykrNmjyIJQZ3LoaFY2tGa36GGrtRuo//Zyi7uJULKk7/Ial/QtNM0vKPr36L1fIfIKe6CKPVM7w9XOvlTeMtK1SZ7Mjbir3jtOt8u3w4zMd9p489IouHSwUrgSXeEul/nHOCqsfwpllfchbA6m22pYRHY5vFclqTTlU71rjU= florencehome@Florences-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@fmccaf1 found in the VFS team roster - kicking off process.

**Comment by kjduensing** [comment]
@fmccaf1 - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
