### ISSUE TITLE
[Infrastructure Request] Provide RDS Postgres database for Keycloak in staging

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#42537]
### Team name

Access Management (AMT) 

### Application name

Keycloak 

### Product Manager (PM) name

Saipriya Gopalakrishnan

### Product Owner (PO) name

Thomas D

### Infrastructure needed

Hi!

Our Keycloak instances need postgres as a datastore, we need a postgres database for our staging keycloak.
Please grant me permissions create/modify a postgres database in RDS. 

Thank you. 

Best,
Carl

### Acceptance Criteria

- [ ] _TBD_

**Comment by mleclerc00** [comment]
Pulling in @jhouse-solvd and @ph-One for a second/third opinion

**Comment by jhouse-solvd** [comment]
@calquisola - Just to echo what Matt mentioned above, and hopefully clarify your requirements: 

Does AMT need an RDS Postgres database for the Keycloak application? 
Does Keycloak have an existing Postgres database currently in use? 

Typically, the solution would be to allow authenticated, programmatic access from an application, but not from individual users.

Is there any reason why a user would need direct access to this instance? 

Any extra information you can provide will be very helpful.

**Comment by calquisola** [comment]
Hi @jhouse-solvd and @mleclerc00,

Thanks for you responses.  

We are trying to setup a "staging" keycloak instance. Yes, we do have postgres databases for utilitly and dev keycloak instances already.  We need another one for staging. 

I tried to create a new postgresql database in RDS for "staging" but did not have permissions, hence this request. 

Please advise on the best path forward. 

Best,
Carl

**Comment by jsgarmon** [comment]
Changing this from a permission request to a resource request.

**Comment by jsgarmon** [comment]
The staging database has been created. @calquisola : Please close this issue if all looks good.

**Comment by jhouse-solvd** [comment]
_(I re-formatted the request using the "Infrastructure Request Form" as the user did not need a new AWS Access Request)_

**Comment by calquisola** [comment]
looks good. thank you.
