### ISSUE TITLE
SOCKS access for Brandon Marrone

### ISSUE THREAD

**Issue by b-marrone** [department-of-veterans-affairs/va.gov-team#42542]
### Your Name

Brandon Marrone

### Your Email

brandon.marrone@thoughtworks.com

### Your Role and Team

Developer on VA Long-COVID

### Product Manager (PM) name and email

Marian.Adly@va.gov

### Product Owner (PO) name and email

Marian.Adly@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGRAQAvswFcDv9uj5mnIpINn4NGaY5us1YFvUC9YLHMwDoir1NeZWPR63u4e2XKLaLwKoJ73BKy6xq1UesZFsibKkWWwSIW1tkmuP85BEUtUl0E2snbB7n4v/VwsLUNPgi7S1F1eN2E5WajAOwO3blk9W+uvW2ufTKsvcM4I+L06mPMmJaMaOGW6a0gKIp2XH0lkQsIm31S+hJJFpok0JSLWzAhGkj+/8DngJ1yHEMlxCSvFL16oWlMLFH8+n5E3MPBMs+Sbp+SYNnwdgCchrt+qREbWnFfgO5j5PbW5edrwiukgD0U04MH5Yiy+JDgQoe6tX/FEOs8dtSDN+yLgkzJWZiZkXV8Y6vlwzmYtq54vixQ8FHHSUsgAL/dwVyGQZsyvPMy9fn4NrRfC3mCICAvBlRkkPOe0DTuMAj1jjenfbPfCX1unHUuBdO6GT27VH7IqabL2PB4s8z+vTsor7wyErPr6ysBqrI+2KbA00h4Htttp7NrkH4eY/RjgWNMb8= brandonmarrone@Brandons-MBP.fios-router.home

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@b-marrone found in the VFS team roster - kicking off process.

**Comment by kjduensing** [comment]
@b-marrone - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
