### ISSUE TITLE
SOCKS access for [Sriparna Sengupta]

### ISSUE THREAD

**Issue by sksengupta** [department-of-veterans-affairs/va.gov-team#42544]
### Your Name

Sriparna Sengupta

### Your Email

sriparna.sengupta@va.gov

### Your Role and Team

Developer - Long COVID Technical Team

### Product Manager (PM) name and email

Marian Adly, marian.adly@va.gov

### Product Owner (PO) name and email

Marian Adly, marian.adly@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgZE29SGb609kGbMRMB4qYaGHuxsy6VGy+fQVa/CnhCP/c/ECBgLhzLkBNDGAs/7e4C5E1JJLrz5hU2qQ/kihsn1wfUSf1ExS1Z2QPX8jHItfu9mqhaX4CRM7aHJGEC6LSAKPMMIBNaEjdNaKa2XubnzdJd3aduCtV4ZS1s9bPCSGJusiQvS5lcq6TyZ3AmFsHe0EoXwZ8Zujl8V4nisViMGzOIj1W0abjptgm2fpgFx0w3DTEVEt2tSAleYw+Vko00IFZerPjbqOBv8vGpvUfnzRFDlR7oZovZcVwtS5DPWOR6j4wWq983b9QFr8mnYv+NNnFte1eTgdH47oUgqJ3QTM/LAR5QyjuaJqyN1g13T7Vn7nDmCG6bcHl7wdGwT9/j+he+dGdUMA2N2mUSwLTrx69xoaYB+dAGy51h+feqzqdnRPN6fBCTxKSlPHSCGJnZQpG7hw663R9IomqRLhnRYfl4GhwdwDN+cy8iTVqU0IKhVw7XTazcJv98eR/eNs= keyasengupta@Keyas-MBP.hsd1.mi.comcast.net

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Hi there @sksengupta. I processed this request and registered an ssh key for you yesterday (https://github.com/department-of-veterans-affairs/devops/commit/9644dd098eab649af3bb7d06b5acfe4583a341a6)

Are you requesting an ssh key change?

**Comment by kjduensing** [comment]
@sksengupta got it, I'll update your key with the one provided here. Thanks for confirming

**Comment by kjduensing** [comment]
@sksengupta - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
