### ISSUE TITLE
Design Intent  - IA Feedback - Benefits Team 2 - Adding medical copays to the Financial Status Report (VA Form 5655)

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#42558]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
I know this is a lot, but the design intent and the research findings you shared convinced me that your team is encountering a problem many designers face when attempting to move an offline process and its associated paperwork into an interactive online form. I've been there myself; it ain't easy. So anyway...

In her article on "[Getting Started with VA.gov Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md)," Shawna Hein, VA Applications Design Lead at Ad Hoc writes,

> "In general, our online forms should not be framed as a 1:1 mapping of the paper form - in other words, **what we are building are data collection mechanisms for the forms themselves**, and therefore do not need approval in the same way the forms themselves do. Therefore, the language does not need to map 1:1 to the paper forms." 

I've provide some external guidance on navigating the print to digital forms transformation together with VA team resources in the formal feedback. Hope you find it helpful. Feel free to reach out with any questions.

Thanks!

Jim Ryan
Information Architect, Governance Team
 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Move marital status question to general personal info 'chunk' 
- Do the same for dependent children question
- Read Shawna Hein's [Getting Started with VA Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md).and reach out to her with any questions or concerns. 
- [Submit an IA and Content request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E), making sure to tag [Pamela Hastings](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) for advice on best practices for a form audit. 

**Should:**
- Read UK governmental design guidance on [Structuring Forms.](https://www.gov.uk/service-manual/design/form-structure)
- Work closely with VA business owners to conduct a [Question Protocol exercise](https://www.uxmatters.com/mt/archives/2010/06/the-question-protocol-how-to-make-sure-every-form-field-is-necessary.php). 

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by denisecoveyduc** [comment]
VFS team (Debt Resolution) will be resolving this as part of the upcoming initiative to develop a streamlined waiver request. As such further implementation will occur as part [#53495](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/53495). As such, closing this ticket. Please reach out if there are any questions.
