### ISSUE TITLE
Adding 3 new users to DSVA Slack

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#42563]
# Description
I've requested the addition of 3 new members using the Slack shortcut in #slack-workspace-admin. The SLA on slack vs. Github issues is unclear (do you all prefer one method or the other?) so I'm creating this issue as a safety, since these folks start on the project tomorrow (6/9): 

* [christia.troyer@civicactions.com](mailto:christia.troyer@civicactions.com) 
  * https://dsva.slack.com/archives/C01S729LX6X/p1654713185499339
* laura.flannery@civicactions.com 
  * https://dsva.slack.com/archives/C01S729LX6X/p1654714941305259
* christian.burk@civicactions.com 
  * https://dsva.slack.com/archives/C01S729LX6X/p1654714941370869

All should be added as Full members, as part of the Sitewide Crew, and added to the #cms-team channel.

**Comment by LEHigley** [comment]
done. idk the right answer to that. i need to figure out who to hand off this responsibility over to bc i don't have bandwidth and i will let that person decide.
