### ISSUE TITLE
SOCKS access for David Shannon

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-team#42560]
### Your Name

David Shannon

### Your Email

david.shannon@agile6.com

### Your Role and Team

Product Manager / Facilities

### Product Manager (PM) name and email

Kevin Walsh  kevin.walsh@civicactions.com

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0jdtQunNFJ9BJK9+kWsSt/NkOXTIKHek92Ue57giguBZd2wwNFGflHpdjwaCZEBpOyQzci05BisGgHNlMwXLM+fJoQjfB++OWilyIhVCGS/Zjy4SyvrMkgRqg1g2PT0cxkujEf+2o1tTY+5cceDuv3HjMgTGuthsg3F+wZMomFmxLSsmMx9q320AhWrMBzgsllva1SK79acK1iV7oOMxbIapnyM6Nmm/wNEfsoIKHVZqOrsMjcl4WePKzEyydjdh/jh78N2KoVDeW3nVC/qstaZN4jpoD6z2mG7spuWnXUu1CgnAFym1KA177wB9TlF5B9YMYzRkVwDw5zL066FY2ExUJ1UM3kn/2QKerMYdJjGeR3qkLK1B1ayRnc25DUocO1CdX7QG0H7KcW74bTbHokAKZL0XkAyvwJOcwAGRQZfOblvb1jJZWTtE5EBXP983CE76Bd5mx2rqisQn7LVHK1EuW4ExeKtUKfzEkAnIi6AdFX8NuK29BDLNsQcC2IYk= dshannon@Agile6-A94

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Found @dsinla in the VFS Team Roster - kicking off process.
