### ISSUE TITLE
Update Incident Response Playbook to address Security Incidents

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#42568]
### Description

The[ current incident response playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook) does not clearly address handling of security incidents or have a step for notifying Platform Security.

The gap was identified in [this Slack Thread.](https://dsva.slack.com/archives/CJYRZK2HH/p1654185548204999)

### Tasks

- [ ] Update Incident Response Playbook to address security incidents and the notification of Platform Security team.

### Acceptance Criteria

- [ ] Incident Response Playbook updated to address security incidents and the notification of Platform Security Team.

**Comment by zachclarity** [comment]
@troymosher  Does the [Incident Playbook High Level steps cover security](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook#High-level-steps), since the Pager Duty trigger has security as one of the types ?

**Comment by troymosher** [comment]
@td-usds see Zack question above.  Since the PD trigger has security as one of the types, if the incident response playbook is followed, would that suffice for notifying Platform Security?
