### ISSUE TITLE
AWS access for [Jake Uhteg]

### ISSUE THREAD

**Issue by Jake-Uhteg** [department-of-veterans-affairs/va.gov-team#42570]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Jake Uhteg

### Your Email

jacob.uhteg@oddball.io

### Your Team, Role, and Company

VA Notify, Test Engineer, Oddball

### Product Manager (PM) name and email

Melanie Jones melanie.jones@oddball.io & Megan Siddle megan.siddle@oddball.io

### Product Owner (PO) name and email

Beverly Nelson beverly.nelson@va.gov

### Desired AWS Access

Please copy the permissions for Kyle MacMillan after his account has been created. Github name: k-macmillan AWS Name: OITCOMacmiK

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by Jake-Uhteg** [comment]
Waiting for clarification on label and specific AWS permissions

**Comment by Jake-Uhteg** [comment]
I received some information from another member of my team who had a better understanding of this process. I have updated my request.

**Comment by jsgarmon** [comment]
@Jake-Uhteg : please clarify what AWS account this is for. We don't have a Kyle MacMillan in the dsvagovcloud account. I suspect your request is for a different account.

**Comment by Jake-Uhteg** [comment]
He requested access in ticket 42573. The account may not be finished being created yet

**Comment by oseasmoran73** [comment]
Closing ticket as asking similar resources from #42573 

We are not familiar with the resources being asked

My recommendation would be to sync up with your PO to understand what resource is needed (as it is a bit unclear to me as well). You are more than welcome to join us at our office hours today 10AM PT to try and clarify on what is being asked. Closing ticket
