### ISSUE TITLE
Update documentation to clarify that elevating permissions for existing users with AWS access requires approval

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#42585]
## Description
Existing [AWS access approval process](https://vfs.atlassian.net/wiki/spaces/OT/pages/1800601685/Approve+AWS+access) does not clarify that a request to elevate permissions for existing users also requires approval.

## Background/context 
A recent security incident occurred where an existing AWS user was granted elevated permissions without OCTO-DE approval.

## Tasks
- [x] Update existing AWS access approval process to clarify that elevating permissions for existing users requires OCTO-DE approval.

## Acceptance Criteria 
- [x] Existing AWS access approval process updated to clarify that elevating permissions for existing users requires OCTO-DE approval.

**Comment by oseasmoran73** [comment]
@troymosher When time permits, can you review this ticket? I believe the acceptance criteria has been met. Internal documentation update can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1800601685/Approve+AWS+access)

Moving to review column

**Comment by oseasmoran73** [comment]
Closing ticket as AC have been met. Please feel free to reopen if this is not the case
