### ISSUE TITLE
A VA.gov redirect to "fix" dead link in PIV office email

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4258]
We should add a redirect on VA.gov to "fix" a dead link that is in the PIV appointment confirmation email.

## Background
When you schedule an appoint to get fingerprinted for your PIV card, you get a confirmation email that contains the following bit of text:

> Make sure that you have completed all “Applicant” requirements listed on the HSPD-12 Internet page prior to showing up for your scheduled appointment. See link below:
> 
> Link: http://www.va.gov/PIVPROJECT/How_to_Get_a_VA_ID_Badge.asp 

That is a dead link and likely has been since the new VA.gov rolled out on Veteran's Day 2018.

## Request
We should add a redirect from https://www.va.gov/PIVPROJECT/How_to_Get_a_VA_ID_Badge.asp to some appropriate content. It should probably direct to the "PIV Checklist" section on this page: https://www.oit.va.gov/programs/piv/how-to.cfm. Unfortunately the PIV Checklist section does not have an ID so you can't link directly to it.

To be clear, the VA PIV team needs to update this email to fix the page they are linking to, but we can at least apply a band aid in the meantime.

**Comment by erikphansen** [comment]
@ncksllvn I mentioned yesterday that I had a suggestion for a website redirect for you. Here are the details!

**Comment by ncksllvn** [comment]
Thanks @erikphansen! @mnorthuis is this in your jurisdiction? 🙂

**Comment by mnorthuis** [comment]
I would say this issue needs to be communicated back to the OIT office (or whoever owns that email) to correct.  This page is not one that we have touched as part of WBC and we should not be redirecting unless we have their approval to do so.

**Comment by MickinSahni** [comment]
Thanks, @erikphansen!

@MickinSahni to send jen the email he received so she can reach out, but will close out this particular ticket
