### ISSUE TITLE
Reduce Potential of Accidental Subversion of Process w.r.t. AWS Access requests.

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#42589]
## Description
Members of cross-functional teams fulfilling DevOps roles should not be able to skip the process for AWS access requests and approvals.  

## Background/context 
A recent security incident occurred where an existing AWS user was granted elevated permissions using AWS console by a member of a cross-functional team fulfilling a DevOps role without OCTO-DE approval.

## Tasks
- [x] Reduce the capability of cross-functional teams' attached DevOps Engineers to specific permission sets with a working permissions boundary.

## Acceptance Criteria 
- [x] All members of cross-functional teams fulfilling DevOps roles are able to complete daily tasks and the role/function of their position, without the ability to grant/deny/reduce/elevate IAM permissions.

**Comment by rmtolmach** [comment]
This will probably be solved as part of  https://github.com/department-of-veterans-affairs/va.gov-team/issues/44388.

**Comment by jbritt1** [comment]
With new processes in place that now include a permissions boundary, this can likely be considered complete by the work done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/41203 && https://github.com/department-of-veterans-affairs/va.gov-team/issues/45254.

**Comment by jbritt1** [comment]
We also have a new Slack channel in the DSVA workspace that all current DevOps folks have been added to called #platform-devops.
