### ISSUE TITLE
Plan the agenda/visuals for the meeting with VFS engineering lead(s) to review env setup 

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#426]
## Goal
The goal of this meeting is to provide the VFS team lead(s) additional guidance and support during their initial local env setup, so that they are in a position to then support their own VFS team members directly, during their setup processes.

## Acceptance Criteria
- [x] Creating a meeting summary/agenda that informs VFS team leads, in advance, what to expect from this meeting
  - Establishes any criteria that must be met by the VFS team lead(s), prior to the meeting
  - This should be within a deliverable that can be sent to the VFS team leads in advance
- [x] Any resources that will be used before, during, after the meeting are documented 
- [x] Creation of any visuals, resources, etc., that are necessary to support the meeting/process
  - Including any resources that the VFS team leads can use to help support their team members during setup
- [x] Definition of how long this meeting will last

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by accbjt** [comment]
Google slide

https://docs.google.com/presentation/d/1t768EX-hF3WJHfE3tx1zjELnRlFlMZQAQXEJnvnwRTY/edit#slide=id.p1

**Comment by accbjt** [comment]
@hpjaj @1Copenut Can you take a look at this slide deck and let me know what you think. Trevor did you want to also go over 508 tools and software in this meeting? I can add that also. This is mainly to get them setup for development but not actually going over processes.

**Comment by 1Copenut** [comment]
@accbjt Yeah, I think I'd like to mention 508 tools that FE teams will want to install / use. It'd be high level, but I'll add that to my todo list this week ahead of our dry run meetings.
