### ISSUE TITLE
Sign-in Service Lucid Chart Diagrams Update

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#42618]
### Sign-in Service [LucidChart](https://lucid.app/documents#/documents?folder_id=285167358) diagrams are out of date and need to be updated
- [x] service diagram
- [x] session & tokens attributes diagram
- [x] web diagram
- [x] mobile diagram

**Comment by joeniquette** [comment]
@bosawt please update: https://lucid.app/lucidchart/e8617fa6-f8c4-4691-81c4-4c98a46d6bc2/edit?page=0_0&invitationId=inv_371c3f8b-6386-461b-93f8-dada94436593#
