### ISSUE TITLE
"Open Issues By Product" DOMO Dashboard Support 

### ISSUE THREAD

**Issue by SarahKay8** [department-of-veterans-affairs/va.gov-team#42627]
## Issue Description
 Hi team! I have been working on pulling in Github Product Label data in order to create a visualization in Domo. After a few tries, I got the SQL to run. The SQL has been modified by replacing hyphens with underscores, making all elements lowercase, etc. Even though the SQL was successful, I'm still experiencing issues getting every label to populate data on the bar graph. Data only populates for 2 out of 11 labels. 

---
### Initial Task: (Ticket Reference #34739) 

As a Governance Team member, I want to see the number of issues by product so that I understand known issues.

As an OCTO-DE lead, I want to see number of issues by product so that I can fully understand the scope of issues across products brought through Collaboration Cycle.

Intended Audience: Governance Team and OCTO-DE leads
Desired Outcome: Shared understanding of product health across VA.gov
Due Date: TBD

## Acceptance Criteria
- [ ] With our move to Product focus, we will need new boards and cards providing data on the product labels added to staging reviews in ticket

## Resources
[Current Dashboard SQL Via Google Platform](https://console.cloud.google.com/bigquery?ws=!1m18!1m3!8m2!1s145052845255!2s701613877b0b42baa5ff413ef33f2f80!1m3!8m2!1s145052845255!2sd1bc65fe43504b2c8998c58d21f35f82!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3sgithub_issues!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3sgithub_metrics&pli=1&authuser=1&project=alert-arbor-307717&d=vsp_testing_tools&p=vsp-analytics-and-insights&t=github_issues&page=table)
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathan-epstein13** [comment]
Hello @SarahKay8 ! I'm going to attach the [original slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1653069772196459) as a reference.

**Comment by SarahKay8** [comment]
Hi @chloedotbrown. That is the correct datasource.

Here is the most recent query. 
`with selected as (
SELECT number, state, labels
FROM `vsp-analytics-and-insights.vsp_testing_tools.github_issues`,
    UNNEST(labels) as collab_cycle_feedback,
    UNNEST(labels) as practice_area,
    UNNEST(labels) as experience_standard,
    UNNEST(labels) as touchpoint
WHERE collab_cycle_feedback = 'collab-cycle-feedback'
    or practice_area in ('QA', 'IA', 'Content', 'Design', '508/Accessibility')
    or experience_standard like 'CCIssue%'
    or touchpoint in ('Staging','Midpoint')
),
oc_counts as (select 
countif(state = 'closed' AND unnestLabels = 'caregivers') as caregivers_closed,
countif('launch-blocking' IN unnest(labels) and 'caregivers' IN unnest(labels) and 'open' IN (state)) as caregivers_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'caregivers' IN unnest(labels) and 'open' IN (state)) as caregivers_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'gi_comparison_tool') as gi_comparison_tool_closed,
countif('launch-blocking' IN unnest(labels) and 'gi_comparison_tool' IN unnest(labels) and 'open' IN (state)) as gi_comparison_tool_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'gi_comparison_tool' IN unnest(labels) and 'open' IN (state)) as gi_comparison_tool_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'notifications_preferences') as notifications_preferences_closed,
countif('launch-blocking' IN unnest(labels) and 'notifications_preferences' IN unnest(labels) and 'open' IN (state)) as notifications_preferences_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'notifications_preferences' IN unnest(labels) and 'open' IN (state)) as notifications_preferences_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'hlr') as hlr_closed,
countif('launch-blocking' IN unnest(labels) and 'hlr' IN unnest(labels) and 'open' IN (state)) as hlr_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'hlr' IN unnest(labels) and 'open' IN (state)) as hlr_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'mcp') as mcp_closed,
countif('launch-blocking' IN unnest(labels) and 'mcp' IN unnest(labels) and 'open' IN (state)) as mcp_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'mcp' IN unnest(labels) and 'open' IN (state)) as mcp_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'dt_find_va_form') as dt_find_va_form_closed,
countif('launch-blocking' IN unnest(labels) and 'dt_find_va_form' IN unnest(labels) and 'open' IN (state)) as dt_find_va_form_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'dt_find_va_form' IN unnest(labels) and 'open' IN (state)) as dt_find_va_form_open_not_blocked,
countif(state = 'closed' AND unnestLabels = '686') as six_eight_six_closed,
countif('launch-blocking' IN unnest(labels) and '686' IN unnest(labels) and 'open' IN (state)) as six_eight_six_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and '686' IN unnest(labels) and 'open' IN (state)) as six_eight_six_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'sign_in_page') as sign_in_page_closed,
countif('launch-blocking' IN unnest(labels) and 'sign_in_page' IN unnest(labels) and 'open' IN (state)) as sign_in_page_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'sign_in_page' IN unnest(labels) and 'open' IN (state)) as sign_in_page_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'hce_checkin') as hce_checkin_closed,
countif('launch-blocking' IN unnest(labels) and 'hce_checkin' IN unnest(labels) and 'open' IN (state)) as hce_checkin_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'hce_checkin' IN unnest(labels) and 'open' IN (state)) as hce_checkin_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'hrt') as hrt_closed,
countif('launch-blocking' IN unnest(labels) and 'hrt' IN unnest(labels) and 'open' IN (state)) as hrt_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'hrt' IN unnest(labels) and 'open' IN (state)) as hrt_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'outreach and events') as  outreach and events_closed,
countif('launch-blocking' IN unnest(labels) and 'outreach and events' IN unnest(labels) and 'open' IN (state)) as  outreach and events_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'outreach and events' IN unnest(labels) and 'open' IN (state)) as  outreach and events_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'typeahead') as  typeahead_closed,
countif('launch-blocking' IN unnest(labels) and 'typeahead' IN unnest(labels) and 'open' IN (state)) as  typeahead_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'typeahead' IN unnest(labels) and 'open' IN (state)) as  typeahead_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'vanotify') as  vanotify_closed,
countif('launch-blocking' IN unnest(labels) and 'vanotify' IN unnest(labels) and 'open' IN (state)) as  vanotify_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'vanotify' IN unnest(labels) and 'open' IN (state)) as  vanotify_open_not_blocked,
countif(state = 'closed' AND unnestLabels = 'virtual_agenty') as  virtual_agent_closed,
countif('launch-blocking' IN unnest(labels) and 'virtual_agent' IN unnest(labels) and 'open' IN (state)) as  virtual_agent_open_blocked,
countif('launch-blocking' NOT IN unnest(labels) and 'virtual_agent' IN unnest(labels) and 'open' IN (state)) as  virtual_agent_open_not_blocked,
from selected,
UNNEST(labels) AS unnestLabels
)
 select 'caregivers' as name, caregivers_open_blocked as open_blocked, caregivers_open_not_blocked as open_not_blocked, caregivers_closed as closed from oc_counts
 union all select 'gi_comparison_tool' as name, gi_comparison_tool_open_blocked as open_blocked, gi_comparison_tool_open_blocked as open_not_blocked, gi_comparison_tool_closed as closed from oc_counts
 union all select 'notifications_preferences' as name, notifications_preferences_open_blocked as open_blocked, notifications_preferences_open_blocked as open_not_blocked, notifications_preferences_closed as closed from oc_counts
 union all select 'hlr' as name, hlr_open_blocked as open_blocked, hlr_open_blocked as open_not_blocked, hlr_closed as closed from oc_counts
 union all select 'mcp' as name, mcp_open_blocked as open_blocked, mcp_open_not_blocked as open_not_blocked, mcp_closed as closed from oc_counts
 union all select 'dt_find_va_form)' as name, dt_find_va_form_open_blocked as open_blocked, dt_find_va_form_open_not_blocked as open_not_blocked, dt_find_va_form_closed as closed from oc_counts
 union all select '686' as name, six_eight_six_open_blocked as open_blocked, six_eight_six_open_not_blocked as open_not_blocked, six_eight_six_closed as closed from oc_counts
 union all select 'sign_in_page' as name, sign_in_page_open_blocked as open_blocked, sign_in_page_not_blocked as open_not_blocked, sign_in_page_closed as closed from oc_counts
 union all select 'hce_checkin' as name,hce_checkin_open_blocked as open_blocked, hce_checkin_open_not_blocked as open_not_blocked, hce_checkin_closed as closed from oc_counts
 union all select 'hrt' as name, hrt_open_blocked as open_blocked, hrt_open_not_blocked as open_not_blocked, hrt_closed as closed from oc_counts
 union all select 'outreach and events' as name, outreach and events_open_blocked as open_blocked, outreach and events_open_not_blocked as open_not_blocked, outreach and events_closed as closed from oc_counts
 union all select 'typeahead' as name, typeahead_open_blocked as open_blocked, typeahead_open_not_blocked as open_not_blocked, typeahead_closed as closed from oc_counts
 union all select 'vanotify' as name, vanotify_open_blocked as open_blocked, vanotify_open_not_blocked as open_not_blocked, vanotify_closed as closed from oc_counts
 union all select 'virtual_agent' as name,  virtual_agent_open_blocked as open_blocked, virtual_agent_open_not_blocked as open_not_blocked,  virtual_agent_closed as closed from oc_counts`
`


The Github data we are trying to populate are "total issues by product" which are the issue tickets our team has created during staging review. 

All staging issue tickets are following [Anatomy of a Staging Review Ticket](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/38075) as a guide.

The Issue Tickets all have CC-Dashboard and the CollabCycle-feedback labels attached to them. If you want to search each product you can filter it by adding product labels such as “HLR” “1010-ez" "Caregivers" , etc. 


Quering in GitHub. 
\

**Comment by chloedotbrown** [comment]
Thanks @SarahKay8 - this is exactly the info I was hoping for. Have a wonderful weekend!

**Comment by SarahKay8** [comment]
> Thanks @SarahKay8 - this is exactly the info I was hoping for. Have a wonderful weekend!

You as well! Much appreciated!

**Comment by SarahKay8** [comment]
@shiragoodman

**Comment by chloedotbrown** [comment]
Hey @shiragoodman - this is all Domo, so no BigQuery access would be needed. If you go to the "Settings" tab at the top and click "Details," you should be able to see it. You and Sarah have the same Domo permissions-levels, so if she's been able to create the data, I imagine you should be able to view. If not, let me know!

**Comment by chloedotbrown** [comment]
Hi @SarahKay8 - I'm still working on this, but wanted to give you an update. I ended up building off the version of the SQL that had been in the DOMO connector, because I noticed there were some syntax errors in the version above. 

One thing that was definitely causing an issue was a couple incorrect label assignments. For example, "Caregivers" in the labels data is lowercase, so the `'Caregivers` tag in the code was missing all these tickets. Similarly, there isn't anything in the data for "notifications-preferences", so I switched it to the "notification-settings" label that sounded like the same thing. 

Take a look at your totals and see if they're closer to what you were expecting? I'm out tomorrow, but will continue looking into this issue on Tuesday.

Finally, once the data output issue is resolved, I'd also love to do a quick restructure of this code so it's a little easier to read and you don't have to make changes in as many places when new products get added or tags change.

**Comment by SarahKay8** [comment]
@chloedotbrown gotcha! Thanks so much. Taking a look now.

**Comment by shiragoodman** [comment]
thank you so much @chloedotbrown . Our focus right now is to try and get this data set correct before we continuing to build out different cards. Would it be possible to set up a meeting to review the issues you documented above? I want to make sure the rest of the team is familiar (and not just Sarah) so that we can have more folks on our team supporting our dashboards in the future. Please let me know.

**Comment by chloedotbrown** [comment]
Hey @shiragoodman - yes, we can definitely set up a time to go over with your team. Do you want to coordinate with the folks on your end who should be there and [find a time](https://calendar.google.com/calendar/u/0?cid=Y2hsb2UuYnJvd25AYWRob2N0ZWFtLnVz)? Tomorrow or later on this week should have some good options.

**Comment by chloedotbrown** [comment]
@shiragoodman - Happy to wait for Sarah! I agree, it'll be a better conversation when she's back. 

Unfortunately, my team's got our grooming session at that time next week. Would 6/29 at 12-1pm, 2-2:30pm, 3-3:30pm, or 4:30-5pm ET work for you and your team? Both @michelle-dooley and I are available at those times, and it would be great to get her in the session as well.

**Comment by SarahKay8** [comment]
Hi @chloedotbrown any time after 1 PM est would be fine with me

**Comment by chloedotbrown** [comment]
Great, just sent out an invite! @shiragoodman, I've included Sarah and Chase from your team since I know they've been working on this, but feel free to add anyone else who should be there to the invite. Look forward to chatting then!

**Comment by shiragoodman** [comment]
great! thank you @chloedotbrown .

**Comment by chloedotbrown** [comment]
Hey @shiragoodman - wanted to follow up! Can you send a quick description of the Github data your team would like filtered and I can update the Domo connector so we can close this ticket out? Thanks so much!

**Comment by shiragoodman** [comment]
thank you @chloedotbrown ! I think this will work. 

Can you point me to guidance on Confluence for how to build cards? Now that we have the data pulled in, I'd like to play around with how best to visualize it. Please let me know!

**Comment by chloedotbrown** [comment]
Hey @shiragoodman - we'll be working on developing some custom Domo trainings, since so many Platform teams we'll be working in it soon. But in the meantime, I'd recommend [Domo's e-learning trainings](https://learndomo.domo.com/pages/15/elearning) to get started (you'll need to just enter "va-gov" at the popup to get in). 

As for Confluence resources, you can also take a look at our internal [Building Standardized KPI Dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/Build+standardized+KPI+dashboards) documentation. It's geared towards our team members and may not cover all the basics or give more guidance than you need right now, but you're welcome to take a look!

For now, I'm going to close out this ticket, since it sounds like the data part of this work is complete.
