### ISSUE TITLE
IA intake request from Auth Exp My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42634]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
  
We are working with the Identity team to implement a redirect post-log-in from the VA.gov homepage to My VA (va.gov/my-va). The redirect will only be implemented when the user logs in from the homepage - no other locations on VA.gov. There are no other design or code changes to My VA. It is a redirect to the existing page as it currently stands.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
8/10 - 8/23
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [My VA redirect initiative brief]([My VA Redirect initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-redirect#my-va-redirect-initiative-brief))
- Link to or attach user flows: NA
- Link to prototype or mockups: NA
- Link to any epics/issues that may be helpful: NA

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: 7/27 - 8/9 (25%)
- Estimated staging review date: 7/13 - 7/26
- Content and IA work needed by: 6/28

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: @Samara-Strauss 
-	Product manager: @ajakabcin 
-	Designer: @aagosto90 
-	FE engineer: @tmitchellgcio 
-	Product/team Slack channel: accountexp-authexp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Description of implementation from slack:

> [Alexander Garcia](https://app.slack.com/team/U018M85FA2K)  [18 hours ago](https://dsva.slack.com/archives/C01K37HRUAH/p1654802994145239?thread_ts=1654802052.243209&cid=C01K37HRUAH) 
Sure Mikki, the current implementation is whichever page the user is currently on, before redirecting to sign in via (ID.me, etc.) the current URL is saved in the session storage.  The proposal is to create some logic to check if the user is on the homepage URL and if they are and the feature toggle is enabled, to update the session storage URL to the /my-va page upon the return to [VA.gov](http://va.gov/) (edited)


Based on implementation approach, there is no IA work needed for this.  Thanks!
