### ISSUE TITLE
List of all resources in EKS clusters

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#42635]
# Description

I would like to get a listing of all Deployments, StatefulSets, DaemonSets and Jobs currently running in our EKS clusters. This snapshot is for investigation purposes.

# Acceptance Criteria

I receive on my VA e-mail an e-mail with one file per requested resource type per cluster. The file is the output of the `kubectl` invocation to list the requested items; conceptually the equivalent of:
```sh
for CLUSTER in utility dev staging prod; do
    kubectl config set-cluster ${CLUSTER?}
    for RESX in Deployments StatefulSets DaemonSets Jobs; do
        kubectl get ${RESX?} --all-namespaces > ${CLUSTER?}.${RESX?}.txt
    done
done
```

**Comment by td-usds** [comment]
NOTE: this is **not** super high priority

**Comment by ianhundere** [comment]
the following was run:
```
for cluster in utility dev staging sandbox prod; do
    for resources in deployments statefulsets daemonsets jobs cronjobs; do
        kubectl get $resources --all-namespaces --context=$cluster >> ${cluster}.${resources}.txt
    done
done
```
dev
[https://app.zenhub.com/files/133843125/8a92dc08-3a53-4b25-8b97-75728ee1390f/download](https://app.zenhub.com/files/133843125/8a92dc08-3a53-4b25-8b97-75728ee1390f/download)
staging
[https://app.zenhub.com/files/133843125/40bfeaa6-10f1-4adc-8777-2cd2b28c1be3/download]
(https://app.zenhub.com/files/133843125/40bfeaa6-10f1-4adc-8777-2cd2b28c1be3/download)
utility
[https://app.zenhub.com/files/133843125/81d3cd12-c441-481a-9094-9b64671689a1/download](https://app.zenhub.com/files/133843125/81d3cd12-c441-481a-9094-9b64671689a1/download)
sandbox
[https://app.zenhub.com/files/133843125/fed91d1a-dfb0-4920-98eb-ebb20506788f/download](https://app.zenhub.com/files/133843125/fed91d1a-dfb0-4920-98eb-ebb20506788f/download)
prod
[https://app.zenhub.com/files/133843125/d3b2bfc8-db89-4483-8ba8-0a80889a02ce/download](https://app.zenhub.com/files/133843125/d3b2bfc8-db89-4483-8ba8-0a80889a02ce/download)
