### ISSUE TITLE
SOCKS access for Mohammed Shamsuddin

### ISSUE THREAD

**Issue by mdshibu76** [department-of-veterans-affairs/va.gov-team#42636]
### Your Name

Mohammed Shamsuddin

### Your Email

mohammed.shamsuddin@va.gov

### Your Role and Team

Data Engineer

### Product Manager (PM) name and email

Zaheda Haidri

### Product Owner (PO) name and email

zaheda.haidri@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDduxlr9JIqqEhKBy1RvDKd/X9hckJq5dZHvVruIVMKmM9uwh+QzzQ817KKcjiDC/gXiTaLTWAKaxJi+0ciXyKBL3VVO/6haGRUXGg264PyLiJNaCvFBW6B7Q22qaH28pLP+4aTUHI15NtSf3ctLOG9UzXEiAmVicclCUAGGUIped8oMM519sDrfUTyF5K2w0BitiCu7fDijwRWn0VgyXC+asEDekpMQt7lG45067kNwyyzSkN4lrcSgqF+bJq4Ao0V2BS6ZmxSsR57hwiDQoZI6jCYRwh4VGD7Cy/qGaWdVgSu3Qz+SfOTZ9FpnOgEVE3djoa+3066N2yv8B1Jaj+zf/jRZsfQTAK3IIOJKvIinm1wocd4YYqz3dg4fxQaqwUEElWq7gUpEwUTIS9TqAE2/brfMZyUfuSOYsaVj9xvbIQQXKTqeE1EsHnWJyZgEf3TTJ6MeS/OJymT+ahVi9/XfXbut7ETR1nOxNb4xzWT7VI8SgtbptJJ7zlCZYuNBAs= shibushamsuddin@Shibus-MBP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@mdshibu76 found in the VFS team roster
