### ISSUE TITLE
Design Intent - Design Feedback - Benefits Team 2: Adding medical copays to the Financial Status Report (VA Form 5655)

### ISSUE THREAD

**Issue by naomimarcussen** [department-of-veterans-affairs/va.gov-team#42645]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- It's great to see the user flow and plans for iterating!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
n/a

**Should:**
n/a

**Consider:**
Consider replacing the [Wizard pattern](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691610/simulate/sitemap?mode=i) with a more accessible '[Check a service is suitable](https://design-system.service.gov.uk/patterns/check-a-service-is-suitable/)' pattern or 'one thing per page' as suggested on the [Wizard pattern in the design system](https://design.va.gov/patterns/wizards). If you do opt to include this new pattern, we encourage you to [contribute your learnings to the design system](https://design.va.gov/about/contributing-to-the-design-system) so others can benefit from your work as well.

## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by humancompanion-usds** [comment]
@rileyorr - I will go one step further and offer to help co-design a replacement for the deprecated Wizard pattern. USDS has recently used the "One thing per page" paradigm on beta.ssa.gov which tested well and which you can see here: https://beta.ssa.gov/prepare/check-eligibility-for-benefits

Let me know if there is any way in which I can support this effort. We really want to get an example of a replacement pattern into the design system a.s.a.p. Thanks!

**Comment by denisecoveyduc** [comment]
**Feb 10, 2023 Update:** We plan to update this wizard when we get to this body of work [[Epic #48133](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48133)] I have integrated these feedback comments to ensure they are captured when we get to it.  Closing this ticket. Please reach out with any questions.
