### ISSUE TITLE
SOCKS access for Christian

### ISSUE THREAD

**Issue by christianmburk** [department-of-veterans-affairs/va.gov-team#42678]
### Your Name

Christian Burk

### Your Email

christian.burk@civicactions.com

### Your Role and Team

Drupal Site Builder, Facilities 

### Product Manager (PM) name and email

David Shannon, david.shannon@agile6.com

### Product Owner (PO) name and email

Dave Conlon, david.conlon@va.gov

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDa3BqCSltMDWQZdB6dRIkrUBLWAy9OUkv0VjbaMLCN2dsLtNdjifzXdiBsF4BluMPUStwPLkBZWTwufeJLY4Yng1RsKkatRn5qBRCdcjcyzj59lFXiHLzoK598Wys57Y5zwQCFBpgyXmMhXEsQOoJ3gxV15455av4yxPwvPdJfAvx1KIladrEurZiTr1atSI9ltoTTkRBdZmdjGV3tUV8eOTzihpf2Gt+5tiFPF08JBKGDhwxG8DNnaCSww1P3Km60hEnstG3B4dvEkKeFyP5tDcQFr6oYeJJYq7FzZHmK22yx88xvZ31YNce5F7+jHO72xd7kSZ0Jlto9goBGHzRW/pCeSl7ITQO2hkyNFxUBszxmZz/IyeyAhcwySBgf710Xu61G+/nxeM6qmi/88ELHytOXAefLUQaC/Gu/9K65RlBl4bv7bhqt4bxsGC/zne9FDkOlbOgowFKOxoeE0TsPdmi5euatYMnEIvnNY63wzbeH5ezW74bYX3xEqoJ8kyU= christianburk@MacBook-Pro-2.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@christianmburk is in the VFS Platform team roster

**Comment by kjduensing** [comment]
@christianmburk - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
