### ISSUE TITLE
AWS access for Kristen Brown

### ISSUE THREAD

**Issue by kristen-brown** [department-of-veterans-affairs/va.gov-team#42670]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kristen Brown

### Your Email

kristen.brown@adhocteam.us

### Your Team, Role, and Company

EVSS/Documents (VA API), Senior Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Kelly Lein, kelly.lein@adhocteam.us

### Product Owner (PO) name and email

Premal Shah, premal.shah@va.gov

### Desired AWS Access

Please mirror all access that Mark Viterna has (including prod access and all accesses given under the AWS Console).

### Access Expiration

Ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by mviterna** [comment]
team-matsumoto was/is Caracal, and we can keep the group name for simplicity

**Comment by mviterna** [comment]
Here is the ticket we copied: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33204 in addition to lighthouse-matsumoto she'll need "adhoc-vetsgov-ssm-prod". Probably easiest to do all including   "dsva-vagov-developers",
    and    "lighthouse-developers", since I'm not sure what those do, but I'm guessing she will need those along with forced MFA.

**Comment by td-usds** [comment]
I'll leave the concrete implementation for which groups/policies need to be applied to the infrastructure team.
Thank you @mviterna for the detailed explanation! :)

AWS Access approved based on the requirements in https://github.com/department-of-veterans-affairs/va.gov-team/issues/42670#issuecomment-1157940232.

**Comment by mleclerc00** [comment]
aws account info passed on to user

**Comment by ianhundere** [comment]
@kristen-brown would also like access to update parameter store as per this request / similar tickets:
- [slack chat](https://dsva.slack.com/archives/CBU0KDSB1/p1667835069742319)
- https://github.com/department-of-veterans-affairs/devops/pull/12187
- https://github.com/department-of-veterans-affairs/devops/pull/12186
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/45799
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/46302

**Comment by td-usds** [comment]
approved

**Comment by kristen-brown** [comment]
I would like to request access to add and delete subscriptions for the following AWS SNS topics:
- VetsGov_Dev_VBADocuments_Uploads
- VetsGov_Staging_VBADocuments_Uploads
- VetsGov_Sandbox_VBADocuments_Uploads
- VetsGov_Prod_VBADocuments_Uploads

These topics are a part of the Benefits Intake API functionality, which I support.

**Comment by td-usds** [comment]
Approved
