### ISSUE TITLE
[SPIKE] [BUG] Users Starting on Bottom of Page after Login

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42684]
## Time box
1/2-1 hour

## Potential Bug
Work with engineers to replicate (and correct, if possible) the scenario where users are starting lower on the page after identity verification

**Comment by brdunfield** [comment]
The closest I can come to replicating this is during a loading screen. If the user has scrolled down far enough, during the loading screen they just see the footer (and so have no idea the app is loading). Once the demographics or appointment page loads, the page auto focuses and scrolls back up to the heading.

I'll look into a quick fix to scroll up to the top of the loading screen.
