### ISSUE TITLE
E-Checking edits [6/16/2022]

### ISSUE THREAD

**Issue by Cmjones233** [department-of-veterans-affairs/va.gov-team#42689]
The following edits listed in the definitions excel need to happen:

- [x] 1

- [x] 17

- [x] 19

- [x] 26

- [x] 29

- [x] 30

- [x] 31

**Comment by Cmjones233** [comment]
edits made and reviewed internally. Reviewing with Shawn

**Comment by lindsay-insco** [comment]
Pending follow-up from Steven Barrs and Allison

**Comment by lindsay-insco** [comment]
Edits this round are completed. Refer to @aschulhof for final decision on ticket

**Comment by lindsay-insco** [comment]
Confirmation above.
