### ISSUE TITLE
<Review of new design component - Opt-in> from <1095-B / VA Profile>

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#42694]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  July - Dec 2022; component will be blocked by HEC legal review 

  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Tracey Mulrooney
-	Product manager: Munish Sikka
-	Designer: Thomas McCue / Carl Dickerson
-	FE engineer: Teagan Stephenson
-	Product/team Slack channel: 1095-B

_**We will be adding a component (opt-in) to a product currently in staging**

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by tameracorson** [comment]
[https://app.zenhub.com/files/133843125/d3dba8b5-6e69-401e-acf6-e89ff04e475a/download](https://app.zenhub.com/files/133843125/d3dba8b5-6e69-401e-acf6-e89ff04e475a/download)

**Comment by katherine-fung** [comment]
Hi @tameracorson @CarlDickerson @tmccue @khandelwal, 

I'm working on the messaging for opting in to paperless delivery, and I have 2 questions: 

1. One of the message options says: "If you would like to save paper and _only get this form online when you need it_, you can opt-in to paperless delivery by updating your delivery preferences in your profile."

If someone chooses paperless delivery, how will they get the form online? Will they get the 1095-B emailed to them once a year, or will the form be available for download only?

2. Will choosing paperless delivery for the 1095-B affect the delivery preferences for any other communications?

**Comment by CarlDickerson** [comment]
@katherine-fung 
- If someone chooses paperless delivery, they will receive a yearly notification via email (or text) that their document is ready for download. The form will not be emailed to them. They will be sent the link to the 1095-B download page for self-service retrieval. Opting into paperless delivery means that they will no longer receive the paper version mailed.
- 1095-B will be a stand-alone preference. It will not affect any of their other communication preferences.

**Comment by laurwill** [comment]
Hi @tameracorson and @CarlDickerson , I believe your team is joining office hours in just a few moments to talk about this content, but wanted to share our suggested language here for reference: 

**Choose paperless delivery**
We mail you a paper copy of your 1095-B form each year. If you want to stop getting paper forms, you can choose paperless delivery. We'll email or text you once a year when your new form is ready to download.

Go to your VA.gov profile to choose 1095-B paperless delivery

And wanted to confirm — will the link bring users directly to their delivery preferences?

**Comment by laurwill** [comment]
Hi @CarlDickerson and Thomas, thanks for coming to office hours today! It was great talking through this content with you both. 

Following up on the question about link formatting — I checked with Danielle, and she and the OCTO design lead recommend:
- Using a [secondary action link](https://design.va.gov/components/link/action) for "Go to your VA.gov profile to choose 1095-B paperless delivery"
- Changing the now-deprecated green button above this content for "Download your 1095-B tax form (PDF)" to a new [primary button](https://design.va.gov/components/button/)

Let us know if you have any questions, feedback, or more review needs here!

**Comment by tameracorson** [comment]
Hi @laurwill Our engineer @stephte  is updating to the new primary button on the MVP in staging to reflect the removal of deprecated design and @tmccue will update the design and get it back to you all today.

**Comment by CarlDickerson** [comment]
@laurwill following up to let you know that we have updated the design to match your previous feedback and suggestions above. The download button has been now replaced with a primary button (blue button) and the click through to VA. profile paperless delivery has been changed to a secondary link. Please find attached, updated design high fidelity [sketch](https://www.sketch.com/s/2f061f33-42de-4d8f-83ad-40286632ba36/a/Kv1jVGV). This has also been updated to reflect changes on our side in staging.![1095-b_Auth_063022.jpg](https://images.zenhubusercontent.com/61ae74788b36cd6592f0fc2d/c3d7da9f-333d-4f7a-b866-681fe040dcf5)
