### ISSUE TITLE
[Bug] Combined Debt Portal - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#42709]
## What happened?
In **Staging Combined Debt Portal**, the following content/styling anomalies were found:
- (1) **Your VA debt and bills** page: Page-title ended with "**...bill**".
- (2) **Current copay balances** page > **How to pay...** section:
  - (2a) Expanded **Option 1...** accordion:
    - (2a1) **Account Number** was missing.
    - (2a2) **Time-zone** format was **3-letter** ("**EST**").
  - (2b) Expanded **Option 2...** accordion: **Account Number** was missing.
  - (2c) Expanded **Option 3...** accordion: **Account number** was missing.
  - (2d) Expanded **Option 4...** accordion:
    - (2d1) **visit-destination** was missing.
    - (2d2) **facility-address** was missing.
- (3) **Current VA debt** page
   - (3a) **Current debts** section: **Debt-cards**' **Check details...** link was not bold.
   - (3b) **How to dispute...** section: **Time-zone** format was **3-letter** ("**CST**").

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: **`vets.gov.user+81@gmail.com` (Travis)** [Has-both-copay-and-debt use-case]

## Steps to Reproduce

1. Go to **[Staging Homepage](https://staging.va.gov/)**, and sign in via **ID.me** as **`vets.gov.user+81@gmail.com` (Travis)**.  [See [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for passwords].
2. Go to **[Your VA debt and bills](https://staging.va.gov/manage-debt-and-bills/summary)** page, and observe that (1) **page-title** ends with "**...bill**".
3. In **Copay-bill-summary-card**, click **Check your balance...** link.
4. On **Current copay balances** page, in **How to pay...** section, expand **Option 1...** accordion, and observe that (2a1) **Account Number** is missing and (2a2) **time-zone** format is **2-letter** ("**EST**").
5. Expand **Option 2...** accordion, and observe that (2b1) **Account Number** is missing.
6. **Back** on **Your VA debt and bills** page, in **Debt-summary-card**, click **Check the status...** link.
7. On **Current VA debt** page, in **Current debts** section, observe that **Debt-cards**'s **Check details...** links are not bold.
8. In **How to dispute** section, observe that (3b) **time-zone** format is **3-letter** ("**CST**").

### Screenshot(s)
![image](https://user-images.githubusercontent.com/587583/173255602-634f1abe-716a-4d00-8cd7-f8c87e589a87.png)

![image](https://user-images.githubusercontent.com/587583/173260539-e2158d8a-7a54-4176-b668-ba297d8fa8f4.png)

![image](https://user-images.githubusercontent.com/587583/173663429-ec3bffca-095d-4fe0-8eb2-9b98d2dee03d.png)

![image](https://user-images.githubusercontent.com/587583/173258455-dc26ed76-12d3-4a8e-b1ec-3be6a92e9b60.png)

## Desired content/styling
- [x] (1) **Overview** page: **Page-title** should end with "**...bills**": 
    ![image](https://user-images.githubusercontent.com/587583/173255750-b6e97055-de87-4dc0-af3a-911b59871aeb.png)
- (2) **Current copay balances** page > **How to pay...** section:
  - (2a) Expanded **Option 1...** accordion:
    - [x] (2a1) **Account Number** should be displayed.
    - [x] (2a2) **Time-zone** format should be **2-letter** ("**ET**").
  - [x] (2b) Expanded **Option 2...** accordion: **Account Number** should be displayed.
  - [x] (2c) Expanded **Option 3...** accordion: **Account number** should be displayed.
  - (2d) Expanded **Option 4...** accordion:
    - [x] (2d1) **visit-destination** should be displayed.
    - [x] (2d2) **facility-address** should be displayed.
- (3) **Current VA debt** page:
  - [ ] (3a) **Current debts** section: **Debt-cards**' **Check details...** links should be bold: 
    ![image](https://user-images.githubusercontent.com/587583/173664290-25353867-4184-4cf5-abf3-d7046a3fe2c1.png)
  - [x] (3b) **How to dispute...** section: **Time-zone** format should be **2-letter** ("**CT**").

## Acceptance Criteria
[see **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by OptionSelect** [comment]
Commenting to keep track. 
1. Bills is what appears based on fix from previous Prestaging review from Riley.
2. Account num now renders properly but is using first of potentially multiple account nums on that page due to way balances are now listed. Per https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/40221 I was asked to remove certain addresses but these are now updated as well and render successfully I believe.
![image](https://user-images.githubusercontent.com/29178824/175547251-634f8377-d840-49ed-beac-af22e3d92848.png)

![image](https://user-images.githubusercontent.com/29178824/175546668-ca503b88-0e49-40b8-b96c-1e0ac2a54f6b.png)

3. The below exists based on pre staging review as well, should satisfy bold requirements I believe. 
![image](https://user-images.githubusercontent.com/29178824/175545366-64d7db96-8450-4252-9619-c60f4682e976.png)

![image](https://user-images.githubusercontent.com/29178824/175547743-eee5f0d3-0a20-4388-9c2c-6e7fb7cee7e1.png)

**Comment by tlei123** [comment]
@OptionSelect , after signing into Staging as 81, are you able to get to the [overview page](https://staging.va.gov/manage-debt-and-bills/summary) right now?

I just tried going there after sign-in, but for some reason kept getting redirected to auth'd Homepage.

**Comment by OptionSelect** [comment]
@tlei123 I am experiencing this as well. @Dr-Pongo Are you experiencing this behavior? The content updates above wouldn't have dealt with the authentication portion.

**Comment by Dr-Pongo** [comment]
@tlei123 @OptionSelect Feature Flipper got toggled on staging! We just need to switch it back

**Comment by tlei123** [comment]
@OptionSelect , confirming here that redirect issues' not related to Flipper...

@Dr-Pongo , I just double-checked Staging flipper settings.  Confirming here that it's conditionally-enabled for about a dozen test-users incl. 81.  Redirect issue still persists.

**Comment by OptionSelect** [comment]
Good morning! I've updated the flipper in staging and was able to get in without getting bounced by the redirect on user 81. When I checked the flipper there were no specific users updated it looked like for me but I went ahead and enabled everyone!

![image](https://user-images.githubusercontent.com/29178824/175973556-b18d94a2-1a23-4f18-b938-7557ecb916d7.png)

![image](https://user-images.githubusercontent.com/29178824/175973565-463e6bb5-92c0-4800-9654-b56751f4ac7a.png)

**Comment by tlei123** [comment]
Thx, @OptionSelect !  Yes, the Staging CDP overview page is now loading.

Looks like the **Copays endpoint**'s throwing **500s** right now &mdash; I'm seeing the same Copays error-message w/ test-user 81 that you saw, and same w/ 80 [Has-Copays-only].  cc @Dr-Pongo

**Comment by OptionSelect** [comment]
@tlei123 Of course! Happy to help. As far as we know at the moment that copays link is 500ing due to something on VBS's side breaking our stuff but that is current knowledge of last week and may no longer be correct.

**Comment by tlei123** [comment]
@OptionSelect , thanks much!  All fixes successfully validated in Staging EXCEPT **(3b) Debt-cards details-links still not in bold**:
![image](https://user-images.githubusercontent.com/587583/176941443-237997e4-bd3f-4fd6-a233-bbf65b272bc6.png)

@denisecoveyduc  ,  definitely _not_ a launch-blocker, but should be a real quick fix.

**Comment by OptionSelect** [comment]
Strange that the class doesn't work! I'll play around with it and get a fix in asap! @tlei123

**Comment by tlei123** [comment]
Clsoing now.  Fix for remaining anomaly (3b) now successfully validated in Staging.
