### ISSUE TITLE
[Bug] Combined Debt Portal - Overview page - Debt error for test-user 80

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#42710]
## What happened?
On **Staging Your VA debt and bills** page, signed-in as **`vets.gov.user+80@gmail.com` (Oscar)**, an **error-message** was displayed instead of expected No-debts alert.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: **`vets.gov.user+80@gmail.com` (Oscar)** [Copay-bill-only use-case]

## Steps to Reproduce

1. Go to **[Staging Homepage](https://staging.va.gov/)**, and sign in via **ID.me** as **`vets.gov.user+80@gmail.com` (Oscar)** on## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: **`vets.gov.user+80@gmail.com` (Oscar)**

## Steps to Reproduce

1. Go to **[Staging Homepage](https://staging.va.gov/)**, and sign in via **ID.me** as **`vets.gov.user+80@gmail.com` (Oscar)**.  [See [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for passwords].
2. Go to **[Your VA debt and bills](https://staging.va.gov/manage-debt-and-bills/summary)** page, and observe unexpected **error-message** in **Debt and bill overview** section.
 [See [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for passwords].
2. Go to **[Combined Debt Portal Overview](https://staging.va.gov/manage-debt-and-bills/summary)** page, and observe unexpected **error-message** in **Debt and bill overview** section.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/587583/173257708-30038aad-5c39-4daa-bc66-ff103f6ff2d2.png)

## Desired behavior
 - [ ] **[Combined Debt Portal Overview](https://staging.va.gov/manage-debt-and-bills/summary)** page **Debt and bill overview** section should display **No-debts alert** for Debts instead of error-message.
     ![image](https://user-images.githubusercontent.com/587583/173257769-5972a4fc-12f2-41f2-af3d-19c225eb7f01.png)

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Dr-Pongo** [comment]
@tlei123 Hey! @ScottyRJames worked some magic and this is now resolved! We had some issues with our test users, but I just checked it out on staging and it should be good to go!

**Comment by tlei123** [comment]
Validated in Staging.
