### ISSUE TITLE
User should see the address they entered when going back to edit their address

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4271]
@tlei123  originally asked out this here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4250#issuecomment-565662819

Copied here:

@artistgreen , got a quick question about the **Edit address** link in the modal's validation screen...

Under **You entered**, when you click **Edit address** below your updated (new) address, would you expect the updated address to pre-populate the address form, or the original (old) address?

 I was kinda expecting the updated (new) address to pre-populate the form \[as in, "ooh, I made a little typo so I should be able to quickly fix that by clicking the Edit link"], BUT instead I saw the original (old) address pre-populate.

Please let me know.  We can always run a Slack-call when I come online Monday morning if need be.

Thanks much!

**Comment by erikphansen** [comment]
@artistgreen @Justin-Pickett @Samara-Strauss can you validate that going back to edit an address from the validation screen works as expected now?

**Comment by Samara-Strauss** [comment]
This looks good to me. I think it's OK that it shows the old address since the new address would not have saved yet.

**Comment by erikphansen** [comment]
@Samara-Strauss this should work as intended now

**Comment by Samara-Strauss** [comment]
Validated!
