### ISSUE TITLE
Sidekiq workers deployment to EKS

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#42712]
## Description
As part of moving vets-api to K8s, we will need to move the Sidekiq workers into a new deployment

## Acceptance Criteria
- [x] Sidekiq resource is moved into the manifests repo
- [x] Workers are running as a new k8s deployment

**Comment by RachalCassity** [comment]
Found this[ sidekiq wiki](https://github.com/mperham/sidekiq/wiki/Kubernetes)

**Comment by laineymajor** [comment]
Needs cleanup. Duplicate of work about to be done.
