### ISSUE TITLE
Additional slide in presentation deck conveying survey timeline

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#42731]
## Issue Description
Need to insert additional slide into Survey results presentation that explains the timeline of the survey (release, synthesis, results publishing)

---
## Tasks
- [x] Add slide that explains the timeline of the survey (release, synthesis, results publishing)

## Acceptance Criteria
- [x] Slide is added to presentation deck template

**Comment by tayism** [comment]
@steel36 What was the reasoning behind this again? I am trying to decipher where in the presentation this would make the most sense -- in the beginning, or end? 

I am leaning more toward the beginning, as it seems like a helpful guide for teams to be aware of our process, but I am in need of a bit more clarity. Thanks!

**Comment by steel36** [comment]
@tayism Ray had asked for such a timeline to be included so people had a high view of how it worked.  

Your selected location looks like the right pick, and the content meets the criteria that I understood from him as well.

**Comment by tayism** [comment]
@steel36 Great! Thanks for that info. Glad to hear my thinking was on the right track.
