### ISSUE TITLE
Vet Centers: Review of Vet Center and Location pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42748]
## Issue Description
We need to review the content on Vet Center main pages and the Vet Center location pages before they are approved for publishing. When the previous contract ended, there was a backlog of pages still needing to be reviewed.

Once we've reviewed them, we either need to send back to the editors with feedback on what should be added/changed, or send to Jessica and Tiffany for her final sign-off before publishing.

We will keep track internally of the work we're doing in our Google doc but also update where things stand in the KB article so that Vet Center editors have awareness

## To review:

- [x] Jacksonville, FL
- [x] Tampa
- [x] Charleston (this one is a second review. They've made the changes we've asked but should be reviewed again before sending back to Jessica)
- [x] Lancaster (Tiffany worked with them on this but Jessica never saw so she'd like us to do a read-through before we send it to her)
- [x] Houston West
- [x] Denver
- [x] Prince George County
- [x] Bucks County
- [x] Gainesville
- [x] Pasco County
- [x] Knoxville
- [x] Marietta
- [x] New Orleans - let Tiffany know when finished reviewing
- [x] Ponce
- [x] Middletown
- [x] Scranton
- [x] Miami
- [x] Bloomfield - let Tiffany know when finished reviewing
- [x] St. Petersburg - let Tiffany know when finished reviewing (see Randi's email) 
- [x] Fort Meyers (district 2) - final copy edit 

## Acceptance Criteria
- [x] All pages were either sent back to editors for revisions or to Jessica for her final review

**Comment by megzehn** [comment]
Note: when reviewing: 

- [ ] pull together list of changes needed for national content (straight quotes, post traumatic, utilize, etc.). And send to Randi.

**Comment by RLHecht** [comment]
@megzehn When you're ready to review a new one, can you prioritize Bucks County? Thanks!

**Comment by RLHecht** [comment]
@megzehn I just added Lancaster to this list. Tiffany worked with them on this but she wants us to do a review and still send to Jessica for her approval.

**Comment by RLHecht** [comment]
@megzehn I just looked at Lancaster after talking to Tiffany about it and sent it to Jessica so you don't need to review that one.

**Comment by RLHecht** [comment]
This work is complete. I've started a new ticket with newer pages to review. Closing.
