### ISSUE TITLE
CT: Remove "Online Only" and "Distance Learning" references from CT

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4275]
## User Story:
As a veteran, I no longer need indicators/filters for "online only" and "distance learning" in the Comparison Tool so that I am no longer confused by the differences and language in the tool.

## Assumptions:
1. This story uses the same feature flag as #4227.
2. Research will be conducted by the developer to identify any other instances of these two identifiers so additional AC can be added if necessary.
3. Research will be conducted by the developer to identify any impacts  that removing this functionality will have so additional AC can be added if necessary.

## Acceptance Criteria:
1. The following filters are no longer available in the non vettec search results:
     - Online Only
     - Distance Learning
2. The following programs are no longer available in the Veteran programs section of the profile:
     - Online Only
     - Distance Learning

## Supporting Artifacts:
1. ![AC1](https://user-images.githubusercontent.com/48260534/70912264-94a27980-1fe1-11ea-963a-4b7ff72f648e.png)
2. ![AC2](https://user-images.githubusercontent.com/48260534/70912261-94a27980-1fe1-11ea-97ff-0608e26e7c6d.png)

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/11334

**Comment by ksantiagomorgan6** [comment]
Pull Request

https://github.com/department-of-veterans-affairs/vets-website/pull/11334

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-12-18 at 10.00.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5f686079-120f-4760-8e28-0ced22999cf6)
##
![Screen Shot 2019-12-18 at 10.01.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4dbf8411-350d-4fa8-b6c7-465c2cc08c8c)

**Comment by sonntag-adam** [comment]
In staging, closing story.
