### ISSUE TITLE
CT: Remove Prod/Feature flag for minor CT enhancements

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4276]
As a developer, I need to remove the feature flag so that the Veteran Programs section updates are available in the production environment.

## Assumptions:
1. This work has been reviewed by EDU and signed off on as of 01/03/2020.
2. The work completed in #4277 is available is to remain behind a production flag.

## Acceptance Criteria:
1. The work completed in #4227 is available in production.
2. The work completed in #4275 is available in production. 

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
Pull request: 

https://github.com/department-of-veterans-affairs/vets-website/pull/11419

**Comment by delli-gatti-michael** [comment]
Both stories above are now live in production. Closing this issue.
