### ISSUE TITLE
Remove content from tables on special benefit allowances rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42773]
## Issue Description

As part of our ongoing effort to remove unneeded tables from VA.gov for accessibility reasons, we need to rework the content on the [special benefit allowances rates page](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/). 

Once we take the content out of the current rates page, we should apply the same changes to the past rates pages in Drupal.  

## Tasks
- [x] Rework content to remove from table
- [x] Copyedit (Megan)

## Acceptance Criteria
- [x] Content is ready for OCTO-DE review

**Comment by katherine-fung** [comment]
This is ready for review: http://preview-prod.vfs.va.gov/preview?nodeId=990

**Comment by RLHecht** [comment]
@megzehn With Laura out this week, we are going to pass this to you before we send to Beth. Katherine modeled this changes after the ones she did on other pages where she removed content from the tables. Could you please do a copyedit and then let Beth know it's ready for her review? Thanks!

**Comment by laurwill** [comment]
Update: Megan raised some good questions here, so the 3 of us chatted and did some group zoom editing to clarify some of the info on this page. I also looked at some related pages for more info. Noting the more substantive changes here for when we pass to Beth:
- Adjusted the "payable August 1" note and nested it under the clothing allowance header, based on the [VA clothing allowance page](https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/) and this [ebenefits rates page]([https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/lo[…]554400000001018/content/554400000162183/2020-COLA-Rates]. The live page applies this August 1 note to all 3 special benefits, but from these 2 sources, I believe it applies only to clothing allowance. **Flagging that we'll need to ask stakeholder to confirm this.**
- Removed the eligibility H2 and placed the link to "find out if you can get xyz" under each benefit header
- Moved the tangential "Learn about other special claims" link from that eligibility H2 into a More Info link

@megzehn , these updates are ready for your copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=990

**Comment by megzehn** [comment]
This is copyedited and ready for you, @bethpottsVADEPO, when you return!

Please see the comments above from @laurwill. We made some substantive edits to the [original post ](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/) that we're hoping you and the stakeholder can review. 

Thank you!

**Comment by RLHecht** [comment]
Closing this ticket as I created a new one for Beth's review, stakeholder feedback and publishing. I moved the comment about our substantive changes to that ticket as well.
