### ISSUE TITLE
CT: Add Language to "Cautionary information" section indicating 24 month window.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4277]
## User Story:
As a veteran, I need the "Cautionary information" section of the profile pages in the Comparison Tool to display language about how recent complaints are so that I can make an accurate decision about where I will choose to use my education benefits.

## Assumptions:
1. This story uses the same feature flag as #4227.

## Acceptance Criteria:
1. In the "Cautionary information" section, the following language is appended to "XX student complaints" (before the source link): "in the last 24 months".

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/colmery-act-2019/design/content/profile-accordion-cautionary-information.md)
2. [Prototype](https://bahdigital.invisionapp.com/share/R3IACBMBWFJ#/screens/296026781)

**Comment by ksantiagomorgan6** [comment]
Pull Request

https://github.com/department-of-veterans-affairs/vets-website/pull/11370

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2019-12-23 at 8.17.33 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a2107807-bb85-44df-a1a3-dcaa8cf7700c)

Local testing complete

**Comment by delli-gatti-michael** [comment]
These changes are now present in staging. Closing this issue
