### ISSUE TITLE
AWS access for Tom Harrison

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#42776]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Tom Harrison

### Your Email

tom.harrison@adhocteam.us

### Your Team, Role, and Company

Authenticated Experience, Back End Engineer, Ad Hoc

### Product Manager (PM) name and email

Sharon Kasimow, sharon.kasimow@gcio.com

### Product Owner (PO) name and email

Samara Strauss, samara.strauss@va.gov

### Desired AWS Access

I need access to production in order to make BGS requests to help troubleshoot latency issues.

### Access Expiration

10/01/2022

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@tpharrison is in the VFS roster.

**Comment by td-usds** [comment]
VOR confirmed eQIP
@tpharrison can you elaborate a bit more about the specific access you'll need? What specific other avenues beyond just 'production access' have been explored in order to troubleshoot these latency issues?

**Comment by tpharrison** [comment]
We've been seeing latency issues related to BGS for the past few months.  You can find more background information in [#bgs-errors-latency-issues](https://dsva.slack.com/archives/C03G60B5DAP) which was created to help some VSA team members and devops folks collaborate on investigating the cause of the latency.

We're fairly certain that the latency is from BGS but we haven't been able to get a lot of traction with them.  If I can call one of the BGS service endpoints directly in production, I might be able to provide more information to the BGS team to help them troubleshoot.

We are only seeing the latency for blocks of time (around 5-6 hours) and then it stops.  I'm hoping to be able to make a request to BGS during one of those blocks to get more info.

**Comment by td-usds** [comment]
chatted with @tpharrison 
he will be out until 6/27 and will not need access _until_ then.
The requested access is approved **from 6/27 until 2 months past that date**.

**Comment by jbritt1** [comment]
> There's always the option in an IAM policy to set access for a desired amount of time, too @jbritt1 . It's not something I see often, but I know it's available. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws-dates.html
> 
> ```
> "Condition": {
>     "DateGreaterThan": {"aws:CurrentTime": "2020-04-01T00:00:00Z"},
>     "DateLessThan": {"aws:CurrentTime": "2020-06-30T23:59:59Z"}
> }
> ```

Yep, @td-usds has mentioned this before as well. Unfortunately, because of how we create users within a `for_each` loop, this would have to be a separate resource I believe for just this policy attachment because if one were to set a time-based condition on the user the way we currently manage IAM group membership, it would apply to all the groups applied. This would in turn make things a little more messy than they already are in the current state so the approach would have to be thought out a little more thoroughly in my honest opinion.

Illustration of what I referring to:
![image](https://user-images.githubusercontent.com/56260532/175957886-2b927ba3-5ed0-478a-a4ef-7b8dc82386b5.png)

I am almost certain if we add a `Condition` block here it would be applied to all group memberships. The only way I could see this working currently would be to add a new `aws_iam_user_policy_attachment` resource definition which would contribute to use maintaining these in more places than we do currently. It could work, but not neatly in our current pattern (again, just my opinion).

**Comment by jbritt1** [comment]
Moving forward with the old pattern on this one just to get Tom squared away, but happy to discuss this new approach more and would love it if we could find a way to make this a thing without increasing managed resource blocks in our Terraform.

**Comment by jbritt1** [comment]
@tpharrison, do you need a prod access extension? The reminder fired today to remove it.

**Comment by tpharrison** [comment]
@jbritt1 - can we extend for another month?  The BGS latency is still ongoing.

**Comment by jbritt1** [comment]
@td-usds, can you approve the 30 day extension for Tom please?

**Comment by raywangoctova** [comment]
approved on behalf of Thomas D who is OOO.

**Comment by rmtolmach** [comment]
@tpharrison Do you need a prod access extension? Your prod access is scheduled to be removed today.

**Comment by tpharrison** [comment]
Hi @rmtolmach - I do not need the extension.  Thanks for checking!

**Comment by jbritt1** [comment]
Production SSM access removed.
