### ISSUE TITLE
[Bug] Staging Combined Debt Portal - Current copay balances - How to dispute section links go to Prod

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#42785]
## What happened?
On Staging **Combined Debt Portal**, **Current copay balances** page, in **How to dispute...** section, links navigated to Prod instead of Staging &mdash; returning to Staging page killed user-session.

## Specs:
- Device: [device-agnostic]
- Browser: ALL EXCEPT Win Firefox, Mac Safari
- Test User _(if applicable)_: **`vets.gov.user+81@gmail.com` (Travis)**

## Steps to Reproduce

1. Go to **[Staging Homepage](https://staging.va.gov/)**, and sign-in via ID.me as **`vets.gov.user+81@gmail.com` (Travis)**.
2. Go to **[Your VA debt and bills](https://staging.va.gov/manage-debt-and-bills/summary)** page.
3. In **Debt and bill overview** section, in **Copay-bill-summary-card**, click **Check your balance...** link.
4. On **Current copay balances** page, scroll down to **How to dispute...** section.
5. Click **Find your nearest...** link, and observe that **Find VA locations** page is in Prod (VA.gov).
6. Click browser **Back** button, and observe that Staging unauthenticated Homepage loads instead of Current copay balances.
7. Repeat procedure to check same section's **Learn more...** link, and observe same behavior.

### Video
Staging **Find your nearest...** link goes from to Prod:
https://user-images.githubusercontent.com/587583/173472063-ba1e2ef3-5b9e-41c5-8ad9-cf3f10bc7f4c.mp4
[same behavior occurs w/ Staging **Learn more...** link &mdash; goes to Prod page.]

## Desired behavior
- [ ] **Find your nearest...** link should go to **Staging Find VA locations** page, not Prod.  Clicking browser **Back** button should return to Staging **Current copay balances** page.
- [ ] **Learn more...** link should go to **Staging Dispute your VA copay charges** page, not Prod.  Clicking browser **Back** button should return to Staging **Current copay balances** page.

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ScottyRJames** [comment]
@denisecoveyduc This would have occurred before the VBS error was present so I think it may have something to do with our links or redirects. Unable to reproduce however until VBS is resolved

**Comment by Dr-Pongo** [comment]
@tlei123 You're right! I've updated and tested the links accordingly and it looks good to go!

**Comment by tlei123** [comment]
Validated in Staging.

**Comment by denisecoveyduc** [comment]
Great work team! 👏🏼
