### ISSUE TITLE
Continue to monitor IA treejack test (#1)

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#42799]
- [x] Monitor IA treejack test progression
- [x] Annotate progression or other concerns in DSVA slack

**Comment by MOStudioCarolyn** [comment]
Veterans studies closed June 21.
Caregivers are still being recruited.

**Comment by MOStudioCarolyn** [comment]
Codes for Perigean https://docs.google.com/document/d/1TztQ2Pk-Mq8hMtYmMJuakf_bc8R7Rodf8dPARRKsaIc/edit?usp=sharing

**Comment by tameracorson** [comment]
Test closed 7/6/2022.
