### ISSUE TITLE
Securely store Lighthouse key in Credstash

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4279]
For our Forms API to work, we need to have a secret API key hidden away in our service, Credstash, so that it isn't exposed over the network and potentially hijacked.

**Comment by ncksllvn** [comment]
Hey @SMLuthi, I think the Vets-API dev environment should be good to go with a Lighthouse API Key. See this PR - https://github.com/department-of-veterans-affairs/devops/pull/6111.

[Behold](https://dev-api.va.gov/v0/forms)

**Comment by Karak888** [comment]
@ncksllvn sounds like this can be closed as validated.  Please let me know if you need to reopen for any reason.  Thanks!
