### ISSUE TITLE
GIBCT Search results not showing

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4280]
The search results are not displaying when searching for a school on staging. Instead, a user is only able to see the "Loading search results" animation. This issue is occurring in Staging.

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Type "College of Charleston" into the search bar
3. Click Search schools

## PRs
department-of-veterans-affairs/devops#6282
department-of-veterans-affairs/vets-api#3811

![Screen Recording 2019-12-16 at 11.08.17 AM.gif](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c1e7463d-acf1-4555-9ec4-db67923b0cd5)

**Comment by zurbergram** [comment]
Prod Config file 
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L66

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3578#issuecomment-557291881

**Comment by zurbergram** [comment]
Another possible instance of the issue https://dsva.slack.com/archives/CBU0KDSB1/p1579708612130200

**Comment by zurbergram** [comment]
Timeout issues were reported on Jan 3rd, 2020 in a private message

**Comment by zurbergram** [comment]
Timeouts occurred in production https://dsva.slack.com/archives/C30LCU8S3/p1579726768127200

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/6282
https://github.com/department-of-veterans-affairs/vets-api/pull/3811

**Comment by desireeturner** [comment]
We anticipate the changes in #5091 will assist with resolving (if not resolve completely) the issue reported in this issue.

**Comment by zurbergram** [comment]
![Screen Shot 2020-02-10 at 8.46.51 AM.png](https://images.zenhubusercontent.com/5bfd74885cb43a45a18acb1b/83b1bcef-d255-447e-9b69-bc720fd85b07)

http://grafana.vfs.va.gov/d/000000050/backend-service-report?orgId=1&var-service=GI&from=1577836800000&to=now&refresh=30s

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/553 has improved performance in institutions endpoint
