### ISSUE TITLE
Add Swagger docs for VA Forms API route 

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4281]
We need to document our addition to Vets-API for the VA Forms, so other engineers know it's available. We do this via Swagger.

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- Nick to drop review requests on the PR

**Comment by MickinSahni** [comment]
2020-02-07 PW Standup
- @ncksllvn - update on this one?

**Comment by MickinSahni** [comment]
2020-02-10 PW Standup
- Awaiting review from VSP, following up since we're past 24 hours

**Comment by MickinSahni** [comment]
Moving to sprint 15

**Comment by MickinSahni** [comment]
2020-02-13 PW Standup
- hey nick, has VSP had a chance to review? @ncksllvn

**Comment by ncksllvn** [comment]
Finally merged! Tomorrow, we should be able to validate this by visiting https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/ and observing a new section for Forms.

**Comment by MickinSahni** [comment]
Validated!!! Closing out
