### ISSUE TITLE
[BE] Don't use statsd.set in HCA::LogEmailDiffJob

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#42836]
Statsd.set does not work. Switch to keeping track of account ids using redis.

**Comment by markfallows** [comment]
Related to logging when someone has a different email in the healthcare application than the email associated to their account.

**Comment by hdjustice** [comment]
This might be good just to see where they may differ, and that may inform us on whether it is a problem or not.
