### ISSUE TITLE
Create Platform Leadership Slack group

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#42847]
### Description

There should be a Slack group that contains the members of Platform Leadership so that this group can be notified of important messages.

### Subject Areas

- [ ] Product
- [ ] Design
- [ ] Engineering
- [ ] OCTO-DE

### Acceptance Criteria

- [x] Slack group created `@platform-crew-leads`
- [x] OCTO and vendor leads are added to this group
- [x] Group is set to automatically join #platform-crew-leadership channel

**Comment by EWashb** [comment]
This is already done. We have the slack group #Platform-Crew-Leadership with contract and gov leads.
