### ISSUE TITLE
Fix Review Environment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42857]
## Problem Statement
We would like to use the Review environment for product/design validation.

## Tasks
- [ ] Ask Shane for a phone appointment clinic on Staging so we can make appointments for test purposes
- [ ] Something is wrong with the Review Environment, need to fix

**Comment by acrollet** [comment]
![Screen Shot 2022-06-30 at 08.31.50.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/49924aa4-65d9-4264-bc25-bd4d0d80be83)

I just verified that an un-related review environment works correctly. (on chrome) Closing as complete, nice work @randomsync !
