### ISSUE TITLE
Accessibility spot check review for redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#42860]
## Issue description
This is a request for an early accessibility review of the redesigned VA.gov home page which has been deployed in staging to be available for usability research sessions and stakeholder discussions. At this time, there is no immediate plan to move this version into production. 

## Background
- The current VA.gov website was launched in 2018 but hadn't been the subject of much user research until Baseline Wayfinding Research was conducted in June 2021. The redesign incorporates findings from that research and will be informed by foundational top task research and usability studies.
- The primary goals of the redesign are
  - to make it easy for Veterans and other VA beneficiaries to complete tasks
  - to improve engagement
  - respond to the expanding benefit and program landscape and stakeholder requests

### Research plan
- The unmoderated top task research is in recruitment as of June 13. We expect this research to have minimal impact on the new home page design but will inform which tasks are displayed in the "Top Task" list. [See the unmoderated research plan.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/research-plan.md)
- The purpose of the usability research is to get user feedback on the redesigned VA.gov home page and assess whether the design changes have improved the usability of the home page. We will observe which areas of the home page they use and how well it supports Veterans, VA beneficiaries, those acting on behalf of Veterans, and service members while completing important benefit-related tasks. The research will be conducted on the version deployed into staging and will include participants who use assistive technology on a daily or near-daily basis. [View the usability research plan.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/redesign-usability/research-plan.md)

### Design
**Summary of changes**
This design delivers a simplified, data driven approach to supporting Veterans and beneficiaries in task completion and includes the following changes
- The static row of Veteran images has been removed. Instead, a randomized, rotating set of Veteran portraits appears at the top of the page (but will not appear in mobile experience). 
- The Sign in/Sign up CTA has elevated visibility and top placement.
- The four top task boxes have been replaced with a data-driven list of links to Veteran-facing pages where actions can be taken.
- A visible search option is available, followed by a data-driven list of four other search tools not available through Search (such as Yellow Ribbon, Education benefits, Find a VA form, Facility Locator). This search feature is expected to mimic site search.
- A single VAntage blog article promo appears in a prominent location. 
- Initial scope will not include the header and footer as these are shared across VA.gov and developing consensus on their use will be significantly more complicated. As a result, some duplicate functionality will exist, such as search, sign-in and mega menu navigation to benefit hubs. 
- The “Other VA resources” section (which contains links to other VA resources such as Choose VA, Resources and Support, VSO websites, VA offices and Programs) is found in the design but not implemented in the testing version as the links are not Veteran-facing.
- [View sketch files](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/PGEaJDr)

## Point of contact
- Team Name: Sitewide home page
- Product Manager: Michelle Middaugh

## Staging URL and credentials, if applicable
- URL: https://staging.va.gov/homepage-test/
- No credentials are needed for this unauthenticated experience.

## Test plan, if applicable
The following functionality is expected and is also documented in [Test Rail](https://dsvavsp.testrail.io/index.php?/suites/view/1260&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4473)

### Sign in/sign up CTA
- Step description: User can click the “Sign in or create account”  button beneath the “Access and manage your VA benefits and health care” heading
  - [ ] Expected Result: Once clicked, the user is presented with the login modal.

### Hero portraits
- Step description: User views VA.gov homepage 
  - [ ] Expected Result: User sees three Veteran portraits
- Step description: Refresh page 
  - [ ] Expected Result: User sees three different Veteran portraits (should change randomly with new page load)
- Step description: Open new window in incognito mode and return to VA.gov 
  - [ ] Expected Result: User sees three different Veteran portraits (should change randomly with new page load)

### Search box with typeahead functionality
- Step description: User visits VA.gov redesigned homepage
  - [ ] Expected Result: Search box is visible
- Step description: Enter characters into the search field
  - [ ] Expected Result: User's input is displayed in the search box. Assuming the input is a valid query with matching results on VA.gov production, suggested search terms should appear in a dropdown below the Search input field while the query is typed
- Step description: Assuming the input was a valid query with matching results on VA.gov production, select a suggested search term
  - [ ] Expected Result: User is directed to the search page where the selected term is displayed in the search field above the list of results
- Step description: Return to VA.gov redesigned homepage, and repeat the same query in the search field. Click on search button
  - [ ] Expected Result: Once clicked, the user is directed to the search page where the input is displayed in the search field above the list of results. Experience in Production and Staging should be parallel. 

### Other search tools
- Step description: Visit redesigned VA.gov homepage
  - [ ] Expected Result: User can see links to search tools displayed below the "Other search tools" heading
- Step description: Click on the “Find a VA facility” link below the “Other search tools” heading
  - [ ] Expected Result: Once clicked, user is directed to the Facility Locator
- Step description: Click on the “Yellow Ribbon” link below the “Other search tools” heading
  - [ ] Expected Result: Once clicked, user is directed to the Find a Yellow Ribbon School search tool
- Step description: Click on the “Education benefits” link below the “Other search tools” heading
  - [ ] Expected Result: Once clicked, user is directed to the GI benefits comparison tool
- Step description: Click on the “Find a VA form” link below the “Other search tools” heading
  - [ ] Expected Result: Once clicked, user is directed to the Find a Form search tool

### Common tasks

- Step description: Visit redesigned VA.gov homepage
  - [ ] Expected Result: User can see links listed below “Common Tasks heading”. Clicking on each link leads to expected url. 

### VAntage Point blog promo
- Step description: Visit redesigned VA.gov homepage
  - [ ] Expected Result: User can see image and blogpost promo with link to story (?)
- Step description: Click link within promo
  - [ ] Expected Result: Once clicked, user is directed to appropriate page

### Benefit hubs
- Step description: Visit redesigned VA.gov homepage
  - [ ] Expected Result: User can see list of benefit hubs with blurbs
- Step description: Find a link to “Service member benefits” and read the summary blurb, “Find out what benefits you may be eligible for during service and which time-sensitive benefits to consider when separating or retiring.” Click link. 
  - [ ] Expected Result: User is directed to https://www.va.gov/service-member-benefits
- Step description: Find a link to “Family member benefits” and read the summary blurb, “Learn about the benefits you may qualify for as a spouse, dependent, or survivor. And find out what you're eligible for as a family member caring for a Veteran with disabilities.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/family-member-benefits
- Step description: Find a link to “Burials and memorials” and read the summary blurb, “Get help planning a burial in a VA national cemetery, order a headstone or other memorial item to honor a Veteran's service, and apply for survivor and dependent benefits.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/burials-memorials
- Step description: Find a link to “Careers and employment” and read the summary blurb, “Apply for vocational rehabilitation services, get support for your Veteran-owned small business, and access other career resources.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/careers-employment
- Step description: Find a link to “Housing assistance” and read the summary blurb, “Find out if you're eligible for a VA-backed home loan. If you have a service-connected disability, see if you qualify for a housing grant to help you live more independently.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/housing-assistance
- Step description: Find a link to “Pension” and read the summary blurb, “Apply for monthly payments for wartime Veterans and survivors with limited or no income who meet certain age and disability requirements.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/pension
- Step description: Find a link to  “Life insurance” and read the summary blurb, “Explore VA life insurance options for Veterans, service members, and families. Manage your policy online, file claims for benefits, and access helpful resources.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/life-insurance
- Step description: Find a link to “Education and training” and read the summary blurb, “Apply for and manage your GI Bill and other education benefits to help pay for college and training programs.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/education
- Step description: Find a link to  “Records” and read the summary blurb, “Apply for a printed Veteran ID card, get your VA benefit letters and medical records, and learn how to apply for a discharge upgrade.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/records
- Step description: Find a link to “Health care” and read the summary blurb, “Apply for VA health care, find out how to access services, and manage your health and benefits online.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/health-care
- Step description: Find a link to “Disability” and read the summary blurb, “File a claim for disability compensation for conditions related to your military service, and manage your benefits over time.” Click link.
  - [ ] Expected Result: User is directed to https://www.va.gov/disability

### Zoom testing
- Step description: View the webpage at 200% browser zoom. 
  - [ ] Expected Result: Page and and interactions are all readable and functional.
- Step description: View the webpage at 300% browser zoom. 
  - [ ] Expected Result: Page and and interactions are all readable and functional.
- Step description: View the webpage at 400% browser zoom. 
  - [ ] Expected Result: Page and and interactions are all readable and functional.

## Keyboard testing
- Step description: Open page. 
  - [ ] Expected Result: Focus goes to the top of the page and indicator of the current page is provided. 
- Step description: Tab to [first] field. 
  - [ ] Expected Result: User can move focus to the [field] using TAB. The field receives focus, "on state" is announced, and the element under focus has a yellow halo around it. 
- Step description: Press SHIFT+TAB
  - [ ] Expected Result: Focus moves to the previous element. The field receives focus, "on state" is announced, and the element under focus has a yellow halo around it. 
- Step description: Continue to navigate the entire page
  - [ ] Expected Result: User can navigate page without keyboard traps. Each element receives focus,  "on state" is announced, and a yellow halo around it. 
- Step description: Navigate to the search field
  - [ ] Expected Result: The Search field is focusable with a keyboard and focus is announced. 
  - [ ] Expected Result: The user is informed that it is an editable field
- Step description: Enter query into search field
  - [ ] Expected Result: The user is informed when there are matches, or if there are no matches 
  - [ ] Expected Result: The user can navigate the matches and is informed when a match is selected. 

## Color testing
- Step description: Visit page with Chrome colorblinding plugin or other similar tool. Check text color pairings for proper color contrast.
  - [ ] Expected result: Text meets contrast ratio requirements to its background.
  - [ ] Expected result: Links are visually distinct from standard text, ie: underlined, especially in paragraph blocks.
  - [ ] Expected result: Links maintain a 3:1 color contrast ratio if not underlined
  - [ ] Expected result: Whenever color is used to provide some level of information or distinguish one object from another, the information is also conveyed through text.  

## AXE and/or Wave testing
- Step description: Visit page with AXE Wave or other suitable accessibility tool 
  - [ ] Expected result: Links are unique and contextual with visual cues. 
  - [ ] Expected result: Page content is contained by landmarks
  - [ ] Expected result: Images have alternative text, including functional images (like submit buttons) and linked images (like in navigation). 
  - [ ] Expected result: Font is placed in easy to read font sizes and styles.
  - [ ] Expected results: The page has at least one heading, beginning wth h1 and does not skip levels. All text that looks like a heading is marked up as a heading.

## Next steps
- [ ] Accessibility specialist will create an epic in Zenhub to capture issues.
- [ ] Team will coordinate another review after work is updated by @-comment in Zenhub in the Github issue.
- [ ] Once all issues are addressed, the ticket is closed with a final comment, “All issues are addressed”, @-comment developer who opened issue, and close ticket/issue.

**Comment by davidakennedy** [comment]
@mmiddaugh @TiffanyPender, @AngelaFowler82 and I have completed testing on the home page. We have a [few minor issues attached to this epic](https://app.zenhub.com/workspaces/vagov-platform-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/43789). Tiffany is writing up one final issue, which will be done shortly, but let us know if you and the team have any questions.

**Comment by mmiddaugh** [comment]
Closing this as issues have been created and linked to [Accessibility spot check review for redesigned VA.gov home page #43789](https://app.zenhub.com/workspaces/vagov-platform-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/43789).
