### ISSUE TITLE
View job details: Include red failure traingle

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#42866]

**Comment by alexandec** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/platform-console-ui/pull/979). All workflow steps now show an icon next to them. Also, cancelled steps now have an icon assigned to them. Here's the new look:

![log-list.png](https://images.zenhubusercontent.com/5fc6638ec869251f539d3881/121f3235-0f19-4228-802b-f708772934a8)
