### ISSUE TITLE
Continue Building Web Components - Q3 2022

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#42873]
## Product Outline
Design System Product Outline  https://vfs.atlassian.net/l/c/Ah0VFf0A

## High Level User Story/ies
- As a VFS team, I want my suggested changes to the design system to be published so that I can use them in my work on VA.gov .
- As the design council, I want approved changes to the design system to be implemented so that VFS teams can use the new designs.

## Hypothesis or Bet
If we build and maintain a library of components that is technically agnostic, more teams can use the Design System components and patterns to build Veteran facing digital applications.

## OKR
_Which Objective / Key Result does this epic push forward?_
Quarterly Operations and Maintenance

### What must be true in order for you to consider this epic complete? 

We have created 3 new web components that were requested by the FLT
- File Upload
- Link
- OMB Info 
- [stretch] Privacy Agreement

**Comment by humancompanion-usds** [comment]
File input, OMB info, and Link have been built. Privacy agreement development is underway. 

We've also started deprecating React components and have deprecated or deleted 19 thus far that we're no longer in use or in limited use with a web-component equivalent. We plan to deprecate and remove 17 more.

We have 9 more rarely used React components left to convert but are deprioritizing that work until teams do a better job adopting the web-components we already have.

**Comment by caw310** [comment]
Team has built the 3 web components identified in the initiative. Privacy agreement is in progress which was a stretch goal. 
File input will go to staging review 9/13 and OMB info just needs to have documentation finalized and to go to staging review.

**Comment by humancompanion-usds** [comment]
Privacy agreement is deployed as is OMB info. Closing.
