### ISSUE TITLE
Inconsistent messaging on 'reason for appointment' page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4287]
Currently (at least in the request flow, didn't validate in DS), there is a continuity bug where the description for 'additional info' breaks when the page is navigated away from.

To reproduce:
- Go down the request flow.
- Pick 'routine or follow up visit'
- Hit continue without entering anything into 'additional info'
- hit 'back' to go to calendar
- continue again back to the 'reason for appointment' page
- See that the 'additional info' description now just says `reasonAdditionalInfo` instead of the paragraph that used to be there (see last screenshot)

AC
- [ ] Title / description for 'additionalInfo' stays consistent regardless of validation errors and navigation changes.

Screenshots:
![Screen Shot 2019-12-16 at 12.27.12 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/3239315c-9787-4ec3-9d36-82322eb7abf7)

![Screen Shot 2019-12-16 at 12.27.08 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/eff3c1e5-ee8a-4e24-b9a2-0ebe75249de0)

![Screen Shot 2019-12-16 at 12.27.00 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/89abfef6-b096-4e52-bb62-a5be01b5d8e9)

![Screen Shot 2019-12-16 at 12.26.39 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/d7d2b49e-1dd3-4ba1-9214-b777a6acd030)

**Comment by peggygannon** [comment]
@markgreenburg Here's the issue where I provided copy for this screen. 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2508
