### ISSUE TITLE
Areas for BE refactor.

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#4292]
There are many more, but I'm starting a list:

https://github.com/department-of-veterans-affairs/vets-api/pull/3631#discussion_r358421617

**Comment by lenaecb** [comment]
@saneshark - is this still relevant?

**Comment by saneshark** [comment]
I think the intention of this ticket was to just keep track of all the inconsistencies and issues we identify on the shared services side. To keep track of all the random little hacks and workarounds we implemented and gotchas we ran into so that we could communicate future improvements. If there is a better way to do that than this ticket which is regrettably, not well maintained, then I'm all for it.

**Comment by saneshark** [comment]
I don't think this ticket makes as much sense with us migrating to the FHIR versions we are developing.
