### ISSUE TITLE
SOCKS access for John Bramley

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#42932]
### Your Name

John Bramley

### Your Email

john.bramley@adhocteam.us

### Your Role and Team

Backend Engineer on VSP Identity

### Product Manager (PM) name and email

Nick Soutouras nick.soutouras@oddball.io

### Product Owner (PO) name and email

Cody Reinold cody.reinold@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuAOJMCbXKJ4binD7YBmDRehJDSQCBStjFFdTZMP49NfR/TUuV3KaQCdFXzka4E6jp4CPjgdkc+krhBMr+DNKyyQybP0GqS+yOcL5kNjciWyq+cMJZGwLPGpNa0tYQD2wCROIXCVxBsBxPanbvInZIvSYhyCHHboseJmA/P7wt1PBloShqR50lBvsG2dCkWE1f0DCgHmIGc3VMwHAINOXj+X8bzrgiauMjSckSGpnd91/WqZ3XeJCHjjk0luaexWTkGOMqYRXmEdx1bEmujMSp6QbQ761Nh8iDybAAKIfJxX65lIJYFNRz26anBp3hnIiKMGtk2SXBaw7g1kk4CJMf/c9a7gpZCNkMG+3YNzMlQqQmNxAXC2nYbINrHUVglPm0xUGhprgwpEt2baBv50Ef7FqDlJmKADuLI0HvZF+q+p/POHO4oza0nHi1MPHXBZsjnwDe4x/VhIy7C4kIzbQTCDUtiwpgTsvoJS9WQPTfEqffB7H1zBb51vh/vzqZGXE= johnbramley@Johns-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
Hi @bramleyjl ! We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with [this platform orientation guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). If you're not newly joining the team, please reach out to your PM or PO for help.
Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by calquisola** [comment]
Hi @jbritt1,

Please advise.  @bramleyjl  is part of identity team,  does he need to be added to the VFS roster?

**Comment by jbritt1** [comment]
> Hi @jbritt1,
> 
> Please advise. @bramleyjl is part of identity team, does he need to be added to the VFS roster?

Identity is platform, so would need to exist in platform roster
