### ISSUE TITLE
Discovery Research Epic - Search results

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#4294]
## High Level User Story
As a Veteran, I need to search for relevant content so I can get to the content I want with as few clicks as possible.

## Goals
_What outcome(s) do we want to see?_ 

## Issues to create within this Epic

```
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

Google Analytics Results from the past week: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:nav-searchresults

**Comment by wesrowe** [comment]
epic never fleshed out
