### ISSUE TITLE
[bug] 526ez | Make 526 VeteranRecordWsClientException retryable in a sidekiq job

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#42947]
# Background
Currently when there is a VeteranRecordWsClientException on the 526 form the submission fails. Generally these exceptions are happening because of a VeteranRecord Service that EVSS relies on to submit claims glitching for short periods of time. In order for the submissions to complete successfully we need to put these exceptions into a sidekiq job so that they will retry automatically.

## Tasks
- [x] Set up sidekiq job for VeteranRecordWsClientException
- [x] Submit PR for review

**Comment by kylesoskin** [comment]
This SHOULD be taken care of in https://github.com/department-of-veterans-affairs/vets-api/pull/10492

**Comment by kylesoskin** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/10492

PR is submitted and un-drafted. Awaiting reviews.

**Comment by kylesoskin** [comment]
This has been merged.
