### ISSUE TITLE
SOCKS access for Brian DeConinck

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#42955]
### Your Name

Brian DeConinck

### Your Email

brian.deconinck@adhocteam.us

### Your Role and Team

Accessibility Specialist on Platform Governance

### Product Manager (PM) name and email

Shira Goodman, shira.goodman@oddball.io

### Product Owner (PO) name and email

Ray Wang, gang.wang@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBS5x4RzafBqQD1CjEL7v3LsleE3ykKjj9YpKlXsBkAH7/cZFiW6g27+qKd7O7Jxh28HjkrcBwD1tuvVV6VLNNs+1Xd6M7tBJE3mb9NF9o/aP3raIDbiRoSCT+espBqaGJjHQzjW89/g+VZfC+Gu52XfUmvr6QRf0fiF2pQHQAhkVjFLqwnHVVGPwCFU2v4r2tZ0oQwqNeO5ju/5x+COAryg7QamLtCujYz36qBimo8cSF+DJyVdR6t40hlbeas204a2GEFKrue7h1hXl9pBqUbbMOujq+Lsr76A3vJKYILxREiRQ9yxMA48X21cCG5KEPstPKAs3ZU0MWoZlMyux9MSRg1XyhGNwdfbZkFZSTO9ZrjUgkEv9XVqrYrWNFOeRQq4+8ENK8cRCnU7oU2YEmi2+2OJgy42+SbefB10BX4PNRok6QuRarKTUWCaaR9qQOHb5+Qft0QVtXtB2QWiJGhdfdmKeZoYduRJeyHfGGtVU77sKuTqtQyoNCHv15/nE= briandeconinck@BrianDeConinckLoaner-HP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by briandeconinck** [comment]
Quick note: I have previously received SOCKS access, but I recently received a new laptop after a hard drive failure. Fresh machine, fresh SSH key, fresh SOCKS request. Let me know if you need anything else from me!

**Comment by calquisola** [comment]
Hi @briandeconinck ,

Please try now. We've updated your ssh key. 

Best,
Carl

**Comment by briandeconinck** [comment]
Looks good, I think I'm all set. Thank you @calquisola!
