### ISSUE TITLE
SOCKS access for amonoxia

### ISSUE THREAD

**Issue by amonoxia** [department-of-veterans-affairs/va.gov-team#42969]
### Your Name

Christia Troyer

### Your Email

christia.troyer@civicactions.com

### Your Role and Team

Backend Developer on VA.gov Team

### Product Manager (PM) name and email

Wes Rowe  wesley.rowe@agile6.com

### Product Owner (PO) name and email

Jill Adams jill.adams@agile6.com

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDucOHY343xjm1aWkGn/nrRCIcTykDsXn6tXD/M7M0AyvDRaZXibIPqQiSbjs0z3H+q+mjUkYn9oHy9shvC50TyRugmtS1Sp3foHLZIs3GWA7EBWbRiZMt6D+FqgqZEXS4Njz2L0QvoeLAaN/wAm2c3GL5baYJ3Hcbf41HcO0Hd+ZlW0biRAHFuUcOMkKtftEetAv8n73UqdOasjCDLKJMWwwD8JpfVAtEvgYRKkIn7D8w14tXS3fl7Z8DELOw1OMHBT6UsxJMolh0dSlyGRqGbG+cMIthTNUvNvydhyQA2j9CMj4DXfWqRTlqxYMgvLajIoY8kTBYc+BOO52xPAy/lOwW6B31sPnLV7IAnvSODJEGH7gI5pF2/VSCfBetTyrKeANA0KX4vHh+yPf6A0H+OcFO6tZd4vpZWfz3+77FjY9alMtFrFMjt0YAXGUGExhX0twe9Dgj7hncFUfGRye1ycXlmlTAetg7kVxgiRa3aNoihUAPpIuzOlq2svntqris= christiahall@Christias-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
