### ISSUE TITLE
Troubleshoot issues with Facility Locator in heroku env

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#4296]
Facility Locator does not operate correctly in a Heroku instance.  See screen shot -- ![Screen Shot 2019-12-16 at 11.22.03 AM.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/af25db84-df02-4336-b804-428f37486832)

**Comment by peterhill-oddball** [comment]
Per information that I've gathered, Heroku instances do not appear to be capable of serving up a functional vets-api.

I will explore alternatives with the Facility Locator team and attempt to determine whether testing in Staging will satisfy the team's requirements.

**Comment by mandifrances** [comment]
Not needed
