### ISSUE TITLE
Create deploy to staging deploy automation

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#42980]
## User Story

_As an engineering user I would like the capability to deploy and automate (leverage container orchestration to host and deploy software applications) Sidekiq UI to staging to simplify the process of deploying the Sidekiq service. 

## Expected Behavior

Should be able to deploy and automate Sidekiq UI within the staging environment using  container orchestration.

## Acceptance Criteria

- [x] _Add bulleted list of all the task that must be finished for the feature to be consider finished & ready to merge_

**Comment by considerable** [comment]
To add a new app in ArgoCD, for instance sidekiq-ui-staging, these steps required:
- create resources (/dsva-vagov/vets-api-sidekiq-ui/staging/*) in AWS parameter store
- create ArgoCD manifests in a separate directory (vsp-infra-application-manifests/apps/platform-pst-iet/vets-api-sidekiq-ui/staging/*)
- create entry in main.jsonnet (vsp-infra-application-manifests/apps/vsp-operations/argocd-apps/staging/main.jsonnet) alike
```
  sidekiqUI: app.new('sidekiq-ui', 'platform-pst-iet', 'platform-pst-iet') +
             app.spec.source.withPath('apps/platform-pst-iet/vets-api-sidekiq-ui/staging') +
             app.spec.syncPolicy.automatedDefault(),
```
_Note:_ The PR involving main.jsonnet requires approval from both the app team (platform-pst-iet) and the infra team (vsp-operations)

_Example:_ https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/652

**Comment by ewilson-adhoc** [comment]
Request to onboard in keycloak https://github.com/department-of-veterans-affairs/access-management-integration/issues/106
