### ISSUE TITLE
Configure sidekiq UI staging to work with keycloak

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#42981]
## User Story

_As a user I would like to have protect access to Sidekiq UI to ensure that the Sidekiq service is secure.

## Expected Behavior

_In order to use the SidekiqUI service a user will be requested to login in to gain access to the service.

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that must be finished for the feature to be consider finished & ready to merge_

**Comment by FHiatt** [comment]
Blocker - we don't have the necessary access -->Need AMT to help via their access capabilities Emily working with AMT.
