### ISSUE TITLE
Linked/embedded diagram not working 

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#42999]
## Description
**The questions below help our team to determine the project scope for incoming documentation support requests.**

The embedded diagrams in this page are visible in confluence but show up as missing links on the platform site. 
Confluence:
[https://vfs.atlassian.net/wiki/spaces/pilot/pages/1844346924/Build+and+deploy+process+flows](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1844346924/Build+and+deploy+process+flows
)
[https://depo-platform-documentation.scrollhelp.site/developer-docs/build-and-deploy-process-flows](https://depo-platform-documentation.scrollhelp.site/developer-docs/build-and-deploy-process-flows)

**1. What do you need help with? Check one:**
- [ ] Creating new documentation
- [x] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

**2. Who are the primary users of your documentation? Check all that apply:**
- [x] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other: ____________________

**3. Estimate the number of pages to be created, updated, or reviewed? **2

**4. Do the documents contain graphics such as screenshots, code snippets, diagrams, or videos?**
- [x] Yes, and describe:diagram of workflows..see confluence document
- [ ] No

**5. Who is the point of contact for this documentation?** Ray Messina

**6. Are there other documents, tickets, or artifacts that will be impacted by this update?**
- [ ] Yes, and describe ____________________
- [x] No

**7. Are there plans to update other documents/pages that have similar content?**
- [ ] Yes
- [x] No

**Comment by lianilychee** [comment]
hey @rmessina1010 !  Thanks for submitting this.  We're already aware and have alerted Carol and Lainey, and outlined the action to take (https://github.com/department-of-veterans-affairs/va.gov-team/issues/42170#issuecomment-1152483950).  It looks like Release Tools Team actually wrote this document -- your team is responsible for updating, so you and Lainey can prioritize in your backlog as necessary.

cc: @laineymajor

**Comment by vbellissimo** [comment]
Followed up with Lainey Trahan and Ray Messina via Slack on 6/30/22.
