### ISSUE TITLE
[SCREENREADER]: Disability Calculator - can we add an aria-label to the Delete buttons for context

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#430]
## Issue
The Delete buttons all have the same text, so they could be improved for screen reader users with an aria-label to help answer what row users will delete. Screenshot and code snippet attached below.

## Related Issues
* #429 

## Acceptance Criteria
As a screenreader user, I would like to hear clear, concise labels that tell me which row I am going to delete.

## Environment
* MacOS && Win10
* Safari, Chrome, Firefox, IE11
* VoiceOver, NVDA, JAWS

## Possible Fixes (optional)
```html
<button
  aria-label="Delete disability row one"
  class="va-button-link delete-btn vads-u-margin--1p5"
  type="button"
  disabled
>
  <i class="fas fa-trash-alt vads-u-padding-right--0p5"></i>
  Delete
</button>
```

## WCAG or Vendor Guidance (optional)
* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs
![Screen Shot 2019-06-27 at 4 35 42 PM](https://user-images.githubusercontent.com/934879/60302885-a2acf280-98fa-11e9-891a-8839b70af34e.png)

**Comment by Karak888** [comment]
@narin is this something you can help with?  Please let me know. Thanks!

**Comment by 1Copenut** [comment]
Re-tested on Staging and functioning correctly. Moving to close.
