### ISSUE TITLE
BE - Auth Profile - Military Info Migration - Add sorting to service history records

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#43003]
## Background
When pulling service history records from VA Profile, they need to be sorted by begin date.

## Tasks
- [ ] Add sorting to service history records

## Acceptance Criteria
- [ ] Service history episodes display sorted by begin date (ascending).

**Comment by SKasimow** [comment]
@tpharrison -is this a dupe to 43004?

**Comment by tpharrison** [comment]
@SKasimow its a dupe.

**Comment by SKasimow** [comment]
closing as it is a dupe ^
