### ISSUE TITLE
BE - Auth Profile - Military Info Migration - Add sorting to service history records

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#43004]
## Background
When pulling service history records from VA Profile, they need to be sorted by begin date.

## Tasks
- [x] Add sorting to service history records

## Acceptance Criteria
- [x] Service history episodes display sorted by begin date (ascending).

**Comment by tpharrison** [comment]
@Samara-Strauss @SKasimow I realized that the eMIS code had been sorting service history records by begin date, so this adds the sorting to the VA Profile code.

I have already opened a PR.

**Comment by Samara-Strauss** [comment]
Great, thank you so much! Let me know when it's on staging, and I'll validate with user 11.

**Comment by Samara-Strauss** [comment]
Great! I also validated. Looks good. Thank you!
