### ISSUE TITLE
[DataDog] Codify resources into Terraform code

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#43000]
## Description
As we transfer Datadog resources (dashboards, monitors, etc) that are not in code from datadoghq.com to vagov.ddog-gov.com, we should try to capture these resources in Terraform code.

Migration is happening as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/42691. Resources owned by the Infrastructure team should be imported into a datadog state file, and code should be iterated until the plan shows no changes.

---
## Tasks
- [x] compile list of Datadog resources not in code but owned by the Infrastructure team

## Acceptance Criteria 
- [x] All Infrastructure DataDog resources are in Terraform code

**Comment by jsgarmon** [comment]
This is nifty! We should be able to use the `datadog_dashboard_json` to get those into the new dd account. We just need to figure out which dashboards need to be moved.

**Comment by jhouse-solvd** [comment]
John recommends breaking this out into sub-tasks, ie monitors, dashboards, and synthetic tests. Let's see how we can break this down and assign sub-tasks to other team members.

**Comment by oseasmoran73** [comment]
> Beginning to compile of list of dashboards that Infra will migrate over. Once we have that going. We can then focus on migrating them over as code (in the near future)

Posting for [x-cross](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42691#issuecomment-1163649778) reference

**Comment by oseasmoran73** [comment]
> Beginning to compile of list of dashboards that Infra will migrate over. Once we have that going. We can then focus on migrating them over as code (in the near future)

Posting for [x-cross](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42691#issuecomment-1163649778) reference

**Comment by oseasmoran73** [comment]
> import these resources into the appropriate statefile and ensure the tf plan shows no changes needed

Removed this section as part of task. We never migrated them over, but rather converted to code directly and applied terraform. See PR for more details

Closing this ticket out. Feel free to reopen if y'all think AC was not met

**Comment by jsgarmon** [comment]
has anyone looked at additional monitors or synthetic tests (that infra owns) not yet in code?
