### ISSUE TITLE
SOCKS access for [Gary Fong]

### ISSUE THREAD

**Issue by garyjfong** [department-of-veterans-affairs/va.gov-team#43012]
### Your Name

Gary Fong

### Your Email

gary.fong@va.gov

### Your Role and Team

Developer - Long COVID Technical Team

### Product Manager (PM) name and email

Marian Adly - marian.adly@va.gov

### Product Owner (PO) name and email

Marian Adly - marian.adly@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaDpnCJMKbCLyEMkjT3cz0ceS436hCGICUc4xtp74lj6HZh9dAcIBjl0GXWmkKxA+/XXp+A+Ja7I9u0MlIzUPMLpzDBfWvIx4Hum14u81czHSKO7xmF1VCt0kmtn449XMUVU6+apzqon9JsS67FyvVT/iV2mKVTfnKnkYNECiQl6KAXXT8F/JCBx2rcpmU8NSTXooxYM2SkDNd41/sZClFmF9vQ+62MqqlkKBC1m/vdEKF45MYSHvh/FsjrNUGeSUUWBjywyDgcAax5dCIi2fompQ1MvPO22tvh6Nn9lH++wCAeZ4rraIIdMnq2+d9nR9PpQGBcQWm07O0XUXBXNPZHVRVOZULmmaKrpbvSVcXQ6tOzmsym6iEfoDqQ4H184im6CZboF3FlPE46bAKT+gNUQKsT7vlL3+UglLv51JPymaI9PQ0EX74eGk9HHfFmF7RrQq+KWceiwdue2Ubt32b8GarpiF21+iu56WcdbsA0GbTKjq6lfAw4O7b82DCFA0= garyfong@Garys-MBP-2.home

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@garyjfong is part of the VFS roster

**Comment by calquisola** [comment]
Hi @garyjfong,

You were just offboarded this week.  

Were you moved to a different project? 

Please advise on your current situation. Thanks. 

Best,
Carl

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
