### ISSUE TITLE
FE |  Profile | Feature Flag Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43019]
## Background

Document how we use feature flags to internally test and phase product released to production.

## Tasks
- [ ] Document use of FF for Profile features

## Acceptance Criteria
- [ ] Post to git-hub

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@mdewey - here is a shell for feature flag documentation. Again, please edit/add as needed and lmk which sprint to include this in or whether to just leave open for now. thanks, Sharon

**Comment by mdewey** [comment]
First draft: https://github.com/department-of-veterans-affairs/va.gov-team/pull/43820/files

@SKasimow and @Samara-Strauss  Let me know what you think!
