### ISSUE TITLE
Define Process for VSP Special Vets-API Monitors for External Services 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#43013]
Description 

We need to decide how to handle this open  [support requests to create a VSP external service monitor](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9399).   

Tasks

- [X] Get Clarification from Platform Ops/Vets-Api Teams the correct process to handle these type of requests

Acceptance Criteria

- [X] Policy for new Datadog Users. : Answers:  [VFS not allowed at this time.](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance)
- [X] Create monitor if needed : Answer: [Create this monitor](https://vagov.ddog-gov.com/synthetics/details/5jw-dyv-4ey)

**Comment by zachclarity** [comment]
Created basic [Synthetic Monitor on Gov DataDog ](https://vagov.ddog-gov.com/synthetics/details/5jw-dyv-4ey)

**Comment by oseasmoran73** [comment]
Is there a reason why the user can't create their own synthetic monitor? CMS has done their own synthetic monitoring in the past.

While the new Gov DataDog may not be quite ready for all users, once it goes live and is ready for them to create monitor/synthetic_tests, it shouldn't be a blocker for them.

**Comment by zachclarity** [comment]
@oseasmoran73  thanks.  I had suggested this and asked for clarification.  I will have him create his.

**Comment by zachclarity** [comment]
Closing I gave @jtmst info on how to requests access.

**Comment by zachclarity** [comment]
Created Monitor

**Comment by zachclarity** [comment]
Because of the policy - we [created a monitor for VFS team.](https://vagov.ddog-gov.com/synthetics/details/5jw-dyv-4ey)
