### ISSUE TITLE
Console Services: IET - [spike] Meet with the QA standards group and get standards

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43027]
## Problem
A research spike is required to better understand what QA standards are required by the standards group

## Acceptance
- [ ] A meeting will be set up with the Standards group to better understand what QA standards are required
- [ ] A list of required QA standards will be generated as a result of the meeting with the standards group

**Comment by npeterson54** [comment]
Wont do, team no longer here
