### ISSUE TITLE
Content work for PACT act

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43021]
## Issue Description
This ticket is for the content work Beth is doing to pages connected with the PACT Act.

These pages include:

- [Gulf War Illnesses linked to Southwest Asia service](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia/)
http://preview-prod.vfs.va.gov/preview?nodeId=885
What's new: A lot of the content in the blue box is new/rewritten. Then everything under this header: **Presumed conditions related to your service**

- [Gulf War Illnesses linked to Afghanistan service](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-afghanistan/)
http://preview-prod.vfs.va.gov/preview?nodeId=884
What's new: A lot of the content in the blue box is new/rewritten. Then everything under this header: **Presumed conditions related to your service**

- [Disabilities that appear within 1 year after discharge](https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/)
http://preview-prod.vfs.va.gov/preview?nodeId=890
What's new: This header is new, but the first 4 bullets under it aren't: **Are any illnesses covered that appear more than 1 year after discharge?**

All the content in the next section within this subhead is new: **Presumptive conditions related to particulate matter exposure**

## Tasks
- [x] Copyedit new content (Megan)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by RLHecht** [comment]
@bethpottsVADEPO I created this ticket though I'm not sure the pages I listed above are correct. But we can use this to track the work you're doing for when you need us to copyedit or anything else.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thank you so much, this is perfect. I'll let you know when it's ready for copyediting. Do you think that would be possible tomorrow morning?

**Comment by RLHecht** [comment]
Yep, that works. @megzehn FYSA this is the ticket I just slacked you about!

**Comment by bethpottsVADEPO** [comment]
@RLHecht @megzehn These 3 pages are ready for copyediting. I added preview links above, and notes about what content is new. You don't need to copyedit the whole of each page, just the new sections. But it might help to read some of the surrounding text for context and considering whether what I added works well / integrates successfully with the page as a whole.

Thanks!

**Comment by megzehn** [comment]
Discussed with Beth on Slack to add consistency to language around presumed diseases/presumptive illnesses.
