### ISSUE TITLE
[spike] Define access policy for sidekiq UI production access

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43032]

**Comment by ewilson-adhoc** [comment]
The first step for this ticket is to reach out to console services team and ask what the current process is for getting access to (development?) https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ericboehs&labels=Console-Services%2C+sidekiq-access-request&template=sidekiq-admin-ui-access-request.md&title=Sidekiq+Admin+UI+Access+Request

Questions to Answers: 
- Who is responsible for granting access? 
- What criteria are required for a user to be given access? 
- Is the process for getting access to staging/prod/etc different?

**Comment by considerable** [comment]
made a formal Sidekiq-UI access request [#43850](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/43850)

**Comment by considerable** [comment]
Eric of console services team says, 
> there is no limit to who can have access. It was only put in place because there is not audit log so we wanted to limit who had access. If there’s an audit log, it shouldn’t be a problem to grant access to devs.
> Dev/staging/prod all use the same list but again, as long as we know who’s access it and what actions they perform, we don’t care about limiting it to competent developers.

Finnier details of Sidekiq-UI for different environments are on this [confluence page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/937558053/Sidekiq+jobs#Deployed-environments).

**Comment by considerable** [comment]
Executive summary: as per the owner of Sidekiq-UI service, any Platform developer may access Sidekiq-UI in any environment for as long as the access audit trail is maintained. Currently, in the absence of the audit trail, the access is granted to developers upon individual request.
