### ISSUE TITLE
CI failures tied to runners: improvements

### ISSUE THREAD

**Issue by mydesignrocks** [department-of-veterans-affairs/va.gov-team#43052]
## Issue Description
CI workflows are getting inconsistent behavior from the aws self-hosted runners. Noticed the issues are either tied to the AMIs or flake tests within the actual workflows. 

## Front end tasks
- Understand the existing process of AMI usage in CI workflows
- Revisit the process to grab the latest AMI
- Change or modify to ensure AMI is available during scaling (ASG) activity within AWS
- work with the qa teams to address the inconsistency and flakiness with unit tests
- 
## Acceptance Criteria
- [x] Make sure build, release, archive and deploy stages are not the cause of workflow instability (RTT)
- [x] Make sure flakiness is addressed (RTT)
- [x] Make sure AMI cleanup process is revisited through the existing lambda - 30 days now (Infra)
- [x] Look for the right AMI and test the AMI before pushing it to the whole CI workflows (RTT)
- [x] Make sure the AMI build itself is cleaner and is a lighter weight model (Infra)
- [x] Test the new lightweight AMIs (RTT and Infra)
- [x] Apply new AMIs to CI workflows (RTT and Infra)
- [x] not use on-demand runners (RTT) 
- [X] make sure all CI jobs are running off of self-hosted runners and asg where possible (RTT)

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/11431#issuecomment-1158226586

**Comment by mydesignrocks** [comment]
CI is now using the self-hosted runners with asg (minus deploy job) and looking good so far. Going into support mode as I close this out.
