### ISSUE TITLE
Generate a list of tools currently used by the platform in support of microservices

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43058]
## Story
As an engineer making recommendations for future architectural states, I would like to gather information about what is currently in place, so that I can understand the current state of available tools. 

## Acceptance Criteria 
- [x] A list of tools that is currently used to support a microservices architecture (logging, CICD, ect)
- [x] Each entry on this list should include information about the current status of the tool and who is responsible for maintaining it. 
- [x] This list is available on [this page](https://vfs.atlassian.net/wiki/spaces/IET/pages/2241003742/Supporting+Tools)

**Comment by MrMorie** [comment]
List updated with prod usage.
