### ISSUE TITLE
[Spike] VVC appointment instructions in V2 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#43051]
## Request
We are requesting the logic for V0 and V2 when an appointment is created from VCM. Once a staff creates a VCM appointment for a Veteran, the appointment will be displayed in VAOS. We recently discovered the VCM team added additional options for the instructions when creating the appointment in the system. 

### Goal
To understand how the application reads the instructions provided from the backend and how does the UI display the message to the Veteran. 

### Requirements to Consider

VCM system: 
_The staff selects the instructions for the appointment_
<img width="735" alt="Screen Shot 2022-06-16 at 12 33 03 PM" src="https://user-images.githubusercontent.com/90797205/174206985-b99df976-b795-4116-b068-59e7393f5410.png">

There were three additional instructions that were added to the VCM workflow recently:
- Message Sent in MyHealtheVet 
- Resources Mailed to Patient 
- Sign up for My HealtheVet Secure Messing 

In V0, we are assuming the application is showing a default message (Video Visit Preparation Instructions) if the value is blank/unknown. 

When testing in VAOS v0, the appointment details page is displaying the following: 
- In VCM select `Med Review`, the application display med review instructions
- In VCM select `Message Sent in MyHealtheVet`, the application displays video visit preparation instructions
- In VCM select `Resources Mailed to Patient`, the application displays video visit preparation instructions
- In VCM select `Sign up for My HealtheVet Secure Messing`, the application displays video visit preparation instructions
- In VCM select `Video Visit Preparation`,  the application displays [video visit preparation instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#vvc-home-booked-future)

---

## Tasks
- Answer the following questions:
  - 1) What are the med review instructions that VAOS is displaying? 
  - 2) What is the logic implemented in V0 if the instructions are not mapped to a UI message? 
  - 3) What is the logic implemented in V2 for the VVC appointments? 

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by simiadebowale** [comment]
@ldelacosta I started looking into this ticket, can we get someone from SQA to create a vcm appointment to test with please

**Comment by ldelacosta** [comment]
@beth-wodzinski / @aarathi-poldass - We are trying to review ticket. Would you be able to create a VVC appointment for us?  Please let us know when you have a chance. Thanks!

**Comment by aarathi-poldass** [comment]
VCM is the application that we use to scheduled VVC appointment. VCM is currently down, so we can't schedule new appointments. I can help test once the application is back up.

**Comment by beth-wodzinski** [comment]
I was able to get into VCM just now, and made a video appointment for Cecil Morgan on 8/2/22 at 11:00 mountain time. Let me know if this works for you or if you need anything else.

**Comment by simiadebowale** [comment]
We currently hardcode instructions for telehealth appointments. 
We get the instructions returned from the appointments endpoint, in the 'patientInstruction' field.
![Screen Shot 2022-08-01 at 10.54.33 AM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/24c10d2e-5d79-44b3-8ada-42e5a549ac8b)
Important Note: the instructions we currently display is hardcoded and different from the instructions we're getting from the api. which/what is the source of truth? 
Here's a sample of the response we get for the 'Medication Review' instruction:
patientInstruction: "Medication Review\n\n- As part of your video visit, your provider wants to review all the medications, vitamins, herbs, and supplements you are taking. Your provider will want to know about these items even if you get them from a local store, another provider, or another VA clinic.\n - Please have available during the visit information about all the medications, vitamins, herbs and supplements you are taking to your video visit.\n - Informing your provider about all these will help you get the best and safest care possible.\n\nRemember, it is your medications, your life, so play it safe by reviewing all your medications with your health care team."
Here's a sample of the response we get for the 'Message Sent in MyHealtheVet' instruction:
patientInstruction: "Message Sent in MyHealtheVet\n\nSign-in to My HealtheVet Secure Messaging  https://www.myhealth.va.gov/ to view resources sent from your VA health care team to support your video visit.\n\nTo use the Secure Messaging feature, you must have registered on MyHealtheVet as a VA Patient and have a Premium account".
It is possible to dynamically pass these instructions into our UI component like shown in the screen shot above however, we would need to discuss a set format for these instructions as they are currently formatted differently.
The idea is for the FE to split the string into an array using the '-' as the separator. 

cc: @ldelacosta

**Comment by ldelacosta** [comment]
@simiadebowale - Please add your recommendation on the data we want to sent from VCM.

**Comment by simiadebowale** [comment]
Recommendations: Either of these two solutions works for us. Our preference however, would be the second.
- 1 - can we get a standard format for separating the text retuned in the patientInstructions field. i.e, Medication review is separated by '\n\n -' while Message Sent in MyHealtheVet is separated by '\n\n' we can make a singe '-' the separator. 
- 2 - we can turn the patientInstructions field to an object that returns values of the patientInstructionsTitle & patientInstructionsText. i.e, patientInstructions: {patientInstructionsTitle: 'Medication Review', patientInstructionsText: 'Instructions'}

**Comment by ldelacosta** [comment]
This has been documented in [GH file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/appointments-reference/data-reference/data-definitions.md#instructions-prepare-for-telehealth-visit). Closing out the ticket. cc: @JRRoof
