### ISSUE TITLE
Adding [Dave Pickett] to DSVA Slack

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-team#43050]
@cmaeng - I think this request needs to officially come from you, but I just created the shell as I'm going through the onboarding checklist 

# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member

- What channel(s) do they need to be added to?
- vfs-all-teams
- 

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Content Designer for the Facilities team.

We aim to complete slack requests within 24hrs.

- Please add Dave.pickett@civicactions.com as a full member.

**Comment by cmaeng** [comment]
@davidmpickett looks like this ticket is all set to process. i added a couple of missing details about your role and team.
