### ISSUE TITLE
Storybook Side Navigation: Sub Folder Maturity Icons

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#43065]
## Related Tickets
#41381 
https://github.com/department-of-veterans-affairs/component-library/pull/464

## Description 
Sub Folders in the Storybook hierarchy do not have Maturity Scale color icons:
https://user-images.githubusercontent.com/12739849/174149849-64af68c4-6ebe-49d2-a72b-885cc4dde7e1.png
Logic would need to be remapped from taking top level name matching to add icon via css to also look at nested folders. This might require some discovery on the best approach since it would be a full rework of current logic.

## Acceptance Criteria
- [ ] Top level and sub folders in nested SB hierarchy should have maturity scale color icons that are added via css on the left side of the text

@k80bowman @andresriveratoro

**Comment by bkjohnson** [comment]
Closing, the hierarchy was removed & work completed in https://github.com/department-of-veterans-affairs/component-library/pull/482
