### ISSUE TITLE
FE | CICD | Isolated App builds, removing cross app dependencies for Profile and adjacent apps PT 1

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#43066]
## Issue Description
To speed up the CI pipeline and make our app less reliant on others, we should remove cross app imports. They are listed here: 
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report

Slack thread here: https://dsva.slack.com/archives/C909ZG2BB/p1655235269599459

More information on this process can also be found here: https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds

INITIAL DISCOVERY DOC:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/engineering/discovery/isolated-app-builds.md

In the discover doc there lists out the specific files that need to be updated. This ticket is to update the profile specific files along with the other minor applications that are also part of the personalization app folders. This is part 1 of 3ish parts.

- personalization/profile/reducers/index.js
- personalization/view-dependents/layouts/ViewDependentsLists.jsx
- personalization/view-dependents/view-dependents-entry.jsx
- src/applications/vre/28-1900/tests/e2e/chapter31-loa1.cypress.spec.js (imports from profile)

## Front end tasks
- Remove cross app imports from Profile, view-dependents, and vre applications
  - Copy/Move imported code into our app where applicable
  - Move code into platform if it is heavily used and is more utility based in nature
- Ensure tests build

## Acceptance Criteria
- [x] Profile cross app imports are resolved
- [x] All test pass

**Comment by mtcA6** [comment]
@adamwhitlock1 
two questions:
- Could you throw an estimate on here? 
- Should I convert this into an epic and we can discuss what the component parts of this would be? 

To me, this reads as one of those things that could sit on the sidelines forever and when we finally pick it up we'd be bummed that we waited so long.

**Comment by mtcA6** [comment]
OooOoOoo reading [FE | Profile | Contact Information | Discovery | Isolate required components to platform level folders#59386](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59386) is 59386 issue a child issue of this issue 43066? Do we want to break down this ticket by each profile page so we work through each page individually?

**Comment by adamwhitlock1** [comment]
@mtcA6 Okay I think this is ready to validate and go over. 

I created this doc here outlining the discover work:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/engineering/discovery/isolated-app-builds.md

Based on the discovery I have updated / created 3 tickets required for the work:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/43066
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65116
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65114

They should be worked sequentially as they are basically chunked out into Profile, My VA, and then Platform based code locations, with the Pt3 ticket being the most time consuming and complex. Pt3 may need to be broken out into 2 tickets, but probably wont know until I really get into working it.

**Comment by mtcA6** [comment]
Hey @adamwhitlock1 mind if we get on a call to discuss to make sure I fully understand front to back?

**Comment by adamwhitlock1** [comment]
I'm still working on this, so going to roll it over to the next sprint. Probably 2 points remaining on the ticket.

Mostly due to some additional apps being in the personalization 'main' folder, and we had some unplanned work around e2e test failures that needed to be addresssed.

**Comment by mtcA6** [comment]
@adamwhitlock1 cheer up! You're making progress! You're doing goooooddddd!

**Comment by adamwhitlock1** [comment]
@mtcA6 I think having this merged into main is validation enough since its code cleanup stuff and nothing to be really checked on the FE.

@allisonlu can you validate that I did the things :)

**Comment by allisonlu** [comment]
@adamwhitlock1 @mtcA6 

Looks good! Good to close
