### ISSUE TITLE
Analytics Feature Request VA Notify Exclude Internal Data

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#43072]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [X] Ticket Description
- [X] Request/Report Description
- [X] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - VA Notify - Melanie Jones, Product Manager & Bev Nelson, VA PO

- Is this a feature request or a bug?

  - [X] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

[VA Notify Dashboard](https://va-gov.domo.com/page/2040841289)

Are you able to exclude service_name ("VA Notify", "vanotify-team") from the notification analytics? We are seeing VA Notify system emails (received email complaint) show up in the analytics dashboard that business lines use to track their email analytics. We do not need to see our system emails on this dashboard.

![image](https://user-images.githubusercontent.com/99204969/174326311-4d9275ea-204c-4b67-a797-674f29c7e884.png)

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

N/A

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [x] Document issue & fixes
- [x] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by mjones-oddball** [comment]
@bevnobev @megansiddle Here is the DOMO enhancement request to exclude VA Notify system emails.

**Comment by michelle-dooley** [comment]
@mjones-oddball - thank you for your request.  We will review as part of sprint planning tomorrow.

**Comment by michelle-dooley** [comment]
@mjones-oddball - we have added this to our sprint starting tomorrow, will get back to you if we have any questions.

**Comment by mjones-oddball** [comment]
@michelle-dooley Thank you!
