### ISSUE TITLE
Adding [Narasimhan Kidambi] to DSVA Slack

### ISSUE THREAD

**Issue by agmurphy** [department-of-veterans-affairs/va.gov-team#43080]
Please add [narasimhan.kidambi@microsoft.com] as a multi-channel guest to this private channel: [va-virtual-agent-msft]

They already have Slack access to a few channels and this is a new channel we'd like to add them to for them to work with the Virtual Agent chatbot team's developers on environment setups and spikes.

**Comment by ksk385** [comment]
Is there anything that is needed from us on this request?

**Comment by LEHigley** [comment]
reactivated this account--are they able to get in?

**Comment by LEHigley** [comment]
@agmurphy checking in here--are they good?
