### ISSUE TITLE
GIDS: Uploading SCO file causes error in staging

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4308]
@sonntag-adam commented on [Tue Dec 17 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20082)

Steps to duplicate:

1. Upload attached txt file (locally or to staging via cag) to SCO specifying pipe delimited
2. Error occurs

![SCO Upload Error.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1ccd6dee-9273-4c6b-8991-e0412b41b2bb)

**Comment by hughes-dustin** [comment]
This is because there are cases where we are using quotation marks in the first name field (ie SGT ROBERT "BOB").

@dneel-bah  Do we want to be able to use quotation marks and if so, which fields do we want to have them in?

**Comment by dneel-bah** [comment]
@hughes-dustin I think that we should be able to upload data as it is received unless it is not technically possible.  What does @shawkey-daniel think?

**Comment by shawkey-daniel** [comment]
Anything that is a valid string character between the delimiters in a string field should be valid and should be ingested.

**Comment by hughes-dustin** [comment]
Okay, I'll implement it to include special characters minus delimiters.

**Comment by hughes-dustin** [comment]
branch: bah-4308
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/539

**Comment by sonntag-adam** [comment]
In staging, testing passes QA
