### ISSUE TITLE
Midpoint Review - Research Feedback - Profile Team - Bad Address Indicator

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#43082]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Take this as preliminary feedback, as this research proposal will still need to go through the [Research Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) before kicking off recruitment
- Overall the plan and guide look to be coming together well, but let me know if you have any questions as you prepare to submit for Research Review.
- As mentioned in meeting, if timing lines up, Shane and I may ask your team to add a couple of lines to your convo guide and relay back answers to 3 questions we want to ask participants regarding the inclusion of observers on VA research.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**
1. Should include some framing to introduce why a participant would be visiting their Profile Page. This should help the participant get in the mindset, thinking about this product, ideally without priming them more than a real situation. Either something like: 
"you got an email notifying you of an issue with your address, this prototype is where the link led." 
Or if accessing by logging in and seeing the alert on their Profile then something more like: 
"how often do you go to or look at your Profile?
What are the reasons you visit your Profile?
Let's pretend you [reason stated] and so you decide to visit your profile"

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by SKasimow** [comment]
@cgednalske feedback for research.

cc/ @Samara-Strauss

**Comment by SKasimow** [comment]
@claytonzook - made the updates you suggested. ok to close?

**Comment by claytonzook** [comment]
@SKasimow feel free to close at your discretion, thank you!
