### ISSUE TITLE
QA Feedback - Staging Review - Public Websitse - IE11 Deprecation Alert

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#43099]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/42893

## Thoughts/questions
None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- CSS centering must be fixed to match the other alert on the homepage:
<img width="1302" alt="Screen Shot 2022-06-17 at 4 46 19 PM" src="https://user-images.githubusercontent.com/3535749/174405609-cff0383a-00ea-4eec-a85b-4a1d7f8071d3.png">

**Should:**
- There is no option to close the alert. Should there be one?

**Consider:**
None

**Comment by kind-claudio** [comment]
@ddzz The VA facility banner seems to be using [va-banner](https://design.va.gov/storybook/?path=/docs/components-va-banner--default) which looks to be composed of [va-alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--fullwidth). I can switch over to using the `va-banner` instead which will likely resolve the centering issue.

Regarding the dismissible UI/behavior, the "mockup" does include that, so I can add that in, as well.

**Comment by wesrowe** [comment]
Centering and dismissibility have both been addressed. Closing issue.
