### ISSUE TITLE
Better differentiation between ophthalmology & optometry

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4310]
## Story
[feedback from production UAT session] As a veteran with eye care needs, I want to more easily understand whether I should request an optometry or ophthalmology appointment so that I see the right kind of doctor for my eye issue.

## AC
- [x] Veterans are not confused about which type of care to pick between the two

**Comment by rtwell** [comment]
this shouldn't need a comp, just the words @peggygannon

**Comment by peggygannon** [comment]
@markgreenburg @rtwell Please let me know if the below content will work for eye care: 

Choose the type of eye care appointment that you need
**• Optometry** 
You can schedule an optometry appointment for a routine eye exam, eye test, or to treat conditions like glaucoma or low vision. Optometrists will also give you a prescription for eyeglasses or corrective lenses.  
**• Ophthalmology** 
You can schedule an ophthalmologist appointment for the diagnosis and treatment of more serious eye conditions that may need surgery, like cataracts, macular degeneration, diabetic retinopathy, or other eye diseases.

**Comment by peggygannon** [comment]
Closing this issue. Dev implementation ticket is here: 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4853
