### ISSUE TITLE
Draft requirements gathering/service design section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43109]
## Story
As an engineer developing a microservice I would like to learn what microservice-specific guidelines I should consider when defining the requirements for my service, therefor the microservice playbook shall address this question.

## Acceptance Criteria 
- [x] Service design's work here is referenced and linked https://vfs.atlassian.net/wiki/spaces/SDT/pages/2210660360/How+to+Service+Design+Your+Tool+Service
- [x] Define what are good targets for microservice -- include a reference to the list of potential services
- [x] What makes a good service (“discrete units of functionality”) 
- [x] Types of services (software-to-software versus human-to-software)
- [x] Brief overview of guidelines and rules (12 factor (EKS) , ZTA,  openAPI etc)
- [x] Include guidance that people should pick the language that best suits their needs.
- [x] Include guidance with how to build the "developer funnel" (how to go from developing your service to getting people to use it)

**Comment by FHiatt** [comment]
IN progress, ready for review EoD today.

**Comment by ewilson-adhoc** [comment]
Ready for team review https://vfs.atlassian.net/wiki/spaces/IET/pages/2285502750/Microservice+Service+Design
