### ISSUE TITLE
Additional Console UI Onboarding

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#43103]
## Description
The Console UI team has provided some additional requirements that are needed to onboard platform-console-api to platform-console-ui. Details can be [found here](https://github.com/department-of-veterans-affairs/platform-pst-console-ui-configuration/issues/78#issuecomment-1157958808).

## Acceptance Criteria
- [ ] Console API is onboarded with the proper details to Console UI

**Comment by LindseySaari** [comment]
PR here: https://github.com/department-of-veterans-affairs/platform-console-api/pull/255

**Comment by LindseySaari** [comment]
https://github.com/department-of-veterans-affairs/platform-pst-console-ui-configuration/pull/90

**Comment by npeterson54** [comment]
This is done
