### ISSUE TITLE
Draft logging playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43114]
## Story
As an engineer responsible for maintaining a microservice, I would like guidelines about how to integrate with infrastructure's logging systems, therefore I would like his section to be included in the playbook. 

## Acceptance Criteria 
- [ ] Give an overview of what tools are currently available for use, what tools the VA wants to use, and what our recommended tools are (include possible link to migration plan recommendations). 
- [ ] Give an overview of who maintains these tools. 
- [ ] Recommendations for formatting logs (aka, structured logs)
- [ ] How to set up your logs to stream into existing logging pipelines (loki). 
- [ ] How to verify that your logs are being pipped into the correct place. 
- [ ] Include information about how to access the logging systems (socks, etc)
- [x] 12 factor techniques to keep in mind
- [x] Guidelines for observability
- [x] How ZTA intersects with logging (EL1 logging maturity)

**Comment by ewilson-adhoc** [comment]
In progress -- would like to nail down a definitive answer what is the status of the different tools we are using (loki, prometheus, datadog, what is the depreciation timeline) for these.

**Comment by FHiatt** [comment]
Observability is via Datadog for vets-api runtime
So we need to say how we transition to it

**Comment by FHiatt** [comment]
will take a look at organizing the doc and add appropriate diagrams for draft.
Will have Microservices Playbook in draft state by end of week where we might have available for review.
