### ISSUE TITLE
Draft dockerizing your application section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43111]
## Story
As as an engineer who is creating a service, I want to know how to stick my application in a docker file, therefore I would like a section of the microservices playbook to go through this process. 

## Acceptance Criteria 
- [ ] Describe a high level overview of using docker (or link to useful tutorials)
- [ ] Define differences between local development and running the application in K8s. 
- [ ] Describe the naming conventions and file structures. 

## Open Questions
Reach out to console service team -- they are thinking of building out a tool to automatically generate this: we should

**Comment by FHiatt** [comment]
In-progress, looks straightforward.
