### ISSUE TITLE
Draft testing section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43116]
## Story
As an engineer responsible for maintaining a microservice, I would like guidance on special considerations for testing within this architecture, therefor I would like this data in the playbook. 

## Acceptance Criteria 
- [x] Describe how to use Github actions for running tests. 
- [ ] Use newman + Postman collections an example for how smoke tests can be run. 
- [ ] Give code coverage guidelines (start at 75% as a baseline, more is better)
- [ ] Describe pact or contract testing -- we didn't do this, but maybe we should mention that it exists? (specifically, that this kind of testing is important for integrating different services). 
- [ ] Give an overview of what testing is recommended for different stages of development (Unit testing, Functional testing, Integration/Systems tests).
- [ ] Guide for how to set up testrail for manual testing.
- [ ] Mention performance testing (possibly reach out to infrastructure for how-to)

## Resources
This can serve as a base for this document: https://vfs.atlassian.net/wiki/spaces/IET/pages/2089189650/How+to+Deploy+Microservice+to+Development

We should also look at the documents that infrastructure has put out, to see if they have anything that is useful.

**Comment by ewilson-adhoc** [comment]
https://github.com/department-of-veterans-affairs/pst-iet-team.documentation/tree/migration_plan

**Comment by FHiatt** [comment]
separate section required for postman section
