### ISSUE TITLE
Draft (CI)CD section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43115]
## Story
As an engineering developing a microservice for the platform, I would like to know how  I leverage existing infrastructure to deploy my microservice onto EKS using argoCD, therefor I would like this data in the playbook. 

## Acceptance Criteria 
- [ ] Describe how to use GithubActions to build your container images and push them into the elastic container repository on AWS. 
- [ ] Be sure to include mentions of recommendations such as semantic versioning.
- [x] Link to section of document related to testing -- mention that CI is done with github actions. 
- [ ] Describe how to use ArgoCD + manifests repository to deploy whenever changes are made. 

## Resources
This can serve as a base for this document: https://vfs.atlassian.net/wiki/spaces/IET/pages/2089189650/How+to+Deploy+Microservice+to+Development

We should also look at the documents that infrastructure has put out, to see if they have anything that is useful.

**Comment by FHiatt** [comment]
Will to meet with with Sal to complete
