### ISSUE TITLE
Draft sunsetting section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43119]
## Story
As an engineer who wants to deprecate a service that I have created from vets-api, I would like guidance on how to do that in the playbook. 

## Acceptance Criteria 
- [x] Describe how to deprecate a service in vets-api. 
- [x] Describe how to deprecate a service. 

## Resources
https://vfs.atlassian.net/wiki/spaces/IET/pages/2176745490/Deprecate+an+endpoint

**Comment by considerable** [comment]
In the spirit of [how](https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/products/platform/platform-website/2021-04-02-deprecate-homepage-decision.md) Platform deprecated pages in the past, the old endpoint must not give 404 upon deprecation.
So let's keep the old endpoint up, yet produce [301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) and redirect to the new URL.

**Comment by FHiatt** [comment]
Redirect to new service URL if it exists (include language when page will be deprecated)
If not new page exist, redirect to an explanation page
It Understood if it is an application it will break
We also want to report out (communicate) that the page/link is/will be deprecated at somepoint (or has been deprecated)
