### ISSUE TITLE
Draft authentication/integration with AMT playbook section

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43113]
## Story
As an engineer responsible for determining who has access to do what with my service, I would like to integrate my microservice with AMS, therefor I would like this data in the playbook. 

## Acceptance Criteria 
- [ ] Describe the technically agnostic solutions for authn/authz in a microservice. 
- [ ] Describe how to set up a microservice with AMS/keycloak specifically. 
- [ ] Describe how to use traefikEE OIDC middleware to provide authn/z on the kubernetes ingress. 
- [ ] (optional?) How to traefik community forwardAuth middleware with sidecar to provide authn/z
- [ ] (optional) How to use in-application code authorization flow to provide authn/z (with traefik) - considerations for when this may cause problem, autoscaling?

## Resources
We can leverage access management's guides as a base https://vfs.atlassian.net/wiki/spaces/AMT/pages/2066907264/Guides

**Comment by FHiatt** [comment]
reading through AMT docs and considering how to layout doc.
