### ISSUE TITLE
Draft monitoring tools section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43117]
## Story
As an engineer responsible for maintaining a microservice, I would like guidelines about how to integrate with infrastructure's metrics systems, therefor I would like his section to be included in the playbook. 

## Acceptance Criteria 
- [ ] Give an over view of what tools are currently available for use, what tools the VA wants to use, and what our recommend tools are (include possible link to migration plan recommendations). 
- [ ] Give an overview of who maintains these tools. 
- [ ] How to set up your events to stream into Datadog
- [ ] How to set up your traces to go into sentry
- [ ] Include information about how to access these systems (socks, etc)
- [ ] 12 factor techniques to keep in mind
- [ ] Guidelines for observability

## Open Questions
We may want to consider putting this with the logging section and creating a generic "observability" section

**Comment by FHiatt** [comment]
source metrics and logs for this (e.g. duration). Igor will make recommendations to obsolete current logging/metrics/tracing tools and replace with Datadog and recommend sundown for Grafana.

**Comment by considerable** [comment]
Current Links:
- ArgoCD UI [https://argocd.vfs.va.gov](https://argocd.vfs.va.gov)
- DataDog UI Logs [https://vagov.ddog-gov.com/logs](https://vagov.ddog-gov.com/logs)
- DataDog UI Dashboard [Sidekiq UI Access Log](https://vagov.ddog-gov.com/dashboard/7n8-5a5-abj/sidekiq-ui-access-log?index=%2A&from_ts=1659549483948&to_ts=1660154283948&live=true)

Legacy Tools to be deprecated:
- Grafana Server manifest in ArgoCD 
- Loki Agent manifest in ArgoCD
- Sentry Agent manifest in ArgoCD
- CloudWatch Agent manifest in ArgoCD
- Grafana UI [https://grafana.vfs.va.gov](https://grafana.vfs.va.gov)
