### ISSUE TITLE
[Research]My VA Redirect: Create Research Plan

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43129]
## Background
As part of the My VA Redirect initiative we want to conduct user research. This ticket is to create the plan for our user research.

## Tasks
- [ ] Create Research Plan based on [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)

**Comment by andaleliz** [comment]
[Research plan draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/research-plan.md) started

**Comment by andaleliz** [comment]
@ericasauv09 Has the team determined which sprint they'd like to run UAT in? Would it be in the next one, or the following (second half of July).  Looks like it's not outlined in the sprint objective doc yet.

**Comment by andaleliz** [comment]
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/research-plan.md) complete
