### ISSUE TITLE
[Research]My VA Redirect: Create Conversation Guide

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43128]
## Background
In order to conduct user research regarding our new My VA Redirect feature we need to create a conversation guide for our user research.

## Tasks
- [ ] Draft conversation guide based on [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

**Comment by andaleliz** [comment]
[Convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/conversation-guide.md) complete
