### ISSUE TITLE
Move Datadog dashboards to Fedramped version

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#43121]
## Description
At the end of the month, our current instance of DataDog at [datadoghq.com](http://datadoghq.com/) will be going away in favor of the fedramped version [vagov.ddog-gov.com](http://vagov.ddog-gov.com/). All metrics and traces will be moved over, but dashboards, monitors, and synthetic tests will need to be ported over manually. Console Services should be sure to transfer over anything belonging to our team that won't be automatically moved over. 

See additional details in the [slack thread](https://dsva.slack.com/archives/CJYRZK2HH/p1655494972231319)

## Acceptance Criteria
- [x] Document what dashboards, monitors, and synthetic tests belong to console services
- [x] Move over necessary items belonging to console services
- [x] Notified infra when completed.

**Comment by RachalCassity** [comment]
Dashboards to move over:

- VSP Utility - Redis
- VSP Utility - Sentry
- External Performance Service Template
- VSP Utility - GitHub
- Console Services
- VSP - Application Request Breakdown
- VSP - External Service Performance Indicators
- VSP - Breakers
- VSP - External Service Status
- Console Services - Backend Service Report

**Comment by RachalCassity** [comment]
This monitor will have to be created when the prod metrics are sent to the Datadog.



![Image](https://user-images.githubusercontent.com/32692924/175117723-2c1cf899-88ee-46c6-9b93-00134a6f1d7b.png)

**Comment by RachalCassity** [comment]
Full list of services from the Datadog trial:



![Image](https://user-images.githubusercontent.com/32692924/175126565-cf70e70d-6947-4c94-899e-a16cc89945cd.png)

**Comment by RachalCassity** [comment]
@zachclarity The dashboards listed are what I have moved over.

**Comment by npeterson54** [comment]
This is done
