### ISSUE TITLE
[Design Research] Banking Info in 526 review step

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4313]
## User Story:
As a claimant, I need to confirm my banking information when finalizing my 526 form so that I can ensure accurate information has been collected when I submit my form.

## Tasks
- [ ] Review notes from bug that identified this need #2345
- [ ] 

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Testable Outcome Y
- [ ] Testable Outcome Z

**Comment by luke-gcio** [comment]
Closing as OBE.  We have review capability for banking info.
