### ISSUE TITLE
Add 800 ph # to Pension "intent to file" info

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4316]
## User Story or Problem Statement
As a Veteran, I need to know that I have a phone option for submitting/declaring my intent to file for pension benefits, so I can quickly and easily establish my intent date without using a form.

On this page: https://www.va.gov/pension/how-to-apply/ 

Per SME email:
You can add the 800-827-1000 number to the pension page as well – the NCC agents are trained and equipped to document pension and survivor ITFs as well.

## Acceptance Criteria
- [x] Add info per SME email thread, similar to Disability intent to file udpate /jen
- [x] Randi or Peggy has reviewed and checked copy. 
- [x] Preview link is sent to Angie Smith, and CC Regina Yount at the VBA call center./jen
- [x] Update is published.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
@RLHecht @peggygannon - can one of you check the updates I made here: http://preview-prod.vfs.va.gov/preview?nodeId=586 and edit anything that needs it. Couldn't hyperlink the phone # as we usually do. 

This is making similar update in the Pension INTENT TO FILE section that the Disablity page is. Per Regina's email, the pension business is now using the same VBA 800 NCC phone number for intent to file.

**Comment by jenniferlee-dsva** [comment]
p.s. This is not urgent, but it would be nice to match the Disability intent to file updates, so there's parity, before the code freeze 12/23.

**Comment by RLHecht** [comment]
I copyedited this page and fixed the hyperlink for the phone number. Just waiting on Peggy to weigh in on the word "declare." Will publish later today.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I just sent Angie the preview link. Could we wait for her reply before publishing? If she doesn't reply by Thursday, I'll ping her and let her know it's going out on Friday before Monday's code freeze.

**Comment by jenniferlee-dsva** [comment]
Angie confirmed the change is accurate. This can be published. @RLHecht

**Comment by RLHecht** [comment]
This page is reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
Validated on live site.
