### ISSUE TITLE
Request Contact Center Review for "Your VA disability ratings" Tool Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4317]
### Context  
The **"Your VA disability ratings"** page is where Veterans can view their combined disability rating and the individual disability ratings in their record.

### Links  
**Staging URL:** https://staging.va.gov/disability/view-disability-rating/rating
**Product Guide:** https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/rated-disabilities/call-center
**Product Video:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/Rated-Disabilities-Call-Center-Walkthrough.mp4
**Product Video Transcript:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/your-va-disability-ratings-video-script.pdf

**Comment by clantosswett** [comment]
@jason-gcio we will be reviewing these items over the next few days and will let you know if we have any questions. In the meantime, do you know the planned go-live date for this new feature?

**Comment by jason-gcio** [comment]
@clantosswett, @Kimberley2019 
Our timeline isn't set in stone per se, but it looks like we will be in good shape in early January.

**Comment by jason-gcio** [comment]
@clantosswett Just wanted to touch base and see if there was anything else we could add to this documentation?

**Comment by clantosswett** [comment]
@jason-gcio Sorry for the delay on responding to this. Everything looks good to me but I did have a one question about the call center numbers provided. In the video, you highlighted two numbers. The one listed under the "What if I have questions" heading makes sense, but I wasn't sure what the other number was and where it pointed to. If you could just clarify that, we will move forward with getting the video added to the VA.gov youtube channel and notify all the call centers. Thanks!

**Comment by jason-gcio** [comment]
@clantosswett The second number (855-574-7286) is the VA.gov Help Desk number and is used on other pages/error notifications as well.  We tested it as live, although we were put on hold before hanging up.
cc: @sporeboy

**Comment by clantosswett** [comment]
@jason-gcio that is an old number is not used anymore for VA.gov support. We should instead direct them to 844-698-2311. Thanks!

**Comment by jason-gcio** [comment]
@clantosswett Ok, sounds good. We will updated that number.  I think the video is non-specific so we shouldn't need to re-create that.  If we update it, can we proceed?

**Comment by clantosswett** [comment]
Yep! No need to redo the video. Is there a target date for the launch?

**Comment by jason-gcio** [comment]
I don't have a date per se as we are waiting for the results of our 508 review but I anticipate this month.

I also updated the Content team in Slack on that new number so future teams use the right one.  [Here is a link to the page we originally got it from.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/design-system/guidelines/error-handling/Content%20Style%20Guide.md#next-step-calls-to-action)

**Comment by clantosswett** [comment]
Awesome. Thanks for the link and thank you for giving the content team the heads up. Once you have a confirmed date, please let us know so we can notify the call centers of the exact timeline.

**Comment by jason-gcio** [comment]
@clantosswett Will do!
cc: @steve-gov

**Comment by jason-gcio** [comment]
@clantosswett Oops, sorry I closed this.

**Comment by clantosswett** [comment]
Hi Jason. I am reopening this until we have the date for the launch. The call center team will close it once we have everything we need for full notification of the call centers. Thanks!
