### ISSUE TITLE
Document Data QA for Data Engineer

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43199]
## Issue Description
We need to define and document data QA requirements/steps for the data engineer before hand off to data analysts.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
@michelle-dooley @jonathan-epstein13 @pavanhothi 

Draft of the [BigQuery QA doc](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery) is ready for your review. Let me know your thoughts!

**Comment by michelle-dooley** [comment]
@chloedotbrown I think this looks great!!  Obviously we can add to as needed,  This will be a big help for a new data engineer.  @pavanhothi and @jonathan-epstein13 - any feedback?  If not I think we are good to close this ticket.

**Comment by pavanhothi** [comment]
@chloedotbrown this looks great to me as well! Very detailed and descriptive, and easy to follow and understand. Nice work!

**Comment by jonathan-epstein13** [comment]
@michelle-dooley I was able to take a look. It looks pretty clear and straight forward. @chloedotbrown looking forward to applying this to BQ data check.

**Comment by chloedotbrown** [comment]
Thanks, all! Going ahead and closing ticket.
