### ISSUE TITLE
[research] Conduct Phase 1 interviews with SMEs and Collaborative Teams

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#43198]
Conduct Phase 1 interviews with SMEs and Collaborative Teams

- What are the biggest challenges for Decision Reviews?
- What is considered new and relevant evidence?
- Can we learn from any efforts where the VA was able to presumptively connect Veterans to a claim? [ i.e. Blue Water Navy ]
- Can we learn from other benefit automation efforts?
- How does this work relate to the personalization initiative?

PHASE 1: Subject Matter Experts (SMEs) and Collaborative Team Members

**Stakeholders**
Matt Self
Shawna Hein
Paul Shute

**Collaborative Teams**
Lighthouse Benefits Crew (ongoing)
Benefits Automation Crew (ongoing)
Contact Center
Content/IA Team (ongoing)

**Comment by thehastingsp** [comment]
Interviews are complete, working towards a top level summary

**Comment by thehastingsp** [comment]
This has been done and is in synthesis
