### ISSUE TITLE
Update vets-api to return provider name with appointments call on CC request

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#43194]
As part of the CC request flow, the provider name is returned to the user once they submit their appointment request. This name is retrieved separately from the rest of the information at that point in the flow, via the getProvider endpoint built from this work: https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/36913

Vets-website is updating to merge this provider name with the rest of the data they currently use: https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/42146

However, for convenience to the frontend in this particular case, we will update vets-api to utilize this getProvider endpoint as part of the response to the appointments endpoint, then serve the unified data set to the website.

This work will take place as part of post v2 launch stabilization/cleanup, and will be tabled until then.

AC:
[ ] vets-api includes provider name on response to a CC request

**Comment by ldelacosta** [comment]
This is a duplicate. We will handle this work in #43195
