### ISSUE TITLE
[research] synthesis

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#43201]
Synthesize desk research and interviews to produce a top line summary.

**Comment by thehastingsp** [comment]
Synthesis is happening here: https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1656423801188?sender=uf4e8628bdc7dc81e50353314&key=036c7cd3-dc92-4927-ae5e-49f72b5dba8e
