### ISSUE TITLE
[FE] Update list of facilities that support prescription texts in notification preferences section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#43206]
## Background

Justin Wowk (VEText PM) emailed us with an updated spreadsheet of facilities that support prescription text messages (attached). Currently, we are showing this preference conditionally in the Notification preferences section to people who go to eligible facilities. We need to review the list of facilities for which we are conditionally showing this preference, and update it based on this spreadsheet.

## Tasks

- [x] Update the list of facilities for which we show the prescription text preference based on the attached spreadsheet of eligible facilities

## Validate

- [ ] If we can figure out which staging users are part of which facilities, we can validate this by making sure this preference is showing for staging users that are part of the facilities in this list.

Otherwise, we may not be able to validate this work in staging.

[VEText_RX_Notification_Facilities_June 2022.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8960841/VEText_RX_Notification_Facilities_June.2022.xlsx)

**Comment by Samara-Strauss** [comment]
cc/ @SKasimow for awareness. We can add this to sprint 77.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss I have a PR in to update these facilities. As I went through and cross checked the various facility numbers with the existing list, I did find one that is _currently_ in the list, but was not in the newest spreadsheet. Should this facility be removed?

The Facility in question is `'608', // Manchester VA Medical Center (Manchester, NH)`

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 we don't have a way to validate facilities, as it's unclear how staging users are assigned. If you validated locally, this should be good to go.
