### ISSUE TITLE
[research] Phase 2: Form gap assessment

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#43200]
- What are the biggest challenges Veterans face when filing supplemental claims?
- What are the biggest challenges adjudicators face in approving claims?
- What is considered new and relevant evidence?
- Where are the opportunities to pre-fill, automate or presumptively connect Veteran claims?
- How does communication with the Veteran typically happen during supplemental claims processing?

**Comment by thehastingsp** [comment]
https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1655823912560?sender=uf4e8628bdc7dc81e50353314&key=4c748934-3cdd-43e2-9a4b-a67f97249cbb

**Comment by thehastingsp** [comment]
This is done to the point of ideating opportunities and risks, which can be f[ound in the Mural here](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1655823912560?sender=uf4e8628bdc7dc81e50353314&key=4c748934-3cdd-43e2-9a4b-a67f97249cbb). We will continue to use this board to dig into deeper technical discovery, but the gap assessment high level part is done.
