### ISSUE TITLE
Search component for Urgent Care MVP (design)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4321]
**This issue represents one area of the urgent care redesign(MVP)**

 ## User story 
- As a veteran, I need to be able to search for an urgent care facility so that I can seek care. 

## Objectives or Key Results this is meant to further
- Improve the Veteran Search Experience (Veterans have the information they need to be prepared for an urgent care visit. )
- Reform Community Care Implementation

## Acceptance Criteria
- **Output:** workflow diagrams (Aricka) for use in editing/creating prototype screens (Ryan) to be used to develop the MVP for this area of the redesign (Please attach to the development issue for this component [#4322]. )
  
- Final design must pass all relevant reviews
  - Design
  - Content  
  - Accessibility 

- Design should include: 
     [ ] List of contents for drop down search boxes
     [ ] Label for each search box
     [ ] Any text that is expected to be displayed in each search box
     [ ] Relevant design details for font, size, color, etc.
     [ ] Description of page/modal/component flow (if new)
     [ ] Workflow/area for displaying urgent care subtype definitions
- Should incorporate previous community and urgent care research, Facility Locator discovery research and feedback

- Veteran can search for an Urgent Care facility using the existing FL search feature drop down
    - _Veterans are not expected to be able to filter or search by facility sub-type (pharmacy, retail or walk-in) for this MVP but may need to for future iterations. Design should consider this possible next iteration although it does not need to be exposed to user for MVP._
    - _Language/facility label (ie: urgent care, etc) should be as Veteran-friendly as possible, given user input during research._ 
- Urgent care sub-type definitions should be displayed for Veteran understanding and use in differentiating search results. 
- Existing search functionality for all other facility types should be maintained
  - _User must still enter city, state, zip_
  - _User can still select VA health care, Vet Center, VA Cemetery and non-urgent Community Care (not sure what words should be used here)_
  - _No changes are expected for list in service drop down appearing for non-urgent care Community care_

**NOTE** The Urgent care PDF workflow design is documented in [#4325].

**Comment by mmiddaugh** [comment]
@davidconlon please confirm that I have captured the requirements for this area of the redesign

**Comment by mmiddaugh** [comment]
@LouCarlozo63 can you or someone on your team review the following and suggest appropriate wording? 
**Context: **The Veteran will need to download/print a three page document to take to the urgent care provider and/or pharmacy. This screenshot is part of the prototype workflow for searching for urgent care facilities: 
![image](https://user-images.githubusercontent.com/55411834/71211100-46041200-2263-11ea-82e7-30ef2bda77db.png)

**Comment by rtwell** [comment]
@mmiddaugh @davidconlon if you could toss the PDF in here for reference that would be great

**Comment by davidconlon** [comment]
@rtwell We have them here. Want to be careful of duplicating and tracking the files themselves.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3268#issuecomment-568520068

**Comment by rtwell** [comment]
ah, i didn't see that last line in the ticket description—my b!

**Comment by mmiddaugh** [comment]
@arickalewis1 please attach artifact

**Comment by arickalewis1** [comment]
Attaching flow for search criteria.
[FL-Search-Flow-Content.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4010603/FL-Search-Flow-Content.pdf)
