### ISSUE TITLE
Copy edit review of new, consolidated Manage debt page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#43223]
## Story

As a Veteran, I need one pathway to everything I need to manage my VA debt for benefit overpayments and copay bills.

## What's needed

Danielle created a new, consolidated page that will eventually replace the existing Manage debt page. For now, it's in a different Drupal node because we were hoping to publish it and test it behind a feature flag. We may now need to recreate the page in staging, depending on dev team decision.

We need a copy edit of this page as early as possible on 6.23.22 so we can pass it off to developers.

Page is here: http://preview-prod.vfs.va.gov/preview?nodeId=46933

**Comment by DanielleThierryUSDSVA** [comment]
@denisecoveyduc Randi is aware this is coming for a copy edit tomorrow and we'll get it over to you all as soon as possible. Thanks!

cc @mnorthuis for awareness

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn! This is ready for you to copy edit when you're in this morning. Feel free to reach out with any questions. Thanks very much!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn! This is ready for you to copy edit when you're in this morning. Feel free to reach out with any questions. Thanks very much!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much, @megzehn!

Answers to your questions:

- For this sentence under "What you can do when you sign in," should it be your VA debt, instead of VA debt? Current version: "Check the amount and status of VA debt related to VA disability compensation, non-service-connected pension, or education benefits." I haven't changed it, because I wanted to confirm.
  - Yes, I think adding "your" is great here. Thank you!

- I added this language next to TTY:711, since that's the pattern I've seen up to this point, but let me know if there's been a change. "If you have hearing loss, call TTY:711."
  - We very recently had a call about this with accessibility folks and I believe we're moving away from this language. Could you revert? I'll confirm for future efforts so we can document and be consistent. Thanks for raising this!

- Under benefit debt, we ask for checks to be payable to "U.S. Department of Veterans Affairs," and under copay bills, we ask for checks to be payable to "VA." Is that intentional? Or should we make them the same? 
  - Great question! Let's leave for now, as this is how we've had this to date. But I will flag this to double check with our SMEs.

**Comment by megzehn** [comment]
Thanks for the quick responses, @DanielleThierryUSDSVA!  I removed the TTY hearing loss language and added "your."  

Does this go back to you or @RLHecht? Or is it ready for me to publish?

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @megzehn! We're going to hold off on publishing for now. The debt team may need to recreate this in staging instead so that they can test it first. I'll circle back when it's time to publish. Thank you again for the quick turnaround on this and the great catches and questions!

@denisecoveyduc This is ready for you all. Note that the sign in widget is a placeholder...your dev team will need to create the new one specific to the new experience. Thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @denisecoveyduc Can I close this ticket or will you both still need to do more work in it?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I think we can close this copy editing ticket. But we'll have more work on this page and related pages. Could you open a new ticket with the following:

- Move content from manage debt consolidated test page (this page here in this ticket) into the real manage debt page
- Move supporting debt and copay bill content into resources and support articles

@denisecoveyduc  2 questions related to moving forward with this work:

1. When are we aiming to launch this?
2. Is there a need for UAT testing and/or a slow rollout of this consolidated page? If yes, we'll need to collaborate on making sure we can serve up the right content at the va.gov/manage-va-debt url at launch.

**Comment by DanielleThierryUSDSVA** [comment]
Also, @RLHecht - @Dr-Pongo is going to reach out here about how we're going to handle hiding this test page from production for the usability testing. Thanks!

**Comment by Dr-Pongo** [comment]
Hey all!
So we have opened [a PR to add a widget](https://github.com/department-of-veterans-affairs/vets-website/pull/21493) that is specific to the combined debt portal with the [originally planned](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/debt-portal.md) `manage-debt-and-bills` URL schema. 
We are hoping that once vets-website is deployed after 2pm today you can publish this page so we can have our test users navigate to the page on prod. Our next session is at noon tomorrow (6/29). 

After UAT is complete on `manage-debt-and-bills` we can coordinate the rollout of the official page/url. The idea here is to not interfere with the existing production page for the sake of testing, and we can get some much needed terminology feedback. I don't believe the Drupal page will be indexed, and we have a feature flag on our side so any user trying to navigate past `manage-debt-and-bills` will be redirected to the homepage, so there will be minimal impact with production. 

Please let me know if you have any comments/concerns!
CC: @denisecoveyduc @OptionSelect @megzehn

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
