### ISSUE TITLE
Analytics Implementation or QA Support for Digital Health Platform - Wearables Activity

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#43225]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Team: Digital Health Platform
    - Points of Contact: 
       - @robbie1226 Kimberly Roberts (Project Manager) - kroberts@thoughtworks.com
       - @zanniemill49 Suzanne Miller (Product Manager) - suzanne.miller@thoughtworks.com
       - @mchaffee-tw Michael Chaffee (TL) - Michael.Chaffee@va.gov

 
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - We would like to track 2 environments:
       - Production: https://www.va.gov/health-care/connected-devices
       - Staging: https://staging.va.gov/health-care/connected-devices
    
- **When is the launch date?**
    - Staging is live and we are planning to launch in production mid-2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

    | Ref | Event | VA.gov URL | Comments |
    | ------------- | ------------- | ------------- | ------------- |
    | 1 | User accesses the Registration landing page  | /health-care/connected-devices  |  |
    | 2 | User begins registration flow  | /dhp_connected_devices/fitbit | the URL is in Vets-API |
    | 3 | User completes registration flow successfully  | /health-care/connected-devices/?fitbit=success#=  |  |
    | 4 | Registration flow completes unsuccessfully  | /health-care/connected-devices/?fitbit=error#= |  |
    | 5 | User disconnects a device successfully  | /health-care/connected-devices/?fitbit=disconnect-success#=  |  |
    | 6 | User disconnects a device unsuccessfully  | /health-care/connected-devices/?fitbit=disconnect-error#=  |  |
    | 7 | Tracking logging in  | /health-care/connected-devices?postLogin=true  | Is there a way to tell which method the user chose to log in with? |

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by robbie1226** [comment]
Adding a link to DHP's [Product Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-platform/README.md)

**Comment by michelle-dooley** [comment]
@robbie1226 - thank you for your submission.  We will review as part of our grooming session tomorrow and get back to you on timing.

**Comment by robbie1226** [comment]
Updated the points of contact to include DHPs Product Manager @zanniemill49

**Comment by jonathan-epstein13** [comment]
Hello @robbie1226 @zanniemill49 @mchaffee-tw
 
Here are 2 different reports to look at in regards to the URL tracking.
[GA Pages report. ](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w178298118p176884211/_u.date00=20220601&_u.date01=20220706&explorer-table.filter=health-care~2Fconnected-devices&explorer-table.plotKeys=%5B%5D)(adjust for dates)
[GA Login method report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220601&_u.date01=20220706&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22login-success%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Fhealth-care~2Fconnected-devices%22,0%5D%5D) - no data yet until product launch. (adjust for dates)
If you would like a funnel (exploration) report, we can set up a funnel for the successful flow while (leaving out the error pages) then still using the pageviews to get a sense of the error volume. Let us know if you have any questions or concerns.

**Comment by robbie1226** [comment]
Thanks @jonathan-epstein13. I'll look over what you shared and get back to you with any questions.

**Comment by jonathan-epstein13** [comment]
@robbie1226 just following up to see if you need anything else from us.

**Comment by robbie1226** [comment]
@jonathan-epstein13 there's nothing else needed. Just learnt that the tracking we requested is already provided / out of the box. Since there's nothing we need to do on our end and I have not questions, I have not objections to closing this issue. Thanks!

**Comment by jonathan-epstein13** [comment]
No worries! Glad we can help. Thank you @robbie1226
