### ISSUE TITLE
List and map display of urgent care search results MVP (design)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4323]
**This issue represents one area of the urgent care redesign (MVP)**

## User story
- As a Veteran, I need to be able to view the results of my urgent care search so that I can select one. 
- As a Veteran, I need to understand the types of urgent care facilities so that I can choose the appropriate one for my situation. 
- As a Veteran, I need to view details about the facility so that I can prepare for my visit. 
- As a Veteran, I want to see the results of my urgent care search displayed in a list and map so that I can choose a facility based on location. 

## Objectives or Key Results this is meant to further
- Improve the Veteran Search Experience (Veterans have the information they need to be prepared for an urgent care visit. )
-  Community Care Implementation

## Acceptance Criteria
**Output**
- Workflow diagrams (Aricka) for use in editing/creating prototype screens (Ryan) to be used to develop the MVP for this area of the redesign. 
- Please attach screens to the development issue for this component [#4324 ]. 

**General AC**
- Wire frame must pass all relevant reviews
  -  Design
  - Content  
  - Accessibility 
- Wire frames should include:
   [ ] Cards for displaying search results
   [ ] Information related to the number of cards to be returned
   [ ] Information related to the method for displaying the cards (scrolling vs pagination)
   [ ] Expected filters that should be displayed following each type of search
   [ ] Iconography to be used to correlate facilities between list and map 
   [ ] All text fields that should be included for each facility card displayed 
   [ ] Any text fields that should be displayed on the map
   [ ] Any linked list content and the content that should be shown via link (including PDF if linked from card)
   [ ] Any linked map content and the content that should be shown via link 
   [ ] Relevant design details for font, size, color, etc.
   [ ] Description of page/modal/component flow (if new)

**AC specific to Facility type = Community care + urgent care (and sub-types)**
- Facilities returned in **Community care + urgent care search** results should display the following card detail: 
  - Name of Facility
  - Type of Facility (urgent/walk-in/pharmacy, as defined in [#4321]
  - Address
  - Phone Number
  - Directions
  - Distance
  - Instructions to call facility for hours of operation (pending Content team input from [#4241)
  - **NOTE**: These facilities will no longer link to Facility Detail pages. 
- As part of this type of search, definitions for types of urgent care facilities should be displayed for Veteran understanding and use in differentiating search results (if not addressed in [#4321]

**AC specific to Facility type = Community care- Non-VA Health (everything except urgent care and sub-types)**
Facilities returned in **Community care- Non-VA Health** results should display the following card detail: 
  - Name of Facility
  - Services (ie: Podiatry)
  - Address
  - Phone Number (found in referral language)
  - Directions
  - Distance
  - Referral language: _If you have a referral: Call this facility at xxx-xxx-xxxx. If you don’t have a referral, contact your local VA medical center._
  - **NOTE**: These facilities will no longer link to Facility Detail pages. 

**AC specific to Facility type = VA Health, including Vet Centers**
Facilities returned in **VHA and Vet Centers** results should display the following card detail: 
  - Name of Facility
  - Type of Facility (ie: VA Health or Vet Center)
  - Address
  - Main Phone Number
  - Mental Health Phone Number
  - Directions
  - Distance
  - Link to Facility detail page

**AC specific to Facility type = Benefits**
Facilities returned in **Benefits** results should display the following card detail: 
  - Name of Facility
  - Type of Facility (ie: Benefits)
  - Address
  - Main Phone Number
  - Directions
  - Distance
  - Link to Facility detail page

**AC specific to Facility type = Cemetery**
Facilities returned in **Cemetery** results should display the following card detail: 
  - Name of Facility
  - Type of Facility (ie: State Cemetery)
  - Address
  - Main Phone Number
  - Directions
  - Distance
  - Link to Facility detail page

**Comment by mmiddaugh** [comment]
@davidconlon please review my requirements above. 
In particular, what is expected behavior for search results displayed for other facility types? (Both VA-owned and Community Care)

**Comment by mmiddaugh** [comment]
Per conversation yesterday:
- "Emergency care" and "In VA Network urgent care pharmacy" should be available as service types under VA Health

**Comment by arickalewis1** [comment]
A few comments as I review this:

- My understanding was that we will not link to the detail pages for this MVP.
- Cemeteries do not currently list the phone number (do we have this information?)
- I was also assuming that "in VA network urgent care pharmacy" would actually be a location type and not a service type

**Comment by arickalewis1** [comment]
Uploading a revised search flow including @mmiddaugh comments above
Also uploading the card type content
[FL-MVP-Card-Types.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4020910/FL-MVP-Card-Types.pdf)
[FL-MVP-Search-Flow-Content.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4020911/FL-MVP-Search-Flow-Content.pdf)

**Comment by mmiddaugh** [comment]
https://vsateams.invisionapp.com/share/EZVJMETDFTK
