### ISSUE TITLE
AWS access for Aditya Sharma

### ISSUE THREAD

**Issue by TW-Addy** [department-of-veterans-affairs/va.gov-team#43255]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Aditya Sharma

### Your Email

aditya.sharma@thoughtworks.com

### Your Team, Role, and Company

QA Engineer 

### Product Manager (PM) name and email

Alina Murphy <amurphy@thoughtworks.com>

### Product Owner (PO) name and email

Luciana Morais <luciana.morais@va.gov>

### Desired AWS Access

Similar permissions as [kha.huynh@thoughtworks.com](mailto:kha.huynh@thoughtworks.com) && [justin.trieu@thoughtworks.com](mailto:justin.trieu@thoughtworks.com)

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
@TW-Addy is listed in VFS Team Roster.

**Comment by iriteshp** [comment]
User: Aditya Sharma
COR: Cecilia Lee
VOR: Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by td-usds** [comment]
ping @TW-Addy

> @TW-Addy can you add which specific privileges you need within AWS? Additionally, is this truly ongoing or only for a particular time-window? The request is overly vague/broad.

**Comment by td-usds** [comment]
Also reached out to VOR for info

**Comment by TW-Addy** [comment]
@td-usds Thanks Thomas, I essentially need access to configure aws credentials and it is ongoing. 
You can refer to my teammates' permissions and give me the same. 
**Teammates** - kha.huynh@thoughtworks.com, justin.trieu@thoughtworks.com, krkrishn@thoughtworks.com

**Comment by td-usds** [comment]
Access approved
