### ISSUE TITLE
create custom eslint rule to flag as deprecated imports from /platform that do not use new yarn syntax

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#43253]
Currently, apps import from platform via `platform/path/to/module`. If the folder in platform has been converted to a workspace, we want to show a warning that the import should be of the form `@department-of-veterans-affairs/platform-<folder>/path-to-module`.

**Comment by it-harrison** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/846) created; ready to be merged/published once yarn workspaces enter production on vets-website.

**Comment by rmessina1010** [comment]
PR Merged. Closing issue.
