### ISSUE TITLE
Fixing Lee Helmer's DSVA Slack Access - can't fully login, blocked by 2FA

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#43268]
# Description

- Full member: Lee Helmer is already a full member of DSVA Slack, but can't fully login, blocked by 2FA
<img width="1082" alt="Screen Shot 2022-06-23 at 11 26 15 AM" src="https://user-images.githubusercontent.com/17835066/175348455-e293d2d2-40e3-4d78-9113-c9c66d60bae7.png">

## Descriptions 

- Please help Lee Helmer regain access to her DSVA Slack, she is locked out because her 2FA is not accessible to her (it was accidentally deleted from her auth app, and she does not have the backup codes)

**Comment by LEHigley** [comment]
@lhelmer who is the COR?

**Comment by lhelmer** [comment]
@LEHigley Looks like the COR is Cecelia Lee. Do you need contact info for her?

**Comment by LEHigley** [comment]
@lhelmer yes please!

**Comment by lhelmer** [comment]
@LEHigley cecelia.lee@va.gov
![Screenshot 2022-06-28 11 49 26 AM](https://user-images.githubusercontent.com/17835066/176236108-2e617d3e-e059-4a30-b75b-e0e49903cbc6.png)

**Comment by LEHigley** [comment]
2FA is disabled

**Comment by lhelmer** [comment]
@LEHigley TY, I was able to login and create a new 2FA. All set.
