### ISSUE TITLE
508-defect-2: List loop pattern heading and unique labelling defects

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#43305]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Details

The list loop patterns in this flow have known issues that have been flagged in previous audits including:

- **Inconsistent headings**; some cards have headings, others don't
- **Duplicative button and field labels;** screen reader users can get lost in duplicative, non-descriptive labels

## Acceptance Criteria

- [ ] Input fields are uniquely labelled
- [ ] Headings are logically ordered

## Proposed Solution (if known)

This is an ongoing issue which I don't believe has a sitewide solution to yet. We should probably check in with the design system team to see if there has been more progress on list loop patterns in general.

### Headings are inconsistent

<img width="885" alt="Screen Shot 2022-06-23 at 2 24 54 PM" src="https://user-images.githubusercontent.com/14154792/175368780-17b34c48-7d57-4f9c-883b-1757e4bad154.png">

### Navigating by form controls is ineffective with non-descriptive labels
<img width="559" alt="Screen Shot 2022-06-23 at 2 35 23 PM" src="https://user-images.githubusercontent.com/14154792/175371332-3ead8b46-6a73-4572-a1f9-b301c30b4600.png">

**Comment by jacobworrell** [comment]
@joshkimux we have the same issue related to the latest comment here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/43262

We have to consider this blocked until we can coordinate with the sitewide team on the best approach.
