### ISSUE TITLE
Update the Additional Info component to be used for Learn More expandable sections in forms

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#4330]
This ticket is to update the Additional Information component ( https://design.va.gov/components/additional-info ) to conditionally use that component as an `<a>` tag with `role="button"` and adding a listener for the SPACE keypress. This is a bit convoluted, but was necessary to not interfere with screen reader normal "click" behavior on `<label>` elements.

The prototype code we tested is on Codepen here: https://codepen.io/tpierce_402/pen/PoYVKKa

Please ignore the tooltips for now; those will be addressed in a separate epic. We are interested in the Learn More "accordion" sections being available to slot in after the `<legend>` tag, and inline in `<label>` tags without disrupting or being read aloud by screen readers.

The Codepen has been rigorously tested with the big three screen readers and with screen reader and screen magnifier users. It does make some opinions about how to mark up radios and checkboxes, but that is not in scope.

The epic #1817 has the entire description of the problem, and our threaded conversations around how we could approach fixing it, and the groups we engaged.

/cc @KevinMHoffmanUSDS && @andreahewitt-odd for visibility

**Comment by 1Copenut** [comment]
@andreahewitt-odd Do we want to keep this in our camp, or assign to VSP-Tools-FE?

**Comment by 1Copenut** [comment]
@Clark-W-Griswold && @rianfowler Is there someone I should ask if they can prioritize this item? I discovered today in testing that the Learn more button `aria-label` is not read aloud by iOS VoiceOver when it's wrapped in a label. Legends work, but not labels.

**Comment by rianfowler** [comment]
@1Copenut should we update it to a defect 2 now?

**Comment by 1Copenut** [comment]
@rianfowler Yes, let's go ahead and bump this up to a defect-2.

**Comment by 1Copenut** [comment]
Issue moved to [department-of-veterans-affairs/vets-design-system-documentation #246](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/246) via [**ZenHub**](https://www.zenhub.com/)
