### ISSUE TITLE
Midpoint Review - Design Feedback - Auth Exp My VA: Payment info section v2

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#43307]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great work, love all the testing you are doing and asking great questions! I know this page has a lot going on, using the action links with the icon links with alerts and defaults links makes this page feel very busy. It is almost impossible to scan. The action link followed by the icon link on mobile is very awkward, the spacing is very different. Also pay attention to the card headers, the page as a whole seems to use different header styles for each card and feels overwhelming. 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

- Outstanding debts and Recent payments” should be coded as an H3

**Should:**
- Change the individual debts/payments cards to show the Due date/ amount due first and the name of the place second
- Make sure the mobile and desktop comps match as far as link styles, I noticed active links on mobile but not on desktop

**Consider:**
- Change the card listing debts/payments to a table or individual cards. See the [authenticated info example](https://design.va.gov/patterns/authenticated-info-list).
- Consider when/if “Add 1 more outstanding bill” truncation text line will appear on desktop.

## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by ajakabcin** [comment]
Closing

**Must:**
- section headers are H3s

**Should:**
- Due date vs amount due order is moot point as we were not able to show the amount owed in our final implementation (due to debt center data limitation)
- Active link style used throughout
