### ISSUE TITLE
Turn on Education GI Bill Statement of Benefits from Education Service

### ISSUE THREAD

**Issue by RileyRPM** [department-of-veterans-affairs/va.gov-team#43315]
## What does your team need support for? Check all that apply.
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [X] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
Recently the GI Bill Statement of Benefits was turned off at the request of Education Service. However, since turning it off, there have been numerous inquiries from the public and the Education Call centers are getting overrun with calls. Although there is an incorrect delimiting date, being published, education service feels that it's acceptable as opposed to having the Statement of Benefits be entirely unavailable. The Statement of Benefits 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: 6/23/2022
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [X] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Darla van Nieukerk (OIT) Joshua Lashbrook (VBA-EDU)
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel: #education-benefits

Additional story will be needed to correct the delimiting date. 

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
This is an old ticket we can close.
