### ISSUE TITLE
508-defect-1 ❗ Transportation expense status message isn't announced to screen reader users

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#43318]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user navigating through a form, I will miss the note on transportation expenses that dynamically appears visually without being announced or accessible by the tab key or up and down form control swipe actions on iOS VoiceOver

## Details

When the user checks "transportation services" a new field and note/status box appears telling them that they will need to upload documentation for the expenses at the end of the application

## Acceptance Criteria

- [ ] The note is embedded as hint text within the `label` OR
- [x] The note uses `aria-live="polite"` to announce itself politely to screen reader users

## Steps to Recreate

1. [Go to step 4: benefits selection](https://staging.va.gov/burials-and-memorials/application/530/benefits/selection)
2. Turn on your screen reading device
3. Check transportation expenses
4. Confirm that the note is not programmatically announced 

## Proposed Solution (if known)

See acceptance criteria

### Screen reader users may tab directly over the paragraph.

https://user-images.githubusercontent.com/14154792/175381663-7afce08d-725d-4a67-babe-fa542843e940.mov

### Rewriting the content to fit in as hint text could fix the issue

<img width="667" alt="Screen Shot 2022-06-23 at 3 19 01 PM" src="https://user-images.githubusercontent.com/14154792/175381913-06f79e15-8e90-4957-b849-ac99011090f8.png">

**Comment by jaredcunha** [comment]
@joshkimux Went with the option to use `aria-live="polite"`. Have some rationale in the PR if you want to take a look.

**Comment by joshkimux** [comment]
Sounds good! Thanks @jaredcunha 🥳
