### ISSUE TITLE
Conduct a content audit for all Learn More buttons in forms based on work for GIBCT

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#4331]
@peggygannon and I were talking the other day about the Learn More button text for GIBCT and how that related to the entire form system universe. She mentioned she'd like to run a full forms audit to see how often we are using this phrase in our forms, and what might be good contextual labels.

The original ask was around Learn More buttons for GIBCT. Peggy's response can be reviewed here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/1817#issuecomment-547554127

I think this is the right approach, to offer a bit more context when users read or hear these labels.

**Comment by 1Copenut** [comment]
@peggygannon Hello. I wanted to circle back briefly on this item and see if you had any updates or would like to review further. Thank you!

**Comment by caw310** [comment]
Closing as this over 2 yrs old and I believe the Additional info component addresses this.
