### ISSUE TITLE
AWS access for Jacob Uhteg

### ISSUE THREAD

**Issue by Jake-Uhteg** [department-of-veterans-affairs/va.gov-team#43311]
### COR Name

Other

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Jacob Uhteg

### Your Email

jacob.uhteg@oddball.io

### Your Team, Role, and Company

VA Notify, Test Engineer, Oddball

### Product Manager (PM) name and email

Megan Siddle megan.siddle@oddball.io & Melanie Jones melanie.jones@oddball.io

### Product Owner (PO) name and email

Beverly Nelson beverly.nelson@va.gov

### Desired AWS Access

Need access lighthouse developers IAM (lower envs only) for testing VaNotify notifications within vets-api.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
@Jake-Uhteg is in the VFS Team Roster

**Comment by iriteshp** [comment]
@Jake-Uhteg who is your COR?

**Comment by kjduensing** [comment]
Just bumping this - @Jake-Uhteg would you mind editing the description or commenting with the name of your COR? Thanks!

**Comment by iriteshp** [comment]
User: Jacob Uhteg
COR: Reney (Laurene) Cook
VOR: Amber Malcolm
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS Access approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user via DSVA Slack workspace DM at this time.
