### ISSUE TITLE
[06/28/22] Draft and Send VEText Admin Training Email

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#43355]
## Description
Now that the VEText annual user audit is underway, it is time to begin referring all VEText admins to complete a round of training (either live with @djfredvs or through a self-paced video) and a short quiz. The product support team needs to reach out to begin this process with a deadline of **July 15, 2022** to successfully complete training.
---

## Acceptance Criteria
- [x] Draft email 
- [x] Include links to booking app, video, and quiz
- [x] Set deadline with admins
- [x] Review with team
- [x] Send
---

**Comment by ahicksfearless** [comment]
- Sent an email out to the first batch of confirmed Admins on 7/5/22. 
- Next step is to send a reminder email to the POCs who have yet to confirm Admin Users for their sites
- Once POCs review the list in full, we can send out another batch of Training emails @chancetheoriginal @lindsay-insco @jwowk

**Comment by lindsay-insco** [comment]
Email and subsequent sent
