### ISSUE TITLE
[07/08/22] VEText Message Volume Dashboard

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#43359]
## Description
As message sending transitions over to VA Notify, it is helpful to communicate the volume of messages for each feature in VEText. A dashboard that breaks down # of messages sent by feature is requested.
---

## Acceptance Criteria
- [x] Discuss idea with @jwowk and @lindsay-insco 
- [x] Build draft dashboard
- [x] Post dashboard to group channel for review
- [ ] Dashboard approved by @jwowk and @lindsay-insco 
---

**Comment by Cmjones233** [comment]
Draft has been post to slack for review

**Comment by Cmjones233** [comment]
Adding PCI and COVID. Waiting for Melissa's feedback

**Comment by Cmjones233** [comment]
Adding PCI and long and shortcode information

**Comment by Cmjones233** [comment]
won't be able to add short code and long code data
