### ISSUE TITLE
Update Spanish Content based on State Department QA

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43361]
## Tasks
- Update the Spanish json file and relationships based on the [final QA files](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/README.md#final-spanish-translations-received-from-the-state-department-on-6242022-qa-round) received from the State Department on 6/24/2022 
- Update the screenshots (take screenshots from Staging) in the following documents to be provided to the State Department
    - [Pre-Check-in Workflow](https://docs.google.com/presentation/d/17f9MSgkKgojsojnkYqx1WgPeWbdBIicNPK8f4JAFN5Y/edit?usp=sharing)
    - [Check-in Workflow](https://docs.google.com/presentation/d/1zjr90_oo5JSX_fTIG5nmef1sFAlGrLgSsUr04_FZmQk/edit?usp=sharing)
- Verify updates

**Comment by brianseek** [comment]
I've updated translation strings from latest QA json. Here are some strings that were provided but we don't use in our application:
`"a-staff-member-will-help-you-on-the-day-of-your-appointment-to-update-your-information": "Un miembro del personal le asistirá el día de su cita para actualizar su información."`

We do have this though:
`"a-staff-member-will-help-you-on-the-day-of-your-appointment": "Un miembro del personal le asistirá el día de su cita."`

These are for the design system and not included in our translation keys:
```
"collapse-all": "Contraer todo",
"collapse-all-accordions": "Contraer todos los acordeones",
```

**Comment by brianseek** [comment]
@loripusey can you review my comment above before I make all the screenshots?

**Comment by loripusey** [comment]
Yes, I think there were some that got translated that we are not currently using. Looks ok

**Comment by brianseek** [comment]
@loripusey I had to push a change to fix an issue on the check-in confirmation page. While waiting for that to hit stage here are the rest of the screenshots[https://app.zenhub.com/files/133843125/52e989d1-e7c2-496a-914c-680229e91a0a/download](https://app.zenhub.com/files/133843125/52e989d1-e7c2-496a-914c-680229e91a0a/download)

**Comment by brianseek** [comment]
@loripusey last screen shot for the check-in complete page ![day-of-check-in_spanish_check-in-complete.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/eb51dc2d-2652-4607-961d-15cc128b54d8)
