### ISSUE TITLE
Staging: Virtual Care Manager (VCM) Recently Added New Instructions to Veteran

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#43363]
VCM used to only have two Instructions to Veteran.  Recently VCM added three new Instructions to Veteran:  1) Message Sent in MyHealtheVet 2) Resources Mailed to Patient 3) Signup for MyHealtheVet Messaging.  So now there are 5 VCM options for Instructions to Veteran.   These three new instructions need to be added to VAOS.  

1.  Log into VCM create five new upcoming appts using the following codes: 1) Medication review 2) Message Sent in MyHealtheVet 3) Resources Mailed to Patient 4) Signup for MyHealtheVet Messaging and 5)Video Visit Preparation.
2.  Log into VAOS and select to view the appointment details.  On the details page select Prepare for Video Visit to display the VCM Instructions to Patient.  
3.  Results expected:  Instructions to veteran display in VAOS and are similar to what was selected in VCM.
4.  Results seen:
         VAR- Resources (vaos service v0):  The existing reasons display as expected. The three new reasons display the Video Visit Preparation instructions 
         VAOS Service (vaos service v2) :  The existing reasons display as expected. The three new reasons do not display at all. There is no Prepare for Video Visit section.  

![VAOSv0_VCM_Instructions.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/2662a5a4-ecf8-46e2-83fd-f4fb1d164032)

![VAOSv1_VCM_Instructions.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/249c68ee-7bf7-47ab-b826-b2972947454e)

**Comment by ldelacosta** [comment]
We have a [spike ticket created ](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/43051) to research the 1:1 mapping for the VAOS instructions. Looking to improve the logic for the VVC appointments.

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this issue was given a **Medium** priority

**Comment by ldelacosta** [comment]
#43051 - Will need to review how we should improve the logic for VVC appointments

**Comment by ldelacosta** [comment]
[Discussed the ticket with our Product Owner Team [Kay, Mark, Stephen and Patrick on 08/17] Upon review, this requires additional research and considered a low priority on the FE. We don't anticipate this to be completed before the go-live date.

**Comment by marcynadeau** [comment]
From Kay Lawyer- in talking with the VCM team, it doesn’t seem that those instructions are in use very much.

**Comment by ldelacosta** [comment]
We will open a new feature once we have defined the instructions with the VCM team. Closing out the ticket. cc: @JRRoof
