### ISSUE TITLE
SOCKS access for [Aaron Young]

### ISSUE THREAD

**Issue by TW-Aaron** [department-of-veterans-affairs/va.gov-team#43375]
### Your Name

Aaron Young

### Your Email

aaron.young@thoughtworks.com

### Your Role and Team

Developer - Virtual Agent (Chat Bot)

### Product Manager (PM) name and email

Alina Murphy amurphy@thoughtworks.com

### Product Owner (PO) name and email

 Luciana Morais Luciana.Morais@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7BuwWn4LYWSf/pGr8vmbBjnNF8KNua4OMX0Jg76WkD3Q4+TW6C5htUvbcbnYUmsy64+k8yKL8+1AEuTbGmNMVgSHcqjfInJhJyIlrhwmiKCzR9ujYEloCG2wCtDzBfWAMfj4J3B9K81goXlDwaHn8bbDSziYvnPEIOwwGi7KwWp5jBRD3/tGqmGwIt86xLpfohKYgWlJoF1bgtoDMedeZvGW9x2koLQkpnUrMq91CywRkFvOWfsJSvzr776G8CWHCqwDvlznaRhpJ8QY/uUM5xyGnrgCGaGx3MwPZ8rS7iWawUK6MKpVLhzZOP85VurcttsDD8Gnty4m4QR8K9uX7jKqcf8tJuld7aE/M4dnoE61W8fvHyd+RtcFAVafM/a8678WdvJiTUg0++f29C6vACI4WKZKH8dNXry7Efm7jd6sU3BRSla7nBfkKNJm5ivjD765qQx346VZ9HAHlDJxikKAv2CyF/6ItJZfAiyGKgV/OHNJs7yWDgQ7EBt2WZ8U= aaronyoung@AaronstwtempMBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
