### ISSUE TITLE
Design | BAI | Usability testing topline summary

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43383]
## Background

Complete topline summary for UAT

## Tasks
- [x] Create summary

## Acceptance Criteria
- [x] Publish summary and Sharon with PO and PM
- [ ] Post to Github research folder

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- I have the [BAI topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/research/topline-summary.md) ready for review! Let me know if any changes are needed.

**Comment by SKasimow** [comment]
@cgednalske - nice job! I don't have any changes.

**Comment by Samara-Strauss** [comment]
This is great! Thank you!

**Comment by SKasimow** [comment]
@cgednalske can this be closed?

**Comment by cgednalske** [comment]
@SKasimow yes it can!
