### ISSUE TITLE
[OPS][DOCUMENTATION] Guidelines for loaned devops engineer

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#43380]
## Description

Infrastructure team currently has a devops engineer loaned to us. Since this is something new for both teams, it is important to capture expectation and define guidelines how to onboard the loaned devops engineer, as well as how we can better enable them

Some starting key points can be the following:
- How long will devops engineer be loaned for?
- Will work be assigned from the initial team or will be working on stories from Infrastructure backlog?
- Is there specific outcome from this loan?
- Should they be added to `vsp-operations` group?

---
## Tasks
- [ ] Create a confluence page with guidelines for the loaned devops engineer

## Acceptance Criteria 
- [ ] TBD

**Comment by jhouse-solvd** [comment]
This is no longer relevant. Please consult the Platform DevOps Community of Practice for the allocation of DevOps engineering resources.
