### ISSUE TITLE
PACT Act single Q&As and dedicated page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#43390]
## Story

As a Veteran or family member, I need one place to find out how the PACT Act may affect my VA benefits and services.

## What's needed

- Create an initial series of single Q&As that VA can use to populate a dedicated page, publish as individual Q&As (as needed), and use to populate content in the chatbot, IVR, and other channels.
- Create a multi-FAQs page to surface all PACT Act Q&As, segmented by impacted audience group.
- Monitor analytics to determine highest value Q&As for potential single publishing.
- Monitor SEO, onsite search, and contact center data for potential additional Q&As to add over time.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @laurwill @megzehn.

This page will need a first-pass copy edit on Monday morning in case people are looking at it: http://preview-prod.vfs.va.gov/preview?nodeId=47278.

And then you'll definitely need to continue updating this page based on final messaging that you should get through the VHA daily standup meetings and PACT Act Teams channel.

For example, there's a question in [one of the Teams docs](https://dvagov.sharepoint.com/:w:/r/sites/PACTActCommsImplementation/Shared%20Documents/General/PACT%20Act%20Q%20and%20A%20v2%2006-26-22.docx?d=w8cb2a111f94940cba602a1350f962abc&csf=1&web=1&e=swL5hx) that's about whether you can apply for VA health care even if your condition isn't considered presumptive yet. There's a note that the answer needs more input so it's not final, but that's one you'll likely want to add.

Also, there are some provisions in the actual draft law that talk about being able to file for compensation early in certain cases...I haven't seen that yet in any docs, but it may come up. 

Thanks so much for handling this while I'm out!

**Comment by DanielleThierryUSDSVA** [comment]
@LucianaAlexanderMorais FYSA this is the main Veteran-facing PACT Act page that the chatbot can point people to once the law passes. http://preview-prod.vfs.va.gov/preview?nodeId=47278. The content is all draft and not approved at this point. The team will let you know as soon as it's published. Thanks!

**Comment by megzehn** [comment]
Hi! I reviewed this page. I have a few questions for @DanielleThierryUSDSVA, @RLHecht, or @laurwill before I make additional changes. 

1. In the 3rd bullet of the second para, should we define “presumptive condition” a bit more? 

Current: Adds more than 20 new presumptive conditions related to burn pits and other toxic exposures

Suggested: Adds more than 20 new presumptive conditions (conditions we’ve determined are connected to burn pit and other toxic exposures in Afghanistan, Iraq, and certain other areas)

2. Should we add “free” after “Provides” in this bullet point? “Provides toxic exposure screenings to every Veteran enrolled in VA health care” 

3. I wonder if we could add any text after the phases to make it less confusing. 

"If you have one of these conditions, you may be eligible for [VA benefits?] after we add it to the presumptive condition list."

**Comment by laurwill** [comment]
Hi @megzehn , as we chatted, I just reached out to Lauren to check if these tweaks are okay — I'll update once I hear back!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @laurwill @RLHecht. First additional copy editing request. Could you please take a look at this Q&A? Thank you!

http://preview-prod.vfs.va.gov/preview?nodeId=46478

**Comment by DanielleThierryUSDSVA** [comment]
@laurwill @RLHecht I also made some minor changes to some Q&As and alerts so they should get another review. Will continue adding as I finalize them on my end. Here are a couple to start:

http://preview-prod.vfs.va.gov/preview?nodeId=47693
http://preview-prod.vfs.va.gov/preview?nodeId=47228

**Comment by RLHecht** [comment]
This page is now live. Going to close this and we can open up new tickets if/when we have to make changes to any of the Q&As.
