### ISSUE TITLE
Remove COVID-19 vaccine full-width alert

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#43392]
## Story

As a Veteran or family member, I need only the most critical, timely information in a full-width alert.

## What's needed

It's time to retire the full-width COVID-19 vaccine alert on relevant pages. As we prepare for the PACT Act, we'll need to put PACT Act related alerts on certain pages and we want to minimize alerts.

- [x] Remove [COVID-19 vaccine full-width alert]([url](https://prod.cms.va.gov/banner/covid-19-vaccines-at-va)) from all pages
- [x] Review COVID-19 in-page alerts on relevant pages and determine which to keep and which to remove

**Comment by RLHecht** [comment]
@megzehn The CMS team pointed me to where this alert is. It was different from the one we were looking at in the alerts section. 

https://prod.cms.va.gov/admin/content?title=&type=banner&moderation_state=All&owner=All 

You can change the moderation state to archived and it will remove it from all the pages.

**Comment by megzehn** [comment]
This alert has been archived. 

Thanks for your help with this, @RLHecht

**Comment by RLHecht** [comment]
Danielle confirmed we can take copay alert down (that we're collecting copays again)

**Comment by megzehn** [comment]
^ CC @RLHecht !

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Do you want to look at the ones Megan flagged and let us know which ones we should take down?

**Comment by laurwill** [comment]
@megzehn to add more detail here and chat with Danielle.

**Comment by RLHecht** [comment]
@megzehn I added to your comment above what pages some of those alerts are on so we know whether it's OK to remove them from all of them.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I went back in to Megan's comment above and added the pages that we have some of those alerts on. Can you let us know if they are good to remove?

**Comment by RLHecht** [comment]
I archived the two alerts we talked about and will confirm they are removed from the live pages after the content release.

**Comment by RLHecht** [comment]
Validated on live site that these are no longer on the pages. Closing!
