### ISSUE TITLE
Fill out new database field values for top forms

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4339]
2 new database fields are being added to the VA forms database. We need to provide Kevin Reid and other form owners the field values for the 2 new fields for the top forms we have identified. 

**User story 1:** 
As a Veteran who looks for a form, I need to know at a glance if there is an online application available and what type of benefit that form/application is used for.

**User story 2:** 
As a form manager, I need to know how to select/fill out the new database fields in the forms library, so that when the form comes up in a VA form search result, Veterans can see quickly what benefit(s) that form is used for and if there's an online alternative. 

**Task:**
Provide the new database field values for our top forms, as identified in  @lwalsh617 's WIP copydeck. (See repo for copy.)

**Draft spreadsheet is attached here:** 
[VA-forms-mvp-redesign-new-db-fields-121019 (Excel)](https://app.zenhub.com/files/133843125/5b4186dd-72a9-471f-88ce-8958949a4407/download)

**The new fields are:**

- Related to field value (multi-select)
- Online tool field value (destination URL if an online tool is available). 
Note: Some online tool URLs will point ppl to the 'how to apply' page, not the tool REACT page.

Product repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

**Comment by jenniferlee-dsva** [comment]
@Karak888 fysa

**Comment by jenniferlee-dsva** [comment]
@lunascoop - A couple of additions to the Related to field values that I forgot to include in the spread sheet attached in the original ticket story ^. 

Please also be sure to include
- Family member benefits
- Service member benefits

Related to multi-select values are alpha ordered (except for the non-benefit related options).

**Comment by jenniferlee-dsva** [comment]
Hi @lunascoop - I'd love to check in about ^. LMK.

**Comment by lunascoop** [comment]
@jenniferlee-dsva Let me know your availability to chat about it. Here's a draft version.
[5b4186dd-72a9-471f-88ce-8958949a4407.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4020946/5b4186dd-72a9-471f-88ce-8958949a4407.xlsx)

**Comment by lunascoop** [comment]
Here is an updated draft[ version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-mvp-redesign-new-db-field-010620.xlsm) with multi-selection features enabled (for Column D of Top forms for MVP 1.0 sheet).

**Comment by jenniferlee-dsva** [comment]
See slack message - due to file upload issues on GH: https://dsva.slack.com/archives/C52CL1PKQ/p1578534232074100?thread_ts=1578534186.074000&cid=C52CL1PKQ

**Comment by jenniferlee-dsva** [comment]
@lunascoop and @lwalsh617 to connect on a few discrepancies btn spreadsheet and copydeck. 

Per call w/Laura: Confirming yes to remove edu form 28-1990 and 8832 from both copydeck and spreadsheet.

**Comment by jenniferlee-dsva** [comment]
This work is complete, so closing the ticket. 

I walked through the spreadsheet with the forms db manager and he made one additional change/requirement to be added. I will create a separate ticket for that work to update the spreadsheet.
