### ISSUE TITLE
Log :view_runtime and :db_runtime data with StatsD

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#434]
In order to improve performance, we must first track it.

## User story
As an engineer, In order to improve app performance, I must first have performance metrics to benchmark against.

## Goal
Track `:db_runtime` data with StatsD.

Links:
[Rails instrumentation documentation](https://edgeguides.rubyonrails.org/active_support_instrumentation.html#process-action-action-controller)
[Example implementation blog post ](https://signalvnoise.com/posts/3091-pssst-your-rails-application-has-a-secret-to-tell-you)

## Acceptance criteria
- [x] `:db_runtime` data is viewable in Prometheus

**Comment by annaswims** [comment]
We already have this data in cloudwatch.  I wonder if there's a way to graph it there. 

https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log;filter=%7B$.payload.db_runtime%20%3E500%7D;start=PT1H

**Comment by annaswims** [comment]
DB and view runtimes are now available in grafana in these graphs

http://grafana.vfs.va.gov/dashboard/db/vets-api?panelId=24&fullscreen&orgId=1&from=now-2d&to=now

http://grafana.vfs.va.gov/dashboard/db/vets-api?panelId=23&fullscreen&orgId=1&from=now-2d&to=now
