### ISSUE TITLE
AWS access for Matt (William) Gardner

### ISSUE THREAD

**Issue by allthesignals** [department-of-veterans-affairs/va.gov-team#43412]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Matt (William) Gardner

### Your Email

mattgardner@navapbc.com

### Your Team, Role, and Company

OCTO Benefits Delivery - Software engineer at Nava PBC

### Product Manager (PM) name and email

Amy Lai

### Product Owner (PO) name and email

Zach Goldfine (zachary.goldfine@va.gov)

### Desired AWS Access

I need access to the vets-api Rails console in a production EC2 instance to assist with research questions that the product team has for feature work related to ABD (automated benefits delivery).

### Access Expiration

6 months (re-review)

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by allthesignals** [comment]
Thanks @kylesoskin! What steps does my team leadership need (@emilytheis) to complete for this? Does she need to reach out to someone to have me added to the roster?

Separately, it looks like I can start platform orientation on my own.

**Comment by rmtolmach** [comment]
@allthesignals, in the documentation Kyle linked, it shows that if you start the orientation, you will be added to the VFS roster (if you're on a VFS team). From the link Kyle posted, click on "[Directions for new VFS team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html#Guidancefornewteamsandteammembers-NewVFSTeammembers)."

**Comment by kjduensing** [comment]
@allthesignals, the next step is for this request to be approved by the POs in conjunction with the COR. If they approve, I'll make the PR to add your permissions.

**Comment by td-usds** [comment]
Reached out to VOR

In the mean time, @allthesignals , do you need a 6 month window to do that research or can that window be shrunk? What is the time line allocated in your team for completing that research?

**Comment by td-usds** [comment]
> > In the mean time, @allthesignals , do you need a 6 month window to do that research or can that window be shrunk?
> 
> Yes, I need the 6 month window because we will need to be able to use it consistently to build and debug features and inform researchers on product work.
> 
> > What is the time line allocated in your team for completing that research?
> 
> Our current roadmap has us doing specific work through October but we anticipate needing to do related work through January.

I can approve access until the end of October with a re-assessment mid-October.

Requested AWS Access approved until 2022-OCT-31.

**Comment by rmtolmach** [comment]
✔️ Prod SSM access added to William.Garder's AWS account. I added a reminder to remove access on 10/31/22 if an extension hasn't been granted. Closing.

**Comment by rmtolmach** [comment]
@allthesignals, looks like you don't need the prod access anymore. I'll remove it today unless I hear otherwise.
