### ISSUE TITLE
Test Sign In service Behavior

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#43446]
Test Sign In Service behavior, put findings in the comments here

**Comment by bosawt** [comment]
Overall the biggest things I found that we’ll have to come up with solutions with SiS on backend are:
ID.me requires 2fa twice when upleveling
InProgressForms won’t play nice with SiS and non-SiS (an issue if certain users might go back and forth in how they’re authenticating)
Credential information is preferred over MPI information with name, ssn, b-date (might not be an issue in a real world situation since this will be close if not always the same, but worth coming up with a plan here)

**Comment by nsoutouras** [comment]
@nsoutouras add to bug epic

**Comment by nsoutouras** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Web%20Rollout%20Phase%201%20(testing).md

**Comment by nsoutouras** [comment]
https://docs.google.com/spreadsheets/d/1kJANirJPyI-yh4hhRCkLPXnZtO3bM8NB6OT6XgSqCus/edit?usp=sharing
