### ISSUE TITLE
Add logic for the Type of Care label [Booked CC appt/Booked VA direct] 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#43460]
## Description
The type of care label should not be displayed on the appointment details page if the data is not available. Only when the type of care data is available, the frontend will display the label. 

For example: CC booked appointment 

<img width="519" alt="Screen Shot 2022-06-24 at 9 44 48 AM" src="https://user-images.githubusercontent.com/90797205/176019875-9b69684b-9f1d-4ee0-8295-f50137aafd55.png">

Response body: 

`Status` is `booked` and `serviceType` is not available 
<img width="969" alt="Screen Shot 2022-06-27 at 3 55 12 PM" src="https://user-images.githubusercontent.com/90797205/176024710-3d7b6f7e-ee97-4e23-87c2-33fd3bac1bd9.png">

---

## Acceptance Criteria

Given when the staff schedules the Community Care appointment for the Veteran
When the `Status` is `booked` and `serviceType` is `blank or null ` 
Then the appointment details will not display the type of care label 

Given when the staff schedules the Community Care appointment for the Veteran
When the `Status` is `booked` and `serviceType` is unavailable 
Then the appointment details will not display the type of care label 

Given when the staff schedules a VA appointment for the Veteran
When the `Status` is `booked` and `serviceType` is `blank or null ` 
Then the appointment details will not display the type of care label 

Given when the staff schedules a VA appointment for the Veteran
When the `Status` is `booked` and `serviceType` is unavailable 
Then the appointment details will not display the type of care label 

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this was issue given priority to be High

**Comment by simiadebowale** [comment]
@aaronhietpas @ldelacosta  this is ready for review

**Comment by ldelacosta** [comment]
@aarathi-poldass - This is ready to be validated. Please let us know if you have any issues. Thanks!

**Comment by aarathi-poldass** [comment]
Re-tested the defect with 2 scenarios. Please find below the detailed discerption: 

**Scenario 1:**  When HSRM doesn't return the Type of Care field in the response body for a booked appointment, VAOS is not displaying the type of care on FE. 
**Response body:**
    {
      "id": "117292",
      "type": "appointments",
      "attributes": {
        "id": "117292",
        "identifier": [
          {
            "system": "http://med.va.gov/fhir/urn/vaos/hsrm/id",
            "value": "524621||6||1"
          }
        ],
        **"kind": "cc",
        "status": "booked",**
        "patientIcn": "1013120830V747912",
        "locationId": "984",
        "start": "2022-07-23T13:30:00Z",
        "created": "2022-07-22T13:40:57Z",
        "cancellable": true,
        "extension": {
          "ccLocation": {
            "address": {
              "line": [
                "10640 MAIN ST ; STE 100"
              ],
              "city": "FAIRFAX",
              "state": "VA",
              "postalCode": "22030",
              "text": "10640 MAIN ST ; STE 100\nFAIRFAX VA 22030"
            },
            "telecom": []
          },
          "hsrmTaskId": ""
        },
        "location": {
          "id": "984",
          "type": "appointments",
          "attributes": {
            "id": "984",
            "vistaSite": "984",
            "vastParent": "984",
            "type": "va_health_facility",
            "name": "Dayton VA Medical Center",
            "classification": "VA Medical Center (VAMC)",
            "timezone": {
              "timeZoneId": "America/New_York"
            },
            "lat": 39.74935,
            "long": -84.2532,
            "website": "https://www.dayton.va.gov/locations/directions.asp",
            "phone": {
              "main": "937-268-6511"
            },
            "physicalAddress": {
              "type": "physical",
              "line": [
                "4100 West Third Street"
              ],
              "city": "Dayton",
              "state": "OH",
              "postalCode": "45428-9000"
            },
            "healthService": [
              "Audiology",
              "Cardiology",
              "DentalServices",
              "Dermatology",
              "Gastroenterology",
              "Gynecology",
              "MentalHealthCare",
              "Nutrition",
              "Ophthalmology",
              "Optometry",
              "Orthopedics",
              "Podiatry",
              "PrimaryCare",
              "SpecialtyCare",
              "Urology",
              "WomensHealth"
            ]
          }
        }
      }
![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/6eaae1fd-bf81-4199-ad9b-3240b819e2bc)

**Scenario 2:** When HSRM returns the Type of Care field in the response body for a booked appointment. I tried multiple instance and HSRM is not returning the type of care, so I reached out to Kent and Moshe to see if we can send that field in the response so that I can validate it on the VAOS side. I'm still awaiting their response.

**Comment by aarathi-poldass** [comment]
As per the discussion with Grace and Marcy the system is working as expected. @ldelacosta as this passed validation please go ahead and close the ticket. Thank you!

**Comment by ldelacosta** [comment]
Validated the changes in staging and no issues reported. 
The TOC label is not shown since the data is not available. 
![Screen Shot 2022-07-26 at 12.39.09 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/46237900-75dd-4756-81fb-2dc2c6ac7771)
