### ISSUE TITLE
[research] Supplemental Claims Form Field Audit

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#43477]
As a product designer I would like to know the destination of every field in the VA Supplemental Claims form 20-0995. 

- [x] List each form field included in the form
- [x] Audit with technical discovery where we can predict, pre-fill and foresee potential issues
- [x] Surface opportunities to clean up data or optimize

**Comment by saderagsdale** [comment]
@thehastingsp Can we close this one?

**Comment by thehastingsp** [comment]
yes
