### ISSUE TITLE
FE | Profile | Personal Information | Remove Feature Flag 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43482]
## Background

As of June 27, 2002 we have launched at 100%. Assuming everything continues to go smoothly we would like to remove this feature flag on/around July 7th. 

## Tasks
- [x] Remove the feature flag used to stage the Personal info Revisions roll-out

## Acceptance Criteria
- [ ] 

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
There is a lot of code tied up in this feature flag logic. I upped the estimate due to that, and have started this work, but will take a couple days.

**Comment by adamwhitlock1** [comment]
@SKasimow and @Samara-Strauss, We can validate this now. Basically everything should work as normal on the Profile with no real additional functionality specifically to check. 

I think a basic sanity check is really the best way to validate:

- Click on various parts of Profile to verify navigation
- Make sure updating preferred name and gender iden still work

**Comment by Samara-Strauss** [comment]
Validated in prod that I can update the personal info fields and everything else in the profile looks as it should. I didn't edit other fields outside of personal info, though, so let me know if you want that validated.
