### ISSUE TITLE
Use Confluence to build out the Map

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43520]
## Issue Description
Use Confluence to add info on teams and their services to the [Airtable](https://airtable.com/appbYNZ8PkZY7o9vs/tblXHp3UQAcjuotNa/viwNjGJl7am1QN2yD?blocks=hide).

Additional sources:
[VSP Org chart](https://docs.google.com/drawings/d/1N7tW2wTNqViooXE6ts8QujG36oyAg4mqu1zyeQ67DiY/edit?pli=1)
[Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster?src=mail&src.mail.action=view&src.mail.notification=com.atlassian.confluence.plugins.confluence-notifications-batch-plugin%3Abatching-notification&src.mail.recipient=622b5b63932f0f00716bdfd6&src.mail.timestamp=1655481712198)

## User Story
As a Platform team member, what tools or services does each team provide for what purpose?

---
## Tasks
- [x] Add additional info on services into Airtable

## Acceptance Criteria
- [x] Services for each team are documented in Airtable

**Comment by tayism** [comment]
@steel36 I don't have access to the [VSP Org Chart ](https://docs.google.com/drawings/d/1N7tW2wTNqViooXE6ts8QujG36oyAg4mqu1zyeQ67DiY/edit?pli=1)listed in the issue description -- can you pass that my way? Thanks!
