### ISSUE TITLE
Clarification on Mapping

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43530]
## Issue Description
Clarify users, use cases, problems this artifact might address. Ask how might we know we're collecting and presenting useful information?
---
## Tasks
- [x] Determine and list out existing problems this map would address

## Acceptance Criteria
- [x] Worksession to discuss perceived problems and aims

**Comment by twoangstroms** [comment]
Notes for session: https://vfs.atlassian.net/wiki/spaces/SDT/pages/2320334895/Mapping+Clarification+Meeting

Mural for workshopping: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1660596741123/1be9a695e25cf1cda7fd73336d62de3295bf4d62?sender=u4f7db1750f2355f805e60296
