### ISSUE TITLE
Create escalation path for POs

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#43545]
In talking w/ Mike there are some thoughts about adjusting the current approach in how issues, etc. are escalated to the POs. The thought is to lower their day to day engagement to allow them higher visibility and opportunity to work more from the vision and traditional PO stance.

The intent of this ticket is to work to flush out some approaches and guidance to allow this to happen and to present that to the POs for feedback.

**Use Case(s):**

- Fielding incoming DMs from VFS teams ( https://dsva.slack.com/archives/CBU0KDSB1/p1655931532348179 ). Currently the communication flow for specific items from a VFS team can get routed directly to a PO. Ideally, there would be an escalation flow identified and in place to get the team member support and would only get raised to a PO if the item was unable to be resolved through other escalation steps.
- POs are heavily embedded within Platform Teams and are actively included on many decisions/questions directly that should potentially be handled within the development team. The scenario here is the teams are provided requirements and priority that they then work to solution, etc. As they are going through that process and questions/unknowns get revealed, those items should be attempted to be addressed within the team prior to any escalation to the PO.

**Acceptance Criteria:**
- [x]  Define what is something that needs to be escalated
- [x]  Identify location for guidance to live
- [x]  Documented process and guidance that can be presented to POs for feedback and revision
- [x] Create any artifacts (boards, ticket template, labels) needed for this to exist
- [x] Document internal process for triaging them
- [x] Review w/ Platform Leadership
- [x] Announce it to all teams

Write up: https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2307620887/PO+Escalation+Process+Flow+Thoughts

**Comment by andreahewitt-odd** [comment]
I think it'd be awesome to have a GH ticket and special label and just have it flow to the leadership board

**Comment by andreahewitt-odd** [comment]
@td-usds @raywangoctova @mchelen Can you look at the examples listed in this doc to make sure we're not missing any examples?

**Comment by raywangoctova** [comment]
Looks good!

**Comment by andreahewitt-odd** [comment]
Moved to about the platform and created the ticket template. Also tested that it will show up on the leadership board. Last thing we need to do is define the triage process @little-oddball.

**Comment by little-oddball** [comment]
> @andreahewitt-odd Can you update the template to use Github YAML format? .cc @little-oddball for tech expertise

Updated to YAML format here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-po-escalations.yml

**Comment by little-oddball** [comment]
Looks to be accessible, etc.

**Comment by little-oddball** [comment]
Working on internal process [here](https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2307620887/PO+Escalation+Process+Flow+Thoughts)

**Comment by little-oddball** [comment]
Process has been created and put out for feedback
