### ISSUE TITLE
[Application Hosting and Deployment] Provide developers with tools to troubleshoot in EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#43549]
## Product Outline
[Application Hosting and Deployment using Container Orchestration (EKS)](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

## High-Level User Story/ies
As a platform crew developer, I need to be able to shell into an application hosted in EKS for the purposes of debugging and troubleshooting. 
As a platform crew developer, I need permission to manage Kube/ArgoCD resources for an application. 

## Hypothesis or Bet
If we make this change, we expect that Platform Crew developers can successfully connect to their applications running in EKS 
If we make this change, we expect that Platform Crew developers can troubleshoot their applications running in EKS 

### What must be true in order for you to consider this epic complete? 

- Platform Crew developers have the permissions needed to connect to their applications running in EKS 
- Platform Crew developers can connect to their applications in EKS 
- There is documentation for Platform Crew developers explaining how to connect to applications in EKS for the purposes of troubleshooting

**Comment by olivereri** [comment]
## 3 main difficulties:
1. How do I best deploy a solution to EKS?
1. What steps or process provides the quickest update/change to deploy/verify loop
1. What steps or process provides the quickest way to verify changes beyond what Argo CD provides in UI logs.

### 1. How do I best deploy a solution to EKS?

This one is probably out of scope for the epic.

Specifically for my use case with Sorry-Cypress I learned to effectively nest the chart I wanted to deploy. If I created a chart in the Application Manifest repository that called an upstream, publicly available chart repo, as a dependency would be easiest way. This pattern wasn't immediately clear to me. I initially tried to commit the entirety of the upstream's charts.

Not everything is going to have charts. Does it make sense of a custom application with no helm chart to create one? For example, would it make sense for the CMS team to create helm charts or just create the k8s resources explicitly in yaml files?

What are the deployment patterns for new applications that do and do not have helm charts?

### 2. Quickest Change to Deploy Loop?

For a new application deployed to EKS it can be a struggle to make tweaks large and small that put the app in a working state. Being able to quickly make a change, and verify it works as intended is tough with a PR approval/merge process.  I ended up using a bot account to approve my own PRs so I could make changes and merge them quickly. Even backing out bad changes.

I know now that one pattern is to turn off Auto-synchronize on Argo CD to prevent it from enforcing git ops, then editing templates within Argo CD or using kubectl directly on the console. That should provide quick feedback that a change will have the intended impact and is safe to put in a PR. After the PR is merged the app in Argo CD can be manually syncd.

### 3. Quickest Way to Verify Changes Beyond what Argo CD Provides in UI logs.

There are some ways an application can fail or not work as intended. The cause isn't visible in logs, or logs are only a pointer to what caused the problem but not the cause itself.  Being able to SSH into a pod/container provides instant feedback.  I had to dig around https://vfs.atlassian.net/wiki/spaces to find what I needed to config `Kubectl`. I eventually found [this](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594088/Create+and+deploy+a+Kubernetes+EKS+Cluster+on+the+Platform) which when paired with my AWS Account credentials got me into a pod.

I'm comfortable with just a terminal and shell to get what I needed done. The Kubernetes dashboard is no longer being maintained, but that has a bit more information than Argo CD. For example, the value of environment variables isn't stuffed in json output and is viewable even if it was a secret.

**Comment by jbritt1** [comment]
The work we are currently doing around GitHub team synchronization with ArgoCD AppProject permissions and policies _should_ solve this for us.

**Comment by jhouse-solvd** [comment]
There are a couple of issues in the review column that need to be tidied up. Then, this epic can likely be closed! :)

**Comment by jhouse-solvd** [comment]
Discussed this w/ @ph-One today. The definition of done has been met. This epic can be closed! :)
