### ISSUE TITLE
[Application Hosting and Deployment] Develop a process that allows developers to promote applications to higher environments (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#43550]
## Product Outline
[Application Hosting and Deployment using Container Orchestration (EKS)](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

## High-Level User Story/ies
As a platform crew developer, I need to be able to promote my application inside Kubernetes to a higher environment. 

## Hypothesis or Bet
If we create this process, then developers will be able to promote their applications to staging and prod easily. 

### What must be true in order for you to consider this epic complete? 

- There should be a process that Platform Crew teams can follow to promote an application to higher environments
- The promotion process should be documented in Confluence

**Comment by jsgarmon** [comment]
My basic thoughts are: once the application is working in dev, there are just a few things that need to happen to promote it to other environments.
1. copy manifest files from `dev` into a new environment folder, updating values and environment-specific specs.
2. add the new environment to the ArgoCD application with a PR like https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/48/files. Once merged, someone with admin perms will need to run `helm upgrade argocd . -n argocd` from `vsp-infra-argocd/chart`.
3. Create the actual application with a PR like https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/530/files.

**Comment by jhouse-solvd** [comment]
Documentation [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2324037840/Promote+an+application+to+a+higher+environment+in+EKS)

This issue can be closed.
