### ISSUE TITLE
Remove and Clean up Telephone Appointments Feature Flag

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43557]
## Tasks
- [ ] Remove and Clean up Telephone Appointments Feature Flag

**Comment by acrollet** [comment]
Validated on staging:
![Screen Shot 2022-12-09 at 08.52.02.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/aaaab4d3-d576-4b76-9589-233e27bc59da)

![Screen Shot 2022-12-09 at 08.52.17.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/e6311f0b-73dd-453f-812b-2b35d6d073e8)
