### ISSUE TITLE
Link to debt portal from redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#43552]
## Issue description
Request to link from redesigned VA.gov homepage to new combined debt portal which displays VHA (medical copays) and VBA (benefit debts) - (launching soon) 

[See design](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148519709/simulate/sitemap?mode=i)

**Comment by jilladams** [comment]
@davidconlon this is a very old ticket and the [new home page](https://staging.va.gov/new-home-page/) does not include a reference to the debt portal. Should this be a backlog item for next iteration, or closed?

**Comment by jilladams** [comment]
Welp - I just closed it accidentally, but: can reopen if this is a valid request and should be tracked for next rev.

**Comment by davidconlon** [comment]
It doesn't include it per-se, but based on our "Top Pages" rubric under "review your payment history" that provides a funnel into that activity. Unfortunately not all things can be linked directly from the homepage lest the homepage become just a link farm.

I don't think that there was an issue finding the debt portal surfaced in our research, but I'd be interested to know what the success metrics are for that teams' processing that would indicate a health metric being below expectations. At that point I'd be curious to know what research we would move forward to answer how best to create funnels to that activity - that would likely include folks from the MyVA profile side of the house too.
