### ISSUE TITLE
Get CDW access (look in Platform Support for link to form)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43567]
## Tasks
- Get CDW access
    - See instructions [here](https://dvagov.sharepoint.com/sites/OITBISL/cdw_support/SitePages/Obtaining-CDW-Access.aspx)
    - Enter these values for these fields
         - Employee Agency = OIT
         - Station Number = 101-Central Office
         - CDW SQL Datasets:
                 - Basic Read Access (CDW_Full)
                 - Priviledged Read patient access (CDW_SPatient)
                 - Staff Real SSN Access (CDW_SStaff)
        - Supervisor = Riley, Keith

**Comment by acrollet** [comment]
Submitted form 7/1

**Comment by randomsync** [comment]
submitted 7/1
