### ISSUE TITLE
Analytics Feature Request/Bug Report - Public Websites

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#43564]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - Role: UX Design, Team: Public Websites

- Is this a feature request or a bug?

  - [x] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature: I'd like to access data on usage of the sidebar nav that is present in benefits detail pages on va.gov. 
- Why the feature is needed: I am working to audit the UX of these sidebar navs. One piece of data that I would be interested in: how often are users double-clicking on a menu dropdown, causing the menu to open and then immediately close? If this is happening frequently, it indicates a hypothesis might be correct (that some users are not aware that these are dropdowns, and instead mistakenly see them as links). 

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?: This is unimportant. I just want a big enough time frame that I can be confident of findings.

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by fmccaf1** [comment]
Hi @jonathan-epstein13 here's a screenshot that I hope will help explain. The screenshot is taken of the entire main nav at va.gov. The benefits detail pages are all the links within each section listed on the left (I started numbering the sections in the screenshot: 1, 2, 3, 4, etc.).[ So an example of a benefits detail page is at this url.](https://www.va.gov/health-care/about-va-health-benefits/)

![Screen Shot 2022-07-07 at 4 38 50 PM](https://user-images.githubusercontent.com/106624475/177867515-1a31118e-0bb1-42da-bc56-3eebe7d4f37f.png)

Does that feel clear? 

This might be a really large project so if that's the case, it might not be worth the work. I'll add @wesrowe here to doublecheck me/add anything I might be missing.

**Comment by wesrowe** [comment]
That's clear to me. I don't know how analytics are implemented, but the URLs follow a pretty clean pattern. The Benefits Detail pages are all under 9 Benefit hubs (the "View all in health care" link in the above example). The url for any given Benefit Detail page is va.gov/`hub-name`/`page-name`.  Hence the example Florence gave above, `https://www.va.gov/health-care/about-va-health-benefits/`.
I'm not an engineer but I think they should all be rendered from a single front-end template.

**Comment by jonathan-epstein13** [comment]
@wesrowe @fmccaf1 I will be looking this over, and get back to you both if I have any questions. Thank you for the clarity!

**Comment by jonathan-epstein13** [comment]
Hello @wesrowe and @fmccaf1. I wanted to give you an update. We were able to see that the interactions are being tracked. 

![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/03892931-df9a-467b-be50-9d99b1ac1041)

Examples;
Clicking on VA Benefits and Healthcare drop down|![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/e39844f1-66e3-45d3-a287-37f47b5244e9) |![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/f60e0796-248b-49ea-af13-fac8a7640fc4) | Status | 🟢 Tracking Correctly |
Clicking on about VA Health benefits| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/1e55c107-bfd0-41fc-9399-d336c0f59f82) | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/70ccca30-cf5f-43cd-bca7-ea80876393ed)  | Status | 🟢 Tracking Correctly |


About the tracking users who open and then close the dropdown, this can only be obtained with big query to look at timestamps. Let me know if you have any questions or next steps. Feel free to come to office hours with any questions!

**Comment by wesrowe** [comment]
@jonathan-epstein13, can we not create a funnel that tracks successive accordion events? I suspect I'm missing context about what is/isn't possible in a funnel. (I've been research events this afternoon but haven't yet tried to build a funnel from them.)

**Comment by michelle-dooley** [comment]
@wesrowe - I think this should give you everything you need for this request so I am going to close this ticket but if you have any further questions please reach out through support or office hours and we will be happy to help!!
