### ISSUE TITLE
'Something went wrong' for systems with nested facilities

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4356]
When veteran picked one specific system of many, he ran into a 'something went wrong' error instead of being able to select a related facility. Ideally, he should've been able to pick a facility from that system, or seen a more relevant error message like 'no facilities support online scheduling in this system'.

In this case, the issue is that he was registered in the 589 system, which has child facilities that have their own child facilities. The front end doesn't handle this correctly.

Seems as though it's this sentry error: http://sentry.vfs.va.gov/vets-gov/website-production/issues/89236/events/b1cbc605ba0a477f8c55e6077fd2b0b7/

**Comment by jbalboni** [comment]
There are two potential fixes for this and they affect which facilities show up in which of the two questions on the facility page. One option is to show all the systems or facilities with child facilities in the first question. The other option is to show just root facilities in the first question and everything else in the second question. The legacy app is basically doing the former with the city/state question, I believe. The redesign intent was to do the latter, but I don’t think we understood this nuance fully.

@rtwell's preference is to show the root facilities in the facilities in the first question and all the child facilities in the second.

**Comment by jbalboni** [comment]
To do the above we need to:

1. Update the backend so that `parent_code` is not a required parameter for the `direct_scheduling_facilities` endpoint in `systems`.
2. Update the front end to filter out non-root systems in the data that comes back from `/facilities` and not send `parent_code` to `direct_scheduling_facilities`.
