### ISSUE TITLE
DevOps Guidelines - launch docs for customers to DIY their own devops as much as possible

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4357]
## Description: 
We want to create a way for teams to start working down the right path with their work and know they are with a DYI manual for DevOps. This will help cut down on teams going off and building something that we can't support and empower teams to feel more comfortable with their decisions. 

## Pain Points being addressed:
- More comfortable building towards success.
- More comfortable with the DevOps world.

## User Story
As a VFS team member, I want to know the right path to follow to be successful working with DevOps, so that I can be confident that my work will be a success.

## VSP OKRs 
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## KPIs
- Customer NPS VFS teams
- Reduction in volume of "non-human-needed" support requests month over month from VFS teams
- Confidence in BRD (increases)

**Comment by jhouse-solvd** [comment]
Please see #17349 for a more current iteration of this effort. 

Closing.
