### ISSUE TITLE
[Design] Payment info MVP: Update sketch files to match error state

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43571]
## Background
As a result of https://github.com/department-of-veterans-affairs/va.gov-team/issues/42911, we determined that there are some discrepancies between how we intended the payment info section to function, how it actually is functioning and the documentation of how it's supposed to function.

This is just a documentation update in our sketch files to show the error messages as they currently display on production.

## Tasks
- [x] Update sketch files to show the [error messages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md#error-states) displayed at the top of the My VA page 

## Acceptance Criteria
- [x] Sketch files are updated 

## Validation
- **Who can validate this ticket? (FE, BE, Design, PM)** any team member
- **How can this work be validated?** View the sketch files, see that the error messages are shown at the top of the My VA page instead of inline with the payment info section

**Comment by aagosto90** [comment]
Updated in [Sketch](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/q5PQD5/a/YGD28qM/r/Ajn34r) and on [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1648129585496/d22080eb307aac8bda5ba1153e013a386b7f1396?sender=uce014850ef6c5a8303e70396)

**Comment by ajakabcin** [comment]
Confirmed sketch files are updated - thanks @aagosto90 !
