### ISSUE TITLE
Write Postmortem Failure to Egress to Internet Incident

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4359]
Write Postmortem on the incident Network issues on 2019-12-16.
Postmortems

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2019-12-16-Failure_to_Egress_to_Internet_Incident.md

**Comment by ricetj** [comment]
Need to make Actions items from this.

**Comment by nathanhruby** [comment]
added tickets and action items to https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2019-12-16-Failure_to_Egress_to_Internet_Incident.md ... @wyattwalter  or @ricetj what else is needed here?  Can I remove DRAFT status and call it done, or do we need to have a meeting, etc..
