### ISSUE TITLE
My VA - Onsite Notifications - PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#43590]
\[**Product Managers**: Open this ticket **at least 2 Sprints (4 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [PTEMS-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by PTEMS-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outlines:
  - [My VA](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
  - [Onsite Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/README.md)
- [Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/mvp#project-outline-on-site-notifications-mvp)
- [QA Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/qa/onsite-notifications-qa-strategy.md)
- [Product/Feature Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30611)
- Product/Feature Copy deck(s): In Design prototypes
- Product/Feature Design prototypes: [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/ZObEKZx) and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/Gmgamo5)
 
## Product-team SMEs

Design/Research: Liz Lantz [@andaleliz], Angela Agosto [@aagosto90]
Content/IA: [n/a]
Front-end: Taylor Mitchell [@tmitchellgcio]
Back-end: Tom Harrison [@tpharrison]
QA: Tze-chiu Lei [@tlei123]

## Proposed use-cases and Staging test-accounts

**NOTE**: Staging test-users are **burnable** &mdash; dismissed Notifications are not restorable via browser.  Data-states for burnt test-users must be restored via collaboration with VANotify team.  Contact @ericasauv09 / @ajakabcin / @Samara-Strauss for restoration coordination guidance/assistance.
[Test-Cases/-Users doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-onsite-notification.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Added product-specific label (if any)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod environment].
- [ ] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

**Comment by tlei123** [comment]
@ajakabcin , fyi, I just started this ticket to keep track of info as test-runs approach.  Please update/finalize **Product/Feature copy deck(s)** [add a link or indicate "in design prototypes"], and let me know if anything in the main description's incorrect/outdated.

@aagosto90 , we do have specific mockup-links in our Test Cases, but would you mind validating the _general_ (All Pages) link above in the main description (**Product/Feature Design prototypes**) please?

Thanks much, all!  :)

**Comment by ajakabcin** [comment]
@tlei123 I updated the sketch files for you with desktop and mobile links and noted that copy could be found in the design prototype links. Thanks!

**Comment by ajakabcin** [comment]
@tlei123 apologies for the delay giving you the green light on this work. We're going to take a few more days to do some more internal end to end testing/kicking of the tires on this feature. We believe we'll be ready to go on QA beginning Wednesday 7/27. I'll circle back next week to hopefully give you the official green light on this request. Thank you!
cc @ericasauv09 @Samara-Strauss

**Comment by tlei123** [comment]
@pjhill , any word on TestRail fix for report generation?  Test-runs here are almost complete, so I thought I'd check in.

FYI, I started another report for [Debt-Resolution (Benefits-2) team's Combined Debt Portal](https://dsvavsp.testrail.io/index.php?/reports/overview/7) yesterday around 5pm MST, and it was still showing in-progress this morning around 10am MST.  Just checked again now and it's errored-out.

**Comment by pjhill** [comment]
> @pjhill , any word on TestRail fix for report generation? Test-runs here are almost complete, so I thought I'd check in.
> 
> FYI, I started another report for [Debt-Resolution (Benefits-2) team's Combined Debt Portal](https://dsvavsp.testrail.io/index.php?/reports/overview/7) yesterday around 5pm MST, and it was still showing in-progress this morning around 10am MST. Just checked again now and it's errored-out.

Hey Tze,

I hadn't gotten around to complaining again, but I just submitted another support request regarding slow report generation. I asked about the ability to prioritize report generation or just generally speed it up on our instance.

**Comment by tlei123** [comment]
FYI, @pjhill , Authd-Exp's [Onsite Notifications Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/348) just took about 30 min.  Still a lot longer than the usual 2-3 min.  So, I started another Debt-Res Combined Debt Portal Summary (Defects) report after discovering the above, but [that one's still been showing in-progress](https://dsvavsp.testrail.io/index.php?/reports/overview/7) since I started it about an hour ago.

I'll keep you posted.  Maybe the issue's Suite-/Report-specific. (?)

**Comment by tlei123** [comment]
@ajakabcin , QA test-runs completed.

1 defect logged: #45144 

TestRail links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3321)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=5373)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/352)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/354)

cc @ericasauv09 @Samara-Strauss

**Comment by tlei123** [comment]
FYI, @pjhill @ddzz , re. TR report-generation slowness, it's not as urgent/important as I had thought:
- It's **not** a system-wide issue, although it has generally been slower than v6 [avg 10-15 min vs v6 avg 3-5 min.].
- The really-slow & error-prone bug is **specific** to Debt-Res team's CDP Summary (Defects) report.  [See their Reports list.]

Feel free to ping me on Slack for further details.  If I have some free-time from hands-on test-planning, I'll see if I can find the exact root-cause.

**Comment by pjhill** [comment]
> 

I did create a new support ticket with Gurock. They indicated that it is a defect with TestRail that they're already tracking. They don't have an ETA for a fix at this time. I'll forward these details along to them. Thanks Tze!

**Comment by tlei123** [comment]
@ajakabcin , just so we don't bug VANotify too much/often, please let me know how/when we should handle _restoring_ Staging test-user data-states for re-testing [incl. other A11y & Platform's other practice-area testing for upcoming Staging Review].

Currently, the only burnt test-users are those with multiple-notifications.  All single-notification test-users have effectively been restored.

**Comment by ajakabcin** [comment]
Thanks @tlei123 we can probably follow up with them next week

**Comment by ajakabcin** [comment]
HI @tlei123 are we ok to close this ticket now? Thank you!

**Comment by tlei123** [comment]
Yes, Closing now.  :)
