### ISSUE TITLE
AWS access for Aaron Young

### ISSUE THREAD

**Issue by TW-Aaron** [department-of-veterans-affairs/va.gov-team#43591]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

John D Lewis

### Your Name

Aaron Young

### Your Email

aaron.young2@va.gov

### Your Team, Role, and Company

Virtual Agent (Chat Bot), Developer, Thoughtworks

### Product Manager (PM) name and email

Alina Murphey amurphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais Luciana.Morais@va.gov

### Desired AWS Access

 I need read/write access to dsva-vagov/va-virtual-agent space in AWS Parameter Store.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
@TW-Aaron is listed in VFS Team Roster.

**Comment by kylesoskin** [comment]
User: Aaron Young
COR: Cecilia Lee
VOR: Other
Approval needed: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
AWS Admin Role: no

**Comment by td-usds** [comment]
Reached out to PM and PO to find out who the VOR. I need information from the VOR that only the VOR can provide.
@TW-Aaron do you know who your VOR is? Could it be Mr. M Lovejoy?

**Comment by td-usds** [comment]
VOR (John Lewis) confirmed eQIP.
Requested read/write access to dsva-vagov/va-virtual-agent space in AWS Parameter Store approved

**Comment by jbritt1** [comment]
First-time login credentials passed to user via DSVA Slack DM at this time.
