### ISSUE TITLE
[UX] Decide on Metrics to Measure Success

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43607]
## User Story
As the Modernized Check-in team, we would like to be able to measure the success of this Epic so that we can determine if we need to make adjustments to the feature.

## Tasks
- [x] Decide on metrics to measure success for the Epic
- [ ] Determine how we will capture the metrics

**Comment by kristenmcconnell** [comment]
Should this be moved to in-progress?

**Comment by loripusey** [comment]
yes, moved

**Comment by benbrasso-agile6** [comment]
To confirm: probably won't touch this again until mid-engineering. Unless there's something else? Just wanted to make sure I'm not missing something.

**Comment by loripusey** [comment]
I think if we have reached a decision on where we are headed with metrics for this epic, we can close this ticket. There is another ticket to create the metrics.
