### ISSUE TITLE
GIDS: Add Partial Match Functionality to Crosswalk Issues Table

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4362]
As an EDU Team Member, I need the ability the ability to see a potential list of IPEDSHD entries that match the WEAMS facility code to reduce the manual effort involved in updating the crosswalk.

## Assumptions:
1. The fuzzy match should leverage database capabilities.

## Acceptance Criteria:
1. There is a "Find" action available in the Crosswalk Issues table.
2. When the users clicks "Find", the following results are returned:
     a. WEAMS "institution name" entries that fuzzy match the IPEDS HD "instnm" entries.
     b. WEAMS "address" (1, 2, 3, city, state, zip) entries that fuzzy match the IPEDS HD "address" (addr, city, stateabbr, zip) entries.
     c. WEAMS "physical address" (1, 2, 3, city, state, zip) entries that fuzzy match the IPEDS HD "address" (addr, city, stateabbr, zip) entries.
3. The following details are displayed:
    - Weams Institution Name
    -  Weams Full Address
    - Weams Full Physical Address
    - IPEDS Institution Name
    - IPED Full Address
    - IPEDS OPEID
    - IPEDS IPED ID
4. The user can:
     a. Select an entry to match with.
     b. Cancel without choosing a matching entry.
5. If the user selects an entry to match:
     a. If a crosswalk entry exists, the entry is updated with the IPEDS data.
     b. If a crosswalk entry does not exist, an entry is created with the IPEDS data.
     c. The row is removed from the "Ipeds issues" table
6. If the user does not confirm the association, no action is taken.

## Supporting Artifacts:
1. The WEAMS and IPEDSHD files from GIDS
2. Example facilities that could identify matches:
     - ALABAMA STATE UNIVERSITY
     - ALABAMA A & M UNIVERSITY

**Comment by hughes-dustin** [comment]
branch: bah-4362
pr: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/567

**Comment by sonntag-adam** [comment]
AC 1. 
![Screen Shot 2020-02-07 at 9.02.31 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ff9fb815-f87a-4669-a0db-7f22349652d7)
##
AC 2 & 3
![Screen Shot 2020-02-07 at 9.14.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1ee3ef8e-f8f1-45c7-8baa-579b81f4d197)
##
AC 4
![Screen Shot 2020-02-07 at 10.03.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/af062633-0b12-4e0a-aae2-5f929d56fb18)
##
AC 5 The row is removed from the "Ipeds issues" table
![Screen Shot 2020-02-07 at 10.06.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/28d08abf-200a-4437-829d-b83b43d888df)
Updated in crosswalk
![Screen Shot 2020-02-07 at 11.02.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8f05e950-27f1-403f-a1a4-af9c3a2f4b84)
##
AC 6 screenshot not applicable
##
Custom ipedhd entry with partial match search, shown for first result
![Screen Shot 2020-02-07 at 10.58.56 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ca45cd7d-cd26-4950-a9df-66a67f1a6816)

**Comment by sonntag-adam** [comment]
In staging, closing story. Testing passes QA
