### ISSUE TITLE
Update Staging Tool so that we can pass a review environment URL parameter and generate appropriate links

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43639]
## Tasks
- [ ] Update Staging Tool so that we can pass a review environment URL parameter to the tool so that it will generate the proper Pre-Check-in and Check-in links

**Comment by acrollet** [comment]
Leaving this in validate until we've tested it on a ticket or two.

**Comment by acrollet** [comment]
@zach-park  has used this functionality successfully, closing this out.
