### ISSUE TITLE
[content] draft Supplemental Claims content

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#43638]
## User Story

As a user I would like to have a clear understanding of what is needed to file a successful Supplemental Claim

## Expected Behavior

Content draft for Supplemental Claim form with omni-channel experience in mind, specifically communications, the claim status, decision letter and mobile app experiences. 

## Acceptance Criteria

- [x] Draft of content to review with platform content team
- [x] Pattern capture of channels that will/could be part of an omni-channel Supplemental Claim journey

**Comment by thehastingsp** [comment]
@Mottie draft of content is here https://docs.google.com/document/d/1lzNEOafHv0s-MrehlvtbMNZYlBPUUE4swn2IglLElfA/edit?usp=sharing

**Comment by thehastingsp** [comment]
@Mottie @scottymeyers @rocio-desantiago FYI I'm continuing the [draft of the Supplemental Claims content here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/%5Bdraft%5Dcontent.md)

**Comment by saderagsdale** [comment]
Keeping this open until after the design intent meeting on 7/28.

**Comment by thehastingsp** [comment]
Closing this initial ticket in favor of breaking of the form into specific areas of content review.  

• https://github.com/department-of-veterans-affairs/va.gov-team/issues/44411
• https://github.com/department-of-veterans-affairs/va.gov-team/issues/44417
