### ISSUE TITLE
[design] draft supplemental claims design

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#43635]
## User Story

As a user I would like to be able to complete a Supplemental Claim form on VA.gov

## Expected Behavior

Happy path design layout for completing a Supplemental Claim on VA.gov

## Acceptance Criteria

- [x] Sketch files with initial happy path layout for Supplemental Claims
- [x] Identified opportunities for optimization 
- [x] Identified use cases

**Comment by thehastingsp** [comment]
Design is in progress in the [viewable sketch file here](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89). @scottymeyers @rocio-desantiago @Mottie @michelpmcdonald @saderagsdale

**Comment by saderagsdale** [comment]
Keeping this open until after the design intent meeting on 7/28.

**Comment by thehastingsp** [comment]
closing this in favor of smaller tickets [housed inside this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45066).
