### ISSUE TITLE
[UX][Research] Create Metrics to Measure Success for an Epic

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43630]
## Tasks
- [x] Create metrics to measure and evaluate success for the Epic
- [x] Make metrics available to the team

**Comment by benbrasso-agile6** [comment]
What to measure:

What we can control:

Total claim submissions (i.e., completed check-ins with "Yes" to travel pay)
% of total completed check-ins with claim
% of times a claim was started, user backed out and said "No," and check-in was completed
% of times a claim was started and user did NOT complete check-in
% PCI utilization before/after comparison to when travel reimbursement was merged

** What we may not be able to control:**

% of claims that are incomplete or not accepted out of total PCI-submitted claims
% of claims that are incomplete or not accepted out of total PCI-submitted claims compared to % of claims that are incomplete or not accepted out of non-PCI-submitted claims
