### ISSUE TITLE
[Story] CT Rating System Calculation Formula Update

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#43644]
## Issue Description
CT Rating System Calculation Formula for four star rating system. 
---
 

## Acceptance Criteria
Update new calculation formula to reflect the correct ratings for the new four star standard. 

- Calculation Formula - **AR = 1a+2b+3c+4d/(R)**

**Comment by MitchLivingstone** [comment]
@PJart Please see Mock data to test calculation formula. 

[https://app.zenhub.com/files/133843125/dc27d1d3-7465-4bce-98ea-cfe84d183340/download](https://app.zenhub.com/files/133843125/dc27d1d3-7465-4bce-98ea-cfe84d183340/downloadt)

**Comment by MitchLivingstone** [comment]
Met with Jessy and his team to discuss the data aggregation for each question. It was determined they will work on an extra column to add the aggregated data. @PJart provided the grouping data 1 - 4 above in an email for clarity. Jessy will follow-up when completed to Patrick to test the new CSV file.

**Comment by MitchLivingstone** [comment]
Waiting for the finial spreadsheet from Juan Jacksons team.

**Comment by MitchLivingstone** [comment]
@PJart New data added. [https://app.zenhub.com/files/133843125/4e7f7e31-e3ca-4025-8f31-eef59ec65c3f/download](https://app.zenhub.com/files/133843125/4e7f7e31-e3ca-4025-8f31-eef59ec65c3f/download)

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3620&group_by=cases:section_id&group_order=asc
Test case: [CT Rating System Calculation Formula Update.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9656867/CT.Rating.System.Calculation.Formula.Update.xlsx)

**Comment by MitchLivingstone** [comment]
Closed and completed. In staging. 09/26/2022
