### ISSUE TITLE
[SPIKE] Research APIs Available for BT

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43657]
## Background

In order to integrate with BTSSS, we'll need to know what APIs are available and how to authenticate to them

## Questions to answer

- What documentation is available?
- What authentication is required?
  - will we be allowed to submit claims using only LoROTA auth?
- What system should we use to connect? (directly from vets-api? via CHIP?)

## Acceptance Criteria

- [ ] Document all findings and link from this ticket
- [ ] Create follow-on issues for research that cannot be completed within this spike

**Comment by randomsync** [comment]
Reviewed the MVP Design : #42935

I don't have access to max.gov to review API documentation. 

Based on reviewing the 'BTSSS Claim Ingest Service Technical Specification' document that Stephen shared with me, it would be great to know:
- the request and response payload format (or OpenAPI spec if that's available)
- authentication details (how our APIs can authenticate and submit claim requests)
- what TCM and VEIS are
- what test environment(s) they have, and if we can get credentials/test data to submit requests to that env

Assumptions:
- submitting requests to their API doesn't require Veteran to be fully auth'ed
- the data payload we currently have in LoROTA has all the information needed to submit the claim request

Some/all of this information might be available in the shared repository (max.gov) that I don't have access to.

**Comment by loripusey** [comment]
@randomsync are you going to reach out to Patrick to see about passing these questions along to the BTSSS folks (seeing as how Stephen is out)?

**Comment by kanchanasuriya** [comment]
Adding a couple of more to the above technical question list,
1.  Is there any claim limit for using ClaimIngestService?
2.  What are the veteran eligibility criteria for calling ClaimIngestService?

From a product perspective, are we looking for notifying staff of the travel reimbursement claims submitted via check-in workflow?

**Comment by batemapf** [comment]
email sent!

**Comment by sarahknoppA6** [comment]
@batemapf just following up on this one- i thought i saw in slack that you did send a few emails about this, but was not fully able to follow the thread or confirm where we are. Could you provide an update here too for clarity? cc @loripusey

**Comment by randomsync** [comment]
We had a discussion with VEIS team (Jordan Baker) and BTSSS team (Michelle Ortiz). VEIS team provides the integration layer that supports authn/authz functionality. They mentioned that they'll provide info on how to get the credentials for vets-api to make calls to BTSSS endpoints.

Next steps: create auth credentials using their portal for vets-api to call the endpoints, and explore the request entities and endpoints available.

Closing this ticket, will be creating further tickets to explore auth and other endpoints.
