### ISSUE TITLE
Channel name change from #cms-team to #sitewide-cms-team

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#43651]
# Description
In DSVA Slack, channel name change from #cms-team to #sitewide-cms-team

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@cmaeng that channel name is already taken
