### ISSUE TITLE
Syntax error in recordEvent function blocking Medallia feedback button

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#43664]
## What happened?

There appears to be a missing comma in the recordEvent function in the covid-status drupal template: 

![Screen Shot 2022-06-29 at 2 01 09 PM](https://user-images.githubusercontent.com/11021491/176505119-8b803135-4bd2-4dbf-aef6-a41729445b7e.png)

https://github.com/department-of-veterans-affairs/content-build/blob/d793ca468d3ad6e16946e28ba5c4259b56b43c08/src/site/includes/covid-status.drupal.liquid#L9

At build, all recordEvents are bundled together along with the function that fires the Medallia Feedback modal. Since there is a syntax error in the recordEvent above, it blocks the Medallia feedback modal from firing.

## Specs:
n/a

## Steps to Reproduce
- URL: https://www.va.gov/greater-los-angeles-health-care/locations/santa-maria-va-clinic/
(all pages that use the `covid-status.drupal.liquid` template

## Desired behavior
clear syntax error in recordEvent

## Acceptance Criteria
- [ ] syntax error is clear

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ethanteague** [comment]
@maxx1128 - pinging you for awareness / assigned to you.
