### ISSUE TITLE
Document Process for Updating Product Guides

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43673]
## Tasks
- Develop a process for updating release artifacts
- Document process in GitHub
- Present to UX & product

**Comment by benbrasso-agile6** [comment]
https://docs.google.com/document/d/1EQssDDb55Am-3Y21iTqV9qDpZQiJBmOa1jT3GqSDeK8/edit

**Comment by loripusey** [comment]
@benbrasso-agile6 are we ready to close this one?

**Comment by benbrasso-agile6** [comment]
No. Work in progress.

**Comment by loripusey** [comment]
@benbrasso-agile6 Can we close this and just move it onto your to-do list? It's been open for 5 sprints

**Comment by benbrasso-agile6** [comment]
I have not made additional progress on it since the last time we spoke. I think, for me to get it done, we should make room for it. I think me just trying to fit it in is not working. 

Or, we push it to the backlog.

**Comment by kellysmith1008** [comment]
Not sure who needs to validate this, but tagging you, @loripusey and @benbrasso-agile6 since it says to inform UX and product :) 
[The guide has been updated](https://docs.google.com/document/d/1EQssDDb55Am-3Y21iTqV9qDpZQiJBmOa1jT3GqSDeK8/edit) - it can be closed after validating or I can make any changes if needed and then close. Thanks!

**Comment by loripusey** [comment]
Looks great! Very thorough! Thanks @kellysmith1008 ; are we going to upload this to our GitHub area somewhere?

**Comment by kellysmith1008** [comment]
Thanks @loripusey! Yes, I will add it as a file to the [product guide page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product/product-guides)? Or would you rather I add it under the **Product guides** heading on our [product page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product)?

**Comment by loripusey** [comment]
I think adding it to the product-guides folder makes sense and then adding a link to it on the Product Outline so people can find it.
