### ISSUE TITLE
Certificate of Eligibility Status | Document Download Links

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#43709]
## Value Statement
**_As a_** Veteran
**_I want to_** download a copy of my Certificate of Eligibility documents
**_So that_** I can share it with my loan service provider.

## Background Context
The scope of this ticket covers hooking up the Document Download Link in the COE Status app. The document Download Link is being hidden for the moment because `vets-api` doesn't currently return a url as part of the payload, which means the link currently doesn't point to anything.

## Acceptance Criteria
- Users can download a copy of their Certificate of Eligibility using the CoE status app.

## Tech Tasks
- [x] create the new endpoint to retrieve the document
- [x] update UI to utilize that new endpoint

## Designs and Build Notes
- @jsokohl Can you add a link to the design?

## Open questions
- Any accessibility criteria needed?

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@jacobworrell Sharing a heads up that Scott added this to the backlog, and labeled it to your squad. I would like to get this work done in the next sprint if possible. I will review this with Scott and pull you in for refinement as needed.

**Comment by scottymeyers** [comment]
Hey @jacobworrell! So this work would require both front and back end changes, those being:

1. Create the actual endpoint to get the PDF, we'll need to create a new `vets-api` endpoint to interact w/ LGY's API.
2. Add the links to download on the Status page. Uou can see an example of how this should look in the prototype here: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140741546/simulate/sitemap

@jerekshoe had initially brought this issue to my attention around the 25th of May. Since then we've had discussions with Kelli Deinarowicz about the remaining form issues, and have since addressed them all. So it looks like this is the last remaining issue.

I understand this is a bit of a hot potato, but it could be a good opportunity for Sam to take a stab at a back end ticket, since, from my understanding, he has some interest in.

Otherwise, let's have a conversation next week w/ @saderagsdale and figure out logistics about Squad 2 owning this ticket.

**Comment by scottymeyers** [comment]
@jacobworrell, squad 2 is taking this one back. Hope you don't mind!

**Comment by scottymeyers** [comment]
Waiting on a review for the UI bit, and then this is done!

**Comment by saderagsdale** [comment]
@scottymeyers is someone actively helping with the UI part or does that need to be assigned?
