### ISSUE TITLE
Datadog dashboard for staging Keycloak

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#43717]
Because dev versions of platform tools will be integrated in Keycloak staging, we need a way to monitor Keycloak staging in order to provide debugging support for our clients.

Done when: 
- [ ] Staging Keycloak monitors & dashboard setup in Datadog

**Comment by calquisola** [comment]
[PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/622) created for staging metrics.

**Comment by calquisola** [comment]
PR was approved by infra team. Dashboard for staging is created. 
Closing ticket.
