### ISSUE TITLE
Design | Profile | Personal Info Revisions | Update Sketch

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43713]
## Description

The Personal Information page's FAQ "How to fix an error on your name or date of birth" includes a phone number that should be shown as clickable. 

## Tasks
- [x] Update sketch files to show the number in the FAQ clickable.

## Acceptance Criteria
- [x] Update sketch files to show the number in the FAQ clickable.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
This is complete 👍 Updated Sketch files: [Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/OmjMy8G) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/OmjMwxm)
