### ISSUE TITLE
AWS Request process highlights and automation opportunities

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#43712]
In order to discover what opportunities there are for automation, we need to describe the process in brief, and highlight what opportunities there are for automation.

Done when:
- [ ] Document or diagram created in Confluence describing the AWS Access Request Process
- [ ] Automation opportunities highlighted in docs

**Comment by girldadmk** [comment]
@kylesoskin can you link Confluence docs and move to review?

**Comment by girldadmk** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2251358357/SOCKS+and+AWS+Access+Request+Automation

Move to complete.
