### ISSUE TITLE
Migrate clients to Keycloak staging via Terraform

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#43718]
Now that we have a Keycloak staging environment, we should move our registered clients from Dev Keycloak to Staging Keycloak. This allows us to experiment with dev (custom extensions, Keycloak plugins, Terraform modules) while keeping our integrations alive.

Done when:
- [x] all clients from the Login.gov realm in Dev Keycloak are present and tested in Staging Keycloak.

- [x] Terraform process in staging

**Comment by iriteshp** [comment]
clients migrated to the keycloak staging environment with Terraform.

https://keycloak-staging.vfs.va.gov/auth/admin/master/console/#/realms/login_gov_tf/clients
