### ISSUE TITLE
AWS access for Ritesh Patel (devops priviliges)

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#43710]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Sabrina Ammon

### Your Name

Ritesh Patel

### Your Email

ritesh.patel@adhocteam.us

### Your Team, Role, and Company

PST Access Management Team, DevOps, Ad Hoc

### Product Manager (PM) name and email

Matt King

### Product Owner (PO) name and email

Thomas Delrue

### Desired AWS Access

Vendor Onboarding representative: Sabrina Ammon [Sabrina.Ammon@libertyits.com](mailto:Sabrina.Ammon@libertyits.com) | [Sabrina.Ammon@va.gov](mailto:Sabrina.Ammon@va.gov)

As a devops resource on our team Ritesh Patel (@iriteshp) need devops access. 

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
bc there is not currently a group for PST DevOps, this ticket may require a bit more work (creating policies and attaching to a new group)

**Comment by kylesoskin** [comment]
@iriteshp is in the Platform Roster.

**Comment by kylesoskin** [comment]
User: Ritesh Patel
COR: Cecila Lee
VOR:  Liberty IT - Michael G. Lovejoy
Approval needed: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
AWS Admin Role: no

**Comment by td-usds** [comment]
Who is the access for? The issue's title says Ritesh Patel, the issue's body says Kevin Duensing and further data is inconclusive

**Comment by td-usds** [comment]
The validation of https://github.com/department-of-veterans-affairs/va.gov-team/issues/41075 carries forward for this one; access approved for Ritesh Patel

**Comment by jbritt1** [comment]
PST-AMT DevOps role granted as requested/approved. For a reference of what permissions this grants exactly we use [this template](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/base_devops_policy.tftpl) and this [tag requirement](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_policies.tf#L2665-L2675) so you will want to make sure any resources you create have the appropriate tags in order to continue having the ability to make changes to them.
