### ISSUE TITLE
SOCKS proxy request process highlights and automation opportunities

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#43711]
In order to discover what opportunities there are for automation, we need to describe the process in brief, and highlight what opportunities there are for automation.

Done when:
- [x] Document or diagram created in Confluence describing the SOCKS Access Request Process
- [x] Automation opportunities highlighted in docs

**Comment by girldadmk** [comment]
@kylesoskin can you link the Confluence page to this ticket?

**Comment by girldadmk** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2251358357/SOCKS+and+AWS+Access+Request+Automation

Moving to complete.
