### ISSUE TITLE
Design Intent - Design Feedback - [VAOS, VA Online Scheduling, Appointment List Feature]

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#43738]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Love seeing all the previous research and showing what you have today vs what you are changing.
- Typically at design intent we like to see user flows and lo fi wireframes and provide limited UI feedback
- The list/table view is very hard to scan. The eye seems to be drawn to the canceled tag and then icons. Try considering what content is most important on the list item and prioritize that and remove any necessary noise like tags. You could also try using less columns, that may make the content more clear 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Remove the “< back” and replace with breadcrumbs. Sync with online check in and Meg Peters who is working on messages for left nav. 
- Remove the background only alert styles, instead if you want to draw attention to something try bold text. Fixing left nav issues will also probably fix the alert issues.
- Use [standardized iconography](https://design.va.gov/foundation/icons) for icons we have and font awesome solid versions if not on the list. DSC is currently auditing and working to update our icon list.
- “Start Scheduling” primary action link text must be sentence case instead of title case.
- Abbreviated days should end with a “.” (i.e Mon., Tue., Wed.) https://d.pr/i/EoOzeo 
- Tag - change font weight from 700 to 400 and remove the .5px letter-spacing.
- Additional info component changes font size when clicked (20px to 16px).  https://d.pr/i/TSzFFF It should be 16px. Update the left blue border color and position and the chevron color to match [current component style](https://design.va.gov/components/additional-info).
- Make sure your buttons are consistent between mobile and desktop (Reschedule appointment/Cancel appointment)

**Should:**

- Use the [card style](https://design.va.gov/components/card) in the appt list/table, not the appt detail page. Knowing that the card style tested well, was mobile friendly and easy to scan you should try to explore using that instead of the list/table. It’s ok to use the card style with no background but remove the border radius and file experimental request. Remove the icon or put it with the title. If you are going to use a background color on the icon use the light blue like profile.
- Since “pending” is so confusing, consider putting it in the list of upcoming appointments and have a status of “requested” or “confirmed”. Similar vocabulary may help the user understand and all of these things are appointments, they are just different statuses. 
- Remove the tags

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
Thanks Allison! Just a couple of clarifying q's to help us work through these items:

> Remove the background only alert styles, instead if you want to draw attention to something try bold text. 

Do you mean the status call outs on the [details pages](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=523%3A36824)? 

---

> Fixing left nav issues will also probably fix the alert issues.

Which alert issues? I didn't see any in the list (or misread).

---

> Tag - change font weight from 700 to 400 and remove the .5px letter-spacing.
and,
> Remove the tags

I'm reading these two recs as "don't display canceled appts, but if you have to, make the status indicator less visually strong" - is that right?

Related note: 

> The eye seems to be drawn to the canceled tag and then icons. Try considering what content is most important on the list item and prioritize that and remove any necessary noise like tags.

In the concept test, we identified canceled and then modality as the most important information that we can consistently provide ([report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-MHV%2BVAOS-appts-list-discovery/report-MHV%2BVAOS-appts-list-discovery.md), [presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-MHV%2BVAOS-appts-list-discovery/Research%20Presentation%20-%20MHV%2BVAOS%20Appointments%20List%20Discovery.pdf)). If we had Type of Care for all appointments, that would take the top spot, hierarchically, just below canceled and time info. We'll continue to dig into this when we take the updated designs into usability research.

---

**Comment by seanasewell** [comment]
@outerpress 

> Do you mean the status call outs on the [details pages](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=523%3A36824)?

Yes, since they are calling out a status, alert styling is not necessary. They look to similar to our [alerts](https://design.va.gov/components/alert) which might confuse users. 

> Which alert issues? I didn't see any in the list (or misread).

See comment above

> I'm reading these two recs as "don't display canceled appts, but if you have to, make the status indicator less visually strong" - is that right?

Correct. Displaying tags rec was in thoughts/considerations. If your testing indicates that the tags are helpful to users, just make sure that they are designed in parallel to what is in [storybook](https://design.va.gov/storybook/?path=/docs/components-tag--default-story). 

> In the concept test, we identified canceled and then modality as the most important information that we can consistently provide ([report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-MHV%2BVAOS-appts-list-discovery/report-MHV%2BVAOS-appts-list-discovery.md), [presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-MHV%2BVAOS-appts-list-discovery/Research%20Presentation%20-%20MHV%2BVAOS%20Appointments%20List%20Discovery.pdf)). If we had Type of Care for all appointments, that would take the top spot, hierarchically, just below canceled and time info. We'll continue to dig into this when we take the updated designs into usability research.

Sounds good!

cc @allison0034

**Comment by outerpress** [comment]
Thanks Allison and Sean! Sean, all that makes sense. We'll check in as we work through the recommendations.

**Comment by ldelacosta** [comment]
No further action needed. Closing out the ticket.
