### ISSUE TITLE
[EKS] R/W access for Rachal Cassity

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#43741]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Rachal Cassity

### Your Email

rachal.cassity@oddball.io

### Your Team, Role, and Company

VSP - Console Services, Backend Engineer, Oddball

### Product Manager (PM) name and email

Nathan Peterson, Nate.Peterson@adhoc.team

### Product Owner (PO) name and email

Thomas Delrue, Thomas.Delrue@omb.eop.gov

### Desired AWS Access

I need access to read-write EKS Clusters. Platform Console Services team will be working on the vets-api staging EKS environment.  I believe the Platform Console Services AWS group name is vsp-backend-tools. The entire @department-of-veterans-affairs/platform-console-services should also have access to EKS clusters.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
@RachalCassity is listed in the Platform Roster.

**Comment by kylesoskin** [comment]
User: Rachal Cassity
COR: Vilay Senthep
VOR: Oddball - Amber Malcolm
Approval needed: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
AWS Admin Role: no

**Comment by td-usds** [comment]
Requested access for Rachal approved

**Comment by jbritt1** [comment]
@td-usds, Rachal is also part of the platform-console services team and will likely need SSM access to prod vets-api at times for debugging while oncall. I would like to go ahead and deliver this permission set to her if I could get you to okay it as time allows please

**Comment by jbritt1** [comment]
Oh wait, nevermind... she already has that permission set added to her user.

**Comment by jbritt1** [comment]
@RachalCassity, is this request specifically for EKS access? Your AWS user is already granted and fine, correct? We have not yet fully worked out the kinks for providing direct EKS cluster access, but have a route and the initiative on our plate. However, it is not yet ready to roll out. We may just need to close this one if this is specifically about EKS access.

**Comment by jbritt1** [comment]
Rachal's AWS account matches that of her teammates. Direct EKS access is not yet available to the platform, but being worked out currently in the linked initiatives. Closing.
