### ISSUE TITLE
VAOS Staging: User is not able to Navigate back to Requested queue after cancelling a CC request

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#43756]
## What happened?
VAOS UI is displaying an error when user is navigating back to Requested queue after cancelling a CC request in VAOS. I have tried using the back arrow, click on the "VA online Scheduling" breadcrumb and selecting the Requested queue and we are seeing the same results.

Workaround:  User can successfully access the Request/ Requested queue by logging out of the application and coming back in and starts a new session.

## Specs:
Staging: DAYTSHR, Dayton
grethel.g.petryniec@id.me, Password1234!

## Steps to Reproduce
Login to VAOS as a VAOS service test user (Ex- grethel.g.petryniec@id.me)
Click on "Start Scheduling"
Select any type of care supported by Community Care (ex:- Primary care, Food and Nutrition, Optometry, Podiatry, Audiology)
Select a preferred provider
Enter a preferred date
Continue without entering any additional comments
Fill in all the required data and create a request
Now user clicks on "Cancel Request" button
The request is cancelled and UI displays "You Cancelled the request. If you still need an appointment, call us or request new appointment online". Please note the "CANCELLED_BY_PATIENT" field is also populated.
Now the User clicks on back arrow (or) click on the "VA online Scheduling" breadcrumb and selecting the Requested queue
Expected Results: System should show the CC request as cancel the requested queue

Actual Results: System is displaying an error message on the UI " We're sorry. We've run into a problem. Something went wrong on our end."

Note: There were no error in Devtolls, but see an error on console - 
instrument.js:109 TypeError: Cannot read properties of null (reading 'replace')
    at Kl (RequestListItem.jsx:69:44)
    at si (react-dom.production.min.js:157:137)
    at Zs (react-dom.production.min.js:267:460)
    at Pu (react-dom.production.min.js:250:347)
    at xu (react-dom.production.min.js:250:278)
    at Cu (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
    at Ko (react-dom.production.min.js:122:428)
    at mu (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at t.v.setState (react.production.min.js:12:369)
    at react-router.js:60:17
    at r (history.js:155:24)
    at history.js:173:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (history.js:172:15)
    at k (history.js:288:23)
    at history.js:369:11
    at Object.confirmTransitionTo (history.js:145:7)
    at Object.push (history.js:350:23)
    at t.<anonymous> (index.jsx:74:15)
    at t.e.addEventListener.r.<computed> (attachProps.js:2:1495)
    at t.r (helpers.js:73:23)
    at ae (index-a9d1b79d.js:1:15179)
    at Object.emit (index-a9d1b79d.js:1:15048)
    at e.handleChange (va-select.entry.js:1:3678)
    at HTMLSelectElement.onChange (va-select.entry.js:1:4509)
    at HTMLSelectElement.r (helpers.js:73:23)
(anonymous) @ instrument.js:109
i @ error.js:67
value @ ErrorBoundary.jsx:19
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
ha @ react-dom.production.min.js:131
ys @ react-dom.production.min.js:220
Nu @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
Tu @ react-dom.production.min.js:252
bu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Ko @ react-dom.production.min.js:122
mu @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
v.setState @ react.production.min.js:12
(anonymous) @ react-router.js:60
r @ history.js:155
(anonymous) @ history.js:173
notifyListeners @ history.js:172
k @ history.js:288
(anonymous) @ history.js:369
confirmTransitionTo @ history.js:145
push @ history.js:350
(anonymous) @ index.jsx:74
e.addEventListener.r.<computed> @ attachProps.js:2
r @ helpers.js:73
ae @ index-a9d1b79d.js:1
emit @ index-a9d1b79d.js:1
e.handleChange @ va-select.entry.js:1
onChange @ va-select.entry.js:1
r @ helpers.js:73
_handleMouseUp @ unknown
Show 6 more frames

![image](https://user-images.githubusercontent.com/69315717/176921160-9f4ff4ea-a5c1-48da-bd9e-f4db88bfa18c.png)
![image](https://user-images.githubusercontent.com/69315717/176921406-a02fbbac-6480-4568-afa1-aea9ca235006.png)

**Comment by aarathi-poldass** [comment]
@ldelacosta - This ticket cannot be tested right now due [VAOSR-3947](https://issues.mobilehealth.va.gov/browse/VAOSR-3947).  According to Marcy's comments on VAOSR-3947 - We have seen similar kind of issue before and that was something fixed by AJ.

**Comment by aarathi-poldass** [comment]
Validated the issue and it's still consistent

**Comment by aarathi-poldass** [comment]
As per the discussion with Grace, Marcy and Judy and have decided that this is not going to be a blocker for going to production but will need to get in the queue to get fixed as soon as we are in production.

**Comment by ldelacosta** [comment]
Added to the backlog. Not a priority before vaos-v2 launch. We will review the work once we have a launch date.

**Comment by aarathi-poldass** [comment]
As per Marcy suggestion and all the recent fixes and deployments in staging related to CC and cancellation, SQA re-tested this to validate if those fixes could have inadvertently fixed this issue and verified that the issue still exists.

**Comment by ldelacosta** [comment]
Thanks @aarathi-poldass. We have put this ticket in the Ready queue. A developer will look into this when they have the bandwidth. Thanks!

**Comment by ldelacosta** [comment]
@jenniemc - This work will be behind the vaos-v2-next feature toggle. Here is the ticket #44559 for the feature toggle work.

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this was issue given priority to be Low

**Comment by ldelacosta** [comment]
@aarathi-poldass - This is ready to be tested. Please let us know if you have any issues. Thanks!

**Comment by aarathi-poldass** [comment]
Re-tested the defect and Passed validation. User is able to navigate back to the previous page after cancelling the CC request using the back arrow or breadcrumbs . @ldelacosta please close the ticket. Thank you!

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
