### ISSUE TITLE
Migrate Vets API VSP graphs over to Datadog

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#43761]
Blocked by infrastructure [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42065)

Status: Jul 19th. Still waiting on infra.

- [x] VSP - [Breakers](https://grafana.vfs.va.gov/d/000000022/breakers?orgId=1)
- [x] VSP Utility - [Redis](https://grafana.vfs.va.gov/d/000000046/redis?orgId=1)
- [x] VSP Utility - [Application Request Break](https://grafana.vfs.va.gov/d/000000026/application-request-breakdown?orgId=1)
- [x] VSP - [External Service Performance Indicators](https://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1)
- [x] VSP Utility - [External Service Status](https://grafana.vfs.va.gov/d/000000025/external-service-status?orgId=1)
- [ ] VSP Utility - [Job Queue](https://grafana.vfs.va.gov/d/000000013/job-queue?orgId=1)
- [ ] VSP - [Backend Service Report](https://grafana.vfs.va.gov/d/000000050/backend-service-report?orgId=1)
- [ ] API - [Vets-api](https://grafana.vfs.va.gov/d/000000017/vets-api?orgId=1)
- [ ] API - [Flipper metrics](https://grafana.vfs.va.gov/d/7MbEgpk7z/flipper-metrics?orgId=1&refresh=1m)
- [ ] VSP - [Backend to Frontend App Mapping](https://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1)

**Comment by LindseySaari** [comment]
@RachalCassity Can you link to the graphs in the new fedramped Datadog version?
