### ISSUE TITLE
Implement super admin for Argo integration

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#43760]
## Why are we doing this
We are currently dependent on the AMT team and need to implement a work around to get Keycloak and Argo to talk together.  This will be removed when AMT gets us a permanent solution 

## Tasks

- [ ] Investigate the use of the Github access token (timeblock this to a few hours max) 
- [ ] Implement super duper user if necessary

**Comment by ericboehs** [comment]
Closing until Console project is active.
