### ISSUE TITLE
Create a production API key for Lighthouse and store into Credstash

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4377]
## User Story or Problem Statement
As an engineer, I need to request, create, and store a production-ready API Key for the VA Lighthouse APIs. This API key should be associated with our work on www.va.gov.

## Goal
The Forms API is functionality in production - `https://api.va.gov/v0/forms`.

## Acceptance Criteria
- [ ] The production API key for VA Lighthouse is stored securely in Credstash
- [ ] https://api.va.gov/v0/forms renders a blob of JSON data describing VA forms
- [ ] The widget on the upcoming `/find-va-forms` page has access to a functional API

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
Email has been sent to Lighthouse API team. Now, we wait :hourglass:

**Comment by ncksllvn** [comment]
Demo with the Lighthouse team is complete, and we have a PR open to implement production access. Should be done today.

**Comment by MickinSahni** [comment]
associating with sprint 13 and closing out cc @MickinSahni
