### ISSUE TITLE
Offboarding of [Yu, (Boris) Ning]

### ISSUE THREAD

**Issue by eunicegar** [department-of-veterans-affairs/va.gov-team#43778]
# Instructions
Fill out name of individual and *Description* section below.

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Yu (Boris), Ning
- team name:
>[all-va](https://github.com/orgs/department-of-veterans-affairs/teams/all-va)
>[BAH-Map-Team](https://github.com/orgs/department-of-veterans-affairs/teams/bah-map-team)
>[BAH-VBMS-Cloud](https://github.com/orgs/department-of-veterans-affairs/teams/bah-vbms-cloud)
>[CTO SRE team](https://github.com/orgs/department-of-veterans-affairs/teams/cto-sre-team)
>[cto-engineers](https://github.com/orgs/department-of-veterans-affairs/teams/cto-engineers)
>[all-va](https://github.com/orgs/department-of-veterans-affairs/teams/all-va)
>[Digital Service at VA](https://github.com/orgs/department-of-veterans-affairs/teams/digital-service-at-va)
>[DS Appeals](https://github.com/orgs/department-of-veterans-affairs/teams/ds-appeals)
>[DSVA - SRE](https://github.com/orgs/department-of-veterans-affairs/teams/dsva-sre)
>[DSVA Appeals - DevOps](https://github.com/orgs/department-of-veterans-affairs/teams/dsva-appeals-devops)
>[MAP-Apothesource](https://github.com/orgs/department-of-veterans-affairs/teams/map-apothesource)
>[VAEC-COMs](https://github.com/orgs/department-of-veterans-affairs/teams/vaec-coms)
>[Vets.gov Engineers](https://github.com/orgs/department-of-veterans-affairs/teams/vets-gov-engineers)

This team includes all members of the Department of Veterans Affairs organiza...
goldenmeanie jjulian ericboehs madebydna dcinzona cweagans acrollet infinityplusone […](https://github.com/orgs/department-of-veterans-affairs/teams/all-va/members)
2999 members	0 teams 
[BAH-Map-Team](https://github.com/orgs/department-of-veterans-affairs/teams/bah-map-team)
Booz Allen team for MAP/VAOS
zanloy jjensen23 boris-ning-usds
3 members	0 teams 
[BAH-VBMS-Cloud](https://github.com/orgs/department-of-veterans-affairs/teams/bah-vbms-cloud)
Working BAH group for Migrating VBMS to the cloud.
1114Organic cameronw711 boris-ning-usds
3 members	0 teams 
[CTO SRE team](https://github.com/orgs/department-of-veterans-affairs/teams/cto-sre-team)
A set of Site Reliability Engineers under the VA CTO's Office
boris-ning-usds
1 member	0 teams 
[cto-engineers](https://github.com/orgs/department-of-veterans-affairs/teams/cto-engineers)
A team for CTO Engineers
stephenBarrs boris-ning-usds mchelen-gov CoryTrimmUSDS shanemelliott robertdurkin codyreinold-usds travis-newby […](https://github.com/orgs/department-of-veterans-affairs/teams/cto-engineers/members)
9 members	0 teams 
[CTO-office](https://github.com/orgs/department-of-veterans-affairs/teams/cto-office)
- role on team:
  > Engineer
- expected last day:
  > 7/5/22
- company they work for:
  > Dept. of VA/OCTO
- email:
  > Yu.Ning@va.gov
- GitHub username:
  > boris-ning-usds
- additional access they may have:
  > ex: SOCKS, Pagerduty, Google analytics, etc.
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [ ] DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [ ] Remove from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [ ] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [ ] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [ ] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [ ] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [ ] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [ ] Datadog account disabled (if applicable. Check [Datadog users](https://app.datadoghq.com/organization-settings/users))
 - [ ] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [ ] Google analytics, and Domo access removed (if applicable) 
 - [ ] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Operations team members
   
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users
   
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-analytics-insights , @department-of-veterans-affairs/confluence-admins

**Comment by rmtolmach** [comment]
Boris already created one 😄 https://github.com/department-of-veterans-affairs/va.gov-team/issues/43736. closing.
