### ISSUE TITLE
LOE for: Drupal template for the basic forms landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4379]
**User story:** 
As a veteran who does a Google or other organic search for form X, I want to be able to find the form and also know if there's an online alternative that's easier than filling out and mailing a paper form. 

**Background:** 
We have 2 kinds of 'master detail' form landing pages - custom and 'template.' We are creating custom landing pages for our top forms that map to our online tools. The custom pages share many of the same content fields as the basic template version but with a few that are unique and customizable. 

**Task:**
- Investigate what it will take to build this page as a template in Drupal. 
- Build the template. 

**Acceptance Criteria:** 
- An LoE and next steps for executing is provided by the VSP CMS team

**The basic template page has these content fields:** 
The content fields in a template landing page – if it has everything filled out in the db schema – will be:
a.	Form number H1  [rigid; dynamically pulled from forms db]
b.	Form name H2 [rigid; dynamically pulled from forms db]
c.	Related to: [category, category… one or multi-select] [rigid; dynamically pulled from forms db]
d.	Form download link [rigid; dynamically pulled from forms db]
e.	Button CTA to online exp – omit in FE if N/A [dynamically pulled from forms db, but only if form has an online tool]
f.	Standard helpful links [rigid; static content]

**FYI for comparison - the CUSTOM (customizable) landing page will include the above, plus:**
- When to use this form [rigid label; customizable blurb text]
- Related forms and instructions [rigid label; customizable text links]
- Custom helpful links (instead of the standard links - but same component style)

Product repo: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

@kevwalsh - [edited JL:] - Doc showing mockups of design is uploaded here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-form-master-detail-LP-patterns-mockups-v7.pdf

FYSA @Karak888 @jefflbrauer - adding this ticket to our board here bc CMS team doesn't have a GH board yet.

**Comment by Karak888** [comment]
follow-up from conversation is we will build page in drupal to host Static content and dynamic content is going to be react based.  @kevwalsh @ncksllvn - will reach out to Lighthouse API team.

**Comment by MickinSahni** [comment]
@jenniferlee-dsva is this an item for pub. websites to accomplish re: determining LoE/building template? If not, which team would we go to for this?

**Comment by MickinSahni** [comment]
Hey @kevwalsh, could you provide an LoE on this effort and/or let us know if you have any questions we can clarify? cc @jenniferlee-dsva

**Comment by MickinSahni** [comment]
Will label with the appropriate PW discipline—FE or content—once this is ready to go

**Comment by MickinSahni** [comment]
PW Grooming notes:
Modify this ticket to more accurately reflect current state. Work with Nick to revise. Likely to be an investigation ticket (or closed out with a new one created if warranted). Assigning to me (Mickin).

**Comment by MickinSahni** [comment]
Update: not active work for PW. PW is going to keep this open to track this effort.

@kevwalsh Hey Kevin, I'm re-assigning this to you so you're aware of how we're tracking this LoE, etc. Feel free to update the milestone as needed. cc @jenniferlee-dsva

**Comment by jenniferlee-dsva** [comment]
@MickinSahni @kevwalsh - We can close this LOE ticket. Per my convo last week with @JeffBarnesUSDS @davidconlon @KevinMHoffmanUSDS and @chrisj-usds, we will request Drupal engineering resource from VAMC team to build this template AX in Drupal.

**Comment by MickinSahni** [comment]
Done. Thanks, Jen
