### ISSUE TITLE
Audit legacy BVA content to prepare for migration

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#43796]
## Story

As a VA.gov or BVA team member, I need to understand the legacy content to be able to discuss and make informed decisions about content migration.

## What's needed

- [x] Create content audit template for BVA site (Danielle)
- [x] Pull Google Analytics report for a year of data on BVA site (Danielle)
- [x] Pull SEMRush report for BVA site (Danielle)
- [x] Add page titles and URLs to audit (VA.gov content and IA team)
- [ ] Fill in information for orange columns in audit (BVA team)
- [ ] Fill in information for blue columns in audit (VA.gov content and IA team)
- [ ] Review audit (Danielle)

## Files for reference

- [Full shared folder for BVA content migration work](https://dvagov-my.sharepoint.com/:f:/g/personal/danielle_thierry_va_gov/EqbHhtw1smhEpxYD6CASXN0BnWbSsQEOyRhH_Roa4abKpA?e=DFPDkQ)
- [WIP BVA content audit](https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/EWjGN0yc1DhEmoiByOwRLJIB9wFOeNtoAu3m4Zg4q3QgzA?e=bQ2aiK)
- [BVA Google Analytics report](https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/EX9Vs-N6Kt5Eg8rKjHUnmhcBr1sJD6B2EBDkmIys65gxew?e=eCaI9I)
- [BVA SEMRush report on organic search](https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/EZWv8h0tsLFFmsf2camlqXABZTax4VkQZI_3OMSi6IyJ3Q?e=lPtpNi)

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA and @RLHecht, I've added page titles and URLs to the content audit spreadsheet.

**Comment by RLHecht** [comment]
@katherine-fung We can continue to use this ticket for the next steps in the audit, which is going through each of the BVA pages you listed in the spreadsheet and filling out the columns H-Q. You can use the GA and SemRush links that Danielle posted above to add that information into this spreadsheet as well for columns S-Y. @DanielleThierryUSDSVA where is the best place for her to find the information about the deprecated IRIS questions?

Here's a link to the spreadsheet for easy access: https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/EWjGN0yc1DhEmoiByOwRLJIB9wFOeNtoAu3m4Zg4q3QgzA?e=bQ2aiK

Everything is in Sharepoint on the VA side of things.

**Comment by katherine-fung** [comment]
Hi @laurwill! Posting a link to the audit spreadsheet for our sync today: 

https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/EWjGN0yc1DhEmoiByOwRLJIB9wFOeNtoAu3m4Zg4q3QgzA?e=bQ2aiK

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA, I've reviewed the BVA pages and filled out the relevant columns in the audit spreadsheet, except for "Related (now deprecated) IRIS questions and VA.gov site or R&S  search data on this topic."

When you have a chance, can you let me know where to find this information? 

Thank you!

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA! 

I've filled out the columns on the BVA audit that our team is responsible for. Please let me know if you have any questions. 

Here's the link: 

https://dvagov-my.sharepoint.com/❌/g/personal/danielle_thierry_va_gov/EWjGN0yc1DhEmoiByOwRLJIB9wFOeNtoAu3m4Zg4q3QgzA?e=bQ2aiK 

Thanks!

**Comment by RLHecht** [comment]
Closing this ticket and breakout out the BVA team and OCTO-DE work into a separate ticket.
