### ISSUE TITLE
Setup DevOps monthly CoP

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#43804]
In the Platform Leadership meeting there was discussion around DevOps and some opportunities to improve the connective tissue for the DevOps engineers that are embedded into teams with the Infrastructure team. A suggestion that was made was to setup a CoP type meeting where the DevOps resource types can have discussions and share information/thoughts.

The goal of this ticket is to work w/ Jesse H to get this meeting coordinated and scheduled out.

**Acceptance Criteria**
- [x] Document meeting goals / objectives
- [x] Determine next steps and address in action items / other tickets as needed

**Comment by little-oddball** [comment]
Jesse and I met on 7/15 and worked out some thoughts and ideas on approach forward. Jesse had already put this document together and we did some expansion on it:

https://vfs.atlassian.net/wiki/spaces/OT/pages/2201255944/GOAL+Implement+DevOps+community+of+practice

It also outlines action items, etc.

**Comment by andreahewitt-odd** [comment]
@little-oddball @jhouse-solvd Can you link the tickets for the next action items here?

**Comment by little-oddball** [comment]
I reached out to @jhouse-solvd to see if he would mind creating an Epic to link back to this ticket and "close the loop"

**Comment by jhouse-solvd** [comment]
@andreahewitt-odd & @little-oddball - Here's a first pass on the issue w/ follow up tasks: 

[[Platform Collaboration] Establish DevOps Community of Practice #45129
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45129)

Let me know if there's anything else you'd like to see on there! :)
