### ISSUE TITLE
GIDS: Use Scorecard API to replace flat-file upload.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4380]
As an EDU team member, I would like GIDS to pull scorecard data via API so I no longer have to upload a CSV into GIDS.

## Assumptions:
1. The current upload functionality will not be removed until after this feature has passed UAT.
2. The developer will need to request an API key from Supporting Artifact # 1; it will be replaced if possible with an enterprise key which is in the process of being requested.

## Acceptance Criteria:
1. The user can manually update the Scorecard data via API.
2. The data retrieved via API matches the data that is uploaded manually.
3. The API key is configurable.

## Supporting Artifacts: 
1. The API and related documentation can be found here: https://collegescorecard.ed.gov/data/documentation/

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/535
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/536
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/534
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/546
https://github.com/department-of-veterans-affairs/devops/pull/6271

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/535
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/536
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/534

**Comment by zurbergram** [comment]
Test using https://github.com/department-of-veterans-affairs/gibct-data-service/pull/534

To Test
- Click "Fetch" button in Latest Uploads > Scorecard row
- Should see a "Fetching" message in this row
- When fetching is done a message at top should be displayed indicating so and the Latest Uploads table should return to normal
- In postgresql database or exported CSV should have 7112 rows in scorecards table

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-01-17 at 8.56.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/45684114-3341-4a40-8c07-3ee2c7b65033)
##
![Screen Shot 2020-01-17 at 8.54.52 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b9057ad8-8f89-47ed-9b5a-84270c79fac3)
##
![Screen Shot 2020-01-17 at 8.53.55 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d98e0eb7-dbda-4a98-8aa4-d588510011be)
##
![Screen Shot 2020-01-17 at 8.54.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ada4877e-f2a0-4024-9895-fe558d319773)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/6271

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/546

**Comment by delli-gatti-michael** [comment]
re-validated in staging. Closing this issue
