### ISSUE TITLE
Define DevOps "Happy Path"

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#43802]
There is some grey area for what DevOps resources on other teams are allowed or not allowed to do and what the expectations around that might be. Additionally, there are challenges with teams that do not have DevOps resources but need assistance and/or those teams, such as Security, that require separation of concerns for DevOps tasks. Due to these items, there is a need to put together a definition of the Happy Path workflow to better define and make clear guidance and direction.

- [x] Work with Kyle, Jesse and Thomas to get happy path outlined and defined
- [ ] Follow up to wrap up outline, etc. to present
- [ ] Review guidance with Platform Crew
- [ ] Make updates to documentation as needed

**Acceptance Criteria**
- [ ] Document Happy Path Workflow
- [ ] Communicate/share guidance with Platform Teams

**Comment by little-oddball** [comment]
Meeting setup to discuss with Kyle and Thomas on 7/28.

**Comment by little-oddball** [comment]
Based on our meeting w/ @td-usds @ph-One @jhouse-solvd here are the notes:

https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2294415411/Dev+Ops+Happy+Path

Test version below:

Team that has a DevOps Resource
Scenario: 

A team has a DevOps resource that needs the ability to manage platform infrastructure resources on behalf of their team. 

In this scenario, the DevOps resource needs a subset of permissions granted to the Platform Infrastructure team. 

Goal: They are put into a permission boundary and can go and do whatever they want, given the permissions that have been granted to them. (See action item below) 

Team that does not have a DevOps Resource
Note: Also covers “team has a DevOps Resource which shouldn’t do a particular thing” which handle

Scenario: 

A team does not have a DevOps resource or does not have a DevOps resource that has the ability (or permission) to manage platform infrastructure resources on behalf of their team. 

Item is explicitly outside of their permission boundary

Separation of Duties 

Platform vs VFS 

A team needs to verify or validate something for compliance, QA, or other 

Goal: ??? 

Note: I think the “goal” is to have them plan the work in advance so they can work w/ the infrastructure team to schedule the work and get it done. (Jesse)

Future Ideas for how to allocate Platform DevOps resource 
If a team has a primary DevOps resource that will not have a full workload for a sprint (or more), then that resource could be allocated to the Platform Infrastructure team to pick up ready-to-do items from the board (or other items as needed by the Infra team). That DevOps resource would still prioritize work from their “home team” to ensure that resources are not being taken away from teams, but rather re-allocated if they have free bandwidth. 

Action items 

The Platform Infrastructure team will schedule work for Sprint 7 to develop a baseline permission boundary policy for DevOps resources on the Platform Crew team. Development of the policy should include automated testing as part of the Acceptance Criteria (WIP [here](https://github.com/department-of-veterans-affairs/devops/pull/11595/files))

  - [ ] What are the teams? 
  - [ ] Who are the DevOps resources on those teams? 
  - [ ] Communicate expectations to those teams and resources
  - [ ] Establish DevOps Community of Practice (in progress)

**Comment by little-oddball** [comment]
@jhouse-solvd @ph-One Just looking to see where we are on this work and if a follow up needs to be scheduled to make any adjustments. Goal is to get thumbs up from PO and messaging out to platform teams so we can close this one out. Thanks.

**Comment by jhouse-solvd** [comment]
@little-oddball - thanks for the nudge. I'll sync w/ Kyle about it next week and follow up here.

**Comment by jhouse-solvd** [comment]
@little-oddball - We're working to [implement the MVP of the permissions boundary](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45254) this sprint. Once that's done, we'd love to discuss it with you and Thomas to see if any adjustments are needed. We'll follow up as head into the next sprint if that works for you. :) 

cc: @ph-One

**Comment by little-oddball** [comment]
> @little-oddball - We're working to [implement the MVP of the permissions boundary](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45254) this sprint. Once that's done, we'd love to discuss it with you and Thomas to see if any adjustments are needed. We'll follow up as head into the next sprint if that works for you. :)
> 
> cc: @ph-One

@jhouse-solvd - That sounds great and thank y'all for working it!

**Comment by little-oddball** [comment]
Based on adjustment of the organization and working towards ALL DevOps resources on the tech teams having the abilities to do the same level of tasks, this is considered OBE.
