### ISSUE TITLE
[DESIGN] MyHealth - Annotate mockups for MHV engineers

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#43838]
Annotate mockups for MHV engineers

**Comment by jonathanjnelson** [comment]
- [Spacing template landing page - desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/agpMAaZ) and [mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/kaPKgQP)
- [Spacing template compose desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/AxpZQR4) and [mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/1KJV0Pk)

[Annotation for landing page ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/4aexVRZ)

[Annotation for compose message](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/eKw8kPj)

**Comment by MarciMcGuire** [comment]
@jonathanjnelson is this ready to be marked as complete?  We have additional time baked in for updates based on the usability study

**Comment by jonathanjnelson** [comment]
Yes, this is all the developers requested/needed right now.

**Comment by MarciMcGuire** [comment]
Perfect.  Thank you!
