### ISSUE TITLE
CT: Update School Locations Section to page when there are more than 10 locations

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4383]
As a CT user, I need the school locations section to include paging so that the amount of scrolling is reduced to get to the next section.

## Assumptions:
1. This work is completed behind a flag so that it is only available in the staging environment and below.

## Acceptance Criteria:
1. On mobile, the initial display is the first 5 locations.
2. On non-mobile, the initial display is the first 10 locations.
3. There is an informational message stating "Showing X of Y locations" if there are more locations than specified for the display type in AC 1 & 2.
     a. X is equal to the number of locations currently displayed
     b. Y is the total number of locations that are possible to be displayed
4.  The user can view 10 additional locations at a time.
     a. The additional locations are appended to the list.
     b. If there are less than 10 additional locations, the button only prompts to show the remaining locations (ex. "Show 3 additional locations)
5. The user has the ability to view all locations at once
6.  Once all locations are being displayed, the user has the ability to revert the locations display the initial locations display

## Supporting Artifacts:
1. Prototype: https://bahdigital.invisionapp.com/share/C3IAC976T2D#/screens/296026170

**Comment by hughes-dustin** [comment]
branch: bah-4383
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11397

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-12-31 at 11.38.26 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/524192c9-255f-4bce-b4d0-92eba0a17970)
##
![Screen Shot 2019-12-31 at 11.38.35 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3df599fe-d3be-4f84-b7b7-2dac9b77eeed)
##
![Screen Shot 2019-12-31 at 11.38.41 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/eadf2bcf-6723-4986-8015-46fae6c99063)
##
![Screen Shot 2019-12-31 at 11.38.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aece67de-78c8-4f3b-9f10-c0904365d17c)
##
![Screen Shot 2019-12-31 at 11.38.54 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/24dd6feb-9d2a-48b6-bd6d-ea260490156d)
## 
![Screen Shot 2019-12-31 at 11.41.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/38a2d192-56df-4289-b598-8a8d55d433bd)
##
![Screen Shot 2019-12-31 at 11.43.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/805cf5a6-83d9-4835-b2e1-056972330af6)
##
![Screen Shot 2019-12-31 at 11.45.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7067d9d3-f316-445b-a3a8-3cb561d88cc6)
##
![Screen Shot 2019-12-31 at 11.46.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c63a41ec-24a6-4862-8642-6cd48dcaf0b8)
##
![Screen Shot 2019-12-31 at 11.46.09 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/193855eb-bfa3-436d-84f2-a784d848e0aa)
##
![Screen Shot 2019-12-31 at 11.46.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/84ac3b64-abf5-4ffd-92b3-d5f0f082a278)

**Comment by sonntag-adam** [comment]
Does not show in a production build.

**Comment by sonntag-adam** [comment]
In staging, closing out story. Testing passes QA
