### ISSUE TITLE
Update Github reminder slack channel destinations, make -alerts channels moderated

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#43842]
- [x] Move [reminder](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-operations/settings/reminders/14147) `#platform-infrastructure-alerts`
- [x] Move [reminder](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-operations/settings/reminders/14560) to `#platform-infrastructure-alerts-private` 
- [x] Set `#platform-infrastructure-alerts` and `#platform-infrastructure-alerts-private` as moderated
  - Allowed users: `@github` `@LambdaBot`

**Comment by rmtolmach** [comment]
@mchelen-gov I get 404s when I go to those "reminder" links, but I think this is related to `LambdaBot` being moved to a different channel and that channel having restricted posting. It looks like the `LambdaBot` AWS reminders of inactivity got moved to the private channel, so even if we were able to create a thread (which I don't think we are anymore. But I could be wrong!), the person would not be notified. [From the Slack docs](https://slack.com/intl/en-in/help/articles/205240127-Use-mentions-in-Slack):
> If it’s a private channel, the member won’t be notified and can’t see your message until you invite them to join the channel.

I think the way to solve this problem (besides reversing the channel posting permissions and moving `LambdaBot` back to a public channel) is by sending a direct message to the IAM users approaching the 90 days of inactivity. I know we're generally supposed to stay out of DMs in the DSVA slack instance, but would this be a valid exception?

(@jhouse-solvd wanted to be involved in this 😃)

**Comment by mchelen-gov** [comment]
> @mchelen-gov I get 404s when I go to those "reminder" links, but I think this is related to `LambdaBot` being moved to a different channel and that channel having restricted posting.
That's because the links require `maintainer` perms on the team: https://github.com/orgs/department-of-veterans-affairs/teams/vsp-operations/members

>It looks like the `LambdaBot` AWS reminders of inactivity got moved to the private channel, so even if we were able to create a thread (which I don't think we are anymore. But I could be wrong!), the person would not be notified. [From the Slack docs](https://slack.com/intl/en-in/help/articles/205240127-Use-mentions-in-Slack):
> 
> > If it’s a private channel, the member won’t be notified and can’t see your message until you invite them to join the channel.
> 
LambdaBot AWS reminders are still going to `#platform-infrastructure-alerts` i.e. https://dsva.slack.com/archives/C03JZS08VV4/p1657119660719169
I just added the bot to both chans in case there were other alerts that need to be sent to `#platform-infrastructure-alerts-private`

> I think the way to solve this problem (besides reversing the channel posting permissions and moving `LambdaBot` back to a public channel) is by sending a direct message to the IAM users approaching the 90 days of inactivity. I know we're generally supposed to stay out of DMs in the DSVA slack instance, but would this be a valid exception?
> 
> (@jhouse-solvd wanted to be involved in this smiley)

Open to any changes with the AWS inactivity alert that would reduce manual involvement from Infra team! My guess is that the hard part is associating AWS IAM IDs with Slack user IDs.

**Comment by rmtolmach** [comment]
> LambdaBot AWS reminders are still going to #platform-infrastructure-alerts

Ah, okay! And I see we do actually have permission to comment in threads. So all is good here. 

> My guess is that the hard part is associating AWS IAM IDs with Slack user IDs.

This hasn't been a problem. People's names match up pretty well.
