### ISSUE TITLE
[BE] 10-10CG Mulesoft Ph2: Implement single, async POST to Mulesoft with Data & PDF

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#43847]
## Background
Currently, vets-api sends the CG application data and PDF in separate calls.  With the Mulesoft integration now in place, we want to combine both the data and PDF in one asynchronous call.  
**Note**: vets-api retries capability will be implemented in ticket #42079.

- [json document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Mulesoft%20Integration/Queuing/1010cg-api-swagger%20(provided%20by%20Salesforce).json) received and stored in GH outlining the appropriate endpoint to receive submissions from va.gov

## Acceptance Criteria
- Once a CG application has been completed and submitted on va.gov, the vets-api will send a single, asynchronous call to Mulesoft with the data **and** PDF of the submitted CG application.

**Comment by hdjustice** [comment]
@markfallows  - FYI, created this ticket based on conversation and agreement with CG team.

**Comment by markfallows** [comment]
This API endpoint may not be available.

Need to confirm with stakeholders that the endpoint is available; and, if not, when it might be.
