### ISSUE TITLE
[BACKEND] MyHealth - Discovery on Cerner endpoints

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#43840]
Overview: Review Cerner API documentation to determine what data is returned in the response and if everything we are proposing to include is supported.

**Comment by MarciMcGuire** [comment]
@patrickvinograd I prob should put this as blocked since there seems to be no clear timeline for getting this info. Agree?

**Comment by batemapf** [comment]
@MarciMcGuire @carlosfelix2 Do we need this ticket? Seems super general, was created nearly a year ago, and it has been sitting in `Blocked` for a couple of months.

**Comment by MarciMcGuire** [comment]
@batemapf Just closed it. It was an overarching Cerner API discovery ticket, and now those will be more granular.  Thank you!
