### ISSUE TITLE
[BE] 10-10CG Mulesoft Ph2: Implement alerts to post in Slack channel and email group

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#43849]
## Background
Currently, vets-api sends the CG application data and PDF in separate calls.  With the Mulesoft integration now in place, we want to combine both the data and PDF in one asynchronous call.  
**Note**: vets-api retries to send this single, async call will be implemented in ticket #42079.

With this single, async call to Mulesoft, we need to put monitors and alerts in place to be notified of any outages or persistent retries and issues (thresholds TBD).  The alerts will need to be added to the #health-tools-1010-apm slack channel, as well as emailed to a specified group of people (TBD).

Current alerting will no longer work since we are moving to a background job.

For details on the procedure when retries fail ("Catastrophic Failure"), Please see the **[Vets-api retries - catastrophic failures SOP (Standard Operating Procedure)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Vets-api%20retries%20for%20MuleSoft%20-%20Ultimate%20Failures%20process.md)**

## Tasks
- [ ] Implement an earlier alert based on **>5 retry failures with 3+ retries over a period of 10 hours**
  - Alerting should post to the following Slack channel: `#health-tools-1010-apm`
- [ ] Implement an alert for when a submission fails completely at 1 day of retry failures
  - Alerting should post to the following Slack channel: `#health-tools-1010-apm`
  - Automated Email should be sent to the following audience:
     - Patrick Bateman
     - Heather Justice
     - Mark Fallows
     - Lihan Li
     - Lisa Zapson
     - Matt Long
     - Nick Osmanski
     - VACARMAOperationsTeam@va.gov
     - DTCMulesoftSupport@va.gov

## Acceptance Criteria
- Monitors will be put in place, along with thresholds identified, so that any alerts will be sent to the #health-tools-1010-apm slack channel, as well as emailed to a specified group of people (TBD).

**Comment by hdjustice** [comment]
@markfallows - FYI, created this ticket to implement monitors & alerts on the calls to Mulesoft along with implementing the single call and retries

**Comment by markfallows** [comment]
Still need to know what kind of thresholds we're looking at for retries.

**Comment by hdjustice** [comment]
@lihanli - I updated the Tasks to indicate that we need 2 alerts = 1 for the pre-catastrophic failures, and 1 for the 1-day catastrophic failure.
