### ISSUE TITLE
Running CI for changed app builds and full builds

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#43867]
**PROBLEM**
There are currently 2 main issues that are blocking the continuous production deployment of applications on the allowlist.

A race condition that will exist between the daily production deploy and changed app production deploys
Changed app production deploys may be built and tested with recent updates to global assets that aren't in the S3 production bucket at the time of their deployments

[More information](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35198#issuecomment-1170528500)

**DEFINITION OF DONE**

**Comment by theodur** [comment]
Closing this ticket since we're no longer planning to update the build directory structure. This won't be needed anymore since CI already handles building and testing both build types with our current infrastructure
