### ISSUE TITLE
Adding Xernan Peralta to DSVA Slack

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#43863]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- What channel(s) do they need to be added to? #feedback-backchannel, #design, #research-ops, #vsp-support, #inclusive-research, #vsp-research, #vfs-test-accounts

## Sample Descriptions 
- Please add peralta_xernan@bah.com as a full member. Xernan is a researcher on the VA Lighthouse program.

**Comment by LEHigley** [comment]
so sorry for the delay @careyotto --i was OOO last week didn't realize these weren't going out. invite sent!
