### ISSUE TITLE
[ISSUE] CT Data list link broken 

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#43877]
## Issue Description
The ComparisonToolData.xlsx link is broken when clicked. 

Please determine why the ComparisonToolData.xlsx link is broken.

-Main Page - **https://www.va.gov/education/gi-bill-comparison-tool/**

- Broken LINK - https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/aeccfb8d-ff94-4145-b2b5-c6b4b1de87f9)

**Comment by af-manish** [comment]
It looks like this is the current link: https://www.benefits.va.gov/GIBILL/docs/**job_aids**/ComparisonToolData.xlsx  . This link, however works: 
https://www.benefits.va.gov/GIBILL/docs/ComparisonToolData.xlsx  

Should it go to this link?

**Comment by MitchLivingstone** [comment]
Brain Grubb will reach out to Tammy Hurley to determine what could be the background issue with the link. All updates to the URL will be on hold until further instructions from Brian Grubb and Tammy Hurley are received. 

- 07/11/2022

**Comment by MitchLivingstone** [comment]
It was determined the original link is the correct link. AFS QA has validated that the original link is functioning properly according to Tammy Hurley's email. This is completed and closed. 

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/b889e041-b189-4b3e-bfad-957b9660606c)
