### ISSUE TITLE
SOCKS access for [Erica Sauve]

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43888]
### Your Name

Erica Sauve

### Your Email

erica.sauve@adhocteam.us

### Your Role and Team

Associate Product Manager, Authenticated Experience

### Product Manager (PM) name and email

Ana Jakabcin - ana@adhocteam.us

### Product Owner (PO) name and email

Samara Strauss - samara.strauss@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDM4FCctptFtNXXkSOGfQJY3nfeFlJKwN9t4K4fmsfDXHKqmu5FSxIuukCiV3syvUvFmqrF9HKIjUkUgtpcF2qT8E9qXzy9ZBcyyhEdR/LhtbNUK125Z2hMi4REQw12Aihhh3P8WWtImdOSg4m2U8drGmRyWrb5pIhmM+zjbJ1ILz4hFMiByWlg7urI61SZ+39HxQA8trVCKMEIjqG5LVRxDIZJH2yjjfzc22ywE241pNMCfzrMnJeoaDG8NxGTjIYm9WKeDxcAv9o/KW71uqCR58Q+OnzolANNrbVKczrgGiM5BIM43/HlLlhmt/xvdTR+7zwIOD4TK69sD4PXp/liKYDGLuRIGZlZHajVIXftNgYxiPdwPEl49V4U0l/T5l8Zy6/LvYcyfvcW+7E5rDbqvUSYCdQ9wZf6hFgpWKuU3LBHkWg0FNAlQk6UBmBV2LkJxhhyTgHU2I4Nr2/OaEhBT0IRbh0gpckvW9TsjUZv/yn1keIjyNJGr6b++t3TbtU= ericasauve@ericas-mbp.lan

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@ericasauv09 - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
