### ISSUE TITLE
From Support Ticket: Create E2E test examples document

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#43886]
We want to write a document explaining best practices for how to set E2E tests with examples of what a good E2E test looks like and some examples of what bad E2E tests look like.

Related to these tickets:
https://github.com/orgs/department-of-veterans-affairs/projects/724/views/1
https://github.com/department-of-veterans-affairs/va.gov-team/issues/42116

**Comment by andreahewitt-odd** [comment]
Should we hand this off to QA standards team?

**Comment by andreahewitt-odd** [comment]
@JoeTice Is this something your team can put in your backlog and prioritize?
