### ISSUE TITLE
SOCKS access for Jason Conigliari

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va.gov-team#43889]
### Your Name

Jason Conigliari

### Your Email

jason.conigliari@adhocteam.us

### Your Role and Team

Backend Engineer on VA Mobile

### Product Manager (PM) name and email

Travis Newby travis.newby@va.gov

### Product Owner (PO) name and email

Travis Newby travis.newby@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUAZj2wSXt5CaXuE55+3yUcrt1SpvHSvO1xeMD0vJ28fhHdP/VVRP7X1gIbNtsOwA6ogRJoPTRWJH6q02L9VJYM5NWhTvj8gxHAfn+0M0Kw08enrCtAfjwv1neuZ4drBxoK2gpmcQGPpIRfT83uiS6dobImjXWbhRF8nur+i8AP4f3kGHDQndJB5WabJ53ZKAywdCoJKCY1kXpkxn74HKKJJZDm0Fj/1xrDkZtwI8OyX5d5NgUNhbnGJOGCQ51o1sn2KJtYvQ2uUGzUl/lPmZQNARGa/VijhFABNOFxXHWafjFOCRbgB9nlja32xZDD6UPuNxgjyOxJSACoQi64vA1MkdDaCw8Fj/J2A468Uh2KB/39DUkkO6m5Y2vSta0tHCmYXBpm6gVUAErz8ugmrmPS72xm43mK9VNhp1GQDE9JVGi1q77PwPndn2eO0REyZXvdk94Jma32B/fGk9+m6QoJ7s7raeqtLtdpVg0KaFIEF7091G+yqZEhL3OJ5R52c0= jasonconigliari@Jasons-MacBook-Pro-2.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Found @Tonksthebear in the VFS Team roster. Proceeding

**Comment by kjduensing** [comment]
@Tonksthebear - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
