### ISSUE TITLE
Adding Jasmyn Kelly to more DSVA Slack Channels

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#43897]
# Description

Jasmyn Kelly (Kelly_Jasmyn@bah.com, jasmyn.kelly@va.gov) **is already present** in DS@VA Slack space but only has 2 of the channels she will need. 

Please change her to a full member guest and ensure she is added to these channels:

#vfs-all-teams
#vfs-benefits
#victories
#oncall
#general
#random
#slack-workspace-admin
#vfs-platform-builds
#vfs-platform-support
#vsa-ebn-migration
#vfs-evss-service-migration
#va-forms
#va-letters
#benefits-team-1
#evss-prod
#evss-devs
#va-mobile-app
#accountexp-authexp

Jasmyn is a software developer in my Lighthouse team. We support several APIs that are leveraged by VA.gov and Mobile.

**Comment by LEHigley** [comment]
changed to full member
