### ISSUE TITLE
Send the VA Design System Tagalog translations for controls

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#43895]
## Issue Description
Currently, VA design system components are not translated when the app is set to tagalog.

We need to coordinate with the VADS team to see whether they can support tagalog, and send over translations for components we are using once we have them.

For reference - The document we sent over for Spanish component translations:
https://docs.google.com/spreadsheets/d/11a5nfSNhFrju_qLRWNM71cb86oZVe4L4K826xNDDDU8/edit#gid=0

Tagalog DS translations:
```
{
  "error": "Error",
  "required:": "Kailangan",
  "max-x-characters": "Pinakamarami ang {{number}} character",
  "date-of-birth": "Petsa ng Kapanganakan",
  "month": "Buwan",
  "day": "Araw",
  "year": "Taon",
  "please-enter-a-year-between-x-and-y": "Mangyaring ilagay ang taon sa pagitan ng {{year1}} at {{year2}}",
  "collapse-all-accordions": "I-collapse ang lahat ng accordion",
  "expand-all-accordions": "I-expand ang lahat ng accordion",
  "collapse-all": "I-collapse ang lahat",
  "expand-all": "I-expand lahat"
}
```

**Comment by brianseek** [comment]
Sent Tagalog DS translations via slack to Katy Bowman: https://dsva.slack.com/archives/C01DBGX4P45/p1658161433127389

**Comment by brianseek** [comment]
closing with translations sent to DS
