### ISSUE TITLE
Implement YAML configuration for Dependabot

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4391]
## Background 
Now that the `vets-api` repo is using Dependabot, we should migrate our configuration to a more specific rules file.
 See [docs](https://dependabot.com/docs/config-file/).

## Acceptance Criteria

- [x] Dependabot uses .yml config
- [x] Configuration is not colliding with CMS or other teams

**Comment by LindseySaari** [comment]
At first glance, the [config docs](https://dependabot.com/docs/config-file/) don't specify a rate limiting config setting.

**Comment by johnpaulashenfelter** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3800
