### ISSUE TITLE
ATO : Database Scan Remediation

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#43915]
- [x] SQL remediation (Andy)
- [x] Mongo remediation (Rob)

**Comment by lindsay-insco** [comment]
Ari put together POA&M

**Comment by lindsay-insco** [comment]
Ari to create POA&M with Ambes

**Comment by ahicksfearless** [comment]
Waiting on more info from Ambes.

**Comment by jwowk** [comment]
Scan occurred week of 10/17, waiting for findings.

**Comment by lindsay-insco** [comment]
November 15 - POA&M Review with Phil

**Comment by jwowk** [comment]
Ari submitted new scan request for SQL, awaiting results.
