### ISSUE TITLE
[DNS] Update documentation with information that explains "why" we use Unbound

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#43916]
## Description
There currently exists good documentation that covers what Unbound is and how it is managed. But, the documentation doesn't articulate the background "why" it's used for platform DNS, ie "why not just use Route53?" 

## Background/context 

- There may be technical constraints or legacy reasons for using Unbound for some parts of Platform DNS resolution. 
- It may be possible to remove Unbound from Platform Infrastructure, though that may require additional work to re-configure various infrastructure components. 
- [Unbound service doc in Confluence](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594384/Unbound)
- [Slack thread w/ relevant info](https://dsva.slack.com/archives/CTYQL39FE/p1657137135377349)

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Update documentation with a better explanation of the purpose of Unbound 

## Acceptance Criteria 
- [x] The historical context and purpose of Unbound for DNS resolution are documented in Confluence

**Comment by jhouse-solvd** [comment]
@ph-One & @jbritt1 can likely help with this

**Comment by jbritt1** [comment]
> Have there been any updates on this?
> 
> FYI @troymosher @gary-fallon

Not to my knowledge, other than the existing [Unbound service doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594384/Unbound).

However, here is some more historical context:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/8455
- https://github.com/department-of-veterans-affairs/devops/pull/7485
- https://github.com/department-of-veterans-affairs/devops/pull/7486
- ![image](https://user-images.githubusercontent.com/56260532/179560382-263ded73-18c8-4dbf-be77-79ff5cd84130.png)
- ![image](https://user-images.githubusercontent.com/56260532/179560598-81a9858f-fc4f-4869-929b-c1e8f263a10b.png)

**Comment by jbritt1** [comment]
`Why do we use it?` section added to existing [Unbound service doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594384/Unbound)

![image](https://user-images.githubusercontent.com/56260532/181016246-a8df776a-0a9e-41ea-8a89-238244b5bd18.png)

**Comment by jbritt1** [comment]
Going to close this one as I feel it is complete at this time with the addition of the new section around the "why" of Unbound. I also made sure to mention that it was entirely possible Route53 Resolver could potentially give us this functionality without the overhead of Unbound, but that will need further discussion, testing, and its own ticket as it is not within the scope of this one. 

Feel free to reopen if anyone disagrees or feels this is still not complete.
