### ISSUE TITLE
Launch MVP of VA.gov Product Level SLO data

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#4392]
## Problem

The platform does not currently have any means to monitor and enforce request timing internally at the vets-api layer, or in regards to down stream services.  We do not have set objectives for the time limits for these requests, and we do not have a way to measure if we are hitting these targets.

## Hypothesis or Bet

If we create SLO's for the vets-api layer and the down stream services layer, we will better understand bottlenecks of the platform, be able to communicate with hard data where those bottlenecks are happening so that we can accurately prioritize them and provide that information to responsible teams for mitigation if necessary. 

## OKR
O5: All customers comply with the Platform's standards.

**Comment by rroueche** [comment]
@alexpappasoddball what objective is this in pursuit of? please add to the description.

**Comment by kfrz** [comment]
Monitoring of identity partners will require further discovery. [Here](http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Prometheus%20(Production)%22,%7B%22expr%22:%22sum(increase(api_auth_saml_callback%7Bstatus%3D%5C%22success%5C%22,context%3D~%5C%22dslogon.*%5C%22%7D%5B$__interval%5D))%20by%20(context)%22,%22format%22:%22time_series%22,%22interval%22:%22%22,%22intervalFactor%22:1,%22datasource%22:%22Prometheus%20(Production)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) is a useful perspective into a given logon partner's SAML success rate (for future reference).
