### ISSUE TITLE
AWS access for Dan Brooking

### ISSUE THREAD

**Issue by dan-brooking** [department-of-veterans-affairs/va.gov-team#43935]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Dan Brooking

### Your Email

dan.brooking@accenturefederal.com

### Your Team, Role, and Company

Ruby on Rails Dev legacy edu

### Product Manager (PM) name and email

Abe Blanco abelardo.blanco@accenturefederal.com

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Desired AWS Access

I needed access to GIDS prod. I run an update script for Brian Grub to geocode institutions and to do small queries on data if our group needs to research issues on production.

### Access Expiration

1/1/2023

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by dan-brooking** [comment]
We're just looking to have more people on the team be able to do this to provide support.

**Comment by dan-brooking** [comment]
Ok, I updated it to about 5 months from now. Let me know if I need to make that shorter.

**Comment by oseasmoran73** [comment]
## For AWS Access
User: Dan.Brooking
COR: Other
VOR: Alexa Elliot
Approval required: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Context: Dan already have AWS access. This request is for elevated privs. Currently there are 3 members on his team (missed one in my initial search)

**Comment by td-usds** [comment]
Access approved for 3 months (5 months is too long of a window); I have updated the issue itself with the same

**Comment by td-usds** [comment]
There are multiple requests for the exact same thing: see https://github.com/department-of-veterans-affairs/va.gov-team/issues/43936 which lists the same thing verbatim:
> I needed access to GIDS prod. I run an update script for Brian Grub to geocode institutions and to do small queries on data if our group needs to research issues on production.

We also have confirmation that other members on this team have the required (elevated) access already.

I think it would make sense to discuss how to structure who actually runs that. I have security concerns with granting everyone on a team access to prod. That to me seems like a recipe for undesired things...

**Comment by td-usds** [comment]
Doing some additional data calls

**Comment by td-usds** [comment]
Also reached out to VOR

**Comment by td-usds** [comment]
Additional data call to PO (@mattpointzxer0 ) via Slack

**Comment by oseasmoran73** [comment]
Given this ticket has gone stale and there has not been a ping for urgency, closing this ticket. Please feel free to reopen or submit new one
