### ISSUE TITLE
AWS access for David Rowley

### ISSUE THREAD

**Issue by dsrr47** [department-of-veterans-affairs/va.gov-team#43936]
### COR Name

Other

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

David Rowley

### Your Email

david.rowley@accenturefederal.com

### Your Team, Role, and Company

Front End Developer

### Product Manager (PM) name and email

Abe Blanco abelardo.blanco@accenturefederal.com

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Desired AWS Access

I needed access to GIDS prod. I run an update script for Brian Grub to geocode institutions and to do small queries on data if our group needs to research issues on production.

### Access Expiration

10/01/2022

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by dsrr47** [comment]
Hi Oseas, 
We are just trying to have more people on the team able to do this to provide support. 

I should have an AWS account. Can you help me create one?

**Comment by oseasmoran73** [comment]
Thanks for getting back to me!

> I should have an AWS account.

This makes it seem like you haven't logged into it for some time, thus must have been deactivated and removed. That being said, once approved from security team, we can recreate and elevate privs (upon approval).

**Comment by oseasmoran73** [comment]
## For AWS Access
User: David.Rowley
COR: Other
VOR: Alexa Elliot
Approval required: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Approvers will check with your VOR on your EQIP status.

Context: This request is to re-onboard for AWS (see [#29030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29030) for previous details) as well as elevated privs. Currently there are 3 members on his team with this priv

**Comment by td-usds** [comment]
There are multiple requests for the exact same thing: see https://github.com/department-of-veterans-affairs/va.gov-team/issues/43935 which lists the same thing verbatim:
> I needed access to GIDS prod. I run an update script for Brian Grub to geocode institutions and to do small queries on data if our group needs to research issues on production.

We also have confirmation that other members on this team have the required (elevated) access already.

I think it would make sense to discuss how to structure who actually runs that. I have security concerns with granting everyone on a team access to prod. That to me seems like a recipe for undesired things...

**Comment by td-usds** [comment]
> Hi Oseas, We are just trying to have more people on the team able to do this to provide support. @af-manish or @mrblanco1 are part of the Leadership team and have time constraints that prevent them to execute a script for a process our client VA EDU requires us to execute at least once a week, on demand.
> 
> I should have an AWS account. Can you help me create one? EDIT: here is a link to the approval for my aws request #29030

@dsrr47 Can you confirm that we should then first revoke said privileges from @af-manish and @mrblanco1 if they have time constraints and no longer use this access? We should be scoping _down_ who has prod access, not up.

**Comment by td-usds** [comment]
Doing some additional data calls

**Comment by td-usds** [comment]
also reached out to VOR

**Comment by mrblanco1** [comment]
Hello @td-usds - I spoke with Matt Self and I decided not to move forward with David's access request. We can close this ticket please. Thanks!
