### ISSUE TITLE
Contact Center Review for [10-10 Team - Sign as a Representative]

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#43948]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The 10-10CG online application allows caregivers for Veterans to apply for caregiver-related benefits.
This guide revision is to update the Representation documentation section with screenshots of the new screens and update the information on how they can be completed.

### Launch Date
02/09/2022

### Version Number
1.1.2

### Product Guide
[10-10CG Caregiver Benefits Application](https://docs.google.com/document/d/1W5v3i8YePIK1UFwVGnyVJAE-lZ2sCbPi2OM_jUrsHqM/edit)
[Online-10-10CG-Product-Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9144059/Online-10-10CG-Product-Guide.1.2.docx)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by markfallows** [comment]
Hi @Kimberley2019 

I just wanted to check in on this ticket since there hasn't been any traffic on it.  Did I create something incorrectly, or are there others that are supposed to be assigned?  Please let me know.

Also, I made a very minor edit to the product guide to incorporate a small feature that's been added, a checkbox for the Primary and Secondary Caregiver(s) to reuse the Veteran's address if they live together.

Thank you!

**Comment by starlow00** [comment]
Hi @hdjustice or @markfallows The guide looks good. I only added a title page. Check it out, and if this looks good, I will share with VEO. Thanks!
[Online-10-10CG-Product-Guide_1_1_2_srt_07222022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9172403/Online-10-10CG-Product-Guide_1_1_2_srt_07222022.docx)

**Comment by markfallows** [comment]
HI @starlow00 this looks good to me.  Thanks for getting back to us!

**Comment by starlow00** [comment]
No changes from VEO. Posting copy here, closing.
[Online-10-10CG-Product-Guide_1_1_2_srt_07222022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9213572/Online-10-10CG-Product-Guide_1_1_2_srt_07222022.docx)
