### ISSUE TITLE
STEM: Review artifacts

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4394]
- [x] Wizard flow
- [x] Process flow for 1995 Application
- [x] Content Docs
- [x] Document notes, Q’s for stakeholders on GH page

- [x] TM
- [x] CC
- [x] AK

**Comment by ccruzgra** [comment]
Discovery artifacts: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/stem/research/wizard-update/discovery-artifacts

Looks like the last 1995 application process flow we have does not include the STEM questions.

**Comment by ccruzgra** [comment]
Updated process flow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/research/wizard-update/VA%20Form%2022-1995%20with%20STEM%20Process%20Flow%20122419%20v0.3.pdf
