### ISSUE TITLE
[07/07/22] Add PCI resources to VEText SharePoint

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#43945]
## Description
Users have demonstrated an increased need for easier-to-access resources for all checkin features, PCI and pre-checkin, so the product support team has decided to compile all of the resources into one space for users on the VEText sharepoint.
---

## Acceptance Criteria
- [x] Add link to PCI resources in VEText SharePoint with pre-checkin materials
---

**Comment by ahicksfearless** [comment]
- Met with @djfredvs on this and decided to include clarification in the next VEText Office Hour on 7/27. 

- Also added a direct link to the top of the Pre-Check-In instructions page to PCI Enterprise Implementation Sharepoint to redirect folks if they are on the wrong page. 

- Will clarify further after 7/27 VEText call, if needed.

**Comment by lindsay-insco** [comment]
Resources on SP and next steps solidified
