### ISSUE TITLE
BETA: Data from Big Query to Domo

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#43950]
**PROBLEM STATEMENT**
Platform teams (including RTT) need an automated way of tracking health metrics in a centralized dashboard. Big Query -> Domo will be used for the health metric dashboard. RTT engineers need to learn the process of adding a dataset to big query, so that the data can be pulled into the centralized Domo dashboard.

**DEFINITION OF DONE**
- [ ] Beta dataset is defined (can be one data point)
- [ ] Data successfully imported into Big Query
- [ ] Data successfully exports from Big Query into Domo
- [ ] Steps are documented

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSP---Release-Tools-FE-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/43950?planning-poker) with ZenHub @jhonnyoddball

**Comment by jhonnyoddball** [comment]
## Recommended Domo Training

- [Domo University Knowledge Base Updates](https://domohelp.domo.com/hc/en-us)
- [Learn by Skill](https://learndomo.domo.com/pages/13/learning-home)

> Login: va-gov.domo.com

**Comment by laineymajor** [comment]
Working with analytics team to determine which of these trainings (if any) are mandatory. Our team does not have the capacity for 20 hrs of training x 2 engineers.

**Comment by laineymajor** [comment]
@jhonnyoddball I think we are good to close this one now, as you and Ian have figured most of this out. If you agree, please feel free to close.

**Comment by jhonnyoddball** [comment]
We decided to use a webhook Json connector from giithub to push data into Domo
