### ISSUE TITLE
Determine operational docs types

### ISSUE THREAD

**Issue by girldadmk** [department-of-veterans-affairs/va.gov-team#43955]
**What (did/needs to) happen?**
Access Management Team needs to review and document which operational documents are required for a smooth transition of knowledge from Spike to its undetermined home. 

**Where (did/does it need to) happen?**
Confluence

**When (did/does it need to) happen?**
Q3 

**Who (was/needs to) be involved?**
Access Management Team including PM

**Why (did/does it need to) happen?**
Allow teams to continue the mission of AMT in the event that the work we've been doing transitions to another team

**Definition of Done**
- [x] Documentation types have been reviewed 
- [ ] A list has been made on the exact documents required for the transition

**Comment by kjduensing** [comment]
Ops Docs types: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2269347882/Operational+Documentation

**Comment by kjduensing** [comment]
@girldadmk added
