### ISSUE TITLE
Keycloak "how to" guide

### ISSUE THREAD

**Issue by girldadmk** [department-of-veterans-affairs/va.gov-team#43956]
**What (did/needs to) happen?**
Access Management Team needs to create a simple to read and follow "how to" guide for Keycloack.

**Where (did/does it need to) happen?**
Confluence

**When (did/does it need to) happen?**
Q3 

**Who (was/needs to) be involved?**
Access Management Team including PM

**Why (did/does it need to) happen?**
Allow teams to continue the mission of AMT in the event that the work we've been doing transitions to another team

**Definition of Done**
- [ ] "How to" guide complete with simple table of contents and hyperlinks to external sources
- [ ] "How to" guide has been reviewed by peer for comprehension 
- [ ] "How to" guide added to Confluence

**Comment by kylesoskin** [comment]
https://vfs.atlassian.net/wiki/spaces/AMT/pages/2279014559/Keycloak+How+to+Guides

Looking for thoughts and feedback.

**Comment by girldadmk** [comment]
@kylesoskin overall I think this is looking good. Well at-least from a non-technical POV.

@calquisola and @kjduensing do you have any comments on the guide in Confluence?

**Comment by kjduensing** [comment]
Added comments.
