### ISSUE TITLE
[URL standards] URL doesn't provide clear and specific context in a few words as possible. (07.04.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43965]
#### VFS team name
Debt Resolution

#### VFS product name
Combined VA Debt Portal

#### Point of Contact/Reviewers
Jim Ryan (@jimuhh) - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
URL doesn't provide clear and specific context in a few words as possible.

### Issue Details
URL title is "summary"  which doesn't match breadcrumb or provide needed context. Parent page to "summary" is a 404

### VA.gov Experience Standard
[Category Number 07, Issue Number 04](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by Dr-Pongo** [comment]
Closing out after updates! 
[Relevant ticket and closure](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43966#issuecomment-1195487748)
