### ISSUE TITLE
STEM: Review analytics

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4396]
- Traffic from Wizard & direct to form
- Form funnel – review for STEM form behaviors (completions & abandonment)
- Collect insights and include Discovery Checkpoint
- [x] TM
- [x] CC
- [ ] AK

**Comment by amyknox** [comment]
Booz team to reach out to DEPO analytics folks for insights into Wizard tracking.

**Comment by amyknox** [comment]
@amyknox - early monday, submit METRICS story to DEPO for their help with this.

**Comment by amyknox** [comment]
From Analytics Slack (via Andrea) 

You can find avg time on page, bounce rates, and exit % here:
https://analytics.google.com/analytics/web/#/report/content-drilldown/a50123418w177519031p184334251/_u.date00=20191101&_u.date01=20191130&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePathLevel1:~2Feducation~2F,analytics.pagePathLevel2:~2Fapply-for-education-benefits~2F

And funneling for the different forms here:
https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184334251/_u.date00=20191101&_u.date01=20191130/

**Comment by amyknox** [comment]
@nedierecel - I just remembered that long ago (this past summer) we worked on an update to the 22-1995 funnel that was supposed to do a better job of tracking STEM responses.  If we could revisit this later this week (I'm out Tu/Wed), that would be really helpful!

**Comment by nedierecel** [comment]
@amyknox Thanks for the refresher on the earlier ticket to track VET TEC engagement within 22-1995. Correcting my statement in our Slack thread--we are capturing radio selections for form 22-1995 upon submission of the form.

I worked on a funnel today to review users who selected "Yes" to the STEM question in 22-1995 and then proceeded to complete Form 22-0994 whether in the same session or another session. We can review when you return. 

CC: @jonwehausen

**Comment by amyknox** [comment]
@nedierecel - great news. Thanks for looking into this.  Do you have time on Friday that we could review this info?

**Comment by amyknox** [comment]
From Jon Wehausen via Slack

Confirmed the request is to understand engagement with the radio buttons that dropdown after clicking on the "Find your education benefits form" green call-to-action button. Analytics is currently not tracking activity with those. 

Put story 4497 in the backlog to support this need.

**Comment by nedierecel** [comment]
@amyknox Jon has a conflict today, but we're both free Monday, 12/6 at 12:30-1 EST. Please advise if your team is free next week. Thanks!

**Comment by amyknox** [comment]
@nedierecel - that works for us.  Please send an invite for that time.  Look forward to chatting with you both.
