### ISSUE TITLE
STEM: Research Plan

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4397]
- [x] Draft research plan for STEM scholarship interviews
- [x] Review with UX team
   - [x] CC
   - [x] TM
- [x] Share with recruting firm NLT Dec 30, 3:30pm

**Comment by amyknox** [comment]
Draft in progress here: https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/education-careers/stem/research/wizard-update/research-plan.md

**Comment by ccruzgra** [comment]
Reviewed plan and shared back with Amy Knox earlier today.
