### ISSUE TITLE
SOCKS access for Lynn Stahl

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-team#43980]
### Your Name

Lynn Stahl

### Your Email

lynn.stahl@agile6.com

### Your Role and Team

Sitewide CMS Engineer 

### Product Manager (PM) name and email

Erika Washburn erika@cityfriends.tech

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDoGBgY//Md1qqxzkanUD6Tmga3pkZlrxxDtf9TaKwW151ieb598SNSrrPbPcdcPq17iRG4QAXKoW++TjWaZMpRCUcYaqhe+5tMMK6yDQb7jzC2rPRCnp6ZM/eDfA2ENDOCCVBnyI2q/PrWCtLNTJAsYVj1LXld9o2wJux0+LcAd2xSv7gY6GjY1ENKZXnbRbjmU1xATO8KQ/ma6lIATFJIYNtQmeazd/VdBlKqiEPnhkoCdXN4yTSyKyory9zkMOnysIEpEA/zF7Aoh/VJsfNq7EEzKOHl2NXWTaatvXhy+hjxVZPis7hafd74c1RqYFrO2Vu2L7JbZno1ZJCmI5I6xGk4YZv9jNIlOUiUgSEpbE4tCAzyVJgTrK5QJObE+KLKk22Mc3lJVKMwNPEHDSSwPnYs0eL2sXAdqUxiO8V/wLWdRKs0eVLWmAkeY2Zdzb+W7nfR79UGRpFmi5B3RNo1PlaZGEq4Pzl877pYdCToSFl6oTyEC5SQoPgaLRiKioE= lstahl@Agile6-A76

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
Thanks Lynn, I'll kick off the process manually.

Found @msbtterswrth in VFS Platform Roster.

**Comment by kjduensing** [comment]
@msbtterswrth - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by msbtterswrth** [comment]
Confirmed access to prod is restored! Thank you!
