### ISSUE TITLE
STEM: Recruiting

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4399]
- Reach out to recruiting team for awareness & scheduling
    - 12/23: will require thought into the profile of users to engage for people who are not currently eligible for STEM Scholarship
- STEM Scholars with >6 months of benefits
- People who are changing schools

**Comment by amyknox** [comment]
DEPO and Perigean report no changes to typical process for recruiting over holidays.

**Comment by amyknox** [comment]
Submitted recruiting request 12/30.

**Comment by ccruzgra** [comment]
@amyknox Looks like we can close this now that we're starting to get participants scheduled by Perigean.
