### ISSUE TITLE
Migrate Jenkins master

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#440]
Jenkins will move to utility VAEC network.

Some changes that we will need to make in order to move this in smoothly:

- get rid of the iptables rule that forwards traffic from 80 to 8080
- setup nginx to listen on 80 with a redirect for the old URL to new
- swarm node master IP would need to change
- test ssh access for Ansible through current jumpboxes

**Comment by wyattwalter** [comment]
Not planning on doing this.
