### ISSUE TITLE
Caution Flags: Collect artifacts 

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4400]
- [x] DEPO patterns
- [x] Review slack, github
- [x] Document any addition notes, q’s for stakeholders in GH

**Comment by ccruzgra** [comment]
No artifacts identified in Slack or Github. 

Github document for capturing notes/q's for stakeholders: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/research/caution-flags/discovery-artifacts.md
