### ISSUE TITLE
Process for the day the PACT Act passes

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#44015]
**1. Wait for official approval and the go-ahead to begin publishing.** OPIA or VHA should provide a "tick tock" (a run-down of what goes live when). We need to make sure we follow the order and publish pages when it's our time to go.

- **Note:** Once we have a date/time, check in with the CMS and Platform support teams to let them know that this will be an urgent, critical content release and we need to make sure that we have people monitoring.

**2. Alert OCTO that we're going to publish.** Tag Lauren Alexanderson, Zach Goldfine, Dave Conlon, Beth Potts, Chante Lantos-Swett, Emily Theis, and Luciana Morais in slack as an FYI.

**3. Update the date for the law passing in all content.** Replace all "July XX, 2022" with the real date.

- **Note:** Team to do audit of all the places where we have a XX for date now.

**4. Publish the ["The PACT Act and your VA benefits" R&S FAQs page](http://preview-prod.vfs.va.gov/preview?nodeId=47278).** Validate that it's live.

**5. Email OPIA (Gary, Gary, Josh) to let them know that they can publish the homepage banner.** Reconfirm the link to the live "The PACT Act and your VA benefits" page.

**6. Post in the VHA Daily Pact Act channel** to let them know that "The PACT Act and your VA benefits" page is live.

**7. Publish the alerts.**

**8. Publish the existing page updates.**

**9. Email VHA and VBA partners to confirm that all new pages and updates are live.**

**Comment by RLHecht** [comment]
@megzehn Can you put a list in a comment here of all the pages and alerts that have the July XX, 2022 date? It would be good to have these all in one place so we know where we need to update the day we are going to publish. Thanks!

**Comment by megzehn** [comment]
Yes!  Here are all the articles I looked at with PACT copy mentioned: 

Has alert box: 
* Exposure to hazardous chemicals and materials: http://preview-prod.vfs.va.gov/preview?nodeId=873
* Health care eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=31
* Priority groups: http://preview-prod.vfs.va.gov/preview?nodeId=708 
* Active-duty service members: http://preview-prod.vfs.va.gov/preview?nodeId=1005
* Operation Enduring Freedom Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=15
* Iraq War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=13
* Gulf War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=12
* Cold War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=11
* Vietnam War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=16
* Eligibility for VA disability benefits: http://preview-prod.vfs.va.gov/preview?nodeId=871
* Agent orange exposure: http://preview-prod.vfs.va.gov/preview?nodeId=874
* Ionizing radiation exposure: http://preview-prod.vfs.va.gov/preview?nodeId=886


Has placeholder dates in text:
Gulf War Illnesses, Afghanistan - http://preview-prod.vfs.va.gov/preview?nodeId=884 (talks about PACT Act, but does not have placeholder date text in it)
Exposure to burn pits and other specific environmental hazards - http://preview-prod.vfs.va.gov/preview?nodeId=889 (has placeholder date - June 16, 2022)
Gulf War Illnesses, Southwest Asia - http://preview-prod.vfs.va.gov/preview?nodeId=885 (has placeholder text in “more helpful information” section)

**Comment by DanielleThierryUSDSVA** [comment]
@megzehn @RLHecht @laurwill 

2 additional things to look for:
- It's looking like we should replace any instances of "millions of Veterans" to "tens of thousands of Veterans" for now. Definitely keep a look out for whether that changes in evolving materials.
- We need to change any instances of "family members" or "families" to "survivors."

I made these changes in the main alert. But if you could please look for these throughout the content, that would be much appreciated!

And here is the link to the [content matrix and status tracker ](https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/EZIzEk3zOCdFnpJQmAX0XNgBw0fk4SbxiYLG9XTp7IAIaA?e=FwLbpA)just to make sure you have that. Everything is up to date in that.

**Comment by RLHecht** [comment]
Closing out this ticket now that PACT Act has passed!
