### ISSUE TITLE
Caution Flag: Review analytics

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4402]
- Research traffic on schools with flags 
- Lookup via institution code
- Dev support = schools w caution flag

- [x] TM
- [ ] CC
- [ ] AK

**Comment by amyknox** [comment]
@ccruzgra - this is a story you could dig into on 12/31.  Dustin or Matt may be able to help you identify schools with caution flags, then you could look to see if they're getting more or less than average # of pageviews in the GIBCT.

**Comment by amyknox** [comment]
Schools with multiple (the most!!) caution flags

24902428 - Art Institute of Las Vegas:  Probation or Equivalent or a More Severe Status: Warning (Significantly out of compliance - student achievement), Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible, Heightened Cash Monitoring (Financial Responsibility)

31702364 - Argosy University - Hawaii: Probation or Equivalent or a More Severe Status: Show Cause (Significantly out of compliance - fiscal and administrative capacity), Loss of Title IV Participation, Assigned receiver has motioned court for an emergency closure of compus. ImmInent closure is a distinct possible, Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible, Heightened Cash Monitoring (Financial Responsibility)

**Comment by ccruzgra** [comment]
@amyknox https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/research/caution-flags/institutions-with-caution-flags-v0.1.xlsx

Anything else we can include before we close?

**Comment by amyknox** [comment]
@ccruzgra - with the udpated excel sheet, I think we're good. Close this story!!
