### ISSUE TITLE
Platform Tool Integration Research

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44026]
**What (did/needs to) happen?**
Researchers from Console UI have provided us with a list of the most used platform tools. In conjunction with our estimate of integration ease, this research could indicate platform tools that have the highest value to VFS teams. By integrating platform tools with high value first, we can provide immediate impact to VFS teams. We need to review the research, document our notes based on conversations with the owners of the identified platform tools, and prioritize a list of tools to integrate. We also need to communicate this list to at least the Console UI team, in order to avoid doing more work that necessary in this shortened quarter.

**Where (did/does it need to) happen?**
Confluence, Zenhub

**When (did/does it need to) happen?**
Q3 

**Who (was/needs to) be involved?**
Access Management Team 

**Why (did/does it need to) happen? How does it move the needle?**
1. Integrating high-value tools provides faster and greater value to VFS teams
2. Documenting the research and our intentions allows teams to continue AMT's work in the future

**Comment by ewilson-adhoc** [comment]
By the way @kjduensing IET has been working on something similar with an eye to microservices -- its still very much a WIP, but can be found here (https://vfs.atlassian.net/wiki/spaces/IET/pages/2241003742/Vets-API+Migration+Plan+Supported+Tools)
