### ISSUE TITLE
Implement updates from "test" Manage debt landing page to existing Manage debt landing page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#44020]
## What's needed

We created a "test" Manage debt landing page for the combined debt experience. We now need to implement the updates from that page into the real, existing Manage debt page in preparation for launch of the next phase of the combined debt experience.

**Important note:** Make these changes, but do not publish now.  Hold for launch.

**Test page:** http://preview-prod.vfs.va.gov/preview?nodeId=46933

**Existing page:** https://prod.cms.va.gov/manage-va-debt

After we move the test page updates into the existing page, we can archive the test page.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Let me know if you have questions about this ticket. Also, can you create an epic for all tickets in support of the combined VA debt experience next phase launch? Thank you!

cc @denisecoveyduc

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! 

@RLHecht, I'm leaving this in draft until we get the green light, but confirming here that it has been copyedited.
