### ISSUE TITLE
Provide recommendations on using service prioritization framework

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#44047]
## Story
As a platform stakeholder I would like to understand how to use the service prioritization framework so that I can use it to rank the value of different services so that I can make informed decisions about which services should be developed next. 

## Acceptance Criteria 
- [x]  The [microservices prioritization famework](https://vfs.atlassian.net/wiki/spaces/IET/pages/2054684691/Vets-api+Microservice+Framework) is reviewed for clarity
- [ ] The work done by IET so far (Sidekiq UI, File Upload, Virus scan) are run through the framework to and the prioritization process is explained
- [ ] This should be accessible on confluence.

**Comment by FHiatt** [comment]
Cleaning up the parameters and layout of doc ect
