### ISSUE TITLE
[BE] [Discovery] Review "Veteran Not Found in MPI" Errors

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44056]
We've been asked to review the *Veteran Not Found in MPI* errors for the 10-10CG online application to determine if there's any root cause or issues that we can address to either eliminate the error or reduce its frequency.

**Comment by hdjustice** [comment]
Current breakdown as of this ticket's creation
![image](https://user-images.githubusercontent.com/92328831/178040150-4b282ba4-0cb6-4dcd-ba82-0afa4e318090.png)

**Comment by batemapf** [comment]
i think this can be closed in favor #44464

**Comment by markfallows** [comment]
@hdjustice After reviewing the numbers, it doesn't look like there's an actual percentage spike in *Veteran Not Found* errors.  Do you agree with closing this ticket in favor of working on logging the transaction IDs, instead, so they can be reviewed in the event of problems in the future?
