### ISSUE TITLE
Access Management Executive Summary

### ISSUE THREAD

**Issue by girldadmk** [department-of-veterans-affairs/va.gov-team#44050]
**What (did/needs to) happen?**
Access Management Team needs to create a single page executive summary outlining the high level work accomplished during PST.

**Where (did/does it need to) happen?**
Confluence

**When (did/does it need to) happen?**
Q3

**Who (was/needs to) be involved?**
Access Management Team including PM

**Why (did/does it need to) happen?**
This executive summary is intended for those not well versed in the impact made by AMT. The intended audience is not technical. Why does this move the needle? PST AMT is proud of the work accomplished in the last ___ months, and we want to showcase that work in a summary format. This document will be referenced when decision makers consider the future of AMT.

**Definition of Done**
The document is written and reviewed by AMT. The document should be peer reviewed by another PST or platform team for comment. Once both are complete and edits are made, the document will be posted in Confluence. 

Includes

- [ ] History of AMT and how we move the needle
"We provide Identity for those how work on VA.gov"
"One way in and one way out"

- [ ] Research blurbs 
1. VFS platform tools priority vs effort 
2. VFS developer onboarding journey

- [ ] How we worked to **Centralize**

- [ ] How we worked to **Streamline**

- [ ] How we worked **Transition**

- [ ] Key wins such as:
1. SOCKS automation
2. Self-hosted runners
3. DevOps privileges 
4. Research

- [ ] Future of Access Management

**Comment by kjduensing** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Access-Management---Platform-Spike-Team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/44050?planning-poker) with ZenHub @calquisola @iriteshp @kylesoskin

**Comment by girldadmk** [comment]
@kjduensing I started to create a framework for the executive summary. 

https://vfs.atlassian.net/wiki/spaces/AMT/pages/2294317057/AMT+Executive+Summary
