### ISSUE TITLE
FE | Profile | Military Info | Add GA for New Endpoint

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44075]
## Background

This is for the front-end work corresponding to ticket #43755. The back-end ticket provides a field to distinguish traffic from the old endpoint (eMIS)to the new endpoint (VA Profile).

## Tasks
- [ ] Add tasks here that must be completed

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - this is the ticket for the FE GA work needed to support the Military migration tracking. Let me know if we should move any of the "update alerts" tickets as this is a higher priority.

**Comment by SKasimow** [comment]
@adamwhitlock1 - I've opened #44075 for the FE work and slotted for upcoming Sprint 78

**Comment by SKasimow** [comment]
@adamwhitlock1 - I think this can be closed as it looks like the work was done in #43087. Can you confirm?

**Comment by adamwhitlock1** [comment]
This still needs to be done, since we implemented the general events before we had decided to add this new 'data source' to the events

**Comment by adamwhitlock1** [comment]
@SKasimow I think we can call this validated, since we are seeing sources in GA now.

**Comment by SKasimow** [comment]
agree!
