### ISSUE TITLE
Comments entered with requests do not display in Schedule Manager

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#44071]
see https://issues.mobilehealth.va.gov/browse/VAOSR-3818. We are not sure if this is a front end issue or a back end issue or both. 

 To test, I entered requests in VAOS, and looked at what reason text was captured in the payload. In all cases, the text WAS captured correctly. 

Then I looked at the requests in SM. In all cases, the "Additional Information" field was missing from the SM gui. Older requests do show this field; recent requests do not. I also looked in developer tools in SM and saw that the reason code and text were there; but the GUI is not displaying them. Furthermore, the field names used in dev tools in SM are different than the names used in VAOS. In Vaos, it's ReasonCode and ReasonCode.txt; in SM it shows as purposeOfVisit and otherPurposeOfVisit. 

Marcy Nadeau comments via slack:
Just a quick FYI.  We have a blocker issue for prod deployment.   VAOSR-3818  VAOS: patient reason free-text is not persisted if the reason code is set. * Veteran's Reason for Appointment comments are not being displayed in SM to the staff user.

Talked with Kay and these comments could contain critical information that the veteran wanted to provide to the scheduler so this is why it has to be fixed before Prod deployment. 
And SQA can't tell if issue is F/E or B/E. 
See attached spreadsheet, requestText.xls, and screen shot, SVCCommentsNotDisplaying.png

[https://app.zenhub.com/files/133843125/314676fa-99d4-4a42-ade9-527645f5115c/download](https://app.zenhub.com/files/133843125/314676fa-99d4-4a42-ade9-527645f5115c/download)
![SCVCommentsNotDisplaying.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/14491105-bedd-413d-af9b-59e536727a90)

**Comment by ldelacosta** [comment]
This will be handled by the VAMF team. No work is needed for FE. Closing out the ticket.
