### ISSUE TITLE
**Discovery** Profile | Personal Info Revisions | UAT | Document Preferred Name Validation Rules

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44082]
## Background

2 participants mentioned that restrictions for how to enter Preferred name - such as character maximum and not allowing all special characters or limiting capitalization to the first character - may cause issues for some Veterans (ie: **A**nn- **M**arie).

## Tasks
- [ ] Document what is and isn't permissible today in the preferred name field

## Acceptance Criteria
- [ ] Review findings with PM and Designer

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @tpharrison @adamwhitlock1  - we recently discussed some of the limitations to types of entries that could be used in Preferred name field (ie: no numbers, character limits, tildes are supported).

**Comment by tpharrison** [comment]
Hi @SKasimow - you can assign this to me.

**Comment by SKasimow** [comment]
Thanks @tpharrison . I put into the upcoming Sprint (Sprint 78) but we can adjust if needed.

**Comment by tpharrison** [comment]
@SKasimow - I've added the validation rules for preferred name [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/README.md#preferred-name-validation-rules).  I discussed the capitalization issue with Ian McEwan (from VA Profile) and he stated that MPI applies the capitalization so we'll have to loop them in a discussion about this.

@andaleliz - let me know if there is a better place to put these rules.

cc/ @Samara-Strauss @adamwhitlock1

**Comment by SKasimow** [comment]
Thank you @tpharrison - this is super helpful and glad you made the rules part of our documentation.

@Samara-Strauss @cgednalske - let me know if we want to pursue the capitalization issue (or any other limitations). From my PoV, it would be helpful to see the type of feedback we get over a period of time and which limitations are most bothersome to users.

**Comment by andaleliz** [comment]
@tpharrison I think that's a great place for now. Thanks for writing this up!

**Comment by Samara-Strauss** [comment]
This is great, and the documentation is in the exact right place! I don't think we need to have any further conversations with MPI at this point.
