### ISSUE TITLE
Fix DataDog synthetic test steps

### ISSUE THREAD

**Issue by rbeckwith-oddball** [department-of-veterans-affairs/va.gov-team#44096]
## Problem
- Exporting our synthetic browser tests to Terraform code leaves the browser steps out of order, which requires us to manually reorder them.
- Terraform and/or DataDog also will not accept changing of the `allow self signed` option via the API

## Proposed solutions
- Find a way to avoid manual edits best as possible

**Comment by pjhill** [comment]
I'm still hunting for an appropriate place to stash this code. Perhaps it would be best to carve out a subdirectory in `devops` with a README explaining the contents and the purpose?

**Comment by pjhill** [comment]
@rbeckwith-oddball is currently creating a PR in `devops` to store this workaround and documentation.

**Comment by rbeckwith-oddball** [comment]
@pjhill - here is said PR https://github.com/department-of-veterans-affairs/devops/pull/11578

**Comment by rbeckwith-oddball** [comment]
There were a few false alerts in the automated code scanning upon submitting the PR. I have commented on the alerts and dismissed them since they are technically false positives.

**Comment by pjhill** [comment]
It looks like there are some comments on the PR that infrastructure needs us to address before they'll approve that PR. Let's get it knocked out -- so close!

**Comment by rbeckwith-oddball** [comment]
Addressed the comments in the PR and just submitted the changes. We will also be the codeowners of this new directory.

**Comment by pjhill** [comment]
We're there!
