### ISSUE TITLE
remove prod IGW from old network

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#441]
## Description

In the pre-VAEC environment (terraform env dsva-vetsgov-prod), we had IGW's that allowed access to the Internet for our VPN backhaul to the TIC. Since we've moved to VAEC, this IGW _should_ no longer be in use, but we need to just go through the work to delete it.

I believe all of these are gone, but we need to confirm there's no EC2 instances or Lambda functions on that VPC. If so, let's check flow logs and security groups for any access to confirm no traffic is going across it or allowed to. Then, we can delete it.

## AC

- [ ] IGW from old prod network is no longer in AWS

**Comment by ricetj** [comment]
Last update: This work is currently in-progress and should have an update within a week.

**Comment by wyattwalter** [comment]
This is not actionable yet as we still have a dependency that needs it. Once all the services are moved to VAEC we can action this.
