### ISSUE TITLE
Adding Michel Mcdonald to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#44104]
Good afternoon,

I am requesting Michel Mcdonald be added as a Multi-Channel user to the DSVA Slack workspace.

Email: michel.mcdonald@adhocteam.us
Channels: 
Va-claims-appeals 
Vsa-benefits-nod 
Appeals-api

Thank you!

**Comment by LEHigley** [comment]
michael mcdonald is showing as a full member already
