### ISSUE TITLE
[FE] 10-10EZ - Medicare Claim number: Add new Claim number field to Insurance Info page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#44106]
## Background
As per request from HEC team/Stacey Echols, the Medicare Claim number is needed by downstream systems to assist in billing processes and tracking.  This field will also be added to the paper form, which we will coordinate our release on 8/8.
We need to add a field on the [Insurance Info - Medicare page](https://staging.va.gov/health-care/apply/application/insurance-information/medicare) to capture the "Medicare Claim Number".  This field is alpha-numeric and **will not** have input validation for having exactly 11 characters.

**Note: We will not be validating this number against any Medicare database for valid coverage**

- See ticket #44112 for Backend details
- See [ticket #33561](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/33561) for content background, as well as the links below for designs:
     - The claim number field [now has an expandable info alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ygw2kK8)
     - The [open expandable info](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/eKeE8dq)
     - The [closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbpzrqd) and [open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/wLqej1V) error states.

---

**In case you are interested, Here is the information from Joshua in regards to the request:**
>it just goes in the policy  number field just like a private insurance; we map it to claim number on the backend if the type is medicare
>
```
<ns2:insurance>
                <ns2:companyName>Medicare</ns2:companyName>
                <ns2:enrolledInPartA>true</ns2:enrolledInPartA>
                <ns2:insuranceMappingTypeName>MDCR</ns2:insuranceMappingTypeName>
                <ns2:partAEffectiveDate>12/03/2006</ns2:partAEffectiveDate>
				<ns2:policyNumber>7AD5WC9MW60</ns2:policyNumber>
            </ns2:insurance>
```

## Tasks
- [ ] Update [Medicare page](https://staging.va.gov/health-care/apply/application/insurance-information/medicare) to include Medicare Claim number field below the Medicare Effective Date question
~Ensure the field validates the input for exactly 11 characters **(THIS IS TBD, pending discussion with Patrick)**~
~Ensure that a validation error appears to indicate what is needed for the field **(THIS IS TBD, pending discussion with Patrick)**~
- [ ] Ensure that the question and the field can be read by a screenreader appropriately for the page

## Acceptance Criteria
- A new Medicare Claim number field is added to the Insurance Info page

**Comment by nicko-amida** [comment]
@longmd @lzapson Hey all - there's been a slight update to the content of the [medicare claim content](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/eKeE8dq): "The VA uses" is now "We use", in the content under the additional info component.

**Comment by hdjustice** [comment]
@nicko-amida @longmd @lzapson - After discussing the 11 character length validation, it is decided that we will not implement that.  We will leave it as a free-form field with the guidance indicating that it is an 11 alpha-numeric input.
I also discovered that the number used to be the person's SSN.  All new cards were sent to Medicare enrollees, however some may still think they need to put their SSN in there

>**[Link to background](https://secure.ssa.gov/poms.nsf/lnx/0600901040#:~:text=The%20Centers%20for%20Medicare%20%26%20Medicaid,Medicare%20cards%20in%20April%202018.)**: The Centers for Medicare & Medicaid Services (CMS) developed a new number called the Medicare Beneficiary Identifier (MBI), which replaces the SSN-based Health Insurance Claim Number (HICN) on the Medicare card. CMS began mailing the new Medicare cards in April 2018

cc: @markfallows  @batemapf

**Comment by longmd** [comment]
@hdjustice / @markfallows / @batemapf , this might be a REALLY silly question. But considering the events of last week, I may as well go ahead and ask. Even though WE are not going to validate for the 11 characters, is the downstream system going to have that in place and reject the data? Is that something we need to confirm with them or has that already been confirmed with them?

**Comment by hdjustice** [comment]
@longmd  I don't think that has been confirmed, but I also don't think that is a silly question at all.
I sent an email requesting how we might coordinate a bit of testing on the American Indian and Medicare number fields, so I can follow up with this as well.

**Comment by hdjustice** [comment]
@longmd - Joshua confirmed that the field has a max length of 30 characters.

**Comment by longmd** [comment]
@hdjustice , That makes sense. So we should then validate for a 30-character maximum then. Agree?

**Comment by hdjustice** [comment]
Yes, we can match the enrollment system to avoid any unintended rejections.  Thank you @longmd !

**Comment by longmd** [comment]
@nicko-amida , do you have a preference on a message for this field being a maximum of 30 characters?

**Comment by longmd** [comment]
@nicko-amida , disregard. The way the input works is it doesn't even let you exceed 30 characters. So we're good... no message necessary.

**Comment by longmd** [comment]
@lihanli , just wanted to give you a heads up that there is a new version of the schema that has been merged in that added the maxLength declaration to this field.
