### ISSUE TITLE
[Spike] Determine if historical endpoint traffic data is available

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#44114]
## Story
As a member of the IET team, I would like to be able to access data from the last 6 months to determine what endpoint traffic is like.

## Acceptance Criteria 
- [x] Determine if there is a way using available tools to collect historical (~last six months) of endpoint traffic.
- [ ] If there is not. Write an RFC for a solution, because this seems like it would be valuable to have. 
- [x] If there is, document the process for accessing these tools and getting this data.

**Comment by considerable** [comment]
Here is [Prometheus query](http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=1h&g0.expr=sum(increase(api_rack_request_duration_count%5B1d%5D))%20by%20(controller)&g0.tab=1) that was used to sample the endpoints traffic in the past

**Comment by ewilson-adhoc** [comment]
Using grafana, we should be able to get historical logs for the system, provided that we log endpoint access -- but we we will need to figure out how to parse them. Logs exist from the end of September 2021 is when this migration occured, we should have logs up to the end of that time period

**Comment by ewilson-adhoc** [comment]
To verify: 
- write the query to get the usage of feature flipper for the last 6 months.
