### ISSUE TITLE
[UX] Interview Travel Clerks at Bay Pines & Corpus Cristi

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44115]
## Problem Statement
We would like to interview <person's name> regarding .....

## Related Documents
See list of questions generated here........

## Acceptance Criteria
- [x] Identify person to lead the interview
- [x] Identify at least one note taker
- [x] Perform Interview
- [x] Take notes
- [x] Post de-identified notes to GitHub

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/tx-valley-interview-notes.md
