### ISSUE TITLE
Aggregate & Collect down time data for external services

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#4415]
## Problem
In our current architecture we do not aggregate or store down time experienced by external services (outside of vets-api).  As we work towards building dashboards to expose these metrics, the first step will be to identify the external services and the metrics required, aggregate that data for a period of time so that we can easily view/report on this data.

## VSP Q1 + Q2 2020 OKRs
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

## Details and Notes
This task will require that we have a mapping of vets-api endpoints to external services.

**Comment by LindseySaari** [comment]
As a start: We currently have "uptime" metrics (percentages) for our backend services by endpoint. The data may need to be aggregated for a longer period of time. http://grafana.vfs.va.gov/d/000000050/backend-service-report?orgId=1
