### ISSUE TITLE
Research & Design Orientation Session - August 2022

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#44158]
## Issue Description
Hosted the Research & Design Orientation Session for VA.gov Platform on 8/1/2022.

---
## Tasks
- [x] Host the session and answer any questions that come up.

## Acceptance Criteria
- [x] We have provided a General Orientation session for VA.gov Platform for August 2022.

**Comment by seanasewell** [comment]
@chaseakirby @shiragoodman I checked off the task and acceptance criteria. Can we close it now?

**Comment by chaseakirby** [comment]
@seanasewell Thanks Sean! I added the Sprint so this is good to close.

**Comment by claytonzook** [comment]
@chaseakirby The issue description says "General Orientation" Does it matter that doesn't match up with the ticket title?

**Comment by chaseakirby** [comment]
@claytonzook Good catch Clayton! I updated it just it doesn't potentially confuse us in the future.
