### ISSUE TITLE
[FE] 10-10EZ Enable Short Form in Production

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44167]
Once final approval has been received from stakeholders, the Short Form will need to be enabled in production.  The details of that rollout are:
- Initial phased launch date: 07/25/2022
- Initial phased population: 5%
---
- Second phase launch date: 07/27/2022
- Second phase population: 100%

**Comment by markfallows** [comment]
Moved and added to the appropriate sprints.

@longmd @lzapson You can use this ticket to track adding activating the short form in production.

cc: @hdjustice

**Comment by longmd** [comment]
@markfallows / @hdjustice , the short form has been activated to 5% of logged in users!

**Comment by hdjustice** [comment]
ack! I cannot contain my excitement
