### ISSUE TITLE
Update Contact Center Guide to Include American Indian Question, Medicare Claim Number Field, and SIGI Changes

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44165]
The Contact Center guide needs to be updated to include any changes involved in the *American Indian* question, *Medicare Claim Number field*, and *Self-Identifying Gender Identity* addition.

These then need to be submitted to the Contact Center for review.

**Comment by markfallows** [comment]
American Indian question has been added to the [10-10EZ Product Guide](https://docs.google.com/document/d/1K0k49Yb4MVfOsWZ6xp1zSC7uE1vpcQSE/edit#).  Feel free to review for any additional changes.

Will process further updates once the Medicare Claim Number field is available.

**Comment by hdjustice** [comment]
American Indian question has been removed, per Business Policy.  The Self-identifying Gender Identity question is still on hold pending business decisions.  Medicare claim number field will be updated with Household Section Optimization guide updates
