### ISSUE TITLE
Rails Engine vs Gems Discovery

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#4416]
## Problem

We are currently using Rails Engine to power our front end applications which the platform team is supporting, which means we support all the FE applications utilizing it.  This increases our PR load and complexity to support each team (and will grow as more VFS teams are added to the platform).  Ultimately we want the application team to be responsible for the development and support of their own app without having to rely heavily on the platform team.

What would happen if we used Gems instead of Rails Engine?  What would the app look like if we wrote it today instead of 3 years ago.

## VSP Q1 + Q2 2020 OKRs 

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

**Comment by kfrz** [comment]
I'd argue this doesn't need to be an epic. It should be a single discovery issue which then would result in a formal problem statement and proposed solution. The discovery could include both research and an RFC.

Additionally, I think it would be less fitting for O1 and more for O5 

> O5: All customers comply with the Platform's standards.


@alexpappasoddball @johnpaulashenfelter @annaswims

**Comment by alexpappasoddball** [comment]
@johnpaulashenfelter need a ticket for sprint 17 on this one!
