### ISSUE TITLE
Change all OCTO Crew Leads to OCTO Crews

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#44176]
## Issue Description
We updated the field of OCTO Crew Lead to be OCTO Crew instead. We need to change the values that exist in the product list to the crews instead of the crew leads. This document can be referenced for information: https://dsva.slack.com/files/UL39HR399/F03D0HNBAKU/digital_experience_team_of_teams_slides_-_04-26-22_final.pptx

---
## Tasks
- [x] Update all OCTO Crew lead values in product-directory.json to be the corresponding OCTO Crew.

## Acceptance Criteria
- [x] All COTO Crew Leads in product-directory.json have been changed to reflect the corresponding OCTO Crew.
---

**Comment by rjohnson2011** [comment]
PR created and in review https://github.com/department-of-veterans-affairs/product-directory/pull/367

**Comment by rjohnson2011** [comment]
PR open -> https://github.com/department-of-veterans-affairs/product-directory/pull/367
