### ISSUE TITLE
Analytics KPI dashboard update request for [10-10 Health Apps]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#44171]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [x] **Forms**: funnel changes - **Going live in August (8/8)**
- [ ] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here: [10-10 EZ American Indian funnel update - Spreadsheet ](https://docs.google.com/spreadsheets/d/1xhVBs54ba5RSmrQKVSSgYnDgVJrxwkNe/edit?usp=sharing&ouid=114633463412960989242&rtpof=true&sd=true)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
     - **I added Chloe, not sure who else on the team I can add to view the spreadsheet**
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by hdjustice** [comment]
@markfallows - here is the analytics ticket to update the funnel for American Indian

**Comment by michelle-dooley** [comment]
@hdjustice and @markfallows - thank you for your request.  We will include this in our next sprint starting next week.

**Comment by chloedotbrown** [comment]
Thanks, @hdjustice and @markfallows! We'll create a new version of the 10-10EZ form funnel including the "American Indian" and "Document Upload" steps, and set it to start collecting data starting August 8th. If anything changes before then, please let us know!

I'll confirm here once the changes are made. We'll likely wait to close the ticket until after this has launched though, just so we can give it a quick QA once the new page is live.

**Comment by hdjustice** [comment]
That sounds great!  Thanks so much for your help with this!

**Comment by markfallows** [comment]
Hi @chloedotbrown 

Just wanted to give you a quick heads-up on this one.  We're going to be pushing this feature live to a very small population come this Monday (7/25) with a larger rollout tentatively scheduled for this coming Wednesday (7/27), pending successful results with the small population.

**Comment by chloedotbrown** [comment]
Thanks for the heads up, @markfallows! We'll start using "version 3" of the 10-10 form, which includes the new steps starting next week. The dashboard updates once a week, so you'll start seeing data for the new steps the following Monday (8/1). If you have any questions - or there are other changes - just let us know!

**Comment by chloedotbrown** [comment]
Hey @markfallows and @hdjustice - following up to see if the launch dates for this version have changed? I was QAing the data, but I'm not seeing any activity on the new "American Indian" step in GA or BigQuery. 

If you could let me know before the weekend, that would be great, so that we pull the correct current version on Sunday's update. Thanks so much!

**Comment by hdjustice** [comment]
Hi @chloedotbrown - the comment above was for a different feature (Short form).  Sorry about the confusion.  This American Indian work is still scheduled to go live on 8/8.

**Comment by chloedotbrown** [comment]
Ah got it - thanks @hdjustice! I'd ben thinking, this is a _very_ busy launch week for your team! I'll reset the American Indian start date to 8/8. I'll leave this ticket open so our team can QA once data starts coming in.

**Comment by michelle-dooley** [comment]
Hi @hdjustice - Just checking in, did the American Indian release go live on Monday?

**Comment by hdjustice** [comment]
Hi @michelle-dooley - The American Indian question was not released on Monday as planned.  There was a last minute decision to pull it from the release due to additional review of the question language.  We do not have a release scheduled at this time.  My apologies, I meant to notate this sooner.

**Comment by markfallows** [comment]
Hi @chloedotbrown, the *American Indian* step isn't in production just yet.  We've had to delay it a little bit to go over the verbiage.

**Comment by hdjustice** [comment]
@chloedotbrown @michelle-dooley - We are finally ready to release the American Indian question.  It was confirmed in staging today and good to go!!  We should see volume coming through this afternoon!

**Comment by markfallows** [comment]
Should this still be in the Icebox?

**Comment by michelle-dooley** [comment]
@markfallows - I do see some activity....
[GA report](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20220901&_u.date01=20220926&explorer-segmentExplorer.segmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&explorer-table.secSegmentId=analytics.eventAction&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22health-care~2Fapply~2Fapplication~2Fveteran-information~2Famerican-indian%22,0%5D%5D)
![image](https://user-images.githubusercontent.com/93597659/192293042-3f4643ce-5cde-4fda-80ce-2aba07f71ffa.png)

**Comment by chloedotbrown** [comment]
Hi all - I'm reopening this ticket, because we actually need to do some work on our end to make sure the new step is captured on the dashboard. I'll update here once changes have been made. You should see the new funnel version that includes the American Indian step next week when this week's data has been added.

**Comment by hdjustice** [comment]
Thank you @chloedotbrown - Let us know if you need anything.

**Comment by chloedotbrown** [comment]
Thanks @hdjustice! BigQuery updates have been made, so closing this ticket out. You should see this as a new "V3" option in your funnel and exit rate tables starting next week.

**Comment by hdjustice** [comment]
awesome, you are a gem @chloedotbrown!  Thank you, thank you.. a thousand times Thank You!
