### ISSUE TITLE
Adding Shoaib Sheikh to DSVA Slack

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#44184]
# Description

Please add Shoaib Sheikh (Sheikh_Shoaib@bah.com, Shoaib.Sheikh@Va.gov) as a full member to DS@VA slack space with initial presence in the following channels:

#vfs-evss-service-migration
#va-forms
#vfs-all-teams
#vfs-benefits
#victories
#oncall
#general
#random
#vfs-platform-builds
#vfs-platform-support
#vsa-ebn-migration
#va-letters
#benefits-team-1
#evss-prod
#evss-devs
#va-mobile-app
#accountexp-authexp

**Comment by LEHigley** [comment]
@NCHLiberty what email address would you like me to use?

**Comment by NCHLiberty** [comment]
hI. The BAH email address would be more convenient for Shoaib. Thank you
