### ISSUE TITLE
Chat about IA for Claim Status Tool (Claims vs. Appeals)

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#44180]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

Benefits Team 1 is working on improvements to the Claim Status Tool. In reviewing the current UI, I've noticed that there is a different IA and overall design approach to showing the status for _claims_ vs _appeals_. I've attached some screenshots to illustrate the distinction. 

I have a hypothesis that the current appeals version is better for meeting known user needs, but I'd like to get more context about the history of these pages to see if there's anything else I should know before moving forward.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
TBD
  
## Supporting artifacts

**Current UI for appeal status** 👇

<img width="699" alt="Appeals1" src="https://user-images.githubusercontent.com/95102058/178510251-3154431e-695b-4ae0-9672-3fb921f2d0bc.png">

**Current UI for claim status** 👇

<img width="566" alt="Claims1" src="https://user-images.githubusercontent.com/95102058/178510709-4680bdad-b892-49c5-a345-1a4296db2d4e.png">

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD
- Estimated staging review date: TBD
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits Team 1
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
-	FE engineer: Jerek Shoemaker
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

**Comment by mnorthuis** [comment]
Hi @skylerschain! This tool has been around since before my time, and I am the original IA on VA work! A team long, long ago created this and it hasn't really been given solid design love in quite some time (that I am aware of), so there likely isn't anyone around that can provide deep background as to why the two scenarios are designed differently.  I would say your best bet is to start with Matt to understand the differences in flows, processing, and data...which was likely at least part of the driving factor.  Any TLC your team can give this would be great, its due for an upgrade!

**Comment by bethpottsVADEPO** [comment]
@skylerschain Please keep @RLHecht in the loop on this work so we can get a content team member involved to ensure alignment with plain language standards.

**Comment by skylerschain** [comment]
Sounds great! Thanks all I will ping this ticket to connect with @RLHecht if/when we move forward.

**Comment by mnorthuis** [comment]
@skylerschain Do you anticipate any work in this area in the near term, or can we close this specific issue out?

**Comment by skylerschain** [comment]
@mnorthuis I think we can close this for now, no immediate action needed on this. Thanks.
