### ISSUE TITLE
Document Strategy to Iterate API V0 to V1 for vets-api

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#4418]
# Problem
There is currently no official strategy or guidelines around creating new (V1) endpoints.  Without a defined strategy we will certainly run into issues with existing apps utilizing deprecated end points.  There needs to be clear guidelines to when and how a new (V1) endpoint is created, when and how existing apps switch where they point, and when that old end point is deprecated.

## VSP Q1 + Q2 2020 OKRs 
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

## Measuring Success

# Details and Notes

### Areas for Discovery

**Comment by kfrz** [comment]
A few thoughts for further discussion:

- V1 should only really be used if we introduce a breaking change. As our api doesn't really follow semantic versioning in the codebase, though this may be somewhat moot.

- Should V1 even be a Rails API? Do we have an argument for migrating to a different architectural pattern altogether? Is this worth talking about?
