### ISSUE TITLE
Scope: EVSS Incident Playbook and FAQ for issues with external services.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#44192]
Description

The following [slack thread](https://dsva.slack.com/archives/C8R3JS8BU/p1657584408641269) identified the need to have a playbook or PagerDuty alert for issues with external services.

Tasks
- [  ] Create Playbook and FAQ for identifying issue with external services. 

Example: [issue with EVSS](https://vagov.ddog-gov.com/dashboard/znd-bmt-vby/vets-api-breakers?fullscreen_end_ts=1657641614431&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1655049614431&fullscreen_widget=8791707030772932&from_ts=1657637999220&to_ts=1657641599220&live=true)

**Comment by alyssagallion** [comment]
@rmtolmach Assigning to you to see if there are any other considerations/tasks we need to accomplish. Trying to stick to this format:

- Description
- Definition of Done
- Tasks to complete

**Comment by rmtolmach** [comment]
From Alyssa
Here are the two notes I had from our Incident Commander for things to update in the documentation. Let me know if ya need anything from me!
Edit documentation to give examples of Incident Types (i.e. DataDog) before any other content on page
What is an incident?
What types are there?
Here's how to handle them!
When to escalate to Tier 2 (automatically does if you don’t acknowledge within 30 minutes)

**Comment by rmtolmach** [comment]
We don't want a PagerDuty alert for EVSS, or any other external service. They are not actionable on our end, so we don't want to be alerted for someone else's service. 

I also don't think any more documentation is necessary :/ There is a section in the [Incident Playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook#Check-Downstream-Services) about downstream services and mentions EVSS and where to go to check maintenance windows. 

In the Slack thread linked from the description, Lindsey reached out to the #evss-prod channel when she saw some EVSS errors that were not scheduled. That is the recommended approach.
