### ISSUE TITLE
AWS access for Oleksii Morgun

### ISSUE THREAD

**Issue by oleksii-morgun-va** [department-of-veterans-affairs/va.gov-team#44203]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Oleksii Morgun

### Your Email

oleksii.morgun@va.gov

### Team, Role, and Company of the target individual

MHV Secure Messaging, Front End Engineer, By Light Professional IT Services

### Product Manager (PM) name and email

Lichelle Bain - lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Desired AWS Access

Requesting the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers

### Access Expiration

ongoing

### Additional Notes

COR: Sean Good
Vendor Onboarding Representative: Kenneth Brown
Access Expiration: Need ongoing access to upstream data APIs in lower environments for VFS development activity

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mleclerc00** [comment]
@oleksii-morgun-va 

I was unable to find you in the vfs/platform roster please see 

If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html

**Comment by mleclerc00** [comment]
User found in vfs team roster

## For AWS Access
User: Oleksii Morgun
COR: Sean Good
VOR: Kenneth Brown
Approval required: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

**Comment by td-usds** [comment]
@oleksii-morgun-va can you be more specific which Kenneth Brown? Can you provide their VA e-mail address

**Comment by td-usds** [comment]
Reach out to VOR

**Comment by mleclerc00** [comment]
Passed account information to user, closing ticket
