### ISSUE TITLE
Pre-Check-in: Handle 4 Modalities (i.e. CVT, VVC, phone, in-person)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44210]
## Background
We have been asked to enable Pre-Check-in for all VA modalities, these include:
- In person (already enabled)
- CVT
- VVC
- Phone

## Wireframes
[CVT](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=239-863&mode=design)
[VVC](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=239-862&mode=design)

## Resources
[Telehealth icons & content matrix](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7-484&mode=design)
[Modalities Priorities matrix](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704222770597/330fb18069c0f3d4b54db4125b81052990dc80c4?sender=uc584f7fcc9a5090000259578)
[Meeting notes with Shawn](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/cvt-appointments/meetings)

**Comment by benbrasso-agile6** [comment]
@loripusey https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw?node-id=7:484&locale=en&type=design
