### ISSUE TITLE
Answer these CST load time questions

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#44215]
- [x] Polling delay potentially defaults to 5 seconds, is there a reason for this time (which is very long)? Task: Ask EVSS about rate limiting.
- [x] It looks like the same request gets made multiple times (possibly, need to investigate more)... is this occurring accidentally in the JS? Task: investigate and debug.
- [x] Would it be possible to create some custom API points for consolidated requests? Task: ask EVSS and/or Lighthouse.
- [ ] Is there a reason that requests come back without the syncStatus set to SUCCESS when they seem to contain the full data already (this may be a staging thing, but would be good to confirm the reason)? Task: investigate and debug.
- [ ] Is there a way to get load time metrics from production? Is this being logged somewhere already? Can we use a test account that runs in production?

**Comment by jacobworrell** [comment]
@samcoforma for any investigation that yields a possible debug opportunity please communicate with the team async as soon as those possibilities emerge, so we can determine whether they're worth pursuing during the sprint.

**Comment by samcoforma** [comment]
@jacobworrell Will do. Those may turn into vertical slice tickets of their own pretty soon after I confirm.

**Comment by samcoforma** [comment]
Question: What is a good way to track and benchmark asynchronous calls? We need to verify that GA does this properly. Also investigate Google Lighthouse. Discover if there is an industry standard here outside of these two tools.

**Comment by samcoforma** [comment]
Tasks: 

- [ ] Gather questions for Lighthouse, and send over to them before the 21st
- [ ] Gather feature requests for Lighthouse, and send over to them before the 21st

**Comment by samcoforma** [comment]
- [ ] explore blames in the code for rate limiting to see potential rationale, if it's been commented on
- [ ] request documentation for rate limiting from EVSS or Lighthouse

**Comment by samcoforma** [comment]
Moment that polling went from 1s interval to 5s interval: https://github.com/department-of-veterans-affairs/vets-website/commit/fb62d5efc48ca35b0e8d2e88b75b13b88763f872

**Comment by sortizsh** [comment]
Closing this because we're moving this to a synchronous call
