### ISSUE TITLE
Configuration for Source-App-Name Header Whitelist

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#4421]
## The Problem
`vets-api` currently maintains a whitelist of `Source-App-Name` header values. These values are generated within `vets-website` (using `yarn apps`). These two sources of truth are not connected in any way and will diverge over time.

## Additional Context
`vets-website` includes a header in each API request named `Source-App-Name` with a value that represents the front-end app that is making the API call. E.g.

```
Source-App-Name: dashboard
```

The value of this header is being read inside a middleware and sent to `StatsD` + `Prometheus` for metrics gathering. If this value is not in the whitelist, then the header is ignored.

See PR: [link](https://github.com/department-of-veterans-affairs/vets-api/pull/3645)

## Work to be Done
- [ ] Draft RFC for solution

**Comment by LindseySaari** [comment]
Initial Thoughts:
Have redis store a roster of source app names similar to StatsDMetric for whitelist names
Unsure on solution for obtaining this whitelist from frontend, any thoughts?
