### ISSUE TITLE
[Story] Update verbiage to the school accreditation section

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#44228]
## Issue Description
To update the verbiage in the  "School accreditation"  section on the comparison tool cards. 

---
## Tasks
- [ ] _Update new verbiage to cards when information is provided.  _
- New verbiage will be provided by Cinda.  
 
![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/34bf1870-388b-4c67-832a-3551d2d2fe36)

**Updated: 07/18/2022**
Please update the below verbiage to the pictured designated spot. 

**Wording for updated accreditation box:**

**CAUTION:  Not every program approved for GI Bill benefits at an accredited school is accredited by the regional or national accreditor.  Prior to enrolling, it’s important you confirm the program you’re seeking is accredited and whether or not your field of study requires accreditation for employment and/or licensing.**  

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/679a0f59-6f47-4bf3-b60a-f63b0dea112d)

**Comment by hallihocine** [comment]
Ticket has been validated in staging: new verbiage is added to the accreditation box. See screenshot: 
<img width="684" alt="Screen Shot 2022-07-19 at 2 02 36 PM" src="https://user-images.githubusercontent.com/86266024/179823561-c145f45c-c0bd-4323-82da-582d60de690e.png">

**Comment by hallihocine** [comment]
Test Run: 
https://dsvavsp.testrail.io/index.php?/runs/view/3418&group_by=cases:section_id&group_order=asc&group_id=5614
Test Steps: 
[Update verbiage to the school accreditation section.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9143775/Update.verbiage.to.the.school.accreditation.section.xlsx)

**Comment by MitchLivingstone** [comment]
**Update: 07/25/2022**
UAT Approved by Brian Grubb.

**Comment by MitchLivingstone** [comment]
Completed and Done 07/28/2022. 
Released into production
