### ISSUE TITLE
[Design] Profile - Explore removing alert and input messaging on notifications page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#44229]
The alert on the page for first time UX, and the input messages on the radio buttons were designed to support the KPIs for our MVP. 

We're no longer tracking those, so I wonder if we can revisit having those on the page. It would clean up the UI if we could eliminate those.

This ticket will track work needed to evaluate how it might impact the notification settings page if we remove these components.

**Comment by SKasimow** [comment]
@liz - do you want to consolidate this work with the 1095b notification mocks ticket?

**Comment by andaleliz** [comment]
@SKasimow yes, I'd love to!  [The mock-up I created to add the 1095-b preference](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/5zZvbp/a/WK8xJy8) shows how it would look without the alert + input messaging.

But there's something I wrote in the description that's confusing me:

>This ticket will track work needed to evaluate how it might impact the notification settings page if we remove these components.

What else do we need to evaluate from the design side? Maybe something with analytics?

@cgednalske or @SKasimow  any recollection? If not, I think the rest of the evaluation would be on the FE side.

**Comment by SKasimow** [comment]
@andaleliz - I took the comment below to refer to needing to track what other implications have to be considered. Front-end work, changes/updates to analytics....

>This ticket will track work needed to evaluate how it might impact the notification settings page if we remove these components.

**Comment by SKasimow** [comment]
@andaleliz - are we just want to get a swag from Adam on FE work? If so, this would be a perfect topic to cover in grooming!

**Comment by andaleliz** [comment]
Yes, I think so. Let's talk about it in grooming.  I'm not sure how to evaluate impacts to analytics - is that something you can tackle?

**Comment by SKasimow** [comment]
Sounds good.  Yes I can look into what's being tracked and make sure changes won't impact ability to report. We can also set a baseline to ensure that changes are +

**Comment by SKasimow** [comment]
@andaleliz - should the UI mirror the page today once notifications are set:

![Notif Pref After Set.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/e35dc132-8ea1-4a4c-b145-ffedbe1ef96c)

**Comment by SKasimow** [comment]
@andaleliz the updated mock done for 1095B asks for email address and I'm not sure if that is a new field or something we show today if someone doesn't have an email address on file (can't find a staging act to check)

>[The mock-up I created to add the 1095-b preference](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/5zZvbp/a/WK8xJy8) shows how it would look without the alert + input messaging.

**Comment by andaleliz** [comment]
Hi @SKasimow no, we wouldn't see it this way with any staging accounts since we don't currently have any email notifications. And we have a gate on the whole feature if there's no mobile number on file (since we couldn't send a text without a mobile number)

The FE logic _may_ already be written to handle this since we originally were going to launch with both email and text notifications, but I'm not totally sure.

**Comment by SKasimow** [comment]
@andaleliz - we touched on this earlier today; think we can close theses I have a FE ticket opened for the dev work #45957.

**Comment by SKasimow** [comment]
@andaleliz - actually I think we need an updated mock (without the 1095B info) showing a screen a) before a user sets any notification preferences and 2) after one/some are set. I was looking at sketch and wasn't sure if we intend to use existing design for scenario a and want to have a clean mock for scenario b.

**Comment by andaleliz** [comment]
@SKasimow you're right - I can work on this this sprint.

**Comment by SKasimow** [comment]
@andaleliz thanks! do you want me to open a new ticket for the mocks?

**Comment by andaleliz** [comment]
@SKasimow no, we can just use this one. Thanks for checking!

**Comment by andaleliz** [comment]
@SKasimow here are the [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/JnL7n1b) and [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8z08VJ) mock-ups. I think we can close this out now :)

**Comment by SKasimow** [comment]
@andaleliz thanks! Do we also need one for when we don't have a user's mobile phone number on file?

**Comment by andaleliz** [comment]
You're welcome @SKasimow! We have that already and nothing should change about what we have today. This ticket was focused on the state of the page when we do have contact information on file.
