### ISSUE TITLE
[SPIKE] [BUG] Research how a Veteran may have received both a system not operational message from CHIP and a second message with a link to start their check-in.

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44240]
## Background
This bug was witnessed during research efforts at Bay Pines. Fairly certain it was at Bay Pines VAMC Building 100 3D (General Surgery, Vascular Surgery, Plastics, Podiatry). 

This particular clinic was not using PCI due to the MSAs needing to print routing sheets from VistA upon check-in. The way they managed this was making all patients check-in with the MSA vs. using PCI. No posters were up at this location. However, we were told by HAS training staff that PCI was enabled for this clinic. So, we hung up a poster and a Veteran immediately used it because there was a long line. In speaking with MSAs, we realized that there current process does not support this because they don't have a way of printing the routing sheets when a patient uses e-checkin. We did validate that that patient did appear in VSE. We then took the check-in poster down. 

The Veteran received two text messages. One that the system was not operational. But they also received a check-in link. The patient successfully checked-in. 

## Task
Research how a Veteran may have received both a system not operational message from CHIP and a second message with a link to start their check-in.

**Comment by loripusey** [comment]
@benbrasso-agile6 add notes to this ticket

**Comment by benbrasso-agile6** [comment]
@acrollet I updated the description

**Comment by loripusey** [comment]
@acrollet did you make any progress on this? If not, I am inclined to stick it back on the backlog.

**Comment by acrollet** [comment]
I spent a bit of time but didn't make much headway, it might honestly make more sense as a request to the VEText team.

**Comment by acrollet** [comment]
Let's revisit if we get another report with enough information to find specific logs.
