### ISSUE TITLE
Playbook for Sidekiq Queue Issues

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#44253]
Tasks
- [  ] Create a playbook for [reviewing Sidekiq queue](https://api.va.gov/sidekiq/queues) issues and various external services that may be the root cause.

**Comment by rmtolmach** [comment]
We have a section on this page: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2599289071/Backend+how-to on how to run a sidekiq job. We will continue to update documentation as needed.
