### ISSUE TITLE
Finalize call center documents and video with hybrid MVP designs 1095B

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44266]
- [x] Complete content for call center documents reflecting 1095-B hybrid MVP
- [x] Create call center video using prototype mock-ups from approved sitewide content IA designs for 1095-B hybrid MVP
- [x] Socialize with VA-PO
- [x] turn over video and documents to call center
- [x] Discover if any additional items are needed for call center review.

**Comment by CarlDickerson** [comment]
@starlow00 @tameracorson I've reshot the product video for 1095-B to include the updates made to the landing page for accessibility. Attached is the new product video walking through the 1095-B download functionality.https://themostudio.zoom.us/rec/share/VZCtcCYOfiUUys2qtrZPhjt74btico84JBnFwZGdTCIvnSYMJPaMCIQYsOcPqPDd.8AgdB8ewGxeIkFbj?startTime=1658498497000
Passcode: 6AyV+3WC

**Comment by tameracorson** [comment]
@CarlDickerson Do you have the updated product guide reflecting current designs and the video transcript?
