### ISSUE TITLE
Version hybrid design for mobile

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44274]

**Comment by tameracorson** [comment]
@tmccue Can you please place direct link to **final mobile design** here and also a **snip & sketch picture**?

**Comment by tmccue** [comment]
https://www.sketch.com/s/2f061f33-42de-4d8f-83ad-40286632ba36

<img width="320" alt="image" src="https://user-images.githubusercontent.com/103584877/180317611-71f69a14-0c6f-4c80-9703-02f3e4f08f4b.png">

<img width="320" alt="image" src="https://user-images.githubusercontent.com/103584877/180317723-b80649bd-aef0-42bb-af42-e916e2aaa94a.png">

**Comment by tameracorson** [comment]
@tmccue Please drop link to individual mobiles in the link you put goes to the 1095-B file and there are tons of designs.  I need to link to correct design for deliverables.  Please drop link to 1) Mobile hybrid MVP - ONLY

**Comment by tameracorson** [comment]
@stephte @khandelwal above, design on the left is the mobile design for our accessible hybrid MVP... ignore the one on the left that has opt-in for now,

**Comment by tameracorson** [comment]
Unauthenticated Mobile Design https://www.sketch.com/s/2f061f33-42de-4d8f-83ad-40286632ba36/a/YGaL1xQ

**Comment by tameracorson** [comment]
Authenticated Mobile Design https://www.sketch.com/s/2f061f33-42de-4d8f-83ad-40286632ba36/a/VrO5pKl
