### ISSUE TITLE
Customer Support KPI Tracking - per VSP Team 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4427]
## Problem Statement

How might we implement tracking of customer support for VFS teams, so that we can identify areas with high burdens of manual support for improvement and so that we can track volume of support by team and practice area over time? 

## VSP Objective (Q1 & Q2 2020)

O4: All of the Platform’s KPIs are easily measured and shared openly.

## Measuring Success (KRs/KPIs)

- [VSP KR] It takes < 1 hour to compile KPI reports
- [VSP KR] At least 2 KPIs tracked by each VSP team
- VFS Customer satisfaction over time
- % of manual support that gets automated

### Links

- Super epic for [Ongoing Service] Global Customer Support #3675

### Goal(s)

- Standardize tracking of customer support for VFS teams so that we can begin to measure this support by team, by practice area, and over time

### Assumptions and Hypotheses

We **assume** that the burden of tracking support should fall primarily on VSP, so that we can maintain the current low barrier for VFS teams to interact with us. 

We **hypothesize** that **if** we standardize tracking of customer support across all of VSP, **then** we will be able to identify “problem areas” with high burdens of manual support to be prioritized in future VSP initiatives.

## Areas for Discovery

- What shortcut can we create to implement quick issue tracking in ZenHub? A GitHub/Slack integration? Something else? 
- What labels are currently being used across the VSP ZenHub? Are there unused labels we can delete? Are there misused labels we should clarify?

## Definition of Done

- [ ] Issue creation and labeling standards are defined for VSP customer support
- [ ] Support issues can be tracked by VSP team members in approximately 2 minutes or less (GitHub/Slack integration or other shortcut is in place)

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this since it's no longer needed.
