### ISSUE TITLE
Build prototype of hybrid MVP

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44273]
- [x] Turn over prototype to Carl for use in call center video

**Comment by khandelwal** [comment]
![image (1).png](https://images.zenhubusercontent.com/601ace099a3aea67f627f313/c27f3fc4-8e10-42b5-90d9-fe3a104756dc)

**Comment by tameracorson** [comment]
@tmccue can you please place the **direct link to the finalized prototype build** here and if possible **screen shot or snip & sketch picture**?

**Comment by tmccue** [comment]
https://www.sketch.com/s/1f2a2fbd-8d48-47c6-8e95-b26d5259a211

**Comment by tameracorson** [comment]
@tmccue same on this ticket.  When I punch link I'm dropped in a file board and am forced to select from several prototypes.  Can you please drop only the link for the correct prototype? ![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/6bb3722c-daf5-416d-8f4e-912e1e287653)

**Comment by tameracorson** [comment]
https://www.sketch.com/s/1f2a2fbd-8d48-47c6-8e95-b26d5259a211/prototype/a/2F852299-DA7F-44DC-82E2-3B5CEC399F05
