### ISSUE TITLE
Documentation - Update user story template to address QA pain points

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#4430]
**Problem Statement**
VFS QA does not receive robust user stories with user scenarios and flows full defined which leads to testing . gaps.

**Goal**
Update the [user story template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/user-story-template.md) to provide QA with sufficient information to successfully create e2e test cases for every user path.

**Objectives**
O5: All customers comply with the Platform's standards.

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this issue since it's no longer needed.
