### ISSUE TITLE
[AWS][GHA] On-demand runners are not cleaning up correctly

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#44319]
## Description

On-demand runners are not cleaning up correctly when retry occurs. If it is successful, then it will clean up that last successful one

## Background/context 

[Repo](https://github.com/department-of-veterans-affairs/ec2-github-runner)

If you search in instances up and running in EC2, you will find on-demand runners that have not been spun down

![image](https://user-images.githubusercontent.com/10648480/178813828-3c40bd6f-d0a9-4883-8be6-a8f9d4487964.png)

---
## Tasks
- [ ] If on-demand runners fail, all instances spun up should be properly shut down and terminated

## Acceptance Criteria 
- [ ] Content-build workflow properly cleans up on-demand runners

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/ec2-github-runner

**Comment by oseasmoran73** [comment]
Adding [slack](https://dsva.slack.com/archives/CQH357ZTP/p1657741989805019) convo

Would be great if we can get this prioritize in the next sprint or two @laineymajor

**Comment by mydesignrocks** [comment]
update: all the workflows tied to content-build are migrated over to either self-hosted/asg or ubuntu-latest (github runner) with the exception of content-release. We are working with the respective teams to address the runner definition for the content-release in this sprint. That should resolve the requirement of this ticket.
In the meantime, we will terminate the lingering unused ec2 on-demand runners, manually.

**Comment by olivereri** [comment]
This can likely be closed to due to work in these issues:

Conent-build no longer uses on-demand runners:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11402

126 orphaned On-demand Content-build runners terminated:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11405

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/github-user-requests/issues/15404 issue request here with GitHub opened to archive this repository.

**Comment by CBonade** [comment]
This was archived by the GitHub team so ready for closing.
