### ISSUE TITLE
Documentation site - iterate on large file support solution

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4432]
## User Story

As a team member building on or in support of VA.gov, I need a place other than GitHub to host large files, so that I can share design, video, and other large files with my team members and publicly. 

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov. 

## Measuring Success (KRs/KPIs)

TBD

### Links

- [Current LFS guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/repo-guidelines.md#large-files)

### Assumptions and Hypotheses

- We **assume** that VSP should determine where VFS teams should host files.

**Comment by vbellissimo** [comment]
Cancelling/old task.
