### ISSUE TITLE
Finalize research plan #2 - moderated testing of trees

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44323]

**Comment by MOStudioCarolyn** [comment]
https://docs.google.com/document/d/1g3hpSTXIDQW_nD2rzwC8JTyFZkveLoaY4gOWxAD0fH0/edit#

**Comment by MOStudioCarolyn** [comment]
Edits from Mikki
[https://app.zenhub.com/files/133843125/644b4849-d611-4e96-bc95-8d6f8813dcaf/download](https://app.zenhub.com/files/133843125/644b4849-d611-4e96-bc95-8d6f8813dcaf/download)
