### ISSUE TITLE
Prep for review of research with VFS-IA Mikki

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44325]

**Comment by MOStudioCarolyn** [comment]
[Uploading... HH-Design Review - Sprint 6 -July 22.pdf]

**Comment by MOStudioCarolyn** [comment]
[https://app.zenhub.com/files/133843125/730411bb-2b4c-47a7-a14f-18deed24b43c/download](https://app.zenhub.com/files/133843125/730411bb-2b4c-47a7-a14f-18deed24b43c/download)

**Comment by MOStudioCarolyn** [comment]
[https://app.zenhub.com/files/133843125/677ab425-3b90-432a-8c43-bfd32f9e0e84/download](https://app.zenhub.com/files/133843125/677ab425-3b90-432a-8c43-bfd32f9e0e84/download)

**Comment by MOStudioCarolyn** [comment]
[https://app.zenhub.com/files/133843125/f820e41d-9aa2-48cd-a0b8-814e9b7384b4/download](https://app.zenhub.com/files/133843125/f820e41d-9aa2-48cd-a0b8-814e9b7384b4/download)

**Comment by MOStudioCarolyn** [comment]
Revised findings.

[https://app.zenhub.com/files/133843125/6e182fba-6a32-41b1-a687-65cdca6a928f/download](https://app.zenhub.com/files/133843125/6e182fba-6a32-41b1-a687-65cdca6a928f/download)

**Comment by MOStudioCarolyn** [comment]
Revised findings after Mikki's feedback

[https://app.zenhub.com/files/133843125/ecb8a8c0-27a6-40f8-8902-fdcc9c8c596c/download](https://app.zenhub.com/files/133843125/ecb8a8c0-27a6-40f8-8902-fdcc9c8c596c/download)
