### ISSUE TITLE
address validation modal radio button selection disappears (again)

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4433]
![movie.gif.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/bfb4fe58-5291-4c81-81cd-a849be2c96e6)

**Comment by erikphansen** [comment]
Can @artistgreen @Justin-Pickett or @Samara-Strauss confirm that the radio selection buttons work again? I'd fixed them but then another change broke them again. They should be all good now.

**Comment by Samara-Strauss** [comment]
It's not working for me. The Suggested Address radio button was filled in, but then the blue circle in the radio button disappeared when I clicked the originally entered address.

**Comment by erikphansen** [comment]
awesome, the site isn't building in Jenkins so new stuff hasn't rolled out for at least a couple of hours

**Comment by Samara-Strauss** [comment]
OK, so should I check back later?

**Comment by erikphansen** [comment]
yeah I'll ping you

**Comment by erikphansen** [comment]
@Samara-Strauss this works on staging now

**Comment by Samara-Strauss** [comment]
Validated!
