### ISSUE TITLE
Contact Center Review | Profile Team | Bad Address Indicator

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44330]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

The name of the project is "Bad Address Indicator". When mail is sent to a Veteran and then returned to the VA, the address is marked as "bad" in VA Profile. The address may very well be a real, valid address, but the returned mail implies that it is no longer the right address for the Veteran for whom the mail was intended. 

This effort is intended to make users aware that they should check their mailing address and ensure it is up-to-date.

### Launch Date
*Please provide the launch or rollout date and details.*

TBD - targeting late Aug/early Sept

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
*Please provide product guide link*
Latest version can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/product)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - @cgednalske and I have put together info on BAI for the Contact center guide. I thought that before I move it over into the full guide, it would  be easier to have you review and comment 
in this [google doc](https://docs.google.com/document/d/1I1LuXnckeisg2s5si40uaOS27RxaqaoiEM6SiMzt_CI/edit#heading=h.nlifrg8e46pm)

**Comment by Samara-Strauss** [comment]
Great! I just requested access. Once I have it, I can review the updates.

**Comment by Samara-Strauss** [comment]
Reviewed! It looks good, but I would remove the terminology "bad address indicator" entirely from this guide. That is internal lingo we don't need to surface to the call center. I made a couple comments as such in the guide itself, but I did not flag every instance of "bad address indicator", so please be careful in reviewing.

**Comment by SKasimow** [comment]
@starlow00 - attaching our updated Profile product guide with BAI internal name only) starting at page 31:

[Profile product guide v5.1](https://app.zenhub.com/files/133843125/a0ad9cb7-27a4-4cc1-97a2-b3a586493181/download)

**Comment by starlow00** [comment]
@SKasimow It looks good, I will forward to VEO

**Comment by starlow00** [comment]
No changes from VEO. Attaching copy here. 
[VA_gov_Profile_v5_1_09072022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9586642/VA_gov_Profile_v5_1_09072022.docx)

**Comment by SKasimow** [comment]
Hi @starlow00 - adding updated file (v 5.2) below:

[https://app.zenhub.com/files/133843125/002ed988-f818-4f12-8208-7c987a4d24d4/download](https://app.zenhub.com/files/133843125/002ed988-f818-4f12-8208-7c987a4d24d4/download)

**Comment by SKasimow** [comment]
Hi @starlow00 - sorry for the delay; here is the updated Profile CC product guide:

[Uploading... VA.Profile.Product.Guide.version.5.2.docx]

**Comment by starlow00** [comment]
No changes from VEO. Approved copy v5.2 attached here. 
[VA_gov_Profile_v5.2_09232022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9669457/VA_gov_Profile_v5.2_09232022.docx)

**Comment by SKasimow** [comment]
@starlow00 Thanks Steve! Did you make any formatting changes or edits? If so, I want to use your version as "final" and work from this one in future so you don't have to re-edit anything :)
