### ISSUE TITLE
Create Console content review workflow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44342]
Acceptance Criteria:

- [x] Meet as a team to determine recommended console content review process
- [x] Create service blueprint/workflow of how content on the console will be reviewed by our team (This will not include the support intake process, since this may be owned by another team).

Mural: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1658930919439/6f43924874384e4b82557b1ad53b278a5247997f?invited=true&sender=u9d01ee38af217e4877e75660

**Comment by lhelmer** [comment]
@jchapin @rbsingleton Feedback on the mural draft process

**Comment by rbsingleton** [comment]
@vbellissimo - I provided feedback on both the product outline and copy review workflow. Please let me know if you need any clarification on anything I wrote!
