### ISSUE TITLE
Ideas for Console content style guide

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44343]
**User Story**

As a platform team member building new functionality for the Console UI,
I need to review content-specific guidance from the Platform Content team,
So that I can make sure there aren't any major content concerns by the time the feature is launched.

**Acceptance Criteria**
- [x] Identify what is unique to the console content that could be added to existing style guide
- [x] Incorporate team notes onto Team confluence space - Not ready to be formally added to the "external" style guide to other Platform teams

Internal checklist: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2297495799/Ideas+for+Console+content+style+guide

**Comment by laucon** [comment]
1. I think we should mention next to our capitalization rules in the style guide that these rules apply to both documentation and microcopy on both the Platform site and the Console.

**Comment by vbellissimo** [comment]
8/9/22 brainstorming session for team to be scheduled

**Comment by laucon** [comment]
https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1660153014730/6f092dad44a50f0021b66a64d8f4a69eb9b2252b?sender=ubdee4da0d43b2aac59d21482

**Comment by laucon** [comment]
https://vfs.atlassian.net/wiki/spaces/~6218e48cc34549007199170b/pages/2312568920/Console+style+guide+brainstorm+results
