### ISSUE TITLE
[SSO-Login] Standalone login page

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#4436]
**User Story**
As a Veteran receiving some or all of my health records via Cerner's portal (HealtheLife), I need a login URL so that I can sign in from one centralized location even if I try to access HealtheLife directly.

**Comment by RayShapouri** [comment]
Is this for SSOi as well or just SSOe?

**Comment by christine-dillman** [comment]
This work has been completed.
