### ISSUE TITLE
[SPIKE] Brainstorm Delivering Login/General Errors Up the Chain to Staff-Facing Applications

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44360]
## Background
Shawn Adams brought up the issue where there exists a "MULTIPLE BIRTH INDICATOR" field that can indicate that there are multiple DOB values for a Veteran. Since CHIP API provides us with only 1 DOB value for each patient, there exists the possibility that a Veteran can enter a DOB that fails verification because that is not the one that we have in LoROTA. Shawn mentioned that it would be nice if we could bubble up login and other error messages to the staff-facing applications so that MSAs can better determine why a Veteran was not able to use Mobile Check-in or Pre-Check-in and know how to help them.

See [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1657740925284699)

## Tasks
- Brainstorm the feasibility of this proposal
- Discuss findings with the Team

**Comment by loripusey** [comment]
@acrollet @randomsync  I went ahead and pulled this into this Sprint, but it was not in our Sprint goals so if you don't have time to get to it we can roll it over. It's here though if the FE or BE team needs some additional work.

**Comment by loripusey** [comment]
@loripusey reach out to Shawn Adams to gauge importance

**Comment by acrollet** [comment]
@loripusey could we gauge priority on this during our sync on thursday? It's likely to be v high effort.

**Comment by acrollet** [comment]
@loripusey should we consider this closed as part of the work done in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54021 ?

**Comment by loripusey** [comment]
sounds reasonable, closing
