### ISSUE TITLE
Revisit deployment time of day

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44373]
Acceptance Criteria:

- [x] Meet as a team to decide new process

Socialize the change:

- [x] Determine HOW to communicate this message (platform confluence, slack, specific slack channels for developers who contribute to the Platform, etc.); Also reference the Communications playbook recommendations: https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1927675936/Platform+communications+playbook+-+Guidelines 

- [x] Make updates, send messages

Message:
The Platform Content team updates the live Platform website twice per week on Tuesdays and Thursdays. The deadline for any new or updated pages to deploy on the live Platform website is 3:00 p.m. ET. Barring any launch-blocking issues, all pending changes will go live by 5:00 p.m. ET.

Slack channels: (Amy)
#platform-confluence
#platform-content
#vfs-all-teams

**Places the time will need to be changed:**

- [x] The #platform-confluence channel, like the screenshot I attached below

**Confluence documents:** (Samara)

- [x] New user guide: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2263187457/Submit+content+edits+on+the+Platform+to+be+deployed
- [x] This internal document of ours: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+website+deployment+instructions
- [x] Create a new platform website document: https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page

**Places we will need to share update:**

- [x] Slack channels (Amy)
- [x] Demo announcement (Amy)
- [x] Team of Teams (Vicky)
- [x] Documents listed above (Samara)

**Comment by vbellissimo** [comment]
**Places the time will need to be changed:**

- [ ] The #platform-confluence channel, like the screenshot I attached
- [ ] New user guide I created: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2263187457/Submit+content+edits+on+the+Platform+to+be+deployed
- [ ] This internal document of ours: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+website+deployment+instructions
- [ ] Create a new platform website document: https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page

**Places we will need to share update:**

- [ ] Slack channels
- [ ] Demo announcement
- [ ] Team of Teams

**Comment by vbellissimo** [comment]
Amy - To share Slack messages on Monday 7/25
Samara - To update on documents on 7/22

**Comment by SSimmorins** [comment]
Hello Vicky,
the docs assigned to me have been updated.
