### ISSUE TITLE
Profile Team | Change Address Messaging Modal | Analytics Feature Request/Bug Report

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44379]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - [Insert role, team and project]

- Is this a feature request or a bug?

  - [ ] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature
- Why the feature is needed

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by michelle-dooley** [comment]
@SKasimow - did you mean to create 2 tickets for address change messaging or is this a shell that is a dupe of #44380 and I can close this one?

**Comment by SKasimow** [comment]
Hi @michelle-dooley - yes this is a dupe. There has been an issue in Zenhub where I'll try to create a ticket, get an error and so create another ticket...only to find the first one actually was created. Sorry!
