### ISSUE TITLE
[Design] Update Check-in wireframes to be up-to-date

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#44382]
Current wireframes don't match the most recent releases. And they need to be audited and then refreshed to be consistent with the latest implementation. 

Task
- [x] Update Check-in wireframes
- [x] Update the Collection (in the master branch)

Acceptance Criteria
- Updated Check-in wireframes to match the latest FE implementation
- Updated the Collection (in the master branch) with clickthrough option

**Comment by loripusey** [comment]
@zach-park Can you point this and add some AC?
cc @sarahknoppA6

**Comment by zach-park** [comment]
Point (2) is added
