### ISSUE TITLE
Profile | Address Change Messaging Modal | Analytics Custom Event Request

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44380]
## Ticket Description

After we began a phased roll-out for the "change address messaging" modal prompt, we saw 2 instances of PII being captured in the GA reports.

While the Analytics team works to scrub the PII and fix this issue (#44350) we determined that we would be better supported by having a custom event created for this modal; this provides more control over what is tracked and how the data appears in GA reports.

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

 - The Profile Team for the Change Address messaging modal project.

 - Is this a feature request or a bug?

  - [x] Feature request
  - [ ] Bug report

## Request/Report Description

We are requesting the set up of a custom event for the profile team and specifically the "Change Address" messaging modal [sketch file here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/EL2Kvm2)

This is what we want to track:

- Event: 'int-profile-custom' (or something of that nature)
- Title: text we can pass in for title or other identifying info 
- Status: text for status state or of data specific to event

(Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
- We have stopped the roll-out of this feature due to the PII issues so would like the custom event asap so we can re-start our launch. Please let us know what is feasible.

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by michelle-dooley** [comment]
@SKasimow - we will work on this as part of our sprint starting today.  Thanks!!

**Comment by SKasimow** [comment]
Thanks @michelle-dooley !

**Comment by jonathan-epstein13** [comment]
Hello @SKasimow. Below you will see the new event created for the Modal (profile_modal). Please let us know if you have any questions. 

dataLayer:
```
{
     event: 'profile_modal',
     modal-status: '<status>',
     modal-primaryButtonText: ‘<text>’,
     modal-title: ‘<title>’
}

```
Here are example values of how it can look: 
modal-title: Address Update
modal-status: Open, Closed
modal-primaryButtonText: Yes, No


How to find in reporting:

Event Category: Interaction
Event Action: Status: {{DL - modal-status}} - Title: {{DL - modal-title}} - Click Text: {{DL - modal-primaryButtonText}}
Event Label: profile_modal

**Comment by SKasimow** [comment]
Thank you so much! I will take a look and let you know if any questions @jonathan-epstein13

**Comment by adamwhitlock1** [comment]
@jonathan-epstein13 This is awesome thanks! I did have a question about the event and how it is set up.

Would it be possible to make it a bit more generic in relation to the event name and properties that get passed in? We were hoping to use this potentially in different ways and not just the modal interactions.

maybe something similar to:

```
{
     event: 'profile_event',
     profile-status: '<status>',
     profile-text: ‘<text>’,
     profile-event-title: ‘<title>’
}
```

That way if we were tracking a custom event we could have a more 'vanilla' way to send the event data for multiple use cases. If not totally cool, we can work with the modal based naming.

**Comment by jonathan-epstein13** [comment]
Hello @adamwhitlock1. Was able to discuss with @jennaouellet, and let's keep the modal based one for now.  

The GA4 event will be more generic, so you and your team can use it however you would want, but those variables we gave for UA will be accepted for any value. So you and your team can ignore the variable names and just know that whatever you would want to pass in will be captured as the Event Action and can be used however you would want it. 

Let me know if this makes sense and if you have any questions, please feel free to reach out.

**Comment by michelle-dooley** [comment]
Closing this ticket as this request has been completed.  Please reach out if you have any further questions.
