### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by stiehlrod** [department-of-veterans-affairs/va.gov-team#44385]
### Your Name

Jennica Stiehl

### Your Email

jennica.stiehl@oddball.io

### Your Role and Team

Backend Engineer on Dash

### Product Manager (PM) name and email

Kayla Watanbe

### Product Owner (PO) name and email

Premal Shah

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0FGTM1a8z0my0hFbtesZoW/m2g0JIYsXHCGB7kQXSvDqiFE0D01KMEr1G+R2I+jPix3ZjLgiMp+0FLuCc29qVPYQyY4h9ran7fYJU+61Mah4mbROI8iGX7nBl6MwZ6jAoiDukef+Cd+/ZzGAaZ3+BTT1MiD6dgsCeSLwnI4AGI5aYR19z0qRxPMnE1T4kH73MX0uBqsLbK/K2pitePSzGIuaVLRiPbrAck9wP28fyodMHxikvsF/fP/wkViP5q4QClDEqbk83r/+LbHI4UlgrnzfevIiWfvs2yHS1pDqTyLMjEbYjcvA6Map9OdfnwiGtRVFe94ekOyNXwsz1amZCFquC3MM/sDAUIrvMAKu2deasktWu5d0ab/+0oZJpNwDBGqEuO1PvcrIv9WwynN7FtleEMpqJ99q0FulnQsMUS6DyBvi+TfJtOAT9mUBBDW7ln9QFokrhHSUpLOY+jlZ6ADMQh7/z4Wb/LQZeZohpWh8eJfz2Xkzar5Rc78lnFCc= jennicastiehl@Jennicas-MBP.hsd1.co.comcast.net

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ryan-mcneil** [comment]
Adding for reference

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41602677/14fcc93c-09a1-47d8-a97f-b6e356660978)
