### ISSUE TITLE
[SSO-Login] My VA dashboard updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#4438]
**User Story**
As a Veteran receiving some or all of my health records via Cerner's portal (HealtheLife), I need My VA (https://www.va.gov/my-va/) dashboard experience to give me correct patient portal information after I have logged in.

_Note that this epic used to include work needed to My Health (va.gov/my-health) which is no longer needed_

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
