### ISSUE TITLE
[FE] - Look into gating profile if a fiduciary flag is present

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#44390]
We currently allow profile updates given a fiduciary/incompetent flag, but we shouldn't. We need to figure out how to stop this altogether.

Thankfully, VA Profile currently blocks this information from getting saved as follows.
From the [#va-profile Slack on 5.27.20](https://dsva.slack.com/archives/C7TE0PFTL/p1590608988135500):
>Joshua Lindsey Today at 3:49 PM: @Samara (She/Her) - just another view to make sure that the fudiciary scenario response is complete. If VBA (VBA Corporate) has a person identified as having a fiduciary. VA Profile will not update the VBA Corporate record. This logic is bi-directional, VA Profile also does not accept those changes to that record from Corporate. DB either. Example, If the address is sent from va.gov to VA Profile. VA Profile will accept the address but will exclude it from what is shared with VBA Corporate.

We're able to show an alert in the direct deposit section when this flag is present. Can we leverage that to block all of profile?

**Comment by andaleliz** [comment]
@SKasimow I created this ticket per the convo we had with Samara on Monday. This isn't a priority at all but wanted to capture it so it doesn't get forgotten. Maybe there'll come a time where one of our FE devs has some downtime and can look into this.

**Comment by andaleliz** [comment]
Hi Arná, I'm not sure how to remove you or why you received this. For this specific issue, you can unsubscribe via the option on the bottom of the right side of the page. Otherwise you'll likely need to update your notification settings in your github account.

**Comment by vahuntera** [comment]
I think I was getting these messages but they were going to the junk folder.  I recently started a new job and I was trying to clean out my inbox and I deleted some rules and then my inbox was inundated with emails concerning Git-Hub.

I have no reason to see these emails and this could be some type of violation being as though I don't have a need for this information.

Arná Hunter
United States Army Veteran
COR Level 2
Financial Systems and Procedures Analyst
Travel Agency/Organization Program Coordinator (A/OPC)
National Cemetery Administration
NCA Financial Systems Oversight & Transformation (42F)

Cell:                 202-384-5360
E-Fax:             202-495-5537


How was my service?<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvaww.vashare.nca.va.gov%2Fsites%2FPPS%2FLists%2FICSS%2FNewForm.aspx&data=05%7C01%7C%7Cbaa4be48ccdf43bbb32f08da60542cd7%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637928211884383458%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TwTtm3YDn8pD5HcTxYmjiuIRgxIsrIznMZgvlqwWIi4%3D&reserved=0>


[Description: Description: ***@***.***
VA Core Values: Integrity Commitment Advocacy Respect Excellence
VA Core Characteristics: Trustworthy | Accessible | Quality | Innovative | Agile | Integrated



From: Liz Lantz ***@***.***>
Sent: Thursday, July 14, 2022 2:09 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Hunter, Arna ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] [FE] - Look into gating profile if a fiduciary flag is present (Issue #44390)


I'll try to help. I need some more info to pass along to the right team.

Is this the first notification you've gotten from the VA.gov repository? Or do you get all of them?

Also, are you getting notifications from any other GitHub repositories?

-

**Comment by andaleliz** [comment]
Can you tell me the email address where you're getting these notifications? It's masked in your replies.

**Comment by vahuntera** [comment]
***@***.******@***.***>


Arná Hunter
United States Army Veteran
COR Level 2
Financial Systems and Procedures Analyst
Travel Agency/Organization Program Coordinator (A/OPC)
National Cemetery Administration
NCA Financial Systems Oversight & Transformation (42F)

Cell:                 202-384-5360
E-Fax:             202-495-5537


How was my service?<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvaww.vashare.nca.va.gov%2Fsites%2FPPS%2FLists%2FICSS%2FNewForm.aspx&data=05%7C01%7C%7Cbaa4be48ccdf43bbb32f08da60542cd7%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637928211884383458%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TwTtm3YDn8pD5HcTxYmjiuIRgxIsrIznMZgvlqwWIi4%3D&reserved=0>


[Description: Description: ***@***.***
VA Core Values: Integrity Commitment Advocacy Respect Excellence
VA Core Characteristics: Trustworthy | Accessible | Quality | Innovative | Agile | Integrated



From: Liz Lantz ***@***.***>
Sent: Thursday, July 14, 2022 2:15 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Hunter, Arna ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] [FE] - Look into gating profile if a fiduciary flag is present (Issue #44390)


Can you tell me the email address where you're getting these notifications? It's masked in your replies.

-

**Comment by andaleliz** [comment]
Hmm, it's still being masked. I reached out to my team and pointed them to this conversation. If the email address is needed, one of us can give you a call to get it. I'm hoping they can remove you via your GitHub user name.

**Comment by speakmin** [comment]
Hi @vahuntera if you don't need any GitHub notifications I recommend going into your profile and _disabling email notifications._ 

You can do so by going to Settings -> Notifications and unchecking all the boxes that have email next to them.

**Comment by andaleliz** [comment]
I spoke to Arná and did my best to help over the phone. They don't have access to their GH account so they can't go to their profile. If possible, let's remove them from our organization so we're not spamming them.

**Comment by SKasimow** [comment]
Closing this; have opened a new ticket #47841
