### ISSUE TITLE
[SMS] Send "Check-in Now" Message 30 Minutes before Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44395]
## Background
This was a recommendation that came out of the [Bay Pines research study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/bay-pines-in-person-uat).

Explore starting check-in via a notification (text/email). We would push something to the Veteran instead of starting with the poster. Stephen brought this up in this Slack thread. We had this idea originally when we started the project, but the stakeholders were worried about it. We have been amassing feedback on why a push notification would be valuable. I think the first step would be to package that feedback in a way to try to convince the stakeholders of the need for the change.

    - Put it into the initial confirmation text message
    - Send the link at a different time of day after confirming their appointment
    - Send the link multiple times, if not completed

## User Story
As a Team, we would like to send a message to Veterans 30 minutes before their appointment to remind them to use Mobile Check-in for their appointment. 

## Idea
- Add a "check in now" message from VeText/CHIP delivered 30 minutes before the appointment.
    - We should not send them a message if they have already checked-in with an MSA
    - We should only send them a message if they have opted in to receive VA text messages

**Comment by acrollet** [comment]
Per @batemapf, there may need to be a clinic level on/off switch for this functionality.

**Comment by loripusey** [comment]
Closing, it was decided we would not pursue this
