### ISSUE TITLE
Parameters to identify invoking application and state

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#4440]
When My VA Health (Cerner) triggers the standalone login page, they need to at a minimum pass a parameter that identifies the application. Additionally they may desire a state/relaystate type parameter that can be echoed back so that they can return user to any specific state/context that they were in before redirecting.

Assumption: the base callback URL will be statically configured for each application (i.e. we won't allow a dynamic callback URL to be presented as a separate parameter). 

Unknown: Do we want to maintain this mapping from application to callback URL in frontend code or in vets-api?
Unknown: What's needed to maintain the relaystate presented. by the My VA Health (Cerner) application across. all of the multiple SAML requests that we will be making to authenticate the user.

**Comment by ambikaroos** [comment]
Dan to work with Chris Valerie this afternoon. We can do it the way we do right now with to and fro, or have a single function as a page and as more navigation comes there it can take on the additional complexity of navigating elsewhere

**Comment by ambikaroos** [comment]
Lauren passed along these questions to Cerner, we're waiting for a response.

> We'd like to get confirmation from Cerner on the following expectations for triggering the standalone login page:
> - My VA Health will need to pass an “application” query parameter (to distinguish it from other potential uses of this login page). Barring any disagreement we’ll use the value “myvahealth” to identify the cerner application
> - After the user authenticates, the VA.gov login page will redirect the user back to a single, statically-configured callback URL on My VA Health - at some point soon we’ll need to know what that URL is in each relevant environment.
> - Do you anticipate wanting to pass any kind of “state” parameter that you want echoed back with the redirect, in order to maintain user context before/after the authentication step? This is a common pattern in OAuth/SAML but since we’re not using those protocols directly not sure if it is a requirement here.

**Comment by ericbuckley** [comment]
@hinzed1127 I just merged https://github.com/department-of-veterans-affairs/vets-api/pull/4042 which should unblock this.

When a user lands on the stand alone login page, we should copy all query parameters form the request over to the API call made to `/v1/sessions/<type>/new` call made.  From there the user should be redirected back to cerner upon successful authentication.  Let me know if you have any questions.
