### ISSUE TITLE
[07/14/22] VEText Admin Training SharePoint Page Creation

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#44409]
- [x] Create Admin Training Criteria SharePoint Page

- [x] Include links to Training page, pre-recorded training, user role audit app, and the follow-up assessment

- [x] Link to VEText Training Page

- [x] Create "Quick Links" button on Training Page

**Comment by lindsay-insco** [comment]
Completed and on SP
