### ISSUE TITLE
Supplemental Claims | 5103 - Notice of Acknowledgement Content review from Benefits Team 1 - Squad 2

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#44411]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Notice of Acknowledgement - 5103 is a required section of 5103 that research has shown is confusing to Veterans. We would like to rework this experience for the online form.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users? Not sure
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/readme.md)
- [Figma sketches](https://www.figma.com/file/2dvNcsPbIlQ4SIa7n5CNnG/Supplemental-Claims?node-id=26%3A6484)
- [Working Sketch files](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89)

## Will this work be going through the Collaboration Cycle?
- [ x]Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: Ongoing. I'm attending Beth Pott's office hours weekly and we don't anticipate a lot of work here, so hoping 1 or 2 sprints.

## Do you plan to bring this to an upcoming content office hours session?
- [x]Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Pam Hastings
-	FE engineer: Robin Garrison
-	Product/team Slack channel: Benefits-Team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by thehastingsp** [comment]
@RLHecht @bethpottsVADEPO and I just discussed this in office hours, so are planning to use this ticket for some back and forth FYI.

**Comment by thehastingsp** [comment]
COMP of proposed:
![Step 3 of 6: 5103 DUTY TO ASSIST ALT Inline Open Copy](https://user-images.githubusercontent.com/68615337/179087299-5aad1255-6d4e-4d2b-9766-8ead71c7bb6b.png)

**Comment by bethpottsVADEPO** [comment]
@thehastingsp Here are some notes I have about this screen. Let me know if you have questions or want to talk through anything! And see No. 6 here. We both have some digging to do...

1/ H1 should be: File a Supplemental Claim ~Equal to~VA Form 20-0995 (delete "Equal to" as that's older language that we no longer use)

2/ For all these subheads attached to "Step 3 of 6" etc., please use sentence casing, so: **New and relevant evidence**

3/ Is this a global component?: "Your application will be saved with every change." I'd like to apply our plain language standards here and make it active voice: "We'll save your application every time you add or update information."

4/ Change this: Please review and acknowledge the evidence statement below to substantiate a claim for benefits.
To this: You'll need to review and acknowledge this notice of evidence needed.

5/ As far as pared down content here about evidence requirements, I'd follow closely what we have on the disability evidence page that the Supplemental Claim form PDF points to. I'd recommend this language:

**Notice of evidence needed** (Note to Pam--don't use all caps here)
--------------------------------

You’ll need to submit new evidence we haven’t reviewed before that’s related to the issue you’re claiming.

**We’ll look for evidence that shows:**
- You have a current physical or mental disability (damage to your body or mind that makes you less able—or totally unable—to do everyday tasks, including meaningful work), **and**
- An event, injury, or illness that happened while you were serving in the military caused this disability

You'll need to submit or give us permission to gather medical evidence from a VA medical center, other federal facility, or your private health care provider.
(Note to Pam--can you find out if we should mention supporting statements here too?)

**I certify that** I have reviewed the notice of evidence needed. 
(I don't think you need to use all caps here either. Let's see if we get pushback on that if we keep it bolded but don't use all caps.)

6/ I want to put a pin in the Need help? section so you and I know we need to revisit the language and the phone numbers provided there. I'll find out what the most up-to-date language is for that. Can you find out which number they want to send people to? I'm not sure what you have is the right one. And for TTY, we do this:
TTY: 711

**Comment by bethpottsVADEPO** [comment]
@CherylEvans for awareness!

**Comment by CherylEvans** [comment]
@bethpottsVADEPO Thank you!!

**Comment by thehastingsp** [comment]
@bethpottsVADEPO thank you! @saderagsdale let's add this to our list of outstanding questions:

```
You'll need to submit or give us permission to gather medical evidence from a VA medical center, other federal facility, or your private health care provider.
(Note to Pam--can you find out if we should mention supporting statements here too?)
```

**Comment by thehastingsp** [comment]
@bethpottsVADEPO the content has been updated with your suggestions, thank you. We just need to pin down the answers above and determine the best route to changing the global element @Mottie mentions in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45639).

**Comment by thehastingsp** [comment]
@bethpottsVADEPO we can go ahead and close this ticket and handle your question around help copy [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45835).

**Comment by bethpottsVADEPO** [comment]
Sounds good @thehastingsp, closing now.
