### ISSUE TITLE
[AWS] Access to Redis clusters for mviterna

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#44419]
## Who is the devops resource on your team?

@mviterna

## Description

I would like access to the Redis Clusters in the AWS Console

## Technical notes

Getting this error: User: arn:aws-us-gov:iam::008577686731:user/Mark.Viterna is not authorized to perform: elasticache:DescribeCacheClusters on resource: arn:aws-us-gov:elasticache:us-gov-west-1:008577686731:cluster:* because no identity-based policy allows the elasticache:DescribeCacheClusters action
---
## Tasks
- [ ] _What things need to happen?_
Get access
## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_
Can view the redis clusters
---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
@mviterna 

For what environment is needed (dev,staging,prod)?
What is the name of the cluster required?

**Comment by mviterna** [comment]
@oseasmoran73 This should be for all environments. I am not sure the cluster name, since I can't see it, but it should be the one for the vets-api Ruby on Rails monolith app.

**Comment by oseasmoran73** [comment]
Question for you @jhouse-solvd & @ph-One 

Are we allowed to give access to Redis cluster for lower environments or does that also need to go through security request? Want to point Mark in the correct direction

**Comment by ph-One** [comment]
I will defer to @ericboehs, as the redis clusters in question belong to his team. If he gives the all clear, then at least dev and staging access can be granted. Prod we will have to check on.

**Comment by ericboehs** [comment]
@mviterna What do you need the access for? I'm not opposed to granting it but I'm trying to figure out why you want read only access and what you think that means.

Granting read-only access to the AWS Console will just let you view information about them, not access them directly. Are you needing direct access for data querying purpose? If so, you'll simply need SSM access to prod Rails for that.

**Comment by mviterna** [comment]
@ericboehs I thought the redis-cli wasn't on our vets-api containers. I just need it to query data. If you have a work around that's fine. What's the best way to query outside of the CLI?

**Comment by ericboehs** [comment]
You can query Redis via the Rails console using the `$redis` global (e.g. `$redis.get('mykey')`). Do you have SSM access?

**Comment by mviterna** [comment]
@ericboehs Yes. I'll try that out. You can close the ticket

**Comment by oseasmoran73** [comment]
Thanks everyone! If you have any additional questions Mark, feel free to reopen this ticket or ask in this thread

Closing
