### ISSUE TITLE
Supplemental Claims | Content Design

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44414]
## Supplemental Claims Product Outline
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/readme.md)

## High Level User Story/ies
As a Claimant, I want the claims I submit to be easy to understand and communicated to me with plain language, clear actions and decisions as they move through VA systems, and I want proactive communications about their progress.

## Purpose
This epic is intended to house the content tickets specific to the initial build of Supplemental Claims. 

## Definition of done
We'll close this epic once we've resolved all content issues related to MVP.
- [x]  [Supplemental Claims Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [x] [Midpoint review feedback content review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46818) *in progress*

**Comment by thehastingsp** [comment]
closing this ticket as we follow up with a [full content review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46818) post usability.
