### ISSUE TITLE
Access for Kevin Shih

### ISSUE THREAD

**Issue by kevinshih613** [department-of-veterans-affairs/va.gov-team#44420]
## Instructions
1. Fill out Description
2. Change the Title to include your name
3. Add the label used by your team (eg: `BAH-526`)
4. Do not remove `operations` label or the `ops-access-request` label; this will notify the VSP Operations team of your request
5. When the issue is closed you will be notified and can continue with on-boarding setup

## Description
* Please provide your Contracting Officer's Representative (COR) name.

> Cecilia Lee

* Please provide your name.

> Kevin Shih

* Please Provide your email.

> [kevin.shih@adhocteam.us](mailto:kevin.shih@adhocteam.us)

* Please provide the name of your team, your role on that team, and the name of the company you work for.

> I am a Researcher on the UX team at VA Lighthouse APIs. I work for Ad Hoc LLC.

* Requesting SSH key authorization?

>NO.
>We don’t need socks proxy, just a limited AWS account with S3 and Transcribe access in iAM. Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1603395713414900

  * What is your public SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```
* Grant AWS Console access?
> YES

* What AWS services do you need access to and why?
> We need to access the transcription service to transcribe interviews that we conduct with non-Veteran users, and also to S3 buckets dvpuxresearchinput and dvpuxresearchoutput

**Comment by calquisola** [comment]
Hi @kevinshih613,

Please use this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D) for AWS Access Request.

Thank you.

Best,
Carl

**Comment by calquisola** [comment]
Spoke with Kevin. He will create a new issue using the [AWS Access Request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D). Please close this ticket when the new request is creatd.

**Comment by calquisola** [comment]
new [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44536) created for this. Closing this request.
