### ISSUE TITLE
AWS access for [John Weisz]

### ISSUE THREAD

**Issue by johnmweisz** [department-of-veterans-affairs/va.gov-team#44422]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

John Weisz

### Your Email

weisz_john@bah.com

### Team, Role, and Company of the target individual

Team Pivot!, Software Engineer, Booz Allen Hamilton

### Product Manager (PM) name and email

Greg Feliberty, feliberty_gregory@bah.com

### Product Owner (PO) name and email

Andrew Fichter, andrew.fichter@va.gov

### Desired AWS Access

I need same access as Derek Brown and/or Larry Crochet

### Access Expiration

July 14, 2024

### Additional Notes

I need access to execute maintenance requests for saml-proxy and oauth-proxy projects both of which team Pivot! is responsible for maintaining.

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mleclerc00** [comment]
Hello @johnmweisz 

I was unable to find you on either the platform or vfs roster.  Please take the appropriate action to be added where you should

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/76792875/179099144-ea13ef82-b5ea-4781-b0e3-eda07f6d42b2.png">

**Comment by oseasmoran73** [comment]
Closing ticket as not reply or action mentioned
