### ISSUE TITLE
Maintenance Ops Docs: Add user to allow list

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44432]
As a temporary measure, we have implemented an allow list for users to access Keycloak. This allow list establishes the user's relationship status with the platform. Since this step is not one that users would intuit, we need to describe the process in order to streamline and troubleshoot their Keycloak onboarding experience.

**done when** 
- [x] doc exists under the maintenance section in confluence
- [x] doc describes 
  - [x] what (the process, the code, the functionality, etc)
  - [x] why (what's the purpose of this process)
  - [x] who (what types of users)
  - [x] where (which environment)
  - [x] when (when does a user need to be added)

**Comment by calquisola** [comment]
confluence doc created. https://vfs.atlassian.net/wiki/spaces/AMT/pages/2321711260/Adding+users+to+allow+list
