### ISSUE TITLE
Maintenance Ops Docs: Incorporating platform tool permissions

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44435]
We have a process and schema in place to describe platform tool permissions. (RFC here). We also ahve defined a process by which paltfrom teams can submit their permissions for integration into Keycloak. We need to document this process so that AMT can manage the permissions lifecycle of a platform tool.

**done when**
- [x] Doc is created under the maintenance secion in confluence
- [x] Doc links to relevant RFCs
- [x] Doc describes **in brief** the process for incorporating a platform tool's permission into Keycloak.

**Comment by iriteshp** [comment]
Doc added here: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2357559362/Incorporating+platform+tools+permissions+with+JSON
