### ISSUE TITLE
Integration Ops Docs: Promoting an integration to a higher KC environment

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44440]
We have 3 different Keycloak environments to assist our platform teams in testing integrations of platform tools to Keycloak. We need to describe a migration process so AMT guide platform teams through promoting their services to the correct environment.

**done when** 
- [x] doc is created in confluence under the integration section
- [x] doc describes **for each environment**
  - [x] Why integration into the environment is important
  - [x] The preconditions for deploying to the environment
  - [x] The process for deploying to an environment (be brief but link to RFC)

**Comment by iriteshp** [comment]
doc added here: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2321022993/Promote+integration+to+a+higher+Keycloak+environments
