### ISSUE TITLE
DevOps Ops Docs: Accessing DataDog Dashboards

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44443]
Our monitoring and alerting is set up in Datadog for all 3 environments. We need to document how to access our dashboards for each environment, and what the dashboards are monitoring.

**Done when**
- [x] We have a document in Confluence created under the DevOps section
- [x] The document includes links to dashboards to each environment
- [x] The document includes descriptions of the purposes of the metrics

**Comment by iriteshp** [comment]
@kjduensing are we going into detail for each widget in this documentation? here is the example https://vfs.atlassian.net/wiki/spaces/AMT/pages/2290155533/Keycloak+Datadog+dashboards#Login-Attempts

**Comment by kjduensing** [comment]
How many widgets are there there?

**Comment by iriteshp** [comment]
about 7 total.

**Comment by iriteshp** [comment]
added doc here: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2290155533/Access+Datadog+dashboards

ready for review.

**Comment by kjduensing** [comment]
Looks great, I think we can close this unless anyone else has commented.

**Comment by iriteshp** [comment]
did not receive any comments. closing the ticket.
