### ISSUE TITLE
Integration Ops Docs: Testing integrations

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44441]
With our main goal being to centralize access to Platform Tools under a single access management system, we expect to integrate many tools over time. Part of integration is testing. We need to document how an AMT maintainer can assist in testing.

**done when**
- [ ] document creating in confluence under the integration section
- [ ] relevant methods of supporting testing are described
  - [ ] REST/Postman
  - [ ] In-Keycloak evaluation

**Comment by girldadmk** [comment]
@calquisola to provide @kylesoskin with existing Postman workflow. 

@kylesoskin will write document showing how it work.
