### ISSUE TITLE
FAQ - Playbook - Reverse Proxy DevOps Off-Cycle Deployment

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#44451]
Description

Info found in [Slack Thread.](https://dsva.slack.com/archives/CBU0KDSB1/p1657894427000929)

PR: [11569](https://github.com/department-of-veterans-affairs/devops/pull/11569)

Tasks
[ ] Create a FAQ and Playbook Documentation for   Reverse Proxy DevOps Off-Cycle Deployment

**Comment by little-oddball** [comment]
Determined OBE
