### ISSUE TITLE
1010CG: log out MPI transaction ID

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#44464]
see slack thread: https://dsva.slack.com/archives/CMJ2V70UV/p1657904815413759?thread_ts=1657902743.046359&cid=CMJ2V70UV

**context**: one of the higher error types (~1.4%) for the 10-10CG is MPI returning "Veteran not found" based on the attributes supplied by the user. we may want to dig into these in the future to understand if there are any ways we could help bring that number down or otherwise handle these more gracefully than telling the user to download and mail a PDF. we understand that when we send attributes to MPI we get a transaction ID back with the response. this ID can be used by the MPI team to gather additional information about the request (and maybe other methods of doing research).

**Comment by markfallows** [comment]
Questions:
1. How can we surface the transaction ID?  Put it in the PII logs table
