### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by bustilloBAH** [department-of-veterans-affairs/va.gov-team#44470]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics
- [ X] Domo
- [ ] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

**I do not have access to the DSVA Slack channel** 

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [x] Provide access to user
- [x] Ensure user received email confirmation

**Comment by bustilloBAH** [comment]
Hi, this is my first time using this. I work for Booz Allen, and am working with DSVA. I spoke with someone that works for the MYVA411 call center, she sent me the link to the DOMO dashboard, but I need access. She sent me this template to request access. Let me know what you need from me please.

**Comment by pavanhothi** [comment]
Hi @bustilloBAH please complete section 2. "User Email Address to Receive Access" of this template in order to complete your access request. Thank you!

**Comment by bustilloBAH** [comment]
The email address is bustillo_gian@bah.com

**Comment by pavanhothi** [comment]
Due to privacy concerns, please do not put your email in this ticket. 
These support requests need to come in through the DSVA slack channel with your email and ticket linked there.

**Comment by bustilloBAH** [comment]
Understood. However, I do not have access to the DSVA slack channel

**Comment by jonathan-epstein13** [comment]
@bustilloBAH I tried getting you access to the DSVA slack channel, but no updates on that front yet.  I also noticed you are not in GH, because I cannot tag you. Is there another contact you have that might help us?

**Comment by bustilloBAH** [comment]
Good morning – Thanks for the update! I am not in GH, as in not in the VA Github? Because I think you tagged me @bustilloBAH within Github, right?

I created my bustilloBAH account myself, so it is not tied to the VA. This whole request may just have to wait until I get my GFE.

As for a contact, you could try Lantos-swett, Chanteclaie E. (she/her/hers) ***@***.******@***.***>. Thank you!!!
Thanks,

Gian
703 606 4489

From: jonathan-epstein13 ***@***.***>
Sent: Tuesday, July 19, 2022 8:08 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Bustillo, Gian [USA] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #44470)


@bustilloBAH<https://urldefense.com/v3/__https:/github.com/bustilloBAH__;!!May37g!JUSDCssES3RNXDiHkf27MpkiVGY3GadYbi5jNn8XqbdJB8U21jdHTfgGcEBS6Dl4EQatNoQCAbd0eKiuz1GNy0g6rQ$> I tried getting you access to the DSVA slack channel, but no updates on that front yet. I also noticed you are not in GH, because I cannot tag you. Is there another contact you have that might help us?

**Comment by pavanhothi** [comment]
@bustilloBAH please resubmit request once you have received your GFE. Thank you!

**Comment by bustilloBAH** [comment]
Hello, I I put in my request on the Slack channel /support, can I reopen this?

**Comment by pavanhothi** [comment]
DOMO access has now been granted
