### ISSUE TITLE
[BUG] [FE] Translation Issues

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44473]
## Pre-Check-in Issues
- On the Respond to Questions page (aka landing page)
     - This
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/62f69505-4cae-4983-9444-8ddafe29da02)
    - Should be this
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/bc3543ac-591b-46bb-ae40-a3bd62bde242)
- On the completion page
    - This
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/fa4f7e78-a0f4-4f1f-86df-f87e0aa2b39d)
    - Should use this key
        - Key = "your-provider-will-call-you-at-your-appointment-time-you-may-need-to-wait-about-15-minutes-for-their-call-thanks-for-your-patience"
        - Value = "Su proveedor le llamará a la hora de su cita. Es posible que tenga que esperar unos 15 minutos por la llamada. Agradecemos su paciencia.",

**Comment by loripusey** [comment]
@acrollet I finished creating the WF docs; I identified these 2 issues. I you can get these in I can generate the screenshots from the pull request. Let me know if you have any questions.

**Comment by loripusey** [comment]
I also identified ones that are not being used (based on my search).[https://app.zenhub.com/files/133843125/4487df6e-570c-4edc-aa7d-3f507dc14a00/download](https://app.zenhub.com/files/133843125/4487df6e-570c-4edc-aa7d-3f507dc14a00/download)

**Comment by loripusey** [comment]
I also added "Telephone appointment" and "In-person Appointment" to the Round 3 spreadsheets as we didn't have those.

**Comment by loripusey** [comment]
@brdunfield @brianseek Could one of you pick up this bug and finish it?  The answer to Adrian's question above is yes, we should extrapolate and add these to the Spanish file. Putting the ticket back in "In Progress". 
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/12ebadce-08fb-4517-bc4d-8c7992c0867eutt)

**Comment by brdunfield** [comment]
@loripusey I see these lines already in the spanish file.
```
"your-appointments-on-day-facility_one": "Su cita es en esta fecha: {{day, long}} y en: {{facility}}.",
  "your-appointments-on-day-facility_other": "Sus citas son en esta fecha: {{day, long}} y en: {{facility}}.",
```

Is this ticket able to be re-closed?

**Comment by loripusey** [comment]
@brianseek @acrollet I think this got dropped when Bethany left. Could one of you finish this bug off if time permits?

**Comment by acrollet** [comment]
@loripusey @brianseek I can pick this up.

**Comment by sarahknoppA6** [comment]
@acrollet will check in on this and make sure it's in a validate state!

**Comment by acrollet** [comment]
@loripusey Bethany did this in #22032, I just checked and the text is presented:

![Screen Shot 2022-09-26 at 12.28.07.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/925b1e02-fae3-4b68-b9b8-c663abe829f5)

Let me know if this needs anything else or we can close it out, thanks!

**Comment by loripusey** [comment]
Validated
