### ISSUE TITLE
Additions to Chatbot KPI Dashboard

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#44475]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [X] Ticket Description
- [X] Request/Report Description
- [x] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - Ian Santarinala, Product Manager, Virtual Agent Chatbot team

- Is this a feature request or a bug?

  - [X] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

### Current State
Currently the Virtual Agent Chatbot KPI Dashboard under the "Click interactions > What interactions were most common? > Interactions with most clicks (drill in place)" section is displaying Interactions Total Events from Google Analytics.

### Desired State
We'd prefer to show Interactions Unique Events. This is because we mostly care about unique users who are using the bot. For example, we use the number of unique users who click on the send button in the chatbot (Event: submitSendBox...the most completed Event on the chatbot page) to measure engagement on the bot. Currently this is about 32K events. Conceivably in a single session, the user could be asking the chatbot multiple questions and each time they'd hit the send button. Unique send button clicks is currently about 19K events. The current section of the KPI report is confusing report users into thinking more people are using the chatbot than actually are. 

Our ask is to ideally replace the existing Interactions Total Events with Interactions Unique Events. Otherwise having both of them side by side would be OK but not the preferred choice.

### Additional Ask
Currently there is a User Interaction rate which from the explanatory text I understand to be # of user who interact with anything on the page / total number of users on the Chatbot page. Would it be possible instead of interactions with anything on the page, instead have it be Interactions with the submitSendBox. Ideally it would be stated as unique Send button events / total number of users to the chatbot page. This would tell us our engagement rate (and you state it as the user interaction rate). There could be many repeat visitors to the chatbot page, but we care how many times they interact with the bot by asking it at least one question (by hitting the send button).

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

We can be reached at #va-virtual-agent-public on Slack if you have any additional questions. Please contact myself or @LucianaAlexanderMorais with more questions.

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by michelle-dooley** [comment]
@ianpsant - thanks for your submission.  To make the change you are requesting we will need to create a new edge case dashboard for you.  Making this change to the standardized content dashboard would change it for all.  Developing an edge case dashboard that is more specific to your chatbot needs is something we have discussed before.  I'm going to get some time on our calendars to discuss, so we can understand all the asks/questions you may want answered so we can include those as well.  Look for a being request for next week.  Thanks.  Michelle

**Comment by LucianaAlexanderMorais** [comment]
@michelle-dooley Thank you! Please include me in these discussions as well. I am going to be off Monday and Tuesday, but I really want to understand what is doable. Thanks again!

**Comment by michelle-dooley** [comment]
@LucianaAlexanderMorais - I moved the meeting to Thursday so you could attend.  Both your calendars looked open at 1:00 ET.

**Comment by LucianaAlexanderMorais** [comment]
Thank you!!

**Comment by michelle-dooley** [comment]
Closing this ticket, this work will be completed as part of the new edge case dashboard #45133
