### ISSUE TITLE
Use CSP data when missing from MPI for SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#44472]
When a user logs in with an IAL2/LOA3 account we get data from the CSP and perform an MPI lookup. Currently with SiS we throw away these CSP attributes after we get a user data return from MPI.

- We should keep the CSP user data for each field that returns as null from MPI
- We should consider performing an MPI add person with the CSP data that is different or missing from MPI (likely a different ticket, but as part of this ticket determine if we want a new ticket for this or not)

**Comment by bosawt** [comment]
We will now use 1302 update patient MPI for this. And we will always make this call
