### ISSUE TITLE
Caution Flags: Update Prototypes

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/va.gov-team#4448]
- [x] Incorporate DEPO input and update mockups/interactions
- [x] Review with UX team
- [x] Review with B.A. /Tech Lead

**Comment by amyknox** [comment]
Prototypes
Desktop: https://bahdigital.invisionapp.com/share/SCIACE37P2J#/screens/296027207
Mobile:  https://bahdigital.invisionapp.com/share/CRIACEMVQD9#/screens

**Comment by ccruzgra** [comment]
Reviewed with BA/Dev Lead. Dev Lead will do further research into items concerning Caution Flags and School Closures which may require further prototype updates.

**Comment by ccruzgra** [comment]
@amyknox Shall we delete the final task for this story or modify it to say "Update, as needed" especially if Dan/Darrell learn something new that affects our proposed enhancements?

**Comment by amyknox** [comment]
Yes, let's remove that last task.  We'll share with them next sprint.  Thanks!
