### ISSUE TITLE
AWS access for Xernan Peralta

### ISSUE THREAD

**Issue by xperalta-va** [department-of-veterans-affairs/va.gov-team#44480]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Xernan Peralta

### Your Email

peralta_xernan@bah.com

### Team, Role, and Company of the target individual

Jr UX Researcher on the UX team at VA Lighthouse APIs. I work for BAH.

### Product Manager (PM) name and email

Dana Harris dana.harris@adhocteam.us

### Product Owner (PO) name and email

Kathy Turney turney_kathleen@bah.com

### Desired AWS Access

I need to access the transcription service to transcribe interviews that we conduct with non-Veteran users, and also to S3 buckets dvpuxresearchinput and dvpuxresearchoutput.

### Access Expiration

Ongoing

### Additional Notes

I need access to AWS to help other researchers on the Lighthouse program transcribe their audio docs. I need ongoing access because this is part of my responsibilities I will be doing.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by xperalta-va** [comment]
I went ahead and submitted that new ticket. I signed up for the Researcher and general VA onboarding sessions. How long does this usually take to be added to the rosters?

From: Ritesh Patel ***@***.***>
Reply-To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Date: Monday, July 18, 2022 at 7:31 AM
To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Cc: "Peralta, Xernan [USA]" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] AWS access for Xernan Peralta (Issue #44480)


Hi @xperalta-va<https://urldefense.com/v3/__https:/github.com/xperalta-va__;!!May37g!OI9Lv6AL8CuyCc3unR15gK1qMYPNykyUSz46StQY4BrQC6Q0uRWMhmaP5Q5KYDCegrwoKJr1YAHCCJV-QT1FGwyYzfA$>! We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with this platform orientation guide<https://urldefense.com/v3/__https:/depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html__;!!May37g!OI9Lv6AL8CuyCc3unR15gK1qMYPNykyUSz46StQY4BrQC6Q0uRWMhmaP5Q5KYDCegrwoKJr1YAHCCJV-QT1FMwQTAWo$>. If you're not newly joining the team, please reach out to your PM or PO for help.
Once you're added to the roster, we can go ahead and continue processing this request. Thanks!

**Comment by oseasmoran73** [comment]
@iriteshp Looks like he was recently add to the roster. Can you double check?

**Comment by iriteshp** [comment]
User found in VFS Team Roster

**Comment by iriteshp** [comment]
### For AWS Access

User: Xernan Peralta
COR: Cecila Lee
VOR: Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by xperalta-va** [comment]
Hello,

I don’t know if I’m supposed to be a part of this conversation or not. I am curious to see if I’m able to get AWS access for transcriptions or not yet?

From: Oseas Moran ***@***.***>
Date: Friday, July 22, 2022 at 9:28 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Peralta, Xernan [USA] ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] AWS access for Xernan Peralta (Issue #44480)

@iriteshp<https://urldefense.com/v3/__https:/github.com/iriteshp__;!!May37g!I92XngZEHU-silx-pMxN6hWA-fUGcquAO3AD7rYaf4G9tv3ewPIeQirsdD7LEnQw-NL6PweP-hPgDaQka_T4_V2r1y4$> Looks like they was recently add to the roster. Can you double check?

**Comment by iriteshp** [comment]
Hello @xperalta-va, you are on the roster now and we do not need any further action from your side. We will not be able to provide you access to AWS until your request is approved.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
AWS access approved

**Comment by jsgarmon** [comment]
First-time login instructions sent via Slack DM.

**Comment by xperalta-va** [comment]
Hi Ritesh,

I’ll take a look at the platform orientation guide this morning and reach back out soon.

Thank you,

Xernan

From: Ritesh Patel ***@***.***>
Reply-To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Date: Monday, July 18, 2022 at 7:31 AM
To: "department-of-veterans-affairs/va.gov-team" ***@***.***>
Cc: "Peralta, Xernan [USA]" ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] AWS access for Xernan Peralta (Issue #44480)


Hi @xperalta-va<https://urldefense.com/v3/__https:/github.com/xperalta-va__;!!May37g!OI9Lv6AL8CuyCc3unR15gK1qMYPNykyUSz46StQY4BrQC6Q0uRWMhmaP5Q5KYDCegrwoKJr1YAHCCJV-QT1FGwyYzfA$>! We couldn't find your presence in the rosters maintained by the organization. If you are newly joining the team, please follow along with this platform orientation guide<https://urldefense.com/v3/__https:/depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html__;!!May37g!OI9Lv6AL8CuyCc3unR15gK1qMYPNykyUSz46StQY4BrQC6Q0uRWMhmaP5Q5KYDCegrwoKJr1YAHCCJV-QT1FMwQTAWo$>. If you're not newly joining the team, please reach out to your PM or PO for help.
Once you're added to the roster, we can go ahead and continue processing this request. Thanks!
