### ISSUE TITLE
VAOS Staging: CC Requests Comments Being Truncated from 250 Characters to 100

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#44493]
## What happened? 
When a user creates a CC request with additional comments (250 characters) in VAOS, the system is not transferring the comments in its entirety to HSRM. Only 100 characters are being displayed in VAOU UI (Pending request page) and HSRM (Comments under Task). SQA team ran a test with VAOS test Harness and was able to determine that the Comments fields is being transferred correctly to HSRM (250 characters). 

## Steps to Reproduce
1. Login to VAOS as a VAOS service test user (Ex- jacobreid.r.iasimone@id.me)
2.  Click on "Start Scheduling"
3. Select any type of care supported by Community Care (ex: - Primary care, Food and Nutrition, Optometry, Podiatry, Audiology)
4. Select a preferred provider
5. Enter a preferred date
6. Enter additional comments (Please note the comment should be 250 characters) 
7. Fill in all the required data and create a request

## Expected Results:
System to display the comment at its entirety (i.e., 250 characters)
## Actual Results:
System is only displaying the comments for with first 100 characters instead of 250  

Please find below the screenshots for reference:
![VAOS 250 characters test](https://user-images.githubusercontent.com/69315717/179525765-51fb10bf-f49e-4cb0-b8e8-763322918716.png)
![VAOS Test Harness 250 characters test](https://user-images.githubusercontent.com/69315717/179527550-35a29712-5fae-4ddb-ab4f-17e3ae43ad7c.png)

**Comment by aarathi-poldass** [comment]
@Ldelacosta Can you please assign this ticket to the developer for further analysis. This issue is related to comments being truncated in VAOS UI.

As this defect is related to comments, please note that this is a Critical defect and needs to be addressed before the Go-Live date. Please Let me know if you have any questions.

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this issue was given a **High** priority

**Comment by simiadebowale** [comment]
@aaronhietpas @ldelacosta  this is ready for review.

**Comment by ldelacosta** [comment]
@aarathi-poldass - This is ready to be tested. Please let us know if you have any issues. Thanks!

**Comment by marcynadeau** [comment]
@ldelacosta @simiadebowale Heard from Aarathi that this passed testing. She will update tomorrow with test results. Just wanted to give you a heads up.

**Comment by aarathi-poldass** [comment]
Re-tested the defect and Passed validation. Able to successfully enter a CC request with 250 characters and it's being transferred successfully over to HSRM. Tested with multiple test users and seeing the same results across the board. Please find attached the screenshot for reference:
![Error](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/fe64128b-7ee5-4806-b7f7-6d4751f3bd7a)

@ldelacosta - This passed validation, please close the defect. Thank you!

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
