### ISSUE TITLE
Determine format of Map

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44498]
## Questions to evaluate:
How do we make it easily consumable while also making it comprehensive?
What are the top / most important pieces of information to map?
Consider multiple iterations dependent upon needs/consumer
How do we map out "reports to"?
How do we map out Platform-Platform and Platform-VFS links/bridges?

-Gaps
-connections
-Perhaps visually: how to make sure connections are clear? and rightly represented?

-rollup for customers of each product on a team

Note:  teams tend not to talk/think about who their customers are.  May be able to surface these voids

Map Mural: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661266120803/aa3069d80fc9a3137a519fe3def0f42d1b27bff7?sender=u4397b715dc3690a417b71483

Correlation Mural:
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661278901419/0c0f38ec98df4b2e188625688eae505e53f08f63?sender=u4397b715dc3690a417b71483

Data reference:  https://airtable.com/appbYNZ8PkZY7o9vs/tblXHp3UQAcjuotNa/viwNjGJl7am1QN2yD?blocks=hide

## Tasks
- [x] Workshop the above questions
- [x] Synthesize discussion points

## Pivot
We decided to survey teams about their offerings to fill out what we've learned from desk research.  This will inform the map's format.

**Comment by twoangstroms** [comment]
Possibility: a node/edge map for showing teams that are connected and the nature of their connections (perhaps using MindMeister or Tableau).

**Comment by tayism** [comment]
Something to consider: How might this mapping change, or our way of thinking about it change, once the Platform Spike Teams 'roll off'?
