### ISSUE TITLE
3 Implement monitoring for MHV identity dependency

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#445]

**Comment by annaswims** [comment]
Completed with https://github.com/department-of-veterans-affairs/devops/pull/5211
we have a pagerduty alert if the success rate for authentication attempts drops below 20% for 5 min

And a graph to monitor http://grafana.vfs.va.gov/dashboard/db/site-authentication?panelId=19&fullscreen&orgId=1&from=now-2d&to=now
