### ISSUE TITLE
Document Platform Github teams in Confluence

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#44529]
## AC
- [x] Ensure all Platform teams have an associated Github Team listed on their Confluence home space
  - [x] Leadership - https://vfs.atlassian.net/wiki/spaces/LEAD/overview#Github-Team
  - [x] Infrastructure
  - [x] SRE
  - [x] Platform CMS
  - [x] Console Services
  - [x] Release Tools
  - [x] Design System
  - [x] Analytics & Insights
  - [x] QA Standards
  - [x] Platform Content
  - [x] Governance
  - [x] Service Design
  - [x] Platform Security
  - [x] Console UI
  - [x] Forms Library
  - [x] IET
  - [x] CIT
  - [x] AMT

**Comment by little-oddball** [comment]
Updated [spreadsheet](https://docs.google.com/spreadsheets/d/1Elk0gubDJ3cTSvXTJ7I5yQfe5UHITXQwfRm3ZIgE4N0/edit#gid=0) created by Jonathan and filled in all the current information. Many of the GH Teams were previously created and I need to request access to work and make modifications. Those requests have been made and are for:

- [ ] cms-infrastructure
- [ ] platform-console-services
- [ ] platform-release-tools
- [ ] platform-design-system-team
- [ ] vsp-analytics-insights
- [ ] qa-standards
- [ ] platform-content
- [ ] platform-governance-team
- [ ] vsp-service-design
- [ ] vsp-security

**Comment by little-oddball** [comment]
This was completed and additionally there have been organization shifts and teams coming off contract that drastically change the landscape for platform teams.
