### ISSUE TITLE
Documentation - Github vs Confluence

### ISSUE THREAD

**Issue by girldadmk** [department-of-veterans-affairs/va.gov-team#44526]
AMT needs to decide where to post all operational and maintenance documentation.

**Hosting on Gitlab**
Pro

Cons
Oddball owns Confluence
Gitlab easier to PDF

**Hosting on Confluence**
Pro

Con

**Comment by kjduensing** [comment]
Closing. We have a ton of stuff in confluence already. Will revisit if desired
