### ISSUE TITLE
AWS access for Kevin Shih

### ISSUE THREAD

**Issue by kevinshih613** [department-of-veterans-affairs/va.gov-team#44536]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Kevin Shih

### Your Email

kevin.shih@adhocteam.us

### Team, Role, and Company of the target individual

Kevin Shih, UX Researcher, Ad Hoc LLC

### Product Manager (PM) name and email

Mike Compton, mike.compton@adhocteam.us

### Product Owner (PO) name and email

Andrew Fichter, andrew.fichter@va.gov

### Desired AWS Access

I need to access the transcription service to transcribe interviews that we conduct with non-Veteran users, and also to S3 buckets dvpuxresearchinput and dvpuxresearchoutput

### Access Expiration

ongoing

### Additional Notes

I need this access so I can transcribe the user interviews I conduct for Quokka and other Delivery Platform teams. I would like to be granted ongoing access so I wouldn't need to make requests for every project I do on Lighthouse. Thank you!

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
Closing ticket as its starting to get stale. If AWS is required please complete requirements prior to submitting request
