### ISSUE TITLE
Update documentation on creating new applications to include information on react routing

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44530]
### Description

When looking at https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application, I don't see any indication that the revproxy config needs to be updated for routing to work correctly. Perhaps the page could link to https://depo-platform-documentation.scrollhelp.site/developer-docs/routing or include a short summary and a link?

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application
- https://depo-platform-documentation.scrollhelp.site/developer-docs/routing

**Comment by taylojill** [comment]
Hello Katy and Carol. We received a request (via the platform footer website) to update documentation. Let us know if you have questions. Thanks!

**Comment by k80bowman** [comment]
This should probably be reassigned to the Release Tools team (@rmessina1010). They own this documentation (I added it to the platform site when I was a member of that team, but I am on the Design System team now).

**Comment by taylojill** [comment]
Hi Ray. Per Katy's request, I am reassigning this to you. Let me know if you have questions. Thanks!

**Comment by taylojill** [comment]
Adding Lainey.

**Comment by rmessina1010** [comment]
added the following to the documentation , under _4. Create the file you referenced in the entryFile property above_ :

> Note: you must  [update revproxy config](https://depo-platform-documentation.scrollhelp.site/developer-docs/routing#Routing-ReverseProxyConfig) to reflect the addition of your application in order  internal links via react-router to work properly.

This should publish by Tue Oct 4,  due to platform-confluence publishing schedule. the issue can be considered closed.

**Comment by rmessina1010** [comment]
This update is now live  in the developer docs. Closing  issue.

**Comment by taylojill** [comment]
10/4/22 - Document updated and published on Platform web site. Closing ticket.
