### ISSUE TITLE
Update existing PW product outline with new KPIs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44531]
Acceptance criteria:

- [ ] Update existing Platform website product outline with defined baseline KPIs: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2064613465/Platform+website+product+outline

Notes:
These are the KPIs being tracked for the Platform website: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2284584976/2022+Q3+Health+Metrics+Initiatives

Link to domo dashboard from here as well: https://va-gov.domo.com/page/1182586883

**Comment by taylojill** [comment]
8/25/22 - Updated existing Platform website KPI tracking page with defined baseline KPIs (2 tables + DOMO link).
