### ISSUE TITLE
[Design] Update Wireframes to Use New Memorable DS Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44542]
## Tasks
- Pull in VA DS library for the new Memorable DS component
- Update the Abstract wireframes for LoROTA Security Updates to use the new Memorable DS component from the library

**Comment by benbrasso-agile6** [comment]
I'm seeing the up/down arrows in the Month and Day fields in the pre-check-in and check-in abstract files

Here's the link to the component - https://design.va.gov/components/form/memorable-date

**Comment by ytsaoca** [comment]
Need to update both date and name error status![Screen Shot 2022-08-11 at 10.01.43 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/df30ad47-b15a-4e31-b99b-72b1bbe0d5b4)

**Comment by loripusey** [comment]
@ytsaoca if there are any engineering tickets that are needed as a result, please create a ticket and add it to the CIE Tech Debt epic. Thanks.

**Comment by ytsaoca** [comment]
Need to discuss whether we want to make error messages that applies to each date field. Started [this thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1660231164839969)![Screen Shot 2022-08-11 at 10.11.47 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/b51d0dde-5382-4afa-b352-712518be16e5)

**Comment by ytsaoca** [comment]
@kristenmcconnell @zach-park 

Check-in: https://share.goabstract.com/2eb369e0-bb14-49c2-8217-418bfb70d857
Pre-check-in: https://share.goabstract.com/b8944533-7b60-4d7e-8bff-26b1d02acc15

**Comment by kristenmcconnell** [comment]
<img width="886" alt="Screen Shot 2022-08-11 at 4 09 16 PM" src="https://user-images.githubusercontent.com/66287082/184232766-e5877e4d-f8b6-463a-a52c-9e8860a702a0.png">
This page in pre-check-in doesn't look updated.

**Comment by ytsaoca** [comment]
Updated the page.

**Comment by zach-park** [comment]
@kristenmcconnell I believe this branch needs to be merged to the master. 
@ytsaoca , I noticed that you also had a couple of additional task(s) in the same branch, would it mess up anything if you merge it now? Ideally, each ticket/task should be a separate branch. So please let us know.

**Comment by kristenmcconnell** [comment]
Yes, we should merge this branch when timezones go live at the end of the sprint. But @ytsaoca, let us know if everything else that Zach mentioned can go too.

**Comment by loripusey** [comment]
Timezones are not going live at the end of the Sprint; CHIP is still doing spikes; DOB is going live at the end of the sprint
@kristenmcconnell @zach-park @ytsaoca
