### ISSUE TITLE
Verify Logic to Identify CVT Appointments with VAOS

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44554]
## Description
We need to verify the logic that Shawn Adams identified for us for how CVT appointments are managed in other VA applications.

## Tasks
- Meet with VAOS to verify the logic
    - Q for VAOS: how are you visually displaying the Patient's appointment? And, was there Veteran research completed as part of this?
    - Agree on how we want to handle CVT appointments in Pre-Check-in and Check-in
    - Make sure we invite an engineer from CIE and an engineering from CHIP

## Logic to Identify a CVT Appointment
- Are there 2 appts for same patient on same day that are 0-5 minutes apart?
    - Yes
        - Does one of the 2 appts have a telehealth stop code?
            - Yes
                 - These 2 appts are part of a CVT appt
            - No
                 - Stop
    - No
        - Stop

## How We Will Want to Treat a CVT Appointment
- Display the one that DOES NOT have the telehealth stop code to the Veteran in Pre-Check-in and Check-in
- When Veteran checks-in for their in-person appointment that is part of a CVT appointment, we also want to complete check-in for the doctor-side appt

**Comment by kristenmcconnell** [comment]
@kristenmcconnell To coordinate the meeting invite with VAOS, CHIP, and Check-in.

**Comment by kristenmcconnell** [comment]
Message sent to Jeff Roof and Chris Horton to identify CHIP and VAOS team members, who should join the meeting.

**Comment by kristenmcconnell** [comment]
Put a meeting on the calendar for August 2 from 3 - 3:30. I'm adding @acrollet and @randomsync to this ticket, so they can help document any findings from the meeting.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell and @benbrasso-agile6 (or other UXers) should sync up with VAOS team who is just about to run a study on displaying different modality types and names. Peter and team are also working with Danielle and team on naming of the modalities. 

We should reach out and see how we can collaborate. 

Right now, they're using a structure of modality type at location/facility. Could be worth testing the opposite. E.g., location/facility with modality type.

**Comment by acrollet** [comment]
The VAOS team was not aware of the CVT appointment modality and wasn't sure how they are displayed. I've [reached out](https://dsva.slack.com/archives/CMNQT72LX/p1659468479548199?thread_ts=1658506566.213739&cid=CMNQT72LX) to try and get access to the MAS source to see what the logic is for detecting CVT appointments and how they are categorized, which should give us a better idea of how they are displayed in VAOS.

**Comment by loripusey** [comment]
@acrollet do you need a f/u ticket for this?
@loripusey

**Comment by acrollet** [comment]
@loripusey IMO we just need to keep this ticket open, I don't consider it resolved yet.

**Comment by loripusey** [comment]
Meeting with VAOS on 8/10/22:
- CIE wants to learn about CVT appointments, how VAOS identifies them and how they are displayed to end users, we want to mirror what VAOS does
- How does VAOS identify telehealth appointments
    - Has an associated Clinic that is a telehealth clinic (i.e. has a stop code that belongs to a list maintained internally)
    - Is a video appt in Vista
- I explained our logic given to us by Shawn Adams to them and they agreed it sounds right
- Brad Crosby's team
    - MAS v1 is read only
    - VAOS service - has write ability
    - MAS v2 (accesses new VAOS service)
- EAS is same team
    - Long-term where we are heading
    - Will replace all of these services
    - Building right now but does not exist
    - Is there a sand box? No
    - Are there docs? No
    - Will be fire(sp?) compliance
    - No test env yet
- We should reach around mid November about EAS
- Mentioned that we should only return the appointment relevant for the patient (patient vs. provider stop codes???)
- Is there VAOS service documentation? Have some Swagger docs in Atlassian
- Talked about us potentially providing access to check-in link to VAOS in the future

**Comment by acrollet** [comment]
This is on hold until we have access to the MAS source to verify the logic.

**Comment by acrollet** [comment]
MAS merges appointment data to create a logical single appointment as mentioned above. Ultimately VAOS doesn't have to check appointments in, so I don't think they're as concerned with the distinction between the patient-side and provider-side appointments as we are. When we revisit this topic we should ask Shawn for a sampling of CVT appointments so that we can verify our logic for determining the provider and patient side. Ultimately we'll want CHIP to have the same concept of a logical appointment, so that we can deal with a single appointment on the vet-facing side and have CHIP take care of handling the check-in correctly. (That is if we haven't moved to using EAS in the meantime)

**Comment by loripusey** [comment]
Here are the [notes ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/cvt-appointments/meetings/meeting-notes-07202022.md) from our meeting with Shawn; the logic and functionality we proposed for us based on the info from that meeting (i.e. eCheck-in) was the following.  Does this make sense now based on what you have discovered @acrollet?:

- If there are 2 appts for same patient on same day that are 0-5 minutes apart (probably 95%) (VAOS & My Healthy Vet)
    - If one has a telehealth stop code
        - Don't display the one that has the telehealth stop code
        - Do display the other
        - When check-in then do check-in for both of them

**Comment by acrollet** [comment]
@loripusey that makes sense based on what I've seen, however there's nuance in that I think we'd have to pull the provider name from the non-telehealth appointment.

**Comment by loripusey** [comment]
Sounds good, I mainly just wanted to get our thoughts down so when we pick this back up we will have a path forward.
