### ISSUE TITLE
VAOSv2 next Feature Toggle 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#44559]
## Item Description
We will need to create a feature toggle for the `vaos-v2-next` work. All the tickets with the label `vaos-v2-next` will be behind the new toggle. 

---

## Tasks
- Add `va_online_scheduling_vaosv2next` feature toggle

## Acceptance Criteria: 
The toggle is created for VAOS

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by jenniemc** [comment]
@ldelacosta For consistency, can we name the toggle flag `va_online_scheduling_vaosv2next` ?

**Comment by ldelacosta** [comment]
The feature toggle has been added for `vaos-v2-next`. Closing out the ticket.
