### ISSUE TITLE
Review OKR Blog post by Christina Wodtke and Discuss as leadership team

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#44561]
### Description

Before we set another round of objectives, let's look at what we provided teams for Q3, read [Christina Wodtke's blog post](https://www.workboard.com/blog/wodtke-okrs.php) on OKRs, and discuss what we did well and what we didn't do well in a retro style. 

### Acceptance Criteria

- [ ] Everyone reads the blog post
- [ ] Everyone fills out this [retro board](https://easyretro.io/publicboard/alLxJJd6gUZDC7DGAlKiZuTMB6M2/243fe3a5-92d1-4aa8-9ad4-5fb26b5cfcdb) before the leadership meeting where we want to discuss it

### Subject Areas

- [X] Product
- [X] Design
- [X] Engineering
- [X] OCTO-DE

**Comment by little-oddball** [comment]
I added mine

**Comment by nsmith1982** [comment]
I also added mine

**Comment by naomimarcussen** [comment]
done

**Comment by EWashb** [comment]
Feels like this might have been done a bit last summer. I think we can close this one. Any objections @andreahewitt-odd ?
