### ISSUE TITLE
[Analytics] [FE] Evaluate GA Events

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44570]
## Engineering Tasks
- Make a list of all events that we have

**Comment by brianseek** [comment]
Events:
API call - all api calls
Back button/Back to appointments - back-button-clicked
Check-in button - cta-button-click, check-in-attempted-after-expiration
Demographics - yes-to-demographic-information, no-to-demographic-information
Emergency Contact - yes-to-emergency-contact-information, no-to-emergency-contact-information
Next of Kin - yes-to-next-of-kin-information, no-to-next-of-kin-information
Landing page - landing-page-launched-no-token, malformed-token
Day of Appointments page - refresh-appointments-button-clicked

**Comment by brianseek** [comment]
@benbrasso-agile6 above are all the events that I could find in the applications. I feel like we only saw the API events in GA when we were looking together. Have you seen any of these other ones? Which of these if any should we keep and get working in GA?

**Comment by benbrasso-agile6** [comment]
Will take a look, thanks

**Comment by benbrasso-agile6** [comment]
Going to move this ticket back to Current Sprint. Next step is to meet with platform team. Scheduled for 8/23.

**Comment by loripusey** [comment]
Can you include me in the meeting @benbrasso-agile6 ?

**Comment by loripusey** [comment]
Closing this ticket as Brian completed the work to make the list. We can f/u in new tickets.

**Comment by benbrasso-agile6** [comment]
Yeah, I would say we should create a new one. I can certainly put in tasks and AC.
