### ISSUE TITLE
Access for Dan Shank

### ISSUE THREAD

**Issue by Clark-W-Griswold** [department-of-veterans-affairs/va.gov-team#4457]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Dan Shank
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name: Product Support Team
   > Company Name: Oddball
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

@department-of-veterans-affairs/vsp-operations Environment Access Request

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7Opiq+m/Vz5n9V9HMLhimTItMJVmmO4Udt+lOEWc+3gQw7MtxJ0bTI8bWg7yaQj+dmqGOhzxMggb+3Z/46Nm2HktClYgDGu4HRAL2Vnl/+bff4eb25ysOQ1HxW379eO2ja0E9IYIJddDo7wgEKAo6jYT8VG4/BLrUloUVOF0BoyCcnPXghUU/+7b5M+Yfo18KNSAhpS5ajdg1MgLooposZPmoQ6FnBim4i0agQLc8V63VGSJDpWjSzAqNDc841xKR5PQuGeeAsDzoP+1cBbcQYeEQGjWWQF60s6R96/rgoezZR887bWQvmN8q83u4VirpsgjWGjA2ysp699Et7P4c8yyD3peKz1pVNIm7PpIemLTIyTmcSJH5a+UkNWSasmzMt1Dnoqz8kIBtlPpjufz7rf7k7TNBY4UfnKe7IdaIxvE4qqBZ2XPOFzBPD2I+SUWs+m8Qi/1HBWit557sDzZmMiTUotsoyUZkwEHW345tpNT8zXUqiGe5eDKLh8N61ZKsYdQwowSTIB0JxpzYfzK1gyDpo3kvP1BGSKQYdC9iW5foycYrWv4fE4oYqkCUSLhR0T2nEJmYXhxMTQ/qyUxRNnd0ULtbeAYc/tM7LX1ieEaCZD3nxMrcjMjDreXPobONDnqtqz6dNIRVsiDjerau+3qDPkDU92So8liAaJzV5w== dan.shank@oddball.io
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Yourself  
User: Dan Shank

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.
