### ISSUE TITLE
[spike] Discuss PDF encryption issue with Platform

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#44589]
## Background
We are using `pdftk` to decrypt PDF files in `vets-api`. `pdftk` doesn't support AES256 encryption, which is available as an extension to PDF v1.7. Currently we are returning an error to the user indicating that we can't unlock their file, so there isn't an immediate need to fix this, but it would be nice to not have this be an issue, as we don't indicate to the veteran what the issue with unlocking their file is. `pdftk` is used throughout `vets-api` so we will probably need to discuss this issue with Platform. NOTE: we are currently on the latest version of `pdftk` so we may need to find a different library to use if we want to be able to decrypt PDFs encrypted with AES256

## Spike
- Investigate Sentry logs to determine severity of issue.

**Comment by jacobworrell** [comment]
Next steps:

- Define problem space for other Platform teams
- Provide evidence (data) supporting our claims
- Submit recommendations and/or potential approaches to Platform.

**Comment by jerekshoe** [comment]
Sentry log for this issue here
http://sentry.vfs.va.gov/organizations/vsp/issues/95118/?project=3&query=encryption&statsPeriod=90d

**Comment by data-doge** [comment]
@CorySohrakoffUSDS recently began looking into this issue. See https://gist.github.com/CorySohrakoffUSDS/a8c4784f4a08eb2bed562c7324746839 and https://dsva.slack.com/archives/C04KHCT3ZMY/p1706047457654769.
