### ISSUE TITLE
Contact Center Review for [MOVE - 1095-B Hybrid MVP for Accessibility replaces MVP in staging from April/2022]

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44593]
# Request the Contact Center Review 

## What this form is for

Use this template to request a Contact Center review of your product.
Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 
## Description

**1095-B Accessible MVP**
Form 1095-B reports the months a person had qualifying minimum health coverage to the IRS. The VA sends this form to Veterans to show what months they were covered under the VA healthcare system. In most cases, it is simply a form for one's records. However, some states still have an individual coverage mandate, and in those states, the form is necessary for filing taxes. The form is not required by the IRS, but it is required to be sent by health care providers as of 2019.  Our product provides Veteran's digital access to download the 1095-B in both PDF and an accessible txt format

### Launch Date
We hope to be in staging by August 2022 with launch following closely

### Version Number
- [x] Version number of video Accessible MVP v1

### Product Guide
- [x] Product guide link in GitHub also attach document below

### Product Video
- [x] attaching link to video

### Product Video Transcript
- [x] upload link to video transcript here and attach below

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by tameracorson** [comment]
@starlow00 For some reason, I cannot upload the video to this ticket.   I  know carl sent the Zoom link and I have successfully uploaded to Slack here.   Please advise if you the video emailed to someone or if you can just upload it from DSVA Slack 1095-B  https://dsva.slack.com/archives/C02TUH5U3HS/p1658585114309979

**Comment by tameracorson** [comment]
Product guide GitHub link here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/Content/Call Center Review/Accessible 1095-B MVP Product Guide Contact Center Review 7.26.22.pdf

**Comment by tameracorson** [comment]
Video transcript here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/Content/Call Center Review/Accessible 1095-B MVP Video Transcript Contact Center Review 7.26.22.pdf

**Comment by tameracorson** [comment]
@Kimberley2019 @starlow00 Please review our contact center review artifacts for acceptance.

**Comment by starlow00** [comment]
Hi @tameracorson. Sorry, I was on vacation. I will begin my review of this today and get comments to you asap!

**Comment by starlow00** [comment]
@tameracorson, the GitHub links to the guide and video transcript are coming up 404 for me. Can you please send me the guide draft itself as a Word attachment on this ticket? I can view the video Carl uploaded to Zoom.

**Comment by starlow00** [comment]
Video looks/sounds good.

**Comment by tameracorson** [comment]
Transcript in GitHub https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/Content/Call%20Center%20Review/Accessible%201095-B%20MVP%20Video%20Transcript%20Contact%20Center%20Review%207.26.22.pdf

**Comment by tameracorson** [comment]
Product guide https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/Content/Call%20Center%20Review/DRAFT%20product_guide_-_contact_center_review%20030922.docx

**Comment by tameracorson** [comment]
@starlow00 The original links look broken .... strange?  Anyhow, relinked above today.   I will email both yo you as well.  Linking @CarlDickerson for visibility

**Comment by starlow00** [comment]
Hi @tameracorson. My comments are attached. Nothing major, save for a few of the photos needing higher resolution replacements. Once you have a clean copy to share with me, I can forward to VEO CC. 
[IRS_1095B_Tax_Form_Healthcare_srt_082022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9223321/IRS_1095B_Tax_Form_Healthcare_srt_082022.docx)

**Comment by CarlDickerson** [comment]
> 

@starlow00 It looks like an older draft version of the product guide was shared to you from Github (prior to design change) when Tamara updated the link. Apologies for this! I have looked over your comments, made a few necessary adjustments and uploaded the most recent iteration of the product guide. Please find attached here.
[Product_Guide__CCR_IRS_1095B_Tax_Form_Healthcare_082022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9237345/Product_Guide__CCR_IRS_1095B_Tax_Form_Healthcare_082022.docx)

**Comment by starlow00** [comment]
Hi @CarlDickerson. The direct URL to the form that the product guide lists (https://www.va.gov/records/download-your-irs-1095-b) still comes up as a "Sorry—we can't find that page" error. Is that link going to go live later?

**Comment by tameracorson** [comment]
@starlow00 It will go live after staging.   It is in prod here http://preview-prod.vfs.va.gov/preview?nodeId=44346

**Comment by starlow00** [comment]
Sending to VEO for review.

**Comment by tameracorson** [comment]
@starlow00 How long does VEO review take?   tagging @CarlDickerson for tracking purposes.

**Comment by starlow00** [comment]
No AVA updates. Attaching current guide version here. 

[IRS_1095B_Form_Healthcare_082022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9283994/IRS_1095B_Form_Healthcare_082022.docx)

Video link (PASSWORD: 6AyV+3WC): https://themostudio.zoom.us/rec/share/VZCtcCYOfiUUys2qtrZPhjt74btico84JBnFwZGdTCIvnSYMJPaMCIQYsOcPqPDd.8AgdB8ewGxeIkFbj?startTime=1658498497000
