### ISSUE TITLE
[Ongoing Service] User Surveys - Implement Medallia for VFS Work

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4460]
## High Level User Story
As a VFS team, I need support for adding veteran user survey analytics tracking to my launches and enhancements so I can track the health and growth of my products.

## Hypothesis/(es)
**If**  we support product teams in adding Medallia analytics tracking to their product launches and iterations **then**  we expect platform products to record the data needed for KPIs and product decisions.

## Assumptions
- VSA and VSP work together to determine best practices and the process by which Medallia surveys are tracked 
- VSP owns Medallia implementation
- VSP has the resources to maintain Medallia implementation

## Goals
Product launches and edits includes Medallia metrics tracking. Requests for platform analytics hardening are met.

## Details & Notes
VSP Analytics & Insights works closely with VFS team product managers to implement Medallia on VA.gov applications.

### Links
- [Historical ForeSee information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/foresee)

### Product Outline
Medallia Product Outline TBD

### Areas for Discovery
The determine process and best practices will be located in the data wrangling super epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/350

### VSP Objectives
`O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.`

### VSP Key Results
- % of Customers tracking KPIs for their products.
- % customers meeting analytics standards

## KPIs
- % of VFS applications with tracked Medallia surveys

**How we will track the KPIs** Planned on #1336 

## Definition of Done
- N/A

**Comment by jwoodman5** [comment]
Standard surveys are now automatically added to all VA.gov pages. Custom surveys are handled on an issue by issue basis. An ongoing service for this is no longer needed. Closing.
