### ISSUE TITLE
Fix the refresh bug

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#44603]
## Issue Description
This issue addresses the refresh bugs that were encountered in the FE.

## Tasks
- [x] Update the calls to `refreshProfile` in Redux to ensure that 401's when the SiS are attempted aren't necessarily updating the loggedInStatus.

## Acceptance Criteria
- [x] The refresh works as expected

**Comment by nsoutouras** [comment]
:partying_face:
