### ISSUE TITLE
Contact Center Review for Patient Check-In - LoROTA Security Updates

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#44614]
## Description

Patient Check-in allows Veterans to check in for their scheduled VA medical appointments using their smartphone. A Veteran or an authorized caregiver can check-in up to 30 minutes before and 15 minutes after their scheduled appointment. To complete check-in, a Veteran:

- Views a poster hung on the walls of the clinic waiting area where they have their scheduled appointment.
- Follow instructions on the poster to scan a QR code or text “check in.”
- Receives a text message with a unique link, such as https://www.va.gov/c/xxxxxxx/.
- Taps on the unique link on their phone and begins check-in on VA.gov.
- Reviews, or has confirmed, contact, next of kin, and emergency contact information within the last seven days.
- Remains in the waiting room until a staff member takes them back for their appointment when ready.
- Pre-check-in allows veterans to use their mobile phones to confirm if their contact, emergency, and next of kin information is up to date. Veterans can most often complete pre-check-in at least 7 days prior to their scheduled appointment, but the timing is based upon the facility’s setup. Veterans are unable to pre-check-in after 12:00 AM on the day of their appointment. 

**This feature release contains a security update for LoROTA, which changes the identity verification from last name and last 4 of SSN to last name and date of birth.**

Further information can be found in our [release notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/detailed-release-notes/lorota-security-updates.md).  

### Launch Date

This feature's launch date is planned for on or around 8/4/2022.  

### Version Number

1.4

### Product Guide

[PRE-CHECK-IN_PRODUCT_GUIDE tracked changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9144503/PRE-CHECK-IN_PRODUCT_GUIDE.tracked.changes.docx)

[PATIENT.CHECK-IN_PRODUCT_GUIDE tracked changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9144505/PATIENT.CHECK-IN_PRODUCT_GUIDE.tracked.changes.docx)

### Product Video

In progress. 

### Product Video Transcript

In progress. 

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by benbrasso-agile6** [comment]
@loripusey FYI

**Comment by starlow00** [comment]
Hi @benbrasso-agile6. Here are my drafts. Once you are good with these, if you wouldn't mind sending me clean copies
[PRE-CHECK-IN_PRODUCT_GUIDE.tracked.changes_srt_07202022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9155041/PRE-CHECK-IN_PRODUCT_GUIDE.tracked.changes_srt_07202022.docx)
[PATIENT.CHECK-IN_PRODUCT_GUIDE.tracked.changes_srt_07202022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9155042/PATIENT.CHECK-IN_PRODUCT_GUIDE.tracked.changes_srt_07202022.docx)
 to share with VEO, that would be great. Thanks!

**Comment by benbrasso-agile6** [comment]
Good catch on the SSN reference that was still in there

**Comment by benbrasso-agile6** [comment]
Thank you for the review @starlow00. Here are the updates: 

[PATIENT.CHECK-IN_PRODUCT_GUIDE.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9162289/PATIENT.CHECK-IN_PRODUCT_GUIDE.pdf)
[PATIENT.CHECK-IN_PRODUCT_GUIDE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9162291/PATIENT.CHECK-IN_PRODUCT_GUIDE.docx)

[PRE-CHECK-IN_PRODUCT_GUIDE.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9162290/PRE-CHECK-IN_PRODUCT_GUIDE.pdf)
[PRE-CHECK-IN_PRODUCT_GUIDE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9162292/PRE-CHECK-IN_PRODUCT_GUIDE.docx)

**Comment by starlow00** [comment]
Thanks @benbrasso-agile6. I'll send over to VEO for their review.

**Comment by starlow00** [comment]
Sent to VEO for review

**Comment by benbrasso-agile6** [comment]
The new release date is ~8/4. I will edit the description of this ticket as well to reflect that.

**Comment by starlow00** [comment]
No changes from VEO. Attaching up-to-date copies here, closing.
[PRE_CHECK_IN_PRODUCT_GUIDE_v1_4_07262022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9213690/PRE_CHECK_IN_PRODUCT_GUIDE_v1_4_07262022.docx)
[PATIENT_CHECK_IN_PRODUCT_GUIDE_v1_4_07262022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9213692/PATIENT_CHECK_IN_PRODUCT_GUIDE_v1_4_07262022.docx)
