### ISSUE TITLE
Spike: Github + Login.gov dual auth to Grafana

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44613]
This has been touched on before, but what happens when I authorize with Github to Grafana one day, and the next I use Login.gov? Are my roles preserved? Do I represent the same entity?

**done when we answer**:
- [x] What's the default behavior?
- [x] How confusing is the default behavior on a scale of 1 - 3 (1 is lowest) for the users logging into Grafana?
- [x] What's the workload (1 - 3) on AMT to correct the default behavior manually?
- [x] What's the workload (1 - 3) on AMT to automate a better experience than the default behavior?
- [x] Are my roles preserved?

**Comment by kjduensing** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Access-Management---Platform-Spike-Team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/44613?planning-poker) with ZenHub @calquisola @iriteshp @kylesoskin

**Comment by girldadmk** [comment]
@kjduensing I am interested to know the effort required for this ticket.

**Comment by kjduensing** [comment]
@calquisola this ticket was blocking #37859. Did we answer the questions above?

**Comment by calquisola** [comment]
### What's the default behaviour?
Github and Keycloak will give you different roles. Roles will determine what you can do with grafana. 

###  How confusing is the default behavior on a scale of 1 - 3 (1 is lowest) for the users logging into Grafana?
3 -  could be really confusing and frustating if they don't have the same roles

### What's the workload (1 - 3) on AMT to correct the default behavior manually?
Needs research. Need to find out how github defines the roles in Grafana. 

### What's the workload (1 - 3) on AMT to automate a better experience than the default behavior?
Needs research. Need to find out how github defines the roles in Grafana. 

### Are my roles preserved? 
Roles are determined by your IDP.
