### ISSUE TITLE
Configure Login.gov for Grafana

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44611]
In order to get around some cookie setting problems, we need to update the Login.gov prod app config to include the redirect URL of the Grafana auth callback.

**Done when**:
- [ ] Login.gov prod app config has been accepted

**Comment by kjduensing** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Access-Management---Platform-Spike-Team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/44611?planning-poker) with ZenHub @calquisola @iriteshp @kylesoskin

**Comment by calquisola** [comment]
I've added the redirect URI for grafana. 

@kjduensing, please request Login.gov for this update.

**Comment by kjduensing** [comment]
![image.png](https://images.zenhubusercontent.com/603e8a65ddcfabcb0d550ba7/79a59ae3-e2e0-43e5-b3ab-c3efdb8f663a)

**Comment by kjduensing** [comment]
![image.png](https://images.zenhubusercontent.com/603e8a65ddcfabcb0d550ba7/39593bf8-d6c3-4a7d-bacc-93dfe9e4be50)

**Comment by kjduensing** [comment]
![image.png](https://images.zenhubusercontent.com/603e8a65ddcfabcb0d550ba7/a0f4f9fd-e3d6-4f96-975e-a0edf09ceb96)
