### ISSUE TITLE
[Bug] Rated Disabilities - Dynamic page copy doesn't match design comp

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#4462]
On Staging's [Rated Disabilities dynamic page](https://staging.va.gov/disability/view-disability-rating/rating/), the actual copy doesn't match the copy shown in the [design comp](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL):

NOTE: The **bolding** below highlights specific COPY mismatches, not styling.

1. In combined-rating box:
    * 1st sentence:
        * Actual copy (on Staging): "...claims that are still **pending**."
        * Expected copy (shown in comp): "...claims that are still **in progress**."
    * 2nd sentence:
        * Actual copy: "...the **claim status** tool."
        * Expected copy: "...the **Claim Status** tool."
1. Individual ratings heading:
    * Actual copy: "**Individual disabilities**"
    * Expected copy: "**Your individual ratings**"
1. Right rail:
    * Under "How did I get this rating?":
        * Actual copy: "...and information from other **sources.**"
        * Expected copy: "...and information from other **sources, like federal agencies.**"
    * Under "Learn about VA disability ratings":
        * Actual copy: "**To see how your combined VA disability rating was determined**,..."
        * Expected copy: "**To learn about how we determined your VA combined disability rating**,..."

#### Staging:
![rated-disabilities-copy-defect-01](https://user-images.githubusercontent.com/587583/71607163-47232200-2b34-11ea-89a5-3d77eac69a53.png)

#### Design comp:
![rated-disabilities-copy-comp](https://user-images.githubusercontent.com/587583/71607251-f102ae80-2b34-11ea-84eb-523f021679e8.png)

**Comment by sporeboy** [comment]
Copy should match after text revisions hit staging. There is an outstanding PR for #4300 (content adj, for Rated Disabilities).

**Comment by tlei123** [comment]
All copy mismatches now fixed via #4300.  Closing this now.
