### ISSUE TITLE
[Design] Update Wireframes for Physical Location

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44629]
## Tasks
- Wireframes need to be updated so that all pages that have appointment information show Location for in-person appointments (if no data then label does not display); these pages include:
    - Pre-Check-in
        - Landing page
           ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9f676e2d-2b7b-46dd-9a54-e6ee545b8163)
        - Completion page
          ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/d967d2a8-7b56-449f-9737-f154682f332d)
    - Check-in
        - Appointment List page
         ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/3b219b12-ca15-41f0-82d5-089e24404c64)
        - Completion page
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/d02f71ef-4cba-4d22-a338-4daf0cd9f25e)

**Comment by loripusey** [comment]
@ytsaoca Did you do this work as part of the wireframes for Type of Care & Doctor's Name?
cc: @sarahknoppA6

**Comment by ytsaoca** [comment]
@loripusey Yes, I did this work as part of the wireframes for Type of Care & Doctor's Name. I've finished it.
'cc @sarahknoppA6
