### ISSUE TITLE
Fix React Test App depdendabot alerts

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44632]
Dependabot has alerted some security issue in our repo. We should fix these since the React test app is a reference implementation that folks will use and possibly attempt to copy parts of the code base for use in their own applications.

https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app/pulls

**Comment by kylesoskin** [comment]
@kjduensing This seems like an easy one I could pick off quick if you want.

**Comment by kylesoskin** [comment]
Going to take this today, and merge 1 by 1 and confirm functionality between each.
