### ISSUE TITLE
SOCKS access for Jami Gibbs

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/va.gov-team#44634]
### Your Name

Jami Gibbs

### Your Email

jami.gibbs@adhocteam.us

### Your Role and Team

Engineer - Design System Team

### Product Manager (PM) name and email

Carol Wong - Carol.Wong@oddball.io

### Product Owner (PO) name and email

Matthew Dingee - matthew.dingee@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjmM3Yv72kj98W0MXuoVeRdoEzViRFulG95mI3oiZzmi0pTrrn3Zjve9HfrPBf1hdpnzgP1TsZaqmLjAGuGHSfCq8gk0nxwmvNjr8uR9d0J0bvxaYZ38qPc2i/snEvsquWo9pzhRNcgjULHKCyWYGnreFI2+IBOu0hiqJGMmCWzAhwZAlQYpLXMMGuXH0Bq77YBeDNjx03i42SRgG6axQTk9Xtw2vfvoWKcvrTOn5g7YVRUFccWZxjpFaHZPU61nK9Qvao46cuFkT1Hjksm7JwyB2V9TIYFFUqWKMFpRtNJsw+6yn5djnF6hIRdF10oFfhFjlw+hhNPqm1P+B4MUI49OkqXsMuPwvpo5EETwd7ElVGxW9oW+9Ied7hZ6JdERSm78LO4zO/3FWtU5N2RyRvAo+TQHwXj5t+QCoRMMWQKJ6EvVQ7DmayLbUy0xD2YSzQ+jyc+ZYPjzwsWjTXCek8n/JoOmqJV2DHq7aN6nHLlvWFVS2xDiP5J3/w5QcQQwc= jamigibbs@jamis-mbp.lan

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
