### ISSUE TITLE
AWS access for Kerry Powell

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#44643]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Kerry Powell

### Your Email

kerry.powell@adhocteam.us

### Team, Role, and Company of the target individual

Platform SRE, Front-end Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Mike Chelen, michael.chelen@va.gov

### Product Owner (PO) name and email

Mike Chelen, michael.chelen@va.gov

### Desired AWS Access

vsp-sre group, reference Gino Perlangeli's permissions

Please also grant lambda function/create, dynamoDB access, EC2 instance create/write. SRE wants to investigate options to move the support slackbot to AWS as a lambda or k8 and begin migrating support request data to dynamoDB.

### Access Expiration

Ongoing

### Additional Notes

I need ongoing access to fulfill my role as a SRE.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
User found in vfs team roster

### For AWS Access
User: Kerry Powell
COR: Vilay Senthep
VOR: Amber Malcolm
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by td-usds** [comment]
AWS Access approved

**Comment by jsgarmon** [comment]
First-time login instructions sent via Slack DM.
