### ISSUE TITLE
[Application Hosting and Deployment] Develop MVP of Helm Chart that can be used to deploy applications to EKS

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#44646]
## Description 
Platform Crew teams need a standardized packaging format that they can use to deploy applications to the platform's delivery infrastructure 

## Background/context 
- See parent epic for more information 

## Acceptance Criteria
- [x] A helm template is developed and available in its own separate repo

**Comment by jhouse-solvd** [comment]
In a conversation with @ph-One on 8/1, we decided that this is in a good MVP state. However, there should be a follow-up task to validate the helm template by deploying XYZ service(s) using the template. ☺️

**Comment by jhouse-solvd** [comment]
We are developing a basic Helm template in #46184

This issue can be closed.
