### ISSUE TITLE
[Application Hosting and Deployment] Process for promoting applications to higher environments 

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#44647]
## Description 
Platform crew teams deploying applications to EKS using ArgoCD need a standardized way to promote applications to higher environments (ie staging, production, etc). 

Currently, teams use the "application onboarding" template to deploy an application to dev. However, there is not yet a process to follow to promote the application to higher environments. 

## Background/context
- See parent epic 

## Acceptance Criteria 
- [ ] A process is established for promoting applications to higher environments 
- [ ] The process for promoting applications is documented

**Comment by ph-One** [comment]
Keep in mind application lifecycles: changes that go into dev but never go beyond. Are there IAM changes that are needed?

**Comment by ph-One** [comment]
Do not confine yourself to what we have today. If there is a better approach and it requires adjusting infra or Argo, let's do our part and flesh out what that looks like

**Comment by jhouse-solvd** [comment]
@jsgarmon & @rmtolmach et al - Thank you both for the great work here. Please link any relevant sub-tasks or PRs as we go.

**Comment by jsgarmon** [comment]
Basic process I just went through with goldilocks in staging:
1. Create a new project in ArgoCD
   - update `projects` in `chart/values.yml` – put in a PR and merge
   - cd to the `vsp-infra-argocd/chart` directory
   - ensure your on the main branch and pointed to the same commit as origin/main
   - ensure your context is pointed to utility
   - `helm upgrade argocd . -n argocd --values values.yaml`
   - you should see the new project in https://argocd.vfs.va.gov/settings/projects

2. Add Helm files for deployment to the correct path
   - deployment lives in `vsp-infra-application-manifests/apps/<app_name>/<env_name>/`

3. Update app-of-apps – to be automated
   - add application name to `vsp-infra-application-manifests/apps/argocd-apps/<env_name>/values.yaml`

4. If migrating an existing project, also remove from old app-of-apps
   - remove entry from `vsp-infra-application-manifests/apps/vsp-operations/argocd-apps/<env_name>/main.jsonnet`
   - steps 2-4 can be bundled into a single PR

5. Update team roster to create GH teams and assign members
   - exact process TBD

**Comment by jhouse-solvd** [comment]
@jsgarmon - looks like good work here. is there anything else needed to close this one out?

**Comment by jsgarmon** [comment]
Created [Promote an Application in the EKS Infrastructure (As a VSP team)](https://vfs.atlassian.net/wiki/spaces/OT/pages/2324037840/Promote+an+Application+in+the+EKS+Infrastructure+As+a+VSP+team) to document this process.
