### ISSUE TITLE
Optimize vets-api build time

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4464]
## Background

Our vets-api builds are painfully slow for how little changes. Other variables such as dependabot (or other automatic builds) also slow things down.

We should identify work paths to improve this build time, thereby improving the E2E data-driven happiness of those devs working on this codebase. 

**This epic needs grooming and further issue definition. Opening as placeholder for discussion.**

**Comment by ricetj** [comment]
Will revisit this after the docker push for vets-api. side note: Bill is doing some work here to help and Taylor is doing work with Jenkins that may help her as well.

**Comment by ricetj** [comment]
Some work is in the process to cut this time down, but the step after that will depend on the larger Infrastructure work in the pipeline.

**Comment by wyattwalter** [comment]
Hey @kfrz is this something you want to prioritize soon and kick off this discussion? Anything we can do at this point?
