### ISSUE TITLE
[BE] On-site notifications: Bug -- notifications should show in reverse chronological order

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#44650]
## Background

Good news! DMC just sent another round of notification requests to us, and we are seeing additional on-site notifications on My VA. 

The bad news: notifications are showing in chronological order. They should be showing in reverse chronological order.

![image](https://user-images.githubusercontent.com/34068740/180044411-288b6ed1-6eeb-42bc-94ef-c528108ae32a.png)

## Tasks

- [ ] Update code so that notifications show in reverse chronological order.

## Validation
- **Who can validate this ticket? (FE, BE, Design, PM)?** Any team member
- **How can this work be validated?** log in to staging using test user 36, ensure that notifications for 7/19/22 show above notifications for 7/12/22

**Comment by ajakabcin** [comment]
We discussed this in grooming and best practice is usually to have filtering like this done on the backend. @tmitchellgcio is going to connect with @tpharrison on this to get his thoughts.
