### ISSUE TITLE
Adjust default drive time radius (BE)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4465]
## Problem Statement
The current default drive time radius of 10000 minutes does not address a business or user need and is contributing to Facility Locator's latency issue.

FYI from [Health Care Options through VA](https://missionact.va.gov/library/files/MISSION_Act_Community_Care_Booklet.pdf)

- Mission Act designated access standards: 
   - within 30 minutes average driving time for primary care, mental health care, or non-institutional extended care services
   - within 60 minutes average driving time for specialty care
- Previous eligibility for Veterans Choice Program: “40 mile” eligibility criterion  (resided more
than 40 miles from the nearest VA medical facility with a full-time primary care provider)

## Goal
- Faster urgent care search performance

## Objectives or Key Results this is meant to further
- Improve Veteran experience 

## Tasks
[ ] Determine distance from map center to farthest edge
[ ] Determine time, assuming 80 miles an hour
[ ] Reset default 
  
**Note:** changes to the functionality for user map interaction will be handled separately. 
  
## Acceptance criteria
**Expected output for this issue:** 
Recommendation for possible changes to default drive radius to improve usability and performance.

**Comment by mmiddaugh** [comment]
Should we be asking our users about drive time preferences? 
Are there industry standards for this?

**Comment by mmiddaugh** [comment]
PPMS max is 500 miles/250 minutes

**Comment by davidconlon** [comment]
@mmiddaugh @darkbushido 
Correct me if I'm wrong, but I think that this may be moot.
When PPMS 8.1 is finally released we will no longer be required to submit drive time.

Instead, all searches should be based upon the default radius of the map, currently 80 miles but may be reduced at some point.

Can you confirm?

**Comment by davidconlon** [comment]
Drive time is no longer required by PPMS.
Closing issue.

**Comment by darkbushido** [comment]
It is no longer required and we need to remove it from the params we send when 8.1 is released
