### ISSUE TITLE
[Sidekiq-UI (Staging)] - Application onboarding infrastructure request

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#44666]
## Summary
IET is in the process of promoting our sidekiq-UI service from development to staging

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

---

## Description of application
_Sidekiq-UI is a web-based admin panel for viewing and debugging sidekiq queues._

### Basic info:
**Team Name:**   
[platform-pst-iet](https://github.com/orgs/department-of-veterans-affairs/teams/platform-pst-iet)
**Application Name:**  
Sidekiq-UI  
**Functionality:**  
Backend tool
**Language/Stack:**  
Ruby + Rack
**Ports/Networking needed:**  
Port 3002 for standard plain HTTP
**Other infrastructure needed:**  
N/A

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] **GitHub repo:** https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui
- [x] **Dockerfile:** https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui/blob/main/app/Dockerfile

### Application delivery pipeline (CI/CD)
- [ ] **AWS service account for GitHub actions**, ie `svc-gha-team-name` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [ ] **AWS Elastic Container Registry (ECR) repository for the app container:** _provide name of ECR repo here_  
_Infrastructure Team_ | [PRs welcome](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)  
- [x] **Automation to release and tag the app's GitHub repo with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation. 
_Requesting team; Infrastructure Team can assist_  
- [x] **Kubernetes manifest in YAML, Jsonnet, or Helm Chart** https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/platform-pst-iet/vets-api-sidekiq-ui/staging
- [x] **Kubernetes detect and update application** in `vsp-infra-applications-manifests` | [Environments](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/argocd-apps)  
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to update the Kubernetes manifest** when a new version of the app's container is pushed to ECR | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/update-manifests.yaml)  
_Requesting team; Infrastructure Team can assist_

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** 
- [ ] **AWS SSM Parameter Store parameters that the app needs to run,**

**Comment by ewilson-adhoc** [comment]
**Open questions:** 
- Should we need different service accounts and ECRs between staging and development?

- I believe the infrastructure team set the following variable for development `/dsva-vagov/vets-api/dev/redis_sidekiq` -- could the team create `/dsva-vagov/vets-api/staging/redis_sidekiq` containing the connection string for the staging redis instance

**Comment by jhouse-solvd** [comment]
Hi @ewilson-adhoc! Thanks for submitting this request. We are currently working to develop a process to allow platform crew developers (including Spike teams) to promote applications to higher environments. (See #43550). 

I'm curious to know if this request can wait for us to develop that process? We don't want to block your work for too long, but I feel like this application (and your team) would be a great candidate for using that new process. We'd love to get your feedback from that process so that we can make it work well for you. 

Let me know your thoughts on timing?

**Comment by ewilson-adhoc** [comment]
@jhouse-solvd we're actually mostly done with this request :) 

The only thing that we need from your team is to populate `/dsva-vagov/vets-api/staging/redis_sidekiq` otherwise we can close this out.

**Comment by ewilson-adhoc** [comment]
My team was able to find the variable and populate it ourselves. This can be closed out now
