### ISSUE TITLE
GIBCT: Wrapped Extension Campus Names Are Not Indented Properly

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4466]
When viewing a profile page for an institution that has extensions, all of the extensions are listed in the "School Locations" section. Some of the institution names are long enough to wrap. The second line of an institution's name should be indented the same amount as the first line. Currently, the second line is not indented enough. Examples are highlighted in red below:

![Screen Shot 2019-12-31 at 9.36.29 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/fda4c6bf-65db-4b80-a34c-5f77d1cc186a)

**Comment by hughes-dustin** [comment]
branch: bah-4466
PR:  https://github.com/department-of-veterans-affairs/vets-website/pull/11415

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-01-03 at 11.08.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2fc00e48-e9b8-4aee-8fb3-32de49c3b805)

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
Changes are in staging. Closing bug.
