### ISSUE TITLE
10-10EZ: Specific Error Messaging

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44664]
10-10EZ users a generic message when the submission fails, provided by the platform.

If we want to provide a different (more specific) error message, we'll need to add it ourselves.

There used to be an error message that stated, _If you'd like to complete this form by phone, please call..._

Suggestion: Can we reuse the error message from the 10-10CG?
- The CG error message has the PDF download attached to it
- Will need some additional verbiage updates to make it accurate to the 10-10EZ

## Content and design mockups

- The VA currently allows applicants to download a PDF copy of the 1010EZ, which is included in the error messaging as an alternative to the online tool:
     - [About VA Form 10-10EZ](https://www.va.gov/find-forms/about-form-10-10ez/)

There are two slightly different versions of the error message: authenticated and unauthenticated:

- [1010EZ authenticated error message](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGqo581)
- [1010EZ unauthenticated error message](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nR30o4z)

**Comment by nicko-amida** [comment]
@hdjustice Here's the updated [10-10EZ confirmation error page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGqo581). Couple of questions I'll ask the team during our next meeting:
- If the user is signed in, all their info stays in the form right?
- The current messaging says "you won't be able to resubmit", but is there a time factor involved? I'm wondering if something similar to "try again later" can be included on the EZ and CG.

Thanks!

**Comment by hdjustice** [comment]
thanks @nicko-amida - One thing we have to keep in mind is that the 10-10EZ does not have the PDF generated.  That is in the backlog, but Lihan did mention it would take a couple months of work to implement that.  So we may have to consider a different message now and add the PDF download option later..

**Comment by nicko-amida** [comment]
@hdjustice Yep that makes sense for the completed application, but this one is just a blank pdf application, like the one on [this 10-10EZ form page](https://www.va.gov/find-forms/about-form-10-10ez/). I thought that was something we could already do?

**Comment by hdjustice** [comment]
You are right, I was thinking the PDF with all the info in it. The blank one should be good then.

**Comment by hdjustice** [comment]
@nicko-amida I've been thinking about this.. I like that we want to revamp the error message, but that blank PDF thing, I dont know if that is a good experience, but if that was the only option, then maybe its ok.  We can keep working through it, but just something i was thinking about

**Comment by nicko-amida** [comment]
@hdjustice Ok here's another update! There is now an [authenticated error message](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGqo581), and a slightly different [unauthenticated error message](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dl3xLP9). I think it's easy to distinguish between sign-in / signed-out from an engineering standpoint, but I still want to ask a couple questions.

**Comment by hdjustice** [comment]
I like the language for the unauth version, it at least says they will have to complete it again.

**Comment by nicko-amida** [comment]
Closing with my updates to the issue - see "Content and design mockups" above.

**Comment by nicko-amida** [comment]
!! We are apparently unable to distinguish between authenticated/unauthenticated. The design has been updated to reflect this in front-end issue #45667. The message is the same for users whether they are signed-in or not.
