### ISSUE TITLE
Meet w/ Slack support point of contact

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44663]
AC:

- [x] Schedule the meeting with point of contact

Meeting topic ideas:

- Discuss how other Platform teams are currently using the Slack form workflow
- We should understand the options available to us within the Slack form process, before we commit to our own workflow

Some questions to ask:
- Who gets assigned to the entry? Can we add entire team?
- How do other teams triage tickets to themselves?
- Do teams create a ticket in zen hub for it?
- What levels of assistance do other teams consider? Quick reply vs requires a fix in the content vs considerate amount of planning, strategy and collaboration, etc.
- What do teams consider "closed"?

- [x] Hold the meeting

- [x] Document our meeting takeaways

**Comment by laucon** [comment]
Kerry Powell
