### ISSUE TITLE
OOO procedure for leadership

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#44661]
As the leadership team is growing and changing, we need to solidify a process for reporting OOO and creating OOO documentation 

Draft here: https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1688666178/Out+of+Office+OOO+Schedule

AC: 

- [x] Create way to let rest of leadership team know you're going to be out
- [x] Create process for OOO Doc
- [x] Create OOO doc template
- [x] Be clear about threshhold --- more than 2 business days

**Comment by EWashb** [comment]
This looks pretty well documented in the link above and is currently being used in the PLatform. I think we are good to close. I'll check off the ACs. Feel free to reopen if you see fit.
