### ISSUE TITLE
Staging review:  Design System Team: Button pair web component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#44671]
## Description
The Design System Team has built Button pair web component which we are submitting for Staging review. 

Link to component: 
https://design.va.gov/components/button/button-pair

## Zoom recording
Meeting Recording:
https://oddball-io.zoom.us/rec/share/eKQwW4qdVigTjvLUVKz69WoX91_Czn2fotx9Fc-JgBqeDkq-84ncMALNwxlVcqfV.A1P1r3ukhRXSDBl_

Access Passcode: BdnAH%3!

**Comment by allison0034** [comment]
No design feedback, thank you

**Comment by jimuhh** [comment]
No IA feedback. Thanks!

**Comment by CherylEvans** [comment]
No Content Feedback.  Thank you!

**Comment by briandeconinck** [comment]
No accessibility feedback, thank you!

**Comment by andresriveratoro** [comment]
Thank you all!
