### ISSUE TITLE
Supplemental Claims | Add Contestable Issues

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44672]
## Value Statement

**_As a_** user
**_I want to_** select the issue that I am contesting 
**_So that_** I can efficiently file a supplemental claim.

## Background Context

Claimants need the ability to add contestable issues to their claim, so VRSs know which issues to check against with the new and relevant info they are submitting.

## Tasks

- [ ] 

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Possibly a duplicate of #44610 - if we copy the pattern used by HLR, both the contestable issues and legacy issues are fetched by the backend and combined, then passed on to the frontend.
