### ISSUE TITLE
Raise address confidence threshold from 80 to 90

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4468]
## Issue
If the user enters an address and the validation/suggestion API returns a single confirmed address with a confidence score >80, we go ahead and save that suggested address for the user. This mirrors the existing behavior on VA.gov. However, in testing we found that there is a `575 20th St, San Francisco CA` 94107 and a `575 20th Ave, San Francisco CA 94121`. Same number and same street name, but one is a _street_ and one is an _avenue_. Now let's say you live on the Avenue but you accidentally enter your address as `575 20th St, San Francisco CA, 94121`. Note: you entered your correct zip code, but accidentally entered `St` instead of `Ave`. The API returns a single suggestion for `575 20th St, San Francisco CA 94107` (note that the zip code does not match what the user entered) with a confidence score of 88. Thus we will take that single suggestion and assume that's what the user meant. This is an example where we should really be asking the user to confirm that they entered the correct address.

## Suggested fix
Raise the confidence score threshold from 80 to 90. This will result in users being prompted to confirm their address more often, but would prevent some edge cases where save an address for the user that they didn't intend to save.

**Comment by erikphansen** [comment]
@Justin-Pickett @Samara-Strauss This would be a quick fix on my end.

**Comment by Samara-Strauss** [comment]
Sounds good to me!

**Comment by erikphansen** [comment]
It looks like making this change will also prevent the profile from changing zip codes at all, which I think is a good thing. It seems right to confirm with a user before we make a change to the zip code as they entered it.

**Comment by Justin-Pickett** [comment]
@Justin-Pickett Need to validate - 

Enter home address zip code incorrectly. 
Verify if you receive a suggestion to verify the correct address  works the way its intended.

**Comment by Samara-Strauss** [comment]
Validated!
