### ISSUE TITLE
Update Choose a VA Clinic Page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#44688]
## Description
We recently made an update to the VAOS FE logic to remove the 24 months filtering to 36 months for the appointment history (#39950). When the Veteran lands on the Choose a VA Clinic page (direct schedule flow), the description still states 
`In the last 24 months you’ve had {a/an} {type of care} appointment at the following {facility name} clinics:`
We would need to update the number from 24 to 36. 

For example: 
User ID: jacobreid.r.iasimone@id.me
<img width="606" alt="Screen Shot 2022-07-21 at 7 53 52 AM" src="https://user-images.githubusercontent.com/90797205/180208381-5cf5db25-8ba3-4803-9281-a5f3f79a43b6.png">

---

## Acceptance Criteria

Given when the user is in the direct schedule workflow 
When the user lands on the page "Choose a VA clinic" 
Then the number of months will be updated to 36 
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/clinic-selection.md#clinic-selection-copy-doc) 

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this issue was given a **Medium** priority

**Comment by aarathi-poldass** [comment]
Reviewed on 7.21.22 with PM and project leads and this issue was given a **Medium** priority

**Comment by ldelacosta** [comment]
@jenniemc - Please put this code behind the `vaos-v2-next` toggle. 

cc: @simiadebowale

**Comment by ldelacosta** [comment]
Validation has been completed. 

![Screen Shot 2022-08-23 at 10.34.09 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ad15b1af-9c0f-4c86-9772-4e22ebd429a7)

SQA can start validation in staging. 
cc: @marcynadeau

**Comment by beth-wodzinski** [comment]
This passes testing. @ldelacosta

**Comment by ldelacosta** [comment]
No issues reported.
