### ISSUE TITLE
Adding Edmund Dunn to DSVA Slack

### ISSUE THREAD

**Issue by dawnpruitt** [department-of-veterans-affairs/va.gov-team#44686]
Sitewide CMS has a new engineer starting 7/22 and he requires access to the DSVA Slack please. He will need access to multiple channels in order to efficiently collaborate and communicate with fellow engineers, his team, UX, etc. Thank you so much!

Please add edmund.dunn@agile6.com as multi-channel full member to the following channels:
# sitewide-cms
# vfs-all-teams
# cms-notifications
# cms-design
# cms-support

Thank you!

**Comment by LEHigley** [comment]
edmund is showing as a full member--can we close this?
