### ISSUE TITLE
Add Offboarding Security Issue to Pager Duty Drop Down list.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#44696]
# Description

There is a need to add a category to PagerDuty for security incident related to Offboarding.  There are incidents related to users not being properly off-boarded in the system. 

 [See Thread](https://dsva.slack.com/archives/C02FHGZQTPF/p1658250454876859)

# Tasks
- [ ] Add Category for Offboarding Security Incidents to Pager Duty.

**Comment by zachclarity** [comment]
Added new Pagerduty Service "Off-Boarding Request - Security".   This should resolve the [comment on the incident playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook).

**Comment by rmtolmach** [comment]
LGTM.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/10993987/180241506-b3204740-c9fd-4634-911c-38935b0f12e1.png">

Only issue is that you have to search for it. It doesn't show up in the dropdown. Opened https://github.com/department-of-veterans-affairs/va.gov-team/issues/44700 to cover that.
