### ISSUE TITLE
[07/25/22] Emergency Management Training Program

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#44726]
## Description
With the launch of the new emergency management in feature in VEText, there is a need to develop new training materials

---

## Acceptance Criteria
- [x] Create new training outline and materials
- [x] Review with team (Post to group channel)
- [x] Approved by Justin/Lindsay
- [X] Create training self-paced video
- [X] Add video to Sharepoint
- [X] Add training availability to Booking Page
---

**Comment by lindsay-insco** [comment]
Coordinate with @ahicksfearless for opening statement

**Comment by djfredvs** [comment]
Have added program description to the title slide. We are waiting for Justin to notify us of what users will be able to add or edit templates.
