### ISSUE TITLE
Expand on research report to include quantified data

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44723]

**Comment by MOStudioCarolyn** [comment]
Revised findings with Mikki's suggestions.[https://app.zenhub.com/files/133843125/a97c9451-37d3-4067-b0e6-6e3365a8f366/download](https://app.zenhub.com/files/133843125/a97c9451-37d3-4067-b0e6-6e3365a8f366/download)

**Comment by MOStudioCarolyn** [comment]
Revised findings from Mikki's feedback.
[https://app.zenhub.com/files/133843125/9bfcb86e-fd14-4eee-888a-7c8e7d219856/download](https://app.zenhub.com/files/133843125/9bfcb86e-fd14-4eee-888a-7c8e7d219856/download)

**Comment by MOStudioCarolyn** [comment]
Revised findings from Mikki's feedback

[https://app.zenhub.com/files/133843125/bb1999a8-f11b-45fc-9e25-ef4f9c71dd48/download](https://app.zenhub.com/files/133843125/bb1999a8-f11b-45fc-9e25-ef4f9c71dd48/download)
