### ISSUE TITLE
[08/01/22] VA Notify Message Template Access & Discovery

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#44734]
## Description

---

## Acceptance Criteria

---

**Comment by ahicksfearless** [comment]
- Communicated with Melanie Jones and I completed Github steps for access. Melanie will complete the process of giving me access on 7/26.

**Comment by ahicksfearless** [comment]
Now have access. 7/29/22

**Comment by lindsay-insco** [comment]
Connected with Melanie
