### ISSUE TITLE
Add instructions for setting up SSH key for Github authentication

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#44753]
### Description
It may be helpful to explicitly direct onboarding engineers to set up authentication with SSH key as part of their setup. We have had some engineers recently authenticating to VA repos with personal access tokens, which is non-standard and can cause some unexpected behavior. In particular, personal access tokens will not work for authentication with SSH git references, i.e.:
```
git clone git@github.com:department-of-veterans-affairs/vets-website
```

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools

**Comment by mchelen-gov** [comment]
originating slack thread: https://dsva.slack.com/archives/CU1E4CX9U/p1658424950038559

**Comment by timcosgrove** [comment]
Github's own documentation: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by taylojill** [comment]
Hello. A request to update documentation came in through the Platform website footer. Also see original Slack message thread above. Let us know if you have questions.

**Comment by taylojill** [comment]
Hello @rmtolmach @td-usds @jhouse-solvd A request to update documentation came in through the Platform website footer. Also see original Slack message thread above. Let us know if you have questions.

**Comment by rmtolmach** [comment]
Some thoughts:
1. The platform documentation you linked is about requesting access to internal tools, not specifically how to set up access to GitHub. 
2. In the SOCKS access video on the platform website (starting at 55 seconds), it demonstrates how to generate a PAT to log into GitHub. It also mentions that you don't need to go through those steps if you already connect to GitHub via ssh.
3. SOCKS access isn't limited to engineers, so oftentimes non-engineering folks are going through the steps in the video and the PAT will work fine for them, especially if they're not doing `git clone`s, etc. for their job. 
4. It wouldn't hurt to add github's documentation about adding SSH keys to your account https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account but I'm not sure where it would belong 🤔. It seems too specific for the [platform orientation onboarding](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D).

**Comment by rmtolmach** [comment]
I am adding some content to Platform Website for another ticket, so I can add something about this. How does this sound?
> If you use `git` in your daily workflow and have already [added your SSH keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account), skip to step 4. Otherwise, create a [GitHub Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) (with at least “repo” scope permissions). You will use this as your GitHub password when prompted. (As of August 2021, your GitHub password won't work here.)

^^that would replace this:
![image](https://user-images.githubusercontent.com/10993987/180883060-a2430dc7-7088-457f-bde5-d4a06578f991.png)
(from here: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy)

**Comment by rmtolmach** [comment]
I added that blurb ☝️. Edits will be published on Thursday. Closing issue.
