### ISSUE TITLE
NOD | Sending encrypted PDF files to Lighthouse

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#44766]
## Background
There are certain scenarios where `vets-api` sends an encrypted PDF file to Lighthouse as part of a Notice of Disagreement submission. The main issue we are experiencing with `vets-api` is that it attempts to create/send an unencrypted PDF **ONLY** if a password is sent along with the PDF file by `vets-website`.  This is an issue because `vets-website` is not currently able to detect whether certain PDF files are encrypted or not. Because of this, `vets-website` isn't guaranteed to prompt the user for a password and in some cases may send the encrypted PDF to `vets-api` without an accompanying password. When this happens, vets-api will send the encrypted PDF to Lighthouse. It is unclear whether Lighthouse checks the files we send it for encryption or not. 

## Considerations
* There are multiple issues, both with `vets-api` and with `vets-website` at play here. This ticket is only meant to address one of them
* The frontend issue with checking for encryption needs to be handled, but we should have checks in `vets-api` to ensure that we at least let the veteran know that we can't unlock their PDF
* CST attempts to unlock the file if a password is present, but also checks to make sure that the file is unencrypted before it is sent to EVSS; this is probably the approach we should adopt
* We should probably err towards the side of giving the veteran an error on the frontend if we are unable to unlock their PDF in favor of sending encrypted PDFs to downstream services

## Relevant code 92b6a09
* [FormAttachment](https://github.com/department-of-veterans-affairs/vets-api/blob/92b6a09/app/models/form_attachment.rb#L38-54)
* [DecisionReviewEvidenceAttachment](https://github.com/department-of-veterans-affairs/vets-api/blob/92b6a09/app/models/decision_review_evidence_attachment.rb) (Inherits from FormAttachment)
* [Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/92b6a09/app/controllers/v0/decision_review_evidences_controller.rb) (includes FormAttachmentCreate mix-in)
* [FormAttachmentCreate mix-in](https://github.com/department-of-veterans-affairs/vets-api/blob/92b6a09/app/controllers/concerns/form_attachment_create.rb) (Controller uses this mix-in)
* [Route](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/routes.rb#L83)

## Tasks
- [ ] Make sure that NOD PDF file uploads are unencrypted before they are sent to Lighthouse

## Acceptance Criteria
- [ ] If an encrypted PDF is encountered by `vets-api` we should always return an error unless we are able to successfully create an unencrypted copy of the PDF

**Comment by saderagsdale** [comment]
@kylesoskin FYI it looks like the info in this ticket explains that vets-api password PDF issue we talked about earlier today. Might be worth discussing with Jerek.
