### ISSUE TITLE
[BUG] veteran attempts to download Benefit Summary and gets "It says we found more than one account for you. Error code 106."

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44761]
## What happened?
Veteran has been log-in issues with accessing 'Download Benefits Letters'.
Error message that comes up is:
"It says we found more than one account for you. Error code 106."

He's cleaned out his cache multiple times but is still getting this error message.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: Veteran says same message comes in all their browsers (Edge,Chrome,Firefox) on Windows 10
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:  https://www.va.gov/records/download-va-letters/

- Log into app
- Navigate to Benefit Letter section
- Make appropriate selections
- Attempt to download Benefit Letter by clicking download button

- Test User _(if applicable)_:

## Desired behavior
Veteran is able to download his "Benefit Summary Letter" 

## Acceptance Criteria
- [ ] Identify the cause of a 106 error
- [ ] Determine whether benefits team can fix
- [ ] Fix bug or hand off to team that can

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by manalo-soco** [comment]
@jacobworrell  
Device was a Dell Windows 10 pc.

**Comment by jerekshoe** [comment]
### Notes
* `/records/download-va-letters` is on the drupal side, the react app starts at `/records/download-va-letters/letters`
* (vets-api) [Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/letters_controller.rb)
* The letters service uses EVSS
* When looking through the `vets-website` codebase, it appears that code 106 refers to the veteran having multiple Corp IDs [source](https://github.com/department-of-veterans-affairs/vets-website/blob/807fbb812a/src/applications/auth/components/RenderErrorContainer.jsx#L254-L268), but this is strictly related to login, and I'm unsure how they would end up seeing this specifically when they are doing things with the letters app

**Comment by jacobworrell** [comment]
This looks like a log in error, we recommend that EVSS looks into how/why a 106 error would come up for a user in this situation.

**Comment by manalo-soco** [comment]
@jacobworrell  Copy, thank you for looking into this. I forward to EVSS.
