### ISSUE TITLE
AWS access for John Weisz

### ISSUE THREAD

**Issue by johnmweisz** [department-of-veterans-affairs/va.gov-team#44765]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

John Weisz

### Your Email

weisz_john@bah.com

### Team, Role, and Company of the target individual

Team Pivot!, Software Engineer, Booz Allen Hamilton

### Product Manager (PM) name and email

Greg Feliberty, feliberty_gregory@bah.com

### Product Owner (PO) name and email

Andrew Fichter, andrew.fichter@va.gov

### Desired AWS Access

I need the same access as Derek Brown and/or Larry Crochet

### Access Expiration

July 14, 2024

### Additional Notes

I need access to execute maintenance requests for saml-proxy and oauth-proxy projects both of which team Pivot! is responsible for maintaining.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
User found in VFS Team Roster

### For AWS Access

User: John Weisz
COR: Courtney Bethea
VOR: Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
@iriteshp can you reach out to me via slack to discuss which permissions are actually requested (i.e. which permissions the referenced individuals currently have) or are the requested permissions just "_ access to execute maintenance requests for saml-proxy and oauth-proxy projects both of which team Pivot! is responsible for maintaining_"?

**Comment by td-usds** [comment]
AWS Access approved

**Comment by jsgarmon** [comment]
First-time login instructions sent via Slack DM.
