### ISSUE TITLE
Get Questions Answered

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44770]
## Questions
- Will Veterans need to have an existing account set up in BTSSS for PCI to submit a claim using the API?
- What unique IDs are available so we can match a Veterans using PCI with Veterans with a BTSSS account? 
- If there's not a way for us to determine if a Veteran has an account set up in BTSSS, can the travel office still review the claim if we submit it to BTSSS? 
- Are there accounts created in BTSSS for Veterans that don't have a direct deposit set up? If so, can the travel office still review claims that PCI submits to BTSSS? 
- Do you have a list of sites where Veterans are not eligible for travel pay. For example, Manila, Philippines.
- Are all Veterans that set up an account in BTSSS eligible to receive travel pay? Or, does eligibility review happen once a claim is submitted? 
- Do Veterans receive a confirmation email when they create a new claim in BTSSS? Or, any other notification such as a text message? If not, at what point do they first hear back about the status of their claim? And, is the notification an email, text, letter, etc? 
- Do Veterans receive a one-way reimbursement for showing up for a cancelled appointment? (For example, this was mentioned from Corpus Christi travel office.) 

## Tasks
- Get and document answers to these questions

**Comment by loripusey** [comment]
@benbrasso-agile6 FYI

**Comment by loripusey** [comment]
Patrick has a meeting with the Travel Office on the 28th; we can wait until after this meeting to tackle this ticket

**Comment by benbrasso-agile6** [comment]
@mdewey Here's our list of questions. Thank you!

- Will Veterans need to have an existing account set up in BTSSS for PCI to submit a claim using the API?
- What unique IDs are available so we can match a Veterans using PCI with Veterans with a BTSSS account? 
- If there's not a way for us to determine if a Veteran has an account set up in BTSSS, can the travel office still review the claim if we submit it to BTSSS? 
- Are there accounts created in BTSSS for Veterans that don't have a direct deposit set up? If so, can the travel office still review claims that PCI submits to BTSSS? 
- Do you have a list of sites where Veterans are not eligible for travel pay. For example, Manila, Philippines.
- Are all Veterans that set up an account in BTSSS eligible to receive travel pay? Or, does eligibility review happen once a claim is submitted? 
- Do Veterans receive a confirmation email when they create a new claim in BTSSS? Or, any other notification such as a text message? If not, at what point do they first hear back about the status of their claim? And, is the notification an email, text, letter, etc?

**Comment by benbrasso-agile6** [comment]
@randomsync Just wanted to let you know that this ticket exists with some questions ^^

**Comment by benbrasso-agile6** [comment]
Ben, add to Git

**Comment by benbrasso-agile6** [comment]
## Confirmed

- Veterans with a BTS3 account are eligible to receive travel pay. 
- Patient Check In should only allow Veterans to file a claim if they have a BTS3 account set up. If the account doesn't have a direct deposit set up, then Patient Check In can still submit the claim. 

## Open Questions for Travel Office

- Are we able to check the BTS3 database programmatically to determine if a Veteran has a BTS3 account set up? If so, how do we go about doing that?
- Does the BTS3 have functionality in place to hold a claim for ~36 hours before processing? If not, is that going to be built into BTS3 or would Patient Check In need to build that on our side? 
- Do you have a list of sites where Veterans are not eligible for travel pay. For example, Manila, Philippines.
- Do Veterans receive a confirmation email when they create a new claim in BTSSS? Or, are there any other notifications such as a text message? If not, at what point do they first hear back about the status of their claim? And, is the notification an email, text, letter, etc? Within Patient Check In, to the extent possible, we'd like to be able to set expectations on when or how Veterans will be notified about next steps. 
- Do Veterans receive a one-way reimbursement for showing up for a cancelled appointment? (For example, this was mentioned from the Corpus Christi travel office.)

 ## Open Items for Patient Check In

- Does the Patient Check In team foresee any issues building in the functionality to only allow Veterans to file for travel pay once per day?

**Comment by benbrasso-agile6** [comment]
@loripusey maybe we close this? Or, once we chat more tomorrow, we can figure out what the next steps are and what tickets, if any, we need to adjust or create.
