### ISSUE TITLE
[Design] MyHealth - Secure Messaging - Left nav work

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#44786]
Background: Some modifications may be needed on the left nav for Secure Messaging within the Health Apartment (MyHealth).   

Task: Work with the Design system & Drupal teas on the left nav.

**Comment by MarciMcGuire** [comment]
Thanks, @jonathanjnelson

**Comment by jonathanjnelson** [comment]
This work is included in the overall IA strategy of the Health Apartment - see ticket [42428](https://app.zenhub.com/workspaces/mhv-to-vagov-top-level-view-62619a987d74510018ecc546/issues/department-of-veterans-affairs/va.gov-team/42428)
