### ISSUE TITLE
Create templates for invitations to onboarding meetings

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#448]
## Goal
We need to formally invite teams to the various onboarding meetings.  These invitations should be 'templated' in the sense that they can be reused, and iterated upon, for each upcoming VFS team.

## Acceptance Criteria
- [ ] Template invitation for all team onboarding meeting
- [ ] Template invitation for engineering onboarding meeting
- [ ] Template invitation for design onboarding meeting
- [ ] Template invitation for product onboarding meeting

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by accbjt** [comment]
Link to Google Doc

https://docs.google.com/document/d/1tpRvaluPrH5uEXB4IXs9ajpdvl131beiNNJKIbQpLMk/edit

**Comment by smoonpeyes** [comment]
Added the welcome email template here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/templates/welcome_email_template.md
