### ISSUE TITLE
Plain Language writing exercises for VA.gov writers, editors, and job candidates

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#4480]
This issue can host writing exercises/tests given to new writers, editors, and job candidates for VA.gov content roles. The first document is a legacy page in Burials. We are tasked with taking that content and rewriting/editing it into plain language according to our VA stylebook, and adding it into an existing page as an accordion question and answer. 

@AnneHurley  can review and give feedback on the exercises. 
I will look for more examples to host on here. Writers/editors, when you're done with your pass on the content, please email back to ahurley@governmentcio.com so I can do my edits with you one on one.
[Writing exercise - headstone replacements]
(https://app.zenhub.com/files/66304117/3051e717-81cc-42ad-baee-d4c86ba2296b/download)

Resources when working on this exercise:

**A.
General Style and Voice Guidelines for website content**

This checklist is for banners, error messages, and short- and long-form informational content. Sometimes the text we work on needs a total overhaul (rewriting); sometimes it needs more of a cosmetic touch up (splitting one long sentence into two, employing contractions, substituting simpler words for more complex ones). Use the below checklist for either scenario.

- For short UX copy like banners or error messages, make sure there’s a header (title) for the message and place bold tags around it.
- Identify words that could be more plain language. Literally scan the text you're given (or that you've just written) for any red flags. In the past, we've seen "temporarily unavailable" and "currently" that we've changed to "isn't working right now" and "at this time" or "right now."
- Look at sentence construction and length with plain language in mind.
- Our target audience is the Veteran. Make sure the text speaks directly to the Veteran in second person. Address the Veteran as “you” rather than “the Veteran” or “Veterans”
- When referencing VA, use first person plural—"we" and “our” instead of "VA."
- Make sure the voice is friendly, sympathetic, helpful, and not formal.
- Be on the lookout for stilted-sounding text, where articles ("a" or "the" have been left out). For some reason, this unnatural-sounding style has been the standard on most websites for short messages, footer text, banners, etc. But we want our friendly, conversational voice to appear in all elements and locations on our site—whether design elements or error messages.
- If at all possible, use active voice. (Who does the action belong to? Who or what connects to the verb? If it's implied rather than written, it's probably passive voice.)
**Passive/Active voice example:**
**Passive:** All benefits decisions can be appealed.
**Active:** You can appeal any decision VA makes about your benefits.

**B.
Plain Language Guidelines**

Plain language uses:

- Common, recognizable words that often have fewer syllables than their more complex synonyms (“help” rather than “assistance” and “happen” rather than “occur”)
- Contractions (“don’t” rather than “do not”)
- Shorter sentences and paragraphs
- Bulleted lists and bolded subheads to organize or “chunk” content in a clear, scannable way
- A conversational style that’s straightforward and avoids jargon
- Definitions for terms or words that are not plain language but must be used. Define such terms using parentheses immediately following the term. Or, if that will make the sentence too long, define the term in a separate sentence.

**Comment by LouCarlozo63** [comment]
Thanks for this Anne!

**Comment by AnneHurley** [comment]
[Writer-editor plain language writing test]
(https://app.zenhub.com/files/133843125/727cc19d-9b6e-4411-af5b-635696bb318f/download)
@larrywest52 @kimmueller1 @psanders86 @LouCarlozo63 @lunascoop  @lwalsh617 @Karak888  @SgardnerPMP 

Hi all, @RLHecht  found the writer-editor test we took when we were hired to work on this project. It would be great for all writers and editors to take this test/exercise in your spare time. You can email me at ahurley@governmentcio.com when you're done with the test, as with above, and then we can go over them as we have time. 

A.

**Comment by AnneHurley** [comment]
Plain language demo from 12/31/19 retro presentation: https://zoom.us/rec/play/7MUodO6sqT43HIeU5QSDVvJxW9TuKKKs13Md8_oImEbgVyMGNVX0brYTYuZZAsUCxSDfL4XnzOGHqVOJ?continueMode=true

**Comment by Karak888** [comment]
This should not be tracking to any team's board this is for internal GCIO
