### ISSUE TITLE
Log "bad" addresses a veteran tries to save

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4481]
## Summary
We should use Sentry or Google Analytics to track the addresses that the VA Profile flags as bad and doesn't allow the user to save.

## Details
When the address validation API gives us an address validation error or does not return a validation key along with suggested addresses, we should log the address that was sent to the validation API. Will determine what data to send to GA and fill in the details here.

**Comment by bradl3yC** [comment]
@erikphansen I don't think sentry would be right for this.  Perhaps google analytics.  Is there some conversation we can link for this request?

**Comment by erikphansen** [comment]
We still need to determine the best path forward with this and likely coordinate with the analytics folks. My main concern is determining how we can easily get a list of all the bad addresses that we've logged.

**Comment by Justin-Pickett** [comment]
@erikphansen will groom this out a bit more.

**Comment by Samara-Strauss** [comment]
Samara will check in with the VA team on privacy concerns here.

**Comment by erikphansen** [comment]
@nedierecel If we wanted to use GA to log "bad" addresses (ie, addresses that the user is prevented from saving to their profile) how could we go about doing that? I'm thinking we could send something like this to GA:

```
{
    'event': 'profile-edit-failure',
    'event-data': '123 main st San Francisco CA 12345'
}
```

Once we start saving addresses to GA, would there be an easy way to get a list of all the addresses that users were unable to save to their profile?

**Comment by erikphansen** [comment]
@bradl3yC I am curious why you think Sentry isn't the right choice for this. There are times when we explicitly report to Sentry from the FE so this wouldn't be a new thing. But I'm also a noob with both Sentry and GA and my skills at digging through the collected data need a lot of help.

**Comment by nedierecel** [comment]
@erikphansen Unfortunately, this would violate GA's storage of PII, so we couldn't store it within Google Analytics. Here's the documentation: https://support.google.com/analytics/answer/7686480?hl=en

**Comment by erikphansen** [comment]
@nedierecel thanks for catching that early :) @Samara-Strauss FYI ☝️ So maybe this whole idea is a no-go, which kinda sucks IMO

**Comment by Samara-Strauss** [comment]
@erik @bradl3yC just heard back from @boris-ning-usds (developer on the VA.gov team) about saving bad addresses and he said the following:

> For the first question, it's possible to store those addresses, but it probably requires some paperwork modification (VA.gov Privacy doc [PIA or PTA] and Authority to Operate [ATO]) because we'll be technically storing PII. Lisa's right, it is considered PII in this case according to NIST guidance.

So I don't know that it's entirely a "no" that we can't do this, but it would probably take a lot of work that might not be worth it. Let me know your thoughts.

**Comment by erikphansen** [comment]
Maybe we should just track when these errors happen without recoding the address that caused the error. At least we can get a sense of how often users are told their address is bad.

**Comment by Samara-Strauss** [comment]
@erikphansen I think that is probably the best move going forward.

**Comment by lisac-usds** [comment]
if it's a Sentry server hosted in VA's cloud, that might be eligible for storing PII.  Although, would need to be cautious of any integrations (e.g. slack->sentry) that might allow content to be leaked.

Inconvenient, but with SaaS we have to verify its fedramp authorization when we consider using it to store PII. GitHub, for instance, meets the "low impact software-as-a-service" (LI-SaaS) baseline, which doesn't meet the bar for PII.  (my read of https://github.blog/2018-10-24-github-is-fedramp-authorized/, https://tailored.fedramp.gov/policy/#fedramp-tailored-lisaas-requirements)

I've learned some of this the hard way.

**Comment by Samara-Strauss** [comment]
@erikphansen any thoughts on @lisac-usds  post above?

**Comment by erikphansen** [comment]
@Samara-Strauss I'm asking on Slack to see if someone more qualified than me knows if we've done this in Sentry.

**Comment by erikphansen** [comment]
@Samara-Strauss in this slack thread Alastair recommended creating a temp database table to store the logged PII. Which also means it's something that @lihanli would have to do since all the logging would happen on the backend. https://dsva.slack.com/archives/CBU0KDSB1/p1578066013119600

**Comment by lihanli** [comment]
i looked in the code and i think we're already logging addresses that couldn't update, let me know what you want me to do with them

**Comment by erikphansen** [comment]
sweet. at this point I'm not sure but this seems like data worth having in case there is a useful way to help improve the validation API.

**Comment by erikphansen** [comment]
since it appears we are storing "bad" addresses already, I'm gonna close this and make a new ticket to simply track _when_ users are told they entered an invalid address in GA.

**Comment by Samara-Strauss** [comment]
Reopening temporarily. @boris-ning-usds @lisac-usds can you confirm this approach does not violate any privacy rules? It looks like we are already tracking addresses in Sentry. I'm genuinely unsure how to determine if this is OK or if we need to stop doing this. Any guidance would be helpful.

From Erik:

> @Samara-Strauss in this slack thread Alastair recommended creating a temp database table to store the logged PII. Which also means it's something that @lihanli would have to do since all the logging would happen on the backend. https://dsva.slack.com/archives/CBU0KDSB1/p1578066013119600 I believe he did something similar when we were trying to figure out the meaning of DD update errors.

From Lihan:

> i looked in the code and i think we're already logging addresses that couldn't update, let me know what you want me to do with them

**Comment by erikphansen** [comment]
@lihanli can you verify where/how the addresses are being logged? In Sentry or a temp DB table outside of sentry?

**Comment by lihanli** [comment]
the addresses are stored in the `personal_information_logs` table in the database, not in sentry, we are already storing SSNs and other PII in the database, it's my understanding that we are allowed to store PII in the database as long as we delete it after a certain amount of time. `personal_information_logs` records get deleted after 2 weeks

**Comment by Samara-Strauss** [comment]
@boris-ning-usds or @lisac-usds can you confirm this is correct? If so, we can close out this ticket.

**Comment by lisac-usds** [comment]
Lihan's description seems reasonable to me, but I'm not able to confirm the implementation or whether it supports PII appropriately, I'm sorry. I'll try to find someone who can advise.

**Comment by Samara-Strauss** [comment]
If this isn't raising any red flags and we're following all the rules or temp. storage of PII in Sentry, then we should be good. Closing.
