### ISSUE TITLE
<Accessible 1095-B MVP - Team MOVE> x Release plan

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44814]
## Acceptance Criteria
- [x] Make a copy of the [release plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) and add to the respective product folder
- [x] Complete release plan for launch

## How to configure this issue
- [x] **Attach to appropriate Epic**  
- [x] **Labeled with Team**

**Comment by tameracorson** [comment]
@shiragoodman Shira, above, it say's attach to appropriate Epic; do you know what that means?

**Comment by shiragoodman** [comment]
@tameracorson I'm not sure. What template did you use to create this ticket? It doesn't look familiar

**Comment by tameracorson** [comment]
@shiragoodman It was in the ZenHub template drop down and a requirement on the Security and Privacy review ticket ![image.png](https://images.zenhubusercontent.com/61856bab21cd5965714d703d/5bc0e395-1aa2-4a0e-ac01-8c1ded3260c4)   If this template is obsolete, I'll remove it.

**Comment by shiragoodman** [comment]
@tameracorson ahh gotcha. The "[Release Plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)" linked above is correct (when in use, it would be as a .md file), however we have never used this specific issue template. You likely can close this issue as Privacy, Security, Infrastructure Readiness Review only cares about the .md file

**Comment by tameracorson** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/1095b-release-plan.md
