### ISSUE TITLE
Review write up by Console UI team

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44822]
Acceptance criteria:

- [x] Everyone read this write up by the Console UI team about content strategy for the Console: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/edit/which-documentation-will-live-in-the-console-ui-vs-the-platform-website/rfc/2022/2022-07-13%20-%20Platform%20Wide%20Documentation%20vs%20Component%20Specific%20Documentation%20Locations.md?pr=%2Fdepartment-of-veterans-affairs%2Fva.gov-platform-architecture%2Fpull%2F33
- [x] Write down questions or comments about it
- [x] Discuss as a team
- [x] Provide feedback to Console UI team: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/edit/which-documentation-will-live-in-the-console-ui-vs-the-platform-website/rfc/2022/2022-07-13%20-%20Platform%20Wide%20Documentation%20vs%20Component%20Specific%20Documentation%20Locations.md?pr=%2Fdepartment-of-veterans-affairs%2Fva.gov-platform-architecture%2Fpull%2F33

**Comment by vbellissimo** [comment]
Vicky's questions:
Questions:

- What is an example of technical documentation that is relevant to all VFS users vs not?
- Is content from “Developer Docs” in the Platform website considered tech docs? Ex: https://depo-platform-documentation.scrollhelp.site/developer-docs/base-setup-vets-api
- Will content from “Developer Docs” in the Platform website transition to the Console? If so, does the content on the Platform website become obsolete? Do we continue to maintain in the Platform?
- How do we feel about #3 and #4?
- Where is this content hosted? https://platform-console-ui-dev.vfs.va.gov/catalog/default/component/platform-console-ui/docs/architecture/ci-cd/

**Comment by laucon** [comment]
Questions:
1. Is there any component-specific documentation on the Platform currently?
2. Would it be a huge problem if any documentation ends up on both the Platform and the Console simultaneously?
3. What does Vicky mean when she says "How do we feel about #3 and #4?"

**Comment by laucon** [comment]
4. Will there be any documents with both component-specific content and more general content? If so, how will we know where to place that? Will we have to separate out such content into separate docs?

**Comment by laucon** [comment]
5. I also want to note that I do like this idea and I wasn't sure if I would. But this does make logical sense to me.
6. With that being said, however, I can see issues arising of people not knowing where to put docs or find docs or knowing what category a certain document falls into. But we're not gonna know if those problems arise until we try this and see.

**Comment by taylojill** [comment]
Questions:
1.	“Collaboration Cycle” …add a definition
2.	Will the technical documentation be moved permanently from Git Hub repositories?
3.	Who will define the information architecture?
4.	Who will move docs from Git Hub to the Console?
5.	Would this include all component-specific technical documentation across all development efforts?
6.	This sounds like a major change in how things have been done in the past. How are they going to socialize the change?
7.	If a clear relationship between the Platform Console and the Platform Website documentation is the goal, how many docs will have to be touched in order to add references?
8.	If the Console UI system is retired, what happens then?

**Comment by SSimmorins** [comment]
Feedback:  

1.The intro section needs a little wording tweaking.
2. I like that they added a risks section, can we think of some other alternatives.  The thought of Confluence retiring is sorta scary.  Like when you add to the Platform you also add to Confluence via Scroll Viewport.  I wonder can we find a way to copy elsewhere for the Console.
