### ISSUE TITLE
Assess if we still need Lucid Chart

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#44827]
### Description

Now that we've moved away from roadmapping in LucidChart -- is anyone using it for anything else?

### Acceptance Criteria

- [x] Figure out if we still need to pay for LucidChart
- [x] If not, get rid of subscription 
- [ ] Let everyone on Platform know.

### Subject Areas

- [X] Product
- [X] Design
- [X] Engineering
- [X] OCTO-DE

**Comment by EWashb** [comment]
It was determined that we ARE still using this for engineering as of 5/2023. No access will be removed. Closing.
