### ISSUE TITLE
Adding Katie Riddle to DSVA Slack

### ISSUE THREAD

**Issue by michelle-d-smith** [department-of-veterans-affairs/va.gov-team#44820]
Adding Katie Riddle katherine.riddle@adhocteam.us to DVSA Slack as a full member she is the Ad Hoc program manager for VSP (VA.gov Platform).

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by michelle-d-smith** [comment]
github: [katieriddle](https://github.com/katieriddle)

**Comment by LEHigley** [comment]
showing as a full member
