### ISSUE TITLE
[FE] 10-10CG: Technical Discovery for Adding Inline File Rendering

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44839]
Placeholder ticket for discovery on the level of effort and complexity involved in adding a file rendering of documents uploaded to the 10-10CG for PoA / Sign as a Representative purposes.

**Comment by hdjustice** [comment]
This will probably end up being a design web component, in which case would be created and maintained by the design system or forms library.  Wanted to have this ticket out there in case we have time to look into it with the design system team.

**Comment by longmd** [comment]
A few notes here for this discovery:

- Effort range would be dependent upon use of external libraries. If using an external library to assist in the preview, then implementation would be more simple. If using an external library is out of play and the component needs to be fully built in-house, the level of effort is pretty great. It is worth noting that many external libs haven't been updated in a long while, so it could be an opportunity to review the codebase and reverse engineer a solution based on another possible solution.
- Preview component would need to be able to support multiple file types. In all my research xls and ppt files are widely unsupported in any external library. 
- Accessibility is a big question mark. PDFs and Word Docs seem to work okay but other file types lack accessibility provisions. 
- Here is an external library that has the largest list of supported file types: https://github.com/plangrid/react-file-viewer
