### ISSUE TITLE
Render File Uploads

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44833]
There are several features for 10-10EZ and 10-10CG that require documents to be uploaded that frequently receive either an incorrect or wrong file.  Adding a rendering of the file(s) uploaded will, hopefully, reduce the amount of erroneous documents that are received and improve the processing times for both applications.

*Current State*
Right now, there is no way to view the files that are uploaded within the applications themselves.  One needs to open the documents after they've been uploaded to confirm that they're the correct ones to have been uploaded.

*Problems*
- 10-10CG frequently receives incorrect PoA documents
  - Some are incomplete (only showing one page instead of the whole document)
  - Some are simply incorrect documents
- 10-10EZ has this issue to a lesser degree since there is only one specific document required

*Outcomes*
Implementing a rendering of the uploaded file(s) should reduce the number of erroneous documents received, meaning more applications can be processed with less corrections that need to occur.

*Phases*
1. Introduce file rendering to 10-10CG for PoA documentation
2. Introduce file rendering to 10-10EZ for DD-214

**Comment by hdjustice** [comment]
Closing this epic for now. We will not be pursuing this work at this time. We may revisit later if we feel this feature is needed to improve the experience. We would also be open to supporting the Design System team in creating a va.gov web component for all teams to use.
