### ISSUE TITLE
Disable "update" button if no address is selected

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4483]
The UPDATE button should not be enable until the user has selected an address option

The UPDATE button in this screenshot should not be enabled.
![disable this.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/21fa4dcc-48f0-4d99-a94a-e537f2292299)

**Comment by Samara-Strauss** [comment]
Question: Shouldn't the address be pre-selected if there is only one option like in the screenshot shown above? I would have imagined there wasn't a use case where the radio button could be deselected/was unselected.

cc/ @artistgreen to weigh in here

**Comment by artistgreen** [comment]
@Samara-Strauss - it should be pre-selected in this case.  And I think you're right about not being to un-select it.

**Comment by Samara-Strauss** [comment]
@erikphansen does that sound good? In cases where there is only one option to update (ie. no suggested addresses), the original address should be pre-selected.

**Comment by erikphansen** [comment]
It only preselects _suggested_ addresses. In this case this is the "bad" address the user entered and there were no suggestions. I don't think we want to encourage users to force through a potentially erroneous address by preselecting it for them.

**Comment by erikphansen** [comment]
And, yes, once you select it here you can't deselect it unless you selected another option.

**Comment by Samara-Strauss** [comment]
> It only preselects suggested addresses. In this case this is the "bad" address the user entered and there were no suggestions. I don't think we want to encourage users to force through a potentially erroneous address by preselecting it for them.

Ah, good point. I'm torn here. On one hand, we definitely don't want to encourage someone to choose a bad address. On the other, people are going to do what they want to do, and if they want to move forward with the address they entered, they'll do this whether we preselect the radio button or not. It's not common in UX to have unselected radio buttons; however, there are some use cases that make sense IMO. My final verdict on this one? I'm leaning slightly towards having this option remain deselected so it is in sync with the experience where there are suggested addresses, and so we are giving that slight but extra nudge for the user to review what they entered.

**Comment by Samara-Strauss** [comment]
Closing in favor of #4362
