### ISSUE TITLE
[Spike] VAOS Homepage Dead Ends 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#44846]
### Request
Product and Design team are requesting help from VAOS FE Engineering team to understand how the application handles dead ends on the VAOS homepage.

### Goal
The team would like to [update the user flows in VAOS](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=267%3A19373). 

### Screenshot of the alerts on the homepage 
<img width="1127" alt="Screen Shot 2022-07-25 at 4 36 58 PM" src="https://user-images.githubusercontent.com/90797205/180869673-6608a34b-96b5-4c09-b0df-5373c998e068.png">

---

## Tasks
- Answer the following questions:
  - Question 1: What triggers the alerts on the homepage? 
  - Question 2: Are there additional alerts not listed in the ticket? If yes, please provide mobile screenshots. 

## Time Box
4 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by simiadebowale** [comment]
'We’re sorry. We’ve run into a problem' Alert is triggered when:
-  veteran tries to open an appointment (this refers to all appointment kinds. va, cc, booked, pending... etc) details page and there's an error loading the veterans appointment details. I.E, api is down / there is an error in FE mapping.
- when a veteran is scheduling a new appointment and 'VA medical center or clinic' if there's an error with the facilities api endpoint, we show this error message.
- when there's an error with the eligibility endpoint while a veteran is direct scheduling.

**Comment by Cieramaddox** [comment]
@simiadebowale Can we confirm that the "We’re sorry, the new VA online scheduling application isn’t available right now" alert has been phased out?

**Comment by simiadebowale** [comment]
@Cieramaddox This is correct.

**Comment by outerpress** [comment]
@simiadebowale thank you for this. I have a few more questions on the 'We’re sorry. We’ve run into a problem' error:

> veteran tries to open an appointment (this refers to all appointment kinds. va, cc, booked, pending... etc) details page and there's an error loading the veterans appointment details. I.E, api is down / there is an error in FE mapping.

The screenshots show the error on the Your/ Past appointments lists:

* What triggers this error to show in place of the entire list of appointments? 
* Can you provide a screenshot of what the error looks like on the details pages, and request list?

> when a veteran is scheduling a new appointment and 'VA medical center or clinic' if there's an error with the facilities api endpoint, we show this error message.

* Can you provide a screenshot showing this state?


> when there's an error with the eligibility endpoint while a veteran is direct scheduling.

Does [this screenshot](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=253%3A41058) show that state? If not, could you provide a screenshot?

**Comment by simiadebowale** [comment]
@outerpress 

> The screenshots show the error on the Your/ Past appointments lists:
What triggers this error to show in place of the entire list of appointments?

- In general, we will show this error message if there's a FE bug causing errors in the application or if there was a error response from the backend services.

> Can you provide a screenshot of what the error looks like on the details pages, and request list?

Error message displayed in place of appointment details when we get an error returned by the appointments by id endpoint.
![Screen Shot 2022-12-19 at 5.24.57 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/e25f5998-5f2e-4588-bb25-dedf2d01dbe2)

Error message displayed in place of pending appointments when we get an error returned by the proposed appointments endpoint.
![Screen Shot 2022-12-19 at 5.31.30 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/9e120fc8-1abd-4127-a91c-0b8c61aad816)

> Can you provide a screenshot showing this state?


Start Scheduling > Select Type of care > Continue
This error message shows up if there's an error returned by any of the backend calls.
![Screen Shot 2022-12-19 at 5.33.51 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/050abe61-72ff-4911-ade8-25eed0394ec1)

> Can you provide a screenshot showing this state?
when there's an error with the eligibility endpoint while a veteran is direct scheduling.

The screenshot above is also how we display error message for this state.

**Comment by outerpress** [comment]
Thank you @simiadebowale ! I captured these in the user flows:

* [Home/upcoming appts errors](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1558%3A20120&t=Qh2CsX1jgPvqfwrT-4)
* [Upcoming details error](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1580%3A20179&t=Qh2CsX1jgPvqfwrT-4)
* [Past appts errors](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1577%3A19975&t=Qh2CsX1jgPvqfwrT-4)
* [Past details error](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1580%3A20048&t=Qh2CsX1jgPvqfwrT-4)
* [Requested/Pending appts error](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1577%3A19969&t=Qh2CsX1jgPvqfwrT-4)
* [Requested/Pending details error](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1580%3A20049&t=Qh2CsX1jgPvqfwrT-4)
* [Facility page error](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=1578%3A21187&t=Qh2CsX1jgPvqfwrT-4)

@ldelacosta this one can be closed out
