### ISSUE TITLE
EMIS deprecation: remove legacy code

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44859]
## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. Once EMIS related information is migrated to VaProfile, we should be sure to remove any dead code. It's possible that we can just alter some of the existing code, but anything that is no longer referenced should be removed. Search for "remove" in the [Main App Responsibilities table](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation#Main-App-Responsibilities)

Once the

Also see:
1. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
2. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
3. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

## Acceptance Criteria
- [ ] Remove unused code
- [ ] Tests pass

**Comment by laineymajor** [comment]
this is accounted for in our deletion ticket
