### ISSUE TITLE
Show spinner when talking to address validation API

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4485]
When hitting the UPDATE button from the address form, we first call the validation API and then if the address is good we call the SAVE/UPDATE endpoint. The UPDATE button only shows the spinner when talking to the SAVE/UPDATE endpoint. It should also show a spinner when waiting on the validation API.

This GIF show the UPDATE button unchanged while it waits on the call to the validation API and then switches to the spinner when it's waiting on the SAVE/UPDATE endpoint

![no-spinner.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/4c239550-eb47-4064-9fd9-dd260de8db09)

**Comment by Samara-Strauss** [comment]
Validated on staging. Closing. @bradl3yC feel free to reopen if you were waiting on additional validation outside of me.
