### ISSUE TITLE
[Spike] - VAOS Appointment Load Time Performance Improvements

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#44851]
## Background/Request

Veterans who have a large number of upcoming appointments can experience slow page load times when viewing their appointments through [VAOS](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/).  Techniques, such as caching facility information, have been deployed to shorten load times, but veterans with a large number of appointments (75+) can still experience page load times in excess of 10 seconds.

The goal of this spike is to test load times when appointments are loaded in smaller time ranges, for example 3 or 6 months at a time.   Investigate techniques for implementing loading data as user scrolls or requests appointments further out in the future.

### Goal
Reduce initial page load and subsequent updates to under 3 seconds.

### Requirements to Consider
Use of existing VA web components and style guidelines.

## Tasks
- Answer the following questions:
  - Q  Does loading smaller time ranges of appointments decrease page load times?
  - Q  How many appointments can be loaded while meeting sub 3 second page load?
  - Q  Does this technique appear to make the loading experience better or worse?
  - Q For DS, we make another all to the appointments endpoint. Instead of making another call to this endpoint, can 
        we use the appointments data already stored in redux for this check?

## Time Box
36 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by simiadebowale** [comment]
we were previously looking into pagination but VAOS-service doesn't currently support that. We're already caching our api responses on all levels so there's not much else we can do to improve the load times unless we shorten the time period we're fetching appointments from.
