### ISSUE TITLE
[FE] Cancel an Appointment - API

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44860]
## User Story
As someone who uses the Staging Tool to create appointments in VistA staging, I would like to be able to cancel an appointment so that I can test affected functionality.

## Background
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1658787144382739)

## Tasks
- API work to cancel an appointment
- Adjust API call from the UI to include any needed data

**Comment by acrollet** [comment]
Completed and available to users.
