### ISSUE TITLE
EMIS deprecation: delete rake task

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44865]
**Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/44856**

## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. 

There's a current rake task that audits redis to see how many cached EMIS responses there are for veteran_status information. This should be be deleted because we're not caching any information

Link to code: https://github.com/department-of-veterans-affairs/vets-api/blob/master/rakelib/redis.rake#L84-L100

Also see:
1. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
2. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
3. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

This entails reviewing the high level [external integrations doc found here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations) along with the child docs for each individual service.

## Acceptance Criteria
- [ ] Update rake task

**Comment by LindseySaari** [comment]
@rmtolmach I believe it's this one: https://github.com/department-of-veterans-affairs/vets-api/blob/master/rakelib/redis.rake#L83C1-L102

**Comment by laineymajor** [comment]
Holden is ON IT!

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/13776
