### ISSUE TITLE
EMIS deprecation: update policy

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44868]
➡️ For Platform ⬅️ 
## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. 

The current [EMISPolicy](https://github.com/department-of-veterans-affairs/vets-api/blob/e934b2a4ec7b0025027d5124ca3337d5032fea2e/app/policies/emis_policy.rb) will need to be renamed accordingly and all references updated.

Also see:
1. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
2. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
3. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

This entails reviewing the high level [external integrations doc found here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations) along with the child docs for each individual service.

## Acceptance Criteria
- [x] Rename EMISPolicy
- [x] Update [references](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-api+%22%3Aemis%2C+%3Aaccess%3F%22&type=code)
- [x] Tests passing

**Comment by LindseySaari** [comment]
For the EmisPolicy: It looks like we need to just rename this. There are references not only in the app, but also throughout the VeteranVerification module

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a10b24e9a87fe81312b48b5d07ec93998e155ff4/Screenshot%202023-08-16%20at%208.35.51%20AM.png)

**Comment by rmtolmach** [comment]
I pointed this as a `1` since the level of effort is low and it only touches about 10 files. Since `:emis, :access?` seems to be used by a variety of teams, it makes sense to me to classify this as Platform work and not VFS work.

**Comment by laineymajor** [comment]
This will need to go to the Authenticated Experience team.

**Comment by laineymajor** [comment]
Rebecca started this work. Meeting with Lindsey to troubleshoot

**Comment by rmtolmach** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/13630 merged. Closing.
