### ISSUE TITLE
EMIS deprecation: update EMIS mocking

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44863]
## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. 

There are some classes that mock EMIS for testing purposes. This should be updated to utilize VaProfile instead of EMIS. [See mocking notes](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation#Mocking)

Also see:
1. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
2. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
3. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

This entails reviewing the high level [external integrations doc found here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations) along with the child docs for each individual service.

## Acceptance Criteria
- [ ] Investigate if we can use anything that the auth experience team has already done
- [ ] Update mocking to utilize new approach
- [ ] Update documentation
- [ ] Tests passing
- [ ] Generate Additional Tickets as necessary

**Comment by laineymajor** [comment]
This might belong to a VFS team

**Comment by laineymajor** [comment]
This is for a VFS team

**Comment by rmtolmach** [comment]
This work is to modify [these files](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/veteran_verification/app/models/emis_redis) which fall within #64032 (veteran_verification) which belongs to Lighthouse. Closing since this is overlap.
