### ISSUE TITLE
EMIS deprecation: modify exception handling

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44869]
**Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/44856**

## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. 

The current code catches some EMIS related errors and we will want to be sure to modify these accordingly to be compliant with any code changes.

- Exception handler: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/services/users/exception_handler.rb
- Exception handler test: https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/services/users/exception_handler_spec.rb
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/id_card_attributes_controller.rb#L32-L34
- Look for `EMISRedis::` within the codebase
- Check for others!

Also see:
1. Might need to check VA Profile API docs for possible exceptions. 
2. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
3. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
4. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

## Acceptance Criteria
- [ ] Update exception classes
- [ ] Update tests
- [ ] Update references to old exceptions

**Comment by laineymajor** [comment]
This needs to be pushed back as it has a number of dependencies (associated with VaProfile change).

**Comment by laineymajor** [comment]
Once Ryan is done with veteran_status, this ticket should come next.

**Comment by LindseySaari** [comment]
This will come up next after the veteran_status work, and will be marked for next sprint.

**Comment by LindseySaari** [comment]
The [error classes here](https://github.com/department-of-veterans-affairs/vets-api/blob/v2_va_profile_veteran_status/app/services/users/exception_handler.rb#L35-L40) have been updated and tested along with the other veteran_status changes. Failures were caught in the test suite on the `v2_va_profile_veteran_status` branch and tests are currently green and passing
