### ISSUE TITLE
[BE] Onsite Notifications: Add VA Notify public key to production

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#44875]
## Background
The VA Notify uses a private key to digitally sign requests to the vets-api. Once the VA Notify team sends their public key,  it will need to be added to the AWS parameter store in production.

Public key in dev stored at `/dsva-vagov/vets-api/dev/onsite_notifications/public_key`
Public key in staging stored at `/dsva-vagov/vets-api/staging/onsite_notifications/public_key`

- [x] Add public key in AWS Parameter Store at `/dsva-vagov/vets-api/prod/onsite_notifications/public_key`
- [x] Update production configuration settings in vets-api repo.
- [x] Determine if any changes need to be made in `vsp-infra-application-manifests` repo?

**Comment by tpharrison** [comment]
@ajakabcin The VANotify team will be sending me the public key within the next few days.  This key will need to be configured in our production environment.  Let me know if you have any questions.

cc/ @Samara-Strauss

**Comment by ajakabcin** [comment]
thanks @tpharrison ! adding this to our next sprint.

cc @ericasauv09

**Comment by tpharrison** [comment]
@ajakabcin @ericasauv09 VANotify's public key has been added to our production environment.  I let Kyle MacMillan and Evan Parish from VANotify know.  They will verify on their end.

cc/ @Samara-Strauss
