### ISSUE TITLE
VAOS Staging: Phone Extension saved on VA.gov Profile Conflicts with Confirm Contact Information Screen

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#44873]
## What happened?
Marcy found this issues while testing - When a Veteran saves Phone number with extension on the VA.gov profile page, that is conflicting with "Your Phone Number" on the 
Confirm Contact Information Screen page as the system only accepts 10-digit phone number. 
## Specs:
- Browser: Chrome. Edge 
- Test User: [jacobreid.r.iasimone@id.me](mailto:jacobreid.r.iasimone@id.me)

## Steps to Reproduce
1. Login to VAOS a jacobreid.r.iasimone@id.me
2. User navigates over to the VA.gov profile 
3. Update the contact information and add phone number with extension 
4. Navigate back to VAOS home page and click on "Start scheduling " 
5. Enter a VA request, CC request or DS an appointment
6. Validate on the "Confirm contact information" screen the phone number is auto populated with ext. 

Expected Results: System should accept the phone ext. entered 
Actual Results: System is throwing an error "Please enter a valid 10-digit phone number (with or without dashes)"

Workaround:  Veteran can remove the extension on the Confirm contact information screen. 

Please find the screenshot for reference. 
![image](https://user-images.githubusercontent.com/69315717/181030506-ecaa77b6-e05b-4f84-9758-b9df2a70723d.png)

**Comment by aarathi-poldass** [comment]
@ldelacosta Can you please assign this ticket to the developer for further analysis. Priority TBD

**Comment by ldelacosta** [comment]
[Discussed the ticket with our Product Owner Team - Kay, Mark, Stephen and Patrick on 08/17] Upon review, this requires additional research and considered a low priority on the FE. We don't anticipate this to be completed before the go-live date.
