### ISSUE TITLE
Address suggestion bug

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4487]
To reproduce:
1. first enter 575 20th San Francisco.
2. then enter 37312 coronado

(that gives an error) but it offers the 575 20th suggestions! so we need to clear the redux state!

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/de6edfed-70d3-4a85-81f8-8f93d3a6e876)

**Comment by erikphansen** [comment]
@Justin-Pickett @Samara-Strauss Feel free to validation this on staging. The steps above to reproduce the bug shown above should no longer result in the described bug.

**Comment by Samara-Strauss** [comment]
I am still seeing this. GitHub isn't allowing me to add a screenshot, so I'll Slack you the screenshot.

**Comment by erikphansen** [comment]
@Samara-Strauss sorry `master` broke and the change didn't get pushed out :( I'll let you know when it's really up.

**Comment by Samara-Strauss** [comment]
@erikphansen noted and thanks! I will be happy to verify it when it's ready.

**Comment by erikphansen** [comment]
@Samara-Strauss okay it's actually fixed now

**Comment by Samara-Strauss** [comment]
Validated!
