### ISSUE TITLE
Formation - CSS issue for checkboxes and radio inputs, text should be inset

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#4489]
## What happened?

The label for checkboxes and bullets should indent consistently. This creates a confusing experience, and may look like an error.

For example:

- [ ] This is how text should left-align, rather than <br/>wrap beneath the checkbox input.

However, this is what we're seeing in staging and in the VA design system:
<img width="457" alt="authd-exp-address-validation-ui-question02" src="https://user-images.githubusercontent.com/57469/71636154-608ea180-2bfa-11ea-8574-9155c4c80499.png">
<img width="771" alt="design-va-gov-checkboxes-issue" src="https://user-images.githubusercontent.com/57469/71636155-608ea180-2bfa-11ea-9b97-7a13c08a2c0c.png">

## Steps to Reproduce
For any radio input or checkbox with a long label, verify that text flows under the input.

## Acceptance Criteria
- [ ] When a checkbox has a label that wraps to more than one line, ensure that the text left aligns.
- [ ] When a radio input has a label that wraps to more than one line, ensure that the text left aligns.

**Comment by jenstrickland** [comment]
@Samara-Strauss - For the checkbox label issue, here's the design system bug to address it. cc @Justin-Pickett

**Comment by Samara-Strauss** [comment]
@bradl3yC can you take a look at this?

**Comment by bradl3yC** [comment]
The fix for this already exists in formation.  There needs to be a vets-website code change that adds a wrapping div with the classname form-checkbox and the text should align properly

**Comment by Samara-Strauss** [comment]
Sounds good, @bradl3yC! Let's close this once the vets-website code change is ready.
