### ISSUE TITLE
[SPIKE] Get Answers to Questions

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44900]
## Timeboxed
- 1-2 days

## Tasks
- Look at Adrian's dusty notes
- Ask Patrick who to reach out to
- Reach out with initial questions

## Benefits to Integrating with EAS
- Performance
- No dependency on CHIP

## Questions to Answer
- Do we have a stable API we can integrate with
- What about authentication? Access w/o full auth?
- What are the expectations around use of EAS?
- Can this work for us?
- Is there any documentation for EAS? Where is it? What is it?
- Could we take a stepped approach to integration?
- How could this benefit Performance? Can it scale?
- Are there existing applications that are using the EAS?

**Comment by acrollet** [comment]
Waiting for source access
