### ISSUE TITLE
Staging Review: Design System Team: Memorable Date & Month/Year date web components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#44929]
This is a staging review request for two date web components. 

**Memorable date** 
Design.va.gov: https://design.va.gov/components/form/memorable-date 
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-memorable-date--default 

**Month Year - Date web component variant** 
Design.va.gov: https://design.va.gov/components/form/date-input  
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-date--month-year  

Product Outline: Design System Product Outline https://vfs.atlassian.net/wiki/spaces/DST/pages/2133557283

**Comment by shiragoodman** [comment]
Confirming that this Staging Review is scheduled for 8/2 at 11:30am ET

**Comment by allison0034** [comment]
No design feedback, thank you.

**Comment by ddzz** [comment]
I have one question for this review: will the `va-memorable-date` component display an error if an invalid month or day are entered?

**Comment by caw310** [comment]
Memorable date would be DoB, a date one would easily recall. 
Date input would be for any date such as appointment date.

**Comment by CherylEvans** [comment]
No Content FB at this time.  Thank you for the additional information during the meeting, regarding the headings! :-)

**Comment by bkjohnson** [comment]
To @ddzz 's comment - validation error messages _will_ appear, but at the moment we only run the default validation if the component is `required`.

![Screenshot of the memorable date web component in storybook, with 13 entered for the month value. The component is required, and has also been blurred which means we see an error message saying "Please enter a valid date".](https://images.zenhubusercontent.com/5db75d6f1484010001787ee1/3db2229e-138f-4d09-94a5-89e80c214777)

**Comment by ddzz** [comment]
@bkjohnson thanks for looking into this. My old feedback is to always run that validation.

**Comment by bkjohnson** [comment]
We changed it to only validate on required because a user could tab into a date field, not enter anything, then tab out, then get a validation error message.

**Comment by ddzz** [comment]
> We changed it to only validate on required because a user could tab into a date field, not enter anything, then tab out, then get a validation error message. Here is a [comment with more info](https://github.com/department-of-veterans-affairs/component-library/pull/489#discussion_r930016730).

Can the validation logic be modified to run only when a date is entered and ignore any navigation into/out of the component?

**Comment by chaseakirby** [comment]
[Zoom Recording](https://oddball-io.zoom.us/rec/share/aJjxJ_AfGmEcBJX9OHHoqCSwwIsFDxRgG_r1CCQQNytb9YUoX7QVon_SsCXXLG2l.bDhOshAEzpGymAzJ)
Passcode: mm!V9nyZ

**Comment by bkjohnson** [comment]
From the Acceptance Criteria for [this `<va-date>` enhancement ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/877):

> All validation for the component should only occur onBlur

**Comment by briandeconinck** [comment]
Sorry for the late posting -- finally got the kiddo to take a nap. Did a screen reader run-through and touched base with @SarahKay8, no concerns and no accessibility feedback!

**Comment by shiragoodman** [comment]
@humancompanion-usds flagging you on this concern. Per @ddzz , when the date is optional, it does allow you to enter and invalid number for the month of day. Per @bkjohnson above, this is part of the Acceptance Criteria. I wanted to bring to your attention since this is concerning. Thanks!

**Comment by k80bowman** [comment]
The logic on the date components is a little tricky. Right now, yes, the validation does depend on the field being required. But, I was reading through the comments on this ticket and I agree that we missed this and we should have validation on these fields if a number is entered, whether the component is required or not.

I think the easiest way to fix this would be to update the validation so that if no date is entered, it checks if the component is required before showing an error message. If it is not required and there is no date entered, no error message should be shown. Otherwise, error messages should be shown when date validation fails.

**Comment by k80bowman** [comment]
Yes, @bkjohnson is working on it now.

Just for clarity's sake, here are the user stories we are working with to make sure the validation matches expectations:
- Given a date/memorable date component is required to be filled out, when a user enters a date that fails validation, then an error message should appear
- Given a date/memorable date component is required to be filled out, when a user does not enter a date, then an error message should appear
- Given a date/memorable date component is not required to be filled out, when a user enters a date that fails validation, then an error message should appear
- Given a date/memorable date component is not required to be filled out, when a user does not enter a date, then an error message should not appear (even if they have clicked into the component and then moved on)
