### ISSUE TITLE
Request Slack Channel Info for Platform Team(s)

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#44925]
The intent of this ticket is to continue adding information to Platform team pages that can be viewed by others and shared via excerpt on the Platform Roster. The primary focus of this ticket is on Slack Channels that are owned by Platform teams.

**Teams:**
  - [x] Infrastructure
  - [x] SRE
  - [x] Console Services
  - [x] Release Tools
  - [x] Design System
  - [x] Analytics & Insights
  - [x] QA Standards
  - [x] Platform Security
  - [x] Identity

**Acceptance Criteria:**
  - [x] Each of the teams provide a list of the Slack Channels they own/manage
  - [x] Each provided channel has a description / purpose provided
  - [x] Once completed will update team pages in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44448)

**Comment by ph-One** [comment]
Infrastructure: vsp-operations-internal (primary team channel), platform-infrastructure (general comm with infra)

**Comment by k80bowman** [comment]
Design System Team:
- #platform-design-system
    - public channel for interacting with external teams about the design system
- #vsp-design-system-team
    - private team channel
- #design-system-council
    - private channel for the design system team and members of the design system council

**Comment by troymosher** [comment]
Platform Security:
#platform-security - public channel for security discussion
#platform-security-internal - private channel for platform security team discussion
#platform-security-operations - internal channel for security and infrastructure discussion

**Comment by joeniquette** [comment]
Identity:
#vsp-identity public channel for identity announcements and discussion
#va-identity-alerts identity alerts channel
#vsp-identity-internal Identity channel used for bot reporting items such as ticket creations, also used for comms between identity team and PO
#vsp-identity-team private internal team only used for Identity team discussions and solutioning

**Comment by rmessina1010** [comment]
Release Tools:
#vsp-fe-review-group
#platform-release-tools
#status-vets-website
#status-content-build
#-daily-lighthouse-scan

**Comment by zachclarity** [comment]
SRE Team:

- #platform-sre-internal

**Comment by ericboehs** [comment]
Console Service:
- #platform-console-services (General comms between teams)
- #console-services-private (Internal team comms)
- #cosnole-services-notifications (Internal automated notifications/alerts)

**Comment by pjhill** [comment]
Quality Assurance Standards:

- #platform-qa-standards : A channel for public discussions about cross-team collaboration, QAS-related issues discovered by other teams, and announcements.
- platform-qa-standards-private : A channel for internal team communication around things like, team members missing a meeting, status updates, or discussions including sensitive information.
- #-daily-accessibility-scan : Slack notifications regarding the daily accessibility scan of `content-build` are routed here. `content-build` stakeholders also monitor this channel.
- #qas-notifications : Slack notifications about product directory updates, synthetic monitors, and failing E2E tests are routed here.

**Comment by little-oddball** [comment]
From Michelle on Analytics:

#vfs-analytics:  public channel for interacting with VFS teams
#platform-analytics:  public channel for interacting with platform team
#platfrom-analytics-private:  private team channel to for internal team collaboration
