### ISSUE TITLE
Docs: Account defaults write up

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44927]
@calquisola discovered that folks get editor access by default to grafana, which allows access to the "explore" menu. This makes sense for us too, in the short term. @kylesoskin discovered that if you have the same email, you have access to the same data, i.e. you have the same account whether you're logged into with Login.gov or Github.

**done when**:
- [x] A short doc exists in confluence that includes:
  - [x] our choice to grant editor access by default
  - [x] information that explains how accounts are linked via having the same email (maybe adding the test performed here)

**Comment by calquisola** [comment]
[doc](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2292154479/Grafana) created.

**Comment by kjduensing** [comment]
Commented
