### ISSUE TITLE
Check node version before running install script 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#4493]
- check node version matches requirement when running `yarn install`
- halt installation and inform when mismatched

**Comment by timwright12** [comment]
Closing as complete https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L44

**Comment by timwright12** [comment]
Closing as complete https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L44
