### ISSUE TITLE
Publish workflow run and error messages to BQ

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44945]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by CBonade** [comment]
Included in #44939. Recommend closing

**Comment by pjhill** [comment]
As indicated, the ingest of error logs is being worked under the linked ticket.
