### ISSUE TITLE
Vets JSON Schema Reconciliation 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4494]
## Goal
There needs to be a 1-1 mapping of fields in the paper form to schema properties in the schema file for the 686, for the existing workflow. This ticket is to add the fields that are missing to the schema file as well as to create a generic location schema that can be used for multiple location inputs on the form, including the location(s) of marriage(s).

## Tasks
- Step through the paper form and determine which fields need to be added or updated to the schema file for the 686. 

## Acceptance Criteria
- All fields for the current workflow (add spouse, add child) have been audited and verified to be present in the schema file found in `vets-json-schema` for the 686.

**Comment by micahchiang** [comment]
Documentation for all necessary updates and additions: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-schema-file-reconciliation.md

**Comment by micahchiang** [comment]
PR merged - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/367
