### ISSUE TITLE
Parse workflow logs for error message

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44943]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by CBonade** [comment]
combined this into the gathering ticket, recommending this be closed

**Comment by pjhill** [comment]
Closing because this work is duplicated elsewhere.
