### ISSUE TITLE
SOCKS access for Edmund Dunn

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-team#44958]
### Your Name

Edmund Dunn

### Your Email

edmund.dunn@agile6.com

### Your Role and Team

Engineer on Sitewide CMS

### Product Manager (PM) name and email

Erika Washburn erika@cityfriends.tech

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDhYHyYICXSzkbu6hIj+RKWhkz6M33eaffiedFmBqR7j1GsWlllwdM1A5CA2zDGEBk/pvzCHsZLxotPU4arKz4G4i9oDGqXaQWYz61OPICbex1XYBAFbGRO/2Sb5KBw+06se9LL/BR0YdX6M39L0uVs9zGxi50WsLbDXqmMae71Ng96Rqfzw6gdehTkivv7CvkuGXz5fo5vOOvITeFIiiyr/xjphLXNMgpD1+c09r+7h20vgJz7VhZKQF5vk8J+pu88Cx4lUmuPwAg91b4J3WMVdouQDXyRW1pavD0qJ+s8wwb29w3NN93qgx7vUDRN4EiWpSSp20wxDIiuaQNfsky+i/HkG8c18LJTsid4a52QMHSbOZlxTH/gJwUXQrCrUw+wWfKWwYwOKpDgPQNKgI1/7YXyxy1v3OhuxRLFhOr6kGUDuJtvNa7sBf1IA+MaTVeD4F66ZFlK5ELrCo+/3r1pWe0IxQKXQjcC+xZuu7oNiQ/SUgZzvo8ZTIJQZa/D8CU= edmunddunn@Edmunds-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
