### ISSUE TITLE
Integrate Sidekiq UI into staging Keycloak

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#44957]
Per @ewilson-adhoc's request: 

**done when**
- [x] https://github.com/department-of-veterans-affairs/access-management-integration/issues/106
- [ ] Terraform process worked
OR
- [x] TF didn't work and we integrated manually

**Comment by kjduensing** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Access-Management---Platform-Spike-Team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/44957?planning-poker) with ZenHub @iriteshp

**Comment by iriteshp** [comment]
created client manually in staging.
