### ISSUE TITLE
Use EFS or something similar to save Atlantis plans between Atlantis instance rotations

### ISSUE THREAD

**Issue by nwalke** [department-of-veterans-affairs/va.gov-team#4496]
Atlantis creates plan files for PRs, if an instance rotates (or if there's more than one Atlantis server running) these plan files are lost and creates a poor user experience from the associated PR thread.  We should utilize something like EFS to create a shared directory of Atlantis plan files between running Atlantis servers.

## Goal
- Atlantis server rotations do not result in lost plan files
- Multiple Atlantis servers with shared plan files directory

## Acceptance Criteria
- [ ] Atlantis saves plan files in a shared plan files directory utilizing some service to share that directory between Atlantis servers

**Comment by ricetj** [comment]
Need to revisit when we move this into Nomad
