### ISSUE TITLE
Review Existing Support Form to Include Console Support

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44970]
**User Story**

As a platform team member building new functionality for the Console UI,
I need to alert the Platform Content team about the new work,
So that they can provide recommendations on micro copy, IA and more.

**Acceptance Criteria**

- [x] Review this existing content support form: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=documentation-support&template=documentation-support-request.yml&title=Documentation+support
- [x] Define what questions can be added or edited to fit the need to a content support request for the Console, as well.

**Comment by amygoldman** [comment]
Here's a copy of the form in Confluence with room for notes: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2311684178/Documentation+support+request+form
