### ISSUE TITLE
What will our internal content review checklist be?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44973]
**User Story**

As a Platform Content team member reviewing content on the Console UI,
I need to know what copy-related items to look for,
So that our team is aligned on what guidance we're providing to those building functionality.

**Acceptance Criteria**
- [x] A checklist of items we look for when reviewing the Console UI, as needed (example: micro copy/ UX strategy, etc.)
- [x] Place checklist (or internal team guide) somewhere in our team's Confluence space

**Comment by laucon** [comment]
1. Can the intended reader understand the microcopy immediately when they see it?
2. Is it plain-language?
3. Does it adhere to the style guide heading standards in that the first letter of the first word will be capitalized and the first letter of subsequent words will be lowercase unless they are a proper noun in which case they will be capitalized?
