### ISSUE TITLE
SOCKS access for Suraj Basnet

### ISSUE THREAD

**Issue by bsuraj123** [department-of-veterans-affairs/va.gov-team#44984]
### Your Name

Suraj Basnet

### Your Email

suraj.basnet@accenturefederal.com

### Your Role and Team

Test Engineer

### Product Manager (PM) name and email

cesar.santiago@va.gov

### Product Owner (PO) name and email

cesar.santiago@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9Z8AI8oON8kqPKBresj1LJLLr90fsv8xKgJivi4b2kFmQxWdeqlWHq0Iol4Vh2o8gboDsRfRgbuhQeXQIcM45g8HaUmXQ/LvCRqwbLuGPS7ZnkUh9Uwpd6mfiKP0yYQgUhnowHwK0ozcrtw0E/maQJ+97nIHvOz2+2/9izIzGUIdE2gq0AwSNwSsf7VIImUkF3/Z9Yx08F+7Tn7BMTvQXgmFYvTHSzKPbrZjrM865ICwe7ODhMEpcf60xvPDsAbobYnJiGia/Hhh4x4zrk7tgeL++IhrmSLpThmyt1KVuSDHgIQWjq7BKBuqBeOlZjytFomo4LckClxL7u8XG2aH9spY3VRy2QseoHM1ptMn0NHk+TeJ/jAeUEODKPUSKE0063Ni7isHMhHnS+fBlX1Jgvwi3e1eoPUn0M+wBArA+nGdv+XDTl/9D9qRY+5VSsAiM/Ppr4djjQ/Qyqe4phYq/6VBoPH5NWBab8ock1LxW/5T+6xo6ZBHPWUXsEQF+H8c= suraj.basnet@AFSMWBSZ1RIYIC7

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by bsuraj123** [comment]
@va-vsp-bot i see that my name is already listed in the VFS team roster. Not sure what else is there to be done. Could someone please approve this request at the earliest as I am stuck?

**Comment by bsuraj123** [comment]
My info exists in the VFS team roster.

**Comment by bsuraj123** [comment]
I see that its listed as suraj.basnet@accenturefederal.com @va-vsp-bot

**Comment by s-caso** [comment]
@jbritt1 Can you take a look at this and help Suraj move forward with his access request?

**Comment by jbritt1** [comment]
Pretty sure the reason this failed is because Suraj provided the email of suraj.basnet@va.gov vs what is in the roster as suraj.basnet@accenturefederal.com

**Comment by jbritt1** [comment]
For transparency, I edited the description of this issue to reflect the email address listed in the VFS team roster for the user (the accenture federal one).
