### ISSUE TITLE
526ez | Set up better Sentry logging for 526 failures

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#44991]
# User Story
As a Veteran I want to have confidence that when I submit a 526 on VA.gov that it will be tracked so that the people responsible can easily see what is happening with my submission

## Background
Currently when a 526 submission to EVSS fails there is limited ways to track the failure. This has resulted in an archaic method of tracking where an engineer needs production access to run a SQL query against the production database to see what submissions failed. This is largely because each submission in placed into a Sidekiq job which then submits to EVSS. Sidekiq is used because these submissions often fail for various reasons that require the submission to try again and we can only do that with Sidekiq. 

When one of these Sidekiq submissions fail EVSS sends us back a reason for the failure and currently there is no monitoring in place that alerts us of the failure and reason. What we need to do is go into the code where the submission happens and put Sentry code in to alert us of the failure.

_Disclaimer - you may need Sidekiq working on your local machine to test your code. Alternatively you can pair with someone who has Sidekiq working. If you do need to set up Sidekiq on your machine you can get instructions on setting up [here](https://github.com/department-of-veterans-affairs/vets-api#base-setup)_

[Here](https://github.com/department-of-veterans-affairs/vets-api/blob/e0054c21a0352ec1b07479902bb747b666d21d0e/app/controllers/v0/disability_compensation_forms_controller.rb#L69) is where in the code we create the submission inside the controller, it looks like we do it as a batch. This then calls the `Form526Submission` which can be found [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form526_submission.rb) and it looks like the place we need to tap into the actual Sidekiq job is right [here](https://github.com/department-of-veterans-affairs/vets-api/blob/e0054c21a0352ec1b07479902bb747b666d21d0e/app/models/form526_submission.rb#L122) but that may not be correct and I suggest we dig a little around this.

What we need to do is tap into the Sidekiq submission and detect a total failure, which Sidekiq calls a [death](https://github.com/mperham/sidekiq/wiki/Job-Lifecycle) on a [batch](https://github.com/mperham/sidekiq/wiki/Batches)  and fire a Sentry event with the reason for the failure. [Here](https://github.com/mperham/sidekiq/wiki) is the main documentation for Sidekiq. The platform team can also help with Sidekiq submissions if needed.

Once we determine where we are going to tap into the Sidekiq submission we need to fire a Sentry event, the documentation for doing that can be found [here](https://docs.sentry.io/platforms/ruby/) although it may be helpful to work with the platform team to make sure that we record Sentry events in a manner consistant with how the rest of the code does (also feel free to just search the codebase).

After adding the Sentry events we need to test that they work in production by viewing them in Sentry. Once we are able to verify the events are firing you can work with Michael McDonald to make sure that we are recording the events that correspond with the failures that he sees in the SQL queries he runs against the production database.

## Acceptance criteria
- [ ] Sentry events are now firing when there is a failure of the Sidekiq submission to EVSS for the 526 and they match the same failures that Michael sees in his reports

**Comment by kylesoskin** [comment]
I will begin adding this, additionally I will look to see what logging already exists around 526 errors and see if there is any reports to be made or stories that can be told with what is already in there.

**Comment by sortizsh** [comment]
relates to: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44990
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44989

**Comment by kylesoskin** [comment]
It looks like there is logging when a 526 submission job is exhausted.

**Comment by kylesoskin** [comment]
Sorry accidentally closed. Still looking into this, just adding findings.

**Comment by kylesoskin** [comment]
Starting to put some stuff together

https://github.com/department-of-veterans-affairs/vets-api/pull/10611

**Comment by kylesoskin** [comment]
Waiting on release of vet-api to check new `job_class` addition to logs, then will see what I can do with that in terms of reporting.

**Comment by kylesoskin** [comment]
Since adding the job_class to the job_exhasuted log message, we can now accurately identify exhaustions of overall claim submissions only. There was 7 over the last 24hrs. 
![Screen Shot 2022-09-07 at 8.20.19 AM.png](https://images.zenhubusercontent.com/62067253500f33af56810776/28b9dd69-e79a-4e3b-b4b1-5fa036758a4b)

Next step is confirming this shows up in sentry somewhere, and then setting up alerts (or a work queue) off of this data. 

Final step then is cross-referencing those alerts/work queues with @michelpmcdonald prod console script.

**Comment by kylesoskin** [comment]
It turns out that since these can be retried with multiple birls, the current messages cannot distinguish that. The logging code may need to sit further back in the code OR if there are more birls to try needs included in the current log message.

**Comment by kylesoskin** [comment]
Code has been merged. We can see in datadog when submissions have failed completely (meaning they were unsuccessful and have exhausted all retries, so will not be tried again, they are "dead"/"exhausted")

We could make dashboards or alerts for this/these BUT in tracing down a few of them, usually in these cases the errors are 2 or 3 systems downstream which will still make solving them difficult.

For example, 2 or 3 of the errors I brought up to EVSS, they can only provide the error message that VBMS provides to them. So then someone have to work with VBMS to figure out specific issue, for specific vets/cases.

I feel like there should be a team or some people who can follow up on these issues, or someone we can pass these failures to to investigate, but for most of them, we have done our job and the error lies outside of our area of control.

**Comment by sortizsh** [comment]
@cohnjesse can you confirm that this the solution kyle provided meets your requirements? ty
