### ISSUE TITLE
attempt to change ASG size to 0 after a failed deploy 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#450]
During a deploy where a service is having trouble starting, the ASG creation step in the deployment roles will eventually timeout and Ansible will mark the job as failed. This is ok, but it will result in an ASG stuck in a cycle where it starts a set of instances then terminates them after a timeout and starts over. That can cause issues with instance availability (t2's are problematic to have this done continuously) and create a lot of extra metrics in Prometheus.

A more appropriate alternative would be to have Ansible attempt to set the ASG size to 0 when the deploy fails (but only when the old ASG is not deleted!). That would leave it in a state where we could go set it to 1 if we wanted to see the attempts to start, but not have it constantly cycling instances in and out.

**Comment by wyattwalter** [comment]
This was an old carry-over. I don't think this is worth doing.
