### ISSUE TITLE
Refine Initial Mockup for "Add Dependent" Workflow to Show Stakeholders

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4500]
## Goal
Ensure that we are going down the right path and what we are producing is what is expected by the stakeholders.

## Tasks
- Clean up and reorganize the starting path for Add Dependents
- Include paper form field mappings on right side
- Share with stakeholders with some written guidance about viewing the mockup and its mapping to the paper form

## Acceptance Criteria
- [ ] First version has been prepared to be sent to Paul for sharing amongst the other stakeholders

**Comment by sporeboy** [comment]
21-686c paper form mapped to initial static mockups. Ready for team review and presentation to VBA stakeholders.

**Comment by jason-gcio** [comment]
XD file is here: https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/
Questions: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/discovery/stakeholders/686-workflow-questions.md
