### ISSUE TITLE
Feature Request: Documentation for using Drupal EHR (i.e. Cerner) data in FE apps and widgets

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#45017]
### Describe the problem

The CMS team has added a data point to Drupal representing whether VAMC systems are using Cerner or VistA as their electronic health record (EHR) system. Previously, this data point was hard-coded in `vets-website`, and various Redux selectors were built that depend on this hard-coded data point.  Product teams across VA.gov are using these selectors. New selectors have been created, and product teams' code will need to be updated to connect to this new Drupal data and to use these new selectors.

We need to provide documentation surrounding this process.  [The documentation is already written](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/cms-source-of-truth/opt-in-drupal-source-of-truth.md), but it seems it might be useful to make it available in a more visible location (i.e. Platform docs).

### Who will benefit

Product teams developing apps and/or widgets that require knowledge of the EHR system being used by certain VAMC systems/facilities.

### Describe your idea

This request is simply to add the already written documentation to the Platform docs. The work we've done will have impact that stretches across teams, and it seems Platform documentation might be the best place to communicate this work.

**Important note:**

This is just one example of the larger topic of accessing CMS (Drupal) data from the browser (i.e. React apps).  This process is something that the CMS team has been working to standardize, so it might be useful to consider this EHR documentation as the first step of creating more robust documentation around this larger process.  Such documentation would likely include:
- A list of static CMS data files that are available to be fetched by the browser and used in React apps/widgets.
- How to connect these data files to the Redux store.
- How to make a request with the CMS team to make additional data available for consumption by the browser.

Not all of these steps are currently standardized, but it does seem that this is the direction we might want to head. Then, this process might be titled something along the lines of "Accessing CMS data from the browser". It would fit naturally in one of these places:
- As its own section under [Frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-developer-documentation)
- As a subsection under [Frontend architecture](https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-architecture)
- As additional information around [Adding applications and features](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-applications-and-features)

### Provide evidence

We have existing documentation as noted above. The evidence is simply that this documentation is not in a highly visible location surrounding other documentation that impacts teams across VA.gov.

### Platform Mission

- [X] Keeps these products and services available, stable, and secure.
- [X] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by vbellissimo** [comment]
- Reach out to Carol Wong and Katy Bowman to 1) review documentation provided and 2) the recommended IA places to live under
- Platform content team will add to the Platform website and add necessary styling best practices
- Deploy on the next deployment day

**Comment by taylojill** [comment]
Hello @caw310 and @k80bowman. I will review the documentation and provide a recommendation as to where it should live on the Platform web site.

**Comment by taylojill** [comment]
Hello @ryguyk @caw310 @k80bowman I converted your document to Confluence for deployment to the Platform web site, it can be viewed here: https://vfs.atlassian.net/l/cp/w12qmjcL
Where would you like to put it on the web site? Ryan suggested three possibilities, any thoughts? 
Once it's moved, it will be deployed live on the site. Please advise on location. Thanks!

**Comment by k80bowman** [comment]
This document is not owned by the Design System Team, so @caw310 and I should probably be taken off of this.

**Comment by taylojill** [comment]
@k80bowman and @caw310 removed. Thank you!

**Comment by jilladams** [comment]
Dave's original suggestion was to put this doc under Frontend Architecture, so it's parallel with other related-ish info like the TeamSite overview. @ryguyk do you have strong feelings as an FE eng whether that's a sensible place to look for it, or if you'd rather see it in 1 of the 2 other locations you listed?

**Comment by vbellissimo** [comment]
@taylojill Please add this new page under the "Frontend developer documentation".

**Comment by taylojill** [comment]
8/23/22 - Document added under "Frontend developer documentation" section.

**Comment by jilladams** [comment]
@taylojill could you provide a link to the final page? Checked that section in Confluence and don't see it, and https://vfs.atlassian.net/l/cp/w12qmjcL is access-blocked for me.

**Comment by taylojill** [comment]
@jilladams Here's the link to the final page: 
https://vfs.atlassian.net/l/cp/Jxvom1Le

**Comment by jilladams** [comment]
Hm. I still don't have access. That will eventually publish out and get a path under https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-architecture?

**Comment by taylojill** [comment]
Yes, it will be under "Frontend developer documentation" and goes live today after 3PM EST.

**Comment by jilladams** [comment]
https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for
