### ISSUE TITLE
AWS access for Rachal Cassity

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#45027]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Rachal Cassity

### Your Email

rachal.cassity@oddball.io

### Team, Role, and Company of the target individual

Console Services, Backend Engineer, Oddball

### Product Manager (PM) name and email

Nathan Peterson, Nate.Peterson@adhoc.team

### Product Owner (PO) name and email

Thomas Delrue, thomas.delrue@va.gov

### Desired AWS Access

I need access to Key Management Service to add new environmental variables to the vets-api.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
User found in Platform Team Roster

For AWS Access
User: Rachal Cassity
COR: Vilay Senthep
VOR: Oddball - Amber Malcolm
Approval required: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
Admin level: no

**Comment by rmtolmach** [comment]
@kylesoskin Rachal already has AWS access: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf#L1502

I'm not sure if getting access to Key Management Service requires an extra approval or not.

**Comment by RachalCassity** [comment]
You are correct. Closing this issue.
