### ISSUE TITLE
Go/No Go for Playbook

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#45021]
- [x] Prep any necessary docs
- [x] Schedule session
- [x] Conduct go/no-go w/ PO
- [x] Conduct go/no-go
- [x] Capture any feedback

Prep doc: https://vfs.atlassian.net/wiki/spaces/SDT/pages/2294055178/GNG+for+Playbook

## Follow-up Steps
- [x] Adjust language on documenting the change on the platform website.

- Mike Chelen thought it was a little confusing, that maybe we were suggesting that the change be documented (when we mean user guides and such).

- [x] Adjust language referring to "teams" in Attention section of formatted Slack communicaton

- Mike Chelen thought it should refer to roles instead.
- [x] Move Attn: section to top of Slack communication instead of the Title

- Naomi thought this might garner the appropriate attention better

- [x] Thomas wants additional [evaluation planning](https://vfs.atlassian.net/wiki/spaces/AP/pages/2226356277/Q3+2022+Crew+Teams+-+OKR+Tracking
) in place before launch

- didn't feel that monitoring the Playbook's confluence page use & monitoring of new channel was sufficient
- he thought we wouldn't know what we didn't know if only monitoring the new channel (we are also going to monitor the vsf-all-teams channel)

**Comment by steel36** [comment]
This was cancelled due to Crew members being OoO.  Will likely be pushed to next week.

**Comment by raywangoctova** [comment]
Approved for Go.

**Comment by steel36** [comment]
Feedback from Go/No Go:

https://dsva.slack.com/archives/C02QN5J3FK6/p1660067208638709?thread_ts=1660067039.187369&cid=C02QN5J3FK6
