### ISSUE TITLE
[CDP] Utilize the term "overpayment"

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#45039]
## Issue Description
[Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-findings.md)

Consider using the term "overpayment" when referring to debt caused by an overpayment. Several participants mentioned overpayment when defining "debt". One participant stated he liked when it was mentioned, "so it doesn't make you feel fraudulent and makes the dispute process easier."

---
## Tasks
- [ ] Discuss where utilizing the term "overpayment" makes sense

## Acceptance Criteria
- [ ] _Issue discussed with stakeholders and content team to determine next steps

**Comment by denisecoveyduc** [comment]
@mgleo do the copy changes covered in 47339 cover this or are there other areas where we need to weave in the overpayment term?

**Comment by mgleo** [comment]
@denisecoveyduc IA/Content team should also look at the Combined Debt Portal as well.

**Comment by denisecoveyduc** [comment]
Agreed! I have spoken with @DanielleThierryUSDSVA and as we take the FSR enhancement release thru the collab cycle the Content and IA teams will review the dortal and ensure consistency with the term overpayment and others. She has just released a [content brief for VA payments, debts and copay bills ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/payments-debts-copay-bills.md)which will be helpful to maintain consistency. 

I am going to close this ticket given we are planning to review as part of the collab cycle touchpoint.
