### ISSUE TITLE
FE | Profile | New Forms Library | Preferred Name

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45048]
## Tasks
- [ ] Add tasks here that must be completed

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@adamwhitlock1 - can you add tasks and acceptance criteria (I'll then use going forward for act'l forms lib work).

**Comment by SKasimow** [comment]
@adamwhitlock1 - should we icebox this or close out? I'm inclined to close so it doesn't clutter the Icebox column and re-open whenever we get back to it....

**Comment by adamwhitlock1** [comment]
I'm closing it and will open a new ticket when we know more about the forms system's future
