### ISSUE TITLE
[BE] [SPIKE] Create credentials for Travel Reimbursement API and explore the endpoints available

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#45044]
## User Story
- Based on Jordan's email, create credentials for vets-api and read documentation on how to use it to get a token
- Explore the BTSSS api endpoints, include the data needed to submit claims

## Acceptance Criteria
- [ ] Document findings
- [ ] create follow up tickets for subsequent work

**Comment by randomsync** [comment]
Created a request using their portal

**Comment by loripusey** [comment]
I'm closing this one as it seems like we met the AC
