### ISSUE TITLE
Include Platform Content Support In #vfs-platform-support Process

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#45047]
## Problem Statement 

Currently, the Platform Content team is not part of the broader Platform support process provided to VFS team members through the #vfs-platform-support Slack channel.

In addition, the Platform Content team answers to support from both VFS team members and Platform teams via two different Slack channels:

1. #Platform-Content
2. #Platform-Confluence

This causes a couple of challenges:

1. We're not part of the broader Platform support process can be confusing to customers, especially to VFS team members, who are used to seeking assistance from #vfs-platform-support.

2. No automated/easy way to quantify the types of support requests we respond to via Slack. We do it manually right now.

**How might transition our current Slack support to streamline it with the broader Platform support process that all Platform teams leverage and VFS teams are accustomed to?**

## Hypothesis or Bet

VFS and Platform teams will benefit from the ability to submit Platform website technical issues to the current Slackbot support process because **it is a familiar process to them.**

**VFS and Platform teams will have 1 less support outlet to have to think through** when determining where to request support from the Platform Content team.

The Platform Content team will benefit from **having 1 less Slack channel to monitor** and maintain.

The Platform Content team will be able to more easily **quantify support requests** we respond to by using the Slack bot data.

## User Stories
As a VFS team member,
I want to report an issue with the Platform Website through the same system all Platform teams use via Slack,
So that I have a steam-lined way of seeking assistance from the Platform teams.

As a Platform team member,
I want to report an issue with the Platform Website through the same system all Platform teams use via Slack,
So that I have a steam-lined way of seeking assistance from other Platform teams.

As a Platform Content team,
We want to retire the #platform-confluence Slack channel and transition questions about the Platform website to the broader Platform support bot,
So that we have 1 less Slack channel to answer, including questions about Confluence that are not related to the Platform Website (access, user accounts, etc.) 

As a Platform Content team,
We want to retire the #platform-confluence Slack channel and transition questions about the Platform website to the broader Platform support bot,
So we have a way to quantify the support request we handle via Slack.

## We will know we're done when... ("Definition of Done")

- [x] VFS and Platform teams will be able to seek support from the Platform Content team via #vfs-platform-support Slack intake form.

- [x] The Platform Content team will be able to start quantifying Slack support intake through this new process.

## Known Blockers/Dependencies 

Coordination with the SRE team to update the current Slack support form found in `#vfs-platform-support`

## Projected Launch Date

End of Quarter 4/On or before December 2022

## Artifacts

- Project notes: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2401239503/2022+Q4+Include+Platform+Content+into+Slack+Support+Bot
- Team workflow: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1665668841851/5f78b14c0b0fd716158556bded3f09d0f85b99f1?sender=u9d01ee38af217e4877e75660
- Communications plan: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2413264910/Communication+Plan+for+Slack+Support+Change

**Comment by annekerr49** [comment]
@vbelllissimo - Vicky we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues. Please let me know if you have any questions.

**Comment by vbellissimo** [comment]
Officially completed all acceptance criteria for this initiative.
