### ISSUE TITLE
AWS access for Afia Caruso

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#45068]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Afia Caruso

### Your Email

afia.caruso@oddball.io

### Team, Role, and Company of the target individual

Identity, Front End Engineer, Oddball 

### Product Manager (PM) name and email

Nick Soutouras nick.soutouras@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghi@va.gov

### Desired AWS Access

Access to debugging information via AWS logs and ability to run adhoc database queries via Rails console in staging.

### Access Expiration

ongoing

### Additional Notes

COR Ray Wang

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
@acaruso-oddball is in the VFS Team Roster.

**Comment by kylesoskin** [comment]
User: Afia Caruso
COR: Ray Wang
VOR: Oddball - Amber Malcolm
Approval required: https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers
Admin level: no

**Comment by td-usds** [comment]
Reached out to VOR

@acaruso-oddball can you be a bit more specific about "ability to run adhoc database queries via Rails console, in staging (and/or production on as needed basis)." Staging is less of an issue, but prod is a big deal.
Additionally, we do not hand out ongoing prod access for all the obvious reasons. Can we split out the prod access from this ticket and deal with that when that need actually arises?

**Comment by joeniquette** [comment]
Hi @td-usds Afia is on the Identity team as a frontend engineer, she works alongside our current frontend engineer @AGarcia-Clarity. She should have the same permissions as he does in order to support day to day Identity responsibilities. As for the database query part, this is all run through rails console so as long as she has SSM access and the underlying permissions to access the api instances then we should be good to go. I haven't confirmed but I thought there was already an Identity team engineer role within AWS, she should just be added to this group.

In terms of the production access, I'm comfortable with the suggested approach of having a separate request for prod access when its needed. Thanks for your assistance on this.

**Comment by acaruso-oddball** [comment]
Hi @td-usds I've gone ahead and updated my request to reflect the terms mentioned above. I appreciate your diligence in this matter, and please feel free to let me know if there are additional edits needed. Thanks!

**Comment by joeniquette** [comment]
@kylesoskin @td-usds Any updates for us here? Do you need anything else to approve Afia's access?

**Comment by td-usds** [comment]
Requested access approved

**Comment by jbritt1** [comment]
First-time login credentials passed to user via DSVA Slack workspace DM.
