### ISSUE TITLE
Create a Working Prototype for "Add Dependent"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4506]
## Goal
Internally, we need a working prototype that will allow us to reference and agree on how the 686 form would work.

## Tasks
- [ ] Likely after stakeholders have weighed in on the flat mockup with the field mapping, add conditions to mockup for different scenarios within the initial workflow

## Acceptance Criteria
- [x] A working prototype is shared in GitHub

**Comment by sporeboy** [comment]
Prototype work underway. First two workflows blocked-out here: https://xd.adobe.com/view/0f7759a1-b990-4d71-50c9-138d9e593fd0-7946/
