### ISSUE TITLE
Pre-Need | Update eligibility submission URL 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#45064]
## What happened?
continuation of this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/35776

## Desired behavior
The preneeds team is moving their service to the cloud and the URL that vets-api uses is going to change, they would like us to test their new URLs to make sure we can access them from our staging env.

This is good news for us, the current preneeds service we call from vets-api staging is not currently working and we have been unable to resolve the issue, I suspect it a configuration\permissions issue on the preneeds side of things, but hopefully we can start using their new staging service from our staging.  Currently, in staging, all attempts to submit a new preneeds request error out

Only the preneeds URL(s) are changing, the service itself is the same, they just moved it to the nice part of town, so no code changes are anticipated other than some url settings

## Acceptance Criteria
- [ ] Test the new URLs preneeds have provided(via Va emails) and make sure we can call them from staging env.
- [ ] Once we confirm the URL are accessible, make the new URLs live in vets-api staging(TBD, not sure they are ready, will ask them)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by saderagsdale** [comment]
@jerekshoe @michelpmcdonald is this still being worked?

**Comment by jacobworrell** [comment]
Let's set up a meeting with EOAS to discuss outstanding items @sortizsh

**Comment by sortizsh** [comment]
scheduled for 9/6
