### ISSUE TITLE
BE, FE - 10-10EZ: Update Place of Birth State Dropdown Menu

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#45076]
For the 10-10EZ, the *Place of Birth* dropdown menu has been expanded to include a number of states that are outside the United States.  This is causing issues with the Enrollment System since it's only designed to handle the 50 states, DC, and Other.

We need to update this field so that it only has the options listed above, and that when *Other* is selected, it sends across a backend code of `FG`.

**Comment by longmd** [comment]
@lihanli , I have the front end work done for this. When you're all set with #45079 , I can update that schema in my branch and be ready to go. There isn't any further back end work , right, because we're already sending "FG" if the user selects "Other"?

**Comment by lihanli** [comment]
@longmd there's no backend work required. i made a pr to update the schema https://github.com/department-of-veterans-affairs/vets-json-schema/pull/711

**Comment by longmd** [comment]
@lihanli , we can probably go ahead and roll with that Schema update PR before the end of the sprint here.

**Comment by hdjustice** [comment]
Validated - This has been corrected and released to production.  Ticket can be closed
