### ISSUE TITLE
[SCREENREADER]: VA is read phonetically instead of as the abbreviation

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#4507]
## Description

In the main navigation, the nav items, "VA Benefits and Health Care," "About VA," and "Find a VA Location," in JAWS IE11, it reads phonetically, VAH - instead of V A. For screenreader users, this is confusing. For those with cognitive issues as well, it might be very difficult to overcome.

## Point of Contact

Jennifer, Trevor

## Acceptance Criteria

As a screenreader user, I want to review the content of the site banner and navigation in order to know what website I am on and what my options are.

## Environment

* Screenreading device: JAWS + IE11
* Server destination: https://staging.va.gov/pittsburgh-health-care

## Steps to Recreate

1. Enter `https://staging.va.gov/pittsburgh-health-care` in browser
2. Start screenreading device listed in Environment
3. Navigate to the banner area
4. Verify that each instance of "VA" is read phonetically instead of spelled out.

## Possible Fixes (optional)

Propose fix of "VA" to be wrapped in an <abbr> tag with "Veterans Affairs".

`<abbr title="Veterans Affairs">VA</abbr>`

Alternatively, an aria-label="V A" might work.

**Comment by FranECross** [comment]
@laflannery I'm not quite clear on whether this should/can be worked on by the PW team. Are you able to shed some light? Thanks!

**Comment by laflannery** [comment]
@FranECross Short answer - no, it's not ready for you. Longer answer - Let's talk about it at our next Thursday sync, I'll put it on our agenda so we don't forget. There's some stuff here
