### ISSUE TITLE
Move away from a shared Keycloak admin account

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#45071]
In order to follow best practices as well as enable a smoother transition, we should move away from using the shared Keycloak admin account. Having individual admin users with the appropriate roles enables teams to autonomously add admin users (or change them) without having to pass around credentials. It also enables AMT to add a user from the receiving team (if known) to the admins group to facilitate the transition.

 The process will go something like:
1. An admin creates a new user
2. The existing admin adds the user to the group kc-admins
3. The user logs in and changes his/her password
4. The user can now login as admin

Note: This requires a group kc-admins to be setup, which maps all the roles from the client realm-management

**done when**:
- [x] `kc-admins` group is created in Keycloak dev, staging, and prod
- [x] The entire AMT team holds individual admin accounts and can log in with their own admin credentals
  - [ ] Carl
  - [x] Ritesh
  - [ ] Kevin
  - [ ] Matt

**Comment by iriteshp** [comment]
Looking at the Login.gov option, timebox it for today. if not will move with manual account creation.

**Comment by iriteshp** [comment]
moving with manual named admin account instead of Login.gov. It can be automated with research on [this](https://app.zenhub.com/workspaces/access-management---platform-spike-team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/44600) issue.

**Comment by iriteshp** [comment]
login info sent. will close this ticket when all confirm access.
