### ISSUE TITLE
10-10EZ: Re-Enable Short Form in Production

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#45077]
The Short Form encountered an error that caused several applications to be unrecoverable.  These applications were submitted with foreign states listed in the *Place of Birth* field, and the Enrollment System was not capable of parsing this information, meaning the applications would have to be processed manually.

However, since the Short Form skips the *Military Information* section of the application, the PDF cannot be rendered since it has those fields marked as required.

In order to re-enable the Short Form, the following steps must be completed:
- [x] [Complete *Place of Birth* dropdown correction] (#45076)
- [x] Enrollment System to update their backend to no longer require the *Military Information* fields
- [x] #45161
- [x] #45164
- [x] #45167
- [ ] Conduct UAT btw 5-25 % with real Veterans, ideally ones who might trigger failures. #40087 
- [x] #45172
- [x] #45173
- [x] #45174
- [x] #45175

**Comment by lalexanderson-dsva** [comment]
@markfallows - please add a few additional steps in here:

Prior to "relaunch to 5%" :
- [ ] Write release plan, including multiple checkpoints with Josh F. & the E&E system to validate at each phase that there are no errors coming through. 
- [ ] Release should go slower, not 5% directly to 100% but with markers at 25% and 50% at a minimum. 
- [ ] Conduct UAT btw 5-25 % with real Veterans, ideally ones who might trigger failures.

**Comment by markfallows** [comment]
@lalexanderson-dsva Done.  You can find the [re-release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Short%20Form/Re-release%20Plan.md) here.

This includes a checkpoint before rollout for us to work directly with the Enrollment System Team to ensure that the same issue doesn't occur as well as a timeframe for us to complete UAT with actual Veterans.

The dates are all placeholders, as they'll be based on when the Enrollment System can be updated.  Five weeks was mentioned previously, so that's what I worked with to ensure that we have some kind of date in there.
