### ISSUE TITLE
SOCKS access for [Aaron Young]

### ISSUE THREAD

**Issue by aaronyoung-tw** [department-of-veterans-affairs/va.gov-team#45086]
### Your Name

Aaron Young

### Your Email

aaron.young@thoughtworks.com

### Your Role and Team

Developer for Virtual Agent team

### Product Manager (PM) name and email

Alina Murphy amurphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais luciana.morais@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdMoD5Hqarp1MZcBYQypyufmO1Yeg52MdD/bRSQZR/yA01mqzcHHFYFvBVjeNxSy0diKn5A8E2nkC2pmAvTIKI+q2ONdsxBpg8H3z5TxTXinwOGgfnEDMYUi1eRrttYAxFHjOEWXxCeQvFnbE4toSWAa+0W1vgvW0wYPxuPMn03Q02ppQFolMIyDB7yDcJU7nnLr5n1ZOqRRdlE+kBUzDTrnZx/nqcnA02ckoBhZpKxjUr2FTmdqgbjjAQtwjOFyw8+qQEW8q+G1u+7B6ppYha6tITPpybWz6PYKuK1rHmzWx+kNae7hlOVq7o1xxlfMsVt1+Q3bCueRz22J3VOptmmOCV3h3JZdDl6U44TZ8Klj0Kq3ojYBcF/gF30NnpHGHCeKVSXbwOK9HJDLse+KEncBQEOZEHeef3noAzrTEfWNS/WBd+JT3rzmbktXKXtfm9ReFpfqjjTNyc1jV4fLwXFQX6jenPn9cdBT19G2qXYIx319MTYNIwAU+8gcUPyWc= aaronyoung@AaronsTW2019MBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
