### ISSUE TITLE
How to isolate your applications and enable autonomous deployments

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#45096]
### Description

The release tools team has been slowly isolating applications and adding them to the "allow-list" to enable autonomous deploys for those applications. Being on the allow-list means that changes to those applications are deployed immediately after merging instead of waiting for the daily deploy, resulting in faster, more frequent deploys (an OCTODE priority). Getting an application on the allow-list is a very straightforward process and we've hand selected a few of your applications that are very close to being eligible. 

These applications are:
- `education-letters`
- `my-education-benefits`
- `toe`

One of the requirements for being on the allow-list is no importing from other applications. This means that the application cannot import from another application AND another application cannot import from the application. Fortunately, these selected applications have very few imports.

`education-letters` is imported by:
- `toe` in `src/applications/toe-benefits/containers/App.jsx`

`education-letters` is importing:
- `my-education-benefits` in `src/applications/education-letters/containers/App.jsx`

`my-education-benefits` is imported by:
- `education-letters` in `src/applications/education-letters/containers/App.jsx`
- `toe` in `src/applications/toe-benefits/containers/App.jsx`

`toe` is importing:
- `my-education-benefits` in `src/applications/toe-benefits/containers/App.jsx`
- `education-letters` in `src/applications/toe-benefits/containers/App.jsx`
- `letters` in `src/applications/toe-benefits/containers/App.jsx`

Even more fortunately, most of these files with imports are redundant and addressing one situation will address another. For these applications, there are only **two** unique files that need to be addressed. For more information on how to address common cross application imports, please read the [developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/addressing-common-cross-app-imports) on the subject.

Beyond removing imports from/to other applications, the applications must [pass the header test](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list#Howtoaddyourapplicationtotheallow-list-Passtheheadertest) and have an application specific [slack group created](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list#Howtoaddyourapplicationtotheallow-list-AddaSlackgroupforyourapp) to receive notifications of build and/or deploy statuses. 

After all those tasks are completed, the applications are ready to be added to the allow-list! The final step is to create a pull request adding the applications to the allow-list that our team will review.

If your team needs any help with any of the steps for the isolation process or general questions about isolated applications, please don't hesitate to reach out in the [#platform-release-tools](https://dsva.slack.com/archives/CQH357ZTP) slack channel or drop a support request in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) slack channel. For all documentation related to isolated applications, see [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds).

****### Definition of done**
**- [ ] All applications listed have had their cross application imports addressed and removed**
**- [ ] All applications have passed the header test**
**- [ ] A slack group for each application is created to notify of build and/or deploy statuses**
**- [ ] A pull request is created adding the applications to the allow-list**

**Comment by cesaresantiago** [comment]
Is the effect of this change to have immediate deploys to production? @ndsprinkle

**Comment by rmessina1010** [comment]
Completed.
