### ISSUE TITLE
Design Intent - Accessibility Feedback - [Benefits Team 1, Supplemental Claims Form 20-0995]

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#45097]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- You're off to a really good start, and definitely continue working with @joshkimux! And feel free to invite him along to any touchpoints moving forward too! 😄 
- As discussed in the meeting, wherever possible try to use established design system patterns and contribute improvements back to them. That helps reduce the cognitive load of having to learn different interaction patterns for similar functions.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- I know a lot of what you shared is still a work-in-progress, but one minor thing to flag. As you continue your design work, avoid URLs in link text (eg. at the end of the ["I certify that" statement for New and Relevant Evidence](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/KvPGPJy)). Parsing through a URL is a cognitive load issue, and also presents issues for understandability when announced by screen readers and pronounceability for voice command software users. With the exception of something short and recognizable like "VA.gov," always default to plain language link text.

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by thehastingsp** [comment]
Hi @briandeconinck I think it might have gotten lost in translation that I found this pattern problematic too, and proposed a solution to present the linked content inline. I can present it here as a before and after and also link to this [[content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44411)]

**CURRENT FORM PRESENTATION**
I CERTIFY THAT I have received or reviewed the notice of evidence necessary to substantiate a claim for Veteran’s Disability Compensation benefits as provided at [www.va.gov/disability/how-to-file/claim/evidence-needed](http://www.va.gov/disability/how-to-file/claim/evidence-needed).

- [ ]  YES
 - [ ] NO

If “NO” is selected, VA will send the 5103 notice to you via mail.

(this expects the user to link out and review the content in the link, then navigate back and check yes to proceed)

**PROPOSED:**
Please review and acknowledge the evidence statement below to substantiate a claim for benefits.

NOTICE OF ACKNOWLEDGEMENT
You'll need to submit evidence of:

1. A current physical or mental disability from a medical professional or layperson (someone who’s not a trained professional), and
2. A link between your current disability and the event, injury, or disease that happened during your service.

Usually we need medical records or medical opinions from health care providers to support this link.
A Supplemental Claim is a claim providing new evidence to support a disability claim that was denied.
You’ll need to submit new evidence we’ve haven’t reviewed before that’s related to the issue you’re claiming.
- [ ] I CERTIFY THAT I have received or reviewed the notice of evidence necessary to substantiate a claim for Veteran’s Disability Compensation benefits.

(This is expected to display inline.)

See comps in [Sketch file here](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89)) that is asking for their review. Please let me know if this addresses the issue you are raising.

**Comment by thehastingsp** [comment]
@briandeconinck wanted to verify that we have worked with content to arrive at final language and will be testing presenting this content inline and not sending anyone away to review a different URL.

**Comment by thehastingsp** [comment]
this issue has been considered and resolved. thank you!
