### ISSUE TITLE
[Spike] VAOS single clinic dead ends

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#45130]
### Request
Product and Design team are requesting help from VAOS FE Engineering team to understand how the application handles single clinic dead ends when the user is in the appointment workflow.

### Goal
The team would like to [update the user flows in VAOS](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=253%3A41058). 

### Screenshots

1. Single clinic dead end when selecting `No, I need a different clinic` 
User ID: jacqueline.morgan@id.me
Type of care: Mental health 
VA location:  Cheyenne VA Medical Center
<img width="545" alt="Screen Shot 2022-08-01 at 2 24 29 PM" src="https://user-images.githubusercontent.com/90797205/182218491-0f4e0fac-cd45-4cc7-8f86-6b8941202abb.png">

2. Single clinic dead end (unsure how this triggers) 
<img width="1017" alt="Screen Shot 2022-08-01 at 2 12 42 PM" src="https://user-images.githubusercontent.com/90797205/182392527-703ef650-350a-48ab-946b-940205cb26ed.png">

---

## Tasks
- Answer the following questions:
  - Q1: What are all the alerts on the `Choose your VA location `page? Please provide mobile screenshots. 
  - Q2: What triggers these alerts to show? 

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by vbahinwillit** [comment]
The type of error message displayed is dependent on how the clinic is configured. Clinic configuration is done thru VATS. A clinic can be configured to support both direct scheduling and appointment requests. This implies that there are error messages for both workflows. This spike address the request workflow only (selecting 'no I need another clinic drops the user into the request workflow).

Q1: What are all the alerts on the Choose your VA location page?

A1: The following alerts are triggered when the user selects 'No, I need a different clinic' on the the 'Choose a VA clinic' page and appointment requests are not support at the given clinic.


.../vaos/utils/constants.js:398
```
export const ELIGIBILITY_REASONS = {
  notEnabled: 'notEnabled',
  notSupported: 'notSupported', -
  noRecentVisit: 'noRecentVisit', -
  overRequestLimit: 'overRequestLimit', -
  noClinics: 'noClinics',
  noMatchingClinics: 'noMatchingClinics',
  error: 'error', -
};
```
The following errors occur during the direct scheduling workflow:
* noClinics
* noMatchingClinics
* notEnabled
Q2: What triggers these alerts to show?
A1: These alerts are triggered when the user selects 'No, I need a different clinic' on the the 'Choose a VA clinic' page and appointment requests are not support at the given clinic. The RequestEligibilityMessage component checks the eligibility reason error code to determine which alert to display. 

../new-appointment/components/ClinicChoicePage/index.jsx:68:
```
const usingUnsupportedRequestFlow =
    data.clinicId === 'NONE' && !eligibility?.request;
```

**Comment by ldelacosta** [comment]
@vbahinwillit - Could you please review the questions from Ciera? Thanks in advance.

**Comment by vbahinwillit** [comment]
Q1 - Is there a difference between "notEnabled: 'notEnabled'" and "notSupported: 'notSupported'"?
A1 - Yes. 'notEnabled' is for direct scheduling only. This indicates that direct scheduling was disabled via feature flag.
```
[ELIGIBILITY_REASONS.notEnabled]:
      'The FE has disabled direct scheduling via feature toggle',
```
'notSupported' is for both workflows and indicates that direct or request scheduling has been disabled via VATs.

Q2 - Do these match up with one another correctly?:

notSupported: 'notSupported', is the same as this? Yes
noRecentVisit: 'noRecentVisit', is the same as this? Yes
overRequestLimit: 'overRequestLimit', is the same as this? Yes

Q3 - What else would trigger an error like this ?
A3 - An error occurred when trying to retrieve eligibility via api call. This type of error is completely out of our control. Ex. network down.

Q4 - Can we get a mobile screen shot for this screen?
A4 - Sent the screenshot via slack. I can't edit the Figma doc.

**Comment by Cieramaddox** [comment]
@vbahinwillit Do we know if notEnabled and notSupported will yield the same error message?

**Comment by vbahinwillit** [comment]
Looks like notEnabled is only used for browser console logging. notSupported is the only one used in the app and it displays the following message:

```
        <InfoAlert
          status="warning"
          headline="This facility does not allow online requests for this type of care"
        >
          This facility does not allow scheduling requests for this type of care
          to be made online. Not all facilities support online scheduling for
          all types of care.
        </InfoAlert>
```

**Comment by Cieramaddox** [comment]
@vbahinwillit Okay, so veterans will not see the notEnabled error?

**Comment by vbahinwillit** [comment]
correct.

**Comment by outerpress** [comment]
All screens and logic captured in user flows [here](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=255%3A41180). Thanks @vbahinwillit and @Cieramaddox !
