### ISSUE TITLE
Team members needs updated access to va.gov-team repo

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4515]
The following individuals need updated access to the va.gov-team repo. They will need both read and write access. I'm currently unable to assign issues to them in this repo.

- GH username: TamGIBill
- GH username: josephpreisser
- GH username: lucastickner

They currently have access to vagov-content and vets-website repos. Their access was originally granted as part of this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3690

**Comment by bobrox1973** [comment]
I have added the users below to the vets.gov-write team, which has write access to the va.gov-team repo. there was no user with the username - lucastickner, so I did a search and added the user - LTickner to the repo. In the future please verify the username prior to submitting the request.
GH username: TamGIBill
GH username: josephpreisser
GH username: lucastickner
