### ISSUE TITLE
SOCKS access for [Azeez.Salu]

### ISSUE THREAD

**Issue by azeez-salu** [department-of-veterans-affairs/va.gov-team#45163]
### Your Name

Azeez.Salu

### Your Email

azeez.salu

### Your Role and Team

Security Engineer on Platform Security 

### Product Manager (PM) name and email

 Nancy Smith - nancy.smith@oddball.io

### Product Owner (PO) name and email

 Nancy Smith  - nancy.smith@oddball.io 

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCy32lAxMKB+wMRLypirKUX777CLu58dhzs1y95c5JVQgB7FEU5IlL96JTNok5iRGLItR1KEm+ddEn7DwALySkJwEI0e64J0z40QvraweyJFyEjn0Xa+Ur5lyKf7rm1hhtFu0GqkCpyB0Hi+0JPzZgk72grQWF6X71rAiOml60jLalPoFzKlEbdmgJ7lzpWFCtDmzq/HscA/KL8xK+EtBzL97AxHPT9OBXjAUsYrJOs6k+2akyQNIumHwRwerlZt8yGG3vpA4rgy5FF0qOg02sM1tvygh6Du9VlvEfLd5OpF7YgDy+e5D/hm0lizcRqFLswMSeI0tep9wn9U672nIQdMCm61n7esN8ggRTZV0wXbgHQ/EFbej+UBRF4n+6GvkZ9zxioqUsdWR3eHzlsEOE6qi0QVldD0WNR4vH/bmcgOmcJwEky2jWgxXH3UPdsZRSMJLpUOdn2yzu+AGWnpfwvK1VK36nnxqkmBie6is+cODsu/m4wDQinxeUf+h3Gurs= aosnote@Azeezs-MBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jsgarmon** [comment]
The bot is not finding his email, though Azeez in in the roster: https://vfs.atlassian.net/wiki/rest/api/content/1908834623?expand=space,metadata.labels,body.view
Almost nobody in here has an email listed, so we might want to change this check to use full name instead of email.

**Comment by kjduensing** [comment]
Good point @jsgarmon. @kylesoskin thoughts on updating the bot to use first + last for at least the platform roster check?

**Comment by kjduensing** [comment]
@azeez-salu - making the SOCKS access PR now :)

**Comment by azeez-salu** [comment]
Thank you @jsgarmon, and I appreciate your help. Is there anything else that I need to do on my end?

**Comment by kylesoskin** [comment]
I will move this discussion out of Azeez's ticket and into infra channel

**Comment by azeez-salu** [comment]
> @azeez-salu - making the SOCKS access PR now :)

Thank you!

**Comment by kjduensing** [comment]
@azeez-salu - SOCKS access granted! Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by azeez-salu** [comment]
@kjduensing Thank you very much. I appreciate your help
