### ISSUE TITLE
Automate export of markdown to pdf for Microservices Playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#45185]
As a user of github, I do not like the UI and visuals for reviewing engineering documentation. I would like a consolidated view in one single easy to read document format such as an exported PDF. Also, I would this PDF document to be automatically updated as the document is updated over time. I would like the Microservice Playbook to be the first document to leverage this capability.

Acceptance
- [ ] As a user I can export the latest copy of the Microservices Playbook into a PDF file
- [ ] The PDF file for the Microservices Playbook will automatically be updated when any changes are made to the document
- [ ] A pipeline exists (such as github actions) that allows the user to generate the new PDF and check it into the repository
- [ ] This work should be timeboxed to what can be completed at the end of the contract period: ideally this PDF would include the contents of all of .MDs collated together, however a partial solution would also suffice

**Comment by MrBilnon** [comment]
is it expected that the PDF be updated when merged? So we need to implement some sort of pipeline (github actions) to generate the new pdf and check it into the project?
