### ISSUE TITLE
Create vfs-platform-support Support Bot Option for "Console UI" team.

### ISSUE THREAD

**Issue by jchapin** [department-of-veterans-affairs/va.gov-team#45187]
Hi, Console UI would like to be integrated into the normal ```/support``` bot procedures. We have requested that a group be set up for us:

https://dsva.slack.com/archives/CBU0KDSB1/p1659461892997579

We're trying to follow the procedures the Forms Library Team used to get set up back on April 11th.

**Comment by zachclarity** [comment]
Completed.

**Comment by zachclarity** [comment]
Completed.  See https://dsva.slack.com/archives/CBU0KDSB1/p1659461892997579
