### ISSUE TITLE
Fix issues with installing component-library dependencies in vets-website

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#45219]
## Description
When installing the `@department-of-veterans-affairs/component-library` package in the `vets-website` repository, the dependencies `@department-of-veterans-affairs/react-components` and `@department-of-veterans-affairs/web-components` aren't being installed at the root level in the `node_modules` directory, but rather in the `node_modules` sub-directory of `@department-of-veterans-affairs/component-library`. This is causes issues with the build and unit tests because of the babel [aliases](https://github.com/department-of-veterans-affairs/vets-website/commit/aaf6601f2d7456f169231ee6489f0e26cfb452f9#diff-93762d35cbe27a8746e1c2d67f37f28c5228d3902431877c5aa64fe884d5c1e0R63-R74) that are used. The aliases are expecting the `react-components` packages to be installed as a dependency. A workaround for the aliases was added in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21802)

This problem only seems to happen in the `vets-website` repository, as installing `@department-of-veterans-affairs/component-library` in other repositories seems to install `react-components` and `web-components` at the root level in `node_modules`. 

One interesting discovery is that removing the `i18next-browser-languagedetector` package from the `vets-website`'s `package.json` seems to allow the `component-library` to install `react-componets` and `web-components` at the root level of the `node_modules` directory. `i18next-browser-languagedetector` is also a dependency in the `component-library` [package](https://github.com/department-of-veterans-affairs/component-library/blob/e0ac32489464e6443cb19cb4cdbd720bc7e56c87/packages/core/package.json#L19).

[Slack thread](https://dsva.slack.com/archives/CQH357ZTP/p1659102320475329)

## Definition of done
- [ ] `@department-of-veterans-affairs/component-library` is able to install the `@department-of-veterans-affairs/react-components` and `@department-of-veterans-affairs/web-components` dependencies at the root level of the `node_modules` directory in `vets-website`
- [ ] The babel aliases for the `react-components` module are reverted to reference the module at the root level (i.e. `@department-of-veterans-affairs/react-components/LoadingIndicator`, etc.)

**Comment by timwright12** [comment]
I've seen this happen when there are multiple versions of the same dependency being installed. Something to look into

**Comment by timwright12** [comment]
PR is open, but I had to skip a test to get it through CI so we have to wait for approval from the code owner

**Comment by timwright12** [comment]
PR has been merged, just awaiting `main` CI

**Comment by timwright12** [comment]
This has been merged, closing out
