### ISSUE TITLE
Force the reindexing of va.gov pages from search.gov

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4521]
Currently, if you search ["Blue Water" on VA.gov](https://www.va.gov/search/?page=1&query=blue+water), there is a result that reads `Blue Water Veterans and Agent Orange Exposure - Public Health`. The correct term is __Blue Water Navy Veterans__. This has been corrected already in the page source for that [page](https://www.publichealth.va.gov/exposures/agentorange/locations/blue-water-veterans.asp). This suggests that the search.gov indexing, which powers our search results, is not updating that page to get the most up-to-date title.

To fix this, we should consider our options for doing the equivalent of issuing a "recrawl" to search.gov. We may have to create a sitemap for the VA subdomains and then consult the search.gov team per https://search.gov/manual/site-launch-guide.html. We should first consult the search.gov team for guidance.

### Screenshot of issue
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/09f12aa1-995c-4c2c-8fce-da82b4b9b477)

### Acceptance Criteria
- [ ] When you search "blue water" on va.gov, results use the correct term "Blue Water Navy Veterans" and not "Blue Water Veterans"

**Comment by ncksllvn** [comment]
CC: @Karak888 

Also, linking to additional tasks - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/va.gov_site_search_brainstorm_list.md

**Comment by aeltarhoni** [comment]
Per @jenniferlee-dsva it is complete.
