### ISSUE TITLE
[support] Grafana sync failure

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#45226]
## Description
This PR was merged: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/669.  But the sync failed in argocd.
https://argocd.vfs.va.gov/applications/grafana-utility?view=tree&resource=&node=%2FPod%2Fobservability%2Fgrafana-6d7c877657-x28ns%2F0&tab=events

Error (formatted by me):
```
The order in patch list: [
  map[
    name:GF_SECURITY_ADMIN_PASSWORD
    valueFrom:map[
      secretKeyRef:map[
        key:admin-password 
        name:grafana
      ]
    ]
  ] 
  map[
    name:GF_SECURITY_ADMIN_PASSWORD
    valueFrom:map[
      secretKeyRef:map[
        key:grafana_admin_password 
        name:grafanasecrets
      ]
    ]
  ] 
  map[
    name:GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET 
    valueFrom:map[
      secretKeyRef:map[
        key:grafana_keycloak_secret 
        name:grafanasecrets
      ]
    ]
  ]
] 
doesn't match $setElementOrder list: [
  map[
    name:GF_SECURITY_ADMIN_USER
  ] 
  map[
    name:GF_SECURITY_ADMIN_PASSWORD
  ] 
  map[
    name:GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
  ] 
  map[
    name:GF_AUTH_GITHUB_CLIENT_ID
  ] 
  map[
    name:GF_AUTH_GITHUB_CLIENT_SECRET
  ] 
  map[
    name:GF_DATABASE_PASSWORD
  ] 
  map[
    name:GF_SECURITY_ADMIN_PASSWORD
  ] 
  map[
    name:GF_SESSION_PROVIDER_CONFIG_PASSWORD
  ] 
  map[
    name:GF_SESSION_PROVIDER
  ] 
  map[
    name:GF_SESSION_PROVIDER_CONFIG_DBNAME
  ] 
  map[
    name:GF_SESSION_PROVIDER_CONFIG_HOST
  ] 
  map[
    name:GF_SESSION_PROVIDER_CONFIG_PORT
  ] 
  map[
    name:GF_SESSION_PROVIDER_CONFIG_SSLMODE
  ] 
  map[
    name:GF_SESSION_PROVIDER_CONFIG_USER
  ]
]
```

## Technical notes
This issue might be relevant: https://github.com/helm/helm/issues/6002
Relevant Slack threads:
https://dsva.slack.com/archives/CTYQL39FE/p1659452984492179
https://dsva.slack.com/archives/CBU0KDSB1/p1659452981519549

---
## Tasks
- [ ] Figure out problem

## Acceptance Criteria 
- [ ] Problem is fixed and Argo is syncing without failure

**Comment by ph-One** [comment]
The issue is duplicate environment variables. Once we locate why they are duplicated, the issue should be cleared up. `GF_SECURITY_ADMIN_PASSWORD` is used twice, which is the problem to solve.

**Comment by ph-One** [comment]
This block, specifically, cannot be accounted for in IaC. I am unsure where this is coming from atm

```
  map[
    name:GF_SECURITY_ADMIN_PASSWORD
    valueFrom:map[
      secretKeyRef:map[
        key:admin-password 
        name:grafana
      ]
    ]
  ] 
```

**Comment by rmtolmach** [comment]
More observations:
* Out of the `name`s listed, all of them are defined in `vsp-infra-application-manifests/apps/vsp-amt/grafana` or `vsp-infra-application-manifests/apps/vsp-operations/grafana` or in both places. All of them EXCEPT one: `GF_SECURITY_ADMIN_USER`. It's not defined anywhere in our code.

* `GF_SECURITY_ADMIN_PASSWORD` is listed twice in the manifests repo:
In `apps/vsp-amt/grafana/values-dev.yaml`:
```  
    GF_SECURITY_ADMIN_PASSWORD:
      secretKeyRef:
        name: "grafanaamt"
        key: "grafana_admin_password"
```
And in `apps/vsp-operations/grafana/values.yaml`:
```
    GF_SECURITY_ADMIN_PASSWORD:
      secretKeyRef:
        name: "grafanasecrets"
        key: "grafana_admin_password"
```

* `GF_SECURITY_ADMIN_PASSWORD` is also listed in: https://github.com/department-of-veterans-affairs/vsp-infra-local/blob/master/nomad_jobs/05_grafana.nomad#L61
```
            template {
                destination = "secrets/file.env"
                env          = true
                data = <<EOF
GF_SECURITY_ADMIN_PASSWORD = "{{with secret "local/data/grafana/admin_password"}}{{.Data.data.value}}{{end}}"
EOF
            }
```

**Comment by rmtolmach** [comment]
Fixed with https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/683 and https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/684
