### ISSUE TITLE
[Spike] Accreditation file dates issue and LOE

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#45225]
Accreditation dates are not loaded correctly, which is causing CT tool to generate a Caution flag on institutions when the correct dates located in the file. The system is using the older dates and ignoring the most up to dates located in the "Date Column"  

## Tasks
- [ ] _Please determine why the dates are not loaded correctly in the accreditation file, Determine the LOE that it will take to fix the issue.

**Comment by af-manish** [comment]
Example accreditation file:
[https://app.zenhub.com/files/133843125/983bafcd-c751-4f8c-87c7-3b3a4c4cc946/download](https://app.zenhub.com/files/133843125/983bafcd-c751-4f8c-87c7-3b3a4c4cc946/download)

**Comment by dan-brooking** [comment]
It looks like as the accreditation file is updated, it's not clearing out caution flags that no longer exist. So those institutions continue to remain flagged.

The suggested fix is to reset the values of accreditation_status, caution_flag and caution_flag_reason to nil before the institution builder runs and then run through the current institution builder logic to populate appropriately.

LOE: 1-2 sprints.

**Comment by mrblanco1** [comment]
Abe shared Dev's analysis results and LOE with VA EDU on 8/04/2022 a.m. Dev work will begin as soon as Michael Napper and Darla approve on Monday 8/08/2022.
