### ISSUE TITLE
SOCKS access for Samuel Cormier

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#45235]
### Your Name

Samuel Cormier

### Your Email

sam.cormier@coforma.io

### Your Role and Team

Software Engineer on VA Benefits

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matt Self, matt.self@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Af5JQ3M4P7QFWy6AWO3Msydf4supg4T8CyCF7qcfrdmN823fkkBhjJPTu5BbkO6zaK6ohLNKU2yVFRmpTjQMs4zC4Lk0YC/Mtb6LakGwS3hYgku+isfs43nGpUH+/arpH/Ux9sV9Z6+gZQwx6rMBQW2PkNlk+lkH5+k1KMJSrVzZkq+c3sMSgpiiDvY7WTL6qPng8ZhqHRpvBSDrDIi2GBLplECFvsPMw+IGofd2/qSkE0z+7kDu38gm2JvW215j6WB1GnuCiloeJuZbMkbB7RjSC2XEPYdL2tc4QnKof0VKELNt9IBqBNcDBqbu5DojiZwOfSTKJx84wqlhxw4hDqPOrtq4MvZlbvRFARlMRYqqzNqRRwJ640qHJqVb/N0w+1+M2wCj5gZbbiZKPAVbqZ2MMrIMOYOMlcfsQvIP/xomecOhgqYIu4yWlbEPomZo+R/9N/755f8cJY4+Q0TVVNmCqbHqqheTg3wWmCETes80pFqQeuFuv3032NIFbwU= samc@Samuels-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@samcoforma - SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).

**Comment by kjduensing** [comment]
@samcoforma as a heads up, it may take 5 - 10 mins for the servers to finish updating, but you should be good to go.
