### ISSUE TITLE
Add checkin stats to daily stats

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#45231]

**Comment by lindsay-insco** [comment]
Revisit to reconcile differences in stats

**Comment by lindsay-insco** [comment]
Being sent in daily email stats. 

Rob updated code to obtain stats to resolve mismatched data. @Cmjones233 to verify data accuracy.

**Comment by Cmjones233** [comment]
numbers are off significantly

**Comment by Cmjones233** [comment]
Dashboard taken down an no longer in use. Numbers were off but there is a know issue with data being reliable
