### ISSUE TITLE
EForce/GI Bill Feedback Tool Connection Assistance

### ISSUE THREAD

**Issue by TylerWatkins1** [department-of-veterans-affairs/va.gov-team#45246]
## Description
 Need assisstance from Ops Team in connecting Salesforce environments (VACOEDUSIT, REG, and Production) to their corresponding Feedback Tool instances (DEV, STAGING, and Production). Meeting is scheduled with Tyler Watkins, Shirley Edwards, Oseas Moran and Kyle Matheny for August 4th at 3 PM PT/5PM CT/6PM ET.

## Background/context 
Certificates connecting Salesforce and GI Bill Feedback Tool Expire annually. Updated Certs have been generated and obtained by System Admin. When the certs are updated in Salesforce, consumer keys will be generated and provided to Ops Team to update in AWS and a PR is needed. 

## Technical notes
Salesforce Environments:
1. https://va--vacoedusit.my.salesforce.com/ 
2. https://va--reg.my.salesforce.com/
3. https://va.my.salesforce.com/

Feedback Tool instances
1. https://dev.va.gov/education/submit-school-feedback/introduction
2. https://staging.va.gov/education/submit-school-feedback/introduction
3. https://www.va.gov/education/submit-school-feedback/introduction

Provide updated Consumer Keys to Ops Team to update in AWS
Ensure VACOEDUSIT, REG, and Production are connected to the Feedback Tool instances of DEV, STAGING, and Production.

---
## Tasks
Update Certs in Salesforce environments (VACOEDUSIT, REG, and Production) 
Provide updated Consumer Keys to Ops Team to update in AWS
Ensure VACOEDUSIT, REG, and Production are connected to the Feedback Tool instances of DEV, STAGING, and Production.
Tyler Watkins needs to understand the process to do this with very little assistance from Ops Team for future cert updates.

## Acceptance Criteria 
1. https://va--vacoedusit.my.salesforce.com/ must be connected to https://dev.va.gov/education/submit-school-feedback/introduction after updating certificate
2. https://va--reg.my.salesforce.com/ must be connected to https://staging.va.gov/education/submit-school-feedback/introduction after updating certificate
3. https://va.my.salesforce.com/ must be connected to https://www.va.gov/education/submit-school-feedback/introduction after updating certificate

---
### Reminders
Operations
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
Adding [slack](https://dsva.slack.com/archives/CBU0KDSB1/p1659371698987569) thread

**Comment by oseasmoran73** [comment]
Had a call with Tyler and Salesforce team and were able to update the following:

- URL for dev (despite the environment not working unfortunately. Something that may need collaboration between infra and console services)
- URL for staging (provided on the called with Tyler & verified)
- Verified & updated the consumer_key with SFA against prod

Additionally, provided Tyler and Scott instructions on how to get AWS access & param store access for him and his team to modify (sent in an email) rather than be dependent on infrastructure team

Thanks for being patient with us and today on the call! Closing this ticket out. Please feel free to reopen or message in slack should an issue arise

**Comment by ph-One** [comment]
The following cURL commands can be used for testing

```
curl 'https://dev-api.va.gov/v0/gi_bill_feedbacks' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: TS01de8f7b=01c8917e488ae4bd5bb2c574e7ec192ecbbf35b3ca42d0fcb3da8c7151ad73525a8a60de655e9752ce8d15929de797ae54cc489d9e; api_session=CYdsPUjDy7lqrBYEV29v%2BRAj76AgdNlGftcIt69G8dpdeTv5Hbfal3IEKSKrLl%2B9uq8z7UahxgGJn6n%2FCgmJtPOnZIquE1Sqcy98JiYtN4p07aiSLlbuxY8jHXYDAIlhVMiS8x7%2FeZl3ozpzFBI7clmB8TAbv1GDIMOu2gFce0r7zZzbKcuMBVmqfmtjleoGbtaASqhglW7QhAkkKie75Kw%2BTXn7JtpTFuoK6m1PYuUc5B9iYbPiq0C%2FeL2teWL056t9KGzX0ylInV1IpecUBXSmz%2FuEeQeEdHUfkmW4aIanc%2BZeBaaA5KUQ1rqUHLw%3D--YFLaQ53TaEP62lrU--eX3OC4DX%2F%2Bb3IUez1jxOTw%3D%3D' \
  -H 'Origin: https://dev.va.gov' \
  -H 'Referer: https://dev.va.gov/education/submit-school-feedback/review-and-submit' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Source-App-Name: feedback-tool' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.167 Safari/537.36' \
  -H 'X-CSRF-Token: HfVc02C9BcH949E5/UypqBQKuahGHUsJvqTdoFziF5qtSlmEDpJj7OCS9aLfKrMsx+Bfex5fEEP0dYEIoKavAg==' \
  -H 'X-Key-Inflection: camel' \
  -H 'sec-ch-ua: "Chromium";v="102", " Not A;Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{"giBillFeedback":{"form":"{\"issue\":{\"other\":false,\"recruiting\":false,\"studentLoans\":false,\"quality\":false,\"creditTransfer\":false,\"accreditation\":true,\"jobOpportunities\":false,\"gradePolicy\":false,\"refundIssues\":false,\"financialIssues\":false,\"changeInDegree\":false,\"transcriptRelease\":false},\"issueDescription\":\"a\",\"issueResolution\":\"a\",\"educationDetails\":{\"school\":{\"facilityCode\":\"13901101\",\"name\":\"ALABAMA STATE UNIVERSITY\",\"address\":{\"country\":\"United States\",\"street\":\"PO BOX 271\",\"street2\":\"915 S JACKSON STREET\",\"city\":\"MONTGOMERY\",\"state\":\"AL\",\"postalCode\":\"36104\"}},\"programs\":{\"chapter33\":false,\"chapter30\":true,\"chapter1606\":false,\"tatu\":false,\"chapter35\":false,\"chapter31\":false},\"assistance\":{\"ta\":true,\"taAgr\":false,\"myCaa\":false,\"ffa\":false}},\"onBehalfOf\":\"Anonymous\",\"anonymousEmail\":\"k@k.com\",\"privacyAgreementAccepted\":true}"}}' \
  --compressed

curl 'https://staging-api.va.gov/v0/gi_bill_feedbacks' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: TS013da938=01c8917e48178a5523dcffb6ffbe7704eecfb980003911412e591260e701b09fb4a826025708eb88257e5c3c31cf5f274eb5f07012; api_session=np30FRtygldlMVIIaJC8jPMpWpdnU8pJxTRWzhxzABcAkdQcmpAizP5Oj%2Bg%2FfE%2FDEOoI489e3sREmbn0p2LsKbR7XHTfpzilwNLlVoR1BJ1wG2b6ELrUn1pPf07D660Ex3s1RMszUkrEqLfQXtJ7Dbi6k7hF1SbvsOCoZX9PBDT4nI8%2FAK1%2BQ%2FPDty8RS7i%2BowV68sM9P9eJ9QgWIzQggW4nfld6oopdCje4jVuBpxGPXcEYEoUZIpYaYQP1KFE%2F1GQpGr1XHZwLauDWEk2QyZA%2BI6lBWqV8GowCLBH5GSfCMIPbCaYBX%2FluMSE5i7s%3D--lTotTazscqNFodjd--92ju880TohUrHBfsq8uxkg%3D%3D' \
  -H 'Origin: https://staging.va.gov' \
  -H 'Referer: https://staging.va.gov/education/submit-school-feedback/review-and-submit' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Source-App-Name: feedback-tool' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.167 Safari/537.36' \
  -H 'X-CSRF-Token: EizshxWd7VYh6Ry6G43TTSFyK/j91abHvmt/D9w8r5VJZsJy62xH63vD5hqBCvfVPaYJzHutF4V+UeAswXzdVQ==' \
  -H 'X-Key-Inflection: camel' \
  -H 'sec-ch-ua: "Chromium";v="102", " Not A;Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{"giBillFeedback":{"form":"{\"issue\":{\"other\":false,\"recruiting\":true,\"studentLoans\":false,\"quality\":false,\"creditTransfer\":false,\"accreditation\":false,\"jobOpportunities\":false,\"gradePolicy\":false,\"refundIssues\":false,\"financialIssues\":false,\"changeInDegree\":false,\"transcriptRelease\":false},\"issueDescription\":\"a\",\"issueResolution\":\"b\",\"educationDetails\":{\"school\":{\"facilityCode\":\"13901101\",\"name\":\"ALABAMA STATE UNIVERSITY\",\"address\":{\"country\":\"United States\",\"street\":\"PO BOX 271\",\"street2\":\"915 S JACKSON ST\",\"city\":\"MONTGOMERY\",\"state\":\"AL\",\"postalCode\":\"36104\"}},\"programs\":{\"chapter33\":false,\"chapter30\":false,\"chapter1606\":false,\"tatu\":false,\"chapter35\":true,\"chapter31\":false},\"assistance\":{\"ta\":false,\"taAgr\":false,\"myCaa\":false,\"ffa\":false}},\"onBehalfOf\":\"Anonymous\",\"anonymousEmail\":\"k@k.com\",\"privacyAgreementAccepted\":true}"}}' \
  --compressed
```
