### ISSUE TITLE
FE | Profile | BAI Foundational Accessibility Testing

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45262]
## Background

Conduct foundational accessibility testing prior to staging review.

Staging Review Process doc [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)

Checklist of the recommended and required accessibility tests have been completed for this effort.

**Foundational accessibility tests (required)**

- [x] Axe scans in daily development 

- [x] Axe scans included in end-to-end (e2e) tests 

- [x] Color tests for proper contrast and colorblindness 

- [x] Content zoomed to 200%, 300%, 400% 

- [x] Keyboard navigation 

**Advanced Accessibility tests (recommended)**

- [x] Screen reader tests (VoiceOver + Safari or NVDA + Firefox) 

- [x] WAVE tool spot checks 

** Additional Tasks**
- [ ] Create tickets for any fixes that are required based on above testing

**Comment by adamwhitlock1** [comment]
I ran axe tests, verified that axe tests are run in E2E tests, and checked for visual contrast. All core accessibility checks seem good.

Wave report:

![Screen Shot 2022-08-23 at 1.50.59 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/28293ff5-d580-4e31-8b8f-254206092eae)

Only 1 error and 1 alert and both are not from this particular feature, but instead are issues with the header section of site.

**Comment by adamwhitlock1** [comment]
Conducted foundational accessibility testing and did not discover any defects to address. Closing
