### ISSUE TITLE
Look at higher bounce rates for screen resolutions

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#45283]
## Background
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/de005cc2-b27d-478d-887c-143be2daacb0)

## Tasks
- Get list of bounce rates at various resolutions and devices per page
- Test the problematic rates in staging with resolution/device emulators to see how the pages display
- Document the list of problems

## AC
- Document the list of problems & present to team

## Details
- Details in [slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1659534988915889)

**Comment by acrollet** [comment]
Let's try to also pull OS/device info and see if we can narrow down the pattern here.
