### ISSUE TITLE
Add space to the "Need help" pseudo-footer on short pages

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#4528]
There are some pages that have a single short-n-sweet question on VAOS, and the "Need help?" section is too close to the Back/Next buttons, which makes it hard to scan the page, for example:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/0db95d99-e868-4344-ab12-77e8b7260e02)

We need to add about 2x or 3x the space below the buttons on those shorter pages.

**Comment by jbalboni** [comment]
Further comments from @rtwell: double the space below the buttons and then send him a screenshot to confirm that it looks ok on a longer page.

**Comment by jenniemc** [comment]
Hi @rtwell, doubled the space below the buttons to give extra spacing for the pseudo "Need help?" footer. I took a screenshot of the short and long pages. How would you to receive the screenshots for review?

**Comment by rtwell** [comment]
You can post them here! Whatever is easiest for you—as long as there is a link where i can see them

**Comment by jenniemc** [comment]
@rtwell,
------ **Here's a screenshot of SHORT PAGE** -----

![image](https://user-images.githubusercontent.com/54327023/72110183-8ce6a400-3305-11ea-97ee-d780d2f69387.png)


------- **LONG PAGE** -------

![image](https://user-images.githubusercontent.com/54327023/72110358-04b4ce80-3306-11ea-9a8c-6983e3fc2ba8.png)

**Comment by rtwell** [comment]
I think this is enough space for now—we'll find out if we need to add more! Thank you @jenniemc !
