### ISSUE TITLE
Remove breadcrumb from print view

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#45288]
## What happened?
Currently when the veteran prints their appointment list or details page, the print page includes the breadcrumb

## Steps to Reproduce
- Navigate to the appointment detail page
- click the print button

![Screen Shot 2022-08-04 at 8.12.41 AM.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/b79d725d-2dce-4460-b6e7-808812347db8)

## Desired behavior
When a veteran prints their appointment list or detailed appointment, it should display just a clean and organized list of their appointments. No breadcrumb.

## Acceptance Criteria
- [x] breadcrumb does not display in the print view

**Comment by ldelacosta** [comment]
@tlei123 - This ticket is ready for validation. Thanks!

**Comment by tlei123** [comment]
@ldelacosta , AC's successfully validated in Staging.

**Comment by ldelacosta** [comment]
This has been validated. Closing out the ticket.
