### ISSUE TITLE
[Copy] Button copy update for address validation where there is only one option

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4529]
## User Story:

As a person using a screenreader, I need the CTAs to be clearer when I am trying to update my address, address validation is triggered, and there is only one address to save. 

## Background

This issue was originally brought up in #4526.  TL; DR is that we have two states that are a problem:

- One is for address validation where a user is allowed to override the determination that their address is problematic, but we do not have any suggested addresses for them. 
- The other is when address override is not allowed and there is only one suggestion.

In both cases, this resulted in there only being one radio button on the form, which is problematic from a usability perspective and for screen readers — radio buttons should only be used when there are multiple options and not when there is only a single option. 

Therefore, I am proposing new designs that remove the single radio button in the problematic states and makes small design adjustments so that the designs will make sense to both people who do and do not need a screenreader.

### Override allowed; no suggestions

We need button copy for the "Use address as entered" CTA shown in the screenshots below.

There are **three** states where a user is allowed to override their address and there are no suggested addresses, which would result in the single radio button problem I have outlined above. However, despite their being three states, we probably need one version of this button copy (and I would prefer that from a code perspective as well). However, I am showing all three states below in case that influences the button copy, or the new design/button copy results in any changes to the warning copy above it.

![13  Scenario 2_ Override; No suggestions](https://user-images.githubusercontent.com/34068740/71735384-4f24df80-2e1c-11ea-913f-1b5bf30773c1.png)
![Add missing unit number with override](https://user-images.githubusercontent.com/34068740/71735385-4f24df80-2e1c-11ea-904c-537a324dd2c6.png)
![Edit bad unit number with override](https://user-images.githubusercontent.com/34068740/71735387-4f24df80-2e1c-11ea-894a-dfa5b9a2513f.png)

### No override, one suggestion

Like above, we need copy for the main blue CTA:

![18  Scenario 3_ No override; Only one suggestion](https://user-images.githubusercontent.com/34068740/71742749-bc427000-2e30-11ea-8289-dfac8cd9d51a.png)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Provide updated button copy for the "Use address as entered" button shown in the screenshots above
- [ ] Provide updated button copy for the "Use suggested address" button above

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Button copy is updated

**Comment by peggygannon** [comment]
@Samara-Strauss 
Button CTA recommendations below. I tweaked the button language to keep wording succinct and parallel: 

For 1st scenario, Override allowed/no suggestion:
{button} Use entered address

For 2nd scenario, override isn't allowed/one suggestion:
{button} Use suggested address 

---

Question: for 2nd scenario, would there ever be a use case where more than one suggested is given to the user? Let me know if I need to write copy for that situation?

**Comment by Samara-Strauss** [comment]
> For 1st scenario, Override allowed/no suggestion:
> {button} Use entered address

Suggestion: What do you think of "Use this address" instead?

> For 2nd scenario, override isn't allowed/one suggestion:
> {button} Use suggested address

Great!

> Question: for 2nd scenario, would there ever be a use case where more than one suggested is given to the user? Let me know if I need to write copy for that situation?

There is! And we already have design/copy for it. Thanks for checking, though!

**Comment by peggygannon** [comment]
@Samara-Strauss Thanks! 

I like your suggestion: Use this address, so let's go with that one. 

Let me know if there's anything else you need from me on this.

**Comment by Samara-Strauss** [comment]
FE ticket #4632
