### ISSUE TITLE
Elements in GIDS do not have sufficient color contrast

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4530]
## Dashboard Page
- The word "Dashboard" in the header
![Screen Shot 2020-01-03 at 11.22.37 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/24a95629-5515-49b4-9254-e7f33e287d1d)

- Show GIBCT and Download Export CSV buttons under Latest Production version
![Screen Shot 2020-01-03 at 10.54.10 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3cac2155-c954-4824-812a-d41327ac4904)

- Generate New Preview Version button
![Screen Shot 2020-01-03 at 10.54.48 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1c370bcc-c3b3-4eca-851a-c2a0ed2119e3)

- Show GIBCT and Download Export CSV and Publish to Production buttons under Latest Preview Version
![Screen Shot 2020-01-03 at 11.01.40 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2fed786f-d711-47ca-a529-8dedc4cf9703)

- View Upload History Button
![Screen Shot 2020-01-03 at 11.02.34 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/86d15d4e-7595-4617-9ede-63724631e908)

- All Upload and Export Button in the Latest Uploads table
![Screen Shot 2020-01-03 at 11.07.55 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/07cde46e-67da-4e71-b05d-89c8bb3cecf7)

## View All Uploads Page
- The word "Upload" in the header
![Screen Shot 2020-01-03 at 11.24.44 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/54b56efc-75af-41c3-85c9-8c41ff1826ff)

- The View Dashboard button
![Screen Shot 2020-01-03 at 11.25.25 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/651ca130-2a23-43f8-acb9-8e15a4cab3cb)

- Previous and Next (when disabled)
![Screen Shot 2020-01-03 at 11.26.07 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d5b1580e-d31d-4546-9359-c5c000658bfb)
![Screen Shot 2020-01-03 at 11.26.51 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ee588b8d-fbbf-45ac-9ef9-a753d5c4531f)

## Shared Storage Page
- The word "Storage"
![Screen Shot 2020-01-03 at 11.28.30 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/51ddbc88-95ca-41c5-b7cc-7060d12f75f7)

- The View Dashboard button
![Screen Shot 2020-01-03 at 11.29.00 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/65f4bf16-43b5-49b0-8636-98310f9f2a58)

- The red warning text
![Screen Shot 2020-01-03 at 11.29.43 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ebde6eb6-ed86-49b8-a7f1-470e69616c9a)

- All Download and Upload buttons in the table
![Screen Shot 2020-01-03 at 11.30.14 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1199a463-33ca-4bf9-8532-6a746be11fcb)

## File Upload page
- The word "Upload" in the header
![Screen Shot 2020-01-03 at 2.27.57 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/016f76e1-9e82-42ab-9b75-bc97d8f917bc)

- View All Uploads and View Dashboard buttons
![Screen Shot 2020-01-03 at 2.27.50 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/af872809-f365-4d32-9f64-9ff7af7b61dc)

---

[More info on WCAG AA Contrast Ratio requirements can be found here](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html)

These defects can be reproduced using the following tools:
- [Axe](https://www.deque.com/axe/)
- [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html)
- [Wave](https://wave.webaim.org/)

**Comment by ksantiagomorgan6** [comment]
Pull Request: 

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/540

**Comment by delli-gatti-michael** [comment]
All color contrast issues but the following button are fixed in Staging:

![Screen Shot 2020-01-14 at 9.51.59 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b1aa8cdf-a9e8-43e0-98dc-3abba5d1cdac)

The fix will be included in the following PR:

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/542

**Comment by delli-gatti-michael** [comment]
All changes are now in Staging. Closing this issue
