### ISSUE TITLE
SOCKS access for [Won Choi]

### ISSUE THREAD

**Issue by wchoiva** [department-of-veterans-affairs/va.gov-team#45306]
### Your Name

Won Choi

### Your Email

won.choi@va.gov

### Your Role and Team

DevOps

### Product Manager (PM) name and email

Riley Ross (riley.ross@va.gov)

### Product Owner (PO) name and email

Riley Ross (riley.ross@va.gov)

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnd7scRhYCyGqgWAd9WoMVJ/l5jei3qCZGx5b21qSosr4EUwppqiqV2TVA3c6xiPeavbiXW2dhD0ANUUWNHCPe4Fq4zLd2MC5iTFEadKW80GvdZp4gwzbx/AwkxhV09y93AZM3purg0+E364cUV/ga1TqUwKzcRiYZCsi0NpTip+BKJLIAcLWzSCrsEqs0RDJ/Ku6hEf54s7Cxf98A0jwXAXBnM0K7m7js64JxYlYVS9oAZdRXnVly/ogK7rdIf8wUupZ3eGF1ZyH5gzDCpU56/QOHQsEZ5j4ufP1IL7ovjGG+e2Fjwr+81nsqEJjyRB/i3xzOOlklh+2EdmoDn2hZ7ryYpBpJPC0MgKS3sKFSk4n8W76riGBBQdIjPGICtbDkV5t8EOZwZ52liWu5bpQyOxj1zjomNO3ARajfm6JVkoICow78I4TrP7GR2qNFUo00Tf8lFtLW7PLBJQcnL7KDNzxzWbRRtee5e8Ldb+lZGnau0Mj7vlvWm0Y0hGnqiJOfQB+O2hVx3TSMVv5MMXYZw79+BrKCCAkzPKk7n8c73JjTwFdDlLahhOteOTJ50/2kzDl8dkRAoOBdhwzsHF46R1n49V3pdSITlAyoH8dDG8FusW5EcX1m2OWtDA3nMBGXF29xvPqAFS3mPpAyfVgdnIN9PqdIyLGhri8PrLw2SQ== won.choiVAEC.pe

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
Due to an issue with the SOCKS automation, I am going to close and reopen this issue to re-run the automated checks for SOCKS access.

**Comment by kylesoskin** [comment]
Reopening

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
