### ISSUE TITLE
[ONGOING] Collaborate with VAOS

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45318]
## Blocker
VAOS is going through usability testing, don't want to talk with them until they are done synthesizing their findings

## User Story
As the VA, we would like the presentation/display of appointment information to be consistent across VA applications so that the Veteran will see the information in the same way each time they access it on a different application.

## Tasks
- Collaborate with VAOS et. al. to determine the final look & feel for displaying appointment information
    - VAOS (Vet can schedule an appointment online & see all your appointments [past, future])
- Cover how VAOS displays modality type in appt list. E.g., so PCI can include modality type in day of check in. 

## Later
- We might want to collaborate with these others
    - Mobile App (Vet can see their appointment list, schedule?)
    - MHV (Vet can see their appointment list) (moving to VA.gov) (also the EMR)

**Comment by kristenmcconnell** [comment]
VAOS is wrapping up their research report right now, which I'll review with them later this week. I will double check, but they haven't started making adjustments to their designs yet. This ticket may not be complete this sprint as a result.

**Comment by loripusey** [comment]
we'll just roll it over until we are able to make progress on our end

**Comment by kristenmcconnell** [comment]
Here is VAOS's [research report](https://dsva.slack.com/archives/C02GXKL8WM6/p1666715801647569).

**Comment by kristenmcconnell** [comment]
Here is the [Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1667329694638369) with all of VAOS's updated designs and research.
