### ISSUE TITLE
CT: Remove Prod/Feature flag for "Cautionary information" section update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4531]
As a developer, I need to remove the feature flag so that the Veteran Programs section updates are available in the production environment.

## Assumptions:
1. This work has been reviewed by EDU and signed off on as of 01/03/2020.
2. The updated data has been loaded into GIDS as of 02/18/2020.

## Acceptance Criteria:
1. The work completed in #4277 is available in production. 

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
Pull Request: 

https://github.com/department-of-veterans-affairs/vets-website/pull/11721

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-20 at 8.05.51 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/edce5035-6dbf-4ae9-a0d9-693e8dbe328e)

**Comment by sonntag-adam** [comment]
in production build
![Screen Shot 2020-02-20 at 10.11.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/377a6fd2-2af3-47c8-bd94-8e32c410d5c9)

**Comment by sonntag-adam** [comment]
In production closing out story.
