### ISSUE TITLE
SOCKS access for [Michael Monty]

### ISSUE THREAD

**Issue by MichaelMontyAFS** [department-of-veterans-affairs/va.gov-team#45337]
### Your Name

Michael Monty

### Your Email

Michael.monty@va.gov

### Your Role and Team

Application Service Analyst

### Product Manager (PM) name and email

riley.ross@va.gov

### Product Owner (PO) name and email

riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCDQpWZKhj9tDaJCDQVKznGrDsM+M0821xcbTopLhTb8H1TbvBiMvCOZq6yUwbiDxiCK/qtgYPEkrk0wVmiEgmN8USFwruuXQOiweMLVIOscGzvqA6tlIR6CxT0TQSLDlB+GGb9OGRC4iTRpG8QPiPZFqb8ZN6GX282HUT2xtxIgXCF8H901F36DlPqREEPPrR0gGFfeqS3uQoefgK6CZygujKMl4S+u7EY3SQ7BrGoaG4H7h7AhlmqVV4x6nfcTh703Rc9E4lUTDQf4GZISpXXcch3bescgVtsCxXIBARQYde17FsZWINdU2rDHZoNP16Bshfzjs8NvFVnGoqbiJp3 rsa-key-20220805

### User must exist in a roster before SOCKS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by MichaelMontyAFS** [comment]
I am on the VFS Team Roster

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
