### ISSUE TITLE
SOCKS access for [Luke Guerry]

### ISSUE THREAD

**Issue by lukeguerry-va** [department-of-veterans-affairs/va.gov-team#45339]
### Your Name

Luke Guerry

### Your Email

luke.guerry@va.gov

### Your Role and Team

Service Management Deputy Lead

### Product Manager (PM) name and email

Riley Ross , riley.ross@va.gov

### Product Owner (PO) name and email

Riley Ross, riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnx04edOssiQQMiAWGIzi1I7aOi7P6tSQUgfINDgGrXKMFuv+VkT0ML2LMzkm2xKXOOyltP1fTjk3O2r6QAOb+AKI3+/urj+OmEfdLS3+eAYJt8wCQ8Nrlt8/ZjlbBxQXNl8QIL8aNUj0EzvHGdUQ9Ly8G7fReZaPNnSMa3U9SsGHLsTdDVReaOdx+ycEAh7UaxBrv7r4SmEPfclj5ftsYaNMT3ZM7XR/fQ4XRPV534X2rdziMDGx8NGZzytt6GNS+IS+syxo90Y7kInLZmn/kshti5nsoQAEu2c7UHetX4PRk1B7btas0MkrT9JeqPrihxVQZ6qjmRPY6qOoSswVEORq0Jq4LrRMpW9hz+7seU9v9DnEZTD5qeG+wVgRtZN+r2SVIusIiKLQOSxkEQMDLt9RigT/UweDSRg0oSIHbXamrIUnzibh0vvl0NbWQhJnYPrA5JWbuUrleuE3SdptLxESmXvPzE6QOBIPooQzGtI/Q94V0Fmp5JHwwT3URfqc= luke.guerry@AFSMWDX0P5VG1QA

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
