### ISSUE TITLE
[Design] Change Resolution for Sketch Files

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45338]
## Problem Statement
In order to resolve some issues with the way the Sketch files display, we need to change the resolution of the wireframes.

## Tasks
- Change the resolution on all Sketch files (either 360 or 375 - ask Kristen which)
- Identify and update the symbols that are affected 
- Coordinate with DS team on the symbol updates

**Comment by sarahknoppA6** [comment]
might make sense to wait on this until after travel pay is released

**Comment by loripusey** [comment]
not necessary, closing
