### ISSUE TITLE
Enable the ability to create columns based off of attributes

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#45334]
## Description
~Logs are currently coming into Datadog, but the lack readability. To remedy this, the `lograge` gem will be used will be used; that is we will log to a file with `lograge` and tail this file with our Datadog Agent turning our logs from this:~
find way to create columns based on attributes in dd logs
~Relevant articles:
https://docs.datadoghq.com/logs/log_collection/ruby/
https://www.datadoghq.com/blog/managing-rails-application-logs/
https://github.com/roidrage/lograge#installation~

## Acceptance Criteria 
~- [x] Add `lograge`~
~- [ ] Test if logs are coming in correctly~
- [x] find way to create columns based on attributes

**Comment by ianhundere** [comment]
I'm implementing it very barebones without `custom_options`:
`config/initializers/lograge.rb`

```
require "lograge"
Rails.application.configure do
  # Lograge config
  config.lograge.enabled = true
  config.lograge.keep_original_rails_log = true
  config.lograge.formatter = Lograge::Formatters::Json.new
  config.colorize_logging = false
  config.lograge.logger = ActiveSupport::Logger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"
end
```

**Comment by ianhundere** [comment]
chatted with Joe and he wants the ability to create columns based off of attributes which you can by:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/35044403-31d7-4023-b3fa-8de8bcfb6db1)
and then:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/b1c1bb7e-2658-49ce-baa4-653ec9eaf844)
and voila:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/ac6cd5c4-be7a-4840-9faa-b6727e1ac35d)

**Comment by joeniquette** [comment]
perfect! Ill go through the rest of my log boards, but the first one I was able to get everything I needed!!
