### ISSUE TITLE
Adding Bryan Paronto to DSVA Slack

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#45345]
# Description

Please add bryan@kindsys.us as a full member. He is a new Front End engineer on the Sitewide Crew, Public Websites team.

**Comment by jilladams** [comment]
Apologies - I initially included the wrong email here. Updated now.

**Comment by jilladams** [comment]
Also requested via SLack: https://dsva.slack.com/archives/C01S729LX6X/p1659990537699909

**Comment by LEHigley** [comment]
this invite went out, will resend
