### ISSUE TITLE
Review/add timeouts to Sidekiq jobs 

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45358]
– are jobs gracefully placed back into the queue? 
- Can we get network timeouts at the application level?

Documentation can be found [here](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2335047868/Sidekiq+Timeouts)

**Comment by RachalCassity** [comment]
The configuration for Sidekiq did not pose any problems. The worker thread count is acceptable given the memory usage.

There should not be any changes at this time. This issue was closed to move forward with the EKS migration.
