### ISSUE TITLE
Review timeouts on current service classes/clients in vets-api for external services

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45350]
Application layer health checks, if we had flame graphs this would be easier to identify

**Comment by jeremyhwu** [comment]
## BGS

- BGS Gem has a `read_timeout` of 120s and `open_timeout` of 10s and retries once on a timeout error:
[https://github.com/department-of-veterans-affairs/bgs-ext/blob/master/lib/bgs/base.rb#L154](https://github.com/department-of-veterans-affairs/bgs-ext/blob/master/lib/bgs/base.rb#L154)
- Somehow, grafana shows the max request time to be 60s, while the vets-api side on datadog shows requests upwards of 5 minutes
    - Grafana BGS: [https://grafana.vfs.va.gov/d/sZP0EYh7z/bgs?orgId=1&from=now-7d&to=now](https://grafana.vfs.va.gov/d/sZP0EYh7z/bgs?orgId=1&from=now-7d&to=now)
- [BGS FWD Proxy URL](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings/test.yml#L98)
- [BGS FWD Proxy Config (No timeout set, defaults to 1 min)](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-prod.yml#L203)

## EVSS

[Base timeout is 15 seconds](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/base_service.rb#L12)

**Some services override the base timeout:**

- [**Disability Compensation Form**](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L384-L386)
    - `timeout` is 55 seconds, `submit_timeout` is 355 seconds or ~6 minutes
- [**Letters**](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L387-L389)
    - 55 seconds
- [**PPIU / PCIU / PCIU Address**](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L390-L395)
    - 30 seconds
- **[ClaimsService](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/claims_service.rb#L9)**
    - 55 seconds

## Documents Service

- [480 seconds (runs in a sidekiq job)](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/documents_service.rb#L11)

**Comment by npeterson54** [comment]
Closing this with #46635
