### ISSUE TITLE
Review the timeouts at the fwdproxy layer

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45355]
Verify if the timeouts are being honored, where are they set

**Comment by LindseySaari** [comment]
Notes:
- The fwd proxy config sets some default timeouts here
- Each external service has the option to set a custom timeout as seen here
- This code then iterates over the forward proxy interfaces and sets the queue and server timeouts if defined

**Comment by npeterson54** [comment]
✅
