### ISSUE TITLE
Dig into AWS network layer, can we get a flame graph

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45357]
Between vets-api and postgres (and other network layers)

**Comment by npeterson54** [comment]
@zachclarity any updates on this?

**Comment by joeniquette** [comment]
flame graphs have been established however we determined that our version of DD doesnt allow us to see this level of detail. Great idea here but will need to wait for this feature to be enhanced by DD. Closing.
