### ISSUE TITLE
Adding new BAH team to DSVA Slack

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4535]
The following individuals need to be added to multiple slack channels as they begin research in support of claims: 
- Christopher.Gilbert@va.gov
- william.jackson2@va.gov
- michael.nuss@va.gov
- nathanael.burns@va.gov

What channel(s) do they need to be added to?
#vfs-platform-support
#vfs-all-team

**Comment by LEHigley** [comment]
done!
