### ISSUE TITLE
Perform load testing on staging or another stack

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45365]
# Description
`vets-api` latency issues have been addressed through various means at this point. Platform should conduct load testing probably targeting `staging` in order to verify that the various changes targeting this issue have been effective and have not caused other issues.

# Tasks

# Acceptance Criteria

**Comment by npeterson54** [comment]
@JoeTice tagging for visibility

**Comment by joeniquette** [comment]
not going to do this as part of this epic.
