### ISSUE TITLE
Investigate mobile interactions with vets-api

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45364]
## Description
Research how the VA mobile app controllers interact with vets-api to determine if there are ways to improve the latency cost. Currently the VA mobile app has custom routes for all of their services, often replicated and slightly changing each of the controller interactions in vets-api. For unknown reasons, potentially valid, these routes are drastically slower than their vets-api counter parts. This ticket is to research all of the routes to identify potential improvements. Any required improvements will be new tickets.

## Acceptance Criteria
Write up of each of the routes and their findings with recommendations.

## Random thoughts.
- Is this related to mobile controllers taking longer than their non-mobile counterpart? 
- Is this general discovery around how much mobile is being used?

**Comment by oseasmoran73** [comment]
>  Yes. these should be helpful: https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Services

> https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/Architecture/Auth%20Diagrams
[1:56](https://dsva.slack.com/archives/D0479606ZK8/p1666299399618599)
FYI, we’re planning on switching all our EVSS services to use Lighthouse but that probably won’t happen till next year

> here’s our endpoint docs though that doesn’t really describe which service is being used but just in case it’s helpful: https://department-of-veterans-affairs.github.io/va-mobile-app/api/

> We’re also in the process of switching from IAM user login authentication to SIS. from what I hear it’s better and faster but couldn’t tell you much more then that.

> Yeah in terms of system latency and up/down time, EVSS has been our biggest pain in the butt but we don’t have much information on the exact causes of the downtimes.

**Comment by rjohnson2011** [comment]
Looked into the mobile controllers and routing, which is handled in the `mobile` modules section of the `vets-api` app. 

Chatted with the va-mobile-app team. Was informed that mobile often uses caching, so initial requests may be slow but subsequent requests should be fast. Also, sometimes mobile has to gather data from multiple sources, where the web app aggregates those multiple sources on the front end. Per Kris,
```an interesting example would be appointments. we pre-cache appointments when the user logs in, so i would expect our appointments endpoints to be very fast. but we also have to aggregate data from three or four upstream services, so it would be very slow without the cache. the web does that aggregation on the front end and does not cache on the back end, so i’d expect their appointments to be slower overall```

Also, ```There are a handful of endpoints where we are more or less a pass through to existing services so those may be a good place to start. If we see a significantly higher latency on those compared to web then my guess would be it's our auth or serializer. We use the fastjson serializer.``` One of which is the `letters_controller` which would be a good place to compare mobile vs web.

Note: There are endpoint latency metrics in DataDog that have not been compared to the web - https://vagov.ddog-gov.com/dashboard/pzz-7x2-4cs/mobile-api-dashboard?from_ts=1666707903336&to_ts=1666711503336&live=true

**Comment by rjohnson2011** [comment]
Currently accessing individual duration metrics by controller action utilizing ATM resources queries in DataDog. Comparing the following controller actions by web vs mobile, compiled from a combination of longest total controller action times as well as mobile team input:

- PaymentHistoryController
- UsersController
- DisabilityRating
- LettersController
- AppointmentsController

Will report individual findings for the above. Looking into placing traces in more specific areas of expensive controller actions to look for fine-tuning optimizations.

**Comment by rjohnson2011** [comment]
I was able to gain a number of insights from investigating Datadog controller actions for the mobile vs web routing.

_Note: All data mentioned is queried from the previous 24 hours._

## UsersController

- Has a wide range of durations. 
- At its fastest, requests take a total of 6.78ms (see photo)
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/9f47a72a-247e-48c2-9097-e7604c7f64c3)
- At the worst they take upward of 1 minute, the product of four 15 s timeout loops.
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/ef347f0d-f10a-4c40-9658-74832a7a8728)

**Comment by rjohnson2011** [comment]
## LettersController

Has 3 separate actions that account for similar length of times. 

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/f97c4e5c-8779-4962-b90b-86bda123eb39)

**Comment by rjohnson2011** [comment]
Closing out this investigation ticket and opening another ticket dedicated to diving deeper into the most expensive latency issues.
