### ISSUE TITLE
SOCKS access for [Michael Monty]

### ISSUE THREAD

**Issue by MichaelMontyAFS** [department-of-veterans-affairs/va.gov-team#45367]
### Your Name

Michael Monty

### Your Email

Michael.monty@va.gov

### Your Role and Team

ASA

### Product Manager (PM) name and email

riley.ross@va.gov

### Product Owner (PO) name and email

riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDm4hpyTlDldUWafDQSzDHTRS9lGGDna8KmvxB15uP/D+n5Jpt5weQbm4RxcTqwWXdNDS0WoheXs1GJhR/JxqT96oUwm3eMsQGh0wsq9jIFtnk3TSFLFIVWKJuOjq7APRH8AcnuC+GhI/iGg8Tl2hrgQE3KwIWiG3tkj/decT4Dh04HY33BQiA4V/6LEgAi5WoJVfr/ZZuaELsRzobUe27/QspK6td3MlJ2fydnmKof0K2MehEA/rIvXhSUOfC0CsjrBE7jyLwcj/GKQUUZvMM/YKkZUtXsYMnfvz/kTTVr/pzqPXnPwxpSJN0mElqgCKhiTLf23QWJS3U5UKipBNX6QGRB7f900s+OalnFLL5Lb6BBiZGanjl4iODHT3aViDlqa9AFig23Ae6ejPghj7PzWrQ872CnxnQMOmvS4gsYtZ+Xgyqm3tZ/OXvXQpQHDwDOl3tGTMjqCnqkMWJwiCX0xu42oSNtJrFt0VYpWR7KToJG9o1JDeqpcTiGISmZR78= michael_monty@AFSWWRJY2UG1CH

### User must exist in a roster before SOCKS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [X] Comment in this issue saying which roster the user is listed in.

**Comment by MichaelMontyAFS** [comment]
I am on the VFS Roster

**Comment by kylesoskin** [comment]
Hi @MichaelMontyAFS , your previous socks request (https://github.com/department-of-veterans-affairs/va.gov-team/issues/45337) was approved and provisioned earlier. Are you having some issues that required a second request?

**Comment by MichaelMontyAFS** [comment]
My previous request used a SSH key that I made in error using a different processes.  This request uses a SSH Key following the steps outlined in your guide.

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
