### ISSUE TITLE
VA API Domain Change Impact Research

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#45375]
# Description

The following needs research to see the impact to SRE related support playbooks and documentation.

Vets-api and Lighthouse currently share the same endpoint, [api.va.gov](https://www.google.com/url?q=http://api.va.gov&sa=D&source=calendar&ust=1660161960481966&usg=AOvVaw3ScwHeAg8kjKM_nt42K0bE). Eventually Lighthouse will assume control of [api.va.gov](https://www.google.com/url?q=http://api.va.gov&sa=D&source=calendar&ust=1660161960481966&usg=AOvVaw3ScwHeAg8kjKM_nt42K0bE) and vets-api will need to transition to a new subdomain, [platform-api.va.gov](https://www.google.com/url?q=http://platform-api.va.gov&sa=D&source=calendar&ust=1660161960481966&usg=AOvVaw1Qlj3lDkM9jCG1OoRu_X80).

Task

- [ ] Research the impact to SRE support playbooks and documentation
- [ ] Create issues to update based on the research

NOTE: use this as a reference the [VA API Domain change Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44538)

**Comment by little-oddball** [comment]
Determined OBE
