### ISSUE TITLE
Staging Review [Auth Exp My VA - My VA Redirect ]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45379]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] **Staging URL:** the redirect to My VA occurs immediately post login from the VA.gov homepage so there isn't a single staging url. The path is log into staging.va.gov > be redirected to staging.va.gov/my-va
- [ ] **Staging test-user information:** _all_ staging users have the redirect enabled

Note: there is a known issue with a race condition that prevents the redirect from working at times. When this happens the user does not know there's a problem, there's no error, they simply land on the va.gov homepage like they did prior to our redirect, instead of landing on My VA. The race condition is associated with the feature flag and once removed shouldn't be an issue for the redirect.

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-redirect#my-va-redirect-initiative-brief) 
 
  

- [ ] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/launch-materials/my-va-redirect-release-plan.md) 

 

### Content artifacts 

- [ ] Your product’s content source of truth - _not applicable_
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable) - _not applicable_

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product [test cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=5770) in TestRail (additional [test case](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-my-va-redirect.md) documentation)
- [ ] [Test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/3494) with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/358) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/359) 

### Accessibility artifacts 

- [ ] [Completed foundational accessibility tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/launch-materials/my-va-redirect-a11y-staging-review-prep.md) - many are not applicable to this work given the nature of the initiative and extremely narrow scope, but for those that were applicable, no issues were found.

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by ajakabcin** [comment]
Hi @shiragoodman just letting you know I'm still adding artifacts to this so it's not quite ready yet. I'll post in slack when it is. Thanks!

**Comment by chaseakirby** [comment]
@ajakabcin Thanks for letting us know and planning to post in slack AJ! Shira is out of office the next two weeks, I'll see the post when it's tagged for the collaboration cycle.

**Comment by allison0034** [comment]
@ajakabcin this is confirmed for August 19th at 2pm ET

**Comment by ajakabcin** [comment]
Requested staging review for next Friday, 8/19, at 2pm. A11y artifacts will be added next week. Thank you!

**Comment by ddzz** [comment]
No QA feedback, looks good!

**Comment by allison0034** [comment]
[Zoom recording](https://oddball-io.zoom.us/rec/share/GNqWAzIlwFtORjvgKEuWEi_yO_8b7h6N3EXYnI9RTgXGadn-XyM9I6VknORcMlxy.0XsxODVrwZ8jQ8B_)
Passcode: @IQTk5wn

**Comment by ajakabcin** [comment]
Since there was no feedback I'm going to close this - thanks all!

**Comment by allison0034** [comment]
[Zoom link](https://oddball-io.zoom.us/rec/share/Ahd2EvpAEZeeTu8HRkjugYkoQsoUrYO7FIHUAJev_3wCwVpZoey3swPgyo3pYAwi.H7L_EcINo7wPtZTf?startTime=1660932260000)
Passcode: @IQTk5wn
