### ISSUE TITLE
[Spike] Update the domain to platform.api-va.gov 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#45376]
## Background
The Cloud Isolation Team will be updating the vets-api and Lighthouse API endpoints by creating routes necessary for each to have its own unique endpoint.  

The current domains: 
- api-va.gov
- dev-api.va.gov
- staging-api.va.gov
- sandbox-api.va.gov

The following domains will be changed to: 
- platform.api-va.gov
- dev-platform-api.va.gov
- staging-platform-api.va.gov
- sandbox-platform-api.va.gov

### Goal
To understand how much work is needed to support the initiative. 

### Requirements to Consider
- [CIT Product Outline ](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525/Product+Outline)
- [Cloud Isolation Epic](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44538)

---

## Tasks
- Answer the following questions:
  - Q1: List out all the test files that display the `api.va.gov ` and requires an update 
  - Q2: List out all the test files that display the` staging.va.gov` and requires an update
  - Q3: Check if we need to update any code in `vets-wesbite `or `vets-api `
  - Q4: Check how many tests in vet-api that we need to update

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by ajmagdub** [comment]
Currently, the Vets API Rspec tests match VCR Cassettes on METHOD and URI. The planned changes to the Vets API domain will break the tests. Changing the VCR Cassette match to METHOD and PATH will allow the tests to pass with regardless of domain naming. See #46292.

Vets API Rspec tests that need to be updated:

- modules/vaos/spec/controllers/v1/base_controller_spec.rb
- modules/vaos/spec/factories/appointment_forms.rb
- modules/vaos/spec/factories/appointment_request_forms.rb
- modules/vaos/spec/factories/cc_appointment_request_forms.rb
- modules/vaos/spec/factories/v2/appointment_forms.rb
- modules/vaos/spec/factories/vaos_users.rb
- modules/vaos/spec/models/cancel_form_spec.rb
- modules/vaos/spec/models/cc_appointment_request_form_spec.rb
- modules/vaos/spec/models/message_form_spec.rb
- modules/vaos/spec/models/v2/appointment_form_spec.rb
- modules/vaos/spec/request/apidocs_request_spec.rb
- modules/vaos/spec/request/appointment_requests_request_spec.rb
- modules/vaos/spec/request/appointments_request_spec.rb
- modules/vaos/spec/request/cc_eligibility_request_spec.rb
- modules/vaos/spec/request/cc_supported_sites_request_spec.rb
- modules/vaos/spec/request/direct_booking_eligiblity_criteria_request_spec.rb
- modules/vaos/spec/request/facilities_request_spec.rb
- modules/vaos/spec/request/messages_request_spec.rb
- modules/vaos/spec/request/preferences_request_spec.rb
- modules/vaos/spec/request/request_eligibility_criteria_request_spec.rb
- modules/vaos/spec/request/systems_request_spec.rb
- modules/vaos/spec/request/v1/appointments_request_spec.rb
- modules/vaos/spec/request/v1/healthcare_service_request_spec.rb
- modules/vaos/spec/request/v1/locations_request_spec.rb
- modules/vaos/spec/request/v1/organization_request_spec.rb
- modules/vaos/spec/request/v1/patient_request_spec.rb
- modules/vaos/spec/request/v1/slot_request_spec.rb
- modules/vaos/spec/request/v2/apidocs_request_spec.rb
- modules/vaos/spec/request/v2/appointments_request_spec.rb
- modules/vaos/spec/request/v2/available_slots_request_spec.rb
- modules/vaos/spec/request/v2/clinics_request_spec.rb
- modules/vaos/spec/request/v2/facilities_request_spec.rb
- modules/vaos/spec/request/v2/mobile_ppms_request_spec.rb
- modules/vaos/spec/request/v2/patients_request_spec.rb
- modules/vaos/spec/request/v2/scheduling_configurations_request_spec.rb
- modules/vaos/spec/routing/v1/fhir_routing_spec.rb
- modules/vaos/spec/routing/vaos_routing_spec.rb
- modules/vaos/spec/serializers/v1/operation_outcome_serializer_spec.rb
- modules/vaos/spec/services/appointment_requests_service_spec.rb
- modules/vaos/spec/services/appointment_service_spec.rb
- modules/vaos/spec/services/cc_eligibility_service_spec.rb
- modules/vaos/spec/services/cc_supported_sites_service_spec.rb
- modules/vaos/spec/services/configuration_spec.rb
- modules/vaos/spec/services/jwt_wrapper_spec.rb
- modules/vaos/spec/services/messages_service_spec.rb
- modules/vaos/spec/services/middleware/vaos_errors_spec.rb
- modules/vaos/spec/services/middleware/vaos_logging_integration_spec.rb
- modules/vaos/spec/services/middleware/vaos_logging_spec.rb
- modules/vaos/spec/services/preferences_service_spec.rb
- modules/vaos/spec/services/session_service_spec.rb
- modules/vaos/spec/services/systems_service_spec.rb
- modules/vaos/spec/services/user_service_spec.rb
- modules/vaos/spec/services/v1/fhir_configuration_spec.rb
- modules/vaos/spec/services/v1/fhir_service_spec.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- modules/vaos/spec/services/v2/mobile_facility_service_spec.rb
- modules/vaos/spec/services/v2/mobile_ppms_service_spec.rb
- modules/vaos/spec/services/v2/patients_service_spec.rb
- modules/vaos/spec/services/v2/systems_service_spec.rb
- modules/vaos/spec/support/fixture_helper.rb
- modules/vaos/spec/workers/extend_session_job_spec.rb

**Comment by ldelacosta** [comment]
There is no FE development work (only BE). Closing out the spike ticket. 

cc: @simiadebowale
