### ISSUE TITLE
Request design review for Caregiver Form 10-10CG 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#4538]
## Instructions

1. Click or press the gear icon next to the "Labels" heading on the right. Search for your team in the labels list. If your team is not listed in the Labels menu, please leave a comment after you have created this issue. The Product Support team will create a new label for your team.
2. Text inside `<-- comment -->` blocks will not appear in your issue ticket. These comments offer guidance on what information you should provide for each section.

### For reference

* **VSP** - [VSP Design Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md)

* **VSA** - [VSA Design Review Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/review-process.md#design-review)

* **Accessibility** - [Accessibility Best Practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md) | [VSA A11y Review Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/review-process.md)

* **Content** - [VSP Content Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/content-review-process.md)

* **IA** - [VSP IA Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/working-with-ia.md)

* **Research** - [VSP Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-process.md)

## Product Name

Caregiver (Form 10-10CG)
## Checkpoint Stage

[ ] **Design Intent** (for early discussions about needs, priorities, concepts, research planning, and direction)

[ x] **Pre-usability testing Review** (for prototype and testing validation of best practices, alignment with va design system, and inclusive research best practices)

[ ] **Design Review** (for design work validation of best practices and alignment with the va design system)

### Where in the process is this? 

[ ] Initial concept

[ x] Initial mockup

[ ] Final mockup

## Design links or mockups

https://vsateams.invisionapp.com/share/QVVDA4JDCTA#/399343663_Apply_For_Caregiver
## Point of contact

Jonathan Nelson
## Next steps

This issue *automagically* creates a Zenhub ticket (assigned to Emily, Crystabel, and Jennifer (VSA Accessibility Specialist), and VSP will schedule a design review.

**Comment by jenstrickland** [comment]
_Accessibility / previous discovery team notes_

- definitions - rather than modals; use tooltip (unless this ends up only being available for acronyms)

- in this flow, each individual has to complete their info in a chain, or together. It's not likely the Vets and Caregivers will do this together. 

- what is the envisioned flow for this form?

- Suggest separating each person and having their certification of truth.

- possibly explore attaching to a Veteran's account - in order to save in progress, collect the different components of the application? A way of having save-in-progress functionality, despite not having individual distinct accounts.

- "Learn more" needs more than just "learn more" -- link should stand on its own. See Peggy Gannon's comments on this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1817

- Accordions - see design.va.gov for spacing

**Comment by 1Copenut** [comment]
_Accessibility / previous discovery team notes_

**Page 1 of 11**
* The first line of text after the `<h1>` and before the introductory paragraph has a low visual hierarchy. I get the sense this information is important. Is there a way it could be rolled into the introductory paragraph or a sub-heading display?
* Are there ways to revise the modal links to use our [Additional Info](https://design.va.gov/components/additional-info) component?

**Page 7 of 11**
* We will want to manage focus carefully when users press the `Add Another Secondary Caregiver` button. Ideally, pressing that button sets focus on a heading or some indication this is a second(?) secondary care provider.

**Comment by jenstrickland** [comment]
Re-opened issue, set assignees to designer, PM, and myself, to use as a working reference. Once @jonathanjnelson  and @ala-yna  feel they have reviewed feedback, they may close this issue, with a comment regarding decisions made.

**Comment by jenstrickland** [comment]
@ala-yna Do you think this ticket can be closed now?
