### ISSUE TITLE
[BUG] Users can submit an uploaded "other" document without a document description

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#45409]
## What happened?
I was able to submit an "other" type of document without a document description despite it being required.

https://user-images.githubusercontent.com/14154792/183465664-0e318def-89b9-490e-87f7-3fef205e24d3.mp4

## Specs:
- Device: Windows
- Browser: Edge
- Test User: 228

## Steps to Reproduce
- URL: [Staging link](https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction)
- Test User _(if applicable)_: 228

## Desired behavior
- Error message should appear to prevent user from uploading an other document without a description OR
- Description should not be required 

## Acceptance Criteria
- [ ] Error message appears when user attempts to submit an other file without a "document description" OR
- [ ] Description is not required for other documents

**Comment by scottymeyers** [comment]
Okay, so the steps to reproduce this are as follows:

1. Go through the form until you land on the **Step 5 of 6: Your supporting documents** screen.
2. Click on the **Upload document** button and select a document.
3. For the **Select a document to upload** dropdown, select "Other".
4. Click on the **Upload another document** button and select a document.
5. For the **Select a document to upload** dropdown, select anything besides "Other".
6. Click on the **Continue >>** button.

**Comment by joshkimux** [comment]
<img width="586" alt="Screen Shot 2022-08-22 at 1 56 04 PM" src="https://user-images.githubusercontent.com/14154792/185987454-fb7996ff-ebb3-4870-bae0-271e419f3bb4.png">
Confirmed this has been fixed, @Mottie you're a rockstar as always 🚀

**Comment by Mottie** [comment]
You can test this now in staging :D

**Comment by joshkimux** [comment]
<img width="660" alt="Screen Shot 2022-08-25 at 12 50 19 PM" src="https://user-images.githubusercontent.com/14154792/186724000-ddd1cc48-dd3c-4bbb-a97e-0c082d57ce01.png">

Confirming this bug is fixed 😄
