### ISSUE TITLE
[Story] Institution Caution Flag

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#45408]
## Issue Description
When GIDs is updated the historical but "fixed" cautionary flags are not cleared from the database. This causes caution flags for school that no longer have an issue. It was determined that the process uses the data in the spreadsheet as the source which indicates if a flag has been deleted from the spreadsheet it will not be processed in the date base. 

---
## Tasks
- [ ] _At the beginning of the institution builder, for each institution reset the below five fields to the 
default value._ 

Reset fields to default state:
**'accredited'
'accreditation_type'
'accreditation_status'
'caution_flag'
'caution_flag_reason'**

## Acceptance Criteria
- [ ] _Create a cautionary flag for an institution to force a cautionary flag. Upload the file then the institution  builder to confirm that the institution has a caution flag. Remove caution flag, run the file and institution builder to confirm the institution does not have a caution flag._

**Comment by MitchLivingstone** [comment]
Please run any plausible tests in staging to determine if the update fixed the underlining issues.

**Comment by AdamFreemer** [comment]
@MitchLivingstone  Code was deployed to Staging that will reset caution flags at the beginning of every institution builder run:

```
'accredited'
'accreditation_type'
'accreditation_status'
'caution_flag'
'caution_flag_reason'
```

To UAT / User Acceptance Test this:

1) User must upload a standard file used in normal process with an Institution that is now "unflagged", where previously "flagged". It's important this is done by User not the Development group to rule out nuances with operating system, etc. 

2) Builder process will be triggered after confirmation of file upload with Institution test flag change.

3) Once builder process completes, User can then confirm if change is reflected on Staging.

**Comment by MitchLivingstone** [comment]
Email sent to Brian Grubb to run UAT in staging to determine if the updated code has fixed the caution flag problem.

**Comment by MitchLivingstone** [comment]
Brian has uploaded a new files in staging to force a caution flag. When the builder is ran in staging it should detect the flags shouldn't be there and removed. Please test to determine if the flags are removed. @hallihocine

**Comment by MitchLivingstone** [comment]
Meeting with Brian at 1pm to determine how the CSV files work with the process. 08/22/2022

**Comment by MitchLivingstone** [comment]
Moved to blocked until updated meetings with Brian Grubb and his extended team meets with AFS to determine the process flow for the caution flags. 08/29/2022

**Comment by MitchLivingstone** [comment]
Problem resolved per Brian Grubb. Complete and Closed 09/19/2022.
