### ISSUE TITLE
FE | Auth Profile | Contact Information | Restrict Address Character Set

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45400]
## Background

VA Profile has requested that we restrict the characters we accept for addresses on the Profile's contact information page.  See this [original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44816) for more details.

#### BE Tasks
- [x] Add validation to limit address character set to those defined in [#44816](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44816).
- [x] Here are the [desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/zx4KgMl) and [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/ygvQP7o) mockups with the approved content. 
- [x] The user messaging will show in-line immediately after a user moves focus off one of the address fields
- [x] Update docs to reflect this validation rule.
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## Acceptance Criteria
- [x] Validation is working in staging environment.
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production using feature flag

**Comment by SKasimow** [comment]
@adamwhitlock1 - I used Tom's estimate of 2 pts for your ticket also - so feel free to update if needed.

**Comment by SKasimow** [comment]
@Samara-Strauss - was reviewing this ticket with Adam and wanted to see if you had any concerns with the following approach:

1. The error message will show in-line immediately after a user moves focus off one of the address fields. This includes:
     - address line 1, 2, and 3
     - city
     - state/province/region (for international addresses)
     - international postal code

2. There is a shared schema for the mailing and home address so the new validation will happen for both address types
    
cc\ @adamwhitlock1

**Comment by Samara-Strauss** [comment]
Sounds good to me!

**Comment by SKasimow** [comment]
Thank you!

**Comment by adamwhitlock1** [comment]
This is live in staging to validate now. you can use a non-ascii character link ¢ or by copying any non ascii characters from here to test: https://terpconnect.umd.edu/~zben/Web/CharSet/htmlchars.html

**Comment by Samara-Strauss** [comment]
Tested with user 382 (new user I just created for direct deposit) for both the home and mailing address form. Works great!

**Comment by SKasimow** [comment]
Closing as completed and validated.
