### ISSUE TITLE
GIDS Dashboard - heading level is skipped

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4541]
On the dashboard page of GIDS, The main heading is heading level one and the following three sections are heading level three. Heading levels should not be skipped. Changing the H3s to H2s would comply with best practices.

The current state of all headings on this page:
```
<h1>GI Bill Comparison Tool Dashboard</h1>
   <h3>Latest Production Version</h3>
   <h3>Latest Preview Version Generate New Preview Versio...</h3>
   <h3>Latest Uploads View Upload History...</h3>
```

This defect can be reproduced using any of the following tools:
- [Axe](https://www.deque.com/axe/)
- [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html)
- [Wave](https://wave.webaim.org/)

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `bah-label-fix`

PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/541

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
In staging, closing bug.
