### ISSUE TITLE
New Users GitHub Request

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4542]
The following individuals need to be added to the BAH-526 team with read and write access (va.gov-team repo). 
GH username: cgilbert1
VA email: Christopher.Gilbert@va.gov

GH Username: wjackson2
VA Email: william.jackson2@va.gov

GH username: randomUser132 
VA Email: nathanael.burns@va.gov

**Comment by bobrox1973** [comment]
Please see my email.

**Comment by desireeturner** [comment]
@bobrox1973 regarding your email, it is not critical that they be added to the BAH-526 team, just that they have read/write access to va.gov-team. If there is another group they can be added too or if access can be added ad-hoc that is fine. Sorry for the confusion. Let me know if there are further questions.

**Comment by bobrox1973** [comment]
All users have been invited to the vets.gov-write team that has write access to the repository requested.
