### ISSUE TITLE
Create Airtable for data collection and referencing

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#45429]
## Issue Description
Airtable needs to be created to allow for capture of the various pieces of initial data that we intend to capture for the Mapping.

## Tasks
- [x] Draft Airtable instance with the information cells described in [workshop](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1659975526362/9bd610b697949280ce76d79e5f8015f0f53c5ee3?sender=u4397b715dc3690a417b71483).

## Acceptance Criteria
- [x] Airtable is drafted

**Comment by twoangstroms** [comment]
https://airtable.com/invite/l?inviteId=invfUAJRSzepJSrh3&inviteToken=063e074b5c5504bc473edff46b968fb51c84c81a93b63eaa3a7186cbd2dce8f4&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts

**Comment by twoangstroms** [comment]
Team -- Any issues you see in using this as a resource? https://vfs.atlassian.net/wiki/spaces/PWD/pages/2294120662/VFS+Product+Directory

**Comment by steel36** [comment]
@twoangstroms Right, that was the intention of this ticket:  https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/department-of-veterans-affairs/va.gov-team/44352

**Comment by twoangstroms** [comment]
Resource: https://docs.google.com/drawings/d/1N7tW2wTNqViooXE6ts8QujG36oyAg4mqu1zyeQ67DiY/edit?pli=1
