### ISSUE TITLE
:orange_circle: Product Definitions 

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#45437]
What
Provide a single source of truth for OCTO product definitions.

Why
Less energy is wasted on creating/maintaining documentation that otherwise may not need to be if there is standardization. It's not a good use of time to have teams creating product outlines for items we consider to be features and/or initiatives. If we can put some framework together, that would keep individuals focused on the work and any necessary documentation.    

Things to do

- [x] Meet with Chris Johnston to discuss definitions
- [x] Rework any feedback that comes out of that conversation
- [x] Determine communication plan
- [x] Create doc in GitHub

**Comment by dmkosko** [comment]
8/25 - Product definitions are being vetted as we go through the product list exercise.

**Comment by MickinSahni** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/operations/product/terms%20and%20definitions.md

**Comment by leahbannon2** [comment]
There are 2 issues we need to resolve on this:

1. The "Operations" folder is not a good name for our folder. We should name and organize docs based on how they will be used and searched for, not the team creating them. Based on several conversations I've had with different folks in OCTO, I think our best approach might be renaming the "Operations" folder to be the "OCTO" folder. Then, clarifying in its description, that all OCTO-wide guidance is going in there. (And possibly noting that va.gov-only guidance is on the platform documentation site and gov-only docs are in OCTOPUS sharepoint site.)
2. This comms plan doesn't plan for how we'll ensure that the doc is used in the future. One approach could be to include a link to it in the Product Directory page and github issue for updates.

**Comment by lkoenigsberg** [comment]
Updates

1. The operations folder has been renamed [OCTO](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/octo)
2. Need to still finalize what the initial comms plan is going to be for both initial launch and continued use.
3. Update the readme file in this GH repo to include links to product outline and initiative brief.
