### ISSUE TITLE
SOCKS access for Susanna Kline

### ISSUE THREAD

**Issue by sdk-irl** [department-of-veterans-affairs/va.gov-team#45439]
### Your Name

Susanna Kline

### Your Email

susanna.kline@adhocteam.us

### Your Role and Team

Tech Writer on Platform Console UI

### Product Manager (PM) name and email

Lee Helmer lee.helmer@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen - michael.chelen@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWTMt30VLz8xZ+OwP4oj/HtNqxmtnpmxp8lf/+YfcXbj1XIrSNfjKeDQwbtj91JTGlXXncKnuw//C8GOPiA5183guBVOMHZ/9X/HXMnFPQWNs9QEt65/aMZhmGQHmhhWQnGqXKvCMfO1u3dtjVGjVTOn4YurpBpVKH+zB09hkAZKiIbEqQPwTpp4l1a76sZxtkjzA4V/w/1u9zYcDnmINJR8laTP6HWPD/J9qdgZk6epzR0fvnfqtp4fr4GmqwSQE4+SRNFIwMNUkOq0k4U9bpFZ6jOcWtIP5pBn1RaRcZHrLIWwyacBr02hU6g1A1MSglbYA7l/w0aCHluUF1jcyuwgpSh2dDBJfVsn6F44xnaw9B3qbLRhoAqkHnfREGLs5jzwHDUwMbcyTe7Kv38spkWFcCcfHHM5fhqxtUW2s6xinUam7Ea4xXp5uzMZ6iIX0zNYhmHPTumeQcc6h32E6UkqaYe4b5UwkQ31VuzLw/ptV1Z6+dfrdKI8Af6wqBT60= susannakline@sdk-personal.overcautio.us

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kylesoskin** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
