### ISSUE TITLE
Adding Maddie Fritz to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#45440]
Good afternoon,

I am requesting, Maddie Fritz, be added to DSVA Slack workspace, as a Multi-Channel user for the below channels. 

Email: maddie.fritz@adhocteam.us
Channels:  #feedback-backchannel, #design, #research-ops, #vsp-support, #inclusive-research, #vsp-research, #vfs-test-accounts

Thank you!

**Comment by LEHigley** [comment]
maddie fritz is already showing as a full member in this workspace
