### ISSUE TITLE
Adding Casey Williams to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#45441]
Good afternoon,

I am requesting Casey Williams be added to DSVA Slack workspace, as a Multi-Channel user for the below Channels.

Emails: casey.williams@adhocteam.us
Channels: 
Team-of-teams-slide-collection 
Va-notify-public 
Vgs-platform-support 
Va-claims-appeals 
Vsa-benefits-nod 
Appeals-api

Thank you!

**Comment by LEHigley** [comment]
assuming vgs is vfs; couldn't find va-claims-appeals
