### ISSUE TITLE
Triage Vets- API Latency issue Ongoing.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#45442]
Info moved to [sensitive repo. ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/542)

**Comment by zachclarity** [comment]
Note this is recurring and we need to determine the root cause.

**Comment by zachclarity** [comment]
The status:

Aug 9th
2:21 PM EST - [Support request ](https://dsva.slack.com/archives/CBU0KDSB1/p1659982890226959)opened with issue of slowness.
3:00 PM EST - Deploy went out which will temporarily fix issue.
3:27 PM EST - Console Services team is still working on root cause and a true fix.
3:58 PM EST - Still latency for some calls
4:13 PM EST - [AWS ASG Sidekiq Workers Increased to 25 instances.](https://dsva.slack.com/archives/CBU0KDSB1/p1660076090451919)
4:20 PM EST - external services being BGS and EVSS are down or slow for this instance
4:35 PM EST - AWS ASG was increased for Sidekiq Queue issue
8:15 PM EST - The latency issue was stable but higher than normal.
Aug 10th
8:50 AM EST - Issue ongoing and root cause search continues. The console services team notified of issue with higher than normal latency. This may be acceptable, but may go up soon.
9:00 AM EST - Also the Platform Team has a couple avenues they are actively working. One is related to BGS and some spikes that are being noticed in DD that look to relate to some of the problem(s) being seen/reported.
10:25 AM EST - The issue seem to correct and the latency went down to acceptable levels.

11:32 AM EST - the latency seems to be going up.

**Comment by zachclarity** [comment]
# Current Hourly Status:
- State of Service:  It is stable but latency seems to be heading higher.
- The current state is stable and watching for latency increases.
- New findings:  TBD .  The team is actively working and I plan to get an update soon.
- Theory eliminations: Nothing has been eliminated yet.  
- Anticipated Next Steps: TBD.  The team is actively working and I plan to get an update soon.
- Next Update at 1pm EST

**Comment by mchelen-gov** [comment]
Moving to -sensitive as it pertains to ongoing incident.

**Comment by zachclarity** [comment]
will do.

**Comment by zachclarity** [comment]
[moved to Sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/542)

**Comment by mchelen-gov** [comment]
fysa there is a gitthub "transfer issue" feature as well https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
