### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/va.gov-team#45454]
### Your Name

David Aslan French

### Your Email

aslan.french@civicactions.com

### Your Role and Team

UX Designer

### Product Manager (PM) name and email

David Shannon david.shannon@agile6.com

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJ6m/dzJZvnsWSt4pxY+qxL4LB8PqUtOujZP57J2dn7YQ6ne5J9geKBb412/g5hKHxsQtYGLGBaaGU6sp2IgIOqxD6tOgILfxQpcs0NPz+RF8eLjMzZ6JBjXwnrbaNvMWVPEmCABAOZb5SHWjLo3YNvgfE5FHnQlbXH3dDn5uA0rXgGTmIqZt4fQYLTBJG2oGB/O0GXpox5FLceA3HgHEUks9BxSMbJWonCXHbB1FtK34X4EH/37AJPax8rw98ZmJe/FRWYDbKUZnSudPU/mqmx8oyK+0vR1i+XGngWT01S+5SWuL3cd7cV3L2yu5+cLVVqFfRCMp5BBLpCZCi8NFD66qIsljKORAP7myotmBRZzc77tcvAcfhuKFs9q0JZDs6b92e15GYNsrhf1jdU3J17kwBO4Em26ZujrKR1Da/u5L/MnrS5K2tY00bt+sImIK40S2Dwcn9YZNOqbdx0rtyVbgbsOESbDri071S5DB0ks17NhxOalrjkYUw3COVq7E= aslan@Aslans-MBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
