### ISSUE TITLE
[My VA Redirect] PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45450]
\[**Product Managers**: Open this ticket **at least 2 Sprints (4 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [PTEMS-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by PTEMS-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: [My VA redirect initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-redirect#my-va-redirect-initiative-brief)
- Product/Feature Epic: #41223
- Product/Feature Copy deck(s): not applicable - there are no design elements to this initiative
- Product/Feature Design prototypes: not applicable - there are no design elements to this initiative

## Product-team SMEs

\[For any Practice-areas worked by 2+ team-member, clarify who specifically is assigned to this initiative/project.  Leave blank for other areas.\]

Design/Research: @andaleliz ran UAT/research for this initiative, there are no design elements to this initiative
Content/IA: Mikki Northuis (before she changed roles)
Front-end: @AGarcia-Clarity (Identity), @tmitchellgcio (Auth Exp My VA)
Back-end: @joeniquette (Identity)
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-users must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: [My VA redirect test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-my-va-redirect.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Added product-specific label (if any)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod environment].
- [x] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

**Comment by tlei123** [comment]
@ajakabcin , all QA test-runs now completed.

**100% Passed** -- No defects logged.

TestRail QA-artifact links [for our Staging Review ticket]:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3494)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=5770)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/358)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/359)

FYI, @pjhill @ddzz , reports above generated in mere _seconds_!  :D  I'm gonna re-generate Debt-Res's Combined Debt Portal Coverage for References report tomorrow and see what happens with that one.  :::fingers crossed:::

cc @Samara-Strauss @ericasauv09

**Comment by ajakabcin** [comment]
Thank you again so much @tlei123 for expediting QA on this feature - I think we're good to close now.

**Comment by tlei123** [comment]
You're welcome, @ajakabcin !  :)
