### ISSUE TITLE
Create Research Plan for "686c Submission Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4546]
## Story
As a design researcher, I want to create a consistent plan that encompasses the guidance of approved methods and all the components for the item I am researching.

## Goal
To validate my hypothesis and ensure that I am applying user centered designs before engineers start to build. 

## Considerations 
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)

## Task
- Document a research plan to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery-research-plan.md)):
  - Research method (moderated user interviews)
  - Participants & Recruitment
  - Timeframe
  - Team Availability
  - Roles (include emails)
  - Seek review before implementation
  
## Acceptance Criteria
- [ ] Research Plan has been reviewed by [Lauren Alexanderson in Recruiting](https://dsva.slack.com/team/U772MC9BQ) ([email](mailto:lauren.alexanderson@va.gov)) and Shawna(?)
- [ ] Notify Yana Roy

**Comment by sporeboy** [comment]
Work-in-progress on guiding questions for usability study: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-research-plan.md

**Comment by sporeboy** [comment]
Test plan revised per Shawna's feedback. Dates entered. Key changes:
 - Sessions expanded to 45 minutes
 - Pilot (dry run) set for 2/21
 - Sessions to start 2/24
