### ISSUE TITLE
Implement Google Analytics for VA Forms Search Page Body Content Links

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4547]
### **Why:**
We'll need Google Analytics added into our **Search Page Body Content Links** to capture key events, so that we know how our widget is being used. We may also want to record clicks to download forms, so that we know what forms are most popular.  We also need Google Analytics added to the links on the page content (outside of the REACT widget).

[Analytics ticket for VA Forms Search Page Widget ](url)
 
**Needs to be updated**

**Comment by ncksllvn** [comment]
Is this different from https://github.com/department-of-veterans-affairs/va.gov-team/issues/3606?

**Comment by Karak888** [comment]
Yes- just clarifying that this work is for VA forms search as opposed to Master Detail Pages for campaign landing pages (outside of REACT)-

**Comment by ncksllvn** [comment]
Implemented per https://github.com/department-of-veterans-affairs/va.gov-team/issues/4458

**Comment by joanneesteban** [comment]
@Karak888 @ncksllvn could we consolidate and/or close this? (per #4458 )

**Comment by joanneesteban** [comment]
@Karak888 @ncksllvn hi again! Wanted to check in on this to see if this can be closed?

**Comment by ncksllvn** [comment]
Hey @joanneesteban yes it can be closed!

**Comment by joanneesteban** [comment]
Thanks!, @ncksllvn! Closing this issue.
