### ISSUE TITLE
Add user attribute checks to SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45513]
To-do:
- [ ] If a user has multiple secids, we should block login to VA.gov
- [x] global deny flag detected, we should block login to VA.gov

Complete and tested:
- Multiple SSN check - No action required, MPI has controls to prevent this
- multiple BIRLS - No action required, we allow multiple
- multiple EDIPI - Confirmed working as expected
- multiple ICN - Confirmed working as expected
- missing CSPID - confirmed an add to MPI worked

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/10464

**Comment by joeniquette** [comment]
No action required on double secids as this is something that wouldnt negatively impact current services and only matters to eauth.
