### ISSUE TITLE
[08/19/22] VEText PCI List Audit

### ISSUE THREAD

**Issue by djfredvs** [department-of-veterans-affairs/va.gov-team#45521]
## Description
There is a large number of users with the PCI link into 0 day 3rd message templates and that is causing issues regarding PCI. The solution is to remove the link from all 0 day templates.
---

## Acceptance Criteria
- [ ] Remove links from associated templates
- [ ] Report to team when completed (post in group slack channel)
---

**Comment by lindsay-insco** [comment]
~35-40% complete
