### ISSUE TITLE
Analytics Implementation for Form Detail Landing Pages

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4552]
<details> 
<summary> Original GH Issue Content</summary>
### **Purpose:**
The primary purpose of this MVP is to increase conversions to digital tools, so we definitely want to track clicks not just to forms but to our digital products via page links. Some of the form detail landing pages will also have CTA buttons to the online tool, and we'll definitely want to track clicks to the tools when applicable. [EDIT: JL]

### **Request:** 
Will need to determine and implement Google Analytics for the form 'master detail' landing pages. 

~**Please Note:**  this piece is not completely ready yet as @lwalsh617 is still finishing the content , AND we have not yet started building these pages in Drupal.  This is for a request that will be coming and is separate from the Analytics implementation for VA Forms Search React component and body links.~ 

Form detail landing page template is now being built in Drupal. Each page will be dynamically generated via the nightly migration of forms db data + the custom rich field values added directly in Drupal. 

**Form landing page template content fields and layout:**
Minimum and Maximum content fields on form detail pages can be seen in these mockups: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs#visual-mockups

**Additional info:**

- There will be about 40 top form detail landing pages with rich custom content fields (Related to; Online tool; When to use this form; Related forms and instructions; customized 'helpful links'). 
- There will be about an additional 420-450 other form detail landing pages with just basic form fields and the Related To field. These basic form detail pages will have standard 'helpful links' at the bottom.

</details>
</summary>
---

# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- **Is this request for Google Analytics implementation or QA?**
  - GA implementation > Addition to existing dashboard ([Find Forms Dashboard 1.0](https://analytics.google.com/analytics/web/?authuser=1#/dashboard/MHSfv0WxQySyKRB5IYyw1Q/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20191231&_.useg=builtin1/))

- **Who is this request for?**
    - Mickin
    - `vsa-public-websites`
    
- **What team/project is this work for?**
   - Public Websites
   - Find VA Forms - Detail Pages
    
- **Provide the Domain where Google Analytics needs to be implemented**
    - www.staging.va.gov and va.gov (but we might need clarification on Drupal urls)
    - _Identify if PII is passed in URL or title tag_ Nope
    
- **Please provide any upcoming deadlines or important milestones**
     - We hope to begin our UAT as soon as the week of August ~10th~ 26th

## Website Interactions to Track
**Note: the url structure of the form detail pages is www.va.gov/find-forms/about-form-[form-nbr]**
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Origin/Acquisition     | Breakdown of whether users are coming from Organic searches (Google), VA.gov on-site search, VA Find VA Forms Search | Table                   |
|2| Baselining             | # of pageviews on form detail pages over time                                                                        | Table and/or Line graph |
|3| Conversions/Engagement | # of PDF downloads (via link click)                                                                                  | Table                   |
|4| Conversions/Engagement | Form name + number of invalid PDF download (via link click)                                                          |       Table                  |
|5| Conversions/Engagement | # of Related form PDF downloads                                                                                      | Table                   |
|6| Conversions/Engagement | # of clicks to Online tool CTAs                                                                                      | Table                   |
|7| Top *n* Information    | Most viewed form detail pages                                                                                        | Table                   |
|8| Top *n* Information    | Most converted "Helpful links..." from form detail pages                                                             | Table                   |
|9| Top *n* Information    | Most converted online tools                                                                                          | Table                   |

 
---
 - Note: some form detail pages show more information than others. Here are mockups for the two scenarios:
    - Version user sees when a page has all custom content fields: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-heading-hierarchy-071620.pdf
    - Version user sees when a page has no custom content fields: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-minimum-content-072820.pdf  `<--updated 7/28 JL`

 
- Additional Comments
    - We have an existing dashboard that we'd like to update with these additional analytics
    - No authentication or test users required

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Karak888** [comment]
we haven't discussed implementation for these pages and they have not yet been created.  FYA @nedierecel - if Analytics has a ticket, it would be good for us to reference that one, but we see epics! thanks

**Comment by nedierecel** [comment]
@ncksllvn This was sitting in the Backlog. Is there anything further we can assist with?

**Comment by ncksllvn** [comment]
Hey @nedierecel, no, this still isn't actionable for your team just yet. Thank you for following up 🙂

**Comment by nedierecel** [comment]
@ncksllvn No problem!

**Comment by nedierecel** [comment]
@ncksllvn When this is ready for Analytics-Insights, can you please tag @bsmartin-ep and @jonwehausen in the comments. 

CC: @joanneesteban

**Comment by jonwehausen** [comment]
@ncksllvn Any movement here?

**Comment by bsmartin-ep** [comment]
@ncksllvn and @Karak888 -

Any updates for this ticket?

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx @jonwehausen @bsmartin-ep - FYSA: I've updated the original placeholder ticket description with more information and materials. 

The Drupal engineer will be complete with the forms db migration later this week. Which means the content team can begin inputting the rich custom content fields next week. I think the analytics work can begin soon but please verify/coordinate timing with @stephorkandatx. Thank you so much.

**Comment by MickinSahni** [comment]
hey team, made updates to this request using the new analytics request template. 

the main goal is to figure out how many users convert to downloading pdfs on these individual form pages and how many users navigate to online tools for a particular form. 

please lmk if i can clarify anything cc @joanneesteban @jenniferlee-dsva

**Comment by jenniferlee-dsva** [comment]
Thx @MickinSahni - confirming what you wrote ^. 

The list of conversions we want to track in the original description is still valid: 

> Calculate PDF conversion rate
> #of PDF downloads
> #of Related form PDF downloads

> #of pageviews on form detail pages 
> 
>Calculate online tool conversion rate
> #of clicks to Online tool CTA
> Helpful links
> #of clicks across helpful links per form

Note: I made 2 updates in the og ticket - ticket title, so it's super clear this is for the form detail pages, not the search; and added an updated PDF link showing the correct form fields and links for what users see when there are no custom content fields.

**Comment by MickinSahni** [comment]
Hey Platform team, I specified above that we should ideally have a singular dashboard for the entire Find VA Forms experience (Search + Detail Pages). Of course, this ticket is for the Detail Pages. I linked to the existing dashboard above. Thanks! :)

**Comment by jenniferlee-dsva** [comment]
@MickinSahni @jonwehausen @bsmartin-ep - A couple of other interaction/data I think would provide helpful data story for these form pages are: 

- How many people are landing on a form detail page from the forms search result link
- How many people are landing on a form detail page from organic search and va.gov site search
- What are the top form detail pages that people are visiting
- What are the top form detail pages that are converting people to a digital tool
- Which content links are the top clicks from form detail pages

These aren't all click events on the form page, so not sure how you can incorporate these into the form detail page data story - please recommend per your expertise.

**Comment by MickinSahni** [comment]
Hi, team. I cleaned up the AC a bit to reflect our updated request. 
Also attaching annotated screenshots to help provide more context:
- <img width="250" alt="image" src="https://user-images.githubusercontent.com/13204473/90662105-f15fcf00-e215-11ea-8d28-7b526f387354.png"> <img width="300" alt="image" src="https://user-images.githubusercontent.com/13204473/90662353-41d72c80-e216-11ea-93b7-dab458f8a036.png">

Would it be helpful to do a 15 min sync to clear up any questions? What's the timeline for providing data layers?

**Comment by jonwehausen** [comment]
Thanks for these updated components @MickinSahni and @jenniferlee-dsva -- those were certainly very helpful! Very much appreciated!

### Notes
- We have global document download tracking throughout the site through GTM, so no DL requirements necessary to track all downloads
- @jenniferlee-dsva once each of the form detail pages are introduced _(i.e `www.va.gov/find-forms/about-form-[form-nbr]` we will be able to track the most visited form detail pages as standard pageviews along with inbound data to those pages
- @bsmartin-ep if you could take a look at if there's further work that needs to be done to capture the search results correlation here that would be great

### DataLayer Requirements
- @MickinSahni here are the requirements we will most certainly want implemented for tracking based on your requirements

Description of Interaction | Screenshot of Interaction | Datalayer Event
------------ | ------------- | -------------
**Clicking on links contained within the Helpful links section** | ![image](https://user-images.githubusercontent.com/48527022/90803784-44ee1d80-e2e7-11ea-9172-d28845bba7bc.png) | `'event': 'nav-linkslist',`<br>`'links-list-header': '<click_label>'`<br>`'links-list-section-header': '<top_line_section_header`<br>`//i.e 'Helpful Links`
**Go to Online Tool primary button CTA click** | ![image](https://user-images.githubusercontent.com/48527022/90804234-ea08f600-e2e7-11ea-8d84-6c93c99f192e.png) | `'event': 'cta-primary-button-click'`

## Next Steps
- @bsmartin-ep to tackle GTM staging setup for tracking these components, and validate if any additional work is necessary to capture the search result tracking outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4552#issuecomment-675563843)
- @bmcgrady-ep to stage dashboard adjustments from comments

**Comment by MickinSahni** [comment]
Hey team, confirming this will probably be on it's own GA dashboard for the Form Detail Pages, correct?

**Comment by jenniferlee-dsva** [comment]
This all LGTM @MickinSahni. Not sure what action item I needed to do here other than review. LMK if there's something else.

**Comment by ncksllvn** [comment]
Can I pick this up as a dev task to implement, or do we need a separate ticket? I think I prefer just using the same ticket.

**Comment by joanneesteban** [comment]
@bsmartin-ep @bmcgrady-ep to follow up on this implementation & questions.

**Comment by MickinSahni** [comment]
> Can I pick this up as a dev task to implement, or do we need a separate ticket? I think I prefer just using the same ticket.

Unfortunately we can't Nick since GH doesn't allow multiple sprints associated with a ticket (VSP + ours). 
I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/12757 for us which is already in our sprint. @ncksllvn

**Comment by ncksllvn** [comment]
Oh I missed that one, sorry. Thanks for creating that!

**Comment by ncksllvn** [comment]
I implemented these analytics in https://github.com/department-of-veterans-affairs/va.gov-team/issues/12757. I think we can use the Drupal preview to validate, http://preview-prod.vfs.va.gov/preview?nodeId=5776. @jonwehausen when you have a moment, would you mind checking the data layer on that page?

**Comment by MickinSahni** [comment]
cc @bmcgrady-ep 

> I implemented these analytics in #12757. I think we can use the Drupal preview to validate, http://preview-prod.vfs.va.gov/preview?nodeId=5776. @jonwehausen when you have a moment, would you mind checking the data layer on that page?

**Comment by MickinSahni** [comment]
@bmcgrady-ep separate topic - don't think we can add more widgets to the existing find forms search dashboard, correct? so our expectation should be a separate GA dashboard for form detail pages specifically?

**Comment by bmcgrady-ep** [comment]
@MickinSahni - no, we are at the limit for the number of widgets we can have on the find forms search dashboard, so we would need to create a separate GA dashboard.

**Comment by MickinSahni** [comment]
Gotcha. Thanks, @bmcgrady-ep. When should we be able to checkout that dashboard?

@ncksllvn considering we're in prod now (behind basic auth), is there anything we need to do to begin seeing GA results?

**Comment by ncksllvn** [comment]
Nope, we should be good to go test start testing the analytics in any environment!

**Comment by jonwehausen** [comment]
### Next Steps
- QA analytics using preview link and document findings (on SOCKS) 
- Correct any GTM changes necessary to support this dataLayer
- Begin construction on form detail page GA dashboard leveraging these analytics

@MickinSahni We have been having some complications with our SOCKS so give us a bit to get that resolved and get the analytics tested

**Comment by ncksllvn** [comment]
> QA analytics using preview link and document findings (on SOCKS)

Actually the pages are published now. You should be able to use https://www.va.gov/find-forms/about-form-10-10ez/, and just use the standard basic auth credentials to access.

**Comment by jonwehausen** [comment]
Okay awesome! Thanks for this @ncksllvn. 

We'll try to get QAed as soon as we can.

**Comment by bmcgrady-ep** [comment]
### DataLayer Changes QA

Description of Interaction | Screenshot of Interaction | Status
------------ | ------------- | -------------
**Clicking on links contained within the Helpful links section** | ![image](https://user-images.githubusercontent.com/66263904/92663814-2b713d80-f2b7-11ea-9fed-eb1e7c72e32e.png) | ✔️ PASS
**Go to Online Tool primary button CTA click** | ![image](https://user-images.githubusercontent.com/66263904/92663557-7cccfd00-f2b6-11ea-9e7d-f7d37d414a22.png) | ✔️ PASS

**Comment by bmcgrady-ep** [comment]
@ncksllvn - Just confirming that once this page is live, users won't have to authenticate as they do now, right?

**Comment by MickinSahni** [comment]
@bmcgrady-ep that's correct. it's an unauth experience. just behind basic auth for phased roll-out

**Comment by bmcgrady-ep** [comment]
@MickinSahni - Thanks for the update. Here is a [link](https://analytics.google.com/analytics/web/#/dashboard/Pq1Oso_0SWWgHWBkcxwqKg/a50123418w177519031p176188361/) to a WIP GA Dashboard for Form Detail Landing Pages. Let me know what you think.

**Comment by jenniferlee-dsva** [comment]
Hi @bmcgrady-ep - the wip dashboard looks good. there are a couple of widgets missing still, but i'm assuming it's still a wip? 

>|1| Origin/Acquisition | Breakdown of whether users are coming from Organic searches (Google), >VA.gov on-site search, VA Find VA Forms Search | Table |

>|2| Baselining | # of pageviews on form detail pages over time | Table and/or Line graph |

>|4| Conversions/Engagement | Form name + number of invalid PDF download (via link click) | Table |

**Comment by MickinSahni** [comment]
hey team, quick bump to jen's message :)

**Comment by bmcgrady-ep** [comment]
Hi @MickinSahni and @jenniferlee-dsva 
I have made some updates to the dashboard to include the requested metrics above for the origin of the users and for baselining. The origin/acquisition had to be broken into 2 widgets - 1 for VA.gov on-site search and Find VA Forms Search and 1 for organic searches.

For the number of invalid PDF downloads, do you have an example of this happening? The only `PDF Downloads` events look to be successful downloads or we aren't currently tracking invalid PDF downloads. The only errors I have found happening on `find-forms/about-form` pages are `Script Errors`.

**Comment by MickinSahni** [comment]
> Hi @MickinSahni and @jenniferlee-dsva
> I have made some updates to the dashboard to include the requested metrics above for the origin of the users and for baselining. The origin/acquisition had to be broken into 2 widgets - 1 for VA.gov on-site search and Find VA Forms Search and 1 for organic searches.

Thanks, Ben! Confirming I'm seeing a couple new widgets. It's interesting we're seeing numbers for organic searches albeit small. @bmcgrady-ep are we able to tell if people are coming to these pages via Google vs. having a link saved. I'm imagining the numbers we're seeing is the result of going directly to the pages since we're currently [preventing indexing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12242).

> For the number of invalid PDF downloads, do you have an example of this happening? The only `PDF Downloads` events look to be successful downloads or we aren't currently tracking invalid PDF downloads. The only errors I have found happening on `find-forms/about-form` pages are `Script Errors`.

hmm @jenniferlee-dsva or @ncksllvn can you share your thoughts on this one?

**Comment by jenniferlee-dsva** [comment]
Replying regarding:

> For the number of invalid PDF downloads, do you have an example of this happening? The only PDF Downloads events look to be successful downloads or we aren't currently tracking invalid PDF downloads. The only errors I have found happening on find-forms/about-form pages are `Script Errors.`

Ah, so maybe I could have worded that better. We have just one error message for the form detail pages - it's for when a PDF form 404s when a user TRIES to download. (So they never actually do download the form bc of the error. That is what we would like to track - how many and what PDF forms are generating this error.)  The `Script Error` might be that but @ncksllvn should confirm.

**Comment by bmcgrady-ep** [comment]
@jenniferlee-dsva - After speaking with my team, we do not currently have tracking on PDF download errors. If you want to track this, we would be happy to, but we would have to work with your developers to render errors on PDF downloads through the Data Layer.

cc: @jonwehausen for visibility

**Comment by ncksllvn** [comment]
> Ah, so maybe I could have worded that better. We have just one error message for the form detail pages - it's for when a PDF form 404s when a user TRIES to download. (So they never actually do download the form bc of the error. That is what we would like to track - how many and what PDF forms are generating this error.) The Script Error might be that but @ncksllvn should confirm.

We are actually tracking that in the form of monitoring - we capture an event with some data into our app monitoring service, Sentry. The trigger for this happening is if the Lighthouse Forms API says a form's PDF is invalid. I'd have to double check on the criteria of what defines a PDF as invalid but previously this just meant the form's PDF couldn't be found (404)

**Comment by bmcgrady-ep** [comment]
> Thanks, Ben! Confirming I'm seeing a couple new widgets. It's interesting we're seeing numbers for organic searches albeit small. @bmcgrady-ep are we able to tell if people are coming to these pages via Google vs. having a link saved. I'm imagining the numbers we're seeing is the result of going directly to the pages since we're currently [preventing indexing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12242).
> 
@MickinSahni - I believe that people who have the link saved would be classified as direct traffic and that the organic traffic is people who land on the page from organic searches.

**Comment by bmcgrady-ep** [comment]
@MickinSahni @jenniferlee-dsva - Is there anything else you guys need in regard to this request?

**Comment by joanneesteban** [comment]
@MickinSahni @jenniferlee-dsva Please let us know if you need anything else! Closing this ticket.
