### ISSUE TITLE
BE | Notification Preferences | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45525]
## Background

Create a document that provides an overview of the back-end services and systems that support the profile notification preferences page.

## Tasks
- [ ] Add documentation for notification preferences.

## Acceptance Criteria
- [ ] Share documentation to the team for review and feedback

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/45525?planning-poker) with ZenHub @tpharrison

**Comment by SKasimow** [comment]
@tpharrison thanks for clarification!

**Comment by tpharrison** [comment]
@SKasimow Here is the [BE document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/notification_settings/backend_documentation.md).  Let me know when you have the product outline done and I'll link the two documents.

If you think some of the information in the "Overview" section might be better off in the product outline document, feel free to move it. Your call.

**Comment by SKasimow** [comment]
@tpharrison this looks great Tom! The Product Notification doc already exists; I'm just updating where needed. I can link to your doc
