### ISSUE TITLE
[Analytics] Help the auth exp team figure out a direct deposit error is recurring for users or not

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4553]
## Description

This request is for the authenticated experience team. We are trying to determine if one of our errors for the direct deposit feature is something individual users see multiple times, or if they see the error once, are able to make the fixes suggested in the error message, and then they are able to move on.

## Timeframe for Analytics Requested

Preferably some time the week of Jan 6 - 10. Please let me know if this is not possible so we can plan accordingly.

## Analytics to Track Down

[This is the link to our analytics for the direct deposit feature](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p187673796/). 

We are specifically interested in home-phone-error-update and home-phone-error-enroll. What we want to know — do users who see this error once see it again? And if they do see it again, how often is that happening?

We also are interested in knowing their path, if possible, after seeing this error. In theory, if they update their direct deposit information > see the error > make the fix we suggested > try to update their direct deposit again, they should not see the error again.

## Which Product Questions are you trying to answer?

This error exists as a bandaid to some internal VA workings. TL;DR is that if our backend detects that the phone number or mailing address in someone's VA.gov profile is not the same as it is in BGS (VA database), that person can not update their direct deposit information. We implemented a fix by putting an error message in the direct deposit form that asks people to update their phone number or address and then come back to try to update their direct deposit after. In theory, after their phone number/address is updated, they should be able to save new direct deposit information. We are trying to figure out whether this fix works or not. If a lot of people are seeing this error repeatedly, we'll need to dig into why that is happening.

## Additional Comments

Let me know if you have any questions! Happy to meet to discuss this briefly if it's helpful.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@Samara-Strauss Confirming I see this and reviewing the request. I'll be back in touch with further questions, if we have any!

**Comment by nedierecel** [comment]
@Justin-Pickett @Samara-Strauss I have the segments built to look at behavior for these errors and am doing my own QA of the results. I'll reach out for a time to review.

**Comment by Justin-Pickett** [comment]
@nedierecel sounds good. Thank you.

**Comment by Samara-Strauss** [comment]
Ditto — Thanks @nedierecel!

**Comment by nedierecel** [comment]
@Justin-Pickett - For your analysis, here is the link to a report using the 12/20/2019-present timeframe that you provided in Slack:

#### Summary and Self-Serve Report
- [Occurrences of Home Phone Update or Enroll errors](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p187673796/_u.date00=20191220&_u.date01=20200109&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Profile%20Save%20Failure%20-%20Direct%20Deposit%20Information%22,0%5D,%5B0,%22analytics.customDimension57%22,%22PT%22,%22home%22,0%5D%5D&explorer-table.secSegmentId=analytics.customDimension57/): There were 72 sessions (unique events) where the `home-phone-update-error` happened at least once. In that same row, there were 124 total events, which indicates that this was happening more frequently across sessions.

**Data Definition/Example of how the data is incremented**: I update my phone number and hit an error. This increments the unique events column 1 time and the total events column 1 time. I hit the error again and then the total events column counts 2 errors.

**Comment by Samara-Strauss** [comment]
Thanks @nedierecel!

**Comment by Samara-Strauss** [comment]
@nedierecel finally had a chance to review this — is there any way for us to tell if someone received this error --> went to edit their home phone number --> and got the error again? Looking at the data, it's unclear to me whether people maybe tried to edit their direct deposit more than one time in a row *without* going to fix their phone number, therefore triggering this error again, OR whether they did try to fix their phone number and then got the error again (which would be more problematic).

**Comment by nedierecel** [comment]
@Samara-Strauss Sure - I'll review the instances when they received the error, tried to edit, then received the Direct Deposit error with a `home-phone` error key.

**Comment by Samara-Strauss** [comment]
@nedierecel thanks!

**Comment by nedierecel** [comment]
@Samara-Strauss @Justin-Pickett I created a segment that looks at the following sequence in a session and found only 2 sessions where this occurred, which seemed to occur within the past few days.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/d9b5c24f-371f-439e-8bcf-c2fd7808c09b)

**Logic Used to Build this Segment**
1. User hits any `home-phone-` error
2. User then submits the form and an Event Action for `Form Submit - home-telephone` is triggered
3. User hits a `home-phone` error again 

_Screenshot of Segment_
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/b958e099-4b4d-4804-9b64-68f6ea244a6b)

**Resources if you want to self-service the report**

1. Step 1 - Click on this [link to Add the Segment to your Google Analytics](https://analytics.google.com/analytics/web/template?uid=frV5EWRMR92HuZneWi9pQQ); Add to the Personalization - Modernized View when it prompts you here:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/ad13efbd-b7ab-4ec7-8874-b72da7973537)

2. Navigate to Audience>Overview, then select "Add Segment" to find the Home Phone Error segment. 

3. @Justin-Pickett The more granular report under Audience>User Explorer will let you see more detailed user interactions once you have applied the segment.

**Comment by Samara-Strauss** [comment]
Thanks, @nedierecel — so it sounds like most people who see the home phone error aren't actually going to reset their home phone number, which would explain why they're seeing the error more than once.  That make sense. 

I think we have what we need. Closing this.
