### ISSUE TITLE
Update Incident Playbook with VSP Leadership Communication Process for Active incidents.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#45536]
# Description

The VSP Leadership team needs to be updated periodically on the status of an active incident.  

# Acceptance Criteria
- [x] Update Incident Playbook to add a section for Communicating on an active incident for the Incident Commander and include the following items.
-- State of Service:  Current state of the incident or service
-- New findings: What new things were found ?
-- Theory eliminations: Has any theories been eliminated ?
-- Anticipated Next Steps: What is planned next ?
-- Next Update:  When will be the next update.
- [x] Add a section for describing where the sensitive triage information is stored that will be linked to the new findings, theories and next steps.
- [x] Create Issue Template in Sensitive repo for issue triage work tracking info that will be linked to comments on incident's active status.

**Comment by td-usds** [comment]
For these specific items:

>       -- New findings: What new things were found ?
>       -- Theory eliminations: Has any theories been eliminated ?
>       -- Anticipated Next Steps: What is planned next ?

I think it's important in these communications to be concrete in what the actual things are. These status updates are intended to give decision makes the insight to make meaningful decisions, so the inputs to those decisions must be provided there.

If no new data (since the last status update) is available, then this must be explicitly listed out as such. But we need to be able to see the chain of events of "anticipated next steps" into new findings/eliminations/new theory

**Comment by zachclarity** [comment]
> For these specific items:
> 
> > * New findings: What new things were found ?
> > * Theory eliminations: Has any theories been eliminated ?
> > * Anticipated Next Steps: What is planned next ?
> 
> I think it's important in these communications to be concrete in what the actual things are. These status updates are intended to give decision makes the insight to make meaningful decisions, so the inputs to those decisions must be provided there.
> 
> If no new data (since the last status update) is available, then this must be explicitly listed out as such. But we need to be able to see the chain of events of "anticipated next steps" into new findings/eliminations/new theory

I think we will have to have an open zoom or slack huddle to share audio of active work.

**Comment by td-usds** [comment]
I was not intending a peek into the "active work as it happens" (because that would be distracting to everyone) but more details around "we've completed X and Y in our quest to deal with this incident" or "We will be working on X and Y next"

**Comment by zachclarity** [comment]
Added [PR for new issue template](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/548) in sensitive area for incident tracking.

**Comment by zachclarity** [comment]
> For these specific items:
> 
> > * New findings: What new things were found ?
> > * Theory eliminations: Has any theories been eliminated ?
> > * Anticipated Next Steps: What is planned next ?
> 
> I think it's important in these communications to be concrete in what the actual things are. These status updates are intended to give decision makes the insight to make meaningful decisions, so the inputs to those decisions must be provided there.
> 
> If no new data (since the last status update) is available, then this must be explicitly listed out as such. But we need to be able to see the chain of events of "anticipated next steps" into new findings/eliminations/new theory. 

A section on communication was [added to the incident playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook#Communication-on-Active-Incidents%5BhardBreak%5D) with these details.
