### ISSUE TITLE
[cFSR] - Create Tests for Copay Resolution Options

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#45556]
## Desired behavior
Tests for Copay Resolution Options should be created and passing for maximal and minimal.

## Acceptance Criteria
- [ ] Tests passing for maximal and minimal.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
This issue will be rolling over to sprint 82 due to competing priorities and bug fixes identified as part of pilot tests.
