### ISSUE TITLE
[08/19/22] Upload annual VEText user audit information to eMASS

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#45564]
## Description
Per the requirements of the VEText ATO, an annual user audit is required to be completed and final evidence is required to be uploaded to eMASS. With the completion of the audit, the final step is to submit evidence to eMASS.
---

## Acceptance Criteria
- [x] Determine final evidence appropriate for eMASS
- [x] Review with team
- [x] Approved by Justin/Shane/Lindsay
- [x] Uploaded to eMASS
---

**Comment by ahicksfearless** [comment]
Aware of this but need clarification on what final evidence is appropriate for eMASS.
