### ISSUE TITLE
[cFSR] - Create Tests for Debt Resolution Options

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#45562]
## Desired behavior
Tests for Debt Resolution Options should be created and passing for maximal and minimal.

## Acceptance Criteria
- [ ] Tests passing for maximal and minimal.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Dr-Pongo** [comment]
Rollover stemming from popups

**Comment by denisecoveyduc** [comment]
This issue will be rolling over to sprint 82 due to competing priorities and bug fixes identified as part of pilot tests.
