### ISSUE TITLE
[08/19/22] Update & Review the VEText PTA 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#45567]
## Description
As part of the VEText ATO maintenance, there is an annual PTA review that must be completed. The annual PTA review occurs in summer - July - September
---

## Acceptance Criteria
- [x] Review PTA
- [x] Make updates as necessary
- [x] Review & Approve with Lindsay/Justin
- [x] Review & Approve with Shane/Rob
- [x] Review & Approve with Randall
- [x] Finalize review process in eMASS
---

**Comment by ahicksfearless** [comment]
Randall just gave his comments. Waiting on Nancy to do the same.

**Comment by ahicksfearless** [comment]
Making edits to send back to privacy for another round of review.

**Comment by lindsay-insco** [comment]
Sent response re: Cloud service provider to Privacy office

**Comment by lindsay-insco** [comment]
Resolving questions with Nancy

**Comment by ahicksfearless** [comment]
All three signatures have been added. Uploading to emass 11/3.
