### ISSUE TITLE
Fine tune data sent from BE to FE for Systems (and possibly others) -- Pre-launch 

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#4556]
Prior to launch, we need to fine tune the data that backend sends to FE

1. Don't send PII such as ICN, EDIPI, patient id. (This is the priority though)
2. Remove any unneeded random data that the FE does not consume now and has no expectation of needing in the future.

The biggest one is the systems endpoint, can open separate tickets for anywhere else that this is a problem (This should probably be an Epic but I'll leave it as an issue for now).

**Comment by jbalboni** [comment]
I removed the ICN check from the front end, so the backend should be free to remove ICNs from any data it's sending to the front end, including in the list of identifiers in the `/systems` service.

**Comment by jbalboni** [comment]
Looking through the data we get back, I only see ICN in two places:

1. The systems service, which has a bunch of other ids, too
2. The `senderId` for the messages service.
