### ISSUE TITLE
Design | Profile | Limit Extensions to 6-Digits

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45563]
## Background

VA Profile has requested that we limit the number of digits we accept in the Contact Information/phone number field's extension section to no more than 6 digits (home, work, mobile).

#### BE Tasks
- [ ] Determine accessibility approach to communicate 6 digit limit
- [ ] Creat mock-up

## Acceptance Criteria
- [ ] Review with Dev and PM (and accessibility if needed)

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @cgednalske - please review and lmk if we should include. in Sprint 80 or 81. Thanks!

**Comment by cgednalske** [comment]
Hi @SKasimow I think this will be straightforward and can go in Sprint 80.

**Comment by SKasimow** [comment]
closing - dupe to #45257
