### ISSUE TITLE
AWS access for Ashton Lee

### ISSUE THREAD

**Issue by Code4FunXD** [department-of-veterans-affairs/va.gov-team#45599]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Ashton Lee

### Your Email

lee_ashton@bah.com

### Team, Role, and Company of the target individual

Team Ninjapigs, Software Engineer, Liberty IT Solutions

### Product Manager (PM) name and email

Nichole Harris, harris_nichole@bah.com

### Product Owner (PO) name and email

Premal Shah, premal.shah@va.gov

### Desired AWS Access

Looking for access to Lighthouse API logs and console utilities related to S3, EC2, RDS for triage and api management purposes. Colleagues whose permissions can likely be emulated are Kevin Cranmer or Aaron Hietpas.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@Code4FunXD is in the VFS roster.

**Comment by calquisola** [comment]
User: Ashton Lee
COR: Cecila Lee
VOR: Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Requested access approved.

**Comment by jbritt1** [comment]
First-time login credentials passed to user via DSVA Slack workspace DM.
