### ISSUE TITLE
ServiceNow access for Triage team

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#456]
## User Story
As a member of the VSP triage team, I need write access to VA's ServiceNow instance so I can file tickets with VAOIT when there are VSP and VA.gov issues that require their collaboration.

As a call center lead, I need access to ServiceNow to report issues to the platform team when issues are reported by VA.gov users.

## Goal
All members of VSP triage team can create a ticket in VAOIT's ServiceNow

## Acceptance Criteria
- [ ] @cvalarida can file a ticket in VAOIT ServiceNow
- [x] @kfrz can file a ticket in VAOIT ServiceNow
- [ ] @omgitsbillryan can file a ticket in VAOIT ServiceNow
- [ ] @LindseySaari can file a ticket in VAOIT ServiceNow
- [ ] @alexpappasoddball can file a ticket in VAOIT ServiceNow
- [ ] @Kimberley2019 can file a ticket in VAOIT ServiceNow

**Comment by alexpappasoddball** [comment]
@LindseySaari @cvalarida, Can you make sure you get this access.  @omgitsbillryan is an admin and he can help.

**Comment by LindseySaari** [comment]
Removing myself from the acceptance criteria. No PIV card yet and unsure of when I will get mine :(

**Comment by alexpappasoddball** [comment]
@Kimberley2019 Do call centers need this?

**Comment by kfrz** [comment]
Closing per thread above. Operations and BE engineers can find more information about ServiceNow by logging into the VA network.
