### ISSUE TITLE
Revert change to Modal component teardown

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4560]
We need to revert this change (https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/201) as it introduces a new little bug where the Modal will remember which element _first_ spawned it and always return focus to that element when the Modal closes.

In this GIF notice how the focus always returns to the second Direct Deposit EDIT button since that was the button that first caused the Modal to appear

![remember-focus.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/86ec08bc-8795-4e9c-958b-db33a9c23edc)

**Comment by bradl3yC** [comment]
Notes:

A change was made to formation-react that caused this bug, but it did not make it into staging yet.  It was also discovered that this breaking change did not fix the original bug.  After some assistance getting set up locally from @erikphansen , I was able to link formation locally and test the fix in the attached PR.  The change fixes the bug addressed in this card and the original bug that had the improper focus.

After that PR is merged / published - I can submit a PR to update the version of formation in vets-website.  At that point, all cards can be moved to validate for testing 👍
