### ISSUE TITLE
AWS access for Gary Fallon

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#45613]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Gary Fallon

### Your Email

gary.fallon@oddball.io

### Team, Role, and Company of the target individual

Platform Security, Security Engineer, Oddball

### Product Manager (PM) name and email

Troy Mosher troy.mosher@oddball.io

### Product Owner (PO) name and email

Thomas Delrue thomas.delrue@va.gov

### Desired AWS Access

I need full access to AWS.

### Access Expiration

ongoing

### Additional Notes

I currently have read access.

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
For AWS ACCESS
User: Ritesh Patel
COR: Crystal Moultrie
VOR: Amber Malcolm
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: yes

**Comment by raywangoctova** [comment]
Approved on behalf of Thomas and Mike while they are out on leave.
