### ISSUE TITLE
Design Intent  - Research Feedback - Public Websites, Income Limits, Income Limits Web App

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#45615]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
This is great timing in the product design cycle to incorporate discovery research! You have a solid plan and artifacts coming together. The bulk of my feedback surrounds trauma informed research, especially considering the questions surrounding family makeup and living situations. VA research has largely been at worst neutral and even a pleasant experience for both researchers and participants, even with highly sensitive topics, so not to make it sound inevitable that a tough situation will arise. 

Still, it's best to be prepared and a heightened sense of awareness is highly advised due to the nature (discovery, more deep probing questions about a veteran's life) and scope of this research (specifically asking about family and living situations). If you feel that you need more expertise in this area, Martha would be a great resource. Cindy has conducted research for the VA with heightened awareness and may also be able to lend some time as a resource. I can help you get in touch with and/or join in a meeting or Slack discussion with them if that would be helpful. Finally, I'll add here that this research feedback for the Midpoint Review is not meant to supersede or supplant the need for the[ Research Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) that's still required before recruitment kickoff.

For easy access, I'm repeating some important links from the feedback section here:

- [Research Safety and Emergency Exit Strategies](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies)
- [Trauma-Informed Conversation Guide TEMPLATE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md)
- [Trauma-Informed Research Plan TEMPLATE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md)
   - And specifically here the subsection section under Method for [Trauma-informed research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md#trauma-informed-research)

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
none

**Should:**
- 1 Should review trauma informed guidance, specifically [Research Safety and Emergency Exit Strategies](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies) before moving forward with conducting research.

- 2 Should tailor research plan to include trauma informed sections of the new [Trauma-Informed Research Plan TEMPLATE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md), where it makes sense for this research. 
   - 2a Should add a subsection to the research guide Methods section for [Trauma-informed research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md#trauma-informed-research). We don't have a budget for social workers (it's currently an aspirational goal), and we don't expect for them to offer their services for free even if you had a connection for including some. However, many of the other points in this section of the template are likely relevant and reasonable actions to document and/or take for this research.

- 3 Should tailor conversation guide to include relevant trauma informed sections of the new [Trauma-Informed Conversation Guide TEMPLATE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md)
   - 3a Some likely relevant sections:  
      - relevant additional language in the [Intro section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md#intro---5-minutes)
      - relevant information or the complete section for [Protocol for Recognizing & Handling Trauma-Triggering](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md#protocol-for-recognizing--handling-trauma-triggering)
      - a section either at the end or another place the moderator can easily scroll to for [emergency exit strategy](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies#ResearchSafetyandEmergencyExitStrategies-Sampleexitstrategies)
  

**Consider:**
- Consider current Question 5 from the conversation guide may be a bit unclear. "Were you receiving other benefits at the time? Which benefits?" 
While in discovery research, vague questions can make sense to better allow the participant to guide the discussion, depending if you are specifically interested in which "VA benefits" and/or which "other insurance/medical benefits" were being used, consider rewording the question slightly, adding a more narrowly tailored followup, or either splitting this into two different questions.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by fmccaf1** [comment]
Thanks for this helpful feedback, @claytonzook. All done here, but not clear on whether or not I'm supposed to close this ticket.

**Comment by claytonzook** [comment]
You may close this Collab Cycle feedback type ticket at your discretion @fmccaf1 

When you are ready for the official [Research Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review), feedback is instead given on the [Research Repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1). Those do stay open - so different protocol on those.
