### ISSUE TITLE
Caution Flag Search Results: Discovery Findings Collection

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4562]
- [x] Replicate Findings Mural Board 
Discovery findings board https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1578343997580/439d55c32c55bc88a9a79d82d4c488d4e30cdd43

- [x] Share findings

**Comment by amyknox** [comment]
Past Caution Flag design research frm Emily... 

Here is the results summary from some earlier versions of the alert boxes (Sept 2018): https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/SSO/Research/Round%201%20-%20MyHealtheVet%20Tools/results-summary.md

And here are the results of testing on the current versions of the alert boxes (Nov 2018): https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/SSO/Research/Round%202-%20Self-Service%20Tools%20CTAs/results-summary.md (edited)
