### ISSUE TITLE
Design | Profile | Personal Info | UAT - Resources and Support Article

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45624]
## Background
- Return to discussion about Resources & Support article. 

## Tasks
- [ ] Add tasks here that must be completed

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @cgednalske - I created this separate ticket for Resources and Support; we can leave in the the backlog until ready to pick-up.

**Comment by andaleliz** [comment]
@Samara-Strauss I've assigned this to myself - looks like it was something Christina was slated to work on. Not sure if you are aware of this ticket, flagging it in case you want it put it in an upcoming sprint. I'm not really clear on what it's for other than something about personal information in the resources and support section of the site.

**Comment by Samara-Strauss** [comment]
TBH I am not sure if this is relevant still or not. @DanielleThierryUSDSVA is there still a plan to add content to resources & support around preferred name and gender identity?

**Comment by DanielleThierryUSDSVA** [comment]
Hi! @Samara-Strauss @andaleliz I think we should put this in the icebox for now. This was something that we talked about potentially adding value, but I think there are a lot of open questions around this from a broader perspective and I don't think we have a lot to add here right now. I think the content we landed on in the profile itself provides the information that we can confidently communicate at the moment.

**Comment by Samara-Strauss** [comment]
Thanks for this, @DanielleThierryUSDSVA! If we feel like this would be on hold indefinitely, with potential to not happen at all, I think I might actually close the ticket. We can open something later on if it seems like it would be useful.

**Comment by DanielleThierryUSDSVA** [comment]
That makes total sense to me. Thanks, @Samara-Strauss!
