### ISSUE TITLE
[BE] My VA: Update My VA Architecture Diagram

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45638]
## Background
The My VA [Architecture diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/Technical-diagrams/My-VA-architectural-diagram.md) is outdated and does not include the recent addition of onsite notifications. We want to review it and update to reflect the current state of My VA, post-launch of all audit UX improvement work. We should also add some additional details to the technical documentation to include descriptions of the APIs we are utilizing.

## Tasks
- [ ] Review and update backend technical documentation in github
- [ ] Review with Tom H (new task)

**Comment by ajakabcin** [comment]
thanks @dellerbie!

**Comment by ajakabcin** [comment]
Thanks @dellerbie ! This is a great start - very thorough in that covers everything I think we're calling. I think we'll want a few more details in here though - do you mind reviewing with @tpharrison? I think he'll be able to help you flesh things out a bit more!

**Comment by ajakabcin** [comment]
oh that's excellent @dellerbie - so helpful! Ok going to mark this as closed now thank you!
