### ISSUE TITLE
Specific header content for Supplemental Claims

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#45639]
Content guidance for header elements from the sitewide IA/content folks. 

1/ H1 should be: File a Supplemental Claim VA Form 20-0995 (delete "Equal to" as that's older language that we no longer use)

2/ For all these subheads attached to "Step 3 of 6" etc., please use sentence casing, so: New and relevant evidence

3/ Instead of "Your application will be saved with every change." Make it active voice [revised 8/15]: "We ~'ll~ save your application with every ~time you add or~ update ~information~."

Final version of this line: We save your application with every update.

**Comment by Mottie** [comment]
We can fix the first 2 easily, but the last one is a global change. We'll need to double check with the content folks.

**Comment by thehastingsp** [comment]
@Mottie [these changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44411) came from the content folks but hear you on the global change. I suspect those have to start somewhere, but let's ask @bethpotts for help on that?

**Comment by thehastingsp** [comment]
This is done
