### ISSUE TITLE
Design Intent - IA Feedback - Public Websites, Income Limits, Income Limits Web App

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#45649]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
Excellent start. I look forward to seeing results of further exploration. 

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
Create [swim lane diagram](https://bigbangip.com/swim-lanes-guides-user-experience-design/) to map current state

**Consider:**
Revising conversation guide to include a [Critical Incident ](https://www.nngroup.com/articles/critical-incident-technique/)question
and adding clarifying questions as follow-ups if needed. 
## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by wesrowe** [comment]
@fmccaf1, the action items here are mostly yours. There are no "musts" so I checked that box already. Are you planning to create a user journey diagram with swim lanes? 

I think we can close this ticket once you've provided that clarification.
