### ISSUE TITLE
[BUG] Accordion design isn't responsive to mobile

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#45652]
## What happened?
Download buttons, tables, and alerts are not fit for mobile

<img width="452" alt="responsivebug" src="https://user-images.githubusercontent.com/14154792/184414632-f53be4ff-7f27-4668-9197-2db6fe0a7fff.png">
<img width="407" alt="Screen Shot 2022-08-12 at 12 43 09 PM" src="https://user-images.githubusercontent.com/14154792/184414635-19a894e9-4770-40f7-9b73-872e46a6d973.png">

## Steps to Reproduce
- [Log in as user 299 and get to step 2](https://staging.va.gov/records/download-va-letters/letters/letter-list)
- Using any browser, reduce the screen width to a mobile size and zoom in by 200%

## Desired behavior
Design should be responsive to mobile

## Acceptance Criteria
- [ ] Buttons don't cut off 
- [ ] [Tables follow VA Design System guidance](https://design.va.gov/components/table)
- [ ] A more mobile friendly alert pattern is used

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jacobworrell** [comment]
@joshkimux is this ticket redundant to the other tier 1 defect

**Comment by joshkimux** [comment]
@jacobworrell it is! Let me close this out and transfer the details over to the new tier 1 defect. Let me know if you'd prefer me to break down that mega tier 1 defect into smaller more palatable ones. I ended up grouping them together as there's lots of interdependencies. Going to work with @skylerschain on this more, but my hunch is that we might want to rethink the design of these accordions wholesale.
