### ISSUE TITLE
General Analytics Request for Skyler Schain (Benefits Team 1)

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#45651]
Hey folks 👋

Our team works on the Claims Status Tool. I am looking to get some info on the **number of claims** the average user has in the Claims Status Tool at any one time. Our staging environment is not very realistic here, since there are a ton of claims associated with each test account. 

Please let me know if you need any more info, or if there is another better way to proceed here. Thanks!

**Comment by jonathan-epstein13** [comment]
@skylerschain is this request to see this specific event is tracking? or is it something else in GA specifically you are looking to see? We might need some more information to see what needs to be done.
I will reach out to the team. 
cc: @michelle-dooley

**Comment by skylerschain** [comment]
Hey @jonathan-epstein13 - thanks for helping out. I'm not sure I understand the question, so let me know if I'm missing something. I am looking to see specifically if we have data on the number of claims in the CST (Claims Status Tool) for the average VA.gov user. I don't know if this is currently being tracked.

**Comment by jonathan-epstein13** [comment]
@skylerschain can you send over the exact URL for the Claims Status Tool (in regards to number of claims in the CST (Claims Status Tool) for the average VA.gov user.) An example would be https://www.va.gov/claim-or-appeal-status/  and I can check what is being tracked there. I see that tracking the number of claims per user isn't realistic to check in the staging, so if I can see the URL tracking what you need, then I can possibly see what is in GA (production) already. Does that make sense? Let me know if you have any questions.

**Comment by skylerschain** [comment]
Indeed! Here's the URL for what I'm calling the "CST Overview Page" – the
page that shows all of your current claims, both open and closed.

https://staging.va.gov/track-claims/your-claims?postLogin=true

**Comment by jonathan-epstein13** [comment]
This is the section to look at and just want to know the number of claims the average user has in this section at specific times? Just want to make sure. 

![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/0533db5e-17bb-4504-b877-276a574478f6)

**Comment by jonathan-epstein13** [comment]
@skylerschain I am looking into this request and will discuss with the team about next steps.

**Comment by jonathan-epstein13** [comment]
@skylerschain here is the [Custom report for CST](https://analytics.google.com/analytics/web/template?uid=8WncU1U6Tb6JHN7aAo7_Lg) let me know if this report is giving you the data you need. We can narrow it down by the type of action for the specific URL.

Instruction to open report: Click on the URL -> select a view from dropdown menu -> Select All VA.gov Website Data {Production} --> Select Create --> Report will pop up in the section Customer reports. 
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/91df8a09-9eb9-49eb-b681-1a958fe10dbc)
Let me know if you have any questions.

**Comment by skylerschain** [comment]
Thanks Jonathan. I am being asked to create an account, I think. Do I need to set something up or connect to an existing account? 
<img width="1232" alt="Screen Shot 2022-08-19 at 4 12 59 PM" src="https://user-images.githubusercontent.com/95102058/185700027-5d36ea2e-f70c-4463-917b-340fc714ecf7.png">

**Comment by jonathan-epstein13** [comment]
[Template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo)for requesting access to google analytics. You can follow the instructions in the template and let me know if you have any questions.

**Comment by skylerschain** [comment]
Thanks Jonathan! I was able to view the report. 

I think this is the right page (www.va.gov/track-claims/your-claims?postlogin=true). But I'm trying to see the # of claims that exist on this page for the average user. I don't think it would be tracked as an "event type", since it's not triggered by a click event. But I could be wrong about that. Is that listed in the report somewhere, and I'm just missing it? Is that something we currently track?

cc: @jerekshoe @samcoforma who might be able to help me explain this better

**Comment by jonathan-epstein13** [comment]
@skylerschain looking into the different reports in GA for you to be able to calculate the # of claims per user, the claims should be tracked and I'll send those interactions and the data layer over as well.

**Comment by jonathan-epstein13** [comment]
| Description of Interaction | Screenshot | DataLayer | Tag | Pass / Fail
| -- | -- | -- | -- | -- |
| Arriving on the track-claims/your-claims page | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/70d6e755-19a0-47c2-927e-00adaedba441)| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/0fd250d6-30f8-4869-92c8-862712007782)| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/f392b05b-50c0-4c36-b1fb-60eaee7bf59a) | :green_circle: PASS


Attached you will see the actual claims are being tracked (when arriving on the page.) Please let me know if this makes sense and I will adjust the report to only show this specific `event_action`.

**Comment by skylerschain** [comment]
Hm, where is the number that shows the actual number of claims? I'm not understanding where to look for that. 

cc: @joshkimux as fyi

**Comment by jonathan-epstein13** [comment]
@skylerschain I'm showing that the claims are being tracked. I believe the calculations you can do manually. 
Below are the events for the `event_action` - `API Request - GET claims - successful` this is my understanding of how the claims are being tracked.
Here is a screenshot from the report and attached here is the [documentation ](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/metrics-and-dimensions )for the metrics & dimensions in GA. 

Would unique events be the type to look for when it comes to # of claims per user? What is being tracked, is an` API_Call `(`event_category`)

Here is an example from the Metrics & Dimensions above:

> Total Events
> 
> Total number of times the interaction was done (includes duplicates, ignores user)
> 
> Veteran A clicks on track claims button, goes to the claims page, circles back and clicks track claims again
> 
> Total Events = 2
> 
> Unique Events
> 
> Number of sessions where the event occurred (excludes duplicates)
> 
> Veteran A clicks on track claims button, goes to the claims page, circles back and clicks track claims again.

Unique Events = 1
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/c37207b6-d024-4224-b541-81cc2683d662)

Let me know if there any other questions or another way we can go through this.

**Comment by skylerschain** [comment]
Hey Jonathan, maybe we can schedule a quick call to run through this?

**Comment by jonathan-epstein13** [comment]
@skylerschain hello! here is a [segment ](https://analytics.google.com/analytics/web/template?uid=YLPqb1pXQ3eJjx9fr3vLzw) I created to use for a user [report ](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220814&_u.date01=20220820&_.useg=user4xUitMR1Qda2aFjdA4jBeQ) (Audience -->overview)

Screenshot of segment:
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/725bbcdf-b54b-486a-9f99-3a05087c1145)

Screenshot of user report (summary)
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/5eea7863-787d-473f-b018-07173350fb8f)

I'll take this back to the team to see _if_ this how we would check for claims per user on the GA side. Keep you posted!

**Comment by skylerschain** [comment]
Thanks!

**Comment by michelle-dooley** [comment]
Hi @skylerschain - Unfortunately the information you are looking for is not stored in GA.  GA only tracks events/interactions on a page, so we could tell you how many times a user clicked on one of their claims but we do not have a way in GA to count the number of of those links that appear on a page.  That information would need to come from the ddb that is storing the claims details.  Do you know where the active claims that populate the page are being pulled from?

**Comment by skylerschain** [comment]
Thanks for clarifying, @michelle-dooley! @jerekshoe might know the answer to that question.
