### ISSUE TITLE
Caution Flag Search Results: Design Reviews

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4566]
- [x] Review with DEPO 
- [x] Review with VA Design

**Comment by ccruzgra** [comment]
Reviewed Caution Flag Search Results work today with VA.gov design teams.

**Comment by ccruzgra** [comment]
@amyknox Since we are combining the discovery and prototype checkpoints where we'll share the CF designs with EDU, can this story be closed?

**Comment by amyknox** [comment]
We'll need to share our final design with DEPO before we deploy it.  Based on our "ambitious" plan to hold the CF checkpoint Thursday, we should plan to review with DEPO before that. Maybe Tuesday during their office hours.

**Comment by ccruzgra** [comment]
Reviewed final designs today with DEPO, specifically Ryan Thurwell.
