### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by FHiatt** [department-of-veterans-affairs/va.gov-team#45661]
### Your Name

Frank Hiatt

### Your Email

Frank.Hiatt@adhocteam.us

### Your Role and Team

Senior Product Manager/Integration Experience Team (IET)

### Product Manager (PM) name and email

Frank Hiatt/Frank.Hiatt@adhocteam.us

### Product Owner (PO) name and email

Thomas.Delrue@va.gov (note he is on PTO until 8-29-2022)

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFM2jCH1B8rM9pmciMEaleTtAGHb3kukxXoIpeuQAZE+J6/axkf4rbtxrdDL/RnAiPh2Vi8E4Us/TwBYsLWaMYbQqxU8G2FFTAzBIuvfPd87UUnxqWqzRkqNa7aXKyO5tk2gsh6uQrclV+lAatR0v8QUNeYFh87H8Iqtcs0KHr8JbUysAVnfobTof/9PU/acVg8rQ9sWCb/Cag6HJQlctmMMYa39IZ/GPdYsYar5mistpUKPIVxZsOs8Gr/sQLC3jj91MR41Iwv7T0ewTqqmQhI0Ildxr30PowOP7GUVUfIznUrjerAUjR3aprQYfYJPrO5Q6xy4KnXCrKhCVvDcgPPIzMcE2zRo9Xjt8T9tHrGND5x7SsUVbOxIm5QeaMa/Dq/o4edojBlGud0gM/7IIlCsO/A+WMI2Ih+81UqH6lHM2ZRo1cImrpK8dfhBIdXG3SEabtm/vh+oNcYxYt0ccqLQpbrcqnKu7EwSL24Ock4yx/xwMkDHQPP6Pgo9335CE= fhiatt@FrankHiatt-HP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by FHiatt** [comment]
Only change is, AdHoc IT requested I create a new SSH key and resubmit my form

**Comment by calquisola** [comment]
Hi Frank, 

Your ssh key was updated.
