### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#45669]
### Your Name

Dan Turner

### Your Email

dan.turner@adhocteam.us

### Your Role and Team

Senior Designer 2 at Service Design Team

### Product Manager (PM) name and email

Bryan Ivie

### Product Owner (PO) name and email

bryan.ivie@adhocteam.us

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYbjciffRX4ES5CgZBirbN8/7tfRuDvtRtVDaToupUIjWXoNJAfKt9K6zy66KTRlgwPeJcFOrvI71dJo4pOBX2Aqps9p527wibkG2ZjsadCLjlRhJYRmUZ7OYoy+G/x+JoQlJPSF6SCrihKed2EcTQEYBqEgygk/vMjzQExf2xcUpnNJFMYVvjwljMgD6V0xjTcBmcl6kGhBhy6vRF8+K0fTcc9yMZdFV6PypXwR6RHWw4ahpdV++s02CzTzCJdpuyxNWtJrVvMcqrZGRh4OZeuNqXHK4CPrwDGpFWaOvGCU230+6lekibm/EyXkGgfyqponILsTCZMPpYVCLkHm3eSFaT50TordrCpF64SkLWTXA2N2XUXWOxfVO5asLD4VZGPwTfD1gTktYqJR+YSq1XBAzwlIRxSQVp6zRXRih2auHLc1TpQVf8TdnYQvxaRQwZGZj4wn/eTmUoF4+LqWli7dqPbKQHdH0xXG1LaJephfHKy11FFxJlKCSvWGOoKyU= danturner@Dan-Turner-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
