### ISSUE TITLE
AWS access for Scott Meyers

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#45660]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Jeff Langworthy

### Your Name

Scott Meyers

### Your Email

scott.meyers@coforma.io

### Team, Role, and Company of the target individual

Benefits, Software Engineer, Coforma

### Product Manager (PM) name and email

Sade Ragsdale, sade@coforma.io

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

I'm currently working on the **LGY: Certificate of Eligibility** application which sits behind a proxy. I need to be able to access requests on staging to debug issues with requests made to this service.

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mleclerc00** [comment]
User is listed in vfs team roster

For AWS ACCESS
User: Scott Meyers
COR: Eunice Garcia
VOR: Jeff Langworthy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by td-usds** [comment]
Requested AWS Access Approved

**Comment by jbritt1** [comment]
First-time login credentials passed to user via DSVA Slack workspace DM.
