### ISSUE TITLE
[FE] 1010EZ submission error messaging

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#45667]
## Description

[Updated to reflect comments below!]

- The 1010EZ error message is generic, and the component needs to be updated to give users a better path forward in the event of an error. 

## Tasks

The [About VA Form 10-10EZ](https://www.va.gov/find-forms/about-form-10-10ez/) page has a link to the PDF download, which the updated error alert includes.

- [ ] Update the error alert for the [submission page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nR30o4z)

## Screenshots

<img width="655" alt="image" src="https://user-images.githubusercontent.com/81988788/189947774-b035090b-4892-4618-8a5f-8a016054ed58.png">

## Acceptance Criteria

- [ ] Update error message with links and PDF download

**Comment by longmd** [comment]
@nicko-amida , we've run into a slight snag here. The form system won't allow for the actual component type that allows us to go out and check if the user is authenticated or not. We will need to revise this to be generic and maybe wordsmith it to cover both status' without swapping out the content.

**Comment by longmd** [comment]
@nicko-amida , just wanted to check on this. I see your comment from 44664 that said the message was updated, but I don't see that in this ticket.

**Comment by nicko-amida** [comment]
@longmd Hey, sorry - I was debating if I wanted to wait for some content team feedback on my updated message, but I might just skip it. I will updated here again today with the new mockup!

**Comment by longmd** [comment]
@nicko-amida , right on!! Do whatever you feel is right with it. I have no problem waiting for that feedback if you want to obtain it. Just wanted to make sure I wasn't missing anything. 👍

**Comment by nicko-amida** [comment]
@longmd Content updates made! The new message is generic enough for unauth/authenticated, and the only other update is the "Other ways to apply" heading.
