### ISSUE TITLE
Design Intent - Accessibility Feedback - Public Websites, Income Limits, Income Limits Web App

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#45663]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
No major feedback at this stage, just wanted to reiterate what folks said in the meeting: 
- Definitely design for mobile and accessibility first! Complex data tables can be a pain for assistive technology users, especially on mobile. If that's the best way to display the data, that's fine and we can make sure it's as accessible as possible. But if there are any alternative approaches that you find in your design work, definitely consider that path!
- Definitely follow the trauma-informed research guidelines that Clayton discussed.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by fmccaf1** [comment]
All finished here @briandeconinck. I'm not sure if I'm supposed to close the ticket.

**Comment by briandeconinck** [comment]
@fmccaf1 You are welcome to close this out whenever you've addressed the feedback and are ready for it to be closed -- no need for permission from us. Thanks!
