### ISSUE TITLE
VBA Facility site modernization from Sitewide Facilities 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-team#45672]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

As a part of the VBA modernization :

- Develop and validate a VBA service taxonomy
- Develop nationalized content for VBA services
- Architect for the reuse common content throughout the VBA facilities pages, and consistently refer Veterans from facilities pages to Benefits Hub content 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes MVP targets 7 of the 58 VBA Regional Office sites
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.

## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
12-18 months (?)
6 months to MVP
6-12 months following to migrate remaining sites

  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices)
- [Design sketch](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)
     - [VBA RO page](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/5712745E-0E95-47D2-9AAE-33F08EA3819E/canvas) mostly follows the patterns established for Vet Centers
     - [VBA RO page annotated](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff) highlights areas where we are iterating on a pattern
     - [Facilities Services](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/9BAF00BD-1CA9-4FCF-A14B-E2B3D31A18E6/canvas) shows the design for an expanded facility service accordion (Veteran benefits, Family member and caregiver benefits, Service member benefits, Other benefits). VBA facility services are based primarily on the current VAMC design.
     -  [Facilities Services annotated](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/578C3207-C5A3-4303-AB18-4AFC27AC54D2/canvas) highlights iterations and additions from VAMC to VBA.
- Link to prototype or mockups: in progress - to be finalized following Midpoint review on 8/1
- Link to any epics/issues that may be helpful
   - Super Initiative - VBA Regional Offices modernization [#13029](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/13029)
   - Initiative - VBA Regional Offices: Design & Develop MVP [#10514](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/10514)
   - Collaboration Cycle for Sitewide Facilities VBA Regional Offices [#46029](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029)
   - [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/2023-06-veteran-facing/research-plan.md) 
   - Research for these pages will focus on specific VBA problems to be solved. 

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated staging review date: by Dec 31, 2023 (just guessing here)

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed 

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name:  Sitewide Facilities 
- OCTO-DE product owner:  Michelle Middaugh
- Product manager:  Jane Xiong
- Designers:  Dave Pickett and Jordan Wood
- Drupal engineers: Steve Wirt and Christian Burk
- FE engineers:  Max Antonucci and Eli Selkin
- Product/team Slack channel: #sitewide-facilities 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by jilladams** [comment]
@mnorthuis @RLHecht @DanielleThierryUSDSVA I know Michelle has been in touch on this in the last few weeks. Our team wanted to flag that we've seen with recent other work that there may be a use case to name-space the VBA URLs, (e.g. /regional-office) in order to make it simple to publish Full-width alerts across all VBAs easily. (This came up in the process of publishing PACT Act extension to VAMCs, where they are not namespaced.)

Let us know if it would be helpful to schedule time to discuss, or what you all are looking at as far as priority to get to this ticket. Thanks!

**Comment by mnorthuis** [comment]
That is an interesting use case.  However, we don't allow for empty directories in our URLs, and this hasn't been the approach to facilities in general.  We can keep this in mind as we are solutioning.

**Comment by davidmpickett** [comment]
@mnorthuis In our conversation the other day, you said we should open a request about VBA. Should we close this one and start a fresh one?

**Comment by mmiddaugh** [comment]
I created VBA IA Request from Sitewide-Facilities #64934 to replace this one so we have a more clean request going forward.
