### ISSUE TITLE
Vet Centers pages in Districts, 1, 2, 3, and 4 to review

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45685]
## Issue Description
This ticket is for the content team's work in reviewing Vet Center pages before we send to Jessica's team for their final sign off. We should be prioritizing centers in Districts 1 and 4, followed by 2 and then 3. Some of these pages may have already been looked at once so we need to confirm that they've made the edits we've asked them to. 

### District 1
- [x] Bloomfield, NJ [(added 8/17 per Slack-MM)] (sent to Tiffany for final sign off) 
 (https://dsva.slack.com/archives/C01K37HRUAH/p1660843823768439) (sent to Tiffany for final sign off) 
- [x] Bucks County (sent to Tiffany for final sign off) 

### District 2
<details>
<summary> Requested reviews and feedback sent </summary>

- [ ] Chattanooga (second round of edits)
- [ ] Orlando - one of MVP locations, was published in July 2021 (MZ: I don't think anything needs to be done here, but just leaving unchecked until I confirm with Tiffany, RH)
- [ ] Columbia, SC (Randi negotiating with Tiffany on this one)
- [ ] Ocala (ready to publish but holding off per Tiffany/Randi)
- [ ] Tampa Vet Center (initial feedback sent 4/5/22 - Megan will review)
- [x] Marietta (Sent to Tiffany with 2 questions/possible edits that are needed) 
- [x] Jupiter _(very close to ready for final review! feedback sent 8/18- MM)_
- [x] Lawrenceville _(feedback sent 8/19 - MM)_
- [x] Greenville _(feedback sent 8/19 - MM)_
- [x] Lexington _(feedback sent 8/19 - MM)_
- [x] Memphis  _(feedback sent 8/19 - MM)_ **_This one is ready for final review and approval - MM 8/25_** 
- [x] Mobile _(feedback sent 8/19 - MM)_
- [x] Pensacola _(feedback sent 8/19, pending addition of Mobile Vet Center then ready for final review 8/23 - MM)_
- [x] Pompano Beach _(feedback sent 8/19, met 9/23, more feedback sent 9/27 - MM)_
- [x] Atlanta (MZ spoke with Nona on 8/26 and sent to Tiffany for final feedback on 8/29) 

Reviews requested 8/18
- [x] Daytona _(feedback sent 8/19, 8/23 - MM)_
- [x] Johnson City  _(feedback sent 8/19 - MM)_
- [x] Hatillo (revisions and feedback sent in April and May, second round revisions from MZ requested 8/21)
- [x] Atlanta _(feedback sent 8/19 - MM)_

Reviews requested 8/19
- [x] Knoxville _(feedback sent 8/22 and 9/27 - MM)_
- [x] Louisville _(feedback sent 8/22 - MM)_
- [x] Bay County _(feedback sent 8/22 - MM)_ **_This one is ready for final review and approval - MM 8/31_** 
- [x] Ponce (Tiffany came back with feedback and sent to Vet Center for more corrections 8/26)

Reviews requested 8/22
- [x] Myrtle Beach _(feedback sent 8/22 - MM)_
- [x] Huntsville (sent to Tiffany 8/24)
- [x] Miami (sent to Tiffany 8/24)

Proactive reviews based on activity
- [x] Fort Lauderdale _(feedback sent 8/22 - MM)_
- [x] Melbourne Vet Center _(reached out to offer assistance 8/22 - MM)_ 
        - has new VOPS - Tiffany provided overview of resources and workbooks, etc on 8/24
- [x] Naples Vet Center _(reached out to offer assistance 8/22, feedback sent 8/23 - MM)_

Reviews requested 8/23
- [x] Clearwater Vet Center _(feedback sent 8/22 - MM)_
- [x] Naples Vet Center  _(feedback sent 8/23 and 9/15- MM)_
- [x] Tallahassee Vet Center  _(feedback sent 8/24- MM)_
- [x] San Juan Vet Center _(feedback sent 8/24- MM)_
- [x] Okaloosa County Vet Center _(reached out to offer assistance 8/22, feedback sent 8/23 - MM)_
- [x] Jacksonville Vet Center _(feedback sent 8/25- MM)_
- [x] Gainesville Vet Center (Megan sent feedback 8/25)

Reviews requested 8/24
- [x] Lexington, KY Vet Center  (back again) **_This one is ready for final review and approval - MM 8/25_** 

**Second reviews** 
- [x] Greenville (requested 9/7) _(feedback sent 9/12- MM)_
</details>

### District 3
<details>
<summary> Requested reviews and feedback sent </summary>

- [x] Columbia, MO
- [x] Anoka _(feedback sent 8/30- MM)_
- [x] Cedar Rapids _(feedback sent 8/30- MM)_
- [x] Sioux Falls, SD _(feedback sent 8/30- MM)_ **_This one is ready for final review and approval - MM 8/31_** 
- [x] Springfield, IL  _(feedback sent 8/30- MM)_
- [x] South Bend  _(feedback sent 8/30- MM)_
- [x] Evansville, IN _(feedback sent 8/30- MM)_
- [x] St. Louis _(feedback sent 8/30- MM)_
- [x] Sioux City _(feedback sent 8/31-this location will need more time to add service details and CAP images - MM)_
- [x] Quad Cities _(feedback sent 8/31- MM)_
Reviews requested 8/23
- [x] Evanston Vet Center _(feedback sent 8/31- MM)_
- [x] Chicago Vet Center _(feedback sent 8/31- almost ready for final review- MM)_ **_This one is ready for final review and approval - MM 9/1_** 
Reviews requested 8/24
- [x] Rapid City, SD Vet Center _(requested during office hours - feedback sent 8/24 - MM)_
- [x] Hatillo (revisions and feedback sent in April and May, second round revisions from MZ requested 8/21)
Reviews requested 8/29
- [x] Chicago Heights _(feedback sent 8/31- MM)_
Reviews requested 8/30
- [x] Madison _(feedback sent 8/31- MM)_
Reviews requested 8/31
- [x] Kansas City _(feedback sent 8/31- MM)_
Reviews requested 9/1
- [x] St. Paul _(feedback sent 9/6- MM)_
- [x] Wichita  _(feedback sent 9/6- MM)_
- [x] Pontiac _(feedback sent 9/8- MM)_
- [x] Macomb County _(feedback sent 9/8- MM)_
- [x] Orland Park _(feedback sent 9/8- MM)_
- [x] Cleveland _(feedback sent 9/8- MM)_
- [x] Metro East _(feedback sent 9/9- MM)_
Reviews requested 9/2
- [x] Bismarck _(feedback sent 9/9- MM)_
- [x] Stark County _(feedback sent 9/9- MM)_
- [x] Lincoln _(feedback sent 9/9 and 9/16 - MM)_
- [x] Columbus, OH _(feedback sent 9/12- MM)_
- [x] Gary area _(feedback sent 9/12- MM)_
Reviews requested 9/6
- [x] La Crosse _(feedback sent 9/12- MM)_
- [x] Dayton _( no local content or images has been added 9/12- MM)_
Reviews requested 9/8
- [x] Des Moines _(feedback sent 9/12- MM)_
Second reviews requested 
- [x] Evansville, IN requested 8/31 and again 9/6) _(feedback sent 9/12- MM)_
- [x] South Bend, IN requested 9/1 **_This one is ready for final review and approval - MM 9/1_**
- [x] San Juan, requested 9/1  
Reviews requested 9/13
- [x] Lakeland  _(feedback sent 9/14- MM)_
Reviews requested 10/7
- [x] Green Bay _(feedback sent 10/7- MM)_
</details>

### District 4
- [x] Houston West
- [x] Denver
- [x] Pueblo (revisions sent in May) (sent to Tiffany for final sign off + 1 question) 
- [x] Abilene

**Comment by megzehn** [comment]
Remaining Vet Centers that haven't been published 

### District 2

- [x] Ocala (ready to publish but holding bc CAPS that are archived are still displaying (8/23/22)
- [ ] Tampa Vet Center (MZ sent follow up feedback on 9/3
- [x] Marietta (ready to publish except holding bc of archives CAPS still showing as of 9/20) 
- [ ] Mobile _(feedback sent 8/19 - MM)_
- [ ] Pompano Beach _(feedback sent 8/19, met 9/23, more feedback sent 9/27 - MM)_
- [ ] Johnson City  _(feedback sent 8/19 - MM)_
- [ ] Louisville _(feedback sent 8/22 - MM)_
- [ ] Fort Lauderdale _(feedback sent 8/22 - MM, sent again by MZ on 9/5)_
- [ ] Melbourne Vet Center _(reached out to offer assistance 8/22 - MM)_ 
        - has new VOPS - Tiffany provided overview of resources and workbooks, etc on 8/24
- [ ] Naples Vet Center _(reached out to offer assistance 8/22, feedback sent 8/23 - MM)_
- [ ] Clearwater Vet Center _(feedback sent 8/22 - MM)_
- [ ] Tallahassee Vet Center  _(feedback sent 8/24- MM)_
- [ ] San Juan Vet Center _(feedback sent 8/24- MM)_
- [ ] Jacksonville Vet Center _(feedback sent 8/25- MM)_

### District 3
<details>
<summary> Requested reviews and feedback sent </summary>

- [ ] Cedar Rapids _(feedback sent 8/30- MM)_
- [ ] Springfield, IL  _(feedback sent 8/30- MM)_
- [ ] Evansville, IN _(feedback sent 8/30- MM)_
- [ ] St. Louis _(feedback sent 8/30- MM)_
- [ ] Sioux City _(feedback sent 8/31-this location will need more time to add service details and CAP images - MM)_
- [ ] Quad Cities _(feedback sent 8/31- MM)_
Reviews requested 8/23
- [ ] Evanston Vet Center _(feedback sent 8/31- MM)_
-  [ ] Chicago Vet Center _(feedback sent 8/31- almost ready for final review- MM)_ **_This one is ready for final review and approval - MM 9/1_** 
Reviews requested 8/24
- [ ] Rapid City, SD Vet Center _(requested during office hours - feedback sent 8/24 - MM)_(MZ sent more requests on 9.21)
- [ ] Chicago Heights _(feedback sent 8/31- MM)_
Reviews requested 8/30
- [ ] Kansas City _(feedback sent 8/31- MM)_
- [ ] St. Paul _(feedback sent 9/6- MM)_
- [ ] Wichita  _(feedback sent 9/6- MM)_
- [ ] Pontiac _(feedback sent 9/8- MM)_
- [ ] Macomb County _(feedback sent 9/8- MM)_
- [ ] Orland Park _(feedback sent 9/8- MM)_
- [ ] Cleveland _(feedback sent 9/8- MM)_
- [ ] Metro East _(feedback sent 9/9- MM)_
Reviews requested 9/2
- [x] Bismarck _(feedback sent 9/9- MM)_
- [ ] Stark County _(feedback sent 9/9- MM)_
- [ ] Lincoln _(feedback sent 9/9 and 9/16 - MM)_
- [ ] Columbus, OH _(feedback sent 9/12- MM)_
- [ ] Gary area _(feedback sent 9/12- MM)_
Reviews requested 9/6
- [ ] La Crosse _(feedback sent 9/12- MM)_
- [ ] Dayton _( no local content or images has been added 9/12- MM)_
Reviews requested 9/8
- [ ] Des Moines _(feedback sent 9/12- MM)_
Second reviews requested 
- [ ] San Juan, requested 9/1  
Reviews requested 9/13
- [ ] Lakeland  _(feedback sent 9/14- MM)_
Reviews requested 10/7
- [ ] Green Bay _(feedback sent 10/7- MM)_
</details>

**Comment by RLHecht** [comment]
Closing this ticket. Created a new one with the remaining District 2 and 3 Vet Centers to track #48037
