### ISSUE TITLE
Move Platform website data and analytics to shared space in Confluence

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#45689]
**User story:**

As a Platform team,
I want to see the most updated and least updated pages on the Platform website,
To better understand which content is being engaged with vs at risk of becoming old content and stale.

**Acceptance criteria:**

- [x] Create new page called "Platform Website Data and Analytics" under the "Platform Website Guidelines" section in Confluence: https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines

- [x] From main page, create an intro paragraph that explains the DOMO dashboard and link to it: https://va-gov.domo.com/page/1182586883

- [x] Move 6 new Confluence dashboards to this new "Platform Website Data and Analytics" section as well: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2308636673/Platform+Website+Edits+Volume+Getting+Started

**Comment by amygoldman** [comment]
Update 9/19:

- Link to new page: https://vfs.atlassian.net/wiki/spaces/AP/pages/2372141343/Platform+website+data+and+analytics
- Subpages moved to new section
- Still working on intro paragraph
