### ISSUE TITLE
[Feature Request [Spanish]: Memorable Date Component Translation

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#45682]
### Describe the problem

As the check-in team was communicating with the State Department about translations of the memorable date component, they let us know that...

The "Required" message in Spanish for the new Memorable Date Design System component needs to be changed to "Requerida" (i.e. feminine since "Fecha" is feminine)."

Other portions of the DS memorable date component are not translated into Spanish yet as well. This ticket is to handle the Spanish language changes needed to the Memorable Date component.

[Slack thread with the initial discussion](https://dsva.slack.com/archives/C01DBGX4P45/p1660236756190719)

### Who will benefit

Any Veteran utilizing Spanish translation.

### Describe your idea

See the problem description section

### Provide evidence

See the problem description section.

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [X] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [ ] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by k80bowman** [comment]
We submitted a request for translations for this component from the State Department on July 18th. We are still waiting for those to come back. As soon as they do, we will add the Spanish language translations for this component.

**Comment by jamigibbs** [comment]
After reviewing this request, our team has determined that the translation of "required" should be based on the text "required field" and not "required date" which would mean it should remain as "Requerido":

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1292#issuecomment-1304080720

**Comment by steel36** [comment]
Moved to Done since ticket was completed.
