### ISSUE TITLE
Adding Vicki Linscombe-Coleman to DSVA Slack

### ISSUE THREAD

**Issue by vickilinscombe-coleman** [department-of-veterans-affairs/va.gov-team#45697]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?
- dsva.slack.com

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
I am the Program Manager for the VRE PSES Contract which will be supporting Veteran Facing Education Products.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add vicki.linscombe-coleman@va.gov as a single-channel guest to dsva.slack.com.
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@vickilinscombe-coleman need to know what channel specifically please!

**Comment by vickilinscombe-coleman** [comment]
Hello
Can you add dsva.slack.com?

It is the information I was provided by the VA PM.
Vicki

Vicki L-Coleman, (Contractor) PMP
GovernmentCIO, Portfolio Director
***@***.******@***.***>
***@***.******@***.***>
512.285.0857

From: Lacey Higley ***@***.***>
Sent: Wednesday, August 24, 2022 2:03 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Linscombe-Coleman, Vicki V. (GovernmentCIO) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding Vicki Linscombe-Coleman to DSVA Slack (Issue #45697)


@vickilinscombe-coleman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvickilinscombe-coleman&data=05%7C01%7C%7Cd3f4195377584d7f5bfe08da86035a6c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637969646200365034%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mhWq0X3WSjZHCouXV4wF1%2BlwzHxdMmSTCpG%2Bz2DVKK0%3D&reserved=0> need to know what channel specifically please!

-

**Comment by LEHigley** [comment]
@vickilinscombe-coleman  dsva.slack.com is the entire workspace--if i am adding them as a single channel guest i need to know a specific channel within the workspace to add them to

**Comment by vickilinscombe-coleman** [comment]
Lacey
Thanks for that clarity.  I will try to get some specificity for the team.
Vicki

Vicki L-Coleman, (Contractor) PMP
GovernmentCIO, Portfolio Director
***@***.******@***.***>
***@***.******@***.***>
512.285.0857

From: Lacey Higley ***@***.***>
Sent: Wednesday, August 24, 2022 2:26 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Linscombe-Coleman, Vicki V. (GovernmentCIO) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding Vicki Linscombe-Coleman to DSVA Slack (Issue #45697)


@vickilinscombe-coleman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvickilinscombe-coleman&data=05%7C01%7C%7C338dde82e5ed4b1db29a08da860674c9%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637969659527180716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=igpx1Pd9IlxfuNCRr%2B52%2ByDbf%2BMoHBI74t3jOaRE3pc%3D&reserved=0> dsva.slack.com is the entire workspace--if i am adding them as a single channel guest i need to know a specific channel within the workspace to add them to

-

**Comment by LEHigley** [comment]
still not sure what to do here..

**Comment by LEHigley** [comment]
closing this--have not gotten the info necessary to add the team member
