### ISSUE TITLE
Adding [Kate Buker] to DSVA Slack

### ISSUE THREAD

**Issue by LucianaAlexanderMorais** [department-of-veterans-affairs/va.gov-team#45698]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Verified - no account
<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Single - guest. Kate Buker is the business-side (VEO) project lead for the new VoiceBot team. She needs access to va-voicebot-public and va-voicebot-team so that we can collaborate across related teams. 
Email: kate.buker@va.gov

Thank you!

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@LucianaAlexanderMorais for some reason it wouldn't let me send--just want to confirm this is the right email address?

**Comment by eunicegar** [comment]
Invite sent.
