### ISSUE TITLE
New Slack group request "@cms-qa-engineers"

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#45690]
# Description

**new slack group request**: @cms-qa-engineers
- to include clarence.maeng@agile6.com, and nathan.douglas@agile6.com
- default channel = #sitewide-cms

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by ndouglas** [comment]
Anything I can do to move this along?

**Comment by ndouglas** [comment]
@LEHigley @KevinMHoffmanUSDS Is it possible to get this done this week?  Is there any other information I need to provide?

**Comment by LEHigley** [comment]
sorry for the delay--this is done
