### ISSUE TITLE
Caution Flag Search Results: Alert Language Updates / DEPO Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4569]
Work with DEPO Content team to refine labels / language

**Comment by amyknox** [comment]
@desireeturner - this story will carry over to sprint 41

**Comment by amyknox** [comment]
@peggygannon the content attached to this story is for the Caution Flags on the GI Bill Comparison Tool. Our goal is to deter students from visiting the profiles of, and ultimately attending, schools with cautionary warnings. 

The spreadsheet shows the various components of the updated alert messages.
(Annotated screens to come)

Sample Prototype Screens (text is FPO)
Search Results https://bahdigital.invisionapp.com/share/AGIACXL4ZJB#/screens/296032064
Profile Page  https://bahdigital.invisionapp.com/share/AGIACXL4ZJB#/screens/296032066[https://app.zenhub.com/files/133843125/abd69aa5-0f46-4f09-91cc-6d0b675fbb6b/download](https://app.zenhub.com/files/133843125/abd69aa5-0f46-4f09-91cc-6d0b675fbb6b/download)

**Comment by ccruzgra** [comment]
@peggygannon Here is a visual to guide for content placement in the search results and school profiles, and from where in the excel alert doc they are sourced.

From github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/design/caution-flags/content/GIBCT-Caution-Flag-Content-Placement-Guidance.pdf

**Comment by peggygannon** [comment]
@amyknox hello! can you tell me the difference between when the caution language from Col A would be used vs. Col B. They both seem like "header" copy.

**Comment by amyknox** [comment]
@peggygannon 
Any School or Campus Closing Caution flags use A & B on the search results page; on the profile page, B & C are used in both the Institution summary and the Cautionary information accordion. 

All non-closing (less critical) alerts use A on the search results page and in the Institution summary and B & C in the Cautionary information accordion. 

The visual that Cindy dropped in helps make sense of what appears where.

**Comment by peggygannon** [comment]
Hello, here is the Excel spreadsheet with my recommendations in red. 

 I have a few followup questions below on some of the language in the caution flag warnings. 

for this warning: 
*Assigned receiver has motioned court for an emergency closure of campus. This campus may close.*

Who are we referring to as the "assigned receiver"? is that the student? 

for this warning:
*There may be a potential loss of program approval for this school.*

Loss of approval from what agency? The dept of Edu or VA? or both? 


[https://app.zenhub.com/files/133843125/dbefce52-95b2-4563-854b-07cf738a6f94/download](https://app.zenhub.com/files/133843125/dbefce52-95b2-4563-854b-07cf738a6f94/download)

**Comment by amyknox** [comment]
Thanks @peggygannon. We'll incorporate your edits.  Also, need to confirm with Edu on those questions. I"ll let you know what we find out.
