### ISSUE TITLE
AWS access for Jerek Shoemaker

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#45708]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Jerek

### Your Email

jerek.shoemaker@adhocteam.us

### Team, Role, and Company of the target individual

Benefits, Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

I'm currently working on the **LGY: Certificate of Eligibility** application with @scottymeyers which sits behind a proxy. I need to be able to access requests on staging to debug issues with requests made to this service.

### Access Expiration

ongoing

### Additional Notes

COR - Keith Riley
VOR - Jeff Langworthy

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
@jerekshoe  is listed on the VFS Team Roster.

**For AWS ACCESS**
User: Jerek Shoemaker
COR: Keith Riley
VOR: Jeff Langworthy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by samcoforma** [comment]
@mchelen-gov Just so we can update the status of our sprint goals, do you have an idea of how long the AWS access approval process typically takes? (I asked this on another ticket just now as well) Thanks!

**Comment by mchelen-gov** [comment]
EQIP transmittal date confirmed ✅

**Comment by jbritt1** [comment]
First-time login credentials provided to user at this time.

**Comment by jerekshoe** [comment]
Hey @oseasmoran73 I'm in the same boat as @kylesoskin and @data-doge and would also like AWS parameter store access. Thanks!

**Comment by td-usds** [comment]
Is this about being added to the `dsva-vfs-developers` group? Can I get an explicit affirmation of this?

**Comment by oseasmoran73** [comment]
That is correct. Users under `dsva-vfs-developers` will have access to param store for vets-api

**Comment by td-usds** [comment]
requested access (cf https://github.com/department-of-veterans-affairs/va.gov-team/issues/45708#issuecomment-1302103829) approved

**Comment by oseasmoran73** [comment]
Policy applied. Closing ticket
