### ISSUE TITLE
Analytics Implementation or QA Support for [Check-in Experience - Language Toggle]

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#45701]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Check-in Experience
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [pre-check-in](https://www.va.gov/health-care/appointment-pre-check-in)
    - [check-in](https://www.va.gov/health-care/appointment-check-in)
    
- **When is the launch date?**
    - Already launched

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - Event tracking for when the language toggle is used

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jonathan-epstein13** [comment]
@brianseek the following is the toggle for the pre-check in and the check-in page. Just want to confirm.
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/e395702c-6c8c-49b2-ae04-87e5f81fd106) 

You and your team would like tracking for toggling (clicking) between English and Espanol?

**Comment by brianseek** [comment]
@jonathan-epstein13 Yep that is the one. I set up some events in code already that use the `recordEvent` function from the platform tools that send events like this:
`{event: check-in-language-switch-es}`
Where the last part of that string is the language that is being toggled to. Also not shown currently, but we are also planing to have Tagalog in the near future. So the options would be: en, es, and tl.
Let me know if you have any other questions.
Thanks!

**Comment by benbrasso-agile6** [comment]
@jonathan-epstein13 What's the category, action and label values for the examples that you referenced? And, how much control would we or do we (i.e., the check in team) have in changing those values so we can find them easily and pull them into our CIE GA Custom Dashboard?

**Comment by jonathan-epstein13** [comment]
event_category: Interactions
event_action: Navigation - Pipe Delimited - es - https://www.va.gov/resources/the-pact-act-and-your-va-benefits-esp 
event_label: nav-pipe-delimited-list-click

Above is the example I sent of what is being tracked. 

If you and your team can put in the same code for your language toggle, then we can QA it and see if it is being tracked on our end in GTM.
To add it to your dashboard (generally, it would be found under the events report in GA), but to add it into your dashboard, I believe you can add a filter by `event_action`

Let me know if this makes sense and I'll see what else I can send over that might help explain better.

**Comment by benbrasso-agile6** [comment]
@brianseek make sense? Also, we're scheduled to speak to Jonathan this afternoon at office hours.

**Comment by michelle-dooley** [comment]
Closing this ticket based on our all last week.  Please reach out if there is anything else we can help with.
