### ISSUE TITLE
STEM Wizard: Interview Synthesis

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4571]
- [x] Consolidate UX Findings & Recommendations
- [x] Consolidate relevant findings from other parties
- [ ] Identify Recommendations & Future Enhancements

**Comment by amyknox** [comment]
Mural board for synthesis https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1578085758227/ffa456d1551536247697c713c6d92734db40d61e
