### ISSUE TITLE
Content review from Authenticated Experience, 1095-B teams

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#45727]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
We need content reviewed for a confirmation email that will be triggered by someone updating their paperless delivery setting in VA.gov profile notification settings

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
   
## When do you expect to launch your product to 100% of users?
  
December 2022
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Product outline for Auth Exp team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/1095B-preference)
- [Email content to be reviewed](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/identity-personalization/notifications/notification-preferences/1095B-preference/content/confirmation-email.md)
- For reference: [draft of emails provided by 1095-B team](https://docs.google.com/document/d/1MPHuzvp1DT3PhEtytjzj9Exi9scSOoMJUaPZ_ogu07E/edit#heading=h.odgy0vbyzw0v) (see the Paperless Confirmation section, v1 and v2 emails. The rest of the emails in the doc are out of scope for the Auth Exp team)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
We'll review in our content meeting on 8/16

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Sharon Kasimow
-	Designer: Liz Lantz
-	FE engineer: n/a, going through VA notiffy
-	Product/team Slack channel: accountexp-authexp, cedar-1095b, va-notify-public

**Comment by SKasimow** [comment]
Hi @andaleliz - can we update this ticket to "yes" since it will be going through the Collab cycle? I'm going to add it to the "umbrella" Collab cycle ticket for this effort.

**Comment by andaleliz** [comment]
@SKasimow yes we can! I'm going to close this though, since Danielle and I completed this review earlier this week.
