### ISSUE TITLE
STEM Wizard: Compile Session Notes

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4572]
Compile session notes
Identify top findings
Upload notes to GitHub Research folder

Uploaded interview notes to Github:
- [x] TM 
- [x] AK 
- [ ] CC

Session notes online here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/stem/research/wizard-update/discovery-phase/session-notes

**Comment by amyknox** [comment]
Mural board for notes 
https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1578085758227/ffa456d1551536247697c713c6d92734db40d61e
