### ISSUE TITLE
Analytics KPI dashboard request for Lighthouse VA Forms API Team

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#45752]
# Request ADJUSTMENT to existing KPI Dashboard for find a search

Hi. i'm a Product Manager in the Lighthouse api program. One of the APIs we support is the VA Forms API which is used by the find a form feature on va.gov. I used to use this dashboard to monitor the search refinement rate (hoping to drive it down by some changes that several systems made). The refinement rate widget is no longer working. can you help? 

https://user-images.githubusercontent.com/78039252/184915727-096452cf-38de-4e4d-a988-59ca4aa48d20.png

### Expected delivery timelines

Whenever you can get to it, we pull metrics each month a few days after month closes. 

## Instructions for the VFS team
all other info on this existing form search dashboard is great/fine as is...just the missing widget i'm looking for help with

**Comment by michelle-dooley** [comment]
@NCHLiberty - Thank you for your submission, we will take a look at get back to you with timing.  It will likely not be until our next sprint starting 9/1.  Thanks. Michelle

**Comment by johnny-jesensky-adhoc** [comment]
Closing as part of analytics backlog review.
