### ISSUE TITLE
BE - My VA - Onsite Notifications - Readiness Review

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#45766]
## Background
Placeholder for https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/547.

**Comment by tpharrison** [comment]
@ericasauv09 @ajakabcin 

I added a link under the "Artifacts" to the technical document.  This is what I've normally done for other reviews in the past.  Let me know if you have any questions.

**Comment by ericasauv09** [comment]
Thank you @tpharrison the documentation looks great! However, there are a few questions within the privacy ticket that I dont see covered in your documentation including the questions related to cookies and the questions about the code base. Unless I missed it in your document would you be able to help us answer those questions as well? I am assuming I need to answer all that before I can submit it to the privacy team.

**Comment by tpharrison** [comment]
@ericasauv09 I supplied some answers and added a few more links to specific sections of the technical document.  Based on my experience with previous readiness reviews, I think this is okay to submit at this point and get feedback.

**Comment by ericasauv09** [comment]
great, thank you so much @tpharrison !
