### ISSUE TITLE
Confirm that Decision Review features still work

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#45762]
Review Decision Review functionality to make sure everything still works since decision_review.url and decision_review.v1.url have been updated in vets-api by  @madebydna 

Links for context:

- https://dsva.slack.com/archives/C5AGLBNRK/p1660264508343569
- https://docs.google.com/spreadsheets/d/111t6f4V3eCVkaKoBIxXi54_HlkPT-54qKShfRjl-iMs/
- https://github.com/department-of-veterans-affairs/devops/pull/11780

**Comment by kylesoskin** [comment]
Hi @samcoforma  just to confirm, you have this deployed in staging/sandbox, and just would like us to submit some claims (one of each type) and confirm it submits successfully?

**Comment by madebydna** [comment]
@kylesoskin, yes, this was deployed in dev and staging and the only thing we need is to test out that the settings change didn't affect the flow of claims submissions.

**Comment by kylesoskin** [comment]
Thanks @madebydna, I will confirm with my team how to test this and get back to you with the results.

**Comment by kylesoskin** [comment]
Hi @madebydna, I have tested in stage and it seems like it successfully was able to submit.
![Screen Shot 2022-08-29 at 9 52 13 AM](https://user-images.githubusercontent.com/37049625/187217158-0d9c17f2-d293-48b4-a5c1-dda0485f5
![Screen Shot 2022-08-29 at 9 52 41 AM](https://user-images.githubusercontent.com/37049625/187217258-7b0239ec-320f-4dde-a193-5b7873bf997f.png)
53f.png)
 
 So it SEEMS that it worked, but I would like to check one more thing before locking in my answer.

**Comment by kylesoskin** [comment]
HLR (which hits lighthouse) submitted and seems to be working fine
![image](https://user-images.githubusercontent.com/37049625/187229610-377b127e-b778-4443-a7a0-fbaeaad4afa2.png)


Form 526 (from previous comment, hits EVSS), after some investigation also was successful (at hitting EVSS, died for other unrelated issues, but hit and got a respsonce from EVSS) 

Let me know if this is sufficient.

Thanks!

**Comment by madebydna** [comment]
@kylesoskin thanks so much for doing this. Your tests seem very thorough and definitely sufficient. I will close this issue and make the equivalent change in production. I will tag you in the PR for awareness.
