### ISSUE TITLE
AWS access for Kyle Soskin

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#45799]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Kyle Soskin

### Your Email

kyle.soskin@adhocteam.us

### Team, Role, and Company of the target individual

Benefits Team #1, Back-end Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Sade Ragsdale, sade.ragsdale@va.gov

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

I have transferred teams and would like to have the following memberships added if possible. 

I am now on the VA Benefits team and will be making features and bugfixes, along with investigating issues, to the `vets-api` and `vets-website` repos. 

I need access to debug and investigate issues in those environments, and also need all permissions needed to  develop on the platform. 

Access requested should be ongoing as issues that need resolved/debugged could come and go at anytime. 

As far as I know I need at minimum:
```
group_memberships = ["dsva-vagov-developers", "force-MFA"]
```

Also, if possible `"adhoc-vetsgov-ssm-prod"` access would allow me to better troubleshoot prod errors, and is access granted for the person I am replacing, however I know prod access is not often given out. 

### Access Expiration

ongoing

### Additional Notes

COR - Keith Riley
VOR - Jeff Langworthy

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by mleclerc00** [comment]
listed on the VFS Team Roster.

**For AWS ACCESS**
User: Kyle Soskin
COR: Keith Riley
VOR: Jeff Langworthy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by td-usds** [comment]
Requested access approved

**Comment by jbritt1** [comment]
Approved access granted.

**Comment by kylesoskin** [comment]
Hey @oseasmoran73 , can I get some of that aws parameter store access as well? I had access before, on my old team.... but it looks like it has since been revoked. I should have the same as what you just granted to @data-doge

https://github.com/department-of-veterans-affairs/va.gov-team/issues/46302
https://github.com/department-of-veterans-affairs/devops/pull/12181
^ same as that. but add to me, I think 😄 

No rush, dont need it any time soon!

**Comment by td-usds** [comment]
Requested access granted

**Comment by oseasmoran73** [comment]
Policy applied. Closing ticket
