### ISSUE TITLE
[Analytics] Education Analytics MVP - Iterate for Access & Thresholds

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#458]
## User Story
As a Product decision maker, I need accessibility to the analytics dashboard so I can easily access readable data and incorporate it into my product decision making workflow.

## Goal
Translate the iterated Product Health Prototype from Google Sheets to Data Studio or create process for VA members to be able to access the Google Sheets prototype.

## Acceptance Criteria
- [ ] Set up the updated MVP as an Education Product Health Tool:
    Include:
    - [x] All Education Products
    - [x] Current GA metrics
    - [x] Updated glossary and tool tips
    - [ ] Updated thresholds (Show time comparisons)
    - [ ] Available Foresee metrics
~- [ ] Make MVP accessible for VA owners~ ON HOLD
- [ ] Review Design
- [ ] Share with Team

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic**
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** 
- [x] **Labeled with Type**

**Comment by joanneesteban** [comment]
RE: https://github.com/department-of-veterans-affairs/va.gov-team/issues/406

> @amycesal @joanneesteban I stood up this sample Data Studio report filtering a table on events that end in `submission` or `failure` in the Education View:
> 
> https://datastudio.google.com/reporting/1Cz1NlnmW69ZVBQOYq8hRBuDQcQVvBDsv/page/ogmt/edit
> 
> _Pros:_
> 
> * More powerful visualizations than Google Sheets
> * No cost
> * Can be accessed by VA (Will confirm with test link)
> * Links directly to GA data, Google Sheets, and BigQuery
> 
> _Limitations/Next steps:_
> 
> * Will have to think through approach blending GA and non-GA Data to recreate the original table in the Education MVP
> * Recreating success and failure rates as we have them in GA Sheets (Calculated metrics is possible but possibly limited by how Data Studio filters event labels)

**Comment by joanneesteban** [comment]
@nedierecel is there a way to show traffic spikes or bounce rates? It looks like those are a couple of the missing analytics from user research that we might be able to add/that isn't uncaptured 
[Research Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/June%202019:%20Education%20Product%20Health%20Dashboard%20MVP/Results-Summary.md)

**Comment by joanneesteban** [comment]
Edited the AC: Make MVP accessible for VA owners is now ON HOLD

**Comment by nedierecel** [comment]
@joanneesteban We can pull trendlines to show traffic spikes or declines if we pull in a longer timeframe and then decide if we want to see by day or week.

Re: bounce rates, in lieu of each form's introduction page, it may serve us to look at the top 10 landing pages and review bounce rate.

**Comment by joanneesteban** [comment]
@nedierecel Thanks for the info! How long would that longer time frame be and what is the effort level on that? Would we be able to add that in this sprint?

**Comment by joanneesteban** [comment]
@amycesal Updated the glossary to reflect the terms you reworked on the monthly and weekly tabs. Given our pivot, unless there's something else to iterate, I'd consider this done.
