### ISSUE TITLE
Update Display of Type of Care for HSRM Sending Treating Specialty for Type of Care for Upcoming CC Appointments 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#45809]
## Description
After the BE changes were deployed [VAOSR-4178](https://issues.mobilehealth.va.gov/browse/VAOSR-4178) to SQA environment the SQA team was able to validate the changes. HSRM is now returning "ccTreatingSpecialty" attribute in the response body for an upcoming CC appointment. 

As per the discussion on the Scrum of Scrum call the FE will display the exactly data returned on the "ccTreatingSpecialty" and they won't be any data transformations. 

## Steps to Reproduce
**VAOS:**
- Login to VAOS as a test user (grethel.g.petryniec@id.me)
- Enter a CC request with Type of care - Podiatry
- Fill in the required information and submit a CC request
- Validate on the Pending appointment page if the information displays as per the fields entered during creating the request. Now head over to HSRM application.

**HSRM:**
- Login to HSRM as a staff and validate if the newly entered request displays under task list
- Click on the new “VAOS Veteran request” and validate the information has been propagated correctly from VAOS
- Change the status to "In progress" and update the task. Now head over to CPRS.

**CPRS:**
- Login to CPRS and create a new consult
- Go through the steps of CTB and fill-in the required fields
- Copy UCID from the consult and now head over to HSRM application. Now head over to HSRM application.

**HSRM:**
- Add the CC# value and update the task
- Do a referral search by using the UCID and select the approved referral
- Enter the NPI value associated with the task and do a PPMS search
- Select the appropriate provider from the list
- Enter all the required information on the “Record Appointment” page and update the referral. Now head over to VAOS application

**VAOS:**
- Validate on VAOS the newly created CC appointment displays under upcoming list and VAOS UI will display "ccTreatingSpecialty" field as it shows in the response  

## Acceptance Criteria
TBD 

### Design Assets
TBD

## Definition of Done
TBD

**Comment by aarathi-poldass** [comment]
@ldelacosta Can you please assign this ticket to the developer for further analysis. @simiadebowale

**Comment by ldelacosta** [comment]
Hey @aarathi-poldass aarathi-poldass I'll create a story to handle this type of work on the FE side. The type of care label is already been created for CC appts. It's the data that needs to be pass through on the FE page.

**Comment by ldelacosta** [comment]
Ticket #46903 was created for the work. We plan to review the ticket during Backlog Refinement 09/14.

**Comment by marcynadeau** [comment]
@ldelacosta  Just a quick heads up until Aarathi has time to update the ticket. Tested and passed with existing requests. Waiting on HSRM fix in Staging to test with newly entered requests This is the JIRA ticket for the HSRM Staging issues. https://issues.mobilehealth.va.gov/browse/VAOSR-4454 (VAOS Staging: 502 error while creating CC request in VAOS)

**Comment by aarathi-poldass** [comment]
@ldelacosta Here are the scenarios that were tested today. I was able to test with multiple test user and different specialty types:

**Scenario 1:** Validate the "Treatment Specialty" is displaying on already existing CC appointments (Upcoming, Past and Cancelled queues) - **PASS**
**Scenario 2:** Enter a CC request in VAOS and process the request with the required specialty and validate the flow - Can't test due to HSRM issue
**Scenario 3:**  Enter a CC request in VAOS and process the request with a different specialty and validate the flow - Can't test due to HSRM issue 
**Scenario 4:** Schedule a CC appointment using a pre-existing referral - **PASS** 
**Scenario 5:** Change the Treatment specialty on a pre-existing referral and validate the flow - **PASS**
**Scenario 6:** Schedule CC appointment with max/ specials character "Treatment Specialty" - **PASS** 

Please note we are waiting on the HSRM side to resolve the issue. There were some recent code changes in the IPE environment which are triggering the error. Thomas is working with the HSRM team. 

Please find the screenshots from my testing today for reference. 
![Optometry](https://user-images.githubusercontent.com/69315717/192375658-0b93ae8b-0c8c-4a1c-a874-af17bf7a4e64.png)
![max/specials character](https://user-images.githubusercontent.com/69315717/192375795-3a478f6c-d163-4ff5-a6c0-1d6aad3dac93.png)

**Comment by aarathi-poldass** [comment]
After [VAOSR-4454](https://issues.mobilehealth.va.gov/browse/VAOSR-4454) was fixed by the HSRM team, We were able to test 2 remaining scenarios from the above Comment:  
**Scenario 1:** Enter a CC request in VAOS and process the request with the required specialty and validate the flow - **PASS**
**Scenario 2:** Enter a CC request in VAOS and process the request with a different specialty and validate the flow - **PASS**

@ldelacosta this passes testing. No issues to report. please close the ticket. Thank you!

**Comment by JRRoof** [comment]
Closing ticket.  All scenarios passed.
