### ISSUE TITLE
STEM Wizard: Research Plan (prototype)

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4582]
Draft initial research plan

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/research/wizard-update/prototype-phase/prototype-research-plan.md

**Comment by tmcmurdo** [comment]
Created Research Plan
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/research/wizard-update/prototype-phase/prototype-research-plan.md
