### ISSUE TITLE
SOCKS access for [Matthew Burnett]

### ISSUE THREAD

**Issue by Mburnett-VA** [department-of-veterans-affairs/va.gov-team#45844]
### Your Name

Matthew Burnett

### Your Email

burnett_matthew@bah.com

### Your Role and Team

Product Manager

### Product Manager (PM) name and email

Matthew Burnett burnett_matthew@bah.com

### Product Owner (PO) name and email

premal shah premal.shah@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC80kBivu4mz2eNoIS2vy3FDi2V2k0+qYuQL49zhwZYf3AyR5wn2qHCX8iOiAe2Zm86q0smdK8cJ5JlBHAQiiTMQkkloaZTSSguoqC0Sam1hlurRO++mj5YTJ2f+H1tbf2UM32/92oVMAhXLTb4gyT0rrK+f/quzI6rTC0Fxlin0zuQ1x6E/4EnZlB/33pTfHWThHS6FNZH9R/xc0UMR1ALeEcPaTna1VcpD0VyGCMK3yRCW+QgCpJIA+QVVw1+9oSJxOhpxIgD5VblEq92lNzdVitRJsSU4j3zFBmuufOLM14RxxK+bFw1B+s+YWJH4eX0ULtXqzeA9aWDPvHGYQopxPlddftaSrQ80GT3NLtLEMHXwfRgF4cufDS59FNjRx74wlmy+8fyKuMD5HYO+n070w4MJJ3lt71uEsslVdNRQSJUzXl3nJWJv5wGaOtpLvYoc7vAkdMs4KRVxoeohVOohZG9GqGffkEgHKt7LuAg2h5szVUaqoMFHpe+ZI3J1OE= matt@LoweBurnett

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by Mburnett-VA** [comment]
Orientation is complete; please let me know if you need anything for socks access.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
