### ISSUE TITLE
Analytics KPI dashboard request for 1095-B

### ISSUE THREAD

**Issue by khandelwal** [department-of-veterans-affairs/va.gov-team#45846]
# Request a New Standardized KPI Dashboard

## Instructions for the VFS team
In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

*NOTE: If you do not have Google access, you can download an Excel version of the template [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f).*

- [X] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [X] Complete worksheet as instructed
- [X] Link your completed spreadsheet here: [Spreadsheet](https://docs.google.com/spreadsheets/d/1XsZCXfrdYjTgyV2N55GmR-CBsXSvQZgIcYQ663W53Qw/edit#gid=0)
- [X] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

Related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/44810#issuecomment-1215709721

**Comment by michelle-dooley** [comment]
@khandelwal - thank you for your submission.  We will review and plan to get added to our upcoming sprint starting on 9/1.  If we can get to it sooner we will do so.

**Comment by michelle-dooley** [comment]
@khandelwal - per my note in #44810 I'm going to closet this ticket as I do not think this dashboard will provide what you need.  As mentioned in the other ticket please reachout when the url is live and we can help you get the metrics you need from GA.
