### ISSUE TITLE
SOCKS access for Pat Siebenlist

### ISSUE THREAD

**Issue by PSIEBENLIST** [department-of-veterans-affairs/va.gov-team#45848]
### Your Name

Pat Siebenlist

### Your Email

Pat.Siebenlist@adhocteam.us

### Your Role and Team

Sr Product Manager on Console UI

### Product Manager (PM) name and email

Lee Helmer, Lee.Helmer@adhocteam.us

### Product Owner (PO) name and email

Michael Chelen michael.chelen@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgqBd1rrIzmAnYJV/+ugMSZOi99s37CAoXaE5GrJqpI5KYTLqmTVuqoIGODHzXmwD9uriPrreZBhFii8zMW+YBZSW5CmZA6SyWo+TxvkImyRhiu55E6bdVR1CjygDq/ZvLrEKOFVqI6qEr8oJwTkVUxz01LDeNIGn2QSOG1XXZnaiQ0Xk4ir1bSdpqCAsBkcRnn6DcVHF7zSq6xH8rHiXj+bNohzjufeKijo2tMS+y+s7xr0faUmkpJajwrd9notMUxhmsPcN4aDxUJl4F8oWtx/qpUeXtUnr+7ej41pnSBSwkhsfffeIwPNbQlrFbF0qYXWrGYm02vZ2crm6FA6RJFnY9U3cqLcngS/pXGkRXvTdLs9938K3KMamnoLJ4I3ZF3tZU28VimzhL/TvtO/bvn98/eXN09QxtlB+Y0T3B1dZfLO5sA4EBvAad1IA3/nS9jmH5cyPV9EYBZt/9eMGKk93LQzLl8uQRGs/CAbSRG71cVeskLd0iHKgQX1xVYX0= patsiebenlist@MR1002s-MBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by PSIEBENLIST** [comment]
Can this not be completed until I am added to VFS roster?

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
