### ISSUE TITLE
Additional Product directory-related documents

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#45853]
Edit 3 Product directory-related documents for clarity and plain language

https://vfs.atlassian.net/wiki/spaces/TTT/pages/2311946314/VFS+Product+Directory+Term+Glossary

https://vfs.atlassian.net/wiki/spaces/TTT/pages/2194374767/VFS+Product+Directory+-+User+Guide

https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VFS+Product+Directory+-+Platform+Documentation

**Comment by laucon** [comment]
I have edited all these documents. I want to wait for a response from Peter and Joe and Ryan. I'm not sure where they intend to publish these docs outside Confluence, if anywhere outside Confluence. But I have given them both edits and comments. :)

**Comment by laucon** [comment]
They're figuring out where to publish the 3 docs and they're not quite ready to publish the product directory yet.

**Comment by laucon** [comment]
Some of it was published correctly today. Some of it was published today with some errors. And a few are going to stay on confluence.

**Comment by laucon** [comment]
Now completely finished. We took care of the issues that Amy correctly pointed out and fixed the other docs problems. :)

**Comment by vbellissimo** [comment]
Troubleshooting with QA Standards team on whether VFS products list will pull/update from Git Hub everyday from now on.
