### ISSUE TITLE
Scenario Run Through

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#45850]
Let's self-review our docs before having a peer review them!

Roles:
- Matt King: Receiving Platform Team Member
- Kevin Duensing: (Understudy) Receiving Platform Team Member, Primary Note Taker
- Carl Alquisola: Observer, Secondary Note Taker
- Ritesh Patel: Observer, Secondary Note Taker 

Scenarios:
- [x] New client integration
- [x] Can't sign in to the Console
- [ ] Need to redeploy Keycloak
- [ ] There's a bug in the post-validation
- [ ] Need to add extra validation to the onboarding automation

**Comment by girldadmk** [comment]
This is bomb! Great idea @kjduensing.

**Comment by kjduensing** [comment]
I have a list of 7 so far - what are y'all's thoughts? https://vfs.atlassian.net/wiki/spaces/AMT/pages/2218098691/Operational+Documentation
