### ISSUE TITLE
OOB Deploy Request for content-build

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#45854]
# Instructions
Fill out Details of need and the PRs related to OOB sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy
 https://github.com/department-of-veterans-affairs/content-build/pull/1265

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
    anyone looking for info on PACT Act materials
   150/day
## Has fix been confirmed in Staging?
- [x] Yes
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
 Related issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10312

Short version.  A missing `}{` that has been in place for over 3 years was causing a lot of improperly filtered results to be returned which exceeded the limit of 10,000 results and resulted in new "[outreach materials](https://www.va.gov/outreach-and-events/outreach-materials/)" from  showing all of the 179 items it should be showing.  Instead it is showing 164.   Several time sensitive PACT Act items are among the missing.
   
## Verify The following
 - [x] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [x] The OOB Deploy Requests is critial and must be resolved before the next automated deploy.  As declared by product owner

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests
 - [x] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by mchelen-gov** [comment]
@swirtSJW Please check GA for daily number of visitors to https://www.va.gov/outreach-and-events/outreach-materials/
