### ISSUE TITLE
Create more granular COVID status messages for VA facilities

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#45855]
## Issue Description
Sitewide Facilities would like content support to create more granular COVID status messages – these would replace the current High, Medium, Low facility status messages. See [intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45774) for more info.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by dsinla** [comment]
Additional Info: Currently the Facility status field would host this new messaging. The Facility status field has a character limit, and is plain text only.
