### ISSUE TITLE
Follow up with Console UI about adding Console content to website

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#45887]
Acceptance criteria:

- [x] Reach out to Console UI team to offer help with Console related documentation for the Platform website; Some things to consider/offer:
- Do they need help editing or finishing the content?
- Where in the IA will it live? Most of it might be under "Getting Started", but review either way
- Do they need help adding to the website to get it ready for deployment?

**Comment by vbellissimo** [comment]
Drafted content:
https://vfs.atlassian.net/wiki/spaces/PWD/pages/2308931631/Platform+Console

Console team's strategy:
https://vfs.atlassian.net/wiki/spaces/CUI/pages/2344681473/Strategy+to+facilitate+user+entry+to+Console

**Comment by laucon** [comment]
I added a ton of corrections to the document for grammar and clarity. I feel like I could add another bunch of comments that to make it better even if the grammar is correct (like getting rid of passive voice and using less future tense and making headers look better), but I wanted to focus on really glaring errors for now.

**Comment by laucon** [comment]
I fixed it. :)
