### ISSUE TITLE
Design | Profile | Notification Preferences | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45891]
## Background

Audit and update the Notification Preferences documentation in Github.

## Tasks
**Create the following**
- [x] user flow
- [x] use cases

## Acceptance Criteria
- [x] PM and PO review
- [x] Tasks completed

**Comment by andaleliz** [comment]
@SKasimow do you want to make a separate ticket for yourself to do the audit/product outline part of this? I'll take care of the use cases and user flow docs (estimate reflects just those things).

**Comment by andaleliz** [comment]
@SKasimow I've completed the [user flow](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8zKwxQ); might be helpful in your audit.

**Comment by SKasimow** [comment]
@andaleliz - my ticket is #45099 and planned for Sprint 81.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss and @SKasimow - I think I've captured [all the current use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/use-cases/README.md), and these docs are ready for your review. 

Let me know if there are any other use cases you can think of.

One thing to note - I linked to the staging test cases doc, but I didn't check each use case to make sure they are accurate. I think that'll be part of the audit work covered in #45099.

**Comment by Samara-Strauss** [comment]
### [User wants to update notification settings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/use-cases/update-settings.md)

- I clarified that people see all preferences with the exception of healthcare, which shows conditionally.

Otherwise, this is all great! Thank you so much!!

**Comment by andaleliz** [comment]
Thanks @Samara-Strauss! I appreciate your review, and you going in and making that clarification. I'll close this out :)

**Comment by SKasimow** [comment]
@andaleliz - I'm going through the use cases now; can you provide a mock that reflects a screen with healthcare notification not showing?
