### ISSUE TITLE
[Discovery] 10-10EZ - Next of Kin

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#45890]
Currently, there are several fields for *Next of Kin* listed on the 10-10EZ paper application.  It's been requested that we add the same, or similar, functionality to the online application.

We've already confirmed with the Enrollment System team that this information can be accepted, but will need to be tested prior to release.

At the time we created this ticket, we were also asked to hold until they determined it to be necessary. It was brought up again in a recent stakeholder meeting, and we further explained that we want to be sure we are asking what is absolutely necessary to enroll into health care (citing Paper Reduction Act as support)

**Comment by hdjustice** [comment]
At the time we created this ticket, we were also asked to hold until they determined it to be necessary.  It was brought up again in a recent stakeholder meeting, and we further explained that we want to be sure we are asking what is absolutely necessary to enroll into health care (citing Paper Reduction Act as support)

**Comment by hdjustice** [comment]
Per PO Patrick Bateman today - Next of Kin and Emergency Contact work will be done by MHV Cartography team (Slack post below)

> Patrick Bateman  9:37 AM
> @ Tom Anderson
> @ Alex Seelig
>  @ Emily Brown
>  @ Lynne Johnson
>  i’ve decided that the mhv cartography team will take on the emergency contact / NOK work in collaboration with the the authenticated exp team. i will make sure the 1010 team and our HEC stakeholders are looped in as needed. cc 
> @ Kristen McConnell
> @ Samara (She/Her)
