### ISSUE TITLE
SOCKS access for Ioan Dobrescu

### ISSUE THREAD

**Issue by IoanDobrescuAFS** [department-of-veterans-affairs/va.gov-team#45899]
### Your Name

Ioan Dobrescu

### Your Email

Ioan.Dobrescu@va.gov

### Your Role and Team

ASA

### Product Manager (PM) name and email

Riley Ross riley.ross@va.gov

### Product Owner (PO) name and email

Riley Ross riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCp9R8EbsZD4SZup/YdvTv+jzTXbPPDeGJ5mh878hgKxqKX7PTVUf5V8nnDcz7KTzJNAswv42J2M+GwCSJd9gcw9Zt4/PqV+E6uKTXZtCWADgXPwxHKSaLcv6deUeVgpd34T7vMA5ntsh/p2BL/COt42BlHUjAF4a4YBPjqnQPgfNdhg+yWqki6xMHKmoQ3Z7XDoAJZFfYuYrqJfg6n5sWV/hf3mXeDyNE4Wq40b+0O5J70jja5mztzul4ejfRmROZhNSpjwBfyzVfzlYPuGBp75Vc6WSOsNV6GXTf6SAmofXtmbyBOh39QdnkwPrVJHviFUdTuM7sWzIBOLHrf/VHv32bWICl15HrqhV72j7kWVi2DKL8cFuTsrOGA4gO2Yrw6hrWlnhmKoNkWVvM5pymm4doVPNdiqYnFFFhLE5LJz5ECALZJG7IFr6IozZmfsnO1FhzbENeIDy+hMsrddZ3IjhhPobAKOgbKZuZ0WneBArWFyDRFYH8aMFxrBN6m1Dk= idobrescu@AFSWW0ROOQ0O4G

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
