### ISSUE TITLE
Adding [@VelascoKatherine] to DSVA Slack

### ISSUE THREAD

**Issue by VelascoKatherine** [department-of-veterans-affairs/va.gov-team#45894]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting to be added to slack.

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

new user requests: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

##Katherine Velasco is a new analyst on the Digital GI Bill. They will be assisting with analytics. Please add [[b-katherine.velasco@accenturefederal.com](mailto:b-katherine.velasco@accenturefederal.com) as a multi-channel guest to these channels: #vfs-platform-support , #vfs-all-teams, and any channel specifically for google analytics (they will also be requesting access shortly)

We aim to complete slack requests within 24hrs.
Thank you so much!

**Comment by alexander-ferzola** [comment]
@eunicegar / @LEHigley  any updates on this thread? :)

**Comment by LEHigley** [comment]
@alexander-ferzola we can add to specific channels but we don't have awareness of all slack channels to be able to confidently add to all google analytics ones. in the future providing the specific channel names is the best way to get folks added to all the right places. 

also quick q--is the email address actually b-katherine.velasco@accenturefederal.com or is the "b-" a typo?

**Comment by alexander-ferzola** [comment]
@LEHigley  the b- is correct and #vfs-platform-support should suffice for analytics! Thank you!!
