### ISSUE TITLE
Adding [Tuan-ba] to DSVA Slack

### ISSUE THREAD

**Issue by tuan-ba** [department-of-veterans-affairs/va.gov-team#45893]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<Tuan Ba is a new analyst on the Digital GI Bill. They will be assisting with analytics. Please add b-tuan.ba@accenturefederal.com as a multi-channel guest to these channels: #vfs-platform-support , #vfs-all-teams, and any channel specifically for google analytics (they will also be requesting access shortly)

We aim to complete slack requests within 24hrs
Thank you so much!>

Are you requesting to add an individual as a:

- Multi-channel

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Tuan is a business analyst for the Digital GI Bill and will be creating reports and dashboards.

We aim to complete slack requests within 24hrs.

**Comment by alexander-ferzola** [comment]
@eunicegar  / @LEHigley  any updates on this thread? :)

**Comment by LEHigley** [comment]
@alexander-ferzola same comment here--need specific channels and want to confirm whether or not we need the "b-" at the start of the email address. thanks

**Comment by alexander-ferzola** [comment]
@LEHigley  the b- is correct and #vfs-platform-support should suffice for analytics! Thank you!!
