### ISSUE TITLE
SOCKS access for [Norman Knolhoff]

### ISSUE THREAD

**Issue by normanknolhoff** [department-of-veterans-affairs/va.gov-team#45897]
### Your Name

Norman Knolhoff

### Your Email

norman.knolhoff@va.gov

### Your Role and Team

ASA

### Product Manager (PM) name and email

riley.ross@va.gov

### Product Owner (PO) name and email

riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDm1KdWdAZ5X/jpncdYEK2FOsIWxBoyAWzxklscq4Qvnfn8h4Fyn0na3HiUC4jOGALJJWgLcSokbAPGgNn7kbnFmfxHMuBsvvbzXJvDguk1iVwOCxI1jQGPEIuu+4BtJl+u0//BE1s1Y12o4fjrRgta+l9KMx3538U82kaHgi0MpuUaDiKzNLhKRR1Anmcx6Xj5prNAWgNGttKd6/tH10VYTYTgzndQrCsEIO/RO165ilVbuqDo7EYC90Pls/PUo7B/o5NYBnwc6ipzoabhNc+1FEpppF7Iq5pC0GoTQv/RkU/OHFrR/C6VKzZwvtA9j6VHaceV8CiKpJOFXRKTrt9qe+meQ6zVqnKSqOVG4hXJvRv+ikTAODmtdic+okwczmacK31WJHGFBU+2z8KcUJ7WZ3hzkKDozOgHFubN3GtG090xT1LfM/fYIx73089vqINbZUIDYNgddBl7Vndpj/3ffOjprxQY3ZTivzXG0bJhsKOz40q/sLnXa5ai2BLp/A0= nknolhoff@AFSWWNSXVPS5I6

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
