### ISSUE TITLE
[Discovery] Evaluate ability to retrieve historical analytics data from ForeSee

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#459]
## User Story
As a Product Owner, I need to have automatic, regular, and easy to consume Foresee analytics updates in order to use user-centric data regularly as a part of my workflow.

## Discovery Question
Can we pull real-time data that shows weekly and monthly analytics and display it somewhere for edu stakeholder to access?

## Constraints/Assumptions
- We can pull the data programmatically

## Acceptance Criteria
- [ ] Determine which data points will need to be pulled (Insights)
- [ ] Discovery has been conducted
- [ ] A readout of findings is documented
- [ ] If we can pull the data from Foresee, update the Google Sheets MVP so that it populates the fields automatically from Foresee weekly and monthly

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rianfowler** [comment]
Foresee has two export APIs worth looking into:

[CX Measure Export API Documentation](https://developer.foresee.com/docs/public-api)
[Feedback Export API Documentation](https://developer.foresee.com/docs/feedback-export-api)

**Comment by joanneesteban** [comment]
Data Points for Education:

Custom Question:
- What Education and Training information or services were you lookin for today?
    - [ ] Check Post-9/11 GI Bill benefits
    - [ ] Apply for GI Bill benefits
    - [ ] Other
    - [ ] Change your current education benefits
    - [ ] View payment history
    - [ ] Compare GI Bill benefits by school
  ^data points captured: Responses % & CSAT Score

- Which category best describes the kind of information or services you were primarily looking for today?
    - [ ] Education and Training
  ^data points captured: Responses % & CSAT Score

CC: @amycesal - These are the only Education related Foresee data points that I found.

**Comment by rianfowler** [comment]
## Responses 

The [project data api](https://developer.foresee.com/docs/feedback-export-api#section-project-data) returns the responses to each survey:
```
{
    "hasMore": false,
    "total": 6,
    "items": [
        {
            "id": "0Nolkwodoghkp5BtF948kA4C",
            "responseTime": "2018-10-09T19:42:29Z",
            "rating": 2,
            "topic": "Topic One",
            "url": "https://survey-dev.foresee.com/f/yFeS5ZdxAL",
            "response": [
                {
                    "id": "XIA0046271",
                    "type": "CQ",
                    "answers": [
                        "2"
                    ]
                },
                {
                    "id": "XIA0046272",
                    "type": "CQ",
                    "answers": [
                        "Site is too slow"
                    ]
                },
                {
                    "id": "device_version",
                    "type": "CPP",
                    "answers": [
                        "Chrome"
                    ]
                },
                {
                    "id": "os",
                    "type": "CPP",
                    "answers": [
                        "Windows 10"
                    ]
                }
         }
 }
```

- this could fulfill the "Response" part of the data points needed to be captured 
- this api could be used in conjunction with the  [projects](https://developer.foresee.com/docs/feedback-export-api#section-projects) and [project definition](https://developer.foresee.com/docs/feedback-export-api#section-project-definition) apis. 

## CSAT Score 

the [measure data](https://developer.foresee.com/docs/public-api#section-measure-data) api returns information on each of the client's measures.

```
{
  "hasMore": true,
  "total": 5227,
  "items": [
    {
      "id": "ABC2013234486504",
      "responseTime": "2013-08-01T04:14:00.000Z",
      "latentScores": [
        {
          "id": "M003703L0002",
          "name": "Product Images",
          "type": "ELEMENTS",
          "score": 87.81034
        }
      ],
      "responses": [
        {
          "id": "ENM003703Q00100",
          "name": "Please rate the number of clicks to get where you want on this site.",
          "phrase": "Please rate the number of clicks to get where you want on this site.",
          "type": "MQ",
          "answers": [
            "9"
          ]
        }
      ]
    }
  ]
}

```

- didn't see something called "CSAT score" in the documentation but the CX measure data looks like it's similar? 
- the "latent scores" in the example above is described as " A Latent is group of questions which focus on a particular aspect of the subject being measured. For example, the Look and Feel latent score of a web site is derived from responses to questions concerning the visual aspect, or appearance, of the user interface, such as color scheme or font size." - not sure if we're leveraging this as part of our surveys 

## Notes

- to make public api calls we will need to obtain a [OAuth2 Access Token](https://developer.foresee.com/docs/using-the-public-api#section-invoking-oauth-calls) and follow the OAuth2 Client Credentials Flow laid out in the documentation. Don't fully understand the [capabilities](https://developers.google.com/apps-script/guides/client-verification) of script.google.com to know if we can do OAuth2 authentication there. 
- suggest matching the capture structure as closely to foresee as possible- changing the structure or aggregating the response data should be done by data miners?

**Comment by andreahewitt-odd** [comment]
@joanneesteban Is this work you still plan on doing or can it be closed? Or should this ticket be changed to finish the export of 2018 and 2017?

**Comment by joanneesteban** [comment]
Will repurpose this ticket to finish the export of 2017-2019 ForeSee data.

**Comment by joanneesteban** [comment]
Work for ForeSee has been changed. Ice-boxing and have open tickets/will open tickets about retrieving ForeSee data as necessary.
