### ISSUE TITLE
Content and IA check from VA Benefits Team 1

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#45908]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
  
We are working on a new feature that allows Veterans to download their Decision Letters from VA.gov, as opposed to having to wait for a physical copy in the mail. After chatting with @Allison Christman and @Jim Ryan (jimuhh in GitHub), the idea is to add a subsection to Records to house these Notification Letters. This new section would serve as a repository for various VA communication, but most importantly the Decision Letters themselves, which the Veteran would be able to download to their device. 
  
## Supporting artifacts

- Link to product outline: [Feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST_%20Download%20Decision%20Letter%20Feature%20Brief%20-%20Draft.docx), [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product%20Outline%20-%20Draft.docx) 
- Link to or attach user flows:
- Link to prototype or mockups: [Prototype](https://sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/a/xrJyeYl/play)
- Link to any epics/issues that may be helpful: 

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits Team 1
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
-	FE engineer: Jerek Shoemaker
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laurwill** [comment]
Hi @skylerschain ! 

Since we have limited time before testing, we'd like to make some suggestions for labels to start, and additional feedback on the Notification letters page as time allows. 

Will your team have time to make label changes ahead of testing, if we can get those over to you by midweek next week?
After testing, we can plan to do a more complete content review of new/updated pages.

In the meantime, we had a couple questions about the "notification letters" label: 
- Is this a term that you've already found is familiar to Veterans, or is this a question you have for testing? Wondering if we can suggest an alternative here, since "notification" is a long word and not clearly related to claims/appeals.
- What specific types of letters would appear on this page besides decision letters?

Thank you!

**Comment by mnorthuis** [comment]
Initial IA work for reference.  We can update and finalize this after research once we know the final approach and labeling for everything. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ben1-letters.md

**Comment by laurwill** [comment]
Hi @skylerschain ! Here's the final copy for testing (for the Download VA letters, Your VA claim letters, and Your compensation claim pages in the Sketch file). We went with "Claim letters" for the label for now, and of course can update this after research, or talk more about that label. Let me know if you'd like to discuss anything!

[Notification.letters.content.review.9.9.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9537653/Notification.letters.content.review.9.9.22.docx)

**Comment by RLHecht** [comment]
@skylerschain Let me know if this is good to close. Thanks!

**Comment by laurwill** [comment]
Hi @skylerschain ,
Thanks for updating us on the testing findings — as we chatted, I've tried some adjustments to the content to move Claim letters higher on the page. If it still isn't prominent enough, we could add the "on this page" element to help people navigate, but you can see how it looks first.

I also removed the "how do I download" text about Adobe, since it seems that I can download and view regular PDFs from the site using other programs. I'd still like to figure out the right team to confirm this with, before we officially make this change — I'll follow up on that next week. I also moved the info about address changes into a separate section under the 2 main letter sections. 

See what you think of this update! I'm out for the rest of the day, but I'd be happy to look again next week. 

[Notification.letters.content.review.9.30.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9685060/Notification.letters.content.review.9.30.docx)

**Comment by laurwill** [comment]
Hi @skylerschain @mnorthuis ,
We were making updates to the [Download VA benefit letters](https://www.va.gov/records/download-va-letters/) page and remembered that we had planned an entry point for the new download decision letters feature here. The decision letter feature is now live in the Check your claim status tool. Should we move forward with the entry point work in this ticket, or has this plan changed?

@mnorthuis , a couple related IA questions:
- We have an [ticket](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/55062) to add links to the new COE and education benefit letters tools here. Just want to confirm, these should be links and not entry points? 
- Back in September we were planning to change the H1 of this page to remove "benefit" and be more general for "VA letters". But does the launch of the education letters tool change the approach for labeling here? 

cc @bethpotts

**Comment by skylerschain** [comment]
Hi @laurwill. I'm OK leaving this as is for now. I know there are some other letters features being developed, and to me it makes sense to consider the broader whole before linking specifically to claim letters from here. We feel confident Veterans are finding claim letters via CST without much difficulty, based on our usage metrics.

**Comment by mnorthuis** [comment]
@laurwill Based on the research done, we aren't ready to broaden this letters feature, so we should keep the existing title and keep it focused on benefit award letters or certificates.  The claim status letter is a decision, and the education letters are also decision letters, not something that needs to be presented as proof of benefit.   

So here's what I believe we need to do on the existing download letters page
- We should add information to the "Which types of letters can I get" section to be more clear on what is available.  A list can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/c3d525f9b0b2c73c54211cc63777b023046163b4/products/benefit-letters
- The home loans COE is a benefit letter, so this should be referenced on the page in the main content.  I could see this being placed under the "Which types of letters can I get" heading, indicating that the COE is available separately.  
- The claim status and education letters could be added to the "More information" box at the bottom

**Comment by laurwill** [comment]
Thank you both for the info! We'll open a ticket to make the changes Mikki suggested here. cc @RLHecht

**Comment by mnorthuis** [comment]
Updates for download benefit letters documented in issue [#55711 ](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/55711)

Work for this issue is complete.  Closing ticket.
