### ISSUE TITLE
[Bug] VA Profile - Contact Info - Error-message styling anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#45905]
## What happened?
On Staging Profile > Contact Information page, the system error message icon did not match mockup.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: Any test-user between 121-126. [See [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for passwords.]

## Steps to Reproduce
- URL: https://staging.va.gov/profile/contact-information
- Test User _(if applicable)_: [see **Specs** above]
- In **Address** > **Mailing**, click **Edit** button.
- Take machine offline.
- Click **Update** button.
- In **error-alert**, observe that the **icon** is black informational.

### Screenshot

[Example from MacOS Safari]
![image](https://user-images.githubusercontent.com/587583/185453593-82e87fab-ab8c-4e2c-b255-e11f9d9bcd78.png)

## Desired styling
- [ ] Icon should be red exclamation.

### Screenshot

From [this mockup](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/eK0eRyp):
![image](https://user-images.githubusercontent.com/587583/185454507-f3320b20-868a-46e6-85ba-4f6217c31bb9.png)

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - can you let me know if this is a simple update I can add to current sprint or should I add to Sprint 81?

**Comment by SKasimow** [comment]
@cgednalske - can you confirm the exclamation point noted in the ticket should be in red?

**Comment by SKasimow** [comment]
@adamwhitlock1 - I won't put this into current sprint but know you said you might be able to address before sprint ends.

**Comment by cgednalske** [comment]
(If still needed) -- confirming the exclamation point should be red 👍  ([Design System source](https://design.va.gov/components/alert))

**Comment by SKasimow** [comment]
Tested in staging:
![Screen Shot 2022-08-31 at 3 24 13 PM](https://user-images.githubusercontent.com/74627978/187765199-5ab26f5e-34b8-4673-93ef-0c7fd4f3aaf6.png)

Closing....
