### ISSUE TITLE
SOCKS access for [Labiba Hanif]

### ISSUE THREAD

**Issue by LabHanif** [department-of-veterans-affairs/va.gov-team#45900]
### Your Name

Labiba Hanif

### Your Email

labiba.hanif@va.gov

### Your Role and Team

ASA 

### Product Manager (PM) name and email

Riley Ross and Riley.ross@va.gov

### Product Owner (PO) name and email

Riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChykhuKpS8rEiyd7MRfn8+YITMYZ5u9Zpdm10HAdpceqWXacaSxO8lzz5HMT8oXI4kzH7i0tiundwpv4kFAHpkXEu1kFBCCG1LDbMyfhwiDRrJ1vFXO8QTZRMR6k4j0j/OOBtv5Wi2ueBGoEbHOvhYER0Jj/w6nI1K6aaGzCgkIB08MSvT0jeW/Wo14ItwvysETjULmWn85+3B84ksslqOtNSo68oPVyCDhdmImWHykoUDdEnhW6fjWK+NpoBP7oy2pojCblIpG6tFmP+eJtIx73nhw2SVdNE2Tg45l9rAQTLMKjsgBtnlGOsslIHtPbm2pIPsj1yO0Qxo/DwpjYq1TUiNMdYXv9tR+YhCiWF8riEBfhyOT/Sork/kbMWT0Ru8m3Xndt79UoSb7foZnnpPMuedWZB93k9TXTvXWV37n5wZgmYIzY2+1HwbFIYf9oVXHdkOSw0J3yAIu3MkpjitNpyEIddE/SdyBNhuTjpphli1eBM4C7iOHlZn3F7m67k= lhanif@AFSWWMG9764LE1

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
