### ISSUE TITLE
SOCKS access for [ Robin Bell ]

### ISSUE THREAD

**Issue by rvbell** [department-of-veterans-affairs/va.gov-team#45901]
### Your Name

Robin Bell

### Your Email

robin.bell1@va.gov

### Your Role and Team

ASA

### Product Manager (PM) name and email

Riley Ross

### Product Owner (PO) name and email

riley.ross@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyAxCEivqdaLTP26+ZviEOV8y7IVlA0oUgl029mYFwEoxHii1BEu2vsXxYswmZOXhinkM8EpOV5f5EUirYz9avNqavwiR5tFWnklZjkDOsyZk4k1FG2KTusT/6/irkX2ZMPp26/oPitTzUgrgUAH0Sx9nVfdUMTGXH7+7pTg1J2Nruek1jZ8D3tVCrKGwXQ2PSQC4SnAXM2fuaenhr/HHUcdRClJafRWMPx1VAhlYeEUSwj1bxwoLu6D7zpM9kSFTvSa22c2HhAX+uz/SEDAh4iq0k253SXIKu9kts3A43j9yhwDVdJ/qcTgwMbBeA95iX+gL6Nt7oQQN+WscajcrfuqQB7iPrfuVe/WIgo0c3XDD/G08z6m+boDH43qzdPm7wauLYV5pXRXTxVZl4hdMyJDZ541/cOKDWnsWyc0CvssbyupZrnM3S/2kZKed8clVIgj9zAXqVp30xTqlU/4P0c7KHHiAqLOD91QCRsCtDHbsn9MkF0Dzs+nt2ZmaaxIk= rvbell@BT8Y0F3

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
