### ISSUE TITLE
Access for Ben Shyong

### ISSUE THREAD

**Issue by bshyong** [department-of-veterans-affairs/va.gov-team#4592]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
Dan Navarra

- Please provide your name.
   Ben Shyong
- Please provide the name of your team, your role on that team, and the name of the company you work for.
Pension Automation team; Engineer, Ad Hoc LLC.    

- [if requesting SSH key authorization] What is the **public** SSH key? 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu2lYQ8T8LvouXFOvjVfzHcJnPm+UpbhRFZyM+/x4LEZbSQS/H2hLDefBJpemJlkHwpa0KulF2Bu+lGxbmyP9MiObQRevWIah4jUWet1PLF2Kj3EnDBusvKLKZjaXx/1j0bxk88vg2GIIQBXDHxWf2pTLMEq89RQNHHfWebU6J5o7KTvyXHffx41Eu+nvzu6/1aMueeNTZzQz6DFyBNlqOptzLJ7+ntCgbUeDfAoS4xgjE2TOL+X2xOvfVvHFd7dlqiLI6L7FcmMZr+H3MUzlmP3itWItqnE+C95AerHq2zggwIFbwO07tVjsBpCB5rG4zarLJOLBW8+WBCTA3Vit7 bshyong@bs-MacBook-Pro
```

- [Grant AWS Console access?]

  - YES
  -  Need VA network access to access staging/dev instances within VAEC. This access is needed to verify and debug integrations with BIP Claims API and other BIP services

**Comment by bshyong** [comment]
ping @department-of-veterans-affairs/vsp-operations for visibility

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Michael Domanski
User: Dan Shank

**Comment by bshyong** [comment]
@tskinn following up on this; is there any other information I should provide for this ticket?

**Comment by bshyong** [comment]
[EDIT] our COR on the contract should be Dan Navarra

**Comment by anushyaprasad** [comment]
@tskinn is there any other information needed from Ben to expedite this? The lack of this access is blocking further developmental efforts.

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for SOCKS and AWS.

**Comment by tskinn** [comment]
You should have socks and aws access now. Reach out in slack if you have any issues.
