### ISSUE TITLE
Content Review - Request and Community Care Flow from VAOS - VA Online Scheduling

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#45948]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?

We anticipate to launch the update in December 2022.  

  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/cc-request-flow.md)
- Link to or attach user flows: [Community Care flow](https://www.figma.com/file/gXTBycqX9KlFmiSqoQr3jD/Content-Review---CC-and-Request-Flow), [Request Appointment flow ](https://www.figma.com/file/gXTBycqX9KlFmiSqoQr3jD/Content-Review---CC-and-Request-Flow?node-id=160%3A36368)
- [Updated screens for all flows](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=0%3A1)
- Link to prototype or mockups: N/A
- Link to any epics/issues that may be helpful: N/A

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: December 2022
- Estimated staging review date: November 2022
- Content and IA work needed by: October 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VAOS (VA Online Scheduling) 
-	OCTO-DE product owner: Lauren Alexanderson, Katherine Lawyer, Patrick Bateman, Stephen Barrs, Mark Dewey
-	Product manager: Leah De La Costa and Jeff Roof 
-	Designer: Peter Russo and Ciera Maddox
-	FE engineer: Simi Adebowale 
-	Product/team Slack channel: #vaos-team 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by ldelacosta** [comment]
Hello, please feel free to add comments in the Figma file.

**Comment by RLHecht** [comment]
@ldelacosta I can't access the Figma files you have linked above. Could you update the permissions? Thanks!

**Comment by ldelacosta** [comment]
@Cieramaddox - When you have a chance, can you give access to Danielle and Randi?

**Comment by outerpress** [comment]
@RLHecht could you check again? I'm able to access it in an incognito window. If it gives you an error message, could you post a screenshot? It'll help me troubleshoot. Thanks!

**Comment by RLHecht** [comment]
@ldelacosta Wanted to drop a note here that we are working on this. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @outerpress! I dropped a bunch of thoughts/questions/suggestions in Figma. Let me know if you and the team want to jump on a call to talk through and brainstorm more together after you have time to review. Thanks!

**Comment by outerpress** [comment]
Hi @DanielleThierryUSDSVA [here are the updated screens](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=0%3A1), I updated a couple of things we talked about today. If you could take one more pass just in case I missed anything I'd appreciate it - thanks!

**Comment by laurwill** [comment]
@outerpress can we close out this (very old) ticket? Anything else needed here? Thanks!

**Comment by outerpress** [comment]
@laurwill yes! The content work is done. The changes are still slowly working its way up to our devs so we might reach out separately with questions when we hit implementation.

**Comment by laurwill** [comment]
Great, thank you!
