### ISSUE TITLE
Analytics Implementation or QA Support for [Facilities - Custom report(s)]

### ISSUE THREAD

**Issue by jonathan-epstein13** [department-of-veterans-affairs/va.gov-team#45941]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [`check`] Google Analytics implementation

     - [ ] QA

- **Who is this request for?**

    - [Facilities Team, for David Shannon - from Office hours 8/18/22.]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)] - will insert from Office hours 8/18 recording.
    - URLs containing health-care/locations or contact-us/
- **When is the launch date?**
    - [NA]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_

    - [QR code - (as an entrance)***if possible]
    - [entrance pages for all locations for the specific URLs]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jonathan-epstein13** [comment]
Hello @dsinla I've attached a [report ](https://analytics.google.com/analytics/web/#/my-reports/XchYhCKcQvGn9U42KTsFaA/a50123418w177519031p176188361/_u.date00=20220807&_u.date01=20220813/)in regards to the walk-thru from office hours on 8/18. I've used the regex `health-care/locations/` as a start. Let me know if this looks good and if there are any specific URLs, I can try to include them. I am trying to possibly do the work around we discussed:
ie: www.va.gov/*/locations/*

I'll post any other findings here and feel free to add to the ticket what you would like to see.

**Comment by dsinla** [comment]
Thanks so much @jonathan-epstein13.  I followed your instructions but I get to a report that displays: _There is no data for this view._

I want to make sure I successfully expressed my request from the office hours. I poked around a bit more after our meeting and I think I can express it like this:

_Show the previous page for all events where a user has arrived at the anchor link: contact-us/#support-for-law-enforcement-an?_ 

In this screenshot report I can see the source (previous page) for all folks who arrived on the contact-us page for Wilmington Health Center. 
![image](https://user-images.githubusercontent.com/62269210/186044249-ed884459-7c55-470b-a40a-bba766660ba6.png)

Can we do the same for the anchor link ` https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an`. Is a source (previous page) possible for an anchor link?  I would look at those source/medium of _direct/none_ as a pretty good estimate of folks who arrived via the QR code.

Then as a next step, can we expand this report to account for all contact-us pages across all facilities by leverage some type regex filter as you have proposed?

If you have some time happy to hop on a quick call so we're both looking at the same thing.

**Comment by jonathan-epstein13** [comment]
@dsinla lets see if we can set some time aside for us to meet and make sure we are looking at the same thing. When's best for you? I'll delve into this more based on your request and send over another report.

**Comment by jonathan-epstein13** [comment]
@dsinla Here is some other reports below I pulled that might help as well. 

Update: I am trying to create that regex to account for all contact-pages and facilities, but hasn't worked on my end yet.


[Previous page report ](https://analytics.google.com/analytics/web/template?uid=yGhv1yeuScq8A5lrOoT8Bg)(for entrances/sources_mediums)***
[Top events report](https://analytics.google.com/analytics/web/template?uid=Xr4V0eJJQPa-11vHX7E9XA) (for action links and sources/mediums)***

***Will try to account for all contact-us pages across all facilities

**Comment by jonathan-epstein13** [comment]
From our meeting, we've discovered that we need to see -->How many people landed on the [anchor link](www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an.), instead of landing on the [contact us page](www.va.gov/wilmington-health-care/contact-us) and clicking on the anchor link. 

| Description of Interaction | Screenshot | DataLayer | Tag | Pass / Fail
| -- | -- | -- | -- | -- |
| Clicking on Support for law enforcement...| ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/3dc2e447-0b4c-465a-b931-8f67522a6cb4) | GA event  UA-50123418-16 ec: Interactions ea: Navigation - Jumplink Click - Support for Law Enforcement and First Responders el: nav-jumplink-click | | :green_circle: PASS

The above interaction takes you to the [anchor link](www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an) 

| Description of Interaction | Screenshot | DataLayer | Tag | Pass / Fail
| -- | -- | -- | -- | -- |
| Arriving on the section - Support for law enforcement... | ![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/53dad4be-a5f5-4c6f-8666-3121bcc094e5) | GA event  UA-50123418-16 ec: Interactions ea: wilmington-health-care-contact el: support-for-law-enforcement-viewed |  | :green_circle: PASS

**Comment by jonathan-epstein13** [comment]
I believe a new implementation for the QR code URL (when provided) will need to be connected to the anchor link [URL](http://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an).

**Comment by michelle-dooley** [comment]
This portion of the work is complete.  QR code work will be completed as part of another ticket.
