### ISSUE TITLE
CDW Knowledge Share Session with Patrick

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#45950]
Today at the metrics & analytics meeting, there was some discussion of having a knowledge share meeting for the people who do have CDW access and Patrick so he can show and share queries he's been working on and help people find their way around.

**Comment by loripusey** [comment]
@sarahknoppA6 Can you please set up a meeting for this?

**Comment by loripusey** [comment]
@sarahknoppA6 did we set up a new meeting for  this?

**Comment by loripusey** [comment]
closing as there is no movement on this one
