### ISSUE TITLE
Talk to Platform team to determine how to store Datadog metrics

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#45953]
Per Adrian, we should consider adjusting datadog so that it stores past metrics, as some of our data currently gets wiped out due to lack of retention.

## Questions
- Can we have more than 7 days of DD data so that we can show trends?
    - May need to talk to Platform team to see what is possible

## Tasks
- Talk to Platform team during office hours to see what is possible

**Comment by loripusey** [comment]
too old, closing
