### ISSUE TITLE
Log when users attempt to save "bad" addresses

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4597]
## Summary
We should use Google Analytics to track when a user is told their address is invalid and can't be saved to their profile. This way we can understand how often this happens.

## Details
We currently track when a transaction fails with:

```
recordEvent({
  event: "profile-edit-failure",
  "profile-action": "save-failure",
  "profile-section": analyticsSectionName
});
```

When we add the new address validation flow we should see a sizeable reduction in these save/update failures as many of them were caused by the user entering an address the API deemed invalid.

Perhaps we should send something like this in the event of an address validation error (ie when the user is told that the address they entered is invalid):

```
recordEvent({
  event: "profile-edit-failure",
  "profile-action": "invalid-address",
  "profile-section": analyticsSectionName
});
```

TODO
- [x] get input from analytics on what data to send them and update this ticket

**Comment by erikphansen** [comment]
@nedierecel Can you help us determine which data to send to GA when a user is told they entered an invalid address via the new address validation/suggestion flow? Let me know if you have any questions. Thanks!

**Comment by erikphansen** [comment]
Tagging @Samara-Strauss for awareness.

**Comment by Samara-Strauss** [comment]
Thanks for the tag! Post QA, we should talk about what other metrics we'd like to gather as part of this effort.

**Comment by nedierecel** [comment]
@erikphansen To confirm my understanding, the `save-failure` would only be reserved for backend, not user error. Is this correct? 

The naming convention seems straightforward unless you want to keep the prefix consistent:
- `save-failure-backend`
- `save-failure-invalid-address`

**Comment by erikphansen** [comment]
@nedierecel Correct. We report a save failure when VA Profile/Vet360 fails to make the update.

For this new issue we'd like the track I don't think that using a `save-failure` prefix is ideal because it really isn't a save that failed; with the new address validation flow we're adding they're actually getting blocked from even trying to save the address.

**Comment by Samara-Strauss** [comment]
Just want to make sure I understand this:

- save-failure-backend = when a valid address fails to save
- save-failure-invalid-address = when an address doesn't save because we determined it's invalid

Is this correct?

**Comment by erikphansen** [comment]
And I don't think we should use `save-failure-invalid-address` when a user has been told their address is invalid because it technically didn't fail to save. The save failures we record are based on when we actually sent data to VA Profile and they couldn't save it for some reason.

**Comment by nedierecel** [comment]
Noted - thanks @erikphansen for clarifying the distinction. Let's keep the `save-failure` as-is then as you noted with this definition:

>The save failures we record are based on when we actually sent data to VA Profile and they couldn't save it for some reason

I think this is fine then to use `invalid-address` to denote user error for invalid addresses.

**Comment by erikphansen** [comment]
@nedierecel thanks. We'll proceed with sending analytics data in this format when the validation API tells them their address is invalid:

```
recordEvent({
  event: "profile-edit-failure",
  "profile-action": "invalid-address",
  "profile-section": <analyticsSectionName>
});
```

**Comment by Samara-Strauss** [comment]
This all looks good to me!

**Comment by erikphansen** [comment]
I don't think we need to do this now that it's possible to override "bad" addresses so we shouldn't run into this issue anymore.

**Comment by Samara-Strauss** [comment]
OK, we can close this out. I'll take some time this sprint to figure out what analytics we do need.
