### ISSUE TITLE
[Spike] Determine the LOE for the 508 Audit and 

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#45974]
## Issue Description
_OIT would like to to determine the LOE of completing the 508 Audit request._

---
## Tasks
- [ ] _Please read over the attached documents to determine what is needed to have the Audit reach compliance._

  [https://app.zenhub.com/files/133843125/f4cdc9f7-a9b6-49b0-9ca2-d52911d98c20/download](https://app.zenhub.com/files/133843125/f4cdc9f7-a9b6-49b0-9ca2-d52911d98c20/download)

**Comment by mrblanco1** [comment]
AFS Dev provided a LOE to CT OIT PM Darla van Nieukerk 9/6/2020. The LOE was 2 sprints (4 weeks) including 2 developers & QA testing.
