### ISSUE TITLE
[Spike] Determine the LOE for the 508 Audit and 

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#45975]
## Issue Description
_OIT would like to to determine the LOE of completing the 508 Audit request._

---
## Tasks
- [ ] _Please read over the attached documents to determine what is needed to have the Audit reach compliance._

 [https://app.zenhub.com/files/133843125/f9f001fe-ee86-42d0-9d47-53c9d3f0484e/download](https://app.zenhub.com/files/133843125/f9f001fe-ee86-42d0-9d47-53c9d3f0484e/download)

**Comment by MitchLivingstone** [comment]
A follow up email has been sent to Christopher in the 508 Audit group to determine if they can provide guidance on where the requested audit fixes can be located in the CT and FB tool.

**Comment by mrblanco1** [comment]
AFS Dev came up with the following LOE: 
2 Sprints
2 Devs
