### ISSUE TITLE
SOCKS access for Shoaib A Sheikh

### ISSUE THREAD

**Issue by Shoaib-VA** [department-of-veterans-affairs/va.gov-team#45981]
### Your Name

Shoaib Sheikh

### Your Email

shoaib.sheikh@va.gov

### Your Role and Team

Software Engineer on Lighthouse VA

### Product Manager (PM) name and email

Nichole Harris, Nichole.harris@va.gov

### Product Owner (PO) name and email

Premal Shah, Premal.shah@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAmacSsoH7bE9OTAEvBl7Gm/re0fX+KQHV4Ozuz7KXoc7dxoOBoH2kGxLra8vIPecxLgl/FtoH4I1u8bXRBBtkudRYGWcwFP4Zi0cOGYQJ1P1gSLKY6TwXXC2aXjfWwS9sZcxAgXNGZFGCa8atcdUfYd/6uwl4EI3meITweVhABtUtYMlQnNFn8dQKpQtbGMsYoDCEYclRvy5sP8W+ELw4HRMFGXQE3jjc6qRoQYL6W/FqaZnujqARa/P/r9VfSHt3V21MCPslfZJa7TvEkOjLvQS6aVQvEU9Ha3U/GP6wb99dn2LvIviYRr7nEUnGh65YI+e7U5WSiolAOuuXXkPs8TLhNkNFsLebC5zalGnaM/XNgPcc2rdBOsREPrNWjwYNioTBz2FJKct5VLN8XhUIUWGG7Iml2EZn2YOufgodqYH//3Ju5Sp57lRozZ7Mztf4ILCNFvLuBjfA7xW1+2ipobV6T+kA6Bg04iobcjBNasMbO6k3EVwwVdswpw0Nd+E= shoaibsheikh@FHL9HYXVWJ

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by iriteshp** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
