### ISSUE TITLE
[Story] Review gibct toggles and inventory if they are being used

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#45997]
We are being asked to cleanup feature toggles that belong to our team. Please identify and cleanup feature toggles from the attached list that are NOT being used. 

On this sheet:
https://docs.google.com/spreadsheets/d/1hurIezpOBFoCLN4H3ETmUYM6m4MWCWRZjkrf06tk20s/edit?usp=sharing

Please go through gibct and mark here with "X" if the feature toggle are being used .

https://afs365.sharepoint.com/sites/DGIBillServicesProject/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120005AB5D5300A959E42A2180BFAC5BF4AB2&id=%2Fsites%2FDGIBillServicesProject%2FShared%20Documents%2FLegacy%20AO%2FTeam%203%2FProject%20Planning%2FDaily%20Tasks&viewid=5afa7f3b%2D6c5d%2D4507%2D87f8%2D2970bb6901a1&OR=Teams%2DHL&CT=1661438156019&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MzEwMTAwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D
Please update the comment with all removed toggles for the record.

**Comment by AdamFreemer** [comment]
The only toggle on the linked spreadsheet in the GIDS codebase currently being used is: `gibct_school_ratings`

https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L88

**Comment by MitchLivingstone** [comment]
Completed and closed. Adam will remove the Booz Allen Toggles. Closed 08/29/2022
