### ISSUE TITLE
Review vets-api toggles and inventory if they are being used

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#45996]
We are being asked to cleanup feature toggles that belong to our team. Please identify and cleanup feature toggles from the attached list that are NOT being used. 

On this sheet:`
https://docs.google.com/spreadsheets/d/1hurIezpOBFoCLN4H3ETmUYM6m4MWCWRZjkrf06tk20s/edit?usp=sharing

Please go through vets-api and mark here with "X" if the feature toggle are being used .

Please use the SharePoint link and update on the spread sheet: 

https://afs365.sharepoint.com/sites/DGIBillServicesProject/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120005AB5D5300A959E42A2180BFAC5BF4AB2&id=%2Fsites%2FDGIBillServicesProject%2FShared%20Documents%2FLegacy%20AO%2FTeam%203%2FProject%20Planning%2FDaily%20Tasks&viewid=5afa7f3b%2D6c5d%2D4507%2D87f8%2D2970bb6901a1&OR=Teams%2DHL&CT=1661438156019&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MzEwMTAwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

Please update the comment with all removed toggles for the record.

**Comment by dan-brooking** [comment]
@af-manish The two flags regarding GIBCT appear to still be in use:

gibct_eyb_bottom_sheet
gibct_school_ratings

**Comment by dan-brooking** [comment]
```
cerner_override_463: no
cerner_override_531: no
cerner_override_648: no
cerner_override_653: no
cerner_override_663: no
cerner_override_668: no
cerner_override_687: no
cerner_override_692: no
cerner_override_757: no
check_in_experience_pre_check_in_enabled: yes
covid_volunteer_intake_backend_enabled: yes
gi_sandbox_comparision_tool_toggle: no
show_form_i18n: no
new_va_forms_search: no
va_online_scheduling_facility_selection_v2_2: no
va_online_scheduling: yes
va_online_scheduling_unenrolled_vaccine: no
va_online_scheduling_facilities_service_v2: no
va_online_scheduling_variant_testing: no
yellow_ribbon_mvp_enhancement: no
```

**Comment by MitchLivingstone** [comment]
Only AFS toggles removed and merged. 08/29/2022

**Comment by MitchLivingstone** [comment]
Only AFS toggles removed and merged. 08/29/2022
