### ISSUE TITLE
Review vets-website toggles and inventory if they are being used

### ISSUE THREAD

**Issue by af-manish** [department-of-veterans-affairs/va.gov-team#45995]
We are being asked to cleanup feature toggles that belong to our team. Please identify and cleanup feature toggles from the attached list that are NOT being used. 

On this sheet: 
https://docs.google.com/spreadsheets/d/1hurIezpOBFoCLN4H3ETmUYM6m4MWCWRZjkrf06tk20s/edit?usp=sharing

Please go through vets-website and mark here with "X" if the feature toggle are being used .

**Please use the SharePoint link and update on the spread sheet:**

https://afs365.sharepoint.com/sites/DGIBillServicesProject/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120005AB5D5300A959E42A2180BFAC5BF4AB2&id=%2Fsites%2FDGIBillServicesProject%2FShared%20Documents%2FLegacy%20AO%2FTeam%203%2FProject%20Planning%2FDaily%20Tasks&viewid=5afa7f3b%2D6c5d%2D4507%2D87f8%2D2970bb6901a1&OR=Teams%2DHL&CT=1661438156019&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MzEwMTAwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

Please update the comment will all removed toggles for the record.

**Comment by MitchLivingstone** [comment]
In progress.

**Comment by dsrr47** [comment]
@af-manish The below flags are still in use. 

Still in Use: 
check_in_experience_enabled
coe_access
covid_vaccine_scheduling_frontend
covid_vaccine_registration_frontend_cta
covid_vaccine_registration_frontend_hide_auth
covid_vaccine_registration_frontend_enable_expanded_eligibility
covid_vaccine_registration_frontend
covid_volunteer_intake_enabled
covid_volunteer_update_enabled
debt_letters_show_letters
dependency_verification
dischargeWizardFeatures
find_forms_show_pdf_modal
file_upload_short_workflow_enabled
hlr_v2
megaMenuMobileV2
pre_entry_covid19_screener
request_locked_pdf_password
search_representative
search_dropdown_component_enabled
show_edu_benefits_0994_wizard
show_edu_benefits_1990e_wizard
show_edu_benefits_1990n_wizard
show_edu_benefits_1990_wizard
show_edu_benefits_1995_wizard
show_edu_benefits_5490_wizard
show_edu_benefits_5495_wizard
show_medical_copays
show_healthcare_experience_questionnaire
show_new_get_medical_records_page
show_new_refill_track_prescriptions_page
show_new_schedule_view_appointments_page
show_new_secure_messaging_page
show_new_view_test_lab_results_page
stem_automated_decision
va_global_downtime_notification
va_online_scheduling
va_online_scheduling_cancel
va_online_scheduling_cheetah
va_online_scheduling_community_care
va_online_scheduling_direct
va_online_scheduling_provider_selection
va_online_scheduling_requests
va_online_scheduling_vaos_service_cc_appointments
va_online_scheduling_vaos_service_requests
va_online_scheduling_vaos_service_va_appointments
va_online_scheduling_poc_health_apt
va_online_scheduling_status_improvement
gibct_eyb_bottom_sheet
dependents_management

**Comment by MitchLivingstone** [comment]
Story updated.

**Comment by dsrr47** [comment]
UPDATE: i see no feature flags still in use related to GIBCT

**Comment by MitchLivingstone** [comment]
Completed and Closed. 09/01/2022
