### ISSUE TITLE
[Discovery] Evaluate ability to programmatically retrieve weekly/monthly analytics data from Grafana

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#460]
## User Story
As a Product Owner, I need to have automatic, regular, and easy to consume latency analytics in order to use Grafana data regularly as a part of my workflow.

## Discovery Question
Can we pull real-time data that shows weekly education latency analytics and display it somewhere for edu stakeholder to access?

## Constraints/Assumptions
- We can pull the data programmatically

## Acceptance Criteria
- [ ] Discovery has been conducted
- [ ] A readout of findings is documented
- [ ] If we can pull the data from Grafana, update the Google Sheets MVP so that it populates the fields automatically from Grafana weekly
## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Education Benefits Claims - Last Week: http://grafana.vetsgov-internal/dashboard/db/application-request-breakdown?orgId=1&from=now-1w%2Fw&to=now-1w%2Fw&var-data_source=Prometheus%20(Production)&var-application=api&var-component=education_benefits_claims

**Comment by joanneesteban** [comment]
Determining if we'll be using Prometheus or Grafana.

**Comment by nedierecel** [comment]
@joanneesteban This looks like a duplicate of #2184. Okay to close?

**Comment by joanneesteban** [comment]
@nedierecel Yup! Closing this ticket.
