### ISSUE TITLE
[Discovery] Recruit for Research Sessions

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#4600]
## Goal
We want to recruit participants for our Claim Status Tool research study

## Acceptance Criteria
- [x] The research plan has been attached to this ticket
- [x] The conversation guide has been attached to this ticket
- [x] Lauren Alexanderson has been assigned
- [x] Identify available dates / times for the sessions
- [x] Identify observers to Perigean (in Slack)
- [x] Recruiting has been kicked off with Perigean

**Comment by kevinstachura** [comment]
@lalexanderson-dsva can you please review the research plan we have put together and let us know if it looks good? We will have the conversation guide posted by later today (will update that here). Thank you!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/research/research-plan.md

**Comment by lalexanderson-dsva** [comment]
@chrvalla - in your convo guide, i would recommend that you do the tech check to see if the Veteran can share their screen at the VERY top of your session before you get too far into your questions. I do mine before i even do the intro.

**Comment by lalexanderson-dsva** [comment]
Would also recommend going with the "What information is confusing" versus "Is any info confusing" - you'll get more honest answers.

**Comment by chrvalla** [comment]
Thank you Lauren!

**Comment by kevinstachura** [comment]
Closing ticket out as all acceptance criteria has been satisfied.
