### ISSUE TITLE
[DESIGN] Update the Help Desk Number

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4601]
## Goal
The number on the red error message for "View your VA disability ratings" has an old number on it and it needs to be updated to **844-698-2311** within the mockup to keep it current.

## Tasks
- [x] Update the current red error message, within the mockup, that appears for any "broken" component to 844-698-2311.

## Acceptance Criteria
- [x] In the mockup, when a red error message appears, the new number is displayed.

**Comment by sporeboy** [comment]
Rated Disabilities revised: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/5973de59-34ae-46ce-8aca-e41d8f73f3d6/RD-Screen-Tool-4
https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/06fe86e9-9efe-44b3-89ea-2bac9f433e10/RD-Screen-Tool-5

View Dependents revised: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/237c9936-10b0-46ed-abd6-18cc62478336/View-Dependents-Error-1
