### ISSUE TITLE
Content request for profile - gender identity FAQ

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#46017]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
 

During Personal information UAT, Veterans conveyed that they’d like more information about the Gender identity field. We’re looking to add a small amount of info in the dropdown information that could further specify who has access to the information. 

Specific feedback:

- 2/7 participants were concerned with VA visibility and would like more information on who can view this information.
- 3/7 participants wondered why the NCM would need to see gender identity, but did not have a negative view on this.
- 1 participant thought more information should be included for how to update their gender identity with their health care team and to define the “healthcare team.”

We discussed this at @DanielleThierryUSDSVA's office hours and have the current revisions in progress (changes in bold). We’d also like to specify what “VA-wide records” means, and are looking into more information on this in order to clarify this term for Veterans.

Note: Another [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36751) has been reopened to address the R&S article.

--------

> [FAQ dropdown] 
What to know before you decide to share your gender identity:
> 
> [Expanded content] 
Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information **because they are part of the same records system**.
> 
> We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.
> 
> [Link] 
**Learn more about… [Resources & Support article]**

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Personal information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information)
- Link to or attach user flows:
- Link to prototype or mockups: [Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/eKYxzDm) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/GmRgk3O)
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: NA
- Estimated staging review date: NA
- Content and IA work needed by: TBD

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Profile - Authenticated Experience
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Sharon Kasimow
-	Designer: Christina Gednalske
-	FE engineer: Adam Whitlock
-	Product/team Slack channel: accountexp-authexp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by cgednalske** [comment]
@DanielleThierryUSDSVA -- here is the information Samara provided surrounding who has access to "VA-wide records." Sounds a bit tricky to provide details without also saying it could be subject to change, so I'm interested to hear your thoughts 👀 

> Preferred name and gender identity information is ultimately stored in MPI, which can be accessed by VBA and NCA if they choose. Right now, I believe only VHA is accessing this information, but I can't guarantee that this will be the case forever. Hence, we included the copy on this being accessible VA-wide because it is not stored exclusively in the VA health record, and could be accessible by other business lines later on.

**Comment by DanielleThierryUSDSVA** [comment]
Hmm. Yeah, I think this is the level of detail we already have so I'm not sure we can provide much else. One follow-up question: Do staff members need to have a specific level of access to be able to access MPI data? That might be a good detail to work in to reassure folks that not **any** staff member from across VA can access their records.

**Comment by cgednalske** [comment]
Hi @DanielleThierryUSDSVA -- Below is Samara's response to your follow-up question. It's still sounding tricky to incorporate this in a concrete way, unless we say something like "goes into your VA-wide records and can be accessed by... [personnel at a certain access level, etc.]"?

> I don't think that anyone can access MPI. As far as I know, people can only access this data if they are accessing it from a system that is integrated with MPI. Example: I can't access MPI, neither can Danielle. So no, any old staff member can't access all veteran data. Things are definitely more secure than that.

**Comment by DanielleThierryUSDSVA** [comment]
Great. Yes, I assumed that not just anyone could access, but it sounds like we don't have a ton of detail around who specifically has access. I think that's okay and we can work with this. I'm also wondering if we want to move away from VBA and NCA specifically and be more general. What do you think of this to start?

Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. 

But you should know that any information you share in your VA.gov profile goes into your VA-wide records. VA staff who have secure access to the VA-wide records system can read this information. 

We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.

**Comment by cgednalske** [comment]
@DanielleThierryUSDSVA Previously we had the first two sections of text as one paragraph. Do you prefer keeping them that way or separating them out as you have in your comment above?

**Comment by cgednalske** [comment]
Hi @DanielleThierryUSDSVA! Checked in with the Samara and Sharon and they're wondering if we can soften the language more so we can be sure it doesn't sound like any VA staff member can go into MPI and look at this data. What do you think of the following?

> But you should know that any information you share in your VA.gov profile goes into your VA-wide records. VA staff outside of the health care system may be able to view this information.

**Comment by DanielleThierryUSDSVA** [comment]
@cgednalske Yes! I had been playing with a version like that and am happy to go with that. Just change "view" to "read" so we're avoiding sighted language.

I broke up the paragraphs just because these are separate thoughts. But I don't have a strong preference there!

**Comment by cgednalske** [comment]
@DanielleThierryUSDSVA Excellent! Sounds great. I've made that change and will send over this version. Thank you!

**Comment by SKasimow** [comment]
@cgednalske - can we close?

**Comment by cgednalske** [comment]
@SKasimow yep! Should be good to close. 👍
