### ISSUE TITLE
Midpoint Review - Research Feedback - Sitewide Facilities, Lovell VAMC/TRICARE pages

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#46045]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Nice research data to guide this iteration. My only comment for moving forward, as listed below in Feedback, is to do another round of research before finalizing design for staging.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
none

**Should:**
1. Should hold another round of usability testing. I'd use the same testing protocol, to the extent possible. Then compare with results of previous design iteration to confirm if this design update had a better success rate than the previous iteration at 32%.
One change I can think of would be to recruit to over-sample any under represented groups in the previous study.

**Consider:**
none

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by dsinla** [comment]
Thanks for your feedback.

- We will not address any of the SHOULD or CONSIDER recommendations at this time; the priority is to ship a solution and make incremental improvements over time
- We will develop metrics to assess the performance of this site to support future improvements
