### ISSUE TITLE
Write SSO rollout FAQ

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#4604]
Address:
* how SSO will function from a user perspective
* Impact on developers
* Operations concerns

Target audience:
VSP and VFS teams (primarily VSA and VAOS right now)

**Comment by ambikaroos** [comment]
Patrick wrote up a list of questions targeted at developers and DSVA folks, but not answers yet. He has also mentioned that this is pending and will be circulated. If needed, we can set up a call to discuss after that.

**Comment by patrickvinograd** [comment]
In progress here: https://docs.google.com/document/d/1gQP4iKZMpCVdhXBptk-ipfUPti_JPq-aw7G65t33AM8/edit#

Will move to va.gov-team once it's in better shape.

**Comment by patrickvinograd** [comment]
Posted for wider review here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/SSOeRolloutFAQ.md

And publicized in vfs-all-teams channel.
