### ISSUE TITLE
Midpoint review - IA Feedback - Sitewide Facilities, Lovell VAMC/TRICARE

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#46042]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
VA, TRICARE and Dual beneficiaries are institutional terms that may not be clear to the end user, so it's important to see whether and to what degree the veteran understands what they mean. 

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
- Add questions to see if the participant 
   - understands the differences between the different types of coverage
   - Understands what it means to be covered by one instead of the other.
   - Knows which one applies to them.

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by dsinla** [comment]
@jimuhh  Thanks for your review. Glad to see there's no SHOULDS.
To be clear, there is no plan for additional testing.  We are proposing some small modifications to the already-reviewed design, based on the feedback from the last rounds of user testing.

**Comment by dsinla** [comment]
Thanks for your feedback.

- We will not address any of the SHOULD or CONSIDER recommendations at this time; the priority is to ship a solution and make incremental improvements over time.
- We will develop metrics to assess the performance of this site to support future improvements
