### ISSUE TITLE
Claim status: MVP mini-learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4605]
**User story:** 
As a Veteran, I want to find what the status of my claim is and feel confident that the information is true and accurate.

**Problem statement:** 

- Today many Veterans submit claim applications and they submit duplicate applications because a long time passes and they don't realize their original claim app is in review; or they call the call center to inquire about their claim status even after first using the claim status tool. 
- There appears to be an information issue (they don't know their claim status or how they can find it easily online) as well as possibly a trust issue with the information that they do have access to (calling even after checking claim status online). 

**Purpose:** 
Create an MVP mini-learning center using "claim status" topic to do user research on it and iterate before rolling it out more broadly.

**What is the business goal?**
- Reduce calls about claims to the call center.
- Reduce duplicate claim submissions.
- Make an MVP and research learning center content model.

**How does this map to our North Star?** 
It increases use of self-service tools.

**How will we measure success?** 

- Track call volume about claim status to call center.
- Track sign ins and usage of claim status tool.

**How well do we understand the problem?**  
In discovery 

**For reference:**
- This is related to the super epic for tier 2 content templates. Learning center is a type of tier 2 content: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2281
- Some draft design templates are already in flight as WIP. 
- We will need to build template authoring experience in Drupal for the final content design templates.

**Comment by aeltarhoni** [comment]
Created for the DEPO board.

**Comment by jenniferlee-dsva** [comment]
Closing this epic related to Claim Status. Chante and I could not get the call center to work with us. Therefore we are creating our learning center templates with a different topic. 
FYSA @rtwell @clantosswett @chrisj-usds @AZSchneider @JeffBarnesUSDS 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/87a3a712-cfb3-403d-82f0-b43328c988fe)

> From: Lee, Jennifer Y. <Jennifer.Lee27@va.gov> 
> Sent: Thursday, February 13, 2020 11:56 AM
> To: Yount, Regina, VBAVACO <Regina.Yount@va.gov>; LantosSwett, Chante <Chante.LantosSwett@va.gov>
> Cc: Quick, Dawna, VBAVACO <Dawna.Quick@va.gov>; Rebstock, Melissa, VBASPT <Melissa.rebstock@va.gov>; Hof, Lindsay, VBAVACO <Lindsay.Hof@va.gov>
> Subject: RE: Claim Status Information - Skype Call
> 
> Hello Regina and team,
> As we have not received a response or the scripts and articles we need to get this started, we have decided to pilot our learning center MVP with a different business and topic.  I just wanted to let you know, so we can have closure on this effort and request. 
> 
> We would definitely like to stay in touch, as we envision in the future, the call center content authors would be one of the primary users of the learning center templates in the new CMS, and we would definitely want to work together to use analytics to measure how learning/support content may be reducing call volumes (and to update and optimize content to work better to do that if we find that they are not work effectively). 
> 
> Best,
> Jen
