### ISSUE TITLE
[Bug] Profile - Contact Info - Bad Address Indicator - Update-saved alert has wrong icon

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#46065]
## What happened?
On **Staging Profile > Contact Information** page, after Updating **Mailing** address _without_ any changes, the **Update saved** alert had the wrong icon.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: 121-126 [see [MVI Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) doc for passwords]

## Steps to Reproduce
- URL: https://staging.va.gov/profile/contact-information
- Test User _(if applicable)_: [see **Specs** above]
- Under **Addresses > Mailing**, click **Edit** button, change **address**, then click **Update** button.
- Observe that **Update saved** alert icon is incorrect.

### Screenshot
[Example from MacOS Chrome]
![image](https://user-images.githubusercontent.com/587583/186031938-80444211-b4fa-4087-b567-20655614311b.png)

## Desired styling
- [ ] **Update saved** alert should have correct icon.

### Screenshot
From [this mockup](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/GmlvPr8):
![image](https://user-images.githubusercontent.com/587583/186032119-507a4a40-0f34-4b96-af07-9b481afff7a7.png)

## Acceptance Criteria
[see **Desired styling** above

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Samara-Strauss** [comment]
Does this have to do with the recent forms system changes?

**Comment by SKasimow** [comment]
@Samara-Strauss - Adam is checking; looks like we may be using previous design.

**Comment by SKasimow** [comment]
Validated in staging and seeing correct color for icon:

![Screen Shot 2022-08-31 at 3 29 27 PM](https://user-images.githubusercontent.com/74627978/187766102-bf4f90c1-2cd3-4311-a2d0-9bf65876c9ec.png)

Closing...
