### ISSUE TITLE
Reconfigure dev environment to point to SSOe INT environment

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#4607]
Per last agreement with IAM, we have the following environment mapping:

```
(vets-api -> SSOe)
localhost -> PINT
dev-api  -> INT
staging-api -> SQA
api -> PROD
```

dev is currently pointing at PINT. Update the dev settings file to use the INT metadata instead.

**Comment by ericbuckley** [comment]
@patrickvinograd I take it "https://int.eauth.va.gov" can only be accessed within a VPN, where "https://pint.eauth.va.gov" is publicly available?  Otherwise are the 2 environments identical?

**Comment by patrickvinograd** [comment]
Yes re VPN vs. public access. They are not guaranteed to be identical - IAM may promote code to one or the other first, but in the steady state they are similar, and use the same user repository.

**Comment by patrickvinograd** [comment]
Closed via https://github.com/department-of-veterans-affairs/devops/pull/6177
