### ISSUE TITLE
Improve error researching for Sign in

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46099]
We currently display the error code and the request id on the frontend. When we search the DD logs for the request ID the error doesnt seem to be there. Id like to remedy this in some way.

Example: https://vagov.ddog-gov.com/logs?query=803a95de-5790-4527-9be2-f3b0c1fd285b&cols=host%2Cservice%2Cenv%2C%40network.client.ip&event=AQAAAYLLTL4xccpVVgAAAABBWUxMVE1WY0FBRDNDQ1lPVTNxbzJRQzQ&index=&messageDisplay=expanded-lg&stream_sort=time%2Casc&viz=stream&from_ts=1661267448917&to_ts=1661268348917&live=true
![Screen Shot 2022-08-23 at 11.42.41.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/4adb8066-f6d5-4e48-b718-b931fbd05980)

**Comment by AGarcia-Clarity** [comment]
@bosawt How did you force the error?  I have to double check the AuthApp and see when the request_id is actually recorded.

**Comment by bosawt** [comment]
Change the `V1/SessionsController#new` function to this:
```    
def new
  type = params[:type]
  Rails.logger.info("Request id for backend: #{request.uuid}")
  redirect_to url_service.login_redirect_url(auth: 'fail', code: '4')
end
