### ISSUE TITLE
View Cancelled Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46108]
## Problem Statement
Veterans may not know that an appointment has been cancelled. When using Pre-Check-in and/or Check-in, could we let them know when an appointment has been cancelled instead of just showing them that they have no appointments or excluding the cancelled appointment from the appointment list.

**Comment by benbrasso-agile6** [comment]
This epic could use a description to help with the RICE scoring, whenever available.

**Comment by kristenmcconnell** [comment]
Looks like pre-check-in scenarios were covered in this [EPIC](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/40418), but day of still needs to be addresses.

**Comment by loripusey** [comment]
I'm not convinced that you could get a check-in link back when you text "check in" for a cancelled appointment. I am going to cancel one of my appointments in the staging tool and see what happens because I don't know on our side. Still a mystery on the VeText side.

**Comment by kristenmcconnell** [comment]
I do wonder if the API would need to be changed; I don't know.
