### ISSUE TITLE
Add new error code links to doc

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46101]
Complete the error code documentation additions and add links to the docs in the main error doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Monitoring%20and%20Alerting/Identity_errors_metrics.md

**Comment by joeniquette** [comment]
Added one link in to Alexs document in the errors section. This should be reviewed and updated.

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/46866
