### ISSUE TITLE
[Analytics] Filter out monitoring IP addresses in GA

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#46103]
Currently, our uptime monitoring is being recorded in Google Analytics, making our analytics less accurate.

## Tasks:
- [x] [Gather list of IP addresses to filter
- [ ] Filter IP addresses in GA

**Comment by randomsync** [comment]
@benbrasso-agile6 and I discussed this. We don't have the ability to add a filter in GA to exclude the traffic from DataDog syntehtics. I'll reach out to platform team to get this added.

**Comment by randomsync** [comment]
reached out to platform analytics team: https://dsva.slack.com/archives/CBU0KDSB1/p1663002239787079

**Comment by randomsync** [comment]
Sharing relevant links: 
Excluding internal traffic in GA: https://support.google.com/analytics/answer/1034840
View filters in GA: https://support.google.com/analytics/answer/1033162

[Link](https://vagov.ddog-gov.com/logs?cols=host%2Cservice%2C%40network.client.ip&event&from_ts=1663169287569&index=&live=true&messageDisplay=inline&query=12345678-1234-1234-1234-0123456789ae+-service%3Avets-api&stream_sort=time%2Cdesc&to_ts=1663170187569&viz=stream) to datadog query to find the incoming IP Addresses

Form what I can tell, the incoming requests from synthetic checks are coming from these 2 ip ranges:

10.247.32.*
10.247.33.*

**Comment by benbrasso-agile6** [comment]
[YOu want to take the lead on creating this ticket for them? ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BProduct%5D)

If you don't get to it today, I can maybe get to it tomorrow when you're out.

**Comment by randomsync** [comment]
Created a ticket for platform analytics team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/47093

**Comment by benbrasso-agile6** [comment]
I say we close this ticket @randomsync @loripusey 

we just have to monitor progress on that ticket that we assigned to analytics
