### ISSUE TITLE
Remove link to paper form on VET TEC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#4610]
## User Story or Problem Statement
As a Veteran interested in the VET TEC program, I need to know where to find the application so I can apply. 

Currently on the [VET TEC page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/), we mention the paper form 22-094 but do not provide a link. This form has been deprecated per Luke Tickner, so we need to point users to the online application instead.

New approved wording for page: 

## How do I apply?
You can [apply](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction ) for the VET TEC program online.

If we determine that you’re eligible for VET TEC, you’ll then apply to the VA-approved training provider of your choice. Your training provider may review your qualifications to assess whether they think you’ll be able to successfully complete their training program and find meaningful, relevant employment.

VET TEC is a five-year pilot program. You can participate as long as the funding is available.

Note: If you haven’t already applied for VA education benefits, you’ll also need to fill out an Application for VA Education Benefits (VA Form 22-1990) or [apply online](https://www.va.gov/education/how-to-apply/).

## Goal
Link to this online application: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction 

## Objectives or Key Results this is meant to further
- Veterans can click to the application directly from VET TEC page.

## Acceptance Criteria
- [x] New text and link added to VET TEC page
- [x] Determine if paper form is mentioned on other pages and if so change to the online application or the how-to-apply wizard
- [x] Send Luke and Tammy preview link of changes when page is ready to go live

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@peggygannon Can you please review this page in Drupal and publish if all looks OK? I also removed the vanity number for the GI Bill lower down on the page. Once it's published, please let me know because I will email the stakeholders with a preview link for awareness. @jenniferlee-dsva I did a search on VA.gov as well as Google and didn't see any more mentions of the paper form for us to change on other pages. 

Preview link in Drupal: preview-prod.vfs.va.gov/preview?nodeId=930

**Comment by peggygannon** [comment]
@RLHecht I've reviewed and published. I updated the link for the 1990, to go directly to the form not to the EDU apply page.  

Having the link go to the Edu apply page can be confusing  b/c, once on the apply page, users would have to go through a wizard to find the 1990.

**Comment by RLHecht** [comment]
Thanks, Peggy. @jenniferlee-dsva I've emailed the preview link to Tammy and Luke. Moving to validate.

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. @Karak888
