### ISSUE TITLE
[Design] MyHealth: Secure Messaging: Icon questions

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#46118]
Background: Some of the icons used on the Create New and Deleted folders may need to be changed if they aren't aligned with the VA Design System.

As a Veteran, I want to have consistent icons throughout VA.gov so that I don't have to learn different design patterns and iconography for different applications. 

Tasks: 
- [x] Review icons during design open office hours
- [x] Make any design adjustments needed as a result of that meeting
- [x] Update any documentation that references icons in question

Tasks: 
- [x] Review icons during design open office hours
- [x] Make any design adjustments needed as a result of that meeting
- [x] Update any documentation that references icons in question

**Comment by jonathanjnelson** [comment]
Updated designs based on Platform feedback: 
![Screen Shot 2022-08-26 at 2 53 38 PM](https://user-images.githubusercontent.com/58444931/186982019-a3e74ab5-8343-4e65-8a63-caa5dac512b3.png)

![Screen Shot 2022-08-26 at 2 56 00 PM](https://user-images.githubusercontent.com/58444931/186982148-a8b98d08-e77f-4091-b208-65fe3494e3ed.png)
