### ISSUE TITLE
[Design] MyHealth: Secure Messaging: Left hand navigation, breadcrumbs, return to landing page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#46122]
Background:  The left hand navigation in VA.gov applications is part of a Drupal template, which can't be changed dynamically.  We need to determine if it is feasible to have a left nav that looks like the Drupal nav, or is a custom version of it.  In addition, there is a question of how best to return users to the landing page, and the appearance of the breadcrumbs. 

Tasks: 

- [ ] Arrange a meeting with the UCD team and Mikki Northius to discuss the items above.  
- [ ] Document any decisions reached in the design decisions doc in the GitHub product folder.

- [ ] Arrange a meeting with the UCD team and Mikki Northius to discuss the items above. 
- [ ] Document any decisions reached in the design decisions doc in the GitHub product folder.

**Comment by jonathanjnelson** [comment]
Closing this. Please see [#44786](https://app.zenhub.com/workspaces/mhv-to-vagov-top-level-view-62619a987d74510018ecc546/issues/department-of-veterans-affairs/va.gov-team/44786)
