### ISSUE TITLE
[Design] MyHealth: Secure Messaging: Feedback from Platform

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#46123]
Background:  Matt Dingee on the Platform team provided some feedback about changing links to buttons, etc.  Jonathan will repost Matt's comments and the design team will attend design office hours if needed.

Tasks:
- [x] Repost Matt Dingee's feedback about changing buttons to links, etc.
- [x] Attend open office hours if needed.

Acceptance Criteria:
- [x] Repost Matt Dingee's feedback about changing buttons to links, etc.
- [x] Attend open office hours if needed.

**Comment by jonathanjnelson** [comment]
Informed design iterations for SM
