### ISSUE TITLE
Need list of "type of care" being passed by Vets API

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#46129]
Per [VAOSR-3707](https://issues.mobilehealth.va.gov/browse/VAOSR-3703) the backend team needs a list of the values for "Type of Care" that are passed from the front end to VAR/SM.

After reviewing the expected the clinical service names, as described in the table in the description, we have confirmed that VAOS is persisting the type of care name to the database with the expected names. When appointment requests are created in VAOS, the clinical service name is mapped from the clinical service id to one of the names listed in the table above. When appointment requests are created in VAR/SM, the clinical service name passed in on the create request is persisted to the database. This is why the requests created via VAOS are all listed above with the expected name. It is possible the FE clinical services names may possibly out of sync with the table above. I recommend having them take a look to verify. 

Description
There are currently 8 types of care labels which were changed in the FE UI (refer to attachment for more information); see table containing override values below (spacing, case, and special characters should match exactly):

Type of Care label *BE override for VA appts | Primary/Secondary Stop Code (for awareness)
---------|----------
Amputation Services | 211
Audiology | 203
Clinical Pharmacy-Primary Care | 160/323
COVID Vaccine | 710 and CHAR4=CDQC
CPAP Clinic | 349/116
Food and Nutrition | 123, 124
MOVE! program | 372, 373
Ophthalmology | 407
Optometry | 408
Outpatient Mental Health | 502/125, 502/179, 502/185, 502/186, 502/187, 502/509, 502/510
Primary Care | 322, 323, 350
Sleep Medicine - Home Sleep Testing | 143/189
Social Work | 125/323

*This table containing override values is also on the wiki: ** https://wiki.mobilehealth.va.gov/x/QoT8EQ

**Comment by jenniemc** [comment]
The following table pertains to VAOS Service

FE type of care name | BE type of Care name  | clinical service id  (v2) | Primary/Secondary Stop Code (for awareness)
---------|----------|----------|----------
Amputation care | Amputation Services | amputation | 211 | 
Audiology and speech (including hearing aid support) | Audiology | audiology | 203
Pharmacy | Clinical Pharmacy-Primary Care | clinicalPharmacyPrimaryCare | 160/323
COVID-19 vaccine | COVID Vaccine | covid | 710 and CHAR4=CDQC
Continuous Positive Airway Pressure (CPAP) | CPAP Clinic | cpap | 349/116
Nutrition and food | Food and Nutrition | foodAndNutrition | 123, 124
MOVE! weight management program | MOVE! program | moveProgram | 372, 373
Ophthalmology | Ophthalmology | ophthalmology | 407
Optometry | Optometry | optometry | 408
Mental health | Outpatient Mental Health | outpatientMentalHealth | 502/125, 502/179, 502/185, 502/186, 502/187, 502/509, 502/510
Primary care | Primary Care | primaryCare | 322, 323, 350
Sleep medicine and home sleep testing | Sleep Medicine - Home Sleep Testing | homeSleepTesting | 143/189
Social work | Social Work | socialWork | 125/323


VAOS makes the call to the vets-api configurations endpoint to retrieve the clinical service IDs for a given facility. FE matches the returned clinical_service_id to display the type of care name defined in the vaos `constants.json` file, https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/utils/constants.js#L91



cc: @JRRoof, @ldelacosta, @marcynadeau

**Comment by jenniemc** [comment]
Looking at how type of care is displayed in VATS, the first request with time stamp 8/29/2022, 19:00:36 was created using v0 for sleep medicine. The second request with timestamp 8/29/2022, 18:41:16 was created using v2. 
<img width="416" alt="image" src="https://user-images.githubusercontent.com/54327023/187329337-9c151d89-c6f3-4be3-b878-ad64c6bb0e3b.png">

Below are the post call responses for appointment requests. 
```
v0
Request Response
{
    "id": "e5f1c31782d64a380182ec43bceb0001",
    "type": "appointment_requests",
    "attributes": {
        "facility": {
            "type": null,
            "address": null,
            "state": null,
            "city": null,
            "name": "CHYSHR-Cheyenne VA Medical Center",
            "facilityCode": "983",
            "parentSiteCode": "983"
        },
        "patient": {
            "inpatient": false,
            "textMessagingAllowed": false
        },
        "appointmentRequestDetailCode": [],
        "lastUpdatedAt": null,
        "createdDate": "08/29/2022 19:00:36",
        "appointmentDate": null,
        "appointmentTime": null,
        "optionDate1": "09/12/2022",
        "optionTime1": "AM",
        "optionDate2": "No Date Selected",
        "optionTime2": "No Time Selected",
        "optionDate3": "No Date Selected",
        "optionTime3": "No Time Selected",
        "status": "Submitted",
        "appointmentType": "Sleep medicine and home sleep testing",
        "visitType": "Office Visit",
        "reasonForVisit": null,
        "additionalInformation": null,
        "email": "apoldass@lts.com",
        "textMessagingAllowed": false,
        "phoneNumber": "9999998888",
        "purposeOfVisit": "Routine Follow-up",
        "providerId": "0",
        "secondRequest": false,
        "secondRequestSubmitted": false,
        "bestTimetoCall": [
            "Afternoon"
        ],
        "hasVeteranNewMessage": false,
        "hasProviderNewMessage": true,
        "providerSeenAppointmentRequest": false,
        "requestedPhoneCall": false,
        "bookedApptDateTime": null,
        "typeOfCareId": "143",
        "friendlyLocationName": "CHYSHR-Cheyenne VA Medical Center",
        "ccAppointmentRequest": null,
        "date": "2022-08-29T19:00:36.830+00:00",
        "assigningAuthority": "ICN"
    }
}
```

```
v2
Request Response
{
    "id": "126132",
    "type": "appointments",
    "attributes": {
        "id": "126132",
        "identifier": [
            {
                "system": "http://med.va.gov/fhir/urn/vaos/ars/id",
                "value": "e5e0de6882b72ca00182ec3201690031"
            }
        ],
        "kind": "clinic",
        "status": "proposed",
        "serviceType": "homeSleepTesting",
        "reasonCode": {
            "coding": [
                {
                    "code": "Routine Follow-up"
                }
            ],
            "text": "Sleep medicine test"
        },
        "patientIcn": "1013120820V528557",
        "locationId": "983GC",
        "created": "2022-08-29T18:41:16Z",
        "requestedPeriods": [
            {
                "start": "2022-09-05T00:00:00Z",
                "end": "2022-09-05T11:59:59.999Z"
            },
            {
                "start": "2022-09-05T12:00:00Z",
                "end": "2022-09-05T23:59:59.999Z"
            }
        ],
        "contact": {
            "telecom": [
                {
                    "type": "email",
                    "value": "apoldass@lts.com"
                },
                {
                    "type": "phone",
                    "value": "9999998888"
                }
            ]
        },
        "preferredTimesForPhoneCall": [
            "Afternoon",
            "Morning"
        ],
        "comment": "Sleep medicine test",
        "cancellable": true,
        "extension": {
            "ccLocation": {
                "address": {}
            }
        },
        "location": {
            "id": "983GC",
            "type": "appointments",
            "attributes": {
                "id": "983GC",
                "vistaSite": "983",
                "vastParent": "983",
                "type": "va_facilities",
                "name": "Fort Collins VA Clinic",
                "classification": "Multi-Specialty CBOC",
                "timezone": {
                    "timeZoneId": "America/Denver"
                },
                "lat": 40.553875,
                "long": -105.08795,
                "website": "https://www.cheyenne.va.gov/locations/Fort_Collins_VA_CBOC.asp",
                "phone": {
                    "main": "970-224-1550"
                },
                "physicalAddress": {
                    "line": [
                        "2509 Research Boulevard"
                    ],
                    "city": "Fort Collins",
                    "state": "CO",
                    "postalCode": "80526-8108"
                },
                "healthService": [
                    "Audiology",
                    "EmergencyCare",
                    "MentalHealthCare",
                    "PrimaryCare",
                    "SpecialtyCare"
                ]
            }
        }
    }
}

```
@marcynadeau
