### ISSUE TITLE
CT: Research Sharepoint Yellow Ribbon Data Source

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4614]
## User Story:
As a developer, I need to research the Yellow Ribbon data available in Sharepoint so that I can determine the best course of action on how to update the Yellow Ribbon data within the Comparison Tool.

## Assumptions:
1. Access to [Yellow Ribbon Sharepoint Site](https://vaww.infoshare.va.gov/sites/educationservice/223/223C/Lists/Dashboard1/AllItems.aspx) is granted by EDU.

## Acceptance Criteria:
1. Analysis is completed and documented on the data contained within the Yellow Ribbon Sharepoint and if it meets the needs of the Yellow Ribbon Data uploaded to GIDS and used by the Comparison Tool.
2. A development plan is documented on how to leverage the Yellow Ribbon Sharepoint data within the GIDS tool.

**Comment by shawkey-daniel** [comment]
For AC 1, all fields in the SharePoint list match fields in GIDS except missed_deadline and date_yr_signed_by_yr_official. Discussed with EDU and determined missing fields are not required for future use.

**Comment by shawkey-daniel** [comment]
[https://app.zenhub.com/files/133843125/0eb89a85-037c-4b4f-bb3a-c40c859520fb/download](https://app.zenhub.com/files/133843125/0eb89a85-037c-4b4f-bb3a-c40c859520fb/download)

AC 2 Document of proposed development plan.
