### ISSUE TITLE
[PM] Review Email Address Pattern

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#46144]
The Forms Team has started moving towards the removal of confirmation fields for email addresses.  To stay in compliance, we'll need to review the updated guidance and plan for the removal of any such fields on the 10-10EZ.

Reference ticket: [#1006](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1006).

The following locations need to be reviewed:
<details>
<summary>1. 10-10EZ Veteran Contact Information</summary>

![Veteran Contact Information EZ.PNG](https://images.zenhubusercontent.com/6258ab9e3d21f626eb2626bc/81ab74be-5269-440d-9ca1-caad834da64d)
</details>
<details>
<summary>2. 10-10CG Veteran Contact Information Page</summary>

![Veteran Contact Information CG.PNG](https://images.zenhubusercontent.com/6258ab9e3d21f626eb2626bc/eb4139ee-70a0-432a-baed-a850c03d61f6)
</details>

<details>
<summary>3. 10-10CG Primary Caregiver Information Page</summary>

![Primary Caregiver Contact Information.PNG](https://images.zenhubusercontent.com/6258ab9e3d21f626eb2626bc/1a288364-fe8d-435c-95b8-b042d559a6b3)
</details>

<details>
<summary>4. 10-10CG Secondary Caregiver Information Page<br>
  - Both first and second Secondary Caregivers</summary>

![Secondary Caregiver Contact Information.PNG](https://images.zenhubusercontent.com/6258ab9e3d21f626eb2626bc/88c08bcd-ab78-49b0-b501-c6d7fa07648a)
</details>

**Comment by hdjustice** [comment]
Reviewed and confirmed that second Verification Email field has been removed.  This field was confirmed as view only, and no data was sent to backend or downstream )no dependencies)
![image](https://user-images.githubusercontent.com/92328831/195927738-87cf1646-4c5e-4678-b005-eeed2e202d0a.png)

**Comment by longmd** [comment]
So much nicer without having to do those twice!!
