### ISSUE TITLE
Design | Profile | Military Info | Update Alerts

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46149]
### Background

While documenting Military Info it was noted that some of the Alerts were outdated and/or needed better messaging (refer to [#45856] and comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45856#issuecomment-1219843523). 

<img src="https://user-images.githubusercontent.com/74627978/185473568-73c4188b-a430-43d1-8651-e88483f07026.png" />

Tasks:

- [ ] Review messaging at an upcoming Content Office hours
- [ ] Update sketch files 

Acceptance Criteria:
- [ ] Notify PM to open a ticket for FE work with link to sketch files

**Comment by andaleliz** [comment]
@tpharrison in our Slack convo you stated:
> If the user does not have an EDIPI, the vets-api will return a 403 error code which indicates that the user is not authorized to access military service records.

Do we get any other information along with this that could help us understand _why_ the user doesn't have an EDIPI?

I'm trying to figure out how to best guide the user when this happens. Is filing a request to change their DD214 really the next best thing, or should they call VA and see if someone can help them first? @Samara-Strauss do you have any recollection about this alert from when it was first created?

**Comment by Samara-Strauss** [comment]
I don't remember when this alert was created, but I don't think the directions we're giving are very helpful. My best guess is that if they are a veteran, they should call the call center or maybe even DMDC to see whether they have military information on file in the first place.

**Comment by tpharrison** [comment]
Hi @andaleliz - I haven't found any info (yet) that tells us _why_ the user doesn't have an EDIPI.  I will ask in the #vsp-identity channel.

We do have `veteran_status` information on the user though.  If a user is a vet, they'll have this...
```
"veteran_status": {
  "status": "OK",
  "is_veteran": true,
  "served_in_military": true
}
```

I checked my info and I see this (probably the same for all non-vets)...
```
veteran_status: null
```

This information is available to the front-end when the page loads and it should be enough to determine if the user _should_ see military history.

**Comment by andaleliz** [comment]
@tpharrison thanks, that is super helpful! I think that's enough to go on. If we get a 403, and `veteran_status` is not null, then we can advise them to call the call center or maybe even DMDC.  I'll talk to Danielle about this. Thank you!

**Comment by andaleliz** [comment]
@Samara-Strauss do you know who can tell us which option - call center or DMDC - would be most helpful for a person to call if they are a Veteran but aren't able to see their military records?

**Comment by Samara-Strauss** [comment]
To be honest, I really have no idea. DMDC would be able to tell them what they have on file re: military records, but no one is going to be able to tell them why things aren't showing up on the website. Let me see if VA Profile has any insight into this.

**Comment by Samara-Strauss** [comment]
So someone from VA Profile sent me this earlier (page is behind VA network, so not linking the whole page). People are supposed to submit forms for corrections, but I'm not sure if we should also tell them to call the call center or DMDC. It's possible that they wouldn't be able to help, but it's also possible they might, especially if the problem is looking into a missing record (which isn't covered below):

![image](https://user-images.githubusercontent.com/34068740/186979917-34e05e6b-f510-47ef-87db-0c4a39e36a53.png)

**Comment by andaleliz** [comment]
@Samara-Strauss this is tough! It feels like there isn't a whole lot we could do for people if they encounter the 403 error that would lead us down this path. Luckily, the work that Tom/Adam are doing to improve how that's handled should reduce the rate we see those. 

How do you feel about this proposed copy? I'll need to run it by Danielle, but it feels like these are really the only possibly helpful things we can tell people:

**We can’t match your information to any military service records**
We’re sorry. If you want to learn what records are available, call the Defense Manpower Data Center (DMDC) at 800-538-9552 (TTY: 866-363-2883). Their office is open Monday through Friday (except federal holidays), 8:00 a.m. to 8:00 p.m. ET. 

If you think there might be a problem with your military service records, you can learn how to apply for a correction.

[  Learn how to correct your military service records on the National Archives website.
](https://www.archives.gov/veterans/military-service-records/correct-service-records.html)

<img width="565" alt="image" src="https://user-images.githubusercontent.com/55992116/186985346-91f168a9-cff1-4772-ae2d-0b2b6d5df6f3.png">


----

The other use case to consider for this ticket is when we get a successful response from the API and the person is not a Veteran (e.g. our accounts, perhaps a caregiver, etc).  Here's what I propose for that, and it has been reviewed and approved by Danielle:

**We don't have military service records for you**
If you think this is an error,  call us at 800-698-2411 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET. 

<img width="978" alt="image" src="https://user-images.githubusercontent.com/55992116/186985260-23c9564e-3619-40b3-8fe5-ef9bffd45950.png">

**Comment by Samara-Strauss** [comment]
Both of these are huge improvements! No changes, they both look good to go if Danielle gives approval.

**Comment by andaleliz** [comment]
Awesome, thank you! I'll check with her.

**Comment by andaleliz** [comment]
@SKasimow I heard back from Danielle and all the alerts are now content-approved, which means this is ready for FE. To recap, instead of what we have today FE needs to update alerts so that we:
- show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/Pbl3eP/a/zxvZ4Le/r/nqJnRW) when successful response from the API and the person is not a Veteran
- show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/52vgV88) when we get a 403, regardless of Veteran status

I think we should update the product documentation (including call center guide) once this is in place on the FE.

Thanks!

**Comment by SKasimow** [comment]
FE ticket #47477 
Doc ticket #47478
