### ISSUE TITLE
GIDS: Allow  for download of historically published versions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4615]
As an EDU team member, I need the ability to download historical published versions of the Comparison Tool data so I can report on the changes over time.

## Assumptions:
1. Given that versions have changed over time, they will all be exported in the current version file format.

## Acceptance Criteria
1. Each previously published version data can be downloaded using the "Download Export CSV" functionality that is currently used to download the current version.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/548

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-01-29 at 10.39.24 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/df2f198c-e3e1-4132-b935-48e7d267efbe)

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging. Closing this issue
