### ISSUE TITLE
Document everything for Transition of ownership - read.me final

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#46162]
Items to include:
- [x] MVP Designs, error state designs, Notifications
- [x] MVP Wayfinding locations
- [x] updated Playbook for annual updates from IRS
- [x] updated MVP docs: release plan, incident response plan, diagrams, Google analytics page for product
- [x] Opt-in Designs, notifications
- [x] Product outline specific to Opt-in
- [ ] Google analytics URL
- [ ] Next steps for new team document with Opt-in requirements/ ownerships in detail

**Place in a singular turnover file.  All designs should be in PDF with links to sketch.  All documents should be clearly labeled (MVP, Post-MVP Opt-in, Post-MVP multi-year).   All links will be accessible to the VA or next team (avoid Google docs, MO Box, Slack channel, MO Mural).**

**Comment by khandelwal** [comment]
We also need to add how to debug the application in production, especially around data loads.
