### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#46163]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: kylesoskin
- Reason access is required: Joined VSA/Claims & Appeals - Backend Software Engineer last week

**Comment by kylesoskin** [comment]
I already have this access so closing this :)
