### ISSUE TITLE
Application to Onboard: [vets-api-server][dev]

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46172]
### Acknowledge Instructions

- [X] I acknowledge that I have read the above instructions and understand the application name provided will be used to create various resources

### Application Name

vets-api-server

### Environment

dev

### Maintainer

ph-One,jbritt1,LindseySaari,ericboehs

**Comment by jbritt1** [comment]
Pull request reviewed/approved/merged by codeowners.
