### ISSUE TITLE
Analytics Reporting Request for OMB Meeting (OIT)

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4618]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- [Insert Name(s)]
    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
- What team/project is this work for?
    OMB Meeting - OIT
    

## Timeframe for Analytics Requested
November & December

## Analytics to Track Down
- [ ] Total users
- [ ] Total Burials Submission
- [ ] Unique Log-ins (DSLogon, ID.me, and MHV)
- [ ] Total Claims Status Views
- [ ] Customer Satisfaction
 

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
**November** 
**[8,209,436](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20191101&_u.date01=20191130/)** Total users
**611** Total Burials Submission
**1,489,181** Unique Log-ins (DSLogon, ID.me, and MHV)
**1,354,948** Total Claims Status Views
**61** Customer Satisfaction

**December**
**[7,750,154](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20191201&_u.date01=20191231/)** Total users
 **[609](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20191201&_u.date01=20191231&_r.drilldown=analytics.eventCategory:Transactions,analytics.eventAction:Forms%20-%20Burials,analytics.eventLabel:burials-530--submission-successful&explorer-graphOptions.selected=analytics.nthWeek&explorer-table.plotKeys=%5B%5D/)** Total Burials Submission
**[1,505,405](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20191201&_u.date01=20191231&_r.drilldown=analytics.eventCategory:Sign-on,analytics.eventAction:Login%20-%20vagovprod&explorer-graphOptions.selected=analytics.nthWeek&explorer-table.plotKeys=%5B%5D&explorer-table.filter=login-success/)** Unique Log-ins (DSLogon, ID.me, and MHV)
**[1,429,545](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20191201&_u.date01=20191231&_r.drilldown=analytics.eventCategory:Transactions,analytics.eventAction:Claims%20-%20View%20Details&explorer-graphOptions.selected=analytics.nthWeek&explorer-table.plotKeys=%5B%5D/)** Total Claims Status Views
**60.2** Customer Satisfaction

**Comment by jonwehausen** [comment]
👍 @joanneesteban -- Looks great, numbers and links are accurate for November and December.

**Comment by joanneesteban** [comment]
Data sent before close of business, Tuesday, January 7th.

**Follow Up**
That office will request the same data set by Close of Business every first Monday of the month. The next request will be due close of business February 3.

**Comment by joanneesteban** [comment]
OMB responded with the request to visualize the data. Re-opening this issue to add visuals to the requested metrics.

**Comment by joanneesteban** [comment]
Visuals sent on 1/8/20.
[Vets.gov_Va.gov Historical Data (2018 vs 2019)- January 2020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4054120/Vets.gov_Va.gov.Historical.Data.2018.vs.2019.-.January.2020.pdf)
