### ISSUE TITLE
SOCKS access for Mariah Sager

### ISSUE THREAD

**Issue by mariahsager-tw** [department-of-veterans-affairs/va.gov-team#46191]
### Your Name

Mariah Sager

### Your Email

mariah.sager@thoughtworks.com

### Your Role and Team

Software Developer on Digital Health Platform Team

### Product Manager (PM) name and email

Suzanne Miller – suzanne.miller@thoughtworks.com

### Product Owner (PO) name and email

Suzanne Miller – suzanne.miller@thoughtworks.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDK5Oxr/ak4WbfCIRBkrN/d+naPXj1oeqyRbhXKfqf7bVTIb8xBo7pTkmcG+8kpxxZe1yMoX219hE9UtLVg2yjKglYDbzpJd3c9byKZdXYe+G5B5cmX3Pc/vv5vancUv7dr99iG5aQcbqm0q4MiSq/LbxvKSceX0FTw9kuKQpcmlsmlKNPV+DlcoY5kKWlVHESIXUMssZqX7AQxXUpQSixHTOPEA8qRnLNYkRJMy9btkJ+WSxqPl02g3HvU1FoBWmYgkcL+zltSvBcgsLTdLEvXkZ197ydhY9vELuycvY2B2ls6Sgcg55y0ggWh/ES3+sXs0mgIfU0Ojl2C+NlD4ELrx6YOqBdzszTYFGNe0UuEA8QQZpktJXB+VNm9gbaSxhU6LCMm1VPWpXs6kops3GExHaumu1+jB2yCQs+FMzUpPW9IXy8giIIv4T60KNMxSoRkEYH3FdDRoyINQu6MnHvEfgme39cUTTKGpU9cVvupzMhbru5H/ttCC3Qdj9jDkzE= mariahsager@Mariahs-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mariahsager-tw** [comment]
I have been added to the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) and am reopening this issue.

**Comment by kjduensing** [comment]
@mariahsager-tw - SOCKS access granted. Please allow 5-10 minutes for the changes to propagate. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
