### ISSUE TITLE
:red_circle: Product Owner/Manager Roles and Responsibilities Overview

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#46192]
What
Create a roles and responsibilities document for anyone assuming the role of Product Owner/Manager at OCTO. 

Why

Fostering room for collaboration, everyone knows the expectations, and there is alignment between the roles which allows for less energy to be wasted.

Things to do

- [x] Work with Platform, Health, and DE to ensure the duties align with what is expected
- [ ] Edit/Proofread/Format
- [ ] Provide link to OCTO Designer so branding can be include
- [ ] Execute comms plan #45405

**Comment by dmkosko** [comment]
8/24 - Document is complete, just waiting on the design team to have at it. I reached out to Danielle and while she is still working on PACT ACT comms, she is going to take a look for us shortly.

**Comment by dmkosko** [comment]
Meeting scheduled with Heather Justice, Mark Fallows, and Patrick Bateman on 11/8 to discuss PL/PM roles and responsibilities document.

Meeting scheduled with Lori Pusey, Chris Horton, and Stephen Barrs on 11/9 to discuss PL/PM roles and responsibilities document.

**Comment by lkoenigsberg** [comment]
Leah's working doc: https://docs.google.com/document/d/1NT0RmiATgsstCG6zs69ffPW2IiK71_s67qBUetyYDAA/edit?usp=sharing

**Comment by dmkosko** [comment]
- [ ] Dan will coordinate with Leah the first week of December on the final research/recommendations and scheduling of a Q&A session

**Comment by dmkosko** [comment]
Leah provided final edits and feedback to the Roles and Responsibilities doc as well as suggestions that should be approved/denied by Lisa. Dan is the process of setting up a Q&A with the Prod Ops team and Leah to discuss. 

[FINAL_OCTO Product Roles & Responsibilities Feedback.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10133383/FINAL_OCTO.Product.Roles.Responsibilities.Feedback.docx)
[FINAL_OCTO Product Roles Responsibilities.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10133384/FINAL_OCTO.Product.Roles.Responsibilities.docx)

**Comment by dmkosko** [comment]
- [ ] Dan to sync up with Mickin to ensure final docs are uploaded to GitHub
- [ ] Revise and Implement communication plan

**Comment by dmkosko** [comment]
Meeting rescheduled to December 13th

**Comment by dmkosko** [comment]
Meeting minutes are [here](https://dvagov-my.sharepoint.com/:w:/r/personal/lisa_koenigsberg_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7B27751B08-B16B-4C43-A392-FFAEC8BB3034%7D&file=VFSProdDirEnhancementMeeting_Jan192023.docx&action=default&mobileredirect=true&cid=70a805ac-e01b-4fcd-92f5-c1dbd1bb849d)

- [ ] Lisa to revisit the Product Playbook and understand where/if roles and responsibilities fit by February 10th  
- [ ] Dan to add the Business Product Owner role (currently in “feedback” document) to the roles and responsibilities document which will help the teams clarify this role by February 10th  
- [ ] Dan to research additional collab cycle documentation/procedures and Gov’t involvement which can be used for the playbook by February 17th. During Leah’s discussions, she felt that’s what people are looking for. An output from these conversations is that additional documentation and guidance is needed around the collab cycle. The point at which the collab cycle team is looped in on a VFS product is ambiguous to the teams. It’s important to understand at what point of the collab cycle is the product outline developed (and does collab cycle care if it’s completed prior to launch)? There is not a standard pre-launch checklist available that goes through the collab cycle with the Product Lead/Manager. Everyone is deciding on requirements individually which has resulted in unsuccessful launches. These are available on GitHub 
- [ ] Mickin to look for pre-launch checklists and development/release plans to see what’s available and provide his opinion on what is missing and is beneficial by January 30th   
- [ ] Dan to discuss with Lisa and team best way for individuals to create new product-specific templates (issue templates, PowerPoint decks, reports) going forward by February 17th

**Comment by dmkosko** [comment]
Dan currently working on adding information to doc regarding role of Product Owner/Business Stakeholder. Hoping to share a draft early next week.

Lisa mentioned that for the Feb 17th action, she recently started a conversation on this topic with government folks which can be found [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1675351781214/30064f6bea753e63105efecd69410879ea925727?sender=u0b0c2c7d9f6691173f685309). The objective here is to make sure we're creating the right product forms (think of onboarding new product people and info on stakeholder mgmt). Lisa is looping in Mickin to assist from the contractor side. The long-term goal is to put together a product library of documents, templates, etc. to give product people the ease of finding commonly used items.

**Comment by dmkosko** [comment]
Dan is still adding to the draft of the Product Owner/Business Stakeholder section. Hoping to send out a draft in a day or two. 

The product development checklist is being retired as the Governance team feels its not something they feel they should be providing to the teams. The checklist hasn't been updated in quite some time and should not be seen as a trusted source of truth. Shira and team working on an updated checklist which is expected to be visible to the teams around the March 31st timeframe. 

Shira has been OOO, but I would like to propose sharing that document with the Prod Ops team to see what feedback is received to ultimately ensure all documents and key areas (KPIs, analytics, etc.) are included and understood.

**Comment by dmkosko** [comment]
Lisa is working on revamping the playbook and potentially thinking about going in a new direction (will discuss with the team). 

Lisa and Dan still working on the roles and responsibilities document updates

Regarding the process for issue templates, before creating anything new, we should see if an existing one is available or if a deleted one can be reused.

**Comment by dmkosko** [comment]
Regarding the collab cycle, there are different stages of the process which require certain artifacts. There may be an area where we can get the Government and Contractor sides engaged and that would be the [Product Launch Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39845). Teams have mentioned this document is beneficial, but lacks recent updates.  

- [ ] Dan to list out current artifacts needed by touchpoint for collab cycle. The hope is to see what's available, what's missing, and what opportunity we have to update (date is TBD).

**Comment by lkoenigsberg** [comment]
@dmkosko , I've cleaned up the latest version of this document [here](https://dvagov-my.sharepoint.com/:w:/r/personal/lisa_koenigsberg_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7Bd9dabb4e-3160-43e8-aa3b-3e6bef8ad313%7D&action=edit&wdPid=2). What is the status of the last section?

**Comment by dmkosko** [comment]
Stakeholder section ready for review as of Wednesday morning. Made final edits Tuesday evening. Shared the update with Lisa on slack, but sharing here as well.

**Comment by dmkosko** [comment]
The roles and responsibilities have been finalized for the Product Lead and Manager sections. Dan will enter the information into GitHub as the one source of truth. We will close this ticket and open up a new one that goes into the next set of activities (i.e., communications, updating existing links on different pages, etc.).

The stakeholder section is a work in progress and we will continue iterating on.
