### ISSUE TITLE
Document change of tax-year steps to include scenario if IRS template changes

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#46210]
**What happens at the end of the year?**
**What needs to be done if the template changes?"**

**Comment by khandelwal** [comment]
This is now completed. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/product-playbook.md

**Comment by khandelwal** [comment]
This is now completed. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/product-playbook.md
