### ISSUE TITLE
Convert existing product documentation into MD files in Github

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#46226]
Add the following to Github as MD files:

- [x] https://docs.google.com/document/d/1JCDhIm7739KRZLNoqxF3dFnDpYE6xgLAERZ4SnFRGYU/edit#heading=h.jeom8qx51si1
- [x] https://docs.google.com/document/d/1RMy84KMu7mzaQznhD5vn4Q18oVlWsBYwP3hixqF3INY/edit
- [x] https://docs.google.com/document/d/1SVmdrkqBnCgD1gJ0RVYJ3CcwpfkdCGcRIU8xGr6jKQQ/edit#heading=h.3jtzz0py039g
- [x] https://docs.google.com/document/d/1El8-dBHfQHYvjZN1V_i_XTITslqKJgPjGOmkrk4VNU0/edit

All should be in this folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status

**Comment by sortizsh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Product%20Outline.md

**Comment by sortizsh** [comment]
Feature Brief 
[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Feature%20Brief.md]

**Comment by sortizsh** [comment]
technical discovery: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/technical%20discovery.md

**Comment by sortizsh** [comment]
Problem brief 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/problem%20brief.md
