### ISSUE TITLE
Application to Promote: sidekiq to staging

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46230]
### Acknowledge Instructions

- [X] I acknowledge that I have read the above instructions and understand the application name provided will be used to create various resources

### Application Name

sidekiq

### Environment

staging

### Maintainer(s)

lindseysaari

**Comment by LindseySaari** [comment]
PR opened here to add sidekiq helm charts: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/763

**Comment by jbritt1** [comment]
Automate PR reviewed/approved/merged.
