### ISSUE TITLE
Content consult: copy for new footer link to https://www.accesstocare.va.gov/

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#46237]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

Public Websites has a request to update VA health care providers  footer link to point to https://www.accesstocare.va.gov/, with a note from Dave to consult with SWC about link text. Ticket = [#10405](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10405). 

Current copy = "VA health care providers"

https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fcamo.githubusercontent.com%2F5111456e10a77d0cc2fb243ccfc486a039573e48f60c6e0e7b764cc766e8665d%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632386661356530646531313830326265353539656436322f32313339383030342d316437612d343131612d386231382d313564383564646563363463

https://dsva.slack.com/archives/C01K37HRUAH/p1661356800958849

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
 

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: no hard timing so far
- Estimated staging review date: "
- Content and IA work needed by: " 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner:  Dave Conlon
-	Product manager: Wes Rowe
-	Designer: n/a
-	FE engineer: tbd
-	Product/team Slack channel: #sitewide-public-websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by katherine-fung** [comment]
Hi @jilladams, 

Here's the copy for the new footer link text: 

VA health care access and quality

**Comment by jilladams** [comment]
Thank you!
