### ISSUE TITLE
Sign in to VA link dying in browser in staging

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#46232]
On staging, the link to "sign in to manage all appointments" on the pre check in confirmation page has now died twice for me and the browser times out. 

I would also check the "sign in" link in the "How can I updated my information?" accordion. 

These links may also be present in day of check in. 

All of this sort of matches what I've been seeing in GA with that the login page that has a high avg page load time. 

Unless this problem is specific to stage. 

![Screen Shot 2022-08-25 at 10.59.47 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/e8854213-e0c4-4150-aaa5-8249936bc2d5
)

## Tasks
- Verify this works in production
- Document why it doesn't work in Staging

**Comment by loripusey** [comment]
@loripusey We need to prod validate this

**Comment by loripusey** [comment]
no longer needed since switched to simplified header
