### ISSUE TITLE
Sentry docs points to outdated Github repo

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#46247]
### Description
https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry contains a link to outdated Github repo page

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-tagging-standards.md

**Comment by taylojill** [comment]
8/26/22 - Slack message sent to Jesse House requesting page review and update of hyperlinks.

**Comment by jhouse-solvd** [comment]
Samara and I reviewed this today. We'll take a look and figure out which links need to be updated.

**Comment by laucon** [comment]
Done
