### ISSUE TITLE
VAOS v2 - Expose mobile-ppms-service to Staff API Gateway

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#46267]
## Description
VAOS FE will need to expose `mobile-ppms-service` to Staff API Gateway. 

---

## Acceptance Criteria
More details will be provided. 

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by simiadebowale** [comment]
staff api url: https://staff.apps.va.gov/ppms/v1
vets-api should make a call using this base url for ppms in PROD.

cc: @cferris32 @ajmagdub

**Comment by ldelacosta** [comment]
We will need to confirm to see if the URL is used by other teams. Also, @simiadebowale will be reaching out to the facilities team to see if they can make the change for this. 

cc: @JRRoof

**Comment by ldelacosta** [comment]
Slack thread with the facilities team: https://dsva.slack.com/archives/C0FQSS30V/p1661795986259249

**Comment by ldelacosta** [comment]
Simi submitted a [post](https://dsva.slack.com/archives/CBU0KDSB1/p1661801298127749) in #vfs-platfrom-support.

**Comment by simiadebowale** [comment]
PR created for this issue: https://github.com/department-of-veterans-affairs/vets-api/pull/10592

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket. 

cc: @simiadebowale
