### ISSUE TITLE
SOCKS access for [Jessica Stump]

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#46263]
### Your Name

Jessica Stump

### Your Email

jessica.stump@adhocteam.us

### Your Role and Team

Senior UX Designer, 10-10 Health Apps

### Product Manager (PM) name and email

Heather Justice, heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman, patrick.bateman@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUlR4I5YtXMU87sZB8yZV5WU6BtqvXS7L+4jLJ4dKvFHW5Btq2ZGyoR3V+szlw6i6Hil9xU6MDCl6DJm7Sz7EyESvwCXXCop6mtS9EwT4IUAWf17RhUxbohNMBBvBdqb06B8HWdM+41oagZh0GNMKfogPaVHJjNPDNaAHoiz0a8EVzkD1Ln/njFD2WgiXNcngM71bMY8ss5XSpQaarphHxkewWBOK8WdU4dXSB9ryq6oVDhGb6umWxDM3oEZ1MoHGIRXc0fdzKrLwyuX0nP4LoGwW99m7SDDnx9EMph6pHbzl9z5CSYN2xQ52XS8jDx6KfK5neu7WH9a7mM73JiwHJVNZeQpPZqCIE4YLvzZs2YxGOF99DhRbhOIPTuwReu8olHca4tAfTW9bRQ8Kx9+QzYoOtea93LZirtQ2nIuhASe220i2+OMmxWK4dBzIwVglOj570s8Xa0i0K2g1yRUeLZDIqh6ceHuyocEoUGeFOxsAIkqRLgrlSjQUSImgw6cE= jessicastump@JessicaStumpMBP.hsd1.wa.comcast.net

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by kjduensing** [comment]
@jessicastump - SOCKS access granted. Please allow 5 - 10 minutes for changes to propagate. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
