### ISSUE TITLE
Implement linting rules to prevent use of the old api.va.gov hostname

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#46274]

**Comment by rmessina1010** [comment]
@madebydna, @oseasmoran73 
What is the status of the  api.va.gov transition? Would having these linting rules still be  helpful?

**Comment by oseasmoran73** [comment]
I am not as involved in the frontend aspect anymore, but I am curious what linting rules were going to be implemented? Would you happen to know?

**Comment by rmessina1010** [comment]
@oseasmoran73 -- The former RTT team was going to write linting rules to alert engineers about  the domain name change for the API (but we were waiting on the new domain to be implemented)

**Comment by rmessina1010** [comment]
Update from Andrea Singh:

> whole transition to the new vets-api domain names is canned, or at least put on ice. The original intent behind the migration was to prepare for the Lighthouse API Gateway migration out of the current environment and to a new API gateway - Apigee - in Google Cloud. That project was halted, Kong is still the API gateway in use, and I don't know of any immediate plans to change that. As such migrating to the use of the new domains is no longer necessary

Closing  ticket.
