### ISSUE TITLE
Update VA Sketch Cloud and Generate Presentation Links for the Happy Path

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46279]
## Tasks
- [x] Update VA Sketch Cloud so that it matches what is in production
   - Content
   - Function
- [x] Generate presentation links for all happy paths
    - [In person Pre-Check-in](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/prototype/a/BE60720E-7D9D-46BD-AF86-6332C23E7D8B) in Sketch Cloud
    - [In person Check-in](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/prototype/a/9F9F9F9F-E205-4F5E-9177-DD4AD750828C) in Sketch Cloud
    - [Telephone Pre-Check-in](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/prototype/a/407FA16E-4716-43C8-8898-B25F96F61001) in Sketch Cloud

**Comment by zach-park** [comment]
@loripusey , the happy path links are complete. Thank you!
