### ISSUE TITLE
Updates globally configured API URL for Dev & Staging

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#46271]

**Comment by Andrew565** [comment]
@laineymajor If this is still a ticket that needs to be worked on, could you add more description as to what work needs to be done? Please and thanks!

**Comment by CBonade** [comment]
Per Ray:
Were supposed to be provided with a date to proceed with this from Lighthouse in December. This never happened. Closing this ticket as stale.
