### ISSUE TITLE
[PO Escalation] Seeking approval to create a Platform DevOps Slack channel 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#46283]
### What is the issue

_Copied from #45927:_ 

As a byproduct of the recent re-organization and the restructuring of the operations/infra team, it's challenging to communicate effectively with other DevOps personnel on the platform. 

Having a dedicated Slack channel to coordinate DevOps personnel across Platform (w/ Identity, CMS) teams would be helpful. We think the channel should be private for now, and/or be restricted to specific teams/members. 

This might also dovetail nicely with the forthcoming DevOps Community of Practice.

### Who is it effecting or who will be effected

Dedicated DevOps personnel from Platform, Identity, and CMS teams. 

### What have you done to resolve this so far

- Created an issue in GitHub for tracking the setup of the proposed Slack channel (#platform-devops)
- Created an issue in GitHub to establish the DevOps Community of Practice
- Discussed with @little-oddball, @ph-One, and the Platform Infrastructure team 

### Dependencies

- Approval from Platform Leadership and OCTO-DE POs to ensure alignment on purpose and audience for this new communications channel

### What's at risk

Some risks: 

- Lack of clarity around the purpose of the channel
- Potential that support issues creep up in the wrong channel 
- The wrong audience for the channel dilutes Platform DevOps discussion 

### Recommendation(s)

Our recommendation is to **follow through w/ #45927 now**, by doing the following: 

- Create a new Slack channel in DSVA Slack: #platform-devops
- Set the purpose of the channel 
  - Note: Make it clear that support should continue through #vfs-platform-support
- Invite team members to the channel (see issue in question)

Separately, continue to prepare for the DevOps Community of Practice, planned to kick off in early Q4, 2022. 

### Additional Information

Relevant issues: 
- #45927
- #45129

**Comment by andreahewitt-odd** [comment]
@jhouse-solvd You can create the channel. You don't need OCTODE approval to create a slack channel.

**Comment by jhouse-solvd** [comment]
> @jhouse-solvd You can create the channel. You don't need OCTODE approval to create a slack channel.

Thank you!

**Comment by jhouse-solvd** [comment]
This issue can be closed. :)
