### ISSUE TITLE
Staging:  Clinics with Direct Scheduling Flag = False Display to Veteran for Direct Scheduling

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#46281]
**Note added by Marcy 10/14:**  The scenarios list below (summary data) where I indicated what passed and what failed do NOT line up with the details for each scenario (see attachment).  The detailed data is correct and should be used for testing.  I**GNORE THE FOUR SCENARIOS** listed below.  Here is what should be tested from the two failed scenarios in the document
1.  Cecil. Springfield Mental Health = Yes Any.  Clinic with DS Flag = False displaying to veteran for direct scheduling. 
2.  Ola.  Cheyenne Optometry= Yes Any. Clinic with DS Flag = False displaying to veteran for direct scheduling. 

Four scenarios
1.	Yes past appt in last 36 mos and DS flag = YES.  Morgan Mental Health clinic IEN 3977.  Passed.  Edgecombe Optometry clinic IENs: 408, 437 and 999.  Passed.
2.	No past appt in last 36 mos and DS flag = NO.  Morgan Mental Health clinic IEN 4293.  Failed.
3.	Yes past appt in last 36 mos and DS flag = NO. Edgecombe Optometry clinic IEN 855 - Failed.
4.	No past appt in last 36 mos and DS flag = YES. Edgecombe CPAP clinic IEN 1099. Passed.

**See attached document** that shows details related to the four scenarios:  Each scenario has the following sections:
1.  Patient past appointment history from Aug 26, 2002 - 36 mos. Appointments in bold are in the stop code as set in VATS.  
2.  CDW data for clinics for that site for that stop code. 
3.  Steps to recreate.
4.  VAOS screen shot of clinics displayed to veteran and backend endpoint with returned data.
5.  Screen shot after appointment date is selected and backend error.

**Attachment Link**:  [https://app.zenhub.com/files/133843125/5fd89684-f6c6-4cd7-b8ed-ab6fb361ad45/download](https://app.zenhub.com/files/133843125/5fd89684-f6c6-4cd7-b8ed-ab6fb361ad45/download)

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/a53f1770-c740-44e3-b64a-f0f6d79f3c0f)

**Comment by ldelacosta** [comment]
@marcynadeau  - @simiadebowale reviewed the ticket and the changes might not be ready by Thursday (I believe we were trying to do another pilot test in production). We will put this code under the `vaos-v2-next` toggle. If anything changes, Simi will update the ticket. Thanks!

**Comment by marcynadeau** [comment]
I completed additional testing and confirmed that clinic with DS flag = NULL are returned by Backend and F/E must is not displaying the clinic. This is as expected.  So the issue is only with clinics were DS flag = False.

**Comment by ldelacosta** [comment]
@marcynadeau - This is ready to be tested. Please let us know if you have any questions or issues. Thanks!

**Comment by marcynadeau** [comment]
Note, this should also be tested with Audiology. Please don't use Jphn Morrison, Cecil Morgan or Ola Edgecombe for testing Audiology because that will mess up other scripts.  Testing will have Audiology = Yes any. Then make sure patient has appts in last 36 mos in each of these clinics:
1.  Chyshr IEN 1020 Wheatland Audiology/WHT AUDIO VAR2 DS = Yes. Clinic should be in list for veteran to select.
2. Chyshr IEN 1014. Friendly Name Audiology/CHY AUDIOLOGY. DS = Yes. Clinic should be in list for veteran to select.
3. Chyhsr IEN 570 Chy C&P Audiology. DS = No. Clinic should not be in list for veteran to select.    Verify in response body but not displayed to veteran.

**Comment by ldelacosta** [comment]
Moving it back to In Progress since it requires re-work. Thanks!

**Comment by jenniemc** [comment]
This ticket is to fix the direct scheduling check for all types of care and add direct schedule past appointment check behind the `vaosV2Next` flag for both v0 and v2

History behind direct scheduling flow for v0: Based on the business logic of V0, past appt for the type of care is required for direct flow, otherwise user is sent to request flow.

> "Veterans are only able to use online scheduling if they’ve been seen at the selected facility for that type of care in the past 2 years. VAOS will automatically check their completed appointment history to make this determination.
> This logic applies to all care types/specialities including Primarcy Care and Mental Health"

> A key design principle for new VAOS is ensuring that Veterans are only seeing options that are available to them. This principle also applies to new business in which Veterans are only enabled for self schedule for VA appointments if they have been previously seen for that type of care at that specific VAMC

Reading the Design Decision, the intent is to make all the upgrades ( ie allow direct scheduling based on VATS settings) on V2. Read more [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/c530288e5bd7e979aa41e6149de8f45892ce5ad1/products/health-care/appointments/va-online-scheduling/product/decisions/decisions-faq.md#previously-seen-business-logic)

**Comment by ldelacosta** [comment]
Feature toggle is available to use. `va_online_scheduling_clinic_filter`

**Comment by ldelacosta** [comment]
@marcynadeau - The ticket is ready to be tested. Please let us know if you have any questions. Thanks!

**Comment by marcynadeau** [comment]
@ldelacosta This failed testing.  Now there is an entirely new issues are presenting.  VETERANS ELIGIBLE FOR DS DROPPED INTO REQUEST FLOW.

1.  Cecil. Springfield Mental Health = Yes Any.  Issues was that a clinic with DS Flag = False was displaying for veteran to select for direct scheduling. FIXED/PASSED
2.  Ola.  Cheyenne Optometry.  Issue was that a clinic with DS Flag = False was displaying for veteran to select for direct scheduling. FAILED but new issue found. Veteran should be able to direct schedule but is being dropped in Request flow.  So because of this can not test if the original issue was fixed.  
3.  Brienne. Cheyenne Optometry.  New scenario added for regression per my notes above.  FAILED.  Veteran should be able to direct schedule but is being dropped in Request flow.

**Comment by ldelacosta** [comment]
@beth-wodzinski @marcynadeau - We realized the feature toggle for the ticket was turned off. Can you re-test and let us know if you're getting the same results?

**Comment by jenniemc** [comment]
@beth-wodzinski reported an error when direct scheduling at Ft Colins for CPAP appointment.
Given that VATS setting for FTC CPAP is set to YES ANY, ola.e.edgecombe@id.me should be able to complete a direct schedule appointment for CPAP appt at Ft Colins. All the api calls returned show patient is eligible for direct schedule, facility is enabled for DS and there is a CPAP clinic returned for DS however, the POST call is returning a Bad Request with "not eligible to book appointment: facility-cs-direct-disabled". 

I believe this is a separate issue from original bug ticket and wonder if this could be a backend issue. 
@simiadebowale @ldelacosta

Here is the payload
```
{
    "kind": "clinic",
    "status": "booked",
    "clinic": "1099",
    "slot": {
        "id": "3230323231313031313930303A323032323131303132303030"
    },
    "extension": {
        "desiredDate": "2022-11-01T00:00:00+00:00"
    },
    "locationId": "983GC",
    "reasonCode": {
        "coding": [
            {
                "code": "New Problem"
            }
        ],
        "text": "jc new issue "
    }
}
```
The response 
```
    {
        "title": "Bad Request",
        "detail": "not eligible to book appointment",
        "code": "VAOS_400",
        "source": {
            "vamfUrl": "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1013120830V747912/appointments",
            "vamfBody": "{\"message\":\"not eligible to book appointment\",\"detail\":\"facility-cs-direct-disabled\"}",
            "vamfStatus": 400
        },
        "status": "400"
    }
```

Here’s the configuration call that confirms the facility has enabled for direct schedule
staging-api.va.gov/vaos/v2/scheduling/configurations?facility_ids[]=983QE&facility_ids[]=983QA&facility_ids[]=983GD&facility_ids[]=983GC&facility_ids[]=983GB&facility_ids[]=983&facility_ids[]=984&facility_ids[]=984GF&facility_ids[]=984GC&facility_ids[]=984GB&facility_ids[]=984GD&facility_ids[]=984GA
```
{
    "facilityId": "983GC",
    "services": [
        {
            "id": "cpap",
            "name": "CPAP Clinic",
            "stopCodes": [
                {
                    "primary": "349",
                    "secondary": "116",
                    "defaultForRequests": false
                }
            ],
            "direct": {
                "patientHistoryRequired": false,
                "patientHistoryDuration": 0,
                "canCancel": true,
                "enabled": true
            },
            "request": {
                "patientHistoryRequired": false,
                "patientHistoryDuration": 1095,
                "submittedRequestLimit": 2,
                "enterpriseSubmittedRequestLimit": 2,
                "enabled": true
            }
        },
```
Here’s the eligibility call that shows patient is eligible for direct scheduling to CPAP
staging-api.va.gov/vaos/v2/eligibility?facility_id=983GC&clinical_service_id=cpap&type=direct
```
{
    "id": "140f",
    "type": "patient_metadata",
    "attributes": {
        "decisionDate": "2022-10-18T18:40:55.3333Z",
        "clinicalServiceId": "cpap",
        "type": "direct",
        "eligible": true,
        "id": "140f"
    }
}
```

Here’s the clinic call that returns a single clinic and it is enabled for direct schedule
staging-api.va.gov/vaos/v2/locations/983GC/clinics?clinical_service=cpap
```
    {
        "id": "1099",
        "type": "clinics",
        "attributes": {
            "vistaSite": 983,
            "id": "1099",
            "serviceName": "FTC CPAP",
            "physicalLocation": null,
            "phoneNumber": null,
            "stationId": "983GC",
            "stationName": "CHYSHR-Fort Collins VA Clinic",
            "primaryStopCode": 349,
            "primaryStopCodeName": "SLEEP MEDICINE",
            "secondaryStopCode": 116,
            "secondaryStopCodeName": "RESPIRATORY THERAPY",
            "patientDirectScheduling": true,
            "patientDisplay": true,
            "char4": "BPRI"
        }
    }
```

**Comment by beth-wodzinski** [comment]
I believe this passes testing. 

Cases executed:

Cecil Morgan/Mental Health/Springfield. Only Clin A should be offered for direct scheduling. PASS.
Ola Edgecombe/Optometry/Cheyenne. Only Chy Opt Var 1 and Chy Visual Field should display. PASS.
Ola Edgecombe/CPAP/FTC. Only FTC Cpap should display. PASS.
Brienne Ferrara/Audiology/Cheyenne. Wheatland Audiology and Friendly name Audiology should display. PASS.

We did run into errors trying to actually direct schedule some of these, but determined that it's a back end issue and outside the scope of this defect. Front end is no longer offering clinics where direct scheduling is set to false. 

@ldelacosta @jenniemc

**Comment by marcynadeau** [comment]
https://issues.mobilehealth.va.gov/browse/VAOSR-4628. This defect was logged for the above backend issue.

**Comment by ldelacosta** [comment]
This ticket has been validated. Closing out the ticket!
