### ISSUE TITLE
[Bug] VAOS - Canceling appointment changes appt-time

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#46298]
## What happened?
On **Review Instance** http://4eff86bce0676764530f60eddd7998c6.review.vetsgov-internal/ , **Your Appointments** [list] page, after Cancelling the pre-existing appointment, the appointment-time changed.

[Ryan, I assigned directly to you since Leah's out-of-office.  I added front-end label, but this could also be API/backend related.  Feel free to also add unplanned work label.]

## Specs:
- Device: MacBook Pro
- Browsers: Chrome & Firefox
- Test User _(if applicable)_: patient998@id.me [see [Staging Test-Accts for VAOS](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md) doc for passwords]

## Steps to Reproduce
- URL: http://4eff86bce0676764530f60eddd7998c6.review.vetsgov-internal/health-care/schedule-view-va-appointments/appointments/
- Test User _(if applicable)_: [see **Specs** above]
- On **Your appointments** page, in the listed **appointment-card** for **Saturday, October 1, 9:00 a.m. MT, Cheyenne VA Medical Center**, click **Details** link.
- On **Appointment detail** page, click **Cancel appointment** link.
- In **Are you sure...** confirmation dialog-box, click **Yes...** button.
- In **...has been canceled** success dialog-box, click **Continue** button.
- On underlaying page, observe that appointment time has changed.
[The time also remains mismatched after you return to the list-page and click Details link again.]

### Screenshots

List-page appointment-card [9:00]:
![image](https://user-images.githubusercontent.com/587583/187006228-078bd23e-7525-4440-b374-c108ec5dc923.png)

Detail page post-cancelation [7:00]:
![image](https://user-images.githubusercontent.com/587583/187006283-c2238753-fa6d-4b88-be26-bd6e866490c3.png)

## Desired behavior
- [ ] After cancelling an appointment, the Detail-page appointment-time should match that of the appointment that was cancelled.

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ryanshaw** [comment]
I did a little digging on this using the same test user mentioned in the description. 

When loading the appointment list page, this is returned from the endpoint (this is a partial snippet of the response).

```json
{
            "id": "103092",
            "type": "appointments",
            "attributes": {
                "id": "103092",
                "identifier": [
                    {
                        "system": "http://med.va.gov/fhir/urn/vaos/vista/983/appointment/id",
                        "value": "1135;20221001.090000"
                    }
                ],
                "kind": "clinic",
                "status": "booked",
                "serviceType": "clinicalPharmacyPrimaryCare",
                "patientIcn": "1013125218V696863",
                "locationId": "983",
                "clinic": "1135",
                "start": "2022-10-01T15:00:00Z",
                "end": "2022-10-01T16:00:00Z",
                "minutesDuration": 60,
                "slot": {
                    "id": "3230323231303031313530303A323032323130303131363030",
                    "start": "2022-10-01T15:00:00Z",
                    "end": "2022-10-01T16:00:00Z"
                },
                "cancellable": true,
                "extension": {
                    "ccLocation": {
                        "address": {}
                    },
                    "vistaStatus": [
                        "FUTURE"
                    ]
                },
```

Notice that `attributes.start` and `attributes.end` are the same as `attributes.slot.start` and `attributes.slot.end`.

After cancelling this appointment, the following response is returned from the endpoint and those attributes do not match. The cancelled appointment view displays timestamps from `attributes.start` and `attributes.end` which are two hours earlier. 

Notice that `attributes.start` and `attributes.end` are the **NOT the same** as `attributes.slot.start` and `attributes.slot.end`.

```json 
 {
        "id": "103092",
        "type": "appointments",
        "attributes": {
            "id": "103092",
            "identifier": [
                {
                    "system": "http://med.va.gov/fhir/urn/vaos/vista/983/appointment/id",
                    "value": "1135;20221001.090000"
                }
            ],
            "kind": "clinic",
            "status": "cancelled",
            "serviceType": "clinicalPharmacyPrimaryCare",
            "patientIcn": "1013125218V696863",
            "locationId": "983",
            "clinic": "1135",
            "start": "2022-10-01T13:00:00Z",
            "end": "2022-10-01T16:00:00Z",
            "minutesDuration": 60,
            "slot": {
                "id": "3230323231303031313530303A323032323130303131363030",
                "start": "2022-10-01T15:00:00Z",
                "end": "2022-10-01T16:00:00Z"
            },


```

**Comment by tlei123** [comment]
@ryanshaw , thx for confirming it's not a frontend bug!  This anomaly is also unique to this test-user/appoinment &mbash; I've just double-checked the other test-users cancellations and they're fine.

Closing this bug now.  Feel free to re-open if you or backend teammate(s) want to troubleshooting further.
