### ISSUE TITLE
SOCKS access for Aaron Read

### ISSUE THREAD

**Issue by Asterix22** [department-of-veterans-affairs/va.gov-team#46299]
### Your Name

Aaron Read

### Your Email

Aaron.Read@va.gov

### Your Role and Team

MyHealtheVet Secure Messaging

### Product Manager (PM) name and email

Lichelle Baine Lichelle.Bain@va.gov

### Product Owner (PO) name and email

Patricia Henry Patricia.Simon-Wigfield@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1enkPMLbRHSEt6nmWoTJkpKkbYq7cu8S9H8zA32SSsEuXH1zfbBv63OZgUqD8UJvPix0hMMEAI6ROCQV2MTC/XiYuNW9ZtrcgGRN2Q3MGj84Nb1feNy1dPAFJlyNrNlSVyTX3RhceUN+hz90av8zQ4GijOSAM59RQkJfntPyBDoXrLfGqT1syZludpISYzeFJCfmaPsGS6M9RMYe/bRl4ibm/vDInrspfPQTcQnUr0+gC6sBYfRtHRpB7LRrrDnaWmReNPX0HbwYmWoUK6jXFlgZLw0uqvfihgrWtEW1P128/jzCtEYKff2sT+SNkR1wb3iiH1Pqi1LSZRizVSpRT+HHLPUzrpsXG1ZseOjAZq3YM+5vwByYQBKVDbE3MFHsK7KeJwN3rsCbrxxTyFsaoy/8bepFi6jakGCvigYIS7464vhsNOCoGghbT8vauRsd/Z96bXqi1RJlhEib+VK3Mr2XgmRmzbGN8foGQFZXe3YmSELXfPO721j9F0rCFUkE= aaronread@Aarons-MacBook-Pro.local

### E-QIP Transmittal Confirmation
![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/125288357/77cd478a-7fc4-4347-bff1-845de5cc8959)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@Asterix22 Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
