### ISSUE TITLE
callback 202 error update language

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46291]
When a user gets a 202 error, often times it will be because they started auth from a different browser. We should add language to inform the user we had a network error and they should try to login again.

**Comment by AGarcia-Clarity** [comment]
Updates language to add the Network Error portion and to ask the user to please sign in again.  There might be a bug when a user clicks the Sign in button on the AuthApp page in which a user could have attempted to sign in with OAuth and the Sign in button forces the user to authenticate with eAuth
