### ISSUE TITLE
AWS access for Eugene Lynch

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#46302]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Eugene Lynch

### Your Email

eugene.lynch@coforma.io

### Team, Role, and Company of the target individual

Benefits, Software Engineer, Coforma

### Product Manager (PM) name and email

Sade Ragsdale, sade@coforma.io

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

I recently joined the VA Benefits team 1. I need access to any resources necessary to develop features, bugfixes, and conduct investiations on, the vets-api and vets-website apps. Thank you.

### Access Expiration

ongoing

### Additional Notes

COR - Keith Riley
VOR - Jeff Langworthy

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by calquisola** [comment]
@data-doge is part of the VFS roster.

**Comment by calquisola** [comment]
For AWS ACCESS
User: Eugene Lynch
COR: Keith Riley
VOR: Jeff Langworthy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by calquisola** [comment]
Hi @data-doge,

Do you need the same access as Kyle Soskin's?

**Comment by data-doge** [comment]
@calquisola Yes, I believe so. Thank you!

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Awaiting further information from VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
VOR confirmed eQIP, @data-doge can you be a little more specific of which permissions you need, which environments, etc...? Is there someone on your team that has a set of permissions that should apply to you as well?

**Comment by td-usds** [comment]
@rmtolmach or @oseasmoran73  could you ping me via slack w.r.t. what permissions Kyle Soskin currently has? I want to make sure we grant enough, but also not too much, permissions...

**Comment by td-usds** [comment]
Access via `dsva-vagov-developers` approved

**Comment by oseasmoran73** [comment]
Reached out to @data-doge via slack to provide information regarding AWS account. Should you run into any issues please feel free to submit request in #vfs-platform-support channel or reopen this ticket.

Closing!

**Comment by data-doge** [comment]
@oseasmoran73 can you help me get view/edit access to AWS parameter store?

**Comment by data-doge** [comment]
@oseasmoran73 Specifically, I need view/edit access to `/dsva-vagov/vets-api/staging/lgy_base_url` in parameter store. Thanks!
