### ISSUE TITLE
Analytics Implementation or QA Support for VA SSO

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#4630]
# Analytics Implementation or QA Request

## Description
- Is this request for Google Analytics implementation or QA?

QA/verification. I've added a new tag and trigger in Google Tag manager and I want to make sure it's properly set up for tracking in Google Analytics

- Who is this request for?

    - Insights Team
    
- What team/project is this work for?
    This is for the SSO project being worked on by Ad Hoc. As part of this, we want to measure the current amount of users that are attempting to navigate to eBenefits from VA.gov. This will help put a number to the scope of users that would benefit from an SSO solution.
    
- Provide the Domain where Google Analytics needs to be implemented
    Production
    
    _Identify if PII is passed in URL or title tag_
    
    - no
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Target launch for SSO is March. Ideally we would be able to collect metrics for a while before then.

- Typical Website Interactions to Track
   
    - All of the places a user navigates to eBenefits from VA.gov when they are currently logged in. Frontend code for that was done [here](https://github.com/department-of-veterans-affairs/vets-website/pull/10874), in about 12 different places on VA.gov
    
- Sample Users when authentication is required

    -  There shouldn't be specific users to test with. The only checks some links check for if a user is logged in _at all_ and not for a specific user

- Test Users to replicate the event

    - See previous

- Certain conditions/responses that need to be reviewed

    - Quite a few of the added events are when a user is implicitly logged in. There are a few cases in which the event only fires when a user is logged in. I will add those from the PR linked above for specific cases. 

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@hinzed1127 Looping in @jonwehausen as well for visibility and for review of the code in the places where this will be inserted.

I made a small tweak within the GTM workspace to follow a convention that brings in `{{event}}` within the Event Label. Another suggestion is to add an Event Action (e.g. `Navigation - Link to eBenefits`)

**Comment by nedierecel** [comment]
Hi @hinzed1127 - I wanted to check in on this issue and see if you have any questions. Thanks!

**Comment by hinzed1127** [comment]
sorry the delay, @nedierecel . The event name refactor just got merged and should get onto staging in the next deploy. I'll keep you posted on that

**Comment by hinzed1127** [comment]
@nedierecel this change should be deployed now if you want to review/validate

**Comment by nedierecel** [comment]
Thanks @hinzed1127 We will review tomorrow morning and send feedback!

**Comment by nedierecel** [comment]
@hinzed1127 Thank you for updating me on the status. I made a tweak within Google Tag Manager to leverage an existing Navigation Lookup table and a Navigation tag we use across Interactions.

I am halfway finished through validating. Of the ones I was able to tackle yesterday, this is my feedback so far:

- Claims Decision: Correct
- NoClaims: Correct
- How to File a Claim Page: Correct when warning appears for "First Time Filing" prompt; I did not see an `nav-` event for this prompt:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/facd4556-43b1-4c36-9154-7fc904edac12)

- Payment Information on Profile360 - Correct
- Post911 Status - Tool was down, so I will revisit

Additionally, I came across these calls-to-action for eBenefits on the following pages. Should these also utilize the same event tracking? 

https://staging.va.gov/records/download-va-letters/
https://staging.va.gov/records/download-va-letters/letters/letter-list
Button on https://staging.va.gov/va-payment-history/ and https://staging.va.gov/change-direct-deposit/

**Comment by nedierecel** [comment]
@hinzed1127 To help facilitate the rest of the QA, can you list the URLs for the remaining places I should validate for the navigation?

Thanks!

**Comment by hinzed1127** [comment]
Hey @nedierecel, the missing "how to file a claim" page update is in code review and just needs to get merged and deployed (https://github.com/department-of-veterans-affairs/vets-website/pull/11694)

The VA letters ones don’t need the GA event because they doesn’t directly navigate to eBenefits from what I can tell.

The last few call to action links unfortunately seem to be using alerts created from Drupal, so there might not be an easy way to add them there. I will inquire about workarounds but don’t see that as a blocker for the rest of the events.

**Comment by nedierecel** [comment]
@hinzed1127 Thanks for the update. I published the changes in a different Google Tag Manager workspace (there were some recent navigation updates in a lookup table that we had to push out with this ticket). 

You might see your original GTM request withdrawn, but you can disregard.

_Screenshot below of new tracking added to the lookup table_:
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/9ad9a0fa-4056-49a9-a9cd-f03966b320df)

**Comment by hinzed1127** [comment]
Great! Verifying that I'm able to view this event successfully in GA. Is there anything else required to consider complete and close this issue?

**Comment by nedierecel** [comment]
@hinzed1127 I think that will wrap up this issue. As you monitor, feel free to reach out if you see anything out-of-the-ordinary. Issues to look for might be complete gaps on pages we had validated or instances where the Category, Action, or Label might be coming in as `(not set)`.
