### ISSUE TITLE
Changes Resulting from State Department QA

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46310]
## Background
We received the QA comments back from the translators. Here is the commented [file ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/LS_2022-0117053-A-SPA-LQM-v3-8.13.22_Spanish%20Round%202%20-%20Pre-Check-in%20Workflow%20in%20Spanish.pdf)we received.

There are 7 changes that need to be made. 

## Tasks 
- Make the 7 changes
- Generate English and Spanish screen shots to reflect the changes

## Change 1
- Change "Phone call" to "Llamada" on all pages where it's used
    - Pre-Check-in "Respond to Questions" page
    - Pre-Check-in "You've Completed Pre-Check-in" page
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/6fb47a12-01aa-4e68-9444-5535a43604e1)

## Change 2
- Change "call 911, or" to "llame al 911, o" in the "Need Help?" section
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/e7524dec-374c-4b9f-b76e-48ce95fa92b7)

## Change 3
- Change "In person" to "En persona" on all pages where it's used
    - Pre-Check-in Respond to Questions page
    - Pre-Check-in Completed page
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/aa1fa2ad-ddea-43df-8d15-d9d851b97876)

## Change 4
- Change "Type of care" to "Tipo de cuidado"  on all pages where it's used
    - Pre-Check-in "Respond to Questions" page
    - Pre-Check-in "You've Completed Pre-Check-in" page
    - Check-in "Your appointments" page
    - Check-in "You're checked in" page
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/aa1fa2ad-ddea-43df-8d15-d9d851b97876)

## Change 5
- Change  "Provider" to "Proveedor" on all pages where it's used
    - Pre-Check-in "Respond to Questions" page
    - Pre-Check-in "You've Completed Pre-Check-in" page
    - Check-in "Your appointments" page
    - Check-in "You're checked in" page
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/aa1fa2ad-ddea-43df-8d15-d9d851b97876)

## Change 6
- Change  "Location" to "Lugar" on all pages where it's used
    - Pre-Check-in "Respond to Questions" page
    - Pre-Check-in "You've Completed Pre-Check-in" page
    - Check-in "Your appointments" page
    - Check-in "You're checked in" page
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/aa1fa2ad-ddea-43df-8d15-d9d851b97876)

## Change 7
- Add link to VA login [with "(en inglis)"] to the Spanish content display for the "What is Pre-Check-in?" accordion
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/c6341561-8cb0-457a-9417-31b0d3f15936)
    - This is how it appears in English
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/7b47030c-564e-4ee8-a8f4-19f5f884536e)

**Comment by brdunfield** [comment]
[https://app.zenhub.com/files/133843125/bb9b5df5-9221-4398-ba62-4f7ed235bee7/download](https://app.zenhub.com/files/133843125/bb9b5df5-9221-4398-ba62-4f7ed235bee7/download)

@loripusey I have added these changes to the feature branch, and attached screenshots generated from the current state of that branch. Let me know if you need anything else!

**Comment by loripusey** [comment]
Thanks @brdunfield !

**Comment by loripusey** [comment]
@brdunfield I need screen shots that show appointments labelled as telephone or in person appointments (need both scenarios). The screenshots you provided don't show the appointments labelled.

**Comment by loripusey** [comment]
@brdunfield Also, the "or" should be changed to "o"
![image](https://user-images.githubusercontent.com/86678742/187927960-0518eeee-4eb4-45f4-aec1-1f381e19e0fd.png)

**Comment by brdunfield** [comment]
@loripusey Here are the updated screenshots:
[https://app.zenhub.com/files/133843125/4d16fd18-c3c9-4f0a-85a2-45c3401c85a1/download](https://app.zenhub.com/files/133843125/4d16fd18-c3c9-4f0a-85a2-45c3401c85a1/download)

Here are some more screenshots to specifically see both in-person and phone appointments:
[https://app.zenhub.com/files/133843125/bed00438-722c-454a-9c0d-8b6e2f63603e/download](https://app.zenhub.com/files/133843125/bed00438-722c-454a-9c0d-8b6e2f63603e/download)

**Comment by brdunfield** [comment]
@loripusey Full in-person screenshots with icons
[https://app.zenhub.com/files/133843125/f1897bf9-2548-4419-9279-151b0e4e6ff3/download](https://app.zenhub.com/files/133843125/f1897bf9-2548-4419-9279-151b0e4e6ff3/download)

Phone appointment screenshots:
[https://app.zenhub.com/files/133843125/2666f8b1-ecae-49c0-afdb-7075608c895b/download](https://app.zenhub.com/files/133843125/2666f8b1-ecae-49c0-afdb-7075608c895b/download)

**Comment by loripusey** [comment]
On 9/2/2022: Sent responses to State Department QA comments along with new screenshots of the implemented changes.
- [Uploading Responses to LS_2022-0117053-A-SPA-LQM-v3-8.13.22_Spanish Round 2 - Pre-Check-in Workflow in Spanish.pdf…])
- [Screenshots for Responses to LS_2022-0117053-A-SPA-LQM-v3-8.13.22_Spanish Round 2 - Pre-Check-in Workflow in Spanish.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9479499/Screenshots.for.Responses.to.LS_2022-0117053-A-SPA-LQM-v3-8.13.22_Spanish.Round.2.-.Pre-Check-in.Workflow.in.Spanish.pdf)
