### ISSUE TITLE
Update the Cypress Viewport Updater

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#46314]
## Issue Description
Cypress 10.00 changed the Cypress config file from `json` to `js` causing the Cypress Viewport Updater to break. May's values were copied over to the `js` file but it hasn't been updated since.

---
## Tasks
- [x] Update the Sidekiq job that updates the `json` config to update the `js` config so viewports are kept up to date.
## Acceptance Criteria
- [x] The updated Sidekiq job will successfully update the Cypress `js` config with last month's viewport data

**Comment by holdenhinkle** [comment]
Draft PR - https://github.com/department-of-veterans-affairs/vets-api/pull/10580

**Comment by holdenhinkle** [comment]
I'm almost there. This took a little longer than expected.

Ruby cannot parse JavaScript. There's an old gem that can do it, but it hasn't been touched in 5-6 years and I didn't want to introduce another Gem to `vets-api` for something so small, let alone one that's so old.

Here's the current output of rewriting `cypress.config.js` to update the viewport values:

```JavaScript
const { defineConfig } = require('cypress');

const cypressConfig = {
    viewportWidth: 1920,
    viewportHeight: 1080,
    modifyObstructiveCode: false,
    fixturesFolder: 'src',
  waitForAnimations: false,
  chromeWebSecurity: false,
  videoCompression: false,
  retries: {
      runMode: 2,
      openMode: 0,
  },
  env: {
      codeCoverage: {
        exclude: ['src/**/*.cypress.spec.js?(x)'],
    },
    vaTopMobileViewportsIterateUptoIndex: 0,
    vaTopMobileViewports: [
        {
          list: 'VA Top Mobile Viewports',
        rank: 1,
        devicesWithViewport:: 'iPhone 12 Pro, iPhone 12',
          'iPhone XS Max, iPhone XR, iPhone 11, iPhone 11 Pro Max',
        percentTraffic: '7.8%',
        percentTrafficPeriod: '7.8%',
        viewportPreset: 'va-top-mobile-1',
        width: 390,
        height: 844,
      },
      {
          list: 'VA Top Mobile Viewports',
        rank: 1,
        devicesWithViewport: 'iPhone 12 Pro, iPhone 12',
        percentTraffic: '7.8%',
        percentTrafficPeriod: '7.8%',
        viewportPreset: 'va-top-mobile-1',
        width: 390,
        height: 844,
      },
      {
          list: 'VA Top Mobile Viewports',
        rank: 1,
        devicesWithViewport: 'iPhone 12 Pro, iPhone 12',
        percentTraffic: '7.8%',
        percentTrafficPeriod: '7.8%',
        viewportPreset: 'va-top-mobile-1',
        width: 390,
        height: 844,
      },
      {
          list: 'VA Top Mobile Viewports',
        rank: 1,
        devicesWithViewport: 'iPhone 12 Pro, iPhone 12',
        percentTraffic: '7.8%',
        percentTrafficPeriod: '7.8%',
        viewportPreset: 'va-top-mobile-1',
        width: 390,
        height: 844,
      },
      {
          list: 'VA Top Mobile Viewports',
        rank: 1,
        devicesWithViewport:: 'iPhone 12 Pro, iPhone 12',
          'iPhone SE 2nd gen, iPhone 6, iPhone 6s, iPhone 7, iPhone 8',
        percentTraffic: '7.8%',
        percentTrafficPeriod: '7.8%',
        viewportPreset: 'va-top-mobile-1',
        width: 390,
        height: 844,
      },
    ],
    vaTopTabletViewportsIterateUptoIndex: 0,
    vaTopTabletViewports: [
        {
          list: 'VA Top Tablet Viewports',
        rank: 1,
        devicesWithViewport:: 'iPad 1-6, iPad mini, iPad Air 1-2, iPad Pro (1st gen 9.7\")',
          'iPad 1-6, iPad mini, iPad Air 1-2, iPad Pro (1st gen 9.7\")',
        percentTraffic: '0.79%',
        percentTrafficPeriod: '0.79%',
        viewportPreset: 'va-top-tablet-1',
        width: 768,
        height: 1024,
      },
      {
          list: 'VA Top Tablet Viewports',
        rank: 1,
        devicesWithViewport:: 'iPad 1-6, iPad mini, iPad Air 1-2, iPad Pro (1st gen 9.7\")',
          'Amazon KSFUWI Fire HD 10 (2017), Amazon KFMAWI Fire HD 10 (2019), Samsung SM-T580 Galaxy Tab A 10.1, Samsung SM-T510 Galaxy Tab A 10.1 (2019), Samsung SM-T560NU Galaxy Tab E',
        percentTraffic: '0.79%',
        percentTrafficPeriod: '0.79%',
        viewportPreset: 'va-top-tablet-1',
        width: 768,
        height: 1024,
      },
      {
          list: 'VA Top Tablet Viewports',
        rank: 1,
        devicesWithViewport:: 'iPad 1-6, iPad mini, iPad Air 1-2, iPad Pro (1st gen 9.7\")',
          'Amazon KFGIWI Kindle Fire HD 8 2016, Amazon KFDOWI Kindle Fire HD 8 (2017), Amazon KFKAWI Fire HD 8 (2018), Amazon KFKAWI Fire HD 8 (2018)',
        percentTraffic: '0.79%',
        percentTrafficPeriod: '0.79%',
        viewportPreset: 'va-top-tablet-1',
        width: 768,
        height: 1024,
      },
      {
          list: 'VA Top Tablet Viewports',
        rank: 1,
        devicesWithViewport: 'iPad 1-6, iPad mini, iPad Air 1-2, iPad Pro (1st gen 9.7\")',
        percentTraffic: '0.79%',
        percentTrafficPeriod: '0.79%',
        viewportPreset: 'va-top-tablet-1',
        width: 768,
        height: 1024,
      },
      {
          list: 'VA Top Tablet Viewports',
        rank: 1,
        devicesWithViewport:: 'iPad 1-6, iPad mini, iPad Air 1-2, iPad Pro (1st gen 9.7\")',
          'This viewport is missing from the devices lookup table. Please contact the Testing Tools Team to have it added.',
        percentTraffic: '0.79%',
        percentTrafficPeriod: '0.79%',
        viewportPreset: 'va-top-tablet-1',
        width: 768,
        height: 1024,
      },
    ],
    vaTopDesktopViewportsIterateUptoIndex: 0,
    vaTopDesktopViewports: [
        {
          list: 'VA Top Desktop Viewports',
        rank: 1,
        devicesWithViewport: 'This property is not set for desktops.',
        percentTraffic: '13.24%',
        percentTrafficPeriod: '13.24%',
        viewportPreset: 'va-top-desktop-1',
        width: 1920,
        height: 1080,
      },
      {
          list: 'VA Top Desktop Viewports',
        rank: 1,
        devicesWithViewport: 'This property is not set for desktops.',
        percentTraffic: '13.24%',
        percentTrafficPeriod: '13.24%',
        viewportPreset: 'va-top-desktop-1',
        width: 1920,
        height: 1080,
      },
      {
          list: 'VA Top Desktop Viewports',
        rank: 1,
        devicesWithViewport: 'This property is not set for desktops.',
        percentTraffic: '13.24%',
        percentTrafficPeriod: '13.24%',
        viewportPreset: 'va-top-desktop-1',
        width: 1920,
        height: 1080,
      },
      {
          list: 'VA Top Desktop Viewports',
        rank: 1,
        devicesWithViewport: 'This property is not set for desktops.',
        percentTraffic: '13.24%',
        percentTrafficPeriod: '13.24%',
        viewportPreset: 'va-top-desktop-1',
        width: 1920,
        height: 1080,
      },
      {
          list: 'VA Top Desktop Viewports',
        rank: 1,
        devicesWithViewport: 'This property is not set for desktops.',
        percentTraffic: '13.24%',
        percentTrafficPeriod: '13.24%',
        viewportPreset: 'va-top-desktop-1',
        width: 1920,
        height: 1080,
      },
    ],
  },
  e2e: {
      setupNodeEvents(on, config) {
        return require('../src/platform/testing/e2e/cypress/plugins/index')(
          on,
          config,
        );
    },
    baseUrl: 'http://localhost:3001',
    specPattern: 'src/**/tests/**/*.cypress.spec.js?(x)',
    supportFile: 'src/platform/testing/e2e/cypress/support/index.js',
  },
};

module.exports = defineConfig(cypressConfig);
```

I need to fix the values for `devicesWithViewport` which often span more than 1 line. There's also a little funkiness with some indentation.

Then I need to update some tests in `vets-api`.

I should have this done tomorrow.

**Comment by holdenhinkle** [comment]
I've got it working, but I think I need to address the long lines on `devicesWithViewport` - https://github.com/department-of-veterans-affairs/vets-website/pull/22061/files

I'm guessing the long lines will result in linting errors.

**Comment by holdenhinkle** [comment]
yup^
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/edfaaea0-5f39-4c38-8d62-bc01b30669a6)

**Comment by holdenhinkle** [comment]
I got this working nicely - https://github.com/department-of-veterans-affairs/vets-website/pull/22073

I started updating/writing new tests in `vets-api` where the code to rewrite the `cypress.config.js` lives and ran into problems when I had to re-record GitHub VCR cassettes where the request is being made my an authorized user.  After several hours, I discovered that the authorization settings in `settings.local.yml` aren't picked up by `rspec`. I tried moving them to `settings/test.yml` and `rspec` picked them up there. I don't like the settings being in that file, even for a second, because it's not gitignored and it's inside the project. Where to put the settings?

I'll pick this back up tomorrow.

**Comment by holdenhinkle** [comment]
Code to select the part of the `cypress.config.js` file want, parse the `js` `object` into a `json` `string`, then call `JSON.parse` on it to convert it into a `hash`:

```
require 'json'
require 'byebug'

LINES_TO_SKIP = %w[vaTopTabletViewportsIterateUptoIndex vaTopDesktopViewportsIterateUptoIndex].freeze
SPECIAL_CHARS = %w[\[ \] { }].freeze

def number?(line)
  line.match(/^-?[0-9]+\..?[0-9]+$/) || line.to_i.to_s == line
end

def special_char?(line)
  SPECIAL_CHARS.any? { |char| line.include?(char) }
end

lines = ''

File.open('cypress.config.js') do |f|
  f.each_line { |line| lines << line }
end

# select lines from file
select_lines = false

line_selection = lines.split("\n").each_with_object([]) do |line, array|
  next if LINES_TO_SKIP.any? { |line_to_skip| line.include?(line_to_skip) }

  select_lines = true if line.include?('vaTopMobileViewports:')
  select_lines = false if line.include?('e2e: {')
  array << line.strip if select_lines
end

# remove unnecessary chars from each line
line_selection = line_selection.map do |line|
  line = line.sub(':', ':DELINEATOR') if line.include?(': ')
  line = line.split(':DELINEATOR').map(&:strip) if line.include?('DELINEATOR')
  line
end

line_selection = line_selection.flatten.map do |line|
  line = line.gsub('"', '\"') if line.include?('"') && line.scan('"').count.odd? # escape double quotes not in a pair
  line = line.gsub("'", '') if line.include?("'") # remove single quotes
  line = line.gsub(',', '') if line.end_with?(',') # remove commas
  line
end

# add commas and double quotes where necessary to format lines into JSON
in_object = false
object_prop_index_is_even = nil
object_prop_index_is_odd = nil

line_selection = line_selection.each_with_index.map do |line, index|
  # set flags
  line << ',' if line == ']' && line_selection[index + 1] != '}'

  if line == '{'
    in_object = true
    object_prop_index_is_even = (index + 1).even?
    object_prop_index_is_odd = (index + 1).odd?
  end

  in_object = false if line == '}'

  # wrap strings in double quotes
  line = "\"#{line}\"" if !number?(line) && !special_char?(line)

  # append colon to properties/keys
  line << ':' if %w[\[ \] { }].none? { |char| line.include?(char) } &&
                 (line_selection[index + 1] == '[' ||
                 line_selection[index + 1] == '{' ||
                 in_object && object_prop_index_is_even && index.even? ||
                 object_prop_index_is_odd && index.odd?)

  # append comma where necessary (at the end of most values, etc.)
  line << ',' if line == '}' && line_selection[index + 1] == '{' ||
                 (in_object &&
                 !line.include?('{') &&
                 !line_selection[index + 1].include?('}') &&
                 !line_selection[index + 1].include?(']') &&
                 (object_prop_index_is_even && index.odd? || object_prop_index_is_odd && index.even?))

  line
end

# puts '{' + line_selection.join()

puts JSON.parse("{#{line_selection.join}")

```

Output:
`{"vaTopMobileViewports"=>[{"list"=>"VA Top Mobile Viewports", "rank"=>1, "devicesWithViewport"=>"iPhone XS Max iPhone XR iPhone 11 iPhone 11 Pro Max", "percentTraffic"=>"6.81%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-mobile-1", "width"=>414, "height"=>896}, {"list"=>"VA Top Mobile Viewports", "rank"=>2, "devicesWithViewport"=>"iPhone 12 Pro iPhone 12", "percentTraffic"=>"6.8%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-mobile-2", "width"=>390, "height"=>844}, {"list"=>"VA Top Mobile Viewports", "rank"=>3, "devicesWithViewport"=>"iPhone 12 Pro Max", "percentTraffic"=>"5.18%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-mobile-3", "width"=>428, "height"=>926}, {"list"=>"VA Top Mobile Viewports", "rank"=>4, "devicesWithViewport"=>"iPhone X iPhone XS iPhone 11 Pro", "percentTraffic"=>"4.62%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-mobile-4", "width"=>375, "height"=>812}, {"list"=>"VA Top Mobile Viewports", "rank"=>5, "devicesWithViewport"=>"iPhone SE 2nd gen iPhone 6 iPhone 6s iPhone 7 iPhone 8", "percentTraffic"=>"2.95%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-mobile-5", "width"=>375, "height"=>667}], "vaTopTabletViewports"=>[{"list"=>"VA Top Tablet Viewports", "rank"=>1, "devicesWithViewport"=>"iPad 1-6 iPad mini iPad Air 1-2 iPad Pro (1st gen 9.7\")", "percentTraffic"=>"0.82%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-tablet-1", "width"=>768, "height"=>1024}, {"list"=>"VA Top Tablet Viewports", "rank"=>2, "devicesWithViewport:"=>"Amazon KSFUWI Fire HD 10 (2017) Amazon KFMAWI Fire HD 10 (2019) Samsung SM-T580 Galaxy Tab A 10.1 Samsung SM-T510 Galaxy Tab A 10.1 (2019) Samsung SM-T560NU Galaxy Tab E", "percentTraffic"=>"0.28%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-tablet-2", "width"=>800, "height"=>1280}, {"list"=>"VA Top Tablet Viewports", "rank"=>3, "devicesWithViewport:"=>"Amazon KFGIWI Kindle Fire HD 8 2016 Amazon KFDOWI Kindle Fire HD 8 (2017) Amazon KFKAWI Fire HD 8 (2018) Amazon KFKAWI Fire HD 8 (2018)", "percentTraffic"=>"0.27%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-tablet-3", "width"=>601, "height"=>962}, {"list"=>"VA Top Tablet Viewports", "rank"=>4, "devicesWithViewport"=>"iPad 7th gen", "percentTraffic"=>"0.24%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-tablet-4", "width"=>810, "height"=>1080}, {"list"=>"VA Top Tablet Viewports", "rank"=>5, "devicesWithViewport:"=>"This viewport is missing from the devices lookup table. Please contact the Testing Tools Team to have it added.", "percentTraffic"=>"0.19%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-tablet-5", "width"=>534, "height"=>854}], "vaTopDesktopViewports"=>[{"list"=>"VA Top Desktop Viewports", "rank"=>1, "devicesWithViewport"=>"This property is not set for desktops.", "percentTraffic"=>"12.79%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-desktop-1", "width"=>1920, "height"=>1080}, {"list"=>"VA Top Desktop Viewports", "rank"=>2, "devicesWithViewport"=>"This property is not set for desktops.", "percentTraffic"=>"4.76%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-desktop-2", "width"=>1366, "height"=>768}, {"list"=>"VA Top Desktop Viewports", "rank"=>3, "devicesWithViewport"=>"This property is not set for desktops.", "percentTraffic"=>"3.87%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-desktop-3", "width"=>1536, "height"=>864}, {"list"=>"VA Top Desktop Viewports", "rank"=>4, "devicesWithViewport"=>"This property is not set for desktops.", "percentTraffic"=>"3.54%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-desktop-4", "width"=>1440, "height"=>900}, {"list"=>"VA Top Desktop Viewports", "rank"=>5, "devicesWithViewport"=>"This property is not set for desktops.", "percentTraffic"=>"2.74%", "percentTrafficPeriod"=>"From: 05/01/2022 To: 05/31/2022", "viewportPreset"=>"va-top-desktop-5", "width"=>1280, "height"=>720}]}`

This needs to be implemented in the `rspec` tests to Cypress Viewport Updaters tests.

**Comment by holdenhinkle** [comment]
This is complete. The PR has been submitted.

**Comment by holdenhinkle** [comment]
This is merged.

**Comment by pjhill** [comment]
But, who will update the updater of the updates? Thanks for sticking to the unit tests in `vets-api` -- sorry I couldn't help you any with that. Good work!
