### ISSUE TITLE
Create standardized messaging for scheduled system maintenance

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4631]
Upcoming scheduled API maintenance on 1/11, Saturday. Related to this platform ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4422

We need the following: 
**Sitewide (on new VA.gov) banner message**
- before and during downtime (Peggy to recommend whether this should be the same or 2 different messages)

**Application page message (REACT pages on public website)**
- in-body alert message with button disabled: before and during downtime (ditto ^)

**Sign in modal message**
- before and during downtime (ditto ^)

The advance message on the public website should display on the day of the downtime.

**Comment by peggygannon** [comment]
@jenniferlee-dsva Downtime banner notifications for your review: 


[For Dev implementation] Please note: Month and times should be formatted as:  
- Months: Jan. , Feb. March, April, May, June, July, Aug. Sept., Oct.,, Nov., Dec.
- Times:  should be written using a.m. and p.m. with periods. For example, 9:00 a.m. 10:00 p.m.
Spell out noon and midnight. Don’t use 12:00 p.m. or 12:00 a.m.

----
Sitewide (on new VA.gov) banner message

Before downtime
**VA.gov will be down for maintenance soon**
We’ll be doing some work on VA.gov on [Date] between [Time] and [Time]. You may have trouble using the site during that time. If you have trouble, please check back after [Downtime end date/time].

During downtime
**VA.gov is down for maintenance right now**
We’re sorry. VA.gov isn’t ready for you right now. We’re doing some work to help make the site even better for Veterans, service members, and family members like you. We hope to finish our work by [Date/Time]. Please check back after then.

------

Application downtime alert message

Before downtime
**[Application/FormName] will be down for maintenance soon**
We’ll be doing some work on [Application/Form] on [Date] between [Time] and [Time]. You may have trouble using this tool or submitting your work during that time. If you have trouble, please check back after [Downtime end date/time].

During downtime
**[Application/Form Name] is down for maintenance**
We’re making some updates to [Application/Form] to help make it even better for Veterans, service members, and family members like you. We hope to finish our work by [Date/Time]. Please check back after then. 

If we're not able to provide a timeframe:
**[Application/Form Name] is down for maintenance**
We’re making some updates to [Application/Form] to help make it even better for Veterans, service members, and family members like you. We’re sorry it’s not working right now. Please check back soon.

------

Sign-in modal message
Before downtime

**VA.gov will be down for maintenance soon**
We’ll be doing some work on VA.gov on [Date] between [Time] and [Time]. You may have trouble signing in or using some tools or services during that time. If you have trouble, please check back after [Downtime end date/time].


During downtime
**You may have trouble signing in or using some tools or services**
VA.gov is down for maintenance right now. We hope to finish our work by [Date/Time]. If you have trouble signing in or using any tools or services, please check back after then.

**Comment by jenniferlee-dsva** [comment]
Per convo with Peggy, after Kelson consult re display form factor. The sitewide messages will use the promo announcement banner with this logic:

1/ In advance of maintenance on the day of (12:01 am Saturday for example)

2/ One hour from maintenance window - sign in/create account to save wip, maintenance starts in X mins.

3/ During downtime - tools and sign in unavailable

When maintenance window ends, banner goes away.

**Comment by jenniferlee-dsva** [comment]
^ @peggygannon RE the 2nd sitewide (X minutes) - could we make the messaging more specific and mention applications that may have started? That's the real concern we want to make folks aware of: if they're in the middle of an app in the unauth state, they need to sign in/create account. 

**Like this - in brackets - def needs massaging:** 
If you’re currently ?? [in the middle of filling out an application ??], sign in or create an account [now] to save your work.

@kelsonic  FYSA - ^ still in flight.

**Comment by jenniferlee-dsva** [comment]
@rianfowler and @lkoenigsberg - please see ^ for Peggy's message texts for your teams:

1/ **Application downtime alert message** [the text that appears in the REACT widget on unauth application pages]
2/ **Sign in modal** [that appears as an in-body alert on the modal]

**Comment by peggygannon** [comment]
@kelsonic @jenniferlee-dsva UPDATED Message 2 (X time from maintenance window)

**We’ll be starting site maintenance in [X minutes].** If you’re in the middle of filling out an application or using our tools, please sign in or create an account to save your work.

**Comment by jenniferlee-dsva** [comment]
@AZSchneider @mattpointzxer0 - per slack ^

**Comment by kelsonic** [comment]
PR is merged and this is now on staging.va.gov! https://github.com/department-of-veterans-affairs/vets-website/pull/11447

**Comment by ncksllvn** [comment]
I think we

**Comment by jenniferlee-dsva** [comment]
@peggygannon - Could we be sure to capture the final sitewide messaging and sign in messaging texts that were used? 

Would also like to tweak sitewide messaging text re that ending 12:01 am time (and @ncksllvn / @kelsonic  - going forward, any way we can change the time zone reference to omit "standard/daylight saving" S/D in EST/EDT? Our site references just ET/PT, no reference to daylight saving or standard, in static content.)

**Comment by peggygannon** [comment]
@jenniferlee-dsva @kelsonic @ncksllvn Here's are the notifications used for this past weekend's downtime: 

I will open another issue to capture the second part of this work: standardizing these downtime notifications. 

Advanced banner messaging: 
**We'll be doing site maintenance on [Date] between [Time] and [Time].** You won’t be able to sign in or use some tools during this time. 

Countdown message: 
**Scheduled maintenance starts in [X minutes].** If you’re filling out a form, sign in or create an account to save your work.

During downtime: 
**We're working on VA.gov.** If you have trouble using online tools, check back after ${expiresAt.format('MMM Do [at] h:mm a z')}.

Sign in messaging
**You may have trouble signing in or using some tools or services**
We’re doing some work on VA.gov right now. We hope to finish our work by [Date and Time]. If you have trouble signing in or using any tool or services, check back after then. 

App messaging
**This form is down for maintenance**
We’re making some updates to this form. We’re sorry it’s not working right now and we hope to be finished by [Date and Time]. Please check back soon.
