### ISSUE TITLE
AWS Prod Access Extension

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#46317]
### What is the issue

90 day prod SSM access was approved in https://github.com/department-of-veterans-affairs/va.gov-team/issues/41701 by @td-usds and it expires today. The user requested an extension until the end of September and we (Infrastructure team) are requesting approval on Patrick's behalf. 

### Who is it effecting or who will be effected

@PJart will lose production SSM access for AWS

### What have you done to resolve this so far

Confirmed with @PJart for future access, tagged @td-usds in  https://github.com/department-of-veterans-affairs/va.gov-team/issues/41701#issuecomment-1230495900, set new reminder, submitted this ticket.

### Dependencies

@department-of-veterans-affairs/operations-aws-approvers 

### What's at risk

Loss of access for Patrick (we will remove requested access if an AWS approver doesn't respond by EOD)

### Recommendation(s)

PO evaluate AWS access on https://github.com/department-of-veterans-affairs/va.gov-team/issues/41701

### Additional Information

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/41701

**Comment by little-oddball** [comment]
@td-usds This is a time sensitive request, could you please review and address as you see fit?

**Comment by td-usds** [comment]
Extension until 2022-09-30 approved

**Comment by rmtolmach** [comment]
Thanks for the quick look!
