### ISSUE TITLE
Latest version of aws-sdk-s3 returns NoSuchKey error which is not properly handled

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4633]
## What happened?
After ~[upgrading `aws-sdk-s3`](
 https://github.com/department-of-veterans-affairs/vets-api/pull/3744) gem from 1.9 to 1.60~, the daily deploy on 1/7/20 we encountered multiple `NoSuchKey` errors in `vets-api`, seen in Sentry here:

http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/91805/
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/91812/
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/91811/

We rolled back the `aws-sdk-s3` gem upgrade that went out in that release (assuming that it was the most likely culprit, but the cause was actually https://github.com/department-of-veterans-affairs/vets-api/pull/3721

## Desired Behavior

When a `NoSuchKey` error is encountered in an `S3` action, the `vets-api` should gracefully handle/rescue the error and return a curated response to the frontend.

## Acceptance Criteria
- [ ] `vets-api` uses latest v1 version of `aws-sdk-s3` gem
- [ ] Specs exist which illustrate the `NoSuchKey` error triggering 
- [ ] When `NoSuchKey` error is encountered Sentry should not be alerted and error is being properly handled

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by annaswims** [comment]
impact: between 3pm and 8:30 today file uploads did not save
