### ISSUE TITLE
[Story] Add N/A for all institution cards that don't display an ownership name. 

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#46348]
## Issue Description
_ EDU would like for the institution Ownership to be displayed on all cards. If institution cards does not have an Ownership name, please add "N/A" after ALL Intuitions ownership.   SAMPLE -**Institution Ownership: N/A**_

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/719da9ee-59dc-4e24-8519-9ffe74ff0b59)

---
## Tasks
- [ ] _All cards should display "Institution Ownership" with or without name._

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by dsrr47** [comment]
Test case for having an owner is here: https://staging.va.gov/education/gi-bill-comparison-tool/institution/21915164

**Comment by hallihocine** [comment]
Ticket has been validated in staging: Institutional Ownership displays N/A for institutions without an Ownership Name. See screenshot: 
<img width="622" alt="Screen Shot 2022-08-30 at 1 19 02 PM" src="https://user-images.githubusercontent.com/86266024/187504212-bb7e2eec-d248-4bdb-ae83-7982e109bccf.png">

**Comment by hallihocine** [comment]
- Test run in TestRail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3531&group_by=cases:section_id&group_order=asc&group_id=5861
- Test steps: 
[Add NA for all institution cards that don't display an ownership name.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9455295/Add.NA.for.all.institution.cards.that.don.t.display.an.ownership.name.xlsx)

**Comment by MitchLivingstone** [comment]
Update 09/15/2022: UAT Approved Please remove all flags move to Prod. 
Completed.

**Comment by MitchLivingstone** [comment]
Closed and completed.
