### ISSUE TITLE
Create Missing Swaggerdoc for `upload_supporting_evidences` & `supporting_documentation_attachements `

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#4634]
## The Problem
We have missing swagger documentation for the following two endpoints:
- `/v0/upload_supporting_evidence`
- `/v0/vic/supporting_documentation_attachments`

## Additional Context
This was discovered while adding `nil` input validation to an endpoint that shares the `FormAttachmentCreate` mixin.
- [PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/3721)
- [issue here](https://github.com/department-of-veterans-affairs/vets-api/pull/3721)

## Work to be Done
- [ ] Create swagger doc for aforementioned endpoints

**Comment by holdenhinkle** [comment]
`/v0/upload_supporting_evidence` - done, added to Swagger
/v0/vic/supporting_documentation_attachments - needs to be added to Swagger
