### ISSUE TITLE
Define "accessibility support person"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46353]
## User Story
As a VFS team member, I want to understand what is meant by "accessibility support person" with regards to Platform guidance/documentation so that I am able to take appropriate actions when/where specified.

Assignee:
Peer Reviewer:

## Description
In ticket #45754, Governance team added instructions to the Staging Review guidance to ask VFS teams to invite their "accessibility support person", if applicable. This is not the first time that Platform has emphasized the importance of including their accessibility support individuals, however the issue persists. We have made the assumption that VFS teams may not understand what is meant by "accessibility support" and think it would be best to include a definition of what this means.

For example, in the past, VFS teams have invited former accessibility specialist Trevor Pierce and/or Noah Gelman, not realizing that those individuals are _Platform's accessibility support persons_ not _VFS accessibility support persons._

## Tasks
- [ ] _Placeholder task_

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@jimuhh this came up in refinement today. Could you please review the US and Description and let me know if this is something that can be referenced in the controlled vocabulary list? I'm not sure if it needs its own ticket, but I just wanted to get it documented so we can take action.

**Comment by jimuhh** [comment]
Hi @shiragoodman The [controlled vocabulary list is here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/2251260066). As you can see, it starts with the concept we're looking to define and moves on to the approved and deprecated terms. So the question is, how would we define this individual's role in plain language regardless of the title we assign them?

**Comment by shiragoodman** [comment]
that's something @briandeconinck can likely help with

**Comment by briandeconinck** [comment]
I'm going to bring it up in today's accessibility-people-sync and ask all of the accessibility support people to define themselves! Will report back after that!

**Comment by jimuhh** [comment]
Thanks @briandeconinck. Go straight to the source!

**Comment by shiragoodman** [comment]
This ticket was discussed at Governance team refinement in January 2024 and was determined to be no longer relevant to the team.

**Comment by jimuhh** [comment]
Hi Shira!
Nice to see you in my inbox! I'm back working at VA but miss the old team. But in the interim, I worked as a content strategist on an Ad Hoc project that produced a rather kick-ass website for the state of Louisiana<https://www.ldaf.la.gov/>.
LMK how you're doing!

Best,
Jim Ryan

From: Shira Goodman ***@***.***>
Sent: Tuesday, February 6, 2024 9:28 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Ryan, James P. (liberty It Solutions, Llc) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Define "accessibility support person" (Issue #46353)


This ticket was discussed at Governance team refinement in January 2024 and was determined to be no longer relevant to the team.

-
