### ISSUE TITLE
[09/05/22] Update Covid vaccine SharePoint resources

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#46356]
With the upcoming COVID vaccines for the year, the VEText team needs to update information available to users.

**Comment by lindsay-insco** [comment]
New COVID booster is bivalent - Moderna and Pfizer

**Comment by ahicksfearless** [comment]
I used this as a resource: https://www.cdc.gov/media/releases/2022/s0901-covid-19-booster.html
