### ISSUE TITLE
Make Case for Removing the VA Sign-in Button

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46352]
## Tasks
- Get analytics to support the case
- Make case for removing the sign-in button to the Platform Design System in their office hours

**Comment by acrollet** [comment]
Recording a conversation with @humancompanion-usds @batemapf @stephenBarrs @brianseek @k80bowman @caw310 just now:

@humancompanion-usds gave us the DS team's blessing to design, test, build and deploy a minimal header/footer, and they'd be interested in us contributing that work back to the design system. They could perhaps be called AppHeader/Footer, to distinguish from the more full-featured versions needed for content pages.

**Comment by loripusey** [comment]
Thanks @acrollet for the info. I'll add some design tickets to this Epic for future sprints to begin the design & discovery process for a pared-down header and footer.
cc: @ytsaoca @kristenmcconnell @zach-park @kellysmith1008 @benbrasso-agile6

**Comment by loripusey** [comment]
Closing this as it looks like we have the buy-in from the DS that we were looking for.
