### ISSUE TITLE
Do we need the /vaos/facilities service?

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#4636]
The FE is only currently using the name, city, and state info from the /vaos/facilities endpoint. We could get this from the regular facilities api, instead of using one that maps back to VAMF.

The only real unique info in that service is parentStationCode, but we probably don't need to use that.

Worth considering removing this service once we're comfortable with how the facilities data is being used.

**Comment by lenaecb** [comment]
@jbalboni - do we need to address this debt before phase 1 rollout?

**Comment by jbalboni** [comment]
This should actually be closed, based on the parent code changes. It's no longer something we can do.
