### ISSUE TITLE
Verify that footer help content is correct for Supplemental Claims from Benefits Team 1

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#46384]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*
We need to validate that this is the correct help content for the Supplemental Claims experience. It appears above the footer on all pages.

TEXT:
Need Help?
If you have questions or need help filling out this form, please call our MYVA411 main information line at 800-698-2411 and select 0. We’re here 24 hours a day, 7 days a week.
If you have hearing loss, call TTY: 711.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
October/November. We are aiming for as soon as possible due to the PACT Act.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*
- Link to product outline:
- Link to or attach user flows:
- [Link to prototype or mockups:](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=contain&page-id=10%3A1697&starting-point-node-id=70%3A5676)
- Link to any epics/issues that may be helpful: [Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45835) [Supplemental Claims content epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44414)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale @saderagsdale 
-	Designer: Pamela Hastings @thehastingsp 
-	FE engineer: Robin Garrison @Mottie 
-	Product/team Slack channel: benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by thehastingsp** [comment]
@RLHecht checking in on this ticket as we are heading into usability research.

**Comment by RLHecht** [comment]
thanks for checking in @thehastingsp When is usability research planned for? If we get it to you by Friday 9/9 does that work?

**Comment by megzehn** [comment]
Hi @thehastingsp! Here's updated copy for the footer. Let us know if you have any questions. Thanks! CC: @RLHecht, @katherine-fung 

--------

**Need help?**
If you need help with this form, call us at 800-698-2411 (TTY: 711). Then select 0. We’re here 24/7.

**Comment by thehastingsp** [comment]
Thank you @megzehn
