### ISSUE TITLE
[Sidekiq UI] Application onboarding infrastructure request

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#46387]
## Summary
The purpose of this template is to capture requirements for onboarding a software application to the Platform's delivery infrastructure. 

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

### Guidance
- Please fill out the sections below with as much info as possible 
- If you don't have info or know the answer to a given prompt, _it's okay to leave it blank_
- The Infrastructure Team will assist you with gathering requirements _and_ performing key setup and configuration tasks 

---

## Description of application
_Backend tool for monitoring sidekiq jobs in production_

### Basic info:
**Team Name:**   Integration Experience
**Application Name:**  Sidekiq UI
**Functionality:**  Backend Tools
**Language/Stack:**  Ruby/Sinatra
**Ports/Networking needed:**  
_ie "80, 443" for standard HTTP and HTTPS_    
Port 3002 for standard plain HTTP
_ie "Database, Redis, S3, etc"_  
None

### Background/Context/Resources
[Initiative Release Plan](https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/40061)

---

### Application repository and container 
- [x] **GitHub repo:** [vets-api-sidekiq-ui](https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui)
- [x] **Dockerfile:** [Dockerfile](https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui/blob/main/app/Dockerfile)

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions**
- [x] **AWS Elastic Container Registry (ECR) repository for the app container:** [ECR](008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/vets-api-sidekiq-ui:1.0.18)

- [x] **Automation to release and tag the app's GitHub repo with a semantic version number** 
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to push the app's container to ECR with a semantic version number** 
- [x] **Kubernetes manifest using Helm charts** in `vsp-infra-application-manifests` 
_Requesting team; Infrastructure Team can assist_  
- [x] **Kubernetes detect and update application** in `vsp-infra-applications-manifests`
- [x] **Automation to update the Kubernetes manifest** 

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** 
- [x] **AWS SSM Parameter Store parameters that the app needs to run,** 

---

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by ewilson-adhoc** [comment]
Note: I think IET is at the point where we were able to self-service most of this deploy, aside from some bits with the network configuration (which aren't captured in this checklist). I haven't merged the manifests yet -- just opening this ticket as a general FYI to track this deploy.

**Comment by jhouse-solvd** [comment]
mentioned this to @ph-One and he will follow up w/ @ewilson-adhoc

**Comment by ewilson-adhoc** [comment]
Followed up with @ph-One all set with this
