### ISSUE TITLE
IE11 won't close the new user modal window if it opens over the login modal window

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#4638]
## User Story or Problem Statement
As an IE11 user, I need to be able to dismiss the `Welcome to the new VA.gov` window so I can log in to access logged in content. See attached screenshot below.

## Goal
IE11 users need to be able to dismiss the welcome modal so they can log in to tools and resources. This is a unique case, because it has some specific steps to re-create:

1. Clear all cookies and history. We need an empty cache to recreate the issue.
1. Copy and paste a logged in URL like scheduling, claims and appeals, profile into a new browser window.
1. Wait for the welcome modal to open on top of the login modal.
1. Verify you cannot click or keypress close the welcome modal. The yellow focus halo should be toggling back and forth between the two modal windows.

## Acceptance Criteria
- [ ] IE11 users can close the welcome modal and log in successfully

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
![Screen Shot 2020-01-07 at 3 36 46 PM](https://user-images.githubusercontent.com/934879/71934007-114ff000-3169-11ea-9bd2-f8b5f40750f4.png)

**Comment by alexpappasoddball** [comment]
@brandonrapp this is something your team handles correct?

**Comment by FranECross** [comment]
Closing due to age and inactivity. More than likely obsolete. Can reopen if needed in the future, or a new ticket created.
