### ISSUE TITLE
SOCKS access for Dave Pickett

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-team#46393]
### Your Name

David Pickett

### Your Email

dave.pickett@civicactions.com

### Your Role and Team

Content Designer

### Product Manager (PM) name and email

David Shannon david.shannon@agile6.com

### Product Owner (PO) name and email

Dave Conlon David.Conlon@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6rtjr85GBvBehEh5eGx4dl+RYGaw/YO5osm+N4e9gtL0Obcd5zTA/rSY2aH+4rOusLeTR2urSHZ72vFBEW9Ue6sqvK5NBAGWUM8j1M1b+994WG1xgXhJrr29zOm4qfGAjVWqHD1vYFYCeZ+zxDUGdS9cnSnsSNJS8nWzUGPOIYcL4K2lggPUFb9PLytCRj+kJ8BOIxXPEAUq7KmLFHRXLodDfmXOPPjAAYbzyLA4tQFM/gFYMcgo/Z8j3F3yJw3iQ7HPd00mlk1D23/lRBpyn8dMo/8kzvbgKCuANDoviEG7eC5VbF+gFEpEW15ANFracUoDBJArfyRa7WIgZ0hgxTba/r85Qw/DgS/SZoReTFWZZaAS4qEVHAmFnpgmPvmAsmyBGBVhZzuvC2O6On4e+4LdJnExGtwwTPuhbBV+7j2+feWm9CruQPvZhH6olf1yfwYC3tgurZ5r2+ub2ZPgchMwNO43tidkGrQ0feMNWIp/HZG9IjhPVgPNAZvwANXM= davepickett@Daves-Razer

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by davidmpickett** [comment]
Fixed typo

**Comment by davidmpickett** [comment]
Note that this is for my second machine. Previously got SOCKs set up for my main machine in https://github.com/department-of-veterans-affairs/va.gov-team/issues/43331

**Comment by jsgarmon** [comment]
@davidmpickett : are you hoping to have 2 active keys? Or are you replacing your old key with your new one?

**Comment by davidmpickett** [comment]
@jsgarmon I'd be fine using the same key on both computers if that's possible, but not sure how I would do that.

**Comment by jsgarmon** [comment]
@davidmpickett : you'd just have to transfer the private key. The SOCKS setup creates a file called `id_rsa_vagov` (in `~/.ssh/` on linux and MacOS, not sure where in Windows). Once moved, you can run `vtk socks setup` again and choose to not create a new SSH key.

**Comment by jsgarmon** [comment]
I've kept both your old and new key, so either should work.
