### ISSUE TITLE
Combine Kraken and Griffin rotations in pagerduty

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#464]
Combine Griffin and Kraken prometheus alerting rules and Pagerduty rotations starting on 7/15 at 11 am EST.

* combine Kraken and griffin schedules in pagerduty and name the group "VSP Engineers" (ensure that whoever is in the rotation in the next 2-3 weeks was previously scheduled or aware of the changes)

* update the [prometheus alert manager](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/alertmanager.yml.j2) to reflect the new combined group

**Comment by annaswims** [comment]
If the work can't be done by then we could just adjust the schedule to have the same person on call for both teams.

**Comment by wyattwalter** [comment]
Are you taking this on @kfrz? Note that most of this is managed by Terraform (don't go clicking through the interface to manually set these up). https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/dsva-pagerduty

We don't manage membership to schedules through Terraform since it can change regularly, so that part has to be done in the UI.

**Comment by kfrz** [comment]
The following engineers are tagged for awareness. 

:warning: The on-call schedule will change as of **July 15 11am EST** :warning: 

---
On-call schedules to be retired:

[`Krakens`](https://dsva.pagerduty.com/schedules#P9QYY1Z): 
@SMLuthi @lihanli @jholton @kfrz 

[`Griffins`](https://dsva.pagerduty.com/schedules#PHBY3O3)
@annaswims @saneshark @U-DON 

--- 
New on-call schedule:

`VSP Engineers`: 
@annaswims @kreek @jholton @U-DON @rianfowler @cvalarida @omgitsbillryan @kfrz 

---
Are there any other VFS engineers coming over to VSP? Anyone I missed?

**Comment by rianfowler** [comment]
@accbjt might have been missed.

**Comment by kfrz** [comment]
Proposed new schedule here: https://dsva.pagerduty.com/schedules#PRPU9R4

**Comment by annaswims** [comment]
In the leads meeting we settled on 1 week per person rotations. if people prefer the split-day rotation they can still find a partner to split rotations with.  Also, @omgitsbillryan will stay in the devops rotation and not be in the VSP Engineers rotation

**Comment by kfrz** [comment]
Ok will update accordingly thanks Anna

**Comment by wyattwalter** [comment]
I think this is done now 👍
