### ISSUE TITLE
Application to Promote: [vets-api-sidekiq-ui]

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#46406]
### Acknowledge Instructions

- [X] I acknowledge that I have read the above instructions and understand the application name provided will be used to create various resources

### Application Name

vets-api-sidekiq-ui

### Environment

staging

### Maintainer(s)

ewilson-adhoc,ericboehs

**Comment by jbritt1** [comment]
Automated pull request reviewed/approved/merged by codeowners.
