### ISSUE TITLE
iphone xr front end issue - confirmation page scrolls up and down on initial load 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#46415]
## Description 

When using day of check in on iphone xr, safari 

Get to your appt screen with an appt that can be checked in

Select "Check In" and touch the screen/scroll around

When the next page loads (i.e., confirmation), it'll flip out like it's scrolling to the top and bottom of the page before loading.

## Tasks

- [x] Try to replicate 
- [ ] Documents issues for how to resolve or proceed with fix

**Comment by acrollet** [comment]
I just tried to reproduce this with an iPhone Xr and a 13 pro, no luck. @benbrasso-agile6 what I tried was tapping the "Check In" button and immediately scrolling around on the page while it was loading the next page. Is that what you did? Do you still encounter the bug?
