### ISSUE TITLE
Content review for Facility Locator Alert and Labels: MVP

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4643]
# User story
As a member of the Facility Locator team, I need to my content reviewed before Urgent care MVP launch to ensure it's accurate, aligns with VA style, and is error-free.

# Goals

## Urgent Care PDF Alert
**We need to make eligibility information available to veterans seeking urgent care at community facilities in a clear and concise way.**
- Benefit information is available in a PDF provided by the Office of Community Care (attached). 
- The PDF must be available (via print or mobile) at the time of the Veteran's urgent care visit. 
- An alert/call to action will be displayed when the relevant facility type has been selected during the search. 

Call to action alert will display below search box. 

![pdf alert](https://user-images.githubusercontent.com/55411834/71930484-9b3f8f00-3150-11ea-8f72-d48d4428842a.png)

PDF (as of 1/6/2020):
https://app.zenhub.com/files/133843125/29c78cf4-1b29-4b39-8a76-1eefa5356f82/download

## Labels

**We need to use labels that differentiate facility sub-types and are meaningful to Veterans.
- Urgent care facilities exist within VAMCs. Veterans can also access care at community based urgent care locations. 
- Routine prescriptions are filled at VA Health locations. Urgent care prescriptions can be filled at community retail locations. 
- Currently, we are using "VA urgent care",  "In-VA network providers" and "In-VA network urgent care pharmacies".
- The OCC requested we drop "urgent care" from the pharmacy label.
- Labels should be consistent with PDF content to avoid confusion. 

![pharmacy label](https://user-images.githubusercontent.com/55411834/71935753-79e4a000-315c-11ea-9121-9533b16f2f59.png)

![urgent care labels](https://user-images.githubusercontent.com/55411834/71935639-270ae880-315c-11ea-9ade-d312c0e7ebaa.png)

**Launch date for MVP: 2/1/2020**
 _However, if possible, we would like to test the changes (and content) with Veterans prior to launch._

**Comment by arickalewis1** [comment]
For context, here are the wires for cards including the labels. 
[Facility Locator Card Types (2).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4036588/Facility.Locator.Card.Types.2.pdf)

**Comment by peggygannon** [comment]
@arickalewis1 @mmiddaugh 
Hello, below are my recommendations for this alert and labeling. I tweaked the alert heading, as "in-VA network provider" is vague and forces the Veteran to figure out what is in-network. 

I also put in a button and a link as two access points to get the document, labeling the button as the "print option" and the link as the "download option". The download link is an already-established pattern on our site. 

---

**To get urgent care with a VA or Community Care provider, you'll need this document**
Please bring a copy of the VA Urgent Care Benefit to your appointment. If you don’t have this document you won’t be able to get care. 
You can print out a copy or download it to your mobile device to bring to your appointment.   

{button} Print VA Urgent Care Benefit
{link}[Download VA Urgent Care Benefit](link to PDF)

------

Label recommendations

VA health >>> VA health care facility
Non-VA health >>>> Community Care facility
Urgent care>>> I recommend nesting 2 labels under this: 
-- VA urgent care facility
-- Community Care urgent care facility

In-network urgent care pharmacies. 
Does this refer to CC pharmacies? If so, here is my recommendation to make this more clear to Veterans.>>>Community Care pharmacy (must be in the VA network)
 
And using "VA pharmacy" for a VA pharmacy.

**Comment by arickalewis1** [comment]
Thanks! @peggygannon

**Comment by peggygannon** [comment]
@arickalewis1 @mmiddaugh Hello! i have been able to attend a few FL user sessions and noticed that the PDF alert language doesn't reflect the recommendation above. Do you need me to provide other language or does the language alert above not meet the AC you need?

**Comment by arickalewis1** [comment]
@peggygannon Hi! We were testing language recommended from the OCC but plan to use our findings combined with your recommendations in the next iteration of the design. Thanks for asking!
