### ISSUE TITLE
Support Resources Are Easier to Use

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46434]
## Product Outline
[Contact Center Support](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1791983795/Contact+Center+Tier+II+III+Support+Product+Outline)

## High Level User Story/ies
_As a user on VA.gov, want support resources for tasks I am trying to complete while on VA.gov to be accessible and easy to use._

## Hypothesis or Bet
**If** _we make support resources on VA.gov easier to use_ **then** _Veterans and other VA.gov users will be able to self-service solutions for issues they encounter while trying to complete tasks_.
**If** _we make knowledge management articles easier to use_ **then** _VEO tier 1 support agents will be able to get Veterans the help they need more often_.

## OKR
_N/A_

## Definition of done
* Resources and Support Articles specifically related to sign-in/identity are comprehensive of existing known and expected issues, and are easily accessible and usable for users of VA.gov.
* Knowledge management articles which VEO contact center tier 1 agents use are comprehensive and easily understood.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by starlow00** [comment]
Stage 1 of KM audit project done as planned for Sprint 9 -- an organization plan for Login issue KMs
Sprint 10 will involve auditing individual KMs... 1-2 per sprint

**Comment by starlow00** [comment]
Sprint goal for KMs reviewed is on track going into Sprint 11.
