### ISSUE TITLE
Draft Phased Rollout for the Product Success Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4647]
## User Story or Problem Statement
How might we publish our roadmap for rolling out the Product Success Tool so that we can understand the work involved and dependencies for the different phases by which the tool can be released and tested with real VFS teams?

## Goal
Draft a phased rollout for the Product Success Tool assuming we are able to obtain access to Domo and BigQuery.

## Acceptance Criteria
- [ ] Draft a phased rollout 
- [ ] Share results with team

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[Rollout Draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/product-success-rollout.md).

@amycesal @nedierecel Please review

**Comment by nedierecel** [comment]
Thanks @joanneesteban @amycesal Additional questions and/or responses from your draft:

1. Recruitment - For stakeholders, who would be removed and/or added from the original team that reviewed the Google Sheets MVP? 
2. Access - FYI Only: Once we know the answer to #1, I created a group within Domo's Admin Settings to see if this provides us with an easier option for managing users:

![image](https://user-images.githubusercontent.com/24525739/72842724-f69c7180-3c66-11ea-97c3-a4e6e98cb211.png)

3. Activity Tracking - We can use the Admin Settings>Activity Log to monitor usage.

**Comment by joanneesteban** [comment]
Thanks for reviewing and the access/activity tracking info, @nedierecel! For the recruitment question, can are you referring to the stakeholders who are using the tool? Or the Insights team members who worked on it?

**Comment by nedierecel** [comment]
Ah, for recruitment - my question is who we would add or remove from the original Education Product Owners/team members that reviewed the initial MVP.

**Comment by joanneesteban** [comment]
Gotcha, so: 

**Keeping:**
- the Product manager for the digital education portfolio [interview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/research/product-health-prototype/version-1/interviews/Participant%202.md)
- the former design lead for the digital education portfolio (our current Platform lead)

**Adding:**
- the new PM/POs for the Education application (BAH)

For any additional testers, deferring to @amycesal for anyone else it might be helpful to test this initial version with (even if it's internal/our Platform design lead, etc.)
