### ISSUE TITLE
Investigate use of feature flagging for SSO rollout

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#4648]
VSP added a feature flag system that allows selective enablement of features without a full deploy cycle, and possibly allows selective roll-out of features.

We might want to use this to reduce risk of rolling out SSOe-integrated login. I don't currently have much knowledge of how to take advantage of it.

The fact that we have separate v0 and v1 sessions controllers should help, we can hopefully implement the feature flag mostly on the front end and just implement different versions of the session initiation process.

The #vfs-platform-support channel in DSVA slack is a good starting point to asking for more info.

*Acceptance Criteria:*
Technical recommendation for how to use the feature flagging mechanism to roll out SSOe integration, or a recommendation that it's not a good fit if that's the case. Any new tickets that are needed to adjust our implementation to take advantage of it.

**Comment by patrickvinograd** [comment]
Anna Carey (backend) and Rian Fowler (frontend) were identified as good engineering points of contact for the feature flag mechanism.

**Comment by patrickvinograd** [comment]
Add more details about where we'd insert feature flagging on both frontend and backend to effect selective roll-out of SSOe-based login.

**Comment by ericbuckley** [comment]
the "feature flipper" interface looks like it will give us some good options here, as we can selectivly enable our SSOe integration with just a handlful of users at first, then slowly roll it out to a percentage of our users before relasing it to everyone. 

For example, here is the config page for an existing feature flag

![Screenshot_2020-01-16 facility_locator_show_community_cares Features Flipper](https://user-images.githubusercontent.com/170002/72569938-6d54fb80-3870-11ea-9990-140a6034791e.png)

**Comment by patrickvinograd** [comment]
One gap I see is that it's based on percentage of *logged in* users - which makes sense, because I'm guessing they associate the toggle state with a user identity to avoid a feature toggling randomly on page reload. 

But we are proposing to toggle the login feature itself which presumably needs to apply to users before they log in.

**Comment by ericbuckley** [comment]
Oh thats a great point, I didn't think about that.  I wonder if there was any thought around enabling feature flags for IP addresses/ranges?  If that was supported do you think that would help us out?

**Comment by patrickvinograd** [comment]
Something along those lines - any stable identifier that would persist across at least page refreshes, and preferably browser sessions, could be hashed and then used to pick out a percentage of users.

**Comment by ericbuckley** [comment]
similar thoughts have come up before, https://github.com/jnunemaker/flipper/issues/128.  Looks like the actor variable doesn't have to be a user at all, it just needs to be an object that supports the `flipper_id` attribute.

If I'm reading this correctly we could
  - create an `IPSession` class that has its `flipper_id` attribute evaluate to the users IP address
  - implement our SSO feature flag so it accepts an instance of an `IPSession` rather than @current_user
  - then manage our Actors (renamed Users in the `/flipper/features/` UI) as IP addresses rather than email addresses.

It does feel hacky though...

**Comment by ericbuckley** [comment]
I think the question that we need to answer first is exactly how do we want to roll out this feature?  Would it really just be a percenage of users coming in, or do we want to "target"  a set of users based on some value like location?

**Comment by ambikaroos** [comment]
Likely will want phased roll out to percentage of users rather than specific population (especially since difficult to target a specific population who is unauthenticated)

**Comment by ericbuckley** [comment]
Here is a proposal for implementation.

1. implement an `IPSession` class that has its flipper_id attribute evaluate to a randomly generated uuid, have an instance of this class initiliazed in middleware and attached to the user's session hash
2. create a new api endpoint that will [toggle a feature flag](https://github.com/jnunemaker/flipper/blob/master/docs/Gates.md#2-individual-actor) on the current `IPSession` (there might be some security implications with this, we may need to limit the feature flags that can be toggled to a whitelist and/or hide the api endpoint with a complex URL path)
3. add a [feature check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/feature-toggles.md#back-end-implementation) in the `v0/sessions_controller.rb` to see if SSOe should be used, if so redirect control to `v1/sessions_controller.rb`

Initially when we roll this out, we will have the flag disabled for all users.  Those that want to test this out, can hit the API endpoint in step 2 to enable the SSOe flag, then continue with the login process.

Once we gain confidence that the SSOe authentication is working, we can enable the flag for a percentage of users (via the admin UI https://api.va.gov/flipper/features), before rolling it out completely.

**Comment by ericbuckley** [comment]
@annaswims / @gunsch I was hoping to get your thoughts on [this proposal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4648#issuecomment-578255363).  From what I understand most of the feature flag use cases within the vets-api are for authenticated users, so to create one for users logging in would require an out of the box implementation.  If either of you have other thoughts as to how this could be accomplished that would be greatly appreciated.

**Comment by gunsch** [comment]
@annaswims out of curiosity, is there a reason flipper is only enabled for auth'd users? I didn't realize we didn't have % rollouts for non-auth'd users at this point.

I'm supportive at a high level of enabling that, though I'll defer to @annaswims for implementation details.

**Comment by annaswims** [comment]
Flipper can be used for unauthenticated users with the "percentage of time" option, which would likely be a good option in this case.  Flipper doesn't add a cookie or anything to the browser though, so the same person may see the feature enabled or disabled.

**Comment by ericbuckley** [comment]
I think the complete rollout may take a few days if not a couple of weeks, so if having a user flip back and forth between the two expereinces (assuming they are logging in on a regular basis), might confuse them.  @patrickvinograd thoughts?

**Comment by ambikaroos** [comment]
Notes from last SU: Investigating a design solution to this, such as an alert above the VA.gov sign in modal letting users know that their session today would be SSOe enabled (written in user-friendly terms).

**Comment by bridgethapner** [comment]
@ericbuckley @patrickvinograd Here is the documentation from Samara I mentioned on 'opt into beta test' - https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Personalization/Beta%20Program

@bshyong :wave: A question for you came up in our stand-up today - We're looking to potentially denote a group of users (~10% of VA.gov users) as participants in an SSO. Patrick mentioned that in the past you're done something similar for a UAT test. Do you think anything you implemented could work for an SSO beta test?

**Comment by gunsch** [comment]
do we set any kind of cooking for unauthenticated user sessions? I think it'd still be reasonable for us to support % rollout for unauth'd users, not just time-based. (@annaswims )

**Comment by annaswims** [comment]
How about something like this https://github.com/department-of-veterans-affairs/vets-api/pull/3868 . 

We could configure by feature toggle type whether we want to use the Google Analytics id or a logged in user's id.

**Comment by ericbuckley** [comment]
@annaswims that would work for us.  Would https://github.com/department-of-veterans-affairs/vets-api/pull/3868 also give us the ability to enable a feature just for a handful of specific actors?

For example, before we roll this out to a percentage of users.  A few of us, could lookup our GA cookie ids in the browser, enable the SSOe feature for actors with matching cookie ids, then test it out?

**Comment by bridgethapner** [comment]
Some UX updates: 

- Per 2/6 meeting with Jen Lee, multiple alerts can't be stacked on top of each other in Drupal, thus feature flagging in sign-in modal is out.
- I am touching base with Jen Lee laster this week to investigate if a dismissible alert pattern she is exploring could be used to announce SSO on VA.gov homepage.

**Comment by annaswims** [comment]
yes, assuming you have the GA id handy you could enable it for individuals.

**Comment by ericbuckley** [comment]
@ambikaroos I think we can close this.  Once https://github.com/department-of-veterans-affairs/vets-api/pull/3868 is merged (its being reviewed now), we'll have all the features we need to implelemnt feature flags on the frontend for unauthenticated users.

**Comment by annaswims** [comment]
@ericbuckley there's one more PR that needs to happen in vets-website to send the GA id to the back end.

**Comment by ericbuckley** [comment]
thanks @annaswims, is there a GH issue we can watch to know when its ready?

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6078

**Comment by ambikaroos** [comment]
Closing - will watch #6078
