### ISSUE TITLE
Replace `active_model_serializers` with `fast_jsonapi`

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#465]
## User Story
As an engineer I need to replace `active_model_serializers` with `fast_jsonapi` so that serialization performance is greatly improved

## Background
[fast_jsonapi repo](https://github.com/Netflix/fast_jsonapi)

`fast_jsonapi` promises to deliver a vastly superior performance compared to `active_model_serializers`
> We want to ensure that with every change on this library, serialization time is at least 25 times faster than Active Model Serializers on up to current benchmark of 1000 records

[blog post on making the conversion](https://mike.polischuk.net/2018/09/moving-from-active-model-serializers-to-fast_jsonapi/)

## Approach
Given how closely the concerns track, this should _not_ be worked on while #466 is actively being worked on.

Given the number of existing serializers, this work should be completed across multiple pull requests.

## Acceptance Criteria
- [x] Add `fast_jsonapi` gem
- [ ] convert existing serializer files to `fast_jsonapi` format
- [ ] remove `active_model_serializers` gem

**Comment by rianfowler** [comment]
# Artifact 
- Deployment of code to production

**Comment by annaswims** [comment]
This may not be worth the effort.  The risk of breaking something is high since the test coverage is low. Also, while the benchmarks for the gems  are much better we don't seem to have a performance problem if we look at view_runtime
