### ISSUE TITLE
Go/no-go on static login page approach with Cerner

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#4650]
Tracking the decision about whether the two-round-trip approach that was proposed for the Cerner authentication process will work with their product. 

@lalexanderson-dsva is working this via email and probably a call. 

If the approach is not feasible we'll need to investigate an alternate approach.

**Comment by ambikaroos** [comment]
Seems that Cerner has the capability to do this, but it is additional scope, so they are ironing that out
