### ISSUE TITLE
[Design] My VA Audit: Mural Board Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#46504]
## Background
As part of the My VA Audit we want to provide designs for each state of each section of My VA in a Mural board. This will give us a better view into all the changes being proposed and be able to have thorough documentation of each state.

## Tasks
- [x] Create Mural board view into each state of My VA showing the new design proposals for those states
- [x] Share with team

**Comment by aagosto90** [comment]
Updates to the [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1662053865313/b0da65137bbfb9615b09534e9a55fa6b1870846e?sender=uce014850ef6c5a8303e70396) that we discussed on 9/6 are done. Closing this ticket!
