### ISSUE TITLE
Supplemental Claims | Confirm primary phone

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46511]
## Value Statement
**_As a_** Veteran
**_I want to_** confirm my primary phone
**_So that_** I can be reached regarding my claim.

---
## Acceptance criteria

- [ ] User must confirm primary phone before proceeding
- [ ] If user only has one number, don't display this page
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Design and Build Notes
- [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/3EA2CBFB-0365-40BA-B9ED-77C233A93C6B/canvas)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---

**Comment by saderagsdale** [comment]
Hold until after Pam approves content changes.

**Comment by thehastingsp** [comment]
design approved, content still in progress

**Comment by saderagsdale** [comment]
@Mottie hey there - what's the next step on this one?

**Comment by Mottie** [comment]
Waiting to get merged. There are some e2e test errors (from a different app) that need to be resolved before that can happen. Once that is done, we'll need you or design to review.

**Comment by thehastingsp** [comment]
@Mottie can you tag me when it is ready please?

**Comment by Mottie** [comment]
This work is ready to be reviewed in staging. Please note that the URL is now https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/introduction

**Comment by saderagsdale** [comment]
@Mottie Just reviewed. Good to close. I shared some feedback in Slack.
