### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Benefits Team 1, Supplemental Claims Form 20-0995

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#46514]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
This is looking great!

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**
As this goes to code, pay close attention to how each question is labeled. In general, it looks like you're using a heading to as a general question and then a label closer to the input itself to make a specific ask for information, eg. a heading of ["Which facility treated you for your disability?"](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=105%3A7320&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676) and a direct label for the field of "Name of VA medical center, VA treatment facility, or Federal department or agency (* Required)" closer to the input. But that pattern breaks down in a few places, eg. ["Do you want to add another VA facility?"](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=105%3A7443&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676) is followed by pure helper text rather than a direct ask for information.

Keeping a consistent pattern to how you ask for information reduces cognitive load, especially for screen reader users. Definitely continue working with @joshkimux for assistive technology testing and to make sure the interaction pattern makes sense both for the `<label>`/`<input>` situations and for the `<fieldset>`/`<legend>` situations.

But this is me being really picky at this stage. Everything looks really good!

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by briandeconinck** [comment]
I'll be out of office on 9/1 and 9/2, which is why you're getting this a little early. Please reach out if you have any questions or anything isn't clear!

**Comment by saderagsdale** [comment]
@thehastingsp How do we want to handle the "should" feedback here?

**Comment by thehastingsp** [comment]
@Mottie FYSA

**Comment by thehastingsp** [comment]
@briandeconinck workshopped this with @joshkimux who helped me clarify the approach we want to take. @Mottie for our question h3s, we will want the question to be nested in instance of the [label](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=105%3A7320&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676) or [legend](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=105%3A7443&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676) and offer hint text for guidance. We can huddle to walk through an example.

**Comment by thehastingsp** [comment]
@briandeconinck we are incorporating this feedback, so please feel free to close this ticket.

**Comment by thehastingsp** [comment]
@briandeconinck @joshkimux and I went through this and resolved. thank you!
