### ISSUE TITLE
Draft ROE for Call Center reported VFS App Bugs

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4652]
## User Story or Problem Statement
As a VFS team, I need to understand the timeline and priority of call center reported bugs so I can address those bugs properly in my sprint planning.

## Goal
Draft an ROE for VFS teams to handle call center reported bugs.

## Additional Information
- [12/30/19 Discussion Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/call-center/vfs-bug-process-discovery.md)

## Acceptance Criteria
- [ ] Determine timeline guidance for VFS teams
- [ ] Determine priority levels for call center issues
- [ ] Draft an ROE based on timeline guidance and priority levels

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
The latest ROE for this process can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/roe.md I will work on updating this and having it reviewed by Kimberley and Joanne.

**Comment by clantosswett** [comment]
Created an updated version of the ROE. Will need @Kimberley2019 and @joanneesteban to review once it is completed. 

https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/platform/call-center/tier-3-escalation-process.md

**Comment by Kimberley2019** [comment]
@clantosswett I have reviewed the document and the changes that you have made look great.  The only question that I have is under assigning issues, it is stated that it will be assigned to Triage for determination.  Is there still a Triage team or does that need to be changed to back end/front end?  Just want to make sure that we are using the correct team names, also for labeling purposes.

Other than that question, the document looks good.

**Comment by clantosswett** [comment]
@Kimberley2019 I updated to BE tools team though I'm not entirely sure that is the right process. I'll reach out to Alex to see if that makes sense.

**Comment by joanneesteban** [comment]
@clantosswett this is great!

A couple questions: 
- Is the "Lack of Communication" section an additional 48 hours after the "Status Request" or is that the same one? In either case, perhaps adjusting the title to "Further Communication" or something more gentle?

- Can we include the goal (that you need the status in order to report back to Call Centers) so it's a little more clear why there's a distinction between our triaging of bugs and Backend's (since other Platform teams will not track the bug status after it has been handed off to VFS)?

- Is `@ all Call Center team members to be notified` VSP team members or Call Centers directly?

**Comment by clantosswett** [comment]
@joanneesteban I'm not sure you are looking at the right document. I don't think there is a "lack of communication" section anymore. This is the updated version: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/tier-3-escalation-process.md

**Comment by joanneesteban** [comment]
@clantosswett ohhh yes, you're right. Thanks for the update. Then here are my remaining questions:
>Can we include the goal (that you need the status in order to report back to Call Centers) so it's a little more clear why there's a distinction between our triaging of bugs and Backend's (since other Platform teams will not track the bug status after it has been handed off to VFS)?

> Is @ all Call Center team members to be notified VSP team members or Call Centers directly?

**Comment by joanneesteban** [comment]
@clantosswett The updates look good - you can close if this is complete on your end.
