### ISSUE TITLE
Product Directory Issues for custom field requests should not trigger issue/PR workflow

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#46527]
## Issue Description
Currently, our manual request for information updates triggers the same automated workflow as the one that creates a PR for form-based updates. This should not trigger this workflow.

---
## Tasks
- [x] Ensure that the automated workflow only triggers for form-based issue submissions.

## Acceptance Criteria
- [x] Custom submissions for field changes do not trigger the automated workflow and issue responses.
---

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/19cd20a8-95e0-485e-8321-8b3d393baaed)

Two new labels for these. Now the `form-submitted-update` label is required to trigger the workflow.

**Comment by pjhill** [comment]
This is an appropriate process change to address the issue with certain Product Directory change requests.  Thanks!
