### ISSUE TITLE
Focus is not set to the H1 and the change isn't clearly announced. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46540]
#### VFS team name
Authenticated Experience

#### VFS product name
My VA

#### VFS feature name
On-site Notifications

#### Point of Contact/Reviewers
Brian DeConinck (@briandeconinck) - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
When following the "Manage your VA debt" link in the notification and going to the Current VA debt page (/manage-va-debt/your-debt/), focus is not set to the H1 and the change isn't clearly announced by a screen reader. Screen reader users may not be certain what change has happened.

### Link, screenshot or steps to recreate
Steps to reproduce:
1. Visit staging.va.gov and authenticate as test user 220.
2. Activate a screen reader. Recommend testing with NVDA on Windows or VoiceOver on Mac.
3. Press [Tab] until keyboard focus is set to the "Manage your VA debt" link.
4. Press [Enter] to follow the link.
5. Note that after the page is loaded (and after the intermediate announcements while the page is loading), no announcement is made for the H1 heading.
6. Press [Tab]. Note that the first tab stop is the Skip to content link.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
The behavior typically exhibited across VA.gov would be for focus to be set to the Current VA debt H1 on page load, and the next tab stop to be the first link that follows that heading. Since that's the main interaction pattern, following the link in the notification should match that pattern.

The actual impact on users is relatively minor --- the first tab stop is a skip link that takes them to the place they'd expect to go --- but it's a deviation from the expected behavior that might trip up some users.

Not sure if this is actually in scope for Onsite Notifications or if it's an issue with the Current VA debt page, but flagging anyway so it can be assigned to the appropriate team as needed.

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by ajakabcin** [comment]
@briandeconinck is this an issue with the My VA page or the debt page (/manage-va-debt/your-debt/)? Our team doesn't manage the debt page. Thanks in advance for you help clarifying!

**Comment by briandeconinck** [comment]
H @ajakabcin! Sorry for the delayed response. Looking at this again, yes, I think it's an issue with the debt page rather than your product.

**Comment by shiragoodman** [comment]
@denisecoveyduc could you take a look at this and let us know if you agree with @ajakabcin and @briandeconinck above? If so, I can update the issue ticket so it has your product's labels.

**Comment by denisecoveyduc** [comment]
@shiragoodman Yep! Will have the team take a look. Thanks all for drawing our attention to it. 
cc: @OptionSelect @Dr-Pongo

**Comment by ajakabcin** [comment]
Removing this from our staging review epic since it doesn't pertain to our onsite notifications feature :)

**Comment by shiragoodman** [comment]
@denisecoveyduc do you have a product label? I thought `vsa-debt` was your team label, not product label. Please let me know!

**Comment by denisecoveyduc** [comment]
@shiragoodman you are correct. Just added the Combined Debt Portal Label - `CombinedVADebt`

**Comment by denisecoveyduc** [comment]
@Dr-Pongo will double check that this. is resolved on the combined debt portal

**Comment by Dr-Pongo** [comment]
Closing out as this is no longer an issue. 
#### Steps to confirm:
1. Visit [staging.va.gov](https://staging.va.gov/) and authenticate as test user 81 (or any user with both debts and copays)
2. Activate a screen reader. Recommend testing with NVDA on Windows or VoiceOver on Mac. (This test was done with voiceover on mac)
3. Navigate to [staging.va.gov/manage-va-debt/](https://staging.va.gov/manage-va-debt/)
4. Press [Tab] until keyboard focus is set to the "Manage your VA debt" link.
5. Press [Enter] to follow the link.
6. Note that after the page is loaded (and after the intermediate announcements while the page is loading), an announcement is made for the H1 heading.

---

Optional steps to be thorough and confirm h1 is announced on every page in app:
#### For debts:
1. Navigate to [staging.va.gov/manage-va-debt/summary/](https://staging.va.gov/manage-va-debt/summary/)
2. Use [Tab] navigation until focus is set on "Check the status and resolve your debt" link
3. Press [Enter] to follow the link
4. Note that after the page is loaded (and after the intermediate announcements while the page is loading), an announcement is made for the H1 heading.
5. Use [Tab] to navigate until focus is set on "Check details and resolve this debt"
6. Press [Enter] to follow the link
7. Note that after the page is loaded (and after the intermediate announcements while the page is loading), an announcement is made for the H1 heading.


#### For copays:
1. Navigate to [staging.va.gov/manage-va-debt/summary/](https://staging.va.gov/manage-va-debt/summary/)
2. Use [Tab] navigation until focus is set on "Check your balance and resolve your bill" link
3. Press [Enter] to follow the link
4. Note that after the page is loaded (and after the intermediate announcements while the page is loading), an announcement is made for the H1 heading.
5. Use [Tab] to navigate until focus is set on "Check details"
6. Press [Enter] to follow the link
7. Note that after the page is loaded (and after the intermediate announcements while the page is loading), an announcement is made for the H1 heading.
