### ISSUE TITLE
Convert Github Documentation to Confluence - Automate Scripts

### ISSUE THREAD

**Issue by FHiatt** [department-of-veterans-affairs/va.gov-team#46542]
## Problem
As an engineer I want people to be able to access my IET product documentation. Some people who will want to access my product documentation do not have access to github but have access to Confluence.
Therefore, I would like to use github as my source of truth for my IET documentation and have that source be used to automatically fill and format this documentation in Confluence, where if github is updated Confluence will automatically be updated.

## Acceptance
- [ ] A script will be available to automatically update Confluence with any documentation changes made in github for: Sidekiq UI, the Vets-API Migration Plan, the MicroServices Deploy Playbook

**Comment by ewilson-adhoc** [comment]
This was out of scope of IET end work, we added documentation to console UI. Closing this ticket.
