### ISSUE TITLE
Create DataDog alerting monitors

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#46541]
## Description
This will track the body of work for various DataDog alerting monitors

### **Outbound**
- [ ] __Staging__
  - [ ] ID.me
    - [ ] SSOe
    - [ ] Sign in Service
  - [ ] Login.gov
    - [ ] SSOe
    - [ ] Sign in Service
  - [ ] DS Logon
    - [ ] SSOe
    - [ ] Sign in Service
  - [ ] My HealtheVet
    - [ ] SSOe
    - [ ] Sign in Service
- [ ] __Dev__
  - [ ] ID.me
    - [ ] SSOe
    - [ ] Sign in Service
  - [ ] Login.gov
    - [ ] SSOe
    - [ ] Sign in Service
  - [ ] DS Logon
    - [ ] SSOe
    - [ ] Sign in Service
  - [ ] My HealtheVet
    - [ ] SSOe
    - [ ] Sign in Service

### **Unified Sign in Page (USiP)**
- [ ] __Staging__
  - [ ] MHV
    - [ ] SSOe only (SiS is not enabled)

### **Inbound (SSOe only)**
- [ ] __Dev__
  - [ ] ID.me
  - [ ] Login.gov
  - [ ] DS Logon
  - [ ] My HealtheVet

### **Forced Authentication routes**
- [ ] __Dev | Staging | Prod__
  - [ ] ID.me
    - [ ] SSOe `idme_verified`
    - [ ] Sign in Service `type=idme&acr=loa3`
  - [ ] Login.gov
    - [ ] SSOe `logingov_verified`
    - [ ] Sign in Service `type=logingov&acr=ial2`
  - [ ] DS Logon
    - [ ] SSOe `dslogon_verified`
    - [ ] Sign in Service `type=dslogon&acr=loa3`
  - [ ] My HealtheVet
    - [ ] SSOe `mhv_verified` (double check this is not `myhealthevet_verified`)
    - [ ] Sign in Service `type=mhv&acr=loa3`

## Acceptance Criteria
- [ ]  Create a new ticket to track the body of work to fix said issue *optional (can use this ticket to track body of work)

**Comment by bosawt** [comment]
@asg5704 Do you think we still need this ticket? I think we've basically done it by now

**Comment by bosawt** [comment]
Wondering if I can close it

**Comment by asg5704** [comment]
Close it
