### ISSUE TITLE
Adding Hakeem Jones to DSVA Slack

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#46558]
# Description
Please add hakeem.jones@va.gov as a full member to at least the #vfs-platform-support channel.

**Comment by Gfeliberty** [comment]
@LEHigley
@KevinMHoffmanUSDS 
I am Hakeem's Job Leader and Product Manager for Lighthouse OAuth; is there a status on getting the DSVA Slack access approved? Once we have this in place we will be able to finalize his AWS. 
Thanks in advance for your time and consideration.

**Comment by CoryTrimmUSDS** [comment]
Invited Hakeem to the DSVA Slack workspace.

**Comment by hncj811-va** [comment]
@CoryTrimmUSDS where should I look for the slack invite? I don't see anything in the app or on my email.

**Comment by hncj811-va** [comment]
@CoryTrimmUSDS may you send the invite to my bah machine too. 
jones_hakeem@bah.com

**Comment by hncj811-va** [comment]
@CoryTrimmUSDS did you see above?
