### ISSUE TITLE
Update product directory machine readable documentation to reflect better support request process

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#46565]
## Issue Description
Update the documentation to direct platform teams that wish to have access to BigQuery to place the support request directly with the analytics team.

---
## Tasks
- [x] Update the documentation to direct users directly to the analytics team for access to our BigQuery table `vsp-analytics-and-insights.testing_tools_team.vfs_product_directory`

## Acceptance Criteria
- [x] Documentation is updated to direct platform teams directly to the analytics team with the appropriate table name that access will be needed to.

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/33214459-aee3-4a02-9aa6-dfe7ad1079fa)

Documentation updated!

**Comment by pjhill** [comment]
Looks like a good update to me!
