### ISSUE TITLE
COE: Ensure that the documents list on the status app is sorted by date

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#46566]
## Value Statement

**_We want to_** make sure that the documents list is sorted correctly on the COE Status Application
**_So that_** are able to easily access the most relevant documents.

---
## Background Context
Robin has been reviewing the front end and noticed our mock data only ever returns a single document.

So, we should mock a scenario where multiple documents are loaded, in the correct order.

## Tasks
- [ ] Confirm that documents are ordered with the most recent at top
- [ ] Update mockdata to mimic scenario where multiple documents are returned

**Comment by jerekshoe** [comment]
This should already be sorted: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/coe_controller.rb#L38
