### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46567]
### Survey Type Requested

User Surveys

### Date Range Start

07-01-2022

### Date Range End

08-31-2022

### Product Name(s)

VAOS

### Product Description

Provides Veterans the ability to schedule and view appointments.

### Product URL(s)

va.gov/health-care/schedule-view-va-appointments/

### VA Email Address(es)

Leah.Delacosta@va.gov, Jeffrey.Roof@va.gov

**Comment by ianMcCullough-ob** [comment]
data sent
