### ISSUE TITLE
Access for Eric Buckley

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#4657]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Dan Navarra
- Please provide your name.
   > Eric Buckley
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA SSO, Sr Engineer, Ad Hoc
- Public SSH Key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzVoCbfJUkAuqS3po9hHBB0FL/qlY/g6cJAEsPf+B+xXyDJO6rgpi4KBhytD9+qDc9+qbyeYXJJzB2QpSIuYNXW7VS0sLkwPr4AwsIVKAlOnhh3d1+bOk25wFKkY8MRtA//zOc/rVUDNSTsRP/lubbcn+sJjkw791ijjyu1tWJ+MGeagq3H8r6NEsK358Fqpb6Ii/T1OcDZX786mkAb7vUiEE/PViWYyS4IpsdKfj33EMx4UI0x3by6fCHfPuK0SMgg7Nu2BYxug4LnLsRuZ/+owFsz6/U1CyxYvM13U2R+5ktUfWe8a50dCu17ZTUmeAmLlPjrFfwik7Qcadxze5k1nmvwULPJk9m5/SeKBZua4FO0GG8nlGP6qQwH5fQIlAm1KB9isB2jc8ekjMJkd46mqASxhS52OEH+aTov+/nSlg8pC5wLfHJUQ9kOZz0gC02WK9PIp6EYf964spK/+mxxIh78uZL2hP+3UC8w9LAA3riyJ2oXEw9g2R3wBQJAv7cndf2T0SJot3VmTd4x4eQn/2Rt8qEzJsv1UwKvgk1+G3a4J3n+1vvdLbRShF16EnhKmi9pyl3qgQ9BuIh6ZAxs1AJmYi7U9K5G2hSxEMu6gewRV8j/6KcpUoUPYN20bNw/XNrYNrFgWzGNp8dG5rRbBU9a/R3zaaFG6mBF8z4Sw== eric.buckley@adhocteam.us
```

- [Grant AWS Console access?]
  > NO

**Comment by ericbuckley** [comment]
ping @department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Michael Domanski
User: Eric Buckley

**Comment by ambikaroos** [comment]
@ericbuckley to reach out to Cat to follow up

**Comment by ericbuckley** [comment]
@ricetj / @Jeff-Hayter I was informed earlier today that Michael is no longer the COR for the project that I'm on, it is now Dan Navarra.  I've updated the description as well.

**Comment by ricetj** [comment]
@ericbuckley due to new changes in the process SOCKS access is granted sooner, but do please keep following up with your paperwork for the VA.

**Comment by ericbuckley** [comment]
great, thank you!
