### ISSUE TITLE
Links on "VA.gov Continuous Integration Process" lead to old GitHub docs, at least one leads back to a 404 on platform docs

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#46587]
### Description

["VA.gov Continuous Integration Process"](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-continuous-integration-process) has multiple links that lead to outdated Github docs. A ["Deployment Process" link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/deployment.md) leads to a Github page that has a broken link in its "Find [the latest version of this page](https://depo-platform-documentation.scrollhelp.site/infrastructure/Deployment-process.590970953.html)" forwarding link. I believe docs should link to [this Platform docs page](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-process).

### Relevant URLs

* https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-continuous-integration-process
* https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-process

**Comment by taylojill** [comment]
9/2/22 - @dcloud Broken links fixed. Updated page will be published on 9/6/22.
