### ISSUE TITLE
Adding Chris Willis to DSVA Slack

### ISSUE THREAD

**Issue by laurylzenobi** [department-of-veterans-affairs/va.gov-team#46581]
Please add [Chris Willis](chris.willis@adhocteam.us) as a full member. Chris is the product manager for the VES-VHA Eligibility and Enrollment team, and will need access to slack to communicate with their PO and coordinate Veteran research with their team.

**Comment by eunicegar** [comment]
what is the email address?

**Comment by TPurple** [comment]
@eunicegar chris.willis@adhocteam.us

**Comment by eunicegar** [comment]
sent invite to join as a member
