### ISSUE TITLE
Investigate Refresh token is not defined

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46585]
http://sentry.vfs.va.gov/organizations/vsp/issues/116969/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by joeniquette** [comment]
Also this: http://sentry.vfs.va.gov/organizations/vsp/issues/125053/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by joeniquette** [comment]
and this..: http://sentry.vfs.va.gov/organizations/vsp/issues/119076/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by AGarcia-Clarity** [comment]
Unable to reproduce locally or in staging.
