### ISSUE TITLE
Fix "benefit office" references on static web pages (to "regional office")

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4658]
**Problem statement:** The style guide calls for using "regional office," not "benefit office" when referring to VA regional offices, but some of our pages are using "regional benefit office." This is not new guidance, as it was a carry over from vets.gov guidance, but I think we've just gotten inconsistent over time.

**Style guide:** https://design.va.gov/content-style-guide/word-list#v
VA regional office: Use “VA regional office” and not “VA regional benefits office.” “Regional Office” should only be capitalized if a specific name is included in the title.

Like this: The Buffalo Regional Office (RO) is one of four regional processing centers nationwide that process education claims.

**Action:**
[ ] Please do a scrub of this term on our site and update as needed. Example pages included below. There will likely be others. 
[ ] Add a style guide cross reference under B for "benefit office" with guidance to not use and to see the entry "VA regional office."

This ticket is part of the ongoing epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1595  

FYSA @Karak888

EX: 
https://www.va.gov/disability/dependency-indemnity-compensation/

https://www.va.gov/disability/how-to-file-claim/

https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea/

**Comment by RLHecht** [comment]
@jenniferlee-dsva I updated about 25 pages (!) that had "benefit office" instead of "regional office." Most were in Drupal and those pages have been published. A few were in decision reviews so I created a PR for you to review and merge for those. There are two instances that I am not sure I can access and will need @ncksllvn or @kelsonic to help with. 

1. Main page: Screen shot below:![Screen Shot 2020-01-10 at 4.47.59 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/059b8a72-583b-4842-8018-2ed1877b5349)

2. https://www.va.gov/find-locations/

**Comment by jenniferlee-dsva** [comment]
@RLHecht ^ -Although the homepage does now live in Drupal (but in weird places in the CMS IA), I think the button in your screenshot is controled by FE. (@kevwalsh or @ncksllvn / @kelsonic for confirmation.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I created a pull request for you to review to add the entry to the style guide word list.

**Comment by kelsonic** [comment]
Sent up a PR for this! Turns out we have instances that need to be updated in [facility locator, profile360, and the homepage](https://github.com/department-of-veterans-affairs/vets-website/pull/11479/files) 🙂

**Comment by kelsonic** [comment]
Merged in the above PR @RLHecht! 🙂Let me know if there's anything else I can do on my end for this ticket!

**Comment by Karak888** [comment]
@RLHecht @kelsonic can you please add an estimate to this please? Thanks

**Comment by RLHecht** [comment]
@Karak888 Estimate added. All the work is done on this. Just need to validate updates on live site after 1/15 deployment.

**Comment by RLHecht** [comment]
This has been validated on live site. Closing issue. Thanks for the help, @kelsonic ! @Karak888
