### ISSUE TITLE
investigate missing mpi_update_profile_template error

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46584]
http://sentry.vfs.va.gov/organizations/vsp/issues/134713/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by joeniquette** [comment]
also this: http://sentry.vfs.va.gov/organizations/vsp/issues/134843/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by joeniquette** [comment]
and this: http://sentry.vfs.va.gov/organizations/vsp/issues/130600/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by bosawt** [comment]
I'm gonna take this ticket and refactor these MPI calls so that they don't use a file as a template to build the request, but do it all within the code itself
