### ISSUE TITLE
Investigate undefined method `body' for #<MPI::Errors::ArgumentError:

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46586]
http://sentry.vfs.va.gov/organizations/vsp/issues/130790/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by bosawt** [comment]
This is happening because we aren't able to parse MPI attributes. For one example user, we don't parse name, so we set it to nil, however it is in their `patientPerson` stanza:
`                <patientPerson>
                  <name use="ASGN">
                    <given>xxx</given>
                  </name>
                  <name use="L">
                    <given>xxx</given>
                    <given>xxx</given>
                    <family>xxx</family>
                    <suffix>SR</suffix>
                  </name>
                  <name use="C">
                    <family>xxx</family>
                  </name>
`
