### ISSUE TITLE
[BE] Profile folder on Github: Moving files request

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#46582]
### Tasks

Tom, could you do the following?:

- [x] Move [account-settings-V1](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-settings-V1) under the [account-security](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security) folder
- [x] Rename [connected-apps-data](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/connected-apps-data) to just "connected-apps"

Thank you!

**Comment by tpharrison** [comment]
Hi @Samara-Strauss - the folders have been moved/renamed.  Please verify when you get a chance.  Thanks!

**Comment by Samara-Strauss** [comment]
Validated! Thank you, @tpharrison!
