### ISSUE TITLE
Clean up validations being served in GH to reduce/eliminate false positives

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4659]
### User Story

As a VFS team member using a repo that has the Vale GitHub action, I only want to see Vale validations that are relevant to my actual content, so that I can act on useful content suggestions without getting lost in noise/seeing content validations related to my code.

**Comment by billfienberg** [comment]
There are currently a lot of false positives related to common technical terms like `www` or `json`. 

As of 2020-01-22, the current list is:
```
www
html
src
env
https
telehealth
Webpack
Metalsmith
param
repo
config
Teamsite
Dev
jenkins
Bing
menubar
json
npm
sourcemaps
css
github
js
eslint
dev
webpack
buildtype
onclick
nonced
Camelcase
uris
attrs
unicode
urls
url
uri
uris
srcset
stdout
metalsmith
const
```

Here's a link to the config file in the Draft PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/11429/files#diff-bfd8b68bd19ba58666e0059c4c86c26a

**Comment by vbellissimo** [comment]
Cancelling/old task.
