### ISSUE TITLE
Midpoint Review - design feedback - [Benefits Team 1, Supplemental Claims Form 20-0995]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#46600]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Thank you for all this great work!
- Robin verified the editing contact info is in production and good to use
- Robin verified the mid form summary is in production and good to use
- I did confirm that this [list and loop pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task#va-online-scheduling-vaos-vaccine-sub-task) has been added to the DS so no need to go through experimental design.
- Be sure the one thing per page goes through experimental design

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Follow the guidelines for [uploading another file](https://design.va.gov/patterns/ask-users-for/files#review-state) or if you want to propose a new pattern use experimental design.
- Update [address block](https://design.va.gov/storybook/?path=/docs/components-address-block--default-story) component blue bar width from [6px to 3px](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=89%3A4965&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676). Name should also have normal casing.
- Ensure that design element specs align with what is in the [design system](https://design.va.gov/foundation/color-palette). For example, input field border colors in the design are #000000 however should be $color-gray (#5b616b).

**Should:**

**Consider:**
- If you need options for another secondary or tertiary button for cards, consider using [Matt’s exploration](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347). This might be helpful for list and loop.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by saderagsdale** [comment]
@thehastingsp Do we need to take care of any of the "must" feedback above?

**Comment by thehastingsp** [comment]
In progress @saderagsdale

**Comment by thehastingsp** [comment]
@allison0034 follow up with question on #1.

MUST: 
1. `Follow the guidelines for [uploading another file](https://design.va.gov/patterns/ask-users-for/files#review-state) or if you want to propose a new pattern use experimental design.` I'm not clear where we are breaking the design system pattern? The only difference I see is that we moved the "upload another document" to the next page where we are asking "would you like to upload another file" when the user selects continue so we can preserve the conversation flow and behavior of one question per page we have established in the form interactions. Maybe I'm missing what you are specifically referring to? I can come to office hours to clarify if you'd like.  

2. `Update [address block](https://design.va.gov/storybook/?path=/docs/components-address-block--default-story) component blue bar width from [6px to 3px](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=89%3A4965&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676). Name should also have normal casing.` **Done**

3. `Ensure that design element specs align with what is in the [design system](https://design.va.gov/foundation/color-palette). For example, input field border colors in the design are #000000 however should be $color-gray (#5b616b).` **Doing**

Consider:` If you need options for another secondary or tertiary button for cards, consider using [Matt’s exploration](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347). This might be helpful for list and loop.` I'll workshop this a bit and ping Matt to understand his explorations and see if I can use this and preserve the secondary back button.

**Comment by allison0034** [comment]
Hi @thehastingsp 

1. Yes, that is what I was referring to, but given you are testing one question per page this may fall in that range. Let me confirm with Matt.
2. Thank you
3. Thank you

Consider: thank you, this is awesome!

**Comment by allison0034** [comment]
@thehastingsp I confirmed with Matt, please use our [current pattern for uploading](https://design.va.gov/patterns/ask-users-for/files#review-state) by placing the "add another" on the same page

**Comment by thehastingsp** [comment]
@allison0034 ok thanks will do

**Comment by thehastingsp** [comment]
@allison0034 confirming that I'll be using the current pattern for uploading so this ticket is ready to close. Thank you!
