### ISSUE TITLE
Research ATO for BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4660]
## User Story or Problem Statement
How might we determine what criteria we need for ATO for BigQuery so that we can understand how BigQuery can affect VA's data security and get approved to implement BigQuery ?

## Goal
Determine what we need to get ATO for BigQuery.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] Draft admin and billing process for Nancy so that BigQuery account is linked to DSVA

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
Next steps:
- Research ATO with Faith
- Jon and I will attend meeting with federal contacts at Google Cloud Platform on 1/15/2020 at 10 and will miss a portion of grooming

**Comment by joanneesteban** [comment]
@amycesal "blue sky" includes qualitative user feedback from call centers and surveys, correct? @nedierecel When you research ATO with Faith, can you bring up the possibility of filtering out PII and storing non-PII free text?

**Comment by nedierecel** [comment]
@joanneesteban I can request. We should think about how we filter for PII that does not follow any email, phone, or home/mailing address patterns.

**Comment by nedierecel** [comment]
@joanneesteban For visibility, I added Nancy's request for billing as an acceptance criteria above. I'll outline these are as I gather the information.

**Comment by nedierecel** [comment]
Follow up items I will need to research with Faith and Google: 
- [ ] Organization name is required to set up billing - I will research if there is an existing organization at a federal level that we should attach our Google BigQuery project.  
- [ ] Region for storage to be selected
- [ ] Establishing billing contact and account (Provide this to Nancy)
- [ ] Obtain list of our VSP contacts that need to be on the GCP/BigQuery account for Identity and Access Management (IAM)

**Comment by nedierecel** [comment]
@joanneesteban I scheduled time with Faith and Jon on Thurs. 1/23 at 11:30 ET to discuss the BigQuery ATO process.

**Comment by nedierecel** [comment]
### Sprint 21
- Attended call with SaaS Inquiry process led by Alysse M Ketner and Puneet-Paul Kalra
  - VSP Attendees: Nancy Smith, Jon Wehausen, Joanne Esteban, Kevin Hoffman, Nedie Recel

**Comment by nedierecel** [comment]
@bsmartin-ep No further action here, but I wanted to keep you on this issue which is the authority to operate process for BigQuery.

**Comment by joanneesteban** [comment]
ATO work moved to Faith in Operations. Closing this ticket.
