### ISSUE TITLE
[09/09/22] OSM promotional material

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#46607]
## Description
Create a 1-2 page promotional document about OSM to go hand-in-hand with upcoming memorandum
---

## Acceptance Criteria
- [x] Draft OSM document
- [x] Review with team
- [x] Approved by Justin/Lindsay/Shane
- [x] Approved by OSM group
---

**Comment by ahicksfearless** [comment]
Passed off a one-page document for review on 9/6

**Comment by lindsay-insco** [comment]
Posted to SharePoint!
