### ISSUE TITLE
PagerDuty accounts for VAOS team

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#46608]
Please make the following changes to PagerDuty for the VAOS team.

**Remove Access**
Bradley Gross – [Bradley.gross@b3groupinc.com](mailto:Bradley.gross@b3groupinc.com) – currently has access, account can be removed

**Grant Access**
Jeffrey Roof – [Jeffrey.Roof@va.gov](mailto:Jeffrey.Roof@va.gov) / [jeff.roof@adhocteam.us](mailto:jeff.roof@adhocteam.us) – needs access
Simi Adebowale - [simileoluwa.adebowale@va.gov](mailto:simileoluwa.adebowale@va.gov) / [simi.adebowale@adhocteam.us](mailto:simi.adebowale@adhocteam.us) – needs access

**Example Account**
AJ Magdub – [ahmed.magdub@va.gov](mailto:ahmed.magdub@va.gov) – currently has access, use this account as an example when creating new accounts

**Comment by zachclarity** [comment]
Thanks @little-oddball   Added
