### ISSUE TITLE
Midpoint Review - Research Feedback - Benefits Team 1, Supplemental Claims Form 20-0995

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#46613]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
This looks great, well thought through! Also thank you for piloting the new recruitment section and offering feedback. A note that my feedback here is as part of the Midpoint Review and not the Research Review. Your research will still need to go through the [Research Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) before kicking off recruitment.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**None**
none

**Should:**
none

**Consider:**
1. Consider: Research Plan > Timeline
As mentioned during the meeting, I don't foresee an issue with having specific start times listed, just spotlighting that we generally submit open timeframes so the recruiters have a bit more leeway in booking session to a participant's need.

2. Consider: Conversation Guide > may need additional questions about experimental design patters used
With this design's inclusion of several design patters that are considered experimental, as discussed in the meeting, you may decide to explore those particular patters deeper with participants. Consider whether successfully exploring those requires additional specific questions about those patters.

**Comment by thehastingsp** [comment]
@claytonzook thank you for the feedback. I've rewritten the timeline to offer time spans and pushed it back slightly to accommodate midpoint review changes and team timing.

**Comment by claytonzook** [comment]
@thehastingsp I unfortunately won't have a chance to guide this through the official Research Review touchpoint and to recruitment, as today is my last day on this contract. 

If you are ready to move forward with the Research Review touchpoint and to begin recruiting, give Shane Strassberg a ping either on your research repo card or in the Research-ops slack channel. You can also call out this ticket to show that your research artifacts have already been through review as part of the Midpoint Review touchpoint.

Finally, since the Governance Team views these feedback tickets as your team's ownership, you are free to close this at your leisure.

**Comment by thehastingsp** [comment]
@claytonzook thank you! I've enjoyed working with this on you and appreciate your guidance. @sstrassberg tagging you for awareness that this research has been through review.

**Comment by thehastingsp** [comment]
closing as this has been through research review.
