### ISSUE TITLE
Coordinate with a VFS product team to test out Vale GitHub action

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4661]
### Problem Statement

Knowing that we will be adding Vale as a GItHub action to an entire repository, how might we coordinate with a single (or two) product team(s) to control messaging and use of the validations and gather direct feedback? 

### Details/Notes

We cannot do a slow rollout within a single repo, so the goal here is to do a slow rollout of our messaging. 

### Definition of Done
- [ ] Identify 1-2 product teams who are interested in working with us on this.
- [ ]  Identify what GitHub repos we would need to add Vale to in order to work with those product teams.
- [ ] Coordinate messaging, instructions, and goals with product team in advance of release

**Comment by billfienberg** [comment]
Since `vets-website` contains a bunch of static content, I definitely think it makes sense for the GitHub action to be used there. 

I did a quick scan of `vets-api`, and I don't see little-to-no user-facing content in there.

**Comment by vbellissimo** [comment]
Cancelling/old task.
