### ISSUE TITLE
Finalize configuration of Vale as GitHub action

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4662]
### User Story

As a VFS team member, I need Vale to work properly in the repo I am using, so that I can see automated content validations and write my own error-free, plain language content, to reduce the burden of manual support on both myself and the VSP content editor.

### Details/Notes

Team had discussed possibility of storing Vale config files in separate repo, to be pulled as needed into various VA.gov repos.

**Comment by billfienberg** [comment]
According to the [`vale-action` docs](https://github.com/errata-ai/vale-action#styles), we can provide a "space-delimited list of external styles." I attempted to extract our styles into a separate repo and rerun the github action, but it didn't seem to work. 

According to the [`styles` docs](https://github.com/errata-ai/styles#available-styles), the available styles include implementations from Microsoft, Google, `write-good`, `proseLint`, and `JobLint`. I still need to try using one of the existing available styles to determine the GitHub action supports any external style, or only the styles specified above.

**Comment by vbellissimo** [comment]
Cancelling/old task.
