### ISSUE TITLE
Refactor Cypress test to remove deprecated cy.setup and cy.route commands.

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#46628]
## Description
Refactor Cypress test to remove deprecated cy.setup and cy.route commands. These commands have been deprecated since 6.0.0. In a future release, support for cy.server() and cy.route() will be removed.

---

## Acceptance Criteria
Background: the `toggle` toggle is on
All stubbed endpoints should use 'cy.intercept'

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
No issues reported in this ticket. Closing out the ticket.
