### ISSUE TITLE
Task: Change all instances of "OJT" to "on-the-job training"

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#4663]
## User Story

As a content editor, I need to ensure all pages adhere to our style guide so there is consistency across the brand.

## Goal

Change all instances of "OJT" on the below pages to "on-the-job training":

- https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/
- https://www.va.gov/gi-bill-comparison-tool/

Preview node ID:
preview-prod.vfs.va.gov/preview?nodeId=923

@peggygannon I think the GI Bill Comparison tool change needs to be made by you since this page lives with the Apps team. 

## Objectives or Key Results this is meant to further
Adherence to the style guide across the whole VA.gov site

## Acceptance Criteria
- [x] Changes made ( @RLHecht )
- [x] Reviewed and published ( @peggygannon )

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@peggygannon Can you please review and publish these changes? Thanks!

**Comment by peggygannon** [comment]
Thanks, @RLHecht page is reviewed and published. I'll work with the BAH team to update GI Bill Comparison Tool .

**Comment by RLHecht** [comment]
Changes published. Closing ticket.
