### ISSUE TITLE
[bug] Certificate of Eligibility | Congratulations message is missing

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#46647]
## Value Statement
**_As a_** Veteran
**_I want to_** see a contratulations message when I receive my Certificate of Eligibility
**_So that_** I know when I've been identified as eligible for a VA loan.

---
## Background Context
This issue was reported by LGY. When using the following test user, vets.gov.user+0@gmail.com, the automated congratulations message is missing.

## Acceptance Criteria
- When a user is approved for a Certificate of Eligibility, they see a congratulations message.

## Tasks
- [ ] Analyze the payload from the determination request when authenticated as this user to understand why this status isn't properly being captured.

**Comment by saderagsdale** [comment]
@scottymeyers Does this need to be transferred over to Robin and/or Eugene?

**Comment by jerekshoe** [comment]
This is what I get back when making the `get_determination` call to LGY's staging service for user with EDIPI: `1005329660` (vets.gov.user+0@gmail.com)

```json
{
	"referenceNumber": "17535373",
	"status": "NOT_ELIGIBLE",
	"determinationDate": 1663180820000
}
```

**Comment by saderagsdale** [comment]
Discuss with LGY because the data from the server says they are ineligible @Mottie @data-doge

**Comment by data-doge** [comment]
Sent the following message to Kelli on 9/26:

> Fortunately, I don’t believe there is any issue with the congratulations message! Given that [vets.gov.user+0@gmail.com](mailto:vets.gov.user+0@gmail.com) should be NOT_ELIGIBLE, and given that users who are NOT_ELIGIBLE should not see a congratulations message — we should expect [vets.gov.user+0@gmail.com](mailto:vets.gov.user+0@gmail.com) to not see a congratulations message. Since this is the reported behavior, and since this reported behavior is expected, I don’t believe there is any follow up here. Please let me know if I am misunderstanding anything.

No response yet. I'll email Kelli to confirm whether we can close this issue.

**Comment by data-doge** [comment]
Kelli just responded: 
> Yes that item can be closed

I'll close this issue.
