### ISSUE TITLE
Monitor Optimal Workshop Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46651]
## Tasks
- Find unique IDs at the end of every day and send those back to Perigean
- When hit max number tell Perigean we are done

**Comment by kristenmcconnell** [comment]
26 Veterans completed the studies (13 each) by the afternoon of the first day.

**Comment by kristenmcconnell** [comment]
End of day 1:
Check-in: 16 participants
Pre-check-in: 24 participants

**Comment by kristenmcconnell** [comment]
End of day 4:
Check-in: 23 participants
Pre-check-in: 28 participants

**Comment by kristenmcconnell** [comment]
Numbers this morning:
Check-in: 27 participants
Pre-check-in: 34 participants 

I messaged Perigean and told them that the pre-check-in study can be closed. I was shooting for 30-35 participants. One study down; one to go.

**Comment by kristenmcconnell** [comment]
The check-in study closed today with 32 participants. @loripusey This ticket is done now, so we could synthesize and complete the report next sprint.
