### ISSUE TITLE
[UX] Create high level UX recommendation for Making Pre-Check-in on Day-of Clearer for the Veteran

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46658]
## Scenarios
- Between midnight on the day-of an appointment and 30-minutes before your appointment. Current solution)
- Between 30-minutes before and 15 minutes after your appointment (Captured in the Mural, link below)
- Greater than 15 minutes after your appointment (Current solution)

## Tasks
- Evaluate current functionality for these scenarios
- Talk to engineering about feasibility of potential solutions
- Make recommendations for how we might 
     - Update the wording for clarity
     - Send Veterans over to Check-in if they are within the check-in window

## UX Deliverable
- [x] UX recomendation in [mural link](https://app.mural.co/t/vfscie8528/m/vfscie8528/1663005558867/b1bc99cc3e652cc456a2e25d6a4b71891f322e43?sender=ue81e026b3c283b5452e52493): https://app.mural.co/t/vfscie8528/m/vfscie8528/1663005558867/b1bc99cc3e652cc456a2e25d6a4b71891f322e43?sender=ue81e026b3c283b5452e52493

**Comment by loripusey** [comment]
@zach-park have you started this?

**Comment by zach-park** [comment]
No, I haven't made much progress. It would need to be re-prioritized for future sprints.

**Comment by benbrasso-agile6** [comment]
Assigned everyone for the moment until we meet to discuss who has next steps on this ticket.

**Comment by benbrasso-agile6** [comment]
Actually. Change that. @zach-park do you want to clean up the mural and share it on friday?

**Comment by zach-park** [comment]
@benbrasso-agile6 , here is [the mural link](https://app.mural.co/t/vfscie8528/m/vfscie8528/1663005558867/b1bc99cc3e652cc456a2e25d6a4b71891f322e43?sender=ue81e026b3c283b5452e52493): https://app.mural.co/t/vfscie8528/m/vfscie8528/1663005558867/b1bc99cc3e652cc456a2e25d6a4b71891f322e43?sender=ue81e026b3c283b5452e52493

**Comment by loripusey** [comment]
Engineering tickets have been created, closing this one.
