### ISSUE TITLE
[Research] Brainstorm Ways to Get Started

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46659]
## Tasks
- Brainstorm ways to test Check-in on a VA-owned device at a facility
- Determine the next steps
- Create tickets as necessary

**Comment by kristenmcconnell** [comment]
Google spreadsheet with [questions/ideas](https://docs.google.com/spreadsheets/d/1bFazMIE_rKhQtEzEi1p66qFVhO0sIeu7aa5QXXNTPB8/edit?usp=sharing) for now. I'll export it as a PDF once I get further along.

**Comment by kristenmcconnell** [comment]
[Exported spreadsheet](https://app.zenhub.com/files/133843125/588912f8-25a8-41cb-997b-e54e608f20f7/download)

**Comment by kristenmcconnell** [comment]
Made a [GitHub page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/VA-owned-device/research-brainstorm.md) instead and put a meeting on the calendar for Thursday for the team to discuss.

**Comment by kristenmcconnell** [comment]
[Mural](https://app.mural.co/invitation/mural/vsa8243/1663107589182?sender=uc940f53ad96ac0203d6d3631&key=e9a1a0bf-fd5e-4dd5-af9b-2bf0fdd91372) for the identity verification discussion at Thursday's meeting.

**Comment by kristenmcconnell** [comment]
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1663261332083169) from today's team meeting.

**Comment by kristenmcconnell** [comment]
[Identity Verification Discussion Mural](https://app.zenhub.com/files/133843125/661dd220-9e14-49db-9019-f581f28b861f/download)
