### ISSUE TITLE
Update #vagov-accessibility to #accessibility-help

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#46664]
### Description
We recently updated the channel name of #vagov-accessibility to #accessibility-help and need to update platform docs to reflect that including the following:

- [ ] [How to request help](https://depo-platform-documentation.scrollhelp.site/developer-docs/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Howtorequesthelp)'s #accessibility-ops should be changed to #accessibility-help
- [ ] [Research Safety and Emergency Exit Strategies](https://depo-platform-documentation.scrollhelp.site/research-design/research-safety-and-emergency-exit-strategies)'s #vagov-accessibility should be changed to #accessibility-help
- [ ] [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)'s #vagov-accessibility should be changed to #accessibility-help

**Comment by taylojill** [comment]
9/7/22 - Hello @joshkimux Three pages updated with new link and channel name. They will be published today after 3pm. Let me know if you have questions.
