### ISSUE TITLE
Known SLAs related to DevOps alerting

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#46661]
### What is the issue

The Platform Infrastructure team is changing the threshold at which some alerts are triggered. We are wondering if there are any Service-Level Agreements that talk about those thresholds.

More info:
Currently, when an app (like vets-website or vets-api) serves > 5% 500 errors, we have it set up to send a page (via PagerDuty). We are proposing sending a page at anything > 10% and sending a warning message at the > 5% level (the warning message gets sent over Slack).

### Who is it effecting or who will be effected

The changes are made in pull request https://github.com/department-of-veterans-affairs/devops/pull/11884 but we need to know if there are any SLAs before we merge.

### What have you done to resolve this so far

I asked Eric Boehs and Jesse House if they knew of any SLAs this would violate. [Link to Slack convo w/ Eric](https://dsva.slack.com/archives/CJYRZK2HH/p1662139615600439?thread_ts=1662056181.931159&cid=CJYRZK2HH). Neither of them did and suggested reaching out to OCTODE.

### Dependencies

A PO who has a list of SLAs or knows how to find out if we would be violating any by changing thresholds. 

### What's at risk

* If we merge without confirmation of SLAs and we _have_ broken an agreement, the consequence is whatever happens when an SLA is violated 😳 
* If we don't merge and there is no decision from the POs, this alert will continue to page on-call engineers during the day and night. 

### Recommendation(s)

Is there some kind of searchable list of SLAs we can get access to?

### Additional Information

Error rate of application: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45683

We might also be modifying the alert for site latency (https://github.com/department-of-veterans-affairs/va.gov-team/issues/43859)

**Comment by little-oddball** [comment]
I reached out to @mchelen-gov  and @td-usds , @mchelen-gov  communicated he was not aware of any SLAs.

**Comment by mchelen-gov** [comment]
Can you clarify what is being measured here, are the 500 server error responses being served by `vets-api` or revproxy or what?

By definition `vets-website` cannot return 500 server errors.

**Comment by little-oddball** [comment]
Thomas reached out and said he had none. So it's a matter of clarifying the question @mchelen-gov has and we should be good.

**Comment by little-oddball** [comment]
Removing escalation flag and assignees. Reassigning to @rmtolmach

**Comment by rmtolmach** [comment]
@little-oddball Thanks for your help getting this looked at by the right people! 👀 

@mchelen-gov They're coming from revproxy. We measure the status codes returned from revproxy broken down by application. Here's a [graph in prometheus](http://prometheus-prod.vfs.va.gov:9090/prometheus/graph?g0.range_input=2d&g0.expr=sum(rate(nginx_http_request_duration_seconds_count%7Bjob%3D%22revproxy%22%2C%20status%3D~%225..%22%2C%20app!~%22ewis-apps%7Cewis%7Cservices%7Coauth-proxy%22%7D%5B1m%5D))%20by%20(app)%20%2F%20sum(rate(nginx_http_request_duration_seconds_count%7Bjob%3D%22revproxy%22%7D%5B1m%5D))%20by%20(app)%20*%20100&g0.tab=0) showing the metric.
