### ISSUE TITLE
Pre-usability: IA Feedback for Fake Issue

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4666]

**Comment by mnorthuis** [comment]
Things I will be looking at pre-usability

- gain an understanding of full scope and user flow
- findability/navigational considerations for the usability test
- general accuracy in representation of URLs, breadcrumbs, navigational components 
- identify any additional considerations prior to moving into development

**Comment by meganhkelley** [comment]
Test
