### ISSUE TITLE
Consolidate questions and concepts from map planning

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#46687]
## Issue Description
Utilize discussions and synthesis to specify questions the map can answer, scenarios, use cases, JTBD, etc

Mural [here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1662520899531/f689e9b30e36c43e40b04bdee26ef55f25b45635?sender=u4f7db1750f2355f805e60296)

[NN/g on scenarios](https://www.nngroup.com/articles/scenario-mapping-personas/)

## JTBD stories
When I need to understand what product/services are critical, I want to be able to easily locate them, so that I can quickly gather the info.

When I need to know something about a service, I want to be able to easily find it on the map, so that I can quickly learn about the details I'm interested in.

When I want to know what teams do what across the Platform, I want to be able to easily locate a team, so that I can look through their offerings.

When I want to browse the offerings of the Platform, I want to be able to navigate them easily via a visual medium, so that I can look around without having to know which team to go to first, such as in Confluence.

When I want to look at a specific journey or experience, I want to know where that exists within the context of Platform services and teams, so that I better understand the tie-ins and relationships.

## Personas
PM/Lead/Delivery
Needs: Seeing direct and downstream users of product, seeing creators of products their team uses

Leadership
Needs: Seeing organization, potential gaps or redundancies, ownerships

"Makers" (Designers/Developers)
Needs: Seeing Seeing direct and downstream users of product, seeing creators of products their team uses

## Above leads to scenarios:
(For example: "We need to add X to Offboarding -- where is that, again?")

[Concepts ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1662051199435/0ccbdef4e1eeb8f0daa7d7ec9607225aa4c064f9?sender=u4397b715dc3690a417b71483)

## Tasks
- [x] assemble questions/scenarios to address via the map

## Acceptance Criteria
- [x] questions/scenarios are framed out

**Comment by twoangstroms** [comment]
Added these scenarios: 

Scenario 1 (Delivery):

Pam PM is working on quarterly/initiative/project planning. She needs to be able to decide what to prioritize to best improve the team's product for its customers. She would like to be able to find what customers use the product (even downstream),  what these teams are working on themselves, and the makeup of the customer teams. Using the Environment Map, she can trace the effects and use of her team's product, learn what other things these customer teams need in their work, and contact teams to learn how to improve her team's product.

Scenario 2 (Leadership):

Otto Octode has to keep track of overall efficiencies and gaps. He needs to be able to see where communication, process, and other gaps are affecting the efficiency of delivering for stakeholders. With the Environment Map, he can trace how information needs to pass between teams and products, where team goals aren't aligning in the journey of a product, and other issues. 

Scenario 3 (Maker):

Dana Designer is working on their team's product and isn't sure how best to think about or design for user needs. They need to make decisions about interactions, what the product will input, and what it will produce. They look at the Environment Map to learn more about the teams who will be the users, what else these teams take in as input, what her customer teams need to produce. They can also use the Environment Map to see who in the customer teams will be direct users, and recruit for learning processes.

Scenario 4 (All/Leadership):

Aurelia is new and needs to get oriented within the complex, matrixed spaces that will define the working relationships she and her team will have. Using the Environment Map, she can trace the journey of products and users, see what teams produce which products, the relationships between teams and BUs, and see tie-ins and relationships, so she can feel more confident in delivering good product advancement.

Scenario 4 (Leadership):

Bella Boss wants an overview of the impact of teams and products across the BU/company/etc. She can go to the Environment Map and see what products and services have a wide reach and which are targeted. With that information, she can define the scope of further analysis.

Scenario 5 (Delivery/Maker):

Pradeesh PO has a team or project that could move forward better by incorporating or using a new tool or service. Pradeesh can browse or search the Environment Map for terms or products related to his team's need.

**Comment by twoangstroms** [comment]
Questions for the above:

-- Are any redundant or overlapping or copying?
-- Are any too broad/narrow in scope?
-- Did I miss incorporating any of our findings?
-- Are these clear?
-- Are these actionable?

**Comment by steel36** [comment]
These make for an interesting approach.
