### ISSUE TITLE
[RESEARCH] Gather analytics for "check-in attempted too early"

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#46697]
## Background

When meeting with Shawn Adams, @stephenBarrs and @batemapf just now, we agreed to dig into what percentage of Veterans attempt check-in too early, and whether they eventually succeed in checking in.

## Tasks

For the past month, get daily numbers for:

- Number of unique patients who attempted to check in too early for an appointment
- Min, average and max minutes check-in was attempted before the appointment
- Number of those patients who eventually succeeded in getting a link

## Acceptance Criteria

- Results have been shared in the #check-in-experience Slack channel with Shawn tagged

**Comment by acrollet** [comment]
@loripusey I agreed with @stephenBarrs to take this on as part of go-live support this week

**Comment by batemapf** [comment]
i pulled a huge amount of data (>1M lines) off the reporting API this evening. the good news: nothing broke. 

the bad news: "too early" or "too late" is not among the reasons for an aborted e-check-in. so we either need to make a code change to capture this better in the CHIP/CW DB (or if it is already there, make sure it is getting written out via the reporting API), or fall back to log analysis in datadog.

reasons for aborted e-check-in (for reference) that are generated by the reporting API:
DEMOGRAPHICS_UPDATE_NEEDED 
INSURANCE_REQUIRED  
URL_SHORTENER_ERROR  
VISTA_ERROR  CW_ERROR  
Request failed with status code 500  
Request failed with status code 403

**Comment by batemapf** [comment]
maybe the best thing to do here is to write a few DD metrics into CHIP along the lines of "too early <5m", "too early 5-10m", "too early >10m" or something like that. maybe not ideal for the long term, but could give us some clean data pretty quick without a lot of log parsing.

**Comment by loripusey** [comment]
I'll bring this up in Sprint planning today and see if we can take this on this Sprint @batemapf

**Comment by batemapf** [comment]
cc @shawn-adams

**Comment by batemapf** [comment]
another idea: @acrollet if you are able to get appointmentSID / IEN (or other unique identifier) + timestamp out of logs where patient is too early, i can run that against CDW for appointment times.

**Comment by shawn-adams** [comment]
Will need to be careful about dealing with the timestamp given in DD when comparing it to check-in time.  If DD's timestamps are localized to the machine being used to query (like @acrollet mentioned on the call), we'll need to adjust those times to the site's local time.  I have a table built to indicate what the timezone offset is that could be used but we'd need the sta6n included in the datasets.

**Comment by shawn-adams** [comment]
I mean when comparing to appt time.

**Comment by acrollet** [comment]
I've wrapped up my effort on this and communicated out on the slack thread. Code and brief docs are here: https://gist.github.com/acrollet/b80a369707a346d3e279f3a9902bb283

@batemapf @shawn-adams let me know if further analysis is required to make the business case. :-)
