### ISSUE TITLE
token exchange errors SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46696]
Thread for status: https://dsva.slack.com/archives/C019S3NSSAD/p1662481720269389

Should be in sign in service tech debt epic, epics not loading

**Comment by alyssagallion** [comment]
Being resolved in this ticket:

https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/vets-api/10951
