### ISSUE TITLE
Make sure that veterans with active PACT don't schedule Primary Care in CC flow

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4669]
Veterans who have an active PACT assignment in a particular system should not be allowed to schedule a Primary Care CC appointment through VAOS. They should coordinate care through their VA primary care doctor, since that is going to be the doctor who has the most context about this issues.

AC
- [ ] Veterans who have an active PACT assignment in the system they choose  ('choose closest city & state) cannot continue with the CC flow
- [ ] Veterans who cannot continue with CC flow have an easy path to getting into the VA flow

**Comment by markgreenburg** [comment]
@rtwell can you please add some mocks to how this will work? I think we need to account for:
- Veteran only has one CC-supported system they're registered to
- Veteran has multiple CC-supported systems they're registered to

@jbalboni for input on whether this would work: Ryan's initial inclination is that if a veteran chooses a 'closest city and state' that corresponds to a system where the veteran has an active PACT, they get a validation error on 'continue' and have to either choose a different system or follow a link to the request flow (note: where in the request flow?). Not sure how this plan would be different for veterans who are only registered to one (or only one CC-supported) system.

**Comment by peggygannon** [comment]
@markgreenburg @rtwell Hi, guys. my recommendation for this validation error message is here: 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4644

**Comment by markgreenburg** [comment]
Moving this to icebox because there are rumblings about the data used for PACT assignments not being accurate.

**Comment by lenaecb** [comment]
Adding comment for awareness as this issue is out of VAOS-R redesign scope of influence. 

Ask Judy & Lauren to elaborate on the PACT data issues in PCMM and next steps

**Comment by laurenernest** [comment]
@lenaecb Do you have a link to a Slack thread in the LH instance related to this convo that you can drop here?

**Comment by laurenernest** [comment]
To be handled by Lighthouse team in CCE API

Related Slack [thread](https://lighthouseva.slack.com/archives/CJ162GDDJ/p1612575703031700)

Dev ticket https://vajira.max.gov/browse/API-2109

**Comment by laurenernest** [comment]
Lighthouse has completed PACT changes in the CCE API.
