### ISSUE TITLE
Sentry Error Fix - Facility Locator - Location Hour Malformed

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#467]
## User Story
As a developer on the VSP, I need this sentry error to be accurate and useful so I can troubleshoot real issues in a timely manner.

## Goal
Sentry is throwing an error, originating from the Facility Locator application, that stats "API location hours data is malformed".  The error is not that the actual data is malformed, it is that the app needs to accept a value of "Closed" in the time range.  Allowing the "Closed" value to be accepted, it will greatly reduce the number of this errors sentry is reporting from the Facility Locator Application.

## Acceptance Criteria
- [ ] The facility locator location hours accepts Closed as a "valid" time range

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
The PR this issue is connected to went out and solved that particular problem, but we're still getting a lot of malformed hours. I wrote [another ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/504) to address the remaining validation errors. ( :crossed_fingers: )
