### ISSUE TITLE
Adding Wanda Jordan to DSVA Slack

### ISSUE THREAD

**Issue by wanda-jordan** [department-of-veterans-affairs/va.gov-team#46702]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<Full Member>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add Wanda Jordan  as a full member., Test Lead
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by eunicegar** [comment]
not on dsva slack

**Comment by wanda-jordan** [comment]
Correction, the intent was to add myself (Wanda Jordan) as a User  (remove eunicegar and LEHigley )

**Comment by wanda-jordan** [comment]
Correction, the intent was to add myself (Wanda Jordan) as a User (remove eunicegar and LEHigley )

**Comment by wanda-jordan** [comment]
Eunice,
I apologize, your name was added in error.

From: Eunice García ***@***.***>
Sent: Wednesday, September 7, 2022 10:31 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Jordan, Wanda (governmentcio Llc) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding Wanda Jordan to DSVA Slack (Issue #46702)


not on dsva slack

-

**Comment by wanda-jordan** [comment]
> not on dsva slack

can you tell me if the issue has been resolved? were you added to Slack and is there something I need to do on my side

> not on dsva slack
Eunice García can you tell me if the issue has been resolved? Was my Slack request processed.?


> not on dsva slack

 Eunice García

**Comment by wanda-jordan** [comment]
Please add wanda.jordan@va.gov as a full slack member. I am the VRE PSES Test Manager, I need the tool to support testing.

**Comment by eunicegar** [comment]
added
