### ISSUE TITLE
Combined FSR redirects and content updates from Benefits Team 2

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#46708]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

After discussion with Danielle, we agree we will set up redirect for the copay page at the point we go live 100% (estimated September 27-29th). At that time we will also update content pages. 

Future discussion is needed regarding the IA changes and Wizard updates. Danielle and Mikki will connect and then we will meet as a group to discuss future changes needed. 
_Thanks for a great collaboration!_ 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*

*Phased Roll out Plan:*
September 12 - 10% 
September 19 - 30%
September 26 - 75%
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Combined FSR Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/product_outline.md) 
- Link to or attach user flows:
- Link to prototype or mockups: [UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/sitemap?mode=i)
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: September 12, 2022
- Estimated staging review date: N/A
- Content and IA work needed by:  September 12, 2022

## Do you plan to bring this to an upcoming content office hours session?
- [] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name:  Benefits Team 2
-	OCTO-DE product owner:  Matt Self
-	Product manager:  Denise Coveyduc
-	Designer: Megan Gayle + Brie Pipitone
-	FE engineer:  Andrew Rodiek + Brandyn Sullins
-	Product/team Slack channel: #benefits-team-2

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
Pretty sure we can close this ticket but want to confirm with you @denisecoveyduc

**Comment by denisecoveyduc** [comment]
Thanks for checking @RLHecht . Yep we are good to close this one now ;)
