### ISSUE TITLE
Contact Center Review for [Benefits Team 1- Certificate of Eligibility]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#46707]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The VA Form 26-1880 is used to apply for a VA home loan Certificate of Eligibility (COE). Veterans and their loved ones need to bring the COE to their lender to prove that they qualify for a VA home loan. 

### Launch Date
[Certificate of Eligibility Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/Test%20and%20Launch/Release%20Plan.md)

### Version Number
Version 1

### Product Guide
[COE product guide](https://docs.google.com/document/d/1HbZqj24HFoutm5KikfbjcFOMA34vI3lfCcraq4UedD4/edit)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by saderagsdale** [comment]
@jwoodman5 Hi Jason! Can you help me get this request to the appropriate folx?

**Comment by jwoodman5** [comment]
@saderagsdale Sure thing. These are supposed to get auto-assigned to @starlow00, but it seems Zenhub is having issues because this has happened with other, unrelated requests also. We will get this in our sprint.

**Comment by saderagsdale** [comment]
Thank youuuu @jwoodman5

**Comment by starlow00** [comment]
Hi @saderagsdale. I couldn't access the draft in Google Docs, so I sent a permission request.

**Comment by starlow00** [comment]
@saderagsdale, the Google docs draft is ready for your review. I made suggestions, had a couple of questions. When it's ready to go, please let me know and I'll forward to VEO for their review. Thanks!

**Comment by starlow00** [comment]
Hi, @saderagsdale. Just checking in to see if you've reviewed the draft I sent you. Thanks!

**Comment by saderagsdale** [comment]
@starlow00 Hey there, thank you! Just returned from OOO and I've reviewed your suggestions. Can you let me know what the next steps are from here?

**Comment by starlow00** [comment]
Thanks, @saderagsdale. Assuming all is good, I will forward a draft to VEO for their approval, which normally is just a formality. You shouldn't need to do anything else. I'll make sure a clean draft in Word format is attached to this ticket.

**Comment by saderagsdale** [comment]
@starlow00 Sounds good! Let me know when I can close this cycle out.

**Comment by starlow00** [comment]
Sending to VEO for review. Will post clean copy afterward.

**Comment by saderagsdale** [comment]
@starlow00 Hey there - checking on the status of this. Has the VEO responded?

**Comment by starlow00** [comment]
No changes from VEO. Copy attached.

[Certificate of Eligibility Product Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9954862/Certificate.of.Eligibility.Product.Guide.docx)
