### ISSUE TITLE
[PM] My VA Redirect: Review/update documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#46712]
## Background
Once My VA redirect is live to all users (after 9/12) we need to review our documentation and update where needed to reflect the new behavior.

## Tasks
- [x] Review product documentation and update as needed to reflect the way in which users navigate to My VA

## Acceptance Criteria
- [x] documentation is updated

**Comment by ericasauv09** [comment]
[Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/launch-materials/my-va-redirect-release-plan.md) to be updated with metrics on 9/19.

**Comment by ericasauv09** [comment]
[Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/README.md) to be updated on 9/19 with metrics.
