### ISSUE TITLE
Vet Centers: Copyedits before sending for final approval

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46710]
## Issue Description
This ticket is to track the final copyedits of Vet Centers before we send them to Tiffany and Jessica for their review. 

Michelle and Randi will add to the list as pages are ready for Megan. 

**District 2**
- [x] Myrtle Beach (requested 9/7)
- [x] St. Petersburg (_email 9/12: Tiffany's asking for a copyedit review before Jessica reviews it. She asked that you email her with any feedback or edits so she can address them with Jessica and the VCD_)
- [x] Jupiter Vet Center (9/22)
- [x] Pensacola
- [x] Daytona Beach
- [x] Knoxville
- [x] Greenville
- [x] Tallahassee 

**District 3**
- [x] South Bend, IN
- [x] Evansville Vet Center (requested 9/14)
- [x] Cleveland Vet Center (requested 9/15) (_fyi the broken link has been reported to the Support team - it's a valid url_)
- [x] Minot

**District 4**

## Acceptance Criteria
- [ ] All pages have been copyedited and sent for final review

**Comment by megzehn** [comment]
Update 9/22: I reviewed all of the VCs in this ticket, plus some others that came through the copyediting phase. Here are where they stand: 

**Edited and sent back for corrections/confirmation:** 

- Jupiter 
- Evansville
- Cleveland
- Rapid City 
- Memphis 
- Bay County (confirming 2 tiny things, but contact is out this week) 


**Edited and sent to Randi for final sign off:**

- Myrtle Beach (Randi asked them to send a photo for their CAP) 
- St. Petersburg (Tiffany has this one) 
- Chicago (Randi sent to Tiffany) 
- South Bend (Randi sent to Tiffany) 
- Gainesville 
- Chattanooga
- Sioux Falls 


**Ready for publishing, except holding for a CAP issue**

- Ocala 
- Marietta

**Comment by mmiddaugh** [comment]
Daytona Beach and Greenville, SC are both ready for your copy-editing pass, @megzehn

**Comment by mmiddaugh** [comment]
Knoxville is also ready for copy-editing @megzehn

**Comment by mmiddaugh** [comment]
@megzehn Madison Vet Center is ready for copy editing.  I've reported their broken link to the support team, fyi.

**Comment by mmiddaugh** [comment]
@megzehn Lawrenceville Vet Center is ready for copy editing

**Comment by mmiddaugh** [comment]
@megzehn Fort Lauderdale is ready for copy-editing

**Comment by megzehn** [comment]
10/6 update: 

**Copy edited and published:** 
Lawrenceville, Madison, Greenville, and Pensacola

**Copy edited and with Tiffany:** 
Daytona Beach 

**Back with VC for more edit requests:** 
Fort Lauderdale 

**To be copy edited:** 
Minot

**Comment by mmiddaugh** [comment]
@megzehn 

- Will you take a peek at Johnson City? They need only a second spotlight so perhaps you could give any other feedback with a gentle reminder on that? (last email was 9/22)
- Likewise, Pompano Beach is spare but ready, aside from a requested revision in Community engagement (last email 9/26)

**Comment by megzehn** [comment]
Hi @RLHecht and @mmiddaugh! Sending a few updates over before I take off for the next week: 

- Cleveland (this one's ready to be published)
- Johnson City (reviewed and sent to Tiffany)
- Wichita (reviewed and sent to Tiffany)
- Minot (reviewed and sent a few pieces of feedback back to the VC) 

I did not finish reviewing Pampano Beach, but I noticed they didn't have any CAPs listed, and their hours posted went to 8 p.m. several nights, so I wasn't sure if you had any insight Michelle. I’m happy to either finish looking at their page when I get back or pass it over to you Randi, if you get some time. 

Thank you both so much for all of your help!!

**Comment by mmiddaugh** [comment]
@megzehn Tallahassee is ready for you - it's spare but clean, I think.

**Comment by mmiddaugh** [comment]
@megzehn Tallahassee is ready for you - it's spare but clean.

**Comment by mmiddaugh** [comment]
@megzehn 
To be copy edited, please

- [ ] Des Moines Vet Center

**Comment by mmiddaugh** [comment]
@megzehn 
To be copy edited, please

- [ ] San Juan Vet Center
- [ ] Columbus, OH Vet Center

**Comment by megzehn** [comment]
- [ ] Saginaw VC (requested an additional review 11/7, MZ will take)

**Comment by RLHecht** [comment]
From Tiffany:
- [ ] Melbourne Vet Center

**Comment by mmiddaugh** [comment]
@megzehn Macomb County is ready for a copy-editing pass.

**Comment by mmiddaugh** [comment]
@megzehn Pontiac is also ready for copy-editing (same editor as Macomb County, fyi)

**Comment by mmiddaugh** [comment]
@megzehn Chicago Heights is also ready for you

**Comment by megzehn** [comment]
Thank you! Confirming that these are all copy edited and submitted for final review. 

- [ ] Chicago Heights
- [ ] Macomb County
- [ ] Pontiac
- [ ] Pasco County
- [ ] Melbourne 

I also sent additional feedback to St. Paul on 11/22.

**Comment by mmiddaugh** [comment]
@megzehn Evanston Vet Center is ready for copy-editing but I let him know that he needs to replace the outdated Veterans Day Brunch spotlight before he can be published.

**Comment by mmiddaugh** [comment]
@megzehn Stark County is ready for copy-editing
2 CAP photos and confirmation of hours are pending

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Lincoln Vet Center is ready for copy-editing with one CAP photo pending

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Fort Wayne Vet Center is ready for copy-editing

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Clearwater Vet Center is ready for copy-editing. 
(Hours are correct and they do not have CAPs)

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Traverse City is ready for your copy-editing. 
(No CAPs)

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Sioux City Vet Center is ready for your copy-editing, pending CAP confirmation

**Comment by mmiddaugh** [comment]
- [ ] Grand Rapids Vet Center is ready for copy-editing, per Tiffany
No CAPs or access to Mobile Vet Center

**Comment by mmiddaugh** [comment]
- [ ] Quad Cities is ready for copy-editing. 
No CAPs
The team is looking into the reason Suicide prevention is duplicated as a service on the page, fyi

**Comment by mmiddaugh** [comment]
- [ ] Aurora Vet Center is ready for copywriting.
No CAPs or public transportation to include
@megzehn

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Cedar Rapids Vet Center is ready for copywriting

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Palm Beach Vet Center is ready for copy-editing. 
They do not have CAPs or an MVC to add

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] La Crosse Vet Center is ready for copy-editing.

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Mobile Vet Center is ready for copy-editing. 
CAP images are pending.

**Comment by mmiddaugh** [comment]
@megzehn 
-[ ] Rockford Vet Center is ready for copy-editing
(two small edits requested 12/12 by email)

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Green Bay is ready for copy-editing per Tiffany on 12/12

**Comment by mmiddaugh** [comment]
@megzehn 
- [ ] Duluth Vet Center is ready for copy-editing. 
He will request an update to the hours of operation.

**Comment by RLHecht** [comment]
Closing as we're tracking the last 2 Vet Centers elsewhere.
