### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by cesaresantiago** [department-of-veterans-affairs/va.gov-team#46713]
# Instructions
A change on MEB’s vets-api setup that was intended only for local development had an unintended consequence on the generation of JWT tokens for production. This has resulted on MEB users unable to submit automated education claims through the app since it was deployed yesterday(09/06/2022) on the daily 3pm deploy.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy

Original PR that caused the issue: 
https://github.com/department-of-veterans-affairs/vets-api/pull/10606

Reversal of PR already merged and tested on staging:
https://github.com/department-of-veterans-affairs/vets-api/pull/10633

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
Since last night we estimate 1000 users have been affected.
## Has fix been confirmed in Staging?
- [ X] Yes
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
We want MEB users to be able to resume their automated claim submissions ASAP. The rate of affected users since last night suggests a large number will be affected from now until 3pm, which will result in a slower processing of their claims. MEB team leadership agrees we need this fix ASAP.
   
## Verify The following
 - [X] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [ X] The OOB Deploy Requests is critical and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests
 - [ ] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by raywangoctova** [comment]
approved

**Comment by zachclarity** [comment]
@cesaresantiago  - Would you provide details for me to add to the postmortem ?

**Comment by oseasmoran73** [comment]
No action should be required from Infra team. Removing label/board. Please feel free re-loop us if needed on our end

**Comment by little-oddball** [comment]
Determined STALE issue is > 2 months old.
