### ISSUE TITLE
Document All Error States & Link to Where Can Find in GA

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46728]
## Tasks
- Document All Error States in a GitHub page
- Link each error state to where it can be found in GA

**Comment by brdunfield** [comment]
To Do: Document how to find these in GA.

I will attach my documentation into this ticket for now, as I know the discussion about where it will live is ongoing. Once that is decided someone can move this information there, as I am offboarding.

Documentation of error parameters:

We have added error parameters to the URL of the error page that take the form:
`/error?error=error-param`
These can be viewed in Google Analytics

Error parameter list:

check-in-post-error: There was an error in the postCheckInData api call
pre-check-in-post-error: There was an error in the postPreCheckInData api call

error-completing-check-in: There was an error in either the postCheckInData api call, or in parsing the response from that call
error-completing-pre-check-in: There was an error in either the postPreCheckInData api call or in parsing the response from that call

no-token: No UUID was provided in the URL when accessing the app
bad-token: an ID parameter was provided, but it is not a valid UUID

cant-retrieve-check-in-data: could not get CheckInData for the provided UUID
Error-getting-pre-check-in-data: could not get PreCheckInData for the provided UUID

no-demographics: the veteran’s data has no demographics information
no-emergency-contact: the veteran’s data has no emergency contact information
no-next-of-kin: the veteran’s data has no next of kin information

pre-check-in-expired: The veteran attempted to pre-check-in after pre-check-in has expired (midnight on the day of their appointment)
appointment-cancelled: The veteran attempted to pre-check-in for an appointment that has bene cancelled

session-error: there was an error in the session retrieved by the getSession api call

error-fromlocation-landing: There was an unknown error which originated from the landing page of the day-of application
Error-from location-precheckin-introduction: There was an unknown error which originated from the introduction page of the pre-check-in application

routing-error: there was an error routing between pages using the router

test-error: used in tests only, and should not be seen in the live app
