### ISSUE TITLE
AWS access for Mariah Sager

### ISSUE THREAD

**Issue by mariahsager-tw** [department-of-veterans-affairs/va.gov-team#46729]
### COR Name

Cecilia Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Mariah Sager

### Your Email

mariah.sager@thoughtworks.com

### Team, Role, and Company of the target individual

Digital Health Platform (DHP), Software Developer, Thoughtworks

### Product Manager (PM) name and email

Suzanne Miller, suzanne.miller@thoughtworks.com

### Product Owner (PO) name and email

Suzanne Miller, suzanne.miller@thoughtworks.com

### Desired AWS Access

Copy permissions from @yonidoronpeters 

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
## For AWS Access

User: Mariah Sager
COR: Cecila Lee
VOR: Michael G. Lovejoy
Approval required: @department-of-veterans-affairs/operations-aws-approvers
Admin level: no

Approvers will check with your VOR on your EQIP status.

**Comment by td-usds** [comment]
Reached out to VOR

@oseasmoran73 can you ping me in parallel (slack, not GH) to illuminate me on which permissions are currently effective for `@yonidoronpeters`? I want to understand the requested scope being requested.

**Comment by td-usds** [comment]
VOR confirmed eQIP, first need to understand what the requested permissions are before approving the request

**Comment by mariahsager-tw** [comment]
Hello @td-usds @oseasmoran73, is there anything I can do to help resolve this ticket?

**Comment by oseasmoran73** [comment]
Hi @mariahsager-tw 

Thanks for the reminder! This slipped through the cracks. I have reached out to @td-usds with the information asked. Waiting for approval

**Comment by td-usds** [comment]
Requested access approved

**Comment by oseasmoran73** [comment]
Reached out to @mariahsager-tw via slack & provided instructions on how to login. Closing ticket
