### ISSUE TITLE
Document issues with review instances and sign in service

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46735]
we dont yet know why the sign in service doesnt work on review instances, this ticket will serve as the initial investigation and documentation of the issues around SIS and RI.

**Comment by joeniquette** [comment]
Ian to initially look at this then handoff back to backend

**Comment by ianhundere** [comment]
reviewed:
- https://depo-platform-documentation.scrollhelp.site/developer-docs/review-instances
- https://depo-platform-documentation.scrollhelp.site/developer-docs/using-review-instances-to-preview-changes

**Comment by joeniquette** [comment]
This is with QA standards. Once the appropriate changes are made then we can re-engage on the issues (lack https).
