### ISSUE TITLE
Feature state not persisting

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#46741]
[Cesar Santiago reported](https://dsva.slack.com/archives/CBU0KDSB1/p1662571586763109) some feature toggles were disabling themselves at random on [staging](https://staging-api.va.gov/flipper/features). He specifically was interested in the `show_meb_unverified_user_alert` feature.

- [x] Investigate the cause of `show_meb_unverified_user_alert` being disabled.
- [ ] Resolve the cause or create an issue to address resolution.

**Comment by ericboehs** [comment]
- I inspected the staging database and I noted that the last `feature_toggle_event` entry in the table was enabling the feature.
- Checking the `flipper_features` table, I noticed multiple features (including `show_meb_unverified_user_alert` being created recently and with the same time stamp).
- After searching documentation and multiple repos, I found that at boot, Vets API processes will create features found in config/features.yml and delete features not found in config/features.yml.
- With an assist from Oseas, we found old staging instances associated with the secondary ASG. We're certain this is the cause of the issue.

Ian Hundere is working on a solution to refreshing these instances upon a version change.

**Comment by ericboehs** [comment]
Ian issued a manual refresh of the ASGs and merged an automated solution.

I'll monitor the secondary ASG as new deploys go out and close this issue once I've confirmed the automated solution is working as expected.

**Comment by ianhundere** [comment]
further confirmation that the fix is working; refresh was triggered for `dev` / `staging` after `vets-api-server` was deployed.

**Comment by ericboehs** [comment]
[Cesar is still seeing](https://dsva.slack.com/archives/CBU0KDSB1/p1662643815177239?thread_ts=1662571586.763109&cid=CBU0KDSB1) feature flags being removed.

I verified that the `show_meb_unverified_user_alert` flag was re-created this morning at 2022-09-08 13:35:24.71178 UTC.

I'm [removing the code](https://github.com/department-of-veterans-affairs/vets-api/pull/10649) which removes these, opting for a [manual process](https://github.com/department-of-veterans-affairs/vets-api/pull/10650).

**Comment by npeterson54** [comment]
Looks like this can be closed out

**Comment by ericboehs** [comment]
Two additional issues were raised matching this same behavior.

On Tuesday, [Tom Harrison reported](https://dsva.slack.com/archives/CBU0KDSB1/p1666112449634839) some feature flags turning off at random (citing `profile_user_claims`). And yesterday, [Jennie McGibney reported](https://dsva.slack.com/archives/CBU0KDSB1/p1666203818054479) that `va_online_scheduling_clinic_location` was getting removed.

---

After much research, we're pretty certain it was old Vets API code still being run. EKS pods related to the EVSS/BGS secondary ASG split were found with the `Flipper.remove` code. These were only found in staging; dev and prod are not affected. These pods have been terminated which (baring something that recreates them) should resolve the flags being removed.

Special thanks to @LindseySaari, @ianhundere, and @ph-One for helping research this issue.
