### ISSUE TITLE
Can we create a GA event for in person vs. telephone appt

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#46755]
## Description 

I'd like to be able to, at least, identify successful pre check ins for telephone appts. I.e., distinguished from in person appts. Is there an event that we can fire that passes the appt type? I'm forgetting the name of the field that contains this logic. 

Or, should this be handled with url params, something else, etc. 

## Tasks

- [ ] Determine if possible and document how. E.g., event, url param, etc. 
- [ ] Create ticket with next steps

**Comment by brianseek** [comment]
Closing since the work in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/49746 solves this.
