### ISSUE TITLE
Remove Chris Wilmsen and Alex de los Reyes from DSVA Slack

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#46766]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

REMOVE USERS from DSVA Slack, as they have been offboarded from the TEVI contract

Christopher Wilmsen - [cwilmsen@fearless.tech](mailto:cwilmsen@fearless.tech)
Alex de los Reyes[areyes@fearless.tech](mailto:areyes@fearless.tech)

**Comment by eunicegar** [comment]
Done
