### ISSUE TITLE
Analytics Internal - New Dataset Request Template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46777]
# Request a New Dataset

## What this form is for

To streamline the communication between team members about the fields, scope of data, and level of detail needed for new datasets in BigQuery and/or Domo.

For more information about this process, please see the [How to request a new dataset](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215576075/How+to+request+a+new+dataset) page under "QA Processes" in Confluence.

## Instructions for Analytics team member

- [ ] Make a copy of the [Dataset Request Form](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit?usp=sharing)
- [ ] Complete request form as instructed
- [ ] Link your completed spreadsheet here: ______

**Comment by shiragoodman** [comment]
I already started the Dataset Request form - https://docs.google.com/spreadsheets/d/1mOFAs1T4AD4a6sVhyPiKVI9CCfSuzn_CcGuqGhBAfrI/edit#gid=0

**Comment by michelle-dooley** [comment]
@shiragoodman - per our meeting I'm going to close this ticket.
