### ISSUE TITLE
DDL: Create designs for any error messages

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#46773]
Identify and design error messages for the following: 

- Authenticated Veteran attempts to access URL where there decision letter would be, but they don't have any
- Letters list fails to load

Figure out other error states and design for those. 

Tasks:

- [x] Determine what sort of errors could occur
- [x] Determine which errors need designs
- [x] Design error states

**Comment by sortizsh** [comment]
Discovery and due diligence to proactively seek out the common fail states and messages as needed. Mottie may be a good resource.
