### ISSUE TITLE
QA Feedback - Staging Review - Profile Team | Bad Address Indicator (BAI)

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#46791]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
QA feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/42706

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- The `Review your mailing address` notification still appears after logging out and then logging back in after updating the mailing address.
	- Steps to reproduce:
		- In staging, log in with `vets.gov.user+124@gmail.com` and navigate to the `Profile` page.
		- `Edit` the mailing address and then `Update` the address without making changes.
		- Log out and close the browser window.
		- Log in with the same account and open the `Profile` page.

**Should:**
None

**Consider:**
None

**Comment by SKasimow** [comment]
@ddzz - this is actually a staging condition; we deliberately set this account and a few others to re-populate with a BAI indicator after updating and closing out. This enables us to continue to test through-out the build and QA cycle.  We have tested other staging accounts that were not set to return to a BAI indicator and in those cases, the alerts will not re-appear.

**Comment by ddzz** [comment]
@SKasimow Thanks for clarifying. I did suspect this was issue only in staging, but I couldn't tell for sure. This can be closed.
