### ISSUE TITLE
FE | Profile | [Markup and meta data] HTML markup isn't valid. (09.01.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46800]
#### VFS team name
Profile Team

#### VFS product name
Profile

#### VFS feature name
Bad Address Indicator

#### Point of Contact/Reviewers
Brian DeConinck (@briandeconinck) - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
HTML markup isn't valid.

### Issue Details
For each of the "Review your mailing address" alerts, the H2 heading has an `aria-label` attribute. `aria-labels` should only be added to interactive elements.

### Link, screenshot or steps to recreate
The "Review your mailing address" alerts are currently coded as:

```
<h2 slot="headline" tabindex="0" role="alert" aria-live="polite" aria-label="The address we have on file for you may not be correct.">Review your mailing address</h2>
<p>The mailing address we have on file for you may not be correct.</p>
<p><a href="...">...</a></p>
```

### VA.gov Experience Standard
[Category Number 09, Issue Number 01](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 1.3.1_A

---

### Platform Recommendation
Typically (although not exclusively!), `aria-label` attributes should only be on interactive elements. It provides something for screen readers to announce as an alternative to the visible text when the visible text is ambiguous or confusing for screen reader users.

In this case, I'm not sure what the `aria-label` buys you. It may not be consistently announced by screen readers, and when it is announced it will likely replace the heading text. Since the `aria-label` text is very similar to the body of the alert, you could end up with some repetition.

If the goal is to get the body of the alert announced at the same time as the heading on page load (thanks to `role="alert"` on the heading -- but see the other issue about that), consider using `aria-describedby` instead to associate the body text with the heading. That might look something like:

```
<h2 slot="headline" tabindex="0" role="alert" aria-live="polite" aria-describedby="alert-body">Review your mailing address</h2>
<p id="alert-body">The mailing address we have on file for you may not be correct.</p>
<p><a href="...">...</a></p>
```

(Note that I haven't tested the example code above, so don't trust me too much!)

### VFS Team Tasks to Complete

- [x] Comment on the ticket if there are questions or concerns
- [x] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by adamwhitlock1** [comment]
Fix has been deployed to staging @SKasimow and heading now uses aria-describedby and points to the paragraph copy.

![Screen Shot 2022-09-21 at 9.53.55 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/adb42ec0-c04f-43fb-b6da-8b3f37cbd4ed)

**Comment by SKasimow** [comment]
Thanks @adamwhitlock1
