### ISSUE TITLE
SOCKS access for Adam Foster

### ISSUE THREAD

**Issue by afoster-va** [department-of-veterans-affairs/va.gov-team#46803]
### Your Name

Adam Foster

### Your Email

foster_adam@bah.com

### Your Role and Team

Product Manager- Lighthouse Health APIs

### Product Manager (PM) name and email

Adam Foster foster_adam@bah.com

### Product Owner (PO) name and email

Chintan Patel chintan.patel2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDPqRFBzNcKyZXjSUfObdDEtOHUHoEnI17IKRmX6tGXBxnD67yTWTPVS7uxz2646+M5rEpy/dFWI1wxTUOvyuaUJKteaHvro74l8Bx9a9pXhB8DD7s9IYMLp9Tph0g07o0TQNKoexkR6QPFmicHCcibqFsNPlnLEw+cqOXDd+cLL4Cj+xWqJ7kA3vhQmp/OZNbQ40Zgk3iIUvV5tjcLCziocroU9wpim3nOFsxXG1q8h3u99JTAlnUFIL6Nj0Vfb8wP4ckyXYGW379oWtNGZ+eAThuNgcOEhEgja3nH2izVfq60smJGrnPulBE9FzvM8t8B2T4t0eRNAXWM9Sz35vBr7f2k+Kl0MDyXAdseTEKjgrZC1KLWb/GqJsjm0tRQn81MQjq6cyHzsqaYRsycDaDys6izFZq+5S1NJTw2vA4RVpx0eepba70Wq8giHHUIQm2NYsrEYS0zzDludK6lRqd4MwFl0hPm0uNKd/pM0044/jxA3DA8rR+/FlreLj5z/8= bahfoster1@BAH5CG1387GNN

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
I see the PR has been merged. Closing ticket. Please feel free to reopen or submit new one should you run into issues
