### ISSUE TITLE
Design | Profile | [Components and pattern standards] Design components or patterns don't align with Design System guidelines. (04.07.2)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46801]
#### VFS team name
Profile Team

#### VFS product name
Profile

#### VFS feature name
Bad Address Indicator

#### Point of Contact/Reviewers
Allison Christman (@allison0034) - Design
Jim Ryan (@jimuhh) - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
There are multiple alerts on the page for the same issue.

Redundant notifications on address page.

### Link, screenshot or steps to recreate

![two-notifications](https://user-images.githubusercontent.com/89798550/189189198-6bb977b0-2bf4-4a86-a35a-d986e7d6d067.png)

### VA.gov Experience Standard
[Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

---

### Platform Recommendation
We have noticed the value of alerts is being diminished on VA.gov and we believe this is due to alert fatigue. (Added the 508-defect-3 label here, as it relates to cognitive load as well. -- @briandeconinck)

Possible solution 1: Have the link (Go to your contact information to review your address) on the first personal information page alert go directly to the bookmark contact-information#mailing-address. Remove the alert at the top of the contact information page. Change the background only alert inside the addresses section to an expandable alert.

Possible solution 2: Remove the background only alert inside the address section. Use an additional info component (no alert styling). It is also against our guidance to use the additional info component inside an alert.

### VFS Team Tasks to Complete

- [x] Comment on the ticket if there are questions or concerns
- [x] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by SKasimow** [comment]
Hi @shiragoodman - should this ticket and #46802 have accessibility labels and defect levels? We're working on them of course but asking bc I'm compiling an epic with all outstanding accessibility tickets and wasn't sure if these were meant to fall under accessibility issues?

**Comment by shiragoodman** [comment]
@SKasimow Yes. If you look under the Platform Recommendation section, @briandeconinck added a comment stating that the various alerts is a cognitive load issue, which is why the defect label and accessibility label have been added. 

In short, any issue we flag that has `508-defect-0`, `508-defect-1`, `508-defect-2`, `508-defect-3` or `508-defect-4` is an accessibility issue and needs to be reported to the VA 508 Office if not addressed before launch.

**Comment by SKasimow** [comment]
+ @cgednalske

**Comment by SKasimow** [comment]
Completed....
