### ISSUE TITLE
Design | Profile | [Components and pattern standards] Design components or patterns don't align with Design System guidelines. (04.07.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46802]
#### VFS team name
Profile Team

#### VFS product name
Profile

#### VFS feature name
Bad Address Indicator

#### Point of Contact/Reviewers
Allison Christman (@allison0034) - Design
Jim Ryan (@jimuhh) - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
You are using the on this page component with only one H2.

Down-arrow used in place of expected link.

### Link, screenshot or steps to recreate
<img width="905" alt="image" src="https://user-images.githubusercontent.com/71330581/189189066-241ee549-3728-4b8f-babf-20a1ce4aa7de.png">

### VA.gov Experience Standard
[Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

---

### Platform Recommendation
Remove the arrow and use a default link or active link styles.

### VFS Team Tasks to Complete

- [x] Comment on the ticket if there are questions or concerns
- [x] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by SKasimow** [comment]
Completed...
