### ISSUE TITLE
Enhance VAOSLogging class with additional error body details

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#46806]
We've identified a potential enhancement to vets-api that would allow the VAOSLogging class to expose additional details of the response body in an error scenario. This would improve our health/monitoring efforts by being able to see more information related to an error response.

AC:
[ ] - VAOSLogging class includes new method to expose response body in an error case

**Comment by ldelacosta** [comment]
The team created a duplicate ticket for the work. The PR for the issue: https://github.com/department-of-veterans-affairs/vets-api/pull/10666#pullrequestreview-1105976776

Closing out the ticket since no new work is needed.
