### ISSUE TITLE
[FE] | [DISCOVERY] | 10-10EZ | Dependents flow for unauthenticated users

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#46815]
## Description

For the redesigned 10-10EZ household information section, we need to know whether the proposed design pattern is feasible for unauthenticated users (who can't have information saved except via cookies).

**The pattern** 

When a user has a yes response to the dependents yes/no question, they proceed to answer dependent questions on the following pages:
- If the user has no additional dependents, they continue to the next question
- If the user has additional dependents, they are taken to the same question pages, incremented for each dependent
- The user should be able to cancel the process of adding an additional dependent, taking them to the additional dependents yes/no question

Here's the proposed pattern:
![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/bbde7aab-dac3-45e2-bcb6-31d7fd08e8b4)

## Tasks

- [ ] Determine if this pattern can be applied to unauthenticated users
- [ ] Determine if this pattern can be applied to authenticated users (I assume so - Nick)

**Comment by longmd** [comment]
@nicko-amida , there is no issue with this pattern for either authentication status. You're good to go with this!

**Comment by nicko-amida** [comment]
@longmd Alright thanks!
