### ISSUE TITLE
Update content in smartphone check-in R&S article to align with new identity verification method

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46817]
## Issue Description
We previously updated content on the [How to check in with your smart phone for some VA appointments](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) R&S page to show 2 options for identity verification while the product team was slowly rolling out this change. This work was completed in ticket #44692.

Once the verification method of using your last name and date of birth will be visible to 100% of users, we need to update the language in this article to reflect the change. 

## Tasks
- [x] Update content (Katherine)
- [x] Copyedit (Megan)
- [x] Publish

## Acceptance Criteria
- [x] Article shows only the DOB and last name option as a verification method on the live site

**Comment by benbrasso-agile6** [comment]
@RLHecht we are re-pushing this update to 10% of Veterans starting on 9/20.

**Comment by benbrasso-agile6** [comment]
Continuing 10% for 9/22

**Comment by benbrasso-agile6** [comment]
@RLHecht moving up to 20% of Veterans for today

**Comment by benbrasso-agile6** [comment]
@RLHecht increasing to 30% of Veterans

**Comment by benbrasso-agile6** [comment]
@RLHecht moving up to 50% of Veterans today

**Comment by RLHecht** [comment]
Thanks @benbrasso-agile6 Do you have a date set for when you think you'll be at 100%? That's when we would want to change the content to reflect only one verification method.

**Comment by benbrasso-agile6** [comment]
Yes

<img width="123" alt="Screen Shot 2022-10-17 at 9 57 20 AM" src="https://user-images.githubusercontent.com/101129355/196196513-183a5d88-3211-4264-b6a2-2c8dab5166de.png">

**Comment by RLHecht** [comment]
@katherine-fung Could you make these changes this week so that we can publish on Thursday? Thanks!

**Comment by katherine-fung** [comment]
Hi @RLHecht - I updated the verification instructions on this page to match the upcoming changes in the check-in process. 

The page now says: "We’ll ask you to provide your last name and your date of birth" in 2 places.  

[I've left a note in the revision log that this change is scheduled to go into effect Thursday, 11/20]

**Comment by benbrasso-agile6** [comment]
@RLHecht increasing to 70% today

**Comment by benbrasso-agile6** [comment]
@RLHecht we decided that we have reached the point of diminishing returns. We have moved this to 100% of Veterans.

**Comment by RLHecht** [comment]
Thanks @benbrasso-agile6 I just published the update to the R&S page to reflect that it's now only the last name and date of birth for verification. Will close once I validate it on the site.

**Comment by RLHecht** [comment]
This is live. Closing.
