### ISSUE TITLE
Supplemental Claims plain language content review

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#46818]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [s] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
October/November
  
*Please provide an estimated date so our team can create other relevant tickets.*
October/November
  
## Supporting artifacts
*Please provide supporting artifacts as available.*
- We intend to test [this prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676) for usability, so it is the most up to date view of the intended flow. 
- This is the [source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md) that represents the entire Supplemental Claims conversation. We do not have all the error states in place yet, as this form will pick up the errors from other claims and appeals forms. 
- [Supplemental Claims Content Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44414)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Testing 9/19, hope to have content review by 10/1
- Estimated staging review date: TBD
- Content and IA work needed by: 10/1

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: @saderagsdale Sade Ragsdale
-	Designer: @thehastingsp Pamela Hastings
-	FE engineer: @Mottie Robin Garrison
-	Product/team Slack channel: Benefits-team-1

**Comment by bethpottsVADEPO** [comment]
@thehastingsp Let's start tackling these screens in my office hours. We can have working sessions each week where you make plain language edits to the file in real time on the call. This will be faster for both of us than putting specific edits in a ticket. What do you think?

**Comment by thehastingsp** [comment]
@bethpottsVADEPO I like it - I was wondering how we could streamline. I'll come next week

**Comment by thehastingsp** [comment]
Closing this issue as we've broken it out into tickets and will be tackling one at a time in the [source of truth here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md).
