### ISSUE TITLE
Establish Research Plan Intent for Modify Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4682]
## Goal
Gain user validation on current working design theories

## Considerations
- Seek 8 discussions on the above
- Front load with personalization items
- Try and get accurate demographics from Perigean
- Need a more gelled workflow established

## Tasks
- Frame questions that will be presented to 8 Veterans

## Acceptance Criteria
 - [ ] An initial plan intent has been established 

## Next Steps
- Conversation guide before scheduling with Perigean

**Comment by sporeboy** [comment]
Initial commit of Research Plan outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-form-gating-research-plan.md
