### ISSUE TITLE
Qualitative Data Request for the VA.gov profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#46843]
### Survey Type Requested

User Surveys

### Date Range Start

06-01-2022

### Date Range End

09-09-2022

### Product Name(s)

VA.gov Profile

### Product Description

I would like to review the Medallia data for **all pages** of the VA.gov profile. 

### Product URL(s)

The VA.gov Profile includes the following URLs:

- https://www.va.gov/profile/personal-information
- https://www.va.gov/profile/contact-information
- https://www.va.gov/profile/military-information
- https://www.va.gov/profile/direct-deposit
- https://www.va.gov/profile/notifications
- https://www.va.gov/profile/account-security
- https://www.va.gov/profile/connected-applications

### VA Email Address(es)

samara.strauss@va.gov

**Comment by Samara-Strauss** [comment]
@jwoodman5 @ianMcCullough-ob this form is great!! One question I had as I was filling it out was what was the difference between the survey types (ie. Support or User Surveys). Ian explained through Slack, but that was not clear to me by reading the form. Otherwise, this was straightforward and really easy to use.

**Comment by ianMcCullough-ob** [comment]
@Samara-Strauss just shared the data with you, message me on Slack if you have any questions. Thanks!
