### ISSUE TITLE
AWS access for Mark Komosa

### ISSUE THREAD

**Issue by markkvba** [department-of-veterans-affairs/va.gov-team#46853]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

GovernmentCIO - Lee Blanchard

### Your Name

Mark Komosa

### Your Email

Mark.Komosa@va.gov

### Team, Role, and Company of the target individual

Dev Lead VFEP (Education), GovCIO 

### Product Manager (PM) name and email

Darla van Nieukerk IT Project Manager, BAM

### Product Owner (PO) name and email

Michael Napper , Education Chief

### Desired AWS Access

 I need access ssh access to EC2 dev, staging, prod (3months) EC2 instances to execute the EDU GIDS Institution Builder and Geocoder process :

We run the geocoder script. To do so, you will need to find the instance id of staging-gids or prod-gids in the EC2 Instance search that will show a list of instances, select an instance and ssh.
•	Once sshed into instance run “sudo su - -c 'docker exec -it gi-bill-data-service bash'” to bash into the container, “source config/.env.sh” to set the config enviornments. “nohup rake fix_coord_mismatch & exit” tpo start the geocoding task and sudo su - -c 'docker exec -it gi-bill-data-service tail -f nohup.out' to monitor.

### Access Expiration

DEV & STAGE 6/1/2027

### Additional Notes

COR :  Riccio, Joseph [Joseph.Riccio@va.gov]

### User must exist in a roster before AWS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
Hi @markkvba !

Can you please update the ticket with the CORs name? This information is required before AWS approver group can review

**Comment by markkvba** [comment]
COR's name is in the Additional Notes field.

**Comment by markkvba** [comment]
ETA please?

**Comment by td-usds** [comment]
Reached out to VOR

The request for Staging is fine with me, it's staging after all but...
I have concerns about the requested level of access: it requests access to prod for too long a time and performs administrative operations (`sudo`) on instances in that environment. This is a serious risk.

Can you elaborate why this requires a human?

I would like to - at the very least - have a discussion as to what can be done to either limit the scope of the request _and_ what the plan of action is to remove the need for a human in this loop that spawned this request.

**Comment by markkvba** [comment]
We are new team taking over an existing process which is verbatim posted above it's run manually as of now. Plan is to visit, improve/automate and or eliminate the manual process.  Maybe a compromise would be for the our team to gain access to prod for a 1  year to evaluate and change this situation?

**Comment by td-usds** [comment]
See also https://github.com/department-of-veterans-affairs/va.gov-team/issues/47401#issuecomment-1255348736 as this pertains to the same thing.

**Comment by markkvba** [comment]
Can we agree on this 3 month PROD doable. We have identified code change to cut down processing time and expect to be eliminating the manual execution step.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by markkvba** [comment]
We'll be working this issue created by prior team to along to eliminiate the need for PROD access: [Here's the prior teams issue ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37944)

**Comment by markkvba** [comment]
VFEP-1 #comment This better make to Jira for us

**Comment by td-usds** [comment]
I am still awaiting the response from the VOR, once I have their response to my data call, then I can move this forward with an approval for 2 months based on our conversation

**Comment by td-usds** [comment]
Note that two of your team mates have received approval (see linked item)

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by markkvba** [comment]
Removed the request for PROD access from this issue..

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
VOR provided background information, awaiting more information from VOR

**Comment by td-usds** [comment]
Pinged VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by BillChapmanUSDS** [comment]
I'm taking this thread over from Thomas. As it is looking like the request is getting stale. I want to understand if this access is still needed since we are already beyond the original temporary request period.

**Comment by markkvba** [comment]
Bill we can close this issue.
