### ISSUE TITLE
Scope where we should start with regression test plans

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4686]
As a QA person, I want to create regression test plans that will give the most value first so that I can get the biggest bang for my buck. 

AC: 
- [x] figure out what areas have the most bugs logged to them
- [x] create spreadsheet of highest buggy features

**Comment by pjhill** [comment]
Exported va.gov-team issues with label "bug" to a spreadsheet and started doing some analysis here --
https://docs.google.com/spreadsheets/d/1Lo7AYuI32en6MN6Mm4L-X3v0xDd9p2DRTh0dLNwQmzw/edit?usp=sharing
