### ISSUE TITLE
Analytics edge case KPI dashboard request for the VA.gov profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#46861]
# Request an Edge Case KPI Dashboard

## What this form is for

Use this ticket template to request a new edge case KPI dashboard on Domo for your product. Edge case dashboards are for products that fall outside of the scope of our standardized KPI dashboards (Forms, Content, and Search).

If you are unsure what type of dashboard your product qualifies for, please check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739) on Domo.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. Please note that these dashboards will require additional data and design discovery and will take additional time to deliver. You can also reach out for updates on this ticket.

## Instructions for the VFS team

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. For edge cases, we also ask for product outlines or other resources that will help us understand success for your product and define metrics: 

- [x] Make a copy of [this Google Sheet](https://docs.google.com/spreadsheets/d/1TSynjEUrOrm_HfLxb2NAPDXxnn7wyy1bSEb2RruC67Q/edit#gid=0) (or download Excel version).
  - [x] Fill out product information basics.
  - [x] If a part of your product involves any sort of linear process/funnel for which you want to be able to measure conversions, please include it in the "Forms" tab of the template.
  - [ ] All other pages associated with your product for which you'd want to track visits and engagement should be added to the "Content" tab.
- [x] Link to your completed spreadsheet here: https://docs.google.com/spreadsheets/d/1TOZ4HNLc-TXjPl32ISvdQ4tq_a7fOpayg8wY6mL2SOE/edit?usp=sharing
- [x] Check your sharing settings to make sure the Analytics team will be able to access it.
- [x] Answer the questions in the **VFS-provided information** section below.
- [x] Add links to the **VFS-provided information** section below.
- [x] Add your team label to this ticket to follow its progress.

### Product questions
Help us understand your product better by answering the following questions:

1. **What does your team consider a completed task?** Clicking "Update"
2. **Who is your product's main user base?** Mostly veterans, but anyone who signs into VA.gov can access the profile regardless of veteran status
3. **Why does your product require an edge case?** We have a ton of GA dashboards because we have a handful of products in the profile. We still need and intend to use those GA dashboards, but it would be helpful to have an overview dashboard for the profile to track things at a high-level.
4. **Does this product currently have a Domo dashboard?** Yes, but I don't have the link for it. We don't use the old profile domo dashboard at all, and it can be totally scrapped.

### Product resources

I would like a high-level Domo dashboard for the profile to track overall profile health across the different products we have in this section. I'd like this dashboard to show five things:

- Total searches across all profile pages (note: there are 7 sections in the profile, each with a unique URL)
- Successful retrievals (`GETs`) across profile products
- Failed retrievals (`GETs`) across profile products
- Successful saves across profile products
- Failed saves across profile products

Being able to view things at a high-level will help me keep an eye on things and will let me know when I might need to drill further into one of our more detailed GA reports.

**Profile URLs**

As a reminder, here are all the Profile URLs:

https://www.va.gov/profile/personal-information
https://www.va.gov/profile/contact-information
https://www.va.gov/profile/military-information
https://www.va.gov/profile/direct-deposit
https://www.va.gov/profile/notifications
https://www.va.gov/profile/account-security
https://www.va.gov/profile/connected-applications

**Existing GA reports**

Additionally, we have a ton of existing GA reports, which we plan to keep and use to drill down for more specific information. In case it is helpful, here are all the existing GA reports for the profile:

- [Personal and military information dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/-x0K5pQPRTaQCa_WzXnEDg/a50123418w177519031p176188361/)
- [Contact information dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/3Z1vT6SlQqevdav1s72QwA/a50123418w177519031p176188361/)
- [Address validation information dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/)
- [Direct deposit for comp & pen dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/)
- [Direct deposit for education benefits dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/)
- [Notification preferences dashboard](https://analytics.google.com/analytics/web/#/dashboard/LcYXUwF2Q8SQ59WQX6OTsw/a50123418w177519031p184624291/)
- [Account security dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/AuydfL6WR7WS_nXqNhC5GA/a50123418w177519031p176188361/)
- [Connected apps dashboard](https://analytics.google.com/analytics/web/#/dashboard/-7uuXRP8QJOLgqwi7s5OOg/a50123418w177519031p176188361/)

**Additional info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards.
- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request it here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by Samara-Strauss** [comment]
@SKasimow I created this request for a high-level Domo dashboard for the profile to see the following across products:

- Total searches across all profile pages (note: there are 7 sections in the profile, each with a unique URL)
- Successful retrievals (GETs) across profile products
- Failed retrievals (GETs) across profile products
- Successful saves across profile products
- Failed saves across profile products

I still plan to use GA dashboards to view more detailed information and KPIs.

**Comment by Samara-Strauss** [comment]
@michelle-dooley whenever you all are ready to pull this into a sprint, let me know. I think it would help to have a quick regroup before getting started.

**Comment by michelle-dooley** [comment]
@Samara-Strauss - thanks for your submission.  As you have heard we are bit under staffed right now.  I will add this to our dashboard backlog (there are 2 other in front of it).  I will let you know when are able to begin working on it but expect that it won't be in the next couple sprints unfortunately.

**Comment by Samara-Strauss** [comment]
Totally fine. There is absolutely no rush. Get to it when you get to it, and thanks!

**Comment by chloedotbrown** [comment]
Hi @Samara-Strauss and @SKasimow - we're finally starting work on this! The actions and URLs submitted in the request template, along with the links to current GA dashboards, have given us a great place to start. 

However, I'm going to need some more help from your team to **fill in the blanks** for some of the `event actions` we're missing to be able to provide the metrics requested. Likewise, if any of these events are **mis-categorized**, please let us know! Once we have this list confirmed, we can start modeling the data for this dashboard.

Profile information | Page | "Retrieve" events | "Save" events
-------|------|-------------------|--------------
Preferred name | /profile/personal-information/ | 'API Request - PUT /profile/preferred_names - (started&#124;successful&#124;failed)' | ❓
Gender identitiy | /profile/personal-information/ | 'API Request - PUT /profile/gender_identities - (started&#124;successful&#124;failed)' | ❓
Military information | /profile/military-information/ | 'API Request - GET /profile/service_history - (started&#124;failed)', 'API Request - GET /profile/service_history Source: api.va_profile - successful' | _(not requested)_
Mailing address | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Mailing Address', 'Profile Save Failure - Mailing Address'
Home address | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Home Address', 'Profile Save Failure - Home Address'
Home phone | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Home Telephone Number', 'Profile Save Failure - Home Telephone Number'
Mobile phone | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Mobile Phone Number', 'Profile Save Failure - Mobile Phone Number'
Work phone | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Work Telephone Number', 'Profile Save Failure - Work Telephone Number'
Contact email | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Email Address', 'Profile Save Failure - Email Address'
Direct deposit (disability comp & pension) | /profile/direct-deposit/ | 'Profile - Direct Deposit Retrieval Successful', 'Profile - CNP Direct Deposit Retrieval Successful', 'Profile - Direct Deposit Retrieval Failed', 'Profile - CNP Direct Deposit Retrieval Failed' | ❓
Direct deposit (education benefits) | /profile/direct-deposit/ | 'Profile - EDU Direct Deposit Retrieval (Started&#124;Successful&#124;Failed)' | ❓
Notifications | /profile/notifications/ | 'API Request - GET communication_preferences - (started&#124;successful&#124;failed)' | 'API Request - POST communication_preferences - (started&#124;successful&#124;failed)'

**Comment by Samara-Strauss** [comment]
Hi @chloedotbrown! Question for you -- are you asking what these are named in GA right now? I would imagine all retrievals are `GET` events and all saves are `PUT` events, though the name that appears on the frontend of GA might be different.

**Comment by chloedotbrown** [comment]
Yep @Samara-Strauss! This dashboard will be based on GA data, so we'll need to know all the GA names for these events to pull the right info.

Based on the GET/PUT note, I've swapped our knowns/unknowns for Preferred Names and Gender Identity. However, it seems like other patterns are used for other events, and not all GETs have a corresponding PUT, etc. Any other info the team can provide would be great!

**Comment by Samara-Strauss** [comment]
@chloedotbrown I've updated the preferred name, gender identity, and direct deposit fields. However, I'm not sure if we have/are tracking `GETs` for contact information (addresses, phone numbers, email address).

@SKasimow can you enlist Adam or John to determine if we are tracking successful and failed retrievals of all the contact information fields? If neither has bandwidth until next sprint, that is fine. This is not urgent, and they can address this as time allows.

**Comment by chloedotbrown** [comment]
Thanks so much for these adds, @Samara-Strauss!

@SKasimow - please feel free to reach out if you have any questions.

**Comment by SKasimow** [comment]
Thanks - I'll circle back when I have the info.

**Comment by adamwhitlock1** [comment]
`API Request - GET /v0/user - successful` looks to be the event action that you would put in that table for all the missing sections, email, phone, address etc

**Comment by SKasimow** [comment]
Thanks - and the rest of the table looks good?

**Comment by SKasimow** [comment]
Profile information | Page | "Retrieve" events | "Save" events| 
-------|------|-------------------|--------------
Preferred name | /profile/personal-information/ | `API Request - GET /profile/personal_information - (started/successful/failed)`| 'API Request - PUT /profile/preferred_names- (started&#124;successful&#124;failed)' |
Gender identity | /profile/personal-information/ | `API Request - GET /profile/personal_information - (started/successful/failed)` | 'API Request - PUT /profile/gender_identities - (started&#124;successful&#124;failed)'
Military information | /profile/military-information/ | 'API Request - GET /profile/service_history - (started&#124;failed)', 'API Request - GET /profile/service_history Source: api.va_profile - successful' | _(not requested)_
Mailing address | /profile/contact-information/ | API Request - GET /v0/user - (started/successful/failed)| 'Profile - Form Submit - Mailing Address', 'Profile Save Failure - Mailing Address'
Home address | /profile/contact-information/ | API Request - GET /v0/user - (started/successful/failed) | 'Profile - Form Submit - Home Address', 'Profile Save Failure - Home Address'
Home phone | /profile/contact-information/ | API Request - GET /v0/user - (started/successful/failed) | 'Profile - Form Submit - Home Telephone Number', 'Profile Save Failure - Home Telephone Number'
Mobile phone | /profile/contact-information/ |  API Request - GET /v0/user - (started/successful/failed) | 'Profile - Form Submit - Mobile Phone Number', 'Profile Save Failure - Mobile Phone Number'
Work phone | /profile/contact-information/ | API Request - GET /v0/user - (started/successful/failed) | 'Profile - Form Submit - Work Telephone Number', 'Profile Save Failure - Work Telephone Number'
Contact email | /profile/contact-information/ | API Request - GET /v0/user - (started/successful/failed) | 'Profile - Form Submit - Email Address', 'Profile Save Failure - Email Address'
Direct deposit (disability comp & pension) | /profile/direct-deposit/ | 'Profile - Direct Deposit Retrieval Successful', 'Profile - CNP Direct Deposit Retrieval Successful', 'Profile - Direct Deposit Retrieval Failed', 'Profile - CNP Direct Deposit Retrieval Failed' | Successful saves - `Profile - Form Submit - CNP Direct Deposit Information`; Failed saves - `Profile Save Failure - CNP Direct Deposit Information`  ([this report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/))|
Direct deposit (education benefits) | /profile/direct-deposit/ | 'Profile - EDU Direct Deposit Retrieval (Started&#124;Successful&#124;Failed)' | Successful saves - `Profile - Form Submit - EDU Direct Deposit Information`; Failed saves -` Profile Save Failure - EDU Direct Deposit Information` ([this report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/))
Notifications | /profile/notifications/ | 'API Request - GET communication_preferences - (started&#124;successful&#124;failed)' | 'API Request - POST communication_preferences - (started&#124;successful&#124;failed)'

**Comment by Samara-Strauss** [comment]
Thank you, @adamwhitlock1 @SKasimow!

**Comment by chloedotbrown** [comment]
Hi @SKasimow and @adamwhitlock1 - thanks for getting this back so quickly!

I'm a little suspicious whether `API Request - GET /v0/user - successful` is actually the event action we need here. There don't seem to be any `started|failed` variations in GA, so we couldn't actually use this to track failures or failure rates for this group of retrievals. In addition, this event seems to exist on many of the other VA Profile pages where retrievals do have information-specific API call events configured that we're using instead.

Is there anything else it could be?

<img width="1367" alt="Screen Shot 2022-11-04 at 8 42 07 AM" src="https://user-images.githubusercontent.com/45518242/200017314-c960a879-979b-42f9-a96a-3fb5d6eeafb5.png">

**Comment by SKasimow** [comment]
@chloedotbrown - we need to dig a little deeper into this so I'm opening a ticket for Adam to investigate; we'll circle back when we have more insight.

**Comment by chloedotbrown** [comment]
Sounds good, @SKasimow! Just update us here when you're ready.

**Comment by michelle-dooley** [comment]
@SKasimow and @Samara-Strauss - Chloe created a [mock up](https://docs.google.com/presentation/d/1zzFSi5ZfIDqy5buQZX1NwRjvCA-dwPTDYOaSidCwZlw/edit#slide=id.g11b31d375b2_0_0) for this request and we would like to schedule some time to walk through together to make sure we are getting you everything you need, answering any questions you may have and talk next steps.  I know with holiday next week it may be a challenge but here are some days/times let us know what works for you and I will get it scheduled.

Monday 11/21:  1-4 ET
Tuesday 11/22:  1-3 ET
Monday 11/28:  3-4 ET
Tuesday 11/29:  1-3ET
Wednesday 11/30:  12-1 
Thursday 12/1:  12-1

**Comment by SKasimow** [comment]
Hello! - I've added in my open slots:

Monday 11/21: 1-4 ET:  1.30 - 2.30pm or 3.30pm et
Tuesday 11/22: 1-3 ET: 1-3pm et
Monday 11/28: 3-4 ET:  xx
Tuesday 11/29: 1-3ET: 1 - 3pm et
Wednesday 11/30: 12-1 12 - 1pm
Thursday 12/1: 12-1: xx

**Comment by Samara-Strauss** [comment]
So sorry this fell off of my radar! My preference would be after Thanksgiving. I can do the following timeslots:

- Tuesday 11/29: 2:30 - 3:00
- Wednesday 11/30: 12 - 1

**Comment by chloedotbrown** [comment]
@dorseypa1 and @michelle-dooley - @SKasimow confirmed on ticket #49847 that her team has completed this implementation, meaning we can begin modeling work. 

Phil, for complete list of events, please see the most recent table in Sharon's comments above. If you have any questions, please feel free to reach out!

**Comment by michelle-dooley** [comment]
@Samara-Strauss - just wanted to give you an update on this work.  @dorseypa1 has completed the data modeling work and our new analyst @ChristineYoungZA is working on the Domo build now.  Hoping to have this to you soon (next week is my goal).

**Comment by michelle-dooley** [comment]
Hey @Samara-Strauss - we are on the final rounds of the dashboard QA and I noticed when looking at the GA dashboards you provided they are not filtered by the profile page type as defined in the table above.  For example your Personal Information numbers are significantly higher b/c you are looking for the "API Request - GET/profile/personal_information" events for all pages and I am using same event but only for that page "/profile/personal-information/" as defined by the table above.  Same issue across other events but not quite as significant.  Do you want us to the page filters outlined above or should we just use those event actions regardless of the page they occurred on?

**Comment by Samara-Strauss** [comment]
@michelle-dooley thanks for raising this -- please only use data that comes from the profile. I don't remember who set up the GA dashboards at this point, but if it was our old PM, she may not have realized she was setting them up to call from all pages and not just the profile.

**Comment by michelle-dooley** [comment]
@Samara-Strauss - I think by the nature of the events they are all on a /profile/  page but perhaps not as outlined above.  My counts are based off the specific page /profile/personal_information/ (yellow highlights) her counts area based on /profile/  Looks like the personal information events can happen on other pages too, do we want those included?  See below I think that will help clarify.

![image](https://user-images.githubusercontent.com/93597659/225731432-79790e2d-d037-47da-a22a-5009bc81c71d.png)

![image](https://user-images.githubusercontent.com/93597659/225732122-0b31c8bc-8e82-4e30-bb02-99b29662018b.png)

**Comment by Samara-Strauss** [comment]
> My counts are based off the specific page /profile/personal_information/ (yellow highlights) her counts area based on /profile/

OK, yes, let's follow your approach - we should be capturing all instances of an event, including where the profile URL has a slug like `postlogin=true` to make sure everything is counted.

**Comment by michelle-dooley** [comment]
@Samara-Strauss - Great!!  And yes we did include URL slugs like ?postlogin and ?next in our page query.  If you change your mind later we can always loosen the parameters to be more inclusive.

**Comment by Samara-Strauss** [comment]
Thank you! And I don't think this will change. The best part of Domo is that it's really easy to get the full picture with aggregated data around different URL permutations. Thank you for checking in on this!

**Comment by michelle-dooley** [comment]
@Samara-Strauss - Here is the [Profile dashboard](https://va-gov.domo.com/page/1834995012)
) for your review.  I will be out next week through the 27th but will be happy to go over and discuss any questions when I am back.  Wanted to give you some time with it while I am out.  Hope it meets your expectations!!

**Comment by Samara-Strauss** [comment]
Thanks, @michelle-dooley! I will review likely on Monday. I'm on baby-watch for my maternity leave, so it's possible I will be out when you get back (or I might still be here -- who knows!). Just wanted to let you know in case I suddenly disappear.

**Comment by Samara-Strauss** [comment]
cc/ @clantosswett @BerniXiongA6 in case you need to step in resolve issues for Michelle while I am out on leave.

**Comment by Samara-Strauss** [comment]
@michelle-dooley this is great! I think this is pretty much good to go, though the graph below can be removed. My initial request was unclear (sorry!), but all we need is the list of search terms across profile that's shown lower in the dashboard.

**To remove**

![image](https://user-images.githubusercontent.com/34068740/226358275-e9659fe3-4c96-4e89-9583-3d02a11d334f.png)

**Comment by Samara-Strauss** [comment]
Great, thank you!!
