### ISSUE TITLE
[BE] 10-10CG - Bug: PDF Special Character Generation Error

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#46862]
In at least some cases, when a PDF is generated from the 10-10EZ form, special characters are not being encoded/translated properly.

The example provided is the middle name _O'Dell_, which came across in the PDF as _O?Dell_.

Per emails from CG team:

> We received an application online in CARMA that contained a ? in the middle name (CD- 1128239). Review of MPI and the electronic health record indicate there should be no ? (we are assuming this was a typo by the applicant), however for due diligence sake: is there a bug of some sort affecting applications.
>The application was received into CARMA on 5/30/22 at 9:54 am ET.
>
>The payload shows a special character so it seems there is an issue when putting special characters into the PDF itself. 
![image](https://user-images.githubusercontent.com/92328831/190244259-d06630f4-9615-4622-b737-bc1cc4293966.png)

**Comment by hdjustice** [comment]
@hdjustice - paste email from CG team here
