### ISSUE TITLE
SOCKS access for Mark Komosa

### ISSUE THREAD

**Issue by markkvba** [department-of-veterans-affairs/va.gov-team#46864]
### Your Name

Mark Komosa

### Your Email

Mark.Komosa@va.gov

### Your Role and Team

Dev LEAD GCIO VFEP 

### Product Manager (PM) name and email

Darla van Nieukerk, IT PM, BAM

### Product Owner (PO) name and email

Michael Napper, EDU Chief

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD3q9oLQDtAMhS0H8WMfmiQadv/Hz7EgqiLl4/zG8IDt/cyVUNUhCHN+2tNizYqGzGmzORA1gweQCj1tdFW2ZA2KtpAdEtJZ7UoYr1GR2OUsovKZatn2XtKPabOuGYF5TyDaKww5oDtqbzO47+pkZVlegqQoUP37//8dyd1UjAjung/544WyZYAI/qQndUMTiVaQInR86GixR0/Z3zd/8c/OaD2evgcUyOXV+kNNekAsWr5yQ2Wj3oHSGysPhHU4e6PlCbVDia3g+hjSr/lsY6PM1YBdOrgmf7Yk/M6sqlTiCuNSvNzK3s6FEINjMUR7kgRL7FWTMIaFfZnNzazzavORi2MSpPEVLnnlV6YUzcC/rCH+zL89PdB5YNJtxeui2OlirGyMfUFBhRW6U4hokAD+w/jT+/QKcNB8+9O3TEgRxdGOASEkvxtck2M11emGiiljc+glF07zPz7mpY7D/FgJy1GccBWEkilehQFwRMDATYA94o6rO/G2YV5LN0NMWE= mark@XPSBox

### User must exist in a roster before SOCKS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
