### ISSUE TITLE
AWS access for Mark Dewey

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#46870]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

No Vender, I am a part of the VA

### Your Name

Mark Dewey

### Your Email

mark.dewey@va.gov

### Team, Role, and Company of the target individual

Engineer, Office of the CTO, Health Apps Teams

### Product Manager (PM) name and email

N/A

### Product Owner (PO) name and email

They closest I have to a PO is Lauren Alexanderson, lauren.alexanderson@va.gov 

### Desired AWS Access

I need access to the staging vets rails console. I need to be able insert rows into the staging database for testing. 

### Access Expiration

ongoing

### Additional Notes

I need access to staging so I can populate staging test data into our database. I have the rails commands ready to go, just need access to the rails terminal. 

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
Hey @mdewey !

I noticed some fields are missing from the ticket, can you get those filled out? They AWS approvers group most likely will not process if those pieces of information are missing

**Comment by mdewey** [comment]
@oseasmoran73 I have updated a few fields, What else do you need?

**Comment by oseasmoran73** [comment]
@mdewey I think we are all set! for request!

**Comment by td-usds** [comment]
Requested access approved

**Comment by oseasmoran73** [comment]
Reached out to Mark via Slack and provided instructions & login credentials. 

Closing ticket. Please feel free to reopen or reach out if you run into any issues Mark!
