### ISSUE TITLE
[Datadog] Write access for Kyle Soskin

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#46872]
## Description

@kylesoskin Was previously on a platform team and still has access to Datadog. With the recent change to a VFS team, he does not have the correct permissions to write/save dashboards

## Background/context 

Evaluate edge cases. See #36260 #33081 for additional details

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
This is no longer needed. Kyle was offboarded.
