### ISSUE TITLE
VAOS - Choose-type-of-care page - Styling anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#46877]
## What happened?
On Staging **VAOS Choose-type-of-care** page [during scheduling], **...home address...** alert, **Update...** button spills-out beyond right border of alert-box.

## Specs:
- Device: Android & iOS phones w/ viewport-widths <= 480px [replicable in desktop Chrome Dev-tools Responsive tab]
- Browser: Chrome, Safari
- Test User _(if applicable)_: patient999@id.me [password same as test-users on [this list](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)].

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/

1. On Staging VA Online Scheduling page, click **Start scheduling** button.
2. On Choose the type of care you need page, in **...home address...** alert, observe that **Update your address** button spills out of alert-box right-border.

### Screenshot
[iPhone 12-mini Safari example]
![image](https://user-images.githubusercontent.com/587583/189462463-3cbb1704-3ca9-4d13-9930-8dc885cddc6d.png)

## Desired styling
- [ ] **Update...** button should stay within alert-box.

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by simiadebowale** [comment]
@ldelacosta, this is ready for Tze to qa.
Review Instance link: http://951298574f6252a6fcce2a26e5bec077.review.vetsgov-internal/

**Comment by ldelacosta** [comment]
@tlei123 - This is ready to be tested. Please let us know if you have any questions. Thanks!

**Comment by tlei123** [comment]
@ldelacosta @simiadebowale , bugfix in RI looks good on Mac Chrome DevTools Responsive emulator.

Let me know please once in Staging &mdash; I'll check it there against mobile devices via BrowserStack.

**Comment by simiadebowale** [comment]
@tlei123 this should be in staging now.

**Comment by tlei123** [comment]
@ldelacosta @simiadebowale , successfully validated in Staging.  Feel free to Close.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
