### ISSUE TITLE
Content review of text notifications content in 1990e tool

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46875]
## Issue Description
Stakeholder Tammy asked us to review this text notification alert content for the 1990e transfer of entitlement tool. 
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/ac714b52-db17-4e13-88aa-13d6458daa84)

Here's a link to the [mockup](https://app.abstract.com/share/4b85619e-f747-4275-993e-2bab8ccfff1a?collectionId=347ac9a2-19f4-48b6-a2b0-7b80a0a8587d&collectionLayerId=970fc815-eb8e-4366-8c72-3264bbad3f8e&present=true&preview=false&sha=70fa2a3561184ef919cd487358f20caef9111027)

---
## Tasks
- [x] Review (Laura)
- [x] Send to Tammy (Laura)

## Acceptance Criteria
- [x] Stakeholder has approved content

**Comment by laurwill** [comment]
Just noting that I sent Tammy some content suggestions over email on 9/15.

**Comment by RLHecht** [comment]
Closing this and will reopen if Tammy comes back with more changes for us to make.
