### ISSUE TITLE
Design | Profile | Accessibility | Screenreader on DD FAQs

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46876]
## Background

When editing Direct deposit/comp & pension benefits, the initial focus is placed on the first editable field (routing info). If you arrow up and open the FAQ, JAWS will not see the paragraph detailing how to get the routing info.

The proposed solution by the a11y team is to:

> Set focus to the h2
> 
> The paragraph with the information is a figure caption. Removing it from the figure element and placing it in a plain paragraph below the image will solve the problem.
> 

Additional background from original ticket is here: #46614.

## Tasks
- [ ] Create a mock with the proposed (or alternative) solution

## Acceptance Criteria
- [ ] Review with Profile and a11y team

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@andaleliz - great! 

This is more of a process question but as we work through the accessibility tickets should we have an a11y person also check and confirm our updates are working as expected?

cc: @cgednalske

**Comment by andaleliz** [comment]
I think it depends on the complexity of the issue, but I'm not totally sure. I don't think there's a process set in stone for that.

That'd be a great question to bring to Angela's office hours on Wednesday evenings or Friday mornings if you are available during those times.

**Comment by SKasimow** [comment]
Hi @TiffanyPender - this is one that looks to be completed; could you review?

**Comment by TiffanyPender** [comment]
Is this one updated in staging? I don't seem to see this update. @SKasimow

**Comment by SKasimow** [comment]
Sorry @TiffanyPender! I tagged you too soon. We have a front-end ticket that needs to go in so will tag you when that's ready in staging. Apologies!!
