### ISSUE TITLE
Content review for Authenticated Experience Profile team - Cancel edit modal buttons

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#46894]
## Background

When a user hits "cancel" instead of "update" while editing their contact information, we currently show a modal with this content:

**Are you sure?** [heading]

You haven't finished editing and saving the changes to your [data]. If you cancel now, we won't save your changes. [body]

Continue editing [button 1] 
cancel [button 2]

<img width="479" alt="image" src="https://user-images.githubusercontent.com/55992116/189689398-9fbc248f-d5c8-4528-a85c-506f1d3d3214.png">

During an accessibility audit, a concern was raised that those buttons _may_ be confusing, and would be more clear with yes and no responses to the "are you sure?" question.

## What we're asking

1. Do you think the labels need to be revisited?
2. If so, what about changing them to 

Yes, cancel my changes [button 1]
No, go back to editing [button 2]

<img width="440" alt="image" src="https://user-images.githubusercontent.com/55992116/189690282-60b8d7ce-4944-41b9-a357-ea7e857e4520.png">

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. I love these changes - yes, let's go with this!

**Comment by andaleliz** [comment]
Wonderful, thanks so much! We'll go with this.
