### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#46899]
### Request type

- [ ] Writing new documentation
- [ ] Updating previously published documentation
- [x] Reviewing recently written, never-before-published drafts

### Number of docs

31

### Subject matter expert

Me.

### Approvals

Naomi Marcussen

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [ ] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other

### This list is a rework of the navs on [Research and Design page](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions).
- **[Research: Overview](https://depo-platform-documentation.scrollhelp.site/research-design/research-overview)**	
  - Research Overview
- **Research: Planning and recruiting**	
  - Planning and recruiting
  - Planning and recruiting checklist
  - Planning Moderated studies
  - Planning Unmoderated studies
  - Recruting participants
- **[Research: Conducting sessions](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)**	
  - Conducting Research Sessions
  - Conducting sessions checklist
  - Pilot participant guidelines
  - Observer Guidelines
  - Safety and Emergency Exit
  - Tech set-up checklist
  - Recording research sessions
- **[Research: Mobile sessions](https://depo-platform-documentation.scrollhelp.site/research-design/using-zoom-for-research)**	
  - iPhone: Start screen share
  - iPhone: Stop screen share
  - iPhone: Screen recording set-up
  - iPhone: Access chat
  - Android: Start screen share
  - Android: Stop screen share
  - Android: Share device audio
- **[Research: Assistive technology sessions](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)**	
  - Research with Assistive Technology Users
  - Testing with screen readers
  - Disability Etiquette

**Comment by vbellissimo** [comment]
@jimuhh Closing this ticket on here, since @naomimarcussen  has completed this request and the Platform Content team has deployed the changes.

**Comment by vbellissimo** [comment]
@laucon Coordinated communication via Slack between Naomi and Jim before publishing the changes live.
