### ISSUE TITLE
Introduce TestRail to VAOS team

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4689]
Peter works with Mark to set up VAOS using TestRail.

**Comment by pjhill** [comment]
- Provided links to documentation and tutorials
- Discussed capabilities of TestRail with Kam and Mark from VAOS team
- Talked to Mark Greenburg about getting some of their test cases into TestRail
- Imported UAT Phase 3 test cases into a new [VSP-VAOS](https://dsvavsp.testrail.io/index.php?/suites/view/21&group_by=cases:section_id&group_order=asc) project within TestRail
