### ISSUE TITLE
Add Treatment Specialty -  Booked Community Care Appointment Details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#46903]
## Description
HSRM is passing Treatment Specialty in `vaos-service` and the frontend will need to display the specialty for the provider on the booked Community Care appointment details page. The Veteran will be able to see the provider's specialty when they are viewing their Community Care appointment. 

**An example of the response body for the booked Community Care Appointment:** 

   {
     "id": "124063",
     "type": "appointments",
     "attributes": {
       "id": "124063",
       "identifier": [
         {
           "system": "http://med.va.gov/fhir/urn/vaos/hsrm/id",
           "value": "524679||2||1"
         },
         {
           "system": "http://hl7.org/fhir/sid/us-npi",
           "value": "1689755084"
         }
       ],
       "kind": "cc",
       "status": "booked",
       "description": "Podiatry DS SEOC 1.0.8 PRCT",
       "patientIcn": "1013124304V115761",
       "locationId": "984",
       "practitioners": [
         {
           "name": {
             "family": "RICHMOND",
             "given": [
               "TANISHA R"
             ]
           }
         }
       ],
       "start": "2022-09-29T13:00:00Z",
       "created": "2022-08-15T19:06:50Z",
       "cancellable": true,
       "extension": {
         "ccLocation": {
           "address": {
             "line": [
               "1323 W 3RD ST"
             ],
             "city": "DAYTON",
             "state": "OH",
             "postalCode": "45402",
             "text": "1323 W 3RD ST\nDAYTON OH 45402"
           },
           "telecom": [
             {
               "system": "phone",
               "value": "937-228-3668"
             }
           ]
         },
         "hsrmTaskId": "12881",
         "hsrmConsultId": "984_644233",
         **"`ccTreatingSpecialty": "Podiatrist"`**
       },
       "location": {
         "id": "984",
         "type": "appointments",
         "attributes": {
           "id": "984",
           "vistaSite": "984",
           "vastParent": "984",
           "type": "va_health_facility",
           "name": "Dayton VA Medical Center",
           "classification": "VA Medical Center (VAMC)",
           "timezone": {
             "timeZoneId": "America/New_York"
           },
           "lat": 39.74935,
           "long": -84.2532,
           "website": "https://www.dayton.va.gov/locations/directions.asp",
           "phone": {
             "main": "937-268-6511"
           },
           "physicalAddress": {
             "type": "physical",
             "line": [
               "4100 West Third Street"
             ],
             "city": "Dayton",
             "state": "OH",
             "postalCode": "45428-9000"
           },
           "healthService": [
             "Audiology",
             "Cardiology",
             "DentalServices",
             "Dermatology",
             "Gastroenterology",
             "Gynecology",
             "MentalHealthCare",
             "Nutrition",
             "Ophthalmology",
             "Optometry",
             "Orthopedics",
             "Podiatry",
             "PrimaryCare",
             "SpecialtyCare",
             "Urology",
             "WomensHealth"
           ]
         }
       }
     }
   },

---

## Acceptance Criteria
Background: the `va_online_scheduling_vaos_v2_next` toggle is on

Given when a Community Care appointment is booked through HSRM 
When a Veteran views their upcoming Community Care appointment details
Then specialty of the provider will be displayed in VAOS  
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-future) 
And page design matches the [design spec](https://www.figma.com/file/HxgPrBFb7RoVtkVXL5CYZJ/Add-Treatment-Specialty-to-CC-details?node-id=525%3A13625)

Given when a Community Care appointment is canceled through HSRM 
When a Veteran views the canceled Community Care appointment details
Then specialty of the provider will be displayed in VAOS  
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-canceled) 
And page design matches the [design spec](https://www.figma.com/file/HxgPrBFb7RoVtkVXL5CYZJ/Add-Treatment-Specialty-to-CC-details?node-id=525%3A13625)

Given when a Community Care appointment is booked through HSRM 
When a Veteran views their past Community Care appointment details
Then specialty of the provider will be displayed in VAOS  
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-past) 
And page design matches the [design spec](https://www.figma.com/file/HxgPrBFb7RoVtkVXL5CYZJ/Add-Treatment-Specialty-to-CC-details?node-id=525%3A13625)

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
The code should sit behind the`vaos-v2-next` toggle.

**Comment by ldelacosta** [comment]
@ryanshaw - We made a minor adjustment to the requirements. I removed this acceptance criteria: 

_Given when a Community Care appointment is booked through HSRM 
When the `ccTreatmentSpecialty` is `null` or `blank` in the response body
Then the frontend will not display the Specialty label in VAOS_ 


Copy docs have been updated for booked CC, canceled booked CC and past booked CC appointment details. 

Example - 
Type of care: {Type of Care}

```
- Community care 
+ Community care proivder
```
{Provider name}
`+ {Treatment specialty}`
@@ GH46903 @@ 

Please reach out if you have any questions. Thanks!

**Comment by ldelacosta** [comment]
When viewing booked CC appt in VAOS, the specialty is not showing up. @ryanshaw will review.

CC booked appt for Judy Morrison on 12/15/2022 at 9:00 AM
Response body: 
``` 
"extension": {
                "ccLocation": {
                    "address": {
                        "line": [
                            "43810 CENTRAL STATION DR ; STE 160"
                        ],
                        "city": "ASHBURN",
                        "state": "VA",
                        "postalCode": "20147",
                        "text": "43810 CENTRAL STATION DR ; STE 160\nASHBURN VA 20147"
                    },
                    "telecom": [
                        {
                            "system": "phone",
                            "value": "703-291-6334"
                        }
                    ]
                },
                "hsrmTaskId": "",
                "hsrmConsultId": "984_644348",
                "ccTreatingSpecialty": "Podiatrist - Foot & Ankle Surgery"
            },
```

![Screen Shot 2022-09-21 at 4.58.04 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/65afec12-21d8-4013-a94e-1929402b00e9)

**Comment by ldelacosta** [comment]
Validated the changes in staging and was able to view the Community Care appointment details on 12/15/2022 for Judy Morrison and Patient999. 

Will close out the ticket when SQA has completed their testing. 

![Screen Shot 2022-09-26 at 12.01.10 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/31d52f47-8a40-4962-b6eb-bd0a540377d3)

![Screen Shot 2022-09-26 at 12.03.08 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/674cec69-5c31-4382-ab22-2bf211f3310f)

**Comment by marcynadeau** [comment]
@ldelacosta Just a quick heads up until Aarathi has time to updated the ticket.  Tested and passed with existing requests. Waiting on HSRM fix in Staging to test with newly entered requests This is the JIRA ticket for the HSRM Staging issues.  https://issues.mobilehealth.va.gov/browse/VAOSR-4454 (VAOS Staging: 502 error while creating CC request in VAOS)

**Comment by aarathi-poldass** [comment]
@ldelacosta Here are the scenarios that were tested today. I was able to test with multiple test user and different specialty types:

Scenario 1: Validate the "Treatment Specialty" is displaying on already existing CC appointments (Upcoming, Past and Cancelled queues) - PASS
Scenario 2: Enter a CC request in VAOS and process the request with the required specialty and validate the flow - Can't test due to HSRM issue
Scenario 3: Enter a CC request in VAOS and process the request with a different specialty and validate the flow - Can't test due to HSRM issue
Scenario 4: Schedule a CC appointment using a pre-existing referral - PASS
Scenario 5: Change the Treatment specialty on a pre-existing referral and validate the flow - PASS
Scenario 6: Schedule CC appointment with max/ specials character "Treatment Specialty" - PASS

Please note we are waiting on the HSRM side to resolve the issue. There were some recent code changes in the IPE environment which are triggering the error. Thomas is working with the HSRM team.

Please find the screenshots from my testing today for reference.
![max/specials character](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/123c62a0-d4a4-40a2-8b14-d119b922c605)
![Optometry](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/42deb6f5-81b2-43cc-88d8-4315ab8e309d)

**Comment by aarathi-poldass** [comment]
After VAOSR-4454 was fixed by the HSRM team, we were able to test 2 remaining scenarios from the above Comment:
Scenario 1: Enter a CC request in VAOS and process the request with the required specialty and validate the flow - PASS
Scenario 2: Enter a CC request in VAOS and process the request with a different specialty and validate the flow - PASS

@ldelacosta this passes testing. No issues to report. Please close the ticket. Thank you!

**Comment by JRRoof** [comment]
Closing ticket.  All scenarios passed.
