### ISSUE TITLE
Investigate evidence submission logs feature logging

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#46953]
# Situation

It is important for us to monitor the number of evidence submissions that are rejected/accepted by upstream systems like BGS.  We should use monitoring tools like Sentry, DataDog, or others to do this. 

For context, Michel was using the following bit of code to do the work: 

`#fetch 526 file upload errors
jss = Form526JobStatus.where(job_class: "SubmitUploads", status: ['exhausted', 'non_retryable_error'])
jss.each do |js|
  puts "#{js.error_message}, #{js.error_class}"
end; nil`

Specifically, it would be good to track these numbers month over month. 

# Acceptance Criteria

- [ ] Set up future monitoring for the above in Sentry/DataDog

**Comment by sortizsh** [comment]
companion to https://github.com/department-of-veterans-affairs/va.gov-team/issues/48198
