### ISSUE TITLE
Adding Oliver Moreno to DSVA Slack

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#46951]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Requesting to add [omorenop@thoughtworks.com](mailto:omorenop@thoughtworks.com) as a full member to DSVA Slack. He will be working as a Developer on the Digital Health Platform (DHP) team.

Please add to the channels
#digital-health-platform-public
#digital-health-platform-team

**Comment by robbie1226** [comment]
Is there any upate?

**Comment by eunicegar** [comment]
Invite sent
