### ISSUE TITLE
Pre-Usability Content Review: Caregiver Form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#4697]
As a member of the Caregiver team, I need to my content reviewed before Urgent care MVP launch to ensure it's accurate, aligns with VA style, and is error-free.

## Goal
Review initial prototype of Caregiver form 10-10CG ahead of usability sessions

https://vsateams.invisionapp.com/share/MWVG8WYHAR8#/screens/399804333

**Comment by peggygannon** [comment]
@ala-yna @psanders86 @Hello, I've completed the initial/pre-usability content review for the first 8 screens of the mockup. I would like to see this mockup again to check change inputs and to give the full form another content pass. 

Please let me know if you have any questions about my suggestions on first 8 screens. 

https://vsateams.invisionapp.com/share/MWVG8WYHAR8#/screens/400377077/comments

**Comment by psanders86** [comment]
Putting these content revisions on this ticket, although I understand they may be migrated to a new ticket.
[10-10CG content revisions.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4062389/10-10CG.content.revisions.docx)
