### ISSUE TITLE
RTT Platform Console Maintenance Plan

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#46974]
**PROBLEM STATEMENT**
The Platform Console was created by a Spike team, with the contracting ending Sept 11, 2022. Release Tools Team will be taking over the majority of Platform Console work, including maintenance. Release Tools Team needs to understand what maintenance tasks are expected, and develop a plan to incorporate that into the team's current support/maintenance structure.

**DEFINITION OF DONE**
- [ ] Complete a [support and maintenance plan](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2363850952/Platform+Console) for RTT for The Platform

Helpful links
- https://vfs.atlassian.net/wiki/spaces/CUI/overview

**Comment by jhonnyoddball** [comment]
Console UI work, closing for now.
