### ISSUE TITLE
Investigate Cerner Staging Login Error

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46982]
Reported to us on 9/9 via email. They stated that when they try to login through the Cerner USiP they are redirected back to the login page on va.gov again after completing a successful auth. The Cerner team (Eric Donovan) share a video via email which demonstrates the looping. 

I was able to repro the issue by starting on this URL:  https://staging-patientportal.myhealth.va.gov/
Use these creds: ssoissoetesting+spokane1@gmail.com

I found an error during the redirect back through Cerner:
1. IDme completed auth
2. ` https://staging-patientportal.myhealth.va.gov/session-api/realm/f0fded0d-d00b-4b28-9190-853247fd9f9d?to=https://staging-patientportal.myhealth.va.gov/&postLogin=true `
3. ` https://staging-patientportal.myhealth.va.gov/?loginFailure=6409201390ff224b8a5a6377fcb9d1a3&errorCode=urn:cerner:error:identity-federation:saml2:security:metadata-unavailable ` 
4. ` https://staging.va.gov/sign-in/?application=myvahealth&to=/session-api/realm/f0fded0d-d00b-4b28-9190-853247fd9f9d?to=https://staging-patientportal.myhealth.va.gov/?loginFailure=6409201390ff224b8a5a6377fcb9d1a3&errorCode=urn%3Acerner%3Aerror%3Aidentity-federation%3Asaml2%3Asecurity%3Ametadata-unavailable `

**Comment by AGarcia-Clarity** [comment]
![Screen Shot 2022-09-13 at 12 54 38 PM](https://user-images.githubusercontent.com/67602137/189961888-450e3847-d9ff-4393-a46a-7f0671c60197.png)

The FE has confirmed the following:
- On initial login, the `createAndStoreReturnUrl` is generating the proper URL: `https://${
    cernerEnvPrefixes[environment.BUILDTYPE]
  }patientportal.myhealth.va.gov` with no additional query params
- Confirmed, no configuration files or URL constants have changed
- Confirmed (see screenshot above) the redirect sends a network request to the My VA Health URL
- Confirmed that the response from My VA Health is redirecting users back to VA.gov via the Unified Sign in Page

**Comment by joeniquette** [comment]
Cerner said they need to further investigate with eauth. We have determined this isnt our issue.
