### ISSUE TITLE
Front end behavior documentation approaches

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#4699]
We need to come up with documentation for the behaviors implemented on the front end. We have decent unit test and e2e coverage, and pretty sparse code comments. It would be nice to come up with a coherent approach so that we can easily on board developers on the rest of the VAOS team.

Some possibilities
- Our unit tests are the best documentation we have right now, so perhaps a combination of some overview docs and more rigorous and descriptive test names/cases
- Write up a bunch of documentation in markdown on GH
- More extensive code comments

**Comment by lenaecb** [comment]
@jbalboni - For the GH bullet, I think adding to and expanding on the current version of the Testing Plan MD would be helpful. This will help with VSP review of our testing plan as well. @pjhill is currently reviewing our latest testing documentation and methods as prep for our phased rollout. May be good time for him to collaborate with us on this.

**Comment by pjhill** [comment]
I would love to work with you all to create new test cases based on both your baseline and your upcoming changes.  TestRail provides for some traceability via links to GitHub user stories and bugs.  Understandably, you may not have user stories with clear acceptance criteria for your baseline, so a good starting point for a manual test plan might be an analysis of the unit tests / e2e tests which we expand for an overall test plan.

**Comment by lenaecb** [comment]
I have scheduled our TestRail intro for Tuesday 4/7

Hopefully from there we can also understand how to scope this particular ticket to better serve our testing and coverage needs.

**Comment by jbalboni** [comment]
So, it sounds like we want to get a list of test cases into TestRail, and that combined with our e2e and unit testing would cover the question asked in the original description for this ticket.

@lenaecb Should we close this now?

**Comment by lenaecb** [comment]
This is being finalized in Testrail test case collection. Business logic documentation will also be part of a different ticket that should account for some of the front end behavior and team member onboarding.
