### ISSUE TITLE
Create downtime notification for vets-api downtime

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#4700]
# Backstory / User Story

There will be scheduled maintenance on vets-api soon and again in the future.

We want to notify users/visitors that there's upcoming or in-progress maintenance on our main API.

Our plan currently is to use a promo banner (https://design.va.gov/components/promo-banners) that will have 4 states based off a config file that has the following timestamp key-value pairs:

`downtimeForewarnStart`
`downtimeStart`
`downtimeEnd`

# Acceptance Criteria

- [ ] If it's before `downtimeForewarnStart` or after `downtimeEnd`, promo banner does not render.
- [ ] If it's between `downtimeForewarnStart` and `downtimeStart`, show promo banner message (still has yet to be created by Peggy, but will probably be something like "VA services will be down in [currentTime - downtimeStart] (minutes)(hours)."
- [ ] If it's between `downtimeStart` and `downtimeEnd`, show promo banner message (still has yet to be created by Peggy, but will probably be something like "VA services will be down for [currentTime - downtimeEnd] more (minutes)(hours)."

**This will need to be live before EOD Friday.**

## Related Tickets

https://github.com/department-of-veterans-affairs/va.gov-team/issues/4631

## Content for downtime notification
Before downtime
Message 1:
We'll be doing site maintenance on [Date] between [Time] and [Time]. You may have trouble signing in or using some tools or services during this time.

Message 2 (X time from maintenance window)
We’ll be starting site maintenance in [X minutes]. If you’re using our tools or services right now, please sign in or create an account to save your work.

During downtime
Message 3
We’re doing some work on VA.gov right now. You may have trouble signing in or using some tools during this time. If you have trouble, please check back after [downtime end date/time].

**Comment by jenniferlee-dsva** [comment]
@rianfowler ^ could you provide maintenance start-end date and times for us?

**Comment by kelsonic** [comment]
@jenniferlee-dsva That's correct! The code needs to be in production by then - not that the banner is necessarily visible on production at that moment (it would depend on what the `downtimeForewarnStart` is).

**Comment by jenniferlee-dsva** [comment]
^ just added the 3 kinds of sitewide messaging specs (from Slack)

**Comment by peggygannon** [comment]
@kelsonic I want to be sure you saw the updated messages posted in the content ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4631

**Comment by kelsonic** [comment]
@peggygannon Thanks! Cross-posting here on this ticket for visibility:

```
Before downtime
Message 1:
We'll be doing site maintenance on [Date] between [Time] and [Time]. You may have trouble signing in or using some tools or services during this time.

Message 2 (X time from maintenance window)
We’ll be starting site maintenance in [X minutes]. If you’re using our tools or services right now, please sign in or create an account to save your work.

During downtime
Message 3
We’re doing some work on VA.gov right now. You may have trouble signing in or using some tools during this time. If you have trouble, please check back after [downtime end date/time].
```

**Comment by kelsonic** [comment]
@peggygannon @jenniferlee-dsva How many minutes before maintenance starts would you like me to show message 2?

**Comment by peggygannon** [comment]
@kelsonic Jen and I discussed 60 minutes yesterday, but let's have Jen weigh in for the final number!

**Comment by jenniferlee-dsva** [comment]
Yes - 60 minutes count down

**Comment by jenniferlee-dsva** [comment]
^ RE text for that count down message - @peggygannon - can you provide update, per my comment on the content ticket? 
jenniferlee-dsva
commented on Jan 9, 2020
^ @peggygannon RE the 2nd sitewide (X minutes) - could we make the messaging more specific and mention applications that may have started? That's the real concern we want to make folks aware of: if they're in the middle of an app in the unauth state, they need to sign in/create account.

Like this - in brackets - def needs massaging:
If you’re currently ?? [in the middle of filling out an application ??], sign in or create an account [now] to save your work.

@kelsonic FYSA - ^ still in flight.

**Comment by kelsonic** [comment]
I think the text may be a tad long with a promo banner @peggygannon, but this is what I have so far:

![image](https://user-images.githubusercontent.com/12773166/72099332-a673f580-32dd-11ea-8008-47dcab4a4c89.png)

![image](https://user-images.githubusercontent.com/12773166/72099701-65c8ac00-32de-11ea-93a1-39989cc13812.png)

**Comment by kelsonic** [comment]
Could I get the exact date + time for `downtimeStart` and `downtimeEnd` @jenniferlee-dsva?

**Comment by peggygannon** [comment]
@jenniferlee-dsva @kelsonic 
Per https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4631, here's the updated countdown message 


**We’ll be starting site maintenance in [X minutes].** If you’re in the middle of filling out an application, please sign in or create an account to save your work.


@kelsonic please let me know if you need me to trim the messages? 

Also, please use the following format for dates/times: 
Jan. 10 at 12:01 a.m. ET

**Comment by AnneHurley** [comment]
Trimmed versions:
We're doing some work on VA.gov, so you may have trouble signing in or using some tools. If you do, please check back after January 9, 2020.
or
We're doing some work on VA.gov, so you may have trouble using some tools. If you do, please check back after January 9, 2020.

#2: 

**note, on hold as @peggygannon has sent trimmed versions.

**Comment by ncksllvn** [comment]
This is all done, but we created a follow-up to help clean up the logic since we did it on such a time crunch. Follow-up is here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/4757.

**Comment by jenniferlee-dsva** [comment]
@kelsonic and @ncksllvn - before refactoring this, we need to share this with the design system folks to use this way (or not) going forward. (Remember, the original ask was to use the full width global-not-global homepage banner component.) 

I really liked this fall back design solution however, and will propose this as a standard use in the future. @Karak888 fysa

**Comment by ncksllvn** [comment]
@jenniferlee-dsva in the event this comes up again, would the expectation be to render a banner site-wide just below the main navigation? Similar to the homepage banner, but on every page
