### ISSUE TITLE
[SPIKE] What Tech Debt Needs to be Addressed for Travel Pay

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47027]
## Tasks
- Determine what Tech Debt Needs to be Addressed for Travel Pay for the logic tree

**Comment by acrollet** [comment]
We had a good discussion with the FE devs around this and don't see a pressing need to change the router approach. I also dove into our approach with HOCs and I don't see that there's necessarily a better way out there to accomplish the things we're doing. At such time as the repo is upgraded to react-router v6 we could look at using nested routes.
