### ISSUE TITLE
AWS access for Justin Trieu

### ISSUE THREAD

**Issue by justin-trieu** [department-of-veterans-affairs/va.gov-team#47029]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Justin Trieu

### Your Email

justin.trieu@thoughtworks.com

### Team, Role, and Company of the target individual

Virtual Agent Chatobot, Software Developer, Thoughtworks

### Product Manager (PM) name and email

Ian Santarinala, ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Marais, luciana.morais@va.gov

### Desired AWS Access

I need access to RDS to read from the development and staging instances of the vets-api database.

### Access Expiration

ongoing

### Additional Notes

Virtual Agent Chatbot team is storing data in the virtual_agent_access_records table in the vets-api database, to send over to VBA for call center volume analysis. For development and QA purposes, we will need read access to the database to support this work.

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
Unfortunately, we don't grant direct RDS access. Please use your existing SSM access to connect to a `vets-api-worker` instance and interact with the database via ActiveRecord through the rails console using the following command:
```sudo su - -c 'docker exec -it vets-api rails console'```
