### ISSUE TITLE
SOCKS access for Napoleon Kernessant

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#47035]
### Your Name

Napoleon Kernessant

### Your Email

napoleon.kernessant@va.gov

### Your Role and Team

Front End Engineer

### Product Manager (PM) name and email

Darla.VanNieukerk@va.gov

### Product Owner (PO) name and email

Darla.VanNieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1kXskCyrzs+uI19yPKaykl2RwVjG2AVT2ytXLi2+soc+rRFkUMG2FR3CpXGyI1bxTmsKnfQUSeIv6zKarWo9KCkEMzOxjSxyTioGuPVsSBiQkOYa5lHu33nLkoOSeKFthV1XB2juCWhGllmKGJzpc1rQER52QLS0ca1AJUGSyjNKXtNbkbe9kcH3o51bxX617GXixixEzxr872NY4tcNMRVAl5H0OcRrMCebcFMPHKt2brFt1lwv+yHNGLJHrVTX1bH2VQQw06j6MubHdZgUlL5g9QUmjrQYAFfjy4nNb6ui6h78kW7tbYJm6RedwHMU6tpOw78vfnGUaiGY2nolf0L1fFxUJzDEu7DppbwB5vwNwhX10w/n8VWhVeMx2/6V9Fa1EewKc4YE7anzeDGG7JBo9U7fQEVtPtJoUwa6tc6vQ2092iGK1I1MqlqVaeikSTdLYT0WEcM96/tNlESu3bFuQkofg1rPMB4dF/AWdjVG88Tg3hXVI+G+BvL0vLok= nkernessant-c02yj3jmjhd2@Nkernessant-C02YJ3JMJHD2s-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by GcioNapoleon** [comment]
napoleon.kernessant@va.gov, napoleon.kernessant@govcio.com

**Comment by rmtolmach** [comment]
I see napoleon.kernessant@va.gov and napoleon.kernessant@govcio.com listed in the vfs roster. I wonder if the automation doesn't know what to do when there are two email addresses listed. I'm going to edit this request to list your va email and see if it works.

**Comment by rmtolmach** [comment]
That didn't work! I'll create the PR myself.

**Comment by GcioNapoleon** [comment]
Thank you

**Comment by rmtolmach** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy.
