### ISSUE TITLE
Platform Website Footer Support Requests: FY2023 Q1

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47051]
## High Level User Story/ies
As a VFS team member,
I need someone to respond to my support requests I submit on Platform Website,
So I can get the answers I need to questions or the content adjusted accordingly.

As a Platform team content SME,
I need assistance from the Platform Content team to help write content for the Platform website,
So that I know the content is following the style guide and using best practices.

As a Platform Content team member,
I need to review a request to determine whether the feedback requires a SME to update or create new content,
So that we can either triage the ticket to a Platform team SME and/or assist them with writing it.

## Definition of done

- [x] All Platform Website Footer Support Requests in Q4 are triaged to the correct team.

- [x] When needed, assist other Platform teams or content SMEs with documentation writing.

**Comment by annekerr49** [comment]
@vbellissimo - Vicky we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues. Please let me know if you have any questions.

**Comment by vbellissimo** [comment]
Closing this initiative, but a new epic card has been created for this same work in FY2023 Q2.
