### ISSUE TITLE
Adding Joni Chan to DSVA Slack

### ISSUE THREAD

**Issue by heyjoni** [department-of-veterans-affairs/va.gov-team#47064]
# Description

I'm an information architect at Ad Hoc joining as a VA contractor for VA.gov projects. I'd like to request Full Member access to the DSVA Slack instance (joni.chan@adhocteam.us)

I'm requesting Github access so I can work on Github issues for my projects.

## Request
- Please add joni.chan@adhocteam.us as a full member.

VA product manager: Mickin Sahni

**Comment by heyjoni** [comment]
Adding VA Product Manager: @MickinSahni

**Comment by eunicegar** [comment]
Done
