### ISSUE TITLE
After usability research content review from Patient Check In

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#47078]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
Editing for plain language and VA.gov content standards. Specifically, we have made some updates to the travel pay pages that are part of the Patient Check In app. The travel pay pages within the Patient Check In app are not yet live. The content updates are a result of receiving feedback from Veterans as part of a [recent research study](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/163).  

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
TBD
  
## When do you expect to launch your product to 100% of users?
  
TBD
  
## Supporting artifacts

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test/research-plan.md)
- [User flow (specifically, Prototype D)](https://app.mural.co/t/vfscie8528/m/vfscie8528/1658844568873/93ba988aed6312d43533b8feaed365529b836332?sender=u83bc52d7fa73658f84f27755)
- [Research synthesis Mural](https://app.mural.co/t/vfscie8528/m/vfscie8528/1661533294973/772d372cc95132227efcf5b3391ed1a02e41e7df?sender=u83bc52d7fa73658f84f27755)
- Initial prototypes: [A](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/prototype/a/19E0B04F-D95E-4CC1-B15A-543FF487AA3E) and [C](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/prototype/a/E3C109B2-DA3E-46CD-8A98-52C09ADD1944)
- [Updated content based on research synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/files/9578982/Travel.Pay.Pages.09.12.2022.1.docx)
- [Quantitative Veteran research participant responses .xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9584789/PCI.Travel.Reimbursement.Research.Participant.Responses.xlsx)
- [Updated content based on research synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/files/9584788/Travel.Pay.Pages.09.12.2022.docx)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: First week of November, 2022
- Estimated staging review date: October 15
- Content and IA work needed by: September 21 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [x] Yes, health content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

## About your team

- Team name: Patient Check In
-	OCTO-DE product owner: Stephen Barrs, Mark Dewey
-	Product manager: Lori Pusey 
-	Designer: Zach Park, Ben Brasso 
-	FE engineer: 
-	Product/team Slack channel: check-in-experience

**Comment by benbrasso-agile6** [comment]
[Updated content document](https://github.com/department-of-veterans-affairs/va.gov-team/files/9578989/Travel.Pay.Pages.09.12.2022.1.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @benbrasso-agile6! Thank you again for the great call last week to go through the research findings and updated content. I think the research-based changes will really help. 

Here are my edits to the updated content, with comments explaining reasons for edits beyond just VA.gov content style. Feel free to reach out with any questions. Thanks!

[Travel.Pay.Pages.09.12.2022_dt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9608233/Travel.Pay.Pages.09.12.2022_dt.docx)

**Comment by benbrasso-agile6** [comment]
Looks great, @DanielleThierryUSDSVA. Thank you so much!
