### ISSUE TITLE
[09/16/2022] Draft Email with Bivalent and Flu Shot Update

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#47081]
- [x] Include an update on the message templates for COVID booster shots to include bivalent in the template (it is the only approved booster now). Alert sites that the template includes that verbiage

- [ ] Update Users that the flu shots can be advertised in the COVID message templates

- [ ] Reviewed by Justin & Shane

- [ ] Email out

**Comment by lindsay-insco** [comment]
Edits being implemented
