### ISSUE TITLE
PROD: 503 Error When Accessing Request from the "Requested" Queue 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#47099]
## What happened?
We observed this issue while doing round 4 of VAOS and HSRM integrating validation in production with Alaska (pilot). Though appears to only be an intermittent problem. Please find below the steps listed: 

## Steps to Reproduce

- User logs into VAOS (as a CC eligible test user)
- Follow the steps to enter a new CC request by filling out the requested fields 
- Click on "Request appointment"
- A new request will be created. Validate on request details page the fields are displayed as entered previously
- User navigates back to the VAOS home page and access the "Requested" queue 

**Expected Results:** System displays the list of requests 

**Actual Results:** System displayed “We’re sorry. We’ve run into a problem. We’re having trouble getting your appointment. Please try again later” and dev tools displays 503 error. Upon reloading page, 503 error no longer displayed.  Validated request details in HSRM and VAOS in synch.       

**Request URL:** https://api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2022-05-16&end=2022-09-14&statuses[]=proposed&statuses[]=cancelled      

**Response:**    
{errors: [{title: "Service unavailable",…}]}   
errors: [{title:   "Service unavailable",…}]   
0: {title:   "Service unavailable",…}   
code: "503"   
detail: "An outage has been reported on the VAOS since 2022-09-13 17:09:28 UTC"   
status: "503"   title: "Service   unavailable"

Notes from Thomas - "Update from Thomas - “VAOS-Service had no errors. MAS had an error log for the ARS problem, but MAS was handling the error properly and returning the appointments it got. For some reason the front end was triggering their circuit breaker causing 503 error. Simi is currently investigating the issue.”

Simi reaching out to platform support team - Please access this chat link to get more details "https://dsva.slack.com/archives/CBU0KDSB1/p1663167828777869"

Please find the screenshot below:

![image](https://user-images.githubusercontent.com/69315717/190306850-eaad3fe3-3196-406f-ae52-609488e6d6c1.png)

**Comment by aarathi-poldass** [comment]
**Platform support**
APP [Today at 11:03 AM](https://dsva.slack.com/archives/CBU0KDSB1/p1663167828777869)
From 
[@Simi Adebowale](https://dsva.slack.com/team/U035E1CTQ20)
: I’m trying to dig in to this issue we’re seeing in prod. We're not seeing any errors in the vaos-service logs so we're not sure what's triggering the 503.
{errors: [{title: “Service unavailable”,…}]}
errors: [{title: “Service unavailable”,…}]
0: {title: “Service unavailable”,…}
code: “503"
detail: “An outage has been reported on the VAOS since 2022-09-13 17:09:28 UTC”
status: “503"
title: “Service unavailable”
https://api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2022-05-16&end=2022-09-14&statuses[]=proposed&statuses[]=cancelled
See less
Request Type: [va.gov](http://va.gov/) - Incident
Assigned to: 
[@Eric Boehs](https://dsva.slack.com/team/U01AAA2QX4P)
 (Console Services Team (Backend))
:eyes:
1

26 replies

Platform support
APP  [13 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663167829335809?thread_ts=1663167828.777869&cid=CBU0KDSB1)
:page_facing_up:  We found some documentation that may help.
:point_right:  [Incident management](https://depo-platform-documentation.scrollhelp.site/support/incident-management)
A support representative will respond shortly.
Did this help?
"No" response recorded
Thank you for your feedback!


Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663168533207799?thread_ts=1663167828.777869&cid=CBU0KDSB1)
[@Kerry Powell](https://dsva.slack.com/team/U032Q8WCBAR)
 I reassigned this to you. I’m not sure how Infrastructure could help.


Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663169187334429?thread_ts=1663167828.777869&cid=CBU0KDSB1)
[@Simi Adebowale](https://dsva.slack.com/team/U035E1CTQ20)
 is it back up? I see a 401 Not authorized error when I go to that link.


Simi Adebowale
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663169363343529?thread_ts=1663167828.777869&cid=CBU0KDSB1)
You will need to be authorized to access this endpoint as it's used to fetch health appointments for users. We got the 503 yesterday during our production test
:+1:
1



Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663169615861009?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Where are you seeing that error message you included in your support request? You see it when you hit that endpoint?


Simi Adebowale
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663169662206939?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Yes, we saw it when we hit that endpoint


Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663169864704539?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Do all calls to any https://api.va.gov/vaos/v2/appointments... endpoints result in the same error?


Kerry Powell
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663169978298889?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Reassigned to console services, they will be able to help with vets-api. 
[@Eric Boehs](https://dsva.slack.com/team/U01AAA2QX4P)
:thank_you:
1



Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170356515049?thread_ts=1663167828.777869&cid=CBU0KDSB1)
I can help troubleshoot but a 503 would be from the fwdproxy which Infra maintains.
:eyes:
1



Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170436749699?thread_ts=1663167828.777869&cid=CBU0KDSB1)
oh, okay. Didn’t realize 503s would be from fwdproxy. I was just seeing 502 errors /vaos/v0/appointments in [datadog](https://vagov.ddog-gov.com/apm/services/vets-api/operations/rack.request/traces?query=%40_top_level%3A1%20env%3Aproduction%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%28%22VAOS%3A%3AV0%3A%3AAppointmentsController%23cancel%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentsController%23index%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23index%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23show%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23create%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentsController%23create%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentsController%23show%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23update%22%29%20-status%3Aok&env=production&spanID=2883378072210330652&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28search%3Aresource_name%253A%2528%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523cancel%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523index%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523index%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523show%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523create%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523create%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523show%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523update%2522%2529%2520-status%253Aok%29%2Cversion%3A%210%29&start=1663166535709&end=1663170135709&paused=true) but I don’t think that’s helpful.


Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170458086709?thread_ts=1663167828.777869&cid=CBU0KDSB1)
The 503s were from yesterday
:white_check_mark:
1



Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170467844169?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Simi is troubleshooting something from yesterday not today.
:white_check_mark:
1



Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170474746019?thread_ts=1663167828.777869&cid=CBU0KDSB1)
https://vagov.ddog-gov.com/apm/resource/vets-api/rack.request/4df6195f5505a4e3?query=env%3Aproduction%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%22VAOS%3A%3AV0%3A%3AAppointmentsController%23index%22&env=production&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&start=1663087753926&end=1663098747167&paused=true


Simi Adebowale
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170488990409?thread_ts=1663167828.777869&cid=CBU0KDSB1)
it was just that specific endpoint. After refreshing the page though, the endpoint returned the expected response. It appears to be an an intermittent problem but we just want to understand why this happened
:+1:
1



Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170571354929?thread_ts=1663167828.777869&cid=CBU0KDSB1)
It looks like starting around 2pm ET to 3:30p ET there were intermittent issues with approximately 13% of the traffic to that endpoint failed with a 503.


Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170648422159?thread_ts=1663167828.777869&cid=CBU0KDSB1)
[@Rebecca Tolmach](https://dsva.slack.com/team/U02SN5US7LK)
 Can you see how many fwdproxy instances were running at that time? (edited) 
:eyes:
1



Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170665309619?thread_ts=1663167828.777869&cid=CBU0KDSB1)
I suspect if there were 8, we had a problem with one of them as 100/8 = 12.5%.


Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170737899649?thread_ts=1663167828.777869&cid=CBU0KDSB1)
I’m completely unfamiliar with the fwdproxies though. Are they running haproxy? Could they each be running two instances of haproxy or something like that? Is it nginx? (edited) 
:eyes:
1



Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663170954024679?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Four is the desired. At 4:25pm ET yesterday they started scaling up. It made it to seven instances at 4:40 and was back down to four instances at 5:10.


Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663171000761539?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Yeah. What I don’t understand though is that:
A) 85%+ of the requests worked
B) Only VAOS had problems. All other endpoints during that period were unaffected.
:thinking_face:
1



Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663171051552059?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Do we have stats from the fwdproxies about completed connections?


Eric Boehs
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663171105172529?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Because it feels like either there was intermittent connectivity issues between AWS GovCloud and VAOS or completely connectivity failure between a single fwdproxy instance and VAOS.


Rebecca Tolmach
  [12 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663171211304319?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Are they running haproxy? Could they each be running two instances of haproxy or something like that? Is it nginx?
Yes, vagov-fwdproxy leverages haproxy under the hood. I’m not sure about the other questions.


Lindsey Hattamer
  [11 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663174262428859?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Could we dig into stats from the fwdproxies about completed connections? That may be a good metric and info to start with


Lindsey Hattamer
  [7 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663187217382579?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Placing some notes here:
It appears that there was some latency issues coming from the va_mobile downstream service around the time that the 503s were reported. See [last graph on the page here](https://grafana.vfs.va.gov/d/000000032/forward-proxy?orgId=1&var-data_source=Prometheus%20(Production)&var-interval=1m&var-backend=va_mobile_back&var-server=All&var-code=All&var-frontend=All&from=now-2d&to=now). Looks like there were some timeouts occurring, resulting in the breaker tripping and that's why the sentry errors show: "An outage has been reported on the VAOS" 
Seeing lots of [504 timeout errors here](https://vagov.ddog-gov.com/apm/services/vets-api/operations/rack.request/traces?query=%40_top_level%3A1%20env%3Aproduction%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%28%22VAOS%3A%3AV0%3A%3AAppointmentsController%23cancel%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentsController%23index%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23index%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23show%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23create%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentsController%23create%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentsController%23show%22%20OR%20%22VAOS%3A%3AV0%3A%3AAppointmentRequestsController%23update%22%29%20-status%3Aok&env=production&spanID=2129754482546006674&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28search%3Aresource_name%253A%2528%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523cancel%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523index%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523index%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523show%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523create%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523create%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentsController%2523show%2522%2520OR%2520%2522VAOS%253A%253AV0%253A%253AAppointmentRequestsController%2523update%2522%2529%2520-status%253Aok%29%2Cversion%3A%210%29&start=1663005625880&end=1663178425880&paused=false), which triggered the breaker


Rebecca Tolmach
  [6 hours ago](https://dsva.slack.com/archives/CBU0KDSB1/p1663190544792039?thread_ts=1663167828.777869&cid=CBU0KDSB1)
Thanks for the notes and feedback. Haven’t forgotten about this thread. Will pick it back up tomorrow.
Some of my notes: Looks like new fwdproxy instances are spun up each day around 4pm ET so I’m not able to SSM into those instances from yesterday. I was poking around datadog looking for the right metrics to pull and came up with [this graph](https://vagov.ddog-gov.com/metric/explorer?start=1663090200000&end=1663101000000&paused=true#N4IgNghgng9grgFxALlADxQRgDQil3AdwEsATBACwJAoFNiBzCpZTAX11NoDNiA7YgmIw+KUAigAHWihBCAtrQDOtAE7FlIXKtoBHOMoRKUAbVA6lkkSoD63GKvkQWc4opXrNufWo3HkZiB8EIqyPqpQAExaIKTOEDZK8KoAxjLIIIoI6inG3gYRskpw8sgUEJKqMGhQAHQARhApANa0fKS1KSJ8tClCIrVqVapKtQgwCBBgwFySYDBQinwINsGKyNyEpJXVUGy1EEo2XXDLABQAlCAcoGvpIOFQAMwxcZOJyWmyWTl5DwX4DLFUrlHY1BpNVrtTrdXr9PgHBAIWjySRGMYTKYzWhzBZLFZ3DZbMF7A5HE7nK5sAC6uHsjjgkH8gXp8kZEDCAMiAAIAPTcx5PbkAKm5mAADOLrrSQEoJGB0qBJFNaEj7qQYAxjkylMQUjEwPxaDYJNIijBDaQDUabCRyFQMnwHE4wNdOMRLJAoCapPdGiNpWw2EA). I’ll double check on those metrics tomorrow.

**Comment by aarathi-poldass** [comment]
I have opened this ticket to track the 503 error in prod. cc @simiadebowale @ldelacosta

**Comment by marcynadeau** [comment]
@ldelacosta This can be closed.  
That issue was verified as fix in production. And then a couple days later we ran into this one same issue but now a different cause:  VAOSR-4394 - HSRM: Implement request logger for all calls to HSRM IN PROGRESS.  Update from Thomas:  Our client was failing to deserialize the response from HSRM due to the json response format being invalid. The json that Moshe showed yesterday during the call looked correct though, so I don’t know why it would be failing to deserialize if it was properly formatted so I put in a story  to rewrite our client code so that we do the deserialization in our service code instead of relying on Jackson to do it for us in our client.

**Comment by ldelacosta** [comment]
No VAOS FE issue reported. Closing out the ticket.
