### ISSUE TITLE
CT 116: Remove Feature Flag for VETTEC programs filter	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4709]
As a developer, I need to remove the feature flag for VET TEC programs filter after the feature goes live because it will no longer be used after than point. 

## Assumptions:
1. EDU has reviewed the VET TEC programs filter functionality and has signed off as of [TBD].

## Acceptance Criteria:
1. The VET TEC programs filter feature flag has been removed and is available in production.

## Supporting Artifacts:
1. Original story to implement functionality: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4032
2. Original PR to implement functionality: https://github.com/department-of-veterans-affairs/vets-api/pull/3605

## PR
https://github.com/department-of-veterans-affairs/vets-api/pull/3759
https://github.com/department-of-veterans-affairs/vets-website/pull/11488
https://github.com/department-of-veterans-affairs/vets-api/pull/3788

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11488
https://github.com/department-of-veterans-affairs/vets-api/pull/3788

**Comment by delli-gatti-michael** [comment]
Changes are now in Production. Closing this issue
