### ISSUE TITLE
Design System upgrade to USWDS v3. Phase 1: pilot with check-in team

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#47102]
**Summary**
The DST will focus on an initiative in Q4 2022 to begin upgrading the Design System to USWDS v3. The work to be done will include upgrading DS web components and developing a plan to upgrade the vets-website and content-build repositories to use the new USWDS v3-based CSS class library. 

**Problem Statement**
Our long-term vision for the VA Design System includes consuming resources from and collaborating on the US Web Design System (USWDS).

VA.gov is currently built using v1 of the US Web Design System (USWDS), which is at this time considered a dead branch. While the site has been maintained by the VA, we have not been able to take advantage of the bug fixes and design improvements made in v2 and the recently-released v3 of USWDS. We’d like to be able to update to v3 and also take advantage of the components that have been released as part of USWDS.

Of the 60 components between the 2 systems (USWDS and VA.gov Design System ) there is the following breakdown:

USWDS components total: 45

VA components total: 41

Shared components between the 2 systems: 26

By doing an audit, we determined that 32 of the USWDS components are either more mature than our component or the VA lacks that component. Mature here means that their version has more functionality, more variations, better guidance, etc. VA has 16 more mature components and we have parity with USWDS on 12 components.

We spent Q3 building out a new CSS class library based on USWDS v3 utility classes, along with a new token library defining basic styles for VA.gov. We need to do some more discovery and outline a plan for upgrading the vets-website and content-build repositories to use this new library, which would remove our dependence on a dead branch of USWDS and allow us to take advantage of future USWDS improvements and bug fixes.

We also need to continue our work to deprecate the rest of our Design System React components. Deprecating these components will reduce the size of the component library package, improving performance, and it will allow us to reduce our dependence on the old USWDS v1-based CSS class library (also known as Formation).

How might we initiate a collaboration with USWDS so that we are sharing component code with their team? 

How might we upgrade the VA Design System to v3 of USWDS with minimal disruption to the teams building on the VA.gov platform?

How might we continue to deprecate the VA Design System React components and encourage frontend teams to use VA Design System web components instead?

## Product Outline
Design System Product Outline
https://vfs.atlassian.net/l/cp/uHW8pif4

## High Level User Story/ies

- As Design System Team member who is responsible for updating and maintaining the VA Design System, I want work collaboratively with USWDS so that we can contribute to each others' Design Systems. 
- As a Design System Team member who is responsible for updating and maintaining the VA Design System, I want to provide the most up-to-date version of USWDS, which is the foundation of our DS, to VFS teams to use when building VA applications.
- As a Design System Team member who is responsible for updating and maintaining the VA Design System, I want to reduce the size of our component library package and and reduce our dependence on the old USWDS v1-based CSS class library.

## Hypothesis or Bet
- If we can modify 1 or 2 of the VA Design System web components to better match their USWDS v3 equivalents and use USWDS resources, such as importing the USWDS component SASS, we can convince USWDS to accept our web components as contributions to their forthcoming web component library. Then we could consume those components from USWDS instead of maintaining them on our own.
- If we can come up with a plan to upgrade the vets-website and content-build repositories to use the new USWDS v3-based CSS class library with minimal disruption, we can speed adoption of the new library and reduce the size of the VA Design System CSS package, thereby improving performance.
- If we can continue to deprecate (and delete) Va Design System React components, we can reduce the size of the component library package and reduce our dependence on USWDS v1-based resources.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
We will know we’re done when we have done the following:

1. Develop a draft contribution back to USWDS
- Discuss an agreement with the USWDS team whereby they would accept contributions of web components from us to the USWDS at some point in the future.
- Work with the USWDS team to determine the details of what a web component contribution to USWDS would entail.
- Develop a test contribution of web component code to USWDS.

2. Upgrade 1 or 2 web components to USWDS v3 (specific web components to be identified)
- Sync Sketch library assets with USWDS Sketch library assets for the components
- Review and reconcile or update user guidance 
- Review and reconcile or update a11y guidance 
- Review and reconcile any colors or typography differences
- Develop a version of the web component that uses USWDS SASS and has equivalent functionality.
-- Release this version of the web component alongside our current version.
-- Identify and work with frontend teams to test new component versions

3. Develop plan to upgrade the vets-website and content-build repositories to use the USWDS v3 CSS class library

4. Deprecate >5 React components

**Known Blockers/Dependencies**
- VA Design System is on USWDS v3 
- Agreement from USWDS
- Frontend teams will need to update their applications to use web components instead of React components

**Projected Launch Date**
End of Q4 2022

**Comment by humancompanion-usds** [comment]
20 of 47 items have been completed. We're behind due to team turn over.

**Comment by caw310** [comment]
Closing as we changed to create a demo application. https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1545
