### ISSUE TITLE
Edit copy for DS Login and Disable login buttons

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#4711]
Edit copy for DS Login - Brooks
Disable Login Buttons for DS Login during downtime - Brook

Text for Login Modal

During downtime
**You may have trouble signing in or using some tools or services**
We’re doing some work on VA.gov right now. We hope to finish our work by [Date/Time]. If you have trouble signing in or using any tools or services, please check back after then.

**Comment by bkjohnson** [comment]
This is what it looks like:

![image](https://user-images.githubusercontent.com/2008881/72109646-2bb1d700-32eb-11ea-9af4-0dc176432c96.png)

The buttons are disabled even though some don't look like it.  When the cursor hovers over it doesn't change to indicate that the buttons are clickable.

Also, I assume we want the downtime end date formatted more nicely.  How should that look?
