### ISSUE TITLE
10-10EZ Self-Identifying Gender Identity - PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#47110]
\[**Product Managers**: Open this ticket **at least 2 Sprints (4 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [PTEMS-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

## Product/Feature summary

A new page is being added to the existing 10-10EZ form to ask the applicant to indicate their self-identified gender. An additional information accordion was also added to the page for context around this optional question. Applicants can be either authenticated or unauthenticated to access this application. This page will be the same for both.

- [Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Self%20Identifying%20Gender%20Identity%20(SIGI))
- [Feature Epic](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/25410)
- Feature Copy deck(s): In Design
- [Feature Design prototypes](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/KvjzaoV)

## Product-team SMEs

\[For any Practice-areas worked by 2+ team-member, clarify who specifically is assigned to this initiative/project.  Leave blank for other areas.\]

Design/Research: Jessica Stump
Content/IA: Jessica Stump and Danielle Theirry
Front-end: Matt Long
Back-end: Lihan Li
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-users must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

[Link to **Use Cases doc**](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Self-identifying-Gender-Identity.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?) - **Set Sprint to target 10/18 for QA completion (a bit flexible if needed)**
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Added product-specific label (if any)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod environment].
- [x] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

**Comment by markfallows** [comment]
Should this still be in the Icebox?

**Comment by tlei123** [comment]
@hdjustice @markfallows , test-runs now completed.  

100% passed &mdash; no defects logged.

QA-artifact links:

- [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/3565)
- [Test cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=6050)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/378)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/379)

**Comment by hdjustice** [comment]
Thank you @tlei123 !! That is great news!

**Comment by hdjustice** [comment]
Closing all SIGI tickets - There has been no further movement or discussion on this topic
