### ISSUE TITLE
[BUG][FE] CHECK-IN: Go to another appt link bug - Single Appointment

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#47135]
## Description 

On staging, I created one appt. Then, I went to check in for that appt. I completed check in. Then, I clicked the "Go to another appointment" link. It took me back to my appts list. The status did not update for my appt. It still had a button for "Check in now." 

1. This seems to be a bug. 

2. What's the intention of the "Go to another appointment" link? Is it intended to link back to the appt list? If so, should it work like, "if the Veteran has more than one appts that day, then show the link. If not, don't show the link."

**Comment by loripusey** [comment]
@benbrasso-agile6 I did this scenario in staging and, for me, it removed from the list each appointment as I checked into them. Not sure this is the behavior we want. I think UX should talk about how it should work. While I didn't get the bug that you reported, I don't like the fact that the checked-in appointments just disappear from this list either.

**Comment by benbrasso-agile6** [comment]
Could you elaborate just a bit on the use case you're experiencing? For example, I was testing 1 scheduled appointment. Am I correct that you're describing multiple appts on one day? And, you're saying that you checked in for 1 appt, went back to your appointment list, and it disappeared? If so, that would be a separate bug. In our product guide, it demonstrates what an appointment should look like if it's already been checked in.

**Comment by benbrasso-agile6** [comment]
I will retest the bug I reported

**Comment by loripusey** [comment]
I'll retest tomorrow, I've got a bunch of appointments today and some the tool won't let me cancel.

**Comment by benbrasso-agile6** [comment]
I go to check in for one appt 

<img width="632" alt="Screen Shot 2022-09-27 at 9 34 58 AM" src="https://user-images.githubusercontent.com/101129355/192541208-db5d214c-e401-4076-9747-29af7478c515.png">

I'm checked in 

<img width="581" alt="Screen Shot 2022-09-27 at 9 35 05 AM" src="https://user-images.githubusercontent.com/101129355/192541271-334761ea-1621-4462-a449-bc6b9905369f.png">

Then I click go to another appt

<img width="761" alt="Screen Shot 2022-09-27 at 9 35 11 AM" src="https://user-images.githubusercontent.com/101129355/192541364-ebda4aa3-c5cf-4d65-8871-5871f1bedeee.png">

The appt was NOT updated. According to the product guide, the appt should look like

<img width="441" alt="Screen Shot 2022-09-27 at 9 35 51 AM" src="https://user-images.githubusercontent.com/101129355/192541451-7ddc747b-d4de-4b60-b157-1933b26e7f17.png">

The resolution that UX discussed was remove the "go to another appt" link when there's only 1 appt.

**Comment by loripusey** [comment]
Makes sense, I'll create a new bug for the behavior I see when there are multiple appointments.

**Comment by benbrasso-agile6** [comment]
I ran into another issue. I had two appts scheduled. I checked in to one. I clicked the link to Go to another appointment. And, the appointment that I checked into was no longer there. According to our product guides, that appointment should still remain in the list. Is this a bug or do we need to update product guides?

**Comment by loripusey** [comment]
I ran into that at well and thought that that was the intended functionality; maybe requires a discussion to confirm

**Comment by kristenmcconnell** [comment]
We came up with the different statuses on the appointments page, so the Veteran would be able to get an overview of the entire day's appointments if and when they got to that page. They should be able to see that a previous appointment was checked into.

**Comment by loripusey** [comment]
that is not what is happening, I'll log a bug to fix it

**Comment by loripusey** [comment]
Can someone point me to a wireframe that shows this scenario with the appropriate message? @zach-park @benbrasso-agile6 @kristenmcconnell

**Comment by benbrasso-agile6** [comment]
The source of truth that I use for reference is the [product guides](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product/product-guides)

**Comment by loripusey** [comment]
@benbrasso-agile6 we need to have a conversation about this; please include @brianseek  and @zach-park

**Comment by benbrasso-agile6** [comment]
Meeting invite sent
