### ISSUE TITLE
Determine support categories we handle

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47134]
AC:
- [x] Think of different support types that we've handled via Slack (you can review the Slack history on both of our channels #platform-confluence and #platform-content to see what customer have reached out to us about)
- [x] Share a preliminary list in #content-chats slack
- [x] Document categories in Confluence: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2401239503/2022+Q4+Include+Platform+Content+into+Slack+Support+Bot

For example:
- break/fix issue 
- content suggestions
- new content provided

**Comment by laucon** [comment]
A few comments:
1. What does I/A mean? Will people know what I/A means?
2. This is me being a little nitpicky, but would it be more consistent to say:
"Updating documentation
Writing documentation
Editing documentation
Providing feedback for documentation"
3. I'm a bit unclear what you mean when you say "(how to do the things people would like to do)." What does that mean?
Otherwise, I think it's a great list. :)

**Comment by amygoldman** [comment]
Thanks for your feedback, Lauren! It's really helpful. Here's an updated version...

Platform website documentation
- Writing Platform website documentation
- Updating Platform website documentation
- Editing Platform website documentation
- Providing feedback on Platform website documentation 
- Providing information architecture (I/A) feedback on a document or a set of documents

Platform website deployment
- Deploying the Platform website
- Reviewing new or recently updated documentation for launch-blocking issues
- Troubleshooting (e.g. identifying why documentation didn’t deploy)

Confluence and Scroll Viewport
- Educating users about using Confluence and Scroll Viewport
- Maintaining the Scroll Content Quality linter 
- Troubleshooting technical issues
- Researching and testing capabilities

**Comment by SSimmorins** [comment]
list looks very comprehensive. I had the same question Lauren asked about "how to do things"

**Comment by vbellissimo** [comment]
Sidenote idea: Add guidance of support types to support categories DURING socialization, announcements, etc.
