### ISSUE TITLE
Add downtime notification for remaining forms

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#4713]
Add downtime notification for remaining forms

**Comment by cvalarida** [comment]
Moving this into Ready since...uh...I haven't been doing it? And it's not come up as a priority?

Happy to pick it up if it is priority, though.

**Comment by rianfowler** [comment]
we're not sure how we want to implement this yet - it might be not added to "existing forms" but become a standard behavior across the entire platform.
