### ISSUE TITLE
AWS STAGING: Var Res (v0) not displaying clinics for direct scheduling

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#47131]
![someClinics.png](https://ima![noClinics.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/f3af1b2b-d971-4c73-90a8-b534e4743954)ges.zenhubusercontent.com/5f2d82cd1166696dbe88379c/a9d8682a-0ec6-42b7-a8da-78f68739f441)Summary: When you try to direct schedule an appointment for a v0 patient, the system does not display clinic locations where they are eligible to schedule. This does NOT happen with vaos service (v2). 

To reproduce: 
1. Set Optometry, Nutrition, Pharmacy and Mental Health to Direct Scheduling and request both to Yes, 12 Months. 
2. Log in as test user and attempt to direct schedule for type of care (see list below). 
Expected result: The system displays the list of clinics where the user has had prior appointments. (see screenshot SomeClinics.png)
Actual result: The system only displays a "I need a different clinic" option. See screen shot NoClinics.png. Because the user cannot select a valid clinic, despite being in the direct scheduling flow, the only option is to choose "I need a different clinic," which takes them to the request flow. 

Impact: Users on v0 cannot direct schedule and will be redirected into the request flow. 

TEST PATIENTS AND TYPE OF CARE
Patient: ruben.moreno@id.me
Types of care: optometry and pharmacy

Patient: jacobreid.r.iasimone@id.me
Types of care: nutrition and mental health

These are currently the only two patients on v0; they have checked out appointments in the last 12 months in the specified types of care.

**Comment by beth-wodzinski** [comment]
![someClinics.png](https://ima![noClinics.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/051dd27f-6979-4205-bbd9-9a1116ebc976)ges.zenhubusercontent.com/5f2d82cd1166696dbe88379c/b1c13d43-e24c-4ae3-834b-62ce54f95612)

**Comment by beth-wodzinski** [comment]
![noClinics.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/345f8cd2-fcd5-4e0d-828c-94eaccd00f67)

**Comment by beth-wodzinski** [comment]
![someClinics.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/dccf1fb8-ea32-4d30-828a-dbde1868a25c)

**Comment by ldelacosta** [comment]
If V2 is not in production by October, we will work on addressing the issue. Waiting to hear back from the team on the HSRM deployment.

**Comment by ldelacosta** [comment]
This work is combined with #46281. Will let the team know when ticket 46281 is completed. Thanks!

**Comment by jenniemc** [comment]
This defect resolved itself in staging when turning the `featureVaosV2Next` off for the v0 users. I will proceed to turn this feature flag off in staging but enable it for v2 users. 

@simiadebowale, @ldelacosta, @JRRoof

**Comment by marcynadeau** [comment]
@ldelacosta @kay. Recommend closing this defect as this was v0 and VAOS service is going to prod soon.
