### ISSUE TITLE
Define Content Support Triaging and Collaboration Process

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47155]
## Problem Statement 
The Platform Content team owns the Platform website's footer support form. We receive entries from both VFS and Platform team members. The main types of support inquiries we receive from VFS teams are:

- broken or incorrect links
- loose feedback about existing content
- edits to existing content
- suggestions of new content

There are quite a few challenges with our current service processes. Some of them include:

- Depending on the type of support entry, our team (Platform Content) is not fully aligned on how to triage certain website footer support requests.
- When our team triages a request to a SME on another Platform team, the ticket often sits in another team's backlog for a lot longer than if our team were to step in to assist them.
- Other Platform teams do not fully understand our triaging process, therefore the tickets we assign to them might be overlooked or de-prioritized.

**How might we improve our current website footer support requests triaging process to provide a better customer experience to both VFS and Platform teams?**

**How might we expand our services by providing content writing assistance to Platform SMEs?**

## Hypothesis or Bet
If we define an improved collaborative process, set expectations and improve communication with other Platform teams, we will

- better assist them with the content development of technical documentation
- support tickets will be full-filled faster
- Platform teams will be better supported by Platform Content team; and
- VFS team members will be more satisfied with our services.

If we establish better practices, set expectations and improve communication with VFS customers, their customer experience will improve as well.

## User Stories

As a VFS team member,
I want to know my support ticket has been triaged to someone within Platform,
so that I know my suggestions are taken into consideration.

As a Platform team member,
I want to know when and how the Platform Content team can support my team with content requests from VFS team members,
so that my team can work through requests quickly and ensure content style quality standards are met.

As a Platform Content team member,
I want to align when and how to better collaborate in pair-writing efforts with other Platform teams,
so that we can work through requests from VFS team members about content on the website more quickly.

## We will know we're done when... ("Definition of Done")

- [x] The current Platform website footer support triaging process will be re-defined and fully understood by all members of the Platform Content team.

- [x] An additional process workflow will be defined for Platform Content team to support other Platform teams in editing existing content or writing new content for the Platform website.

## Known Blockers/Dependencies 
A potential blocker/risk/dependency might be:

- Our team's ability to successfully identify SMEs in other Platform teams for specific technical documentation. _A suggestion from leadership is that when in doubt, seek help from someone based on the Community of Practice groups (frontend, backend, or devops engineers)._

Other dependencies:

- Agreement from other Platform teams on collaboration process to triage and co-write documentation for the website
- Other Platform teams' capacity to contribute their expertise to new or existing documentation
- Our team's ability to prioritize incoming VFS content suggestions with other technical Platform teams' workload priorities.

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

**Comment by annekerr49** [comment]
@vbellissimo - Vicky we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues. Please let me know if you have any questions.

**Comment by vbellissimo** [comment]
Initiative completed.
