### ISSUE TITLE
Update vets-api makefile

### ISSUE THREAD

**Issue by wunderhund** [department-of-veterans-affairs/va.gov-team#4717]
Silvio asked in this thread in Slack if we could update the makefile with commands to make it easier to make changes to the vets-api code, stopping the container, then rebuilding it with the changes in place to test:

https://dsva.slack.com/archives/C7S6EA0ES/p1578592093044400?thread_ts=1578590220.028300&cid=C7S6EA0ES

@nathanhruby asked for a ticket to remind him of this request.

**Comment by wyattwalter** [comment]
The path for doing this is using review instances. We're not going to support this model going forward.
