### ISSUE TITLE
Add use case to Cypress

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#47178]
## Task

Add screenshots to cypress for the following: 

- Click pre check in link between midnight and appt time on day of appt for an in person visit 
- Click pre check in link between midnight and appt time on day of appt for a phone visit
- Started pre-check-in before 12:00 a.m. the day of the appointment, but pre-check-in is already complete

**Comment by benbrasso-agile6** [comment]
Tagging @loripusey to review next week and drop in backlog

**Comment by brianseek** [comment]
@benbrasso-agile6 After digging in, it looks like we have the first two in `Pre-check-in--expired-error` & `Pre-check-in--Phone-appointment--expired-error`
The third does not have a unique screen, its just the regular pre-check-in complete screen which we have a screenshot for.

I did discover a screenshot we were missing while talking to Zach last week that I added for when there is an error but we know the appointment date. Which also caught an issue where we weren't printing the date out in the Spanish version. Attached are those new screenshots. 
[https://app.zenhub.com/files/133843125/56b62fee-858d-4b23-9392-ad7839e5b3f2/download](https://app.zenhub.com/files/133843125/56b62fee-858d-4b23-9392-ad7839e5b3f2/download)

**Comment by loripusey** [comment]
can this be closed @brianseek ?

**Comment by brianseek** [comment]
@loripusey if @benbrasso-agile6 gives thumbs up, we can close

**Comment by benbrasso-agile6** [comment]
gtg
