### ISSUE TITLE
Update rates for FY 2023 on disability housing grants for Veterans page-HOLD TO PUBLISH UNTIL 10/1/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47183]
## Issue Description
The rates for Special Home Adaptation grants change on 10/1/22. We need to update these numbers on our [Disability housing grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/) page. 

The 2023 rates are (in order of them listed on the page):

$109,986 – (SAH, Section 202)
$22,036 – (SHA)
$44,299 – (TRA)
$7,910 – (TRA)

## Tasks
- [x] Update rates and change mentions to FY 2023 (Aliyah)
- [x] Review (Laura)
- [x] Copyedit (Randi)
- [x] Publish (Randi)

## Acceptance Criteria
- [ ] Live page has 2023 rates

**Comment by aliyahblackmore** [comment]
Hi @laurwill - these 2023 rates (with the updated year) are ready for you to review!

**Noting here what the previous text was and, as [outlined by Randi](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47183#issue-1376476823), that they were added in this order:**

**$109,986 (SAH, Section 202)** - previously $101,754 for FY 2022
**$22,036 (SHA)**  - previously $20,387 for FY 2022
**$44,299 (TRA)** - previously $40,983 
**$7,910 (TRA)** - previously $7,318

*One content flag on this page:** 

In the H2 "Grant eligibility for a temporary home," one bullet point uses this sighted language:

"You qualify for an SAH or SHA grant (**see above**)..." 

Wondering if this can be changed and if there is a need to link to the relevant section, could this include a jump link to H2 "Grant eligibility for your permanent home," as this section includes the information on the SAH and SHA grants? 

If a change can be made and a jump link can be included here, proposing that the link language come underneath the bullet point and be along the lines of this: 

**Learn more about the SAH or SHA grant**

**Comment by laurwill** [comment]
Thanks @aliyahblackmore ! 
New rates look good, and these are both great content flags. 
- For "see above," I added the jump link your suggested
- For the cap language, I rephrased that entire sentence to avoid passive voice and "cap" — see update:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/104158104/191313308-168f58ac-fdc8-4833-9efd-849d2410bafe.png">

@RLHecht , this page is ready for you to prepub/pub for 10/1.

**Comment by aliyahblackmore** [comment]
As discussed during 9/22 standup, adding these rates and changes back in and saving as a draft ahead of the 10/1 prepub/pub.

**Comment by laurwill** [comment]
@aliyahblackmore you can go ahead and re-make these changes and save as draft — stakeholders are good with the current eBenefit content on the page

**Comment by aliyahblackmore** [comment]
Thank @laurwill ! This is ready for you, with the rate changes and small tweaks! 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=750

**Comment by megzehn** [comment]
Thanks! Changes look good, and this is now published.

**Comment by RLHecht** [comment]
This is live. Closing ticket!
