### ISSUE TITLE
Authenticated 22-1990e TOE Form URLs from My Education Benefits

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#47200]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [X] IA support
  
Review and approval of the URLs that we will be using for the new version of the authenticated 1990e:

**Application Instructions:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/introduction
 
**Applicant Information:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/applicant-information

**Sponsor information (multiple states):** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/sponsor-information

**Sponsor information - High School:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/high-school

**Sponsor information - High School - Date Received:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/high-school-completion

**Contact Information - Phone/Email:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/phone-email

**Contact Information - Mailing Address:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/mailing-address

**Contact Information - Follow-up Questions/Preferences:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/preferred-contact-method

**Direct Deposit:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/direct-deposit

**Application Review:** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/review

**Application Confirmation (multiple states):** /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/confirmation

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
Jan 2023
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/TOE%2022-1990e%20Updates/TOE%20Product%20Outline.md
- Link to or attach user flows: https://accenturefederal.invisionapp.com/freehand/Design-Intent---User-Flow-TOE-U3BzprxZZ?dsid_h=06a224645241871fa5475824bd7e4ed97d273fcdf1fcb16d2890ca7d8bc61039&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01
- Link to prototype or mockups: https://accenturefederal.invisionapp.com/freehand/Design-Intent---User-Flow-TOE-U3BzprxZZ?dsid_h=06a224645241871fa5475824bd7e4ed97d273fcdf1fcb16d2890ca7d8bc61039&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37551, https://github.com/department-of-veterans-affairs/va.gov-team/issues/37658

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Jan 2023
- Estimated staging review date: Nov 2022
- Content and IA work needed by: September 30th 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: My Education Benefits
-	OCTO-DE product owner: Matt Self
-	Product manager: Russell Lyons
-	Designer: Leelah Holmes
-	FE engineer: Cesar Santiago
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Hi @rlyons89,  are the labels bolded above the approved H1s for each of the pages in the form flow?  If they are, the only thing I would suggest is to add "sponsor" to the URL path for those 3 pages to be clear who's information you are collecting since it is not the Veteran's.

**Comment by rlyons89** [comment]
@mnorthuis yes, sounds good, we will add in 'sponsor' per your recommendation.

**Comment by btruongafs** [comment]
@mnorthuis do you have any other feedback? if not, can you create the IA Design document to finalize the approval?

**Comment by mnorthuis** [comment]
@btruongafs working on finalizing the IA doc, will post soon.

**Comment by rlyons89** [comment]
Hey @mnorthuis, following up on the IA doc, let us know if we should be looking for it somewhere else, thanks.

**Comment by mnorthuis** [comment]
@rlyons89 Confirming a couple of things with the content team tomorrow and will have things finalized for you shortly after that, sorry for the delay.

**Comment by mnorthuis** [comment]
@rlyons89 Can you confirm that all entry points should be pointed at the new 1990e form, and from there if they choose to continue without signing in, they will be sent to [the "old"  unauth version of the 1990e](www.va.gov/education/apply-for-education-benefits/application/5490/)

**Comment by mnorthuis** [comment]
@rlyons89 Follow up question...I'm assuming visitors could still get to the /introduction page of the existing 1990e, so that content should be updated to the same content as the /introduction page of the new 1990e, correct?

**Comment by mnorthuis** [comment]
IA design found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-1990e-authenticated.md

Please see process flow in the IA design, and let's confirm how we are handling the routing with the existing (unauth version) of the 1990e.  It is possible that links can exist elsewhere in the experience, externally, in search, or in bookmarks. 

FYSA @heyjoni

**Comment by rlyons89** [comment]
Thanks @mnorthuis! We have not updated the content on the existing 1990e introduction page; updates to that page are out of scope for our team to work on. I don't believe the content should match, as there are differences in the information/data needed from the applicant between the 2 versions of the form.

**Comment by mnorthuis** [comment]
@rlyons89 Thank you for the additional background.  Let me know if there are any questions on what I've provided.

**Comment by mnorthuis** [comment]
@btruongafs Since this has been through staging review, are we good to close?
cc @RLHecht

**Comment by btruongafs** [comment]
@mnorthuis yes good to close!
