### ISSUE TITLE
[My VA/Payment Info V2] QA Test Plan

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47208]
\[**Product Managers**: Open this ticket **at least 2 Sprints (4 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.

**See also**: Relevant [PTEMS-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by PTEMS-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
- [Feature Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43332)
- Product/Feature Copy deck(s): [Benefit payment documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md) & [Outstanding debts documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md)
- [Product/Feature Design prototypes](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/rb3RzvK)

## Product-team SMEs

\[For any Practice-areas worked by 2+ team-member, clarify who specifically is assigned to this initiative/project. Leave blank for other areas.\]

Design/Research: Angela Agosto

Content/IA: Danielle Thierry

Front-end: Taylor Mitchell

Back-end: Tom Harrison

QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-users must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

[Link to **Use Cases doc**](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md)

**Staging users are still being added to use case doc**

## How to configure this issue

- [X] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [X] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [X] Added product-specific label (if any)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod environment].
- [x] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

**Comment by ajakabcin** [comment]
Hi @tlei123 we have a few minor issues to resolve on this feature so we're not quite ready for QA to start right away. We're still aiming for the current sprint (84, 10/5-10/18). Does that still work for you? Thank you! cc @ericasauv09

**Comment by tlei123** [comment]
Hi, @ajakabcin !  Please ping me on Slack once everything's ready.

We may have a collision w/ 1010's test-runs but it won't swing by more than 3 days &mdash; hard to say for sure 'cuz Heather just told me earlier this week that they also have some more changes.

**Comment by tlei123** [comment]
@ericasauv09 , all test-runs now completed:

3 defects logged: #48809 , #48810 , #48812 

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3426)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=8197) NOTE: Error-state test-cases were not run [no provided test-users brought up any error-alerts in Staging]

Reports are pending - TestRail's issue with report-generation is still ongoing.  I did start reports-generation, so I'll check TestRail right before Staging Review meeting and provide links if they're successfully created.

**Comment by ericasauv09** [comment]
Thank you @tlei123!

**Comment by tlei123** [comment]
@ericasauv09 , error-states automated test\* results now [posted to TestRail](https://dsvavsp.testrail.io/index.php?/runs/view/4195&group_by=cases:title&group_order=asc).  I'll also add this to our Stg Rvw tic.

\* @tmitchellgcio , the new spec's still in my feature-branch right now.  [As we discussed](https://dsva.slack.com/archives/C909ZG2BB/p1666972650484829?thread_ts=1666965370.889839&cid=C909ZG2BB), a PR-link will be ready for you Monday morning.

**Comment by tlei123** [comment]
@ericasauv09 , Benefit-payments error-states automated test results now also [posted to TestRail](https://dsvavsp.testrail.io/index.php?/runs/view/4202&group_by=cases:title&group_order=asc). I'll also add this to our Stg Rvw tic.

cc @tmitchellgcio

**Comment by tlei123** [comment]
TestRail reports did get generated:

- [Coverage for References (Cases)](https://dsvavsp.testrail.io/index.php?/reports/view/377)
- [Defects (Summary)](https://dsvavsp.testrail.io/index.php?/reports/view/376)
