### ISSUE TITLE
[Bug] Facility Locator - Clicking/tapping map-icon navigates to blank page

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#4720]
## What happened?

On Staging Facility Locator page, after search results loaded for **Washington, DC** search, tapping a map-icon loads a blank page.
**NOTE**: This appears to be intermittent; the first try usually works, but not the next.

## Specs:
- Browsers/Devices: [this bug is browser- and device-agnostic]

## Steps to Reproduce
1. Go to Staging Facility Locator page [https://staging.va.gov/find-locations/](https://staging.va.gov/find-locations/) \[enable/allow geolocation if prompted]
1. In **Search...** textbox, input **Washington DC**.
1. From **Search for** dropdown, choose **VA Health**.
1. Tap/click **Search** button.
1. In **map** panel/tab, tap/click any **map-icon**.
1. Observe blank page -- no location popup appears on map for the tapped icon.

**NOTE**: Bug may not occur the first time you try -- from my testing it appeared to occur only on second or subsequent tries.

#### Win Chrome example
![map-icon-blank-page](https://user-images.githubusercontent.com/587583/72225336-cdcafc80-3541-11ea-979d-bda55bf38fb0.png)

#### iPhone 11 example
![image](https://user-images.githubusercontent.com/587583/72097827-7545f600-32da-11ea-836e-cc95de02d0f7.png)

## Desired behavior
Location popup appears after map-icon click/tap.

## Acceptance Criteria
- [ ] \[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This issue is resolved by the UX changes which has removed map icons

**Comment by tlei123** [comment]
> This issue is resolved by the UX update which removed map icons

@mmiddaugh , I'm not sure exactly which update you meant above, but FYI, just out of due diligence...

This is now fixed on all browsers/devices EXCEPT emulated Android devices on SauceLabs (Samsung S9, S6, & generic Android 8 emulator).

Unless we can find someone with a real Android phone, I think this can remain Closed.

**Comment by brangi** [comment]
@tlei123 - this UI update https://github.com/department-of-veterans-affairs/va.gov-team/issues/4872 will remove the popups when you click on map markers so this bug should not happen after removing those popups.
