### ISSUE TITLE
Remove macro from Dev Docs section

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47204]
Acceptance criteria:

- [x] The "recently updated dashboard" Confluence macro found on this page will be removed: https://vfs.atlassian.net/wiki/spaces/pilot/overview
- [x] The live page will no longer show the list of blue links: https://depo-platform-documentation.scrollhelp.site/developer-docs/

**Comment by laucon** [comment]
It should be reflected after Samara publishes today
