### ISSUE TITLE
K8s settings-configmap syncing

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#47213]
Currently, the [vets-api-server](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api-server) and [sidekiq](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/sidekiq) k8s deployments both have their own settings-configmap files, but they SHOULD hold the same values. We most likely want to create a central/consolidated configmap eventually, but until then, we’ve been trying to keep these manually in sync. We should consider some sort of GHA that diff’s the files and prevents merging if there are differences.

**Comment by laineymajor** [comment]
Add as step for higher environments
