### ISSUE TITLE
[FE] 10-10EZ - Intro Page: Relocate the maintenance alert on the Intro page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#47218]
## Background

Currently, the maintenance alert for the 10-10EZ is nested within another information box at the bottom of the intro page. The alert needs to be moved to the top of the page, consistent with the 10-10CG alert.

<details>
<summary>10-10EZ with maintenance alert at the bottom on the intro page inside another alert</summary>

![image](https://user-images.githubusercontent.com/92328831/191358205-a0029d05-b03c-42ff-b5da-0ab31ddaaa4d.png)

</details>

<details>
<summary>10-10CG with maintenance alert at the top of the intro page</summary>

![image](https://user-images.githubusercontent.com/92328831/191357926-dac45a9c-05fd-47b4-b921-6a7b23a95530.png)

</details>

## Tasks
- [ ] Relocate the maintenance alert to the top of the page, consistent with the look & feel of the 10-10CG

## Acceptance Criteria
- The maintenance alert will be displayed at the top of the 10-10EZ intro page

**Comment by markfallows** [comment]
Ticket will be repurposed.

**Comment by longmd** [comment]
@hdjustice , do you know if we could do maintenance windows in either RI or staging? I'd love to be able to visually verify this when its all ready to go.

**Comment by hdjustice** [comment]
Alert has been updated, and tested in staging
![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/fd2b62b6-5a96-43a6-93fc-abbb2fb208df)
