### ISSUE TITLE
AWS access for Napoleon Kernessant

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#47235]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Napoleon Kernessant

### Your Email

napoleon.kernessant@govcio.com

### Team, Role, and Company of the target individual

React Developer

### Product Manager (PM) name and email

Darla.VanNieukerk@va.gov

### Product Owner (PO) name and email

Michael Napper , Education Chief

### Desired AWS Access

I need access ssh access to EC2 staging, prod EC2 instances to execute the EDU GIDS Institution Builder and Geocoder process :

We run the geocoder script. To do so, you will need to find the instance id of staging-gids or prod-gids in the EC2 Instance search that will show a list of instances, select an instance and ssh.
• Once sshed into instance run “sudo su - -c 'docker exec -it gi-bill-data-service bash'” to bash into the container, “source config/.env.sh” to set the config enviornments. “nohup rake fix_coord_mismatch & exit” tpo start the geocoding task and sudo su - -c 'docker exec -it gi-bill-data-service tail -f nohup.out' to monitor.

### Access Expiration

09/01/2027

### Additional Notes

COR : Riccio, Joseph [[Joseph.Riccio@va.gov](mailto:Joseph.Riccio@va.gov)]

### User must exist in a roster before AWS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
### For AWS Access
User: Napoleon Kernessant
COR: Riccio, Joseph [[Joseph.Riccio@va.gov](mailto:Joseph.Riccio@va.gov)]
VOR: None provided. @GcioNapoleon, please also include your Vendor Onboarding Representative
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no, but please note the request for prod access

**Comment by td-usds** [comment]
I will try K West as the VOR

**Comment by td-usds** [comment]
Reached out to VOR

The request for Staging is fine with me, it's staging after all but...
I have concerns about the requested level of access: it requests access to prod for too long a time and performs administrative operations (`sudo`) on instances in that environment. This is a serious risk.

Can you elaborate why this requires a human?

I would like to - at the very least - have a discussion as to what can be done to either limit the scope of the request _and_ what the plan of action is to remove the need for a human in this loop that spawned this request.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by GcioNapoleon** [comment]
Please let me know if you need me to do anything

**Comment by GcioNapoleon** [comment]
Please approve my staging access and we can cancel the prod access.

**Comment by td-usds** [comment]
@markkvba confirmed that issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/37944 is being tackled with high priority and is the first issue they will be working on.
Access for @nfstern02 approved for 2 months; based on the conversation with Mark, this is sufficient time for now.

**Comment by jbritt1** [comment]
@td-usds, are we able to grant general + lower env access to Napoleon at this time? Or is your note about Noah Stern superseding this request at this time and the thing we are moving forward with currently?

Just want to make sure I am understanding what is / is not being approved at this time.

**Comment by GcioNapoleon** [comment]
Because I'm the team lead I'm just trying to get access to the lower env so that I can understand the process. I don't need production access at the moment.

**Comment by andreahewitt-odd** [comment]
@td-usds ^

**Comment by td-usds** [comment]
Lower environment access is approved, production is not approved at this point

**Comment by ianhundere** [comment]
access no longer needed
