### ISSUE TITLE
eMIS Deprecation

### ISSUE THREAD

**Issue by td-usds** [department-of-veterans-affairs/va.gov-team#47240]
## Problem Statement

Need to validate scope -- Spike/leadership

eMIS (Enterprise Military Information Service) is a system that can be queried in order to enable pre-filling of forms, thus reducing the time to fill in forms. The information that can be pre-filled is military information, status, and payments. It is an external, upstream service to `vets-api` but appears to be/is offered as a shared platform service. eMIS is exposed via a SOAP API available over HTTPS.

This is currently a platform shared service which **had** an intended deprecation date of 2022-09-30. The desire is/was to deprecate by end of fiscal year 2022. This date has been pushed back to the beginning of FY23 (Dec/Jan timeframe).

eMIS is currently used in all sorts of places in `vets-api`, but that also means that this does/should not impact `vets-website`.

There is a thing called 'VA Profile' built by VA Data Analytics Product Line (which is not the same as 'VA Profile within va.gov') that can be used as a replacement for eMIS; it "...provides a single, authoritative source of truth for Veteran data across all VA systems".

So the matter is really about: replace eMIS with "VA Profile" (the one referred to above) and what is involved in terms of effort and impact.

We would like to scope our work for this particular task as narrow as possible to just the prefill functionality, and not branch out too much into other things that eMIS does. We also need to come up with a solution for what we do with 'those other things'? Just turn them off? For this, we need to identify the places where eMIS is called and find out who owns that code.

## User Impact

Based on a 1 week timeframe, 51k veterans used eMIS-driven pre-fill.
If we do not provide a replacement functionality, these users will no longer benefit from the pre-filling functionality.
If we instead utilize 'VA Profile', the functionality will remain at least to a certain extent (based on the information available in VA Profile).

## Where was this problem reported?

Driven by internal VA roadmap of eMIS deprecation.

## How well do we understand the problem?

CST has done extensive research on this subject:

- https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation
- https://vfs.atlassian.net/wiki/spaces/~6193f2d9ebce470067aebefd/pages/2231959560/eMIS+Deprecation+Tracker#Action-Item-Tracker
- the sensitive repo contains more information on this as well

### Related Issues

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/43745
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/43602

## What is the acceptance criteria?

TBD: we need to define how we want to deal with the deprecation before this question can be answered:
1. Eliminate eMIS without replacement
2. Replace eMIS functionality with pre-fill from VA Profile

## How should we measure success?

TBD: this also depends on our decision of which avenue(s) we take.

## TODOs
- [x] Convert this issue to an epic

**Comment by andreahewitt-odd** [comment]
@mchelen-gov @raywangoctova Hey I saw an August 15, 2023 date thrown around for eMis deprecation this week.

**Comment by andreahewitt-odd** [comment]
@mchelen-gov @raywangoctova Hey I saw an August 15, 2023 date thrown around for eMis deprecation this week.

**Comment by LindseySaari** [comment]
We may be able to [build off of this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/11858/files). It seems that other teams are currently migrating to VaProfile

**Comment by laineymajor** [comment]
Closing this epic and will continue to monitor then delete old code. We have the appropriate tickets outlined for this subsequent work.
