### ISSUE TITLE
SOCKS access for Steve Dickson

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#47247]
### Your Name

Steve Dickson

### Your Email

sdickson@greenthreadsllc.com

### Your Role and Team

Lead Engineer on Identity Product Team

### Product Manager (PM) name and email

Mike Prusaitis mike.prusaitis@frogdesign.com 

### Product Owner (PO) name and email

John Rahaghi John.Rahaghi@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNYzRKDhLTa46u1rR9PDKeXOE3HF48UpkzOuZqBVSHg42itLUZxPSp4110Pm2Dp6JVwzwd9UGtefuZbaYY94U25DZ5UlQFGY49nDcbtWh79MAyFkjGrtpzY2aAcp304ujxNhVhbf2ur2wMrdoYlL+VZbWhfUvQPYrmDZA681XhD86NvAGLAzFbStTsjNW9w3VV6pxFgK5giCCnbF2VPAOzFpg79yesNGgT7JsTVrJADrNTBn+qRXzGzZPRbXZX9XhI/GIQTthMUAYoUlfnbC45V338KZXONCDBVKro9SMAug0zOy9ELpAzV0s3ExFXEwnV5rJML69HaxifRBbgcvui+Cb1gs3NOfhw/R5O/7ZEGc/M757vWRzDgp4HmI1/QsDXM2qvtlTA/9Cufw0xnw69fV3RB0TUYbvRNHsm6vIyXvxHLiagMf3TsVc5SA+retwTWB71MGnQjqjpsjTbNLPEX3c1JPAFukoPhYAdzIwsQdvCsd14PdxgOtpy8nRQk6E= steve@steves-mbp-2021.lan

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
@sdickson-gt, you are in fact on the roster. The above is an error with our bot that we plan to fix in the near future. Please DM me on the DSVA Slack (Jeremy Britt) at some time tomorrow and let's get your SOCKS access squared away. Apologies for the inconvenience and/or any confusion.
