### ISSUE TITLE
PagerDuty accounts for 10-10 Health Apps team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#47261]
Please make the following changes to DSVA PagerDuty for the 10-10 Health Apps team.

Grant Access:
Heather Justice - heather.justice@adhocteam.us / heather.justice1@va.gov
Mark Fallows - mark.fallows@adhocteam.us / mark.fallows@va.gov
Matt Long - matt.long@adhocteam.us / matthew.long6@va.gov
Lisa Zapson - lisa.zapson@adhocteam.us / lisa.zapson@va.gov

Please reach out to Heather Justice if additional information is needed.

**Comment by hdjustice** [comment]
@little-oddball - Please let me know if this should be assigned to someone else.  We would like to get our team to have access to the Pagerduty, if possible.
Thanks!

**Comment by little-oddball** [comment]
Work has been performed and emails from PagerDuty should have been sent out.

**Comment by hdjustice** [comment]
Thank you Clint!

**Comment by hdjustice** [comment]
@little-oddball - Hi Clint!  In testing a maintenance window in Staging for the services we use (ES and CARMA), we are getting a message that we do not have permissions to do that.  Is there something specific we need to do to get permissions?

**Comment by little-oddball** [comment]
> @little-oddball - Hi Clint! In testing a maintenance window in Staging for the services we use (ES and CARMA), we are getting a message that we do not have permissions to do that. Is there something specific we need to do to get permissions?

@hdjustice Hi, I would suggest making that request in the support channel and will most likely require a ticket. Thank you!
