### ISSUE TITLE
SOCKS access for Jarred Simon

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#47284]
### Your Name

Jarred Simon

### Your Email

jarred.simon@va.gov

### Your Role and Team

Frontend - Veteran Facing Education Services

### Product Manager (PM) name and email

Darla VanNieukerk  darla.vannieukerk@va.gov

### Product Owner (PO) name and email

Darla VanNieukerk  darla.vannieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtekmeDNSrh1jFX2Clx8MpjeKMjN9Ez6Qu4N2//Jt8BVups462IZj5HPdDZDyLZWeWHUKvCvQTX04Q+gVFR1BihBUBaoyNHFSjuehvX6Ulg7a3+gKVhSww2nzyZgZz/YyknWKhI8oKSMZ5+sDAo20ULQgwWnvfMOUr7GLE4MMssDO72vSOaK8vcYZyK/i7Tvy+B5Mvz1QqUv9hB/C76RCgdPkWNqSwv0VQbYsrY9IVXLMq+PluEp7InbRzN/dHivXMTsbqjAdkdbv+wyZGJYkLdetXxOVxzWT0JDcMyOU0o85vszrBywllOsdPy9C6BXo0WE8PRtcQ3D1g6a0sIb9AaaEefO6QwZOXYimycCAg+kJYPMOV034FOB6nBZhZKfEOB2P/gFm25GncCZxE1YThbIPhxrbr/L8+QIUjBE0u5HXduz8i5+nd8QQftLq8b1iQBVHtniNi+1z0rGcR76iJJ+1BTosXNR8FnnjmPjpOddof9iuB8CaLCMCRn3ARUi0= jarred@jarred-VirtualBox

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
@jsimonVA, there is currently a bug in our bot causing this issue. I manually searched for you and located you within the VFS team roster. I will continue processing this request and will get you squared away shortly.

**Comment by jsimonVA** [comment]
I see my email ***@***.******@***.***> in the VFS team roster. Can you check again

Jarred Simon | Front-End Developer
Mobile: +1 (405) 443-0002​
Email: ***@***.******@***.***> | ***@***.*** ***@***.***>
Office Hours: 8am-4pm ET
Connect with VetsEZ: Website<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvetsez.com%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583207196%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DJEaTHkGGzM2SyOJh9bwOiJVxdS2Dlyb6%2Fd5xSEF7AE%3D&reserved=0> | News<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvetsez.com%2Fnews-and-articles-2%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583217146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ILTWxLagnq6nZx20Z7E6seNJhhz1xLpZUQ7i9Dw0hrk%3D&reserved=0> | LinkedIn<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fvetsez%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583217146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yuVUWayRu1FdPau7qfqSyoEBBDn0gwuPorRMlbLBZfg%3D&reserved=0> | Twitter <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FVeteransEZ&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583217146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ArHVgVIvrMuTtzuPxsIenms%2FqrdrE%2BabeSRhFoDQuQg%3D&reserved=0>
***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvetsez.com%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583227106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mEZ0uhCVGnDdxp7ogHXqDvOaMxvp3iOeJSx8nwYBQo0%3D&reserved=0>
**PROPRIETARY and CONFIDENTIAL** This email and any attachments are confidential and/or proprietary and intended solely for the named recipients. Unauthorized use, copying, or distribution is prohibited. If you received this e-mail in error, please notify me by replying and delete the message without copying or disclosing it. Thank you.

From: VA VSP Bot ***@***.***>
Sent: Tuesday, September 20, 2022 1:03 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Simon, Jarred C. (governmentcio Llc) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] SOCKS access for Jarred Simon (Issue #47284)


I was unable to locate your email ***@***.******@***.***>") in the VFS Team Roster or the Platform Roster.

If you’re on a VFS team, please start the platform orientation<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdepo-platform-documentation.scrollhelp.site%2Fgetting-started%2Fguidance-for-new-teams-and-team-members%23Guidancefornewteamsandteammembers-NewVFSTeammembers&data=05%7C01%7C%7C164779ea27dc4603a93408da9b325c33%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637992937840636647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cNsTHcA4OyRrYXzuWFyqad2ed0%2BKkKzVdHQrWPgqGMA%3D&reserved=0> process for VFS team members (even if you’re not new) so that you can be added to the VFS Roster<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw%2Fedit%3Ffolder%3D0ALlyxurHpUilUk9PVA%23gid%3D2042046665&data=05%7C01%7C%7C164779ea27dc4603a93408da9b325c33%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637992937840636647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7ruAC%2BprD%2BB04P4ZK87yXpzdv2YsAR9tORrEAqLt3kk%3D&reserved=0>.

If you’re on a Platform team, please reach out to your team leadership about getting added to the Platform Roster<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvfs.atlassian.net%2Fwiki%2Fspaces%2FAP%2Fpages%2F1908834623%2FPlatform%2BRoster&data=05%7C01%7C%7C164779ea27dc4603a93408da9b325c33%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637992937840636647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=84lsU7d51VxTqej6vDFL4ECQbxzIVqlrn6%2BWyW4l1OM%3D&reserved=0>. (See the roster for the list of Platform teams.)

I’m closing this Issue. Please RE-OPEN when you’ve been added to either the VFS Roster (which should happen after your Platform Orientation Template is started) or the Platform Roster and I will check the rosters again for your email address.

**Comment by jsimonVA** [comment]
Thank you

Jarred Simon | Front-End Developer
Mobile: +1 (405) 443-0002​
Email: ***@***.******@***.***> | ***@***.*** ***@***.***>
Office Hours: 8am-4pm ET
Connect with VetsEZ: Website<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvetsez.com%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583207196%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DJEaTHkGGzM2SyOJh9bwOiJVxdS2Dlyb6%2Fd5xSEF7AE%3D&reserved=0> | News<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvetsez.com%2Fnews-and-articles-2%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583217146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ILTWxLagnq6nZx20Z7E6seNJhhz1xLpZUQ7i9Dw0hrk%3D&reserved=0> | LinkedIn<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fvetsez%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583217146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yuVUWayRu1FdPau7qfqSyoEBBDn0gwuPorRMlbLBZfg%3D&reserved=0> | Twitter <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FVeteransEZ&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583217146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ArHVgVIvrMuTtzuPxsIenms%2FqrdrE%2BabeSRhFoDQuQg%3D&reserved=0>
***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvetsez.com%2F&data=04%7C01%7C%7Cd5fcb03cb7454b5b17b008d9619dc8c0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637648152583227106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mEZ0uhCVGnDdxp7ogHXqDvOaMxvp3iOeJSx8nwYBQo0%3D&reserved=0>
**PROPRIETARY and CONFIDENTIAL** This email and any attachments are confidential and/or proprietary and intended solely for the named recipients. Unauthorized use, copying, or distribution is prohibited. If you received this e-mail in error, please notify me by replying and delete the message without copying or disclosing it. Thank you.

From: Jeremy Britt ***@***.***>
Sent: Tuesday, September 20, 2022 1:06 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Simon, Jarred C. (governmentcio Llc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] SOCKS access for Jarred Simon (Issue #47284)


@jsimonVA<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FjsimonVA&data=05%7C01%7C%7Cb2ea5728c6974c4a094308da9b32e2a4%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637992940095823394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bC7%2ByxSB2r%2BJMfuDD4tLw%2FRm5evRHt6MOIqhK5bghcg%3D&reserved=0>, there is currently a bug in our bot causing this issue. I manually searched for you and located you within the VFS team roster. I will continue processing this request and will get you squared away shortly.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
