### ISSUE TITLE
Define Process for VSignals

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47282]
## Tasks
- Evaluate this week's data
- Define a process as you go

**Comment by kristenmcconnell** [comment]
[Sept. 19 VSignals Summary](https://dsva.slack.com/archives/C022AC2STBM/p1663966536485699)

**Comment by kristenmcconnell** [comment]
Set up a meeting with Ben to run by process ideas by him.

**Comment by kristenmcconnell** [comment]
I believe that this process will evolve. For instance, I still need to meet with Shane Strassberg to talk through a VSignals taxonomy for the research repo. However, the process that I think will work for now has been added to [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/VSignals/README.md). I can take on next sprint's analysis and keep refining.

@benbrasso-agile6 @loripusey
