### ISSUE TITLE
SOCKS access for TEST. 👋 rebecca is testing the workflow

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#47290]
### Your Name

Napoleon Kernessant

### Your Email

napoleon.kernessant@va.gov

### Your Role and Team

TEST n/a

### Product Manager (PM) name and email

TEST n/a

### Product Owner (PO) name and email

Test n/a

### Access Type Requesting

viewers

### Public SSH Key

I don't think this is going to work. I didn't update these lines: https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/pst-amt-roster-check.yml#L111-L117

Testing anyway to see what happens!

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
NICE!

**Comment by rmtolmach** [comment]
ooh yay. I was thinking it would error in the Action:
```yml
body: |
  # Platform Roster - ${{ steps.roster_checker.outputs.PLATFORM_RESULT_EMOJI }}
  ${{ steps.roster_checker.outputs.PLATFORM_RESULT_MSG }}
  ${{ steps.roster_checker.outputs.PLATFORM_FOUND }}

  # VFS Roster - ${{ steps.roster_checker.outputs.VFS_RESULT_EMOJI }}
  ${{ steps.roster_checker.outputs.VFS_RESULT_MSG }}
  ${{ steps.roster_checker.outputs.VFS_FOUND }}
```
Since only the VFS_ or PLATFORM_ outputs would be set. But looks like having them empty doesn't make the step fail 🤷 LGTM! Closing.
