### ISSUE TITLE
Vaos Clinics filtering Feature flag

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#47302]
## Item Description
We need to create a feature toggle for VAOS direct scheduling & appointment request clinic filtering (V0 & V2). 
Flag name: `va_online_scheduling_clinic_filter`

---

## Tasks
- Add `va_online_scheduling_clinic_filter` feature toggle
## Acceptance Criteria: 
The toggle is created for VAOS

## Definition of Done
- [ ] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by ldelacosta** [comment]
Is the feature toggle available in staging? I tried to validate and I could not find it. 

cc: @simiadebowale @ryanshaw

**Comment by ldelacosta** [comment]
Validated in staging. The toggle is available in staging. 

cc: @jenniemc ![Screen Shot 2022-09-22 at 10.36.40 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/6acd08a6-9ae7-4485-8f79-34e624b4f9df)
