### ISSUE TITLE
[Design] 10-10EZ | Start Research Preparation for Household Redesign

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#47300]
## Background
In support of the initiative to improve the household information section ([epic #41403](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41403)) a research roadmap (this ticket) will be created to help prepare all materials ensuring the research plan and methods help support the objective and key results.

> ### Objective 
> Update the 10-10EZ, so it is easier for applicants to understand and complete without having to exit the application.
> 
> ### Key Results
> Key Result # 1: Reduce drop-off/exit rate for the Household section pages by half.
> Key Result # 2: Increase application submissions by 10%, and submissions within a single session by 5%
> Key Result # 3: Veterans feel prepared when they begin the Household section
> Key Result # 4: Veterans understand what is being asked of them and why, feeling comfortable in providing the information.
> Key Result # 5: Reduced call center complaints on the Household section of questions
> 
> ### User Story
> As a health care applicant, I need to proceed through the application easy and confidently so I will be better prepared to complete the application the first time without interruption or having to save & finish later.

## Research Goal: 
Understand and measure the usability impacts of optimizing the household information section question flow and content. Provide qualitative data to align with initiative key results 4 and 5.

### Methods: 
- [Household Info Form UX Audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Research/Household-UX-Audit.md)
- Analytics analysis of existing site for key results
- Qualitative baseline on Veterans/applicants perception of the existing site in comparison to the new proposed design
- Usability testing on desktop prototype of proposed optimized flow task completion

### Research Questions
- Within the household information section (step 4) of the 10-10EZ health care application, do the questions occur in an **order that is logical** to Veterans/applicants?
- Are the questions worded and explained in a way that is **clear and understandable** to the Veterans/applicants or is additional context and explanation needed?
- What is **easy or difficult and why** for the Veteran/applicant as they work through the household information questions?

## Research roadmap tasks to complete:
- [x] Research goals, methods and questions
- [x] Mobile testing/design plan (will test in staging post this research study)
- [x] Create [interactive prototype in UXPin](https://preview.uxpin.com/6a98bfd8c3a76816b8695fbdc6883bd477610024#/pages/159024257) 
- [x] [Existing wireflows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/ED183CDE-8743-4185-BB25-E708084B0E9C/canvas) of household info section 
- [x] [Proposed wireflows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/AE225764-D5BB-4CE6-9577-38E8F570392B/canvas)
- [x] Create research folder on GH
- [x] [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Plan.md) 
- [x] [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Conversation%20Guide.md)

**Comment by markfallows** [comment]
@nicko-amida and @jessicastump will update this with any additional details/steps needed.

**Comment by jessicastump** [comment]
## Background
In support of the initiative to improve the household information section ([epic #41403](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41403)) a research roadmap (this ticket) will be created to help prepare all materials ensuring the research plan and methods help support the objective and key results.

> ### Objective 
> Update the 10-10EZ, so it is easier for applicants to understand and complete without having to exit the application.
> 
> ### Key Results
> Key Result # 1: Reduce drop-off/exit rate for the Household section pages by half.
> Key Result # 2: Increase application submissions by 10%, and submissions within a single session by 5%
> Key Result # 3: Veterans feel prepared when they begin the Household section
> Key Result # 4: Veterans understand what is being asked of them and why, feeling comfortable in providing the information.
> Key Result # 5: Reduced call center complaints on the Household section of questions
> 
> ### User Story
> As a health care applicant, I need to proceed through the application easy and confidently so I will be better prepared to complete the application the first time without interruption or having to save & finish later.

## Research Goals: 
Understand and measure the usability impacts of changing the household information section question flow and content.


### Methods: 
- [Household Info Form UX Audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Research/Household-UX-Audit.md)
- Usability testing on desktop prototype of proposed optimized flow
- Analytics analysis of existing site for key results
- 


### Research Questions
- Within the household information section (step 4) of the 10-10EZ health care application, do the questions occur in an **order that is logical** to Veterans/applicants?
- Are the questions worded and explained with additional context in a way that is **clear and understandable** to the Veterans/applicants?
- What is **easy or difficult and why** for the Veteran/applicant as they work through the household information questions?


## Research roadmap tasks to complete:
- [ ] Research goals, methods and questions
- [ ] Mobile testing/design plan
- [ ] Create interactive prototype in UXPin 
- [ ] Existing wire flows of household info section
- [ ] [Proposed wireflows](url)
- [ ] Research Plan 
- [ ] Conversation Guide

**Comment by jessicastump** [comment]
Submitted for research review - [ticket link](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/192)
