### ISSUE TITLE
Header/Footer Subdomain font size issues

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#4730]
## What happened?
The Font Size/Spacing/CSS for the header/footer on the subdomains is incorrect resulting in text being cutoff (screenshots below)

## Specs:
- Device: Win 10/Dell GFE Laptop
- Browser: Chrome, IE
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: Example, but appears on most (all?) subdomains: https://www.benefits.va.gov/benefits/offices.asp 
- Test User _(if applicable)_: N/A

## Desired behavior
Menu & Menu Text size on subdomains should maintain a seamless experience on subdomains and be the same as on va.gov

## Acceptance Criteria
- [ ] Font Size/Spacing is the same of Menu/Menu Items on Subdomains

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

Chrome:
![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/f00f94cf-420c-40ba-9e8a-f7dd18b39290)

IE:
![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/c47c2d44-ab93-4544-905f-76ca12c4860c)

**Comment by brianalloyd** [comment]
Reviewed in grooming, need to review other affected areas and work in future sprint.

**Comment by brianalloyd** [comment]
Closing.
