### ISSUE TITLE
Write-up lessons learned implementing OAuth with idme and logingov

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#47317]
List out all of the bugs and issues we ran into when implementing OAuth with idme and logingov

- token error: We are getting valid codes from idme and logingov and they are sending an error back to us stating the code is invalid
- state in different browser: if you start a logingov create account session in one browser, click the verify email in another device or browser, when you return to va.gov you get a state error. This doesnt happen with idme because they force the user to go back to the original window
- up-leveling not setup like it is for saml

@bosawt and @AGarcia-Clarity Looking for you two to lead the conversations from your teams. Adding in the issues, impact, and resolution in bullet form to this ticket is fine. Expand upon anything you'd like. Ill draft the doc and collect it all.

**Comment by bosawt** [comment]
I'm gonna close this ticket, I think it's been long enough
