### ISSUE TITLE
AWS Staging: Sterling VA Clinic (983QE) is not displaying in VAOSv0

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#47312]
BLUF: Sterling VA clinic is not displaying under "Choose a VA location" list in VAOS
Pre-condition: Login to VATS- Select Sterling VA clinic as facility location- Primary Care- Request = Yes, ANY veteran and DS = No

Steps to Reproduce:

Login to VAOS as jacobreid.r.iasimone@id.me (VAR test patient)
Click on "Start Secluding"
Select "Primary Care" for Choose the type of care you need
User is directed to "Choose a VA location"
 
Expected Results: Sterling VA clinic should display under the "Choose a VA location" list. 

Actual Results: Sterling VA clinic is not display under the "Choose a VA location" list. Note all other sites display as appropriate. It is just Sterling 983 QE that is NOT displaying.  

[https://staging-api.va.gov/vaos/v0/request_eligibility_criteria?parent_sites[]=983&parent_sites[]=984]

This URL shows Sterling (983QE) in the list of sites returned.  See attachment.  
Tried with v0 test users and Sterling VA Clinic is not displaying in the option list for location.

Issue also created in JIRA while we figure out if Backend or Frontend issue:  https://issues.mobilehealth.va.gov/browse/VAOSR-4419

![Sterling983QENotDisplaying.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/b1b36885-c4ca-4421-809e-3309d2327224)

[https://app.zenhub.com/files/133843125/88186509-c173-476b-9e77-c172a46c215f/download](https://app.zenhub.com/files/133843125/88186509-c173-476b-9e77-c172a46c215f/download)

**Comment by ldelacosta** [comment]
@simiadebowale will review to see if this is a bug or enhancement. If it's an enhancement, VAOS FE team will need to create a new ticket. If it's a bug, we will update the code #46281.

**Comment by simiadebowale** [comment]
@marcynadeau I reproduced this using  test user: judy.morrison@id.me in v2 & I was able to get Sterling VA clinic returned back.
![Screen Shot 2022-09-20 at 8.38.59 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/feeea033-e26e-4c2a-b259-cf723ac39e85)

**Comment by marcynadeau** [comment]
From Brad:  Really need front end to look into this as data from MFS is correct.

**Comment by marcynadeau** [comment]
Closing as invalid.  1) Lighthouse Facilities API and CDW sandbox environments are copies of production and Sterling is no longer a valid site in production.  2) CHYSHR VistA instance is a static copy and does not get updated to be in synch with production site updates.

**Comment by marcynadeau** [comment]
1) Lighthouse Facilities API and CDW sandbox environments are copies of production and Sterling is no longer a valid site in production.  2) CHYSHR VistA instance is a static copy and does not get updated to be in synch with production site updates.
