### ISSUE TITLE
Purge PII from public va.gov-team repo Q1 2020

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4731]
### Problem Statement

PII was introduced to the public va.gov-team repository, and has since been deleted. 

How might we purge the history of the affected issues and files, so that the PII is not accessible in the history of the repo? How might we standardize and document that process so that we can follow it in the future?

**Comment by billfienberg** [comment]
Thus far, I have done the following:
- Researched how to completely remove sensitive content from a repo
  - I've documented my findings in the [va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/removing-sensitive-data-from-a-repository.md)
  - The most helpful article for me was https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository
- Created a test repo on my personal Github, and added a file that would typically have sensitive content (`.env`), and 
- Created a checklist for how to remove sensitive data based on GitHub's docs
  1. Back up repo
  2. Close/merge all open PRs
  3. Use BFG/git filter-branch to purge file(s)
  4. Contact GitHub support to permanently remove cached views and references to the sensitive data in pull requests
  5. Tell collaborators to rebase any branches they created off of the old repository history
- Practiced removing sensitive data from my test repo
- Confirmed that LFS files are unaffected and still accessible after running `git filter-branch` to remove sensitive data from a repo
- Reached out to various authors about closing/merging open branches/PRs
  - This has been an iterative process
- Proposed the following plan to ensure the PII is removed from the `va.gov-team` history this sprint
  1. Post a message in a public channel letting everybody know that we found PII in the repo, and it is imperative that we purge it.
  2. In that notification, let people know that we need to close/merge open PRs/braches by a specific date this sprint (perhaps Friday January 17th so we’d have the last 2 days of the sprint to actually purge the files).
  3. On whatever date we decide, purge the files.
  4. Notify everybody to rebase, or delete-then-reclone the repo.

**Comment by meganhkelley** [comment]
Conversation with GitHub enterprise support: https://enterprise.githubsupport.com/hc/en-us/requests/518697

meganhkelleyThursday at 08:31
Hi again — my apologies, I do have another question here.

When you say "The action we would take on our end would be similar to the issue deletion action you would take as an administrator," are you saying that the issue deletion is crucial to purging history even if the edit history is deleted?

Let's take an example — say we have an issue in our public `va.gov-team` repository, and I write my social security number in the body of the issue and again in a comment.

Upon realizing that I've written out my social security number, I delete the text from the body of the issue (after which I follow [the steps](https://help.github.com/en/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) to delete the edit history), and I delete the entire comment that had contained my social security number.

Those steps (deleting text from issue body & deleting the corresponding edit history, and separately, deleting the comment itself) are _entirely_ sufficient to purge my social security number from the `va.gov-team` repository, and it would be impossible for a bad actor to retrieve that information in any way. Is that correct?

(_Or_ are you saying that those steps _must be followed_ by an administrator deleting the issue itself?)

Thanks again,
Megan

---

François ConilMonday at 00:37
Hi Megan,

This is correct. Deleting the comment, editing the body of the issue, and then deleting the edit history is sufficient. Once the edit history is gone, the original text cannot be retrieved.

Let me know if you have any questions.
François

**Comment by meganhkelley** [comment]
Current remaining action items documented here: https://github.com/department-of-veterans-affairs/github-user-requests/issues/1319#issuecomment-594167680
