### ISSUE TITLE
Adding Shakuntala Majumder to DSVA Slack

### ISSUE THREAD

**Issue by cbrizen** [department-of-veterans-affairs/va.gov-team#47310]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Are you requesting to add an individual as a:
- Multi-channel

- What channel(s) do they need to be added to?
-  Please add [shakuntala.majumder@thoughtworks.com] as a multi-channel guest to these channels: [long_covid_leadership][long-covid-public][long-covid-team].

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
Need to get Shakuntala into Slack for the Long COVID project. She is new to the team and joining as Tech Lead. She needs to be able to communicate with the team and the client.

**Comment by LEHigley** [comment]
cant add to long covid leadership
