### ISSUE TITLE
AWS access for Jared Cunha

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#47322]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Jared Cunha

### Your Email

jared@coforma.io

### Team, Role, and Company of the target individual

Benefits, Software Engineer, Coforma

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

I'm currently working on the **Claims Status Tool**, **LGY: Certificate of Eligibility**, and **VA Benefit Letters**  application which sits behind a proxy. I need to be able to access requests on staging to debug issues with requests made to this service.

### Access Expiration

ongoing

### Additional Notes

Vendor Onboarding Representative Name: Jeff Langworthy, Coforma

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
Found user in VFS team roster

**Comment by jbritt1** [comment]
### For AWS Access
User: Jared Cunha
COR: Eunice Garcia
VOR: not provided, @jaredcunha please also identify your VOR as time allows
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by jaredcunha** [comment]
@jbritt1 I had that in the additional notes - It's Jeff Langworthy

**Comment by jbritt1** [comment]
> @jbritt1 I had that in the additional notes - It's Jeff Langworthy

Apologies for missing it, that is my mistake! Thank you for providing that!

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Requested AWS access ("I need to be able to access requests on staging to debug issues with requests made to this service.") approved

**Comment by jbritt1** [comment]
First-time login credentials provided to user via DSVA Slack workspace DM at this time.
