### ISSUE TITLE
Remove past appointment history check for mental heath & Primary care Appointments in v0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#47327]
### Description

We no longer need to make a past appointment history check or mental heath & Primary care Appointments in v0.
We have already taken this check out for v2 and it's behind the v2next flag. We need to use the `va_online_scheduling_clinic_filter` instead to make this change also available for v0.

---

### Acceptance Criteria

When the `va_online_scheduling_clinic_filter` toggle is on, there should be no past appointment history check for Mental health & Primary care appointments in v0 & v2.

---

## Definition of Done
- [ ] Acceptance criteria is met.

**Comment by jenniemc** [comment]
@simiadebowale, @ldelacosta, @JRRoof A previous ticket [#28269 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28269) has already addressed removing past clinic check for Primary Care and Mental Health in v0. Closing this ticket.
