### ISSUE TITLE
Implement Algolia search across all repos

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4733]
### User Story

As a team member building on or in support of VA.gov, I want to search all existing documentation, so that I can find (on my own) the information I need to do my job. 

### Details and Notes

Initial notes about Algolia can be found in the discovery sprint [technology discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/research/discovery-sprint-12-2019/technology-discovery.md). 

### Goal(s)

- Users can functionally search all existing documentation for building on and in support of VA.gov from one location

"Functionally" = search _works_ and generally helps people find what they're looking for.

### Areas for Discovery

Can Algolia simultaneously search across private and public repos? If not (if public only), is it still part of our recommendation?

**Comment by meganhkelley** [comment]
Group met on 2/18 to determine next steps for Algolia: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/research/search-mtg-notes-021820.md

Moving this issue to Icebox as search has been deprioritized as part of documentation MVP.

**Comment by vbellissimo** [comment]
Cancelling/old task.
