### ISSUE TITLE
SOCKS access for Andrew Rodiek

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#47330]
### Your Name

Andrew Rodiek

### Your Email

andrew.rodiek@govcio.com

### Your Role and Team

Debt Resolution, Front End Engineer, GovCIO

### Product Manager (PM) name and email

Denise Coveyduc

### Product Owner (PO) name and email

Matt Self

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDwC/gCq9ygpZleWl1Jku8BU6KMMAFrd4ZYy618/S/z1ySs27ixJQdSRSh0SOOfnq8xeklql8r732A5+piJvdOsiUp/bDWP5Ko4t6hxqBOb4bes7oPuSw4y/rwZmlljVJklENJAMhZLzsEsKpGCxDv4jcwtQcE3Gf/duFvyX8burW+nJs/H6RLNB6goi7zPaAvv4eyhl0J1jA6oZxqV/4cZPK1Yo6LhQrVGqgm0MAAAH6KVyMGp1LA2OWjkiBmE0vMHZZ95yGdVw+fpPlEkUMSqALukg7fXTBCFgACFugPPlNedrU8WgWRJ/8uXKMng6Q1Mt5qweZPp34kVkJZ0z6PrPQHs+nBNgbhM1jpVLZCjWuOrtH8Ca1/WHXeGAfFWHFTWcGF8AuXVeciSUN+0DdX4kL5kbwzf8jHQWofj9SMscovc5vAPvyo6Vp+ZdyEVXL+8qwHOdZ3pHXcyDhrzFYhWV9kiBnvOkjWLXcHBWQkVpawjNOm/Xcvso0TVriH6ZBM= work@Andrews-MacBook-Air.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by Dr-Pongo** [comment]
This is for a new laptop. [Previous request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36413)

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
