### ISSUE TITLE
BE | Profile | Move Error Document to Repo

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#47332]
## Background
The error code documentation is currently in Google Docs. 

## Tasks
- [x] Convert to Markdown and add to Github Repo

**Comment by tpharrison** [comment]
@SKasimow @adamwhitlock1 

The [profile errors document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/profile_errors.md) has been converted to markdown and added to the sensitive repo.

No other documents are currently linked to it.

**Comment by SKasimow** [comment]
Thanks Tom!
