### ISSUE TITLE
[Wizard] Define copay path

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#47342]
## Issue Description
Define copay path for Wizard

---
## Tasks
- [x] Define path for veterans to use wizard for copays

## Acceptance Criteria
- [x] Path defined

**Comment by briepipitone** [comment]
[MCP Wizard Mapping Doc](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B8B3A764A-D917-4EAA-BEF7-3C25C44D8654%7D&file=MCP%20Wizard%20Mapping.docx&action=default&mobileredirect=true&cid=90b0c2f9-c4c9-4c77-8efd-f40e76ad1c0d)

**Comment by mgleo** [comment]
@denisecoveyduc 
Some answers available on the [Wizard mapping doc](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B8B3A764A-D917-4EAA-BEF7-3C25C44D8654%7D&file=MCP%20Wizard%20Mapping.docx&action=default&mobileredirect=true&cid=90b0c2f9-c4c9-4c77-8efd-f40e76ad1c0d), some still unanswered.

Does the contact info/content we see on the VBA path match what should appear on the VHA path of the [wizard](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)?
For example, the path **request debt relief > spouse** has the following info:

> 
> Based on the information you provided, this isn’t the form you need.
> Here’s how to request help with debt for spouses or dependents:
> 
> To request help with VA education, disability compensation, or pension benefit debt, fill out the PDF version of ourFinancial Status Report (VA Form 5655).
> 
> You can use this form to request a debt waiver, compromise offer, or extended monthly payment plan. You’ll also need to include a personal statement to tell us why it’s hard for you to repay the debt.
> 
> Submit your completed, signed form and statement by mail or fax.
> 
> Mail:
> Debt Management Center
> P.O. Box 11930
> St. Paul, MN 55111-0930
> Fax: 612-970-5688
> If you submitted VA Form 5655 in the past 6 months
> 
> You don’t need to submit a new request unless you have changes to report. Call us at800-827-0648(or+1-612-713-6415from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET. If you have hearing loss, call TTY:711.
>

**Comment by denisecoveyduc** [comment]
@mgleo  Let me check with our stakeholders, there was some discussion of routing all requests to the DMC at least initially so we can better track  issues but I am not sure that decision was finalized. I will circle back when I have clarity.

**Comment by mgleo** [comment]
Wizard currently shows the following info for copays:
![Screen Shot 2022-10-04 at 3.43.31 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/6768b74c-5a68-4e01-b92c-764bc8e0011d)

**Comment by denisecoveyduc** [comment]
Related to #27918
