### ISSUE TITLE
[Bug/edge case] Facility Locator - Map not loading upon specific address search

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#4734]
## What happened?
On Staging Facility Locator page, after results load for certain specific addresses*, the map does not load -- only the icon appears.  Clicking on the icon does nothing either.
**\*NOTE**: This is address-specific, and seems to occur only when 1 single search-result is returned.

## Specs:
- Devices: Samsung S7 \[owned by @cgreim]

## Steps to Reproduce
1. Go to Staging Facility Locator page [https://staging.va.gov/find-locations/](https://staging.va.gov/find-locations/) \[enable/allow geolocation if prompted]
1. In **Search...** textbox, input **522 Camino de Nevada, Bisbee, AZ 85603**.
1. From **Search for** dropdown, choose **Benefits**.
1. Tap **Search** button.
1. After results load under **View List** tab, tap **View Map** tab to bring that forward.
1. Observe lone icon displayed on top of empty background -- no underlying map displayed.

![image](https://user-images.githubusercontent.com/587583/72113680-6d984880-32fe-11ea-9fb4-8f09d36b4fbe.png)

**NOTE**: This does not seem to happen with address that returns 2+ search-results:

* Bug appears to occur with addresses returning single search-result:
  * 522 Camino de Nevada, Bisbee, AZ 85603
  * 4351 E, AZ-90, Sierra Vista, AZ 85635
* Bug does NOT occur with addresses returning multiple search-results:
  * 4720 East Broadway Boulevard, Tucson, AZ 85711
  * 1600 Pennsylvania Ave NW, Washington, DC 20500

## Desired behavior
Map image loads underneath icon.

## Acceptance Criteria
- [ ] \[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
This is also replicable, and hopefully also fixable, using macOS Chrome's Dev Tools emulator for iPhone X.

**Comment by tlei123** [comment]
@brangi , this is now fixed on iPhones, but still persists on emulated Android devices on SauceLabs (Galaxy S9, S6)...

Let me know if you have a real Samsung S9/S6 (or anything in between); I think it might be advantageous to try replicating on a real device before further work is done here.

@mmiddaugh , if you know anyone with a real Samsung S9/S6 (or anything in between), pls. see if he/she would be amenable to help us replicate.

Thanks!

**Comment by tlei123** [comment]
FYI, I found a Samsung real-device owner who'll help us replicate this tmrw/Monday.  I'll update her replication results here soon.  :::fingers-crossed:::

**Comment by tlei123** [comment]
Replicated on real Samsung phone by @gmaciolek .

**Comment by brangi** [comment]
I think the issue could be reproducible but it should be treated at known bug because it happens on production, it was not necessarily introduced by the sdk upgrade.

<img width="1293" alt="Screen Shot 2020-01-24 at 12 27 26 PM" src="https://user-images.githubusercontent.com/100468/73093924-305abb80-3ea5-11ea-96c0-7787c4105b46.png">

**Comment by tlei123** [comment]
Cool, thx @brangi !

@mmiddaugh , I'll defer to you for listing this as a "Legacy" issue and moving it to Icebox pipeline.  After all, I wouldn't argue against calling this an edge case.

**Comment by mmiddaugh** [comment]
This issue is resolved. Screenshot from production: 
![image](https://user-images.githubusercontent.com/55411834/110858208-0914a880-8277-11eb-8a42-237c4eaf34ee.png)
