### ISSUE TITLE
[cFSR] Design for FSR Review page

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#47346]
## Issue Description
Design for FSR [review page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487560/comment/sitemap,comments?mode=vid)
---
## Tasks
- [x] Create designs for open accordions on [review page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487560/comment/sitemap,comments?mode=vid)

## Acceptance Criteria
- [x] UXPin updated

**Comment by mgleo** [comment]
Examples of the Review Page follow current design on FSR:
[Notice of Disagreement](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27)
[Higher Level Review](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6)
[10-10EZ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6)

**Comment by denisecoveyduc** [comment]
During 9/28 Grooming session we discussed this has turned out to be more work than anticipated. @mgleo will break out additional work to continue into Sprint 84

**Comment by denisecoveyduc** [comment]
Rolling over to Sprint 84 - determined to me much more involved and complex than first anticipated.

**Comment by mgleo** [comment]
Currently on FSR: 
![Screen Shot 2022-10-18 at 11.04.43 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/5cbb2eb1-150d-498e-af2a-8b19b06f6f60)

Any reason not to change Personal information section to something like this?
![Screen Shot 2022-10-18 at 11.06.02 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/dd75e633-ab9d-466e-80f2-b712515fa28b)
