### ISSUE TITLE
Update form link on FSGLI insurance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47351]
## Issue Description
Tanekwa Bournes let us know that there's a broken link on the [Family Servicemembers' Group Life Insurance](https://www.va.gov/life-insurance/options-eligibility/fsgli/) page.

At the bottom of the page under the "Which forms would my service member need?" we need to update the first link for the Claim for Accelerated Benefits (SGLV 8284A).

The new link should be: https://benefits.va.gov/INSURANCE/forms/8284a.htm

## Tasks
- [x] Update link
- [x] Review (Laura)
- [x] Copyedit
- [x] Publish
- [x] Notify stakeholder that changes are live

## Acceptance Criteria
- [x] Updated link is working and live on the site

**Comment by aliyahblackmore** [comment]
Hi @laurwill this is ready for you! 

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=765

Because we are only linking to one form, I included a direct link to the PDF (which seems to have been the case previously and is the case for the Report of Death of Family Member (SGLV 8700) form).

**Comment by laurwill** [comment]
Thanks @aliyahblackmore !
I think the form landing page didn't exist previously — and in this case, even though there's only one form, we want to use the landing page in case the prudential folks update the form (to prevent another broken link). So I swapped it to the "Get XXX to download" model. 

@RLHecht want to copyedit/pub this update?

**Comment by RLHecht** [comment]
Thanks all. I copyedited and published this. Moving to validate and I'll let Tanekwa know once it's live.

**Comment by RLHecht** [comment]
This is live and I let Tanekwa know. Closing!
