### ISSUE TITLE
Content review for pre-need intro page from benefits

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#47358]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
This page appears to have outdated content. [There are heading issues as well documented in this ticket caught in a maintenance audit.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47355) We'd love y'alls help in updating the content of this page to meet updated standards.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/burials-memorials/pre-need)
- [Link to page on production](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
No due date as this has already launched

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits 
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@joshkimux Thanks for this ticket! This is an older form that’s on our to-do list to rework, though not right away. But if there's specific content that's incorrect, we can address that now and make other broader changes at a later date. 

Also regarding the 508 issue with headings, we often bold our setup lines to bulleted lists. These aren't intended to be headers, but I'm curious if they are coming up as ones in the screen reader tools you're using.

**Comment by joshkimux** [comment]
Closing this as the content team will be returning to this in their rework!
