### ISSUE TITLE
Review & Merge Yarn Workspaces PR

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47367]
## Background

https://github.com/department-of-veterans-affairs/vets-website/pull/22234

## Acceptance Criteria

- [ ] PR is tested and has no functional regressions
- [ ] PR is merged

**Comment by loripusey** [comment]
@acrollet who needs to validate this?

**Comment by acrollet** [comment]
I think the fact that it's been in production without issues is validation enough, closing.
