### ISSUE TITLE
Missing link for Downtime Notifications

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#47379]
### Description
This [page](https://depo-platform-documentation.scrollhelp.site/developer-docs/backend-developer-documentation#Backenddeveloperdocumentation-PlatformFeatures) lists "Downtime Notifications / Maintenance Windows" as a Platform feature, however there is no link and the content does not appear to exist in Platform Website. For some reason it does not appear to have been migrated from: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/pages/platform/tools/downtime-notifications.mdx

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/backend-developer-documentation#Backenddeveloperdocumentation-PlatformFeatures
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/pages/platform/tools/downtime-notifications.mdx

**Comment by taylojill** [comment]
Hello @LindseySaari  and @ericboehs This ticket regarding backend developer documentation came in through the Platform web site footer. Let me know if you have questions or need assistance.

**Comment by taylojill** [comment]
10/6/22 - Issue has been resolved. The Downtime notifications page had a launch blocking issue which has been resolved. The page is now live on the Platform web site. I added a link to the page referenced above as requested.
cc @mchelen @vbellissimo
