### ISSUE TITLE
SOCKS access for Noah Stern

### ISSUE THREAD

**Issue by nfstern02** [department-of-veterans-affairs/va.gov-team#47376]
### Your Name

Noah Stern

### Your Email

noah.stern@va.gov

### Your Role and Team

Veteran Facing Education Services

### Product Manager (PM) name and email

Darla vanNieukerk Darla.VanNieukerk@va.gov

### Product Owner (PO) name and email

Darla vanNieukerk Darla.VanNieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrprmaJjnChrlb+zLUjhaHwVceJ6Dy+wqaJ+SUVgVCDnaDkd7PYmp5pWmv/lpjcDS5avbGIfgbs/3q4hv7atwA81BWGWz92le+JPysDk3G+pCiEHQ1EhoY6G9amRyMnQ0j4Ofvn6igVT7prPGKN05UCERC4LKpZv4z5o4WEyM4Mki0Aw+BFhEs8ggT79Cri/rqMnVfm7I2dIsiotUHniyqeNCJfQzsbozYIjfc6iRswUMC1+wWzYsSz5WDeNtOiHR/JMe+QhpydnQ956kC71JM4KXlj5tvnrG3GCvrO2l/KK/jFnpyOBhhF7+U4oBADE3tb1hkWq/0x6aTxsQacYbTBUf/cdYAaQdSOsiKLnzx0hHqHKuy4IwCnPSaKwgQ5MAJ05lOlGDJF/Fh7aTKCDWH20EsSE0P+fgQ5RAXxyr+1/3HIwnE7R+If0mBybVhq5CAuLC2yDwAEJdjcT6kBVsANk4v8VVnHfkfFup+Tq1Dl6PNlEjy/V33k50+oBZS0sE= noah@Ubuntu2004Vm1

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by nfstern02** [comment]
Seems like somehow I got the wrong ssa key. Repasted. Please kindly do the needful. Thx

**Comment by hgbarreto** [comment]
I see this was re-opened by mistake - Both requests point at the same PR though. Closing this one out as well.

@nfstern02 Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
