### ISSUE TITLE
GIBCT - States drop down is not sorted in alphabetical order. 

### ISSUE THREAD

**Issue by ksantiagomorgan6** [department-of-veterans-affairs/va.gov-team#4737]
## Description

As a developer upon selecting the states drop down, the states must be ordered alphabetically from A-Z. Current the drop down has the states ordered by their abbreviation code. 

Can be reproduced by going to https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=&vetTecProvider=false and selecting the state drop down. 

## Screenshot

![Screen Shot 2020-01-10 at 8.29.57 AM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/7505a52a-a2dd-42d1-a9fa-6d74b4b4e041)

# Acceptance Criteria

1. States list is sorted alphabetically from A-Z.

**Comment by ksantiagomorgan6** [comment]
Pull Request:

https://github.com/department-of-veterans-affairs/vets-website/pull/11450

**Comment by delli-gatti-michael** [comment]
Fix is in Staging. Awaiting UX approval

![Screen Shot 2020-01-10 at 3.34.14 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b4756527-3455-4c9d-829a-4a789855a9ac)
