### ISSUE TITLE
[Content] Define Content & Pass off to VCNE/CHIP

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47372]
## Background
See Slack [thread](https://dsva.slack.com/archives/C022AC2STBM/p1663774039032219)

## Tasks
- Define content for SMS messages for 2 scenarios
- Review content with Danielle
- Pass off content to Chris Horton
    - Here is the CHIP [ticket](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/1244)

**Comment by sarahknoppA6** [comment]
maybe @ytsaoca can pick this up? cc @kristenmcconnell

**Comment by loripusey** [comment]
@ytsaoca where are we with this ticket?
cc: @kristenmcconnell

**Comment by kristenmcconnell** [comment]
@Hortonio Just a heads up that I'll try to find some time with your next week to talk through this text message scenario.

**Comment by kristenmcconnell** [comment]
Sync invite sent out for Oct. 12.

**Comment by kristenmcconnell** [comment]
Closing ticket for now. We talked to Chris about what they will be able to detect on the backend (can they split this into two messages or not). He isn't sure what they will be able to create. The PCI API team's work is slated for the Nov. 1 sprint, so they will let us know what they can do then. We will be able to update any product guides or documentation afterwards.
