### ISSUE TITLE
AWS access for Yang Yang

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#47374]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Yang Yang

### Your Email

yangyang@navapbc.com

### Team, Role, and Company of the target individual

OCTO Benefits Delivery, Software Engineer, Nava PBC

### Product Manager (PM) name and email

Amy Lai (amylai@navapbc.com, amy.lai2@va.gov)

### Product Owner (PO) name and email

Zach Goldfine (zachary.goldfine@va.gov)

### Desired AWS Access

Requesting access to
- read from S3 bucket `dsva-vetsgov-prod-evss`
- vets-api prod Rails console

I am stepping in on the Benefits Delivery team for Matt (William) Gardner @allthesignals need to inherit his permissions. See Matt's [AWS access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37780) & [prod console access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43412)).

### Access Expiration

6 months (re-review on 2023-03-20)

### Additional Notes

COR: Johnathan Ivey (new to OCTO as of Sept 2022)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
Found in VFS team roster

**Comment by jbritt1** [comment]
### For AWS Access

User: Yang Yang
COR: Johnathan Ivey
VOR: Agile Six - Anthony M. Arashiro
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no, but please note the 6 month production access request

**Comment by td-usds** [comment]
Reached out to VOR

@nanotone can you elaborate as to why you need vets-api prod rails console access? This is sensitive access which we do not like to hand out on an ongoing basis. What really is it that you need this level of access for and is there another - more tightly scoped - set of permissions we could grant you?
Is this request a "it's so that I have it when I need it" or is there an actual, concrete, imminent need for you to have this access?

**Comment by nanotone** [comment]
@td-usds Sure thing, I'll paraphrase and elaborate based on [this comment in the original access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43412#issuecomment-1205559994) from Matt (my outgoing teammate).

The OCTO Benefits Delivery team aims to use existing veteran data to programmatically accelerate decisions on certain benefits claims. To that end, I need prod rails console access to
- inspect sample veteran data that's representative of real-world data, for UX research purposes, and
- understand and debug new integrations, or data in existing integrations, that would be useful for determining whether a claim could be accelerated.

This work is currently underway, and I will need access at least through early 2023, when the team's efforts will be applied to PACT-Act-related claims. Let me know if you'd like more details!

**Comment by td-usds** [comment]
Did data call to PO and PM

**Comment by td-usds** [comment]
VOR confirmed information, requested access approved.

**Comment by jbritt1** [comment]
> VOR confirmed information, requested access approved.

Just to be clear, user is approved for general access and 6 months of prod access? Or ongoing? Or some other combination of access levels?

**Comment by nanotone** [comment]
Bumping this to make sure it doesn't fall through the cracks.

@jbritt1 Yes, I've requested general AWS access, and 6 months of prod access, and assumed that's what I'm approved for. Looking to @td-usds if otherwise.

**Comment by td-usds** [comment]
> > VOR confirmed information, requested access approved.
> 
> Just to be clear, user is approved for general access and 6 months of prod access? Or ongoing? Or some other combination of access levels?

user is approved for general access and 6 months of prod access

**Comment by mydesignrocks** [comment]
access provided and DMd the initial login details/procedure.

**Comment by rmtolmach** [comment]
@nanotone Your six months of prod access has expired. I will remove this access unless there is justification for you to have it longer and that gets approved.

policy to be removed: `"adhoc-vetsgov-ssm-prod"`

**Comment by rmtolmach** [comment]
From DM with Yang Yang:
> I did get some version of prod access renewed for ArgoCD amidst the EKS migration, [ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56564). I don’t think I need SSM anymore, in which case this policy can be removed.

Access removed in:
* https://github.com/department-of-veterans-affairs/devops/pull/12952

**Comment by considerable** [comment]
TF applied
