### ISSUE TITLE
CT: Providers filter should be in alphabetical order on Search Results page

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#4738]
Providers filter should be in alphabetical order on Search Results page by provider name

https://staging.va.gov/gi-bill-comparison-tool/program-search

![Screen Shot 2020-01-10 at 10.58.40 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/34765ba7-e036-40d3-818a-cfe81bcb5986)

**Comment by dmccurdybah** [comment]
Can be tested on vets-website branch `vettec-program-filter-sort`

PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11451

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging. Closing this issue
