### ISSUE TITLE
Create user flows

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47407]
## Description
We need to create user flows to guide the conversation guide for upcoming round 2 usability testing

## Tasks
- [ ] Using current design mockups, create user stories and flows that reflect our assumed user path and interactions through secure messaging

**Comment by jonathanjnelson** [comment]
@rbsingleton Please see [the Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1663877414155/ed1b223faea115af8d750a4aa2ec865c695b2b10?sender=jonathannelson8855) for these high level flows to help inform conversation guide.

**Comment by MarciMcGuire** [comment]
This issue is replaced by #47516
