### ISSUE TITLE
Supplemental Claims | Add autocomplete for VA facility

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#47426]
## Value Statement
**_As a_** developer
**_I want to_** utilize the [`/treatment-centers` Benefits Reference Data](https://dev-developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current) provided by Lighthouse
**_So that_** my VA medical facility is included in the autocomplete dropdown (`/decision-reviews/supplemental-claim/request-supplemental-claim-form-20-0995/supporting-evidence/va-medical-records`)

## Background Context

Including an autocomplete would make it easier for Veteran to fill out their VA treatment location name within the form.

Note: This VA medical facility autocomplete was previously implemented within form 526ez (via EVSS). Adding it to Supplemental Claims should be done after implementing it there. 

## Acceptance Criteria
- VA medical facilities autocomplete has been added
- All tests passing

## Tasks
- [ ] Update VA medical facility autocomplete
- [ ] Add unit tests

**Comment by eileen-coforma** [comment]
@saderagsdale This was an enhancement that came out of Pam's initial usability study. I saw that you said we need some light research, can I get some context?
