### ISSUE TITLE
Analytics Implementation or QA Support for Combined FSR/Enhanced FSR

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#47442]
# Google Analytics Implementation or QA Request

## What this form is for
Combined and Enhanced FSR need additional tracking for individual metrics for VBA and VHA respectively. 
Tags Requested
- cfsr-5655-vba-submitted
- cfsr-5655-vha-submitted

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [ X ] Google Analytics implementation

- **Who is this request for?**
 Michelle Dooley
   
- **Provide the link(s) for Google Analytics implementation or QA**
https://github.com/department-of-veterans-affairs/vets-website/pull/22221  
    
- **When is the launch date?**
Already launched

- **Any additional comments**
This is just for successful submissions at the end of FSR.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@OptionSelect - thank you for your submission.  We have some items in front of this request but will get to this as soon as we can.  Will keep you posted when we have an ETA.

**Comment by OptionSelect** [comment]
@michelle-dooley No worries! Thank you for the update :)

**Comment by michelle-dooley** [comment]
@OptionSelect and @denisecoveyduc - I need some more details on this.  I have found the [link to "Request help...page"](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) referenced in the screen shot but I am unclear what action on here you are trying to track?  Can you please provide screen shots of the specific events actions you are looking for tagging to be added to. cc: @chloedotbrown

**Comment by OptionSelect** [comment]
Good afternoon,

Technically we're looking to log the result of the action pointed out to by the arrow in the first screenshot, the submission of FSR. Depending on selected debts at the beginning of the form, once submission is confirmed to be successful, we're looking to log the two above which happens during the initialization of the confirmation page.

https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit (page that contains action)
https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/confirmation (Where dispatch of value actually happens)

![image](https://user-images.githubusercontent.com/29178824/195142939-6ede89b9-cce7-4609-ab45-e07f9a66f300.png)

Hopefully that helps, I'm looking into getting some more screenshots but we're dealing with issues on the back end response atm. Will add more today!

**Comment by michelle-dooley** [comment]
Thank you for the info.  I will get this added to our upcoming sprint.

**Comment by michelle-dooley** [comment]
@OptionSelect - Which button event are you using?

![image](https://user-images.githubusercontent.com/93597659/198320088-1f933a9e-1c3a-4046-9272-4d4e25375afe.png)

**Comment by michelle-dooley** [comment]
@OptionSelect - just following up on this.  If you could provide me more details on the code you are using for this button action that would be helpful.  Thanks!!

**Comment by michelle-dooley** [comment]
@OptionSelect - I am seeing event: 'fsr-5655-submission'  when I click the submit button, does that not give you what you are looking for?
![image](https://user-images.githubusercontent.com/93597659/199547457-095d17c0-0561-4916-9c39-c397445d63a4.png)

**Comment by OptionSelect** [comment]
@michelle-dooley  Good afternoon, my apologies I should've clarified. The behavior fires upon successful submission; that said, we have need for tracking both successful submissions of VHA and VBA separately. Those events live on the confirmation page after clicking the submit button and will run on page load running against some responses from the api after submission.

**Comment by michelle-dooley** [comment]
@OptionSelect - Ok I think that is what I was not following b/c when I hit the submit button it just takes me to a blank page so I cannot see those 2 events.  Do you have screen shots of that?

**Comment by OptionSelect** [comment]
Good afternoon, my apologies for missing this. On staging I used user 228 in order to get to the page. I went through the FSR and submitted it with a compromise reaching this page. This is where we'd expect to see those events rattling off for Denise whether or not they ended up doing one, the other, or both!

![image](https://user-images.githubusercontent.com/29178824/201156281-b9057df3-db1c-4cb2-8058-32a62b0fe313.png)

**Comment by michelle-dooley** [comment]
@OptionSelect - I went through the flow as 228 and am able to see the 5655 submit event
![image](https://user-images.githubusercontent.com/93597659/203114292-2c483f16-5945-4c99-9050-6fb667f8da60.png)  and I am able to get to the 2nd "print this page" part but what on are there are you wanting to see recorded?  By seeing the successful submission I know that page view is next.  Also I don't know how to determine VHA vs VBA, are they both triggered by submitting the 5655 form and if so how is it determined which?

**Comment by OptionSelect** [comment]
Perfect! Thank you for that. Nothing necessarily existing ON that page is providing us with the information. If there has to be an element it would be the initial checkboxes when you selected a debt as 228 upon going through the form. However, we're doing our check at the end because in theory they could change their selections any time prior to submitting. Do you need us to make it the checkboxes in order for the analytics to work? IIRC the VHA and VBA type just depend on if it was a copay debt or a benefit debt type selected. If they have one of each type we want both in analytics otherwise its one or the other! Hopefully that makes sense, sorry if I'm making this complicated!

**Comment by ScottyRJames** [comment]
Hey @michelle-dooley! I've also worked a little bit on getting this in place. You're correct that those checkboxes are what determine what events our app triggers on the confirmation page. The available options would be `cfsr-5655-vba-submitted`, `cfsr-5655-vha-submitted` or `cfsr-5655-combined-submitted`. VBA debts are associated with education or compensation & pension debts and VHA ones are copays that are owed to medical facilities. User 228 only has VBA on staging but User 81 has both to test with. 

Also the event `fsr-5655--submission-successful` you see being recorded is from the platform's form system (outside of our event triggers). I'll see if I can replicate this myself and show their recordings.

**Comment by michelle-dooley** [comment]
Hey @ScottyRJames!!  I have looked at this some more and am I not quite sure how to get to the VBA vs VHA submission level detail b/c the form is the same 5655 form that is submitted so that event does not know the difference.  The only way I can break out VHA vs VBA is by recording which they click at the beginning, example events:  cfsr-5655-vba-selected or cfsr-5655-vha-selected so in this screen shot 'cfsr-5655-vba-selected' event checkbox would be recorded since it is a pension debt.  I know that is not exactly what you are looking for but I do not know how else to breakout since its the same form that is submitted for both.  My best suggestion would be to create a report that shows all users that submitted an fsr and then break out from them how many selected VHA, VBS or both at the beginning.   If you have other thoughts or ways to determine this please let me know.
![image](https://user-images.githubusercontent.com/93597659/207393485-b35f0988-c950-44da-99db-80bc9fc9bdb3.png)

**Comment by Dr-Pongo** [comment]
Hey @michelle-dooley! So some background on what we talked about in office hours: 

Every form submission triggers the following `recordEvent` ([Platform source](https://github.com/department-of-veterans-affairs/vets-website/blob/a01c372544383f349f47c62d07294985c838ea95/src/platform/forms-system/src/js/actions.js#L102-L105)) 
Where `trackingPrefix` is unique to each form, and `eventData` consists of optional properties. 
``` 
recordEvent({
   event: `${trackingPrefix}-submission-successful`,
   ...eventData,
}); 
``` 
> 

The [following proposed changes](https://github.com/department-of-veterans-affairs/vets-website/pull/23092/files#diff-269a1b28df612534a2e11b2a69b55e08b958458a649754cf47b7ddce0a57dcdfR15-R18) for the FSR will populate the `eventData` with the following properties so we can distinguish the type of debt selected for the FSR submission. 
```
return {
   'request-includes-copay': hasCopays,
   'request-includes-debt': hasDebts,
};
  ```
As it stands now `hasCopays` and `hasDebts` will be boolean `true`/`false` values, but I can update them to be `Yes`/`No` if it's easier to track on the dashboard. 

 --- 
 ### Example
The Corona Virus Research uses `covid-research-volunteer--submission-successful` as the event title, and here are some of the [custom properties it has on submission](https://github.com/department-of-veterans-affairs/vets-website/blob/a01c372544383f349f47c62d07294985c838ea95/src/applications/coronavirus-research/sign-up/config/submitForm.js#L31-L54): 
- `'previously-diagnosed-with-covid19'`
- `'close-contact-with-positive-test'`
- `'hospitalized-w-in-six-months'`
  
 --- 
### Question
Do you think this implementation will allow us to sort/organize submissions based on these new property values?

**Comment by michelle-dooley** [comment]
@Dr-Pongo - ok I think I understand how the covid example works and how to replicate.  Have you configured those new properties (request-includes-copay and request-includes-debt) in the code yet?  If so I can configure in GTM and test to see if they are working as expected.  If not please add and then I will be able to test.

**Comment by Dr-Pongo** [comment]
@michelle-dooley I have not implemented it yet, but I have an open PR I can get merged in today! I'll let you know when it's in so you can begin tracking

**Comment by Dr-Pongo** [comment]
@michelle-dooley 
Here are the labels and [the associated PR to merge them](https://github.com/department-of-veterans-affairs/vets-website/pull/23092)!
`request-includes-copay`
`request-includes-debt`

**Comment by michelle-dooley** [comment]
@Dr-Pongo - good news I was able to replicate how covid did it and have those data layer variables show in the event action label.  However it just shows true/false so its unclear which is true and which is false (copay vs debt).  I see the same with covid.  The values are in the data layer now so you can pull out of ddb for details or if you want to see in GA reports with it added to label naming convention with more detail is there a way to record a string vs true/false?  

![image](https://user-images.githubusercontent.com/93597659/213241196-54c3a900-d76d-4fb5-8b33-e3a8b620fe19.png)

![image](https://user-images.githubusercontent.com/93597659/213241303-191fa309-ac59-43c4-82a5-2cf722feca52.png)

**Comment by Dr-Pongo** [comment]
@michelle-dooley It looks like strings are definitely an option based on the `None of the above` from the covid screener. 
Maybe we could do a single label like `submission-type:` `debt-submission`/`copay-submission`/`combo-submission`?
That way it's a little more clear when viewing the Event Action.

So Event Action titles will be one of the following:
- `Forms - FSR - debt-submission`
- `Forms - FSR - copay-submission`
- `Forms - FSR - combo-submission`
- `Forms - FSR - err-submission` (fallback case.. just in case)

@denisecoveyduc / @HeatherRienks Thoughts? What would be easier to read on the dashboard?

**Comment by michelle-dooley** [comment]
Thanks for update.

**Comment by michelle-dooley** [comment]
@Dr-Pongo - what is the name of the new datalayer variable, 'submission-type'?

**Comment by michelle-dooley** [comment]
@Dr-Pongo - I think we are good on this.  This is what I see now...The submission successful event will be recorded as it was originally (2nd screen shot) and it will also be recorded with the new submission type variable (1st screen shot).  I can change the prefix on the new one to say 'Forms - Debt Management - .... '  instead of  'Forms - FSR - ....'  if that matters?  I cannot change the original though without changing it for all 'Forms - Debt Management' events.  Hope the helps, let me know if you have any questions... 

![image](https://user-images.githubusercontent.com/93597659/214375547-ae744677-dee1-4d4c-8520-1389047d41a2.png)

![image](https://user-images.githubusercontent.com/93597659/214375490-c705ab31-654e-4765-9f7d-576b958d1186.png)

![image](https://user-images.githubusercontent.com/93597659/214375982-67401a4d-1ee7-4f9d-bbd5-fc9977ba28c9.png)

**Comment by Dr-Pongo** [comment]
@michelle-dooley Thank you! I'll touch base with @denisecoveyduc before closing out just to make sure she can gather the metrics she's looking for!

cc: @HeatherRienks

**Comment by michelle-dooley** [comment]
@Dr-Pongo - there were only debt options for me to choose so I couldn't test copay or both but it should track the same since its feeding off the same 'submission-type' variable.

**Comment by Dr-Pongo** [comment]
@michelle-dooley roger that! We're going to pull reports through some other methods and make sure they align

**Comment by michelle-dooley** [comment]
@Dr-Pongo everything should be working as expected so I am going to close this ticket.  Please reach out if you need anything else.
