### ISSUE TITLE
CHECK-IN:  Change Wording for "Go to another appointment" Link

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47443]
## Tasks
- Change Wording for "Go to another appointment" Link ([confirmation page](https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b?collectionLayerId=47832230-7bc5-48dd-a02e-38517161db5e&mode=design))
    - Need to get wording from UX
- Only show link if the user has more than 1 appointment for the today

**Comment by benbrasso-agile6** [comment]
If there's time left after other tickets are complete, we can get to this work.

**Comment by loripusey** [comment]
I thought we decided to not show it if there is only 1 appointment?

**Comment by benbrasso-agile6** [comment]
That sounds fine. I had just forgotten.

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I had a moment to look at this ticket. Thoughts below. Do you want to give it a review? 

Recommend: Go back to your VA appointments

Rationale: While VAOS often uses the "back" breadcrumb (and not a "go back to your appointment list" feature), they do have a call to action of "Go to your VA appointments" that takes Veterans into their appointment list. So, we could amend that.  

![Screen Shot 2022-10-25 at 10.05.47 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/3ee7930f-5a05-43e9-8fb0-0cd17db1b1da)

**Comment by kristenmcconnell** [comment]
Do we need to emphasize what they would be able to do when they click the link? What if the new wording had "check in" in it? Something like "Check in for another appointment" or "Go back to check in for another appointment."

**Comment by benbrasso-agile6** [comment]
Alternative could be, Go back to view your VA appointments

**Comment by acrollet** [comment]
> They would not be able to "check in" for another appt though

fwiw if someone had consecutive appts they should be able to go back and check in once the window opens for the next appt.

**Comment by kristenmcconnell** [comment]
It is a fine line between what our appointment list shows and what is available on VAOS.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Could we do "View your VA appointments" instead? The idea of "go back" implies that a user will see the same (or similar) workflow they just completed (think of when you go back in a web browser, the previous page is often similar or the same as it was when you navigated away from it), but if we remove the "go back" idea I think this works: "View your VA appointments"

**Comment by benbrasso-agile6** [comment]
I like it 👍 Will see what others think on the thread and then we can move it along to engineering

**Comment by loripusey** [comment]
The only problem to consider is that these are not necessarily ALL of their VA appointments, only the ones for which eCheck-in is enabled or applicable (i.e. only in-person appointments). So we don't want them to think that this is everything either, I think we need to qualify it with "these are the ones you can do eCheck-in for" or something to that effect.

**Comment by benbrasso-agile6** [comment]
Would we also then want to correct that on the "Your appointments" page? I feel like introducing "eCheck..." type language will cause confusion with Veterans. 

Let me see if I can pull Analytics for that link real quick to help guide us.

**Comment by benbrasso-agile6** [comment]
Gets more clicks than I would have guessed 

[Analytics All VA.gov Website Data [Production] Top Events 20220925-20221024.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9863461/Analytics.All.VA.gov.Website.Data.Production.Top.Events.20220925-20221024.pdf)

**Comment by benbrasso-agile6** [comment]
This can be PL'd tomorrow

**Comment by benbrasso-agile6** [comment]
Back to today's appointments

^ Only display when more than 1 appointment is available for the day

**Comment by wullaski** [comment]
There's a Spanish translation of the old wording. Is it okay to leave that as is for now?

**Comment by loripusey** [comment]
yes, let's leave the old translation, I'll add the new wording to the list of translations for round 4

**Comment by loripusey** [comment]
@wullaski can you paste here what we decided on for the final wording? I can't remember and I'm not sure that we added it here.

**Comment by wullaski** [comment]
@loripusey it's "Back to today's appointments"

**Comment by loripusey** [comment]
@wullaski typically, we leave a ticket in the validated column until someone validates it, typically myself or Zach (unless it's Tech Debt then engineering would validate)

**Comment by loripusey** [comment]
validated in staging
