### ISSUE TITLE
[Content] Review proposed item name for new BVA notification preference

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#47441]
### Background

We will be adding a new notification preference in Profile, which will send people text message updates when there is a status change with their appeal. We need to confirm what the name of this notification will be so we can get that copy over to VA Profile for implementation.

- Current proposed notification name:  Board of Veterans' Appeals status updates (**needs review**)
- Current proposed group: Applications, claims, decision reviews, and appeals (This is likely fine, but let us know if you have concerns)

### Tasks

- [ ] Confirm whether the proposed notification name is OK, or let us know how we should update it
- [ ] Confirm that the proposed group is OK, and if not, let us know so we can check in with Mikki

**Comment by Samara-Strauss** [comment]
@SKasimow @cgednalske @andaleliz FYI I have created this ticket for Danielle. I'm not totally sure of the preferred protocol, so if the preferred protocol is to bring this to content office hours, will one of you take this on for next week? It should be a fairly quick task. Thank you!

**Comment by andaleliz** [comment]
Thanks @Samara-Strauss! For something like this I usually create a ticket and then let Danielle know in Slack. I'll share it with her. If she can't get to it before next Thursdays office hours, one of us can take it there :)

**Comment by Samara-Strauss** [comment]
Great, thank you for fielding this, @andaleliz!

**Comment by Samara-Strauss** [comment]
@andaleliz @cgednalske following up -- can one of you get this to Danielle's office hours next week? VA Profile was asking about it in today's call. It had fallen off my radar, so sorry I didn't get you a reminder sooner. I can add one of you as an assignee if that helps.

**Comment by andaleliz** [comment]
I thought I responded to this, must've been while I was in transit from retreat and I only typed up a draft. I can discuss this w/ Danielle this Thursday. Thanks for the nudge!

**Comment by andaleliz** [comment]
After discussion, we landed on a different name for the notification since we are moving away from the word "appeals", and this verbiage aligns with the unauth content.

We also think it would be better to update the name of the group, since we have nothing related to claims or applications at this time, and participants got very confused about this in our last research study.

Notification group: Decision reviews and appeals

Notification item: Status updates for your decision review or appeal

@Samara-Strauss how does this land? If you agree, I'll spin up a ticket to update our mock-ups to reflecft this.

cc @mnorthuis for awareness

**Comment by Samara-Strauss** [comment]
@andaleliz this is great. I will pass along to the VA Profile team. Thanks!!

**Comment by andaleliz** [comment]
You're welcome @Samara-Strauss! I realize we'll need to update the mocks when these go live so I'll just wait until then.

**Comment by mjones-oddball** [comment]
@Samara-Strauss Only thought I have is if it's going to break the wording down, do we need to mention hearings as well? That falls under a potential type of update. @bevnobev

**Comment by bevnobev** [comment]
I'm going to run the name change by "The Board" and get their feedback.  I'll cc  @Samara-Strauss

**Comment by Samara-Strauss** [comment]
@bevnobev sounds good! Let's see what they say, and if they have comments, we can bring back to Danielle. If they want us to add "hearings" as Melanie mentioned, that should be fine. 

cc/ @andaleliz it sounds like we should hold off on closing this until BVA signs off. If they have feedback, we'll need you to bring that back to Danielle.

**Comment by bevnobev** [comment]
Just heard back from the BVA.  Below is there response.  Based on what they said, we probably need to change the group name as well.

> It will probably be less confusing if we separate appeals into it’s own group.    In AMA decision reviews and higher level reviews are not handled by the Board, and the Board only works on appeals.    
> 
> Could we do this instead – it makes the distinction very clear to the Veteran about what type of information these notifications will be related to:  
> 
> Notification item: Status updates for your appeal to the Board of Veterans’ Appeals

**Comment by Samara-Strauss** [comment]
@andaleliz can you take this feedback to Danielle for review?

**Comment by andaleliz** [comment]
@Samara-Strauss definitely - what is the timeline for this? Trying to determine if I should schedule a separate meeting with her or if it's OK to wait until office hours next Thursday.

Also, do you have any more info about what the notification is? What are the possible statuses?

**Comment by mjones-oddball** [comment]
@Samara-Strauss @bevnobev My only concern with making the grouping more specific is that I thought it was meant to capture high level categories of things even if they are handled by multiple departments/business lines. For example, payments. If we make the distinction clear in the item name would that be enough?

**Comment by mjones-oddball** [comment]
@andaleliz @Samara-Strauss Here's the general list let me know if you need to see any further detail:

Appeal docketed
Appeal decision mailed (Non-contested claims)
Appeal decision mailed (Contested claims)
Hearing scheduled
Withdrawal of hearing
Postponement of hearing
Privacy Act request pending
Privacy Act request complete
VSO IHP pending
VSO IHP complete

**Comment by bevnobev** [comment]
Just wanted to clarify BVA wasn't dictating the group name.  I only asked for suggestion on the item name.  I'm slightly torn on the group name.  A part of me feels it should be broad, but as @andaleliz mentioned, the broad aspect is causing confusion with Veterans.

**Comment by andaleliz** [comment]
@bevnobev do you think if we changed the group name to "Decision reviews and appeals" it would be appropriate for the two notifications we have now?

People were confused about the group name because it also included the words "applications and claims". I think once we have relevant notifications about those things, we can broaden the group name, but for now, we can limit it so it's relevant to the available notifications.

I'm not concerned about the group name changing in the UI (and possibly confusing people) since this isn't the kind of page people visit regularly.

**Comment by Samara-Strauss** [comment]
> @bevnobev do you think if we changed the group name to "Decision reviews and appeals" it would be appropriate for the two notifications we have now?

I would say given this feedback from the Board:

> In AMA decision reviews and higher level reviews are not handled by the Board, and the Board only works on appeals.

"Decision reviews and appeals" might not be an appropriate group name if the "Decision reviews" part doesn't apply.

**Comment by bevnobev** [comment]
@andaleliz I agree with @Samara-Strauss that the "Decision Review" doesn't apply and is not appropriate.

**Comment by andaleliz** [comment]
I'll clarify with @DanielleThierryUSDSVA on Thursday (unless you can chime in sooner, @DanielleThierryUSDSVA?) but she said the term "appeals" is going away, to be replaced by decision reviews, and including the two phrases together would align with the unauthenticated content Veterans will see about these things on VA.gov.

**Comment by Samara-Strauss** [comment]
Hmm, that's interesting. I obviously don't know much about the world of appeals, but I'd be curious if there is differing guidance being given by different people in BVA.

**Comment by Samara-Strauss** [comment]
Also, I would confirm Danielle is holding office hours this week, as she will be at the OCTO offsite.

**Comment by bevnobev** [comment]
It is odd that  the Board of Veteran Appeals team did not mention that the term appeals will no longer be used

**Comment by mnorthuis** [comment]
Adding a little background in case it's helpful

Before the Appeals Modernization Act, everything was referred to as an "appeal", and after AMA it was referred to as a "decision review".  We used to refer to the old process as the "legacy appeal process" and have shifted the overarching terminology to "Requesting a decision review".   

That said, there are 3 options you can choose when requesting a decision review- 1) Submit new evidence/supplement claim 2) Request a higher level review 3) appeal to the BVA  - that is where the "appeal" language comes into play. 

If the only notification is for the BVA appeal, then I would suggest the name is centered around that or it may be misleading if there are no other items from decision reviews.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @mnorthuis. Yes, the term "appeals" as the overarching term is going away and being replaced by "decision reviews." "Decision reviews and appeals" has been the interim H1 of that section due to the familiarity and SEO value of the "appeal" term.

I agree that if Veterans can't get notifications for the other 2 decision review options (supplemental claim or higher level review) at this time, then we should keep the heading narrowed to BVA notifications to avoid confusing or misleading people.

**Comment by Samara-Strauss** [comment]
@mnorthuis @DanielleThierryUSDSVA thank you for the background info! This is super helpful.

@andaleliz I think your suggestions are clear and succinct, and I co-sign them if @DanielleThierryUSDSVA says they are ok.

**Comment by DanielleThierryUSDSVA** [comment]
Agree @Samara-Strauss! @andaleliz your suggestions are great. Thank you!

**Comment by Samara-Strauss** [comment]
Great, thank you, @DanielleThierryUSDSVA!

I will send Liz's latest suggestion over to BVA. cc/ @bevnobev

**Comment by Samara-Strauss** [comment]
Quick q -- Should it be "reminder" or "reminders"? Assuming there is only 1 since it is currently "reminder", but I figure I'd ask since "status updates" is plural.

**Comment by andaleliz** [comment]
@Samara-Strauss it's singular in the current UI; @mjones-oddball do you know how many text notifications a person will get as a hearing reminder if they opt into this notification?

**Comment by mjones-oddball** [comment]
@andaleliz I do not. Asking VEText - will get back to you!

**Comment by andaleliz** [comment]
Thanks @mjones-oddball! Let me know what you learn and we can update the notification name if needed.

**Comment by andaleliz** [comment]
Thanks @mjones-oddball! Let me know what you learn and we can update the notification name if needed.

**Comment by mjones-oddball** [comment]
@andaleliz 
QSTN:  do you know how many text notifications a person will get as a hearing reminder if they opt into this notification?
ANSWER: Two - one at seven days prior, and the second at three days prior

**Comment by andaleliz** [comment]
Thanks @mjones-oddball ! Reminder**s** it is.

**Comment by Samara-Strauss** [comment]
All -- I am SO sorry. I somehow missed a reply from John Gosnell last week confirming that it should be "reminders" instead of "reminder":

> We send VEText for hearings at 10 and 3 days out from the hearing so it’s multiple reminders.  Also, Veterans can have multiple appeals, each with their own hearing, so would receive separate reminders for that hearing also. 
> 
> “Appeal hearing reminders” is more accurate.

I have a final email out to him to confirm he signs off on the rest of the copy, since he didn't address it in his most recent email.

Again, so so sorry for the delay. I don't know how I missed his email.

**Comment by Samara-Strauss** [comment]
CONFIRMED! John has signed off on the copy [Liz outlined above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47441#issuecomment-1292206130). I will pass this on to VA Profile. We can otherwise close this ticket.
