### ISSUE TITLE
BUG: Duplicate hint text in categories checkbox

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#47444]
## What happened?
"You may check more than one" is repeated twice for the categories question
<img width="435" alt="Screen Shot 2022-09-23 at 11 27 23 AM" src="https://user-images.githubusercontent.com/14154792/191997081-99de0acf-aac6-4916-99af-d9723ec75194.png">

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User: unsigned in

## Steps to Reproduce
- URL: [Production pre need form, veteran applicant information page](https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/veteran-applicant-information)
- Test User: unsigned in

Also exists for sponsor page

<img width="637" alt="Screen Shot 2022-09-23 at 2 45 10 PM" src="https://user-images.githubusercontent.com/14154792/192036245-1b664d70-3cc7-4a24-b6bf-36d5068010d9.png">

## Desired behavior
There should only be one "you may check more than one" hint text. It looks like there may be unintentionally nested patterns as this checkbox features a fieldset nested within a fieldset.

<img width="1268" alt="Screen Shot 2022-09-23 at 11 30 33 AM" src="https://user-images.githubusercontent.com/14154792/191997746-1588605a-3ad0-43b2-9aff-3e75133c1dcd.png">

## Acceptance Criteria
- [ ] Only one hint text exists

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jaredcunha** [comment]
I don't know the provenance of this selector, but it seems like an attempted patch at something, probably this bug, but it didn't work: 
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/pre-need/sass/pre-need.scss#L44

That was part of this update:
https://github.com/department-of-veterans-affairs/vets-website/commit/06a9e1564041ca22e090a47a6ec831b145263082

Didn't get to dig too deep, but I suspect might be worth looking at the [Object Field component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/fields/ObjectField.jsx)

**Comment by jaredcunha** [comment]
Some other issues I'm noticing with this:
- Nested fieldsets don't seem necessary
- Shouldn't the hint be programmatically linked?

A patch would be to take the hint text and put it in parenthesis, which is how most of the hint text is handled elsewhere on the form. But I think there is still something going on with the ObjectField component. This fixes the double text issue here, but not the nested fieldset.

<img width="900" alt="Screen Shot 2022-10-12 at 4 12 37 PM" src="https://user-images.githubusercontent.com/1094951/195438506-1713086a-bcf7-494a-b856-69a3eabb63b4.png">

**Comment by joshkimux** [comment]
@jaredcunha ooph, yea, I don't see the need for a nested fieldset here and assumed it was a flat out bug to be fixed (as opposed to something intentional). There's also the content issue of this being addressed to "you" and not the "sponsor" 😦

**Comment by jaredcunha** [comment]
The `<ObjectField>` component looks like it does a LOT of things and there's a ton of conditional logic within it. It's used for the checkbox, it's used in a zip code field. It might be used for everything? Might need to raise this with the platform team.

**Comment by jaredcunha** [comment]
@joshkimux what do you think we should do with this ticket?

**Comment by joshkimux** [comment]
@jaredcunha I'm not as fluent on the technical side here, so I trust and support your intuition on raising this with the platform team! Thank you for digging into this as well as expertly as you always do ❤️

**Comment by jaredcunha** [comment]
@AlexanderSherrow There was fix that @jerekshoe applied, but it might be worth reverse-engineering that PR or looking at it to see how to reproduce. It looks like it might be solved, but this is going back to October, so my memory on this is now a little hazy.

Just collecting other threads, I did also add a [platform support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1665757314053049).

**Comment by coforma-terry** [comment]
@AlexanderSherrow - I believe the bandaid that @jerekshoe put in place fixed the issue and I think we can close this out with Jereks's blessing.

We might, however, want to write up an additional defect 4 to note that descriptive text should be a hint and not directly a part of the label though (to reduce SR verbosity).

**Comment by jaredcunha** [comment]
@coforma-terry 
> We might, however, want to write up an additional defect 4 to note that descriptive text should be a hint and not directly a part of the label though (to reduce SR verbosity).

The reason why we we've been putting the descriptive text inside the label is because it's not actually programmatically linked to the label. If a user on a screen reader is tabbing through a form, they might not get that information.

**Comment by joshkimux** [comment]
@jaredcunha is the `aria-describedby` fix to the `hint` still not completed yet? 😱

**Comment by carly-yamrus** [comment]
@jaredcunha @joshkimux @coforma-terry Alex Sherrow confirmed with you all yesterday that this is no longer an issue.Are one of you able to close out this PR/Work item so that it is no longer showing active?

**Comment by joshkimux** [comment]
@carly-yamrus this has been fixed, so we can close, but a new ticket (likely a defect-4) may need to be created to address a minor concern around verbosity for screen readers. We'd need to answer:
- is the DST's hint text using `aria-describedby` to be programatically linked to the label
  - if so, write a ticket transitioning descriptive text to hint text instead of within the label for a pause to be present between the label and description
  - if not, search to see if an existing bug ticket exists for the DST's hint text
    - if a bug ticket exists, write the defect-4 ticket but mark it as blocked until DST resolves the bug
    - if it doesn't exist, we'll need to write a but ticket for DST

**Comment by MichelleDieudonne** [comment]
@joshkimux  @AlexanderSherrow Are we closing this item, it is still showing open?  Is it just that we are waiting for the new issue above to be filed before this is closed?

**Comment by joshkimux** [comment]
[I've added this as a bug for DST](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1334#issuecomment-1451913743). Please create a new `defect-4` to note the verbosity issue in this ticket. If you need help creating that ticket, please reach out to the CAIA team 🙏
