### ISSUE TITLE
508-defect-1 ❗ Relationship to service member information isn't announced to screen reader users

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#47457]
## Point of contact

Josh Kim

## Severity level

1, Launchblocker. Critical. Must be fixed before launch.

## Details

https://user-images.githubusercontent.com/14154792/192024256-9dfbc341-654f-4287-8988-12a29a8cb393.mov

Additional information appears when a user selects different radio options in the question "Relationship to service member(*Required)." As this information isn't in the natural tab order and sits between radio options (which screen reader users navigate using the up and down arrow keys), they will not be announced to screen reader users.

## Reproduction steps

1. [Start the pre need flow without signing in](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information)
2. On the first page, turn on your screen reader and select any of the options
3. Using your up and down arrow keys, confirm that the additional information is not read out to screen reader users

## Proposed solution or next steps

There are several methods to resolve this ticket

## [Bandaid] Use `aria-describedby` (doesn't change the design) 

We can connect the added information to the radio option using `aria-describedby` so it announces out to users. Although this doesn't change the design, it may be unlikely that a user will wait long enough to hear the description (see video below).

https://user-images.githubusercontent.com/14154792/192025309-e35c59e6-d296-4048-9d10-b16f3596989b.mov

## [Long term fix] Provide their information on the following page

Assuming that users _don't need_ the additional information to make a choice, we can simply provide the additional information on the following page (as a confirmation notifying them of the following steps).

<img width="374" alt="Screen Shot 2022-09-23 at 1 46 20 PM" src="https://user-images.githubusercontent.com/14154792/192026771-34f46b55-7eac-4f46-937f-cc6e5c950fe9.png">

## References, articles, or WCAG support

1. [Wizards are now deprecated](https://design.va.gov/patterns/wizards)
2. [One thing per page](https://www.smashingmagazine.com/2017/05/better-form-design-one-thing-per-page/)

## Type of issue

- [X] Screenreader
- [ ] Keyboard
- [ ] Focus
- [ ] Headings
- [ ] Color
- [ ] Zoom
- [ ] Semantics
- [ ] Axe-core
- [ ] Something else

**Comment by jaredcunha** [comment]
@joshkimux In similar tickets, we've also added `role="status"` to the information box because its contents are not apparent if the user is tabbing through.

**Comment by joshkimux** [comment]
@jaredcunha that's a great idea! If we go for the bandaid solution of `role="status"` and `aria-describedby`, we can bump this down to a `508-defect-4`  😄

**Comment by jaredcunha** [comment]
@joshkimux Similar to my comment in [#22622](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22622#issuecomment-1265759243), curious what the preference is between using `role="status"`/`aria-describedby` reading the text twice.

**Comment by joshkimux** [comment]
@jaredcunha Again, this is really tricky and will require some subjective takes (unless we can do testing with actual screen reader users). 

If this information is important, I think it may be worth keeping `aria-describedby` even if it makes the experience more verbose as at least it will be programmatically linked to the radio buttons (permanently, not temporarily announced).

If it's not important, and arguably skippable, it may also not be worth the added verbosity.

What are your thoughts on the one thing per page approach here of providing the confirmation or additional details on the following page as opposed to as an immediate response within the radio buttons? Is that technically feasible now?

**Comment by sonntag-adam** [comment]
@joshkimux the fix is in staging.

**Comment by joshkimux** [comment]
@sonntag-adam 🥳 awesome! @coforma-terry can we find a specialist/log a CAIA ticket to validate and close this out?

**Comment by SarahKay8** [comment]
@sonntag-adam Validated. Thanks, everyone!

https://user-images.githubusercontent.com/102324990/221691854-86988896-1410-460d-bf59-c870a662b560.mp4
