### ISSUE TITLE
Increase default timeout across our services.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#47455]
## Description
We've been experiencing a lot of gateway timeouts recently due to calls exceeding the 15seconds threshold we've set as default. We want to increase this default to 55seconds.  This is for both v0 & v2.

---

## Acceptance Criteria
v0 & v2 services have a default timeout of 55s.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ajmagdub** [comment]
Increased default timeout from 15 seconds to 55 seconds. Removed all timeout overrides, since they were equal to or less than the new default timeout of 55 seconds.
