### ISSUE TITLE
Memorable Date Component Bugs

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47467]

**Comment by loripusey** [comment]
@acrollet what would you think about having @wullaski work on the bugs in this Epic this sprint to help get him up-to-speed?

**Comment by acrollet** [comment]
@wullaski how would you feel about working on these? I'd be happy to pair and look at things together, the first thing to do will be to narrow down whether the problems are with the component or our implementation/custom validation.
