### ISSUE TITLE
508-defect-1 ❗ Note on national cemeteries is not programmatically linked to the national cemetery question

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#47468]
## Point of contact

Josh Kim

## Severity level

1, Launchblocker. Critical. Must be fixed before launch.

## Details

Screen reader users in forms mode (e.g. using the `tab` key as they anticipate only form fields, not static text fields) will likely miss the note describing the VA national cemetery question (as it is sandwiched between two interactive elements).

https://user-images.githubusercontent.com/14154792/192038422-8275c02f-8df9-485e-b73e-b0d63869ea90.mov

## Reproduction steps

1. [Begin the pre need flow unsigned in ](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information)
2. Get to step 3 
3. Turn on your screen reader and tab through the page
4. Confirm that the note "Please note: This doesn’t guarantee you’ll be buried in your preferred cemetery. We’ll try to fulfill your wishes, but will assign a gravesite in a cemetery with available space at the time of need." is not read out

## Use the [additional information component](https://design.va.gov/components/additional-info)

As the additional information component is interactive, it will fall within the natural tab order

<img width="822" alt="Screen Shot 2022-09-23 at 3 03 43 PM" src="https://user-images.githubusercontent.com/14154792/192039287-53d276f2-e640-4d4e-9f28-c2a4c0378c78.png">

## Use `aria-describedby`

We can also programmatically link the note to the input field using `aria-describedby`

<img width="1210" alt="Screen Shot 2022-09-23 at 3 05 45 PM" src="https://user-images.githubusercontent.com/14154792/192039707-ba8e06c0-da6a-476a-8466-55e83f3de5fa.png">

## Type of issue

- [X] Screenreader
- [ ] Keyboard
- [ ] Focus
- [ ] Headings
- [ ] Color
- [ ] Zoom
- [ ] Semantics
- [ ] Axe-core
- [ ] Something else

**Comment by jacobworrell** [comment]
We're going to use the aria_describedby solution.
