### ISSUE TITLE
Update PromoBanner docs on design.va.gov after HTML changes

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4747]
In this [pull request](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/203), we updated the PromoBanner in the design system to add support for wrapping text to meet the requirements for the global downtime message. However, we had to change the PromoBanner's HTML to do so. We need to update the sample HTML on [design.va.gov](https://design.va.gov/components/promo-banners) to reflect the most up-to-date version.

**Comment by MickinSahni** [comment]
2020-02-10 PW Standup
- PR merged and just needs to be validated 
  - design.va.gov promobanner under components
     - review changes https://design.va.gov/components/promo-banners
