### ISSUE TITLE
SOCKS access for Michael Hobson

### ISSUE THREAD

**Issue by michaelhobson** [department-of-veterans-affairs/va.gov-team#47474]
### Your Name

Michael Hobson

### Your Email

michael.hobson@adhocteam.us

### Your Role and Team

Product Manager on Banana Peels (Appeals APIs, lighthouse)

### Product Manager (PM) name and email

Me, michael.hobson@adhocteam.us (or shaun.hobson@va.gov)

### Product Owner (PO) name and email

Premal Shah, premal.shah@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsjxatYGoAdrm2lz7CyYO+rCC3OpiUgH0uTMKKd9jkNC0aPE/tQ+NWSbgmthamsT982zGm3ikxAwdQ6sRWbtZiq0CdYZpHPM4UrRTgZsoLhEtEN6l4ICRsZve60BRV2WYmHa9BiU1IuQXALv+G89k1ohVl0RDojuSxkN3qyNOIXXZTEBulRX2MtKV7Ipq8i4/ZsqVRNiiIRFWkGAsKd/EXA0bofgGJu7/11l/3X3XYYuJEtO6SZfvu6g5/EH5O0Z8ebMazXHN7gEjK7oe2E0CRRE2Mze8upJGeot63F9vsBdszRHhsUuYrz2ejXKqZgmxHUCZ+tuVbXpJ/7rDDCVd8rK58TF0an51ajrlWKsYvBsBvMQFb5md47PZ3VJAXAVF2Gw72O1GPhgBBW86U1YP/DVTIBUZDLSIT89U1Ya2g0IW2GaQfGnMI1efk6+7Rd0jb/BhQO5NsB+zSYlomXq0hYpFQEMwg7MLGHu4rNPBh+eMneT+Gp9TjCqvtxKUJq28= smh364@MichaelHobson-HP

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
