### ISSUE TITLE
Move Load Testing documentation from the `devops` repo to Platform Website

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#47482]
The documentation for load testing VFS applications lives in the `devops` repo, but it would be useful to move it to the Platform Website where it could be searched for easily.

**Comment by it-harrison** [comment]
Published to Developer Documentation

**Comment by pjhill** [comment]
Hooray, nice job! Documentation fits in nicely [here ](https://depo-platform-documentation.scrollhelp.site/developer-docs/load-tests)and looks good.
