### ISSUE TITLE
Adding Blake Organ to DSVA Slack

### ISSUE THREAD

**Issue by dawnpruitt** [department-of-veterans-affairs/va.gov-team#47504]
Respectfully requesting multi-channel DSVA slack access for Blake Organ (blake.organ@civicactions.com). 

Blake is our new Product/Content Designer for Sitewide Crew which requires him to work cross-functionally with product teams. 

Please add him to the following channels:
sitewide-public-websites
vfs-all-teams
vfs-change-announcements
cms-design
sitewide-cms
sitewide-facilities
sitewide-program
victories
random

**Comment by dawnpruitt** [comment]
Reopening ticket to respectfully request Blake's access be changed to FULL MEMBER from multi-channel guest. It was my error, thank you so much!

**Comment by cmaeng** [comment]
this was resolved through slack [here](https://dsva.slack.com/archives/C01S729LX6X/p1666626584040279)
