### ISSUE TITLE
GIDS: Allow user to update crosswalk values for WEAMS data that has an IPED or OPE match

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4751]
As an EDU Team Member, I need the ability to link the Dept of Education IPEDS data to the VA EDU Services WEAMS data so that the correct information is displayed on the Comparison Tool Profile Page.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The 'Crosswalk' column has an 'Actions' sub-column.
2. The following actions are available for each row in the column:
     a. Add blank OPE/IPEDS data to Crosswalk
     b. Add WEAMS OPE/IPEDS data to Crosswalk
     c. Add IPEDSHD OPE/IPEDS data to Crosswalk
     d. Manually add OPE/IPEDS data to Crosswalk
3. If the user takes the "Add blank OPE/IPEDS data to Crosswalk" action; the crosswalk data source is updated with an entry that contains the following information:
     a. facility code: matches the WEAMS data
     b. institution name: matches the WEAMS data
     c. city: matches the WEAMS data
     d. state: matches the WEAMS data
     e. ipeds: [blank]
     f. ope: [blank]
     g. notes: [user entered]
4. If the user takes the "Add WEAMS OPE/IPEDS data to Crosswalk" action; the crosswalk data source is updated with an entry that contains the following information:
     a. facility code: matches the WEAMS data
     b. institution name: matches the WEAMS data
     c. city: matches the WEAMS data
     d. state: matches the WEAMS data
     e. ipeds: matches the WEAMS data
     f. ope: matches the WEAMS data
     g. notes: [user entered]
5. If the user takes the "Add IPEDSHD OPE/IPEDS data to Crosswalk" action; the crosswalk data source is updated with an entry that contains the following information:
     a. facility code: matches the WEAMS data
     b. institution name: matches the WEAMS data
     c. city: matches the WEAMS data
     d. state: matches the WEAMS data
     e. ipeds: matches the IPEDS HD data
     f. ope: matches the IPEDS HD data
     g. notes: [user entered]
6. If the user takes the "Manually add OPE/IPEDS data to Crosswalk" action; the crosswalk data source is updated with an entry that contains the following information:
     a. facility code: matches the WEAMS data
     b. institution name: matches the WEAMS data
     c. city: matches the WEAMS data
     d. state: matches the WEAMS data
     e. ipeds: matches the user specified data
     f. ope: matches the user specified data
     g. notes: [user entered]
7. For AC 3 - 6; the user is displayed a preview of the data that will be updated within the crosswalk.
8. On save:
     a. If a crosswalk entry exists, the entry is updated with the data.
     b. If a crosswalk entry does not exist, an entry is created with the data.
     c. The row is removed from the "Crosswalk issues" table if the WEAMS IPEDS/OPE matches the Crosswalk IPEDS/OPE matches the IPEDS HD IPEDS/OPE values.
9. If the user cancels, no action is taken.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/549

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `bah-crosswalk-fix`

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-01-30 at 7.27.50 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/14be8aa4-5a80-4e07-8c0a-91030aa10580)

---

![Screen Shot 2020-01-30 at 8.02.56 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b5881f9d-40ab-406f-b101-c637c7f14bac)

**Comment by delli-gatti-michael** [comment]
Functionality is now in Staging but blocked by defect #5613.

**Comment by delli-gatti-michael** [comment]
#5613 has been resolved and this functionality is now present in Staging. Closing this issue.
