### ISSUE TITLE
New Vietnam Veteran health care Q&A for PACT Act page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#47519]
We're preparing to add this new Q&As to the PACT Act page:

https://prod.cms.va.gov/resources/am-i-eligible-for-va-health-care-as-a-vietnam-veteran

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn (cc @laurwill). Could you copy edit this one Q&A today? I'll also send you a reference doc to check the dates against. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Note: We do **not** want to publish this Q&A yet. We just need to have it ready. Thanks!

**Comment by megzehn** [comment]
Thanks, Danielle! I reviewed this and left it in drafts.

**Comment by RLHecht** [comment]
This has been published. Closing ticket
