### ISSUE TITLE
[UX] MyHealth: Secure Messaging: Support research and design

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#47515]
## :star2: Description
The core team and MHV teams will need some support as the complete research and design tasks for Secure Messaging.

## :star2: User Story
As a Veteran, I want to have an interface that has been agreed upon by USDS and the teams building it so that I know it has been designed to be as user-friendly as possible.

## :star2: Acceptance Criteria
Designers and researchers on MHV to VA.gov teams have gotten the support they need while completing their research and designs.

**Comment by coultonbunney-usds** [comment]
@MarciMcGuire How is this different than #47609?

**Comment by MarciMcGuire** [comment]
🤦‍♀️it's not; I forgot I created that one yesterday.  I'll close yesterday's since this one is consistent with the one for Medical Records.

**Comment by MarciMcGuire** [comment]
This work has been completed
