### ISSUE TITLE
Adding Paul Short to DSVA Slack

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4752]
Paul Short, a new engineer, is starting with the VSA Project. Could you please add him as a full member to the DSVA Slack?

Email:
pshort@governmentcio.com

Channels to join:
#vsa
#vsa-engineering 
#vfs-platform-support
#vetsgov-fe
#vetsgov-engineer

Thank you!!

**Comment by LEHigley** [comment]
@YanaRoy this is done, but didn't see the last two channels (#vetsgov-fe or #vetsgove-engineer)

**Comment by short000** [comment]
Unable to login using GovCIO account. My email pshort@governmentcio.com and password works for governmentcio-fed.slack.com but the same credentials do not work for dsva.slack.com:
![login-failed](https://user-images.githubusercontent.com/6720077/72192367-157b4800-33cb-11ea-8834-d17b785e7948.png)

**Comment by short000** [comment]
Sorry, my bad. I missed the registration email. I had already registered with Slack under the GovCIO subdomain, but had to also register with the DSVA subdomain separately, even though both logins use the same email address. I'm closing the ticket.
![missed-registration-email](https://user-images.githubusercontent.com/6720077/72193796-a9034780-33d0-11ea-9bed-cb443273e565.png)
