### ISSUE TITLE
Update copy on find-va-forms

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#4753]
# Description / User Story
The content on the `/find-va-forms-beta` page needs to be updated. This ticket is a dev-ticket related to [3604](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3604).

# Screenshots
### Current Content:
![Current Content](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/6aac13f2-a2db-46f1-b56d-f753d7a9d228)

# Acceptance Criteria
- [ ] Instead of the intro text underneath that H2 that's there it should read: `You can now do many form tasks online, like filing a disability claim or applying for the GI Bill. Get started online, and we’ll walk you through step-by-step.`

**Comment by Karak888** [comment]
moving to close.
