### ISSUE TITLE
[Datadog] Set up monitors and alerts for EKS Ingress

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47545]
## Product Outline
[Monitoring using DataDog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593917/Monitoring+using+DataDog)

## High-Level User Story/ies
As a VA.Gov Platform Operator, I need monitoring for EKS Infrastructure components to help maintain the availability of platform services _(and their dependencies)_. 

## Hypothesis or Bet
_Thoughts:_ Platform operators should be able to
- acknowledge issues more quickly 
- respond to issues with better information 
- address issues proactively 

_Note: Can we tighten these up and measure specific outcomes?_

## Tech notes
- Datadog: [Platform Monitors and Alerts dashboard](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors--alerts?from_ts=1665677627710&to_ts=1665681227710&live=true)

### What must be true in order for you to consider this epic complete? 

**Dashboards exist for the following:** 
- [ ] EKS Ingress
  - [ ] dev
  - [ ] staging
  - [ ] production
  - [ ] sandbox
  - [ ] utility

Note: Multiple services can be displayed on the same dashboard, _ie there does not need to be a dashboard for every service, but that service should be represented on a dashboard_. 

**Monitors exist for the following:** 
- [ ] EKS Ingress
  - [ ] dev
  - [ ] staging
  - [ ] production
  - [ ] sandbox
  - [ ] utility

**Alerts exist for the following:** 
- [ ] EKS Ingress
  - [ ] dev
  - [ ] staging
  - [ ] production
  - [ ] sandbox
  - [ ] utility

Note: Alerts should be routed to the appropriate channel/personnel based on the alert's severity.

**Comment by jhouse-solvd** [comment]
This epic is nearly done but will carry into the next sprint. 

The issues are in the review column, but we'll need a little bit of time to get them reviewed and closed out.

**Comment by jhouse-solvd** [comment]
Multiple team members have been out of the office recently, which has impacted our ability to complete this. 

But now that @ph-One is back, he should be able to review and provide feedback, and then we'll get this over the line.

**Comment by npeterson54** [comment]
Not quite complete, rolling into next sprint
