### ISSUE TITLE
test connection to gettraits by cspid

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#47547]
email from Savita:
You will be connecting to MVI directly using this endpoint https://ps.int.iam.va.gov:8957/psim_webservice/IdMSSOeWebService

You can create a SOAP UI/Postman project using this wsdl https://ps.dev.iam.va.gov/psim_webservice/IdMSSOeWebService?wsdl

Sample request is in this email. We can have a quick call if you have some questions. Let me know if I am missing something.

If you are not able to use this information to test the MPI call, report in the comments why so we can iterate with Savita.

**Comment by bramleyjl** [comment]
@joeniquette can you find a copy of this email still? The sample request it has didn't make it over to this issue ticket.

**Comment by bramleyjl** [comment]
Reduced priority - we don't believe we'll need to add `sec_id` creation/IAM calls for SiS user account creations in the near future

**Comment by alyssagallion** [comment]
Not working on this any longer, closing.
