### ISSUE TITLE
SOCKS access for Steve Long

### ISSUE THREAD

**Issue by stevelong00** [department-of-veterans-affairs/va.gov-team#47555]
### Your Name

Steve Long

### Your Email

steven.long@adhocteam.us

### Your Role and Team

Software Engineer on Team Quokka

### Product Manager (PM) name and email

Mike Compton mike.compton@adhocteam.us

### Product Owner (PO) name and email

Andrew Fichter andrew.fichter@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCugmbruzJqkwBn+/D9lbXl1GeYPxq3FKIYAXJFNw3OS3isFzp88VHNRUFaHtqC19CD/RW6Nrr1E3/AHtjlXjAQO629Q/npP6vLPjVXOvsB6K2JGw8kCCVGn5ftupYVrqLu8R6zjEZ7PnnJVPVEyxneaBxxR4lzUbYHHiP31DgRNPtLswlH2jxFnhZOq0JVb8pN8Vc+4A+BNDoHYcr7OxG7OAYAOdhc0HnfVMXqHn0UghX94sWFSa1XV0/knx9FbyQXW8DmCpYEoP9h2zgyhh8FH+JFpCAiCEOBZZNXa6DGuA9J8oPRFLHNjWcpUBaLEbheJPiIMSf5XFuugadUlu6ZBAuH8Qh9NoNeDSIUBfpE1TwokGwiGNBj3YEdoszWZc1K+ZRQV5D1wISMN1l6/izTEXA5RiB/GPc/p7plGr3vFiaLBnqh+q7FDz4Z6MWWouGlicGGzbFrUvn8CtK6Bd5Po4mPpmI1qk6wI7oel59VkLkoll+xkhxlZ/+ERY9MKA0= steve@SteveLong-HP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
Looks like this has been merged and accessed already. Closing ticket. Please reopen should you run into any issues or open a new one
