### ISSUE TITLE
Design intent - design feedback - Authenticated Experience, My VA, Audit UX Improvements

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#47550]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Be sure to consider how this page will look with alerts and notifications
- We have noticed alert fatigue on va.gov. I do not believe you need an alert style for the verify identity

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Green buttons are reserved for log in only. Replace the green button styles with primary styles.

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by ajakabcin** [comment]
Closing - this was corrected in designs and incorporated into development. Visible on staging with LOA1 user.
![Screenshot 2023-03-09 at 3 23 52 PM](https://user-images.githubusercontent.com/45603961/224147029-e98a9090-83cd-424d-a9bc-d9f046a3bf46.png)
