### ISSUE TITLE
[ONGOING] Analyze VSignals Weekly

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47569]
## Tasks
- Analyze the VSignals spreadsheet on the VA network
- Tag entries with the identified tags
- Write research summary
- Post report on GitHub

**Comment by loripusey** [comment]
## Tasks
- Analyze the VSignals spreadsheet on the VA network
- Tag entries with the identified tags
- Write research summary
- Post report on GitHub

**Comment by kristenmcconnell** [comment]
@loripusey I cleaned up the VSignal spreadsheet and shared edit access with your VA email. Let me know if you don't have access. I also added this week's report to the spreadsheet. You'll be synthesizing Rows 365 to 627. I'm still synthesizing rows 112 to 365. If you have any questions, let me know.

**Comment by kristenmcconnell** [comment]
For the sprint starting on Oct. 19, rows 628-1106 will need to be synthesized.

**Comment by kristenmcconnell** [comment]
For the sprint starting on Nov. 2, rows 1107- 1397 will need to be synthesized.

**Comment by loripusey** [comment]
@kristenmcconnell since you are the only one that gets the spreadsheet, how can we get someone else added to the distribution list. Perhaps @ben, @sarahknoppA6, and myself could get added?

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell @kellysmith1008 has the VSignals spreadsheet been updated with the current sprint's analysis? Just wanted to ask before I add the new data for next sprint.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Yes sir. I've gathered the information I need for the report and will publish it later today. Feel free to add the new data. Thanks!

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Could you send me a link to the new data? I thought I read somewhere that it was being moved out of Kristen's OneDrive but I can't find the new location. Thanks!

**Comment by benbrasso-agile6** [comment]
It was moved to my drive. There are a couple related comments in this ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/49136

You should have received an email to your VA email where the file is located in my drive. Do you need the link again?

**Comment by kellysmith1008** [comment]
Ah, no sir - I was looking through my CA email instead of my VA one. I've uploaded the 11/15 excel file. Thanks!

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell new data is in the spreadsheet

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell is this still a 3 point task or should we increase? I figure 1 pt is for pulling new data into spreadsheet.

**Comment by benbrasso-agile6** [comment]
Comments added for past 2 weeks

**Comment by kristenmcconnell** [comment]
The number of points really depending upon the number of comments each week. 618 comments like last time will take more time, than 200 and something comments. I would say that 3 is still a good average.

**Comment by kristenmcconnell** [comment]
[Dec. 23 summary.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/VSignals/2022-12-23-VSignals.md) I didn't quite get to finish the process documentation, since I was playing around with more graphs.

**Comment by benbrasso-agile6** [comment]
Requested data from 12/14-12/27

**Comment by kristenmcconnell** [comment]
I just sent a DM to Jason Woodman (at Kevin Hoffman's suggestion) to find out more about the VSignals DOMO pilot that occurred sometime in the last 6 months.

**Comment by kristenmcconnell** [comment]
I found out about a sentiment analysis tool that VA has already, but only VA employees can access it. I sent a Slack message to Stephen Barrs and Patrick Bateman on 1/6 to see if they could get access for us/how they wanted to proceed.

**Comment by cgednalske** [comment]
Here's the [January 24 VSignals summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/VSignals/2023-01-24-VSignals.md) - following the format of the previous summary but starting to look at weekly trends.

**Comment by benbrasso-agile6** [comment]
@cgednalske nice work!

**Comment by cgednalske** [comment]
Here is the latest VSignals data in an new [VSignals Trends report format](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/VSignals/VSignals-trends.md). 

We iterated on our process this sprint to focus on a growing overview of trends throughout all reporting periods, with only Mobile Check-in and General Check-in data included. The new doc includes graphs for these two categories + any interesting/important comments or topics the reviewing team member noted. Both sections will be updated each reporting period directly in this document.

**Comment by benbrasso-agile6** [comment]
Nice work

**Comment by loripusey** [comment]
I like it! Great job @cgednalske

**Comment by loripusey** [comment]
FYI, This was an ongoing ticket. I'm going to create a template and do a new ticket each sprint for this work.

**Comment by benbrasso-agile6** [comment]
Makes sense thx
