### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by devinderr** [department-of-veterans-affairs/va.gov-team#47561]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: devinderr
- Reason access is required: I work for Riley Ross in OIT.  When processing of the vets.gov spool file fails, it needs to be debugged.  I need access for that.  The processing message are located in: https://app.slack.com/client/T03FECE8V/C01T05TPTQQ .

**Comment by ericboehs** [comment]
You need to be a member of our org to join the team.
