### ISSUE TITLE
[SCREENREADER, KEYBOARD]: Focus on page load is on the breadcrumbs, but needs to be at the top of the page

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#4756]
# [SCREENREADER, KEYBOARD]: Focus on page load is on the breadcrumbs, but needs to be at the top of the page

## Description

When a screen reader or keyboard user first arrives on this page the focus is set on the breadcrumbs. This is different from other static page behavior and is disorienting. The user needs to know about the navigation area above, so the focus should start at the top, as with other static pages. 

## Point of Contact

Jennifer / Trevor

## Acceptance Criteria

As a keyboard user, I want to be able to navigate from the top of the entire page when it loads.

## Environment
 
* Browser: Safari
* Screenreader: VoiceOver

## Steps to Recreate

1. Enter `https://staging.va.gov/disability/view-disability-rating/rating` in browser
2. Start screenreading device listed in Environment
3. Reload page
4. Verify that the focus starts on the breadcrumbs

## Possible Fixes (optional)

Right now, this isn't in an application flow per se, it's more like a static content page. I'd like to remove the focus() from the breadcrumbs on first load. This is likely happening in the React container's componentDidMount() lifecycle method.

Since it's static, we want assistive tech users to be able to interact with the entire page. When this gets built out to include editing or more features, then we would go ahead and set focus on the `<h1>` when we change routes using React.

**Comment by jason-gcio** [comment]
@jenstrickland - in speaking to @cohnjesse, it looks like this is in the breadcrumb component itself and we don't have a great way to edit it.  Can this ticket go to Public Websites for their take?

**Comment by jenstrickland** [comment]
@1Copenut - What do you think? This issue was super disorienting in VoiceOver, as we observed during our meeting to review the behavior.

**Comment by 1Copenut** [comment]
I agree with @jenstrickland about this not being in application flow, and focus being better served at the top of the page. Looking at the page source quickly, it looks like focus is being called somewhere up the stack, possibly a Liquid template?

**Comment by jenstrickland** [comment]
@jason-gcio - perhaps we schedule a call with @cohnjesse and @1Copenut to discuss? That may speed up next steps alignment.

**Comment by 1Copenut** [comment]
@cohnjesse After meeting this morning, we determined that the Breadcrumb component was being rendered twice because of its placement inside the RatedDisabilityView.jsx file.

Nick suggested we move the following block out to RatedDisabilityApp.jsx, just above the `<RequiredLoginView />` on line 17:

```javascript
<div className="medium-screen:vads-u-padding-left--1p5 large-screen:vads-u-padding-left--6">
  <Breadcrumbs>
    {[
      <a href="/" aria-label="back to VA Home page" key="1">
        Home
      </a>,
      <a
        href="/disability"
        aria-label="Back to the Disability Benefits page"
        key="2"
      >
        Disability Benefits
      </a>,
      <a
        href="/disability/check-disability-rating"
        aria-label="back to the view your VA disability rating page"
        key="3"
      >
        View your VA disability rating
      </a>,
      <a href="/disability/check-disability-rating/rating" key="4">
        Your VA disability rating
      </a>,
    ]}
  </Breadcrumbs>
</div>
```

/cc @ncksllvn @jenstrickland @jason-gcio
