### ISSUE TITLE
Adding [sierra.nelmes@coforma.io] to DSVA Slack

### ISSUE THREAD

**Issue by jlang10761** [department-of-veterans-affairs/va.gov-team#47566]
Please add sierra.nelmes@coforma.io as a full member, they will be joining the CEDAR Benefits project as an designer. We will add them to the appropriate channels once they are in.

Please reach out to jeff@coforma.io on DSVA slack for any questions/clarifications.

**Comment by eunicegar** [comment]
Invite sent.
