### ISSUE TITLE
Midpoint review - design feedback -  Modernized Check-in, Patient Check-in, Beneficiary Travel

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#47567]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- The flow straight from travel reimbursement to check in without a confirmation or submit in between makes me think something went wrong or I missed submitting my travel expense. Consider adding a submit button or a confirmation letting the user know they are actually submitted the reimbursement request.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Align more closely with the card style on [design.va.gov](https://design.va.gov/components/card) (unbold body text, left align the button)

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by benbrasso-agile6** [comment]
@zach-park see the comment about the appt block on the Your Appointments page

**Comment by benbrasso-agile6** [comment]
@zach-park @kristenmcconnell you guys will want to respond to this ticket when ready, thanks

**Comment by zach-park** [comment]
The card UI style is updated. Also, the button (wihtin the card) is flushed left and right side as shown below: 

![card_button3.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/98c5d7c9-0528-4d43-933c-15c5ae642631)

**Comment by loripusey** [comment]
@zach-park @benbrasso-agile6 This wireframe does not look any different than what we had. Were these "must haves" addressed?
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/1601fcce-4d1e-4bc5-90bf-652bdbfaea53)

**Comment by benbrasso-agile6** [comment]
Or, was it that abstract/sketch were using the right ds component, but production was?

**Comment by loripusey** [comment]
then why would we need to update the wireframe?

**Comment by benbrasso-agile6** [comment]
So we don't get dinged next time at collab cycle :) Also, will wait for zach to chime in since he's closest to this.

**Comment by loripusey** [comment]
Got it

**Comment by loripusey** [comment]
can this ticket be closed then?

**Comment by zach-park** [comment]
@allison0034 , please note that we're already using the unbold for body content:

<img width="411" alt="card_body_unbold" src="https://user-images.githubusercontent.com/91493630/194101378-8d969f69-8b2d-464a-a037-ceac8f4d9bf7.png">

**Comment by zach-park** [comment]
For @allison0034 , one quick question... I believe that we're following the format for the card, but we have an inconsistency in terms of font format with another page as shown in the example below. Is it possible to use a mixed format like the attache example (e.g., **Time:** 9:26 a.m.)? Would you be able to advise us? 

<img width="275" alt="Screen Shot 2022-10-05 at 9 12 58 AM" src="https://user-images.githubusercontent.com/91493630/194110136-b0fd5aa8-0c6d-447a-98be-2ff4bd71a2af.png">
