### ISSUE TITLE
Remove downtime notification announcement

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4757]
### **Background:**  
There **was** a scheduled maintenance to the vets-api on 1/11/20, and Veterans, caretakers, family members, or other users of the website will need to be notfified that VA services will be down for a period of time. This code should now be removed.

### **AC:**
- [x] Remove downtime notification announcement.

**Comment by ncksllvn** [comment]
Done in this PR, https://github.com/department-of-veterans-affairs/vets-website/pull/11447. However, we created a follow-up to help clean up the logic - https://github.com/department-of-veterans-affairs/va.gov-team/issues/4757 - since it was done in a rush.

**Comment by ncksllvn** [comment]
Nvm, I misunderstood this issue. This ticket _is_ the follow-up.

**Comment by kelsonic** [comment]
Updated this ticket to tear down the code we wrote for the downtime announcement. @ncksllvn @Karak888

**Comment by Karak888** [comment]
Validated, moving to close
