### ISSUE TITLE
Add ICN to the LoROTA Entry

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47578]
## Tasks
- Complete this CHIP [ticket](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/1248)

**Comment by acrollet** [comment]
[PR](https://github.com/department-of-veterans-affairs/chip/pull/1288) has been created and is awaiting code review.

**Comment by acrollet** [comment]
This was shipped yesterday. https://github.com/department-of-veterans-affairs/chip/issues/1248#event-7672909908
