### ISSUE TITLE
Design: Tool for VFS teams to look up information from the accounts table

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#47593]
Currently, if a VFS team needs to know specific information about a user they want to test with, Trevor has to log into the EC2 instance on staging or prod to access the accounts table and get the information. 

If we build out a UI for folks to just view information from the accounts table, this will expediate VFS teams time to test and cut down on manual support for the identity team

This could potentially be a standalone tool or integrated into TUD -- whatever makes the most logical sense for the user journey. 

AC: 
Create design 
Test design

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
