### ISSUE TITLE
[SPIKE] Pass Users to Check-in when Access Pre-Check-in Link on Day of Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47595]
## Tasks
- What new endpoint from CHIP would we need?
- Think through the ramifications or potential side effects of implementing this
- What else....

## Questions
What do we do if the user needs an insurance review?

**Comment by loripusey** [comment]
Question: What should we do if the user needs an insurance review?
@acrollet

**Comment by acrollet** [comment]
I'd suggest that we develop specific wording (or take the existing text message wording) and explain to the veteran that they need to go to the desk to check in.
