### ISSUE TITLE
[PM] Payment Info V2: Prep for Staging Review

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47615]
## Background
This ticket is to prepare for staging review for the Payment Info V2 project.

## Tasks
- [x] Gather artifacts
- [x] Submit [request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D)

## Acceptance Criteria
- [x] Staging review is scheduled

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ NA
- _How can this work be validated?_ NA

## Resources
- [Background info on staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) _Note: we started this initiative prior to May 26 2022 which is the cutoff for switching to the new/current collab cycle request format_

**Comment by ajakabcin** [comment]
@ericasauv09 I broke this out to gather artifacts this sprint and complete it next sprint (#47869). Looking at remaining work, time for QA and turnaround on reports, plus leaving time to resolve any potential findings, I doubt we'll get the staging review complete within this sprint.

**Comment by ajakabcin** [comment]
Holding on this until we have a better idea of when QA will happen

**Comment by ajakabcin** [comment]
Started the ticket and have compiled a good portion of the artifacts to get us started - #48603

**Comment by ajakabcin** [comment]
Staging review scheduled for 11/3 at 2pm - all artifacts are submitted
