### ISSUE TITLE
alert on missing metrics from vets-api

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#4761]
## User Story or Problem Statement

Today we had a configuration update that went out which caused statsd metrics from vets-api to be sent to the wrong place, and they ended up not in Prometheus. There wasn't an alert that caught this immediately, it took someone discovering it while looking at dashboards to realize they had stopped. The statsd exporter itself does publish some metrics itself, so the number didn't go to 0 exactly. Also, a general rule to detect this situation would be really useful. How might we alert on a condition like this to catch it automatically?

## Goal

An alert that can detect a situation where there's a significant drop in metrics for a certain target type.

## Objectives or Key Results this is meant to further
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

## Acceptance Criteria
- [ ] Investigate and push out an alert to let us know when a large number of metrics are missing
- [ ] documentation for the on-call to understand this alert and how to troubleshoot

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
This same thing happened on HAProxy where a release of the haproxy_exporter caused issues and we stopped getting metrics. The exporter was "up" from Prometheus' standpoint, but there was a really small number of metrics making it to Prometheus.

**Comment by wyattwalter** [comment]
Prometheus has https://www.robustperception.io/absent-alerting-for-scraped-metrics, but the sentence is not reality for us:

> It's best to avoid metrics that appear and disappear, however it can happen that certain subsystems of a target don't always return all metrics that they should.

It's possible that a generic rule for this would be too cumbersome and we should focus on a few key situations and call it good enough until this component gets swapped out.

You can get a count of metrics on a specific job to detect a sudden drop, but that's normal for the way that labels are being done when a new "deployment" gets triggered. Don't run this on a graph query, but something like this does work `count({__name__=~".+"}) by (job)`.

**Comment by ricetj** [comment]
We need to keep this in mind when we move to DD.

**Comment by jhouse-solvd** [comment]
Please see #23513 for a more up-to-date iteration of monitoring where I've added this as an add'l consideration
