### ISSUE TITLE
[Application Hosting and Deployment] Document the packaging and deployment pattern 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47613]
## Description 
There should be operational documentation that explains the standardized pattern for packaging an application, pushing it to ECR, and updating the app manifests repo. The intention is to provide operators with enough information to be able to modify, improve, extend, or troubleshoot the current pattern. 

## Background / context 
ie, for every deployment to EKS, there are common components:
- manifests that live in the manifest repo
  - that should live under the new app of apps (“apps directory”)
- stuff that lives in infra repos for each component
  - ie infra-traefik
  - this is where we build out the image that gets pushed to ECR
  - store the version of the component/application
  - this drives updating the manifest repo
  - anything that needs to be packaged with the image lives in that repo
- automation / triggers
  - GitHub actions
    - build images and push to ECR
    - update manifests in the manifest repo anytime you make a change / update the version

## Acceptance Criteria
- [x] Documentation exists in Confluence explaining this pattern 
- [ ] Diagram exists in Confluence explaining this pattern

**Comment by jhouse-solvd** [comment]
This documentation would provide the detail behind [this](https://vfs.atlassian.net/wiki/spaces/OT/pages/2231304195/Platform+Diagrams#Overview-and-high-level-workflow) diagram.

**Comment by rmtolmach** [comment]
@jhouse-solvd Who is the audience for this documentation?

**Comment by jhouse-solvd** [comment]
@rmtolmach - I think the audience is primarily platform operators, but also developers using this system that want to understand the underlying "magic". Does that help?

**Comment by rmtolmach** [comment]
Clarified that "platform operators" is whoever would be maintaining or debugging this workflow. What was previously known as the individuals on the "Operations" or "Infrastructure" teams. 

Link to documentation: https://vfs.atlassian.net/wiki/spaces/OT/pages/2388885509/Details+on+app+onboarding+WIP

**Comment by jhouse-solvd** [comment]
One way to look at the pattern is from the user perspective. One way to look at the pattern is from the configuration or system perspective.

**Comment by oseasmoran73** [comment]
[Slack](https://dsva.slack.com/archives/CTYQL39FE/p1665163925885149?thread_ts=1665163693.975199&cid=CTYQL39FE) on current progress of this ticket

**Comment by jhouse-solvd** [comment]
Diagram of this pattern posted to confluence [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/2231304195/Platform+Infrastructure+Diagrams#Packaging-and-Deployment-Pattern)

**Comment by jhouse-solvd** [comment]
The documentation and diagram are good to go. Closing.
