### ISSUE TITLE
Midpoint review- IA Feedback - Modernized Check-in, Patient Check-in, Beneficiary Travel

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#47626]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

- Consult with sitewide content and IA on options for condensing and simplifying instructional text on [mileage claim screen.](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6/a/WK18Qln) 

**Consider:**
- Add some kind of system status alert when user adds mileage report. 

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by benbrasso-agile6** [comment]
Taking to talk to Danielle about

**Comment by benbrasso-agile6** [comment]
> Consult with sitewide content and IA on options for condensing and simplifying instructional text on mileage claim screen.

Action: Consulted with sitewide. Updated. 

Are you claiming only mileage and no other expenses today?

If you need to submit receipts for other expenses like tolls, meals, or lodging, you can’t file a claim now. But you can file your claim online 24/7 through the Beneficiary Travel Self Service System (BTSSS). Or you can use VA Form 10-3542 to submit a claim by mail, fax, email, or in person.  

> Add some kind of system status alert when user adds mileage report.

Action: No change. However, we tried it for the scenario when the claim won't be able to be submitted. E.g., we added an additional page. However, we all thought that adding that additional page would drastically cut down on the success of someone making it through to check in. We agreed that the priority of the app is on check in, where travel reimbursement is secondary. We may be able to address this consideration if/when we move to a different form UI pattern that better communicates progress in the overall form.

**Comment by benbrasso-agile6** [comment]
@jimuhh thank you for the feedback. all set.
