### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Modernized Check-in, Patient Check-in, Beneficiary Travel

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#47639]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
- I didn't think to mention this during the meeting, but I have some concerns around the placement of information alerts throughout the workflow. For screen reader users navigating via keyboard, they may hear the question and any information that comes before the buttons, then they'll tab through Yes and No and make their selection -- but never get far enough down the page to hear the info alerts that come after the buttons. If possible, move the alerts above the buttons. If that's not possible, when it goes to code we'll want to associate the alerts with the most-relevant Yes/No button using `aria-describedby`. That's a little more cumbersome, so moving the alert above the buttons would be my first choice!
   - Let me know if you have questions about this, since we didn't discuss it in the meeting. This would be a great thing to test with the Shared Support accessibility specialists, too.

**Consider:**
- Consider placing a confirmation message about the reimbursement request earlier in the workflow, before the check-in itself.
- Consider whether the claim number is necessary. If it's not something Veterans actually need, the long incomprehensible (and, for screen readers, unpronounceable) claim number is probably just going to increase cognitive load. If it is something Veterans need to know, provide more explicit text instructing them where they can find the number later if they're not able to save or write it down right away.
 

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by loripusey** [comment]
@benbrasso-agile6 let's talk through these recommendations

**Comment by benbrasso-agile6** [comment]
@loripusey using this ticket, for the moment, to represent progress across all the team's feedback. addressed some of the feedback via content. I sent this to danielle a moment ago. she'll either respond asynchronously or I'll catch her at office hours tomorrow. updated content and new suggestions are in here - https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit#heading=h.51654galu146

zach is aware of all of these.

**Comment by benbrasso-agile6** [comment]
> I didn't think to mention this during the meeting, but I have some concerns around the placement of information alerts throughout the workflow. For screen reader users navigating via keyboard, they may hear the question and any information that comes before the buttons, then they'll tab through Yes and No and make their selection -- but never get far enough down the page to hear the info alerts that come after the buttons. If possible, move the alerts above the buttons. If that's not possible, when it goes to code we'll want to associate the alerts with the most-relevant Yes/No button using aria-describedby. That's a little more cumbersome, so moving the alert above the buttons would be my first choice!

Action: Moved all notifications above Yes and No buttons

> Consider placing a confirmation message about the reimbursement request earlier in the workflow, before the check-in itself.

Action: We tried it for the scenario when the claim won't be able to be submitted. E.g., we added an additional page. However, we all thought that adding that additional page would drastically cut down on the success of someone making it through to check in. We agreed that the priority of the app is on check in, where travel reimbursement is secondary. We may be able to address this consideration if/when we move to a different form UI pattern that better communicates progress in the overall form. 

> Consider whether the claim number is necessary. If it's not something Veterans actually need, the long incomprehensible (and, for screen readers, unpronounceable) claim number is probably just going to increase cognitive load. If it is something Veterans need to know, provide more explicit text instructing them where they can find the number later if they're not able to save or write it down right away.

Action: Removed

**Comment by benbrasso-agile6** [comment]
@briandeconinck thank you for the feedback. all set.
