### ISSUE TITLE
Broken link on Sentry page

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#47630]
### Description
https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry contains a link to a README which is a broken link: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#runningtesting-sentry-locally

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#runningtesting-sentry-locally

**Comment by jhouse-solvd** [comment]
@mchelen-gov - I took a look at this. Sentry is now deployed via EKS [(configuration here)](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/sentry). There's a README but there's nothing in it yet. I'm not sure how useful or relevant that would be for VFS developers. 

Some options: 

- Part of me thinks it could be good to just **remove the line** _"For more in-depth technical knowledge, this [Sentry README](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#runningtesting-sentry-locally) defines the technical, architectural, and configuration details related to Sentry."_ entirely
- **Fill in the README** with useful info, or 
- **Link to the k8s deployment config** folder and write something like: _"Sentry deployment configuration can be found [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/sentry)"_

Thoughts? 

cc: @laucon

**Comment by laucon** [comment]
I think removing the line would be easiest. @mchelen-gov what do you think?

**Comment by mchelen-gov** [comment]
>  I think removing the line would be easiest. @mchelen-gov what do you think?

That's fine, we might want to review the rest of the page though because there are some other issues as well, like it does not actually include a link to Sentry instance.

**Comment by mchelen-gov** [comment]
@laucon This section still contains a link to Github markdown file:

> Before you begin
> In order to access Sentry you must have configured the SOCKS proxy. Proxy setup instructions are found in the [Internal Tools Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md).

**Comment by laucon** [comment]
@mchelen-gov Is it not supposed to contain a link to a Github markdown file? I didnt realize that that was a problem since the link is still working. But I'll go ahead and change that link so that it links to the platform documentation instructions for setting SOCKS proxy [here](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy).

**Comment by laucon** [comment]
@mchelen-gov Also, is this an ok link? https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-tagging-standards.md It appears at the end.

**Comment by laucon** [comment]
@jhouse-solvd On [this document](https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry), at the bottom it says "VFS engineers are responsible for complying with the Platform’s current [tagging standards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-tagging-standards.md)." But it links to [this github file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-tagging-standards.md) that says "We're moving our docs!" It sounds like we need to change that. Would it be better to replace [this link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-tagging-standards.md) with [this document](https://depo-platform-documentation.scrollhelp.site/developer-docs/sentry-tagging-standards) about Sentry tagging standards?

**Comment by jhouse-solvd** [comment]
Agreed on updating the link to "[Sentry tagging standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/sentry-tagging-standards)" on the Platform Website. 

And thank you for closing #47994 which appears to be a duplicate. :)

**Comment by laucon** [comment]
@jhouse-solvd Great! I changed the "tagging standards" link. It will appear as a new link once I deploy it on Monday at 3:30-ish. I don't want to close this doc just in case there are any other links Mike would like to change.

**Comment by jhouse-solvd** [comment]
Thank you @laucon ☺️

**Comment by laucon** [comment]
@jhouse-solvd I have now deployed this doc. So I am going to close the ticket. If there are any other links that you or Mike see that need to be resolved, just let my team know. Thanks!

**Comment by jhouse-solvd** [comment]
Thank you @laucon! ☺️
