### ISSUE TITLE
[Design] MyHealth: Medical Records: Create Prototype to Test with End Users

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#47638]
## :star2: User Story
As a designer, I want to create prototypes so that we can test our designs with users.

## :star2: Tasks
- [ ] Create prototype
- [ ] Work with Research to create any interactions needed for testing with end users
- [ ] Review prototype with team
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## :star2: Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities

<hr>

## 🌟 How to configure this issue
- [ ] Confirm this issue is being added to the correct team (ex. Core or MHV) and Product (ex. Secure Messaging) board
- [ ] Add App Name (ex. Secure Messaging) and Task Name to Issue Title ⬆️
- [ ] Fill in User Story ⬆️
- [ ] Link to any Related Documentation if appropriate, and remember to update if they change ⬆️
- [ ] Fill in Description ⬆️
- [ ] Add/remove Tasks as needed ⬆️
- [ ] Add/remove Acceptance Criteria as needed ⬆️
- [ ] Attach any Dependency stories, indiating whether this is a blocker, or is being blocked 
- [ ] If work is in progress, change Pipeline to In Progress :arrow_right: 
- [ ] Add any necessary labels not automatically included.  If this is unplanned work, add the `unplanned work` label :arrow_right: 
- [ ] If work is in progress, add Assignee(s) in addition to PM :arrow_right: 
- [ ] If Sprint is known, select it at the right :arrow_right: 
- [ ] If work has been sized, add story points :arrow_right: 
- [ ] Attach to an Epic (what body of work is this a part of?) :arrow_right:

**Comment by bryan-riley-va** [comment]
No longer needed
