### ISSUE TITLE
PM | Profile | Document Checklist

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47649]
## Background

Describe the issue background and scope

## Tasks
- [x] Compile a list of profile features and identify any sections that still need documentation (FE, BE, Design)

|Feature|FE|BE|Design | Notes |
|----------|--------|---------|-------------|--------|
|Personal Info|y| y| y|
|Contact Info| y| y| y|
|Military Info| y | y| y| 
| Direct Deposit| y| y| y| |
|Notifications| y| y| y | |
|Account Security |y|y|y| Sprint 85 #48365|
|Connected Apps| y| y|y| Sprint 85 #48381 |

**Comment by SKasimow** [comment]
@Samara-Strauss - we're close to finishing up documentation!

**Comment by Samara-Strauss** [comment]
Great! Thank you for letting me know, and for clearly documenting what is/isn't done. Looks like we're almost complete! 🎉

**Comment by Samara-Strauss** [comment]
Also, why is FE documentation for Connected Apps showing as N/A? Did you confirm with Adam that there isn't anything needed?

**Comment by SKasimow** [comment]
Yes I did and he said it was all Lighthouse so there wasn't really anything to note. I can ask him to add a sentence or two though so we have something in the section.

**Comment by SKasimow** [comment]
I spoke to Adam and asked him to add a quick write-up so there is something there.

**Comment by SKasimow** [comment]
Completed....
