### ISSUE TITLE
BE | Profile | Discovery | Planning: Identify Caching Opportunities for BGS Calls

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#47651]
## Background
Trevor Bosaw has added caching to BGS calls.  The purpose of this ticket is to identify if any opportunities exist for the Profile and My VA pages to adopt existing or similar caching of BGS calls.

## Tasks
- [x] Determine which supporting calls can be cached and create a ticket for each.
- [x] Create tickets for implementation.

**Comment by tpharrison** [comment]
@Samara-Strauss @SKasimow  - If you're okay with it, I was planning on using this ticket to first identify which areas of the profile can take advantage of the caching mechanism.  Once I figure this out, I can create the tickets and start the work this sprint.

**Comment by Samara-Strauss** [comment]
Sounds good! I'll update the title to make sure it's clear this is for planning.

**Comment by tpharrison** [comment]
Determined that the only other BGS request that can benefit from this caching is CH33 Bank Accounts.  Other calls go through EVSS.
