### ISSUE TITLE
STEM: Remove REAP Option from VA Form 1995

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4765]
As a benefits applicant, I should not be able to select the REAP benefit because it was retired in November of 2019.

## Assumptions:
1. This work will be completed behind a production / feature flag so that it is only available in the staging environments and below.
2. No action is to be taken on the page linked to in the "Learn More" link.

## Acceptance Criteria:
1. The "Reserve Educational Assistance Program (REAP, Chapter 1607)" is not an available benefit option when completing the 1995 form.

## Notes: 
Unsure if this "REAP" selection is in the schema, so check to make sure it doesn't need to be removed from there as well. 

@mattpointzxer0 commented on [Tue Oct 29 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19865)

From Luke T.
"I am asking that the option to select Reserve Educational Assistance Program (REAP, Chapter 1607) on the VA Force 22-1995 be removed from va.gov.

The ask is that the last option (highlighted below) be removed from page so that it is no longer an option.  The program officially ended on Nov 25, 2015 but some benefits were in place for up to three years.  At this point in time no one is able to apply for that benefit so it can be removed from the site."![image001.png](https://images.zenhubusercontent.com/5a60e1d24b5806bc2bc34c42/676edb09-1e92-4d43-8a23-0b5db10a07c1)

## PRs: 
department-of-veterans-affairs/vets-website#11562

**Comment by ksantiagomorgan6** [comment]
PR: 

https://github.com/department-of-veterans-affairs/vets-website/pull/11562

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-01-24 at 2.13.12 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c21c2b8e-6f5a-40ca-8b11-a0dc15aa0436)

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging. Closing this issue
