### ISSUE TITLE
[Spike] Improve VAOS process to look up the timezone - (BE)

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#47650]
## Background/Request
We need to update the facilities timezone offset in the preferred timezone VAOS FE is sending back (endpoint/name of field)
This would apply to direct appointment workflow.

Background:
For V0, we were sending the veterans preferred date with a 0 offset: desiredDate: ${data.preferredDate}T00:00:00+00:00Z and the facility timezone in a separate timezone field. It was confirmed that VAR appears to be ignoring the timeZone field on direct booking requests and getting the value from MFS v2 directly.
Vaos service doesn't do this so for v2, we need to send the veterans preferred date with the facility offset. i.e, if the facility's offset is UTC-5, we will send desiredDate: ${data.preferredDate}T00:00:00-05:00.

### Goal
Determine if it's possible for the BE to accept a flag from the FE that triggers vets-api to make an additional call to the facilities api to get the facility timezone.

### Requirements to Consider
- Can the BE append the timezone offset to the desired date field being sent?
- How can we limit this call to only direct scheduling appointment workflow?

---

## Tasks
- Answer the following questions:
  - Q

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ajmagdub** [comment]
The facility timezone lookup can be performed in Vets API. The VAOS::V2::AppointmentsService#post_appointment method can be modified, so that facility information is retrieved using the VAOS MobileFacilityService class. In the facility information is the facility's time zone. The desired date can then be modified within the post's body using the timezone if the appointment is directly scheduled, kind = clinic, and status = booked.

**Comment by simiadebowale** [comment]
Thank you @ajmagdub, I'll create a ticket to implement this change.
