### ISSUE TITLE
VA Request Flow - Preferred Dates (Acheron) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#47660]
## Description
Scheduling Manager is the service layer used to send the data for the VA request. There is a plan to sunset scheduling manager later this year. We need to send the VA request data to Acheron (new service). 

When a Veteran selects the preferred date(s) in VAOS, the front end will pass the 1st date in the `PID` field Patient Indicated Date and 2nd and 3rd date in the comments to Acheron. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_acheron_service` toggle is on

Given the user is in the VA request flow 
When the user selects one Preferred Date in VAOS
Then the VAOS app will pass the 1st preferred date in the `PID` field Patient Indicated Date 

Given the user is in the VA request flow 
When the user selects two Preferred Date(s) in VAOS
Then the VAOS app will pass the 1st preferred date in the `PID` field Patient Indicated Date and the 2nd date in the comments field

Given the user is in the VA request flow 
When the user select three Preferred Date(s) in VAOS
Then the VAOS app will pass the 1st preferred date in the `PID` field Patient Indicated Date and the 2nd and 3rd date in the comments field  

## Suggested Order for the comment fields: 

1. Contact Information (phone # and email) - #47730
2. 2nd and 3rd Preferred Dates 
3. Reason Code Abbreviation and comments #47734

**Suggested Format:** 
|label: DAY MON-DD-YY AM/PM| 

**For Example:** 
`If user selects 1 date`   |preferred Date: TUE OCT-18-22 AM|  
`If user selects 2 dates` |preferred Date: TUE OCT-18-22 AM, WED OCT-19-22 PM|  
`If user selects 3 dates` |preferred Date: TUE OCT-18-22 AM, WED OCT-19-22 AM, FRI OCT-22 AM|  

### Design Assets
No changes in the design 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
There is a new feature toggle for Acheron work #48250. cc: @simiadebowale

**Comment by jenniemc** [comment]
The location where patient preferred date values should reside per Brad C.

> requestedPeriods[] should have the earliest requested appointment time, and reasonCode.text should have everything else, including the other preferred appointment times

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
