### ISSUE TITLE
CT: Remove production flags for VET TEC feedback items.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4767]
As a developer, I need to remove the production flag so that minor content updates to the comparison tool are available in production.

## Assumptions:
1.  The work completed in story #4781 has been reviewed by the EDU team and signed off on as of 01/13/2020.

## Acceptance Criteria
1. The work completed in story #4781  is available in production.

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/11513

**Comment by delli-gatti-michael** [comment]
All functionality from the original story is present in a local production build

**Comment by delli-gatti-michael** [comment]
PR has been merged. Changes should be in production after today's 2:00 deploy

**Comment by delli-gatti-michael** [comment]
All Changes are now in production. Closing this issue
