### ISSUE TITLE
Remove "Issue Date" column from search results

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4768]
After performing a search on [Find VA Forms Beta](https://dev.va.gov/find-va-forms-beta/?q=), search results render in the form of a table with one of the columns containing "issue date." Our team was informed recently by the Lighthouse team that the "issue date" field has been shown to have no value to veterans, and doesn't really reflect anything meaningful. We should remove it so that all of the data contained in the results is meaningful to the user.

## Acceptance criteria
- [ ] Issue date is no longer rendered in search results table

**Comment by Karak888** [comment]
Validated per PR, moving to close.
