### ISSUE TITLE
Protected Route Sign-In redirect update

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#47691]
## Issue Description
When a unauthenticated(not signed in yet) user attempts to access a protected route they are redirected to the home page with SSOe sign in. This needs to be updated to redirect to SiS sign in page. 

## Tasks
- [ ] Update the protected route to redirect to SiS component.

## Acceptance Criteria
- [ ] When an unauthenticated user attempts to access a protected route they are redirected to the SiS sign in page.

**Comment by alyssagallion** [comment]
Unit testing now.

**Comment by alyssagallion** [comment]
Still in review.

**Comment by alyssagallion** [comment]
Requested update on review yesterday.
