### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#47695]
### Description
On Welcome page (https://depo-platform-documentation.scrollhelp.site/getting-started/welcome)
Under Analytics and insights the link is broken for 
"Here's how to set KPIs to track the success of your VA.gov solutions"
(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-protocol.md)
I'm guessing it should be https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-setting-protocol.md

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/welcome
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-protocol.md

**Comment by laucon** [comment]
Hi Elizabeth. Thanks so much for pointing this out. I fixed the link. I will deploy at 4pm today and then the link should be fixed on the platform website.

**Comment by laucon** [comment]
@elizabethkochBT I fixed this and deployed the document. :)
