### ISSUE TITLE
[Analytics Request] Discovery Education Data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#477]
## User Story
As an Education platform team member, I need to know what Education data exists so I can use metrics in my product decision making. 

## Goal
Education data request from Kevin, Matt, and Amy; original meeting coordination came via Slack via Kevin, and meeting will be on Tuesday, July 9th.

## Acceptance Criteria
- [x] Meet with the Education team
- [x] Provide summary of existing data (Nedie)

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@joanneesteban Shifting the `Milestone` since the training is on 7/9 and may have follow-up requests.

**Comment by nedierecel** [comment]
@jonwehausen Tagging you here to document any follow-ups from the meeting. If there are additional implementation items following our meeting, we can split off these into separate issues.

**Comment by jonwehausen** [comment]
# Meeting Notes

_Goal is to have in place by August 1. _

## Short-Term Needs
- Preferred provider filters
- Understand filter options being used (only captured as a boolean within URL currently)
- Profile Metadata (status, program length, for profit?, learn more clicks, size)
- Outbound to additional resources or institution page
- Cleanup comparison tool page capture...merge homepage with index.html

## Long-Term Needs
- Understand institutions / facilities viewed within the UI after search (search results)

**Comment by joanneesteban** [comment]
On implementation phase.

**Comment by nedierecel** [comment]
@KevinMHoffmanUSDS Please see the link to a [shared dashboard within the Education Modernized View](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/PPUZ37Q0SOi_CiRCBb-HBg/a50123418w177519031p184334251/). This communicates:

1. Total pageviews/trendline of the GIBCT Landing Page
- You'll notice in the table a very small set of `/gi-bill-comparison-tool` URLs that are formatted differently or use a different subdirectory structure. I left those in for now.

2. Top form fields selected on the landing page 

3. Users by State
