### ISSUE TITLE
[Design] Submit our Navigation Pattern to the Experimental Design System

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47716]
## Description
We need to submit our navigation pattern to the experimental design system. Our back button and how we display buttons is different. Our pattern was based off of the COVID screener. 

## Tasks
- Prepare documentation
- Submit to Design System

**Comment by kristenmcconnell** [comment]
@loripusey - @zach-park found out that they did add our pattern to the design system, so this ticket is no longer needed.
