### ISSUE TITLE
Content Review Request from Contact Center

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#47723]
## What does your team need support for? Check all that apply.
- [X] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [X] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [x] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to prototype or mockups: [Desktop prototype](https://sketch.com/s/cbb5c762-39e4-47bb-af88-22e693a4cb51/a/eK2jjlW/play)
- [Google Doc with content used for the prototype](https://docs.google.com/document/d/1Fhn_iBrWC3RSCXJ9hCUahLu6vFTUHkwGVcvGphn3wTs/edit)

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: No clear launch date yet, dependent on research and Design System council review.
- Estimated staging review date:
- Content and IA work needed by: If possible, 10/14 so we can do another round of research

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Chante Lantos-Swett (@clantosswett)
-	Product manager: Jason Woodman (@jwoodman5)
-	Designer: Ian McCullough (@ianMcCullough-ob)
-	FE engineer: Aubrey Arcangel (@aubreyarcangel) 
-	Product/team Slack channel: [vsp-contact-center-support](https://dsva.slack.com/archives/CNCEXNXK4) 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by manalo-soco** [comment]
@DanielleThierryUSDSVA  Checking in here. Are you able to help with the content review for this prototype:

Link to prototype or mockups: [Desktop prototype](https://sketch.com/s/cbb5c762-39e4-47bb-af88-22e693a4cb51/a/eK2jjlW/play)
[Google Doc with content used for the prototype](https://docs.google.com/document/d/1Fhn_iBrWC3RSCXJ9hCUahLu6vFTUHkwGVcvGphn3wTs/edit) 

Please let us know if you have any other questions. 
cc @jkwontheso @ianMcCullough-ob

**Comment by mnorthuis** [comment]
@heyjoni This will need IA work to determine placement, entry points, URL, and breadcrumb direction.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @manalo-soco. Thanks for checking in. I've been a bit behind due to travel for work and then illness. I'm reviewing this now. Also pulling in Mikki and Joni for an IA perspective. Thanks!

**Comment by jkwontheso** [comment]
Hi @DanielleThierryUSDSVA @mnorthuis @heyjoni, look forward to seeing your responses.

**Comment by heyjoni** [comment]
Hi @jkwontheso, I have just a few questions to help me better understand the context:
* How do we expect Veterans to get to this page? Will it be linked from somewhere (the login modal?)
* Once a Veteran complete the steps, where are we taking them? 

Thanks!

**Comment by ianMcCullough-ob** [comment]
Hello @heyjoni! Chiming in on this one.

- We would like to do further testing on the point of entry. One of the leading thoughts is from the login modal window, but we are also considering adding it to the [Signing In To VA.gov resources page](https://www.va.gov/resources/signing-in-to-vagov/).
- Once the veteran completes the step, they will be taken to either a page where they can submit a ticket through the appropriate credential or they will be given a phone number to contact the appropriate team. 

The goal is for them to reach out to the source of the issue (ID.me, MHV, DS Logon, etc) rather than reaching out to the VA contact center; often the VA contact center directs them to their credential provider depending on the issue. This tool is an attempt to eliminate the middle man, thus reducing the number of steps and time needed to resolve their issue.

Feel free to reach out to me for further clarification. Thanks!

**Comment by heyjoni** [comment]
Thanks for clarifying, @ianMcCullough-ob. These entry point ideas make sense. Would there also be login error states that you can test as entry points? 

Also, you might already have these in mind: when you do user testing, can you include a task that would help us understand how visitors look for the link? How would they look for it on the page?

For exit pages, once they see the ticket or phone number for the appropriate credential, would we take them back to whatever task/page they were on before they tried to log in?

**Comment by ianMcCullough-ob** [comment]
@heyjoni

Not sure I understand your first question. Are you asking if we would start with the error instead of starting with the login credential?

We have done some research around where users look for assistance with login problems, in general, to see if we can glean where we might be able to add the link. We'd definitely like to include questions like that in future testing to nail that down a bit more.

I have not considered exit pages that much. I did ask in previous research what their next steps would be after reaching the end of the tool, many just responded that they would open up a ticket or call. But I'm not sure how to handle the page itself. Do you have recommendations?

**Comment by heyjoni** [comment]
@ianMcCullough-ob Thanks for clarifying.

I meant for the login error pages to be additional entry points. I think it makes sense to have it on the regular login modal as a starting point and I'm wondering if making it appear (perhaps more prominently) on error pages as well might be valuable to test.

Regarding exit pages, it makes sense to just show the page where people can open a ticket, start a chat, or call since they'll probably want to refer to information on that page (phone numbers, issue IDs, etc.) when they contact customer service.

**Comment by ianMcCullough-ob** [comment]
@heyjoni sounds good! I'll look into having a link show on error pages, though there might be a barrier depending on who owns that error page (VA vs DS Login vs ID.me, etc).

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht I'm going to close this ticket since this work was paused on the contact center team side. Thanks!
