### ISSUE TITLE
Contact Center Review for Benefits Team 1 Download Decision Letter 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#47748]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Initial roll-out will be a new feature within the Claim Status Tool, but will eventually be a standalone tool.  The feature allows veterans to download their official claims decision letters, a specific type of notification letter the VA sends via regular mail. 

### Launch Date
Tentative Release Plan can be found [here](https://docs.google.com/document/d/11lj3v1yen6ypmqSkjRgHwIF6QsvV4GP_QzhfEAg7QfM/edit?usp=sharing). Stage A release scheduled for mid-late November, full release mid January.

### Version Number
1.0

### Product Guide
[Notification Letter Feature Product Guide - DRAFT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/Decision%20Letter%20Product%20Guide%20-%20DRAFT%20.docx)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Thank you, @MarciMcGuire and @jacobworrell, this draft looks good. FYI, I hid the name and address on the sample letter at the end of the document, for potential PII (even if it is fake, it's a real address). I will forward it to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. Draft is attached for reference.
[Notification Letter Tool Product Guide v1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9767655/Notification.Letter.Tool.Product.Guide.v1.docx)
