### ISSUE TITLE
Add alt text entry to style guide

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#47741]
## Stories

As a Veteran, I need relevant and meaningful alt text for images on VA.gov.

As a VA content author, I need clear and concise instructions on how to create relevant and meaningful alt text for images on VA.gov.

## What's needed

- Copy edit of entry content
- Add entry to style guide, in alphabetical order in the style guide's navigation list

Here's the content for the entry:

# Alternative text for images

## What alternative text is

Alternative text (also called "alt text") is a written substitute for a visual image on a screen. Alt text provides the content and purpose of the image to people who can't perceive the visual image. 

## Why we must provide relevant and meaningful alt text

We must provide relevant and meaningful alt text for images on VA.gov. This helps us make sure that everyone gets the same information—no matter how they interact with our site.  

For example:

- People who are blind or have low vision can listen to the alt text description of an image on their screen reader.
- People who've turned off images on their device because they have low internet bandwidth can read the alt text description instead.

### A note on decorative images

Images that are for decorative purposes only don't require alt text.

Here's when we consider an image decorative:

- The image doesn't provide important context to the page content, **and**
- The image isn't used as a link to direct people to more information

## How to create quality alt text

Follow these 5 tips to create relevant and meaningful alt text:

1. **Provide the same meaningful information the image provides.** Use clear, descriptive text to describe what the person needs to know from the image. Be sure to consider the context of the image within the surrounding page content as well.
2. **Be concise.** Use as few words as possible to tell the person what they need to know. Aim for no more than 150 characters. Concise content allows people to focus on the most important information.
3. **Avoid duplicate page content.** Only include unique information that's not also in page content near the image. Repeating information can cause frustration or confusion.
4. **Skip phrases like "image of", "photo of", or "graphic of."** Screen readers already announce that each image is a graphic. So you don't need to add this context. 
5. **Leave the image file name out of your alt text.** File names don't provide useful information and can cause frustration or confusion.

**Comment by megzehn** [comment]
Hi @DanielleThierryUSDSVA! I copyedited this and added it to github. 

Here's the PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1250

Let me know if you need us to do anything else. Thank you! 

CC @RLHecht

**Comment by RLHecht** [comment]
Moving this to validate and will close once it's live in the style guide.

**Comment by RLHecht** [comment]
This is now live. Closing!
