### ISSUE TITLE
Update NADL rate on Native American Direct Loan Rate page--PUBLISH ON 10/3

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47746]
## Issue Description
The NADL rate is changing on October 3. The new rate should be **5.50%**. We need to make this change on the [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) housing page. 

This page needs to be published on Monday 10/3.

## Tasks
- [x] Update rate 
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New rate is live on the site

**Comment by katherine-fung** [comment]
Hi @megzehn - this page is ready for copy edit. It needs to be published Monday, 10/3. 

http://preview-prod.vfs.va.gov/preview?nodeId=758 

I only updated the rate per requested. Just FYI it looks like you copyedited this page recently, in mid-July. 

cc @RLHecht

**Comment by RLHecht** [comment]
@megzehn I published this so it would get into the 9 a.m. build. Moving to validate and will close once it's live. Thanks all!

**Comment by RLHecht** [comment]
This is live. Closing ticket.
