### ISSUE TITLE
MISSION Act final phase updates to caregiver program landing page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#47753]
## Story

As a Veteran or caregiver, I need to know the latest eligibility information for the caregiver program.

## What's needed

The final phase of the MISSION Act goes into effect on 10/1. This phase expands caregiver program eligibility to caregivers of Veterans of all service eras.

We need to update content to reflect this update:

- Update [family member health benefits page](http://preview-prod.vfs.va.gov/preview?nodeId=32) to remove reference to specific time periods.
- Update [caregiver program landing page](http://preview-prod.vfs.va.gov/preview?nodeId=10) to reflect new eligibility criteria.
  - Update [alert component](https://prod.cms.va.gov/block/19?destination=/admin/content/alerts) that appears on this page to reflect latest communication update.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn @RLHecht. Could you please copy edit the preview pages listed here today? Please don't publish. I am actually going to publish these and do a content release tomorrow morning since that's when this new rule goes into effect. Thanks!

For reference, here's the Word doc with content updates to the main page and alert that our SME partner approved. Thanks!
[https://app.zenhub.com/files/133843125/09268810-3ade-47d8-a41d-4e23cc1f84fc/download](https://app.zenhub.com/files/133843125/09268810-3ade-47d8-a41d-4e23cc1f84fc/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn @RLHecht. Could you please copy edit the preview pages listed here today? Please don't publish. I am actually going to publish these and do a content release tomorrow morning since that's when this new rule goes into effect. Thanks!

For reference, here's the Word doc with content updates to the main page and alert that our SME partner approved. Thanks!
[https://app.zenhub.com/files/133843125/09268810-3ade-47d8-a41d-4e23cc1f84fc/download](https://app.zenhub.com/files/133843125/09268810-3ade-47d8-a41d-4e23cc1f84fc/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn @RLHecht. Could you please copy edit the preview pages listed here today? Please don't publish. I am actually going to publish these and do a content release tomorrow morning since that's when this new rule goes into effect. Thanks!

For reference, here's the Word doc with content updates to the main page and alert that our SME partner approved. Thanks!
[https://app.zenhub.com/files/133843125/09268810-3ade-47d8-a41d-4e23cc1f84fc/download](https://app.zenhub.com/files/133843125/09268810-3ade-47d8-a41d-4e23cc1f84fc/download)

**Comment by megzehn** [comment]
Hi @DanielleThierryUSDSVA - I reviewed your changes, and they look good! 

On the Family and Caregiver Health Benefits page, I made some minor tweaks to get the links under 100 characters. Let me know if that's OK!

**Comment by DanielleThierryUSDSVA** [comment]
Oh, that's great to get that link shorter - thank you, @megzehn!

**Comment by RLHecht** [comment]
These changes are now live. Closing ticket.
