### ISSUE TITLE
Fix Wireframes to Match Production

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47788]
## Tasks
- Fix Wireframes to Match Production
   - If there are designs in the wireframes that SHOULD be in the product, please bring these to Lori's attention. Here is [**the list of UX items**](https://docs.google.com/spreadsheets/d/1vr5m0tfqAtCtBFLMvn54aU9bdWhxR7GRxNkZzw42G10/edit#gid=0) that are reviewed with Lori in which we would need to update.
- Delete any wireframes that are not needed or obsolete (once collections are merged to the main Abstract branch we should consider archiving them)

**Comment by zach-park** [comment]
@loripusey we found additional updates (from the VA side) that needed to be updated so I added them to the spreadsheet in the AC. Also we found a bug (from VA) regarding the "Feedback CTA" ticket (also added to the spreadsheet: line 7 & line 23) that needs to be reported back to them to fix it. 

[Language toggle]
![Screen Shot 2022-10-18 at 11.20.28 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/2ca1fe33-1ba5-44e8-a592-8981145652db)


![Screen Shot 2022-10-18 at 11.12.00 AM copy.jpg](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/13e7a6a8-8bbb-4a11-87a1-9fc59b05f2ff)

![Screen Shot 2022-10-18 at 11.12.10 AM copy.jpg](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/797839f2-8f9e-4de2-bda0-06a1991f4066)

![Screen Shot 2022-10-18 at 11.07.46 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/924a9d51-bcc3-4aa6-b10d-d3fcfa1fdb65)

**Comment by loripusey** [comment]
I would think so yes
