### ISSUE TITLE
Analytics Implementation or QA Support for [10-10EZ]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#47780]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - 10-10 Health Apps team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - FE ticket #47706
    - [URL for Authenticated page](https://www.va.gov/health-care/apply/application/veteran-information/maiden-name-information)
    - [URL for Unauthenticated/Auth with no rating page](https://www.va.gov/health-care/apply/application/va-benefits/confirm-service-pay)
    
- **When is the launch date?**
    - 9/30/2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - We are looking to track one event `hca-short-form-flow`, which is triggered in two different places, depending on whether the Veteran is authenticated with a >50% disability rating or is unauthenticated/authenticated with no disability rating
         - [Event tag to the authenticated short form alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47706#issuecomment-1263602406) to track those who qualify based on their disability rating
         - [Event tag to the service-connected confirmation alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47706#issuecomment-1263606594) to track those who are unauthenticated or don't have a disability rating associated with their VA profile

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Test user # 228

- **Any additional comments**

    - This is an existing form on VA.gov, with existing URLs and alerts.  We are adding an event tag to track applicants who start the shortened version of the healthcare application.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by hdjustice** [comment]
cc:  @markfallows

**Comment by michelle-dooley** [comment]
@hdjustice - I saw in the #47706 that these events are being tracked.  Do you need anything more on this ticket or are we good to close?  cc:  @markfallows

**Comment by hdjustice** [comment]
Hi @michelle-dooley - Yes, we can close this ticket.  Thank you!
