### ISSUE TITLE
update prod idme oauth SiS cert

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#47792]
IDme is rotating the production cert VA.gov uses for the sign in service on the night of the 8th.

- Cert rotation has already been completed for staging and below
- The value of the cert must be extracted from the idme JWKS file and then stored in the appropriate AWS PS value
- We must then kickoff a deploy of production after the change is in to force the instances to pick up the new PS value
- Then we will test all CSP SiS login methods by kicking off the automated tests in datadog
  - DSLogon is not setup to automatically test production and this test will be done manually by an individual who has a valid DSLogon production account (Joe)

**Comment by joeniquette** [comment]
Updated the devops config to use the PS value instead of the locally stored version: https://github.com/department-of-veterans-affairs/devops/pull/12039

**Comment by andreahewitt-odd** [comment]
Waiting for production code change to get to the old one. Should go out with prod deploy today.

**Comment by joeniquette** [comment]
Confirmed as complete with todays prod deploy.
