### ISSUE TITLE
[Documentation] Vets.gov Analytics Issues Transfer

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#478]
## User Story
As a Platform team member, I need to know the current analytics issues that Insights is working on and has on their backlog so I can prioritize work.

## Goal
Transfer Analytics backlog issues from vets.gov-team repo to va.gov-team repo.

## Acceptance Criteria
- [x] Vets.gov-team repo issues have been transferred with proper PII accommodation
- [x] Completion has been shared with the team

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** 
- [x] **Labeled with Type**

**Comment by nedierecel** [comment]
@joanneesteban I am copying the `analytics` issues from the Vets.gov-team repo that I authored and will place/prioritize for the VSP board. There are other issues that I didn't create that live on VFT that I will comb through as well.

https://docs.google.com/spreadsheets/d/10RsqRkAoUgNDjM3PENgA7Bh-w1vrh35xWfG9x0UMFCI/edit#gid=0

@jonwehausen I'll continue bringing these issues over into the VSP Backlog for Sprint Planning.

**Comment by nedierecel** [comment]
@joanneesteban For your awareness, I moved the issues that I authored/prioritized from the `vets.gov-team` repo to VSP. Other issues that I did not move are still listed on the GSheet.
