### ISSUE TITLE
No validation feedback on calendar pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#4780]
When you don't select a date on the calendar pages and then click the continue button, you don't get any feedback about why you don't go forward.

The way we usually present validation errors probably doesn't work that well here, so we need some design input to fix this.

**Comment by jbalboni** [comment]
FYI @markgreenburg @rtwell

**Comment by rtwell** [comment]
oy vey—this has not crossed my mind. hmmm i will think on this and get something here asap

**Comment by rtwell** [comment]
thoughts on this approach?

![image](https://user-images.githubusercontent.com/12564977/72461358-d703d580-379c-11ea-8460-7a702d618a4b.png)

**Comment by jbalboni** [comment]
@rtwell That seems ok to me, but @narin would be more familiar with that page.

**Comment by narin** [comment]
@rtwell That should work.  Thanks!
