### ISSUE TITLE
[Design] Create Final Wireframes for Check-in Info when Using Pre-Check-in Link on Day of Appointment Outside of Check-in Window

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47816]
## User Story
As a Veteran, when I click on my Pre-Check-in link on the **day of my appointment**, but **outside the check-in window**, because I think that this is how I need to check-in, I would like to see a message that tells me what I need to do to check-in and when.

There are 2 scenarios:
 - Day-of appointment but BEFORE the check-in window
     - Need new error message for Pre-Check-in that says what to do to Check-in & what the window is (1) refresh? (2) text "check-in"? (3) show link to resource page?
 - Day-of appointment but AFTER the check-in window
    - Need new error message for Pre-Check-in to see MSA to check-in for in-person & if you're at the clinic

[Mural 
](https://app.mural.co/t/vfscie8528/m/vfscie8528/1663005558867/b1bc99cc3e652cc456a2e25d6a4b71891f322e43?sender=u83bc52d7fa73658f84f27755)
## Tasks
- [ ] Create final wireframes

**Comment by benbrasso-agile6** [comment]
For scenario #2, the existing page has a h1 that reads, "Sorry, pre-check-in is no longer available" 

![Screen Shot 2022-11-07 at 10.13.23 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/cfab7bd1-d316-4c19-8cb8-aa05ab8d8a72)

I think we could modify it with: 

<blue box>We're sorry. Online check-in is no longer available for your appointment time. Ask a staff member for help.</blue box>

This is the same message that CHIP sends when someone attempts to use check in after 15 mins.

**Comment by loripusey** [comment]
I think for the scenario where a Vet is using Pre-Check-in on the day of their appointment to check-in, this information isn't that clear to them because they think they are checking-in

**Comment by benbrasso-agile6** [comment]
@loripusey we tackled this a bit at stand up, but still not sure what, if anything, needs to be improved or changed (for scenario #1 above)

**Comment by loripusey** [comment]
If we don't know then I guess close the ticket

**Comment by benbrasso-agile6** [comment]
We'll skip scenario 1 and work on scenario 2

**Comment by ytsaoca** [comment]
scenario 2: https://share.goabstract.com/5db20262-46ec-4f94-9ca1-58bffbdc1789

**Comment by ytsaoca** [comment]
scenario 2: https://share.goabstract.com/5db20262-46ec-4f94-9ca1-58bffbdc1789

**Comment by ytsaoca** [comment]
@benbrasso-agile6 @kellysmith1008 @zach-park 
Ready for validation

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
LGTM
