### ISSUE TITLE
Grab Analytics for Header/Footer Clicks from Pre-Check-in or eCheck-in Pages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47859]
## Tasks
- Grab Analytics for Header/Footer Clicks from Pre-Check-in or eCheck-in Pages

**Comment by benbrasso-agile6** [comment]
Need to run out to VA. Got most of day of done 

https://docs.google.com/spreadsheets/d/1U0gxklu9ZwUTcUi_Qburpo0T5_opdn9pB8AXnLdZGxU/edit?usp=sharing

Need to clean up and add pre check in

**Comment by benbrasso-agile6** [comment]
@loripusey fyi, the footer accordions aren't firing events within our application. Logged with the platform team for now - https://dsva.slack.com/archives/CBU0KDSB1/p1665165272126369

**Comment by benbrasso-agile6** [comment]
This is complete - https://docs.google.com/spreadsheets/d/1U0gxklu9ZwUTcUi_Qburpo0T5_opdn9pB8AXnLdZGxU/edit?usp=sharing


<img width="666" alt="Screen Shot 2022-10-07 at 4 41 29 PM" src="https://user-images.githubusercontent.com/101129355/194649325-ac395856-b36a-4a60-b380-a8a7efee2e81.png">
<img width="678" alt="Screen Shot 2022-10-07 at 4 41 11 PM" src="https://user-images.githubusercontent.com/101129355/194649327-a949b213-5096-4a10-a3e3-458af9134388.png">
