### ISSUE TITLE
Adding Abbie Burton to DSVA Slack

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#47858]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting to add abbie.burton@thoughtworks.com as a full member to DSVA Slack. She will be working as a Product Manager on the Digital Health Platform (DHP) team.

Please add to the channels
#digital-health-platform-public
#digital-health-platform-team

**Comment by eunicegar** [comment]
account exists and has not accepted so account shows as inactive. Abbie has been invited as a full member. Closing ticket.
