### ISSUE TITLE
[Design] Create Wireframe for Reduced Header & Footer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47852]
## Tasks
- [ ] Create wireframe

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities

**Comment by ytsaoca** [comment]
Mural  board for information collection and ideation 
https://app.mural.co/t/vfscie8528/m/vfscie8528/1665431891681/e232da055539a2681bca924c23b5d36fa557b811?sender=u70b8b2930b03d3ef317d2520

**Comment by ytsaoca** [comment]
Mural  board for information collection and ideation 
https://app.mural.co/t/vfscie8528/m/vfscie8528/1665431891681/e232da055539a2681bca924c23b5d36fa557b811?sender=u70b8b2930b03d3ef317d2520

**Comment by loripusey** [comment]
@ytsaoca @benbrasso-agile6 do we have wireframes yet?

**Comment by benbrasso-agile6** [comment]
1. Adjust the wires to have two versions. One with the footer that is just the logos. The other one with the logos plus the bottom links. Make sure to add all of the links. 
2. I would also add the Feedback button and the Crisis hot line in the footer to both versions. 
3. We should share those two versions with the CIE team. 

--
Create new ticket(s) with this information: 

4. Meet and share those two versions to the DS team (Matt Dingee) and have them make a decision on the footer. 
5. When Matt decides, create branch in Abstract and update all the header and footers in pre check in and check in. 
6. Start a new ticket with some tasks we want to complete for re-envisioning the "Need Help?" section. Then, we can point that ticket.

**Comment by loripusey** [comment]
Create new [ticket ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/48394)for the items (4-6) listed above.  Will 1-3 happen as part of this ticket?

**Comment by benbrasso-agile6** [comment]
Ya-ching is working to complete them now. We'll have to figure out when to share with the CIE team. Probably a quick share, so maybe sometime tomorrow during planning day. @ytsaoca thoughts?

**Comment by ytsaoca** [comment]
Couldn't find all of the footer links and the Feedback button element so I didn't include them in the 2 version. Will discuss with @zach-park about where to get them.
https://share.goabstract.com/96c4d4d5-1089-4ff6-af1b-25051ec084d2

**Comment by ytsaoca** [comment]
Couldn't find all of the footer links and the Feedback button element so I didn't include them in the 2 version. Will discuss with @zach-park about where to get them.
https://share.goabstract.com/96c4d4d5-1089-4ff6-af1b-25051ec084d2

**Comment by loripusey** [comment]
there is a new ticket in this next sprint to collaborate with DS on this; I'm thinking UX can set that up
@benbrasso-agile6 @ytsaoca

**Comment by benbrasso-agile6** [comment]
Yeah, I would just wait to give the new header/footer to CIE team until Matt Dingee makes a decision or provides some type of feedback to us
