### ISSUE TITLE
SOCKS access for Matthew Christianson

### ISSUE THREAD

**Issue by mchristiansonVA** [department-of-veterans-affairs/va.gov-team#47862]
### Your Name

Matthew Christianson

### Your Email

matthew.christianson@adhocteam.us

### Your Role and Team

Backend Engineer on VA Lighthouse

### Product Manager (PM) name and email

Kayla Watanabe, kayla.watanabe@va.gov

### Product Owner (PO) name and email

Janet Coutinho, Janet.Coutinho@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrSMXYLkeYQIRlnYhAPfdbYPs9FZtuDculdUesfXOOS/HEXpBfbuqq8+z6cIVPxwnKhNeRs0ecyhJXgjWQ3EI7Kio9MCd/AFHSeUWQRW69Esft3mUCObndU0QrmdQc8fogH0TC5Cbn5itwXAiHLkxMJ4mkR46c7k+kdkf+Ywp/XBNbcPBoYw1OR9UzR9cUvk7xIgbEIfsUevi2hCQ0Lbhiwv8MbsAjo8oKf3RRLfYVvKftdpmykdXdvriZV1Ew3rdcjkXzi7tTicrjzoHEfhtrvD7rpkqaGIh1stdX1HOq34P5u/CXxkhJjF/8Z5SEDSOxozBm8jPMyn8kJrdOfwW+O8UxR18126G6lhlLI1QdIxwA/FI8O3Swf/di+rSpheWAtphSmuNKCnM6Bdcb2sj7CGA1IYVwp7o88hLDHymjROgnki+6ONVRSHK2RNTy/m0RCI4r/AzBOFOerc3G3U2mCj+KKid1Lc3MNoNNlsUgS1aoEliDNIFlUL7nhIB+Guk= matthewchristianson@MatthewansonMBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@mchristiansonVA Can you double check that that's your public SSH key? Our automation is flagging it as invalid. Your public ssh key can be found using this command:
```
cat ~/.ssh/id_rsa_vagov.pub
```

**Comment by mchristiansonVA** [comment]
@rmtolmach Apologies, I copied the key fingerprint instead of the public key. Corrected in my original comment above.

**Comment by rmtolmach** [comment]
@mchristiansonVA Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
