### ISSUE TITLE
Rotate IAM metadata files for int, dev, sqa

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#47861]
Review steps [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/How-To/Security/SSOe_certs.md) for instructions. This process is completed once a year as the certs in the metadata files for our SAML authentication expire yearly.

- Work is being completed on 10/5/22, emailed by the IAM team in advance of the required change.
- The subsequent prod change is scheduled for the 27th of October.

**Comment by joeniquette** [comment]
PR for change https://github.com/department-of-veterans-affairs/devops/pull/12051

**Comment by ianhundere** [comment]
`vsp-infra-application-manifests` PR for change: [department-of-veterans-affairs/vsp-infra-application-manifests#924](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/924)

**Comment by joeniquette** [comment]
The intent of this task is completed and validated as working as of 1530 ET
