### ISSUE TITLE
Message SME about outstanding tickets

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47863]
Tasks:

- [x] Send message to Joe in his team's Slack channel about these two tickets:

https://github.com/orgs/department-of-veterans-affairs/projects/724/views/1
https://github.com/orgs/department-of-veterans-affairs/projects/724/views/1

Drafted message:

Hi, _! The Platform Content team would like to help you close ticket #__. The ticket author recommends adding a sentence and/or link to an existing page. It looks like an easy fix since they provided a suggested link. Let us know if you'd like to work with us to close this ticket!

**Comment by taylojill** [comment]
10/17/22 - Messages sent to Joe Tice and Peter Hill via platform-team Slack channel.
