### ISSUE TITLE
Dig into MHV survey results

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#47878]
MHV provides survey results every 10 days that have feedback from users broken out with a category around login. If we pay attention to these results and create themes or artifacts around it, we can figure out how to solve for the most vulnerable users. 

John recieves the emails of the results and will forward to Amanda and Andrea. 

AC:
Figure out how we can use this information
Figure out areas where we need more information
Figure out processes for scanning through this and updating information

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
