### ISSUE TITLE
[Bug] Modify displayed data so that screen readers DO NOT read non-acronyms one letter at a time

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47874]
## Background
Screen readers may read the all caps within some of our appointment cards one letter at a time and not as a word. So, the location would be read as “S E C O N D F L O O R R O O M 2” for example, not “Second floor room 2.” To fix this, engineering would have to make adjustments to what is coming out of the database. The design work is complete; the wireframes show everything as lowercase.

## Tasks
- Modify displayed data so that screen readers DO NOT read non-acronyms one letter at a time

## Potential Ideas
https://freshysites.com/wordpress/ada-compliance/capital-letters-accessibility/

**Comment by benbrasso-agile6** [comment]
Wonder how we'll consistently address this. I think some of the clinic and location names are quite obscure. Would be curious how VAOS is handling this too. At least, to be consistent across the apps.

**Comment by loripusey** [comment]
I think we'll have to make some assumptions, like if it's a clinic name that is capitalized that it should stay capitalized because we have nothing to tell us otherwise, might need engineers to look at the data
