### ISSUE TITLE
Adding [Tricia Baker] to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#47896]
new user requests: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Are you requesting to add an individual as a:

Full member
Tricia is our new Product Manager on the VA.gov Product Teams- Form CEDAR Task Order. She will need full access to DSVA slack to communicate across teams & with VA PO- Matthew Dingee.

tricia.baker@oddball.io

We aim to complete slack requests within 24hrs.

**Comment by eunicegar** [comment]
invite sent
