### ISSUE TITLE
IA/Content edits to "Other" expenses

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#47898]
## Issue Description
Joni's suggestions for "Other" expenses ([Link](https://miro.com/app/board/uXjVPVTltko=/))

---
## Tasks
- [x] _Make updates to [UXPin](https://preview.uxpin.com/817f1694effafce3e133be363684526331f350fe#/pages/158986738)_

## Acceptance Criteria
- [x] _UXPin link or screenshot sent to Jill_

**Comment by briepipitone** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/47898?planning-poker) with Zenhub @briepipitone
