### ISSUE TITLE
Fix broken link on travel pay reimbursement page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47908]
## Issue Description
SiteImprove reported a broken link on our [VA travel pay reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) page. 

The action link "Go to the AccessVA travel claim portal to file a claim" needs to be updated with a new link. 

After slacking with Danielle we determined the best place to send users is here: https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20%26ForceAuthn%3Dfalse&foiaUrl=https%3A%2F%2Fwww.va.gov%2Ffoia%2F&nonce=wAgV5olUxtVXF0HKzldSWFbceFooqprj

Slack thread for background: https://dsva.slack.com/archives/C01K37HRUAH/p1665077950394379

We need to update the page with this change.

## Tasks
- [x] Update action link
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live page now has working action link

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! I went ahead and updated the action link and left the link language as is, but noted a few things to Randi.

**Notes:**

Currently, we use the word **"portal"** on this page. The [BTTS link](https://dvagov-btsss.dynamics365portals.us/) (from the the [chat](https://dsva.slack.com/archives/C01K37HRUAH/p1665077950394379) with Danielle) leads to a page that uses the word "portal." The new link that we are using leads directly to AccessVA but **does not** include the word "portal." 

To remain consistent in how we label the page on the VA site, I wondered if one of two options can work, to remove the word "portal:" 

1. We remove the "travel claim portal" language and just include "**...through AccessVA**" or "**...to AccessVA to file a claim**" 

OR 

2. We use the same name from the AccessVA page. For in text language, "**AccessVA Veteran Travel Claim Entry**" and for the link language, "**Go to the AccessVA Veteran Travel Claim Entry to file a claim.**" I used upper case here as "Veteran Travel Claim Entry" seems to be an official name for this entry point for filing travel claims.


Randi and I chatted about using "portal" after the word "entry" but felt it was a bit repetitive. I also think that perhaps "Claim" from the official name and in the link language ("file a claim") feels a bit repetitive as well. 

Just wanted to move this along ahead of being OOO. Thank you!

**Comment by laurwill** [comment]
Thanks Aliyah! I think the AccessVA page is what most people would think of as a "portal", and I want to get the link fixed without futzing around too much in the page content. But I did shorten the link itself to drop "travel claim portal" since I think you're right it's not needed.

@megzehn this is ready to publish!

**Comment by laurwill** [comment]
We chatted about this in standup and I published the link fix.

**Comment by laurwill** [comment]
@RLHecht the link is working now — do we need to notify anyone before we close out?

**Comment by RLHecht** [comment]
Thanks! This is now live so closing. I'll check with Danielle if we need to alert anyone. We were notified through SiteImprove and not a stakeholder, so I'm not sure.
