### ISSUE TITLE
Add Redis monitoring in Datadog

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#47910]
[DD Amazon ElastiCache](https://docs.datadoghq.com/integrations/amazon_elasticache/)

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by theodur** [comment]
After doing some digging, I came across the [AWS Elasticache (Redis)](https://vagov.ddog-gov.com/screen/integration/149/aws-elasticache-redis) dashboard that contains Redis metrics. This dashboard seems to already be monitoring the performance of our Redis clusters.

 There are 4 key metric categories worth monitoring, and the dashboard covers them all:
- [Client metrics](https://www.datadoghq.com/blog/monitoring-elasticache-performance-metrics-with-redis-or-memcached/#client-metrics)
- [Cache performance](https://www.datadoghq.com/blog/monitoring-elasticache-performance-metrics-with-redis-or-memcached/#cache-performance)
- [Memory metrics](https://www.datadoghq.com/blog/monitoring-elasticache-performance-metrics-with-redis-or-memcached/#memory-metrics)
- [Other host-level metrics](https://www.datadoghq.com/blog/monitoring-elasticache-performance-metrics-with-redis-or-memcached/#other-host-level-metrics)

One thing to note is it looks like the dashboard is a template, so if we want a more tailored view of a specific cluster or metric, we can always clone the dashboard.

**Comment by theodur** [comment]
For setting up ElastiCache monitoring, there are two methods:
- [Installation without Datadog Agent](https://docs.datadoghq.com/integrations/amazon_elasticache/#installation-without-datadog-agent)
- [Installation with Datadog Agent (recommended)](https://docs.datadoghq.com/integrations/amazon_elasticache/#installation-with-datadog-agent-recommended)

After looking through the [Ansible DataDog role (private repo)](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/datadog) directory, I didn't notice the agent config in the directory, which most likely means the ElastiCache monitoring was set up with the first installation method through the ElastiCache integration. Even though installing with the agent is the recommended way, it's probably not necessary as long as we have the metrics we need with the integration (which it seems like we do).

**Comment by theodur** [comment]
I reached out to the DataDog team to see what additional metrics are available with the agent, and they linked to the metrics listed [here](https://docs.datadoghq.com/integrations/redisdb/?tab=host). There are some additional metrics like `expired and evicted keys`, and `secondary connections` that are only available with the agent, but it seems like the important metrics such as memory usage and cache performance are still available with the integration. It seems like we should be good to continue using the integration for now. If we ever need additional metrics, listed in the link above, we can always set up monitoring with the agent.

**Comment by theodur** [comment]
Since Redis monitoring is configured in DataDog, this ticket is complete. A new [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48372) for creating dashboards for specific clusters has been created.
