### ISSUE TITLE
Add content from Post-9/11 rates page to R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47926]
## Issue Description
We need to add some information we have on our modernized Post-9/11 GI Bill (Chapter 33) rates page to the R&S article [How we determine your percentage of Post-9/11 GI Bill benefits](https://www.va.gov/resources/how-we-determine-your-percentage-of-post-911-gi-bill-benefits/). 

The content to revise in the R&S article is under the H3s Eligibility for 100% of Post 9/11 GI Bill benefits and Eligibility for a percentage of benefits based on how long you served on active duty. We need to update the R&S content to match the content in the Post-9/11 GI Bill (Chapter 33) rates page.

Post-9/11 rates preview page: http://preview-prod.vfs.va.gov/preview?nodeId=1009

## Tasks
- [x] Revise R&S article (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] R&S article is revised with content from current rates page

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO and @RLHecht. I updated the R&S page "How we determine your percentage of Post-9/11 GI Bill benefits" to match the content in the Post-9/11 GI Bill (Chapter 33) rates page.

http://preview-prod.vfs.va.gov/preview?nodeId=35364

Should I also now go into the Post-9/11 GI Bill rates page, remove the content and link to the R&S article instead?

**Comment by katherine-fung** [comment]
Update to add that Beth answered the question in the previous comment. For now, we are leaving the content on the Post-9/11 GI Bill rates page.

**Comment by katherine-fung** [comment]
Update to add that Beth answered the question in the previous comment. For now, we are leaving the content on the Post-9/11 GI Bill rates page.

**Comment by RLHecht** [comment]
@megzehn I think this one got lost on our board. This is ready to move along and publish. Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming this has been published.

**Comment by RLHecht** [comment]
This is live. Closing ticket!
