### ISSUE TITLE
Qualitative Data-Request

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47923]
### Data Type Requested

User Surveys

### Date Range Start

07-19-2022

### Date Range End

10-06-2022

### Product Name(s)

Combined Debt Portal

### Product Description

Combined Debt Portal on va.gov is there to help Veterans understand why they have debt, what the status of their debt is, and what steps they need to take to resolve their debt.  The portal includes both benefit overpayments as well as medical copays. Veterans are also able to complete and submit an online Financial Status Report (VA Form 5655) to request that their debt be waived.                                                  

### Product URL(s)

I am not sure the best URL to use.. I'd love to see feedback on the entire portal so I am going to assume. https://va.gov/manage-va-debt/ will highlight the pages we have.  

**_A few other links that may be helpful:_**
https://va.gov/manage-va-debt/summary is a summary of both types of debt 
https://va.gov/manage-va-debt/request-debt-help-form-5655/introduction is the beginning of the FSR Form 
https://va.gov/manage-va-debt/summary/copay-balances  is the summary of medical copays
https://va.gov/manage-va-debt/summary/debt-balances is the summary of benefit overpayments

### VA Email Address(es)

denise.coveyduc@va.gov

**Comment by jwoodman5** [comment]
@denisecoveyduc Sorry about the delay. This one slipped by. We will get you your data in the next few days!

**Comment by jwoodman5** [comment]
@ianMcCullough-ob Denise confirmed https://va.gov/manage-va-debt/ is the URL she would like the data for. Thanks.

**Comment by ianMcCullough-ob** [comment]
@denisecoveyduc files have been shared, you're good to go. Thanks!
