### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#47925]
# Instructions
A change to the SessionTimeoutModal component in vets-website to a web component had an unintended consequence of affecting VA.gov team-sites: (example: https://www.va.gov/opa) as described in this Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1665146147067899.  This has resulted in users possibly seeing a rather unsightly header for these team-sites on VA.gov (see screenshot below)

<img width="1448" alt="Screen Shot 2022-10-07 at 9 00 54 AM" src="https://user-images.githubusercontent.com/67602137/194572591-98c3b260-c564-49c4-ad70-8fc6f49f2d69.png">

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy

Original PR (caused issue):
https://github.com/department-of-veterans-affairs/vets-website/pull/22256

New PR (fixes issue):
https://github.com/department-of-veterans-affairs/vets-website/pull/22368

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
>  Since the merge we estimate around 2000 users might have been affected

## Has fix been confirmed in Staging?
- [x] Yes
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
   > The Sitewide CMS team requested an OOB Deploy due to impact on their work as well as it impacting Veterans using these team-sites to get information about their VA.gov benefits and services.
   
## Verify The following
 - [x] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [x] The OOB Deploy Requests is critical and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropriate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests
 - [x] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by raywangoctova** [comment]
OCTO approved
