### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#47945]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: rjohnson2011
- Reason access is required: I'm attempting to complete [the following ticket](https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/department-of-veterans-affairs/va.gov-team/45360) which requires access to api.va.gov/sidekiq/busy . Currently I'm getting the message "You don't have access to team 4917328".

**Comment by ericboehs** [comment]
Added
