### ISSUE TITLE
Discovery: What are the security considerations with moving vets-api to EKS?

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#47941]
**PROBLEM STATEMENT**
We need an understanding of the security concerns with moving vets-api to EKS, so security concerns can be addressed. 

**DEFINITION OF DONE**
- [x] Documentation of discovery is linked [HERE](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2403532805/Discovery+Vets-API+from+BRD+to+EKS+47627)
- [x] Send to SA for review

**Comment by laineymajor** [comment]
Group concerns into 
- completed
- now/immediate concerns
- upcoming
- ongoing

**Comment by RachalCassity** [comment]
[https://app.zenhub.com/files/133843125/dd72da54-79ea-46d3-80c2-117b70ea18c2/download](https://app.zenhub.com/files/133843125/dd72da54-79ea-46d3-80c2-117b70ea18c2/download)

**Comment by RachalCassity** [comment]
[https://app.zenhub.com/files/133843125/dd72da54-79ea-46d3-80c2-117b70ea18c2/download](https://app.zenhub.com/files/133843125/dd72da54-79ea-46d3-80c2-117b70ea18c2/download)

**Comment by laineymajor** [comment]
Discovery work has been completed. Considerations have been sent to SA/PO.
