### ISSUE TITLE
Gather relevant industry blueprint/map samples

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47947]
## Issue Description
Gather relevant blueprint/map examples to "borrow" from.

## Tasks
- [x] Collect blueprint samples for reference

[Confluence page - Table Comparison](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2400387073/Maps+views+Findings)

[Mural - Comparative Analysis](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1665162435560/e9f7047b3e74b2d90d12331694c6753670e429f8?sender=u4f7db1750f2355f805e60296)

## Acceptance Criteria
- [x] samples are collected for easy viewing and review

**Comment by tayism** [comment]
[We started documenting examples here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1665517968025/7f0b6ae502331974299f47ba1ca6a24c63dc5c12?sender=u9ea6bd3ca12795949b606150)
