### ISSUE TITLE
Modify Logingov logout call for SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#47955]
- Logingov changed their logout requirements to only use "client id' instead of "id token hint
- We need to change the backend built logout call for logingov on SiS to send the client id and remove the id token hint
- This change went into staging on Oct 6th, with no prior notice from logingov, and goes live to prod on Oct 20th.

AC: 
Get rid of id token hint

**Comment by bramleyjl** [comment]
Confirmed `client_id` is present and `id_token` is not in SiS/Login.gov logout calls in all environments

![image.png](https://images.zenhubusercontent.com/5f99b8d1032b9709f1c7e051/9929d86e-e1c1-421b-9aab-7f86f1edc34f)
