### ISSUE TITLE
[Support] Investigate where we should send people with direct deposit for comp & pen issues

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#47950]
### Background

Issues like the following frequently come in to the Medallia Feedback survey and the call centers:

> While trying to update direct deposit, online it states that the Veteran does not receive disability compensation but she does. Veteran checked with the Benefits Administration and they have the correct information, only online is incorrect. Email on account is accurate and active.

Currently, the VA.gov interface sends people to the NCC if they have direct deposit issues. However, Chante says that they refer people directly to EVSS when they have issues with direct deposit for comp & pen. Given that the call centers can not resolve direct deposit issues, Chante is going to determine if there is another place we can refer people to from the interface.

### Tasks

- [ ] Chante to confirm where we should send people with direct deposit for comp & pen issues
- [ ] Regroup with Samara on findings

**Comment by Samara-Strauss** [comment]
cc/ @SKasimow for awareness

**Comment by clantosswett** [comment]
@anitadewitt-va Let's make sure to add to the upcoming sprint to confirm what this error message should say to ensure veterans are getting help from the right group first. Thanks!

![image](https://user-images.githubusercontent.com/32465263/200328302-9b1297e0-b26d-464c-bbfb-96c920a5b496.png)

**Comment by clantosswett** [comment]
I am going to reach out to Regina Yount to see if they have any metrics on the support they are able to give before having this changed to sending people to VA411.

**Comment by ATMiddleton** [comment]
@clantosswett will connect with Auth Experience. Further information to follow.

**Comment by ATMiddleton** [comment]
Updated the procedure and can close ticket
