### ISSUE TITLE
10-10CG Instructions Translated to Additional Languages

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#47952]
The 10-10CG Stakeholders have asked that the instructions for the caregiver application be translated into additional languages.  Those languages are:
1. Spanish
2. Tagalog

This ticket is to track whatever work is necessary on our side or to document progress if another team must do the work.

**Comment by markfallows** [comment]
After discussing with Patrick Bateman, it was indicated that we would need to translate the entire application and not just the instruction pages.

Meeting with Danielle from the Content team will be set for after 10/14 so we can speak with the CG stakeholders to ensure everyone is on the same/right page.

**Comment by hdjustice** [comment]
Closed as duplicate, we have an epic for this now.
