### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#47968]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: sethdarragile6
- Reason access is required: development on the VA Automated Benefits team

**Comment by ericboehs** [comment]
Done
