### ISSUE TITLE
SOCKS access for Seth Darr

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#47962]
### Your Name

Seth Darr

### Your Email

seth.darr@agile6.com

### Your Role and Team

Backend Engineer on VA Automated Benefits Delivery

### Product Manager (PM) name and email

Elizabeth Neal,  elizabeth.neal@agile6.com

### Product Owner (PO) name and email

Rakshinda Aslam, rakshinda.aslam@agile6.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNvgXrK4elRfYE1kzX59fb98OKnNbcMlJxSBAlXJkQT5oRIBBx0RSe3C6kgucdZiDZYE0CroC2BH54/zlFoBYrrWjRpIbhfblo4xIN0t4YD/uGLwpgdzOMHvTw8I+Cw9CWJmmustKDVsZBZYzuW688f+liefQbgd+yl4JXqXWOlMpb0bhH3md+ZNUkef6k2ci/d16vbQrz7UIpH0ud0PI7nImEAhEfJ2GmuWioXb9FHLgedTIDP+mS5XE3pJwQEdqtegVYtfHQeBdX3anruy0rbx+C14m7R0Oo8jJrPOAVaCsUKsNizKTQpkQVlNSLLTNS9nDNSNxTp0MFpj5kdPUNnHO0B5nq0jNxdrbDWx3n22C8l2Wz1uOqFat9u+OjGnlKAXh/ZQ51Fen/uLe6pcxaubClXUkmIwmbupI/W2AahDueyPzIw0GFE2p6kLgcq03v+R11kenXzCyhc0X1rms5QIKo6/EVhCN4vUi9U/tboO7AL++I1fWODNrfa0wH7ZM= seth@Agile6-A78

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@sethdarragile6  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.

**Comment by ryan-mcneil** [comment]
Adding for reference

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41602677/b078ebbc-773e-471d-a5f0-324ede2bbf47)
