### ISSUE TITLE
SOCKS access for Curt Bonade

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#47960]
### Your Name

Curt Bonade

### Your Email

curt.bonade@oddball.io

### Your Role and Team

Frontend Engineer on Tech Team 4

### Product Manager (PM) name and email

Joe Tice | joe.tice@oddball.io

### Product Owner (PO) name and email

Mike Chelen | unsure

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHWgmcixx2wAOO28L9V67Tm5U5S8XHbQ3XyJV26FdOKHAlftfkjhOI9jk/D7LUQbb/EefciPGqt3dLaUtdR95dWsFLuBfSVlqiZlZwgC4KR77AD3hWjKrMs19B0DYj0q7r8va79ilZu1ktL+JSLgNMZOk5hXWfkuIjQT4HPL46TTA/GqQZ6kytFeOgab8dxOOi6Uy6M7ph+Od5Xubi46pvyotK2FIdrzrXkW1UDbKRBuNV9sDIh/ydD+mzqSaixRdU0vBe0RVscHEd+RSYNvMWSSaP5b/0jBiUzEzvlRM5GDmPUg+tX2euBgkjpR7SUhXMMpyx9t/Q+roV9qLXMGk3tx94Q56/KDTqk1e90T+WuEvuLy6Vm9Pg/QilwD1wLKwgjuPln5tbW/R0nuwkfERsvRYWyGHYvv5rGC3cmnUOMy5IUCZiYLyQgAOFLdYcKrz3d1/RUzr3iXAAVeWBkeY8smU+PG63i1Demy95iKQphxKO9eV8GrlDvEBD8/uWxR0= cbonade@Curts-MBP.attlocal.net

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by oseasmoran73** [comment]
Done my man! Let me know if you run into any issues
