### ISSUE TITLE
AWS access for Helene McCarron

### ISSUE THREAD

**Issue by helene-mccarron** [department-of-veterans-affairs/va.gov-team#47970]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Helene McCarron

### Your Email

helene.mccarron@thoughtworks.com

### Team, Role, and Company of the target individual

Team: Virtual Agent ChatBot, Role: software developer, Company: Thoughtworks

### Product Manager (PM) name and email

Ian Santarinala

### Product Owner (PO) name and email

ian.santarinala@thoughtworks.com

### Desired AWS Access

I need access to AWS Parameter Store to view secrets from /dsva-vagov/vets-api/

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by helene-mccarron** [comment]
I will also need access to the following path: /dsva-vagov/va-virtual-agent/

**Comment by ianhundere** [comment]
not seeing the individual on either roster

**Comment by japui-coder** [comment]
AWS access for [individual] #47970

**Comment by ianhundere** [comment]
it looks as if this individual already has access to parameter store:
- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf#L638
