### ISSUE TITLE
[Datadog] Eval/Setup Monitoring for AWS:ElastiCache

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47977]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for ElastiCache

# Acceptance Criteria
- [ ] ElastiCache is evaluated for monitoring needs
- [ ] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- Use the USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.
- Use the RED method for services
  - **R**ate: The number of requests the service is handling per second
  - **E**rror: The number of failed requests per second
  - **D**uration: The amount of time each request takes (latency)

**Comment by rsmithadhoc** [comment]
- Utilization
  - [Platform - AWS ElastiCache CPU Utilization](https://vagov.ddog-gov.com/monitors/100568)
  - [Platform - AWS ElastiCache Change in Available System Memory by Node (%)](https://vagov.ddog-gov.com/monitors/101155)
- Saturation
  - [Platform - AWS ElastiCache (Memcached) Hit Rate (%)](https://vagov.ddog-gov.com/monitors/101152), [Platform - AWS ElastiCache (Redis) Hit Rate (%)](https://vagov.ddog-gov.com/monitors/101153) - Cache efficiency. If hit rate is low, the cache’s size might be too small and the cache has to evict data too often.
  - [Platform - AWS ElastiCache Evictions by Cluster](https://vagov.ddog-gov.com/monitors/101154) - Evicting a lot of keys can decrease the hit rate, leading to longer latency times.
