### ISSUE TITLE
Thumbnail mapping- incorporate feedback to 2nd iteration

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4798]
## User Story:
As a Designer, I need to incorporate the feedback from the DLC/BAM2 from the second iteration of our thumbnail map so that I can determine if the 2nd flow meets the DLC objectives.

## Tasks
- [ ] Incorporate changes to 2nd iteration. 
- [ ] Determine if additional iteration are necessary

## Acceptance Criteria:
Given: That the DLC objective is to create a User's process flow
When: The team has a understanding of what steps are need/required to complete a order
Then: The team can finalizes on 1 flow and start wire-framing based of the agreed thumbnail map.

## Next Steps
-wireframe

## Blockers
- Feed back from DLC regarding the 1st iteration.
- Ticket 4797

**Comment by rebeccawalsh** [comment]
Exports of work can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/thumbnail-mapping/README.md#iteration-3---sprint-13
