### ISSUE TITLE
[Datadog] Eval/Setup Monitoring for Network:LoadBalancers

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47980]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for Load Balancers

# Acceptance Criteria
- [x] Load Balancers are evaluated for monitoring needs
- [x] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- Use the USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.
- Use the RED method for services
  - **R**ate: The number of requests the service is handling per second
  - **E**rror: The number of failed requests per second
  - **D**uration: The amount of time each request takes (latency)

**Comment by rsmithadhoc** [comment]
- [Platform - AWS Application Load Balancer HTTP 2xx Responses](https://vagov.ddog-gov.com/monitors/101714)
- [Platform - AWS Application Load Balancer HTTP 3xx Responses](https://vagov.ddog-gov.com/monitors/101716)
- [Platform - AWS Application Load Balancer HTTP 4xx Responses](https://vagov.ddog-gov.com/monitors/101715)
- [Platform - AWS Application Load Balancer HTTP 5xx Responses](https://vagov.ddog-gov.com/monitors/101717)
- [Platform - AWS Application Load Balancer Active Connections](https://vagov.ddog-gov.com/monitors/101718)
- [Platform - AWS Application Load Balancer New Connections](https://vagov.ddog-gov.com/monitors/101719)

**Comment by rsmithadhoc** [comment]
Added to [Platform Monitors & Alerts](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors--alerts):
- Application ELB
    - [Platform - AWS Application Load Balancer % of HTTP 4xx Responses](https://vagov.ddog-gov.com/monitors/101715)
    - [Platform - AWS Application Load Balancer High Requests Per Second](https://vagov.ddog-gov.com/monitors/101840)
    - [Platform - AWS Application Load Balancer High Response Time](https://vagov.ddog-gov.com/monitors/101844)
- AWS ELB
    - [Platform - AWS ELB High % of HTTP 4xx Responses](https://vagov.ddog-gov.com/monitors/101860)
    - [Platform - AWS ELB High % of HTTP 5xx Responses](https://vagov.ddog-gov.com/monitors/101717)
    - [Platform - AWS ELB High Latency](https://vagov.ddog-gov.com/monitors/101846)
    - [Platform - AWS ELB High Requests Per Second](https://vagov.ddog-gov.com/monitors/101861)
    - [Platform - AWS ELB Spillover Detected - Requests Are Being Dropped](https://vagov.ddog-gov.com/monitors/101863)
    - [Platform - AWS ELB Surge Queue Length Approaching Limit](https://vagov.ddog-gov.com/monitors/101862)
- Network ELB
    - [Platform - AWS Network ELB High Active Flow Count](https://vagov.ddog-gov.com/monitors/101865)
    - [Platform - AWS Network ELB High RST Packets Generated By Clients](https://vagov.ddog-gov.com/monitors/101869)
    - [Platform - AWS Network ELB High RST Packets Generated By Host](https://vagov.ddog-gov.com/monitors/101868)
    - [Platform - AWS Network ELB High RST Packets Generated By Load Balancer](https://vagov.ddog-gov.com/monitors/101867)

**Comment by jhouse-solvd** [comment]
Application ELB - AWS Application Load Balancer High Response time: 
- TODO: Evaluate what this metric means. If response times are latent, is that a problem or a symptom?

Platform - AWS ELB High Latency
- No description 

Platform - AWS ELB Spillover Detected - Requests Are Being Dropped
- We might want to make this "> 0"

Platform - AWS Network ELB High RST Packets Generated By Clients
- We might want to expand on the explanation given

**Comment by rsmithadhoc** [comment]
Made some updates:
**Application ELB - AWS Application Load Balancer High Response time:** 
- This one did seem like more of a symptom of other issues such as saturating its disk I/O or CPU, so I ended up removing it. I believe this is also covered by requests per second monitor to some degree https://vagov.ddog-gov.com/monitors/101840.

**Platform - AWS ELB High Latency**
- Description added

**Platform - AWS ELB Spillover Detected - Requests Are Being Dropped**
- Made this "> 0"

**Platform - AWS Network ELB High RST Packets Generated By Clients**
- Added RST packet description to all of the RST monitors.

**Platform - AWS ELB High % of HTTP 4xx Responses**
- Updated to a correct percentage.

**Comment by rsmithadhoc** [comment]
The alerting chain has been added, closing this one out.
