### ISSUE TITLE
[Datadog] Eval/Setup Monitoring for Network: Forward Proxy (USE)

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47983]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for the Forward Proxys

# Acceptance Criteria
- [ ] Forward Proxies are evaluated for monitoring needs
- [ ] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- https://grafana.vfs.va.gov/d/000000032/forward-proxy?orgId=1
- Confirm that backends/upstream are healthy
- Forward Proxies are EC2's that are running HAProxy
  - Each EC2 runs a single proxy
- Use the USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.

**Comment by ph-One** [comment]
The forward proxy's USE monitors are already handled by the ASG's and EC2's USE monitors. All that is really needed for this work are the RED monitors

**Comment by rsmithadhoc** [comment]
- [Platform - AWS Forward Proxy (HAProxy) High Number of Backend Requests](https://vagov.ddog-gov.com/monitors/102230)
- [Platform - AWS Forward Proxy (HAProxy) High Number of Connection Attempts](https://vagov.ddog-gov.com/monitors/102225)
- [Platform - AWS Forward Proxy (HAProxy) High Number of Frontend Requests](https://vagov.ddog-gov.com/monitors/102228)
- [Platform - AWS Forward Proxy (HAProxy) High Number of Sessions](https://vagov.ddog-gov.com/monitors/102165)
- [Platform - AWS Forward Proxy (HAProxy) Low Number of 2xx Responses (Backend + Frontend)](https://vagov.ddog-gov.com/monitors/102231)

**Comment by ph-One** [comment]
Closing. See the comment above about not needing USE, only RED (this is an application)
