### ISSUE TITLE
Destructive actions

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#48]

**Comment by jaredcunha-usds** [comment]
Do we have any destructive actions where files/content/etc is deleted? 

Maybe there's a standardized flow that we use? 
1) User clicks button
2) Confirmation dialog box appears
3) Item disappears
4) Alert shows indicating item successfully deleted

Questions:
- What color alerts do we use?
- What color buttons do we use? 
- What icons do we use?

Is there any way to recover deleted items?

**Comment by caw310** [comment]
Closing as this is over 2 yrs old.
