### ISSUE TITLE
Create beta '/yellow-ribbon/schools` page

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#4800]
# Description
This pertains to the [YR epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3703). We need to create a page where this work will live. The title proposes a URL for it, but this is just a placeholder URL.

## Tasks
- [ ] Create beta URL on dev.va.gov - Nick - 3 hours

## Acceptance Criteria
- [ ] Create beta `/yellow-ribbon/schools` page.

**Comment by ncksllvn** [comment]
I remove the `Submit request to Mikki for IA and URL - .5 hours` task from this work because I don't think I'm the right person to submit a request to IA. I'm still a little unclear on if we intend to have this page become the destination for all legacy Yellow Ribbon pages.
