### ISSUE TITLE
Auth Exp Profile | FE | Bug: zoom with gesture disabled for modals on iOS

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#48006]
In a recent research session, we noticed users can't use a touch gesture to enlarge text in modals. This can be reproduced by: 
1. logging into staging.va.gov (or prod, va.gov), on a touch screen device
2. going to the Contact Information section of profile.
3. Click edit on a section
4. Click edit on another section to trigger the "you are currently editing" modal. Try to use two fingers to zoom in. No dice.

The crisis line modal _does_ allow zoom by touch gesture; the sign in modal does not.

**Tasks**
- [ ] Update the code to enable enlarging via gesture for all modals 

AC

- [ ] A person can use a gesture to enlarge content in a modal on VA.gov

**Comment by andaleliz** [comment]
@SKasimow creating this from the research synthesis while I'm thinking about it. Please assign to FE as you see fit :)

**Comment by SKasimow** [comment]
FYI...you can zoom in on other messages such as "We don't seem to have your military records".

**Comment by andaleliz** [comment]
I think what you're referring to isn't in a modal component though.  I believe this specifically impacts modals, but it's not sitewide since the crisis line modal allows for gesture zooming.

**Comment by SKasimow** [comment]
Notes: Is this an issue specific to Profile modals - if so we can address. If not, talk to Design system folks.

Compare against Crisis modal and see if it uses the legacy react modal component.

**Comment by andaleliz** [comment]
Hi @joshkimux! Sharon isn't working with us anymore.  I'm not sure why she just unassigned herself without assigning it to anyone else. Thanks for rescuing this.

I just checked 2 non-profile modals - the crisis line, and the sign in.  Crisis line does allow for zooming in, but the sign-in modal does not.  On account of that, I'm going to call this a global issue. Who can I add as an assignee so it gets tracked with CAIA work?

**Comment by joshkimux** [comment]
I got you covered there! Re-assigning as a CAIA task

**Comment by coforma-terry** [comment]
@joshkimux - beat me to it - thanks!

**Comment by SarahKay8** [comment]
Hi @andaleliz! May I have a staging link so I can test this out?

**Comment by andaleliz** [comment]
@SarahKay8 sorry about that - it's staging.va.gov.  [Here's the staging user list](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv), in case you need that too.

I also updated the description so it's included there now.

**Comment by SarahKay8** [comment]
Got it thanks! @andaleliz

**Comment by RLHecht** [comment]
Closing this ticket as SK is going to create a new bug ticket.
