### ISSUE TITLE
Come up with more effective organization VAOS application folder

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#4801]
The VAOS application folder follows the typical structure of our other applications, which is an older React/Redux style:

- actions
- reducers
- components
- containers
- some kind of utilities folder
- sass
- tests

In our case, we have a giant components folder, and small actions/reducer folders. While we shouldn't create deep folder structures, better top-level organization might be useful.

**Comment by lenaecb** [comment]
Update: Reassess the timing of this work based on our technical discovery and implementation prep for FHIR/EAS

**Comment by vbahinwillit** [comment]
To address the issue of the large containers and components folder, it is suggested that the project be organized by feature instead. The following structure is proposed:

- components
    - Address
    - Alerts
    - Breadcrumbs
    - Buttons
    - FormButtons
    - RadioButton
    - Tabs
    - TextArea

- appointment-list
    - components
    - redux

- new-appointment
    - components
    - redux

- express-care
    - components
    - redux

## Component Folder
The top level components folder is intended to be used for reusable components. The 'appointments-list', 'new-appointments', and 'express-care' folders are intended to represent the current features of the VAOS application. Feature folders should contain everything required for a feature to work on its own.

## Feature Folder
The top level of the feature folder is intended to contain the pages (container components) that make up the feature. This folder can also contain nested page folders.

### Component Folder
The components folder under each feature is intended to contain components specific to a feature. These components are not intended to be shared.

## Redux Folder
The redux folder under each feature is intended to contain redux specific artifacts such as actions and reducers.

## Summary
To implement these changes will touch the majority of files in the project. So it is suggested that these changes are implements in stages.

1. Create new feature folders and sub-folders containing 'README.md' file
3. Determine which files will cause the least amount of disruption when moved
2. Gradually start moving chunks of files to the appropriate folders

## Concerns

- Coordinating these changes with team members working on other issues

**Comment by jbalboni** [comment]
Documented in GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/architecture/front_end_directory_structure.md
