### ISSUE TITLE
[Tech Team 2] Create team charter

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#48015]

**Comment by jhouse-solvd** [comment]
## Description 
As a newly formed team, Tech Team 2 needs a Team Charter document that outlines :
- Who the team is
- Why the team is here 
- How the team works
- What the team does 

## Background / context 
The Platform "Tech Team 2" is a newly formed project-oriented team w/ current members: 
- Kyle Matheny - Team Lead (TL)
- Jesse House - Product Manager (PM) 
- Ryan Smith - Frontend Engineer (FE)
- Chris Alexander - Frontend Engineer (FE)

## Acceptance Criteria
Documentation exists in the Tech Team 2 Space that outlines and details the following: 
- Summary
- Meet the team
- Why we’re here
  - Mission
  - Product Suite
  - Product Portfolio
  - Responsibilities
  - Roadmap
- How we work together
  - Regularly-scheduled meetings
  - Issues management 
  - Kanban board management
- How we communicate
  - Channels
  - Norms and expectations

**Comment by jhouse-solvd** [comment]
[Team Charter [WIP]](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2401796102/Team+Charter+WIP)

**Comment by jhouse-solvd** [comment]
@ph-One, @rsmithadhoc, @alexandec - Please review as time allows and drop questions, comments, suggestions, or other feedback on the document in Confluence. 

We'll work together to ensure that the charter speaks to our values and sets us up for effective collaboration and team success.

**Comment by ph-One** [comment]
Closing. Everyone has had eyes on this. This charter will continue to evolve with the team
