### ISSUE TITLE
Adding Daniel Scarbrough to DSVA Slack

### ISSUE THREAD

**Issue by cbrizen** [department-of-veterans-affairs/va.gov-team#48013]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Daniel just joined the team as a Data Engineer and will need to communicate via Slack with our stakeholders and the rest of the team.

Are you requesting to add an individual as a:

- Full member

- What channel(s) do they need to be added to? long-covid-public, long-covid-team

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [_daniel.scarborough@thoughtworks.com_] as a full member.

**Comment by LEHigley** [comment]
resent invite
