### ISSUE TITLE
[BUG] "English" need to have the "E" capitalized in the English JSON File

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48021]
## Tasks
- Change "in english" to "in English" in the English JSON file 
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/6ecd25cf-3983-4641-a7a6-4b7069e4ec3a)

**Comment by brianseek** [comment]
@loripusey this was just merged and should be ready to validate soon

**Comment by loripusey** [comment]
validated
