### ISSUE TITLE
BE | Profile | BGS Caching | Ch33 Banking Requests

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#48022]
## Background

Currently, the `BGS::People::Request#find_person_by_participant_id` method is using a caching mechanism that Trevor Bosaw put in place. 

The `CH33BankAccountsController` can also benefit from caching.

Tasks:
- [ ] Add caching to the `CH33BankAccountsController`.
- [ ] Determine cache expiration and review with team.

**Comment by SKasimow** [comment]
@tpharrison - was I supposed to move this to Sprint 86?

**Comment by tpharrison** [comment]
Sure - we can add to Sprint 86.

**Comment by tpharrison** [comment]
The intent was to add caching to `BGS.get_ch33_dd_eft_info` which returns bank account information.  Started working on these changes, but decided to roll them back.  The reason for this is that bank account information needs to be masked prior to caching, but the My-Education Benefits team is now retrieving unmasked direct deposit information for one of their forms so it can be submitted for claims processing.  We could add logic that determines whether to pull data from the source or from cache, but I think it is prudent to wait on this since latency isn't common or significant for this particular method and the Edu Benefits team just made these changes.
