### ISSUE TITLE
[FE] Claims and Appeals Section: Error not showing properly

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48038]
## Background
When logging into Staging, we noticed that some users had an error due to their claims and appeals information not being available. When the error appeared however it has odd placement and the Claims and Appeals heading does not appear. We believe this has happened before and it was due to conditional logic only showing the error OR the section header. It should be that both the header AND the error appear for the user.

![image](https://user-images.githubusercontent.com/97113607/195135006-3c8b319a-3b99-4880-b840-867f7f418553.png)

## Tasks
- [x] Update the FE condition so the Header and error appear together

## Acceptance Criteria
- [x] Claims and Appeals error is showing under a header and formatted properly

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ This may be hard to validate as the error only appears when there is an issue with the Claims and Appeals API

**Comment by tmitchellgcio** [comment]
This is a downtime notification. This was a bit before my time so I'm not sure what their purpose is or how it works exactly. This may take me longer to figure out than originally expected. I'm still tracking this down. Basically if it seems like a service is down I think they are supposed to say it's down. I'm looking for documentation

**Comment by ajakabcin** [comment]
There's documentation on error states for the current implementation of My VA (2.0) [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/claims-and-appeals-status.md#when-to-show-the-claims-and-appeals-section)

**Comment by tmitchellgcio** [comment]
PR here but it won't let me tag the ticket because Zenhub https://github.com/department-of-veterans-affairs/vets-website/pull/22454

**Comment by ericasauv09** [comment]
I got an error while validating with user 36 and it looks like this issue was fixed properly:
![Screen Shot 2022-10-24 at 14.34.05.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/1680a097-91ee-4d19-bd0e-1c4466fa2a05)
