### ISSUE TITLE
Vet Centers in Districts 2 and 3 to review

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48037]
## Issue Description

This ticket is to keep track of Michelle and Megan's reviews of Vet Center pages in Districts 2 and 3 before they are ready for final copyediting and to send to Tiffany for final signoff.

These are the pages that still need to be published:

### District 2
<details>
<summary> Requested reviews and feedback sent </summary>

- [x] Tampa Vet Center (MZ sent follow up feedback on 9/3
- [x] Mobile _(feedback sent 8/19 - MM)_
- [x] Johnson City  _(feedback sent 8/19 - MM)_ 
      - _needs second spotlight and with Megan for copy-editing_
- [x] Louisville _(feedback sent 8/22 - MM)_
- [x] Fort Lauderdale _(feedback sent 8/22 - MM, sent again by MZ on 9/5)_
       - _with Megan for copy-editing_
- [x] Melbourne Vet Center _(reached out to offer assistance 8/22 - MM)_ 
        - has new VOPS - Tiffany provided overview of resources and workbooks, etc on 8/24
        _meeting with Michelle on 10/13_
- [x] Naples Vet Center _(reached out to offer assistance 8/22, feedback sent 8/23 - MM)_
- [x] Clearwater Vet Center _(feedback sent 8/22 - MM)_
- [x] Tallahassee Vet Center  _(feedback sent 8/24- MM)_
- [x] San Juan Vet Center _(feedback sent 8/24- MM)_
- [x] Lakeland  _(feedback sent 9/14- MM)_
- [x] Birmingham _(feedback send 10/11 - MM)_
- [x] Sarasota _(requested 10/26 - sent feedback 10/26- MM)_

</details>

### District 3
<details>
<summary> Requested reviews and feedback sent </summary>

- [ ] Cedar Rapids _(feedback sent 8/30- MM)_
- [ ] Springfield, IL  _(feedback sent 8/30- MM)_
- [x] Evansville, IN _(feedback sent 8/30- MM)_
- [ ] St. Louis _(feedback sent 8/30- MM)_
- [ ] Sioux City _(feedback sent 8/31-this location will need more time to add service details and CAP images - MM)_
- [x] Quad Cities _(feedback sent 8/31- MM)_
Reviews requested 8/23
- [ ] Evanston Vet Center _(feedback sent 8/31- MM)_
- [ ] Rapid City, SD Vet Center _(requested during office hours - feedback sent 8/24 - MM)_(MZ sent more requests on 9.21)
- [x] Chicago Heights _(feedback sent 8/31- MM)_
Reviews requested 8/30
- [x] Kansas City _(feedback sent 8/31- MM)_
- [ ] St. Paul _(feedback sent 9/6- MM)_
- [x] Pontiac _(feedback sent 9/8- MM)_
- [x] Macomb County _(feedback sent 9/8- MM)_
- [ ] Orland Park _(feedback sent 9/8- MM)_
- [ ] Metro East _(feedback sent 9/9- MM)_
- [x] Bismarck _(feedback sent 9/9- MM)_
- [x] Stark County _(feedback sent 9/9- MM)_
- [ ] Lincoln _(feedback sent 9/9 and 9/16 - MM)_
- [x] Columbus, OH _(feedback sent 9/12- MM)_
- [x] Gary area _(feedback sent 9/12- MM)_
- [ ] La Crosse _(feedback sent 9/12- MM)_
- [ ] Dayton _( no local content or images has been added 9/12- MM)_
Reviews requested 9/8
- [x] Des Moines _(feedback sent 9/12- MM)_
- [x] Green Bay _(feedback sent 10/7- MM)_
- [ ] Saginaw _(asked for review 10/14-RH - feedback sent 10/14 - MM)_
- [x] Dearborn  _(proactively sent feedback 10/19- MM)_
- [x] Milwaukee  _(proactively sent feedback 10/19- MM)_
- [x] Omaha _(proactively sent feedback 10/19- MM)_
- [x] Manhattan, KS _(proactively sent feedback 10/19- MM)_ - same editor as Fargo, fyi
- [x] Forest Park  _(proactively sent feedback 10/20- MM)_
- [x] Duluth _(proactively sent feedback 10/20- MM)_
- [x] Fargo _(proactively sent feedback 10/20- MM)_ - same editor as Manhattan, KS, fyi
- [x] Fort Wayne _(requested 10/19 -  sent feedback 10/21- MM)_
- [x] Indianapolis _(requested 10/19  -  sent feedback 10/21- MM)_
- [x] Aurora Vet Center (_requested 11/8 - sent feedback 11/8 - MM_)
</details>

<details>
<summary> From Tiffany's email on 11/22 </summary> 

Vet Center | Status | Who
---| --- |---
Anoka  | submitted for an initial review and sent feedback | Michelle proactively reached out 11/30 - editor is working with Tiffany|
Aurora  | Michelle sent feedback 12/6
Bismarck  | submitted for an initial review and sent feedback | Michelle proactively reached out 11/30 |
Cedar Rapids  | met with Michelle - ready for copy-editing 12/7|
Clearwater | submitted for an initial review and sent feedback | Michelle proactively reached out 11/30 - meeting set 12/1, now ready for copy-editing
Dayton | ready for initial review | Michelle - feedback sent 11/23 and 12/2 - 
Dearborn  | submitted for an initial review and sent feedback - attended office hours 11/23||
Detroit  | not yet submitted for initial review | |
Duluth  | submitted for an initial review and sent feedback | Michelle proactively reached out 12/1|
Fargo  | submitted for an initial review and sent feedback ||
Forest Park  | submitted for an initial review and sent feedback |Michelle proactively reached out 12/1|
Fort Wayne  | submitted for an initial review and sent feedback, requested subsequent review 11/29  | Michelle - done 11/29 - ready for copy-editing 12/1 |
Gary Area  | Michelle proactively reached out 12/1 - ready for copy-editing 12/13|
Grand Rapids  | not yet submitted for initial review  | Michelle proactively send feedback 12/2| 
Green Bay  | submitted for an initial review and sent feedback ||
Indianapolis  | submitted for an initial review and sent feedback | Michelle proactively reached out 12/1|
Lincoln  | Ready for subsequent review | Michelle - done 11/22 - ready for copy-editing 12/1
Louisville | Changes made early November | Michelle - met 11/30 - will be ready for copy-editing after a few small changes and CAP confirmation
Manhattan, KS  | submitted for an initial review and sent feedback ||
Metro East  | submitted for an initial review and sent feedback | Michelle proactively reached out 12/1|
Milwaukee  | submitted for an initial review and sent feedback | Michelle proactively reached out 12/1|
Naples | Recent updates noticed 11/30 | Megan
Omaha  | Ready for subsequent review | Michelle - done 11/22
Orlando Park  | submitted for an initial review and sent feedback ||
Parma | not yet submitted for initial review  | |
Peoria  | not yet submitted for initial review - contacted support 11/28 | Michelle - done 11/29 |
Pontiac |  Ready for subsequent review | Michelle - needs mobile image and CAP confirmation, otherwise ready for copy-editing 11/23
Quad Cities  | submitted for an initial review and sent feedback | Michelle - ready for copy-editing 12/2|
Rapid City  | submitted for an initial review and sent feedback ||
Rockford  | not yet submitted for initial review  | Michelle will follow-up  |
Saginaw  | submitted for an initial review and sent feedback ||
Sioux City | Ready for subsequent review | Michelle - done 11/22, ready for copy-editing 12/2, pending CAP confirmation
Springfield, IL  | submitted for an initial review and sent feedback | Michelle proactively reached out 11/30 |
Springfield, MO  | not yet submitted for initial review  | Michelle - done 11/23 |
St. Louis  | Ready for subsequent review | Michelle - done 11/22
St. Paul | Ready for subsequent review | Megan
Stark County   | submitted for an initial review and sent feedback - requested review 11/30 | Michelle - needs 2 CAP photos and to confirm hours - otherwise, ready for copy-editing - 11/30 |
Toledo  | not yet submitted for initial review   | |
Traverse City  | requested review 12/1 | Michelle - feedback sent 12/1 - ready for copyediting 12/2  |
</details>

## Updated status
Vet Center | Status | 
---| ---
Aurora  | ready for copyediting 12/7 - _submitted for approval_
Cedar Rapids  | ready for copy-editing 12/7 _submitted for approval_
Dayton | Michelle - feedback sent 11/23 and 12/2 
Dearborn  | submitted for an initial review and sent feedback - attended office hours 11/23|
Detroit  | in progress - attended office hours on 12/7| 
Duluth   | Michelle proactively reached out 12/1 - _met 12/15- now ready for copy-editing_
Fargo  | submitted for an initial review and sent feedback 
Forest Park  |Michelle proactively reached out 12/1
Gary Area   | will be ready for final review after adding CAP 12/7 _submitted for approval_
Green Bay  | working with Tiffany | _ready for copy-editing per Tiffany on 12/12_
Indianapolis  | Michelle proactively reached out 12/1
La Crosse  |  ready for copy-editing - 12/8 - _submitted for approval_
Lakeland Vet Center | has been in contact with Tiffany as of 12/15 |
Lincoln  | ready for copy-editing 12/1 _submitted for approval_
Louisville | Michelle - met 11/30 - will be ready for copy-editing after a few small changes and CAP confirmation - Michelle checked in 12/7 _submitted for approval_
Manhattan, KS  | submitted for an initial review and sent feedback |
Metro East  | Michelle proactively reached out 12/1|
Milwaukee  | making final adjustments to Spotlights |
Mobile Vet Center | ready for copy editing 12/12 - CAP images pending _submitted for approval_
Naples |  _submitted for approval_
Okaloosa County Vet Center | ready for copy editing 12/13 _submitted for approval_
Omaha  | Michelle  send feedback 11/22 _submitted for approval_
Orland Park  | ready for copy-editing 12/6- _submitted for approval_
Palm Beach | ready for copy-editing 12/7 _submitted for approval_
Parma | not yet submitted for initial review - covered by Toledo director - meeting with Tiffany 12/14
Peoria  |  Michelle sent feedback 11/29 
Quad Cities  | ready for copy-editing 12/2- _submitted for approval_
Rapid City  | submitted for an initial review and sent feedback |
Rockford  | ready for copy-editing, 12/12 _submitted for approval_
Saginaw  | submitted for an initial review and sent feedback |
Springfield, IL  | Michelle proactively reached out 11/30 |
Springfield, MO  | Michelle sent feedback 11/23 
St. Louis  | Michelle sent feedback 11/23 
Tampa | _submitted for approval_
Toledo  | not yet submitted for initial review  - meeting with Tiffany 12/14 
Traverse City  |  ready for copyediting 12/2 _submitted for approval_

**Comment by mmiddaugh** [comment]
@megzehn Johnson City needs only a second spotlight but is otherwise ready for copy-editing. I sent the second spotlight request 9/22 but maybe it would make sense for you to send it as a gentle reminder along with any tweaks you find?

**Comment by mmiddaugh** [comment]
@megzehn San Juan Vet Center is ready for copyediting, per Tiffany. Thank you!

**Comment by RLHecht** [comment]
Closing this ticket as we're tracking the remaining 2 Vet Centers elsewehere.
