### ISSUE TITLE
Create list of kiosk functionality & evaluate for inclusion in our backlog for Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48058]
## Tasks
- Create list of ALL existing kiosk functionality 
- Evaluate functionality for possible inclusion in our backlog
- Present to team

**Comment by kristenmcconnell** [comment]
Posted [current list](https://dsva.slack.com/archives/C02GXKL8WM6/p1666636518154709) in Slack to have Shawn Adams review.

**Comment by kristenmcconnell** [comment]
Shawn edited the list of VetLink functionalities in this [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1666636518154709) post. He shared a Cerner functionality gap analysis in the thread as well.

**Comment by kristenmcconnell** [comment]
After speaking with @loripusey, we are going to close this ticket and do a value vs complexity analysis of these items within another ticket.
