### ISSUE TITLE
[Design] Create Draft Wireframes using the New DS Progress Bar

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48069]
## Tasks
- Collaborate with DS team on their new design for the Progress Bar component (talk to Josh Kim and Pam Hastings)
   - What is the DS team's vision
   - [DS Sketch file](https://www.sketch.com/s/09640425-48be-4019-8277-8a924eff1df7)
   - New design has connection to the [Sub-task pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task)
- Create draft wireframes for using the new DS stepped component in Pre-Check-in application
- Create draft wireframes for using the new DS stepped component in Check-in application

**Comment by kristenmcconnell** [comment]
Meeting with Pam Hastings and Josh Kim, who worked on the new pattern recently, is set up for Tuesday, Oct. 25 at 13 pm EST.

**Comment by kristenmcconnell** [comment]
We met with Josh and pam. After talking through the history of the progress bar and navigations needs within a form, we realized that the best pattern to look into is uk.gov's [task list pattern](https://design-system.service.gov.uk/patterns/task-list-pages/).

[Example of a complete uk.gov form using the pattern.](https://www.tax.service.gov.uk/feedback/TAMC)

**Comment by benbrasso-agile6** [comment]
We @kristenmcconnell @zach-park @ytsaoca did some low fi wires with the progress bar and task list components and reviewed them together. 

We decided that for pre check in, there are too few steps right now to utilize either of those components. As a next step, I'm going to create a separate ticket for finding ways to better visualize and communicate the 2-step process of pre check in and check in within the pre check in app. That visualization could be shown on the intro page or on the confirmation page or a combination of the two. 

For now, we're going to focus on solving the challenge of communicating the steps of check in within the check in app. Zach is working through a wireframe workflow for check in using the task list component with statuses on a new overview page and using the progress bar component on the individual pages.

**Comment by benbrasso-agile6** [comment]
@loripusey [I added this ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/48985). It can be pulled out of this Epic. Up to you.

**Comment by zach-park** [comment]
Here is the link to the lo-fi wireframes: https://app.mural.co/t/vfscie8528/m/vfscie8528/1666811871797/9a5b5cef3f567a6311f232325721fa1a6a17209f?sender=ue81e026b3c283b5452e52493
**The latest UX decision version is what the team agreed on**. Its screenshot is also attached below.

<img width="1701" alt="Screen Shot 2022-10-31 at 8 00 44 AM" src="https://user-images.githubusercontent.com/91493630/199042945-5237dab1-0ac9-4d38-b148-f457d8c8f79e.png">
