### ISSUE TITLE
Front-end: YR Search Results sorting functionality

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#4808]
# Description
This pertains to the [YR epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3703). We need to make sure we can sort by `Benefit Amount`, `School Name`, `City`, and `State` in our SearchResults component/container for YR.

## MVP Design Specs
Mobile: https://vsateams.invisionapp.com/share/K7VEJ2UE365#/screens
Desktop: https://vsateams.invisionapp.com/share/X5VOMBG2YP4#/screens/402038362

## Acceptance Criteria
- [ ] Add sort by logic for `Benefit Amount`, `School Name`, `City`, and `State`.

**Comment by kelsonic** [comment]
This ticket is blocked until this functionality is supported on `vets-api`.

**Comment by MickinSahni** [comment]
Removing this from sprint 13 due to blocker

**Comment by MickinSahni** [comment]
Still pending integration vets-api but gonna move forward on front-end

**Comment by kelsonic** [comment]
Updating this ticket to only focus on the FE implementation.

**Comment by kelsonic** [comment]
This ticket is actually blocked by 3 things:

1. https://github.com/department-of-veterans-affairs/va.gov-team/issues/5602
1. https://github.com/department-of-veterans-affairs/va.gov-team/issues/5608
1. An updated design spec that includes sorting: https://vsateams.invisionapp.com/share/X5VOMBG2YP4#/screens/402038362

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
This issue is being closed based on the new design spec.
