### ISSUE TITLE
[SPIKE] CHECK-IN: Explore if we Display Appointments for Which Check-in is NOT Enabled

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48101]
## Tasks
- Determine if we are getting appointments from PCI/API for facilities in which Check-in is NOT enabled
- If we are, are we displaying the following message (from the Product Guide)?

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/08653b38-937f-48c4-89b8-b26d2940de0a)

**Comment by acrollet** [comment]
I verified that we are getting appts for echeckin disabled, but are not displaying this message. It looks like we're not getting the correct eligibility status to be able to do so, I spoke with the API team and logged https://github.com/department-of-veterans-affairs/chip/issues/1396

We should re-check this once that's complete.

**Comment by acrollet** [comment]
@loripusey please see the above comment, do you want to keep this open to follow up or re-visit another way?

**Comment by loripusey** [comment]
Closing this one; I'm going to create a work ticket to display the "online check-in isn't available" message
![image](https://user-images.githubusercontent.com/86678742/201719164-6bac37e8-25bd-4add-bc97-554c66e4a897.png)
