### ISSUE TITLE
Fix typo in Form 22-5490 best bet on search.gov

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48117]
## Issue Description
Stakeholder Cinda Quattrini informed us there's a typo in the best bet on search.gov for Form 22-5490. It's currently showing as 22-5940 in the linkable text:

![Screen Shot 2022-10-12 at 8.23.37 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/39132022-4576-4a06-b829-38366e0e1c8d)

## Tasks
- [x] Change form number to 22-5490

## Acceptance Criteria
- [x] Search.gov is showing correct form number for the best bet

**Comment by mnorthuis** [comment]
This is corrected and validated on production. I also added the key words "dependent education" to capture variations on that.
