### ISSUE TITLE
[BUG] [FE] Address Bugs Identified During Wireframe Audit

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48110]
## Background
[Audit Documentation](https://docs.google.com/spreadsheets/d/1vr5m0tfqAtCtBFLMvn54aU9bdWhxR7GRxNkZzw42G10/edit#gid=0)

## Tasks
- Fix the items marked as "bug" that are highlighted in yellow (**for both Pre-Check-in and Check-in**)
    - First one
        ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/67379823-19f2-4e43-8af4-6de35c27cf37)
    - Second one
        ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/e152dd54-b7c3-41e3-996d-6eea3c549108)

**Comment by brianseek** [comment]
The first task in this ticket is an element outside of our control.

**Comment by brianseek** [comment]
@loripusey this is ready to be validated on stage. See this slack conversation for context around the changes here:
https://dsva.slack.com/archives/C02GXKL8WM6/p1667240759512029

**Comment by loripusey** [comment]
validated
