### ISSUE TITLE
Include facility timezone lookup in the VAOS::V2::AppointmentsController#create method

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#48115]
## Description
We need to update the facilities timezone offset in the preferred timezone VAOS FE is sending back (endpoint/name of field)
This would apply to direct appointment workflow.

Background:
For V0, we were sending the veterans preferred date with a 0 offset: desiredDate: ${data.preferredDate}T00:00:00+00:00Z and the facility timezone in a separate timezone field. It was confirmed that VAR appears to be ignoring the timeZone field on direct booking requests and getting the value from MFS v2 directly.
Vaos service doesn't do this so for v2, we need to send the veterans preferred date with the facility offset. i.e, if the facility's offset is UTC-5, we will send desiredDate: ${data.preferredDate}T00:00:00-05:00.

## Dev Notes
We want to modify the VAOS::V2::AppointmentsService#post_appointment method so that facility information is retrieved using the VAOS MobileFacilityService class. In the facility information is the facility's time zone. The desired date can then be modified within the post's body using the timezone if the appointment is directly scheduled, kind = clinic, and status = booked.

In the initial spike review, I thought the desired date update should go in the VAOS::V2::AppointmentsService#post_appointment method. But as I started implementing the change, I realized the VAOS::V2::AppointmentsController#new_appointment method is a better place for the changes.
  --ajm

## Acceptance Criteria
- [x] This should be behind the v2 toggle.
- [x] Accurate Facility timezone is being sent with post request.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Copied @marcynadeau notes from #47437

### **Notes for testing:  Once this is fixed test in the course of testing this defect test the Clinic Wait Time 2.**  
MBAA*1*13 caused the Clinic Wait Time2 NULL issue in CHYSHR.   The patch was backed out of CHYSHR. I retested today.

The  CID/Preferred date I entered  in VAOS was 10/1:
VistA shows.....OCT 02, 2022@18:00.  This is known defect.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/47354

Clinic Wait Time2 was NULL and now is being calculated but the calculation is off by a day since the above date is off by a day.
VistA show.....Clinic Wait Time2: 1 day. This should be two days since Preferred date 10/1 and actual appt date is 10/3. This will get fixed once 47354 is fixed.  Clinic wait time 2 is the difference b/w Appt  Date and Preferred/Desired Date of Appointment.

**Comment by ldelacosta** [comment]
@marcynadeau - This ticket can be tested. Please let us know if you have any issues. Thanks!

**Comment by beth-wodzinski** [comment]
After discussing with marcy, these were the scenarios I tested. 

1. Brienne Ferrara/Audiology/Cheyenne. 
Today's date: 10/28/22. Request Date: 11/1/22. Scheduled date: 11/10/22.

Expected dates in Vista:
   CID/Preferred date: 11/1/22
   Clinic Wait Time1: 13 days                                              
   Clinic Wait Time2: 9 days  
    
Actual results in Vista: 
    CID/Preferred date: OCT 31, 2022@18:00   
    Clinic Wait Time1: 13 days                                              
    Clinic Wait Time2: 10 days  
   
2. Cecil Morgan/Optometry/Cheyenne
Today's date: 10/28/22. Request date: 11/2/22. Scheduled date: 11/16/22 (14 days after request date)
   
Expected dates in Vista:
     CID/Preferred date: 11/2/22
     Clinic Wait Time1:  19 days                                              
     Clinic Wait Time2: 14 days  
  
Actual dates in Vista:
    CID/Preferred date: NOV 01, 2022@18:00                                               
    Clinic Wait Time1: 19 days                                              
    Clinic Wait Time2: 15 days                                              
 
3. Cecil Morgan/Optometry/Cheyenne
Today: 10/28/22. Request date: 11/10/22. Scheduled date: 11/17/22
 
 Expected dates in Vista:
    CID/Preferred date: 11/10/22
    Clinic Wait Time1: 20 days                                              
    Clinic Wait Time2: 7 days 
 
 Actual dates in Vista:                                              
    CID/Preferred date: 11/10/22
    Clinic Wait Time1: 20 days                                              
    Clinic Wait Time2: 8 days 
 
 Note from vista: 
 NOTE: Clinic Wait Time1 represents the difference between the date the appointment was entered (10/28) and the date it was performed.  Clinic Wait Time2 represents the difference between the 'CID/Preferred date' and the  date the appointment was performed.                                       
  
The CID/Preferred date is still wrong, and therefore the Clinic Wait Time2 is still wrong. This does not pass testing.

@marcynadeau @ldelacosta

**Comment by ajmagdub** [comment]
Changed so that the desired date/time is not modified and the facility time zone offset is added.

**Comment by ajmagdub** [comment]
@marcynadeau @beth-wodzinski this is ready for a re-test.

**Comment by beth-wodzinski** [comment]
@ldelacosta @marcynadeau This passes testing. I ran through the scenarios above and they all worked like a charm.

**Comment by ldelacosta** [comment]
Closing out the ticket. No new issues reported. Thanks!
