### ISSUE TITLE
Update NADL rate--HOLD TO PUBLISH FOR 10/24

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48119]
## Issue Description

The NADL rate on the [Native American direct loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page is changing on 10/24/22. We need to change the number to **6.00%**

**We need to publish this the morning of 10/24/22.**

## Tasks
- [x] Update rate (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New rate is live on production

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for publish on 10/24! 

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=758

**Comment by aliyahblackmore** [comment]
Hi @megzehn (cc: @RLHecht) just confirming that I checked and the rate change is still updated (after the "linkies"). 

This is ready for 10/24!

**Comment by megzehn** [comment]
@RLHecht I reviewed the rate change, and it looks good. This is ready for you to publish on Monday a.m.

Thank you so much!!

**Comment by RLHecht** [comment]
I published this. Will close out and let Raleigh know it's live after I validate.

**Comment by RLHecht** [comment]
This is live. Closing!
