### ISSUE TITLE
[Research] Run Usability Research Sessions on Baseline Tasks for 10-10EZ

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#48120]
## Issue Description
Conduct the usability research sessions on the baseline tasks for 10-10EZ.

## Resources
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-01-Baseline%20Task%20Research/research-plan.md)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-01-Baseline%20Task%20Research/conversation-guide.md)
- [Link to item on Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/212)

---
## Tasks
- [Platform Research Checklist - Conduct Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-5.Conductsessions)

## Acceptance Criteria
- [x] Moderate all sessions scheduled 
- [x] Complete tasks for before, during and after research sessions
---

**Comment by thehastingsp** [comment]
@jessicastump could @TPurple and I potentially attend a few of these?

**Comment by jessicastump** [comment]
Sure @thehastingsp! Let me know what ones/times work for you both and I can add to the invite - should be able to see from OCTO calendar but let me know if you have any questions about which sessions to join.
