### ISSUE TITLE
Request e2e tests and axe checks be added to GI Bill Comparison Tool

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#4812]
## Description

The GI Bill Comparison Tool (GIBCT) has end-to-end tests for the first page only. We should explore adding e2e tests for the second page of search results, and the third page of provider detail views. Staging URLs will be provided below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] End to end tests are written for the search results page. Sample URL for a search on keyword "Omaha": https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=omaha&vetTecProvider=false
- [ ] End to end tests are written for the provider detail page. Sample URL for an Omaha provider: https://staging.va.gov/gi-bill-comparison-tool/profile/31002227
- [ ] End to end tests include an [axeCheck](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/testing/e2e/nightwatch-commands/axeCheck.js) for the main content areas.

**Comment by zurbergram** [comment]
This is duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/7373

**Comment by zurbergram** [comment]
@1Copenut this is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/7373

**Comment by 1Copenut** [comment]
@zurbergram Good call. I must have forgotten I wrote this ticket some time back. I'll close it in favor of 7373.
