### ISSUE TITLE
YR Comparison Results page

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#4814]
# Description
This pertains to the [YR epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3703). We need to create a component/container that renders all of the comparison results.

## MVP Design Specs
Mobile: https://vsateams.invisionapp.com/share/XBVON0YMJ4Y
Desktop: https://vsateams.invisionapp.com/share/X5VOMBG2YP4#/screens

## Acceptance Criteria
- [ ] Create relevant actions for the ComparisonResults + unit tests.
- [ ] Create relevant api functions for ComparisonResults + unit tests.
- [ ] Create relevant constants for ComparisonResults + unit tests.
- [ ] Create ComparisonResults container + unit tests.
- [ ] Create relevant sub components + unit tests for each.
- [ ] Create relevant helpers for ComparisonResults + unit tests.
- [ ] Update relevant reducers for ComparisonResults + unit tests.
- [x] Add flag to show this on dev/staging.

**Comment by andaleliz** [comment]
Based on the usability study, we can limit the amount of schools to compare to 5.

**Comment by MickinSahni** [comment]
Next step: Figure out routing
Decision to be made: Moving forward with new page (opposed to a modal). Allows comparison results to persist e.g. if a Veteran shares this link with others. But, research participants have not voiced this as a need. Should this be part of MVP?

**Comment by andaleliz** [comment]
@kelsonic When you write up the DOM for the page w/ the comparison table on it, can you please make sure that the text saying how many schools are selected (immediately under the h1) is either a `<caption>` element inside the `<table>`, or the element gets an `id="tableCaption"` attribute, and then the table gets an `aria-labelledby="tableCaption"` attribute?  

This will ensure that screen readers can properly announce the table. Thank you!

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- continue on this for sprint 14

**Comment by kelsonic** [comment]
This ticket is now [being postponed](https://dsva.slack.com/archives/C52CL1PKQ/p1581025377388100?thread_ts=1581019248.376100&cid=C52CL1PKQ) until [we can verify that the acceptance criteria on this ticket are still valid](https://dsva.slack.com/archives/C52CL1PKQ/p1581022487382700?thread_ts=1581019248.376100&cid=C52CL1PKQ).

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
This issue is being closed as it is not needed based on the new design spec.
