### ISSUE TITLE
AWS access for Ritesh Patel

### ISSUE THREAD

**Issue by iriteshp** [department-of-veterans-affairs/va.gov-team#48143]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Ritesh Patel

### Your Email

ritesh.patel@adhocteam.us

### Team, Role, and Company of the target individual

Koala, Lighthouse, Adhoc LLC

### Product Manager (PM) name and email

Alayna Abel, alayna@adhocteam.us

### Product Owner (PO) name and email

Dave Mazik, david.mazik@va.gov

### Desired AWS Access

I do already have an AWS account. I need access same as **Kevin Gin (Team Koala, Lighthouse)**

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ianhundere** [comment]
they're not listed on any roster.
@iriteshp

**Comment by ianhundere** [comment]
and they are now; VFS Team Roster

**Comment by td-usds** [comment]
Requested access approved

**Comment by ianhundere** [comment]
asking for additional perms specifically the ability to run/maintain specific ECS clusters and RDS instances as per:
- https://dsva.slack.com/archives/CBU0KDSB1/p1668545596909119

**Comment by td-usds** [comment]
Provided this is similar to Kevin Gin's request, the same requested permissions are approved

cf.:
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1319104037 
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/40233#issuecomment-1320169859
