### ISSUE TITLE
VEText Feature Request: Opt-out of All Comms Selector

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#48158]
The current toggle only opts out of appointment reminders.

Recently, numerous staffmembers have been requesting the addition of a checkbox/button/toggle that will opt-out the patient to **all** VEText use cases: appointment reminders, vaccine outreach, Rx tracking, etc.

**Comment by jwowk** [comment]
Rob completed
