### ISSUE TITLE
Supplemental Claims | Review Veteran Personal Info

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48159]
## Value Statement
**_As a_** Veteran 
**_I want to_** review my personal info
**_So that_** I know it's accurate and can edit it if needed. 

---
## Acceptance Criteria
- [x] User cannot make edits to their SSN, file number, DOB, or gender
- [x] User cannot proceed if they don't have the right properties
- [x] User receives error message if they don't have required data for this section
- [x] Unit tests complete (90% coverage)
- [x] E2E tests complete
- [x] Accessibility testing complete
- [x] Reviewed and approved by product and/or design

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/Mdvgll/p/6CCF7EBD-6581-4D46-836D-5AACD930F159/canvas?posX=-625.5418090820312&posY=-61.72180938720703&zoom=0.7663475275039673)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)
- [ERROR](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/9Pvvp97)

## Definition of Ready 

- [x] Clear value description
- [x] Testable acceptance criteria
- [x] Accessibility added to acceptance criteria
- [x] Approved designs attached
- [x] Sample data provided where appropriate
- [x] Estimated to fit within the sprint
- [x] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---

**Comment by thehastingsp** [comment]
design approved, content still in progress.

**Comment by thehastingsp** [comment]
Added prototype to ticket.

**Comment by thehastingsp** [comment]
@Mottie @saderagsdale [content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md) approved.

**Comment by Mottie** [comment]
This work has been merged, it should be available for testing in staging soon (like maybe an hour or so), [check the status here, and look for "Supplemental Claims | Update Veteran information page"](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/)

**Comment by saderagsdale** [comment]
@Mottie confirm when this is ready to close.

**Comment by Mottie** [comment]
Opened a PR to fix handling of prefill data from the backend

**Comment by saderagsdale** [comment]
@Mottie is this dependent on #49068?

**Comment by Mottie** [comment]
Nope, this is done and ready to be reviewed.

**Comment by thehastingsp** [comment]
this looks good from my review.

**Comment by saderagsdale** [comment]
@Mottie if the other AC are complete, you can check them off and close this one up

**Comment by Mottie** [comment]
> User cannot proceed if they don't have the right properties

This AC doesn't apply. The page is only displaying info. We are preventing the Veteran from starting the form if they aren't LOA3 verified, which I believe means that they have some sort of ID associated (EDIPI, SSN, BIRLS ID or Participant ID), but I'm not sure which. I'll discuss this with Kyle next week

**Comment by saderagsdale** [comment]
@Mottie cool beans. would be good to confirm where we cut off access if the user doesn't have the right properties.

**Comment by Mottie** [comment]
Asked for context ([thread](https://dsva.slack.com/archives/CSFV4QTKN/p1668442137273909)):

Me: I'm curious what exactly being LOA3 verified means... do we have access to the Veteran's SSN, EDIPI, or whatever once they are verified? In some of our forms we have to take extra steps to check these, but is it unnecessary?

> LOA3 verified means the user completed a NIST compliant verification process with IDme (for [login.gov](http://login.gov/) its IAL2 compliant). In terms of what this means for [VA.gov](http://va.gov/), it means we should always get back:
>
> - first name
> - last name
> - SSN
> - DOB
> - ICN (from MPI)
>
> as for promises on other values, we cant make that because anyone can verify on [VA.gov](http://va.gov/) with idme and [login.gov](http://login.gov/). It doesn't mean they are Veterans
>
> so you should still always look for these values because they cannot be promised

**Comment by saderagsdale** [comment]
@saderagsdale ask Matt/Alejandro about this one.

**Comment by saderagsdale** [comment]
@Mottie Let's move forward with the requirement that these fields be validated in order for a user to complete the form.

**Comment by saderagsdale** [comment]
@eileen-coforma and @Mottie to add error message that appears if the user doesn't have the required info for this section.

**Comment by saderagsdale** [comment]
@eileen-coforma pinging you on this one

**Comment by eileen-coforma** [comment]
@saderagsdale Copy is blocked because of a phone number. 

Do you know who we can contact to get the right phone number for the veterans who need to change/add their personal identifying information? Is it the general help line (I hope not)?

**Comment by eileen-coforma** [comment]
@Mottie Design has been updated with the approved copy for error messaging.

**Comment by Mottie** [comment]
This is a work in progress. We don't have access to the Veteran's SSN before starting the form, so we'll be checking a value within their profile.

**Comment by saderagsdale** [comment]
@eileen-coforma we can test this by trying to login with an email address that is id.me

**Comment by saderagsdale** [comment]
@Mottie looking for an LOA3 account to test with or will share screengrab in local environment

**Comment by eileen-coforma** [comment]
Checked with the LOA3 account on dev using [link](https://coforma.slack.com/archives/C039EAY655H/p1673550388079629) that @Mottie provided.
It works. This is good to go.

**Comment by saderagsdale** [comment]
Looks good to me too.
