### ISSUE TITLE
Content Request from Auth Exp - My VA - "My VA audit improvements"

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48155]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.* 
- Our team is making multiple changes to the content on the My VA page as part of our My VA Audit project -  [Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit). We have worked with Danielle Thierry and she has reviewed the content. This is our formal request for a final content review before we move onto Midpoint Review.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [X] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users? 
December, 2022  
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
- Link to or attach user flows: N/A
- Link to prototype or mockups:

[Sketch mockup 1](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/E6ADDE2C-0D24-484F-A829-CEA239BD56E6) (user with no claims or appeals or health care; with an application in progress)
**Sections we need reviewed for content:** Claims and appeals, health care, education and training, saved applications

[Sketch mockup 2](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/10A09E21-70D7-4606-9E8A-1EBB31AE8EC9) (User who has claims and appeals and health care and no saved applications)
**Sections we need reviewed for content:** Saved applications

[Sketch mockup 3](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/32BCF55D-35A5-4A17-9F37-3DCA903B7A50) (LOA1 user)
This view isn't changing from how it currently looks except for the style of the identity verification CTA but since it's likely been a long time since it's been reviewed by content, would like you all to confirm the content of this CTA is still good.

- [Link to epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41934)

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Late Nov/Early Dec
- Estimated staging review date: Late Nov
- Content and IA work needed by: Ideally by 10/31

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Authenticated Experience - My VA
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Anastasia Jakabcin, Erica Sauve
-	Designer: Angela Agosto
-	FE engineer: Taylor Mitchell
-	Product/team Slack channel: accountexp-authexp

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Not sure if you have more background on this ticket. @ericasauv09 if you haven't met with Danielle about this, could you provide a little more info in the ticket above with what specific content or IA help you're looking for from our team? This way I'll know how to assign it. Thanks!

**Comment by ericasauv09** [comment]
Sorry @RLHecht I thought I had to post in the Slack channel to formally submit this, I just starting creating this today to gather the info needed in the ticket, I am still waiting on a few things before we are ready for your team to take a look. I should have it all completed by Friday.

**Comment by RLHecht** [comment]
ah got it! Since I'm automatically assigned I got the alert. I'll check back tomorrow for more info. Thanks for letting me know!

**Comment by ericasauv09** [comment]
@RLHecht this is all set now, do I need to post it in your Slack channel?

**Comment by RLHecht** [comment]
Thanks! Yeah, please post a message just so the rest of the team has awareness.

**Comment by ericasauv09** [comment]
@RLHecht Do you have an estimate of when the content review will be complete for this? thanks!

**Comment by RLHecht** [comment]
@ericasauv09 We are working on this currently and should have feedback by end of day tomorrow. We might need to follow up on some of it with Danielle before passing to you but I'll keep you posted.

**Comment by laurwill** [comment]
Hi @ericasauv09 , I'm getting "artboard does not exist" for the links to sketch mockups 2 and 3 above. Could you confirm which screens/links you'd like us to look at for those? Thank you!

**Comment by ericasauv09** [comment]
@laurwill sorry about that, @aagosto90 is going to take a look and update those links.

**Comment by aagosto90** [comment]
Hi @laurwill ; could you try those links again now? They are working for me but the designs have been updated in Sketch since I added them to this ticket and the first one has not so I'm wondering if that was causing a glitch for you.

**Comment by laurwill** [comment]
Working now! Thank you :)

**Comment by laurwill** [comment]
Hi @ericasauv09 , 
Here are a few notes on the content in the Sketch screens. Let me know if you'd like to chat about anything. Thanks for the chance to review! 

All screens
- Suggest removing "service connected" after "Your disability rating: 40%" (I think it could read as % connected to service rather than % disabling)
- I wondered if "decision reviews" should also appear in the "Claims and appeals" header — but I think there have been some recent discussions about this point, so I'll follow up about this tomorrow!

In [Sketch mockup 1](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/E6ADDE2C-0D24-484F-A829-CEA239BD56E6)
- Suggest changing "View your payment history" link to "Review your payment history" (we're moving away from sighted words like "view" when possible)
- In the links under "Education benefits", cap "GI Bill" and "GI Bill Statement of Benefits"
- And a question for consideration — In the label of the saved application, would it be helpful to get more specific than "Application for education benefits"? I think it's possible a user might apply for more than one type, so could consider including the name of the program (in this case National Call to Service).

In [Sketch mockup 2](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/10A09E21-70D7-4606-9E8A-1EBB31AE8EC9) 
- Suggest changing "View details" to "Get your claim details" or something similar
- Is "evidence gathering, review, and decision" a single status option? "Evidence gathering" sounds like an earlier step than "decision," but maybe there's a need to group these!

In [Sketch mockup 3](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/32BCF55D-35A5-4A17-9F37-3DCA903B7A50)
- Suggest shortening the body text of the green sign-in block (under the "Verify your identity" header):

We need to make sure it's you before we can give you access to your personal information. 

It takes about 10 minutes to verify your identity. You only need to do this once.

**Comment by ericasauv09** [comment]
Thank you @laurwill, my team will review your recommendations and let you know if we have any questions!

**Comment by ericasauv09** [comment]
@laurwill thank you so much for your feedback, here are the changes we will be making:

1. We will be updating all links that mention "view" to "review." 
2. We will also update the GI Bill information to be capitalized. 
3. We are going to look into what other types of benefits users may be able to apply for, we are unsure if we can be more specific here. 
4. We cannot update the Claims/Appeals status as those are the statuses available from the claims tool. 
5. We will also review the body of text for "verify your identity" We believe it is important to explain to users why they should verify their identity but we understand this may be done in a more simplified manner.

**Comment by ajakabcin** [comment]
Work to address the changes that @ericasauv09 outlined can be tracked in #48701

**Comment by RLHecht** [comment]
@ericasauv09 I'm going to close this as I think our team's work is complete. Please reopen if you need anything more from us. Thanks!
