### ISSUE TITLE
'back' button skips some pages

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4815]
E.g.: when veteran chooses sleep care, then selects a follow-up subtype of sleep care, then continue to facility selection, then hit back, they go to the first 'type of care' page. I think there are a couple of other instances of this I've run across previously, but not sure where specifically.

When hitting the 'back' button, veterans should go to the last page in the flow in almost all, if not all, cases.

AC
- [ ] Back button behavior on all pages goes to last previous page

**Comment by narin** [comment]
Should be address by PR https://github.com/department-of-veterans-affairs/vets-website/pull/11482
