### ISSUE TITLE
Ability to opt-out of multiple/all VEText Use Cases / Short Codes

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#48152]
There have been requests for Veterans to be able to opt-out of more than just the first short code features (appointment reminders, etc.) which is what they are limited to at this time.

Two options proposed:

1. On the VEText patient message tool, we expand the "opt-out" checkbox to become a multi-selection DDL for each use case/stop code so that staff can opt patients in or out of necessary UCs

2. In lieu of responding just "STOP" to all 3 short-codes, Veterans can respond to any message with "STOP ALL" (Or something else unique) to opt out of every VEText UC

**Comment by lindsay-insco** [comment]
Going into staging today

**Comment by lindsay-insco** [comment]
Unable to test due to issue with invoking certain RPCs against dev VistA - Rob investigating

**Comment by ahicksfearless** [comment]
Sent Justin STOP verbiage.
