### ISSUE TITLE
Supplemental Claims | Follow these steps to get started

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48156]
## Value Statement
**_As a_** Veteran
**_I want to_** know how to complete my supplemental claim
**_So that_** I'm prepared and know what to expect when I fill out the form.

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] User can enter the **Veteran Info** section by clicking **Start your claim**
- [ ] User can open and close accordions underneath each step
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [DESIGNS](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/Mdvgll/p/B3A2055C-DABF-4873-8EB5-846DCFDD0AB3/canvas?posX=-710.3186645507812&posY=-121.84492492675781&zoom=0.5904070138931274)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Open Questions
- Does the user need to be LOA3 (SSN, file number, DOB, and gender confirmed) to proceed?
- What messaging is shown if the user doesn't have the required user properties? (design)

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---

**Comment by saderagsdale** [comment]
Note: We can mock the LOA1/3 properties in local environments.

**Comment by thehastingsp** [comment]
Added prototype to ticket.

**Comment by thehastingsp** [comment]
@Mottie @saderagsdale [content approved](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md). I think this is a duplicate ticket - [this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46510)?
