### ISSUE TITLE
GIDS: Selecting the wrong value in the Column Separator drop-down on upload results in "Something Went Wrong" error message

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4817]
The validation for how a file is delimited is broken. If a user attempts to upload a pipe-delimited file but selects the comma option from the Column Separator drop-down, they should receive an error message indicating that they should check the data. Currently the user only receives the generic "Something Went Wrong" error message and is unable to proceed without re-accessing GIDS.

![Screen Shot 2020-01-14 at 8.37.17 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/31f174f4-153f-495a-85aa-d129a0268e1f)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/542

**Comment by delli-gatti-michael** [comment]
This fix is now present in Staging. Closing this issue
