### ISSUE TITLE
GIDS: EduProgram has an extra bullet point below "These columns must have a value: facility code" for CSV Data Requirements

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#4818]
1. Navigate to https://staging.va.gov/gids/uploads/new/EduProgram
2. Under "These columns must have a value: facility code" there is an extra bullet point
##
![Screen Shot 2020-01-14 at 8.59.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8030b86a-0511-445a-b4e8-86f7bf7cc1c1)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/542

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-01-14 at 10.43.19 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c62e0691-95df-4f59-a41f-24b671633b1b)

**Comment by sonntag-adam** [comment]
In staging. Closing out bug.
