### ISSUE TITLE
BE | Profile | Database Queries

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48192]
## Background

The VA.gov profile team needs help answering the following questions: 

1. How many people save a Mailing address or Home address with the "I live on a United States military base outside of the United States." checkbox checked? 

This can be found at https://www.va.gov/profile/contact-information.

2. How many accounts are left blank for  "Contact email" out of total accounts?

This field can also be found at https://www.va.gov/profile/contact-information.

## Tasks
- [x] Request the VA Profile team run a database query to provide us with the above information

**Comment by tpharrison** [comment]
Ian McEwan (VA Profile) will run these queries on Monday, Oct. 17th.

**Comment by SKasimow** [comment]
Awesome - thanks Tom!

**Comment by tpharrison** [comment]
Asked Ian McEwan to run queries for the following:

1. How many production users have an overseas military address (home or mailing)?
2. How many production users have an overseas military address (home or mailing) with an address-type of "Domestic"?
3. How many users are missing an email address?

His answers...

- VA Profile has contact information for 26.2 million people.
- 34K have overseas military.
- 7.6 million have email addresses.

Ian is still working on question 2.
