### ISSUE TITLE
Midpoint Review - IA Feedback - VAOS VA Online Scheduling

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#48190]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

- Align breadcrumb segment text with H1 of page 
  - i.e. "VA online scheduling" should be edited to align w/ page title
- use the mobile version of the breadcrumb on tablet or phone
  - Do not use "back" on [details page](https://www.figma.com/proto/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?page-id=1160%3A65447&node-id=1170%3A62650&viewport=-5700%2C-6043%2C0.24&scaling=min-zoom&starting-point-node-id=1334%3A68885&show-proto-sidebar=1)
- Make sure that breadcrumb corresponds to path shown in leftnav 
  - breadcrumb on "Schedule and manage..." does not include 
  - Continue working w/ sitewide content to achieve desired clarity on labels for online sessions
- Use a drop-down component instead of the hanging links (Pending/Past) on [appointments list page](https://www.figma.com/proto/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?page-id=1160%3A65447&node-id=1169%3A59522&viewport=-5700%2C-6043%2C0.24&scaling=min-zoom&starting-point-node-id=1169%3A59522&show-proto-sidebar=1)
  
**Should:**
- Iterate Experimental Design of new card pattern to determine layout of appointments on desktop displays

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
@jimuhh thanks! Just a couple of follow-up questions for you:

> breadcrumb on "Schedule and manage..." does not include

I think a word is missing after "include" here? ^

> Use a drop-down component instead of the hanging links (Pending/Past) on appointments list page

Why? The links go to separate pages. It would be confusing to ask a user to switch to an item in a dropdown to navigate to a new page. And since there are fewer than five options, it doesn't seem worth hiding them in a dropdown menu.
We switched from using a dropdown to links because we believed that the dropdown was reducing discoverability of these pages. We're currently gathering usage data on the change (this change was made separately from this work.)

**Comment by jimuhh** [comment]
@outerpress Thanks for the feedback. I will edit the ticket to fix the sentence fragment. 
As far as the decision on links vs drop downs, that was a consensus decision arrived at after discussions with colleagues who felt that the links represented a departure from our standard design patterns.  FWIW, I agree with you that these links are probably more discoverable and wish I had argued that case harder. 

But IMO this is a case worth appealing. I would recommend your team put together a document to pitch these contextual links as experimental design components. I certainly see their usefulness.

**Comment by outerpress** [comment]
Gotcha, thanks @jimuhh ! 

We released the change from dropdown to links list while we were in the process of redesigning the appointments list. So I will do as you say and propose that as an experimental design feature. We're getting comparative usage data now so that should be helpful.

**Comment by outerpress** [comment]
@ldelacosta we've covered everything in this ticket, and will open up an experimental design ticket in the future for the appointments list. You can close this ticket.

**Comment by ldelacosta** [comment]
No further action needed. Closing out the ticket.
