### ISSUE TITLE
Offboarding of Lauren Maxwell

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#48191]
# Description
Please provide the following information about the individual being offboarded:
- name:
  > Lauren (Mary) Maxwell
- team name:
  > FLT
- role on team:
  > Engineering
- expected last day:
  >  _(09/13/2022)_
- company they work for:
  > Ad Hoc
- email: _(Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc....)_
  > lauren.maxwell@adhocteam.us
- GitHub username: _(Please include @ symbol)_
  > @mlauren 
- additional access they may have: _(First line formatted with access titles only. Additional notes may be added on second line after the list.)_
  > unknown  
 
 
## Acceptance Criteria
*Performed by Platform team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] Requested removal from DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Requested removal from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key.
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS user name (typically FIRST_NAME.LAST_NAME).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://vagov.ddog-gov.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Requested removal from Google analytics and Domo by checking that the `analytics-insights` label is on this Issue. 
 - [x] Bot user GitHub account(s) YubiKey(s) removed
   > Typically only applies to Infrastructure team members.  
   > Refers to the `va-bot`, `va-vfs-bot`, and `va-vsp-bot` users.  
   > Documentation for this process can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members).

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/platform-analytics-insights-team , @department-of-veterans-affairs/confluence-admins

**Comment by holdenhinkle** [comment]
@department-of-veterans-affairs/confluence-admins Can you please remove Lauren Maxwell from Confluence? https://vfs.atlassian.net/wiki/people/618193a4062f4c00691d775e

**Comment by holdenhinkle** [comment]
Oseas Moran
  [1 minute ago](https://dsva.slack.com/archives/C02RLAUM2LV/p1666024877773109?thread_ts=1665600171.547229&cid=C02RLAUM2LV)
User does not have AWS as I cant find in IAM directory (edited)

**Comment by holdenhinkle** [comment]
Request to have user removed from VA GitHub Org - https://github.com/department-of-veterans-affairs/github-user-requests/issues/12917

**Comment by holdenhinkle** [comment]
User does not have a PageDuty account

**Comment by holdenhinkle** [comment]
User does not have a Sentry account

**Comment by holdenhinkle** [comment]
Submitted a support request with the Analytics Insights team asking them to remove her from GA and DOMO - https://dsva.slack.com/archives/CBU0KDSB1/p1666025603217209

**Comment by holdenhinkle** [comment]
User does not have bot user GitHub account(s) YubiKey(s).

**Comment by michelle-dooley** [comment]
No GA or Domo.

**Comment by holdenhinkle** [comment]
> No GA or Domo.

Thank you!
