### ISSUE TITLE
SCO: School certifying officials section not displaying on profile page

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#4819]
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/HACK%20REACTOR%20SOFTWARE%20ENGINEERING
2. Scroll down to School certifying officials section.
##
![Screen Shot 2020-01-14 at 10.47.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4a0b36ac-1f8a-47e3-9142-8030946ced88)

**Comment by dmccurdybah** [comment]
Can be tested on vets-website branch `bah-sco-fix`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-01-14 at 1.16.14 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5eeee203-9157-4d40-9c87-e54f95a2a826)

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
