### ISSUE TITLE
Figuring out additional meeting cadence

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#48206]

**Comment by Eallan919** [comment]
@tbaker1026 Did y'all get the demo schedule after chatting with Andrea? If yes, let's sync at the end of standup :)

**Comment by Eallan919** [comment]
Em's 1:1 with Matthew scheduled every Tuesday

**Comment by Eallan919** [comment]
@tbaker1026 Maybe on Tuesday- at the Sprint start (every other week) we can extend our standup and have 30 min of refinement? Have a think and LMK if that sounds good!

**Comment by Eallan919** [comment]
We will cover in our sync today! I should be able to close this out this afternoon

**Comment by Eallan919** [comment]
okay! Meetings are scheduled! @ndsprinkle can coordinate with engineers on their syncs + a sync with Matthew if need be!
