### ISSUE TITLE
GIBCT: Caching of calls in vets-api needs to be much shorter

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4820]
Currently, vets-api calls are cached every 86400 seconds (24 Hours). This long time period is causing issues displaying information to the end-user. Shortening the time to 900 seconds (15 minutes) would help alleviate these issues.

**Comment by dmccurdybah** [comment]
Can be tested using vets-api branch `gids-redis-ttl`

PR: https://github.com/department-of-veterans-affairs/vets-api/pull/3781

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging. Closing this issue
