### ISSUE TITLE
Investigate how to auto-generate models for forms in vets-api

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#48204]

**Comment by tbaker1026** [comment]
Demo stuff to Jesse & Nick - worth keeping working on it- able to generate stuff for the backend stuff to stub in. Figure out how far it goes etc.

**Comment by charleystran** [comment]
As a spike, I think we have decided with Nick that the spike proved we could do it and this is a go. Closing the spike ticket and will create others for the non spike work
