### ISSUE TITLE
Chat with Central Mail to see if we can get their paper submission metrics

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#48203]
https://docs.google.com/spreadsheets/d/1yVuH4Ltp00X-XAZhWp5g9GaUl-Jgxd8q/edit#gid=2011638928

**Comment by tbaker1026** [comment]
Charley to see if they can provide the form # on the download and find out what taxonomy means.

**Comment by tbaker1026** [comment]
Sent request back to Melissa - to explain what the taxonomy is and the form #

**Comment by tbaker1026** [comment]
Form # is in the name but not consistent.

**Comment by charleystran** [comment]
I think we can close this one. I dont think we will get any more detailed info from central mail on this.
