### ISSUE TITLE
Build a script or application to scrape/analyze a PDF and output a "complexity score" (and other helpful info)

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#48215]

**Comment by tbaker1026** [comment]
Have general skeleton done, right now it excepts a single PDF at a time and then adapt for multiple PDF's.  Trying to use a different PDF reader, to see if get different results from what Jesse was using.  Look into Popular PDF

**Comment by ndsprinkle** [comment]
This is the PDF analyzing tool used by vets-api: https://poppler.freedesktop.org/

Seems a bit dated, but may be an alternative to the other PDF parsing tools we are looking at.
