### ISSUE TITLE
Reviewing/diving into VAFSC to see what works and what doesn't Front End

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#48210]

**Comment by jessecanderson** [comment]
All the work I've done to get this going and the example for the 10-10d form can be found in the [upgrade_yarn](https://github.com/department-of-veterans-affairs/va-forms-system-core/tree/upgrade_yarn) branch in the core library repo.

**Comment by Eallan919** [comment]
[Feature List Doc](https://docs.google.com/document/d/1Vj3-_2WKX31PZ2teM1uOvfM9eJNJv-G1KSXh5RUvMZ8/edit#)
