### ISSUE TITLE
Reach out to team utilizing Docusign

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#48232]
We would like to understand more about potential solutions to use to digitize unauthenticated forms. 

Reach out to teams/programs using Docusign and set up a meeting/info transfer with the blockers and work-arounds the teams utilized. 

At the end, our team needs to assess if we want to leverage docusign or implement another solution.

**Comment by tbaker1026** [comment]
Reached out to Nicole working with Docusign

**Comment by Eallan919** [comment]
Started a convo with LH folks although that is not proving as fruitful. Marci is our go to person atm. Which, Pat and Tricia are syncing with her. Closing this out.
