### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by eli-oat** [department-of-veterans-affairs/va.gov-team#48238]
### Your Name

Eli Mellen

### Your Email

eli.mellen@adhocteam.us

### Your Role and Team

Associate Product Manager and QA specialist on Shared Support

### Product Manager (PM) name and email

Eli Mellen, eli.mellen@adhocteam.us

### Product Owner (PO) name and email

Martha Wilkes, martha.wilkes@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiaN0B3MKuFmkfMCbXGnrkCMmKHFJ30INvU+9S8kSGh6FIwDpqup1FyswbQcXqf6N/PvPezBs0KMnd5raMwmGALyo5leb7I6j9NSOZRMNQqdzySw5VVLUEe7TagzBNGoTfz/xJha9kvg0gut42Wi2EIBkM4bROi8A5JWr3SUS010YEylObs/3I9AthdN7m2yeA3LagiUB5CqUC1z1aEWXVpSs7hJyBpdABmGHNXI3IjsV7+BGlZdRwN+eJh/k0K15KAagMLFBfNkiiz1EtlLb+WvPshVwVQiSPJBaYPRRAekdEsImV3+ZEb7sekBcRb23LHG9a5B5Vm5g/1ALp/J0qXYKAmN8x/IA+HZas0bQPdhNj5pkMrzcE8rvfgggAclEBjeOBKxMF3NDtAWh0FFM6/lb+KM6GOjcrPcyj54o/XMmW0bgcVM21dHhF4XSEMqDdXvgJAVlbLHl42A6Pg8CDacamrnwG2tJgGotSBx4bWp0iTfSBxAjYHDwJh2LH5X8= elimellen@professionalpossum.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) to establish a connection to SOCKS proxy. If you run into any issues, please feel free to reach out in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel using the [support request workflow](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
