### ISSUE TITLE
Sponsor page needs additional discovery and content review (and possibly redesign)

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#48233]
### Are all questions required?
The form instructs users to answer as many questions as possible to help speed up the process, but doesn't offer deeper explanation as to why. Some questions appear to be sensitive and possibly trauma inducing. Specifically:
- Marital status
- Date and cause of death
- Race
- Sex

### Why is sex required?
The form requires the sex field to be filled out for "statistical purposes" without explaining what that means. Slight concern this may impact trust.

### Can this page be redesigned to reduce cognitive load and be more mobile-friendly?
Around 16 fields exist on this page. Filling this out on a mobile device may prove to be challenging (~50% of va.gov usage is on a mobile device). For those with cognitive disabilities (e.g. TBI, memory loss, etc); keeping track of all these questions at once may be overwhelming. Could we explore sub-tasks or a one thing per page approach?

![image](https://user-images.githubusercontent.com/14154792/195863787-52ddd489-5fa5-43ad-9b5a-52eaabcefbac.png)

<img width="638" alt="Screen Shot 2022-10-14 at 1 58 12 PM" src="https://user-images.githubusercontent.com/14154792/195911262-5ceb8f64-2977-43a7-b0cc-2caf594483dd.png">

## Changelog
- Content team reviewed this and noted that (a) it was too substantive and (b) should receive the attention of a product team to improve
- @jsokohl reviewed some questions and noted that [sex should not be required (and arguably removed)](https://dsva.slack.com/archives/C5AGLBNRK/p1664553378725789)

## Next steps
- [ ] Designer to conduct discovery research to answer open questions (and add any more as they emerge)

## Supporting artifacts
*Please provide supporting artifacts as available.*

1. [Production link to pre-need form](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/sponsor-information)
2. Start the form without signing in
3. Select "other" at the end of the first page
4. Review the sponsor page

## A11y notes

Depending on how this review goes and which questions are kept or deleted, we may need to conduct additional review on the typeahead dropdown and date of death fields.

**Comment by RLHecht** [comment]
@joshkimux These kinds of substantive questions are for a product team to answer. I'm not sure if there is one working on this right now but you could ask some other teams. Maybe benefits team 1?

**Comment by joshkimux** [comment]
@RLHecht thank you for the quick reply Randi! Agree these are heavy and need proper discovery. Will update this ticket and unassign you! 🙏

**Comment by AlexanderSherrow** [comment]
@joshkimux @jsokohl can we confirm or deny that the research in this pr is still ongoing or if the changes suggested are needed or rejected?

**Comment by joshkimux** [comment]
@AlexanderSherrow from what I'm aware, no research has yet been kicked off yet 🙇

**Comment by MichelleDieudonne** [comment]
Memorials Self-Service Jira Work Item: https://jira.devops.va.gov/browse/MBMS-42222

**Comment by MichelleDieudonne** [comment]
This work has been completed through our page redesigns in the FY24Q2 and FY24Q3 PIs.
