### ISSUE TITLE
Staging Review [Design System Team - OMB info component]

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#48242]
The Design System Team would like staging review for the OMB info web component.

OMB info
design.va.gov: https://design.va.gov/components/omb-info
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-omb-info--default

**Comment by allison0034** [comment]
No design feedback, thank you : )

**Comment by CherylEvans** [comment]
No content feedback.  Thank you!

**Comment by sterkenburgsara** [comment]
No IA feedback either. Thanks!

**Comment by it-harrison** [comment]
No QA feedback. Looks good!

**Comment by allison0034** [comment]
[Zoom recording](https://oddball-io.zoom.us/rec/share/OikhWfexwRm7Kljle4f3nBLCagHIEsf3R38Qc1kRK5b1F_6Izl_j9W0uxbBfZK9q.eu0sSbUeHPLWdrWk)
Passcode: 2+XfEHDQ
