### ISSUE TITLE
End date shouldn't be visible when Veteran is currently enlisted 

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#48244]
#### VFS team name
Benefits 1

#### VFS product name
Certificate of Eligibility

#### Point of Contact/Reviewers
Ian Harrison (QA)

---

### Platform Issue
Content includes an error message or validation error to indicate an error or empty state. (05.09.01))

### Issue Details
There is a possible discrepancy between steps 4 and 5 of the [Steps to Reproduce](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Certificate%20of%20Eligibility%20Test%20User%20Information.md) that doesn't get flagged: in step 4 a veteran clicks "I'm an active-duty service member" but does not have an unpaired "Service Start Date" in step 5. This is not a big deal, but I thought you might want to consider it.

### Link, screenshot or steps to recreate
Either create a new COE or modify an existing COE.

### VA.gov Experience Standard

[Category 05, Issue 09](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards)

### Other References
[WCAG SC 3.3.1 A](https://www.w3.org/WAI/WCAG21/quickref/#error-identification)

### Platform Recommendation
Consider showing an error message if active duty veteran does not list an unpaired service date.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

## Platform directions
- Update "Issue Title"
- Link to  Collaboration Cycle Request epic
- Add the VFS team and product name
- Add your name and practice area under Point of Contact(Practice Area)
- Add the Platform Issue. The Issue column from the [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
- Add the Issue Details and any links, screenshots or steps to recreate
- Add the [VA.gov Experience Standard](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html) number
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by sortizsh** [comment]
Not a launch blocker, nice to have

**Comment by tblackwe** [comment]
@DLarson-Oddball Can you please take a look at this issue, determine if it is still relevant, and if so, size the effort to resolve?

**Comment by DLarson-Oddball** [comment]
After discussing with the team, we are going to close this issue as there is a valid use case where a veteran may have previous periods of service (which would require an end date) in addition to their current period of service. Please advise @it-harrison if you feel there is more we should consider.

<img width="1080" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/133443504/76f77366-5c51-4c74-a2da-6759d17aeff3">
