### ISSUE TITLE
Fetch data from GH APIs

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4826]
As a developer, I would like to query github api's against one or many repositories.

- [ ] Able to fetch data from githubs api's.

**Comment by Clark-W-Griswold** [comment]
During our research, we came across this repository. It however doesn't give us the data we need to answer the greater questions being asked. 
https://github.com/infinityworks/github-exporter

Serves as an example of code though that connects to github and exports to prometheus.
