### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#48262]
### Data Type Requested

Support

### Date Range Start

01/01/2022

### Date Range End

10/14/2022

### Product Name(s)

VA Forms

### Product Description

We are analyzing and digitizing VA Forms and would like to see which forms are the most problematic for Veterans.  Search term Form. Not sure just pulling find-forms is too generic.

### Product URL(s)

https://www.va.gov/find-forms/

### VA Email Address(es)

tricia.baker@oddball.io

**Comment by ianMcCullough-ob** [comment]
Hey @tbaker1026 

I wrapped up the exports. I have 3 of them:
1) I searched for the term "form" to see what users were saying about forms
2) One for just the url va.gov/find-forms
3) One that has all the about form pages (about-form-20-572, about-form-10-2850c, etc)

Unfortunately I can only share these files with VA email addresses. Some of these responses contain PII (email, phone numbers, etc) and that information can only be shared on the VA network. Do you have a VA email addresses? If not, does someone on your team?

**Comment by tbaker1026** [comment]
Is it possible to remove the PII data?

**Comment by ianMcCullough-ob** [comment]
Closing this to pursue an alternate solution using DOMO.
