### ISSUE TITLE
Update to Static Pages from GovCIO

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#48280]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
  
I am currently working a ticket to remove the online portion of Form 22-1990n. There are two pages that link to the online form that I need to remove. 

 https://www.va.gov/find-forms/about-form-22-1990n/ in this page I need to remove the "Online Tool" section

https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/ in this page I need two updates. The first is to replace the link text of "Apply online now" in the "How do I get these benefits?" section with the following text "Download VA Form 22-1990n (PDF)". The URI for this link needs to be "http://www.vba.va.gov/pubs/forms/VBA-22-1990n-ARE.pdf".

The second update is to remove the "Get more information" section altogether. Currently the link within this section is broken and the Product Owner has asked to remove the entire section from the page.

Redirect of URL - as far as I am aware, this is the only URL for the actual online Form 22-1990n
URL -  https://www.va.gov/education/apply-for-education-benefits/application/1990N/introduction
Not sure exactly how this is handled when an online form is being removed, but would like the above URL to be redirect to 
https://www.va.gov/find-forms/about-form-22-1990n/  since the PDF version will remain available for download.

Search Bar best bets - looking for assistance in removing "https://www.va.gov/find-forms/about-form-22-1990n/" from returning in a search for form 22-1990n National Call to Service program

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
19 Oct 2022 | already in production, just need an update made to the two pages
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: none
- Link to or attach user flows: none
- Link to prototype or mockups: none
- Link to any epics/issues that may be helpful: none

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: 19 Oct 2022
- Estimated staging review date: 20 Oct 2022
- Content and IA work needed by: 19 Oct 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Cinda Quattrini
-	Product manager: Kara Ciprich
-	Designer: 
-	FE engineer: Jarred Simon
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@jsimonVA Question about the PDF link we want to put onto the National Call to Service page. As a general rule, when we have form PDFs, we usually direct the user to the find form page for that specific form instead of directly to the PDF with this type of content: Get VA Form XX-XXXX to download. Is there a reason we can't do this here and would need to link directly to the PDF?

**Comment by jsimonVA** [comment]
No reason at all. If there is a general rule then lets follow it. The thought process was to have the user able to download the form without any extra steps. I wasn't aware of a standard way of handling this so lets just do as you mentioned.

**Comment by RLHecht** [comment]
@jsimonVA Just want to clarify: Is our team removing the online tool section from the find forms page or is Public Websites? I want to add it to our ticket if it's us. Thanks!

**Comment by jsimonVA** [comment]
@RLHecht from what I understand, your team is removing it.

**Comment by jsimonVA** [comment]
@RLHecht The intent was to have this completed prior to next Tuesday (25 Oct 2022). However, I have let them know that I just made the request to have the content changed on the static sites and the URL redirected which will take up to two weeks. 

So no, the changes do not have to be done this week. Next week would be perfect. Would you like me to send them your question(s) or will you reach out to the directly?

**Comment by RLHecht** [comment]
@jsimonVA That's great to hear about timing. We can email with the stakeholder. Is Cinda who you've been working with or is it someone else?

**Comment by jsimonVA** [comment]
@RLHecht Cinda is the main person, I am not sure if Michael Napper would have any input on this as well but probably include him.

**Comment by RLHecht** [comment]
@jsimonVA The online tool link is now gone from the find forms page and the National Call to Service program page. Let me know if this ticket is now good to close. Thanks!

**Comment by jsimonVA** [comment]
@RLHecht looks good to me. We are good to close this. I will close the issue
