### ISSUE TITLE
Add RSVP links to Platform Office Hours Page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#48284]
Acceptance criteria:

- [x] The Platform Team Office Hours page will include links to each of the teams' RSVP Calendly links: https://vfs.atlassian.net/wiki/spaces/AP/pages/2407464993/Platform+Team+Office+Hours

The Calendly RSVP links can be found here: https://depo-platform-documentation.scrollhelp.site/support/office-hours

The new Calendly RSVP link for the Platform Content team is this: https://calendly.com/platform-office-hours/platform-content-office-hours?month=2022-10

**Comment by taylojill** [comment]
10/18/22 - I did not see calendar links to CMS - Accelerated Publishing or Platform Crew. All other links added to page.

**Comment by laucon** [comment]
I added our new calendly link to [this page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2407464993/Platform+Team+Office+Hours). I'm not sure if there was anything else I needed to do here.
