### ISSUE TITLE
[COGNITION]: Heading nesting level should increase by one

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#483]
## Issue
The heading levels are jumping from an H1 to H5 on the Find Locations landing page, and improperly nesting H4s inside H2s on the Facility Detail pages. These were flagged as SC 1.3.1 issues. Screenshots attached below.

## Audit Finding
* Note 1, Defect 1

## Acceptance Criteria
* As an assistive device user, I want to hear the headings announced in proper nesting order, with no heading levels skipped for our content.
* As a user with a level of visual acuity, I do not want to see any visual changes in the application

## Environment
* MacOS Mojave
* Chrome latest
* https://staging.va.gov/find-locations
* https://staging.va.gov/find-locations/facility/vha_674GD

## Possible Fixes (optional)
Check out the [Design System font-size utility](https://design.va.gov/utilities/font-size) for using the right semantic heading levels and styling them to match current visuals.

## WCAG or Vendor Guidance (optional)
* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs
![Screen Shot 2019-07-03 at 5.14.49 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/3c508789-ec2b-4399-ab07-dc3c8ac7a360)

---
![Screen Shot 2019-07-03 at 5.15.29 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/b490105b-9032-4a6f-b5ca-4ef78f70ba0b)

**Comment by Karak888** [comment]
will take on in this sprint 5.

**Comment by 1Copenut** [comment]
Confirmed this item has been remediated. Used the axe scanner to verify H2's were showing up as expected. Moving to close.
