### ISSUE TITLE
Need Athena access for RDS

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#48304]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@github-name
mviterna (Mark.Viterna)
kristen-brown (Kristen.Brown)
michelpmcdonald (Michel.McDonald)
cilestin (Drew.Fisher)
Alex.Wilson

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Team Dash and Caracal need access to read tables on RDS that are used by the vets-api Rails application. This is for running reports and production support. We already have access to S3, just need Athena 

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 
Production support
## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_
arn:aws-us-gov:iam::008577686731:user/Mark.Viterna is not authorized to perform: glue:GetDatabases on resource: arn:aws-us-gov:glue:us-gov-west-1:008577686731:catalog because no identity-based policy allows the glue:GetDatabases action

Remove above error and grant access
---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mviterna** [comment]
@mydesignrocks Hi there, we were wondering if this was going to be possible? We are trying to find good ways to avoid using the Rails Console, and a read-only Athena query might meet that need for us. Otherwise, we would need to build a custom internal only API support tool

**Comment by kristen-brown** [comment]
Spoke to @oseasmoran73 via [a Platform Support Request](https://dsva.slack.com/archives/CBU0KDSB1/p1670871212590319), and he suggested that we continue to use the Rails console and ActiveRecord for querying the database, as this is the preferred method from DevOps.
