### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#48305]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: 
mviterna (Mark.Viterna)
kristen-brown (Kristen.Brown)
michelpmcdonald (Michel.McDonald)
cilestin (Drew.Fisher)
Alex.Wilson
- Reason access is required:
Production support for Benefits teams Dash and Caracal

**Comment by mviterna** [comment]
I already have access, so you can disregard mine

**Comment by mviterna** [comment]
but they all need similar to what I have

**Comment by ericboehs** [comment]
Everyone already had access except @Alex.Wilson which is not a GitHub member.
