### ISSUE TITLE
508-defect-1 ❗ Contact information isn't announced to screen reader users

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#48300]
## Point of contact

Josh Kim

## Severity level

1, Launchblocker. Critical. Must be fixed before launch.

## Details

Screen reader users in forms mode (e.g. using the tab key as they anticipate only form fields, not static text fields) will likely miss the note describing how the VA will contact them on the _applicant address_ page.

<img width="502" alt="Screen Shot 2022-10-17 at 11 56 40 AM" src="https://user-images.githubusercontent.com/14154792/196225407-7f360599-580f-4bc2-92b9-b2dce191d5df.png">

## Breaking down the issue

If we were to annotate and break this page, we'll notice that:
- The applicant address is a fieldset which is arguably the first part of the page
- The email and phone number are arguably the second part of page
- The note's first paragraph describes the phone number and the note's second paragraph describes the email address

![screencapture-va-gov-burials-and-memorials-pre-need-form-10007-apply-for-eligibility-applicant-contact-information-2022-10-17-11_55_40](https://user-images.githubusercontent.com/14154792/196227862-5a8b39d5-5e12-48cd-86c5-6e5cee7fac68.png)

## Reproduction steps

1. [Begin the pre need flow unsigned in](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information)
2. Select "other" for relationship to service member
3. Reach step 6 of 7: contact information

### As a separate page
Given the content within the note, this could arguably be its own page specific to the applicant's phone and email (both of which are unrelated to the address itself).
<img width="553" alt="Screen Shot 2022-10-17 at 12 20 48 PM" src="https://user-images.githubusercontent.com/14154792/196230374-1be68cc5-5789-4c97-8491-cea4dbdb3f95.png">

### Using hint text
We could also cut up the note and use hint text to embed them within the input fields themselves.

<img width="489" alt="Screen Shot 2022-10-17 at 12 18 23 PM" src="https://user-images.githubusercontent.com/14154792/196229891-21ccf584-fef6-4f26-b3e4-76846a4319ee.png">

### [BANDAID] Using `aria-describedby`
If we need a bandaid that does not change the actual design, we may also use `aria-describedby` to programmatically link the first paragraph to the phone input field and the second paragraph to the email input field.

## Type of issue

- [X] Screenreader
- [ ] Keyboard
- [ ] Focus
- [ ] Headings
- [ ] Color
- [ ] Zoom
- [ ] Semantics
- [ ] Axe-core
- [ ] Something else

**Comment by joshkimux** [comment]
@jaredcunha couple of thoughts to those awesome thoughts:

- Are these required fields... actually optional by any chance? Do we know if these are actually required? Because the  written "why" for needing them doesn't sound very compelling.
- No reason why we can't make use of the `va-additional-info` component, that's a great idea! ✨

**Comment by sonntag-adam** [comment]
@joshkimux fix has been pushed to staging.

**Comment by joshkimux** [comment]
@coforma-terry and CAIA team to review 🥳 @sonntag-adam for future validation, please tag Terry ❤️

**Comment by MichelleDieudonne** [comment]
@coforma-terry I see that this is still open.  Has this been reviewed for closure?  Our team is done with it.  Thank you!

**Comment by MichelleDieudonne** [comment]
Jira work item https://vajira.max.gov/browse/MBMS-37652

**Comment by SarahKay8** [comment]
Can confirm that "Applicant's Mailing Address" has been changed into a `legend` in order to caption the `fieldset` Also validated `va-additional-info` component is being used instead of note. Tested with VO + Safari and JAWS. @coforma-terry  @sonntag-adam Closing this out!

https://github.com/department-of-veterans-affairs/va.gov-team/assets/102324990/2353b505-b826-4ec7-bcd9-3652bd2d318a


![F9053E81-7A30-41C0-96EB-8C75BD3DB36A_1_105_c](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102324990/015a94a4-48f1-41c0-bc0c-0bec92c4f81d)

**Comment by MichelleDieudonne** [comment]
Jira work item link: https://vajira.max.gov/browse/MBMS-37652
