### ISSUE TITLE
VAOS Staging: V2 User not able to choose both AM and PM on a preferred date for CC request 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#48313]
We have noticed that when the user selects AM and PM on a particular preferred date the system is throwing a 400 error and the request is not making its way through to HSRM. We have tested this scenario during VAR Res 4.32.10 regression and passed testing. 

**Validation steps before reporting: **

- This issue is inly happing with CC requests only. VA flow is working as expected
- Only happens with V2 test users 
- Tested with multiple V2 test users and seeing the same results across the board 
- After testing with VAOS test harness the request was transferred over to HSRM when we selected AM and PM selected on a preferred date. This is how we determined this issue is related to FE.
- Tested with multiple type of care and seeing the same results 

## Steps to Reproduce
- Login to VAOS as any V2 test user (grethel.g.petryniec@id.me)
- User is brought to VAOS home screen 
- Click on "Start Scheduling"
- Select any Type of care (ex: - Podiatry)
- On "Choose an appointment day and time" page select AM and PM on a preferred date (Ex; - 11/ 30 AM and PM)
- Navigate through the steps and fill in the required fields
- On "Review your appointment details" page validate the information is displayed correctly 
- Click on "Request Appointment" button 

## Expected behavior
System should create a new CC request and it should be transferred over to HSRM as per the flow 
## Actual behavior
System is throwing a 400 error and request is not being created in VAOS 
Request URL - https://staging-api.va.gov/vaos/v2/appointments
Response: {"errors":[{"title":"Bad Request","detail":"requestedPeriods.period: start and end must occur on the same day","code":"VAOS_400","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1013120820V528557/appointments","vamfBody":"{\"message\":\"requestedPeriods.period: start and end must occur on the same day\"}","vamfStatus":400},"status":"400"}]}:

![image](https://user-images.githubusercontent.com/69315717/196261315-94ca8b3d-4b21-4e7d-a8e2-8aa6fa3a5250.png)

**Comment by aarathi-poldass** [comment]
@ldelacosta Can you please assign this ticket to the developer for further analysis. Please note this is marked as high priority and needs to be addressed before Go-Live date. Thank you!

**Comment by ldelacosta** [comment]
Hello @aarathi-poldass

This is not a defect. I was able to submit a CC request for Grethel. Please check with us to see if a user ID has all the V2 feature toggles turned on. The user grethel.g.petryniec@id.me was not set up for the` mobile_appointment_use_VAOS_v2`
toggle. Please re-test to see if you can submit it. Thanks! 

![Screen Shot 2022-10-17 at 4.43.58 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/e359490b-248c-4052-8979-2d5d02d8aeb3)

**Comment by ldelacosta** [comment]
Reviewing the ticket details.

**Comment by ldelacosta** [comment]
Need to determine if this is a BE services issue. There is a [thread in the PPG slack](https://vappgteam.slack.com/archives/C023EFZPX4K/p1666051798611209). Waiting to hear back from Thomas. 

cc: @aarathi-poldass

**Comment by marcynadeau** [comment]
per Slack this might be related to this JIRA ticket:  VAOS: Improve create appointment validations. https://issues.mobilehealth.va.gov/browse/VAOSR-3901

**Comment by ldelacosta** [comment]
Per Brad's update in the slack thread: 
> We will look at correcting this with `VAOSR-4598.` Jonathan Williams- I recommend we pull this bug into the current sprint.

**Comment by aarathi-poldass** [comment]
This issue was addressed after pushing VAOS-Service 1.23.1 to staging environment. I was able to create a CC request by choosing both AM and PM on a preferred date and request is making it's way through to HSRM. Attached below is a screenshot for reference.
![image](https://user-images.githubusercontent.com/69315717/197120878-be8ca111-d9ae-4698-8515-b36eed0543bb.png)

**Comment by ldelacosta** [comment]
Thanks! Whenever you have a chance, please close out the ticket @aarathi-poldass
