### ISSUE TITLE
Profile Team | "One Thing Per Page" | Research Recommendations

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48326]
## Description

Based on the final report from the recent research sessions around the concept of "one thing per page" (see ticket #47381), several areas within the Profile were identified as areas we could improve upon and create a better experience for our users.

Full research report is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/findings-summary.md).

These included:

1. Managing notification settings (including the nomenclature and setting up mobile number)
     a. Update naming for notification and group name (#48396)
     b. Discovery for flow when adding a mobile number from settings page to contact page and back (#48410)
2. Re-visiting the address validation flow (incl overrides, alerts) (#48537)
3. Consistency and simplification of button pairs ("save" vs "update") (#48441)

The data that would be helpful to have included:

1. Report showing # of users clicking the link from the Notification settings page to the Contact info page (to add a mobile number) and how many then click the link on the Contact page to return to the Notification page (#48437)
2. Track # of users who add/update their mailing or home address and how many errors they get upon submission (ticket #48147)
3. Count of modal "currently editing another section" while on Contact info page (#48439)

**Comment by andaleliz** [comment]
Here's the analytics event that I see in the console when the "currently editing modal is triggered". These should line up with the Behavior > Event reports in analytics

Running command: ga("gtm253.send", {hitType: "event", 
**eventCategory**: "Interactions", 
**eventAction**: "Modal - Click - warning - You’re currently editing your preferred name - (not set) - (not set) - Edit", 
**eventLabel**: "int-modal-show"})
