### ISSUE TITLE
Design Intent - Accessibility Feedback - 10-10EZ Household Information Optimization

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#48324]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Overall I think this is looking good! I'm looking forward to seeing what 

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
- In the meeting there was some discussion about one-thing-per-page and the conditional display of certain fields. As much as possible, avoid conditional display of fields. In situations where breaking questions out into follow-up pages feels onerous, see if there are ways to re-word or re-order questions to make them more natural together without having conditional display. If there's no better way of presenting the information and conditional display tests better with users, that's fine -- but be sure to keep it as simple as possible. I'd recommend working with the Shared Support accessibility specialists on this.

**Consider:**
- When using the Additional Info component, make sure it makes sense to hide information in the first place. In particular, I'm thinking about the [Veteran annual income](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/5LaJRx/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas?posX=-21698.978515625&posY=-3367.021484375&zoom=0.5) questions. Inputs at that step have a label and some pretty lengthy helper text, and then some extra definitions hidden inside the Additional Info component. Since there's already a lot of helper text on screen, it's not clear to me that you gain a lot by hiding information for these questions. The pattern is accessible, but every time we add an extra click or other user interaction (especially for assistive technology users), it's worth verifying that it's an extra interaction that provides value.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by nicko-amida** [comment]
@briandeconinck 
[Updated household information designs](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)

**Should**
- The conditional fields that used to appear dynamically on pages have been moved to their own pages. Now there is no longer a need to create a custom screen-reader event for dynamically added fields.

**Consider**
- The additional info components on the [annual income page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/L0yqdk5) have been removed, and the definitions incorporated into the sub-labels.
