### ISSUE TITLE
AWS access for Igor Yegorov

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#48320]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Igor Yegorov

### Your Email

Igor.Yegorov@adhocteam.us

### Team, Role, and Company of the target individual

VSP DevOps Community of Practice, Senior Software Engineer, AdHoc LLC

### Product Manager (PM) name and email

Lainey.Trahan@adhocteam.us

### Product Owner (PO) name and email

Michael.Chelen@va.gov

### Desired AWS Access

Need the vsp-operations role to do my work as a DevOps resource.

### Access Expiration

Never

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
VOR Confirmed, approved

**Comment by rmtolmach** [comment]
@laineymajor, Can you add Igor to the Platform Roster? https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
