### ISSUE TITLE
Create instance of Grafana for PR timing dashboard

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4833]
As a developer, I would like an instance of grafana so that I can visualize data from Prometheus.

AC: 
- [ ] Instance of graphana setup with our instance of Prometheus as our data source.

**Comment by Clark-W-Griswold** [comment]
Existing instances of prom/grafana will be used. The instance to be used in this case is the "Utilities" instance.
