### ISSUE TITLE
Login Button Standardization

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48357]
## Issue Description
This PR creates a button component that standardizes the process of toggling the LoginModal. When clicked, the button should toggle the LoginModal open and correctly append SiS attributes.

## Tasks
- [ ] Update logic around toggleLoginModal to properly append SiS. 

## Acceptance Criteria
- [ ] When a user toggles open the login modal their url should update with the appropriate search params.

**Comment by alyssagallion** [comment]
Button is good to go, testing.

**Comment by acaruso-oddball** [comment]
Tests are finish just working through errors.
