### ISSUE TITLE
[task] Request from VA Notify | Fix staging view of the 40-10007

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48369]
## Value Statement
**_As a_** product manager
**_I want to_** fix the staging view of the form
**_So that_** I can complete testing in staging. 

---
## Background Context
From Megan Siddle: My team had a few questions about the 40-10007 form as we are working through creating the email confirmation:

- Any update on if/when this form submission might get fixed in Staging?
- How do you get two applicants on the one form (the mockup of the confirmation page showed two applicants so we thought that was an option)?
- If there are two applicants, are there two different confirmation ids or just one that is shared?
- If there are two applicants, are there two different email addresses that would receive confirmation emails?

## Tasks
- [x] Follow up with EOAS and provide any info needed for them to implement a fix

**Comment by saderagsdale** [comment]
@megansiddle @Mottie hey both! I added this to our backlog as a staging task. Megan - let me know if there's any other helpful context that should be here! Robin - the VA Notify team needs us to make some quick fixes to the staging setup so they can complete some testing on their end.

**Comment by megansiddle** [comment]
@saderagsdale just checking in on the status of this ticket. :)

**Comment by saderagsdale** [comment]
@megansiddle Hey Megan! I've asked @Mottie to assign this to a team member to fix the issue for ya.

**Comment by Mottie** [comment]
cc: @sortizsh

**Comment by saderagsdale** [comment]
@jacobworrell this is a pre-need related item.

**Comment by jerekshoe** [comment]
@megansiddle I'd be interested to see the mockups that you referred to in the original description, but looking at the code, only one person can be listed on the confirmation page. I think that answers the last 3 questions. As far as if/when the form submission will work in the staging environment, I can ask around and see if I can get info. EOAS is working on a new version of the backend service we make the form submission to, so the issues are probably tied to that

**Comment by megansiddle** [comment]
Thank you @jerekshoe! I had pulled it from [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/design/pre-need-mockups.sketch) 
<img width="110" alt="image" src="https://user-images.githubusercontent.com/99678581/200883712-39125f19-83c4-4c42-826a-2b3065afb356.png">
But sounds like its probably outdated. I was wondering though if the confirmation page not displaying in Staging is also causing the successful submission trigger to not happen too? Meaning could the error just be on the page display and not the form submission (that way we could still run trigger tests for the email confirmation in Staging).

**Comment by jerekshoe** [comment]
Posting this for my own benefit: #44754 is related to this ticket

**Comment by jerekshoe** [comment]
@megansiddle I did find a workaround to create a successful submission. I believe that there is an issue with the form submission when there are supporting documents uploaded during the form process. If you go through the form without uploading any documents on this page: https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/supporting-documents, then the submission _should_ be successful. I am discussing this issue with EOAS and we should be able to find a resolution that won't require the above workaround.

**Comment by jerekshoe** [comment]
@megansiddle Also, as far as your above question: If the submission is not successful, the successful submission trigger should not execute. Let me know if the above workaround works for you and feel free to reach out if any more questions come up

**Comment by jerekshoe** [comment]
I've been in communication with EOAS and I believe that we have found a resolution to this issue. Let me know if you see any further issues in staging, but I am going to go ahead and close this for now

**Comment by megansiddle** [comment]
Hello @jerekshoe we are seeing an error again in staging. This is occurring even when we aren't uploading supporting documents.
<img width="424" alt="image" src="https://user-images.githubusercontent.com/99678581/205705837-2908341a-9300-42b6-856d-1c9876a36e13.png">
CC: @Jake-Uhteg

**Comment by jerekshoe** [comment]
> Hello @jerekshoe we are seeing an error again in staging. This is occurring even when we aren't uploading supporting documents. <img alt="image" width="424" src="https://user-images.githubusercontent.com/99678581/205705837-2908341a-9300-42b6-856d-1c9876a36e13.png"> CC: @Jake-Uhteg

@megansiddle I reached out to my contact at EOAS to see if they could look into it and get this resolved. I will keep you updated as I find out more

**Comment by jacobworrell** [comment]
Still awaiting response from EOAS.
