### ISSUE TITLE
[FE] | 10-10CG | Update MaxLength values in Schema to match Salesforce values

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#48366]
## Description
It was recently discovered that we have multiple fields in the Caregiver application whose max character length value in the current schema is greater than the max number of characters that the Salesforce system can accept downstream. An audit has been completed and a list of max values has been provided by Salesforce. We need to update the schema to match our max values with those from Salesforce.

## Acceptance Criteria
- [ ] Schema maxLength values match those provided by Salesforce for the specified fields

**Comment by longmd** [comment]
This is the [link to the provided fields and character limits](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/10-10CG%20SalesForce%20field%20character%20limits.md)

**Comment by longmd** [comment]
@lihanli , this schema change has been completed and approved for update in `vets-website`. Do you want to do a PR to update in `vets-api`?

**Comment by lihanli** [comment]
@longmd sure, i will do it later

**Comment by longmd** [comment]
@hdjustice , the character length updates are in staging. I have verified the lengths and successfully submitted a form with that updated schema.

**Comment by hdjustice** [comment]
awesome! Thanks @longmd

**Comment by hdjustice** [comment]
Hey @longmd  - can you let me know which fields were updated?  
I know we kept some at their current limits that were lower than the CARMA limits, so I want to document and test which ones we did update.
Thanks!

**Comment by longmd** [comment]
@hdjustice , the following fields were updated: 

- Middle name - Added maxLength of 40
- Phone number - Added maxLength of 40
- Email address - Lowered maxLength from 256 to 80
- City - Lowered maxLength from 51 to 40

**Comment by hdjustice** [comment]
Confirmed the above-listed fields were updated and no submission issues encountered.
