### ISSUE TITLE
BE | Profile | Documentation | Account Security 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48365]
## Background

Create a document that provides an overview of the back-end services and systems that support the account security page in Profile.

## Tasks
- [x] Add documentation for account security

## Acceptance Criteria
- [x] Update Github file
- [x] Notify PM

**Comment by tpharrison** [comment]
Reference - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/README.md#backend

**Comment by tpharrison** [comment]
The [backend section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/README.md#backend) of the Account Security Product Outline document has been updated to link to the [new backend documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/account_security/backend_documentation.md).

**Comment by SKasimow** [comment]
Awesome!
