### ISSUE TITLE
Midpoint Review - IA Feedback - Sitewide Homepage, VA.gov homepage redesign

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#48361]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- User research is really insightful and I found it fascinating to read.
- What will be driving the list "Popular on VA.gov" - will this change over time based on analytics, or more or less stay the same? 
- I am curious about the two distinct tasks sharing the hero/promo space - the Pact Act advertisement & Create Account button. I think the gradient background contributes to some possible visual confusion here - maybe worth testing with users.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**
- There's a deliberate prominence on search here, which we assume will lead to more people using it. There was one example in your research ("benifits" being spelled wrong and leading to low results). I imagine we'll see a lot more of this. How confident are we in things like: case sensitivity, autocomplete suggestions, robust fuzzy matching capabilities with our search index? 
- What do we know about veteran users & [keyword foraging](https://www.nngroup.com/articles/keyword-foraging/)?
- Provide guidance to future stakeholders who want to use the "VA news" space that content they feature should link back to VA.gov.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by mmiddaugh** [comment]
Thank you for your input @sterkenburgsara. I'll do my best to respond to your feedback here 

What will be driving the list "Popular on VA.gov" - will this change over time based on analytics, or more or less stay the same?
> It's intended to change over time. We're in the process of developing the rubric for this list. It includes analytics as well as  considerations such as relevance to a broad audience of Veterans and other beneficiaries, how difficult the task/tool is to discover by browsing or searching, indications that the topic/tool is in demand and long term relevance. 

Possibility of the gradient background contributing to some possible visual confusion here - maybe worth testing with users.
> Noted. (So far nothing has come up during usability testing.)

How confident are we in things like: case sensitivity, autocomplete suggestions, robust fuzzy matching capabilities with our search index? What do we know about veteran users & [keyword foraging](https://www.nngroup.com/articles/keyword-foraging/)?
> We're using the same search engine as appears in the header. I routinely monitor searches initiated from the homepage, looking for trends in search terms and abandonment rates. 

Provide guidance to future stakeholders who want to use the "VA news" space that content they feature should link back to VA.gov
> This stakeholder will generally link to [VA News and Information](https://news.va.gov/) but we're developing a content governance rubric for this space.

**Comment by mmiddaugh** [comment]
@davidconlon any additional thoughts?

**Comment by sterkenburgsara** [comment]
@mmiddaugh Of course! I am new to the team, so please forgive my lack of context for some things. The rubric around "Popular on Va.gov links" sounds great. I don't have any follow-on questions. Good luck!
