### ISSUE TITLE
Address Validation Error State not resetting

### ISSUE THREAD

**Issue by bradl3yC** [department-of-veterans-affairs/va.gov-team#4837]
Currently the error state is not being reset if there is a successful api request that follows immediately

Steps to reproduce:

1. Try to save a bad address that would return a non-200 response
2. Click Edit Address
3. Type a good address and try to save
4. Notice the modal still shows with the edit address button text

**Comment by Samara-Strauss** [comment]
So just went to test this. Good news is the buttons are now behaving as expected. The bad news is that I get this message when I click "Use suggested address":

<img width="605" alt="Screen Shot 2020-01-15 at 10 48 42 AM" src="https://user-images.githubusercontent.com/34068740/72450389-47ecc280-3788-11ea-84da-7344d14fdf46.png">

How this happened:

1. Entered this address and clicked "Update": 1510 Irving, Washington, DC 20010
2. From the address validation form, clicked "Edit address."
3. Entered this address and clicked "Update": 1510 Park St, Washington, DC 12345
4. From the address validation form, clicked "Edit address."
5. Entered this address again and clicked "Update": 1510 Irving, Washington, DC 20010
6. From here clicked "Use suggested address". The form closed, appeared to save, and then generated the error above.

**Comment by bradl3yC** [comment]
```{"data":{"id":"","type":"async_transaction_vet360_address_transactions","attributes":{"transactionId":"a50177bd-8d2a-4ab9-ab47-890df9bf4b4c","transactionStatus":"COMPLETED_FAILURE","type":"AsyncTransaction::Vet360::AddressTransaction","metadata":[{"code":"ADDR312","key":"addressBio.failAddressOverrideCriteria","retryable":null,"severity":"ERROR","text":"The address override criteria has not been met, please attempt validation again"}]}}}```

Error being returned by vet profile API

**Comment by Samara-Strauss** [comment]
This issue appears to be resolved! I was able to successfully save two addresses on staging. Closing!
