### ISSUE TITLE
[FE] Fix Skipped Test

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48376]
## Tasks
- Determine if test is necessary
- Delete if no or fix it yes
src/applications/check-in/pre-check-in/tests/e2e/validation-attempts/validation.attempts.reset.cypress.spec.js

**Comment by brianseek** [comment]
Deleted this test since we are no longer managing validation attempts in the frontend. Also created this ticket to clean up flag and logic https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/48879

cc @loripusey

**Comment by brianseek** [comment]
Closing since there is nothing to validate here
