### ISSUE TITLE
Revoke All Endpoint (requires research)

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#48398]
- review doc for notes: https://docs.google.com/document/d/1WrEql7TQokx9l5VGPQQui-x1NpilCMgIKAMqt8LhtvE/edit

**Next steps:**
- Research oauth logout compliance requirement
- Start with research based on “where would you expect to find this” without showing them anything to start with
  - After this show some ideas of where we think we want to place it
- Generate some low fidelity and mobile mockups of revoke all ideas
  - Name drop down
  - Account security option
  - Modal of confirm you want to logout all sessions
  - Show users where they are logged into
  - Session timeout modal*

**Comment by asg5704** [comment]
This needs research from UX and will need to go through the Collab Cycle.

Essentially, we want to add a place where users can revoke access to all signed-in devices.
- Where do users expect to be able to view this? (Information Architecture)
- What do they think will happen when they click the button? (Content)

**Comment by kingbmike** [comment]
@asg5704 @claytonzook Can this ticket be closed given the newer Manage Devices work that has been done?  If so, I will close, if not I will move to different epic as 'tech debt' epic for SiS is going away.

**Comment by claytonzook** [comment]
@kingbmike All the UX research/design components were completed on this. My feeling is this ticket can close.
