### ISSUE TITLE
Provide Veterans with ability to edit  benefit information for their FSR Submission

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48409]
## Issue Description
As a Veteran completes an online FSR they are presented with Benefit information. We have heard on a few occasions that this information can be incorrect and the business would like to providing Veterans with a way to edit the benefit information that is presented to them.  The edited information should override what is submitted on the form for that submission. 

![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/e7b8bb55-36a6-4e14-80e9-32237724ca2a)
---
## Tasks
- [x] mock up designs for editing capabilities

## Acceptance Criteria
- [x] design has been reviewed by Platform
---

**Comment by mgleo** [comment]
Met with Platform 11/1/22 with mockups, making updates based on feedback.
