### ISSUE TITLE
DSVA channel #platform-release-tools

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#48416]
**PROBLEM STATEMENT**
As a VFS engineer, I have questions/comments/concerns that do not necessarily qualify as support, but need an appropriate _channel_ to communicate with engineers who are knowledgeable about platform FE product areas.

Before the reorg, VFS engineers (and OCTODE) used the DSVA #platform-release-tools channel to communicate information that isn't appropriate for support bot. With the reorg, what is the expectation of this channel (who monitors the channel, etc)?

**Comment by rmessina1010** [comment]
@laineymajor 
Is our intent to create a new channel with the function of the old RTT, or to close out the  unmaintained RTT channel?

**Comment by littlelingo** [comment]
@laineymajor @rmessina1010 The expectation is engineers would use the CoP channels for items that are not classified as support. This is how both DevOps and BE are setup as well.

What should occur is the FE CoP puts a plan in place to Archive the RTT channel and to communicate the existence of the FE CoP channel... Additionally, re-iterate using the support channel for those types of requests.

**Comment by jhonnyoddball** [comment]
The CoP channel is being used instead
