### ISSUE TITLE
[cFSR] Checkbox to input boxes Enhancements - Housing Expenses

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48440]
## Issue Description
Add "Checklist to box" functionality in FSR for the following pages. Confirm expenses explainer is up to date

- [Housing expenses](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022052/specification/sitemap?mode=i)

Example of functionality 
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/2322a621-233e-43e2-934a-d938d19590cd)
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/cfeed84f-5e25-4585-ba45-26fab3759aa7)

---
## Tasks
- [ ] Add checkbox to input functionality for pages listed above

## Acceptance Criteria
- [ ] New page formats are functioning as expected and match design
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Moving back to ready as a part of planning/reordering

**Comment by OptionSelect** [comment]
Bumping from 2 to 3 due to level of time and effort it took with cfsr and efsr changes needed.
