### ISSUE TITLE
Content Review - Appointment Modality/Appointment Details Page from VAOS - VA Online Scheduling

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#48448]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: 
- Link to or attach user flows:
- Link to prototype or mockups: 
   - [Modality Structure](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1194%3A66663)
   - [Pending Appt description](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2362%3A65832)
   - [Details Page Join Instructions](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1808%3A68061)
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: February 2023 
- Estimated staging review date: January 2023
- Content and IA work needed by: December 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VAOS, VA Online Scheduling
-	OCTO-DE product owner: Lauren Alexanderson, Katherine Lawyer, Stephen Barrs, Patrick Bateman, Mark Dewey
-	Product manager: Leah De La Costa & Jeff Roof
-	Designer: Peter Russo & Ciera Maddox
-	FE engineer: Simi Adebowale
-	Product/team Slack channel: #vaos

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@ldelacosta Can you link to the content you want reviewed or provide a little more detail on what support you are looking for from our team? Thanks!

**Comment by ldelacosta** [comment]
Hey @RLHecht - We are not ready yet. We are still updating the details in the ticket. Will let you know when it's ready. If you have any questions, please reach out. Thanks!

**Comment by ldelacosta** [comment]
@RLHecht - This ticket is ready for review. We are looking for guidance from your team on how VAOS should display the modality for the appointments. If you need further details, please reach out. Thank you!
