### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#48452]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: nanotone
- Reason access is required: My team (OCTO Benefits Delivery) works on the Hypertension Rapid Ready for Decision (RRD) fast-track utility, which is triggered via Sidekiq.

Note: I've previously had access (#37049), and got removed from the Github org when on leave. I'm back on the same project.

**Comment by ericboehs** [comment]
Done
