### ISSUE TITLE
Remove medallia feedback button from PCI (pre check in and day of)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#48456]
Decision was made here in [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1629382816348500) to remove

## Tasks

- [x] Create ticket for Platform team to remove Medallia feedback form/button from our app
- [ ] Monitor movement on ticket

**Comment by acrollet** [comment]
Created platform support request: https://dsva.slack.com/archives/CBU0KDSB1/p1666734111554899

**Comment by acrollet** [comment]
The analytics team [completed their work yesterday](https://dsva.slack.com/archives/CBU0KDSB1/p1668618765742409?thread_ts=1666734111.554899&cid=CBU0KDSB1) and I've verified that the Feedback button is not shown on day-of or pre-check-in.
