### ISSUE TITLE
[Design] Create Final Wireframes for Claim Exists Error Message

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48476]
## Tasks
- [ ] Create final mockups with callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=ud3aa760e30b39bcf436d4473

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @ytsaoca The content is drafted on [page 14 of this doc](https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit#heading=h.d1kx2t347fpy). Let me know if you'd like me to change or update it.

**Comment by benbrasso-agile6** [comment]
Thanks. Will take a look in the am.

**Comment by ytsaoca** [comment]
@kellysmith1008 Hope we can explore any chance to simplify the H1.
The current H1 doesn't look good because there are some lines that only include one word, leaving much space. Also, the title is too long. Therefore, it is not easy to scan for users.

![Screen Shot 2022-11-07 at 9.58.49 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/96f950a3-dad4-4aff-8c21-ea2482bb8676)

**Comment by ytsaoca** [comment]
Wireframe: https://share.goabstract.com/2c27652a-084b-4a36-8130-cd5130b6c673?mode=design&sha=c64fae50ded2eaf95e9f85740a2ba76062256a09

**Comment by ytsaoca** [comment]
Wireframe: https://share.goabstract.com/2c27652a-084b-4a36-8130-cd5130b6c673?mode=design&sha=c64fae50ded2eaf95e9f85740a2ba76062256a09

**Comment by benbrasso-agile6** [comment]
Looks nice. Great work.

**Comment by kellysmith1008** [comment]
Agreed - nice job, @ytsaoca !

**Comment by benbrasso-agile6** [comment]
@ytsaoca is this ready for validation? 

@loripusey @zach-park I feel like we may want to merge this sub-branch into the "Travel pay wireframes" branch. That way, all the MVP wireframes are in a single branch. Thoughts?

**Comment by zach-park** [comment]
Regarding the H1 copy, no more than 4 lines of text wrap is typically recommended, fyi. 

Regarding the "error page" sub-branch, yes, it can be merged once the wireframe is PO accepted/approved.

**Comment by loripusey** [comment]
I agree with the merging

**Comment by ytsaoca** [comment]
@benbrasso-agile6 ready for validation. Who at the engineer team do we tag for validating it?

**Comment by ytsaoca** [comment]
@benbrasso-agile6 ready for validation. Who at the engineer team do we tag for validating it?

**Comment by loripusey** [comment]
@wullaski has this engineering ticket that goes with this work; 
@ytsaoca do you have access to our board?

**Comment by ytsaoca** [comment]
@loripusey Which board are you mentioning?

**Comment by loripusey** [comment]
never mind

**Comment by ytsaoca** [comment]
Abstract Collection: https://share.goabstract.com/b0ddb4a1-cb79-4f93-89ff-68a05806f2f4?collectionLayerId&mode

**Comment by benbrasso-agile6** [comment]
@ytsaoca @loripusey @zach-park could we merge that wireframe into the existing collection? 
https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?sectionId=7e5f334e-d9bb-42e1-b8c6-de8808e72592

That way, we only have one final collection.
