### ISSUE TITLE
Adding Rakshinda Aslam to DSVA Slack

### ISSUE THREAD

**Issue by ENeal49** [department-of-veterans-affairs/va.gov-team#48494]
# Adding Rakshinda Aslam rakshinda.aslam@agile6.com to DSVA slack

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Are you requesting to add an individual as a: Full member

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Rakshinda Aslam is a Product Manager just joined Automated Benefits Delivery team.

We aim to complete slack requests within 24hrs.
#benefits-delivery-team
#benefits-rrd-health-evidence
#benefits-virtual-regional-office
#benefits-delivery-design
#benefits-rrd-engineering
#design (general VA design team)
#research-ops (veteran-facing research)
#rrd-tracking (notifications for RRD pilot)
#rrd-alerts (notifications for RRD pilo

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by eunicegar** [comment]
Done.
