### ISSUE TITLE
Adding Arash Aria to DSVA Slack

### ISSUE THREAD

**Issue by ENeal49** [department-of-veterans-affairs/va.gov-team#48492]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Adding Arash Aria arash.aria@agile6.com as a new users in DSVA slack

Are you requesting to add an individual as a: Full member

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

#benefits-delivery-team
#benefits-rrd-health-evidence
#benefits-virtual-regional-office
#benefits-delivery-design
#benefits-rrd-engineering
#design (general VA design team)
#research-ops (veteran-facing research)
#rrd-tracking (notifications for RRD pilot)
#rrd-alerts (notifications for RRD pilo

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Full stack Engineer, joined Automated benefits delivery team.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by eunicegar** [comment]
Done.
