### ISSUE TITLE
Give ID.me information about SiS user info errors

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#48502]
Errors from: https://sentry.vfs.va.gov/organizations/vsp/issues/157956/?environment=production&project=3&query=is%3Aunresolved+signincontroller&statsPeriod=24h

**Comment by bosawt** [comment]
One user, with remote_ip: `98.97.182.134`
- `2022-10-19T16:35:03.114275Z` - Auth sent to ID.me with state: `eyJhbGciOiJSUzI1NiJ9.eyJhY3IiOiJtaW4iLCJ0eXBlIjoiaWRtZSIsImNsaWVudF9pZCI6IndlYiIsImNvZGVfY2hhbGxlbmdlIjoidUtrYVhrRnc5aVNfWXA2ZzRDLXRBWVBGa3pMa251c0pLNXF1bWw1cnRFOCIsImNsaWVudF9zdGF0ZSI6ImNiM2VmMWVmY2I1OTA5ZGQ0MTRhNzNiNzZkYjU1YzE2NDVkMjk3YmRmODIzMjJhMTc1YjE5YTg0IiwiY29kZSI6ImU1MWQ3MzBiNWMyMzEwYTA4ZjVhZGE2ZTU3MzM1MzZkIn0.f2y9K92OwPsEvHjw9vsL39dUuxRQ30D1VAgNTWktlf5OOZ6KfcGI5vzgnDsT6IoJ2MWk40yBkYkezjsG45SWRc7J8h48P2unlvr_viy29KqjxiewYDkqw5-ciPzYydEEZj83Qhdp5ePsttjCkDRewiCZLotmhp20xZph4g_tZZvVRWee-jHcR5gB-JIwdm6zxBUIZn01vG46W_1ao3HP8qIbHJU1LNKGArhCvld5zlFWLInbErSK5VFbnw45r_Ele-sWB8vnRLPzqPKMymsoo3qb1m3eLit6DIPWFFeRiws-T81ll1ajqMm6VEqFMRE3dvZXIvL7W1qT4nNFmAEzKA`
- `2022-10-19T16:35:29.850554Z` - Id.me `/token` success with code: `b21587dc6b4c410d90170c2913539b36`
- `2022-10-19T16:35:30.155353Z` - Id.me `/userinfo` failure with `401`

**Comment by bosawt** [comment]
![image.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/efb266b2-daa2-4ed9-9cb5-bf30e8350402)

**Comment by bosawt** [comment]
22 logs

**Comment by bosawt** [comment]
Questions:
- Why is status `nil` for many of these?
- Why is there no description? (We look at `error_description` in response body for description)

**Comment by alyssagallion** [comment]
Followed up in Slack Channel #idme-va-gov with Jessica McClure, she will follow up on 10/28 with progress. Alyssa will follow up by EOD that day if have not heard back.

**Comment by alyssagallion** [comment]
Blocked by ID.me currently. Working with Joe to get a list of items to bring to ID.me. Will follow up with Jessica when I have that list.

**Comment by alyssagallion** [comment]
Followed up via email today and will circle back when I hear something. If don't hear back by Thanksgiving, will reach out again the following Monday.

**Comment by alyssagallion** [comment]
Blocked by ID.me, emailed John to push for answers.

**Comment by bosawt** [comment]
I'm gonna close this, if we want to work with ID.me on new SiS errors we can investigate separately
