### ISSUE TITLE
Inform ID.me of missing attributes in valid credentials

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#48504]
https://sentry.vfs.va.gov/organizations/vsp/issues/160316/?environment=production&project=3&query=is%3Aunresolved+signincontroller&statsPeriod=24h

**Comment by bosawt** [comment]
User with id.me uuid: `d6ec82c304ae4df39d86fe47924017cb` appears to have missing attributes in the credential, we need to find out why

**Comment by alyssagallion** [comment]
Followed up in Slack Channel #idme-va-gov with Jessica McClure, she will follow up on 10/28 with progress. Alyssa will follow up by EOD that day if have not heard back.

**Comment by alyssagallion** [comment]
Followed up via email today and will circle back when I hear something. If don't hear back by Thanksgiving, will reach out again the following Monday.

**Comment by alyssagallion** [comment]
Blocked by ID.me, emailed John to push for answers.

**Comment by bosawt** [comment]
I'm gonna close this, we can follow up with ID.me on future errors if we want to
