### ISSUE TITLE
Fix broken link on Pension benefit hub page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48514]
## Issue Description
A stakeholder reached out to let us know that we have a broken link under the Other benefits and services section of the [VA pension benefits](https://www.va.gov/pension/) hub landing page. 

The link for FTC complaint assistant for reporting fraud should be replaced with this: https://reportfraud.ftc.gov/#/

## Tasks
- [x] Update link
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Link is working on live site

**Comment by katherine-fung** [comment]
Hi @megzehn - I updated the broken link for "FTC complaint assistant for reporting fraud." It now points to a link that the stakeholder provided, which leads to the FTC page for reporting fraud.
 
http://preview-prod.vfs.va.gov/preview?nodeId=73

**Comment by megzehn** [comment]
Thanks, @katherine-fung!

@RLHecht, I published the page with the updated link.

**Comment by RLHecht** [comment]
This is live. Closing ticket.
