### ISSUE TITLE
Adding Sarah Koomson to DSVA Slack

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#48516]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

- Please add Sarah.Koomson@oddball.io as a full member. Sarah is rejoining as an a11y specialist on the Design System team. She was previously a member of the workspace.

**Comment by LEHigley** [comment]
reactivated account
