### ISSUE TITLE
Monitoring for each TIC gateway

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#48518]
## Issue Description

As an action item from the [vets-api latency postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/577/files#diff-2f510b355aac3047109ef16923f9aac80a17a78b533cd8612b2b990d9b24d84a), platform should be sure to increase monitoring and visibility for ALL the TIC gateways. It was new knowledge to platform that a round robin scheme is used to load balance requests across all gateways. Additionally, many of our downstream partners utilize GWS. It was to our knowledge that we didn't use GWS, therefore we had limited monitoring for GWS. Will we want to expand our monitoring, etc, to cover "blindspots" we might have.

## Tasks
- [ ] Increase monitoring for GWS

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by jbritt1** [comment]
Hopefully this can now be closed with the merge of https://github.com/department-of-veterans-affairs/devops/pull/12174.

**Comment by ericboehs** [comment]
Closing as dupe to https://github.com/department-of-veterans-affairs/va.gov-team/issues/48523.
