### ISSUE TITLE
Adding Lee Warrick to DSVA Slack

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#48515]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

- Please add lee.warrick@oddball.io as a full member. Lee is joining as a DevOps engineer on the VA.gov Platform contract.

**Comment by andreahewitt-odd** [comment]
@KevinMHoffmanUSDS @LEHigley Any chance I can get an approval?

**Comment by LEHigley** [comment]
reactivated
