### ISSUE TITLE
Confirm SNOW access for teams who do incident response

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#48519]
## Issue Description
As an action item from the [vets-api latency postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/577/files#diff-2f510b355aac3047109ef16923f9aac80a17a78b533cd8612b2b990d9b24d84a), platform should enable and confirm SNOW access for teams who do incident response. SNOW is the ticketing system is product of VA OIT for  collaboration with business partners.

## Tasks
- [ ] Ensure SNOW access for platform member incident response

**Comment by rjohnson2011** [comment]
Created an issue in the VA sensitive repo, as instructed via Eric B/Mike C -> https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/640
