### ISSUE TITLE
Create troubleshooting playbook for components like Vets API

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#48520]
## Issue Description
As an action item from the [vets-api latency postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/577/files#diff-2f510b355aac3047109ef16923f9aac80a17a78b533cd8612b2b990d9b24d84a), platform should document a playbook for troubleshooting the various components of vets-api in relation to latency. It's possible that a playbook currently exists and in that case, it should be reviewed/updated accordingly. It's important to document various infrastructure related troubleshooting steps along with backend/application layer analysis.  

## Tasks
- [ ] Create or update playbook
- [ ] Note: identify existing EKS items to mitigate vets-api cycling

**Comment by rjohnson2011** [comment]
Draft of the playbook available -> https://vfs.atlassian.net/wiki/spaces/~527721881/pages/2447736836/Troubleshooting+Playbook+for+Vets+API+Components
