### ISSUE TITLE
Remove SSOe Sidekiq Configs

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#48529]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Unused [SSOe SAML metadata files](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/sidekiq/dev/templates/ssoe-int-config.yaml) exist in the VSP-Infra repository. After confirming that these are truly unused they should be removed.

[Related Slack discussion](https://dsva.slack.com/archives/CSFV4QTKN/p1666198842617899)

---
## Tasks
- [x] Investigate the possible existence of any remaining Sidekiq jobs that involve authentication/SSOe
- [ ] Remove unused SSOe files from Sidekiq manifests

**Comment by bramleyjl** [comment]
Removal commit: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/b3bf393083b44a765b005680cdc20bb00071f34f

**Comment by alyssagallion** [comment]
Waiting on Lindsey
