### ISSUE TITLE
[BE] Investigate 1010ez validation error

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#48528]
http://sentry.vfs.va.gov/organizations/vsp/issues/129405/events/dead7ba50c8f49309487b98ad70c6ee2/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Ahealth_care_applications+level%3Aerror&statsPeriod=14d

**Comment by lihanli** [comment]
this error linked in the issue hasn't happened recently, however i did see a few errors related to the short form.

the frontend is sending a short form submission and then the backend calls the disability rating api to see if the user has a high enough disability rating to use the short form, but then the call either fails or the user doesn't have a high enough disability rating, then a validation error is thrown because the user is missing the long form required fields.

i'm going to add additional logging to see if the disability rating call is failing or the user's rating is too low to qualify for short form.

**Comment by lihanli** [comment]
@longmd in order to fix these validation errors i think that the `vaCompensationType` field should be filled in by the frontend for logged in users. right now what is happening is the user is sending a short form submission, then the backend calls the disability rating api and gets an error or the backend sees the form as coming from a logged out user and cannot call the rating api, and then the form is processed as a long form submission and the missing fields trigger a validation error.

**Comment by longmd** [comment]
Just doublechecking... you’ll be able to do with what you need by just having the string value for that `vaCompensationType` field? The options would be `none`, `lowDisability`, `highDisability` or `pension`.

**Comment by lihanli** [comment]
@longmd if the frontend sends `vaCompensationType = highDisability` for logged in short form submissions then the validation errors should stop happening

**Comment by longmd** [comment]
@lihanli , so it looks like you can have a value of `lowDisability` or `highDisability` for that and still submit a short form. For example, that staging user 228 has a value of `lowDisability` for the rating, but is still eligible for the short form.

**Comment by lihanli** [comment]
@longmd that's news to me, lisa told me that only users that have a highDisability rating are eligible for short form. 228 also should be highDisability since it has a 100 disability rating

**Comment by lihanli** [comment]
@longmd what are the exact rules for when short form submissions are allowed? in the backend it is allowed if the user's disability rating is 50% or higher or if the user is not logged in and they select `highDisability` for `vaCompensationType`. if that isn't correct then i need to change the backend code.

**Comment by lihanli** [comment]
according to this issue the short form is directly connected to the disability rating
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37822

**Comment by longmd** [comment]
@lihanli , so by the actual logic put into the form conditionals, you are correct that it is looking at the disability rating number and issuing the short form flow based on that value. However, for the `vaCompensationType` value, there is logic in migration function that evaluates other data to set the none, low, high or pension string values. I'm still working on tracking down where those data bits are coming from.

**Comment by lihanli** [comment]
@longmd for logged out users, what values of `vaCompensationType` allow a user to access the short form?

**Comment by longmd** [comment]
@lihanli , `highDisability` is the value that gets submitted for those who manually select 50% or higher. It looks like `vaCompensationType` comes from prefill, too, so I wonder if there is different criteria that sets those values in their profile that allows for someone with a high rating but low classification.

**Comment by lihanli** [comment]
@longmd i don't think the prefill migration rules matter here. short form submissions from logged in users should have a `vaCompensationType` of `highDisability` since only `highDisability` is accepted for short form for logged out users.

**Comment by longmd** [comment]
@lihanli , so what if I just put a check in that says if the disability rating is >= 50% and `vaCompensationType` does not equal `highDisability`, then I override the value to submit to you `highDisability`? That would take care of a prefill mismatch.

**Comment by lihanli** [comment]
@longmd if you send `highDisability` for short form users then that would solve the problem. according to lisa, the frontend is not sending anything for the `vaCompensationType` field for logged in short form users.

**Comment by longmd** [comment]
@lihanli , we're all good to go with the FE work. This will go out with today's daily.

**Comment by hdjustice** [comment]
@lihanli @longmd - did this issue get resolved or do we still need to do something?

**Comment by lihanli** [comment]
@hdjustice i think it's resolved now
