### ISSUE TITLE
[tech task] Maintenance | Update Bypass schema form documentation

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#48526]
## Value Statement
**_As a_** frontend developer
**_I want_** documentation that includes recent changes to the Bypass schema form documentation
**_So that_** I can efficiently use the `CustomPage` component

## Background Context

While building some `CustomPage` components for our Supplemental Claims form, I noticed that the form was not auto-saving, and the "Finish this application later" link and save-in-progress status window, above and below the form progress buttons, were not included. A PR ([#22457](https://github.com/department-of-veterans-affairs/vets-website/pull/22457)) was created to add this functionality.

## Relevant URLs

- [CustomPage enhancements PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22457)
- [Document page to update](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-bypass-schema-form)

## Content to add

Under "CustomPage props"

Additions:

- `contentBeforeButtons`: Element
  - Renders the "Finish this application later" link as well as the save-in-progress menu link (when enabled)
- `contentAfterButtons`: Element
  - Renders the `SaveStatus` component which shows the time and date of the last time the application was saved
- `setFormData`: Function
  - Calls the `setData` action
  - This function also auto-saves the form data change, which in turn updates the `SaveStatus` date and time

Updates:

-  `goToPath` (add before last entry)
  - The path can also include search parameters which would allow navigating between CustomPages, and pass a reference; example: `goToPath('/view?id=1234')`

**Comment by vbellissimo** [comment]
@Mottie Hi Rob, thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by laucon** [comment]
@Mottie I added the additions. I placed them at the bottom of the "CustomPage props" section. This will be deployed today at 5pm. If you want me to place the additions somewhere else within that section, feel free to let me know.

I wasn't sure how to do the other updates you asked for. You said:
"Updates:
    goToPath (add before last entry)"

- Did you want me to update a place where it already says "goToPath?"
- Did you want me to add the words "goToPath" between the words "In the [Common tasks](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-bypass-schema-form#common-tasks) section below, updatePage is used to update the review page: onReviewPage ? updatePage() : ..." and the words "editPage: () => void"?
- Did you want me to add the words "goToPath" between the words "The function to call to initiate editing the data on the review page." and "This function also auto-saves the form data change, which in turn updates the SaveStatus date and time"?

**Comment by laucon** [comment]
@Mottie Correction: I changed it back to what the doc originally said because my manager told me to wait before editing and deploying this.

**Comment by Mottie** [comment]
@laucon Thank you. Yes, these changes shouldn't be deployed until after the work in [#22457](https://github.com/department-of-veterans-affairs/vets-website/pull/22457) has been merged.

**Comment by laucon** [comment]
@theodur @npeterson54 Mottie had 2 requests, an addition and an update. For the addition, I added the text at the bottom of the "CustomPage props" on [this page.](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-bypass-schema-form) Here is the before and after.

Before the edit, the section looks like this:
<img width="1787" alt="Screen Shot 2022-10-24 at 12 09 45 PM" src="https://user-images.githubusercontent.com/14806304/197574696-91490b08-9aeb-44f8-bf43-00de779115e3.png">

After the edit, the section will look like this (I've highlighted the text I will add):
<img width="1782" alt="Screen Shot 2022-10-24 at 12 09 07 PM" src="https://user-images.githubusercontent.com/14806304/197574768-bd6f29ff-4185-4bb9-8798-36cef75aafc8.png">

Is this ok? Would you prefer that I place this text somewhere else on the page?

Also, I wanted to mention that I can't deploy this until [pull request 22457](https://github.com/department-of-veterans-affairs/vets-website/pull/22457) is completed. Do you have any thoughts on that or any idea when [pull request 22457](https://github.com/department-of-veterans-affairs/vets-website/pull/22457) will be completed?

**Comment by laucon** [comment]
@theodur @npeterson54 Hello again. Mottie had a second request which was harder for me to understand. Mottie said "Updates:
    goToPath (add before last entry)
    The path can also include search parameters which would allow navigating between CustomPages, and pass a reference; example: goToPath('/view?id=1234')"

I don't know what that means. Can you figure out what text he wants to update and where and how? Thanks!

**Comment by Mottie** [comment]
@laucon Sorry I wasn't clear. I was suggesting this change to `goToPath`:

> - `goToPath`: Function
>   - `CustomPage` only.
>   - Function to call if you need to go to a specific path within the form.
>   - When calling this function with a valid active path, it will return you to that page. For example, goToPath('/second-page').
>   - The path can also include search parameters which would allow navigating between CustomPages, and pass a reference; example: `goToPath('/view?id=1234')`
>   - An invalid path will send you back one page, so be careful.

The item, "The path can also... ", is added before the last item

**Comment by laucon** [comment]
@Mottie Understood. ok. thank you so much. @theodur @npeterson54 so, are you ok with this edit? I've highlighted the text I want to add. It's just me adding 1 single line.

Before:
<img width="1784" alt="Screen Shot 2022-10-24 at 12 51 03 PM" src="https://user-images.githubusercontent.com/14806304/197581947-270a9bca-e94e-4323-9f36-91f97ff21d33.png">

After:
<img width="1788" alt="Screen Shot 2022-10-24 at 12 52 14 PM" src="https://user-images.githubusercontent.com/14806304/197582014-9515e19b-df0d-4bd2-aa14-cf47038582bb.png">

Also, I want to be clear on the reason why I'm asking Theo and Nate. Our team has been told by management to talk more to people like Theo and Nate simply because people like Mottie are so busy with tons of other stuff. But we also want to get oks from subject matter experts before publishing changes. Thanks to everybody!

**Comment by theodur** [comment]
@laucon Hi Lauren, there's a new team that manages the forms library. They would probably be the best people to ask. I believe you can reach them in [#forms-library](https://dsva.slack.com/archives/C862Q82UQ) but I'm tagging @PSIEBENLIST @tbaker1026 & @ndsprinkle for reference.

**Comment by Mottie** [comment]
@laucon I've merged in the CustomPage work, so we should be good to update the documentation now.

cc: @jamigibbs

**Comment by laucon** [comment]
I'm letting everyone know that Nick Sprinkle and Tricia Baker checked and approved my edits, so I'm going to publish the edits on Monday. yay!

**Comment by laucon** [comment]
Since I'll be deploying at 3:30 today, I'm going to close this ticket.
