### ISSUE TITLE
Restore network monitoring in Datadog  

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#48525]
## Issue Description
As an action item from the [vets-api latency postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/577/files#diff-2f510b355aac3047109ef16923f9aac80a17a78b533cd8612b2b990d9b24d84a), platform should ensure that we restore network monitoring in Datadog. Network Performance Monitoring (NPM) would allow for greater insight into quality and performance of the existing infrastructure components and their network traffic. NPM would allow for engineers to pinpoint unexpected or latent service dependencies. More on [NPM here](https://docs.datadoghq.com/network_monitoring/performance/)

## Tasks
- [ ] enable/re-enable NPM in Datadog

**Comment by ericboehs** [comment]
My team confirmed this was working as expected. There was some initial confusion as DD leaves a tutorial on how to set it up as the default view after it's already set up.
