### ISSUE TITLE
[Dev]: Better differentiation between ophthalmology & optometry

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#4853]
## Story
Feedback from production UAT session:  As a veteran with eye care needs, I want to more easily understand whether I should request an optometry or ophthalmology appointment so that I see the right kind of doctor for my eye issue.

## AC
- [ ]  Content below is implemented on "Type of Care" selection page
- [ ]  @peggygannon validates content implementation on staging.

-----

Choose the type of eye care appointment that you need
**• Optometry** 
You can schedule an optometry appointment for a routine eye exam, eye test, or to treat conditions like glaucoma or low vision. Optometrists will also give you a prescription for eyeglasses or corrective lenses.  
**• Ophthalmology** 
You can schedule an ophthalmology appointment for the diagnosis and treatment of more serious eye conditions that may need surgery, like cataracts, macular degeneration, diabetic retinopathy, or other eye diseases.

**Comment by markgreenburg** [comment]
@peggygannon is this meant to use the 'follow up page' pattern we've used for sleep medicine and audiology? If so, what should the type of care option be? Just 'eye care' or something else?

**Comment by rtwell** [comment]
love this! thank you @peggygannon great work as always!

**Comment by peggygannon** [comment]
Hi, @markgreenburg Yes, this should follow same pattern that we used for sleep medicine. I recommend using "Eye care" as the type of care option.

**Comment by lenaecb** [comment]
@jenniemc - are we ready to close out this ticket?

**Comment by jenniemc** [comment]
Hi @lenaecb, still working this ticket.
