### ISSUE TITLE
Dynamic ID's Are Getting Into the `endpoint` Label of Prometheus Metrics

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#4854]
## The Problem
Dynamic ID's are getting into our `endpoint` label for the `api_external_http_request_duration_seconds` metric. 

Specifically, 

```
/api/v1/users/SOME_DYNAMIC_ID
```
This results in a limitless number of values for the `endpoint` label of the `api_external_http_request_duration_seconds` metric - which means it has the potential to overload our prometheus storage devices.

## Additional Context
Prometheus link as proof:
http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=1h&g0.expr=count%20by%20(endpoint)%20(api_external_http_request_duration_seconds%7Bendpoint%3D~%22%2Fapi%2Fv1%2Fusers%2F.%2B%22%7D)&g0.tab=1

## Work to be Done
- [ ] Filter these dynamic id's and replace them with `xxx`

**Comment by LindseySaari** [comment]
Duplicate ticket, Taken care of by this commit: commit/e3fd816d0f2f5b10ede26cfcde9c773e89a7d16d#diff-a0963798e0d9e90d8896475cc9707260
