### ISSUE TITLE
[Spike] Review FE logic for Type of Care page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#48556]
## Background/Request
The product team is looking for assistance from the development to research on how the code is built on the frontend for scheduling flow. We would like to improve the code base in the near future. After the spike ticket is complete, our team will evaluate the next steps to improve the code by comparing the business rules to the current behavior.

### Goal
To understand the behavior of the FE code and update the VAOS documentation

### Requirements to Consider
- N/A 

---

## Tasks
- Answer the following questions:
  - Q1: What are the frontend checks when a user lands on the type of care page? Where does the type of care list come from (is there a 1:1 mapping)? 

![Screen Shot 2022-10-24 at 7.41.13 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/71d3b747-a7e1-4058-94c3-ff02e30c2013)

  - Q2: Are there any additional frontend checks when a user lands on the sub-type of care page for eye care? 
![Screen Shot 2022-10-24 at 7.43.14 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7d51c95e-c660-4a60-a5d3-fa781b96188b)

  - Q3: Are there any additional frontend checks when a user lands on the sub-type of care page for sleep care? 
![Screen Shot 2022-10-25 at 9.27.45 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3e425101-50b7-4cfc-8966-7e5b7cc595fe)

  - Q4: Since Podiatry is for only Community Care, what are the checks to allow the user to submit a CC request? 
![Screen Shot 2022-10-25 at 9.29.54 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/19a448d7-374b-4efb-b3b6-4014192ca85b)

- Q5: What are the type of care checks that triggers the next screen `Choose where you want to receive your care` page? 

![Screen Shot 2022-11-03 at 2.14.38 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/676de571-2064-4998-8849-aaf3db32512e)

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by outerpress** [comment]
@ldelacosta @JRRoof we might have all this documented in the feature reference. See [type of care](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/all--type-of-care.md#functional) in the scheduling flow

**Comment by ldelacosta** [comment]
No additional research needed. Closing out the ticket.
