### ISSUE TITLE
Investigate “Code in state is not valid” error

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48562]
https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20error%20deployment_env%3Avagov-prod%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%22logout%22%20%22callback%22%20%E2%80%9CCode%20in%20state%20is%20not%20valid%E2%80%9D&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=service%2Cdesc&viz=stream&from_ts=1666195200000&to_ts=1666209600000&live=false

Idme 49
Logingov 68
Dslogon 11
Mhv 1

**Comment by bramleyjl** [comment]
I looked up several of the IPs from these logs and found that these errors are usually happening 15-60+ minutes after the authorize call to start the SiS login flow was called. I believe that the majority of these are resulting from users that start SiS authentication but do not finish CSP authentication until much later, so when the CSP returns our `state_code` it is no longer there, as it is set to last only 30 minutes.

**Comment by joeniquette** [comment]
standard activity, closing.
