### ISSUE TITLE
Investigate “Code is not defined” error

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48563]
https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20error%20deployment_env%3Avagov-prod%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%22logout%22%20%22callback%22%20%E2%80%9CCode%20is%20not%20defined%E2%80%9D&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=service%2Cdesc&viz=stream&from_ts=1666195200000&to_ts=1666209600000&live=false

**Comment by bosawt** [comment]
I'm gonna close this, dunno if we can even see the logs in data dog anymore
