### ISSUE TITLE
Investigate “Unable to Authorize User” Error

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48564]
https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20error%20deployment_env%3Avagov-prod%20logout&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=service%2Casc&viz=stream&from_ts=1666195200000&to_ts=1666209600000&live=false

**Comment by joeniquette** [comment]
closing, duplicate
