### ISSUE TITLE
Adding [Daniel Scarbrough] to DSVA Slack

### ISSUE THREAD

**Issue by cbrizen** [department-of-veterans-affairs/va.gov-team#48568]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Daniel to DSVA Slack

Are you requesting to add an individual as a:

- Full member

Daniel was just onboarded to the Long COVID team as a data engineer and needs to be able to communicate with the team and stakeholder.

- Please add [daniel.scarbrough@thoughtworks.com] as a full member.

**Comment by eunicegar** [comment]
Sent.
