### ISSUE TITLE
Investigate “Attribute mismatch, ssn in credential does not match MPI attribute” error

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48561]
https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20error%20deployment_env%3Avagov-prod%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%22logout%22%20%22callback%22%20%E2%80%9CAttribute%20mismatch%2C%20ssn%20in%20credential%20does%20not%20match%20MPI%20attribute%E2%80%9D&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=service%2Cdesc&viz=stream&from_ts=1666195200000&to_ts=1666209600000&live=false

**Comment by bramleyjl** [comment]
This happened twice to the same user in quick succession - looks like they attempted to auth again after the first try failed. I looked up their SSN from the MPI response and it looks fine, @bosawt do you know how to query their CSP attributes (Login.gov) in production for comparison?

**Comment by joeniquette** [comment]
@bramleyjl please give me icn, cspid, mpi transaction id of the mpi query.

**Comment by bramleyjl** [comment]
* ICN: `1027434315V423368`
* [Transaction ID (Find Profile Response)](https://vagov.ddog-gov.com/logs?query=%222601%3A2c7%3A4200%3A1290%3Ab04c%3Acbb0%3Aef5d%3A2e24%22&cols=host%2Cservice&event=AQAAAYPxqve_ySckAAAAAABBWVB4cTBfNkFBQUFlRUNZVW82Y3V3QzM&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1666159200000&to_ts=1666245540000&live=false): `e0b63f9263504c8843f2c2b0`
* Login.gov ID: `5b92705a-ccb3-48d4-a33f-8e3d0a0f7c37`

**Comment by joeniquette** [comment]
Submitted report to Danny Reed. Setup Monthly reminder in team slack channel.
