### ISSUE TITLE
Midpoint Review - Design Feedback - Sitewide Homepage, VA.gov homepage redesign

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#48576]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
- Alphabetize the popular links list

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by mmiddaugh** [comment]
Thanks @allison0034 rather than alpha order, we intentionally ordered the list to group related tasks (i.e., health care tasks appear more or less together).

**Comment by allison0034** [comment]
Ok thanks @mmiddaugh . If you do any future testing I would try A/B testing. If users are likely to know the name of what they are looking for typically alpha is a better option, but obviously user testing wins. : )
