### ISSUE TITLE
Create Github Actions Self-hosted runner to automatically update mock data (dev/staging)

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#48581]
## Description
We now have a script in vets-api to iterate through the `vets-api-mockdata` repository and update mocked records with actual MPI lowers records, but we should automate this more thoroughly. We can add a Github self-hosted runner that will pull vets-api-mockdata, run scripts to update MPI (and other services that may make sense), and create a PR for review and submission.

Currently the synchronization rake task is located in `rakelib/mockdata_synchronize.rake`.

## Technical Details
initial iteration can use `workflow_dispatch` (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) with inputs such as the `icn`, `env` etc:

- creds are seeded (aws-cli / github token)
  - example of grabbing creds for aws / parameter store:
    - https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/packer-build-eks.yml#L45
- eks cluster added
  - `aws eks update-kubeconfig --name ${CLUSTER_NAME}`
- exec into `vets-api` instance
  - run script
  - `kubectl exec -it <pod_name> -n vets-api --context=<env> -- <script_cmd>`
- store new `*.yml` file in mockdata repo (e.g. `/app/config/vets-api-mockdata`)
  - `vets-api-mockdata/mvi/profile_icn/<new_data>.yml`
- create new branch / open PR with new `*.yml`

this user: `svc-gha-platform-infrastructure` along with these credentials `/devops/dsva-ecr-service-account/AWS_ACCESS_KEY_ID` / `/devops/dsva-ecr-service-account/AWS_SECRET_ACCESS_KEY` can be used 

repo where workflow will live / PRs created:
https://github.com/department-of-veterans-affairs/vets-api-mockdata

script command: `rake mockdata_synchronize:mpi_profile_icn\[<icn_number>\] --trace`

## Acceptance Criteria
- [x] create workflow
  - get workflow to show up in github action menu in repo
  - get manual trigger to show up in github action menu in repo
- [x] seed aws/gh(?) creds
- [ ] add cluster
- [ ] exec into pod / run script
- [x] save yaml file
- [x] open pr

**Comment by ianhundere** [comment]
tried running the script locally, albeit dockerized:
```
vets-api@1a15c8b7324a:~/src$ rake mockdata_synchronize:mpi_profile_icn
rake aborted!
SocketError: Failed to open TCP connection to ps-dev.commserv.healthevet.va.gov:8110 (getaddrinfo: Name or service not known)
/usr/local/bundle/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
/usr/local/bundle/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:43:in `create_curl'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:11:in `create_cache_from_profile'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:47:in `update_mpi_record_for_icn'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:58:in `block (3 levels) in <main>'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:56:in `each'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:56:in `block (2 levels) in <main>'
/usr/local/bundle/gems/ddtrace-1.8.0/lib/datadog/tracing/contrib/rake/instrumentation.rb:32:in `execute'
/usr/local/bundle/gems/ddtrace-1.8.0/lib/datadog/tracing/contrib/rake/instrumentation.rb:21:in `invoke'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
SocketError: getaddrinfo: Name or service not known
/usr/local/bundle/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
/usr/local/bundle/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:43:in `create_curl'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:11:in `create_cache_from_profile'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:47:in `update_mpi_record_for_icn'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:58:in `block (3 levels) in <main>'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:56:in `each'
/srv/vets-api/src/rakelib/mockdata_synchronize.rake:56:in `block (2 levels) in <main>'
/usr/local/bundle/gems/ddtrace-1.8.0/lib/datadog/tracing/contrib/rake/instrumentation.rb:32:in `execute'
/usr/local/bundle/gems/ddtrace-1.8.0/lib/datadog/tracing/contrib/rake/instrumentation.rb:21:in `invoke'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => mockdata_synchronize:mpi_profile_icn
(See full trace by running task with --trace)
```

i assume this is because it's using a bridge network as a opposed to a host network preventing it from using socks.

**Comment by ianhundere** [comment]
i think an easier route for this would be to just automate using ssm to jump onto an instance and run the script instead of using a hosted runner. though we do have hosted runners specifically for `vets-api`, i just don't see any evidence they're being used:
- `devops/terraform/environments/dsva-vagov-utility/gha-runners.tf`
```
    "vets-api" = {
      image_id              = "ami-00800e8f7f03f831f"
      instance_type         = "c5.4xlarge"
      security_groups       = ["sg-0e23b56be3798e3a1"]
      policy_arn            = "arn:aws-us-gov:iam::008577686731:policy/gha_frontend_user_ssm"
      desired_capacity      = 4
      max_size              = 4
      min_size              = 1
      threads               = 4
      asg_name              = "dsva-vagov-vets-api-gha-runners-asg"
      max_instance_lifetime = 432000
    }
```

**Comment by ianhundere** [comment]
running into the following issue when trying to run the script via EKS dev:
```
nonroot@vets-api-web-85b774f59f-48s68:~$ rake mockdata_synchronize:mpi_profile_icn\[1008709763V491590\] --trace
rake aborted!
LoadError: cannot load such file -- ddtrace
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/app/Rakefile:7:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

Trevor mentioned the rake task may require `ddtrace` which we may want to remove specific to the script.

**Comment by ianhundere** [comment]
this user: `svc-gha-platform-infrastructure` along with these credentials `/devops/dsva-ecr-service-account/AWS_ACCESS_KEY_ID` / `/devops/dsva-ecr-service-account/AWS_SECRET_ACCESS_KEY` can be used

**Comment by ianhundere** [comment]
- creds are seeded (aws-cli / github token)
- eks cluster added
- exec into `vets-api` instance
- run script
- create new branch
- open pr

**Comment by ianhundere** [comment]
example of grabbing creds for aws / parameter store:
- https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/packer-build-eks.yml#L45

**Comment by ianhundere** [comment]
an alternative to execing into an eks pod is to use the `vets-api` gha runner:
- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-utility/gha-runners.tf#L3

**Comment by vidjovanovic** [comment]
Spoke with Riley, he had created mockdata endpoint and this task can be unblocked

**Comment by vidjovanovic** [comment]
Finalized GHA with Tim, looked at outputs in /mvi/profile_icns and confirmed that script is working as intended and post-process scripts are working as well.
