### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Sitewide Homepage, VA.gov homepage redesign

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#48585]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Heading structure is fantastic! I really appreciate the thought that went into it.
- On staging the illustration accompanying the Pathfinder news article has alt text `Thumbnail alt text goes here`. I'm sure you're already thinking about it, but make sure there's some editorial process in place to ensure that whenever a new news article gets switched into that space, the image has meaningful alt text.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
- For the search input and the email address input, I see that each has an `aria-label` giving them an accessible name for screen readers. If possible try to provide a visible label associated with each field using the `<label>` element instead. 
   
   For sighted voice command software users (eg. Dragon Naturally Speaking), moving focus to a form control is accomplished by speaking a command like "Click [name of control]." That requires the user knowing what the name of the control is --- which requires having a label they can see. In this context, both the search field and the email address field are pretty guessable, and most users will probably get enough of a match that their software can get them to the right place. But it's a potential point of friction that can be removed easily with a visible label.
   
   **Edit:** Chatted with @laflannery for a few minutes and she reminded me that the search input is using the design system `va-search-input` component -- so it likely is not feasible to add a visible label to that input unless changes are made to the component. That's probably fine, since the input immediately follows a heading that also identifies the purpose of the input, so the name of the input is very easy to guess. Laura and I will follow up with DST to decide if there's a better/different way forward with visible labels on that component.
   
   But I'd still recommend a visible label for the email address input. That one is still pretty guessable but may be a little less clear for voice command users, and a visible label should solve that issue.

**Consider:**
These consider items are *very* picky -- but it is the homepage, and you all did such a great job with all the things I would normally flag!
- Under "Other search tools" and "Popular on VA.gov," there are unordered lists of links. Both `ul`'s use `list-style: none` for styling. VoiceOver on Mac removes the implicit list role when using `list-style: none`, meaning these lists aren't announced as "list, [n] items" for VoiceOver users. 

   As far as Apple is concerned, this is a feature and not a bug that needs to be fixed. They deliberately remove list semantics to address situations where `ul` lists are used for things that aren't really proper lists, like main navigation menus. If a `list-style: none` list is truly a list, they recommend explicitly adding that role using `role="list"`.
   
   In this case, these lists of links are pretty clearly supposed to be list-y. I would recommend adding `role="list"` to the `ul` to explicitly set the list semantics.
   
- At the top of the page, the PACT Act section follows the pattern:   
  ```
  [heading]
  [description]
  [link]
  ```
  Further down the page, the Pathfinder news item follows the pattern:
  ```
  [linked heading]
  [description]
  [link]
  ```
  Consider harmonizing these so it's a consistent interaction pattern. Between the two of them I would suggest matching the PACT Act section, which keeps the purpose of the heading separate from the link and the "Learn what the PACT Act means to you" link is a single link with unambiguous text, which is a smoother interaction for screen reader users. 

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by mmiddaugh** [comment]
Thank you @briandeconinck - please let us know what you learn about the search input label. This feedback has been separated into two issues: 
- [Redesigned homepage: Email address and search field input #11389](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11389) _- to be prioritized before launch_
- [Redesigned homepage "consider" accessibility feedback](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11392) _- to be prioritized post-MVP_
