### ISSUE TITLE
Build Drupal AX for campaign landing page template

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4858]
## Build Drupal AX for campaign landing page template

This is part of the epic to create a campaign landing page template.  For problem statement and background, see epic and product info here: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4621

- We have a FE design template and content model and content specs/requirements
- We have a possible pilot stakeholder, Office of Mental Health Suicide Prevention. 
- Desired availability of CMS AX: Q1 (more specific timeline TBD conversations with other teams involved).

**Product repo:** 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates

**Product outline:** 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/README.md

FYSA @davidconlon  - assigning this ticket to you for when you're ready to assign out to Drupal engineer.

**Comment by jenniferlee-dsva** [comment]
Per latest conversation with @AkucherGCIO and info that a new Drupal engineer will be available on the PW team starting April, this work can be implemented by PW team by the new Drupal engineer. FYSA @davidconlon  @AkucherGCIO

**Comment by jilladams** [comment]
CLPs were built, this ticket is very old. CLosing.
