### ISSUE TITLE
Analytics Implementation or QA Support for [Authenticated Experience My VA - Payment info v2]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48598]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**
     Authenticated Experience My VA    
    
- **Provide the link(s) for Google Analytics implementation or QA**
    - va.gov/my-va
    
- **When is the launch date?**
    - mid-late Q4 2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    - [Payment info v2 metrics](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history#v2-updating-payments-and-debts-to-address-usability-issues-may-2022---current) (Outstanding Debts and Benefit Payments)
    - Will need to ensure that a distinction between clicks on "Manage your VA debt" link in Outstanding Debts section and "Manage your VA debt" link within onsite notifications persists. 
    - Monitor successful gets and failures
   

### Optional
- **If applicable, what test users are needed?** Please see our test cases linked below as well as our test user summary table (same document) which will help you see at a glance which test users have varies types of debts and payments, as well as some notes on troubleshooting.
      - [Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md)
      - [Test User Summary Table](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md#Test-User-Summary-Table)

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@ajakabcin - so we know from our previous work on #41730 that link from the notification is working as expected....

![image](https://user-images.githubusercontent.com/93597659/198076530-b9de9d2d-ba00-4047-b8e6-84c41bd66cf3.png)

![image](https://user-images.githubusercontent.com/93597659/198076773-3712d0c9-a0ce-45d1-b29b-91ed50173e41.png)

To track the link click from 'Outstanding debts' section use the following:
event: 'dashboard-navigation'
dashboard-action: 'view-link'
dashboard-product: 'view-manage-va-debt'

After you implement the code let me know and we can test.

**Comment by ajakabcin** [comment]
Hi @michelle-dooley thanks for this - yes you're right the only _new_ tracking we need to add here is on the "Manage your VA bills" seen in[ this sketch file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/rb3RzvK) on the Copay card

Does that still align with your guidance above? Thanks!

**Comment by michelle-dooley** [comment]
Here is what you need for that one....

event: 'dashboard-navigation'
dashboard-action: 'view-link'
dashboard-product: 'view-manage-va-bills'

**Comment by ajakabcin** [comment]
Thanks @michelle-dooley and then I think because we're going from one section ("Benefit payments and debts") to two sections ("Outstanding debts" and "Benefit payments"), I think, per your [comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48598#issuecomment-1292307869) we just need to update the existing tag on the "view manage va debt" to indicate it's from the Outstanding debts section, correct?

So our work would be:

1. Implement tagging on "Manage your VA bills" link (within copay card) using 
> event: 'dashboard-navigation'
> dashboard-action: 'view-link'
> dashboard-product: 'view-manage-va-bills'

2. Update tag on "manage va debt" link (within debt card) to 

> event: 'dashboard-navigation'
> dashboard-action: 'view-link'
> dashboard-product: 'view-manage-va-debt'

**Comment by michelle-dooley** [comment]
Ok so let me make sure I am following you (you are confusing me a bit with the copay card and debt card).  The 3 links circled are the 3 you need tracking on with the ability to know which is which, correct?  Are there any of these links in other sections that I am missing?

**Comment by ajakabcin** [comment]
Sorry about that! I’ll swing by office hours today so we can talk through it :)

**Comment by michelle-dooley** [comment]
@ajakabcin - just checking in on this, you should have everything you need.  Just let me know once you implement the code and I will test.

event: 'dashboard-navigation'
dashboard-action: 'view-link'
dashboard-product: 'view-manage-va-bills'

event: 'dashboard-navigation'
dashboard-action: 'view-link'
dashboard-product: 'view-manage-va-debt'

**Comment by ajakabcin** [comment]
Hey @michelle-dooley - thanks for checking in and apologies for the delay. We have this slated for our current sprint (started yesterday). We'll ping you when we're ready for testing. Thank you!

**Comment by ajakabcin** [comment]
@michelle-dooley - @ericasauv09 confirmed today she's seeing click tracking flow through on the prod dashboards. Closing this out - thanks again for your help!

**Comment by michelle-dooley** [comment]
@ajakabcin, @tmitchellgcio @ericasauv09 - The events are showing in the GA, everything is working as expected.  Unless you need anything else I plan to close this ticket.
https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p184600834/_u.date00=20221107&_u.date01=20221114&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventLabel:dashboard-navigation/
![image](https://user-images.githubusercontent.com/93597659/201981980-bdf4e5ad-82cb-4b81-b4ac-dbb2d93523a8.png)
