### ISSUE TITLE
Add app version tag to Sentry events

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#486]
## User Story
As a VSP / VSA front end engineer, I need to know what version of the app was running when an error occurred so I can determine whether a fix I already made worked.

## Goal
Users may be using an outdated version of the front end code at any given time. I want to know if new events on an issue come from the outdated version, or the one that should have the fix in place.

## Acceptance Criteria
- [ ] A tag is assigned to every event that can be tied to a release

**Comment by cvalarida** [comment]
There's a fair amount of uncertainty here, so I set the estimate on the higher side.

- How can we tie the tag to a release (deploy) from within the code?
  - Poking around in `.git/` for a commit hash?
  - Using the cache-busted JS bundle name?
    - I think the cache busting uses a timestamp, so it's sorta loosely tied to a release
- How can we get this information to the Sentry init code?
  - Something something metalsmith, but... :man_shrugging: 
  - It'll take some experimentation
- How will this affect non-production builds?
  - Do we skip this for localhost since we won't necessarily have a commit and probably don't care anyhow?
- How do we test that it works?
  - Something something Sentry Testkit, but I'm not totally sure _how_ yet

**Comment by timwright12** [comment]
Closing due to age and since Sentry is being evaluated right now
