### ISSUE TITLE
Analytics Implementation or QA Support for [MHV Secure Messaging on VA.gov] - In Progress

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#48627]
**This ticket is still in progress and being filled out by the MHV Secure Messaging team**

# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>The intent of this ticket is to share our plans for Analytics and to seek feedback on the implementation and measurement strategies to capture the necessary metrics.  

Secure Messaging on VA.gov will provide Veterans with the same ability to securely contact their VA health care providers as on MyHealtheVet (MHV) today The new application will employ modern technology and user-centered design to ensure that the tool is accessible, straightforward, and simple to use. Moving this product out of MyHealtheVet and into the VA.gov landscape will also provide a more seamless and consistent experience than was possible on two distinct web sites.</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - Q1 2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]

URLs of the application (all have the root path of /my-health/secure-messages/).  Seeking guidance for helping set up 'paths'.
/ - Authenticated landing page/Inbox
/faq - F.A.Q. page
/folders - Clicking on “My Folders” in the navigation bar brings you to the Folder Management page
/compose - Clicking the “Compose” link in the navigation bar or the “Compose message” link on the Inbox page brings you to the Compose Message page.
/message/:messageId - Clicking on an individual message link in a folder list view brings you to the Message Details page
/reply - Clicking the “Reply” button in the Message Details page brings you to the Reply page
/search - Clicking “Search messages” in the navigation bar brings you to the Basic Search page
/search/advanced - Clicking the “Advanced Search” link on the Basic Search page brings you to the Advanced Search page
/search/results - Performing a search brings you to the search results page
/draft/:draftId - Clicking on an individual message link in a folder list view brings you to the Draft Message Details page
/sent/:messageId - Clicking on an individual message link in a folder list view brings you to the Sent Message Details page
/trash/:messageId - Clicking on an individual message link in a folder list view brings you to the Trash Message Details page
/sent - Clicking “Sent” in the navigation bar brings you to the Sent Messages page
/trash - Clicking “Trash” in the navigation bar brings you to the Trash page
/drafts - Clicking “Drafts” in the navigation bar brings you to the Draft Messages page
/folder/:folderId - Clicking on a specific folder in the Folder Management page brings you to the list of messages in that folder

    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Use user 1 (MHV login) at https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/a71afbc4bed16476d1fea492471a077e29a265b2/teams/sm/test-accounts.md

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@bryan-riley-va - can you please provide details on this request and what you need implemented.  Urls and screen shots are great.

**Comment by bryan-riley-va** [comment]
@michelle-dooley we are still putting that all together and I'll get those into the ticket asap

**Comment by michelle-dooley** [comment]
@bryan-riley-va - I'm going to put this in our icebox, let us know when you are ready to pick it back up.

**Comment by michelle-dooley** [comment]
@bryan-riley-va - I'm trying to walk through the flow.  Is this how I get there (see screen shot below)?  I've also tried going through the My Health tab at top right but each way I try I keep getting "This site can't be reached" error?

![image](https://user-images.githubusercontent.com/93597659/201984822-3f1c960f-c07d-4629-bf8c-79fc23424708.png)

**Comment by michelle-dooley** [comment]
@bryan-riley-va - just following up on my questions above...

**Comment by michelle-dooley** [comment]
[mhv sm custom components.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10355617/mhv.sm.custom.components.xlsx)

**Comment by michelle-dooley** [comment]
@bryan-riley-va and @oleksii-morgun-va - follow up to our slack convos, I updated the worksheet with more comments after your responses Oleksii.  Adding here for tracking purposes. 
[mhv sm custom components .xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10461468/mhv.sm.custom.components.xlsx)

**Comment by michelle-dooley** [comment]
The tagging work is complete.  Please reach out if you have any questions.
