### ISSUE TITLE
Staging Review [MHV Secure Messaging in VA.gov] - In Progress

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#48629]
**This ticket is still in progress and being filled out by the MHV Secure Messaging team**

# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [ ]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [ ]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.
- [ ]  Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)

 **Platform**
 
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [X] Staging URL and staging test-user information
-URL: https://staging.va.gov/my-health/secure-messages/
-Test User/Credentials: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/7ab689ee294f3a6bd4b853b994a874d5c6bd2cdf/teams/sm/test-accounts.md

- [ ] Product outline 
 https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/product

  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Your product’s content source of truth
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  

### Accessibility artifacts 

- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman

**Comment by shiragoodman** [comment]
@bryan-riley-va sorry! typed this out yesterday and never commented.

Do you know if your team completed a Midpoint Review for Secure Messaging? I was able to find the [Design Intent ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41827), but I don't see anything after that. Please let me know.

**Comment by bryan-riley-va** [comment]
Hi Shira - we did not go through midpoint review as we were in usability testing at the time and wouldn't have the artifacts which would have pushed back the timelines.  At that point our team was new and the test cases had also not been written.  I confirmed with Marci M and she had recalled some conversations about being able to bypass midpoint review.

**Comment by shiragoodman** [comment]
@bryan-riley-va Marci is correct. You can skip Midpoint Review, but I just wanted to check and confirm I wasn't missing anything. Please follow the instructions above when you're ready to schedule this Staging Review. Thanks!

**Comment by shiragoodman** [comment]
@bryan-riley-va any update on this? We'd like to get something scheduled soon if your team is ready

**Comment by bryan-riley-va** [comment]
@shiragoodman we have different tasks assigned for all the artifacts and we are still moving through filling out the relevant info.  We are working through this one, the Analytics ticket, Contact Center, and also the Security/Privacy.  Is there any mandatory order we must do them in?

**Comment by shiragoodman** [comment]
@bryan-riley-va no, there is no mandatory order. If you have questions about the timing of each touchpoint, check out the different [Touchpoint pages on Platform Website. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints) On the left navigation pane, select the touchpoint you have questions about and there is a "Timing" section with our expectations around when each review should be held. 

Let me know if you have any questions.

**Comment by MarciMcGuire** [comment]
@shiragoodman cc @bryan-riley-va in a recent meeting, some members of the MHV tea asked if they can request a midpoint review after the fact.  Since this is their first pass through the collab cycle, they would like an opportunity to get feedback before Staging review.   Our previous PO opted to skip it to hit a date for starting prototype testing, but the team would like to have one if that is possible.

**Comment by shiragoodman** [comment]
@MarciMcGuire @bryan-riley-va totally fine with us. Just keep in mind, the Midpoint Review is not as thorough as Staging. We don't complete any accessibility testing at Midpoint Review. It's designed to be a check-in touchpoint before VFS teams complete usability testing with veterans, but it can happen whenever. 

Let me know if you have any other questions.

**Comment by bryan-riley-va** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/51115

Replaced by ticket above
