### ISSUE TITLE
Facility Locator implementation of Health Service Taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4864]
## High Level User Story
As the Facility Locator team, we need to implement the health services taxonomy so our consolidation of other locators will be more efficient.  

## Hypothesis or Bet
**If** we implement the health service taxonomy **then**:
- We expect our users to have a better search experience for health related facilities and services.  
- We expect our consolidation of health related locators to be easier. 

## OKR
- User satisfaction
- Consolidation of legacy facility locators 

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by davidconlon** [comment]
[https://app.zenhub.com/files/133843125/19f342b9-42fe-45cf-9227-07acf7fb87e6/download](https://app.zenhub.com/files/133843125/19f342b9-42fe-45cf-9227-07acf7fb87e6/download)
