### ISSUE TITLE
EKS Testing Concerns

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#48648]
# Problem Statement

## Problem 1 - Param store values
We should create tests to ensure the most critical values, between BRD and EKS, are in sync. As we are in a migration state from BRD to EKS, both deployments exist simultaneously. We currently have an [alert via GHA ](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/k8s-settings-prompt.yml) that triggers anytime a -env*-settings.yml file is updated, which alerts the developer to update the corresponding configmap in the manifest repo. This alert isn't a catch all, and needs to be either improved upon OR we should create something more automated.

## Problem 2 - Test data
As we migrate to EKS, we should create functional tests to ensure vets-api endpoints are behaving as expected. One major pain point related to testing is the state and limitations of available test data. The vets-api server environments are vastly different.. e.g. dev returns mocked responses, prod has no test users, etc.

If calling out to external services, will we need to have the data in a certain state? Is this data available. Do external services have test data for us to work with? Could we mock the data and use it for testing purposes? 

It's also to our knowledge that for example, staging is connected to pre-prod environments (in terms of external services), so how can we be confident that if a tests passes in staging, that it will also pass in prod?

Testing ideas: Datadog synthetic tests, insomnia/ or postman, pact (could be useful for mocking external services calls)

# Definition of Done
- [ ] Documentation of next steps with SA/PO
- [ ] .....

**Comment by laineymajor** [comment]
@LindseySaari I'm going to place this as 'in review'... just wanted to check with you before I close this. I think everything in this ticket is captured elsewhere. If so, I'll go ahead and close. Let me know your thoughts.

**Comment by LindseySaari** [comment]
> @LindseySaari I'm going to place this as 'in review'... just wanted to check with you before I close this. I think everything in this ticket is captured elsewhere. If so, I'll go ahead and close. Let me know your thoughts.


Yes, go ahead and close!
