### ISSUE TITLE
VBA taxonomy (Veteran facing labels) for Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4865]
## High Level User Story
As the Facility Locator team, we need to work with the VBA to create a system of Veteran facing labels so our consolidation of other locators will be more efficient.  

## Hypothesis or Bet
**If** we create a system of Veteran facing VBA labels **then**:
- We expect our users to have a better search experience for benefit-related facilities and services.  
- We expect our consolidation of benefit-related locators to be easier. 

## OKR
- User satisfaction
- Consolidation of legacy facility locators
 
### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by davidconlon** [comment]
A-Z Service Listing as of 7/20/2020

https://dvagov-my.sharepoint.com/:x:/g/personal/david_conlon_va_gov/EW32mUPq0kNJlJGOy4flS4EBjw6zKLn9E5U0Wnrd8Y1F3w?e=BHdi7d

**Comment by dsinla** [comment]
Closed - Over a year old and not considered urgent or high impact. Will be accounted for in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9659
