### ISSUE TITLE
Midpoint Review - IA Feedback - [Authenticated Experience, My VA, Audit UX Improvements] #42601

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#48667]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
* Some sections have “Manage your _____” embedded in the card template, but other sections have it sitting outside the card (also varies on Desktop whether it is in the right vs. left column). Use fixed logic around what appears where, so that the IA experience is consistent across all sections. 
* Move “What benefits does VA offer” external link from under the “Saved applications” area - this is unrelated. Work with site-wide content & IA to find a page location that is a better fit.
* In [this sketch file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/9P240Kn) showing loading problems on MyVA Page, we send people externally to My HealtheVet. Ensure users will be able to navigate back to MyVA.

**Consider:**
* Authenticated users see “Saved applications” as H1 section header. For the same section, unauthenticated users see “Apply for VA benefits.” Since we are saving in-progress forms for unauthenticated users, can we use the same language across both?

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by ajakabcin** [comment]
Hi @sterkenburgsara! Under the Consider feedback you wrote

> Authenticated users see “Saved applications” as H1 section header. For the same section, unauthenticated users see “Apply for VA benefits.” Since we are saving in-progress forms for unauthenticated users, can we use the same language across both?

Did you mean LOA3 vs LOA1 instead of authenticated users vs unauthenticated users? Unauthenticated users can't access My VA at all, they're immediately prompted to log in. Thanks!

**Comment by sterkenburgsara** [comment]
@ajakabcin Ah, forgive me, I am only a few weeks into this role and still learning the various user states & acronyms. Peeking back at the wireframes, yes - I am referring to the [LOA1](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/padQ1OG) vs. LOA3 user types.

**Comment by ajakabcin** [comment]
@sterkenburgsara No need to apologize! Just wanted to make sure we understood the states you were referring to. Thanks for clarifying!

**Comment by ajakabcin** [comment]
I believe the concerns raised have been addressed - closing
