### ISSUE TITLE
Remove search best bet for 1990N form

### ISSUE THREAD

**Issue by heyjoni** [department-of-veterans-affairs/va.gov-team#48663]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [ ] NEW: You would like to create a new best bet
    - [x] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @denisecoveyduc  and @John Hashimoto

# Section 1: New Request

### Description

        > description

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > date/time
 
 ### Please provide the following information:

 - [ ] Specify the **Headline** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

> Example: Get information about the COVID 19 vaccine from your local VA facility_

        > enter headline
 - [ ] Specify the **Text** for the Best Bet *(@DanielleThierryUSDSVA or @bethpotts)

> Example: Get the latest updates about COVID-19 vaccines at your nearest VA facility._

        > enter text

 - [ ] Specify the  **Keywords** that would generate the Best Bet*(@DanielleThierryUSDSVA or @bethpotts)

> Examples: covid vaccine, covid vaccine availability, vaccine availability, etc._

        > enter text

 - [ ] Specify the **URL** for the Best Bet (@davidconlon )

> Examples: https://www.va.gov/find-locations?facilityType=health&serviceType=Covid19Vaccine_

        > enter url
       

# Section 2: Change Request

### Description
*Per #48280 the team is no longer accepting online 1990N forms. Searches for "1990N", "1990" and "form 22-1990" are turning up the online form so we will need to remove it from these search best bets: (https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction/) 

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
This week if possible. Removing references to this form is already in progress. 
 
 ### Please provide the following information:
 - [x] Identify the Best Bet requiring changes
*1990n
*1990
*form 22-1990
        > associated best bet
- [ ] Specify the change(s) that are required.  
Remove https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction/

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: These requests are handled by the Search & Discovery  Team. Reach out via Slack #va-search with any questions.*** 

#### Acceptance Criteria
- [ ] Add this request into a Zenhub Epic
- [ ] Follow-up with requester to address any lingering questions/concerns
- [ ] For new Best Bet: Setup, test and validate the Best Bet in Production via the Search.gov dashboard (@johnhashva)
- [ ] For Best Bet Changes: Alter Best Bet via the Search.gov dashboard, test and validate (@johnhashva)

#### Definition of Done

 - [ ] Request has been implementation and live on production

**Comment by denisecoveyduc** [comment]
@mnorthuis looks like we need to update the template.. still shows John and I as primary contact for best bets.

**Comment by mnorthuis** [comment]
@heyjoni The best bet for the 1990n that was directing visitors to the online form has been removed.  It was an older best bet and there is an additional one that directs visitors to the find a form landing page that is still live.  

@denisecoveyduc I will work with @heyjoni to update this template. Sorry for the noise!
