### ISSUE TITLE
Link to confluence

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#48668]
[Current Forms Library Audit: Features, definitions, components, fields](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2031812688/Current+Forms+Library+Audit%3A+Features%2C+definitions%2C+components%2C+fields+-+FLT) on [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) links to confluence. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview

**Comment by laucon** [comment]
Hi @andreahewitt-odd Just letting you know that our team has seen this. We will work on trying to figure out the best alternative link or wording to use instead of the confluence link. Thanks for bringing this to our attention. :)

**Comment by laucon** [comment]
@andreahewitt-odd I think the content team needs an answer or a general guideline: is it bad if any Pltform website docs link to confluence? Because you had the issue with [this link](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2031812688/Current+Forms+Library+Audit%3A+Features%2C+definitions%2C+components%2C+fields+-+FLT), but the page also links to [this confluence doc](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2280161283/VA+Forms+System+Core+VAFSC+Work+Stream+-+FLT) and [this confluence doc](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2042200279/What+is+a+Form+-+FLT). And if those confluence docs are ok to link to, what makes them different from [this confluence doc](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2031812688/Current+Forms+Library+Audit%3A+Features%2C+definitions%2C+components%2C+fields+-+FLT) that seems to pose a problem?

**Comment by laucon** [comment]
After talking to Vicky, I think it would be best to get rid of all the links to confluence docs. I think there are 3 main steps to doing this for this document:
1. Change:
 "If you are looking for information about the VA Forms System Core (VAFSC - the next generation version of the Forms Library), details about the current development status of the package can be found on the [VAFSC Work Stream page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2280161283/WIP+VA+Forms+System+Core+VAFSC+Work+Stream) and the [VA Forms System Core Docs page](https://department-of-veterans-affairs.github.io/va-forms-system-core/)."
 to
If you are looking for information about the VA Forms System Core (VAFSC - the next generation version of the Forms Library), you can find details about the current development status of the package on the [VA Forms System Core Docs page](https://department-of-veterans-affairs.github.io/va-forms-system-core/).

2. Delete the sentence:
If you'd like a deeper look into “What is the Forms Library” you can take a look at this audit for details about definitions, functions, widgets and more of the Forms Library. [Current Forms Library Audit: Features, definitions, components, fields](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2031812688/Current+Forms+Library+Audit%3A+Features%2C+definitions%2C+components%2C+fields+-+FLT)

3. Change:
"To determine when to use the Forms Library please refer to the [What is a Form](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2042200279/What+is+a+Form+-+FLT) page, which describes what a “Form” is inside of the Forms Library."

to 

"To determine when to use the Forms Library use the guidelines listed below:"

4. Add this text to the bottom of the section "When should the Forms Library be used?"

"**What is not a Form?**

    A search bar

        Submit and data goes somewhere but it isn’t saved for later

    Login

        Authorization and can be submitted more than once

    CRUD

        Create, Read, Update, and Delete interface / system that can be continuously updated

        You can personally maintain in an ongoing fashion

        Example: profile page, preference settings

    VA hospital finder - using forms library to find now but is really a search function

    Note that not all forms applications are using the current forms library:

        VAOS scheduling

        VA forms (checkin, et al)"
        
    5. Change
    "After reviewing the [What is a Form](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2042200279/What+is+a+Form+-+FLT) page and determining that your use case does NOT fit the definition of a form (ex. Search bars, login pages, CRUD, etc), then we suggest you take a look into the Design System elements and components to see which of these could be useful. Here are some helpful links to get you started."
    
to

"After reviewing the guidelines in the above section, and determining that your use case does NOT fit the definition of a form (ex. Search bars, login pages, CRUD, etc), then we suggest you take a look into the Design System elements and components to see which of these could be useful. Here are some helpful links to get you started.

**Comment by laucon** [comment]
I'm letting everyone know that Nick Sprinkle and Tricia Baker checked and approved my edits, so I'm going to publish the edits on Monday. yay!

**Comment by laucon** [comment]
Since I'll be deploying at 3:30 today, I'm going to close this ticket.
