### ISSUE TITLE
Keyboard testing helper: Follow up with Platform SME

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#48662]
Tasks:

- [ ] Follow up with Platform SME (Peter Hill, Joe Tice) regarding this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46964

**Comment by taylojill** [comment]
Hi @pjhill  Let us know if we can assist in any way.
cc @vbellissimo

**Comment by taylojill** [comment]
10/24/2022 - Follow-up message sent to Peter Hill.
