### ISSUE TITLE
Implement an authentication event API for fraud detection

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#4868]
## User Story or Problem Statement
As the VBA fraud detection team, I need to query VA.gov for the history of authentication events related to a specific user or IP address, so that I can investigate claims of fraud related to payments. 

When VBA receives a complaint of fraud (e.g. a veteran's benefit payment direct deposit being changed without their consent),  they need to assemble an audit record of online interactions so that they can assess and investigate the complaint. They already have access to some data:
* They can see when payment information was changed in various VBA systems, and retrieve an ICN for. the affected user.
* They can see records of SSOe and DSLogon authenticaiton events. For SSOe in particular, they have access to IAM's Splunk instance.
* They newly have the ability to query an event log API provided by ID.me that lets them  retrieve events for a given IP address or UUID. That API is described here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/fraud-team/idme-event-and-logging.md

Currently VBA does _not_ have access to any VA.gov authentication data. 
Initially, we thought that they only needed a mechanism to link ICNs to UUIDs so that they could link the ICN they had to the UUID needed to invoke the ID.me API mentioned above. This work was described in #3592 

After further discussion, VBA would prefer to have an internal API that provides the history of sign-in events for VA.gov users. The key properties of this API:
- They can easily consume a RESTful JSON API protected by an API key.
- They want to be able to query by user's ICN and retrieve a full history of events for that user. Because of law enforcement requirements, they need "as full a history as possible", i.e. we can't just retain a small amount like the last 30 days of records. However they are aware that VA.gov may have its own ATO-based record retention policy to abide by. 
- They also want to be able to query by a source IP address and retrieve all events associated with an IP.
- This needs to be a real-time API that their system can invoke; fraud investigations are frequent enough that any manual process (e.g. requesting logs from operations team) will not be able to keep up.
- The exact content of the API is not specified by VBA, but should at a minimum contain the ICN, UUID, timestamp of authentication and IP address. Following the ID.me API as a guide, we likely also want to differentiate different session events (login vs. logout) and likely also want to record the AuthnContext and/or credential type that was used.

## Concerns
- Since direct deposit is live, VBA is already receiving fraud complaints and has outstanding cases of changes on VA.gov needing investigation. So time is of the essence.

- Any solution that involves retaining records of these events for a long period of time needs careful capacity planning to ensure the repository (database or otherwise) is not exhausted, and an eventual plan for either deletion or cold-storage of these records. 

## Proposal 1
1. Begin recording authentication events to RDS
2. Define an JSON API endpoint (likely under the `/services/openid_auth` module that is used elsewhere for internal authentication use cases) that satisfies the above stated requirements (query by ICN, query by IP address, unbounded retention likely with pagination)
3. Configure the Lighthouse API gateway to expose this endpoint, and issue the VBA team an API key. (Note I am proposing that as a VA.gov requirement, a VA.gov team implement this but do so using the Lighthouse API gateway as an access control mechanism)

## Proposal 2
We discussed propagating event data into an existing VA instance of Splunk . VBA has successfully used Splunk as a datasource and should be capable of querying it. There is a VAEC-wide Splunk instance, but discussion with the SRE team suggested that provisioning access across multiple AWS accounts would be challenging. 

**However**, VA.gov could potentially use a system like ElasticSearch that exists within our own AWS VAEC environment. We have prior art for forwarding selected logs entries to ElasticSearch and making them queryable/deriving metrics from them. If it appears feasible for VBA to query this source within our AWS environment, then this work would largely devolve to (a) making sure events are logged with sufficient detail in a well-defined format and (b) configuring the CloudWatch -> ElasticSearch filter

**Comment by patrickvinograd** [comment]
Tagging a few people to poke holes at this:
@wyattwalter @annaswims @kfrz @wunderhund @kalilsn @dvogel

**Comment by patrickvinograd** [comment]
Discussion on 1/17 with @annaswims and @wyattwalter, we had consensus that the elasticsearch approach (roughly Proposal 2 above) would be lower-lift.

- Log authn events with sufficient detail (including uuid/ICN/IP/timestamp/authncontext) to a separate audit log, in Cloudwatch.
-  Forward those entries to a new elasticsearch  instance
- Give access  to VBA to elasticsearch either directly via AWS or via  the API gateway with an API  key protecting  it.

**Comment by dvogel** [comment]
I think the suggestions from your meeting with Anna and Wyatt are sensible. From the Lighthouse angle, I would say definitely don't build in `openid_auth` because Lighthouse is trying to separate from VSP in some ways and this is likely moving out of vets-api. More generally, is there room for a 3rd proposal where the new position of IAM within the VA.gov login would allow the ICN to be attached to the SSOe events already in the IAM splunk instance?

**Comment by patrickvinograd** [comment]
@dvogel Yes, integrating with SSOe should largely obviate this whole issue, since VBA can presumably fetch those events/correlations from IAM splunk. So this is largely a stopgap measure.  

Now we may want to have VA.gov-centric audit logging for our own purposes but that might now have the same requirements/constraints.

**Comment by charwo** [comment]
I would be curious in hearing more thoughts about the proposal to push our logs into one of VA's existing Splunk instances (VAEC's, or there is one run by CSOC/NSOC). It would seem to me that could save a lot of custom development work if it were possible. Do folks agree that this is a preferred approach? If so, it would be helpful to learn more about what the blockers are.

**Comment by wyattwalter** [comment]
Those Splunk installations aren't built/staffed to be like "logging as a service" for the agency. They aren't not being operated in a way that allows for general purpose writing to and reading from for development teams around VA. They purpose-built for the specific departments that need access to that data to receive it. If the Fraud team is housed under the Cybersecurity (CSOC) arm and already has access to one or both, then it could make sense for us to send that data along. If not, then there's no way for them to query it once we ship the logs there. I don't remember where I heard this specifically, but I've heard that they definitely don't want application logs shipped to them just for the sheer volume of data they'd have to support.

**Comment by patrickvinograd** [comment]
Closing this one out.

The identity team gave the fraud detection team access to cloudwatch and mechanisms to do the needed queries via Athena. They seem to have what they need.

Additionally once we are 100% on SSOe login they should be able to derive all the info they need from IAM Splunk logs.
