### ISSUE TITLE
[10/29/22] VEText/AVS Tier 3 Escalation Guide

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#48694]
## Description
To onboard the VNCE Tier 3 team and make escalation of additional issues for VEText and AVS as seamless as possible, the VEText and AVS helpdesk team has been tasked with creating a guide of what is often escalated to Rob, now Tier 3
---

## Acceptance Criteria

- [x] Create draft
- [ ] Review with Team
- [ ] Approved by Justin/Lindsay
---

**Comment by manalo-soco** [comment]
@chancetheoriginal  When you can pls past the link to the SOP draft here

**Comment by lindsay-insco** [comment]
Completed!
