### ISSUE TITLE
[FE] Add GA Events for Travel

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48703]
## Tasks
- Add the new API events & Yes/No clicks for travel questions to the spreadsheet
- Add the new events to the dashboards?

**Comment by benbrasso-agile6** [comment]
- Added events to [spreadsheet](https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=0)
- Engineers will add two more for additional API responses 
- Have not added to dashboards yet

**Comment by benbrasso-agile6** [comment]
https://analytics.google.com/analytics/web/#/dashboard/1iHzB1FJTq6wHfngzN0LQg/a50123418w177519031p176188361/_u.dateOption=last7days/

Added widgets for travel into GA dashboard. Once FE finishes their additional ticket, I may need to adjust the filters.

**Comment by benbrasso-agile6** [comment]
Moving to closed
