### ISSUE TITLE
AWS access for Matthew Christianson

### ISSUE THREAD

**Issue by mchristiansonVA** [department-of-veterans-affairs/va.gov-team#48702]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Matthew Christianson

### Your Email

matthew.christianson@adhocteam.us

### Team, Role, and Company of the target individual

Dash on Lighthouse, Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Kayla Watanabe, kayla.watanabe@va.gov

### Product Owner (PO) name and email

Janet Coutinho, Janet.Coutinho@va.gov

### Desired AWS Access

Please copy same permissions as teammates Jennica Stiehl, Jeff Wallace.

### Access Expiration

Ongoing

### Additional Notes

I need this access for ongoing development work on the Benefits Claims API.

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by FonzMP** [comment]
User is on the VFS Team Roster.

Please let us know if you need any further details from our end.

**Comment by FonzMP** [comment]
Anything we need to do to get this moving forward?

**Comment by FonzMP** [comment]
hey @ianhundere, does `Awaiting Approval` require anything from our end (Team Dash)? Just want to make sure you're not waiting on us. - Thanks!

**Comment by ianhundere** [comment]
no, y'all are good. the awaiting approval tag is for the approver(s).

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Approved

**Comment by ianhundere** [comment]
creds sent
