### ISSUE TITLE
[Spike] Incorrect Claims Data Showing

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#48700]
## Spike open question: 

Why are the values in eBenefits different form CST? 

## What happened?
A Veteran and VA employee states that his claim data on the VA.gov claims status tool is showing differently than it should. In particular, he states that on eBenefits and the disability ratings page the information is correct but on claims status tool it is incorrect. Specifically the claimed condition of Prostate Cancer (correct) was changed to Prostate injury (not correct). Also Degenerative Spurring, Spine (correct) was changed to Lumbosacral or Cervical Strain (not correct). Attached to this issue is a document where the differences between ebenefits and VA.gov are highlighted in corresponding colors. 

## Specs:
- Device: All devices
- Browser: All browsers

## Steps to Reproduce
- URL: https://www.va.gov/track-claims/your-claims
[eBenefits vs VAgov.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9861736/eBenefits.vs.VAgov.docx)
[VAgov Disabilty Ratings URL.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9861815/VAgov.Disabilty.Ratings.URL.pdf)

## Desired behavior
The Veteran would like to see the condition names to match what is shown on ebenefits. 

## Acceptance Criteria
- [ ] 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by saderagsdale** [comment]
@jacobworrell Matt flagged this for review. I can bring you up to speed when you return tomorrow.

**Comment by jacobworrell** [comment]
@saderagsdale we'll take a look into this. Curious why the data looks different between the two systems. I would think the values would be the same if ultimately they're looking at values written by VBMS into Corp DB, but obviously things aren't getting mapped the same. 

@clantosswett it's difficult to say when this bug will get resolved, especially if this sends us down a big rabbit hole. What does this veteran actually need at this time? We shouldn't build an expectation that a bug like this gets fixed immediately. If the veteran needs precise documentation showing his ratings decision, there should be a way to provide that documentation without relying on the bug fix. Just want to make sure the individual gets what they need while the solution is in progress.

**Comment by clantosswett** [comment]
@jacobworrell thanks for this information. This bug came from a VA employee with a number of other stakeholders interested in why this was happening. So there isn't necessarily an urgency to fix this because the user is blocked, but I think more concern why there would be a discrepancy. I can certainly relay back the information and let them know there isn't likely to be an immediate fix. 

When you say the veteran should have access to other documentation that has the conditions listed correctly, where would he find that? Would it be in his benefits letters or elsewhere?

**Comment by jacobworrell** [comment]
@clantosswett Hi there, following up here, we haven't been able to track down why this data discrepancy. I'm wondering if EVSS knows why the contention mapping might have changed from what's displayed in eBenefits to what's currently displayed in CST. They own the service currently providing those values.
