### ISSUE TITLE
[FE] [Bug] Update authentication error message for date of birth (CI and PCI)

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#48721]
## Description
Update the infobox text to "We’re sorry. We couldn’t find an account that matches that last name or date of birth. Please try again." 

## Wireframes
- [Anstract](https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b?collectionLayerId=a2391179-643f-4a54-8c5f-737ff2d362dd&mode=design) 
- NOTE: The following is a screenshot of the Sketch file at the time this ticket was created, if the screenshot differs from the Sketch file when this ticket is worked, please raise the issue with the team during stand up

  - **_insert screenshot of Sketch file that shows the work to perform in this ticket_**

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Judging from other similar strings, it could be as simple as turning the `,` to a `.` then capitalizing the next word to start a new sentence, but I didn't want to make assumptions on the other languages.

**Comment by brianseek** [comment]
@loripusey makes sense, I'll make that update. How do you feel about doing that with Tagalog? We have this sentence in there `We’re sorry. We couldn’t match your information to our records. Please ask a staff member for help.` and it translates to `Paumanhin. Hindi namin maitugma ang iyong impormasyon sa aming mga rekord. Mangyaring humingi ng tulong sa isang staff member.`

Seems like `Paumanhin. Hindi namin mahanap ang account na tumutugma sa apelyido o petsa ng kapanganakan. Mangyaring subukang muli` would be correct.

**Comment by loripusey** [comment]
Seems correct according to an on-line translator.
![image](https://user-images.githubusercontent.com/86678742/200646322-9fee8ae1-ed9b-4cf5-bd5b-77961a065c95.png)

**Comment by brianseek** [comment]
ok, I'll add that update too!

**Comment by brianseek** [comment]
@loripusey / @zach-park This is merged and will be ready to validate shortly. See screenshot below as well:![Screen Shot 2022-11-07 at 2.43.32 PM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/73934027-a37c-4442-9663-30c851c6e7c0)

**Comment by zach-park** [comment]
LGTM. Thank you!
