### ISSUE TITLE
Initial changes to be pushed for Urgent care MVP

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4872]
This issue represents the initial MVP content to be pushed to Production. Changes specific to urgent care will be held pending user research and input from the Office of Community Care. 

## User story
As a veteran, I need an updated UX experience so that I can easily locate a facility to meet my needs.

## Objectives or Key Results this is meant to further
- Improve the Veteran Search Experience (Veterans have the information they need to be prepared for an urgent care visit. )
- Reform Community Care Implementation

### Search functionality

[ ] Search functionality will use new 2 row stacked design (as in prototype and in images attached)
[ ] Search boxes are stacked with search button at the bottom in mobile version
[ ] User **MUST** enter city, state, zip, unless user has allowed browser location
[ ] Under _Choose a VA facility type_, the user can select one of the following from the dropdown
> VA health
> VA Community Care (In network)
> VA benefits
> VA cemetery
> Vet Centers

[ ] Wording at the top has changed and should reflect what is displayed in prototype. The following are exceptions and will remain: 
  - _Need same-day care for a minor illness or injury? Search for your nearest VA health facility. Or find VA-approved urgent care locations and pharmacies near you.
  - _Can’t find what you’re looking for? Try using our other tools to search.

![image](https://user-images.githubusercontent.com/55411834/72839020-5d5d6300-3c46-11ea-9626-a50839eb250c.png)

[ ] Items in the VA facility type dropdown should not have icons.

[ ] When VA facility type = VA health, the _Choose a service type_ dropdown defaults to _All VA health services_
[ ] When VA facility type = VA health, the user can select one of the following from the _Choose a service type_ dropdown
> Urgent Care
>     Emergency Care
>     Primary Care 
>     Mental Health Care
>     Dental Services
>     Audiology
>     Cardiology
>     Dermatology
>     Gastroenterology
>     Gynecology
>     Ophthalmology
>     Optometry
>     Orthopedics
>     Urology
>     Women's Health

[ ] Assistive device users are prompted to enter a value for "service type" when _VA health_ is selected.

[ ] When VA facility type = VA benefits, the _Choose a service type_ dropdown defaults to _All VA benefit services_
[ ] When VA facility type = VA benefits, the user can select one of the following from the _Choose a service type_ dropdown
> Applying for benefits
> Burial claims
> Disability claims
> eBenefits registration
> Education and career counseling
> Education claims
> Family member claims
> Help for homeless Veterans
> VA home loans
> Insurance claims and financial counseling
> Integrated disability evaluation system (IDES)
> Pensions
> Pre-discharge claims
> Transition
> Updating direct deposit information
> Vocational rehabilitation and employment (VR&E)

[ ] Assistive device users are prompted to enter a value for "service type" when _VA health_ is selected.

[ ] When VA facility type = Vet Centers, the _Choose a service type_ dropdown is inactive. 

[ ] When VA facility type = VA cemeteries, the _Choose a service type_ dropdown is inactive. 

[ ] When VA facility type = VA Community Care (In network), the _Choose a service type_ dropdown is required to be populated by manual input with the existing service options. 
[ ] Existing service type list is maintained.
[ ] Placeholder text should not disappear when the "Service type" input receives or loses keyboard focus.
[ ] The type of services to be added needs to be included in the label or as descriptive text, as specified in WCAG guidance.
[ ] Assistive device users are  prompted to enter a value for "service type" when VA Community Care (In network) is selected. 
 ] Service Type field shows a clearly marked error message (_Service type not found_) when the field resets to default or user has entered data incorrectly. [#489] 
[ ] Error is read aloud when the Service Type field is reset to default or an assistive device user has entered data incorrectly. [#489]

![new search design.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/1137d2ac-faf8-4b14-bfc9-52a683c193d2)

![facility type dropdown.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c5267796-77ba-46bb-8ca6-d42927f548df)

### Results map and list acceptance criteria

[ ] When Veteran clicks on a map location, the corresponding card is highlighted.
[ ] Facilities are marked with icons/pins on the map. 
[ ] The number of search results displayed in the list should be consistent with the number displayed on the map [#2701]
[ ] Map does not display pop-up/hover over information.
[ ] 20 results are displayed per page, by default
[ ] Pagination is persistent (displayed outside scroll box).
[ ] Only Facility names with links for Facility Detail Pages will have "linked" appearance.
[ ] Links to Facility Detail pages will be announced as links for screen reader users.
[ ] Current keyboard focus is retained when keyboard user zooms the page in or out using browser zoom feature.
[ ] Keyboard user can see the yellow focus halo when the link for any facility type has focus. [#492]
[ ] Keyboard user can see the focus halo in heavier yellow color when tabbing through the map icons.
[ ] Current page of results is announced as the current item for screen reader users. [#713]
[ ] Other page result links announce themselves as links for screen reader users. [#713]
[ ] Map provides clear instructions on how to interact with it (including zoom in / zoom out buttons, and the arrow keys).
[ ] Cards will display consistent with prototype (as in image below, except the icons A, B, etc)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/685ba309-c6e0-4cc9-b55a-884452221951)

[ ] **When VA facility type = VA health** cards should display the following information:

>   - Distance
>   - VA HEALTH
>   - Name of Facility (linked to Facility Detail page or Facility page as governed by VAMC Pittsburgh logic)
>   - Address
>   - Directions
>   - Main Phone Number
>   - Mental Health Phone Number

[ ] **When VA facility type = VA Community Care (In network),** cards should include the following information:

>   - Distance
>   - Services (ie: PODIATRY)
>   - Name of Facility (linked to Facility Detail page)
>   - Address
>   - Directions
>   - Main Phone Number
>   - Referral language: _If you have a referral: Call this facility at xxx-xxx-xxxx. If you don’t have a referral, contact your local VA medical center._

[ ] **When VA facility type = VA benefits**, cards should display the following:

>   - Distance
>   - Type of Facility (ie: BENEFITS, current functionality maintained)
>   - Name of Facility (linked to Facility Detail page)
>   - Address
>   - Directions
>   - Main Phone Number

[ ]  **When VA facility type = Cemetery**, cards should display the following:

>   - Distance
>   - Type of Facility (ie: STATE CEMETERY)
>   - Name of Facility (linked to Facility Detail page)
>   - Address
>   - Directions
>   - Main phone number

[ ] If any value is unavailable in the data source (ie: phone number), expected behavior is for the area for that value to not be shown.

**Comment by tlei123** [comment]
Hi, @arickalewis1 !  Do you have the mobile comps for this?

Pls. let me know.  Thx much!  :)

**Comment by arickalewis1** [comment]
Hi @tlei123, deferring to @rtwell. Not sure if they're done but he'll be the one to own that!

**Comment by rtwell** [comment]
everything should stack/function exactly as it does now. is there something in particular that is not clear?

**Comment by tlei123** [comment]
@mmiddaugh @brangi , I've created my [preliminary Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/39) on TestRail for your review.

NOTE: The **Geolocation, Dropdown Defaults, Text Results** test-run will be the one expanded into separate browser-/device-specific runs after your review.  **Content & Layout** will remain browser-/device-agnostic (as responsive-CSS only cares about screen-width).

Pls. provide feedback.  Thx much!
