### ISSUE TITLE
Save in Progress forms - Replace fetch with apiRequest

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#48729]
## Description
This ticket represents the body of work of replacing the `fetch` with the `apiRequest` function for Save in Progress forms

## Tasks
- [x] Replace the `fetch` with the `apiRequest` function
- [x] Update unit tests and Cypress (E2E)

**Comment by joeniquette** [comment]
Its still ongoing

**Comment by AGarcia-Clarity** [comment]
Still ongoing should wrap up hopefully by End of Sprint.

**Comment by alyssagallion** [comment]
Alex implementing feedback that was provided.

**Comment by alyssagallion** [comment]
Waiting on other teams to review code.

**Comment by alyssagallion** [comment]
Pinged teams today for update.
