### ISSUE TITLE
Pre-needs - Replace fetch with apiRequest

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#48731]
## Description
This ticket represents the body of work of replacing the `fetch` with the `apiRequest` function for Pre-needs

## Tasks
- [x] Replace the `fetch` with the `apiRequest` function
- [x] Update unit tests and Cypress (E2E)

**Comment by alyssagallion** [comment]
Waiting on VSA to look at code.
