### ISSUE TITLE
[eFSR] - Veteran Information - Required Text Placement & Screen Adjustments

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#48736]
## What happened?
![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/cbf545ea-3556-4442-b257-7c6b6bf74281)_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

## Desired behavior
Move required text to correct element.

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by Dr-Pongo** [comment]
Completed with addressing a few axe and error validation issues!
