### ISSUE TITLE
Claims Status - Replace fetch with apiRequest

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#48737]
## Description
This ticket represents the body of work of replacing the `fetch` with the `apiRequest` function for Claims Status

## Tasks
- [x] Replace the `fetch` with the `apiRequest` function
- [x] Update unit tests and Cypress (E2E)

**Comment by AGarcia-Clarity** [comment]
This will carry over to the next sprint.  Did not work on at all as the Save In-Progress forms took up a lot of time.

**Comment by alyssagallion** [comment]
Finishing up some end-to-end tests.
