### ISSUE TITLE
PM | Profile | BAI | Update Pre and Post Launch Metrics (after Nov)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48739]
## Background

Update BAI metrics in the Product Outline once we are one month post launch date. We launched to 100% on 10/24/22 so we should update the outline on or after 12/1/22

Tasks
- [x] Get current count of BAI flags from VA Profile
- [x] Pull metrics from GA and add them to the Product Outline under measuring success
- [x]  Create report to show how many users that saw the BAI alert went on to update their mailing address

**Comment by SKasimow** [comment]
Added in the data from GA and now waiting for VA Profile to provide an updated baseline to the BAI Project outline [found here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/bad-address-indicator#measuring-success)

**Comment by SKasimow** [comment]
For the month of Nov there were 314 unique users that saw the BAI alert and 112 (36%) went on to update/confirm their mailing address.

**Comment by Samara-Strauss** [comment]
Thank you for letting me know! How did you confirm that 112 went on to update/confirm their address?

**Comment by SKasimow** [comment]
Michelle set up a segment capturing the users that see the BAI alert and then I was able to look at the "event" for updating the mailing address.

However, I was just playing with the report some more and now have a question on how the 314 unique users are being defined....so I'll follow-up with her at office hours next week and will let you know the outcome.

**Comment by Samara-Strauss** [comment]
Thank you! Can you also send me the report or show me how to evaluate this information myself?

**Comment by SKasimow** [comment]
Sure here is the [link](https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361/edit/AmvJoiCgQAS1rtAe1XrmLg)

Initially I couldn't access and had Michelle change permissions so lmk if you can't open.

**Comment by SKasimow** [comment]
@Samara-Strauss - I updated the metrics in the project document and added the source of the data for each metric [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/README.md). Let me know if everything looks ok.

**Comment by Samara-Strauss** [comment]
Looks great! Thank you!

**Comment by SKasimow** [comment]
Thanks...closing.
