### ISSUE TITLE
Connect axe scans with VA.gov Experience Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48744]

**Comment by briandeconinck** [comment]
@shiragoodman I think there's still value in this for VFS teams, some way of seeing that the results they get from axe support meeting our Experience Standards. This ticket clearly needs to be refined but I think it's a good follow-up to #45330.

**Comment by shiragoodman** [comment]
thanks @briandeconinck . I agree - the impact of connecting axe scans to the Exp Stds would be valuable to VFS teams. However, I don't think it's within scope for this current initiative.

I am going to move this to our backlog, and remove it from this initiative. We can discuss at a later date.

**Comment by shiragoodman** [comment]
This ticket was discussed at Governance team refinement in January 2024 and was determined to be no longer relevant to the team.
