### ISSUE TITLE
[eFSR] - Content Page & Start Your Request

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#48747]
## What happened?
New
![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/166312fc-7a17-43d3-82fd-fd7eed283413)

Old
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/7d9c9ac2-793c-45df-ad0d-1da308c28ae6)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/7190043c-5d7a-438a-9c32-2d38450a6356)

## Desired behavior
Update to match design

## Acceptance Criteria
- [ ] Updated to match design

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by OptionSelect** [comment]
See https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021573/simulate/sitemap?mode=i

**Comment by amponce** [comment]
It looks like the note component is currently owned by the platform team and is referenced in more than one location, we can coordinate to make this change with platform if they want to update the text.

```
/src/platform/forms/save-in-progress/SaveInProgressIntro.jsx
```

**Comment by amponce** [comment]
Update: Banner UI aligned with uxpin, now we just need to test with auth
<img width="1122" alt="Screenshot 2023-01-19 at 2 03 32 PM" src="https://user-images.githubusercontent.com/3916436/213572222-4f1faf51-b264-420f-94df-0d03d567f0e2.png">

**Comment by amponce** [comment]
Merged
