### ISSUE TITLE
[eFSR] - Spouse Information Sections

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#48750]
## Desired behavior
Implement new design, list loop removed.

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/1da46e84-f459-4c9d-b447-4fbae653c8bf)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/bb35e2d7-8049-40e8-a652-1b0ffa7b01a9)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/873d926e-501c-4ffd-be1a-6ab73e9c0df7)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/f6e71065-7fd4-4c80-9073-c83c98e4a14c)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/1f2ef55a-e796-4963-826c-e99e892deb66)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/d07e27a2-414c-4a12-8262-b9d5c030f502)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/dd58d8e6-e2bd-4c9b-af61-3fe6676426fb)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/7d02e0c0-5515-41a2-845e-621ba03dbe3d)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/72fda897-7725-408e-b3c5-9079684a4726)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/4120646a-d90f-4b24-b3cd-5567d798f1de)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/fb889ba3-c6f7-4015-8c89-df0d0dd08ca6)

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/4173c01e-a1d9-4c95-96c2-7df75a293b00)

## Acceptance Criteria
- [ ] List loop removed and new designs implemented

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by Dr-Pongo** [comment]
This is a larger ticket intended to be broken down once employment history information has been tidied up a bit.

**Comment by Dr-Pongo** [comment]
Closing out large ticket with smaller more bite sized tickets:
[Employment Information](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52818)
[Benefit Information](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52819)
[Other Income Information](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52820)
