### ISSUE TITLE
Veteran signs in and is immediately signed out

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#48751]
## What happened?
The veteran I am working with has a login.gov and id.me account. The veteran navigates to va.gov and clicks the sign in button. When the veteran tries to sign in with login.gov, they are able to enter their email address, password, two-factor authentication. It appears they are being signed in until the below page appears on their screen and then several seconds later, it signs them out. 

![screenshot firefox](https://user-images.githubusercontent.com/32465263/197853491-85e389f9-525c-46c3-8eef-71bff9d44ae5.png)

When the veteran signs in using ID.me in the same way as login.gov, the same thing happens except rather than seeing the screen it just immediately signs them out back to the homepage. 

The veteran tried to sign in today (Tuesday, 10/25) several times between 2:00pm - 2:10pm EST using both login.gov and ID.me. 

A few pieces of information to note:

1. The Veteran said they have signed into VA.gov before but only using Internet Explorer. They estimated the last time they successfully signed in was in June using Internet Explorer.
2. The Veteran has had some issues as it relates to their identity. Their DD214 has one version of their last name while their drivers license and passport have a different version. We had the EVSS helpdesk work with him to resolve this so it doesn't seem like this would be the cause of the issue but wanted to flag in case it was. 
3. We confirmed with the Veteran that his computer clock was set correctly. He was able to confirm this. However, he did say that his Microsoft Teams was not synced to the right time. 

## Specs:
- Device: Following up on this and will update once confirmed.
- Browser: occurs on chrome and edge 

## Steps to Reproduce
See above description. 

## Desired behavior
User should be able to sign into VA.gov account after entering information correctly.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by joeniquette** [comment]
I understand that the user believes their time is set correctly, but this happens when the time is not set to automatic on their windows machine. In the image attached, the use must ensure that the "set time automatically" and "set time zone automatically" and then click "sync now". Once they have done this then they should try to login again. I will also confirm that this user does not appear to have a verified login.gov account, so seeing the verification link is expected when they login with login.gov.

**Comment by clantosswett** [comment]
Thanks, Joe. I've instructed the Veteran to check his time settings. Will wait to hear back before closing but hopefully this fixes the problem.

**Comment by clantosswett** [comment]
Heard from the veteran and he was able to get in. Thanks for the extra guidance @joeniquette
