### ISSUE TITLE
[Feature] Shared Access >> MHV

### ISSUE THREAD

**Issue by pscruz** [department-of-veterans-affairs/va.gov-team#48767]
## Product Outline

This feature gives you the option to set-up limited or full access to your account for anyone who you want. 
- Person will be able to create their own account with their own email and password and access as much of your information as you want them to
- User can change or remove their access at any time

**Location:** Post MHV Login
- _Premium_ Account

**Integrations:**
- MPI >> profile data
- Login.gov >>

**Scenario 2:** Deferred Migration
- Task #9 >> https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=152%3A169
- Task #10 Email reminder >> https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=152%3A238
> If you want to make any changes it gives you a link to update. The email also asks you to think about anyone you might have shared your user name and password with. If any of those people should no longer have access to your account it suggests you change your password and provides a link to do that as well.
 >>

## High Level User Story/ies
As a user, I want to be able to give others differing levels of access to my MHV account, so I can empower them to provide greater care and support to me.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.
- Usefulness of feature
- Who they would share with and what information or level of access
- How they describe someone (language they use)

### What must be true in order for you to consider this epic complete? 
**Collected Inputs**
- First Name
- Last Name
- Email
- Relationship to you (drop-down)
- Type of information you want to grant access (drop-down)

Submission leads to appointment of access levels and auto-outreach to the designated person with new access

**Access Levels:**
- Limited 
- Full

```
Submission >> send an auto-email to specified person at their corresponding email address
- What are the next steps?
```

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by pscruz** [comment]
Question: Login.gov integration >> will 3rd party users need login.gov credentials?

**Comment by pscruz** [comment]
Question: Submission >> send an auto-email to specified person at their corresponding email address
- What are the next steps?

**Comment by elizabethkochBT** [comment]
canceled see #52657
