### ISSUE TITLE
Lighthouse developers: additional AWS access - IAM policy

### ISSUE THREAD

**Issue by mydesignrocks** [department-of-veterans-affairs/va.gov-team#48765]
Lighthouse development team is looking to gain additional access (mostly readonly) to be able to view resources like RDS and be able to SSM from the was console. This issue will be filling in for a couple of requirements that popped in during the support.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48304
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48447

Options:
- expand the existing IAM policy (policies) by lighthouse to include access to additional resources
- build a new role and attach new policies to it

Completion / Done:
- Create new role or new policy (as marked above with the 2 options available)
- Adjust the `iam_users.tf` within the devops repo for thee respective users
- Verify the users access have been met

**Comment by mviterna** [comment]
@mydesignrocks Hello, any update on this?

**Comment by kristen-brown** [comment]
#48304 has been closed as needing no further action.

**Comment by oseasmoran73** [comment]
Closing ticket as tickets have been addressed and/or reached out to
