### ISSUE TITLE
Automated User Emails 

### ISSUE THREAD

**Issue by pscruz** [department-of-veterans-affairs/va.gov-team#48760]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The VA needs email as an integral form of communication with users.

### Flows
**Scenario 2:** Deferred Migration
- Email from MHV about updating the way you login: https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=152%3A5
- Email from MHV reminding of the upcoming appointment (notified of access eligibility for ID Verification, as needed) >> https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=177%3A209
- Email from MHV reminding that you (user) set up shared access for [person(s) mentioned in last task] and what level of access you gave them. >> https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=152%3A238
**Scenario 1:** Migration
- Task 1 Ability to update user security >> https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=101%3A263

**Components**
- Email Templates

**Integrations**
- MPI [for user profile information]
- MHV [for account details, appointment information, shared access]
- Login.gov [for access eligibility])
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lmorris3** [comment]
Closing this - outdated.
