### ISSUE TITLE
Address Verification by Mail >> login.gov

### ISSUE THREAD

**Issue by pscruz** [department-of-veterans-affairs/va.gov-team#48764]
## Product Outline

**Scenario 2:** Deferred Migration
- Address verification >> https://www.figma.com/file/nAlLYv1GLIpB9KMavdZKq0/VA-Identity-Research?node-id=152%3A30

**Outcome:** Imagine you use the code from the letter and verify your address for Login.gov. After that you see that your Login.gov account is now working, and you can start using it to access MHV from now on.

## High Level User Story/ies
As a user, I need verify my physical address, so I can verify my account and gain full access (all benefits) to login.gov.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

- What is this letter asking you to do?
- Is there anything confusing about this letter?
- What would you do next?

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by elizabethkochBT** [comment]
canceled
