### ISSUE TITLE
Staging:  Update Verbiage when Veteran presented clinics for direct scheduling.  

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#48769]
These are issue are arising because Front End was filtering the return of clinics to only those clinics where veteran was seen in the last 36 months.  
Scenario #1:  **INT11Amp**	 
1.  Set Fort Collins DS= Yes, Any.  Req = Yes 36 mos. Clinic configured. FTC Amputation/Friendly Name FTC (IEN 1081)
2.  Log in as Patientfour.vaostest@id.me (no past Amputation appointments ) or john.morrison (who has past Amputation appointments).
3. Select Amputation. Select Fort Collins
4. Results Seen
                 Y**_our last amputation care appointment was at Friendly Name FTC Amputation:_** 
                 Fort Collins VA Clinic
                 2509 Research Boulevard
                 Fort Collins, Colorado 80526-8108
                 Main phone: 970-224-1550 (TTY: 711)
                Would you like to make an appointment at Friendly Name FTC Amputation?(*Required)

                Yes, make my appointment here
               No, I need a different clinic
 5. This message could be incorrect.  _"Your last amputation care appointment was at Friendly Name FTC Amputation"_. Patient may have never had an amputation appointment in any clinic.   Patientfour with no amputation appointments and john morrison with past appointments get this same message.  Patientfour could find it confusing that VAOS is telling them that they have had a past appt in clinic where they never have had a past appointment

Scenario #2:  **INT11Optom**	
This following verbiage issue is arising because Front End removed the filter that used to filter the return of clinics to only those clinics where veteran was seen in the last 36 months.
Veteran are seeing this message when VATS is set to yes last seen within 36 mos. _"In the last 36 months you’ve had an optometry appointment at the following Dayton VA Medical Center clinics:"_     Veteran may not have been seen in any of the displayed optometry clinics.   The veteran could have had a past optometry appointment in a clinic NOT configured for direct scheduling. So that clinic won't display but other optometry clinics configured for direct could display and veteran many have never been seen in those.  Veteran could find it confusing that VAOS is telling them that they have had a past appt in clinic within the last 36 mos when that might not be true.  **Marcy to add  steps to recreate to , there is staging bug and I can't add details until it is fixed**

**Comment by JRRoof** [comment]
Marcy will retest and update the format of this ticket.

**Comment by ldelacosta** [comment]
@marcynadeau - let us know when you have updated the format for this ticket. Thank you.

**Comment by marcynadeau** [comment]
@ldelacosta @JRRoof I have updated the ticket with the first scenario and some details on the second scenario.  As soon as vaosr-5655 is fixed, I will provide the remaining details on the second scenario.

**Comment by ldelacosta** [comment]
@marcynadeau - our team will close out the ticket. We have placed it in our epic to improve the alert message for reference. @JRRoof @outerpress
