### ISSUE TITLE
Param store values

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#48776]
**PROBLEM STATEMENT**
Param store values need to be added as credstash cannot be used in EKS.

**DEFINITION OF DONE**
- [x] Param store values have been added for dev
- [x] Param store values have been added for staging
- [x] Param store values have been added for sandbox
- [ ] Param store values have been added for prod

- [x] Necessary tests complete

**Comment by laineymajor** [comment]
@RachalCassity @considerable can you update this ticket to include the work you've recently done here? Thanks!

**Comment by considerable** [comment]
added values to the parameter store for staging, reflecting it in secrets.yaml and settings-configmap.yaml
