### ISSUE TITLE
Supplemental Claims | Endpoint and JSON schema works/documentation

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#48788]
This is a requirement that needs done before release

- [ ] Add/Update https://github.com/department-of-veterans-affairs/vets-json-schema
- [ ] Add to Swagger docs https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/supplemental_claims/createSupplementalClaim
- [ ] Add test cases that make use of the schemas

**Comment by saderagsdale** [comment]
@kylesoskin Is this different than the work previously done by Scott? [#44674](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44674)

**Comment by kylesoskin** [comment]
@saderagsdale it is different in that it needs updated. Scott did not add anything about the 4142 info to the schema, I am assuming because it may not have been a requirement then at that time? 

I also do not think he added anything to the swagger API docs

**Comment by kylesoskin** [comment]
JSON updated to most recent state. 

Will need additional updating later though, but closing for now as it is merged in current state. Updated state will be covered in work in other tickets.

Will update swagger docs at that time too.
