### ISSUE TITLE
Determine IA and URL approach for campaign landing pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4878]
## Determine IA and URL approach for campaign landing pages

This is part of the epic to create a campaign landing page template. 

**IA questions to resolve:**

- Where should campaign landing pages live in the public website IA?
- What should the URL pattern and format be? 
- Who should/will create the URLs (DEPO, stakeholder business team)? 

There are potentially other questions to answer, which will be assessed by the Content-IA team. 

**See the problem statement, product, and background info in the epic:**
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4621

- We have a FE design template and content model, close to done.
- We have a possible pilot stakeholder, Office of Mental Health Suicide Prevention.
- Desired availability of CMS AX: Q1 (more specific timeline TBD conversations with other teams involved).

**Product repo:**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates

**Comment by meganhkelley** [comment]
Hey @jenniferlee-dsva — what is your approximate timeline on needing this complete? It looks like the timeline for the whole epic is Q1, correct? I'll check with @mnorthuis about when we can slate this in. Thanks!!

**Comment by mnorthuis** [comment]
Work completed in #16813
