### ISSUE TITLE
Reduce unneeded User attribute sourcing from UserIdentity

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#48798]
## Description
The Identity Team would like to reduce the size and usage of the `UserIdentity` class, which is not leveraged as much for SiS as it is for SSOe. The goal of this ticket is to analyze the remaining `User` class attributes that are sourced from `UserIdentity` and move as many as possible to MPI sourcing.

The following attributes should continue to be sourced from UserIdentity:
- `multifactor` - this can eventually be removed after both DSLogon & MHV credentials are deprecated from VA.gov
- `authn_context` - the purpose of this is being overtaken by the `sign_in` hash but it is still used extensively for SSOe, easiest to refactor to remove it after SSOe has been phased out
- `verified_at` - this is relevant to user authentication and should stay
- `sign_in` - this is relevant to user authentication and should stay
- `email` - not yet present in MPI responses
- `loa3?` - LoA/IAL status comes from CSP and should stay, perhaps change to `verified?` to cover both LoA from ID.me and IAL from Login.gov better?

The following attributes are safe to move to MPI sourcing:
- `logingov_uuid` - ID that can be sourced from MPI
- `idme_uuid` - ID that can be sourced from MPI
- `person_types` - this attribute can be sourced either from ISAM headers or the MPI find_profile query

The following attributes require further investigation:
- `mhv_icn`:
    * Identity "icn": `icn: { regex: PERMANENT_ICN_REGEX, root_oid: VA_ROOT_OID, type: :single_id }` (parsed from gcids)
    * Identity "mhv_icn": `safe_attr('va_eauth_icn')` (taken from SAML headers, `safe_attr('va_eauth_mhvicn')` is only used for icn mismatch check)
    * MPI "icn": `icn: { regex: PERMANENT_ICN_REGEX, root_oid: VA_ROOT_OID, type: :single_id }` (parsed from gcids)
    * No apparent reference to an MHV-sourced ICN in the MPI docs

## Tasks
- `logingov_uuid` - move User delegation to MPIData, saved for [future tech debt story](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/49706) due to complexity of removal
- `idme_uuid` - move User delegation to MPIData, saved for [future tech debt story](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/49706) due to complexity of removal
- [x] `person_types` - switch primary sourcing to MPIData

**Comment by alyssagallion** [comment]
Finishing specs.

**Comment by bramleyjl** [comment]
After more analysis the Identity Team has concluded that switching over CSP uuids, namely `logingov_uuid` & `idme_uuid`, would result in a very large number of vets-api RSpec unit tests to break, given the frequent dependency on the `User` factory and the related assumptions about how it is made. As such a new ticket will be created just to handle those two IDs to be switched, and I anticipate completing that work at some point over the 2022-2023 holidays when active development on VA.gov slows down.

A small PR to change `person_types` sourcing from defaulting to UserIdentity to defaulting to MPI Profile has been included.
