### ISSUE TITLE
Cleanup DD documentation

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#48797]
## Description
We currently don't have a lot of comprehensive information in regards to Datadog especially in terms of logging. This ticket will update/create the necessary documentation to help others use Datadog successfully.

## Acceptance Criteria
- [x] Add the necessary documentation to the confluence doc:
    - https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+infrastructure+and+applications+with+Datadog

**Comment by ianhundere** [comment]
added the following:
- https://vfs.atlassian.net/wiki/spaces/OT/pages/edit-v2/2490761544
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2492498000/Logging
