### ISSUE TITLE
IA recommendation for Supplemental Claim form 20-0995 from Benefits-team 1

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#48796]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
  
  
We need IA URL recommendations for the form page. It is currently a work-in-progress located at https://staging.va.gov/decision-reviews/supplemental-claim/request-supplemental-claim-form-20-0995, but with the content suggestion of using "File a supplemental claim" instead of "Request a..." (like HLR and NOD), the URL will need to change to use "file-"

We have not yet received initial URL path recommendations for the Supplemental Claim form.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.

We have not yet started work on the React widget for Supplement Claims

## When do you expect to launch your product to 100% of users?
  
Targeting the end of November.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims
- Link to or attach user flows: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/supplemental-claims-flow.md
- Link to prototype or mockups: https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89#Version
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/48138

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

*NOTE* this [IA feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45031) did not include any recommendations

## When does this work need to be done?
- Estimated launch date: ??
- Estimated staging review date: 
- Content and IA work needed by: Content in progress (w/Beth Potts)

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits Team 1, squad 2
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Pam Hastings
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by heyjoni** [comment]
Here's [IA feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-supplemental-claims-form.md) for the Supplemental Claims form. Please let me know if you have questions.

@RLHecht, FYSA. There are content recommendations in my feedback but I understand that @bethpottsVADEPO has been working on these changes already.

**Comment by RLHecht** [comment]
This work is complete. Closing

**Comment by RLHecht** [comment]
Keeping in validate until we implement the IA.

**Comment by Mottie** [comment]
Hi @RLHecht! I don't think we have a definite date set, @saderagsdale would know. As for the [React widget, yes we have a ticket to start building it](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48808) which will likely get done in our next sprint.
