### ISSUE TITLE
[Bug] My VA - Benefit payments - Recent direct-deposit - display/data anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#48809]
## What happened?
On Staging **My VA** page, **Benefit payments** section, for User with recent direct-deposit payment, display of payment info [and incoming API-data] appeared anomalous, as did related display/data on **Your VA payments** page:

- My VA page:
  - Zero amount - not sure why a zero-amount payment was displayed and why such payment would be sent from API in the first place.
  - "Deposited" - mismatch with Your VA payments page & API-data [paymentMethod was null].  Should front-end have made an apparent "judgment call" and displayed this instead of "Check mailed" or just displayed dashes?
- Your VA payments page:
  - "Direct Deposit" not displayed - mismatch with My VA page
  - Missing Bank & Account info - something to do with zero amount?

**NOTES**: 
- This _might_ be just a Staging API mock-data error, but it's definitely worth investigating.
- I've added design, frontend, and backend practice-area labels.  It appears some team-wide decision needs to be made on how this potential bug should be fixed. 

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User: 36 (Wesley) &mdash; has recent payment via direct deposit

### Screenshots
**My VA** page:
![image](https://user-images.githubusercontent.com/587583/198164461-bc01c577-b8a3-438f-939d-ca7d24d6cf4e.png)

**Your VA payments** page:
![image](https://user-images.githubusercontent.com/587583/198164933-730d507c-c275-448e-ad55-46ce175d6823.png)

## Steps to Reproduce
- URL: https://staging.va.gov/my-va/
- Test User:  36 (Wesley)

1. On **My VA** page, in **Benefit payments** section, in **payment card**, note **+$0.00** amount and **Deposited on**.  [API data said null for paymentMethod.]
2. In **payment card**, click **View your payment history** link.
3. On **Your VA payments** page, in **Payments you received** section, in **1st table row**, note **$0.00** amount and **---** in **Method**, **Bank**, and **Account** columns.

## Desired behavior

Sorry, this is a tricky one.  I only have questions:
- Do zero-amount payments really occur in Production?
- If they do occur:
  - Would they really be missing Method, Bank, or Account data?
  - Would Veterans find zero-amount payments useful? Should front-end display them at all?
  - If they should be displayed:
    - If null paymentMethod API-datum comes in, should f/e assume it's Direct Deposit?
    - Would the dashes in payment details cause Veterans confusion/concern?

Feel free to schedule a Zoom chat with me as needed/desired.

## Acceptance Criteria
[see **Desired behavior** above &mdash; need discussion if this is really a bug]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tmitchellgcio** [comment]
Samara said she's ok with how the code works so I'm closing this
