### ISSUE TITLE
Supplemental Claims | Add content page React widget

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#48808]
## Value Statement
**_As a_** Veteran
**_I want to_** see an action link on the supplemental claim info page
**_So that_** I can start the form.

---
## Background Context
- The Drupal [content info page](https://staging.va.gov/decision-reviews/supplemental-claim/) will get a React component injected on to that page which uses a feature flag to show an action link that directs the Veteran to start the online form

## Acceptance Criteria
- [ ] User will see, or not see, the start the online Supplemental Claim form depending on the state of the feature flag
- [ ] User will be directed to the `/start` page after activating the action link
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- DESIGNS: pending - needs discussion with sitewide content
- CONTENT: pending

## Open Questions
- What content needs to show when the feature flag is disabled
- What content, besides the start form action link, needs to show when the feature flag is enabled

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---

**Comment by Mottie** [comment]
[Work started by Rocio](https://github.com/department-of-veterans-affairs/vets-website/pull/22659); only awaiting content recommendations before making the work ready for merging

**Comment by sortizsh** [comment]
@Mottie can you reach out to Randi H to get content for this?

**Comment by saderagsdale** [comment]
@RLHecht Hey Randi! We're nearing the end of our work on this form. Can you let us know what content to include for this? Also, let us know if there's a separate content ticket we should be using to track the work.

**Comment by Mottie** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50527

**Comment by RLHecht** [comment]
Thanks @saderagsdale One of our writers is working on this but has been pulled into some other priority work that should be wrapping up next week. She'll be able to turn back to it next week and will post the final content here.

**Comment by saderagsdale** [comment]
@RLHecht Hey Randi! Has the team finalized content so it can be posted here for review?

**Comment by RLHecht** [comment]
Yep, we posted it for you in the intake ticket: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/50515#issuecomment-1387617329

**Comment by saderagsdale** [comment]
@RLHecht What's the best way to test this?

**Comment by RLHecht** [comment]
@saderagsdale I'm not sure what you mean. @Mottie how have you tested other widgets we've given you content for? Our team plugs the react code into Drupal that your team provides but we can't really test how it works there (we can just see content for one side of it).

**Comment by Mottie** [comment]
Previously, I tested the React widget in my local environment. What we were wondering is how can we test this code in the staging environment

**Comment by Mottie** [comment]
@RLHecht we have merged in the React widget changes.

**Comment by RLHecht** [comment]
Thanks @Mottie Can you provide us with the react app code that we can add in Drupal?

**Comment by Mottie** [comment]
`coe_access`

**Comment by RLHecht** [comment]
This is for COE or Supplemental Claims?

**Comment by Mottie** [comment]
Oh oops LOL... `supplemental_claim`

**Comment by rocio-desantiago** [comment]
Hi @RLHecht Just following up to see if the app code `supplemental_claim` worked.

**Comment by RLHecht** [comment]
@Mottie This code isn't working when I add it to Drupal: 
<img width="785" alt="Screen Shot 2023-02-07 at 2 56 23 PM" src="https://user-images.githubusercontent.com/48728214/217351502-aa56d46c-68db-426b-94ed-5d18d233b1c8.png">

**Comment by Mottie** [comment]
@RLHecht It looks like we're missing the definition in the [`widgetType` file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/widgetTypes.js). We'll get that updated and let you know when it's done

**Comment by rocio-desantiago** [comment]
@RLHecht the fix has been merged in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23330). Can you test again?

**Comment by RLHecht** [comment]
@rocio-desantiago That worked! It's rendering correctly on the page.
