### ISSUE TITLE
[Bug] My VA - Outstanding debts - No debts, Has copays - Missing Learn about VA debt link

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#48812]
## What happened?
On Staging **My VA** page, **Outstanding debts** section, for user with No debts but Has copays, **Learn about VA debt** link was missing.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User: 36 (Wesley)

## Steps to Reproduce
- URL: https://staging.va.gov/my-va/
- Test User: 36 (Wesley)

1. On **My VA** page, in **Outstanding debts** section, note missing **Learn about VA debt** link to the right of debts card.

### Screenshot
![image](https://user-images.githubusercontent.com/587583/198192216-e292727e-6b49-4544-859e-19d9e24fad92.png)

## Desired content/behavior
- [ ] **Learn about VA debt** link should be displayed to the right of debts card.

### [Mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/nR30rda)
![image](https://user-images.githubusercontent.com/587583/198192405-ef53f7d3-0d83-4b74-9f7a-2f842134a3f5.png)

## Acceptance Criteria
[see **Desired content/behavior** above]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ajakabcin** [comment]
Per [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#learn-about-va-debt-link), this "Learn about VA debt link" should appear for user 36, who has copays, but no debts

**Comment by tmitchellgcio** [comment]
just merged give it about 30 min

**Comment by ericasauv09** [comment]
validated with user 36: ![Screen Shot 2022-11-08 at 13.28.11.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/777f3885-47b2-429d-94ae-bddd65aaff0e)

**Comment by tlei123** [comment]
Validated across supported devices/browsers.
