### ISSUE TITLE
3rd Message Inadvertent Send Issue

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#48819]

**Comment by jwowk** [comment]
Clinic was configured under 179 credit stop and 310 stop code.  179 credit stop did not have a third message configured, but VEText sent a third message using the 310 stop code config which does have a third message configured using the NIRMO template.  Because the clinic is in both 179 and 310, it utilized the latter config when the former did not have a template configured for the third message.

**Comment by lindsay-insco** [comment]
No fix implemented yet. Branch created and in progress

**Comment by lindsay-insco** [comment]
Still in progress

**Comment by lindsay-insco** [comment]
Fixed
