### ISSUE TITLE
[Bug] My VA - Benefits payments - Recent check - Display/data mismatch with Your VA payments page

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#48810]
## What happened?
On Staging **My VA** page, **Benefit payments** section, for User with recent check payment, display of payment info does not match **Your VA payments** page:

- My VA page:
  - Payment-card appeared okay, but...
- Your VA payments page:
  - First 3 pages showed zero-amount payments [1-18].
  - Page 4 also showed mostly zero-amount payments [19-23], with matching payment [24] at the bottom.

**NOTES**:
- This is similar to the potential bug #48809
- This _might_ be just a Staging API mock-data error, but it's definitely worth looking into.
- I've added design, frontend, and backend practice-area labels.  It appears some team-wide decision needs to be made on how this potential bug should be fixed. 

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User: 80 (Oscar)

## Steps to Reproduce
- URL: https://staging.va.gov/my-va/
- Test User: 80 (Oscar)

1. On **My VA** page, in **Benefit payments** section, in **payment card**, note payment info displayed.
2. In **payment card**, click **View your payment history** link.
3. On **Your VA payments** page, in **Payments you received** section, note **n/a** dates, **$0.00** amounts, and **---** in **Bank** & **Account** columns.
4. In **pagination bar**, click **Next**, and note same display/data anomalies on table-page 2.
5. Keep clicking **Next**, and note same anomalies on table-pages 3 & 4.  On table-page 4, note mostly matching payment [24] at the bottom &mdash; **n/a Date** mismatched with incoming API-datum, and **---** in **Bank** & **Account** columns.

## Desired behavior

- [ ] My VA page payment info should match Your VA payments page.

[See related questions in #48809 if this is indeed a legitimate bug.]

Again, feel free to schedule a Zoom chat with me as needed/desired.

### Screenshots

**My VA** page:
![image](https://user-images.githubusercontent.com/587583/198173817-e23dc2f7-0e37-4c9b-8bee-d40171ae383c.png)

**Your VA payments** page [table-page 1]:
![image](https://user-images.githubusercontent.com/587583/198173931-8c473360-340b-413a-816c-e51226ca8d48.png)

**Your VA payments** page [table-page 4]:
![image](https://user-images.githubusercontent.com/587583/198174346-547e4220-3218-4973-bf80-583cb28f225a.png)

## Acceptance Criteria
[see **Desired behavior** above &mdash; need discussion if this is really a bug]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tmitchellgcio** [comment]
I don't see this being common as it is and really it would surprise me if it happens at all in production, but I have validated the code is showing what is expected. Samara said she's ok with how the code works so I'm closing this
