### ISSUE TITLE
Yellow Ribbon MVP Content Review

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#4881]
## User Story:
As a Veteran, I need to understand Yellow Ribbon participating school information so that I can choose the best school option for me.

### [Landing Screen](https://vsateams.invisionapp.com/share/K7VEJ2UE365#/screens/398947503_Start)
- [ ] Review title on landing page - is this the name we want?
- [ ] Provide intro copy. Users may come from elsewhere on va.gov, or organic search
- [ ] Review labels for search fields
- [ ] Provide content below search fields - should it link back to hub?

### [Results Screen](https://vsateams.invisionapp.com/share/K7VEJ2UE365#/screens/398947911)
- [ ] Review `Sort By` options.  Need to succinctly yet clearly communicate options to users
- [ ] Review labels for each data point in card.  Hoping for as clear and short as possible.
- [ ] Review labels for search fields
- [ ] Provide content below search fields - should it link back to hub?

### [Results Screen with compare](https://vsateams.invisionapp.com/share/K7VEJ2UE365#/screens/399214814)
- [ ] Review wording of `Compare 2 schools selected` link

### [Results Screen with compare, mobile](https://vsateams.invisionapp.com/share/K7VEJ2UE365#/screens/398948126)
- [ ] Review page title
- [ ] Review `Compare By` menu (click Maximum Benefit heading)
- [ ] Any other copy needed for this page?

### [Results Screen with compare, desktop](https://vsateams.invisionapp.com/share/2CVEX68T5A9#/screens/399330380)
- [ ] Review column headings

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Word doc provided with any needed updates

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AnneHurley** [comment]
Here's a screen shot of the landing screen:
[YR landing page shot]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4065749/Yellow.Ribbon.screen.shot.docx)

**Comment by AnneHurley** [comment]
[Yellow Ribbon tool screens and copy v1]
(https://app.zenhub.com/files/133843125/830802e6-fd60-4a01-8240-1fbeb2be3e17/download)

@andaleliz  @RLHecht  Randi ready for your copy editor eyes. Liz - note I have some questions about some results we can't see on these screens, about a couple of CTAs, etc - I'm sure you and your team have already gone through a lot of those so apologies in advance. Let me know if you have any questions.

**Comment by andaleliz** [comment]
@AnneHurley Answers to your questions:

- The sorting terms are visible if you click on the `Sort By` text in the prototype on the linked **Results** screen, and something I need your guidance on.  Alternatively, you can see them as a single screen (instead of an overlay) if you use the right arrow to go to the end of the prototype

- I'm not sure about how many schools or divisions can be returned per school, yet. @ncksllvn or @kelsonic might know by this point. It was something we need to look into, if it's possible/logical to group the programs when benefit amount, # of students, and degree level are all the same

- The schools are selected by clicking the `Add to compare` button

- Your question about how we got to the **Compare School Selections** screens makes me a little concerned the prototype isn't clear, but I suppose we'll learn in testing. You get to that screen by clicking the `Compare Selected Schools` button.

- You asked about if there should be a CTA on the last screen, or next steps - one of my main questions I'm hoping research will answer is "What would you do next, now that you have this information?".  I really have no idea what a Veteran would want to do yet and thus can't recommend a CTA from here.  I definitely agree that it would be helpful to provide them a way to get to the next step, whatever it may be.

**Comment by AnneHurley** [comment]
@andaleliz  - ok thx for this ^ I hadn't realized the sort by was linkable. 

Sort by should have a lowercase "by"
Benefit amount: High to low
Benefit amount: low to high
School name: A to Z
School name: Z to A
City: A to Z
City: Z to A
State: A to Z
State: Z to A

Couple of questions - do you think we could get away with listing just "School: A to Z" or do you think we need it? I'm on the fence.
Do you think anyone would use the Benefit amount: low to high sort? I suppose it doesn't hurt to keep it, but that could be something to test too.

**Comment by RLHecht** [comment]
@andaleliz @AnneHurley Here is the PDF with my edits. Not much more from what Anne had in there.
[Yellow Ribbon copy-RH edits.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4093316/Yellow.Ribbon.copy-RH.edits.pdf)

**Comment by andaleliz** [comment]
@AnneHurley I do think we could get away with just school. I'd love to consolidate it any more if possible.  Having users check out the sort functionality is in the conversation guide, so I'm hopeful we'll get feedback on the options.

@RLHecht , and @AnneHurley Thank you for turning this around so fast! I'll update my prototype now

**Comment by andaleliz** [comment]
From @jenniferlee-dsva "also can we not call it “benefit,” but … not sure, money, funding?"

From me: "I'm a little concerned about the label "Benefit available for" (or whatever we'll use instead of benefit), referring to the number of students.  It makes sense in the card format, but questioning if it is translating well to the comparison table.  I don't know that "Number of students" is really clear either (which is what is currently there).  Just want to double check that you think this language makes sense.

**Comment by andaleliz** [comment]
Also please review the updated labels for search fields ![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/bb5382ba-ffd4-47c7-a269-857d564b800f)

**Comment by RLHecht** [comment]
@andaleliz instead of "Select a degree level" I think it should read "Degree level" so it's parallel to the other labels that don't use verbs.

**Comment by andaleliz** [comment]
@RLHecht Sounds good, I'll make sure that update makes it to the hi-fis.

Speaking of - breadcrumbs weren't something I addressed in the initial sketches. Now that we're at this stage, they need to be considered.

Is that something you or Anne would address, or something that gets addressed via Peggy or Mikki's review? 

Here they are: https://vsateams.invisionapp.com/share/X5VOMBG2YP4

**Comment by peggygannon** [comment]
@andaleliz Hello, I added reviewer comments in the Invision mockup and am leaving them here below as well. Please let me know if you have any questions!  

First screen: 

--Breadcrumb and header: I suggest rewriting to the below to make more active: 
Find a Yellow Ribbon school 

-- I think we need an intro sentence to set up to tool. I suggest swapping and rewriting the paragraphs to the below to better set up to tool: 
 
Use our tool to find schools that participate in the Yellow Ribbon Program. 
The amount of money you get from the Yellow Ribbon Program varies by school, degree type, and the program you’re enrolled in.

--It seems odd to have eligibility information here on the tool intro page. Also it seems like the bullet list is only a subset of the all eligibility info that appears on the Yellow Ribbon static page. I suggest removing eligibility info from the tool page. 

--General question:
Do users have to search by all 3 criteria? or can they search by just school name or location or degree?
If users can search by any of these options, then I suggest we add content to let them know they can search by just 1 (or all 3) of the criteria.


In addition, I marked areas in which we need to make the buttons/subheads sentence-cased.

**Comment by andaleliz** [comment]
@peggygannon Thank you! I've made many of the changes you suggested and have some responses for further discussion on a couple points below:

> -- I think we need an intro sentence to set up to tool. I suggest swapping and rewriting the paragraphs to the below to better set up to tool. 

> Use our tool to find schools that participate in the Yellow Ribbon Program.
> The amount of money you get from the Yellow Ribbon Program varies by school, degree type, and the program you’re enrolled in.

I think the copy above works really well on this page.  One thing to consider is that users may land on this page from organic search, or a place outside the benefit hub, so it's possible they won't have seen eligibility information anywhere else.  With that in mind, do you still think we should **swap** the content with your suggestion, or perhaps add this immediately below the paragraph ending with "...division you're studying in"?

Same thinking applies to removing the eligibility information from the page.  Do you still think we should remove it if students are entering va.gov via this page somehow?

> --General question:
> Do users have to search by all 3 criteria? or can they search by just school name or location or degree?
> If users can search by any of these options, then I suggest we add content to let them know they can search by just 1 (or all 3) of the criteria.

Users can search just by one of those fields, or none, so I agree with you that content letting them know how to search would be helpful.  Can you or @AnneHurley provide that, please?  

I'll make updates once I hear from you.  Thanks!

**Comment by AnneHurley** [comment]
@andaleliz  @peggygannon  @RLHecht 

Search Yellow Ribbon schools
You can use one or more of these search terms.

^that's as short as I thought I could make it. It could be subhead size under that main label head. OK?

**Comment by andaleliz** [comment]
@AnneHurley That sounds good to me, but am not totally clear on the sizing.

In the original content you provided, I understood the text of `Search Yellow Ribbon schools` to be the normal body size, and that it would be immediately above the search fields.

So with this update, should `Search Yellow Ribbon schools` be an h2, and `You can use one or more of these search terms`? That seems like it'd be a bit big.  

The more specific you can be the better. Feel free to provide in a word doc or leave an InVision comment directly in the mockup

**Comment by AnneHurley** [comment]
@andaleliz  I'm not sure either and I know there's  not much room. If you can make that second line about searching by the search terms in a size smaller so it looks like a subhead, that's what I was envisioning. The shortest way I think we could do this to address @peggygannon 's feedback is:
****Use 1 or more of these terms****
[I should have had the 1 as a numeral to begin with]
if the type size can be smaller than that label head Search Yellow Ribbon schools, then I think it would work. If there's room for it. LMK.

**Comment by andaleliz** [comment]
@AnneHurley I'm not aware of any constraints we have on space.  We can make the page as long as necessary to fit the right content.  I think it's most important that we provide clarity to our users.

**Comment by peggygannon** [comment]
Hello, @andaleliz Here are responses to your questions above. Let me know if you have any additional questions:

--Yes, I do think we should swap the content with the intro sentences that I suggest above. 

--Regarding eligibility info on this tool page, to account for users who might get to this page outside of VA.gov, I recommend that we move up and update the the link at the bottom of the screen to right below the intro sentences: 

So suggested content flow would be: 

{Header} **Find a Yellow Ribbon school**
Use our tool to find schools that participate in the Yellow Ribbon Program.
The amount of money you get from the Yellow Ribbon Program varies by school, degree type, and the program you’re enrolled in.

[Find out if you qualify for the Yellow Ribbon program](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/)

Search for schools by 1 or all of the terms below.

**Comment by jenniferlee-dsva** [comment]
Great suggestions, thank you @peggygannon.  One very very minor style guide item - @andaleliz can make this later post-user research iterations: "Spell out 'one' when it’s used by itself in a sentence, or in expressions like one-to-one, one-on-one, and one-time."

Reference: https://design.va.gov/content-style-guide/numbers#exceptions

**Comment by andaleliz** [comment]
Thanks @peggygannon and @jenniferlee-dsva , the copy has been updated in the prototype (including spelling out `one`). I removed the link below the fields pointing on the hub page, since we now have a link above them doing the same thing.

**Comment by peggygannon** [comment]
Hi, @andaleliz. I'm OK, with using the word funding in place of "benefit" 

Next time you're in the mockup, can you please capitalized Program in this link? [Find out if you qualify for the Yellow Ribbon Program]  Other than that, all looks good!

Platform content review is completed for the Yellow Ribbon prototype!

**Comment by MickinSahni** [comment]
🙌 @andaleliz cool if i close this out given vsp's completed review?

**Comment by andaleliz** [comment]
Yes! Thanks @MickinSahni
