### ISSUE TITLE
[EPIC] MHV to VA.gov: Problem List: Usability Testing & Refinement

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#48843]

**Comment by MarciMcGuire** [comment]
@bryan-riley-va I am just tagging you on this so I know the ByLight team will be handling.  Thanks!

**Comment by rbsingleton** [comment]
Closing this in favor of [usability testing epic](https://app.zenhub.com/workspaces/mhv-on-vagov-research-644bfcfc77c2ba00146120d7/issues/gh/department-of-veterans-affairs/va.gov-team/57629)
