### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by kristen-brown** [department-of-veterans-affairs/va.gov-team#48868]
# Instructions
Fill out Details of need and the PRs related to OOB sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy

Original PR that caused the issue: 
https://github.com/department-of-veterans-affairs/vets-api/pull/11011

Reversal of PR merged and tested on staging:
https://github.com/department-of-veterans-affairs/vets-api/pull/11018

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
Three Benefits Intake submissions (likely 3 users) have been affected as of the creation of this ticket.

## Has fix been confirmed in Staging?
- [x] Yes
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
A read timeout change deployed during the regular deploy caused three jobs to begin but not complete. Without another deployment to revert the change, those jobs will continue to run in Sidekiq without anything to stop them. It is unclear whether other jobs will have the same problem, although signs point to this issue being caused by the timing of those three jobs around the prior deployment, so it seems unlikely. However, the currently running jobs will continue to take up resources that could be used for other background jobs in `vets-api` until the revert PR can be deployed.
   
## Verify The following
 - [x] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [x] The OOB Deploy Requests is critial and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests
 - [ ] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by oseasmoran73** [comment]
[PD](https://dsva.pagerduty.com/incidents/Q33CDX00QQI0GE)
[Jenkins job](https://dsva.slack.com/archives/CBU0KDSB1/p1666908552411349?thread_ts=1666907153.158359&cid=CBU0KDSB1)
[Confirmation](https://dsva.slack.com/archives/CBU0KDSB1/p1666909751071819?thread_ts=1666907153.158359&cid=CBU0KDSB1)

As a reminder @kristen-brown a postmortem is required. Should you have any questions, please let me know

**Comment by little-oddball** [comment]
Closing this ticket as Post-Mortem is not a Platform responsibility for this item. Additionally ticket for Post-Mortem was created and reference in this ticket.
