### ISSUE TITLE
[BE] Github folder reorganization: Notification preferences and onsite notifications

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#48862]
### Background

Hey Tom -- I was hoping to reorganize and rename some of our GitHub folders to minimize confusion. Can you help me with the following?

**Move notification-preferences**

First, can you help me move the notification preferences folder so that it lives under profile? Specifically:

- [ ] Move all of [notification-preferences](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences) so that it lives under [va.gov-team/products/identity-personalization/profile/](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile). So, the new github structure for the notification preferences folder would be `va.gov-team/products/identity-personalization/profile/notification-preferences`.

**Rename notifications folder**

Second, can you rename the current notifications folder to onsite-notifications?

- [ ] So, changing `va.gov-team/products/identity-personalization/notifications/` to `va.gov-team/products/identity-personalization/onsite-notifications/`.

Third:

- [ ] Can you move the [mvp folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/mvp), the [notifications-v2 folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/notifications-v2), and the  [README.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/README.md) so they live directly under the new `va.gov-team/products/identity-personalization/onsite-notifications/` folder? I want to eliminate [vagov-notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications) as a folder, **but not the documentation that live in it** (the mvp and notifications-v2 folders and README listed above). Let me know if this part is unclear, as I don't want to remove any documentation, just move things around.

### Acceptance criteria 

- [ ] Everything has been moved/renamed as outlined above, and Samara has validated that everything looks good.

**Comment by Samara-Strauss** [comment]
Adding this for next sprint, so no need to tackle sooner unless you have time.

**Comment by tpharrison** [comment]
Yep - no problem.

**Comment by Samara-Strauss** [comment]
Sorry for the last minute change, but can we push this back 1 sprint? I need some of these links to stay the same in the next two weeks, and reorganizing as I've requested will break those links. We should be fine to do this in the next sprint. @tpharrison @SKasimow

**Comment by tpharrison** [comment]
@Samara-Strauss Let me know when you're ready, and I'll make these changes.

FYI - @andaleliz and I put together a video tutorial that shows how to make these types of changes to a Github repo.  Liz shared it with the platform team and they have posted it [here](https://www.youtube.com/channel/UCq3F4c_-IIdantkT8hQxS9g).

cc/ @SKasimow

**Comment by Samara-Strauss** [comment]
@tpharrison thank you, I will!

And thank you for this video! It's great!!

**Comment by SKasimow** [comment]
@Samara-Strauss - should I leave this on "hold" or move to Sprint 88

**Comment by Samara-Strauss** [comment]
We can actually close this. I know how to move folders now, thanks to a video Tom created, so I no longer need help.
