### ISSUE TITLE
Add Workflow to 686: "Report a divorce"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4886]
`MAY BREAK INTO SMALLER PARTS: -/+ step child`

## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for divorce so that I can maintain an accurate representation of my status with the VA.

## Goal
Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
 - [Mockup](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/screen/cf1d4c72-97a0-45af-b9b4-2cfdcc2e7288/Apply-Dependents-Report-Divorce-1A
)

## Tasks
- [x] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [x] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
PR has been merged into master. Closing.
