### ISSUE TITLE
[EPIC] MHV to VA.gov:MR: Remaining MR Domains: Review requirements for remaining domains

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#48890]
Review requirements in preparation for creating low-fi designs for the following domains:

- [x] Clinical Notes
- [x] Health Issues
- [x] Vitals
- [x] Demographics
- [x] Allergies
- [ ] DoD Information
- [ ] Printable Reports

**Comment by MarciMcGuire** [comment]
Jonathan, do we need to leave this issue open?  Do you know what the plan is for Demographics?
