### ISSUE TITLE
[EPIC] MHV to VA.gov:MR: Admissions and Discharge: Usability testing & refinement

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#48897]

**Comment by rbsingleton** [comment]
Closing this in favor of [usability testing epic](https://app.zenhub.com/workspaces/mhv-on-vagov-research-644bfcfc77c2ba00146120d7/issues/gh/department-of-veterans-affairs/va.gov-team/57629)
