### ISSUE TITLE
[EPIC] MHV to VA.gov:MR: Lab and Tests: Low-fi design & refinement

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#48920]
### Low-fi designs for Labs and Tests

At this time, we plan to combine the following domains that are currently treated as distinct entities in the legacy application (subject to be adjusted based on usability testing results):

#### VA Lab Results
- Chemistry/Hematology
- Microbiology

#### VA Pathology Reports
- Surgical Pathology
- Cytology
- Electron Microscopy

#### VA Medical Images and Reports
- VA Radiology Reports 
- VA Medical Images

#### VA Electrocardiogram (EKG) Reports
- EKG Reports - note - these are no longer updated in VistA, but historical records are available.

The [domain brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/labs-and-tests/labs-and-tests-brief.md)with further details and examples is on GitHub

**Comment by rbsingleton** [comment]
![image.png](https://images.zenhubusercontent.com/62447f703e03001d353b1d23/b71e0715-3995-4dda-acaa-c5c4535e21a5)

**Comment by jonathanjnelson** [comment]
[Designs](https://www.sketch.com/s/0803544d-e78c-423a-a70e-7db01a9a31c7)
[Design brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/labs-and-tests/labs-and-tests-brief.md)
[Requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/cded6cd339d4bfbf01c1c6e5f1be3020c4d0fff9/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/requirements/requirements.md)
