### ISSUE TITLE
[EPIC] MHV to VA.gov:MR: Labs and Tests: Usability testing & refinement

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#48923]

**Comment by rbsingleton** [comment]
MR usability testing [ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/309) in research repo

**Comment by rbsingleton** [comment]
Usability testing for prototype with all medical records, not just labs and test. Using Sketch so will need future usability testing with users of assistive tech.

**Comment by rbsingleton** [comment]
Closing this in favor of [usability testing epic](https://app.zenhub.com/workspaces/mhv-on-vagov-research-644bfcfc77c2ba00146120d7/issues/gh/department-of-veterans-affairs/va.gov-team/57629)
