### ISSUE TITLE
Add Workflow to 686: "Report the death of a dependent"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4898]
## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for the death of a dependent so that I can maintain an accurate representation of my status with the VA.

## Goal
Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
- [Mockup](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/screen/e977555f-cb21-4dd7-b7bc-799478247b66/Add-Modify-Dependents-Report-Death-1A)
- There seems to be some overlap/other logics that take this workflow into potentially different directions: we want to ensure that is wholly complete
- Loop and list: adding another entity

## Tasks
- [x] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [x] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/11557#pullrequestreview-347599342

**Comment by micahchiang** [comment]
@jason-gcio - fyi, I removed the acceptance criteria for submitting a PR to `vets-json-schema`. @cohnjesse and I discussed this and agreed that all schema changes should, for the time being, be localized to `vets-website` to allow for building unit tests.
