### ISSUE TITLE
[FE] Complete Functional Testing/QA of eCheck-in Workflow with Travel Reimbursement

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48986]
## TO DO
Get test data & access to API in staging
Add 500 and 530 as stations to the allow list (NOTE: it is still TBD on whether we are doing facility or clinic level)

## Resources
[Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4249)
[Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/2134&group_by=cases:section_id&group_order=asc&display_deleted_cases=0) - See eCheck-in with Travel: MVP
[User Workflow](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=ud3aa760e30b39bcf436d4473)
 [Presentation wireframes](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/005790a0202eed0e984eb6e87c8d183d090d945f/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/9B61B462-73BA-45CF-ABA4-215FD07B6D5A?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&present=true&preview=false&sha=005790a0202eed0e984eb6e87c8d183d090d945f)

## Tasks
- [ ] [FE] Complete the *[Pre-Staging Review Functional Test Run - Frontend](https://dsvavsp.testrail.io/index.php?/runs/view/4292)* test run

**Comment by loripusey** [comment]
@benbrasso-agile6 @zach-park Can you insert a link to the final travel wireframes above when they are ready? Also, take a look at the mural that demonstrates the workflow and tell me if there are any issues with it. Thanks.

**Comment by benbrasso-agile6** [comment]
Reviewed workflow and added comments

**Comment by acrollet** [comment]
@brianseek @wullaski and I just went through the test cases in testrail - all passed that we were able to test, one is marked as blocked due to our inability to trigger a generic error on the BTSSS side. We can discuss during Monday's standup.

@loripusey @sarahknoppA6

**Comment by loripusey** [comment]
closing, thanks
