### ISSUE TITLE
Adding [Jeana Clark] to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#48981]
# Description

please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel) DONE!

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [[jeana.clark@adhocteam.us](mailto:jeana.clark@adhocteam.us)] as a full member.

She is joining the VA.gov Product Teams Forms Program!

**Comment by eunicegar** [comment]
done
