### ISSUE TITLE
Address the Issue that Page Refresh Wipes Data on Any Page (Modify Dependents)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4900]
## Goal
Research the issue where autofill works on staging but is breaking on refresh when local

## Tasks
- Attempt to reproduce
  - Check staging

## Acceptance Criteria
- [x] Define and document the issue in GitHub with some potential solutions if possible
- [x] Address the issue, make note of any blockers or out of scope items

## Things to Check ([Reference list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0cb404d836086dc1d73ebb4b0fa9cf0c501a1b67/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686FrontEndResearch.md)):
- When refreshing the page after problem #2, spouse information is removed from the review page, leaving only three sections. This also coincides with problem #1, the remaining three sections are blank.
- Using the browser back button allows you to go back, but all fields are empty. In order to regain your data, you have to use the URL to navigate to /disability-benefits/apply/dependents/, the start of the form, where upon you can click on continue application, thereby retrieving all of your existing data.

**Comment by cohnjesse** [comment]
It turns out this is expected behavior, the save in progress is set up so that it treats local environments differently and does not pre-fill on refresh. this is set based on logic inside `platform/forms/save-in-progress/RoutedSavableApp.jsx` . I have also verified that neither of the issues under things to check out happen on staging either.

**Comment by jason-gcio** [comment]
Made a note on the comment above in the [686 FE Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686FrontEndResearch.md)
