### ISSUE TITLE
Business intake form for VaProfile

### ISSUE THREAD

**Issue by ianveracity** [department-of-veterans-affairs/va.gov-team#49009]
## Your Details
1.  Ian McEwan ian.mcewan@va.gov
​
2.  VaProfile
​
## Notification Details
1.  Email
​
2.  When non deliverable or otherwise bad contact information given to system, alert the user they might benefit from logging into va.gov and checking their current contact information.
​
3.  Log into va.gov to update their contact information
​
4.   More accurate contact information.
​
5.  Vaprofile
​
6.  identification by data quality of invalid contact information
​
7.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
8.  Unknown
​
9.  TBD
​
10.  No for this
​
11.  TBD
​
12.  No date set yet.

**Comment by christy-tongty** [comment]
Hi @ianveracity, thanks for reaching out. Here's our [VA Notify Playbook.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9912628/VA.Notify.Playbook.pdf) for viewing where you will find information about our APIs and how to access them.  We'll set you up with access to our self-service UI, in our Staging environment, for template (content) creation. 

Besides you, are there other team members who would also need access?

**Comment by ianveracity** [comment]
Right now its just me, I will be doing the spike to take a look at the service, then I might have a need for others. 
Thank you.

**Comment by christy-tongty** [comment]
Sounds good. Thank you!

**Comment by christy-tongty** [comment]
Hi @ianveracity, here is our [SSUI (Self-service UI) - Staging](staging.notifications.va.gov) for template creation. 

You shall now be able to log in with your VA credential and when in it, on the top-right corner next to your name, you'll see your service portal name - "VA.gov". When in it, under "Notification templates for va.gov", there is a template created earlier in regards to bad mailing address email notifications. You may pause at this point and let us know if you can access without issues. 

We'll follow up in establishing the API  key. Thanks!

**Comment by christy-tongty** [comment]
^The link to Staging is: https://staging.notifications.va.gov/

**Comment by bevnobev** [comment]
Duplicate
