### ISSUE TITLE
(Samara) Update deployment announcement with Quality Checklist

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49012]
### Tasks:

- [x] Update the deployment announcement message with the new customer-facing quality checklist: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+Content+team+deployment+instructions

### Notes:
Link to announcement: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+Content+team+deployment+instructions

**Comment by SSimmorins** [comment]
Task completed.
