### ISSUE TITLE
Revised My Health landing page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#49026]

**Comment by rtwell** [comment]
[sketch comps](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa)

Design notes:
1. We would like to beef up our default link size to 19px (currently they render at 16). I have spoken with @artsymartha68 and @humancompanion-usds about piloting this approach on this page, and have their collective blessing. 
2. Chevrons right align on smaller screens, up to the `$medium-screen` breakpoint.
3. Icons are the same as we use elsewhere for the same products


Mobile
Desktop
