### ISSUE TITLE
Create message for when users hit appointment request limit (VAOS)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#4903]
## Story
When a user hits the appointment request limit, we need to create messaging letting them know that and they have two options: 
- Go to the appointment list view and cancel any outstanding requests that are older than X number of days 
- Or call the medical facility to request appointment and cancel older appointments. 

## AC
- [x]  @peggygannon Creates appointment limit message 
- [x] @rtwell and @markgreenburg review/approve message
- [ ] dev ticket created for implementation

**Comment by peggygannon** [comment]
@markgreenburg 
@rtwell 

Please see request message below. Can you let me know your feedback and if this would work? 

**You’ve reached the limit for appointment requests at this location** 
We can’t process this appointment request because you’ve reached the request maximum for this facility. You’ll need to schedule or cancel your open requests in order to request this appointment. To schedule or cancel your open requests: 

•	Go to [your appointment list](link to appointment screen) and cancel appointment requests older than [[TK number]] days, **or**
•	Call the medical facility to request this appointment

**Comment by rtwell** [comment]
are we still labeling appointment requests as "pending appointments"? if so, i'd like to make sure our language is consistent. so maybe it should be 

> • Go to [your appointment list](link to appointment screen) and cancel **pending  appointments** older than [[TK number]] days, or

does that make sense?

**Comment by peggygannon** [comment]
@rtwell yes, makes sense. I will update the message. 
Here is the updated message.. if all looks good I will create dev implementation ticket. 

**You’ve reached the limit for appointment requests at this location**
We can’t process this appointment request because you’ve reached the request maximum for this facility. You’ll need to schedule or cancel your pending appointments in order to request this appointment. To schedule or cancel your open requests:

• Go to [your appointment list](link to appointment screen) and cancel pending appointments older than [[TK number]] days, or
• Call the medical facility to request this appointment

**Comment by rtwell** [comment]
perfecto! lgtm

**Comment by peggygannon** [comment]
ok, thanks! Closing this issue. 

Dev implementation ticket is here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4946
