### ISSUE TITLE
AWS access for Bradley Bergeron

### ISSUE THREAD

**Issue by bradbergeron-us** [department-of-veterans-affairs/va.gov-team#49039]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Bradley Bergeron

### Your Email

bradley.bergeron@accenturefederal.com

### Team, Role, and Company of the target individual

Education Benefits and application VFS Backend Engineer

### Product Manager (PM) name and email

cesar.santiago@accenturefederal.com

### Product Owner (PO) name and email

tammy.hurley1@va.gov, Eddie.Ricks@va.gov

### Desired AWS Access

Requesting access to Dev instances to be able to properly create and link our mocked users to be able to sign in.

### Access Expiration

March 1. 2023

### Additional Notes

I'm requesting this access because we created a number of id.me test users that aren't properly mocked in v[ets-api-mockdata ](https://github.com/department-of-veterans-affairs/vets-api-mockdata)and only work on localhost. I would like to be able to link these test users to the mockdata repository which would require access to run a rails console on a dev instance. 

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ianhundere** [comment]
@bradbergeron-us hey Bradley, i don't see you on that vfs team roster. please start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html

**Comment by bradbergeron-us** [comment]
Hey @ianhundere I see myself on the VFS team roster link above on row 26.

**Comment by ianhundere** [comment]
oops

**Comment by ianhundere** [comment]
@bradbergeron-us correct, you most likely were added recently.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Requested access in dev approved
