### ISSUE TITLE
Build Health Apt Landing Page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#49046]

**Comment by batemapf** [comment]
@MarciMcGuire any issues with moving #51126 (`My Health: review some of the past designs and options for integrating the brand`) the only ticket that is part of this epic) to #49659 (`[SUPER EPIC] Health apartment UX Design and prototyping`) and closing this out?

**Comment by MarciMcGuire** [comment]
No issues at all!

**Comment by batemapf** [comment]
done!
