### ISSUE TITLE
Review health app auth changes

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#49067]
An engineer is having issues with auth when adding new code to vets-api. The person who picks this ticket up should review the branch to try and identify why the authentication issues may be occurring: https://dsva.slack.com/archives/CBU0KDSB1/p1667317029254339?thread_ts=1665669482.908009&cid=CBU0KDSB1

**Comment by bosawt** [comment]
closing this, it's been around since 4-ever
