### ISSUE TITLE
Supplemental Claims | Investigate and Fix/Implement Pre-fill data

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#49068]
Work with @Mottie to ensure that pre-fill is supported in supplemental claims.

Ticket will be further stubbed out after initial investigation to determine what is needed.

**Comment by kylesoskin** [comment]
PR in, just needs merged

**Comment by saderagsdale** [comment]
@kylesoskin @Mottie hey both - what's the next step on this one?

**Comment by Mottie** [comment]
This is done as far as I know.
