### ISSUE TITLE
Analytics Implementation or QA Support for [Platform Content Team]

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#49062]
Hello Analytics team!
The Platform team would like it if you could reconfigure the events in Google Tag Manager so that, moving forward, we can use google analytics to get lists of the links inside the documents on the Platform website AND the URLs that those link lead to. Right now, we only get lists of links, NOT lists of URLs.

For example, right now, using Google Analytics, we can see a list of links that looks like this:
<img width="424" alt="Screen Shot 2022-10-28 at 10 27 36 AM" src="https://user-images.githubusercontent.com/14806304/199268479-7fe9716a-fe14-4e89-b567-002e9ae54e3f.png">

Moving forward, we want to be able to see a list of URLs AND links that looks like this:
<img width="1250" alt="Screen Shot 2022-10-28 at 10 26 51 AM" src="https://user-images.githubusercontent.com/14806304/199268726-ab43a5a8-b1c9-4036-92ee-d2b677a82524.png">

Can you reconfigure the events in Google Tag Manager to make that happen? Thanks!

**Comment by michelle-dooley** [comment]
@laucon - does this [GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w224573768p240292331/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension2&explorer-table.rowCount=250&explorer-table-dataTable.sortColumnName=analytics.eventAction&explorer-table-dataTable.sortDescending=true/) give you the detail you are looking for?

**Comment by michelle-dooley** [comment]
@laucon - looks like you didn't have access.  I just added you, you should get an email.

**Comment by laucon** [comment]
yes! This is fantastic. Thank you

**Comment by michelle-dooley** [comment]
Great!!  Reach out if you need anything else.
