### ISSUE TITLE
Adding Jay Tanner to DSVA Slack

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#49060]
new user requests: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add [jtanner@pluribusdigital.com](mailto:jtanner@pluribusdigital.com) as a full member.
Jay is the Program Manager for the new identity product team.

**Comment by eunicegar** [comment]
done
