### ISSUE TITLE
DDL: Privacy, Security, Infrastructure, Readiness Review Questions

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#49079]
We need to answer the following questions and also update the information in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/630

## Questions

This list of questions is _not_ intended to be comprehensive. It _is_ intended to be comprehensively covered in a review.

#### Logs

* Are there any new logging statements? (FE or BE). This includes data sent to Sentry, Cloudwatch, Google Analytics, ...?
    * _A: Yes, we're logging errors to Sentry_
* What kinds of information are logged in the new logging? Is there anything that uniquely identifies a user (Personally Identifiable Information)?
    * _A: We're not including personally identifying information._ 

#### User tracking / identity

* Are there any new cookies?
    * _A: No._ 
* Are there any new uses of existing cookies?
    * _A: No._

### Security

* How are systems authenticating with one another?
    * _A: We rely on standard user authentication for vets-api_
* Is anyone bypassing any obvious built-in protections? (CSRF protection in form submissions, auto-escaping in FE template rendering systems, use of `innerHTML`)
    * _A: No._

#### Frontend

* Is anyone using `innerHTML`, or otherwise bypassing template rendering system protections like auto-escaping?
     * _A: No._
* Are there any new cookies?
    * _A: No._
* Are there any new uses of existing cookies?
    * _A: No._

#### Backend

* Are there any new REST endpoints exposed by `vets-api`, or new behavior change on existing endpoints?
    * _A: GET /v0/claim_letters & GET /v0/claim_letters/[Document_ID]_
    * What new interactions are allowed?
        * _A: GET requests_
            * A) _return a JSON list of available efolder documents for the logged in user, and_
            * B) _return a specific PDF when provided with a document_id_
    * Is there any new risky data being sent to `vets-api` (XML, file uploads, etc.)?
        * _A: No._
    * How could this endpoint be misused?
        * _A: We've taken steps to make sure a document_id cannot be used if it is not a part of the set of documents available to the logged in user. This prevents manual manipulation of the document_id to see unauthorized documents_
* Are there new integrations with VA backends? _A: No._
    * What data are we sending to this backend?
    * How could this backend integration be misused?

#### Traffic

* How much new traffic are you expecting to send to `vets-api`?
    * Consider both average (typical weekday traffic) and burst (e.g. an email blast to Veterans)

#### Rollout

* What's your rollout plan? Specifically:
    * What % of users are you rolling out to at each phase?
    * What metrics are you looking at before deciding to continue rollout?

#### Incident response

* Is there a playbook for investigating and handling likely failure modes?
* Are there new integrations with VA backends?
    * What is this backend's latency/availability profile?
    * Do we have points of contact for each new backend, in case of outages or security incidents? (TODO: link to where these should be stored/documented)

#### SLO definition

*Note: tentative while SLO infrastructure work is underway*

* Are there any new REST endpoints exposed on `vets-api`?
    * Do all new endpoints exposed on `vets-api` have availability + latency expectations?
    * Are those expectations configured in our SLO monitoring system? (TODO)

**Comment by samcoforma** [comment]
Just want to add that we should look into DataDog as well, since that was recommended by @cohnjesse
