### ISSUE TITLE
Investigate VA OCC Mobile Staging Error

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#49071]
https://staging.va.gov/sign-in/?application=vaoccmobile&redirect_uri=%2Fmyvaimages%2F&oauth=true

I think this should be defaulting to false

**Comment by brucehendrickson** [comment]
I'm passing a work around to our testers to manually update the URL (true to false) and refresh in the interim.

We are allowed to use the login options from then on.
