### ISSUE TITLE
Adding Kevin Duensing to DSVA Slack

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#49085]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add/re-activate Kevin Duensing [kevin.duensing@adhocteam.us](mailto:kevin.duensing@adhocteam.us) as a full member. He was deactivated after moving off of his last team. He is now on the Benefits Tools team needs access to Slack for communicating with the benefits team, other VA teams, and Product Owners.

Please add him to the following channels:
benefits-team-1

**Comment by eunicegar** [comment]
done

**Comment by kjduensing** [comment]
@eunicegar Hi there. After trying to sign in to the slack workspace at dsva.slack.com, I was sent an email with this text:

> You recently tried to sign in to Digital Service @ VA, but it looks like your account for that workspace is deactivated.

How can I help get my account reactivated? 

Thanks!

**Comment by eunicegar** [comment]
I have activated your account @kjduensing

**Comment by kjduensing** [comment]
Thanks! Just got the invite.
