### ISSUE TITLE
Add a Workflow for 686: "Report the marriage of a child under 18"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4908]
## User Story
As a veteran, I want to use the 686c to report the marriage of a child under 18, so my disability benefits information is reported accurately. 

## Considerations
- [Mockup for workflow](https://xd.adobe.com/view/0f7759a1-b990-4d71-50c9-138d9e593fd0-7946/screen/dba0e2aa-ee9f-42ec-9414-806c58b1695b/Apply-Dependents-Report-Child-Marriage-1B)
- [Corresponding paper form section](https://www.vba.va.gov/pubs/forms/VBA-21-686c-ARE.pdf)

## Tasks
1. Add the workflow for reporting the marriage of a child to the existing 686c form.

## Definition of done
- [ ] The section has been added and maps correctly to the paper form.

**Comment by micahchiang** [comment]
PR into `vets-website` - https://github.com/department-of-veterans-affairs/vets-website/pull/11520

PR into `vets-json-schema` - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/373

**Comment by micahchiang** [comment]
Merged the above `vets-website` PR.

**Comment by micahchiang** [comment]
merged the above `vets-json-schema` PR
