### ISSUE TITLE
Unit Test for Workflow: "Report the marriage of a child under 18"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4909]
## Goal
Write and complete a unit test for the workflow mentioned above.

## Considerations
- Implement items from previous unit test tickets.
- Use some existing unit test as a model.

## Acceptance Criteria
- [x] 80% coverage for the workflow has been achieved.

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/11708
