### ISSUE TITLE
Add Workflow to 686: "Report That a Child 18 or Older Has Stopped Attending School"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4910]
## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for a child 18 or older has stopped attending school so that I can maintain an accurate representation of my status with the VA.

## Goal
Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
- [Mockup](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/screen/ca28116a-bcfe-4016-a123-8a96bdad53d0/)
- There seems to be some overlap/other logics that take this workflow into potentially different directions: we want to ensure that is wholly complete
- Loop and list: adding another entity
- Located in Section 8 of the 686

## Tasks
- [ ] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [ ] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/11773
