### ISSUE TITLE
Unit Test for Workflow: "Report the death of a dependent"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4912]
## Goal
Write and complete a unit test for the workflow mentioned above.

## Considerations
- Implement items from previous unit test tickets.
- Use some existing unit test as a model.

## Acceptance Criteria
- [x] 80% coverage for the workflow has been achieved.

**Comment by micahchiang** [comment]
I'm pulling this into the in progress column. I decided to include these in the PR for #4898 since that ticket is waiting on a PR to merge. 

The new file can be found [here](https://github.com/department-of-veterans-affairs/vets-website/pull/11557/files)
