### ISSUE TITLE
Configure our vets-api module to handle the 10-10d submission

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49126]
### Description

Since we are digitizing the 10-10d form in the forms-library, we need to configure our vets-api module to accept the form submission from vets-website. This may have already been completed or mostly completed with the digitization in the VAFSC.

### Definition of done

- [x] The vets-api forms_api module accepts the 10-10d submitted payload

**Comment by gmrabian** [comment]
update: getting help from Charley on this - successfully submitting from frontend to backend but the `.json.erb` mapping is not working as expected

**Comment by gmrabian** [comment]
This task is done, now that I've reread it and added a definition of done. The API layer is able to accept a 10-10d payload. The
