### ISSUE TITLE
Map 10-10d submission data to a PDF in vets-api module

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49127]
### Description

After configuring our module to accept 10-10d data from vets-website, we should take the necessary steps to generate a PDF from the submission data to be able to submit to central mail.

**Comment by gmrabian** [comment]
update: we have proof of this working via tests. still working to confirm via a local instance

**Comment by gmrabian** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/11615

**Comment by gmrabian** [comment]
VA Platform support request following up on PR: https://dsva.slack.com/archives/CBU0KDSB1/p1674573207309899

**Comment by gmrabian** [comment]
merged!
