### ISSUE TITLE
Nessus Scan Findings/POAM [11/08/22]

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#49139]
- [ ] Keep communication up with Phil on POAM creation.

**Comment by ahicksfearless** [comment]
I emailed Phil and forwarded the Nessus Scan findings on 11/2 to see if we need any POAMs created or if they are already in the works.

**Comment by lindsay-insco** [comment]
@jwowk to follow-up on confirming POA&M remediation

**Comment by lindsay-insco** [comment]
Resolved.
