### ISSUE TITLE
Configure 10-10d submission to vets-api in vets-website

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49135]
### Description

Generally, this is the final step in the form digitization process, but a lot of the work will be handled with the completion of the other stories,

**Comment by gmrabian** [comment]
@ndsprinkle I think this is done, right?

**Comment by ndsprinkle** [comment]
Yeah, I'll close it out. Everything 10-10d related should be fine to close now.

**Comment by ndsprinkle** [comment]
Well, except the documentation ticket and the nested forms ticket (for when we want to investigate nested forms later)
