### ISSUE TITLE
Update CSPID constants in SiS

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#49169]
### Issue Description
The SiS currently uses several different ways to compare against CSP types: writing out the string (`logingov`, `idme`, etc.) and referring to the `SAML::USER` (SSOe-based) constants can both be found. These CSPIDs should be included in the SiS constants directory & implemented throughout SiS code.

**Comment by alyssagallion** [comment]
Production deployment today.
