### ISSUE TITLE
Someone audit getting started section

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#49168]
Tasks:

- [x] Review each page under this section: https://depo-platform-documentation.scrollhelp.site/getting-started/

-  There are 21 total pages
-  7 have already been audited
-  There are 14 pages remaining that need auditing

- [x] Any pages with links to unpublished versions of the website (Confluence URLs, instead of the scroll viewport URL will be documented in the spreadsheet below:

Google spreadsheet: https://docs.google.com/spreadsheets/d/1h3Etep81sRK4_C88SOPZ2e0IeTFHE3KQp9qJJV53kMk/edit#gid=252229441

Instructions:

- DO NOT AUDIT PAGES UNDER "PRODUCT DIRECTORY"
- Pages without any Confluence links should be documented in the "Getting Started" tab
- Pages with Confluence links should be documented in the "docs that have confluence links" tab

**Comment by taylojill** [comment]
11/14/22 - Audit completed.
