### ISSUE TITLE
[11/08/22] Review Updated SOP Templates

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#49173]
- [x] Review updated templates due to the NIST 800-53 Rev. 5 transition

- [x] Discuss next steps at 11/8 ATO meeting

[SOP Templates](https://dvagov.sharepoint.com/sites/OITCRM/SOP%20Templates/Forms/AllItems.aspx?xsdata=MDV8MDF8fDU0NzFkN2Y5NTQxZDQ1MjlhZDhlMDhkYWJjZTUxZjE0fGU5NWYxYjIzYWJhZjQ1ZWU4MjFkYjdhYjI1MWFiM2JmfDF8MHw2MzgwMjk5ODk0ODEzMjgwMTR8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2TldNM056SmxNemN0Wmpaa01DMDBaR015TFdGaU5tRXRZakkwWWpSa01HSXdaak16WHpjMk56VTRaalExTFRoak5XUXRORGhpTnkxaE5tSTVMV0kxTkRabU9ETTVPR1JpWWtCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=SWZCMElNaEFSUTR5SjJTajF0bjhKLzF2VmI2Z0kzRUJvMyszcnZWQVBDQT0%3D&ovuser=e95f1b23-abaf-45ee-821d-b7ab251ab3bf%2CAriel.Hicks%40va.gov&OR=Teams-HL&CT=1667402379004&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjEwMTQwNjMwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

[KSRev5 - Knowledge Service](https://dvagov.sharepoint.com/sites/OITOIS/KnowledgeService/Pages/KSRev5.aspx?ovuser=e95f1b23-abaf-45ee-821d-b7ab251ab3bf%2cAriel.Hicks%40va.gov&OR=Teams-HL&CT=1667400379587&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjEwMTQwNjMwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3d%3d)

**Comment by lindsay-insco** [comment]
SOPs completed updates - pending upload into eMASS.
