### ISSUE TITLE
Add shared secret for BIP Claims API to VA.gov dev/staging environment

### ISSUE THREAD

**Issue by bshyong** [department-of-veterans-affairs/va.gov-team#4918]
The Pensions Automation team is building work on vets-API that requires an integration with the BIP Claims API. This service requires a shared secret to access. 

The BIP Claims API team has given us a secret for their UAT environment that we need to integrate into vets-API in order to use the service.

cc @jjulian

**Comment by jbritt1** [comment]
Requesting the secret be shared via https://onceler.app.cloud.gov/.

**Comment by jbritt1** [comment]
Secret added to credstash as requested. Title of credstash entry passed back to Ben.

**Comment by jbritt1** [comment]
Verified with requester to ensure this ticket was resolved in accordance with desired outcome. Eventually a prod key will be needed also. We can reopen this or start a new ticket and we will be happy to support.
