### ISSUE TITLE
AWS access for Holden Hinkle (AKA Emmerson Hinkle)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49190]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Holden Hinkle (AKA Emmerson Hinkle)

### Your Email

holden.hinkle@oddball.io

### Team, Role, and Company of the target individual

VSP Backend Support, Oddball, Inc.

### Product Manager (PM) name and email

Lindsey Hattamer

### Product Owner (PO) name and email

lindsey.hattamer@oddball.io

### Desired AWS Access

In addition to my current access, I need to be able SSM into instances of vets-api, prod.

### Access Expiration

ongoing

### Additional Notes

COR Name: Ray Wang

Access Expiration: `ongoing`, because I need access indefinitely for my role in Backend Support.

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ianhundere** [comment]
Platform Team Roster

**Comment by laineymajor** [comment]
@ianhundere do you know who we are waiting on approval from? I'd like to escalate.

**Comment by ianhundere** [comment]
@laineymajor approvals happen every Thursday by either @td-usds or @mchelen. there is no avenue for escalation.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Pinged VOR

**Comment by td-usds** [comment]
approved
