### ISSUE TITLE
Adding [Tammy Hurley and Eddie Ricks] to DSVA Slack

### ISSUE THREAD

**Issue by RileyRPM** [department-of-veterans-affairs/va.gov-team#49208]
Education Users Tammy Hurley and Eddie Ricks need to become full members of DSVA slack.

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Tammy Hurley And Eddie Ricks are VBA Education Service Product Owners and need Full Member access to DSVA

Are you requesting to add an individual as a:

- Full member

Tammy and Eddie are both Product Owners for many VBA education products and need to collaborate with the Va.gov teams

We aim to complete slack requests within 24hrs.

- Please add [tammy.hurley1@va.gov] as a full member.
- Please add [eddie.ricks@va.gov] as a full member.

**Comment by RileyRPM** [comment]
I've further found out @eunicegar and @LEHigley that Eddie could potentially be a full member right now. I just checked in slack and it looks like he's good. Tammy, however, is a guest member with maybe some shared channels.

**Comment by LEHigley** [comment]
tammy is  now a full member

**Comment by RileyRPM** [comment]
Thanks @LEHigley !
