### ISSUE TITLE
Pharmacy - ScriptPro

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#49203]

**Comment by shanemelliott** [comment]
[https://app.zenhub.com/files/133843125/00c96a80-f5bb-4864-9bb8-ddb4feb979df/download](https://app.zenhub.com/files/133843125/00c96a80-f5bb-4864-9bb8-ddb4feb979df/download)

**Comment by shanemelliott** [comment]
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/5ba329cf-0987-41a9-9aaa-a382230873c5)

**Comment by lindsay-insco** [comment]
Done and deployed to staging but lack of access to staging environment. Potential resolution is to mock up API environment to test.

**Comment by jwowk** [comment]
Rob updated API, Justin to let ScriptPro know

**Comment by lindsay-insco** [comment]
In Production - On hold until April (Takes 4mos to deploy)

**Comment by jwowk** [comment]
Resuming testing on 4/17

**Comment by jwowk** [comment]
Moved to new board #573
