### ISSUE TITLE
10-10CG: Review Branch Service Lists

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#49215]
Quoted from Patrick:
> as you may recall, a new service branch — space force — was created a few years back. persons are now separating from the space force and applying for VA benefits and services. we've been asked to look for and update any content that mentions service branches (e.g., army, navy, etc...) to include space force.

We need to review any lists of service present in the 10-10EZ to ensure that Space Force is listed in there, as well as confirming if any branches are missing.

**Comment by hdjustice** [comment]
Check out National Guard, should it be here???
