### ISSUE TITLE
Rewrite Health travel benefits page 

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#4921]
- [ ] Page content needs to be updated and sent to SME(s) for approval.
- [ ] Drupal page needs to be updated and approved by SME(s)

Current URL | Redirected to | Corrected Redirect
-- | -- | --
www.va.gov/HEALTHBENEFITS/vtp/beneficiary_travel.asp | /health-care/get-reimbursed-for-travel-pay/ | I don't believe this page is live yet

**Comment by lunascoop** [comment]
### Related commentary from ticket 4334 (now closed):

**Anne 01/08/20:** (https://github.com/department-of-veterans-affairs/va.gov-team/files/4042043/Health.travel.main.with.resources-AH-2019.docx) @Karak888 @mnorthuis @lunascoop @jenniferlee-dsva  I just lightly edited this doc I had worked on last March with Danielle; cannot find the ticket it was initially assigned to, nor whether it went through SME review. To be on the safe side I recommend we send to the Health > Travel Benefits SMEs for review even if they saw it before. 
NOTE: The legacy page has tons and tons of info linked from it - brochures, datasheets, etc. and for now I've captured the most relevant information on this page if not every detail. Also there are sub pages on the legacy site - a link to actual contact people in various regions and their phone numbers that Veterans or families can call; a way to look up by state where the Transport van pickup sites, are etc. @mnorthuis  - do you know what we decided last year about content strategy for those supporting pages?

_Originally posted by @AnneHurley in https://github.com/department-of-veterans-affairs/va.gov-team/issues/4334#issuecomment-572711594_

**Randi 01/12/20:** @AnneHurley @lunascoop The beneficiary travel page was redirected to the new URL but that page isn't live yet (see Anne's comment above), so we are getting a broken link on this page: https://www.va.gov/health-care/about-va-health-benefits/

_Originally posted by @RLHecht in https://github.com/department-of-veterans-affairs/va.gov-team/issues/4334#issuecomment-573673419_

**Comment by RLHecht** [comment]
@lunascoop and @AnneHurley is this ticket different from #4804? I'm confused.

**Comment by lunascoop** [comment]
Closing ticket as this is a duplicate effort of ticket #4804 .
