### ISSUE TITLE
Modify Tome Sync output to include metatags

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#4922]
## Problem Statement
The current `tome-sync` output doesn't include metatags. 

## Acceptance Criteria
- [x] The metatags are in the CMS Data Export
- [ ] The image path has the right base path, e.g. 

The red is what's in the tome-sync export, the green is from the GraphQL query.

![image](https://user-images.githubusercontent.com/1504756/72479335-07517100-37a9-11ea-9bcf-9c5858813911.png)

**Comment by cvalarida** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/86613404a59b6a11ea2e3a8cfd9a457f14b65c92/src/site/stages/build/process-cms-exports/tests/entities/node.0b130154-df25-4284-a561-f5370d589ffd.json#L94

**Comment by ElijahLynn** [comment]
This is done now in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/827.
