### ISSUE TITLE
Review Section data in simple forms

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#49220]
- [ ] Start to audit "Veterans Information" Section
    - [x] How many audited forms have such a section
    - [x] How varied are they
    - [ ] Identify what might need to be updated to match the design system

**Comment by jeana-adhoc** [comment]
Here's my initial review of "Veterans Information" in the 44 Simple forms that were originally identified. ([Google sheet](https://docs.google.com/spreadsheets/d/1wZOYpINt1bBt5z9Jt6EAMhBXTyQfW29zAZ3tnl2hM88/edit?usp=sharing))

TLDR;
25 out of the 44 forms asked "Veterans Information" Of those 25 forms, the breakdown of fields went like this:
25	Names (in some configuration)
21	SSN (in some configuration)
19	VA File # 
16	DOB (in some configuration)
16	phone number (in some configuration - including daytime/evening)
15	Mailing Address (in some configuration)
14	Email address
8	Veterans Service Number
6	I agree to receive electronic correspondence from VA in regards to my claim.
3	Claim Numbers
2	Place of Death
2	DOD (in some configuration)
2	VA Insurance File
2	Branch of Service (in some configuration)
2	International phone
1	Is veteran deceased
1	Did veteran die while on active military service
1	Military service verified
1	Date of Marriage
1	Physical Address
1	Planned Mailing address

(In some configuration = sometimes the form asked for data broken up like 3 fields for SSN, and other times it was all in one field)

I think it's going to be challenging to build some sort of consistent "Veterans Information" block that benefits most forms. Each form seems to vary quite a bit. But, perhaps a baseline component would only contain the first 7 items (Name, SSN, VA File #, DOB, Phone, Mailing address, email address)

Next step is looking at the design system and plain language guidelines to see how these might need to be updated.
