### ISSUE TITLE
Investigate id.me dslogon credentials missing 'dslogon level of assurance' value

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#49221]
https://vagov.ddog-gov.com/logs?query=%27dslogon%20level%20of%20assurance%27&cols=host%2Cservice%2C%40message%2C%40named_tags.remote_ip&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1666828304081&to_ts=1667433104081&live=true

Most of the dslogon logins through Sign in Service are missing a 'dslogon level of assurance', so we set these to `loa1`, even when they should be `loa3`. It also makes their `UserVerification` inaccurate, as we are unable to correlate their dslogon uuid (`edipi`)

**Comment by bosawt** [comment]
This is seeming to be an issue with the production `dslogon_loa3` scope. I'm not seeing evidence of any auth attempt with that scope returning with appropriate dslogon data

**Comment by bosawt** [comment]
Currently we are asking ID.me to investigate and determine what's going on with the production `dslogon_loa3` scope

**Comment by bosawt** [comment]
Currently we are asking ID.me to investigate and determine what's going on with the production `dslogon_loa3` scope

**Comment by joeniquette** [comment]
we switched to the `dslogon` scope to resolve this issue for now. Closing until IDme comes back with a solution.
