### ISSUE TITLE
MVP Urgent Care Part 2

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4924]
## User stories
As a veteran, I need to be able to search for an urgent care facility so that I can seek care.
As a veteran, I need to be able to search for an urgent care pharmacy so that I can have my urgent care prescription filled in my community.

## Objectives or Key Results this is meant to further
Improve the Veteran Search Experience (Veterans have the information they need to be prepared for an urgent care visit. )
Reform Community Care Implementation

## Acceptance Criteria

**This issue builds on the code changes already merged as part of [#4872].**

[Invision prototype](https://vsateams.invisionapp.com/share/EZVJMETDFTK

### Addition of urgent care and pharmacies to search feature

 [ ] The **Facility Type** dropdown includes the following:

> - VA health
> - Urgent care _(new addition)_
> - Community providers (in VA’s network) _(label change)_
> - VA benefits
> - VA cemeteries
> - Vet Centers
> - Community pharmacies (in VA’s network) _(new addition)_

When **Facility type** = "Urgent care"
[ ] Service type drop down is available, with the following choices:
> VA urgent care
> Community urgent care providers (in VA’s network)
[ ] Service type drop down defaults to VA urgent care

When **Facility type** = "Urgent care" and **Service type** = "VA urgent care"
[ ] Results should include only VA urgent care facilities from Facilities API

When **Facility type** = "Urgent care" and **Service type** = "Community urgent care providers (in VA’s network)":
[ ] Results should include only Community Care (In Network) locations (PPMS Place of Service 17 and 20)

When **Facility type** = "Community pharmacies (in VA’s network)"
[ ] Results should include only Community Care pharmacies
[ ] Service type drop down is unavailable.
[ ] Assistive device users are not prompted to enter a value for "service type" when In VA Network urgent care pharmacy is selected.

### Addition of urgent care and pharmacies labels to cards 

[ ] Results will be linked between list and map

Cards for **VA urgent care** (Facilities API) locations will be similar to existing functionality for VHA locations and include:

> Distance
> Type of Facility: URGENT CARE
> Name of Facility (linked to Facility Detail page or Facility page as governed by VAMC Pittsburgh logic)
> Address
> Directions
> Main Phone Number
> Mental Health Phone Number

**Community urgent care providers (in VA’s network)** (Community Care- urgent care facilities (non-pharmacy)/PPMS) cards should include the following information: 

> Distance 
> Type of Facility: URGENT CARE (if POS code = 20), RETAIL/WALK-IN CARE (if POS code = 17)
> Care Site Name
> Address
> Directions
> Main Phone Number
**NOTE:** This facility type WILL NOT link to Facility Detail page

**Community pharmacies (in VA’s network)** (Community Care/PPMS) cards should include the following information:

> Distance
> Type of Facility: COMMUNITY PHARMACY (IN VA'S NETWORK) 
> Care Site Name 
> Address
> Directions
> Main Phone Number
**NOTE:** This facility type WILL NOT link to Facility Detail page

All other facility types will maintain existing functionality

All mention of Urgent care PDF has been removed as the decision per OCC (1/27/2020) is that this is no longer needed for MVP. OCC will develop web page to handle content.

**Comment by arickalewis1** [comment]
[FL-MVP-Card-Types.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4119731/FL-MVP-Card-Types.pdf)
[FL-MVP-Search-Flow-Content.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4119733/FL-MVP-Search-Flow-Content.pdf)

Attaching card types and the content for drop downs

**Comment by tlei123** [comment]
@mmiddaugh @arickalewis1 , I have some quesitons re. the Part 2 changes/additions:

1. Is **VA Community Care (In network)** going away?  It's not listed under Acceptance Criteria above, but it does appear in the [InVision Prototype](https://vsateams.invisionapp.com/share/EZVJMETDFTK#/screens/400664664). 
1. **Non-VA urgent care pharmacies** \[listed under Acceptance Criteria above] appears as **VA
Community Care pharmacies (In network)** in the Invision prototype.  Which one is correct?

I'm almost done finalizing the test-cases for Part 2, just need the answers above before finalizing and requesting final-review.

Thanks much!

cc @brangi

**Comment by mmiddaugh** [comment]
@brangi this issue has been updated with label changes
Non-VA health -> Community providers (in VA’s network)
Urgent care + Non VA-health -> Urgent care + Community urgent care providers (in VA’s network)
Non-VA urgent care pharmacies -> Community pharmacies (in VA’s network)

**Comment by mmiddaugh** [comment]
@tzelei the comment immediately above this one confirms the intended labels. 

In short, there was negotiation between stakeholders on the preferred language to be used and it changed several times during the design and development process. 

Please let me know if anything is still less than clear. Thanks for your patience!

**Comment by tlei123** [comment]
> @brangi this issue has been updated with label changes
> Non-VA health -> Community providers (in VA’s network)
> Urgent care + Non VA-health -> Urgent care + Community urgent care providers (in VA’s network)
> Non-VA urgent care pharmacies -> Community pharmacies (in VA’s network)

@mmiddaugh, I think I got it, but ust wanna confirm my understanding visually [referencing the [prototype](https://vsateams.invisionapp.com/share/EZVJMETDFTK#/screens/400664664) screens] -- let me know if I got them right: 

**Facility-type label-changes**:
![urgent-care-mvp2-label-changes-1](https://user-images.githubusercontent.com/587583/73988294-7ed57480-48ff-11ea-9b53-b7448ec949f9.png)

**Urgent-Care service-type label-change**:
![urgent-care-mvp2-label-changes-2](https://user-images.githubusercontent.com/587583/73988299-839a2880-48ff-11ea-85ad-ebacc3a525f7.png)

Please let me know if I got it right.  Thanks much!

Sorry, lost Internet here for a few hours this afternoon, but I'll check back here tmrw (Fri) morning for your confirmation and finalize my test-cases.

**Comment by mmiddaugh** [comment]
You got it, @tzelei!

**Comment by tlei123** [comment]
@mmiddaugh , here's are my [finalized test-case](https://dsvavsp.testrail.io/index.php?/runs/view/131&group_by=cases:section_id&group_order=asc) for your review.

Thx much for the confirmation!

**Comment by mmiddaugh** [comment]
@tlei123 can this be closed?

**Comment by tlei123** [comment]
Yep.  Closing now.
