### ISSUE TITLE
[FE] Onsite Notifications: Remove Notifications Header when there is an error

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49256]
## Background
When there is any sort of backend error with onsite notifications that prevents us from displaying the notifications we should not show the Notifications section at all for those users.

## Tasks
- [x] Update error state for onsite notifications to not display when there is a backend error
- [x] Validate

## Acceptance Criteria
- [x] The notifications section does not show when there is any sort of backend error with onsite notifications

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Not sure how or if we can trigger an error to validate this. Provide screenshots

**Comment by tmitchellgcio** [comment]
just merged give it about 30 min

**Comment by ericasauv09** [comment]
validated with user 11, saw the notification then I blocked the notify URL to trigger the error and reloaded the page and the notification section no longer appeared.
